### ISSUE TITLE
Unable to compile using 'python3 setup.py build'

### ISSUE THREAD

**Issue by arkokoley** [kovidgoyal/kitty#1]
I get this error at the end. 

```
In function ‘glfw_wait_events’:
/home/arkokoley/code/kitty/kitty/glfw.c:166:10: error: implicit declaration of function ‘glfwWaitEventsTimeout’ [-Wimplicit-function-declaration]
     else glfwWaitEventsTimeout(time);
```

**Comment by kovidgoyal** [comment]
You need glfw-dev >= 3.2 installed. IIRC some linux distros only have older version of glfw. On my system with glfw-3.2.1 that function is in the file /usr/include/GLFW/glfw3.h

**Comment by arkokoley** [comment]
Ubuntu 16.04 has only the glfw-dev version "3.1.2-3", hence this won't compile. Thanks :)
