### ISSUE TITLE
Broken cursor highlight definition in neovim

### ISSUE THREAD

**Issue by marekkon** [kovidgoyal/kitty#100]
Highlight definition for Cursor in neovim colorscheme doesn't affect cursor color. It is the same color as that defined in the kitty's configuration file.

OS: Arch Linux
Kitty: latest
Neovim: 0.2.0

**Comment by kovidgoyal** [comment]
I dont use neovim, so I have no idea what it uses to change cursor color. But kitty uses the OSC codes documented here: http://invisible-island.net/xterm/ctlseqs/ctlseqs.html

You can test that by doing, for example

printf '\033]12;red\007'

which will turn the cursor red. neovim probably needs to be configured/modified to emit the correct OSC codes for cursor color
