### ISSUE TITLE
ibus input woes: bad pre-edit text position after commit

### ISSUE THREAD

**Issue by martinetd** [kovidgoyal/kitty#1000]
As you're aware there are a few problems with the ibus input, but unfortunately I kind of need it for Japanese (no, compose really doesn't cut it ;))

I've sent a PR for the first problem that really annoyed me as it was happening quite often, but I have another problem closer to kitty you might be of good advice for.
Basically, the pre-edit text position can be positioned wrongly if it's open immediately after a commit - e.g. since the commit only schedules a write, if by the time the next key is typed the write hasn't happened yet, the preedit text will be displayed first where the cursor was before the commit and then the previously-committed text will be displayed after the preedit overlay.　From there on things get quite ugly :)

I think the simplest fix to that would be to delay the displaying of the ime pre-edit overlay until the schedule write is over; we can still process text input and send it to ibus etc but just not display it until we know where to place ourselves?
Ideally it would be better to display the window in the right place but I don't think that's quite possible; we *could* try to display the preedit text where the cursor is then on the actual committed text write notice there is a pre-edit window and write over it then redisplay the pre-edit window but I'm afraid that would flicker and think it's best to just delay the display rather than flickering.

What do you think?

Implementation-wise I'm not sure, an easy way out would be to call `write_to_child` ourselves in/before `update_ime_position` but then that won't continue processing input like I said we would; we need to check if there is pending data and if there is mark the ime overlay "to be displayed" somehow, and let the io loop handle that...?

**Comment by kovidgoyal** [comment]
If I understand the issue correctly, I dont think this is solvable. This is because writing to the child is fundamentally asynchronous. Just because kitty finishes the write_to_child does not mean the kernel has actually written to the child and the cursor movement/text echoing bytes have been received by the input side of the tty. Basically there is no way that I know of to guarantee that the result of a previous commit will not appear in the middle of the next pre-edit. 

But maybe I am misunderstanding something.

**Comment by martinetd** [comment]
No, I think you understood this correctly.
Basically even if kitty has written to the shell's input, there is a delay until that shell reads the input and moves the cursor; so waiting is not a solution.

I guess that means we need to go for the flickery way and display the new text coming in the right place over the pre-edit overlay, then redraw the pre-edit overlay in the new position... I'll look for something in that direction

**Comment by kovidgoyal** [comment]
I think the approach should be that if a draw command is received (screen_draw is called) while a pre-edit is active, the pre-edit should be hidden, the draw command processed and the pre-edit re-shown after at the correct place.

**Comment by martinetd** [comment]
That sounds like a good way forward; thanks for the suggestion!
I'll have lots of disconnected time this weekend (yay cramped flying tincans), so will finally do the cleanup I promised and I'll play with this.

**Comment by kovidgoyal** [comment]
Planes are wonderful for getting boring work done :)

**Comment by page-down** [comment]
This issue should also have been resolved due to the recent improvements for IME.

**Comment by kovidgoyal** [comment]
Indeed, closing. Ping me if it is not fixed in master.

**Comment by martinetd** [comment]
definitely improved, thanks for the heads up!
There's still some weird padding if typing while the shell output things (e.g. run `while sleep 1; do date; done` in a loop and type through ibus), but I don't actually do this normally and it didn't actually lose any character so it's pretty good.

Can't compare to three years ago :)

**Comment by kovidgoyal** [comment]
run kitty with

kitty --dump-commands

see what commands are being sent to kitty by the sheel, locate them in
screen.c and add MOVE_OVERLAY_LINE to the start of those functions and
you should be fine.
