### ISSUE TITLE
During selecting text with the mouse the focus jumps to the first window

### ISSUE THREAD

**Issue by binor** [kovidgoyal/kitty#1002]
This is especially irritating when using a fullscreen layout because I can't select anything anymore.

My setup:

MacOS: 10.13.6 (17G65)
kitty: 0.12.1.

**Comment by kovidgoyal** [comment]
Sorry, I dont understand/cannot replicate what you are saying. Steps I tried:

1) Run kitty with the tall layout
2) Open two kitty windows
3) Focus secnd window
4) Select text in the second window
5) Focus remains in second window

**Comment by binor** [comment]
I made a video to demonstrate what I mean. Hope it clarifies it.

[kitty-issue-1002-video.mov.zip](https://github.com/kovidgoyal/kitty/files/2407701/kitty-issue-1002-video.mov.zip)

**Comment by kovidgoyal** [comment]
So from that video, what I can see:

1) Selecting text in the second window works fine in the tall layout
2) When you switch to the stack layout and then try to select text the window switches under you

Is that correct? I cannot replicate that either using master. What version of kitty are you running? And can you provide a minimal kitty.conf to replicate it?

I tried with the following kitty.conf:
```
enabled_layouts tall,stack
```

I pressed kitty_mod+enter to create second window, selected text in it, then pressed kitty_mod+l to switch layouts, tried selecting text again and the window stayed in place

**Comment by binor** [comment]
> 1\. Selecting text in the second window works fine in the tall layout

Well, yes. But you can see the focus border jumping to the first window while dragging, and jumping back when dragging has finished.

> 2\. When you switch to the stack layout and then try to select text the window switches under you

That is correct.

I did a binary search in my config and got the problem narrowed down to this setting:

`focus_follows_mouse yes
`

When I set it to `no` things work fine again. I'm using kitty v0.12.1, installed via brew cask.
