### ISSUE TITLE
*_color settings should allow using colors from the terminal’s color scheme

### ISSUE THREAD

**Issue by amarshall** [kovidgoyal/kitty#1004]
It would be nice to be able to have all color configuration permit, e.g., “color1” (aka red) as the value that is then mapped to the appropriate color configured in the terminal (whether set by `color1` in `kitty.conf`, or via the appropriate escape codes). Of course, this includes through `color255`.

Some color settings include:

- `active_border_color`
- `cursor_text_color`
- `bell_border_color`
- `inactive_border_color`
- `url_color`

**Comment by kovidgoyal** [comment]
This is rather a lot of work, for relatively small benefit, because of the way rendering works in kitty. Not worth the effort for me, but patches are welcome.
