### ISSUE TITLE
Setting background_opacity to 0.0 does not make the area around characters transparent

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1005]
I was trying to implement a transparent background blur on macOS using `NSVisualEffectView`. For this to work, kitty needs to have a transparent background. When setting `background_opacity 0.0` in `kitty.conf` the text looks very bad:
![text transparent bright bg](https://user-images.githubusercontent.com/15217907/45916073-2d3e5e00-be60-11e8-9608-74c2267b6d11.png)
![text transparent dark bg](https://user-images.githubusercontent.com/15217907/45916071-257eb980-be60-11e8-8eaa-99c5047ece98.png)
This is roughly how I would expect it to look:
![expected](https://user-images.githubusercontent.com/15217907/45916084-67a7fb00-be60-11e8-8b35-6368885739d6.png)
Am I missing something or is this a limitation of the current text rendering implementation?

**Comment by kovidgoyal** [comment]
I dont have time to look at the code right now, but I suspect that is because the text anti-aliasing does not work with background opacity of 0. I suggest instead using a low but non-zero value.

**Comment by Luflosi** [comment]
The text anti-aliasing seems to get worse as the `background_opacity` approaches 0. I stacked five kitty instances with one window each on top of each other. Every kitty instance only has `background_opacity` set in `kitty.conf`. The value of `background_opacity` of the lowest (leftmost) window is `1.0` and the background is completely black. Every other window has at least some transparency, through which the black color of the lowest window is visible.
![blocky text](https://user-images.githubusercontent.com/15217907/45917458-e8bebc80-be77-11e8-88ba-fbdf80259af4.png)
As you may be able to see every window except the one with a value of `0.0` has at least some anti-aliasing going on although the text seems to expand in thickness as the opacity approaches 0 and an opacity value of 0.01 looks almost as bad as a value of 0:
0.01:
![0 01](https://user-images.githubusercontent.com/15217907/45917535-a1d1c680-be79-11e8-9369-bbf8f83369ab.png)
0.0:
![0 0](https://user-images.githubusercontent.com/15217907/45917536-a9916b00-be79-11e8-92c7-a3c93421769b.png)

**Comment by kovidgoyal** [comment]
I suspect the problem is that anti-aliasing works by mixing the foreground and background colors using a mixing function that is different than the mixing function used by the OS to blend pixels in the window buffer. I can' t think of a good way around that.

**Comment by Luflosi** [comment]
After playing around with the code a little, I found that making this change:
```diff
diff --git a/kitty/cell_fragment.glsl b/kitty/cell_fragment.glsl
index 689e2334..d7b31926 100644
--- a/kitty/cell_fragment.glsl
+++ b/kitty/cell_fragment.glsl
@@ -102,7 +102,7 @@ void main() {
     // SIMPLE
 #ifdef TRANSPARENT
     final_color = alpha_blend_premul(fg.rgb, fg.a, background * bg_alpha, bg_alpha);
-    final_color = vec4(final_color.rgb / final_color.a, final_color.a);
+    final_color = vec4(final_color.rgb, final_color.a);
 #else
     // since background alpha is 1.0, it is effectively pre-multiplied
     final_color = vec4(premul_blend(fg.rgb, fg.a, background), 1.0f);
```
makes anti-aliasing work again, although I don't understand the rendering process enough to know why.
The following screenshot is of kitty with a transparency of 0.0:
![It Works!](https://user-images.githubusercontent.com/15217907/48522974-d612a380-e87a-11e8-9967-b29910644493.png)
Although there are some weird side effects (that also occur without that change AFAICT; the following screenshots are without the modification), like selection not being properly shown, the filler area between where all the cells are and the window border being a slightly non-transparent white-ish color or black borders around everything when the window doesn't have focus:
![sideeffect 1](https://user-images.githubusercontent.com/15217907/48523182-ab751a80-e87b-11e8-9f51-333b31290f5b.png)
![sideeffect 1 different](https://user-images.githubusercontent.com/15217907/48523221-d6f80500-e87b-11e8-90ad-2c1955965f08.png)
![sideeffect 2](https://user-images.githubusercontent.com/15217907/48523240-e8411180-e87b-11e8-91ed-2dce59321ead.png)
But maybe that's for another GitHub issue.

**Comment by kovidgoyal** [comment]
does that actually work with values other than zero?

**Comment by Luflosi** [comment]
With a value of 0.5:
![0.5](https://user-images.githubusercontent.com/15217907/48538399-a97b7d80-e8b4-11e8-8a2d-eb2a461f4ea6.png)
0.9:
![0.9](https://user-images.githubusercontent.com/15217907/48538433-bbf5b700-e8b4-11e8-8855-f8d692cdb0b3.png)
0.95:
![0.95](https://user-images.githubusercontent.com/15217907/48538508-ffe8bc00-e8b4-11e8-87e0-c8a2c27a661d.png)
0.98:
![0.98](https://user-images.githubusercontent.com/15217907/48538549-1262f580-e8b5-11e8-8791-ad683d8fc997.png)
1.0:
![1.0](https://user-images.githubusercontent.com/15217907/48538646-476f4800-e8b5-11e8-924b-bf3a08b6c7bd.png)

**Comment by kovidgoyal** [comment]
Hmm odd, ok I'll take a look at it in more detail when I have a minute.

**Comment by sylv256** [comment]
I'm getting this bug again I believe (on swayfx w/ blur).

![Image](https://github.com/user-attachments/assets/f8ee1bbe-d7d8-471f-ae78-362bb69cd01e)

**Comment by kovidgoyal** [comment]
Dont see how you could be, since it has been fixed. Indeed that whole part of the code has been completely refactored and explicit workarounds were added precisely because compositors dont do correct alpha blending, see #6218 for details.
