### ISSUE TITLE
kitty crashes with BadRRCrtc 

### ISSUE THREAD

**Issue by daenney** [kovidgoyal/kitty#1006]
Kitty sometimes crashes after the display it's on has gone through a sleep->wake cycle (turned off the monitor or system comes out of standby).

This is what I end up with in the journal:
```
Sep 22 12:21:41 monoceros kitty.desktop[60717]: X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
Sep 22 12:21:41 monoceros kitty.desktop[60717]:   Major opcode of failed request:  140 (RANDR)
Sep 22 12:21:41 monoceros kitty.desktop[60717]:   Minor opcode of failed request:  20 (RRGetCrtcInfo)
Sep 22 12:21:41 monoceros kitty.desktop[60717]:   Crtc id in failed request: 0x20
Sep 22 12:21:41 monoceros kitty.desktop[60717]:   Serial number of failed request:  3225
Sep 22 12:21:41 monoceros kitty.desktop[60717]:   Current serial number in output stream:  3225
```

Environment:
* Kernel: 4.18.9-arch1-1-ARCH
* Wayland/wayland-protocols: 1.16
* GNOME Shell: 3.30 (this also happened on 3.28)
* Kitty: 0.12.1
* WAYLAND_DISPLAY=wayland-0
* XDG_SESSION_TYPE=wayland
* DISPLAY=:0

Possibly related, or not, I've been seeing these a lot in the journal too:

```
Sep 22 12:21:46 monoceros org.gnome.Shell.desktop[60717]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1a0000e (kitty)
```

**Comment by daenney** [comment]
This only seems to happen once, pretty quickly right after the sleep->wake cycle. It's unfortunate since that means any open terminal sessions are lost. When I start Kitty again it doesn't crash at all until the next display sleep->wake cycle.

**Comment by martinetd** [comment]
Sounds like gnome might destroy the output and create a new one with a different crtc... Not a fix but as a workaround you might want to try to export KITTY_ENABLE_WAYLAND=1 and use the wayland protocol instead of Xwayland, at the very least it won't have *this* problem (but it's not enabled by default, so I assume it's not perfect, I didn't try it for long)

**Comment by kovidgoyal** [comment]
dup of #700 

this is really a bug in glfw not kitty, but since I do lots of work on glfw anyway, I can look into fixing it, if you can generate a stack trace, as described, in #812

**Comment by daenney** [comment]
I don't think the Arch packages builds with debug so it'll take me a bit to rebuild that and trigger it.

As an aside, I tried out @martinetd's suggestion which seems to work but results in an always full-screen Kitty and with seemingly no way to resize it/no window controls. Is that intended?

**Comment by kovidgoyal** [comment]
wayland has this crazy design where every window is responsible for drawing its own window borders and glfw does not do that very well at the moment, so you might end up with no borders. https://github.com/glfw/glfw/issues/1257

**Comment by daenney** [comment]
Mmm, so I updated the PKGBUILD to do this instead: `python3 setup.py linux-package --debug --prefix ${pkgdir}/usr`. That should've built a debug version, correct? Or does that only work then the argument is `build`?

I installed it, launched Kitty, switched monitors on/off and Kitty was gone, but no core dump. What am I missing?

**Comment by kovidgoyal** [comment]
Kittyis really easy to just build from source. Checkout the source code, run

make debug

run kitty as

python3 .

and you should get a stack strace with

echo bt | coredumpctl gdb

make sure generating core files is enabled on your system (arch wiki will tell you how to do that)

**Comment by daenney** [comment]
From what I can tell, core dumps are enabled by default for Arch/systemd, and I haven't changed those settings.

I did the `make debug`, ran Kitty, did the monitor sleep dance and all I get is that same error as the original bug report and just the process having quit. I don't see anything in coredumps and coredumpctl doesn't list any either.

**Comment by kovidgoyal** [comment]
What exit code is it quitting with?

**Comment by daenney** [comment]
It exists with 1

**Comment by daenney** [comment]
Alright, so here's what I did:

```diff
diff --git a/glfw/x11_monitor.c b/glfw/x11_monitor.c
index ae7075cd..72c0f00d 100644
--- a/glfw/x11_monitor.c
+++ b/glfw/x11_monitor.c
@@ -150,8 +150,9 @@ void _glfwPollMonitorsX11(void)
                 XRRFreeOutputInfo(oi);
                 continue;
             }
-
+            printf("Before XRRGetCrtcInfo in _glfwPollMonitorsX11\n");
             ci = XRRGetCrtcInfo(_glfw.x11.display, sr, oi->crtc);
+            printf("After XRRGetCrtcInfo in _glfwPollMonitorsX11\n");
             if (!ci)
             {
                 XRRFreeOutputInfo(oi);
@@ -239,7 +240,9 @@ void _glfwSetVideoModeX11(_GLFWmonitor* monitor, const GLFWvidmode* desired)
             return;
 
         sr = XRRGetScreenResourcesCurrent(_glfw.x11.display, _glfw.x11.root);
+        printf("Before XRRGetCrtcInfo in _glfwSetVideoModeX11\n");
         ci = XRRGetCrtcInfo(_glfw.x11.display, sr, monitor->x11.crtc);
+        printf("Before XRRGetCrtcInfo in _glfwSetVideoModeX11\n");
         oi = XRRGetOutputInfo(_glfw.x11.display, sr, monitor->x11.output);
 
         for (i = 0;  i < oi->nmode;  i++)
@@ -290,7 +293,9 @@ void _glfwRestoreVideoModeX11(_GLFWmonitor* monitor)
             return;
 
         sr = XRRGetScreenResourcesCurrent(_glfw.x11.display, _glfw.x11.root);
+        printf("Before XRRGetCrtcInfo in _glfwRestoreVideoModeX11\n");
         ci = XRRGetCrtcInfo(_glfw.x11.display, sr, monitor->x11.crtc);
+        printf("After XRRGetCrtcInfo in _glfwRestoreVideoModeX11\n");
 
         XRRSetCrtcConfig(_glfw.x11.display,
                          sr, monitor->x11.crtc,
@@ -325,7 +330,9 @@ void _glfwPlatformGetMonitorPos(_GLFWmonitor* monitor, int* xpos, int* ypos)
         XRRCrtcInfo* ci;
 
         sr = XRRGetScreenResourcesCurrent(_glfw.x11.display, _glfw.x11.root);
+        printf("Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos\n");
         ci = XRRGetCrtcInfo(_glfw.x11.display, sr, monitor->x11.crtc);
+        printf("After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos\n");
         if (ci)
         {
             if (xpos)
@@ -362,7 +369,9 @@ GLFWvidmode* _glfwPlatformGetVideoModes(_GLFWmonitor* monitor, int* count)
         XRROutputInfo* oi;
 
         sr = XRRGetScreenResourcesCurrent(_glfw.x11.display, _glfw.x11.root);
+        printf("Before XRRGetCrtcInfo in _glfwPlatformGetVideoModes\n");
         ci = XRRGetCrtcInfo(_glfw.x11.display, sr, monitor->x11.crtc);
+        printf("After XRRGetCrtcInfo in _glfwPlatformGetVideoModes\n");
         oi = XRRGetOutputInfo(_glfw.x11.display, sr, monitor->x11.output);
 
         result = calloc(oi->nmode, sizeof(GLFWvidmode));
@@ -411,7 +420,9 @@ void _glfwPlatformGetVideoMode(_GLFWmonitor* monitor, GLFWvidmode* mode)
         XRRCrtcInfo* ci;
 
         sr = XRRGetScreenResourcesCurrent(_glfw.x11.display, _glfw.x11.root);
+        printf("Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode\n");
         ci = XRRGetCrtcInfo(_glfw.x11.display, sr, monitor->x11.crtc);
+        printf("After XRRGetCrtcInfo in _glfwPlatformGetVideoMode\n");
 
         if (ci) {
             const XRRModeInfo* mi = getModeInfo(sr, ci->mode);

```

```
make clean
make debug
```

```
python3 .
Before XRRGetCrtcInfo in _glfwPollMonitorsX11
After XRRGetCrtcInfo in _glfwPollMonitorsX11
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
[265 13:36:53.360254] [PARSE ERROR] Unknown OSC code: 7
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
After XRRGetCrtcInfo in _glfwPlatformGetVideoMode
Before XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
After XRRGetCrtcInfo in _glfwPlatformGetMonitorPos
Before XRRGetCrtcInfo in _glfwPlatformGetVideoMode
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x3cf
  Serial number of failed request:  1126
  Current serial number in output stream:  1126
```

So it seems to die in `_glfwPlatformGetVideoMode` after the monitor sleep->wake dance.

**Comment by kovidgoyal** [comment]
So it looks like the problem is somewhere in XWayland, XRRGetCrtcInfo is calling exit(1) when the crtc is invalid instead of just returning null. Dont know the best way to workaround that. Find some other xrandr function that can validate the crtc perhaps and call that first.

**Comment by daenney** [comment]
Should I file an issue with GLFW instead?

**Comment by daenney** [comment]
I took a look at libxrandr, can't see it calling exit there but it does a bunch of things, so I suppose it can be burried somewhere deeper. Any way to track this down on my side?

**Comment by kovidgoyal** [comment]
Feel free to file an issue with glfw, but glfw development is largely dead, so you aren't likely to get much movement from there. 

If you can build libxrandr from source, stick a  few prints in there and see where it is calling eit you might get further. Basically what we need is some function from libxrandr that will check if a crtc is valid that we can call before calling XRRGetCRTCInfo.

**Comment by daenney** [comment]
Looking at libxrandr I don't see anything related to validating the CRTC I'm afraid, so looks like that won't be an option.

Where should I stick the prints?

**Comment by martinetd** [comment]
It does `exit(1)` in `_XReply` which is in libX11, ultimately in `_XDefaultError`

If you set another handler with `XSetErrorHandler` you can get something else back, but it still means X11 considers that to be a fatal error..

**Comment by daenney** [comment]
That sounds an awful lot like there's no way to fix this.

**Comment by martinetd** [comment]
It's programming, there's always ways to fix anything, not necessarily all good ones though :p

That being said, I'm sure we can get some event from X that the crtc changed... XRRCrtcChangeNotifyEvent perhaps? if so you should see something in the `if (event->type == _glfw.x11.randr.eventBase + RRNotify)` check of `processEvent` in `kitty/glfw/x11_window.c`
If that's not the one I'd try to see if it's possible to just dump all the X11 events in some parsable format to see if there's anything about the Crtc we could use.

**Comment by daenney** [comment]
I'm totally up for trying this, but I'm not very familiar with C and aboslutely unfamiliar with the graphical parts of the linux desktop stack. If you happen to have a small patch I can apply, build and run I'm happy to do so.

**Comment by kovidgoyal** [comment]
Hmm from what I remember of glfw, basically there is a global list of monitors. So what would be needed would be to catch whatever event notifies us that a monitor is gone/crtc is invalid and reset the internal monitor references. That should take care of it. As far as I know glfw should be doing that already (see the handling of RRNotify event). So it seems RRNotify is not enough. Sadly, I am no X expert either (all I know about X I pretty much learned working on fixing bugs in glfw). It may be that if you run xev and do the sequence of steps to create the monitor removal it will tell us what other event we need to catch.

**Comment by kovidgoyal** [comment]
Although thinking about it, I dont know how X11 is supposed to work. How is it possible to ever guarantee that a client will not make requests about an invalid monitor in an asynchronous protocol. The client could send a request to the server for monitor information between the monitor being disconnected and the server sending the notification to the client.

**Comment by daenney** [comment]
Figured I'd circle back to this one... it's fixed itself. There's been some issues with the amdgpu driver but it looks like kernel 4.19 and an updated libdrm have gotten rid of whatever ailed it.

**Comment by kovidgoyal** [comment]
that's nice :) it's great when things fix themselves
