### ISSUE TITLE
Rendering issue on macOS 10.12.6

### ISSUE THREAD

**Issue by leonardt** [kovidgoyal/kitty#101]
Tried a couple of the `.dmg` releases (current and previous versions) as well as building from source.

<img width="1660" alt="kitty" src="https://user-images.githubusercontent.com/3766436/28834659-baa01368-7697-11e7-9a45-cb5160f83515.png">

Let me know if there's any commands I can run to help debug

```
❯ python3 . --version
kitty 0.2.7 by Kovid Goyal
```

Running with `--debug-gl` doesn't yield any messages.

Edit: appending some dependency info
```
❯ brew info python3
python3: stable 3.6.2 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python3/3.6.1 (3,712 files, 57.6MB)
  Poured from bottle on 2017-07-14 at 08:39:44
/usr/local/Cellar/python3/3.6.2 (3,728 files, 57.9MB) *
  Poured from bottle on 2017-07-20 at 09:13:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python3.rb
```
```
❯ brew info glfw
glfw: stable 3.2.1 (bottled), HEAD
Multi-platform library for OpenGL applications
http://www.glfw.org/
/usr/local/Cellar/glfw/3.2.1 (14 files, 286.5KB) *
  Poured from bottle on 2017-07-30 at 08:45:13
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/glfw.rb
```

**Comment by kovidgoyal** [comment]
Unfortunately, I dont have a mac capable of running kitty, only building it, so OS X issues are hard to debug. From your screenshot it looks like an issue with the graphics drivers on your machine? What graphics card does it have?

**Comment by leonardt** [comment]
Intel Iris Plus Graphics 650 1536 MB

**Comment by kovidgoyal** [comment]
Hmm, well I know that rendering does ot work on some older cards on macOS, but that is definitely new enough. Sorry dont have any other insight to offer.

**Comment by dprandzioch** [comment]
Anything new in this regard? I'm experiencing the same issue (having the same versions of both python and glfw) on 10.12.6.
![bildschirmfoto 2017-08-05 um 22 12 14](https://user-images.githubusercontent.com/4499821/28998443-51b93126-7a2b-11e7-9ef4-e529f5b01d22.png)

**Comment by kovidgoyal** [comment]
As far as I can tell this is caused by something in the opengl/graphics drivers. Unfortunately, I have no idea how to debug those on macs. kitty itself includes a --debug-gl flag that will print any failures reported by the OpenGL sub-sytem, but as per the OP there aren't any, which means the problem is likely lower down in the stack. 

If you are familiar with opengl you can try modifying the shaders kitty uses, which can be found it char_grid.py. Try stripping as much functionality from them as possible to see what rendering succeeds.

**Comment by TheMegaTB** [comment]
I got this issue as well with the Intel HD Graphics 615 and it appears that the cursor shader is working properly:
<img width="678" alt="screen shot 2017-08-13 at 11 02 00" src="https://user-images.githubusercontent.com/5037967/29248374-1458ff18-8017-11e7-8c1a-594a4dd90448.png">
Everything else is somewhat screwed up though. When typing it leaves a trail of ghost cursors in various shades of gray
<img width="579" alt="screen shot 2017-08-13 at 11 04 37" src="https://user-images.githubusercontent.com/5037967/29248385-3bb2a7d0-8017-11e7-8f83-485286180335.png">

**Comment by kovidgoyal** [comment]
Hmm, well you can check if the font glyphs are being rendered correctly by running

/Applications/kitty.app/Contents/MacOS/kitty -c "from kitty.fonts.coretext import *; develop()"

This will create a file /tmp/cell.data

This in turn can be viewed using the Pillow python library, with the following script:

```py
def display_bitmap(data, w, h):
    from PIL import Image
    img = Image.new('L', (w, h))
    img.putdata(data)
    img.show()

import pickle
show_bitmap(*display_bitmap(*pickle.loads(open('/tmp/cell.data', 'rb').read()))
```

On my OS X system (which cannot actually run the full kitty), this results in:

![screenshot_20170813_181037](https://user-images.githubusercontent.com/1308621/29249730-c4ff5340-8052-11e7-84e4-bdf4d2d4334c.png)


It renders different characters with both strikethrough and curly underlines which is why it looks so messy.

**Comment by kovidgoyal** [comment]
If the font glyphs are being rendered correctly then the culprit is most likely somewhere in the cell shader or in the OpenGL calls to upload texture data to the GPU. Unfortunately, it is hard to know where exactly. As I said the actual shaders are in char_grid.py and texture management code is in shaders.py.

**Comment by dprandzioch** [comment]
Is there any workaround for this / like some config entry or anything?

**Comment by koekeishiya** [comment]
I'm successfully running [this fork](https://github.com/koekeishiya/kitty) of Kitty on macOS Sierra (10.12.6) (NOTE: it has changes related to keyboard input to properly handle norwegian keyboard layout, breaks meta and shift-meta keys for US layouts).

I had rendering issues with some specific fonts, where the kerning would be wrong and deformed characters were rendered. The default font did work fine though, IIRC. I've successfully used the font *Input Mono* and I am currently using *Fantasque-Sans-Mono*.

Not sure if this matters, but I have the following (config](https://github.com/koekeishiya/dotfiles/blob/master/kitty/kitty.conf)

After running the build instructions, I drop the generated directories into a pre-built *kitty.app* from the official *dmg* installers, and fix the *rpaths* using [this script](https://github.com/koekeishiya/dotfiles/blob/master/kitty/kitty_rpaths.sh) (require editing of paths to be usable by other).

**Comment by kovidgoyal** [comment]
I'm pretty sure this is caused by missing OpenGL functionality in the graphics drivers for Intel cards. I have added a check for it: https://github.com/kovidgoyal/kitty/commit/a9f3a698d275bf13bbba440e95fc2e58748e370f

**Comment by kovidgoyal** [comment]
I changed the code to not use GL_ARB_texture_buffer_object_rgb32 as that is likely what is not available, it might help:

https://github.com/kovidgoyal/kitty/commit/101a50b0ff0584a08f80e110f562cd914a47945b

**Comment by dprandzioch** [comment]
Thanks for this. I built kitty from master but the error seems to still persist. Did anyone else have success with this? Btw. I have a MacBook 13,1 with Intel Iris Graphics 540 1536 MB.

**Comment by kovidgoyal** [comment]
Oh well, it was worth a try. Basically, It looks like support for texture buffer objects with intel drivers on macOS is broken.

**Comment by koekeishiya** [comment]
Kitty works perfectly fine for me though, on macOS Sierra 10.12.6.
Macbook pro Retina 15inch mid-2014 with Intel Iris Pro

Is there some other system information that I could provide to try and help clear up the requirements for Kitty to run on mac ?

**Comment by kovidgoyal** [comment]
I'm going to see if I can change kitty to use vertex buffer objects instead of texture buffer objects. That is older functionality so maybe that will fix it. It should have slightly better performance as well. 

Problem is I am not a mac user, so I have no intuition for what might be the issue.

**Comment by kovidgoyal** [comment]
THe code I committed to swith to using vertex buffer objects should have fixed this, as best as I can tell, but has introduced lots of latency into the rendering, I'll have to investigate why.

**Comment by kovidgoyal** [comment]
Latency fixed. Should be fine now. Let me know if it works.

**Comment by dprandzioch** [comment]
@kovidgoyal You're my hero of the day :-) It works!
