### ISSUE TITLE
Wrong keybindings inside programs

### ISSUE THREAD

**Issue by nicoulaj** [kovidgoyal/kitty#1010]
I want to use the <kbd>page up</kbd>/etc keys without a modifier, so I have this config:
```
kitty_mod     ctrl
map page_up   scroll_page_up
map page_down scroll_page_down
map home      scroll_home
map end       scroll_end
```

It works fine in the shell, but in curses programs such a `vim` or `less`, it works only with the modifier (<kbd>ctrl</kbd>+<kbd>page up</kbd>/etc).

Tested with bash and zsh.
Tested with xterm and terminator, <kbd>page up</kbd>/etc work in `vim` and `less`.

Is this the intented behaviour ?

**Comment by nicoulaj** [comment]
`TERM` is set to `xterm-kitty` and terminfo files are there (`/usr/share/terminfo/x/xterm-kitty`). I am using the Arch Linux [kitty package](https://www.archlinux.org/packages/community/x86_64/kitty/) (also tested on [kitty-git](https://aur.archlinux.org/packages/kitty-git/)).

I can reproduce the behaviour in a clean Debian testing virtual machine, using [Debian's kitty package](https://packages.debian.org/buster/kitty). Example steps to reproduce using Vagrant+VirtualBox:

1. create `Vagrantfile` with contents:

       Vagrant.configure("2") do |config|
         config.vm.box = "natx/debian-testing-amd64-desktop"
         config.vm.provider "virtualbox" do |v|
           v.gui = true
           v.memory = 2048
         end
       end

2. `vagrant up`
3. login as `vagrant`/`vagrant`
4. run `sudo apt update && sudo apt install kitty`
5. create file `~/.config/kitty/kitty.conf` with contents:

       map page_up   scroll_page_up
       map page_down scroll_page_down

6. launch `kitty`
7. run `find`:

    * <kbd>page down</kbd>/<kbd>page up</kbd> works => as expected
    * <kbd>ctrl</kbd>+<kbd>page down</kbd>/<kbd>page up</kbd> doesn't work => as expected
    * <kbd>shift</kbd>+<kbd>page down</kbd>/<kbd>page up</kbd> doesn't work => as expected
    * <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>page down</kbd>/<kbd>page up</kbd> works => **it should not ?**

8. run `find | less`:

    * <kbd>page down</kbd>/<kbd>page up</kbd> doesn't work => **it should**
    * <kbd>ctrl</kbd>+<kbd>page down</kbd>/<kbd>page up</kbd> doesn't work => as expected
    * <kbd>shift</kbd>+<kbd>page down</kbd>/<kbd>page up</kbd> works => **it should not ?**
    * <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>page down</kbd>/<kbd>page up</kbd> doesn't work => as expected

**Comment by maximbaz** [comment]
I just tried out of curiosity and can also repro the issue.

1. run `kitty`, in there run `find | less` and press <kbd>page down</kbd> — it scrolls down.
1. run `kitty -o 'map page_down scroll_page_down'`, in there run `find | less` and press <kbd>page down</kbd> — nothing happens.

**Comment by kovidgoyal** [comment]
scroll_page_up and scroll_page_down actions are meant for scrolling kitty's scrollback buffer, not that of less or vim. By default kitty_mod+page up is bound to scroll_age_up similarly kitty_mod+page down is bound to scroll_page_down. 

pageup and page down by themselves will produce the bytes 

```

^[[5~

and

^[[6~

```

which programs like less and vim then interpret as page down and page up key presses.
