### ISSUE TITLE
Creating a new window with the same path

### ISSUE THREAD

**Issue by Longhinus** [kovidgoyal/kitty#1013]
I recently ditched tmux and switched to the native kitty multiplexer. Kitty is really great and fast but I miss the ability to create a window in the directory as previous one _(eg. using vim and then opening a new window with gcc)_.

The way I can think about it would be as a new keybinding, like:
`map kitty_mod+g new_window_here`

I believe it would be really nice to see this feature coming in kitty.

**Comment by kovidgoyal** [comment]
Use

```
map kitty_mod+g new_window_with_cwd
```
