### ISSUE TITLE
Never display a tab bar.

### ISSUE THREAD

**Issue by AmokHuginnsson** [kovidgoyal/kitty#1014]
Hello.

`kitty` is a very nice terminal emulator, that being said,
I would like to request a new feature for it.

I would like to get an ability to tell `kitty` to never display a tab bar.
Maybe new setting for `tab_bar_style`, something like

`tab_bar_style = none`

 or

`tab_bar_style = hidden`

What do you think?

**Comment by maximbaz** [comment]
So you are actually using tabs, but you don't want to see that you have multiple tabs?

**Comment by AmokHuginnsson** [comment]
Yes. Exactly. I want maximal terminal estate. I remember which tabs are open and what is their content.

**Comment by aIRisius** [comment]
You can:
1. Open kitty/tab_bar.py
1. Add `return` at line 135
```python
def layout(self):
    return
    central, tab_bar, vw, vh, cell_width, cell_height = viewport_for_window(self.os_window_id)
    ...
```

**Comment by AmokHuginnsson** [comment]
@aIRisius I want to do it through configuration. Not to patch the code on every machine I use.

**Comment by erf** [comment]
You can set the following in kitty.conf:
```
tab_bar_style              separator                                                          
tab_separator              " "
```
and then set the bash terminal title empty like this:
```
PROMPT_COMMAND='echo -ne "\033]0; \007"'
```

**Comment by AmokHuginnsson** [comment]
@erf That would wast one line of available space which is precisely what I want to avoid.
