### ISSUE TITLE
missing build dependencies

### ISSUE THREAD

**Issue by sbeckeriv** [kovidgoyal/kitty#1019]
I think these are the ones that got me going on Ubuntu 
```
libegl1-mesa-dev
libwayland-dev
wayland-protocols
```

**Comment by kovidgoyal** [comment]
Thanks, but, I think
libgl1-mesa-dev is already listed here: https://sw.kovidgoyal.net/kitty/

wayland is optional, if it is not found, the wayland backend simply wont be built.
