### ISSUE TITLE
Window hangs on paste by middle-click

### ISSUE THREAD

**Issue by NeoTheFox** [kovidgoyal/kitty#102]
On my two PCs running arch kitty always seem to hang on middle-button parse from selection.
This only happens when kitty is started by i3, which is really weird. When started by another terminal of by rofi it doesn't happen. 
Here is a screencap of that happening (the terminal on the left started by rofi and the one on the right is started by a keybind). 
[Screencap](https://media.giphy.com/media/3o6vXSWG6uQoUeurDO/giphy.gif)

**Comment by kovidgoyal** [comment]
When you middle click, kitty calls the xsel program to get the selection, see get_primary_selection() in utils.py. Presumably that is what is hanging. You can try running it yourself, via

xsel -p

**Comment by NeoTheFox** [comment]
xsel -p works regardless of a parent process, but the middle click still hangs the terminal started with i3. 
I know it's a very strange bug. Presumably something is different about i3 exec and normal exec. Same happens when launched with nohup, so something must be missing.

**Comment by kovidgoyal** [comment]
Running kitty as 

nohup kitty

gives me no issues with middle click pasting.

**Comment by NeoTheFox** [comment]
Interesting, what is your i3 version? Mine is 4.13
Do you think it's an i3 bug?

**Comment by kovidgoyal** [comment]
No I meant with just nohup, I dont use i3.

**Comment by NeoTheFox** [comment]
This happens when kitty is started by i3 using i3's exec.
When started from another terminal or rofi it's gone.

**Comment by kovidgoyal** [comment]
I thought you said it also happens when launched with nohup

**Comment by NeoTheFox** [comment]
When launching with nohup, but still from i3.

**Comment by kovidgoyal** [comment]
Only thing I can think of is stderr/stdin are hanging when launched from i3. You can try replacing line 184 in kitty/utils.py with
```py
return subprocess.check_output(['xsel', '-p'], stderr=open(os.devnull, 'wb'), stdin=open(os.devnull, 'rb')).decode('utf-8')
```

that might make it work.

**Comment by NeoTheFox** [comment]
Yup, that worked, thanks!. Maybe then consider adding a cmd flag like `-q` for kitty to be quiet?

**Comment by kovidgoyal** [comment]
The std streams hanging is pretty catastrophic for lots of software. For example, any print statement anywhere can potentially hang. I doubt this problem is a general one. More likely some misconfiguration in your setup. Since you are using i3 you may not be using a startx script, in which case dont forget to redirect the stdout and stderr of that script to ~/.xsession-errors or similar. 

I will change kitty to redirect the streams to null when calling xsel, since that is the most likely vector, but I dont want to sped the time trime to make all print statements hang proof.

**Comment by kovidgoyal** [comment]
I added a --detach option that detaches kitty from whatever environment it was launched in. Use 

kitty --detach

instead of plain

kitty

in your i3 config.

**Comment by NeoTheFox** [comment]
Nice, thanks a lot for the fix!
I checked my setup (I am using SDDM for session startup), and it had been writing to the logfile without any problems, other apps started from within i3 had their stdout and stderr in there. But with the latest commits everything is fixed and I've added --detach too.
