### ISSUE TITLE
Strange bug in app only on Kitty, not other terminals

### ISSUE THREAD

**Issue by tom-adsfund** [kovidgoyal/kitty#1020]
I was testing "Liquid editor for Clojure" (https://github.com/mogenslund/liquid), and found a problem that only happens when using Kitty (not a range of other terminals, including system TTY and Terminator).

It seems that holding down a key does something like feed in some erroneous characters.

You can easily try the app and see the problem:
```
cd /tmp
wget http://salza.dk/liq.jar
java -jar liq.jar
```

Press tab to go into insert mode, then hold the up arrow. In Kitty this will corrupt the buffer. In all other terminals tried, it doesn't.

I am not a core developer for Liquid. Although I'm sure the core developer for that project would help. See related issue on their project: https://github.com/mogenslund/liquid/issues/17

**Comment by kovidgoyal** [comment]
first make sure you are running an up to date version of kitty (0.12.2) Then start kitty like this

kitty --config NONE --dump-bytes dump.bin

then perform the minimal steps to recreate the issue and post the dump file.

**Comment by tom-adsfund** [comment]
I was using 0.12.0 (25 days ago). Seems to have been fixed since!

Thanks for an excellent terminal.

**Comment by kovidgoyal** [comment]
:) kitty development is fairly rapid at the moment and you're welcome

**Comment by kovidgoyal** [comment]
Well if you manage to figure out a set of steps to reproduce, feel free to follow the procedure I gace above to create a dump file.
