### ISSUE TITLE
Ctrl-Shift-bracketright/-0x5d does not override default ("]")

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#1021]
For `Ctrl-Shift-+` (plus) on a German keyboard I am seeing this:

```
Press scancode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)                                                         
on_key_input: glfw key: 341 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x32 clean_sym: Shift_L composed_sym: Shift_L mods: ctrl glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)                                                                 
on_key_input: glfw key: 340 native_code: 0xffe1 action: PRESS mods: 0x2 text: '' state: 0 sent key to child                                                                                  
Press scancode: 0x23 clean_sym: plus composed_sym: asterisk mods: ctrl+shift glfw_fallback_key: 93 (RIGHT BRACKET) xkb_key: 93 (bracketright)                                                
on_key_input: glfw key: 93 native_code: 0x5d action: PRESS mods: 0x3 text: '' state: 0 handled as shortcut                                                                                   
```

(I had `map kitty_mod+plus     change_font_size current +0.1` in my config, therefore I assume it worked before in a previous version, but am not sure about this - I just start playing with kitty again.)

But now I have to use either `kitty_mod+0x5d` or `kitty_mod+bracketright`, which is unfortunate, but OK.

However, it only works when using `clear_all_shortcuts yes` before, or `kitty_mod+]` to override the default for `next_window`.

1. I think it would be good if the debug output ("handled as shortcut") would provide more information, which would have made it easier to find the root cause for this.  Maybe a `repr()` of `key_action` could be returned from `dispatch_action`/`dispatch_special_key` or something similar?

2. When debugging it it turned out that it is due to `next_window` (`'kitty_mod+]'`), and that if I use `kitty_mod+]` myself in the config it will override the default.

I think later shortcuts should always be checked before earlier ones - I assume that currently `]` is checked before `bracketright`/`0x5d`.

**Comment by kovidgoyal** [comment]
I'm confused. Why dont you just use 

```
map kitty_mod+] change_font_size
```

Binding by scancode/xkb name has lower preference than binding by cross platform key name.,

**Comment by blueyed** [comment]
Yeah, I am using this now, but I had to debug kitty first to come to this conclusion.

I think defaults should have a lower preference altogether, and/or that scancodes should be the most specific (they are not used with defaults, so that should help with that also).
What about `scancode > xkb name > cross platform name`?

And do you think improving the debug logging would be good (to have the action being dispatched therein)?

**Comment by blueyed** [comment]
> I'm not in favor of giving scancodes a higher precedence. They are not protable (even from the same OS to the same OS they can vary by keyboard). And they are harder to debug/understand.

I totally agree, and it is unfortunate that they have to be used after all.
But it is really frustrating on top if they are ignored then additionally.

> I'm OK with having the debug logging indicate what action is being matched.

Cool.
I think it could also make sense to have some debug output in case multiple actions are matched (via different methods) maybe.

**Comment by blueyed** [comment]
Just for reference: https://github.com/kovidgoyal/kitty/commit/3f2489b306ae400858ba1ac1830705d5f6c2e5a1 (via https://github.com/kovidgoyal/kitty/issues/1224) fixed the original issue.
