### ISSUE TITLE
Right alt/option key on macOS setting different to left one possible?

### ISSUE THREAD

**Issue by cultavix** [kovidgoyal/kitty#1022]
On my iTerm2 terminal, I have the following settings for my alt keys, which give me everything I need.

![image](https://user-images.githubusercontent.com/3919945/46083784-09e61c80-c19a-11e8-8c1b-0ebb8f718d11.png)

I want to be able to use `alt/option` to for example do. `alt + 3 == #` OR `alt . == (would toggle through the last arguments/params I passed in the previous commands)`

Is this possible in Kitty?

The only option I see is `macos_option_as_alt yes/no`

Can you somehow make a new option to distinguish between the left/right alt/option keys?

Thanks!!!!!

**Comment by kovidgoyal** [comment]
I'm afraid this is too much work for me, sorry. But patches are welcome.

**Comment by kovidgoyal** [comment]
Actually on second thoughts there might be an easy way to accomplish this, I'll look into it when I have a moment.

**Comment by cultavix** [comment]
@kovidgoyal - That would be amazing and would allow me to use this terminal as my main terminal.

**Comment by hauleth** [comment]
Right now I have problem with this as I cannot enter national letters due to fact that Kitty register RALT and LALT as the same characters and do not handles them via the OS, which mean that I cannot enter letters like `ą` (RALT-a) in the terminal.

**Comment by kovidgoyal** [comment]
Simply set macos_option_as_alt to no in your kitty.conf

**Comment by hauleth** [comment]
Still it, this cuts me from all ALT chords. Ideal would be to use one ALT as Escape code prefix and second as a AltGr.

**Comment by robertnorenberg** [comment]
@hauleth (assuming Polish):
```
map alt+a send_text all \u0105
map alt+c send_text all \u0107
map alt+e send_text all \u0119
map alt+l send_text all \u0142
map alt+n send_text all \u0144
map alt+o send_text all \u00F3
map alt+s send_text all \u015B
map alt+z send_text all \u017A
map alt+x send_text all \u017C

map alt+shift+a send_text all \u0104
map alt+shift+c send_text all \u0106
map alt+shift+e send_text all \u0118
map alt+shift+l send_text all \u0141
map alt+shift+n send_text all \u0143
map alt+shift+o send_text all \u00d3
map alt+shift+s send_text all \u015a
map alt+shift+z send_text all \u0179
map alt+shift+x send_text all \u017b
```

**Comment by robertnorenberg** [comment]
@hauleth Not sure if this is acceptable to you (not the "ideal" case I guess), but as I only use `Alt`+`b|f|t` the following forks just fine for me:

```
map alt+a send_text all \u0105
map alt+c send_text all \u0107
map alt+e send_text all \u0119
map alt+l send_text all \u0142
map alt+n send_text all \u0144
map alt+o send_text all \u00F3
map alt+s send_text all \u015B
map alt+z send_text all \u017A
map alt+x send_text all \u017C

map alt+shift+a send_text all \u0104
map alt+shift+c send_text all \u0106
map alt+shift+e send_text all \u0118
map alt+shift+l send_text all \u0141
map alt+shift+n send_text all \u0143
map alt+shift+o send_text all \u00d3
map alt+shift+s send_text all \u015a
map alt+shift+z send_text all \u0179
map alt+shift+x send_text all \u017b
```

**Comment by jacwah** [comment]
@robertnorenberg Thanks for the tip! I never use alt for "unicode symbols", but the key is required for normal symbols like `[]{}|\$@` with my keyboard layout.  This is the setup I am trying out right now:

```
macos_option_as_alt yes

# combinations where I want the "option" behavior
map alt+2 send_text all @
map alt+4 send_text all $
map alt+7 send_text all |
map alt+8 send_text all [
map alt+9 send_text all ]
map shift+alt+7 send_text all \\
map shift+alt+8 send_text all {
map shift+alt+9 send_text all }

# readline bindings I can't type with this layout
map alt+' send_text all \x1b*
map alt+plus send_text all \x1b?
```

Unfortunately (emacs/readline) prefix arguments aren't possible with this configuration. Maybe it's time to learn to use a US keyboard...
