### ISSUE TITLE
kitty `sudo htop` cannot open terminal

### ISSUE THREAD

**Issue by dqian96** [kovidgoyal/kitty#1024]
When using Kitty, I cannot open `htop` with superuser privileges. I get the error `Error opening terminal: xterm-kitty.`. I discovered that the reason behind this is that `$TERMINFO` is not set for sudo. Is there a way to automatically forward this for sudo? (`-E` does not forward terminfo because of security concerns).

Kitty Version: 0.12.2
OS: MacOS 10.13.6
Also using tmux, although this issue should be independent of it.

**Comment by maximbaz** [comment]
Why not install `xterm-kitty` terminfo system-wide? 😉

**Comment by kovidgoyal** [comment]
Or you can add TERMINFO to the sudo config file as a forwarded variable.
