### ISSUE TITLE
Consider changing the name to avoid confusion

### ISSUE THREAD

**Issue by ccharles** [kovidgoyal/kitty#1025]
I was quite confused when I stumbled across this project. There's already [another terminal emulator called KiTTY][1] (it's a fork of the famous [PuTTY][2]).

Would you consider changing the name of your project?

[1]: http://www.9bis.net/kitty/
[2]: https://www.putty.org/

**Comment by SolitudeSF** [comment]
#9

**Comment by kovidgoyal** [comment]
dup of #9 I have said all I am going to say on this subject, there.
