### ISSUE TITLE
kitty @set-colors --all --configured doesn't seem to work

### ISSUE THREAD

**Issue by tcoopman** [kovidgoyal/kitty#1027]
I'm running `kitty @set-colors --all --configured ~/.config/kitty/dark` but new terminals don't have the colors and open colors also don't have the correct colors.

Not sure if I'm missing something, can't find anything obvious in the documentation

**Comment by tcoopman** [comment]
so this is in my `kitty.conf`

```
# remote control
allow_remote_control yes
```

running `kitty @set-colors --all --configured ~/.config/kitty/dark` sets the color for the current open kitty, exit code is **0**.

Opening a new kitty: wrong colors
Running the command with more than one kitty open: only current one changes color.

**Comment by kovidgoyal** [comment]
configured changes the color for all new windows opened in the current instance, not for new instances. All remote control command in general only work on a single kitty instance, not future instances. Use the --single-instance switch to kitty if you want all kitty top level windows to belong to a single kityt instance.
