### ISSUE TITLE
kitty.fast_data_types.wcwidth: does not return negative values (for e.g. 0xe0c2)

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#1029]
I am trying to figure out why kitty renders a private unicode codepoint from nerdfonts in a single cell, and noticed the following:

```
>>> from kitty.fast_data_types import wcwidth
>>> print(wcwidth(0xe0c2))
18446744073709551613
```

This appears to be due to -3 returned in the following code overflowing?!
https://github.com/blueyed/kitty/blob/3323ddcdef7dabad6bd1540ba39a677132240bb0/kitty/wcwidth-std.h#L620-L621

Are negative values meant to be handled in a special way later, e.g. by querying the font for metrics etc?

I think the Python interface should return also the negative values in the first place.

**Comment by kovidgoyal** [comment]
All private use unicode codepoints have to be rendered in one cell as per the standard. kitty makes an exception specifically for nerd fonts in that a PUA followed bya  space uses two cells. So make sure you follow your PUA characters with a space if you want them rendered wide.

As far as I recall the python version of wcwidth is not actually used anywhere other than the test suite, but it should certainly be fixed.

**Comment by blueyed** [comment]
> All private use unicode codepoints have to be rendered in one cell as per the standard.

Do you have a reference?
Has this changed in one of the later ones?  Because IIRC it was different a while (1-2 years?) ago.

btw: when hacking on urxvt to make it handle wide glyphs I've also thought about a `wcwidth` wrapper that would look at the font to return the number of cells actually (i.e. the width would be different based on the font being used) - but that certainly only works if you use the same `wcwidth` then will all programs (e.g. via `LD_PRELOAD`).

> kitty makes an exception specifically for nerd fonts in that a PUA followed by a space uses two cells.

Interesting.  However it does not appear to work for me:
![pua](https://user-images.githubusercontent.com/9766/46145059-2a2bdf00-c25f-11e8-96d5-35b587688606.png)

In urxvt (patched) it gets displayed in 3 cells:
![pua-urxvt](https://user-images.githubusercontent.com/9766/46145060-2a2bdf00-c25f-11e8-9b64-850e480bb723.png)

I am using the patch Hack Nerd font (http://nerdfonts.com/#downloads).

**Comment by blueyed** [comment]
In an older version of the font this glyph even took 4 or 5 cells btw.

**Comment by kovidgoyal** [comment]
PUA characters have undefined width. undefined width has to be rendered as one cell. And no you cannot use the same wcwidth as all programs. programs use all sorts of wcwidth implementations, and we wont even get into SSH. The only sane way is to follow the standard.

urxvt's approach, which appears to be use the glyph width from the font, is completely bonkers. That way it is impossible for any terminal program to know what width any PUA character takes, which means it is impossible to reliably draw a terminal UI.

And it works fine for me. See lines 1009 -- 1024 in fonts.c

**Comment by blueyed** [comment]
> urxvt's approach, which appears to be use the glyph width from the font, is completely bonkers.

This is not urxvt itself, but my (rather huge) patch to handle wide glyphs with it - normally it would just not display too wide glyphs.

My urxvt patch has a similar approach like kitty - it also requires spaces after the glyphs (but not limited to just one):

![pua-urxvt2](https://user-images.githubusercontent.com/9766/46146012-fdc59200-c261-11e8-8fb9-1fb051bfdb1e.png)

> And it works fine for me. See lines 1009 -- 1024 in fonts.c

With `python -c "print('\ue0c2 ')"` `prev_width is 1 for me here:
https://github.com/kovidgoyal/kitty/blob/e498cedf5634794d1ef6ca88d3a3fedcc7da3288/kitty/fonts.c#L1021 (the `if` gets triggered once for the PUA character as expected though).

When setting `prev_width` to 2 explicitly (what is expected to happen / happens in your case) to actually let it `continue` then later, it behaves as follows (note the 2nd case):
![prev_width_2](https://user-images.githubusercontent.com/9766/46147269-62362080-c265-11e8-84bc-2ab401b33e2b.png)

I assume for some reason it gets rendered into a single cell already (and therefore `prev_width` becomes 1?!).

I've tried another glyph, and noticed that double clicking on it will select two cells (same for the first glyph also).  It also gets rendered in a single cell:

![e61e](https://user-images.githubusercontent.com/9766/46148014-58adb800-c267-11e8-86ba-86f30a20559b.png)

What font and glyph are you using?

**Comment by kovidgoyal** [comment]
It's been a while since I tested it (I dont use nerd fonts) but IIRC it was with nerd fonts that the code was developed. You should be able to use git blame to check the commit it was added, which should reference the issue which th ecomit fixes. (Sorry I am away from my computer at the moment, so i cant do this myself)

**Comment by kovidgoyal** [comment]
relevant issue #357

**Comment by blueyed** [comment]
I am not sure, but I might have used "X Nerd Font Mono" instead of "X Nerd Font" (or something similar - resulting in the glyphs being restricted to a single cell after all).

For reference: `fc-list ':charset=0xe0c2'` was useful in this regard to see which fonts provide it.

I consider this to be fixed/closed now really. Thanks!
