### ISSUE TITLE
Report info about character on screen / ISO 14755

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#1030]
urxvt has support for [ISO 14755](https://en.wikipedia.org/wiki/ISO/IEC_14755), which includes that you can select a character/cell on the screen and it will display information about it (codepoint, attributes etc).

I am particular interested in the reporting feature, since kitty already has other methods to input special characters.

![iso](https://user-images.githubusercontent.com/9766/46111229-830b6100-c1e6-11e8-8a72-1ac92ef09a2d.png)

**Comment by kovidgoyal** [comment]
Not worth the effort to me (this functionality is already present in things like vim) but patches are welcome. You'd basically need to create a kitten similar to  the hints kitten that takes the screen contents and displays data about the character under the cursor (IIRC the kittens system does not currently pass info about the cursor position,, but that can be easily changed).
