### ISSUE TITLE
Adding bindings for mouse buttons

### ISSUE THREAD

**Issue by lazarcf** [kovidgoyal/kitty#1033]
Hey,

I would very much appreciate it if I could change the middle / right click mouse button behaviour, for instance make them paste from clipboard.

**Comment by kovidgoyal** [comment]
I'm afraid this is not something I am interested in, patches are welcome. And note that middle click already pastes, from primary selection, on platforms that have a primary selection.

**Comment by lazarcf** [comment]
The problem is I select something in one kitty terminal and can't middle-click paste it on another..

**Comment by maximbaz** [comment]
> The problem is I select something in one kitty terminal and can't middle-click paste it on another..

Works for me. Are you saying that middle click works in the same kitty instance, but not in a different one?

**Comment by somody** [comment]
I'm interested in this feature for another usecase.  Buttons 8 and 9 on my external mouse are generally understood by software as _back_ and _forward_ commands, respectively.  Right now, these buttons are useless in `kitty`, but it would be nice to map them to `previous_tab` and `next_tab`, respectively.  Although the mouse buttons could be mapped to keyboard shortcuts, and then these keyboard shortcuts could be used with `kitty`, this would break the current functionality of the mouse buttons with Chrome, etc.

**Comment by kovidgoyal** [comment]
Mouse button mapping was implemented in 0.21.0

**Comment by tjatjagithub** [comment]
It's fantastic, that we have mouse binding!

Sadly, even after several hours, I am not able to create a working "copy on select" and "paste on right mouse button" configuration.

Did anybody ever got this running?
I already fear that I will get stuck with iTerm2 :-(

My latest try looks like this:

detect_urls no
copy_on_select clipboard
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+
focus_follows_mouse yes
mouse map right click grabbed no-op
mouse map right click ungrabbed no-op
mouse map right click grabbed,ungrabbed no-op
mouse_map right click grabbed,ungrabbed paste_from_clipboard
allow_hyperlinks no

But that first selects up to where my mouse pointer is, and then paste everything from what I selected down to, where my mouse currently. 
Very strange :-O

A working version in the comments would help immensely :-)

**Comment by tjatjagithub** [comment]
I found what is happening:

```
Press mouse_button: 1 mods: none grabbed: 0
on_mouse_input: press button: right mods: none grabbed: 0
MouseEvent matched action: mouse_selection
Release mouse_button: 1 mods: none handled as drag end
on_mouse_input: click button: right mods: none grabbed: 0
MouseEvent matched action: paste_from_clipboard
```

So there is a right mouse press action, that selects by the mouse position, as it seems.

So I removed any and all click, press and release actions ...

And now it works!!!! :-)

**Comment by tjatjagithub** [comment]
```
mouse_map right click grabbed no-op
mouse_map right click ungrabbed no-op
mouse_map right click grabbed,ungrabbed no-op

mouse_map right press grabbed no-op
mouse_map right press ungrabbed no-op
mouse_map right press grabbed,ungrabbed no-op

mouse_map right release grabbed no-op
mouse_map right release ungrabbed no-op
mouse_map right release grabbed,ungrabbed no-op

mouse_map right click grabbed,ungrabbed paste_from_clipboard
```

But I cannot copy the <newline> when selecting the whole line, which means that I always need to press the <Enter> key, even when copying a whole line.

Maybe that is hidden in the "select_by_word_characters" setting ...

**Comment by tjatjagithub** [comment]
Sadly, this still does not work.

Hyperlinks continue to be interpreted and open a webbrowser, so you cannot even copy-paste them!

No idea, how to fix this :-(

**Comment by tjatjagithub** [comment]
This seems to work:

```
focus_follows_mouse yes

# Do not handle URLs
mouse_map left click ungrabbed no-op
detect_urls no
allow_hyperlinks no

#copy_on_select clipboard
copy_on_select yes

strip_trailing_spaces smart
select_by_word_characters ${}/&@_.

#mouse_map right press grabbed,ungrabbed paste_from_clipboard
mouse_map right press grabbed,ungrabbed paste_from_selection
```

Not sure why "yes" works for the clipboard.
And not sure what is the difference between paste_from_clipboard and paste_from_selection - both seem to work the same.

And, I cannot copy the "newline" of a line with a tripple-click.

**Comment by tjatjagithub** [comment]
Alacritty is going to add support for right-click paste!
If that allows to copy the whole line including the newline character, that's what I need :-)

**Comment by tjatjagithub** [comment]
Why did my posting get removed?

I think it contained a very important information!
