### ISSUE TITLE
macOS Mojave: Initial window is blank

### ISSUE THREAD

**Issue by herrbischoff** [kovidgoyal/kitty#1037]
## Environment

```
$ kitty -v
kitty 0.12.2 created by Kovid Goyal
```
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14
BuildVersion:   18A391
```

## Issue

Since upgrading to Mojave (with Dark Mode activated), kitty only displays a blank window. It does bring up the command line, which is indicated by a changing menu bar when running commands blindly. After once completely hiding and unhiding the window, everything works as expected from then on. It's a minor issue but a moderately annoying one.

Let me know if you need any more info.

**Comment by kovidgoyal** [comment]
dup of #887

**Comment by herrbischoff** [comment]
Ah, didn't see that. Thanks for already having taken care of it.
