### ISSUE TITLE
linux plateform pulls in sphinx

### ISSUE THREAD

**Issue by Arnaudv6** [kovidgoyal/kitty#1038]
Hello and thanks again for this incredible terminal.
I wish I could avoid pulling in sphinx (and 30 deps I never needed otherwise) "just" for doc generation.
Furthermore when your online doc is awesome (yes, I do RTFM).
Any chance you'd allow a configure'flag to not install the doc?
(Or any better solution you can find?)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/build.html

use the install from source instructions there, they do not require sphinx unless you are a building a kitty package. If you are then since the package includes the docs you need sphinx.

**Comment by Arnaudv6** [comment]
OK, sorry: wrong place, I read the makefile to fast, should have read your nice build instructions.
Opened https://bugs.gentoo.org/667264
