### ISSUE TITLE
Kitty incorrectly renders text when a monitor is in portrait orientation

### ISSUE THREAD

**Issue by Bouldersky** [kovidgoyal/kitty#1039]
On a multi monitor system (specific info below), if one monitor is rotated to the portrait orientation, then kitty renders text stretched vertically. This behavior only happens if the monitor rotation is done through the xorg.conf file. If I boot with the monitor in landscape orientation, then I rotate it via xrandr (after I'm logged in) then kitty is fine. Kitty renders the text incorrectly regardless of what monitor it is on I'm on, and no other application (that I've observed) is effected by this issue.

Here is a screenshot of kitty rendering all ascii characters (next to xterm, which is working properly). The windows are sitting on a monitor which is in landscape mode. A second monitor is in portrait orientation:
![stretchedscreenshot](https://user-images.githubusercontent.com/5067181/46251285-08238f80-c40c-11e8-96bf-e3bb8032e1da.png)

Here is a screeshot of the same thing, but after booting without the 2nd monitor rotated:
![nonstretchedscreenshot](https://user-images.githubusercontent.com/5067181/46251286-08238f80-c40c-11e8-96ce-400e531f8ef5.png)

The only change in the xorg config file between screenshots is going from this (which caused distortion):
`"metamodes" "DP-2: 2560x1440_144 +1920+0, DVI-D-0: nvidia-auto-select +4480+0 {rotation=left}, HDMI-0: nvidia-auto-select +0+0"`
To this (which didn't):
`"metamodes" "DP-2: 2560x1440_144 +1920+0, DVI-D-0: nvidia-auto-select +4480+0, HDMI-0: nvidia-auto-select +0+0"`

Here's all the system info  that I can think of which could be relevant, but let me know if I missed anything:
kitty version: screenshots in 0.12.1 installed with pacman, but I also tried compiling from source and it happened there as well. Using the default kitty config file in both cases.
distro: 
  arch
window manager: 
  i3-gaps
graphics driver:
  nvidia 396.54-6
  nvidia-utils 396.54-1 (contains openGL)
openGL version: 
  4.6.0
Monitor layout which causes the issue:
![problematiclayout](https://user-images.githubusercontent.com/5067181/46251408-335bae00-c40f-11e8-9e71-9aaf19324cd2.png)
Monitor layout which works fine:
![workinglayout](https://user-images.githubusercontent.com/5067181/46251463-c47f5480-c410-11e8-97f1-730b0835332f.png)
Just to clarify, the screenshots were taken with the windows on the middle monitor, not the monitor which is changing orientation. Also, if I configure the monitors with the second (working) layout in the xorg.conf file but use xrandr to rotate the monitor after login, kitty doesn't have a problem.

**Comment by kovidgoyal** [comment]
this will be because X and Y DPI values are incorrect. which will ause cell size calculation to be incorrect. DPI values come from glfw (the toolkit kitty uses), so you would need to fix that. As far as I recall, glfw will use the Xft.dpi resurce if it is present, falling back to querying X. So assuming your monitors have the same (or similar) DPI along both axes you can workaround the issue by setting that tot he correct DPI value.
