### ISSUE TITLE
Rendering issue (I think?)

### ISSUE THREAD

**Issue by peyloride** [kovidgoyal/kitty#104]
There is a flat lines on every line. I dont know how can i really explain this so i take screenshot.
http://imgur.com/a/3rvwp

Also, when i run kitty within another terminal; i see these messages pop:
```
[PARSE ERROR] Unknown OSC code: 13
[PARSE ERROR] Unknown OSC code: 14
[PARSE ERROR] Unknown OSC code: 708
```
I did try both compiling by hand and use AUR package, result was same.

Thanks for your hardwork.

My specs:
ArchLinux + i3-gaps + Polybar
Intel Celeron N3150 Processor ( Acer ES1-331-C2TZ )

**Comment by kovidgoyal** [comment]
I suspect this has something to do with your shell. What shell are you using? Try it with a default config and see if the problem goes away.

**Comment by peyloride** [comment]
Thanks for your support,

I'm using zsh shell with oh-my-zsh(default) config. I did try launching kitty from bash terminal and  switching to bash terminal in kitty. But no luck.

**Comment by kovidgoyal** [comment]
The OSC codes 13 and 14 are for changing mouse pointer colors. I have no idea what OSC 708 is, never heard of it. Something in your shell config is outputting those codes, and probably also codes that are causing the underlining of blank cells. 

Try running

kitty cat

which will run kitty with the cat program as the shell. Do you still get lines?

**Comment by peyloride** [comment]
As you mentioned above, i tried kitty cat, and there is no blank cell underlining.

**Comment by kovidgoyal** [comment]
So it is something in your shell config. Hard for me to say what that might be. I use zsh myself, without issues, but not oh-my-zsh.

**Comment by kovidgoyal** [comment]
You can use the --dump-bin option to store all the bytes kitty receives and upload it here. I can take a look at it and see what exact control sequence is causing the underlining. There is a chance that kitty is misinterpreting a control sequence used for something else.

**Comment by peyloride** [comment]
I did try --dump-bin but i think you misspell it since it doesnt recognize that command. So i look at --help and saw --dump-bytes and used it. I attached that file.

Thanks for your interest.
[dump.zip](https://github.com/kovidgoyal/kitty/files/1199756/dump.zip)

**Comment by kovidgoyal** [comment]
According to that github page, wal is deprecated. Maybe try replacing it with pywal as its author recommends.

**Comment by kovidgoyal** [comment]
There is indeed a bug in the way kitty handles the escape codes to set the default foreground and background colors, I'll fix it soon.

**Comment by blakat360** [comment]
I get `[PARSE ERROR] Unknown OSC code: 708` when running the[ autogenerated (by nix-colors) theming script](https://github.com/Misterio77/nix-colors/blob/main/lib/contrib/shell-theme.nix) from bash, zsh, fish and sh in kitty.

On linux, this does not affect the user experience. On mac, this comes with a sequence of "-ne" being spammed onto the screen.

I have made an associated issue [here](https://github.com/Misterio77/nix-colors/issues/33).

Could the bug still be present in kitty?

**Comment by nakoo** [comment]
> I get `[PARSE ERROR] Unknown OSC code: 708` when running the[ autogenerated (by nix-colors) theming script](https://github.com/Misterio77/nix-colors/blob/main/lib/contrib/shell-theme.nix) from bash, zsh, fish and sh in kitty.
> 
> On linux, this does not affect the user experience. On mac, this comes with a sequence of "-ne" being spammed onto the screen.
> 
> I have made an associated issue [here](https://github.com/Misterio77/nix-colors/issues/33).
> 
> Could the bug still be present in kitty?

Hi, did you solve this issue? I have same issue with nix-colors.

**Comment by blakat360** [comment]
I didn't manage to fix the underlying issue. But I did get a workaround.

I think I ended up just clearing the screen manually on shell startup.
