### ISSUE TITLE
Add last_tab and last_window hotkeys

### ISSUE THREAD

**Issue by marningmol** [kovidgoyal/kitty#1040]
I want to try kitty as a replacement for tmux, but an integral part of my workflow depends on the use of the following Tmux commands which I cannot find a replacement for in Kitty:

```
last-pane [-de] [-t target-window]
                   (alias: lastp)
             Select the last (previously selected) pane.  -e enables or -d
             disables input to the pane.

last-window [-t target-session]
                   (alias: last)
             Select the last (previously selected) window.  If no
             target-session is specified, select the last window of the cur‐
             rent session.
```

Just to make it blindingly obvious, the behavior here is for a hotkey that switches to whatever Window / Tab is **not** currently active but was **most recently** active.

I believe this would be easy to add and make a good improvement to Kitty.

**Comment by kovidgoyal** [comment]
sure, should not be hard. I'll get to it when I have a moment, feel free to submit a patch before then, if you want.

**Comment by marningmol** [comment]
Sadly I don't have the time to get into this codebase. I'll wait patiently and be much obliged when it lands.

**Comment by pablox-cl** [comment]
@kovidgoyal, can you point to me where this functionality could be, so I can take a look?

**Comment by kovidgoyal** [comment]
Run kitty from master or wait for the next release and then use goto_tab
-1
