### ISSUE TITLE
hang when asking selection from a stopped window

### ISSUE THREAD

**Issue by martinetd** [kovidgoyal/kitty#1042]
This is a bit borderline, more of a glfw bug, but you seem to be taking these...

My use-case is this:
 * select something in a kitty window that is under gdb, so it sets itself as selection owner; then break in gdb (breakpoint happens, or ^C in gdb window).
This can be any other graphical app and can happen with a sigstop (e.g. I sometimes `pkill -STOP firefox` to save battery)
 * try to paste in another kitty window. That window hangs until the initial window gets unstopped.

It gets worse when trying to paste to the window containing gdb (there is no way to unstop the first kitty), or if you quit without unstopping the gdb at which point there is no way to un-hang the second kitty ; and is even more annoying when you use some degree of single-instance (all windows of a given instance you are pasting to are frozen)...

In `glfw/x11_window.c`'s `getSelectionString()`, we just wait forever for a SelectionNotify event:
```
    while (!XCheckTypedWindowEvent(_glfw.x11.display,
                                       _glfw.x11.helperWindowHandle,
                                       SelectionNotify,
                                       &notification))
        {
            waitForX11Event(-1);
        }
```

A first workaround could be to add an ugly timeout there (if selection takes more than a few seconds to come give up on it), but a proper fix would probably be to handle this type of `SelectionNotify` events in `processEvent` like glfw does with drag n' drop.
Doing things asynchronously would probably still need some form of timeout though (maybe not time, but related to other input?); I believe pasting the text after something else happened if the source finally wakes up after a while would be confusing at best.

Anyway, too many things pending right now so won't do that in the close future, but figuring I'd open an issue to remember.

**Comment by kovidgoyal** [comment]
As far as I know, glfw is riddled with plenty of these loops that can hang indefinitely in x11 backend. For that matter it's fundamental design is wrong for the cocoa backend (apple does not want applications to control the event loop). 

I'm not sure I understand how moving it into processEvent would be better. You still have to, at some point read the data from another client which could be hung. I dont see how you can avoid a timeout when doing that.

**Comment by martinetd** [comment]
We're not reading from another client directly, we're waiting for X11 events -- processEvent can gradually append to some global (in the _GLFWWindow) selectionString everytime a new event comes, and if it is the last event (itemCount == 0) finish the processing ; if the client gets stuck at some point between two such events we would just sit there with an incomplete string but at least we would still be processing other events while waiting; it wouldn't just freeze all the windows.


That is some big API change though, getSelectionString would no longer return a string but would be called with a callback function to finish the processing ; from an API point of view it's probably better to leave getSelectionString and add a new async function requestSelectionString or something similar.

**Comment by martinetd** [comment]
FWIW if we're breaking the API it'd actually probably be better to paste progressively every time each time we get such an event instead of allocating a huge string, e.g.
 * open bracketed paste mode
 * request selection
 * events happen and paste data progressively
 * if there is some user input, unset the callback and and close bracketed paste mode
 * when no more data, unset the callback and close bracketed paste mode.

That's an even bigger change though, I'd be happy just allocating a huge string and passing it off if/when it completes.

**Comment by kovidgoyal** [comment]
I think I am fine with just putting in a timeout in getSelectionString. This matches how, for instance, the wayland backend works (see read_data_offer() in wl_window.c) 

I dont want to have code with different semantics for different backend in kitty, if at all possible.

**Comment by martinetd** [comment]
Good point, it's best to keep things similar, and that makes it a rather easy change.
I'll get around to it eventually but feel free to do it first if you have time.
