### ISSUE TITLE
Show more output on resize

### ISSUE THREAD

**Issue by juancampa** [kovidgoyal/kitty#1047]
In my usual workflow I have multiple small terminals open. Sometimes I run a command in one of them with a lot of output, to read the whole thing I usually maximize the terminal. When kitty is maximized however, the amount of output shown stays the same, so I have to manually scroll back. 

In other words, if an instance of kitty is small in the screen fitting 20 lines, when said window is resized vertically to fit more lines, say 40, kitty will add 20 blank lines at the bottom, instead of scrolling back 20 lines and showing more of the existing output.

Other terminals (e.g. gnome-terminal, urxvt) scroll back so that the most recent output line is shown at the bottom of the screen

**Comment by juancampa** [comment]
Repro:

 1. Start kitty occupying a portion of the screen
 1. Run a command with a lot of output (e.g. `ls -lahG /dev`)
 1. Maximize the window

Result: **Blank lines are shown at the bottom of the window.**

Expected Result: **More of the previous output is shown.**

**Comment by kovidgoyal** [comment]
Sorry, but I like the current behavior of not changing what is shown on the screen when increasing the window size, I find text moving around disorienting. That said, I wont refuse a patch for an option (default off) to change the behavior.

Feel free to submit a PR with the option and I will review and merge. Ask if you need guidance navigating the kitty codebase. To build kitty from source: https://sw.kovidgoyal.net/kitty/build.html

**Comment by juancampa** [comment]
@kovidgoyal thanks for replying. Question, could this be implemented as a kitten?

**Comment by juancampa** [comment]
Also, could you give me general guidance on how to build this? I'm thinking that I need a few things:
 1. An event that fires when the window is resized
 1. A variable or function that allows me to set the scroll position
 1. A way to determine what value to set 2 (window height? buffer height?)

Any help is appreciated

**Comment by kovidgoyal** [comment]
no it cannot be implemented as a kitten. Although the original use case is well covered by existing functionality. If you want to browse the screen and scrollback simply use the existing functions for it: https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Browse scrollback buffer in less

You can have it open in a new top level window, or tab or overlay, as you like.

**Comment by kovidgoyal** [comment]
If you do want to implement you basically have to change how screen_resize works in screen.c 

Move the existing lines downand fill up the space created with lines from the history buffer.

**Comment by kovidgoyal** [comment]
sorry wrong link: https://sw.kovidgoyal.net/kitty/#scrollback

**Comment by juancampa** [comment]
On a related issue I just discovered. If you resize the width to a point where lines start to wrap, and then resize back to the original width, some of the lines don't reappear in the line buffer, and the history buffer is never rewrapped

**Comment by juancampa** [comment]
I took a look and my initial thought is that it could be implemented in `rewrap_inner`. Would that make sense to you?

Something like:
```
  num_extra_lines = dest.numy - src.numy;
  if (num_extra_lines > 0)
    move num_extra_lines from historybuf to dest

  (do what `rewrap_inner` normally does, fill the rest of dest)
```

If I understand correctly `next_dest_line` takes care of pushing the lines that don't fit back to the history buffer

**Comment by kovidgoyal** [comment]
If you shrink the window, then some lines will go into the history buffer since all the lines cannot fit in the new shrunk window. If yo then restore the original size, they will not move back, since on size increases existing text is kept as is.

It would probably be better to move lines after rewrap rather than before. So let the normal rewrap proceed, then move the screne lines down as much as needed using screen_reverse_index() and move some lines from the history buffer to the screen to fill up the blank lines.
