### ISSUE TITLE
[Help] Map key to copying whole scrollback to clipboard

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#1048]
Taking configuration example `map f1 pipe @ansi overlay less +G -R`, I'm trying to `map f12 pipe @text none xclip -selection c`, without success (i.e. after pressing F12, my clipboard remains untouched).

Linux, kitty 0.12.3, `xclip` is installed, in PATH, `echo testxclip | xclip -selection c` correctly results into 'testxclip' in my clipboard, and yes I restarted kitty to reload my conf.

Ideas? Other ways to achieve what I'm trying to do?

Thanks for Kitty.

**Comment by kovidgoyal** [comment]
I'm not a user of xclip, so I cannot comment on that. But if you want to debug the issue, write your own script that reads from stdin and saves the data to a file. Then map that and make sure data is being sent as expected. 

Also you can run kitty from a terminal and it will print any problems to its stdout.

**Comment by ronjouch** [comment]
Thanks, the suggestions helped. I was 1. using `none` instead of `tab`/`window`, and 2. xclip doesn't work, dunno why, but xsel does. So, settling with:

```
map kitty_mod+a pipe @text tab xsel -i -b
```
