### ISSUE TITLE
How does one send the escape sequence ctrl+shift+6 in Kitty?

### ISSUE THREAD

**Issue by kcbark** [kovidgoyal/kitty#1049]
Normally in other terminals when interacting with cisco gear in cli, one could use ”ctrl+shift+6” then press x to escape from ping or traceroute. In iTerm one can use ctrl+^ for this. Is this possible in kitty? How would one make this work? I’ve tried different approaches such as using send_text but haven’t found a solution.

**Comment by kovidgoyal** [comment]
Use ctrl+6

in most terminals ctrl+6 and ctrl+shift+6 generate the same bytes. In kitty, I dont have redundant key mappings like that, so ctrl+shift+6 does nothing.
