### ISSUE TITLE
Map key to another key?

### ISSUE THREAD

**Issue by execb5** [kovidgoyal/kitty#1054]
Hey

This could be a stupid question, but I'm not being able to map a key to another key, what I wanna do is that when I press F1 it actually runs is ctrl+b. Is that possible?

```
map 0x7a 0xb
```

This is what I was trying, got the codes using the debug mode.

Thanks!

**Comment by kovidgoyal** [comment]
You use send_text to do that. Look at the docs: https://sw.kovidgoyal.net/kitty/conf.html  which have examples.

**Comment by kovidgoyal** [comment]
you want
```
map f1 send_text all \x02
```

**Comment by execb5** [comment]
Thank you so much!
It worked perfectly!
