### ISSUE TITLE
AltGr registering as left arrow

### ISSUE THREAD

**Issue by alcino** [kovidgoyal/kitty#1057]
Like in #643 I need to use AltGr to insert `[` and `]` in a Portuguese keyboard. However, AltGr is being registered as a left arrow press. It still works once the key combo is pressed, but first it moves the cursor to the left which makes writing anything very hard. I thought this might have to do with the keyboard layout, but changing back to English doesn't make the behaviour disappear. It also only happens in kitty, xterm behaves fine.

With `kitty --debug-keyboard`:

```
Press scancode: 0x71 clean_sym: ISO_Level3_Shift composed_sym: ISO_Level3_Shift mods: none glfw_fallback_key: 263 (LEFT) xkb_key: 65361 (Left)
on_key_input: glfw key: 263 native_code: 0xff51 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x11 clean_sym: 8 composed_sym: bracketleft active_unknown_mods: Mod5 consumed_unknown_mods: Mod5 text: [ mods: numlock glfw_key: 91 (LEFT BRACKET) xkb_key: 91 (bracketleft)
on_key_input: glfw key: 91 native_code: 0x5b action: PRESS mods: 0x0 text: '[' state: 0 sent text to child
Release scancode: 0x11 clean_sym: 8 mods: numlock glfw_key: 56 (8) xkb_key: 56 (8)
Release scancode: 0x71 clean_sym: ISO_Level3_Shift mods: numlock glfw_fallback_key: 263 (LEFT) xkb_key: 65361 (Left)
on_key_input: glfw key: 263 native_code: 0xff51 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

With `showkey -a`:
```
^[[D     27 0033 0x1b
         91 0133 0x5b
         68 0104 0x44
[        91 0133 0x5b
```

In xterm with `showkey -a`:
```
[        91 0133 0x5b
```

(I don't know how to get the gflw scancodes in xterm).

Is it possible to fix this on my end or is it a bug?

**Comment by kovidgoyal** [comment]
In a US keybaord layout, pressing alt gr should generate alt_r, like this:

```
Press scancode: 0x6c clean_sym: Alt_R composed_sym: Alt_R mods: none glfw_key: 346 (RIGHT ALT) xkb_key: 65514 (Alt_R)
on_key_input: glfw key: 346 native_code: 0xffea action: PRESS mods: 0x0 text: '' state: 0 sent key to child
```

why is it generating ISO_Level_3_Shift on your keyboard? You can probably override it using a ~/.Xcompose file.

**Comment by martinetd** [comment]
AltGr (right alt on some european layouts) really is `ISO_Level3_Shift`; it's different from Alt_R in the xkb logic ; if he overrides it he won't be able to input `[` / `]` anymore (just setxkbmap pt to try and xev should confirm your right alt will become that level3 shift thing; the brackets are right alt + 8/9)

It just works for me though, I don't see any left key press, I'm not sure why it's different for @alcino -- setting his keymap to us should make the log show Alt_R for him as well and he says he still sees a left key there.
What are the lines above the ones you pasted from --debug-keyboard?
Similarily, a few blocks from xev around when you press the AltGr key might give a clue

**Comment by kovidgoyal** [comment]
yeah I meant why is it ISO_Level_3-Shift in the Us layout. There must be something else like an xcompose rule or a modmap or something causing that.

**Comment by alcino** [comment]
Sorry, when I said I changed it back to English I meant UK layout since it's the default here. You're right, in the US layout I do get a Right Alt:
```
Press scancode: 0x71 clean_sym: Alt_R composed_sym: Alt_R mods: none glfw_key: 346 (RIGHT ALT) xkb_key: 65514 (Alt_R)
on_key_input: glfw key: 346 native_code: 0xffea action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release scancode: 0x71 clean_sym: Alt_R mods: alt+numlock glfw_key: 346 (RIGHT ALT) xkb_key: 65514 (Alt_R)
on_key_input: glfw key: 346 native_code: 0xffea action: RELEASE mods: 0x4 text: '' state: 0 ignoring as keyboard mode does not allow release events
```
However, US-International has the same left arrow issue.

@martinetd That's all the output from the debug terminal session, I just opened it and pressed AltGr. As for xev, I get this in the Portuguese layout:
```
KeyPress event, serial 29, synthetic NO, window 0x280001,
    root 0xf3, subw 0x0, time 77043765, (341,284), root:(477,443),
    state 0x10, keycode 113 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x280001,
    root 0xf3, subw 0x0, time 77043875, (341,284), root:(477,443),
    state 0x90, keycode 113 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
And this in the US one:
```
KeyPress event, serial 29, synthetic NO, window 0x280001,
    root 0xf3, subw 0x0, time 77218406, (586,236), root:(644,317),
    state 0x10, keycode 113 (keysym 0xffea, Alt_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x280001,
    root 0xf3, subw 0x0, time 77218500, (586,236), root:(644,317),
    state 0x18, keycode 113 (keysym 0xffea, Alt_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by martinetd** [comment]
(The edit looks the same as the initial comment? :))
Not giving much help though, it does confirm something weird with ISO_Level3_shift but I don't understand why I cannot reproduce; you seem to have Num lock on according to xev but that didn't change anything for me either, I now have the exact same thing there and it doesn't send the first strokes you see with showkey...

**Comment by kovidgoyal** [comment]
The problem appears to be that on your machine, for some reason the the default keymap maps alt gr to left instead of Alt_R. For reference, on my system:

setxkblayout gb

and pressing altgr gives:

```
Press scancode: 0x6c clean_sym: ISO_Level3_Shift composed_sym: ISO_Level3_Shift mods: none glfw_fallback_key: 346 (RIGHT ALT) xkb_key: 65514 (Alt_R)
```

see the difference starting with glfw_fallback_key. That will be because of line 502 in xkb_glfw.c where the fallback key is taken from the default keymap., which is constructed from the default keymap on line 236 which in turn is created in the load_keymaps function. According to that, the default keymap can be controlled via the XKB_DEFAULT_RULES env var. See https://xkbcommon.org/doc/current/structxkb__rule__names.html 

for details. I am guessing that if you either unset that env var or set it to the default us layout you will be fine.

**Comment by alcino** [comment]
Yes, `export XKB_DEFAULT_RULES=base` fixed it, thanks!
