### ISSUE TITLE
Automatically change to directory of current tab in new tabs

### ISSUE THREAD

**Issue by nkiesel** [kovidgoyal/kitty#1059]
The current directory in new tabs is always the home directory. Is there an option to instead set the current directory to the same directory as the current tab.  This was the default behavior of gnome-terminal and I found that useful (and switching to home in the new tab - if desired - is of course trivial).

**Comment by kovidgoyal** [comment]
Map new_tab_with_cwd as described in https://sw.kovidgoyal.net/kitty/conf.html

**Comment by FernandoBasso** [comment]
If I run `kitty --directory ~/Public/`, then do `cd ~/work/proj-x/` and _then_ run a map which is bound to `new_tab_with_cwd`, that new tab still opens in `~/Public/` rather than in `~/work/proj-x/`. Is that expected or something wrong with my config?

**Comment by kovidgoyal** [comment]
Works for me with kitty 0.19.1, steps I tried

1) Run kitty with: 
kitty --directory /tmp --config NONE -o 'map f1 new_tab_with_cwd'
2) cd
3) press f1
4) new tab is created with cwd the home directory, as expected

**Comment by FernandoBasso** [comment]
Indeed it works. My bad. I had some extra mappings overriding the one with `new_tab_with_cwd`. Thanks.
