### ISSUE TITLE
Every version of Terminus I try..  Will not work...

### ISSUE THREAD

**Issue by Anonrate** [kovidgoyal/kitty#106]
So I have been going at this for hours now.  I'm sure you all have heard of the font **Terminus**.  It's the only font I will use in the Terminal.  I just discovered **kitty** about 12 hours ago, and in that 12 hours all I've been trying to do is get the font **Terminus** to work.

#### Versions that I have used are as follows:
* Font package from [Debian Stretch][1] **xfonts-terminus**
* I've manually built the [original][2] font (Both **PSF** and **PCF**)
* I've tried the [Powerline][3] version of the font in the format of **PCF**
* Lastly..  I tried the very *shitty* looking **TTF** format from [ax86][4] <sup>[\[1\]](#error)</sup>

I will also put a code version of this arrow so you can navigate to the locations with ease.
![image](https://user-images.githubusercontent.com/11949153/28974525-b3623daa-7904-11e7-8ccf-3f77922098ce.png)

[1]:https://packages.debian.org/stretch/xfonts-terminus (Package Details for xfonts-terminus)
[2]:http://terminus-font.sourceforge.net/ (Terminus Font Home Page)
[3]:https://github.com/powerline/fonts/tree/master/Terminus (Terminus Powerline)
[4]:https://files.ax86.net/terminus-ttf/ (Terminus \(TTF\))

Every single one failed to show any signs of being present.

#### Trying to resolve the issue myself, I have also tried:
* I have got all the required packages to build **Kitty** and have successfully built it without error.
* Other fonts will work, and if it wasn't for the **TTF** format of **Terminus** not working as well...  I would have guessed that it is only bitmap fonts that wont work.
* I've rebuilt that font cache via `fc-cache -fv`
* Tried with a fully configured `kitty.conf`
* Tried with and without haveing `bold_font`, `italic_font`, `bold_italic_font` with still no avail.
* Tried using the full qualified name of the font, rather than just the *alias*.
* Increasing the size of the font
* Specified full font family(*?*) name (with Regular, Medium, etc..) with and without the same casing
* I've enabled bitmap fonts by removing **70-no-bitmaps.conf** from the font configure directy.
* I've tried changing the `TERM` variable to `xterm-256color`
* I've tried with and without system wcwidth
* I've ran **Kitty** from a different directoy

<a name="error">\[1\]</a>: Got this error while running `python3 .src/kitty` with only `font_family   Terminus (TTF)` in the config file.
<pre>
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File <a href=../blob/master/__main__.py>".src/kitty/__main__.py"</a>, line <a href=../blob/master/__main__.py#L7>7</a>, in <module>
    <a href=../blob/master/__main__.py#L7>main()</a>
  File <a href=../blob/master/kitty/main.py>".src/kitty/kitty/main.py"</a>, line <a href=../blob/master/kitty/main.py#L315>315</a>, in <a href=../blob/master/kitty/main.py#L258-L315>main</a>
    <a href=../blob/master/kitty/main.py#L315>run_app(opts, args)</a>
  File <a href=../blob/master/kitty/main.py>".src/kitty/kitty/main.py"</a>, line <a href=../blob/master/kitty/main.py#L223>223</a>, in <a href=../blob/master/kitty/main.py#L188-L223>run_app</a>
    <a href=../blob/master/kitty/main.py#L223>boss = Boss(window, opts, args)</a>
  File <a href=../blob/master/kitty/boss.py>".src/kitty/kitty/boss.py"</a>, line <a href=../blob/master/kitty/boss.py#L107>107</a>, in <a href=../blob/master/kitty/boss.py#L69-L107>__init__</a>
    <a href=../blob/master/kitty/boss.py#L107>self.sprites.do_layout(cell_size.width, cell_size.height)</a>
  File <a href=../blob/master/kitty/shaders.py>".src/kitty/kitty/shaders.py"</a>, line <a href=../blob/master/kitty/shaders.py#L65>65</a>, in <a href=../blob/master/kitty/shaders/py#L58-L65>do_layout</a>
    <a href=../blob/master/kitty/shaders.py#L65>self.pre_render()</a>
  File <a href=../blob/master/kitty/shaders.py>".src/kitty/kitty/shaders.py"</a>, line <a href=../blob/master/kitty/shaders.py#L76>76</a>, in <a href=../blob/master/kitty/shaders.py#L67-L76>pre_render</a>
    <a href=../blob/master/kitty/shaders.py#L76>send()  # blank</a>
  File <a href=../blob/master/kitty/shaders.py>".src/kitty/kitty/shaders.py"</a>, line <a href=../blob/master/kitty/shaders.py#L71>71</a>, in <a href=../blob/master/kitty/shaders.py#L70-L71>send</a>
    <a href=../blob/master/kitty/shaders.py#L71>buf = render_cell(*a, **kw)[0]</a>
  File <a href=../blob/master/kitty/fonts/render.py>".src/kitty/kitty/fonts/render.py"</a>, line  <a href=../blob/master/kitty/fonts/render.py#L41>41</a>, in <a href=../blob/master/kitty/fonts/render.py#L36-L41>render_cell</a>
    <a href=../blob/master/kitty/fonts/render.py#L41>first, second = rc(text, bold, italic)</a>
  File <a href=../blob/master/kitty/fonts/freetype.py>".src/kitty/kitty/fonts/freetype.py"</a>, line <a href=../blob/master/kitty/fonts/freetype.py#L260>260</a>, in <a href=../blob/master/kitty/fonts/freetype.py#L254-L260>render_cell</a>
    <a href=../blob/master/kitty/fonts/freetype.py#L260>bitmap_char = render_char(text, bold, italic, width)</a>
  File <a href=../blob/master/kitty/fonts/freetype.py>".src/kitty/kitty/fonts/freetype.py"</a>, line <a href=../blob/master/kitty/fonts/freetype.py#L183>183</a>, in <a href=../blob/master/kitty/fonts/freetype.py#L157-L283>render_char</a>
    <a href=../blob/master/kitty/fonts/freetype.py#183>return render_using_face(font, face, text, width, italic, bold)</a>
  File <a href=../blob/master/kitty/fonts/freetype.py>".src/kitty/kitty/fonts/freetype.py"</a>, line <a href=../blob/master/kitty/fonts/freetype.py#L131>131</a>, in <a href=../blob/master/kitty/fonts/freetype.py#L130-L131>render_using_face</a>
    <a href=../blob/master/kitty/fonts/freetype.py#L131>bitmap = render_to_bitmap(font, face, text)</a>
  File <a href=../blob/master/kitty/fonts/freetype.py>".src/kitty/kitty/fonts/freetype.py"</a>, line <a href=../blob/master/kitty/fonts/freetype.py#L125>125</a>, in <a href=../blob/master/kitty/fonts/freetype.py#L119-L125>render_to_bitmap</a>
    <a href=../blob/master/kitty/fonts/freetype.py#L125>format(text, bitmap.pixel_mode)</a>
ValueError: FreeType rendered the glyph for ' ' with an unsupported pixel mode: 1
</pre>

It's now comming up to about 14-15 hours now and I really need to get some sleep.  I will check back when I'm up, and will provide any other information that may be needed.  System specs are as follows though.

Debian Stretch
RX 480
NVME
i7 6850K
32GB DDR4
Open Source Drivers

**Comment by IllanFed** [comment]
Dublicate of #52   
https://github.com/kovidgoyal/kitty/issues/52#issuecomment-279769100

**Comment by kovidgoyal** [comment]
Relevant bug reports: #52 and #97 

So, to sumamrize, if you use a new enough version of freetype you should be able to use the terminus ttf font. And kitty does not support bitmapped fonts.

**Comment by sajattack** [comment]
I'm getting weird looking glyphs using Terminus (TTF) 4.46.
![screenshot](https://i.imgur.com/DA9wNh2.png)

**Comment by kacejot** [comment]
What should I write in the config file to change font?
There is an abstract thing `font_family` in the config file. What should I write there? There is no instructions how to set a font by its name.

I want to set Terminus font and here is output of fc-list:

```
/usr/share/fonts/misc/ter-x12b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x22b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x32b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x18b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x20b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x28b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x16b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x14n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x14b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x24n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x24b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x16n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x18n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x20n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x28n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x12n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x22n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x32n.pcf.gz: xos4 Terminus:style=Regular
```

Help, please. I have spent a lot of time in search of a way to set the font, but there is no result.

**Comment by SolitudeSF** [comment]
kitty does not support bitmap fonts

**Comment by isaz** [comment]
Note for using Terminus TTF,  you need to use the right `font_size` to have the embedded bitmaps selected, otherwise the auto-generated (ugly) outlines will be used.
Try starting kitty with `-o font_size=12.0` for example with increments of `0.1` till you get it right for your screen ppi.

**Comment by iderik** [comment]
Here is a table of point versus pixel sizes for Terminus (TTF): https://files.ax86.net/terminus-ttf/
There is also some information about how to calculate point size for other DPI/PPI than 96 on that website.
