### ISSUE TITLE
Add option for unicode input

### ISSUE THREAD

**Issue by sirplatypos** [kovidgoyal/kitty#1060]
I find the menu you made for the Unicode input to be a really neat approach.  My problem is that I'm running Gentoo on an Asus X205TA, which has the power of my wooden desk as far as performance in any area.  The q key broke long ago, forcing me to use control shift u 71 instead.  My issue with the menu is that it takes a full second and a half to load, which as you can imagine is a massive slowdown when I'm just trying to insert an ASCII letter.  My last terminal was Termite, which would just underline the code point as you typed it until you hit enter.  I was wondering if it might be possible to add a feature where one can enable this style of Unicode insertion over the menu, for times when speed becomes more of a necessity.

**Comment by kovidgoyal** [comment]
Just use send_text for things like this, see https://sw.kovidgoyal.net/kitty/conf.html(search the page for send_text)
