### ISSUE TITLE
kitty cannot display in macOS(10.14) Mojave

### ISSUE THREAD

**Issue by WindProphet** [kovidgoyal/kitty#1061]
I install kitty 0.12.2 on macOS, when the system is upgraded to 10.14.
It cannot display.

<img width="731" alt="screen shot 2018-10-14 at 10 52 44" src="https://user-images.githubusercontent.com/13548240/46911721-55bd0200-cf9f-11e8-9d75-ef571d6ec1de.png">
When I resize the window, it can display again.

<img width="717" alt="screen shot 2018-10-14 at 10 54 04" src="https://user-images.githubusercontent.com/13548240/46911728-7b4a0b80-cf9f-11e8-8133-86a0ace2f09d.png">

**Comment by Luflosi** [comment]
Upgrade kitty to 0.12.3
