### ISSUE TITLE
FYI: kitty completions under fish

### ISSUE THREAD

**Issue by mqudsi** [kovidgoyal/kitty#1063]
Just a heads-up: when fish 3.0 is released, it'll have native support for kitty completions.

See https://github.com/fish-shell/fish-shell/commit/9c6bd8b1b4fc2069d1e9aed0945e1b9aff0f493d

**Comment by Luflosi** [comment]
@kovidgoyal Can we reach you via some means other than GitHub issues? I sometimes wish I could ask questions about how something is implemented, ask you to give advice on how to implement a new feature or ask you how you think certain details should work in kitty. This GitHub "issue" is also not an "issue" but "Just a heads-up" and might fit better in something like discord or a mailing list. But I can also totally understand it if you don't have the time and/or desire to answer potentially annoying questions.

**Comment by mqudsi** [comment]
_Technically_ this is an issue since the docs would need an update to drop the no-longer-needed installation instructions.

**Comment by kovidgoyal** [comment]
@Luflosi  you can always send me email, I wont promise to reply always, as I am quite busy, but I should be able to reply most times. I dont really have the time/interest to setup a mailing list. You can find my email address at the top of most kitty source code files.

I'm also fine using github issues for questions/.discussion. I will simply close the issue and continue discussion on the closed issue.

@mqudsi I'll be happy to modify the docs to note that the installation is only needed on older fish versions once fish 3.0 is released. Please ping this bug report or send a PR when that happens. I dont want to remove the instructions completely, as there might still be many people using older versions of fish, especially on linux.

**Comment by Luflosi** [comment]
Ok, thank you.
