### ISSUE TITLE
Underscore not visible with DejaVu Sans Mono size 10.0

### ISSUE THREAD

**Issue by wchresta** [kovidgoyal/kitty#1064]
I'm using kitty with NixOS Linux. Since the update to Kitty 0.12.3 the underscores in my `DejaVu Sans Mono` font are not displayed anymore. Changing the font size to 10.2 pt makes them appear again. It seems that the underscores just get cut off as the rest of the text displays normally.

![screenshot_2018-10-15_08-08-15](https://user-images.githubusercontent.com/34962284/46932777-7e053900-d051-11e8-9331-c868397d598d.png)

Playing around with it, it seems that only the font size 10.0 and 10.1 have this problem. Larger and smaller font sizes don't (I tried 9, 9.5, 9.9, 10.2, 11).

```
$ kitty --debug-config
kitty 0.12.3 created by Kovid Goyal
Linux host 4.18.12 #1-NixOS SMP Wed Oct 3 23:59:28 UTC 2018 x86_64
Running under: X11
<<< Welcome to NixOS 18.09.812.8cfce968b1a (\m) - \l >>>

Run `nixos-help` for the NixOS manual.
Loaded config files: /home/user/.config/kitty/kitty.conf

Config options different from defaults:
background           Color(red=40, green=40, blue=40)
color0               Color(red=40, green=40, blue=40)
color1               Color(red=204, green=36, blue=29)
color10              Color(red=184, green=187, blue=38)
color11              Color(red=250, green=189, blue=47)
color12              Color(red=131, green=165, blue=152)
color13              Color(red=211, green=134, blue=155)
color14              Color(red=142, green=192, blue=124)
color15              Color(red=251, green=241, blue=199)
color2               Color(red=152, green=151, blue=26)
color3               Color(red=215, green=153, blue=33)
color4               Color(red=69, green=133, blue=136)
color5               Color(red=177, green=98, blue=134)
color6               Color(red=104, green=157, blue=106)
color7               Color(red=168, green=153, blue=132)
color8               Color(red=146, green=131, blue=116)
color9               Color(red=251, green=73, blue=52)
cursor               Color(red=215, green=153, blue=33)
font_family          DejaVu Sans Mono
font_size            10.0
foreground           Color(red=242, green=229, blue=188)
selection_background Color(red=102, green=92, blue=84)
```

**Comment by wchresta** [comment]
Workaround: Use font size 9.9

**Comment by martinetd** [comment]
I had that problem too; ended up fixing it by overwriting the _ character with that of another font (picked Hack) with `symbol_map`.

It also works to set `adjust_line_height 1`, I didn't know point font sizes were a thing so I guess that's probably better... It looks like Deja Vu Mono just sets its underscore too low for some reason.

**Comment by kovidgoyal** [comment]
yeah I dont know of a good way to fix this in kitty, it is basically a bug in the font as best as I can tell. Workarounds include:

1) Adjust font size
2) Use adjust_line_height
3) Use symbol map to get the underscore from elsewhere

The only way this could be fixed in kitty is to override drawing of the underscore, which is pretty drastic to fix a bug in a single font.
