### ISSUE TITLE
macOS: When running from source, kitty is shown with a rocket launcher Python icon in Cmd-tab

### ISSUE THREAD

**Issue by ptbrowne** [kovidgoyal/kitty#1065]
<img width="109" alt="image" src="https://user-images.githubusercontent.com/465582/46939966-e3642480-d067-11e8-96c8-1fff637f1f0a.png">

Any idea what can be the problem ?

After cloning the repository, I did 

```
$ make
```

Then I saw that I lacked `librsvg` so I installed it via `brew`, re-ran `make`, and then saw the `logo` folder, and ran `python3 make.py`.

```
$ python make.py                                                                                                                                 Rendering at 256x256...
Rendering at 16x16...
Rendering at 32x32...
Rendering at 64x64...
Rendering at 128x128...
Rendering at 256x256...
Rendering at 512x512...
Rendering at 1024x1024...
```

I have the `kitty.iconset` now in `logo/`.

**Comment by Luflosi** [comment]
When running kitty with `python3 .` I get that icon both in cmd-tab and in the dock. Build kitty with `make app` and run the app as a workaround to get the kitty icon. I don't know if it's possible to get the icon when running with `python3 .`.

**Comment by ptbrowne** [comment]
Thanks, with the app it is working, I wonder what is lacking when running completely from the source.

**Comment by kovidgoyal** [comment]
macOS takes doc isonc from application bundles. When you run using python3 . the relevant bundle is the python3 bundle, which has the rocket as its icon. There is probably some cocoa API to programatically override the icon, but, it will still start with a rocket and then change, so the make app is a better solution.
