### ISSUE TITLE
Ligatures support

### ISSUE THREAD

**Issue by bugworm** [kovidgoyal/kitty#107]
Fira Code font.
Konsole
![image](https://user-images.githubusercontent.com/7214361/28996212-1b833998-7a04-11e7-9359-c3bf70e4b1a3.png)

Kitty
![image](https://user-images.githubusercontent.com/7214361/28996209-16e791ea-7a04-11e7-8657-14b8d563555c.png)

**Comment by kovidgoyal** [comment]
#50
