### ISSUE TITLE
Make current window zoom to fill the terminal window

### ISSUE THREAD

**Issue by Rameshv** [kovidgoyal/kitty#1070]
One of the features I use frequently in [tmux](https://sanctum.geek.nz/arabesque/zooming-tmux-panes/) is to zoom the currently active window to fill the terminal window when working with multiple split panes. Is there a way to do that in kitty?

A quick look at the docs reveals there is an option to set the bias to the layouts. And its restricted to 10 - 90%.  So I tried setting this `enabled_layouts grid,tall:bias=90,fat:bias=90` in the config. But this is not working as I expected.

It does make the 1st window to occupy 90% of the space, but not the currently active window.

Any ideas on how to make that work? If you think this is a reasonable feature, I could try fork and make a PR?

Awesome work by the way 👍

**Comment by kovidgoyal** [comment]
dup of #870
