### ISSUE TITLE
render << as <  in ligatures

### ISSUE THREAD

**Issue by dsewnr** [kovidgoyal/kitty#1074]
![image](https://user-images.githubusercontent.com/3303223/47031619-d0a23a80-d1a2-11e8-9c10-a5be6157ffd7.png)

Version: 0.12.3
OS: Ubuntu 18.04
Config:
```
font_family			FuraCode Nerd Font Mono
bold_font			auto
italic_font			auto
bold_italic_font		auto
dynamic_background_opacity	no
background_opacity		0.97
cursor				#ff2600
cursor_text_color		#f1c1c1
url_color			#0087BD
url_style			curly
active_tab_foreground		#000
active_tab_background		#eee
active_tab_font_style		bold-italic
inactive_tab_foreground		#444
inactive_tab_background		#999
inactive_tab_font_style		normal
mouse_hide_wait			3.0
focus_follows_mouse		no
copy_on_select			yes
enabled_layouts			tall:bias=50
```

**Comment by maximbaz** [comment]
Works for me with your config but with regular `Fira Code` font, try it too. Probably something is off in the Nerd font.

![image](https://user-images.githubusercontent.com/1177900/47032650-2ced6600-d173-11e8-8f69-b7804fb6ee6e.png)

**Comment by dsewnr** [comment]
Solved, thank you.
