### ISSUE TITLE
Option to choose font based on sequence of characters

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1078]
`symbol_map` gives us a really powerful way to mix and match fonts, but one thing I'm missing is the option to have one font for basically all characters and another like FiraCode for certain ligatures. If I wanted the `!=` from FiraCode for example, I could put `symbol_map U+21,U+3d Fira Code` into my `kitty.conf`. But then if there is just a `!` or a `=` on its own, that character is also displayed using Fira Code. And if I want the ligature for the time, like `9:45`, I'd have to display all the numbers (and colon) in Fira Code. For the special x in hexadecimal characters, I'd have to display all the hexadecimal characters and the x in Fira Code. Worse, for a special * in pointers, I'd have to use Fira Code for all characters allowed in C for variable names and *. Then there is really no point in using another font for the few remaining characters, it would probably just look inconsistent. It would be very nice to have something like `symbol_map U+21&U+3d Fira Code` or similar to mean that whenever there is a `!=`, kitty should use Fira Code for those two characters.

**Comment by kovidgoyal** [comment]
I'm afraid this is not something I am interested in implementing, sorry. It means that font lookups will become much slower, not a tradeoff that is worth it, IMO.

**Comment by Luflosi** [comment]
Font lookup would not have to become any slower if there are no config entries that specify a ligature, right?

**Comment by kovidgoyal** [comment]
you'd basically need to change the data structures used for lookup to accomaodate multiple codepoints, which would make things slower, even in the single codepoitn case, or you'd need to write completely separate code paths for the two cases, which is a lot of extra, similar code.
