### ISSUE TITLE
\b handling at the right margin

### ISSUE THREAD

**Issue by egmontkob** [kovidgoyal/kitty#1079]
The behavior of most terminal emulators, and the expectation of ncurses is that after printing a letter in the last (80th) column, a backspace character retreats the cursor to column 79. In Kitty the cursor ends up in column 80.

See [VTE 731155](https://bugzilla.gnome.org/show_bug.cgi?id=731155) for an ncurses test application that is mishandled by Kitty (just as it used to be mishandled by VTE).

See also [Konsole 399615](https://bugs.kde.org/show_bug.cgi?id=399615) for a relevant recent investigation on how certain other terminal emulators handle this situation.

(You might also want to take a look at [VTE 62](https://gitlab.gnome.org/GNOME/vte/issues/62) for some broader picture.)

**Comment by kovidgoyal** [comment]
thanks for the heads up, I'll look into this when I have a moment.

**Comment by kovidgoyal** [comment]
Hmm I took a look at this, and the behavior of most terminal emulators seems very wrong to me. Not being able to backspace the last character in a line when using cooked mode (cat) seems a severe bug. Not to mention that this behavior is "unnatural" both to implement and to use. It means you cannot use backspace in terminal applications without knowing the width of the terminal. And you cannot use backspace to delete the last character of the line in cooked mode interactively.

To me, this behavior is wrong and should be changed. I know of no actual modern terminal applications that rely on the behavior of backspace you describe, so I am inclined to not change kitty. That might well change if there is a significant application that does rely on this behavior. If so please update this bug report.
