### ISSUE TITLE
Alt+arrow over ssh - term info copied over

### ISSUE THREAD

**Issue by hanoii** [kovidgoyal/kitty#1081]
I am not sure how to make this work.

I have copied the term info to the ssh but still alt+arrow gives me a D on the remote server. it works on my OSX local shell.

It also works on iTerm (sshing to the remote), any ideas?

**Comment by kovidgoyal** [comment]
presumably you copied over the terminfo incorrectly. Run infocmp and make sure it is reporting the terminfo for kitty. And if you are using tmux, try it without tmux or in a new tmux session.

**Comment by hanoii** [comment]
Same infocmp (xterm-kitty) locally and remotely, no tmux. Any further ideas?

**Comment by Luflosi** [comment]
Can you try `kitty +kitten ssh myserver`, like described in https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer?

**Comment by hanoii** [comment]
Same behavior, I keep seeing D's being printed

**Comment by hanoii** [comment]
That made it work @Luflosi , thanks!

Would you mind explaining the issue/difference from standard setup?

**Comment by Luflosi** [comment]
I'm not sure what the default behaviour does but these two config lines send special escape codes to your shell/vim/whatever is running, which then hopefully interprets those escape codes as "move by word". If you execute the cat program (which does not interpret anything and just echoes everything back), you can get an idea of what gets sent.

**Comment by hanoii** [comment]
Interesting

without any setting it sends `^[[1;3D`

And with yours  sends `^[b`

The default works on `fish`, but as soon as I hit `bash`, it stops working.. does this make sense @kovidgoyal ? Just trying to get my head around this. Thanks!

**Comment by kovidgoyal** [comment]
And I should note that the kitty terminfo file specifies that `^[D` is the kcub1 capability, i.e. the left key. the modified forms with repetitiion counts are generated using ctrl+arrow key or alt+arrow key. Sadly various shells dont use terminfo to setup terminal key bindings, instead using various incorrect heuristics, which leads to situations like this.

**Comment by hoyhoy** [comment]
@Luflosi I spent over an hour trying to figure out why `backward-word` and `forward-word` wouldn't work over ssh.  The bindings worked locally on macOS, but over ssh I would get `;3C` and `;3D`...

This solved it though...
```
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66
```

Thank you!
