### ISSUE TITLE
[OS X] Screen mirroring switches kitty to smallest font that cannot be changed

### ISSUE THREAD

**Issue by baremetalfreak** [kovidgoyal/kitty#1083]
When an external monitor is connected in a screen mirroring mode under OS X (Sierra 10.12.6), kitty changes font size to something very tiny and it cannot be changed. The shortcuts for changing font size that normally work stop working. Also setting the size with kitty shell `set-font-size 15` no longer works.

**Comment by xiaket** [comment]
I can confirm that this is the case with High Sierra(10.13.6).

**Comment by kovidgoyal** [comment]
dup of #1056
