### ISSUE TITLE
slowdown when opening 3 kitty windows in i3

### ISSUE THREAD

**Issue by cycomanic** [kovidgoyal/kitty#1084]
I'm using i3 and when I open a third kitty window on the same screen everything in that window becomes extremely slow (>1s wait per keystroke). This happens on ubuntu 18.10 as well as 18.04 with latest git installed.

**Comment by kovidgoyal** [comment]
I have eleven kitty windows open in i3 right now, four of them currently
visible and notice no slowdowns. Make sure you actually have opengl
hardware rendering working. kitty performance problems are typically
caused by using mesa or another software opengl implementation.
