### ISSUE TITLE
I can't enter a # symbol on macos

### ISSUE THREAD

**Issue by d5ve** [kovidgoyal/kitty#1086]
I am using a macbook air with a UK keyboard. This has the £ (GBP/pound) symbol as the standard character when hitting `<shift>3`. To enter a # (hash/octothorpe/pound) symbol I hit `<alt>3` instead. This works in all other apps, including iterm2 and ssh connections to remote machines.

`<alt>3` doesn't work that way in kitty. Instead I see the text `(arg: 3)` appear in the lefthand side of the terminal. Pressing `<alt>3` twice makes `arg(33)` appear etc.

Does anyone know what I'd need to change to have `<alt>3` insert a # again? I'm reduced to keeping a # in a vim register so I can paste it in.

Cheers,

Dave.

**Comment by Luflosi** [comment]
Put `macos_option_as_alt no` in your `kitty.conf`.

**Comment by d5ve** [comment]
Heh, that was pretty obvious in retrospect!

Cheers @Luflosi!

**Comment by idmyn** [comment]
I've got # working with this setting but although the cursor moves along to indicate that it's been inserted, it appears invisible in zsh (but works fine in bash!) shell. Any idea why this might be?

**Comment by kovidgoyal** [comment]
probably something in your zshrc, try bisecting it.
