### ISSUE TITLE
Terminal crashes on input 

### ISSUE THREAD

**Issue by chrjen** [kovidgoyal/kitty#1087]
The terminal crashes when trying to display the example below. This includes using cat, vim, less, tail, etc. I am using kitty 0.12.3.

Name[te]=అడ్డదారుల కూర్పకం

Same, but outputted using xxd, can be reverted back to binary using command «xxd -r».
```
00000000: 4e61 6d65 5b74 655d 3de0 b085 e0b0 a1e0  Name[te]=.......
00000010: b18d e0b0 a1e0 b0a6 e0b0 bee0 b0b0 e0b1  ................
00000020: 81e0 b0b2 20e0 b095 e0b1 82e0 b0b0 e0b1  .... ...........
00000030: 8de0 b0aa e0b0 95e0 b082 0a              ...........
```

The crash gives the following error in the terminal «double free or corruption (fasttop)».

**Comment by kovidgoyal** [comment]
I cannot reproduce, running with:

kitty sh -c "xxd -r /t/crash.txt; read"

where /t/crash.txt contains the xxd output you posted. Post a backtrace for the crash, or a minimal kitty config that reproduces it. And what OS you are on.

**Comment by chrjen** [comment]
It crashes when trying to *display* the characters, not reading them.

Try `kitty sh -c "xxd -r /t/crash.txt"` instead, crashes for me.

**Comment by kovidgoyal** [comment]
The code I posted is displaying them, and no your command line does not
crash for me.

**Comment by kovidgoyal** [comment]
I'm not familiar with your distro, but in general. Build kitty from source with debug symbols using

make debug

https://sw.kovidgoyal.net/kitty/build.html


then use whatever facility your distro provides for generating backtraces. On systemd based systems, it is

echo bt | coredumpctl gdb

**Comment by kovidgoyal** [comment]
that's a crash in freetype, not kitty. Most likely freetype does not like whatever font is being used for those characters on your system. Probably some bitmap font. Install a scalable font that is capable of displaying those chars and you will be fine. My system uses Arial Unicode MS. 

Or run kitty with --debug-font-fallback which will show you what font is being used, and post that, I will take a look and see if I can workaround the crash in freetype.

**Comment by chrjen** [comment]
Well in that case I hope you will take this up with whoever is responsible for that library. In any case this is what I got running with kitty with `--debug-font-fallback`.

```
% kitty --debug-font-fallback
[297 03:57:28.451330] Preloaded font faces:
[297 03:57:28.451364] normal face: /usr/share/fonts/TTF/VeraMono.ttf:0
[297 03:57:28.451374] bold face: /usr/share/fonts/TTF/VeraMoBd.ttf:0
[297 03:57:28.451381] italic face: /usr/share/fonts/TTF/VeraMoIt.ttf:0
[297 03:57:28.451388] bi face: /usr/share/fonts/TTF/VeraMoBI.ttf:0
[297 03:57:28.786252] [PARSE ERROR] Unknown OSC code: 13
[297 03:57:28.786370] [PARSE ERROR] Unknown OSC code: 708
[297 03:57:28.786381] [PARSE ERROR] Unknown OSC code: 13
U+c05 Face(family=Unifont, style=Sans-Serif, ps_name=, path=/usr/share/fonts/misc/unifont.bdf, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
U+c21 U+c4d Face(family=Unifont, style=Sans-Serif, ps_name=, path=/usr/share/fonts/misc/unifont.bdf, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+c21 Face(family=Unifont, style=Sans-Serif, ps_name=, path=/usr/share/fonts/misc/unifont.bdf, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+c26 U+c3e Face(family=Unifont, style=Sans-Serif, ps_name=, path=/usr/share/fonts/misc/unifont.bdf, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+c30 U+c41 Face(family=Unifont, style=Sans-Serif, ps_name=, path=/usr/share/fonts/misc/unifont.bdf, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+c32 Face(family=Unifont, style=Sans-Serif, ps_name=, path=/usr/share/fonts/misc/unifont.bdf, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
double free or corruption (fasttop)
[1]    2387 abort (core dumped)  kitty --debug-font-fallback
```

**Comment by kovidgoyal** [comment]
now fixed by working around the freetype issue.
