### ISSUE TITLE
Kitty does not match some valid URLs/IRIs

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1089]
Kitty does not match `http://a.de`, even though it is a valid URI, in fact the domain name even resolves and seems to redirect to some random website. I think you're using a regex as a heuristic to match URLs (right?) and we should probably relax it a little. http://www.faqs.org/rfcs/rfc3987.html might be of interest, especially section `7.3.  URI/IRI Transfer between Applications` (three small blocks of text) and `2.2.  ABNF for IRI References and IRIs` (basically a bunch of rules to match an IRI). Some guy on stackoverflow claims to have a regex to match all IRIs although you need to decide if you want such a giant regex and also allow IRIs which are valid and should be anticipated but are probably not what a user would want to be matched in practice: https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url. I also did not test that regex with my example yet.

**Comment by kovidgoyal** [comment]
no it does not use a regex, and it deliberately does not match very short URLs as in practice these are very rare. IIRC, it has a limit of five or something similar. If you use the hints kitten instead, which does use a regex, your url will match.
