### ISSUE TITLE
Issue with font sizes

### ISSUE THREAD

**Issue by lcagustini** [kovidgoyal/kitty#109]
![mypicture](https://user-images.githubusercontent.com/3537599/29008066-ba8f7b04-7ae6-11e7-87e9-4dd532d9f750.jpg)

Kitty and xfce4-terminal side by side, both with 12pt font size.
For some reason kitty's font is way bigger than it should, even with the default config file.

**Comment by kovidgoyal** [comment]
Effective font size is a combination of DPI and specified font size. kitty gets its DPI value from the Xft.dpi X resource. I have no idea where xfce4-terminal gets it from, presumably from some xfce specific setting. Set Xft.dpi to the correct value and you will be fine. For example, on my system, with a high DPI monitor:

```
xrdb -query                                                                                                                                                    
Xft.dpi:       192
Xcursor.size:  48
Xcursor.theme: Oxygen_White
```
