### ISSUE TITLE
Availbility of a 'default command' to run after shell invocation?

### ISSUE THREAD

**Issue by arooni** [kovidgoyal/kitty#1094]
Hi!  

Coming from iTerm on Mac -- first off thanks for the amazing software -- was tired of my terminal taking 30% of my poor mac mini's cpu.

Q: I use tmux and I often just need to reconnect to the same tmux session upon opening a new terminal window.  So I'd like to run a default command for each time a kitty window is invoked.  So far I jsut see the value of shell in the config file and nowhere for a default command.  It would be nice to run my 'tmux attach-or-create SysAdmin' command as a default in kitty.  Ideas?

Note: I searched thru issues and the config file and didn't see a mention of this so if it's somewhere else -- my mistake.  

Unrelated:  After you're done editing the kitty config settings -- is there any way to apply these settings/changes other than restarting kitty?  Thanks!

**Comment by kovidgoyal** [comment]
Use

shell bash -c "some_command; bash -login"

**Comment by odrzutowiec** [comment]
@kovidgoyal `bash -c "bash -login"` doesnt work for me, kitty just hangs and doesnt show any screen at all (mac os)

**Comment by alexjordan** [comment]
@odrzutowiec I use the following in `.session` files to source specific environments for new shells, which seems to work fine:
```
# 1st window
cd /my/work/dir
launch bash -c "source ./myenv; exec bash -login"

# 2nd window
cd /my/other/dir
launch bash -c "source ./myenv; exec bash -login"
```
