### ISSUE TITLE
[0.12.3 on ubuntu] seeing output of "[1 q⏎" after every command

### ISSUE THREAD

**Issue by arooni** [kovidgoyal/kitty#1096]
Interestingly enough I don't see this happening on the same version and same config file on Mac.  

Seeing the [1q ⏎
after every command and before prompt again

**Comment by kovidgoyal** [comment]
that's because you have put something in your shell configuration to cause that. Use a new config or bisect your shell's configuration and you will be ine. Most likley something related to the shell prompt.

**Comment by arooni** [comment]
So if you first have 

set -x TERM screen-256color

in your config.fish file then run set -g fish_key_bindings fish_vi_key_bindings 

the error occurs with an otherwise empty fish config file.

So as long as TERM is set to xterm-kitty -- everything is fine.  It seems like this should be a valid line to set my TERM on fish shell.  So do you still not consider this a bug?  If not, how else am I supposed to set my TERM variable on fish shell on Ubuntu and still have vi bindings?

**Comment by kovidgoyal** [comment]
Do not change your TERM variable, if you do that, all sorts of things will break. And tmux has a bug where you cannot re-attach to sessions that were started under a different TERM variable. Simply start new sessions using ATERM=xterm-kitty and you will be fine.
