### ISSUE TITLE
Some font families can't be loaded

### ISSUE THREAD

**Issue by matj1** [kovidgoyal/kitty#1098]
When I set `font_family` in config to some values, it doesn't load the fonts and loads DejaVu Sans Mono instead. I've checked the names with `fc-list` and they should be correct.

Fonts families that were loaded:
- `DejaVu Sans Mono`
- `Source Code Pro`
- `Liberation Mono`
- `Fira Code`
- `Fira Mono`
- `Ubuntu Mono`

Font families that I couldn't get to load:
- `Linux Libertine Mono`
- `Latin Modern Mono`
- `Noto Sans Mono`

**Comment by kovidgoyal** [comment]
kitty will only use fonts that are detecxted as monospace by fontconfig, i.e. have spacing=100. Use kitty list-fints to see which fonts are correct or fc-list : family spacing | grep spacing=100

**Comment by matj1** [comment]
Is there a way to load fonts not listed as monospaced?

**Comment by Luflosi** [comment]
I'm pretty sure they need to be monospaced and there is no way around that.
