### ISSUE TITLE
Change font size only for the current window

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#1099]
Is there a way to change the font size only for the current window.
For example, I have 2 kitty windows created with *new_os_window* command. When I increase the font size in the first window, the font changes in the second window.
Is there a way to disable this behavior and apply the change only to the first window?
Thanks!

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#font-sizes

**Comment by mihaicristiantanase** [comment]
Works perfectly. Thanks!

**Comment by johnallen3d** [comment]
@kovidgoyal - Is there any way to do this via remote control?

**Comment by johnallen3d** [comment]
Actually I was looking to do this for a specific "split", which, based on [this issue](https://github.com/kovidgoyal/kitty/issues/405) I'm guessing won't be an option.

**Comment by kovidgoyal** [comment]
No only top level windows can have different font sizes, kitty windows within a single top level window cannot.

**Comment by wookayin** [comment]
(for those who find this issue from Google) As per [the documentation](sw.kovidgoyal.net/kitty/conf.html#font-sizes),

> To setup shortcuts for specific font sizes:
> ```
> map kitty_mod+f6 change_font_size all 10.0
> ```
> To setup shortcuts to change only the current OS window’s font size:
> ```
> map kitty_mod+f6 change_font_size current 10.0
> ```

**Comment by Evidlo** [comment]
I launch kitty with `--single-instance` (for faster startup time), which means that `change_font_size current` does not work.

Is there any way to get the fast startup time but a per-window font size?

**Comment by kovidgoyal** [comment]
On Sun, Jun 01, 2025 at 05:50:09PM -0700, Evan Widloski wrote:
> Evidlo left a comment (kovidgoyal/kitty#1099)
>
> I launch kitty with `--single-instance` (for faster startup time), which means that `change_font_size current` does not work.
>
> Is there any way to get the fast startup time but a per-window font size?

Font size can be changed per *OS Window*. --single-instance causes new
OS windows to be created, so it works fine.

**Comment by Evidlo** [comment]
I've tested this on `Kitty 0.41.1`, the latest version packaged on Debian, but it seems like the font size is still linked when kitty is launched with `--single-instance`.

Below, I've launched two Kitty instances from XFCE terminal with `--single-instance` and used the keyboard shortcut to increase the font size on the rightmost window.

![Image](https://github.com/user-attachments/assets/5330408d-22db-401d-9f86-ab84fc3184e7)

This does not happen when I launch without `--single-instance`

![Image](https://github.com/user-attachments/assets/4e5a9656-57a2-449f-af1e-cfcda2d80da7)

<details><summary>My kitty config:</summary>

```
font_family  Terminus (TTF)
bold_font    Terminus (TTF) Bold
font_size    13.5

window_padding_width 2

scrollback_lines 10000
adjust_line_height   -2
enable_audio_bell no
confirm_os_window_close 0
paste_actions quote-urls-at-prompt

open_url_with /home/evan/bin/copy

foreground #eeeeee
background #000000
# foreground #000000
# background #eeeeee

map ctrl+page_up scroll_page_up
map ctrl+page_down scroll_page_down

open_url_with firefox
mouse_click_url open_url

remember_window_size no
initial_window_width  800
initial_window_height 540

# --- Shortcuts ---

map ctrl+shift+minus change_font_size current -1.5
map ctrl+shift+plus change_font_size current +1.5
```

</details>

**Comment by kovidgoyal** [comment]
Does not reproduce for me with the steps:

1) kitty --config=NONE -1 -o 'map f1 change_font_size current +10'
2) kitty -1
3) Press f1 in one of the two kitty windows, the font size in only that window is increaed.

**Comment by Evidlo** [comment]
Thanks for the test case!  After some trial and error I determined that my config was wrong:

```
map ctrl+shift+minus change_font_size current -1.5
map ctrl+shift+plus change_font_size current +1.5
```

should have been

```
map ctrl+shift+minus change_font_size current -1.5
map ctrl+shift+equals change_font_size current +1.5
```
