### ISSUE TITLE
Can't build due to missing dependency that is present

### ISSUE THREAD

**Issue by geordieF** [kovidgoyal/kitty#11]
When I run `./setup.py build`, it stops and says `#error "glfw >= 3.2 is required"` glfw 3.2.1-1 is definitely installed (at leas according to pacman) and I have tried both the X11 and wayland versions..

**Comment by kovidgoyal** [comment]
Yeah, that was a typo. Update the source checkout and it should build again.

**Comment by geordieF** [comment]
@kovidgoyal Thanks, was using my laptop and didn't bother to check ;)
