### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by kerabromsmu** [kovidgoyal/kitty#110]
I'm trying to install kitty on Windows 7 pro. When I run the command "python setup.py build", it outputs "CC: gcc (5,1)", and doesn't seem to do anything after that. I can enter characters from keyboard, and they show on the screen, but there's no reaction.

Also, could not install all the required packages. Pip doesn't find these: glew, pkg-config. It finds fontconfig, but it fails to install with an error in a setup script.

**Comment by kovidgoyal** [comment]
kitty is not designed to work on windows. Windows programs use an entirely different API for interacting with terminals, which would need to be implemented for kitty to be useful for running windows command line programs. You could probably get kitty to run on windows 10 using the WSL and run unix programs in it, but that is about it.

**Comment by deevus** [comment]
😢
