### ISSUE TITLE
[Request] Selectively load separate kitty.conf files @ run time depending on the OS or allow casing

### ISSUE THREAD

**Issue by arooni** [kovidgoyal/kitty#1100]
So I have mostly got everything working the way I want it on both Mac & Ubuntu.  Trouble is I needed to tweak some things like fonts, as well as various keyboard shortcuts that work better for each enviornment.  

I then like to commit these to mr/vcsh to store my .dotconf files and have them more easily deployed on the different enviornments I work on (remote servers, multiple computers).  

So is there a way now, or do you plan on supporting a way to have different tweaks to the conf file depending on which OS kitty is running on?  

Thanks

**Comment by kovidgoyal** [comment]
Use the include directive which expands environment variablees in its path argument. https://sw.kovidgoyal.net/kitty/conf.html first couple of paragraphs

**Comment by Luflosi** [comment]
#811 might also be helpful.
