### ISSUE TITLE
[request] Add support to be default terminal on Ubuntu

### ISSUE THREAD

**Issue by arooni** [kovidgoyal/kitty#1101]
If you run the following, kitty is not an option.  I'm trying to get it so that the default to invoke terminal (ctrl+alt+t) loads kitty.  

[I]  ~/.l/k/bin  sudo update-alternatives --config x-terminal-emulator
                  
There are 8 choices for the alternative x-terminal-emulator (providing /usr/bin/x-terminal-emulator).

  Selection    Path                             Priority   Status
------------------------------------------------------------
  0            /usr/bin/roxterm                  50        auto mode
  1            /usr/bin/gnome-terminal.wrapper   40        manual mode
* 2            /usr/bin/koi8rxterm               20        manual mode
  3            /usr/bin/lxterm                   30        manual mode
  4            /usr/bin/roxterm                  50        manual mode
  5            /usr/bin/urxvt                    20        manual mode
  6            /usr/bin/urxvtc                   20        manual mode
  7            /usr/bin/uxterm                   20        manual mode
  8            /usr/bin/xterm                    20        manual mode

also tried with
gsettings set org.gnome.desktop.default-applications.terminal exec 'kitty'  without success

also would be nice to be able to invoke kitty via albert, or ubuntu launch menu.  right now i have to load up gnome-terminal to launch kitty which i have setup via a fish alias.  seems a bit convuluted.

**Comment by kovidgoyal** [comment]
You simply need to add kitty to whateever mechanism your distro is using for alternatives. THis is not something kitty can do itself since the installer does not run with root privileges.

As for making it available in the menus/launcher, read https://sw.kovidgoyal.net/kitty/binary.html#desktop-integration-on-linux

**Comment by martinetd** [comment]
This really is distribution specific, there's no standard "alternatives", much less if it's installed in your home (the alternatives are system-wide, and another user would no longer be able to run x-terminal-emulator unless your home is wide open).

If you had installed from a package I would say the maintainer needs to do the job, but in this case you have to figure out how to tell gnome what your default terminal is withotu relying on alternatives.

**Comment by JPYamamoto** [comment]
For everyone with this problem, I've found a workaround.
First you have to set kitty as an alternative:
`sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/kitty 50`
Remember to change `/usr/bin/kitty` to the path where you have the terminal installed.
Then, just update the alternative:
`sudo update-alternatives --config x-terminal-emulator`
And choose the option that points to kitty.

**Comment by aral** [comment]
To add to @JPYamamoto’s excellent answer, if you don’t want to hunt down where you have Kitty installed, just copy and paste the following, verbatim:

```sh
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator `which kitty` 50
sudo update-alternatives --config x-terminal-emulator
```

**Comment by delijati** [comment]
Kinda related has someone a kitty config that has the same keybindings as gnome-terminal ... i hate relearning keybindings ;)

**Comment by vietanhduong** [comment]
On ubuntu try this command :)

```
gsettings set org.gnome.desktop.default-applications.terminal exec 'alacritty'
```
