### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by NightMachinary** [kovidgoyal/kitty#1105]
Current behavior:
![image](https://user-images.githubusercontent.com/36224762/47652932-85255e80-db9c-11e8-99d4-6700d082d9b0.png)

Correct behavior (screenshot taken from Chrome which supports RTL :)) ):
به که چنین می‌گویی؟
![image](https://user-images.githubusercontent.com/36224762/47652982-a6864a80-db9c-11e8-941c-3d2677ea72c7.png)

**Comment by kovidgoyal** [comment]
RTL needs to be supported by applications that run in the terminal, not terminal emulators. THe task of editing RTL is too complex to implement correctly at the terminal level. That said, I believe there are some terminals that try to implement some form of RTL support, I think mlterm is the most prominent among them.

**Comment by NightMachinary** [comment]
@kovidgoyal Mlterm is not a cross-platform solution. And it’s definitely impossible to get ALL unix utilities to support RTL. It’s clearly a terminal issue. The thing is, kitty doesn’t even show RTL text correctly on its fucking prompt.
I get it that this might be hard to implement, and that there might not be contributors interested in doing it. That’s, well, pretty much the way the opensource development works. But there is no reason to close the issue.

**Comment by kovidgoyal** [comment]
kitty does not have a prompt, fucking or of any other kind. And given your tone, I have zero interest in explaining to you why terminals are not the right place to implement RTL support. If you are interested, google is your friend.
