### ISSUE TITLE
The "macos_hide_titlebar" option should be combined with "x11_hide_window_decorations"

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1106]
The `macos_hide_titlebar` config option doesn't just hide the titlebar, it hides all the window decorations including the window title, the red, yellow and green buttons, the border around the window, the rounded corners and the window shadow. Therefore a name like `macos_hide_window_decorations` seems more appropriate. I assume `x11_hide_window_decorations` does a very similar thing. But then what's the point in having separate options for macOS and X11? Why not just call the option `hide_window_decorations` and have it do nothing for Wayland?

**Comment by kovidgoyal** [comment]
I'm afraid rationalizing config option names is not worth the disruption it would cause, with people's config not working after updating. I am willing to break compat in kitty.conf if there is some actual new functionality/critical bug, but notsimply for the sake of rationalization.

**Comment by Luflosi** [comment]
Would creating the new option and making the old options be aliases of the new option work? We could then deprecate the old options. One issue I can see with this approach is if the user has an option that does not apply to the current operating system as with this change the option will become active for their platform. Another option would be to leave the old options like they are (and deprecate them) and just add the new option. What do you think?
