### ISSUE TITLE
Some incoherent char width?

### ISSUE THREAD

**Issue by martinetd** [kovidgoyal/kitty#1107]
I first noticed this when someone decided it would be fun to include the heart symbol `❤️` in their mail subject and the color line from mutt spilled out to the next line... so it looks like ncurses? thinks that this symbol should be one character wide, while kitty? or the font? thinks it should be two.

The coloring also only hits the first cell, e.g. if you use the command below, the background will be yellow for both cells of the clover but only for the first of the heart cells.
```
echo -e '\e[1;43mfoo🍀bar❤️moo\e[0m' 
```

Shells also do weird things with them, bash displays it correctly but has an off-by-one in character position... fish is worse than bash in that moving left/right on the line duplicates them... I can get it to display red letters somehow by typing before the heart :)
zsh prints the heart as `❤<fe0f>` (with another heart symbol)... in xxd, the first heart is `e29d a4ef b88f` while the second one `e29d a4` (if I remove the `<fe0f>` I can manipulate the smaller heart - they're displayed the same to me in firefox but if you copy/paste them in kitty they're different!...)

Anyway, I think kitty is probably correct on this one that these are two different characters, one wide and not the other, but I'd like to understand this a bit better and we'd probably want to fix the background to color both cells of the wide heart.
... and then tell ncurses/shells about this eventually...

**Comment by kovidgoyal** [comment]
kitty gets its wcwidth implementation from the up-to-date unicode standard. Se gen-wcwidth.py. Emoji characters have something called emoji presentation which determines whether they are two cells or one cell. Older emoji chars have a default of text presentation which means they are one cell wide, newer ones typically have default of emoji presentation which makes them two cells wide. Most terminal programs either have their own out-of-date width tables or use the system wcwidt implementation, which is typically even more out-of-date.

**Comment by martinetd** [comment]
Well yes I'm not really complaining about other programs, I just checked the mail subject header does encode the variant with the emoji variation selector so kitty is correct to display it as two cells... I'd be tempted to argue it's probably better (more coherent) to have everyone use the system's wcwidth instead of having yet another program with their own table, despite it being more up to date, but I can understand it's also got benefits so I won't suggest to change what we're doing.

That said there's something we're not doing properly either, try the echo command I gave and the second cell background of the heart isn't colored as it should

**Comment by kovidgoyal** [comment]
I used to have kitty use system wcwidth, but then realised it's the wrong way. Think of ssh. And different systems have widely varying wcwidth implementations. And many programs use their own wcwidth implementations already, most prominently, vim.

The only sane way is to hew to the standard.

As for the background issue, that definitely looks like a bug, can you open a separate bug report for that, and I will look into it.

**Comment by martinetd** [comment]
hmm yeah didn't think as far as ssh, I guess you're right.
And actually given this comes with a variation selector I guess it's not even a wcwidth problem, you can't fit 6 bytes in a wint_t; so as much as I wanted to think I could get away with reporting this to my libc I'll have to go to ncurses / check what mutt is actually doing :/

opening another issue for the background color
