### ISSUE TITLE
background color not applied to all cells of all wide chars

### ISSUE THREAD

**Issue by martinetd** [kovidgoyal/kitty#1109]
Some wide chars have an uncolored background for their later cells, e.g. in this example the clover correctly has both cells yellow but the heart only has the first one colored off:
```
echo -e '\e[1;43mfoo🍀bar❤️moo\e[0m' 
```

**Comment by kovidgoyal** [comment]
this is likely because of the variation selector, the cell only becomes wide alter, and that code path probably forgot to copy the cell attributes to the neighboring cell when the cell is made wide. Should be an easy fix, will look into it ina bit.

**Comment by martinetd** [comment]
Thanks!
