### ISSUE TITLE
KDE panel freezes when "copy_on_select" set to yes

### ISSUE THREAD

**Issue by ncsibra** [kovidgoyal/kitty#1110]
Hi,

I'm experiencing a strange issue on Manjaro with KDE, here's some system information first:
```
System:    Host: ncsibra-pc Kernel: 4.14.78-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: KDE Plasma 5.14.2 
           Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: MSI model: B250M PRO-VD (MS-7A74) v: 1.0 serial: <filter> UEFI: American Megatrends v: 1.40 
           date: 04/06/2017 
CPU:       Topology: Quad Core model: Intel Core i7-6700 bits: 64 type: MT MCP arch: Skylake-S rev: 3 L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 54544 
           Speed: 800 MHz min/max: 800/4000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
Graphics:  Device-1: NVIDIA GP107 [GeForce GTX 1050] vendor: ASUSTeK driver: nvidia v: 410.73 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.3 driver: nvidia resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 1050/PCIe/SSE2 v: 4.6.0 NVIDIA 410.73 direct render: Yes  
```
Kitty version is `0.12.3`.
`XDG_SESSION_TYPE=x11`.

When `copy_on_select`  set to yes and I select some text with the mouse and trying to change application with task switcher from the task bar, it does not responds for a few seconds, then show me the app I clicked on.
When pasting the selected text to the terminal, it works fine, even when I paste to an active window on my other monitor.
If I wait a few seconds after copying then switching app, it works.
Sometimes the digital clock on the panel freezes permanently and I need to restart plasmashell.
When `copy_on_select` set to no, it does not happening, copying with Ctrl+Shift+C and switching apps just works fine.

Any idea what can cause this?
Or is there any setting/flag/env variable I should try to fix it?

**Comment by ncsibra** [comment]
Could be handy when middle click is remapped so something else and I think simply used to it, because I both use windows and linux.

**Comment by kovidgoyal** [comment]
I looked at the code in kitty that implement it and it literally works by calling the same function as pressing ctrl+shift+c does. (set_clipboard_string) So I cannot see anything wrong in kitty code. Presumably the plasma applet simply cannot handle both types of clipboard data being set in quick succession.
