### ISSUE TITLE
Trouble with remapping previous_tab and next_tab (retains old/default mapping even after being remapped)

### ISSUE THREAD

**Issue by arooni** [kovidgoyal/kitty#1114]
To reproduce:

Run Ubuntu at latest kitty release version.

1) remap previous_tab and next_tab to something else; say
 map ctrl+page_up  previous_tab
 map ctrl+page_down  next_tab

2) notice that while the new commands do work to move to next and previous tabs... the default mapping is still mapped, namely

map kitty_mod+left previous_tab
map kitty_mod+right next_tab

...

Expected behavior would be after remapping to a new shortcut the old/default shortcut would no longer work.  I wouldn't have noticed it except I use a mapping of ctrl+shift+left/right arrows to move windows around in tmux and kitty doesn't seem to want to relinquish this particular shortcut.

Thanks in advance.

**Comment by kovidgoyal** [comment]
mappings dont work that way. You can have multiple mappings to actions. If you want to unmap a default mapping, map it to no_op, as noted in the shortcuts section of https://sw.kovidgoyal.net/kitty/conf.html

**Comment by arooni** [comment]
Seems similar to #285 

with the following config on Ubuntu; 
map no_op previous_tab
map no_op next_tab
map ctrl+page_up  previous_tab
map ctrl+page_down  next_tab

The default mapping of ctrl+shift+left/right arrows still seem reserved an unable for tmux.  On MacOS however, the no_op works fine.

**Comment by kovidgoyal** [comment]
OK I'll take a look
