### ISSUE TITLE
xdg-open prevents kitty from closing on bash exit

### ISSUE THREAD

**Issue by Tacklebox** [kovidgoyal/kitty#1117]
I'm not sure if this is by design or not, but if you use xdg-open to open a file, then later exit bash, the kitty window stays open and lets you type, despite bash having exited already.

Manually clicking the x in the corner still closes the window, and the window never becomes unresponsive.

If there are any troubleshooting steps that would help diagnose this let me know!

**Comment by maximbaz** [comment]
I don't reproduce, but sounds like something that would be work-arounded by adding [`close_on_child_death yes`](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.close_on_child_death) to your `kitty.conf`.

**Comment by Tacklebox** [comment]
That does solve the problem, My mistake!
Thanks for the help.
