### ISSUE TITLE
Scroll wheel is not working in tmux on Mac (to enter copy mode, or scrolling in vim)

### ISSUE THREAD

**Issue by arooni** [kovidgoyal/kitty#1118]
I started using kitty because I was tired of how slow iterm2 was for basic things.  Kitty is way faster!  It's amazing.  

Well anyway, I like tmux.  And I think a lot of people do too.  But what from what I gather the author doesn't like tmux very much.

But still it seems to me bugs #249 and #927 are not necessarily resolved.  

On 0.12.3, on Mac + tmux 2.8:

* When scrolling in regular terminal applications, scrolling up with the mousewheel loads kitty's buffer, not scrollback buffer thru tmux -- this is reproduced in #249.  

* when scrolling back in vim even with the author's suggested 
mouse=a
ttymouse=sgr

scrolling with the mouse wheel does not scroll within vim and again uses kitty's scrollback buffer.  #927 references this

I have 
bind-key    -T copy-mode-vi WheelUpPane       select-pane \; send-keys -X -N 5 scroll-up
bind-key    -T copy-mode-vi WheelDownPane       select-pane \; send-keys -X -N 5 scroll-down

in my .tmux.conf file

On Ubuntu 18.04 everything works just fine.  

Thanks in advance.

**Comment by kovidgoyal** [comment]
Sorry I'm really not interested in debugging tmux issues. As for vim, I cannot reproduce. With a vimrc of just

```
set mouse=a
set ttymouse=sgr
```

using the scroll wheel scrolls the contents of vim not kitty. Indeed I dont see how it is possible for kitty to scroll its own scrollback buffer, because in alternate screen mode (which full screen application like vim use) kitty has no buffer. 

I'm guessing you are using vim within tmux, just get rid of tmux and you will be a lot happier.

**Comment by ilAYAli** [comment]
I am also experiencing this issue.
Terminal scrolling works perfectly in iTerm2, Terminal.app and Alacritty
It is not related to vim.

Your "solution" of asking your users to stop using tmux is quite puzzling, as tmux is considered the best program for remote terminal management. 
It is fair enough if you do not want to support tmux, but then you should explicitly say so on the project homepage. Users shouldn't have to read through closed issues to see you are "not interested in debugging tmux issues".

**Comment by Luflosi** [comment]
I'm also using a Mac and I didn't have any problems with tmux. I'll try to help you later.

**Comment by kovidgoyal** [comment]
Umm why on earth would any user expect me to be willing to debug issues in third party software? I do it occassionally, when I believe that the issue could be an underlying issue in kitty. I dont believe that in this case.

**Comment by Luflosi** [comment]
I can't reproduce your issue. I'm using kitty from the latest master but the latest stable release should also work. I'm also using tmux 2.8, VIM  8.1, NVIM v0.3.4 and zsh 5.3 on macOS 10.14.3 Mojave. I deleted all contents in my `kitty.conf`, `.tmux.conf` and `.vimrc`. When scrolling with the mouse wheel (or touch pad in my case), I can make the cursor go up and down in vim and nvim and I can recall the previous or next commands in the shell in tmux. When I add `set -g mouse on` to my `.tmux.conf`, I can scroll in the scroll buffer of tmux. I have no idea why you're experiencing the issues you have, sorry.

**Comment by ilAYAli** [comment]
Setup: 
* `kitty 0.13.3` no additional configuration 
* `tmux 2.8` clean session with no tmux.conf 
`NVIM v0.4.0-337-gbe2a6c11e` not relevant as I do not need it to trigger the problem.

Test:
1) E.g `find /some/folder/containing/enough/files/to/scoll/the/terminal/`
2) Attempt to use MBP touch pad to scroll => fail, as in shows previous data, not contents of the tmux scroll buffer.

This works with:
* `iTerm Build 3.2.7`
* `Alacritty 0.1.0`
* `Terminal.app Mojave`

**Comment by kovidgoyal** [comment]
If you want the touchpad to scroll the tmux buffer, you need to add

set -g mouse on

in tmux.conf

**Comment by kovidgoyal** [comment]
Works for me and for luflosi, so I'm afraid you are not doing what you think you are doing. And the reason it works on other terminal emulators is probably because tmux stupidly tries to detect mouse protocol support based on the value of TERM which is xterm-256colors by default for all those terminal emulators and not for kitty.

This is a bug in tmux not kitty.
