### ISSUE TITLE
Kitty doesn't remember position on macOS screen

### ISSUE THREAD

**Issue by iandol** [kovidgoyal/kitty#1119]
Hi, using Kitty 0.12.3 on macOS 10.14.1 and `remember_window_size` enabled, when Kitty first starts it does not remember its position on screen. As I also have `draw_minimal_border` enabled I have to drag edges to get the window where I want it. It would be nice if kitty could remember its position as well as its size on a restart.

Thanks for a great minimalist terminal!

**Comment by kovidgoyal** [comment]
IMO window placement should be the responsibility of th eOS, not individual applications. For macOS I believe there are third party tools that allow you to save and restore window positions for individual applications, such as: https://www.macworld.com/article/2036191/mac-gems-stay-keeps-your-windows-exactly-where-you-want-them.html

**Comment by iandol** [comment]
@kovidgoyal — thanks for the reply, all other apps on macOS that I'm aware of do have their position remembered, I assume because they all use the OS API. I'm not a mac developer so cannot tell you how other apps do this, this was all I found, and it is part of the Cocoa frameworks:

https://developer.apple.com/documentation/appkit/nswindow/1526255-restorable 
https://www.raywenderlich.com/613-windows-and-windowcontroller-tutorial-for-macos 

Kitty's behaviour is currently different to most other apps, and yes this is a minor issue that can be worked around with 3rd party window managers.

**Comment by kovidgoyal** [comment]
The cocoa APIs are not really suitable, since kitty, being a terminal has special sizing requirements, its window size can either be remembered or depend on the font size, dpi and number of cells specified in its config.  It's probably possible to make ethis work with cocoa api, but I'm afraid its too much work, at least for me. Patches are welcome.

**Comment by orthodoX** [comment]
Started experimenting with kitty recently and I'm amazed how light and fast it is. I know it's been a while since this issue was closed, I must agree with @iandol, it's a bit irritating to readjust the position and size of the window all the time or have a third party app only for managing kitty window 😞

**Comment by rix0rrr** [comment]
+1, I would consider dropping kitty over something as trivial as this. I don't need lots of tiny needle pricks added to my daily routine, all day every day.

**Comment by bogdancss** [comment]
any updates on this?

**Comment by chrisgrieser** [comment]
I actually wanted to switch to kitty, and set up configs and a theme etc – but having to resize the window *every time* really is a deal breaker.

**Comment by Luflosi** [comment]
The _size_ can be adjusted. Look at the three options here: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remember_window_size.
Only the _position_ cannot.

**Comment by chrisgrieser** [comment]
when you remove window decorations from a mac app, the only way to move the window literally by resizing it though 🙈

**Comment by Luflosi** [comment]
Also see #3683. Unfortunately I haven't found the motivation to continue the linked PR.

**Comment by chrisgrieser** [comment]
ah, I see. a bit better, but still requires moving the window every time 🙁

**Comment by yuri-urban** [comment]
still no update on this? this is really annoying. the window size isn't a problem, but dragging the position every time it opens is very annoying. considering to switching to another terminal, such a pity...

**Comment by webservices-network** [comment]
I ended up resorting to 3rd party software to change position after kitty starts. Shouldn't have to use mouse or 3rd party to accomplish this though. Great apart from this bugginess I call it ;)

**Comment by MurtadhaInit** [comment]
I know it's been years but it really is a shame that such a bug has been ignored. The terminal is great apart from this usability issue.

You can't just drag the window every time you open the terminal, especially if you have the title bar (window decorations) disabled.

**Comment by NathanCummings** [comment]
I would also like to register my interest in this feature. Even using a 3rd party app to manage window placement (Rectangle in my case), it's still a pain to have to reposition kitty when other apps remember their position.

**Comment by kobzar** [comment]
Any updates?

**Comment by AigenUK** [comment]
> Any updates?

Got a feeling this will never be fix d now. Ended up using Wezterm.

**Comment by lucifer9** [comment]
I managed to achive this using Apple Script.
```applescript
if application "kitty" is running then
	tell application "System Events"
		set position of first window of application process "kitty" to {X_you_want, Y_you_want}
	end tell
end if
```
Use Script Editor to save the above to a file like `~/Documents/pos.scpt`, then in your `.bashrc` or `.zshrc` add 
```bash
osascript ~/Documents/pos.scpt
``` 
Remenber to add `kitty.app` and/or `/usr/bin/osascript` to `Accessibility` ( in `System Settings` -> `Privacy & Security` ).
One thing to note: new OS window created afterwards ( e.g. using `⌘ N` ) will be positioned at the location specified in the previous Apple Script. This may cause confusion in some usage scenarios.

**Comment by hotsno** [comment]
Latest nightly build has `remember_window_position` config option now
