### ISSUE TITLE
Characters inserted on vim startup if <Esc>P is bound

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#1120]
I have `<Esc>P i` bound to an action in vim. When starting vim some random characters are inserted into the buffer. If I remove the binding, this does not happen. This doesn't happen in other terminals, which is why I'm reporting it here instead of to vim.

I can reproduce it with this vim-config using vim 8.1:
```
nmap <Esc>P i
```

If I run `vim`, it will open with this already in the buffer: `1+r436f=323531+r6b75=1b4f41+r6b64=1b4f41+r6b72=1b4f41+r6b6c=1b4f41+r2332=1b5b313b3241+r2334=1b5b313b3241+r2569=1b5b313b3241+r2a37=1b5b313b3241+r6b31=1b4f50634843216`.

`kitty --debug-config` outputs:
```
kitty 0.12.3 created by Kovid Goyal
Linux george 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64
Running under: X11
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

Config options different from defaults:
```

**Comment by trygveaa** [comment]
Sorry, I see now that this happens in xterm as well, so the problem doesn't seem to lie in kitty. It doesn't happen in urxvt or termite though. I don't understand why it's happening, any debugging help would be much appreciated.

**Comment by kovidgoyal** [comment]
<ESC>P is the start of a device control sequence (DCS) escape code. Presumably if you map it, it will cause issues in terminal emulators that uses DCS codes, I know kitty and xterm do.

**Comment by trygveaa** [comment]
Aha! Thanks for the info.
