### ISSUE TITLE
Terminfo file should mention support for "full keyboard mode"

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#1122]
According to [this comment](https://github.com/mawww/kakoune/issues/2554#issuecomment-435720958), kitty must explicitly mention that it supports "full keyboard mode" in its terminfo database so that applications are able to make use of it.

/cc @Screwtapello

**Comment by kovidgoyal** [comment]
I'm happy to add it, though there should be no need in a full screen application like kakoune, since it can be queried via DECQRM.
