### ISSUE TITLE
Issue with Cyrillic input

### ISSUE THREAD

**Issue by sprainbrains** [kovidgoyal/kitty#1124]
OSX: 10.14.1
Kitty version: 0.12.3

When i tried to write a russian text so i got this UB:
![2018-11-06 13 12 38 mov](https://user-images.githubusercontent.com/10284309/48059930-88879e00-e1cb-11e8-99b9-f1dc3a65788b.gif)

`kitty --version` got a error:

> [310 13:19:17.290599] Failed to set locale with LANG: en_RU.UTF-8
> kitty 0.12.3 created by Kovid Goyal

**Comment by maximbaz** [comment]
Make sure `en_RU.UTF-8` locale is actually generated, not sure how you do it on Mac, but on Linux you edit `/etc/locale.gen` and then re-run `locale-gen` command.

**Comment by kovidgoyal** [comment]
you likely just need to set the the LANG variable to en_RU.UTF-8 system wide, then kitty will pick up and use it.

**Comment by sprainbrains** [comment]
Thanks. It helped.
