### ISSUE TITLE
16 colors are only for backgrounds

### ISSUE THREAD

**Issue by maksbotan** [kovidgoyal/kitty#113]
Hi. First of all, thanks for this awesome terminal!

I've tried settings `color0` -- `color15` to my favourite solarized values, but this seems to affect only background colors (`\033[4${color}m` stuff), but not foreground (`\044[3${color}m`).
Is this intentional? Can these color be overriden in the config too?

Thanks!

**Comment by kovidgoyal** [comment]
Not sure what you mean. In a normal kitty, running

```
printf '\033[32mtest'
```

Prints test in green foreground color.

Now running kitty as

```
kitty -o color2=\#ff0000
```

which sets the color2 option 

and doing the same printf command
prints test in red colro as expected.

**Comment by maksbotan** [comment]
Very strange, I'm sure I've seen strange behaviour as I described. However, now everything is ok...
Sorry for disturbing. I'll reopen if I can reproduce it again.
