### ISSUE TITLE
Flow control (ctrl+s, ctrl+q)

### ISSUE THREAD

**Issue by RaitaroH** [kovidgoyal/kitty#1134]
I cannot figure this out. I remapped in vim ^S and ^Q. I have in my zshrc (I start zsh in kitty by default):

```
stty ixany
stty ixoff -ixon
stty stop undef
stty start undef
```
Now, I open kitty, then I type `vim blabla` ^S and ^Q work fine, no problem there. On the other hand, if I do `kitty -e "vim"` ctrl+s and ctrl+q are gone. So I thought, kitty doesn't source the zshrc file, no problem, I will just run the commands in the terminal (didn't work), run them in vim with `!` (didn't work), put them in `.xprofile`! (didn't work). So am I just missing something? :)

**Comment by RaitaroH** [comment]
This is vim.desktop, it simply starts in the default terminal.
```
[Desktop Entry]
Comment[en_GB]=Edit text files
Exec=vim %F
Icon=vim
Name=vim
GenericName=Text Editor
NoDisplay=false
Path[$e]=
Categories=Utility;TextEditor;
StartupNotify=false
Terminal=1
TerminalOptions=
Type=Application
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
X-KDE-SubstituteUID=false
X-KDE-Username=
```

**Comment by kovidgoyal** [comment]
Terminals like kitty do not source shell startup files. They run programs (like shells) inside them which may or may not do that. When you run kitty -e vim there is no shell being run. vim is started directly. If you want to run vim inside a shell to ensure the shell's startup files are run, use something like

kitty zsh -c "source ~/.zshrc; vim"

**Comment by RaitaroH** [comment]
@koekeishiya So those commands have to be run again for every single terminal? That's why xprofile wasn't working? :thinking: 

Well, whatever, a bit too convoluted but alas.
