### ISSUE TITLE
Add nvim to the list of default editors?

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1136]
I know that it's already possible to set the editor with an environment variable and a config option but would you still be willing to add nvim to the list of default editors in utils.py? The list currently contains `vim`, `vi`, `emacs`, `micro` and `nano`. If your answer is yes, should it be before or somewhere after `vim`?

**Comment by erf** [comment]
Also add [vis](https://github.com/martanne/vis)?
