### ISSUE TITLE
SSH without writing files?

### ISSUE THREAD

**Issue by apnewberry** [kovidgoyal/kitty#1139]
Hello, I'm trying out kitty for the first time, and I'm enjoying it a lot so far.

I went to ssh to an Ubuntu 18.04 server and it said `tput: unknown terminal "xterm-kitty"`. From the [faq](https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer) I understand I'm supposed to copy some files over to the server with the `kitty +kitten ssh myserver` command. 

I haven't actually run into a problem yet, but I am worried about the situation where I'm sshing to fix a server that ran out of disk space, which happens sometimes, or where for some other reason I'm not able to write to disk. 

Is it possible to neatly handle this situation? Perhaps by using the terminfo in memory, or by falling back to a less capable protocol?

I'm not well versed in how terminals work, so I don't know if there's a solution that makes sense, or if I'd need to just temporarily switch to another emulator when I'm in that situation.

Thanks!

**Comment by Luflosi** [comment]
You only need to run `kitty +kitten ssh myserver` once, after that you can just as well use normal ssh. After the files have been copied, kitty works just like any other terminal and you shouldn't have to worry that there is no space left for the files.

**Comment by maximbaz** [comment]
And if you are ssh'ing for the first time using kitty to a server that has 0 bytes left, you can overwrite TERM variable via `$ TERM=xterm-256color ssh myserver`. This is not recommended and will break some features, but I imagine at that point of time you will have bigger problems at hand anyway 😉

**Comment by kovidgoyal** [comment]
There is no way to handle this without writing files, thanks to the poor
design of ncurses. It requires the terminfo database to be in the
filesystem. 

As others have said, you only need to do it once, and in an emergency,
you can always change the value of TERM to something like
xterm-256colors.

**Comment by josser** [comment]
Can you tell a bit more about what files is required?
When I connecting to some ssh server by my own user everything is working fine with ssh kitty 
However if I want to do sudo -u someother user it breaks (
