### ISSUE TITLE
Text colors

### ISSUE THREAD

**Issue by rightaway** [kovidgoyal/kitty#1142]
If you run `pygmentize -l shell file.sh` (using http://pygments.org/) where file.sh is a simple text file with some shell commands

```
#this is a comment
command --arg #another comment
```

It outputs different text colors for the comment and the other text if I'm using a different terminal but not in kitty where it's all the same color. Even though I customized all 16 color values in `kitty.conf`. Anything I can do to get the colors to appear differently as expected?

**Comment by maximbaz** [comment]
![image](https://user-images.githubusercontent.com/1177900/48514139-e9634600-e85d-11e8-94dc-85e38be9eef2.png)

Take [my config](https://github.com/maximbaz/dotfiles/blob/e720325ecc1b125f1288b9bd83369c61b94bc53d/.config/kitty/kitty.conf#L7-L41) and try to figure out what I did that you didn't do.

**Comment by kovidgoyal** [comment]
works for me. you probably changed the value of TERM from xterm-kitty to something else.
