### ISSUE TITLE
Margin redrawing glitches when creating a new window

### ISSUE THREAD

**Issue by joaocampinhos** [kovidgoyal/kitty#1144]
When creating a new (third) window with a configured margin, I end up with gibberish on the margin from the window that got shrinked. Here is an example with lines 16 and 17 showing. I have margin and padding set to `10.0`

It does not matter if it's vim or any other program.

Thank you!

Kitty 0.12.3
Mac OS X 10.13.6

![screen shot 2018-11-15 at 14 11 30](https://user-images.githubusercontent.com/239438/48558482-494f0080-e8e1-11e8-8334-079c1784c616.png)
![screen shot 2018-11-15 at 14 11 26](https://user-images.githubusercontent.com/239438/48558483-494f0080-e8e1-11e8-83c5-37c110eb3312.png)

**Comment by kovidgoyal** [comment]
likely the same as #1104 run from master and see if it fixes it, if not ping me and i'll re-open this bug.
