### ISSUE TITLE
ctrl + j and ctrl + k not working in vim (macosx)

### ISSUE THREAD

**Issue by yazgoo** [kovidgoyal/kitty#1145]
Hi,

When running vim on macos with `0.12.3`, ctrl + j and ctrl + k do not work as expected (changing vim window).

Should I change something in the configuration to make them work ?

Regard

**Comment by kovidgoyal** [comment]
works fine for me with running

kitty --config NONE vim 

with a minimal vimrc containing only

```
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
```

which is what is needed to map c-j/h to window up down
