### ISSUE TITLE
editing executable scripts with vim

### ISSUE THREAD

**Issue by koopa1338** [kovidgoyal/kitty#1160]
Hi,
i have some weird issue when I open shell or python scripts with vim
![screenshot_1911x187-20-11-2018](https://user-images.githubusercontent.com/20669804/48789833-39bf2580-ecee-11e8-8370-f1a33eef7c02.png)
The weird part is, that if I fullscreen the terminal the symbols go away. I also tried different fonts but the symbols still appear

**Comment by kovidgoyal** [comment]
you need to provide some kind of minimal kitty.conf and .vimrc to reproduce your issue. Certainly opening python files in vim works fine with kitty, since I do that all day long, everyday :)

**Comment by koopa1338** [comment]
here is my kitty.conf: https://hastebin.com/wagokowesi.css
and here is my vimrc: https://hastebin.com/ekapawonam.sql

**Comment by kovidgoyal** [comment]
neither of those links work for me, and I need a minimal pair of conf files, do some bisection on them to find the problematic setting, which will most likely be some vim plugin.

**Comment by koopa1338** [comment]
Ok, the plugin syntastic caused the error. I set the syntastic_check_on_open to 0 and everything works. the SyntasticCheck function doesn't cause the error.
