### ISSUE TITLE
How to use AddressSanitizer on macOS

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1162]
First, I'll have to say that I have no experience using AddressSanitizer.
I tried building kitty with `make asan`. When running kitty with `python3 .`, I get the following error:
```
==25587==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
```
I tried running kitty with `DYLD_INSERT_LIBRARIES='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib' python3 .`, which prints the same error message. I thought that environment variable may not be passed from python to the compiled part of kitty but it seems like there is a security feature in macOS that somehow prevents me from setting DYLD_* variables: `DYLD_TEST=whatever env | grep DYLD_` prints nothing, while `TEST=whatever env | grep TEST` prints `TEST=whatever`. What else could I try except to do this on Linux? It must be possible to use AddressSanitizer on macOS.

**Comment by kovidgoyal** [comment]
sorry, I have no idea. I was never able to get sanitizers to work in macOS, you can check in the .travis.yml, look for SANITIZE_ARG which is defined only for some linux builds. As i only build kitty on macOS in a VM trying to debug this/get it working was too much work for me. 

The best I can think of is to somehow get clang to link directly against the asan dylib when building rather than using dlopen.See line 505 in setup.py

**Comment by kovidgoyal** [comment]
You run it just as you would, if you were running kitty from source, instead of python3 . use ./asan-launcher .

Feel free to send a PR with docs.

**Comment by martinetd** [comment]
I don't have a mac around but on linux you can also link a library to a program after the fact, e.g. `gcc /usr/lib64/libasan.so.5.0.0 /usr/bin/python3 -o test` will produce an executable that behaves like `LD_PRELOAD=/usr/lib64/libasan.so.5.0.0 python3` except it would presumably load libasan sooner.
Something similar might be worth a try as an alternative to that `DYLD_INSERT_LIBRARIES` variable

**Comment by kovidgoyal** [comment]
Re-reading the original bug report, I see you were trying to run kitty as python3 .

that is the cause of the error message. Run it instead as 

./asan-launcher .

asan-launcher should be automatically linked against the asan lib.

**Comment by martinetd** [comment]
> asan-launcher should be automatically linked against the asan lib.

. . .except that setup.py has this:
```
sanitize_lib = ['-lasan'] if cc == 'gcc' and not is_macos else []
```
so it probably won't be of much use for mac, failing both checks :)

**Comment by Luflosi** [comment]
Ok, running kitty with `./asan-launcher .` does not print the error message. Unfortunately it still doesn't work correctly: When i compile kitty without AddressSanitiser and run it with `python3 .`, a new kitty instance starts. It has a rocket icon in the doc, shows up in cmd-tab and it properly focuses/unfocuses when I click on the window/click on another window. When I compile kitty with `make asan` and run it with `./asan-launcher .`, a new window opens, which is presumably a new kitty instance but it doesn't have its own doc icon, doesn't show up in cmd-tab and it looks like it is constantly in focus because the cursor is a block:
![block cursor](https://user-images.githubusercontent.com/15217907/48900273-38a70900-ee52-11e8-8840-746cec792a1f.png)
, even when another window has focus. I would expect the cursor to look like this when the window doesn't have focus:
![non-block cursor](https://user-images.githubusercontent.com/15217907/48900749-8d974f00-ee53-11e8-84e5-0956142ecd57.png)
When I click on the new kitty window/hopefully instance to try to give it focus, the kitty window responsible for running the start command remains focused. Typing stuff still writes to that window. Do you know what could be causing this?
