### ISSUE TITLE
Keystrokes are duplicated.

### ISSUE THREAD

**Issue by aboettger-tuhh** [kovidgoyal/kitty#1163]
Keystrokes are duplicated. I logged on to a remote system using an SSH connection.

![peek 2018-11-21 14-38](https://user-images.githubusercontent.com/17931448/48845091-ed322380-ed9b-11e8-9fde-fb014ae0302a.gif)

**Comment by kovidgoyal** [comment]
Make sure the kitty terminfo file is available on the remote system. See the kitty FAQ.

**Comment by aboettger-tuhh** [comment]
Thx
