### ISSUE TITLE
Memory leak: RES have exceeded 700 MB accidentally

### ISSUE THREAD

**Issue by bodqhrohro** [kovidgoyal/kitty#1165]
That's definitely not scrollback or something like that: I have just 4 tabs with less/vim or plain Bash. How do I debug it? Did not kill that process yet, but probably will soon, as it keeps growing.

kitty 0.12.3-1 on Debian 10, config:
```
font_family			Inconsolata Medium
font_size 			12

cursor				#00ff00
cursor_shape			underline
cursor_blink_interval		0.2
cursor_stop_blinking_after	0

visual_bell_duration		0.1

tab_bar_edge			top
tab_bar_style			separator
active_tab_background		#00ff00
active_tab_foreground		#000000
inactive_tab_background		#ffff00
inactive_tab_foreground		#666666

background_opacity		0.7
background			#000066

color0				#000000
color1				#cc0000
color2				#00cc00
color3				#cccc00
color4				#0000cc
color5				#cc0080
color6				#00cccc
color7				#d3d3d3
color8				#7f7f7f
color9				#ff0000
color10				#00ff00
color11				#ffff00
color12				#5c5cff
color13				#ff0080
color14				#00ffff
color15				#ffffff

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10
```

**Comment by bodqhrohro** [comment]
I made a dump from 0x562b6de06000 to 0x562ba2e85000, now investigating it with hexer. The dump is mostly filled with some patterns repeating with some changes every 8 bytes, probably graphics. Is that related to hardware accelerated nature of kitty, so it just started to keep rendered buffers in memory?

**Comment by Luflosi** [comment]
I don't think kitty keeps any rendered buffers in memory except maybe the current frame and the one before that but you'll have to wait for an answer from @kovidgoyal to be sure.

**Comment by bodqhrohro** [comment]
The xzipped dump takes only 2 MB, I can upload it for research if sure that it doesn't contain sensitive data.

**Comment by bodqhrohro** [comment]
Moreover, kitty keeps leaking even after restarting 😱 300 MB already, with only one tab with Vim.

**Comment by kovidgoyal** [comment]
this is likely a leak in the graphics drivers/opengl implementation. Do you have a working 3d driver on your system? What does kitty --debug-gl report?

**Comment by bodqhrohro** [comment]
I found the culprit!
```xdotool key 3270_CursorBlink```
When I run it, even if focus is on another window, kitty hangs for a while and it's memory consumption increases for several megabytes. So "pressing" 3270_CursorBlink from time to time causes a constant memory leak.

>  What does kitty --debug-gl report?
```
GL version string: '3.3 (Core Profile) Mesa 18.1.9' Detected version: 3.3
```

**Comment by kovidgoyal** [comment]
that indicates you are indeed using a software opengl driver, which is almost certainly the cause of your excessive memory usage. For comparison in my system with an intel GPU kitty uses ~16MB 

As for the cursorblink key, I have no idea what that is. What actual key does 3270_CursoBlink correspond to?

**Comment by bodqhrohro** [comment]
> that indicates you are indeed using a software opengl driver
Hmm, that's strange. `glxinfo` says:
```
OpenGL renderer string: AMD PALM (DRM 2.50.0 / 4.18.0-2-amd64, LLVM 6.0.1)
```
So why can't kitty pick it up?
> What actual key does 3270_CursoBlink correspond to?
I have no idea too; I have found it in `/usr/include/X11/keysymdef.h` in section of some plain old terminal, and used it for years for imitating user activity. That key does nothing on modern systems, and had no side effects until I ran the imitator along with kitty.

**Comment by kovidgoyal** [comment]
look at the direct rendering part of glxinfo.

**Comment by bodqhrohro** [comment]
```
direct rendering: Yes
```

**Comment by kovidgoyal** [comment]
Well I looked into this, and as far as I can tell the leak is not in
kitty code. I verified that by simply ignoring keypress and keyrelease
events in the x11 backend, and the leak was still present.

Given the obscurity of this use case, I'm afraid I am not going to spend
more time on it. But patches are welcome.

**Comment by bodqhrohro** [comment]
I investigated the bug deeper. "Pressing" 3270's keys triggers a sequence of XkbMapNotify events, on which kitty always generates a new keymap.

So the bug can be also reproduced with, for example:
```
while true; setxkbmap us,ru,uk; sleep 2; setxkbmap us,ru,gr; sleep 2; done
```
Which is less obscure use case, as X.Org supports switching among only 4 keymaps simultaneously, and some people may need more.

`valgrind` confirmed my assumptions:
```
==17746== 6,194,297 (3,072 direct, 6,191,225 indirect) bytes in 48 blocks are definitely lost in loss record 1,512 of 1,512
==17746==    at 0x48377D5: calloc (vg_replace_malloc.c:711)
==17746==    by 0x7A9C9C9: ??? (in /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0)
==17746==    by 0x7A9CC40: xkb_compose_table_new_from_locale (in /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0)
==17746==    by 0x79DBA4A: glfw_xkb_compile_keymap.constprop.45 (in /media/d/temp/git/kitty/kitty/glfw-x11.so)
==17746==    by 0x79E29A9: _glfwDispatchX11Events (in /media/d/temp/git/kitty/kitty/glfw-x11.so)
==17746==    by 0x79E47CC: glfwWaitEventsTimeout (in /media/d/temp/git/kitty/kitty/glfw-x11.so)
==17746==    by 0x59C893B: main_loop (in /media/d/temp/git/kitty/kitty/fast_data_types.so)
==17746==    by 0x50C3A0: ??? (in /usr/bin/python3.6)
==17746==    by 0x50FAD8: _PyEval_EvalFrameDefault (in /usr/bin/python3.6)
==17746==    by 0x50B518: ??? (in /usr/bin/python3.6)
==17746==    by 0x50C24C: ??? (in /usr/bin/python3.6)
==17746==    by 0x50FAD8: _PyEval_EvalFrameDefault (in /usr/bin/python3.6)
```
However, I did not found yet where the leak happens exactly. UK/US macros seem to work well. Probably the whole `_glfw.x11.xkb` is reassigned without unreferencing somewhere.

**Comment by kovidgoyal** [comment]
good find, thanks :)
