### ISSUE TITLE
fullscreen option

### ISSUE THREAD

**Issue by rtorresware** [kovidgoyal/kitty#117]
Is there a fullscreen option implemented?
Kitty does not seem to answer to f11, alt + enter or any other common commands.

**Comment by kovidgoyal** [comment]
Fullscreen is typically the resonsibility of the window manager, not the application. On macOS you click the fullscreen button, on linux, dpending on what window manager you use, there will be some method for making windows fulscreen.

**Comment by richardpl** [comment]
But no all wm supports that, and glfw allows fullscreen.

**Comment by kovidgoyal** [comment]
I've never heard of a window manager that does not support either maximizing windows to use all available space or making them fullscreen. In fact you can even do it from a script using xdotool with any EVMH compatible window manager.

**Comment by richardpl** [comment]
I'm using weston.

**Comment by kovidgoyal** [comment]
Why? weston is a toy compositor. Use something like sway instead. Not to mention that kitty is not fully functional under wayland anyway. You have to compile glfw from master and build glew with the EGL backend and even then auto-repeat wont work. Though I support you could probably run it under XWayland.

**Comment by richardpl** [comment]
Then I will add it myself.

**Comment by kovidgoyal** [comment]
Well, I decided implementing this is no harm, so https://github.com/kovidgoyal/kitty/commit/ff528604ddef3834eee00ab9e3c5a6e1f150478d

**Comment by Athesto** [comment]
`ctrl+shift+f11` this is the link to the manual
https://sw.kovidgoyal.net/kitty/conf/#miscellaneous
