### ISSUE TITLE
Some fonts appear shifted down

### ISSUE THREAD

**Issue by occivink** [kovidgoyal/kitty#1173]
OS: ubuntu 18.04
Kitty version: built from master, a7a7216b307c69f5533bf56a2c94935e80a16649
Kitty config: none

~~https://0x0.st/s0VB.png~~
~~As you can see on the cursor, the bracket character is not centered vertically.~~ 
edit: This seems to be because the Ubuntu Mono font is setup like that. Somehow alacritty renders it centered, which made me think that this was an issue on kitty's side. The following still applies:

If I add the following to my `~/.config/fontconfig/fonts.conf`:
```
<edit mode="assign" name="hinting">
    <bool>false</bool>
</edit>
```
https://0x0.st/s0Va.png
The characters are shifted even more, so much so that they get clipped.

This does not seem to happen with all fonts, I could reproduce it with Ubuntu Mono (screenshots), Noto Mono but not Fantasque Sans Mono, for example. My fonts are not patched, they're the default system ones.

I can alleviate this somewhat with `adjust_line_height` but I cannot achieve proper centering with it.

**Comment by maximbaz** [comment]
I'm wondering if they are even supposed to be centered, what governs this, the font itself?

Here's mine, not perfectly centered but I don't know if it should be.

![image](https://user-images.githubusercontent.com/1177900/49022762-f05f5200-f195-11e8-9950-e4137992f20a.png)

**Comment by occivink** [comment]
Yes I realized that this was actually part of the font (I inspected the font with [this tool](http://bluejamesbond.github.io/CharacterMap/)). However, there still seems to be an issue with hinting=false in fontconfig

**Comment by kovidgoyal** [comment]
I cannot replicate with hinting=false using ubuntu mono on my linux system, tried at several font sizes as well.

**Comment by occivink** [comment]
This is my ~/.config/fontconfig/fonts.conf stripped to the minimum:
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <match target="font">
        <edit mode="assign" name="hinting">
            <bool>false</bool>
        </edit>
    </match>
</fontconfig>
```
And my kitty.conf:
```
font_family      Ubuntu Mono
```

**Comment by kovidgoyal** [comment]
ah sorry, my testing was incomplete, forgot to use an empty kitty.conf, I can reproduce now.

**Comment by rjmk** [comment]
I have this issue and am using 15.1 which I think is after the fix commit. I have my font slighter smaller than I'd like, as at the next size up, the issue appears (and the size above that, it's gone again)
