### ISSUE TITLE
Window and tab title get set by `cat`ing /dev/random

### ISSUE THREAD

**Issue by Kyle-Verhoog** [kovidgoyal/kitty#1174]
kitty version: 0.12.3
macOS version: 10.13.6
config: none
shell: zsh v5.5.1

As per the title. It seems like `cat`ing /dev/random or /dev/urandom (for whatever reason someone may want to do this) will cause the window and tab title to be set to a string of random bytes. Maybe escape codes are being generated by /dev/random which are triggering the change?

Steps to reproduce:

```
$ cat /dev/random
```

Result:

![screen shot 2018-11-26 at 5 23 04 pm](https://user-images.githubusercontent.com/6321485/49027203-f5290380-f19f-11e8-89dc-b7d4e65a5d18.png)

**Comment by kovidgoyal** [comment]
Well yes, if you cat random bytes, sooner or later there will come an
escape sequence that will have some visible effects. The most common is
the audio bell, catting random bytes will trigger it repeatedly. But
other escape sequences can be triggered too.

**Comment by Kyle-Verhoog** [comment]
Gotcha. This was just something that I noticed that hasn't been an issue in other terminal emulators I've used before. Thought it might be a symptom of something undesirable.

**Comment by kovidgoyal** [comment]
Nah kitty is probably just more catholic in what it accepts when parsing
escape codes, so the likelihood of random bytes trigerring an escape
code is higher.
