### ISSUE TITLE
readline woes

### ISSUE THREAD

**Issue by daniel-pfeiffer** [kovidgoyal/kitty#1176]
On Ubuntu 18.10 I have the following software (though remote very old bash & readline give me the same behaviour)
bash 4.4.19   (shopt -s extglob; set -o emacs)
readline 7.0
GNOME Terminal 3.30.1
kitty 0.12.3

In gnome-terminal (even with `\[\e[…m\]` in PS1) long inputs just wrap around cleanly to next lines, and I can use left & right arrow-keys to go back over several lines upto after the prompt.

But in kitty (even with plain `PS1='$ '`) the first wrap goes around to the beginning of the same line, overwriting the prompt.  Then sometimes it will wrap to the next line.  Going back with arrow keys, will make overwritten lines appear one before another, above the original line, where the prompt used to be.

It is independent of terminfo, as `TERM=xterm-256color bash -i` in kitty behaves the same.

**Comment by tfkhsr** [comment]
I can second that on macOS. When wrapping a line of text the prompt simply deletes the currently existing line and starts from the beginning.

Can we somehow help to debug it?

**Comment by tfkhsr** [comment]
I think I found a solution: Apparently we need to set the UTF8 explicitly, hence I declared in my .zshrc:

```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

And this make prompt breaking working perfectly. Also it got rid of an tab autocomplete issue where the tab did not clear previously typed chars.

Does this work for you as well?

**Comment by daniel-pfeiffer** [comment]
@tfkhsr This is amazing!  On my remote connections I have locale C, and your solution indeed seems to solve it – wow!

What totally baffles me, is that I had tried this locally, where I already had UTF-8 locales (Ubuntu gives me a hodgepodge of Esperanto and French, apparently support for the former is not complete).  Without changing anything yet (I know, they all say that…), suddenly it's working just because of reading your workaround. 🤔

**Comment by daniel-pfeiffer** [comment]
Oh no, I just sudo'ed remotely, where I have a longer PS1, and there with UTF-8 locale it's worse than before:  The **cursor** now starts out **in the middle of the prompt**.  I have:

    0000000   \   [   \   e   [   3   m   \   ]   $   {   ?   #   0   }   \
             5c  5b  5c  65  5b  33  6d  5c  5d  24  7b  3f  23  30  7d  5c
    0000020   [   \   e   [   0   m   \   ] 360 237 224 247   \   [   \   e
             5b  5c  65  5b  30  6d  5c  5d  f0  9f  94  a7  5c  5b  5c  65
    0000040   [   1   ;   4   m   \   ]   \   u   \   [   \   e   [   2   4
             5b  31  3b  34  6d  5c  5d  5c  75  5c  5b  5c  65  5b  32  34
    0000060   m   \   ]   @   \   h   :   \   w   $   \   [   \   e   [   0
             6d  5c  5d  40  5c  68  3a  5c  77  24  5c  5b  5c  65  5b  30
    0000100   m   \   ]  \n
             6d  5c  5d  0a

Italic exit-code if not 0, a wrench, and the rest bold, with username underlined.

**Comment by kovidgoyal** [comment]
Check your terminfo availability. And no changing TERM is not a check,
you have to make the kitty terminfo available on the server, see the
kitty FAQ

**Comment by daniel-pfeiffer** [comment]
I can't `kitty @ ssh` because Balabit is f@&!ed up ssh.  Whatever you're attempting there, gives an "exec request failed on channel 1" with return code 255.  :(

You suggest recompiling it on the remote server, but also I can't because there's no compiler available.

I have the local file copied to remotehost:.terminfo/x and export TERMINFO pointing to it when I sudo.  Mostly working fine, e.g. less stopped complaining after I did that, and seems to work well.

I don't get how sudo interferes here.  I tried `-Pi` (no good, dumb shell), `-Ps` or command `-P bash -i`.  Then I source my own .profile & .bashrc.  I had an stty command, but also removed that to no avail.

**Comment by kovidgoyal** [comment]
sudo filters out (depending on how it is configured) various env vars.
It is likely filtering out TERMINFO.

**Comment by daniel-pfeiffer** [comment]
Yes, I set it again in .profile if not running as myself (i.e. sudo).

**Comment by daniel-pfeiffer** [comment]
Just 1 command after sudo -Ps suffices to do this (locale is preserved):
PS1='\[\e[3m\]${?#0}\[\e[0m\]'"♬a\[\e[1;4m\]\u\[\e[24m\]@\h:\w\$\[\e[0m\] "
A combination of ANSI-sequence and wide-character seems to be necessary.  Also whether this happens depends on how long the expansion of \w is:  just ~ is fine, but else the longer the path, the further right inside the prompt the cursor is.

Exactly the same steps on gnome-terminal work, with 1 difference:  The wide character is displayed wide, but occupies just one cell, i.e. next character overwrites the right half of it.

What can I do to help you understand this?  Strace kitty & bash at the same time?

**Comment by kovidgoyal** [comment]
your problems are likely because bash incorrectly expects the wide character to be narrow. kitty uses char width from the unicode standard, the various shells use outdated/buggy wcwidth implementations. If the shell and the terminal emulator disagree, then you have problems like what you describe.

**Comment by daniel-pfeiffer** [comment]
Yes, but it must be something that kitty does differently than gnome-terminal, because everything else I did is identical.  Only under kitty does readline sometimes get completely confused about prompt width.

G-T otoh seems to not realize that it's printing the emoji wider than it thinks.  That bug is more benign, because I could compensate it with a space or maybe \[ \].

**Comment by daniel-pfeiffer** [comment]
Ok, I think I got it now: I source my private .profile as the 1st command to the sudoed bash.  Apparently that's too late.  Readline/curses has already been setup and doesn't notice TERMINFO being set.  If I then `exec bash -i` and set the prompt again, it works. 🤬

I discovered C-x C-r but that's not enough.  I apparently need to exec a new bash and then reread my private .bashrc (which sets the prompt). 😖

**Comment by kovidgoyal** [comment]
> G-T otoh seems to not realize that it's printing the emoji wider than it thinks. That bug is more benign, because I could compensate it with a space.

Yes, but G-T rendering it in a single cell is *wrong* as per the unicode standard. It just works because both bash and G-T happen to have the same bug, that cancels itself out.
