### ISSUE TITLE
Potential mistake

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1178]
From kitty/freetype.c, around line 61:
```C
#ifdef FT_ERRORS_H
#include FT_ERRORS_H
#else
    FT_ERROR_START_LIST FT_ERROR_END_LIST
#endif
```
I think the line with the `#include` contains a mistake. I don't think there is anything named `FT_ERRORS_H` that could be imported.

**Comment by kovidgoyal** [comment]
Sure there is:

https://www.freetype.org/freetype2/docs/reference/ft2-header_file_macros.html

**Comment by Luflosi** [comment]
Ok, my bad, sorry. Unusual to use macros for includes though.
