### ISSUE TITLE
fontconfig: does not find bold/italic for font with multiple family names

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#1190]
`fc-query Ligaiosevka-term-regular.ttf` displays `fc-family: "Iosevka Term"(s) "Liga Iosevka Term"(s)`, which I interpret as mutliple families.

In kitty.conf I am using `font_family Liga Iosevka Term`, i.e. the second name.

Kitty loads the font properly, but then fails to find the bold etc variants for it:
```
[334 23:07:53.043393] normal face: /home/user/.fonts/Ligaiosevka-term-regular.ttf:0
[334 23:07:53.043475] bold face: /home/user/.fonts/Ligaiosevka-term-regular.ttf:0
[334 23:07:53.043554] italic face: /home/user/.fonts/Ligaiosevka-term-regular.ttf:0
[334 23:07:53.043625] bi face: /home/user/.fonts/Ligaiosevka-term-regular.ttf:0
[334 23:07:53.043703] Symbol map faces:
[334 23:07:53.043772] /home/user/.fonts/Hack Regular Nerd Font Complete.ttf:0
[334 23:07:53.043842] /usr/share/fonts/TTF/DejaVuSansMono.ttf:0
```

It uses `Ligaiosevka-term-regular.ttf` for all of them.

From a quick look this appears to be kitty not finding/handling the "Liga
Iosevka Term" family.

```
> …/Vcs/kitty/kitty/fonts/fontconfig.py(36)

  34     @lru_cache()                                                                                                                                                                         
  35     def all_fonts_map(monospaced=True):                                                                                                                                                  
  36  ->     return create_font_map(fc_list(monospaced))                                                                                                                                      
(Pdb++) [x for x in l if x['path'] == '/home/user/.fonts/Ligaiosevka-term-bold.ttf']
[{'path': '/home/user/.fonts/Ligaiosevka-term-bold.ttf', 'family': 'Iosevka Term', 'style': 'Bold', 'full_name': 'Liga Iosevka Term Bold', 'postscript_name': 'LigaIosevka-Term-Bold', 'weight': 200, 'slant': 0, 'index': 0, 'scalable': True, 'outline': True, 'color': False, 'spacing': 'MONO'}]
```

Relevant C code: https://github.com/kovidgoyal/kitty/blob/819ee94a70163be5317be09660907dd01d709a97/kitty/fontconfig.c#L39-L44

I am not sure how to handle this (i.e. if it should be a list internally, and/or just have multiple entries in the map(s) - and could not find documentation on how to query this even in the first place).

In this case the candidate is returned via `selector="full_map"` in https://github.com/kovidgoyal/kitty/blob/819ee94a70163be5317be09660907dd01d709a97/kitty/fonts/fontconfig.py#L62-L66.

Skipping this code and using `fc_match` here appears to work:
```
Pdb++) fc_match(family, True, False)
{'path': '/home/user/.fonts/Ligaiosevka-term-bold.ttf', 'family': 'Iosevka Term', 'style': 'Bold', 'full_name': 'Liga Iosevka Term Bold', 'postscript_name': 'LigaIosevka-Term-Bold', 'weight': 200, 'slant': 0, 'hint_style': 2, 'index': 0, 'subpixel': 1, 'lcdfilter': 1, 'hinting': True, 'scalable': True, 'outline': True, 'color': False, 'spacing': 'MONO'}
```

**Comment by blueyed** [comment]
I.e. this works:
```diff
 kitty/fonts/fontconfig.py | 34 +++++++++++++++++++---------------
 kitty/fonts/render.py     |  1 +
 2 files changed, 20 insertions(+), 15 deletions(-)

diff --git i/kitty/fonts/fontconfig.py w/kitty/fonts/fontconfig.py
index 5ef2912b..f5042a0d 100644
--- i/kitty/fonts/fontconfig.py
+++ w/kitty/fonts/fontconfig.py
@@ -49,23 +49,27 @@ def family_name_to_key(family):
 
 
 def find_best_match(family, bold=False, italic=False, monospaced=True):
-    q = family_name_to_key(family)
-    font_map = all_fonts_map(monospaced)
-
-    def score(candidate):
-        bold_score = abs((FC_WEIGHT_BOLD if bold else FC_WEIGHT_REGULAR) - candidate.get('weight', 0))
-        italic_score = abs((FC_SLANT_ITALIC if italic else FC_SLANT_ROMAN) - candidate.get('slant', 0))
-        monospace_match = 0 if candidate.get('spacing') == 'MONO' else 1
-        return bold_score + italic_score, monospace_match
-
-    # First look for an exact match
-    for selector in ('ps_map', 'full_map', 'family_map'):
-        candidates = font_map[selector].get(q)
-        if candidates:
-            candidates.sort(key=score)
-            return candidates[0]
+    # q = family_name_to_key(family)
+    # font_map = all_fonts_map(monospaced)
+    #
+    # def score(candidate):
+    #     bold_score = abs((FC_WEIGHT_BOLD if bold else FC_WEIGHT_REGULAR) - candidate.get('weight', 0))
+    #     italic_score = abs((FC_SLANT_ITALIC if italic else FC_SLANT_ROMAN) - candidate.get('slant', 0))
+    #     monospace_match = 0 if candidate.get('spacing') == 'MONO' else 1
+    #     return bold_score + italic_score, monospace_match
+    #
+    # # First look for an exact match
+    # for selector in ('ps_map', 'full_map', 'family_map'):
+    #     candidates = font_map[selector].get(q)
+    #     if candidates:
+    #         candidates.sort(key=score)
+    #         return candidates[0]
+    possibility = fc_match(family, bold, italic)
+    if possibility:
+        return possibility
 
     # Use fc-match to see if we can find a monospaced font that matches family
+    font_map = all_fonts_map(monospaced)
     possibility = fc_match(family, False, False)
     for key, map_key in (('postscript_name', 'ps_map'), ('full_name', 'full_map'), ('family', 'family_map')):
         val = possibility.get(key)
```

**Comment by blueyed** [comment]
The fonts are from https://github.com/be5invis/Iosevka/issues/248#issuecomment-414131620.

**Comment by kovidgoyal** [comment]
fc_match is deliberately not used first, because it will always return something, even if it does not match at all.

**Comment by kovidgoyal** [comment]
this font is just weird. Its regular variant does not have the word "regular" in its full and postscript names. And its family name is Iosevka Term instead of Liga Iosevka Term. Either change the font to fix these two issues or use explicit names/paths instead of auto in kitty.conf. I dont really see how kitty is supposed to select the variants of that font automatically.

Note that automatic selection will work if yu uninstall the normal Iosevka and use font_family Iosevka Term in kitty.conf. This is because the actual family name of the above font files is Iosevka Term not Liga Iosevka Term.

**Comment by blueyed** [comment]
Thanks for the explanation.
The font appears to be weird due to the patching necessary to make it work with Kitty in the first place.  It is unfortunate that Kitty then also cannot handle it correctly.. ;)

What about the point that there are multiple family names apparently, but Kitty only uses the first one?

**Comment by kovidgoyal** [comment]
well iosevka is a pretty weird font to start with. I have no idea why it is designed with inifinte length ligatures as a design goal.

there is only one family name, "Iosevka Term" really the font should have a different family name, especially if it is intended to be used alongside normal iosevka.

**Comment by blueyed** [comment]
Yes, the patching of the font certainly could be improved.

However, I am seeing two family names with `fc-query Ligaiosevka-term-regular.ttf`: `family: "Iosevka Term"(s) "Liga Iosevka Term"(s)` - don't you see this also?

(I've fixed this for myself now by using only the first one in my config.

**Comment by kovidgoyal** [comment]
Fonts have many names. there is a family name, a full name and a
postscript name. The patched font has a full name of Liga Iosevka Term
Bold/Italic/Whatever and a family name of Iosevka Term. The family name
should be Liga Iosevka Term if you want to use it alongside iosevka
term, otherwise install only it and use it in kitty.conf as Iosevka
Term, it will work fine.

**Comment by blueyed** [comment]
But what about `fc-query` returning two family names here?
It looks like a list of string ("(s)") to me.

**Comment by kovidgoyal** [comment]
the output of fc-query shows the family and then the full name
