### ISSUE TITLE
Map keys depending on terminal mode

### ISSUE THREAD

**Issue by yurikhan** [kovidgoyal/kitty#1193]
It might be nice to be able to map keys differently for normal and application terminal mode.

The specific case that I’d like to achieve is:

* In normal mode, I want `Shift+Page Up` and `Shift+Page Down` bound to buffer scrolling actions `scroll_page_up` and `scroll_page_down`, because pretty much all terminal emulators use these exact keys for buffer scrolling.

* However, in application mode, there is no need nor possibility of scrolling. Moreover, editors and terminal multiplexers work in application mode, and those want `Shift+Page Up` and `Shift+Page Down` for their own purposes. Specifically, in editors such as mcedit or emacs with cua-mode, they are used to extend selection by a page; in terminal multiplexers, they should be available for buffer scrolling. Therefore, in application mode, I want `Shift+Page Up` to send the `CSI [ 5 ; 2 ~` sequence (and have it described as `kPRV` in terminfo), and `Shift+Page Down` to send `CSI [ 6 ; 2 ~` (`kNXT`).

The following does not achieve the desired result:

```
map shift+page_up send normal \x1b[5;2~
map shift+page_up scroll_page_up
```

As a workaround, it might be achieved by writing a kitten whose `main` only returns a non-`None` result, and whose `handle_result` checks the current window’s mode and does the dispatch; but it will cause unpleasant flicker when the kitten’s `main`’s result is printed in the overlay window.

**Comment by kovidgoyal** [comment]
Not sure what you mean by application mode? If you mean when the alternate screen of the terminal is active, then yes there is no way to map keys specifically for that. But you can do that using a kitten, without screen flicker. See the code I added recently to the kitten subsystem to run kittens without any UI. See docs/kittens/custom.rst for details.

**Comment by yurikhan** [comment]
Ooh, nice.

Yes, in my mind, the DECCKM mode where cursor keys send SS3 codes got mixed up with the alternate screen buffer mode because they are often used together.

Anyway, I think UI-less kittens are a great addition and go a long way toward a fully scriptable terminal emulator. Thanks!

**Comment by yurikhan** [comment]
I ended up with [this kitten][1], maybe somebody will find it useful.

[1]: https://github.com/yurikhan/kitty-smart-scroll
