### ISSUE TITLE
j and k do not repeat in vim

### ISSUE THREAD

**Issue by jmarchello** [kovidgoyal/kitty#120]
Generally, when I hold the j or k keys, the cursor will scroll down or up in Vim. This is not working. (it works fine in iTerm2). The h and l keys do repeat though.

**Comment by kovidgoyal** [comment]
Works fine for me. Indeed, as vim is my primary editor, I use it all the time in kitty. It is likely something in your config. Start vim with the default config as

vim -u NONE

and kitty with default config as

kitty --config NONE

**Comment by jwkvam** [comment]
I see this issue in the shell itself (I use fish).

**Comment by kovidgoyal** [comment]
Run

kitty cat


Then see if your issue is still present (i.e. hold down the j key)

If not then it is something in your shell config. Probably something you inserted at some point to specialise it for some other terminal.

**Comment by jwkvam** [comment]
Yea same thing happens when running `cat`. This probably sounds crazy but the keys that _do_ repeat are the same ones that have accent pop up menus. For example:

Working keys include: a, z, s, o, n, c
Non-working keys include: h, j, k, d, w, f

Consequently, I also see this in bash, vim, etc. This is without making a config and I'm on macos :/

**Comment by kovidgoyal** [comment]
Then it is something specific to your system + glfw (the windowing toolkit kitty uses). It should be easy to see by inserting some printf() into glfw.c at line 61 in char_mods_callback

That is the function that is called by glfw on *text input* i.e. when you press keys without any additional modifiers/unicode text input mode enabled. I'm guessing for some reason repaet events for those keys are not being delivered. Proabbly something to do with keyboard layout, although not being a mac user, I'm not sure.

**Comment by jwkvam** [comment]
You're totally right! https://github.com/glfw/glfw/issues/1010 Looks like it'll be fixed in the next minor release.

**Comment by kovidgoyal** [comment]
No need to wait for a glfw release. I ported the fix from glfw into kitty.

**Comment by richardpl** [comment]
I do not get key repeats on Ubuntu under wayland.

**Comment by kovidgoyal** [comment]
You need to use the version of glfw compiled from master -- there are various bugs in wayland supprot in the last released version of glfw.

**Comment by kovidgoyal** [comment]
https://github.com/glfw/glfw/issues/1108

**Comment by melMass** [comment]
>Working keys include: a, z, s, o, n, c
Non-working keys include: h, j, k, d, w, f

Hey I'm having the exact same issue on OSX using [amp](https://github.com/jmacdonald/amp)

**Comment by mantheflan** [comment]
> Working keys include: a, z, s, o, n, c
> Non-working keys include: h, j, k, d, w, f

I'm getting the exact same issue on OSX Mojave (whether it be in my editor or at the prompt). I've installed glfw from Homebrew (`brew install glfw`), with no effect.

**Comment by marcelfahle** [comment]
For me the exact same issue in macos Catalina. I tested other apps as well, Macvim has the same problem, Alacritty, Hyper and iTerm work fine. I hope this helps.. I would be grateful if someone has a hint for me how to address this.

Thank you! Also, great work @kovidgoyal loooove Kitty!

**Comment by Goorzhel** [comment]
I hate to necropost, but I had `clipboard_control write-clipboard` in my `kitty.conf` for reasons I've forgotten by now. Commenting it out fixed my key repeats.
