### ISSUE TITLE
Emojis broken since today December 3

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#1200]
Following one of the commits of yesterday or today, only a few pixels of emojis display today. For example, the "👍" emoji looks like this (see the four yellow dots after `echo`):

![screenshot_broken-emojis-kitty-december3_2018-12-03-11 00 28](https://user-images.githubusercontent.com/522085/49385151-b688d100-f6ea-11e8-880b-bd18f93ed183.png)

Kitty 3d5977669e4ed586686b6a051617ea8b6281a3f3 on Ubuntu Linux 18.04.1LTS, running the fish shell.

**Comment by kovidgoyal** [comment]
already fixed, update to current master.
