### ISSUE TITLE
URLs mis-handled by mouse support

### ISSUE THREAD

**Issue by lenormf** [kovidgoyal/kitty#1202]
Hi,

Write the following URL in a terminal:

```
https://ya.ru/
```

The URL is not highlighted when the cursor is placed over the first slash `/`.

*EDIT*: the above issue was fixed in 47ec372

A second issue is that sometimes clicking on a URL doesn't do anything, even when it's being currently highlighted. The URL-mode (<kdb>shift</kdb><kdb>ctrl</kdb><kdb>e</kdb>) always works though.

HTH.

**Comment by Luflosi** [comment]
Your issue was probably fixed a couple hours ago, see #1201.

**Comment by lenormf** [comment]
Possibly, I'll have to try.

However I don't think the commit fixes the second issue I'm reporting.

**Comment by kovidgoyal** [comment]
sometimes doesn't do anything isn't very useful i'm afraid. kitty simply passes the url to the OS (xdg-open on linux and open os macOS). you would need to find something common in those times. Or run kitty from another terminal and see if it prints any error output when clicking a url fails.

**Comment by lenormf** [comment]
I can't reproduce it anymore, maybe that commit fixed it after all.

@kovidgoyal in the future refrain from closing issues solely based on a lack of information, denying there's a bug because users don't serve a full bug report to you on a platter is bad practice, and it helps no-one ;)

**Comment by kovidgoyal** [comment]
@lenormf In the future kindly refrain from telling me how to run my projects. After fifteen years and millions of users, I happen to be pretty good at guessing when something is a bug or not, thank you very much.

**Comment by lenormf** [comment]
Please refer to #1203 for the bug that I reported in this issue that you closed prematurely.

**Comment by Luflosi** [comment]
@lenormf don't worry too much about @kovidgoyal closing the bug report. If you think your issue wasn't resolved, you can just comment on the closed issue and give him more information. If he determines that this is a bug in kitty that needs fixing, he will probably reopen it.
