### ISSUE TITLE
Unable to select just one character

### ISSUE THREAD

**Issue by diamond-lizard** [kovidgoyal/kitty#1205]
Using the mouse, I am unable to select just one character.  Kitty seems to only want to let me select a minimum of two characters.

I'm using kitty 0.12.3 on Gentoo Linux.

**Comment by martinetd** [comment]
It's a known feat^W problem, #1007 kind of works and does fix that if you rebuild your own kitty and want to use it for now, but I was a bit too ambitious and really need to get back to it.

**Comment by kovidgoyal** [comment]
closing in favor of #1007

**Comment by minusf** [comment]
i was just about to submit this...   is there any update on this?  is it too difficult to fix it outside the refactor?

**Comment by kovidgoyal** [comment]
No Idea, it's been years since I looked at the selection code.
