### ISSUE TITLE
macOS: sometimes content lingers after resize when alpha

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1207]
I'm not able to recreate this issue consistently, but here are steps to reproduce:
1. i use a kitty.config with "background_opacity 0.8"
2. i do a "ls" to display some text
3. i rapidly resize the window using the bottom right corner
Sometimes when i do this the font enlarges and changes ratio, and sometimes when this happens, the stretched / enlarged text is left as part of the background ( screen is not completly cleared it seem ).

I'm on macOS, kitty version 0.13.0.

Screenshot of artifact after resize ( notice the white enlarged text in the background ):
![screenshot 2018-12-05 at 16 28 51](https://user-images.githubusercontent.com/1562523/49523851-de269780-f8aa-11e8-8de6-817bc0cc83cf.png)

**Comment by kovidgoyal** [comment]
I cannot reproduce this on my macbook. Indeed during a resize, the kitty window is explicitly rendered with an empty background color, so I dont see how this can happen. This was done deliberately, see https://github.com/kovidgoyal/kitty/commit/21d586cc86e8d700289175e4873c53cfb591c026

**Comment by erf** [comment]
I usually have to give this a few (~10) tries before the issue shows up. Resizing from small to big.

**Comment by kovidgoyal** [comment]
I tried resizing it continuously big smal smal big for a few minutes ata time and could not reproduce.

**Comment by erf** [comment]
Ok. I also notice this, on a rare occasion, happens when i press `CTRL-l` to clear the screen, and the text lingeres in the background as grey text. Maybe it could be a threading/timing issue.

**Comment by kovidgoyal** [comment]
dont see how, kitty is single threaded, only input from the child process is read in a different thread. All actual rendering happens in one thread.
