### ISSUE TITLE
Static link for config file is not working

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#1208]
I've been watching this url with `urlwatch` to be notified when default config changes:

```
https://sw.kovidgoyal.net/kitty/_downloads/kitty.conf
```

Since today I'm receiving 404s, and I noticed that the new url is:

```
https://sw.kovidgoyal.net/kitty/_downloads/fdd5fc58492b70fe2188716f86e7ff87/kitty.conf
```

Is it possible to get the old url back please? 🙂

**Comment by kovidgoyal** [comment]
Sadly, I dont know of a way to fix this. Basically, the link is created
by Sphinx (the documentation system kitty uses) from the download
directive. With newer versions of sphinx, for some reason it is including
a hash, probably for versioned downloads. I could find no way to turn it
off in sphinx. If someone else knows of such a way, please enlighten me.

**Comment by kovidgoyal** [comment]
I looked at the sphinx code and the hash inthe URL is simply the md5 hash of the full file path, which is stable (barring more changes in sphinx), so just use the new URL as the URL to monitor.
