### ISSUE TITLE
Startup and border issue

### ISSUE THREAD

**Issue by zevenblade** [kovidgoyal/kitty#121]
I am using the 0.3.0 version from the releases page. I am experiencing two minor issues.

First     :   If i open kitty the prompt is not displayed properly. I need to ctrl+l first
                 to get a proper prompt. I get the issue for bash, fish shell and zsh.

Wrong prompt
<img width="560" alt="startup_failure" src="https://user-images.githubusercontent.com/19251295/30294388-344e356c-973d-11e7-9e52-2c1701912110.png">

After ctrl+l
<img width="357" alt="after_clear" src="https://user-images.githubusercontent.com/19251295/30294383-338e3622-973d-11e7-91be-a46b20700c67.png">

Second : A border is not displayed. I use the macos no border setting with yes option
                I have set a border width and distinct color. 

Relevant part of config.

The width (in pts) of window borders. Will be rounded to the nearest number of pixels based on screen resolution.
window_border_width 5

The window margin (in pts) (blank area outside the border)
window_margin_width 0

The window padding (in pts) (blank area between the text and the window border)
window_padding_width 30

**Comment by kovidgoyal** [comment]
Borders are displayed only if there is more than one window. i.e. they are used to demarcate different windows. And I dont see any difference int he screenshots you posted? You mean the extra blank line?

**Comment by kovidgoyal** [comment]
No followup
