### ISSUE TITLE
Strange behavior with iconic font on 0.13.1

### ISSUE THREAD

**Issue by ephase** [kovidgoyal/kitty#1210]
Hello, on Archlinux, I've got some strange behavior with the 0.13.1 version here an example, look at the echoed character or the end of my time segment on the right.

![kitty-0 13 1](https://user-images.githubusercontent.com/6266961/49615060-46a56f80-f9a4-11e8-8b1a-6a171d8564b4.png)

Here is an example of what I had with the version 0.12.3

![kitty-0 12](https://user-images.githubusercontent.com/6266961/49614872-9b94b600-f9a3-11e8-9b9e-d020e1580c9b.png)

My system : 
 - Archlinux
 - I3wm
 - FuraCode Nerd Font

My kitty.conf : 

```
font_family         FuraCode Nerd Font
bold_font            auto
italic_font            auto
bold_italic_font   auto

font_size 25.0
```
Thank you

**Comment by kovidgoyal** [comment]
this is likely because of #1036 you should be able to fix it by not having more than one space after the character.

**Comment by ephase** [comment]
As you see in the first screenshoot (kitty 0.13.1), there is just one space after my echo command.

**Comment by kovidgoyal** [comment]
In that case, can you post a link to somewhere I can download the font you are using from so I can try to reproduce.

**Comment by ephase** [comment]
Here is the font : https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraCode.zip
Thank you.

**Comment by aidanharris** [comment]
I'm seeing this too. Weirdly if I downgrade kitty to an older version I'm certain worked fine (0.12.1 and 0.12.3)
 the issue still occurs. I'm starting to think something else might be to blame but I'm not sure what.

![kitty_ps1](https://user-images.githubusercontent.com/3309784/49931787-8ba73580-febf-11e8-9daa-f50107a2b5f7.png)

**Comment by maximbaz** [comment]
Git bisect will certainly help 😉

**Comment by kovidgoyal** [comment]
well if the issue still occurs when running 0.12.1 then I doubt it has anything to do with kitty. I still haven't found the time to try to reproduce it however
