### ISSUE TITLE
Installing on Ubuntu from deb

### ISSUE THREAD

**Issue by cancunia** [kovidgoyal/kitty#1212]
Any idea why the .deb install on my ubuntu 18.x system decided to remove over 90 packages including stuff like Ubuntu Cleaner,  USB Creator?

Be warned folks, backup your data before installing!!

**Comment by kovidgoyal** [comment]
I have no idea, you'd have to ask whoever created that deb package. If you follow the official kitty install instructions, you will see no deb pacakges involved.
