### ISSUE TITLE
How to send Ctrl+- with Kitty/send_text?

### ISSUE THREAD

**Issue by ersv** [kovidgoyal/kitty#1214]
I just came by Kitty, and it looks really awesome/ambitious. Thank you for this piece of code.
Now for the question:
I am running Emacs inside Kitty and when pressing 'ctrl+-',  emacs is only receiving '-' 
To work around that, I tried 
map ctrl+- send_text application \xsomething
It seems to be working insofar that Kitty catches the map, as evident when using --debug-keyboard. Also, emacs receives \xsomething and displays it.
However, in spite of quite some googleing, I can not seem to figure out what ctrl+- should be coded as to be sent correctly with send_text. How should it be coded?
Also, what is any resource to figure out the control code of any other possible future modifier key  combination that I might like to send with send_text?

**Comment by kovidgoyal** [comment]
Terminal programs cannot traditionally handle ctrl+- 
Terminal emulators all send the same bytes for them as for -, as you can
check using 

showkey -a

In kitty you can handle it using the extended keyboard protocol, but for
that you need a terminal program that understands that protocol.

https://sw.kovidgoyal.net/kitty/protocol-extensions.html

**Comment by ohjames** [comment]
I can't even work out how to send `control+a h`. I wanna control tmux more easily with simpler key bindings.

**Comment by p00f** [comment]
there's https://github.com/benjaminor/kkp now fyi
