### ISSUE TITLE
`kitty` is an Unknown command on macOS

### ISSUE THREAD

**Issue by jsatk** [kovidgoyal/kitty#1215]
I installed view `brew cask install kitty`. Opened kitty.app. Everything seems find. I started to dig into the docs more and saw several places talking about a CLI tool `kitty`. I tried to add Fish shell completion using this but get this error. 

<img width="492" alt="screen shot 2018-12-08 at 11 04 02 pm" src="https://user-images.githubusercontent.com/1005550/49694368-db8fa080-fb3d-11e8-805c-55d3db62ac7c.png">

I'm on the latest macOS 10.14.1 & kitty 0.13.1.

What am I doing wrong?

**Comment by kovidgoyal** [comment]
Sorry I dont support the brew kitty, I have no idea what it does. If you install kitty from the official dmg, it will automatically add a directory to PATH from which kitty is available.

**Comment by splintah** [comment]
@jsatk,
The Homebrew formula installs the kitty application – for me, at least – at `/Applications/kitty.app`; the `kitty` executable can then be found at `/Applications/kitty.app/Contents/MacOS/kitty`.

To include this file in your `PATH`, you could add it to your `PATH` variable in your shell startup file, or you could create a symlink in, for example, `/usr/local/bin`: `ln -s /Applications/kitty.app/Contents/MacOS/kitty /usr/local/bin/kitty`.
