### ISSUE TITLE
Startup crash on OSX 10.12

### ISSUE THREAD

**Issue by sasq64** [kovidgoyal/kitty#122]
After simple build & run:
```
2017-09-12 20:36:35.686 Python[47072:452549] *** Assertion failure in -[NSMenu itemAtIndex:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/Menus.subproj/NSMenu.m:940
2017-09-12 20:36:35.687 Python[47072:452549] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: index >= 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9cf4c2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffb1d5c48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9cf51042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff9e999be0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff9a9ada63 -[NSMenu itemAtIndex:] + 162
	5   AppKit                              0x00007fff9a990826 -[NSApplication(NSWindowsMenu) setWindowsMenu:] + 196
	6   fast_data_types.so                  0x000000010d81772b cocoa_create_global_menu + 1147
	...
```

Also tried the binary 0.3.0 release which seems to quit on startup, likely the same issue.

MacOS Sierra 10.12.6 (16G29)

**Comment by kovidgoyal** [comment]
That's a weird error, it looks like a bug in the setWindowsMenu coca function. See if moving the call to 

```
[NSApp setWindowsMenu:windowMenu];
```

in cocoa_window.m

to just before

```
[windowMenu release];
```

makes it go away. I suppose I could always catch the exception and ignore it as well, since starting up with no window menu is better than not starting up at all.

**Comment by sasq64** [comment]
That does indeed work. The only strange thing is that my starting directory becomes Python.app/Contents/Resources deep inside the Python.framework.

I should also mention that I stumbled upon Kitty when researching quirks of the vt100/xterm protocol for my own terminal emulator, which incidentally has very similar goals to Kitty.
Some differences are that I am writing in _D_, and using the OpenGL ES 2.0 subset as rendering target to also support the Raspberry PI.

But it is also designed to be fast and portable, and to support a terminal/vim centric development workflow, and I am extending the protocol with features that make sense, such as giving access to more keys and modifiers for more shortcuts in vim. Maybe we should compare notes at some point.

**Comment by kovidgoyal** [comment]
Cool, I am happy to compare notes. You might be interested in https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc

which includes, among other things an extended keyboard protocol with full support for all modifier keys, etc. Comments are welcome.

**Comment by sasq64** [comment]
Yes, that was actually the document that lead me to Kitty.

I started with actually sending all supported modifiers in the `CSI <num> ~`  sequences, that's an easy way to get more bindable shortcuts. But implementing a full mode like that seems like a good idea.

When it comes to graphics it's trickier -- what should happen to rendered graphics when the screen scrolls or resizes -- should it always be cleared? If you interleave text and graphics, should it all go on top of each other or should graphics always go above?

Also there is the problem that the terminal has no context; if you run two programs using tmux  for instance, they will interfere with each other.

My idea was something like this;
* Render graphics using text based coordinates, and use fractions for "sub-character" positioning.
* Graphics are persistent, scrolls together with text.
* Changing font (cell) size scales graphics, so it still covers the same cells.
* Possibility to target both background and foreground layers, to avoid rendering order problems.
* For image data, _allocate_ ID:s to use to avoid collisions -- similar to _glGenTextures()_

**Comment by kovidgoyal** [comment]
I have addressed most of these issues in the protocol. Graphics scroll with the screen, (i.e. their position is specified by cell + sub-cell co-ordinates), however, the spec leaves it upto implementers whether to preserve them in the history buffer or not. Graphics are pixel addressable, (i.e. you can specify rendering for individual pixels). Currently graphics always overlay text, but there is no reason a z-index parameter cannot be added to the protocol. Image data is identified by ids. 

As for changing font size, the spec does nto really specify what happens in that case.

**Comment by kovidgoyal** [comment]
In any case a better place to discuss this is in #33 so others can also comment.
