### ISSUE TITLE
Margin different color with transparency

### ISSUE THREAD

**Issue by RosalesJ** [kovidgoyal/kitty#1221]
## Issue
The margin displays as a lighter color than the background when background_opacity < 1.

![shot](https://user-images.githubusercontent.com/17154302/49759204-02112100-fc8f-11e8-819a-f3147ab79e54.png)

## System
macOS Mojave 10.14.2
kitty 0.13.1

Versions affected: 0.13.1, 0.13.0

## Replication
Minimal configuration in ```kitty.conf```:
```sh
background_opacity 0.85
background #002b36
window_margin_width 10
```

**Comment by Luflosi** [comment]
I noticed this too, also without the `window_margin_width` or `background` config options. There are three screenshots of this happening in https://github.com/kovidgoyal/kitty/issues/1005#issuecomment-438880434
