### ISSUE TITLE
Number as default tab name

### ISSUE THREAD

**Issue by fanktom** [kovidgoyal/kitty#1223]
Hey there,

I would love to have the index of the tab as the default tab name, like e.g. i3 does.
I read through the source code, especially tabs.py and if I am not mistaken this is currently not possible through configuration.

Is this assumption correct, and would you be interested in such a feature?
Thanks and all the best!

**Comment by kovidgoyal** [comment]
why is the tab number important to you?

**Comment by fanktom** [comment]
I switch tabs based on CMD+number (in i3 this would be called a workspace). If I have e.g. 6 tabs open, its hard to find the correct number for the tab to directly jump to it.

Of course I can rename it manually once I created it, but that is cumbersome and involves manual counting.

**Comment by kovidgoyal** [comment]
for switching tabs a better approach is to have switch tab mode, press a key, it will mark the tabs with numbers/letters press the number letter you want. Like the hints kitten operates.

**Comment by fanktom** [comment]
That would also be a suitable approach for me. Is there such a mode implemented?

I, however would prefer the numbers to be present all the time, because it is visually easier to recognize.

**Comment by kovidgoyal** [comment]
No there is no such mode implemented, feel free to request one in a separate ticket. As for this, I'm afraid I am not interested in implementing it, sorry. Note that tabs will show the title set by whatever program is running in the active window in the tab, which makes displaying numbers as default titles useless unless you never run programs that change window titles.

**Comment by fanktom** [comment]
Okay, thanks for the information. I will try to implement the functionality in a fork anyways. I will try to autmoatically rename the tab, as for renamed tabs, the title does not change with running programs.

**Comment by kovidgoyal** [comment]
sure, I'm fine with that.

**Comment by fanktom** [comment]
Cool, thanks @nerdrew and @kovidgoyal!
