### ISSUE TITLE
PowerlineSymbols font rendering issue

### ISSUE THREAD

**Issue by fpbouchard** [kovidgoyal/kitty#1225]
<img width="95" alt="rendering issue" src="https://user-images.githubusercontent.com/102135/49806897-d772a700-fd26-11e8-8a84-a9f8dd949d33.png">

When I start a fresh instance of kitty, the symbols are rendered with an underlying "box". Once I resize the fonts, the box disappears. I can also reset the font size and it still renders correctly.

**Comment by kovidgoyal** [comment]
which symbol is this? on what version of kitty on what OS? with what actual font?

**Comment by fpbouchard** [comment]
Symbol e0b1, kitty 0.12.3, Mac OS X Mojave, PowerlineSymbols font

**Comment by kovidgoyal** [comment]
First, there have been lots of changes to kitty since 0.12.3 so update
and test. Secondly, you dont need to use powerlinesymbols for that
character, there is a perfectly useable alternative in unicode, see
U+29fd

Finally, if you do want me to take a look at it, please post a link to
where I can download the exact font you are using. There are all sorts
of builds of "PowerlineSymbols" floating around

**Comment by fpbouchard** [comment]
1. My bad on running on an older version, sorry about that. I've updated to 0.13.1, the issue is still there
2. The U+29fd character is not adequate for my current usage.
3. I'm using the otf font from the powerline repository: [PowerlineSymbols](https://github.com/powerline/powerline/blob/develop/font/PowerlineSymbols.otf). However, I've also tried it using "patched" fonts that I knew were working before using kitty (I started using the powerline-only fonts since using kitty thanks to its great `symbol_map` feature) but I get the same issue no matter which font I use.

Here is a clearer screenshot of my use case, in neovim's lightline at the bottom of the screen.

1. Before changing font size:
<img width="801" alt="screen shot 2018-12-11 at 20 45 06" src="https://user-images.githubusercontent.com/102135/49841458-bb522280-fd85-11e8-981c-c3c41330e994.png">

2. And after having changed the font size:
<img width="801" alt="screen shot 2018-12-11 at 20 45 22" src="https://user-images.githubusercontent.com/102135/49841479-c0af6d00-fd85-11e8-9521-819b155a5479.png">

While comparing both screenshots, I can see that there seems to be an issue with the character width since the alignment of the glyph changes between the two screenshots (only for this character).

Thanks for your time.

**Comment by kovidgoyal** [comment]
I dont see that on my macOS machine -- I'm guessing it only happens at some font sizes. Can you post a minimal kitty.conf to reproduce. Also are you on a retina screen? And does changing the font size back to the original cause the issue to re-appear?

**Comment by kovidgoyal** [comment]
no followup

**Comment by fpbouchard** [comment]
@kovidgoyal 

Ok, I had some time to test this. I just reinstalled kitty from scratch, the PowerlineFonts from scratch, on both my MBPs. Fresh kitty.conf, the only change I make is that I uncomment the following line:
`symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols`

When I type the U+E0B1 symbol, it appears like my first screenshot on both MBPs. Both have retina displays.

Using the latest version (0.13.3), zooming in/out doesn't fix the issue anymore. When it did, the rendering was fixed even when going back to the original font size.

**Comment by kovidgoyal** [comment]
Are you sure you are actually loading the correct font? run kitty with --debug-font-fallback to check

**Comment by kovidgoyal** [comment]
I tried again with:

```
kitty --config NONE -o "symbol_map=U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols" --debug-font-fallback zsh -c "printf '\ue0b1'; read"
```

and I cannot reproduce.

**Comment by fpbouchard** [comment]
Weird. It does work when I just printf the character in a bash/zsh session (even with my full config), but not when I run an interactive shell.

Might be something in my rc files? An environment variable?

```
[064 08:59:00.880332] Preloaded font faces:
[064 08:59:00.880370] normal face: {'monospace': True, 'bold': False, 'italic': False, 'family': 'Menlo'}
[064 08:59:00.880387] bold face: {'monospace': True, 'bold': True, 'italic': False, 'family': 'Menlo'}
[064 08:59:00.880402] italic face: {'monospace': True, 'bold': False, 'italic': True, 'family': 'Menlo'}
[064 08:59:00.880416] bi face: {'monospace': True, 'bold': True, 'italic': True, 'family': 'Menlo'}
[064 08:59:00.880432] Symbol map faces:
[064 08:59:00.880453] {'path': '/Users/fpbouchard/Library/Fonts/PowerlineSymbols.otf', 'postscript_name': 'PowerlineSymbols', 'family': 'PowerlineSymbols', 'style': 'Medium', 'bold': False, 'italic': False, 'monospace': True, 'weight': 0.23000000417232513, 'width': 0.0, 'traits': 1024}
```

**Comment by fpbouchard** [comment]
I can also reproduce if I start neovim like this and type the unicode character (i,ctrl+v,u,e0b1):

```
kitty --config NONE -o "symbol_map=U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols" --debug-font-fallback nvim
```

**Comment by fpbouchard** [comment]
Log:
```
[064 09:11:37.497958] Preloaded font faces:
[064 09:11:37.497995] normal face: {'monospace': True, 'bold': False, 'italic': False, 'family': 'Menlo'}
[064 09:11:37.498012] bold face: {'monospace': True, 'bold': True, 'italic': False, 'family': 'Menlo'}
[064 09:11:37.498026] italic face: {'monospace': True, 'bold': False, 'italic': True, 'family': 'Menlo'}
[064 09:11:37.498040] bi face: {'monospace': True, 'bold': True, 'italic': True, 'family': 'Menlo'}
[064 09:11:37.498055] Symbol map faces:
[064 09:11:37.498074] {'path': '/Users/fpbouchard/Library/Fonts/PowerlineSymbols.otf', 'postscript_name': 'PowerlineSymbols', 'family': 'PowerlineSymbols', 'style': 'Medium', 'bold': False, 'italic': False, 'monospace': True, 'weight': 0.23000000417232513, 'width': 0.0, 'traits': 1024}
[064 09:11:37.815928] Escape codes to resize text area are not supported
[064 09:11:40.571966] WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation
```

**Comment by kovidgoyal** [comment]
Cannot reproduce with neovim either with that command line

**Comment by matclab** [comment]
Same problem as @fpbouchard here. The *zsh print* snippet works, but in vim or neovim, I got a spurious little box after the angle symbol.
I'm on arch linux with kitty 0.13.3.

However, the following (with a space after `e0b1`) shows the problem:
```
kitty --config NONE -o "symbol_map=U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols" --debug-font-fallback zsh -c "printf '\ue0b1 '; read"
```

**Comment by hillyu** [comment]
same here on linux.

**Comment by RobSis** [comment]
Since we now have clear steps to reproduce the issue, can this PR be re-opened?

**Comment by Luflosi** [comment]
I can reproduce the weird character with the `PowerlineSymbols` font liked above:
![PowerlineSymbols](https://user-images.githubusercontent.com/15217907/61054213-4d3f0e00-a3ef-11e9-8d47-3d815cf4d3d6.png)
However, the issue goes away when I use 3270Medium Nerd Font Mono (from https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/3270/Medium/complete/3270-Medium%20Nerd%20Font%20Complete%20Mono.otf I think):
![3270Medium Nerd Font Mono](https://user-images.githubusercontent.com/15217907/61054251-5fb94780-a3ef-11e9-9620-ff719dacd98e.png)

**Comment by matclab** [comment]
Thank a lot !

**Comment by fpbouchard** [comment]
Thanks!
