### ISSUE TITLE
MacOS Mojave titlebar button colors

### ISSUE THREAD

**Issue by szymonkaliski** [kovidgoyal/kitty#1226]
Based on this: https://github.com/kovidgoyal/kitty/blob/ae9d04901105eaeeb8cac6105cb83505e858ce3f/kitty/cocoa_window.m#L286-L292 kitty changes button colours depending on background colour, this creates situations where I have red/green/yellow icons in kitty but gray everywhere else (since I'm using "Graphite" highlight colour in system preferences).

Would it be possible to always match the OS settings here?

**Comment by kovidgoyal** [comment]
kitty does not change button colors, it changes the cocoa "appearance".
The actual colors are set by the system based on that appearance.
Presumably whatever theme you are using has not changed the button
colors for that appearance. The list of all possible "appearances"
ishere: https://developer.apple.com/documentation/appkit/nsappearancename?language=objc

**Comment by Luflosi** [comment]
When I set my highlight color to "Graphite", the color of the red/yellow/green icons didn't change in any of the apps I looked at, including kitty. I think that option is only used when selecting text, e.g. in Safari. kitty doesn't use that color for text selection, only the config option but that didn't bother me yet. Could you provide a few screenshots so we can see what's wrong?

**Comment by szymonkaliski** [comment]
Let me illustrated, with these settings:

![screenshot 2018-12-14 at 11 14 17](https://user-images.githubusercontent.com/1040420/49997322-874b4d00-ff91-11e8-9148-df2e421b1f70.png)

All windows have gray buttons:

![screenshot 2018-12-14 at 11 14 45](https://user-images.githubusercontent.com/1040420/49997337-93370f00-ff91-11e8-8d36-e0be41955c9a.png)

Except kitty:

![screenshot 2018-12-14 at 11 14 29](https://user-images.githubusercontent.com/1040420/49997350-9f22d100-ff91-11e8-8a71-d5078cd4ea52.png)

**Comment by Luflosi** [comment]
Ohh, it's not the highlight colour but the accent colour.
With that setting, I can reproduce your issue.

**Comment by szymonkaliski** [comment]
@kovidgoyal ideally the buttons in kitty would stay gray if they are gray everywhere else in the system.

**Comment by kovidgoyal** [comment]
Sure, except that kitty does not choose button colors.

**Comment by szymonkaliski** [comment]
Uhm, so what does? Kitty's button colors are the only ones that don't follow the global OS settings, so if Kitty is not doing that, then do you know what is?

**Comment by szymonkaliski** [comment]
One more thing, if I keep everything the same, and change the theme I'm using to one with light background, like solarized-light, the buttons in fact are gray. So in what I can observe, background color of the kitty windows is related to the button colors, and the code I linked in first comment here is the only relevant part where that could happen...

![screenshot 2018-12-14 at 15 30 23](https://user-images.githubusercontent.com/1040420/50008722-5aa92c80-ffb5-11e8-8399-280f8d6312fa.png)

**Comment by kovidgoyal** [comment]
exactly, like I said, the system implements the button colors as bright for the "dark" appearance. kitty has no control over that. It needs to be fixed by apple. All kitty could possibly do is not set the titlebar to have the dark appearance when the background is dark. But that means the titlebar clashes withthe bakground, which is a much worse side effect.
