### ISSUE TITLE
 how to get alt to send escape?

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#123]
I'm trying to switch from iterm to kitty, except that the alt key in kitty does not work for me inside (neo)vim because it does not seem to send ESC, so mappings like `a-s` don't work.

**Comment by kovidgoyal** [comment]
Alt most definitely does send escape. Try running 
```
cat
```

in the terminal and typing

alt+s

You get 

```
^[s
```

Or if you are on OS X, IIRC the OS converts Alt + key into unicode characters. A bit of googling will show you how to get OS X to stop doing that. I'm not an OS X user so I can't really help with that.

**Comment by Alok** [comment]
https://stackoverflow.com/questions/11876485/how-to-disable-typing-special-characters-when-pressing-option-key-in-mac-os-x

That fixes it

**Comment by justinmk** [comment]
If there's a way to do this in kitty by default on macOS I would strongly suggest doing that.

https://stackoverflow.com/questions/11876485 involves installing software or setting a system-wide setting.

Currently option (alt) chords in kitty on macOS don't do anything useful. E.g. in bash it inserts non-printable bytes--it doesn't show the expected multibyte character. 

For comparison:

- In Terminal.app, with "Use Option as meta key" disabled, alt+o inserts `ø` (0xF8) in bash.
- In Terminal.app, with "Use Option as meta key" enabled, alt+o sends ESC + o.
    - Would be nice if kitty behaved like this by default on macOS.
- In kitty on macOS, alt+o in bash enters some unfinished state, which is then combined with the next keypress. E.g. in bash, `nvim <a-o>foo` edits a file named `<b8>a`.

**Comment by kovidgoyal** [comment]
I dont know of any API on macOS that allows applications to prevent the OS from converting alt+keypress into unicode input. So the only way to do it would be to bypass the key handling of GLFW and process the raw scancodes, which is probably what terminal.app does. And then you have to worry about handling people using non-standard keyboard layouts. That's way more work than I care to put in for a platform I dont use. Patches are welcome.

**Comment by justinmk** [comment]
Maybe @gnachman knows :)

**Comment by justinmk** [comment]
@kovidgoyal alacritty issue tracker has some hints, `NSEvent.charactersIgnoringModifiers()` seems to be the way to get "o" from alt+o. Then that could be combined with the detected ALT modifier.

https://github.com/jwilm/alacritty/issues/62#issuecomment-316056241

https://github.com/gnachman/iTerm2/blob/c67051d19907e77be670fa04d22d8d5710a0fc62/sources/PTYSession.m#L5817

**Comment by kovidgoyal** [comment]
Thanks, that is essentially the solution I was talking about, bypassing GLFW. That is still a pretty large amount of work, because one has to first bypass glfw and implement key event handler, then remap the key events back to glfw key events. Still, might be worth doing someday.

**Comment by kovidgoyal** [comment]
Turns out that it is possible to at least support the "option as meta" use case without bypassing glfw. Basically you just have to manually handle the case of alt + printable keys instead of relying on glfw. https://github.com/kovidgoyal/kitty/commit/f137ea709455cb334ccf95de9f3bf42bcf1201d6

I'd appreciate it if some mac users sould test it out more thoroughly.

**Comment by justinmk** [comment]
@kovidgoyal Wonderful! Is it much trouble to post a dmg?

**Comment by kovidgoyal** [comment]
The dmg is inside the attached zip file because github doesnt allow uploading dmg files.
[kitty.zip](https://github.com/kovidgoyal/kitty/files/1449907/kitty.zip)

**Comment by justinmk** [comment]
@kovidgoyal This works much better than the [keymap hack](https://github.com/justinmk/config/commit/fd5b8842a1964aa43480a417641f14325ddf0607#diff-1ac41350a61d902f52aa8abb26d41369R323) I was using (which had weird interactions with tmux). No problems so far.

**Comment by kovidgoyal** [comment]
Glad to hear it :)

**Comment by kovidgoyal** [comment]
And it finally turns out that I was completely wrong. It's actually possible to do both unicode input and option as alt without bypassing glfw. https://github.com/kovidgoyal/kitty/commit/505ae90fd7fe298809bd74ff7bbabc54190df1d9
