### ISSUE TITLE
Split commands on whitespace if not found for backwards compatibility?

### ISSUE THREAD

**Issue by pjz** [kovidgoyal/kitty#1236]
Other terminals (xterm, rxvt, gnome-terminal, xfce4-terminal, ...) use the -e option to specify a command to be executed - with kitty it's unnecessary.  Any chance we can ignore it for backwards compatibility?  It'd mean not having to edit every script that calls `${TERMINAL} -e run-some-command`.

**Comment by SolitudeSF** [comment]
kitty already ignores it

**Comment by pjz** [comment]
You're correct.  It's a quoting issue.  But it's a backwards-compatible quoting issue.
`xterm -e "iostat 5"` 
works fine, but
`kitty -e "iostat 5"`
errors with:
```
Failed to launch child: iostat 5
With error: No such file or directory
Press Enter to exit.
```
because it's treating the whole command as the thing to execute and not breaking on whitespace.
I suggest if there's a not found error, fall back by splitting on whitespace and trying again.  I don't see any other way to be compatible with other terminals' syntax.

**Comment by martinetd** [comment]
It really shouldn't try both, that's horrible. Trying to split is clumsy as well, splitting complex commands e.g. (silly example) `kitty -e "sh -c 'echo foo'"` is a pretty hard problem.
I think `-e`'s argument should just be passed to a shell as a whole, instead of passing the rest of the line as it normally would without `-e` -- so, not ignore the option but handle it properly.

**Comment by kovidgoyal** [comment]
I'm afraid I agree with @martinetd kitty should not try both, that way lies chaos and tons of corner cases. 

And as for splitting, splitting by what rules? That way also lie tons of corner cases. Commands to be executed are not passed through a shell, they are executed directly. That is not going to change.

Oh and just by the way, this is what gnome-terminal has to say about the -e option (try running gnome-terminal -e cat from another terminal to see it):

```
# Option “-e” is deprecated and might be removed in a later version of gnome-terminal.# Use “-- ” to terminate the options and put the command line to execute after it.
```
