### ISSUE TITLE
When scrolling with the mouse, one tick does not do anything if the scrolling is slow enough

### ISSUE THREAD

**Issue by dylan-chong** [kovidgoyal/kitty#1238]
When scrolling slow enough with a mouse wheel, there may not be any movement on the terminal at all. Note that I am using Mac OS, and using a normal mouse (not the magic mouse) so the mouse wheel is clicky.

When using a program such as the Ranger file browser https://github.com/ranger/ranger, one click on the mouse should equal moving the focus to the next or previous item on the list. However, when scrolling slow enough, the focus may not be moved at all. The same behaviour can be replicated using fzf, where one tick on the mouse would also make sense as moving the focus by one item on the list.

I am using kitty 0.12.3

**Comment by Luflosi** [comment]
I can reproduce your problem. I think I found the cause of this bug and will make a pull request tomorrow.

**Comment by Luflosi** [comment]
One day later than promised but here it is. @dylan-chong can you try this patch?

**Comment by dylan-chong** [comment]
Is there a prebuilt binary from mac os or should i build from source?

**Comment by Luflosi** [comment]
I don't have a prebuilt binary for macOS. Could you build from source please?

**Comment by dylan-chong** [comment]
Do you still need me to test this @Luflosi ?

**Comment by Luflosi** [comment]
I'm quite sure it works correctly but feel free to compile kitty from source anyways if you don't want to wait for the next version of kitty to have this issue fixed for you.

**Comment by dylan-chong** [comment]
I’m good with waiting

Has anybody tried it with a mouse like the magic mouse with smooth scrolling? I don’t have one but it sounds like a decent edge case

**Comment by Luflosi** [comment]
The magic mouse most likely reports high-precision scroll events. In this case, this patch has no effect on those mice.
