### ISSUE TITLE
Split support?

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#124]
Are vertical/horizontal splits planned to be supported (or are maybe already supported and I couldn't find reference to them in the config file)? Or is that something you'd rather defer to `tmux` or some other tool?

**Comment by kovidgoyal** [comment]
Theya re already supported, see the readme.

**Comment by alshdavid** [comment]
I'd motion to reopen this. Layouts are great, but aren't as flexible as most would expect from a modern terminal emulator. See [Hyper](https://hyper.is/) or [iTerm2](https://www.iterm2.com/features.html).

`cnt+shit+h` should be "split focused terminal horizontally"
`cnt+shit+v` should be "split focused terminal vertically"

**Comment by kovidgoyal** [comment]
sorry not a fan of arranging windows via splits, I find then painful to use in practice.

**Comment by knubie** [comment]
> sorry not a fan of arranging windows via splits, I find then painful to use in practice.

Isn't that what kitty's layouts are, windows arranged via splits?

**Comment by kovidgoyal** [comment]
No you dont arrange them via splits. How new windows show up when you
create them is layout dependent. There is no concept of a
horizontal/vertical split.

**Comment by knubie** [comment]
Fair enough, while we're on the subject of windows, is it possible to accomplish something like [this](https://github.com/christoomey/vim-tmux-navigator#add-a-snippet) with kitty? Specifically the following tmux conf snippet:

```conf
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
```

The shortcuts behave differently depending on whether vim is running or not. If vim is running, it just passes the keys along unchanged, but if vim is not running, it selects a window as normal.

Tmux accomplishes this with their `if_shell` command.

**Comment by kovidgoyal** [comment]
yeah you can do pretty much anything you want by writing a UI less kitten and binding it to your shortcuts of choice. See https://sw.kovidgoyal.net/kitty/kittens/custom.html

**Comment by kovidgoyal** [comment]
In handle_result in the kitten you'd basically get the target window, check what the process name of the child is (window.child.cmdline) and then dispatch your shortcuts accordingly. IIrC someone else wrote a kitten that does  something similar, dispatching key presses based on whether the alternate or main screen is visible. You can use that to get started.

**Comment by kovidgoyal** [comment]
No, github is pretty much the place to discuss stuff. I haven't the time/interest to setup a mailing list/IRC channel for kitty.

**Comment by rraks** [comment]
Is there any way I can achieve a vertical split through a kitten?
I find it hard to use layouts coming from the tmux world.

**Comment by kovidgoyal** [comment]
No, you'd have to write a layout that supports splits for that, see layouts.py

**Comment by yellowhat** [comment]
> Thanks a lot @kovidgoyal, I found the kitten you were talking about, which got me pretty close. I hit a wall though when I realized I can't do `kitty @ neighboring_window ___` from vim. So my next idea is to make another kitten that just calls `neighboring_window` and do `kitty @ kitten neighboring_window.py`.
> 
> BTW, is there a better place to discuss these kinds of things other than github issues, like IRC maybe?

Hi may I ask to share "the kitten you were talking about".
I am trying to achieve the same functionality.

Thank you very much

**Comment by knubie** [comment]
@yellowhat I think this was the kitten https://github.com/yurikhan/kitty-smart-scroll

And this is what I ended up making: https://github.com/knubie/vim-kitty-navigator

**Comment by yellowhat** [comment]
Thank you very much

**Comment by yellowhat** [comment]
Hi,
there has been some commit about "splits", like:
https://github.com/kovidgoyal/kitty/commit/36fda90814727bf2e67d86507d3984d014d94ab6
https://github.com/kovidgoyal/kitty/commit/ad3b527bc470dddefdd938334a858a117f2b6bc1

but I am not able to find any reference in the documentation.

Thanks

**Comment by kovidgoyal** [comment]
Look in layouts.rst

**Comment by yellowhat** [comment]
Thank you very much.

**Comment by gowhari** [comment]
For those who haven't found it, check here:
https://sw.kovidgoyal.net/kitty/layouts/#the-splits-layout

Your layout needs to be set to `splits` for this to work.

```
enabled_layouts splits,stack
map f4 launch --cwd=current --location=split
map f5 launch --cwd=current --location=hsplit
map f6 launch --cwd=current --location=vsplit
map f7 layout_action rotate
```

Of course, you can enable more layouts.

> Added in version 0.17.0: The Splits layout (Mar 24, 2020)
