### ISSUE TITLE
Call internal API from mapped keys?

### ISSUE THREAD

**Issue by nerdrew** [kovidgoyal/kitty#1240]
I see that I can enable remote-control and use kitty to change the terminal colors, but I'd like to avoid enabling remote-control since I frequently ssh to servers I don't control.

I wrote a kitten that will change the colors for me: https://github.com/nerdrew/kittens/blob/master/set_colors.py and then setup the following maps:

```
map cmd+ctrl+p        combine : new_tab_with_cwd : kitten kittens/set_colors.py solarized_dark.conf
map cmd+ctrl+s        combine : new_tab_with_cwd : kitten kittens/set_colors.py solarized_dark.conf cursor=green
```

Is it possible to call internal kitty APIs / commands from a mapped key? The kitten above is basically copied and pasted from https://github.com/kovidgoyal/kitty/blob/62cb035afe4db3dd7615032e4804759085453145/kitty/cmds.py#L659

**Comment by kovidgoyal** [comment]
you can change terminal colors directly using escape codes, you dont need to use remote control for that. As for calling internal APIs kittens run in the same process space as kitty, so you can do anything in a kittens code that you can do in kitty itself.
