### ISSUE TITLE
Missing characters where spaces should be in prompt

### ISSUE THREAD

**Issue by Dakedres** [kovidgoyal/kitty#1243]
So I'm trying to switch to kitty and I've found that it's showing missing character symbols where spaces should be after my powerline symbols?
![image](https://user-images.githubusercontent.com/36781227/50059815-9396fc00-0183-11e9-93e5-7a50ad7f97ec.png)
Now from the moment I first launced kitty [Powerline Extra Symbols](https://github.com/ryanoasis/powerline-extra-symbols) has been working fine, I even mapped the symbols but it refuses to fix the missing characters. Here's [my config](https://gist.github.com/Dakedres/e10a6d129bfeb3fecd4b8d32b63133e6).

**Comment by kovidgoyal** [comment]
dup of #1210
