### ISSUE TITLE
pipe with "none" destination target does not pass scrollback buffer to stdin

### ISSUE THREAD

**Issue by cfal** [kovidgoyal/kitty#1244]
stdin is empty when piping to 'none' target.

can reproduce with something like:

```
#!/bin/sh
cat > output
```

this mapping works and the file "output" contains the screen buffer:
map ctrl+shift+s pipe @text window script.sh

when changed to the following, stdin is empty and "output" is also empty:
map ctrl+shift+s pipe @text none script.sh

**Comment by kovidgoyal** [comment]
this is already fixed in version 0.13.1 update and you should be fine
