### ISSUE TITLE
Copy text on select

### ISSUE THREAD

**Issue by chmln** [kovidgoyal/kitty#125]
Hello,

First of all, thank you for `kitty` and especially for focusing on performance.

Does `kitty` have some sort of a plugin system?
I've come to rely on "copy text upon selection" feature found in some terminals.

Would it be possible to implement something like that in `kitty`?

**Comment by kovidgoyal** [comment]
kitty already implements that, but you need to have the xsel program installed for it to work (at least until a version of glfw is released with support for primary selection).

**Comment by mredaelli** [comment]
Is copy on select possible under MacOS? xsel is not available, but maybe using pbcopy?
(I have no idea what I'm talking about - just found this: https://github.com/fish-shell/fish-shell/issues/605 )

**Comment by kovidgoyal** [comment]
copy on select is a linux feature, it doesn't really fit on macOS. Apple decided they dont want it. While it's technically possible to implement, I dont think it is a good idea.

**Comment by wez** [comment]
Can you elaborate on how to configure kitty to automatically copy the selection?  You mentioned `xsel` but I don't see that mentioned in the config.

**Comment by kovidgoyal** [comment]
You dont need to configure it, it works automatically. And xsel is not needed as of kitty 0.6

**Comment by wez** [comment]
If I double click some text in the terminal, then tab over here and paste, what was selected in the terminal doesn't paste here.  I have to press the copy_to_clipboard shortcut to manually copy the selection from the terminal as an extra step.  Is this working as intended?  I'd like to eliminate pressing the shortcut :-) I'm running with master from last night

**Comment by kovidgoyal** [comment]
You paste by middle clicking. That's how select+paste works in most linux desktops.

**Comment by wez** [comment]
I think you're misunderstanding the request; I'd like kitty to automatically `copy_to_clipboard` when selecting text.  This doesn't happen for me today.  My test case is to double click (or just click and drag) to select some text in kitty, then switch to this comment box and paste.  The selected text in kitty is not pasted when I do this, which implies that it is not copied to the clipboard.   Is this a bug, or something that is not yet implemented, or something that you don't feel should be implemented?

This feature is available as an option known as xterm style selection in just about every other terminal emulator and is something that is difficult to live without.  Terminal emulators on mac (iTerm2) also have support for this despite it not being a core macOS concept.

**Comment by kovidgoyal** [comment]
Double click word, switch to this tab. Middle click in the text box, word is pasted. Automatically overriding the contents of the clipboard on select is a security risk, because all programs on your system can read from it, which is why most platforms, even wayland on linux have disabled it.

**Comment by kovidgoyal** [comment]
In any case, I added an option to turn on copy to clipboard on select, defaulting to off, because of the security implications. https://github.com/kovidgoyal/kitty/commit/81b5d2c4f27bbd158cbd5736d0dc8dcae93978d6

**Comment by wez** [comment]
Thanks!

**Comment by mredaelli** [comment]
That's great, thanks!
