### ISSUE TITLE
shell command hangs forever

### ISSUE THREAD

**Issue by kuehnelth** [kovidgoyal/kitty#1253]
The command `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1` in kitty with bash as shell never finishes.
It prints one line but doesn't finish. cat continues to read forever.

kitty with fish shell works fine.
terminator and xterm with either bash or fish are also fine.

**Comment by kuehnelth** [comment]
Bash behaving differently based on what terminal it detects sounds like a good idea. At least the TERM environment variable seems to be different when using kitty.

**Comment by martinetd** [comment]
I was curious, the problem isn't `TERM` but that bash doesn't reset signal handlers apparently?

The "hang" boilds down to SIGPIPE being ignored with bash+kitty.
This program exhibits different behaviour on kitty and on urxvt:
```
#define _POSIX_C_SOURCE 200112L
#include <stdio.h>
#include <signal.h>
#include <errno.h>


int main() {
        struct sigaction oldact;
        int rc;

        rc = sigaction(SIGPIPE, NULL, &oldact);
        if (rc < 0) {
                perror("sigaction failed");
                return -1;
        }
        printf("oldact handler == IGN: %d\n", oldact.sa_handler == SIG_IGN);
        return 0;
}
```

for example, bash+kitty will say 1, zsh+kitty or bash+urxvt will say 0

**Comment by kovidgoyal** [comment]
kitty does not ignore the SIGPIPE signal, so I dont know why it should have a default value of IGN, but it's easy enought to explicitly reset it before launching the child.
