### ISSUE TITLE
Caps lock causes buffer to scroll down

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#1255]
On my system (`4.19.10-arch1-1-ARCH`, `kitty 0.13.1`, tried the git version) pressing the caps lock key causes kitty to reset from wherever I've scrolled, right back to the shell prompt (i.e. it undoes any scrolling I've done). `xterm` for example does not display this behavior. Caps lock, which I've remapped to `Hyper_L`, is my wm's main modifier, so the unwanted scrolling behavior is often annoying.

Kitty's keyboard debug output on pressing the caps lock key:
```
Press scancode: 0x42 clean_sym: Hyper_L composed_sym: Hyper_L mods: none glfw_fallback_key: 280 (CAPS LOCK) xkb_key: 65509 (Caps_Lock)
on_key_input: glfw key: 280 native_code: 0xffe5 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release scancode: 0x42 clean_sym: Hyper_L mods: super glfw_fallback_key: 280 (CAPS LOCK) xkb_key: 65509 (Caps_Lock)
on_key_input: glfw key: 280 native_code: 0xffe5 action: RELEASE mods: 0x8 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

To solve this, I've already tried mapping all  keycodes from the output above to `no_op`, per the documentation, as well as added the option `clear_all_shortcuts yes`. Both resolve nothing, unfortunately. Any insight in which key or modifiers causes this to happen, and how to disable this behavior? All other modifiers I press (including super) don't display this problem.

**Comment by kovidgoyal** [comment]
Hyper is not a recognized modifier in glfw (the toolkit kitty uses) and
therefore, it wont behave like the other modifiers in kitty. Your best
bet is to map caps lock to super instead and map super to hyper.

**Comment by Luflosi** [comment]
@kovidgoyal could we add support for <kbd>Hyper</kbd>?

**Comment by rien333** [comment]
I still wonder whether my original buffer scroll down issue is related to <kbd>Hyper</kbd> or <kbd>Caps Lock</kbd>. It definitively receives (fallback?) scancode `0xffe5`, which, in decimals, equals ` xkb_key: 65509 (Caps_Lock)`. As said, mapping this scancode to something meaningless kinda resolves this issue, although I've yet to come up with a properly meaningless mapping to bind <kbd>Caps Lock</kbd> to.

**Comment by kovidgoyal** [comment]
@Luflosi feel free to try

On Sun, Oct 27, 2019 at 05:27:48AM -0700, Luflosi wrote:
> @kovidgoyal could we add support for <kbd>Hyper</kbd>?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/1255#issuecomment-546689777

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by Luflosi** [comment]
I don't know how to simulate the <kbd>Hyper</kbd> key on macOS, so I can't implement this feature, sorry.

**Comment by rien333** [comment]
Fixed with https://github.com/kovidgoyal/kitty/commit/b796ceecdd369842c7680d9071bd3e10d911f3f8!

**Comment by rien333** [comment]
@kovidgoyal this issue has returned once again in the slew of key input handling commits after 0.19.3.  Perhaps something done in https://github.com/kovidgoyal/kitty/commit/b796ceecdd369842c7680d9071bd3e10d911f3f8 was made undone?

**Comment by rien333** [comment]
Could be because https://github.com/kovidgoyal/kitty/blob/f6d4b8e0b0c5cae053f7d76a50420180b652e7d6/kitty/keys.c#L151-L154 doesn't check for the Caps Lock key (while the function `is_modifier_key` does)

**Comment by kovidgoyal** [comment]
Are you upto date on master? And if you are post the output of running

kitty --debug-keyboard

and pressing the hyper key.

**Comment by kovidgoyal** [comment]
In particular make sure you have https://github.com/kovidgoyal/kitty/commit/60e589f775fde7065c749c22c7025a981ea249df

**Comment by rien333** [comment]
Works fine again, thanks! I was on https://github.com/kovidgoyal/kitty/commit/f6d4b8e0b0c5cae053f7d76a50420180b652e7d6, FWIW.
