### ISSUE TITLE
Scrolling speed is capped in programs like vim and tmux (again)

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1257]
This is essentially like #837, just for low-resolution mice and touch pads.
I think the second half of 4d2d9d55749948a18f73e3676b66664dfe57e1d6 should be undone. Without that change the maximum speed isn't capped.
Just because an input device is not high resolution does not mean, that it isn't possible to scroll more than one line per scroll event. On macOS and possibly other platforms, mice can have scrolling acceleration as well, in which case the number of scrolled lines can be more than one.
I'm guessing you changed it because you wanted whatever program you're running to receive one event per mouse scroll "click", even when `wheel_scroll_multiplier` is not 1. I think the real issue here is that different programs scroll a different amount per scroll escape code. I think the best thing to do here is to assume that they scroll by one line per event. For me `vim` without a config file for example moves the cursor by one line per escape code. Under this assumption, to maintain a consistent scrolling speed between alternate screen mode and the normal mode in all cases, that special case should be removed. With that special case, scrolling acceleration doesn't work and even without scrolling acceleration, one must still configure every single program which uses the alternate screen mode to scroll `wheel_scroll_multiplier` many lines per escape code to make the scrolling speed consistent between alternate screen mode and the normal mode instead of just having one setting in the kitty config.

I'm not really personally affected by this issue since I don't usually use a low-resolution mouse on macOS, I just noticed the issue while reading the code.

**Comment by kovidgoyal** [comment]
IIRC this was done this way, because all others terminal emulators behave this way. The idea being that different applications could have different requirements/sensitivities needed for scrolling, so it is best to leave it up to them to choose a multiplier.
