### ISSUE TITLE
Use background color for character below cursor

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#126]
As per the title; it would be nice to be able to have kitty draw the character currently below the *block cursor* in the same color as the background color.

I did not find any way in the current setting to allow for this, and it would go really well with having full cursor opacity.

Do you think this would be hard to implement, and if not, would you consider adding this?

Thanks.

**Comment by kovidgoyal** [comment]
Implementing it is probably not difficult, but why background color? Shouldn't it be a dedicated color contrasting with the cursor color? After all the background color changes depnding on the application.

**Comment by koekeishiya** [comment]
I suppose that would indeed be more appropriate.

**Comment by kovidgoyal** [comment]
Hmm I'm not convinced this is a good idea. With a blinking cursor it would look pretty bad to have the foreground color changing both when cursor moves and on blink. But maybe I am imagining it. Do you know of any other terminal that have this feature, so Ican try it out and see how it looks, before spending the time to implement it?

**Comment by koekeishiya** [comment]
iTerm2 for macOS does this. I don't know of any terminal applications on Linux that does this, but I'm sure there has to be some. I've attached a short gif demonstrating the behaviour with the colors / effect I'd like.

![cursor](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif)

**Comment by kovidgoyal** [comment]
Implemented in the fast branch.

**Comment by koekeishiya** [comment]
Works great, thanks!

**Comment by kovidgoyal** [comment]
There are three possible approaches:
1) Use a defined foreground and background color
2) Use a defined background color and the foreground color from the current terminal background
3) Use a full reverse video effect (invert the colors in the terminal for the cursor)

Different terminals typically support one of these three approaches. And different kitty users have requested all three at different times. I am fine with (1) and (2). The problem with (3) is that it breaks the terminal escape codes used to change cursor colors.

That said I also dont much see the point of (1). You should set your cursor color to have good contrast with the background color. If you do that and you still have poor contrast with text , then that means the text already has poor contrast with the background, and is hard to see regardless of whether the cursor is over it or not.

**Comment by Asheq** [comment]
Thanks for the quick reply! The problem for me is that my colorscheme in Vim has a dark background under normal circumstances, but search matches have a light background (yellow) with a dark foreground. Please see this gif for my issue.

![test](https://user-images.githubusercontent.com/4657140/42606592-5d1eac08-8533-11e8-8609-42da4ec592ac.gif)

Should I just change how search matches show up in my Vim colorscheme?

**Comment by kovidgoyal** [comment]
Yeah, the easiest thing to do is change either the search highlight color to be a bit darker, or your cursor color to be a bit darker. Although, given that the cursor blinks, it isn't that hard to see the text under it :)

**Comment by kovidgoyal** [comment]
There you go: https://github.com/kovidgoyal/kitty/commit/55fc5c435869c5343dfead0a788e39c6aaabb0ac

**Comment by Asheq** [comment]
Thank you, I'll give it a try!

**Comment by romgrk** [comment]
@kovidgoyal is cursor color invertion supported? (as showed in https://github.com/kovidgoyal/kitty/issues/126#issuecomment-329957873) I've tried the `background` cursor text color, but it's not quite what I want. Color invertion ensures the cursor is visible at all times, as explained in https://github.com/kovidgoyal/kitty/issues/126#issuecomment-404356384.
I'd be happy to open a PR if it's not supported yet and you're ok with including it.

**Comment by kovidgoyal** [comment]
As I said above, I am not a fan of inversion because it breaks the terminal escape codes used to set cursor colors. It means that it is no longer possible for terminal applications to control cursor colors, as needed.

**Comment by romgrk** [comment]
Ok, I get your point, it's true that it has downsides. However, I think that ultimately, if the user really wants to have inversion, it should have priority over terminal applications. 
Besides, cursor color inversion is also the best way (that I know of) to make the cursor clearly visible at all times. For example, I use a dark colorscheme in the terminal, but a light colorscheme in neovim. Any cursor bg color choice will fail to make it visible at some point. The proof that it's so useful is that it is implemented in most other terminals (which unfortunately lack the features of Kitty, thus why I'm being insistent on having it in Kitty :)
I understand that you're not a fan of using it yourself and thus have no interest in implementing it, but if you can tolerate it being implemented in Kitty I can do it myself. Let me know what you think.

**Comment by subnut** [comment]
> The problem with having inverted colors is that it means the entire ecosystem can no longer rely on being able to change cursor colors

@kovidgoyal @romgrk 
Isn't it possible to set _inverted cursor_ as a kind of default? I mean, I imagine an option, which when set to `true`, will cause kitty to render inverted cursor by default **unless** the terminal application (neovim in this case) explicitly mentions something else. Isn't it possible?

> it is implemented in most other terminals (which unfortunately lack the features of Kitty, thus why I'm being insistent on having it in Kitty :)

Exactly. :)
I perfectly understand that @kovidgoyal doesn't want to implement it himself. But if this feature is possible to implement, and @romgrk can submit a PR, then I think there should not be any problem....

**Comment by romgrk** [comment]
I'm not using kitty at the moment so I don't plan to submit a PR.

**Comment by subnut** [comment]
@romgrk What are you using now?

**Comment by romgrk** [comment]
tilix

**Comment by gshpychka** [comment]
The lack of cursor color inversion is what's preventing me from switching from Alacritty, which has this on by default.

**Comment by eddyekofo94** [comment]
I wish to move away from Alacrity but this is a let down a little

**Comment by tamton-aquib** [comment]
Same as gshpychka, this is the only feature alacritty has over kitty.
It would be nice if there was an option :( .

**Comment by rosshadden** [comment]
I don't disagree that in a vacuum this is something that makes more sense for an application (vim, zsh, etc.) to handle than a terminal. But the reality is many terminals support this and it's an (admittedly weird) turn-off when a terminal doesn't. At the end of the day it's subjective and many of us like our cursors behaving this way while many may not. I'm not the author but I don't see what harm it does to add in a strongly-requested feature and let people opt-in to it if they wish.

My personal reason for liking this and using it in every terminal I use is very well captured in [the image](https://github.com/kovidgoyal/kitty/issues/126#issuecomment-404356384) that @Asheq shared above. In ~5 years of doing this in various terminals (termite being my most recent) I have not once seen a color combination that was hard to see such as in the aforementioned gif. Which is kind of the point---it's impossible or maybe just extremely unlikely at worst.

**Comment by metaory** [comment]
Alacricity handles cursor so nicely, but dont play nice with x wm motif and size hints,  
https://github.com/alacritty/alacritty/issues/1702#issuecomment-846153763 :zany_face: 

Kitty handles size hints nicely and support X spec, but this bad vi cursor color support,,,, 
this even carries into my vim/nVim too,

still bad cursor better than bad size hints, Ive been telling myself 😬 but it hurts!!

<sup>[wezterm](https://github.com/wez/wezterm)?!</sup> :tada:

**Comment by yebt** [comment]
> iTerm2 for macOS does this. I don't know of any terminal applications on Linux that does this, but I'm sure there has to be some. I've attached a short gif demonstrating the behaviour with the effect I'd like.
> 
> ![cursor](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif)

What is this font?

**Comment by koekeishiya** [comment]
Uh probably https://github.com/belluzj/fantasque-sans

Sent from my iPhone

On 18 Aug 2021, at 09:04, yebt ***@***.***> wrote:

﻿

iTerm2 for macOS does this. I don't know of any terminal applications on Linux that does this, but I'm sure there has to be some. I've attached a short gif demonstrating the behaviour with the effect I'd like.

[cursor]<https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif>

What is this font?

**Comment by carlosala** [comment]
> The good lord alone knows what iTerm is doing. That's not reverse video, that's some pick whatever cursor color I think looks good algorithm. If you like it so much feel free to look in its source code and figure out the algorithm and submit a PR for it, you just need to modify the pick_cursor_color() function in kitty.

As I understand, what is expected to happen when you have anything selected (as because is below the cursor or just a big selection) is that background should be the text color and text color should be cursor background color. And just that character, the others must have the normal color.

**Comment by carlosala** [comment]
> Thanks a lot for implementing this. Looks great! Here are my first experiments with Neovim and the new option. Looks like there is still some room for improvements! ;)
> 
> Seoul256 theme:
> 
>  2021-10-27.23.45.15.mov 
>  2021-10-28.00.16.30.mov 
> Cake16 theme:
> 
>  2021-10-27.23.43.53.mov 
> Nord theme:
> 
>  2021-10-27.23.40.32.mov

As you can see in the first video, both braces change color. This is not expected (or doesn't work like this in Alacritty or other terms)

**Comment by kovidgoyal** [comment]
I dot what you are talking about. The cursor and the cursor alone changes color because fo kitty. anything else changing color is because vim changed its color.

**Comment by page-down** [comment]
> > The good lord alone knows what iTerm is doing. That's not reverse video, that's some pick whatever cursor color I think looks good algorithm.
> 
> As I understand, ... background should be the text color and text color should be cursor background color. ...

No, it is not. I don't even have to look at the code at all. iTerm2 uses the text foreground color as the cursor background color. When the color is lighter than 50%, black is used as the cursor text color. When the color is darker than 50%, white is used instead. Black and white refer to two of the 8 ANSI colors in the iTerm2 configuration.

This is clearly not a reverse video effect. And this iTerm2 feature is completely dead when the cursor is on RGB true color text.

**Comment by carlosala** [comment]
> > > The good lord alone knows what iTerm is doing. That's not reverse video, that's some pick whatever cursor color I think looks good algorithm.
> > 
> > 
> > As I understand, ... background should be the text color and text color should be cursor background color. ...
> 
> No, it is not. I don't even have to look at the code at all. iTerm2 uses the text foreground color as the cursor background color. When the color is lighter than 50%, black is used as the cursor text color. When the color is darker than 50%, white is used instead. Black and white refer to two of the 8 ANSI colors in the iTerm2 configuration.
> 
> This is clearly not a reverse video effect. And this iTerm2 feature is completely dead when the cursor is on RGB true color text.

I am talking about Alacritty and gnome-terminal, I hadn't used iTerm2.

**Comment by carlosala** [comment]
I tried `nightly` version and looks great. I'm looking forward to seeing a new release with this!

**Comment by romgrk** [comment]
I've just noticed that this was implemented :O Thanks a lot for this, @kovidgoyal !

**Comment by kovidgoyal** [comment]
you are welcome!

**Comment by calvinchoy** [comment]
Does anyone have an example of this working in kitty + neovim? I am using the following settings with the tokyonight.nvim theme and the cursor doesn't change color at all.

```
cursor none
shell_integration no-cursor
```

Is there something I need to change on neovim side or is it depending on the theme being used? Using Alacritty the cursor by default reverses when I am in neovim. As the documentation mentioned:

"Note that if the program running in the terminal sets a cursor color, this takes precedence. Also, the cursor colors are modified if the cell background and foreground colors have very low contrast."

Does this means that the theme in neovim is overriding the cursor color of kitty? I tried setting cursor colors in both kitty and neovim highlight Cursor but changes doesn't take effect.

Thanks

**Comment by Yuxin0610** [comment]
> iTerm2 for macOS does this. I don't know of any terminal applications on Linux that does this, but I'm sure there has to be some. I've attached a short gif demonstrating the behaviour with the effect I'd like.
> 
> ![cursor](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif) [ ![cursor](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif) ](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif) [ ](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif)

I am also using iterm2 but it doesn't do this. How did you make it work in iterm2?

**Comment by Yuxin0610** [comment]
> iTerm2 for macOS does this. I don't know of any terminal applications on Linux that does this, but I'm sure there has to be some. I've attached a short gif demonstrating the behaviour with the effect I'd like.
> 
> ![cursor](https://user-images.githubusercontent.com/6175959/30511158-5cd1765e-9ad3-11e7-99bc-ed4e5019244d.gif)

I am also using iterm2 but it doesn't do this for me. How did you make it work in iterm2?

**Comment by joelpeapen** [comment]
After playing with this for a while trying to get it to work, i realised the themes were setting the cursor colors. Can the `kitty.conf` to override the colors from `current-theme.conf` so switching between themes with `kitten themes` doesn't interfere with my permanent options? Thanks.

**Comment by kovidgoyal** [comment]
On Wed, Feb 14, 2024 at 09:19:56PM -0800, Joel Eapen wrote:
> After playing with this for a while trying to get it to work, i realised the themes were setting the cursor colors. Can the `kitty.conf` to override the colors from `current-theme.conf` so switching between themes with `kitten themes` doesn't interfere with my permanent options? Thanks.

Use --config-file-name for the themes kitten and include that file in
kitty.conf, then the themes kitten wont touch kitty.conf.

**Comment by joelpeapen** [comment]
> On Wed, Feb 14, 2024 at 09:19:56PM -0800, Joel Eapen wrote: After playing with this for a while trying to get it to work, i realised the themes were setting the cursor colors. Can the `kitty.conf` to override the colors from `current-theme.conf` so switching between themes with `kitten themes` doesn't interfere with my permanent options? Thanks.
> Use --config-file-name for the themes kitten and include that file in kitty.conf, then the themes kitten wont touch kitty.conf.

`kitten themes --config-file-name` modifies `themes.conf` with `incude current-theme.conf`, which contains a new cursor value from the chosen theme. `kitty.conf` is untouched, but `current-theme.conf`'s cursor value takes precedence over `cursor none` in `kitty.conf`

**Comment by kovidgoyal** [comment]
On Wed, Feb 14, 2024 at 10:56:31PM -0800, Joel Eapen wrote:
> > On Wed, Feb 14, 2024 at 09:19:56PM -0800, Joel Eapen wrote: After playing with this for a while trying to get it to work, i realised the themes were setting the cursor colors. Can the `kitty.conf` to override the colors from `current-theme.conf` so switching between themes with `kitten themes` doesn't interfere with my permanent options? Thanks.
> > Use --config-file-name for the themes kitten and include that file in kitty.conf, then the themes kitten wont touch kitty.conf.
> 
> `kitten themes --config-file-name` modifies `themes.conf` with `incude current-theme.conf`, which contains a new cursor value from the chosen theme. `kitty.conf` is untouched, but `current-theme.conf`'s cursor value takes precedence over `cursor none` in `kitty.conf`

No, it doesnt, provided you put cursor none **AFTER** the include
