### ISSUE TITLE
Large margin outside window's borders despite it being disabled

### ISSUE THREAD

**Issue by bool3max** [kovidgoyal/kitty#1261]
[`kitty --debug-config output`](https://pastebin.com/8TJTxYVi)
* using kitty on `i3 v4.16` and arch `kernel 4.19.12`

Having 2 windows open in a vertically-split layout causes noticeably large top and bottom (and sometimes horizontal) margins to appear outside of the windows' borders, despite them being completely disabled in the config: 

![Image](https://user-images.githubusercontent.com/12991998/50383449-edcc1b80-06b3-11e9-894a-ea6e54d5977f.png) 
the white border is kitty's while the orange one is the wm's

Disabling window borders in i3 causes the problem to somewhat disappear (*some horizontal margins are still present*): 
![23-12-2018--13 09 00](https://user-images.githubusercontent.com/12991998/50383468-5b784780-06b4-11e9-83a5-18f4fdc3e1fa.png)

Changing the font size/family doesn't help, as does not changing the border width in i3.

**Comment by kovidgoyal** [comment]
If the window size is not an exact multiple of the cell size there will be some extra pixels left over, since kitty does not draw partially cutoff lines/columns.
