### ISSUE TITLE
Differentiate between Return, Ctrl+Return, Shift+Return etc.

### ISSUE THREAD

**Issue by sztomi** [kovidgoyal/kitty#1265]
I ran showkey and pressed Return, Ctrl+Return, Alt+Return and Shift+Return.

```
➜ showkey -a

Press any keys - Ctrl-D will terminate this program

^M 	 13 0015 0x0d
^M 	 13 0015 0x0d
^[^M 	 27 0033 0x1b
 	 13 0015 0x0d
^M 	 13 0015 0x0d
^D 	  4 0004 0x04
```

It seems that only Alt+Return generates a different keycode and none of the others. I realize that other terminals don't differentiate either, but this would be a useful feature IMO. Is there any way to achieve this currently or is it something that might be possible in the future?

**Comment by kovidgoyal** [comment]
See the extended keyboard protocol at https://sw.kovidgoyal.net/kitty/protocol-extensions.html

**Comment by kovidgoyal** [comment]
And you can map any key combination to generate any bytes you like using the send_text directive in kitty.conf

**Comment by sztomi** [comment]
Fantastic, thank you!
