### ISSUE TITLE
Scrolling is transfered between tabs

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1267]
If i scroll in one tab and change to a new tab, the new view will continue to scroll ( if enough history in view ). This seem unintentional. I would expect scroll state is kept per tab.

**Comment by Luflosi** [comment]
Tell us more about your environment please. Which OS and kitty version are you using?

**Comment by kovidgoyal** [comment]
I am guessing this is because of momentum scrolling? The OS will keep
sending scroll events even when the user is not touching the trackpad for
a little while. Is that correct?

**Comment by erf** [comment]
That is correct.

**Comment by kovidgoyal** [comment]
I've already made a commit that makes this easy to fix: https://github.com/kovidgoyal/kitty/commit/fc5e74e45707b78da3c57c9389d5f4f64fbcda7f

Just need to track the current window id when momentum scrolling starts,
and if the window id changes ignore the scroll events until momentum
scrolling ends. Feel free to send a PR with that, or I will get to it
when I have a moment.
