### ISSUE TITLE
How to set specific font for all chinese character

### ISSUE THREAD

**Issue by yqrashawn** [kovidgoyal/kitty#127]
I don't know if it's the font's problem. But Chinese characters are squeeze into each other. 
```shell script
font_family      monospace
italic_font      auto
bold_font        auto
bold_italic_font auto
```
![Chinese character squeeze into each other](https://user-images.githubusercontent.com/15090582/30526624-317c8bfa-9c50-11e7-9743-b5108b906ca4.png)

**Comment by kovidgoyal** [comment]
This will happen if the wcwidth function on your system is outdated/broken. You can test if that is the case by using the option to use internal wcwidth in the kitty config. Note that doing that will cause other problems unless you can also get the programs running in the terminal to use a modern wcwidth. 

See the attachment for what wide characters look like on a system with proper wcwidth() in kitty
![screenshot_20170918_075829](https://user-images.githubusercontent.com/1308621/30527516-37d7f2fe-9c47-11e7-9d69-1657c5b803e4.png)

**Comment by yqrashawn** [comment]
@kovidgoyal So the command that went wrong is the default ls command. That means I need to wait for apple to update the command line tool or there's no other way to fix this?

Another problem is my computer restart when launching kitty. It's a hackintosh macOS 10.12 GTX1080. And the hackintosh in my office (macOS 10.11 GTX960) don't have the problem.

**Comment by kovidgoyal** [comment]
Your computer restarting is an issue with GPU drivers. Nothing I can do about it. As for wcwidth, it comes from the system C library, so either you have to wait for the OS vendor to update it or patch it yourself, or use some LD_PRELOAD type hack to replace it at runtime (I assume OS X has an equivalent to LD_PRELOAD).
