### ISSUE TITLE
the background keeps going back to an opacity of 1

### ISSUE THREAD

**Issue by joshuah345** [kovidgoyal/kitty#1276]
i have it in my conf file to set the opacity of terminals to a very low value (0.1) and after a while the background opacity resets to 1 even though the conf says 0.1

compton (compositor) is still running as transparency on other ui elements work.

current conf file 

include snazzy.conf
font_family      SF Mono
bold_font        SF Mono Bold
italic_font      SF Mono Italic
bold_italic_font SF Mono Bold Italic
cursor_shape underline
tab_bar_style fade
active_tab_font_style bold
inactive_tab_font_style normal
inactive_tab_background   #686869
tab_fade 0.89 1
background_opacity 0.1
window_margin_width 8.0

**Comment by joshuah345** [comment]
Arch Linux
WM : I3-gaps
kitty 0.13.1

**Comment by kovidgoyal** [comment]
cannot reproduce. what does after a while mean? kitty itself contains no code that could possibly cause transparency to spontaneously disappear. Indeed, the value of transparency gets hardcoded into the shaders that are compiled at program startup, see load_shaders() in window.py.

The only scenario in which the background color will be non-transparent is if something is explicitly setting the background color to the non default value via ANSI escape codes, as kitty only renders the default background color as transparent.

So either you have some such program running or your window system's implementation of transparent windows is breaking. You can eliminate the former by simply running

kitty cat

and leaving it alone for "some time" and seeing if it remains transparent.

**Comment by joshuah345** [comment]
[363 05:18:17.651422] Failed to enable transparency. This happens when your desktop environment does not support compositing. 

but compton is running

**Comment by joshuah345** [comment]
relaunching compton and then opening a new kitty window works though
 im not sure about it happening again though

**Comment by kovidgoyal** [comment]
I suggest switching to wayland where transparency is a first class citizen. Use KITTY_ENABLE_WAYLAND=1 to use kitty's wayland backend.

**Comment by LinuxIsCool** [comment]
I'm having this issue. After about 0.5 seconds of launching kitty, transparency goes to 1. Happens when running `kitty cat`.

**Comment by LinuxIsCool** [comment]
It happens after focusing the kitty window, not just opening it. When I switch to another window and then back to kitty, it will be transparent, but then turn to opacity 1 after about 0.5 seconds.

**Comment by FujiwaraChoki** [comment]
Was a fix found for this?
