### ISSUE TITLE
docs: improve rendering of :option: / fix desc with "Keyboard shortcuts"

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#1279]
In `docs/generated/conf/kitty.conf` `:option:`kitty --debug-keyboard`` gets rendered as `kitty --debug-keyboard`.
1. I think this should have double backticks in the config file
2. It should not have "kitty" in there additionally

Section in the rendered docs: https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts
Rendered default conf: https://sw.kovidgoyal.net/kitty/_downloads/fdd5fc58492b70fe2188716f86e7ff87/kitty.conf

**Comment by kovidgoyal** [comment]
1. why should it have backticks in the config file? It's not written in markdown or similar. It is plain text.

2. kitty is there because that option applies to running kitty, not one of its sub-programs such as a kitten.

**Comment by blueyed** [comment]
> why should it have backticks in the config file?

It uses backticks also later in that section:

> In that text look for ``native_code`` the value of that becomes the key name in the shortcut.

It might also prevent the text from wrapping as a sideeffect.

Anyway, not really important - I've just noticed it when diffing the new default config.
