### ISSUE TITLE
remapping split window controls using osx CMD

### ISSUE THREAD

**Issue by davidosomething** [kovidgoyal/kitty#128]
Can you provide an example of how to remap new-window+switch-vertical-layout at the same time to cmd-d ?

**Comment by kovidgoyal** [comment]
You cannot map multiple actions to a single shortcut. You need to use multiple shortcuts for that.

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/kitty/commit/efc8b898f87db2bc71d26b7bed743b84c0d021c3
