### ISSUE TITLE
set_background_opacity subtraction does not work

### ISSUE THREAD

**Issue by mvrozanti** [kovidgoyal/kitty#1282]
Relevant part of `kitty.conf`:
```
background_opacity         0.7
dynamic_background_opacity yes
map kitty_mod+j    set_background_opacity -0.01
map kitty_mod+k    set_background_opacity +0.01
map kitty_mod+l    set_background_opacity 1
map kitty_mod+0    set_background_opacity default
```

`kitty_mod+l`, `kitty_mod+0` and `kitty_mod+k` work as expected.  `kitty_mod+j` does not. It actually removes transparency (can be reverted with `set_background_opacity default`). Is the syntax correct? 

```
$ kitty cat

[365 15:02:39.264733] Ignoring unknown config key: scrollback_pager_history_size
[365 15:02:39.264769] Ignoring unknown config key: touch_scroll_multiplier
[365 15:02:39.265046] Ignoring unknown config key: hide_window_decorations
```

Installed using `pacman` on i3-gaps on Arch Linux

**Comment by kovidgoyal** [comment]
yes the syntax is correct. Have you enabled dynamic_background_opacity? And do the default shortcuts work?

**Comment by kovidgoyal** [comment]
Does background opacity work at all, I notice you said you use i3, as
far as I know, on X11 without some compositor running, transparency does
not work at all.

**Comment by mvrozanti** [comment]
I'm using `compton`
I get transparency, I just don't get decreasing opacity.

**Comment by kovidgoyal** [comment]
run kitty in a terminal and see if it prints out any error messages when starting up or changing transparency.

**Comment by kovidgoyal** [comment]
you appear to be using an out of date version of kitty, update and you should be fine.

**Comment by mvrozanti** [comment]
I'm running 0.12.3 
I'm gonna try and clone this repo

**Comment by kovidgoyal** [comment]
Umm th elatest version of kitty on arch is the current one, 0.13.1. Or just use the official kitty biaries if you dont want touse the arch package.

**Comment by mvrozanti** [comment]
Thanks it worked! 0.13.1 works as expected. I'm not sure if you're refering to AUR, I'm getting only version 0.12.3 through `pacman`

**Comment by kovidgoyal** [comment]
https://www.archlinux.org/packages/community/x86_64/kitty/

**Comment by mvrozanti** [comment]
Needed an update. Happy new year's !
