### ISSUE TITLE
Semi-transparency does not work with colors other than black.

### ISSUE THREAD

**Issue by gleason2** [kovidgoyal/kitty#1285]
I am trying to use a white background with 50% opacity, but it only becomes transparent when I configure it to 0 opacity.

**Comment by kovidgoyal** [comment]
No it only does not work with white. Choose a slightly off-white shade
such as #eee and you will be fine.

**Comment by Luflosi** [comment]
Why does it not work with white?

**Comment by kovidgoyal** [comment]
If I had to guess, I'd say white is used a sentinel value somewhere, since it is 0xffffff

**Comment by Luflosi** [comment]
It's not a sentinel value, since 0xfefefe didn't look any different than 0xffffff in my testing, it's most likely a problem in the color blending in the shader code.
