### ISSUE TITLE
Changing the current tab color

### ISSUE THREAD

**Issue by octplane** [kovidgoyal/kitty#1287]
Hello,

thanks for kitty!

Would you be interested in adding a command to change permanently the current tab color? I use [a small app](https://github.com/octplane/cocotte) to color my iTerm tabs and was looking for a way to do the same in kitty. If you can point me at some code, I'll gladly try and add the feature.

**Comment by kovidgoyal** [comment]
seems somewhat odd using an escape code for that. A tab can have more than one window, so either:

1) last color received by some window in the tab wins
2) the color set by the current active window is used

(1) is easier to implement, (2) is more correct.

If you want to implement it, you would first need to implement anew escape code for it, probably something under the DCS namespace with the @ key, look in parser.c for dispatch_dcs()

then add a handler to store the requested color in window.py. Then implement using that color in tabs.py and tab_bar.py

**Comment by kovidgoyal** [comment]
Oh and for ease of use there should really be an interface for this in kitty remote control as well, since presumably escape codes will only be allowed to change the color of the current tab.

**Comment by giftig** [comment]
I think option (1) is actually pretty reasonable if you consider the tab colour as belonging to the tab, not belonging to the window (which seems fair enough since it's the colour of the tab itself).

**Comment by securisec** [comment]
@kovidgoyal are you releasing this feature in an upcoming release or is it nightly releases from now on? Asking because 0.23.1 was a while ago.
