### ISSUE TITLE
cursor_text_color background option has no effect

### ISSUE THREAD

**Issue by jcrd** [kovidgoyal/kitty#1288]
kitty version: 0.13.2
OS: Arch Linux 4.20.0-zen1-1-zen

`cursor_text_color background` worked as expected in 0.13.1, but as of 0.13.2 it has no effect.

**Comment by kovidgoyal** [comment]
I cannot reproduce on Arch, running kitty as:

kitty -o cursor_text_color=red

causes the text under the cursor to be rendered in red.

**Comment by jcrd** [comment]
Sorry, I was referring to the special keyword `background` discussed in #126. Specifying the color directly as in your example still works.
