### ISSUE TITLE
Start hints markers from 1 instead of 0

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#1289]
When using hints, I often select one of the last ones. For 1 and 2 this is practical, because they are close to ctrl+shift+e so I can do all presses with the left hand (e.g. if my right hand is at the mouse). However, I can't reach 0 with the left hand, so to select the last hint, I have to use both hands.

A nice solution for this would be to start the hints at 1 instead of 0. What do you think?

**Comment by lamby** [comment]
Ah, the power of defaults; only until this change did I realise that the `<shortcut> → 0` was so ingrained in me that it was distressing that I thought I wouldn't be able to configure it back..!

**Comment by kovidgoyal** [comment]
Yeah I try to make it a point to never make changes to existing functionality without some way of configuring them back, as I too hate changing my ingrained behaviors.

**Comment by nkiesel** [comment]
Can you please add an entry to the example `kitty.conf` that shows how/where to specify that? I tried to simply add a line `hints_offset 1` to my `~/.config/kitty/kitty.conf` but that produces:
```
lt-nkiesel:~/.config/kitty% kitty --debug-config                             
kitty 0.13.3 created by Kovid Goyal
Linux lt-nkiesel 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64
Running under: X11
Debian GNU/Linux buster/sid \n \l
Loaded config files: /home/nkiesel/.config/kitty/kitty.conf
[028 11:04:53.043904] Ignoring unknown config key: hints_offset
```

**Comment by nkiesel** [comment]
Can you please add an entry to the example `kitty.conf` that shows how/where to specify that? I tried to simply add a line `hints_offset 1` to my `~/.config/kitty/kitty.conf` but that produces:
```
lt-nkiesel:~/.config/kitty% kitty --debug-config                             
kitty 0.13.3 created by Kovid Goyal
Linux lt-nkiesel 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64
Running under: X11
Debian GNU/Linux buster/sid \n \l
Loaded config files: /home/nkiesel/.config/kitty/kitty.conf
[028 11:04:53.043904] Ignoring unknown config key: hints_offset
```

**Comment by lamby** [comment]
It's actually part of the `run_kitten` args, not a global:

```
map ctrl+shift+u         run_kitten text hints --hints-offset=0
```
(:+1: on an example in the `kitty.conf` docs for this very reason.)

**Comment by nkiesel** [comment]
Thanks.

This means I have to add this to all kittens if I want to restore the previous behavior, correct?

In the future, it might be better to leave the original value as the default (as long as that is a defensible position, would eg not apply to settings where the new value is more secure). That way, users who want this pay the price and not the ones who are happy with the current setup.

**Comment by kovidgoyal** [comment]
What all kittens? There is only one affected kitten. And, I'm sorry but,
rarely, defaults will change if a clearly better value for a default is
found. I refuse to let software ossify for ever because of an initial
poor choice. It's not just users who like the existing behavior that pay
the price, it is new users as well, that will tend to just go with the
inferior default.

And the option is already documented, here: 
https://sw.kovidgoyal.net/kitty/kittens/hints.html

**Comment by nkiesel** [comment]
yeah, I only read the changelog and not the manual page.  The manual page does indeed describe that.  One tiny caveat: it says: "Note that only numbers greater than zero are respected."  But `0` is valid, no?

Regarding only 1 kitten: I thought I have to change that for all kitten mappings, like so:
```
map kitty_mod+e kitten hints --hints-offset=0
map kitty_mod+p>f kitten hints --hints-offset=0 --type path --program -
map kitty_mod+p>shift+f kitten hints --hints-offset=0 --type path
map kitty_mod+p>l kitten hints --hints-offset=0 --type line --program -
map kitty_mod+p>w kitten hints --hints-offset=0 --type word --program -
map kitty_mod+p>h kitten hints --hints-offset=0 --type hash --program -
```
Did I still get this wrong?

**Comment by kovidgoyal** [comment]
No you would need to change it for every mapping involving the hints
kitten, you are correct there. I thought you were referring to changing
invocations for other kittens.
