### ISSUE TITLE
Scroll by half page

### ISSUE THREAD

**Issue by cvincent** [kovidgoyal/kitty#1293]
Is it possible to map keys like `scroll_page_up` and `scroll_page_down` but only by half pages?

**Comment by kovidgoyal** [comment]
no there is no scroll by half page function in kitty to bind to. Not something I am interested in personally, but patches are welcome.

**Comment by filchristou** [comment]
for future reference you can do that as described here https://github.com/kovidgoyal/kitty/issues/5294
e.g. `map ctrl+shift+page_up remote_control scroll-window 0.5p-` to scroll up have a page.
