### ISSUE TITLE
A few kitty questions and feedback 🤓

### ISSUE THREAD

**Issue by jenstroeger** [kovidgoyal/kitty#1294]
Hi,

Just stumbled upon `kitty` and I’m very intrigued and excited, thank you for all the work, @kovidgoyal! There are a few things that I noticed and I wanted to bring up, so I hope filing an issue here is acceptable…

 1. When I quit kitty it just quits. Which I guess is ok when I have no tabs or windows or terms open, but it also quits when a lot of terms are running stuff. In such cases it would be great if kitty could just pop open a small alert window “Are you sure you want to quit and terminate all processes?” or some such.
 2. You mentioned in the config that the window title bar on macOS is out of reach, so there is no way to remove it completely? It would be nice to have the kitty window without a title bar sitting below the screen menu. Or: full-screen mode and still see the screen menu (because I’m running [iStats](https://bjango.com/mac/istatmenus/)).
 3. Can I put monitoring information into the tab bar?
 4. Just noticed today that standard macOS keys like `opt-[` don’t produce `”` and so forth, i.e. it seems that the keyboard mappings are incomplete?
 5. Is it possible to save all tabs and terms when I quit kitty, and restore it all upon the next start?
 6. Is it possible to open tabs to the left/right of the current one, instead of appending to the end?
 7. I have been using [i3](https://i3wm.org/) on Mac and Linux so I quite like that binary-tree tiling. Have you considered adding that?

Happy to file separate issues if need be, and I’m curious about your thoughts regarding the above!

Cheers,
Jens

**Comment by kovidgoyal** [comment]
On Tue, Jan 08, 2019 at 01:49:13PM -0800, Jens Troeger wrote:
> Hi,
> 
> Just stumbled upon `kitty` and I’m very intrigued and excited, thank you for all the work, @kovidgoyal! There are a few things that I noticed and I wanted to bring up, so I hope filing an issue here is acceptable…
> 
>  1. When I quit kitty it just quits. Which I guess is ok when I have no tabs or windows or terms open, but it also quits when a lot of terms are running stuff. In such cases it would be great if kitty could just pop open a small alert window “Are you sure you want to quit and terminate all processes?” or some such.

See #734

>  2. You mentioned in the config that the window title bar on macOS is out of reach, so there is no way to remove it completely? It would be nice to have the kitty window without a title bar sitting below the screen menu. Or: full-screen mode and still see the screen menu (because I’m running [iStats](https://bjango.com/mac/istatmenus/)).

See the hide_window_decorations config option.

>  3. Can I put monitoring information into the tab bar?

No.

>  4. Just noticed today that standard macOS keys like `opt-[` don’t produce `”` and so forth, i.e. it seems that the keyboard mappings are incomplete?

See the macos_option_as_alt config option.

>  5. Is it possible to save all tabs and terms when I quit kitty, and restore it all upon the next start?

No, but you can create session files.

>  6. Is it possible to open tabs to the left/right of the current one, instead of appending to the end?

See the neighbor feature of new_tab

>  7. I have been using [i3](https://i3wm.org/) on Mac and Linux so I quite like that binary-tree tiling. Have you considered adding that?

No, not a fan of binary tiling, I prefer layouts. That said you can
easily (well relatively easily) create a layout that does that.
