### ISSUE TITLE
Doesn't require scalable fonts

### ISSUE THREAD

**Issue by n1-cz** [kovidgoyal/kitty#1295]
Hi there

I would like to thank you for this amazing peace of software. Althought I do have one thing. Many people use bitmap fonts. See here: https://github.com/Tecate/bitmap-fonts

Althought kitty doesn't allow to use these fonts. Why? They are designed for terminals and I have to say I will never look back to non bitmap font for terminal. My eyes will thank me one day.

Is it possible to add a config directive to turn off this behavior and make kitty to load bitmap fonts? Pretty please? :)

**Comment by maximbaz** [comment]
This has been discussed previously 😉 https://github.com/kovidgoyal/kitty/issues/97#issuecomment-373970232

**Comment by kovidgoyal** [comment]
dup of #97

**Comment by Al-Caveman** [comment]
@im-n1 - time to fork kitty.

**Comment by CMOISDEAD** [comment]
we need a fork
