### ISSUE TITLE
OSX: converting tab to window in "traditional" fullscreen mode crashes Kitty 0.13.2

### ISSUE THREAD

**Issue by jtdaugherty** [kovidgoyal/kitty#1296]
OS X version: 10.13.6

Steps to reproduce:
* In the Kitty config, set `macos_traditional_fullscreen yes`.
* Start Kitty fresh (i.e., no previous running Kitty session).
* Fullscreen the new window.
* Open a new window/tab with `Command-n`.
* In the tab bar that appears at the top of the window, drag the newly-created window's tab downward out of the tab bar.

Expected behavior: dragged tab results in new separate OS X window.

Observed behavior: Kitty crashes and all windows disappear.

**Comment by kovidgoyal** [comment]
kitty has no facility for converting tabs to windows, so I am not sure what you are referring to? Also the kitty tab bar appears at the bottom of the window, by default, unless you have changed it in kitty.conf

And you open new tabs using the shortcut ctrl+shift+t

I think you are talking about some native macOS fullscreen window mangement feature? Where if you open new fullscreen window macOS shows them as tabs? Not a macOS user so no idea.

**Comment by jtdaugherty** [comment]
Thanks for your response. Please re-open this ticket, since we have not resolved the issue.

Have you attempted to follow the steps that I outlined in the original report to see if you can reproduce the behavior? I think that will help provide answers to your questions.

**Comment by kovidgoyal** [comment]
Umm the issue was closed because it has been fixed, at least to the extent that kitty will no longer crash when macOS reports invalid DPI numbers. See the commit that closed this issue.

**Comment by jtdaugherty** [comment]
Thanks, sorry about that - I didn't see the commit that closed this and you didn't mention it. That, combined with your various questions and uncertainty that my problem could exist, left me feeling confused that the ticket was closed since you didn't confirm one way or the other. A more explicit communication would have been helpful.

Do you know when the fix will be released?

**Comment by jtdaugherty** [comment]
Okay. Thanks!

**Comment by jtdaugherty** [comment]
> Also the kitty tab bar appears at the bottom of the window, by default, unless you have changed it in kitty.conf

Something else I wanted to note is that at least in 0.13.2, tabs *do* appear at the top of the screen when using the steps I described above, and I have not customized that behavior. I've attached a screenshot that shows this:

<img width="1920" alt="screen shot 2019-01-11 at 9 04 31 am" src="https://user-images.githubusercontent.com/427221/51048494-f6f82c00-157f-11e9-91d6-63f301cfa32d.png">

**Comment by kovidgoyal** [comment]
Those are not kitty tabs. Those are OS tabs. if you want to see kitty tabs press ctrl+shift+t
