### ISSUE TITLE
Negative scroll multiplier not applied in vim

### ISSUE THREAD

**Issue by ATonyNgo** [kovidgoyal/kitty#1299]
As of release version 0.13.2, negative scrolling multipliers in kitty.conf aren't applied properly in `vim`. I have narrowed the problem down locally to [this merge](https://github.com/kovidgoyal/kitty/commit/b881364c504e79950942dc38ec355a360091fc31).

For reference I am using a touchpad on a Dell XPS 9730 on Arch Linux. The reverse multiplier seems to be applied fine in other applications such as `less`. I also have both `wheel_scroll_multiplier` and `touch_scroll_multiplier` in my config both set to a negative value (-3).

**Comment by Luflosi** [comment]
This was my pull request #1263, which fixed #1257. Sorry, evidently I didn't think about negative multipliers. Multiplying `s` with -1 if `OPT(wheel_scroll_multiplier)` is less than 0 should fix this issue. @kovidgoyal can you think of a better fix? If not, I can make a pull request.
