### ISSUE TITLE
[macOS] Cursor selection is off on retina display

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#130]
I believe there has been a regression after the rewrite in the *fast* branch.
Briefly looking through the issue history, it seems like the same problem as #43

Basically, when I try to select text using the mouse, the selection x and y coordinate is off, the text that is selected is further towards the top-left than it should be.

This is not really a high priority issue as I barely use the mouse, but figured it was worth mentioning.

**Comment by kovidgoyal** [comment]
I have committeda  fix but I have no way to test it, so let me know if it works.
