### ISSUE TITLE
Per-window background colours?

### ISSUE THREAD

**Issue by giftig** [kovidgoyal/kitty#1300]
First of all, I swapped to kitty today and I'm already enjoying it over my previous roxterm, so thanks.

One thing I'd really like to see is a background colour per window. I'm using the grid window layout and I usually split my terminal into 4 or 6 windows, and background colour is a nice way to break them up visually, as well as to mark different panes' purposes - e.g. I might make two grey because they're tailing some logs and one red because I've SSHed into a production box.

I imagine it being configured similarly to how you set tab titles, so something like a window_background_color directive you can use in the session file and as a keyboard shortcut.

Ideally I actually want a background image per window (one of the very few things I miss about iOS when I use linux is having a terminal emulator where I can have split panes and pretty backgrounds) but that's a separate thing and I've commented on an issue related to that just now.

Is the per-window colouring something which might be considered?

**Comment by kovidgoyal** [comment]
You can set background colors using either terminal escape codes or the kitty remote control feature: https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by giftig** [comment]
Changing the background colour of a terminal window is not the same thing as setting the background colour of some text in a terminal using OSC escape codes.

**Comment by kovidgoyal** [comment]
Yes, it is, since there exist escape codes to change terminal colors,
including background and foreground.
