### ISSUE TITLE
FZF navigation for tabs

### ISSUE THREAD

**Issue by devth** [kovidgoyal/kitty#1303]
I'm wondering if it would be possible to navigate kitty tabs using a FZF window that would fuzzy match all available tab names. This is how navigating tmux sessions works.

**Comment by kovidgoyal** [comment]
You can use the kitty remote control feature to navigate kitty windows however you like, including using fzf itself by writing a script to get the list of window titles and passing it to fzf. https://sw.kovidgoyal.net/kitty/remote-control.html

If you want to avoid using remote control, you can write a kitten to do the same thing, https://sw.kovidgoyal.net/kitty/kittens/custom.html

**Comment by rmacklin** [comment]
Just stumbled upon this old issue after wondering about the same question. @devth @sethwoodworth Did you happen to write a script or kitten to do this?

**Comment by devth** [comment]
I never did :(

**Comment by rmacklin** [comment]
That's okay, thanks for responding! If I write one I'll share it here in case you're still interested (or did you switch to something other than kitty since then?)

**Comment by page-down** [comment]
I have shared a similar script before.

```text
https://github.com/kovidgoyal/kitty/issues/5503#issuecomment-1247592401
```

Only minor adjustments are needed to use the latest versions of kitty and fzf.
The following script selects the tab titles of the current OS window.

```bash
#!/usr/bin/env bash
fzf --with-nth 2.. --bind 'enter:execute-silent(kitty @ focus-tab -m id:{1})+accept' > /dev/null \
    <<<$(kitty @ ls | jq -r '.[] | .tabs[] | select(.is_focused == false) | (.id|tostring) + " " + .title')
```

```conf
map f1 launch --allow-remote-control /path/to/script
```

**Comment by brandonchinn178** [comment]
FYI the above script won't work as-is because bash doesn't preserve newlines by default in `$(...)` (you have to quote it). Here's my script, which works:

```bash
#!/usr/bin/env sh

all_tabs="$(
    kitty @ ls | jq -r '
        .[]
        | select(.is_active)
        | .tabs[]
        | select(.title != "Tab selection")
        | [.title, "id:\(.id)"]
        | @tsv
    ' | column -ts $'\t'
)"

new_tab_id="$(fzf --reverse <<< "${all_tabs}" | awk '{ print $2 }')"
kitty @ focus-tab -m "${new_tab_id}"
```
<img width="228" alt="Screen Shot 2022-12-20 at 8 09 08 PM" src="https://user-images.githubusercontent.com/6827922/208819317-64b26d99-6327-4aca-bea8-6bd4919e7c6f.png">

**Comment by slikie** [comment]
> new_tab_id="$(fzf --reverse <<< "${all_tabs}" | awk '{ print $2 }')"

This is gonna result in wrong match when tab title includes space. I think replacing with $NF is fine.
new_tab_id="$(fzf --reverse <<< "${all_tabs}" | awk '{ print $NF }')"

**Comment by roylez** [comment]
I made some change to the script to allow it jump to any window in any tab or os window. It is a poorman's imitation of tmux's `choose-tree`.

``` bash
#!/usr/bin/env sh

windows=$(kitty @ ls | \
  jq -r '
    .[]
    | .id as $os_win_id
    | .tabs[] += { tab_len: (.tabs|length) }
    | .tabs[]
    | select(.is_focused == false)
    | .id as $tab_id
    | .tab_len as $tab_len
    | .windows[] += { tab_id: $tab_id, os_win_id: $os_win_id, win_len: (.windows|length), tab_len: $tab_len }
    | .windows[]
    | [.os_win_id, .tab_id, .id, .tab_len, .win_len, .title  ]
    | @tsv
    ' |\
  awk -F"\t" '
      {
        single_tab=$4==1;
        single_win=$5==1;
        last_tab=$4==i+1;
        last_win=$5==j+1;
        first_tab=i==0;
        first_win=j==0;
      }

      { printf $3"\t" }

      single_tab && first_win { printf "---" }
      !single_tab && first_win { printf "+--" }
      !single_win && !first_win { printf "   " }

      single_win { printf "---" }
      !single_win { printf "+--" }

      {print "\t"$1":"$2"\t"$6}

      { last_tab ? i=0 : i++ ; last_win ? j=0 : j++}
      ' |column -ts  $'\t'
    )


window_id=$(fzf --prompt="CHOOSE WINDOW> " --nth=1,4 --reverse <<< "${windows}" | awk '{ print $1 }')

kitty @ focus-window -m "id:${window_id}"
```
![screenshot 2024 06 19 1322](https://github.com/kovidgoyal/kitty/assets/62289/cd1b2f7a-4dbe-4b03-8d1d-4066358b1376)

**Comment by jamesb93** [comment]
I posted my own script here, https://github.com/kovidgoyal/kitty-fosshack2024/issues/1#issuecomment-2215503849.
