### ISSUE TITLE
Cannot render invisible characters correctly in vim

### ISSUE THREAD

**Issue by sashasylona** [kovidgoyal/kitty#1307]
# Issue
When inserting whitespace into vim (tabs, spaces, newlines, carriages), it is rendered with Kitty's background color, not the current vim theme. 
# Reproduction
Set Kitty's background color to #FFF, install dark theme for vim. Open a source file and insert a <CR> at the end of a line. The resulting `\n` should be #FFF as opposed to the rest of the source file. This malrendered whitespace can then be relocated. If the <CR> is deleted, the discolored whitespace will render beginning at the end of the previous line.
# Miscellany
This issue only occurs on vim, I couldn't reproduce it on neovim. It also does not occur on any non-Kitty terminals (tested on gnome-term, termite, tilix, and 16-color tty). My system uses nvidia proprietary drivers on i3-gaps with Arch, but this also happens on Void and Alpine with gnome and xfce terminals under both proprietary and libre/mesa drivers.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim

**Comment by sashasylona** [comment]
xterm-kitty is the output of `echo $TERM` and `let &t_ut=''` is in my .vimrc.

**Comment by kovidgoyal** [comment]
I cannot reproduce, post a minimal vimrc and kitty.conf and set of steps to reproduce the issue.
