### ISSUE TITLE
Wrong binding for ctrl-z with HR layout

### ISSUE THREAD

**Issue by vsajko** [kovidgoyal/kitty#131]
When using HR keyboard layout (z and y keys are swapped):
cat ctrl-z gives ^Y
cat ctrl-y sends cat to background

Expected is that ctrl-z sends cat to background and ctrl-y gives ^Y.

Works correctly with US layout
I can't reproduce it in Xterm, urxvt, gnome-terminal, linux console

**Comment by kovidgoyal** [comment]
kitty does not do interpretation of keyboard event itself, that is up to glfw the iwndowing toolkit kitty uses. Presumably, that has issues with this keyboard layout. You can test that by looking in the on_key_input() function in keys.c 

Uncomment line 157 and you will see what key glfw is reporting as being pressed. If I am correct, you should report the issue on the glfw bug tracker.
