### ISSUE TITLE
Feature request: Move window to another Tab

### ISSUE THREAD

**Issue by binor** [kovidgoyal/kitty#1310]
Sometimes I'd like to move a window to another Tab when organizing Tabs. Would this be a feature you could implement?

**Comment by kovidgoyal** [comment]
should also have the possibility to make a new tab from the window.

**Comment by torfsen** [comment]
I have the opposite need: A tab that I'd like to make into a window.

BTW, thanks for Kitty, it's awesome!

**Comment by kovidgoyal** [comment]
Since a tab contains multiple windows how does it become a window?

**Comment by torfsen** [comment]
@kovidgoyal Perhaps a better formulation would be: I'd like to move all windows from one tab into another tab and automatically close the first tab.

**Comment by kovidgoyal** [comment]
Sorry I dont understand your use case? What does moving al lwindows from a tab into a new different tab and closing the old tab achieve that simply renaming the old tab/moving it around does not?

**Comment by yurikhan** [comment]
I think @torfsen is asking for tab merging. At start: tab A has windows A1, A2, …, An, tab B has B1, B2, …, Bm; on completion: tab A contains windows A1, A2, …, An, B1, B2, Bm; tab B no longer exists.

**Comment by kovidgoyal** [comment]
ah well, that is basically the same as move one window, just move all instead.

**Comment by 0x17de** [comment]
i am working on a patch to move windows into separate tabs (which is working for me so far). i just need to finish the documentation parts and check if some cleanups are required before i submit a PR.
once this is done it should be easy to implement the opposite direction.

do you have some idea for hotkeys for both directions?

**Comment by kovidgoyal** [comment]
The hotkey space is kind of crowded. I think you will need to use
kitty_mod+function key or something similar. Or maybe dont give it a
shortcut by default, there are several such actions already.
