### ISSUE TITLE
New OS window menu (macos) only works on current workspace

### ISSUE THREAD

**Issue by ggsalas** [kovidgoyal/kitty#1312]
Hi, I'm very happy with the new menu item "New OS window" but is not working if I use it on a workspace that haven't any kitty window open.

Then, if I move to a desktop that has a kitty window, works instantly. 

I have created a capture to clarify this behavior: https://drive.google.com/open?id=1vG0ON4pYhcoLxYe5Hl4BzsUF6--RVZyH

**Comment by kovidgoyal** [comment]
Since @jacwah added this feature, he is the best person to comment.

**Comment by jacwah** [comment]
The request to create a new window is processed at the next run through the main loop. The problem is that when the application is not focused it is not receiving any events, and will just wait until something happens, e.g. you change to a workspace with Kitty on and it gets a "focused" message.

**Comment by ggsalas** [comment]
Hi @jacwah, I not fully understand your message. There is not way to create a new os window when kitty is not focused?. 
I know that is not big issue, but is the expected behavior for other apps like Chrome, Safari, Finder, Terminal etc.

**Comment by jacwah** [comment]
@ggsalas The problem is fixed in my commit that was just merged. It will be included in the next version of Kitty. Thanks for reporting it!

**Comment by ggsalas** [comment]
Oh, great. Thank you!
