### ISSUE TITLE
Quickstart should include OSX kitty.conf snippet to make Kitty conform to OSX standard keyboard shortcuts

### ISSUE THREAD

**Issue by feoh** [kovidgoyal/kitty#1313]
Hi there!

Kitty is amazing. Thank you for building it!

Please consider adding the following blurb to your Quickstart, or something similar.

"
If you're on a Mac, and want Kitty to respond to standard Cmd key keyboard shortcuts, just include the following line in your kitty.conf:

kitty_mod cmd
"

I've seen a number of people discard Kitty out of hand because it doesn't conform to Mac app standards, and this is a crying shame, because it's so easy to fix for those who care!

Thanks again for building such an amazing tool! I'd generate a pull request but the Quickstart doesn't appear to be within the repo.

**Comment by kovidgoyal** [comment]
The docs are in the docs subdirectory. But a better fix is to simply add macOS aliases for common shortcuts, which is done already for a few such as copy/paste. If you want to do that, look in config_data.py

**Comment by kovidgoyal** [comment]
Search the file for is_macos to see how to do it.

**Comment by kovidgoyal** [comment]
The latter and there is already cmd+v, IIRC

**Comment by Luflosi** [comment]
I just used `kitty_mod+v` as an example, `kitty_mod+k` for example doesn't have a `cmd+k` counterpart.

**Comment by kovidgoyal** [comment]
What's cmd-k? best I can tell, it is "add a web link" https://support.apple.com/en-in/HT201236

**Comment by kovidgoyal** [comment]
the idea is to only add aliases where they correspond to well know/common macOS shortcuts
