### ISSUE TITLE
fi becomes a single character

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#1314]
when I type file in my terminal it becomes like fi le what happens is fi becomes small an tight so it can fit in a single character square and so the next square with was supposed to be for i becomes empty. but if I copy paste the text it's correct so it's just a visual issue.
I have kitty on archlinux. I don't think I had this issue ever before. also it's not only in the shell where this is happening I have the same behavior in vim too.
```
$ kitty --version
kitty 0.13.2 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
Use a font that does not have a fi ligature. Most monospace fonts are like that, use one of them.
