### ISSUE TITLE
change font size with window size

### ISSUE THREAD

**Issue by jeapostrophe** [kovidgoyal/kitty#1315]
I would like some of my kitty windows to have a consistent width in characters regardless of the size of the window, with a minimum size. I use a tiling window manager and when a window running an editor becomes full-screen, I'd like the font size to increase. (Some windows I wouldn't want this behavior, because I could use more than 80 columns, so I'd want to be able to have it be the default but turn it off dynamically.)

**Comment by kovidgoyal** [comment]
Sorry, not something I think is a good idea, having different windows with text at different sizes next to each other would just give me a headache. That said, I have no objections to having a way to toggle this behavior for windows, but it is not something I am going to spend time on.
