### ISSUE TITLE
Unable to map "cmd+period" keyboard shortcut

### ISSUE THREAD

**Issue by fallwith** [kovidgoyal/kitty#1318]
I'm using v0.13.3 on macOS 10.14 Mojave. Kitty's features and performance have convinced me to use it instead of the built-in Terminal app, and now I am in the process of bringing my keyboard shortcuts over from Terminal to Kitty.

One shortcut I am stuck on is `cmd + .` which in Terminal behaves exactly like `ctrl + c`.

I am unable to implement this functionality in Kitty for two reasons:

1. Via `kitty --debug-keyboard`, I can see that Kitty knows when I press and then release `cmd`. It does not register anything at all, however, when I hit `.` while holding down `cmd`. Only `.` appears to be affected. I can see the debugger report other combinations correctly, such as `cmd + l` or `cmd + o` or `cmd + p`.
2. Even if I could get Kitty to recognize that `cmd + .` was being inputted, I do not know how to map that combination to `ctrl + c`. Should I send `interrupt` or is there a way to have it send hex? (For hex I would need to send `\x03`.

I would appreciate any assistance with pointing me in the right direction with this matter. Thank you fort your time.

**Comment by kovidgoyal** [comment]
that will likely be because cocoa swallows the cmd+period key press for some action. it would likely need to be explicitly overridden in the keypress application filter. And the send_text action does accept hex, see its documentation in the conf file or the kitty website.

**Comment by fallwith** [comment]
Understood. Thanks for the help, @kovidgoyal.

**Comment by docwhat** [comment]
Just an FYI:

As of kitty 0.22.2 the following work...

    # \x1b is ESC (033 octal, 27 dec)
    map  cmd+.                send_text all \x1b
