### ISSUE TITLE
How to change line height on windows

### ISSUE THREAD

**Issue by stefaanv** [kovidgoyal/kitty#1322]
I'm setting up Kitty on Windows but want some more spacing between the lines to have a better overview when reading.
I managed to get Kitty to save the settings into text files in a directory structure, however the layout of the settings file is different from what is described on https://sw.kovidgoyal.net/kitty/conf.html : for instance, `font_size 11.0` is `FontHeight\10\` in my settings file.  Changing the value and reloading the session does reflect the change so I'm certain I'm changing the correct file.
However, when I insert `AdjustLineHeight\10\` into the file, nothing happens on the kitty screen.
I'm using version 0.70.0.8

**Comment by Luflosi** [comment]
You probably installed `KiTTY` from https://www.9bis.net/kitty/, which is different from `kitty`. `kitty` doesn't support windows yet. There is an unfortunate naming conflict. You'll have to check the documentation of `KiTTY`.

**Comment by stefaanv** [comment]
Bugger, my mistake.
