### ISSUE TITLE
Opening/make the window to full-screen requires a click before input is focused

### ISSUE THREAD

**Issue by MindTooth** [kovidgoyal/kitty#1324]
Started recently to use my applications in full-screen mode.  One annoyance I've noticed with `kitty` is that I need to click inside the windows/input to make it active for me to type.

When it's activated once, I can CMD+Tab switch away and return with the window accepting my input.

Believe I've experienced this for some time, but haven't though much of it since I did not use full-screen that much.  Now that I do, it's a bit annoying.

Ed1t:  I also just before posting this, enabled full-screen to be enabled by default using the cmd file in the config-dir.

## Details
OS: macOS Mojave
kitty: 0.13.3 (Installed via Homebrew Cask)
Config: https://gist.github.com/MindTooth/e6f6b41219d6a8b13b9158f23427c32a

**Comment by kovidgoyal** [comment]
I cannot replicate this on my mojave machine with an empty kitty.conf. Running kitty as:

open -a kitty.app --args --start-as=fullscreen

opens a fullscreen kitty window in which I can type straightaway.

**Comment by MindTooth** [comment]
This caused it.
```conf
# Hide the kitty window's title bar on macOS.
macos_hide_titlebar  yes
```

**Comment by kovidgoyal** [comment]
dont know what I can do about that -- seems like a bug/feature in cocoa -- titlebar less windows are assumed to not need input focus on full screening. May be possible to workaround it by explicitly calling focus after fullscreening. Does the issue also happen if you switch out of fullscreen and then back to fullscreen?

**Comment by MindTooth** [comment]
When switching between using ⌃⌘F, it do not gain focus in either state.  Even after multiple goes.

(Suddenly I've had some crashed after I disabled the option.  Properly unrelated. :smile:)

**Comment by kovidgoyal** [comment]
since full screen windows dont have titlebars in any case, seems like the workaround is to simply not hide the titlebar.

**Comment by MindTooth** [comment]
Absolutely.  At least this is now part of the issue tracker.  Let's hope people be doing a search. :smile:

Thanks@

**Comment by ujwal-setlur** [comment]
I am seeing this issue as well on Big Sur. This is my first day with kitty, and I might be missing some configuration. For example, I don't see the ``macos_hide_titlebar`` setting in the kitty.conf file.

I must say kitty is quite nice, particularly being super fast. And I can say this even being biased...I am the original author of iTerm :)

**Comment by ujwal-setlur** [comment]
This setting causes the problem:
macos_traditional_fullscreen = yes

turning it off resolves the issue, but full screen transition is a bit slower, and the text looks big during transition...

**Comment by kovidgoyal** [comment]
See #3100
