### ISSUE TITLE
Failed to set locale with LANG

### ISSUE THREAD

**Issue by Ponny035** [kovidgoyal/kitty#1325]
I have  issue when I run command in kitty desktop app something say "Failed to set locale with LANG: en_TH.UTF-8
An argument is required for the option: --config" so what should I do about this error

ps. I'm new user for linux feel free to give me explanations or documentation

**Comment by kovidgoyal** [comment]
make sure you have installed that locale in your system. A bit of googling will tell you how to do that.

**Comment by Ponny035** [comment]
Thank a lot. :)
