### ISSUE TITLE
alt key with tab1 and after startup

### ISSUE THREAD

**Issue by faustri** [kovidgoyal/kitty#1327]
I use alt+t to open kitty, if i keep holding the alt key after starting kitty and adding the key for new tab(/), it does not register as alt+/, only as /.

Also if i rapid-change between tabs with alt+number, kitty seems to unpress the alt so only numbers go through, this seems to happen only when i rapid-change from/to tab number 1, making me suspect it is a related problem.

If I have 'goto tab 1' mapped to kitty_mod+number i don't get this problem.

**Comment by kovidgoyal** [comment]
what OS/kitty version? On linux running kitty with:

 kitty -o "map=alt+1 goto_tab 1" -o "map=alt+2 goto_tab 2" -o "map=alt+3 goto_tab 3"

and changing tabs rapidly including tab 1 by holding down alt and pressing 1,2,3 works for me.

**Comment by faustri** [comment]
kitty 0.13.2 on void linux.

**Comment by faustri** [comment]
Sorry, seems to have been my k380 bluetooth keyboards fault, i thought it worked with a similar settup with urxvt, but seems not. Works on my wired keyboard. Setting issue as closed.
