### ISSUE TITLE
Use kitty automation to send Ctrl+c

### ISSUE THREAD

**Issue by dj-foxxy** [kovidgoyal/kitty#1329]
Is it possible to use kitty's automation e.g. `kitty @ --to=/path/to/socket send-text --match-tab=id:1 'Ctrl+C'`, to send SIGINT/SIGTERM/SIGKILL to the program running in the matching tab?

Thanks

**Comment by kovidgoyal** [comment]
You can send any bytes you like with send_text. Ctrl-C is \x03
But that will work only if the terminal device is in cooked mode (the
defalut mode). More robust is to get the child pic using @ ls and send
it a signal explicitly.

**Comment by bonnefoi** [comment]
You could use jq to retrieve the pid :
```
kitty @ --to=/path/to/socket ls | jq '.[0].tabs[0],windows[0].foreground_processes[0].pid'
```
then you can send the appropriate signal to this process.
