### ISSUE TITLE
Provide config option & environment variable for unix socket

### ISSUE THREAD

**Issue by SevereOverfl0w** [kovidgoyal/kitty#1330]
I'd like to ease the setup of accessing kitty from contexts without a TTY (e.g. vim).  One idea I had was to copy the neovim design for it's unix sockets, where it creates a socket pointing at a temp file, and then sets an environment variable to allow you to access that socket.

Would this be a feature Kitty could adopt in order to support this use-case?

EDIT: I found in the source code $KITTY_LISTEN_ON, so the read part of this already exists. So the convenience would be having a config option for always creating a temporary file as the listen-on address.

**Comment by kovidgoyal** [comment]
It is a command line parameter. Use kitty --listen-on, create an alias for it on linux or use the kitty facility for permanent command line parameters on macOS.see the kitty FAQ.

**Comment by SevereOverfl0w** [comment]
Alternatively, could it be possible to change the TTY which is used by the kitty command? I believe I can find the the tty file of vim using /proc/pid/$PID/fd/. Currently it appears to use terminos?

**Comment by SevereOverfl0w** [comment]
I am using a wrapper on linux, but this does not work with `new_os_window_with_cwd`, which I frequently use.

**Comment by kovidgoyal** [comment]
WHat do you mena by it doesn't work? What does new_os_window_witch_cwd
have to do with --listen-on anyway?

**Comment by SevereOverfl0w** [comment]
@kovidgoyal I have a keybinding for new_os_window_with_cwd, which I use to open new terminals in the same directory.

If I open vim in that new window, and utilize my script from vim to control it, it is unable to work because `--listen-on` was not called for that new window, and also `$KITTY_LISTEN_ON` is not set.

**Comment by kovidgoyal** [comment]
listen-on applies to the entire kitty instance and all kitty windows created in it. I cannot reproduce with running kitty as:

kitty --listen-on=@test -o "map=f1 new_os_window_with_cwd"

and pressing F1 to create a new os window. The new window has KITTY_LISTEN_ON set and working.
