### ISSUE TITLE
Window title doesn't get updated

### ISSUE THREAD

**Issue by Kistelini** [kovidgoyal/kitty#1332]
I'm using Awesome as window manager. If kitty's window is minimized the window title doesn't update.

**Comment by kovidgoyal** [comment]
Not sure what I can do about that. kitty has no control over how the
window manager draws window titles for minimized windows, when setting
the window title it call the glfw function glfwSetWindowTitle, which
IIRC on X11 changes the NET_WM_NAME and NET_WM_ICON_NAME properties.

You should contact your window manager developers and ask them why
they dont respect changes to NET_WM_NAME when windows are minimized.

**Comment by Kistelini** [comment]
Hm it works in VTE-based terminals. Will check if it has to do something with glfw.

**Comment by luisdavim** [comment]
that didn't work for me.

**Comment by Kistelini** [comment]
Thank you!
