### ISSUE TITLE
Difficulty rendering U+26a0 double-wide, or at all

### ISSUE THREAD

**Issue by vphantom** [kovidgoyal/kitty#1333]
Hello, and thank you for Kitty. :)

I suspect that my issue may not be rooted in Kitty itself, however the only bit of debugging information I have comes from it, and I'd appreciate any hints you may have.

**TL;DR:** What does the absence of `emoji_presentation` mean in Kitty 0.13.3's `--debug-font-fallback` output? Is this a broken font, or glib; possibly something I can work around in fontconfig?

How I got this far:

* I upgraded to Debian Buster to have libc 2.28-5, fontconfig 2.13, harfbuzz 2.3.0, the works.  I compiled Kitty from source (I needed one `+=` to become `=` re: clipboard).  Kitty is configured to use the  "Fira Code" font:

```conf
font_family Fira Code
font_size 12
# Weird, Stretch->Buster condensed lines quite a bit?
adjust_line_height 125%
```

* I also have installed `NotoColorEmoji.ttf` and configured Fontconfig to use it with:

```xml
<match target="scan">
	<test name="family">
		<string>Noto Color Emoji</string>
	</test>
	<edit name="scalable" mode="assign">
		<bool>true</bool>
	</edit>
</match>

<!-- Add emoji generic family -->
<alias binding="strong">
	<family>emoji</family>
	<default><family>Noto Color Emoji</family></default>
</alias>

<!-- Some fonts interfere with emoji and somehow get prioritized first -->
<selectfont>
	<rejectfont>
		<pattern><patelt name="family"><string>DejaVu Sans Mono</string></patelt></pattern>
		<pattern><patelt name="family"><string>VL Gothic</string></patelt></pattern>
		<pattern><patelt name="family"><string>DejaVu Sans</string></patelt></pattern>
		<pattern><patelt name="family"><string>FreeSerif</string></patelt></pattern>
		<pattern><patelt name="family"><string>VL PGothic</string></patelt></pattern>
		<pattern><patelt name="family"><string>Unifont</string></patelt></pattern>
	</rejectfont>
</selectfont>
```

* Fontconfig seems to fall back to the right font for emoji:

```text
$ fc-list ':charset=26a0'
/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf: Noto Color Emoji:style=Regular
$ fc-list ':charset=26a1'
/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf: Noto Color Emoji:style=Regular
```

* In Kitty 0.13.3, displaying a few emoji with `--debug-font-fallback` gives me the following:

```text
[024 14:26:25.930188] Preloaded font faces:
[024 14:26:25.930214] normal face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[024 14:26:25.930224] bold face: /usr/share/fonts/opentype/firacode/FiraCode-Bold.otf:0
[024 14:26:25.930231] italic face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[024 14:26:25.930237] bi face: /usr/share/fonts/opentype/firacode/FiraCode-Bold.otf:0
U+26a0 Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
U+26a1 emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
U+26d4 emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
```
* Kitty displays most emoji fine (about half of them do fall to Noto Color Emoji).  It used to display a monochrome, single-cell triangle for :warning: (0x26a0) and, now that I'm more aggressive with Fontconfig, I get a completely blank cell, still single-wide.

* In QTerminal, ironically it is one of the very few emoji to render in color, however the cursor is _not_ double-wide on that one as opposed to others, which causes side-effects.  So I suspect something's wrong with glibc or fontconfig or the font itself.

* I could not convince Fontconfig to use Twitter Color Emoji instead of Noto Color Emoji (even if I uninstalled the latter), so I have no means to identify whether the font is at fault.  I tried two versions of the font (official Google and Ubuntu's latest) with same results however, so I suspect glibc and/or fontconfig.

The only distinguishing trait I found so far about `0x26a0` is that Kitty doesn't say `emoji_presentation` about it.  What does that flag mean?

Thanks again, if you made it this far. :wink:

**Comment by kovidgoyal** [comment]
Emoji presentations means a glyph should be rendered two cells wide. If
you read the unicode standard you will see that various code points can
have either text or emoji presentation, and you can swap between them
using emoji variation selectors (VS15 and VS16 -- wikiedia should tell
you about them). 

Also, there is no need to struggle with fontconfig, simply use the 
symbol_map feature in kitty.conf to tell kitty to use X font for some
rangle of codepoints.

**Comment by kovidgoyal** [comment]
Just for completeness, here's what it should look like (from my Linux System)
![screenshot_20190125_084635](https://user-images.githubusercontent.com/1308621/51723088-db138080-207d-11e9-9350-346a8e4208f5.png)

**Comment by vphantom** [comment]
Thank you for the hint.  It doesn't work, but maybe we're closer. :)  I removed my Fontconfig test configuration, `fc-cache -f` and I added the following line to my configuration file:

```conf
symbol_map U+26A0 Noto Color Emoji
```

But somehow, that makes Kitty try "DejaVuSans.ttf" for symbols (instead of nothing being reported about symbols):

```txt
[025 08:13:02.610105] Symbol map faces:
[025 08:13:02.610114] /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:0
U+26a1 emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
```

It's almost as if Kitty's requesting "Noto Color Emoji" got translated into "DejaVu Sans", yet the font is clearly available and used for `U+26A1`:

```txt
$ fc-list ':family=Noto Color Emoji'
/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf: Noto Color Emoji:style=Regular
lis@titanium:~$ fc-list ':charset=26a0 26a1'
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Oblique,Oblique
/home/lis/.fonts/truetype/NotoColorEmoji-Google.ttf: Noto Color Emoji:style=Regular
[...]
```

I ran `strace` on Kitty but no mention of "Noto Color Emoji", so it must be done on the Python side.  How does Kitty end up with DejaVu Sans?  It's almost as if `symbol_map` ignored the font argument and just relied on Fontconfig's suggestion.

**Comment by kovidgoyal** [comment]
you need to use \u26a0\ufe0f bot just 26a0

**Comment by vphantom** [comment]
Thank you.  Unfortunately this does not fully solve the issue: depending on context (cursor movement maybe), I may or may not see the character immediately following that pair.  It sometimes "eats up" the following character, especially in Vim (seen above; cli below):

![kitty-ok_vim-bug](https://user-images.githubusercontent.com/3063161/51755948-d0f97e00-208d-11e9-9774-20ab0cfd34ab.png)

It also does not solve displaying existing content which I cannot edit (i.e. software output, various documents) so it's not quite ideal.  Note that the above was done _without_ any `symbol_map` configuration.  If I use `symbol_map`, then I get blank space because of the incorrect font selection.

Very puzzling.

**Comment by kovidgoyal** [comment]
That's a bug in vim. It does not support variation selectors and modern
unicode standards. If you want to display it in existing content, it
will be displayed non-color as a single cell width character. You need
to install a non-emoji font that has the character, such as symbola.

**Comment by vphantom** [comment]
Thank you for clarifying. I guess having that symbol in a Linux console will remain a dream for a few more years.

**Comment by kovidgoyal** [comment]
Not sure what you mean. That symbol is rendered correctly already, nothing is going to change in a few years. In fact there are probably terminals that incorrectly render it as an emoji even without the \ufe0f this behavior is incorrect and is what is likely to change in a few years.

**Comment by vphantom** [comment]
…because it's not in the Emoji range per se; I understand that. :)  I just mean that suffixing \ufe0f causes the following character to be "eaten up" by the combination, making the rest of the line unaligned, so I can't actually use it in a Vim gutter as I do a few other symbols. It's not the end of the world, but it's one of very few details in which I can't get my Vim setup to match my former GUI editor's look and feel. I was hoping I could fool something in the font rendering process (Fontconfig, Kitty, other) into believing it's an actual, double-wide emoji, like :no_entry: and what not which happen to be treated as such by my system.

**Comment by kovidgoyal** [comment]
I use a slightly different symbol in vim, see screenshot
![screenshot_20190126_182821](https://user-images.githubusercontent.com/1308621/51787459-49e4fc80-2198-11e9-86ae-e68510d38137.png)

**Comment by kovidgoyal** [comment]
There are a lot of unicode symbols out there :)

**Comment by kovidgoyal** [comment]
In fact if I were you what I would do is use something like Nerd font and make the symbol one of the private use area sybols from that font followed by a space. kitty will automatically use the trailing space to render the PUA symbol double wide.

**Comment by vphantom** [comment]
Indeed I'm using :no_entry: and :bell:  for now in the gutter. (:radioactive: isn't available in my setup, like :warning:, alas.)

I have my eye on Nerd Fonts, but it doesn't support merging a color font yet and I'm all set with plain Fira Code for the basics. (I thought ligatures were a gimmick until I gave them a fair try, and now I wouldn't go back.  It's kind of like syntax highlighting: you get used to it, and then it makes you slightly more efficient at glancing at code.)
