### ISSUE TITLE
inactive_text_alpha doesn't return foreground color to normal one after window focus

### ISSUE THREAD

**Issue by neyuki** [kovidgoyal/kitty#1336]
I have inactive_text_alpha lets say to 0.4

Now, if I start some ncurses app, and, before its fully started unfocus window, all will be drawn with alpha. But, after returning to that window (focus it again) text colour isn't return to a normal state.

Tested under i3wm, dunno, maybe it is wm specific?

**Comment by kovidgoyal** [comment]
I dont see how what you describe is possible. The way inactive_text_alpha works is as an overlay (basically whatever text colros the app sends are multiplied by that alpha on the GPU). When it is turned off, they are no longer multiplied, so it should not matter what app is running in the terminal, any bug would be independent of the actual colors used. Maybe it is just easier to notice in your case with a fullscreen app. But it certainly should not depend on timing of unfocusing/re-focus the window.

So if you can come up with some set of steps + a minimal kitty.conf to reproduce the issue I will be happy to take a look, closing issue till then.

**Comment by kovidgoyal** [comment]
I cannot replicate using those steps and your kitty.conf. Tried with both vim and newsboat, although I dont know how I am supposed to switch to another window fast enough, since both start up insub 100ms times on my machine.

**Comment by neyuki** [comment]
How about to try:

`sleep 2;newsboat`
