### ISSUE TITLE
Disabling active window border?

### ISSUE THREAD

**Issue by mikeroll** [kovidgoyal/kitty#1337]
I'm trying to combine these options to have only edge borders between windows + indicate the current window solely via text opacity.
```
draw_minimal_borders yes
inactive_border_color #cccccc
inactive_text_alpha 0.65
```
However I can't find a way to disable _active_ window border, which in my case is a redundant visual distraction. Setting `active_border_color` to background color does not help.
Is it possible? If not, would you accept a PR?

**Comment by kovidgoyal** [comment]
I'm afraid that isn't possible, even if you set the active window border to the same color as the background, you will still get the extra border drawn. I'm not really a fan of not drawing borders around the active window, however, I am not adamantly opposed to it either, so if you can come up with a PR (and make it toptional), I will review it.
