### ISSUE TITLE
Idea: place tab bar on left/right

### ISSUE THREAD

**Issue by kapsh** [kovidgoyal/kitty#1339]
Currently kitty allows to set `tab_bar_edge` only to `top` or `bottom`. Since most of the screens nowadays have more horizontal space than vertical it makes sense to allow placing tabs bar on left or right side and rotate tab titles text accordingly.

**Comment by kovidgoyal** [comment]
Not something I am interested in, as I tile multiple windows side by
side, but patches are welcome.

**Comment by kapsh** [comment]
Thanks for the feedback. Can you please keep this issue opened so it can catch one's attention?

**Comment by kovidgoyal** [comment]
I dont keep issues that I am not keen on having in kitty open. I will
accep t apatch for it, but it is not something I particularly want to
encourage.

**Comment by ecbaldwin** [comment]
I would like to add my voice of support for tabs shown vertically on the left. I was excited to try kitty but this is the show stopper.
