### ISSUE TITLE
Weird Font Issues

### ISSUE THREAD

**Issue by schaden-freude** [kovidgoyal/kitty#134]
I am trying to use FuraMonoForPowerline Nerd Font with the style set to Medium. I believe `font_family      FuraMonoForPowerline Nerd Font Medium` is the way to set it. Unfortunately, this borks kitty. Here is a screenshot with the same font set in kitty(left) and terminator.
![kit](https://user-images.githubusercontent.com/17528465/31053954-68b34698-a6c5-11e7-8dee-e4629510f875.png)

If I don't set it to the font to Medium it works without issues. Is there a recommended way of setting the font to Medium?

**Comment by kovidgoyal** [comment]
It depends on what is in the font files' name metadata. See the example kitty.conf for examples of setting fonts with their weights.

**Comment by kovidgoyal** [comment]
Oh and incidentally, with kitty you dont need to use fonts patched for powerline. You can use the symbol_map setting to specify a special font to use. You can then use the PowerlineSymbols font directly with that setting to render the powerline glyphs. See the example kitty.cong file.

**Comment by schaden-freude** [comment]
Could you elaborate more on setting fonts with their weights and the font file metadata? 

I looked at the config file and am still confused. There is a commented out line `# font_family SF Mono Medium`. But when I try to use the medium weight of the font I am now using by setting `font_family Iosevka Term Slab Medium`, it doesn't work at all.

I get the same garbled output on kitty, while the same font with medium weight works on other terminals like terminator, urxvt, xterm etc without any issues.

**Comment by kovidgoyal** [comment]
Do a fc-list, look at the names in that list. Use them. For example to use the Operator Mono font

```
fc-list : family | grep -i operator                                                                                                                                                                                                        
Operator Mono,Operator Mono XLight
Operator Mono,Operator Mono Light
Operator Mono,Operator Mono Bold
Operator Mono,Operator Mono Book
Operator Mono,Operator Mono Medium
```

SO you'd use

font_family Operator Mono Medium

**Comment by kovidgoyal** [comment]
And here is screenshot of what kitty looks like with the options:

```
kitty -o "font_family=Iosevka Term Slab Light" -o "bold_font=Iosevka Term Slab Medium"
```

![screenshot_20171109_063516](https://user-images.githubusercontent.com/1308621/32583189-502e51b4-c518-11e7-9704-842dc27d65c8.png)
