### ISSUE TITLE
icat kitten does not work with HTTPS image URIs

### ISSUE THREAD

**Issue by lamby** [kovidgoyal/kitty#1340]
This appears to be due to [ImageMagick's Security Policy](https://imagemagick.org/script/security-policy.php):

```
$ icat https://sw.kovidgoyal.net/kitty/_static/kitty.png
Failed to open image: https://sw.kovidgoyal.net/kitty/_static/kitty.png with error: identify-im6.q16: attempt to perform an operation not allowed by the security policy `HTTPS' @ error/delegate.c/InvokeDelegate/1726.
identify-im6.q16: unable to open file `': No such file or directory @ error/constitute.c/ReadImage/600.
```

If it helps, the underlying call is: `identify -format '%m %w %h %A' https://sw.kovidgoyal.net/kitty/_static/kitty.png`. Hopefully we can set a policy when calling-out to `identify`.

Note that HTTP (ie. not-SSL) images Just Work.

**Comment by kovidgoyal** [comment]
You could just do

curl https://whatever | icat

**Comment by lamby** [comment]
Oh sure, lots of solutions… but it's strange to half-support HTTP (!) but not HTTPS.  :)

**Comment by kovidgoyal** [comment]
well icat does not technically support any network protocols, that is an accident of imagemagick. The proper fix for this would be to identify http(s) URLs and either download them ourselves before processing, or filter them out.
