### ISSUE TITLE
Grouped windows?

### ISSUE THREAD

**Issue by tjohnston-cd** [kovidgoyal/kitty#1346]
I started using kitty recently and I'm really happy with it.

The only feature I'm missing is grouping terminals (like in terminator) - you name a group, add terminals ("windows" in kitty) to it, then type into every terminal in the group at once.

Thoughts on this? Would it be possible / of interest? (Or is there a way to do it that I've missed?)

**Comment by kovidgoyal** [comment]
Not familiar with terminator so I may not grasp all the subtleties, but if you want to send text into an arbitrary set of windows, you can do so using the remote control facility in kitty, see https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by tjohnston-cd** [comment]
Yeah, that will certainly allow me to do what I want.
Awesome! Thanks very much.
