### ISSUE TITLE
ncurses rendering issue

### ISSUE THREAD

**Issue by nagy135** [kovidgoyal/kitty#1349]
Hello,
I m having this issue with kitty when using ncurses app i wrote. The project is my effort to learn some c++ so i wrote little app that mounts my external drives ( [mounting program](https://github.com/nagy135/mounter-cli) ), but i m having this rendering issue that is present only on kitty ( so far i tested alacritty, xfce4-terminal, st ). I would take it to ncurses issues but this behaviour seems to be kitty specific.

[screenshot](https://imgur.com/a/oFn0Tvi)

I experience this issue on 2 machines, with kitty version 0.13.1.
I m pretty sure there must be solution to prevent this in my app, but while this doesnt happen in any other terminal emulator, i m hoping this has nothing to do with my code.
Any help would be appreciated.

**Comment by nagy135** [comment]
while ago i changed $TERM to xterm since it had some strange colors when ssh-ing ...after changing it back to xterm-kitty issue dissapeared. For now i m gonna solve this by making alias to change $TERM locally before running my mounter app

**Comment by kovidgoyal** [comment]
You should never change TERM, it means that ncurses programs no longer know the right escape codes to use to accomplish various tasks.

**Comment by Luflosi** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer will probably solve your ssh issue.

**Comment by nagy135** [comment]
thank you, i probably got that idea from some stackoverflow and while it worked i let it be...strangely i use a lot of ncurses apps and never had any problems, so the difference must be minimal.
Anyway, thanks for clarifying...closed

**Comment by LinArcX** [comment]
I have same problem. Is there any general solution to overcome this issue?

**Comment by nagy135** [comment]
> I have same problem. Is there any general solution to overcome this issue?

 As you might read above, only issue i had was changing $TERM variable from xterm-kitty to something else ...make sure its set to that value and you should be fine

**Comment by LinArcX** [comment]
@nagy135 it right now sets to this value:
`TERM=xterm-256color`

**Comment by nagy135** [comment]
> @nagy135 it right now sets to this value:
> 
> ```
> > printenv | grep $TERM   
> TERM=xterm-256color
> ```
> 
> But still i have same issue.

 I dont mean to disrespect you, but simply read what was already written in this thread ...it should be xterm-kitty so i m assuming you kinda have little idea of what you doing ...so just put this line in your .profile or .bashrc 
`export TERM="xterm-kitty"`

but since this is default value, you probably have line in one of these where it is set to your current value, so you should just delete that one, just make sure new terminal has value "xterm-kitty"
