### ISSUE TITLE
modifiers not applying to backspace/delete

### ISSUE THREAD

**Issue by somaulte** [kovidgoyal/kitty#1351]
Hello, using kitty-0.13.3 I am unable to map keycombos using backspace. with --debug-keyboard glfw shows that both backspace and modifier keys are working, but backspace has no mods applied.
```Press scancode: 0x40 clean_sym: Alt_L composed_sym: Alt_L mods: none glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x16 clean_sym: BackSpace composed_sym: BackSpace mods: none glfw_key: 259 (BACKSPACE) xkb_key: 65288 (BackSpace)
on_key_input: glfw key: 259 native_code: 0xff08 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release scancode: 0x16 clean_sym: BackSpace mods: none glfw_key: 259 (BACKSPACE) xkb_key: 65288 (BackSpace)
on_key_input: glfw key: 259 native_code: 0xff08 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release scancode: 0x40 clean_sym: Alt_L mods: none glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```
The same behavior applies to delete. Any ideas? 

I've also observed the same behavior with insert, home, end, page up and page down.

**Comment by kovidgoyal** [comment]
Works for me, with current kitty release:

Press scancode: 0x40 clean_sym: Alt_L composed_sym: Alt_L mods: none glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x16 clean_sym: BackSpace composed_sym: BackSpace mods: alt glfw_key: 259 (BACKSPACE) xkb_key: 65288 (BackSpace)
on_key_input: glfw key: 259 native_code: 0xff08 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
Release scancode: 0x16 clean_sym: BackSpace mods: alt glfw_key: 259 (BACKSPACE) xkb_key: 65288 (BackSpace)
on_key_input: glfw key: 259 native_code: 0xff08 action: RELEASE mods: 0x4 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release scancode: 0x40 clean_sym: Alt_L mods: alt glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: RELEASE mods: 0x4 text: '' state: 0 ignoring as keyboard mode does not allow release events

**Comment by somaulte** [comment]
Solved, was an issue with my keyboard's implementation of NKRO. Thanks for such a great terminal.
