### ISSUE TITLE
OSX Romanian Programmers keyboard not working

### ISSUE THREAD

**Issue by cvicentiu** [kovidgoyal/kitty#1353]
Hi!

I am using this keyboard layout on OS X:

https://github.com/SaltwaterC/romanian-programmers-mac

Pressing RightAlt + <key> produces different characters in certain combinations. Most important:
```
RAlt+a: ă
RAlt+q: â
RAlt+t: ț
RAlt+s: ș
RAlt+i: î
```
This works fine in iTerm2, however Kitty only works if I map these in the config:

```
map alt+a send_text all ă
map alt+q send_text all â
map alt+s send_text all ș
map alt+i send_text all î
map alt+t send_text all ț
```

Not sure if this is particularly a bug in Kitty or the Keyboard Layout, but since this works in all other terminals I've tried and only works here with this particular workaround, I classify it as a bug.

This does not happen with Kitty on Linux btw, but that uses the Romanian Programmers layout natively available from the Linux distribution.

**Comment by Luflosi** [comment]
Put `macos_option_as_alt no` in your `kitty.conf`.
