### ISSUE TITLE
Erratic resize behavior

### ISSUE THREAD

**Issue by skrat** [kovidgoyal/kitty#1357]
This is running in i3, compared to urxvt (left).

https://youtu.be/YL3zJyw1O4o

**Comment by kovidgoyal** [comment]
That is deliberate, kitty debounces resize events and only redraws when continuous resizing is done, to save CPU. So you will get flicker during resizes.

**Comment by skrat** [comment]
All I want is smooth and pleasant experience, like anyone else. This is simple change of the debounce function would make it better experience for any i3 (or any wm that supports keyboard or command resize).

**Comment by kovidgoyal** [comment]
No, that would depend on the time between steps compared to the debounce
time.

And your "smooth and pleasant experience" comes at the cost of a ton of
extra CPU consumption. The tradeoff might be worth it to you, it isn't
to me.

**Comment by Luflosi** [comment]
Since resizing is happening pretty infrequently and it is personal preference which way it should be, this could be a config option.
Another maybe better option for the particular case of tiling window managers could be the following idea: right now I think the drawing area for OpenGL is centered both vertically and horizontally within the window. While making the window taller or less tall, the top of the drawing area will shift in relation to the top of the window, which makes it look very jumpy, like this bug report describes. But if the drawing area were to be connected to the the top of the window while resizing, this might fix the problem for @skrat. This was just the rough idea and in the actual implementation we would have to handle the fact, that the window can have margins and stuff like that. Could this work? This is probably not super trivial to implement when the size of the OpenGL buffer is adjusted immediately and just the content is not, I haven't looked at the code and have no idea how this actually works.

**Comment by skrat** [comment]
@Luflosi you nailed it, that's another annoying thing in tiling wm's, that centering which appears as variable top margin

**Comment by kovidgoyal** [comment]
I dont see how a variable top margin is worse than a variable bottom margin in a tiling WM (apart from the case of resizing). The bottom margin is basically the top margin for the next window.

As for @Luflosi idea, I doubt changing the alignment will help all that much, after all, when resizing the entire contents of the window will change, and that will still be jumpy. Instead, I think what would be better is to just render a blank window, like is done on macOS (for technical reasons) until the resizing is over.

**Comment by skrat** [comment]
I really like the way rxvt does it and most other terminal emulators do it. There's no centering. It calculates the max number of rows that fit between the window size minus user defined margins and that's it. Simple.

**Comment by kovidgoyal** [comment]
Umm what's so simple? There will always be leftover margin regardless of how it is calculated, unless the window size is an exact multiple of the cell size.

**Comment by martinetd** [comment]
Actually I'm pretty sure the window can at least ask for a different size; I don't think i3 does it but urxvt+wmii always falls on an exact multiple of line counts when I resize them (e.g. wmii asks for a size, urxvt replies it prefers another, and wmii uses it then manage the margins itself)

This is useful when stacking multiple windows visible as it will let the wm optimize the sizes, e.g. with 3 urxvt open some would have 1 more line than the others if that helps use the space more efficiently.

iirc i3 doesn't do it though so /shrug, I don't care all that much.

**Comment by erf** [comment]
@kovidgoyal flickering on resize is not really an issue for me, but i'm just wondering.. i don't think people resize their terminal window that often, and thus should not really have much impact on CPU, so is it really neccessary to deboune the resize events?

**Comment by kovidgoyal** [comment]
@martinetd yeah in X11 windows can set a expected/requested size/aspect
ratio, which window managers will try to honor as best they can. i3 and
tiling window managers generally dont do it, for obvious reasons, and I
dont know if there is equivalent functionality in wayland/cocoa.

@erf: How often it happens, depends on your workflow,
and on window resize, the full screen and history buffers have to be
resized, lines re-wrapped etc. This is a whole lot of work, just for a
bit of smoothness while resizing. As I said it probably makes sense to
just render a blank window while a resize is in flight.

**Comment by martinetd** [comment]
wmii is tiling and does it, that was my point ;)
Anyway, probably not worth doing, especially if not portable. iirc for wayland the window can advertise min/max sizes in the configure request but the compositor doesn't have to respect it either, and it's not as precise (e.g. you can't say you want ax+b pixels); no clue about cocoa.

**Comment by Luflosi** [comment]
@kovidgoyal Would you accept a pull request that replaces the 0.1s constant debounce time with a config setting?

**Comment by kovidgoyal** [comment]
Not yet, I need to see if simply blanking the window during resizes
works well. Haven't had the time to look into it.

**Comment by skrat** [comment]
@kovidgoyal it obviously won't "work" as that will create a visible interruption to the user where the terminal blanks during resize. No one wants that. The desired behavior is that terminal contents stays visible during resize, every single frame, and doesn't change it's position relative to the top left corner of the window, because that's how terminals traditionally align their content, ie. to top-left corner

**Comment by Luflosi** [comment]
> No one wants that

You don't know that, I'm sure there are people that want that.
But I do agree with the rest of your comment.

**Comment by kovidgoyal** [comment]
> @kovidgoyal it obviously won't "work" as that will create a visible interruption to the user where the terminal blanks during resize. No one wants that. The desired behavior is that terminal content stays visible during resize, every single frame, and doesn't change it's position relative to the top left corner of the window, because that's how terminals traditionally align their content, ie. to top-left corner

Not going to happen.
