### ISSUE TITLE
Unsupported screen mode:  7 

### ISSUE THREAD

**Issue by herver** [kovidgoyal/kitty#1359]
**OS**: Archlinux
**Shell**: fish
**Session type**: wayland
**Kitty version**: 0.13.3
**dstat version**: 0.7.3

I switched from `Termite` to `Kitty` and so far I really like it, except for one thing: when using dstat to monitor performance of some nodes, some characters are not visible:

 * Using Termite
![image](https://user-images.githubusercontent.com/218323/52257403-02d6d400-291b-11e9-9798-06e7174c8841.png)

 * Using Kitty
![image](https://user-images.githubusercontent.com/218323/52257427-197d2b00-291b-11e9-96a4-5749178dfeae.png)

When launching kitty with some debug flags it reports this error:
```
screen_carriage_return
screen_reset_mode 7 0
[036 07:54:12.359909] [PARSE ERROR] Unsupported screen mode:  7 
```
As I'm not very familiar with terminal emulator internals, I'm not quite sure what causes this, because it works fine with other emulators.

**Comment by kovidgoyal** [comment]
dup of #135
