### ISSUE TITLE
Hack in kitty

### ISSUE THREAD

**Issue by pmatos** [kovidgoyal/kitty#1360]
I installed hack as the kitty (0.13.3) font and for some reason it seems that kitty is cutting the font at the bottom.

Config is:
```
font_family             Hack Regular
italic_font             auto
bold_font               auto
bold_italic_font        auto


# Font size
font_size               9.0
font_size_delta         1
```

When I write `git`, I am getting the following on the screen (see screenshot).
![2019-02-05-090934_86x46_scrot](https://user-images.githubusercontent.com/7911/52260256-c8beff80-2925-11e9-9f00-9c6d424c61e0.png)

**Comment by martinetd** [comment]
It's a known issue (too lazy to search issues but there are 2-3 others with the same)
workarounds are either using a bigger font or setting adjust_line_height to 1; the font is just bigger than it pretends it is and there isn't much we can do as far as I can tell.

Comparing with urxvt at font 9 it feels as if urxvt automatically has adjust font height/width set to 1, so you're not really losing by setting it.

**Comment by pmatos** [comment]
Yes, makes sense. Making the font size 10 works. Thanks
