### ISSUE TITLE
Copying tabbed output copies spaces instead

### ISSUE THREAD

**Issue by Tyilo** [kovidgoyal/kitty#1361]
See following test:

```
$ printf '\ta\n' | xclip -i
$ xclip -o | xxd
00000000: 0961 0a                                  .a.                                  .
$ # Now copy the output in kitty instead
$ printf '\t\n'
        a
$ xclip -o | xxd
00000000: 2020 2020 2020 2020 61                           a
```

**Comment by kovidgoyal** [comment]
See https://unix.stackexchange.com/questions/324676/output-tab-character-on-terminal-window

Basically, tabs are not printable characters, instead they move the
terminal cursor, they are control characters.

kitty could try to implement a hack to try to round trip tabs through
selection/copying, like VTE does, but personally, I'm not in favor of
such hacks. They are fragile and add overhead.

And given that I long ago decided in favor of spaces over tabs, my
motivation for this is not very high either :)

**Comment by kovidgoyal** [comment]
Oh and just for giggles, here is an easier way to demonstrate thecontrol-characterness of TAB in terminals: https://stackoverflow.com/questions/1627100/can-one-highlight-tab-characters-in-the-terminal
