### ISSUE TITLE
Single process kitty partially stops working after memory exhaustion

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#1363]
I experienced an issue now where new terminals launched with `kitty -1` doesn't open properly. I'm only getting a blank window, and the shell never shows. Existing terminals mostly works, but opening the hints kitten or show_scrollback doesn't do anything.

I launched the initial kitty process from my window manager, so I don't have it's output easily available. However, I tried looking at `/dev/vcs1` and see this:

```
OSError: [Errno 12] Cannot allocate memory"/usr/bin/../lib/kitty/kitty/child.py", line 180, in fork    pid = fast_data_types.spawn(exe, self.cwd, tuple(argv), env, master, slave, stdin_read_fd, stdin_write_fd, ready_read_fd, ready_write_fd)
```

I'm not sure, but it seems that this happened once while I ran out of memory, and after some memory was freed, the issues described above still occurs. I currently have 2 GB free memory.

Launching a new kitty process without `-1` works fine without issues.

**Comment by kovidgoyal** [comment]
I dont really see what I can do about that. That error is a failure of
malloc to allocate memory. No reasonably complex program can survive
that kind of failure. I suggest you enable some swap on your system, so
that if it happens in the future, all it will cause is your system will
become slow and you can fre up the memory and proceed.
