### ISSUE TITLE
Disable new tab on a per-session basis

### ISSUE THREAD

**Issue by cweagans** [kovidgoyal/kitty#1364]
Hi! I'm using a kitty session and a .desktop file to launch mutt in a kitty session of its own. I was wondering if there was a way that I can (in my session file) disable creating new tabs/splits/whatever and force that window to be single purpose. Is that possible right now?

**Comment by kovidgoyal** [comment]
Simply unmap the shortcuts for it in your desktop file, something like

kitty -o "map=ctrl+shift+t no-op"

**Comment by cweagans** [comment]
So easy! Love it! Thanks :)
