### ISSUE TITLE
Repeatedly opens using recommended user script

### ISSUE THREAD

**Issue by 0xADB** [kovidgoyal/kitty#1365]
OS : Debian 9 (4.19.0-0.bpo.1-amd64)
Installation: 
- harfbuzz - from source to `/opt/harfbuzz` prefix
- kitty - from source with exporting `PKG_CONFIG_PATH=/opt/harfbuzz/lib/pkgconfig:$PKG_CONFIG_PATH`

Run: added two scripts
`~/bin/kitty.py` (following [instructions](https://sw.kovidgoyal.net/kitty/build.html)):
```
#!/usr/bin/env python3
import runpy
runpy.run_path('/home/beregovoy/src/kitty/kitty', run_name='__main__')
```
and `~/bin/kitty` (since I have to provide harfbuzz library path):
```
#!/usr/bin/env bash
export LD_LIBRARY_PATH=/opt/harfbuzz/lib
~/bin/kitty.py
```
- running `kitty` from another console got `kitty` opening over and over again
- renaming `~/bin/kitty` to `~/bin/kitty.run` fixes the issue

**Comment by kovidgoyal** [comment]
That's not the recommended user script that's the recommended user
script + extras you added. If you need to set an env var before running
kitty, use this:

```sh
#!/bin/sh

export VAR=VAL
python3 /path/to/kitty/dir
```
