### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jthemphill** [kovidgoyal/kitty#1366]
It looks like we tried accessing memory address `0x158`, which was probably supposed to be an integer. I've reported the segfault to Apple, but I don't actually know if Apple sends those reports to developers. [This is the text of the report](https://github.com/kovidgoyal/kitty/files/2842144/kitty-dump.txt).

**Comment by kovidgoyal** [comment]
update kitty, glfwContentScale was re-writtena  while ago.
