### ISSUE TITLE
tput color changes are lost in some circumstances

### ISSUE THREAD

**Issue by emmanueltouzery** [kovidgoyal/kitty#1367]
So this is a very specific issue, and about which I really don't know much so I'm not sure how to give more information, and which may not even be a bug.

I have a custom terminal theme (I'm using [powerlevel-9k](https://github.com/bhilburn/powerlevel9k)). To make it look more pleasing, I tuned the terminal colors, but I did that through `tput` commands in my `.zshrc`:

```
tput initc 0 172 196 200
tput initc 1 800 210 100
tput initc 2 220 560 220
tput initc 3 800 460 180
tput initc 4 350 530 670
tput initc 5 630 380 470
tput initc 6 470 710 760
tput initc 7 810 810 810
tput initc 8 570 570 570
tput initc 9 1000 280 200
tput initc 10 720 710 0
tput initc 11 1000 780 430
tput initc 12 530 760 1000
tput initc 13 820 820 1000
tput initc 14 440 760 830
tput initc 15 910 910 910
```
I have no issues with that setup with `gnome-terminal`, but an issue which I noticed since migrating to `kitty` is that I am loosing these customizations if I run typescript's compiler `tsc` in watch mode (`tsc -w`) and exit it through `ctrl-c`. When returning to the shell after that, the colors are the original ones, as if the `tput` commands were never executed.

If I try to guess what's going on, the typescript compiler presumably repeatedly prints the backspace character `\b` to reset its output when it recompiles, and I suspect it may be printing too many `\b` characters, voiding the `tput` special commands which were executed beforehand? But I have no idea really. I tried reproducing the issue by running `watch -n 1 ls -lh`, touching files and hitting `ctrl-c`, but I could not reproduce the issue.

Now, I can say that `gnome-terminal` does not exhibit the issue => the colors customizations remain if applying the same test. However `xterm` behaves the same as `kitty`, so `kitty` may be handling the situation correctly?

**Comment by egmontkob** [comment]
(gnome-terminal developer chiming in)

> However `xterm` behaves the same as `kitty`, so `kitty` may be handling the situation correctly?

Yup, apparently it's a gnome-terminal (vte) bug, then. Could you please file it at https://gitlab.gnome.org/GNOME/vte/issues ? Also, arguably tsc shouldn't do whatever it does that resets the colors, which we'll investigate in the vte bugreport, and then you might ask tsc not to do it.

> I suspect it may be printing too many `\b` characters, voiding the `tput` special commands

No, that's not how terminal emulation works. Once a control instruction is executed, the instruction itself is forgotten, only its result lives on. There's no way to backspace over it.

**Comment by kovidgoyal** [comment]
It's likely that tsc is using some kind of reset command to reset the
colors, likely accidentally. You can use the --dump-commands switch to
kitty to see the command if you want. I highly doubt this is a kitty
issue, likely tsc is just output something that vte ignores, but if the
investigation in vte concoludes otherwise, let me know and I will take a
look.
