### ISSUE TITLE
Support drag and drop for text

### ISSUE THREAD

**Issue by skurfer** [kovidgoyal/kitty#1368]
I select and drag text to and from Terminal windows all the time. kitty doesn’t seem to allow dragging text either direction.

Thanks.

**Comment by kovidgoyal** [comment]
Not something I am interested in. You can simply select the text and paste it, either using a middle click if you are on X11 or your clipboard aste shortcut otherwise. You can use the copy_on_select option in kitty.conf to make this faster.

**Comment by skurfer** [comment]
> Not something I am interested in.

OK, but it’s standard behavior across most apps and it’s a nice way to move text around without destroying what you had in the clipboard.

**Comment by Luflosi** [comment]
I imaging drag and drop of text into kitty would be very similar to the code for dragging a file into kitty on macOS.

**Comment by neuton** [comment]
> Not something I am interested in.
This does not seem like a fair justification for closing the feature request issue.
If you do not feel like implementing the feature is worth your time and effort, someone else may, right?

**Comment by kovidgoyal** [comment]
And they are welcome to, just because an issue is closed does not mean
people are unable to send a PR. I dont keep issues open for things I
dont think are a good idea.

**Comment by Luflosi** [comment]
@skurfer and @neuton I implemented dragging and dropping of text into kitty.
