### ISSUE TITLE
Support SSH URLs

### ISSUE THREAD

**Issue by skurfer** [kovidgoyal/kitty#1369]
It should be possible to tell your OS to open ssh://xyz with kitty. The result would be a new kitty window connected to host xyz.

I know that on macOS, adding this to the `Info.plist` generating code in `setup.py` will at least tell the OS that the app supports SSH:

```python
CFBundleURLTypes=[
    {
        'CFBundleURLName': 'ssh URL',
        'CFBundleURLSchemes': ['ssh'],
    }
],
```

But of course that’s a lie until we can also add code to handle opening the SSH URLs.

I’m using macOS personally, but I imagine other OSes have similar URL handling abilities.

Thanks.

**Comment by kovidgoyal** [comment]
just create a wrapper script, like this,

```sh
#!/bin/sh

kitty ssh $1
```

kitty is not going to support SSH urls directly, since its command line already is used for running commands, including ssh, if needed.

**Comment by skurfer** [comment]
The `ssh` command isn’t the only way to start an SSH session. In fact, I almost never do it that way. Other common ways to start SSH:

  * A [launcher](https://qsapp.com/) could [index](
https://github.com/quicksilver/RemoteHosts-qsplugin) the hosts you commonly access
  * Internal documentation at your organization could provide one-click access to the appropriate system

Both of those rely on support for SSH URLs.

And there’s no way to tell the system that a shell script is responsible for these URLs, so I’m not sure what you’re getting at there.

**Comment by kovidgoyal** [comment]
I'm not a mac user, but I'm pretty sure there will be a way of telling
the system that any program is responsible for any URL. Hell if there
isn't you can simply create a dummy app around the shell script to do
it. A bit of googling will tell you how.
