### ISSUE TITLE
Does kitty support osc handlers?

### ISSUE THREAD

**Issue by amosbird** [kovidgoyal/kitty#137]
Hi, this terminal emulator looks promising. I wonder if it has following features,

1. osc handler support
    This is the main reason I'm stuck in urxvt. I use it to copy text and open remote files.
2. url hinting
    https://bitbucket.org/sterlingcamden/urlpicker
3. auto completion
    https://github.com/Vifon/autocomplete-ALL-the-things

regards,
Amos

**Comment by kovidgoyal** [comment]
Mouse over URLs will highlight them and you can click to open them. Not sure what OSC has to do with copy text, you simply select the text you want to copy with the mouse and copy it. As for auto-complete, no, I dont see much point to having autocomplete at the terminal level. Makes far more sense to implement it at the application level.

**Comment by dkasak** [comment]
@kovidgoyal I'm also interested in using kitty, but I need keyboard-driven control, specifically URL selection/opening/copying using the keyboard and the same for arbitrary pieces of text in the buffer (something like visual selection in vim). Are you specifically against these features or you don't want to implement them yourself but would accept PRs?

**Comment by kovidgoyal** [comment]
You know that you can open the kitty buffer + history in any program of your choice with a keypress (ctrl+shift+h by default which opens it in less)? Once you do that you can select/copy/open URLS using whatever you like. For example I use urlscanner, but you use whatever you like.

**Comment by kovidgoyal** [comment]
So for example, if you have some command line program that scans text for urls and allows you to select them, like mailscanner, you just define the kitty shortcut, 

map ctrl+shift+x      new_window @text my_program

Then pressing ctrl+shift+x will open my_program in a new kitty window.

**Comment by dkasak** [comment]
That's actually a very interesting feature. I missed that kitty supports sending the buffer's contents to other programs. I'll try to configure a setup using this, thanks.

**Comment by kovidgoyal** [comment]
Yeah it's nice because you dont have to shoehorn all features into the terminal emulator, instead you can use programs with a dedicated UI for the task at hand. I use it mostly for browsing the history buffer, but it can equally well be used for picking URLs or saving/editing the session or ...
