### ISSUE TITLE
Cursor lags in full-screen mode or in window without title bar

### ISSUE THREAD

**Issue by equaeghe** [kovidgoyal/kitty#1370]
[Kitty 0.13.3 under X/Kwin/Plasma 5]

When I use Kitty in full-screen mode or in a window with the title bar hidden, the cursor lags. Meaning that, e.g., if I backspace over typed text, it sometimes take a visible amount of time for the cursor to move or sometimes the cursor skips a position. The moment I go out of full-screen mode or bring back the title bar, the issue disappears.

**Comment by kovidgoyal** [comment]
I cannot replicate this on my system (albeit using a different window manager under X11). Since no rendering code in kitty itself depends on whether the title bar is hidden or the window is full screen or not, I think this issue is lower down in the graphics stack on your system.
