### ISSUE TITLE
Mouse selection broken when SSHed into a tmux session from Linux

### ISSUE THREAD

**Issue by sssilver** [kovidgoyal/kitty#1371]
On Ubuntu 18.04 with the latest Kitty, I am experiencing this bizarre bug where mouse selection works fine when I'm on my local shell, but whenever I mosh to my remote server (where I run tmux), mouse selection (when holding shift) starts acting up. 

It will randomly (and very quickly) deselect the selection, or randomly change the selection to include a large area of text outside of anything I intended to select.

Again, this only happens when both of these are true:
1. Running Kitty on Linux (doesn't happen on macOS, which I find to be quite bizarre)
2. Attached to a tmux session on the remote (doesn't happen when the remote is detached from tmux; doesn't happen when attached to tmux locally)

The behavior also existed as early as Kitty 0.9.0.

**Comment by kovidgoyal** [comment]
From your description you likely have a clock or similar in your tmux
status bar, anything that causes changes to the screen can mess with the
current mouse selection, although this effect has been mitigated in
newer kitty releases.
