### ISSUE TITLE
Support for mono fonts with no registered spacing information

### ISSUE THREAD

**Issue by reaysawa** [kovidgoyal/kitty#1372]
I've had this roadblock upon trying Kitty for the first time, where my favorite fonts would not load despite them being monospaced (yes, I also visited https://github.com/kovidgoyal/kitty/issues/1344; that's how I found out about it in the first place).

Some fonts don't come with spacing information encoded in the metadata (e.g. [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts), random fonts downloaded from the internet), which makes them undetectable by [fontconfig.py list_fonts()](https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts/fontconfig.py#L38).

Built-in system mono font with correct metadata:

>         'mathjax_vector': [{
>             'path': '/usr/share/fonts/opentype/mathjax/MathJax_Vector-Regular.otf',
>             'family': 'MathJax_Vector',
>             'style': 'Regular',
>             'full_name': 'MathJax_Vector-Regular',
>             'postscript_name': 'MathJax_Vector-Regular',
>             'weight': 100,
>             'slant': 0,
>             'index': 0,
>             'scalable': True,
>             'outline': True,
>             'color': False,
>             'spacing': 'MONO'
>         }],

Nerd Font with incomplete metadata - **missing 'spacing': 'MONO'**:

>         'furamono nerd font mono': [{
>             'path': '/home/user/.fonts/FiraMono/Medium/complete/Fura Mono Medium Nerd Font Complete Mono.otf',
>             'family': 'FuraMono Nerd Font Mono',
>             'style': 'Medium',
>             'full_name': 'Fura Mono Medium Nerd Font Complete Mono',
>             'postscript_name': 'FuraMonoNerdFontCompleteM-Medium',
>             'weight': 100,
>             'slant': 0,
>             'index': 0,
>             'scalable': True,
>             'outline': True,
>             'color': False
>         }

---

My question is, since this is difficult to change unless generating a new font with the correct metadata, would you consider a more flexible approach?

```
def list_fonts():
    is_mono = re.compile('Mono')
    for fd in fc_list(False):
        fn = (fd.get('family', '') + ' ' + fd.get('style', '')).strip() or fd.get('full_name')
        if fn:
            is_mono = is_mono.search(fn)
            yield {'family': fd.get('family'), 'full_name': fn, 'is_monospace': is_mono}
```

**Comment by reaysawa** [comment]
I've opened https://github.com/ryanoasis/nerd-fonts/issues/323, but still suggested the workaround here anyway because it might also happen in some other cases. It's very understandable if you don't agree with the suggestion. :+1:

**Comment by kovidgoyal** [comment]
I'm afraid not. Non-monospace fonts render very poorly in kitty's cell
based rendering system, which is why I filter them out in the first
place.
