### ISSUE TITLE
Bug with ↵ and zsh right prompt

### ISSUE THREAD

**Issue by juanibiapina** [kovidgoyal/kitty#1373]
This character: https://www.fileformat.info/info/unicode/char/21b5/index.htm

With this zsh config:
```
PROMPT='123'
RPROMPT='↵'
```

The prompt cursor is rendered on top of the number `2`. This works correctly on iterm.

**Comment by kovidgoyal** [comment]
![screenshot_20190210_212205](https://user-images.githubusercontent.com/1308621/52535908-05518780-2d7a-11e9-8b0d-daab41f01726.png)

works for me with up-to-date kitty and zsh

**Comment by juanibiapina** [comment]
I have the same configuration.

**Comment by kovidgoyal** [comment]
then it is likely that zsh uses the system wcwidth() which returns an incorrect value on your system. kitty uses a wcwidthh() implementation based on the latest unicode standard. macOS is notorious for out of date software so I wouldn't be surprised if wcwidth() is old/broken there.

**Comment by Luflosi** [comment]
![screenshot](https://user-images.githubusercontent.com/15217907/52536331-61f07a80-2d59-11e9-9757-fa60194392a1.png)
Works for me too on macOS.

**Comment by juanibiapina** [comment]
This thing has too many issues with unicode and fonts. This, plus https://github.com/kovidgoyal/kitty/issues/799 makes it unusable for me :(

**Comment by juanibiapina** [comment]
Nevermind, it's actually now broken on iterm as well. I must have updated something else which broke it.

**Comment by juanibiapina** [comment]
This issue is fixed by correctly setting the locale. The trick is that iterm and terminal.app will automatically partially set it, which fixes some cases but not others. Most of the time you need 3 configurations:

```
export LC_ALL=en_US.UTF-8                                                                                          
export LANG=en_US.UTF-8                                                                                            
export LC_CTYPE=UTF-8
```
