### ISSUE TITLE
Unable to send escape sequence to change cursor style with send_text

### ISSUE THREAD

**Issue by reaysawa** [kovidgoyal/kitty#1374]
**OS: Ubuntu 18.04 x64**

Having read through

https://github.com/kovidgoyal/kitty/blob/c02fa79591008740b0d5f7bf90dce2c073566482/kitty_tests/parser.py#L170

https://github.com/kovidgoyal/kitty/issues/747#issuecomment-412658543

https://github.com/kovidgoyal/kitty/issues/715#issue-339880660

I've tried a lot of combinations but none actually solves the problem. I don't see kitty complaining about invalid escape sequences so I assume they are being recognized correctly.

The two below **do not** work:

`map escape combine : send_text <ESC>[?2 q : send_text normal,application \x1b`

or

`map escape combine : cursor_mode block : send_text normal,application \x1b`

What I want to do is: upon pressing escape, I want to change the cursor style and send a normal Escape key press to the terminal.

**Comment by kovidgoyal** [comment]
your first command has an incorrect send_text invocation, you forgot to specify the modes. Your second invocation will do nothing, as there is no action named "cursor_mode". You need something like:

```
map escape send_text \x1b[?2 q\x1b
```

**Comment by reaysawa** [comment]
@kovidgoyal Thanks for the quick response.

I've changed to the code you provided but it still does nothing at all. Does it work for you?

**Comment by kovidgoyal** [comment]
Sorry forgot the modes

```
map escape send_text normal,application \x1b[?2 q\x1b
```

**Comment by reaysawa** [comment]
My bad, the command was incorrect.

It should be `map escape send_text normal,application \x9b02 q\x9c\x1b`.

Useful page: https://en.wikipedia.org/wiki/ANSI_escape_code#Escape_sequences

Thanks for the help!
