### ISSUE TITLE
Can't get the config to work

### ISSUE THREAD

**Issue by magicalbanana** [kovidgoyal/kitty#1375]
I can't seem to get the config to work. I have set up the env var for the kitty config location and still nothing.

Here's my config:

```
# vim:fileencoding=utf-8:ft=conf

# Font family. You can also specify different fonts for the
# bold/italic/bold-italic variants. By default they are derived automatically,
# by the OSes font system. Setting them manually is useful for font families
# that have many weight variants like Book, Medium, Thick, etc. For example:
# font_family Operator Mono Book
# bold_font Operator Mono Thick
# bold_italic_font Operator Mono Medium
# font_family      Input Mono
font_family      mononoki Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto

# Font size (in pts)
font_size        50.0

# The amount the font size is changed by (in pts) when increasing/decreasing
# the font size in a running terminal.
font_size_delta 1

# colorscheme to be used
include dracula.conf
```

**Comment by kovidgoyal** [comment]
Press ctrl+shift+f2 and edit the config file that will open and you will be fine.

**Comment by magicalbanana** [comment]
@kovidgoyal not ideal for me since I have dotfiles that I use for each machine I work on. I found a way though and that's to create an AppleScript that opens kitty while pointing to the config.

```
do shell script "open -a /Applications/kitty.app/Contents/MacOS/kitty --args -c ~/.config/kitty/kitty.conf"
```

**Comment by Luflosi** [comment]
Could you see if there is a file `~/Library/Preferences/kitty/kitty.conf`? If there is, remove that file and directory. I use macOS too, don't have that directory and kitty uses `~/.config/kitty/kitty.conf` without a problem.

**Comment by kovidgoyal** [comment]
@magicalbanana not sure what you mean, the process I described simply edits the kitty dot file. The difference being that it will open the right one for you automatically.

**Comment by magicalbanana** [comment]
@kovidgoyal I did but it wouldn't apply the changes. But like I said, I just created an AppleScript and works fine now. I am guessing the Kitty app on MacOS is not looking at the right directory?

**Comment by Luflosi** [comment]
@magicalbanana Did you try my suggestion? Does it help?

**Comment by magicalbanana** [comment]
@Luflosi there was no file there at all. I tried to symlink it though but still didn't work. The one sure way I found was to create an AppleScript which isn't so bad since I bound it to a keyboard shortcut.

**Comment by Luflosi** [comment]
Hmm, I wonder why it doesn't work then. The workaround with the AppleScript is less than ideal.
`kitty --debug-config` prints where the config file was loaded from, maybe that helps in some way.

**Comment by magicalbanana** [comment]
@Luflosi yeah. The problem is, when installing `kitty` using the `dmg`, it doesn't come with a CLI executable so I can't run it like that. Although, the `AS` would be able to do that. I just never really bothered to do so.

**Comment by Luflosi** [comment]
Kitty adds itself to the path so you can start kitty and then execute the command from inside kitty.

**Comment by magicalbanana** [comment]
This is weird,

```
╰─$ /Applications/kitty.app/Contents/MacOS/kitty --debug-config
kitty 0.13.3 created by Kovid Goyal
Darwin Kareems-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:        10.14.3 BuildVersion:   18D109
Loaded config files: /Users/khepburn/.config/kitty/kitty.conf

Config options different from defaults:
background  Color(red=40, green=42, blue=54)
color1      Color(red=255, green=85, blue=85)
color10     Color(red=90, green=247, blue=142)
color11     Color(red=244, green=249, blue=157)
color12     Color(red=202, green=169, blue=250)
color13     Color(red=255, green=146, blue=208)
color14     Color(red=154, green=237, blue=254)
color15     Color(red=230, green=230, blue=230)
color2      Color(red=80, green=250, blue=123)
color3      Color(red=241, green=250, blue=140)
color4      Color(red=189, green=147, blue=249)
color5      Color(red=255, green=121, blue=198)
color6      Color(red=139, green=233, blue=253)
color7      Color(red=191, green=191, blue=191)
color8      Color(red=77, green=77, blue=77)
color9      Color(red=255, green=110, blue=103)
font_family mononoki Nerd Font
font_size   11.6
foreground  Color(red=248, green=248, blue=242)
```

But prior to using the `AS` I couldn't get the config to work.

**Comment by magicalbanana** [comment]
I think I know what's going on and maybe a bit harder to debug. When running kitty through the CLI, it respects the config directory. But if running it directly through `Applications` as an app, it doesn't. That's what I'm guessing is happening.

**Comment by Luflosi** [comment]
I'll wait to see what @kovidgoyal has to say, maybe he knows what's happening.

**Comment by kovidgoyal** [comment]
I dont see how that's possible, but you can override where kitty loads
its config from via an environment variable, see kitty --help for
details, and remember to set the env var systemwide.

**Comment by Luflosi** [comment]
@magicalbanana Can you try setting the following option in your `kitty.conf`
`shell bash -c 'kitty --debug-config; read'`
and restart kitty?
This should execute `kitty --debug-config` differently than from the cli, although I can't imagine it having any effect. I had to use bash as just using `shell kitty --debug-config` will just briefly flash the output with not enough time to read it and I couldn't think of another way to accomplish this.
You may not be able to use kitty to edit your config file back, so be prepared to use another terminal emulator for that.

**Comment by robalaban** [comment]
Ran into the same problem. Launching Kitty from the Application folder will not load the correct config even after setting the `KITTY_CONFIG_DIRECTORY` env variable. 

I have all the my config files under .dotfile directory so I had to create a symlink. 

My config in `.zshrc`:

```sh
export KITTY_CONFIG_DIRECTORY="/Users/{$USER}/.dotfiles/kitty"
```

Symlink: `ln -s ~/.dotfiles/kitty/kitty.conf ~/.config/kitty/kitty.conf` now the proper config file loads when launching kitty from Application folder. 

Hope it helps!

**Comment by kovidgoyal** [comment]
You cant set environment variables in your shell rc files, the shell
runs AFTER the terminal emulator. You need to set them in launch
services.

**Comment by elthariel** [comment]
`launchctl setenv KITTY_CONFIG_DIRECTORY$HOME/.config/kitty/`

**Comment by dcow** [comment]
So where does `kitty` load it's default config from on macOS when launched from the finder/spotlight/applications folder (not command line `kitty`)?

**Comment by chamilad** [comment]
Sorry if this is adding to the noise, but if you're not seeing the changes you made to `~/.config/kitty/kitty.conf` even after closing the app, it's probably because you didn't **stop** the app like @elthariel  mentions above (dock -> right click -> quit). MacOS and it's assumptions of what a user needs is a headache.

**Comment by camsteffen** [comment]
Fixed for me by logging out and back in to macos. I don't think the env variable is necessary.

**Comment by mikinis111** [comment]
I have the same problem with linux mint, but since you are using MacOS specific commands I'm a bit confused. `kitty --debug-config` says these are locations of my config files: 
```
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/mikinis/.config/kitty/kitty.conf
```
Even after removing .conf file in /etc/ still nothing happens. It says:
```
update_check_interval 0
```
Tried to change value to 1 but nothing happened.

**Comment by neumachen** [comment]
@mikinis111 keep in mind that running the command in your terminal might not be the same as the App launcher. Try running kitty by referencing the bin file in the Application directory and you might see where it's pulling the config.

**Comment by RaananHadar** [comment]
So this does appear to be a bug in the default config in osx, as many people will use .dmg files I would fix this if possible.

**Comment by espbee** [comment]
@neumachen is right, it all depends on whether you run via terminal (type kitty in terminal, or in kitty) or as an app (apple-space, type kitty in the search bar).

**Comment by huyz** [comment]
Relatedly, when I go to `kitty > Settings…`, a window flashes and immediately closes if kitty was launched as a GUI app (either as a login item, or from the Dock, or from Spotlight, or from BetterTouchTool).  But the config file does appear in my editor if kitty is launched from the CLI.
Weird.
