### ISSUE TITLE
How to get glew >= 2 on Ubuntu 16?

### ISSUE THREAD

**Issue by exebook** [kovidgoyal/kitty#138]
Kitty requires glew 2+, but Ubuntu 16.04 only has libglew1.6-dev in repository, any hint how to get the lib requiredto build kitty?
Should I uninstall libglew1.13 installed by default as well?

**Comment by kovidgoyal** [comment]
No idea, I dont use debian/Ubuntu. In gneral, simply build it from source and install. Or there might be a PPA somewhere you can use.

**Comment by dansdantas** [comment]
@exebook Have you had any success installing glew >= 2?

**Comment by kovidgoyal** [comment]
kitty master no longer needs glew.
