### ISSUE TITLE
Unicode_input hotkeys

### ISSUE THREAD

**Issue by mvrozanti** [kovidgoyal/kitty#1385]
![image](https://user-images.githubusercontent.com/11381662/52857249-bc008f80-310d-11e9-943c-bf4fd73fe512.png)

Hi there

I didn't find how to access these hotkeys on unicode_input kitten
The python script doesn't seem to be waiting for key events other than directional movement and tab/s-tab:

https://github.com/kovidgoyal/kitty/blob/0833697c49b3a7f635b3aa91d4928596c601d434/kittens/unicode_input/main.py#L393-L431

**Comment by kovidgoyal** [comment]
Type a space and then .0

**Comment by mvrozanti** [comment]
![image](https://user-images.githubusercontent.com/11381662/52872420-9edeb780-3133-11e9-83dc-4ed9f67f0d39.png)

I don't get it. If I'm typing the name of the character and hit space and .0 I just insert a space and the rest of the characters on emoji search box.
