### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#139]
Just curious about how often you release binaries, since I've been running into issues where custom keymaps 
on macOS break because they require the application to be in the standard app bundle.

**Comment by kovidgoyal** [comment]
There is no particular schedule. I make releases whenever I deem the time "suitable". For instance, right now, once the code for #33 has had a chance to settle and be tested a bit by users, that is when the next release will be made.

**Comment by Alok** [comment]
Understood. If we want to make our own "release" (which seems to consist of adding an `Info.plist` and a copy of python 3), is there a script to do so?

**Comment by kovidgoyal** [comment]
There is no script. You can use the kitty branch of https://github.com/kovidgoyal/build-calibre to do it, but that's a lot of works to setup. Much easier to just replace the bits you want replaced in an existing app bundle.

**Comment by Alok** [comment]
I think I'll just wait for a new release in that case. I couldn't get the bundle built by `python3 setup.py osx-bundle` to work.
