### ISSUE TITLE
Is remote control working?

### ISSUE THREAD

**Issue by Donkeyfish87** [kovidgoyal/kitty#1391]
Akin to the tutorial, I just tried from an Iterm window to open Kitty with the "listen-to" option. But when I then tried to control it from iTerm it threw an error, time out while waiting to read cmd response

https://www.dropbox.com/s/kurs2kch191qqps/Screenshot%202019-02-17%2018.08.59.png?dl=0

**Comment by kovidgoyal** [comment]
yes it is working. If you want to control kitty from a program not
running within kitty you will need to setup a socket, see the
--listen-on command line option.

**Comment by Luflosi** [comment]
It might be good to change the error message to be more helpful.

**Comment by kovidgoyal** [comment]
To what? All the client code knows is that the response has timed out. It cant know it is not running inside kitty, since there is no reliable way to detect terminals, short of querying them, which is rather too much work.

**Comment by kovidgoyal** [comment]
Well, I suppose I could add a note about running commands within kitty
to the timeout error.

**Comment by simurgh9** [comment]
> If you want to control kitty from a program not
> running within kitty you will need to setup a socket, see the
> --listen-on command line option.

This should be documented here,

https://sw.kovidgoyal.net/kitty/remote-control/

**Comment by kovidgoyal** [comment]
It is https://sw.kovidgoyal.net/kitty/remote-control/#remote-control-via-a-socket

**Comment by kovidgoyal** [comment]
,,,

**Comment by simurgh9** [comment]
That does talk about the socket setup but does not say that having a socket is a requirement to control (launch another Kitty tab from, e. g., Emacs) Kitty from a program not running within Kitty.

**Comment by kovidgoyal** [comment]
How else would you control kitty from outside kitty? There must be some channel over which to communicate with the program you are trying to control. If you are running inside kitty you can use the tty itself, if you are outside kitty it *must* be a socket or similar IPC mechanism.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/5004cf2dbf8fe741a917efaf2110b6e4bf21daac
