### ISSUE TITLE
Malformed config options can crash kitty

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1394]
kitty does not properly check the config options in all cases. Should malformed config options print an error message and ignore the option instead of crashing kitty?
`adjust_column_width -100%` for example will result in
```
[049 23:41:38.811736] [glfw error 65540]: Invalid window size -639x393
[049 23:41:38.826235] Traceback (most recent call last):
  File "/path/to/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/main.py", line 277, in main
    _main()
  File "/path/to/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/main.py", line 270, in _main
    run_app(opts, args)
  File "/path/to/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/main.py", line 146, in run_app
    _run_app(opts, args)
  File "/path/to/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/main.py", line 132, in _run_app
    args.cls or appname, load_all_shaders)
ValueError: Failed to create GLFWwindow
```
for me. I found some other examples of crashes due to weird config options while reading the code.

**Comment by Luflosi** [comment]
Here are a few more crashes (basically negative and positive absolute and percent values for two config options):
`adjust_column_width -10` (with a value smaller than the column width) results in `Invalid window size -159x393`
`adjust_column_width 1000` and `adjust_column_width 10000%` result in `Too many pre-rendered sprites for your GPU or the font size is too large`
`adjust_line_height -1%` results in `Line height too small after adjustment`
`adjust_line_height -100` (with a value smaller than the line height) results in `Line height too small after adjustment`
`adjust_line_height 10000` (with this value plus the line height bigger than 1000) results in `Line height too large after adjustment`
`adjust_line_height 10000%` (with this value times the line height bigger than 1000) results in `Line height too large after adjustment`

Some of those are a bit more tricky to fix (if you want to fix them) because they need to take the font size into account.

**Comment by kovidgoyal** [comment]
There is no real way to fix very large positive values, but negative
values have been fixed
