### ISSUE TITLE
Tab completion bugged with zsh frameworks zim and Prezto

### ISSUE THREAD

**Issue by truongio** [kovidgoyal/kitty#1395]
When you start writing a command and press tab, the thing you started writing stays in the screen and gets duplicated but it doesn't do anything. For example, if I start writing `gi` and press TAB, it will look like `gigi` on my screen and if I want to get it to say `git`, it will instead say `gigit`. Pressing enter still makes it behave as if I have typed `git` even though it says `gigit`. See GIF (Zim is used) for clarification.

![out](https://user-images.githubusercontent.com/28986412/52993831-dd1af600-3415-11e9-902e-826d4c79b0f7.gif)

**Comment by kovidgoyal** [comment]
I have no idea what frame zim and prezto are, I need a minimal .zshrc to reproduce your issue with, or otherwise use --dump-bytes with kitty to create a minimal dump file to recreate the issue.

**Comment by truongio** [comment]
My apologies, the title was incorrect. It was supposed to be "framework". They are configuration frameworks for zsh. https://github.com/zimfw/zimfw and https://github.com/sorin-ionescu/prezto

**Comment by truongio** [comment]
Can be recreated with this .zshrc

```
# zim
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

autoload -Uz compinit
compinit
# Completion for kitty
kitty + complete setup zsh | source /dev/stdin
```

**Comment by kovidgoyal** [comment]
doesn't that require something in ~/.zim?

**Comment by truongio** [comment]
Yes, you need to install zim. https://github.com/zimfw/zimfw

**Comment by truongio** [comment]
I identified the module in ZSH that messes it up, it's https://github.com/zimfw/zimfw/blob/master/modules/prompt/README.md

**Comment by truongio** [comment]
Found a solution.
https://github.com/sindresorhus/pure/issues/412
https://github.com/sindresorhus/pure/issues/300#issuecomment-328744993

**Comment by lminer** [comment]
I have this identical problem but only when I ssh into a remote server. Happens with ohmyzsh and pure prompt. Adding those two lines to my .zshrc does not fix anything. Here's my dump file.


[dump.tar.gz](https://github.com/kovidgoyal/kitty/files/4532394/dump.tar.gz)

**Comment by kovidgoyal** [comment]
Do this: https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by lminer** [comment]
It works! I had to alter my path so that anaconda wasn't being used first.
