### ISSUE TITLE
vim keybinding not working in kitty: nnoremap ˚ <C-w>+

### ISSUE THREAD

**Issue by kevindashgit** [kovidgoyal/kitty#1399]
os: osx Mojave
kitty version: kitty 0.13.3 created by Kovid Goyal
neovim version: 0.3.2-dev

I have the following bindings setup to resize the panes within terminal neovim.
```bash
nnoremap ∆ <C-w>-
nnoremap ˚ <C-w>+
nnoremap ˙ <C-w><
nnoremap ¬ <C-w>>
```

The funky characters are to simulate 'j' 'k' 'l' 'm' vim movements

In Term and iTerm2 I don't have a problem. Kitty, however, is problematic. 

**Expected**: The vim pane is resized by one character.
**Actual**: The behavior is that the alt/option key is ignored and I end up moving up/down/left/right one character.

**Comment by kevindashgit** [comment]
Ah just to defend the significance of the binding (to avoid any "who cares" type sentiment towards this issue) - I'm able to mash <alt> + 'l' 'l' 'l' ...  and watch the pane expand _n_ times as opposed to the default <C-w>+ where I'd have to mash <C>+ for each.

**Comment by kovidgoyal** [comment]
See macos_otion_as_alt in kitty.conf

**Comment by kevindashgit** [comment]
thanks @kovidgoyal 

Slight correction:  `macos_option_as_alt` and the value I want is `no`
