### ISSUE TITLE
1px of extra spacing, Makes Powerline look terrible

### ISSUE THREAD

**Issue by geordieF** [kovidgoyal/kitty#14]
there seems to be an extra `1px` of letter spacing, powerline doesn't look right.
![DodgyAF.png](https://cloud.githubusercontent.com/assets/10172736/21743844/e5de663a-d50a-11e6-850d-fe86c1fabe86.png)

**Comment by kovidgoyal** [comment]
What powerline font is that? Not only is there a border, the solid arrow does not seem to be properly aligned. Basically it looks like the solid arrow glyph is not palced correctly in the patched font. 

See the screenshot in the kitty readme page for how a properly patched powerline font renders. IIRC the powerline font patcher is outdated and unmaintained, I have an updated font patcher script in my watcher repository that works with modern versions of fontforge, try regenerating your font with that.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/watcher/blob/master/fontpatcher.py
