### ISSUE TITLE
Feature request: Resize Kitty window using mouse

### ISSUE THREAD

**Issue by entscheidungsproblem** [kovidgoyal/kitty#1402]
Would it be possible to add support for resizing Kitty windows? I'm thinking of something like tmux mouse-resize-pane.

**Comment by kovidgoyal** [comment]
kitty windows are already resizable, see https://sw.kovidgoyal.net/kitty/#layouts
using keyboard shortcuts. I'm afraid I'm not interested in making them
resizable via mouse as well.

**Comment by ManyEyedFox** [comment]
I posted on the original request for this feature, would you be interested in predefined sizes in session files ?

**Comment by tijptjik** [comment]
For those looking for a direct reference to the [resizing docs](https://sw.kovidgoyal.net/kitty/layouts/#window-resizing): 

> You can resize windows inside layouts. Press `ctrl+shift+r` (also `⌘+r` on macOS) to enter resizing mode and follow the on-screen instructions.

**Comment by bjesus** [comment]
I love kitty but this really goes against what the FAQ says about "kitty contains features that do all of what tmux does, but better". tmux allows me to resize my windows by simple dragging the border lines, which is impossible in kitty.

**Comment by rjpcasalino** [comment]
@kovidgoyal thanks for kitty! Works wonderfully thus far. Along with the keyboard shortcuts I can resize my windows w/ alt key and middle mouse button. Perhaps that will work for others? I'm running kitty with X11 and the calm window manager.

**Comment by webdev23** [comment]
The packaging is great, as well as the performance, however it's really deceptive to see the lack of crucially important features, like \e[5m blinking characters, mouse tab resizing, or session persistence.  

Even after spending a lot of time configuring that program and reading the whole documentation, I fear that I am going to face something else of the kind again. 

I understand the coast of refreshing the buffer for blinking characters, and the time engaged, but without the 3 features cited above, Kitty can't be sold as a replacement for `tmux`.
