### ISSUE TITLE
Background flashes black when opening new OS window

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1404]
I noticed, that the background flashes back, whenever I open a new OS window. This didn't happen a few commits ago. I recorded my screen so I could make a screenshot.
For the first four frames kitty looked like this:
![black background](https://user-images.githubusercontent.com/15217907/53264487-ff459a00-36db-11e9-8542-2f264d6d7bcc.png)
This is what the fifth frame looked like:
![normal background](https://user-images.githubusercontent.com/15217907/53264515-12586a00-36dc-11e9-979f-e7c34fc5ddf6.png)
I found out, that dcb2d95f9a9dc7d95a8d69b98684ee24bd50bd4b  doesn't show this behaviour but the next commit, f3974671f6a1eaf91d2b00b34f481d49b295002d does. I tried reverting f3974671f6a1eaf91d2b00b34f481d49b295002d on top of the latest master but that didn't help. I have to also revert abd4de731102ef13651b760bb0aef05cc2ced573. Reverting either one of them doesn't fix this issue. Do you know why this could be happening and how I can debug this?

**Comment by kovidgoyal** [comment]
I have no idea why it might be happening, but to debug it look at calls to swap_window_buffers(). See how many times it is called before the proper color is rendered. Check if it is being called from framebuffer_size_callback
