### ISSUE TITLE
Opacity setting persisting in Full Screen Mode on MacOS

### ISSUE THREAD

**Issue by publik-void** [kovidgoyal/kitty#1405]
When entering full screen in MacOS while using background transparency, you get a black color "behind" the full screen terminal window. Is there a way to disable background transparency in full screen mode or, alternatively, change the background color in full screen mode to make up for the perceived shift in brightness?
In other words, I would like to use transparency only when using kitty in a floating window, but to have kitty's background fully opaque as soon as I enter full screen mode.

* kitty version: 0.13.3
* OS: MacOS Mojave 10.14.3

**Comment by kovidgoyal** [comment]
You can control background opacity via key board shortcuts as well as
the remote control facility in kitty. Either of those two will let you
change the background opacity as you wish. See
dynamic_background_opacity in kitty.conf or
https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by publik-void** [comment]
Thanks! But as far as I can see, there's no "entered full screen" hook which lets kitty automatically change the background opacity exactly at the time you enter full screen mode. Keyboard shortcuts are no real solution, since you'd have to press a shortcut key every time you enter or leave full screen mode. That would be quite annoying, in my humble opinion.
I'd imagine something like a `disable_background_opacity_in_fullscreen` option in kitty.conf.
Anyway, I might submit a pull request in the future when I get the time to wrap my head around the codebase and, of course, provided you are at all interested in such an option.

**Comment by kovidgoyal** [comment]
use the combine action to create a new shortcut in kitty.conf that
enters full screen and then sets the background opacity to whatever you
like.

**Comment by Luflosi** [comment]
That won't work if he's using the native means of entering fullscreen on macOS, like clicking the green button, `ctrl+cmd+f`, the menu bar item "Enter Full Screen" or dragging the window from Mission Control into the top bar.

A lot of of macOS apps that have some translucency like Safari and iTunes let the Desktop wallpaper shine through. Maybe the same thing can be done with kitty. Perhaps all that is needed is some Cocoa API call to tell macOS to show the wallpaper behind the window but I really have no idea.
I tried creating a blurred background before: https://github.com/Luflosi/kitty/tree/background_blur (very unclean test code) but I didn't manage to have both a blurred background and text visible at the same time. I think that's because when I create a new `NSVisualEffectView`, that view is on top of the other view with the OpenGL stuff but since I'm an Objective-C noob, I have no idea how to fix that. Anyways, that code manages to show the blurred wallpaper (but makes kitty useless since no text is visible), it could potentially be helpful.

Another option could be to disable and re-enable transparency in the `toggleFullScreen()` function in `glfw/cocoa_window.m`.

**Comment by kovidgoyal** [comment]
well if you can figure out how to let the desktop wallpaper through in full screen mode, I will be happy to merge the PR.

**Comment by Luflosi** [comment]
I don't think I can do that so don't hold your breath.

**Comment by kovidgoyal** [comment]
Hmm well I dont see any other good solutions. The OP should simply use a kitty shortcut for this rather than clicking/dragging whatever.

**Comment by arkenthera** [comment]
Sorry for necroing this issue, I was looking for how I could achieve the "vibrancy" effect on Kitty and stumbled across this post. I managed to hack it around: I created 2 views, one for `NSVisualEffectView` and one plain `NSView` and added these into content view. Then when creating the `NSGL` context I fed it the regular `NSView` so GL would render into the `NSView`. Like @Luflosi said, if you just add an `NSVisualEffectView`, Kitty's rendering breaks and you only see the blurred background. But if we instruct the GL context to use another view it just works. 

![2021-04-04 00 06 10](https://user-images.githubusercontent.com/5428012/113491763-c17ee680-94db-11eb-800e-8d039b8c3450.jpg)
![2021-04-04 00 05 58](https://user-images.githubusercontent.com/5428012/113491770-c80d5e00-94db-11eb-8fe4-bad7d8fbfb92.jpg)

**Comment by Luflosi** [comment]
Feel free to make a PR with a first draft of your code, then I can help you improve it and maybe get it merged.

**Comment by kammerdienerb** [comment]
I'm also interested in this patch that adds the macOS vibrancy to the background. Is it something that could possibly be merged or shared in a fork?

**Comment by Luflosi** [comment]
I tried implementing this a long time ago but I couldn't get it to work. See my [comment](https://github.com/kovidgoyal/kitty/issues/1405#issuecomment-466654947) above.

**Comment by kammerdienerb** [comment]
Ah. I was encouraged by arkenthera's screenshots and hoped he had managed to figure it out...

**Comment by arkenthera** [comment]
here is my fork: https://github.com/arkenthera/kitty

sorry about the commit messages and logs, I hadnt intended to make it public

**Comment by Luflosi** [comment]
Ah, sorry, I only remembered my attempt and didn't read the post again. Looks like @arkenthera indeed managed to make it work. Thanks for sharing your code.

**Comment by kammerdienerb** [comment]
Oh thank you, this is great! What would need to be done in order for this to be merged in?

**Comment by arkenthera** [comment]
it was just for myself so you would need to clean the code and create a PR i guess.

**Comment by kammerdienerb** [comment]
I suppose I was mostly wondering what @kovidgoyal would deem necessary (such as config options, tests, etc.)

**Comment by kovidgoyal** [comment]
It would need and option to turn it on. And the PR would need screenshots showing how it interacts with the various other macOS settings such as hide_window_decorations, background opacity etc.

**Comment by AbrahamRaGo** [comment]
It's possible, just need to set macos_traditional_fullscreen from no, to yes 

`macos_traditional_fullscreen yes`

**Comment by BIKA-C** [comment]
@0x61726b , i tried your implementation with the current version of kitty. Apparently when the window resizes, the content is not updated (so, the content is limited to a certain size if i make the window too big). Would you think might be the issue? i really want to make this feature into kitty but i have very limited experience in obj-c. Could u maybe point me some direction to look up for?

**Comment by nrdlab** [comment]
> It's possible, just need to set macos_traditional_fullscreen from no, to yes
> 
> `macos_traditional_fullscreen yes`

Working 🙌
