### ISSUE TITLE
Invisible text on macOS 10.11.6

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#141]
Using the latest build from `master`, all the text in the spawned terminal is invisible.

**Comment by kovidgoyal** [comment]
Works for me. Run it with --debug-kitty-gl and see if it reports any errors.

**Comment by Alok** [comment]
No errors get printed out when I run it with that. I notice that pressing `c-d` does not exit the spawned terminal, i have to type `exit` to do that, though control c works, judging by how the cursor jumps. The cursor is the only visible component.

**Comment by kovidgoyal** [comment]
Hmm well without being able to reproduce it, it's hard for me to help. See if this commit makes a difference: https://github.com/kovidgoyal/kitty/commit/3f8b2184a6081c616378e34452c5dba9a47f2620

**Comment by Alok** [comment]
It doesn't, but I'll try to reproduce the issue and report back.

**Comment by kovidgoyal** [comment]
Here is the build I used that does not show this issue: https://download.calibre-ebook.com/betas/kitty-0.3.0.dmg

**Comment by Alok** [comment]
That build displays the issue for me, so I'll have to continue trying to reproduce it.

**Comment by kovidgoyal** [comment]
I should say I have tried it only on macOS 10.13 not 10.11.

**Comment by kovidgoyal** [comment]
Another commit that might help, let me know if it works: https://github.com/kovidgoyal/kitty/commit/e679fa9a1c55c27345ae09524299571a22572b44

**Comment by Alok** [comment]
didn't work

**Comment by kovidgoyal** [comment]
I give up, I've just disabled graphics support on older macOS versions. That should take care of it.

**Comment by kovidgoyal** [comment]
A better fix, that should allow graphics to works as well, though I have no way to test that. https://github.com/kovidgoyal/kitty/commit/66803e6873c9f8df1a75265aedc0670fce4411be

**Comment by Alok** [comment]
Thank you. I can appreciate the headache of trying to fix a problem on software you don't even have.

Really enjoying the commit messages too.

**Comment by eldentyrell** [comment]
Sorry about the slow response, I got dragged into a firefight on another project yesterday.

Simply disabling graphics on outdated OSes is probably the right approach.  Personally I'm trying to move off of them, and Kitty is a major help in doing this.

However @kovidgoyal if you run into a frustrating bug on hardware you don't have please let me know and I can set up a VNC machine for you.  I believe that Macs use the actual graphics hardware (underpowered Intel GPU in many cases) to render even for VNC sessions so you should be able to see any GPU-induced OpenGL bugginess.  I have a pretty large assortment of older mac hardware and most versions of MacOS available and it's a fiber connection on the US West Coast so the latency to you should be very good.

**Comment by kovidgoyal** [comment]
Thanks for the offer. However, as I am in India, I doubt the latency would be tolerable. Still if it is something critical it would be better than nothing. 

As for disabling graphics, I like to support as wide a gamut of OSes/OS versions as is practical. ANd since the fix does not impose too much of a performance penalty (and zer penalty when you dont use the graphics) I considered it worthwhile. 

I too wrote kitty because I am trying to gradually transition off GUI based applications entirely. However, for some things, such as image viewing, you do need graphics. My motivation for implementing fgraphics in kitty is to port https://github.com/kovidgoyal/iv to become a terminal program.

**Comment by alok** [comment]
@kovidgoyal did you ever end up putting `iv` in the terminal?

**Comment by kovidgoyal** [comment]
On Tue, Apr 06, 2021 at 01:04:33AM -0700, Alok Singh wrote:
> @kovidgoyal did you ever end up putting `iv` in the terminal?

Doing that is why #3287 exists.
