### ISSUE TITLE
feature request: make tabs with "bell" character more noticeable

### ISSUE THREAD

**Issue by h5vx** [kovidgoyal/kitty#1413]
In some cases, e.g. when you working in one tab and have irssi or some significant process running in another, you will not notice when something happens there. In tmux, when you have inactive windows, their tabs change color (you can also configure them to blink) when ASCII "bell" (`\a`) character appears in their output. That's useful, because many programs use `\a` symbol to indicate that something important happens (e.g. terminal IM clients: poezio (XMPP), irssi (IRC), etc).

I found out that kitty already have this feature, but still not as good as tmux; kitty just append "bell" character to the tab, this character is even not visible! (fallback to little "square" character).

So, my offer is to:
* **Add option to change tab's background and foreground color when "bell" character appears**
    * **Add blink option**
* (less important) **Add option to underline tab's title when new output appears**

**Comment by kovidgoyal** [comment]
I find the bell character pretty unmistakeable. Install a color emoji
font on your system then you will also find it pretty obvious (it will
be rendered as a bell icon).
