### ISSUE TITLE
Invalid content after resize on macOS

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1416]
If i list the files in a folder, then resize the window to a minimum in width / height, then back and scroll up, various rendering issues occur. Here is the original image:
<img width="677" alt="screenshot 2019-02-24 at 18 06 56" src="https://user-images.githubusercontent.com/1562523/53302542-63dd3200-385f-11e9-9c4a-4189afa0f429.png">

If i minimize in both width and height, and then back again, the last line is repeated two times, on one line, like this.
<img width="632" alt="screenshot 2019-02-24 at 18 07 10" src="https://user-images.githubusercontent.com/1562523/53302544-68094f80-385f-11e9-88dd-07a881af20b8.png">

If i only minimize in width and back, the second last line is now under the last line, like this:
<img width="758" alt="screenshot 2019-02-24 at 18 06 50" src="https://user-images.githubusercontent.com/1562523/53302567-9850ee00-385f-11e9-8105-c3a40f2cc072.png">

**Comment by kovidgoyal** [comment]
I cannot replicate, using either bash or zsh and kitty from master (although there are no changes in recent versions of kitty that should affect this) on my macOS system, steps Itried:

1) Start kitty
2) run ls -l
3) resize kitty window to minimum size
4) resize kitty window to original size
5) Scroll up

The only artifact I see is that one line is wrapped early, i.e., it was not unwrapped back to the original state after expanding the window. There are no duplicated or shifted lines.

I'm guessing this is some interaction with whatever shell you are using.

**Comment by erf** [comment]
I'm on bash shell. I think this issue has existed for a while. I tried to disable `.bash_profile` and `kitty.conf`. I can now only see the last line from `ls -l`, on the current line, after i resize to minimum and back.

**Comment by erf** [comment]
Oh, and by resizing i mean dragging the window from bottom right to top left and NOT by pressing the yellow minimize button. So the window will look something like this:
![screenshot 2019-02-25 at 13 27 47](https://user-images.githubusercontent.com/1562523/53337318-5b3d3800-3901-11e9-8147-0ed622067973.png)

**Comment by kovidgoyal** [comment]
Yeah that was the resizing I tried

**Comment by erf** [comment]
I also notice the wrapped line. Does this not indicate there is some missing layout / rendering after resize?

**Comment by kovidgoyal** [comment]
No, basically the first line in the scrollback buffer cannot be unwrapped because of a detail of how th ebuffer is implemented. That is fairly harmless, it just means one unwrapped line

**Comment by erf** [comment]
Yep, not a big issue, just a minor visual annoyance  - do you think it is worth looking into the buffer implementation?

Also it seem scrolling does not trigger re-layout.

**Comment by kovidgoyal** [comment]
Not worth it to me, but patches are welcome. What do you mean by
scrolling not triggerring a re-layout? Why would scrolling cause
re-layout?

**Comment by erf** [comment]
So all history should be rendered correctly before scrolling?

Ok, i will close this now then. I don’t think i’m able to fix the buffer, but others feel free.
