### ISSUE TITLE
feature request: query background color

### ISSUE THREAD

**Issue by gavocanov** [kovidgoyal/kitty#1417]
Hi,

It seems like automatic background color detection has landed in [neovim](https://github.com/neovim), based on [this commit](https://github.com/neovim/neovim/commit/246408621c405a6c0f24e2e5cd66e8776eb04fe6#diff-3ac88981a139ac0eee448a6bd19c7569R1655), as [stated](https://github.com/neovim/neovim/pull/5027) it seems like it's something supported `on any xterm compatible terminal`, would be nice if it worked on kitty also.

I tried it but it seems like it's not working, can this be implemented?

Thnx in advance and keep up the good work!!

**Comment by kovidgoyal** [comment]
This is implemented already in kitty, has been for years.

```
printf '\x1b]11;?\x07
^[]11;rgb:0000/0000/0000^[\
```
