### ISSUE TITLE
How do I customize the status bar when we have Tabs?

### ISSUE THREAD

**Issue by varmanishant** [kovidgoyal/kitty#142]
I didn't see anything in the default configuration file.

Mainly I am looking for two things:

1. Show the active Tab name in the Normal font without italics. 
2. Make the delimiter something simple like a pipe or none at all. (It is redundant)

Can someone please assist?

**Comment by kovidgoyal** [comment]
The only customization you can do is of the colors, see the section labeled Tab-bar colors. And the separator is most definitely not redundant. How would you distibuish consecutive tabs if their titles are long and have spaces in them?
