### ISSUE TITLE
issue with repaints over ssh

### ISSUE THREAD

**Issue by nickdesaulniers** [kovidgoyal/kitty#1425]
so I ssh from kitty+zsh+linux mint into a ubuntu+zsh box.  I haven't booted the box in a few months, but even after updates, ctrl+l (L) and backspace aren't working correctly.

ctrl+l puts the prompt on the same line, to the right.
backspace moves the prompt right two.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

make sure the kitty terminfo files are available.
