### ISSUE TITLE
Ignore vsync setting on wayland

### ISSUE THREAD

**Issue by Gigg1ty** [kovidgoyal/kitty#1426]
It might be a good idea to ignore the "sync_to_monitor" setting or default to "no" if running on wayland, as wayland already has vsync enabled by default.

Kitty on swaywm was really slow to open new windows (even with --single-instance) or resize existing ones while vsync was enabled in kitty.

Thank you for your great work by the way!

**Comment by kovidgoyal** [comment]
sync_to_monitor works via render frames in wayland. I dont use sway, but I can see no performance problems under weston. For example running:

time kitty sh -c exit

takes 0.75 seconds on my three year old laptop. This is the total time to launch kitty and open a single window. Opening a new window in an already running instance is perceptually instantaneous for me.

**Comment by kovidgoyal** [comment]
Test on your ysstem using weston and also make sure you are running up-to-date versions of kitty sincethere have been several wayland related fixes in the recent past.

**Comment by kovidgoyal** [comment]
Also are you actually runningusing wayland or xwayland? You have to use KITTY_ENABLE_WAYLAND=1 to get kitty to use its wayland backend.

**Comment by Gigg1ty** [comment]
"KITTY_ENABLE_WAYLAND=1" is set, and "kitty --debug-config" reports "Running under: Wayland".

But this might have been a sway issue. I have set "sync_to_monitor" to yes again to test this, but it is now instantaneous again.

Sorry for bothering you... 😅 (And again thank you for kitty. Love it!)

**Comment by Hello71** [comment]
I think this actually doesn't work right. In single-instance mode on sway, if a window is not displayed and has some pending output (I used mpv, but probably `while sleep 1; echo hello; done` has the same effect), and sync_to_monitor is set to true, kitty will "lag" on the displayed windows.

**Comment by Hello71** [comment]
... and also if kitty is using xwayland, and also if xorg-server is at least 1.20.4 (which fixes xwayland vsync).

**Comment by kovidgoyal** [comment]
I cannot reproduce on weston, steps I tried:

1) Launch kitty
2) In weston terminal run yes
3) minimize weston terminal
4) In kitty run htop
5) kitty window is updated continuously

**Comment by Hello71** [comment]
uh, perhaps I wasn't clear. I specifically did this:

1. start sway
2. set `sync_to_monitor true`
3. unset KITTY_ENABLE_WAYLAND
4. start `kitty -1` twice
5. in the first one, run mpv
6. move the first one to a new workspace
7. run ls in the second one

expected results: as I type, l is displayed immediately (within 100ms), then s, then a new line, then the results of the command.

actual results: there is a significant delay of many seconds. the delay is "aborted" (output appears) if the new workspace is switched to and back from.

**Comment by kovidgoyal** [comment]
That's certainly clearer, but why are you disabling the wayland backend?
And can you reproduce with kitty from master? I ask because
KITTY_ENABLE_WAYLAND no longer exists in master and there have been
several changes that could affect this.

**Comment by Hello71** [comment]
well I'm not setting KITTY_ENABLE_WAYLAND=0, just not explicitly enabling it. I think it works alright on master. I tested 0.13.3 above.
