### ISSUE TITLE
Double width chars resized to one cell

### ISSUE THREAD

**Issue by jmriego** [kovidgoyal/kitty#1427]
Hi! Sorry to open an issue to similar to previous ones. This is happening when using Nerd Fonts as the font for glyphs. It seems like the code for activating double width chars when you have an unicode PUA character and then an space is not activating for me.

My `kitty.conf` is as follows:

    font_family      UbuntuMono
    symbol_map U+E000-U+FFFF UbuntuMono Nerd Font

After investigating this for a while, I noticed that this used to work but stopped working with release v0.13.0. My guess is that it's related to the change for choosing the number of cells based on bitmap width. Is this something that can be fixed or should I look into modifying something else?
Thanks a lot!

**Comment by kovidgoyal** [comment]
Works for me, update to the latest release, IIRC there was a regression
in 0.13.0 about this.
