### ISSUE TITLE
get_glyph_width returning zero

### ISSUE THREAD

**Issue by jmriego** [kovidgoyal/kitty#1428]
Hi!
When testing Kitty with Nerd Fonts, I noticed an issue when rendering PUA characters. They all seemed to be scaled down to one cell for me in Ubuntu 18.04. I have tried many different Nerd Fonts from old versions, different forks, cleaning the font cache every time.

This has been happening in every version since Kitty v13. I have had a deeper look at the issue and found that the issue is happening for me in the `get_glyph_width` function.

This is what it looks now for me:
![screenshot from 2019-02-28 09-41-16](https://user-images.githubusercontent.com/15045950/53562057-4999a180-3b48-11e9-8413-c5192a3cde9b.png)
This is what it used to look before v13:
![screenshot from 2019-02-28 09-42-49](https://user-images.githubusercontent.com/15045950/53562068-51f1dc80-3b48-11e9-9deb-1cebe4933633.png)

get_glyph_width is returning zero as the bitmap width in this part of the code:
    
        FT_Bitmap *bitmap = &self->face->glyph->bitmap;
    #define M self->face->glyph->metrics
    #define B self->face->glyph->bitmap
        printf("glyph: %u bitmap.width: %d bitmap.rows: %d horiAdvance: %ld horiBearingX: %ld horiBearingY: %ld vertBearingX: %ld vertBearingY: %ld vertAdvance: %ld width: %ld height: %ld\n",
                g, B.width, B.rows, M.horiAdvance, M.horiBearingX, M.horiBearingY, M.vertBearingX, M.vertBearingY, M.vertAdvance, M.width, M.height);
        return bitmap->width;

This is what that `printf` is showing me for the Python logo:
`glyph: 3732 bitmap.width: 0 bitmap.rows: 0 horiAdvance: 832 horiBearingX: 0 horiBearingY: 768 vertBearingX: -448 vertBearingY: 192 vertAdvance: 1216 width: 832 height: 896`

`B.width` returns zero even though `M.width` returns 832. Should I send a pull request that returns `M.width` when the bitmap width is greater than zero?
Thanks!

**Comment by jmriego** [comment]
Thanks a lot! It works perfectly here

**Comment by kovidgoyal** [comment]
You're welcome :)
