### ISSUE TITLE
separate font_size per window

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#1429]
Is it possible for every window to have its own `font_size`?
Currently it seems that changing the font size through the hotkeys changes every window.
For example I might want to have a bigger font on my big external display and keep
the smaller font size on the built-in display. Thank you.

**Comment by kovidgoyal** [comment]
See change_font_size in kitty.conf, you can tell it to change size in
only the current OS window, or all windows.

**Comment by minusf** [comment]
my bad, need to get friendlier with the config file, sorry about the noise.
