### ISSUE TITLE
emacs's supercomplicated rendering engine misrenders on kitty

### ISSUE THREAD

**Issue by eldentyrell** [kovidgoyal/kitty#143]
Emacs's terminal output driver doesn't like kitty.  In particular, when you page down (C-v) it misrenders badly, shifting some text over by one character.  Since the rendering is incremental this also means it sometimes leaves one character of garbage when it does this.

I have a patch to fix the kitty bug, will be submitting a pull request right after this.

Screenshot below shows the misrender after page-down (in the file all lines starting with "&&" are indented identically, using spaces not tabs).

![misrender](https://user-images.githubusercontent.com/1221356/31608591-9fef131a-b225-11e7-86d2-be3d1e89366e.png)

**Comment by kovidgoyal** [comment]
I knew there was a reason I prefered vim ;)

Thanks for the patch.

**Comment by eldentyrell** [comment]
> I knew there was a reason I prefered vim ;)

Yeah one of these days I will defect to the other side :)

Thank you so much for writing kitty!  Besides being awesome, it works (well) on both MacOS and Linux which makes transitioning between them so much easier.

**Comment by kovidgoyal** [comment]
You are welcome :)

Incidentally, since you appear to be both using macOS and running from master, are you experiencing the issue #141 ?

I cannot replicate it, but I only have a single old mac mini so it would be good to know if it works on a more representative mac.

**Comment by eldentyrell** [comment]
> Incidentally, since you appear to be both using macOS and running from master, are you experiencing the issue #141 ?

Funny you bring that up.

I did not experience it with the latest (3.0) dmg downloaded from github.

I just rebuilt kitty from git source on my mac (10.9.5) and I *am* experiencing it.

Any suggestions?

**Comment by kovidgoyal** [comment]
Hmm from the nature of the problem it seems like some data is not being passed to the GPU as expected. mac OpenGL drivers are pretty bad, so I'm guessing it has something to do with the changes to the OpenGL code I made for #33 

Try git bisect to identify the problem. I expect the problem somewhere between the commit b032130 and HEAD. Note that while bisecting you might have to edit the file graphics_fragment.glsl to replace texture2d() with texture() as the mac OpenGL drivers dont support texture2D().

**Comment by kovidgoyal** [comment]
Also, if you drag with the mouse to select text, does the text become visible?

**Comment by eldentyrell** [comment]
Yep, bisecting now.  Selecting unrendered text does not result in rendering (see screenshot).
![fail](https://user-images.githubusercontent.com/1221356/31611221-1f53257e-b230-11e7-95c4-27ca9fff3e8b.png)

**Comment by kovidgoyal** [comment]
Hmm unfortunately my only mac has macOS 10.13 and that does not show this problem.

**Comment by eldentyrell** [comment]
Hrm, I also have to push 952f0ad9 backwards...

**Comment by kovidgoyal** [comment]
That commit should not affect text rendering at all, it only touches the graphics shaders and the code to load the graphics shader data.

**Comment by eldentyrell** [comment]
Right but from that commit until several commits later the binary crashes.

**Comment by eldentyrell** [comment]
commit 138a37ccace8032ee11dc0fe0721fe8d5b7f595b
Author: Kovid Goyal <kovid@kovidgoyal.net>
Date:   Wed Oct 4 04:52:00 2017

    Start work on the graphics program

**Comment by eldentyrell** [comment]
That is the culprit.

**Comment by eldentyrell** [comment]
It has the no-chars-drawn bug, and the commit before it does not.

**Comment by eldentyrell** [comment]
Suggestion: having a "clean" target in your Makefile would be a nice idea.  Remember to get rid of the __pycache__ junk too.

**Comment by kovidgoyal** [comment]
If you comment out lines 225 and 226 in shaders.c does it fix it?

**Comment by kovidgoyal** [comment]
There's not much need for clean since by default everything is rebuilt. You can do incremental building by

python3 setup.py --incremental

**Comment by eldentyrell** [comment]
> There's not much need for clean since by default everything is rebuilt.

... unless that is in fact the source of the bug :)

Just a troubleshooting habit.  Always start from a totally clean slate when running an experiment.

**Comment by eldentyrell** [comment]
Um, which lines?  225+226 are a blank line and close-semicolon.  Can you paste what you expect to be on the lines that should be commented out?

**Comment by kovidgoyal** [comment]
```c
    add_buffer_to_vao(vao_idx, GL_ARRAY_BUFFER);
    AL(GRAPHICS_PROGRAM, "src", 4, GL_FLOAT, NULL, 0);
```

**Comment by kovidgoyal** [comment]
Since make rebuilds everything, you are starting from a completely clean slate. Adding a clean to the Makefile would just be theatre.

**Comment by kovidgoyal** [comment]
The line numebrs refer to current master, not the problem commit.

**Comment by eldentyrell** [comment]
Those lines do not appear in the problem commit.  Did you mean these?

>    add_buffer_to_vao(vao_idx, GL_ARRAY_BUFFER);
>    AL(GRAPHICS_PROGRAM, "src", 4, GL_FLOAT, 0, sizeof(ImageRenderData));

**Comment by kovidgoyal** [comment]
Yes in the problem commit, those would be the corresponding lines.

**Comment by kovidgoyal** [comment]
Sorry, in the problem commit it would be three lines, not two:

```
add_buffer_to_vao(vao_idx, GL_ARRAY_BUFFER);
AL(GRAPHICS_PROGRAM, "src", 4, GL_FLOAT, 0, sizeof(ImageRenderData));
AL(GRAPHICS_PROGRAM, "position", 4, GL_FLOAT, offsetof(ImageRenderData, dest_rect), sizeof(ImageRenderData));
```

**Comment by eldentyrell** [comment]
Ah thanks.  Yes, that fixes #141 -- specifically I can confirm the code as it appears in the second pull request works.

**Comment by kovidgoyal** [comment]
See if this fixes it https://github.com/kovidgoyal/kitty/commit/e679fa9a1c55c27345ae09524299571a22572b44

**Comment by kovidgoyal** [comment]
You should be happy to hear that I have added a clean action to the Makefile, not for the purpose of build testing, but so that I can easily check that bootstrapping from a clean checkout works.

**Comment by eldentyrell** [comment]
Thank you!  I will try e679fa9 this afternoon.

**Comment by kovidgoyal** [comment]
No need, #141 has been fixed via see the bug for discussion. The final fix was https://github.com/kovidgoyal/kitty/commit/66803e6873c9f8df1a75265aedc0670fce4411be
