### ISSUE TITLE
Running shell script from mapping

### ISSUE THREAD

**Issue by kristijanhusak** [kovidgoyal/kitty#1431]
Hi, is there a way to run external shell script from mapping, or maybe an alias?

For example:
```
map ctrl+F8 ~/scripts/my_script.sh
```
or `alias myscript="~/scripts/my_script.sh"`:
```
map ctrl+F8 myscript
```

I docs i found only way to run internal commands/actions, or to create a "kitten" in python.

**Comment by kovidgoyal** [comment]
See the pipe command https://sw.kovidgoyal.net/kitty/pipe.html

**Comment by mgiugliano** [comment]
@kristijanhusak May I ask you whether it worked for you? What is your final line in kitty.conf to launch a (custom) shell script?

**Comment by kristijanhusak** [comment]
@mgiugliano tbh I don't remember why i needed this. I don't use this at all.
