### ISSUE TITLE
How to change font family on the fly?

### ISSUE THREAD

**Issue by eater** [kovidgoyal/kitty#1436]
I see that I can issue a remote command to change font _size_, but often (e.g. when using bitmap fonts that don't change size gracefully) I'd like to change the font _family_ in my open terminals.

What's the easiest way to do this?

**Comment by kovidgoyal** [comment]
Sorry this is not a capability I am interested in providing. I'm sure it
is technically possible, but it is complex and the whole reason kitty
does not do bitmap fonts is that they are not scaleable and having
freely scaleable fonts is one of kitty' core goals.

**Comment by eater** [comment]
Ah, too bad. It's not only bitmap fonts -- most fonts are more readable at some sizes than other sizes, so since I use a wide range of DPIs and displays, this will prevent me from adopting Kitty.

**Comment by metalelf0** [comment]
> Ah, too bad. It's not only bitmap fonts -- most fonts are more readable at some sizes than other sizes, so since I use a wide range of DPIs and displays, this will prevent me from adopting Kitty.

@eater yeah I feel your pain too. The only way right now is killing kitty and starting over. If you're using tmux you could just detach and reattach, but if you're using kitty panes and windows - like I'm doing - you're lost. I'd really love this feature to be added too. I tried starting working on it, but this is not my domain at all (I'm into web dev), and I got lost pretty soon in the code :/
