### ISSUE TITLE
Vim devicons not working

### ISSUE THREAD

**Issue by ChrisCallanJr** [kovidgoyal/kitty#1437]
relevant plugin: https://github.com/ryanoasis/vim-devicons

basically, when looking at (neo)vim side by side in iterm and kitty, the dev icons for vim are not working in kitty. I am using the same patched font on both(I know kitty eliminates the need for patched fonts but I have yet to able to get code points to work properly) was curious if this has come up before and if I'm missing something

**Comment by kovidgoyal** [comment]
search for nerd fonts in the kitty issue database and you will find the relevant info. Basically you have to ensure there are enough blank saces after the symbol codeoints.
