### ISSUE TITLE
Kitty doesn't play nice with telnet

### ISSUE THREAD

**Issue by Compunctus** [kovidgoyal/kitty#1438]
Seems like it doesn't like some escape sequences from D-Link dgs 1210 switch.
OS: archlinux
telnet: one from inetutils 1.9.4-7
"raw" data from both kitty and terminator attached.

[terminator.txt](https://github.com/kovidgoyal/kitty/files/2927910/terminator.txt)
[kitty.txt](https://github.com/kovidgoyal/kitty/files/2927911/kitty.txt)

**Comment by kovidgoyal** [comment]
Use the --dum-bytes command line option in kitty to generate a dump file of a minimal session reproducing the problem, and also describe what the problem is.

**Comment by Compunctus** [comment]
Here's log and --dump-bytes result.
Basically, "listing" operations with constant updates to data shown (like "show ports") fail to display anything. They only show "259A" and that's it. xterm/terminator work properly.

Later I'll give you access to one such switch. Should be much easier to debug this way.

Relevant log lines:
```
draw Command: show ports
screen_carriage_return
screen_linefeed
screen_carriage_return
screen_linefeed
screen_reset_mode 25 1
screen_cursor_up2 0
screen_carriage_return
Invalid character in CSI: 0x2d, ignoring the sequence
draw 259A
screen_carriage_return
```

[kitty_telnet_log.txt](https://github.com/kovidgoyal/kitty/files/2929444/kitty_telnet_log.txt)
[kitty_telnet_dump.txt](https://github.com/kovidgoyal/kitty/files/2929445/kitty_telnet_dump.txt)
