### ISSUE TITLE
ctrl+l to clear screen not working anymore ( and other issues after update )

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1439]
I used to be able to press `ctrl+l` to clear screen, but this is not working anymore since 6d970c11759be60d28014c994b8b5033560b83c4.

I now also get a warning `WARNING: terminal is not fully functional`, when i do `git log`, and `Warning: unknown term "xterm-kitty"` when i open my `vis-editor`, and `nano` gives me `Error opening terminal: xterm-kitty.`.

I'm on `macOS 10.14.3`.

**Comment by Luflosi** [comment]
#1440 hopefully fixes all the issues you described.
