### ISSUE TITLE
Nerdfont triangle problems

### ISSUE THREAD

**Issue by weilbith** [kovidgoyal/kitty#1441]
I'm using a Nerdfont and like to use the `nf-ple-upper_right_triangle (`\ue0be`) at some places (e.g. NeoVim tabbar). So far this is the only character which does not looks nice, since it appends a space afterwards.
How can I solve this problem?

![1551435479](https://user-images.githubusercontent.com/12543647/53798811-4c760700-3f39-11e9-81bd-3f2d45863ebd.png)

**Comment by kovidgoyal** [comment]
kitty does not append spaces to characters. If there is a space after it, it must be present in the string being rendered. Remove it from there and you should be fine.

**Comment by weilbith** [comment]
This is the line I use to configure the _Lightline_ tabbar in _NeoVim_ and there is no space.
```vim
let g:lightline.tabline_separator    = { 'left': '', 'right': '' }
```

Furthermore I have similar issues at the format string for the _TMux_ status bar. There I haven't set any space es well. But here I was able to somehow fix it by using the opposite rectange (forward<->background) and switched the colors to use. Here at _NeoVim_ I can't do so. The same configuration in other terminal don't have this problem.

**Comment by kovidgoyal** [comment]
I can see no spaces with the following command line:

```kitty --config NONE -o "symbol_map=U+E0A0-U+E0A2,U+E0B0-U+E0B3 3270Medium Nerd Font Mono" --debug-font-fallback 
![screenshot_20190305_195545](https://user-images.githubusercontent.com/1308621/53812101-c4b3eb00-3f80-11e9-908c-127836b0d818.png)
sh -c "printf '\ue0beM'; read"
```

As I said if there is a space, it is there because whatever software is generating the string is inserting a space at that position.
