### ISSUE TITLE
Forward slash character is cut off when using Operator Mono Italic

### ISSUE THREAD

**Issue by marcoms** [kovidgoyal/kitty#1442]
Not sure why this only seems to affect Operator :/

![screenshot from 2019-03-05 15-01-57](https://user-images.githubusercontent.com/4211302/53814628-da60ea80-3f57-11e9-9a17-1f7c3e545c8c.png)

vs

![screenshot from 2019-03-05 15-03-10](https://user-images.githubusercontent.com/4211302/53814636-de8d0800-3f57-11e9-8a04-d2181727eb16.png)

My config:

```
font_family Operator Mono Book
bold_font Operator Mono Medium
italic_font Operator Mono Book Italic
bold_italic_font Operator Mono Medium Italic
font_size 24

repaint_delay 16
tab_bar_style separator
tab_separator '|'

map ctrl+t new_tab
map ctrl+w close_tab
map page_up scroll_page_up
map page_down scroll_page_down
map ctrl+up scroll_line_up
map ctrl+down scroll_line_down
```

**Comment by kovidgoyal** [comment]
Dup of #205
