### ISSUE TITLE
Save tabs between sessions

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1443]
Is there a way to save tabs, so that if you close Kitty with tabs open. Kitty, automatically open them the next time you open Kitty?

**Comment by kovidgoyal** [comment]
No, there isn't. It would basically tak eimplementing #391 for this functionality.

**Comment by Luflosi** [comment]
This is also similar to #1197.

**Comment by kovidgoyal** [comment]
Not really that is about restoring windows positions. To actually fully restore a session, you have to restore all running programs, which can only be done with #391

**Comment by KelvinJPS** [comment]
@kovidgoyal  why this feature cannot be implemented, I mean how do you achieve this otherwise?

**Comment by jenstroeger** [comment]
Alternatively, is there a way to run a script when Kitty opens which sends a bunch of [new_tab](https://sw.kovidgoyal.net/kitty/actions/#action-new_tab) and [new_window](https://sw.kovidgoyal.net/kitty/actions/#action-new_window) — I think that’d achieve a similar result.
