### ISSUE TITLE
confusion about initial window size

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#1444]
I am somewhat confused about the initial window size setting configuration:

```
remember_window_size  no
# initial_window_width  640
# initial_window_height 400
initial_window_width  50c
initial_window_height 10c

#: If enabled, the window size will be remembered so that new
#: instances of kitty will have the same size as the previous
#: instance. If disabled, the window will initially have size
#: configured by initial_window_width/height, in pixels. You can use a
#: suffix of "c" on the width/height values to have them interpreted
#: as number of cells instead of pixels.
```

after restarting Kitty.app i get:
```
$ echo $COLUMNS
100
$ echo $LINES  
20
```

So cells are half of the character size?

I personally find giving the size in pixels for a terminal emulator strange.
All other programs normally work with columns and lines like 80x25, etc
and for me pixels dont make any sense in this case.

**Comment by Luflosi** [comment]
Are you using a Mac with a retina display? I imagine that the calculation does not take the higher pixel density into account.

**Comment by minusf** [comment]
yes, it is a retina macbook pro

**Comment by Luflosi** [comment]
How does the font size look compared to another app, say TextEdit? If you create a new TextEdit document with the same font and the same font size as kitty, does the font in kitty look about the same size or about half that size?
This is what it looks like for me:
![screenshot](https://user-images.githubusercontent.com/15217907/53887871-74419980-4023-11e9-9c11-f8498232168a.png)

**Comment by minusf** [comment]
it's the same
<img width="296" alt="screenshot 2019-03-06 at 15 33 25" src="https://user-images.githubusercontent.com/3632883/53888711-7e649780-4025-11e9-9741-1337b4ae189f.png">

**Comment by kovidgoyal** [comment]
what version of kitty is this?

**Comment by minusf** [comment]
(the version number in about is not copy pasteable btw 😸 )
```
$ brew cask info kitty
kitty: 0.13.3
https://github.com/kovidgoyal/kitty
/usr/local/Caskroom/kitty/0.13.3 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kitty.rb
==> Name
kitty
==> Artifacts
kitty.app (App)
```

**Comment by kovidgoyal** [comment]
sadly I dont have a retina mac to test with, but if it is indeed a retina issue the workaround is to simply change the numbers you specify by the appropriate factor.

**Comment by Luflosi** [comment]
Sadly I can't test this myself since I don't have any retina displays either.
@minusf Do you think you can compile kitty from source? If so, can you try to apply this patch please?
```diff
diff --git a/kitty/config.py b/kitty/config.py
index 4b72e7e1..b636d234 100644
--- a/kitty/config.py
+++ b/kitty/config.py
@@ -529,12 +529,13 @@ def initial_window_size_func(opts, cached_values):
     h, h_unit = opts.initial_window_height
 
     def get_window_size(cell_width, cell_height, dpi_x, dpi_y):
+        print(cell_width, cell_height, w, h, dpi_x, dpi_y, opts.window_margin_width, opts.window_margin_width, opts.window_padding_width, opts.window_padding_width)
         if w_unit == 'cells':
-            width = cell_width * w + (dpi_x / 72) * (opts.window_margin_width + opts.window_padding_width) + 1
+            width = (72 / dpi_x) * cell_width * w + (dpi_x / 72) * (opts.window_margin_width + opts.window_padding_width) + 1
         else:
             width = w
         if h_unit == 'cells':
-            height = cell_height * h + (dpi_y / 72) * (opts.window_margin_width + opts.window_padding_width) + 1
+            height = (72 / dpi_y) * cell_height * h + (dpi_y / 72) * (opts.window_margin_width + opts.window_padding_width) + 1
         else:
             height = h
         return width, height
```
It prints some debug information and if your dpi is 144, it should halve the size of your window. To see the debug information, run kitty like this after compiling: `kitty.app/Contents/MacOS/kitty`.

**Comment by minusf** [comment]
i can confirm that this fixes my issue:

```
$ ./kitty
16 30 40 15 144.0 144.0 1.0 1.0 0 0
```

and the window size is as expected with the `c` suffix parameters.

**Comment by Luflosi** [comment]
@minusf you can either compile kitty from the latest master or use the workaround described in https://github.com/kovidgoyal/kitty/issues/1444#issuecomment-470133885 and wait for the next version.

**Comment by minusf** [comment]
i can live with this until the next brew update, thanks :}
