### ISSUE TITLE
Font scaling under wayland

### ISSUE THREAD

**Issue by jeLee6gi** [kovidgoyal/kitty#1445]
This might be related to #1143 but I can reproduce it on a single monitor. The font of new kitty instances becomes much bigger after scaling changes even if you change scaling back.

Under a recent git version of sway, I can reproduce this by
1. opening kitty
2. in my case running the following two commands to change to HiDPI and back to my original scaling of 1
```
swaymsg output eDP-1 scale 2
swaymsg output eDP-1 scale 1
```
3. opening a new kitty instance which has a much larger font size than the original instance

This persists until I restart sway

**Comment by kovidgoyal** [comment]
Likely sway is reporting incorrect scaling values and/or the glfw wayland backend is buggy. I've outlined what to look for in the ayland backend in #1380 insert some prints into those functions to see what scaling/dpi is being reported.

**Comment by jeLee6gi** [comment]
Thanks for linking the other issue, the scaling issue actually goes away if I run kitty with `KITTY_ENABLE_WAYLAND=1`. Sorry, I didn't know about that flag, my fault!
