### ISSUE TITLE
Cannot find how to get the current font size within a kitten

### ISSUE THREAD

**Issue by eepp** [kovidgoyal/kitty#1446]
Is there an API to get the current global font size from a kitten? I see that `boss.py` uses `global_font_size()`, but the `fast_data_types` module does not seem to be imported within a kitten.

**Comment by kovidgoyal** [comment]
Inside handle_result() you can do anything boss.py can do. If you want to import fast_data_types you can do so. Note that this does not apply to main() which is run in a separate process.

**Comment by eepp** [comment]
Just to make it clear for future readers, you need to import from the `kitty` package, for example:

```
from kitty.fast_data_types import global_font_size
```
