### ISSUE TITLE
MacOS: "New OS window" creates an OS tab

### ISSUE THREAD

**Issue by matthewmazzanti** [kovidgoyal/kitty#1447]
Under MacOS 10.14.3/Kitty 13.3, when you create a new OS window through any method (shortcut, remote control, toolbar) it gets put into a MacOS managed tab rather than splitting off into a fully-qualified window. Ideally there would be some way to change the default behavior so that you can instead create a completely separate OS window rather than having the new window show up as a tab.

That said these tabs *are* technically full OS windows- they can be split off into top level windows by right clicking and selecting "Move Tab To New Window".  Mostly current default behavior just defies expectations as I expected to get two separate windows with the option, rather than get a new window in a tab.

**Comment by kovidgoyal** [comment]
I cannot replicate, creating new OS windows puts them in separate
windows, not OS tabs. The exception is fullscreen. When in fullscreen
mode new os windows become tabs -- this is something mandated by Apple,
not something that kitty does. There may be some cocoa API to disable
it, if so, patches are welcome for an option to control it.

**Comment by matthewmazzanti** [comment]
For future reference if anyone finds this:
It was the system preferences value "prefer tabs to windows when opening documents" under dock settings that was causing the "issue". Changing this will modify default behavior.
