### ISSUE TITLE
"kitty.app" would like to access the microphone

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#1449]
as far as i know i did not run anything in the terminal that would require this,
so i just put this here:

<img width="423" alt="screenshot 2019-03-08 at 16 19 50" src="https://user-images.githubusercontent.com/3632883/54037569-c3700180-41be-11e9-810f-294c86f3c154.png">

**Comment by kovidgoyal** [comment]
kitty does not contain any code to ask for microphone access. Feel free to grep its source code to confirm that.

**Comment by Luflosi** [comment]
I can confirm that kitty never asked me for microphone access and it doesn't appear in the settings in the list of apps that have microphone access.

**Comment by minusf** [comment]
i wonder how it would be possible to track this down and avoid the confusion.

**Comment by kovidgoyal** [comment]
Likely some process running inside kitty used the requestAuthorization cocoa API and since command line programs have no app bundles, cocoa found the closest app bundle it could in the process tree which would be kitty. Dont see what kitty can do to avoid that.
