### ISSUE TITLE
Can't select text on second display in areas above/below primary display

### ISSUE THREAD

**Issue by grugnog** [kovidgoyal/kitty#1451]
I have a second monitor that I keep in portrait mode. I am able to select text fine on my primary display, but on the secondary display I can only select text in the (vertical) center of the second display.

At the top or the bottom of the second display (i.e. above/below where the top/bottom of the primary display intersects the second) the cursor still changes to an I-beam, but no text is selected. If I drag a selection from the center upwards it stops selecting once it hits this boundary.

I am using wayland and sway-git and default kitty config.

**Comment by kovidgoyal** [comment]
I'm afraid I dont have multiple monitors to test with, so I can't really
help. One thing to do is make sure kitty is using its Wayland backend (set
KITTY_ENABLE_WAYLAND=1) or if it is using the wayland backend already,
switch to XWayland and see if that works better.

If that does not solve it, then you will need to look at the mouse
reporting code in the glfw wayland backend. Relevant files are
glfw/wl_window.c and kitty/mouse.c

**Comment by grugnog** [comment]
@kovidgoyal that did the job! Thank you so much for your help :)
