### ISSUE TITLE
Failsafe installer feature: let the user know what options are available to run kitty on ubuntu 16.04  

### ISSUE THREAD

**Issue by Petrox** [kovidgoyal/kitty#1453]
While I understand that this is the same result as #992 , closed with the comment: https://github.com/kovidgoyal/kitty/issues/992#issuecomment-422874567 , but I'd suggest to improve the installer to check for this condition, and give a hint (URL) how to solve.  

Also if kitty does not work on ubuntu 16.04 and it is a known limitation. ( as it seems to be the case https://github.com/kovidgoyal/kitty/issues/1125#issuecomment-437242603 ), then the script could just tell this to the user before downloading and trying and failing.

#595 seems to be the issue that should solve this, but it does not have a working solution. In either case the installer should be able to check for ubuntu xenial or the better for the version of the dependencies (freetype), and then let the user know what the situation is and that it is something the devs already know about, and that there are 1-2-3 options to choose from.

This would result in a better user experience even if the OS is not the favourite or most supported one. 

:1st_place_medal: 

````
$ uname -a
Linux op6 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

t$ dpkg --list *freetype6*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-==================================================================================================
ii  libfreetype6:amd64                             2.6.1-0.1ubuntu2.3           amd64                        FreeType 2 font engine, shared library files
ii  libfreetype6-dev:amd64                         2.6.1-0.1ubuntu2.3           amd64                        FreeType 2 font engine, development files


$ curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8249  100  8249    0     0   9493      0 --:--:-- --:--:-- --:--:--  9492
Using python executable: /usr/bin/python3
Checking for latest release on GitHub...
Will download and install kitty-0.13.3-x86_64.txz
Downloaded 8121640 bytes 
Extracting tarball...
kitty successfully installed to /home/petros/.local/kitty.app
Use /home/petros/.local/kitty.app/bin/kitty to run kitty
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 110, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 7, in <module>
ImportError: /home/petros/.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
````

Suggestion:

```
$ curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8249  100  8249    0     0   9493      0 --:--:-- --:--:-- --:--:--  9492
Using python executable: /usr/bin/python3
It looks like you have an old version (xxx) of freetype installed (required: [yyy]), please check link for possible solution: https://github.com/kovidgoyal/kitty/issues/595

```

Unfortunately: http://ubuntuhandbook.org/index.php/2017/06/install-freetype-2-8-in-ubuntu-16-04-17-04/ does not work anymore, the referred ppa has been removed.

**Comment by kovidgoyal** [comment]
Sorry, but I am not going to maintain a list of all possible historical distros and
distro versions that kitty does not work on. That way lies madness.
kitty works on the latest stable Ubuntu LTS release, and I believe as of
Ubuntu 18.10 it even has an official package.

**Comment by Petrox** [comment]
What I was trying to say is that the installer should verify whether the required dependencies exists or not.

There could be 12 or 1200 different dependencies, and checking those before dieing with an exception would the elegant way to do the install.

Exit with a stacktrace is not what an installer should do, by design. 

Of course it's your call, the issue was just an improvement suggestion.

**Comment by kovidgoyal** [comment]
You are welcome to contribute patches to the installer to do that. But the only way I know of to semi-robustly test if a dependency is of a required version is to either:

1) Use pkg-config which may not be present
2) Compile some test code which requires dev tools which may not be present
3) Dynamically load the library and check for version info (which is not reliable because distros often patch libraries with upstream patches without bumping version numbers)

Of the 3 approaches only number 3 is really workable and even there, cannot be made fully robust. And would need to be done for every possible library that kitty loads. Waaay too much work.

**Comment by Petrox** [comment]
It seems you have invested more time in this, I'll accept this as it is now, and will just come back when the OS upgrade happened. :) 

Thanks for your efforts on building a better terminal.

**Comment by mnn** [comment]
> Sorry, but I am not going to maintain a list of all possible **historical** distros and
> distro versions that kitty does not work on.

Version | Code name | Docs | Release | End of Standard Support | End of Life
-- | -- | -- | -- | -- | --
Ubuntu 16.04.6 LTS | Xenial Xerus | Changes | **February 28, 2019** | **April 2021** | April 2024

One line mentioning still a lot used version of most used distro would be nice. I don't like wasting my time and I imagine a lot of other potential users will be similarly annoyed and won't bother trying this project even after they upgrade.

**Comment by catskul** [comment]
Solution from #595 for convenience:
https://github.com/kovidgoyal/kitty/issues/595#issuecomment-504260295
> jberryman commented on Jun 20
> FWIW, on Debian stretch It looks like things are working after doing:
> 
>   * unpack the binary bundle from https://github.com/kovidgoyal/kitty/releases to ~/.local
>   * build harfbuzz from source (was very straightforward `./autogen.sh && ./configure && make`)
>   * copy the `libharfbuzz.so` you just built, overwriting `~/.local/lib/libharfbuzz.so.0`
