### ISSUE TITLE
Background color of wide glyphs

### ISSUE THREAD

**Issue by jmriego** [kovidgoyal/kitty#1455]
This is related to the issue #467. I'm using airline for vim and tmux instead of powerline but this would probably happen with any custom status line.

My issue is that I have a two different backgrounds color separated by a double-width glyph. After that glyph, there is a space (so it's detecting correctly that is a ligature and thus a wide glyph). The next space should be in a different background color but it's not doing so because of the special case that was introduced for powerline in #467.

![airline](https://user-images.githubusercontent.com/15045950/54122194-4928c280-43f4-11e9-8266-7297030d9ba8.png)

I was thinking of several solutions such as not doing that special case of duplicating the colors unless the change is exactly in the next space to the glyph. Probably the easiest way would be just to do the copy of the foreground color as the code is doing now but don't making any changes to the background color. That seems to work for both powerline and any custom line I have thought of

**Comment by jmriego** [comment]
Thanks a lot @kovidgoyal ! I agree with the comment in the code about powerline though :laughing:

**Comment by kovidgoyal** [comment]
Yeah I put that comment there coz I was annoyed at the time I had to make the workaround. But it is not nice to call someone else's hard work stupid, I need to learn to be nicer :)
