### ISSUE TITLE
Entering unicode characters with xdotool does not work

### ISSUE THREAD

**Issue by atx** [kovidgoyal/kitty#1456]
I have a script that types unicode characters using xdotool. Unfortunately this does not seem to work with kitty.

For example
```
xdotool key U2208
```

Types the ∈ character. This works in Qt and GTK applications but nothing happens with kitty (tested with 0.13.3 and the current master).

EDIT:

A hacky workaround can be done by inserting the character to the X clipboard and then emulating middle click. e. g.

```
echo "∈" | xclip
xdotool click --window $(xdotool getactivewindow) 2
```

Unfortunately it breaks if the mouse cursor is positioned in the wrong place on the focused window (for "normal" applications and presumably TUI programs that handle mouse clicks).

**Comment by kovidgoyal** [comment]
You want to send text to kitty use the remote control system, see https://sw.kovidgoyal.net/kitty/remote-control.html

Or use the send_text action in kitty.conf to bind arbitrary keyboard shortcuts to insert arbitrary text.

Or use the unicode input kitten https://sw.kovidgoyal.net/kitty/kittens/unicode-input.html

**Comment by eepp** [comment]
Question is: why does `xdotool` work with all the other applications, but not kitty? It is just too bad that I can't use any existing utility using `xdotool` to type a non-ASCII character.

I guess there could be a kitten which launches an external tool, waits for it to return, then inserts into the window what the other tool prints to its standard output?

**Comment by aearil** [comment]
I have to agree with @eepp, it really is inconvenient to have to setup two different methods of entering unicode characters: one for the whole system, and one just for kitty.

That isn't very user friendly.

**Comment by kovidgoyal** [comment]
Well feel free to figure out why whatever hack xdotool uses (XTEST,
IIRC) to insert text doesn't work with glfw (the toolkit kitty uses) and
submit a PR, I will be happy to merge it.

**Comment by atx** [comment]
Observation: on wayland, using [wtype](https://github.com/atx/wtype) everything works as expected. This is likely because the virtual-keyboard protocol emulates an actual keyboard instead of using some weird X server hack.

So maybe walking the path of progress and switching to wayland is the proper solution here :)
