### ISSUE TITLE
symbol_map seems doesn't work as expected

### ISSUE THREAD

**Issue by luokuning** [kovidgoyal/kitty#1458]
Hi there, I have installed [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) and wanted to display fancy icon in kitty. The 'fold' icon shown below which it's unicode point is `f115`:

<img width="122" alt="image" src="https://user-images.githubusercontent.com/12708534/54175445-e142ac80-44c5-11e9-9069-2f5a816f7a3b.png">

My kitty config is `symbol_map U+F115 Hack Regular Nerd Font Complete`, but when I run `echo '\uf115'`, kitty can not display the fold icon:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/12708534/54175515-2e268300-44c6-11e9-8480-9fd924032576.png">

and the debug message (`kitty --debug-font-fallback`) is like this:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/12708534/54175556-46969d80-44c6-11e9-8c8c-54dfceb95c91.png">

My environment is macOS 10.14.3.

Is there anything wrong with my kitty config?

**Comment by kovidgoyal** [comment]
Run

kitty --debug-font-fallback sh -c "echo '\uf115'; read"

and post the output

**Comment by luokuning** [comment]
Below is the output:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/12708534/54177854-ac872300-44ce-11e9-909c-84148fe8f69a.png">

It turns out that the font family name is incorrect (I was just simply copy the font file name from ` ~/Library/Fonts` 😅), so I change it to `symbol_map U+E000-U+E7C5,U+F000-U+FD46 Hack Nerd Font`, and everything works fine.

Thanks for quick reply.
