### ISSUE TITLE
Option for no pixel Sub Sampling

### ISSUE THREAD

**Issue by Anonrate** [kovidgoyal/kitty#146]
I've been working on a font for months now.  At first I was designing it for a 187ppi monitor, and now I've been doing it for a 108ppi monitor.

I absolutely Love Kitty.  It is so smooth when scrolling.  I really appreciate all your hard work and I thank you very much.

I noticed that in the terminal pixel sampling is going on and Ive tried changing the settings in KDE, I've even gone to designing a font that fits perfectly on the pixel grid at 96ppi at 12pt.   Is it possible to turn that off so it just renders the characters as they are?  If not, what about (And I know this has been asked already) adding support for bitmap fonts?  How much work would it require to implement that feature into Kitty?

**Comment by kovidgoyal** [comment]
I assume you are talking about linux. On linux kitty uses fontconfig + freetype to render. The problem with adding support for bitmapped fonts is that they are not scalable. kitty supports changing font size both via options and dynamically while running. Non-scalable fonts (and fitting fonts to a pixel grid in general) doesn't really work with that. font sizes are in pts and the final pixel size is calculated based on the point size and the DPI. 

That said you can probablyeasily customize your copy of kitty to use a fixed size font by changing a few lines in freetype.py/freetype.c As long as you specify a size that maps to the pixel size of the font and dont use the font size changing capabilities you should be fine.

**Comment by Anonrate** [comment]
What about the antialiasing?  Is there a way to turn that off?

**Comment by kovidgoyal** [comment]
Use something like https://www.gamedev.net/forums/topic/446204-freetype2--disable-anti-aliasing-effect/

**Comment by Anonrate** [comment]
Thank you very much.  I apologize if I was being a pest.

**Comment by kovidgoyal** [comment]
No problem. One of my goals is to keep kitty esily hackable precisely so people like you with use cases I cannot accomodate can make their own forks easily.
