### ISSUE TITLE
Kitty "spams" the clipboard when selecting text

### ISSUE THREAD

**Issue by teancom** [kovidgoyal/kitty#1460]
I use Alfred (https://www.alfredapp.com) for (among other things) clipboard history. When selecting text in kitty, it seems to "send" what is highlighted to the copy buffer every so often (multiple times a second) instead of waiting until the mouse is released. Here is a screenshot of my Alfred clipboard buffer after a single highlight of my `/etc/hosts`

<img width="343" alt="Screen Shot 2019-03-12 at 2 39 11 PM" src="https://user-images.githubusercontent.com/609527/54234429-b875e380-44d4-11e9-960e-dcc5d7e78178.png">

Expected behavior: kitty would only put text into the clipboard after the mouse is release.

**Comment by alepez** [comment]
Same here, I use gpaste on linux.

![image](https://user-images.githubusercontent.com/877244/54702427-1dfe4b80-4b37-11e9-8795-d3cf8b6274f2.png)
