### ISSUE TITLE
parse_kittens_shortcut not returning expected values?

### ISSUE THREAD

**Issue by taylorthurlow** [kovidgoyal/kitty#1465]
I started using [vim-kitty-navigator](https://github.com/knubie/vim-kitty-navigator) but its shortcuts aren't working. By default they are `ctrl+h/j/k/l`. I saw there was [an open issue](https://github.com/knubie/vim-kitty-navigator/issues/2) which I commented on. I dug around the source for the kitten, and I don't know much python, but I was able to see a few things that I may or may not be misunderstanding. I left them in a comment on the issue I linked, but I will rephrase them here:

My understanding of `parse_kittens_shortcut` is that it takes a string representation of the shortcut (lets say in this case, `"ctrl+j"`). It returns a tuple of:
* `mods` - is an integer representation of the modifier keys being pressed, 1, 2, 4, and 8, being shift, control, alt, and super, respectively. I expect that `mods` is the sum of the modifiers being pressed.
* `rkey` - I can't figure out what the r in rkey stands for, but it's essentially the key name without modifiers. In my example, just `j`.
* `is_text` - A boolean flag which says whether or not the shortcut is just some text being sent to the terminal or if it's an escape sequence of some sort?

Given an input of `ctrl+j`, I'd expect that `parse_kittens_shortcut` returns `(2, 'j', False)`. Please correct me if I make any incorrect assumptions.

Instead of getting that expected output, i get `(4, 'j', True)` instead. I won't bother you with the details of the implementation of the kitty itself, but the issues I have with the kitty seem to stem from the fact that this function is returning values I don't expect.

**Comment by kovidgoyal** [comment]
mods is a bitmap, you use & with it to test for a modifier. For example:

from kitty.key_encoding import CTRL
has_ctrl = CTRL & mods

rkey means resolved key and is just a value used to match key events
from kitty's keyboard protocol. See the diff kitten for an example.

is_text means if the key corresponds to one of the keys that are
reported as plain text by the keyboard protocol, thisis used when
matching key presses without modifiers.
