### ISSUE TITLE
clear_all_shortcuts disables shortcuts completely

### ISSUE THREAD

**Issue by zeorin** [kovidgoyal/kitty#1466]
[From the docs](https://sw.kovidgoyal.net/kitty/conf.html?highlight=clear_all_shortcuts#opt-kitty.clear_all_shortcuts):

> You can have kitty remove all shortcut definition seen up to this point. Useful, for instance, to remove the default shortcuts.

When I enable this option, all my shortcuts stop working.

Extract from my `kitty.conf`:
```
clear_all_shortcuts			yes
rectangle_select_modifiers	no_op
map kitty_mod+c				copy_to_clipboard
map kitty_mod+v				paste_from_clipboard
map kitty_mod+equals		change_font_size all +1.0
map kitty_mod+minus			change_font_size all -1.0
map kitty_mod+backspace		change_font_size all 0
map kitty_mod+u				input_unicode_character
```

I have also tried:
```diff
 clear_all_shortcuts		yes
+kitty_mod					ctrl+shift
 rectangle_select_modifiers	no_op
 map kitty_mod+c			copy_to_clipboard
 map kitty_mod+v			paste_from_clipboard
 map kitty_mod+equals		change_font_size all +1.0
 map kitty_mod+minus		change_font_size all -1.0
 map kitty_mod+backspace	change_font_size all 0
 map kitty_mod+u			input_unicode_character
```
With no change in behaviour.

`v0.13.3` (built from source on Ubuntu 18.04 from commit `fbccfb9`)

**Comment by Luflosi** [comment]
This seems to be an issue with the parser, if I replace all the tabs with spaces, it works for me.

**Comment by zeorin** [comment]
I can confirm that workaround works for me.

**Comment by Luflosi** [comment]
I'm making a pull request to fix it.

**Comment by Luflosi** [comment]
lol

**Comment by Luflosi** [comment]
You were faster 😄

**Comment by kovidgoyal** [comment]
yeah sorry I saw your message after I had already made the fix.

**Comment by Luflosi** [comment]
No problem. Your fix was much more complete anyways. I only fixed the parsing of the keyboard shortcuts. And I commented literally 30 seconds before you made your commit.

**Comment by janbaer** [comment]
I also have a problem with the redefinition of the keyboard shortcuts. In VIM I use Ctrl+Shift+L for a specific action. When I start VIM within Kitty, the keymapping is no longer working. After I saw this issue here, I also tried to **clear_all_shortcuts** and then just to define the shortcuts manually I want to use with Kitty. But in VIM my defined keymapping for Ctrl+Shift+L is still not working. When I use another terminal, it's working fine.

**Comment by Shmik2003** [comment]
I had the same problem. Replacing tabs and spaces doesn't worked for me, but when I added ; to end of line it's worked fine
![image](https://user-images.githubusercontent.com/35891761/75132110-c6714400-56e6-11ea-8ade-5ce73c0aab28.png)

**Comment by kovidgoyal** [comment]
There is no such thing as a mapping to ctrl+shift+l in vim. Run showkey -a in a terminal and you will see that ctrl+L and ctrl+shift+L generate the exact same bytes. The fact that you cannot use ctrl+shift in traditional terminal programs is the whole reason it is used as kitty_mod

**Comment by koaydemir** [comment]
I'm still having this problem. kitty 0.36.0. macos sonoma 14.6.1. adding clear_all_shortcuts yes on top of my config file breaks all shortcuts. Things like copy paste that are defaults, and all the shortcuts that i define AFTER clear_all_shortcuts, gets cleaned
