### ISSUE TITLE
Enhancement: Allow diffing of deleted files

### ISSUE THREAD

**Issue by io41** [kovidgoyal/kitty#1468]
Some tools pass in paths to files that have been deleted, when comparing files. Rather than display an error messages, such as `/path/to/deteled/file does not exist` on the console, it would be nice if kitty showed the before file on one side, and on the other side a message or symol such as `file deleted`.

One such tool that does this allows diffing the entire filesystem  before and after changes were made, such as a package installed / removed: http://snapper.io/tutorial.html

**Comment by kovidgoyal** [comment]
If you diff directories, removed files are shown as removed and added files shown as added. If you pass in file paths to diff on the command line, then the kitten considers it an error if one of the files is missing, which is desired behavior.

**Comment by io41** [comment]
Snapper is a tool used to see what's changed on the entire filesystem.

When it comes to diffing the entire filesystem, passing in the root isn't
really viable (the filesystem has millions of files), which is why snapper
passes all paths that have changed, including files that have been just
created.

Anyway, perhaps you're right, kitty isn't the right place to add the
functionality required to make snapper diffs more readable... At least not
directly. I'll think on it some more

Kovid Goyal <notifications@github.com> schrieb am Fr., 15. März 2019, 14:13:
