### ISSUE TITLE
window size flashes when focusing or defocusing under wayland

### ISSUE THREAD

**Issue by Hello71** [kovidgoyal/kitty#1473]
On master, with sway master and focus-follows-mouse, moving the cursor onto or away from a kitty window causes the window size to flash on the screen. I think this doesn't happen with 0.13.3.

**Comment by kovidgoyal** [comment]
Can you make a video of what is happening? In master kitty will show the screen size in cells, during a resize. But I see no reason for that to happen on mouse entr/exit. Is the size you are referring to a size on cells or something else? Does the kitty window blank all contents when showing this size?

**Comment by Hello71** [comment]
I assume it is the size shown on resize. It is "nnn x nn cells" in the middle of the window. During the few milliseconds it is displayed, the terminal contents are removed from the display. It does not occur if WAYLAND_DISPLAY is unset before launching kitty.

**Comment by kovidgoyal** [comment]
That would imply that sway is generating resize events with
focus-follows-mouse, seems like a bug there. To confirm simply add a
printf() to framebuffer_size_callback in glfw.c in kitty. That is the
function called for resize events, and that is where the cells indicator
is drawn.

**Comment by Hello71** [comment]
```
15:46 <Hello71> sway sends xdg_toplevel.configure on focusing a window. is this "a bug"?
15:46 <emersion> no, as we add the "active" state
15:48 <Hello71> I guess we're getting into wayland questions now, but are clients supposed to cache the old state then? https://github.com/kovidgoyal/kitty/issues/1473
15:52 <emersion> well, depends on the client
15:52 <emersion> if the client does special things on resize, it should only do it when the size actually changes
15:53 <emersion> there's no way to tell whether a configure event happens because the compositor requests a new size or because the state has changed
```

**Comment by kovidgoyal** [comment]
Sigh wayland really is a special snowflake, I will look into a workaround when I have moment.
