### ISSUE TITLE
Only background when launched, reversed characters after typing random commands.

### ISSUE THREAD

**Issue by lem0n4de** [kovidgoyal/kitty#1475]
Kitty can not render terminal correctly. When I open it, background is seen only and no text. After typing some command like ls, this happens.

![2019-03-16-180200_675x698_scrot](https://user-images.githubusercontent.com/34353293/54477227-f47fb000-4816-11e9-936a-7e2f0b50f9a1.png)

I updated my packages today, so I am guessing it has something to do with a dependency.

**Comment by kovidgoyal** [comment]
Use --debug-gl and --debug-font-fallback and post the output

**Comment by lem0n4de** [comment]
This is the output of both. There is no custom configuration.

> \>\>\> kitty --debug-gl --debug-font-fallback
[076 13:07:50.671390] Preloaded font faces:
[076 13:07:50.671463] normal face: /usr/share/fonts/TTF/DejaVuSansMono.ttf:0
[076 13:07:50.671504] bold face: /usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf:0
[076 13:07:50.671526] italic face: /usr/share/fonts/TTF/DejaVuSansMono-Oblique.ttf:0
[076 13:07:50.671571] bi face: /usr/share/fonts/TTF/DejaVuSansMono-BoldOblique.ttf:0
GL version string: '3.3 (Core Profile) Mesa 19.0.0' Detected version: 3.3

**Comment by kovidgoyal** [comment]
What graphics drivers do you have on your system? Why is the OpenGL version so old? 3.3 is from a decade ago. This looks like a driver issue. I'm guessing the system update broke something in your graphics stack.

**Comment by lem0n4de** [comment]
Today I reinstalled kitty again to try it and it seems issue is resolved. I did not change anything on the system.

**Comment by kovidgoyal** [comment]
dup of #1484
