### ISSUE TITLE
WARNING: unknown option: kitty --class

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1477]
While executing `make docs`, I got the following warning:
```
/path/to/kitty/docs/changelog.rst:391: WARNING: unknown option: kitty --class
```
This warning seems to have been introduced by 33f0ac83c1e5e247dc46caf33f36a534b2c0a836.
Is this warning platform specific? Maybe it only happens on macOS.

**Comment by kovidgoyal** [comment]
--class is a linux only option. Therefore this warning will happen on macOS.
