### ISSUE TITLE
Symbols flipping horizontally every 2 seconds or so

### ISSUE THREAD

**Issue by cr1sp1n** [kovidgoyal/kitty#1480]
Hello, I'm using Arch Linux and after an system upgrade I've got this strange bug, symbols appear to be flipping horizontally every 2 seconds or so.

![shot-2019-03-17_09-40-25](https://user-images.githubusercontent.com/3318534/54490994-92b45a00-4899-11e9-9594-7743760616d4.jpg)
Any hint of which kitty dependencies I should be looking at to solve this problem?

**Comment by Luflosi** [comment]
This is probably related to #1475. I can't help you with that, maybe @kovidgoyal can.

**Comment by kovidgoyal** [comment]
Its either freetype or the graphics drivers. Check what was updated recently.

**Comment by kovidgoyal** [comment]
I use arch myselfwith an intel graphics card and dont see anything after the latest update

**Comment by cr1sp1n** [comment]
Thanks!

I will look at which packages updated recently.

I'm also using an intel graphics, the kernel loaded driver is i915.

**Comment by kovidgoyal** [comment]
dup of #1484

**Comment by Luflosi** [comment]
Was there a comment that was deleted?

**Comment by cr1sp1n** [comment]
I don't remember if I deleted any comments, but related to this problem, it was solved after I ran the command with --debug-gl and --debug-font-fallback.

**Comment by Luflosi** [comment]
I didn't mean you, @cr1sp1n. I was just a little confused why @kovidgoyal wrote that this is a duplicate, because the last comment before that was from a month ago. I thought that maybe someone wrote another comment which he deleted again after @kovidgoyal commented.

**Comment by kovidgoyal** [comment]
Just doing some issue cleanup
