### ISSUE TITLE
Kitty on Wayland can hang from resizes

### ISSUE THREAD

**Issue by tarmack** [kovidgoyal/kitty#1482]
Since the addition of a resize indicator Kitty on Wayland is very prone to hangs (with the resize banner visible most of the time). It looks like having two resize events very close after each other might be triggering this. If I comment out `swap_window_buffers` from `framebuffer_size_callback` it works fine. 

The resize banner actually does not work at all on Wayland (or at least in Sway).

I am trying to find a solution for both problems but I got rather stuck now. Could I get some assistance with this?

**Comment by tarmack** [comment]
I have been able to stop the hangs by removing the "Fake resize event needed on weston to ensure surface is positioned correctly after DPI change" event. Maybe it is not needed anymore?

**Comment by kovidgoyal** [comment]
Can you give me some more information about your setup. What compositor are youusing? sway? what version? And I dont understand why the fake resize event wworkaround should matter since that is only supposed to be triggered if the DPI changes, which should not happen during a resize.

**Comment by tarmack** [comment]
Your fix does make sense for the scale changes in a previous pull request but it does not address the problem here. This issue was introduced with the introduction of the resize size indicator. The buffer swap in there is breaking things.
I attached a stacktrace from a hung kitty to help pinpoint the issue here.
[kitty_hang.txt](https://github.com/kovidgoyal/kitty/files/2990168/kitty_hang.txt) 

I am using Sway build from git. The reason a DPI change and a resize go together for me is because Sway is a tiling window system, so when the scale of the screen changes the size of all the windows require a change as well. There is no resize when I float the window and change the scale (this still does not result in a scale change for rendering in kitty without a resize or configure event but that is not important for this issue).

**Comment by kovidgoyal** [comment]
Well, I see no reason why calling swap buffers in a resize callback
should be a problem, but just for completeness I have moved the rendering
of the resize banner into the same function as renders the normal
window.

**Comment by tarmack** [comment]
This fixed the problem, and now also the resize banner actually shows up when resizing also. Thank you for taking the time in fixing this. The resize banner was a thing that I was looking forward to as an addition to Kitty. :)

**Comment by rumpelsepp** [comment]
Is this issue somehow related to this behaviour?

https://github.com/swaywm/sway/issues/3970
https://files.rumpelsepp.org/recording.mp4

Kitty is pretty much unusable as floating window on sway. The issue from the video disappears, when switching to `termite`. Any ideas? Do you need more data?

**Comment by kovidgoyal** [comment]
this issue refers to some changes on kitty master and has nothing to do with released kitty. If you are using released kitty, remember to set KITTY_ENABLE_WAYLAND=1 to use the wayland backend.

**Comment by rumpelsepp** [comment]
The flicker problem appears on the wayland backend with the latest released kitty and kitty from master (~ yesterday or so) as well.

**Comment by kovidgoyal** [comment]
I am not a sway user and given how many issues on Wayland are entirely
due to sway, I'm not particularly interested in debugging it.

I will say that there is no flickering with floating windows in weston.
You can try turning off sync_to_monitor in kitty.conf in case the issue
is caused by sway not sending render frames as expected.

**Comment by kovidgoyal** [comment]
I just installed sway 1.0 and ran kitty from master. Made the kitty window floating with mod+shift+space then ran htop in it, could see no flickering.

**Comment by rumpelsepp** [comment]
It only happens, when you make the window floating with a startup rule in the config:

```
for_window [title="^launcher$"] floating enable
```

Then start kitty with `kitty --title launcher`. To me it seems, that during the resize a few frames are not drawn.

**Comment by rumpelsepp** [comment]
I disabled vsync and now this happens:
https://files.rumpelsepp.org/recording2.mp4

**Comment by kovidgoyal** [comment]
Sorry its not clear to me what the flisker you are refering to is? All I can see is switching between various windows.
