### ISSUE TITLE
Multiple cursors when over multi-cell character using beam cursor shape

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1486]
While testing my PR #1479, I noticed, that kitty shows two cursors over wide characters when using the beam cursor shape.
Here are three screenshots with the cursor moving from the left to the right:
![Left beam](https://user-images.githubusercontent.com/15217907/54681827-a49e3300-4b0d-11e9-8804-5462c0dbc8f7.png)
![Double beam](https://user-images.githubusercontent.com/15217907/54681846-aff15e80-4b0d-11e9-84e4-cd7b6fd7f09a.png)
![Right beam](https://user-images.githubusercontent.com/15217907/54681865-b7186c80-4b0d-11e9-8b65-331dc17af496.png)
I guess this behaviour was introduced to make the block cursor fill the whole character and not just half of it. But for beam cursors, this is confusing.
Here are the first two screenshots again with a block cursor shape:
![Left block](https://user-images.githubusercontent.com/15217907/54681897-c8617900-4b0d-11e9-87c7-4539d86a13e1.png)
![Double block](https://user-images.githubusercontent.com/15217907/54681914-d0b9b400-4b0d-11e9-97e3-399326b3b6db.png)
But even with the block cursor, there is still a bit of an issue when the window isn't focused:
![Double block unfocused](https://user-images.githubusercontent.com/15217907/54682623-b8e32f80-4b0f-11e9-8ee1-39f6d53876cd.png)
I tested this in the commit for my PR and in v0.13.3.

**Comment by Luflosi** [comment]
The double beam cursor is fixed 👍
Could the block cursor be improved when the window doesn't have focus? It now looks like this:
![focus](https://user-images.githubusercontent.com/15217907/54697000-1d60b780-4b2d-11e9-9d1f-95a6f1f31300.png)
And with focus:
![no focus](https://user-images.githubusercontent.com/15217907/54697293-98c26900-4b2d-11e9-9a51-4d4be1a742c5.png)
How hard would it be to render it like in the last screenshot of my previous comment, just with the two middle rows of pixels removed?

**Comment by kovidgoyal** [comment]
cursors are rendered as sprites and there is a single
sprite index which means a double cursor has to have identical sprites.
To fix that you would need to use dual cursor sprites. IMO the
overhead/complication is not worth it.

**Comment by Luflosi** [comment]
Fair enough.
