### ISSUE TITLE
Some icon fonts aren't rendered correctly on Linux 

### ISSUE THREAD

**Issue by fdev31** [kovidgoyal/kitty#1487]
![shot](https://user-images.githubusercontent.com/238622/54718089-05ebf380-4b5a-11e9-81e0-fc013a6295ff.png)
Using linux with such fontconfig configuration:

```xml
  <family>Hack</family>
    <prefer>
      <family>Pomodoro</family>
      <family>FontAwesome</family>
      <family>Octicons</family>
      <family>Icomoon</family>
      <family>Symbols Nerd Font</family>
    </prefer>
```
Some fonts like the `Symbols Nerd Font` (from the archlinux package ttf-nerd-fonts-symbols) are showing two squares instead of a space after the icon:
![terminator](https://user-images.githubusercontent.com/238622/54717733-2c5d5f00-4b59-11e9-9be7-8efe162c1bdf.png)
vs
![kitty](https://user-images.githubusercontent.com/238622/54717740-32534000-4b59-11e9-87f2-1040e450830a.png)

It looks like the double size glyph is upscaled and the next space is taken from the wrong font file, which is missing the space glyph or have an incorrect definition probably.
Note the other terminal (reference screenshot) doesn't seem to handle double size glyphs.
A few icon fonts are producing this problem, is there a solution or an alternative to such fonts to get those glyphs?

**Comment by kovidgoyal** [comment]
Use symbol_map in kitty.conf to map the symbols directly to the desired fonts instead of relying on fontconfig. I doubt the issue is caused by an incorrect space glyph though. When a private use unicode codepoint is followed by a space, kitty will use the space cell to also render the PUA codepoint, allowing it to be as wide as needed.

**Comment by fdev31** [comment]
Unfortunately I don't see how it can fix my problem and a quick test confirmed it didn't change anything: the right font is already in use - I don't know any other glyph providing this symbol.

To be clearer I made another screenshot:

![shot](https://user-images.githubusercontent.com/238622/54781758-7c9df500-4c1d-11e9-8567-55011507ddb5.png)

**Comment by kovidgoyal** [comment]
I dont know what Symbols Nerd Font is, but if youwant to use the actual Nerd fonts with kitty you should be using 3270Medium Nerd Font Mono which corresponds to the current Nerd Font release https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/3270.zip

**Comment by fdev31** [comment]
Thank you for the tip!
For info the one installed here resolves as:
Nerd Font Complete.ttf: "Symbols Nerd Font" "2048-em"

**Comment by yannick1974** [comment]
Hi,

I have the same problem if I use this fontconfig replacement system (well, it may not be the right term, I mean the family→prefer→family as written in the first post) but not using the fully patched font from Nerd Font (in my case Fira Code / Fura Code).

**Comment by fdev31** [comment]
Using fontconfig fallback (as in my snippet) and changing the font to the
one recommended by Kovid works perfectly for me.

Le mar. 26 mars 2019 à 21:54, Yannick Roehlly <notifications@github.com> a
écrit :

**Comment by yannick1974** [comment]
Hi Fabien,

Do you mean you use the full font "3270Medium Nerd Font Mono" in the fallback instead of just the symbol font?

**Comment by fdev31** [comment]
Yes, which I stored in:
~/.local/share/fonts/TTF/3270-Medium\ Nerd\ Font\ Complete.ttf
since I'm not using one provided by the package manager anymore.

Also ensure you have no trace of the other font that could load first, you
can validate it on kitty using  "--debug-font-fallback" and at system level:

$ fc-match -a |grep Nerd
3270-Medium Nerd Font Complete.ttf: "3270Medium Nerd Font" "Medium"

In my fontconfig this font is the first prefered one:
```
    <prefer>
      <family>3270MediumNerdFont</family>
...
```

Le mer. 27 mars 2019 à 18:36, Yannick Roehlly <notifications@github.com> a
écrit :
