### ISSUE TITLE
Window title is not reset after using a kitten which changes it

### ISSUE THREAD

**Issue by eepp** [kovidgoyal/kitty#1488]
Steps to reproduce:

1. Press **Ctrl**+**Shift**+**u**. The window title changes to _Unicode input_.
2. Press **Escape**.

After pressing _Escape_, the window title stays _Unicode input_.

I see that another operation after that, like focusing another window and then returning, resets the window title.

My guess is that something should be done in `Handler.__enter__()` (`handler.py`) to keep the current window title (I don't how to do this, it's not available in `operations.py`; I guess it's a specific terminal command), and then reset it in `Handler.__exit__()`.

**Comment by kovidgoyal** [comment]
I cannot replicate with those steps. What OS/kitty version are you on? Unicode input happens in a separate
kitty overlay. When that overlay is closed, the OS window title is once
again taken from whatever window was underneath the overlay.

**Comment by Luflosi** [comment]
For me it's slightly different than what @eepp described. When the unicode input is closed, the tab title stays "Unicode input" but the OS window title is correctly updated. When doing something like switching to another tab or unfocusing the OS window, the tab title is updated.

**Comment by kovidgoyal** [comment]
Well the issue with the tab title I could replicate, it is now fixed.

**Comment by eepp** [comment]
> When the unicode input is closed, the tab title stays "Unicode input" but the OS window title is correctly updated. When doing something like switching to another tab or unfocusing the OS window, the tab title is updated.

That's exactly what I described. I didn't write _tab title_ because I thought the tab title is just the current window title anyway, so from my perspective, the window title is not reset when quitting the kitten.
