### ISSUE TITLE
weird - letters dancing ;)

### ISSUE THREAD

**Issue by cypa** [kovidgoyal/kitty#1489]
see this gif screencast
![foo](https://user-images.githubusercontent.com/807372/54760679-5e7ec780-4c12-11e9-80bb-102f41f2adf5.gif)
I've got this right after sysupgrade on my Archlinux lenovo Yoga 11e (chromebook), interesting on another my Archlinux laptop all looks OK with same sysupgrade ... weird

```
~λ kitty --version 
kitty 0.13.3 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
downgrade mesa to 18.3.4

**Comment by pehota** [comment]
Hi @kovidgoyal, 
Is downgrading mesa the only solution there will be or you're going to address this issue later on?
Thanks

**Comment by kovidgoyal** [comment]
It's a bug in mesa, how or why would I address it?

**Comment by Luflosi** [comment]
I don't see what @kovidgoyal could do about this other than to simply wait until mesa is fixed. According to #1484, which describes the same issue, The fix has been merged, so hopefully we will get a new version soon that doesn't have this problem anymore.

**Comment by pehota** [comment]
@kovidgoyal Thanks.
I am have zero knowledge about mesa and didn't know it was a bug. I just thought you had incompatibility of some sort that needed taking care of.
Thank you @Luflosi as well for the clarification. 
Only thing left to do is wait for the update.
Cheers
