### ISSUE TITLE
feature request: multiple windows

### ISSUE THREAD

**Issue by eldentyrell** [kovidgoyal/kitty#149]
Kitty uses "window" to mean what I usually see called a "pane" (i.e. a subdivision of a window, where window is the smallest unit managed by the OS window manager).  Setting that aside for a moment and using "frame" to mean "the smallest unit managed by the OS window manager"...

I'm accustomed to being able to press Command-N to open up a new frame.  I've kludged this into Kitty by having it double-fork-exec a copy of itself, but this probably isn't how you'd want it done so I haven't submitted a pull request for it.  Is this something you deliberately left out of kitty?  If not, is there a particular way you'd want to see it implemented?

**Comment by kovidgoyal** [comment]
kitty is designed to have only a single OS frame. You can launch as many kitty instances as you need to have multiple frames. The way to do it would be to define a global shortcut to launch a new kitty frame. For instance, in my environment I have bound the global shortcut windows key + Enter to launch a new kitty instance. 

I dont think this belongs in kitty itself, the correct place to define shortcuts to launch new instances of applications is in the desktop environment itself.

**Comment by kovidgoyal** [comment]
Oh and if you did want to implement it in kitty, it would get the bundle path using the cocoa api and launch it using 

```
/usr/bin/open bundle_path --args -d current_working_directory
```

and on linux, simply

```
kitty --detach -d cwd
```

**Comment by eldentyrell** [comment]
> /usr/bin/open bundle_path -F --args -d current_working_directory

Hrm, I didn't know about the -F argument to /usr/bin/open.

But it does not work "out of the box"; did you mean that invocation should be a starting point for adding the feature?

Also, the usage of --detach you point out is precisely why I opened #147

**Comment by kovidgoyal** [comment]
On Wed, Oct 18, 2017 at 10:39:49PM -0700, eldentyrell wrote:
> > /usr/bin/open bundle_path -F --args -d current_working_directory
> 
> Hrm, I didn't know about the -F argument to /usr/bin/open.
> 
> But it does not work "out of the box"; did you mean that invocation should be a starting point for adding the feature?

Yeah it is a starting point. 

> 
> Also, the usage of --detach you point out is precisely why I opened #147 

IMO it is better to use launch services, which takes care of setting up
all the coca process state rather than relying on --detach which knows
nothing about macs.

**Comment by thomasjachmann** [comment]
In case anyone stumbles upon this ticket from a search, I'll document here how I achieved the requested behaviour:

```
map cmd+n new_os_window
```
