### ISSUE TITLE
Wrong behaviour of regex groups and ? quantifier

### ISSUE THREAD

**Issue by dkasak** [kovidgoyal/kitty#1490]
It seems there's something weird going on with hint regexes that use groups and the `?` quantifier. I used a map like this

```
map kitty_mod+t      kitten hints --program - --type regex --regex "(foo)?123"
```

Expected: Pressing `kitty_mod+t` matches strings `foo123` and `123` and inserts whichever string is matched into the terminal.

Actual:  Pressing `kitty_mod+t` matches the string `foo123`, but *not* `123`. Notably, it also *does not* match the strings `foo` and `foo124`, so it seems it correctly requires the `123` suffix. Matching and selecting `foo123` inserts only the string `foo, however.

I also tried replacing `?` with `{0,1}`, but I get the same behaviour.

**Comment by kovidgoyal** [comment]
Use `(?:foo)?123` and you should be fine.

**Comment by kovidgoyal** [comment]
As is noted in the help for the --regex option, if you specify a group only the group will be matched. So in your case where you are using the group as a way to specify an optional prefix, use a non-capturing group.

**Comment by dkasak** [comment]
Thanks, I didn't think of non-capturing groups.
