### ISSUE TITLE
Setting tab title width?

### ISSUE THREAD

**Issue by ddddavidmartin** [kovidgoyal/kitty#1494]
Good day,

I was wondering whether there is a way of setting the tab title to a fixed width. The default is to expand the tab when the title is longer and I'd like to avoid that.

See for example this screenshot with different tab widths.

<img width="830" alt="Screen Shot 2019-03-25 at 1 03 19 am" src="https://user-images.githubusercontent.com/710898/54880565-f5a98080-4e99-11e9-8ebb-587dff8414d7.png">

Thanks!

**Comment by kovidgoyal** [comment]
Why would you want to leave unused available space?

**Comment by ddddavidmartin** [comment]
> Why would you want to leave unused available space?

I feel it helps with parsing the open tabs at a glance when they are all equally sized.

Though I have now worked with the tabs as they are for a bit and I may actually mind it a lot less than I initially thought. :)

**Comment by kovidgoyal** [comment]
I see, I dont really feel the need for this myself, but I will accept a
PR adding an option for it.
