### ISSUE TITLE
Font shifted up

### ISSUE THREAD

**Issue by FFY00** [kovidgoyal/kitty#1496]
Hi, I was thinking of moving to Kitty from Termite but I ran into some configuration problems.

![kitty-font-bug](https://user-images.githubusercontent.com/11718923/54883875-47ceaf80-4e62-11e9-8cc7-83328425136f.png)

Here we can see Termite (above) and Kitty (bellow). For some reason the characters are shifted up and bold.

My config:
```
font_family             CamingoCode Nerd Font Mono
font_size               11.0
bold_font               auto
italic_font             auto
bold_italic_font        auto

scrollback_lines        30000

background_opacity      0.9
foreground              #a1b0b8
background              #263238
color0                  #252525
color8                  #708284
color1                  #ff5252
color9                  #ff5252
color2                  #c3d82c
color10                 #c3d82c
color3                  #ffc135
color11                 #ffc135
color4                  #42a5f5
color12                 #42a5f5
color5                  #d81b60
color13                 #d81b60
color6                  #00acc1
color14                 #00acc1
color7                  #f5f5f5
color15                 #f5f5f5
```

**Comment by Luflosi** [comment]
It looks like you're using a different font for kitty and for Termite. The "n" for example has serifs in kitty but not in Termite. Are you sure both are using the same font?
Also, what is the output of `kitty list-fonts`? It should contain `CamingoCode Nerd Font Mono` if that's the font you want to use in kitty.

**Comment by Luflosi** [comment]
You can also try to run `kitty` from the command line and see if it prints any error messages.

**Comment by FFY00** [comment]
You're right. FOr some reason Kitty is not dettecting 'CamingoCode Nerd Font Mono'. Any ideas why?

**Comment by Luflosi** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font may help.

**Comment by FFY00** [comment]
Noted, thanks!

**Comment by Luflosi** [comment]
Did you manage to use CamingoCode? I installed CamingoCode from https://janfromm.de/typefaces/camingomono/camingocode/ on my system and it shows up in `kitty list-fonts`. To get your nerd font symbols back, you can use the very powerful font management available in kitty and use NerdFonts just for those symbols:
`symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B 3270Medium Nerd Font Mono`
Of course, you also need to install that font if it's not installed already (https://nerdfonts.com#downloads).

**Comment by FFY00** [comment]
I patched CamingoCode with Nerd Fonts but it isn't actually needed in Kitty because it does a great job at resolving symbols. Other terminals (and apps) don't so I had to patch the font.
