### ISSUE TITLE
Problems with clearing screen and moving scrollback when connected through SSH

### ISSUE THREAD

**Issue by ddddavidmartin** [kovidgoyal/kitty#1497]
Good day,

I'm using the mapping from the example config [0] to clear the terminal and move the scrollback up. This works fine when I'm working locally. But when I connect to a different machine via SSH it just prints the prompt again. It is as if I was just pressing enter.

Am I missing something obvious? The machines I connect to run Ubuntu or Debian and fairly standard zsh/bash.

Thanks!

[0] `map ctrl+l combine : clear_terminal scroll active : send_text normal,application`

**Comment by ddddavidmartin** [comment]
Ah, I just saw the [FAQ items on using kitty through SSH](https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer). Will try those.

**Comment by ddddavidmartin** [comment]
Okay, running `kitty +kitten ssh myserver` as mentioned in the FAQ works.

**Comment by ddddavidmartin** [comment]
Actually, when I run `kitty +kitten ssh myserver` CTRL+L clears the screen. But, it deletes the scrollback as well.

Is this intentional?

**Comment by kovidgoyal** [comment]
Ctrl-L simply sends the ctrl-L bytes to the shell. What happens next is up to the shell. If you want to have it always do something specific, then map it in kitty.conf. For example:

map ctrl+l clear_terminal clear active


see the kitty.conf docs for more examples.

**Comment by ddddavidmartin** [comment]
Thanks @kovidgoyal, I think what has been misleading me a bit is that my existing kitty.conf does not mention the `\x0c` after the command to both scroll and clear.

As in my kitty.conf looks as below:
```
#: It is also possible to remap Ctrl+L to both scroll the current
#: screen contents into the scrollback buffer and clear the screen,
#: instead of just clearing the screen::

#:     map ctrl+l combine : clear_terminal scroll active : send_text normal,application
```

I see in the repo that it mentions the correct form in config_data.py:
```
It is also possible to remap Ctrl+L to both scroll the current screen contents into the scrollback buffer
and clear the screen, instead of just clearing the screen::

    map ctrl+l combine : clear_terminal scroll active : send_text normal,application \x0c

```

Is this a bug in how the config file is written to disk? I only installed kitty yesterday with the curl invocation.

```
$ kitty --version
kitty 0.13.3 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/kitty/commit/e7099cc771c6f1c14fb5a809d4bb3a43f2b7acda
