### ISSUE TITLE
first line of terminal is black.

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#1498]
```
$ kitty -v
kitty 0.13.3 created by Kovid Goyal
$ uname -a
Linux Christopher 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux
$ awesome -v
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
When I open a new terminal the first line of my terminal shows a blank black line. as if something is masking the text. if I type asdf and press enter I get 
```
zsh: command not found: asdf
Christopher[19:39] ~$
```
in the second and third lines. if I open multiple windows only the first window has this issue and actually when I change the layout and type some stuff the first window renderes badly and some characters change. but if I select it it selects the right characters so it's a rendering problem. this problem is only for the first 2-3 lines. the first line of the first windows is always blank the second and third lines become badly rendered as I change the content of other windows. the other lines are just fine. if there is only a single window there is not rendering problems with the second and third lines. btw I have this issue even if I create 10 windows and then remove the first 8 windows. then the ninth windows with is now the first window gets bad rendering.
I don't recall having had this issue before. I just updated and restarted and figured I have this issue. I don't remember the last time I had an update. a month ago at most.

**Comment by kovidgoyal** [comment]
dup of #1484
