### ISSUE TITLE
Some shortcut mappings overridden by default mappings

### ISSUE THREAD

**Issue by FrancescoMagliocco** [kovidgoyal/kitty#1499]
So it seems only some shortcuts are effected by this.   I have copied and pasted the original config file and replaced `map ctrl+shift+backspace change_font_size all 0` with `map kitty_mod+0 change_font_size all 0` and using those keystrokes did nothing.  Using the original keystroke of <kbd>ctrl+shift+backspace</kbd> did work however.

I thought that maybe it was because I used <kbd>kitty_mod</kbd> rather than <kbd>ctrl+shift</kbd> so I tried using <kbd>ctrl+shift+0</kbd> but those keystrokes still did not work.  The original one once again did work just like last time.

I then thought that maybe it was because the mapping for `tenth_window` was `map kitty_mod+0 tenth_window` so I changed that to be <kbd>kitty_mod+1</kbd>.  Still the default key strokes would only work to reset the font size.

Starting kitty via `kitty -o "map=kitty_mod+0 change_font_size all 0` did work which made me think that maybe if I set the mapping to reset the font size as one of the first things in the config file, it will work.  So I went into my config file and as the first line I put `map kitty_mod+0 change_font_size all 0` and it finally worked.

**Comment by kovidgoyal** [comment]
I cannot replicate. Putting 

map kitty_mod+0 change_font_size all 0

at the start or the end of the config file makes no difference. It works
in either case. You likely have something else in your config file interfering.
