### ISSUE TITLE
Keyboard issues

### ISSUE THREAD

**Issue by vlisivka** [kovidgoyal/kitty#15]
All combinations below are working properly in gnome-terminal and mate-terminal. Some of them are working in rxvt too.

Ctrl-arrow jumps over words, like Alt-f/w in bash. Common combination since DOS times.

Shift-arrow selects text as cursor moves, ctrl-shift-arrow jumps over word and selects it in mceditor.

Ctrl-pgup/pgdown jumps to top/bottom of the current screen in mcedit without moving it.

Shift-del (cut), ctrl-ins (copy), and shift-ins (paste) are parts of IBM CUA guidelines since 1988. Only shift-ins is necessary to implement, because mouse selection is automatic (no need for ctrl-ins) and shift-del (cut) has no sense. Unlike ctrl-shift-v, shift-ins is pasting mouse (selection) buffer. I.e. I can select a text with mouse in Firefox and then immediately insert it with shift-ins (or middle mouse button or shift-middle if mouse is overriden by an application) in terminal.

Middle mouse button pastes mouse buffer. Shift-mouse click works when terminal program overrides mouse behavior. mc and mcedit are examples. 

Ctrl-arrow and ctrl-shift-arrow are huge performance boosts.

**Comment by kovidgoyal** [comment]
Again, if you want shift-ins/ctrl-ins you simply need to add them to your config. The default config hides all shortcuts behind ctrl+shift modifier so as not to interfere with programs running in the terminal (there is no way to pass the shift modifier to programs using ansi escape codes). And middle mouse button to paste as well as shift clicking to override mouse mode both work in kitty. 

bash by default *does not* use ctrl-arrow to jump over words, you need to add something like described here https://stackoverflow.com/questions/5029118/bash-ctrl-to-move-cursor-between-words-strings to your bashrc for that. You just need to use the right keycodes for the terminal you are using which you can get by using Ctrl-V followed by key press. However, I think there is indeed a bug in kitty where the escape sequences sent for ctrl+arrow key are the same as for only arrow key, I will look into that.
