### ISSUE TITLE
Consolas font clipped on macOS 10.12

### ISSUE THREAD

**Issue by bsuh** [kovidgoyal/kitty#150]
![image](https://user-images.githubusercontent.com/47231/31799202-98a54db6-b4ed-11e7-8fd3-d50cc65b1b5c.png)

Here's instructions to get this font https://gist.github.com/avalonalex/8125197

**Comment by bsuh** [comment]
This does not seem to be a problem on master. Any info when there would be a new release?

**Comment by bsuh** [comment]
I am wondering if this is a problem with launching Kitty.app vs running `python3 .` in the source folder. It seems that several things are not working correctly when launching Kitty.app. PATH environment variable misses some paths and bell is not working. How do I create a macOS application bundle from source? I tried `python3 setup.py osx-bundle`, but I don't see the bundle anywhere

**Comment by kovidgoyal** [comment]
There will be a new release soon probably within a week or so. Creating bundles from source is not easy, you have to setup the build infrastructure.
