### ISSUE TITLE
Nvidia Optimus messes up Kitty font-size when pluggin in external monitor

### ISSUE THREAD

**Issue by Nikki1993** [kovidgoyal/kitty#1500]
### Specs & Setup
I am gonna include all the info I think may or may not be relevant so apologies if smth happens to be irrelevant. 
Running Lenovo X1E with 4k screen that has 2 GPUs, Intel 630 and GTX 1050ti MAX-Q. 
Archlinux, Sway that is launched via .zprofile like this to support multi gpu setup so I can plug in external monitors.

`if [ "$(tty)" = "/dev/tty1" ]; then
        WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1 ssh-agent sway
        exit 0
fi`

Using modesetting driver for both + xf86-video-nouveau for nvidia gpu, both modules are done with early KMS with mkinitcpio.conf

`MODULES=(intel_agp i915 nouveau)`

I have consolefont module loaded asap to set ter-v32n (terminus-font) so I can see systemd-boot on a 4k without resorting to tiny fonts eye breaking experience. 

`HOOKS=(base consolefont udev autodetect modconf block keyboard encrypt lvm2 filesystems fsck)`

Kitty config

`
font_family      Iosevka Term
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
cursor_shape underline
enable_audio_bell yes
`

**All external output are wired to Nvidia GPU**

### Issue
When I plug in external GPU Kitty font increases to disproporational sizes, here is the comparison before I plug it in and after. 

![2019-03-25-192630_screenshot](https://user-images.githubusercontent.com/1446529/54940695-f2fb6980-4f33-11e9-9c2a-6ab798ccdbd7.png)

Any idea why it happens and how to tell kitty to not to do that?

**Comment by Luflosi** [comment]
@kovidgoyal could it be related to these likes: https://github.com/kovidgoyal/kitty/blob/e7099cc771c6f1c14fb5a809d4bb3a43f2b7acda/kitty/config.py#L536 ?

**Comment by kovidgoyal** [comment]
IIRC this is already fixed in master. Run kitty from HEAD and see if yu
can replicate. If so then re-open. Most likely, the compositor is
reporting incorrect scale values to kitty. See the
get_window_content_scale() function in glfw.c
