### ISSUE TITLE
[Question] --listen-on default address?

### ISSUE THREAD

**Issue by occivink** [kovidgoyal/kitty#1501]
Hi,

I've allowed remote control and would like to control a kitty terminal without explicitly specifying the address it should listen on. 
I presume that kitty is already listening on *some* address, considering that it is possible to simply do `kitty @` inside that terminal and it will auto-connect, but I could not find anything interesting in the environment. 
Is there a way to get this address, in order to use it from a separate context?

**Comment by kovidgoyal** [comment]
There is no default address. If you dont specify --listen-on kitty will
not listen on anything. Instead it will use escape codes as part of the
stdin/stdout streams to the child process for remote control.

**Comment by occivink** [comment]
I see, thank you for the clarification
