### ISSUE TITLE
Ability to detach and re-attach a window

### ISSUE THREAD

**Issue by alexherbo2** [kovidgoyal/kitty#1502]
Hi,

I would like to detach a window (make it an OS window), or re-attach a window to the last focused window.

I use this feature on [Chrome].  Here is a picture:

[![Detach and re-attach in Chrome](https://i.imgur.com/kEelbNt.gif)](https://imgur.com/kEelbNt)

[Chrome]: https://chromium.org

**Comment by kovidgoyal** [comment]
Not something I am interested in, but patches are welcome.

**Comment by trygveaa** [comment]
Off-topic: How do you do that in Chrome?

**Comment by alexherbo2** [comment]
Once a window has been created, can the window be moved to another window or its own OS window?

**Comment by kovidgoyal** [comment]
Sure, it can, in principle. It's just a bunch of book-keeping data
structures that have to be updated so that the window is moved from one
OS Window to another.

**Comment by alexherbo2** [comment]
@leonardt I configured Chrome to do that.

https://github.com/alexherbo2/configuration/tree/master/config/chromium/Default/Extensions/Configuration

**Comment by alexherbo2** [comment]
@trygveaa I configured Chrome to do that.

https://github.com/alexherbo2/configuration/tree/master/config/chromium/Default/Extensions/Configuration

**Comment by leon-volq** [comment]
@kovidgoyal Has anyone implemented this since this issue was created? I'm interested in at least the detach part.

If not, could you guide me a little bit on how could this be Implemented?

Thank you, great terminal

**Comment by kovidgoyal** [comment]
Long ago, see detach_window

**Comment by leon-volq** [comment]
Thank you very much, I should RTFD XD.   🙏
