### ISSUE TITLE
disable all tab-like functionality

### ISSUE THREAD

**Issue by mattp-** [kovidgoyal/kitty#1506]
my workflow is tmux with a fullscreen'd kitty per session. It seems there are two separate sets of tab systems in kitty, cmd-t for the in terminal tabs, and os-window tabs. I'd like to disable both. For the in-terminal it seems I can unbind the binds. for cmd-n, is it possible to disable that tabbing as well?

**Comment by kovidgoyal** [comment]
You'd have to ask apple. Those tabs come from cocoa. I vaguely recall
there being some setting somewhere you can use to turn them off.

**Comment by mattp-** [comment]
ah ok, didn't realize that. thank you!

**Comment by kovidgoyal** [comment]
Basically any full screen windows get displayed as tabs when there are more than one by cocoa.

**Comment by Luflosi** [comment]
See #1447.

**Comment by mattp-** [comment]
@Luflosi ah thank you
