### ISSUE TITLE
New kittens always start in home directory

### ISSUE THREAD

**Issue by alexherbo2** [kovidgoyal/kitty#1507]
**Example** – Create a new window:

``` sh
cd Documents/
kitty @ new-window
```

kitty creates a new window in home directory, instead of `Documents`.

**Comment by kovidgoyal** [comment]
kitty @ new-window --help

In particular, see --cwd

**Comment by alexherbo2** [comment]
I knew about `--cwd` option, but why does `kitty` honor the current directory (Default value of `--directory` being `.`) and not `kitty @ new-window`?

**Comment by kovidgoyal** [comment]
I dont know what you are asking. Why should kitty @ new-window honor the current directory? There is no a-priori reason to expect the user to open a new window in the same directory. Instead by default kitty will open a new widow with cwd set to whatever the cwd was for the kitty process.
