### ISSUE TITLE
Official release with recent changes?

### ISSUE THREAD

**Issue by ddddavidmartin** [kovidgoyal/kitty#1509]
Good day,

are you planning on releasing a newer version with the latest changes by any chance? I'd love to see [the clipboard fix](https://github.com/kovidgoyal/kitty/commit/cb095be0cc5f3a2ca560dd1474a62bc7aa2a5a46) included.

If not I'd have a look at building from source.

Thanks!

**Comment by kovidgoyal** [comment]
Not any time soon, kitty is trivial to build from source:
https://sw.kovidgoyal.net/kitty/build.html

**Comment by ddddavidmartin** [comment]
You are right, it was super easy to build. Thanks!
