### ISSUE TITLE
macOS: when running from source code, opening a link hangs the python process

### ISSUE THREAD

**Issue by bsuh** [kovidgoyal/kitty#151]
This doesn't seem to be a problem in the packaged DMG version.

**Comment by kovidgoyal** [comment]
I dont have a mac capable fo running kitty from source so I cannot test this, but I dont see what possible difference running from source would make. The relevant function is open_cmd() in utils.py. You can remove the wait() at the end of line 212, which should fix it. But the question is really why /usr/bin/open is hanging.

**Comment by bsuh** [comment]
The commit fixed it! Thanks.
