### ISSUE TITLE
scrollback lines mysteriously move around

### ISSUE THREAD

**Issue by Hello71** [kovidgoyal/kitty#1510]
On wayland with master, in some cases, lines of output (I think always complete lines, not parts of lines) reappear far from their original position. They behave, as far as I can tell, as if they were originally outputted there: scrolling around keeps them in the same relative position, even scrolling offscreen and scrolling back; copying and pasting gives the same output as on screen; show_scrollback shows the same output as on screen.

example after compiling Linux kernel and then emerging some packages:

```
>>> Emerging (20 of 20) dev-python/s3transfer-0.2.0::gentoo
>>> Installing (20 of 20) dev-python/s3transfer-0.2.0::gentoo
>>> Installing (17 of 20) media-libs/mesa-19.0.1::gentoo
>>> Installing (15 of 20) app-editors/neovim-0.3.4-r1::gentoo
>>> Jobs: 20 of 20 complete                         Load avg: 3.62, 4.43, 4.31
  AR      sound/parisc/built-in.a
 * Messages for package app-emulation/docker-18.09.4:
 * Log file: /var/log/portage/build/app-emulation/docker-18.09.4:20190329-210658.log

 *   CONFIG_CGROUP_FREEZER:      is not set when it should be.
```

The "AR" line mysteriously moved from thousands of lines prior down into the middle.

I think this problem may be related to exceeding the limit for the number of scrollback lines. It might also be related to large amounts of simulated backspacing (the "Load avg" display is maintained by repeated backspacing and re-printing).

I am fairly sure that this is a kitty bug, as I have seen it multiple times, in different contexts. I never saw it before when using alacritty or termite. I also never selected the text `AR      sound/parisc/built-in.a`, so I think it is not related to clipboard or some type of readback.

**Comment by kovidgoyal** [comment]
I am going to need some way to reproduce it. Reduce the value of scrollback_lines and write a script that does the thing you suspect of triggerring it

**Comment by Hello71** [comment]
Is there a way to save the original output from kitty? or should I use `script -t`?

**Comment by kovidgoyal** [comment]
I dont need the output, just a script and kitty.conf to reproduce. You
can use either --dump-bytes or --dump-commands as well instead of a
script if you prefer to re-create it manually. But a script is better.

**Comment by Hello71** [comment]
I suspect that this entails some sort of race condition. You think a fixed output will work?

**Comment by kovidgoyal** [comment]
yes, i do

**Comment by Hello71** [comment]
upon further testing, I strongly suspect that it involves rewrapping after resizing the window.

**Comment by kovidgoyal** [comment]
It's possible, but I am still going to need some way to reproduce. There
are quite a few tests for resizing in kitty_tests/screen.py look for
test_resize and test_cursor_after_resize.

**Comment by Hello71** [comment]
so, to be clear, `create_screen(scrollback=6)` refers to `scrollback_lines`, which is the number of real lines, not the number of displayed (wrapped) lines, right? and if that's the case, then resizing the window should never change the actual scrollback buffer, only its presentation on screen?

**Comment by kovidgoyal** [comment]
It is the number fo lines in the scrollback buffer, which has exactly
the same number of columns as the screen and is rewrapped on resize just
as the screen is re-wrapped.

**Comment by kovidgoyal** [comment]
no followup
