### ISSUE TITLE
Window/tab titles not updating when running commands

### ISSUE THREAD

**Issue by keyofnight** [kovidgoyal/kitty#1511]
When running different commands in Kitty, the window title and tab title do not update. 

I've tried to set the title in a few different ways: 

* When I use the keyboard shortcut, the tab's title updates but the window title does not. 

* Running `/Applications/kitty.app/Contents/MacOS/kitty --title "Foo"` sets the window/tab titles for the first window/tab open (as expected). 

* Both ` kitty @ set-window-title --match title:"bash"  foo` and ` kitty @ set-tab-title --match title:"bash" bar` also work as expected.

* Oddly enough, running `echo -ne "\033]0;"Title goes here"\007"` inside Kitty sets the window/tab titles just fine. Programs running in kitty will not, however.

* Both iTerm2 and Terminal.app change window/tab titles just fine.

**Comment by kovidgoyal** [comment]
If the echo command works then kitty is working fine. Whatever programs
you are using simply need to be told to use it to change window titles.
Presumably you either configured them in the past for iterm or they
auto-detect it based on the TERM value.

**Comment by keyofnight** [comment]
Oh. I see. Now I understand what you meant when you said (in #610):

> I find naming tabs by the process running in them rather wasteful, since most of the time they would show bash or vim or zsh or ssh. Instead tabs are automatically named by whatever title the terminal program running in the active window in the tab sets. Most modern shells, editors, etc have the ability to set this title builtin (though you may have to turn it on in the config).

As it turns out, I've never configured any of the programs I use to change window titles. My terms (Terminal.app, iterm2) have just been changing the title to the name of the running process is on their own. (Which, as you've said, is kinda useless.) I just added `set title` to my `.vim/vimrc`, and… wow… I've never seen these kinds of window title updates before.

Thanks for teaching me something I should've known already. 👍

**Comment by kovidgoyal** [comment]
You're welcome :)

Terminals are full of arcane little goodies waiting to be discovered.
