### ISSUE TITLE
IDE.

### ISSUE THREAD

**Issue by ECourant** [kovidgoyal/kitty#1513]
What IDE do you use to develop Kitty? Or do you have a preference? 

What tools do you use to debug (if you use a debugger at all)?

**Comment by Luflosi** [comment]
@kovidgoyal please correct me if I'm wrong.
I think he doesn't use an IDE, just vim.
Don't know about the debugger.

**Comment by kovidgoyal** [comment]
vim and no printf() + careful thought for debugging. I have been using
this combination to do all my development for almost 20 years now.
