### ISSUE TITLE
Random hangup on linux

### ISSUE THREAD

**Issue by troubas** [kovidgoyal/kitty#1515]
Since I have a new computer I've noticed random freezes of kitty where all open instances freeze and the openGL content bugs out (when changing workspace on i3 it keeps the content of the other workspace at that place -> no update ?).

I've cloned the repository and have been able to receive the following output:
```
ModuleNotFoundError: No module named 'kitty.update_check'
[091 16:36:22.878932] Failed to process update check data '', with error: invalid literal for int() with base 10: ''
```

I'll run again with `--debug` and hope that I will be able to provide more information.

Edit: I'm only able to close kitty with `kill -9`

**Comment by kovidgoyal** [comment]
downgrade mesa likely similar to #1484
