### ISSUE TITLE
regression on master: `double-click + drag` used to select a word, and then select new words as the cursor is dragged

### ISSUE THREAD

**Issue by nerdrew** [kovidgoyal/kitty#1516]
In version 0.13.3, `double click` would select a word, and then dragging would select more words. This seems to be broken on master.

**Comment by nerdrew** [comment]
Note: I do appreciate the fix for only copying the selection when the selection is complete :)

**Comment by kovidgoyal** [comment]
As far as I know, that was never an intended feature. If you wish to
extend a previous selection you can do it via right click. See https://sw.kovidgoyal.net/kitty/#mouse-features

**Comment by nerdrew** [comment]
Hmmmm. Too bad, I liked the unintended feature. I'll get used to the right-click replacement (though on an apple touchpad, right click isn't as natural).
