### ISSUE TITLE
Fonts keep rotating in weird directions every second

### ISSUE THREAD

**Issue by Docbroke** [kovidgoyal/kitty#1517]
I am using archlinux with i3-wm. This is first time I am using kitty. Configuration is default, only font sized changed to 16 for better view.
![image](https://user-images.githubusercontent.com/16881701/55377173-6ce1b300-5531-11e9-9d2e-bc411b7b6797.jpg)
![image0](https://user-images.githubusercontent.com/16881701/55377197-7f5bec80-5531-11e9-8ddf-c4ad994aab37.jpg)

**Comment by kovidgoyal** [comment]
dup of #1484
