### ISSUE TITLE
multi-key shortcuts unexpected behavior

### ISSUE THREAD

**Issue by FrancescoMagliocco** [kovidgoyal/kitty#1518]
### Starting Kitty via
```
kitty --config NONE -o "map=ctrl+shift+t new_tab" -o "map=ctrl+shift+t>ctrl+t new_os_window" -o "map=ctrl+shift+l change_font_size all +1" -o "map=ctrl+shift+t>ctrl+shift+l change_font_size all -1"
```
### Results in:

| Keypress                             	| What it does              	| What it should do         	|
|--------------------------------------	|---------------------------	|---------------------------	|
| <kbd>ctrl+shift+t</kbd>              	| Nothing                   	| `new_tab`                 	|
| <kbd>ctrl+shift+t>ctrl+t</kbd>       	| `new_os_window`           	| `new_os_window`           	|
| <kbd>ctrl+shift+l</kbd>              	| `change_font_size all +1` 	| `change_font_size all +1` 	|
| <kbd>ctrl+shift+t>ctrl+shift+l</kbd> 	| `change_font_size all -1` 	| `change_font_size all -1` 	|

Or if you press <kbd>ctrl+shift+t</kbd> then change your mind and just want to start typing, the first character you type will not be output.  
#### For example:
If you press <kbd>ctrl+shift+t</kbd> then start to type *'foo bar'*, only *'oo bar'* will be shown.
### Starting Kitty via
```
kitty --config NONE -o "map=ctrl+shift+t>ctrl+t new_os_window" -o "map=ctrl+shift+l change_font_size all +1" -o "map=ctrl+shift+t>ctrl+shift+l change_font_size all -1" -o "map=ctrl+shift+t new_tab"
```
<sup>**Note the order of** `-o "map=ctrl+shift+t new_tab"`  **Instead of being the first argument, it is the last one this time**</sup>
### Results in:

| Keypress                             	| What it does              	| What it should do         	|
|--------------------------------------	|---------------------------	|---------------------------	|
| <kbd>ctrl+shift+t</kbd>              	| `new_tab`                 	| `new_tab`                 	|
| <kbd>ctrl+shift+t>ctrl+t</kbd>       	| Nothing                   	| `new_os_window`           	|
| <kbd>ctrl+shift+l</kbd>              	| `change_font_size all +1` 	| `change_font_size all +1` 	|
| <kbd>ctrl+shift+t>ctrl+shift+l</kbd> 	| `change_font_size all -1` 	| `change_font_size all -1` 	|

The previous example applies for this situation as well.
### Possible Solution
Add a *Timeout* so if there is no keypress within a specified time frame, the next keypress will either trigger a different shortcut, or just output the text as is typed.

I'm sometimes not good at explaining things, if this is that case, I have provided a table giving examples for different scenarios.
#### Example:
Lets say we have the following configure file.
```
multi_key_timeout       300
map ctrl+shift+t        new_tab
map ctrl+shift+t>ctrl+t new_os_window
map ctrl+shift+t>f      move_tab_forward
```

<sup>**Note The *Before* and *After* represent *Before Timeout* and *After Timeout* respectively**</sup> 
<table>
  <tr>
    <th>First Keypress</th>
    <th colspan="2">Second Keypress</th>
    <th>Results</th>
  </tr>
  <tr>
    <td rowspan="2"><kbd>ctrl+shift+t</kbd></td>
    <th><sup>Before</sup></th>
    <td><kbd>ctrl+t</kbd><br></td>
    <td><code>new_os_window</code></td>
  </tr>
  <tr>
    <th><sup>After</sup></th>
    <td>No Keypress</td>
    <td><code>new_tab</code></td>
  </tr>
  <tr>
    <td rowspan="2"><kbd>ctrl+shift+t</kbd></td>
    <th><sup>Before</sup></th>
    <td><kbd>ctrl+shift+l</kbd></td>
    <td><code>change_font_size all -1</code></td>
  </tr>
  <tr>
    <th><sup>After</sup></th>
    <td><kbd>ctrl+shift+l</kbd></td>
    <td><code>change_font_size all +1</code></td>
  </tr>
  <tr>
    <td rowspan="2"><kbd>ctrl+shift+t</kbd></td>
    <th><sup>Before</sup></th>
    <td><kbd>ctrl+w</kbd></td>
    <td><code>close_tab</code></td>
  </tr>
  <tr>
    <th><sup>After</sup></th>
    <td><kbd>ctrl+w</kbd></td>
    <td><code>close_tab</code></td>
  </tr>
  <tr>
    <td rowspan="2"><kbd>ctrl+shift+t</kbd></td>
    <th><sup>Before</sup></th>
    <td><kbd>foo bar</kbd></td>
    <td><code>move_tab_forward</code> and <i>oo bar</i> is output</td>
  </tr>
  <tr>
    <th><sup>After</sup></th>
    <td><kbd>foo bar</kbd></td>
    <td><i>foo bar</i> is output</td>
  </tr>
  <tr>
    <td rowspan="4"><kbd>ctrl+shift+t</kbd></td>
    <th rowspan="3"><sup>Before</sup></th>
    <td><kbd>bar foo</kbd></td>
    <td><i>bar foo</i> is output</td>
    </tr>
  <tr>
    <th colspan="2"><sup>Notes</sup></th>
  </tr>
  <tr>
    <td colspan="2"><sup>The next keypress is <kbd>b</kbd>, and there is no mapping for <kbd>ctrl+shift+t>b</kbd>, so the timeout is automatically canceled.</sup></td>
  </tr>
  <tr>
    <th><sup>After</sup></th>
    <td><kbd>bar foo</kbd></td>
    <td><i>bar foo</i> is output</td>
  </tr>
</table>

**Comment by kovidgoyal** [comment]
I'm afraid I dont like timeouts, they are fiddly. You cannot combine an
action for a shortcut and also use it as the base for a multiey
shortcut. Instead do:

map ctrl+shift+t>t new_tab
map ctrl+shift+t>w new_os_window

As for the issue of the first character not being sent to the child if
it does not match a sequence, IIRC that was by design. I prefer to not
have random keys sent to the child if I accidentally press the wrong ey
during a multi-key sequence. If you change your mind during such a
sequence, simply press esc to abort it safely (assuming you dont map esc
as one of the sequence keys).
