### ISSUE TITLE
All child processes fail to launch

### ISSUE THREAD

**Issue by Jomik** [kovidgoyal/kitty#1519]
I get the following error trying to use `kitty +kitten ssh myserver`, and similar for `+complete` and the likes.
Even `kitty list-fonts` fails.

The error is sadly not very helpful to me, I know my setup is non-standard, as I am on NixOS, but I don't know what it is looking for, so I can not fix/patch it.

```
Failed to launch child: +kitten
With error: No such file or directory
Press Enter to exit.
```

```
➜ kitty --debug-config
kitty 0.13.3 created by Kovid Goyal
Linux tamaskan 4.19.32 #1-NixOS SMP Wed Mar 27 05:14:43 UTC 2019 x86_64
Running under: X11
<<< Welcome to NixOS 19.03beta171931.3a4ffdd38b5 (\m) - \l >>>

Run `nixos-help` for the NixOS manual.
Loaded config files: /nix/store/421whnqj91igvs6hmphyq84krldzcpr9-kitty.conf

Config options different from defaults:
background            Color(red=251, green=241, blue=199)
color0                Color(red=251, green=241, blue=199)
color1                Color(red=157, green=0, blue=6)
color10               Color(red=152, green=151, blue=26)
color11               Color(red=215, green=153, blue=33)
color12               Color(red=69, green=133, blue=136)
color13               Color(red=177, green=98, blue=134)
color14               Color(red=104, green=157, blue=106)
color15               Color(red=40, green=40, blue=40)
color2                Color(red=121, green=116, blue=14)
color3                Color(red=181, green=118, blue=20)
color4                Color(red=7, green=102, blue=120)
color5                Color(red=143, green=63, blue=113)
color6                Color(red=66, green=123, blue=88)
color7                Color(red=40, green=40, blue=40)
color8                Color(red=146, green=131, blue=116)
color9                Color(red=204, green=36, blue=29)
cursor                Color(red=80, green=73, blue=69)
cursor_blink_interval 0
cursor_text_color     None
font_family           Fira Code Retina
foreground            Color(red=40, green=40, blue=40)
scrollback_lines      10000
selection_background  Color(red=40, green=40, blue=40)
selection_foreground  Color(red=213, green=196, blue=161)
```
```

**Comment by kovidgoyal** [comment]
That indicates kitty is not running kittens but instead trying to open a
new window with +whatever as the program to run in it. Which will happen
only if you are running a very old kitty or you have one somewhere in
your path or the command line arguments being passed to kitty are
incorrect.

**Comment by Jomik** [comment]
@kovidgoyal so, I am running latest release, 0.13.3, and I only have that kitty in my path.
I am pretty certain it is a bit with my installation, as I use Nix.. But I would like to debug it, I just can't seem to get a more useful error message. Is there a way I can see what exact path it is trying to execute?

**Comment by kovidgoyal** [comment]
It tells you exactly what it is executing, in this case +whatever.

If you want to debug, look in the main() function in __main__.py
that is where it decides whether to run kitty itself or a kitten or
remote control, etc.

**Comment by Jomik** [comment]
@kovidgoyal I used `strace -vfefile kitty list-fonts` and it looks like it is using for a `list-fonts` executable in my PATH. And when I do `kitty +kititen ssh` it seems to look for a `+kitten` program in my PATH.

**Comment by kovidgoyal** [comment]
That is what I told you in my previous comment.

**Comment by Jomik** [comment]
Solved it. The error was that I had kitty linked to a script that looks like
```
#!/usr/bin/env bash
export PATH='/nix/store/rilqraca9bg9za56sb2shc8d00v0xmns-kitty-0.13.3/bin:/nix/store/4rkgha69h44gxpw4i4x96i1q2999khah-imagemagick-6.9.9-34/bin:/nix/store/p54kyqvkcxdjr4p2s7syanpinlzidv1v-xsel-unstable-2018-01-10/bin'${PATH:+':'}$PATH
 exec -a "$0" "/nix/store/rilqraca9bg9za56sb2shc8d00v0xmns-kitty-0.13.3/bin/..kitty-wrapped-wrapped"  --config /nix/store/421whnqj91igvs6hmphyq84krldzcpr9-kitty.conf "${extraFlagsArray[@]}" "$@"
```
I removed the `--config` flag and just set the `KITTY_CONFIG_DIR` environment variable instead.
Seems there is a bug if you call `kitty` with config and then try to launch any child.

**Comment by kovidgoyal** [comment]
--config is a commnd line option for kitty, not for kittens, which have their own unique set of command line arguments. Indeed, some of them have their own different config files. You cannot pass the kittyconfig arg to kittens, only to kitty itself.

**Comment by Jomik** [comment]
@kovidgoyal The `--config` option is being passed to `kitty`, not a kitten.

**Comment by kovidgoyal** [comment]
When you run kitty +whatever you are running a kitten not kitty.

**Comment by Jomik** [comment]
I ran `kitty --config /my/config/dir/kitty.conf +kitten ssh myserver` ..?

**Comment by Jomik** [comment]
Either way, it does work now, by not using `--config`, but the environment variable, so all is good :)

**Comment by kovidgoyal** [comment]
If you want to run a kitten you have to make + the first argument to
kitty. If you put it after --config it will not work.

So when you do

kitty --config x +kitten ssh

you are telling kitty to run itself using the config file x and starting
the program +kitten witht he arguments ssh

**Comment by Jomik** [comment]
@kovidgoyal Ah, that does make sense. So I can not pass a configuration file to kitty, if I want to run a kitten. But I guess it does not actually make sense to pass a config file when starting a kitten!
Thank you for clarifying!
And thanks for the terminal, it's awesome :+1:

**Comment by kovidgoyal** [comment]
You're welcome :)

**Comment by alephnull** [comment]
I want to launch a new kitty os window running the ssh kitten _and_ pass some command line arguments to the containing kitty, so I came up with:
```
alias goto='kitty -o background_image=${bg_img} -o background_image_layout=scaled +kitten ssh $*'
```
`$bg_img` is generated on the fly and is different for each host (it is an image of the hostname). Alas, the limitation of not being able to pass dynamic config to the kitty invocation when also launching a kitty gets in the way. The options parsing code is quite hairy but I think https://github.com/kovidgoyal/kitty/blob/master/kitty/cli.py#L514 is the condition that decides if we should go into "kitten mode" or proceed as normal.

**Comment by kovidgoyal** [comment]
if you want to run the ssh kitten inside a new kitty, you do this:

```
kitty --config whatever -o whatever -o whatever kitty +kitten ssh whatever
```

**Comment by alephnull** [comment]
Apologies for the necro-bump, but not sure if a new issue is appropriate when the behaviour is intentional.

**Comment by kovidgoyal** [comment]
What behavior?? I showed you how to pass dynamic config to kitty when running a kitten inside a new kitty instance.

**Comment by alephnull** [comment]
I posted that on a stale form that had not been refreshed. Your fix works, got lost in a maze of kitty invocations :)

**Comment by spik3** [comment]
I'm tring to install Kitty to pi and I get this popup.   Failed to execute child process "/home/pi/.local/kitty.app/bin/kitty" (No such file or directory) it would be great to sort this out.
