### ISSUE TITLE
macOS: Cannot use Command (AKA super) key in key mapping

### ISSUE THREAD

**Issue by bsuh** [kovidgoyal/kitty#152]
I bisected and ever since e8a1ada5bfa4db9 key mappings containing super modifier key do not work.

**Comment by kovidgoyal** [comment]
Are you sure that's the actual commit? i.e. does it work on the previous commit. Because I can see nothing there that would single out the super key as oppsd to the other keys. And the super key continues to work on my linux machine.

**Comment by bsuh** [comment]
Yes that is the actual commit. I've narrowed it down to the actual hunk as well.
```
@@ -280,7 +311,7 @@ with open(
     defaults = parse_config(f.readlines(), check_keys=False)
 Options = namedtuple('Defaults', ','.join(defaults.keys()))
 defaults = Options(**defaults)
-actions = frozenset(defaults.keymap.values())
+actions = frozenset(a.func for a in defaults.keymap.values())
```

If I revert this portion, the key mapping starts working again, which is
```
map super+t        new_tab
```

Here is a video showing when I check out e8a1ada, the shortcut stops working https://www.youtube.com/watch?v=DdO5q2TWLko&feature=youtu.be where as the parent 73b6cc4 works fine. You can see the keys being typed in the top right corner.

**Comment by bsuh** [comment]
I am not sure that is the correct fix. If the custom mapping contains arguments, then would it also not get set because an action with the same func name and same args does not exist in the default keymap. Shouldn't `actions` remain a set of func names and https://github.com/kovidgoyal/kitty/blob/master/kitty/config.py#L336 be
```
 if v.func in actions:
```

Maybe https://github.com/kovidgoyal/kitty/blob/master/kitty/config.py#L333 should be changed as well, I am not sure how noop works though.

**Comment by kovidgoyal** [comment]
Yeah I realized that and already fixed it in https://github.com/kovidgoyal/kitty/commit/70bfe8589f68513a0c3231429c6402b02f908688
