### ISSUE TITLE
BrokenPipeError when enabling completion in bash

### ISSUE THREAD

**Issue by WillEccles** [kovidgoyal/kitty#1520]
### Specs:

- Kitty 0.13.3
- MacOS 10.14
- Using bash

### My .bashrc:

I use this same file on multiple systems, so I have a quick conditional to check for Kitty, which then enables completion as specified in the docs:

```
if [ "${TERM}" = "xterm-kitty" ]; then
    source <(kitty + complete setup bash)
fi
```

### Output:

Upon either launching a new instance of Kitty or doing `source .bashrc`, I get the following error:

```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> BrokenPipeError: [Errno 32] Broken pipe
```

I am not sure what this error really means, nor how to fix it. I'm not a huge Python guy, so after a cursory glance at `complete.py`, I was unable to find where this error likely arises from. This is not a huge deal, since I haven't really got any clue how Kitty's completion would help me much, since I have never used it, but it would be nice to be able to try it.

### Debug Config:

```
~  kitty --debug-config
kitty 0.13.3 created by Kovid Goyal
Darwin <redacted hostname> 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:        10.14 BuildVersion:     18A391
Loaded config files: /Users/willeccles/.config/kitty/kitty.conf
[092 13:39:33.797861] The option macos_hide_titlebar is deprecated. Use hide_window_decorations instead.

Config options different from defaults:
active_border_color                Color(red=184, green=184, blue=184)
allow_remote_control               True
background                         Color(red=40, green=42, blue=54)
color1                             Color(red=255, green=85, blue=85)
color10                            Color(red=90, green=247, blue=142)
color11                            Color(red=244, green=249, blue=157)
color12                            Color(red=202, green=169, blue=250)
color13                            Color(red=255, green=146, blue=208)
color14                            Color(red=154, green=237, blue=254)
color15                            Color(red=230, green=230, blue=230)
color2                             Color(red=80, green=250, blue=123)
color3                             Color(red=241, green=250, blue=140)
color4                             Color(red=189, green=147, blue=249)
color5                             Color(red=255, green=121, blue=198)
color6                             Color(red=139, green=233, blue=253)
color7                             Color(red=191, green=191, blue=191)
color8                             Color(red=77, green=77, blue=77)
color9                             Color(red=255, green=110, blue=103)
cursor                             Color(red=172, green=172, blue=172)
cursor_stop_blinking_after         0
enable_audio_bell                  False
font_family                        Operator Mono Medium
font_size                          12.0
foreground                         Color(red=248, green=248, blue=242)
inactive_border_color              Color(red=38, green=38, blue=38)
kitty_mod                          8
macos_quit_when_last_window_closed True
macos_titlebar_color               1
selection_background               Color(red=68, green=71, blue=90)
selection_foreground               Color(red=248, green=248, blue=242)
symbol_map                         {(57504, 57506): 'Fira Code', (57520, 57523): 'Fira Code'}
window_margin_width                4.0
window_padding_width               4.0
Added shortcuts:
         control+alt+1 KeyAction(func='goto_layout', args=['tall'])
         control+alt+2 KeyAction(func='goto_layout', args=['stack'])
```

**Comment by kovidgoyal** [comment]
That error means kitty could not write to stdout. I suggest you run 

kitty +complete bash > kitty-completions

The source kitty-completions in your bashrc directly. This has the
advantage of being a bit faster as well.

As for why it is happening, probably something in your bash config, hard
to say.

**Comment by WillEccles** [comment]
> I suggest you run
> 
> kitty +complete bash > kitty-completions
> 
> The source kitty-completions in your bashrc directly. This has the
> advantage of being a bit faster as well.

Interesting. I just tried this, and it seems to be going on forever, whatever it's doing:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/3360049/55506804-5b2d0800-5624-11e9-9be6-197fa255ef0f.png">

**Comment by WillEccles** [comment]
Okay, I gave it another minute or so and then cancelled it. A quick `less kitty-completions` confirms there's nothing in the file either.

**Comment by kovidgoyal** [comment]
I dont see how it could possibly be going on forever, its just outputting
a fixed string. It is literally three lines of code. 

In any case, here is what you need in kitty-completions:

```bash
_kitty_completions() {
    local src
    local limit
    # Send all words up to the word the cursor is currently on
    let limit=1+$COMP_CWORD
    src=$(printf "%s
" "${COMP_WORDS[@]: 0:$limit}" | kitty +complete bash)
    if [[ $? == 0 ]]; then
        eval ${src}
    fi
}

complete -o nospace -F _kitty_completions kitty
```

**Comment by WillEccles** [comment]
I wrote that file manually and then sourced it manually and it isn't giving me any errors, though I don't know how kitty completion works yet, so I'm not sure if it is doing anything to be honest. Thanks for the help!

**Comment by kovidgoyal** [comment]
You're welcome and to see completion in action type kitty space and then
press tab. Although completion is typicallyfancier in more advanced
shells such as zsh and fish. Completion is most useful when using
remote control.

**Comment by davegregg** [comment]
For the record, I'm experiencing the exact same set of scenarios as @WillEccles.
1. The same BrokenPipeError exception.
2. The same unterminating behavior from executing `kitty +complete bash > kitty-completions`. Here is the traceback I get after I force termination with Ctrl-C:
```
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 108, in main
  File "kitty/__main__.py", line 68, in namespaced
  File "kitty/__main__.py", line 39, in complete
  File "kitty/complete.py", line 376, in main
```

**Comment by sterpe** [comment]
@kovidgoyal @WillEccles @davegregg 

Bash `source` [doesn't work](https://lists.gnu.org/archive/html/bug-bash/2006-01/msg00018.html) with process substitution.

Work around is to use this.

```
if [ "${TERM}" = "xterm-kitty" ]; then
  source /dev/stdin <<<"$(kitty + complete setup bash)"
fi
```

**Comment by sterpe** [comment]
@davegregg 

> The same unterminating behavior from executing kitty +complete bash > kitty-completions

Should be `kitty + complete setup bash > kitty-completions`
