### ISSUE TITLE
kitty on wayland

### ISSUE THREAD

**Issue by mmdmine** [kovidgoyal/kitty#1525]
Hi
I have a minimal archlinux installation on my usb stick.
it includes base system, kitty, and sway.
I know kitty supports wayland, as the kitty package depends on wayland and I've found an article that introduces kitty as 'Best Terminal Emulator for Wayland',
However, I'm unable to start kitty on sway, I get this error:
```
[093 19:22:51.244448] [glfw error 65544]: X11: Failed to open display 
GLFW initialization failed
```
I didn't found anything about 'forcing kitty to use wayland instead of X11', So I came here to ask about that.
the variable WAYLAND_DISPLAY is wayland-0. I tried GDK_BACKEND=wayland but it does no effect.
I've also installed glfw-wayland.
kitty is v0.13.3.
Also being able to use kitty as a stand-alone wayland compositor without sway or anything else is good, as it provides Tabs and a tiling windows.

**Comment by kovidgoyal** [comment]
Set 

KITTY_ENABLE_WAYLAND=1

Or run kitty from master where that env var is not required anymore.

**Comment by EvanCarroll** [comment]
Is there a way to force xorg backend @kovidgoyal ?

**Comment by kovidgoyal** [comment]
linux_display_backend

On Wed, Jun 10, 2020 at 09:20:05PM -0700, Evan Carroll wrote:
> Is there a way to force xorg backend @kovidgoyal ?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/1525#issuecomment-642396637

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by EvanCarroll** [comment]
Yep, I just found out right after I asked that question! Awesome. This is great and super useful since nothing can screen share on wayland.
