### ISSUE TITLE
First line appears random and animates

### ISSUE THREAD

**Issue by fdev31** [kovidgoyal/kitty#1528]
On one of my systems using an integrated intel (haswell) chip, after a software upgrade I get such first lines on each terminal:
![shot](https://user-images.githubusercontent.com/238622/55683852-b02e8e00-5944-11e9-876e-46f578d439f2.png)
![shot2](https://user-images.githubusercontent.com/238622/55683853-b02e8e00-5944-11e9-8cd9-822a0adb92f4.png)

Also usage of background_opacity will lead to a completely random "animated" output.
- on other systems the exact same software setup "works"
- with the  default kitty configuration I experience the same

**Comment by kovidgoyal** [comment]
dup of #1484
