### ISSUE TITLE
Purpose of index_type

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1530]
I was wondering what the purpose of the `index_type` datatype is. It is defined as `unsigned int`. Is it used to make it clearer what a variable is used for? Or maybe to make changing the datatype to something bigger in the future easier if the need arises? However there are places in the code where `index_type` is not used consistently, making it much harder to change what `index_type` is.

**Comment by kovidgoyal** [comment]
For both reasons.

**Comment by Luflosi** [comment]
How exactly do you decide when to use `index_type` and when to use `unsigned int`? Should the `Cursor` `x` and `y` position be an `index_type` for example?

**Comment by kovidgoyal** [comment]
Sure they could be, they are likely unsigned int because that structure
was defined from before index_type was created and I didn't bother to
port it.
