### ISSUE TITLE
kitty --help does not use alternate screen mode

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1531]
`kitty --help` has a `less`-like interface but does not use the alternate screen mode. I'm still able to scroll in the scroll back buffer and when pressing <kbd>q</kbd> to quit, the help text isn't cleared from the screen.

**Comment by kovidgoyal** [comment]
kitty --help uses less. See line 277 of cli.py

**Comment by Luflosi** [comment]
Removing the `-X` option of `less` fixes my issue. What was the reason for using that option?

**Comment by kovidgoyal** [comment]
Because I want to be able to browse the history in the terminal even
after quitting less.

**Comment by Luflosi** [comment]
Ok, I don't see an easy way to keep the history while allowing normal scrolling in less.
