### ISSUE TITLE
Unicode input inputs <00> for symbol map glyph

### ISSUE THREAD

**Issue by sethwoodworth** [kovidgoyal/kitty#1532]
I created a single glyph font named hack-lcars which contains a block symbol.
When I set the font via symbol map `symbol_map U+E000 hack-lcars` and go to insert it with the unicode input screen the glyph shows up as expected:
![kitty1](https://user-images.githubusercontent.com/123998/55921061-33f8ac80-5bc9-11e9-8d39-3512362bd6ca.png)
But when I select the glyph, it inputs `<00>` into my terminal instead.
![kitty2](https://user-images.githubusercontent.com/123998/55921066-378c3380-5bc9-11e9-8ae5-85de1fe12190.png)

I'm running kitty 0.13.3 on Linux, I can upload my custom font somewhere, but given that it renders in the unicode input screen, I'm not sure if it's relevant.

**Comment by sethwoodworth** [comment]
[hack-lcars.ttf.gz](https://github.com/kovidgoyal/kitty/files/3066295/hack-lcars.ttf.gz)
(I figured out I needed to gzip the font to be able to upload it)

**Comment by sethwoodworth** [comment]
Actually, it only inputs `<00>` in zsh, I can input the character as expected in vim and in bash, so this is likely not a kitty issue

**Comment by kovidgoyal** [comment]
This is a zsh issue. zsh replaces characters ti does not understand with hex escapes.
