### ISSUE TITLE
Feature request: option for hide mouse on keypress event

### ISSUE THREAD

**Issue by crichardson332** [kovidgoyal/kitty#1534]
It would be really nice if the user could enable an option to instantly hide the mouse cursor on any keypress event in the active window. That way you could click inside a window, and as soon as you start typing in your terminal, the mouse cursor disappears. This feature is enabled by default in many other terminal applications like iTerm2. Right now the user has to hack this feature in by setting the mouse_hide_wait param to be very small, which has unintended effects if you're actively using the mouse.

**Comment by kovidgoyal** [comment]
Not worth the effort to me, but patches are welcome.
