### ISSUE TITLE
vim-airline vim-devicons Fira Code

### ISSUE THREAD

**Issue by ecx** [kovidgoyal/kitty#1536]
Default linux ubuntu, installed: vim + vim-airline + vim-devicons (nerd fonts pack installed too), installed Fira Code fonts with `sudo apt install fonts-firacode`

when I enter for editing file in kitty:

![Снимок экрана от 2019-04-12 22-59-05](https://user-images.githubusercontent.com/467270/56063020-d1ddaa00-5d76-11e9-92ac-d0d0e33864ee.png)

same in gnome terminal:

![Снимок экрана от 2019-04-12 23-02-34](https://user-images.githubusercontent.com/467270/56063111-179a7280-5d77-11e9-8648-de1350a6781e.png)

kitty --debug-config
```kitty 0.13.3 (8969206450) created by Kovid Goyal
Linux eax-Z270-HD3 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
Running under: X11
Ubuntu 18.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
Loaded config files: /home/eax/.config/kitty/kitty.conf

Config options different from defaults:
font_family Fira Code
font_size   19.0
symbol_map  {(57504, 57506): 'PowerlineSymbols', (57520, 57523): 'PowerlineSymbols'}
```

kitty --debug-font-fallback
```[102 23:04:01.639009] Preloaded font faces:
[102 23:04:01.639042] normal face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[102 23:04:01.639067] bold face: /usr/share/fonts/woff/firacode/FiraCode-Bold.woff:0
[102 23:04:01.639080] italic face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[102 23:04:01.639089] bi face: /usr/share/fonts/woff/firacode/FiraCode-Bold.woff:0
[102 23:04:01.639098] Symbol map faces:
[102 23:04:01.639106] /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf:0
[102 23:04:02.055341] [PARSE ERROR] Unknown OSC code: 7
U+e61e Face(family=FuraMono Nerd Font Mono, style=Regular, ps_name=FuraMonoNerdFontCompleteM-Regular, path=/home/eax/.local/share/fonts/NerdFonts/Fura Mono Regular Nerd Font Complete Mono.otf, index=0, is_scalable=True, has_color=False, ascender=1050, descender=-350, height=1400, underline_position=-100, underline_thickness=50) (new face)
U+e61e Face(family=FuraMono Nerd Font Mono, style=Regular, ps_name=FuraMonoNerdFontCompleteM-Regular, path=/home/eax/.local/share/fonts/NerdFonts/Fura Mono Regular Nerd Font Complete Mono.otf, index=0, is_scalable=True, has_color=False, ascender=1050, descender=-350, height=1400, underline_position=-100, underline_thickness=50)
U+e712 Face(family=FuraMono Nerd Font Mono, style=Regular, ps_name=FuraMonoNerdFontCompleteM-Regular, path=/home/eax/.local/share/fonts/NerdFonts/Fura Mono Regular Nerd Font Complete Mono.otf, index=0, is_scalable=True, has_color=False, ascender=1050, descender=-350, height=1400, underline_position=-100, underline_thickness=50)
U+2630 bold Face(family=DejaVu Sans, style=Bold, ps_name=DejaVuSans-Bold, path=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf, index=0, is_scalable=True, has_color=False, ascender=1901, descender=-483, height=2384, underline_position=-175, underline_thickness=90) (new face)
```
how to make it normal view?

**Comment by kovidgoyal** [comment]
you have something in your vim config/plugins that is emitting malformed escape sequences. Bisect vimrc to find out what and remove it. As for fonts, if you want to use nerd fonts dont install a patched font, instead install the nerd fonts standalone. Patched fonts often have broken metric. kitty will pick them up automatically or you can use symbol_map in kitty.conf

**Comment by ecx** [comment]
my .vimrc:
https://pastebin.com/yWmbDGW9
I have played with config, disabling all that can be broke Kitty, but nothing changes.
I'm using FiraCode not from nerd font pack, it's not patched, it's just stock packaged from ubuntu repository. 
`kitty list-fonts` show's me it:
https://pastebin.com/DHzdwnS9
I have added symbols that can broke Kitty to symbol_map:
`symbol_map U+E61E,U+E712,U+2630 PowerlineSymbols`
and set:
`font_family FiraCode-Regular`
nothign changes, but `kitty --debug-font-fallback` show's me:
[103 10:11:45.741573] Preloaded font faces:
[103 10:11:45.741619] normal face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[103 10:11:45.741633] bold face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[103 10:11:45.741645] italic face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[103 10:11:45.741656] bi face: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf:0
[103 10:11:45.741671] Symbol map faces:
[103 10:11:45.741684] /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf:0
[103 10:11:46.173769] [PARSE ERROR] Unknown OSC code: 7
it is just vim-airline plugin broke Kitty, I think

**Comment by kovidgoyal** [comment]
Sorry I dont have any interest in debugging vim plugins. Seems like an over-engineered solution looking for a problem. If you want to use glyphs in your vim status line, just have whatever is generating the status line to output the corresponding unicode codepoints, kitty will automatically render them using fallback fonts, including nerd fonts.

I have no idea why vim-devicons is causing vim to output invalid escape codes to the terminal, you will need to take that up witht he author of vim-devicons.

**Comment by ecx** [comment]
I am understood how to catch bug: everything, that vim outputs, going to stdout/stderr, no other output ways interesting for terminal application. So you **doesn't need to debug vim, vim scripts** or any other terminal applications to understand the bug. I am start's writing vim output with `script`, and it can't show a trouble, then I tryed `asciinema` and it can! I wrote both sessions: from gnome-terminal and from kitty. The Kitty bug well-shown in asciinema.
gnome-terminal: [https://asciinema.org/a/240692](https://asciinema.org/a/240692)
Kitty: [https://asciinema.org/a/240691](https://asciinema.org/a/240691)
the result's of asciinema is regular text files, that you can study. As for me, problem is looks like unintialized variable/array or broken pointer inside Kitty code, but, you know's better than me, why it's happens(it's 100% not a vim trouble)

**Comment by kovidgoyal** [comment]
You dont need to use asciienema just use --dump-bytes to kitty if you
want to record the byte stream and --dump-commands if you want to record
the results of parsing the byte stream. From your screenshot, it is
obvious to me that most likely there is a malformed escape code in the
byte screen. asciienema and gnome-terminals escape code parsers are
probably just handling the malformed escape sequence differently.

Feel free to use --dump-bytes to confirm.

**Comment by ecx** [comment]
Kitty dump:
[kitty.dump.txt](https://github.com/kovidgoyal/kitty/files/3076245/kitty.dump.txt)
Kitty commands:
https://pastebin.com/dkUxevbn
Interesting line is 723

**Comment by kovidgoyal** [comment]
As I suspected, it is corrupted output from vim. Look at offset 0x1022
in the dump in a hex editor. You will see the bytes ^[P1+ (5E 5B 50 31)
these should have been preceded by the byte 1B (ESC) to form a valid
"Privacy Message" or PM escape code. That ESC is missing. Which is why
kitty echoes the following bytes to screen.

**Comment by ecx** [comment]
Strange data, but other terminal emulators process it(if it's really outputs from vim). How can I get this dump from vim without Kitty? redirection with >, session and asciinema does not write's this.

**Comment by kovidgoyal** [comment]
--dump-bytes dumps exactly the bytes kitty receives from the client
program. And programs like vim implement all sorts of behavior changes
based on TERM variables and other heuristics to detect terminals.


Liek I said just dump the icons package and use simple unicode
characters directly.

**Comment by ecx** [comment]
Demo program that makes Kitty buggy output:
https://pastebin.com/0uHns7g3
I think, Kitty must ignore output till 0A, otherway it throwing trash

**Comment by kovidgoyal** [comment]
Oh that's a DCS capabilities reporting escape code, and kitty is doing the right
thing there. It is sending back the asked for information.
gnome-terminal simply ignores the capabilities request.

Run your program in xterm and you will get the same output. So again,
the bug is in vim/vim-devicons.

When a client program sends a DCS query code it should:

1) put the terminal in NOECHO mode
2) read back the response and handle it

vim/vim-devicons is doing neither of those things

**Comment by kovidgoyal** [comment]
Oh and by the way you dont need to use a C program for this, a simple

printf '\x1bP+q436f\x1b\\\n'

will do the trick

**Comment by ecx** [comment]
nope, I have checked xterm works correct, as gnome terminal, as alacritty, only Kitty fails and throws garbage. I have inspected a little bit code of gnome-terminal - it's simpy ignores DCS codes, and seems it's okay. Try to inspect a little bit alacritty source code for DCS control codes handling, may be you will understand that code better than me.
shell command `printf '\x1bP+q436f\x1b\\n'` does not work for me(may be because of fish shell), that's why C program. I like c programs because it's work everywhere!

**Comment by kovidgoyal** [comment]
Sigh, read up on DCS codes: you will see that the correct response
to a DCS code enquiring about capabilities is what kitty is sending.

https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Device-Control-functions


I am done wasting my time on this.

**Comment by ecx** [comment]
This feature disabled by defaults or works different way than Kitty in all terminals: xterm, uxterm, gnome-terminal, alakritty, qterminal is little bit buggy too, but different. I have tryed different xterm/uxterm options - they are both processed that, buggy for Kitty, output correctly. Can you remember software, that you see in-the-wild, that uses DCS control codes and handles it correctly? As for me, may be you all done right but need to write output to a different stream(exclude output to the Kitty's visual terminal)

**Comment by Luflosi** [comment]
I am confident that @kovidgoyal knows that what kitty does is the correct thing to do according to the spec. Maybe you should try to report this bug to the vim plugin you're using.

**Comment by duganchen** [comment]
Looks like it's been reported to said vim plugin:

https://github.com/ryanoasis/vim-devicons/issues/266

**Comment by vitorpy** [comment]
Just leaving a note here in case someone else stumbles upon this:

Fix:

Add `set t_RV=` to the *end* of `.vimrc`.

Probable cause:

`vim-devicons` seems to be a trigger, the issue seems to be caused by vim's terminal handling.  The issue also occur with the Tilix terminal. I would guess terminals with a stricter (than gnome-terminal) handling of the spec allows this issue to surface. 

Source: https://github.com/ryanoasis/vim-devicons/issues/266
