### ISSUE TITLE
[Feature Request] Open a new window with a different font family?

### ISSUE THREAD

**Issue by WyldeLaRue** [kovidgoyal/kitty#1540]
Is it possible to have different terminal windows have separate fonts? This is a nice way to have distinct "profiles" for terminal windows with different tasks. There are certain fonts that look substantially better or worse with different colors or sizes. I know that this is a feature supported out of the box at least for Konsole, iTerm, and the builtin MacOS Terminal.app.

The only way I know to get something like this by changing the font options in kitty.conf and then starting a new instance of kitty. This unfortunately does not play nice with the builtin MacOS window manager as you end up with a new application in the dock for each kitty instance running. 

For this reason, it would be nice to be able to have some way of setting the font options either of a new window or an existing window. I tried to look through the documentation and the source code to see if there was a way of doing this with the remote-control utility, but it doesn't look like that is currently possible.  It's entirely possible that this feature is available somewhere, but I could not find it.

**Comment by kovidgoyal** [comment]
dup of #1436
