### ISSUE TITLE
Kitty interprets the wrong <alt-KEY> combo

### ISSUE THREAD

**Issue by Frojdholm** [kovidgoyal/kitty#1541]
OS: Manjaro 18.04
Kitty 0.13.3

On the swedish keyboard `;` and `:` are `<shift-,>` and `<shift-.>` respectively. ![swedish_keyboard_layout](https://user-images.githubusercontent.com/3251566/56211123-87e71380-6057-11e9-8a7d-6024945934fb.png)

When trying to get `<alt-;>` and `<alt-:>` (`<alt-shift-,>` and `<alt-shift-.>`) I get the following output from `showkey -a`:

Kitty:
```
^[<      27 0033 0x1b
         60 0074 0x3c
^[>      27 0033 0x1b
         62 0076 0x3e
```

Gnome Terminal:
```
^[; 	 27 0033 0x1b
 	 59 0073 0x3b
^[: 	 27 0033 0x1b
 	 58 0072 0x3a
```

**Comment by kovidgoyal** [comment]
Without the hardware hard for me to test, but you can get detailed
output about what key events kitty is seeing with --debug-keyboard

**Comment by Frojdholm** [comment]
For what it's worth I have observed this on both of my laptops. One Dell Vostro 3350 and one Lenovo Y50-70.

This is the output from `kitty --debug-keyboard`
```
Press scancode: 0x40 clean_sym: Alt_L composed_sym: Alt_L mods: numlock glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x32 clean_sym: Shift_L composed_sym: Shift_L mods: alt+numlock glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
Press scancode: 0x3b clean_sym: comma composed_sym: semicolon mods: alt+shift+numlock glfw_key: 44 (COMMA) xkb_key: 44 (comma)
on_key_input: glfw key: 44 native_code: 0x2c action: PRESS mods: 0x5 text: '' state: 0 sent key to child
Release scancode: 0x3b clean_sym: comma mods: alt+shift+numlock glfw_key: 44 (COMMA) xkb_key: 44 (comma)
on_key_input: glfw key: 44 native_code: 0x2c action: RELEASE mods: 0x5 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release scancode: 0x32 clean_sym: Shift_L mods: alt+shift+numlock glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: RELEASE mods: 0x5 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release scancode: 0x40 clean_sym: Alt_L mods: alt+numlock glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: RELEASE mods: 0x4 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

**Comment by kovidgoyal** [comment]
As far as I can tell kitty is doing the right thing here. The key you are pressing is comma not semi-colon. Therefore the shortcut being pressed is alt+shift+comma, not alt+semicolon. If you want kitty to send alt+semicolon instead you can use send_text in kitty.conf to tell it to do that. Let me know if you have trouble with figuring out the right send_text directive and I will help.

**Comment by Frojdholm** [comment]
Okay I managed to fix it using send_text as you suggested. I document it here in case someone else finds this issue.

```
map alt+shift+, send_text all \x1b;
map alt+shift+. send_text all \x1b:
```
