### ISSUE TITLE
CTRL+SHIFT+F2 ignore $EDITOR and use nano 

### ISSUE THREAD

**Issue by wizzup** [kovidgoyal/kitty#1544]
Is this expected behavior?  (click the image for youtube video)

[![Alt text](https://img.youtube.com/vi/aHcEjFpW15A/0.jpg)](https://www.youtube.com/watch?v=aHcEjFpW15A)

**Comment by kovidgoyal** [comment]
You need to set EDITOR system wide not in your shell's startup files.
kitty runs before the shell.
