### ISSUE TITLE
Incorrect rendering of ligatures in Space Mono

### ISSUE THREAD

**Issue by josswright** [kovidgoyal/kitty#1545]
I've read through some of the other issues around incorrect ligature rendering, but I hadn't seen specific mention of [Space Mono](https://fonts.google.com/specimen/Space+Mono). I recently tried it, and noticed that the "fi" and "<-" ligatures (at least -- I imagine it's consistent across the font) are being rendered incorrectly. It looks to me as if the ligature is being compressed into one cell, as "fii" and, say, "ibm" are taking up the same width, as you'd expect.

I don't know if this is another case where Space Mono is doing something "wrong" and so it's not fixable within kitty, but I thought that I'd report it just in case.

**Comment by kovidgoyal** [comment]
It's likely that space mono is using an unsupported technique similar to Iosevka (see #297). You should be able to check by using the hb-shape command I posted in that bug report.

**Comment by josswright** [comment]
Just as a follow-up to help anyone who finds this issue, Space Mono does have some odd ligatures enabled in a way that kitty can't disable. There is, however, a patched version of the font with Vim Powerline symbols added that resolves this issue: https://github.com/powerline/fonts/tree/master/SpaceMono
