### ISSUE TITLE
Pushing the limits of Kitty's startup time

### ISSUE THREAD

**Issue by atomsymbol** [kovidgoyal/kitty#1546]
Hi. I am avoiding single Kitty instance (`-1` command-line option) as a means of preventing potential bugs from propagating from one terminal group to all other terminal groups. With this assumption, the non-single-instance startup time becomes an important factor.

Kitty's startup time on my machine is:

    $ /usr/bin/time kitty true
    0.227user 0.056system 0:00.316elapsed

    $ kitty --version
    kitty 0.13.3 

For comparison, xfce4-terminal startup time (the same window size and the same font as Kitty):

    $ /usr/bin/time xfce4-terminal -e true
    0.093user 0.007system 0:00.123elapsed 

I am wondering whether it would be possible to optimize Kitty's startup time to 0.1 seconds (make it start 3 times faster).

**Comment by Luflosi** [comment]
On my machine, kitty takes much longer to start (almost 2 seconds):
```
$ time /Applications/kitty.app/Contents/MacOS/kitty true
/Applications/kitty.app/Contents/MacOS/kitty true  0.91s user 0.32s system 70% cpu 1.757 total
```
Alacritty for comparison:
```
$ time /Applications/Alacritty.app/Contents/MacOS/alacritty --command true
/Applications/Alacritty.app/Contents/MacOS/alacritty --command true  0.22s user 0.10s system 83% cpu 0.385 total
```
I don't know how to measure how long iTerm2 and the default Terminal.app take since they don't automatically quit after the command is executed.

But the startup time doesn't affect me as much as @atomsymbol because I'm only using a single instance. But it would still be nice to make kitty start a little faster if that's possible.

**Comment by atomsymbol** [comment]
`perf record -g -F10000 -- kitty true` is reporting that 12.5% CPU time is being spent in function `FcFontMatch`:

      Children      Self  Command    Shared Object                Symbol
    +   12.18%     0.00%  kitty      libfontconfig.so.1.11.1      [.] FcFontMatch
    +   12.11%     0.00%  kitty      libfontconfig.so.1.11.1      [.] FcFontSetMatchInternal
    +   12.07%     0.87%  kitty      libfontconfig.so.1.11.1      [.] FcCompare
    ...

Maybe this is a starting point for an optimization.

**Comment by kovidgoyal** [comment]
This is not something I care about personally, since in three years of
using kitty -1 I have never encountered a bug that has caused me to
loose work. That's not to say such a bug will never exist, but it is low
probability enough that I dont care.

That said, I am happy to accept patches to reduce startup time. IIRC the
biggest factors are:

1) python startup time
2) GUI toolkit startup time
3) config parsing time
4) DLL load time

You will need to instrument startup to find the biggest contributors.
See the section on using gperftools to instrument  kitty performance,
though I dont know how well that will work for short duration events
like startups. Feel free to ask if you need tips on getting started.

@Luflosi: 2 secs is horrible. On Linux systems it is typically 0.2-0.3
seconds and on macOS it is 0.8-1.0 secs.

**Comment by kovidgoyal** [comment]
fcfontmatch comes from libfontconfig and is used to find the fonts kitty needs. You can completely eliminate, that time by simply specifying an exact font family name in kitty.conf. See the find_best_match function in fontconfig.py

**Comment by atomsymbol** [comment]
> ... in three years of
> using kitty -1 I have never encountered a bug that has caused me to
> loose work. That's not to say such a bug will never exist, but it is low
> probability enough that I dont care.

Just a note: There also exist hardware data corruptions.

**Comment by atomsymbol** [comment]
@kovidgoyal I would like to remove `temp_window` from function `create_os_window` and thus use monitor in function `get_window_content_scale`. Would this be OK with you, or is there an other reason why `temp_window` is needed? Kitty is working OK without it. Startup CPU time is reduced by 10ms, though startup realtime is reduced by just 2ms.

**Comment by kovidgoyal** [comment]
On Sat, Apr 20, 2019 at 11:54:30AM -0700, Jan Ziak wrote:
> > ... in three years of
> > using kitty -1 I have never encountered a bug that has caused me to
> > loose work. That's not to say such a bug will never exist, but it is low
> > probability enough that I dont care.
> 
> Just a note: There also exist hardware data corruptions.

Which are even lower probability than software bugs, and are quite
likely to lead to total machine shutdown, when they do happen.

**Comment by kovidgoyal** [comment]
How would you know which monitor to use in a multi-monitor system? That
is the reason temp_window is used. The other option is to create the
glfw_window with some default size, get the content scale from it,
and then call get_window_size() and resize the window. The downside of
this approach is that on Wayland it will mean the window is resized
immediately after being shown, which is probably more resource intensive
and may cause flicker. This can be fixed if and when https://github.com/glfw/glfw/issues/1268
is fixed.

**Comment by atomsymbol** [comment]
> ... in three years of
> using kitty -1 I have never encountered a bug that has caused me to
> loose work. That's not to say such a bug will never exist, but it is low
> probability enough that I dont care.

I think you are underestimating the probability of software bugs. If I was passing `-1` to Kitty _git-tip_ I would lose work because of #1549.

**Comment by kovidgoyal** [comment]
Sorry but you dont get to introduce a bug into a program and then use it as evidence that the probability of software bugs is high :))

**Comment by atomsymbol** [comment]
Related bug: https://bugs.gentoo.org/683962

Correctly using `__pycache__` seems to lower Kitty's startup instruction count by just 4e6 compared to not using the cache, which translates to just 1 millisecond on current CPUs, but I want to be pedantic.

**Comment by atomsymbol** [comment]
> Sorry but you dont get to introduce a bug into a program and then use it as evidence that the probability of software bugs is high :))

Obviously, a newcomer to Kitty cannot know all of Kitty's internals. So it is by necessity a process of trial and error. Eliminating newcomers in software development is impossible.

While end-users of Kitty will not experience this particular bug (#1549), the fact is that the bug did occur at least one time in history.

Kitty's `make test` doesn't detect this bug.

_An interesting question is whether it would be possible to detect this particular bug at compile-time by making compilers more advanced._

**Comment by atomsymbol** [comment]
> This is not something I care about personally, since in three years of
> using kitty -1 I have never encountered a bug that has caused me to
> loose work. That's not to say such a bug will never exist, but it is low
> probability enough that I dont care.

An example: NetBeans runs on Java and sometimes (once per month or so) crashes with an internal JVM error (which might in fact be caused by GPU drivers, I didn't investigate the cause). -- Chrome browser uses a new Linux process for each tab to prevent some failures from spreading to all other tabs. -- If NetBeans was isolating tabs from each other, then maybe the fault wouldn't spread to other tabs and the crashed tab would simply be reloaded by the user to continue work.

It depends on whether the developer is designing the software with fault isolation in mind as a primary principle.

**Comment by atomsymbol** [comment]
> Sorry but you dont get to introduce a bug into a program and then use it as evidence that the probability of software bugs is high :))

I still think the probability of software bugs is higher than you imagine: #1550

**Comment by Luflosi** [comment]
@kovidgoyal wrote:
> This is not something I care about personally, since in three years of
using kitty -1 I have never encountered a bug that has caused me to
loose work. That's not to say such a bug will never exist, but it is low
probability enough that I don't care.

While #1550 is an example of a software bug, it is not an example of a bug that leads to loss of work.

**Comment by kovidgoyal** [comment]
> > This is not something I care about personally, since in three years of
> > using kitty -1 I have never encountered a bug that has caused me to
> > loose work. That's not to say such a bug will never exist, but it is low
> > probability enough that I dont care.
> 
> An example: NetBeans runs on Java and sometimes (once per month or so) crashes with an internal JVM error (which might in fact be caused by GPU drivers, I didn't investigate the cause). -- Chrome browser uses a new Linux process for each tab to prevent some failures from spreading to all other tabs. -- If NetBeans was isolating tabs from each other, then maybe the fault wouldn't spread to other tabs and the crashed tab would simply be reloaded by the user to continue work.
> 
> It depends on whether the developer is designing the software with fault isolation in mind as a primary principle.

What has bugs in other software got to do with bugs in kitty. You are talking about a bug that would: a) cause a crash or other catastrophic failure b) fail in a way that is isolated among separate kitty instances
The probability of such a bug is, empirically, very low. In any case, this discussion is beside the point. If you wish to improve kitty's startup times feel free to do so, I have no objections.

**Comment by kovidgoyal** [comment]
> Related bug: https://bugs.gentoo.org/683962
> 
> Correctly using `__pycache__` seems to lower Kitty's startup instruction count by just 4e6 compared to not using the cache, which translates to just 1 millisecond on current CPUs, but I want to be pedantic.

Well, I have changed setup.py to generate bytecode at all optimization levels.

**Comment by atomsymbol** [comment]
I believe you are living in a fantasy world that isn't the real world: #1551

**Comment by kovidgoyal** [comment]
> I believe you are living in a fantasy world that isn't the real world: #1551

Are you high? Even if it was an actual bug, how would it cause you to
lose work?
