### ISSUE TITLE
Crash when using python3 from nix on macOS

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1548]
I recently installed python3 using the package manager nix and noticed, that after recompiling kitty, some process crashes when opening a new OS window, tab or kitty window. Before the shell prints something, the first line I see in kitty is `[2]    94981 segmentation fault`. Otherwise kitty seems to behave pretty normal after that crash but I haven't tested it much. I could post the macOS crash report but it's probably not very useful, the call stack shows `libpython3.7m.dylib` on top, followed by `fast_data_types.so` and a bunch of `org.python.python`. The python3 version from brew is still installed if that matters. After uninstalling python3 using nix and recompiling kitty, the crashes are no longer happening. When I uninstalled python3 from nix without recompiling kitty, the crashes were still happening. Similarly, when having a "good" kitty app, just installing python3 again does not change anything, the crashes only happen after recompilation. When running kitty from the command line with `kitty.app/Contents/MacOS/kitty`, nothing crashes. This might be an environment variable problem. I found out, that removing the path `/Applications/kitty.app/Contents/Frameworks/kitty/kitty/launcher` from my `PATH` and then starting kitty from the command line results in the same crash. With that path, nothing crashes.
Could you give me a tip on how to debug this please? I'd like to keep python3 from nix if possible.

**Comment by kovidgoyal** [comment]
Sorry, I have no clue, I use neither nix nor macOS. Run something other
than a shell and see if it still crashes, if not, then it is something
in your shell's sartup files, probably the kitty completion code. Which
would imply it is starting an incorrect kitty.

**Comment by Luflosi** [comment]
Your tip was very helpful, it was the kitty completion code, it looks like this in my `.zshrc`: `kitty +complete setup zsh | source /dev/stdin`. The reason that didn't crash when executing from the command line is that my PATH was different and included a directory with another version of kitty in it, which doesn't crash. I debugged this a little more and found, that `PATH=/usr/local/bin /path/to/kitty.app/Contents/Frameworks/kitty/kitty/launcher/kitty +complete setup zsh` does crash while `PATH=/usr/local/bin /path/to/kitty.app/Contents/MacOS/kitty +complete setup zsh` doesn't. The crash happens in `data-types.c`, line 252, `m = PyModule_Create(&module);`. Do you know why this is happening?

**Comment by kovidgoyal** [comment]
Most likely mixing different python interpreters, the one you are
running the launcher with is dofferent from the one kitty was compiled
against.

**Comment by Luflosi** [comment]
How does the launcher choose which python interpreter to use and why is there a difference in the behaviour between the two different binaries?

**Comment by kovidgoyal** [comment]
The launcher doesn't choose it, the launcher is a python script.

**Comment by Luflosi** [comment]
Why do we have a launcher Python script and a launcher C program? What's the difference?

**Comment by kovidgoyal** [comment]
The C program did not exist originally, it was written for the binary builds of kitty. It is conceivable to replace the script with the binary even when running from source, but it would be a good deal of churn. You could no longer start kitty with python3 . and all the linux distro packages would probably need to be modified as well.

**Comment by Luflosi** [comment]
Are you sure, that it would prevent usage of `python3 .`? If I remove the file `kitty/launcher/kitty` and recompile kitty, I can still execute kitty with `python3 .`.

**Comment by kovidgoyal** [comment]
Yeah you can start it, since the launcher is not used for startup, but then when the newly started kitty tries to launch another kitty for a kitten or any other reason, if it is using a binary then there is no guarantee that the python it uses matches whtever python3 is, leading to mysterious crashes.
