### ISSUE TITLE
macOS: Possible to bind alt or super key as meta?

### ISSUE THREAD

**Issue by bsuh** [kovidgoyal/kitty#155]
Other terminal emulators for macOS include this as an option.

**Comment by kovidgoyal** [comment]
Not sure what you are asking for. Why do you need to bind one modifier as another? Simply use whatever modifier you want in your shortcut definitions. Or do you mean you want to change the modifiers passed down to the program running in the terminal?

**Comment by bsuh** [comment]
Yes I want to send meta down to programs running in the terminal. I think in Linux alt key is translated to meta key by X window server. I can remap alt to escape in macOS, but that would make it not possible to use many keyboard shortcuts that use alt key. I think instead in macOS, most popular terminal emulators offer option to translate alt key to meta key.

**Comment by kovidgoyal** [comment]
kitty already sends alt to the child running in the terminal. Run cat in kitty and press alt+key and you will see that alt key presses are translated into Esc+key. Which is the same behavior as on linux. Note that you might have to turn off the macOS facility for using alt to type unicode characters first.

**Comment by bsuh** [comment]
Unfortunately it does not seem trivial to do so. The unicode characters seem to be part of the keyboard layout and when switching to a custom keyboard layout with alt+key unbinded, it does not seem to send alt at all.

Would you be interested in merging a pull request, if I open one for adding this behavior as a configuration?

**Comment by kovidgoyal** [comment]
See #123

**Comment by kovidgoyal** [comment]
I dont mind adding this as an option, but really the correct fix is to stop s x from hijacking your alt key.

**Comment by emacstheviking** [comment]
I have this problem too. I disabled the Alt (Option) key from inside System -> preferences -> Keyboard -> Modifier keys and selected 'No action' for the Alt(Option) key. It has made a difference in that the key no longer seems to do anything! That is to say, when pressing Alt+, or Alt+. to rorate through nano buffers, I just get the key press. This seems to imply that 'No actoni' means 'no event transmitted' which is not helpful to Kitty.

Therefore I think it may be necessary to add it in to kitty as an option one day. I find binding Alt as Meta incredibly useful with nano, I use Mercury language and nano is my editor of choice.

Thanks for kitty though, it is absolutely THE BEST terminal emulator I've ever used and trust me, as an old VAX/VMS user I've tried a lot. I have a ten year old (late 2012) iMac and this is hands down the fastest and nicest terminal emulator I've ever used.

**Comment by emacstheviking** [comment]
As an update, I have managed to achiebe a result by configuring Karabiner Elements , I added a mapping so that:

right_alt => escape

and I can now use the Alt key as a meta key.

This Is The Way.

**Comment by wongjiahau** [comment]
Not only `nano`, `emacs` also requires this to work properly on MacOS, because a lot of keybindings on `emacs` relies on the meta key.

**Comment by emacstheviking** [comment]
The BETTER solution I found was to get rid of Karabiner elements and then I uncommented this entry in the configuration which I found further down.

macos_option_as_alt yes

The Alt key is now perfect for nano!
