### ISSUE TITLE
The terminal window sometimes does not repaint

### ISSUE THREAD

**Issue by atomsymbol** [kovidgoyal/kitty#1550]
Hi. I am using mc (Midnight commander) to run some executables&scripts by moving cursor over the executable and pressing Enter. mc is set up to wait for a keypress after the command finishes. The last line on the terminal then is:

    Press any key to continue...

The issue is that sometimes this line does not show up. The hidden text is revealed in Kitty when:

- moving the mouse
- pressing a key like Ctrl
- opening a new window via a global keyboard shortcut
- opening a new window via for example `sleep 10; kitty` running in background

This issue seems to manifest itself only when the machine is under heavy load (1200%, the CPU has 12 hardware threads), such as when compiling the package `qtwebengine` in the background.

`xfce4-terminal` does not have this issue.

Kitty version: git tip

**Comment by atomsymbol** [comment]
Steps to reproduce:

    $ head load.sh keypress.sh 
    ==> load.sh <==
    #!/bin/bash
    trap 'kill $(jobs -p)' EXIT
    for((i=0; i<4*$(nproc); i++)); do
            bash -c "while true; do true; done" &
    done
    wait
    
    ==> keypress.sh <==
    #!/bin/bash
    while true; do
            find /usr/lib/
            echo "Press enter ..."
            read
    done

1. Open a terminal and start `load.sh`
2. Make sure the path in `keypress.sh` (/usr/lib/) contains a lot of files
3. Open a second (independent) Kitty terminal and start `keypress.sh`
4. Keep pressing the Enter key in the 2nd terminal when you see the text `"Press enter"` until the issue manifests itself. It takes about 10 Enter keystrokes on my machine to trigger 1 occurrence of the issue.

@kovidgoyal Please try it on your machine(s).

**Comment by atomsymbol** [comment]
Almost **always** reproducible:

- Login via ssh to a remote machine: The prompt does not show up (defined by `PS1` env variable)

**Comment by kovidgoyal** [comment]
Known issue in master, see https://github.com/kovidgoyal/kitty/issues/461#issuecomment-483091044

**Comment by kovidgoyal** [comment]
I dont keep open bugs against un-released code.

**Comment by Giessen** [comment]
I came across this problem tool, running on WSL2. 
Reproducing:
------
1.launch:     kitty --detach -1 --hold /bin/zsh
2.run nnn (a terminal file manager):       NNN_PLUG='i:preview-tui' nnn -a -i -Pi
3.browse with up/down arrow keys
At somewhat 1/5 chance, the splitted preview pane refuses to refresh. If I move mouse cursor, suddenly it refreshes.
I also tried building kitty from source, still no luck.
Any ideas please. Thanks.

**Comment by kovidgoyal** [comment]
That will have nothing to do with kitty. The split pane here is an nnnpane not a kitty one. nnn is responsible for refreshing it.

**Comment by Giessen** [comment]
Thanks for the quick response. I read in the page preview-tui plugin of nnn (https://github.com/jarun/nnn/blob/master/plugins/preview-tui ):
65 #   The previews will be shown in a tmux split. If that isn't possible, it
66 #   will try to use a kitty terminal split. And as a final fallback, a
67 #   different terminal window will be used ($NNN_TERMINAL).

Because I 'm not using tmux here, it seems nnn is using "kitty terminal split". I don't quit understand how it works exactly, so I could be wrong.

Any advices are appreciated. Thanks.

**Comment by kovidgoyal** [comment]
No clue. I dont use nnn. At a minimum for it to use kitty splits, you
have to enable remote control.

**Comment by Giessen** [comment]
OK. Thanks for the info. I'll try that.
