### ISSUE TITLE
First instanceof kitty -1 sometimes does not terminate

### ISSUE THREAD

**Issue by atomsymbol** [kovidgoyal/kitty#1551]
Hi. While performing some stress tests, the first `kitty -1` does not terminate despite having no child processes. In this state, while the first `kitty -1` is still running, executing `kitty -1` in another terminal does not open a new terminal window.

Kitty version: git

**Comment by kovidgoyal** [comment]
dup of #1550

**Comment by atomsymbol** [comment]
I can reproduce this issue in Kitty 0.13.3. Reopen this issue -- or chose to remain in the fantasy world.

**Comment by lifranc** [comment]
I had this on version 0.14.6 while working, single-instance was still alive but the terms were gone (suddenly dissapeared) and lost ability to spawn new windows, had to `kill -9 pid`. WM is sway v1.2 on tweaked nixOS.
