### ISSUE TITLE
KITTY_ENABLE_WAYLAND=1 still runs on X11

### ISSUE THREAD

**Issue by kkga** [kovidgoyal/kitty#1553]
Trying to use Kitty in wayland-native mode, but no luck so far. Starting it with an environment variable still launches the app under X11. Any ideas?

![image](https://user-images.githubusercontent.com/1460122/56511265-de12f580-6534-11e9-880c-ea61ef188458.png)

**Comment by kovidgoyal** [comment]
Both KITTY_ENABLE_WAYLAND and WAYLAND_DISPLAY need to be set and the kitty wayland backend needs t have been built which means glfw-wayland.so has to exist.

**Comment by EvanCarroll** [comment]
For those coming to this issue from bad Google Indexing, I think this is no longer required.
