### ISSUE TITLE
[stress test] Most characters render blank after switching to&from console

### ISSUE THREAD

**Issue by atomsymbol** [kovidgoyal/kitty#1555]
A result from randomized stress testing:

1. Open new Kitty window
2. Open two tabs
3. Start stress test
4. Press Ctrl+Alt+F1 to switch from X desktop to Linux console
5. Switch back to X desktop
6. Almost all characters in the Kitty window and tab titles now render as blanks (like the space character)
7. Stop the stress test

For comparison: xfce4-terminal, using the same font as Kitty, survives this stress test and is able to maintain correct font rendering.

Kitty version: 0.13.3
GPU currently in use: Nvidia GTX 750

Trying harder does not require a reason.

**Comment by kovidgoyal** [comment]
This is a bug in your GPU drivers. And you are not welcome here anymore, please use another terminal.

**Comment by xanderxylona** [comment]
What a horrendous way to handle community feedback.

**Comment by nicolascolla** [comment]
> What a horrendous way to handle community feedback.

Just look at the other four or five issues opened by atomsymbol. He was being openly and unnecessarily rude with people that are working on a product for free.

**Comment by sashaarawn** [comment]
> Just take a look at the other four or five issues opened by atomsymbol. He was being openly and unnecessarily rude with people that are working on a product for free.

Fair enough; I had seen one other where Kovid incorrectly closed some bug off the pretense that it was internal to a previously fixed and private, and associated therefore that he was just being a prick. That seems to have been essentially the *only* time he (atomsymbol) was being rude. Even so, I'd cede making too many issue reports can be a little annoying.

**Comment by kovidgoyal** [comment]
For reference: https://github.com/kovidgoyal/kitty/issues/1546

Life is too short for me to tolerate "community feedback" of this nature.
