### ISSUE TITLE
Error using sphinx-build from nix

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1561]
Does kitty assume, that `sphinx-build` is a python script? I tried using `sphinx-build` from nix, which is a shell script wrapper around the real `sphinx-build` but I get an error message:
```
  <More stack trace here>
  File "/Users/user/.nix-profile/bin/sphinx-build", line 2
    export PATH='/nix/store/......
              ^
SyntaxError: invalid syntax
make[1]: *** [man] Error 1
make: *** [man] Error 2
```

**Comment by kovidgoyal** [comment]
Yes it does, it has to since it has to be able to import the kitty
package, which can happen only if sphinx-build is run with kitty added
to the PATH.

**Comment by Luflosi** [comment]
The line that alters the PATH keeps the kitty binary in the PATH, so that shouldn't cause problems. Is there a way to execute `sphinx-build` as a binary rather than assuming a python script?

**Comment by Luflosi** [comment]
Oh, sorry, didn't see that commit.

**Comment by Luflosi** [comment]
It works now 🎉
