### ISSUE TITLE
couldn't unmap ctrl+l

### ISSUE THREAD

**Issue by theonlygusti** [kovidgoyal/kitty#1566]
I added 

```
map ctrl+l no_op
```

in my kitty.conf because I want to start using ctrl-l as a shortcut in my shell (autosuggestion expansion) and don't want ctrl-l to clear the terminal.

However ctrl-l is still clearing the terminal.

**Comment by kovidgoyal** [comment]
That is because your shell interprets ctrl+l as clear screen.
