### ISSUE TITLE
WARNING: terminal is not fully functional (local computer)

### ISSUE THREAD

**Issue by Oreolek** [kovidgoyal/kitty#1567]
When calling `systemctl status [service]` it complains about the terminal. Even as root (without sudo), on local computer. `$TERM` is `xterm-kitty`.

**Comment by kovidgoyal** [comment]
You need to install kitty terminfo files system wide so they are
available when using sudo.

**Comment by Oreolek** [comment]
I already wrote I'm not using sudo.

**Comment by Luflosi** [comment]
He meant when being root. You can install the terminfo files into the home directories of all the users you will be using. The structure looks like this in my home directory:
```
$ tree .terminfo
. terminfo
├── 78 -> x
└── x
    └── xterm-kitty

2 directories, 1 file
```

**Comment by Oreolek** [comment]
I installed them globally to `/etc/terminfo` and locally to root home. Does not work.

**Comment by Luflosi** [comment]
Did you put the `78` symlink and the `x` directory into `/etc/terminfo`? That should be correct. If so, here are a couple other things you could try that may or may not work:

- Restart your shell
- Restart kitty
- Double check, that TERM is set to `xterm-kitty` or set it explicitly: `export TERM=xterm-kitty`

I don't know what else to try, maybe @kovidgoyal has a hint for you.

**Comment by raffaem** [comment]
> You need to install kitty terminfo files system wide so they are available when using sudo.

How can I do so?

**Comment by raffaem** [comment]
> You need to install kitty terminfo files system wide so they are available when using sudo.

For others coming here, from a kitty terminal run:
```
sudo cp -a $TERMINFO/. /etc/terminfo/
```

**Comment by raffaem** [comment]
> > > You need to install kitty terminfo files system wide so they are available when using sudo.
> > 
> > 
> > For others coming here, from a kitty terminal run:
> > ```
> > sudo cp -a $TERMINFO/. /etc/terminfo/
> > ```
> 
> This is dangerous in case `$TERMINFO` is unset. Instead, I have had luck with:
> 
> ```
> sudo cp -a "${TERMINFO:-$HOME/.terminfo}"/* /etc/terminfo/
> ```

My understanding is that kitty *always* set $TERMINFO to the correct path.

**Comment by wgqimut** [comment]
@kovidgoyal I think I found the root cause, I use `strace` to trace which file will be read when `less` command executed, and for kitty, I think the program find wrong directory:
```
81182 access("/etc/terminfo/x/xterm-kitty", R_OK) = -1 ENOENT (No such file or directory)
81182 access("/lib/terminfo/x/xterm-kitty", R_OK) = -1 ENOENT (No such file or directory)
81182 access("/usr/share/terminfo/x/xterm-kitty", R_OK) = -1 ENOENT (No such file or directory)
```
it try to read `/usr/share/terminfo/x/` directory, the real kitty config file is located `/usr/share/terminfo/k`, the reason I think its `$TERM` name, it's `xterm-kitty` not `kitty`! compared to Alacritty:
```
82689 access("/etc/terminfo/a/alacritty", R_OK) = -1 ENOENT (No such file or directory)
82689 access("/lib/terminfo/a/alacritty", R_OK) = -1 ENOENT (No such file or directory)
82689 access("/usr/share/terminfo/a/alacritty", R_OK) = 0
```

```
$ echo $TERM
alacritty
```

**Comment by kovidgoyal** [comment]
sudo apt-get install kitty-terminfo 

and you will be fine.
