### ISSUE TITLE
question: send keypress to all windows/OS windows

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#1569]
Is there a way to have synchronous typing in all kitty windows/OS windows
like tmux's `:setw synchronize-panes`?

**Comment by kovidgoyal** [comment]
Yes, the remote control feature can be used to do that
https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by rjcoelho** [comment]
@kovidgoyal can you provide an example on how to toggle window sync across all windows in a given tab using remote control ?

**Comment by kovidgoyal** [comment]
It would require writing some small terminal program that reads keypresses and then sends those keypresses to all kitty windows using kitty @ send-text. Simply run that program in one window, then anything you type there will be sent to all windows by the program. I'm afraid I dont have time to write the program for you, but it should be pretty simple to do. In python pseudo code:
```
set stdin to unbuffered using the tty module
while True:
    bytes = sys.stdin.buffer.read(1)
    subprocess.run(['kitty', '@', 'send-text', '--match-tab', 'the tab you want matched', '--stdin'], stdin=bytes)
```

And if you want to get more sophisticated you can write it as a kitten and avoid needing to use remote control at all.

**Comment by rjcoelho** [comment]
Thanks, I'll try to come up with a PR for docs, if that makes sense for you.

**Comment by kovidgoyal** [comment]
sure

**Comment by aorith** [comment]
I'm using this simple kitten:

```python
from sys import exit

def main(args):
    # this is the main entry point of the kitten, it will be executed in
    # the overlay window when the kitten is launched
    print("Send to all windows in this Tab.\n")
    try:
        answer = input("> ")
    except KeyboardInterrupt:
        print("Cancelled.")
        exit(0)
    # whatever this function returns will be available in the
    # handle_result() function
    return answer


def handle_result(args, answer, target_window_id, boss):
    tab = boss.active_tab
    windows_dict = tab.list_windows(target_window_id)
    for w_dict in windows_dict:
        w = boss.window_id_map.get(w_dict.get("id"))
        if w is not None:
            #w.paste_bytes(answer + "\x0d")
            w.paste(answer + "\r")
```

`map f2 kitten kittens/broadcast_to_current_tab.py`
Press F2, write a command and press ENTER. It will send the command to all the windows in current tab.

Still, it feels like a bad hack and you can only send one command at a time, it doesn't stream the chars as you type them like in tmux implementation. I tried to do it by using yield but failed...

**Comment by kovidgoyal** [comment]
I had a little time, so I implemented the kitten.
