### ISSUE TITLE
Wayland: Focusing a window requires user interaction

### ISSUE THREAD

**Issue by bearcatsandor** [kovidgoyal/kitty#157]
[glfw error 65544]: Wayland: Focusing a window requires user interaction
Traceback (most recent call last):                                    
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)           
  File "./__main__.py", line 13, in <module>                            
    main()                                                              
  File "./kitty/main.py", line 292, in main                             
    run_app(opts, args)                                                 
  File "./kitty/main.py", line 202, in run_app               
    initialize_window(window, opts)                          
  File "./kitty/main.py", line 161, in initialize_window
    glewInit()                              
RuntimeError: GLEW init failed: [4] Unknown error
[glfw error 65537]: The GLFW library is not initialized

Am i missing a library here or is this not operable on Wayland yet?

Thanks

**Comment by kovidgoyal** [comment]
You need to compile glew with the EGL backend. By default it is compiled with the GLX backend.

**Comment by kovidgoyal** [comment]
And you will also need to compile glfw from master as the released version of glfw has a bug that causes duplicated key presses under wayland.

**Comment by kovidgoyal** [comment]
For people that might find this bug report, you compile glew with EGL using

make SYSTEM=linux-egl

Since wayland is pretty new it's likely your distro does not have a precompiled version of glew built this way. 

For example, in Arch:
https://bugs.archlinux.org/task/56025

**Comment by aenda** [comment]
This error still occurs for me using the glew-wayland package from arch, which does set `SYSTEM=linux-egl` (see [the PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/glew-wayland)). I'm also using glfw-wayland-git to build from master.

I get
```
GL version string: '4.5 (Core Profile) Mesa 18.0.3' Detected version: 4.5
wl_surface@13: error 3: xdg_surface must not have a buffer at creation
[135 23:29:00.699834] [glfw error 65544]: Wayland: Focusing a window requires user interaction
[135 23:29:00.699870] [glfw error 65544]: Wayland: Window position retrieval not supported
```

**Comment by kovidgoyal** [comment]
The information in this bug report is obsolete. kitty now has its own bundled glfw and you dont need to compile it separately. To run kitty under wayland you do
```
KITTY_ENABLE_WAYLAND=1 kitty
```

also make sure that the WAYLAND_DISPLAY env var is set. As for your actual error, it is likely caused by an obsolete wayland compositor. I can tell you that kitty runs fine under weston 4.0.0

**Comment by kovidgoyal** [comment]
@aenda Feel free to pass it on to the glfw project, there is no wayland specific code in kitty itself.

**Comment by ignisf** [comment]
FYI https://github.com/glfw/glfw/issues/1121
