### ISSUE TITLE
Strange Font Rendering

### ISSUE THREAD

**Issue by NateDogg1232** [kovidgoyal/kitty#1572]
I really like Kitty's Unicode abilities compared to urxvt's, so I decided I'd switch over, but I noticed, upon starting it up, that there is noticable stretching in the font. A screenshot with a comparison to urxvt is [here](https://i.imgur.com/7d9OxVI.png)

Kitty version: 0.13.3
OS: Arch Linux (Other details given in the screenshot through neofetch)

My current kitty config is [here](https://gitlab.com/NateDogg1232/dotfiles/blob/master/kitty/kitty.conf)
At its base, it includes the wal colorscheme (Only has some color definitions) and sets the font to Source Code Pro at a font size of 14.0. I just changed it to the Nerd Fonts patched one, in hopes of fixing it, but it stayed the same.

If you need any other configuration files, I'm open to providing them.

**Comment by kovidgoyal** [comment]
I'm confused. From the screenshot it looks like shrinking not stretching? I have a couple of recommendations
1) Dont use a patched font, just install the nerd fonts separately, kitty will use them automatically
2) You can always tinker by using the adjust_line_height/adjust_column_width settings

**Comment by kovidgoyal** [comment]
No followup?

**Comment by NateDogg1232** [comment]
I'm sorry. I meant to follow up, but didn't get a notification.
Upon adjusting the column height and width, I just get the glyphs chopped off.
Example with adjust_line_height set to 80%: 
![image](https://user-images.githubusercontent.com/12480453/56872738-32a8eb80-69e1-11e9-8a36-91ad9c98609d.png)
And example with adjust_column_width set to 120%: 
![image](https://user-images.githubusercontent.com/12480453/56872763-671ca780-69e1-11e9-88a1-cae721c48a6e.png)
And with both set to those values: 
![image](https://user-images.githubusercontent.com/12480453/56872780-99c6a000-69e1-11e9-8d4b-51d9fa74f4d3.png)

They are being stretched vertically and shrinking horizontally. I don't know if this will help, but I have three monitors, two at 1080p, and one at 1280x1024 but rotated

**Comment by kovidgoyal** [comment]
This will be caused by the rotated monitor. Try temporarily disconnecting it and see if the issue goes away.

**Comment by NateDogg1232** [comment]
The rendering was def fixed when unplugging the rotated monitor. How exactly do I go about fixing this?

**Comment by kovidgoyal** [comment]
That means the X server (I assume you are using X) is not swapping the X and Y dpi values when the monitor is rotated. The function in kitty responsibe for this is get_window_content_scale() which in turn relies on glfwGetWindowContentScale which on X11 uses _glfwPlatformGetWindowContentSclae in x11_window.c which uses _glfwG_glfwGetSystemContentScaleX11 in x11_init.c

See that function for details of how the process works.

**Comment by kovidgoyal** [comment]
The easiest way you can control it as a user is to set Xft.dpi using xrdb

**Comment by NateDogg1232** [comment]
Thanks, that fixed it.
I think it'd be a good idea to put this somewhere as a note for those who have rotated monitors.
