### ISSUE TITLE
pasting isn't instant

### ISSUE THREAD

**Issue by theonlygusti** [kovidgoyal/kitty#1573]
When I cmd-v to paste into the terminal I can watch it overwrite the current command line as if it's being typed out fast from the start of the line, then it gets shifted to where it should have been pasted to.

This effect is not very nice.

Is there a way to make pasting instant?

I am in zsh, on macOS.

I am pasting stuff into zsh's command line. I am not connected to a server. I remember pasting was instant in iTerm2.

**Comment by Luflosi** [comment]
Pasting is instant for me. Can you tell us a bit more about what exactly you're doing? Which shell are you using? Where are you pasting stuff into? Your shell? Your editor? Are you maybe connected to a server via ssh or mosh? Was pasting instant with the last terminal emulator you used?

**Comment by theonlygusti** [comment]
@Luflosi added that to the first post, thanks for pointing it out

**Comment by Luflosi** [comment]
I'm also using zsh on macOS and I don't have this problem.
You could try starting kitty with an empty `kitty.conf` and zsh with an empty `.zshrc` and see if that changes anything.
If that doesn't change anything, I don't know why this could be happening. Maybe @kovidgoyal has an idea.

**Comment by theonlygusti** [comment]
@Luflosi oh, this is a zsh issue.

**Comment by kovidgoyal** [comment]
Try turning on bracketed paste in zsh
