### ISSUE TITLE
How to I install/load/configure the xterm-kitty file?

### ISSUE THREAD

**Issue by tonnydourado** [kovidgoyal/kitty#1577]
I'm getting the `Error opening terminal: xterm-kitty.` message when trying to run `htop` with `sudo`. [This issue](https://github.com/kovidgoyal/kitty/issues/1024) says I should "install xterm-kitty terminfo system-wide", but there's not explanation there, or anywhere else in the docs, about how exactly is this done, and I think I'm googling it wrong, cos' I haven't been able to figure it out.

So, maybe it could be add to the F.A.Q? 

By the way: I'm on Xubuntu 18.04. And htop and other ncurse programs (I tried mc and vim) work fine without sudo.

**Comment by tonnydourado** [comment]
Ok, found a solution: I have a config file on sudoers.d for htop, so I just add a line to forward the TERMINFO environment variable, like this: `Defaults  env_keep += "TERMINFO"`.

I'll leave this open in case someone wanna add this to the F.A.Q., but otherwise, feel free to close it.

And thanks for this project, seems quite cool and I look forward to trying it out more =)

**Comment by kovidgoyal** [comment]
It is already in the FAQ https://sw.kovidgoyal.net/kitty/faq.html#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo

**Comment by tonnydourado** [comment]
My bad! Thanks for the link, has some extra stuff I'll look into =)

**Comment by tomjakubowski** [comment]
I hope you won't mind if I inline another relevant and _very_ helpful bit from just above what you linked, in case someone else stumbles here:

> You can ssh in using the following command which will automatically copy the terminfo files to the server
> ```
> kitty +kitten ssh myserver
> ```

**Comment by imranZERO** [comment]
> It is already in the FAQ https://sw.kovidgoyal.net/kitty/faq.html#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo

This link is not available anymore.

**Comment by oditynet** [comment]
> kitty +kitten

`kitty +kitten ssh myserver` It is NOT WORK!

Used: `export TERM=xterm;ssh user@172.3.2.1` - WORK! But export TERM is puts in .bashrc and not work from his :(
