### ISSUE TITLE
margin background color is not terminal background color

### ISSUE THREAD

**Issue by Trollwut** [kovidgoyal/kitty#1579]
Hey folks!

On the margins to the borders, the background color seems to be a solid `#000000` instead of the set background color for the terminal.

![Example image](https://i.imgur.com/cE4xTQA.png)

As this margin changes with resizing the windows, I guess it's like calculating "how many lines fit in there" and center it. The rest ist being filled by black.

I didn't see anything in the config to just fill it with `background` color. Did I miss this or is this intentional behaviour?

Also: can I force kitty to have the first terminal line aligned on top of the window and not like vertical-center?

**Comment by kovidgoyal** [comment]
when you have a single active window, margins and paddings will take the color of that window's background. I am guessing that is a screenshot in some editor, maybe vim or similar. In that case you should configure that editor to actually change the terminals background color rather than just filing every cell with the same background, which is much more performant anyway.

You can do so by creating a shell script that use OSC escape codes to set the terminal background color and then change the editor config to not have a background color at all.

**Comment by Trollwut** [comment]
Yes, it is VIM. Unfortunately, this problem also occurs when no app is opened in the terminal:

![no apps, just kitty](https://i.imgur.com/4ixCGrK.png)

Now when I set `background #FF00FF` in the `kitty.conf`, there's that (only kitty running):

![pink is nice](https://i.imgur.com/e3Njhct.png)

You can see that the "margin background" is also pink, just a hint darker. So is there a setting where I can paint it the same as the `background` setting?

**Comment by kovidgoyal** [comment]
Are you on some older version of kitty? See #1221

**Comment by Trollwut** [comment]
AFAIK running the latest version on a Manjaro system:

    $ kitty -v
    kitty 0.13.3 created by Kovid Goyal

But yes, it seems indeed to have opacity. When I run `compton`, the margin part seems slightly transparent.

**Comment by kovidgoyal** [comment]
If you are setting background_opacity then it is expected that things will
be semi-transparent.

**Comment by Trollwut** [comment]
Had the time yesterday to test it on my main machine. It is indeed the transparency setting and so on. On my main machine I use a compositor and therefore the whole window renders fine.

It's just when I don't use an compositor - or even worse, the VM I have this error just doesn't have the graphics coverage needed for that. So… it's the VM, not the terminal.

Yet, the terminal is vertically centered, so sometimes I have just a few pixels from the top, where the command line begins. Is there an option to always have the first line directly on top without the margin? (I mean it could add to the bottom instead)

Also, I use this opportunity to tell you that this terminal is freaking awesome, really love to work with it :>

**Comment by kovidgoyal** [comment]
No there is no setting to top align vertically, but patches are welcome.
I personallylike centered and it is fairly involved, so I have not
bothered.
