### ISSUE TITLE
How do i map Ctrl + semicolon to send Ctrl + b?

### ISSUE THREAD

**Issue by ingjieye** [kovidgoyal/kitty#1580]
Sorry maybe this is a simple question, but I read the full doc and not found a solution, did try  `map ctrl+SEMICOLON send_text \x2` doesn't work.

**Comment by kovidgoyal** [comment]
You have not specified a mode for send_text and use ; not SEMICOLON.

**Comment by ingjieye** [comment]
Try `map ctrl+; send_text all \x2` still didn't working

**Comment by ingjieye** [comment]
`map ctrl+; send_text all \x02` works fine now, thanks
