### ISSUE TITLE
Remote commands doesn't accept negative decrements

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#1582]
When running remote commands in shell with negative decrement value, I get an error:
```
$ kitty @ set-background-opacity -a -0.1   
Unknown option: -0.1
```
Tried escaping the `-` with backslash and quotes but most probably uses custom argument parsing and doesn't handle them.

**Comment by SolitudeSF** [comment]
`kitty @ set-background-opacity -a -- -0.1` works

**Comment by sergei-dyshel** [comment]
@SolitudeSF 
You're right, `--` is the proper way of escaping.
