### ISSUE TITLE
Add command to just run arbitrarily program

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#1583]
It would be nice to have key-mappable command which just runs given program (just like `pass_selection_to_program` but without passing selection), e.g.
```
map ctrl+minus combine : change_font_size all +1.0 : run_program modify-kitty-conf-font-size.sh +1.0
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/pipe.html
