### ISSUE TITLE
No difference between different box characters?

### ISSUE THREAD

**Issue by dieggsy** [kovidgoyal/kitty#1585]
First, a question: Do I understand correctly (from reading related issues) that box drawing chars in kitty work by drawing them directly rather than using the font's glyphs (or something to this effect?)?

I noticed that e.g. `╭` (0x250C) and `┌` (0x256D) are drawn the same in kitty - is this intentional? It seems a bit unintuitive behavior as those glyphs are supposed to be different (e.g. one curved and one straight).

**Comment by kovidgoyal** [comment]
Yes, box drawing characters are drawn directly, that's the only way to
guarantee they will always line up at all font sizes. And yes its
deliberate as I dont have the time/interest to implement drawing a
curve for those characters. Patches are welcome, relevant code is
in box_drawing.py. See the D() function for an example of drawing
curves.
