### ISSUE TITLE
Some TUI applications do not get killed with Kitty

### ISSUE THREAD

**Issue by OndrejSlamecka** [kovidgoyal/kitty#1588]
How to reproduce:
1. open Kitty,
2. start Matterhorn https://github.com/matterhorn-chat/matterhorn (or any other application using https://hackage.haskell.org/package/brick)
3. kill Kitty (`SIGTERM` or the actual usage is closing its window in a window manager),
4. observe Matterhorn surviving (having `init` as its parent now and eating CPU due to processing errors regarding terminal interaction in a loop).

What I would expect: Matterhorn is killed in/after step 3.

I also tried xterm and rxvt-unicode to check that it is not possible to reproduce the problem with them. On the other hand, I tried running alsamixer in Kitty and that gets successfully killed with the terminal.

Environment: Updated Arch Linux and Kitty built from source. When I start it with `python3 .` I get the following which does not look related

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 117, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 108, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 68, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 27, in runpy
    exec(args[1])
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'kitty.update_check'
[124 10:55:50.649562] Failed to process update check data '', with error: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "./kitty/window.py", line 281, in use_utf8
    get_boss().child_monitor.set_iutf8(self.id, on)
AttributeError: 'fast_data_types.ChildMonitor' object has no attribute 'set_iutf8'
```

Also, thanks for this great terminal emulator!

**Comment by kovidgoyal** [comment]
So, when kitty closes a window it sends the child process the SIGHUP signal. This, as far as I know, is the correct behavior. I'm not familiar with brick or matterhorn so I am only guessing, but I would imagine that it is installing a signal handler for SIGHUP. 

You can confirm kittys behavior by adding some printfs to the remove_children function in child-monitor.c

Regarding your tracebacks, it is caused by having two kittys on thesystem. Uninstall the orginal one and then you should be fine.

**Comment by OndrejSlamecka** [comment]
Thank you, that's useful information!

I looked at https://github.com/thestinger/vte-ng/blob/0.50.2-ng/src/vte.cc#L8422 and it appears to do SIGHUP & memory freeing like kitty, yet due to some detail it does not suffer from this issue (I tried with `termite` terminal emulator which uses `vte-ng`).

On the application side I found `vty` (the underlying library of Brick) is what suffers from this problem. I tried basic tricks (setting `TERM` to `xterm` before running matterhorn) and digging inside vty but disabling the signal handlers I found (search for `installHandler`) did not help (and I did not find any other).

I am out of obvious clues now.

---

For anyone interested, the strace below shows where it keeps getting exceptions in a loop when the terminal is closed (however, it's probably not very interesting for this bug bug)

```
[pid 24835] write(2, "*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: \n  ", 72) = -1 EIO (Input/output error)
[pid 24835] write(2, "Graphics.Vty.Input.Loop.parseEvent", 34) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.Loop.loopInputProcessor", 58) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.Loop.runInputProcessorLoop.\\", 63) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.Loop.runInputProcessorLoop", 61) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.Loop.forkOSFinally.\\", 55) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.Loop.forkOSFinally", 53) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.Loop.initInput", 49) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.Input.inputForConfig", 49) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Graphics.Vty.mkVty", 34) = -1 EIO (Input/output error)
[pid 24835] write(2, ",\n  called from Main.main", 25) = -1 EIO (Input/output error)
[pid 24835] write(2, "\n", 1)           = -1 EIO (Input/output error)
```

And this is how to reproduce 
`stack new vtydemo`, replace `app/Main.hs` with https://github.com/jtdaugherty/vty/blob/master/demos/Demo.hs and add `vty`,`mtl`,`containers` into dependencies in `package.yaml`, compile with
`stack build --ghc-options="-fprof-auto -fprof-cafs" --executable-profiling`, run with `stack exec -- vtydemo-exe +RTS -xc` find the pid with `pgrep vtydemo`, and attach strace with `strace -f -e trace=write,network -s 80 -p $pid`, finally, kill the terminal.

**Comment by kovidgoyal** [comment]
As

**Comment by kovidgoyal** [comment]
as far as I can tell this is not a bug in kitty, at least I cannot see anything it should do differently. If that changes I will re-open this bug.
