### ISSUE TITLE
trim_selection option ?

### ISSUE THREAD

**Issue by sloonz** [kovidgoyal/kitty#1589]
Using middle-click to copy-paste something from vim adds trailing spaces.

To prevent this behavior, xterm has an option to remove trailing spaces from selection : https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:trimSelection

It could be helpful to have a similar option in kitty.

**Comment by kovidgoyal** [comment]
Just turn on mouse support in vim and you wont need workarounds like
that.
