### ISSUE TITLE
Disable resizing information

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#1591]
Recent git master builds of Kitty hide the window contents during resizes and instead only show the new terminal size  (see the accompanying message  of the 0.14 release in [doc/changelog.rst](https://github.com/kovidgoyal/kitty/blob/master/docs/changelog.rst)). I understand that this decision might have been made for technical reasons (e.g. smoother resizing), but I do not understand the new behavior from a  functional or  aesthetic standpoint. 

Functionally speaking, what does displaying the exact  numerical terminal size add? I already have the ability to perceive the (relative) size of my windows---I have them right in front of me--- so the ability to glance at quickly changing numbers doesn't really help the practice of resizing all that much. More than often I am only interested in the relative terminal size as opposed to their exact size anyway (e.g. if they fill my screen or evenly divide it in some way). 

Aesthetically speaking, I find this new behavior very visually distracting. Opening new windows now quickly flashes some text, which is imo very jarring. Moreover, due to me using a tiling wm any resize from any app makes kitty change it's inner text and so provides a continuous visual distraction (more so, opening a kitty window next to some other kitty windows makes them all flash). 

If you're not interested in restoring the old behavior in any form, I think I would even prefer to have my kitty windows be blank when creating or resizing them over them flashing some text which I have no need for.

**Comment by kovidgoyal** [comment]
I have no objections to having an option to turn off drawing text, it
should be trivial five line patch, PRs are welcome. Note that the window
will still be blanked.

Something has to change when windows are resized, you can always set the
option for resize_debounce_time to 0 that should greatly reduce the
amount of perceived change.

**Comment by rien333** [comment]
Thanks for your reply and all your work! I'll definitely have a go at a PR whenever I find the time. 
I can't help but wonder though, is the current/0.13.3 resizing behavior really that bad that it warrants such non-standard behavior as complete screen erasure?  I can't think of any other GUI app that does this, terminal and non-terminal alike. Even super old 90s GUI apps didn't  do this I think, and kept the old content stationary until the resize  had finished so the user always knew what of all his windows represented and never lost acces to their contents. Maybe I'll get used to it, but I find the blanking to be somewhat odd looking.

**Comment by kovidgoyal** [comment]
leaving the old rendered content on screne means it will be partially vut off (when decreasing size) or have blank borders around it when increasing size. I find those far more unsightly.

**Comment by Luflosi** [comment]
On macOS the content used to be stretched when resizing, not cut off or with blank borders.

**Comment by kovidgoyal** [comment]
yes stretching is obv another option. Which IMO looks even weirder than
borders

**Comment by rien333** [comment]
Thank you for looking into this issue, your work on Kitty is much appreciated! :smile:

**Comment by Luflosi** [comment]
Why did you make `scale` the default? I thought you didn't like it? I don't mind a different default.

**Comment by kovidgoyal** [comment]
Because that is the closest to existing behavior and given that
there is not much difference here, I prefer not to change existing
behavior.

**Comment by trygveaa** [comment]
Could you add an option to cut off the text/add padding when resizing? I think that would be the closest to the old behavior, and it would cause the least visual noise since what is drawn will only change after the resizing is complete.

**Comment by kovidgoyal** [comment]
> Could you add an option to cut off the text/add padding when resizing? I think that would be the closest to the old behavior, and it would cause the least visual noise since what is drawn will only change after the resizing is complete.

That's rather more work than I am interested in, but patches are
welcome.

**Comment by trygveaa** [comment]
Alright, I see.
