### ISSUE TITLE
Don't resolve symlink passed to --directory

### ISSUE THREAD

**Issue by rightaway** [kovidgoyal/kitty#1595]
I'm opening kitty with `--directory` but it looks like it resolves the symlink before going to the path. The directory should be opened as given with no symlink resolution. I think it could be the default behavior but if it not then maybe a config option not to resolve symlinks?

**Comment by egmontkob** [comment]
I doubt Kitty explicitly resolves anything. Instead, I think it changes to the given directory, and when the child process is launched it's by Unix design that the path that led there (possibly including symlinks) isn't forwarded, it's just the final location that the child process (shell) is aware of, which will be displayed using its canonical path.

The solution Kitty could apply is to set the `PWD` environment variable to the given string. See e.g. `get_current_dir_name(3)`. By convention, if this environment variable is set and indeed points to the current directory then the path contained in this variable (possibly containing symlinks) is used. This is supported by at least `bash`, but I assume pretty much all shells.

**Comment by rightaway** [comment]
Child process in this case means the shell that's launched?

I hope there's a way to change it either in terminal or shell or somewhere because right now I'm manually changing to the symlink dir instead of opening it there automatically because the original dir names are very messy (I know it's just a cosmetic minor thing though).

**Comment by egmontkob** [comment]
Yep the child is usually the shell.

Meta: I'm not Kitty's developer, and my comment was primarily addressed to him. He may or may not be aware of PWD's aforementioned behavior, I don't think it's common knowledge. If he accepts my proposal and sets PWD in Kitty, it'll just work for you. Until then, a wrapper script in front of Kitty which exports this variable and starts Kitty with the same `--directory` probably works as well (at least works for me).

**Comment by kovidgoyal** [comment]
sure setting PWD seems like a a worthwhile thing to do.
