### ISSUE TITLE
Kitty unable to find fonts

### ISSUE THREAD

**Issue by isaaclo123** [kovidgoyal/kitty#1596]
When running the command kitty list-fonts, only a few of the many fonts installed on my system appear. Some of them are locally installed (in ./local/share/fonts) and other ones are installed system wide. However, kitty can still utilize and show fonts that are not in the "list-fonts" output. However, when using any of the fonts not in list-fonts, the font will not display correctly.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font
