### ISSUE TITLE
Unicode character prints trailing space

### ISSUE THREAD

**Issue by jneidel** [kovidgoyal/kitty#1597]
See issue description at [tmux/1728](https://github.com/tmux/tmux/issues/1728)

As described [here](https://github.com/tmux/tmux/issues/1728#issuecomment-490522779):
[this](https://github.com/tmux/tmux/files/3157931/bad.txt) is the text the tmux prints to the screen, which on kitty includes the space:
![2019-05-08-171258_1440x900_scrot](https://user-images.githubusercontent.com/25589715/57386495-c2eee980-71b4-11e9-9c6d-2b2dcd23ad00.png)

whereas it does not on, e.g. terminator:
![2019-05-08-173120_1440x900_scrot](https://user-images.githubusercontent.com/25589715/57387738-2f6ae800-71b7-11e9-912f-8e87640997d9.png)

System:
```
os: arch linux
kitty -v: 0.13.3
--config NONE
```
[font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraMono/Regular/complete)

Edit:
[Here is the stripped down command to reproduce this (the space is red, when it is supposed to be green):](https://github.com/tmux/tmux/issues/1728#issuecomment-490590101)
```
echo -e '\e[41mfoo\ue0ba\e[42m bar\e[m'
```

**Comment by kovidgoyal** [comment]
I cannot replicate on kitty running from master, see screenshot, space is green, as expected.

```
kitty bash -c "echo -e '\e[41mfoo\ue0ba\e[42m bar\e[m'; read"
```
![Screenshot_20190509_153147](https://user-images.githubusercontent.com/1308621/57445343-c1362c00-726f-11e9-9614-8ab2f0185296.png)

**Comment by jneidel** [comment]
Yeah, does not occur in the git version either.
[AUR](https://aur.archlinux.org/packages/kitty-git/)

**Comment by Luflosi** [comment]
That version in the AUR is outdated. https://www.archlinux.org/packages/community/x86_64/kitty/ has 0.13.3, while the AUR has 0.13.1.

**Comment by jneidel** [comment]
> That version in the AUR is outdated.

Thats what I thought as well.
> 0.13.3, while the AUR has 0.13.1.

The AUR version is also 0.13.3 (when installed).

The problem only exists in the official package, while it does not it the AUR one.

**Comment by Luflosi** [comment]
> The AUR version is also 0.13.3 (when installed).

Oh, ok. I assumed the name of the package indicated the real version. Now I know better, thanks for that.

**Comment by trygveaa** [comment]
> That version in the AUR is outdated. https://www.archlinux.org/packages/community/x86_64/kitty/ has 0.13.3, while the AUR has 0.13.1.

git packages in AUR are built from the git repo on installation, so it will always build the up to date master branch (or another branch if specified). Because of this, the packages usually aren't updated when new versions are released because it's not necessary. So the version number shown on the web page just references whatever version was the most recent when the package was updated, but it doesn't mean anything (the version number on your machine will be set on installation and will be correct).
