### ISSUE TITLE
Text is rendering differently in kitty vs konsole/alacritty

### ISSUE THREAD

**Issue by tbodt** [kovidgoyal/kitty#1598]
I noticed the font rendering looks the same in alacritty and konsole, but kitty looks different. Here are some screenshots. Both are with the font set to Fira Code and font size set to 7.

Alacritty:
![2019-05-08-101657_1436x504_scrot](https://user-images.githubusercontent.com/5678977/57394676-ef860f80-717a-11e9-9bce-1689dbca5eb4.png)

Kitty:
![2019-05-08-101702_1436x504_scrot](https://user-images.githubusercontent.com/5678977/57394677-ef860f80-717a-11e9-9463-475edd5666dc.png)

It almost looks like kitty has scaled down the text very slightly in the Y axis. It's also rendering a ligature out of two characters with different colors, but that's not really a problem.

Here's my kitty config file (in its entirety):
```
font_family Fira Code
font_size 7
font_size_delta 1

foreground #c5c8c6
background #1d1f21

color0 #1d1f21
color1 #cc6666
color2 #b5bd68
color3 #e6c547
color4 #81a2be
color5 #b294bb
color6 #70c0ba
color7 #373b41
color8 #666666
color9 #ff3334
color10 #9ec400
color11 #f0c674
color12 #81a2be
color13 #b77ee0
color14 #54ced6
color15 #282a2e

scrollback_lines 100000
```

**Comment by kovidgoyal** [comment]
kitty simply uses freetype to render text, which most other programs also use on Linux. So I dont really see how it could be rendering text differently. Most likely you are on X11 where there is no accepted standard for DPI retrieval. kitty uses Xft.dpi falling back to physical monitor dpi if that is not available. try setting it.

**Comment by autra** [comment]
@kovidgoyal I know this is very old, but according to my tests, alacritty, konsole, xterm and libreoffice all render fonts exactly the same. Only kitty behaves differently, and I'm on wayland.

I can provide screenshots if you want. I think this should be reopened.

**Comment by kovidgoyal** [comment]
Rendering like any other program is not a goal for kitty. And note that kitty provides way more flexibility to adjust rendering than any of the programs you mentioned. Start with reading up on text_composition_strategy in kitty.conf. Almost certainly whatever "difference" you perceive comes from that. Good luck.

**Comment by autra** [comment]
@kovidgoyal thanks for your quick answer!

I understand your point about rendering not being your goal. However, let me just argue than when choosing a font, a user would like to avoid rendering differences between program... 

That being said, the pointers you gave me were very useful. In the end, I used settings nearer those of macos (especially `text_composition_strategy 1.0 30`) and that makes the rendering virtually identical to the others.

Thanks again!
