### ISSUE TITLE
Font spacing issue

### ISSUE THREAD

**Issue by bthiebault** [kovidgoyal/kitty#1599]
Here you can see my termite terminal (top) and my kitty terminal (bottom).

They both use the same font, RobotoMono Nerd Font in size 10. They both look the same size, but the spacing between characters is bigger with kitty. Is there a setting I missed or is this a bug?

Here is what the fc-list command returns

```
fc-list : family spacing | grep Roboto
Roboto
RobotoMono Nerd Font:spacing=100
RobotoMono Nerd Font
Roboto Condensed
RobotoMono Nerd Font Mono
```

![Screenshot_2019-05-09_00-24-51](https://user-images.githubusercontent.com/50426075/57412459-05361c00-71f1-11e9-9805-323cabd20cb1.png)

**Comment by kovidgoyal** [comment]
1) Dont use patched fonts, they are often buggy. There is no need, kitty will pick characters from the installed NERD Font automatically.

2) If you dont like the amount of width between characters, you can control is via the adjust_cell_width setting in kityt.conf but beware that doing so could lead to some wider characters being downscaled when rendered.

**Comment by bthiebault** [comment]
Thank you for your answer.

I have some additional questions:

- How do you know a font is patched?
- What do you mean by "kitty will pick characters from the installed NERD Font automatically"? I want to use the RobotoMono Nerd Font, and what I did is just (in the config file) :

```
font_family      RobotoMono Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto
```
How do I tell kitty to "automatically" choose the appropriate Roboto Font?

**Comment by kovidgoyal** [comment]
If it has "Nerd" added to its name its patched. Simply install the
standalone NERD fonts. When you use a symbol for which they have a
glyph, kitty will pick it up automatically and use it.
