### ISSUE TITLE
Feature Request: Add support for using as external terminal in VSCode

### ISSUE THREAD

**Issue by nikhilkamineni** [kovidgoyal/kitty#1600]
VSCode has a setting (`terminal.external.osxExec`) that lets you specify an external terminal app that that you can use, for example, to launch a debugger.

It works with other terminal apps like iTerm or macOS's Terminal (I've only tried this on macOS) but when setting the value of this setting to `"kitty.app"` an error message pops up saying "Cannot launch debug target in terminal ('kitty.app' not supported)."

**Comment by Luflosi** [comment]
I've noticed the same behaviour in a different program. I tried to figure out what iTerm does to tell macOS, that it is a terminal emulator but I didn't manage to figure that out.

**Comment by Luflosi** [comment]
I just played around with it some more and thought that adding
```XML
<key>CFBundleDocumentTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Shell</string>
		<key>LSItemContentTypes</key>
		<array>
			<string>public.unix-executable</string>
		</array>
	</dict>
</array>
```
to the `Info.plist` file would do the trick but apparently not.

**Comment by kovidgoyal** [comment]
I know of nothing kitty can do to advertise itself as a terminal emulator tht it does not already do. If anybody else knows, feel free to send a patch, will be gladly accepted. Although if you ask me, if a user explicitly configures some program why should the hist application care whether it is a terminal or not? it should just execute it.

**Comment by Luflosi** [comment]
Do you think we can bother gnachman and ask him what iTerm2 does to tell macOS that it is a terminal emulator?

**Comment by kovidgoyal** [comment]
Isn't vscode open source, should be simply to look for whatever it is checking for to determine that kitty.app is not supported. If I were to guess it's most likely a hardcoded list of terminals.

**Comment by nikhilkamineni** [comment]
Relevant areas in the vscode source seem to be here: https://github.com/microsoft/vscode/blob/a69d0f8b218498e22b7c3a0f76926cc6322e6106/src/vs/workbench/contrib/externalTerminal/electron-browser/externalTerminalService.ts#L139

and here:
https://github.com/microsoft/vscode/blob/a69d0f8b218498e22b7c3a0f76926cc6322e6106/src/vs/workbench/contrib/debug/node/terminals.ts#L129

It's checking specifically for the Terminal.app or iTerm.app and running a corresponding applescript.

If I have some free time I may work on making a contribution to vscode that adds support for kitty. Unless that's something @Luflosi or anyone else wants to do instead.
