### ISSUE TITLE
After leaving window open for a while, text becomes black/white

### ISSUE THREAD

**Issue by xuanruiqi** [kovidgoyal/kitty#1601]
After I leave a Kitty window for a while, sometimes the text becomes black/white, with all previously colored text becoming black.

I suspect that this could be a OpenGL driver bug and not a Kitty issue. My OpenGL driver is the proprietary OpenGL driver provided by NVIDIA.

Here is my `kitty --debug-config` output:

```
kitty 0.13.3 created by Kovid Goyal
Linux Xuanrui 5.0.14-1-clear #1 SMP Wed May 8 14:03:33 EDT 2019 x86_64
Running under: X11
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/xuanrui/.config/kitty/kitty.conf

Config options different from defaults:
background            Color(red=0, green=40, blue=54)
font_family           Consolas
font_size             12.0
initial_window_height (600, 'px')
initial_window_width  (1000, 'px')
remember_window_size  False
shell                 zsh -l
```

**Comment by kovidgoyal** [comment]
I dont have nvidia hardware to test with (I avoid them because of poor drivers/bad community integration), so I cannot test your exact scenario. But I cannot replicate on either AMD or Intel graphics cards. 

Try using the nouveau drivers and see if the bug goes away.
