### ISSUE TITLE
xmodmap makes kitty an unresponsive CPU hog for several seconds

### ISSUE THREAD

**Issue by hakonrk** [kovidgoyal/kitty#1606]
Just observed a weird interaction between kitty and xmodmap. Try executing

$ `xmodmap -pke | xmodmap -` 

from any terminal (xterm, kitty, etc - it does not matter who executes the xmodmap command). The important thing is that at least one instance of kitty is already running at the time xmodmap is executed.

The `-pke` flag makes xmodmap dump the current keymap table to stdout, in a form that xmodmap parse. In other words, `xmodmap -pke | xmodmap -` does not change anything, since all keys are remapped to their current values. What is interesting is that the xmodmap remapping causes all instances of kitty to go into a state where they become _completely_ unresponsive for a long time. Even the cursor stops blinking, and the mouse cursor becomes invisible if you move it over a kitty window. This lasts for about 25 seconds on my system. During this time, all instances of kitty show up in `top` with close to 90% CPU usage.

Note that, xmodmap does not take 25 seconds to finish. If I run the xmodmap command from xterm, I can see that it finishes in a fraction of a second. kitty is stuck long after xmodmap is done. It is like each remap event sent by xmodmap is queued by kitty, and it does something extremely computationally expensive on every queued remap event.

**Comment by kovidgoyal** [comment]
It's likely that doing that generates lots of configurenotify events, which cause kitty to reload the keymap. IIRC @martinetd foudn something similar when changing layouts. 

Simplest fix is probably to just debounce those events.

**Comment by hakonrk** [comment]
I just added some debug code to the event handler (processEvent() in glfw/x11_window.c. No events are processed during the 25 seconds kitty is stuck.

**Comment by kovidgoyal** [comment]
Then profile it to see what it is doing, instructions for profiling are on the website.

**Comment by kovidgoyal** [comment]
Let me know if you need help setting up the profiling.

**Comment by hakonrk** [comment]
Thanks, I will let you know if I need any help. I thought I would give callgrind a try first, though. I do not have much experience with profilers, but I have had success with callgrind in the past.

**Comment by hakonrk** [comment]
kitty is spending 98.7% of its time in glfw_xkb_compile_keymap(), which is called by _glfwDispatchX11Events().

**Comment by kovidgoyal** [comment]
dispatch simply calls processEvent so that does not make sense with your
previous comment??

**Comment by hakonrk** [comment]
That's what callgrind tells me. Here's a screenshot from my callgrind frontend:
[https://i.postimg.cc/yYM6mT8Y/profiling-result.png](url)

By the way, I'll be AFK for a while now. Won't have time to keep investigating this before Sunday.

**Comment by kovidgoyal** [comment]
I tried adding a printf() at the start of postEvent and I got continuous output from it while xmodmap was running. You probably didn't see the output when you were doing it because you were printing it out to another kitty instance which was itself frozen. Try running  kitty from naother terminal and then issue the xmodmap.

**Comment by hakonrk** [comment]
The reason my printf statements in processEvent() did not produce any output was that I had placed them just before `switch (event->type)`, _not_ at the start of processEvent() which I should have done. If I had bothered to look at the code between the start of the function and the switch-statement, I would have noticed that processEvent() also does some event processing before it enters the switch statement, and that's where the XkbMapNotify events were processed. Anyway, it doesn't matter anymore, because the profiler has shown that the issue is caused by glfw_xkb_compile_keymap() being called too many times, so I'll focus my attention on fixing that.

I will try to make a patch for this issue on Sunday, unless someone else fixes it in the meantime. For me, the challenge will be to figure out which XkbMapNotify events can be ignored and when glfw_xkb_compile_keymap() actually needs to be called. Any tips would be appreciated.

**Comment by kovidgoyal** [comment]
I doubt there is anyway to know which events can be ignored. The
simplest solution, as I mentioned before, is to simply debounce the
events. So when the first XkbMapNotify is received, set a boolean flag.
Then when any other keyboard related event, such as press/release or
statenotify or new keyboard is received, do the keymap update and clear
the flag. This way any number of consecutive updates will never result
in more than one call to compile keymap.
