### ISSUE TITLE
Unable to bind arrow key presses with bindkey in zsh

### ISSUE THREAD

**Issue by joelostblom** [kovidgoyal/kitty#1607]
I am unable to bind up and down arrow presses to history substring search in zsh. Running `cat -v` and `showkey -a` reports up arrow as `^[[A`, and this binding works in `termite`, but not in `kitty`.

So far, I have tried the following without any luck

    bindkey "$terminfo[kcuu1]" history-substring-search-up
    bindkey "\E[A" history-substring-search-up
    bindkey "^\E[A" history-substring-search-up
    bindkey "^[[A" history-substring-search-up
    bindkey "\EOA" history-substring-search-up
    bindkey "^\EOA" history-substring-search-up
    bindkey "^[0A" history-substring-search-up

I tried following the instruction in a [link you posted previously](https://github.com/kovidgoyal/kitty/issues/796#issuecomment-411267558), but adding the following to my `.zshrc` had no effect.

    [[ "$terminfo[kcuu1]" == "^[O"* ]] && \
                   bindkey "${terminfo[kcuu1]/O/[}" \
                   history-substring-search-up

I also tried the [.zshrc config you posted](https://github.com/kovidgoyal/kitty/issues/29#issuecomment-272597768), but to no avail. At this points I guess I am missing something simple and would greatly appreciate any pointers of what I am doing wrong.

**Comment by joelostblom** [comment]
I should note that I am also unable to bind ctrl-P (`^P`) and ctrl-N (`^N`) in the same manner, but these bindings are not working in `termite` either. Binding other single keys such as just `j` or `k` works in termite, but not in kitty, so I guess this is not related to escape sequences as I thought at first.

**Comment by kovidgoyal** [comment]
The correct bindings, from my zshrc are:

```
    bindkey "^[[A" up-line-or-beginning-search # Up
    bindkey "^[[B" down-line-or-beginning-search # Down
``

**Comment by joelostblom** [comment]
Thanks for the reply. The issue was that I sourced oh-my-zsh after redefining these keybindings and it would produce the behavior I described above only when running in tmux which I had set to autostart in kitty but not in termite. Sorry for the noise.
