### ISSUE TITLE
Mouse input support

### ISSUE THREAD

**Issue by sorenbug** [kovidgoyal/kitty#1609]
Relevant documents:
- DECSET: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_ (Find `CSI ? Pm h`)
- SGR 1006 mode: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Extended-coordinates

If this feature already does exist, as far as I can tell I can't use it. Tmux doesn't allow me to click to change windows and emacs doesn't allow me to click to do anything.

**Comment by kovidgoyal** [comment]
It already exists. All these programs use various silly euristics to detect mouse support in the underlying terminals. Turn it on explicity in their config and you will be fine.

**Comment by sorenbug** [comment]
30 year old standards back at it again. Sorry for the bother.
