### ISSUE TITLE
Text rendered half-width on new terminals after disconnecting second screen

### ISSUE THREAD

**Issue by koirikivi** [kovidgoyal/kitty#1610]
I have started my X session with two screens connected. However, after running `xrandr -s 0`, new Kitty terminals have all text in half-width:

![one-screen](https://user-images.githubusercontent.com/1846933/57608930-97824b00-7576-11e9-8ebf-b4f53563df4c.png)

Making sure the second screen is physically connected and running the following `xrandr` script to restore my monitor configuration fixes the issue when a new terminal is opened:

`xrandr --output HDMI-1 --off --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-2 --off --output DP-1 --mode 1920x1080 --pos 1920x0 --rotate normal`

Output from first screen when two screens connected (works as expected):
![two-screens](https://user-images.githubusercontent.com/1846933/57608554-d82d9480-7575-11e9-8a4c-dc902a4fe15a.png)

Running xmonad on Ubuntu. Apologies if this is a noob issue, as I'm not very used to Linux desktop config.

Outputs from `xrandr` attached:

[xrandr-one-screen.txt](https://github.com/kovidgoyal/kitty/files/3172009/xrandr-one-screen.txt)

[xrandr-two-screens.txt](https://github.com/kovidgoyal/kitty/files/3172010/xrandr-two-screens.txt)

**Comment by kovidgoyal** [comment]
Set Xft.dpi via xrdb and you should be fine.

**Comment by koirikivi** [comment]
Thanks, it works indeed.
