### ISSUE TITLE
Text hidden in vim after "▶︎" char

### ISSUE THREAD

**Issue by ggsalas** [kovidgoyal/kitty#1611]
Hi, I have problems to read code with symbols.
On this screenshot you can see the default macos terminal and kitty terminal at the bottom. Both terminal have the same file open with neovim, but on kitty the symbols `◀︎ ▶︎` and the `</div>` are hidden. 
![image](https://user-images.githubusercontent.com/8403993/57624460-58e59400-7568-11e9-8536-257d03ec01f0.png)

I add the file here
[App.js.zip](https://github.com/kovidgoyal/kitty/files/3173029/App.js.zip)

I'm using:
- kitty: 0.13.3
- nvim: 0.3.4
- macos: 10.14.4

Regards

**Comment by kovidgoyal** [comment]
I have committed a fix for the triangle not being rendered because of the presence of the VS15 variation selector. i cannot however reproduce the div not being rendered on my system with nvim 0.3.5

**Comment by ggsalas** [comment]
Hi @kovidgoyal I have updated to neovim 0.3.5 and the bug is the same (without `</div>`)
There is a simple way to test your fix or is better wait for the next release? 
Thanks!

**Comment by Luflosi** [comment]
You can compile from source, it is pretty simple IMHO, see https://sw.kovidgoyal.net/kitty/build.html.

**Comment by ggsalas** [comment]
Great! I have tested and is working perfect now!! 🎉 

There is a way to get notified on the next release to remember upgrade kitty?

**Comment by Luflosi** [comment]
After enough people asked for an update notification mechanism in #1108 and #1342, @kovidgoyal  implemented such notifications in https://github.com/kovidgoyal/kitty/commit/d3ad15dc516515329fb4f85f43867168d1dd30a7.

**Comment by Luflosi** [comment]
But of course, you can still use the other ways to get notified, e.g. if you click the watch button at the top of the GitHub page and choose "Releases only" or via RSS feeds.
