### ISSUE TITLE
Warning sign is rendered small

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#1612]
I've looked into better rendering of the warning sign (`U+26A0`), but it seems like it is rather tiny/small with all the fonts I've tried.

This is with `symbol_map U+26A0 Code2000` (where it appears to be extra small; zoomed a lot):

![2019-05-14-015805_503x102_escrotum](https://user-images.githubusercontent.com/9766/57661646-0bab0600-75ec-11e9-9052-eed09ff62946.png)

How does it look / work for you?  Which font?

It is not possible to have different font sizes / zoom levels for symbol map entries, is it?  Would that be something to consider?

I've only checked the Python `wcwidth`, which returns 1 for it.

**Comment by kovidgoyal** [comment]
You need to use the emoji variation selector to render it in width 2, i.e. follow the warning unicode codepoint by \ufe0f

**Comment by blueyed** [comment]
Oh, thank you!
Unfortunately this does not work in Neovim / Vim (https://github.com/neovim/neovim/issues/7151#issuecomment-395065888).
