### ISSUE TITLE
Error opening terminal: xterm-kitty

### ISSUE THREAD

**Issue by sergiotapia** [kovidgoyal/kitty#1613]
```
MacBook-Pro:~ sergiotapia$ sudo nano ~/.ssh/config
Password:
Error opening terminal: xterm-kitty.
MacBook-Pro:~ sergiotapia$ 
```

Any ideas how to fix this? This is a brand new Mac.

**Comment by sergiotapia** [comment]
From stackoverflow:

` export TERM=xterm`

And it works.

**Comment by Luflosi** [comment]
This is actually not the correct solution, see https://sw.kovidgoyal.net/kitty/faq.html#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo for something that should work and https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.term for why it is a bad idea to change the TERM environment variable

**Comment by sergiotapia** [comment]
So I just copy these commands verbatim into my kitty terminal?

```
sudo … TERMINFO=$HOME/.terminfo bash -i
sudo … env TERMINFO=$HOME/.terminfo bash -i
TERMINFO=/home/ORIGINALUSER/.terminfo exec bash -i
```

**Comment by kovidgoyal** [comment]
Either instal the kitty terminfo file system-wide or follow the
instructions in the FAQ. Either approach will work.

**Comment by tsujp** [comment]
I had to use a small workaround as the `Defaults` visudo section of the FAQ didn't work for me, commented on the following issue: https://github.com/kovidgoyal/kitty/issues/579

**Comment by qbaze** [comment]
Unless correctly supported I applied locally a quick WAD as below, no side effects yet.

1. create ssh wrapper in /usr/local/bin

**Comment by qbaze** [comment]
side effects
- works only for a user one logins with
- doesn't work with git over ssh if the server uses a git shell

**Comment by qbaze** [comment]
Just a quick update, the better approach is to override TERM with the globally known one when using ssh, no side effects then.

```
#!/bin/bash
#echo "ssh.wrapper"

if [ "$TERM" = "xterm-kitty" ]; then
        TERM=xterm #should work most of the times, you could try any of the globally known ones e.g. screen, rxvt, vt100 etc. 
else
        /usr/bin/ssh "$@"
fi
```

**Comment by kovidgoyal** [comment]
You should never override TERM, TERM is how applications know what escape sequences the terminal expects, and what features it supports. You change that and things will break.

**Comment by qbaze** [comment]
True, not ideal as any workaround. 
I really like kitty and use it locally but I also work with a lot of remotes so I need this wad. 

One can experiment with different terminal emulators as an override, the less sophisticated one the less chance for issues.  For my case xterm is fine, for others the only option can be the minimalist vt100.

**Comment by BlueskyFR** [comment]
@kovidgoyal I agree with @qbaze!!
You are telling us not to override TERM but what other solution do we have?
There is a serious problem here.

**Comment by ionstormx** [comment]
@BlueskyFR I tried the command he mentioned in his FAQ and it worked for me. Replace {server_ip} with your server IP.

`kitty +kitten ssh {server_ip}`

[https://sw.kovidgoyal.net/kitty/faq.html](https://sw.kovidgoyal.net/kitty/faq.html)
keyword: terminfo

**Comment by russkel** [comment]
It doesn't work very well on an ubuntu 20.04 remote:

```
$ russ @ blah in ~ [14:16:15]
↳ kitty +kitten ssh ubuntu@192.168.1.64
ubuntu@bigmac:~$ sudo nano /etc/fstab
Error opening terminal: xterm-kitty.
```

**Comment by nowfred** [comment]
> It doesn't work with sudo on an ubuntu 20.04 remote:
> 
> ```
> $ russ @ blah in ~ [14:16:15]
> ↳ kitty +kitten ssh ubuntu@192.168.1.64
> ubuntu@bigmac:~$ sudo nano /etc/fstab
> Error opening terminal: xterm-kitty.
> ```

If you have permissions on the server and you're comfortable with it, `sudo apt install kitty` on the remote will solve the issue.

**Comment by Luflosi** [comment]
Installing `kitty-terminfo` should be enough.

**Comment by russkel** [comment]
Thanks for the suggestions. I have been forcing `TERM=xterm` and it's working fine.

**Comment by ShayBox** [comment]
I'm sorry guys but I don't know how kitty and other terminals with the same problem have gotten so far without some kind of automatic or manual fallback, copying files or installing packages on a remote host is not an acceptable solution in a lot of cases, and overriding TERM barely works at best, there needs to be a fallback that makes kitty use xterm internally so there's no problems connecting to any remote machine.

**Comment by hedefalk** [comment]
Possibly dumb question - I would be fine if I just could find a kitty-specific startup script so I could just:

alias ssh="kitty +kitten ssh"

just for kitty. For now I stuck this in my fish config, but would rather have this in my kitty dotfiles:

```
if test "$TERM" = "xterm-kitty"
  alias ssh="kitty +kitten ssh"
end
```

**Comment by louwers** [comment]
Why do I need to modify systems I `ssh` into just to use this terminal emulator??

**Comment by BlueskyFR** [comment]
> Why do I need to modify systems I `ssh` into just to use this terminal emulator??

Because the key bindings it uses are not pre-installed with your system. Only the most popular terminals terminfos comes by default.

**Comment by sigboe** [comment]
> If you have permissions on the server and you're comfortable with it, `sudo apt install kitty` on the remote will solve the issue.

This is not acceptable in. I interact with hundreds of servers with different distros, and different owners, and many have ephemeral environments which only lasts one boot.
Kitty is the best terminal emulator I have tried, I love it, but I will be looking for what is the next big thing. But I will be limited to whatever is supported by ncurses-terminfo. This is ridiculous. Unless the people at ncurses come to their senses and accept kitty into the fold, or at the very least explain to @kovidgoyal what they expect of him to integrate the terminfo.

I'm just frustrated, and angry at everyone except @kovidgoyal 😢

**Comment by BlueskyFR** [comment]
> > If you have permissions on the server and you're comfortable with it, `sudo apt install kitty` on the remote will solve the issue.
> 
> This is not acceptable in. I interact with hundreds of servers with different distros, and different owners, and many have ephemeral environments which only lasts one boot.
> Kitty is the best terminal emulator I have tried, I love it, Ive used it for over a year now, but this has gone on my nerves the whole time. I have to start looking at what is the next best terminal emulator for me. But I will be limited to whatever is supported by ncurses-terminfo. This is ridiculous. Unless the people at ncurses come to their senses and accept kitty into the fold, or at the very least explain to @kovidgoyal what they expect of him to integrate the terminfo.
> 
> I'm just frustrated, and angry at everyone except @kovidgoyal 😢 

I really felt the same way as you because I also connect to many remote servers, that is mainly why I switched to Alacritty. It also had its own custom terminfo but it is pre-installed with the latest versions of ncurses, and xterm (which is the default value, installed on literally every system) makes it work at 99% of its functionalities so no problem so far!
I recommend you to take a look at it :)

**Comment by sigboe** [comment]
> 
> 
> > > If you have permissions on the server and you're comfortable with it, `sudo apt install kitty` on the remote will solve the issue.
> > 
> > 
> > This is not acceptable in. I interact with hundreds of servers with different distros, and different owners, and many have ephemeral environments which only lasts one boot.
> > Kitty is the best terminal emulator I have tried, I love it, Ive used it for over a year now, but this has gone on my nerves the whole time. I have to start looking at what is the next best terminal emulator for me. But I will be limited to whatever is supported by ncurses-terminfo. This is ridiculous. Unless the people at ncurses come to their senses and accept kitty into the fold, or at the very least explain to @kovidgoyal what they expect of him to integrate the terminfo.
> > I'm just frustrated, and angry at everyone except @kovidgoyal 😢
> 
> I really felt the same way as you because I also connect to many remote servers, that is mainly why I switched to Alacritty. It also had its own custom terminfo but it is pre-installed with the latest versions of ncurses, and xterm (which is the default value, installed on literally every system) makes it work at 99% of its functionalities so no problem so far!
> I recommend you to take a look at it :)

Thank you, I will look strongly into alacritty because of what you said. I tried it before, but I couldn't do something I dont remember what, and it was so easy to do in kitty, and kitty has such good documentation, and settings. I really love Kitty, its such a shame to say goodbye to it. If I move away from kitty now, I will surly consider switching back to it at the first sign of ncurses adoption.

**Comment by dapt4** [comment]
the solution is here: 
https://www.reddit.com/r/commandline/comments/prenxh/error_opening_terminal_xtermkitty/

**Comment by HikariWS** [comment]
I don't understand properly the cause of this issue, but it's acceptable to me that new softwares have compatibility issues, specially when they change old standards. Terminal is an extremely old standard which all Unix OSes work with, so developing a terminal emulator that uses new techs and go farther from the standard might break things.

I started using Kitty recently and faced this issue when accessing a server that's still on Ubuntu 20.04 which doesn't have Kitty yet. I used the  kitty +kitten ssh and it's been working, even under sudo.

**Comment by wick3dr0se** [comment]
Either `cp -r /usr/share/terminfo <destination>` or installing specific/all terminfo packages works for building a new root

**Comment by flipphillips** [comment]
I've noticed that packages installed via `snap` (nvtop for example) don't have access to this global terminfo. Everything else seems to work fine, but if I try to run nvtop via a shell, remotely, I get the dreaded no terminfo found. All non-snap stuff works fine, emacs, etc.

**Comment by bassamanator** [comment]
What I've been doing is simply to ssh into the device via `kitten ssh user@ip.address` once, and then you can go about your normal business after that. Be sure to do it for `root` as well if you plan on doing a `sudo nano ...`.

**Comment by ndunks** [comment]
Specific for ssh, you can fix by adding `SetEnv TERM=xterm-256color` into your local `.ssh/config` file

![image](https://github.com/user-attachments/assets/0de162ad-3e05-4e79-a565-d221ec4f822a)

**Comment by ash1khan** [comment]
changing the config toml of kitty works for me. 

- Open `$XDG_CONFIG_DIRS/kitty/kitty.conf` which is in my case `~/.config/kitty/kitty.conf` 
- Look/search for commented out line `# term xterm-kitty` 
- Change it to `term xterm`

And all good in my macos laptop, nixos home server, and popos workstation. 👍

**Comment by mattes3** [comment]
From within Kitty, I used `kitten ssh myuser@myserver`. This copied the terminfo into my home directory `~/.terminfo` on the remote server. But `nano` still said it does not know the terminal. Then I did this to make it work:

`export TERMINFO=$HOME/.terminfo`

Suddenly, it worked like charm.

**Comment by wick3dr0se** [comment]
You can also do like I do with [archstrap](https://github.com/wick3dr0se/archstrap):

```bash
: 'usr/share'; [[ -d "/$_/terminfo" ]] && cp -r "/$_/terminfo" "DESTINATION/$_/"
```

Which is just copy the terminfo directory; no need for exporting an env if it's in the correct path

**Comment by gl00ten** [comment]
this is really annoying. i switched out of kitty cause of it. not sure if it's an arch only thing. dont want to remember to add extra bits to a simple ssh command.

**Comment by leleobhz** [comment]
@kovidgoyal i noticed a strange behavior from a server (A CachyOS ones - Arch based):

```
[root@deodora ~]# strace -f -s 2000 htop 2>&1| grep -i terminfo
newfstatat(AT_FDCWD, "/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=3488, ...}, 0) = 0
access("/usr/share/terminfo/x/xterm-kitty", R_OK) = 0
openat(AT_FDCWD, "/usr/share/terminfo/x/xterm-kitty", O_RDONLY) = 3
read(5, "grep\0-i\0terminfo\0", 4096)   = 17
^C
[root@deodora ~]# export | grep TERMINFO
declare -x TERMINFO="/root/.terminfo"
```

Even with TERMINFO set properly, some apps are just ignoring the variable. This behavior *DOES NOT* happens in a Debian server.

Some issues reported as "not work for me" when using `kitty +kitten ssh` maybe in fact an application issue.

**Comment by kovidgoyal** [comment]
On Thu, Oct 09, 2025 at 05:53:43AM -0700, Leonardo Amaral wrote:
> Some issues reported as "not work for me" when using `kitty +kitten ssh` maybe in fact an application issue.

Yeah the ssh kitten at this point is pretty battle tested.
Most modern widely used applications already have and will
continue to migrate off terminfo anyway, so this becomes
less and less of an issue. The terminfo database has been very poorly
managed sadly, so it is now ignored by all new terminal
libraries/software/emulators.
