### ISSUE TITLE
Image flickers with neofetch

### ISSUE THREAD

**Issue by Allmeta** [kovidgoyal/kitty#1614]
![gif demo](https://media.giphy.com/media/SYFiKYZWFF1DoNE2SX/giphy.gif)

I'm using w3m as backend for neofetch btw.

This issue does not appear in any other terminal that I have tried.

**Comment by SolitudeSF** [comment]
neofetch supports kitty image backend. and this issue is present in many terminals, you are just lucky you tested it in other terminals.

**Comment by Allmeta** [comment]
Wow alright ,didn't know that kitty had its own backend. Thanks @SolitudeSF ! Solved my issue
