### ISSUE TITLE
weird  font rendering of "fi"

### ISSUE THREAD

**Issue by tehdarthvid** [kovidgoyal/kitty#1617]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/2049325/57918589-a8f68a80-78c9-11e9-9a63-fb7109e85279.png">
kitty 0.13.3,
Menlo for Powerline,
MacOS 10.14.5

Same case for "fl", but "f1" is fine. Haven't run into other character combinations where the rendering changes like that (yet).

**Comment by kovidgoyal** [comment]
those are liagtures in whatever font you are using. use a monospace font that does not use ligatures and you will be fine.

**Comment by foxpy** [comment]
Is it possible to ignore ligatures? Would be very nice to implement, increasing supported fonts coverage.

**Comment by Luflosi** [comment]
That feature is implemented but not in a stable version yet, you would have to compile kitty from source to use that feature.

**Comment by kovidgoyal** [comment]
I doubt that would work, it only disables calt ligatures, I douby fi, ff
are implemented as calt ligatures.

**Comment by vcfvct** [comment]
+1 
Is there a way to fix this instead of changing font? The font works well in all other terminals(system/alacritty/hyper). 

Thanks.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features
