### ISSUE TITLE
1 px high clickable area above tab bar reported to child process

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1621]
Cutting an ssh connection while a vim session is open leaves the terminal in a state where mouse clicks are printed to the shell as escape codes. This lead me to discover a one pixel high area at the very top of the tab bar where mouse clicks don't change the tab but instead are reported to the child process via escape codes. I set my tab bar to be at the top of the window.
Let me know if you can easily reproduce the issue. If you can't I'll gladly provide more information.

**Comment by kovidgoyal** [comment]
Should be easy for you to fix, look at window_for_event in mouse.c

**Comment by kovidgoyal** [comment]
And I cannot replicate it on my machine.

**Comment by Luflosi** [comment]
Looks like the mouse coordinates are off on macOS. If I use the `hide_window_decorations` config option, the top left pixel should have the coordinates x=0, y=0, when printing `global_state.callback_os_window->mouse_x` (and y) in the `window_for_event()` function, right?

**Comment by Luflosi** [comment]
I think I also found a bug in the built-in macOS program "Digital Color Meter". Where it thinks the cursor is and where it actually is seems to be off by half a pixel or so (yes, mouse coordinates can have fractional values on macOS).

**Comment by Luflosi** [comment]
Yeah, I think the x coordinate is one pixel off, the range -1 to 0 seems to still be in the kitty window.

**Comment by kovidgoyal** [comment]
well mouse co-ords come from glfw, see the relevant functions in glfw.cocoa_window.py

**Comment by Luflosi** [comment]
> I think the x coordinate is one pixel off

I meant the y coordinate.
