### ISSUE TITLE
Braille font in Gotop and Gtop are not rendered right

### ISSUE THREAD

**Issue by Yash-Kaveeshwar** [kovidgoyal/kitty#1623]
The Braille font in both gotop and gtop are not rendered correctly in Kitty 0.13.3 
![2019-05-19_19-52](https://user-images.githubusercontent.com/26587446/57983499-2cea7700-7a70-11e9-9a52-d9e279fa3834.png)
Left is Terminator and the right is Kitty

**Comment by kovidgoyal** [comment]
kitty only works well with monospace fonts, what is a braille font? What would be the point of a braille font on a non-tactile screen?

**Comment by Yash-Kaveeshwar** [comment]
That font is usually used in various graphs and would be useful if it can be displayed correctly.

**Comment by kovidgoyal** [comment]
I'm still going ot need some reference as to what that font is and where I can get hold of it.

**Comment by Yash-Kaveeshwar** [comment]
it is in AUR ttf-braille the upstream for it according to AUR is http://yudit.org/download/fonts/UBraille/

**Comment by kovidgoyal** [comment]
seems to render fine in gtop on my system without needing to install a braille font. see screenshot
![Screenshot_20190519_203817](https://user-images.githubusercontent.com/1308621/57984151-7047e400-7a76-11e9-93b6-ca08828da84b.png)

**Comment by kovidgoyal** [comment]
that uses the standard symbola font

**Comment by Yash-Kaveeshwar** [comment]
Ok I'll try it then

**Comment by Yash-Kaveeshwar** [comment]
Still can't get to work. Even after installing Symbola font

**Comment by kovidgoyal** [comment]
Uninstall the braille font or use symbol_map in kitty.conf to tell kitty
to use symbola preferentially for the braille codepoints.
