### ISSUE TITLE
Docs - call attention to `mouse_hide_wait`

### ISSUE THREAD

**Issue by hangtwenty** [kovidgoyal/kitty#1626]
I love this terminal, and I've really dug into the configuration. Somehow I missed the `mouse_hide_wait` setting though. It was driving me kinda mad, and I tried to "fix" it at the OS level a couple of times. Didn't realize it was a Kitty setting.

Maybe it would make sense to reorder [the docs subheaders](https://sw.kovidgoyal.net/kitty/conf.html?highlight=mouse%20hide#opt-kitty.mouse_hide_wait) so that this setting is up at top of Mouse section. Or... maybe even having it _not_ hide the mouse in default preferences?

**Comment by kovidgoyal** [comment]
I'm afraid the default is not going to change, lots of people, including
me, prefer the mouse hidden while typing. However, I am OK with moving
the option to the top of the mouse section, feel free to send a PR. You
just have to move the option to the top of the mouse section in
config_data.py

**Comment by Luflosi** [comment]
@hangtwenty I made the pull request for you.
