### ISSUE TITLE
can i put command line parameter 'listen-on' into kitty.conf?

### ISSUE THREAD

**Issue by zk4** [kovidgoyal/kitty#1628]
First . Fantastic project! Way more  faster than iTerm2!

**My Problem:**
I need changing view from vim to shell  back and forth a lot.  
Thanks to this plugin  unifying the hotkey with kitty and vim [plugin](https://github.com/knubie/vim-kitty-navigator).
But start the kitty needs to do this 

```
kitty -o allow_remote_control=yes --listen-on unix:/tmp/mykitty
```
So, I need to start some terminal  first  to do that ..
and it print a lot of log info that I don`t need.

I can`t find any configuration  about 'listen-on' in kitty.conf .

**So my Question is :**
How can I put command line parameter 'listen-on' into  kitty.conf?
Can I disable the log output if I can put 'listen-on' in kitty.conf?

**Comment by kovidgoyal** [comment]
If you want to start kitty with particular command line parameters, you
can simply create a new .desktop file for it on linux, or follow these
instructions macOS https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos

And if you want to silence the output from any command you can use a
redirect, like this

kitty > /dev/null 2> /dev/null
