### ISSUE TITLE
Scrollback - clears on returning from command

### ISSUE THREAD

**Issue by csghuser** [kovidgoyal/kitty#1630]
Firstly, many thanks for this terminal.

I'm having an issue where once I exit a command, say exit vim, the scrollback history is cleared and I'm left with a blank window. Is this by design?

I tried with a number of other terminals an upon exiting vim, the previous scrollback history is displayed, rather than an empty window. I can scroll up with the mousewheel to view past history that had scrolled off the screen however.

**Comment by kovidgoyal** [comment]
I cannot replicate. After quitting vim both the contents of the screen and the scrollback are undisturbed. Try with wmpty kitty.conf and vimrc it's likely the interactio of some setting.

**Comment by csghuser** [comment]
@kovidgoyal thank you for the quick response. The issue was the following bash_profile line....

```export TERM=xterm```

Removing that solved the issue.
