### ISSUE TITLE
Kitty doesn't work with uniemoji

### ISSUE THREAD

**Issue by topaxi** [kovidgoyal/kitty#1636]
I'm using https://github.com/salty-horse/ibus-uniemoji to enter emojis. With kitty, when I change my layout to uniemoji, whenever I enter a character, kitty just inputs as if I'm still on my default layout.

**Comment by kovidgoyal** [comment]
Not something I am interested in investigating, but patches are welcome. Note that kitty has its own emoji input system. https://sw.kovidgoyal.net/kitty/kittens/unicode-input.html
