### ISSUE TITLE
Unicode character in tab separator

### ISSUE THREAD

**Issue by sysashi** [kovidgoyal/kitty#1640]
Excuse me for my ignorance, I could not find information about it. Is it possible to use Unicode character for tab separator? e.g.
```
symbol_map U+E0B8-U+E0BF PowerlineExtraSymbols
tab_separator U+E0B9 # or tab_separator " \uE0B9 "
```

**Comment by Luflosi** [comment]
Does putting the character directly into the config file (without any escape sequences) work?

**Comment by kovidgoyal** [comment]
Simply type in the character directly. How yo do that depends on what
editor you use. For example, in vim, use ctrl+v and then typein the four
chars of the hex code for the character.

**Comment by Luflosi** [comment]
Or just use the unicode input kitten.

**Comment by Luflosi** [comment]
@kovidgoyal you should consider adding support for using something like `tab_separator U+E0B9`.

**Comment by kovidgoyal** [comment]
That is done in general where needed, for example for send_text, where you may want to send arbitrary bytes. However, doing it here doesn't really seem necessary and it will break backwards comapt a little since now escape codes get interpreted.

**Comment by Luflosi** [comment]
Ok
