### ISSUE TITLE
The formatting for `map f1 pipe @ansi overlay less +G -R` is off on macos

### ISSUE THREAD

**Issue by nerdrew** [kovidgoyal/kitty#1642]
Using `kitty_mod+h` to `show_scrollback`, my scrollback looks like:

![Screen Shot 2019-05-24 at 09 43 13](https://user-images.githubusercontent.com/10101/58343639-69b7c480-7e08-11e9-83e1-ef61931763b0.png)

Using `f1` to `pipe @ansi overlay less +G -R -n`, my scrollback looks like:
![Screen Shot 2019-05-24 at 09 43 02](https://user-images.githubusercontent.com/10101/58343676-818f4880-7e08-11e9-9d5d-7735db200623.png)

**Comment by kovidgoyal** [comment]
Works for me, with:

```
kitty -o "map=f1 pipe @ansi overlay less +G -R -n"
```

**Comment by nerdrew** [comment]
Hmmm. I set my scrollback_lines to 200 before running the `for i in $(seq 0 400); echo $i` loop shown in the screenshot. As you can see, the syntax highlighting disappears in the `pipe` version, while it is visible in the `show_scrollback` version.

Also, there is consistently a missing newline at the first line outside of the current viewport.

Here's the prompt after running the `for` loop above:
<img width="936" alt="Screen Shot 2019-05-27 at 14 45 36" src="https://user-images.githubusercontent.com/10101/58440334-325a4980-808e-11e9-9b54-12d789eb5cf1.png">

Here's scrolling up 3 lines:
<img width="936" alt="Screen Shot 2019-05-27 at 14 45 52" src="https://user-images.githubusercontent.com/10101/58440348-4b62fa80-808e-11e9-84b4-8f11814581df.png">

Is it possible that this is caused by something in my config or a mac only issue?

**Comment by Luflosi** [comment]
I can reproduce the issue with the missing newline but the text color works for me. I'm also using a Mac.
I'm starting kitty using `kitty.app/Contents/MacOS/kitty --config NONE -o "map=f1 pipe @ansi overlay less +G -R -n"`. I scrolled two lines up.
`type -a less` outputs `less is /usr/bin/less` for me.
![screenshot](https://user-images.githubusercontent.com/15217907/58460957-eca18d80-812e-11e9-808e-c34de0d8d8ee.png)

**Comment by nerdrew** [comment]
To get the color issue, you need to have the scrollback go into the "pager" history, not the `scrollback_lines`. I used this to repro:

```
kitty -o "map=f1 pipe @ansi overlay tee boom.log" -o "scrollback_lines 100" --config NONE -o "scrollback_pager_history_size 100"
```

Then make sure you push the colorized text past the regular scrollback lines (hence the for loop in my example above).
