### ISSUE TITLE
Consider putting binary bundle inside AppImage rather than tar.xz

### ISSUE THREAD

**Issue by probonopd** [kovidgoyal/kitty#1644]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

Think of an AppImage as a self-mounting filesystem that executes the binary bundle contained inside it whenever it is launched.

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
Since you are already making binary bundles, putting them into AppImages should be very easy - let me know if you are interested, then I can write a short script.

**Comment by kovidgoyal** [comment]
Sorry no, not interested. I am quite happy with kitty's existing
binary installation infrastructure.
