### ISSUE TITLE
Wayland: Missing window decoration

### ISSUE THREAD

**Issue by archusr** [kovidgoyal/kitty#1645]
Wayland vs. X11:
![kitty-0 14 0](https://user-images.githubusercontent.com/14299209/58368622-9abef480-7eef-11e9-8270-f6367b6e43dd.png)

```
$ kitty -v
kitty 0.14.0 created by Kovid Goyal

$ kitty --debug-gl
GL version string: '3.3 (Core Profile) Mesa 19.0.5' Detected version: 3.3

$ pacman -Q gnome-desktop kitty linux mesa wayland
gnome-desktop 1:3.32.2-1
kitty 0.14.0-1
linux 5.1.4.arch1-1
mesa 19.0.5-1
wayland 1.17.0-1
```

**Comment by kovidgoyal** [comment]
This is a limitation of glfw which kitty uses. When the compositor does not support server side decorations, glfw draws a plain white rectangle as window decorations.

**Comment by daenney** [comment]
Unfortunately this renders Kitty pretty unusable on Gnome. It might be worthwhile detecting this by looking at `DESKTOP_SESSION=gnome` and not using the Wayland backend.

**Comment by kovidgoyal** [comment]
Why would missing close and minimize buttons render kitty unusable?

**Comment by daenney** [comment]
It's not just that, the window is now fullscreen by default and you have no window decorations to resize it by. I can't even figure out how to resize Kitty on Gnome right now.

**Comment by kovidgoyal** [comment]
I'm confused, as far as I recall, glfw does draw decorations, a plain white rectangle, which is what you show in your screen shot as well. 

Oh and for reference, here is the discussion where the GNOME developers refuse to fix this issue: 
https://gitlab.gnome.org/GNOME/mutter/issues/217

**Comment by kovidgoyal** [comment]
I just tried it with weston, which aslo has no server side decorations and using the plain borders provided by glfw to move and resize the window works fine for me.

**Comment by kovidgoyal** [comment]
Oh and if you are on older versions of gnome, resizing probably wont work because of this bug: https://bugzilla.gnome.org/show_bug.cgi?id=781811
