### ISSUE TITLE
Feature request: minimal cli for remote control

### ISSUE THREAD

**Issue by tammersaleh** [kovidgoyal/kitty#1646]
I use Kitty on my laptop, and I often ssh into other servers.  In order to make use of the remote-control features, I need to install all of Kitty on those instances (including python, etc).  I'd love to have a tiny CLI that I can install instead, which doesn't have the Kitty terminal features, but only knows how to send remote-control commands.  Ideally, this CLI would be statically compiled for easy installation.

Alternatively, could you publish the remote-control protocol so we might be able to make such a CLI ourselves?

**Comment by kovidgoyal** [comment]
I'm not particularly interested in creating a standalone client, but I
am definitely willing to document the protocol.

**Comment by daniel-pfeiffer** [comment]
I have already created such a beast in pure Shell (bash or busybox sh).  Currently I can't grab the response, and awk (available even on embedded platforms) might not be enough to parse it, but the sending part works.  There is a simple little language, which creates the cumbersome json-message and echoes it to kitty.

    function kitty_ {
	local noresp=+ stty
    #    [ "x$1" = x-r ] && { noresp=-; shift; trap "stty $(stty -g); trap - RETURN INT" RETURN INT; stty -echo; }

	local cmd=$1
	shift

	[ $# -gt 0 ] && set payload\{ "$@" \} # wrap into outer parts of json msg
	set cmd:$cmd version.'[0, 14, 1]' "$@" no_response$noresp

	local json sep='' arg key val
	for arg; do
	    key=${arg%%[^a-z0-9_]*} # can't do this in case, e.g. *.* wrongly grabs id:a.b
	    val=${arg#$key}         # cut off rest
	    case $val in
		'') val=null;;
		+) val=true;;
		-) val=false;;
		.*) val=${val#.};;
		:*) val=${val#:}; val=${val//\\/'\\\\'}; val=\"${val//\"/\\\"}\";; # in dash redo last 2 in sed
		\{) json="$json$sep\"$key\": {"; sep=''; continue;;
		\}) json="$json}"; sep=', '; continue;;
		*) echo "wrong '$arg' -- use: key key+ key- key.literal key:string key{ }"; return 1;;
	    esac
	    json="$json$sep\"$key\": $val"
	    sep=', '
	done
	cmd=-en; [ -z "$kitty_debug" ] || cmd=-E
	echo $cmd "\eP@kitty-cmd{$json}\e\\"
    #    [ $noresp = - ] &&
    #       awk 'BEGIN { RS="\33\\\\" }
    #       { sub( /^\33P@kitty-cmd{"ok": ?(false|true), "data": /, "AA", $0 ); print; exit }' </dev/tty
    #    :
    }

The args are any of key key+ key- key.literal key:string key{ }
which map to null, true, false, the exact literal, the escaped string and a nested json object.

This can be used as

    function kbgcolor {
        kitty_ set-colors title:"background=#$1" match_window match_tab all- configured- colors\{ background.$(( 0x$1 )) \} reset-
    }

or

    function ktitle {
	kitty_ set-window-title title:"$1" match temporary+
    }

I even have a poor man's scp which types a file into another window.  Usage is "kcp file window-id", or - for stdin.  It switches you to the receiving window (as a safeguard to not send MBs to wrong window).  There it typed in the receive command for you, which you complete with a filename or pipe to another command:

    function kcp {
	local id="id:${2-1}" st1 st2
	st1=$(kitty_ send-text match:$id is_binary- match_tab- text:'kcp_receive ')
	echo -n "$st1"
	st2=${st1#*kcp_receive }
	st1=${st1%kcp_receive *}
	kitty_ focus-window match:$id
	read -p "Go & start kcp_receive on $id!  Come back & return to send / ^C to cancel " </dev/tty
	base64 -w 1023 "$1" |
	    while read; do echo -n "$st1$REPLY\n$st2"; done
	echo -n "$st1\\\\4$st2"
    }

    function kcp_receive {
	echo "Go back to kcp & return to send / ^C to cancel"
	trap "stty $(stty -g); trap - RETURN INT" RETURN INT
	stty -echo
	if (( $# )); then
	    base64 -d > "$1"
	else
	    base64 -d
	fi
    }

**Comment by daniel-pfeiffer** [comment]
That didn't answer the question about the protocol.  The part of the protocol we need to care about, is the inner `payload` json object.  This reflects all the possible options of a given command.  Sadly on this level they are not optional.  That means as new options appear (and the `version` gets bumped on line 9 of `kitty_`) the following may need to be repeated.

There are 2 ways of sniffing and roughly transforming what a `kitty @` command does.  Either you run it through strace with long strings:

    strace -s 9999 -e trace=write   kitty @ send-text aha

Then you pipe what kitty writes through this command.

    # mostly transform STRACE STRING to kitty_ syntax
    sed -E 's/\\"([a-z][a-z0-9_]*)\\": /\1\cA/g;
            s/\cAnull,*//g;
            s/\cAtrue,*/+/g;
            s/\cAfalse,*/-/g;
            s/\cA([-+0-9][-+0-9.e]*),*/.\1/g;
            s/\cA\\"([^"]*)\\",*/:"\1"/g;
            s/\cA\{/\\{ /g;
            s/\cA/:/g;
            s/\\\\/\\/g'

Or, if you have Emacs M-x shell, where what `kitty @` writes just appears as output, use this:

    # mostly transform OUTPUT to kitty_ syntax
    sed -E 's/"([a-z][a-z0-9_]*)": /\1\cA/g;
            s/\cAnull,*//g;
            s/\cAtrue,*/+/g;
            s/\cAfalse,*/-/g;
            s/\cA([-+0-9][-+0-9.e]*),*/.\1/g;
            s/\cA("[^"]*"),*/:\1/g;
            s/\cA\{/\\{ /g;
            s/\cA/:/g'

Rather than my few functions with hardwired options, one could of course write more complex functions with getopt, which behave like the originals.  I had no need for such luxury.

**Comment by kovidgoyal** [comment]
There is no need for them not be optional, I haven't really designed the
current protocol with an eye towards interoperability, it can be easily
modified for that goal.

**Comment by kovidgoyal** [comment]
Note that I have not completed the documentation for individual commands, contributions are welcome!
