### ISSUE TITLE
Italics not rendered

### ISSUE THREAD

**Issue by tammersaleh** [kovidgoyal/kitty#1649]
I'm 75% sure that this is a configuration issue on my end, but I'm stymied.  I believe I'm doing everything correctly.  I have `TERM` set to `xterm-kitty`, I've installed the terminfo file, and `infocmp` correctly reports that the terminfo understands italics, however:

``` console
$ echo $TERM
xterm-kitty
$ infocmp -1x | grep itm
        ritm=\E[23m,
        sitm=\E[3m,
$ echo -e "\e[1mbold\e[0m\n\e[3mitalic\e[0m\n\e[4munderline\e[0m\n\e[9mstrikethrough\e[0m"
bold
italic
underline
strikethrough
~ $ 
```

...and a screenshot to show the actual behavior:

<img width="1025" alt="bash 2019-05-25 15-08-16" src="https://user-images.githubusercontent.com/2016/58375039-ffce1680-7efe-11e9-8083-a69f12cfe510.png">

**Also, here's something that I've never quite understood:**

I _think_ the terminfo system is there to allow applications to detect what escape codes to send to perform different actions.  If I want to start italic text, I ask the terminfo DB what the escape code is for `sitm`, which turns out to be `\E[3m`, which I then print to the screen.

If that's the case, then it shouldn't matter if I have a terminfo entry for `xterm-kitty`, given that I'm actually sending the raw escape sequences without looking them up beforehand, right?  Obviously, well-behaved programs like Vim would use it, but my `echo` above should still work fine?

**Comment by kovidgoyal** [comment]
dup of #1648

**Comment by tammersaleh** [comment]
Huh - not sure how this dupe happened - sorry about that.
