### ISSUE TITLE
emojis stop showing, starting a new kitty instance works

### ISSUE THREAD

**Issue by geekodour** [kovidgoyal/kitty#1650]
I am not sure how to reproduce this, but emojis suddenly stop showing and it works if I open new kitty instances. I've tried running `reset` but it does not seem to change anything.

![Emojis not showing](https://i.ibb.co/pb99B5w/2019-05-27-172130-445x314-scrot.png)

![Emojis showing](https://i.ibb.co/hfr5h6j/2019-05-27-172250-447x276-scrot.png)

Any help on this?

**Comment by kovidgoyal** [comment]
By stop showing you mean they were showing and you do something and they render as lines? Or do you mean they dont show from the beginning in some kittyinstances but not others?

**Comment by kovidgoyal** [comment]
And post the output of kitty --debug-config

**Comment by kovidgoyal** [comment]
no followup

**Comment by geekodour** [comment]
@kovidgoyal It didn't happen after that hence I was not able to post --debug-config output. I'll post it the next time it happens and I meant initially everything is working fine then for some unknown reason they become lines.

**Comment by kovidgoyal** [comment]
--debug-config does not have to be only when the issue occurs. It's just
for me to see what config you are using. 

And the next time the issue occurs try changing the font size and see if
that restores the icons. 

Also use --debug-font-fallback to get data on what fonts kitty is using
to draw the icons. I am guessing there is some font on yoursstem where
those icons are represented as lines.

**Comment by geekodour** [comment]
Here is the log: http://dpaste.com/3S0WNJT.txt

and resizing the fonts did restore the emojis. thanks!

**Comment by kovidgoyal** [comment]
Run it with --debug-font-fallback and see if any output is produced when the emojis change, that should tell us is my theory about another font is correct.

**Comment by Luflosi** [comment]
When I'm running kitty without my config, I sort-of reliably get that line for most nerd font symbols.
Here is a screenshot of a git branch symbol in kitty with my config:
![with](https://user-images.githubusercontent.com/15217907/58525496-3ab89e80-81cc-11e9-9425-d1d01d736c3d.png)
And with no config:
![without](https://user-images.githubusercontent.com/15217907/58525511-47d58d80-81cc-11e9-8ff5-d08b76d81521.png)
kitty prints
```
ValueError: Failed to find fallback CTFont other than the LastResort font
```
I have a big file with all the nerd font symbols in it. When I cat it in kitty without a config file, most of them are not rendered correctly (only as the weird line) and I get that error message above. Scrolling up and down and then catting the file again, makes all the newly printed symbols render correctly. `--debug-font-fallback` prints lines like
```
U+e0a0 Face(family=3270Medium Nerd Font Mono, full_name=3270-Medium Nerd Font Complete Mono, postscript_name=3270MediumNerdFontCompleteM-Medium, path=/Users/<username>/Library/Fonts/3270-Medium Nerd Font Complete Mono.otf, units_per_em=1000, ascent=8.9, descent=2.2, leading=0.0, point_sz=0.0, scaled_point_sz=11.0, underline_position=-1.4 underline_thickness=0.6)
```
I have attached the file here, maybe it helps.
[nerd-fonts-test.txt](https://github.com/kovidgoyal/kitty/files/3233617/nerd-fonts-test.txt)
