### ISSUE TITLE
Transparency doesn't work on cli apps

### ISSUE THREAD

**Issue by carz0** [kovidgoyal/kitty#1653]
Dear developer. Firstly thank you for your software.

I would want to know if kitty is making some changes that are not undone upon uninstalling.
I tried kitty but transparency only worked on default terminals but not in apps such as cmatrix.

After reading about kitty, I think this is just not supported. However after uninstalling kitty with pacman -Rns and coming back to Simple terminal this kind of behavior didn't disappear. It used to work before with st.

Thanks for your time

**Comment by kovidgoyal** [comment]
kitty makes no changes to the system whatsoever. In fact, given that its
install is done without root privileges it cannot make changes to the
system even if it wanted to.
