### ISSUE TITLE
CJK characters not rendering correctly

### ISSUE THREAD

**Issue by lxcode** [kovidgoyal/kitty#166]
CJK characters are rendering garbled, regardless of whether or not I've defined a symbol_map referencing a font that should support them:

![screen shot 2017-11-08 at 12 49 37](https://user-images.githubusercontent.com/1959603/32573642-7d47c18e-c483-11e7-9dac-62583834184d.png)

My font setup is:

font_family      Source Code Pro
italic_font      auto
bold_font        auto
bold_italic_font auto
symbol_map U+3000-U+303F,U+3040-U+309F,U+30A0-U+30FF,U+FF00-U+FFEF,U+4E00-U+9FFF Osaka

This includes the ranges for all kana and kanji. I've verified that on startup, kitty is parsing the symbol map correctly and finding the Osaka font.

**Comment by kovidgoyal** [comment]
I'm guessing you are on OS X. CJK characters are not going to work there anyway, because the wcwidth() apple uses is extremely old and reports a width of 1 for most of them. You can try setting use_system_wcwidth to no. But this will cause other problems since now the applications running in the terminal will no longer agree with kitty on how wide characters are.

**Comment by lxcode** [comment]
Sorry — yes on OS X, and with use_system_wcwidth=no. Also using git HEAD.

I saw in #165 that things were getting truncated, but in this case they don't actually resemble the characters at all, so it seems like it might be a different issue. Full config is here:

https://github.com/lxcode/dotfiles/blob/master/kitty.conf

**Comment by kovidgoyal** [comment]
Weird. I am not going to spend time on this as the font rendering code is being completely changed to use harfbuzz and support opentype advanced features such as ligatures, anyway. If it still exists after that work (which is happening in the liga branch) is merged, ping me.

**Comment by kovidgoyal** [comment]
I just tried it with the liga branch and it seems to be fixed (at least with whatever font is the default fallback on macs. I did not try Osaka). Closing, feel free to re-open if it is still a problem. 

Note that the liga branch will likely get merged into master in a day or two.
