### ISSUE TITLE
Cannot display some symbols

### ISSUE THREAD

**Issue by mvrozanti** [kovidgoyal/kitty#1661]
Some characters of the [Halfwidth and Fullwidth Forms](https://unicode-table.com/en/blocks/halfwidth-and-fullwidth-forms/) are not being displayed:

I'm using 'Fira Mono for Powerline' font, which is able to display these characters:
`ﾊﾐﾋｰｳｼﾅﾓﾆｻﾜﾂｵﾘｱﾎﾃﾏｹﾒｴｶｷﾑﾕﾗｾﾈｽﾀﾇﾍｦｲｸｺｿﾁﾄﾉﾌﾔﾖﾙﾚﾛﾝﾘｸ`

This is the output of my clipboard, containing the characters being printed in the terminal, as well as in hex. Notice the bright cyan row -- these are supposed to be the rendered characters. In the background, there's the preview of my font in `gtk2fontsel`

![image](https://user-images.githubusercontent.com/11381662/58522773-36728e00-8198-11e9-83f6-50d3b953e2c6.png)

**Comment by loeschzwerg** [comment]
Have you tried it with another font, that should be able to display it?
Do you have a reference terminal where it is working? E.g. Gnome-Terminal

**Comment by loeschzwerg** [comment]
You can try to use echo -e "\u3042 \u30a2" to display japanese 'A's
works for me:
![2019-05-31-135440_1258x998_scrot](https://user-images.githubusercontent.com/24317401/58704267-ae64d200-83ab-11e9-8ac5-66bb9d05fa19.png)

**Comment by mvrozanti** [comment]
@loeschzwerg sorry I completely forgot to respond to this issue. Yes, I can display japanese 'A's. No I don't have another terminal displaying those characters. Tried in st and xterm

**Comment by kovidgoyal** [comment]
As far as I know, Fira Code does not has glyhs for those characters. You need to install a proper CJK font on your system to display them. On my system they display correctly with Noto Sans CJK

You can check which font kitty uses for any symbol by using --debug-font-fallback
