### ISSUE TITLE
On wayland, the maximized size is wrong

### ISSUE THREAD

**Issue by cdrcnm** [kovidgoyal/kitty#1662]
On Wayland/Gnome , when kitty is maximized, the window is bigger than the screen.
Its seem that the window without the decorations is at the size of the screen.
So with the borders, the window is bigger than the screen.

kitty 0.14.0
Gnome 3.32.2
1920*1080 screen

**Comment by ellisgeek** [comment]
I can also confirm this.

**Comment by kovidgoyal** [comment]
confirm what, it is already fixed and released.
