### ISSUE TITLE
text overflows screen boundary (text not wrapping)

### ISSUE THREAD

**Issue by peschkaj** [kovidgoyal/kitty#1663]
Using kitty 0.14.0 on Arch...

I would expect that long lines would wrap in kitty. However, with kitty as the only window on the screen, I experience text not being wrapped like this:

![DeepinScreenshot_select-area_20190529101144](https://user-images.githubusercontent.com/71570/58577066-8bdf8700-81fa-11e9-8306-77c8e1f0b7bd.png)

This also happens when a pair of kitty windows are side-by-side:

![DeepinScreenshot_select-area_20190529101423](https://user-images.githubusercontent.com/71570/58577138-b03b6380-81fa-11e9-9c69-611c70c10059.png)

**Comment by Luflosi** [comment]
Try kitty 0.14.1. Looks like it is already available on Arch Linux.
And are you using Wayland?

**Comment by peschkaj** [comment]
Oh happy day, that fixed it! Resizing the window also works correctly.

I am not using Wayland, I'm using xmonad.
