### ISSUE TITLE
kitty +icat renders images at the wrong location after resizing kitty

### ISSUE THREAD

**Issue by Tyilo** [kovidgoyal/kitty#1664]
Steps to reproduce:
1. Run `kitty +icat foo.png` in a terminal
2. Resize kitty to be smaller
3. Resize kitty to its original size
4. See that the image is not positioned correctly anymore

For a screencast of this happening, see: https://gfycat.com/poshsamebactrian

**Comment by kovidgoyal** [comment]
There is no robust way to implement this. Images are placed at cell locations
on the screen, cell locations are changed by re-wrap when resizing
terminal windows.

**Comment by kovidgoyal** [comment]
Actually. I take that back, there is a way to implement it robustly, but it is sufficiently painful that I dont car enough to implement it. Basically what you do is map the cell location to some text position, like char X in line Y, then after the rewrap map that back to the cell location.

**Comment by kovidgoyal** [comment]
Apart from being painful the problem with that approach is it can potentially cause an image to be rendered partially offscreen, if after wrapping the cell moves closer to the edge of the screen. The current code tries to avoid that, at the cost of not being able to restore positions exactly. I'm not convinced, restoring positions is the better approach.

**Comment by 14Si** [comment]
It's pretty problematic for those that use tiling window managers where windows get drastically resized and even the current approach can cause images to get clipped and often cover the prompt.
