### ISSUE TITLE
Unicode arrow character doesnt fully render

### ISSUE THREAD

**Issue by dvtkrlbs** [kovidgoyal/kitty#1667]
I am using macos with the latest version and my shell is zsh and the font is IBM Plex Mono. My prompt uses `HEAVY ROUND-TIPPED RIGHTWARDS ARROW` character.  It doesnt render correctly on the prompt. It works on the other terminals i tried (Terminal.app and alacritty)

<img width="353" alt="Screen Shot 2019-05-30 at 3 05 39 PM" src="https://user-images.githubusercontent.com/24792168/58631837-734f9980-82ec-11e9-9fb4-68ba6620ade9.png">
 <img width="87" alt="Screen Shot 2019-05-30 at 3 07 10 PM" src="https://user-images.githubusercontent.com/24792168/58631899-9ed28400-82ec-11e9-9a4c-1f60b387af8f.png">

Also it is broken on most of the fonts (all the fonts i tried are monospace fonts) the only working font i tried is Menlo
Here is my config file: [kitty.conf](https://github.com/kovidgoyal/kitty/files/3236936/kitty.txt)

**Comment by kovidgoyal** [comment]
Presumably the metrics of whatever font you are getting that character
from are not compatible with whatever font you have selected as your
primary font. Other terminals will allow characters that dont fit in a
cell to bleed into neighboring cells. kitty will not. You can either
adjust cell width to accomodate just that character or use symbol_map to
laod that character from a font with compatible metrics.

**Comment by dvtkrlbs** [comment]
Is there way to allow bleeding directly ?

**Comment by kovidgoyal** [comment]
no, there is not, it is impossible witht he way kitty works.
