### ISSUE TITLE
"Shortcut ... has unknown modifier, ignoring" - when a "map" command contains the "tab" key

### ISSUE THREAD

**Issue by bool3max** [kovidgoyal/kitty#1669]
Environment: kitty `0.14.1` running on Arch linux (kernel 5.1.5) on `sway 1.0` (wayland). 

`kitty` refuses to create any maps with the `"tab"` key present in them, and displays this when ran with the `--debug-keyboard` option: 

`[152 19:26:13.479915] Shortcut: alt+tab+5 has unknown modifier, ignoring`

I have also tried using native codes (`0xff09` for `"tab"`) displayed using `kitty --debug-keyboard`, but that doesn't seem to work either.

Here is my attached [kitty.conf](https://github.com/kovidgoyal/kitty/files/3244038/kitty.log).

**Comment by kovidgoyal** [comment]
tab is a key not a modifier. You cannot use it like a modifier. So you can have a shortcut like alt+tab not alt+tab+5

**Comment by kovidgoyal** [comment]
Oh and if you want to use shortcuts with multiple keys, kitty supports that using ```>``` see the kitty docs for details.
