### ISSUE TITLE
ctrl+shift+tab broken on MacOS

### ISSUE THREAD

**Issue by gavocanov** [kovidgoyal/kitty#1671]
It seems like  https://github.com/kovidgoyal/kitty/commit/8193b2a44bf26662bc4e855bd88ee9c7829e3317 broke `ctrl+shift+tab` on MacOS, when reverted it works like before.

**Comment by kovidgoyal** [comment]
can you print out what characters ignoring odifiers is when pressing ctrl+shift+tab

**Comment by gavocanov** [comment]
Thnx for the quick fix, it works now.
`event.charactersIgnoringModifiers` is blank, just for the record.
