### ISSUE TITLE
Emoji in tmux status line cause wrapping

### ISSUE THREAD

**Issue by ashb** [kovidgoyal/kitty#1673]
Trying out kitty I noticed an odd issue under tmux - my (supposed to be) single-line tmux status line was wrapping! The emoji I have is `⚡` (U+26A1)

<img width="718" alt="Screen Shot 2019-06-02 at 21 30 37" src="https://user-images.githubusercontent.com/34150/58767027-b4aaa800-857d-11e9-8d46-8eb2b0167efd.png">

(The last character of the time `21:30` is wrapped around on to the next line)

I am using https://github.com/source-foundry/Hack as my font.

<details>
    <summary>minimal tmux.conf</summary>

```
# -*- conf -*-
set -w -g window-status-current-bg red

set -g status-bg colour236
set -g status-fg white
set -g status-left-length 40
set -g status-left '#[fg=yellow]#{session_name} ⧉ '
# Simulate status from https://github.com/Goles/Battery
set -g status-right '#[fg=green][97%] ⚡  #[fg=yellow]#h #[fg=blue]%H:%M'
```
</details>

*Without emoji in the status line*
<img width="718" alt="Screen Shot 2019-06-02 at 21 31 35" src="https://user-images.githubusercontent.com/34150/58767034-d0ae4980-857d-11e9-97e5-846b43dda06c.png">

I've looked through the issues and seen reports of wide characters being clipped, but it's almost like I've got the opposite here? This could be the same issue reported in #561 (but the OP never replied there).

**Version:**
Kitty: 0.14.1
Tmux: 2.8
Platform: OSX 10.12.6

**Comment by ashb** [comment]
It may be specific to _that_ one "high voltage sign" emoji

**Comment by kovidgoyal** [comment]
This will be because tmux incorrectly expects that character to be
rendered in one cell instead of two. The current unicode standard specifies it
has emoji presentation, so must be rendered in two cells.

**Comment by kovidgoyal** [comment]
See http://www.unicode.org/Public/emoji/12.0/emoji-data.txt

search for 26a1

**Comment by kovidgoyal** [comment]
oh and if you want kitty to render the symbol in one cell you can use emoji variation selectors to do it:

```
printf '\u26a1\ufe0e'
```

will render it in one cell (assuming you have a non-emoji font capabe of displaying it on your system, such as symbola)

**Comment by ashb** [comment]
I think I have a repro case that isn't dependent on tmux (just uses tput) - but I guess this :

```
log_msg() {
     RED=$(tput setaf 1)
     GREEN=$(tput setaf 2)
     NORMAL=$(tput sgr0)
     MSG="$1"
     let COL=$(tput cols)-${#MSG}+${#GREEN}+${#NORMAL}
 
     printf "%s%${COL}s" "$MSG" "$GREEN[OK]$NORMAL"
}
log_msg "⚡a"
```

And this shows the same wrapping issue:
<img width="1064" alt="Screen Shot 2019-06-03 at 09 27 18" src="https://user-images.githubusercontent.com/34150/58787558-f4a37680-85e1-11e9-8193-b6685ef6f466.png">

Now this is likely the same cause (that the `COL` calculation is assuming the emoji is 1 cell wide) - is there any tput-y way of finding out how wide it would be rendered? (The zero-wdith-combiner doesn't work for me - get a replacement box, and I'd _like_ if possible to have it the Apple color emoji.)

**Comment by kovidgoyal** [comment]
If you want to calculate the width of an arbitrary string, you need to
refer to the unicode standard. I dont know of any existing command line
tools that do that. But it is trivial to create one using kitty, for example:

```
kitty +runpy "from kitty.fast_data_types import wcswidth; import sys; print(wcswidth(sys.argv[-1]))" test
```

replace test above with whatever string you want to get the width off,
its width in cells will be printed to stdout.

**Comment by ashb** [comment]
Thanks.

I noticed another (related?) problem.

If I type/paste this in a prompt:

```
 echo a🔋b
```

and use the left cursor key to go from the end to `a` then something thinks that the battery is two characters, at least visually.  This is hard to describe. In other words to get the cursor to _appear_ on the `a` it takes 4 movements, but this then gets out of sync with where the cursor actually _is_

**Comment by kovidgoyal** [comment]
You need to use a shell that computes character widths correctly. IIRC
up-to-date versions of zsh do so. Dont know about bash.

**Comment by Luflosi** [comment]
`zsh 5.3 (x86_64-apple-darwin18.0)` and `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)` work correctly on my Mac.

**Comment by ashb** [comment]
Bash 4.4.0 works in this case in Terminal.app and iTerm2

(I'd like to switch to kitty because it's faster :) - awesome project btw)

**Comment by kovidgoyal** [comment]
bash uses readline for prompts, so relevant versions wil be for that if you are using bash. Personally, I'd just switch to zsh

**Comment by ashb** [comment]
Probably about time I made the investment in porting my bash config to and learn Zsh - one of those things I've just been meaning to find time for but my spare time is limited!

Thanks again.
