### ISSUE TITLE
pass_selection_to_program string concatenation possible?

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#1677]
I finally figured out how to get pass_to_selection_to_program to Firefox to work:
```
map kitty_mod+o pass_selection_to_program /Applications/Firefox.app/Contents/MacOS/firefox -new-tab 'https://www.google.com'
```
So when I have something highlighted and I hit mod+o it opens Firefox to Google.

However, the whole point of this is so I can highlight error messages so I can look at them in Google.  I would need a way to pass in the '@selection'

I have tried 
```
map kitty_mod+o pass_selection_to_program /Applications/Firefox.app/Contents/MacOS/firefox -new-tab https://www.google.com/search?q=@selection
```
and even:
```
map kitty_mod+o pass_selection_to_program /Applications/Firefox.app/Contents/MacOS/firefox -new-tab @selection
```
The last one doesn't open Firefox at all since it is not a valid URL.  Is there a way to append the `@selection` at the end of the 'https://www.google.com/search?q='?

Is what I am trying to do achievable at the moment?

**Comment by kovidgoyal** [comment]
Simply write a script that takes the selection as input and does
whatever you need with it before invoking firefox.

**Comment by esn89** [comment]
Alright, so then that would be simply like:
```
map kitty_mod+o pass_selection_to_program esn89/super/cool/firefox/script
```

My script would then expect the @selection to be from stdin right?

**Comment by kovidgoyal** [comment]
No, as a command line argument

**Comment by esn89** [comment]
Ah okay.  Let me try.

**Comment by esn89** [comment]
God it to work.  Thanks @kovidgoyal  for the help and the quick replies!

**Comment by Strykar** [comment]
@esn89 Would you share your kitten? I'm looking to achieve exactly this but with google-chrome instead of FF.

**Comment by esn89** [comment]
Sure:

The script I have is called:  selectiontobrowser.sh:
```
#!/bin/bash

URL="https://www.startpage.com/do/dsearch?query="
PRE_FORMAT_QUERY=$1
QUERY=$(echo $PRE_FORMAT_QUERY | sed -e "s/\ /+/g")

/Applications/Firefox.app/Contents/MacOS/firefox -new-tab ${URL}${QUERY}
```

Then in my ~/.config/kitty.conf I have this line:
```
map kitty_mod+o pass_selection_to_program /Users/evanng/.config/kitty/selectiontobrowser.sh
```

This allows me to press my mod key + o and then it will open firefox with a new tab to start page, with the words I selected.

**Comment by Strykar** [comment]
@esn89 Perfect, thanks very much.

**Comment by dakeryas** [comment]
Just for reference, if you are too lazy to write a script, you can use `--` to make sure the selection is passed to the shell execution:

```
map kitty_mod+o pass_selection_to_program zsh -c "firefox -new-tab google.com/search\?q=${1:gs/ /+}" -- 
```

I am just using in replacement of all the spaces with + with the `gs/ /+` for the first argument received by shell `$1` after the command to execute.
