### ISSUE TITLE
angular symbols

### ISSUE THREAD

**Issue by MiF36rus** [kovidgoyal/kitty#1679]
Hi a have fino zsh prompt , and some symbols are displayed not correctly, how i can fix it?
some terminal:
![image](https://user-images.githubusercontent.com/20323633/58865975-37d41700-86c0-11e9-9c5d-5ba6e980014d.png)

and on my kitty terminal:
![2019-06-04-120209_413x64_scrot](https://user-images.githubusercontent.com/20323633/58866189-b9c44000-86c0-11e9-9e22-0d89d1b24f46.png)

**Comment by kovidgoyal** [comment]
Use symbol_map in kitty.conf to tell kitty to use some special font for that symbol. I'm guessing it is a patched font you are using in your other terminals. Rather than patching fonts, which is fragile hack, use symbol_map in kitty.

**Comment by Luflosi** [comment]
This could also be related to #1585.
