### ISSUE TITLE
Regression > v0.13.3: window borders under wayland are broken

### ISSUE THREAD

**Issue by jasminabasurita** [kovidgoyal/kitty#1682]
Using kitty on Arch Linux with Gnome/Wayland. Downgrading kitty to v0.13.3 fixes the issue
#### v0.14.1:
![image](https://user-images.githubusercontent.com/4014487/58886288-9f369a80-86b1-11e9-9e64-fc34f81aea33.png)
#### v0.13.3:
![image](https://user-images.githubusercontent.com/4014487/58886520-09e7d600-86b2-11e9-9f79-b213155232ba.png)

**Comment by kovidgoyal** [comment]
dup of #1659

**Comment by Luflosi** [comment]
I think it's time to add a FAQ entry.

**Comment by Luflosi** [comment]
Oh, I just saw 277f43aed6760d652e0e4dd741a5ce326bdad3b1.
