### ISSUE TITLE
How to disable middle click paste

### ISSUE THREAD

**Issue by wmonk** [kovidgoyal/kitty#1684]
Is it possible to disable the paste from middle click on macos?

#1033 is where this was added, but I can't see how to configure it off?

**Comment by kovidgoyal** [comment]
It's not possible. Just dont middle click if you dont want to paste
with the middle click.

**Comment by wmonk** [comment]
> Just dont middle click if you dont want to paste with the middle click.

This is why i'm requesting the feature - i have a macbook pro with the massive trackpad and my fat hand keep accidentally triggering a middle click...

Surely if it had to be turned on, it could be made to be configurable?

**Comment by kovidgoyal** [comment]
It was not added in 1033 as far as I know it was always present. And
yeah it can obv be turned off, but it doesn't really make sense to me to
add an option for it. It would make sense if one could configure the
actions of mouse buttons in general, but that is not currently possible.
As it is, if you want to disable it for yourself, simply run kitty from
source and in boss.py find paste_from_seletion() and add a return at the
start of it.

It's very easy to run kitty from source:
https://sw.kovidgoyal.net/kitty/build.html

**Comment by kovidgoyal** [comment]
Not to mention that if you find yourself accidentaly middle clicking, the correct solution is to configure your touchpads threshold for detection, or if macOS does not provide that facility, then remap the middle click to some other button.

**Comment by Luflosi** [comment]
As far as I know macOS doesn't natively support middle clicking using touch pad so he must be using some program to add this capability.

**Comment by wmonk** [comment]
> As far as I know macOS doesn't natively support middle clicking using touch pad so he must be using some program to add this capability.

Bingo! I didn't realise this, i've got it setup with a different application. Thanks both for your help! 😄

**Comment by florianb** [comment]
Sorry for disturbing this old thread.
---
It's not that easy on **Gnome/Ubuntu** - there exists the `org.gnome.desktop.interface` setting [`gtk-enable-primary-paste`](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-enable-primary-paste) (true/false) which is not respected by kitty (because it's no GTK application). I wish you @kovidgoyal would reconsider adding a conf-option allowing us to map or unset mouse buttons like keyboard shortcuts.

However i leave this workaround using "easystroke" for any further frustrated Gnome user: https://ubuntuforums.org/showthread.php?t=1335587&page=3&p=11811126#post11811126

**Comment by gbishop** [comment]
For those who come looking for answers to this issue. I fixed it with [input remapper](https://github.com/sezanzeb/input-remapper)

**Comment by vitaly-zdanevich** [comment]
Still no config to disable middle mouse pasting?

**Comment by vitaly-zdanevich** [comment]
> simply run kitty from source and in boss.py find paste_from_seletion()

`paste_from_seletion` not found in this repo

![image](https://github.com/user-attachments/assets/3124ce12-82ac-415d-9f32-b5df6faff352)

**Comment by kovidgoyal** [comment]
Read the docs, you can remap any mouse action to whatever you want in kitty.
