### ISSUE TITLE
Small question about code in the installer

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1686]
Under which circumstances would `__file__` not be defined?
https://github.com/kovidgoyal/kitty/blob/c9045788f54cbcf15f6829a927bf3e5847976f80/docs/installer.py#L24-L28

**Comment by kovidgoyal** [comment]
When the code is not loaded from a file. For example if it is exec()ed

**Comment by Luflosi** [comment]
When is this actually needed? I can't think of any practical use cases where the installer would be called in such a way.
I also tried executing `exec ./test.py` with `test.py` containing
```Python
#!/usr/bin/env python3
# vim:fileencoding=utf-8

try:
    __file__
    from_file = True
except NameError:
    from_file = False

print(from_file)
```
but that printed `True`. Am I doing something wrong? How would I need to use exec to make `from_file` be `False`?

**Comment by kovidgoyal** [comment]
Look at installer.sh that does just that, namely an exec. And you cant
test it so easily, the behavior of __file__ varies between python
versions, the installer has to run on all versions of python.
