### ISSUE TITLE
URL highlight works only first line

### ISSUE THREAD

**Issue by house-of-vanity** [kovidgoyal/kitty#1687]
Hi,
If URL is quite long and doesn't fit on one line highlighting doesn't work as expected - it works only for a first line.
It looks like this gif.
![kitty](https://user-images.githubusercontent.com/4666566/58966314-c036e280-87ba-11e9-8060-d21916f66a1a.gif)
i use:
kitty 0.14.1
Arch Linux 5.1.6-1-ck

Thank you!

**Comment by kovidgoyal** [comment]
That is by design, as a performance enhancement. Otherwise everytime the
mouse moved over such a line kitty would have to search an potentially
unbounded number of lines upwards to find the start of the URL
