### ISSUE TITLE
Kitten `clipboard` non-deterministically copies/truncates big scrollback when piped tab `@text` by keybinding

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#1693]
To copy the whole scrollback to the clipboard, I use
```
map kitty_mod+a pipe @text tab kitty +kitten clipboard
```

With a small scrollback it works great, but with a big scrollback it consistently fails to copy the *whole* scrollback, instead truncating the end of the scrollback at non-deterministic positions 😕.

For example, after `ls -la /usr/bin` (2800 lines), when pressing <kbd>kitty_mod</kbd>+<kbd>a</kbd>,

1. First press yields 2122 lines
2. Second press yields 317 lines
3. Third press yields 2635 lines

I'm using kitty master @ 4faf71bd03b1a1bce39652ae950e800dff294576 under Ubuntu 19.04, my shell is fish 3.0.2 .

---

*Note: this is a followup of [[Help] Map key to copying whole scrollback to clipboard](https://github.com/kovidgoyal/kitty/issues/1048), where I asked for advice to achieve the same result, using `xclip`/`xsel`. It worked, until it didn't, for reasons I didn't investigate, so I moved to `kitten clipboard` and was happy, then I noticed this problem.*

**Comment by kovidgoyal** [comment]
Does using the clipboard kitten directly with a large text file work?

kitty +kitten clipboard < some text file

**Comment by ronjouch** [comment]
> Does using the clipboard kitten directly with a large text file work?
> 
> ```
> kitty +kitten clipboard < some text file
> ```

@kovidgoyal yes this works consistently (same test case, with a `ls.txt` containing the same 2800 lines of `ls -la /usr/bin/`). Problem happens only when invoking the kitten from a binding, which opens a transient tab which gets closed after a few milliseconds. Maybe the transient tab is closed too soon / fails to wait for the kitten to finish?

As usual, thanks for the fast feedback.

**Comment by ronjouch** [comment]
Additional data point: this feels like a regression, I don't think I did encounter that back a few months ago.

**Comment by kovidgoyal** [comment]
Should be easy to fix, create a script that calls the kitten and sleeps
for a little while afterwards then use that in your binding.

**Comment by ronjouch** [comment]
@kovidgoyal I compiled 84fcabe and updated my config to `map kitty_mod+a pipe @text tab kitty +kitten clipboard --wait-for-completion`. Although it visibly waits, it now fails differently, truncating the *beginning* of a big scrollback and only keeping the *end*. In a terminal with a big scrollback of several `ls -la /usr/bin`, I get three only-slightly different outputs in my clipboard:

1. First run: 11871 lines, 744.285 bytes.
2. Second run: 11878 lines, 744.758 bytes.
3. Third run: 11876 lines, 744.638 bytes.

My `scrollback_lines` is currently set to `100000`, so it shouldn't be the problem.

Am I missing something?

**Comment by kovidgoyal** [comment]
Just use

pipe @text clipboard dummy

**Comment by ronjouch** [comment]
> Just use
> 
> ```
> pipe @text clipboard dummy
> ```

@kovidgoyal yes! That works muuuuuch better, it's reliable and fast. Sorry, had focused on the first commit with `--wait-for-completion` but didn't see the contents of the second, adding the pipe command to send to clipboard.

Thanks for the fix and for the continued work on kitty :pray: ! Good day/night.
