### ISSUE TITLE
kitty window tiny/frozen after switching display output in sway/wayland

### ISSUE THREAD

**Issue by craftyguy** [kovidgoyal/kitty#1696]
When switching display outputs in Sway, kitty's window will either be hidden or super tiny (see screenshot) and unusable.
![58931410-e8ddbe80-875f-11e9-98eb-d1ebb65b22f3](https://user-images.githubusercontent.com/1474209/59053142-92e34680-8845-11e9-8074-511ff5e006c7.png)

I can reproduce this reliably by plugging in a new display and running something like `swaymsg output DP-1 enable 2560x1440 && swaymsg output eDP-1 disable` (where DP-1 is the new display and eDP-1 is the old display)

I tried setting `sync_to_monitor=no` in kitty.conf per this comment, but it did not prevent the issue: https://github.com/kovidgoyal/kitty/issues/1681#issuecomment-498940914

System details:
Arch Linux, 5.1.7 kernel using i965/Intel graphics.
Sway 1.1.1 (and tried with sway git master as of this issue filing)
wlroots 0.6 (and tried with wlroots git master as of this issue filing)

**Comment by kovidgoyal** [comment]
Is this a rendering issue or does kitty freeze completely? If you press ctrl+shift+n does a new window get created?

**Comment by craftyguy** [comment]
Ok seems like this is not fixed by 857a53e, and it also seems like kitty is not frozen as I can ctrl+shift+n and get a new window. The existing window is just extremely small/unusable. Can this issue be re-opened since it is not fixed?

**Comment by kovidgoyal** [comment]
Try setting 

sync_to_monitor no 

in kitty.conf

**Comment by kovidgoyal** [comment]
And note that you need to be running kitty 0.14.2 not just that commit as there were several other wayland multi-monitor related fixes.
