### ISSUE TITLE
kitty stopped working after upgrading Fedora

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#1706]
I upgraded from Fedora 28 to Fedora 29 which also upgraded Linux (current system: 5.0.14-200.fc29.x86_64) and Python3.6 to Python3.7. Ever since kitty no longer launches. I suspect this is a python problem because virtualenvwrapper also stopped working after the upgrade. I had to reinstall virtualenvwrapper in python3.7's site directory to get it working again.

The kitty launch script no longer works:

```
#!/usr/bin/env python3
import runpy
runpy.run_path('/home/user/kitty/kitty_source', run_name='__main__')
```

and when I try running kitty from source (i.e. in the top level of the kitty source directory) with `python3 .` I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 104, in <module>
    main()
  File "./__main__.py", line 97, in main
    from kitty.main import main
  File "./kitty/main.py", line 10, in <module>
    from .borders import load_borders_program
  File "./kitty/borders.py", line 7, in <module>
    from .fast_data_types import (
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```
I also get the same error when I run `kitty --version` so I cannot even check what version of kitty I am using. All I know is that I am using a version of kitty from around July 2018

From the last line:
> ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

I'm guessing kitty tries to import **libpython3.6m.so.1.0** but the file does not exist, or may be kitty tries to use **libpython3.6m.so.1.0** since **libpython3.6m.so.1.0** is not a Python module which means it cannot be imported . Which kitty set-up file contains this line of code so I can update it? 

FYI `find` shows that `/usr/lib64/libpython3.7m.so.1.0` exists but `/usr/lib64/libpython3.6m.so.1.0` does not exist (any more)

### update
```
grep -r libpython3.6m.so.1.0
Binary file kitty/fast_data_types.so matches
Binary file kittens/diff/diff_speedup.so matches
Binary file kittens/unicode_input/unicode_names.so matches
```
Does this mean that libpython3.6m.so.1.0 is being imported in a binary file? In that case how do I change it?

**Comment by Luflosi** [comment]
Can you try a newer version? The latest version 0.14.2 was released three days ago.

**Comment by ChukwuemezieChristopherAneke** [comment]
> Can you try a newer version? The latest version 0.14.2 was released three days ago.

I would have to build from source, it would be useful to know what is causing this bug. Is it possible that the version of kitty I am using is hardcoded to use `libpython3.6m.so.1.0` since python 3.6 was the latest version of Python when I installed kitty?

**Comment by Luflosi** [comment]
@kovidgoyal will have to comment on that, I don't know.

**Comment by ChukwuemezieChristopherAneke** [comment]
> @kovidgoyal will have to comment on that, I don't know.

@Luflosi yes, he most likely knows. Just in case the only solution is to get the latest version of kitty, can you remind me, is updating kitty from source simply `git pull`, then `make`? I'm asking because its been long since I built from source so I'm a bit rusty

**Comment by Luflosi** [comment]
If all the dependencies are installed, pretty much, yes. See https://sw.kovidgoyal.net/kitty/build.html for more info.
You could also install a pre-compiled version of kitty, see https://sw.kovidgoyal.net/kitty/binary.html.

**Comment by kovidgoyal** [comment]
You build kitty from source against python 3.6 presumably your system no
longer has python3.6, so build it again. Or use the kitty binary release
which has its own python.
