### ISSUE TITLE
macOS pipe `none` command seems to freeze kitty

### ISSUE THREAD

**Issue by hanoii** [kovidgoyal/kitty#1708]
I don't use this very often, but I needed it now and it froze kitty.

I have this in config:

```
map f1 pipe @text none /usr/local/bin/subl
scrollback_pager_history_size 50
```

Now when I run f1, the editor opens with the output but kitty freezes and become unresponsive, I have to force quit it.

On the other hand, using `tab` instead of `none` works.

**Comment by kovidgoyal** [comment]
When you pass data to an external program kitty waits until all data is
read. It does so on the main thread. Presumably whatever program you are
passing the data to is not reading all of it.

**Comment by hanoii** [comment]
That didn't happen on on 0.13.x, started to happen just recently.

Also, isn't `none` supposed to be background? it freezes with the loading clock, completely unresponsive. `tab` works.

**Comment by kovidgoyal** [comment]
No, the process is background, passing data to it is not, and never has
been. So if you use pipe with none without any data, it will never hang,
with data, it will hang till the process reads all the data.

**Comment by hanoii** [comment]
Right..

`echo "aa" | subl` also never ends until I close the tab.. which just found out it also unfreezes kitty.

The data is all read, but I guess sublime is leaving stdin open.

Ok, I can work around this. Thanks  :)!
