### ISSUE TITLE
Possible to use backtick as a map character?

### ISSUE THREAD

**Issue by ch-tactica** [kovidgoyal/kitty#1710]
Trying to switch over from tmux to some of the kitty layout management features, but I don't like the use of Ctrl as a map character, I'd much rather use the backtick character (`) in place of common key-bindings.

I tried the following, but it didn't work:

```
# Window management
map `+minus new_window
```

Is there a special escape sequence needed in order to do this?

**Comment by kovidgoyal** [comment]
backtick is not a modifier. If you want to use it as the first character
in a key sequence, you can use kitty's multi-key feature, see kitty.conf
for examples, basically something like this

`>a
`>b
`>c>d
