### ISSUE TITLE
Triple click doesn't select whole line

### ISSUE THREAD

**Issue by house-of-vanity** [kovidgoyal/kitty#1711]
Hello, Triple click doesn't select whole line when line starts with spaces.
Expected behaviour: triple click should select from ^ till $.
![kitty](https://user-images.githubusercontent.com/4666566/59435416-33150e80-8df6-11e9-9481-b5b151558e57.gif)
kitty 0.14.2
Arch linux

**Comment by kovidgoyal** [comment]
That is by design, leading and trailing white space is ignored on line
select.

**Comment by copy** [comment]
@kovidgoyal Would you reconsider this for multi-line selections? This often results in spaces missing in the first line:

![Screenshot_2020-01-14_17-31-02](https://user-images.githubusercontent.com/1816456/72391740-a9af1d00-36f3-11ea-8ad5-f4751fd30a5c.png)

**Comment by kovidgoyal** [comment]
Sure, I dont mind modifying the selection when triple-click + drag
occurs. Patches are welcome, relevant code is in mouse.c and screen.c
