### ISSUE TITLE
Starting a word with the hash sign (#) will color it black and thus not visible on dark themes

### ISSUE THREAD

**Issue by mihai-dinu** [kovidgoyal/kitty#1716]
When typing something like `#this is text` in kitty, the text is displayed in black color and is not visible if you are using a dark theme. 

Kitty version and $TERM env var, plus a "hidden message"
![image](https://user-images.githubusercontent.com/26204012/59550650-6b8b2880-8f6d-11e9-938d-06e4ee27cbdc.png)

![image](https://user-images.githubusercontent.com/26204012/59550695-fc620400-8f6d-11e9-8d88-c5b190690d53.png)

**Comment by kovidgoyal** [comment]
umm if your editor is set to display commented text in black, then that is what will happen. Change the comments color in your editor and you will be fine.

**Comment by mihai-dinu** [comment]
There is no editor. It's just text written in the kitty terminal. But that did get me thinking and it looks like it might be related to zsh. Thanks

**Comment by kovidgoyal** [comment]
In that case it is the shell -- terminals are just containers to run
client programs.

**Comment by mihai-dinu** [comment]
Got to the bottom of the problem. It was a zsh plugin that changed colors. In case someone else has the same problem, the solution is here: https://github.com/zdharma/fast-syntax-highlighting/issues/138

**Comment by psprint** [comment]
@kovidgoyal; But the comments are in black **bold**, and other terminals choose to display such color as a distinct one compared to a normal black.

**Comment by kovidgoyal** [comment]
That is a bug in those terminal that means they cannot have bold text.
See #197

**Comment by psprint** [comment]
However, the terminals have options to switch between true bold fonts and the upper, lighter-brightness colors

**Comment by kovidgoyal** [comment]
Read the issue I linked.

**Comment by psprint** [comment]
Ok I did read it now more closely and I can see your point.

**Comment by mad01** [comment]
@mihai-dinu any idea what you actually did to fix this. I don't fully understand what i can do to fix it in my shell. the link to the issue you added no longer works

**Comment by mad01** [comment]
found the solution if using zsh an alternative to fix this is to set this variable 
```
export ZSH_HIGHLIGHT_STYLES[comment]='none'
```
