### ISSUE TITLE
OSX: `macos_traditional_fullscreen yes` causes weird focus bug

### ISSUE THREAD

**Issue by evantravers** [kovidgoyal/kitty#1717]
I recently turned on `macos_traditional_fullscreen yes`, which looks great and was one of my favorite features on iTerm when I was rolling that way… but something is weird.

1. Start up Kitty
2. Switch to full-screen (in my case, cmd-enter)
3. I can type, things work fine.
4. Alt-tab away from Kitty to something else.
5. Alt-tab back… kitty is full screen.
6. Type… and you get an alarm bell on each keystroke.
7. Click on Kitty with the mouse.
8. Type… and it works normally.

I have to click on Kitty each time I return to it… it's odd.

```
❯ kitty --version
kitty 0.14.2 created by Kovid Goyal
```

Current config file:
```
# vim:fileencoding=utf-8:ft=conf

# Theme
include themes/gruvbox.conf

# OS specific changes
macos_hide_from_tasks no
macos_option_as_alt yes
macos_hide_titlebar yes
macos_titlebar_color system
macos_traditional_fullscreen yes

# what counts as a word
select_by_word_characters :@-./_~?&=%+#

# alert options
visual_bell_duration 0.0
enable_audio_bell yes
window_alert_on_bell yes
bell_on_tab yes

# advanced
allow_remote_control no
clipboard_control write-clipboard write-primary
term xterm-kitty

# keyboard shortcuts
kitty_mod super
map kitty_mod+enter toggle_fullscreen

# mouse settings
mouse_hide_wait 1

window_margin_width 20.0
```

**Comment by kovidgoyal** [comment]
dup of #1342

**Comment by Luflosi** [comment]
@kovidgoyal I don't see, how the two issues are related. Did you mistype the issue number?
@evantravers did you mean <kbd>cmd</kbd>+<kbd>tab</kbd> instead of <kbd>alt</kbd>+<kbd>tab</kbd>?

**Comment by kovidgoyal** [comment]
Oh yeah sorry, meant #1324

**Comment by evantravers** [comment]
@Luflosi yes… thanks. Long habit. 🙇
