### ISSUE TITLE
Is there an argument to specify the position and the size of the window?

### ISSUE THREAD

**Issue by netjune** [kovidgoyal/kitty#1719]
Like the the argument "-geometry" of rxvt.

**Comment by kovidgoyal** [comment]
Poisitioning windows is the job of the window manager, not individual
applications. As for size, there are various options in kitty.conf to
control it, which you can override on the command line using -o

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.remember_window_size.
