### ISSUE TITLE
Weird resizing behaviour

### ISSUE THREAD

**Issue by valentjedi** [kovidgoyal/kitty#172]
Hi, thanks for the fix for #170!

However, I've noticed that another issue emerges and it might be related to that one.
So if I resize a terminal window in floating mode, it eventually becomes something like this:
![2017-11-16-003542_1274x913_scrot](https://user-images.githubusercontent.com/7038954/32841582-6f22dbf0-ca66-11e7-9b66-5e3090557e3e.png)

Also, when I open some second window side by side with existing terminal window and it cuts the terminal window in a half (I use i3wm, but any tiling wm works like that), all recently printed lines on terminal either disappear or you have to use scrollback to reach them.

Let me show an example.
1) Single kitty window:
![2017-11-16-004410_2880x1800_scrot](https://user-images.githubusercontent.com/7038954/32841781-024dd542-ca67-11e7-9925-8bb480dfa01a.png)
2) I've opened the second window, notice how some text disappeared from kitty:
![2017-11-16-004553_2880x1800_scrot](https://user-images.githubusercontent.com/7038954/32841871-4aef7c4c-ca67-11e7-9d9f-bd1fce8e0666.png)
3) I've opened the third window, and all text disappeared from the kitty. It's not available even from scrollback
![2017-11-16-004648_2880x1800_scrot](https://user-images.githubusercontent.com/7038954/32841886-5b49375e-ca67-11e7-925f-4deac2470daa.png)

Btw if kitty runs some running process which prints to the stdout constantly (like selenium server for example), resizing seems to work fine.

Hope it'll further debugging.

**Comment by kovidgoyal** [comment]
I can make that happen in pretty much any terminal, for example here's a screen shot of termite after a bit of wild resizing:

![screenshot_20171116_004248](https://user-images.githubusercontent.com/1308621/32855251-2795204e-ca67-11e7-95e8-7f2679c73b8b.png)

**Comment by kovidgoyal** [comment]
And here is xterm:
![screenshot_20171116_004420](https://user-images.githubusercontent.com/1308621/32855303-50877cfe-ca67-11e7-9295-1a390b76e729.png)

Granted, it happens a littel more easily in kitty. But I suspect that is a side effect of kitty being very fast, so more consecutive resize events are processed than in other terminals. Probably, best fix would be to debounce the resize handler.

**Comment by valentjedi** [comment]
Well, indeed. I guess that I've noticed it after I started to experiment with resizing because of lines disappearing I showed on my last three screenshots :)
