### ISSUE TITLE
`kitty @ new-window [CMD]` does not find binaries in `/usr/local/bin`

### ISSUE THREAD

**Issue by grtlr** [kovidgoyal/kitty#1721]
My system is running on macOS 10.14.5. When I run `kitty @ new-window [CMD]`, a new kitty window opens, but it fails with the following error message:
```
Failed to launch child: [CMD]
With error: No such file or directory
Press Enter to exit.
```

In my `kitty.conf` I have the following option `shell /usr/local/bin/fish --login`, to tell kitty to run in an interactive shell. 

Now, when I start kitty through the macOS Terminal app (`open -a kitty`) and then do `kitty @ new-window [CMD]`, it works. So it seems to be a problem with the login shell of macOS. In which environment ist `[CMD]` executed?

Please let me know if I can be of any help, or how I could tackle this problem. Thank you very much!

**Comment by kovidgoyal** [comment]
Add /usr/local/bin to the system PATH, this means not i your shell
startup files but macOS system wide. This is the environment kitty runs
in.Or alternatively use the full path to the executable you want to
start when running kitty @ new-window

**Comment by grtlr** [comment]
Thank you for your quick reply! I cannot seem to get it to work even though I tried all of the following:

* `/usr/local/bin` was already in `/etc/paths`
* Adding `export PATH="/usr/local/bin:$PATH"` to `~/.bash_profile
* Creating a `*.plist` according to this StackOverflow post answer:  https://apple.stackexchange.com/a/106814

Whats even more interesting, if I do:

    kitty @ new-window "echo $PATH"

I get the following error:

    Failed to launch child: echo [...]:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:[...].:/Applications/kitty.app/Contents/MacOS
    With error: No such file or directory
    Press Enter to exit.

So `/usr/local/bin` seems to actually be in the path. Maybe this is some weird timing issue? Would you mind reopening this issue? Thanks again!

**Comment by Luflosi** [comment]
Changing the shell in the config file or changing `~/.bash_profile` won't do anything to fix your issue as the shell is not being executed when using `kitty @ new-window [CMD]`.
Don't worry too much about this issue being closed. If you couldn't fix your problem, just continue asking questions and giving feedback.

**Comment by kovidgoyal** [comment]
If you cannot figure out how to specify PATHs system wide, do so in
kitty.conf instead with the env key. Something like:

env PATH=${PATH}:/usr/local/bin
