### ISSUE TITLE
Kitty freezes when switching monitors on OSX

### ISSUE THREAD

**Issue by metalelf0** [kovidgoyal/kitty#1725]
Hi, since version 0.14 I'm facing an issue with my dual monitor setup. I usually use a single monitor (the external 4k one) and keep the laptop lid closed. When I open the lid (e.g. to use the webcam), kitty becomes totally unresponsive, with no other choice than killing it and restarting it. It started to happen with 0.14, I upgraded to 0.14.1 and 0.14.2 without any success.

Let me know what kind of log/backtrace I can eventually send you to help you debug this issue.

Thanks and keep up the great work!

**Comment by kovidgoyal** [comment]
try setting sync_to_monitor no in kitty.conf

**Comment by metalelf0** [comment]
Ok, tried it right now and it seems the issue is gone. Thank you!

**Comment by kovidgoyal** [comment]
It should not happen with sync_to_monitor yes though -- sadly I dont
have an external monitor to test with on my macOS laptop, so it is hard
for me to debug.
