### ISSUE TITLE
Leading Zero to select unicode not working for me.

### ISSUE THREAD

**Issue by evantravers** [kovidgoyal/kitty#1728]
> You can also type a leading period and the index for the match if you don't like to use arrow keys.

(from https://sw.kovidgoyal.net/kitty/kittens/unicode-input.html)

I really like this idea… but I can't seem to replicate it. I can use tab or the arrow keys… but I can't jump to the unicode character by using the index provided. I'm on OSX, my config looks like: https://github.com/evantravers/dotfiles/blob/master/kitty/.config/kitty/kitty.conf

**Comment by kovidgoyal** [comment]
This is fixed in master.
