### ISSUE TITLE
send_text should override map

### ISSUE THREAD

**Issue by mbward** [kovidgoyal/kitty#173]
If my `kitty.conf` doesn't have any "map" definition for Ctrl+Shift+C or Ctrl+Shift+V, but defines an action for them using "send_text", e.g.

```
#map ctrl+shift+v        paste_from_clipboard
#map ctrl+shift+c        copy_to_clipboard

send_text all ctrl+shift+c \x03
send_text all ctrl+shift+v \x16
```

pressing Ctrl+Shift+C or Ctrl+Shift+V does nothing.

It works if I prepend

```
map ctrl+shift+c no_op
map ctrl+shift+v no_op
```

but that seems unnecessary.

**Comment by kovidgoyal** [comment]
send_text is a bit of a wart. If I were implementing it today, I'd just use the fact that now-a-days kitty shortcut actions can take arguments to implement it as a normal shortcut. Maybe worth doing anyway, leaving the old send_text in there for backwards compat. So you'd use

```
map ctrl+shift+c send_text \x03
```

There is no question of precendence in this case.
