### ISSUE TITLE
Missing some UTF-16 characters

### ISSUE THREAD

**Issue by Ra0EL** [kovidgoyal/kitty#1732]
Hi,

I am giving a try to Kitty, as an alternative to my usual  GPU-rendering terminal (Alacritty :smile:).

I have to say it is pretty cool and interesting.
But allow me to report an issue.

Screenshot below is self-explanatory.
You can see comparison of what is displayed in Konsole (top) and Kitty (bottom). Yes, some _emoji_ are missing...
![kitty](https://user-images.githubusercontent.com/8389138/59932329-3ab46300-9447-11e9-804b-c2671915dc43.png)

Is it a bug ? Or something wrong with my config ( KDE on OpenSuSE Leap 15.1 ) ?

Besides, you can see sad side-effects, regarding your position about intense/bold color (yes, I read your discussion on **htop** thread). Since this is expected, it does not call any action.

But, regarding these missing chars, it is a concern, actually.
Best regards.

**Comment by kovidgoyal** [comment]
It would be nice if you posted the list of characters as text, so I can copy paste to test them on my system without needing to retype them. Although from the screenshot I am guessing the issue is you dont have an emoji font installed on your system. Installing symbola and Noto Color Emoji should be sufficient for mostof those symbols.

**Comment by Ra0EL** [comment]
Hi,
and thank you for the quick answer. Not sure why you close this request though...

So,

- regarding fonts, I am using Hack. And as you can see on my screenshot, all emoji are displayed correctly in Konsole. It is only in Kitty that some of them are missing.
- environment is exactly the same - as far as I can tell - in both Konsole and Kitty.
- emojis are given in my `echo` command, as you can see. On your request, see chars below :
  🍃 🌀 🌪 🌫 🌁 🌥 🌤 🌈 🌦 🌩 🌧 🌨

By simply copy-pasting these characters in Kitty console, I have exactly the same issue than illustrated in my screenshot, that is to say : 

- emojis are missing in Kitty (e.g. 🌪 ; details here : <https://www.fileformat.info/info/unicode/char/1f32a/index.htm> )
- while they are all displayed correctly in Konsole or Yakuake, for instance.

Any help appreciated.

**Comment by kovidgoyal** [comment]
All those emojis display fine in kitty for me. I already told you,
install the symbola and Noto Color Emoji fonts and you will be fine.
Hack does not have those symbols, konsole is falling back on some bitmap
font on your system. kitty does not support bitmap fonts, so again,
install symbola and Noto Color Emoji

**Comment by Ra0EL** [comment]
OK, got it, thanks.
So I have deployed Color Emoji Fonts. Ok, now I have colored emojis... but still missing the same emojis :(
In screenshot, below,
 - on top you can see Konsole, with all colored emojis available.
 - at bottom, you can see Kitty. Still missing emojis - but indeed, now, some color.

![Screenshot_20190624_132822_001](https://user-images.githubusercontent.com/8389138/60015598-2e691980-9684-11e9-806a-1e19fe4305f0.png)

**Comment by kovidgoyal** [comment]
Install symbola

**Comment by Ra0EL** [comment]
Not available from repo. Where could I find it ?

**Comment by kovidgoyal** [comment]
google is your friend.

**Comment by kovidgoyal** [comment]
And you might want to report the bug to konsole that it is showing 2 cell wide color emojis for symbols that are defined with text presentation in the unicode standard. For instance, to see a color emoji for 1f328, the correct sequence is

printf '\U1f328\ufe0f'


which with a color emoji font installed, kitty wil display. And if you dont add the U+fe0f then kitty will display a text mode, single cell representation of the symbol, as required by the unicode standard. But for that you need to install symbola or some other scaleable font that has the symbol.

**Comment by Ra0EL** [comment]
mmm... this `printf` command you share **does** display the expected colored emoji (without the need to install symbola, btw). So, let's consider this problem is fixed.
I don't feel like report this bug to Konsole team - as I have no significant skill in Unicode and so on.

Thank you for quick answers.
