### ISSUE TITLE
Small kitten to get/set colors

### ISSUE THREAD

**Issue by mvrozanti** [kovidgoyal/kitty#1733]
I was wondering how to use `cmds.set_colors`, `cmds.cmd_set_colors` and their get counterparts.

Would be even better, if it was possible to directly use `patch_color_profiles` for performance.

I wanted to do something like this:

```
def main(args):
    return None

def handle_result(args, answer, target_window_id, boss):
    # bg = get_background_color(boss.active_window)
    # bg.blue += 1
    # set_background_color({'background':bg})
```

I tried several combinations of arguments, learned about `reset`, `configured` and `all` but to no avail. 

I just want to get/set background of the `boss.active_window`

Is there an easy way to do that?

Thanks!

**Comment by kovidgoyal** [comment]
You want a way to get and set colors in the active window? There is no need for a kitten for that. Either use the remote control system or the existing terminal escape codes.

**Comment by kovidgoyal** [comment]
reference to OSC codes to set and query colors; https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands

**Comment by mvrozanti** [comment]
I tried using terminal escape codes but for some reason they don't work. I tried the following, with no effect:

```
echo -ne '\e]11;#abcdef\e\\'
echo -e '\e[0;41m'
```

Using the remote control works great (`kitty @ --to unix:@mykitty set-colors background=#abcdef`) though -- but it's kind of slow and for some reason I can't call it properly from python. I could put it in a shell script but then one'd need to call that shell script _from python_, either a kitten or by using `send-text`

**Comment by kovidgoyal** [comment]
Works fine for me, for example:

```
printf '\x1b]11;red\x1b\\'
```

will change the background color of every cell that does not have its
own background color set.

**Comment by kovidgoyal** [comment]
And for your particular example,

```
printf '\x1b]11;#abcdef\x1b\\'
```
