### ISSUE TITLE
Kitty ignores colors set for color 8-15

### ISSUE THREAD

**Issue by gryf** [kovidgoyal/kitty#1738]
Hi Kovid, I've bumped on issue regarding changing the color scheme for Kitty. I've been using the very same colors for Xterm and Kitty, here is the config:

```
color0      #000000
color1      #9e1828
color2      #aece92
color3      #968a38
color4      #414171
color5      #963c59
color6      #418179
color7      #bebebe
color8      #666666
color9      #cf6171
color10     #c5f779
color11     #fff796
color12     #4186be
color13     #cf9ebe
color14     #71bebe
color15     #ffffff
foreground  #7f7f7f
background  #000000
```

As it can be seen on the screenshots, the colors defined for bright version are ignored - they are only bolded. Is that by intention, or am I missing something obvious?

![kitty](https://user-images.githubusercontent.com/264785/59979454-73d80900-95e8-11e9-9375-af1a17e9b568.png)
![xterm](https://user-images.githubusercontent.com/264785/59979455-75a1cc80-95e8-11e9-8267-4d574801f225.png)

**Comment by Luflosi** [comment]
Yes, this is intended, see https://github.com/kovidgoyal/kitty/issues/197#issuecomment-348062665, maybe even read through that entire issue.

**Comment by gryf** [comment]
Ok, got it. Although I don't buy the story about how broken "bold" fonts in other terminal are. That's how it is, and a lot of apps will suffer by decision, to keep the bold fonts, instead of keeping aligned with all the others terminal emulators. IMHO, TERM value shouldn't be set to `xterm-kitty` since it isn't xterm compatible after all - at least not from colors perspective.

**Comment by Luflosi** [comment]
For a discussion on why `TERM` is `xterm-kitty` and not `kitty`, see point number two in https://github.com/kovidgoyal/kitty/issues/879#issuecomment-419686348 and the response to question https://github.com/kovidgoyal/kitty/issues/879#issuecomment-437733153.

**Comment by gryf** [comment]
Thanks for the links!
