### ISSUE TITLE
"make app" throws exception

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1744]
`package()` still tries to copy `kitty/launcher/kitty` with `shutil.copy2('kitty/launcher/kitty', os.path.join(libdir, 'kitty', 'launcher'))`, even though that file was deleted in 9135387cfa141e9ec27271bc41d5b6c43da90197. The CI didn't catch this because it executes `python3 setup.py build` first, which creates that file. Do we really need to copy the launcher to two different places, now that there is only one launcher?
```
Traceback (most recent call last):
  File "setup.py", line 963, in <module>
    main()
  File "setup.py", line 958, in main
    package(args, bundle_type='macos-package')
  File "setup.py", line 807, in package
    shutil.copy2('kitty/launcher/kitty', os.path.join(libdir, 'kitty', 'launcher'))
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'kitty/launcher/kitty'
```

**Comment by kovidgoyal** [comment]
And no, the launcher should not be needed, since the one from the MacOS
directory will beused, but no real harm in copying it, that way the
source tree is not different between different builds of kitty.

**Comment by Luflosi** [comment]
`macos-freeze`, `linux-package` and `linux-freeze` also fail its the same error.

**Comment by kovidgoyal** [comment]
Should be fine now.

**Comment by Luflosi** [comment]
It does not work because the launcher directory may not exist.

**Comment by Luflosi** [comment]
It works now 🎉.
Third time's the charm, right? 😄
