### ISSUE TITLE
Kitty seems unable to use font sizes beneath 6pts

### ISSUE THREAD

**Issue by wbthomason** [kovidgoyal/kitty#175]
As the title implies, I'm trying to set my font size below 6pts (since Kitty seems to render fonts larger than expected - I've tried setting `Xft.dpi` as in https://github.com/kovidgoyal/kitty/issues/109, but it does not help). However, all sizes in the range 1.0 - 6.0 seem to render at the same size. Is this intended behavior?

For reference, I am using the following font config in `kitty.conf`:
```
# Fonts
font_family      Fira Code
bold_font        Fira Code Bold
# Because Fira Code has no italic face. Also, I know that I can use symbol_map instead of a patched font, but I haven't gotten to that yet
italic_font      Iosevka Italic Nerd Font Complete Mono
bold_italic_font Iosevka Bold Italic Nerd Font Complete Mono
font_size 6.0
```

I'm on Arch Linux with the latest Kitty build from AUR.

**Comment by kovidgoyal** [comment]
See MINIMUM_FONT_SIZE in config.py. Change it to whatever you like. Although, I dont see why you would need to. You should be able to scale the effective font size to anything via Xft.dpi
