### ISSUE TITLE
New launcher isn't working

### ISSUE THREAD

**Issue by spejamchr** [kovidgoyal/kitty#1756]
When I run the launcher (`./kitty/launcher/kitty`) a window pops up, but it doesn't seem to receive focus. It doesn't receive my key events, instead, they go to whatever program had focus before (and apparently, that program still has focus).

Things I've tried:

- I use chunkwm. I tried turning it off, but the same issue happens.
- I've tried running the launcher with no custom configuration, but get the same result.
- Running kitty with python (`python3 .`) still works.

I'm on macOS 10.14.5 (18F203), running kitty at commit c8631160.

**Comment by Luflosi** [comment]
How did you build kitty? `make`? Try `make app` and then use `kitty.app` or `kitty.app/Contents/MacOS/kitty`.

**Comment by spejamchr** [comment]
I built using `make` (been building kitty for about a year now. Thanks!). I also tried removing the whole repo and re-cloning it, and then running `make` again.

Building with `make app` and using `kitty.app` or `kitty.app/Contents/MacOS/kitty` both work. But even after that I get the same odd behavior when running `./kitty/launcher/kitty`.

I only bring it up because this code suggests launching kitty one way, which isn't working. I'm happy to continue launching it with `python3 .` if that continues to work.

https://github.com/kovidgoyal/kitty/blob/c8631160118a0f86c12dd67a27621d4ee6c530e8/docs/build.rst#L45-L47

**Comment by Luflosi** [comment]
Maybe @kovidgoyal knows how to fix the launcher or he can change the docs.
I think `python3 .` is not supposed to work in all cases but if it works for you...
Why not just use `kitty.app`? Is that not easier? Just wondering.

**Comment by spejamchr** [comment]
No particular reason. I read the "Build From Source" guide, tried the first option, and stuck with it since it worked. I don't mind switching.

**Comment by kovidgoyal** [comment]
This will be the usual cocoa issue with running an unbundled executable. It works ok with python3 . becaue the python3 executable comes from a bundle. There are two possible solutions I think. One is to create a lightweight bundle in the launcher dir the other is to figure out what cocoa api to sue to get macOS to recognize the executable as a GUI program. As best as I can tell, from https://www.cocoawithlove.com/2010/09/minimalist-cocoa-programming.html

calling

```objc
[NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
[window makeKeyAndOrderFront:nil];
[NSApp activateIgnoringOtherApps:YES];
```

should do the trick. If it works, it should make the re-exec for symlink kludge unnecessary as well.

**Comment by kovidgoyal** [comment]
Fixed by using a minimal bundle. Note that I have not tested the fix,
please do that and let me know if it works as expected.

**Comment by Luflosi** [comment]
@kovidgoyal your fix works 🎉.
@spejamchr you can now use `kitty/launcher/kitty` when building with `make` or use `kitty.app` when building with `make app`.
The docs mention `make app` just under the section you were looking at: https://github.com/kovidgoyal/kitty/blob/master/docs/build.rst#building-kittyapp-on-macos-from-source.

**Comment by spejamchr** [comment]
Awesome! Thanks!
