### ISSUE TITLE
bash completions do not complete aliases

### ISSUE THREAD

**Issue by scopatz** [kovidgoyal/kitty#1758]
Bash completions do not work on that standard aliases defined in the docs.  For example:

```bash
$ alias icat="kitty +kitten icat"
$ icat --<TAB>
```

will not produce any results, unlike completing on  `kitty +kitten icat --<TAB>`

**Comment by kovidgoyal** [comment]
I'm not a bash user, but a bit of googling suggests you need special
code to turn on completion for aliases in bash, for example: https://superuser.com/questions/436314/how-can-i-get-bash-to-perform-tab-completion-for-my-aliases

Or just use a better shell, such as zsh for which stuff like this works
out of the box.

**Comment by scopatz** [comment]
Thanks for the link.

I do use a better shell: [xonsh](https://xon.sh/).  I am writing a package for kitty support for xonsh ([xontrib-kitty](https://github.com/scopatz/xontrib-kitty)).  Xonsh supports both its own completion tools and bash-completion. The reason I went down the Bash route was because I couldn't easily figure out how to use the Python kitty completes.  

Specifically, I was looking at [`kitty.complete.find_completions()`](https://github.com/kovidgoyal/kitty/blob/master/kitty/complete.py#L312).  Are there docstrings or docs for how to use this function or module?  It would be much better to use this API than Bash completions.

**Comment by kovidgoyal** [comment]
You dont need to use that API. See https://github.com/kovidgoyal/kitty/commit/c84e73d8e67a19f693aee98be140b08b2483aa83
