### ISSUE TITLE
Question: How to send keystrokes to kitty from a script

### ISSUE THREAD

**Issue by myelsukov** [kovidgoyal/kitty#1759]
I am building a console music player of my dream :)
Building blocks are: MOC (Music on console), kitty and couple of shell scripts.
So I open a kitty tab with three windows. In one of them I run MOC itself, another one is dedicated for displaying lyrics and the third one displays album art.
In the each of the auxiliary windows I am running a special script.
Upon receiving a track change event one of the scripts displays Album Art and another one
retrieves the lyrics and displays it. The lyrics can be longer than the screen, so I need to execute `scroll_home` in that window to uncover the beginning of the lyrics.

I wonder what is the easiest way to initiate the `scroll_home` action from the script?

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/remote-control.html 

In particular the send_text action allows you to send arbitrary bytes to
any kitty window.

**Comment by myelsukov** [comment]
Please forgive my ignorance, but it's not obvious to me how can I send `Ctrl-Shift-Home` using `@ send_text` Could you please give me a hint?

**Comment by kovidgoyal** [comment]
If you want to see what bytes are needed for any particular key
combination, run 

showkey -a


and press the key

Note that ctrl+shift+home is already used in kitty to scroll to the top
of the scrollback buffer, so you will need to unmap it in kitty.conf
first, if you want to see it with showkey, or use another terminal to
run showkey

**Comment by myelsukov** [comment]
Either I was stupid or you didn't understand my problem. :(
I used `showkey -a` and found that CTRL-SHIFT-HOME generates `^[[1;6H`
When I use `kitty @ send-text --match title:Lyrics \\x1B\\x5B\\x31\\x3B\\x36\\x48`
I see `^[[1;6H` printed on the terminal. The `scroll_home` action associated with the CTRL-SHIFT-HOME is not executed.

**Comment by kovidgoyal** [comment]
No, I dont understand your problem. What scroll_home action? You want
kitty to scroll to the top of the scroll back buffer in a specified
window? 

In that case, no, I dont think that functionality is exposed via the
remote control facility. What you can do instead is show the lyrics
using a pager such as less, and then send the bytes for the Home key to
that window, that will cause less to scroll to the top. 

I could add a scroll command to the remote control facility as well, of
course, but using less will work now.

**Comment by myelsukov** [comment]
OK. I had to use a pager. This approach isn't perfect though. The main inconvenience: I have to activate the window to scroll the text using mouse wheel.
It would be much more preferable to me if I could execute `scroll_home` action programmatically.
Frankly, I don't understand why you haven't made all mappable actions available in the kitty shell :) 
![Screenshot_2019-06-28_00-48-34](https://user-images.githubusercontent.com/18082026/60327250-3d7bf000-9940-11e9-9d40-d76480089e07.png)

**Comment by kovidgoyal** [comment]
Feel free to contribute patches to expose more actions via remote control
