### ISSUE TITLE
Rendering glitch with Fira Code font in multiple windows on macOS fullscreen

### ISSUE THREAD

**Issue by zthompson47** [kovidgoyal/kitty#1762]
kitty 0.14.2, macOS 10.14.5, config:
```
# kitty.conf
font_family      Fira Code Retina
```
1. Open kitty and enter fullscreen mode
2. Open new window (cmd+enter)
3. Change layout (kitty_mod+l)
4. Open new window (cmd+enter)

Result:
<img width="1280" alt="Screen Shot 2019-06-28 at 5 50 41 AM" src="https://user-images.githubusercontent.com/184890/60334900-96f91480-996a-11e9-995d-96ca2ae7564c.png">

The screenshot doesn't show it, but if you start typing in any of the three open windows, a cursor appears in that little cutoff segment in the top right (cutoff as well).  What you type is not echoed up there, but the cursor blinking is synchronized with the cursor blinking in the window you're typing in.

**Comment by kovidgoyal** [comment]
That looks like one of the window's border rectangles is not being drawn. Does changing the windo size (prticularly height) fix it? You can do that by exiting fullscreen mode or opening a fourth window.

**Comment by zthompson47** [comment]
Yes, that fixed it.  Both exiting fullscreen mode and opening a fourth window did the trick.

One note, however.  When I exited and re-entered fullscreen mode, kitty became unresponsive, requiring 'kill -9'.  I've seen this happen once before in a month or so of heavy kitty usage, but I don't remember if that case had to do with fullscreen mode.  AFAIK, it's a separate issue, but I'm mentioning it here in case it's related to this issue.  I'll post another issue if it keeps coming up.

**Comment by kovidgoyal** [comment]
Can you figure out a way to reproduce the rendering glitch. I am guessing it has to do with window dimensions. So thta means a particular window size and font size combination. You can control both on the kitty command line like this

```
kitty -o initial_window_height=XXX -o -o remember_window_size=n -o initial_window_width=YYY -o font_size=ZZZ --config NONE
```

**Comment by zthompson47** [comment]
Sorry I didn't get back to your comment sooner - I must have deleted the email alert without looking.

I found a way to reproduce the bug when launched from the command line as you suggested:
```
kitty -o remember_window_size=n -o initial_window_width=640 -o initial_window_height=490 -o font_size=11 --config NONE
```
`initial_window_width` seems to be arbitrary for this bug.  I randomly resized the width after launching kitty a few times, and it persisted.  Setting `initial_window_height=800` also triggered it, and I can imagine it has to do with height modulo font size or something.  I could only get the bug with `font_size=11` in my tests, though.

Also, fullscreen mode and `font_family` are unrelated, so the steps to reproduce are:
1. Open new window (cmd+enter)
2. Change layout (kitty_mod+l)
3. Open new window (cmd+enter)

Should I edit the issue title?

*Possibly related:*
While testing I found another glitch that seems similar.  If my shell prompt is wider than the width of a window after a split I get this:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/184890/61181396-040bdb80-a5f4-11e9-82b5-25e57f1fcd8d.png">
Please let me know if I should file a separate issue for that one.

**Comment by ismay** [comment]
I'e encountered this bug as well when rendering fullscreen at 2560 x 1600 on macOS 10.14.5, with [this kitty.conf](https://github.com/ismay/dotfiles/blob/f0cf6827d779786d82a35cbaaa01ef58ac324345/config/kitty/kitty.conf). With two open windows it looks like this:

<img width="1280" alt="Screenshot 2019-07-20 at 14 19 40" src="https://user-images.githubusercontent.com/7355199/61578582-b44c7900-aaf9-11e9-8697-790136b59d5f.png">

And after opening a third window the glitch shows up top right:

<img width="1280" alt="Screenshot 2019-07-20 at 14 19 51" src="https://user-images.githubusercontent.com/7355199/61578586-c0383b00-aaf9-11e9-8f44-478ce5e7a330.png">

**Comment by ismay** [comment]
Note that after switching kitty to Fira Sans (`brew cask install font-fira-sans`) I'm not encountering this bug anymore.

**Comment by ismay** [comment]
Note that after switching kitty to Fira Code (brew cask install font-fira-code) I'm not encountering this bug anymore.

**Comment by zthompson47** [comment]
@ismay Thanks for the debugging help!  I was able to reproduce the issue by applying the following diff to your kitty.conf:
```
21,24c21,24
< font_family      OperatorMono Nerd Font Book
< bold_font        OperatorMono Nerd Font Bold
< italic_font      OperatorMono Nerd Font Book Italic
< bold_italic_font OperatorMono Nerd Font Bold Italic
---
> font_family      Fira Code
> #bold_font        OperatorMono Nerd Font Bold
> #italic_font      OperatorMono Nerd Font Book Italic
> #bold_italic_font OperatorMono Nerd Font Bold Italic
26c26
< font_size 12.0
---
> font_size 11.0
284c284
< initial_window_height 400
---
> initial_window_height 502
```
I'm pretty sure the issue has more to do with the combination of window height and font size than any particular font family.

**Comment by zthompson47** [comment]
@kovidgoyal I started noticing recently that once I clear the glitch by opening and closing a new window, it actually will come back after switching back and forth between tabs.  This happens only sometimes, and I don't the exact way to reproduce it.

Also, when it comes back, the partial line that's rendered comes from the window that I just switched *from*.  It blinks when the cursor is blinking and stops when the cursor stops blinking.  HTH

**Comment by 1g0rb0hm** [comment]
I have a similar issue and seems to be related to font size. 

**Note** the space between the window frame (yellow) and the terminal on the top right and bottom right.

Changing the font size causes the space between them to grow/shrink.

![Screenshot 2020-03-12 at 16 51 16](https://user-images.githubusercontent.com/24808322/76540439-6f0efa00-6482-11ea-9970-ca984e37900e.png)

**Comment by selckin** [comment]
Also hit this with fira code retina in awesome-wm & single fullscreen terminal

**Comment by steeve** [comment]
I get it with Hack, 4k screen (but not full screen) and 12 font size:
```
font_family                         Hack
bold_font                           auto
italic_font                         auto
bold_italic_font                    auto
font_size                           12.0
```

**Comment by kovidgoyal** [comment]
I looked into this, but could not replicate with

kitty -o remember_window_size=n -o initial_window_width=640 -o initial_window_height=490 -o font_size=11 --config NONE

on macOS, though my macOS laptop does not have a retina screen. Same settings on my linux laptopn with a high dpi screen also failed to reproduce.
