### ISSUE TITLE
It cost too much power on mbp

### ISSUE THREAD

**Issue by netjune** [kovidgoyal/kitty#1763]
I use kitty on my mbp for seval days. Everyday, when I go to sleep, I just close lid. I see that the left battery is 91% tomorrow. If I close kitty before closing the lid. The left battery is 98% tomorrow.

**Comment by kovidgoyal** [comment]
kitty does absolutely nothing when idle, look at activity monitor to confirm. The only thing running inside kitty when nothing is happening is the silly Apple CVDisplayLink thread, and IIRC Cocoa shuts that down when the monitor is turned off.

**Comment by kovidgoyal** [comment]
Oh and you can turn off even CVDisplayLink by setting sync_to_monitor = no in kitty.conf

**Comment by kovidgoyal** [comment]
And I added code to automatically shutdown CVDisplayLink on inactivity
