### ISSUE TITLE
Request: Inverted colors for selected text

### ISSUE THREAD

**Issue by leotaku** [kovidgoyal/kitty#1764]
It is quite common for terminals to simply invert the color of mouse-selected text. It, for example, is the default for xterm and urxvt.

I happen to like said feature and would like to request it being added to kitty. I also think it would make sense to have this feature as we already have the same option for text under the cursor (#126).

Thank you for your hard work on kitty.

**Comment by kovidgoyal** [comment]
This is not something I am a fan of personally, gives me migraines :)
But patches are welcome for an option for it.
