### ISSUE TITLE
Setting title: fixed + variable part?

### ISSUE THREAD

**Issue by pauschuu** [kovidgoyal/kitty#1765]
Right now I have `title kitty` in my default session file.

Because I need to have some fixed "kitty" string within the title to make it easier for tools like KeePass to set the Auto-Type window. 

But I would prefer to have the title started with a fixed string (like "kitty") plus the current directory or the current running program for example.

Is there any kind of placeholder that I probably just missed to include that in the session file? Something like `title kitty %s` or whatever?

**Comment by kovidgoyal** [comment]
No, there is no such functionality. Why do you need to set the title to detect kitty windows? They have WM_CLASS set on X11 and the app id set on wayland to kitty by default which can be customized via the --class command line parameter.

**Comment by Luflosi** [comment]
He may be on macOS. Is there a similar mechanism for macOS?

**Comment by kovidgoyal** [comment]
No idea, not a macOS user.

**Comment by pauschuu** [comment]
I'm not on macOS.

There are several use cases for having a more flexible terminal title:

1. KeePass Auto-Type feature or other password managers which use only the title to match a window
2. Window Managers which give you the ability to type-and-search for windows (like a grep on title)
3. Other software like kupfer which has plugins for finding windows by title
and probably more

The ideal would be if the terminal title was customizable with these 3 components:
- fixed strings
- placeholder for the current directory
- placeholder for the current running program

This would give users full control over the terminal title to customize it in any way they like.

**Comment by kovidgoyal** [comment]
You can customize the title however you like, dynamically. There is no
need to use placeholders. Use either the terminal escape codes to set
the terminal title in your shell, or use the kitty remote control
facility for it.

**Comment by pauschuu** [comment]
I'm not sure, but is there an easy way to have the terminal title showing "ASDF <working_dir>" ?

**Comment by kovidgoyal** [comment]
Just google for shell commands to set terminal window titles, it is trivial.

**Comment by pauschuu** [comment]
Yes but anyway that would mean I have to run a script everytime I cd into something?

**Comment by kovidgoyal** [comment]
No, it doesn't. All modern shells have facilities to do this
automatically via PROMPT_COMMAND or preexec_fn just google for whatever
shell you use.

**Comment by pauschuu** [comment]
Ok thx and sorry to bother you.
