### ISSUE TITLE
The bundled version of glfw doesn't support FreeBSD

### ISSUE THREAD

**Issue by yurivict** [kovidgoyal/kitty#1768]
```
glfw/wl_init.c:34:10: fatal error: 'linux/input.h' file not found
```

The ```glfw``` package is available:
```
glfw-3.3                       Portable framework for OpenGL development
```

**Comment by kovidgoyal** [comment]
Upstream glfw also unconditionally includes that header:
https://github.com/glfw/glfw/blob/master/src/wl_init.c#L34


I'm guessing the freebsd glfw package is either patched in some way or
does not build the glfw wayland backend. In any case thatheader is not
actually needed, so I have removed it.
