### ISSUE TITLE
Backspace and Escape is not recognized

### ISSUE THREAD

**Issue by haqle** [kovidgoyal/kitty#177]
Hi,
I'm having troubles getting the backspace/escape keys recognized by kitty, ^H/^[ works fine though. In konsole, if I type ^V followed by backspace, the character '^?' is inserted, but in kitty, nothing is inserted.

I'm using Fedora 27, zsh 5.4.1, glfw 3.2.1, HarfBuzz 1.7.1, and I built kitty from the last git master

**Comment by kovidgoyal** [comment]
recognized in what application? On my system typing Ctrl-v + backspace gives ^? If you mean in zsh, try running it with an empty zshrc and see if that makes a difference. If it does, you are likely setting up some key mappings in zsh that are causing problems or you have the TERM env var set to something other than xterm-kitty

**Comment by haqle** [comment]
I mean the keys are just not recognized in the commandline. I have the same issues with bash as well so it's not specific to zsh. I tried setting TERM to xterm-kitty and xterm-256color, neither works for me.
I'm not sure if it's related but kitty also prints out this
````
[PARSE ERROR] Unknown CSI code: 't' with start_modifier: '' and end_modifier: '' and parameters: '0 192 46'
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
[PARSE ERROR] Unknown OSC code: 50
````

**Comment by kovidgoyal** [comment]
That doesn't mean anything, bash and zsh could be both be configured the same way. Use a default config. Those parse errors indicate your shell is generating some non-standard escape codes. Which implies it is configured in some non-standard way.

**Comment by kovidgoyal** [comment]
For instance OSC 50 is a code to set the font in the terminal emulator. Neither bash nor zsh use it in out-of-the-box configurations.

**Comment by kovidgoyal** [comment]
Or try it with cat, like this

```
kitty cat
```

which eliminates all interference from shells.

**Comment by haqle** [comment]
I tried again with an empty .zshrc config and the issue persists. When I tested with bash before, I didn't config bash at all so everything was default.

**Comment by kovidgoyal** [comment]
Run 

```
kitty --dump-bytes log.bin cat
```

Then type

a<BS>b<ctrl+C>

and post the log.bin

**Comment by haqle** [comment]
Ahh, I figured out the cause of my issue. I used setxkbmap to use a custom keyboard where I remap different key to the backspace. I didn't suspect this at first because nothing else gave me issues. Is there a way to keep kitty happy with my keyboard layout? This is the remapping part in my xkb symbols file.
```
    key <ESC> { [          XF86WakeUp, XF86WakeUp, XF86WakeUp, XF86WakeUp       ] };                                                                                                                                 
    key <TLDE> { [         Escape,      asciitilde, grave       ] };                                                                                                                                                 
                                                                                                                                                                                 
    key <BKSL> { [         BackSpace,   Delete  ] };                                                                                                                                                                 
    key <BKSP> { [         backslash,   bar     ] }; 
```

**Comment by kovidgoyal** [comment]
Not really, glfw the toolkit kitty uses does not really support things like that, see https://github.com/glfw/glfw/issues/1140

It's on my TODO list to fork glfw and re-implement key handling using libxkbcommon...
