### ISSUE TITLE
Hints Kitten: patterns that wrap in terminal not fully captured.

### ISSUE THREAD

**Issue by kovasap** [kovidgoyal/kitty#1772]
I commonly run up against an issue where I have a string I want to have identified by the hints kitten, but the pattern wraps to the next line and the hints kitten only matches the string up to the wrapping point.  For instance:

```
echo http://this-is-a-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-long-url
```

My custom regex for urls will only match as much as up to the wrapping point.  I would expect the wrapping to be completed ignored by the hints kitten, since it has nothing to do with the actual content of the terminal (b/c it's just an artifact of how big the window is).  Am I misunderstanding something here?

This is my regex (I use it with some other url options in the list of OR'd together prefixes):
```
map ctrl+shift+e kitten hints --type regex --regex "((?:file\:\/\/|ftp\:\/\/|http\:\/\/|https\:\/\/).+?(?:\>|\s))" --program google-chrome
```

**Comment by kovidgoyal** [comment]
Use a multiline regex, prefix with (?m)

**Comment by kovasap** [comment]
That doesn't seem to work for me, with either:

```
map ctrl+shift+e kitten hints --type regex --regex "((?m)(?:file\:\/\/|ftp\:\/\/|http\:\/\/|https\:\/\/).+?(?:\>|\s))" --program google-chrome
```

or

```
map ctrl+shift+e kitten hints --type regex --regex "(?m)((?:file\:\/\/|ftp\:\/\/|http\:\/\/|https\:\/\/).+?(?:\>|\s))" --program google-chrome
```

Am I missing something here?

**Comment by kovidgoyal** [comment]
Yes, you need to add the DOTALL flag to the rgex as well, otherwise .+
will not match across line boundaries.

**Comment by kovasap** [comment]
Got it working finally with:

```
map ctrl+shift+e kitten hints --type regex --regex "(?m)(?s)((?:file\:\/\/|ftp\:\/\/|http\:\/\/|https\:\/\/).+?(?=\)|\>| |\t))" --program google-chrome
```

Thanks for the pointers!
