### ISSUE TITLE
(active | inactive) background color

### ISSUE THREAD

**Issue by disruptek** [kovidgoyal/kitty#1775]
Issues #256 and #900 represent requests for active/inactive background color differentiation.  One resulted in the `inactive_text_alpha` option, while the other was dismissed. Anyone else still interested in this?

A hacky solution would be to hook to window manager events and remotely adjust background color on focus changes, but I'd rather just have a configuration option in kitty.

**Comment by kovidgoyal** [comment]
Not a good idea IMO because changing background colors is not guaranteed
to work. Full screen terminal applications typically set their own
background colors, so changing the background color will have no effect
there, making this a rather unreliable way of indicating active/inactive
status.

**Comment by disruptek** [comment]
[Here is my implementation of that hacky solution.](https://gist.github.com/disruptek/e25688dbc65bd2acd8d11f7bf9d6f0b9)
