### ISSUE TITLE
setterm: terminal xterm-kitty does not support --blength

### ISSUE THREAD

**Issue by cyrinux** [kovidgoyal/kitty#1777]
Hi Kovid,

I got this error with my zsh and kitty running on archlinux.

"setterm: terminal xterm-kitty does not support --blength"

I saw you work on linux bell support, so the support will come or this is another point?

Thanks you for your work.

**Comment by kovidgoyal** [comment]
As is noted in the setterm manpage --blength is only to be used with virtual consoles, not X terminals. It wont work in anything other than a linux console.
