### ISSUE TITLE
Remap new_window on macOS

### ISSUE THREAD

**Issue by tormodatt** [kovidgoyal/kitty#1778]
I'm trying to remap the default behavoir of that cmd+enter opens a new window, as I want to use that shortcut for something else.

I tried `clear_all_shortcuts yes`, `kitty_mod alt` and `map alt+enter new_window`, but cmd+enter still opens a new kitty window.

Where is this shortcut set?

kitty 0.14.2

**Comment by kovidgoyal** [comment]
If you want to remap cmdenter, simply remap it. Clearing shortcuts or
assinginf different shortcuts to its action will not have any effect.

**Comment by tormodatt** [comment]
what if I want to use cmd+enter in another app? I want to use the cmd+enter in Intellj for executing a SQL-query, but when I do a Kitty-window pops up in stead

**Comment by kovidgoyal** [comment]
kitty shortcuts are not global. They work only if kitty is focussed, so
I dont see how pressing cmd+enter could possibly cause a new kitty app
to popup unless kitty already has focus. Oh and if you wish to unmap nay
action in kitty, map it to no-op

**Comment by tormodatt** [comment]
ok thanks, I guess it was the no-op I was looking for. 

i added `map cmd+enter no-op` to my config now. but still, if I quit Kitty completly and focus Chrome or whatever, a Kitty window pops up when I hit cmd+enter. I tried uninstalling kitty, and hitting cmd+enter in Intellj does nothing, so I guess that shortcut is set globally somewhere. however, I do not recall doing that

**Comment by tormodatt** [comment]
finally found what was doing the binding. I had kept a setting from the default config in skhd which I'm also using: https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc#L109

thanks again for the fast response
