### ISSUE TITLE
Unable to use mplus Nerd Font Mono

### ISSUE THREAD

**Issue by ellesde** [kovidgoyal/kitty#1781]
I'm trying to use said font and have tried a variety of configuration options to no avail.

I've tried
- Setting default monospace font
- Changing kitty.conf
- Passing font through -o flag

In all the above cases, kitty was not rendering text using the configured font.

I've read through a lot of issues trying to figure this out but I'm desperately in need of help.

Things I've made certain of are:
- Ensuring kitty can see the font
```
~ 
➜ kitty list-fonts
Courier 10 Pitch
    Courier 10 Pitch Bold
    Courier 10 Pitch Bold Italic
    Courier 10 Pitch Italic
    Courier 10 Pitch Regular

DejaVu Sans Mono
    DejaVu Sans Mono
    DejaVu Sans Mono Bold

Fira Code
    Fira Code Regular

Fira Mono
    Fira Mono
    Fira Mono Bold
    Fira Mono Medium

FreeMono
    FreeMono
    FreeMono Bold
    FreeMono Bold Oblique
    FreeMono Oblique

Liberation Mono
    Liberation Mono
    Liberation Mono Bold
    Liberation Mono Bold Italic
    Liberation Mono Italic

mplus Nerd Font Mono
    M+ 1m bold Nerd Font Complete Mono
    M+ 1m regular Nerd Font Complete Mono
```
- Ensuring it fits the definition of being a monospace font
```
~ 
➜ fc-list : family spacing | grep mplus
mplus Nerd Font Mono:spacing=100
```

Please help!

**Comment by kovidgoyal** [comment]
kitty --config NONE -o font_family "mplus Nerd Font Mono" --debug-font-fallback


Although the way to use Nerd fonts is kitty is not touse patched fonts, as these often have issues. Instead use whatever normal font you want touse and simply install the NERD fonts in addition. kitty should pick them up automatically for symbols not in the main font, or if not you can always use the symbol_map feature in kitty.conf
