### ISSUE TITLE
List window titles (or, check if a window with a given title exists)

### ISSUE THREAD

**Issue by metalelf0** [kovidgoyal/kitty#1783]
Hi, I'm working on a little project that requires interacting with kitty from remote control. One of the use cases involved is: if a window with a given title already exists, send text to it; otherwise open a new window with that title and send text.

I know about `kitty @ ls` but the fact that the output is in json format requires either parsing it via tools like `jq` or grepping titles in it (which of course is doable, but not very elegant).

What would you suggest to get this job done? I feel this is a pretty basic scenario in scripting interactions with kitty, so I'm a little puzzled about how other people deal with this.

Thanks and keep up the great work!

**Comment by kovidgoyal** [comment]
You dont need to use jq, use the python json module and a python script,
which you can run with kitty itself, using

kitty +launch myscript.py

I stopped using shell scripts for scripting decades ago.

**Comment by metalelf0** [comment]
Ok, thanks.
