### ISSUE TITLE
Update Ubuntu package

### ISSUE THREAD

**Issue by travellingprog** [kovidgoyal/kitty#1789]
I'm having a display issue suddenly (the first line of display seems to be partially blocked; the tab bar, which would usually render there, is also not rendering well). 

I thought this was caused by some update and was about to post that issue, until I just realized that the Ubuntu package is still at 0.13.3 while other Linux distributions are at 0.14.2: https://packages.ubuntu.com/disco/kitty

Could you update the Ubuntu package to the latest release? I'll check after that if i'm still having that issue. By the way, I'm on the latest LTS release of Ubuntu (18.04 Bionic Beaver).

Thanks

**Comment by Luflosi** [comment]
@kovidgoyal does not maintain the Ubuntu package, someone else does that. The Ubuntu package is also most likely from debian (https://tracker.debian.org/pkg/kitty). That package should be updated instead. It's on the TODO list of the maintainer: https://udd.debian.org/dmd/?jamessan%40debian.org#todo.

**Comment by kovidgoyal** [comment]
Use the official kitty binariy is you want to stay up to date. https://sw.kovidgoyal.net/kitty/binary.htmlAlthought I'm fairly certain your issue is caused by a broken mesa version.
