### ISSUE TITLE
Not using the fonts asked for (not monospace?)

### ISSUE THREAD

**Issue by kazuoteramoto** [kovidgoyal/kitty#179]
I'm trying to use kitty with [Iosevka](https://github.com/be5invis/Iosevka). But its not loading it either if I set `font_family` or run it with `kitty -o "font_family=Iosevka"`. I checked that is loading a default font (using `lsof`).

I supose the reason is that Iosevka don't have `spacing: 100`:

    $ fc-match -v Iosevka|grep -E '(fullname|spacing):'
    fullname: "Iosevka"(s)
    spacing: 90(i)(w)

Iosevka is also not listed under `kitty list-fonts`. Iosevka Term works with kitty but it don't have ligatures.

Another font with the same behaviour (don't load but the Mono version without ligatures do) is Pragmata Pro. Is this a bad implementation of ligatures on these fonts or is there something kitty can do about? (Fira Code and Hasklig works for me).

**Comment by kovidgoyal** [comment]
kitty only uses monospace fonts, that is the fonts listed under kitty list-fonts. Because kitty speeds up rendering by storing individual cell glyphs on the GPU, and monospaced font is really needed. It could use non-monospaced fonts, but that would lead to many rendering artifacts and lots of bug reports that I dont want to deal with.

**Comment by jpotier** [comment]
Well, Iosevka is a monospace font, isn't it? There does not seem to be any problems with Fira Code either, although in this case it is accepted by kitty.

I'm also trying to get the ligatures of Iosevka to render with kitty, the same way they did for Fira Code. What does need changing in the font for kitty to accept to use it?

**Comment by kovidgoyal** [comment]
Iosevka is not a monospace font. Iosevka Term (or something similar) is the monospace variant and that does not have ligatures.

**Comment by jpotier** [comment]
Styles related to ligations and spacing:
    term : Disable ligations. When this style is present, the font built will not contain ligatures, and its family name will be set to “Iosevka Term”. In case of your OS or editor cannot handle ligatures correctly, you can disable ligations with it.

Iosevka Term is just Iosevka with ligation disabled. How come one can be a monospace font and not the other?

**Comment by kovidgoyal** [comment]
Why dont you ask the creator of Iosevka that? All fonts that identify themselves as monospaced will show up when you do kitty list-fonts. If the font is listed in that, it can be used, if not, it cannot.

**Comment by jpotier** [comment]
Sure, I'll do that. I'm not laying blame here, just trying to understand how this works.

**Comment by jpotier** [comment]
Ok, so Iosevka has a `spacing: 90(i)(s)` which, according to [fontconfig's doc](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfreetypecharsetandspacing.html) corresponds to `FC_DUAL`. This should be workable with kitty, right?

What do you think @kovidgoyal ?

**Comment by jpotier** [comment]
What's more I have built a version of Iosevka that is considered monospace, but with the ligations included. They are not loaded in kitty though.

https://github.com/jpotier/Iosevka/tree/v1.13.42

![screensel](https://user-images.githubusercontent.com/752510/35455615-4d1db8c4-02db-11e8-86a2-cbc522a3efe8.png)

**Comment by kovidgoyal** [comment]
spacing has nothing to do with ligatures. spacing is about whether individual glyphs in the font are all designed to be equally wide or not.

In monospaced fonts a N character ligature is typically implemented as N-1 dummy glyphs and 1 glyph whose width is N times the width of a single glyph, with a negative left bearing. For example:

```
hb-shape --cluster-level=1 --show-extents  ~/work/env/conf/fonts/FiraCode-Regular.otf '==='
[LIG=0+600<0,0,0,0>|LIG=1+600<0,0,0,0>|equal_equal_equal.liga=2+600<-1094,538,1588,-452>]
```

hb-shpae is a frontend to harfbuzz, which is what kitty uses for ligatures.

**Comment by kovidgoyal** [comment]
The other approach to ligatures, which is common in non-monospaced fonts is to simply substitute a single wide glyphs for N monospaced glyphs. Since v 0.7 kitty supports that approach as well. For example:

```
hb-shape --cluster-level=1 --show-extents  ~/work/env/conf/fonts/OperatorMonoLig-Book.otf '==='
[equal_equal_equal.liga=0+1650<78,564,1494,-513>]
```

**Comment by jpotier** [comment]
I see. So in theory no problem for Iosevka then.

**Comment by kovidgoyal** [comment]
yes, the presence of ligatures does not affect whether a font is considered monospace or not as far as kitty is concerned. All that matters is its spacing.

**Comment by jpotier** [comment]
Ok, now I have a build that is recognized by kitty. Ligations are off somehow though:
![screensel](https://user-images.githubusercontent.com/752510/35470113-27e6129c-034c-11e8-884d-9b5f6a04e146.png)

Here is the ttf file of the font: https://framadrop.org/r/163QLHkQI9#y60ZdwuHquUijvj/kaFzxET90CYZwoY7bO4oEaJYpIg=

I'm also talking to the person/team behind Iosevka to see whether this should be resolved at the font level or in kitty.

**Comment by lyneca** [comment]
+1, same issue here

**Comment by IsaacWoods** [comment]
Any progress on this?

**Comment by kovidgoyal** [comment]
See #297
