### ISSUE TITLE
Sirious Ubuntu glitches

### ISSUE THREAD

**Issue by ecx** [kovidgoyal/kitty#1790]
Last month was done a very buggy commit that is cause rendering bugs:
![Screenshot from 2019-07-09 19-01-25](https://user-images.githubusercontent.com/467270/60921544-70f53d80-a2a3-11e9-94a8-760163ef2d4e.png)
every my day starts in Ubuntu from: launching kitty, ssh'ing to remote server, and I see welcome message without first letter "elcome to fish, the friendly interactive shell" (was eated "W"), tmux, mc, ctrl + o
as you see left down corner - there is strange mc trace. To "hide it" I must resize kitty window, but it will gone not totally, "green traces" will be removed by black color(partially eated tab decor). But it's not all: the focus of tab now glitches and can be redrawn after some seconds when I switch to other tabs.
How can I get important logs that will help you to catch this bugs?

**Comment by kovidgoyal** [comment]
This will be because Ubuntu updated its mesa to a broken version. Search Either downgrade mesa to 18.x or upgrad to >= 19.0.5
