### ISSUE TITLE
The motd isn't displayed when logging in on a ssh server

### ISSUE THREAD

**Issue by pandark** [kovidgoyal/kitty#1791]
When I log in a ssh server using urxvt, the motd is displayed.
When I log in to the same ssh server using kitty, it is not.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by pandark** [comment]
@kovidgoyal That's not it.
I have copied the file to ~/.terminfo/x/xterm-kitty via the kitten command **and** I just installed the `kitty-terminfo` package.

**Comment by kovidgoyal** [comment]
In that case presumably whatever yo uare using to display the mtd has
hardcoded some TERM value somewhere.

**Comment by pandark** [comment]
I found out what my problem is…
I aliased `ssh` to `ssh='kitty +kitten ssh'`
When I use the regular `ssh` via `\ssh` instead, the motd is displayed.

**Comment by kovidgoyal** [comment]
Ah yes, the ssh kitten doesn't run a shell directly so probably it bypasses whatever hook the server is using to run motd.

**Comment by pandark** [comment]
I don't know if there is a fix, other than _not using the kitten command as a replacement for regular ssh_.
If not, maybe adding a warning in the FAQ would be nice :slightly_smiling_face:
