### ISSUE TITLE
Is there a way to remap META key?

### ISSUE THREAD

**Issue by banderlog** [kovidgoyal/kitty#1793]
I am using `kitty` under `i3wm` and I need to lunch `tmux`. `i3wm` has a lot of keybindings which use Alt as a META key. `tmux` also has a lot of keybindings with Alt as a META key which I am unable to use because of `i3wm` bindings. Thus I have to rebind every keybinding with META key or redefine META key for `tmux`.

`tmux` developer said that there is no way to remap META key in `tmux` and I should remap it in my terminal ([source](https://github.com/tmux/tmux/issues/1835))

According to <https://sw.kovidgoyal.net/kitty/conf.html>, there is a way to map key using its code: `map 0x61 something`. But is there a way to map one key to another, e.g.: `map Super_R Alt_L`?

**Comment by kovidgoyal** [comment]
No you can map keys to actions not to one another. I use i3wm myself and
simply set the super key as the META key instead of alt. Super key
cannot be usedin most terminal programs, so is perfectly good to use for
the window manager.

**Comment by Luflosi** [comment]
Well, it is sort of possible to rebind keys with https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Send%20arbitrary%20text%20on%20key%20presses, but it is not as easy as rebinding <kbd>super</kbd> to <kbd>alt</kbd>. You would need to map all the key combinations with <kbd>alt</kbd>, at which point you would be better off, just rebinding them in `tmux`.
