### ISSUE TITLE
Images for tabs and scrollbar

### ISSUE THREAD

**Issue by adamhotep** [kovidgoyal/kitty#1794]
I see that kitty has the ability to display images (as mapped to the character grid) and to display text atop images. I've also seen some requests for colored tabs (pending) or GTK-like tabs (dependency undesired → rejected) and it's not long before a similar request for a scrollbar comes along.

I think both can be solved with custom images.

A tab would be three images: left, middle, and right. The middle would be repeated to fill the tab width between the left and right images. It'd be pretty easy to mimic the a GTK tab appearance (though the font size would be the same as the rest of the terminal).

A scrollbar could be implemented by sacrificing one character on the right or left side and using Unicode characters for up and down arrows, the groove, and the bar. Take a look at Midnight Commander for inspiration:
![midnight commander screenshot](https://user-images.githubusercontent.com/6454774/61009783-de57ab80-a341-11e9-8ff4-3e6f3675ce75.png)

This style of scrollbar could of course also accept images for each of those characters, though its width wouldn't be customizable.

**Comment by kovidgoyal** [comment]
I dont actually want a scrollbar in kitty -- I tend to hide scrollbars in whatever programs have them as it is :)

They could of course be optional, but the additional complication is not worth it, at least for me. Patches for an optional scrollbar are welcome, as long as they use native kitty functionality for drawing, not GTK/Qt whatever I'm OK with it.

As for custom tab images, given that the height of the tab is restricted to one line, I dont think it will ever look native. It could of course look nicer than the current one, but that's not sufficient motivation for me. Again, patches are welcome.

**Comment by Seanmatthews** [comment]
How do you scroll back long distances then? Is there a hotkey?

**Comment by kovidgoyal** [comment]
I open the scrollback in a pager or editor and search through it or use the pagers
scroll functionality. https://sw.kovidgoyal.net/kitty/#the-scrollback-buffer

**Comment by alkaris2** [comment]
I find this is incredibly backwards, just because YOU might not want a scrollbar, doesn't mean others can't have or use a scrollbar, it should always be an option to turn on or off at the user's discretion by defining a specific option for it in their config. Nobody wants to sift through long documentations for hours trying to figure out how to have a scrollbar, only to find out there is no functionality for a scrollbar.

**Comment by trygveaa** [comment]
> I find this is incredibly backwards, just because YOU might not want a scrollbar, doesn't mean others can't have or use a scrollbar.

He said patches are welcome (under certain conditions). Do you really find it strange that he doesn't want to spend time writing code he doesn't want to use himself? (and he does write code he doesn't use himself many times, just not for all functionality people request, which I find totally understandable)
