### ISSUE TITLE
Kitty hangs on OSX

### ISSUE THREAD

**Issue by pirj** [kovidgoyal/kitty#1795]
Kitty hangs on macOS from time to time, approximately once a day.
Couldn't find any consistent pattern in those hangs.

The only option is to Force Quit Kitty.

The screen doesn't redraw. It is possible, however, to resize the window - its contents is proportionally resized (distorted).
Keyboard input goes through.

macOS 10.14.5

With Kitty 0.14.0 https://gist.github.com/pirj/a11f44580c4efd21dfa0b84304711056
With Kitty 0.14.2 https://gist.github.com/pirj/87235e671989b62b047e21a78b914921

**Comment by kovidgoyal** [comment]
dup of #1779
