### ISSUE TITLE
resize_draw_strategy not applied when maximizing

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#1798]
It seems that `resize_draw_strategy` is always `scaled` when maximizing the window by double clicking on the title bar.

macos mojave 10.14.5
kitty 0.14.2

**Comment by kovidgoyal** [comment]
That's because the OS does not treat maximize as a resize. There is no start
resizing/end resizing event, which kitty uses to recognize resizes on
macOS.
