### ISSUE TITLE
Can't enter emojis with ctrl+shift+u

### ISSUE THREAD

**Issue by MrCappuccino** [kovidgoyal/kitty#1801]
The ctrl+shift+u menu works for all cases, except when I'm trying to enter a code (F1). Whenever I enter the period key '.', I can't seem to delete the code or press enter to enter the emoji into the terminal.

Version: kitty 0.14.2

Video demonstration: https://0x0.st/z92O.mp4

**Comment by kovidgoyal** [comment]
Already fixed in master

**Comment by Luflosi** [comment]
Maybe it's time for a new release? Is there anything that needs to be done before a new release can be made?

**Comment by kovidgoyal** [comment]
Yeah I need to track down and fix the cause of kitty's event loop
occasionally hanging until you press a key/move the mouse on X11. The
fix for #1782 exposed this bug.

Sadly it only happens once in a few hours, so I either need to figure
out how to make it happen more reliably or write some code stress test
the event loop.
