### ISSUE TITLE
[MacOS] Kitty grabs focus in split fullscreen unexpectedly

### ISSUE THREAD

**Issue by DazWorrall** [kovidgoyal/kitty#1803]
If 2 windows - A and B - share a native fullscreen desktop on MacOS, the window with focus is preserved as you switch to and from that desktop. E.g. if you're typing something into window A, switch to another desktop to copy some text and switch back, you can hit paste and have the contents land exactly where you left your cursor. If kitty is one of those windows it will always grab focus when returning to the split view. The previous example is a real life one for me and several times I've pasted something I didnt mean to into my shell!

Using 0.14.2.

**Comment by Luflosi** [comment]
I cannot reproduce the issue. Here is what I tried:
1. Open kitty and Sublime Text
2. Make the two windows fullscreen and make them share a fullscreen desktop with split-view
3. Focus Sublime Text, this unfocuses kitty
4. Use a multitouch gesture to switch to a desktop with no windows
5. Use a multitouch gesture to switch back
6. Sublime Text has focus, not kitty

**Comment by DazWorrall** [comment]
Weird 🤔I'll give everything a reboot at the next opportunity and see if it persists. Here's a gif for posterity. I can only replicate this with kitty.

![2019-07-15 at 11 42](https://user-images.githubusercontent.com/398706/61210881-c98a6780-a6f5-11e9-87de-269e68cfb688.gif)

**Comment by Luflosi** [comment]
Try starting kitty with `kitty.app/Contents/MacOS/kitty --config NONE` and see is that fixes the issue. If it does, something in your config is causing it and you can find out what is.

**Comment by DazWorrall** [comment]
Ok, having played around I know what this is - I'm switching away to _another kitty window on the next desktop_. This takes focus, then when I return to the split view kitty is actually _retaining_ the focus it got from the next window. This is probably a MacOS thing, sorry to bother.

**Comment by Luflosi** [comment]
That's weird, even when I have another kitty window open on the second desktop, kitty still doesn't have focus when I switch back.

**Comment by DazWorrall** [comment]
Is the other kitty window a separate instance of the app?

Grr, just invalidated my previous theory while writing this comment. I switch the other way to Slack while typing here, switch back and kitty has focus again 🤔

**Comment by Luflosi** [comment]
Did you try the `--config NONE` thing?

**Comment by DazWorrall** [comment]
I did, but perhaps not rigorously enough. Trying again with a more systematic approach.

**Comment by DazWorrall** [comment]
Desktop setup is [ Slack ] | [ Chrome + kitty ] [ kitty ]. Result is what happens when switching back:

| Action | My Config | No Config |
| --- | --- | --- |
| Focus chrome, switch to Slack | Kitty takes focus | ✅
| Focus chrome, switch to fullscreen kitty | Kitty takes focus | Kitty takes focus
| Focus kitty, switch to Slack | ✅| ✅
| Focus kitty, switch to fullscreen kitty | ✅ | ✅

✅ = On return, same app has focus
Fullscreen kitty created with CMD+N.

Something in my config is causing that first de-focus then, I'll try and figure that out. Current config

```
$ egrep -v '^(#|$)' ~/.config/kitty/kitty.conf 
font_family      Monaco
font_size 12.0
open_url_modifiers cmd
copy_on_select yes
select_by_word_characters @-./_~?&%+#
sync_to_monitor no
enable_audio_bell no
enabled_layouts vertical,fat:bias=70,grid
inactive_text_alpha 0.6
macos_option_as_alt no
macos_quit_when_last_window_closed yes
macos_thicken_font 0.75
kitty_mod alt+shift
map shift+page_up   scroll_page_up
map shift+page_down scroll_page_down
map shift+cmd+enter kitten zoom_toggle.py
map cmd+w scroll_end
map alt+left send_text normal \x1bb
map alt+right send_text normal \x1bf
```

**Comment by eldh** [comment]
I had the same problem. Removing `open_url_modifiers cmd` from my config seems to have fixed it, I think.

**Comment by Luflosi** [comment]
@DazWorrall I couldn't reproduce the issue with your config file. Can you try to figure out which config option is responsible for your issue? After looking at the code of `open_url_modifiers`, I couldn't find anything that could be causing this behaviour. A video of the issue could also be helpful.

**Comment by kovidgoyal** [comment]
no followup
