### ISSUE TITLE
Clipboard wiped when kitty is closed

### ISSUE THREAD

**Issue by film42** [kovidgoyal/kitty#1805]
I apologize if this is a duplicate. I searched through open/ closed issues for about 15 minutes before opening.

Env: Arch linux with i3.
```
$ kitty -v
kitty 0.14.2 created by Kovid Goyal
```

Config:
```
copy_on_select clipboard
```

I can copy text from kitty and paste it anywhere, this works great... until I close kitty. As soon as I close kitty the clipboard is wiped. I would expect anything copied from kitty to persist in my clipboard after kitty is closed. If kitty is behaving correctly, would you be open to making this behavior configurable?

P.S. :heart: Kitty!

**Comment by trygveaa** [comment]
There is no persistent clipboard on X11, when you paste something, X11 sends a query to the program which owns the clipboard content. So there is no way for kitty to solve this without staying open in the background after you close it as far as I know.

**Comment by kovidgoyal** [comment]
You need to install a clipboard manager program if you want persistent
clipboard under X11. Otherwise anything copied from any program will be
around only as long as that program is running.
