### ISSUE TITLE
547132131a90318867196a125a3d9b5ab2225b0a causes ctrl+c to fail

### ISSUE THREAD

**Issue by prometheanfire** [kovidgoyal/kitty#1806]
`ctrl+c` works when sudo'd but not su'd.

I'm not familiar enough with the code for the change but I was able to bisect it to this commit.

https://github.com/kovidgoyal/kitty/commit/547132131a90318867196a125a3d9b5ab2225b0a

**Comment by kovidgoyal** [comment]
I tried running

```
su -
yes
and the pressing ctrl+c
```

it worked for me.

**Comment by prometheanfire** [comment]
I'm not sure exactly the cause, I suspected it was my bashrc but xfce4-terminal didn't have a problem and replacing it with distro default didn't help.

**Comment by kovidgoyal** [comment]
It will likely be because that commit blocks a few signals and bash on
your system is not resetting the signal mask, in any case I should have
kitty reset it when launching the child.

**Comment by kovidgoyal** [comment]
Note that I have not actually tested the fix since I cannot replicate the issue, so let me know if it works.

**Comment by prometheanfire** [comment]
seems to work now, thanks
