### ISSUE TITLE
MacOS unable to copy/paste with system clipboard through ssh and tmux

### ISSUE THREAD

**Issue by jessebett** [kovidgoyal/kitty#1807]
I have tried the `no-append` solution to the problem described in #782 but I am still unable to copy/paste from my system keyboard inside a remote tmux session.

e.g. `macOS -> ssh -> vim` if I yank to system keyboard with `"+y` it is not shared with my macOS system keyboard.

Further if I paste from system keyboard here it is fine, but if I paste within `tmux -> vim` all newlines get recursively indented. 

How can I have `macOS -> ssh -> tmux -> vim` share the `macOS` system keyboard?

**Comment by kovidgoyal** [comment]
These are all issues in tmux/vim kitty simply provides the facilities
via OSC 52. You will need to configure the software you use to actually
make use of OSC 52 to do the copying. For vim use vim-poweryank or
vim-osc52 or some such. For tmux I have no idea, I wouldn't touch it
with a ten foot bargepole. But likely some configuration setting to get
it to passthrough OSC 52
