### ISSUE TITLE
Is it possible to show user@host in the title and pwd in the tabs?

### ISSUE THREAD

**Issue by cjnucette** [kovidgoyal/kitty#1810]
Hi, Can this be done or implemented?

Great application btw.

**Comment by kovidgoyal** [comment]
You can probably get it to work using the remote control feature which
allows you to separately set the window and tab titles. You will need to
add some code to your shell rc files to use that facility and enable
remote control. https://sw.kovidgoyal.net/kitty/remote-control.html
