### ISSUE TITLE
With Neovim and Coc plugin it breaks the terminal

### ISSUE THREAD

**Issue by ggsalas** [kovidgoyal/kitty#1811]
Hi, I have a strange bug with Neovim (version: 0.3.8) and [Coc plugin](https://github.com/neoclide/coc.nvim)

Coc is updating the screen for each change of the code inside Neovim, but sometimes it breaks as you can see on this video: https://drive.google.com/file/d/1pWeIb6JVb_cJX81z342bK4EyXn3G92uF

I'm not sure how to debug this, so I'm reporting this bug because seems not happen on other terminal like iTerm2 (on macos).

I'm using Kitty version 0.14.2 on macos 10.14.5.

Thanks.

**Comment by kovidgoyal** [comment]
To debug that you use --dump-commands generate some minimal activity to
reproduce the bug, then edit the list of commands to a minimal set to
reproduce and post that. Use --replay-commands to test the command list.

**Comment by kovidgoyal** [comment]
no followup
