### ISSUE TITLE
Add option for dark themed window decorations

### ISSUE THREAD

**Issue by dtcyganok** [kovidgoyal/kitty#1816]
I prefer to use a dark background for the terminal, but when the terminal is surrounded by light frame it looks inconsistent.

Many applications in the GNOME have a dark window decorations. Is it difficult to implement such an option for kitty?

**Comment by kovidgoyal** [comment]
kitty does not draw window decorations at all, unless you are on a
Wayland compositor that does not support server side window decorations
and you have set the linux_backend to wayland in kitty.conf

So simply set it to auto or x11 and your window decorations will be
drawn byt he system.
