### ISSUE TITLE
Odd rendering issue with patch font

### ISSUE THREAD

**Issue by mhartington** [kovidgoyal/kitty#1818]
Hi there. I have a font that I've patched using nerd-fonts that seems to have issues when rendering the characters "fi"

Now I would have assumed this was an issue with nerd-font and their patcher script, but the same font in other terminals renders fine.

Here's test case with Kitty on the left, iTerm in the middle, and Alacritty on the right.

<img width="1680" alt="Screen Shot 2019-07-20 at 7 21 41 PM" src="https://user-images.githubusercontent.com/2835826/61585168-9e53ae00-ab23-11e9-8967-eeccc6e30cb3.png">

I am using the latest release of kitty (0.14.2). 
Any idea on what could be happening here?

**Comment by Luflosi** [comment]
I don't know why this is happening, @kovidgoyal will have to comment on that but I just wanted to mention, that you don't need patched fonts when using kitty. There is a feature that allows you to specify fonts for specific unicode characters or character ranges, see https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.symbol_map. This might also work automagically without that config option (not 100% sure how well this works).

**Comment by kovidgoyal** [comment]
kitty has support for ligatures. I am guessing there is a fi ligature in your original font. Which means it is not a monospaced font.You should use only monospaced fonts in kitty as it renders text in an actual character grid for performance. 

@Luflosi assuming you have only a single font that provides the private use glyphs on your system, yes it will be picked up automatically.
