### ISSUE TITLE
Question about GLFW

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1823]
Why did you embed the GLFW files directly into the kitty source tree? Using a fork of GLFW in a git submodule would have made cherry-picking changes from upstream much easier, right?

**Comment by kovidgoyal** [comment]
Because kitty's version of glfw is going to diverge from upstream more
and more with time. And the ease of cherrypicking commits is far
outweighed by the increased difficulty of managinig/integrating a
submodule.
