### ISSUE TITLE
Help: I can't get remote control to work.

### ISSUE THREAD

**Issue by raguay** [kovidgoyal/kitty#1824]
I am trying to add Kitty to my workflow using Alfred, but I can't get the remote control stuff to work. If I run Kitty with the --listen-to using a tcp port, the terminal can't be used by me. When I send a command using kitty @ --to, it just says them port isn't valid.

Can you show me a concrete example using this so that I can open new tabs/windows from my Alfred program? I'm sure I'm just not getting something right here.

Thanks.

**Comment by kovidgoyal** [comment]
Why are you using a tcp port? alfred runs on the same machine as kitty, so use a unix socket.  And remember to enable allow_remote_control in kitty.conf.

**Comment by raguay** [comment]
Either way, I can't use the keyboard on that terminal then. I've used this:

kitty -o allow_remote_control=yes --listen-on unix:/tmp/mykitty

And it opens a terminal that all I can do is look at. All keyboard presses go to the iterm I launched Kitty in. That is why I asked for a complete example of how to do it since I must be getting something wrong somewhere.

**Comment by kovidgoyal** [comment]
If you want to pass command line arguments to kitty, use 
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos
