### ISSUE TITLE
desktop shortcut not working when kitty is in Full-screen 

### ISSUE THREAD

**Issue by srbhp** [kovidgoyal/kitty#1831]
```
kitty -v 
kitty 0.14.2 created by Kovid Goyal
```

I am on opensuse KDE. Many desktop shortcuts doesn't work when kitty is in the fullscreen mode. This also happen even when kitty is not in the focus. (example ctrl+F10 )

`kitty -c NONE --debug-keyboard` says 

```
Press scancode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x4c clean_sym: F10 composed_sym: F10 mods: ctrl+numlock glfw_key: 299 (F10) xkb_key: 65479 (F10)
on_key_input: glfw key: 299 native_code: 0xffc7 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
```

**Comment by kovidgoyal** [comment]
Kitty is not responsible for dispatching window manager shortcuts. That
is the job of the window manager. If the window manager cannot dispatch
global shortcuts when kittyis fullscreen that is a bug in the window
manager.
