### ISSUE TITLE
Is a certain change to GLFW still needed?

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1833]
Is a1e9b854e305513c72eff38040873451a8e6fe30 still needed? I think there were some changes to the run loop, so this change may be obsolete.

**Comment by kovidgoyal** [comment]
There is not dispatchCustomEvent in current master.

**Comment by Luflosi** [comment]
So this is not needed? The `GLFWApplication` interface still exists.

**Comment by kovidgoyal** [comment]
GLFWApplication is needed for other reasons
