### ISSUE TITLE
Why is a certain check needed?

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1838]
What is the check for `glfwGetCocoaWindow` for? Other functions don't have a similar check, right?
https://github.com/kovidgoyal/kitty/blob/8c6d593c410888d8a3065fbf7c2ae361a2089dfe/kitty/glfw.c#L639-L640
This check was introduced in 3773aaa8a1a52bd1660e418b9c97d06a755520a6.

**Comment by kovidgoyal** [comment]
I have no idea, probably back then in some circumstances that function was not available.

**Comment by Luflosi** [comment]
Do you think that check is still needed?

**Comment by kovidgoyal** [comment]
No idea, but its harmless, so I dont want to remove it.
