### ISSUE TITLE
Feature Request: Change Font Size utilizing the Mouse Wheel

### ISSUE THREAD

**Issue by a0n** [kovidgoyal/kitty#1839]
My System:
Working with a 2-in-1 HiDPI System (Tablet/Notebook Hybrid) on Sway/Wayland Linux.
With different external Monitors with different Resolutions.

I have to change my Font Size quite often depending on the Work I do, the Screen I use at a given moment and the Seating Position I am In.
I would like to change the Font Size by activating a Modifier key and the mouse scroll wheel.
Similar to Firefox with Ctrl+scroll wheel.

**Comment by Luflosi** [comment]
@kovidgoyal this could possibly be implemented by allowing mouse buttons and scroll events to be mapped like keyboard shortcuts.

**Comment by kovidgoyal** [comment]
This is not something I am particularly interestedin, but patches are
welcome.

@Luflose Yes, the only way I would accept this is via some kind of
generalised support for mapping mouse actions.
