### ISSUE TITLE
Strange thing

### ISSUE THREAD

**Issue by karambaq** [kovidgoyal/kitty#184]
left: kitty
right: urxvt

![image](https://user-images.githubusercontent.com/14233969/33232563-74dd05e2-d219-11e7-9442-45d1715e2aad.png)

**Comment by kovidgoyal** [comment]
Umm I'm going to need a bit more information than that. Like a file containing those characters. And what font you are using.

**Comment by karambaq** [comment]
@kovidgoyal It's Monaco For Powerline.
https://pastebin.com/tayGSk2G

**Comment by kovidgoyal** [comment]
Ah it is using block drawing characters -- I have gotten around to implementing special rendering for them yet, only for the box drawing chars.

**Comment by karambaq** [comment]
Why did you close that?

**Comment by kovidgoyal** [comment]
Because it is fixed, read the commit message.

**Comment by karambaq** [comment]
@kovidgoyal Oh, so fast, I'm sorry. Thank you! Great work. I'm finally moving from urxvt
