### ISSUE TITLE
Parts of strings repeat sometimes

### ISSUE THREAD

**Issue by tanyaionova** [kovidgoyal/kitty#1843]
Steps to reproduce:
```sh
git clone https://github.com/jarun/nnn
cd nnn
make
cd misc/test
sh mktest.sh
../../nnn
# navigate to outdir/unicode/ and select last file
```
Filename at the bottom has repeating `<space>3)]`
Issue **does not** exist in `xterm` and `alacritty`
Issue **does** exist in `0.14.2` with `kitty -c /dev/null` and `0c5d59bc` with `python3 .`

kitty:
![image](https://user-images.githubusercontent.com/42947087/61870980-4254a500-aee8-11e9-9835-8ca859084055.png)

alacritty:
![image](https://user-images.githubusercontent.com/42947087/61871361-4e8d3200-aee9-11e9-83bf-9ece1d4c7a62.png)

**Comment by kovidgoyal** [comment]
This will be because the string width calculations differ for the
unicode characters between kitty and nnn. kitty uses the latest unicode
standard to do its calculations. nnn and alacritty and xterm probably
all use wcswidth() from glibc which is often incorrect.
