### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by Dovydev** [kovidgoyal/kitty#1853]
`[208 18:45:27.825463] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 274, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 217, in _main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

Idk what to do, it worked before. Now it started to complain. I'm running arch linux (manjaro KDE)

**Comment by alwayslivid** [comment]
Could you please run `locale` and share the output?

![image](https://user-images.githubusercontent.com/30193966/61999278-23136e80-b0c6-11e9-95eb-f3e81b326a0e.png)

**Comment by kovidgoyal** [comment]
Your system is not properly configured. You need to install a locale
that matches the value of whatever locale environment variables you have
set. Google: python unsupported locale setting for more details.

**Comment by Dovydev** [comment]
![asdf](https://user-images.githubusercontent.com/10171579/63130310-455c2600-bfba-11e9-8f5c-2eaa4fe02d8d.png)

**Comment by Luflosi** [comment]
The value of `LANG` looks wrong. You should find out where it is set and remove the `nexport`.
