### ISSUE TITLE
new_window_with_cwd doesn't work

### ISSUE THREAD

**Issue by goldylucks** [kovidgoyal/kitty#1854]
Thanks in advance for the help (and for the greatest terminal I've ever used!)

![Peek 2019-07-28 07-51](https://user-images.githubusercontent.com/6963212/62002431-86c08a80-b10c-11e9-9c9d-bd28496440d4.gif)

```
kitty 0.14.2 (65b95999c1) created by Kovid Goyal
Linux goldy 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64
Ubuntu 18.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
Loaded config files: /home/goldy/.config/kitty/kitty.conf
[209 07:49:58.492509] clear_terminal needs two arguments, using defaults
Running under: X11

Config options different from defaults:
copy_on_select    clipboard
disable_ligatures 1
enabled_layouts   ['grid', 'stack']
font_family       Fira Code
font_size         18.0
Added shortcuts:
         control+h KeyAction(func='neighboring_window', args=['left'])
         control+j KeyAction(func='neighboring_window', args=['bottom'])
         control+k KeyAction(func='neighboring_window', args=['top'])
         control+l KeyAction(func='neighboring_window', args=['right'])
         control+alt+enter KeyAction(func='new_window_with_cwd', args=())
         super+l KeyAction(func='clear_terminal', args=['reset', 'active'])
```

**Comment by goldylucks** [comment]
okay this is interesting ...

After a few times of closing and opening kitty, it suddently started working.

Any ideas why that is?

**Comment by goldylucks** [comment]
ok so it sometimes work, sometimes not ... reopening.

**Comment by kovidgoyal** [comment]
it works by querying the kernel for the cwd of the current foreground process in the currently active kitty window. I am guessing when it does not work, the foreground process is not your shell but some other program running inside it.

**Comment by goldylucks** [comment]
no foreground process is running, and it still happens. Any ideas?

![Peek 2019-07-29 19-24](https://user-images.githubusercontent.com/6963212/62064912-93410200-b236-11e9-9dce-2fbb40883f11.gif)

**Comment by kovidgoyal** [comment]
kitty simply reads the cwd from /proc/pid/cwd, see foreground_cwd in
child.py so either there is some foreground processes other than the
shell in the process group or your shell is not setting its cwd
globally.

**Comment by goldylucks** [comment]
>kitty simply reads the cwd from /proc/pid/cwd

I don't have pid, cwd or pwd under `/proc`. Maybe that's the problem?

> so either there is some foreground processes other than the
shell

Wouldn't that show in the `fg` command I input in the gif above?

>  or your shell is not setting its cwd globally.

I use zsh with oh my zsh, with very little configuration.

I googled "zsh set cwd globally" and didn't find any entries remotely related :/

typing `cwd` in the terminal produces nothing, but pwd works.

What's the fix here? Should I manually add a custom script to `/proc/pid/cwd` to take care of that?

**Comment by kovidgoyal** [comment]
pid refers to the process number which will be under /proc

You will need to figure out why it is not working on your system,
sinceit issomething specific to that. Run kitty from source and some
prints() to the functions in child.py to see why you dont get the right
cwd.

**Comment by goldylucks** [comment]
is there a way to set it to `pwd`?

**Comment by goldylucks** [comment]
never mind, I  think I found the problem, thanks
