### ISSUE TITLE
Terminal font is acting weird

### ISSUE THREAD

**Issue by Dutchthunderbolt** [kovidgoyal/kitty#1857]
When I open the terminal the tekst is all messed up and stays this way (see included video)
[kitty.zip](https://github.com/kovidgoyal/kitty/files/3439436/kitty.zip)
.
Is there any fix or am i just out of luck?

**Comment by kovidgoyal** [comment]
Couple of things to check:

1) Your mesa version is either < 19 or > 19.0.5
2) Specify a proper font in kitty.conf (check with -debug-font-fallback
to see what font kitty is using)
3) Make sure your system is set up with UTF-8 encoding.

**Comment by Luflosi** [comment]
Just to clarify: In 2, that's `kitty --debug-font-fallback`.
