### ISSUE TITLE
Shift-up and Shift-down is unmapped

### ISSUE THREAD

**Issue by vsajko** [kovidgoyal/kitty#186]
Thanks for great terminal.
There is a issue that Shift+UP and Shift-DOWN gives same response as UP and DOWN on Linux.
Response is same as for UP and DOWN.
I can provide PR if you like.

**Comment by kovidgoyal** [comment]
The default mapping for scroll up and down is ctrl+shift+up/down. If you want to change it, simply change it in your kitty.conf.

**Comment by vsajko** [comment]
And if you want to ue it in other program? Vim for example

**Comment by kovidgoyal** [comment]
Not sure what you are asking. full screen application like vim define their own keyboard shortcuts. These have nothing to do with the keyboard shortcuts defined by the terminal emulator which are used to scroll through the scrollback buffer of the *terminal*.

**Comment by vsajko** [comment]
I didn't explained it well.
In Xterm type cat and press DOWN
you get ```^[[B```
For Shift-DOWN you get  ```^[[1;2B```
Result is different depending on did you used Shift or not.
Same is also in GnomeTerminal, Urxvtt, Alacrity.
In Kitty you get same result for DOWN and Shift-DOWN

If you want to map <S-Up> in vim or any other program vim depends on terminal to make difference between those 2.
So I can map <S-Up> to some command in vim but it works in all terminals except Kitty.

**Comment by kovidgoyal** [comment]
Ah, I get it now :)

Well you can use the 

```
map shift+down send_text all \033[1;2B
```

But, sure this should probably be made the default behavior.
