### ISSUE TITLE
[Linux] Emacs client super key

### ISSUE THREAD

**Issue by ja0nz** [kovidgoyal/kitty#1861]
Anyone using **emacsclient** here? In my setup kitty doesn't recognize the _super key_ (keycode 133) keybindings while other terminal emulators like Konsole do. Control and Alt keybindings work expectedly.

This is how I assign the keybindings (using [Emacs Prelude](https://github.com/bbatsov/prelude)):
```
(defvar prelude-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "s-r") 'crux-recentf-find-file)
...
)
```

**Comment by kovidgoyal** [comment]
The super modifier is not supported by traditional terminal programs. I am
guessing konsole is using some custom keyboard protocol, for which
someone added support to emacsclient. Use showkey -a to see wha codes
konsole is sending. You can tell kitty to send the same codes using the
send_text facility 

https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Send arbitrary text on key presses

**Comment by kovidgoyal** [comment]
Actually the other way around, konsole hardcoded support for emacs weird prefix scheme https://bugs.kde.org/show_bug.cgi?id=96282

**Comment by ja0nz** [comment]
Thank you for your reply and explanation! I just was confused because kitty actually logs the super key correctly:

`Release scancode: 0x85 clean_sym: Super_L mods: super glfw_key: 343 (LEFT SUPER) xkb_key: 65515 (Super_L)`

I may be mistaken but according to https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts all GLFW keys should be supported, right?

I will try your fix with send_text. Thank you again:)

**Comment by kovidgoyal** [comment]
kitty supports super just fine, it is terminal programs that do not
support it. You can see it in action in kitty by using kitty's extended
keyboard protocol: https://sw.kovidgoyal.net/kitty/protocol-extensions.html#keyboard-handling

kitty +kitten key_demo

**Comment by Sleepful** [comment]
Hello @kovidgoyal , I am new to kitty, and I am wondering if there's a way to get full emacs keybindings with it.

Would it be possible to create a `kitty` that translates the keypresses to the "weird emacs prefix scheme"?

I am willing to create this kitty but I am a little clueless.

I imagine the kitty would need to own emacs and act as a communication layer between the terminal and emacs, and intercept the key chords from the terminal to translate it to ones that emacs can understand.

Any help is very appreciated.

**Comment by kovidgoyal** [comment]
You can ask kitty to send any bytes you like in response to any keypress
using the send_text directive in kitty.conf

On Mon, Feb 15, 2021 at 06:21:07PM -0800, Jose Vargas wrote:
> Hello @kovidgoyal , I am new to kitty, and I am wondering if there's a way to get full emacs keybindings with it.
> 
> Would it be possible to create a `kitty` that translates the keypresses to the "weird emacs prefix scheme"?
> 
> I am willing to create this kitty but I am a little clueless.
> 
> I imagine the kitty would need to own emacs and act as a communication layer between the terminal and emacs, and intercept the key chords from the terminal to translate it to ones that emacs can understand.
> 
> Any help is very appreciated.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/1861#issuecomment-779539360

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by Sleepful** [comment]
Using send_text I would need to write a `map` inside `kitty.conf` for every combination of keys.
I imagine there could be a better way of doing this? Ideally I would be able to intercept input, and simply replace the modifier keys for their prefix, and then append the last input letter.

**Comment by kovidgoyal** [comment]
There's no way to do that short of modifying kitty source code. And then emacs weird prefix scheme will break all other terminal applications, so you would only ever be able to run emacs inside the modified kitty. 

And rather than doing that, why dont you modify emacs' source code to actually use a proper keyboard reporting protocol instead of all these hacks piled on top of hacks. The next release of kitty has a very easy to use and comprehensive keyboard reporting protocol as discussed in #3248 

Since emacs likes to use modifiers, their developers should actually care about fixing this properly, once and for all.

**Comment by Sleepful** [comment]
Of course, thanks for your guidance. I'm just trying to get something that works with the least amount of work 😌

I did download Kitty from the master branch to look at the CSI codes, those look very neat.

Modifying the emacs source is a little scary, maybe I can try to implement as a separate emacs package. And if that doesn't work then emacs source would be only option. Anyway, the demo-keys looks awesome. Can't believe no other terminal had done this before.

**Comment by Sleepful** [comment]
> their developers should actually care about fixing this properly, once and for all.

I'm not sure they care about something they don't use. Those that use emacs in a terminal probably use the xterm "hack" with "modifyOtherKeys". Ref: [iTerm support](https://gitlab.com/gnachman/iterm2/-/issues/8382#note_365264207), [Alacritty's issue](https://github.com/alacritty/alacritty/issues/3101).

Right now, adding special escape sequences for every combination inside `kitty.conf` and capturing them in `emacs` seems like the most straightforward solution.
