### ISSUE TITLE
Is there a way for a plugin to add GUI buttons?

### ISSUE THREAD

**Issue by mikepanayotov** [kovidgoyal/kitty#1862]
Kitty is great, but I need it even better to boost my productivity. I would like to develop a plugin that add UI buttons that execute commands. Imagine you work with `react-native` and you have buttons on that tab that execute `react-native link`, `cd ios && pod install`, `npm run start:ios`, etc. Is this possible?

**Comment by kovidgoyal** [comment]
kitty does not do GUI buttons, it is keyboard focused. If you wish to
send commands to the active window you can do that via keyboard
shortcuts defined in kitty.conf, see 
https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Send arbitrary text on key presses

**Comment by Luflosi** [comment]
You could draw buttons with ASCII art or use kitty's capability to display images and then use a mouse protocol to record mouse clicks. This should allow you to do what you want if I understood it correctly.
