### ISSUE TITLE
Children processes should be terminated on kitty exit

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#1863]
On exiting a Kitty instance with running children processes, the children processes keep running:

![children-process-alive-after-kitty-exit](https://user-images.githubusercontent.com/522085/62053319-5d276200-b1e5-11e9-9ebf-260265c9df4c.gif)

To me it's unintuitive and contrary to other terminal emulators behavior. Here's GNOME Terminal:

![gnometerm-killing-children-on-exit](https://user-images.githubusercontent.com/522085/62053826-636a0e00-b1e6-11e9-863d-05fa412958d2.gif)

I looked for an option to terminate such children processes when parent kitty itself exits, but didn't find one (e.g. `close_child_on_kitty_death`). Am I missing it?

**Motivation**: after a few hours/days of work in kitty that included exiting kitties with running processes, I often realize I have many of these running processes still alive and consuming lots of CPU/RAM resources, while I was expecting them to be long dead.

I'm running kitty 0.14.3 with the fish shell 3.0.2, under Linux.

**Comment by kovidgoyal** [comment]
I cannot reproduce, on a normal kitty exit all windows are closed, when
a window is closed, the child program running in it is sent a SIGHUP
signal. It is up to the child process how it handles that signal. Most
terminal programs such as shells will quit on getting it and send it to
all their child processes as well.

https://en.wikipedia.org/wiki/SIGHUP

You can confirm this for yourself by putting in a printf() in the
hangup() function in child-monitor.c

Steps I tried:

1) Run kitty bash
2) Close kitty using the window manager's close window function
3) No bash process is left running

**Comment by ronjouch** [comment]
@kovidgoyal thanks for the fast feedback as usual. Sounds like a `fish` misconfiguration or bug then. Digging.
