### ISSUE TITLE
Sending control characters with an active selection

### ISSUE THREAD

**Issue by taylorthurlow** [kovidgoyal/kitty#1864]
I can't send `Ctrl+C` when I have a selection in the current window.

**Comment by kovidgoyal** [comment]
I cannot reproduce, steps I tried:

1) Run ls
2) double click a word to select it
3) Press Ctrl+C
4) The ctrl+c causes the shell to start a new prompt, as epected

**Comment by taylorthurlow** [comment]
Hmm, that's unfortunate. Following your steps I'm able to reproduce on multiple machines. Both have the same configuration, for what it's worth. I'll keep investigating and let you know if I figure anything out.

**Comment by kovidgoyal** [comment]
Which shell are you using?

**Comment by taylorthurlow** [comment]
I'm using `zsh` on both.

**Comment by kovidgoyal** [comment]
As am I. try running with an empty zshrc

**Comment by taylorthurlow** [comment]
Running with an empty zshrc had no effect.

If it's helpful, here's my `kitty.conf` with the comments removed: https://gist.github.com/taylorthurlow/0bb8414a62123ab0d78752d5069601de

**Comment by kovidgoyal** [comment]
I cant think of any kitty setting that could possibly affect this, but
use 

kitty --debug-config

if you wish to post your config options.
