### ISSUE TITLE
Kitty runs .profile

### ISSUE THREAD

**Issue by asdfjkluiop** [kovidgoyal/kitty#1867]
I just updated to v0.14.3 and now for some reason my .profile is being run by bash, this does not happen on the older version. Is kitty by any chance running bash with -l or something else that would cause it to think it's the login shell?

**Comment by kovidgoyal** [comment]
Yes, kitty will now run the shell to try to read the value of EDITOR set
in the shell's RC files so that it works out of the box for people who
dont know how to set environment values system-wide. Set the env var
system wide so that kitty inherits it and it wont run the shell.

**Comment by yw662** [comment]
But how to prevent it from calling .profile ? It should be non-login shell right ?

**Comment by mikelward** [comment]
This is also causing me problems. My `~/.profile` runs `~/.logout`, which cleans up my session.

This behavior is different from most terminals. I don't think it should do this by default.

**Comment by Luflosi** [comment]
Set the `EDITOR` environment variable system-wide or change the [editor](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.editor) config option.

**Comment by kovidgoyal** [comment]
All terminals run shells. If you mean kitty should not run a login shell, running a login shell is pretty much the only way to reliably get a shell variable set in an rc file that is usually run in interactive mode. People are sadly in the habit of putting env variable exports in rc files that are only run in interactive or login mode. So the *only* way to get access to those variables is to run the shell in that mode.

**Comment by mikelward** [comment]
https://github.com/kovidgoyal/kitty/blob/145ec86d3bacae7f590009f2a140a994a92626bd/kitty/child.py#L253 seems accurate to me.

But it also suggests kitty only prepends `-` on macOS. Hmm...

**Comment by mikelward** [comment]
Thanks @Luflosi . `read_shell_environment` does seem to be the cause. That is very unexpected behavior!

**Comment by yw662** [comment]
Login shell is only for login. It is prepared for starting new sessions, or, for processes directly called by /usr/bin/login.

A terminal emulator is not a new session, so it is not a login shell. That is it.

**Comment by yw662** [comment]
Besides rc file is sourced by all interactive shells, not only login shell. If what you want is to source rc file, instead of rc and profile, you should run it as interactive, not login.

**Comment by kovidgoyal** [comment]
> Besides rc file is sourced by all interactive shells, not only login shell. If what you want is to source rc file, instead of rc and profile, you should run it as interactive, not login.

And doing that would still source .profile, so what do you think you are solving??

**Comment by kovidgoyal** [comment]
> Thanks @Luflosi . `read_shell_environment` does seem to be the cause. That is very unexpected behavior!

You dont expect the terminal emulator to run a shell!!

**Comment by mikelward** [comment]
I expect it run the shell once, and as a non-login shell.

Former you agreed with me in the link I posted above. ;)

**Comment by kovidgoyal** [comment]
On Sat, Jul 11, 2020 at 08:44:53PM -0700, Mikel Ward wrote:
> I expect it run the shell once, and as a non-login shell.

You let me know how to extract environment variables, doing that, and I
will gladly implement a patch.

**Comment by mikelward** [comment]
It's easy enough for me to work around the surprising behavior by exporting
EDITOR even for non-interactive shells. And it was a bug in my .exitrc to
kill an ssh-agent without properly verifying it was the one started in
.profile.

But I'm still not sure it's a good idea for kitty to be invoking login
shells, especially not just to query the user's environment and then tear
down. Login shells can have side effects, and can be expensive. Or at least
that's my take on the difference between .profile and .shrc (and
equivalent).

**Comment by kovidgoyal** [comment]
On Sat, Jul 11, 2020 at 09:05:04PM -0700, Mikel Ward wrote:
> But I'm still not sure it's a good idea for kitty to be invoking login
> shells, especially not just to query the user's environment and then tear
> down. Login shells can have side effects, and can be expensive. Or at least
> that's my take on the difference between .profile and .shrc (and
> equivalent).

Sure, I would love to not do it, it's not like I do it for giggles. The
problem is people set EDITOR in their shell rc files not system wide,
especially on macOS because Apple in their infinite wisdom, provide no
good way to set environment variables system-wide. 

Which means that I get bug reports about kitty not respecting EDITOR.
The number of people that want EDITOR to work out of the box exceeds the
number of people that write ~/.profile to have side-effects.

**Comment by mikelward** [comment]
I'd probably just fall back to /usr/bin/vi or complain it's unset. But
that's just me. :)

**Comment by mikelward** [comment]
Yep. Understood. :)

**Comment by yw662** [comment]
https://wiki.archlinux.org/index.php/Bash

Login shells and interactive non-loginw shells are different.

**Comment by kovidgoyal** [comment]
> https://wiki.archlinux.org/index.php/Bash Login shells and interactive non-login shells are different.
> […](#)
> On Sat, Jul 11, 2020, 7:41 PM Kovid Goyal ***@***.***> wrote: Besides rc file is sourced by all interactive shells, not only login shell. If what you want is to source rc file, instead of rc and profile, you should run it as interactive, not login. And doing that would still source .profile, so what do you think you are solving??

Sigh, do you really imagine I dont know that. Try running an interactive shell as a background process and see what happens.
