### ISSUE TITLE
.bash_profile not being sourced and altert bell sounds missing

### ISSUE THREAD

**Issue by iamrobox001** [kovidgoyal/kitty#1870]
I am using Arch Linux, and after update 0.14.3-1 kitty isn't sourcing my .bash_profile anymore. It works as intended in rxvt-unicode.

![1564504413](https://user-images.githubusercontent.com/38200989/62149609-a235bc00-b2eb-11e9-8b89-004644394dd6.png)
Here is the content of .bash_profile:
```
`[ranger@BlueRingedOctopus ~]$ cat .bash_profile
export XDG_CONFIG_HOME=$HOME/.config
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_OPTIONS='-Dsun.java2d.opengl=true'
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
PATH=$PATH:$HOME/.local/bin
export PATH

# aliases
alias tmux='tmux -2'
alias list-packages='pacman -Qi | egrep "^(Name|Installed)" | cut -f2 -d":" | paste - - | column -t | sort -nr -k 2 | grep MiB'
alias renpydev='python $HOME/.local/bin/renpydev.py'
alias unren='sh $HOME/.local/bin/unren.sh "$PWD"'
alias grep='grep --color=auto'
alias linuxit='python $HOME/.local/bin/renpy_version.py'
alias myip='python $HOME/.local/bin/myip.py'
alias tauon='python /opt/tauon-music-box/tauon.py'
alias lockscr='betterlockscreen --lock blur --text "Locked - BlueRingedOctopus"'
alias nmrestart='sudo systemctl restart NetworkManager.service'

# source $HOME/.bashrc
[[ -f ~/.bashrc ]] && . ~/.bashrc
`
```
Also, the alert bell sound which occurs on reaching the end of line with backspace or trying to tab complete with multiple possible alternatives, etc. stopped working when using kitty. While they continue working on rxvt-unicode for comparison.

**Comment by Luflosi** [comment]
I don't know about the `.bash_profile`, @kovidgoyal will have to comment on that.
There was a change in the way that bell sound is being played. Read @kovidgoyal's comment in a similar issue: https://github.com/kovidgoyal/kitty/issues/1866#issuecomment-516214100, maybe that helps.

**Comment by YokaiRick** [comment]
It sources .bashrc / .bash_profile for me, but since the last to update 0.14.3-1 on Arch it runs the following script within .bashrc wrong (everytime i open a new kitty instance, another sway instance is created, maybe the $tty isn't set correctly anymore -> downgrading kitty fixes this problem for me

``` #If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
        exec sway
  else
        exec fish
fi

**Comment by Luflosi** [comment]
@YokaiRick see #1867.

**Comment by YokaiRick** [comment]
@Luflosi ah thanks, i fixed it

**Comment by kovidgoyal** [comment]
Post the output of kitty --debug-config

**Comment by iamrobox001** [comment]
> Post the output of kitty --debug-config

```
[ranger@BlueRingedOctopus ~]$ kitty --debug-config
kitty 0.14.3 created by Kovid Goyal
Linux BlueRingedOctopus 5.2.4-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 28 10:52:46 UTC 2019 x86_64
Arch Linux \r (\l)
Loaded config files: /home/ranger/.config/kitty/kitty.conf
[212 07:52:24.011047] Ignoring unknown config key: adjust_line_width
[212 07:52:24.011097] Ignoring unknown config key: disable_lignature
Running under: X11

Config options different from defaults:
adjust_line_height      1
background              Color(red=10, green=11, blue=10)
color0                  Color(red=10, green=11, blue=10)
color1                  Color(red=56, green=72, blue=89)
color10                 Color(red=82, green=85, blue=96)
color11                 Color(red=158, green=95, blue=86)
color12                 Color(red=69, green=69, blue=145)
color13                 Color(red=94, green=112, blue=140)
color14                 Color(red=112, green=143, blue=160)
color15                 Color(red=175, green=208, blue=221)
color2                  Color(red=82, green=85, blue=96)
color3                  Color(red=158, green=95, blue=86)
color4                  Color(red=69, green=69, blue=145)
color5                  Color(red=94, green=112, blue=140)
color6                  Color(red=112, green=143, blue=160)
color7                  Color(red=175, green=208, blue=221)
color8                  Color(red=122, green=145, blue=154)
color9                  Color(red=56, green=72, blue=89)
cursor                  Color(red=175, green=208, blue=221)
focus_follows_mouse     True
font_family             Hack Regular
font_size               9.0
foreground              Color(red=175, green=208, blue=221)
wheel_scroll_multiplier 3.0
window_padding_width    5.0
```

**Comment by kovidgoyal** [comment]
I dont see anything suspicious there, I suggest moving ~/.bash_profile
to ~/.profile which is more robust anyway (reboot after doing that). Or
alternatively set shell in kitty.conf to bash -l -i which will force
bash to start in login+interactive mode which will cause it to read
~/.bash_profile

Read the bash man page for details, or https://askubuntu.com/questions/121073/why-bash-profile-is-not-getting-sourced-when-opening-a-terminal

**Comment by yw662** [comment]
guy, .bash_profile should only be sourced by login shell.

**Comment by iamrobox001** [comment]
> guy, .bash_profile should only be sourced by login shell.
I use login shell (tty) to login. I don't have a graphical login manager.

**Comment by yw662** [comment]
That is what I mean. We never tell kitty to run login shell. So it should never think of .profile, or .bash_profile, or sth. It IS a bug.
