### ISSUE TITLE
feature request: use diffrent fonts for ASCII character and non-ASCII character

### ISSUE THREAD

**Issue by dzpao** [kovidgoyal/kitty#1875]
just like iTerm2:

![image](https://user-images.githubusercontent.com/52447680/62260367-52b6d380-b444-11e9-8a75-e51cec0c9157.png)

thanks.

**Comment by kovidgoyal** [comment]
Use symbol_map in kitty.conf

Although there should be no need since appropriate fonts are chosen automatically.
