### ISSUE TITLE
How to enter number sign with alt key mac

### ISSUE THREAD

**Issue by wmonk** [kovidgoyal/kitty#1877]
I have `macos_option_as_alt yes` set in my config, which means I can still use option commands on my command line. But I still want to be able to add things like `#` or `€` which in macos are alt+3 and alt+2 respectively.

Can you help with adding a keybinding for those sequences? This is the output from `cat` with those keybindings.

```
$ cat
^[3

^[2
```

I tried things like `map ^[3 send_text all \x23` but that didn't work. Probably I need to escape something in that setting?

**Comment by kovidgoyal** [comment]
Just use left or right for that option, that way one option key will act
as alt and the other will remain as normal option key.
