### ISSUE TITLE
[Feature request] Make set-colors persistent for the whole session

### ISSUE THREAD

**Issue by metalelf0** [kovidgoyal/kitty#1878]
The current behaviour of `kitty @ set-colors [-a]` is to set a provided color scheme to the current window, or to all windows if the `-a` flag is provided.

However, if you open a new window (or a new tab) after using `set-colors`, the configuration is still the one loaded from `kitty.conf`, which is never re-read after starting the kitty instance, as far as I can tell.

Would it be possible to have something like a `-p` switch (persistent), or `-s` (sticky), to make kitty apply the color scheme also to new windows and tabs?

Thank you.

**Comment by SolitudeSF** [comment]
the colors persist on my machine

**Comment by SolitudeSF** [comment]
huh, nevermind, they persist when i use `set-colors -c colorfile`, but not when providing individual colors.

**Comment by metalelf0** [comment]
You're right, it's the `-c` switch. Shame on me for not noticing that. Thank you!
