### ISSUE TITLE
[Feature Request] Make hint characters configurable

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#1879]
I'm used to having the characters for hints on the home row (from browser extensions like VimFx). It'd be great if the hints kitten could accept a string of characters to use in hints, the first character would be used where `1` is used now, etc.

Additionally, it'd be great if kittens could be configured separately in `kitty.conf` or aliased. I've recently been bitten by #1289 and having to remember to pass `--hints-offset=0` for every use of the hints kitten is rather annoying. (I'm also of the opinion that the changed default only benefits people who don't touch type and I'm not sure that's the majority. But I'd be fine with a better way to change the default.)

**Comment by kovidgoyal** [comment]
Not sure what you mean with regards to aliasing kittens. Simply pass any
parameters you want to the kitten when you define the key map that
invokes the kitten in kitty.conf

**Comment by toonn** [comment]
Should I open a new issue for the second request?
I'll try explaining better here anyway:

Providing the `--hints-offset=0` for every mapping using the hints kitten is annoying and error prone. It adds a lot of line noise to the mappings. I mostly used the defaults, to potentially benefit from changes for the better. Now I have to explicitly remap the default maps just to pass the offset flag.

Two solutions I suggested, as an example take `map kitty_mod+e kitten hints --hints-offset=0` but achieved without changing the mapping in the default config:
  1. Make the kittens configurable, adding a generic way to specify options that are always passed to kittens, something like `kitten-name_option-name = whatever-value`. For the example, `kitten-hints_hints-offset = 0`, now all the default maps using the hints kitten use offset 0.
  2. Add a way to alias kittens specifically or commands in general. `hints = hints --hints-offset=0` would achieve the same thing as before because it shadows `hints` as used in the default mappings. Would also make it easy to do things like `hint0 = kitten hints --hints-offset=0`, `hintA = kittenn hints --hints-offset=0 --alphabet abc`, to be used in mappings like `map kitty_mod+e hint0` and `map kitty_mod+o hintA --program @ --program $browser` (which'd open  a link in your browser for previewing but also copy it to your clipboard, this is something I do a lot with cli pastebins, so multiple allowed actions would be nice too, currently I have to use two maps every time I want to share a paste to irc).

**Comment by kovidgoyal** [comment]
Create your own custom kitten that basically just calls the
implementation of the builtin kitten with whatever arguments you like. 
https://sw.kovidgoyal.net/kitty/kittens/custom.html

Then you can use it in all your mappings as an alias. 

I could consider add some general mechanism to parsing kitty.conf
that would allow for variable substitution, but not one specifically for
kittens/maps.

**Comment by kovidgoyal** [comment]
Oh and I added the ability to specify --program multiple times

**Comment by kovidgoyal** [comment]
Actually adding an aliasing facility for kittens is a sufficiently simple change that I decided to do it anyway.

**Comment by toonn** [comment]
This is great. Now all I need to know is how to get the default behavior of opening the browser in `map kitty_mod+e kitten hints` to work with multiple `--program` flags. Would `map kitty_mod+e kitten hints --program --program @` work for both opening an url in the system browser and copying it to the clipboard?

**Comment by kovidgoyal** [comment]
--program default

**Comment by BlueDrink9** [comment]
I found this issue because I was about to open a similar one. Browser-based vi hinting allows using character combinations for hints, rather than numbers.

Is it currently possible to configure hints to be characters rather than numbers?
Or is this something that would require a new feature?

As far as I can tell you have only answered the other part of this query, about default options.

Love your work, kitty is phenomenal software!

**Comment by trygveaa** [comment]
@BlueDrink9: He implemented that feature request in the commit which closed this issue: 05f7334

**Comment by BlueDrink9** [comment]
Thank you! Such a great dev
