### ISSUE TITLE
Confirmation on multiline paste

### ISSUE THREAD

**Issue by tobia** [kovidgoyal/kitty#188]
Some terminals (rxvt, qterminal, and probably others) have an optional confirmation behavior when pasting text that contains one or more newline `\n` characters.

This is a useful safety net to avoiding executing a command when the text you copied from some other program inadvertently contains a newline. It should apply both to clipboard paste and selection paste.

Rxvt's implementation is done in Perl (it can be found in `/usr/lib/urxvt/perl/confirm-paste`) and displays a one-line prompt at the bottom of the terminal, with a distinct color, saying: "Paste of $count lines, continue? (y/n)"

I'm not sure what the best way would be to add this feature to Kitty, because I have yet to see a confirmation prompt in it. Maybe it could reuse the "tab bar" space, making it red, and ask for the (y/n) key?

I'll just leave this feature request here for any intrepid hacker who wishes to try their hand at it!

**Comment by kovidgoyal** [comment]
Why is this needed at all? kitty supports bracketed paste which means that as long as you use a modern shell with support for it (such as zsh), there is no need for worry. Pasting multiline text is not executed.

**Comment by kovidgoyal** [comment]
No followup
