### ISSUE TITLE
Changes to Font in kitty.conf have no effect

### ISSUE THREAD

**Issue by odinsride** [kovidgoyal/kitty#1880]
I am running kitty on Debian 10 and have installed fonts-powerline as well. I was trying to use Roboto Mono for Powerline, but the branch symbol for git status renders as a capital L with an accent over top of it.

Anyway, I then cloned fonts-powerline from git and manually installed those Roboto Mono for Powerline ttf files, and rebuilt the font cache.  The symbol still doesn't render properly.

So, I thought I would try changing to some completely other font, like Hack.  I relaunched kitty and it doesn't show any difference in the font.  When I run "kitty font-list", neither Hack or Roboto Mono for Powerline are listed. Is this the issue? If so, how to I use Roboto Mono for Powerline with kitty?

Thanks!

**Comment by SolitudeSF** [comment]
use normal non-patched font as your main font and add this to `kitty.conf`
```
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B YOUR_POWERLINE_PATCHED_FONT_NAME
```

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font

if your font is listed by the fc-list command at that link it will work
with kitty. And note that you should not use a patched font, instead
just install the powerline font and either kitty will pick it up
automatically, or you can use the symbol_map directive in kitty.conf to
tell it to use the powerline font for the appropriate unicode code
points.
