### ISSUE TITLE
Issue with graphics protocol

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#1882]
Sadly i dont have minimal example, but it is reproducible consistently on my machine.

This can be use with either ranger or [hunter](https://github.com/rabite0/hunter), since they both implement image previews using kitty.

To reproduce you must hover over the image and quit while its displaying the image preview. If you launch any program that is using alternate screen, such as ranger/hunter itself, in place where the was an image will be black rectangle. But if kitty is launched with `--debug-gl`, the terminal will crash with following error `OpenGL error: This operation is invalid (GL_INVALID_OPERATION) (calling function: glBindTexture)`
I have amd card and mesa 19.1.3.

**Comment by kovidgoyal** [comment]
I dont use either of those two programs, how does one get ranger to display image previews in kitty? I tried opening a directory of images and moving the cursor over image files but got no previews. Is there some config required?

**Comment by kovidgoyal** [comment]
Figured out how to get ranger to display images, but I cannot replicate your sympotoms steps I tried:

1) Start ranger as: ranger logo (where logo is the logo directory in the kitty source code)
2) Select kitty.png to display the kitty icon in ranger
3) Press q to quit

I see neither the opengl error with --debug-gl nor a black rectangle

**Comment by SolitudeSF** [comment]
did you open the ranger or other program using alternative screen afterwards?

i assume you're using intel integrated graphics. would be nice if someone with amd card confirmed that its the driver issue.

**Comment by kovidgoyal** [comment]
Yes I opened ranger again after quitting. And I tried it on both Intel and Radeon HD 7770/8760 using opens ource drivers.

**Comment by kovidgoyal** [comment]
I switched to a radeon 540X with amdgpu drivers and cant reproduce there either. Closig since I cannot reproduce and no one else has reported a similar issue either.

**Comment by SolitudeSF** [comment]
i cant reproduce it now either. even tho i had it just few days ago.

**Comment by SolitudeSF** [comment]
damn, i cant reproduce it with ranger, but can with hunter, but since no one but me has this, i guess this one is remains a mistery.
