### ISSUE TITLE
Let monotonic() return uint64_t instead of double?

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1885]
Can I make `monotonic()` return the number of nanoseconds since the start in an `uint64_t` instead of the number of seconds in a `double`? That would ensure a constant nanosecond accuracy for the next 580 years or so. The `double` will slowly get less accurate over time although that may not be a problem in practice. But I'd like to make sure that it never becomes a problem.

**Comment by kovidgoyal** [comment]
monotonic subtracts the start time for the returned time anyway. Simply have it do that subtraction in the numerator before dividing, then there are no dimishing accuracy issues with using a a double.

**Comment by kovidgoyal** [comment]
Actually since monotonic() is not too widely used, it might make sense to change it to use nanosecs rather than secs, but I would need to see how invasive the patch is

**Comment by Luflosi** [comment]
I changed `monotonic()` in `kitty/data-types.c` and got it to compile after changing less than 30 lines. I need to change a bit more to make it actually work again though. But I don't think this patch will be too invasive.
Should I introduce a new datatype or hardcode the datatype to `uint64_t`?

**Comment by kovidgoyal** [comment]
Probably best to have a monotonic_type since in the future we may get
better than nansecond resolution and having a dedicated type will make
it easier to track down and change.
