### ISSUE TITLE
Why isn't Fixedsys Excelsior with ligatures supported?

### ISSUE THREAD

**Issue by sorenbug** [kovidgoyal/kitty#1887]
https://github.com/kika/fixedsys

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html

**Comment by Luflosi** [comment]
Specifically https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font.
Also see https://github.com/kika/fixedsys/issues/1. It seems that Konsole also does not support non-monospace fonts but the owner of the repo with the font apparently does not know how to fix that. @kovidgoyal if you know how and have nothing better to do, you may want to help him.

**Comment by kovidgoyal** [comment]
I think it's also a bitmapped font which wont work well with kitty anyway.

**Comment by Luflosi** [comment]
From the fonts README.md:
> Darien simulated the bitmap with TrueType outlines by building the font from 10x10 squares ("pixels") and then joining the squares together. As such, this font only works as intended in only one size and usually with antialiasing switched off. The size is 16px or 12pt.

So I think it's not a bitmapped font.

**Comment by kovidgoyal** [comment]
The point is not so much how it is implemented, but that kitty tends to
need freely resizable glyphs, because when a glyph overflows the cell,
kitty scales it down to fit. And ofcourse it allows free dynamic font
resizing.

**Comment by Luflosi** [comment]
Everybody using this font needs to decide for himself/herself if it works well enough. Of course this font wouldn't work properly at the wrong font size or when kitty resizes a glyph. Living with these limitations is a tradeoff some people are willing to make.

**Comment by kovidgoyal** [comment]
The problem with that noble sentiment is that using such a font means kitty wont work well, and I will have to deal with the consequent bug reports.

**Comment by Luflosi** [comment]
Yeah, that's true.
