### ISSUE TITLE
"Compressed" horizontal lines

### ISSUE THREAD

**Issue by Sheridan** [kovidgoyal/kitty#1889]
mc render right, but kernel `make nconfig` render wrong :(

![image](https://user-images.githubusercontent.com/728591/62411567-8ee16400-b5fd-11e9-9508-3fd6c94a1192.png)

My config:
```
font_family      Ubuntu Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
adjust_column_width 1
font_size 9.5

term xterm-256color

cursor_shape beam
cursor_blink_interval      0.7
cursor_stop_blinking_after 600.0
focus_follows_mouse yes

scrollback_lines 8196

copy_on_select yes

tab_bar_edge top
tab_fade 0.7 0.8 0.9 1

background_opacity         0.9
dynamic_background_opacity yes

x11_hide_window_decorations yes

#include ./base16-kitty/colors/base16-google-dark-256.conf
include ./base16-kitty/colors/base16-material-darker-256.conf

cursor #22BE00
```

**Comment by kovidgoyal** [comment]
Run kitty with --dump-bytes and do the minimum needed to recreate the
issue and post the dump file.

**Comment by egmontkob** [comment]
Looks like Kitty doesn't support REP, whereas the said `xterm-256color` describes it as being available and thus ncurses uses it.

**Comment by kovidgoyal** [comment]
Oh right, didn't notice the term xterm-256color. Thanks @egmontkob

@Sheridan Dont change the value of term, it will break things.
