### ISSUE TITLE
Wrong render of some unicode symbols

### ISSUE THREAD

**Issue by webhive** [kovidgoyal/kitty#1890]
I am using rounded corners symbols in my terminal. It work fine with Gnome Terminal, but kitty render these symbols (U+256D, U+2570) wrong way - for some reasons it is not rounded

Here is a screenshoot 

![kitty-screen-1](https://user-images.githubusercontent.com/1154997/62412215-d8cf4780-b607-11e9-9cc9-7d057b0caa1a.png)

Initially thought it was a font issue - but it is not depends on font. And Gnome Terminal used exactly the same font and everything displayed well.

**Comment by kovidgoyal** [comment]
It's not a font issue. Box drawing characters are not drawn with fonts otherwise they dont always line up correctly. I simply haven't bothered with implementing rounded corners, in the custom drawing code. Patches are welcome, relevant code is in box_drawing.py search for TODO

**Comment by webhive** [comment]
Done some quick attempt using midpoint algorithm
It is harder work when initially expected :) Definitely need to implement somehow a thinkness and antialiasing. 

![image](https://user-images.githubusercontent.com/1154997/62417436-a64d3b00-b657-11e9-9e03-06698d96e6df.png)

**Comment by Luflosi** [comment]
https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm may help. Also see 3fa7007e910242c4fb3f691acae74b887c26a718.

**Comment by kovidgoyal** [comment]
Yeah that's why I have not bothered implementing it. There are examples
of doing curves and anti-aliasing in that file. For instance, the D()
function or fill_region()

**Comment by webhive** [comment]
Ha! Added thikness.

Small font 
![image](https://user-images.githubusercontent.com/1154997/62424014-78a4d800-b6d1-11e9-80a8-4097ce27fbb3.png)
![image](https://user-images.githubusercontent.com/1154997/62424040-d76a5180-b6d1-11e9-8722-566b211402ec.png)
Large font
![image](https://user-images.githubusercontent.com/1154997/62424026-97a36a00-b6d1-11e9-9277-ae0f8732cde7.png)

So the only thing to do is antialiasing. Damn - I never had so fun for a long time :)

**Comment by webhive** [comment]
Hmm - applied Wu AA

Top right is mine, another one is GnomeTermnal
![image](https://user-images.githubusercontent.com/1154997/62428522-7bbcba00-b70b-11e9-8382-03f15031296d.png)

Close look

![image](https://user-images.githubusercontent.com/1154997/62428540-a149c380-b70b-11e9-9049-439a0327b11c.png)

It is definitely antialiased, but looks ugly. Gnome Terminal has better AA while it is way more simple. Any suggestions?

**Comment by kovidgoyal** [comment]
It's been a while since I did any anti-aliasing, but as I recall using
the various theoretical methods was overkill/didn't work well. Just a
simple y-axis blur seemed to work best, search the file for anit-alias
to see the implementation I used.

**Comment by Luflosi** [comment]
@webhive maybe you didn't implement the algorithm correctly? https://create.stephan-brumme.com/antialiased-circle/ has some sample code for using Wu's algorithm to draw a circle. But I'm not sure how to make the line thicker than one pixel. Maybe the approach @kovidgoyal mentioned is better. Or maybe you find a completely different algorithm.

**Comment by webhive** [comment]
@Luflosi Funny - used exactly this article. Yea - will try @kovidgoyal approach
