### ISSUE TITLE
Keyboard shortcut to navigate to specific tab

### ISSUE THREAD

**Issue by asgeo1** [kovidgoyal/kitty#1891]
Thanks for making Kitty.  Just trying it out for the first time, I'm coming from iTerm2 on OSX

Having a small issue with tab navigation.  I have tried searching and looking for the answer, but can't seem to find it, so apologies if this is actually documented somewhere.

Anyway, in iTerm2 I use Cmd+_number_ i.e. Cmd+3 to navigate to tab number 3.  So you can quickly get to any tab by using Cmd+_number_

That mapping also works in a number of other tabbed programs, such as Chrome.

Anyway, I have that ingrained into my muscle-memory, and hoping to setup shortcuts for the same thing with Kitty.

Is it possible?

**Comment by Luflosi** [comment]
Put
```
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
```
into your `kitty.conf`. You may also use `kitty_mod` instead of `cmd` if you have `kitty_mod cmd` in your `kitty.conf`.
See just below https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Set%20tab%20title.
@kovidgoyal do you think adding those by default is a good idea?

**Comment by kovidgoyal** [comment]
No, kitty_mod+number is already used for going to specific windows.

**Comment by asgeo1** [comment]
Thanks @Luflosi that worked a treat 👍

**Comment by yurenchen000** [comment]
I use Alt+1,2,3.. to switch tab:

<kbd>ctrl+shift+f2</kbd> edit conf
```
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
```
`:w` save

<kbd>ctrl+shift+f5</kbd> reload conf
