### ISSUE TITLE
Ctrl+C does not terminate a process

### ISSUE THREAD

**Issue by gianarb** [kovidgoyal/kitty#1893]
Hello

I am having trouble understanding if this is an issue in some way related to kitty or not. So I am sorry if this is not in the right place. If so, feel free to close it.

Recently I am experiencing issues terminating processes using `Ctrl+C` because it does not terminate them. The easier test is with the sleep command:

```bash
$ sleep 5
sleep 5
^C^C^C^C
```

This is what happens when I try to terminate the `sleep` command, but it does not stop. I have the same problem with almost all the programs I run. I say "almost" because something works, but so little that I can not recall which one (I will update this issue when I will find a reproducible one that works).

I tried with `gnome-terminal` and I do not experience this issue. I can terminate all the programs. (I can't get the information about when/where it stopped to work even)

Here all the versions of the software I think can be useful to have and my kitty configuration

```bash
$ kitty -v
kitty 0.14.2 created by Kovid Goyal

$ uname -a
Linux gianarb 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux

$ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
cat ~/.config/kitty/kitty.conf 
enable_audio_bell no
// term xterm-256color

foreground            white
background            black
title_fg              black
title_bg              #EEEEEE
margin_bg             #fafbfc
margin_fg             #aaaaaa
removed_bg            #ffeef0
highlight_removed_bg  #fdb8c0
removed_margin_bg     #ffdce0
added_bg              #e6ffed
highlight_added_bg    #acf2bd
added_margin_bg       #cdffd8
filler_bg             #fafbfc
hunk_margin_bg        #dbedff
hunk_bg               #f1f8ff
```

**Comment by kovidgoyal** [comment]
I cannot reproduce this with the current version of kitty which is
0.14.3, steps I tried:

1) Run kitty --config NONE bash
2) sleep 5s
3) Press ctrl+C sleep is terminated
