### ISSUE TITLE
Graphical artifacts (black box) in top & bottom left corners (Ubuntu LTS 18.04)

### ISSUE THREAD

**Issue by peteygao** [kovidgoyal/kitty#1894]
This just started recently, my Ubuntu version & graphics info:
```bash
$ uname -a
Linux 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lshw -c video
$ sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:27 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:5000(size=64) memory:c0000-dffff
```

I'm on x11 and not Wayland:
```bash
$ loginctl show-session 2 -p Type           
Type=x11
```

Happy to provide any additional details about my machine to help repro. Just to repeat: kitty was fine until a few days (weeks?) ago. I updated to latest version (0.14.3) with no avail.

Screenshot of the problem (notice the top left and bottom left [top & bottom screenshots respectively] corners with characters are covered by black artifact):
![Screenshot from 2019-08-05 17-23-47](https://user-images.githubusercontent.com/2184561/62502906-b58ece80-b7a6-11e9-8f3a-520ea48b0ed2.png)
![Screenshot from 2019-08-05 17-23-57](https://user-images.githubusercontent.com/2184561/62502907-b58ece80-b7a6-11e9-91b4-d8c777ba32c2.png)

**Comment by kovidgoyal** [comment]
dup of #1484
