### ISSUE TITLE
Cannot launch kitty from i3 or rofi

### ISSUE THREAD

**Issue by gvelchuru** [kovidgoyal/kitty#1896]
Seems similar to @347 but I'm unsure how to debug

Kitty version 0.14.3
I cannot launch kitty from i3 or rofi, but i can launch from terminal

**Comment by kovidgoyal** [comment]
You need to make sure the kitty is in the system-wide PATH. Inside a
terminal PATH gets change by your shells rc files.

**Comment by gvelchuru** [comment]
I tried executing /usr/bin/kitty instead, but that didn't work either, and in rofi I don't get the error "no such file or directory" which I normally do when executing something not in the path. In fact, I don't get any error at all

**Comment by kovidgoyal** [comment]
You likely have multiple kitties installed. Uninstall your distro version
and any others you have and install the official binaries, as described
here: https://sw.kovidgoyal.net/kitty/binary.html

**Comment by gvelchuru** [comment]
I tried that, still the same problem -- in i3 I cannot exec ~/.local/kitty.app/bin/kitty either

**Comment by kovidgoyal** [comment]
Then you need to figure out where i3's logs go and see what error
message is logged when launching.
