### ISSUE TITLE
Inline Image Support?

### ISSUE THREAD

**Issue by scopatz** [kovidgoyal/kitty#19]
Hi! Are there any plans or goals to support inline images like in iTerm2? This is a feature I have been looking for in a terminal that works on linux for a couple of years.

**Comment by kovidgoyal** [comment]
Not something I care about personally, but patches are welcome! IIRC this is done via "sixels" and there is a libsixel one can look into for supporting them.

**Comment by kovidgoyal** [comment]
Superseded by #33
