### ISSUE TITLE
Named key PLUS

### ISSUE THREAD

**Issue by zartstrom** [kovidgoyal/kitty#190]
I would like to use `ctrl+shift+plus` as shortcut for increasing font size.
But this is obviously not supported:
```
Shortcut: ctrl+shift+plus    increase_font_size has an unknown key, ignoring
```
and `ctrl+shift++` gives an error.
In `kitty/config.py` there is a dict `named_key`. Would it be feasible to add a mapping PLUS -> '+'?

I guess there is a reason to why it's not in there .. if it's document, I'm sorry, I didn't find it yet.

**Comment by kovidgoyal** [comment]
+ is not a key on most keyboards (leaving aside the numeric keyboard). The default shortcut is ctrl+shift+= 

The equal key typically has + as its shifted alternative. 

As for the numeric keyboard support for that requires https://github.com/glfw/glfw/issues/1140

**Comment by zartstrom** [comment]
Thanks for the super fast answer! I see :)
