### ISSUE TITLE
Kitty creates broken theme.conf

### ISSUE THREAD

**Issue by TeslaNguyen** [kovidgoyal/kitty#1903]
Hi!

`ln -s ./kitty-themes/themes/Floraverse.conf ~/.config/kitty/theme.conf` or in my case
`ln -s ./kitty-themes/themes/Solarized_Dark_-_Patched.conf ~/.config/kitty/theme.conf` creates a broken theme.conf

What can I do?

Cheers

**Comment by Luflosi** [comment]
You reported the same issue in https://github.com/dexpota/kitty-themes/issues/14 already. Please don't report an issue in multiple places as this creates more work for people.
This is not an issue in kitty so this issue here should be closed. I'll try to help you in the other issue.

**Comment by TeslaNguyen** [comment]
Sorry, my bad and thank you!
