### ISSUE TITLE
base16/xresource colours not kept during hints and history

### ISSUE THREAD

**Issue by BlueDrink9** [kovidgoyal/kitty#1906]
I use base16-shell to change kitty's colours from time to time (usually in the evenings). Since kitty can't source a new colours.conf while running (AFAIK), this is the only option.

When opening the scrollback pager, or opening hints, the colours return to those specified in the config file.

Note, they do return to base16's colours after closing the pager/hinting.

**Comment by SolitudeSF** [comment]
it can using remote protocol. `kitty @ set-colors`

**Comment by BlueDrink9** [comment]
Woah, neat. Still means base16-shell has significantly reduced usefulness, but I'm pleased about this option!

**Comment by BlueDrink9** [comment]
Yes, this has solved my use-case most of the time, I'll just stick to using actual kitty schemes as much as possible. On that note, a central repo for schemes would be excellent...

However, the problematic behaviour remains, so I'll leave it up to the maintainer as to whether to close the issue.

**Comment by Luflosi** [comment]
There is a central repo for themes, see https://github.com/dexpota/kitty-themes. It even has instructions on how to load the themes without restarting kitty.
<br>

> When opening the scrollback pager, or opening hints, the colours return to those specified in the config file.

@kovidgoyal is there a way to change this?
