### ISSUE TITLE
vim and scroll up

### ISSUE THREAD

**Issue by mschwartz** [kovidgoyal/kitty#1907]
Whether I run vim in tmux or without, kitty misbehaves.

Instead of the mouse (trackpad/touchpad) gestures scrolling the vim editor up and down, it scrolls kitty's history up and down.

What I see is the top of vim scrolled down and all the commands and output from before I ran vim above.

I use termite as my main terminal under i3, and it works as I expect.

I really want to use kitty instead!

Thanks for making this.

**Comment by kovidgoyal** [comment]
Add 

set mouse=a

in your .vimrc

**Comment by mschwartz** [comment]
For anyone who comes across this issue, TERM needs to be set to xterm-kitty and all is good.

Added this to my zshrc, too:

```
[ ! -z "$KITTY_WINDOW_ID" ] && export TERM=xterm-kitty
```

**Comment by mschwartz** [comment]
Thanks for the answer.  Kitty is up there with the best of the terminal programs I've tried.

(Been doing unix/linux for 30+ years)
