### ISSUE TITLE
Kitty python framework doc

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [kovidgoyal/kitty#1908]
I've struggled to find any resource to make a simple kitten python file and finally abandon the idea.
So my issue is that their is almost no documentation for the kitten framework, and it's a shame. The project is amazing and people would be really happy to make kittens if a real nice documentation (like a readthedocs page or a github wiki) would be provided.

**Comment by trygveaa** [comment]
Have you read this? https://sw.kovidgoyal.net/kitty/kittens/custom.html

**Comment by kovidgoyal** [comment]
As @trygveaa said the kittens framework is already documented. And there are links to kittens kitty users have made. If something is unclear, feel free to ask.
