### ISSUE TITLE
Hints kitty's hash type misses

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#1911]
The hints kitten is great in all its variations, I was surprised to see it miss the `got: sha256:0cpqrf...` hash though. The all-zero hash is hinted without problem.

Part of the contents of my terminal at the time:
```
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:0cpqrf3939hcvwg7sd8055ghc8x964ilimlri16czzx188a9jx9v
```

Note that just the hash part of `got: ...` is enough to reproduce the problem.

**Comment by kovidgoyal** [comment]
That's not a valid hash, it has the letters z,x and v in it. Hashes are
typical represented in hexadecimal notation [0-9a-f] which is what the
kitten recognizes.

**Comment by toonn** [comment]
Oh, yup, it's a base32 representation. I guess that can't be generalized, so I've had to resort to `kitty +kitten hints --hints-offset=0 --type regex --regex '(?m)\b([0-9a-f]{7,128}|[0-9A-F]{7,128}|[0-9a-df-np-sv-z]{52})\b' --program -`.

**Comment by Luflosi** [comment]
@kovidgoyal I think it would be a good idea to be able to specify which bases should be matched via a config option.

**Comment by toonn** [comment]
@Luflosi many of the base32/64 encodings allow for different character sets though. Including the RFC standard sets would be nice but wouldn't have helped me here.

**Comment by kovidgoyal** [comment]
Indeed, there is too much variation to make this an option. Since the
kitten supports regular expressions, any user can simply choose whatever
character sets they need.
