### ISSUE TITLE
too many pre-rendered sprites

### ISSUE THREAD

**Issue by dimaqq** [kovidgoyal/kitty#1913]
If I try to use a fancy font, `kitty` fails to start with:
```
… ~> kitty
[231 14:27:10.912155] Failed to set locale with LANG: en_JP.UTF-8
[231 14:27:11.441011] Too many pre-rendered sprites for your GPU or the font size is too large
```

`kitty 0.14.3`, macOS with all the updates.

**Comment by kovidgoyal** [comment]
kitty supports only monospace fonts as its main font. Wht font are you
trying to use?

**Comment by dimaqq** [comment]
I tried a hacked up version of "Operator Mono".
I suppose I'll have to verify if all the glyphs are indeed the same size... 🤔

**Comment by kovidgoyal** [comment]
You dont need to use hacked up fonts. Use symbol_map in kitty.conf
instead to load special symbols from a dedicated font.
