### ISSUE TITLE
Creating .ktx file

### ISSUE THREAD

**Issue by bajinabass** [kovidgoyal/kitty#1914]
Hello,

I'm hoping someone can refresh my memory on how to create a custom .ktx file.  I did one a year or so ago and I need to create a new one and I cannot figure out how.  Thanks-

**Comment by kovidgoyal** [comment]
I have no idea what a .ktx file is and kitty uses no such thing.

**Comment by bajinabass** [comment]
It's a KiTTY Connection Manager file and Kitty does use such a thing as I have been using it for over a year.  Thanks-

**Comment by SolitudeSF** [comment]
`kitty` not a fork of `KiTTY`. thats absolutely separate project that unfortunately shares the name.
