### ISSUE TITLE
Conditional padding or 'moving the prompt'

### ISSUE THREAD

**Issue by Ginner** [kovidgoyal/kitty#1915]
Hi Kovid. 

First off thank you for your work!

I like to have some padding or margin in the terminal (otherwise I think the prompt is too close to the edge, both top/bottom and left/right), however I don't want it in Vim or some other terminal applications. My Vim (nvim) runs different colorschemes based on the file-type, and the padding from Kitty, which surrounds the editor, makes this look a little odd. 

Is there a way to remove the padding conditionally? Or achieve the desired functionality in another way?

**Comment by Luflosi** [comment]
Would changing the background color of the padding to the background color in vim solve your problem? This is probably already possible with the remote control protocol (https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-set-colors) and some scripting. But maybe it is not too hard to implement this functionality in kitty. Do you feel comfortable compiling kitty from source? A couple months ago I implemented something that might do what you want, not 100% sure though, I'll have to check.

**Comment by kovidgoyal** [comment]
The padding in kitty automatically follows the default background color
in the active window. Change your vim color scheme switcher to actually set the
terminal default foreground/background colors and you will be fine.

**Comment by Ginner** [comment]
I think changing the terminal default colours is a good option, thank you both. 

However I think I'd look better if I could have padding in there terminal and no padding when in the editor. I'm looking into whether this is possible with the kitty remote protocol. Here I'd have an alias for `vim` which sends a command to kitty to set the padding to 0. Is this possible within the same window? I don't see the option within the protocols in https://sw.kovidgoyal.net/kitty/rc_protocol.html#resize-window.

**Comment by kovidgoyal** [comment]
padding is not per window, it applies to all kitty windows. And no there
is currently no remote control for it, but it should be possible to add,
patches welcome. Look in cmds.py for defining the remote control command
and grep the source for padding to see whre all it will need to be
updated.

**Comment by maxdevjs** [comment]
@Ginner did you solve it?

Nowadays, something like:

```yaml
vim.api.nvim_command([[ autocmd VimLeave * :silent !kitty @ set-spacing padding=20 margin=10 ]])
```

works for me (nvim).

> Note: alternative is to use `vim.cmd`

**Comment by Ginner** [comment]
Hi @maxdevjs 

Sorry for the late reply. 
No, I have the padding in both terminal and editor. I don't know if I've just grown accustomed to it, but I think it's fine now :)

**Comment by HakonHarnes** [comment]
Here's an alternate solution that worked better for me:

```
#!/bin/sh

kitty @ set-spacing padding=0
nvim $*
kitty @ set-spacing padding=default
```

**Comment by smabbasht** [comment]
@HakonHarnes Thanks for the solution. For me, when I am executing this script from a `tmux` session, it is giving me 
> "Error i/o timeout"
However, the script runs fine when executed outside the tmux session. Maybe tmux sessions aren't allowed i/o permission. Is there any way around? Since many of us use tmux for everything...

**Comment by mistricky** [comment]
As @maxdevjs mentioned the solution, there is one other thing worth noting here: if you want a remote control the Kitty terminal padding from Vim, there may be an error:
```
Failed to open controlling terminal: /dev/tty
```

I turned on `listen_on` item in my kitty.conf solved this problem:
```
listen_on unix:/tmp/mykitty
```

**Comment by kitesi** [comment]
If you switch between terminals, having a check for kitty might be useful:

```lua
vim.cmd([[
augroup kitty_mp
    autocmd!
    au VimLeave * if !empty($KITTY_WINDOW_ID) | :silent !kitty @ set-spacing padding=20 margin=10
    au VimEnter * if !empty($KITTY_WINDOW_ID) | :silent !kitty @ set-spacing padding=0 margin=0
augroup END
]])
```

**Comment by Axhyy** [comment]
If you use dashboard then you'll need to add "BufEnter"
```lua
vim.cmd([[
augroup kitty_mp
    autocmd!
    au VimLeave * if !empty($KITTY_WINDOW_ID) | :silent !kitty @ set-spacing padding=20 margin=0
    au VimEnter * if !empty($KITTY_WINDOW_ID) | :silent !kitty @ set-spacing padding=0 margin=0
    au BufEnter * if !empty($KITTY_WINDOW_ID) | :silent !kitty @ set-spacing padding=0 margin=0
augroup END
]])
```

**Comment by Raideeen** [comment]
> [@HakonHarnes](https://github.com/HakonHarnes) Thanks for the solution. Whenever I execute this script from a `tmux` session, it is giving me
> 
> > Error: i/o timeout
> 
> However, the script runs fine when executed outside the tmux session. Maybe tmux sessions aren't allowed i/o permission. Is there any way around? Am I missing something in my tmux conf? Since many of us use tmux for everything so it is essential... These are my [.tmux.conf](https://github.com/smabbasht/Dotfiles/blob/personal/.tmux.conf) & [kitty.conf](https://github.com/smabbasht/Dotfiles/blob/master/kitty/kitty.conf)

I've developed a solution to manage window padding in Kitty terminal emulator when using Neovim within Tmux sessions. This approach works even with multiple Kitty sessions open simultaneously.

The main idea is to leverage the `$KITTY_LISTEN_ON` variable created by kitty to apply window padding to the correct Kitty session. This works by communicating through a socket, even when multiple sessions are active. Each Kitty session creates a socket.

## Prerequisites
1. Add these settings to `~/.config/kitty.conf`:
```conf
allow_remote_control yes
listen_on unix:/tmp/mykitty
```
This settings will allow to send commands to our kitty terminal emulators [from scripts](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.allow_remote_control) through a socket created in `/tmp/mykitty-[PID]`.
2. Add this line to `~/.tmux.conf`:
```conf
set -g update-environment `KITTY_LISTEN_ON`
```

## First Implementation

Create a script called `kitty_nvim.sh`:

```bash
#!/usr/bin/env bash

# Get Kitty socket
KITTY_SOCKET=$(echo $KITTY_LISTEN_ON)

# We can control the current kitty terminal using socket 
# and using "kitten" : https://sw.kovidgoyal.net/kitty/remote-control/#remote-control-via-a-socket
if [ -n "$KITTY_SOCKET" ]; then
    kitten @ --to $KITTY_SOCKET set-spacing padding=0
fi

nvim $*

if [ -n "$KITTY_SOCKET" ]; then
    kitten @ --to $KITTY_SOCKET set-spacing padding=default
fi
```

Then:
1. Make it executable: `chmod +x path/to/the/script/kitty_nvim.sh`
2. Add to your shell config (`~/.zshrc` or `~/.bashrc` or whatever...): `alias nvim=path/to/the/script/kitty_nvim.sh`  
3. Source your confifg: `source ~/.zshrc`

However, as you can see in the following gif, when using Tmux panes and both panes are running Neovim, exiting one pane will reset the padding for all panes. Although, it is nice to see that it doesn't reset the window panning for all kitty sessions! 😄 

![Kitty window padding with tmux setup - first case](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDFyczRiMjRvcHFvOWIxZm52cWR6ZHEzYXNqZmkwNTNtMHVsMjg2byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/YB9NJJ6YoPLU3Rahkv/giphy.gif)

## Second Implementation (Multi-Pane Support)

To better handle multiple Neovim instances, we can create a script that uses a lock file with a count to only reset the window padding if there are no Neovim sessions running. 

```bash
#!/usr/bin/env bash

# Use the Kitty socket name to keep it unique per Kitty window
sock_basename="$(basename "${KITTY_LISTEN_ON#unix:}" 2>/dev/null)"
count_file="/tmp/kitty_padding_count_${sock_basename}"

# We'll also create a lock file so multiple parallel nvim starts
# won't clobber each other's reference count.
lock_file="/tmp/kitty_padding_count_${sock_basename}.lock"

increase_padding_refcount() {
  exec 9>"$lock_file"
  flock 9            # Acquire exclusive lock

  # Read current count (0 if no file)
  if [[ -f "$count_file" ]]; then
    read -r count < "$count_file"
  else
    count=0
  fi

  # If count=0 => we're the *first* nvim in this Kitty window
  if [[ "$count" -eq 0 ]]; then
    kitty @ --to "$KITTY_LISTEN_ON" set-spacing padding=0
  fi

  # Increase count
  count=$((count+1))
  echo "$count" > "$count_file"

  flock -u 9         # Release lock
}

decrease_padding_refcount() {
  exec 9>"$lock_file"
  flock 9            # Acquire exclusive lock

  # Read current count (assume 1 if no file for safety)
  if [[ -f "$count_file" ]]; then
    read -r count < "$count_file"
  else
    count=1
  fi

  # Decrease count
  count=$((count-1))
  echo "$count" > "$count_file"

  # If count=0 => no more nvim sessions => restore
  if [[ "$count" -eq 0 ]]; then
    kitty @ --to "$KITTY_LISTEN_ON" set-spacing padding=default
  fi

  flock -u 9         # Release lock
}

if [[ -n "$KITTY_LISTEN_ON" ]]; then
  increase_padding_refcount
fi

nvim "$@"

if [[ -n "$KITTY_LISTEN_ON" ]]; then
  decrease_padding_refcount
fi
```

![Kitty window padding with tmux setup - second usage](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnRuaHZ1d2lxdDNvZTZnY3QwdGdrOXdqaWR4eW1jcGJqMGpqb2luYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gas5RmtvuNtQ9gACFU/giphy.gif)

**Comment by LeonMusCoden** [comment]
Thank you @Raideeen! This is working nicely. I've noticed that the second implementation doesn't recognize nvim in more than one tmux session. Is there a fix for that?
