### ISSUE TITLE
Working towards migrating to kitty

### ISSUE THREAD

**Issue by aste4** [kovidgoyal/kitty#1917]
I am looking to switch to using kitty on both Mac OS and later Linux. The current roadblock is fonts.

Coming from iTerm, I can't migrate correctly because the fonts look off. I am using Hack font. Font size 11 on kitty is not the same as Font 11 on iterm.  From what I found looking around past issues, (https://github.com/kovidgoyal/kitty/issues/109) its an DPI issue. But something is off because I don't think the DPI is detected correctly. On an external monitor it seems to be 72 - when in reality its ~110. On the mac retina with no monitor connected it is also incorrect. 

I played around trying to see if I can first hardcode the DPI in somewhere (`dpi_for_os_window_id`) so I can get the same  font proportions but without success.

Any suggestions?

**Comment by kovidgoyal** [comment]
Effective font size is simply dpi and pt size, if you cant adjust one,
adjust the other. And dpi is never taken as exact value, on macOS it is
calculated as contentScale * 72

**Comment by aste4** [comment]
Where in the code should I adjust the other value? What number should I tweak to see if it is even possible to recreate the same look and feel in kitty?

What is the significance of 72? I see it across the code. Why isn't it a constant value that could be modified?

**Comment by kovidgoyal** [comment]
Adjust the font size in kitty.conf it accept arbitrary floating point
numbers.

And 72 is the DPI Apple uses. Just like on Linux it is 96

**Comment by aste4** [comment]
I already tried adjusting the font size with 0.5 increments but either width or the height was a bit off. I'll try smaller increments. 

With Linux, I can actually get it to be **identical** between gnome-terminal and kitty. 

I am not too hopeful with Mac OS but I'll try to report back

**Comment by kovidgoyal** [comment]
Umm why do you care about it being identical to a terminal you no longer
use? And you can adjust the cell width/height by individual pixels using
the adjust_* settings in kitty.conf

**Comment by aste4** [comment]
I use both on a semi-regular basis which is why it is important to me. And I'm looking to make a consistent environment regardless of the platform. When you stick with a font long enough, it's easy to notice differences. Even if I switch to kitty on Mac OS, it should be visually identical since I've been using iterm with a particular font with a particular size for so long

Yeah, I've also tried playing with adjust_*. I'll continue tweaking.

**Comment by aste4** [comment]
Like in the issue I linked above, it is easier if font 9 in on terminal A visually corresponds to the same font of size 9 in terminal B

**Comment by Luflosi** [comment]
See if https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.macos_thicken_font makes the font look better for you. Start by setting the value to 0.5 or 0.75.
