### ISSUE TITLE
Mapping Special Keys (Ctrl+ö)

### ISSUE THREAD

**Issue by bschnitz** [kovidgoyal/kitty#1919]
Some mappings seem not to be detected by kitty.

How to reproduce:
1. put `map ctrl+odiaeresis paste_from_clipboard` (or `map ctrl+0xf6 paste_from_clipboard`) into the kitty.conf .
2. open kitty, copy something into clipboard and try to paste using ctrl+ö

Expected result:
The contents from clipboard appear.

Actual result:
; is written to the terminal

**Comment by Luflosi** [comment]
I tried it with `map ctrl+ö paste_from_clipboard` and had the same problem. When starting kitty, it prints the following error message:
```
Shortcut: ctrl+ö has unknown key, ignoring
```
`0xf6` is not the same key as `ö` and kitty does not print any error message.

PS: Also using a german keyboard?

**Comment by bschnitz** [comment]
0xf6 is the output of  `kitty --debug-keyboard` for the key-press event of ö. I think You can't use `map ctrl+ö paste_from_clipboard` for mapping inside kitty.conf. The manual states:

> For a list of key names, see: GLFW keys. The name to use is the part after the GLFW_KEY_ prefix. For a list of modifier names, see: GLFW mods. On Linux you can also use XKB key names to bind keys that are not supported by GLFW. See XKB keys for a list of key names. The name to use is the part after the XKB_KEY_ prefix. Note that you should only use an XKB key name for keys that are not present in the list of GLFW keys. Finally, you can use raw system key codes to map keys. To see the system key code for a key, start kitty with the kitty --debug-keyboard option. Then kitty will output some debug text for every key event. In that text look for native_code the value of that becomes the key name in the shortcut.

There are links in the manual. I couldn't copy them. I suggest to look into it directly:
https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts

**Comment by kovidgoyal** [comment]
You cannot map arbitrary key names, since these tend to be platform dependent. Use the native code/name to map it instead which you can get from --debug-keyboard. Sadly I dont have a german keyboard, so I cant test this, but the relevant code is in keys.py see the get_shortcut function

**Comment by bschnitz** [comment]
I did some research. And I think the problem is in check_if_special in keys.c . Here key is checked to be in the global key_map. However key is in this case the glfw key, which is maped to ';' for 'ctrl+ö'. I guess this check is incorrect, but I am not sure. I don't know, why it is done this way. It could also be key_map, which is wrong and should contain ';'. Or the initial glfw-map of 'ctrl+ö' to ';' is wrong. Anyways, for me it is sufficient to put the following in kitty.conf:
`
map ctrl+odiaeresis  paste_from_clipboard
map ctrl+;  paste_from_clipboard
`
Now if pressing 'ctrl+ö', all checks succeed and clipboard is inserted. Note however, that there is still a bug and that it isn't possible to map 'ctrl+;'. At least I didn't find a way to do that. So I will not close this issue.

**Comment by kovidgoyal** [comment]
If the key is getting mapped to semi-colon then there is no bug. As
noted in the docs, you can only use OS specific names/codes if there is
no corresponding GLFW key. In this case there is, namely ; 

So the code based mapping will not work. 

If the key cap display the diaresis char I dont know why it is getting
mapped to semi-colon, but that happens in a lower layer than kitty code.

**Comment by Luflosi** [comment]
@bschnitz you're also using macOS, right?

@kovidgoyal `cocoa_init.m` has a line `_glfw.ns.keycodes[0x29] = GLFW_KEY_SEMICOLON;` in it. When I press the <kbd>ö</kbd> key, the scan code is 0x29. So the mapping GLFW uses seems to only be valid for US keyboards. Do you see some way to fix this?
In a file with the name `Events.h` deep in the Xcode app I found (thanks to a Stackoverflow answer) an enum that maps `kVK_ANSI_Semicolon` to 0x29. Just above the enum definition is the following comment:
```h
/*
 *  Summary:
 *    Virtual keycodes
 *  
 *  Discussion:
 *    These constants are the virtual keycodes defined originally in
 *    Inside Mac Volume V, pg. V-191. They identify physical keys on a
 *    keyboard. Those constants with "ANSI" in the name are labeled
 *    according to the key position on an ANSI-standard US keyboard.
 *    For example, kVK_ANSI_A indicates the virtual keycode for the key
 *    with the letter 'A' in the US keyboard layout. Other keyboard
 *    layouts may have the 'A' key label on a different physical key;
 *    in this case, pressing 'A' will generate a different virtual
 *    keycode.
 */
```
Maybe this helps somehow.

**Comment by kovidgoyal** [comment]
Not sure, if Apple reuses scancodes for different physical keys, then I
dont know of a good way to support that in glfw. If there is some cocoa
API that maps scancodes based on current keyboard layout, it could be
used, but I dont know of one.

**Comment by Luflosi** [comment]
I found a way to get an NSString from a key code. The function correctly outputs `ö` for the key code `0x29`. Would that help? Should I make a WIP pull request with that function? It requires linking against Carbon.

**Comment by kovidgoyal** [comment]
Feel free to try, kitty already links against carbon for UCKeyTranslate

**Comment by bschnitz** [comment]
@Luflosi I tried your version, but with no success, whatever I put into the config, strg+ö will still output ';'. But anyways, thank You for the effort :D . Also I don't have a Mac, just an old Dell ;) .

**Comment by Luflosi** [comment]
My patch isn't functional currently, it only prints some information. I need to actually do something with that information to make my patch functional.
Hmm, I thought this was something specific to macOS. But it looks like this will need fixing both on macOS and on Linux.

**Comment by Luflosi** [comment]
@bschnitz can you try it again please? It works on macOS but I haven't tested it on Linux.

**Comment by Luflosi** [comment]
I added more keys and broke something, I'll let you know when it works again.

**Comment by Luflosi** [comment]
@bschnitz It compiles again, please test.

**Comment by bertin0** [comment]
So, currently there is no way to map `ctrl+;` or `ctrl+backspace` to an arbitrary escape sequence in kitty? Is that going to be the case for the forseeable future? Considering tmux doesn't support the kitty keyboard protocol (at least, not yet), there is currently no way to send these shortcuts in a way that could be received by tmux.

**Comment by kovidgoyal** [comment]
kitty -o 'map ctrl+; new_os_window' works fine on my macOS machine. If you have some non-US keybaord on your machine, use --debug-input to see exactly what you need to map. I dont know what tmux has to do with anything. If mapping to new_os_window works then mapping to send_text will also work and so you can have them send whatever arbitrary bytes you like.

**Comment by bertin0** [comment]
I am on linux, not mac. For me, `map ctrl+; send_text HELLO` or anything else still produces a plain `;`.

**Comment by kovidgoyal** [comment]
That's because you are using send_text incorrectly. Read its docs.
