### ISSUE TITLE
Feature request: gapless grid layout

### ISSUE THREAD

**Issue by lxcode** [kovidgoyal/kitty#192]
As far as I can understand the layout code, it's not obvious to me how to make the left/right/top/bottom stuff work like dwm's gaplessgrid or dvtm's grid layout, where some windows would end up straddling between left and right columns. I find a grid mode mode useful to have, particularly on large monitors. Any chance you could implement this?

References:

https://github.com/TaylanTatli/dwm/blob/master/gaplessgrid.c
https://github.com/martanne/dvtm/blob/master/grid.c
http://img.voidcn.com/vcimg/000/001/593/989_02c_6a8.png

**Comment by kovidgoyal** [comment]
Not sure what you mean by a gapless grid? What does windows straddling columns have to do with gaps? To me, gaps refers to the spacing between adjacent windows. Do you mean something else by it?


And wouldn't having straddling windows require some UI/keyboard shortcuts for designating the windows as straddling?

**Comment by lxcode** [comment]
Perhaps that term just confuses things — in dwm, the old "gridmode" always forced windows to be of equal sizes (resulting in significant gaps between windows), whereas "gapless" allows flexible window sizes. Essentially, when you start the first three terminals, things work the same as the "tall" layout, but then it goes like:

![grid1](https://user-images.githubusercontent.com/1959603/33329949-6da9fd20-d412-11e7-8192-b9ea6d5c750e.png)
![grid2](https://user-images.githubusercontent.com/1959603/33329951-6dc93956-d412-11e7-95d6-bd1d2a0ca628.png)
![grid3](https://user-images.githubusercontent.com/1959603/33329952-6de257e2-d412-11e7-978f-59e871312ec7.png)
![grid4](https://user-images.githubusercontent.com/1959603/33329953-6dfa7fac-d412-11e7-9ab4-a27a42f4583d.png)
![grid5](https://user-images.githubusercontent.com/1959603/33329954-6e18612a-d412-11e7-82a4-ba0b95e1deba.png)
![grid6](https://user-images.githubusercontent.com/1959603/33329955-6e71b22a-d412-11e7-8094-24587d74252e.png)
![grid7](https://user-images.githubusercontent.com/1959603/33329956-6e95f1bc-d412-11e7-9e5e-d2473ccd55d4.png)

**Comment by kovidgoyal** [comment]
So you mean a grid layout which, when the number of windows is not an exact multiple of the number of columns has windows of different sizes in different columns? That should be easy to implement by modifying the tall layout. Look in layout.py. Basically subclass Layout and implement do_layout() with your preferred grid algorithm. I imagine the algorithm would try to maximize averge window area. For n windows there are n layouts, with 2 to n columns. Calculate the average window area for each such layout and pick the one with the highest value. For each individual candidate layout, with k columns, there are two cases:

1) n % k == 0 -- balanced grid done
2) n % k != 0 in this case. In this case k - 1 columns have n // k windows and the last column has n % k windows

You can probably avoid the need to iterate over all layouts to calculate the one with the max avg area by using some more maths. i.e. it should be fairly simple to derive a closed form expression for it. Although given that n is a small number there is no real need to do it.

**Comment by kovidgoyal** [comment]
Actually, since these are gappless average area maximization is too simple, it will yiield the same result for all layouts, you'll need a more sophisticated computation of niceness.

**Comment by kovidgoyal** [comment]
Probabaly distance of average aspect ratio from 80x25 will do the trick.

**Comment by kovidgoyal** [comment]
And looking at the implementation in dwm it is even simpler, it does not bother with a fitness function at all, just hard codes the cases for n <= 5 and for the rest sets the number of columns to min(sqrt(n), n//2)

**Comment by kovidgoyal** [comment]
Implemented in the win branch.
