### ISSUE TITLE
Cursor rendering looks odd with adjusted line hight

### ISSUE THREAD

**Issue by mobius3** [kovidgoyal/kitty#193]
Currently the text rendered by kitty is displayed at the topmost position of the specified line height, which makes odd looking selected lines and cursor rendering.

![kitty](https://user-images.githubusercontent.com/945210/33342183-5b9fbb3c-d468-11e7-8cc2-d678460d7d96.png)
- Here you can't actually see but the beam occupies the whole line height and it looks off with the text rendered. This would be fixed by setting the cursor height to be the same size of the rendered font before applying line height adjustments.
- The highlighted text looks weird because the background is painted according to the resulting line height. It also would be fixed if background was rendered according to the actual text height.

![kitty2](https://user-images.githubusercontent.com/945210/33342361-fbade8e2-d468-11e7-8473-3ad5ed3544b4.png)
- Here you can see that the box-drawing lines ├ looks weird next to the text

The ideal solution would be to render text center-aligned in the cell height, but setting cursor and background height aliviates the problem.

**Comment by nolanwrightdev** [comment]
Hi, I wish to change the adjusted line height property because I think it looks nicer, but when I do so, as mentioned in this issue, the cursor takes up the entire height which looks quite odd. Might it be better if the cursor were to stay the same height as the font in this case?
