### ISSUE TITLE
"Failed to launch child" when opening kitty in a folder

### ISSUE THREAD

**Issue by Jeppefs** [kovidgoyal/kitty#1930]
Opening a new kitty terminal in a given directory using the command
`kitty PATH`
does not work as expected

Example with an existing path: 
`kitty /home/jfs/Dropbox

Expected result: 
Opening a new kitty terminal in `/home/jfs/Dropbox`

Real result: 
A new kitty window is opened with the following message 
`
Failed to launch child: /home/jfs/Dropbox
With error: Permission denied
Press Enter to exit.
`

This only happens with kitty - other applications launch in a given folder just fine. Do I maybe need to give some permissions somewhere?

**Comment by Luflosi** [comment]
When you pass an argument to kitty like that, kitty tries to execute it. To open a new kitty instance with a different directory, use `kitty --directory /home/jfs/Dropbox` or `kitty -d /home/jfs/Dropbox`. You can see this and all the other command line arguments with `kitty --help`.

What are you trying to do? Maybe there is a better way to do this. If you open a new instance of kitty it takes up more resources than just one kitty instance with multiple windows. The `--single-instance` or `-1` command line argument would help with that.

**Comment by Jeppefs** [comment]
Wauw, thank you for your response Luflosi. I feel a bit stupid now - I can not believe I completely missed that. I have looked through kitty --help multiple times and completely missed it... 

The command is used when starting up the window manager, to startup a kitty session in a given directory. I am often using multiple Kitty sessions, so the --single-instance argument is very useful to know about. The additional advice is much appreciated.

**Comment by Kabouik** [comment]
I'm getting the same issue when trying to launch `kitty` from command line and have it run an alias from my `~/.bashrc` immediately using `kitty aliascmd`. I'm guessing it's because kitty doesn't take `~/.bashrc` into account when it is launched this way. Is there a workaround? I would need it to automatically run the correct programs in kitty when opening some i3 workspaces, and some of those aliases are [very long](https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_zsh) so using the base command is not really an option.

**Comment by FrenzyExists** [comment]
I have it when i want to open a file for some reason, for example
![image](https://user-images.githubusercontent.com/47986470/108001192-2c26a200-6fc2-11eb-9483-8600fba8f904.png)
if I click the file (aka `powerlevel10k/gitstatus/README.md`) I end up with
![image](https://user-images.githubusercontent.com/47986470/108001255-4e202480-6fc2-11eb-9040-f912e9e486d4.png)
However, the rest of the files (the lines n stuff) i can open it with nvim just fine, so, any idea of where i am messing at?

**Comment by kovidgoyal** [comment]
Set the EDITOR env var system wide or specify the editor without using the env var in open-actions.conf

**Comment by FrenzyExists** [comment]
got it, lemme try that a sec-

**Comment by FrenzyExists** [comment]
Ok, so, i'm kinda lost... so, my `$EDITOR` is in fact nvim, when I type the env var in kitty I get nvim, so, I'm quite lost.

**Comment by FrenzyExists** [comment]
Ok update. So, I'm dumb, really dumb. I had the `action launch` thingy on '${EDITOR}, which yeah, it should work, yeah, its from the manpages, but for some reason it didn't worked. So anyway I changed it to `nvim` and voila! it worked, somehow, not gonna question it at all. Here's the config file for anyone having the issue or something:

```
# Open any file with a fragment in vim, fragments are generated
# by the hyperlink_grep kitten and nothing else so far.
protocol file
fragment_matches [0-9]+
# action launch --type=overlay nvim +${FRAGMENT} ${FILE_PATH}
action launch --type=overlay nvim ${FILE_PATH}

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=overlay nvim ${FILE_PATH}
```

**Comment by Luflosi** [comment]
You probably changed the `EDITOR` environment variable in your `.bashrc` or similar. But that file is loaded by your shell _after_ kitty starts, so kitty can' know about it. See https://serverfault.com/questions/375252/what-is-the-best-place-to-setup-system-wide-environment-variables-on-linux for how to set an environment system-wide.

**Comment by FrenzyExists** [comment]
i use zsh

**Comment by ota0912** [comment]
When I try to launch a `.bashrc` alias command using `kitty -e aliascmd`, it reports the error 
`Failed to launch child: aliascmd With error: No such file or directory` 
Why does this happen even though am able to run the alias command directly?
