### ISSUE TITLE
urxvt tint replacement

### ISSUE THREAD

**Issue by mikusHusbando** [kovidgoyal/kitty#1932]
Hello everyone,

I am using kitty with much pleasure since a while now, but I am really missing urxvts tint (cyan) feature and I am unable to recreate the effect in kitty. Any chances I can recreate this effect? 
![20190607-235216-323285432](https://user-images.githubusercontent.com/30121701/63838637-3d629580-c96d-11e9-90fe-9ff0c0a82cc3.png)

**Comment by kovidgoyal** [comment]
Not sure what you mean? How is this different from the existing
background_opacity feature in kitty.conf? Choose a greenish background
color and set the opacity and it should be similar.

**Comment by mikusHusbando** [comment]
Hello, thanks for the swift response. I had tried (and just tried again) creating this effect but all my tinkering leads to bad results. I was hoping someone could point me in the right direction of what settings to use. This is what I can get out of it:
![20190828-130652-386085699](https://user-images.githubusercontent.com/30121701/63850577-ecaa6700-c983-11e9-9afe-8cf8464f1539.png)

They just all seem too light in comparison to the desired result and I don't know how to change that. The opacity setting only has limited effects to this and I seem to not grasp color theory enough to change it into a darker shade (tried #00fffff and #22dddd for background).

**Comment by mikusHusbando** [comment]
I forgot to mention that the two terminals on the left are urxvt, the two on the right are kitty, with different opacity settings and cyan (00fffff) for background color.

**Comment by kovidgoyal** [comment]
well your best bet is to check the urxvt source code to see how it does
the tint effect, figure out what the effective colorituses is and
replicate that in your kitty settings. 

Apart from that, in general for this kind of thing I like to work in the
HSL space rather than RGB, then you can adjust L for lightness to get
good results.
