### ISSUE TITLE
Feature Request: Warn before quitting if process is running

### ISSUE THREAD

**Issue by nrigaudiere** [kovidgoyal/kitty#1933]
Hi! 
First of all, thanks a lot for this great term!

I used to be working with the native MacOS Terminal.app and there was one feature that was quite usefull when you press Cmd+Q instead of Cmd+W for example ... 

> If a process is running (mysql connection etc...) a popup window would open to ask if you really want to quit.

Thanks a lot :)

**Comment by kovidgoyal** [comment]
dup of #734
