### ISSUE TITLE
Spurious Key Repeat when Starting GTK3 Applications (Wayland?)

### ISSUE THREAD

**Issue by yourealwaysbe** [kovidgoyal/kitty#1934]
Apologies if this is not directly a Kitty issue. I have checked that Termite, XTerm, and URxvt, under the same environment, do not show the same behaviour.

Environment: 
uname: Linux csmattpp 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
kitty version: 0.14.3
Window Manager: sway 1.2-rc2
Libinput: 1.14.0

Steps to reproduce:
1) Open kitty
2) Start a GTK3 application (geeqie, libreoffice) from the command line (and release keys)
3) Switch focus back to kitty with mouse (or keyboard even)
4) The last key pressed (enter or j if ctrl-j used) will be repeated in kitty

Starting GTK2 (viking) or QT applications (nvim-qt, sqlitebrowser) does not show the same issue.

**Comment by kovidgoyal** [comment]
I dont see how this can possibly be a kitty issue. kitty does not use
GTK and it does not ever synthesize key events on its own. If it is
seeing a key event it is because the compositor is sending it one. You
can check that by running kitty with --debug-keyboard
