### ISSUE TITLE
icat in small terminal issues

### ISSUE THREAD

**Issue by ahh** [kovidgoyal/kitty#194]
![demo](https://user-images.githubusercontent.com/247726/33366036-f4614a08-d49e-11e7-829b-a85bbbce9301.png)

In this image, I ran icat to display a simple image in a terminal that wasn't very tall.  The paging here isn't quite what I'd like.  In particular, I think this should give me a prompt *below* the image entire, which I should then be able to scroll back over.

**Comment by kovidgoyal** [comment]
Yeah, that's a bug I just haven't got around to fixing, press enter a fw times and your prompt will appear and you will be able to scroll to see the image.
