### ISSUE TITLE
Where's build-kitty?

### ISSUE THREAD

**Issue by webknjaz** [kovidgoyal/kitty#1941]
Hi, I noticed that build scripts refer to `build-kitty` which is nowhere to be found. Any chance that you open source it?

**Comment by Luflosi** [comment]
Maybe it's the kitty branch of https://github.com/kovidgoyal/build-calibre?

**Comment by kovidgoyal** [comment]
It is the bitty branch of build-calibre

**Comment by webknjaz** [comment]
Ah, cool. It'd be nice to mention this in readme probably.
