### ISSUE TITLE
cannot break out of command history search buffer

### ISSUE THREAD

**Issue by nsklaus** [kovidgoyal/kitty#1944]
hi,
i use this mapping in ~/.config/kitty/kitty.conf
`map ctrl+c copy_or_interrupt`

and when i do ctrl+r to do a reverse search in command history buffer i cannot break out of it because of my mapping. copy_or_interrupt is supposed to send a break when nothing is selected to copy, it usualy do that well, but not in that particular case.

**Comment by kovidgoyal** [comment]
With what shell?

**Comment by nsklaus** [comment]
bash

**Comment by kovidgoyal** [comment]
I cannot replicate steps I tried:

1) Run kitty as:
kitty -o "map=ctrl+c copy_or_interrupt" bash

2) Press ctrl+r, reverse search prompt appears

3) Press ctrl+c, works as an interrupt, back to bash prompt

**Comment by kovidgoyal** [comment]
Also, I dont see how what state the shell is in could possibly matter to this function. Whether kitty sends a interrupt or not depends entirely on whether there is a selection or not, whichis not in the control of the shell.

**Comment by nsklaus** [comment]
this problem exists. you just need to run the shell longer.
if you just start new instance it works as intended. 
if you keep that instance running after a while it just doesn't send break anymore.
and this is not just with the reverse history command search with every command.
after a while you just cannot send breaks anymore.

**Comment by kovidgoyal** [comment]
Again, it does not matter what state the shell. Or how long it has been
running. The *only* thing that can cause this is there being a
selection. So I suggest when it happens, you simply deliberately select
and then clear the selection by clicking elsewhere in the window.

**Comment by nsklaus** [comment]
don't you think that's the most evident think to do and i already tried it and it didn't work?

**Comment by nsklaus** [comment]
here, it's a video of it:
https://ufile.io/4ilgjccd

terminal on workspace 5 is freshly started, ctrl+c break works as intended.
terminal on workspace 4 was started a while ago, ctrl+c doesn't send break anymore.

**Comment by kovidgoyal** [comment]
Well considering this bug report is a perfect example of minimum effort
bug report, I am not going to made assumptions about what you may or may
not have tried. You haven't bothered to tell us anything about what OS,
kitty version, shell version. What steps to minimally reproduce your
problem (and I'm sorry but "leave it running for some time is useless"). 

So I'm just going to leave you with a link to the five line function
that implements this feature, see if you can find a bug in it:

https://github.com/kovidgoyal/kitty/blob/master/kitty/window.py#L554

On Wed, Sep 04, 2019 at 01:10:03PM -0700, nsklaus wrote:
> don't you think that's the most evident think to do and i already tried it and it didn't work?
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/1944#issuecomment-528064914

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by nsklaus** [comment]
my os is arch linux.
my kitty version is: 0.14.4-1
when i get more info to share on this i'll communicate. a modest contribution is better than nothing. you should know there's no such thing as bug free code. don't be so quick to judge or dismiss the possibility. it can come from many points, including some upstream libs you might rely on.

**Comment by kovidgoyal** [comment]
Well, if you find a way to make it reproducible, I will be most interested.
