### ISSUE TITLE
Underline rendering different with iTerm2

### ISSUE THREAD

**Issue by ingjieye** [kovidgoyal/kitty#1945]
I'don't know if this is a bug or misconfiguration or something. 

Kitty render underline as:
<img width="299" alt="屏幕快照 2019-09-01 下午5 03 49" src="https://user-images.githubusercontent.com/13421169/64074201-e9441200-ccda-11e9-95e2-c4fe5b40cdea.png">
While iTerm2 render underline as:
<img width="296" alt="屏幕快照 2019-09-01 下午5 03 53" src="https://user-images.githubusercontent.com/13421169/64074207-f6f99780-ccda-11e9-8310-e2d11f0d0cd5.png">
 
I've tried to adjust the `adjust_line_height` but won't work.
So how do I make kitty render underline like iTerm2 does? 
Thanks!

**Comment by kovidgoyal** [comment]
I'm afraid that there is no setting to control underline rendering
in kitty. Underline thickness and position comes from the informatin in
the font, specifically CTFontGetUnderLinePosition() see core_text.m for
details.

**Comment by ingjieye** [comment]
> I'm afraid that there is no setting to control underline rendering
> in kitty. Underline thickness and position comes from the informatin in
> the font, specifically CTFontGetUnderLinePosition() see core_text.m for
> details.

In my configuration Kitty and iTerm2 use the same font.
So does this mean iTerm2 use something rather than CTFontGetUnderLinePosition() to get underline positions? Is there a way to optimize this?

**Comment by kovidgoyal** [comment]
No idea, iTerm is open source am sure you can check. Rendering the same
as iTerm is not really a goal for kitty though. If there is some actual
improvement that can be made to the algorithm to place underlines, I'm
open to ideas.

**Comment by ingjieye** [comment]
> No idea, iTerm is open source am sure you can check. Rendering the same
> as iTerm is not really a goal for kitty though. If there is some actual
> improvement that can be made to the algorithm to place underlines, I'm
> open to ideas.

I know that rendering the same as iTerm does is not Kitty's goal. And it shouldn't. 
But underline rendering indeed iTerm do better than Kitty.

So I've checked the iTerm's source code. there's no `CTFontGetUnderLinePosition()` function. And do have some function regarding underline, but I'm not a native developer so it's hard for me to read into iTerm's source code.

Then I decide why don't I just change the return value of `CTFontGetUnderLinePosition` and `CTFontGetUnderlineThickness`. So here's What I do:

<img width="749" alt="屏幕快照 2019-09-02 上午9 15 22" src="https://user-images.githubusercontent.com/13421169/64084986-944bde80-cd62-11e9-9115-17778edad222.png">

I know it seems ugly and might break upon future commit (currently on release 0.14.04).
But I work's for me. So I decide just paste I out incase anyone have the same problem.
Tested on macOS 10.14.6 with both retina and regular monitor.

Here's what Kitty's underline rending looks like after what I did:
![屏幕快照 2019-09-02 上午9 19 29](https://user-images.githubusercontent.com/13421169/64085064-0d4b3600-cd63-11e9-83d3-ba4f5f61dfad.png)

**Comment by kovidgoyal** [comment]
You cant use hard-coded offsets since the vaues depend on font family and font size, which is the whole reason kitty uses CTFontGetUnderLinePosition() in the first place, which is th erecommended practive by Apple for text rendering.

**Comment by sujiyuan** [comment]
Please reopen to open this question.
I think there are two aspects to the improvement of the underline.

1. The location of the underline. Underline is too close to the text. I changed a lot of fonts, the display effect is not ideal;
2. The other is the thickness. Thin lines make it difficult to identify. Vi m generally uses the underline to display errors, warnings, etc., so I prefer it to be conspicuous.

Consider providing `underline_offset` and `underline_thickness` options to configure the position and thickness of the underline by the user.

**Comment by ingjieye** [comment]
> Please reopen to open this question.
> I think there are two aspects to the improvement of the underline.
> 
> 1. The location of the underline. Underline is too close to the text. I changed a lot of fonts, the display effect is not ideal;
> 2. The other is the thickness. Thin lines make it difficult to identify. Vi m generally uses the underline to display errors, warnings, etc., so I prefer it to be conspicuous.
> 
> Consider providing `underline_offset` and `underline_thickness` options to configure the position and thickness of the underline by the user.

I think that's a preety good workaround instead of recompile kitty every time it gets update. Please consider it @kovidgoyal

**Comment by kovidgoyal** [comment]
Not something I am interested in, but patches are welcome.

**Comment by rajadain** [comment]
To add to this discussion, not only is there a difference in the thickness and offset of the underline, the iTerm underline keeps the text in front of the underline, allowing for elegant breaks:

![image](https://user-images.githubusercontent.com/1430060/66952267-4ba66700-f02a-11e9-84dd-c232bdf1533a.png)

in a manner similar to [`text-decoration-skip-ink`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink) in CSS.

**Comment by fsouza** [comment]
@kovidgoyal sorry for resurrecting this thread and I know you said it before, but since it's been a year I want to confirm before opening a PR: would you take a patch adding config parameters as suggested by @ingjieye? 

Thanks!

**Comment by kovidgoyal** [comment]
yes, i would, although nowadays, vim finally uses curly underlines, so the options would not be useful for the original use case anyway.

**Comment by davidscotson** [comment]
As a potential workaround for this, is it possible to display all standard underlines as curly underlines instead via a setting?

**Comment by tmillr** [comment]
I have this exact issue. I'm using `Source Code Pro` font. I don't see anywhere in the config that the underline offset may be configured? Having the underline touch the letters hurts legibility and almost ruins underlines altogether. May as well just disable them (which I don't want to do).

**Comment by kovidgoyal** [comment]
Look harder: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font
