### ISSUE TITLE
Mouse disappears on macOS?

### ISSUE THREAD

**Issue by miguelmota** [kovidgoyal/kitty#1949]
Hello, I'm trying out kitty and when I launch it my mouse disappears and need to close kitty to get it back. Is there a way to fix this? Thanks

**Comment by miguelmota** [comment]
Ok so after reading this thread https://github.com/kovidgoyal/kitty/issues/1218 I set `mouse_hide_wait 0` in `~/.config/kitty/kitty.conf` which seems to have fixed the mouse cursor from disappearing

**Comment by Luflosi** [comment]
The actual bug referenced in that issue should be fixed now. The `mouse_hide_wait` config option purposefully hides the mouse after three seconds. As you already figured out, you can turn that off by setting the config option to `0` if you don't like that.
