### ISSUE TITLE
fade inactive terminals

### ISSUE THREAD

**Issue by ahh** [kovidgoyal/kitty#195]
Several terminals I've used (Terminator comes to mind) support a very useful feature: terminals that are unfocused dim/fade (set brightness to 80%, say) all their contents (not just titlebars, etc.)  This is great as a visual cue for where my cursor is and where I'm giving input. (Note that I use awesome-wm so I don't have any cues you're showing in titlebars or the like.)  

I can't find an option for this in kitty--am I missing one?  If not, I'd love if it were added.

**Comment by kovidgoyal** [comment]
Doesn't your window manager provide cues as to what the active window is? Forinstance, i use a tiling wm and have it set to change the color of the broder around the active window. The only cue kitty itself provides is the block cursor being filled/hollow. 

IMO, this is really a function your window manager should provide, not one that every application should have to re-invent.
