### ISSUE TITLE
Copying the current text in prompt to clipboard?

### ISSUE THREAD

**Issue by brandonharrisonhpe** [kovidgoyal/kitty#1954]
Is there a way to copy the current prompt to the clipboard?  I use this often when I am creating an alias for a command and want to quickly copy whatever I've been typing.  The only way I've seen to do this without resorting to the mouse is to use the copy lines hints with `kitty_mod+p>l` and do it one line at a time for a particularly long command.

**Comment by kovidgoyal** [comment]
Most modern shells have this functionality builting, for example:

echo !!

if you want to do it in kitty, setup a right hand prompt in your shell
and use the hints kitten that matches text between the left hand and
right hand prompts.
