### ISSUE TITLE
`kitty list-fonts` shows nothing at all?

### ISSUE THREAD

**Issue by thecakeisalie25** [kovidgoyal/kitty#1955]
`kitty list-fonts` shows no output, despite `fc-list` showing a bunch of fonts. I've done `fc-cache -r`, and still no luck. Any help?

I use arch btw.

kitty --version: 0.14.4
![Here's my neofetch, kitty --debug-config, and --default-font-fallback](https://user-images.githubusercontent.com/9502466/64347200-1f261680-cfb9-11e9-9cf5-bb04dd93fdbb.png)

**Comment by kovidgoyal** [comment]
You need to have some actual monospace fonts installed, check with the
fc-list command as described here: https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font

**Comment by Luflosi** [comment]
I find it a bit weird, that kitty actually uses NotoSansMono for him but doesn't list it with `kitty list-fonts`.

**Comment by thecakeisalie25** [comment]
I installed noto fonts via yay, so it should at least list that, right?

**Comment by thecakeisalie25** [comment]
I also installed nerd-fonts-source-code-pro, so it should list that, right?
