### ISSUE TITLE
Feature Request: Convert Session to New-OS-Window

### ISSUE THREAD

**Issue by parf** [kovidgoyal/kitty#1956]
Trying to convert from Konsole terminal to kitty, i'm missing this feature:

>> Detach Current View (Ctrl+Shift+H) Opens the current view in a separate window
i.e. convert current session to a new os-window (similar to Ctrl+Shift+N but for current session)

**Comment by Luflosi** [comment]
This is similar to #1310.

**Comment by kovidgoyal** [comment]
Indeed, if and when I implement #1310, this would be a simple addition, please add a note there.
