### ISSUE TITLE
set-colors does not update background border color

### ISSUE THREAD

**Issue by ismay** [kovidgoyal/kitty#1957]
When using `kitty @ set-colors -all <theme.conf>` all colors are updated correctly, except for the border that extends the background color (see the light gray color that surrounds the dark blue, especially at the bottom, that's the background color from the old theme):

<img width="1280" alt="Screenshot 2019-09-07 at 10 01 34" src="https://user-images.githubusercontent.com/7355199/64471848-80cfb780-d156-11e9-836d-3118dec3720d.png">

the colors I'm setting with the set-colors command are:

```
background #1b182c
foreground #cbe3e7
color0 #3b3b4f
color1 #ff5458
color2 #62d196
color3 #ffb378
color4 #65b2ff
color5 #906cff
color6 #63f2f1
color7 #a6b3cc
color8 #807b8a
color9 #ff8080
color10 #95ffa4
color11 #ffe9aa
color12 #91ddff
color13 #c991e1
color14 #aaffe4
color15 #cbe3e7
url_color #65b2ff
cursor #a6b3cc
cursor_text_color #1b182c
selection_background #cbe3e7
selection_foreground #1b182c
active_tab_background #807b8a
active_tab_foreground #cbe3e7
inactive_tab_background #807b8a
inactive_tab_foreground #a6b3cc
inactive_border_color #cbe3e7
bell_border_color #cbe3e7
```

When I include the same theme in my kitty.conf and restart kitty the background color is extended correctly, the visual bug only happens when using set-colors (with the exact same .conf).

**Comment by kovidgoyal** [comment]
I'm not sure what you are refering to? I see a dark gray padding color at the bottom. You mean the padding in the kitty window when the window is not an exact multiple of the cell size?

**Comment by ismay** [comment]
> You mean the padding in the kitty window when the window is not an exact multiple of the cell size?

Yes exactly, that's retaining the old background color. To clarify:

![image](https://user-images.githubusercontent.com/7355199/64472204-26852580-d15b-11e9-88f8-d1b0d16bbf53.png)

**Comment by kovidgoyal** [comment]
That's because you have multiple windows open, in this case the
configured background color is used. switch to a layout with a single
window and you will see the color change. You can use the --configured
flag to set-colors to also change the configured colors.

**Comment by ismay** [comment]
Ah I see, I didn't realize that. Thanks for the quick reply, and my compliments on maintaining this project so well! 👍
