### ISSUE TITLE
Consistant layout options for startup session

### ISSUE THREAD

**Issue by Mozhaaak** [kovidgoyal/kitty#1958]
The layout is inconsistent when setting it in start session via *kitty @ new-window* and *kitty @ resize-window*. Basically, I was trying to combine a Music player, cover, visualization in one terminal tab like so ![2019-09-08_02-38-44_screenshot](https://user-images.githubusercontent.com/47674192/64481298-22e8b180-d1e2-11e9-8a40-b67698f5afb6.png)
I went with a Grid layout and from time to time I would get windows spawned in the wrong order, sometimes 1 window wouldn't spawn at all, also the focus could get off the window chosen with *--match title:window*.
It would be cool to change window position, like swapping it with another window by inline numbers. Or some other way to make custom layouts consistent.
Used commands:
[Controlling kitty from scripts or the shell](https://sw.kovidgoyal.net/kitty/remote-control.html)
[Startup Sessions](https://sw.kovidgoyal.net/kitty/index.html#startup-sessions)

**Comment by kovidgoyal** [comment]
Why are you using kitty @ newwindow in a startup session? Just use launch, that will guarantee consistent startup order. If startup order is consistent that will make positioning also consistent.

**Comment by Mozhaaak** [comment]
Thank you, that solved my problem. Didn't bother to check whether launching new stuff would allocate new window in kitty =)
P.s. Custom layouts like in tmux would be great though.
