### ISSUE TITLE
Can no longer switch tabs via keyboard

### ISSUE THREAD

**Issue by qazip** [kovidgoyal/kitty#1959]
I can no longer switch tabs using my keyboard shortcut. This is what I have in kitty.conf:

map ctrl+PageUp next_tab
map ctrl+PageDown previous_tab

However, when pressing those keys I get "5~5~5~5~5~" in the terminal window, without actually switching tabs..

**Comment by Luflosi** [comment]
You're not providing much information, more information would be helpful. Which OS are you using? Which kitty version are you using? Did you update kitty recently? Which version were you using before?

**Comment by kovidgoyal** [comment]
The key name is page_up not pageup

**Comment by qazip** [comment]
Sorry @Luflosi, here it goes:
OS: Arch;
Kitty version: kitty 0.14.4 created by Kovid Goyal

I updated kitty 8 days ago, when it was released.

**Comment by qazip** [comment]
> The key name is page_up not pageup

Ah yes, this fixed it.

**Comment by Luflosi** [comment]
> I can no longer switch tabs using my keyboard shortcut.

This sounds like it used to work and now doesn't anymore. If the name has always been `page_up` then why did `PageUp` work in the past?
