### ISSUE TITLE
Can't compile on x86 system

### ISSUE THREAD

**Issue by NeoTheFox** [kovidgoyal/kitty#196]
Despite  8961eaaa9dc35c6654ff1651c4729253e3d2c628 I still can't build kitty on Intel atom system. 

```
/home/neothefox/.cache/pacaur/kitty-git/src/kitty/kitty/line.c: In function ‘text_at’:
/home/neothefox/.cache/pacaur/kitty-git/src/kitty/kitty/line.c:164:14: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (xval >= self->xnum) { PyErr_SetString(PyExc_IndexError, "Column number out of bounds"); return NULL; }
              ^~
```

**Comment by kovidgoyal** [comment]
Yeah, I dont have a 32bit system to test on. (to be more precise, I dont have the time/interest to setup a 32bit VM). So I can only fix errors other people point out to me.

**Comment by kovidgoyal** [comment]
So I'll be happy to accept PRs with changes to support 32bit, but I am not going to spend time on it myself.
