### ISSUE TITLE
Italic "M" rendered incorrectly

### ISSUE THREAD

**Issue by berenddeboer** [kovidgoyal/kitty#1960]
The bottom left of the italic "M" is cut off. I think I'm using "Inconsolata Medium".

**Comment by kovidgoyal** [comment]
kitty renders fonts in a character grid, so if the italic font you are
using does not fit in the cell size as calculated for the main font, you
will get glyphs either shrunk or cut off. You can either: Pick a
different font, or adjust the cell size in kitty.conf via
adjust_column_width

**Comment by berenddeboer** [comment]
Gnome terminal displays font just fine. And it's just the letter M.

**Comment by kovidgoyal** [comment]
Your point being?

**Comment by berenddeboer** [comment]
That it is just odd. I have tmux open in gnome terminal, all fine, in kitty the M is cut off. Same screen etc. I thought you wanted to know.

**Comment by kovidgoyal** [comment]
I already know, this is by design, read my previous post.
