### ISSUE TITLE
Deadlocks when recived incompleted graphic command

### ISSUE THREAD

**Issue by aslpavel** [kovidgoyal/kitty#1961]
If incomplete graphic command send by some programm, you cannot do anything to get control back.
- way to reproduce `$ printf "\x1b_G"`
- what happens: terminal locks and ignores all possible combinations to regain control

**Comment by kovidgoyal** [comment]
Sure you can, just keep any key pressed for a few seconds. This is the
whole reason I insist on having short max escape code lengths in kitty.

That said I should probably have the reset terminal action reset the
parser state as well.
