### ISSUE TITLE
Autoreconnect stuck on Error message

### ISSUE THREAD

**Issue by MacGyver27** [kovidgoyal/kitty#1962]
Hi,

My scenario is to use kitty as a tunnel initiator from the host. While having **autoreconnect** set up the kitty will hang on a error message window and won't reconnect.. E.g. if there is a short network disconnect, error will say it cannot resolve the host and requires manual confirmation in order to proceed and then it will autoreconnect. It is counterproductive and there should be another check-box to suppress any kind of errors and just try to reconnect in a infinite loop.

![image](https://user-images.githubusercontent.com/6546231/61704624-6a0b0800-ad44-11e9-85e9-9c83586a7796.png)

This would be much appreciated, thanks Michal

**Comment by Luflosi** [comment]
I think you're mistaking KiTTY for kitty. KiTTY runs on windows and kitty does not. This is an unfortunate naming conflict.

**Comment by MacGyver27** [comment]
true.. sorry for that, however is this "addressed" here?

**Comment by Luflosi** [comment]
What do you mean with "addressed here"? The two projects are totally different.

**Comment by MacGyver27** [comment]
just if such a configuration is possible.. I also have a Linux VM.. and my
goal is to have a persistent tunnel no matter the fluctuation on the
network..

**Comment by kovidgoyal** [comment]
Persistent SSH tunnels are not the province of terminal emulators. For
that, use a tool like autossh

**Comment by MacGyver27** [comment]
thanks a lot, michal
