### ISSUE TITLE
Latest master spawns infinitely due to update checking

### ISSUE THREAD

**Issue by dcolascione** [kovidgoyal/kitty#1965]
I just built kitty master. When running it, it spawns an infinite number of terminals, each displaying:

Failed to launch child: +runpy
With error: No such file or directory
Press Enter to exit.

In the launching terminal, kitty outputs, repeatedly, "[254 17:22:42.539356] Failed to process update check data '', with error: invalid literal for int() with base 10: ''

Turning off the update check fixes the problem

**Comment by dcolascione** [comment]
In the launching terminal, kitty outputs, repeatedly, "[254 17:22:42.539356] Failed to process update check data '', with error: invalid literal for int() with base 10: ''

**Comment by kovidgoyal** [comment]
You likely have two version of kitty in your system/PATH. The
conflicting versions are causing the issue. Clean out the old one and yu
will be fine.
