### ISSUE TITLE
set-colors mapped to kb?

### ISSUE THREAD

**Issue by vaskark** [kovidgoyal/kitty#1970]
I'm wondering if the `kitty @ set-colors` command can be put into our kitty.conf file and mapped to certain keys to change colour schemes on the fly.

This is what I have in kitty.conf:

```
map kitty_mod+shift+c>0		set_colors reset
map kitty_mod+shift+c>1		set_colors -a ~/.config/kitty/themes/Nord.conf
map kitty_mod+shift+c>2		set_colors -a ~/.config/kitty/themes/Argonaut.conf
etc ...
```

Thanks.

Ubuntu 19.04
kitty 0.14.4

**Comment by kovidgoyal** [comment]
You can run any arbitrary command via mappings, including kitty @ commands. See https://sw.kovidgoyal.net/kitty/pipe.html  use it with none none to run the command in the background.
