### ISSUE TITLE
Kitty has problems rendering certain emoji

### ISSUE THREAD

**Issue by lyneca** [kovidgoyal/kitty#1971]
For example, the fire 🔥 emoji - U+1F525:
![09-16-19T16:31:43](https://user-images.githubusercontent.com/7028282/64937950-8e481880-d89f-11e9-9f74-e79824e9d015.png)

I have the following in my `kitty.conf`:
```conf
symbol_map U+1F525 JoyPixels
# (where JoyPixels is the new name for EmojiOne)
```
And JoyPixels certainly has the glyph in question:
![09-16-19T16:27:45](https://user-images.githubusercontent.com/7028282/64938003-c0f21100-d89f-11e9-8a30-da43a578069d.png)

The emojis render correctly and in full color _without_ this `symbol_map` definition.

However in nVim, many problems occur when entering emoji; stray characters 'stick' to the screen position when scrolling the screen, and the cursor's position may be a few characters off where the cursor actually is.

Is this a Kitty problem, or a vim/shell problem? I'm on Arch, Kitty 0.14.4, and zsh.

**Comment by kovidgoyal** [comment]
A vim problem. It will not be using the right width for that symbol.
kitty uses width from the current unicode standard for all codepoints.
Many other software tends to use outdated or system dependent width
implementations.

**Comment by lyneca** [comment]
Thanks for your quick response :)
