### ISSUE TITLE
Scroll position after resize window

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1972]
If i resize the window, e.g. make it smaller in height, and then large again, the scroll position does not move up again, like it does in the macOS terminal app ( and also in alacritty ). I would prefer this familiar behavour. 

list some files
<img width="696" alt="Screenshot 2019-09-16 at 23 27 08" src="https://user-images.githubusercontent.com/1562523/64995222-f49e5c80-d8da-11e9-8eb7-f543698452a1.png">
make window smaller in height
<img width="587" alt="Screenshot 2019-09-16 at 23 27 20" src="https://user-images.githubusercontent.com/1562523/64995223-f49e5c80-d8da-11e9-9e7b-b5fe9f4cc359.png">
make it large again, does not scroll to the original position
<img width="684" alt="Screenshot 2019-09-16 at 23 27 33" src="https://user-images.githubusercontent.com/1562523/64995225-f536f300-d8da-11e9-9b2e-b146be65c2de.png">

I did mention some resize issues before, so sorry if i repeat myself.

( I also would really like if it would re-render / wrap text on the fly as you resize, but i think you've mentioned before there were some problems doing this .. )

I'm on macOS 10.14.6 (18G95) using latest Kitty 5bed0ddd

**Comment by kovidgoyal** [comment]
Sorry not something I am interested in implementing.
