### ISSUE TITLE
Kitty doesn't use xinput mouse mappings?

### ISSUE THREAD

**Issue by Phill** [kovidgoyal/kitty#1974]
I have an eight button mouse and I've remapped the buttons with xinput.

xinput set-button-map 6 1 10 3 4 5 6 7 8 9 2 11 12

This works in all my apps so far except Kitty. Kitty still uses the default mapping. How do I remap the mouse buttons.

**Comment by kovidgoyal** [comment]
No idea, you'd have to ask in the glfw project which is the toolkit
kitty uses.

**Comment by Phill** [comment]
OK.
