### ISSUE TITLE
Change tab character width

### ISSUE THREAD

**Issue by pema99** [kovidgoyal/kitty#1981]
Hey there, I have a question that I haven't been able to find an answer to in anywhere in the docs.

Is it possible to change the width/size of the tab character (\t)?

By default it seems to be equivalent to the size of 8 spaces, but I would like to change it to be equivalent to 4.

Example:
![2019-09-19-025219_420x106_scrot](https://user-images.githubusercontent.com/11212115/65200801-94e5b400-da88-11e9-98ee-9c5923c9196b.png)

**Comment by kovidgoyal** [comment]
There are standard terminal escape codes you can use to set tab stop
positions in all terminals, a bit of googling should find them for you.

**Comment by Frydac** [comment]
I did some googling and came out on
https://linux.die.net/man/1/tabs
e.g.
`tabs -15`
sets the tabwidth to 15 characters, I think this is handy when my cli program prints tab separated value (tsv) format tables
