### ISSUE TITLE
Kitty can't handle journalctl output

### ISSUE THREAD

**Issue by andriyohorodnyk** [kovidgoyal/kitty#1985]
System: OpenSUSE Tumbleweed and Ubuntu 19.04 (both on Wayland)
Executing command journalctl gives the following message:
```
# sudo journalctl -xe
WARNING: terminal is not fully functional
-  (press RETURN)
```
and scrolling is not possible

**Comment by Luflosi** [comment]
Did you execute this command on your local machine where kitty is installed or over ssh?

**Comment by alephnull** [comment]
Take a look at the ssh kitten which will setup a functioning terminal over ssh for you. A quick and dirty workaround is to:
```shell
alias ssh='TERM=xterm ssh'
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer
