### ISSUE TITLE
The purpose of `/usr/lib/kitty/terminfo/x/xterm-kitty` file

### ISSUE THREAD

**Issue by vp1981** [kovidgoyal/kitty#1989]
Hello,
I'm using Archlinux and recently the kitty package was splitted into two packages, one of which provides the `xterm-kitty` terminfo file. This is ok and in accordance with suggestion on page
https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers
but still the 'kitty' package provides the same file in path `/usr/lib/kitty/terminfo/x`. Does kitty use that file or it is used by kitty only when it runs in build directory?

**Comment by kovidgoyal** [comment]
You can remove it from the kitty package dir if you really want to, but
I would advise against it. It's not a large file and generally speaking
downsream packages should diverge as little as possible.

**Comment by vp1981** [comment]
Hello,
sorry to reply to closed issue, but I want to be sure on topic. Right now Archlinux provides two packages: `kitty` and `kitty-terminfo`. The file in question is in `kitty` package, I suggested to move it to `kitty-terminfo` package (same path). I think it is more logical to have all terminfo files in one package. If it is Ok for you, wouldn't you mind to update the page https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers to explicitly suggest to move all terminfo file into separate package?

**Comment by kovidgoyal** [comment]
No not really. The kitty-terminfo installs a system wide terminfo. The
one in the kitty package is private to kitty. I dont this the
kitty-terminfo package should install a private terminfo file.
