### ISSUE TITLE
kitty.conf on MacOS not being used

### ISSUE THREAD

**Issue by hurrtz** [kovidgoyal/kitty#199]
Hey guys,

I am checking kitty out (coming from iterm and hyperterm) and somehow I can't get the kitty.conf to work...

After having installed kitty from the dmg I have put your example kitty.conf (with the font size set to 50) into both ~/.config/kitty and ~/Library/Preferences/kitty - both to no avail. Have I done something wrong?

**Comment by kovidgoyal** [comment]
Works for me.
``` 
cat ~/Library/Preferences/kitty/kitty.conf
font_size 50.0
```

Results in enormous text.

You can always use command line arguments to specify both individual configuration directives as well as the path to one or more config files, that are merged.

```
/Applications/kitty.app/Contents/MacOS/kitty --help
```
