### ISSUE TITLE
A simpler way of lauching a new window/tab with kitten

### ISSUE THREAD

**Issue by alephnull** [kovidgoyal/kitty#1991]
# Context
I  ssh to a lot of strange servers. Most of them work poorly with kitty due to `TERM=xterm-kitty`. The ssh kitten does fix the terminal problem but it does it in the active window. It would be prefereable to launch a new tab.

# Approaches

## From sway
As you know making ssh DTRT with TERM is non-trivial so after setting up a chain of wrappers and sort of getting it to work from the window manager (sway), I threw all of it away as an unmaintainable mess.

## Use the ssh kitten
Attempt to bind it to a kitty keybinding. I tried:
```
map kitty_mod+alt+p>c       new_tab kitten ssh cubox tmux a
```
but that's a bust. Looking at the code, I'm not sure this is ever going to work.

## Remote control
I am able to get it to work with the following commands:
```shell
new-window --new-tab --tab-title cubox --keep-focus --title cubox
kitten --match title:cubox ssh cubox tmux a
```
However, I am unable to bind this to a key.

# Help needed
I come to kitty after about 20 years with rxvt-unicode and it is awesome. Thanks very much. It is the main reason it has made it possible for me to move to the brave new Wayland world.

**Comment by kovidgoyal** [comment]
You want to open a new tab with an ssh session?

map some_key new_tab kitty +kitten ssh whatever
