### ISSUE TITLE
kitty won't come up when starting via sxhkd

### ISSUE THREAD

**Issue by ohle** [kovidgoyal/kitty#1993]
I usually start terminals with an sxhkd hotkey. Since kitty version 0.14.4, no window appears when pressing the hotkey. There also seems to be nothing on standard input or standard output, yet two new kitty processes are spawned with each press of the hotkey.

attaching strace to sxhkd seems to show repeated read access to `/dev/ptmx`, which is answered with `EAGAIN`.

**Comment by kovidgoyal** [comment]
What is sxhd? What OS is this on? Have you tried with kitty 0.14.3 and
0.14.5? And any errors kitty experiences are logged to stdout/stderr?
What happens to thos? If you run with --debug-gl something is always
printed to stdout, can you see it?

**Comment by ohle** [comment]
I'm sorry, [this](https://github.com/baskerville/sxhkd) is the sxhkd in question (it's just an X11 hotkey daemon started by my window manager).

I'm using Ubuntu 18.04. There's nothing on stdout/stderr (`sxhkd` has an option to redirect those to a file). Also nothing with `--debug-gl`. If I replace the hotkey with echos, I do see the output.

**Comment by ohle** [comment]
> Have you tried with kitty 0.14.3 and 0.14.5?

0.14.3 works, 0.14.5 doesn't.

**Comment by kovidgoyal** [comment]
I need some way to get the stdout/stderr of the process to help you,
without that there is no information about what is going on. Create a
wrapper script that saves it to a file and use that top launch kitty if
you cannot get it to show up in sxhd's logs.

On Mon, Sep 23, 2019 at 04:30:08AM -0700, ohle wrote:
> > Have you tried with kitty 0.14.3 and 0.14.5?
> 
> 0.14.3 works, 0.14.5 doesn't.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/1993#issuecomment-534059805

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by ohle** [comment]
Like I said, there is no output. I *can* capture output from sxhkd, as verified by starting different things, but with kitty, there just isn't any.

Just to be sure I tried using a wrapper script, and I still didn't get any output 90% of the time (triggered the hotkey approx. 20 times), while still two kitty processes were spawned per incovation. These processes are still alive, by the way.

I *did* get one line of output now, out of all these attempts, though:

  > [266 15:10:40.920393] Failed to write to loop wakeup fd with error: Bad file descriptor

**Comment by kovidgoyal** [comment]
I dont see how that's possible. With --debug-gl kitty always outputs
at least one line of debug information. And if the kitty processes are
still running then they must be either in a system call or looping.
Check CPU consumption fo rthe latter and use strace for the former.

**Comment by kovidgoyal** [comment]
Ah I got it. You have two kitties on your system, and when launching
from sxhd it is launching the wrong one. Uninstall the other one and you
will be fine. That one line of output you got is from an older version
of kitty.
