### ISSUE TITLE
Fonts look very, very bad and monospaced fonts have weird spacing

### ISSUE THREAD

**Issue by tsujp** [kovidgoyal/kitty#1996]
See the left of this picture for kitty, and the right for iTerm2 both using Fira Code Regular for the font display; I don't think it's really useable with font rendering like this or is there something I am doing wrong?

I know there is no sub-pixel antialiasing on Kitty and I've played around with `macos_thicken_font` but all values look equally as bad as each other.

![img](https://i.imgur.com/CfBZjCJ.png)

Edit: I've messed around with `adjust_line_height` and `adjust_column_width` _without_ `macos_thicken_font` set which makes it look better, before I was doing it with `macos_thicken_font` set at the same time, the font still looks blurry though and not sharp.

![img2](https://i.imgur.com/gnlBSnk.png)

**Comment by kovidgoyal** [comment]
Well, feel free not to use it then.

**Comment by tsujp** [comment]
@kovidgoyal my apologies I didn’t mean to come off strong I appear to have pasted the wrong title in, I only meant for one occurrence of “very”.

It appears it might be an external monitor issue as I did a bit more digging and found another issue relating to that, I’ll give this a shot on just my laptop screen later on.

It still strikes me as weird that the font spacing is a bit whack by default even though controls are in place to adjust that as the docs themselves state using negative values might result in render artefacts.

My intent here is to be constructive.

**Comment by kovidgoyal** [comment]
font spacing looks normal to me, I suspect it is just a matter of what you are used to.

**Comment by dagadbm** [comment]
i also have the same issue.
The font looks a bit pixelated. Is there some configuration I am missing?

**Comment by dagadbm** [comment]
I am using jetbrains mono i just followed their recommendations and changed font size to 13 pixel and the line spacing to 1.2 (i could not put float values in adjust_line_height so I had to do 1.2% which I hope does the same thing)

**Comment by ctrlcctrlv** [comment]
1.2 &ne; 1.2%

**Comment by dagadbm** [comment]
So how would i input 1.2? It only accepts ints

**Comment by Luflosi** [comment]
I'm guessing 120% will do what you want.
