### ISSUE TITLE
ld: library not found for -lhon.framework/Versions/3.5/Pyt

### ISSUE THREAD

**Issue by Addisonbean** [kovidgoyal/kitty#2]
I am trying to compile kitty with Python 3.5.2 using `python3 setup.y build`, but it fails on this command:

    gcc -Wall -O3 -pthread -shared /Users/addisonbean/misc/software/kitty/build/fast_data_types-charsets.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-colors.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-cursor.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-data-types.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-freetype.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-glfw.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-history.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-line-buf.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-line.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-parser.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-screen.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-sprites.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-tracker.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-parser_dump.c.o -L/Users/addisonbean/.pyenv/versions/3.5.2/lib -lhon.framework/Versions/3.5/Pyt -L/usr/local/Cellar/glew/2.0.0/lib -lGLEW -L/usr/local/opt/freetype/lib -lfreetype -L/usr/local/lib -lglfw3 -o /Users/addisonbean/misc/software/kitty/kitty/fast_data_types.so

I am getting this error:
    
    clang: warning: argument unused during compilation: '-pthread'
    ld: library not found for -lhon.framework/Versions/3.5/Pyt
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

It looks like one of the options got truncated somehow. Any idea why this is happening? Thanks!

**Comment by kovidgoyal** [comment]
Are you doing this on OSX? kitty does not currently support OS X, although it should be relatively easy to port. This particular error occurs because of line 73 in setup.py It probably needs to be adjusted for OS X.

**Comment by kovidgoyal** [comment]
What does 

python3 -c "import sysconfig; print(sysconfig.get_config_var('LDLIBRARY'))" 

output

**Comment by samet** [comment]
I have the same issue. @kovidgoyal the output is:

`Python.framework/Versions/3.5/Python`

**Comment by kovidgoyal** [comment]
Hmm, so we need some way to get the full path to the python framework on OS X. Can somebody post the output of 

python3 -m sysconfig

on OS X? That should hopefully have enough info to get the full path.

**Comment by samet** [comment]
@kovidgoyal I put sysconfig output here: http://samet.asopy.com/sysconfig.txt

**Comment by kovidgoyal** [comment]
I have made a commit that should fix this, although I currently dont have access to an OSX machine to test on

**Comment by Addisonbean** [comment]
After that commit, I am now getting this error from python:

    Traceback (most recent call last):
      File "setup.py", line 161, in <module>
        main()
      File "setup.py", line 154, in main
        init_env(args.debug, args.asan)
      File "setup.py", line 76, in init_env
        fd = fd[:fd.index('/Python.framework')]
    ValueError: substring not found

**Comment by kovidgoyal** [comment]
Post the output of

python3 -m sysconfig

on your machine

**Comment by Addisonbean** [comment]
Here is it: http://pastebin.com/X7M79WZm

**Comment by kovidgoyal** [comment]
Ah you are running under pyenv -- I added some code for that, try it again.

**Comment by Addisonbean** [comment]
It seems closer, now I got this error:

    ld: framework not found Python.framework

That was on this command:

    gcc -Wall -O3 -shared /Users/addisonbean/misc/software/kitty/build/fast_data_types-glfw.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-charsets.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-colors.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-cursor.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-data-types.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-freetype.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-history.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-line-buf.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-line.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-parser.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-screen.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-sprites.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-tracker.c.o /Users/addisonbean/misc/software/kitty/build/fast_data_types-parser_dump.c.o -F /Users/addisonbean/.pyenv/versions/3.5.2 -framework Python.framework -L/usr/local/Cellar/glew/2.0.0/lib -lGLEW -L/usr/local/opt/freetype/lib -lfreetype -L/usr/local/lib -lglfw3 -o /Users/addisonbean/misc/software/kitty/kitty/fast_data_types.so

**Comment by kovidgoyal** [comment]
Does Python.framework not exist in /Users/addisonbean/.pyenv/versions/3.5.2?

**Comment by kovidgoyal** [comment]
This commit might also make a difference https://github.com/kovidgoyal/kitty/commit/0cd0a9f77841fd2fb5c30aee289a0fb65bf38b1f

**Comment by Addisonbean** [comment]
That last commit now gives me this error: http://pastebin.com/BCmibFGY

**Comment by kovidgoyal** [comment]
Ah looks like one more missing -framework arguments in the linker command. These should have been returned by pkg_config('glfw3', '--libs'). What does

pkg-config --libs glfw3

return on your system?

**Comment by Addisonbean** [comment]
It returns `-L/usr/local/lib -lglfw3`.

**Comment by kovidgoyal** [comment]
This should do the trick: https://github.com/kovidgoyal/kitty/commit/192ce1dea883c6cc780b512b09a3dbc0def369a7

**Comment by Addisonbean** [comment]
That's closer... Now I got this error:

Undefined symbols for architecture x86_64:
  "_glBindTexture", referenced from:
      _BindTexture in fast_data_types-data-types.c.o
  "_glBlendFunc", referenced from:
      _BlendFunc in fast_data_types-data-types.c.o
  "_glClear", referenced from:
      _Clear in fast_data_types-data-types.c.o
  "_glClearColor", referenced from:
      _ClearColor in fast_data_types-data-types.c.o
  "_glDeleteTextures", referenced from:
      _DeleteTexture in fast_data_types-data-types.c.o
  "_glDisable", referenced from:
      _Disable in fast_data_types-data-types.c.o
  "_glDrawArrays", referenced from:
      _DrawArrays in fast_data_types-data-types.c.o
  "_glEnable", referenced from:
      _Enable in fast_data_types-data-types.c.o
  "_glGenTextures", referenced from:
      _GenTextures in fast_data_types-data-types.c.o
  "_glGetError", referenced from:
      _Viewport in fast_data_types-data-types.c.o
      _CheckError in fast_data_types-data-types.c.o
      _ClearColor in fast_data_types-data-types.c.o
      _GetProgramiv in fast_data_types-data-types.c.o
      _GetShaderiv in fast_data_types-data-types.c.o
      _Uniform2ui in fast_data_types-data-types.c.o
      _Uniform1i in fast_data_types-data-types.c.o
      ...
  "_glGetIntegerv", referenced from:
      _GetIntegerv in fast_data_types-data-types.c.o
  "_glGetString", referenced from:
      _GetString in fast_data_types-data-types.c.o
  "_glPixelStorei", referenced from:
      _PixelStorei in fast_data_types-data-types.c.o
  "_glTexParameteri", referenced from:
      _TexParameteri in fast_data_types-data-types.c.o
  "_glViewport", referenced from:
      _Viewport in fast_data_types-data-types.c.o

**Comment by kovidgoyal** [comment]
That means the OpenGL libraries are not linked against. UNfortunately, I have no experience with OpenGL on OSX, so trying to figure out that the link flags for it should be is going to take some experimentation/googling.

**Comment by kovidgoyal** [comment]
Maybe try: -framework OpenGL

**Comment by kovidgoyal** [comment]
I have now got kitty building on OS X see #5 for details. Now to actually make it work :)
