### ISSUE TITLE
Launch issue MacOS

### ISSUE THREAD

**Issue by sbeldekov** [kovidgoyal/kitty#200]
MacOS 10.13.1
I am using kitty.app 0.5.0 Installed via homebrew
I am using bash-4.4.12 installed via homebrew
My kitty.conf has only colors changed

When kitty.app started directly from MacOS Launchpad it looks like behaves as non login shell. For instance, It does not source /etc/profile, so PATH variable does not have values from /etc/path and /etc/path.d and my startup .bashrc commands fail.
iTerm and Terminal do not have that issue.

My workaround for now is to started kitty.app using 'open -a' from another terminal. All works fine here.

Is it kind of expected behaviour?
Thanks in advance for the great app.

**Comment by kovidgoyal** [comment]
What is macOS Launchpad? And I dont see what difference how kitty is launched could possibly have on programs running inside kitty. Probably something in your setup somewhere is sensitive to some environment variable that is different in the two scenarios. Use env to check the differences. Presumably the other terminal emulators are stripping/normalizing those env vars. If you can identify what they are, I can implement the same in kitty.

**Comment by sbeldekov** [comment]
Thanks for the quick response.
I mean https://en.wikipedia.org/wiki/Launchpad_(macOS)

I used Hyper a while ago. It did not have the issue.
Probably my setup is the cause. I will try to investigate it.

**Comment by kovidgoyal** [comment]
I tried launching kitty from launchpad on my mac and I get the same PATH as when launching from the dock or via open -a

**Comment by sbeldekov** [comment]
Found interesting thing.

Run kitty.app from launchpad. It complains for commands not found due to invalid PATH.
Execute '/usr/local/bin/bash -l'  and it loads new shell with all PATHs correct. But without '-l' has no effect.

**Comment by sbeldekov** [comment]
'shopt' builtin says in kitty:
login_shell     off

in other terminals:
login_shell    	on

I believe it is 'on' on your end too.
No idea why it is 'off' on my side.

The truth is out there...

**Comment by kovidgoyal** [comment]
Yeah it is on for me. Like I said it is most likely something different int he environment. Run diff on the output of env in the two cases.

**Comment by kovidgoyal** [comment]
Then I'm out of ideas, sorry. I suggest just creating a script to launch kitty using open -a

**Comment by markmark1** [comment]
how to specify kitty to open brew bash v 5 and not bash 3 from mac alacritty and westerm and terminal open with correct version but kitty doesn't how to specify this in kitty.conf
