### ISSUE TITLE
resize kitty terminal window

### ISSUE THREAD

**Issue by toppk** [kovidgoyal/kitty#2002]
I'm coming from xterm, and I'm used to resizing fonts changing the window to maintain the column  and rows count as is.  Is this something that's doable?  I'd be happy to help code it if given some pointers, but haven't looked at the codebase just yet.

(I have a list of my favorite xterm features that I'm looking to replicate if I'm ever going to switch.  So far you have the only font rendering that has me willing to leave my bitmap fonts.)

**Comment by kovidgoyal** [comment]
Note that many window managers do not allow applications to resize their
own windows freely, that said, I am ok with an option to turn on this
behavior. Feel free to ask if you need pointers into the source code,
instructions for building kitty from source are at
https://sw.kovidgoyal.net/kitty/build.html 

On Wed, Sep 25, 2019 at 06:44:09PM -0700, toppk wrote:
> I'm coming from xterm, and I'm used to resizing fonts changing the window to maintain the column  and rows count as is.  Is this something that's doable?  I'd be happy to help code it if given some pointers, but haven't looked at the codebase just yet.
> 
> (I have a list of my favorite xterm features that I'm looking to replicate if I'm ever going to switch.  So far you have the only font rendering that has me willing to leave my bitmap fonts.)
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/2002

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________
