### ISSUE TITLE
Symbols from fallback font cut off when using narrow main font (M+)

### ISSUE THREAD

**Issue by BVollmerhaus** [kovidgoyal/kitty#2004]
Apologies if this is a duplicate or has already been answered, there are just a lot of font rendering–related issues to sift through.

### Situation

kitty version: `0.14.6`

I'm currently trying to use the standard, non-patched `M+ 1m` font in kitty. This is a fairly narrow font (vertically). For displaying any symbols or glyphs not part of the font, kitty automatically falls back to other fonts on my system, as expected.

### Problem

Some fairly wide symbols not in the font (that kitty has to fall back for) appear slightly cut off, irrespectively of whether they have a space after them or not. In my concrete situation, these are [`U+1f86b`](https://graphemica.com/%F0%9F%A1%AB)/[`U+1F869`](https://graphemica.com/%F0%9F%A1%A9) (🡫/🡩) and [`U+276f`](https://graphemica.com/%E2%9D%AF) (❯), see the screenshots below. Interestingly, this doesn't happen with all font sizes and the cut-off width varies as well.

Font size 12 - 🡫 slightly cut off, ❯ fine:
![cut-off-12](https://user-images.githubusercontent.com/30414540/65715832-2911d580-e09e-11e9-9153-e9ccdce17fdb.png)

Font size 14 - 🡫 cut off, ❯ slightly cut off:
![cut-off-14](https://user-images.githubusercontent.com/30414540/65715833-2a430280-e09e-11e9-935f-589eb83a4d60.png)

Font size 16 - both fine, or at least not noticeable:
![not-cut-off-16](https://user-images.githubusercontent.com/30414540/65715835-2b742f80-e09e-11e9-8240-fe41cf0d644f.png)

kitty automatically falls back for these symbols as follows:
```
U+1f86b Face(family=Noto Sans Symbols2, style=Regular, ps_name=NotoSansSymbols2-Regular, path=/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf, index=0, is_scalable=True, has_color=False, ascender=1069, descender=-630, height=1699, underline_position=-125, underline_thickness=50) (new face)
U+276f bold Face(family=DejaVu Sans Mono, style=Bold, ps_name=DejaVuSansMono-Bold, path=/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf, index=0, is_scalable=True, has_color=False, ascender=1901, descender=-483, height=2384, underline_position=-175, underline_thickness=90) (new face)
```

Now, I know that kitty renders everything in cells and I suppose that the cell size is being determined once by the main font. I guess that this cell size is then used for everything, even the fallback fonts. Hence, when using a narrow main font, the cell size is based only on that font and any fallback fonts that are wider/have wider symbols get cut off. Is this assumption correct?

Is there anything I could do to mitigate this, apart from manually increasing the column size (which would of course also affect the main font)? Shouldn't kitty automatically downsize the symbols to fit the cell, instead of cutting them off?

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#some-special-symbols-are-rendered-small-truncated-in-kitty

In your case either use a main font that has metrics compatible with the
symbol fonts you are using or vice versa. Alternately, use the setting
in kitty.conf to adjust cell width, that way all symbols will fit, at
the cost of extra spacing between regular text.
