### ISSUE TITLE
Dynamic font scaling (with font size change keys) isn't perfect

### ISSUE THREAD

**Issue by bew** [kovidgoyal/kitty#2006]
![ezgif-1-e542106769cf](https://user-images.githubusercontent.com/9730330/65805335-54bbbb00-e185-11e9-99c2-99e4e7d12d22.gif)
The text is:
```
████████
██████
████████
```
(rendering in the browser is pretty broken ^^)
The offending char symbol is (hex unicode): `e0be` with the font: `DejaVuSansMono Nerd Font Mono`.

Do you have any idea why the font scaling is doing that? Can it be avoided?

**Comment by kovidgoyal** [comment]
It has nothing to do with font scaling but rather rendering of that particular symbol. For these kinds of symbols, you can really use font rendering because they should exactly fill the cell. Instead they should be drawn manually, you can add drawing overrides for them in box_drawing.py where IIRC there are already a few PUA symbols used by nerdfonts/powerline overridden.

**Comment by bew** [comment]
It looks like this symbol is not managed by the box_drawing primitives, thus it falls back to a font..

I'm trying to implement it in box_drawing, but I don't really understand how the function `fill_buffer` is supposed to be used, especially the `xlimits` parameter.
Could you help me on that? Thank you

**Comment by kovidgoyal** [comment]
It is simply the limits within which to antialias. But you dont have to use this function if you dont want to. Rendering simply involves filling the cell buffer with numbers between 0 and 255 indicating how much opacity to apply at that pixel

**Comment by bew** [comment]
Thanks! I did the change and tested it using the `test_char` function, but now when I run a freshly compiled kitty terminal instance, it still uses the font-provided glyph, is there something else to change in the codebase to add a new manually printed glyph?

Also, where is the branching between print-using-font vs print-using-box_drawing ?

**Comment by kovidgoyal** [comment]
yes look in fonts.c search for BOX_FONT

**Comment by kovidgoyal** [comment]
And also dont forget box_glyph_id
