### ISSUE TITLE
Background proc keeping window open

### ISSUE THREAD

**Issue by redshodan** [kovidgoyal/kitty#2007]
Backgrounding a process in the shell, then exiting the shell will keep that terminal window/tab open and unusable until all backgrounded processes exit. Every term emulator I've used ignores backgrounded processes when deciding if the shell it runs has exited and needs to close the window.

Steps to replicate
start kitty
run these in shell:
  sleep 10&
  exit

The window/tab will close after 10 seconds and the sleep exits. Run something else that doesn't exit and it will never go away. You can forcibly close it with kitty_mod+w.

**Comment by kovidgoyal** [comment]
Look at close_on_child_death in kitty.conf

**Comment by redshodan** [comment]
Ok. I missed that config toggle. Could that default to be on then? To match behavior of every other terminal emulator out there.

**Comment by kovidgoyal** [comment]
Sorry, I find the behavior of every other terminal emulator out there
incorrect. Randomly breaking the stdout/stderr of background processes
is not the right thing to do. Still if you think it is feel free to use
the option.
