### ISSUE TITLE
Pasting is broken

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#2008]
It looks as if kitty's pasting behavior has changed in recent commits. If I install the stable version (14.6-1 from the Arch repo's), pasting works fine (I achieve pasting with `map ctrl+shift+v  paste_from_clipboard` in `kitty.conf`, or middle-clicking). However, when I launch a kitty instance build from HEAD, pasting doesn't give any results, even though pasting in other windows belonging to kitty 14.6 still works. 

Pasting in other apps also seems fine. I hope someone else can reproduce.

**Comment by nwronski** [comment]
I also built kitty from `HEAD` and can confirm this (on Fedora 30):
- I can copy to clipboard within kitty and paste into another kitty window
- I can copy to clipboard within kitty and paste into another program (e.g., firefox, vscode)
- I *cannot* copy to clipboard in another program and paste into kitty, even though I can paste the same clipboard contents into another program (e.g., terminator, gnome-terminal)

```
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

**Comment by Luflosi** [comment]
Looks like I broke something 🙄. I'll try to debug this tomorrow.

**Comment by Luflosi** [comment]
I found the bug.
