### ISSUE TITLE
Command line option for window title

### ISSUE THREAD

**Issue by dtcyganok** [kovidgoyal/kitty#201]
I propose to name this option as in other terminals `-t` or `--title`

**Comment by kovidgoyal** [comment]
Why would you want to set the window title? Typically the program running inside the terminal does that. For instance, the shell will set the window title to the current working directory, vim will set it to the name of the file being edited, etc. Do you mean WM_CLASS? If so you can do so via --class

**Comment by dtcyganok** [comment]
For example
`kitty -t 'Task Manager' htop`
`kitty -t 'Calculator' bc`

Thus the different kitty windows have a friendly name on the taskbar of the window manager (or in Alt-Tab dialog)

**Comment by dtcyganok** [comment]
Yes, I know about WM_CLASS. I have experience using various window managers (openbox, awesome, enlightenment), but the option --class is not helps.

**Comment by kovidgoyal** [comment]
This is implemented in the win branch.

**Comment by dtcyganok** [comment]
It's great! Thank you

Will you merge branch win to master?

**Comment by kovidgoyal** [comment]
The win branch will become kitty 0.6.0
