### ISSUE TITLE
Fedora 30, latest master ( d37e73db546e0fcd4f6baebea97b9db8bd178936 ) do not start

### ISSUE THREAD

**Issue by olivierchatry** [kovidgoyal/kitty#2010]
Using wayland, get this error : 

[272 15:10:48.583168] [glfw error 65544]: Wayland: Failed to connect to display
GLFW initialization failed

It might come from my configuration, just wanted to put it there in case someone else have the issue.

**Comment by kovidgoyal** [comment]
Works fine for me, note that WAYLAND_DISPLAY needs to be set.

**Comment by olivierchatry** [comment]
Will check if it is. Oddly, it was working some version ago. Might be some broken package update.
