### ISSUE TITLE
permissions of files in linux archive

### ISSUE THREAD

**Issue by arouene** [kovidgoyal/kitty#2011]
In the latest **linux amd64 archive** (at least, didn't check the others), many files are with a permission of **766** instead a permission of **755**.

It's a problem because it gives the right to write executable files to *others*. But no rights to executes to everybody.

Please consider to generate your archive with 755 for executable files and directories, 644 for other files.

**Comment by kovidgoyal** [comment]
Why do the permissions in the tar file matter? They are not used unless
you pass the preserve flag when un-tarring and kitty's installer script
does not do that. 

For example, permissions after running
tar xvf kitty-0.14.6-x86_64.txz

ls -l bin
-rwxr--r-- 1 kovid kovid 10520 Sep 25 11:30 kitty

Although IIRC the --preserve-permissions is default when untarring as
superuser, which may make this worth fixing.

**Comment by kovidgoyal** [comment]
Fixed in https://github.com/kovidgoyal/build-calibre/commit/ea90dd038b24c047ee4e9ed5a70696adac2a22b2
