### ISSUE TITLE
kitty @ kitten icat/diff not working

### ISSUE THREAD

**Issue by thunder-road** [kovidgoyal/kitty#2012]
Hi

I tried displaying an image into a secondary window using the syntax `kitty @ kitten -m title:Title icat filename`. The image displays just fine using `kitty +kitten icat filename` syntax. 

Also tried `kitty @ new-window --match title:ImageViewer kitty +kitten icat filename`, what i see really quickly is a new window open and message **ImageMagick is required to process image**

Also tried `kitty @ kitten -m title:Title diff file1 file2` and it also didn't display the diff in the secondary window but in the one I typed the command in. Perhaps I've misunderstood the use of the  `kitty @ kitten` syntax ?  

This is on Mac OS Mojave 10.14.5

**Comment by kovidgoyal** [comment]
You want

kitty @ new-window bash -c "kitty +kitten icat whatever; read"

The icat kitten exits after displaying the image so you cant run it
directly in a new window, or the ne window will close immediately.

**Comment by thunder-road** [comment]
Thanks for the prompt response, however I still get the message **ImageMagick is required to process images**

**Comment by kovidgoyal** [comment]
Then make sure imagemagick is in your system-wide path or run the shell
with the --login argument to make sure it reads your rc files.

**Comment by thunder-road** [comment]
Awesome that did the trick ! Thanks very much.
