### ISSUE TITLE
Variable referencing in config

### ISSUE THREAD

**Issue by amanjitsk** [kovidgoyal/kitty#2013]
This might be a silly question, but is there a way of referencing variables in the config ?
For example, I'd like to define `active_border_color` to be equal to the value of the variable `color3`. Is this currently possible ? I'd like to avoid hard-coding as I use pywal to configure colors dynamically, and would like to able to style the border colors based on that.

Best,
Amanjit

**Comment by kovidgoyal** [comment]
Not directly, but you can use the include directive which supports
environment variables to dynamically include conf files.
See https://sw.kovidgoyal.net/kitty/conf.html
