### ISSUE TITLE
Keyboard key is falsely recognized as being pressed

### ISSUE THREAD

**Issue by m-rey** [kovidgoyal/kitty#2014]
## steps to reproduce
1. open two kitty terminals, side by side
2. move your mouse over the first terminal, focusing it
3. hold down a keyboard key
4. while still pressing the key, move the mouse away from first terminal to second terminal, focusing the second terminal
5. release the key while being in the second terminal. Now no key is currently being pressed
6. move the mouse back to the first terminal, focusing it
-> the previously held down key is being printed and thus recognized as pressed, even though no key is being pressed.

**Comment by kovidgoyal** [comment]
I cannot replicate on X11 using those steps with

kitty --config NONE -o focus_follows_mouse=y

**Comment by Luflosi** [comment]
I cannot replicate on macOS with the same command line options.

**Comment by m-rey** [comment]
using swaywm (wayland) and kitty 0.14.4

**Comment by kovidgoyal** [comment]
Ah Wayland. Yeah that is a limitation of Wayland's design. In
Wayland there are no key repeat events. So glfw runs a timer to
simulate key repeat. If you release the key on another window then there
is never a release event to stop the timer in the first window. And so
it keeps going. I suppose one could workaround it by also killing the
timer when the window loses focus, but then that means you cannot mouse out
and mouse back with a key pressed and expect the repeat to continue.

**Comment by kovidgoyal** [comment]
@emersion any hints on what the correct way to do this in wayland is, if there even is one?

**Comment by alexandergraul** [comment]
@kovidgoyal I don't know how it is done, but GNOME Terminal handles this correctly on Wayland

**Comment by kovidgoyal** [comment]
yeah killing the timer on focus loss is the obvious thing to do, but it means that if you keep a key pressed and your mouse happens to stray off the window for a second, boom key repeating stops working. This does not happen on other platforms. So I would hope wayland has some way to actually implement it correctly as is done on all other platforms, but maybe I am being optimistic.

**Comment by emersion** [comment]
>If you release the key on another window then there
is never a release event to stop the timer in the first window.

Clients should release all keys when the `wl_keyboard.leave` event is sent.

**Comment by kovidgoyal** [comment]
On Mon, Sep 30, 2019 at 04:06:52AM -0700, Simon Ser wrote:
> >If you release the key on another window then there
> is never a release event to stop the timer in the first window.
> 
> Clients should release all keys when the `wl_keyboard.leave` event is sent.

I guess that means, if your mouse strays off the window accidentally and
you have focus_follows_mouse, key repeat is going to stop on Wayland,
unlike all other platforms.

**Comment by emersion** [comment]
No, it will work, just like on other platforms.

If you have focus_follows_mouse and move the mouse accidentally, it'll change the keyboard focus, just like on X11.

**Comment by kovidgoyal** [comment]
On Mon, Sep 30, 2019 at 04:15:34AM -0700, Simon Ser wrote:
> No, it will work, just like on other platforms.
> 
> If you have focus_follows_mouse and move the mouse accidentally, it'll change the keyboard focus, just like on X11.

See above. On X11 with focus_fllows_mouse you can move the keyboard to
another window and move it back and the repeat events will continue.
Same on macOS. Only on wayland will that scenario cause them to stop.

**Comment by emersion** [comment]
The `wl_keyboard.enter` event contains the set of pressed keys. You can restart the timers there.

**Comment by kovidgoyal** [comment]
On Mon, Sep 30, 2019 at 05:30:50AM -0700, Simon Ser wrote:
> The `wl_keyboard.enter` event contains the set of pressed keys. You can restart the timers there.

Interesting, thanks. I can use that to check if the key being repeated
is still pressed and restart timer accordingly.
