### ISSUE TITLE
System-wide environment variables on Mac OS are a pain

### ISSUE THREAD

**Issue by KevinSjoberg** [kovidgoyal/kitty#2015]
First of all I'd like to thank you for the immense effort you've put into kitty, @kovidgoyal. I truly appreciate all work you've put in.

Browsing previous issues, it's clear that kitty uses system-wide environment variables and not variables set by your given shell. It's also clear, that Mac users have a really hard time setting system-wide environment variables and most often that not, it's a result of hacking together something with a launch agent. The solution also seem to be different depending on what version of Mac OS you're running and each solution usually come with some caveats.

Preferably, running `kitty @ new-window <cmd>` would yield an environment equal to the one you're currently in. If you can't/won't set system-wide environment variables you could specify specific environment variables in your `kitty.conf`. This is also not ideal due to the fact you're having to keep both your shell  configuration and `kitty.conf` declarations up-to-date.

I know workarounds have been introduced in the past, e.g., reading environment variables from the login shell for the `EDITOR` value and it got me thinking we perhaps could do something similar for `PATH`?

Perhaps I'm glancing over some vital pieces here, making this a no-go. But I thought it might be worth raising the question.

**Comment by kovidgoyal** [comment]
Simply maintain your environment variables in kitty.conf, then you dont
need to set them in your shell rc files. And they will work everywhere.
As long as you use kitty as your terminal emulator. And you are not
sshing into your box.

Or put them in /etc/launchd.conf which will have similar effects, as
long as you run kitty using launch services.

Running a shell on every kitty startup to get env vars is an awful hack,
that I want to avoid as much as possible. The proper solution is of
course to get Apple to define a central place for system wide env vars
that is not tied to launch services. But, this being Apple, I would not
hold my breath.

And if your particular issue is env vars in a new window, simply use

bash --login -c "<cmd>" as the command to run in the new window, which
will automatically setup env vars for you.

**Comment by KevinSjoberg** [comment]
@kovidgoyal I guess one of the big differences is that setting the environment variables inside `kitty.conf` only solves one part of the problem. Anything run by the login shell, e.g., scripts and so on, would not be present. This wouldn't be the case on a UNIX-system I believe?

**Comment by kovidgoyal** [comment]
Well, put them in /etc/launchd.conf and they should be present in the
login shell as well as all kitty instances, since kitty itself is
launched via launch services and any sub-command will inherit its
environment.

**Comment by basbebe** [comment]
> Well, put them in /etc/launchd.conf and they should be present in the
> login shell as well as all kitty instances, since kitty itself is
> launched via launch services and any sub-command will inherit its
> environment.
> 

This doesn’t seem to work in newer versions of Mac OS any more.
