### ISSUE TITLE
Clipboard Size Limit?

### ISSUE THREAD

**Issue by Integralist** [kovidgoyal/kitty#2017]
I use tmux and have the following clipboard configuration...

```
# ~/.tmux.conf
bind-key -T copy-mode-vi 'y' send -X copy-pipe "kitty +kitten clipboard"

# ~/.config/kitty/kitty.conf
clipboard_control write-clipboard write-primary no-append
```

This works fine but I've noticed that if I try to copy a _large_ chunk of the screen, then I hear a 'beep' from the terminal and it will have _not_ copied anything until I select a smaller range to copy.

I checked in the `kitty.conf` to see if there was a hard limit defined for copying data to the clipboard but I couldn't find anything.

Any ideas on how to increase the clipboard buffer size?

**Comment by kovidgoyal** [comment]
There is no size limit for the clipboard buffer. There is a size limit
for any escape code, including the ones used for clipboards, which is
why I modified the clipboard protocol in the first place. 
https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard

so the only way this will work is to get tmux to support it or ditch
tmux.
