### ISSUE TITLE
Kitty(?) outputs gobbledigook when quitting vim (sometimes)

### ISSUE THREAD

**Issue by tsujp** [kovidgoyal/kitty#2018]
Apologies for the heinous title I didn't know how else to title this.

I've noticed since swapping to Kitty that sometimes when I am done with a file in vim and I either `:wq` or `:q` or `:q!` out of it that I will get the following in my next prompt such that the next prompt is `foo@location ~ $ <this string of stuff>`.

![img](https://i.imgur.com/IjX7Uiq.png)

It only happens sometimes, and whenever it happens I make a mental note "remember if you're pushing anything next time you exit vim" but then it takes a while before it crops up again and by that time I've forgotten my mental note.

I assume this is Kitty as it hasn't happened with any other terminal I've used, I wonder what it could be or if anyone has any insight unless this is a bug.

Please let me know what further information I can provide.

**Comment by kovidgoyal** [comment]
First make sure TERM is xterm-kitty and not something else. That
gobbelydook is a DCS control sequence which kitty will send is eom
program running inside it requests terminfo data from it. IIRV vim does
so in various circumstances. For whatever reason it is not sticking
around long enough to read the response, so it bleeds into the shell
instead. Bisect your vimrc/plugins to find the culprit.

**Comment by tsujp** [comment]
It's likely coming from vim-material since this is all my .vimrc is, I shall continue investigating though

```vimrc
syntax enable
set tabstop=2
set softtabstop=2
set expandtab
set number
set showcmd
set showmatch

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'hzchirs/vim-material'

call plug#end()

" Palenight
let g:material_style='palenight'
set background=dark
colorscheme vim-material
```
