### ISSUE TITLE
Ligature rendering is broken

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#2019]
4369255a25b0edd2dc8488321e5fd55c07fc9120 broke ligature rendering.
Before:
![before](https://user-images.githubusercontent.com/15217907/65977632-947aef00-e472-11e9-93ca-60c241438c29.png)
After:
![after](https://user-images.githubusercontent.com/15217907/65977641-9b096680-e472-11e9-97c5-b2376299b8f2.png)

**Comment by kovidgoyal** [comment]
Works for me with Fira Code what font is that with? And post the actual text file you are using.

**Comment by Luflosi** [comment]
Minimal kitty.conf:
```
symbol_map U+21,U+23,U+24,U+25,U+26,U+28,U+29,U+2a,U+2b,U+2d,U+2e,U+2f,U+3a,U+3b,U+3c,U+3d,U+3e,U+3f,U+40,U+5b,U+5c,U+5d,U+5e,U+5f,U+7b,U+7c,U+7d,U+7e,U+2713 Fira Code
```
Test file:
```
==  ==  a
=== === a
!== !== a
<=  <=  a
```

**Comment by Luflosi** [comment]
`font_family Fira Code` will not show the issue, for some reason only `symbol_map` does.

**Comment by Luflosi** [comment]
Awesome, that fixed it, thank you.
I also had a problem where the ~ would be rendered a bit to the right, which no longer happens with your fix.
