### ISSUE TITLE
Line wrapping issues with two-line PS1 Prompt

### ISSUE THREAD

**Issue by hughesjs** [kovidgoyal/kitty#2023]
My PS1 prompt spans two lines:

`PS1='\[\033[0;32m\]\[\033[0m\033[0;32m\]\u\[\033[0;36m\] @ \[\033[0;36m\]\h \w\[\033[0;32m\]$(__git_ps1)\n\[\033[0;32m\]└─\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\] ▶\[\033[0m    \] '`

It has the hostname, full path and the current git branch on line one, then an arrow on line 2, which is where I type my commands.

If typing a command that is longer than one line, rather than wrapping to the next line, kitty wraps to the start of the same line, overwriting the characters that I've already typed. This is only a display issue, the command still executes correctly.

I'm using Kitty 0.14.6 on Arch with Kernel 5.3.1.

**Comment by kovidgoyal** [comment]
Wrapping mode is entirely independent of prompts. Make sure you have not
changed TERM to be anything other than xterm-kitty.

**Comment by hughesjs** [comment]
I can confirm I've not changed this. It should be noted that if I go at fill a second line's worth of text it then starts to wrap correctly.

**Comment by mighty9245** [comment]
hello, could you confirm that you are still able to reproduce the issue? if yes, then are you able to reproduce the issue if you replace `$(__git_ps1)` with static text like `git thingy`?

**Comment by kovidgoyal** [comment]
It definitely does not reproduce with static text for __git_ps1 so most likely this is caused by formatting codes in __git_ps1 that are not wrapped in ```\[ \]``` pairs

**Comment by mighty9245** [comment]
that was what i wanted to tell him about. i just saw his unresolved issue before creating my own one, so i decided to help him after resolving my own issue. sharing is caring :)

**Comment by kovidgoyal** [comment]
yeah cool, thanks :)

**Comment by jrood** [comment]
I had this issue and the fix in my case was to use named colors like `%F{cyan}` instead of `\[\033[0;36m\]`
