### ISSUE TITLE
kitty@new-window with fixed size 

### ISSUE THREAD

**Issue by timescam** [kovidgoyal/kitty#2024]
When I open a new window in kitty (let say icat, for showing album covers), after I resize the os window, kitty would resize all windows according to the layout biases.

Is it possible to set a fixed size window in kitty, with something like `kitty@new-window --size x y` in the future?

Kitty is pretty successful at getting me to ditch tmux, with this it would be perfect. Thank you for your work.

**Comment by kovidgoyal** [comment]
I dont really see how this would work. Remember that layout biases apply
to columns and rows. If you have one fixed size window, then all windows
in its column and row will have to have the same width and height
respectively. And whathappens if you have two fixed size windows with
different sizes in the same column and row?
