### ISSUE TITLE
icat --print-window-size "overflows"

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#2026]
Most of the time, kitty outputs the wrong window size: 

```bash
$ kitty icat --print-window-size
65535x65535
```
I've also seen it output the correct size, but that seems way more rare. Note that 65535 is the largest value an unsigned short can hold.  This bug initially came to light when I was trying to use the following code to calculate the screen size: 

```python

fd = sys.stdout
buf = array.array('H', [0, 0, 0, 0])
fcntl.ioctl(fd, termios.TIOCGWINSZ, buf)
```

Seemingly, I don't have any other problems when executing `kitty icat` commands.  I'm running Linux 5.3.4, on X11. I've tried both kitty 14.6, and building from `HEAD`.  I hope somebody else can reproduce.

**Comment by kovidgoyal** [comment]
Nope, never seen that. It looks like something is setting the window
size to -1. Are you running this command inside kitty or in another
terminal?

**Comment by rien333** [comment]
I'm running it inside kitty.

**Comment by rien333** [comment]
Somewhat ironically, if I run the command in [st terminal](https://st.suckless.org/) terminal, it does output the correct size.

**Comment by kovidgoyal** [comment]
Then I dont see how its possible. The only way I can think of is if
kitty is never initializing that data, but I dont see how that could be,
add some prints to set_geometry in window.py to check.

**Comment by rien333** [comment]
`current_pty_size` from `set_geometry` matches `tput lines` and `tput cols`, so that seems fine. I'm not sure which variables you currently think are culprits, but maybe this print information is informative:

``` python
def set_geometry(self, window_idx, new_geometry):
    ...
    self.geometry = g = new_geometry
    print(self.os_window_id, self.tab_id, self.id, window_idx, sg.xstart, sg.ystart, sg.dx, sg.dy, self.screen, *g[:4])
    set_window_render_data(self.os_window_id, self.tab_id, self.id, window_idx, sg.xstart, sg.ystart, sg.dx, sg.dy, self.screen, *g[:4])
```

Output:

``` python-console
1 1 1 0 -0.9835820895522388 0.9512195121951219 0.019402985074626865 0.1197339246119734 <fast_data_types.Screen object at 0x7f8b1d1c4010> 11 11 1324 416
```

I'm not totally sure what all values mean, but `sg.xstart` is always negative, maybe that's a problem?

**Comment by kovidgoyal** [comment]
Its the latter two values in currnt_pty_sz that matter here, lines and
cols are not important.

**Comment by rien333** [comment]
Okay, if I add `print(current_pty_size[-2:])` in `set_geometry` this (for instance) outputs `(676, 891)`. 

Running `xwininfo` on that same window gives me (not sure if this informative, again):

``` python-console
xwininfo: Window id: 0x1c0000e "xwininfo /home/rw/Devil/kitty"

Absolute upper-left X:  38
Absolute upper-left Y:  63
Relative upper-left X:  38
Relative upper-left Y:  63
Width: 710
Height: 932
Depth: 24
Visual: 0x10d
Visual Class: TrueColor
Border width: 3
Class: InputOutput
Colormap: 0x1c0000a (not installed)
Bit Gravity State: ForgetGravity
Window Gravity State: NorthWestGravity
Backing Store State: NotUseful
Save Under State: no
Map State: IsViewable
Override Redirect State: no
Corners:  +38+63  -2246+63  -2246-999  +38-999
-geometry 710x932+38+63
```

**Comment by kovidgoyal** [comment]
Then kitty is correctly setting the windows size, so I dont see how it
is possible that the ioctl is returning the wrong size. Just to double
check, and some prints to pty_resize in child-monitor.c to make sure
that the ioctl is being called with the correct values, these values
will have been passed in from window.py

**Comment by rien333** [comment]
I changed `pty_resize` to the following:
```c
pty_resize(int fd, struct winsize *dim) {
    while(true) {
        printf("%d\n", fd);
        printf("%hu %hu\n", dim->ws_xpixel, dim->ws_ypixel);
        printf("ioctl return code: %d\n", ioctl(fd, TIOCSWINSZ, dim));
        if (ioctl(fd, TIOCSWINSZ, dim) == -1) {
        ...
     }
     return true;
```

Which outputs:
```bash
(676, 891) # This is the print(current_pty_size[-2:]) in window.py
8
676 891
ioctl return code: 0
```

**Comment by kovidgoyal** [comment]
Then I'm afraid I dont see what kitty could possibly be doing wrong.
There is no other instance of TIOCSWINSZ in the kitty codebase. So it is
setting correct values. If I had to guess some program you are running
inside kitty, maybe in your shell config, or similar, is calling
TIOCSWINSZ use strace to figure out what it is.

**Comment by rien333** [comment]
Ah yes, my shell seems the root of the problem. Running `kitty icat --print-window-size` from bash works, but it doesn't when run from fish. Thanks for your assistance! I suppose kitty can't do anything about this behavior of fish, so I might need to get in contact with the fish devs.

**Comment by ammgws** [comment]
@rien333 This appears to be fixed in the fish master branch. At least it works for me anyway.

**Comment by rien333** [comment]
Indeed! Thanks for bringing this to my attention.
