### ISSUE TITLE
Strange font rendering glitch with italic 'Q'

### ISSUE THREAD

**Issue by cloudhead** [kovidgoyal/kitty#2028]
Hey there, I'm seeing a strange rendering glitch with [Victor Mono][0], with the italic capital letter `Q`, as seen in this screenshot:

![image](https://user-images.githubusercontent.com/40774/66274804-76eac280-e882-11e9-896c-8675c7a6cf98.png)

The letter renders fine in [Alacritty][1] and Chrome, which leads me to believe it's an issue with Kitty.

Everything else renders perfectly.

One thing that is interesting is that the letter has the correct size (though there is overlap) when `font_size` is set to `38`, but no other size smaller than 38 seem to render the glyph correctly.

[0]: https://rubjo.github.io/victor-mono/
[1]: https://github.com/jwilm/alacritty

**Comment by cloudhead** [comment]
Here's how it looks in alacritty for reference:
![image](https://user-images.githubusercontent.com/40774/66274883-69820800-e883-11e9-93c2-046d14bc7092.png)

**Comment by kovidgoyal** [comment]
The font is buggy. The italic Q is wider than the cell size for all
other glyphs. Report it to the font's creators. https://sw.kovidgoyal.net/kitty/faq.html#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by cloudhead** [comment]
I see, thanks!
