### ISSUE TITLE
New configuration options

### ISSUE THREAD

**Issue by dtcyganok** [kovidgoyal/kitty#203]
* `underline_style` - `linear / curly`
* `tabs_position` - `top / bottom`
* `tabs_separator` - any symbol (`|`, `/`, `>`)
* `tabs_separator_color` - color in hex
* `active_tab_font_style` - `normal / bold / italic / bold-italic`
* `inactive_tab_font_style` - `normal / bold / italic / bold-italic`

**Comment by dtcyganok** [comment]
Is it possible to center text between the tabs separators?

**Comment by kovidgoyal** [comment]
There is no spare space to center. The tabs are exactly as wide as they need to be to show the titles.

**Comment by dtcyganok** [comment]
I see

`kitty  |kitty  |kitty  |`

instead

` kitty | kitty | kitty |`

Maybe tab names have spaces at end?

**Comment by kovidgoyal** [comment]
There is a trailing space to offset the separator if that's what you mean. Are you saying you want a leading space as well? If so, I dont agree, it's a waste of space.

**Comment by dtcyganok** [comment]
I propose trim trailing spaces and add option `tab_name_padding`

**Comment by kovidgoyal** [comment]
The ones I am interested in implementing have been implemented in the win branch. And there is no need add options to trim spaces/add padding. Simply remove the spaces from the separator.
