### ISSUE TITLE
Reature request: reload XCompose

### ISSUE THREAD

**Issue by timtro** [kovidgoyal/kitty#2032]
Is it possible to have a way to reload the user XCompose file? I play with mine _a lot_ because I edit a lot of documents (in neovim) with Unicode characters. I also run a lot of kitty windows that need to be restarted each time, adding a lot of overhead to adjusting my XCompose.

Thanks for your consideration.

**Comment by kovidgoyal** [comment]
kitty responds to switching of keyboard layouts, for which the server
sends an event. I dont think there is any event for changing XCompose
files, at least as far as I know. But if you know differently, patches
are welcome, relevant code is in xkb_glfw.c

**Comment by rysson** [comment]
Info.
If I open new kitty terminal window (shell command) is uses new `.XCompose`  as usual.
A bonus is – existing kitty reloads `.XCompose` too.
