### ISSUE TITLE
Support LS_COLORS flashing

### ISSUE THREAD

**Issue by tsujp** [kovidgoyal/kitty#2033]
I'm using Kitty with Bash and setting the following for orphaned symlinks in LS_COLORS `or=5;95;40` expecting to see a flashing orphaned symlink with a purple foreground and black background, I see all but the flashing – I cannot find the text "flash" or "ls_colors" in the docs; is flashing supported in Kitty?

**Comment by kovidgoyal** [comment]
No it is not, am not a fan of blinking text, gives me headaches.

**Comment by tsujp** [comment]
Would this be welcome in a PR with the default being `off`? If so, any guidance on where to specifically look as an entry for such a thing would be most helpful.

**Comment by kovidgoyal** [comment]
No, besides being something I personally dislike, it would impose a
fairly large overhead in terms of code complexity/performance. In order
to implement this the event loop would basically have to tick ever
second or whatever just in case there is blinking text. Or alternately
one would have to somehow keep track of when there is blinking text on
the screen.

**Comment by tsujp** [comment]
That's a valid point actually, I'd agree that performance outweighs what is comparatively a subjective minor convenience.
