### ISSUE TITLE
`window_padding_width` and `window_margin_width` not affecting tabs

### ISSUE THREAD

**Issue by tsujp** [kovidgoyal/kitty#2034]
*I accidentally hit enter while typing the title, updating issue text now.*

I've seen this issue: https://github.com/kovidgoyal/kitty/issues/584

And have `window_padding_width 10` in my kitty.conf yet the tabs don't follow the padding (they are flush against the top edge instead of 10 pixels inset)

![img](https://i.imgur.com/ISRg2xu.png)

**Comment by kovidgoyal** [comment]
Those setting apply to individual windows. tabs are not part of any window. So you will see that padding between the tabs and a kitty window, not between the tabs and the border of the OS window

**Comment by kovidgoyal** [comment]
Oh and #584 refers to tab_margin_width a different setting

**Comment by tsujp** [comment]
Ah I see, so there is no way currently to specify padding/margin for the tab bar itself?

`tab_bar_margin_width` is nice for horizontal inset but vertical would be nice too to give it a bit of spacing from the edge of the OS window, perhaps a `tab_bar_margin_height` property?

**Comment by kovidgoyal** [comment]
Not something I need personally, but patches are most welcome. Should be
similar to the patch for the horizontal margins.

**Comment by tsujp** [comment]
I'll explore the code when I have some time then and make a PR :)
