### ISSUE TITLE
Kitty can't handle UTF-8 characters when passing the directory option: surrogates not allowed

### ISSUE THREAD

**Issue by jorgicio** [kovidgoyal/kitty#2038]
Hi! I'm trying Kitty on Gentoo (Kitty version: 0.14.6). When I want to pass the `--directory` option with a name with UTF-8 characters, it fails.

This happens:

```
hackenherr:~ jorgicio% kitty -d=Imágenes                                                                                         [18:31:12]
[282 18:31:16.740854] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 338, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 331, in _main
    run_app(opts, args, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 149, in run_app
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 134, in _run_app
    boss = Boss(window_id, opts, args, cached_values, new_os_window_trigger)
  File "/usr/bin/../lib64/kitty/kitty/boss.py", line 138, in __init__
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/usr/bin/../lib64/kitty/kitty/boss.py", line 158, in add_os_window
    tm = TabManager(os_window_id, self.opts, self.args, startup_session)
  File "/usr/bin/../lib64/kitty/kitty/tabs.py", line 401, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/usr/bin/../lib64/kitty/kitty/tabs.py", line 72, in __init__
    self.startup(session_tab)
  File "/usr/bin/../lib64/kitty/kitty/tabs.py", line 82, in startup
    self.new_special_window(cmd)
  File "/usr/bin/../lib64/kitty/kitty/tabs.py", line 253, in new_special_window
    return self.new_window(False, *special_window, location=location, copy_colors_from=copy_colors_from)
  File "/usr/bin/../lib64/kitty/kitty/tabs.py", line 240, in new_window
    child = self.launch_child(use_shell=use_shell, cmd=cmd, stdin=stdin, cwd_from=cwd_from, cwd=cwd, env=env)
  File "/usr/bin/../lib64/kitty/kitty/tabs.py", line 232, in launch_child
    ans.fork()
  File "/usr/bin/../lib64/kitty/kitty/child.py", line 224, in fork
    pid = fast_data_types.spawn(exe, self.cwd, tuple(argv), env, master, slave, stdin_read_fd, stdin_write_fd, ready_read_fd, ready_write_fd)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 17-18: surrogates not allowed
```

![image](https://user-images.githubusercontent.com/554710/66522651-4e520b00-eac4-11e9-8e3f-c2e211c4d689.png)

Thanks.

EDIT: My `$LANG` variable:
```
hackenherr:~ jorgicio% echo $LANG                                                                                                
es_CL.utf8
```

**Comment by kovidgoyal** [comment]
Works fine on my Arch linux system, kitty comes up with the specified
directory, Imágenes

Steps I tried:

1) mkdir Imágenes
2) kitty -d Imágenes
3) kitty opens in the Imágenes directory

**Comment by Luflosi** [comment]
I tried the same steps on macOS and Fedora and also couldn't reproduce the issue.

**Comment by jorgicio** [comment]
Finally I found a workaround in order to escape the surrogates and turned it into a patch.
Tried here and working with lots of options.

https://gist.github.com/jorgicio/d094b673a99a721697bd8ee5e82f72cf

**Comment by kovidgoyal** [comment]
Why do you have surrogates in your command line arguments? Surrogates are
only needed if you have invalid unicode. Just dont do that.

**Comment by jorgicio** [comment]
That's the weird part: I can't find what a surrogate character is. The only "weird" character here is a tilde (in the example, in the "á" as in "Imágenes"). I don't know why it complains about that, unless I may not know a tilde is a surrogate character.

That's weird.

**Comment by kovidgoyal** [comment]
surrogates in python encoding are used when there are non-decodable
bytes. So whatever actual bytes you are using for that folder name are
not valid utf-8 representation of it, causing the error. See  https://www.python.org/dev/peps/pep-0383/

**Comment by jorgicio** [comment]
Ok, it makes sense, but that's the weird part, I insist: There are no surrogates character in Spanish accents (at least in folder names I used). But Python (or Kitty or whatever) interprets them as surrogates and I don't know why.

Also, I had to change the `LANG` variable to `es_CL.UTF-8` and without that patch, the error is still the same. Tried with all possible UTF-8 characters I could.
