### ISSUE TITLE
Kitty starts up with the wrong dimensions and confuses programs

### ISSUE THREAD

**Issue by MichaelAquilina** [kovidgoyal/kitty#2039]
I am using a tiling manger (sway). This means that sway determines what size kitty will be regardless of what is set for `remember_window_size`.

This unfortunately causes an issue in kitty for determining the terminal dimensions when executing kitty with a program. For example `nmtui`: 

![2019-10-09_23-02-23](https://user-images.githubusercontent.com/2650040/66523912-ed88f980-eae8-11e9-9c43-97fd9a5a0905.png)

The issue becomes a bit more visible when you get kitty to launch with this script:

```
#! /usr/bin/env bash
tput cols
tput lines
sleep 2
tput cols
tput lines
sleep 100
```

The output is:

```
64
18
75
39
```

**Comment by kovidgoyal** [comment]
Sorry I dont see how that's an issue. Your terminal programs need to be
able to handle window resizes, if they cant do that, that is a bug in
the program. And kitty cant do anything about the window manager
deciding to resize the window.
