### ISSUE TITLE
Doesn't launch on OSX Catalina

### ISSUE THREAD

**Issue by evantravers** [kovidgoyal/kitty#2040]
I think it's related to that notarization policy they just introduced…

**Comment by evantravers** [comment]
https://developer.apple.com/developer-id/

**Comment by Luflosi** [comment]
That is the workaround I was talking about. Thank you for laying out the steps more clearly than I did.

**Comment by kovidgoyal** [comment]
As long as you dont download the dmg via safari and manually install it,
gatekeeper should not kick in. Use the installation script from
https://sw.kovidgoyal.net/kitty/binary.html and it should bypass
notarization. 

And I totally agree that notarization and paying Apple for the privilege
of distributing free applications that make their platform better is
total bullshit. 

That said, I already notarize calibre, which needs it since it is used by
less technically inclined people so cant point them to
workarounds/scripts. So maybe at some point I will add notarization to
kitty as well.

**Comment by rahulkp220** [comment]
Having issues downloading on MacOS Catalina.
```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8606  100  8606    0     0  10664      0 --:--:-- --:--:-- --:--:-- 10664
Using python executable: /usr/local/bin/python3
Checking for latest release on GitHub...
Failed to contact https://api.github.com/repos/kovidgoyal/kitty/releases/latest with error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>```

**Comment by Luflosi** [comment]
Very similar to #1485. Either wait until GitHub fixes it or try downloading the .dmg manually using the browser and using the workaround from https://github.com/kovidgoyal/kitty/issues/2040#issuecomment-540631916 for GateKeeper.

**Comment by strogonoff** [comment]
Kitty suddenly won’t launch no matter what. Also Catalina. Worked perfectly up until today. Rebooted, reinstalled, opened with right-click and silenced Gatekeeper. App icon will jump a few times and disappear.

**Comment by Luflosi** [comment]
Try opening the Console App and search for kitty. Maybe there are some helpful error messages.

**Comment by immackay** [comment]
Launching from the .app is broken for me with newest version - launching via terminal works fine.

Potentially relevant console messages:

```
Timed out waiting for shell to quit while reading shell environment
```

& 

```
Traceback (most recent call last):
  File "kitty/main.py", line 347, in main
  File "kitty/main.py", line 336, in _main
  File "kitty/main.py", line 270, in setup_environment
  File "kitty/main.py", line 245, in read_shell_environment
AttributeError: 'function' object has no attribute 'ans'
```

**Comment by strogonoff** [comment]
For me it failed from .app and via an Automator script (the latter is my regular way, not sure if that’s equivalent to launching Kitty from shell)

**Comment by immackay** [comment]
As far as I know, Automater uses `open` to launch applications, which would result in the same behavior as opening the .app.

I created a relevant issue for this in #2232 - already fixed in master!

**Comment by strogonoff** [comment]
> As far as I know, Automater uses `open` to launch applications, which would result in the same behavior as opening the .app.
> 
> I created a relevant issue for this in #2232 - already fixed in master!

You’re entirely right, and it’s great to see it fixed so fast!

**Comment by wd** [comment]
Can't launch kitty even operate as @ddnomad said. After select Open in step #4, there will be an kitty icon showed in dock, but after a splash, it will exit soon.

I tried to run kitty in Terminal.app, it will opened successfully.
