### ISSUE TITLE
window_border for single window

### ISSUE THREAD

**Issue by arkilho** [kovidgoyal/kitty#2043]
Kind Kovid Goyal and other contributors,
thank you for this great piece of software.
I apologize because this issue may likely be my fault in configuring.
I didn't found any other way like an official forum, to ask to.

I'd like to put the nice window border also for the first-launch single window. I mean the border that appears and works wery well when I press at least Ctrl+Shift+Enter.
The reason is that with the 16:9 aspect ratio, the vertical space is real-estate, and I wish to remove the useless windowmanager title bar, making use of the small kitty border to have evident window edge.

I tried changing many of the configuration options without any luck.

Could you please help me?
Thanks and regards.
Marco (arkilho)

**Comment by kovidgoyal** [comment]
I'm afraid kitty does not draw borders around single windows, for
exactly that reason, it would be a waste of space. I suggest you switch
to a window manager that does not insist on useless window chrome. I
personally use and recommend i3, but there are many such options.
