### ISSUE TITLE
Bold Font not work

### ISSUE THREAD

**Issue by arkhan** [kovidgoyal/kitty#2044]
Regards,

I have configured kitty to use the [Cascadia Code](https://github.com/microsoft/cascadia-code) font, it works quite well, but the bold font is not shown as you can see in the attached image, on the left is urxvt and on the right kitty.

![img-2019-10-10-154034](https://user-images.githubusercontent.com/3141865/66605052-f6271180-eb74-11e9-9963-176fec677610.png)

Is it a configuration parameter that must be parameterized?

Thank you

**Comment by kovidgoyal** [comment]
Does cascadia code have a bold variant? And use --debug-font-fallback to see what fonts kitty is using. you can use the the various font_family directives in kitty.conf to specify fonts for bold/italic etc. if they are not being automatically picked up

**Comment by damageboy** [comment]
@arkhan How did you get Cascadia code to work?

I can't seem to get it to render well on my Kitty...

Can you share the config?

**Comment by arkhan** [comment]
@damageboy sure,

```
font_family      Cascadia Code
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

remember_window_size  no
initial_window_width 100c
initial_window_height 30c

cursor #cccccc
cursor_text_color #111111
cursor_shape underline
cursor_blink_interval      0.0
cursor_stop_blinking_after 15.0

scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
wheel_scroll_multiplier 5.0

url_color #0087BD
url_style curly
open_url_modifiers kitty_mod
open_url_with default
copy_on_select yes

rectangle_select_modifiers ctrl+alt
select_by_word_characters :@-./_~?&=%+#

click_interval 0.5
mouse_hide_wait 3.0
focus_follows_mouse no

foreground #cfcfc2
background #000000

#: black
color0 #202020
color8 #31363b

#: red
color1 #c0392b
color9 #f44f4f

#: green
color2 #218058
color10 #27ae60

#: yellow
color3 #fdbc4b
color11 #fdbc4b

#: blue
color4 #2980b9
color12 #0099ff

#: magenta
color5 #8e44ad
color13 #af81ff

#: cyan
color6 #27aeae
color14 #31dddd

#: white
color7 #acada1
color15 #cfd0c2

```

**Comment by autoteelar** [comment]
same with me but default monospace idk why it worked on my old install not this
