### ISSUE TITLE
Cursor won't change in vim when in insert mode

### ISSUE THREAD

**Issue by DavBE** [kovidgoyal/kitty#2045]
Hi,

In Vim, the cursor won't change in insert mode in Kitty. I tried different combinations of 

let &t_SI = "\<Esc>[5 q"

in my .vimrc but the cursor will always be a block.

Any way to change this behavior ?

Regards,

David

**Comment by DavBE** [comment]
Oops wrong kitty sorry ^^

**Comment by rubenkharel** [comment]
Which is the right one then? I am having the same issue in kitty term emulator.

**Comment by trygveaa** [comment]
@rubenkharel: This works in kitty https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes#For_VTE_compatible_terminals_.28urxvt.2C_st.2C_xterm.2C_gnome-terminal_3.x.2C_Konsole_KDE5_and_others.29_and_wsltty

That is:

```
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
```

**Comment by psygo** [comment]
Somehow nothing seems to be working right now, related to this problem, on Kitty, and I've tried a dozen other solutions also. The cursor was working fine up to a few days ago, now it always stay in block mode.

**Comment by trygveaa** [comment]
@psygo: The vim config I posted still works fine for me. I get a beam cursor in insert mode in both kitty 0.20.3 and master.

**Comment by mlthlschr** [comment]
My problem was that somewhere in my `.zshenv` i manually set the `TERM` variable to the wrong value. After deleting this line kitty was able to show the correct cursors again :tada: Now `TERM` is set by the terminal when starting, in the case of kitty `xterm-kitty`. Maybe it helps.
