### ISSUE TITLE
Access Font Awesome unicode characters via unicode kitten

### ISSUE THREAD

**Issue by ghyatzo** [kovidgoyal/kitty#2048]
Hello,

I'm trying to add the font awesome icon pack to the list of unicode characters i can access via the unicode picker kitten.

I tried mapping the Font Awesome unicode range via symbol_map.
at the moment i have: 
`symbol_map U+f000-U+f2e0 Font Awesome`

I tried various variations of the font name, but still no luck.
`kitty list-fonts` doesn't show font awesome in the output (probably because it's not monospaced)
How can i make it work? (if i can at all)

**Comment by kovidgoyal** [comment]
In the code section of the unicode kitten, simply type the unicode code
in hex for the character you want. Using sympbol_map simply means the
font will be used to render those characters. it does not give the
characters names.

**Comment by ghyatzo** [comment]
I've already tried, the symbol doesn't show correctly, only an empty rectangle.
Besides, on the log i find "The font FontAwesome was not found, falling back to Menlo".

I can't seem to find the correct pointer to those symbols.

**Comment by kovidgoyal** [comment]
You need to figure out the correct name for the font and use that

**Comment by Luflosi** [comment]
Well, he wrote that `kitty list-fonts` doesn't show the font, so he won't be able to use it even if he has the correct name.
@ghyatzo see if https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font helps.

**Comment by kovidgoyal** [comment]
kitty list-fonts only applies to the main font. You can use anyfont for
fallack rendering regardless of it being monospace for not.

**Comment by Luflosi** [comment]
Oh, ok. I didn't know that.

**Comment by ghyatzo** [comment]
alright, font family name i was trying to use was an old one.
Fixed.
