### ISSUE TITLE
REUSE compliance

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#2050]
https://reuse.software makes the licensing information easily machine readable. REUSE is built on [SPDX](https://spdx.org/), which is used by the Linux kernel.
REUSE sounds like a good idea and I'd like to hear your opinion about it.

**Comment by kovidgoyal** [comment]
The license in the kitty repository is a byte-for-bye copy of the
standard GNU GPL v3, pretty much any machine that reads licenses, should
be able to recognize it, trivially.

**Comment by Luflosi** [comment]
Yes, that is correct. However the biggest feature of REUSE is that it makes the licensing information in every file easily machine readable. It also makes mixing licenses licenses easy. Currently to find out that GLFW is licensed under a different license requires looking at the GLFW files and recognising the license text as being the Zlib license. With REUSE all the licenses used in the project would be in the LICENSES directory and every file would have a machine (and human) readable license identifier. That way it is very obvious which licenses are used in the project, not just the main one and which license every file belongs to.

**Comment by kovidgoyal** [comment]
Seems like pointless beauracracy to me. Has anyone that would actually
make use of this information expressed an interest in it? With it on
would now have to remember to update some extra location apart from the
file header for licensing information And there become two sources of
truth. All in all seems highly inelegant. Better to just standardize
licensing comments in file headers.

On Sun, Oct 13, 2019 at 02:01:12AM -0700, Luflosi wrote:
> Yes, that is correct. However the biggest feature of REUSE is that it makes the licensing information in every file easily machine readable. It also makes mixing licenses licenses easy. Currently to find out that GLFW is licensed under a different license requires looking at the GLFW files and recognising the license text as being the Zlib license. With REUSE all the licenses used in the project would be in the LICENSES directory and every file would have a machine (and human) readable license identifier. That way it is very obvious which licenses are used in the project, not just the main one and which license every file belongs to.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/2050#issuecomment-541400495

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by Luflosi** [comment]
> Seems like pointless beauracracy to me.

Maybe. But the vast majority of files already have a copyright header, so it would be very simple to change these headers to be machine readable.

> Has anyone that would actually make use of this information expressed an interest in it?

Not that I know of. But there are a lot of tools for copyright review that get crazy complicated with hundreds of regexes and stuff like that just to mostly work but not always. Just take a look at this list from Debian: https://wiki.debian.org/CopyrightReviewTools. At least some of these tools can parse SPDX for copyright information.

> With it on would now have to remember to update some extra location apart from the file header for licensing information And there become two sources of truth. All in all seems highly inelegant. Better to just standardize licensing comments in file headers.

REUSE compliance can be checked automatically with sort of a linter. This could be integrated in the CI, making remembering not really an issue.
The REUSE specification does use a standardised format for file headers called SPDX. Unfortunately it is impractical/impossible to add file headers to some files, e.g. images. The REUSE specification has two possible solutions for this problem: Either create a file with the same name as the original, only with ".license" appended at the end and put the copyright information in there or to list the file in a central DEP5 file. You're right, that is an extra location that has to be updated for these sorts of files but there should never be two sources of truth. Files are also created very infrequently and the license information needs to be updated/changed even less frequently, so the effort required to maintain this should be fairly similar compared to what it currently is.

I would also like to add that it is currently not very clear at all if kitty is licensed under GPLv3-only or GPLv3+. There are at lest two distributions/package managers I found, that show kitty as being licensed under GPLv3+.

**Comment by kovidgoyal** [comment]
On Mon, Oct 14, 2019 at 12:43:33PM -0700, Luflosi wrote:
> > Seems like pointless beauracracy to me.
> 
> Maybe. But the vast majority of files already have a copyright header, so it would be very simple to change these headers to be machine readable.

Sure but it would take time, time better spent actually workingon
something that adds value to actual kitty users/developers.

> 
> > Has anyone that would actually make use of this information expressed an interest in it?
> 
> Not that I know of. But there are a lot of tools for copyright review that get crazy complicated with hundreds of regexes and stuff like that just to mostly work but not always. Just take a look at this list from Debian: https://wiki.debian.org/CopyrightReviewTools. At least some of these tools can parse SPDX for copyright information.

OK, still not a problem that interests me. I've never understood why
Debian is so fussy about individual file licenses. It should be up to
the project maintainer to ensure the licenses he uses are compatible
with the overall license. If it is not, why is that Debian's problem.
It's just busywork.

> 
> > With it on would now have to remember to update some extra location apart from the file header for licensing information And there become two sources of truth. All in all seems highly inelegant. Better to just standardize licensing comments in file headers.
> 
> REUSE compliance can be checked automatically with sort of a linter. This could be integrated in the CI, making remembering not really an issue.

Which means more wasted time/CPU cycles installing and running this
linter and possible breakage every time there is a bug in the linter.
Nothing in this world is free.

> The REUSE specification does use a standardised format for file headers called SPDX. Unfortunately it is impractical/impossible to add file headers to some files, e.g. images. The REUSE specification has two possible solutions for this problem: Either create a file with the same name as the original, only with ".license" appended at the end and put the copyright information in there or to list the file in a central DEP5 file. You're right, that is an extra location that has to be updated for these sorts of files but there should never be two sources of truth. Files are also created very infrequently and the license information needs to be updated/changed even less frequently, so the effort required to maintain this should be fairly similar compared to what it currently is.

I am OK with a PR to change the header license format to SPDX, but I am
not ok with maintaining copyright information in sidecar files. Any file
in the repo that does not have a copyright header can be assumed to be
under the overall LICENSE.

And I really dont want to waste CI time running linters for something of
so little utility.

**Comment by Luflosi** [comment]
> Which means more wasted time/CPU cycles installing and running this linter

True but to be fair, `reuse lint` runs in under a second on my MacBook Air from 2012 with a dual core 1.8 GHz Intel Core i5.

> And I really dont want to waste CI time running linters for something of so little utility.

I respect your argument.
<br>
> I am OK with a PR to change the header license format to SPDX

Ok, here is an example header:
```Python
# SPDX-FileCopyrightText: © 2019, Kovid Goyal <kovid at kovidgoyal.net>
#
# SPDX-License-Identifier: GPL-3.0-only
```
Would you like the `©` to be there or not? And do you prefer to have the empty line between the two other lines or not?
Is kitty licensed under GPL v3 only or GPL v3+? I don't think this is made clear anywhere.

**Comment by kovidgoyal** [comment]
On Sun, Oct 20, 2019 at 06:16:38AM -0700, Luflosi wrote:
> Ok, here is an example header:
> ```Python
> # SPDX-FileCopyrightText: © 2019, Kovid Goyal <kovid at kovidgoyal.net>
> #
> # SPDX-License-Identifier: GPL-3.0-only
> ```

Isn't there a single line version of this? Currently all that info is in
a single line. I hate large, mostly useless file headers, every time you
open a file you have to scroll past useless boilerplate.

> Would you like the `©` to be there or not? And do you prefer to have the empty line between the two other lines or not?
> Is kitty licensed under GPL v3 only or GPL v3+? I don't think this is made clear anywhere.

GPL v3, nowhere in kitty as far as I know is a reference ever made to
GPL v3+, so I dont know why anyone would assume that

**Comment by Luflosi** [comment]
> Isn't there a single line version of this?

Unfortunately not. There is only a two line version.

> so I dont know why anyone would assume that

Both [Debian](https://metadata.ftp-master.debian.org/changelogs//main/k/kitty/kitty_0.14.4-1_copyright) and [Void](https://github.com/void-linux/void-packages/blob/master/srcpkgs/kitty/template) mark kitty as being GPL v3+, so it seems to be not 100% obvious, that kitty is GPL v3 only.

**Comment by kovidgoyal** [comment]
On Mon, Oct 21, 2019 at 01:04:25PM -0700, Luflosi wrote:
> > Isn't there a single line version of this?
> 
> Unfortunately not. There is only a two line version.

Then I suggest keeping only the license information and removing
the copyright header. Or just ditching the enterprise, it really does
not seem worth the trouble. 

> 
> > so I dont know why anyone would assume that
> 
> Both [Debian](https://metadata.ftp-master.debian.org/changelogs//main/k/kitty/kitty_0.14.4-1_copyright) and [Void](https://github.com/void-linux/void-packages/blob/master/srcpkgs/kitty/template) mark kitty as being GPL v3+, so it seems to be not 100% obvious, that kitty is GPL v3 only.

And that flag was set by a human, which I doubt is going to be different
if the syntax of the license header is changed.
