### ISSUE TITLE
launch new program from command line

### ISSUE THREAD

**Issue by amanjitsk** [kovidgoyal/kitty#2051]
This maybe a ultra-silly question but I can't seem to get to launch kitty with the specified program.
For example, if I need to run `nvim` in the emulator `st`, then I just run `st -e nvim`. I can't seem to be able to do the same with kitty. How do I run programs in kitty from the command-line (not necessarily from within kitty, but also from other terminal emulators). 

P.S. Within kitty, I have no problem doing `kitty @ new-window nvim` and that pops a new kitty window with the desired program, but how I do a launch a `new-os-window` when doing so ?

**Comment by rien333** [comment]
`kitty htop` or `kitty emacs -nw` works for me (as in, it opens an os-level window with that programming running).

**Comment by amanjitsk** [comment]
That does not work for me, it just opens up the config specified by the `default_session` file. Now that I tried deleting that file, it works like a charm! So that essentially means that if I have a `default_session`, I would need to somehow override that ?

**Comment by kovidgoyal** [comment]
-o default_session=none
