### ISSUE TITLE
Line being "corrupted" when do search and movement in bash

### ISSUE THREAD

**Issue by vp1981** [kovidgoyal/kitty#2052]
Hello,
I only recently began to use kitty so don't remember when I started to see this strange behavior but when I do in bash the `C-r` (`search-reverse-history`) and press immediately after that any movement combination (either `C-e`, `C-a` or `C-b`) the line is "corrupted" (see screenshot image).

![screenshot](https://user-images.githubusercontent.com/287444/66712236-33d1a780-edcc-11e9-8034-4a13b18fc55e.png)

This in just in a plain kitty tab, the `TERM` is `xterm-kitty`, nothing fancy in `inputrc` (nothing concerning movement keys). I see the same "corruption" when do ssh on a host (in just bash) and do `C-r`, don't remember if the `C-r` alone "spoils" the line.

**Comment by barraponto** [comment]
See if this helps you https://github.com/kovidgoyal/kitty/pull/2066/commits/86b9814dac5cc4f10c541bc18d3d669eaef5fd30

**Comment by vp1981** [comment]
Hello,
@barraponto , thanks for hint but this would be redundant for my case. When I began to use kitty everyday I copied `xterm-kitty` to all hosts I ssh to. Besides this doesn't explain the local host problem(s?) and I think when I do ssh I only face the same problem but under different conditions.

**Comment by vp1981** [comment]
There might be a problem with bash/readline because I didn't see same behavior with zsh, though I didn't use zsh everyday.

**Comment by kovidgoyal** [comment]
I dont use bash so I'm not sure what I am supposed to be doing to reproduce, can you elaborate? I tried

kitty -c NONE bash

typed C-r and then C-e and was brought back to a bash prompt with ^E at the prompt.

A set of steps and a minimal bashrc to reproduce would help.

**Comment by vp1981** [comment]
@kovidgoyal , good point. May be I have a bit complicated bash configuration. I'll try to debug my bash configuration and report results.

**Comment by vp1981** [comment]
Ok, I didn't yet touch my configuration but tried to do the same steps in termite, alacritty and terminology (this is the only terminal I have) and all show the same behavior so this might be related with bash itself. Still investigating.

**Comment by kovidgoyal** [comment]
As I cannot replicate and it happens in multiple terminals, am going to assume this is not a kitty bug. Feel free to post if you have evidence to the contrary.

**Comment by vp1981** [comment]
Yeah, I found the problem, I overplayed too with colors in prompt and forgot to surround CSI with `\[\]` as bash manual strongly advises!

Sorry for noise.
