### ISSUE TITLE
How to run ` kitty +kitten ssh ...` for second-level servers in chain ?

### ISSUE THREAD

**Issue by collegeimprovements** [kovidgoyal/kitty#2053]
Hi Sir,
Thanks a lot for your work on kitty. It's super fast.

Provided we have two servers: 
- `jump_server` 
- `destination_server`

And `destination_server` can only be accessed from `jump_server`.

When I run ` kitty +kitten ssh username@jump_server` kitty works great. 
(e.g. `clear` command works.)

How can we run `kitty +kitty ssh username@destination_server` from our local-machine or from `jump_server` ? 
Currently when we run `clear` command we get `'xterm-kitty': unknown terminal type.` error.
This situation arises because we can't download `kitty` on `jump_server`.

**Comment by kovidgoyal** [comment]
You cannot. Instead copy the terminfo files manually, as described in https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by nertpinx** [comment]
With new enough ssh client you should be able to do `kitty +kitten ssh -J jump_server destination_server`.

**Comment by glebsam** [comment]
> With new enough ssh client you should be able to do `kitty +kitten ssh -J jump_server destination_server`.

does not work for me unfortunately

**Comment by nertpinx** [comment]
> > With new enough ssh client you should be able to do `kitty +kitten ssh -J jump_server destination_server`.
> 
> does not work for me unfortunately

Well, then I guess you can create an ssh tunnel `ssh -L localhost:12345:machine2:22 machine1` and then in another shell do `kitty +kitten localhost -p 12345`. (written from the top of my head, not tested).

**Comment by glebsam** [comment]
Yep, it seems to me will work. But my intention was to use the kitten as drop-in replacement for usual SSH command. Thanks for you answer, anyway!

**Comment by glebsam** [comment]
I have finally figured out what's wrong with my scenario. Issue #2779 helped me. Indeed, I used command 

```
ssh -At -J user@jumper.internal.com user@target-host.internal.com sudo su
``` 

Command `sudo su` is a key to the riddle: ssh kitten will only copy terminfo for user under which the connection was created, ignoring permissions elevation made by just a command (which seems a sane design decision).

**Comment by chapmanjacobd** [comment]
just in case people aren't aware you can install the terminfo files like so in many distros:

```
sudo apt install kitty-terminfo
```
