### ISSUE TITLE
BUG: goto indexed tab key map breaks after upgrading from 0.14.2 to 0.14.6

### ISSUE THREAD

**Issue by stephencheng** [kovidgoyal/kitty#2068]
Not sure if anyone else encountering the same issue here, I have key mapping like:
``` 
map ctrl+shift+1        first_window
```

It worked fine in 0.14.2, until I just upgraded to 0.14.6

**Comment by kovidgoyal** [comment]
Works for me with

```
kitty --config NONE -o "map=f1 first_window"
```

**Comment by stephencheng** [comment]
Ok, seems I have got something else messed up. I couldn't locate what wrong, but managed work around.

Thanks
