### ISSUE TITLE
Feature request: edit(vim) mode and copy/yank 

### ISSUE THREAD

**Issue by stephencheng** [kovidgoyal/kitty#2069]
In tmux, there is a feature that you can enter editing mode and vim key bindings are supported to do search, than you can do yank to copy to clipboard.

In iterm2, there is native support to do similar to do on screen selection of text and then copy to clipboard.

In kitty, it provides scrollback + hints, which pretty much doing the similar, but the hints feature is just not entirely matching the ability to do your own selection on screen.

Is this even possible to be implemented? and I found this is the last wish that make kitty perfect.

Thanks

**Comment by kovidgoyal** [comment]
Press ctrl+shift+h to open the contents of the kitty screen in any
program of your choice (defaults to less). And if you search a bit in
the issues you will find people using neovim for this task so you get an
actual full fledged editor to do your searching and selection in.
