### ISSUE TITLE
[Assets] Alternate Logo if you want it

### ISSUE THREAD

**Issue by stagfoo** [kovidgoyal/kitty#2072]
Hey, I have been enjoying the terminal so i wanted to create a new icon for it :)
There are 3 concepts, let me know if you like any and I will do a pull request for the assets
![](https://mir-s3-cdn-cf.behance.net/project_modules/1400_opt_1/462ed786863923.5da69ea308c2e.png)

**Comment by kovidgoyal** [comment]
Cool, thanks for the icons, I like the left and right ones. But, I kinda have a soft spot for the current one, I made it when my cat of 9 yrs disappeared, and it is associated with her for me. And while I am sure for many people a new icon would be cool, this is something I'd rather not change.

**Comment by aral** [comment]
@kovidgoyal I’m so sorry to hear about what happened to your cat. What an awesome way to honour her. :cat2: :two_hearts:

**Comment by kovidgoyal** [comment]
Thanks :) Her name was Lychee

**Comment by npielawski** [comment]
@kovidgoyal I really like this new set of icons and the current style does look old. I do think that the fact that you have an emotional connection to the current icon is wholesome and must be preserved. Do you think that a new logotype that also looks like your cat could ease the transition? We could have Lychee as the official mascot! :)

**Comment by kutsan** [comment]
Sorry for bringing this up but it would be better to have an icon like that the ones in https://cookicons.co IMO. As others say the current one looks old.

I'm just leaving my opinion here since this is a highly subjective topic.
