### ISSUE TITLE
Mapping set_colors is not working

### ISSUE THREAD

**Issue by strogonoff** [kovidgoyal/kitty#2076]
I have some custom mappings, and they work. However, mappings involving `set_colors` don’t seem to have any effect, like this one:

```
map kitty_mod+b set_colors -a ~/.config/kitty/Github.conf
```

I’m not sure whether I’m not using the correct syntax, or there’s an issue with mapping `set_colors` specifically.

I presume syntax should be correct, as I took existing mappings as a guideline, e.g.:

```
map kitty_mod+a>d    set_background_opacity default
```

Sending `set-colors` via remote control works.

**Comment by strogonoff** [comment]
To answer myself, the following works instead (and isn’t perceptibly slower):

```
map kitty_mod+d pipe none none kitty @ set-colors -a ~/.config/kitty/Github.conf
```

**Comment by kovidgoyal** [comment]
There is no set_colors action to map, that functionality is only
available via remote control.
