### ISSUE TITLE
Some applications (GNU Info, Profanity) do not work with TERM=xterm-kitty

### ISSUE THREAD

**Issue by HiPhish** [kovidgoyal/kitty#2077]
Some applications do not work when the `TERM` environment variable is set to the default value of `xterm-kitty`. For example Info complains `info: Terminal type 'xterm-kitty' is not smart enough to run Info`.

I can get them work by prefixing the command with `TERM=xterm-256color` and making an alias in my shell, but that is just a workaround, not a solution. I have not been able to find anything regarding this in the documentation.

Is there a solution, or should just just create an alias for every application I find not working? I am running Kitty 0.13.3 installed vial APT on Kubuntu 19.04.

**Comment by Luflosi** [comment]
`info` did not print any errors for me, when calling it with no arguments. Does it only print the error for you when you do something else with `info`?
Did you run these programs on your local machine or over ssh?

**Comment by HiPhish** [comment]
On my local machine, and it happens with and without arguments to Info. I get the same behavior on my home computer and my workplace computer (I am using the same setup on both).

**Comment by kovidgoyal** [comment]
No idea what profanity is but info works fine with kitty. I am guessing for some reason ncurses is unable to read the kitty terminfo files on your system. See if infocmp is able to output the kitty terminfo file when run. And try uninstalling the distro package and use the official kitty binaries instead.

**Comment by HiPhish** [comment]
Sorry, I should have posted a link to [Profanity](https://profanity-im.github.io/), it's a TUI chat client for XMPP (formerly known as Jabber). I am also getting problems in [Wine](https://profanity-im.github.io/).

>  I am guessing for some reason ncurses is unable to read the kitty terminfo files on your system. See if infocmp is able to output the kitty terminfo file when run.

I have attached my `infocmp` output: [infocmp.txt](https://github.com/kovidgoyal/kitty/files/3747724/infocmp.txt)

>  And try uninstalling the distro package and use the official kitty binaries instead.
I could try that as a last resort, but I prefer to have my software under package management. Usually I use [GNU Guix](https://guix.gnu.org/) as my secondary package manager if I want recent software, but for whatever reason anything that uses GLFW as a dependency and is installed via Guix crashes my entire system.

**Comment by kovidgoyal** [comment]
> >  And try uninstalling the distro package and use the official kitty binaries instead.
> I could try that as a last resort, but I prefer to have my software under package management. Usually I use [GNU Guix](https://guix.gnu.org/) as my secondary package manager if I want recent software, but for whatever reason anything that uses GLFW as a dependency and is installed via Guix crashes my entire system.

kitty does not use glfw as a dependency, it has its own forked version.
And I'm afraid I dont have the time to debug issues in builds I have not
created, such as distro packages. All I can tell you is that info works
fine with the official kitty binaries or kitty built from source.

Given that infocmp is able to pick up the kitty terminfo files I have no
idea what the issue with info on your system is, since at least on my
system it is linked against ncursesw just like infocmp, so should be
able to pick up terminfo files in just the same way.

**Comment by HiPhish** [comment]
> kitty does not use glfw as a dependency, it has its own forked version.

I just checked and GLFW is not listed as a dependency. I could have sworn that it used to be there, maybe they have changed it since. I'll try once more with the Guix version, and if it is still failing I'll just set up aliases for those applications that don't work (I just found that [weechat](https://weechat.org/) does not work either).
