### ISSUE TITLE
artifacts between terminal content and padding/margin space

### ISSUE THREAD

**Issue by mighty9245** [kovidgoyal/kitty#2079]
hello, i've noticed some artifacts to appear between terminal content and padding/margin space if you display an image (`kitty +kitten icat ...`, originally found while playing with `neofetch --kitty ...`).

this issue seems to be related to background opacity, because if background is fully opaque, i can't reproduce the issue. this issue also seems to be related to window geometry, because i can reproduce it only with specific window sizes.

displaying an image with `kitty +kitten icat ...` then opening and closing nano, `window_padding_width 12.0`, `background_opacity 0.8`:
![1571604674](https://user-images.githubusercontent.com/52252283/67166062-cd80f200-f394-11e9-8917-fe188f02f0a6.png)
displaying an image with `kitty +kitten icat ...` then opening and closing nano, `window_padding_width 12.0`, `background_opacity 1.0`:
![1571604972](https://user-images.githubusercontent.com/52252283/67166104-38cac400-f395-11e9-9f1a-3253160edb50.png)

kitty config: https://hastebin.com/raw/tenageyoqe

kitty 0.14.6
compton v.7.4
both from arch linux repositories (not aur)

**Comment by mighty9245** [comment]
i also noticed that in some transitions (when resizing a window, for example) margin space has different color/opacity, but i guess it may be related to compton

**Comment by mighty9245** [comment]
initially i thought there is only vertical lines, but as you can see there is a kind of frame around the image. according to the `xwininfo` utility, the window size is 1014x911 (1010x907 w/o borders, i guess they are included) and the image size is 1400x1273, window padding is set to 12 and background opacity to 0.8. i hope you will be able to reproduce the issue with this information
![123](https://user-images.githubusercontent.com/52252283/67417459-7ddb3a00-f5d1-11e9-83fd-b4ae78b9c1ef.png)

**Comment by Luflosi** [comment]
@mighty9245 can you try compiling kitty from source with the patch from #2214 applied and see if that fixes your issue?

**Comment by mighty9245** [comment]
@Luflosi, nah, the issue is still here. i would recommend you to play with terminal window geometry (resizing it and running the test) and you'll probably see that the issue is still here even with your patch.

btw i was playing with these lines adding -1 and +1 a while ago with no luck.
