### ISSUE TITLE
broken text wrapping

### ISSUE THREAD

**Issue by mighty9245** [kovidgoyal/kitty#2080]
if you reach the end of the line the string will overlap itself once and then start wrapping normally. also for some reason the string starts wrapping pretty early for the first time, leaving some space before the window border.
![1571595944](https://user-images.githubusercontent.com/52252283/67164191-94d71d80-f380-11e9-8047-54878ac64f1a.png)
![1571596037](https://user-images.githubusercontent.com/52252283/67164193-9bfe2b80-f380-11e9-8523-a1854c908539.png)

my kitty config can be found in my previous issue (except padding: i disabled it to see if it is the cause): #2079

**Comment by kovidgoyal** [comment]
This likely has nothing to do with kitty. Make sure your TERM variable is set to xterm-kitty. And try to run

kitty cat

and then try to reproduce the issue. If you can feel free to update this issue with the output of kitty --debug-config and I will take a look.

**Comment by mighty9245** [comment]
@kovidgoyal, looks like i found the root cause: it happens only if ps1 has colors.
![1571653808](https://user-images.githubusercontent.com/52252283/67198218-3c972e80-f407-11e9-9963-545f33e04abd.png) and i assume it has something to do with kitty.

p.s. my term variable is set to xterm-kitty

**Comment by kovidgoyal** [comment]
No it has to do with your shell. Use
```
\[\e[36m\]\h:\w\\$\[\e[0m\]
```

**Comment by mighty9245** [comment]
@kovidgoyal, it works fine now, thank you! i remember these escaped brackets but i lost my previous bashrc file where i used them so i decided to ignore them, but looks like they are important.
