### ISSUE TITLE
libcanberra dependency

### ISSUE THREAD

**Issue by berceanu** [kovidgoyal/kitty#2089]
When using the binary install script on a new Ubuntu 18.04 headless server instance, `libcanberra` is required as a dependency. As far as I can see this is related to the sound system, and while useful in a desktop install, pulls in a lot of useless dependencies on a server. Could it be made optional?

Also, a docker image would be useful for remote systems where users are not allowed to install anything.

**Comment by kovidgoyal** [comment]
What are you installing kitty on a headless machine for? The terminfo files? or the remote control facility? If the former you can ust copy the terminfo files, if the latter a bt of searching will find you a shell script that can talk the kitty remote control protocol in one of the issues here.

**Comment by berceanu** [comment]
Hey, thanks for the quick reply (and awesome work!).
I actually need to use the `icat` kitten over SSH (as well as diff), so that's why I'm installing it, as I am running python scripts on the server which generate `png` files.
