### ISSUE TITLE
Audible bell doesn't works

### ISSUE THREAD

**Issue by dtcyganok** [kovidgoyal/kitty#209]
OS: `Linux 4.13.12`
kitty: `0.5.0`

Visual bell works, but audio bell don't. Tested with `echo -e '\a'` and neovim.

**Comment by kovidgoyal** [comment]
Works for me on linux. In version 0.5.0 kitty simply writes \a to /dev/tty. So if you dont have a working pc-speaker then it wont work. In master it use XAudioBell.

**Comment by dtcyganok** [comment]
I have several terminal emulators installed. In others audio the Bell works fine. Maybe something from config file can influence?

**Comment by kovidgoyal** [comment]
Use master or wait for 0.6
