### ISSUE TITLE
XKB compose file error

### ISSUE THREAD

**Issue by rathod-sahaab** [kovidgoyal/kitty#2091]
```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN"
[297 12:47:07.413685] [glfw error 65544]: Failed to create XKB compose table for locale en_IN
```

Manjaro: 18.1.1
```
kitty --version
kitty 0.14.6 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
You are missing the XKB compose files for the locale you have chosen. Install
them and you will be fine.

**Comment by AIGeneratedUsername** [comment]
@rathod-sahaab I am sorry for touching an old thread, but could you please share how you added or installed this "XKB compose" something?

On start I have the same
```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_AG"
[061 20:51:42.093448] [glfw error 65544]: Failed to create XKB compose table for locale en_AG
ignoreboth or ignorespace present in bash HISTCONTROL setting, showing running command in window title will not be robust
```
I use Lubuntu 22.04

**Comment by T0nd0Tara** [comment]
To install more locales you can use the command `dpkg-reconfigure locales`. If it still doesn't work, you can try using the `utf-8` version.

i.e. run `export LANG='en_AG.utf8'` (add this line to `.bashrc` for it to persist) 

[This answer](https://askubuntu.com/a/1371980) helped me understand it a bit more
