### ISSUE TITLE
Sometimes Kitty takes too much RAM

### ISSUE THREAD

**Issue by RaitoBezarius** [kovidgoyal/kitty#2093]
For some strange reason I am not always to reproduce, when running software which can take a lot of RAM (e.g. Python), when closing them, the RAM is not freed.

But when I close the Kitty tab, the RAM is freed.

I'll try to come up with a minimal repro case, but I wonder if it makes sense or is it related to the GPU nature of this terminal.

**Comment by Luflosi** [comment]
My guess is that the RAM is used for the scroll back history when the programs produce a lot of output.
Try reducing [scrollback_lines](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.scrollback_lines) in `kitty.conf` and restart kitty.

**Comment by RaitoBezarius** [comment]
It makes sense, it might be just this as I have set it to 12M of lines…
Thank you. I'll close this except if this parameter does not solve the issue.

**Comment by Luflosi** [comment]
Also take a look at https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.scrollback_pager_history_size.
