### ISSUE TITLE
Changing from insert to command mode slow in Neovim w/ tmux on OS X

### ISSUE THREAD

**Issue by aknuds1** [kovidgoyal/kitty#2097]
First of all, thanks for making Kitty, I'm enjoying getting to know it!

I just installed Kitty for the first time today, on OS X 10.14.6. I'm using Neovim, under tmux, to edit files in it, and while it's in general going great, I notice that exiting from insert mode to command mode is more sluggish than in iTerm2. I estimate the time required to ~1 second. The behaviour seems to be the same with Vim.

I've noticed that the problem seems linked to tmux, as it appears fast if I run neovim outside of tmux.

Is there anything I can tweak to get rid of this sluggishness?

**Comment by aknuds1** [comment]
Closing for now, since it seems related to tmux instead.

**Comment by Luflosi** [comment]
Does this happen in Terminal.app as well or does it only happen in kitty?

**Comment by aknuds1** [comment]
@Luflosi Never mind, I did determine it's a tmux thing :) The reason is that tmux waits for 500ms by default after you hit Esc, in order to determine it's not a combination. I fixed it by putting the following in ~/.tmux.conf:

```
set-option -s escape-time 10
```
