### ISSUE TITLE
Does not exit until background tasks are finished

### ISSUE THREAD

**Issue by igor37** [kovidgoyal/kitty#2099]
Let's say I run a command in the background, like `sleep 30 &`. Now if I want to close the terminal immediately afterwards by using `exit`, Kitty will not close until the 30 seconds are over and the sleep process terminates. The expected behaviour would be that the window closes immediately as the sleep command will continue to run in the background anyway.

This is a problem especially when starting a script or program running in the background for an extended period, making it impossible to close the window via `exit`.

**Comment by kovidgoyal** [comment]
No that's not the expected behavior, that's broken ass behavior.
Terminal emulators should not exit when programs can still write to
their screens. But if you wish to enable this broken-ass behavior, feel
free to do so via the exit_on_child_death option in kitty.conf

**Comment by MultiCoreNop** [comment]
I tried Kitty today and ran into this issue, too. How does one set this option? Searching for `exit_on_child_death` in this repo did not return any results (besides this ticket). A helping hint would be very welcome. Thanks!

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death
