### ISSUE TITLE
Selecting from output that spans multiple lines breaks the content

### ISSUE THREAD

**Issue by arkilho** [kovidgoyal/kitty#2100]
From the terminal output, if you do for example:
```sh
cat ~/.ssh/id_rsa.pub
```
you have two or three rows on the output, based on the term width
But they're truly a single line of text..
If you select it and paste it to some authorized_keys it will not work, because **kitty output breaks the line!**

Obviously I do know about `ssh-copy-id`, but that's not the point
In the same scenario the good old rxvt don't break anything.

Is there tha chance to correct kitty about this issue?
Really, it's a dealbreaker!

Thanks.
Marco.

**Comment by kovidgoyal** [comment]
I cannot reproduce this issue. Copy/pasting text without newlines in
kitty, does not insert newlines.
