### ISSUE TITLE
More Weird font glitch with nerd font icons

### ISSUE THREAD

**Issue by damageboy** [kovidgoyal/kitty#2104]
Much like #550, I'm seeing some weird glitches between Alacritty and kitty:

Kitty:

![image](https://user-images.githubusercontent.com/125730/67669864-673f3500-f97b-11e9-989a-a4c9ca9a4cac.png)

Alacritty:

![image](https://user-images.githubusercontent.com/125730/67669926-83db6d00-f97b-11e9-97c6-98d5836120ea.png)

The unicode point in question here is:
\uE0BC

which seems to be magically missing a line of pixels in some magical way on its top row.

Is there something that could be done about this?

From the little I can tell, this is already a special handled case in [box_drawing.py](https://github.com/kovidgoyal/kitty/blob/f93b605b758f210b368c7b3585976aea52fab261/kitty/fonts/box_drawing.py#L180):
https://github.com/kovidgoyal/kitty/blob/f93b605b758f210b368c7b3585976aea52fab261/kitty/fonts/box_drawing.py#L180-L193

I've managed to "fix" this by replacing the `height - 1` with `height`...
But this looks too easy?
Am I missing something?
Would you like to get a simple PR for this?

BTW: Awesome project!

I've just started using Kitty and I absolutely love it!
I can't wait to start to seriously play with the graphical protocol!

**Comment by kovidgoyal** [comment]
Sure feel free to send a PR, probably all the bounds for the equations should be changed. So zero becomes -1, height -1 becomes height, width - 1 becomes width. Also check that there is no danger of out of bounds access because of these changes, that is check the fill_region function.

**Comment by bew** [comment]
This looks weird, are you running kitty from the master branch in your test?

I recently fixed those corner triangles to fix this issue (showned by #2006, fixed by #2074)

**Comment by bastienGranger** [comment]
Hey there I have a different but similar pb 

![Screenshot 2019-10-31 at 6 04 36 PM](https://user-images.githubusercontent.com/2982906/67969272-3ffd9780-fc09-11e9-94cf-2190757ed9ca.png)

**Comment by kovidgoyal** [comment]
no followup
