### ISSUE TITLE
kitty list-fonts in target font

### ISSUE THREAD

**Issue by ahh** [kovidgoyal/kitty#2107]
If feasible, it would be very helpful when choosing fonts if kitty list-fonts gave the font name in the actual font.  

Right now the least cumbersome way I can find to see what the fonts look like _in kitty_ is invoking kitty -o font_family='font name', which is rather unpleasant (for one thing I use a tiling window manager, which means opening new windows has a higher cost in ux terms.)

Being able to look at the list of available choices and immediately see them as they'd appear would be a very nice usability improvement.

Failing that, is it possible to change the font family of a running terminal? I saw https://github.com/kovidgoyal/kitty/issues/1436 which you closed, but you seemed to close that over the request for bitmap fonts; I am happy with my available choices but would like to switch between them in an already-open window.

**Comment by kovidgoyal** [comment]
How would kitty list-fonts display how different fonts look? It outputs
text. 

As for changing fonts in running kitty instances, that is not possible.
You can change font sizes, not font faces.
