### ISSUE TITLE
Unable to create more than two tabs in startup session

### ISSUE THREAD

**Issue by YorkZ** [kovidgoyal/kitty#2114]
The following is my session file:

```
title TARGET
launch ssh TARGET

new_tab PROJECT1
cd PATH/TO/PROJECT1

new_tab PROJECT2
launch bash
```

The tab TARGET and PROJECT2 were created successfully, but PROJECT1 was not created at all.

**Comment by kovidgoyal** [comment]
You need a launch for PROJECT1

**Comment by YorkZ** [comment]
That worked, thank you very much.
