### ISSUE TITLE
Preserving files and shmem for animated images

### ISSUE THREAD

**Issue by jacobroly** [kovidgoyal/kitty#2115]
In the documentation, it says that the terminal can - if displaying images - read raw pixel data from temporary files and shared memory objects, however, they are autodeleted by the terminal. If I wanted to display animated images or videos, wouldn't it be better to preserve them and reread instead of deleting and recreating them every frame? Is there an option to preserve them?

**Comment by kovidgoyal** [comment]
Use regular files instead of temp files or shared memory and the
terminal wont touch them. Indeed if you create a temp file and dont
pass the t key in the graphics command the terminal wont touch the file.
