### ISSUE TITLE
Large selection

### ISSUE THREAD

**Issue by jesk78** [kovidgoyal/kitty#2116]
I'm forced to select pretty large amounts of lines (thousands) into buffer or clipboard. Selecting a line and then moving the mouse up/down while not releasing the left-click, is a way too slow in terms of scrolling and can take minutes. I'm rather used to selecting the start of the text with left-click, releasing the mouse, pressing shift and then scrolling fastly to the end/start of my desired text to finally left click again to get the complete selection (done by most terminals). 

I'm doing this remotely, so I cannot use local hacks, but I need to have it in the clipboard or terminal buffer for being able to paste in some pty.

Any ideas on this?

**Comment by kovidgoyal** [comment]
Use the pipe feature to open the scrollback buffer in a program of your
choice such as a text editor like vim where doing fast selections should be
trivial without even needing to use the mouse at all.

https://sw.kovidgoyal.net/kitty/pipe.html 

For instance by default ctrl+shift+h will open in less and you can use
marks, as described here: https://unix.stackexchange.com/questions/109935/how-to-copy-multi-page-text-from-the-terminal-into-the-clipboard
to pipe the selection to clipboard.

**Comment by jesk78** [comment]
This means that I need server side clipboard support (eg. neovim has no native clipboard support) or I need to copy the text first locally.

**Comment by kovidgoyal** [comment]
What you dont need anything server side. I suggest you understand what I
am suggesting. Using pipe opens the contents of the screne in aprogram
running on your computer not the server. And there are tons of programs
that can copy to clipboard locally.

**Comment by Luflosi** [comment]
If some text is selected, kitty supports extending the selection using the right mouse button. Unfortunately this doesn't work if there is no selection visible on screen (because it was scrolled out of view). I'm looking into improving this. If I were to fix this, would this work for your use case?

**Comment by jesk78** [comment]
As I said you need to copy locally, too many iterations for my taste.

**Comment by jesk78** [comment]
> If some text is selected, kitty supports extending the selection using the right mouse button. Unfortunately this doesn't work if there is no selection visible on screen (because it was scrolled out of view). I'm looking into improving this. If I were to fix this, would this work for your use case?

That would be a great extension, I think it's also what most people are used, provides fast workflow and is basically terminal standard.

**Comment by Luflosi** [comment]
I hacked together a quick fix that appears to work. I don't yet understand why it works but feel free to use it while I haven't come up with a proper solution yet. You need to apply the patch to the source code and compile kitty from source to use this "fix".
```diff
diff --git a/kitty/screen.c b/kitty/screen.c
index 3b9a4620..c715c7ae 100644
--- a/kitty/screen.c
+++ b/kitty/screen.c
@@ -1537,8 +1537,8 @@ screen_update_cell_data(Screen *self, void *address, FONTS_DATA_HANDLE fonts_dat
 
 
 static inline bool
-is_selection_empty(Screen *self, unsigned int start_x, unsigned int start_y, unsigned int end_x, unsigned int end_y) {
-    return start_x >= self->columns || start_y >= self->lines || end_x >= self->columns || end_y >= self->lines || (start_x == end_x && start_y == end_y);
+is_selection_empty(UNUSED Screen *self, unsigned int start_x, unsigned int start_y, unsigned int end_x, unsigned int end_y) {
+    return start_x == end_x && start_y == end_y;
 }
 
 static inline void
@@ -1555,6 +1555,12 @@ selection_coord(Screen *self, unsigned int x, unsigned int y, unsigned int ydelt
     }
 }
 
+static inline void
+selection_coord2(Screen *self, unsigned int x, unsigned int y, unsigned int ydelta, SelectionBoundary *ans) {
+    y = y - ydelta + self->scrolled_by;
+    ans->x = x; ans->y = y;
+}
+
 static inline void
 full_selection_coord(Screen *self, unsigned int x, unsigned int y, unsigned int ydelta, FullSelectionBoundary *ans) {
     ans->x = MIN(x, self->columns - 1);
@@ -1570,6 +1576,14 @@ full_selection_coord(Screen *self, unsigned int x, unsigned int y, unsigned int
     else { *(left) = b; *(right) = a; } \
 }
 
+#define selection_limits_2(which, left, right) { \
+    SelectionBoundary a, b; \
+    selection_coord2(self, self->which.start_x, self->which.start_y, self->which.start_scrolled_by, &a); \
+    selection_coord2(self, self->which.end_x, self->which.end_y, self->which.end_scrolled_by, &b); \
+    if (a.y < b.y || (a.y == b.y && a.x <= b.x)) { *(left) = a; *(right) = b; } \
+    else { *(left) = b; *(right) = a; } \
+}
+
 #define full_selection_limits_(which, left, right) { \
     FullSelectionBoundary a, b; \
     full_selection_coord(self, self->which.start_x, self->which.start_y, self->which.start_scrolled_by, &a); \
@@ -1651,7 +1665,7 @@ apply_selection(Screen *self, uint8_t *data, SelectionBoundary *start, Selection
 bool
 screen_has_selection(Screen *self) {
     SelectionBoundary start, end;
-    selection_limits_(selection, &start, &end);
+    selection_limits_2(selection, &start, &end);
     return !is_selection_empty(self, start.x, start.y, end.x, end.y);
 }
```

**Comment by jesk78** [comment]
Cool, I will try it out.

**Comment by Luflosi** [comment]
Did the fix work for you? If so, I'll start making a proper fix soon.
