### ISSUE TITLE
borked ssh output

### ISSUE THREAD

**Issue by JackofSpades707** [kovidgoyal/kitty#212]
when $TERM is set to 'xterm-kitty' on some devices the output looks like this : 
![image](https://i.imgur.com/RtqTET5.png)

As you can see in the screenshot, setting $TERM to xterm fixes the issue, although it creates a new one with my favorite text editor, NeoVim as discussed here: #160 

Note : $TERM set to xterm-kitty seemingly shows no issues with my ubuntu VPS, it's only present on my archlinux ARM raspberry pi's

**Comment by kovidgoyal** [comment]
Not much I can do about that. All I can suggest is you make sure the kitty terminfo file is available on whatever server you are sshing into.

**Comment by kovidgoyal** [comment]
And just for completeness, here's a link from the arch wiki on how to copy over terminfo https://wiki.archlinux.org/index.php/Secure_Shell#.22Terminal_unknown.22_or_.22Error_opening_terminal.22_error_message
