### ISSUE TITLE
autokey snippets not sending shifted characters

### ISSUE THREAD

**Issue by xircon** [kovidgoyal/kitty#2122]
e.g. if I have a snippet ` | grep -i` when run in kitty I get ` \ grep -i`  if I try `@` I get `'` 

This is a UK keyboard, running Manjaro  Unstable, KDE.

**Comment by kovidgoyal** [comment]
I have no idea what autokey is, am guessing it is some unlovely hack
that uses XTEST for its functionality. If you want to define shortcuts to send
text to kitty, I suggest using either the builtin in send_text function
in kitty.conf or the kitty remote control interface,
https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by jimyhuang** [comment]
For someone struggling with this issue like me, here is some hint:
1. Filter hotkey settings in "autokey" using window filter. Hotkey setup in autokey will trigger whatever, even your script doesn't send any text, the hotkey still triggered. For that reason, kitty never catch correct key binding.
2. Use `kitty +kitten show_key kitty` to catch the real key you want.
3. Use kitty.conf to map keys that kitty show you.

e.g. Here is the sample that mapping alt+i to key end.
end key setting in autokey py file "end.py"
```
# Enter script code
keyboard.send_key("<end>")
```

end key json settings in autokey py file .end.json
You will see hotkey mapping with alt + i, but only effect on code and terminator window. 
```
{
    "type": "script",
    "description": "end",
    "store": {},
    "modes": [
        3
    ],
    "usageCount": 1,
    "prompt": false,
    "omitTrigger": false,
    "showInTrayMenu": false,
    "abbreviation": {
        "abbreviations": [],
        "backspace": true,
        "ignoreCase": false,
        "immediate": false,
        "triggerInside": false,
        "wordChars": "[\\w]"
    },
    "hotkey": {
        "modifiers": [
            "<alt>"
        ],
        "hotKey": "k"
    },
    "filter": {
        "regex": "^(code\\.Code|terminator\\.Terminator)$",
        "isRecursive": false
    }
}
```

kitty.conf settings here. I don't know why doesn't work with `\x1b[H` in VIM. But below will send "end" key correctly when press alt+i both in terminal and VIM .
```
map alt+i send_text all \x1bOH
```

Hope this will help someone one day. It took me hours to figure out.
