### ISSUE TITLE
macOS High Sierra emoji render as lines

### ISSUE THREAD

**Issue by bmcorser** [kovidgoyal/kitty#2123]
<img width="329" alt="Screen Shot 2019-11-10 at 18 08 00" src="https://user-images.githubusercontent.com/1449387/68548725-105c4580-03e8-11ea-94b4-b8eefa232cb9.png">

Not a tremendously important issue, but I don't see emoji being rendered by Kitty. I'm using the default configuration (modulo a few key mappings) and installed via the Homebrew cask.

**Comment by kovidgoyal** [comment]
Presumably your system has some incompatible emoji font installed.
Emoji's work fine in kitty on macOS with the default Apple emoji font,
use --debug-font-fallback to check what font is being picked up and
uninstall it and you should be fine.

**Comment by bmcorser** [comment]
I'm not a fan of Apple's colour emoji, so I replaced `/Library/Fonts/Apple Color Emoji.ttf` with the Noto monochrome emoji font file. However, it seems that macOS is selecting Helvetica.

Anyone else doing weird stuff with their fonts like me and seeing similar?

Debug output:
```
[315 19:57:55.488486] Preloaded font faces:
[315 19:57:55.488608] normal face: {'monospace': True, 'bold': False, 'italic': False, 'family': 'Menlo'}
[315 19:57:55.488647] bold face: {'monospace': True, 'bold': True, 'italic': False, 'family': 'Menlo'}
[315 19:57:55.488666] italic face: {'monospace': True, 'bold': False, 'italic': True, 'family': 'Menlo'}
[315 19:57:55.488698] bi face: {'monospace': True, 'bold': True, 'italic': True, 'family': 'Menlo'}
[315 19:57:56.097052] [PARSE ERROR] Unknown OSC code: 7
[315 19:57:56.226372] No render frame received in 0.250000 seconds, re-requesting at: 1.765544
[315 19:57:56.338813] [PARSE ERROR] Unknown OSC code: 7
[315 19:58:38.588555] [PARSE ERROR] Unknown OSC code: 7
U+1f607 emoji_presentation Face(family=Helvetica, full_name=Helvetica, postscript_name=Helvetica, path=/System/Library/Fonts/Helvetica.ttc, units_per_em=2048, ascent=16.9, descent=5.1, leading=0.0, point_sz=0.0, scaled_point_sz=22.0, underline_position=-1.7 underline_thickness=1.1) (new face)
The font chosen by the OS for the text: U+1f607 is Face(family=Helvetica, full_name=Helvetica, postscript_name=Helvetica, path=/System/Library/Fonts/Helvetica.ttc, units_per_em=2048, ascent=16.9, descent=5.1, leading=0.0, point_sz=0.0, scaled_point_sz=22.0, underline_position=-1.7 underline_thickness=1.1) but it does not actually contain glyphs for that text
```

**Comment by bmcorser** [comment]
Also to note, elsewhere in the OS (eg. in the browser) I do see emoji rendered in the Noto font, so Kitty must be doing something a bit differently `:/`

**Comment by bmcorser** [comment]
Following https://github.com/kovidgoyal/kitty/issues/707 I can render specific codepoints in Noto
<img width="257" alt="Screenshot 2019-11-11 at 20 40 59" src="https://user-images.githubusercontent.com/1449387/68619626-bdf05700-04c3-11ea-9b52-9200a5bb1f2d.png">
It would great to have some control over fallback fonts.

**Comment by kovidgoyal** [comment]
Just use symbol_map for the emoji codepoint range then no fallbacks will
be involved.

**Comment by steadysupply** [comment]
Yep, I used [`fonttools`](https://github.com/fonttools/fonttools) to print out all the codepoints offered by the Noto Emoji font as `symbol_map` lines eg. 
```
...
symbol_map U+2708 Noto Emoji
symbol_map U+2709 Noto Emoji
symbol_map U+270A Noto Emoji
symbol_map U+270B Noto Emoji
symbol_map U+270C Noto Emoji
...
```
Now I see more unexpected behaviour. When I use a light theme, the emoji glyph receives a light colour and appears to be anti-aliased as if it should appear on a dark background!
<img width="577" alt="Screen Shot 2019-11-12 at 09 51 59" src="https://user-images.githubusercontent.com/18679515/68661008-2249ff80-0532-11ea-9f19-f416dd5a6daa.png">
With a dark theme, the emoji renders the same way (I imagine) and looks correct.
<img width="567" alt="Screen Shot 2019-11-12 at 09 53 14" src="https://user-images.githubusercontent.com/18679515/68661122-52919e00-0532-11ea-9765-c3594f8d3778.png">
Perhaps related to https://github.com/kovidgoyal/kitty/issues/252?

**Comment by kovidgoyal** [comment]
If the font you are using has colored emojis then kitty has no control
over the color, it is set by the font. If it does not then the emoji
will be rendered as normal text in the same color as normal text is
rendered.

And you should use ranges for symbol_map for better performance rather
than individual code points.

**Comment by steadysupply** [comment]
Thanks for all your replies on my piffling (and closed!) issue ... :+1:

This is Apple's "Terminal" app happily changing the colour of a glyph that is rendered in white by Kitty.

<img width="445" alt="Screen Shot 2019-11-12 at 10 19 40" src="https://user-images.githubusercontent.com/18679515/68663096-00eb1280-0536-11ea-8a19-83680ad08953.png">

Is it that Kitty _chooses_ not to mess around with the colour of emoji glyphs in the way that Terminal does?

**Comment by kovidgoyal** [comment]
That's not a colored glyph. Terminal is not getting the glyph from the
same font as kitty is. A colored glyph looks like the emoji here https://www.bustle.com/articles/76283-why-are-emoji-yellow-an-exploration-of-default-options-and-arbitrary-color-choices

And if you really want to deep dive into the unicode standard, emoji
have two variants text presentation and emoji presentation. The former
is not colored the latter is. You can use emoji variation selectors to
switch between them, like this:
![emoji](https://user-images.githubusercontent.com/1308621/68670194-56ddab80-0572-11ea-9088-e8f6ffea9231.png)

Now each emoji has a default presentation which can be either text or emoji controlled by the standard. Terminal.app is incorrectly using the text presentation for the emoji rather than the emoji one. If you want to see kitty do that follow the emoji bu U+feof

**Comment by kovidgoyal** [comment]
Oh and I should note that the variation selectors may not work in the face of symbol_map since it hardcodes the symbol used for a particular codepoint.

**Comment by bmcorser** [comment]
(sorry for the slow reply, since this issue is closed, I'm not getting notifications of your replies!)

> Terminal.app is incorrectly using the text presentation

I've deleted the `Apple Color Emoji.ttf` font that comes with macOS, since I don't want coloured emoji interspersing my non-coloured text. I've replaced this file with [Noto Emoji](https://www.google.com/get/noto/#emoji-zsye) which as far as I can tell is a non-coloured emoji font.

Without the hardcoded `symbol_map` directives in Kitty's config, I see the lines reported initially (and font debug reveals that Noto Emoji is not selected as a feasible font for rendering emoji glyphs -- for whatever reason). In this case I see
<img width="258" alt="Screen Shot 2019-11-19 at 11 39 09" src="https://user-images.githubusercontent.com/1449387/69143715-897f2b00-0ac1-11ea-88fc-4b45b66b97a4.png">


With the hardcoded `symbol_map` directives, the Noto Emoji font is selected (since it's explicitly selected in Kitty's config) but for light themes I see
<img width="265" alt="Screen Shot 2019-11-19 at 11 40 02" src="https://user-images.githubusercontent.com/1449387/69143727-93a12980-0ac1-11ea-8167-ce2f07498b02.png">

Terminal.app manages to select Noto Emoji as a feasible font for rendering emoji, like this
<img width="477" alt="Screen Shot 2019-11-19 at 11 42 29" src="https://user-images.githubusercontent.com/1449387/69143828-d5ca6b00-0ac1-11ea-91a3-e509da7eb047.png">

**Comment by kovidgoyal** [comment]
OK I looked into it, and this is not worth the effort to fix for me.
Basically if you want to fix it figure out how to query if a glyph is
colored or not using some Core Text API (I couldn't find one with a
brief google). Then before line 494 in core_text.m insert the line

*was_colored = *was_colored && is_glyph_colored_in_font()

where you would need to implement the is_glyph_colored_in_font function.

**Comment by bmcorser** [comment]
I never want to use coloured glyphs (eg. the coloured Apple Emoji) so I have just re-compiled Kitty with the following patch, which seems to give the behaviour I'm looking for ...

``` patch
diff --git a/kitty/fonts.c b/kitty/fonts.c
index bb2f01f4..692c0c4b 100644
--- a/kitty/fonts.c
+++ b/kitty/fonts.c
@@ -703,6 +703,7 @@ render_group(FontGroup *fg, unsigned int num_cells, unsigned int num_glyphs, CPU

     clear_canvas(fg);
     bool was_colored = (gpu_cells->attrs & WIDTH_MASK) == 2 && is_emoji(cpu_cells->ch);
+    was_colored = false;
     render_glyphs_in_cells(font->face, font->bold, font->italic, info, positions, num_glyphs, fg->canvas, fg->cell_width, fg->cell_height, num_cells, fg->baseline, &was_colored, (FONTS_DATA_HANDLE)fg, center_glyph);
     if (PyErr_Occurred()) PyErr_Print();
```

... hopefully my hackery doesn't blow anything up for me later `:)`

**Comment by bmcorser** [comment]
PS: Thanks for Kitty!
