### ISSUE TITLE
Kitty crashes on open after driver change

### ISSUE THREAD

**Issue by klmunday** [kovidgoyal/kitty#2126]
after installing nvidia driver 340 on Fedora I can no longer open Kitty,
The error i'm getting is: `Unknown uniform in borders program: _main_pos_map_0[0]`

From what I can tell this is a duplicate of #456 however i'm having a problem following your suggestion of `"You can make it work by ignoring the sanity checks"`

```
~ ❯ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.4.0 NVIDIA 340.107
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL version string: 4.4.0 NVIDIA 340.107
OpenGL shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL ES profile version string: OpenGL ES 3.1 NVIDIA 340.107 340.107
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
    GL_EXT_separate_shader_objects, GL_EXT_shader_implicit_conversions, 
```

```
~ ❯ kitty --debug-gl
GL version string: '3.3.0 NVIDIA 340.107' Detected version: 3.3
[315 10:12:19.664792] Unknown uniform in borders program: _main_pos_map_0[0]
```

I have tried buidling from source but the problem persists. I appreciate any help in getting this to work, Thanks!

I have also tried building from source

**Comment by kovidgoyal** [comment]
You need to grep for that error message and comment out the line where it occurs to ignore the check.

**Comment by vegalou** [comment]
Update latest current NV driver v.390. It works for me.
