### ISSUE TITLE
--debug-config should identify secondary config files

### ISSUE THREAD

**Issue by Gestas** [kovidgoyal/kitty#2127]
I was troubleshooting an issue with a secondary config file specified via the `include` directive and found two minor usability issues - 

1. The output of `--debug-config` should include the path to any user specified config files.
2. The default `kitty.conf` file should include the `include` directive and an example.

If it would be accepted I can submit a pull request for these changes. Thoughts?

#### My environment details -
```
user@acomputer:~$ kitty --debug-config
kitty 0.14.3 created by Kovid Goyal
Linux acomputer 5.3.0-18-generic #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019 x86_64
Ubuntu 19.10 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/user/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background   Color(red=64, green=69, blue=82)
...
```

**Comment by kovidgoyal** [comment]
The include directive is documented right at the start of https://sw.kovidgoyal.net/kitty/conf.html
dont see much point in also adding a commented out version to the
default kitty.conf, but ok, no real harm either.

As for --debug-config printing out included conf files, sure, a PR is most
welcome. Note that include is recursive.

**Comment by Gestas** [comment]
That it was at the top of the docs is one of the things that lead to my confusion. When I specified the `include` directive at the top of the file it didn't take effect. When I moved it to the bottom it did. I'm guessing that when a directive is specified twice the "second" one is used.
