### ISSUE TITLE
Launch command from rofi/fzy in new window/tab

### ISSUE THREAD

**Issue by amanjitsk** [kovidgoyal/kitty#2128]
What what be the right way to launch a selected program in a new tab/window ? For example, I am trying to do something to the effect of 

```
map kitty_mod+shift+r new_window @ ssh $(list_some_ssh_hostnames | fzy)
```
so that I can dynamically select a server to ssh into, as opposed to defining custom keybinds for each server I need to ssh into. Similarly, running a selected program from rofi in a new tab or new window. 

Best,
Amanjit

**Comment by kovidgoyal** [comment]
See the docs for new_window. https://sw.kovidgoyal.net/kitty/conf.html#window-management

**Comment by amanjitsk** [comment]
I checked the docs, they dont help with integration with rofi/fzy , which is what I was trying to get at. For example, instead of ssh'ing into a specific server, i want to open up a list of servers that I can ssh into using rofi or dmenu and then run the selected program in the new window.

**Comment by kovidgoyal** [comment]
So write a script that runs your chooser of choice and then does the
desired action and launch that script using new_window
