### ISSUE TITLE
Weechat Mouse Support for Kitty

### ISSUE THREAD

**Issue by JackofSpades707** [kovidgoyal/kitty#213]
I'm uncertain if I should be making a bug report here or for weechat.

Either way, utilizing a mouse just types seemingly random characters 

Any mouse function results in similar output, sometimes the same output even though it's a different key which seems rather odd to me.

![image](https://i.imgur.com/Y46wsPt.png)

**Comment by kovidgoyal** [comment]
It's probably because weechat is using an obsolete mouse protocol. I have only tested the newest and oldest mouse protocols in kitty. See #167
