### ISSUE TITLE
How to open new window with current ssh session?

### ISSUE THREAD

**Issue by sergeda** [kovidgoyal/kitty#2130]
I wondering how it is possible to open new window using ssh session from current window?
I know it's possible because I did it once accidentally. But I can't find needed key bindings in the doc.

**Comment by kovidgoyal** [comment]
There is no such functionality. kitty knows nothing about ssh and as far
as as I know ssh has not functionality to clone sessions. The best that
could be done is add an action to kitty to open a new window using the
cmdline of the current foreground process. There is no built-in action
for it but you can script it easily using the remote control facility
https://sw.kovidgoyal.net/kitty/remote-control.html 

kitty @ ls

will give you the cmdline of the ssh session and kitty @ new-window can
use it.

**Comment by ethanabrooks** [comment]
@kovidgoyal This functionality is actually promised by [the ssh kitten](https://sw.kovidgoyal.net/kitty/kittens/ssh/#truly-convenient-ssh):

> Then, pressing F1 will open a new window automatically logged into the same host using the ssh kitten, at the same directory.

The problem is that it attempts to open the new window at the same directory as the _local_ machine, not the remote host. Is there some way to correct this?

**Comment by kovidgoyal** [comment]
If you use the ssh kitten it works automatically. Your new window will
open connected to the remote machine at the same directory on the remote
machine as the current window.

**Comment by ethanabrooks** [comment]
Sorry to bother you... I now seem to be unable to reproduce this issue. Everything seems to work fine.
