### ISSUE TITLE
Can interrupt signal be remapped?

### ISSUE THREAD

**Issue by grissius** [kovidgoyal/kitty#2134]
Many terminal offer remapping of interrupt signal, mapped by default to `ctrl+c`.
Is this possible in Kitty? I could not find it in docs nor source at a glance.

Since many terminal don't have smart copty or interrupt behavior #1286, some users, myself included, have gotten used to mapping interrupt on `ctrl+shift+c`.

```
kitty 0.14.6 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
Use send_text to send \x03 on ctrl+c in kitty.conf

**Comment by grissius** [comment]
@kovidgoyal Thanks for a prompt reply!
The closest (inpsired [here](https://github.com/kovidgoyal/kitty/issues/498#issuecomment-384955808)) I could get was using
```
map ctrl+shift+c send_text all \x03\\
```
Which somewhat works fine, but triggered on empty prompt without a running program to interrupt, it inserts `\` (it doesnt work without the additional slash at the end). Perhaps I am using `all` incorrectly or I should input the symbol differently?

**Comment by grissius** [comment]
I must have been doing something wrong, thanks for update. For future readers, remapping copy and interrupt:
```
map ctrl+shift+c send_text all \x03
map ctrl+c copy_to_clipboard
```
In `kitty.conf`

**Comment by FlorianZahn** [comment]
For nix users: you need to escape the `\`
``` nix
# Home Manager
programs.kitty = {
  enable = true;
  keybindings = {
    "ctrl+c" = "copy_to_clipboard";
    "ctrl+shift+c" = "send_text all \\x03";
  };
};
```
