### ISSUE TITLE
Alt-tab-ing away from Kitty makes Kitty last in the window select switch

### ISSUE THREAD

**Issue by MehdiSaffar** [kovidgoyal/kitty#2136]
Say you have Firefox and Kitty running and a bunch of other apps with windows.

I am in Kitty and Alt-tab to Firefox. The normal behavior with all the apps is that Alt-Tab a second time would bring me back to Kitty. But When I Alt-tab away from Kitty, I noticed that it changes its position/index to the very last one.

Apps:
**Kitty** - A - B - C - D - E - F 

Alt-tab away from Kitty:

Expected: A - **Kitty** - B - C - D - E - F
Actual: A - B - C - D - E - F - **Kitty**

This is annoying because many times I memorize which windows I will have when I Alt-Tab and I sometimes need to keep checking something between the terminal and whatever windows I have open frequently so I Alt-tab multiple times.

What could be the issue?

I am on Ubuntu 18.04 LTS with GNOME 3.28, Kitty 0.12.3

**Comment by Luflosi** [comment]
Your kitty version is from September 2018. Please try the latest release or even the git version to make sure that this hasn't been fixed already. See https://sw.kovidgoyal.net/kitty/#quickstart and choose between a binary install or compiling from source.

**Comment by MehdiSaffar** [comment]
I didn't notice that. Thank you @Luflosi, I will upgrade and check if the behavior is the same.

**Comment by MehdiSaffar** [comment]
Wow, upgrading to `0.14.6` seems to have fixed it. Didn't think this would be it. Thanks a lot

**Comment by Luflosi** [comment]
I'm glad, I could help.
