### ISSUE TITLE
[BUG] ssh kitten should support `-p` for port

### ISSUE THREAD

**Issue by webknjaz** [kovidgoyal/kitty#2137]
When I run
```console
kitty +kitten ssh -Y user@host -p11111 -v
```

I get
```console
Option -p cannot occur in the middle
```

I think this shouldn't be happening. I tried changing the args order and nothing helps.

**Comment by martinetd** [comment]
Just adding a space (`-p 11111`) will make it work, but I also believe the kitten shouldn't try to interpret anything and just pass things to ssh -- any reason not to just make the initial passthrough check on first arg only and pass the rest? that is how most wrapper handle command line args

**Comment by webknjaz** [comment]
Oh wow! This should've been documented somewhere...

**Comment by kovidgoyal** [comment]
The kitten cannot just pass through args to ssh, to understand why read the source code for it. Basically, args have to be split into what is meant to be interpreted by ssh and what is meant to run on the remote machine.
