### ISSUE TITLE
How to configure status bar to show realtime memory and cpu status?

### ISSUE THREAD

**Issue by thamaraiselvam** [kovidgoyal/kitty#2138]
is there any way to create a real-time status bar like iterm?
<img width="749" alt="Screenshot 2019-11-17 at 3 48 24 AM" src="https://user-images.githubusercontent.com/6559664/68999885-22a91880-08ed-11ea-8700-a099cd8d8e76.png">

**Comment by kovidgoyal** [comment]
No, kitty does not have status bars. If you are on X11 you can use it to efine your panel. https://sw.kovidgoyal.net/kitty/panel.html
