### ISSUE TITLE
Can't use external clipboard

### ISSUE THREAD

**Issue by olivatooo** [kovidgoyal/kitty#2142]
OS: `Linux 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux`

I can't use this external clipboard extension from gnome. I already read the kitty docs but don't helped me. 

![image](https://user-images.githubusercontent.com/15200079/69084888-eb895300-0a23-11ea-8b6d-5c80592077c6.png)

**Comment by kovidgoyal** [comment]
I dont know anything about clipboard extensions. What is preventing you using it?

**Comment by kovidgoyal** [comment]
no followup
