### ISSUE TITLE
Is it possible to render "underline" as a box surrounding the underlined text?

### ISSUE THREAD

**Issue by Asheq** [kovidgoyal/kitty#2150]
I would like to see something like this:
![image](https://user-images.githubusercontent.com/4657140/69380260-e49e5280-0c66-11ea-9afe-f741f2b30719.png)

(I think this image is from the editor, Sublime Text)

Thanks!

**Comment by kovidgoyal** [comment]
Sorry, no. This is not something I am interested in implementing.
