### ISSUE TITLE
Question: How to edit the default title in each tab?

### ISSUE THREAD

**Issue by ScrumpyJack** [kovidgoyal/kitty#2155]
How to I control the title of the tab?

tab_title_template {title}
but that the docs don't show how to create a template

`A template to render the tab title. The default just renders the title. If you wish to include the tab-index as well, use something like: {index}: {title}`

but that the docs don't show how to create a template

At the moment the tab title includes the username, command and hostname (if ssh), which is too long for me

**Comment by kovidgoyal** [comment]
The tab title by default comes from whatever window title is set by the
shell running inthe currently active window. If you want to change it,
that is where you should do it, i.e. in your shell config.

**Comment by kai-dg** [comment]
Is it possible to customize the templates a little more? I prefer to use Kitty, but Konsole helps make my tabs look more readable without needing to change the `$PS1` like in this screenshot: https://imgur.com/jIHegT2

Maybe like `{file}` for filename and `{cwd}` for cwd without $HOME

**Comment by kovidgoyal** [comment]
You dont need to change PS1 to set window and therefore tab titles.
Google for how to change terminal titles using prexec hooks in your
shell config, which will work with all terminals.
