### ISSUE TITLE
Mouse cursor disappears when going full screen in macOS Catalina

### ISSUE THREAD

**Issue by pgib** [kovidgoyal/kitty#2158]
I've noticed that since upgrading to Catalina, my mouse cursor disappears when I'm using kitty in full screen mode and then going back to a different space. Moving my mouse up to the far left corner where the Apple menu is and clicking a bunch of times usually brings it back, but it's not super fun to have to do. Using kitty 0.14.6 on macOS 10.15.1. Happens on multiple computers and only with kitty. Terminal.app doesn't do it and neither does iTerm 2.

**Comment by kovidgoyal** [comment]
Set mouse_hide_wait to zero in kitty.conf.

I think I am just going to change the default to zero for macOS as I am
sick of trying to find workarounds for every corner case on macOS,
especially given that the corner cases change with every macOS release.
