### ISSUE TITLE
libpng16 removes libfontconfig on Ubuntu 16.04

### ISSUE THREAD

**Issue by anchnk** [kovidgoyal/kitty#217]
On Ubuntu 16.04 LTS if you install  `libpng16-dev` it automatically removes `libfontconfig-1dev` so running `python3 setup.py build` will failed while checking env as fontconfig lib is missing. Trying to reinstall libfontconfig from package manager throw unmet dependencies error:

```
The following packages have unmet dependencies:
 libfontconfig1-dev : Depends: libfreetype6-dev (>= 2.1.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I am just trying to make it work on that configuration but I am not sure there's something that can be done in the project itself to fix this.

**Comment by kovidgoyal** [comment]
This looks very much like the package database on your install is broken. kitty compiles succesfully on travis with Ubuntu 14.04 let alone Ubuntu 16.04 https://github.com/kovidgoyal/kitty/blob/master/.travis.yml

I dont use Ubuntu so I cannot help with diagnosing the issue.

**Comment by FvD** [comment]
I have exactly the same problem as @anchnk and cannot get further in the install process on Ubuntu 16.04. For some reason `fontconfig` on this system is bound to `libpng12`. Maybe we just need to wait a few months until Ubuntu 18.04 comes out.

**Comment by kovidgoyal** [comment]
See the discussion here: https://github.com/kovidgoyal/kitty/commit/11b17c09ced4577f5c1464fe1d040bda22972c77

**Comment by FvD** [comment]
Thanks! That was it.

- Build [libpng16 from source](http://www.libpng.org/pub/png/libpng.html)
- Add missing [wayland packages](https://launchpad.net/ubuntu/xenial/+source/mesa) (`libegl1-mesa-dev` and `libwayland-egl1-mesa`)

And the build finishes without further issues. Thanks!
