### ISSUE TITLE
Tab indices in the detach_window "ask menu" are hidden by `hints` labels

### ISSUE THREAD

**Issue by rafikdraoui** [kovidgoyal/kitty#2174]
Assuming  `map kitty_mod+d detach_window ask` in the config, then entering the following keystrokes in sequence (create new tab, create new tab, detach window):

```
kitty_mod+t
kitty_mod+t
kitty_mod+d
```

we get to a menu looking like:

![detach-menu](https://user-images.githubusercontent.com/767223/69773163-06fd0800-1160-11ea-97b0-3bc3d7684910.png)

It would be nice if the tab index would be visible in the label to make it easier to disambiguate between tabs, especially when they have the same title.

Looking at `Boss.detach_window`, the tab index _is_ included on each line, but it ends up being covered by the overlays of the hint kitten.

As a workaround, I can use something like this:

```diff
diff --git a/kitty/boss.py b/kitty/boss.py
index 6d8c3f72..536d15c0 100644
--- a/kitty/boss.py
+++ b/kitty/boss.py
@@ -1196,7 +1196,7 @@ class Boss:
         for i, tab in enumerate(self.all_tabs):
             if tab is not current_tab:
                 tab_id_map[i + 1] = tab.id
-                lines.append('{} {}'.format(i + 1, tab.title))
+                lines.append('{} {} [{}]'.format(i + 1, tab.title, i + 1))
         new_idx = len(tab_id_map) + 1
         tab_id_map[new_idx] = 'new'
         lines.append('{} {}'.format(new_idx, 'New tab'))
```

... which helps disambiguate the tabs. But it still is a bit weird to have to press "4" when I want to choose tab "1". Alternatively, maybe there's a way to get the hint kitten to use the matched `\d` from the regex as the hint label?

**Comment by rafikdraoui** [comment]
Thank you!

I still encounter a few glitches though (using kitty@da7a7869)

---
1. 
```
new tab
previous tab
detach_window ask
  press 1 (move to only other open tab, i.e. tab 2)
```
=>
nothing happens, and `KeyError: 1` in traceback (for the line `done.tab_id = tab_id_map[int(data['groupdicts'][0]['index']) + 1]`)

---
2.
```
new tab
move to previous tab
detach_window ask
  press 2 ("New tab")
```
=>
moves to a new window instead of moving to a new tab

---


The above examples might not really happen in real usage (for example, it's a bit useless to detach a single-windowed tab to a new tab), but the same glitches happen in more realistic cases, like having two windows in the first tab and one window in the second tab, and wanting to move one of the window in the first tab to a new (third) tab. Right now, this would only be possible to do in two steps: move window to second tab, then from there move it to a new tab (or by reordering the tabs and them detaching windows, it seems that `detach_window` operations initiated on the last tab will work correctly)

**Comment by rafikdraoui** [comment]
Leaving the current tab in the output seems to neatly solve the problems for me. As an added bonus, the hint label corresponds to the tab index:

```diff
diff --git a/kitty/boss.py b/kitty/boss.py
index c1e9f862..a4848fbd 100644
--- a/kitty/boss.py
+++ b/kitty/boss.py
@@ -1193,11 +1193,9 @@ class Boss:
         ]
         fmt = ': {1}'
         tab_id_map = {}
-        current_tab = self.active_tab
         for i, tab in enumerate(self.all_tabs):
-            if tab is not current_tab:
-                tab_id_map[i + 1] = tab.id
-                lines.append(fmt.format(i + 1, tab.title))
+            tab_id_map[i + 1] = tab.id
+            lines.append(fmt.format(i + 1, tab.title))
         new_idx = len(tab_id_map) + 1
         tab_id_map[new_idx] = 'new'
         lines.append(fmt.format(new_idx, 'New tab'))
```

**Comment by kovidgoyal** [comment]
Should be fine now.
