### ISSUE TITLE
Title is not updated after exiting kitty-diff

### ISSUE THREAD

**Issue by judaew** [kovidgoyal/kitty#2175]
**Environment:**
- macOS 10.15.1
- kitty 0.15.0
- zsh 5.7.1

**Reproduce Step:**
1. Add to .gitconfig difftool kitty;
2. Open project with changes;
3. Enter `git difftool ...`;
4. Close kitty-diff;
5. After the exit title is not updated.

![image](https://user-images.githubusercontent.com/41125715/69817940-6280d180-1204-11ea-842a-0c821e0f72a1.png)

**Comment by kovidgoyal** [comment]
Works fine for me. Title updating is in anycase done by the shell not
kitty. So make sure you have setup your shell to correctly send the title
update escape codes when drawing the prompt.

**Comment by judaew** [comment]
How should the shell be configured? Below is a demo in bash without any configuration. The old version of the shell for the test, but it also.

![term-speed150per](https://user-images.githubusercontent.com/41125715/69822405-f48dd780-120e-11ea-83bb-a79e06cc073d.gif)

**Comment by kovidgoyal** [comment]
Google setting window title in PS1

**Comment by judaew** [comment]
I figured it out! Thanks!
