### ISSUE TITLE
Weird mouse cursor in vim

### ISSUE THREAD

**Issue by swedneck** [kovidgoyal/kitty#2179]
When vim is open in kitty the mouse cursor changes sprite to a mirrored black and white arrow, i can't find any documentation on why this happens or how to stop it.

kitty v0.14.6
Fedora workstation 30
Happens regardless of any config options i've tried

**Comment by kovidgoyal** [comment]
Look at the setting pointer_shape_when_grabbed in kitty.conf

**Comment by swedneck** [comment]
i can't find any documentation for the valid values for that option.

**Comment by Luflosi** [comment]
The possible values are `arrow`, `beam` and `hand`. I'll make a PR to document that.

**Comment by swedneck** [comment]
Thanks!

**Comment by swedneck** [comment]
I think it should be considered a bug that the arrow value uses a different sprite from the OS setting, should i open a separate issue for that?

**Comment by kovidgoyal** [comment]
It does not use a different image. Indeed, the only custom cursor image
in kitty is for the beam cursor, not the arrow cursor. Which can be
enabled disabled with macos_custom_beam_cursor.
