### ISSUE TITLE
How to compiling for macOS .app

### ISSUE THREAD

**Issue by zchee** [kovidgoyal/kitty#218]

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty#installation

**Comment by zchee** [comment]
@kovidgoyal Hey. Sorry, I was mistaken create an issue(empty posted).
I writing the comment now. Could you re-open this issue?

**Comment by zchee** [comment]
@kovidgoyal Very sorry... :(
I finished issue comment. I hope you re-open this issue 🙏

**Comment by zchee** [comment]
sorry, re-create issue because it does not solve you said comment.
