### ISSUE TITLE
Problem with DPI in version 0.15

### ISSUE THREAD

**Issue by barlog-m** [kovidgoyal/kitty#2181]
I'v been using kitty for long time on my arch linux with PragmataPro font at size 14. But after update to 0.15 the size of signs became very small. For example at the right side in the screenshot is gnome terminal with same font settings.
![arch-kitty-dpi-problem](https://user-images.githubusercontent.com/3830685/69918922-59a03200-1488-11ea-944c-f5bf1da51f32.png)

**Comment by kovidgoyal** [comment]
If you are on X11 you need to set Xft.dpi that is how kitty gets DPI
information. If you are using gnome, then kitty will disable wayland
because gnome lacks server side window decorations on wayland, you can
enable it explicitly via linux_display_backend in kitty.conf.

**Comment by barlog-m** [comment]
Thank you very much for your answer. Set Xft.dpi fixed the problem. I wonder how it worked before 0.15 without Xft.dpi.

**Comment by Anfid** [comment]
This change should be somehow highlighted in the changelog, if changing original behavior was intended. I had to spend a few hours trying to fix problem without success, before searching similar issues directly on github. However, this change feels as a regression to me. Could it be caused by 91299a279bc033683e8e655c4a6d1e841e748dfc?

**Comment by kovidgoyal** [comment]
I highly doubt it, and as far as I know no behavior on X11 has been
changed. As long as you have Xft.dpi set kitty (or more properly glfw)
will use that DPI on X11. That has been th ecase for many, many moons.
There were some wayland specific changes,
https://github.com/kovidgoyal/kitty/commit/65fa7da24a3a7e82ecab5175866ed667317abc0d
but at least the OPs issue is on X11 not Wayland.

**Comment by Anfid** [comment]
The behavior certainly changed. Unfortunately, I do not have understanding of kitty's internals, but I just installed 0.14.5 for testing purposes and it did pick up DPI without Xft.dpi variable set

**Comment by kovidgoyal** [comment]
Then the behavior changed in glfw, not kitty. Look at the _glfwGetSystemContentScaleX11 function.

**Comment by Anfid** [comment]
Then it may be 61a77e19e. I can try to test if revert fixes it, if I figure out how to build kitty

**Comment by Anfid** [comment]
I have tested it. After commit revert original behavior is restored

**Comment by kovidgoyal** [comment]
Well you'll have to convince the glfw maintainers that not assuming
96DPI is wrong. Personally, I would just set Xft.dpi and forget about
it.
