### ISSUE TITLE
Problems after ssh login into remote server

### ISSUE THREAD

**Issue by pingu1m** [kovidgoyal/kitty#2182]
Hi, I have been using kitty for few weeks. I noticed after I ssh into an AWS remote server. The terminal prompt loses its color and I'm unable to ctr-l to clear the screen. It is a minor issue but it does interrupts my workflow. The only thing I have changed is the font.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by kadeguilherme** [comment]
I have the same problem. Kitty gets all lost when I make an ssh connection to gcp
