### ISSUE TITLE
Invisible colors in Elm, Jest, Random Node.js errors

### ISSUE THREAD

**Issue by ultrox** [kovidgoyal/kitty#2189]
Hi, I'm experiencing this for some time now, and frankly, I don't know how to solve it. I'm using Solarize Dark

it seems its related to #446 & #541 

I don't know how to start debugging this. How can I see available colors and reassign them? I was reading your comments at #446 but I'm not very experienced with terminal colors. I realize I need to add 256 colors but no idea how to start.

## This is my theme:
```
# The foreground color
foreground       #839496

# The background color
background       #002b36

# The foreground for selections
selection_foreground #93a1a1

# The background for selections
selection_background #073642

# The cursor color
cursor           #ffffff

# The 16 terminal colors. There are 8 basic colors, each color has a dull and
# bright version.

# black
color0   #073642
color8   #002b36

# red
color1   #dc322f
color9   #cb4b16

# green
color2   #859900
color10  #586e75

# yellow
color3   #b58900
color11  #657b83

# blue
color4  #268bd2
color12 #839496

# magenta
color5   #d33682
color13  #6c71c4

# cyan
color6   #2aa198
color14  #93a1a1

# white
color7   #839496
color15  #2010 
```

## ELM (normal & highlighted)
![image](https://user-images.githubusercontent.com/3077558/70444140-b6f43e80-1a99-11ea-841c-d437fbe2f3b5.png)

## Jest (normal & highlighted)

![image](https://user-images.githubusercontent.com/3077558/70444245-e30fbf80-1a99-11ea-96b4-d86de8d42e8e.png)

## Node Js random error (normal & highlighted)

![image](https://user-images.githubusercontent.com/3077558/70444301-f753bc80-1a99-11ea-8f63-fe4eca749ed9.png)

**Comment by kovidgoyal** [comment]
First of all #2010 is not a valid color specification. I'm afraid I dont have the time to debug your color theme for you, but in general, comment out individual color lines till you find the problem set,

**Comment by Luflosi** [comment]
The problem ist that your `color8` is the same as your `background` color, making that color invisible. You should change one of the two. You should also fix `color15` as @kovidgoyal suggested.

**Comment by ultrox** [comment]
@Luflosi thanks, you were right color8 is offending, it's fixed now. Thanks, man!
