### ISSUE TITLE
How to compiling for macOS .app

### ISSUE THREAD

**Issue by zchee** [kovidgoyal/kitty#219]
At first, this issue is re-created from #218. I was mistaken create #218 issue that is an empty comment. very sorry...but I create issue again because it does not solve you said:

https://github.com/kovidgoyal/kitty/issues/218#issuecomment-350256702
> https://github.com/kovidgoyal/kitty#installation

---

Hi,
I'm very interesting this project. Thanks for developing kitty!! It's change of life... very fast terminal AFAIK.

BTW, I planned developing enable `CGContextSetFontSmoothingStyle` for macOS.
So, I want to know how to compiling macOS `.app` bundle.

Currently, `make osx-bundle` will create `Contents` under the `linux-package` directory. But that internal file such as Python files is different to your released `.dmg` at least [Release version 0.5.1](https://github.com/kovidgoyal/kitty/releases/tag/v0.5.1).
e.g.: your released `.dmg` have `.pyo` file, but I compiled `Contents` doesn't `.pyo`, `.py` only.

Why is that different? Is there anything else I need to do?

**Comment by kovidgoyal** [comment]
If you want to make changes to kitty code, compile it from source and run it directly, there is no need to create an app bundle. You can simply update the changed files in an existing kitty app bundle as well.

And note that setting CGContextSetFontSmoothingStyle will have no effect as kitty uses freetype to render text not CoreText.

**Comment by kovidgoyal** [comment]
Oh and instructions for compiling it are in the README. You can also refer to the .travis.yml file that build kitty on OS X using brew to install dependencies.

**Comment by zchee** [comment]
@kovidgoyal Thanks for information!!
I’ll try to make change and compile, and copy into released kitty.app.

> And note that setting CGContextSetFontSmoothingStyle will have no effect as kitty uses freetype to render text not CoreText.

Thanks again explain to kitty internal implements. I understand.
I’ll digging FreeType C API.

Your comment was very helpful. Thank you for your polite answer.

**Comment by kovidgoyal** [comment]
You're welcome :) Feel free to ask if you have questions.

**Comment by kovidgoyal** [comment]
FYI, I just implemented using CoreText on macOS for rendering.

**Comment by zchee** [comment]
@kovidgoyal Wow, really!? I'll try to `master` branch and test it.
If found any bugs, I'll fix and commit. I would like to be helpful to you in some way.

Anyway, very thanks for mentioned :)

**Comment by kovidgoyal** [comment]
Feel free to test and fix any problems. Note that you dont need to use an .app for testing. Simply compile and run with

```
make debug
python3 .
```

(you will first need to install the dependencies using something like brew).

**Comment by zchee** [comment]
@kovidgoyal 
Thanks for how to develop command :)

> Note that you dont need to use an .app for testing. Simply compile and run with...
I understand. I'll try it for developing.

> (you will first need to install the dependencies using something like brew)
Yes, I have already dependency package (`python3` and`harfbuzz`, Now no need `freetype`).

Thanks again quickly response!!

`kitty` is great terminal emulator, changing the world at least me :D
