### ISSUE TITLE
WEIRD POWERLINE FONT LOADED ON TMUX

### ISSUE THREAD

**Issue by SayidMabrur** [kovidgoyal/kitty#2193]
![Screenshot from 2019-12-13 12-47-12](https://user-images.githubusercontent.com/51082837/70772331-be239100-1da6-11ea-8d1e-fd169b5152a9.png)
**the picture above is the screenshot tmux running on kitty.**

![Screenshot from 2019-12-13 12-48-56](https://user-images.githubusercontent.com/51082837/70772382-f32fe380-1da6-11ea-85e2-cd369a7b5939.png)

**the picture above is the screenshot tmux running on gnome-terminal**

as you can see on gnome terminal, the powerline looks beautiful, but in kitty the powerline font loaded differently.

OS: Kali Linux

**Comment by kovidgoyal** [comment]
Set TERM=xterm-kitty inside tmux and you will be fine.
