### ISSUE TITLE
send text to last active kitty window/tab via remote control in an external program

### ISSUE THREAD

**Issue by QiangF** [kovidgoyal/kitty#2194]
I use exwm (https://github.com/ch11ng/exwm/) as my window manager, and I am trying to send a string from the emacs kill ring.
I need a way to match the last active kitty window/tab, then I can use command like this to send the string.

    kitty @ send-text --match last_active_kitty 'text to send'
    
A better way to send the paste key, but kitty seems to be running in a lower level, things like this is not working:

    (exwm-input--fake-key (aref (kbd "C-S-v") 0))

I guess exwm-input--fake-key is similar to autokey and xdotool, apparently all of them won't work with a terminal emulator:
https://github.com/kovidgoyal/kitty/issues/2122

**Comment by kovidgoyal** [comment]
I dont understand your use case. You are trying to do what? Send text
from emacs to a kitty window? Is emacs running inside kitty? Or trying
to copy to clipboard?

**Comment by QiangF** [comment]
Sorry. Let me explain:
1. emacs is my window manager via exwm, kitty is running as an application
2.  I am trying to send a string from my window manager to kitty, in emacs I can select the string from kill ring,  like dmenu.

**Comment by QiangF** [comment]
I am trying to send a particular string from my clipboard history to kitty. In my window manager I have a pop up showing a list of my clipboard history, then I select one item in the pop up, and the selected string is sent to kitty window.

**Comment by QiangF** [comment]
I need to match the kitty window in focus before the minibuffer popup.

**Comment by kovidgoyal** [comment]
Use kitty @ ls to get the active window before launching dmenu (or
whatever) store it in a variable and pass it along.

**Comment by QiangF** [comment]
It like dmenu, but not demenu, I am execute the command in kitty. The command is run in my window manager, which is emacs. Kitty is run inside emacs actually.

**Comment by kovidgoyal** [comment]
So in your window manager, run a script instead of the command. In that script run kitty @ ls
to get the active window, then run the command then run kitty @ send-text

**Comment by kovidgoyal** [comment]
Oh and to make it easier I just added code to have kitty @ ls return the active window history for each tab as well.
