### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by dm17** [kovidgoyal/kitty#2196]
Has anyone reproduced these benchmarks with kitty?
https://lwn.net/Articles/751763/
Thanks :)

**Comment by kovidgoyal** [comment]
Not that I know of, you are welcome to try :) My own personal goal for kitty is mostly CPU/energy usage while performing everyday tasks, since its latency is already too low for at least me to notice. See https://sw.kovidgoyal.net/kitty/performance.html  for details.

**Comment by jsravn** [comment]
I was curious so I tested it out on OSX, kitty vs terminal.app:

![image](https://user-images.githubusercontent.com/522123/76403135-5fa58900-637c-11ea-9aa3-3cd8dacbc6f0.png)

Short of it is: Set `input delay 0` for best latency.

* At stock, kitty has around 3ms more delay than Terminal.app.
* `input_delay 0` has the largest effect - reducing latency down to ~6ms from ~9ms, only about 600us slower than Terminal.app on average. However it still has around 1ms higher std. dev and the max is 2ms larger.
* `repaint_delay` and `sync_to_monitor` seem to have little effect on latency. `repaint_delay` actually seems to make things worse in some cases (higher max, more variance in delay).
* `sync_to_monitor no` actually seems to increase latency slightly, weird! Might be an OSX thing.

I imagine the results will be different on Linux.

**Comment by dm17** [comment]
Sweet, thanks! If the latency is higher, then for practical purposes it isn't faster for anything I do in the terminal.

**Comment by jsravn** [comment]
Here's iterm2 and alacritty in comparison:

![image](https://user-images.githubusercontent.com/522123/76404001-ad6ec100-637d-11ea-90a5-2ba5630bc92d.png)

iterm2 is just terrible. alacritty is pretty much the same as kitty.

**Comment by dm17** [comment]
As I understand it st is the lowest when considering added optimizations:
https://lwn.net/Articles/752894/

**Comment by kovidgoyal** [comment]
I am pleased to see kitty's numbers, especially compared to Terminal.app that has far less features and access to internal macOS APIs. :+1:

**Comment by travankor** [comment]
There were some [Linux comparisons](https://github.com/alacritty/alacritty/issues/673#issuecomment-459342135) with kitty ~1 year ago.

**Comment by jsravn** [comment]
Interesting... although I think I trust typometer more - otherwise you are primarily measuring the display itself.

**Comment by falcucci** [comment]
I was looking for more comparisons about what really matters for me (input latency) and maybe this article can also help:

https://www.lkhrs.com/blog/2022/07/terminal-latency/
