### ISSUE TITLE
Enhacement Request: Change tab line background and diffentiate tab_title_template for active tab

### ISSUE THREAD

**Issue by pwntester** [kovidgoyal/kitty#2198]
Thanks for kitty, just moved to it and found it awesome! Two minor requests that other users may want as well:
- allow defining a `tab_background` color different from `background`
- allow different tab templates for active and inactive tabs. eg: `active_tab_title_template` and `inactive_tab_title_template`

Thanks!

**Comment by kovidgoyal** [comment]
There already are (in)active_tab_(fore|back)ground color settings. As well as font style settings. As for different template for active tabs, not something I am interested in persoally, but patches are most welcome!

**Comment by pwntester** [comment]
Thanks for the quick response. For the first request, I was referring to the space to the right of the last tab. Is there a way to treat that space as inactive tabs?

**Comment by kovidgoyal** [comment]
Ah, you mean, you want the tab bar to be some color than than the
terminal background color? Yes, there's not setting for that.
