### ISSUE TITLE
Unknown uniform in cursor program

### ISSUE THREAD

**Issue by JulioJu** [kovidgoyal/kitty#221]
Hi

Kitty doesn't seem to work for me.

With kitty 0.5.1 or kitty kovidgoyal/kitty@b8093d6b83d2b48da8ffbdb49dddba0d37917311 when I launch kitty from a terminal (urxvt or gnome-terminal) I have the error `Unknown uniform in cursor program`. The return code is 1.  Kitty doesn't work too when I launch it with the .desktop shorcut.

Kitty use the Gpu. Maybe it's a problem with my old graphic card ? 
Actually I use
```
$ sudo inxi -b
System:   Kernel: 4.14.4-1-ck x86_64 bits: 64 Distro: Arch Linux
Graphics:  Card: NVIDIA GT216M [GeForce GT 330M]
Display Server: X.Org 1.19.5 drivers: nvidia (unloaded: modesetting,nouveau)
Resolution: 1600x900@60.31hz
OpenGL: renderer: GeForce GT 330M/PCIe/SSE2 version: 3.3.0 NVIDIA 340.104
```

Thanks in advance !

**Comment by JulioJu** [comment]
Yes,  the problem is with the driver.
When I use Nouveau, kitty wants to launch. But Nouveau it's very buggy, so I can't use your software :'(
The fallowing configuration works>
```
$ sudo inxi  -b
Graphics:  Card: NVIDIA GT216M [GeForce GT 330M]
           Display Server: X.Org 1.19.5 drivers: nouveau (unloaded: modesetting) Resolution: 1600x900@60.31hz
           OpenGL: renderer: NVA5 version: 3.3 Mesa 17.2.6
```

**Comment by kovidgoyal** [comment]
I'm afraid there's not much I can do about buggy graphics drivers. kitty requires working OpenGL 3.3 support, which is almost a decade old at this point https://www.khronos.org/opengl/wiki/History_of_OpenGL#OpenGL_3.3_.282010.29

**Comment by nono** [comment]
Hello,

I have the same issu. `glxinfo` says that my GPU supports OpenGL 3.3:

```
$ glxinfo | grep 'OpenGL version'
OpenGL version string: 3.3.0 NVIDIA 340.104

$ inxi -b
Graphics:  Card: NVIDIA GT218 [GeForce 210]
           Display Server: x11 (X.Org 1.19.5 )
           drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 2560x1440@59.95hz
           OpenGL: renderer: GeForce 210/PCIe/SSE2
           version: 3.3.0 NVIDIA 340.104
```

Do you think it's a bug of my GPU? Or is it something that can be fixed, and if it is the case, will you accept a pull request for that?

I don't know OpenGL and I will totally understand if you do not want a patch from me, because it may become a burden to maintain later.

**Comment by kovidgoyal** [comment]
It's definitely a bug in the graphics drivers. You are welcome to submit a pull request, I cant promise I will accept it, but I will review it.

**Comment by JulioJu** [comment]
Yes, I have a also NVIDIA 340
```
$ glxinfo | grep 'OpenGL version'
OpenGL version string: 3.3.0 NVIDIA 340.106
```
Nvidia driver it's not Open source and this version of the driver is marked as legacy (see http://www.nvidia.com/object/IO_32667.html). They only want maintain the compatibility with current X.Org and Linux version, not implement correctly OpenGL 3.3.0 specification. @nono : Nouveau Driver could be a solution (even if often it has others compatibility problems like when you suspend your laptop or adjust the brightness).

Maybe you could try anyway to post an issue at https://devtalk.nvidia.com/default/topic/522835/linux/if-you-have-a-problem-please-read-this-first/ ?

**Comment by nono** [comment]
Thanks for the feedback.

Last time I tried nouveau, I didn't find a way to support the native resolution of my screen (2560x1440).

**Comment by JulioJu** [comment]
@nono. Maybe look https://wiki.archlinux.org/index.php/nouveau#Loading. They explain a solution to resolve this.
