### ISSUE TITLE
"uninitialized" content displayed on startup

### ISSUE THREAD

**Issue by fdev31** [kovidgoyal/kitty#2216]
# Description

The kitty's window content is displayed incorrectly for some time on startup.
Looking like "random zones" of the video buffers are showing for a second on screen.

# Demo

[![running multiple kitties](https://img.youtube.com/vi/2UXbFgRw7gQ/0.jpg)](https://www.youtube.com/watch?v=2UXbFgRw7gQ)

# Details

- Archlinux
- kitty including v0.14.x & 0.15.0, I can try a bisect if it helps
- [kitty.conf.txt](https://github.com/kovidgoyal/kitty/files/3985620/kitty.conf.txt)
- compton v7.5
- awesome v4.3
- nvidia v440

Running from a console, such warning can be seen:

    [353 22:06:53.193974] [glfw error 65544]: Failed to create XKB compose table for locale

**Comment by fdev31** [comment]
The problem is still here, but less visible (it happens faster).

**Comment by kovidgoyal** [comment]
It's too fast for me to see at all, so I cant really fix it, but patches
are most welcome.
