### ISSUE TITLE
Shortcuts explanation missing?

### ISSUE THREAD

**Issue by kajukenbo** [kovidgoyal/kitty#2219]
Is there any place I have missed that explained complicated shortcuts like:

ctrl+shift+a>m 
ctrl+shift+a>l 
ctrl+shift+a>1 
ctrl+shift+p>f 

I did not follow what those shortcuts were supposed to be.
Pressing 5 keys simultaneously did not seem like a shortcut to me.

I finally figured out that it meant press 'ctrl+shift+p' release and then press 'f' to select anything that looks like a path or filename and then insert it into the terminal

Perhaps updating the web pages a bit to clarify this would be of value?

**Comment by kovidgoyal** [comment]
The multi-key shortcut synatx is exaplaine at the start fo the Keyboard
shortcuts documentation, with examples. If you feel it can be further
improved, a pull request is welcome.

https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts
