### ISSUE TITLE
macOS font smoothing

### ISSUE THREAD

**Issue by slice** [kovidgoyal/kitty#222]
Is there a way to change how fonts are smoothed while using kitty on macOS?

iTerm2 is on the left, and kitty is on the right.
![image](https://user-images.githubusercontent.com/4206232/33801261-9f74bda8-dd0a-11e7-9971-82d99db26d1c.png)

Is there a way to accomplish the same smoothing as iTerm?

**Comment by kovidgoyal** [comment]
No, you will never get the same rendering between iterm2 and kitty as kitty does not use CoreText to render fonts. The next kitty release will however include support for subpixel antialiasing, which IIRC iterm2 uses as well (although personally, I find sub-pixel antialiasing to be sub-optimal on high resolution displays).

**Comment by slice** [comment]
Thank you for the quick response! :+1:

**Comment by kovidgoyal** [comment]
Actually, I should say that I am currently investigating getting kitty to use CoreText on macOS, if I succeed, this should be automatically fixed.

**Comment by kovidgoyal** [comment]
I managed to get CoreText rendering working (in the ct branch)

**Comment by slice** [comment]
I built a fresh version of kitty and there appears to be no effect, how strange. I tried messing around with the render context in the `render_glyphs` function and couldn't figure out how to make the text appear to my liking.

I guess it's not a big deal, though.

**Comment by kovidgoyal** [comment]
Make sure you are using the same font variant, i.e. the thick/thin/medium/book style. Use kitty list-fonts to get a list.

**Comment by slice** [comment]
Some recent changes caused the font rendering to change substantially for me:

![image](https://user-images.githubusercontent.com/4206232/33968836-ee9c0b22-e01e-11e7-97e1-e0895e26fc3d.png)

Old on the left, new on the right. Thanks for this, it looks much better now!

**Comment by kovidgoyal** [comment]
That's likely the effect of https://github.com/kovidgoyal/kitty/commit/b9d0ec0d4cc4e35b805f5dd3b8e9342926051673

**Comment by slice** [comment]
Hmm...

I know this issue is closed and it has been a while, but font smoothing is still "thin" despite terminal glyphs being rendered with CoreText.

**Comment by kovidgoyal** [comment]
The remaining difference between kityt and most other terminals is kitty does not so sub-pixel AA as it is an unnecessary waste of resources on modern retina displays, see other bug reports for full explanation.

**Comment by nielsk** [comment]
Looks great on the internal display of my MacBook Pro, looks crap on the display I am using most of the time which isn't a retina-display :/

**Comment by jrnkng** [comment]
@nielsk ever found a way to improve it?

**Comment by nielsk** [comment]
No. Fonts only look good on a HiDPI-display.
