### ISSUE TITLE
Backspace & Delete not repeated

### ISSUE THREAD

**Issue by evelineraine** [kovidgoyal/kitty#2220]
Hi,

When holding any key in my Kitten `0.15.0` on Fedora 31 (Wayland) it repeats itself several times a second - this also includes arrow keys. But, if holding Backspace or Delete, only one character is deleted, afterwards nothing happens.

When comparing to any other graphical application - including GNOME Terminal - Backspace and Delete are being repeated properly.

Is this a bug or an expected behaviour?

**Comment by kovidgoyal** [comment]
Works for me under wayland wiht both weston an sway compositors. I dont
have a system to test it under GNOME, but am sure that if it didn't work
there lots of other ppl would have complained. So that indicates an
issue specific to your system. Things to check:

1) The value of the TERM environment variable is xterm-kitty
2) Try setting linux_display_server to both wayland and x11 and see if
the problem goes away in either case

**Comment by evelineraine** [comment]
Thank you! Setting `linux_display_server` to `wayland` explicitly solved the issue.
However, other issues appeared instead:
1. Window decorations are not displayed, just an empty stripe at the top. Pointing a cursor on it leaves graphical artifacts on the screen.
2. Trying to go full-screen crashes an entire app with the following error:
    ```
    kitty.desktop[1988]: [355 19:27:27.302405] [glfw error 65544]: Wayland: Window position retrieval not supported
    ```
    I have currently a vanilla GNOME DE installed.

Please let me know if either of these is something new, and I will open a more detailed issue for it.

**Comment by kovidgoyal** [comment]
On Sat, Dec 21, 2019 at 09:33:25AM -0800, Eveline Raine wrote:
> 1. Window decorations are not displayed, just an empty stripe at the top. Pointing a cursor on it leaves graphical artifacts on the screen.

GNOME does not support server side windows decorations on Wayland, that is why
Wayland is disabled by default on it. They actually expect every
application to link against GTK to draw window decorations. kitty is
never going to do that.

> 2. Trying to go full-screen crashes an entire app with the following error:
>     ```
>     kitty.desktop[1988]: [355 19:27:27.302405] [glfw error 65544]: Wayland: Window position retrieval not supported
>     ```
>     I have currently a vanilla GNOME DE installed.
> 
> Please let me know if either of these is something new, and I will open a more detailed issue for it.

How are you going fullscreen and build kitty from source and post a
backtrace.

https://sw.kovidgoyal.net/kitty/build.html
