### ISSUE TITLE
MacOS: powerline symbols not work when starting kitty from launcher

### ISSUE THREAD

**Issue by hujianxin** [kovidgoyal/kitty#2221]
but work when starting kitty from terminal

image blow is starting kitty form macos launcher
![image](https://user-images.githubusercontent.com/9526904/71310400-ac995380-244e-11ea-8076-f2f3d2362677.png)

image blow is stating kitty from terminal:
![image](https://user-images.githubusercontent.com/9526904/71310407-bae76f80-244e-11ea-9f0e-fe64acf604dd.png)

the font config is :

```

font_family      Fira Mono for Powerline
bold_font        auto
italic_font      auto
bold_italic_font auto

#: You can specify different fonts for the bold/italic/bold-italic
#: variants. To get a full list of supported fonts use the `kitty
#: list-fonts` command. By default they are derived automatically, by
#: the OSes font system. Setting them manually is useful for font
#: families that have many weight variants like Book, Medium, Thick,
#: etc. For example::

#:     font_family      Operator Mono Book
#:     bold_font        Operator Mono Medium
#:     italic_font      Operator Mono Book Italic
#:     bold_italic_font Operator Mono Medium Italic

#: Font size (in pts)
font_size 13.0

adjust_line_height  0
adjust_column_width 0
```

**Comment by hujianxin** [comment]
that maybe not powerline symbols, but this can not display normally anyway

**Comment by kovidgoyal** [comment]
This will be because your terminal startup scripts are setting some
environment variables that are not set in your macOS launchd
environment. Most probably locale related variables. Figure out what
those are and set them in kitty.conf instead of your shell startup
scripts using the env command and you will be fine.

**Comment by hujianxin** [comment]
put this into .zshenv soves this:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

thank you
