### ISSUE TITLE
[INFO] Tmuxinator replacement

### ISSUE THREAD

**Issue by gavinhoward** [kovidgoyal/kitty#2223]
I am currently evaluating using `kitty` instead of `gnome-terminal` + `tmux`, and one of the things I use is [`tmuxinator`][1], which allows me to easily set up my terminal in various ways for various projects.

Do you think it be possible for me to write a kitten that will fulfill the same role for `kitty` that `tmuxinator` fills for `tmux`? It would make it much easier to switch.

Also, if it *is* possible, would bash/shell completion for it be possible as well?

[1]: https://github.com/tmuxinator/tmuxinator

**Comment by kovidgoyal** [comment]
I dont know what tmuxinator is or what it can do, but kitty has various
facilities for setting up sessions. See the kitty help on sessions and
remote control.

https://sw.kovidgoyal.net/kitty/#startup-sessions
https://sw.kovidgoyal.net/kitty/remote-control.html

These should provide plenty of building blocks to create a tool to
manage your sessions.

**Comment by kovidgoyal** [comment]
And if some control/session functionality is missing, unclear, feel free
to ask about it.

**Comment by gavinhoward** [comment]
Is there a complete set of documentation of the Python API?

**Comment by kovidgoyal** [comment]
Neither of the two things I pointed you to require the use of python,
and the links point to complete documentation for them.
