### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by s1341** [kovidgoyal/kitty#2225]
Hi,

I've noticed that kitty has a very high memory usage, with some instances reserving more than 2G of memory.

You can see in the below screenshot from htop:
![2019-12-23-102139_472x913_scrot](https://user-images.githubusercontent.com/5682183/71345510-4277d000-256e-11ea-89d1-ad9fbf297c42.png)

Is there an explanation for this? If so, is it possible to reduce the footprint?

**Comment by kovidgoyal** [comment]
You presumably increased the max scrollback size from the default.
Reduce it nd you should be fine in kitty.conf.

**Comment by s1341** [comment]
Ok. Makes sense. Is there a way to reduce the usage of an existing session? Perhaps it can release some of the buffer when the terminal is reset?

**Comment by kovidgoyal** [comment]
Clearing the scrollback buffer releases memory IIRC, and there is an
action for that, though I cant recall if it has a default keybinding or
not.

**Comment by Yevgnen** [comment]
@kovidgoyal Hi, I've tried the below options from the document to release the memory usage of an existing session after outputed large contents but none of them seemed to work.

```
# Reset the terminal
map kitty_mod+f9 clear_terminal reset active
# Clear the terminal screen by erasing all contents
map kitty_mod+f10 clear_terminal clear active
# Clear the terminal scrollback by erasing it
map kitty_mod+f11 clear_terminal scrollback active
# Scroll the contents of the screen into the scrollback
map kitty_mod+f12 clear_terminal scroll active
```

**Comment by kovidgoyal** [comment]
clearing the scrollback releases the memory fine for me, in current
kitty.

**Comment by kovidgoyal** [comment]
Yes, but I was mis-remembering, clearing the scrollback does not free the memory, I think that was changed a while ago, see the historybuf_clear() function, it only resets index pointer, does not clear the allocated segments.

**Comment by Yevgnen** [comment]
So how can I do that? Or is the change a new feature?

**Comment by kovidgoyal** [comment]
You currently cant. IIRC it was done to avoid having to re-alloc memory,
since typical scrollback sizes are not that large. I guess you would
need an option, to release memory on clear or maybe release it for
scrollback sizes above a certain threshold.

**Comment by kovidgoyal** [comment]
That should take care of it: https://github.com/kovidgoyal/kitty/commit/57583d6b0070642ed567f4d8848c285c951188f1
