### ISSUE TITLE
--hold option for launch

### ISSUE THREAD

**Issue by wallace11** [kovidgoyal/kitty#2229]
Hi,
New `launch` option is awesome and useful.
When launching some commands, they result in automatic closing of the window/tab. I though it might be a good idea to have a `--hold` option that does the same thing as it does for the main program. 

To anyone who comes across this, as a workaround I'm currently simply calling a separate instance of kitty for those particular scenarios.  
Example:
```sh
kitty --hold ls
```

**Comment by kovidgoyal** [comment]
Just wrap it in a shell, like this:

sh -c "whatever-command-you-want; echo Press enter to close; read"

then the window will remain open till you press enter
