### ISSUE TITLE
Question about macos package

### ISSUE THREAD

**Issue by kalekseev** [kovidgoyal/kitty#223]
Hi, thanks for the project, I have a small question about macos package. Kitty respects that option 
![2015-02-15_10-24-17](https://user-images.githubusercontent.com/367259/33821308-6ae385c8-de64-11e7-9d65-4d73d98b8622.png)
while alacritty app doesn't respect it, I want to fix that but don't have experience with macos apps so I would appreciate any related info. Thanks!

**Comment by kovidgoyal** [comment]
No idea, as far as I can recall kitty does not do anything special for that. Probably the relevant code is in glfw, you should ask there.
