### ISSUE TITLE
Launching through .app fails on Mac OS

### ISSUE THREAD

**Issue by immackay** [kovidgoyal/kitty#2232]
Mac OS Catalina 10.15.2

Launching from the .app is broken for me with newest version - launching via terminal works fine.

Potentially relevant console messages:

```
Timed out waiting for shell to quit while reading shell environment
```

& 

```
Traceback (most recent call last):
  File "kitty/main.py", line 347, in main
  File "kitty/main.py", line 336, in _main
  File "kitty/main.py", line 270, in setup_environment
  File "kitty/main.py", line 245, in read_shell_environment
AttributeError: 'function' object has no attribute 'ans'
```

Looks like c510584 is to blame.

**Comment by immackay** [comment]
That's the fastest issue resolution I've ever witnessed.

Cheers, and thanks for making such a great program!

**Comment by kovidgoyal** [comment]
You're welcome :)

**Comment by crazy-matt** [comment]
Hi,
It reappeared again on Catalina 10.15.7. Here is what works well for me: https://github.com/kovidgoyal/kitty/issues/2241#issuecomment-830655874
