### ISSUE TITLE
kitty +kitten ssh won't connect to OpenWRT via SSH

### ISSUE THREAD

**Issue by kozross** [kovidgoyal/kitty#2233]
Every time I try to SSH into my OpenWRT device, I get the following:

```
[koz@Sebastian ~]$ kitty +kitten ssh root@192.168.20.38
root@192.168.20.38's password: 
ash: tic: not found
Connection to 192.168.20.38 closed.
```

I tried copying the terminfo file from ``/usr/share/terminfo/x/xterm-kitty`` to ``/usr/share/terminfo/x`` on the OpenWRT device, setting ``TERM``, and changing shells on the OpenWRT device, but I had no luck with any of the above. Is there something I can do to fix this?

**Comment by kovidgoyal** [comment]
That error is because your openwrt is missing the tic utility from
terminfo. Copying the terminfo file manually should work fine.

**Comment by kozross** [comment]
```
root@OpenWrt:/# ls -A /usr/share/terminfo/x/
xterm           xterm-256color  xterm-color     xterm-kitty
```

I tried manually copying, but I'm still getting the same error.

**Comment by kovidgoyal** [comment]
No idea, not familiar with OpenWRT. It probably has an incopatible version of ncurses or something.

**Comment by martinetd** [comment]
copying the terminfo file won't magically make the `tic` command appear, just use regular ssh after copying the file...

**Comment by kozross** [comment]
@martinetd I tried using regular SSH as well, no luck either.

**Comment by martinetd** [comment]
You get `ash: tic command not found` error and shell closes immediately when using regular ssh?! You must have some environment that use the ssh kitten instead

**Comment by Luflosi** [comment]
Logging into OpenWRTworks for me.
Try executing `type ssh` on your local machine, maybe you set up an alias that executes the ssh kitten.
