### ISSUE TITLE
fail to start kitty after the latest manjaro linux upgrade inside virtualbox

### ISSUE THREAD

**Issue by iharh** [kovidgoyal/kitty#2237]
After upgrading my manjaro linux inside virtualbox I can't start kitty anymore because of:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  72 (X_PutImage)
  Serial number of failed request:  358
  Current serial number in output stream:  392
```
Notes:
- https://forum.manjaro.org/t/stable-update-2019-12-29-kernels-kde-apps-19-12-xorg-stack-mesa-qt5/116899
-  everything works fine at my bare-metal box

BTW: what can I do in order to diagnose the issue further ???

**Comment by kovidgoyal** [comment]
That's an error in the X libraries, not in kitty code. I have no idea
where to begin diagnosing that, but most likely your VM is missing GPU
acceleration or has broken GPU drivers. Try google XPutImage failures.

**Comment by iharh** [comment]
Thank you - will do
