### ISSUE TITLE
Feature request: Using icat in FZF preview window

### ISSUE THREAD

**Issue by tonybounty** [kovidgoyal/kitty#2238]
I try to use `kitty +kitten icat` with `fzf --preview=` option in order to display image with FZF.

Currently : 
![kitty_fzf_icat](https://user-images.githubusercontent.com/47276302/71602241-a6def480-2b57-11ea-8e59-b3a2c2f93bd8.gif)
 
```
kitty 0.14.3 created by Kovid Goyal
Linux ryzen 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64
Ubuntu 19.10 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/tony/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_border_color   Color(red=0, green=0, blue=153)
background            Color(red=39, green=40, blue=34)
font_family           Fira Code
font_size             12.5
foreground            Color(red=248, green=248, blue=242)
initial_window_height (654, 'px')
initial_window_width  (1300, 'px')
remember_window_size  False
scrollback_lines      10000
update_check_interval 0.0
```

**Comment by kovidgoyal** [comment]
How is this something for kitty to implement? fzf will need to add
support for displaying images, currently as far as I know it just takes
the output of the preview program and dispays it. That is not going to
work with graphics display since graphics display involves writing
escape codes to the terminal. Use something like ranger instead which
has integrated support for kitty's graphics protocol.

**Comment by p-kolacz** [comment]
`kitty icat --transfer-mode file` works in `fzf`.

**Comment by shanness** [comment]
> `kitty icat --transfer-mode file` works in `fzf`.

Just in case this helps, using clear and place solved my problem of it putting it over the selection.
`ls *jpg | fzf --preview="kitty icat --clear --place 200x40@0x0 --transfer-mode file {}"`

**Comment by Randalix** [comment]
For me this only works without the clear option. Wich obviously is not ideal (screen get's not cleared)
Can someone help me? Kitty version 0.26.5

**Comment by yrammos** [comment]
This no longer works, with or without `--clear`.

**Comment by elzii** [comment]
Bump. Do we know the commit SHA that broke this?
