### ISSUE TITLE
Subsequent tab naming Q/issue

### ISSUE THREAD

**Issue by Strykar** [kovidgoyal/kitty#2239]
I start kitty without borders on login as:
`Exec = kitty --config=~/.config/kitty/weechatkitty.conf --start-as=minimized --directory=/home/strykar`

`~/.config/kitty/weechatkitty.conf` specifies a session file which contains:
```
title irc
launch env WEECHAT_PASSPHRASE=_mypass weechat
```
If I set a title for this tab in the session file like `irc` or `irc@kitty`, it works. Trouble is, when I open a new tab, they're just all named `strykar@i-5` and don't update when I ssh in to remote machines, which I would like. If I don't name the tab, it gets named `env` (presemably from the `env launch weechat`), and while I can manually rename it later, I wish to do it via the session file.

Is this something I've missed while reading the docs or is this the expected behavior?
How would I name just the first tab that runs weechat _and_ maintain kitty's standard tab naming scheme for any new tabs that are opened after.

**Comment by kovidgoyal** [comment]
Session is with --session not --config. Use that and you should be fine.

**Comment by Strykar** [comment]
I was calling session from inside the config. Thank you @kovidgoyal!
