### ISSUE TITLE
mac: box drawing rounded corners are not rounded

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#2240]
Left: kitty 0.15.1, right: iterm2 Build 3.3.7

For example: `╰`

Font is PragmataPro 

<img width="1587" alt="Screenshot 2020-01-01 at 17 21 07" src="https://user-images.githubusercontent.com/63876/71643551-76b06680-2cbb-11ea-8cf7-1c607c0ce2ae.png">

Same with other fonts (they all work in iterm)

FiraCode
<img width="268" alt="Screenshot 2020-01-01 at 17 28 16" src="https://user-images.githubusercontent.com/63876/71643629-53d28200-2cbc-11ea-9ab0-dfe629a127c9.png">

Iosevka
<img width="329" alt="Screenshot 2020-01-01 at 17 29 07" src="https://user-images.githubusercontent.com/63876/71643642-68af1580-2cbc-11ea-872c-261bdc3f8392.png">

**Comment by kovidgoyal** [comment]
Yes, I have never bothered implementing drawing of rounded corners. I
dont care enough, if you do patches are welcome, relevant code is in
box_drawing.py

**Comment by rodrigore** [comment]
It would be cool to render border, for example you can make the floating window on neovim with rounded borders

**Comment by ahmedelgabri** [comment]
> @ahmedelgabri did you hack some solution?

No, I didn't have time to do it yet. Feel free to pick it up if you want.

**Comment by ctrlcctrlv** [comment]
I think it's possible to disable Kitty's box drawing code and use the glyphs in the font. Does that work for you?

**Comment by rodrigore** [comment]
> I think it's possible to disable Kitty's box drawing code and use the glyphs in the font. Does that work for you?
Not sure what is the option to disable box drawing, can you give me a hand?

**Comment by ctrlcctrlv** [comment]
Try this:

```diff
diff --git a/kitty/fonts/box_drawing.py b/kitty/fonts/box_drawing.py
index d03f5bec..ecb6236b 100644
--- a/kitty/fonts/box_drawing.py
+++ b/kitty/fonts/box_drawing.py
@@ -707,6 +707,7 @@ def test_drawing(sz=48, family='monospace'):
             return concat_cells(width, height, False, cells)
 
         def render_chr(ch):
+            return space
             if ch in box_chars:
                 cell = bytearray(len(space))
                 render_box_char(ch, cell, width, height)
```

Of course, it will require you to compile kitty.

**Comment by ctrlcctrlv** [comment]
(If my idea works for you, I'll make a PR to make it an official option.)

**Comment by ctrlcctrlv** [comment]
I'm sorry, my previous patch is bad. Please try this one, I'm sure it works on my system this time. My eyesight is bad, and I thought I saw a difference before, but there was none.

![2020-01-31-090757_3043x1942_scrot](https://user-images.githubusercontent.com/838783/73504045-09ead200-4409-11ea-8733-c907990ebb4f.png)

Not at all beautiful, but possible.

```diff
diff --git a/kitty/fonts.c b/kitty/fonts.c
index 0c6d1f43..02a7186a 100644
--- a/kitty/fonts.c
+++ b/kitty/fonts.c
@@ -581,15 +581,6 @@ START_ALLOW_CASE_RANGE
         case ' ':
         case '\t':
             return BLANK_FONT;
-        case 0x2500 ... 0x2573:
-        case 0x2574 ... 0x259f:
-        case 0xe0b0 ... 0xe0b4:
-        case 0xe0b6:
-        case 0xe0b8: // 
-        case 0xe0ba: //   
-        case 0xe0bc: // 
-        case 0xe0be: //   
-            return BOX_FONT;
         default:
             ans = in_symbol_maps(fg, cpu_cell->ch);
             if (ans > -1) return ans;
```

**Comment by kovidgoyal** [comment]
I'm afraid using fonts for box drawing characters is a no-go. They wont
line up properly at different font sizes. You are welcome to use the
patch yourself, but I am not going to accept it as an option in kitty.

**Comment by ctrlcctrlv** [comment]
Oh OK, I understand. Yes, as my screenshot shows, it looks very ugly. I think it might be possible to make a font that understands how Kitty renders which would work, but at that point, we should just add whatever is needed to `box_drawing.py` instead.

**Comment by kovidgoyal** [comment]
Drawing the curve is relatively easy it should be doable using a cubic
bezier. The hard part is drawing an anti-aliased curve that looks good
at different sizes, line thicknesses. Currently the box_drawing.py code
contains code for drawing filled curves like a filled D shape which are
easier. But curved lines somewhat harder.

**Comment by kovidgoyal** [comment]
And I just added support for antialiasing using super sampling which should make this easier.

**Comment by rodrigore** [comment]
Hey @kovidgoyal, how can I test?
Should I clone the last version and should be ok or I have to do something?
Thanks

**Comment by kovidgoyal** [comment]
You need to add @supersampled() to any function whose result you want
anti-aliased. The functions first three arguments must be the buffer,
width and height.
