### ISSUE TITLE
Question: How to execute command on start?

### ISSUE THREAD

**Issue by miguelmota** [kovidgoyal/kitty#2246]
For example on lxde you can do `lxterminal -e tmux` and it'll start the terminal with tmux. I've tied `kitty -e tmux`, `kitty tmux`, and `kitty /bin/bash -c tmux` but the new terminal opens and closes immediately. Not sure if that's intentional or a bug. Is it possible to launch kitty with a command to run?

**Comment by kovidgoyal** [comment]
kitty command is the appropriate syntax. See kitty --help.

Your issues ae caused by tmux, probably because you are trying to use
multiple terminals with a single tmux session. Close all tmux sessions
and then run it.

**Comment by miguelmota** [comment]
@koekeishiya it's a kitty issue because launching tmux with the command flag works with lxterminal, terminator, and konsole. I'm using a different terminal now that doesn't have this issue. Thanks for the reply.

**Comment by weetabix** [comment]
I use that functionality, and it works fine for me. I issue "kitty vi" and I have an open editor. "kitty tmux" worked fine, as did using -e flags on other terminals. 

I'm using Xubuntu, 20.04 and kitty 0.9.3.

**Comment by miguelmota** [comment]
I tried it again and it's working so maybe it was a bad installation when I was trying it last year.

**Comment by alikaramniya** [comment]
I use i3 and solve this problem with below command in .config/i3/config file

bindsym $mod+Return exec kitty -e tmux

**Comment by trxharu** [comment]
I have added a `launch.conf` file in `~/.config/kitty` with following option: `launch sh -c "tmux"`. It works for me.

Note: make sure to add this line in kitty.conf `startup_session launch.conf`

**Comment by paramSonawane** [comment]
> I have added a `launch.conf` file in `~/.config/kitty` with following option: `launch sh -c "tmux"`. It works for me.
> 
> Note: make sure to add this line in kitty.conf `startup_session launch.conf`

This launches tmux with default config for me. (My tmux binary is in different path as i have built it from source)

**Comment by jordannakamoto** [comment]
https://unix.stackexchange.com/questions/43601/how-can-i-set-my-default-shell-to-start-up-tmux

**Comment by shashinvision** [comment]
> ```shell
> if [ -z "$TMUX" ] && [ "$TERM" = "xterm-kitty" ]; then
>   tmux attach || exec tmux new-session && exit;
> fi
> ```

Work for me, thanks

**Comment by jhwheeler** [comment]
For me with Hyprland, I've got it to work with the keyboard shortcut I use to open kitty by adding this to my hyprland.conf: `bind = $mainMod, Q, exec, kitty -e tmux`. So I press alt + q, and it opens kitty with a new tmux session. So if you're not using Hyprland, `kitty -e tmux` should work.
