### ISSUE TITLE
Block Select on selecting with Ctrl+Alt pressed

### ISSUE THREAD

**Issue by pallavagarwal07** [kovidgoyal/kitty#225]
It would be nice to have support for block select like most common linux terminals (urxvt, gnome-terminal). Most terminals allow block select on pressing Ctrl+Alt while selecting.

**Comment by kovidgoyal** [comment]
Press Ctrl+Shift when selecting.

**Comment by kovidgoyal** [comment]
Sorry maybe I misunderstood your feature request, what exactly do you mean by block select?

**Comment by pallavagarwal07** [comment]
Selecting a rectangular block of text. (screenshot from URXVT).


![2017-12-12-145307_1920x1080_scrot](https://user-images.githubusercontent.com/9394044/33876722-358262a4-df1e-11e7-8127-af3496fba1af.png)

**Comment by rankun203** [comment]
@kovidgoyal Is there any news for this feature?

**Comment by kovidgoyal** [comment]
It was implemented years ago.

**Comment by rankun203** [comment]
How to use it? I tried all kinds of key combinations for Ctrl, Command / Win, Option / Alt, Shift, none worked, I'm on macOS, v0.19.1.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/#mouse-features

**Comment by rankun203** [comment]
Great, thanks for your time to implement this and replying here 👍

**Comment by revington** [comment]
@kovidgoyal  the right link is https://sw.kovidgoyal.net/kitty/overview/#mouse-features.

**Comment by danielb2** [comment]
> @kovidgoyal the right link is https://sw.kovidgoyal.net/kitty/overview/#mouse-features.

I don't see instructions for block select here. did they move

**Comment by danielb2** [comment]
oh it does work. tmux was inteferring. how to fix that?
