### ISSUE TITLE
Window border?

### ISSUE THREAD

**Issue by alsonkemp** [kovidgoyal/kitty#2253]
@kovidgoyal Congrats on kitty.  Very nice.

I've got a beginner question: is there any way to set a **window** border and color?  I guess, unlike most others, I'm having a slight problem distinguishing content within kitty (and where to grab to resize).  Is it possible to set a window border?  (I've tried and failed...)

**Comment by alsonkemp** [comment]
e.g.! [here](https://drive.google.com/file/d/1D84h7L9FQHg_eYISRc-L3rKeD49Di7Hv/view?usp=sharing)

**Comment by kovidgoyal** [comment]
If you mean actual OS window borders,they are drawn by the operating
system/window manager, not kitty. You can have kitty ask the OS to *not*
draw them via the hide_window_decorations option in kitty.conf but other
than that there is no control of window decoration from kitty (with one
exception of GNOME under wayland).

**Comment by alsonkemp** [comment]
Thanks for the quick reply.  Looks as though I get to look into Gnome theming...

**Comment by Luflosi** [comment]
Would https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.window_margin_width do what you want? It doesn't allow you to change the color of the border though.
