### ISSUE TITLE
Fallback font is rendered differently than main font

### ISSUE THREAD

**Issue by imran-iq** [kovidgoyal/kitty#2257]
Hi.

I've install `ttf-joypixels` and have gotten emoji working, however i notice that the emojis seem to be drawn with a vertical offset

### Kitty (version 0.15.1)
![image](https://user-images.githubusercontent.com/624456/71785662-45dc7400-2fd0-11ea-982e-cd2c11d6066e.png)

```
~ >>> kitty --debug-font-fallback                                                                                                                                                                                       
[005 15:26:59.100318] Preloaded font faces:
[005 15:26:59.100339] normal face: /usr/share/fonts/TTF/PragmataPro_Mono_R_liga_0828.ttf:0
[005 15:26:59.100347] bold face: /usr/share/fonts/TTF/PragmataPro_Mono_B_liga_0828.ttf:0
[005 15:26:59.100354] italic face: /usr/share/fonts/TTF/PragmataPro_Mono_I_liga_0828.ttf:0
[005 15:26:59.100361] bi face: /usr/share/fonts/TTF/PragmataPro_Mono_Z_liga_0828.ttf:0
U+2728 bold emoji_presentation Face(family=JoyPixels, style=Regular, ps_name=JoyPixels, path=/usr/share/fonts/joypixels/JoyPixels.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
U+1f370 bold emoji_presentation Face(family=JoyPixels, style=Regular, ps_name=JoyPixels, path=/usr/share/fonts/joypixels/JoyPixels.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+2728 bold emoji_presentation Face(family=JoyPixels, style=Regular, ps_name=JoyPixels, path=/usr/share/fonts/joypixels/JoyPixels.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
```

### xfce-terminal comparison
![image](https://user-images.githubusercontent.com/624456/71785699-a5d31a80-2fd0-11ea-9250-edbcc55a9f3c.png)

Another example (hopefully easier to see)
![image](https://user-images.githubusercontent.com/624456/71785728-0eba9280-2fd1-11ea-94e0-2871fda10dff.png)

In kitty the face is kind of getting cut off.
I looked through https://sw.kovidgoyal.net/kitty/conf.html#conf-kitty-fonts, but there doesn't seem to be anything to changing how the fallback font is rendered. For reference here is the output of `kitty --debug-config`

```
kitty 0.15.1 created by Kovid Goyal
Linux linux-desktop 5.4.6-2-MANJARO #1 SMP PREEMPT Tue Dec 24 15:55:20 UTC 2019 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.1.5
DISTRIB_CODENAME=Juhraya
DISTRIB_DESCRIPTION="Manjaro Linux"
Loaded config files: /home/imran/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_border_color     Color(red=116, green=115, blue=105)
active_tab_background   Color(red=45, green=45, blue=45)
active_tab_foreground   Color(red=211, green=208, blue=200)
background              Color(red=45, green=45, blue=45)
color0                  Color(red=45, green=45, blue=45)
color1                  Color(red=242, green=119, blue=122)
color10                 Color(red=153, green=204, blue=153)
color11                 Color(red=255, green=204, blue=102)
color12                 Color(red=102, green=153, blue=204)
color13                 Color(red=204, green=153, blue=204)
color14                 Color(red=102, green=204, blue=204)
color15                 Color(red=211, green=208, blue=200)
color16                 Color(red=249, green=145, blue=87)
color17                 Color(red=210, green=123, blue=83)
color18                 Color(red=57, green=57, blue=57)
color19                 Color(red=81, green=81, blue=81)
color2                  Color(red=153, green=204, blue=153)
color20                 Color(red=160, green=159, blue=147)
color21                 Color(red=232, green=230, blue=223)
color3                  Color(red=255, green=204, blue=102)
color4                  Color(red=102, green=153, blue=204)
color5                  Color(red=204, green=153, blue=204)
color6                  Color(red=102, green=204, blue=204)
color7                  Color(red=211, green=208, blue=200)
color8                  Color(red=116, green=115, blue=105)
color9                  Color(red=242, green=119, blue=122)
copy_on_select          clipboard
cursor                  Color(red=211, green=208, blue=200)
font_family             PragmataPro Mono Liga
font_size               14.0
foreground              Color(red=211, green=208, blue=200)
inactive_border_color   Color(red=57, green=57, blue=57)
inactive_tab_background Color(red=57, green=57, blue=57)
inactive_tab_foreground Color(red=160, green=159, blue=147)
repaint_delay           6
selection_background    Color(red=211, green=208, blue=200)
selection_foreground    Color(red=45, green=45, blue=45)
url_color               Color(red=160, green=159, blue=147)
```

**Comment by ctrlcctrlv** [comment]
I'm sorry, I looked hard but I don't see a problem.

Even under magnifier, emoji :stuck_out_tongue_winking_eye: doesn't look cut off to me?

**Comment by imran-iq** [comment]
![image](https://user-images.githubusercontent.com/624456/71928036-c0d69380-3164-11ea-9129-4f7aa23f204d.png)

does this help?

**Comment by ctrlcctrlv** [comment]
Hello friend:

Thank you for the image, I can see it now. I have poor vision, and thought you meant that the side was cut, not the bottom.

I decompiled the emoji font, downloaded from repositories, and realized it only contains rasters?? CBDT/CBLC, apparently a deprecated format for storing rasters in SFNT files. I don't think we anticipated that. (The current format is called `sbix` for rasters and either `COLR/CPAL` or `SVG ` for vectors.)

This format is like the bitmap formats of old, with bitmap strikes and then emoji rendered at those sizes. I would recommend not using the font.

**Comment by kovidgoyal** [comment]
I suggest using noto-fonts-emoji, it works better.

**Comment by imran-iq** [comment]
I switched to noto-fonts-emoji as recommended, and it seems to have a similar issue (tongue is cut off, image gets larger if you click on it)

![zoomed](https://user-images.githubusercontent.com/624456/72026579-f2755a80-3249-11ea-8f04-d2981c7a5d9a.png)

```
~ >>> kitty --debug-font-fallback                                                                                 
[008 19:00:38.146563] Preloaded font faces:
[008 19:00:38.146585] normal face: /usr/share/fonts/TTF/PragmataPro_Mono_R_liga_0828.ttf:0
[008 19:00:38.146593] bold face: /usr/share/fonts/TTF/PragmataPro_Mono_B_liga_0828.ttf:0
[008 19:00:38.146600] italic face: /usr/share/fonts/TTF/PragmataPro_Mono_I_liga_0828.ttf:0
[008 19:00:38.146607] bi face: /usr/share/fonts/TTF/PragmataPro_Mono_Z_liga_0828.ttf:0
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
U+1f92a emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0)
```

**Comment by imran-iq** [comment]
I noticed that some applications (namely csgo) also have a similar issue where unicode/emoji (in player names) are rendered offset similar to the images above

(side note i have a laptop installed with manjaro and the same issue happens there)

I did a little digging and I feel like this is an issue with the freetype library (afaict both csgo and kitty use freetype for loading fonts)

xfce-terminal on the other hand relies entirely on GTK which uses a [pango](https://gitlab.gnome.org/GNOME/pango) for text rendering, and a quick [search](https://gitlab.gnome.org/GNOME/pango/-/blob/master/NEWS#L69) shows that they no longer rely on freetype for font loading.

That being said I /feel/ like this not a valid issue any more as this is not specific to kitty

**Comment by kovidgoyal** [comment]
![emoji](https://user-images.githubusercontent.com/1308621/82110044-e69a2780-9758-11ea-9947-888cc3ed6b7b.png)
This is what it looks like on my system, with freetype 10.2 and kitty 0.17.4

**Comment by imran-iq** [comment]
I have freetype 10.1 and kitty 0.17.4
![image](https://user-images.githubusercontent.com/624456/82111145-fbeb6380-9710-11ea-9eb4-dc1e2372422b.png)

top right, kitty with my regular font, top left kitty with droids sans mono, bottom xfce-terminal with droid sans mono

I'm just going to chalk this up to something being screwy with manjaro (dont have this issue on mac os)

**Comment by thisguychris** [comment]
> I suggest using noto-fonts-emoji, it works better.

Hey @kovidgoyal, I apologize in advance for resurrecting this issue, but how do you set `noto-fonts-emoji` to be used as a fallback font in kitty? All I see reference in https://sw.kovidgoyal.net/kitty/conf.html#conf-kitty-fonts is for symbol_map?

Is there an option to set the fallback font for glyphs, not in my main font?

**Comment by kovidgoyal** [comment]
Symbol map does the trick, default fallback is mediated by your
operating system libraries. If you are on Linux you can configure it via
fontconfig, no idea on macOS.
