### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by mfilenko** [kovidgoyal/kitty#2258]
I might have overlooked that, but is there a way to define a default layout?

My working session with Kitty usually starts with switching to the tall layout by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>l</kbd>. I believe, there should be a better way.

Maybe there's a way to map a keystroke that will open a new window in a certain layout as an alternative solution?

Anyways, thank you for building Kitty! It's a very worthwhile terminal replacement 👍

**Comment by Luflosi** [comment]
I think you can use https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.enabled_layouts and specify the tall layout first.

**Comment by kovidgoyal** [comment]
The first layout listed in enabled_layouts in kitty.conf will be the
default. And you can use the combine operator to create a new window and
change its layout with a single keystroke.

**Comment by mfilenko** [comment]
Hey guys,

Thank you very much for your help! I've clearly read documentation not attentive enough :sweat_smile:

Although I'm a bit confused now as <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>l</kbd> with default configuration and specifying `enabled_layouts` in the configuration explicitly result in different behaviour.

This is five windows opened after I've pressed <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>l</kbd> once to switch to the tall layout with the default configuration (`enabled_layouts` commented out):

![Screen Shot 2020-01-07 at 10 21 01](https://user-images.githubusercontent.com/199476/71974539-0604cf00-3212-11ea-9bc4-6ea57d65428f.png)

This is five windows opened with `enabled_layouts` set to `tall,fat,grid,horizontal,vertical,stack` in the configuration file explicitly:

![Screen Shot 2020-01-07 at 10 22 01](https://user-images.githubusercontent.com/199476/71974552-0bfab000-3212-11ea-9508-4710dbcfdab7.png)

Here are the screencasts for better illustration:
* [Default config with switching to tall manually](https://www.dropbox.com/s/o1j9pc51t7el4g7/Screen%20Recording%202020-01-07%20at%2009.55.20.mov).
* [Explicit list of enabled layouts with tall being the first one](https://www.dropbox.com/s/l4wdiguy4jh2t3f/Screen%20Recording%202020-01-07%20at%2009.57.48.mov).

The former behavior seems to be more intelligent to me and **I'm trying to configure my Kitty to behave exactly this way** (so I don't have to press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>l</kbd> every time I start it).

Maybe I misunderstand what <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>l</kbd> does, but it feels like with no enabled layouts specified Kitty tries to open a new window in the most optimal way having just fat layout as the first option.

My environment is macOS 10.15.2, kitty 0.15.1 (Homebrew).

**Comment by kovidgoyal** [comment]
The default configuration is ['fat', 'grid', 'horizontal', 'stack', 'tall', 'vertical'] pressing ctrl+l once is getting you grid layout not tall layout. In the second screenshot, you are in tall layout. Whatever layout you put in enabled_layouts fist will be the layout kitty starts with. I think you are misunderstanding what each layout does. I suggest you put only a singlelayout in enabled layouts and familiarise yourself with what they look like.

**Comment by mfilenko** [comment]
Hey,

Thanks a lot for taking a moment to clarify this for me! I really appreciate it :)

I had false assumptions I was coming from! Now it's perfectly clear and Kitty behaves exactly the way I want it to behave 👍
