### ISSUE TITLE
Add a help menu item

### ISSUE THREAD

**Issue by ramonpoca** [kovidgoyal/kitty#2260]
When starting with kitty I find myself going back and forth to the documentation for hotkeys.
As the documentation is html, it would be easy to package it in the "Resources" folder and add an item to the menu.

About the menu item, as the menu is created programatically, it should be added manually.

**Comment by kovidgoyal** [comment]
dup of #2236

**Comment by Luflosi** [comment]
This is not a duplicate as this issue is about adding the documentation to kitty itself and my PR only added the menu item and no documentation. I'll look into it.

**Comment by kovidgoyal** [comment]
While having a local copy might be useful for machines that dont have
internet connections, other than that I dont really see a point. The
website is essentially the same.

**Comment by ramonpoca** [comment]
I believe that it would be possibe to render the documentation as HTML and add it to the package. Then it will be presented by the MacOS help system, and become a part of binary distributions.

**Comment by Luflosi** [comment]
@ramonpoca I can probably add the menu item but you'll need to create the HTML files, I don't really know anything about the macOS help system.
