### ISSUE TITLE
Text typed by X SendEvent (XTest/xdotool/xautomation) is weirdly affected by modifiers

### ISSUE THREAD

**Issue by Boolean263** [kovidgoyal/kitty#2261]
The X protocol has a SendEvent request, which the XTest extension to X (and programs that use it, such as xdotool and xautomation) uses to allow a program to use this feature to send keystrokes to other X windows. I use it to send long strings of text that I'd rather not retype manually, to several windows (not just kitty, but web browsers, text editors, etc.)

Kitty properly processes the text of these simulated keystrokes, but applies the keyboard modifiers that are currently being held down by the user, not the ones that are being sent by XTest. 

![kitty-xtest-demo](https://user-images.githubusercontent.com/2158683/71910559-1cdaf100-3140-11ea-912d-fd8142441cb0.png)

The above screenshot demonstrates a comparison between xterm, urxvt, [st](https://st.suckless.org/), and kitty. (Examples are just terminals I have installed; no other feature comparison is intended.) In each child terminal, the command `xdotool getactivewindow` is run within that terminal to get the window's ID number. These are passed to the example script which types `AbCd!2#4` in each terminal.

The first run of `xdotest.sh` was run with no keyboard modifiers held down. The second run has a `sleep` in front of it to give me time to hold the Shift key down before it runs again. The kitty window shows two different results between the two runs, which is not desirable.

----

This has been previously reported in other issues such as #2122 and #639. The response to those issues was to instruct the reporter to configure kitty to enter the text instead. This is a good workaround, but does not address the underlying problem of kitty incompletely supporting SendEvent.

If this behaviour will not be addressed, I suggest removing SendEvent support entirely from kitty. It is better to not have the feature at all than to incompletely support it. This would also be more secure depending on who you ask. (xterm disables SendEvent support by default, and docs for the `allowSendEvents` option call it a ["very large security hole"](https://linux.die.net/man/1/xterm).)

Thank you for sharing your hard work on Kitty (and calibre!) with us all.

**Comment by kovidgoyal** [comment]
If you are running X you have *no* isolation of programs from one
another, one program can do pretty much anything to another program.
Disabling XTest (not XSendEvent) is not going to fix that. And if you
want to do it, the correct place to do it is in the server, not
individual application. So I dont see any value in that.

As for fixing the actual issue with XTest generated events, patches are
welcome, but I am personally not going to work on it, since kitty has
various ways to send text to it all of which are superior to XTest and
cross platform.
