### ISSUE TITLE
X Error preventing Kitty from starting 

### ISSUE THREAD

**Issue by jonasreitemeyer** [kovidgoyal/kitty#2262]
Hi, 

i am on a fresh arch install and get this error when trying to start kitty:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Serial number of failed request:  337
  Current serial number in output stream:  338
```

Xorg -version returns
```
X.Org X Server 1.20.6
```
 
Kernel version: 5.4.8

The problem also occurs when building kitty from source.

Btw, love your work :)

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. That error indicates you have
disabled MIT-SHM on your X server. Re-enable it and you will be fine.

**Comment by jamesb6626** [comment]
I had a similar issue after an upgrade on arch in virtualbox, despite no other changes.
Also, MIT-SHM is listed in the output of `xdpyinfo -queryExtensions`.
I narrowed it down to an upgrade of mesa, and reported it over here:
https://gitlab.freedesktop.org/mesa/mesa/issues/2291
