### ISSUE TITLE
Small rendering of special characters

### ISSUE THREAD

**Issue by j-james** [kovidgoyal/kitty#2266]
Kitty renders some special characters comparatively smaller than others, using the monospace font and all auto settings. 

This problem doesn't happen with the Monospace 12 font on xfce-terminal. 

![2020-01-07-155508](https://user-images.githubusercontent.com/35242550/71939304-12801d80-3167-11ea-9f5c-dcbe41fdf450.png)
![2020-01-07-155508 (copy 1)](https://user-images.githubusercontent.com/35242550/71939305-1449e100-3167-11ea-956e-340ae3ca58ee.png)

**Comment by j-james** [comment]
Different settings from the [default](https://sw.kovidgoyal.net/kitty/conf.html#sample-kitty-conf) are as follows:

```
font_size 12.0
enable_audio_bell no
window_margin_width 5.0
foreground #cfd8dc
background #263238
```

**Comment by kovidgoyal** [comment]
What charater is that? If it is a private use character you need to follow it with a space. https://sw.kovidgoyal.net/kitty/faq.html#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by j-james** [comment]
It's followed by a space in my `PS1`. 

`PS1='\[\033[01;32m\][🜃 \W\[\033[01;32m\]]\$\[\033[00m\] '`

**Comment by kovidgoyal** [comment]
Looks correct to me:

![Screenshot_20200109_081033](https://user-images.githubusercontent.com/1308621/72033195-93e6c580-32b7-11ea-8390-34050a982156.png)

**Comment by j-james** [comment]
Strange, I'm unable to reproduce. 

![2020-01-08-233911](https://user-images.githubusercontent.com/35242550/72047782-282d3a00-3270-11ea-8241-3fb1a3d78f01.png)

Does the character show up as large in a shell prompt on your end?

**Comment by kovidgoyal** [comment]
yes shell prompts are no different from ordinary text as far as a
terminal isconcerned.

**Comment by kovidgoyal** [comment]
Make sure you are using an up-to-date version of kitty.

**Comment by j-james** [comment]
Yup, `0.15.1`.

That's weird then - since there's a space after that character in my shell prompt, it _should_ be showing up correctly.

Extra strange that I can't reproduce in the Python environment, even with all default settings. 

![2020-01-09-082008](https://user-images.githubusercontent.com/35242550/72084711-d6f56880-32b8-11ea-9daf-3344bc8c7757.png)

**Comment by kovidgoyal** [comment]
post kitty --debug-config

**Comment by j-james** [comment]
```
kitty 0.15.1 created by Kovid Goyal
Linux manjaro 5.4.6-2-MANJARO #1 SMP PREEMPT Tue Dec 24 15:55:20 UTC 2019 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.1.5
DISTRIB_CODENAME=Juhraya
DISTRIB_DESCRIPTION="Manjaro Linux"
Loaded config files: /home/teal/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=38, green=50, blue=56)
color0                Color(red=38, green=50, blue=56)
color1                Color(red=255, green=85, blue=85)
color10               Color(red=85, green=255, blue=85)
color11               Color(red=255, green=255, blue=85)
color12               Color(red=85, green=85, blue=255)
color13               Color(red=255, green=85, blue=255)
color14               Color(red=85, green=255, blue=255)
color2                Color(red=85, green=255, blue=85)
color3                Color(red=255, green=255, blue=85)
color4                Color(red=85, green=85, blue=255)
color5                Color(red=255, green=85, blue=255)
color6                Color(red=85, green=255, blue=255)
color7                Color(red=170, green=170, blue=170)
color8                Color(red=0, green=0, blue=0)
color9                Color(red=255, green=85, blue=85)
enable_audio_bell     False
font_size             12.0
foreground            Color(red=207, green=216, blue=220)
selection_background  Color(red=207, green=216, blue=220)
selection_foreground  Color(red=38, green=50, blue=56)
update_check_interval 24.0
window_margin_width   5.0
```

**Comment by kovidgoyal** [comment]
Dont see anything suspicious there

**Comment by j-james** [comment]
I'm puzzled.

The issue isn't vertical encroachment either.

![2020-01-09-183451](https://user-images.githubusercontent.com/35242550/72121052-bf48cf00-330e-11ea-88b5-dadfd45f7cf3.png)

**Comment by kovidgoyal** [comment]
There is no vertical encroachment, characters are always clipped to cell boundaries in kitty. What font are you using for this character? I suggest installing symbola, check with --debug-font-fallback

**Comment by j-james** [comment]
[Seems to be Bitstream Vera Sans Mono, but it looks like 🜃 is falling back to Noto Sans Symbols.](https://gist.github.com/j-james/3fbd8131ce5e731509d28d55cb5abcc7)

xfce-terminal uses the same font without the rendering issue.

**Comment by kovidgoyal** [comment]
That's likely a non-scaleable bitmapped font, as I said, install
symbola.

**Comment by j-james** [comment]
Thank you for all your help - Symbola works perfectly!
