### ISSUE TITLE
Raise graphics storage quota so icat doesn't delete images

### ISSUE THREAD

**Issue by kovasap** [kovidgoyal/kitty#2269]
I'm having an issue where i can only display ~3 images at a time in kitty using icat.  I was reading here: https://sw.kovidgoyal.net/kitty/graphics-protocol.html#image-persistence-and-storage-quotas that there is a quota of 320MB that, once met, will lead to deletion of old images.  I think this is what I'm experiencing.  Can I raise this quota in kitty to something higher?

**Comment by kovidgoyal** [comment]
320MB should be plenty for more than 3 images. What size are your
images?

**Comment by kovasap** [comment]
Yeah, good point, they are very small (<30KB).  Hmm, I wonder what else could be causing this.  I am running over multiplexed ssh.

**Comment by kovidgoyal** [comment]
What is multiplexed ssh?

**Comment by kovasap** [comment]
It's an option to run multiple ssh sessions over the same connection (like multiple terminals).  A description is here: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing.  I just tested without it enabled and I have the same problem.  Sorry for the noise!

**Comment by kovidgoyal** [comment]
I cant replicate over plain ssh and that form of multiplexing is irrelevant. I'd need some way to reproduce. Maybe attach a zip file with enough images to trigger it. I tried catting 8 medium sized images over ssh and they all displayed in the scrollback buffer. Try running the shell and kitty with default configs.

**Comment by kovidgoyal** [comment]
closing in the absence of a way to replicate. If you can come up with one will be ahppy to re-open
