### ISSUE TITLE
Window opening in weird order

### ISSUE THREAD

**Issue by Luis-Hebendanz** [kovidgoyal/kitty#2275]
I have kitty configured with following config:
```
font_family      monospace
font_size        16.0
bold_font        auto
italic_font      auto
bold_italic_font auto

scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
focus_follows_mouse yes

term xterm-256color
mouse_hide_wait 3.0

touch_scroll_multiplier 5.0
touch_scroll_multiplier 4.0

copy_on_select yes
draw_minimal_borders yes
window_padding_width 0.1
inactive_text_alpha 0.8
enabled_layouts grid, stack

map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter 3
map f11 kitten zoom_toggle.py

map ctrl+down           next_window
map ctrl+up             previous_window
map ctrl+enter          new_window
```
If this is my current window layout:
![1578761261_grim](https://user-images.githubusercontent.com/22085373/72207558-9a816280-349a-11ea-87e4-c7db5f4ff9d5.png)

and I spawn a new window with ctrl+enter the window on the bottom-right gets moved to the left

![1578761278_grim](https://user-images.githubusercontent.com/22085373/72207560-9ead8000-349a-11ea-9523-3ebdf0f62146.png)

What I would expect is that the new window would spawn at the bottom left.

**Comment by kovidgoyal** [comment]
Why would you expect that? New windows get added after all existing
windows, and after all windows means bottom right. If you want a new 
window to open next to the currently active one, use --location=neighbor
in the launch command mapping.
