### ISSUE TITLE
Configure how many full size windows are present in Tall and Fat layouts

### ISSUE THREAD

**Issue by gsteff** [kovidgoyal/kitty#2276]
None of Kitty's current layouts can efficiently display four windows on very wide screens (say, 34 inch). The best current candidates are "Grid" and "Tall", but Grid's windows are excessively wide (for typical shell or text editor use), and the three side windows in Tall are too short (no matter what value you give the bias). The most practical four window layout on widescreen monitors, I think, would be "TwoTall", a variant of the Tall layout that makes the first two windows full height, before vertically stacking the remainder. Alternatively, perhaps the Tall layout could be given a second integer parameter that indicates how many windows should be made full height before stacking the others.

**Comment by ctrlcctrlv** [comment]
If Kovid wants to do this that's his right... But I'd say giving users finer grained control over layouts is a better fix. Ultra wide monitors might need a "ThreeTall". And I'm not sure it makes sense to add a TwoTall without a TwoFat. (TooFat? But then again I'm not the subject here, Kitty is. :stuck_out_tongue_winking_eye:)

**Comment by kovidgoyal** [comment]
Not something I am personally interested in but am happy to accept a
patch that adds a setting to the Tall and Fat layouts for number of
single window columns/rows. It's basically a couple of classes in
layout.py that you would need to modify. Should be a fun couple of hour
project.

**Comment by gsteff** [comment]
Thanks!
