### ISSUE TITLE
display region support in `kitty icat`

### ISSUE THREAD

**Issue by soredake** [kovidgoyal/kitty#228]
To support displaying images in [ranger](https://github.com/ranger/ranger/blob/master/ranger/ext/img_display.py) and [vifm](https://wiki.vifm.info/index.php?title=How_to_preview_images#Setup)

**Comment by kovidgoyal** [comment]
Can you elaborate on exactly what you want? Displaying a part of an image? Choosing what part of the screeen to display it in? All these things are already supported by the graphics protocol, which is what applications like ranger should use. But I am willing to add command line options for these to kitty icat as well, if needed. 

See https://github.com/kovidgoyal/kitty/blob/master/graphics-protocol.asciidoc#controlling-displayed-image-layout

for how to display parts of images in the graphics protocol.

**Comment by soredake** [comment]
I want 4 command line options (described later) in`kitty icat`
Ranger reference:
https://github.com/ranger/ranger/blob/master/ranger/ext/img_display.py#L187-L194

Vifm reference:
```
%px x coordinate of top-left corner of preview area;
%py y coordinate of top-left corner of preview area;
%pw width of preview area;
%ph height of preview area.

X=$1
Y=$2
COLUMNS=$3
LINES=$4
FILENAME=$5
e.g. fileviewer *.jpg kitty icat %px %py %pw %ph $file
```

**Comment by kovidgoyal** [comment]
These co-ords are in cells or pixels?

**Comment by soredake** [comment]
`They are expressed in number of characters.`
https://github.com/ranger/ranger/blob/master/ranger/ext/img_display.py#L151-L194

**Comment by soredake** [comment]
e.g. i want functionality to display images in needed in the right place like the ranger and vifm doing with w3mimdisplay help
![kittyicat](https://user-images.githubusercontent.com/5204968/34003732-efcb82be-e0ed-11e7-9c7d-a1fc1bcd774d.png)

**Comment by soredake** [comment]
@kovidgoyal tried with vifm (`fileviewer *.jpg,*.jpeg kitty icat  --transfer-mode=stream --place=%pwx%ph@%pxx%py %c`) and kitty icat returns `Must be run in a terminal, stdout is currently not a terminal`

**Comment by kovidgoyal** [comment]
I have no idea how vifm works, but kitty icat will return that error is isatty() returns false for stdout or stdin. Is vifm redirecting those?
