### ISSUE TITLE
Kitty config for shell 

### ISSUE THREAD

**Issue by irfn** [kovidgoyal/kitty#2280]
I am trying to get Kitty to run a shell command instead of plain shell
eg:
`shell "fish -c tmux new-session -A -s kitty-default"`
or 
`shell fish -c tmux new-session -A -s kitty-default`
or 
`shell /usr/local/bin/mycommand`

Is there a way to achieve this behaviour?

**Comment by irfn** [comment]
Should update the docs accordingly on what is a valid value for shell

**Comment by kovidgoyal** [comment]
kitty my-command my-command-arg1 my-command-arg2 ...

kitty --help
