### ISSUE TITLE
Set the equivalent of Vim's 'nosplitbelow' when creating windows

### ISSUE THREAD

**Issue by resolritter** [kovidgoyal/kitty#2283]
Hello! And once again thank you for creating my favorite terminal program. :-)

I've read through [the documentation on `new-window`](https://sw.kovidgoyal.net/kitty/remote-control.html?highlight=new%20window#kitty-new-window), but I haven't been able to find a setting where I could specify where the window would pop up. By default, without any layout specification, using `kitty @ new-window` always splits to the newly-created window (like Vim's `splitbelow` setting). 

While I wonder if one solution would be to move the split after creating it, I'd like to not have to do those two separate commands if possible. What I want is to straight away create the split directly on top without messing with my current layout. Is it possible currently? Could it be possible in the future?

Thank you for your time.

**Comment by kovidgoyal** [comment]
You can choose to either create new windows after all existing windows
or after the current window or before all existing windows. This is
achieved by using the --location argument to the launch command. https://sw.kovidgoyal.net/kitty/launch.html

And if you want to both launch and move a window you can do so using
combine to map multiple actions to a single key stroke.
