### ISSUE TITLE
Config file on windows 10

### ISSUE THREAD

**Issue by AndiLeni** [kovidgoyal/kitty#2287]
Hello,

I need some advice. I downloaded Kitty from fosshub and it works fine, but it does not find my config file. Where do I have to place it to make kitty find it?

And another question: it it possible to create macros?  
F.e. I frequently need to insert some text and wanto to create a shortcut for this. (similar to conemu which assigns a ``printf()`` method to a shortcut.)

Regards
Andi

**Comment by Luflosi** [comment]
This is a wrong kitty. The one you are probably looking for is here: https://github.com/cyd01/KiTTY/

**Comment by AndiLeni** [comment]
You are right. I am deeply sorry.

**Comment by Luflosi** [comment]
Don't worry too much, it's fine.
