### ISSUE TITLE
Using `ctrl+c` for copy removes `ctrl+c` for SIGINT on Arch Linux

### ISSUE THREAD

**Issue by tsujp** [kovidgoyal/kitty#2289]
Using the same binding on macOS works, I can still copy and paste. On Linux binding copy/paste to `ctrl+c` removes functionality as above.

I'm currently using `ctrl+shift+c` but I'd prefer to use `ctrl+c` again and keep the SIGINT behaviour. In my macOS config I simply have `copy_to_clipboard` bound as `cmd+c` and I've tried `ctrl+c` directly instead of `kitty_mod`.

```
clear_all_shortcuts yes
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
```

**Comment by ctrlcctrlv** [comment]
Why not using `copy_or_interrupt`?

**Comment by kovidgoyal** [comment]
Bind ctrl+c to copy_or_interrupt

**Comment by tsujp** [comment]
My mistake for missing that.
