### ISSUE TITLE
Clicking-to-open local directories/files seems buggy 

### ISSUE THREAD

**Issue by sts10** [kovidgoyal/kitty#2292]
New Kitty user here. Everything's working great for me so far on macOS (10.14), but I found something a little peculiar that may be a bug. 

I have a command-line tool that prints the path to a local directory to the terminal, like `file:///Users/sts10/path/to/directory/`. In Kitty (0.15.1), when I try to use the mouse to open the directory in Finder by holding down Shift+Ctrl and clicking on the text of the path, it _only_ works if I click in the small space between the `:` and the first `/`. If I hover or click anywhere else on the path, Kitty seems to treat it like normal text. 

Is this expected behavior? (I can click anywhere on `http` URLs to open them.)

**Comment by kovidgoyal** [comment]
And note you might be interested in:
https://sw.kovidgoyal.net/kitty/kittens/hints.html

**Comment by sts10** [comment]
Thanks for getting to this so quickly! Looking forward to testing your fix in the next release (or sooner, if I get up the courage to build from source).

**Comment by Luflosi** [comment]
Building from source is pretty easy, especially on macOS, see https://sw.kovidgoyal.net/kitty/build.html.

**Comment by sts10** [comment]
Yeah, I was just poking around and it did look pretty straight forward. I just tried cloning the repo and running `make` (hoping dependencies would be fine as is), but I got this error:

```
Linking kittens/unicode_input/unicode_names ...
clang -Wextra -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -O3 -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidden -flto -Ikitty -I/Users/sschlinkert/.pyenv/versions/3.8.0/include/python3.8 -Wall -O3 -shared -flto build/unicode_names-unicode_names.c.o -ldl -framework CoreFoundation -L/Users/sschlinkert/.pyenv/versions/3.8.0/lib -lpython3.8 -Wl,-stack_size,1000000 -framework CoreFoundation -o build/kittens/unicode_input/unicode_names.so
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```

I'd guess that it's probably due to a missing or outdated dependency — and tbh I'd rather not go on an installation mad-dash on my work computer right now.
