### ISSUE TITLE
Glyphs which slightly overflow bounds are resized to fit

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#2294]
I'm sorry if this has been pointed out before, but I noticed it today.

In some fonts it's more serious than others; sometimes the difference is so small one would hardly notice. Of course the difference is directly proportional to how much overflow there is.

Take a look at the M's (TT2020 Style G):

![2020-01-17-200201_2039x1732_scrot](https://user-images.githubusercontent.com/838783/72611082-1892ad00-3964-11ea-9b3d-f84b4e05b177.png)

Some of them are slightly smaller. It's much more evident in TT2020 Style B, where one M is much smaller than the others:

![2020-01-17-200400_2039x1732_scrot](https://user-images.githubusercontent.com/838783/72611182-5d1e4880-3964-11ea-9ced-0dca49d3ae27.png)

Not only my exotic fonts are affected. One of the most common monospace fonts, Nimbus Mono PS, is affected as well:

![2020-01-17-200811_1037x440_scrot](https://user-images.githubusercontent.com/838783/72611394-f188ab00-3964-11ea-98f6-140eb1c12383.png)

How hard is it to allow the sprite inside a cell to overflow that cell? And should we allow it by default if the overflow is &le; _n_ pixels?

**Comment by ctrlcctrlv** [comment]
Oh, and by the way, this issue can be worked around via e.g.:

```
adjust_column_width 109%
```

for Nimbus Mono PS, and 105% for TT2020 Style B.

(This might be enough for Kovid to close it, but the question about overflow remains in my mind, as it doesn't look as it would in other terminal emulators which allow the contents of a cell to slightly overflow it.)

**Comment by kovidgoyal** [comment]
I'm afraid its impossible. Each cell in kitty is rendered separately so
one cell cannot overflow into another, unless they are part of a
ligature and then only horizontally not vertically.
