### ISSUE TITLE
Run kitty remote control in background

### ISSUE THREAD

**Issue by CD3** [kovidgoyal/kitty#2297]
I am using kitty's remote control feature to change the terminal colors. I would like to run the command in the background so that it returns immediately, but it suspends instead

```
$ kitty @ set-colors foreground=red &                                                                                                                                                                           [1] 17078
$
[1]  + suspended (tty output)  kitty @ set-colors foreground=red
$ fg
[1]  + continued  kitty @ set-colors foreground=red
$
```
The colors do not get changed until the process is brought back to the foreground. From what I've read, this is caused by the process connecting to a tty. Is there a way around this?

**Comment by kovidgoyal** [comment]
Dont use a tty use a socket for remote control. 
See --listen

**Comment by CD3** [comment]
Perfect. Thanks.
