### ISSUE TITLE
kitty_mod alt and set_tab_title remapped, alt+t still tries to set tab title (x86)

### ISSUE THREAD

**Issue by kevinclevenger** [kovidgoyal/kitty#2298]
Arch x86_64, US keyboard, LC_*=en_US.UTF-8
kitty_mod alt OR kitty_mod alt+shift OR kitty_mod ctrl+alt
map ctrl+shift+z set_tab_title <literally anything can be used, I tried 7 or 8 key combinations and saw the same behavior>
no other key overrides set

kitty_mod+t still invokes set tab title, does not spawn a tab
ctrl+shift+z also still invokes set tab title

// due to wm and other mappings I can't really use ctrl, ctrl+shift, or win for kitty_mod

**Comment by kovidgoyal** [comment]
That's because set_tab_title is defined as kitty_mod+alt+t so setting
kitty_mod to alt will result in it being alt+t. Map alt+t to whatever
you need explicitly in your kitty.conf.

**Comment by kevinclevenger** [comment]
Yes I did. There's a bug using "kitty_mod alt" + "map kitty_mod+t new_tab"

What does work is unmapping it first:
kitty_mod alt
map kitty_mod+t no_op
map kitty_mod+t new_tab

If you just use:
kitty_mod alt
map kitty_mod+t new_tab

then kitty_mod+t will just fire set_tab_title

**Comment by kovidgoyal** [comment]
I cannot replicate

kitty --config NONE -o "kitty_mod alt" -o "map kitty_mod+t new_tab"

and alt+t runs new_tab

**Comment by kevinclevenger** [comment]
I tested on a second host with the exact same config (minus the no_op) and it works as expected, so there must be something going on specific to the first host. Apologies for the noise.
