### ISSUE TITLE
Kitty builds, but fails tests.

### ISSUE THREAD

**Issue by Robgambrill** [kovidgoyal/kitty#23]
Hi, 

 I am getting some odd behavior trying to build kitty. If you have a minute could you look at the following and see if you can spot what is going on?

On slackware64 14.1 I already had setup python3.5.1 which is working fine.

 I removed glew1.9.0 and then built glew2.0 and tested it. Test programs work OK.

 Then I cloned the glfw3 repository on github and built that. All seem to work fine and pass included tests. (BTW: I also tried the latest stable release with the same results).

I then built kitty and it compiled without error.

 But when I tried to run test.py I got some undefined symbol errors. In order of appearance they were...

undefined symbol: XineramaQueryScreens
undefinded symbol: XcursorImageCreate
undefined symbol: XRRFreeScreenResources

... I fixed those by adding the following lines to setup.py around line 78...

    ldflags.append('-lXinerama')
    ldflags.append('-lXcursor')
    ldflags.append('-lXrandr') 

 After rerunning setup.py, kitty builds fine again, test.py now runs but produces the following errors...

======================================================================
FAIL: test_simple_parsing (kitty_tests.parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/kitty-master/kitty_tests/parser.py", line 60, in test_simple_parsing
    self.ae(str(s.line(4)), '\u30cb\u30c1 ')
    pb = functools.partial(<bound method TestParser.parse_bytes_dump of <kitty_tests.parser.TestParser testMethod=test_simple_parsing>>, <fast_data_types.Screen object at 0x27c1d10>)
    s = <fast_data_types.Screen object at 0x27c1d10>
    self = <kitty_tests.parser.TestParser testMethod=test_simple_parsing>
AssertionError: '\u30cb\u30c1   ' != '\u30cb\u30c1 '
- \u30cb\u30c1   
?    --
+ \u30cb\u30c1 

======================================================================
FAIL: test_char_manipulation (kitty_tests.screen.TestScreen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/kitty-master/kitty_tests/screen.py", line 129, in test_char_manipulation
    self.ae(str(s.line(0)), ' x\u30b3 ')
    init = <function TestScreen.test_char_manipulation.<locals>.init at 0x7f1dbfa212f0>
    s = <fast_data_types.Screen object at 0x27c1d10>
    self = <kitty_tests.screen.TestScreen testMethod=test_char_manipulation>
AssertionError: ' x\u30b3\u30b3 ' != ' x\u30b3 '
-  x\u30b3\u30b3 
?    -
+  x\u30b3 

======================================================================
FAIL: test_draw_char (kitty_tests.screen.TestScreen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/kitty-master/kitty_tests/screen.py", line 60, in test_draw_char
    self.ae(str(s.line(0)), '\u30b3\u30b3x')
    s = <fast_data_types.Screen object at 0x27c1d10>
    self = <kitty_tests.screen.TestScreen testMethod=test_draw_char>
AssertionError: '\u30b3\u30b3x  ' != '\u30b3\u30b3x'
- \u30b3\u30b3x  
?    --
+ \u30b3\u30b3x

======================================================================
FAIL: test_utils (kitty_tests.datatypes.TestDataTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/kitty-master/kitty_tests/datatypes.py", line 268, in test_utils
    self.ae(tuple(map(wcwidth, 'a1\0\u30b3')), (1, 1, 0, 2))
    self = <kitty_tests.datatypes.TestDataTypes testMethod=test_utils>
AssertionError: Tuples differ: (1, 1, 0, 1) != (1, 1, 0, 2)

First differing element 3:
1
2

- (1, 1, 0, 1)
?           ^

+ (1, 1, 0, 2)
?           ^

----------------------------------------------------------------------
Ran 26 tests in 0.022s

FAILED (failures=4)

  Running kitty just shows a blank window except for the cursor, text is not being drawn (BTW: The joystick test in GLFW3 draws text fine).

 Also I noticed when I run kitty with the --session session.vim argument I get the following error...

Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/kitty-master/__main__.py", line 7, in <module>
    main()
  File "/usr/local/src/kitty-master/kitty/main.py", line 147, in main
    run_app(opts, args)
  File "/usr/local/src/kitty-master/kitty/main.py", line 92, in run_app
    boss = Boss(window, opts, args)
  File "/usr/local/src/kitty-master/kitty/boss.py", line 70, in __init__
    startup_session = create_session(opts, args)
  File "/usr/local/src/kitty-master/kitty/session.py", line 88, in create_session
    return parse_session(f.read(), opts)
  File "/usr/local/src/kitty-master/kitty/session.py", line 78, in parse_session
    raise ValueError('Unknown command in session file: {}'.format(cmd))
ValueError: Unknown command in session file: "
[glfw error] The GLFW library is not initialized
  

Any ideas what is causing the build to fail on my system?

**Comment by kovidgoyal** [comment]
kitty's session files arent in vim syntax, see the readme for the syntax kitty uses. The failed tests all seem to have to do with wide characters. It maybe that the wcwidth() on your system is broken. For example, on my system, running the following code:

```
kitty -c "from kitty.utils import wcwidth; print(list(map(wcwidth, '\u30cb\u30c1')))"
```

gives [2, 2]
