### ISSUE TITLE
Tab to get bold on activity

### ISSUE THREAD

**Issue by krish7919** [kovidgoyal/kitty#2301]
I am not sure if the shell or the terminal emulator handles it, but I have this requirement since I have moved to Kitty.

When I was using tmux/byubu + iTerm2, when opening multiple tabs, the tab with an activity would get *bold*.

This would help me say, run a command and move on to work on something else on another tab, and get back to the original tab on activity.

How do I set something similar in Kitty?
If not Kitty, then is it possible in `.zsh`?

Thanks!

**Comment by ctrlcctrlv** [comment]
Kitty already displays a bell in inactive tabs if there's a terminal bell. Is that not enough? It definitely gives you more control over what _kinds_ of activity matter in inactive tabs. You can run commands as e.g.

```
make ; tput bel
```

**Comment by krish7919** [comment]
Yes, I do not want to do it for every command I type. Maybe will figure out a post-run hook for it in `zsh`...

**Comment by kovidgoyal** [comment]
closing as this is better implemented in the shell.
