### ISSUE TITLE
Kitty on Void/Wayland; EGL: Failed to create context: Arguments are inconsistent

### ISSUE THREAD

**Issue by Spilskinanke** [kovidgoyal/kitty#2303]
I am running this on the latest version of kitty, Void Linux, and Wayland with Sway. The error is currently occurring on a laptop I'm running that (at the moment) does not have access to internet. I can get the exact error message if needed, but from what I see, the Traceback shows 4 failed calls all in main.py, namely main(), run_app, and window_id= create_os_window( . A ValueError says that it failed to create a GLFWwindow. glfw-wayland is installed, and running kitty --debug-config shows that it is in fact running under wayland.
To reproduce this, install kitty from either the given package manager xbps or compiling from source, and run kitty from terminal.

**Comment by kovidgoyal** [comment]
Works fine for me under sway on Arch. I'm afraid I am not going to
install void linux just for this. And posting the exact error message
will be useful.

**Comment by Spilskinanke** [comment]
[020 19:54:44.414832] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[020 19:54:44.421620] Traceback (most recent call last):
  File "/home/sagarmatha/kitty/kitty/launcher/../../kitty/main.py", line 351, in main
    _main()
 File "/home/sagarmatha/kitty/kitty/launcher/../../kitty/main.py", line 344, in _main
    run_app(opts, args, bad_lines)
 File "/home/sagarmatha/kitty/kitty/launcher/../../kitty/main.py", line 145, in run_app
    _run_app(opts, args, bad_lines)
 File "/home/sagarmatha/kitty/kitty/launcher/../../kitty/main.py", line 125, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow

This is the exact error when calling kitty from terminal. Note that is also with zsh 5.7.1, kernel 5.4.13_2.

**Comment by kovidgoyal** [comment]
That's a driver issue. Your OpenGL driver is failing to create an OpenGL
context. Make sure your user is a member of the video group. And update
your GPU drivers/switch to a proprietary/non-proprietary one.

**Comment by katattakd** [comment]
I'm encountering the same issue on Debian sid with Sway.
