### ISSUE TITLE
Error: Invalid face handle

### ISSUE THREAD

**Issue by Strykar** [kovidgoyal/kitty#2304]
Kitty will throw this when I specify IBM Plex Mono as the Italic and Bold Italic font to use.
```
~ kitty --session=~/.session1
fast_data_types.FreeTypeError:
Failed to set char size for non-scalable font, with error: invalid face handle
```
The Mono font itself exhibits no visual issues in spite of this message in the terminal.
https://github.com/IBM/plex/issues/298 suggested it may be a terminal implementation problem.

**Comment by kovidgoyal** [comment]
I cannot reproduce using the fonts from ttf-ibm-plex on Arch Linux, running kitty from master, with:

```
kitty --config NONE -o font_family=IBM\ Plex\ Mono -o bold_font=IBM\ Plex\ Mono -o italic_font=IBM\ Plex\ Mono
```

**Comment by Strykar** [comment]
`kitty --config NONE -o font_family=IBM\ Plex\ Mono -o bold_font=IBM\ Plex\ Mono -o italic_font=IBM\ Plex\ Mono `does not throw errors for me either. Closing this until I investigate this further to confirm where the issue lies.
