### ISSUE TITLE
Possible to define horizontal and vertical windows

### ISSUE THREAD

**Issue by krish7919** [kovidgoyal/kitty#2306]
Is it possible to create a new window with more customization?

I would like to control if the new window where the new window is positioned and also to specify if it has to be a vertical or horizontal split.

I am trying to achieve something like:

```
|------------------------|
|       Win 1            |
|------------------------|
|       Win 2            |
|------------------------|
| W3    |W4   |W5   |W6  |
|------------------------|
```

Is it already possible and did I get the docs wrong?

**Comment by kovidgoyal** [comment]
The fat layout does exactly that, and if you run from master you can
customize it to specify how many full width windows it allows.

**Comment by krish7919** [comment]
Not really. From the docs:

`Fat -- One window is shown full width on the top, the rest of the windows are shown side-by-side on the bottom`

I am aiming for 2 horizontal windows in full width, and others at the bottom.

**Comment by Luflosi** [comment]
Yes, as @kovidgoyal said, the ability to customise how many full width windows should be shown is only in the master branch and has not made it to a stable release yet. See https://github.com/kovidgoyal/kitty/blob/d55242aa82b0cd79db73976d1e40fe632396f967/docs/index.rst for the latest (but not well formatted by GitHub) docs, search for "fat" to find the layout.
> Some layouts take options to control their behavior. For example, the fat and tall layouts accept the bias and full_size options to control how the available space is split up.

**Comment by mhalano** [comment]
I think the idea here is create some shortcurt like Tmux has for horizontal split and vertical split:
%  vertical split
"  horizontal split
So we can define if we want a new panel (ctrl-shift-Enter) wplitted horizontally or vertically.
