### ISSUE TITLE
Font not changing

### ISSUE THREAD

**Issue by gregf** [kovidgoyal/kitty#2309]
system: archlinux stable
version: kitty 0.15.1

When setting any font in kitty.conf theres no change when I open my terminal. 

I can change to these same fonts in alacirtty another gpu based terminal emulator and it works fine.

![2020-01-23_17-32](https://user-images.githubusercontent.com/980/73029847-541af480-3e06-11ea-936d-4e86ec335ce4.png)

I  have opened gtk2fontsel to see the font names, thinking maybe I was getting the name wrong even though in alacritty they seemed to be changing like I would expect. Any help would be appreciated.

**Comment by ctrlcctrlv** [comment]
Have you tried the [instructions in the FAQ](https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font) ?

**Comment by gregf** [comment]
That was it, appears there's just about no font I use that kitty can support. That's to bad. Thanks.

**Comment by ctrlcctrlv** [comment]
You use Arch yes? So you can use Fontconfig overrides as the FAQ describes. I have done so personally and have had no problems.

**Comment by gregf** [comment]
I just tried that and the spacing was still really odd. Here's what I did.

in kitty.conf I have.

font_family Noto Sans Mono Medium Nerd Font Complete Mono

and in ~/.config/fontconfig/fonts.conf I have this.

<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<match target="scan">
    <test name="family">
        <string>Noto Sans Mono Medium Nerd Font Complete Mono</string>
    </test>
    <edit name="spacing">
        <int>100</int>
    </edit>
</match>
</fontconfig>

Then I ran fc-cache -r and restarted my terminal. It was a bit better but it still wasn't "right"

**Comment by gregf** [comment]
I had nerd-fonts-complete installed in archlinux which apparently didn't ship most of the mono fonts or something. I installed them from the git repo and things are working fine now. Thanks.
