### ISSUE TITLE
Add a nightly build to Travis configuration

### ISSUE THREAD

**Issue by cweagans** [kovidgoyal/kitty#231]
I think it would be really helpful to be able to test kitty.app without having to get a full build toolchain set up. Travis CI could be easily configured to build a nightly release for all currently supported platforms and post it to Github.

**Comment by kovidgoyal** [comment]
Why? If you want to run kitty from source, all you need to do is 

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install harfbuzz; brew install python3; make debug; python3 .
```

brew installs the build tools for you automatically.
And the first step is not even needed if you already have brew installed. It doesn't seem like that big of a burden.

**Comment by cweagans** [comment]
I already have Homebrew installed. I am _capable_ of running from source, but that doesn't mean that I _want_ to, even if there's stuff in HEAD that hasn't yet been released. This is an easy thing to set up on Travis and it doesn't hurt anything, so why not?

**Comment by kovidgoyal** [comment]
Umm if you dont want to run from source, then why do you want to run from nightly? What's the difference? And no it is not an easy thing to setup.

**Comment by cweagans** [comment]
I don't want to run from source, but I want to test recent changes to the codebase (particularly the DPI one). I will set up the Travis stuff if you'll accept it. It's really not that hard.

**Comment by kovidgoyal** [comment]
Sorry, I'm really not willing to maintain nightly releases.
