### ISSUE TITLE
Open multiple URLs in hint mode

### ISSUE THREAD

**Issue by lenormf** [kovidgoyal/kitty#2316]
Hi,

Is it currently possible to open multiple URLs at once (maybe using a kitten)? If not, could we have an interface to allow that, as hitting <kbd>shift</kbd><kbd>ctrl</kbd><kbd>e</kbd> repeatedly can get tedious.

Thanks!

**Comment by kovidgoyal** [comment]
kitty +kitten hints --help

Look for --multiple

**Comment by lenormf** [comment]
Thanks!

I've come up with the following mapping, but it doesn't seem to execute the default open program:

```
map ctrl+shift+e launch --stdin-source @screen --type overlay kitty +kitten hints --multiple --program default
```

Any idea why?

**Comment by kovidgoyal** [comment]
map X kitten hints --multiple

is what you need.

As for why it is not opening the default program, that will depend on
what the default program is, try passing a specific program.

**Comment by lenormf** [comment]
Thanks again, that worked!

As for the original mapping, I've tried several different values for `--program` (`firefox`, my editor, a local shell script), but they were never executed. I `strace`'d the process to make sure - the matches were only ever printed, and the programs never run.

I feel like it should work, maybe there's a bug somewhere at a lower level.
