### ISSUE TITLE
Question: Invoke arbitrary command by typing it (without a map)?

### ISSUE THREAD

**Issue by Asheq** [kovidgoyal/kitty#2317]
Kovid,

(I apologize if this is in the documentation but I couldn't find it)

Is there currently a way to type an arbitrary command that doesn't have an existing map?

For example, I would like to enter a key combo to bring up a kitty-specific command line and type `detach_window` and hit enter.

**Comment by kovidgoyal** [comment]
I dont follow what you want to do, can you post an example of the "kitty
specific commandline"

**Comment by ctrlcctrlv** [comment]
Kitty REPL?

**Comment by ohle** [comment]
I think [`kitty @`](https://sw.kovidgoyal.net/kitty/remote-control.html) comes close to what you want.

**Comment by kovidgoyal** [comment]
Press ctrl+shift+esc (which launches the kitty shell) and type away to your hearts content. the supported commands are precisely from the remote control protocol pointed out by @ohle
