### ISSUE TITLE
`create_marker` removes all previous markers

### ISSUE THREAD

**Issue by ohle** [kovidgoyal/kitty#2318]
I like the new markers feature.

I was hoping that calling `create_marker` or `toggle_marker` multiple times (with different mark group numbers) would leave me with multiple active mark groups at the same time, but it doesn't. Would that be possible?

**Comment by kovidgoyal** [comment]
You can define multiple expressions for a single marker, with different
colors. See https://sw.kovidgoyal.net/kitty/marks.html

**Comment by ohle** [comment]
OK, how would I do that with `create_marker`? Sorry, but I've read the docs and I don't see it.

**Comment by kovidgoyal** [comment]
create_marker takes exactly the same syntax as toggle_marker and there
is an example of defining multiple match expressions for toggle_marker

**Comment by ohle** [comment]
Ah, I see what you mean. That means I have to always specify all patterns; I was hoping I could do it cumulatively (with successive calls to `create_marker`, each specifying only one pattern).

Anyway, thanks for your help.

**Comment by kovidgoyal** [comment]
there is history at the create_marker prompt
