### ISSUE TITLE
Cannot select one character with Shift

### ISSUE THREAD

**Issue by lenormf** [kovidgoyal/kitty#2319]
Hi,

On Kitty v0.15.1 (ArchLinux), I cannot select a single character on the terminal when holding <kbd>MOUSE1</kbd> and <kbd>shift</kbd>. The selection always jumps to select two characters.

HTH.

**Comment by ctrlcctrlv** [comment]
I think this is expected behavior. I have the same problem. See #945. Doesn't really bother me.

**Comment by kovidgoyal** [comment]
yes the way selection is designed currently selecting single characters
is not possible, someday I might get around to reworking it, but not
anytime soon.
