### ISSUE TITLE
Set WINDOWID env variable to X11 window id

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#232]
Gnome terminal, Konsole, Alacritty do it.  Some programs (such as Vim) guess their window id from this variable. Right now I'm using the following quick hack:
```patch
diff --git a/kitty/utils.py b/kitty/utils.py
index 676a23ff..5ac66fb7 100644
--- a/kitty/utils.py
+++ b/kitty/utils.py
@@ -155,12 +155,13 @@ def init_startup_notification_x11(window_id, startup_id=None):
     # https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt
     from kitty.fast_data_types import init_x11_startup_notification
     sid = startup_id or os.environ.pop('DESKTOP_STARTUP_ID', None)  # ensure child processes dont get this env var
-    if not sid:
-        return
     display = x11_display()
     if not display:
         return
     window_id = x11_window_id(window_id)
+    os.environ['WINDOWID'] = str(window_id)
+    if not sid:
+        return
     return init_x11_startup_notification(display, window_id, sid)
 
 
```

**Comment by kovidgoyal** [comment]
That's intereseting, what does vim use WINDOWID for and what does it do when running on a non-X11 platform?

**Comment by sergei-dyshel** [comment]
Vim (terminal) just stores $WINDOWID in it's internal variable `v:window_id` (Gvim stores real X11 window ID there). I'm using this value to raise (activate) specific Vim window when using Vim's client/server functionality (`--remote`).

**Comment by jbriales** [comment]
> Vim (terminal) just stores $WINDOWID in it's internal variable `v:window_id` (Gvim stores real X11 window ID there). I'm using this value to raise (activate) specific Vim window when using Vim's client/server functionality (`--remote`).

Is this true? `echo v:window_id` shows undefined variable for me in `vim` and `gvim`, regardless of the terminal (even though `$WINDOWID` is defined.
