### ISSUE TITLE
Disabling ligatures in kitty shell  -> Unhandled error

### ISSUE THREAD

**Issue by r4v** [kovidgoyal/kitty#2320]
Hi
I've updated to 0.16.0 and when i try to disable ligatures in kitty shell (ctrl+shift+esc) i'm getting error:

```
🐱 disable-ligatures --all
Unhandled error:
Traceback (most recent call last):
  File "kitty/shell.py", line 196, in real_main
  File "kitty/shell.py", line 132, in run_cmd
  File "kitty/cmds.py", line 1276, in cmd_disable_ligatures
IndexError: list index out of range
```

**Comment by kovidgoyal** [comment]
You need to specify the STRATEGY, see 
disable-ligatures -h

The error message should certainly be improved though.

**Comment by r4v** [comment]
Oh my mistake. Thanks for the clarification
