### ISSUE TITLE
MacOS mouse dissapeares

### ISSUE THREAD

**Issue by paul-nameless** [kovidgoyal/kitty#2322]
After upgrading to 16.0 version (I've been using kitty from sources for the last two weeks and an issues reproduces there as well. It wasn't release so I didn't create an issue) I noticed that mouse cursor hides after some time and when I switch to other application (e.g. Firefox) and start to move mouse it doesn't appear (until I turn on mission control).
Reproducible.
I know, in configuration says that mouse hide feature is disabled on MacOS but it works... just doesn't unhides the mouse cursor)
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.mouse_hide_wait

 > kitty --version
kitty 0.16.0 created by Kovid Goyal

Is there any other way I can help you?

**Comment by kovidgoyal** [comment]
I tried getting mouse hiding working on macOS and gave up. macOS is
simply too buggy. I'm afraid its not going to be implemented.

**Comment by paul-nameless** [comment]
Yes, I'm not asking to implement mouse hiding. I am asking to fix the bug, which causes mouse to hide on MacOS. I don't remember such behavior on earlier version.
Do you mean, that it can't be fixed?

**Comment by kovidgoyal** [comment]
yes I mean it cant be fixed. Search the issue tracker you will see the
various problems with it. It has never worked reliably on macOS.

**Comment by paul-nameless** [comment]
Understood, thanks for the answer.

**Comment by paul-nameless** [comment]
I've found work around for this problem. For other people who might need fix, here is the app which "unhides" app when you move cursor: http://doomlaser.com/cursorcerer-hide-your-cursor-at-will/
Can be installed through homebrew
