### ISSUE TITLE
kitty.conf is not loading. 

### ISSUE THREAD

**Issue by HenningCode** [kovidgoyal/kitty#2324]
I read the other issues and tried to get it working, but my kitty.conf file not being loaded. I opened it via Preferences and just set the opacity to 0.6 and a new font a different background color and so on, but nothing is being displayed. If i run `kitty --debug-config ` It shows me this path `/Users/henningwilmer/.config/kitty/kitty.conf` without any changes to the default config. Then I opened this file via vim and my changes are still there so I don't understand why kitty isn't accepting them. 

Greetings 

Edit: I have not folder` /Library/Preferences/kitty`

**Comment by Luflosi** [comment]
Do you see any error messages when executing `kitty` from inside kitty or another terminal?

**Comment by HenningCode** [comment]
If i run kitty from the terminal.app `zsh: command not found: kitty` this is the output. Also I realized that somehow scrolling through the past actions was activated and I had to disable inside the terminal.app to disable that inside kitty. I actually don't know whats happening.

**Comment by kovidgoyal** [comment]
Run kitty from within kitty to see config related error messages. Although you would see them with --debug-config as well.

**Comment by HenningCode** [comment]
If I run kitty inside of kitty a new window is opened without a error message.

**Comment by kovidgoyal** [comment]
I'm guessing you forgot to uncomment your changes. Remove the leading #
from the lines you changed.

**Comment by shrilakshmishastry** [comment]
> I'm guessing you forgot to uncomment your changes. Remove the leading # from the lines you changed.

thanks, I was doing the same, forgot to uncomment and scratching from a long why it's not working 🤣

**Comment by Tobeytt** [comment]
Why you changed it , it is still not working.

________________________________
发件人: Shrilakshmi Shastry ***@***.***>
发送时间: 2024年4月23日 5:17
收件人: kovidgoyal/kitty ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [kovidgoyal/kitty] kitty.conf is not loading. (#2324)


I'm guessing you forgot to uncomment your changes. Remove the leading # from the lines you changed.

thanks, I was doing the same, forgot to uncomment and scratching from a long why it's not working 🤣
