### ISSUE TITLE
Cells with explicitly set black blackground are rendered transparent

### ISSUE THREAD

**Issue by Wuestengecko** [kovidgoyal/kitty#2325]
Since the update to v0.16, cells that have their background set to black are actually rendered without background when the window background is semi-transparent. Previously it would render these cells with a solid black background. This makes a powerline-esque prompt look somewhat ugly.

**old**: ![kitty-prompt-old](https://user-images.githubusercontent.com/1579756/73386547-4e725280-42cf-11ea-958d-9dc9a228d1fe.png)
**new**: ![kitty-prompt-new](https://user-images.githubusercontent.com/1579756/73386580-5b8f4180-42cf-11ea-896b-b845d78ce6f3.png)

The screenshots were made with kitty's default `#000000` background at a `background_opacity` of 0.8 against a fully `#ffffff` wallpaper.

The sample `kitty.conf`'s comments on `background_opacity` suggest that the old behavior is still intended (see line 563):

```
#: […] Note that it only sets the default background color's
#: opacity. This is so that things like the status bar in vim,
#: powerline prompts, etc. still look good.  […]
```

I tried `git bisect`ing, but couldn't pinpoint a single commit due to #2277:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 3a4ba7e8340ac04e23857a8d8db384d75e88b988
> d8ed135b46709d5f6d7202196f2d4470c93272a7
> fab57fbdf136a7864befd97ac1df0bded88a8218
> 2045055ae37eddf05aaa4c200c5552023d07cb8d
> 76a93b6cd6f14f510ce7df4f13cc2bffdaf84b39
> 8c540d5a46394aaf1255dcb1d6c8b8b372b5c1aa

Judging by the commit message, 2045055ae37eddf05aaa4c200c5552023d07cb8d changes this behavior on purpose. So, as for this bug report, it is about one of:

* [ ] Cell background is rendered incorrectly **or**
* [ ] Documented behavior in the sample configuration is out of date

I'll let you choose ;)

**Comment by kovidgoyal** [comment]
Yes it is deliberate. Dont use the same background color for both powerline and the terminal default background and you will be fine. The docs are fairly ambiguous on the subject of whether explicitly set colors that match the default or only unset colors are made transparent. I will clear that up.

**Comment by ctrlcctrlv** [comment]
Hi, sorry. I feel like that's partly my fault.

I also want to make it so that *non-default* background cells can be given an opacity, I think it would look cool in combination with #163, which I continue to work on. (Everything, except tiling, is done! I've got my nose in the OpenGL book right now.)

So expect more changes I'd say, though hopefully none will take effect without a configuration change.
