### ISSUE TITLE
[Question] How to use neovim (or vim) as scrollback pager?

### ISSUE THREAD

**Issue by Asheq** [kovidgoyal/kitty#2327]
I've tried adding `scrollback_pager nvim` in kitty.conf but when I press `kitty_mod+h` I see the screen flash but no neovim.

PS: I recently stopped using tmux in favor of pure kitty and I very much like the idea of using neovim as the scrollback pager instead of tmux's built-in pager which is awkward and only has pseudo-vim key bindings.

**Comment by kovidgoyal** [comment]
You need to run vim in a mode where it understands ansi escape codes and
reads data from stdin. If you search the issues here you will find
examples of how to do that.

**Comment by Asheq** [comment]
@kovidgoyal Kovid, just wanted to let you know that the reason `scrollback_pager nvim` was not working was because the  `nvim` command was not found (see https://github.com/neovim/neovim/issues/11797#issuecomment-581088660)

Providing the full path to neovim via `scrollback_pager /usr/local/bin/nvim` works.

Any idea why this is the case?

**Comment by kovidgoyal** [comment]
Because it is not in the system wide PATH which is what kitty will see
when it tries to launch things.

**Comment by Asheq** [comment]
Okay, thanks! Any reason why it doesn't/can't look at the user PATH?

BTW, if you are curious here's a preview of it working:

![example](https://user-images.githubusercontent.com/4657140/73620628-a2d74400-45e7-11ea-8c40-0558b0f9aad5.gif)

Still trying to perfect the command but here is what I have so far:

scrollback_pager /usr/local/bin/nvim  -c "set nonumber nolist showtabline=0 foldcolumn=0" -c "autocmd TermOpen * normal G" -c "silent write /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "

I am making use of neovim's built-in terminal so it can handle the ANSI escape codes.

**Comment by kovidgoyal** [comment]
It does look at the user PATH. You are presumably talking about whatever
modifications you have made to PATH in your shell startup scripts. kitty
is not going to look at those. You need to make those modification
available to launchd if you want them to be used by GUI applications
like kitty.

**Comment by Asheq** [comment]
Gotchya! Thanks for the explanation 👍

**Comment by javiertury** [comment]
The terminal trick didn't work for me, so I modified it to use `ft=man` instead
```
scrollback_pager nvim --noplugin -c 'setlocal ft=man nonumber nolist showtabline=0 foldcolumn=0' -c "autocmd VimEnter * normal G" -
```

**Comment by thornycrackers** [comment]
I had to force writing for the terminal trick with `silent!` or else it would complain about the file existing:

```
scrollback_pager nvim -c "set norelativenumber nonumber nolist showtabline=0 foldcolumn=0" -c "autocmd TermOpen * normal G" -c "silent! write /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "
```

**Comment by David-Else** [comment]
For me, this is the best and most terse solution:
```
scrollback_pager nvim --noplugin -c "set signcolumn=no showtabline=0" -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "
```
`"set signcolumn=no showtabline=0"` depends on your current config.

**Comment by page-down** [comment]
@David-Else 

Maybe you are interested in this. Here is my configuration.

https://github.com/kovidgoyal/kitty/issues/719#issuecomment-952039731

There is no need to write temporary file or keep cat running.

**Comment by agzam** [comment]
Related question. Does anyone know if it's possible to set Helix as the pager?

**Comment by insilications** [comment]
My attempt: https://gist.github.com/insilications/9ec404b74771add0a431e06b00f39679

**Comment by menisadi** [comment]
Somehow none of the above didn't work for me so I did the following:
```bash
#!/bin/bash
/usr/bin/perl -pe 's/\e\[[0-9;:]*[a-zA-Z]//g; s/\e\][^\a\e]*(?:\a|\e\\)//g; s/\r//g' | \
    /opt/homebrew/bin/nvim \
    -c "set norelativenumber nonumber nolist showtabline=0 foldcolumn=0 clipboard+=unnamedplus" \
    -c "normal G" \
    -
```

And 
`scrollback_pager ~/.config/kitty/scrollback_pager.sh`

It doesn't render colors which is a same but my main purpose was to be able to find and copy parts from the scrollback, so I guess for now it's enough.

**Comment by rochacbruno** [comment]
For those looking for how to have scrollback top open in classic vim (not neovim)



```vim
# Set vim as editor
editor vim
# Map Ctrl+Shift+G to open last command output in vim overlay
map ctrl+shift+g launch --stdin-source=@last_cmd_output --type=overlay vim -
# Map Ctrl+Shift+I to copy last command output to clipboard
map ctrl+shift+i launch --stdin-source=@last_cmd_output --type=clipboard
```


If you have issues with escaped chars put this somwewhere in your vim config

```vim
if $TERM =~# 'kitty'

  " Map Alt key combinations to escape sequences for fzf
  set <M-a> = "\ea"
  set <M-d> = "\ed"

  " Mouse support
  set mouse=a
  set ttymouse=sgr
  set balloonevalterm
  " Styled and colored underline support
  let &t_AU = "\e[58:5:%dm"
  let &t_8u = "\e[58:2:%lu:%lu:%lum"
  let &t_Us = "\e[4:2m"
  let &t_Cs = "\e[4:3m"
  let &t_ds = "\e[4:4m"
  let &t_Ds = "\e[4:5m"
  let &t_Ce = "\e[4:0m"
  " Strikethrough
  let &t_Ts = "\e[9m"
  let &t_Te = "\e[29m"
  " Truecolor support
  let &t_8f = "\e[38:2:%lu:%lu:%lum"
  let &t_8b = "\e[48:2:%lu:%lu:%lum"
  let &t_RF = "\e]10;?\e\\"
  let &t_RB = "\e]11;?\e\\"
  " Bracketed paste
  let &t_BE = "\e[?2004h"
  let &t_BD = "\e[?2004l"
  let &t_PS = "\e[200~"
  let &t_PE = "\e[201~"
  " Cursor control
  let &t_RC = "\e[?12$p"
  let &t_SH = "\e[%d q"
  let &t_RS = "\eP$q q\e\\"
  let &t_SI = "\e[5 q"
  let &t_SR = "\e[3 q"
  let &t_EI = "\e[1 q"
  let &t_VS = "\e[?12l"
  " Focus tracking
  let &t_fe = "\e[?1004h"
  let &t_fd = "\e[?1004l"
  execute "set <FocusGained>=\<Esc>[I"
  execute "set <FocusLost>=\<Esc>[O"
  " Window title
  let &t_ST = "\e[22;2t"
  let &t_RT = "\e[23;2t"

  " vim hardcodes background color erase even if the terminfo file does
  " not contain bce. This causes incorrect background rendering when
  " using a color theme with a background color in terminals such as
  " kitty that do not support background color erase.
  let &t_ut=''
endif
```
