### ISSUE TITLE
[Question] Is it possible to have a single map that toggles/cycles between two or more background opacities?

### ISSUE THREAD

**Issue by Asheq** [kovidgoyal/kitty#2328]
I want to be able to press a single key combo (`kitty_mod+o`) that switches back and forth between a background opacity of 0.9 and 1.0 every time it is invoked.

Is it possible? Or does this require some new options? Something similar to how layouts can be toggled:

```
enabled_background_opacities  0.9, 1.0
map  kitty_mod+o  next_background_opacity
```

Thanks!

**Comment by kovidgoyal** [comment]
Use the remote control protocol in a script to do this. kitty @
set-background-opacity. The script should save whatever was set last and
toggle on next invocation.

**Comment by Asheq** [comment]
Okay, seems doable! Thanks!
