### ISSUE TITLE
tab_title_template string formatting

### ISSUE THREAD

**Issue by chriszarate** [kovidgoyal/kitty#2332]
Thank you for kitty, it is a wonderfully focused terminal emulator.

I am running kitty 0.16.0 on OS X, installed from the .dmg (not Homebrew).

I would like to use `tab_title_template` to provide leading and trailing spaces around the tab title. The docs and other issues seem to imply that these options accept python string literals, i.e., a value that could be passed to `print`. However, when I try this, it leads to over-escaped results.

```
tab_title_template " {index} {title} "
```
![Screen Shot 2020-02-02 at 9 21 58 AM](https://user-images.githubusercontent.com/739304/73609636-aba32800-459d-11ea-8cff-c6ce3d593ffb.png)

Using Unicode code points doesn't work either:

```
tab_title_template \u0020{index} {title}\u0020
```

![Screen Shot 2020-02-02 at 9 23 09 AM](https://user-images.githubusercontent.com/739304/73609643-c2497f00-459d-11ea-9f18-c1342c14db96.png)

Is this a bug or is there another way to achieve this spacing? Here are the other tab config values used to create the screenshots:

```
active_tab_background   #458588
active_tab_font_style   normal
active_tab_foreground   #1d2021
inactive_tab_background #1d2021
inactive_tab_font_style normal
inactive_tab_foreground #928374
tab_bar_style separator
tab_separator " "
tab_title_template " {index} {title} "
```

Thanks!

**Comment by kovidgoyal** [comment]
tab_title_template is not a python string literal just ordinary utf-8
text. You cant have leading spaces on it because of the way option
parsing works, spaces are the separator between the option name and
value. instead use one of the unicode space characters such as
U+2009 which you will need to input as itself, not using an escape.

**Comment by chriszarate** [comment]
Apologies, but that does not work either:

```
tab_bar_style separator
tab_separator " "
tab_title_template    {index} {title}   
```

![Screen Shot 2020-02-02 at 10 09 08 AM](https://user-images.githubusercontent.com/739304/73610343-18212580-45a4-11ea-9dea-e058fa5eb55d.png)


This is an exact cut and paste from my config. You can see that I've used an em space, and en space, and a thin space (your suggestion). All are stripped.

**Comment by chriszarate** [comment]
Looks like that fix will allow:

```
tab_title_template " {index} {title} "
```

Thanks so much!
