### ISSUE TITLE
Improving accessibility of remote servers

### ISSUE THREAD

**Issue by mnaser** [kovidgoyal/kitty#2333]
Hi there,

First of all, thanks for the amazing project, it's great to have such a responsive and modern terminal which makes use of things like ligatures too.

I am someone who needs to SSH to a lot of different servers often and I'm struggling a little bit with usage, I've alias'd my `ssh` to the kitten, however, a lot of times, if I run a `sudo -i` -- it breaks things again..  I've tried to avoid it and stick to `sudo -s` but then I also attach into remote lxc containers often using `lxc-attach` and that breaks...

Would it be possible to workout out a way to allow the ability of using some of more standard options when SSHing remotely?  This is all way above my understanding of terminals and emulation but I'd like to try and help if I can be pointed a specific path.

Thanks,
Mohammed

**Comment by kovidgoyal** [comment]
Basically some terminal program use a database called terminfo that
contains terminal definitions. If the database on the remote machine 
does not contain a definition for the terminal you are using, then
things break. You basically need a way to ensure that definition is
present on the machines you SSH into. The SSH kitten does it for you for
ssh, for other things you will need to figure out equivalent mechanisms,
or simply install the terminfo definitions as part of setting up the
machines.

**Comment by skluthe** [comment]
Hate to say it but this is a bad way of doing things. If I can't just ssh into a server and run standard commands (like every other terminal emulator ever) then I'm not going to be able to use this. I'm not setting up a new file on every one of my servers (100+) just to use this and I'm sure many others don't.

I understand I can just use another terminal emulator (and that's what I'll be doing) but I wanted to provide feedback.
