### ISSUE TITLE
Unable to change shortcut for change_font_size (nano shortcut conflict)

### ISSUE THREAD

**Issue by kgizdov** [kovidgoyal/kitty#2334]
Hi,

So I've run into a strange issue. I cannot seem to change the default shortcuts to alter the font size from:
```
map kitty_mod+equal     change_font_size all +2.0
map kitty_mod+minus     change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
```
to:
```
map ctrl+alt+equal     change_font_size all +2.0
map ctrl+alt+minus     change_font_size all -2.0
map ctrl+alt+backspace change_font_size all 0
```
When I set this in my config and run `kitty --debug-config`, I get:
```
Linux yavin4 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/gizdov/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
bold_font             FiraCode Bold
bold_italic_font      FiraSans BoldItalic
cursor                Color(red=237, green=212, blue=0)
font_family           FiraCode Retina
font_size             12.0
foreground            Color(red=237, green=212, blue=0)
italic_font           FiraSans Italic
scrollback_lines      20000
strip_trailing_spaces smart
tab_bar_edge          1
Added shortcuts:
	control+alt+minus KeyAction(func='change_font_size', args=[True, '-', 2.0])
	control+alt+equal KeyAction(func='change_font_size', args=[True, '+', 2.0])
	control+alt+backspace KeyAction(func='change_font_size', args=[True, None, 0.0])
```
However, when I'm inside a nano session and press `ctrl+shift+minus`, instead of getting a line search bar, my font decreases... I've tried reloading config. Closing and restarting the terminal. Rebooting machine.

The only thing that works is to change the `kitty_mod` or to `clear_all_shortcuts`. However, I do not wish to do that. I'm used to it being the default and don't want re-learning or manually redefining all the other shortcuts just for this.

Could you help?

**Comment by Luflosi** [comment]
Try adding
```
map kitty_mod+equal no_op
map kitty_mod+minus no_op
map kitty_mod+backspace no_op
```
The default shortcuts are still there until you overwrite them.

**Comment by kgizdov** [comment]
indeed that works, thanks.

**Comment by kovidgoyal** [comment]
Setting another shortcut will simply mean you now have two shortcuts for
that action. If you wish to make a particular ke combination available
to a terminal program map it to no-op.

map ctrl+shit+minus no_op
