### ISSUE TITLE
env TERMINFO=... has no effect

### ISSUE THREAD

**Issue by YaBoiBurner** [kovidgoyal/kitty#2336]
Setting TERMINFO in config file doesn't do anything. Including `env TERMINFO=${HOME}/.terminfo` or `env TERMINFO=${XDG_DATA_HOME}/terminfo` still leaves terminfo set to `/usr/lib64/kitty/terminfo`.

I think [child.py](https://github.com/kovidgoyal/kitty/blob/master/kitty/child.py) is overriding it.

Currently using kitty version `0.15.1` from Fedora 31.

**Comment by kovidgoyal** [comment]
Yes, terminfo is overridden to point to kitty terminfo files. This is by
design.
