### ISSUE TITLE
Issuing remote control commands from inside tmux session

### ISSUE THREAD

**Issue by aasutossh** [kovidgoyal/kitty#2338]
I am trying to change color scheme of kitty from inside of tmux session.
I have enabled remote control by specifying 
`allow_remote_control yes` in `kitty.conf`.
I get the following error:
`TimeoutError: Timed out while waiting to read command response. Make sure you are running this command from within the kitty terminal. If you want to run commands from outside, then you have to setup a socket with the --listen-on command line flag.`

How do I set the `--listen-on` to listen to tmux?

**Comment by kovidgoyal** [comment]
There can be no listen to tmux. tmux is probably filtering out the kitty
control sequences. My recommendation, as always, is to not use horrible
hacks like terminal multiplexers.

If you must then you will need to setup --listen-to with a unix or tcp
socket to bypass tmux.

**Comment by guilhermedeandrade** [comment]
@aasutossh Were you able to find a solution for this? I'm facing the same problem

**Comment by aasutossh** [comment]
@guilhermedeandrade no, I didn't. Removed kitty, and used alacritty for a long time.

**Comment by luisdavim** [comment]
> My recommendation, as always, is to not use horrible hacks like terminal multiplexers.

This makes me sad.

**Comment by johnnovak** [comment]
> This makes me sad.

That makes two of us. But I guess it "makes sense"... we don't get bold=bright color support either in the name of pedanticism vs practicality.

**Comment by luebking** [comment]
Fwiw
```
    HEAD=""
    TAIL=""
    if [[ $TERM =~ "tmux"* ]]; then
        HEAD="\033Ptmux;\033"
        TAIL="\033\\"
        tmux set allow-passthrough on
    fi
    printf "${HEAD}\033]10;$FG\007${TAIL}"
    printf "${HEAD}\033]11;$BG\007${TAIL}"
    printf "${HEAD}\033]39;$FG\007${TAIL}"
    printf "${HEAD}\033]49;$BG\007${TAIL}"
    if [[ $TERM =~ "tmux"* ]]; then
        tmux set allow-passthrough off
    fi
```

Obviously figure $FG and $BG (fishing them out or xrdb based on redshift's color temperature calculation)

**Comment by luisdavim** [comment]
I use https://github.com/lemnos/theme.sh from inside tmux and it works fine.  

I also use https://github.com/wookayin/kitty-tmux
