### ISSUE TITLE
alternative search type switching shortcut for unicode input

### ISSUE THREAD

**Issue by towc** [kovidgoyal/kitty#2343]
In my configuration, `f1` is bound to something at the i3-level.

When in kitty I type `ctrl+shift+u`, and get to the unicode input kitten, then switch to `f2` for names, I can't go back to `f1`, because it's captured by i3.

If restarting the kitten made it go back to `f1` mode, it would be good enough of a workaround, but it doesn't, and it probably shouldn't.

Can there be a `ctrl+tab`/`ctrl+shift+tab` in unicode input mode that switches to the next/prev search mode?

**Comment by Chaz6** [comment]
Uh oh, this conflicts with the common ctrl-tab/ctrl-shift-tab binding to cycle through tmux/screen windows (\E[27;5;9~ and \E[27;6;9~)
