### ISSUE TITLE
percentage caracter output in printf

### ISSUE THREAD

**Issue by haddadnidal** [kovidgoyal/kitty#2345]
when i use printf i have a "%" output caracter at the end, i dont have this type of behaviour in gnome-terminal
here is a screenshot of the output
![pic](https://user-images.githubusercontent.com/9222035/74091162-ea147780-4ab4-11ea-809b-b261e45f5d22.png)

**Comment by Luflosi** [comment]
I think this is a feature of the shell (I guess zsh in your case) to indicate that there was no newline at the end. If you execute `printf 'hgi\n'`, there should be no `%` at the end. I tested this (`printf 'hgi'`) and see the `%` in all the terminal emulators I have: kitty, Terminal.app, Alacritty and iTerm2.
I don't know why this doesn't happen in gnome-terminal. @kovidgoyal do you know why this could be happening?

**Comment by haddadnidal** [comment]
After some investigation you are right it's a zsh issue here is a link for anyone that might ask the same question.
thank you the \n solved my issue.

[](https://stackoverflow.com/questions/27238564/getting-a-weird-percent-sign-in-printf-output-in-terminal-with-c)
