### ISSUE TITLE
Space between Kitty tab bar and Vim tab bar

### ISSUE THREAD

**Issue by CKolkey** [kovidgoyal/kitty#2348]
First and foremost, I really appreciate the work you guys do on this project. 

I'm using the new `hide_window_decorations titlebar-only` option, and wanted to see if there was a way to fix the gap that appears between the bottom edge of the kitty tab bar, and the top edge of vim. For example:
![Screenshot 2020-02-09 10 13 41](https://user-images.githubusercontent.com/7228095/74099597-dbb27400-4b25-11ea-9593-f730c9a43534.png)

It might be nice to have that be a configurable pixel value (tab-bar-bottom-margin?) or just have it sit nice and flush. 

I'm using kitty 0.16.0 and macos 10.14.6.

**Comment by ctrlcctrlv** [comment]
Does the size of the "gap" change as you resize the window? I think you need to change `placement_strategy` to e.g. `bottom-left`. I think there is also a way to force Kitty to only resize in full cells, but I'm not sure how to do it. (Maybe related to `window_resize_step_cells`?)

**Comment by Luflosi** [comment]
Set the initial window size in cells instead of pixels and resize in steps, e.g.:
```
initial_window_width  80c
initial_window_height 28c
resize_in_steps yes
```
The only problem is that this doesn't work perfectly yet when dynamically changing the font size. `resize_in_steps` is also not yet supported on Wayland.

**Comment by ctrlcctrlv** [comment]
Thanks @Luflosi ! :-) `resize_in_steps` is a nice feature for those concerned with gaps. It must be relatively new as it's not in my config file.

**Comment by kovidgoyal** [comment]
If your window size is not a multiple of cell size then there will
always be some padding, that is unavoidable.
