### ISSUE TITLE
[Enhancement] Support for iTerm-like "Set window title and tab chrome background color"

### ISSUE THREAD

**Issue by meddario** [kovidgoyal/kitty#2349]
Hi, this issue is a feature proposal to implement some custom OSC codes to implement the feature described in https://iterm2.com/documentation-escape-codes.html > "Set window title and tab chrome background color".

This would be useful for example to color tabs based on the current git repository (example [here](https://github.com/meddario/workspace-utils)).

<img width="850" alt="tab-colors" src="https://user-images.githubusercontent.com/16596646/74101245-1e7d4780-4b38-11ea-92e6-77d77836b808.png">

A few questions:
1. Am I missing something and this is already possible with Kitty's APIs?
2. Are you interest in adding this feature/to receive a pull request to add this?
3. (I am not familiar with the code base) Where should I look to add this feature?

**Comment by kovidgoyal** [comment]
There are already escape codes to set window titles supported by a large
range of terminal emulators and kitty as well. Not to mention the kitty
remote control protocol:
https://sw.kovidgoyal.net/kitty/remote-control.html 

As for changing tab
colors see https://github.com/kovidgoyal/kitty/pull/1305

**Comment by meddario** [comment]
Hi, didn't see that PR, thank you!
