### ISSUE TITLE
Neofetch stuck in execution

### ISSUE THREAD

**Issue by Kaitalyn** [kovidgoyal/kitty#2352]
Hello I am new to linux so sorry for incompetence.
When running `neofetch` in the kitty terminal, the program gets stuck after the `Terminal: kitty` line. But when running in other terminals, it does not get stuck. Appreciate the help.
![kitty-neofetch-error](https://user-images.githubusercontent.com/41388558/74133001-7b124e00-4b9c-11ea-9aab-9aa899c13984.png)

**Comment by kovidgoyal** [comment]
You should report that to neofetch, most likely an isue with the
graphics protocol implementation.
