### ISSUE TITLE
Segfault on specific actions

### ISSUE THREAD

**Issue by poldi1405** [kovidgoyal/kitty#2353]
Steps to reproduce: (in current master)
with less
1. open less with any file
2. go to the end of the file
3. Press down (arrow-key) once

with vim (at least in my config):
1. open vim
2. Press Esc twice

Error Message:
```
dsp_protocol_open_node(): Could not open pcm device file /dev/dsptask/pcm2
fish: 'kitty' terminated by signal SIGSEGV (Adressbereichsfehler)
```

**Comment by Luflosi** [comment]
I think this is an issue with the beep sound. For some reason playing the sound doesn't work. Until @kovidgoyal can give us some insight into why this might be happening, you can put `enable_audio_bell no` into your `kitty.conf` (and restart kitty), which should "fix" the issue (but leave you with no sound).

**Comment by kovidgoyal** [comment]
whats happening is that libcanberra is crashing on your system
presumably because it is missing any sound devices. It should not crash
ofcourse but i dont see what kitty can do about it. there may be some
libcanberra api to check for this error condition, but i am not sure.

**Comment by kovidgoyal** [comment]
See for example: https://www.linuxquestions.org/questions/slackware-14/sound-problems-on-slackware64-current-october-17th-update-4175640546-print/

I dont think there is anything kitty can do here. You can use the
workaround @luflosi suggested to prevent kity from trying to play the
beep.
