### ISSUE TITLE
Is it possible to typing in 2 pane / shell in the same time ?

### ISSUE THREAD

**Issue by Oxyaxion** [kovidgoyal/kitty#2354]
It's possible to sync 2 pane like terminator (or tmux) ? Typing text in 2 or mores panes / shell in the same time is very usefull for admin tasks.

I'm looking in the documentation but I can't find this feature ...

Thanks !

**Comment by kovidgoyal** [comment]
You can send arbitrary text to arbitrary numbers of windows using the
remote control protocol.
https://sw.kovidgoyal.net/kitty/remote-control.html 

So you write a small script that forwards key strokes from stdin to
arbitrary windows using remote control. Run the script in some window,
type there and what you type will appear in other windows.
