### ISSUE TITLE
macos_option_as_alt not working

### ISSUE THREAD

**Issue by siikamiika** [kovidgoyal/kitty#2355]
I just updated kitty from https://sw.kovidgoyal.net/kitty/binary.html, and my config at `.config/kitty/kitty.conf` having `macos_option_as_alt no` isn't in effect (alt isn't registered in key combos such as alt+o). What can I do to further debug the issue?

I'm running Catalina 10.15.3 and `kitty --version` says `kitty 0.16.0 created by Kovid Goyal`

**Comment by Luflosi** [comment]
If I understand you correctly, you need to set it to yes.
From the documentation:
```
Use the option key as an alt key. With this set to no, kitty will
use the macOS native Option+Key = unicode character behavior. This
will break any Alt+key keyboard shortcuts in your terminal
programs, but you can use the macOS unicode input technique. You
can use the values: left, right, or both to use only the left,
right or both Option keys as Alt, instead.
```

**Comment by kovidgoyal** [comment]
a value of no means the option key will not work as alt. A value of both
mens it will. https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.macos_option_as_alt

If you want pressing option+o to act as alt+o set it to both.

**Comment by siikamiika** [comment]
Alright so I think the problem was that I never actually restarted kitty although I tried different values for `macos_option_as_alt`. It works now after setting it to either `both` or `yes` and fully closing and opening kitty. Thanks!
