### ISSUE TITLE
Weird cursor on Manjaro Linux

### ISSUE THREAD

**Issue by joe23rep** [kovidgoyal/kitty#2356]
hi- i get a strage oldschool left hand cursor whenever i use kitty. its otherwise the perfect terminal so id love to use it but this makes it almost unusable to me. its not the gtk cursor- its something else. im not alone with this- found a different thread over on the manjaro forum but noone knew an answer.

https://forum.manjaro.org/t/kitty-terminal-mouse-cursor/110567

i tried the normal version and the git version out of the aur. both times they behave the same. maybe u know whats going on here and how i could change this. 

im running on a kde desktop and the kitty version is 0.16.0

**Comment by kovidgoyal** [comment]
dup of #2341
