### ISSUE TITLE
When switching IME, characters dangled

### ISSUE THREAD

**Issue by zk4** [kovidgoyal/kitty#2358]
kitty version: 0.16
system  version:   mac 10.12.6 (16G1710)

when switching IME from Chinese  to English with <command +space> key pressed ,  characters dangled.  
In Kitty 0.16
![2020-02-12 10 48 58](https://user-images.githubusercontent.com/996674/74298697-7492fa80-4d85-11ea-8f4a-afcdadd8482e.gif)

I test it on iTerm2 and Mac  Terminal ,  they both do fine. When switching the IME,  they will clear the dangled characters in the screen.  
In iTerm2 
![2020-02-12 10 54 34](https://user-images.githubusercontent.com/996674/74298943-25999500-4d86-11ea-98e0-baefcf6b3bb6.gif)

The characters seem to be left on the screen buffer. When switching IME, that little character-dangled aera does not redraw. If I type some characters to overwrite the area of dangled characters. It will be overwrited.

**Comment by kovidgoyal** [comment]
most likely glfw/coca_window.m will need to be modified to intercept this event and clear any pending IME.

**Comment by zk4** [comment]
Is there any plan to fix this  in latest version?

**Comment by zk4** [comment]
@kovidgoyal 
Thanks for your fix! That's quick ! But problem still exist, 😅 just become a little smaller.
I tried  https://github.com/kovidgoyal/kitty/commit/56e5c8be3279963220edd6da9141f804d2a08fd1
，

When typing in NVIM v0.5.0-370-g5d5b068d5  in latest kitty, some characters still dangled.
This dangled chars is produced by vim extension `coc-imselect` with coc.vim.
![image](https://user-images.githubusercontent.com/996674/74658398-2b033f00-51cd-11ea-9d15-4cdafa0fe599.png)

and I tested it in iterm2.  iterm2 seems ok.  
![image](https://user-images.githubusercontent.com/996674/74658709-cdbbbd80-51cd-11ea-946c-d209e081876f.png)

**Comment by kovidgoyal** [comment]
Well I can replicate the issue, so someone that can is going to have to
improve the patch.

**Comment by kovidgoyal** [comment]
Or simply press the key to cacnel the IME before switching.

**Comment by zk4** [comment]
Solved. In case some encounter the same problem. Here is the solution.

Cocconfig
"imselect.enableFloating": false
