### ISSUE TITLE
tab_bar_style has no effect on macOS

### ISSUE THREAD

**Issue by kmatt** [kovidgoyal/kitty#2360]
In Kitty 0.16 **tab_bar_style** seems to have no effect. Setting to either separator or powerline still shows the "fade" effect. As a check of the config syntax, the same settings in a Fedora 31 Xfce VM changes the tab style accordingly.

```
$ kitty --debug-config
kitty 0.16.0 created by Kovid Goyal
Darwin kmatt 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.14.6 BuildVersion:	18G103
Loaded config files: /Users/kmatt/.config/kitty/kitty.conf

Config options different from defaults:
font_family     FiraCode-Medium
mouse_hide_wait 3.0
tab_bar_style   separator
```

![image](https://user-images.githubusercontent.com/435936/74371913-b03ebc00-4da7-11ea-888b-14fccbb68ab8.png)

**Comment by Luflosi** [comment]
Works for me.
Do any other settings take effect? Are you editing the right file (`/Users/kmatt/.config/kitty/kitty.conf`)? Did you restart kitty?

**Comment by kmatt** [comment]
> Are you editing the right file ?

Yes, see output of --debug-config above. Output shows the three settings changed from default.

Multiple restarts in testing different settings of tab_bar_style and font_family.

**Comment by kmatt** [comment]
App bundle from Installed from app bundle in https://github.com/kovidgoyal/kitty/releases/tag/v0.16.0 shows the above behavior, but local build from source with v0.16.0 tag is working as expected.
