### ISSUE TITLE
Wayland fuzzy text on HiDPI monitor when resuming from sleep

### ISSUE THREAD

**Issue by donnex** [kovidgoyal/kitty#2361]
I'm running multiple monitors on my setup. One of the monitors are using scale factor 2.0 since it's a 4k monitor. This works great and kitty looks very sharp.

However when sleeping / suspending the computer and wake it up again kitty seems to loose the scale factor and all existing terminals on this monitor get fuzzy text. If I open a new terminal it works as intended with sharp text again.

- Arch Linux
- Sway 1.2
- Kitty 0.16.0

```
Output eDP-1 'Unknown 0x573D 0x00000000'
  Current mode: 1920x1080 @ 60.033001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal

Output HDMI-A-1 'Dell Inc. DELL U2719DC 9J6Q5R2'
  Current mode: 2560x1440 @ 59.951000 Hz
  Position: 1920,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal

Output DP-6 'Dell Inc. DELL P2415Q D8VXF87309FB' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 4480,0
  Scale factor: 2.000000
  Subpixel hinting: unknown
  Transform: 270
```

Screenshot of two terminal windows. One created before suspend and the other after wakeup.

![2020-02-13-113945_screenshot](https://user-images.githubusercontent.com/58866/74437694-d6786080-4e68-11ea-83c6-59f1b8758af7.png)

**Comment by kovidgoyal** [comment]
How are you sleeping/suspending and does this happen with only a single monitor if you manually set its scale to 2??

**Comment by kovidgoyal** [comment]
no followup
