### ISSUE TITLE
Option to start a specific size?

### ISSUE THREAD

**Issue by JamsNJellies** [kovidgoyal/kitty#2363]
When kitty is closed and then re-opened, it starts at the previous size. This is annoying when opening multiple terminals, is there some way to start at a specific size or to disable this behaviour?

**Comment by Luflosi** [comment]
See the three options at https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.remember_window_size.

**Comment by JamsNJellies** [comment]
Thanks, changed my config now.
