### ISSUE TITLE
Trouble rendering SVG and some transparent PNGs

### ISSUE THREAD

**Issue by SitiSchu** [kovidgoyal/kitty#2364]
When trying to display a SVG (using `kitty +kitten icat`) the output looks like the following:
![image](https://user-images.githubusercontent.com/18517178/74577755-20f4fc80-4f91-11ea-99ab-07ce4c17ed49.png)

The SVG I'm using is this one: https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg 

I get similarly garbled output when displaying some PNGs with transparency:
![image](https://user-images.githubusercontent.com/18517178/74577882-dc1d9580-4f91-11ea-8af1-973570039ee2.png)

Running kitty with `--debug-gl` doesn't throw any errors.
kitty version 0.16.0

**Comment by kovidgoyal** [comment]
Works fine for me on arch with snowflake.svg. icat call convert from imagemagick to process images. There are probably issues with your ImgeMagick installation.
![snowflake](https://user-images.githubusercontent.com/1308621/74590227-982e9d00-5032-11ea-85a0-e18caa6a7d46.png)

**Comment by Mukundan314** [comment]
I am also having the same issue but manually converting the `svg` to a `png` with imagemagick seems to work fine

Command used for converting `svg` to `png` then displaying it (tried to make the command as close to what the `convert` function in `kittens/tui/images.py` would execute):
```
$ convert -background none -- <path/to/file.svg> -depth 8 tmp.png && icat tmp.png
```

ImageMagick Version: `ImageMagick 7.0.10-6 Q16 x86_64 2020-04-07`
Kitty Version: `0.17.2`

Screenshot:
![1587040235](https://user-images.githubusercontent.com/30190448/79457561-092c0a00-800e-11ea-9db1-bc123e1809ac.png)

**Comment by kovidgoyal** [comment]
Then there will be some environment variables you set in your shell startup scripts bt not globally that are causing the different behavior of ImageMagick.

**Comment by Mukundan314** [comment]
I have found the problem in version `v0.17.2` of kitty the [convert function](https://github.com/kovidgoyal/kitty/blob/v0.17.2/kittens/tui/images.py#L79) does not explicitly set the depth option for the convert command but this has been fixed in the [master branch](https://github.com/kovidgoyal/kitty/blob/master/kittens/tui/images.py#L97), so the problem should be fixed in the next release.
