### ISSUE TITLE
check for precomposed characters before switching to a fallback font

### ISSUE THREAD

**Issue by tertium** [kovidgoyal/kitty#2365]
Currently, when Kitty processes composed characters, it requires the base codepoint as well as every combination character to have dedicated glyphs in the font (see [`has_cell_text()`](https://github.com/kovidgoyal/kitty/blob/64567646d9c92519967828d44cca6869933f6b5f/kitty/fonts.c#L475)), otherwise it switches to a fallback font. This is undesirable when a font has a precomposed glyph for the combination but not the individual combination chars. For instance, Roboto Mono is rather bad in this regard.

Given that HarfBuzz will try to normalize the combination anyway, we can just look for a precomposed character in the current font before giving up. Possible [implementation](https://gist.github.com/tertium/629468565ee6cad3d758e36ed6af331d).

**Comment by tertium** [comment]
That was lightning quick, thank you!

**Comment by tertium** [comment]
The second argument of `hb_unicode_compose()` in line 487 in `fonts.c` should be `cell->ch` instead of `ch`, otherwise the test does not work. Sorry, didn't notice it at first.

**Comment by kovidgoyal** [comment]
right, thanks.
