### ISSUE TITLE
Elinks fails to switch to the alternate screen mode

### ISSUE THREAD

**Issue by tertium** [kovidgoyal/kitty#2366]
The terminal-based web browser Elinks uses the CSI code `?47h` to switch to the altscreen mode, which is supported by XTerm and URxvt, but not by Kitty which only recognizes `?1049h`. One negative consequence of this is that scrolling with mouse wheel does not work.

The issue is arguably on the Elinks' side, but it would be nice if mode 47 was supported as a synonym for 1049. Possible [implementation](https://gist.github.com/tertium/7f5c47b54c0288295f7d98dfb872559b).

**Comment by kovidgoyal** [comment]
This is definitely a bug in elinks. Application must use the terminfo
properties smcup and rmcup to change to alternate screens. kitty's
terminfo species 1047 for these. If elinks has this value hardcoded it
should be changed to use the value from terminfo.

**Comment by tertium** [comment]
Fair enough.

To whomever with the same issue, `tput smcup ; elinks ... ; tput rmcup` will work, too, as long as you don't use the "OS Shell" feature (or at least don't use altscreen programs when in there).
