### ISSUE TITLE
Weird cursor icon in programs like ranger and htop

### ISSUE THREAD

**Issue by LaBatata101** [kovidgoyal/kitty#2369]
OS: Manjaro 19.0.0 Kyria
kitty 0.16.0
This is my normal cursor icon:
![cursor](https://user-images.githubusercontent.com/20308796/74611363-daf78000-50d9-11ea-918e-67c9162ecae8.png)
But when I open ranger or htop it gets like this:
![htop](https://user-images.githubusercontent.com/20308796/74611375-ffebf300-50d9-11ea-9db1-7a05027b5119.png)
Why does that happen?

**Comment by Luflosi** [comment]
Dup of #2341.

**Comment by Luflosi** [comment]
The fix will be in the next version.
