### ISSUE TITLE
Open tab in the current working directory

### ISSUE THREAD

**Issue by wuerges** [kovidgoyal/kitty#237]
I'm really sorry to bother you with this since there's probably already a setting that enables this option. 

How can I make it so kitty opens new tabs in the current working directory, instead of going back to cwd?

**Comment by kovidgoyal** [comment]
What's the difference between current working directory and cwd? Note that the terminal emulator cannot in general know what the cwd for the process running inside it is. So new tabs will open with whatever the cwd for the *kitty* process is.

**Comment by kovidgoyal** [comment]
Actually, with a bit of googling it turns out that it is possible to detect the current working directory of a child process using platform specific APIs. So, in theory this could be implemented.
