### ISSUE TITLE
Bold font looks mangled and misaligned

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#2376]
I'm using kitty with these [configs](https://pastebin.com/AQMwDKZx):
And the fonts are monospaced which I get from calling `kitty list-fonts`

The regular font looks good without any problems, however, the bold font looks like this:

https://i.imgur.com/qxihkmC.png

https://i.imgur.com/1XcbKSk.png

Any ideas why?

**Comment by kovidgoyal** [comment]
Probably because the bold fonts metrics dont match the regular font so it is being resized to fit. Try a font family whose bold face is metric compatible with the regular face or alternately make the kitty cell larger with adjust_cell_width in kitty.conf.

**Comment by esn89** [comment]
thank you.  I will play around with the adjust_cell_width!
