### ISSUE TITLE
Diff kitten broken in 0.16.0 for directories ?

### ISSUE THREAD

**Issue by amanjitsk** [kovidgoyal/kitty#2378]
Hi,
Running `kitty +kitten diff dir1 dir2` gives the following error in release 0.16.0
![image](https://user-images.githubusercontent.com/12499495/74832926-6b0a1500-52e6-11ea-8034-79d1acfbc573.png)
whereas the same command works as expected for version 0.15.1 . Is this a known bug or am I just missing a dependency ?
Thanks,
Amanjit

**Comment by kovidgoyal** [comment]
I cannot replicate and that traceback does not make much sense. Can you create a tarfile with minimal directories to comapre that generates the error?

**Comment by amanjitsk** [comment]
Seems like the issue exists with `.DS_store` files on a mac, and some others like the attached `.ropeproject` directory. Put either one of these in a subdirectory of one of the two directories that will be diffed, and you should be able to replicate the error.
[faulty.tar.gz](https://github.com/kovidgoyal/kitty/files/4225467/faulty.tar.gz)
