### ISSUE TITLE
Programs with mouse support flips the mouse pointer

### ISSUE THREAD

**Issue by LouisTakePILLz** [kovidgoyal/kitty#2379]
![image](https://user-images.githubusercontent.com/920910/74860549-dc61bc00-5316-11ea-95b8-28c5434bd0f9.png)

I tested this behavior with `vim`, `nvim` (both with `set mouse=a`) and `nano -m`.
Kitty seems to be the only terminal to behave like this. I didn't have this problem with xterm, st, alacritty or termite.

Kitty version: 0.14.6
OS: NixOS 19.09 x86_64 (Linux 5.4.15)
Shell: zsh 5.7.1
DE: xsession (no DE)
WM: bspwm

Config: [kitty.conf](https://github.com/LouisTakePILLz/dotfiles/blob/971de53a8e1db1ae3208a9017333ad906008848f/term/.config/kitty/kitty.conf)

**Comment by Luflosi** [comment]
Duplicate of #2341. This is fixed in master.

**Comment by LouisTakePILLz** [comment]
Okay thanks!
