### ISSUE TITLE
Can't run some commands.

### ISSUE THREAD

**Issue by karambaq** [kovidgoyal/kitty#238]
Hello, I using OS X High Sierra, and can't run some commands from kitty, for example neovim, I launch it with nvim and kitty says:

     zsh:  command not found: nvim

Thank you.

**Comment by kovidgoyal** [comment]
That means PATH is not being set correctly. Set it manually in the init file for whatever shell you use. >zshrc or .bashrc or whatever.

**Comment by karambaq** [comment]
Godbye kitty.
