### ISSUE TITLE
Kitty is not working properly under ubuntu 18.04 Gnome

### ISSUE THREAD

**Issue by jamellyf** [kovidgoyal/kitty#2380]
I followed the installing steps on [(https://sw.kovidgoyal.net/kitty/binary.html)](url). First when trying to run Kitty from terminal it was complaining about server side decorations, so I've forced wayland on Kitty settings `linux_display_server wayland`. The problem is that when I set up some keyboard shortcut to the `kitty` command it does not work.

**Comment by jamellyf** [comment]
I've switched to Xorg and on it everything seems to work properly.

**Comment by kovidgoyal** [comment]
GNOME does not support server side decorations so kitty will default to
X11 under GNOME. And I cannot replicate shortcuts not working under
wayland in kitty.

**Comment by jamellyf** [comment]
Thanks!
