### ISSUE TITLE
Inconsistent colors in scrollback mode

### ISSUE THREAD

**Issue by LouisTakePILLz** [kovidgoyal/kitty#2381]
Colors render differently with scrollback mode enabled:
![scrollback_colors](https://user-images.githubusercontent.com/920910/74875230-e8a64300-532f-11ea-9d7b-81747c7b3dc4.gif)

Kitty version: 0.14.6
OS: NixOS 19.09 x86_64 (Linux 5.4.15)
Shell: zsh 5.7.1
DE: xsession (no DE)
WM: bspwm

Config: [kitty.conf](https://github.com/LouisTakePILLz/dotfiles/blob/971de53a8e1db1ae3208a9017333ad906008848f/term/.config/kitty/kitty.conf)

**Comment by kovidgoyal** [comment]
I cannot reproduce using the default scrollback pager, less and the default kitty.conf and kitty from master. If you can come up with a minimal kitty.conf and set of steps to reproduce with kitty 0.16 or kitty from master, update this issue and I will re-open.

**Comment by trygveaa** [comment]
I can reproduce it without a `kitty.conf` and kitty from master by running `ls -1` in the kitty repo and pressing `kitty_mod+h`.

Normal:
![shot_2020-02-24_19-19-43_491x843](https://user-images.githubusercontent.com/601966/75179571-a53a4300-573a-11ea-9afc-e8497aa51097.png)

Scrollback pager:
![shot_2020-02-24_19-19-47_491x843](https://user-images.githubusercontent.com/601966/75179573-a66b7000-573a-11ea-8208-75d39f385e14.png)

**Comment by trygveaa** [comment]
I tried without `.zshrc` now and the problem disappeared. Will investigate further.

**Comment by trygveaa** [comment]
For some reason I can't reproduce it with `ls` anymore, even after reinstating my config.

But I can reproduce it by running `git log -p` in the kitty repo and then pressing `kitty_mod+h`, without `kitty.conf` or `.zshrc`.

**Comment by kovidgoyal** [comment]
Does not reproduce for me with

kitty --config NONE git log -p

and pressing ctrl+shift+h

check your environment variables.

**Comment by trygveaa** [comment]
It still happens for me with 2d870fc8. I tried removing environment variables such as `LESS` and `PAGER`, and running `kitty --config NONE git log -p`.

These are the environment variables that are left:
<details>
  <summary>Click to expand</summary>
<pre><code>DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_STARTUP_ID=awesome/kitty/596-0-george_TIME125199
DISPLAY=:0
EDITOR=vim
HOME=/home/trygve
KITTY_WINDOW_ID=365
LANG=en_US.UTF-8
LC_ADDRESS=nb_NO.UTF-8
LC_COLLATE=nb_NO.UTF-8
LC_CTYPE=nb_NO.UTF-8
LC_IDENTIFICATION=nb_NO.UTF-8
LC_MEASUREMENT=nb_NO.UTF-8
LC_MONETARY=nb_NO.UTF-8
LC_NAME=nb_NO.UTF-8
LC_NUMERIC=nb_NO.UTF-8
LC_PAPER=nb_NO.UTF-8
LC_TELEPHONE=nb_NO.UTF-8
LC_TIME=nb_NO.UTF-8
LOGNAME=trygve
MAIL=/var/spool/mail/trygve
OLDPWD=/home/trygve
PATH=/home/trygve/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:./node_modules/.bin:/home/trygve/.yarn/bin
PWD=/home/trygve/dev/kitty
SHELL=/usr/bin/zsh
SHLVL=2
TERMINFO=/usr/lib/kitty/terminfo
TERM=xterm-kitty
USER=trygve
_=/usr/bin/env
WINDOWID=6293051
WINDOWPATH=1
XAUTHORITY=/home/trygve/.Xauthority
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_TYPE=tty
XDG_VTNR=1
</code></pre>
</details>

**Comment by trygveaa** [comment]
I bisected the issue to commit bd3f0b53639988f5d09f4ecc8be4e88a4c1a01f1.

**Comment by kovidgoyal** [comment]
Can you run kitty --dump-bytes and post the dump with some minimal git log -p output that shows the issue. I dont see anything wrong with either of those two commits.

**Comment by kovidgoyal** [comment]
Oh and the terminal size you used when generating the dump is probably also relevant.

**Comment by trygveaa** [comment]
Here it is. The terminal size when running this was 50x80 and I ran it with `./kitty/launcher/kitty --dump-bytes kitty-color-issue-dump.txt --config NONE git log -p -2 2d870fc8~`
[kitty-color-issue-dump.txt](https://github.com/kovidgoyal/kitty/files/4249156/kitty-color-issue-dump.txt)

**Comment by trygveaa** [comment]
Here is a minimal text which reproduces the issue for me when `cat`-ing it:
```
[32mgreen[0m
[32mgreen[0m
```

[Here it is as an attached file](https://github.com/kovidgoyal/kitty/files/4250061/color.txt), including some other combinations of colors. This is what it looks like here:

Normal mode:
![shot_2020-02-25_13-56-50_325x305](https://user-images.githubusercontent.com/601966/75249526-c5b7db00-57d6-11ea-9588-9bf92c8dba2e.png)

Scrollback mode:
![shot_2020-02-25_13-56-54_325x305](https://user-images.githubusercontent.com/601966/75249529-c6507180-57d6-11ea-8133-f9ad89a56b3f.png)

So the issue seems to be that if a line ends with some color or attributes and the next line starts by setting the same, they won't be set.

**Comment by trygveaa** [comment]
Oh, so it was a bug in less.

Thanks for fixing it! I can confirm that it works.
