### ISSUE TITLE
Cannot open kitty window on the focused display (monitor)

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#2383]
Kitty version 0.16.0
macOS: 10.15.3

Background:
I use my MacBook Pro with two external monitors. And I bind a shortcut to open kitty by an application called [skhd](https://github.com/koekeishiya/skhd) as this: `cmd - return : /Application/kitty/Contents/macOS/kitty --single-instance -d ~`, which means pressing Command key plus Enter key to open a kitty window.

My concern:
On monitor_1, I open a kitty window and then I close it (kitty is still running with no window). Then I move my mouse pointer to monitor_2 and make monitor_2 be focused by one clicking. Then I try to open a kitty window on monitor_2, but the new window appears on monitor_1. 

It seems that kitty will remember the monitor where it is first launched. And later when we want to create a new window, no matter which monitor is focused, kitty will create it on that initial monitor. 

I am wondering whether I can create a new window on the focused monitor? Thanks a lot.

Best regards.

**Comment by kovidgoyal** [comment]
kitty does not choose monitors for windows. That is up to the window
manager. For instance, I use kitty with i3, precisely with
--single-instance and new kitty OS windows open on the currently active
workspace/monitor. 

I dont know what the deal with macOS is with regards to this, I would
not be surprised if, as usual, Apple fails to provide the needed APIs for
this. 

Read create_os_window() in glfw.c to see how kitty windows are created.
They call glfwCreateWindow to create an offscreen window, then send a
startup notification on X11 and finally show the window. There is no
point in the entire process where kitty chooses a monitor. 

If there is some API that kitty can use to help skhd position its
windows, feel free to send a PR, or let me know about it.

**Comment by yanzhang0219** [comment]
Okay, I got it. Thanks.
