### ISSUE TITLE
Kitty Tab Title Configuration

### ISSUE THREAD

**Issue by sundarv85** [kovidgoyal/kitty#2387]
Hello,

I'm using autokey to open certain applications quickly using shortcut keys using the method [described here](https://github.com/autokey/autokey/wiki/Scripting#switch-or-start-firefox).

This uses the `wmctrl -l`'s output and then open that application. 

For e.g. with Chromium or Firefox, always the name Chromium or Firefox is present in the output. A sample output is

```
0x02400001  1 linux bash
0x03400001  1 linux New Issue · kovidgoyal/kitty - Chromium
0x01a00003  1 linux test - Google Search - Mozilla Firefox
```

The first one is `Kitty`. The problem I have is whenever the tab title changes, the `wmctrl -l` output also changes. So I'm not able to link to the same kitty window every time.

Is it possible to add a name `- Kitty` at the end of all the tab titles, so that independent of the tab title, I can always link to the same window.

Note: That I would be able to [set the tab title](https://sw.kovidgoyal.net/kitty/remote-control.html?highlight=title#kitty-set-tab-title), but when I ssh into another system, the tab tile changes to root@system-name.

**Comment by kovidgoyal** [comment]
look for the tab_title_template option in kitty.conf

**Comment by sundarv85** [comment]
I already tried the `tab_title_template`. I do see that the template changes the name that is displayed in the Kitty itself. However, the output of `wmctrl -l` still only the original tab title and not the one that is rendered using the `tab_title_template`.

For e.g. I changed the template variable to
```
tab_title_template {title} -- Kitty
```
In the UI, I see it as `bash -- Kitty`, but the output `wmctrl -l` still shows
```
0x0500000e  1 linux bash
0x04e0000e  1 linux root@system ~
```
for the two Kitty application instances that I have opened.

**Comment by kovidgoyal** [comment]
I dont know why you are using title if you want to match applications.
use WM_CLASS for that. That's what it exists for. In any case, if you
want to override the title, use --title when invoking kitty.

**Comment by sundarv85** [comment]
Thanks! `WM_CLASS` is the better solution. I will use that.

**Comment by samnj** [comment]
@kovidgoyal old thread but how would you use WM_CLASS to match the kitty window in this case?

**Comment by kovidgoyal** [comment]
man kitty (the very first option)
