### ISSUE TITLE
Selection is moving when a tmux pane is scrolling

### ISSUE THREAD

**Issue by bengentil** [kovidgoyal/kitty#2388]
When using multiple panes in tmux, the selection in a pane starts moving when
another reach the last line and starts scrolling.

This may be linked to #2351 

![kitty-selection-issue](https://user-images.githubusercontent.com/2110851/74989065-bbe15100-543f-11ea-9baa-1cfd8d754483.gif)

**Comment by kovidgoyal** [comment]
kitty selections cannot work with tmux, the two are completely
orthogonal. If the text in the terminal moves then the selection must
move with it or be cleared. As always, I strongly recommend dropping the
use of terminal multiplexers, they are an awful, and largely unneeded, hack.
About the only thing tmux does that kitty does not (yet) do is provide a
daemon see #391

**Comment by Frankkkkk** [comment]
FYI: I had the same problem and thus reverted to another terminal; a shame that we don't know how to fix this.

**Comment by bechampion** [comment]
For now i guess i will only use kitty for vim , and alacritty for terminal , kinda unacceptable to suggest to no use multiplexers.
