### ISSUE TITLE
Allow different font sizes for different panes

### ISSUE THREAD

**Issue by Lyle-Tafoya** [kovidgoyal/kitty#2389]
Currently when I split into multiple panes, every pane uses the same font size.  If I change the font size, it impacts all the panes simultaneously. However, the only reason I would ever use a built-in splitting feature is to get different font sizes for the different panes. Otherwise I would just use tmux which offers this same functionality. Please consider adding the ability to control font size for different panes separately.

**Comment by kovidgoyal** [comment]
You can have different font sizes per OS window, not per kitty window.
That is not going to change.

**Comment by ctrlcctrlv** [comment]
If you are interested in the technical reasons why, this comment by @kovidgoyal might be of interest: https://github.com/kovidgoyal/kitty/issues/2259#issuecomment-571879195
