### ISSUE TITLE
kitty doesn't adapt to key remapping using xkb

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#239]
How to reproduce:
- Start kitty
- `setxkbmap -option caps:swapescape` - swaps CapsLock and Escape (very popular remap among Vim users).
- Now pressing Escape (physical key) both triggers Escape in kitty and toggles CapsLock (as it should). 

If kitty started after running *setxkbmap* then remapped keys work as expected but kitty won't respect to subsequent invocations of *setxkbmap*.

I know that there is an ongoing work to improve keyboard handling in *glfw* fork, but currently this problem causes me to restart all my terminals each time I remap keys (which I am doing each time dock/undock my laptop). I wonder if there is simple to way to fix this issue without changing too much code.

**Comment by kovidgoyal** [comment]
Not that I know of. Patches are welcome.

**Comment by kovidgoyal** [comment]
This is resolved in the xkb branch, see #1140

**Comment by sergei-dyshel** [comment]
Great work, I was waiting for this fix! :+1:
