### ISSUE TITLE
kitty keeps messing up my clipboard content when x forwarding

### ISSUE THREAD

**Issue by laggardkernel** [kovidgoyal/kitty#2390]
I have been using X forwarding to sync the clipboard content between the remote and the local machine. One weird thing I notice is that kitty keeps messing up my clipboard.

Environment:

local

- macOS 10.13.6
- kitty 0.16.0
- XQuartz 2.7.11

remote

- Archlinux with xorg-xauth 1.1-1
- tmux 3.0a with plugin [tmux-yank](https://github.com/tmux-plugins/tmux-yank)
- xsel 1.2.0

My tmux conf

```
# vim:foldmethod=marker:foldlevel=0:shiftwidth=2
if "test ! -d ~/.tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
bind-key M-e source-file ~/.tmux.conf \; display-message "Sourced .tmux.conf!"
set-option -g mouse on

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default
run -b '~/.tmux/plugins/tpm/tpm'

# Changing TERM doesn't help at all
set -g default-terminal "tmux-256color"
# set -g default-terminal "xterm-256color"
# set -g default-terminal "xterm-kitty"
```

The problem only happens in kitty, with remote tmux plugin tmux-yank when I yank things with my mouse.

## Problem Description
```
  lk@pd-arch ~ 
❯ xsel -p

  lk@pd-arch ~ 
❯ xsel -b
new
\ No newline at end of selection

  lk@pd-arch ~  
❯ # yank this line with mouse

  lk@pd-arch ~  
❯ xsel -p
# yank this line with mouse
\ No newline at end of selection

  lk@pd-arch ~  
❯ xsel -b
xsel -ib
xsel -b
lation.md
selectionbind-key    -T copy-mode-vi MouseDragEnd1Pane     send-keys -X copy-pipe "xsel -i --primary"bind-key    -T copy-mode    y                     send-keys -X copy-pipe "xsel -i --clipboard"# yank this line with mouse
\ No newline at end of selection
```

In the last command `xsel -b`, I print the content after I copied `# yank this line`, but some content comes from nowhere.

Does kitty has a internal buffer holding the clipboard content?

## What I've done

The plugin tmux-yank set the following related MouseDrag key binding.

```
bind-key    -T copy-mode    y                     send-keys -X copy-pipe "xsel -i --clipboard"
bind-key    -T copy-mode-vi MouseDragEnd1Pane     send-keys -X copy-pipe "xsel -i --primary"
```

After trial and err, it turns out that the problem happens

- only on kitty, which is not a problem on iTerm2 or Alacritty
- only when yank with MouseDrag, copying with `y` doesn't has the problem
- only with `xsel -i --primary`. (Setting `-i --clipboard` for `MouseDragEnd1Pane` solves the problem.)

**Comment by kovidgoyal** [comment]
kitty has nothing to do with X11 forwarding, that is between SSH and
wahtever program you are using to connect to the forwarded X server, the
terminal is not involved.

Kitty has native functionality to copy to clipboard, via OSC 52.
https://sw.kovidgoyal.net/kitty/kittens/clipboard.html

Use that and you will have no issues.

**Comment by laggardkernel** [comment]
I'm not sure. But from the output of `xsel -b`, `xsel -p` on the remote machine, everything is alright. Considering the problem doesn't occur with other terminals, there must be something happened on the local side. That's why I opened an issue here.

**Comment by kovidgoyal** [comment]
Try not using tmux and see if the problem still occurs.

**Comment by laggardkernel** [comment]
Without using tmux, the remote CLIPBOARD are synced back successfully by something like `echo "b-kitty" | xsel -b`.

I tried to use vim with `set clipboard=unnamed,unnamedplus`, which sync the CLIPBOARD correctly as well.

So, this is a bug of tmux?

**Comment by laggardkernel** [comment]
@kovidgoyal Sorry to disturb you again. But should I report this to tmux?

**Comment by kovidgoyal** [comment]
Sure, if you wish.

**Comment by laggardkernel** [comment]
I've reported this to tmux. The author of tmux deem it a problem of the implementation of OSC 52 in kitty.

Quote from nicm, author of tmux:

> This is a bug in Kitty, when using OSC 52 it appends to the selection rather than replacing it. I believe there may be an option to change this behaviour.
>
> However if you are using some mechanism to set the clipboard via X (such as xsel or xclip) it is pointless to also use OSC 52. You can stop tmux using it by turning off the set-clipboard option.

**Comment by kovidgoyal** [comment]
No, it's a bug in tmux, in that it refuses to use the proper OSC 52 protocol for the terminal emulator it is running in. As documented here: https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard

If tmux refuses to do the right thing, then use the clipboard_control setting as documented there with no-append.

**Comment by Davincible** [comment]
Sounds much more sensible to use `no-append` by default. It's what all the other emulators also do right
