### ISSUE TITLE
detach_window does not ask for target tab

### ISSUE THREAD

**Issue by skrobul** [kovidgoyal/kitty#2393]
I have recently updated kitty to v0.16.0, mostly because I was excited about new "detach tab" feature that I missed badly from tmux.

After adding relevant bindings to my  [kitty.conf](https://github.com/skrobul/dotfiles/blob/c929d7c/kitty.conf#L926-L927):
```
map kitty_mod+m detach_window new-tab # moves the window into a new Tab
map kitty_mod+/ detach_window ask     # asks which tab to move the window into
```
it does not seem to work correctly - when I press either `Ctrl+Shift+m` or `Ctrl-Shift+/`, the result is always the same - tab detaches into new OS window without any questions being asked.
If I understood the documentation correctly, `detach_window ask` should present list of open tabs and after user selects the tab, the window should be moved there.

screencast:   https://youtu.be/PxfXT6Gcu-4

Steps to reproduce the problem:

1. Open kitty
2. Open at least one extra tab
3. In that tab, open multiple windows
4. Trigger `detach_window ask` shortcut

While troubleshooting, I have opened the 'kitty shell' (`ctrl-shift-esc`) and ran `help detach-window` and it does not seem to have `ask` option, the tab can be specified only explicitly by number.

Am I doing something wrong?

Bit of extra context:
- OS: Fedora 31, running stock Gnome.

**Comment by kovidgoyal** [comment]
Works for me with

kitty --config NONE -o 'map f4 detach_window ask'

pressing f4 causes the kitten to run asking which tab to detach to.
