### ISSUE TITLE
resizing a single kitty session small (a few char lines) kills kitty. 

### ISSUE THREAD

**Issue by ulaas** [kovidgoyal/kitty#2394]
on amgdpu wayland
0.16.0
happens only on vertical resize,
horizontal has a limit for scale.

process dies if kitty scaled a lot on vertical axis

**Comment by kovidgoyal** [comment]
I cannot reproduce on weston running with

kitty --config NONE -o linux_display_server=wayland


resizing the window to 1 px high does not cause a crash. Post the stderr
and backtrace of the crash.

**Comment by ulaas** [comment]
hello here is the output. i am on sway, but looks like a wayland issue right?

 ~  kitty --config NONE -o linux_display_server=wayland                                                                                                                                                                                            11.7s  Mon 24 Feb 2020 04:20:37 PM +03
wl_drm@27: error 2: invalid name
[055 16:20:47.712785] [glfw error 65544]: Wayland: fatal display error: Protocol error

**Comment by kovidgoyal** [comment]
Ah, sway. It is by far the most fussy Wayland compositor. If you can
provide me with steps on how to reproduce the problem, I will look into
it. Is there a better way to make windows small in sway other than
making it float and resize??

**Comment by ulaas** [comment]
hello sir,
read this if you have time
https://github.com/alacritty/alacritty/issues/2895
i have the same hardware, and she/he also mentions kitty to have the same issue :)
i am thinking a mesa driver issue. not even sway or wayland,
any way thanks for your time. great terminal i love it.

**Comment by ulaas** [comment]
i will install mesa-git (they released 20.0 recently to see if that makes a difference. will let you know.

**Comment by ulaas** [comment]
hello, mesa 20.0 does not have this problem. so it is an issue for 19 users with NAVI10 boards i guess.
thanks

**Comment by kovidgoyal** [comment]
Thanks for letting me know.
