### ISSUE TITLE
Question: fonts fallback and available glyphs

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#2396]
Hey! I wanted to ask for your thoughts about how font fallback works exactly.

Imagine I have a `<mono-font>` set as `monospace` via fontconfig, and I have an `<emoji-font>` installed which if for example appended to the end of `monospace` family. With no extra configuration when I launch a new terminal, everything is rendered via `<mono-font>`, and only those glyphs that are not available in the font (e.g. smiley faces) will be rendered with `<emoji-font>`.

Now if I reverse this process, and *prepend* `<emoji-font>` to `monospace`, in this specific case I would expect that kitty would behave in the exact same way, it would first try to render everything via `<emoji-font>`, and since no glyphs would actually match the font it would fallback to rendering everything with `<mono-font>`.

This isn't what actually happens, in reality if I prepend the `<emoji-font>` like so:

```
<match target="pattern">
    <test name="family"><string>monospace</string></test>
    <edit name="family" mode="prepend" binding="same"><string>JoyPixels</string></edit>
</match>
```

kitty would crash on startup with the following error:

```
$ ./kitty/launcher/kitty
[056 00:23:37.808374] Cell height invalid after adjustment, ignoring adjust_line_height
[056 00:23:37.808401] Line height too small: 0
```

Why is so? Is this a bug or intentional behavior?

---

A bit of context of why I'm looking into this. In rare cases when the same glyph is present in several fonts, I want to enforce it to be rendered via a specific font.

I know that kitty is awesome and that it provides `symbol_map` for exactly this purpose. Unfortunately the rest of the world is not that flexible, and so I'm researching if there are some fontconfig hacks that could provide similar effect. And while trying this "prepend trick", I noticed that it crashes kitty and I got curious why.

**Comment by kovidgoyal** [comment]
The primary font is used to calculate cell metrics, this happens before
any fallback. I'm guess that calculation produces invalid values with
the emoji font you have specified. 

If you wan to use that hack specify an actual font_family in kitty.conf
