### ISSUE TITLE
Resizing window to reveal more lines in scrollback

### ISSUE THREAD

**Issue by DanielLaszlo** [kovidgoyal/kitty#2398]
I am using i3wm, and when I change the height of the window, the same number of lines are drawn from the scrollback as was previously visible. Is there a way to increase this line count, so that e.g. maximizing a window reveals more lines of the output of previous commands?

**Comment by kovidgoyal** [comment]
No, just scroll up. I personally dont like the contents of the screen
changing on window resize, but if you do, a PR with an option for
implementing that behavior is welcome.

**Comment by DanielLaszlo** [comment]
Okay, I might try to implement this behaviour. In the meantime, scrolling back doesn't really work as I expected. After I scroll back, and start typing, the prompt jumps back to its original position, where it was after the resizing. Is there a workaround to this?

**Comment by kovidgoyal** [comment]
Why would there be? You wan to type without being able to see what you
are typing??
