### ISSUE TITLE
latest kitty crashes on mouse-wheel scroll

### ISSUE THREAD

**Issue by AppMathIsRealMath** [kovidgoyal/kitty#2400]
My latest kitty build (0.16.0, commit 507fbc7a) crashes with a segmentation fault upon repeated mouse-wheel scrolling.

My distro's (Solus Linux 4.1) kitty (0.16.0 dated 4 Feb 2020) doesn't exhibit this issue as far as I can tell.

I can readily reproduce the fault with:

- start kitty terminal
- clang --help
- mouse-wheel scroll to top (sometimes needs scrolling up and down a bit)
- segmentation fault

Final lines from --debug-gl, --debug-keyboard:

> Press xkb_keycode: 0x2e clean_sym: l composed_sym: l text: l mods: none glfw_key: 76 (L) xkb_key: 108 (l)
on_key_input: glfw key: 76 native_code: 0x6c action: PRESS mods: 0x0 text: 'l' state: 0 sent text to child
Release xkb_keycode: 0x2e clean_sym: l mods: none glfw_key: 76 (L) xkb_key: 108 (l)
on_key_input: glfw key: 76 native_code: 0x6c action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
Press xkb_keycode: 0x21 clean_sym: p composed_sym: p text: p mods: none glfw_key: 80 (P) xkb_key: 112 (p)
on_key_input: glfw key: 80 native_code: 0x70 action: PRESS mods: 0x0 text: 'p' state: 0 sent text to child
Release xkb_keycode: 0x21 clean_sym: p mods: none glfw_key: 80 (P) xkb_key: 112 (p)
on_key_input: glfw key: 80 native_code: 0x70 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
Press xkb_keycode: 0x24 clean_sym: Return composed_sym: Return mods: none glfw_key: 257 (ENTER) xkb_key: 65293 (Return)
on_key_input: glfw key: 257 native_code: 0xff0d action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release xkb_keycode: 0x24 clean_sym: Return mods: none glfw_key: 257 (ENTER) xkb_key: 65293 (Return)
on_key_input: glfw key: 257 native_code: 0xff0d action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
Segmentation fault

My --debug-config:

> kitty 0.16.0 (507fbc7abf) created by Kovid Goyal
Linux solus 5.5.4-148.current #1 SMP PREEMPT Wed Feb 19 14:18:17 UTC 2020 x86_64
[[ Solus Operating System ]]
LSB_VERSION=1.4
DISTRIB_ID=Solus
DISTRIB_DESCRIPTION="Solus"
DISTRIB_RELEASE=4.1
DISTRIB_CODENAME=fortitude
Loaded config files: /home/sam/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background     Color(red=255, green=69, blue=0)
active_tab_font_style     (True, False)
active_tab_title_template 🢂 {index}
background                Color(red=13, green=13, blue=13)
cursor                    Color(red=102, green=255, blue=0)
cursor_text_color         Color(red=0, green=0, blue=0)
editor                    neovim
enable_audio_bell         False
font_family               Liberation Mono Bold for Powerline
font_size                 18.0
foreground                Color(red=255, green=255, blue=255)
inactive_tab_background   Color(red=0, green=0, blue=0)
inactive_tab_foreground   Color(red=102, green=102, blue=102)
initial_window_height     (924, 'px')
initial_window_width      (1680, 'px')
mouse_hide_wait           0.0
remember_window_size      False
scrollback_lines          131072
tab_bar_background        Color(red=13, green=13, blue=13)
tab_bar_edge              1
tab_fade                  (0.125, 0.25, 0.5, 0.75, 1.0)
tab_switch_strategy       last
tab_title_template        {index}
update_check_interval     0.0
window_alert_on_bell      False
Added shortcuts:
	page_up KeyAction(func='scroll_page_up', args=())
	page_down KeyAction(func='scroll_page_down', args=())
	home KeyAction(func='scroll_home', args=())
	end KeyAction(func='scroll_end', args=())
	f7 KeyAction(func='pipe', args=['@ansi', 'tab', 'less', '+G', '-R'])
	control+c KeyAction(func='copy_or_interrupt', args=())
	control+t KeyAction(func='new_tab_with_cwd', args=())
	control+escape KeyAction(func='previous_tab', args=())
	control+tab KeyAction(func='next_tab', args=())
Changed shortcuts:
	shift+control+n KeyAction(func='new_os_window_with_cwd', args=())

Output from dmesg:

> [16041.592842] kitty[85909]: segfault at 7f9cc9222068 ip 00007f9cc9e77400 sp 00007ffd92dcf4b0 error 6 in fast_data_types.so[7f9cc9dfb000+82000]
[16041.592910] Code: eb 05 54 c9 04 00 41 83 c1 01 48 83 c1 10 0f 11 41 f0 41 39 f1 72 e3 c1 e6 04 01 f2 41 39 f0 0f 84 

If I can provide any other information please let me know.

**Comment by kovidgoyal** [comment]
Post a backtrace from the crash

make debug

echo bt | coredumpctl gdb

**Comment by AppMathIsRealMath** [comment]
Your commit fixed it, thanks! I was about to attach the bt when I noticed you closed it - and indeed the fault happened in apply_selection().
