### ISSUE TITLE
Freezes with yash shell

### ISSUE THREAD

**Issue by travankor** [kovidgoyal/kitty#2404]
I tried to run kitty with the [yash](https://github.com/magicant/yash) shell, version 2.49. Kitty freezes and the memory consumption increases until OOM killer triggers. This behaviour does not happen on three alternative terminal emulators.

I am testing with a default yash instance and kitty's wayland backend.

**Comment by kovidgoyal** [comment]
The memory consumption of yash or kitty increases?? And what freezes, the shell or kitty? I am going to guess the latter. If so you should report it to the developers of the shell. If not update this bug report and I will re-open.
