### ISSUE TITLE
Change single window width with keyboard shortcuts

### ISSUE THREAD

**Issue by maxigaz** [kovidgoyal/kitty#2405]
Skimming through [the sample config file](https://sw.kovidgoyal.net/kitty/_downloads/433dadebd0bf504f8b008985378086ce/kitty.conf), I’ve found the option `single_window_margin_width`. I’m wondering if it’s possible to change its value on the fly, through keyboard shortcuts.

I’ve noticed that the [online documentation](https://sw.kovidgoyal.net/kitty/#layouts) mentions the following:

```
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3
```

However, these only seem to take effect when there are at least two windows open inside kitty. What I’d like to do instead is launch separate instances of kitty so that the arrangement of their position can be done with i3.

Using kitty 0.16.0 under Manjaro Linux.

**Comment by kovidgoyal** [comment]
No there is no facility for changing margins dynamically. it should be
easy to add via remote control however, patches welcome.

https://sw.kovidgoyal.net/kitty/remote-control.html
