### ISSUE TITLE
Ability to rotate windows

### ISSUE THREAD

**Issue by kraftwerk28** [kovidgoyal/kitty#2406]
Currently, you can only move window forward, backward and also to top (Ctrl+Shift+F; Ctrl+Shift+B, Ctrl+shift+` by default). What about adding shortcut to rotate window layout?
Like
Before:
```
+-----+-----+
|  A  |  B  |
+-----+-----+
|     C     |
+-----------+
```
After:
```
+-----+-----+
|     |  A  |
+  C  +-----+
|     |  B  |
+-----+-----+
```

**Comment by kovidgoyal** [comment]
You can add shortcuts to move a window to any of its neighbors. Search
for neighbor in https://sw.kovidgoyal.net/kitty/
