### ISSUE TITLE
Bell is off, but bell still sounds on MacOS

### ISSUE THREAD

**Issue by zostay** [kovidgoyal/kitty#2407]
I use the same config on Linux with no problems, but on Mac OS Catalina, even with `enable_audio_bell` turned off, the bell sounds when I do anything that triggers the bell, e.g., `echo '\a'`.

```
kitty 0.16.0 created by Kovid Goyal
Darwin Scamander.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:        10.15.3 BuildVersion:   19D76
Loaded config files: /Users/sterling/.config/kitty/kitty.conf

Config options different from defaults:
bell_on_tab          False
bold_font            Fira Code Bold
bold_italic_font     Fira Code Bold Italic
copy_on_select       clipboard
enable_audio_bell    False
font_family          Fira Code Regular
font_size            12.0
italic_font          Fira Code Italic
window_alert_on_bell False
```

I went ahead and turned off everything I could find that was bell related to see if that helped, but no joy. Works great on Linux, but not on Mac OS.

**Comment by kovidgoyal** [comment]
Works fine for me:

kitty --config NONE -o enable_audio_bell=n

results in no audible bell on macOS.
