### ISSUE TITLE
Weird behavior when resizing. (flashing, shaking, ghost shadow)

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#2408]
kitty version: 0.16.0
macOS version: 10.15.3

When I resize the kitty window, the fonts are shaking (stretching back and forth), the window is kinda flashing. What's more, in the last part of the gif, when the window is maximized suddenly, there are some residual shadows (i.e, some words appear at someplace momently).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11582667/75826756-12faf600-5d5d-11ea-8c58-cccdb2f6fb86.gif)

Thank you.

**Comment by kovidgoyal** [comment]
I cant make out what th eissue is in your attached gif, but if you dont like the resize draw behavior, change the value of resize_draw_strategy in kitty.conf to something that better suits you, such as blank or size or static (the default).
