### ISSUE TITLE
Open program for hints in overlay

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#2409]
I'm trying to run a program which gets the result from the hints kitten and outputs to an overlay in the same kitty window, but I'm not able to figure out if it is possible.

I tried using `--customize-processing` and running `boss.launch('--type', 'overlay', ...)` in `handle_result`, but the result opens in a new window instead of in an overlay.

What I'm trying to accomplish is using the hints kitten to select an url which points to an image. Then I want that image to be shown in an overlay in the terminal, so the only thing which is shown is that image, until I press a button to close the overlay and go back to the normal terminal.

**Comment by trygveaa** [comment]
I managed to get the result I want by launching my kitten first, and then calling both `hints` and `icat` from `main` of my kitten.

I'd still be interested to hear anything about why the launch command opened a new window instead of an overlay though. Is it because the hints overlay still was active?

**Comment by kovidgoyal** [comment]
Yes you cannot open an overlay on top of another overlay. A windo can
have only a single overlay at a time. If you wish to chain multiple
overlays, you can do so via the action_on_close facility to launch the
second overlay once the first has closed.

**Comment by trygveaa** [comment]
Ah, didn't know about `action_on_close`. Thanks!
