### ISSUE TITLE
v0.6.0 requires OS X 10.12?

### ISSUE THREAD

**Issue by justinnhli** [kovidgoyal/kitty#241]
I recently updated kitty via homebrew on my MacBook Air, but got the message that the application now requires OS X 10.12 (I'm running OS X 10.10.5). Downloading the dmg from the releases page results in the same issue. v0.5.1 does not have this problem.

Is this deprecation of support for older versions intentional?

**Comment by kovidgoyal** [comment]
yes, the 10.9 VM I use to build kitty mysteriously stopped working. THere is nothing in kitty's code that actually requires 10.12 as far as I know, so you should still be able to build it yourself on older versions of mac os.
