### ISSUE TITLE
kitty master crashes on macOS

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#2410]
The latest master 1e998b6a3f2f3042b02df2ee7e31db0b2f704340 crashes on macOS when quitting kitty.
Here is the stack trace:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.python.python             	0x000000010591fa23 subtype_dealloc + 197
1   org.python.python             	0x00000001058e8c18 method_dealloc + 103
2   fast_data_types.so            	0x0000000106074817 cleanup + 135 (cocoa_window.m:487)
3   org.python.python             	0x000000010599a836 Py_FinalizeEx + 384
4   org.python.python             	0x00000001059b8960 pymain_main + 5095
5   org.python.python             	0x00000001059b7573 Py_Main + 52
6   kitty                         	0x00000001058c4d0d main + 797
7   libdyld.dylib                 	0x00007fff707c47fd start + 1
```
If I remove the line `if (notification_activated_callback) Py_DECREF(notification_activated_callback);` from `kitty/cocoa_window.m`, I cannot reproduce the crash anymore.
Would you like me to do a git bisect?

**Comment by kovidgoyal** [comment]
bisects are always useful

**Comment by Luflosi** [comment]
You fixed it. I still bisected it and f0b29e15c3b5446c2a30e6accb657a92e609b8ed was the first commit with this issue.
