### ISSUE TITLE
Backwards mouse cursor in Vim, even after changing pointer_shape_when_grabbed

### ISSUE THREAD

**Issue by alexozer** [kovidgoyal/kitty#2413]
Hi, it appears that running Vim or Neovim in Kitty causes my mouse cursor to be shown backwards. I've tried each setting for `pointer_shape_when_grabbed` and the other two non-default settings ("beam" and "grabbed") show the corresponding correct cursor, but "arrow" still shows my backwards cursor.

See this screenshot: https://i.imgur.com/59uJFhx.png

My normal cursor in vim/neovim in other terminals is exactly this shown cursor, but reflected across the Y axis.

It's strange because I've tested this in plenty of other terminals and don't see this behavior, so I don't think it has to do with my cursor theme. If it's relevant though, I'm using the "Human" cursor theme.

This behavior occurs with a blank `kitty.conf`.

**Comment by kovidgoyal** [comment]
dup of #2341

**Comment by alexozer** [comment]
My apologies for the dup, after reading the related issues I did not realize the issue was in fact the same and that it was fixed in master, somehow. My bad.
