### ISSUE TITLE
Black background color when scrolling in vim with bright background

### ISSUE THREAD

**Issue by marlun** [kovidgoyal/kitty#2415]
If I use a vim colorscheme with a bright background color and scroll I get the terminal background color on the lines which shows. If I test the same in iTerm it does not happen. It also doesn't happen if I use page-down instead of scrolling a single line with 'j'

<img width="950" alt="Screenshot 2020-03-07 at 11 08 01" src="https://user-images.githubusercontent.com/19663/76141406-2c08ed00-6064-11ea-8e21-89e1eb142ebc.png">

I'm using 0.16.0 on MacOS 10.15.3.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim

**Comment by marlun** [comment]
Sorry about that, looked through old issues but forgot about the FAQ. `let &t_ut=''` worked great.

**Comment by kah-ell** [comment]
> Sorry about that, looked through old issues but forgot about the FAQ. `let &t_ut=''` worked great.

Thank you so much, you are a life saver. :)
