### ISSUE TITLE
Configure URL prefixes for hints kitten and URL detection?

### ISSUE THREAD

**Issue by nblock** [kovidgoyal/kitty#2416]
The hints kitten allows to configure the list of url prefixes with the `--url-prefixes` parameter. This can be used to add custom URL schemes and open them by pressing `kitty_mod+e`.

However, custom URL prefixes are not highlighted and underlined due to a hardcoded list of prefixes in https://github.com/kovidgoyal/kitty/blob/master/kitty/line.c#L52. As a consequence, they are not mouse-clickable with `kitty_mod+left-mouse`.

It would be great, if one can configure the list of url prefixes once and kitty uses this list for the hints kitten and the URL detection mechanism.

**Comment by kovidgoyal** [comment]
kittens and kitty are completely separate program they dont share
configuration. You could of course have a separate url prefixes setting
for kitty, patches are welcome.
