### ISSUE TITLE
Terminus (TTF) and thickness of glyphs to show the hierarchy

### ISSUE THREAD

**Issue by xenogenesi** [kovidgoyal/kitty#2418]
I am a kitty novice and for now I really like it.

As a font I have used Terminus (TTF) for a long time in different terminals and also in kitty it is well displayed:

```
font_family Terminus (TTF)
font_size 8.7
adjust_line_height -2
```

```
/var/log/Xorg.0.log: NVIDIA (0): DPI set to (92, 94); computed from "UseEdidDpi" X config
```

There is only one thing that bugs me visually with kitty and Terminus, often using commands such as `mutt`,` tree`, `htop`,` npm ls`, the glyphs used to represent hierarchies are thicker, at least 1 or 2 pixels more.

I tried the font with small variations in size but the result does not change.

Where could I look to make them less thick as with the other terminals? Can it depend on how kitty uses ttf fonts or does it depend on graphic libraries?

```
│ └─>
└─>
   └─>
```

**Comment by kovidgoyal** [comment]
Box drawing characters are not drawn from fonts and you can control
their thickness with a setting in kitty.conf look for box_drawing_scale
