### ISSUE TITLE
Feature request: Configurable application icon

### ISSUE THREAD

**Issue by myelsukov** [kovidgoyal/kitty#2424]
I am a heavy command line user. I often have several different applications running in several terminal windows. For the ease of navigation I would like those windows to have different icons.
Many terminal emulators provide command line options/configuration parameters for that.
For example:
xfce4-terminal: `--icon=<icon file name>`
urxvt: `-icon <icon file name>`, etc.

Right now I have to use [xseticon](http://www.leonerd.org.uk/code/xseticon/) line utility to set different icons to the different kitty windows.

Could you please consider adding command line option and/or configuration parameter allowing to change kitty application icon?

**Comment by kovidgoyal** [comment]
I dont think this is a good idea. Setting window icons only works on
X11, not Wayland and not macOS. And specifically for X11 there already
exist tools to set icons for windows, as you point out. Doesn't seem
worth the effort, therefore.
