### ISSUE TITLE
Weird black bar on the bottom right of my terminal

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#2427]
I am using Kitty 0.16.0 installed via the .dmg on my Mac.

And when I type into my terminal this black bar on the bottom right keeps flashing.  It comes when I focus on kitty, but when I focus it somewhere else, like Firefox, it is gone (I have a monitor attached to my mac)

https://imgur.com/a/uP2DyDZ

**Comment by kovidgoyal** [comment]
Whatever shell you are using is causing it, most likely because you have changed TERM. Make sure TERM is xterm-kitty and try with empty shell config to start.

**Comment by esn89** [comment]
You're right, fixed.
