### ISSUE TITLE
problems with opening windows with multiple spaces in macOS

### ISSUE THREAD

**Issue by szymonkaliski** [kovidgoyal/kitty#243]
I have this in kitty.conf:

```
map super+n new_os_window
```

Which works fine if I keep opening windows on the same desktop, but if I have kitty window running on one space, switch to another, then cmd-tab to kitty and hit cmd-n I don't get a window.

To reproduce:

- create two spaces
- open kitty on first space
- switch to second space
- cmd-tab to kitty
- hit cmd-n

**Comment by kovidgoyal** [comment]
I cannot replicate this on my mac with those steps, running from master. All I can suggest is check if the window is opened on some other space.

**Comment by szymonkaliski** [comment]
Yes, there is window open on another space, but cmd+n should open new one on the current one, that's how all the other macOS apps work (and iTerm for example).

**Comment by szymonkaliski** [comment]
Ok, I managed to work around this when compiled from source, and then used appify script with `--single-instance` mode. Thanks!
