### ISSUE TITLE
Ctrl+Tab to be ignored by Kitty

### ISSUE THREAD

**Issue by krish7919** [kovidgoyal/kitty#2430]
I have set my configs to change/switch on Cmd+<arrow keys> with Cmd being my `kitty_mod` key too.

The default setting of switching tabs using Crtl+tab still works with Kitty.

However, now I want to use Crtl+tab to switch between vim tabs and I cannot find the config in the docs to make kitty ignore the Ctrl+tab key combination.

Is this supported?

**Comment by krish7919** [comment]
Something to the effect of `nomap` or ignore the key combination so that vim, etc in the terminal window can handle it.

**Comment by kovidgoyal** [comment]
map cmd+tab no_op

Its in the first few paragraphs of https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts

**Comment by krish7919** [comment]
Wow you are fast!
