### ISSUE TITLE
Selection doesn't extend to left-most character

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#2431]
A couple of commits ago (I'm now on https://github.com/kovidgoyal/kitty/commit/60995ff04b7fbe8cf784da43473fb0a4628891ef), kitty stopped extending the selection to the left most character.

So, imagine that in the example below I'm trying to completely select the two lines of output. Currently, kitty doesn't allow me to extend the selection to the left most "A" of "Author", whereas it did so previously. If I move up the selection to the line above, said "A" is selected. 
![Peek 2020-03-13 21-49](https://user-images.githubusercontent.com/10417027/76658688-f472d700-6574-11ea-939a-8c9c33cc4c6b.gif)

I'm on X11, if that matters. Doesn't seem to be shell dependent.

**Comment by kovidgoyal** [comment]
works for me on X11, and there have been no recent commits that affect selection since the large selection refactor a week or two back. Note that to select the last character on a line, you have to move the mouse into the left half of the character (or right half if going from left to right).

**Comment by rien333** [comment]
> Note that to select the last character on a line, you have to move the mouse into the left half of the character (or right half if going from left to right).

Ah right, if I move my mouse on the left half of the character it works. But it deselects that character immediately if I go just slightly outside of it, which feels pretty weird. Is this intentional? Other programs like my browser 
 just keep the selection the same if I move mouse slightly outside the selection, or even outside of the window for that matter. Why does only the left-most character have this peculiar  behavior?

**Comment by kovidgoyal** [comment]
All characters have the same behavior. Watch the selection as it extends
by character, it will extend to the character under the mouse only after
it crosses half the character. And most programs have it as well. Watch
how selection works in your browser, as you move the mosue from right to
left, the next character is selected only when the mouse enters the left
half of the character.

**Comment by rien333** [comment]
> Watch how selection works in your browser, as you move the mouse from right to left, the next character is selected only when the mouse enters the left
half of the character.

Yeah totally agree about the left half stuff, but my last comment was meant to convey  something different. What kitty currently does different from other programs (and did not always do), is that the moment you _leave_ the left-most character, it deselects it. 

Compare my browser in the first gif, with kitty in the second in gif. If leave the "T" from "The" on my browser (chrome-based), and even if I go outside of the window all together, the "T" stays selected. Whereas in kitty, this letter suddenly deselects if I go outside of the character or the window. 

![browser](https://user-images.githubusercontent.com/10417027/76680853-d47efa00-65ec-11ea-96b3-3744a79f6569.gif)
**browser**

![kitty](https://user-images.githubusercontent.com/10417027/76680863-e3fe4300-65ec-11ea-845a-47c4c071dabc.gif)
**kitty**

To my knowledge, other programs (like emacs) seems to behave similar to the first gif, and don't alter the selection if you leave the window/left-most character.

**Comment by kovidgoyal** [comment]
I cannot reproduce, as long as the mouse remains vertically aligned with
the character, leaving the window does not de-select it.

**Comment by rien333** [comment]
Odd, must be something in my setup then. Thanks!

**Comment by kovidgoyal** [comment]
can you reproduce with an empty kitty config

kitty --config NONE

**Comment by rien333** [comment]
Nope, good catch. I'll see what in my config is causing this.

**Comment by rien333** [comment]
My issue seems to be caused by the fact that I've set `window_padding_width` to `8.0`.  If I create a config file with just that setting, and load it with `--config`, I can consistently reproduce the issue. 

If I set `window_padding_width` to `0` my selection problem does not occur.

**Comment by kovidgoyal** [comment]
OK, I'll take a look when I have a moment
