### ISSUE TITLE
Linux glitches

### ISSUE THREAD

**Issue by xenogenesi** [kovidgoyal/kitty#2435]
I am used to leaving my desktop pc turned on for hours, sometimes for days.

Today it stayed on for about 8-9 hours and when I turned it on I found this:

![kitty](https://user-images.githubusercontent.com/5729893/76686072-13c34000-6619-11ea-8667-38d93eb8de4b.png)

On the same PC I often use the web version of whatsapp with Chromium, since when I use Kitty I have noticed that often this has some graphic glitch, especially when I come back to the window after some time, usually I just need to open a new tab to refresh it .

This pc has a not very recent 2 gpu video card, any idea what the problem might be?

Thanks

```
04: 00.0 3D controller: NVIDIA Corporation GK104 [GeForce GTX 690] (rev a1)
```

**Comment by kovidgoyal** [comment]
It will be an issue with your GPU drivers. There's nothing that can be
done at an application level for this kind of thing.
