### ISSUE TITLE
remote side unexpectedly closed network connection

### ISSUE THREAD

**Issue by ricain59** [kovidgoyal/kitty#2437]
Hi,

I try used kitty, but on used plink i get this error "remote side unexpectedly closed network connection".
I have try on clean windows installation, without putty registry but i have a same error.
How resolve this?

With putty, works fine.

Thank you for help.

**Comment by Luflosi** [comment]
This is the wrong kitty. The KiTTY you're looking for is here: https://github.com/cyd01/KiTTY.
