### ISSUE TITLE
icat error: identify: unrecognized option `--`

### ISSUE THREAD

**Issue by wookayin** [kovidgoyal/kitty#2438]
I believe #1575 is related to this.

```
kitty +kitten icat file.png
Failed to open image: file.png with error: identify: unrecognized option `--' @ error/identify.c/IdentifyImageCommand/920.
```

It seems that on some environments `convert` does not accept the `--` separator.

Environment:

- MacOS (10.14 Mojave)
- ImageMagick 7.0.7-35 Q16 x86_64  (installed through `brew install`)
- Kitty: 0.16.0

```
$ kitty --version
kitty 0.16.0 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
That's a bug in your version of ImageMagick. Works fine for me:

identify -version                                                                                              
Version: ImageMagick 7.0.10-0 Q16 x86_64 2020-03-07 https://imagemagick.org

identify -- logo/kitty.png                                            
logo/kitty.png PNG 256x256 256x256+0+0 8-bit sRGB 8355B 0.000u 0:00.000


And the same on macOS with:

identify -version
Version: ImageMagick 7.0.8-9 Q16 x86_64 2018-08-08 https://www.imagemagick.org

identify -- x.jpg   
x.jpg JPEG 1334x976 1334x976+0+0 8-bit sRGB 83316B 0.000u 0:00.000

**Comment by wookayin** [comment]
Reinstalled imagemagick and now it works. Thanks for the information!
