### ISSUE TITLE
GTK theme variants

### ISSUE THREAD

**Issue by dwma** [kovidgoyal/kitty#2439]
Is there a setting to change which variant of a GTK theme (light or dark) kitty will use? Currently, setting it via the GTK_THEME env var won't work. I tested this under Gnome 3.36 with Wayland, kitty 0.16.0:
```
GTK_THEME=Adwaita:dark kitty
```
However, what does work is changing the theme after the kitty window has opened using a tool like xprop:
```
xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT "dark" -name "zsh"
```

**Comment by kovidgoyal** [comment]
kitty does not have any knowledge about GTK or link against any GTK
libraries. I assume you mean the theme for the window decorations? Those
are controlled by the window manager, not kitty.

**Comment by baco** [comment]
Alacritty can.

**Comment by 73** [comment]
Is that a "never gonna happen"?

> kitty does not have any knowledge about GTK or link against any GTK
> libraries. I assume you mean the theme for the window decorations? Those
> are controlled by the window manager, not kitty.

Is that a "never gonna happen"?

**Comment by kovidgoyal** [comment]
Yes, kitty is never going to link against GTK, or indeed any desktop environment. If you want native window decorations under GNOME, use the X11 backend for kitty, in which case mutter or whatever the idiotic GNOME window manager is called will provide native window decorations, or just ditch GNOME if you want to use Wayland.

**Comment by baco** [comment]
Nope, I guess is not GNOME's Client Side Decorators what we are asking here to have. Only to honor that if the global theming is dark, in either GNOME, XFce, Mate, or whatever GTK-based desktop environment you are on; then the color of the Window Title Bar (not the CSD, the Title Bar) to be dark as well.

**Comment by kovidgoyal** [comment]
There is no title bar. Window title bars are part of window decorations.

**Comment by 73** [comment]
> There is no title bar. Window title bars are part of window decorations.

Exactly what you use X11 (xlib) for.
We would kindly like to ask you to make the [X property](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#XChangeProperty) `_GTK_THEME_VARIANT` accessible by config (so we may set it to `dark`).

I am very sorry if we have triggered you. It was not my intention to set you off.

**Comment by kovidgoyal** [comment]
Sorry, I dont get it. If you want to use a dark theme, use one. Set it up in your desktop settings, and if you are using X11, then window decorations are drawn by your desktop environment so they will be respected, automatically. If they are not, open a bug report with your desktop environment.

There is no need for every application to add support for it in any form. Indeed, if whatever desktop environment you are using requires every application to be configured independently for dark mode, its is a frankly ridiculous desktop environment and you should find a better one.

**Comment by 73** [comment]
I don't want to use dark theme on all applications. Which could very well be done by a desktop setting.

> There is no need for every application to add support for it in any form. Indeed, if whatever desktop environment you are using requires every application to be configured independently for dark mode, its is a frankly ridiculous desktop environment and you should find a better one.

You are right. There is no need. An I am not required to do so. There is just the possibility to do so, and frankly I would like to. That is all. I think Kitty is great and this would be the cherry on top.

If you are not fond of implementing it yourself, never mind. However, would you be willing to accept a pull request?

**Comment by kovidgoyal** [comment]
On Wed, Nov 04, 2020 at 11:40:35PM -0800, 73 wrote:
> I don't want to use dark theme on all applications. Which could very well be done by a desktop setting.
> 
> > There is no need for every application to add support for it in any form. Indeed, if whatever desktop environment you are using requires every application to be configured independently for dark mode, its is a frankly ridiculous desktop environment and you should find a better one.
> 
> You are right. There is no need. An I am not required to do so. There is just the possibility to do so, and frankly I would like to. That is all. I think Kitty is great and this would be the cherry on top.
> 
> If you are not fond of implementing it yourself, never mind. However, would you be willing to accept a pull request? 

Sorry, no I am not adding desktop environment specific settings to
kitty. You can achieve the same effect by simply adding a call to xprop
in your shell rc files. kitty exports the X11 window id as the WINDOWID
environment variable to make this easy.

**Comment by 73** [comment]
I see. Thanks. That should be in the FAQ.

**Comment by kovidgoyal** [comment]
It's standard practice, for most linux terminals. I know xterm and urxvt do it, for instance.

**Comment by mkpaz** [comment]
For posterity.

```shell
force_gtk_theme() {
    local term
    local window_id=$WINDOWID
    term="$(basename "$(cat "/proc/$PPID/comm")")"
    if [ "$term" == "kitty" ] && [ -n "$window_id" ]; then
        xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT dark -id "$window_id"
    fi
}
force_gtk_theme
unset force_gtk_theme
```

**Comment by cryptoEcho** [comment]
should I use the function above in .bahrc? Or how I can achieve described goal?

**Comment by errantepiphany** [comment]
All I had to do to get a system-themed titlebar for kitty is set this in my kitty.conf:
`linux_display_server x11`
Possible values are x11, wayland, or auto (which for me had been defaulting to wayland).
