### ISSUE TITLE
Remote control ideas: wait for window to close, get window's stdout/stderr

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#2440]
I was playing with remote control to implement a script that would take stdin, run fuzzy filter on it in a new kitty window, and spit out the result. A very generic script, can be used e.g. in text editor if I want to search and open a file.

I was struggling quite a bit with the following:

After I create a new window, I would like to wait until this window is closed, and get back its stdout and stderr to the caller. 

Please let me know if I'm being silly and am missing an obvious solution to this, but I didn't find a way to do it with the current remote control API, so I basically ended up with the following hacky solution:

```sh
#!/bin/sh

tmp=$(mktemp -d)
trap 'rm -rf $tmp' EXIT

mkdir $tmp/done
cat >$tmp/stdin
kitty @ new-window --no-response --cwd "$PWD" sh -c "cat $tmp/stdin | sk -m --reverse >$tmp/stdout 2>$tmp/stderr; touch $tmp/done/1" >/dev/null 2>&1
inotifywait -q -e create "$tmp/done" >/dev/null

cat $tmp/stdout
cat $tmp/stderr >&2
```

`sk` is a fuzzy filter, can be replaced with `fzy`, `fzf` and the likes.

If the script is saved as `filter`, it can be used e.g. as `rg --files | filter`.

Is it something that you'd be interested to add in the remote control API?

**Comment by kovidgoyal** [comment]
On Tue, Mar 17, 2020 at 03:28:31PM -0700, Maxim Baz wrote:
> I was playing with remote control to implement a script that would take stdin, run fuzzy filter on it in a new kitty window, and spit out the result. A very generic script, can be used e.g. in text editor if I want to search and open a file.
> 
> I was struggling quite a bit with the following:
> 
> After I create a new window, I would like to wait until this window is closed, and get back its stdout and stderr to the caller. 

This is not in general possible, since the stdout and stderr are written
to a screen which has limited scrollback. So you can never be sure of
capturing all of it. However you may not care about that.

Also remote control has no concept of "waiting" for events. It's very
much an imperative API where it sends a command to kitty, and prints out
the response. Adding support for waiting for events would basically
imply adding support for persistent connections, which is a whole can of
worms.

Your best bet is to basically do what you did and have the
command you run signal its completion using the filesystem or some other
means. 

That said I could add a --on-exit option to the launch command that will
run an arbitrary program on exit to simplify this use case.  It could
take either an absolute path name and write the screen contents to that,
or a program to run and write the screen contents to either its STDIN or
a temp file who's path is passed on the command line.

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by maximbaz** [comment]
Taking screen contents might be a bit problematic if you want to distinguish stdout from stderr, but I can see the challenge you describe.

Speaking of waiting for window to close, does kitty create any sort of socket or temporary file for a new window? Or maybe this could be added? 

Suppose I create a window via `kitty @ new-window cat` and I get `2` returned, where `2` is the ID of the window. If I could know that for example a file `/tmp/kitty/2.socket` was created and that this file would be removed once the window is closed, I wouldn't need any `--on-exit`, because I could simply use `inotifywait -m -e delete_self /tmp/kitty/2.socket` to wait, and then run my commands on exit.

What do you think?

**Comment by kovidgoyal** [comment]
On Wed, Mar 18, 2020 at 05:32:01AM -0700, Maxim Baz wrote:
> Taking screen contents might be a bit problematic if you want to distinguish stdout from stderr, but I can see the challenge you describe.

There is no stdout and stderr. stdout and stderr are both the same file
descriptor in a terminal.

> 
> Speaking of waiting for window to close, does kitty create any sort of socket or temporary file for a new window? Or maybe this could be added? 

No, why would it? 

> 
> Suppose I create a window via `kitty @ new-window cat` and I get `2` returned, where `2` is the ID of the window. If I could know that for example a file `/tmp/kitty/2.socket` was created and that this file would be removed once the window is closed, I wouldn't need any `--on-exit`, because I could simply use `inotifywait -m -e delete_self /tmp/kitty/2.socket` to wait, and then run my commands on exit.

What's the difference? With --on-exit you can have inotify wait for the created file instead. And you get access to the output of the command.

**Comment by maximbaz** [comment]
> What's the difference? With --on-exit you can have inotify wait for the created file instead. And you get access to the output of the command.

Not much difference, only that creation and removal of the watch file becomes a user script's responsibility. But on the other hand, if kitty itself has no use for these files, then there is not much sense in creating such files.

Running inotifywait from `--on-exit` or outside as I have now (after calling `kitty @ create-window`) seems more or less identical at least for my use-case 🤔

**Comment by kovidgoyal** [comment]
On Wed, Mar 18, 2020 at 05:59:38AM -0700, Maxim Baz wrote:
> > What's the difference? With --on-exit you can have inotify wait for the created file instead. And you get access to the output of the command.
> 
> Not much difference, only that creation and removal of the watch file becomes a user script's responsibility. But on the other hand, if kitty itself has no use for these files, then there is not much sense in creating such files.

No only removal, you can watch for the create event and after that
remove it. And no it does not have any use for them.
