### ISSUE TITLE
Drag&drop URL to kitty

### ISSUE THREAD

**Issue by ondrejj** [kovidgoyal/kitty#2441]
Please, allow dropping URL from browser to kitty.

In most cases I need to download some files from browser to a remote ssh session. It's too complicated to download them to local machine and then send to server. It's easier to drag&drop them to terminal's ssh session.

In other terminals I can just type "wget " command and then drag&drop multiple URLs to this command.

It would be nice to configure, how this URL will look in terminal, for example add one space at end or send it in apostrophes or quotation marks.

Currently it's possible to copy URL from browser and paste it to kitty terminal, but doing this for multiple URLs takes too long time.

**Comment by kovidgoyal** [comment]
I dont understand. You are asking for the ability to drag and drop
selected text into the terminal? Why not just middle click?

**Comment by ondrejj** [comment]
For example sometimes I am installing packages on Fedora/CentOS from koji. I should open this url:
  https://koji.fedoraproject.org/koji/buildinfo?buildID=1478496
And download/install some packages on my system. Before I used gnome-terminal, where I was able to drag&drop these URL links to terminal, which results in pasting URLs to currently typed command (for example wget). So it's easy to copy files from web to terminal, same for installation files, images, documents, ...
In kitty I have to right-click on URL, select Copy URL link and paste.
For 5 or more files this is very complicated.

**Comment by Luflosi** [comment]
fyi this already works on macOS. ofc it would be nice if this also worked on Linux.

**Comment by kovidgoyal** [comment]
yeah you dont need to right click, etc. Just select the url and then
middle click in kitty. Much easier than drag and drop.

**Comment by ondrejj** [comment]
How I can select an URL in firefox? If I click it, then it's opened directly. Unable to select URL in browser, I only can copy address link by right-clicking and selecting copy URL ... :-(

**Comment by kovidgoyal** [comment]
How are you selecting it for drag and drop? And the usul way is to start
the lick just outside the URL and drag

**Comment by ondrejj** [comment]
URL is not displayed on page, unable to select it. Firefox on drag of a href element will drag it's URL (href link), not selected text below.
I don't understand. What do you mean with "start the lick"?
Try on my URL mentioned below. First "download" link (in src) should result in:
https://kojipkgs.fedoraproject.org//packages/firefox/74.0/9.fc31/src/firefox-74.0-9.fc31.src.rpm

**Comment by kovidgoyal** [comment]
start the click. not start the lick, typo. If the URL is not displayed then obviously it wont work.

**Comment by ondrejj** [comment]
How I can start the click but do not click?
Obviously "a href" URLs are not displayed and an text about them is displayed.
Works perfectly with all terminals except kitty. :-(
I like kitty, everything works well in it except this.

**Comment by trygveaa** [comment]
It took me a bit to understand that you mean a link where the text isn't the url itself. It would have been clearer if the link you posted here on github didn't contain the url in the text.

So, what you mean is that with [this link](https://kojipkgs.fedoraproject.org//packages/firefox/74.0/9.fc31/src/firefox-74.0-9.fc31.src.rpm), you would have to right click to be able to copy it, while if you could drag it, right clicking wouldn't be necessary.

**Comment by kovidgoyal** [comment]
well that's a bug in firefox. It is producing a drag and drop event
without the standard mime type text/uri-list, which kitty supports.
Instead it has text/x-moz-url and _NETSCAPE_URL

**Comment by trygveaa** [comment]
It happens with chrome as well for me.

**Comment by ondrejj** [comment]
Any chance to support text/x-moz-url and _NETSCAPE_URL in kitty? Looks like all other terminals supports this. Curious, that this works in macos, as mentioned in comment #3.

**Comment by Luflosi** [comment]
It works on macOS because `NSPasteboardTypeString` is accepted as a dragged type: https://github.com/kovidgoyal/kitty/blob/e827e6fa21d6f435cde32b758bce69693e823f63/glfw/cocoa_window.m#L684
I implemented this in https://github.com/kovidgoyal/kitty/pull/1921.

**Comment by ondrejj** [comment]
Your patch is working well. Thank you very much.

**Comment by ondrejj** [comment]
One more thing. As I described in issue description, it would be nice to have configurable dropping/pasting in terminal. For example drag&dropping multiple URLs serially requires to add space after each paste.

Is it possible to configure this or to write kitten to do this? For example if URL starts with http:// or https://, then an space after it is a good idea.

Some better terminals already implement this.

**Comment by kovidgoyal** [comment]
seems like a bad idea to me. How is kitty to know what trailing character
is required? Could be a quote or a space or something else, depending on
the situation. Simply type the character after dropping a URL.

**Comment by ondrejj** [comment]
Should be configurable, what character should be used. But mostly one space is better than nothing.

Yes, I can type a space manually, but then this procedure should be used:
1. drag&drop url from firefox to kitty
2. switch to kitty by clicking on it
3. press space
4. switch to firefox again

4th step can be sometimes skipped, if URL is still visible, but not always.
When a space is added, then it's only one step.

At least it's possible to extend dropping in kittens?
Can I map some commands to drop events?

**Comment by kovidgoyal** [comment]
On Thu, Mar 19, 2020 at 12:52:19AM -0700, ondrejj wrote:
> Should be configurable, what character should be used. But mostly one space is better than nothing.

And then if you are pasting into a context that requires a trailing
quote, instead of a trailing space, it means you have to erase the space.

> 
> Yes, I can type a space manually, but then this procedure should be used:
> 1. drag&drop url from firefox to kitty
> 2. switch to kitty by clicking on it

Use focus follows mouse and you dont need that.

> 3. press space
> 4. switch to firefox again

Again, use focus follows mouse.

> 4th step can be sometimes skipped, if URL is still visible, but not always.
> When a space is added, then it's only one step.

That's assuming space is the correct character.

> 
> At least it's possible to extend dropping in kittens?
> Can I map some commands to drop events?

No, it is not.

**Comment by faerot** [comment]
Would be nice if drag / drop events could be handled somehow (i.e. via kitten). I am using terminal file manager inside kitty and the need to drag/drop files happens quite often (i.e. dragging attachment to evolution mail client, etc.). Currently I am handling this via "dragon" tool, but it is not as convenient and requires extra steps.

**Comment by alvv-z** [comment]
Doesn't kitty already have a functionality to detect URLs? You could just make it configurable which character to add after a URL is dragged into the window (maybe only if there are no characters succeeding the cursor).
