### ISSUE TITLE
Text selection highlight doesn't update when scrolling down

### ISSUE THREAD

**Issue by Xyene** [kovidgoyal/kitty#2442]
When scrolling down while selecting text through several screen-fulls, the highlighted region doesn't update.

![image](https://user-images.githubusercontent.com/1403503/76932189-b8b37680-68c0-11ea-889f-0cdcf0211f9f.png)

([Video.](https://drive.google.com/file/d/1kieaZVgL21Y5PMgdriSJnKD3Dyk8UcYt/view?usp=sharing))

I can reproduce this on latest master, under Wayland (sway). I'm happy to provide any other information that may be useful.

**Comment by kovidgoyal** [comment]
It's just temporary, while scrolling, as soon as you stop, it will re-adjust. Obv would be nicer if it adjusted on the fly.

**Comment by Xyene** [comment]
Thanks for the quick fix, it's nicer now :smile: 

I think there's just one visual glitch left: if the selection starts somewhere in the middle of a line, the part left of the start is never shown as selected after scrolling past its initial position.

![image](https://user-images.githubusercontent.com/1403503/76969441-c12ba180-6900-11ea-9ea2-3e562851d376.png)

The unselected top-left-corner updates as I scroll up after finishing my selection.

![image](https://user-images.githubusercontent.com/1403503/76969517-dc96ac80-6900-11ea-9b18-967d30300f3d.png)

This seems to persist even after scrolling has completed.

**Comment by kovidgoyal** [comment]
That should also be fixed in master.
