### ISSUE TITLE
Shift + Space doesn't work right as in other terminals

### ISSUE THREAD

**Issue by Godnyx** [kovidgoyal/kitty#2444]
Hi! I don't know of that's an error or if there is something be default that I have to configure (I have read the docs but I haven't found something). I use a custom keyboard layout and I have binded Shift + Space to Backspace. That means that that when I press Space, it will generate a space but with I hold down Shift and then press Space, it will generate Backspace (aka delete-character). In any other terminal or app this works fine. But with Kitty it doesn't. Space and Shift + Space both generate a space. I don't know what's going on but it is really wired!

I'm on Manjaro Linux and I have changed my keyboard layout through XKB itself and not with any 3rd party software if that helps.

**Comment by kovidgoyal** [comment]
There are half a dozen ways you can remap keys on X11 some of them will
work and some will not. Your best bet is to simply remap it in
kitty.conf using send_text

map shift+space send_text all \x7f


And you can use --debug-keyboard to see what key events kitty is
actually seeing.

**Comment by rempas** [comment]
> There are half a dozen ways you can remap keys on X11 some of them will work and some will not. Your best bet is to simply remap it in kitty.conf using send_text
> 
> map shift+space send_text all \x7f
> 
> And you can use --debug-keyboard to see what key events kitty is actually seeing.

Hi! I probably totally missed that and that's why I didn't replied to thank you! All this time I thought I couldn't used kitty but, as wezterm stopped working with hyprland, I came back to check and found you replied so, I wanted to thank you! It works amazing!
