### ISSUE TITLE
High "latency" of right-click selections compared to xterm

### ISSUE THREAD

**Issue by Xyene** [kovidgoyal/kitty#2445]
Hi,

I've been trying to move to `kitty` from `xterm`, since `xterm` has some graphical glitches running on Wayland whereas `kitty` "just works" -- thanks a lot for that.

One thing I noticed during use is that making selections via left-click felt much more sluggish compared to `xterm`. It seems `xterm` updates the selection on left-click press, whereas `kitty` only on release, so there's a visual delay lower bounded by the release time.

Apart from reduced visual delay, on-press has the ergonomic advantage of being able to finely select the ending character by left-dragging, as opposed to repeatedly clicking.

It would be nice if `kitty` had this behaviour, or at least an option to enable it :)

**Comment by kovidgoyal** [comment]
I dont follow. Kitty selections most definitely happen on mouse down.
And in fact you cannot extend them by left clicking at all, only right
clicking.

**Comment by Xyene** [comment]
Sorry, that's my mistake -- what I meant was `s/left/right/g`. If you try to extend by right click, the extension happens when you release the mouse button, and doesn't update when dragging the right button (I imagine these would be repeat events?)

**Comment by Xyene** [comment]
That's works well, thanks a lot for your very quick patches @kovidgoyal!

**Comment by kovidgoyal** [comment]
you're welcome :)
