### ISSUE TITLE
Visual artifacts during startup

### ISSUE THREAD

**Issue by Xyene** [kovidgoyal/kitty#2447]
When opening a new `kitty` window, there's a brief (100~200ms period) where the `kitty` window is visible, but has visible artifacts. I was able to capture three stages by recording my screen and then sequencing with `ffmpeg`:

1. Terminal window is created (note screenshot is the size of the terminal), but only a black subrectangle is rendered; the rest of the terminal background is totally transparent. The picture visible is my desktop background.

![image](https://user-images.githubusercontent.com/1403503/76991267-ab79a480-691f-11ea-8bf5-04726777160e.png)

2. Text appears, but is vertically-centered and "compressed".

![image](https://user-images.githubusercontent.com/1403503/76991381-e2e85100-691f-11ea-9719-efc293118045.png)

3. Text is finally positioned and sized correctly.

![image](https://user-images.githubusercontent.com/1403503/76991451-fbf10200-691f-11ea-92db-c29fc1839239.png)

This issue is particularly noticeable with a tiling window manager, since opening a new terminal is a frequent action. I'm happy to provide any other information that might be useful.

**Comment by kovidgoyal** [comment]
I'm afraid I really dont care about this, if you do patches are welcome.
