### ISSUE TITLE
freeze with certain unicode 13.0.0 characters

### ISSUE THREAD

**Issue by devsnek** [kovidgoyal/kitty#2448]
Certain characters new in unicode 13.0.0 (using `cat`, etc) cause kitty 0.16.0 to freeze

As a test, try `cat`ing this file: https://github.com/tc39/test262/blob/master/test/language/identifiers/start-unicode-13.0.0.js

**Comment by kovidgoyal** [comment]
Works fine for me. I highly doubt it is kitty that is freezing, but your
shell. Press ctrl+shift+n to open a new kitty window to confirm.

**Comment by devsnek** [comment]
@kovidgoyal ctrl+shift+n doesn't do anything

**Comment by kovidgoyal** [comment]
I still cannot reproduce. catting that file is instant, scrolling up to view the catted contents is a bit slow in the region with the suspect characters, but that is all.

**Comment by kovidgoyal** [comment]
And the scrolling is slow because of all the characters that have no fonts to display them, which means that for every such character, kitty has to query the OS to find a font, which is slow
