### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by ttyz** [kovidgoyal/kitty#2452]
Hi, I do enjoy kitty as my terminal, and the only thing I am missing is a simple status bar that I can set to display some text via remote control.

I think having something like that on the right-hand side of the tab bar would be very nice for displaying current working directory, git branch, etc.

In my opinion, this should be as simple as possible and just display user-provided text

Panel kitten does not fill the gap in this case, because it takes extra space on the screen.

If this can be achieved by a new kitten somehow, I am probably completely missing it

**Comment by kovidgoyal** [comment]
dup of #2391
