### ISSUE TITLE
On Wayland, mouse scroll resolution is controlled by `touch_scroll_multiplier`

### ISSUE THREAD

**Issue by Xyene** [kovidgoyal/kitty#2456]
Kitty's config has two options for controlling scroll resolution:

* **`wheel_scroll_multiplier`**
    > Modify the amount scrolled by the mouse wheel. Note this is only used for low
precision scrolling devices, not for high precision scrolling on platforms such
as macOS and Wayland. Use negative numbers to change scroll direction.

* **`touch_scroll_multiplier`**
    > Modify the amount scrolled by a touchpad. Note this is only used for high
precision scrolling devices on platforms such as macOS and Wayland.
Use negative numbers to change scroll direction.

On Wayland, though, it seems the correct field to modify is `touch_scroll_multiplier`, even for mice. This is somewhat confusing, but I'm not sure whether this is a bug, or whether the wording of the documentation is meant to suggest that _all_ scrolling devices on Wayland are high-precision, such that even mice should be using `touch_scroll_multiplier`. (Or whether I happen to have a "high precision" mouse.)

For reference, the events received by kitty on my machine / with my mouse are of the form `wl_pointer@19.axis(38755715, 0, 15.000000)`.

`udev` appears to correctly identify my mouse as a mouse (`ID_INPUT_MOUSE=1`), rather than a touchpad.

```
$ udevadm info /dev/input/event9
P: /devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:05:00.3/usb3/3-3/3-3:1.0/0003:046D:C083.0005/input/input9/event9
N: input/event9
L: 0
S: input/by-path/pci-0000:05:00.3-usb-0:3:1.0-event-mouse
S: input/by-id/usb-Logitech_G403_Prodigy_Gaming_Mouse_0B9038633232-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:05:00.3/usb3/3-3/3-3:1.0/0003:046D:C083.0005/input/input9/event9
E: DEVNAME=/dev/input/event9
E: MAJOR=13
E: MINOR=73
E: SUBSYSTEM=input
E: USEC_INITIALIZED=4975518
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_MODEL=G403_Prodigy_Gaming_Mouse
E: ID_MODEL_ENC=G403\x20Prodigy\x20Gaming\x20Mouse
E: ID_MODEL_ID=c083
E: ID_REVISION=0801
E: ID_SERIAL=Logitech_G403_Prodigy_Gaming_Mouse_0B9038633232
E: ID_SERIAL_SHORT=0B9038633232
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030102:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:05:00.3-usb-0:3:1.0
E: ID_PATH_TAG=pci-0000_05_00_3-usb-0_3_1_0
E: LIBINPUT_DEVICE_GROUP=3/46d/c083:usb-0000:05:00.3-3
E: DEVLINKS=/dev/input/by-path/pci-0000:05:00.3-usb-0:3:1.0-event-mouse /dev/input/by-id/usb-Logitech_G403_Prodigy_Gaming_Mouse_0B9038633232-event-mouse
```

**Comment by kovidgoyal** [comment]
Yes, the first setting is for low precision devices, the second for high
precision ones. If all mice on wayland are high precision, then the
second one will apply. I have no idea if that is actually the case or
not.
