### ISSUE TITLE
Mouse selection unavailable on 0.16.0

### ISSUE THREAD

**Issue by alephnull** [kovidgoyal/kitty#2458]
I am sure this was working. My workaround to get access to the mouse selection is to have
```
copy_on_select clipboard
```
And use *kitty_mod*+{c,v}. I am using Wayland on Ubuntu Eoan.

It appears that the problem is that the selection is not happening as middle-click/shift+ins does not seem to be pasting anything in Emacs or chromium.

**Comment by kovidgoyal** [comment]
Many wayland compositors do not support middle click copy/paste. It was
left out of the wayland protocol. Use the copy to clicpboard on middle
click setting in kitty.conf.

**Comment by alephnull** [comment]
So it appears to be part of the protocol now?
https://github.com/wayland-project/wayland-protocols/blob/master/unstable/primary-selection/primary-selection-unstable-v1.xml
And the GNOME guys [are supporting it](https://wiki.gnome.org/Initiatives/Wayland/PrimarySelection)?

I guess I could learn to use just one clipboard, like some sort of animal.

**Comment by kovidgoyal** [comment]
And it works fine on compositors that support it such as sway. But yeah
if you want advanced stuff like copy on select, your best bet is X11

**Comment by alephnull** [comment]
Yes, can confirm it works fine on sway. I think the problem is that the name of the buffer changed (in the protocol or in the GNOME implementation) and sway wrote a little compatibility code. I'm still trying to figure out which link in this chain is broken.
