### ISSUE TITLE
OSX - Fullscreen kitty is minimized when focusing on another app

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#246]
Steps to reproduce:
1. Open kitty
2. Go to fullscreen with Ctrl+Shift+F11 command
3. Cmd+Tab and navigate to a different app

I've tested and the issue shows up on the 2 latest OSX releases (0.6.0 and 0.5.1).

**Comment by kovidgoyal** [comment]
Isn't that how full screen apps are supposed to work on OS X? In any case, kitty itself does not contain any code to manage fullscreen ness. That is the province of glfw, the windowing toolkit kitty uses.

**Comment by kovidgoyal** [comment]
no followup

**Comment by mihaicristiantanase** [comment]
Sorry, I wasn't online for a few days :)

"Isn't that how full screen apps are supposed to work on OS X"
 - I've been developing on OSX for quite some time and, from my experience, kitty is the only app that has this behavior

I've done some research on GLFW and found this on http://www.glfw.org/docs/latest/window_guide.html:
> By default, the original video mode of the monitor will be restored and the window iconified if it loses input focus, to allow the user to switch back to the desktop. This behavior can be disabled with the GLFW_AUTO_ICONIFY window hint, for example if you wish to simultaneously cover multiple windows with full screen windows.

Unfortunately, I could not test that flag on my machine due to a compile error when running:
> python3 setup.py build

> CC: clang (4, 2)
> harfbuzz >= 1.5 is required, found version: 1.4.5

I've also rechecked on the latest release (0.6.1) and the issue still shows up.

**Comment by kovidgoyal** [comment]
I just tried it with iterm, with the following steps:

1) Click the fullscreen toggle in the iterm title bar
2) cmd+tab to a previously opened finder window

The iterm fullscreen window disappears and I can see the finder window + desktop instead.

I dont see how what you are claiming is possible. In fullscreen mode, the window manager is disabled and the application takes over control of drawing the entire screen. This avoids a round trip through the window manager and is a performance enhancement originally intended for fullscreen games. There is not way to have both a fullscreen window and other windows drawn tot he screen at the same time. 

Maybe you mean a maximized window instead?

**Comment by kovidgoyal** [comment]
And you just need to do brew update harfbuzz (assuming you previously installed harfbuzz using brew)

**Comment by mihaicristiantanase** [comment]
"Click the fullscreen toggle in the iterm title bar"
- this is not correct; as I mentioned in the bug description, the command I'm using to go to fullscreen is Ctrl+Shift+F11

**Comment by mihaicristiantanase** [comment]
"And you just need to do brew update harfbuzz (assuming you previously installed harfbuzz using brew)"
- I have mannaged to do a succesfull build, but I'm having trouble finding *kitty.app* (I've tried **python3 setup.py osx-bundle** and **python3 setup.py build**)

**Comment by kovidgoyal** [comment]
You run kitty from source as

python3 .

I'm not an OS X user but from your screen shot Ctrl+Shift+F11 is not a real fullscreen. I have no idea what it is, the dock/bar hide themselves and make then maximize the window?

**Comment by mihaicristiantanase** [comment]
The Ctrl+Shift+F11 is the mapping I found in kitty.conf:
> map ctrl+shift+f11      toggle_fullscreen

The effect that I'm looking for is:
1. the title bar is hidden
2. there is no space between the margins of the app and the edges of the screen
3. the app stays in the same workspace

As a workaround, for now I'm using
> macos_hide_titlebar yes

and maximizing the window
which solves (1) and (3), but has noticeable space between the bottom margin of the app and the bottom edge of the screen

I'll add the flag and I'll be back with a followup, and maybe with a pull-request if that solves the problem.

**Comment by mihaicristiantanase** [comment]
As a followup, I've tested the flag with
> glfwWindowHint(GLFW_AUTO_ICONIFY, false);

but than the app becomes topmost and I could not switch to a different app without manually exiting fullscreen.

From what I see, this is an intended behavior of GLFW (http://discourse.glfw.org/t/creating-windowed-fullscreen/825/3) so, unfortunately, it's either impossible to mimic the behavior I'm used to in iTerm or I need to do more investigation of GLFW.

In any case, for now, this issue will remain closed.

**Comment by kovidgoyal** [comment]
Well kitty ships with its own, modified copy of glfw, so I am willing to entertain a patch to that glfw to fullscreen behavior similar to iTerm. See my glfw fork (you will probably need to make a simple patch to cocoa_window.m around line 330).

**Comment by kovidgoyal** [comment]
You can test the change by modifying glfw/cocoa_window.m and if it works, send a PR to my glfw fork.

**Comment by mihaicristiantanase** [comment]
Thanks for the suggestion! I'll let you know how it goes.

**Comment by mihaicristiantanase** [comment]
I've done more digging on this issue and here's what I found:
- trying to mess with the GLFW_AUTO_ICONIFY flag or the logic behind it (in
  cocoa_window.m) produces one of the two effects: the app is either minimized
  when navigating to a different app, or the app is topmost all the time and
  you cannot navigate to other apps unless you exit fullscreen mode;
- the bottom gap (approx. 4px) shows up when the Dock is in autohide mode and
  the app is maximized;
- from I've seen this is actually intented by Apple, and the reason would be
  that if the user goes with the mouse over that gap, than the Dock will
  become visible again - my opinion is that this is actually a bug from
  Apple's development team;
- iTerm does not do fullscreen when the user presses CMD+ENTER, but it (1)
  hides the title bar, (2) maximizes the app, and (3) adjusts the width and
  the height of the app (probably a hack) to cover the gap;

The setup that I'm using at the moment which works for me is:
- use a fork of Spectacle app (window manipulation),
  https://github.com/mihaicristiantanase/spectacle, which adjusts the size of
  the app (when maximized) to cover the gap;
- set "macos_hide_titlebar" to "yes";
- maximize kitty via Spectacle;

So, a possible fix would be to have a keyboard shortcut (only for OSX) which
toggles between the current window configuration (title bar visibility, size)
and the "fullscreen" configuration (no title bar, size set to size of the
screen + the gap adjustment).
But I'm not sure if this is something that should be implemented in Kitty.
What do you think?

**Comment by kovidgoyal** [comment]
IMO this kind of thing does not really belong in kitty. It's fragile and platform specific. Apple should implement an API for maximized but not fullscreen apps otherwise trying to fake it is just going against intended usage of the platform, which I dont like to do.
