### ISSUE TITLE
Focus prev/next OS window keyboard shortcuts

### ISSUE THREAD

**Issue by nkhlmn** [kovidgoyal/kitty#2461]
Would it be possible to add shortcuts for these, assuming there isn't already some other way to do that?

**Comment by kovidgoyal** [comment]
There already are such shortcuts. You can focus next/prev and
neighboring windows and move window around. https://sw.kovidgoyal.net/kitty/#tabs-and-windows

**Comment by nkhlmn** [comment]
Don't those existing shortcuts only work for windows within the same OS window?

**Comment by kovidgoyal** [comment]
yes, you use your window manager's controls for OS Windows. That's the
whole point of using OS Windows, at all.

**Comment by nkhlmn** [comment]
My thinking is that since you can only have a single font size per OS window, a workaround would be to use OS windows instead of regular windows for splits. In that situation it would be convenient to replace the default `kitty_mod+[`/`]` keys within your `kitty.conf` and not have to configure things separately depending on what OS you're on.

But fair enough if you don't think that's warranted or is too much of a hassle.

**Comment by kovidgoyal** [comment]
If you want to do splits using OS Windows, you are pretty much going to
have to configure your window manager for window control anyway, and use
a tiling window manager. At which point there is need to duplicate the
window managers functionality inside kitty.

**Comment by nkhlmn** [comment]
For people that switch between macos and linux a fair amount it would be nice to be able to just copy a kitty.conf file and have things working the same without having to fiddle with OS specific settings. That was my main motivation for switching from iterm to kitty anyway. I like to keep OS level customization as default as possible.

I'm not sure what you mean by requiring a tiling window manager. I personally use [phoenix](https://github.com/kasper/phoenix) on macos to arrange windows, though it wouldn't be much harder to just setup a separate desktop with a few different OS windows and leave it like that, which is what I do when i'm on linux.

**Comment by kovidgoyal** [comment]
On Mon, Mar 23, 2020 at 09:31:10PM -0700, nkhlmn wrote:
> For people that switch between macos and linux a fair amount it would be nice to be able to just copy a kitty.conf file and have things working the same without having to fiddle with OS specific settings. That was my main motivation for switching from iterm to kitty anyway. I like to keep OS level customization as default as possible.

You are talking about people that work on both, want to use OS
Windows rather than kitty windows and dont already have proper window
manager setups on their systems. Doesn't seem a demographic worth
targeting, at least for me. That said, I wont refuse a patch to add 
actions for switching focus between OS Windows. Note that some
environments, such as Wayland, dont even allow applications to switch
focus between OS windows.

> 
> I'm not sure what you mean by requiring a tiling window manager. I personally use [phoenix](https://github.com/kasper/phoenix) on macos to arrange windows, though it wouldn't be much harder to just setup a separate desktop with a few different OS windows and leave it like that, which is what I do when i'm on linux.

You talked about splitting windows, that is typically done with a tiling
WM. I suggest you try one out, you will find it is a great productivity
enhancer.
