### ISSUE TITLE
Very dim colours in 0.17.0

### ISSUE THREAD

**Issue by lithammer** [kovidgoyal/kitty#2462]
After upgrading to v0.17.0 on macOS Catalina 10.15.3, the colours are super dim.

v0.16.0

<img width="752" alt="Screenshot 2020-03-24 at 07 49 54" src="https://user-images.githubusercontent.com/177685/77396514-30434300-6da4-11ea-9ad9-5a3276a3e5ad.png">

v0.17.0

<img width="752" alt="Screenshot 2020-03-24 at 07 48 24" src="https://user-images.githubusercontent.com/177685/77396528-36d1ba80-6da4-11ea-90c8-a937f6a8ee4c.png">

**Comment by lithammer** [comment]
After bisecting a bit, it seems like it's related to the `font_family` setting. It's mostly Iosevka that looks this bad, the default `monospace` looks fine for example.

**Comment by kovidgoyal** [comment]
I cant think of any changes in 0.17 that affect font rendering. Can you bisect to find the problem commit?

**Comment by lithammer** [comment]
I tried to bisect with `git bisect start v0.17.0 v0.16.0 --`. I had to skip a bunch of commits that either didn't build, did't start start or didn't use the correct font (used a fallback font?). None of the commits look very suspicious though 🤔 

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> ac2c21e046bb0622880571360cb6a7fd5eb6ddf2
> c817ba9eaea52bc813cfbd38e0c0073b92c65b50
> 3c2f3ecd8e3864731040d3e01cad030dc5b2932e
> 92827ae647e5eede7f8ff499d178e481274a37b4
> 5bdb405635fe7f8be528df119d88fb5936264860
> 7298de646a3f1a520afb029941cd039fb33dae75
> 7d690bbad2fdb904d9407922e902b144a3bcc54b
> 9beae321d7c999a19975e2bf4378628c8f9bff86
> 353db678a2836335c2674c9ab1d392532959c70e
> abff2292c16724309d1533092ab6bc03d3bb0bdf
> 8ae110691eb885651e7d41a40725bc8ddc186609
> 9b973ef99c54eb87c5a5a00cc6cb0050989f7e93
> 308d171dae7712a37a7a73ba97bdec442fac02e1
> f74fb846e544298ddbad03684a26cad5f77a3d2d
> d8f214a267241ebf1d3c5b5daedbc910a31863b1
> We cannot bisect more!

Here's the complete log:

> \# bad: [93271b93e68b8875878c87b5e0e4572e23bd369a] version 0.17.0
> \# good: [644ee646a2dc3f70f648c59869e8d12edadfaf78] version 0.16.0
> git bisect start 'v0.17.0' 'v0.16.0' '--'
> \# skip: [e03aabd97218d4ca5e5cc7acfa15267e144d107f] Some consting
> git bisect skip e03aabd97218d4ca5e5cc7acfa15267e144d107f
> \# skip: [5bbc15583eb9ca6e68303bf742682b915aa0d2f0] Non-scrolling based selection tests all pass
> git bisect skip 5bbc15583eb9ca6e68303bf742682b915aa0d2f0
> \# good: [f7299853464c6b190cfc0c55149c7b47c6962d0c] More typing work
> git bisect good f7299853464c6b190cfc0c55149c7b47c6962d0c
> \# bad: [b27f6d595743546365f3e59f5b647769ae4c3185] more typing work
> git bisect bad b27f6d595743546365f3e59f5b647769ae4c3185
> \# skip: [3c2f3ecd8e3864731040d3e01cad030dc5b2932e] Fix #2420
> git bisect skip 3c2f3ecd8e3864731040d3e01cad030dc5b2932e
> \# skip: [ac2c21e046bb0622880571360cb6a7fd5eb6ddf2] more typing work
> git bisect skip ac2c21e046bb0622880571360cb6a7fd5eb6ddf2
> \# good: [645890ccc8b63b0b3eea3a0de2c1c88003410050] Make the set of URL prefixes that are recognized while hovering with the mouse configurable
> git bisect good 645890ccc8b63b0b3eea3a0de2c1c88003410050
> \# bad: [d8f214a267241ebf1d3c5b5daedbc910a31863b1] oops
> git bisect bad d8f214a267241ebf1d3c5b5daedbc910a31863b1
> \# skip: [92827ae647e5eede7f8ff499d178e481274a37b4] More typing work
> git bisect skip 92827ae647e5eede7f8ff499d178e481274a37b4
> \# skip: [c817ba9eaea52bc813cfbd38e0c0073b92c65b50] more typing work
> git bisect skip c817ba9eaea52bc813cfbd38e0c0073b92c65b50
> \# skip: [308d171dae7712a37a7a73ba97bdec442fac02e1] More typing work
> git bisect skip 308d171dae7712a37a7a73ba97bdec442fac02e1
> \# skip: [5bdb405635fe7f8be528df119d88fb5936264860] More typing work
> git bisect skip 5bdb405635fe7f8be528df119d88fb5936264860
> \# skip: [abff2292c16724309d1533092ab6bc03d3bb0bdf] Workaround for sphinx type info being available magically on the CI server
> git bisect skip abff2292c16724309d1533092ab6bc03d3bb0bdf
> \# skip: [9beae321d7c999a19975e2bf4378628c8f9bff86] More typing work
> git bisect skip 9beae321d7c999a19975e2bf4378628c8f9bff86
> \# skip: [9b973ef99c54eb87c5a5a00cc6cb0050989f7e93] More typing work
> git bisect skip 9b973ef99c54eb87c5a5a00cc6cb0050989f7e93
> \# skip: [353db678a2836335c2674c9ab1d392532959c70e] Add typing to box_drawing
> git bisect skip 353db678a2836335c2674c9ab1d392532959c70e
> \# skip: [8ae110691eb885651e7d41a40725bc8ddc186609] More typing work
> git bisect skip 8ae110691eb885651e7d41a40725bc8ddc186609
> \# skip: [7298de646a3f1a520afb029941cd039fb33dae75] more typing work
> git bisect skip 7298de646a3f1a520afb029941cd039fb33dae75
> \# good: [7057bc663ec9837e7b0defd5e8638c6120b6b2c0] Implement proper editor integration for mypy
> git bisect good 7057bc663ec9837e7b0defd5e8638c6120b6b2c0
> \# skip: [7d690bbad2fdb904d9407922e902b144a3bcc54b] Run mypy on CI
> git bisect skip 7d690bbad2fdb904d9407922e902b144a3bcc54b
> \# skip: [f74fb846e544298ddbad03684a26cad5f77a3d2d] Fix #2421
> git bisect skip f74fb846e544298ddbad03684a26cad5f77a3d2d
> \# only skipped commits left to test
> \# possible first bad commit: [d8f214a267241ebf1d3c5b5daedbc910a31863b1] oops
> \# possible first bad commit: [f74fb846e544298ddbad03684a26cad5f77a3d2d] Fix #2421
> \# possible first bad commit: [8ae110691eb885651e7d41a40725bc8ddc186609] More typing work
> \# possible first bad commit: [abff2292c16724309d1533092ab6bc03d3bb0bdf] Workaround for sphinx type info being available magically on the CI server
> \# possible first bad commit: [7d690bbad2fdb904d9407922e902b144a3bcc54b] Run mypy on CI
> \# possible first bad commit: [7298de646a3f1a520afb029941cd039fb33dae75] more typing work
> \# possible first bad commit: [3c2f3ecd8e3864731040d3e01cad030dc5b2932e] Fix #2420
> \# possible first bad commit: [ac2c21e046bb0622880571360cb6a7fd5eb6ddf2] more typing work
> \# possible first bad commit: [c817ba9eaea52bc813cfbd38e0c0073b92c65b50] more typing work
> \# possible first bad commit: [92827ae647e5eede7f8ff499d178e481274a37b4] More typing work
> \# possible first bad commit: [5bdb405635fe7f8be528df119d88fb5936264860] More typing work
> \# possible first bad commit: [9beae321d7c999a19975e2bf4378628c8f9bff86] More typing work
> \# possible first bad commit: [353db678a2836335c2674c9ab1d392532959c70e] Add typing to box_drawing
> \# possible first bad commit: [9b973ef99c54eb87c5a5a00cc6cb0050989f7e93] More typing work
> \# possible first bad commit: [308d171dae7712a37a7a73ba97bdec442fac02e1] More typing work

**Comment by kovidgoyal** [comment]
Which Iosevka variant are you using? I will try to reproduce.

**Comment by lithammer** [comment]
Thanks. I'm currently [02-iosevka-fixed-3.0.0-rc.4.zip](https://github.com/be5invis/Iosevka/releases/download/v3.0.0-rc.4/02-iosevka-fixed-3.0.0-rc.4.zip). I know it's a release candidate, but I could also reproduce with the stable [02-iosevka-term-2.3.3.zip](https://github.com/be5invis/Iosevka/releases/download/v2.3.3/02-iosevka-term-2.3.3.zip) release. It's slightly better though.

Note that in the release candidate `iosevka-term` was renamed to `iosevka-fixed` and a new package `iosevka-term` was introduced that contains ligatures.

**Comment by kovidgoyal** [comment]
Which variant are you using? As in what is the value of font_family in kitty.conf and what does kitty --debug-font-fallback say about which font is selected? On linux with

kitty --config NONE -o font_family=Iosevka\ Fixed

it works fine. Dont have access to macOS at the moment to test there

**Comment by lithammer** [comment]
> Which variant are you using? As in what is the value of font_family in kitty.conf

```
font_family      Iosevka Fixed
bold_font        auto
italic_font      auto
bold_italic_font auto
```

> what does kitty --debug-font-fallback say about which font is selected?

v0.16.0

```
[084 13:19:57.583526] Preloaded font faces:
[084 13:19:57.583560] normal face: {'monospace': True, 'bold': False, 'italic': False, 'family': 'Iosevka Fixed'}
[084 13:19:57.583576] bold face: {'monospace': True, 'bold': True, 'italic': False, 'family': 'Iosevka Fixed'}
[084 13:19:57.583588] italic face: {'monospace': True, 'bold': False, 'italic': True, 'family': 'IosevkaFixed'}
[084 13:19:57.583601] bi face: {'monospace': True, 'bold': True, 'italic': True, 'family': 'Iosevka Fixed'}
```

v0.17.0
```
./kitty --config NONE -o font_family=Iosevka\ Fixed --debug-font-fallback
[084 13:17:47.255557] Preloaded font faces:
[084 13:17:47.255620] normal face: /Users/peter/Library/Fonts/iosevka-fixed-extendedthin.ttf
[084 13:17:47.255645] bold face: /Users/peter/Library/Fonts/iosevka-fixed-extendedbold.ttf
[084 13:17:47.255666] italic face: /Users/peter/Library/Fonts/iosevka-fixed-oblique.ttf
[084 13:17:47.255686] bi face: /Users/peter/Library/Fonts/iosevka-fixed-extraboldoblique.ttf
```

It seems like it's picking up the 'thin' variant instead of 'regular'.

**Comment by kovidgoyal** [comment]
Should be fine in master.
