### ISSUE TITLE
Build error if compile with --debug

### ISSUE THREAD

**Issue by tim77** [kovidgoyal/kitty#2468]
After trying this patch https://github.com/kovidgoyal/kitty/commit/76a6bba64310024c2780ff26e5bbcd3f8b520b38 i struggle with another issue when building with `--debug`:

```
/usr/bin/python3 setup.py linux-package --libdir-name=lib64 --prefix=/builddir/build/BUILDROOT/kitty-0.17.0-1.fc33.x86_64/usr --update-check-interval=0 --debug
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-redhat-linux/10/include/stdint.h:9,
                 from glfw/../kitty/monotonic.h:11,
                 from glfw/internal.h:30,
                 from glfw/x11_window.c:31:
/usr/include/features.h:397:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
CC: gcc (0, 0)
```

- [Full build log](https://paste.centos.org/view/raw/4faaa41f)
- GCC: `gcc-10.0.1-0.9.fc32`

**Comment by kovidgoyal** [comment]
That looks like a bug in gcc 10 to me. Its complaining about the use of
FORTIFY_SOURCE saying it requires an -O optimization option, but the -g3
option has been passed which is sufficient for FORTIFY_SOURCE on other
gcc versions.

**Comment by kovidgoyal** [comment]
Actually the problem is tne detected ccver in you build environment is (0, 0).  What is the output of cc -dumpversion on your system?

**Comment by tim77** [comment]
> What is the output of cc -dumpversion on your system?
```
cc -dumpversion

10
```

**Comment by tim77** [comment]
@kovidgoyal thanks a lot! https://github.com/kovidgoyal/kitty/commit/0547102bdd6ce3b71cf53f2cb75b2f85692789f5 fixed this issue.
