### ISSUE TITLE
Some tests not passed on aarch64 and ppc64le arches

### ISSUE THREAD

**Issue by tim77** [kovidgoyal/kitty#2469]
Tests not passed on `aarch64` and `ppc64le` arches. Latest kitty `0.17.0` with https://github.com/kovidgoyal/kitty/commit/76a6bba64310024c2780ff26e5bbcd3f8b520b38 and https://github.com/kovidgoyal/kitty/commit/0547102bdd6ce3b71cf53f2cb75b2f85692789f5. On `armv7hl`, `i686` and `86_64` all tests passed.

Full build log for:

- [aarch64](https://kojipkgs.fedoraproject.org//work/tasks/9186/42739186/build.log)
- [ppc64le](https://kojipkgs.fedoraproject.org//work/tasks/9187/42739187/build.log)

[Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=42739173).

```
test_box_drawing (kitty_tests.fonts.Rendering) ... Traceback (most recent call last):
  File "/builddir/build/BUILD/kitty-0.17.0/kitty/fonts/render.py", line 284, in prerender_function
    cells = f(1), f(2), f(3), f(0, True), f(missing=True), c(1), c(2), c(3)
  File "/builddir/build/BUILD/kitty-0.17.0/kitty/fonts/render.py", line 256, in render_cursor
    horz('bottom', cursor_underline_thickness)
  File "/builddir/build/BUILD/kitty-0.17.0/kitty/fonts/render.py", line 246, in horz
    height = max(1, min(int(round(height_pt * dpi_y / 72.0)), cell_height))
ValueError: cannot convert float NaN to integer
[084 13:19:18.725580] Failed to pre-render cells
```

Hope this is helpful bug report. But not really a big issue here, JFYI. This is not primary arches so just close it if you wish. Thanks.

**Comment by kovidgoyal** [comment]
This should already be fixed in master
