### ISSUE TITLE
0.17.1 won't compile on ppc64le arch

### ISSUE THREAD

**Issue by tim77** [kovidgoyal/kitty#2471]
Some new regressions again, now error during build on `ppc64le` arch. Previously it compiles fine.

- [Full build log](https://kojipkgs.fedoraproject.org//work/tasks/617/42740617/build.log)
- [Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=42740602)

Once again feel free to close this issue if you consider this arch not important. Thanks.

**Comment by kovidgoyal** [comment]
I dont see any actual error there, looks like the compiler is crashing.

**Comment by sharkcz** [comment]
If I see right, then the kitty buildsystem injects "-march=native", which works only on some arches.

**Comment by tim77** [comment]
> If I see right, then the kitty buildsystem injects "-march=native", which works only on some arches.

I disabled already hardcoded `native_optimizations=False` but yes, on this arch new GCC 10 with this hardcoded `-march=native` now won't compile. Kitty was never compiled in Fedora with `native` anyway.

**Comment by kovidgoyal** [comment]
But that has not changed between 0.70.0 and 0.17.1 and native
optimizations are only enabled if building for local use, not when using
linux-package to build packages.

**Comment by tim77** [comment]
Yep. Something with new GCC 10 probably. Don't know what a proper place for reporting this bug, RHBZ or GCC bug tracker...

**Comment by sharkcz** [comment]
The sed command in th spec file doesn't work any more, nothing related to gcc10.

**Comment by tim77** [comment]
> The sed command in the spec file doesn't work any more, nothing related to gcc10.

Wow, this is true. Thanks for catching this. In previous 0.16.0 there was an option for this in `setup.py`.

**Comment by kovidgoyal** [comment]
why are you guys sedding stuff? If you want an option to turn off/on things just ask.

**Comment by tim77** [comment]
> why are you guys sedding stuff? If you want an option to turn off/on things just ask.

Yeah, would be nice to respect default compiler flags during build in general. Should i wait for fix or maybe we can workaround this somehow for now?

**Comment by kovidgoyal** [comment]
CFLAGS from the environment is already uses, see line 281 of setup.py

**Comment by tim77** [comment]
OK, i dropped sedding build flags, but for `ppc64le` issue the same. [Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=42741581) and [build log](https://kojipkgs.fedoraproject.org//work/tasks/1587/42741587/build.log).

**Comment by kovidgoyal** [comment]
Why are you doing setup.py build? I am assuming you want to generate a linux package?? If so

use ./setup.py linux-package

and see https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers

**Comment by kovidgoyal** [comment]
This will automatically not use -march=mative

**Comment by tim77** [comment]
> Why are you doing setup.py build? I am assuming you want to generate a linux package?? If so
> 
> use ./setup.py linux-package
> 
> and see https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers

I realized this just now as well. This is left from previous maintainer. Thanks a lot for help!
