### ISSUE TITLE
Have one terminal screen clear the output of another

### ISSUE THREAD

**Issue by bhougland18** [kovidgoyal/kitty#2472]
Hello,

I have read the documentation multiple times and can't figure out how to have an editor (kakoune) clear the repl running in another kitty terminal running on the same instance.  I can do this manually by using the keyboard command Ctl+Shift+delete in the repl window.  Also, I can use send-text to essentially highlight something in my editor and send it to the repl by using the -m=title option, but how can I actually send a command to another window.? I would like something similar to this mapping:

map cmd+k combine : **clear_terminal scrollback active : send_text normal \x0c**

I am new to kitty and loving the endless possibilities it offers, sorry for the newbie questions.

**Comment by kovidgoyal** [comment]
There are various clear terminal escape codes. You can use

kitty @ send-text 

to send them to the window you want. Just like you use send_text in
kitty.conf

See https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by bhougland18** [comment]
This text gets stuck on the repl promt not the terminal prompt.  How can I have it go directly to the terminal shell?

**Comment by kovidgoyal** [comment]
Text that you send to a window goes to whatever program is running in
the foreground of that window. So send whatever text you need for the
REPL to clear the screen. For example in an ipython repl you would send
clear\r
