### ISSUE TITLE
Tests not passed on s390x arch

### ISSUE THREAD

**Issue by tim77** [kovidgoyal/kitty#2473]
Tests not passed on `s390x` arch. All 5 arches OK except this one.

- [Full build log](https://kojipkgs.fedoraproject.org//work/tasks/3349/42743349/build.log)
- [Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=42743340)

**Comment by kovidgoyal** [comment]
Sorry, I have no clue about this arch.

**Comment by tim77** [comment]
NP. I excluded it and that's it. Thank you one more.
