### ISSUE TITLE
iTerm2-like font rendering

### ISSUE THREAD

**Issue by AranelSurion** [kovidgoyal/kitty#248]
First of all, thanks for taking the initiative and creating an awesome terminal.

It seems, even after adopting CoreText, there are still some noticeable differences between iTerm2 and kitty on rendering text. I don't know the appropriate term for it, "shadow behind the letters" as I call them seem to be quite different. It would be great to understand why there is such a difference, and if possible, gain iTerm2-like font rendering even if its optional.

I am attaching two screenshots I got from Apple 's color picker app.

**iTerm2**
<img width="486" alt="it2" src="https://user-images.githubusercontent.com/271860/34314919-542d84a8-e78a-11e7-9ce5-8038fd5c4ecb.png">

**kitty**
<img width="458" alt="kitty" src="https://user-images.githubusercontent.com/271860/34314920-55baa1d4-e78a-11e7-8b34-d32f60c00104.png">

PS: Colors are also a bit off, but it seems iTerm2 is to be blamed on this. I have configured c7c7c7 on both terminals.

Kitty ver 0.6.0
iTerm2 latest
OS X High Sierra

**Comment by kovidgoyal** [comment]
That's sub-pixel antialiasing. There's another issue about it, where I explain the reasons kitty does not so sub-pixel antialiasing (in brief, it is a performance/memory consumption hit that is not really needed on modern high density displays). 

For the reasons outlined I'm not interested in implementing sub-pixel anti-aliasing in kitty. However, if someone submits a PR that implements it as an option defaulting to off, I wont refuse it out of hand.
