### ISSUE TITLE
Remove update notifications

### ISSUE THREAD

**Issue by vujazzman** [kovidgoyal/kitty#2481]
Update notifications are an antifeature. 

Firstly, from just a straight usability standpoint, it does the job of a package manager, but worse. Imagine also a system in which every tool like kitty caused desktop notifications: it would be unceasing noise.

Secondly, phone home features like this really are not in the spirit of free software. The user should choose if they want to connect to a third party server, not the software.

Finally, saying the fact the feature may be disabled is not a serious mitigation. Again, imagine if all software had usability degrading and privacy invading features, much less such features which are enabled by default. Common users would not bother to disable them due to the nuisance, and could never know if they had done so for all such features anyway. Updates may change the corresponding configuration file and reset user configuration of this feature. The sense of control over and trust in one's system is slowly eroded over time.

Thank you for making such useful software. Let it not be marred by this scourge of software features.

**Comment by kovidgoyal** [comment]
I disagree. And I have explained my reasons already kindly do not waste
your own and my time.
