### ISSUE TITLE
Suggestion: higher default input deplay

### ISSUE THREAD

**Issue by JacksonGariety** [kovidgoyal/kitty#2485]
Kitty is easily one of my favorite programs. That's why I found it disappointing when my kitty instances were not as perceptually responsive as other terminals, e.g. when switching from `urxvt`. But then I was delighted today to discover that bumping up my `input_delay` to `13` makes the entire emulator feel more visually responsive and without any perceived loss of connectivity between key presses and screen events. I presume that the higher input delay gives kitty time to draw the characters before processing the next input. In any case, I wish that when I first installed kitty, I had known that its default input delay would make it less perceptually responsive out-of-the-box than traditional terminal emulators.

EDIT:
My relevant system details:
- Software: Arch Linux 2020.03.01 (Linux 5.5.13.arch1-1)
- `xset r rate 200 50` (this is fast but not uncommonly so)
- CPU: AMD Ryzen 5 2600 3.4 GHz 6-Core Processor
- Graphics card: Radeon RX 580 8 G

**Comment by kovidgoyal** [comment]
Are you running on a system with software rendering/broken GPU drivers or
something? Because there is no way you should be seeing slow rendering
of characters, certainly not slower than urxvt

**Comment by JacksonGariety** [comment]
If I set `input_delay 6` in my `kitty.conf` and use `sleep 0` as my bash prompt function, holding the 'Enter' key in kitty causes the the prompt to flicker. It does not flicker in urxvt. But if I bump the `input_delay` to `7`, then there is no flicker. Remove `sleep 0` gets rid of the flicker too, obviously, but most of us are drawing some kind of dynamic text there so it's reasonable to expect a non-flickering prompt with `sleep 0`.

So: why would it flicker in kitty but not urxvt? I assumed that there was a performance price for the true unicode support, which urxvt (despite the name) lacks.

I use the [`mesa 19.3.4-2` and `xf86-video-amdgpu 19.1.0-1` drivers](https://wiki.archlinux.org/index.php/AMDGPU#Selecting_the_right_driver) on arch.

How do I tell if they are broken?

**Comment by kovidgoyal** [comment]
flicker happens when rendering is too fast, so you see intermediate
states rendered. input_delay prevents that from happening by effectively
batching things. There is no possible way input delay could improve
responsiveness to keystrokes however. See for example here: https://github.com/kovidgoyal/kitty/issues/2196

**Comment by JacksonGariety** [comment]
This is why I wrote "not as _perceptually_ responsive" instead of "not as _computationally_ responsive."

**Comment by kovidgoyal** [comment]
Yeah, all input_delay does is make the thread that processes input
sleep. I dont really see how that could possibly improve perceptions of
input latency, it certainly doesn't for me. But I'll leave this open if
others feel an increased default is better, I'd like to hear it.

**Comment by kovidgoyal** [comment]
Since no one else agrees, closing.
