### ISSUE TITLE
To add to the FAQ: Mouse focus events.

### ISSUE THREAD

**Issue by gbin** [kovidgoyal/kitty#2486]
I was wondering for a while why my vim was acting crazy every time I tried to copy paste something from or to the terminal.

Then simply doing cat and clicking in and out the terminal made me understand something was weird.

```bash
sal ➜  ~  cat
^[[O^[[I^[[O^[[I^[[O^[[I^[[O^[[I^[[O^[[I
```

This is a bad interaction with oh-my-zsh that enables mouse focus events.
To fix this, simply add to your .zshrc after sourcing oh-my-zsh:

```bash
source $ZSH/oh-my-zsh.sh

# oh-my-zsh enables mouse focus events that makes applications misbehave
# This re-disables them.
printf "\e[?1004l"
```

**Comment by kovidgoyal** [comment]
this is a bug in oh-my-zsh, it should be resetting terminal state to
defaults before running the program, otherwise programs will all have to
do that manually before anything else.

**Comment by gbin** [comment]
I found the exact source of the bug (if someone gets into the same case) it is the option:
VIM_MODE_CURSORSHAPE=true
for the plugin vim-mode
