### ISSUE TITLE
initial_window_width doesn't always work

### ISSUE THREAD

**Issue by Nudin** [kovidgoyal/kitty#2489]
I have a very weird behavior for the configuration of the initial window size:

- Is `initial_window_width` set to an value below 1100 px, the window has exactly this size, as it should 
- Is `initial_window_width` set to an value betweem 1101 and 2046 px, the window is always 1100 pixels wide.
- Is `initial_window_width` set to an value above 2047 px, the window has exactly this size, as it should

I set it like this:
```
remember_window_size  no
initial_window_width  2047
initial_window_height 1005
```
Output of kitty --debug-config:
```
kitty 0.17.1 created by Kovid Goyal
Linux hostname 5.5.13-arch1-1 #1 SMP PREEMPT Wed, 25 Mar 2020 16:04:40 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/name/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_font_style (True, False)
background_opacity    0.95
bold_font             JetBrainsMono-Bold
bold_italic_font      JetBrainsMono-Bold-Italic
close_on_child_death  True
cursor_blink_interval 0.0
editor                nvim
enable_audio_bell     False
enabled_layouts       ['fat', 'tall', 'grid', 'horizontal', 'vertical', 'stack']
font_family           JetBrainsMono-Regular
font_size             10.0
initial_window_height (1005, 'px')
initial_window_width  (2046, 'px')
italic_font           JetBrainsMono-Italic
remember_window_size  False
scrollback_lines      100000
tab_bar_edge          1
tab_bar_style         separator
tab_separator          │ 
visual_bell_duration  0.01
```

PS: Thanks for this wonderful piece of software!

**Comment by kovidgoyal** [comment]
This is with what window manager?? I am guessing this is caused by some
interaction with the window manager, since kitty does not care about
sizes, just passes the size request to the system.

**Comment by Nudin** [comment]
marco window manager, Mate as DE.

**Comment by kovidgoyal** [comment]
I'm afraid I am not going to install MATE to try to reproduce. I tested
it with a couple of window managers on my Linux machine with the
following command line and it works fine:

kitty -o remember_window_size=n -o initial_window_width=1203 -o initial_window_height=1005 --config=NONE

Looking at the code, all kitty does is pass the size to glfw when
creating the window and glfw in turn passes it to the window manager. So
I cannot see how this is a kitty issue.
