### ISSUE TITLE
Scroll wheel not working in tmux

### ISSUE THREAD

**Issue by AranelSurion** [kovidgoyal/kitty#249]
Hi,

I've tried running tmux with kitty, and it seems scroll wheel does not work inside tmux. By not working I mean using the scroll wheel does not do anything inside a tmux session. It's not possible to go back in scroll history, and it also does not work in "vim inside tmux" kind of scenarios. Other mouse events (clicking on panes, selecting text/yanking etc) work just fine.

I've tried attaching to the same session with same configuration, with iTerm2 and it worked without problems, except it being generally pretty slow ofc. 

I've also tried using vim without tmux, with kitty and scrollwheel worked in that scenario.

kitty 0.6.0
tmux 2.6
OS X High Sierra

**Comment by kovidgoyal** [comment]
I'm not a tmux user, but I tried running tmux with default config in both kitty and a couple of other terminals, and I see the follwoing behavior:

1) Kitty, and all vte based terminals: scroll wheel has same effect as up/down arrow keys (i.e. it scroll through command history at a zsh prompt)
2) xterm: no effect

So I'm guessing this has something to do wuth some iterm2 specific configuration you have in your tmux. 

Similarly for vim inside tmux, the scroll wheel scrolls the buffer in kitty. Note that you can often solve vim mouse issues by adding

```
set ttymouse=sgr
```

to your vimrc. Normally, vim will autodetect sgr protocol support, but running via tmux can mess this up (one of the many, many reasons, IMO that tmux is a bad idea).

**Comment by Perlence** [comment]
I experience the same issue on 0.12.0 with tmux 2.6. There's a binding in tmux that makes it enter copy mode when scrolling up with mouse wheel:

```
bind-key -T root WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= \"#{pane_in_mode}\" \"send-keys -M\" \"copy-mode -et=\""
```

So when I scroll up I just see kitty's buffer scroll up, looks like the event doesn't reach tmux. And also scrolling doesn't work in vim in a tmux window as @YektaLeblebici mentioned.

**Comment by kovidgoyal** [comment]
kitty will pass scroll events to the application if the application
running inside it tells it that it wants scroll events. See for example
vim with mouse=a in .vimrc

You just need to configure/patch tmux to do that.

**Comment by yiblet** [comment]
If that's the case then tmux wouldn't be working either in other terminal emulators but this issue seems unique to kitty. I have the same problem and tested both konsole and alacritty. They work in both.  However, in kitty, scrolling works on other processes like vim and fail in tmux. 

Has someone found a workaround?

**Comment by kovidgoyal** [comment]
Since alacritty and konsole both use TERM=xterm-256color it is likely that tmux is special casing this TERM value. This is a bug in tmux.

**Comment by nopper** [comment]
I am also affected by this and I don't suppose it's a bug in tmux. I am using byobu with tmux as a backend and scrolling works nicely in any other terminal emulator I've tried (iTerm, any vte based terminal, etc) but not in kitty.

**Comment by matthew-nm** [comment]
I'm encountering a similar issue with WSL (Windows Subsystem for Linux) Ubuntu and the WSLtty (based on Mintty) terminal. Using Tmux in the normal WSL terminal results in perfect scrolling without any strange configuration (just turn mouse mode on). But in WSLtty, it is interpreted as arrows. Why does Tmux see scrolls up/down as arrow keys in WSLtty but not other terminals?

I'm using Tmux 2.6.

See issue I posted in WSLtty here: https://github.com/mintty/wsltty/issues/238

**Comment by trygveaa** [comment]
This is working fine for me with tmux 3.0a and kitty 0.17.2, so maybe it has been fixed for you if you try a newer version?

I tested a couple of other terminals (konsole, alacritty, gnome-terminal), and for me it's working exactly the same way it those terminals as in kitty. If mouse is disabled, scroll triggers arrow keys, and if it's enabled it scrolls the pane.

Also, make sure that mouse mode is enabled in tmux. If you haven't set it explicitly, maybe you have something which sets it based on the TERM value? That could explain the difference in behavior in kitty. If so, try to add `set -g mouse on` to your config.

**Comment by mckellyln** [comment]
Hi,
Thank you for awesome kitty.
But I also cannot get the mouse scroll-wheel to be recognized by tmux or vim.
What is your terminal set to inside tmux ?
Are there any special bindings in your kitty.conf file ?
kitty does not seem to be sending esc sequences, or at least not like other terminals.
I tried these -
```
printf '\033[?1006h\033[?1002h' ; cat <then scroll wheel ...>
printf '\033[?1h\033=\033[?1006h\033[?1002h' ; cat <then scroll wheel ...>
```
and no esc sequences.  But
```
printf '\033[?1049h\033[22;0;0t\033[?1h\033=\033[?1006h\033[?1002h' ; cat <then scroll wheel ...>
```
does produce esc sequences that may be ok, but are diff than other terminals.
I am not sure what terminfo setting I need to get my vim and tmux to read the alt-screen seqences ?
thx,
-m

**Comment by trygveaa** [comment]
> What is your terminal set to inside tmux ?

Both the default `screen` and `tmux-256color` works.

> Are there any special bindings in your kitty.conf file ?

No, it's working without any `kitty.conf` file.

> kitty does not seem to be sending esc sequences, or at least not like other terminals. I tried these -

kitty only sends scroll sequences when in alternate screen. Run that inside tmux and you should get sequences.

> does produce esc sequences that may be ok, but are diff than other terminals.

What do you mean different than other terminals? They are the same for me.

**Comment by mckellyln** [comment]
Hi,
Thanks.
>> kitty only sends scroll sequences when in alternate screen.
yes, this is what I dsicovered and showed with the above printf+cat outputs above.
>> What do you mean different than other terminals?
comparing the sequences there are slightly different than what xterm shows.  But I don't think that is an issue - I cannot get any sequences.
>> Run that inside tmux and you should get sequences.
Sorry, but I do not know what to change to get these seq seen once inside tmux.
Do you have some terminal-overrides set ?
Do you have some tmux mappings for this ?
thx,
-m

**Comment by trygveaa** [comment]
> comparing the sequences there are slightly different than what xterm shows. But I don't think that is an issue - I cannot get any sequences.

As in, the second and third number is different? That would be because your mouse is in another position.

> Sorry, but I do not know what to change to get these seq seen once inside tmux.
> Do you have some terminal-overrides set ?
> Do you have some tmux mappings for this ?

No, it works with a `tmux.conf` containing only mouse enabling, i.e.:

    setw -g mouse on

You haven't changed the value of `TERM`? It should be `xterm-kitty` before launching tmux.

**Comment by mckellyln** [comment]
I do have:
```
setw -g mouse on
```
on my tmux config, 
and my TERM is xterm-kitty outside of tmux and tmux-256color inside of tmux.
Where does kitty look for its terminfo db ?  Perhaps I don't have that set ?
Let me check.

**Comment by trygveaa** [comment]
You can see where the terminfo file is with `echo $TERMINFO`, but tmux won't launch if it can't find the terminfo, so that shouldn't be the problem (well, unless the file contains the wrong stuff).

**Comment by mckellyln** [comment]
I meant the xterm-kitty terminfo db, sorry to not be clear.  TERMINFO env is typically empty because most/common TERM settings are in the default terminfo db, right ?  
This is my question - for kitty I may need to set TERMINFO or install the db into a default location ?

**Comment by trygveaa** [comment]
If you're running tmux locally, kitty should provide the terminfo file automatically, but if you're running it over ssh, then yes, you need to install it. See https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by mckellyln** [comment]
ok, toe -a shows it finds
```
xterm-kitty     KovIdTTY
```
I am running locally.
Thanks for the help.

**Comment by mckellyln** [comment]
I discovered if I turn the mouse off in tmux then I get some esc seqences to show up.
```
set -g mouse off
```
I'm going to give up tho, if anyone else finds a solution please post here.
Other than this issue, kitty has been very good.

**Comment by mckellyln** [comment]
Hi.  Thanks everyone for the help.  I discovered a setting that interfered with mouse wheel esc codes.  I removed this setting and tmux and vi receive mouse wheel codes and work properly.
The setting is terminal-overrides for xterm*:smcup@:rmcup@
My complaint now is alt+wheel does not scroll more lines as I have it configured to.  @nopper I found this setting in $BYOBU_PREFIX/share/byobu/profiles/tmux
thx
-m

**Comment by trygveaa** [comment]
> I discovered a setting that interfered with mouse wheel esc codes. I removed this setting and tmux and vi receive mouse wheel codes and work properly.
> The setting is terminal-overrides for xterm*:smcup@:rmcup@

Ah, that makes sense. That setting tells tmux to not use the alternate screen. Seems to me like a bad idea to have as default in byobu.

> My complaint now is alt+wheel does not scroll more lines as I have it configured to

Well, how have you configured it...?

**Comment by mckellyln** [comment]
@trygveaa hi,
I [think I] am passing the event through to kitty.  Is there a way to configure kitty to scroll more with the Alt modifier ?  If not perhaps I can send scroll-up/down or regular up/down with a repeat ?
thank you,
-m

**Comment by trygveaa** [comment]
I see now that kitty doesn't set modifiers when sending scroll events to the terminal application. And as far as I now, kitty doesn't support configuring what the mouse buttons do. So I don't think this will be possible to achieve without someone adding support for those things.

> If not perhaps I can send scroll-up/down or regular up/down with a repeat ?

What do you mean?

**Comment by mckellyln** [comment]
Hi,
If kitty doesn't send alt mod with wheel than I cannot know to do anything different.
What I meant was perhaps the alt gets thru but kitty doesn't scroll more with it, in which case I can still see this in tmux and vim and send multiple up/downs to get the same effect.

**Comment by mckellyln** [comment]
I'll submit a feature request to kitty for sending ctrl/alt modifiers with scroll wheel.
Thx so much for your help!
take care,
-m

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/aa9c3cd63468d0cef475ecae6517af94770ba4b7

**Comment by mckellyln** [comment]
@kovidgoyal awesome, thank you so much!

**Comment by test-account-0** [comment]
I tried version 0.17.4. Scrolling does not work for me. Also tmux clipboard integration gives some weird results. I'm searching for terminal with simple config file that would work with tmux without issues. Nothing so far.

**Comment by Luflosi** [comment]
Try putting `setw -g mouse on` into `~/.tmux.conf`. This should allow you to scroll using the mouse. I'm not using the the clipboard integration, so I can't help you with that.

**Comment by trygveaa** [comment]
And make sure you do **not** have `terminal-overrides` set to `xterm*:smcup@:rmcup@` or similar (some people in this thread were using byobu which has this set by default).

> Also tmux clipboard integration gives some weird results.

This is probably because of https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard

I'm not sure if there's any configuration in tmux you can use to fix it, but you can fix it in kittys configuration by including `no-append` in the `clipboard_control` option.

**Comment by test-account-0** [comment]
@Luflosi I do have `mouse on`. This is my tmux.conf:
```
# use C-a, since it's on the home row and easier to hit than C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix
set -g base-index 1
set -g set-clipboard on
set -g buffer-limit 100

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# vi is good
setw -g mode-keys vi

# mouse behavior
set -g mouse on

set-option -g default-terminal tmux-256color
set-option -g history-limit 100000
set-option -g renumber-windows on
set-option -g status-interval 1
set-option -wg word-separators ' '

bind-key : command-prompt
bind-key enter next-layout
bind-key C-o rotate-window
bind-key c new-window
bind-key C-c new-window
bind-key C copy-mode
bind-key P paste-buffer
bind-key -n MouseUp2Pane paste

# navigation
bind-key v split-window -h -c "#{pane_current_path}"
bind-key C-v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"
bind-key C-s split-window -v -c "#{pane_current_path}"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key C-n next-window
bind-key C-p previous-window
bind-key S set-window-option synchronize-panes
bind C-l send-keys 'C-l'
bind C-k send-keys 'C-k'
bind-key C-Left swap-window -t -1
bind-key C-Right swap-window -t +1

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R

# copying
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y \
    send-keys -X copy-selection \; \
    send-keys -X clear-selection

bind -T copy-mode-vi MouseDown3Pane \
    send-keys -X copy-selection-and-cancel

unbind -n MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDrag1Pane \
    send-keys -X clear-selection \; \
    send-keys -X begin-selection
bind -n MouseDrag1Pane \
    copy-mode -M \; \
    send-keys -X clear-selection \; \
    send-keys -X begin-selection

# Double LMB Select & Copy (Word)
bind-key -n DoubleClick1Pane \
    select-pane \; \
    copy-mode -M \; \
    send-keys -X select-word
bind-key -T copy-mode-vi DoubleClick1Pane \
    select-pane \; \
    send-keys -X select-word

# Triple LMB Select & Copy (Line)
bind-key -T copy-mode-vi TripleClick1Pane \
    select-pane \; \
    send-keys -X select-line
bind-key -n TripleClick1Pane \
    select-pane \; \
    copy-mode -M \; \
    send-keys -X select-line

# status bar
set-option -g status-interval 1
set-option -g status-left ''
set-option -g status-right ''

# colors
set-option -g status-fg black
set-option -g status-bg default

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on
```
Scrolling up by default triggers copy-mode. It works in every terminal I tried apart from kitty.

**Comment by test-account-0** [comment]
> And make sure you do **not** have `terminal-overrides` set to `xterm*:smcup@:rmcup@` or similar (some people in this thread were using byobu which has this set by default).
> 
I don't have any overrides.

> This is probably because of https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard
> 
> I'm not sure if there's any configuration in tmux you can use to fix it, but you can fix it in kittys configuration by including `no-append` in the `clipboard_control` option.

Yes! That was it. Thanks :)

**Comment by mckellyln** [comment]
@test-account-0 does anything else happen/show when you use the scroll wheel ?
Does the scroll wheel work in vi/vim (both outside tmux and when in tmux) ?

**Comment by test-account-0** [comment]
> @test-account-0 does anything else happen/show when you use the scroll wheel ?

No, nothing.

> Does the scroll wheel work in vi/vim (both outside tmux and when in tmux) ?

It doesn't work anywhere. I have scrollback set to 0 in kitty.

**Comment by mckellyln** [comment]
If you start a new kitty term and do not start tmux and enter this -
```
printf '\033[?1049h\033[22;0;0t\033[?1h\033=\033[?1006h\033[?1002h'
cat
```
and then move the scroll wheel - do you see esc codes ?

**Comment by test-account-0** [comment]
> If you start a new kitty term and do not start tmux and enter these 2 lines -
> 
> ```
> printf '\033[?1049h\033[22;0;0t\033[?1h\033=\033[?1006h\033[?1002h'
> cat
> ```
> 
> and then move the scroll wheel - do you see esc codes ?

Yes. a lot of them.

**Comment by mckellyln** [comment]
ok, good and if you do this same thing inside tmux do you see similar esc codes ?

**Comment by test-account-0** [comment]
> ok, good and if you do this same thing inside tmux do you see similar esc codes ?

I haven't checked it, BUT I had TERM set to xterm-mono.
I've changed it to xterm-256color and scrolling works in kitty.

Is kitty special casing this TERM value?

**Comment by mckellyln** [comment]
Outside of tmux you should have TERM=xterm-kitty.
Inside tmux I think you already have it set correctly to tmux-256color.

**Comment by test-account-0** [comment]
But what if I don't want to see colors?

**Comment by mckellyln** [comment]
ok, I dont know that sorry.  Do you want colours inside of tmux but not outside ?  Or never ?

**Comment by test-account-0** [comment]
never :)

**Comment by test-account-0** [comment]
I want to same myself tedious task of matching color schemes on my computer and on remote servers.

**Comment by mckellyln** [comment]
Perhaps there is some better way but you can set the colours 0-15 in your kitty.conf.

**Comment by test-account-0** [comment]
Ok. I'll try it. Thank You for help :)

**Comment by mckellyln** [comment]
Sure, take care.

**Comment by mckellyln** [comment]
Comparing terminfos:
```
% infocmp xterm-kitty xterm-mono | grep cup    
	rmcup: '\E[?1049l', '\E[2J\E[?47l\E8'.
	smcup: '\E[?1049h', '\E7\E[?47h'.
```
So I'd guess the smcup/rmcup in xterm-mono are not correct for these.
You could try to update your xterm-mono terminfo for these.
Or leave TERM as xterm-kitty ... and change your colours.
