### ISSUE TITLE
Inconsolata fonts stretched due to xft bug

### ISSUE THREAD

**Issue by yourealwaysbe** [kovidgoyal/kitty#2491]
Kitty [is affected](https://bugs.archlinux.org/task/65932?project=5&string=ttf-inconsolata) by a bug, [apparently in xft](https://github.com/LukeSmithxyz/voidrice/commit/f6659aac334265a73c48d27a7babdfce1f5f886e#commitcomment-37998014). This causes the Inconsolata font to be stretched. The fix is apparently to switch to use Cairo instead.

I'm reporting this here in case it's something that Kitty can change. Apologies if it is not.

**Comment by kovidgoyal** [comment]
kitty doesn't use xft. Font data comes from two places, fontconfig and freetype. If those are reporting incorrect values, then the bug really needs to be fixed in inconsolata, as *lots* of software uses and will continue to use those two.

**Comment by yourealwaysbe** [comment]
Sorry -- i looked into this and it doesn't seem related to the xft thing, just similar symptoms at the same time.

Kitty seems to be defaulting to the extra-expanded version of Inconsolata when configured to use the "Inconsolata" font. It works ok if i set the font to "Inconsolata Regular".

```
$ kitty --debug-font-fallback
[088 16:54:40.922790] Preloaded font faces:
[088 16:54:40.922835] normal face: /usr/share/fonts/TTF/Inconsolata-ExtraExpanded.ttf:0
```
Config:
```
font_family Inconsolata # defaults to extra wide
font_family Inconsolata Regular # works ok
```

**Comment by yourealwaysbe** [comment]
Thanks!
