### ISSUE TITLE
Some curious and detailed questions about symbol_map

### ISSUE THREAD

**Issue by ywpkwon** [kovidgoyal/kitty#2492]
Hi, I'm really a fan of kitty. Earlier I faced a font rendering problem and I read about `symbol_map` setup and `--debug-font-fallback` check, which were extremely useful. I also found that when there is space, nerd symbols tries to scale up (I am totally not familiar with the `glyph` thing or `wcwidth` thing...).

So, everything works fine now. I'm just curious what if I want to map all symbols to a certain font?

Somewhere, I found this table.
```
let NerdFont = [|
    (0x23fb, 0x23fe)  // Power Symbols
    (0x2665, 0x2665)  // Octicons
    (0x26a1, 0x26a1)  // Octicons
    (0x2b58, 0x2b58)  // Power Symbols
    (0xe000, 0xe00a)  // Pomicons
    (0xe0a0, 0xe0a2)  // Powerline Symbols
    (0xe0a3, 0xe0a3)  // Powerline Extra Symbols
    (0xe0b0, 0xe0b3)  // Powerline Symbols
    (0xe0b4, 0xe0c8)  // Powerline Extra Symbols
    (0xe0ca, 0xe0ca)  // Powerline Extra Symbols
    (0xe0cc, 0xe0d4)  // Powerline Extra Symbols
    (0xe200, 0xe2a9)  // Font Awesome Extension
    (0xe300, 0xe3e3)  // Weather
    (0xe5fa, 0xe62e)  // Custom + Seti
    (0xe700, 0xe7c5)  // Devicons
    (0xf000, 0xf2e0)  // Font Awesome
    (0xf300, 0xf31c)  // Font Logos (Font Linux)
    (0xf400, 0xf4a8)  // Octicons
    (0xf500, 0xfd46)  // Material
|]
```

Should I list all of them like `symbolmap=U+23FB-U+23FE,U+2665-U+2665,...,...`? Or is there a simpler way to set? I saw a `codepoints` keyword in the FAQ. Is the keyword referring to those nerd font symbols? (I think no since when I tried, it didn't work.)
 
Can I have multiple of them in the configuration file? Or, will the last one just overwrite?
```
symbol_map=U+23FB-U+23FE Font A
symbol_map=U+F500-U+FD46 Font B
```

**Comment by kovidgoyal** [comment]
Yes, you list all of them them and yes you can have multiple ones.
However, I recommend against doing that, there is rarely a need for it,
since nerd fots will automatically be used if found in most cases.
