### ISSUE TITLE
"[PARSE ERROR] Unknown CSI s sequence" error!

### ISSUE THREAD

**Issue by henryzxb** [kovidgoyal/kitty#2493]
(1) When i run the command "kitty --class music -e ncmpcpp",the error occured. 
The out is: "[PARSE ERROR] Unknown CSI s sequence with start and end modifiers: '?' '' and 1 parameters".
but when i run the command "kitty --name music -e ncmpcpp", replace parameter "class" with "name", it just ok.

(2)I have found another issue, when i run a command with complex parameters, such as "kitty @ set-colors $path", the $path can not use tab key to autocomplete, i hope it can be fixed.

**Comment by kovidgoyal** [comment]
1) Means the program you are running sent an escape sequence kitty does
not understand. Not an error in kitty.

2) Not really worth the effort for me, but patches are welcome. Relevant
code is in complete.py

**Comment by kovidgoyal** [comment]
Never mind, I had a minute for (2) so https://github.com/kovidgoyal/kitty/commit/610e9afdf0a17584b80a28dc571b9172a4be2302

**Comment by henryzxb** [comment]
First, thanks a lot for your work! but what i mean i can't use tab key to autocomplete the path is not only about the "set-colors" module, i think it is a function not included in kitty terminal. while i use other terminal like st or urxvt, to run command "st --class music -e ncmpcpp -c $filepath" which has complex parameters, the filepath can use tab key to autocomplete, but kitty not.

**Comment by kovidgoyal** [comment]
Autocompletion in general has nothing to do with terminals. It is done by the
shell. And shells most definitely do autocomplete when run inside kitty.

**Comment by henryzxb** [comment]
Maybe autocompletion is related to the shell, i haved change bash to zsh, the autocompletion work well. However, why autocompletion with bash work well in st or urxvt, kitty with bash not? it's weird.
