### ISSUE TITLE
Kitty crashes in fedora 31

### ISSUE THREAD

**Issue by martin236** [kovidgoyal/kitty#2494]
Hi, I'm new to kitty and have installed the latest Fedora 31 RPM.

I tried running it from terminal, but i get this error;

[root@localhost /]# kitty
[089 11:04:57.499767] Timed out waiting for shell to quit while reading shell environment
[089 11:04:58.030559] Unknown uniform in borders program: _main_pos_map_0[0]

I guess that I need to configure something? If you need any log information just let me know and I'll see what I can find.

Thanks for any help you can provide.
Regards 
Martin Roll, UK.

At this time Stay Safe and Well !

**Comment by kovidgoyal** [comment]
This is the problem: Unknown uniform in borders program: _main_pos_map_0[0]

It indicates your OpenGL drivers are too old/broken. They dont support
array uniforms. kitty requires OpenGL 3.3 compliant drivers (which is
over a decade old at this point)

**Comment by martin236** [comment]
I have this :  OpenGL version string: 3.3.0 NVIDIA 340.108, Is it that my NVIDIA isn't supported ?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by kovidgoyal** [comment]
Yeah, then it is a bug in the driver.

**Comment by martin236** [comment]
I'm looking at changing my card because the linux support for it isn't 100%

Thanks for your help.

Martin.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
