### ISSUE TITLE
Size option for icat-kitten

### ISSUE THREAD

**Issue by kellerben** [kovidgoyal/kitty#2496]
There is an option to print out images in a certain size using `--place <width>x<height>@<left>x<top>`. However, I found no option to print out an image with something like `--size <width>x<height>`.

Did I miss something or is this something which is not implemented yet?

Background: I use this in a script, where I move the cursor using shell escapes like `printf \033[K\033[%iA 10` and want to print out the image afterwards on the current cursor position with a specific size…

**Comment by kovidgoyal** [comment]
Just use the current cursor position as the argument to --place, or
alternately use imagmagick to convert the image to the size you want
before calling icat (you can rely on imagemagick being present since
icat itself uses it).

**Comment by kellerben** [comment]
Trying to get the current cursor position seems to be really hard inside a posix shell script. I found only some hacky options in a bash script reading `\033[6n`…
Modifying the picture with imagemagick feels a bit hacky as I need to calculate the size in advance (I need the number of lines in pixels…) and therefore need to call kitty several times… However, if anyone is interested in the shell-function which works for me:
```
cat_on_current_cursor_with_num_lines() {
  cat_lines=$1
  file_to_show=$2

  term_height=$(kitty +kitten icat --print-window-size|cut -f 2 -d x)
  term_lines=$(tput lines)
  h=$((term_height*(cat_lines)/term_lines))
  tmpfile=$(mktemp --suffix .png)
  convert "$file_to_show" -resize "9999x$h" "$tmpfile"
  kitty +kitten icat "$tmpfile"
  rm "$tmpfile"
}
```

**Comment by kellerben** [comment]
finally… I found a solution which worked for me… here for everyone who searches for something similar: https://unix.stackexchange.com/a/88327
