### ISSUE TITLE
Potential segfault on Linux 5.6/mesa 20

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#2499]
Arch Linux recently updated to a newer mesa version (20.0.2-1). Today, I also installed linux 5.6. Ever since, kitty sometimes segfaults on me out of nowhere, with the following error in dmesg:

```
[19411.105666] kitty[1535]: segfault at 16 ip 00007f00fd6bffb4 sp 00007ffedf5293a0 error 6 in iris_dri.so[7f0
0fd686000+db9000]
[19411.105689] Code: 24 40 17 00 00 f0 0f b1 55 00 85 c0 75 38 49 8d 94 24 30 17 00 00 48 8d 43 08 48 89 53 1
0 49 8b 94 24 30 17 00 00 48 89 53 08 <48> 89 42 08 49 89 84 24 30 17 00 00 f0 83 6d 00 01 75 49 5b 5d 41
```

Running kitty from the newest commit btw, and my arch is fully updated (outside of linux 5.6, which is not "official" yet)

**Comment by rien333** [comment]
There seem to be some other graphical glitches as well. (I can post some later, if you want)

**Comment by kovidgoyal** [comment]
Looks like a segfault in the driver. Nothing kitty can do about it.

Build kitty with make debug, generate the segfault and use

echo bt | coredumpctl gdb

to confirm.

**Comment by rien333** [comment]
I think the segfault is indeed due to some change in mesa, see https://gitlab.freedesktop.org/mesa/mesa/issues/1358. If I can obtain some debug information or a way to consistantly reproduce this issue I'll update accordingly (tho I'm hoping this will just go away with a mesa update)

**Comment by kovidgoyal** [comment]
yeah seems prettly likely since the crash is in iris_dri.so
