### ISSUE TITLE
Cannot build on Ubuntu 16.04 due to glew

### ISSUE THREAD

**Issue by alanwj** [kovidgoyal/kitty#25]
After manually fixing issue #24 by adding ".group(0)" to setup.py line 75:

```
$ python3 setup.py build
glew >= 2.0.0 is required, found version: 1.13.0
```

It appears that 1.13.0 is the latest version available in Ubuntu 16.04 LTS.

**Comment by kovidgoyal** [comment]
Yes, kitty requires glew >= 2.0 If it is not available in your distro, you can always build it from source.

**Comment by kovidgoyal** [comment]
And just to note: glew 2.0.0 is available in Ubuntu Zesty according to https://launchpad.net/ubuntu/+source/glew you might be able to use the .deb package from there.

**Comment by kovidgoyal** [comment]
I dont really care aboutthe caps lock key. The reasonI excluded
modifiers is that modifiers can be pressed while using the mouse to
alter its behavior, so they should not hide the mouse cursor.

**Comment by Luflosi** [comment]
You meant to reply to https://github.com/kovidgoyal/kitty/commit/25cfcdba76be1eac491a84c87381506bac74eaf5#commitcomment-33194311, not this issue.

**Comment by kovidgoyal** [comment]
right sorry.
