### ISSUE TITLE
Issue with emojis in NeoVim

### ISSUE THREAD

**Issue by igorlakic** [kovidgoyal/kitty#2500]
First I have to say that I already saw #875 and that I'm a huge fan of Kitty terminal emulator. Great job!

**Info**
I have zsh 5.8, kitty 0.17.2.
In NeoVim I configured: 'set noemoji' 

**More about issue**
When I e.g. insert emoji for information ℹ️ , the whole line in nvim doesn't render properly. I've tested the same thing in Mate terminal and few others and it works as expected. Do I have to configure something in Kitty to work as expected?

Thanks in advance!

**Comment by kovidgoyal** [comment]
This will be because neovim does not support emoji variation selectors
(U+FE0F in this case) and so incorrectly thinks the width of that emoji
is 1 char instead of 2. Report the bug there.

**Comment by igorlakic** [comment]
Like I already described above, this can be easily fixed in Vim/NeoVim by inserting `set noemoji` in configuration file (which I did). I also tested this behavior in several terminal emulators and it's working there. So for example: Tilix, Xfce terminal, LXTerminal, Mate terminal, Alacritty - they all renders cursor positioning correctly.
So obviously, the problem is not in NeoVim/Vim - when you add `set noemoji` in Vim/NeoVim configuration file problem is solved on Neovim/Vim side.

Can you please reopen this issue again and take a look at this issue?

Thanks in advance!

**Comment by kovidgoyal** [comment]
On Tue, Mar 31, 2020 at 11:40:10AM -0700, Igor Lakić wrote:
> Like I already described above, this can be easily fixed in Vim/NeoVim by inserting `set noemoji` in configuration file (which I did). I also tested this behavior in several terminal emulators and it's working there. So for example: Tilix, Xfce terminal, LXTerminal, Mate terminal, Alacritty - they all renders cursor positioning correctly.
> So obviously, the problem is not in NeoVim/Vim - when you add `set noemoji` in Vim/NeoVim configuration file problem is solved on Neovim/Vim side.

That will be because none of those terminal emulator support unicode
variation selectors. Read up on them. That symbol by default has a width
of 1 char with U+fe0f it becomes 2 chars as per the unicode standard.
kitty renders it in two cells, as required by the standard.

**Comment by igorlakic** [comment]
So there's no appropriate solution for this emoji issue? 
Anyway, thanks for a fast reply @kovidgoyal and thanks for all the effort you put in development of Kitty.

**Comment by kovidgoyal** [comment]
On Wed, Apr 01, 2020 at 01:34:04PM -0700, Igor Lakić wrote:
> So there's no appropriate solution for this emoji issue? 

The solution is for neovim to add support for unicode variation
selectors.
