### ISSUE TITLE
Resizing extremely slow in tiled setups

### ISSUE THREAD

**Issue by OctarineSorcerer** [kovidgoyal/kitty#2501]
Resizing windows when kitty is involved seems to slow down the resizing astronomically. I am not using a compositor, my window manager is bspwm, system specs are Intel Core i5-4690K and NVIDIA GeForce GTX 970. 

Here is a [recording](https://imgur.com/a/mtGvIaB) of the issue - you can see on the desktop with kitty, resizing is incredibly laggy (note my mouse is indeed moving when it appears to freeze). I'd have uploaded the file to github, but two screens of .gif ends up rather large.

This also occurs if I put kitty in the left-hand desktop in that gif - adding kitty to the mix seems to slow it all down. Interestingly, if I set kitty to float instead of tile in the window manager, all windows in that desktop (including kitty) seem to resize with the normal expected performance

**Comment by kovidgoyal** [comment]
I dont see what this has to do with kitty. Resizing of windows happens
perfectly performantly when using i3 for instance (although to be fair
i3 doesnt redraw windows while resizing). And in any case
window managers dont care how slow or not applications are when
resizing. They simply resize the window and send a resize event to the
application. It is then up to the application to redraw when it can. The
process is asynchronous. This is likely a bug in your window manager.
