### ISSUE TITLE
Request: Show a scroll bar or a very minimized version of it

### ISSUE THREAD

**Issue by gerion0** [kovidgoyal/kitty#2502]
I often have the usecase (especially when compiling C++-programs) to get a lot of output nearly at once in the terminal and then struggle to find the actual command again to start reading at the beginning of the output.

My workaround for this is to start the program (in this case GCC) and then scroll 1 line up. GCC is then dumping a lot of warnings and errors to stderr and into the scroll buffer of kitty. Then I can scroll down and read the output from the beginning to its end. However, I have no indicator how much lines of the terminal output are hidden below the actual displayed output, so I don't get a notification when the compiler is done with its job.

Is there some kind of scrollbar, that is only visible when you are actually scrolling up? Or is there any other kind of indicator where you are in the current terminal session? What do you think about a little indicator button in the right corner that prints the amount of lines coming below the current displayed ones (some similar button like many mobile chat programs nowadays have to scroll to the end with one click)?

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in implementing a scrollbar, kitty is very
much intended for keyboard use. As for your actual use case, use the
marks feature, it is designed for exactly this

https://sw.kovidgoyal.net/kitty/marks.html

simply add some distinctive text/symbol to you prompt and jump to it
using a mark.

**Comment by gerion0** [comment]
Nice feature, thanks for the tip! This is even better.

**Comment by Atralb** [comment]
@kovidgoyal Marks are not an alternative to a scrollbar in the slightest. Scrollbars are primarily used in order to know where you are within your scrollback. At the very least kitty should display a percentage indicating the relative position in the scrollback. As is, I'm afraid kitty is a no-go for me, even if I quite like the program.

**Comment by iamtakingiteasy** [comment]
Indeed, without visual indication it is hard to orient in large scrollback buffers. Lack of simple indication makes it less than convincing alternative to more mature projects.

**Comment by backermanbd** [comment]
@kovidgoyal we want scroll bar at least
furthermore there's no ui in terminal
do this.. or we won't use your shitty terminal
