### ISSUE TITLE
Alt + "<" keyboard command not working

### ISSUE THREAD

**Issue by tommyalatalo** [kovidgoyal/kitty#2503]
I'm using tmux in kitty and want to bind Alt + "<" (the key to the right of left shift) on a nordic keyboard to split windows vertically. This doesn't work in kitty, but works perfectly in alacritty, xfce terminal, guake and terminator. In kitty nothing happens when pressing the above shortcut, however pressing Alt + "-" to split horizontally works fine in tmux across all terminals, including kitty.

Is there some setting that needs to be configured for this to work, or is this a bug/limitation with kitty as it is now?

**Comment by kovidgoyal** [comment]
I'm not familiar with that keyboard layout. But on a US layout you would
need to press alt+shit+, to generate alt+<

And you can see what key is being sent by kitty using
showkey -a
For my keyboard pressing alt+shift+, generates
^[< 	27 0033 0x1b
 	    60 0074 0x3c

as expected. Finally, if for whatever reason you cant get it to work,
you can always add a manual override for it in kitty.conf via send_text

**Comment by tommyalatalo** [comment]
When I add showkey -a and press Alt + "<" there is no output.
Something is wrong in the way kitty reads the input if it works on all the other terminals, it seems.

**Comment by kovidgoyal** [comment]
So use --debug-keyboard and map whatever the key event actually is using send_text

**Comment by tommyalatalo** [comment]
Pressing alt + < in kitty debug mode yields this:
```
on_key_input: glfw key: 60 native_code: 0x3c action: PRESS mods: 0x4 text: '' state: 0 handled as shortcut
Press xkb_keycode: 0x5e clean_sym: less composed_sym: less mods: alt glfw_key: 60 (LESS) xkb_key: 60 (less)
Keypress matched action: send_text
```
I tried adding all of the below separately:
```
map alt+< send_text all \0x3c
map alt+< send_text all 0x3c
map alt+< send_text all \x3c
map alt+< send_text all \0x4
map alt+< send_text all \0x5e
map alt+< send_text all \x5e
```
None of these work, though some of them toggle tmux's "kill pane" shortcut

**Comment by kovidgoyal** [comment]
As can be seen from the send_text output I posted above, the correct
value is

\x1b\x3c
