### ISSUE TITLE
XOrg drag-and-drop crash

### ISSUE THREAD

**Issue by LouisTakePILLz** [kovidgoyal/kitty#2505]
Kitty 0.17.2 crashes when dragging files from the GNOME file roller, VLC and possibly a lot more programs:
```
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x0
  Serial number of failed request:  504
  Current serial number in output stream:  505
```

gif: 
![kitty_dnd_crash](https://user-images.githubusercontent.com/920910/78264550-51f1a800-74d1-11ea-8531-e7d45bbf450b.gif)

**Comment by Arnaudv6** [comment]
Do you consider a release with this fix soon please?
