### ISSUE TITLE
[Help needed] how would you implement a gitmoji kitten?

### ISSUE THREAD

**Issue by metalelf0** [kovidgoyal/kitty#2507]
Hey man, first of all, hope you and your dearest ones are all safe and healthy during this covid crisis.

I'm using [gitmoji](https://gitmoji.carloscuesta.me/) regularly and I'd like to add it to kitty. I thought about an extra mode in the unicode input kitten, but I'm missing something. To make it work as expected, I'd copy the `names.h` file, adding (or replacing) unicode names with the gitmoji hints (e.g. ":zap: improving performance" in place of `LIGHTNING`). Then I'd duplicate the functions responsible of loading those names and somehow bind them to a custom set (e.g. `GITMOJI_SET`) inside the kitten `main.py`, with a `F5` key. Does this sound reasonable to you? I'm no python expert, so I'm asking before diving in cause maybe you could have hints about a better way to do it. And yes, I know `gitmoji` is just eyecandy, but I like it ;)

**Comment by kovidgoyal** [comment]
We're doing fine, so far, thanks :)

I'm not familiar with gitmoji is it simply a set of aliases for existing
unicode symbol names? If so you best bet is to modify gen-wcwidth.py to
add those aliases when it creates names.h
