### ISSUE TITLE
Dragging a Firefox tab over kitty crashes it

### ISSUE THREAD

**Issue by farid-fari** [kovidgoyal/kitty#2508]
Using GNOME 3.36.1, and Firefox 74.0.1 under Xorg.

I have a kitty terminal open, and a Firefox window with several tabs. I drag a tab from Firefox over to `kitty`, go over the `kitty` window *without dropping the tab*, and `kitty` immediately crashes.

**Comment by kovidgoyal** [comment]
dup of #2505
