### ISSUE TITLE
Alt + arrow bindings not working

### ISSUE THREAD

**Issue by AranelSurion** [kovidgoyal/kitty#251]
Hi,

I am using alt + up/down/left/right arrow to switch panes in tmux, yet it seems alt+arrow keybindings are not working in kitty. As far as I am aware, other modifiers (alt + numbers for example) are working.

macos_option_as_alt yes (alt key stops working altogether if set no)
kitty 0.6.0
tmux 2.6
OS X High Sierra

**Comment by kovidgoyal** [comment]
Let's reduce the number of moving parts in this equation first :)
Run cat in kitty and press the alt+arrow key combinations ans see what you get. Compare it with what you get in another terminal.

**Comment by kovidgoyal** [comment]
On my mac doing the above yields, for Alt+right arrow
```
^[[1;3C
```

which is the correct escape code (in that it matches the kitty terminfo file for 3 right key presses), and matches what is seen in xterm, gnome-terminal, etc. However, iTerm seems to generate `^[f` which is weird. I'm guessing that you have either configured tmux to recognize those sequences, or tmux comes hardcoded to match iterm behavior on os x. Either way, I'm not sure I see anything kitty can fix here. You can override what escape codes kitty sends for any given key press, via map send_text in kitty.conf. So you can workaround this by adding the appropriate rules to your kitty.conf file. Or presumably tmux has some config options that work similarly on the other end.

**Comment by AranelSurion** [comment]
I've tried alt+arrows today outside tmux, yet they did not generate any escape codes at all. just using arrows correctly generated escape codes though.

**Comment by kovidgoyal** [comment]
Is this with a default kitty config?

**Comment by AranelSurion** [comment]
here is my kitty.conf: https://github.com/AranelSurion/dotfiles/blob/master/kitty.conf

If I set macos_option_as_alt to no, alt + 1...9 combinations stop working.

**Comment by kovidgoyal** [comment]
Yes if you set that to no, then option is used to enter unicode characters, as in the rest of macOS. And the kitty.conf you posted has it set to no. Change it to yes and you shoudl get the same results I get.

**Comment by AranelSurion** [comment]
D'oh. 😶 Sorry I've mislead you on this. 

Thing is, now I've set it to "yes" and alt+arrow combinations are now working, but ALT+1..9 keys are no longer printing any symbols. I'm using a TR_Q keyboard layout, so ALT+4 should be "$" sign, yet nothing happens when I press these combinations. As soon as I revert back to "no", alt+numbers work and alt+arrow stops working.

**Comment by kovidgoyal** [comment]
Yes you can either have the option key generate unicode symbols/text or have it work as the alt modifier, not both. That is a fundamental limitation.

**Comment by AranelSurion** [comment]
Okay. Is this a kitty limitation though? Symbols and modifiers both work in, for example, iTerm2. 

If this is a kitty limitation, maybe this issue should be reopened so it will be visible for anyone to attempt such an improvement.

**Comment by kovidgoyal** [comment]
That makes no sense. Either alt+X can generate A or it can generate B. It cannot generate both A and B. If you mean that for some values of X, for which the OS does not generate symbols, iterm2 generates escape codes, sure that is a limitation of kitty, or more properly speaking, a limitation of glfw, since it has no way to handle both key and text input (see https://github.com/glfw/glfw/issues/1140)
