### ISSUE TITLE
[RFC] Sixel support

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#2511]
[Sixels](https://en.wikipedia.org/wiki/Sixel) are an ancient protocol for supporting graphics in the terminal, similar, but inferior to, Kitty's native graphics protocol.

The major way sixels are inferior is that there is no alpha and the color palette is limited, unlike Kitty's support for full RGBA. 

Be that as it may, due to their age, many other terminals support them, which becomes a self-fulfilling prophecy, as people are more likely to add sixel support than Kitty graphics support.

So, I wonder what the right play is here. Implement sixels? Not hard to do, just translate the commands into Kitty graphics commands internally.

Or, given our market leader position, ignore sixels, and continue to ask other VTEs to implement our protocol?

**Comment by kovidgoyal** [comment]
On Sun, Apr 05, 2020 at 11:58:55AM -0700, Fredrick Brennan wrote:
> [Sixels](https://en.wikipedia.org/wiki/Sixel) are an ancient protocol for supporting graphics in the terminal, similar, but inferior to, Kitty's native graphics protocol.
> 
> The major way sixels are inferior is that there is no alpha and the color palette is limited, unlike Kitty's support for full RGBA. 
> 
> Be that as it may, due to their age, many other terminals support them, which becomes a self-fulfilling prophecy, as people are more likely to add sixel support than Kitty graphics support.
> 
> So, I wonder what the right play is here. Implement sixels? Not hard to do, just translate the commands into Kitty graphics commands internally.

sixels have other problems, no z-index, much harder to implement, no
support for efficient data transmission when the emulator and program
have a shared filesystem/memory. See the original issue for graphics
support in kitty (it is linked to from the graphics protocol page) for a
discussion.

> 
> Or, given our market leader position, ignore sixels, and continue to ask other VTEs to implement our protocol?

As I noted on the original issue, I have no interest personally in
implementing an inferior graphics protocol in kitty. I know of no
program that I would use that supports sixels but not kitty's graphics
protocol.

That said, I wont refuse a patch to implement it on top of the existing
graphics support, provided I was reasonabl confident the person
implementing it would stick around to maintain it as well.
Although I suspect it wont be quite trivial, as the
semantics of how images drawn with sixels work with scrolling, screen
boundaries, cursor position are probably different.

**Comment by kovidgoyal** [comment]
For reference: https://github.com/kovidgoyal/kitty/issues/33

**Comment by kovidgoyal** [comment]
Since no one else has comments, closing.

**Comment by ctrlcctrlv** [comment]
Sixel's are once again on my mind. They're supported in a lot of programs, including `mpv` (Cf. #3673, [saitoha/libsixel `README`](https://github.com/saitoha/libsixel)).

I'd appreciate this being reopened, but even if it's not, I'm going to spend tonight integrating `libsixel` as an optional build dependency into Kitty. It's a C library with a Python binding. I think I can do it in a few hours.

**Comment by kovidgoyal** [comment]
The hard part isnt parsing the escape codes, which libsixel will do for you, its adding support for the very different semantics that sixels based images have wrt to things like scrolling, text overwriting the image, what happens when the terminal resizes, etc.

If I were you I would instead spend this energy on adding support for the kitty graphics protocol to mpv :)

**Comment by ctrlcctrlv** [comment]
I have the basics of Sixel support working.

![image](https://user-images.githubusercontent.com/838783/120416359-03d17200-c32b-11eb-831a-962991dbfbea.png)

![image](https://user-images.githubusercontent.com/838783/120416485-3da27880-c32b-11eb-9128-43f5b19b9b21.png)

I'm using `xterm -ti vt340` as the source of truth for what should happen in various situations. I feel like `xterm` is already a logical source of truth anyway.

I posted the code to try to answer some of @dankamongmen's questions. No, sixel images don't blow away Kitty graphics data. They work together, they're implemented through `grman_handle_command`!

**Comment by kovidgoyal** [comment]
Good progress, now try the following things:

1) Sending an image larger than the screen
2) Moving the cursor back and printing some text over the image


See if what happens matches xterm.

**Comment by ctrlcctrlv** [comment]
# Test case 1
![image](https://user-images.githubusercontent.com/838783/120422126-a858b180-c335-11eb-848e-439a398f26ee.png)

I fixed this by switching from `grman_handle_command` to `screen_handle_graphics_command`. 

# Test case 2
![image](https://user-images.githubusercontent.com/838783/120422403-2ae17100-c336-11eb-8b7b-b19ef3e94d4d.png)

I'm still working on this one, as you can see it's quite different. Any ideas?

**Comment by ctrlcctrlv** [comment]
Actually after I adjusted the z-index to -1, it's just a matter of fixing the placement of "hello". I think that the white background of the cells in xterm should be optional, but if it's really important to you I can fix that too.

# New test case 2
![image](https://user-images.githubusercontent.com/838783/120422734-e6a2a080-c336-11eb-9af3-009f306105f5.png)

**Comment by kovidgoyal** [comment]
Not sure I am following about the white background. I think the sixel semantics are that both the foreground and background colors are displayed for text printed over an image. @dankamongmen can correct me if I am wrong. For you I think that means the z-index needs to be low enough that the image is displayed below the background layer (IIRC this was a feature of the graphics protocol you requested :)

It is important to have the cursor positioned at the same location post drawing a sixel as xterm does it.

**Comment by ctrlcctrlv** [comment]
Got it. `-2` is correct.

I've discovered that `xterm` considers a Sixel sequence as having an implied newline, even if the file is `noeol`. If the sequence is followed by a newline, however, that's not an extra newline.

**Comment by ctrlcctrlv** [comment]
I'm making good progress with this. I'm also now the lead maintainer of [libsixel](https://github.com/libsixel/libsixel/).

I have tested a variety of programs, and so far they all work equal to xterm except w3m. The issue with w3m is that it expects drawing sixels over top of text to erase the text. Here's an image comparison of `w3m -sixel 'https://commons.wikimedia.org/wiki/Category:Atlantic_City_High_School'`

## xterm
![image](https://user-images.githubusercontent.com/838783/121793271-7ebc4780-cbcb-11eb-9ebd-115a4900c22f.png)

## kitty
![image](https://user-images.githubusercontent.com/838783/121793292-af9c7c80-cbcb-11eb-8ca9-08f633c01344.png)

I'm thinking how to fix this. Looking through `screen.h` for a function I can call to clear a square of cells before I draw a sixel image on it.

**Comment by kovidgoyal** [comment]
I dont think there are any pre-built functions for this, but you can add one in screen.c similar to screen_erase_in_display. It can serve as the basis for implementing DECERA

**Comment by valderman** [comment]
Did anything ever come out of this? An upcoming sixel patch is mentioned in #3737, but as far as I can tell that's where the trail ends.

**Comment by ctrlcctrlv** [comment]
@valderman yes it did. But Kitty is a very security important application. After I took over the maintainership of libsixel I unfortunately decided it cannot support the security demands of Kitty, it is too insecure internally. I need to write a Rust library or something. But there is a patch above that should still compile which uses libsixel if you are curious, the screenshots weren't faked or anything...

**Comment by ctrlcctrlv** [comment]
@valderman I, or someone else, needs to write one in Rust with a compatible C ABI to the normal libsixel. `kitty` can then link to that. Cf. https://github.com/kovidgoyal/kitty/issues/2701#issuecomment-1242602181

**Comment by voronoipotato** [comment]
I didn't even know there was a security focus for kitty, I just use it because it's fast enough, has themes, and supports ligatures. I'd kinda prefer sixel support over some "security" , at least as an option...

**Comment by ctrlcctrlv** [comment]
If it's not @kovidgoyal's focus it's at least mine for my patches, all I can say :)

**Comment by Meow-purr** [comment]
im forking it @ctrlcctrlv could you submit apatch after i fork(in a few minuts

**Comment by Meow-purr** [comment]
see https://github.com/Meow-purr/Cat

**Comment by Kreijstal** [comment]
so, how is sixels progress going? are there any emulators besides xterm that support sixels?

**Comment by ErrorNoInternet** [comment]
> are there any emulators besides xterm that support sixels?

https://arewesixelyet.com/

**Comment by Kreijstal** [comment]
> KiTTY's graphics protocol is superior to sixel, but then again, Betamax was superior to VHS, and we all know how that ended. sixel support please. Not just in KiTTY but _everywhere._

this

**Comment by RobertWHurst** [comment]
Except that VHS was the superior format. Most people confuse the version of betamax used for professional mastering with the consumer version. They weren't even compatible. The consumer version of betamax was pitiful in comparison to vhs, which is why it failed.

Technology Connections did a series on this https://youtu.be/FyKRubB5N60?si=ysNxgfb-og4qtx6E

**Comment by artcancrotp** [comment]
> Except that VHS was the superior format. Most people confuse the version of betamax used for professional mastering with the consumer version. They weren't even compatible. The consumer version of betamax was pitiful in comparison to vhs, which is why it failed.

You're wrong about that, but it also doesn't matter.  At this point it's all over but the shoutin' -- Sixel has won.  The ecosystem around Sixel continues to expand rapidly -- heck, it's even getting merged into Windows Terminal as we speak.  Tools to generate Sixel graphics, people using it for data visualization, and [many terminals](https://www.arewesixelyet.com/) supporting it -- there is no doubt that we are headed into an age where supporting something other than Sixel for terminal bitmap graphics is like supporting something other than ANSI for color and cursor control.

Don't get me wrong, KiTTY graphics is _excellent_ but if the superior technology always won we'd all be using Amigas right now.

**Comment by SolitudeSF** [comment]
> Sixel has won

nuh uh

**Comment by artcancrotp** [comment]
> nuh uh

Thank you for that insightful, fact filled, and thought provoking response.

It's an open source project and Kovid can do whatever he wants with it, of course.  But it is now the current year and writing a terminal that supports some other graphics protocol instead of Sixel is like writing a terminal that supports (for example) Wyse 50 terminal sequences instead of ANSI.

I switched from KiTTY to a different terminal program for exactly this reason.  I'm not alone.

**Comment by SolitudeSF** [comment]
Cool analogy. Too bad it doesn't make sense.

**Comment by artcancrotp** [comment]
> Cool analogy. Too bad it doesn't make sense.

That's because it all happened before you were born.  Every terminal had a different language and we needed cumbersome abstraction layers to build software that could deal with the differences.  Today, every terminal supports ANSI and you can count on the `ESC [` codes being available everywhere.  Everyone converged on the language originally conceived by DEC in 1978 for the VT100.  Other terminal control languages are not just abandoned but practically forgotten.

Learn from technology history.  So far all you've contributed to the conversation is rude quips.  We are now in the same situation with terminal raster graphics where we were with basic terminal control codes in the 1980s.  But time marches on and convergence happens.  The world is converging around Sixel whether you like it or not.

**Comment by artcancrotp** [comment]
> Window Terminal adds Sixel support

There's a very spirited discussion that has been going on for a long time over there.  It's a pretty sad state of affairs that Microsoft (MICROSOFT!) is acknowledging and adopting the de facto standard (sixel) while KiTTY continues soldiering forth with its own incompatible format.

I stopped using KiTTY because it has no Sixel roadmap and the world is quickly standardizing on Sixel.

**Comment by CannibalVox** [comment]
Sixel support is in the windows terminal preview now and should go into public release by the end of the year. iTerm2 has support. tmux has support from `brew install` (it has some issues that will have fixes in public release by the end of the year).  

Kitty is very much the outlier here.

**Comment by Kreijstal** [comment]
> Sixel support is in the windows terminal preview now and should go into public release by the end of the year. iTerm2 has support. tmux has support from `brew install` (it has some issues that will have fixes in public release by the end of the year).
> 
> Kitty is very much the outlier here.

just use wezterm lmao

**Comment by paulie-g** [comment]
> @valderman yes it did. But Kitty is a very security important application. After I took over the maintainership of libsixel I unfortunately decided it cannot support the security demands of Kitty, it is too insecure internally. I need to write a Rust library or something.

Just out of curiosity (and with the deepest respect), did you actually identify security issues in libsixel or is this "anything written in C is insecure and must be rewritten in Rust"? Unless the deep details differ significantly from the description of the sixel protocol, it's not particularly complex to decode (vt* requires a substantially more hairy hand-written FSM essentially). libsixel's decode functionality is, at a superficial count, under 2k sloc (most of the code in libsixel appears to be encoding, conversion from misc image formats and bindings for other languages) and therefore easily auditable (with your eyes, a fuzzer, or both) and, if necessary, fixable. There's also libsixel-rs.

**Comment by dankamongmen** [comment]
> Just out of curiosity (and with the deepest respect), did you actually identify security issues in libsixel or is this "anything written in C is insecure and must be rewritten in Rust"? Unless the deep details differ significantly from the description of the sixel protocol, it's not particularly complex to decode (vt* requires a substantially more hairy hand-written FSM essentially). libsixel's decode functionality is, at a superficial count, under 2k sloc (most of the code in libsixel appears to be encoding, conversion from misc image formats and bindings for other languages) and therefore easily auditable (with your eyes, a fuzzer, or both) and, if necessary, fixable. There's also libsixel-rs.

i can answer this, as one of the last maintainers of libsixel. the API as defined does not allow you to pass in a maximum write length, but allows arbitrary input sizes. this can't be changed without changing the library API. you can go look at the bugs i filed and the length discussions that resulted. eventually i abandoned maintainership, as the library is unredeemable.

**Comment by paulie-g** [comment]
> i can answer this

Thank you very much for the info, that's perfectly clear (also ty for notcurses, it's dank ;).

**Comment by dankamongmen** [comment]
> Libsixel2 when?

it certainly wouldn't be from me. sixel is a terrible standard. i've got some thoughts on that [here](https://nick-black.com/dankwiki/index.php/Theory_and_Practice_of_Sprixels). the kitty format is far superior.

**Comment by 0x501D** [comment]
Ok. Still no sixel support.
No problem. I will fork and add it for myself.

**Comment by Kreijstal** [comment]
> Ok. Still no sixel support. No problem. I will fork and add it for myself.

based lain

**Comment by 0x501D** [comment]
> Ok. Still no sixel support. No problem. I will fork and add it for myself.

I looked into kitty's RCF on graphics-protocol and found it to be much more capable than sixel. The main idea for me was to support virtual machine previews in my program [nEMU](https://github.com/nemuTUI/nemu). As a result, I will do the preview using the kitty graphics protocol.

**Comment by 0x501D** [comment]
That's all Folks!
https://github.com/libsixel/libsixel
This repository has been archived by the owner on Feb 12, 2025

**Comment by Kreijstal** [comment]
> That's all Folks! https://github.com/libsixel/libsixel This repository has been archived by the owner on Feb 12, 2025

I'll just try to provide the releases, I don't like with conversation gets shutdown like that https://github.com/Kreijstal/libsixel

**Comment by SolitudeSF** [comment]
> > I looked into kitty's RCF on graphics-protocol and found it to be much more capable than sixel.
> 
> It doesn't matter for protocols how capable they are. What matters is the prospects of adoption. Adoption of Kitty graphics protocol is marginal and will likely stay so. Especially considering the author's communication talents.
> 
> > That's all Folks!
> 
> All what? It's just one implementation (which didn't disappear anyway). There is [Chafa](https://hpjansson.org/chafa/) too.

even the library you referred to implement kitty graphics.

**Comment by SolitudeSF** [comment]
> The point of your statement is beyond me. Are you trying to argue with something in my message? Try harder then.

why should i try for a ragebaiting troll?

**Comment by 0x501D** [comment]
> > Ok. Still no sixel support. No problem. I will fork and add it for myself.
> 
> I looked into kitty's RCF on graphics-protocol and found it to be much more capable than sixel. The main idea for me was to support virtual machine previews in my program [nEMU](https://github.com/nemuTUI/nemu). As a result, I will do the preview using the kitty graphics protocol.

Done
https://github.com/nemuTUI/nemu/pull/186
Kitty gpaphics protocol is good!

**Comment by CannibalVox** [comment]
My favorite type of TUI application is the type that tells me what terminal to install.

**Comment by brandon-fryslie** [comment]
> given our market leader position

mid 90s Apple vibes

**Comment by clort81** [comment]
apt purge kitty
