### ISSUE TITLE
Feature suggestion: tab style for bell activity

### ISSUE THREAD

**Issue by ericem** [kovidgoyal/kitty#2514]
This is a suggestion to implement a separate tab style for a tab that has a bell event. This would allow high-lighting tabs in a different color to make them more visible. I recognize that Kitty already supports adding a bell icon to a tab, this enhancement would add more granular control to the look of a bell tab.

bell_tab_foreground
bell_tab_background
bell_tab_font_style

**Comment by kovidgoyal** [comment]
Not worth the effort to me, with a bell icon the tab is pretty
distinctive already. That said I wont refuse a PR.
