### ISSUE TITLE
Non-standard monospace fonts cannot be used by default

### ISSUE THREAD

**Issue by georgeabr** [kovidgoyal/kitty#2516]
As per the link below, you have to add your non-standard monospace font to the `~/.config/fontconfig/fonts.conf` file, to make it work with `kitty`:
https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font
The `match target` filter did not work for me, for example for font `Roboto Mono`.

I have therefore replaced the line in the documentation
```<match target="scan">``` (does not work)
with
```<match target="font">``` (works)
to make `fontconfig` and `kitty` recognize `Roboto Mono` as a monospace font.

Here are the filter lines that worked for me:
```
<match target="font">
    <test name="family">
    <string>Roboto Mono</string>
    </test>
    <edit name="spacing">
        <int>100</int>
    </edit>
</match>
```
Maybe you could modify the corresponding documentation line to ```<match target="font">```.

**Comment by kovidgoyal** [comment]
feel free to send a pul request the documentation is in faq.rst
