### ISSUE TITLE
^W doesn't work if layout is different from English

### ISSUE THREAD

**Issue by korjavin** [kovidgoyal/kitty#2522]
If my keyboard layout is different from English hotkeys ^W, ^Y and others don't work.

lxterminal and gnome-terminal have different behaviour (continue working)

**Comment by kovidgoyal** [comment]
Yes if the W key is not W then why would you expect pressing ctrl+not W
to give you ctrl+w?? Say W is mapped to A then pressing w gives you a
and ctrl+w gives you ctrl+w. Seems completely wrong to me.

**Comment by korjavin** [comment]
It could be wrong, but since ALL other terminal emulators that I've ever seen have this behavior, it seems that kitty should have it as well.

**Comment by kovidgoyal** [comment]
If I wanted to always do what all terminal emulators do, I would never
have bothered creating my own.

**Comment by korjavin** [comment]
Well, it was a good try then. I give it a try for couple of days. It's not bad.

But it's totally unusable for every one who has more then one layout on their computers.
There are hundreds hotkeys like ^W, ^D and others.
Which works in layout-independent way in every application. Terminal emulators/ browsers/ IDE.

If you trying to enforce opposite option in the very one application it probably prevent using of it.
