### ISSUE TITLE
Add documentation for panel example

### ISSUE THREAD

**Issue by twoboxen** [kovidgoyal/kitty#2523]
Hello!  Kitty has been great, and I'd like to try out Kitty panel with bspwm.  Can you please add the command you used to generate the example screenshot:
https://github.com/kovidgoyal/kitty/blob/3b1490020d7bc23fadedb02168f1e15970f8e0bc/docs/screenshots/panel.png

In addition to "Hello World" example?

Thanks!

**Comment by kovidgoyal** [comment]
I'm afraid that's something private I use for my own machines.

**Comment by twoboxen** [comment]
lol.  wtf?  A sensitive status command?  this is a first.

**Comment by kovidgoyal** [comment]
Yup its part of an entire custom desktop that I have written for myself that most definitely does include sensitive things.
