### ISSUE TITLE
[Bug/Help] Kitty only renders properly in fullscreen

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [kovidgoyal/kitty#2524]
I think this issue is related to [kitty#780](https://github.com/kovidgoyal/kitty/issues/780), however, it doesn't seems to be fixed yet despite the issue being closed.

I am using i3wm on manjaro, integrated graphics UHD 620.

The behaviour stay consistent with whether `GLFW_IM_MODULE=none` being set or not, I am using fcitx. 
The keys are registered when kitty is not in fullscreen.
The program will render properly when it enters fullscreen by shortcut.

When kitty is not in fullscreen, most of the time it would just be blank, sometimes, it will have the prompt with it. It appears to be frozen, unresponsive to keyboards input, however, it upon starting kitty and enter `exit` + hit enter will exit the program.

I believe this is not because of Kitty, because the same behavior can be observed on some other programs I wrote that uses glfw. And **similar**  behaviors on alacritty, discord (completely not rendering even in fullscreen).

I still would like to put this issue up to get some help fixing these issues. Thanks

**Comment by kovidgoyal** [comment]
As I noted in #740 this is not an issue in kitty code. This is an Xorg/driver issue, and I am not an expert in those, you should ask for help in those projects support fora. Or maybe switch to Wayland.
