### ISSUE TITLE
Feature Suggestion: Hold Shift to mark selection

### ISSUE THREAD

**Issue by NovaDev94** [kovidgoyal/kitty#2525]
It works the same way as how most applications are on macOS.

1. Click to mark the start of the selection
2. Hold Shift
3. Click again to mark the end of the selection

Step (1) and (2) are interchangeable. You can hold Shift first, before click to mark the start...

The reason for this is it's easier to select a lot of text - especially when it doesn't fit in a single screen.

**Comment by kovidgoyal** [comment]
This already exists, via right click. https://sw.kovidgoyal.net/kitty/#mouse-features
Of course Apple thinks its users are not sophisticated enough to handle
two button mice, so I dont know if this is useable on macOS. Maybe the
contol+click or cmd+click right click simulation works, not sure.

And shift click in terminals is reserved to allow the user to force
terminal selection even when the application running in the terminal
grabs the mouse.

**Comment by NovaDev94** [comment]
I'm sorry that I haven't done my search better... Thanks a lot for your great work.
