### ISSUE TITLE
very minor documentation improvement...

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#2526]
> #: The enabled window layouts. A comma separated list of layout names.
#: The special value * means all layouts. The first listed layout will
#: be used as the **startup** layout. For a list of available layouts, see
#: the layouts.

is written in the config file
I think it's better to use **default** instead of **startup** since

> By default, all layouts are enabled and you can switch between layouts using the ctrl+shift+l key combination. You can also create shortcuts to select particular layouts, and choose which layouts you want to enable/disable, see Layout management for examples. The first layout listed in enabled_layouts becomes the **default** layout.

This is written in the documentation and also to be honest I personally couldn't find that part and I had to check the website to figure it out.

**Comment by kovidgoyal** [comment]
Sure, send a PR
