### ISSUE TITLE
Some console app breaks kitty output

### ISSUE THREAD

**Issue by korjavin** [kovidgoyal/kitty#2530]
I tried to use clickhouse-client with kitty.

It uses some kind of special characters for spinning progress bar, and it ruins kitty output.

it position cursor in random places after.

**Comment by korjavin** [comment]
example of output
```
↗ Progress: 105.65 thousand rows, 93.17 MB (9.87 thousand rows/s., 8.70 MB/s.) ████████▊                                                                    11%
```

**Comment by kovidgoyal** [comment]
This will be because because clickhouse-client is using an incorrect wcwidth() for the spinning arrow character. As per the unicode standard it must be two cells, clickhouse is almost certainly assuming it is one cell. Report it to them

**Comment by kovidgoyal** [comment]
Oh and if they want it to occupy a single cell, they need to output a U+FE0E character after it

**Comment by korjavin** [comment]
Could you please take a look on: https://github.com/ClickHouse/ClickHouse/issues/10189
