### ISSUE TITLE
window zoom refinements

### ISSUE THREAD

**Issue by franco** [kovidgoyal/kitty#2531]
I'm using the [`zoom_toggle.py`](https://sw.kovidgoyal.net/kitty/kittens/custom.html#using-kittens-to-script-kitty-without-any-terminal-ui) kitten suggested in #870 as a workaround for zooming a window. It works fine for me with two small issues:

### Indication for zoomed window
Sometimes, with multiple tabs and zoomed windows, I'm losing track if I'm looking at a zoomed window or a tab with only one window. A visual indicator to distinguish between the two cases would be nice. I was thinking of drawing a border around a zoomed window. Is it possible to extend [`zoom_toggle.py`](https://sw.kovidgoyal.net/kitty/kittens/custom.html#using-kittens-to-script-kitty-without-any-terminal-ui) to draw a border? Or would that need changes to kitty itself?

### Maximize displayed scrollback buffer in zoomed window
Let's imagine a small window with already scrolled up output gets zoomed. I would expect the zoomed window to show as much of the scrollback buffer as possible (same as in tmux). Currently it does not show any additional output form the scrollback history. Any idea how to handle that with a kitten?

**Comment by kovidgoyal** [comment]
Neither of those are addressable in kittens, I'm afraid. For your first request the
easiest way would be to allow tab title templates to accept
{num_of_windows} and {num_of_visible_windows}

For, the second the way scrollback is handled when resizing is my
personal preference, if you want to change it, you will need to add an
option to kitty to control it.

**Comment by kovidgoyal** [comment]
Or for (1) you could add a must draw border option to the stack layout and have your kitten toggle it.
