### ISSUE TITLE
Kitti  minimizes when I'm switching workspaces (Ubuntu xfce)

### ISSUE THREAD

**Issue by idopshik** [kovidgoyal/kitty#2532]
Xubuntu 19.04 disco with XFCE environment.
Kitty 0.13.3
I'm using kitties combination to full-screen, change workspace, go back - kitty is in minimized state.
All other terminals stay in full screen by changing workspaces.

**Comment by kovidgoyal** [comment]
Sorry I cannot reproduce with any window manager at my disposal, and I'm
not installing all of xfce to test it.

**Comment by kovidgoyal** [comment]
And note that kitty contains no code to change its window size or iconification status, after initial window creation. That is coming from the window manager. Why XFCE's window manager does that, I have no clue.
