### ISSUE TITLE
Wrong marker highlight for tabs and emojis

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#2534]
The marker feature treats tabs as one character wide, so if the terminal text contains tabs, the highlight will be offset from the matched text. Can be reproduced by creating the marker `text 1 test` and running `echo -e '\ttest'`, which will look like this:

![image](https://user-images.githubusercontent.com/601966/79057358-f5c11d80-7c60-11ea-8221-1127be5c0468.png)

Or if you match a tab, only one character will be highlighted. Can be reproduced by creating a marker that matches `\t` and running `echo -e '\ttest'`, which will look like this:

![image](https://user-images.githubusercontent.com/601966/79057380-4cc6f280-7c61-11ea-8829-fa9b94925890.png)

Another issue is that if you match an emoji that is two characters wide, only the left of the characters will be highlighted. Can be reproduced by creating the marker `text 1 😂` and running `echo '😂test'`, which will look like this:

![image](https://user-images.githubusercontent.com/601966/79057399-7b44cd80-7c61-11ea-8974-9295a37d04a8.png)

And if you match a character printed directly after an emoji, the highlight will include the right character in the emoji. Can be reproduced by creating the marker `text 1 t` and running `echo '😂test'`, which will look like this:

![image](https://user-images.githubusercontent.com/601966/79057445-eababd00-7c61-11ea-9d15-baf3ce1da212.png)

**Comment by kovidgoyal** [comment]
Yeah this is one the tabled for a rainy day type issues that I did not
have time to work on when implementing the feature. Since someone
noticed it, I will move it up my todo stack.

**Comment by trygveaa** [comment]
Thanks!
