### ISSUE TITLE
EGL: Failed to create context: Arguments are inconsistent

### ISSUE THREAD

**Issue by mb720** [kovidgoyal/kitty#2536]
Hi and thanks for kitty!

When I try to run kitty 0.17.2 on Sway, I get this error:

    [103 10:28:36.031861] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
    [103 10:28:36.039711] Traceback (most recent call last):
      File "/usr/bin/../lib/kitty/kitty/main.py", line 322, in main
        _main()
      File "/usr/bin/../lib/kitty/kitty/main.py", line 315, in _main
        run_app(opts, cli_opts, bad_lines)
      File "/usr/bin/../lib/kitty/kitty/main.py", line 158, in __call__
        _run_app(opts, args, bad_lines)
      File "/usr/bin/../lib/kitty/kitty/main.py", line 131, in _run_app
        window_id = create_os_window(
    ValueError: Failed to create GLFWwindow

**Comment by kovidgoyal** [comment]
That looks like a driver issue. glfw is unable to create a valid OpenGL
context. Do you have working OpenGL drivers??

**Comment by mb720** [comment]
`glxinfo | grep OpenGL version` returns "OpenGL version string: 2.1 Mesa 20.0.4".

I can run a program like `fire` from `mesa-demos`.

**Comment by kovidgoyal** [comment]
kitty needs OpenGL 3.3 at a minimum which is over a decade old at this
point. In fact I am surprised you didnt get a better error message since
IIRC kitty checks the open gl version on startup.

**Comment by mb720** [comment]
Thanks, that's good to know.

I tried `alacritty` on the same machine, it failed with a message that GLSL 3.0 is not supported.

But after reading [this hint](https://github.com/alacritty/alacritty/issues/128#issuecomment-588237461-permalink) on disabling hardware acceleration, I was able to run it with

    env LIBGL_ALWAYS_SOFTWARE=1 alacritty

Is there something equivalent for kitty?

**Comment by kovidgoyal** [comment]
You can use mesa sftware drivers if you like, but performance will be
terrible.

**Comment by jerbaroo** [comment]
`env LIBGL_ALWAYS_SOFTWARE=1 kitty`
