### ISSUE TITLE
Faulty picture display with some pictures if picture is bigger than terminal

### ISSUE THREAD

**Issue by RockyBoulder** [kovidgoyal/kitty#2542]
Hello,

I am new to kitty. Like it so far but have one problem: Some pictures are broken when I use icat.
Only pictures that don't fit in the terminal window are affected. If I resize the terminal so that they fit and do icat again they are displayed correctly. Not all pictures not fitting in the terminal are affected. 
Pictures all do display all right with for expample image magicks display command. 
![wrong](https://user-images.githubusercontent.com/617855/79137352-d9cd9100-7db2-11ea-9e1b-f4c3d9451898.png)

./kitty --version
kitty 0.17.2 created by Kovid Goyal
Package: imagemagick
Version: 8:6.9.10.23+dfsg-2.1
Linux orihime 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by kovidgoyal** [comment]
I'm going to need a way to reproduce. Attach a picture that causes the issue.

**Comment by RockyBoulder** [comment]
![tuuube](https://user-images.githubusercontent.com/617855/79138499-e5ba5280-7db4-11ea-8e76-f7b783fc8338.png)

Sure.

**Comment by kovidgoyal** [comment]
That mess is what imagemagick does when resizing the image. I have no
idea why, not an ImageMagick expert.

**Comment by kovidgoyal** [comment]
To reproduce:

convert kbad.png -resize 20x20\! /tmp/q.rgba
ls -l /tmp/q/rgba

gives a size of 3200 instead of the expected 20x20x4=1600

**Comment by RockyBoulder** [comment]
convert kbad.png -resize 20x20! -depth 8 /tmp/q.rgba
ls -l /tmp/q/rgba 

gives a size of 1600

I tried out a little more myself:
The not working png files are all 16-bit sRGB. Reducing the depth makes them show up non faulty (but naturally with reduced depth).

**Comment by Luflosi** [comment]
You may not have noticed the fix above. 16-bit depth images should work in the latest master now.
