### ISSUE TITLE
Feature request: "ils" thumbnails (icat but to list images)

### ISSUE THREAD

**Issue by z3ch5** [kovidgoyal/kitty#2544]
Thanks for Kitty for being great, as the project describes itself **featureful** , there is a thing that I am really missing in terminals, which is "thumbnails".

icat is great for showing images, but it misses small scripting part to make images listed like **lsix** do, and as I read in https://github.com/kovidgoyal/kitty/issues/2511
Supporting Sixel could not happen in the near future, and I do agree that kitty does indeed great job in showing images, just if you may consider showing thumbnails it would make people not in the need of using a file/folder manager like ranger, and even with ranger, it would be a difficult to show tens of images and it's containts at once.

Expectation:
https://raw.githubusercontent.com/hackerb9/lsix/master/README.md.d/example1.png

PS: I already have seen the project https://pypi.org/project/pixcat/
but it is an extra python library, plus it doesn't show thumbnails with the name of the images under it and to show them in one line under another like lsix do.

**Comment by ctrlcctrlv** [comment]
Sixels aren't required to draw mutliple images at once, Kitty can do so easily with its native protocol.

**Comment by kovidgoyal** [comment]
Someday, sure. In fact the original reason I wrote the graphics protocol
in kitty is to replace https://github.com/kovidgoyal/iv with a terminal
implementation. However, I have no immediate plans to do so.
