### ISSUE TITLE
CTRL-\ sometimes kills the current window/tab

### ISSUE THREAD

**Issue by s1341** [kovidgoyal/kitty#2547]
Sometimes, when hitting ctrl-\ to send a SIGQUIT to the currently running command/application, the kitty window/tab dies instead.

I've been unable to isolate when this happens. Will try to reproduce.

**Comment by kovidgoyal** [comment]
Run kitty from another terminal and see ifsomething is printed to stderr
that will help with diagnostics

**Comment by s1341** [comment]
I don't see anything in the output. I ran xterm, and from there kitty, then hit CTRL-\ a few times.

The thing is that it only happens some of the time.. I'm trying to isolate when...

**Comment by kovidgoyal** [comment]
If you can comeup with a way to reproduce let me know and I will re-open

**Comment by s1341** [comment]
Hi,

I've managed to reproduce this.

Run the following python script:
```
import time
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    time.sleep(5)
```

Then hit `ctrl-d` followed immediately by `ctrl-\`. Your kitty session will exit.

Expected behavior is that the python instance will quit.

If you give me some pointers I can try to debug this myself.

**Comment by kovidgoyal** [comment]
Doesn't reproduce for me, steps I tried:

Save yoru script as t.py
python t.py
Press ctrl+d
Press ctrl+\

zsh reports 
zsh: quit (core dumped)  python t.py

As expected, since ctrl+\ causes SIGQUIT to be sent to running program.

**Comment by s1341** [comment]
hrm... It seems to work fairly consistently for me. I'm running nixos... maybe I should try on ubuntu...

**Comment by kovidgoyal** [comment]
what exit code is kitty quitting with?

**Comment by martinetd** [comment]
Also what shell are you using? That plays a big part in handling ctrl+\...

**Comment by s1341** [comment]
Of course I can't get it to reproduce anymore... it worked consistently this morning. I'm using zsh. Will try to get the exit code.
