### ISSUE TITLE
Fira Code v3 is not recognised by kitty

### ISSUE THREAD

**Issue by ysooqe** [kovidgoyal/kitty#2549]
I just updated Fira Code to the latest version 3 and for some reason, it is now not recognized by kitty anymore.

When doing `kitty list-fonts` it does not show up. Doing `fc-list : family spacing | grep -e spacing=100 -e spacing=90` as suggested by the kitty FAQ, Fira Code will not be listed here either.

I am not sure what additional information I could or should provide, please let me know if anything else is needed.

**Comment by trygveaa** [comment]
This is an issue in the font: https://github.com/tonsky/FiraCode/issues/1000

**Comment by ysooqe** [comment]
Thanks for pointing this out! I am sorry for opening the issue here, therefore I think it can be closed.

**Comment by kovidgoyal** [comment]
That means fira code is no longer a monospaced font. kitty can only use
monospaced fonts as its main font. You should open a bug report with
fira code and ask if the change is intentional.
