### ISSUE TITLE
feature request: add OS window position to kitty @ ls

### ISSUE THREAD

**Issue by eraserhd** [kovidgoyal/kitty#2552]
Rationale: I'm moving from tmux to kitty+yabai using OS windows only, and one of my normal mappings, `C-w ,`, sends `C-p Enter` to the window in the lowest, rightmost corner.  This is useful for running unit tests or rerunning a shell command, for example.

In order to implement this, I need to discover which window is in the bottom right corner.

I can ask yabai, but this only works if the asker is local, and I'm often SSH'd into a server for development.

An alternate approach would be some kind of terminal escape with a payload that I can handle with a shell command locally.

Thoughts?

**Comment by kovidgoyal** [comment]
This is a bit of a crap shoot. The problem is that not all platforms
make this information available. For instance, on Wayland, applications
are not allowed to query the system for their own window positions.

**Comment by eraserhd** [comment]
This looks nice, thank you!

**Comment by eraserhd** [comment]
I'm just getting to using this, and I can't figure out a way to get an OS window ID or handle.  (This is Mac OS.)

So, I can get any process's Kitty window ID, and I can make the kitten that asks yabai for all the window positions, but I can't match up window positions to Kitty windows:

1. Kitty is the process for all the windows, so I can't match the window by process id.
2. Kitty window ids appear to be unrelated to OS window IDs, so I can't use that.
3. This leaves title, but title is often the same for me for several windows.

The best option I can think of is to add a unique cookie to every window title to make them unique.  I actually want my windows numbered by position (a separate idea), but I need two passes:

1. Make sure all windows have unique titles.
2. Get all window positions.
3. Renumber windows based on positions.

Thoughts?

**Comment by kovidgoyal** [comment]
The output of kitty @ ls will tell you the kitty os window id for any
given kitty window id. Each entry in the ls output is of the form

{
'id': XXX # this is the OS window id
'tabs': [
  'id': XXX # this is the tab id
  'windows': [
     'id': XXX # this is the window id

**Comment by eraserhd** [comment]
It doesn't look like the OS window id on Mac OS:

```
$ kitty @ ls | jq '.[].id'
1
2
3
4
5
6

$ yabai -m query --windows | jq '.[].id'
9628
9592
9480
9555
9458
9516
9051
8333
236
179
187
11704
11701
198
```

**Comment by kovidgoyal** [comment]
This is kitty's internal id for the OS window, kitty has no information
about what ids external programs assign to windows. If you are asking
how to figure out which kitty window id is which yabai window id, I have
no clue. On linux you'd use the --class property to give os windows
identifiers that you can refer to in other programs. I dont think macOS
has any similar concept.

**Comment by eraserhd** [comment]
After a bit of digging, yabai is using Mac OS's accessibility system id for the window, which is obtained by a private API.

**Comment by eraserhd** [comment]
@kovidgoyal would you be fundamentally opposed to publishing this ID in the `ls` JSON?  The draw back would mean that kitty could not be allowed in the App Store with this API call in it.

**Comment by kovidgoyal** [comment]
Well if there is a reasonable way to get that number in kitty, I can put
it into an env var, just like WINDOWID under X11.

**Comment by eraserhd** [comment]
Oh, nice!  I'll investigate and make a PR.

**Comment by kovidgoyal** [comment]
Oh and while I dont care, at all, about the app store, kitty must still pass notarization. I dont recall what the deal with notarization and private APIs is, if they prevent kitty from being notarized, I will have to remove them.

**Comment by eraserhd** [comment]
I think that will prevent using this API, but I'll double-check on that and also see if there's another way to get it.

**Comment by koekeishiya** [comment]
What you want is [my_window windowNumber] where my_window is of type NSWindow.

**Comment by kovidgoyal** [comment]
At least from the cocoa docs windowNumber is process internal cannot be
used for cross process communication.
https://developer.apple.com/documentation/appkit/nswindow/1419068-windownumber
