### ISSUE TITLE
CLI TAB completion ?

### ISSUE THREAD

**Issue by philiprhoades** [kovidgoyal/kitty#2553]
People,

Kitty looks very nice and I think might solve some of my annoyances with other software but I seem to have a problem straight away which looks to be an odd issue given how sophisticated Kitty seems to be:

Iin all other environments that I use (xfce4-terminal, mrxvt, xterm etc) I can make use of "TAB Completion" to type part of a name of a command or file name in the current dir to finish the word instead of typing the whole line - this greatly speeds up CLI stuff but it doesn't seem to work in Kitty?  I couldn't find any config stuff that looked related and no other issues here seems to cover my problem - am I missing something?

Thanks,
Phil.

**Comment by kovidgoyal** [comment]
Completion for the command line is performed by the shell you run in the
terminal, not the terminal itself. Most likely some misconfiguration in
your shells startup files. Run it with empty startup files and bisect to
find the problem.

**Comment by philiprhoades** [comment]
@kovidgoyal , thanks for that - I thought it had to be a Kitty problem because my other terminal emulators have never had that problem.

After a fair bit of messing around I eventually found it was due to:

  .inputrc

which has in it:

  set keymap vi
  set editing-mode vi

- which I really want to keep . . is there a work-around I could use?

Thanks.

**Comment by kovidgoyal** [comment]
I dont know what vi mode would have to do with tab completion. And I dont use bash, but I can tell you that completion works fine in zsh with vi mode enabled, which I use personally.

**Comment by philiprhoades** [comment]
@kovidgoyal ,

You're right - this is weird - I created a new user iwth my .bash_profile, .bashrc and .inputrc and that works fine . .  So I went back to my setup and it appears the problem is related to the Kitty session file I have started to create as a replacement for the mrxvt session I currently have - if I start Kitty without the session, TAB Completion works fine . . if I start Kitty with "--session current" I get the problem . . I don't know what it going on . . I will look at zsh now anyway (I have been meaning to do it for decades now . .) but here is the session file as it is currently in case there is anything that you can see - but I still don't know why there should be that weird interaction with .inputrc . . :

```
title phr
os_window_size 180c 50c                                                                                                 
cd ~
launch sh

new_tab newsbeuter                                                                                                      
cd ~/.newsbeuter                                                                                                        
enabled_layouts tall, stack                                                                                             
launch /usr/bin/newsbeuter                                                                                              

new_tab Bookmarks                                                                                                       
cd /home/phr/0_Bookmarks                                                                                                
launch sh
 
new_tab Tabfern                                                                                                         
cd /home/phr/0_TabFern                                                                                                  
launch sh

new_tab vimwiki" 
cd /home/phr/vimwiki
launch sh

new_tab txts
cd /home/phr/txts                                                                                                       
launch sh                                                                                                               

new_tab phr
cd /home/phr
launch sh

```

**Comment by trygveaa** [comment]
The reason it's not working is probably because you're launching `sh` instead of `bash`. Just drop all the `launch` lines, and kitty will use your default shell which should work.

**Comment by philiprhoades** [comment]
> The reason it's not working is probably because you're launching `sh` instead of `bash`. Just drop all the `launch` lines, and kitty will use your default shell which should work.

Ah! - that makes sense - I will have a look at that . .

Thanks!

**Comment by philiprhoades** [comment]
@trygveaa ,

Deleting the laucnh lines causes the tabs not to be created but launching bash instead of sh works . . introduces a different issue which I will post separately if I can't sort it out . . 

Thanks!

**Comment by trygveaa** [comment]
Right, removing `launch` entirely was wrong. Just using `launch` without any arguments is the correct thing when you want a shell.

**Comment by philiprhoades** [comment]
Ah - good to know.

Thanks.

**Comment by mcourteaux** [comment]
For me, it was the terminal-bell, while my pulseaudio server died. Kitty freezes when trying to play the bell sound. Your other terminals don't bell, or do it in a separate thread.

**Comment by weynhamz** [comment]
Had the same issue, it turns out, Kitty's default SHELL integration is messing up with it, after adding below to 'kitty.conf' and relaunching Kitty, it works.

```
shell_integration disabled
```
