### ISSUE TITLE
Possible to swap cmd and ctrl on OSX in Kitty?

### ISSUE THREAD

**Issue by DanielPower** [kovidgoyal/kitty#2555]
I'm a Linux user, but am required to use OSX for work. Because in most keybindings on osx use cmd in place of ctrl, I've swapped the two keys in the OS settings so that my keybindings would behave more closely to those on my Linux systems.

Unfortunately, the exception to this is in terminal applications, where I actually want the ctrl key to be ctrl. iTerm has the ability to remap modifier keys, so I'm wondering if kitty has a similar feature? I mainly just want to have kitty interpret ctrl as cmd, and cmd as ctrl.

**Comment by kovidgoyal** [comment]
I'm afraid not, it should be a fairly easy patch however, PRs are
welcome, for remapping of modifiers.

**Comment by flowchartsman** [comment]
#1077
