### ISSUE TITLE
htop not working

### ISSUE THREAD

**Issue by TadielloM** [kovidgoyal/kitty#2556]
I'm trying to use htop on kitty but it is not working.
When I try to run it I get
```Error opening terminal:  xterm-kitty```
I've checked the TERM and TERMINFO variables and they point to the right position. 
I've checked on the FAQ but it does not seem to be a problem of sudo.
What can I do to solve this?
I'm running Ubuntu 18.04 and I followed the manual installation for installing kitty.
```kitty --version
kitty 0.17.2 created by Kovid Goyal```

Thanks in advance

**Comment by ctrlcctrlv** [comment]
Do you actually have the terminfo installed, though? It's not enough to have the environment variables correct if that's not the case.

**Comment by kovidgoyal** [comment]
Run infocmp if it successfult prints out the kitty terminfo, the terminfo is installed and available, and this sisue is some problem with th encurses library linked into htop. If not, then install the kitty terminfo system wide to be safe, althogh for normal use you dont need to do this.

**Comment by TadielloM** [comment]
Thanks for your help.
I solved adding
 
```export $TERM="xterm-256color"```

to my .bashrc file.

**Comment by erlangparasu** [comment]
`export TERM="xterm-256color"`
