### ISSUE TITLE
feature request: listen_on config file option

### ISSUE THREAD

**Issue by eraserhd** [kovidgoyal/kitty#2557]
Rationale: I'm on Mac OS X, and I want to add `--listen-on`, but if I start kitty from the command-line instead of from the application bundle, it doesn't play well with the OS (the title bar isn't the correct color, but an old default, and yabai doesn't seem to be able to manage the windows correctly).  I want to control kitty from outside a terminal session, specifically from `skhd`, a hotkey daemon.

Also, I failed to mention last time that I'm willing to do the work.

**Comment by Luflosi** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos is probably what you're looking for.

**Comment by eraserhd** [comment]
Oh, this works!  Thanks.
