### ISSUE TITLE
Are kittens support find text capabilities at scroll buffer and if needed to scroll to find text?

### ISSUE THREAD

**Issue by vkravets** [kovidgoyal/kitty#2558]
Are kittens support the find text at  scroll buffer and scroll to it? If yes where I can found the examples of it?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/#the-scrollback-buffer

https://sw.kovidgoyal.net/kitty/marks.html

https://sw.kovidgoyal.net/kitty/kittens/custom.html
