### ISSUE TITLE
In a session, exiting the launched program closes the tab . . how can it just exit to a shell?

### ISSUE THREAD

**Issue by philiprhoades** [kovidgoyal/kitty#2559]
People,

I have this in session file:

```
new_tab newsbeuter                                                                                                      
cd ~/.newsbeuter                                                                                                        
enabled_layouts tall, stack                                                                                             
launch /usr/bin/newsbeuter
```

I would like to be able to exit the newsbeuter program but NOT close the tab after the exit (so I can do something else - in this case, edit the newsbeuter urls file and restart the newsbeuter program) and be left at a shell prompt - is this possible?  I tried a few things that didn't work . . 

Thanks,
Phil.

**Comment by kovidgoyal** [comment]
Open a new window before closing the newsbeauter one. Or run newsbeuter
form a shell script that launches a shell after it exits.

**Comment by philiprhoades** [comment]
> Open a new window before closing the newsbeauter one. Or run newsbeuter
> form a shell script that launches a shell after it exits.

Both those options would create a new window at the end of the existing row of tabs (ie in a different postition from the original tab) I think - I want to keep the window open on the current tab in its current position relative to the other tabs . . I can currently do this with mrxvt but that software's other limitations have become to much to continue to put up with . .

Thanks.

**Comment by trygveaa** [comment]
Do `launch bash -c "newsbeuter; bash"`.

**Comment by philiprhoades** [comment]
> Do `launch bash -c "newsbeuter; bash"`.

Ah! - perfect! - thanks.  Now I think I have everything that I could do in my mrxvt sessions - plus all the niceness of Kitty!  I am still getting a warning / error message - I think to do with my session file again - but I will post a note about that seprarately.

**Comment by hankyusa** [comment]
For those using ZSH, I found that I needed to use ` -o interactive`.

```
launch zsh -o interactive "newsbeuter; zsh"
```
