### ISSUE TITLE
[108 12:27:14.454660] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: '' and parameters: '0 2'

### ISSUE THREAD

**Issue by philiprhoades** [kovidgoyal/kitty#2560]
People,

This must be another session file issue - I don't get this error message if I don't start a session - I include the current session file (more expansion of tabs to follow) - any suggestion about what this problem is? - how to resolve it?

Thanks,
P.

```
title phr
os_window_size 180c 50c
cd ~
launch bash

new_tab newsbeuter
cd ~/.newsbeuter
enabled_layouts tall, stack
launch bash -c "newsbeuter ; bash"

new_tab Bookmarks
cd /home/phr/0_Bookmarks
launch ./0.sh
 
new_tab Tabfern
cd /home/phr/0_TabFern
launch bash

new_tab vimwiki
cd /home/phr/vimwiki
launch v index.wiki

new_tab txts
cd /home/phr/txts
launch bash

new_tab phr
cd /home/phr
launch bash
```

**Comment by kovidgoyal** [comment]
Its not a problem. It means one of the programs you are running is using
a escape code kitty does not support.
