### ISSUE TITLE
Is it possible to save a new running kitty environment as a new session?

### ISSUE THREAD

**Issue by philiprhoades** [kovidgoyal/kitty#2561]
People,

I couldn't find a reference to this possibility - it would be nice when working on a project with a set of tabs in a Kitty window (set of windows in a new session?) to save it as a new session - to easily come back to where I left off some time previously . .

Is it possible somehow?

Thanks,
Phil.

**Comment by kovidgoyal** [comment]
dup of #1197

saving/restoring state is the same thing
