### ISSUE TITLE
Visual artefacts after changing layouts

### ISSUE THREAD

**Issue by LkeMitchll** [kovidgoyal/kitty#2562]
I am seeing visual artefacts between window splits after changing the layout:

**Screenshot:**
<img width="1377" alt="Screenshot 2020-04-17 at 10 42 15" src="https://user-images.githubusercontent.com/1729878/79555893-332a0e80-8098-11ea-9973-68ca8c33090b.png">

**GIF:**
![kitty](https://user-images.githubusercontent.com/1729878/79556116-89974d00-8098-11ea-8d26-96835b708cbf.gif)

**Steps to reproduce:**
- Open more than one window
- Change layouts (using kitty_mod+l)

**Quirks**
- This seems to occur moving between the "tall" and "fat" layouts. 
- It also seems to occur in both windowed and fullscreen mode. 
- It doesn't seem dependant on font.
- Fix: Resize kitty window

**Minimal kitty.conf to reproduce:**
```
window_margin_width    15
enabled_layouts    tall,fat
```

**Information:**
- OS: macOS 10.15.4
- Kitty: v0.17.2
- Full kitty.conf: [GitHub](https://github.com/LkeMitchll/Dotfiles/blob/master/config/kitty/kitty.conf)

**Comment by kovidgoyal** [comment]
It doesnt reproduce for me. But in any case I am currently in the process of rewriting the layout code to enable per window margin/padding settings and also changing how the blanks between windows are cleared. So I suggest wait for the next release and update this bug report if it is still an issue. (or wait till I commit the changes and test from master)

**Comment by kovidgoyal** [comment]
The changed layout code is now committed to master.

**Comment by LkeMitchll** [comment]
> The changed layout code is now committed to master.

@kovidgoyal This has now fixed the issue, thanks!
