### ISSUE TITLE
Documentation for restoring shell signal commands

### ISSUE THREAD

**Issue by s0merando** [kovidgoyal/kitty#2563]
Hello,

I am new to kitty and I am having a hard time figuring out how to restore standard shell interrupts and bash shortcuts: ctrl-z, ctrl-c, ctrl-d, and for bash/zsh: ctrl-a return to beginning og line, ctrl-e end of line, and ctrl arrow keys for word skipping. I have figured out:

map kitty_mod+c send_text all \x03 

which works for ctrl-c but the rest of the signals I am not able to get to work with this method.

Full disclosure I am using zsh with oh-my-zsh and also like to use tmux, I know kitty also allows split screens but I am not able to find how to set those options. 

Thank you for this wonderful terminal emulator and reading my annoying bug request.

**Comment by kovidgoyal** [comment]
You dont need to map those, they work out of the box. Just make sure
TERM is xterm-kitty and not something else.

**Comment by s0merando** [comment]
I confirmed that I cannot get these shortcuts to work on the latest versio of kitty. I am using the example config file from https://sw.kovidgoyal.net/kitty/conf.html?highlight=config#shortcut-kitty.Edit%20config%20file

and I have these term env variables:

GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/qterminal.desktop
TERM=xterm-kitty
TERMINFO=/home/a/.local/kitty.app/lib/kitty/terminfo

I cannot execute ctrl-a to return cursor to the shell prompt or ctrl-e to end of prompt buffer. Word jumping by arrow keys does not work but ESC-b/ESC-f works.

**Comment by kovidgoyal** [comment]
Use an empty zshrc and you will be fine. Something in your zshrc is breaking it.
