### ISSUE TITLE
Documentation is terse for ssh examples

### ISSUE THREAD

**Issue by s0merando** [kovidgoyal/kitty#2564]
I understand that ssh connections can be evoked with 

kitty +kitten ssh

But on the documentation site the explanations are not descriptive of how or why to do this, some examples:

"Can be controlled from scripts or the shell prompt, even over SSH."

"Note that in the example’s above, kitty @ messaging works only when run inside a kitty window, not anywhere. But, within a kitty window it even works over SSH."

"It supports all image types supported by ImageMagick. It even works over SSH. For details, see the kitty graphics protocol."

"Allow other programs to control kitty. If you turn this on other programs can control all aspects of kitty, including sending text to kitty windows, opening new windows, closing windows, reading the content of windows, etc. Note that this even works over ssh connections."

And presumably the page that should be the source of how to do this is https://sw.kovidgoyal.net/kitty/remote-control.html but it has no further examples of using the ssh kitty than the unix socket file.

I would like to see 2-4 of the most common examples of the expected commands of how this is expected to work since "even over ssh" is not very explanatory.  Thank you for responding to this low priority, dumb user request.

**Comment by kovidgoyal** [comment]
You dont need to use the ssh kitten for remote control. It exists only
for this reason: https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer
