### ISSUE TITLE
Feature Request: URL copy option in additon to opening it

### ISSUE THREAD

**Issue by Ramkumar47** [kovidgoyal/kitty#2566]
Dear Kovid Goyal,
You have developed an excelent terminal emulator! .. it has 99% all the features i needed. Just today i moved to **kitty**. One feature i would like Kitty to have is the ability to **copy url** in addition to opening it in web browser, because, if one has to copy url, he has to use Ctrl+Shift+E and can select url with corresponding number, then it will open in browser, from there only he can copy url. Another way would be to use scrollback_buffer directed to vim instead of less and a search and highlight will do.. 
If kitty has this url-copy feature, then it will be the 100% satisfied terminal to all!

also one more thing, i dont know whether kitty has it already. When i open a new window or tab from kitty, i would like it to open in the same working directory.. if it already has, plz let me know how to get that.. if not, plz add such feature to make Kitty irresistible by power users..

Thanks a lot to provide us such powerfull terminal!

**Comment by kovidgoyal** [comment]
Already has both those features, read the documentation.

**Comment by Ramkumar47** [comment]
hi, i figured out how to open new window with current working directory with 
`map ctrl+shift+enter launch --cwd=current`
but i am unable to do for new tabs and new os window... need help on that..

also unable to copy url with Ctrl+Shift+e option, only opens in browser.. currently using scrollback buffer on Vim (changed to vim from less) to copy url.. need help on this as well

here is my configuration for cross-checking: [kitty.conf](https://gofile.io/?c=RH7kYo)

**Comment by trygveaa** [comment]
Isn't the documentation pretty clear on both of these things?

From https://sw.kovidgoyal.net/kitty/launch.html:
> To open the new window in a new tab:
> ```map f1 launch --type=tab```

From https://sw.kovidgoyal.net/kitty/kittens/hints.html:
> ```--program <PROGRAM>```
> What program to use to open matched text. Defaults to the default open program for the operating system. Use a value of - to paste the match into the terminal window instead. A value of @ will copy the match to the clipboard. A value of * will copy the match to the primary selection (on systems that support primary selections). A value of default will run the default open program. Can be specified multiple times to run multiple programs.

Have you read this?

**Comment by Ramkumar47** [comment]
Ah right, thanks

**Comment by duganchen** [comment]
map ctrl+shift+p>d kitten hints --program @ --type url

**Comment by debajit** [comment]
For anyone who is looking for a ready reference or example, here is the shortest way to bind a key to copy a URL:

```bash
map ctrl+shift+y kitten hints --program "@" 
```

This is documented in https://sw.kovidgoyal.net/kitty/kittens/hints/
