### ISSUE TITLE
icat not working over SSH

### ISSUE THREAD

**Issue by jubame** [kovidgoyal/kitty#2568]
icat does not work over SSH for me. This is the output:
```
[test@localhost ~]$ kitty +kitten icat image.png 
^[_Gi=1;OK^[\This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it
[test@localhost ~]$ kitty +kitten icat image.png 
                                                                  
[test@localhost ~]$ kitty +kitten icat image.png 
This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it
```
As can be seen above, sometimes I get an error message, other times an empty line.
It works fine locally.

kitty version: 0.17.2 on both my PC and server
OS: Fedora 31 on both my PC and server
I have no kitty config files

**Comment by kovidgoyal** [comment]
I'm going to need some way to reproduce your problem "does not work over
ssh" is insufficient, since it definitely does work over ssh. Make sure
you are not running tmux or screen or something of the sort. Make sure
your TERM is set correctly to xtem-kitty and you have either used the ssh
kitten or otherwise made the kitty terminfo files available on the
server.

**Comment by jubame** [comment]
I have previously done `kitty +kitten ssh test@192.168.1.31
`and terminfo file is present:
```
[test@localhost ~]$ ls -l ~/.terminfo/x/xterm-kitty
-rw-rw-r--. 1 test test 2197 Apr 18 19:11 /home/test/.terminfo/x/xterm-kitty
```
TERM variable seems fine:
```
[test@localhost ~]$ echo $TERM
xterm-kitty
```
I am not running under tmux or screen.

**Comment by kovidgoyal** [comment]
OK, I'll take a look when I have a moment.

**Comment by jubame** [comment]
Thank you. I have built from source and now it works.

**Comment by hongquan** [comment]
Could you please show me example on how to use `icat` with SSH? Does "kitty" need to be installed on remote machine?

**Comment by kovidgoyal** [comment]
Yes, it does. Since icat is a program that is part of kitty. Otherwise
write your own script to do it, using the graphics protocol:
https://sw.kovidgoyal.net/kitty/graphics-protocol.html

**Comment by kovasap** [comment]
I just ran into this same problem with kitty 0.19.3.  
```
> icat file.png
This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it
> echo $TERM
xterm-kitty
> ls -l ~/.terminfo/x/xterm-kitty
-rw-r--r-- 1 kovas primarygroup 2197 Mar 10 10:27 /home/kovas/.terminfo/x/xterm-kitty
```
I'm not running under tmux or screen.

**Comment by kovidgoyal** [comment]
Then what are you running, because you have to be running something that
is filtering out the graphics protocol escape codes between the client
and the terminal emulator.

**Comment by rickalex21** [comment]
I'm getting the same error ssh from windows to Linux, not sure why it does not work via ssh.
I also tried with default settings for fish shell.

**Comment by cpbotha** [comment]
I just ran into similar unexpected behaviour, but then @kovidgoyal 's comment made me think about my tailscale-ssh...

I've now experimentally discovered that when I ssh to a machine on my local network, from kitty 0.36.4 using kitten ssh, but via tailscale ssh, I get the error message `Error: Terminal does not support reporting screen sizes in pixels, use a terminal such as kitty, WezTerm, Konsole, etc. that does.` when I try to `kitten icat some_image.jpg`

However, when I do the exact same thing, except via ssh to the machine's local, non-tailscale-IP, I can display the exact same image without any issues.

**Comment by kovidgoyal** [comment]
Presumably tailscale is using its own pseudo terminal implementation, and has
failed to set the ws_pixel fields in the struct winsz. Report it to
them.

**Comment by cpbotha** [comment]
Thanks @kovidgoyal !

I have reported to the tailscale folks at https://github.com/tailscale/tailscale/issues/13669

I'm sorry, my error message is not exactly the same as that of the reporter. However, this part of the thread could help other tailscale users.
