### ISSUE TITLE
Crash if I hit Command-V

### ISSUE THREAD

**Issue by sbeldekov** [kovidgoyal/kitty#257]
I have tried 0.6.1
Every time I press Command-V to paste the clipboard content the kitty crashes

[cmd-v.txt](https://github.com/kovidgoyal/kitty/files/1591216/cmd-v.txt)

**Comment by kovidgoyal** [comment]
That's a crash inside Apple's CoreFoundation libraries. Not sure what Ic an do about it. Does it happen if you use the default shortcut for paste, ctrl+shift+v?

**Comment by sbeldekov** [comment]
ctrl+shift+v works perfect
but sometimes I use cmd-v by force of habit

**Comment by kovidgoyal** [comment]
Have you actually mapped cmd-v to paste in kitty.conf or are you just pressing it by accident?

**Comment by sbeldekov** [comment]
I have not mapped anything in kitty.conf

**Comment by kovidgoyal** [comment]
Hmm well I cant reproduce the segfault with or without mapping cmd-v. And given that it is happening inside CoreFoundation, I hae no way of debugging it either, so I'm afraid this is a wontfix.
