### ISSUE TITLE
[Clarification] Is there a delay on the --title flag?

### ISSUE THREAD

**Issue by bbaserdem** [kovidgoyal/kitty#2570]
I have been having a minor issue with kitty. I am running bspwm; which I can define rules for windows upon generation. I have a ruleset that applies to any window with the `WM_NAME` of `Dropdown terminal`.

The ruleset applies when I use it with other terminals (`alacritty --title 'Dropdown terminal'`, `termite -t 'Dropdown terminal`). However; the ruleset does not apply to kitty. (When I run `kitty --title 'Dropdown terminal'`; the ruleset with window title is not recognized.)

Since bspwm applies rules on window generation; i was wondering if there is a (possibly miniscule enough that I can't determine) delay between setting of title and window launching. I want to test this; but I don't know how to test it myself.

* OS: Archlinux (5.6.4-arch1-1)
* Kitty: version 0.17.2

I can employ a workaround; it's not a problem or a bug report. However; I'm curious as to why my specific workflow does not work for kitty terminal only.

**Comment by kovidgoyal** [comment]
And note that you should really not use window title for this. Use
WM_CLASS instead which you can set with --class

**Comment by bbaserdem** [comment]
Very fast response; thank you.

I changed my script to use your suggestion and works well.
