### ISSUE TITLE
Alt+Shift change keyboard layout not working

### ISSUE THREAD

**Issue by paraduxos** [kovidgoyal/kitty#2571]
I have 2 keyloard layout: `english` and `thai`
I use `Alt + Shift` to toggle between layout
It work well with every application eg. `firefox`, `xfce4terminal`

This is my `i3 config`
```conf
set $mod Mod4

exec_always --no-startup-id setxkbmap -model pc105 -layout us,th -option grp:alt_shift_toggle
```

When i press `Alt + Shift` in `kitty`, it has weird behavior
- On `polybar` sometimes layout is switched, sometimes it's not.
- More importantly, even if the layout on `polybar` has switched to `thai` layout,
it still produce english character on `kitty` when I type.

I use `Debian 10`
I use the default `kitty config`, except the `font`.

I'm not sure, if this happen because of some key combination in kitty, but I can't find something similar in my config file?

**Comment by kovidgoyal** [comment]
dup of #2519

**Comment by paraduxos** [comment]
After read your reply, I try uninstall `kitty` by `sudo apt remove kitty`.
Then I `build from source`

This is build files I downloaded
`glfw.c` is the same with  [https://github.com/kovidgoyal/kitty/pull/2527/files](https://github.com/kovidgoyal/kitty/pull/2527/files)
```c
// line 623
   if (xkb_sym == XKB_KEY_ISO_First_Group || xkb_sym == XKB_KEY_ISO_Last_Group || xkb_sym == XKB_KEY_ISO_Next_Group || xkb_sym == XKB_KEY_ISO_Prev_Group || xkb_sym == XKB_KEY_Mode_switch) {
      return;
```

And from [https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/xkeyboard-config-2.29/symbols/group](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/xkeyboard-config-2.29/symbols/group)
```bash
partial modifier_keys
xkb_symbols "ralt_rshift_toggle" {
    virtual_modifiers Alt;
    key <RALT> {
        symbols[Group1] = [ NoSymbol, ISO_Next_Group ],
        virtualMods= Alt
    };
    key <RTSH> {
        type[Group1]="PC_ALT_LEVEL2",
        symbols[Group1] = [ Shift_R, ISO_Next_Group ]
    };
};

partial modifier_keys
xkb_symbols "alt_shift_toggle" {
    include "group(lalt_lshift_toggle)"
    include "group(ralt_rshift_toggle)"
};
```

And this
```shell
~$ kitty --debug-keyboard
Press xkb_keycode: 0x40 clean_sym: Alt_L composed_sym: Alt_L mods: none glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press xkb_keycode: 0x32 clean_sym: Shift_L composed_sym: ISO_Next_Group mods: alt glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
Release xkb_keycode: 0x40 clean_sym: Alt_L mods: alt glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: RELEASE mods: 0x4 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release xkb_keycode: 0x32 clean_sym: Shift_L mods: none glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

**Comment by kovidgoyal** [comment]
Your layout being switched or not has nothing to do with kitty, since that is implemented by the X server. As for the key still having an effect in kitty, that is precisely what was addressesed in #2527 if it is not working for you followup on that pull request.
