### ISSUE TITLE
Terminal not updated when SSHing and other odd behaviour

### ISSUE THREAD

**Issue by keshto** [kovidgoyal/kitty#2572]
When SSHed in to my server (OpenSSH_8.2p1 Debian-4, OpenSSL 1.1.1f), the prompt does not seem to fully inherit .bashrc. The `ls --color` alias defined works, but the prompt itself is not colorized `user@host:CWD$` (it is with gnome-terminal).
When pressing the up key, the last command is displayed but after what is already on the prompt. Example if `cat .bashrc` was the last and I have `ls` on the prompt and press up I get `lscat .bashrc` as opposed to just the last command. Pressing enter does indeed invoke the `cat .bashrc` it is just not updated for me. Similarly, pressing backspace will just add a space after the whatever is currently typed (on the prompt), but is indeed sending the backspace to the sever.

```
 $ stty -a
speed 38400 baud; rows 36; columns 142; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
ctrl+v then backspace shows `^?` so that all appears fine.

Note: this is running without any changes on Void using Kitty version `kitty 0.17.2 created by Kovid Goyal`

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by keshto** [comment]
Thanks. Some suggestions;
1. Maybe rename that FAQ header to something similar "Problems when SSHing" or something.
2. https://github.com/alacritty/alacritty/issues/3606 any reason why this is not mentioned. I know setting TERM might have unwanted behavior, but xterm is quite universal and for the most part just works.

Thanks again

**Comment by kovidgoyal** [comment]
Because changing TERM is an extremely bad idea that will break things ranging from keypresses to colors to lots of other things.
