### ISSUE TITLE
Render error with neovim

### ISSUE THREAD

**Issue by ggsalas** [kovidgoyal/kitty#2574]
Hi, I see a render problem using neovim. Frecuently I see render problems like this 
![kitty bug render](https://user-images.githubusercontent.com/8403993/79891984-124c1b00-8402-11ea-9a3a-3807d57b8fe6.gif)

Some time ago [I have reported a similar bug](https://github.com/kovidgoyal/kitty/issues/1811), but is difficult to me debug the error.

Thanks!

**Comment by kovidgoyal** [comment]
Im afraid I cannot help without a minimal test case. This could be caused by pretty much anything. I told you how to generate a minimal test case in your previous bug report. If something in those instructions in unclear, let me know and I will explain further. And fele free to post on closed issues if you have new information.

**Comment by ggsalas** [comment]
can you give me a step guidance for debug this?

**Comment by ggsalas** [comment]
I have started kitty with `kitty --dump-commands` and I see this error (kitty is with nvim, at the bottom)
![image](https://user-images.githubusercontent.com/8403993/79899222-cbafee00-840c-11ea-9534-bc3537d98267.png)

**Comment by kovidgoyal** [comment]
Redirect the output of --dump-commands to a file. Performa  minimal set
of steps to create the error. Close kitty. Now run

kitty --replay-commands filename

inside a new kitty terminal. see if the error is recreated.

Now open the file in an editor and delete as many lines as you can while
making sure the error is still re-created. This will require some back
and forth and trial and error, you will likely need a few hundred lines
at the top and then remove a bunch in the middle and so on.

**Comment by ggsalas** [comment]
The error I see is not related to 1 file. This error is random and happens most frequently when I'm navigating into the project between files. I'm using[ coc plugin for neovim](https://github.com/neoclide/coc.nvim) that's redraws the screen a lot. Some times I see a minimal bug, and on others I see a big bug (like the video I posted here).

That's why  I'm not sure on how to test this error with 1 only file. 

I'm guessing that probably is a performance/redraw problem. I'm not sure what is the most safe configuration. Yesterday I have the default, today I cahange by:
```
input_delay 6
sync_to_monitor yes
```

Let me know if I can try with other configuration or if I can use the dump commands with many files in some way.  Thanks.

**Comment by kovidgoyal** [comment]
debugging it has nothing to do with files. What you need to do is

1) Find a minimal set of steps to reproduce it
2) run kitty with --dump-commands and perform the steps from (1)
3) edit the file produced by --dump-commands deleting as many commands
as possible in a way that preserves the problem with you rerun the file
produced by --dump-commands using --replace-commands

**Comment by ggsalas** [comment]
I have tried and ATM I can't reproduce the error. The only strange thing I see on the console while I'm using kitty with --dump-commands is this: 
```
[113 11:23:45.202069] No render frame received in 0.25 seconds, re-requesting at: 211.991120
[113 11:23:56.638801] No render frame received in 0.25 seconds, re-requesting at: 223.428377
[113 11:24:06.084601] No render frame received in 0.25 seconds, re-requesting at: 232.874179
[113 11:24:07.104743] No render frame received in 0.25 seconds, re-requesting at: 233.893577
[113 11:24:08.234649] No render frame received in 0.25 seconds, re-requesting at: 235.023101
[113 11:24:08.883343] No render frame received in 0.25 seconds, re-requesting at: 235.672927
[113 11:24:24.136786] No render frame received in 0.25 seconds, re-requesting at: 250.926361
[113 11:24:55.550682] No render frame received in 0.25 seconds, re-requesting at: 282.339497
[113 11:24:57.033891] No render frame received in 0.25 seconds, re-requesting at: 283.823473
[113 11:24:58.199853] No render frame received in 0.25 seconds, re-requesting at: 284.988333
[113 11:25:04.033085] No render frame received in 0.25 seconds, re-requesting at: 290.821252
[113 11:25:09.279122] No render frame received in 0.25 seconds, re-requesting at: 296.067479
[113 11:25:15.838499] No render frame received in 0.25 seconds, re-requesting at: 302.628078
[113 11:25:25.369848] No render frame received in 0.25 seconds, re-requesting at: 312.159423
[113 11:25:26.872818] No render frame received in 0.25 seconds, re-requesting at: 313.656489
```

**Comment by FelschR** [comment]
I'm experiencing the same issues with neovim and I'm also using `coc`. The issue appears to occur somewhat unpredictably.

**Comment by ggsalas** [comment]
I'm not sure if my fix is really good, but I have removed the emojis from the default statusLine of COC and I have not seen this bug again. This is my new statusLine: https://github.com/ggsalas/dotfiles/blob/master/.config/nvim/init.vim#L520-L532

**Comment by kovidgoyal** [comment]
If the issue is being caused by emoji, then it will be because coc/nvim is calculating an incorrect width for the emojis, that disagrees with the unicode standard, which is what kitty uses.

**Comment by FelschR** [comment]
There are no emojis in my neovim setup.

**Comment by ggsalas** [comment]
@kovidgoyal  Could exist a way to remove the icon but avoid nvim/kitty breaks if the emojis not follow the standard? 

If is not, you know if I need to report this bug to nvim or COC?

Thanks!

**Comment by kovidgoyal** [comment]
On Wed, May 13, 2020 at 02:21:17AM -0700, Gabriel Salas wrote:
> @kovidgoyal  Could exist a way to remove the icon but avoid nvim/kitty breaks if the emojis not follow the standard? 

No, not really. The terminal emulator and the program running in the
terminal have to agree on what the emoji width should be, otherwise
things will break. The only way to agree is to follow the standard.
Which kitty does.

> 
> If is not, you know if I need to report this bug to nvim or COC?

No idea, I dont use either of those programs. Most likely nvim, since
coc will likely only pass text to nvim of rendering.

**Comment by fabienengels** [comment]
Hi,

I got a similar issue that I solved by disabling [Devicons](https://github.com/ryanoasis/vim-devicons) extension that I was using with [Lightline](https://github.com/itchyny/lightline.vim). So it seems the problem is really coming from these characters.

**Comment by fabienengels** [comment]
More information... I was able to reenable Devicons, the problem was coming from my setting where I override the default Rust icon :

```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['rs'] = '⚙️ '
```

Keeping the default icon fix the issue I had.

@FelschR you may look in your setting if there isn't a missed unicode used at least, the comment from @kovidgoyal helped me to find this issue

**Comment by FelschR** [comment]
@fabienengels Yup, that's indeed the case. I'm using starship in my shell which I frequently access via neovim.
Some relevant neovim issues:
https://github.com/neovim/neovim/issues/7151
https://github.com/neovim/neovim/issues/12523
