### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by plasmoduck** [kovidgoyal/kitty#2575]
I get this error after crashing on FreeBSD. How to fix please?

[113 04:42:26.575738] [PARSE ERROR] Unknown OSC code: 13
OSError: Failed to load the function ca_context_create with error: Shared object "liballocator.so.0" not found, required by "kitty"
[1]    28754 segmentation fault (core dumped)  ~/git/kitty/kitty/launcher/kitty

**Comment by plasmoduck** [comment]
Also, I have to press ctl+shift+del to clear terminal before kitty accepts my settings in ~/.config/kitty/kitty.conf

**Comment by kovidgoyal** [comment]
No idea. Install liballocator I assume. ca_context_create comes from
libcanberra, install its dependencies.
