### ISSUE TITLE
strikethrough is not in terminfo

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#2576]
#2567 supposed to add strikethrough to terminfo but I can't seem to find it.

<img width="851" alt="Screenshot 2020-04-23 at 06 28 52" src="https://user-images.githubusercontent.com/63876/80059270-e7f67c80-852b-11ea-82cf-679e94bcec5c.png">

**Comment by kovidgoyal** [comment]
It's present in terminfo/kitty.terminfo. Most likely ncurses/infocmp/tic
dont support it since as far as I know its an extension property
introduced by tmux.
