### ISSUE TITLE
Neovim ctrl+c : response time

### ISSUE THREAD

**Issue by BigfootN** [kovidgoyal/kitty#2577]
Hello,

I am having some response issue with the keyboard in `neovim`. When issuing `ctrl+c` and then `:` in neovim it doesn't work right away. I have to perform `ctrl+c`, wait some time and then perform `:`. I have tested with another terminal (`gnome-terminal`) and I didn't face any problem.

Thank you very much in advance for your help.

**Comment by kovidgoyal** [comment]
I cannot reproduce using either showkey -a or vim. Pressing ctrl+c an
then ctrl+: responds instantly.

**Comment by BigfootN** [comment]
Hello,

Thank you for your quick response. I think I may have found the source of the problem.
May I ask you, if I may, and if you set it, what `delay` and `rate` you set in 
`xset r rate <delay> <rate>` ?

Thank you very much in advance.

**Comment by kovidgoyal** [comment]
kitty does not set anything for those, they are system wide.

**Comment by BigfootN** [comment]
Is there a option in the config for this ?

**Comment by kovidgoyal** [comment]
No, key repeat is set at the system level in the X server, individual
applications do not manipulate it.

**Comment by BigfootN** [comment]
Thank you very much for your great help, but where would I find such a setting ?
Doesn't `xset`communicate with the X server ?

Thank you for your great help.

**Comment by kovidgoyal** [comment]
yes xset is how you do it, but that has nothing to do with kitty, it sets the keyboard repeat rate for all applications.

**Comment by DaikyXendo** [comment]
Hello, I'm also having the same problem. If I press too fast, kitty can skip Ctrl+C, which is very annoying on Neovim because it won't exit INSERT mode. Looking forward to a fix.
