### ISSUE TITLE
[macos] Numpad keys are not differentiated from regular keys

### ISSUE THREAD

**Issue by Jayphen** [kovidgoyal/kitty#2578]
I am trying to bind numpad keys in vim using the mapping `<k1>` for the numpad 1 key for example. It appears that kitty passes all numpad keys through as regular keys, so the binding does not work.

I've confirmed that the same binding does work in the native Terminal app, so there is no problem with the binding itself.

Is it possible that support for the numpad was intentionally removed in [this PR](https://github.com/kovidgoyal/kitty/pull/2224/files)? If so, would it be possible to opt-in to the previous behaviour?

**Comment by kovidgoyal** [comment]
As far as I know, terminals report all numpad keys as their normal key equivalents. I dont see how you could bind them in terminal programs. If that were not the case, then pressing, for example, the KP_1 key at a shell prompt would not display 1 but something else. As long as you want your numpad keys useable at a shell, you cannot bind them separately in terminal programs. 

Now the terminfo database actually allows terminals to provide special codes for numpad keys, but as far as I know the vast majority of terminals do no do this, as they make the keys unusable at a shell, as I described earlier.

**Comment by kovidgoyal** [comment]
Actually, I should not say the vast majority of terminals dont implement
these, as I have not actually tested that.

**Comment by Jayphen** [comment]
>As far as I know, terminals report all numpad keys as their normal key equivalents. I dont see how you could bind them in terminal programs.

This does not seem to be the case — my binding for `<k1>` works fine in Vim as long as I am using the native MacOS Terminal.app, but it does not work in kitty, where it just sends `1`.

**Comment by kovidgoyal** [comment]
On Thu, Apr 23, 2020 at 05:34:38AM -0700, Jayphen wrote:
> >As far as I know, terminals report all numpad keys as their normal key equivalents. I dont see how you could bind them in terminal programs.
> 
> This does not seem to be the case — my binding for `<k1>` works fine in Vim as long as I am using the native MacOS Terminal.app, but it does not work in kitty, where it just sends `1`.

Yes, kitty does that deliberately since doing it means you can use your
numpad keys to actually type.

**Comment by Jayphen** [comment]
>Yes, kitty does that deliberately since doing it means you can use your
numpad keys to actually type.

I understand. So I suppose this is a feature request for a toggle, so that I can use the numpad keys as shortcut keys rather than for typing.

**Comment by kovidgoyal** [comment]
well a patch for it is most welcome, not something I am interested in
implementing personally.

**Comment by Jayphen** [comment]
Fair enough. I don't have the knowledge to create a PR for this, so I will just map the keypad keys to something else at the system level.

**Comment by kovidgoyal** [comment]
You can map them in kitty too using send_text in kitty.conf
