### ISSUE TITLE
How exactly do I create & re-use Sessions?

### ISSUE THREAD

**Issue by peterpme** [kovidgoyal/kitty#2579]
Hey, thanks so much for this awesome tool!

- I went through the [Startup Sessions](https://sw.kovidgoyal.net/kitty/#startup-sessions) docs here
- I went through [Layouts](https://sw.kovidgoyal.net/kitty/#layouts)
- I tried searching Github code for commands

I'm struggling to figure out how I can:
- Create a session
- Use that session

I copied over the example under `Startup Sessions` but I just couldn't get it working. Am I idiot? Am I missing something?

Any help would be appreciated, even an example somewhere I can look at.

Thanks!!!

**Comment by kovidgoyal** [comment]
Copy the sample session to a file named simple.session, run kitty with:

kitty --session simple.session

**Comment by peterpme** [comment]
Thank you!
