### ISSUE TITLE
Font is rendered too thin

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#2580]
I set the same fonts in kitty, alacritty and iterm2, but the font in kitty is very thin. 

The font I use:
font_family            JetBrainsMono Nerd Font Mono Regular
bold_font              JetBrainsMono Nerd Font Mono Bold
italic_font              JetBrainsMono Nerd Font Mono Italic
bold_italic_font    JetBrainsMono Nerd Font Mono Bold Italic

kitty version: latest
macOS version: 10.15.4 (latest)

kitty:
![image](https://user-images.githubusercontent.com/11582667/80147688-bcde4e00-8568-11ea-8661-e6e27a24fa4e.png)

alacritty:
![image](https://user-images.githubusercontent.com/11582667/80147725-cc5d9700-8568-11ea-9b4a-6d6b9077393c.png)

iterm2:
![image](https://user-images.githubusercontent.com/11582667/80147757-d7182c00-8568-11ea-976e-b70ccc7964fd.png)

So it can be observed that both regular and bold fonts in kitty are thinner than them in alacritty or iterm2. 

How to solve this? Thank you very much.

**Comment by Luflosi** [comment]
You can try to play around with https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.macos_thicken_font.

**Comment by yanzhang0219** [comment]
Okay. I will try that. Thanks.

**Comment by leleliu008** [comment]
what's the solution for GNU/Linux?

**Comment by page-down** [comment]
@leleliu008

> what's the solution for GNU/Linux?

https://github.com/kovidgoyal/kitty/pull/5969

Install the nightly release or compile from master and configure the option `text_composition_strategy`.
See the description of this option in `kitty/options/definition.py` and refer to PR 5969 for information on how to tweak it.

**Comment by leleliu008** [comment]
Okay. I will try it. Thanks a lot.

**Comment by adrianmay** [comment]
I also want the fonts thicker but I don't know how to adjust any option, be it text_composition_strategy or any other. PR 5969 does not explain that AFAICT. Is there any evidence that the majority of people like these spider thin fonts, and iff not why not fix the default?

**Comment by ad-chaos** [comment]
Here's where the option is explained with more details
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy
