### ISSUE TITLE
Fira Code Retina does not render ligatures when old numerals are set 

### ISSUE THREAD

**Issue by thinred** [kovidgoyal/kitty#2584]
Hey,
it seems that when I enable old numerals, ligatures are not rendered, I'm not sure if this is expected (maybe these two font features are not supported together).

Config:

```
font_features FiraCode-Retina +onum
disable_ligatures cursor
```
With this setup, old numerals are used, but there are no ligatures. When I remove "font_features", ligatures work.

I also tried adding +liga and +calt to the feature list, but the result is the same.

Thanks for Kitty, it's great!

**Comment by kovidgoyal** [comment]
Works for me with 

kitty --config NONE -o "font_family Fira Code" -o "font_features FiraCode-Regular +onum" sh -c "printf  000; printf ===; read"

ligatures are rendered and I *think* the zeros are old style

**Comment by kovidgoyal** [comment]
Also works with

kitty --config NONE -o "font_family Fira Code Retina" -o "font_features FiraCode-Retina +onum" sh -c "printf  000; printf ===; read"


this is on Arch Linux with kitty 0.17.3

**Comment by luetage** [comment]
I can confirm this problem. When you load in kitty.conf
`font_family Fira Code Retina`
and
`font_features FiraCode-Retina +onum`
then numerals work as expected but ligatures disappear.
Trying out 
`kitty --config NONE -o "font_family Fira Code Retina" -o "font_features FiraCode-Retina +onum" sh -c "printf 000; printf ===; read"`
the result is the same – ligatures disappear.
I'm on Fedora 31 Wayland with kitty version 0.17.2

**Comment by luetage** [comment]
Ok, this is all my fault, seems like Fira Code has removed ligatures for F + L in the latest release, that's why I got confused. All is working fine on my end. Sorry :/

**Comment by thinred** [comment]
Interesting, I've removed my per-user installation of FiraCode and installed fonts-firacode in Debian. Now it works. Thanks.

Sorry for the churn!
