### ISSUE TITLE
Kitty window killed when dragging a firefox tab into the surface currently mapped by the kitty window

### ISSUE THREAD

**Issue by Atralb** [kovidgoyal/kitty#2585]
I discovered this by needing to detach a firefox tab from a window and reattach it again to another firefox window, while having an interposed kitty window. As soon as the mouse holding a firefox tab gets over a kitty window, it instantly kills the kitty window with no form of warning.

This evidently creates a dangerous loss of work.

Am I the only one to experience this issue ?

System : 
Ubuntu 18.04
kitty 0.17.2
i3 4.14.1

PS : don't know if that matters, but the issue does not exist with alacritty

**Comment by Luflosi** [comment]
This is fixed in 0.17.3, see #2505.

**Comment by Atralb** [comment]
@Luflosi Thanks for your answer.

I am sorry to bother you, but would you mind explaining to me how to cleanly update kitty (since it is not in my package manger repos) ? I have installed kitty with the binary installer pulled with curl, but I'm not sure if I need to uninstall kitty, then reinstall it with the curl command, or if simply running the command again will already get me a clean update without duplication ?

**Comment by Luflosi** [comment]
Yep, simply rerun the command from https://sw.kovidgoyal.net/kitty/binary.html#kitty-binary-install.
I'm curious, which package manager are you using?

**Comment by kovidgoyal** [comment]
Simply rerun the binary install command.

**Comment by Atralb** [comment]
@Luflosi Nothing fancy : `apt`.

Kitty is not in the repos for Ubuntu 18.04 apparently.
