### ISSUE TITLE
Text overflows between panels

### ISSUE THREAD

**Issue by aral** [kovidgoyal/kitty#2587]
![Screenshot from 2020-04-25 13-53-50](https://user-images.githubusercontent.com/41798/80280498-5853f800-86fc-11ea-958e-685c7abdce19.png)

**Comment by aral** [comment]
(Also, panel tops and bottoms do not align in all configurations.)

**Comment by kovidgoyal** [comment]
dup of #2562 

And why would they align?? they are of different sizes. The only way to align them would be to set border,padding and margin to zero
