### ISSUE TITLE
New version popup is really annoying, please let me disable it

### ISSUE THREAD

**Issue by witcheslive** [kovidgoyal/kitty#2589]
Every time I open a new terminal window the update popup comes on. I cannot figure out how to disable it. I will not be updating until there's an ebuild in portage so it is especially obnoxious. Please add an option to disable it or add something to the documentation on how to disable it if it already exists, because I cannot find it

**Comment by Luflosi** [comment]
If you only have a single instance of kitty, you should only see the notification once on startup. There is a single instance mode, that can help you with that, should even save some resources.
Anyways, you can disable the notification by setting `update_check_interval` to 0, see https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.update_check_interval.

**Comment by trygveaa** [comment]
The portage build should set `--update_check_interval=0` at build time. It's mentioned at the bottom of the [Note for Linux/macOS packagers](https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers). You can also see how to use it in the [Arch package](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/kitty#n22).
