### ISSUE TITLE
there a way to place default config in /etc/kitty/kitty.conf 

### ISSUE THREAD

**Issue by bradlyatc** [kovidgoyal/kitty#259]
there a way to place default config in /etc/kitty/kitty.conf and upon first launch cp to ~/.config/kitty/kitty.conf    that would be amazing

**Comment by kovidgoyal** [comment]
Why? kitty is not a system program, so it doesn't feel right for it to look for config files in /etc

If you want to provide a per-site default for new users, use the existing /etc/skel mechanism, that is what it is for.
