### ISSUE TITLE
Firacode Rendering on OSX for ligatures looks offset and not-centered.

### ISSUE THREAD

**Issue by EvanCarroll** [kovidgoyal/kitty#2591]
This looks really weird compared to my Debian machine,

<img width="118" alt="Screen Shot 2020-04-25 at 22 36 16" src="https://user-images.githubusercontent.com/19922/80297053-6b3eea80-8745-11ea-970e-ada695d5b47a.png">

On my Debian machine, `HELLO::WORLD` results in the `::` being tighter together without sitting on the left with a glaring space on the right.

I'm using `FiraCode Nerd Font` and I've tried with `FiraCode Nerd Font Retina`

-----

```text
$ kitty --version
kitty 0.17.3 created by Kovid Goyal
```

-----

```text
[116 22:39:19.097078] Preloaded font faces:
[116 22:39:19.097111] normal face: /Users/evancarroll/Library/Fonts/Fira Code Retina Nerd Font Complete.otf
[116 22:39:19.097124] bold face: /Users/evancarroll/Library/Fonts/Fira Code Retina Nerd Font Complete.otf
[116 22:39:19.097135] italic face: /Users/evancarroll/Library/Fonts/Fira Code Retina Nerd Font Complete.otf
[116 22:39:19.097145] bi face: /Users/evancarroll/Library/Fonts/Fira Code Retina Nerd Font Complete.otf
```

-----

```text
$ brew cask info font-firacode-nerd-font
font-firacode-nerd-font: 2.1.0
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode
/usr/local/Caskroom/font-firacode-nerd-font/2.1.0 (80 files, 140.5MB)
From: https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-firacode-nerd-font.rb
==> Name
FiraCode Nerd Font (Fira Code)
==> Artifacts
Fira Code Light Nerd Font Complete Mono.otf (Font)
Fira Code Medium Nerd Font Complete.otf (Font)
Fira Code Retina Nerd Font Complete.otf (Font)
Fira Code Regular Nerd Font Complete.otf (Font)
Fira Code Light Nerd Font Complete.otf (Font)
Fira Code Bold Nerd Font Complete Mono.otf (Font)
Fira Code Medium Nerd Font Complete Mono.otf (Font)
Fira Code Retina Nerd Font Complete Mono.otf (Font)
Fira Code Regular Nerd Font Complete Mono.otf (Font)
Fira Code Bold Nerd Font Complete.otf (Font)
```

**Comment by kovidgoyal** [comment]
First, dont use patched fonts. They are often broken. And there is no need to use them with kitty. As long as you have the nerd fonts installed, kitty will pick up and use them automatically, or you could configure it to do so with symbol_map in kitty.conf. let me know if the issue persists without using patched fonts, if so, I will take a look.

**Comment by EvanCarroll** [comment]
I believe these fonts are unpatched, I had started with them:

```text
[116 23:30:11.822716] Preloaded font faces:
[116 23:30:11.822748] normal face: /Users/evancarroll/Library/Fonts/FiraCode-Retina.otf
[116 23:30:11.822761] bold face: /Users/evancarroll/Library/Fonts/FiraCode-Retina.otf
[116 23:30:11.822771] italic face: /Users/evancarroll/Library/Fonts/FiraCode-Retina.otf
[116 23:30:11.822781] bi face: /Users/evancarroll/Library/Fonts/FiraCode-Retina.otf
```

-----

```text
$ brew search fira
==> Casks
font-fira-code ✔                         font-fira-sans
font-fira-mono                           font-firacode-nerd-font
font-fira-mono-for-powerline             font-firamono-nerd-font
```

-----

```
brew cask info font-fira-code
font-fira-code: 3.1
https://github.com/tonsky/FiraCode
/usr/local/Caskroom/font-fira-code/3.1 (29 files, 3.8MB)
From: https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-fira-code.rb
==> Name
Fira Code
==> Artifacts
otf/FiraCode-Bold.otf (Font)
otf/FiraCode-Light.otf (Font)
otf/FiraCode-Medium.otf (Font)
otf/FiraCode-Regular.otf (Font)
otf/FiraCode-Retina.otf (Font)
```

**Comment by alappe** [comment]
I can confirm this issue. It was introduced with `v0.17.3` and working fine with `v0.17.2`.

Using Fira Code Retina, `Version 1.206;PS 001.206;hotconv 1.0.88;makeotf.lib2.5.64775`

**Comment by kovidgoyal** [comment]
Then it will be because of the fix for https://github.com/kovidgoyal/kitty/issues/1457 

I dont really see a good solution here. centering breaks rendering for
some glyphs and not centering breaks rendering for others and there is
no a-priori way to know which are which. I could implement some hacky
solution like tracking if the glyph is a ligature and centering in that
case on macOS.

**Comment by kovidgoyal** [comment]
Note, I have not tested the fix, I leave that to somebody that uses macOS as their primary platform.

**Comment by alappe** [comment]
Using `make app` in the master including your fix, I still have issues:

![Screenshot 2020-04-27 at 13 55 55](https://user-images.githubusercontent.com/1357848/80369783-1d35fe00-888f-11ea-8050-b4cbe40b0a7c.png)

**Comment by kovidgoyal** [comment]
This should fix that: https://github.com/kovidgoyal/kitty/commit/e803505aad864067258ef8d6efd5145a8167a7d0

**Comment by alappe** [comment]
Yes it does, thank you!

**Comment by horta** [comment]
Great work!
