### ISSUE TITLE
Ligatures - Spacing issue with MonoLisa font

### ISSUE THREAD

**Issue by bebraw** [kovidgoyal/kitty#2599]
> Original issue: https://github.com/MonoLisaFont/feedback/issues/15 .

Here's a rendering with MonoLisa when ligatures are enabled:

<img width="406" alt="Screenshot 2020-04-28 at 9 30 33" src="https://user-images.githubusercontent.com/166921/80462765-df44e280-893f-11ea-9510-3c4ca8f490b9.png">

Minimal config:

```bash
 font_family        MonoLisa                                                                                                                                                                      
  bold_font          auto                                                                                                                                                                                        
  italic_font        auto                                                                                                                                                                                        
  bold_italic_font auto                                                                                                                                                                                        
  font_size          13   
```

Let me know if you need any further info and/or the font to test.

**Comment by kovidgoyal** [comment]
Thay will be because those ligatures are larger than the number of characters they are meant to replace. https://sw.kovidgoyal.net/kitty/faq.html#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by bebraw** [comment]
@kovidgoyal Is that due to the fact that MonoLisa glyphs are slightly wider (about 7%) so that the logic you described kicks in?

**Comment by kovidgoyal** [comment]
No idea, I have not looked at the actual font. But kitty will resize a
glyph when it is too large to fit in the cells it is supposed to fit in.

**Comment by mekkablue** [comment]
> The exception is if these characters are followed by a space or empty cell in which case kitty makes use of the extra cell to render them in two cells.

MonoLisa does this. And the ligatures are still rendered too small.

**Comment by kovidgoyal** [comment]
On Wed, Jul 22, 2020 at 06:26:37AM -0700, Rainer Erich Scheichelbauer wrote:
> > The exception is if these characters are followed by a space or empty cell in which case kitty makes use of the extra cell to render them in two cells.
> 
> MonoLisa does this. And the ligatures are still rendered too small. 

Space or empty cells apply to PUA or symbol glyphs, not ordinary text. 
A ligature is rendered in the number of cells taken up by the
constituent characters of the ligature. If the ligature in question is
being resized, then it is because it does not fit in that space.

**Comment by kovidgoyal** [comment]
So, again without having looked at the font itself, my guess would be that it suffers the same issue as Iosevka, namely that its ligatures are implemented as chained glyphs rather than dummy glyphs + actual glyph. See #297 for details.

**Comment by ronjouch** [comment]
@kovidgoyal it looks like the ligatures of [Cascadia Code](https://github.com/microsoft/cascadia-code) version [2102.03](https://github.com/microsoft/cascadia-code/releases/tag/v2102.03) render similarly incorrectly in Kitty.

1. Chrome & Firefox render this font's ligatures perfectly:
    - Firefox 87.0a1 (2021-02-12):
      ![screenshot_firefox_2021-02-12-13:08:15](https://user-images.githubusercontent.com/522085/107805491-6e867f80-6d33-11eb-8d2b-3e6efdaad4d1.png)
    - Chrome 89.0.4389.9:
      ![screenshot_chrome_2021-02-12-13:13:00](https://user-images.githubusercontent.com/522085/107805989-29af1880-6d34-11eb-8f0d-957de88d0041.png)
2. But in Kitty 0.19.3 (zero config, except `font_family Cascadia Code`), ligatures seem to render at a smaller font size (half, maybe?):
  ![screenshot_kitty_2021-02-12-12:52:55](https://user-images.githubusercontent.com/522085/107804177-95dc4d00-6d31-11eb-9488-84fd5811f999.png)

Chatting with the font authors in [a comment of Cascadia Code issue #409](https://github.com/microsoft/cascadia-code/issues/409#issuecomment-778387276), here is what the font maintainer @aaronbell has to say:

> Previously [until version 2009.22, included], the ligatures in Cascadia were "backwards looking", which is to say that in a three glyph run, such as `>>>`, the final `>` would contain the ligature with a negative left side bearing, and normal right side bearing.
>
> However, [starting with version 2102.03] I changed it to be "forwards looking" which means that the first `>` contains the ligature as that allows me to be more efficient with my code and simplifies things quite a bit. But it appears that Kitty can't deal with that.

Does it make sense / do you acknowledge Kitty's rendering is incorrect?

**Comment by kovidgoyal** [comment]
This is a monospaced font. To render a ligature composed of three characters, the result needs to be three cells wide, not more. If kitty is rendering the result smaller it will be because the ligature does not fit in three cells. kitty does not care what direction ligatures are declared in.

**Comment by aaronbell** [comment]
What do you mean by “the result needs to be three cells wide”? All ligatures in Cascadia Code fit within their anticipated widths. `>>>` takes up three spaces. `&&` takes up two.

**Comment by kovidgoyal** [comment]
The cell width is calculated from the font metrics once at load time. All characters in a monospaced font are supposed to fit inside a cell. For multi character ligatures of N characters, they have to fit inside N cells. When a character or ligature does not fit inside its nominal number of cells, kitty reduces the font size and renders it, to force it to fit. If the overflow is small, then it just chops off a few pixels instead.

If you need to see why your font is overflowing, you can use th ehb-shape command to do it

hb-shape --show-extents --cluster-level=1 --shapers=ot /path/to/font/file text

this will use harfbuzz to calculate glyph geometries, it is this geometry information that kitty uses in turn to place glyphs.

**Comment by ronjouch** [comment]
> If you need to see why your font is overflowing, you can use th ehb-shape command to do it

@kovidgoyal @aaronbell here's what I see:

```
23:56:46 ~ hb-shape --version
hb-shape (HarfBuzz) 2.6.4
Available shapers: graphite2,ot,fallback

23:56:53 ~ hb-shape --show-extents --cluster-level=1 --shapers=ot ~/CascadiaCode-2102.03/ttf/static/CascadiaCode-Regular.ttf 'hello'
[h=0+1200<168,1500,864,-1500>|e=1+1200<136,1080,928,-1100>|l=2+1200<98,1500,976,-1520>|l=3+1200<98,1500,976,-1520>|o=4+1200<136,1080,928,-1100>]

23:57:42 ~ hb-shape --show-extents --cluster-level=1 --shapers=ot ~/CascadiaCode-2102.03/ttf/static/CascadiaCode-Regular.ttf '!=='
[exclam_equal_equal.liga=0+1200<180,1520,3240,-1620>|LIG=1+1200<0,0,0,0>|LIG=2+1200<0,0,0,0>]

23:57:47 ~ hb-shape --show-extents --cluster-level=1 --shapers=ot ~/CascadiaCode-2102.03/ttf/static/CascadiaCode-Regular.ttf '&&'
[ampersand_ampersand.liga=0+1200<186,1440,2008,-1460>|LIG=1+1200<0,0,0,0>]

23:57:52 ~ hb-shape --show-extents --cluster-level=1 --shapers=ot ~/CascadiaCode-2102.03/ttf/static/CascadiaCode-Regular.ttf '//'
[slash_slash.liga=0+1200<294,1610,1898,-1800>|LIG=1+1200<0,0,0,0>]
```

**Comment by aaronbell** [comment]
Thank you @ronjouch. 

If I am reading this correctly, then yes, all of the glyphs fit within the appropriate bounds. The base letter width is 1200. 

`!==` has a width of 3240, which is within the three cell width of 3600 (even including the LSB of 180).
`&&` has a width of 2008, which is within the two cell width of 2400 (even including the LSB of 186).
`//` has a width of 1898, which is within the two cell width of 2400 (even including the LSB of 294).

So why does Kitty shrink these ligatures?

**Comment by kovidgoyal** [comment]
Yes, looks correct, I will investigate in more detail when I have some time.

**Comment by aaronbell** [comment]
Thank you! @ronjouch, sorry to be a bother, but could you open a new issue here to track this? I’m away from my desk 😨 .

**Comment by ronjouch** [comment]
> Thank you! @ronjouch, sorry to be a bother, but could you open a new issue here to track this? I’m away from my desk fearful .

@aaronbell done: https://github.com/kovidgoyal/kitty/issues/3313 . Thanks for the help to both of you, @aaronbell @kovidgoyal .
