### ISSUE TITLE
the ability to install kitty via make install

### ISSUE THREAD

**Issue by funeralismatic** [kovidgoyal/kitty#26]
Can you add `install` (with DESTDIR), `build` and `test` targets to Makefile?

**Comment by kovidgoyal** [comment]
kitty is designed to run in place. If you want to package it for a distro, see https://github.com/kovidgoyal/kitty#note-for-linux-packagers

for how to create a package.

I suppose one could wrap the linux-package command into the Makefile, though I dont see much point to it.

**Comment by funeralismatic** [comment]
I can't (or don't want; nevermind) create a binary package.

Ok, I get it.
