### ISSUE TITLE
xcursor not listed as dependency

### ISSUE THREAD

**Issue by avernan** [kovidgoyal/kitty#260]
Trying to compile v0.6.1 I got the following error messages
```
Linking kitty/fast_data_types ...
Package xcursor was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcursor.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xcursor' found
The package xcursor was not found on your system
```
```
Linking kitty/fast_data_types ...
Package xkbcommon-x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon-x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon-x11' found
The package xkbcommon-x11 was not found on your system
```
fixed (on Ubuntu) by installing `libxcursor-dev` and `libxkbcommon-x11-dev`. Should these be listed along the other dependencies or are they supposed to be required by something else?

**Comment by kovidgoyal** [comment]
Those are both part of X11 and used by wayland as well. How is it you dont already have them installed? I dont list basic system packages in dependencies, if I did that the dependency list would become very, very long.

**Comment by avernan** [comment]
The base package were already installed, what was missing where the "-dev" packages that include the header files.

**Comment by kovidgoyal** [comment]
Yes because version 0.5 did not include glfw, which is what needs X11.
