### ISSUE TITLE
macOS: Option+Left prints a capital D

### ISSUE THREAD

**Issue by ionstormx** [kovidgoyal/kitty#2600]
I use Option+Left (and Right) to quickly jump to start/end of words. When I do this in kitty, It prints a capital D.

I've looked through the documentation and I honestly don't know how to go about remapping or changing this behaviour.

Thanks!

**Comment by kovidgoyal** [comment]
Use the option_as_alt setting in kitty.conf.

**Comment by ionstormx** [comment]
Unfortunately, I have tried the **macos_option_as_alt** setting _disabled (commented out), no, left, right and both_, but I still get the same result. I have also tried it in the bash shell.

I do use Karabiner-Elements and Oh-My-Zsh, although i'm not sure if that's relevant.

**Comment by Luflosi** [comment]
Leave `macos_option_as_alt` at the default value of `no` and try adding
```
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66
```
to your config.

**Comment by ionstormx** [comment]
@Luflosi that worked! Thanks! Now i'm curious why.

**Comment by Luflosi** [comment]
It tells kitty to send special escape codes when you press <kbd>alt</kbd>+<kbd>left</kbd> or <kbd>alt</kbd>+<kbd> right </kbd>.

**Comment by ionstormx** [comment]
Alright. I'll look up escape codes. Thanks again!

**Comment by Luflosi** [comment]
Also see #838 and the comment https://github.com/kovidgoyal/kitty/pull/1323#issuecomment-456762751 and the comment after that.
