### ISSUE TITLE
Clicking on edge of maximized window switches to other window

### ISSUE THREAD

**Issue by aral** [kovidgoyal/kitty#2603]
## To reproduce

1. Create two windows, side by side
2. Maximize the window on the _right_
3. Click towards either the left or right edge of the maximized window

## What should happen

Nothing.

## What actually happens

The window switches to the window that was on the right.

**Comment by kovidgoyal** [comment]
What does this have to do with kitty, which is a terminal emulator??

**Comment by aral** [comment]
You use the terminology “window” to refer to what is more commonly called a panel, so I was using your terminology. Given that I’ve been making things with computers for over three decades and that I’m not an absolute idiot, we can probably discount the fact that I was opening an issue about my display manager.

The windows in question are Kitty windows (this is why the issue is in the Kitty issue tracker) and this is a bug in Kitty.

If you do not want bug reports, please say so or otherwise don’t rudely dismiss people who are taking their time to report issues because they love what you’ve built and want to see it improve. I know everyone’s on edge with the state of things right now but please don’t take it out on people who are trying to help.

Hope you’re well and that I just caught you on a bad day.

**Comment by kovidgoyal** [comment]
For Pete's sake you could simply have posted an issue in the wrong place accidentally, there is absolutely no call to fly off the handle. Asking you for more information is not "taking anything out on you". And what does maximize a window in kitty mean??? Switch to the stack layout? something else? Kitty has no concept of maximizing windows. And your bug report states that clicking on the maximized right window edge cause the "window to switch to the window on the right". I have no idea what that means, either.

**Comment by aral** [comment]
Right, don’t worry about it. It’s not a problem.

**Comment by MrPetovan** [comment]
> Asking you for more information

Closing the issue preemptively cannot be construed as "Asking for more information" by anyone in good faith.

**Comment by kovidgoyal** [comment]
Right, of course, I closed the issue, how nasty of me. Feel free to not use kitty.
