### ISSUE TITLE
Clicking in the window padding or margin in the stack layout switches to the first window

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#2604]
I can reproduce #2603 with these steps:

1. Open a second kitty window
2. Switch to the stack layout
3. Click somewhere in the window padding or margin.
    - If you use a maximized window without window decorations and the size doesn't exactly match the rows/columns, this is easily triggered by moving the mouse to the edge of the screen and clicking.
    - If not, set `window_padding_width` or `single_window_margin_width` to a large value and click in the margin or padding.

**Comment by kovidgoyal** [comment]
That sounds like the window visibility property is not being updated
when switching layouts.

**Comment by trygveaa** [comment]
It happens if I switch to the stack layout first, and then opens the second window too. And also if I switch back to the second window after clicking and click again.

**Comment by trygveaa** [comment]
Thanks for being super quick to fix it, as usual :)

**Comment by kovidgoyal** [comment]
You're welcome :)
