### ISSUE TITLE
Drag n drop files not working in macOS

### ISSUE THREAD

**Issue by miuirussia** [kovidgoyal/kitty#2605]
```
kitty(14729,0x10b725dc0) malloc: can't allocate region
:*** mach_vm_map(size=140733193392128, flags: 60000100) failed (error code=3)
kitty(14729,0x10b725dc0) malloc: *** set a breakpoint in malloc_error_break to debug
MemoryError
```

**Comment by Luflosi** [comment]
I can confirm, I'm bisecting it now.

**Comment by Luflosi** [comment]
e827e6fa21d6f435cde32b758bce69693e823f63 works fine, 2458c3a7c66ad45c49bfbcd8dfa4fe9cf108a958 doesn't compile and ab9a36f8c1c9a3d43d56c584767bde2072161408 crashes. If I replace `WINDOW_CALLBACK(on_drop, "sy#", mime, data, (int)sz);` with `WINDOW_CALLBACK(on_drop, "sy", mime, data);` it works fine. `on_drop()` in `boss.py` doesn't seem to accept an argument for the length.

**Comment by kovidgoyal** [comment]
@Luflosi: I dont follow, y# means convert a const char* and a size into a python bytes object. Which is what on_drop is accepting.

**Comment by Luflosi** [comment]
You're right.
But what's the `goto` for? Probably to reset `global_state.callback_os_window`. But shouldn't it then also be reset when any of the three cases above are executed?

**Comment by kovidgoyal** [comment]
yeah, it should
