### ISSUE TITLE
Wayland: kitty randomly starts floating

### ISSUE THREAD

**Issue by travankor** [kovidgoyal/kitty#2606]
On Wayland (sway specifically), kitty instances that were initially started floating will randomly float without user interaction even if they are not currently floating. Not really sure what's causing this, but I've run into this behaviour several times. And this doesn't happen with any other terminal emulator.

I'm going to try to reproduce this with `kitty --dump-commands` in case that gives more insight, but I wanted to give a heads up just in case someone else has any ideas.

Steps to reproduce:
1) `for_window [app_id="termfloat"] floating enable`
2) `kitty --class="termfloat"`
3)  Unfloat window
4) ??? (wait some period of time I guess since this is where the bug happens)
5) Window starts floating again without user interaction (Opening or closing windows adjacent to kitty might trigger this?)

**Comment by kovidgoyal** [comment]
kitty never sets its own window size (the only exception being when
transitioning out of fullscreen, where it restores its previous size,
and obviously at window creation time). 

You can confirm this for yourself by grepping the source for
glfwSetWindowSize. This is likely something to do with your window
manager.
