### ISSUE TITLE
`exit` hangs/locks up when executed after `disown`

### ISSUE THREAD

**Issue by hendersonreed** [kovidgoyal/kitty#2608]
I launch a good number of applications directly from the command line with the form `<executable name> & ; disown ; exit` and have found that switching to kitty breaks this workflow, for the reason described in the title. After running `exit` after `disown`, the entire terminal hangs and is fully unresponsive - ctrl-c, ctrl-d, ctrl-z, none work and simply enter ^C, ^D and ^Z at the cursor location.

I've tried this using nohup as well, and both work fine in gnome-terminal (though I haven't tried this in any other terminals.) Is this something configurable? I looked through the configuration docs but couldn't find anything that quite matched what I was interested in.

edit: apparently ctrl-return submits the issue, even if you're not done writing it :)

I am running under SwayWM on Fedora 31, with kitty 0.17.2, and this issue occurs without any configuration whatsoever.

**Comment by trygveaa** [comment]
This is the option you're looking for: https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.close_on_child_death

>  entire terminal hangs and is fully unresponsive

It doesn't really hang, kittens still works for instance. To close the window, you should just close it with your window manager like any other window (but if you change the option mentioned, you don't have to close it manually).

**Comment by hendersonreed** [comment]
Oh, I see - I misunderstood what that option was - I was imagining that the child process was the disowned process, not the shell itself.

**Comment by amarshall** [comment]
Alternatively, can run the process disconnected from stdin/out/err. This is probably better since, as noted in the docs, the process in this case won’t have broken pipes (and `close_on_child_death` may be left at its default of no). E.g.

```
sleep 100 </dev/null &>/dev/null & ; disown %1 ; exit
```
