### ISSUE TITLE
Issue selecting latest version of JetBrainsMono

### ISSUE THREAD

**Issue by vianpl** [kovidgoyal/kitty#2609]
Hi @kovidgoyal,
I'm seeing issues with the latest version of JetBrainsMono. For some reason kitty doesn't select them as bold/bi fonts while that was fine with previous iterations of the font. Here's the issue on JetBrains repo https://github.com/JetBrains/JetBrainsMono/issues/227. Would you mind having a look?

**Comment by trygveaa** [comment]
Probably something wrong with your font installation. It works fine for me. I installed it by downloading it from the releases page and placing the ttf files in `~/.fonts`.

**Comment by trygveaa** [comment]
What does `fc-match --sort monospace | head` and `fc-match --sort monospace:bold | head` output?

**Comment by vianpl** [comment]
That's exactly how I installed it.

Here's the output:

```
nico@linux-9qgx:~> fc-match --sort monospace:bold | head
SourceCodePro-Bold.otf: "Source Code Pro" "Bold"
LiberationMono-Bold.ttf: "Liberation Mono" "Bold"
DejaVuSansMono-Bold.ttf: "DejaVu Sans Mono" "Bold"
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
DejaVuSansMono-Oblique.ttf: "DejaVu Sans Mono" "Oblique"
DroidSansMono.ttf: "Droid Sans Mono" "Regular"
andalemo.ttf: "Andale Mono" "Regular"
courbd.ttf: "Courier New" "Bold"
couri.ttf: "Courier New" "Italic"
n022004l.pfb: "Nimbus Mono L" "Bold"

nico@linux-9qgx:~> fc-match --sort monospace:bold | head
SourceCodePro-Bold.otf: "Source Code Pro" "Bold"
LiberationMono-Bold.ttf: "Liberation Mono" "Bold"
DejaVuSansMono-Bold.ttf: "DejaVu Sans Mono" "Bold"
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
DejaVuSansMono-Oblique.ttf: "DejaVu Sans Mono" "Oblique"
DroidSansMono.ttf: "Droid Sans Mono" "Regular"
andalemo.ttf: "Andale Mono" "Regular"
courbd.ttf: "Courier New" "Bold"
couri.ttf: "Courier New" "Italic"
n022004l.pfb: "Nimbus Mono L" "Bold"
```

That said here's my font config in kitty:

```
 font_family	  JetBrains Mono Regular
 bold_font        JetBrains Mono Bold
 italic_font      JetBrains Mono Italic
 bold_italic_font JetBrains Mono Bold Italic

```
I removed everything except for the `font_family` option and it's now working fine. So I guess something subtle changed in the font naming.

**Comment by kovidgoyal** [comment]
You should generaly need to specify only font_family unless kitty selects the wrong alternate faces automatically.

**Comment by trygveaa** [comment]
Oh, it seems to be because the bold version contains non-monospaced glyphs. If I run `kitty list-fonts` or `fc-list : family spacing | grep -e spacing=100 -e spacing=90`, only the regular and medium versions are listed.

One weird thing is that with version 1.0.5, that `fc-list` command still doesn't list the bold version, but `kitty list-fonts` does. If I print `fd` [here](https://github.com/kovidgoyal/kitty/blob/8327dabb29549bc43cdd2b16f2d99129d054528f/kitty/fonts/fontconfig.py#L51), I see that it has `spacing` set to `MONO`.

@kovidgoyal: Do you know what could be the cause of kitty and fc-list seeing different things?

**Comment by kovidgoyal** [comment]
kitty allows MONO and DUAL, see https://github.com/kovidgoyal/kitty/blob/8327dabb29549bc43cdd2b16f2d99129d054528f/kitty/fonts/fontconfig.py#L59

**Comment by trygveaa** [comment]
Oh, it's listed (with 1.0.5) with `fc-list :bold family spacing | grep -e spacing=100 -e spacing=90`. I guess `:` doesn't list the bold versions, even though the man page says:

> ``:'' is an empty pattern that matches all fonts".

**Comment by trygveaa** [comment]
> kitty allows MONO and DUAL, see

Yeah, I know, but none of them were DUAL.

**Comment by trygveaa** [comment]
I'll post in the issue in the font repo about the bold version containing non-monospaced glyphs.

**Comment by vianpl** [comment]
Thanks for the help Trygve!
