### ISSUE TITLE
font-size adjust

### ISSUE THREAD

**Issue by jojoyuji** [kovidgoyal/kitty#261]
I'm having trouble with my font-size

![kitty-screenshot](https://user-images.githubusercontent.com/675317/34533814-ffb1eb40-f0a2-11e7-9482-f39d45628859.png)

Is there a way to increase/decrease its size like `cmd +` / `cmd -`?

Nice project BTW ;)

**Comment by kovidgoyal** [comment]
See kitty.conf

**Comment by kovidgoyal** [comment]
IIRC ctrl+shit++ and ctrl+shift+- to change font sizes.
