### ISSUE TITLE
ctrl+shift+enter could open terminal in the current working directory (instead of $HOME)

### ISSUE THREAD

**Issue by thinred** [kovidgoyal/kitty#2610]
(it's more like a feature request)

In terminator, opening a new window opens it in the same directory as the current window. This is very convenient as I usually want to work in the same directory. Kitty on the other hand seems to always go back to $HOME. It would be nice if that could be customized. I may give it a shot myself.

**Comment by SolitudeSF** [comment]
`map ctrl+shift+enter launch --type=os-window --cwd=current`

**Comment by thinred** [comment]
Wow, that was fast.

Actually, I needed
```
map ctrl+shift+enter launch --type=window --cwd=current
```

Seems like pretty much everything can be configured. :)

Thanks a lot!
