### ISSUE TITLE
How can I hook the 'on_term' method within a kitten?

### ISSUE THREAD

**Issue by OrDuan** [kovidgoyal/kitty#2611]
Hi,
I would like to write a kitten that hooks into the `on_term` (which get called as a signal) for the whole kitty process.
https://github.com/kovidgoyal/kitty/blob/382c31ddf20d7b1323ae4636f36518d4b2f2c243/kittens/tui/handler.py#L85

This method from my understanding is being called by the `SignalManager` later in the loop.
Would love to get any technical direction on that.

### Background
I saw that you are not going to implement an on-exit prompt, which make sense for me.
I want to give it a try so other like me can use that(#1933, #1554, #1294)

**Comment by kovidgoyal** [comment]
kittens cannot hook events, and they certainly cannot change on exit
behavior. And I have no objection to a confirm on exit option, I am just
not going to spend time writing it myself. So if you want it, patches
are welcome. The entire mechanism would need to be carefully altered,
with tracking for whether a close request comes from the OS or from a
child process ending. You will need to read and understand
process_pending_closes() and mark_os_window_for_close()
