### ISSUE TITLE
Option to set X11 window id 

### ISSUE THREAD

**Issue by toniz4** [kovidgoyal/kitty#2612]
i dont like how kitty manages tabs and prefer ussing tabbed, but i did not found a option to not set a window id, like alacritty --embed or st -w. its possible to implement that?

**Comment by kovidgoyal** [comment]
I dont know what you are asking for, elaborate.

**Comment by toniz4** [comment]
Basically make it xembed aware 

https://specifications.freedesktop.org/xembed-spec/xembed-spec-latest.html

**Comment by kovidgoyal** [comment]
Sorry not something I am interested in implementing, given it will work only with X.
