### ISSUE TITLE
Tab Location

### ISSUE THREAD

**Issue by rigelrozanski** [kovidgoyal/kitty#2614]
Hey! it would be great to have an option in the config to change the location of the tabs. I find it very unintuitive to show the tab as the bottom of the window as opposed to the top (which is standard for every application I can think of).

**Comment by kovidgoyal** [comment]
There already is such an option.

**Comment by rigelrozanski** [comment]
Ah thank you I just found it, doesn't seem to be in the docs anywhere but was able to find in the default config file

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.tab_bar_edge
