### ISSUE TITLE
Tab Auto-Naming

### ISSUE THREAD

**Issue by rigelrozanski** [kovidgoyal/kitty#2615]
There is this cool feature within Iterm2 whereby the tabs are renamed to the executing program within them (such as vim for instance). When a program is executed for a short duration of time, it flashes the command name for a second or so, but when a program is continuously runs (like vim would) it just keeps that tab named the new command. 

Having this feature, is just a kinda nice way to quickly distinguish between what's running in each tab. Having everything just say "bash" gets kinda old and I'm not about to manually name each tab I want to use 

Just an idea! keep up the great work!

**Comment by kovidgoyal** [comment]
Why would you want to see the name of the program?? Say you had 10 tabs with vim showing 10 different files, you'd see 10 vims. Not that useful. Instead teach your command line programs to set the terminal window title, which will show up inthe tab name automatically. A bit of googling will show you how to do that for both bash and vim and pretty much any modern command line program.

**Comment by rigelrozanski** [comment]
You're blowing my mind. Thank you
