### ISSUE TITLE
Fullscreen scroll multiplier

### ISSUE THREAD

**Issue by smasher816** [kovidgoyal/kitty#262]
When scrolling in programs such as vim or less text only moves a single line. In the normal terminal scrollback lines are correctly moved 5 at a time as specified by wheel_scroll_multiplier.

I am using the 0.6.1 Arch package. Changing my TERM variable has not helped. xev reports buttons 4 and 5 being pressed.

**Comment by kovidgoyal** [comment]
vim implements its own handling of mouse wheel events, that is not in kitty's control. I assume there is some config in vim to change the amount scrolled by the wheel.

**Comment by kovidgoyal** [comment]
Make sure that ttymouse is set to sgr in vim. It may or may not do that automatically, depending on the value of TERM and vim version and...

**Comment by smasher816** [comment]
What about other programs such as less which scroll multiple lines with no custom configuration in other terminals such as termite?

I haven't confirmed it but I believe libvte based emulators may be sending multiple events to programs. Would something like that be possible here, or is that out of scope for the project?

**Comment by kovidgoyal** [comment]
It's no problem to send multiple key events in kitty for wheel events.

**Comment by smasher816** [comment]
Perfect, thank you.

less and vim are now working as expected with kitty-git

**Comment by kovidgoyal** [comment]
You're welcome. But if you needed this fix in vim, it indicates vim is not enabling mouse support. Set mouse=a and ttymouse=sgr in your vimrc
