### ISSUE TITLE
Bottom of glyph cut off with Terminus TTF font

### ISSUE THREAD

**Issue by Evidlo** [kovidgoyal/kitty#2622]
I'm trying to replicate my [urxvt config](https://github.com/Evidlo/dotfiles/blob/master/.Xdefaults) in kitty, but in order to get the line height the same, I need to set `adjust_line_height -1`, which cuts off the bottom of some characters.

Here is a comparison of urxvt with BDF Terminus and kitty with TTF Terminus.

![out](https://user-images.githubusercontent.com/5455841/80938146-a07ab680-8d9d-11ea-99bc-e69babce8757.gif)

My kitty config:

```
font_family  Terminus (TTF)
bold_font    Terminus (TTF) Bold
font_size    12

window_padding_width 5

adjust_line_height   -1
```

Is there a way to get kitty to trim this extra line height from the top rather than the bottom?

**Comment by Evidlo** [comment]
And the reason I needed to set `adjust_line_height` in the first place is because the 12pt font is being rendered to lines which are 18 pixels tall, while in urxvt with the bitmap font they are 16 pixels tall.

(also, for the heck of it, I tried Terminus TTF at 12pt in Libreoffice, which renders the lines 17 pixels tall)

**Comment by Evidlo** [comment]
Also, as an experiment I measured the line height of bitmap Terminus and Terminus (TTF) in various programs.

- urxvt, BDF, fontsize:16px - 16px tall
- xfontsel, BDF, fontsize:16px - 16px tall
- libreoffice, TTF, fontsize:12pt - 17px tall
- kitty (adjust_line_height 0), TTF, fontsize:12pt - 18px tall

**Comment by kovidgoyal** [comment]
kitty gets its cell height from freetype, see calc_cell_height() in
freetype.c

I have no idea how urxvt gets its line height, but emulating urxvy is
not a goal for kitty.

**Comment by Evidlo** [comment]
I didn't mean to imply that kitty should try to replicate urxvt behavior.

It seems I provided too much detail, so I'll be more explicit.  Is there any finer grain control over `adjust_line_height`?  If not, would you accept a PR which adds this?

**Comment by kovidgoyal** [comment]
Finer than 1 pixel? Not sure what that would look like.

**Comment by Evidlo** [comment]
By "finer grained control", I mean can it be made to crop from the top of the line instead of the bottom.

**Comment by kovidgoyal** [comment]
The way font rendering works is that you ask freetype to render a glyph for you. This gives you a bitmap. You line up the baseline of that bitmap with the baseline of the cell and crop the bitmap to the cell limits. There is no cropping from top or bottom. I dont really understand your issue. Just dont use adjust_line_height and there will be no cropping. The documentation of that option specifically states that reducing line height can lead to cropped glyphs. Evidently the font in question needs the full cell height to render its glyphs.

**Comment by Evidlo** [comment]
The issue is that the lines are 18 pixels tall.  I've looked through the ttf file on FontForge and the tallest glyph at 12pt is only 14 pixels tall.

**Comment by kovidgoyal** [comment]
Those are the metrics reported by FreeType for this font. Again, look at
calc_cell_height(). If you believe these are incorrect, then report it
to the developers of FreeType.
