### ISSUE TITLE
The ability to reset the terminal

### ISSUE THREAD

**Issue by SubhamoyS** [kovidgoyal/kitty#2623]
Coming from more gnome-y terminals like [tilix](https://gnunn1.github.io/tilix-web/), the only feature I cannot seem to get/configure on kitty is resetting the terminal regardless of whether or not a prompt is available. For a very very long-running process, it is sometimes super handy to clear existing output without having to get a prompt back (so that I could issue an actual command like 'reset'). Binding a shortcut to reset the shell does not help in this case.

Is there a solution to this?

If there is no present solution, but you would be open to entertaining pull requests on this, I would appreciate some hint on where to look, because I have not worked on a terminal emulator's codebase before.

Thanks in advance!

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Reset the terminal
