### ISSUE TITLE
noticable delay before kitty shows up

### ISSUE THREAD

**Issue by mighty9245** [kovidgoyal/kitty#2624]
compared to xterm (just a random terminal i installed for comparsion) there is a noticable delay before kitty shows up. i have kitty bound to a key combination and that's became pretty annoying to wait for terminal to show up. is there any way i can speed it up? i also tried with the default config but result is pretty much the same.

[here is the vid](https://www.youtube.com/watch?v=nJNvneju4BQ)

**Comment by kovidgoyal** [comment]
launch kitty as kitty -1

**Comment by mighty9245** [comment]
@kovidgoyal, so i should change by kitty binding to invoke `kitty -1` instead of `kitty`?

**Comment by Luflosi** [comment]
Yeah, that starts kitty in the single instance Mode so that it starts only once.

**Comment by mighty9245** [comment]
well, i did so. it improves the situation but also introduces a new problem: if i kill one of kitty windows the main window (this single instance) segfaults...

**Comment by Luflosi** [comment]
That shouldn't happen. Are you using the latest version 0.17.3? Can you build from source using `make debug` instead of `make` and post a stack trace? See https://sw.kovidgoyal.net/kitty/build.html.

**Comment by mighty9245** [comment]
i'm bad at getting decent stack traces, can i just send you a coredump instead? :) this one is from debug build of kitty: 
[core.zip](https://github.com/kovidgoyal/kitty/files/4576954/core.zip)

this happens only if there are more than one window spawned with `kitty -1`, killing a single window spawned with `kitty -1` works fine.

**Comment by Luflosi** [comment]
How to get a stack trace from a core dump in case you need it again in the future: https://stackoverflow.com/questions/5745215/getting-stacktrace-from-core-dump.
Looks like you're experiencing the mesa bug described in #2583. If you're using Arch Linux you can downgrade mesa with the command in the comment https://github.com/kovidgoyal/kitty/issues/2583#issuecomment-619136578 until that bug is fixed.
