### ISSUE TITLE
freezing when parent new_os_window_with_cwd windows closed

### ISSUE THREAD

**Issue by aarobc** [kovidgoyal/kitty#2625]
OS: 5.6.7-arch1-1
DE: i3 version 4.18.1
kitty: 0.17.3
shell: zsh

kitty.conf: 
```
map ctrl+shift+n new_os_window_with_cwd
```

steps to reproduce:

1.open a kitty terminal
2. navigate to any directory not in home (eg: `cd ~/Documents`)
3. use the keyboard shortcut to open a new window (ctrl+shift+n)
4. close the original terminal (type `exit` or mod+shift+q)
5. observe the newly created window either closes, or freezes up

I'm able to consistently reproduce this issue. 

I've tried disabling compton, and that makes no difference.

**Comment by kovidgoyal** [comment]
Downgrade mesa. https://gitlab.freedesktop.org/mesa/mesa/-/issues/2865
