### ISSUE TITLE
Pass variables to kitty --session

### ISSUE THREAD

**Issue by dylanirlbeck** [kovidgoyal/kitty#2627]
Hello! I couldn't think of a better title for this, but I'm wondering if there's a way to essentially pass variables to the `kitty --session` command. I have a few different projects (with similar frameworks/languages), and it'd be great to be able to pass a directory to open like this:

```
kitty --session javascript.conf some-js-project/

kitty --session reasonml.conf some-reasonml-project/
```

Thanks in advance!

**Comment by kovidgoyal** [comment]
Just use environment variables in the cd directive in your session file.

cd ${PROJECT_DIR}
