### ISSUE TITLE
Packaging: Allow extra build of only terminfo

### ISSUE THREAD

**Issue by gerion0** [kovidgoyal/kitty#2628]
Due to an inconsistency with ncurses, it is beneficial to have a seperate terminfo for kitty (for now). This is also recommendend in the packaging guide. However, I have Gentoo, so I always have to build kitty as part of the installation.

It seems, that the current packaging process is meant to build kitty as a whole and then split it into the terminfo and normal package. It would be nice, if you add two targets, that build the splitted parts on its own.
We have already done this for Gentoo in form of extra patches. See [this patch](https://678486.bugs.gentoo.org/attachment.cgi?id=618046) from my [Gentoo bug report](https://bugs.gentoo.org/678486) and the modified patches by the maintainer in Gentoo in both packages: [kitty](https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-terms/kitty/files/kitty-0.16.0-remove-terminfo.patch) and [kitty-terminfo](https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-terms/kitty-terminfo/files/kitty-terminfo-setup-0.17.2.patch).

**Comment by kovidgoyal** [comment]
I'm totally confused. The kitty release tarball contains the pre-built
terminfo files. Simply have your kitty-terminfo package copy them, no
need to build anything.

**Comment by Luflosi** [comment]
Why is the terminfo file compiled when packaging kitty and not just copied since it already exists in the source tree?

**Comment by kovidgoyal** [comment]
Because the database format varies from platform and ncurses versions.
