### ISSUE TITLE
FYI: Debian RFP submitted

### ISSUE THREAD

**Issue by sandebert** [kovidgoyal/kitty#263]
This is not an issue, just to let everyone know there's a Debian RFP (Request For Package) posted. We'll see if it makes it into the repo at some point.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886311

**Comment by kovidgoyal** [comment]
Cool, thanks for the heads-up

**Comment by sandebert** [comment]
Just a follow-up: Kitty 0.9.0 has been packaged for Debian and will hit the Unstable repo shortly. More info here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886311

**Comment by kovidgoyal** [comment]
I've added a link in the readme.
