### ISSUE TITLE
Config not being properly applied when launching from Dock or Spotlight.

### ISSUE THREAD

**Issue by nickcorin** [kovidgoyal/kitty#2630]
When launching `kitty`, some configuration options are not being applied when launching from the dock or through Spotlight.

Color schemes seem to be loaded correctly, but fonts, opacity, etc. are not being loaded.

When running `kitty` from within a `kitty` instance, the new window that's launched has all the configuration options set correctly - which to me indicates that there is no issues with the configuration itself.

AFAIK, the default configuration for `kitty` on MacOS is in `~/Library/Preferences`.

My current configuration is portable between MacOS and Linux - which uses the `XDG_CONFIG_HOME` directory for configs.

I have tried:
- creating a symlink between `XDG_CONFIG_HOME/kitty` and `~/Library/Preferences`.
- exporting `KITTY_CONFIG_DIRECTORY` to `XDG_CONFIG_HOME/kitty/`.

OS: `MacOS Catalina 10.15.4`
Kitty: `Version 0.17.2`

**Additional Info:**
When running `kitty --debug-config` within a `kitty` instance that's been launched with the missing configuration options I get a list containing all the correct configuration options (even those that have not been applied in the current instance).

**Comment by kovidgoyal** [comment]
When you launch via the GUI the env vars are different than when you
launch from inside a terminal. On macOS, launching from the GUI will
*not* read env vars you set in your shell config.

Presumably you have multiple kitty.conf
files on your machine and different ones are being picked up depending
on environment variables. Have only one kitty.conf and see the help of
the --config option (kitty --help) to learn where to place it.

**Comment by nickcorin** [comment]
I currently only have one `kitty.conf` file on my machine which is located at `~/.config/kitty/kitty.conf`.

When running `kitty --help` the `--config` help text specifies that configuration files are searched for in (and in order):
- `$XDG_CONFIG_HOME/kitty/kitty.conf`
- `~/.config/kitty/kitty.conf`
- `~/Library/Preferences/kitty/kitty.conf`
- `$XDG_CONFIG_DIRS/kitty/kitty.conf`

Since my `XDG_CONFIG_HOME` is set to `~/.config`, which means it should be found in the first path. **If** the environment variable is not set when opening with the GUI and `XDG_CONFIG_HOME` is empty, then `kitty` should find the configuration during the second search into `~./config/kitty/kitty.conf`.

Again, some of the configuration **is** being loaded, while some is not.

**Comment by kovidgoyal** [comment]
I'm afraid I dont see how loading part of the configuration while not
loading the rest is possible. And you say that it does work when
launched from inside a shell, which can only happen if some other
kitty.conf file is being loaded.

**Comment by nickcorin** [comment]
I think I've found the cause of issue here.

You say that environment variables are **not** passed when opening from the GUI. My `kitty` config includes other configuration files based on environment variables.

Example snippet:
```
#: Fonts {{{
include ${PLATFORM}-fonts.conf
#: }}}
```

`PLATFORM` is being set inside my `.zshrc`, which I'm assuming from your comment would be an empty string when opening with the GUI - hence that configuration not being loaded in.

@kovidgoyal What would you suggest to achieve this behaviour?

**Comment by Luflosi** [comment]
You could try to set the environment variable system wide but since that's not so easy on macOS you could also put `include platform-fonts.conf` in your config and then have a symlink there that links to the correct file.

**Comment by kovidgoyal** [comment]
set your environment variables system wide rahter than in zshrc

**Comment by nickcorin** [comment]
@Luflosi your suggestion I think the best solution. I just moved the platform specific logic from `kitty.conf` to the `Makefile` that creates the symlinks.

Everything is working as intended.

Thanks!
