### ISSUE TITLE
inconsistent size/DPI/DPR ?

### ISSUE THREAD

**Issue by mckellyln** [kovidgoyal/kitty#2631]
Hi,
Thanks for kitty.
Sometimes when I start a new kitty the size is huge.  So I change the font size and window size smaller.  And then the next day or whenever soon when I start a new kitty the size is too small and I have to change the font size and window size larger.
I have a laptop with an external monitor - and its configured only for the external monitor and that has not changed.  The external monitor is 4k.  I know with other terminals before I had a similar issue and I worked around it by setting an env var for the DPR value before launching.  Is there such a setting for kitty ?  I'm on ubuntu 18.04 with wayland (and xwayland).
btw - is there a way to specify the starting location/position/geometry (not rows/cols but position) ?
thx again for your work,
-m

**Comment by mckellyln** [comment]
I'm using 0.17.3

**Comment by kovidgoyal** [comment]
If you are using X11, you need to set the Xft.dpi property for
consistent DPI. And no starting position is the responsibility of the window
manager, not kitty.

**Comment by mckellyln** [comment]
ok, thank you.  I have not explcitly stated I want to use X11, and in fact if I do:
KITTY_ENABLE_WAYLAND=1 kitty --debug-config
I still see:
Running under: X11
Is there another way to not use X11 ?
-m

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.linux_display_server

**Comment by mckellyln** [comment]
ok, awesome, thx.
