### ISSUE TITLE
Letters start disappearing on macOS

### ISSUE THREAD

**Issue by maksbotan** [kovidgoyal/kitty#2632]
Hi.

I have a very strange bug on macOS. Sometimes certain letters just stop to render:

![image](https://user-images.githubusercontent.com/275614/81148870-c06cce80-8f85-11ea-92a7-80cb2246555b.png)

![image](https://user-images.githubusercontent.com/275614/81148876-c5318280-8f85-11ea-8e59-ed9f589573a1.png)

I've built kitty from commit fc0095f505efaf53aeda96d660df907cf48ea819 via `make app`.

My config:

```
background #282828
foreground #ebdbb2

font_family Hack Nerd Font
```

**Comment by kovidgoyal** [comment]
Does this happen from the beginning, or after some time? Does it happen
only with the built from source kitty or the released one? Is there any
output printed to stderr if you run kitty from another terminal? Does it
happen with the default config?

**Comment by maksbotan** [comment]
After some time. I was unable to spot the exact moment. Probably it happens only after resume from suspend.

I'll try to run kitty from another terminal and see if there is anything on stderr.

With released binary version I have another problem: I can't type non-ascii letters in bash prompt, they are displayed as escape codes (`\231` and so on). In neovim, on another hand, they work fine.

**Comment by kovidgoyal** [comment]
That will be because of LANG/LOCALE environment settings. Set the correctly in your shell rc files and you will be fine.

**Comment by maksbotan** [comment]
That worked. Strange that on source builds I don't have to set LANG, but okay. Let's see if I can reproduce disappearing letters.

**Comment by maksbotan** [comment]
So far I got this in stderr:

```
[127 11:14:10.675327] [PARSE ERROR] Unknown OSC code: 7
```

But it seems to work fine.

**Comment by kovidgoyal** [comment]
It will be because when building from source you are running from a terminal where LANG is already set.
