### ISSUE TITLE
Background opacity does not seem to work anymore

### ISSUE THREAD

**Issue by JasonLighthunter** [kovidgoyal/kitty#2633]
Suddenly my terminal background is not transparent anymore.

Distro: arcolinux 
Kernel: 5.6.11-arch1-1
Terminal Font: otf-fira-code 3.1-1
Compositor: picom 8-2
WM: i3-gaps 4.18.1-1

**Comment by kovidgoyal** [comment]
I dont see how that has anything to do with kitty. Presumably your
compositor has stopped working.
