### ISSUE TITLE
Alternate screen reported as unsupported via DECRQM

### ISSUE THREAD

**Issue by aslpavel** [kovidgoyal/kitty#2636]
When requested via [DECRQM](https://vt100.net/docs/vt510-rm/DECRQM.html) kitty reports alternate screen mode DEC mode 1049 as unsupported. When it is obviously supported.
**How it fails:**
```
$ cat
^[[?1049$p
^[[?1049;0$y   # 0 - indicates that mode is unsupported
```
**Expected behavior:**
- when enabled
```
$ cat
^[[?1049$p
^[[?1049;1$y
```
- when disabled
```
$ cat
^[[?1049$p
^[[?1049;2$y
```
`DECRQM` is obviously supported by kitty as it used to query for kitty specific mode 2017.

**Comment by aslpavel** [comment]
Thank you for the quick fix!
Sorry for reporting in the same issue but same problem happens for DEC modes 1000 - VT200_MOUSE, 1006 - SGR_EXT_MODE_MOUSE and  1003 - ANY_EVENT_MOUSE.

**Comment by aslpavel** [comment]
And maybe we should also allocate DEC mode `KITTY_GRAPHIC_PROTO = 2018` for kitty graphic protocol support, which should return "\x1b[?2018;3$y" which would indicate that it is permanently set?

**Comment by kovidgoyal** [comment]
Does anything actually use this detection though?? As for the graphics
protocol it already has its own way to query support.

**Comment by aslpavel** [comment]
I was hoping to use them. And iTerm definitely returns them correctly. Since mouse support is controlled via DEC, and kitty DECRQM handles and supports mouse I think it is reasonable to assume that it should be handled correctly. As for graphic protocol I feel it is more consistent to indicate support via DEC same way it is done for keyboard support?

**Comment by aslpavel** [comment]
Is there a way to detect kitty graphic support without setting timeout and waiting for response? DECERQ is supported by a lot of the terminals, and by default they would indicate that kitty graphics is unsupported.

**Comment by kovidgoyal** [comment]
On Sat, May 09, 2020 at 08:10:02AM -0700, Pavel wrote:
> I was hoping to use them. And iTerm definitely returns them correctly. Since mouse support is controlled via DEC, and kitty DECRQM handles and supports mouse I think it is reasonable to assume that it should be handled correctly. As for graphic protocol I feel it is more consistent to indicate support via DEC same way it is done for keyboard support?

The graphics protocol query mode allows you to query both support for the
protocol and types of transfers available simultaneously which is much
more efficient. 

And what would you need to query the mouse modes for? If you are going
to handle mouse events just use the SGR mode which is the least obsolete
of the lot.

Indeed, I dont think there are any modern terminals that dont support
it. 

That said I have no objection to adding DECQRM support for mouse modes,
should be a simple patch.

**Comment by kovidgoyal** [comment]
You have to set a timeout and wait for a response to DECQRM as well. Any
form of querying of the terminal emulator requires setting a timeout and
waiting for a response.

**Comment by aslpavel** [comment]
> You have to set a timeout and wait for a response to DECQRM as well. Any
> form of querying of the terminal emulator requires setting a timeout and
> waiting for a response.

Indeed all of them require timeout but if kitty graphics is unsupported, implementation would have to wait whole timeout before proceeding while DECQRM would result in mediate response in most terminals

**Comment by kovidgoyal** [comment]
That is true if the terminal does not support DECQRM as well. And if you
want a way to query for the kitty image protocol, you can just query the
terminal name using the Da sequence. Or in fact you can use TIOCGWINSZ
to check if the terminal reports non-zero pixel sizes for the window,
which IIRC only kitty and xterm do. This requires no waiting at all,
just a single system call.

**Comment by aslpavel** [comment]
Just check this on four terminals `iTerm`, `Alacritty`, `wezterm`, `kitty` all of them return pixel size correctly with TIOCGWINSZ. So it is not only `kitty`. For example if I write a program that shows a picture on the screen and I want to use kitty protocol if available just detection of this feature would slow down this program on other terminals that do not support this protocol.

**Comment by kovidgoyal** [comment]
So query the terminal name, that way you can detect a whole bunch of
things apart from just graphics protocol. See https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Device-Control-functions

**Comment by kovidgoyal** [comment]
For completeness, you make the query with:
```
printf '\eP+q544e\e\\'; read
```
and get back the terminal name, hex encoded, for kitty it would be
```
^[P1+r544e=787465726d2d6b69747479^[\
```

which when decoded gives you xterm-kitty

**Comment by trygveaa** [comment]
> So query the terminal name, that way you can detect a whole bunch of things apart from just graphics protocol.

Isn't that a bad idea? What if other terminal emulators want to add support for kittys graphics protocol?

**Comment by Luflosi** [comment]
> Isn't that a bad idea? What if other terminal emulators want to add support for kittys graphics protocol?

I agree, this seems like a bad idea.

**Comment by kovidgoyal** [comment]
So far, none have, and the graphics protocol is several years old, so I
am sceptical any ever will. And if they do, we can revisit, or OP can
simply add the name of that terminal to the list to check. I dont like
adding DECQRM codes because there is no central authority for them, and
every number added just means, that number becomes permanently
contested. In the case fo the keyboard protocol there is no pre-existing
detection method, so DECQRM was used.

**Comment by trygveaa** [comment]
> So far, none have, and the graphics protocol is several years old, so I am sceptical any ever will.

I know of a person that says he has, but he hasn't released the application or code to anyone yet.

> And if they do, we can revisit, or OP can simply add the name of that terminal to the list to check.

That depends on how many that uses this solution I guess. Suddenly you end up with the same situation as xterm today, where you have to call the terminal xterm-kitty to get applications to work properly, and there are too many to change.

> I dont like adding DECQRM

I don't know much about DECQRM, so I won't argue for or against that. I see your points about it.

**Comment by ctrlcctrlv** [comment]
To support any type of terminal that supports Kitty graphics, I don't understand what's wrong with doing the APC code with `a=q` and seeing if you get a reply or not? Why do you even need anything else?

**Comment by kovidgoyal** [comment]
On Sun, May 10, 2020 at 02:30:42AM -0700, Fredrick Brennan wrote:
> To support any type of terminal that supports Kitty graphics, I don't understand what's wrong with doing the APC code with `a=q` and seeing if you get a reply or not? Why do you even need anything else?

The issue is that a terminal that does not support the protocol will not
reply at all, so the application has to wait for a timeout before
deciding to fallback to some other method, or abort or wahtever.

**Comment by ctrlcctrlv** [comment]
@kovidgoyal I was under the impression that the terminal will block while waiting for an APC response if one is going to be provided. So why can't we send APC `_Gi` with `a=q`, then immediately after do some other action that we can test for?

So for example:

* We do `_Gi` w/`a=q`
* We do any other blocking action e.g. TIOCGWINSZ

And:

* If we receive the reply to TIOCGWINSZ but no APC reply, we know none is coming.
* If we receive the APC reply *and* the TIOCGWINSZ reply, we know Kitty graphics are supported.

**Comment by kovidgoyal** [comment]
On Sun, May 10, 2020 at 03:48:47PM -0700, Fredrick Brennan wrote:
> @kovidgoyal I was under the impression that the terminal will block while waiting for an APC response if one is going to be provided. So why can't we send APC `_Gi` with `a=q`, then immediately after do some other action that we can test for?
> 
> So for example:
> 
> * We do `_Gi` w/`a=q`
> * We do any other blocking action e.g. TIOCGWINSZ

TIOCGWINSZ comes from the kernel not the terminal emulator. The terminal
emulator uses TIOCSWINSZ to set the values in the kernel. However, in
the general case one can certainly do some other escape code that
requires a response from the terminal emulator, such as DA or even the
code I posted above to get the terminal name. And if the response to
that is received but not the response to the graphics escape code,
assume it is not supported. 

This would assume that the terminal emulator replies to received escape
codes in a FIFO manner, which is not guarantee but I think is the case
in most terminal emulators, certainly in kitty.

**Comment by ctrlcctrlv** [comment]
> This would assume that the terminal emulator replies to received escape
codes in a FIFO manner, which is not guarantee but I think is the case
in most terminal emulators, certainly in kitty.

@kovidgoyal Sure, and even in the rare TE that isn't FIFO, I don't think it's a problem at all for us to declare that for a terminal emulator to be standards-compliant (w.r.t Kitty graphics protocol standards document), it *must* immediately block on receiving any APC beginning with `G` and process no other escape code until it deals with the APC.

I can write this into the documentation and PR you it, added to &sect; Detecting available transmission mediums, to be renamed &sect; Querying support and transmission mediums, if that sounds OK with you.

**Comment by kovidgoyal** [comment]
On Sun, May 10, 2020 at 09:51:50PM -0700, Fredrick Brennan wrote:
> @kovidgoyal Sure, and even in the rare TE that isn't FIFO, I don't think it's a problem at all for us to declare that for a terminal emulator to be standards-compliant (w.r.t Kitty graphics protocol standards document), it *must* immediately block on receiving any APC beginning with `G` and process no other escape code until it deals with the APC.

I'm not sure we should specify this in general. It places unnecessary
restrictions on internal implementation details of the TE. But we can
certainly specify it for the query APC codes used for detection of
capabilities.

> 
> I can write this into the documentation and PR you it, added to &sect; Detecting available transmission mediums, to be renamed &sect; Querying support and transmission mediums, if that sounds OK with you.

Sounds fine.

**Comment by aslpavel** [comment]
Sounds like a lot of hassle instead adding DEC flag with [DECRPM](https://vt100.net/docs/vt510-rm/DECRPM.html) 3 (Permanently set) which is specifically designed for cases like this? It would be literally one line of code and one line in spec.

**Comment by ctrlcctrlv** [comment]
A decision has already been made and it was already explained to you why it was made. No one "allocates" DEC modes. There is no "spec" besides the hardware capabilities of VTx00. We've come up with a simple way regardless to figure out if Kitty graphics support is available that doesn't rely on XTGETTCAP TN.

If that simple method is too much hassle for you, implementing a terminal emulator is way too much hassle for you.

**Comment by dankamongmen** [comment]
@aslpavel, you might want to look at Notcurses to see how all of this stuff can be functionally, efficiently, and portably accomplished.

and fwiw, WezTerm now has a compliant Kitty graphics implementation (you can again look at Notcurses to see support for three distinct level of the Kitty graphics protocol).
