### ISSUE TITLE
printing esc code for title causes print to hang

### ISSUE THREAD

**Issue by mckellyln** [kovidgoyal/kitty#2637]
Hi,
```
print -Pn '\033]2;%12<..<%~%<<%\007'
```
causes my zsh to hang when in kitty.  It does not seem like a kitty issue, but this does not happen in any other terminal.  Any ideas why ?
thx,
-m

**Comment by mckellyln** [comment]
I will try out the latest zsh ...

**Comment by kovidgoyal** [comment]
Running that command works fine in my zsh (version 5.8).

**Comment by mckellyln** [comment]
I discovered if I remove the trailing % then it works ok; I've had that in there incorrectly for years!
thx, -m
