### ISSUE TITLE
Exiting a `new_os_window_with_cwd` window also causes parent window to exit

### ISSUE THREAD

**Issue by dharmab** [kovidgoyal/kitty#2640]
My `kitty.conf`:

```
# https://sw.l.net/kitty/conf.html
font_size 14.0

# Visual tweaks
window_border_width 0
url_style single
enable_audio_bell no

# Cursor tweaks
cursor_blink_interval 0.5

# Mouse tweaks
mouse_hide_wait 0.2

# Infinite scrollback
scrollback_lines -1

# Keyboard shortcuts
clear_all_shortcuts yes

map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard

map super+enter new_os_window_with_cwd
```

Reproduction steps:

1. Open a Kitty window
1. Press super+enter to open a second window
1. In the second window, type `exit` or press Ctrl+D

Expected behavior:

The second window should close while the first remains open.

Actual behavior:

Both the first and second windows close. 

This will also happen with large "trees" of open windows, which can be quite surprising if I've opened 4 or 5 windows while working on a complex codebase for my compiler, VMs, etc.

Kitty version: 0.17.3
WM: i3
OS: Arch Linux

**Comment by kovidgoyal** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2865
