### ISSUE TITLE
Fonts in /usr/local/share/fonts not displayed

### ISSUE THREAD

**Issue by vaskark** [kovidgoyal/kitty#2641]
I moved some of my fonts from `.local/share/fonts` to `/usr/local/share/fonts` and now they are no longer available in kitty (kitty list-fonts). Other terminals are fine with these fonts in their new location. 

I have run `fc-cache -vf` and `sudo dpkg-reconfigure fontconfig`.

Any help would be appreciated.
I'm on Ubuntu 20.04 with updated kitty (git).

**Comment by kovidgoyal** [comment]
kitty uses fontconfig to query for fonts. Are they showing up in 

fc-list : family spacing | grep -e spacing=100 -e spacing=90

**Comment by vaskark** [comment]
Forgive me. I should have stated that I already added a statement in fontconfig to allow this font to be used:

```
<match target="scan">
    <test name="family">
        <string>scientifica</string>
    </test>
    <edit name="spacing">
        <int>90</int>
    </edit>
</match>
```

It was showing when this font was stored locally just fine. Now, not (as stated in my original post).

**Comment by ctrlcctrlv** [comment]
No @vaskark, regardless of whether or not you have any special Fontconfig configuration, Kitty still uses Fontconfig. It's a library that tells Kitty what fonts are on the system and some information about them.

**Comment by vaskark** [comment]
I'm not sure I'm following your post. That above statement allowed _scientifica_ to be used in kitty. Without it, that font **did not** show up for use.

**Comment by ctrlcctrlv** [comment]
Please just run the command Kovid gave you and show me the output. I'm too tired to explain it.

**Comment by vaskark** [comment]
```
Hurmit Nerd Font Mono:spacing=100
DejaVu Sans Mono:spacing=100
MesloLGS Nerd Font Mono:spacing=100
Nimbus Mono PS:spacing=100
Liberation Mono:spacing=100
Courier 10 Pitch:spacing=100
TakaoGothic,Takaoゴシック:spacing=90
Material Icons:spacing=100
Nimbus Mono L:spacing=100
UbuntuMono Nerd Font Mono:spacing=100
siji:spacing=100
Iosevka Custom:spacing=100
Noto Color Emoji:spacing=100
Ubuntu Mono:spacing=100
```

**Comment by ctrlcctrlv** [comment]
OK, so there's no `scientifica` there, so this isn't Kitty's fault. 

Fontconfig either can no longer find the font at all, or it's no longer associating your custom configuration with the font.

To see if it can find the font at all, remove the `grep` and see if it's in the list, and what it's `spacing` is listed as.

**Comment by vaskark** [comment]
I noticed that `fc-cache -vf` was showing me an error related to `~/.cache/fontconfig`. I've deleted that folder and tried again. Seems to work fine now.

fc-list : family spacing | grep -e spacing=100 -e spacing=90

`scientifica:spacing=90`

Removing grep from that command produced nothing at all.

**Comment by ctrlcctrlv** [comment]
Glad I could help :-)

Probably Fontconfig just choked when a font it was expecting to be there went missing. If you can find a reproducible case the Freedesktop team probably wants to know about it. Make sure to check their tracker first though!

**Comment by vaskark** [comment]
I shall. Thanks for all your effort. It's very much appreciated.
