### ISSUE TITLE
Kitty's update notification.

### ISSUE THREAD

**Issue by KoO-303** [kovidgoyal/kitty#2642]
I have already updated Kitty to 0.17.4 but the notification keeps coming up every time I open a new kitty based application.

Debian 10 bullseye
i3wm
exec --no-startup-id dunst &  <<< maybe but not sure if dunst and kitty's own notification could be clashing.

Thanks for your Work.

**Comment by kovidgoyal** [comment]
What is dunst??

**Comment by kovidgoyal** [comment]
And note that you can turn off the update notification in kitty.conf

**Comment by ctrlcctrlv** [comment]
(Dunst is an implementation of a notification server as required by the GNOME [Desktop Notifications Specification](https://developer.gnome.org/notification-spec/). Essentially, it provides desktop notifications to Linux users who, for some reason known only to them, fail to use KDE :-P)

**Comment by KoO-303** [comment]
> And note that you can turn off the update notification in kitty.conf

Thanks kovidgoyal I have now changed the line to zero. update_check_interval 0

**Comment by KoO-303** [comment]
> (Dunst is an implementation of a notification server as required by the GNOME [Desktop Notifications Specification](https://developer.gnome.org/notification-spec/). Essentially, it provides desktop notifications to Linux users who, for some reason known only to them, fail to use KDE :-P)

Keep dreaming on KDE I am no GUI user i3 or SpectrWM and the world is a better place. :-)

**Comment by kovidgoyal** [comment]
Well I cannot replicate and looking at the code it will never show that popup unless the latest version is newer than the current version and even then shows the popup only once, so, given that you have turned it off, am closing.
