### ISSUE TITLE
force kitty so use xwayland as backend 

### ISSUE THREAD

**Issue by salkin-mada** [kovidgoyal/kitty#2648]
System: Arch linux, Sway wm

I am normally **not** in the need of opening kitty in X under Wayland. But for sharing the kitty window during jitsu meet or other conference platform sessions it is needed.

When unsetting the wayland display `unset WAYLAND_DISPLAY` apps then try to open with XWayland. This works with some native Wayland terminal emulators and other native Wayland apps.

But with kitty, i guess after the [KITTY_ENABLE_WAYLAND env var is longer needed](https://github.com/kovidgoyal/kitty/issues/1525#issuecomment-479529432) , I cant seem to figure out how to force/make kitty to open with X.
`unset WAYLAND_DISPLAY && kitty` stills opens a kitty with Wayland. not X.
So i tried exporting it to an empty string. (which also works with other wayland native apps) `export WAYLAND_DISPLAY="" && kitty` here i found kitty throwing an GLFW error. 
It seems kitty still wants to open with wayland.
```
[132 22:23:07.604940] [glfw error 65544]: Wayland: Failed to connect to display
GLFW initialization failed
```

Is there an env var like `KITTY_DISABLE_WAYLAND` or maybe `KITTY_FORCE_UNSECURE_X` 

:=) and thanks for making this wonderful terminal emulator.

**Comment by Luflosi** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.linux_display_server might be what you want.

**Comment by trygveaa** [comment]
> Is there an env var like KITTY_DISABLE_WAYLAND

Did you try this? It does exist. From the [changelog](https://sw.kovidgoyal.net/kitty/changelog.html#id15):

> Wayland: Use the kitty Wayland backend by default. Can be switched back to using XWayland by setting the environment variable: KITTY_DISABLE_WAYLAND=1

**Comment by salkin-mada** [comment]
> Did you try this? It does exist. From the [changelog](https://sw.kovidgoyal.net/kitty/changelog.html#id15):
> 
> > Wayland: Use the kitty Wayland backend by default. Can be switched back to using XWayland by setting the environment variable: KITTY_DISABLE_WAYLAND=1

thanks! yeah. this dont seem to work here. `xeyes` are not moving.
when doing `KITTY_DISABLE_WAYLAND=1 && kitty` atleast. 
Maybe something I am missing?

**Comment by Luflosi** [comment]
Try `KITTY_DISABLE_WAYLAND=1 kitty`.

**Comment by salkin-mada** [comment]
> https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.linux_display_server might be what you want.

nice. this is new info to me :-)
but as far as I understand, setting this in my kitty.conf will make kitty open with X11 as backend as new default in Wayland. Instead of auto detecting Wayland, kitty just goes for X11.
How could i use this as a command? as a kitty.config like so maybe?:
`kitty --config linux_display_server x11`

**Comment by salkin-mada** [comment]
> Try `KITTY_DISABLE_WAYLAND=1 kitty`.

nope. no cigar.   :-)
thanks. really appreciate your help !

**Comment by Luflosi** [comment]
> How could i use this as a command? as a kitty.config like so maybe?

Like so:
```bash
kitty -o linux_display_server=x11
```

**Comment by salkin-mada** [comment]
> > How could i use this as a command? as a kitty.config like so maybe?
> 
> Like so:
> 
> ```shell
> kitty -o linux_display_server=x11
> ```

yes. niice. this works indeed. I will go and check the `-o` option, seems like a good thing to know about ;-)

**Comment by Luflosi** [comment]
Glad it works now.
I had a look at the code and unsetting `WAYLAND_DISPLAY` or setting `KITTY_DISABLE_WAYLAND` to any value should disable Wayland as long as the `linux_display_server` config option is set to the default value of `auto`. Maybe you changed it to `wayland` in your `kitty.conf`? You can use `kitty --debug-config` to see which config options are different from the default.
