### ISSUE TITLE
Feature idea: SublimeText-like "minimap" that shows shape of terminal output

### ISSUE THREAD

**Issue by kovasap** [kovidgoyal/kitty#2649]
I frequently end up running commands in Kitty that spew out a lot of output.  It would be convenient if I could see the shape of this output in a "minimap" like format as Sublime Text and other editors do for code.  Here is an example of what I'm talking about: https://user-images.githubusercontent.com/630224/27031735-c66b5f92-4f71-11e7-802f-696b788b9ad8.gif.  With this, I could with just one click find the part of the output I'm interested in, without piping the scrollbar buffer to a text editor or a pager, for example.  

Is this possible with Kitty today?  Has anyone done something like this before?

**Comment by kovidgoyal** [comment]
I havent ever used such a feature, and straight off the bat I dont see how it would be useful. Why would the shape of text help you to navigate to it, in the general case, better than just searching for the text you want to find? Also I am not a big mouse user, so dragging/clicking to find things doesn't seem appealing to me. That said this feature should be possible to implement yourself using kittens. Send the scrollback buffer to a kitten and have it render a "shape" for it and respond to clicks and then it can use remote control to scroll the parent window in response to the clicks. https://sw.kovidgoyal.net/kitty/kittens/custom.html
