### ISSUE TITLE
Mouse click will not place cursor after the 250th column

### ISSUE THREAD

**Issue by WaterSibilantFalling** [kovidgoyal/kitty#2650]
Hi, 

As per the subject line, in Kitty (WSL)  clicking the mouse in the terminal window does not place the cursor after the 250th column.  I am seeing this in a maximized Kitty window with a split vim 'window' inside it: on the LHS, the mouse can be placed anywhere, on the RHS, only first 116 columns are available to the mouse (for a total width, in Kitty, of 250 columns). 

At a lower column number, the cursor is placed. 
If I click towards the end of a longer line, the cursor is not placed. 

I have played with the settings, but nothing seems to change this issue. 
I have the latest kitty 0.73.2.14p  It is running within windows, supporting a WSL bash system.

**Comment by kovidgoyal** [comment]
This is a limitation of whatever program/shell you are running in the
terminal. It is using an outdated mouse protocol.

**Comment by kovidgoyal** [comment]
And from the version number you posted, you want https://github.com/cyd01/KiTTY/

**Comment by WaterSibilantFalling** [comment]
Thank you.
