### ISSUE TITLE
selecting from buffer via mouse clicks

### ISSUE THREAD

**Issue by basiliscos** [kovidgoyal/kitty#2651]
Hi,

In `lilyterm` I usually select multi-screen text in the buffer via clicking `ctrl+shift+LBM` (begin) and then 
`ctrl+shift+LBM` (end). I haven't found that feature in kitty, but may be I miss something. Click and scroll to the end of the section is very unhandy for multil-line text.

Thanks for Killty :)

**Comment by trygveaa** [comment]
If I understood you correctly, you can do it with right click.

**Comment by basiliscos** [comment]
Originally all is done  via left button click. I.e. the same as on the browser: I click on on "Thanks" in my first message, than I shift+click on "Hi", and voila - all I need is selected.

**Comment by kovidgoyal** [comment]
You use right click to extend selections in kitty. https://sw.kovidgoyal.net/kitty/#mouse-features
