### ISSUE TITLE
Command not found: scrollback_pager

### ISSUE THREAD

**Issue by kylevon** [kovidgoyal/kitty#2653]
(shell: zsh) I just started using kitty today, I haven't done any configuration on kitty and I would assume scrollback_pager should would off the bat. How could I send some debugging information if that is the case?

**Comment by kovidgoyal** [comment]
The default scrollback_pager commadn is less. If you dont have it
installed on your system, install it or change it in kitty.conf to
something else.

**Comment by kylevon** [comment]
But the command that is not found is scrollback_pager, not less.

**Comment by kovidgoyal** [comment]
There is no command named scrollback_pager. Either you have set shell in
your kitty.conf to scrollback_pager or you are running kitty passing
scrollback_pager as a command line argument.

**Comment by kylevon** [comment]
Oh, I'm sorry, I thought scrollback_pager was an inbuilt command. It is a variable that is used to be able to see the scrollback buffer using ctrl+shift+h.
