### ISSUE TITLE
kitty ncmpcpp + albumart

### ISSUE THREAD

**Issue by KoO-303** [kovidgoyal/kitty#2656]
I can't get album art to work with kitty and ncmpcpp with URxvt it works fine but not with kitty.
Just don't understand why it doe's not work with kitty. Any help would be welcomed.

Below is the script I use to show album art using URxvt. art.sh

https://ibb.co/k85fTZ0
```
#!/bin/bash

MUSIC_DIR="/var/lib/mpd/music"

COVER="/tmp/cover.png"

function reset_background
{
    printf "\e]20;;100x100+1000+1000\a"
}

{
    album="$(mpc --format %album% current)"
    file="$(mpc --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    if [[ -n "$src" ]] ; then
        #resize the image's height to 300px & extent it to cover the urxvt length
        convert "$src" -resize 300x -extent 300x298 "$COVER"
        if [[ -f "$COVER" ]] ; then
        
           #-- original script --
           #scale down the cover to 30% of the original
           #place it 1% away from left and 50% away from top.
           #printf "\e]20;${COVER};70x70+0+4:op=keep-aspect\a"
           #---------------------
           
           #no need to scale down, i have extent it
           printf "\e]20;${COVER};30x30+50+95:op=keep-aspect\a"
        else
            reset_background
        fi
    else
        reset_background
    fi
} &

```

**Comment by kovidgoyal** [comment]
I have no idea what that script does, if you want to display images in
kitty, use the icat kitten https://sw.kovidgoyal.net/kitty/kittens/icat.html

**Comment by ctrlcctrlv** [comment]
For future reference, OSC command `2`, which in most terminals only sets the terminal title, has been extended to display images in `rxvt-unicode` (`urxvt`), with a non-default option known as "pixbuf". This is a very very bad idea, much worse than our use of APC codes. The only way to choose images is with local filenames, meaning it does not, and cannot, work on remote computers.

We definitely should not copy this "protocol", they should copy ours.

**Comment by KoO-303** [comment]
> For future reference, OSC command `2`, which in most terminals only sets the terminal title, has been extended to display images in `rxvt-unicode` (`urxvt`), with a non-default option known as "pixbuf". This is a very very bad idea, much worse than our use of APC codes. The only way to choose images is with local filenames, meaning it does not, and cannot, work on remote computers.
> 
> We definitely should not copy this "protocol", they should copy ours.

Thanks for the reply & information.
