### ISSUE TITLE
Issues with previews in kitty with nnn

### ISSUE THREAD

**Issue by jarun** [kovidgoyal/kitty#2658]
We are working on a plugin to enable previews in kitty with [`nnn`](https://github.com/jarun/nnn). The following PR has the sample implementation: https://github.com/jarun/nnn/pull/574

When we try to preview anything, the preview is shown but we see the following issues:

1. It breaks `nnn`'s input (you have to press keys multiple time for one to be registered)
2. We see the following backtrace when `nnn` is quit (needs multiple `^Q` due to problem 1):

```
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 121, in <module>
  File "kitty/__main__.py", line 117, in main
O  File "kitty/__main__.py", line 23, in remote_control
  File "kitty/remote_control.py", line 187, in main
  File "kitty/remote_control.py", line 136, in do_io
  File "kitty/remote_control.py", line 115, in simple_recv
OSError: [Errno 5] Input/output error
```

It's very much possible we are missing something here. Can you please take a look what might be the reason?

**Comment by kovidgoyal** [comment]
You probably need to use the option to have kitty @ not wait for a response.
--no-response

**Comment by jarun** [comment]
That works, thank you!

**Comment by kovidgoyal** [comment]
And generally speaking, FYI, if you are using remote control, without --listen-on that means remote control works by writing to and reading from /dev/tty. You cannot have multiple programs reading/writing to /dev/tty at the same time, so nnn has to suspend its own handling of /dev/tty while kitty @ is running.

**Comment by jarun** [comment]
Thanks for the note!

**Comment by jarun** [comment]
An additional question on this... if I try to preview an image with the following command:

    kitty +kitten icat "$1"
Only the very first image is previewed but post that no preview (for any type of file) works. Is any _cleanup_ required after previewing an image?

**Comment by kovidgoyal** [comment]
No, icat can dispay any number of images. Just run it in a shell to check for yourself

**Comment by jarun** [comment]
Yes, that's what I was banking on. However it's not working as I expected. This is the patch we are trying:

```diff
diff --git a/plugins/preview-tui b/plugins/preview-tui
index 3ebf195..16af95f 100755
--- a/plugins/preview-tui
+++ b/plugins/preview-tui
@@ -35,6 +35,8 @@ preview_file () {
     elif [ "${mime%%/*}" = "text" ] ; then
         # Print file head
         head -n $lines "$1" | cut -c 1-"$cols"
+    elif [ "${mime%%/*}" = "image" ] ; then
+        kitty +kitten icat "$1"
     else
         # Binary file
         echo "-------- Binary file --------"
@@ -60,6 +62,12 @@ fi
 
 if [ -e "${TMUX%%,*}" ] && [ "$(tmux -V | cut -c6)" -eq 3 ] ; then
     tmux split-window -e "NNN_FIFO=$NNN_FIFO" -e "PREVIEW_MODE=1" -dh "$0" "$1"
+elif [ "$TERM" = "xterm-kitty" ] \
+     && kitty @ launch --no-response \
+        --title "nnn preview" --keep-focus --cwd="$PWD" \
+        --env "NNN_FIFO=$NNN_FIFO" --env "PREVIEW_MODE=1" \
+        "$0" "$1" > /dev/null ; then
+    :
 else
     PREVIEW_MODE=1 $TERMINAL -e "$0" "$1" &
 fi
```

**Comment by kovidgoyal** [comment]
Use --silent and you can also try --transfer-mode=stream though that should not make a difference.

**Comment by jarun** [comment]
If i use the `--silent` option I get: `Unknown option: --silent`.

I am on `kitty 0.17.4`.

**Comment by jarun** [comment]
OK. I see it's an `icat` option.

**Comment by jarun** [comment]
Tried `--silent` with `icat`. Still the same.

**Comment by jarun** [comment]
`--stdin=no` does it! Thank you so much for the pointers!

**Comment by leovilok** [comment]
@kovidgoyal the issue with using `--no-response` in our case is that the command don't fail anymore if remote control is not activated. What's the best / most efficient way of knowing if remote control is on?

**Comment by kovidgoyal** [comment]
You would need to run some command that produces output and check its
return code, like say kitty @ ls which willl only ever fail if remote
control is disabled.

**Comment by kovidgoyal** [comment]
But note that if you do this you *must not* write anything to the tty
until after the kitty @ ls program finishes.

**Comment by leovilok** [comment]
This works now, thank you!
