### ISSUE TITLE
Not getting focus events with tmux

### ISSUE THREAD

**Issue by infokiller** [kovidgoyal/kitty#2659]
When I'm running vim in tmux in kitty, vim doesn't seem to get focus events.
It does work when running kitty without tmux, or vim in tmux in termite.

To debug, I tried to run the following in both kitty and termite, with and without a focus event:

```
script --command='vim' --quiet --log-in kitty_focus_input
```

The diff of the terminal input in both kitty and termite between the script run without focusing and the one with is `\e[O\e[I`, so I would expect them to work the same.

Any pointers/suggestions on how to figure this out?
Thanks!

**Comment by kovidgoyal** [comment]
tmux screws with TERM, even with escape codes that pass between the
application and the terminal emulator. It could be pretty much anything.
You will need to read the vim source code to figure out what it uses to
detect support for focus events in the terminal. Then you will need to
read the tmux source code to figure out why tmux is blocking whatever
that is, and then figure out how to configure/patch tmux to not do that.

**Comment by kovidgoyal** [comment]
To help you get started, here is the riginal patch that was propsed for
adding support for this to vim: https://groups.google.com/forum/#!topic/vim_dev/ASn8QqQqVe0
I have no idea if this was the eventual patch that made it in, or
something else, but it should give you a clue where to start looking.

**Comment by kovidgoyal** [comment]
And from https://github.com/vim/vim/issues/609 looks like that patch never made it in, which means your vim install is using some vimscript hack for focus events and that hack is what you will need to fix.

**Comment by kovidgoyal** [comment]
https://github.com/tmux-plugins/vim-tmux-focus-events

**Comment by infokiller** [comment]
Thanks for the help!
I'm actually using neovim which should support focus events properly.
I'll try your suggestions.

**Comment by CallumHoward** [comment]
Hi @infokiller, curious if you found a solution. I'm also using Neovim and I have `tmux set-option -g focus-events on` in my `tmux.conf`. I have tried with `TERM=tmux-256color` and `TERM=xterm-kitty`. 

The focus events do work outside of Tmux, and they also work inside Tmux when I'm using the macOS Terminal.app.

**Comment by infokiller** [comment]
@CallumHoward it works for me when I'm testing it now, not sure what changed. Using tmux 3.2, Kitty 0.19.3

**Comment by CallumHoward** [comment]
@infokiller thanks, I updated Tmux 3.1c -> 3.2 and reloaded everything and now it seems to work well. From the [changelog](https://raw.githubusercontent.com/tmux/tmux/3.2/CHANGES) it does appear there were some changes to focus events.
Also managed to get undercurl and coloured undercurl working in Tmux with [this](https://raw.githubusercontent.com/tmux/tmux/3.2/CHANGES).  
Only things left to get working are: 
- Hyperlinks, (which seem to work inside Tmux in iTerm2) and 
- Coloured undercurls in Tmux in Neovim (partially working, they work in Neovim and in Tmux but not in Neovim inside Tmux).

I might try your `script` debug strategy. Thanks for your help!

**Comment by trygveaa** [comment]
> Hyperlinks, (which seem to work inside Tmux in iTerm2)

@CallumHoward: Are you sure they work in tmux in iterm2? As far as I know tmux does not support hyperlinks.

**Comment by CallumHoward** [comment]
@trygveaa Ah yes, you are correct. I guess I must have been mistaken, maybe I mixed it up with a normal URL. It looks like there is a patch here that I might try when I have time.
https://github.com/tmux/tmux/issues/911#issuecomment-554312483
