### ISSUE TITLE
Hidden escape code unsupported

### ISSUE THREAD

**Issue by ccc032** [kovidgoyal/kitty#266]
In most other terminals such as xterm, the code  `<ESC>[8m` makes the text invisible.
Trying this in kitty: `printf '%b\n' '\e[8mHidden'` does nothing.

**Comment by kovidgoyal** [comment]
This is IMO not a good idea. It's a security risk (it can be used to hide text in the output of tools like git diff, etc), and a performance hit for not much gain. As such I dont want to implement it.
