### ISSUE TITLE
Re-open: sometimes unicode symbols are not displayed

### ISSUE THREAD

**Issue by femtomc** [kovidgoyal/kitty#2660]
Re-opening from closed issue #799.

I'm having the same issue as well. Sometimes glyphs render correctly, sometimes they do not. 

I think mine is slightly complicated by the fact that I'm using PragmataPro Mono (which doesn't support nerd font glyphs). So I should expect them not to work correctly in the first place. However, sometimes, they render correctly - most of the time they do not.

Is there a way to force a fallback? I'm don't know much about this.

Edit: interesting twist on this - I'm using `ranger` and when I highlight a file it renders the glyph correctly.

![image](https://user-images.githubusercontent.com/34410036/82134722-9ce92580-97c8-11ea-97ec-45a397e10372.png)

Edit: it appears that if I wait long enough before opening a new terminal process, it will render correctly - so I have no idea what is going on.

The fallback sometimes grabs the highlighted font below:

![image](https://user-images.githubusercontent.com/34410036/82134873-7926df00-97ca-11ea-8a45-b20a99d07282.png)

**Comment by kovidgoyal** [comment]
If you want to force a fallback, use symbol_map in kitty.conf
