### ISSUE TITLE
Extra space after pipe ligature with JetBrains Mono font on Mac

### ISSUE THREAD

**Issue by aerosol** [kovidgoyal/kitty#2661]
Hello. I'm having problems with ligations on Mac.

The font is [JetBrains Mono](https://www.jetbrains.com/lp/mono/).
I'm getting extra space for `|>` on Mac OS. Similar issues with other ligature-enabled fonts I tried.
I could not reproduce this on Linux kitty build.

![kitty2](https://user-images.githubusercontent.com/173738/82138274-8cb06500-981f-11ea-8aca-a4e4959a5930.gif)

**Comment by kovidgoyal** [comment]
dup of #2591
