### ISSUE TITLE
multiple `symbol_map` entries do not override as expected

### ISSUE THREAD

**Issue by loveencounterflow** [kovidgoyal/kitty#2662]
When I configure in my `kitty.conf` the following:

```
# Note: inline comments only for reference, not in `kitty.conf`
font_family               IosevkaNerdFontCompleteM-Thin
symbol_map U+61-U+7a      Iosevka-Slab-Heavy  # (1) /[a-z]/
symbol_map U+51-U+5a      Iosevka-Slab-Heavy  # (2) /[Q-Z]/
symbol_map U+61           LastResort          # (3) /[a]/
symbol_map U+65           LastResort          # (4) /[e]/
symbol_map U+69           LastResort          # (5) /[i]/
symbol_map U+6F           LastResort          # (6) /[o]/
symbol_map U+75           LastResort          # (7) /[u]/
symbol_map U+51-U+53      LastResort          # (8) /[QRS]/
symbol_map U+59-U+5a      LastResort          # (9) /[YZ]/
```

I'd expect the outcome to be as follows:

* **(1)** Use `IosevkaNerdFontCompleteM-Thin` as default,
* **(2)** except for the lower case `[a-z]` range, for which use `Iosevka-Slab-Heavy`,
* **(3)** except for the upper case `[Q-Z]` range, for which likewise use `Iosevka-Slab-Heavy`; of these,
* **(4-7)** use LastResort for `/[aeiou]/`, overriding **(1)**,
* **(8)** use LastResort for `/[QRS]/` overriding **(2)**,
* **(9)** use LastResort for `/[YZ]/`, likewise overriding **(2)**.

What happens in reality is that Kitty applies the only rules **(1)**, **(2)**, **(3)**, **(8)**, but
discards **(4)**, **(5)**, **(6)**, **(7)** and **(9)**; it so happens that both the ranges / single
codepoints addressed in the shadowing rules that *were* honored (**(3)** and **(8)**), their first
codepoints (`a` = `U+61` and `Q` = `U+51`) coincided with the first codepoints of the rules they shadowed.
Observe that while e.g. codepoint `e` = `U+65` of rule **(4)** is indeed the first (and only) codepoint of
that rule, that is not what matters; what matters is where that shadowing codepoint falls within the rule it
is intended to supplant, namely rule **(1)**. Since there it is the 5th, not the 1st codepoint of the range
given, it does—erroneuosly, one should think—not succeed.

I believe I can fix that by making all codepoint ranges disjunct (i.e. non-overlapping). Still, it would be 
way easier and mor intuitive if later ranges would just partially override earlier ones, the way they do 
in CSS Unicode Ranges.

I'm using Kitty 0.17.4 on Linux Mint 19.3 (on Ubuntu 18.04).

**Comment by kovidgoyal** [comment]
You are welcome to submit a PR to implement normalization of the ranges,
but as it stands if multiple symbol_maps overlap the result is
undefined.

**Comment by kovidgoyal** [comment]
And to get you started, you basically implement a finalize_symbol_maps() function in kitty/config.py that merges the symbol maps and ends up with a set of non-overlapping ranges.

**Comment by kovidgoyal** [comment]
Or actually, a better place to do it would be in coalesce_symbol_maps in kitty/fonts/render.py

**Comment by loveencounterflow** [comment]
OK thanks for the tips. I'm doing a rewriting tool in NodeJS right now where the input is CSS-like ranges with possible overlaps and the output is disjunct ranges as needed by the Kitty configuration. I'll see whether I can derive some Python code from that.
