### ISSUE TITLE
A confirm_on_os_window_close feature raises multiple kittens on multiple key presses

### ISSUE THREAD

**Issue by ahlinc** [kovidgoyal/kitty#2664]
**Describe the bug**
If accidentally press a system window close shortcut several times kitty generates a several `ask` kitten overlays and if a user wants to say No, then several presses for a `N` are needed.

**To Reproduce**
1. Press a system window close shortcut several times.
2. Press `N` and see that overlay doesn't gone.

**Expected behavior**
Just one `ask` kitten overlay.

**Note**
I'm very expected this `confirm_on_os_window_close` feature and if it possible that default option on just `Enter` press would be `No` it would be even better. Thanks!

**Comment by kovidgoyal** [comment]
This feature is not complete yet, feel free to comment about it when it
is. The default option is yes and so enter will trigger yes. Escape can
be used to trigger no.

**Comment by kovidgoyal** [comment]
This feature is finished now.
