### ISSUE TITLE
Could kitty on macOS with custom macos_titlebar_color respect OS settings for close/minimize/maximize button?

### ISSUE THREAD

**Issue by alappe** [kovidgoyal/kitty#2666]
Using `macos_titlebar_color #1d1f21` the tab bar is dark as expected, but the three buttons for close/minimize/maximize window are colored, whereas all other windows on the system do use the gray coloring for those buttons (see screenshots of kitty and e.g. Firefox):

![Screenshot 2020-05-18 at 14 48 27](https://user-images.githubusercontent.com/1357848/82215099-1d1da100-9917-11ea-9245-2434288d4f15.png)
![Screenshot 2020-05-18 at 14 50 04](https://user-images.githubusercontent.com/1357848/82215104-20b12800-9917-11ea-88f2-b1e1f1bc07d1.png)

It's documented as a window hack, but I wonder if it would be possible to get gray buttons for the active window here as well?

**Enviroment details**
OS: Name and version of operating system(s)
- macOS: `v10.14.6`<br />
- kitty: `v0.17.4`

**Comment by kovidgoyal** [comment]
If somebody knows how to do it, patches are welcome, but I am not going
spelunking in the cocoa APIs. Look in cocoa_set_titlebar_color() to make
the patch.

**Comment by alappe** [comment]
Alright
