### ISSUE TITLE
Proper Wayland HiDPI mouse cursors

### ISSUE THREAD

**Issue by TheDaemoness** [kovidgoyal/kitty#2669]
When using HiDPI on Wayland (or at least on sway), mouse cursors over kitty windows are loaded at their non-scaled resolutions, and then upscaled. This doesn't look very good.
![Screenshot](https://user-images.githubusercontent.com/5815194/82372708-fdb47000-9a0b-11ea-994d-0ec4fd16179e.png)

There's been prior work on getting cursors to look good in HiDPI Wayland setups in [upstream glfw](https://github.com/glfw/glfw/pull/1271/files), but their solution has a few limitations (like not respecting the `XCURSOR_*` environment variables and only really supporting scale=2).

However, AFAICT, the general approach here should be similar:
* Load the appropriately-scaled cursor images at some point.
* Make window scale information available to `setCursor` and `setCursorImage` (in `glfw/wl_init.c` and `glfw/wl_window.c`).
* Divide the hotspot coordinates by scale when calling `wl_pointer_set_cursor`.
* Call `wl_surface_set_buffer_scale` with the cursor surface and the scale factor.

General approaches to loading the appropriately-scaled cursor images "at some point" include:
* Loading one set of cursor images per window.
* Loading one set of cursor images per scaling factor used.
* Loading only the largest set of cursor images required across all windows, and downscaling where needed.
* Doing what upstream glfw does and only supporting scale=2 for cursors, allowing the cursor images to be loaded ahead of time.

I'm making this a feature request because while I'm willing to contribute code toward implementing this, I'd first like to know which approach to go with, or if there are any complications that make would make implementation more difficult than it seems at first glance.

**Comment by Luflosi** [comment]
Here is a very similar issue: #2647.

**Comment by kovidgoyal** [comment]
Follow up in #2647. Regarding your question, I prefer one set of cursor images per scale factor.
