### ISSUE TITLE
scrolling in Micro editor selects text

### ISSUE THREAD

**Issue by evolbug** [kovidgoyal/kitty#267]
While using [Micro editor](https://github.com/zyedidia/micro), scrolling begins selecting text at the mouse cursor, as cursor begins to move, requiring an extra click to stop the selection and to be able to move cursor without selection. This only happens in this terminal.
Kitty:
![peek 2018-01-06 15-04](https://user-images.githubusercontent.com/19688801/34639988-1e6f5f0c-f2f3-11e7-8158-11bb64454ea1.gif)
xfce4-terminal:
![peek 2018-01-06 15-08](https://user-images.githubusercontent.com/19688801/34639998-7549f418-f2f3-11e7-8d9d-1b1193c7ad7a.gif)

**Comment by kovidgoyal** [comment]
I tried running micro and it gave me an error saying it does not recognize the terminal. Apparently it does not know how to use terminfo. I tried setting TERM=xterm and scrolling around and I could not replicate the behavior you describe. Given that micro apparently does not know how to use a terminfo database, I'm not going to spend more time on it.

**Comment by evolbug** [comment]
micro uses tcell which uses terminfo databases. https://github.com/gdamore/tcell

**Comment by kovidgoyal** [comment]
Then why does it claim the terminal is unrecognized with TERM=xterm-kitty? Since kitty comes with its terminfo database.

**Comment by SolitudeSF** [comment]
micro also has similiar problems with termite's terminfo.

**Comment by evolbug** [comment]
you tell me. 
![peek 2018-01-07 12-13](https://user-images.githubusercontent.com/19688801/34648574-4307742e-f3a4-11e7-8069-2c2d7b6d61dd.gif)

**Comment by kovidgoyal** [comment]
Sorry I have better things to do that debug other people's software.

**Comment by evolbug** [comment]
But it's your software that's faulty, Micro works flawlessly in terminals like xfce4-terminal, gnome-terminal, urxvt, hyperterm, alacritty - to name a few; except yours. Micro's terminal detection or anything is not at fault here.

**Comment by kovidgoyal** [comment]
Really? I tried running it in termite and I get
```
terminal entry not found
Micro does not recognize your terminal: xterm-termite
Please go to https://github.com/zyedidia/mkinfo to read about how to fix this problem (it should be easy to fix).
```
And following that link tells me that micro wants you to compile the terminfo database into its own special-snowflake format. So it presumably it ships with pre-compiled definitions for some terminals and not others. An utterly brain-dead design. I'm done wasting time on this. You will get no more responses from me on this issue.

**Comment by evolbug** [comment]
perhaps it's your environment?
![peek 2018-01-07 13-05](https://user-images.githubusercontent.com/19688801/34648869-6b246046-f3ab-11e7-99bd-3e9caaf3eb0d.gif)

**Comment by evolbug** [comment]
It looks like you are sending a different mouse event (32) than other terminals (35) which could be the cause for this bug, as shown by micro's raw event inspector. The scroll up/down (64/65) event is the same in both

xfce4-terminal (left) : kitty (right)
![peek 2018-01-07 14-10](https://user-images.githubusercontent.com/19688801/34649283-baebc4c6-f3b4-11e7-8c8a-6c3b1828ea2b.gif)

**Comment by evolbug** [comment]
I am pretty confident this is the cause for the issue, as other terminals have the separation between 32 (mouse-down+move) and 35(move).
