### ISSUE TITLE
'clear' does not clear the scrollback buffer

### ISSUE THREAD

**Issue by evolbug** [kovidgoyal/kitty#268]
shell `clear` command should clear the scrollback as well.
![peek 2018-01-06 15-14](https://user-images.githubusercontent.com/19688801/34640053-561a9c72-f2f4-11e7-8446-bff63c59cde0.gif)

**Comment by kovidgoyal** [comment]
No, it should not. clear clears only the screen.

**Comment by kovidgoyal** [comment]
To be precise clear clears the scrollback buffer only if the E3 capability is defined, which kitty does not define.

**Comment by kovidgoyal** [comment]
And just for fun, surveying terminal behavior:
Terminals that use clear to clear scrollback
xterm, linux console, putty
Terminals that use clear to clear only the screen:
kitty, konsole, urxvt, all VTE based terminals such as gnome terminal

**Comment by kovidgoyal** [comment]
And with this commit, https://github.com/kovidgoyal/kitty/commit/1ef010689dd8dc24f658f870d34453b42304cf52

you can use

```
printf '\E[H\E[3J'
```

to clear the scrollback buffer as well as the screen, if you need to.

**Comment by spl** [comment]
Also, since I came here looking for this and others might be interested, the following works [[1](https://stackoverflow.com/a/1348624/545794), [2](https://apple.stackexchange.com/a/318217/62339)] to clear the screen and scrollback buffer in kitty, iTerm2, Apple Terminal, and presumably other Linux terminals (which I do not have at hand to test right now):

```bash
printf '\033[2J\033[3J\033[1;1H'
```

**Comment by collegeimprovements** [comment]
@spl it works as expected on kitty. How can I map it with `cmd+k` key on mac ? 
I tried `map cmd+k printf '\033[2J\033[3J\033[1;1H'` with no success :|

**Comment by OmisNomis** [comment]
@collegeimprovements - did you figure out how to map it to `cmd+k`?

**Comment by nkouevda** [comment]
@collegeimprovements @OmisNomis Escape the `'` and `\`:

    map cmd+k send_text normal printf \'\\033[2J\\033[3J\\033[1;1H\'\x0d

**Comment by OmisNomis** [comment]
@nkouevda  - Thanks. Unfortunately `map cmd+k combine : clear_terminal ..... ` has weird behaviour when text has been used (see gif below). 

Escaping the `'` and `\` also didn't work - when using `cmd+k`, nothing happens. 


![screencast 2020-01-06 09-37-17](https://user-images.githubusercontent.com/14848394/71809596-517b7980-3068-11ea-81f1-0de29e676784.gif)

**Comment by YarekTyshchenko** [comment]
So... how does one clear the scrollback (especially when looking at a running process)?

**Comment by screendriver** [comment]
On `macOS` it's working on my machine with `map ctrl+k combine : clear_terminal active : send_text normal \x0c`

**Comment by YarekTyshchenko** [comment]
Hmm this is interesting: `ctrl+shift+delete` does clear the scrollback, but it doesn't de-allocate the ram storage. Perhaps this should be a new issue

**Comment by jpmvferreira** [comment]
> On `macOS` it's working on my machine with `map ctrl+k combine : clear_terminal active : send_text normal \x0c`

It also works for me, but when I type something and then press the up key to find the previous command that starts or includes whatever I just wrote in zsh, as I usually do, it ignores whatever I write completely.

Is anybody facing this issue, and if so, how to work around it? (besides just doing a ctrl+c or typing something and running it)

**Comment by Chaitanyabsprip** [comment]
is there any way to disable scrollback buffer altogether?

**Comment by kovidgoyal** [comment]
ihttps://sw.kovidgoyal.net/kitty/conf/#opt-kitty.scrollback_lines

**Comment by madhur** [comment]
`
map ctrl+k combine : clear_terminal active : send_text normal \x0c
`

This does not work for me on linux. Using kitty 0.39.1

**Comment by tiagofmcosta-epi** [comment]
> `map ctrl+k combine : clear_terminal active : send_text normal \x0c`
> 
> This does not work for me on linux. Using kitty 0.39.1

@madhur It also started to not work for me recently on MacOS, but when I changed the keyboard mode from `normal` to `all` it started to work again.
Hope it helps.

**Comment by itsaphel** [comment]
> map ctrl+k combine : clear_terminal active : send_text normal \x0c

Does not seem to work for me on macOS even with `all`. Manually doing `printf '\033c'` does work however. Not sure how to map this to `cmd+k` correctly though.

Really feels like this shouldn't be this hard :/

**Comment by zzhaolei** [comment]
work for me:
```
map cmd+k  clear_terminal to_cursor_scroll active
map cmd+shift+k combine : clear_terminal scroll active : clear_terminal scrollback active
```

**Comment by olsonpm** [comment]
I'm confused why `clear` shouldn't clear the scrollback buffer.  `man clear` says

> DESCRIPTION
> &nbsp;&nbsp;`clear`  clears your terminal's screen and its scrollback buffer, if any.

After which, it explains the capabilities which I'm reading as implementation details, not semantics of the command.

**Comment by aaron-dotnet** [comment]
This works for me:

`alias clear='clear -T xterm-256color'`

```bash
~$ clear -
Usage: clear [options]

Options:
  -T TERM     use this instead of $TERM
# ...
```

**Comment by orpheus6678** [comment]
@kovidgoyal i use konsole and it resets the scrollback buffer on clear

**Comment by yurenchen000** [comment]
`ctrl+shift+delete`   reset terminal (clear scrollback)

broke  adb shell those days.
- kitty-0.29.0  is ok
- kitty-0.48.1 broke

when it broken adb shell with `ctrl+c` will exit
