### ISSUE TITLE
OpenType-SVG font with color supported?

### ISSUE THREAD

**Issue by T0astBread** [kovidgoyal/kitty#2691]
Out of curiosity I tried building a custom font using [scfbuild](https://github.com/13rac1/scfbuild) which generates OpenType fonts with SVG glyphs and TrueType outlines (`glyf` table) as a fallback. kitty seems to work well with this, however, I haven't been able to get it to accept my colored glyphs so far.

Here's a rendering of the font in Firefox (B, f and ⚠️ are defined, the rest is fallback):
![Custom font rendering in Firefox](https://user-images.githubusercontent.com/24869055/82762134-d3d5c180-9dee-11ea-85e6-76081e4f6f78.png)

And here's a rending from kitty when invoked with `kitty -o font_family="customfont Regular" -o font_size=16`:
![Custom font rendering in kitty](https://user-images.githubusercontent.com/24869055/82762198-34fd9500-9def-11ea-9c01-3fb7298ff539.png)

It falls back on my regular emoji font for the ⚠️ sign and doesn't display the B glyph with colors. If I use `symbol_map` to force the custom font for the emoji it looks like this:
![Custom font rendering in kitty](https://user-images.githubusercontent.com/24869055/82762268-8443c580-9def-11ea-8423-90db49cb9671.png)

I assume it falls back to the TrueType outlines (?).

Does kitty support colored OpenType-SVG fonts or have I made a mistake here? (Apologies if this is sort of a "bad issue" - I'm just experimenting and it could very well be an error on my side. I understand if you don't wanna look at this.)

## Steps to reproduce

1) Unpack the attached ZIP file
2) Copy `customfont.otf` to `~/.fonts`
3) Copy `996-custom-font.conf` to `/etc/fonts/conf.d`
4) `fc-cache ~/.fonts -fv`

Now `kitty list-fonts` should show `customfont Regular` and you can start kitty with the `font_family` override to test it.

## Output from `kitty --debug-config`

```
kitty 0.17.4 created by Kovid Goyal
Linux t0aster 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64
Debian GNU/Linux bullseye/sid \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf
Running under: X11

Config options different from defaults:
update_check_interval 0.0
```

## Attachments

[customfont.zip](https://github.com/kovidgoyal/kitty/files/4674227/customfont.zip)

**Comment by ctrlcctrlv** [comment]
The relevant questions here are two:

* Does the version of FreeType you built Kitty with support this feature? 
* Does HarfBuzz need any special prodding to get it to accept such fonts? I'd assume not.

It is extremely likely glyf table is in use, but if you want to be certain, just make them look different instead of just one in color and one not

**Comment by T0astBread** [comment]
Right, I haven't thought of that; glyf is indeed in use.

I'm using kitty from the Debian testing repository which, if I'm not mistaken, uses FreeType 2.10.1. However, the only thing I found for FreeType in relation to OpenType-SVG is [this ticket which has been left untouched for years](https://savannah.nongnu.org/bugs/?46141). I haven't found much about HarfBuzz but [apparently it supports it](https://github.com/harfbuzz/harfbuzz/issues/1192#issuecomment-433890773).

I will close this issue, as it appears not to be within kitty's bounds. I guess I could try generating CBDT or COLR/CPAL fonts, as those seem to be more widely supported in general.

**Comment by ctrlcctrlv** [comment]
COLR/CPAL is your best bet.

**Comment by joveian** [comment]
I found this PR trying to figure out why OpenMoji Color emoji aren't displaying in color (kitty 0.26.5, freetype 2.12.1, arch linux).  FreeType earlier this year (2.12.0) added some support for OpenType-SVG but the application must set hooks (kitty is showing the error "fast_data_types.FreeTypeError: Failed to load glyph_index=858 load_type=1048580, with error: SVG hooks have not been set").  [Here](https://gitlab.freedesktop.org/freetype/freetype-demos/-/blob/master/src/rsvg-port.c) is a demo for using librsvg to render the SVG and [here](https://freetype.org/freetype2/docs/reference/ft2-svg_fonts.html) is the documentation for the hooks.

While FreeType has some built in support for COLRv0, it sounds like it isn't fully featured (I'm not clear on the details) and the COLRv1 support contributed by Google also doesn't just work but requires using a different API (an extension of the one that can also be used for COLRv0). [They said](https://lists.gnu.org/archive/html/freetype-devel/2020-12/msg00011.html) that rasterization seemed like a better fit for 2D graphics libraries.  I couldn't find a good overview of that API beyond what is in the [changelog](https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/docs/CHANGES) (in particular see the 2.10.0 and 2.11.0 releases).

This all seems less than ideal and reading through freetype-devel a bit it sounds like setting a default SVG renderer was previously implemented and I didn't see why that wasn't in the final version (possibly to avoid cyclical dependencies).  Additionally, the COLRv1 API was described in the changelog as experimental and it sounds like not all of the freetype developers are happy with it (but I didn't notice any plans to implement anything else).  It might be worth adding a FAQ entry about what kind of color emoji is expected to work (which I guess is just COLRv0? at least on Linux), but I at least wanted to add what I found here for anyone searching about this issue.

OpenMoji fonts are also experimental and crash Firefox at times so possibly adding the SVG hooks would lead to more trouble for that font in particular or in general.  Also, it sounds like OpenMoji may soon update their build process and might add COLRv0 fonts.

**Comment by kovidgoyal** [comment]
Yes, I am definitely not in favor of adding things that can cause crashing bugs just to support a not widely used glyph format. And rendering SVG is a huge task I dont think having that in your text rendering pipeline is a particularly good idea.

**Comment by khaledhosny** [comment]
> While FreeType has some built in support for COLRv0, it sounds like it isn't fully featured

FreeType should be able to rasterize COLRv0 just fine, this is what Cairo (and I believe Skia on Linux) use.

**Comment by ctrlcctrlv** [comment]
Kitty should work fine on all COLRv0 fonts. COLRv1 support is down to the rasterizer. On macOS it may work if CoreText supports it, I don't know. On GNU/Linux it's going to entirely be up to FreeType to support. Personally I agree with Kovid that we should not add another library overtop FreeType/HarfBuzz for COLRv1 support. If FreeType has not decided how they want to support it yet we should wait for them. If they end up never supporting it fully then Kitty probably won't either and it'll end up being a more specialty format in free software more generally (which would be a shame).
