### ISSUE TITLE
Unicode input character color

### ISSUE THREAD

**Issue by framon** [kovidgoyal/kitty#2692]
Unicode input is really awesome. Thanks for it.

Let me talk about one issue: The current output color of unicode character is `gray`, which is actually dark white ANSI Color. Since I prefer light background, it becomes almost unreadable. I know maybe I need adjust the colot palette to add some contrast, but shoulnd't it be foreground color?

```python
    yield colored(idx, 'green') + ' '
    yield colored(c, 'gray', True)
```

![screenshot_2020-05-24-231924](https://user-images.githubusercontent.com/2184684/82775800-2e871180-9e1f-11ea-8300-f043a4fd0cb5.png)

Thanks in advance

**Comment by kovidgoyal** [comment]
If you are changing the background color, it is up to you to change the
first 16 colors to work well with that background color. In other words
you should use a proper light color theme, not just change the
background color. The 16 basic terminal colors are meant to be changed
as a set.

**Comment by framon** [comment]
Sure I have changed all colors as a set. Specifically, I'm using [CRLS](https://github.com/dexpota/kitty-themes/blob/master/themes/CLRS.conf) from https://github.com/dexpota/kitty-themes. Futhermore, I can't turn white (ANSI 37) too much gray because I will lost white over a color background.

Seeing from the other side, black (ANSI 30) is also not readable on all dark themes I have seen. So, for me, it is the same case: black over dark or white over light.

**Comment by kovidgoyal** [comment]
You need to pick a color theme that preserves contrast relationships between the colors. gray in a light color theme needs to be a less dark black. Just like "white" becomes black and "black" becomes white.
