### ISSUE TITLE
Send cursor position to scrollback command

### ISSUE THREAD

**Issue by eraserhd** [kovidgoyal/kitty#2699]
**Is your feature request related to a problem? Please describe.**

I'm using my editor as the scrollback_pager command.  [With a little bit of work](https://github.com/eraserhd/dotfiles/blob/develop/kitty/default.nix#L216), I've gotten it to honor `INPUT_LINE_NUMBER` to scroll the buffer to coincide with what was on the screen before, which is really nice.

However, I'd also like to position the cursor where it was on the original screen, since it is often close to what I want to copy, and my brain is already tracking the cursor position so I don't have to go look for it.

**Describe the solution you'd like**

CURSOR_COLUMN and CURSOR_LINE substituted into the scrollback_pager command.

**Describe alternatives you've considered**

From "nice for me" to "not so nice for me" (but any would work).

1. Cursor position set in an environment variable.
2. A kitten that could get the cursor position.
3. A confirmation that the cursor position before my editor starts is the same as it was before the scrollback command was invoked, so that I can wrap my editor with a program to query the cursor position using a terminal escape.

**Comment by kovidgoyal** [comment]
Use the launch command, see https://sw.kovidgoyal.net/kitty/launch.html#the-piping-environment

this is both more general and more powerful than show_scrollback whichis
really present only for legacy reasons.
