### ISSUE TITLE
scrolling in Micro editor selects text: the cause

### ISSUE THREAD

**Issue by evolbug** [kovidgoyal/kitty#270]
Since the developer has chosen to close and ignore the last issue (#267), blaming the editor, i'm opening another one to finish this.

Kitty is sending (or detecting) the wrong event type for mouse move (32) whereas other terminals have distinct events for mouse move (35) and mouse-down+move(32). The behaviour is shown here, using Micro's raw event inspector from the [nightly release](https://github.com/zyedidia/micro/releases/tag/nightly):
xfce4-terminal(left) - kitty(right)
![peek 2018-01-07 16-23](https://user-images.githubusercontent.com/19688801/34650280-3af07d4e-f3c7-11e7-87a2-2f980eb59d21.gif)

I am confident this is the cause for the issue as all terminals which have the distinction do not have the bug.

**Comment by kovidgoyal** [comment]
Kindly do not open multiple bug reports for the same issue.

**Comment by evolbug** [comment]
so is this getting fixed or ignored as the last issue?

**Comment by kovidgoyal** [comment]
I am not going to be convinced by a bug report involving micro, given that I cannot get it to run without changing TERM and once TERM is changed, I cannot reproduce your issue. So either come up with a test case not involving micro, say use one a dozen different editors (for instance, I use vim with kitty all day and have never noticed a problem with mouse movement). Or submit a PR and I will review it.

**Comment by kovidgoyal** [comment]
Oh and the relevant code for encoding mouse events is in mouse.c

**Comment by evolbug** [comment]
I literally just described the cause and solution for the issue.

**Comment by evolbug** [comment]
However I believe this line should be split into 2 conditions for DRAG and MOVE, if I understand the logic correctly. https://github.com/kovidgoyal/kitty/blob/master/kitty/mouse.c#L57

**Comment by kovidgoyal** [comment]
Like I said, a PR is most welcome.

**Comment by kovidgoyal** [comment]
Oh and to help you, you can see the codes being generated for mouse events by simply doing

```
printf '\E[1003;1006h' && cat
```

in any terminal.

**Comment by kovidgoyal** [comment]
Sorry make that
```
printf '\e[?1003;1006h' && cat
```

Forgot the ?
