### ISSUE TITLE
Environment in Mac OS

### ISSUE THREAD

**Issue by basbebe** [kovidgoyal/kitty#2704]
Under Mac OS 10.15.4, Kitty doesn"t recognize env variables when opening the .app.
Opening e.g. `kitty @ launch kak` (or any other program that's been installed to `/usr/local/bin` using Homebrew) will result in an error.

```
Failed to launch child: kak
With error: No such file or directory
Press Enter to exit.
```

It seems like this is the Path kitty has when it's being started by Mac OS:
```
PATH=/usr/bin:/bin:/usr/sbin:/sbin
```

This is my `/etc/paths`
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

Some applications (like kakoune or nnn) use kitty to open new splits.
They don't use the `--copy-env` argument so it seems that other OSes don't have that problem.

When I open kitty from another terminal I don't have some of these problems because the env gets taken over.

Of course I could add PATH to my env in Kittys config but there are other variables in my `config.fish` that the applications I'm opening rely on.

Is this a Mac OS "thing" or is this some misconfiguration or misinterpretation on my end?

```
kitty 0.17.4 created by Kovid Goyal
Darwin Bastians-MBP.fritz.box 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.4 BuildVersion:	19E287
Loaded config files: /Users/bastian/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height   1.2
allow_remote_control y
background           Color(red=40, green=40, blue=40)
color0               Color(red=40, green=40, blue=40)
color1               Color(red=204, green=36, blue=29)
color10              Color(red=184, green=187, blue=38)
color11              Color(red=250, green=189, blue=45)
color12              Color(red=131, green=165, blue=152)
color13              Color(red=211, green=134, blue=155)
color14              Color(red=142, green=192, blue=124)
color15              Color(red=146, green=131, blue=116)
color2               Color(red=152, green=151, blue=26)
color3               Color(red=215, green=153, blue=33)
color4               Color(red=69, green=133, blue=136)
color5               Color(red=177, green=98, blue=134)
color6               Color(red=104, green=157, blue=106)
color7               Color(red=168, green=153, blue=132)
color8               Color(red=146, green=131, blue=116)
color9               Color(red=251, green=73, blue=52)
cursor               Color(red=146, green=131, blue=116)
editor               /usr/local/bin/kak
env                  {'LANG': 'de_DE.UTF-8'}
font_family          mononoki
font_size            14.0
foreground           Color(red=235, green=219, blue=178)
macos_option_as_alt  2
macos_thicken_font   0.25
macos_titlebar_color 1
selection_background Color(red=60, green=56, blue=54)
selection_foreground Color(red=146, green=131, blue=116)
shell                /usr/local/bin/fish --login
Changed shortcuts:
	 shift+control+enter KeyAction(func='new_window_with_cwd', args=())
	 super+enter KeyAction(func='new_window_with_cwd', args=())
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You need to set your environment variablessystem wide for them to be
available inside applications launched vi launch services. Setting them
in your shells rc files is insufficient. Googling should tell you how to
set nevironment variables system wide, I will warn you that appe does
not make it easy/conveninent.

**Comment by basbebe** [comment]
> You need to set your environment variablessystem wide for them to be
> available inside applications launched vi launch services. Setting them
> in your shells rc files is insufficient. Googling should tell you how to
> set nevironment variables system wide, I will warn you that appe does
> not make it easy/conveninent.

Thanks.
Yes, I have not yet found a way to set variables system wide.
At the moment I might stick with setting path in `kitty.conf`.
