### ISSUE TITLE
Let double-clicking URLs select the full URL

### ISSUE THREAD

**Issue by hvdijk** [kovidgoyal/kitty#2705]
In earlier kitty releases, when I double-clicked most URLs, the whole URL would be selected. With the resolution of issue #2602, which removes `:` from the default `select_by_word_characters`, this no longer works. Clearly it is possible to just put that back into `select_by_word_characters`, but I think removing it was the right call. URLs are an exception, so leaving `:` out to support the more common cases is something I agree with.

URLs are a common enough exception though that special casing them would be nice. kitty already contains logic to detect URLs: when hovering over them, the whole URL is underlined and the mouse cursor is changed to indicate that clicking it (with modifier keys pressed as well) will open it. Can this existing logic be reused so that when a URL is double clicked without modifier keys, it is considered a single word regardless of the value of `select_by_word_characters`?

**Comment by kovidgoyal** [comment]
It's already done in master.

**Comment by hvdijk** [comment]
Huh, so it is. Sorry for missing that, and thanks!
