### ISSUE TITLE
Pass Cmd key on mac to the running application vim.

### ISSUE THREAD

**Issue by atishay** [kovidgoyal/kitty#2706]
**Is your feature request related to a problem? Please describe.**
Want to map cmd key in vim `<D-p> :CtrlP<CR>` just like macvim.

**Describe the solution you'd like**
Being able to pass Cmd Key to vim and then override with kitty specific handling manually if needed.

**Describe alternatives you've considered**
Mapping each combinations to `send_text all <some special character>`. It is not clean and easy.

**Additional context**

**Comment by kovidgoyal** [comment]
The traditional terminal keyboard encoding hasno support for modifiers
other than ctrl, alt and shift. If you want to do this you have to get
vim to support kitty's extended extended keyboard protocol,
https://sw.kovidgoyal.net/kitty/protocol-extensions.html

**Comment by iansinnott** [comment]
In case it helps anyone else coming across this issue, here's an example of how you can send command keys through to vim. It is indeed not a clean solution since the mappings show here will just insert a bunch of text if you happen to be in insert mode. But I've found it to be effective enough for my use case.

In your `kitty.conf`:

```viml
map cmd+j send_text all :execute "normal \<d-j>"\r
map cmd+k send_text all :execute "normal \<d-k>"\r
map cmd+p send_text all :execute "normal \<d-p>"\r
map cmd+/ send_text all :execute "normal \<d-/>"\r
map cmd+s send_text all :execute "normal \<d-s>"\r
```

**Comment by typkrft** [comment]
> In case it helps anyone else coming across this issue, here's an example of how you can send command keys through to vim. It is indeed not a clean solution since the mappings show here will just insert a bunch of text if you happen to be in insert mode. But I've found it to be effective enough for my use case.
> 
> In your `kitty.conf`:
> 
> ```viml
> map cmd+j send_text all :execute "normal \<d-j>"\r
> map cmd+k send_text all :execute "normal \<d-k>"\r
> map cmd+p send_text all :execute "normal \<d-p>"\r
> map cmd+/ send_text all :execute "normal \<d-/>"\r
> map cmd+s send_text all :execute "normal \<d-s>"\r
> ```

You should be able to send some arbitrary text that isn't used for anything else and bind in (n)vim.

kitty.conf
```CONF
map cmd+right send_text application \02312
map cmd+left send_text application \1234
map alt+right send_text application \121949
map alt+left send_text application \123591
```

init.lua
```LUA
-- CMD
vim.api.nvim_set_keymap('n', 'S4', '0', { noremap = true })
vim.api.nvim_set_keymap('n', '12', '$', { noremap = true })
vim.api.nvim_set_keymap('i', 'S4', '<Esc>0i', { noremap = true })
vim.api.nvim_set_keymap('i', '12', '<Esc>$a', { noremap = true })
-- ALT
vim.api.nvim_set_keymap('n', 'S591', 'b', { noremap = true })
vim.api.nvim_set_keymap('n', 'Q949', 'w', { noremap = true })
vim.api.nvim_set_keymap('i', 'S591', '<Esc>bi', { noremap = true })
vim.api.nvim_set_keymap('i', 'Q949', '<Esc>wwi', { noremap = true })
```

or 

init.vim
```VIM
nmap S4 0
"ETC...
```

**Comment by kuntau** [comment]
> Maybe this is what is being referred to, but you should be able to send some arbitrary text that isn't used for anything else and bind in (n)vim. It takes all of a few seconds to setup properly for whatever mode you want.

@typkrft I'm trying to setup this. Where do you this seems random number `\02312` and the equivalent `'S591'` in nvim?

```
map cmd+right send_text application \02312
map cmd+left send_text application \1234
map alt+right send_text application \121949
map alt+left send_text application \123591
```

**Comment by page-down** [comment]
@kuntau 
In Python,  `\ooo` represents `Character with octal value ooo`. This is not a random number.

`\123591` -> `\123 5 9 1` -> 0x53 0x35 0x39 0x31 -> `S591`

The above example refers to arbitrary characters. This is not perfect, but it will work.

For example, move to the beginning of the line when you press `cmd+left`, and move to the end of the line when you press `cmd+right`.

```shell
kitty -o 'map cmd+left send_text application abc' -o 'map cmd+right send_text application def'
```

init.vim
```vim
nmap abc 0
nmap def $
```

Or specify an uncommon modifier shortcut in vim/neovim and then configure the cmd modifier key combination in kitty to send that shortcut.

**Comment by kuntau** [comment]
@page-down It's confusing. If I understand this correctly `\123` is the octal part and `591` is any random number we choose. `123` in octal translated to `0x53` in hex. 

And from [this ascii table](https://www.rapidtables.com/code/text/ascii-table.html) `0x53` hex or `83` decimal is character `S`. Is this correct?

> The reason why you should not start with a character like a is that it will cause a delay in the a key function. 

If `a` cause delay, wouldn't starting with `S` also cause delay?

Can we use weird character from extended ascii table like `¼` `¬` `Ø`?

**Comment by page-down** [comment]
> If I understand this correctly \123 is the octal part ...

Yes, I mean `\123` is the ASCII code of `S` in octal. If it's not a keyboard keystroke character, I don't think it can be supported by the key mapping feature.

Please refer to the documentation for details and try the key combinations you want.

https://vimhelp.org/map.txt.html
https://neovim.io/doc/user/map.html#mapping
https://neovim.io/doc/user/intro.html#key-notation

I suggest defining the uncommon ctrl or alt key combinations in vim/neovim and then having kitty send them when the cmd key combination is pressed. Or use `<leader>` key, or comma, etc.

**Comment by kuntau** [comment]
How do I send function key from Kitty? `F1 - F24` ... I can't find any reference. Thanks

**Comment by page-down** [comment]
Make sure that the function keys are not bound in kitty, then run kitten `kitty +kitten show_key` and press the corresponding keys.
