### ISSUE TITLE
Small-sized Nerd Font symbols after installing kitty, cannot restore original size

### ISSUE THREAD

**Issue by RationalG** [kovidgoyal/kitty#2707]
Looks related to this issue : # #1463 

After installing kitty and launching it for the first time, the symbols displayed using Nerd Font got decreased in size. Now, even if I use another terminal, like Hyper for example, the size of the symbols remains small. Even after uninstalling kitty the problem is still there.
I uninstalled kitty, hyper, zsh and all its plugin including oh-my-zsh and powerlevel10k, reinstalled everything except kitty, and the problem is still there.

I just don't understand how this could have broke the initial configuration ? it looked like kitty was pretty much isolated from everything else.

Is there a way to restore the original size ?

**Comment by ctrlcctrlv** [comment]
This issue is silly. There's no way this happened how you're describing it. Certainly Kitty didn't overwrite your fonts, unless your distribution is packaging some bizarre Fontconfig which it then forgets to remove, or there was a conflict in dependencies. Either way, Kitty isn't the problem.

**Comment by kovidgoyal** [comment]
kitty does not touch your system fonts or indeed system settings
generally in any shape or form. If your fonts have changed in your
system generally, then something else was changed in your system.
