### ISSUE TITLE
Two terminfo entries defined as the same thing

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#2713]
I'm trying to create a grammar with all the escape codes kitty supports. My fuzzer can then automatically generate valid escape codes for me. While doing this, I noticed, that both `bel` and `fsl` are defined as `^G` in `terminfo.py`:
```Python
# The audible bell character
'bel': r'^G',

# From status line (end window title string)
'fsl': r'^G',
```
Is that intended?

**Comment by kovidgoyal** [comment]
Yes ^G is an escape code terminator also.
