### ISSUE TITLE
env vars not expanded for include directive

### ISSUE THREAD

**Issue by alephnull** [kovidgoyal/kitty#2718]
Documentation states that environment variables are expanded in the config file. However, they do not appear to be.

With the following dir structure:
```
/home/alok/.config/kitty
├── kitty.conf -> ../../dotfiles/kitty/.config/kitty/kitty.conf
├── mobius.conf -> ../../dotfiles/kitty/.config/kitty/mobius.conf
└── themes -> ../../dotfiles/kitty/.config/kitty/themes
```

And the contents of `kitty.conf`:
```
linux_display_server wayland

include ${HOST}.conf
```

Running kitty results in:
```
% kitty
[154 11:32:45.470584] Could not find included config file: /home/alok/.config/kitty/${HOST}.conf, ignoring
[154 11:32:45.471661] Ignoring invalid config line: include
```

However, a kitty window pops up with the content:
```
Failed to launch child: mobius.conf
With error: No such file or directory
Press Enter to exit.
```

**Expected behavior**
The configuration in `mobius.conf` will be loaded.

**Enviroment details**
OS: Debian sid, running kitty 0.17.4-1

Output of kitty --debug-config
```
kitty --debug-config
[154 11:45:23.838893] Could not find included config file: /home/alok/.config/kitty/${HOST}.conf, ignoring
[154 11:45:23.840030] Ignoring invalid config line: include
```

**Comment by kovidgoyal** [comment]
Am guessing you are on macOS. The environment variables that are
relevant are the *system-wide* ones, not the ones you set in your
shell's rc files. Set $HOST system wide and it will be expanded.

**Comment by alephnull** [comment]
I'm on Debian sid. $HOST is set _system wide_, just like `$USER`. I do not set this in my rcfiles.

**Comment by kovidgoyal** [comment]
Works for me. Either HOST is not set or its set to a value different than what you think it is.

**Comment by kovidgoyal** [comment]
Actually looking at the code, it is not set. You are probably confusing it with HOSTNAME

**Comment by alephnull** [comment]
Setting an env var on GNOME is just ridiculous :D

**Comment by kovidgoyal** [comment]
Well I believe macOS is an inspiration for GNOME and setting env vars system wide on macOS is almost impossible.

**Comment by alephnull** [comment]
FTR, I found `/etc/security/pam_env.conf` (or `~/.pam_environment`) to be the best place to set system specific env vars that will work for DE and console logins. It is rather limited in that you can't invoke programs to populate values, since that sort of freedom is too dangerous :wink:

**Comment by khughitt** [comment]
Another option that works on linux is just to manually export `HOSTNAME` in your .zshrc, etc.:

```
export HOSTNAME=`hostname`
```

**Comment by bhushan** [comment]
This doesnt work on mac @khughitt any other way we have ?
