### ISSUE TITLE
Holding alt while selecting should select a square

### ISSUE THREAD

**Issue by daurnimator** [kovidgoyal/kitty#2719]
**Is your feature request related to a problem? Please describe.**

All terminals I've ever used have supported selecting a square by holding down ALT while selecting with the mouse.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/#mouse-features

**Comment by daurnimator** [comment]
why Ctrl+Alt instead of just Alt?

**Comment by kovidgoyal** [comment]
Because that would mean you can use the alt+mouse in terminal programs that support mouse interaction.

**Comment by daurnimator** [comment]
> Because that would mean you can use the alt+mouse in terminal programs that support mouse interaction.

In other terminals, holding SHIFT prevents sending mouse events to the program

**Comment by kovidgoyal** [comment]
As it does in kitty as well, your point being?

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.rectangle_select_modifiers and set it to alt if you prefer it that way.
