### ISSUE TITLE
preference to confirm closing windows

### ISSUE THREAD

**Issue by smolin** [kovidgoyal/kitty#2723]
**Is your feature request related to a problem? Please describe.**
It's too easy to lose work by accidentally closing the window, eg command-w in macos

**Describe the solution you'd like**
When you close a window, a dialog box could pop up to confirm the action

**Describe alternatives you've considered**
I could remap the command-w action (but it would require installing 3rd-party software).

**Additional context**
MacOS 10.14.6 Mojave, dual monitors, nothing special

**Comment by kovidgoyal** [comment]
This is already implemented in master.

**Comment by Luflosi** [comment]
Put `confirm_os_window_close 1` into your `kitty.conf` and compile kitty from source or wait until the next version is released.
