### ISSUE TITLE
tab separator cannot be a space, defaults to the original symbol

### ISSUE THREAD

**Issue by evolbug** [kovidgoyal/kitty#273]

**Comment by kovidgoyal** [comment]
Use one of the unicode space symbols, like the non-breaking space

**Comment by evolbug** [comment]
That is not a solution, that's a dirty hack.

**Comment by kovidgoyal** [comment]
Thank you for that delightful comment. Your persistent rudeness has now landed you permanently on my ignore list. Good bye and good luck.
