### ISSUE TITLE
Some characters in urls break url recognition when last before line break

### ISSUE THREAD

**Issue by agschaid** [kovidgoyal/kitty#2731]
**Describe the bug**
If an url does not fit completely into a line some characters break url-recognition if they are the last character before the visual line break.

**To Reproduce**

(NOTE: these steps are reproducible with `kitty --config NONE`)

1. run `echo "https://gitlab.my-company.com/someGroup/someProduct/billy-the-gate/-/merge_requests/new?merge_request%5Bsource_branch%5D=bring-the-cattle-in"`
2. adjust the width of the terminal so that the url gets broken up into two lines and that one of the following characters is the last one before the visual line-break: `-`, `?`, `_`, `%` (probably works with many others but these were the ones I was able to identify)
3. let the mouse pointer hover over the first line of the url
4. Error: the underline (signifying an URL) does not continue beyond that character and does not continue into the second line. When doing a Ctrl+Shift Click only the part before the character is copied to the browser

**Expected behavior**
The underline should continue into the second line until the end of the URL. When doing a Ctrl+Shift Click the full URL should be copied to the browser.

**Enviroment details**
kitty 0.16.0 on NixOS 20.03

```
Output of kitty --debug-config

kitty 0.16.0 created by Kovid Goyal
Linux langeoog 5.4.43 #1-NixOS SMP W
ed May 27 15:46:53 UTC 2020 x86_64
<<< Welcome to NixOS 20.03.2013.e985ffea2d6 (\m) - \l >>>

Run `nixos-help` for the NixOS manual.
Loaded config files: /home/agl/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background           Color(red=0, green=43, blue=54)
color0               Color(red=7, green=54, blue=66)
color1               Color(red=220, green=50, blue=47)
color10              Color(red=88, green=110, blue=117)
color11              Color(red=101, green=123, blue=131)
color12              Color(red=131, green=148, blue=150)
color13              Color(red=108, green=113, blue=196)
color14              Color(red=147, green=161, blue=161)
color15              Color(red=253, green=246, blue=227)
color2               Color(red=133, green=153, blue=0)
color3               Color(red=181, green=137, blue=0)
color4               Color(red=38, green=139, blue=210)
color5               Color(red=211, green=54, blue=130)
color6               Color(red=42, green=161, blue=152)
color7               Color(red=238, green=232, blue=213)
color8               Color(red=0, green=43, blue=54)
color9               Color(red=203, green=75, blue=22)
cursor               Color(red=147, green=161, blue=161)
cursor_shape         2
enable_audio_bell    False
font_family          Victor Mono
font_size            12.0
foreground           Color(red=131, green=148, blue=150)
selection_background Color(red=129, green=144, blue=143)
```

**Comment by kovidgoyal** [comment]
Works fine for me tested with - as the last char on the line. Note that
URLs are recognized only when the mouse is over the first line, the one
containing the http:// Your version of kitty is pretty ancient, am
guessing this bug was already fixed a while ago, update.

**Comment by agschaid** [comment]
you're right. Works with a 0.17 version.

**Comment by agschaid** [comment]
Had similar issues again with 0.19.1
Will investigate and either reopen or create a new one (depending on HOW similar the issue is)
