### ISSUE TITLE
i3wm doesn't work with background_opacity.

### ISSUE THREAD

**Issue by AVCADO** [kovidgoyal/kitty#2736]
**Describe the bug**
kitty's `background-opacity` doesn't work on i3wm

**To Reproduce**
1. set `background-opacity` to 0.95
2. run i3wm
3. run kitty

**Expected behavior**
I expected the terminal to be  transparent, but it wasn't 

**Screenshots**

**Enviroment details**
OS: Name and version of operating system(s)
Arch Linux x86_64
```
Output of kitty --debug-config
```
Linux arch 5.4.44-1-lts #1 SMP Thu, 04 Jun 2020 07:31:01 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/nick/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity 0.95
```
**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You need a compositor for semi-transparent windows.

**Comment by otakutyrant** [comment]
Just install and execute picom, and restart Kitty.
