### ISSUE TITLE
Choose monitor kitty appears on start via session config

### ISSUE THREAD

**Issue by Strykar** [kovidgoyal/kitty#2740]
**Is your feature request related to a problem? Please describe.**
I just got a second monitor and I cannot get Kitty to start on the monitor I want via Kitty's session config in Gnome.

**Describe the solution you'd like**
Define where kitty is displayed in the session config, kinda like Tilda terminal does it, see screenshot below.

**Describe alternatives you've considered**
I assume this could be controlled via the WM, but this feature and (horizontal/vertical) pixel alignment (also in the screenshot below) is one of the reasons I currently use Tilda for a few transparent terminals on my desktop and would be nice to have I could run 3 kitty terminals instead.

**Additional context**
https://i.imgur.com/11nu0Hi.png
https://github.com/kovidgoyal/kitty/issues/2383

**Comment by kovidgoyal** [comment]
I'm afraid controlling window placement is specific to window
manager/platform, etc. As such I am not going to maintain multiple
backends for it in kitty.

**Comment by Strykar** [comment]
Alright, I assumed there was an WM agnostic method to achieve it seeing it in Tilda's options.
