### ISSUE TITLE
Offer a geometry option to control where kitty window spawns on startup

### ISSUE THREAD

**Issue by Strykar** [kovidgoyal/kitty#2741]
**Is your feature request related to a problem? Please describe.**
Offering a geometry option would allow control over which monitor to open different kitty terminals on.

**Describe the solution you'd like**
Offer a --geometry option like gnome-terminal
```
#left monitor:
gnome-terminal --geometry 1x1+0+0 --full-screen

#right monitor:
gnome-terminal --geometry 1x1+3600+0 --full-screen
```

**Describe alternatives you've considered**
https://github.com/kovidgoyal/kitty/issues/2740

**Additional context**
If not, what options currently exist to control opening multiple Kitty sessions and placing them exactly as wanted on different (fixed) locations across multiple monitors?

**Comment by kovidgoyal** [comment]
I've already said I wont be doing this. Indeed its not even possible on
Wayland, where clients cant control their own window position.
