### ISSUE TITLE
Why does kitty use 0x3B `:` inside CSI parameters?

### ISSUE THREAD

**Issue by christianparpart** [kovidgoyal/kitty#2746]
This is a purely informational ticket, and unless Github will open up their discussions feature to the public, I hope you don't mind doing it that way :-)

You decided to go for the colon `:` (0x3B) for providing stylized underline extensions. For that you also extended the VT protocol (at least as far as one may be concerned with regards to the following description: https://vt100.net/emu/dec_ansi_parser).

While I'd not like to say it's entirely bad, I'd at least like to understand your actual reasoning behind this move. I think it would have been much easier to just use higher value numbers to achieve the same.

I am asking because I'd like to implement this feature (which seems to be originated by kitty?) in my own VTE, too, but before doing so, I'd like to understand it a bit more.

Many thanks in advance,
Christian Parpart.

**Comment by kovidgoyal** [comment]
colons are most definitely valid inside CSI codes, read the ECMA 48
standard. If you want to implement a VTE you definitely have to support
colons, they are used for instance for truecolor. See #226 for more
discussion.

**Comment by christianparpart** [comment]
That is interesting. Many thanks. Especially since ctlseqs.txt of xterm documentation does not mention that and used the colon for that instead. I may have just overseen that.

**Comment by mintty** [comment]
Colon is 0x3A, by the way. Maybe rename the issue?

**Comment by christianparpart** [comment]
Fixed, thanks @mintty. I mean, ticked is closed, and my actual question wasn't really answered, but yeah :-)

**Comment by mintty** [comment]
It's good to distinguish multi-value parameter clearly from other parameters, so this sub-parameter grouping was included in the standard. It's also used for a number of colour SGRs as described in ISO/IEC 8613-6.

**Comment by christianparpart** [comment]
Hey @mintty . I just checked and hoped to get a look into this standard. It seems like I have to pay a lot to be able to read that document? Is there any other way to get a look at? Otherwise I literally don't see any reason why open source applications should adhere to something that they have to pay for in order to be confirming. I am somewhat, sadly, disappointed. ;-(

**Comment by mintty** [comment]
I agree that is annoying practice but if you google for "IEC 8613-6", the first result page will lead you to a free download at ITU.
Apart from that I think it is a good concept to have parameter sub-groups in order to clearly separate and identify multi-valued parameters.

**Comment by christianparpart** [comment]
Ah. Many thanks for the ITU tip.

For the subgroups, I actually like the syntax, I just never saw that before (my source of truth was ctlseqs.txt and vt100.net until now). Thanks for the clarification.
