### ISSUE TITLE
Kitten for word completion from scrollback buffer

### ISSUE THREAD

**Issue by chin4ski** [kovidgoyal/kitty#2749]
Thanks for creating kitty!

Is it technically possible to create a kitten that allows what is described in [this Stack Exchange question](https://unix.stackexchange.com/questions/41886/auto-completion-of-words-from-the-terminal-buffer)?

**Comment by kovidgoyal** [comment]
Yes, of course. kittens are passed the entire screen contents and
scrollback contents, along with cursor position. So you just need to have
you kitten detect the current word under the cursor, look for
completions in the passed in scrollback and ask for them, once the user
selects the completion, paste it into the active window.

**Comment by chin4ski** [comment]
Thanks, that's great, I'll give it a try when I have some time. If meanwhile anyone implements this, please share!

One more question: about kittens in general, it would be nice to have some kind of "centralised repository" collecting them, so that it would be easier to discover them (I believe there are useful kittens out there written by users). Do you have any thought/plan about that?

**Comment by kovidgoyal** [comment]
A list of user developed kittens is at the bottom of https://sw.kovidgoyal.net/kitty/kittens/custom.html

**Comment by chin4ski** [comment]
Thanks, I missed that
