### ISSUE TITLE
[macos] Patching old .app bundle

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#275]
Sorry for bothering you with this again, but the previous method I used to patch the .app bundle (upating rpaths) seem to no longer work. Well first things first..

After doing a `python3 setup.py osx-bundle` I get the following error when trying to launch the executable (running from a terminal session with: `./linux-package/Contents/MacOS/kitty`):

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffa987d340 (most recent call first):
[1]    88404 abort      ./linux-package/Contents/MacOS/kitty
```
Now I'm fairly sure I used to be able to run the binary like this before.
As far as I can tell, the above error is an indication that the python stdlib could not be loaded or something? (excuse my lack of python knowledge)

It does run correctly if I just do `python3 setup.py build` followed by `python3 .`
I do think this is an error related to my setup, but I just fail to understand the difference between this newly built Kitty executable and the older one that I have, which is still working just fine.

I have verified that all the rpaths are the same as my currently working version of Kitty, so it does link against the proper framework. 

Any help and/or additional information would be appreciated.

**Comment by kovidgoyal** [comment]
I suggest you follow the advice in https://github.com/kovidgoyal/kitty#how-do-i-build-kitty-app-on-macos that way you do not have to worry about patching bundles. You can simply create a placeholder bundle and use that to run kitty from the source checkout.

**Comment by koekeishiya** [comment]
I tried doing the method suggested in the README as you proposed, and indeed it did work, but the running name was always "Python", which annoyed me.

I did some more investigation and tried to debug `linux-launcher.c` a bit. For some reason the binary that is generated using `python3 setup.py osx-bundle` ends with a `PyObject_CallMethod(pyrun, ...)` that basically does nothing at all, and the program exits immediately without any error.

Interestingly enough, if I build with `python3 setup.py linux-package` everything works just fine, and so I wrote a basic script that performs `python3 setup.py linux-package` and creates a fresh .app (with the correct path for **../lib/kitty** rather than **../Framework/kitty**)

Anyway enough rambling, thanks again for Kitty and the insight you've provided :)

**Comment by kovidgoyal** [comment]
osx-bundle is really not meant to be used by anything other than the official app. As for using the name Python, you probably just need to edit the Info.plist and change the name there.

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/kitty/commit/566e641be1ae493d90b8617fc27e5e48317d681c

that lets you build the wrapper kitty.app easily with correct icon/app name. I haven't tested it however.

**Comment by dsanson** [comment]
Following the latest instructions, I get an app that has the correct icon and the correct name in the dock, but the name in the menubar is still "Python". I suspect this might be an inherent limitation of packaging a mac app as a wrapper around a script stub.

**Comment by koekeishiya** [comment]
For what its worth, I did the following:

Create a new folder called kitty_template inside the root folder my local kitty git repository.
Copy the kitty.icon file from an existing kitty.app bundle into the kitty_template folder.
Copy the kitty .plist file from an existing kitty.app bundle into the kitty_template folder.

Run the following script:
```
#!/bin/bash

rm -rf ./linux-package
rm -rf ./kitty.app

python3 setup.py clean
python3 setup.py build
python3 setup.py linux-package

mkdir ./kitty.app
mkdir ./kitty.app/Contents
mkdir ./kitty.app/Contents/MacOS
mkdir ./kitty.app/Contents/Resources

cp ./linux-package/bin/kitty ./kitty.app/Contents/MacOS/kitty
cp ./kitty_template/Info.plist ./kitty.app/Contents/Info.plist
cp ./kitty_template/kitty.icns ./kitty.app/Contents/Resources/kitty.icns
cp -r ./linux-package/lib ./kitty.app/Contents
```

This creates a working kitty.app for me, that runs just as any officially distributed kitty.app.
Do notice that this does not adhere to any kind of "good practices" or whatever on macOS, and it doesn't even use the `Frameworks` directory that app bundles "must have" or whatever. I don't particularly care about this, as long as it works fine.

**Comment by kovidgoyal** [comment]
This should take care of it: https://github.com/kovidgoyal/kitty/commit/236c92b2b40d468ac2272ab56d4b741befd66d99
