### ISSUE TITLE
Add a directory for usage examples + first contribution: inline gnuplot diagrams

### ISSUE THREAD

**Issue by bjorn-fischer** [kovidgoyal/kitty#2750]
The **kitty** terminal is a powerful application opening new possibilities that were unthinkable beforehand. Well, with heavy and ugly tmux hacking, maybe. After installing kitty one may be overwhelmed by the new degrees of freedom. So it might be a good idea to provide a collection of examples of what to do with kitty (and how). Not just within the documentation, but by means of an *example* or *user-contrib* directory like `/usr/share/docs/kitty/examples`.

Here is my suggestion for a first contribution:
Put this into your `~/.bashrc` to get inline plots from **gnuplot**:
```
#
# needs ImageMagick (for icat) and gnuplot
#
function iplot {
    cat <<EOF | gnuplot
    set terminal pngcairo enhanced font 'Fira Sans,10'
    set autoscale
    set samples 1000
    set output '|kitty +kitten icat --stdin yes'
    set object 1 rectangle from screen 0,0 to screen 1,1 fillcolor rgb"#fdf6e3" behind
    plot $@
    set output '/dev/null'
EOF
}
```
Source this and then type, e.g. `iplot 'sin(x*3)*exp(x*.2)'`

**Comment by kovidgoyal** [comment]
I like the idea of having user contributed examples. However, I am dubious as to their discoverability in /usr/share/docs. Many systems such as macOS ones cant have documentation installed there by user software like kitty. And even on Linux many people dont know to look there. 

And there are already lists to third party kittens here: https://sw.kovidgoyal.net/kitty/kittens/custom.html  and programs that use the kitty graphics protocols here: https://sw.kovidgoyal.net/kitty/graphics-protocol.html

I think a good way forward is to have a a section in the docs titled something like "Cool kitty integrations" or similar. Consolidate those lists there, and allow people to submit new ones.
