### ISSUE TITLE
increased memory consumption with more tab

### ISSUE THREAD

**Issue by nirmoy** [kovidgoyal/kitty#2751]
**Describe the bug**
More tab = more memory and thats fine but if I close tabs kitty won't reclaim memory  
**To Reproduce**
1 Keep adding tabs and observe RSS consumption

**Expected behavior**
As I close tabs RSS should be reduced

**Enviroment details**
OS:  Linux + wayland

**Comment by kovidgoyal** [comment]
I cannot replicate, while RSS certainly grows with new tabs a certain
aountm beyond a point it stops growing and is reclaimed when tabs are
closed. This is to be expected with python which uses arenas for
allocation, and does not release all memory to the OS when objects are
destroyed.
