### ISSUE TITLE
Windows in "splits" layout leaves a mark after being closed

### ISSUE THREAD

**Issue by marioortizmanero** [kovidgoyal/kitty#2752]
**Describe the bug**
Normal kitty, version 0.17.4.r158.g5f6faa1b-1:

![image](https://user-images.githubusercontent.com/25647296/84045584-432fe180-a9a9-11ea-9514-4577b5d01591.png)

Changing layout to "splits" and opening a new window:

![image](https://user-images.githubusercontent.com/25647296/84046210-14fed180-a9aa-11ea-8379-be5e815c9b9c.png)

After closing with ctrl+C the new window, some marks are left at the top and the bottom. This also happens with horizontal splits:

![image](https://user-images.githubusercontent.com/25647296/84046277-28aa3800-a9aa-11ea-8605-6056402b207a.png)
![image](https://user-images.githubusercontent.com/25647296/84047128-3ad8a600-a9ab-11ea-8b7c-7788ac431601.png)

**To Reproduce**
1. `kitty @ goto-layout splits`
2. `kitty @ launch cat`
3. close the new window with Ctrl + C, Ctrl + D or whatever you want

**Enviroment details**
OS: Arch Linux

```
~
❯ kitty --debug-config
kitty 0.17.4 (5f6faa1bf0) created by Kovid Goyal
Linux glowarch 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/mario/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background   Color(red=187, green=192, blue=201)
active_tab_foreground   Color(red=40, green=44, blue=52)
allow_remote_control    y
background              Color(red=40, green=44, blue=52)
bold_font               SF Mono Bold
bold_italic_font        SF Mono Bold Italic
color0                  Color(red=40, green=44, blue=52)
color1                  Color(red=224, green=108, blue=117)
color10                 Color(red=86, green=182, blue=194)
color11                 Color(red=229, green=192, blue=123)
color12                 Color(red=97, green=175, blue=239)
color13                 Color(red=190, green=80, blue=70)
color14                 Color(red=86, green=182, blue=194)
color15                 Color(red=171, green=178, blue=191)
color2                  Color(red=152, green=195, blue=121)
color3                  Color(red=229, green=192, blue=123)
color4                  Color(red=97, green=175, blue=239)
color5                  Color(red=190, green=80, blue=70)
color6                  Color(red=86, green=182, blue=194)
color7                  Color(red=183, green=188, blue=199)
color8                  Color(red=57, green=62, blue=72)
color9                  Color(red=209, green=154, blue=102)
font_family             SF Mono
font_size               12.0
foreground              Color(red=187, green=192, blue=201)
inactive_tab_background Color(red=40, green=44, blue=52)
inactive_tab_foreground Color(red=171, green=178, blue=191)
italic_font             SF Mono Regular Italic
selection_background    Color(red=187, green=192, blue=201)
selection_foreground    Color(red=40, green=44, blue=52)
window_padding_width    FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
```

**Additional context**
This also happens with a minimal config file that only enables `allow_remote_control` (though it's less noticeable, as no `window_padding_width` is set:

![image](https://user-images.githubusercontent.com/25647296/84046793-d6b5e200-a9aa-11ea-8358-e2aae69b2fce.png)

And doesn't happen with other layouts like `grid` (ignore the `--location` parameter in the last command):

![image](https://user-images.githubusercontent.com/25647296/84046859-ecc3a280-a9aa-11ea-8bb3-5516cd18023f.png)

**Comment by kovidgoyal** [comment]
Doesnt repro for me. Wht is the other layout you are going back to?

**Comment by marioortizmanero** [comment]
Just launched a brand new install of Ubuntu 20.04 in a VM to test it and it also happens in there, see at the bottom and top:

![image](https://user-images.githubusercontent.com/25647296/84086730-d9cfc300-a9e8-11ea-821f-9ae73cc45460.png)

I used [this script I found](https://gist.github.com/reed-jones/b7ea9ce2c79d3809494f78affc1d58d3) to build it inside Ubuntu, and it's only using X11 libraries, so it might be related to that (as in, building of wayland backend was disabled). I'll investigate more on this to see if I'm right.

> Doesnt repro for me. Wht is the other layout you are going back to?

In the examples it's the default config, so whatever the default is (I think "fat").

**Comment by marioortizmanero** [comment]
Okay this seems to happen even on Wayland:

![image](https://user-images.githubusercontent.com/25647296/84087613-cde50080-a9ea-11ea-8c0b-8d8fefde8779.png)

(I compiled it properly, and set `linux_display_server` to  `wayland`)

**Comment by kovidgoyal** [comment]
I doubt it has anything to do with display backend. Does it happen at
all window sizes for you?

**Comment by kovidgoyal** [comment]
Aah I think I got it, you are seeing the remnant white lines in the splits layout itself not returning to the previous layout. With that I am able to reproduce.

**Comment by marioortizmanero** [comment]
Great! That indeed worked. Thanks :)
