### ISSUE TITLE
URLs are not selected properly

### ISSUE THREAD

**Issue by skorokithakis** [kovidgoyal/kitty#2756]
On Kitty 0.17.4, double-clicking on a displayed URL doesn't highlight the protocol part. Ie, if I double-click on "https://www.example.com", only "//www.example.com" will be highlighted. This completely breaks the double-click functionality, since I now always have to click and drag to select URLs.

**Comment by Luflosi** [comment]
Dup of #2705. It's fixed in master. Either wait for the next version or build from source.

**Comment by skorokithakis** [comment]
Ah, I searched but didn't find that issue, thanks.
