### ISSUE TITLE
Allow Customizing "create_marker" Prompt

### ISSUE THREAD

**Issue by Rayqan** [kovidgoyal/kitty#2757]
Would you consider adding the option to customize the prompt shown when dynamically creating a marker?

**Comment by kovidgoyal** [comment]
Why?

**Comment by kovidgoyal** [comment]
no followup

**Comment by kovidgoyal** [comment]
How would prompt customization help with that? You are presumably asking for the ability to name marker functions with a "friendly name" and display that name while scrolling through history??
