### ISSUE TITLE
weird kerning compared to other terminal emulators

### ISSUE THREAD

**Issue by vthriller** [kovidgoyal/kitty#2758]
**Describe the bug**

![urxvt-sakura-kitty](https://user-images.githubusercontent.com/176062/84296522-cc374c00-ab54-11ea-8ae1-d22c0f916263.png)

Note the `0K`, `CR`.

Here's animated version:

![urxvt-sakura-kitty](https://user-images.githubusercontent.com/176062/84296519-cb061f00-ab54-11ea-84c5-506ce551b3ec.gif)

All terminals are configured to use `DejaVu Sans Mono-8`, DPI is 103×103.

**Enviroment details**

```
$ kitty --debug-config
kitty 0.17.4 created by Kovid Goyal
Linux random 5.4.38-gentoo #1 SMP Tue May 19 14:32:41 MSK 2020 x86_64
This is \n.\O (\s \m \r) \t
Loaded config files: /home/thriller/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background                 Color(red=255, green=255, blue=255)
bold_font                  DejaVu Sans Mono Bold
box_drawing_scale          (0.5, 0.5, 0.5, 1.0)
color0                     Color(red=34, green=34, blue=34)
[…other colors snipped for brevity…]
cursor_stop_blinking_after 0
cursor_text_color          None
disable_ligatures          2
font_family                DejaVu Sans Mono
font_size                  8.0
foreground                 Color(red=0, green=0, blue=0)
```

**Comment by kovidgoyal** [comment]
This will be because of anti-aliasing, with anti-aliasing K is large enough to fill the cell width, increase the cell width a bit and you will be fine, as I suggested earlier.
![Screenshot_20200611_073739](https://user-images.githubusercontent.com/1308621/84337261-c07c7180-abb6-11ea-9fcc-0624ef86c3f4.png)
