### ISSUE TITLE
kitty screen corrupted

### ISSUE THREAD

**Issue by avkoval** [kovidgoyal/kitty#2759]
**Describe the bug**

When I start kitty it shows well. Then I change terminal size and screen gets corrupted.

**Expected behavior**
There should not be unexpected characters on the screen

**Screenshots**

![](http://scr.ua2web.com/avk/ss_20200611061904_dz6UQjl06cpOntpUnCeL.png)

**Enviroment details**

```
OS: arch linux
kitty: community/kitty 0.17.4-1 [installed]
```

Output of kitty --debug-config

```
vkoval@avkdell ~ $ kitty --debug-config                                                                                                                                     06:21:52
kitty 0.17.4 created by Kovid Goyal
Linux avkdell 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /mnt/ubuntu/home/k/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background  Color(red=255, green=255, blue=221)
font_family Iosevka
foreground  Color(red=4, green=4, blue=3)
```

**Additional context**
It started to appear after recent system update.

**Comment by kovidgoyal** [comment]
This will be a bug in your system, probably mesa. Roll the update back and you should be fine.
