### ISSUE TITLE
kitty icat --place doesn't always display the image

### ISSUE THREAD

**Issue by dsanson** [kovidgoyal/kitty#276]
I've been playing around with `kitty icat --place`, and I've noticed that sometimes an image simply won't display given a specific set of dimensions. For example, I have an image, `test.png` and I can get it to display using:

    kitty icat --place 10x10@0x0 test.png

but I get nothing when I try:

    kitty icat --place 139x41@0x0 test.png

This is in a window whose dimensions are 143x42. Lots of other combinations work, but every once and awhile, one of them just doesn't.

**Comment by dsanson** [comment]
It does not seem to depend on the size of the terminal.

**Comment by kovidgoyal** [comment]
Works for me with the following:
```
convert kitty/logo.png -scale 10x10 /tmp/test.png
kitty icat --place 139x41@0x0 /tmp/test.png
```

I get a tiny version of the kitty logo 10x10 displayed in the middle of the top row of the terminal. Note that --place does not scale images up to fit the specified rectangle only down. 

The only other variable I can think of is the size of a cell. It might be that the size at which problems occur is related to the size (in pixels) of a cell in the terminal. You can get that size by running

kitty -c "import struct, fcntl, termios; s = struct.pack('HHHH', 0, 0, 0, 0); x = fcntl.ioctl(1, termios.TIOCGWINSZ, s); print(struct.unpack('HHHH', x))"

This will print out
(number of rows, number of columns, screen width in px, screen height in px)

**Comment by kovidgoyal** [comment]
Actually, make that command a little simpler:
```
kitty -c "from kitty.icat import *; print(screen_size())"
```

**Comment by kovidgoyal** [comment]
Oh and you can use ctrl+shift++/- to increase/decrease the cell size to test things.

**Comment by kovidgoyal** [comment]
Also, just FYI, newer versions of kitty automatically ensure that the kitty command is in PATH when running on macOS (I noticed you have instructions about symlinking kitty in your termpdf readme).

**Comment by dsanson** [comment]
Ah, I think we are getting somewhere. If I change the font size (using keys mapped to `increase_font_size` or `decrease_font_size`), then I can get it to display. Here is the output of your command at my default font size:

    Size(rows=27, cols=53, width=954, height=972)

Here are some commands that work:

    kitty icat --place 139x40@0x0 test.png
    kitty icat --place 139x44@0x0 test.png

Here are several that don't work:

    kitty icat --place 139x41@0x0 test.png
    kitty icat --place 139x42@0x0 test.png
    kitty icat --place 139x43@0x0 test.png

Here is the output of your command when the font size has been decreased by two steps:

    Size(rows=30, cols=60, width=960, height=960)

That changes everything: now 139x40 and 139x44 don't work, but 139x41, 42, and 43 all work.

**Comment by kovidgoyal** [comment]
Hmm, I still cannot replicate even when the cell height is 36 as in your example. Makes it a little hard to debug. Can you run kitty from source and make a few changes to icat.py? Here's a diff to output some debugginf info:

```diff
diff --git a/kitty/icat.py b/kitty/icat.py
index a3f4cb6..42db709 100755
--- a/kitty/icat.py
+++ b/kitty/icat.py
@@ -164,6 +164,7 @@ def set_cursor_for_place(place, cmd, width, height, align):
         extra_cells = (place.width - num_of_cells_needed) // 2
     elif align == 'right':
         extra_cells = place.width - num_of_cells_needed
+    print(place.top + 1, x + extra_cells)
     sys.stdout.buffer.write('\033[{};{}H'.format(place.top + 1, x + extra_cells).encode('ascii'))
 
 
@@ -182,6 +183,7 @@ def write_chunked(cmd, data):
 
 def show(outfile, width, height, fmt, transmit_mode='t', align='center', place=None):
     cmd = {'a': 'T', 'f': fmt, 's': width, 'v': height}
+    print(cmd)
     if place:
         set_cursor_for_place(place, cmd, width, height, align)
     else:
```

**Comment by kovidgoyal** [comment]
Also, just in case attach the test.png you are using.

**Comment by kovidgoyal** [comment]
You might be interested in this: https://github.com/kovidgoyal/kitty/commit/03702772d3e45a58d7d4b6c7252dc3b6caecd3ae

**Comment by kovidgoyal** [comment]
I found a bug, though I cant say if it is the cause of your issue or not, try https://github.com/kovidgoyal/kitty/commit/b02ef0a7fbdf19388b2430207c44f750ef3761e9

**Comment by kovidgoyal** [comment]
Sorry wrong commit, make that: https://github.com/kovidgoyal/kitty/commit/025a46bb35a99354483b45f56b51e445f7e431d2

**Comment by dsanson** [comment]
I am running into another bug when trying to run from source. When I try to display an image, it occasionally works, but about 90% of the time, I get:

    $ kitty icat test.png
    ^[_Gi=1;OK^[\^[_Gi=2;OK^[\0s max. wait)...

and, after a few seconds, that transforms into:

```
^[_Gi=1;OK^[\^[_Gi=2;OK^[\This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it
```

But this isn't right, and the usual test for support works fine: 

     $ kitty icat --detect-support && echo "yes"
     fileyes

As a workaround, I deleted the lines:

```python
        if not detect_support(wait_for=args.detection_timeout):
            raise SystemExit('This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it')
    else:
```

That got me back to a working version of icat. But, unfortunately, the bug is still there with the same symptoms described above. I added the lines to report info. Here is what I get:

```bash
$  kitty icat --place 139x40@0x0 test.png
{'a': 'T', 'f': 32, 's': 1112, 'v': 1440}
(1, 39)
$  kitty icat --place 139x41@0x0 test.png
{'a': 'T', 'f': 32, 's': 1139, 'v': 1476}
(1, 38)
$  kitty icat --place 139x42@0x0 test.png
{'a': 'T', 'f': 32, 's': 1167, 'v': 1512}
(1, 38)
$  kitty icat --place 139x43@0x0 test.png
{'a': 'T', 'f': 32, 's': 1195, 'v': 1548}
(1, 37)
$  kitty icat --place 139x44@0x0 test.png
{'a': 'T', 'f': 32, 's': 1223, 'v': 1584}
(1, 36)
```

As before, x40 and x44 display an image, but x41, 42, and 43 don't.

Here is the image:

![test](https://user-images.githubusercontent.com/14331/34781073-7eaee5aa-f5ea-11e7-8d99-bffb643110b5.png)

I used imagemagick to convert it to jpg and got the same symptoms. The png was originally produced by pdftocairo from a pdf file. I randomly tried several images I had lying around, and only some of them seem to have the problem. Maybe a common feature is being generated by pdftocairo: I seem to be able to regularly generate the problem by converting pdf files to png or jpg using pdftocairo.

Here is another file that has the same problem for me. I think it was also generated by pdftocairo.

![saturday morning breakfast cereal - philosophy](https://user-images.githubusercontent.com/14331/34781596-d87cb3ea-f5eb-11e7-9d4b-c319cac8a9f9.png)

With all the same settings, it fails to display for heights of 30, 31, 33, 34, 37 and 40. But displays fine for heights of 32, 35, 36, 38, and 39, 41, 42, 43, and 44:

```bash
$ kitty icat --place 139x30@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 890, 'v': 1080}
(1, 45)
$ kitty icat --place 139x31@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 920, 'v': 1116}
(1, 44)
$ kitty icat --place 139x32@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 950, 'v': 1152}
(1, 44)
$ kitty icat --place 139x33@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 979, 'v': 1188}
(1, 43)
$ kitty icat --place 139x34@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1009, 'v': 1224}
(1, 42)
$ kitty icat --place 139x35@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1039, 'v': 1260}
(1, 41)
$ kitty icat --place 139x36@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1069, 'v': 1296}
(1, 40)
$ kitty icat --place 139x37@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1098, 'v': 1332}
(1, 40)
$ kitty icat --place 139x38@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1128, 'v': 1368}
(1, 39)
$ kitty icat --place 139x39@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1158, 'v': 1404}
(1, 38)
$ kitty icat --place 139x40@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 32, 's': 1187, 'v': 1440}
(1, 37)
$ kitty icat --place 139x41@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 100, 's': 1215, 'v': 1473}
(1, 36)
$ kitty icat --place 139x42@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 100, 's': 1215, 'v': 1473}
(1, 36)
$ kitty icat --place 139x43@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 100, 's': 1215, 'v': 1473}
(1, 36)
$ kitty icat --place 139x44@0x0 Saturday\ Morning\ Breakfast\ Cereal\ -\ Philosophy.png
{'a': 'T', 'f': 100, 's': 1215, 'v': 1473}
(1, 36)
```

**Comment by kovidgoyal** [comment]
Good, with the test image I am able to reproduce. I'll look into it.

**Comment by kovidgoyal** [comment]
Just FYI, you can improve performance with a couple of tweaks:

1) Generate uncompressed PNG
2) Generate PNG of the actual size needed for display, so that icat does not have to resize images. If it does not have to resize images, it can transmit the PNG directly to kitty. You can use the command I posted earlier to get the screen size and use that to calculate the required image dimensions.

**Comment by dsanson** [comment]
Thanks for the fix! And thanks for the tips!

**Comment by kovidgoyal** [comment]
One more performance tip (this is particularly relevant over ssh). Store the output from --detect-support and use it with --transfer-mode. This means that subsequent invocations of icat will avoid a round-trip at the beginning to detect support.
