### ISSUE TITLE
new_window with given relative size

### ISSUE THREAD

**Issue by duranivan** [kovidgoyal/kitty#2760]
I'm really enjoying kitty as a replacement for iTerm. Kitty is really fast, even compared to alacritty. Thanks for this!

_I have this question or feature request:_

**Is your feature request related to a problem? Please describe.**

In tmux I am able to create a new horizontal/vertical pane which is 20% of the current window size, e.g `bind-key = split-window -v -p 20`.

I would like to do the same in kitty!

**Describe the solution you'd like**
Create a shortcut so I can create a new window with size relative to the one it was created from.

**Describe alternatives you've considered**
So far I have this mapping: `map kitty_mod+= combine : new_window : goto_layout vertical` which creates a new window in the bottom but it is 50% of the current window size.

I just want to be able to determine the relative size of the new window, say 20% of the original.

Thanks in advance!

**Comment by kovidgoyal** [comment]
Use the splits layout and 

map whatever launch --location=hsplit

this will split at 50% you can then use the resize_window operation to resize,
using combine to combine the two.

See the docs. https://sw.kovidgoyal.net/kitty/launch.html

**Comment by duranivan** [comment]
Great thanks! it is working with something like this `map kitty_mod+= combine : launch --location=hsplit : resize_window shorter 7`
