### ISSUE TITLE
Artifacts after resizing, look like waves

### ISSUE THREAD

**Issue by mb720** [kovidgoyal/kitty#2765]
Hi!

With Kitty 0.17.4, I occasionally see wavy artifacts after resizing a window (I'm using Sway):

![kitty with artifacts](https://i.imgur.com/LkRTaBG.png)

`clear`ing the terminal doesn't help.
Changing the size of the window doesn't get rid of the artifacts either.

**Comment by kovidgoyal** [comment]
dup of #2747
