### ISSUE TITLE
Open file in Visual Studio Code and jump directly to that line

### ISSUE THREAD

**Issue by screendriver** [kovidgoyal/kitty#2766]
**Is your feature request related to a problem? Please describe.**

When I run my unit tests in `kitty` I can see at which line and column one test fails. Unfortunately I can't click on that file.

<img width="490" alt="Screenshot 2020-06-15 at 16 16 29" src="https://user-images.githubusercontent.com/149248/84668193-995dd100-af23-11ea-8f0f-455144e91ca7.png">

(here it would be `test/unit/branch.test.ts:5:16`)

**Describe the solution you'd like**

I wish I could just click on that file and my `Visual Studio Code` opens directly with that file and the cursor is exactly at that line and column.

**Describe alternatives you've considered**

When I run my unit tests directly in `Visual Studio Code`'s built in terminal I can do what I want:

<img height="600" alt="Screenshot 2020-06-15 at 16 16 29" src="https://user-images.githubusercontent.com/149248/84668314-c9a56f80-af23-11ea-8ae9-2269b7ca30c7.gif">

**Additional context**

I'm aware that I can define my own keyboard shortcuts / actions in my `kitty.conf`. Especially the [launch action](https://sw.kovidgoyal.net/kitty/launch.html) but I don't know if that's possible what I want to achieve.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/hints.html

**Comment by screendriver** [comment]
Would you mind to maybe assist me with that? I tried many combinations but I don't get it to work. Luckily Visual Studio Code can opened with exact the argument I need:

``` sh
# Open a file at the path on the specified line and character position
$ code --goto <file:line[:character]>
```

In my `kitty.conf` I tried for example:

```
# Opens VIM although I specified - which should paste it in my terminal
map kitty_mod+p>v kitten hints --type linenum --program -
# Same here. Just copy to clipboard it opens VIM
map kitty_mod+p>v kitten hints --type linenum --program @
# Includes ( in the path: code -g '(test/unit/branch.test.ts:5:0'
map kitty_mod+p>v kitten hints --type linenum code -g {path}:{line}:0
# Prints exactly what I need in my terminal: test/unit/branch.test.ts:5:16
map kitty_mod+p>v kitten hints --type path --program -
# Unknown option: -g
map kitty_mod+p>v kitten hints --type path --program code -g
# Does nothing
map kitty_mod+p>v kitten hints --type path --program "code -g"
# Extra command line arguments present: code -g
map kitty_mod+p>v kitten hints --type path code -g
```

PS: what is the difference between `--program code` and just `code` without `--program`?

**Comment by kovidgoyal** [comment]
See the example in the docs:

map ctrl+g kitten hints --type=linenum --linenum-action=tab nvim +{line} +{path}

**Comment by screendriver** [comment]
But as I already wrote this does not work. It either gives me the message `Extra command line arguments present: code -g` or `Unknown option: -g` or it does nothing (see the comments `#` that I wrote for every single mapping)

**Comment by kovidgoyal** [comment]
Read the help, for --type=linenum, and then the help for --linenum-action

**Comment by kovidgoyal** [comment]
For the extra comman line options present error use a -- before code, like this:

map ctrl+g kitten hints --type=linenum --linenum-action=background -- code whatever

**Comment by screendriver** [comment]
> Read the help, for --type=linenum, and then the help for --linenum-action

I did this

> map ctrl+g kitten hints --type=linenum --linenum-action=background -- code whatever

#### --type=linenum

I tried `map kitty_mod+p>v kitten hints --type=linenum --linenum-action=background -- code -g` but nothing happens

I tried `map kitty_mod+p>v kitten hints --type=linenum --program -- code -g` and Visual Studio Code opens but not with the given file	

I tried `map kitty_mod+p>v kitten hints --type=linenum -` to see which file it tries to open but then I get a `Unknown option: -`

I tried `map kitty_mod+p>v kitten hints --type=linenum --program -` o see which file it tries to open but instead of printing it to the console like it's written in the help it opens `vim`. Also there is nothing mentioned in the help about what is the difference between using or not using `--program`

#### --type=path

I tried `map kitty_mod+p>v kitten hints --type=path -` but then I get a `Unknown option: -`

I tried `map kitty_mod+p>v kitten hints --type=path --program -` and now it prints me the found path to my terminal (here is the first difference to `--linenum` where it behaves differently)

I tried `map kitty_mod+p>v kitten hints --type=path -- code -g` but then I get a `Extra command line arguments present: code -g` (this is the second time where `--linenum` behaves differently)

I tried `map kitty_mod+p>v kitten hints --type=path --program -- code -g` and I get a `Extra command line arguments present: code -g` (again a different behaviour than `--linenum`)

**Comment by kovidgoyal** [comment]
--program does not apply to --linenum, which you would know if you had
actually read the help. 

And I'm afraid I am not installing vscode to help you.

**Comment by screendriver** [comment]
> which you would know if you had actually read the help.

Where exactly? I can't find any paragraph that mentions that 😢 

> And I'm afraid I am not installing vscode to help you.

Just try it with any other program that accepts arguments with a dash `-`. This errors are not related to Visual Studio Code itself. Just a gut feeling: could it be that your code interprets the given dash as an additional argument to `kitten hints`? So for example when I use `map kitty_mod+p>v kitten hints --type=path --program -- foo -bar` it says `Extra command line arguments present: foo -bar`

**Comment by kovidgoyal** [comment]
On Mon, Jun 15, 2020 at 08:51:41PM -0700, Christian Rackerseder wrote:
> > which you would know if you had actually read the help.
> 
> Where exactly? I can't find any paragraph that mentions that 😢 

https://sw.kovidgoyal.net/kitty/kittens/hints.html#cmdoption-kitty-kitten-hints-type

> 
> > And I'm afraid I am not installing vscode to help you.
> 
> Just try it with any other program that accepts arguments with a dash `-`. This errors are not related to Visual Studio Code itself. Just a gut feeling: could it be that your code interprets the given dash as an additional argument to `kitten hints`? So for example when I use `map kitty_mod+p>v kitten hints --type=path --program -- foo -bar` it says `Extra command line arguments present: foo -bar`

That's what the standalone -- is for it stops interpretation of arguments after it. If it s not working, it may well be a bug, a PR fixing it is most welcome. Or just write a trivial two line wrapper script for invoking vscode.

**Comment by kovidgoyal** [comment]
And I just tried it with:
```
kitty -o 'map ctrl+g kitten hints --type=linenum vim -u NONE +{line} {path}'
```

it works fine. I have now wasted as much time as I am going to on this. Good luck.

**Comment by screendriver** [comment]
Thanks a lot

**Comment by trygveaa** [comment]
@screendriver: Read the docs for `--linenum-action`:

> The action to perform on the matched errors. The actual action is whatever arguments are provided to the kitten, for example: kitty + kitten hints --type=linenum vim +{line} {path} will open the matched path at the matched line number in vim.

 You haven't showed any attempts where you use `--linenum-action` together with `{path}` and `{line}`.

This mapping works:

    map kitty_mod+g      kitten hints --type=linenum --linenum-action=background -- code -g {path}:{line}

The hints kitten doesn't support providing the column though, just the line.

**Comment by screendriver** [comment]
> You haven't showed any attempts where you use --linenum-action together with {path} and {line}

I did in my first https://github.com/kovidgoyal/kitty/issues/2766#issuecomment-644258862 😉 Ok, without `--linenum-action` because I thought it doesn't matter if I provide an action or not:

```
# Includes ( in the path: code -g '(test/unit/branch.test.ts:5:0'
map kitty_mod+p>v kitten hints --type linenum code -g {path}:{line}:0
```

The main problem here is that it includes the leading `(` when it parses the line 

```
       at Context.<anonymous> (test/unit/branch.test.ts:5:16)
```

That was the reason why I tried to use `--type=path` instead of `--type=linenum`

> The hints kitten doesn't support providing the column though, just the line.

That's fine for me. The line is enough ☺️

**Comment by trygveaa** [comment]
> I did in my first #2766 (comment) wink Ok, without --linenum-action because I thought it doesn't matter if I provide an action or not:

Whether you include `--linenum-action` matters very much... That's the parameter that allows you to include the editor as an argument, like it says in the docs:

> The action to perform on the matched errors. The actual action is whatever arguments are provided to the kitten

> The main problem here is that it includes the leading ( when it parses the line

Okay, that was not clear from your previous comments. I see now that you only mentioned it briefly in the middle of one of your blocks of attempts.

> That was the reason why I tried to use --type=path instead of --type=linenum

linenum is special, so you can't just use another type because `--linenum-action` only works with `--type=linenum`, and `--linenum-action` is what you want to use. (or, technically you can use another type, but you have to set `--customize-processing='::linenum::'`)

What you want to do is modify the regex that linenum uses so that it doesn't match the parenthesis. You can provide it with the `--regex` option. The default regex is `(?P<path>(?:\S*/\S+?)|(?:\S+[.][a-zA-Z0-9]{2,7})):(?P<line>\d+)`.

**Comment by screendriver** [comment]
**Ah!** Finally I found the solution 🎉 

It did **not** work with:

```
map kitty_mod+p>v kitten hints --type=path --program code -g
map kitty_mod+p>v kitten hints --type=path --program -- code -g
map kitty_mod+p>v kitten hints --type=path --program "code -g"
map kitty_mod+p>v kitten hints --type=path --program -- "code -g"
map kitty_mod+p>v kitten hints --type=path --program /usr/local/bin/code -g
map kitty_mod+p>v kitten hints --type=path --program -- /usr/local/bin/code -g
```

But it worked with 

```
map kitty_mod+p>v kitten hints --type=path --program "/usr/local/bin/code -g"
```

🕺 

Thank you very much trying to help me @kovidgoyal and @trygveaa . Such a great terminal emulator! 💪

**Comment by trygveaa** [comment]
Right, okay. Since the `-g` option for VS code expects the path/line/column in exactly the same format as it's printed in your terminal, you can use `--program` instead of `--linenum-action`.

**Comment by screendriver** [comment]
Do you know why I have to provide the full qualified path to `code` and why I have to wrap it in quotes?

**Comment by trygveaa** [comment]
The reason you have to use the full path probably has to do with where you're including `/usr/local/bin` in `$PATH`. If you do that in your shell configuration kitty won't see it unless you open kitty from another shell. You have to do it system wide (how to do that depends on the system).

You have to wrap it in quotes because the whole thing has to be an argument to `--program`. While `--linenum-action` allows you to specify the command arguments at the end, `--program` is just a normal option which takes a single argument, so you have to specify the path and the options as a single argument.

**Comment by dylankb** [comment]
I'll leave the solution the worked for me case it helps others that land here via search (thanks @screendriver).

```
# https://github.com/kovidgoyal/kitty/issues/2766#issuecomment-644561577
map kitty_mod+p>v kitten hints --type linenum code -g {path}:{line}:0`
```

The other two solutions cited in this thread did not work for me - the session window just flashed. Perhaps an error message is being swallowed. 

```
# https://github.com/kovidgoyal/kitty/issues/2766#issuecomment-644576683
map kitty_mod+p>v kitten hints --type=path --program "/usr/local/bin/code -g"
# https://github.com/kovidgoyal/kitty/issues/2766#issuecomment-644555695
map kitty_mod+g      kitten hints --type=linenum --linenum-action=background -- code -g {path}:{line}
```

I am a little mystified that my solution works. I would expected the solution to require either `--linenum-action` ("The action to perform on the matched errors...") or `--program` ("What program to use to open matched text..."), but I didn't look into source code or exhaustively try different options. Note: this will dump a `code -g /path/to/test` into your terminal since it does not use `--linenum-action=background`, I believe.

Anyways, kitty is a great tool - thank you!

**Comment by davidsierradz** [comment]
You can also use a hint of type `path` with a custom program to pre-process the input:

```conf
map kitty_mod+p>shift+n kitten hints --type path --program vv
```

And a script `vv`:

```sh
#!/bin/bash

set -eo pipefail

function vv() {
  path=$(awk -F ':' '{print $1}' <<< "$1")
  line=$(awk -F ':' '{print $2}' <<< "$1")
  nvr \
    --servername "$(nvr --serverlist | head -n1)" \
    +"$line" "$path" \
    && xdotool search --name "NVIM" windowactivate --sync
}

vv "$1"
```
