### ISSUE TITLE
Ligature not showing properly 

### ISSUE THREAD

**Issue by shulhi** [kovidgoyal/kitty#2767]
**Describe the bug**

`<*>` is shown as ` with JetBrains Mono font

**To Reproduce**
1. Use JetBrains Mono font with ligature enabled
2. Type `<*>`

**Expected behavior**
It should render the ligature properly

**Screenshots**
![image](https://user-images.githubusercontent.com/913103/84731014-2b201980-afca-11ea-9bcc-cf7ac4e3d464.png)

This is how it should be rendered based on JetBrains Mono website,
![image](https://user-images.githubusercontent.com/913103/84731077-54d94080-afca-11ea-977d-d25691e2a579.png)

**Enviroment details**
OS: Ubuntu 20.04 with kernel 5.4.0-33-generic
Kitty version: 0.17.4

**Comment by shulhi** [comment]
It's probably an issue with the font? I tried on OSX (iterm2 with ligatures enabled) and `<*>` returns nothing.

**Comment by kovidgoyal** [comment]
It is almost certainly an issue with the font. kitty does not have glyph
specific rules when handling ligatures, so if one glyph out of many
fails the problem is in that glyph

**Comment by trygveaa** [comment]
It's fixed in more recent versions of the font: https://github.com/JetBrains/JetBrainsMono/issues/245

**Comment by shulhi** [comment]
@trygveaa awesome, the recent version works now!
