### ISSUE TITLE
Improve multiple line selection with mouse

### ISSUE THREAD

**Issue by ray-x** [kovidgoyal/kitty#2770]
**Is your feature request related to a problem? Please describe.**
It is not as convenient to select multiple lines with mouse.

**Describe the solution you'd like**
I missing the features from **iTerm2** or mac Terminal when I could use:
* ~~Shift+mouse to select the lines between first click and last click.  You do not need to hold Shift or mouse-L-button all the way when you select.~~   (I found that I can use right click in kitty to do that)
* Alt+mouse to select multiple lines/word separately.

**Comment by kovidgoyal** [comment]
I dont know what alt+mouse to select lines words separately means.

**Comment by ray-x** [comment]
Hi, Kovidgoyal
Thanks for looking into this.
Take following screen shot as an example. In `iTerm2` user can select discontinued sections by holding `Alt` key and use mouse to pick the fields(either line or words) he needed. In the following example I selected and yanked follow fields:

```
<title>math/bits.TrailingZeros64</title>
<text text-anchor="middle" x="614.4606" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">math/bits.TrailingZeros64</text>
edge
<title>math/bits.TrailingZeros-&gt;math/bits.TrailingZeros64</title>
<path fill="none" stroke="#000000" d="M522.7513,-72.5708C538.8325,-63.0018 558.9648,-51.0223 576.2668,-40.7269"/>
```


<img width="617" alt="Screen Shot 2020-06-17 at 1 52 37 pm" src="https://user-images.githubusercontent.com/1681295/84853139-db148600-b0a1-11ea-8ef6-0a8dcf609bd7.png">

**Comment by kovidgoyal** [comment]
I'm afraid selections in kitty are always going to be contiguous, I am
not interested in adding support for discontinuous selections. If you
need more involved selection capabilities you should just pipe the
scrollback into an editor, and select away using your favorite tools.
