### ISSUE TITLE
[question] kitty terminfo in ncurses database

### ISSUE THREAD

**Issue by romkatv** [kovidgoyal/kitty#2773]
There are two entries in the [ncurses terminfo database](https://invisible-island.net/ncurses/terminfo.src.html) whose names start with "kitty":

- "kitty" with the description "KovId's TTY"
- "kitty-direct" with the description "KovId's TTY using direct colors"

There is no "xterm-kitty".

Are these related to https://github.com/kovidgoyal/kitty? Is any of them identical to "xterm-kitty" from kovidgoyal/kitty? Compatible with the terminal from kovidgoyal/kitty?

**Comment by kovidgoyal** [comment]
No idea, you'd have to ask the ncurses maintainer. The official kitty
terminfo is xterm-kitty distributed with kitty.

**Comment by kovidgoyal** [comment]
Oh and you can use infocmp to diff the terminfos to see if there is any difference.

**Comment by romkatv** [comment]
I'm probably going to make a full of myself by explaining something you know better than me. But I'll take the risk on the chance that there is something useful for you in my comment.

Applications that read terminfo (e.g., shells) don't do it directly. They use ncurses. So when you install a shell that cares about `TERM` (Bash, Zsh, Fish, etc), you are also installing ncurses **and its terminfo database**.

*Terminals set `TERM` environment variable for ncurses.*

Kitty essentially has two components: the client application (kitty proper) and the terminfo entry for ncurses. Those must be installed in different places. The client application must be installed on the client -- the dev machine, and the terminfo entry must be installed everywhere where the user will run shell. Kitty has a good distribution story for the client (it can be installed with the standard package manager in all popular operating systems) but not for the terminfo entry.

Since terminfo is read only by ncurses, and ncurses comes bundled with a terminfo database, the best way to distribute xterm-kitty terminfo is to include it in the ncurses database. As it's currently not included, system administrators need to manually install xterm-kitty on servers they provision. There is no package for it in any package manager I know of (it wouldn't make sense to have it because the standard place for all terminfo definitions is ncurses). Installing kitty client on the server is out of question. Downloading files from github outside of releases is also out (master branch is often unstable). So one would either need to download a whole source package from github releases (which is larger than necessary and unsigned) or `git clone` the repo (this has the benefit of signed release tags but requires `git` and wastes resources) and extract the terminfo entry from it. That's burdensome enough that most sever administrators won't do it.

**Comment by kovidgoyal** [comment]
On Wed, Jun 17, 2020 at 10:27:06PM -0700, Roman Perepelitsa wrote:
> I'm probably going to make a full of myself by explaining something you know better than me. But I'll take the risk on the chance that there is something useful for you in my comment.
> 
> Applications that read terminfo (e.g., shells) don't do it directly. They use ncurses. So when you install a shell that cares about `TERM` (Bash, Zsh, Fish, etc), you are also installing ncurses **and its terminfo database**.

There are many kinds of applications, some of which read terminfo
through ncurses, some that dont at all, and some that do it without ncurses.
terminfo is an application neutral database that DOES NOT require
ncurses.

> 
> *Terminals set `TERM` environment variable for ncurses.*

No, they set it for terminal identification. ncurses uses it to look up
terminal specific quirks in terminfo, other application use it for other
purposes.

> 
> Kitty essentially has two components: the client application (kitty proper) and the terminfo entry for ncurses. Those must be installed in different places. The client application must be installed on the client -- the dev machine, and the terminfo entry must be installed everywhere where the user will run shell. Kitty has a good distribution story for the client (it can be installed with the standard package manager in all popular operating systems) but not for the terminfo entry.
> 

No, kitty-terminfo packages exist for most operating systems as well. 
https://www.archlinux.org/packages/community/x86_64/kitty-terminfo/
https://packages.ubuntu.com/search?keywords=kitty-terminfo
https://packages.debian.org/unstable/kitty-terminfo
and so on.

Not to mention that kitty itself ships with its own terminfo definition
which all programs running inside access automatically via the TERMINFO
variable that kitty sets. The exceptions are of course, ssh and sudo/su.

For the former there is the ssh kitten that auto installs the terminfo 
on the remote server while you ssh in.

And coming to distributing terminfo via ncurses, that is a pretty bad
idea for several reasons:

1) ncurses is released maybe once a year
2) It has the same maintainer as xterm and that maintainer is not shall
we say, the best, even leaving aside conflict of interest issues whereby
he regularly gives xterm special treatment in ncurses. See for instance #879

**Comment by romkatv** [comment]
Thanks for the prompt and informative response. As I expected, you know way more about this than I do. I see that you were facetious in your previous comment, or perhaps I've asked wrong questions, but the link to https://github.com/kovidgoyal/kitty/issues/879 is exactly what I was looking for.

Cheers!

**Comment by Luflosi** [comment]
That environment variable in combination with a corresponding file somewhere on the system tells programs running in terminal emulators which escape codes to send in order to use certain features like colors, underlines, the bell sound, moving the cursor around, etc.. If you change it to anything other than the correct value, things will break depending on how different the two terminfo files are. I don't know exactly how different they are but be prepared that many things will behave weirdly or not work at all. I strongly recommend setting it to the correct value.

**Comment by romkatv** [comment]
> Just wondering if anything bad would happen if in kitty.conf we set term xterm-256color

Yes.

> That feels like terminal that should be broadly compatible with xterm-kitty .

It’s not.

**Comment by Luflosi** [comment]
Read https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer which was linked above.
It's TERM=xterm-kitty and not TERM=kitty because there are many broken programs, especially shell scripts that just test if TERM starts with xterm and then enable some functionality.

**Comment by kovidgoyal** [comment]
You've already been told its not compatible. If you dont want to believe it, there's nothing more to say. If you want to see all the differences for yourself, use infocmp.

**Comment by NickHu** [comment]
You should probably be setting `TERM=kitty`, not `TERM=xterm-256color`, if you want kitty to 'just work' without copying around terminfo files yourself. ncurses includes terminfo for modern terminals like alacritty and kitty now, but kitty sets `TERM=xterm-kitty` whereas it's filed under `kitty` in ncurses.

The odd thing is that they're different terminfos, so actually you might get different behaviour; ideally they would be unified (see https://github.com/kovidgoyal/kitty/issues/879#issuecomment-727708887).

**Comment by kovidgoyal** [comment]
@NickHu I have sent you email as well, but as I am having email deliverability issues these days, am also posting it here:
```
Sure, happy to. To see the differences run

infocmp -d kitty

inside kitty.

1) kitty is missing the km capability compared to xterm-kitty
this capability indicates suport for the meta key, which kitty does
indeed support.

2) The number of color pairs is increased from 0x7fff to 0x1000
I think only ncurses uses this, so *probably* safe to change it in
xterm-kitty to match kitty.

3) kitty is missing cvvis which is an escape code to make the cursor
visible

4) There are a bunch of key definitions missing in kitty vs xterm-kitty,
that's the properties starting with k. Some empty key definitions are
represented as empty strings in xterm-kitty and are missing in kitty.
these should possibly be changed in xterm-kitty

5) The rep escape code for repeating text is missing from kitty

6) The reset (rs1) capability in kitty is incorrect

7) The sgr capability in kitty is incorrect.

```
