### ISSUE TITLE
Lack of support for TERM=xterm-kitty

### ISSUE THREAD

**Issue by tallakt** [kovidgoyal/kitty#2774]
**Lack of support for xterm-kitty**

I find myself every time I ssh a linux server, that it does not support the env variable Kitty uses for TERM. So I get some «stone age» keyboard bindings that I fix by typing:

‘’’
$ export TERM=xterm
‘’’

I realize what Kitty is doing is probably the right thing to do, nevertheless as long as ecosystem support is not there, this is a real problem, and quite annoying

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by korncola** [comment]
the reasons i wiped kitty, its nice, but this for professional use in business env just damn annoying

**Comment by tallakt** [comment]
> the reasons i wiped kitty, its nice, but this for professional use in business env just damn annoying

I think the web page over gives a few good options for dealing with the issue. For me a remote ‘apt install kitty’ made the problem nonexistent

**Comment by korncola** [comment]
i know, i used to do `TERM=xterm` BUT:
* when switching users on the remote systems,  you are back with a non-working terminal
* when doing quickly a docker / k8s pod shell: bäm
* customer systems
* one time visit systems
* too many servers

Thats sad, cause i like the font representation on screen, the whole kitty themed stuff like custom app logo etc, the speed is awesome. May work for people with less than 10 servers an no containerization but for professional use as an DevOps and Cloud Architect when dealing with > 100 systems (also of customers), some servers I visit 5 times and never again etc. its just an unusabale toy cause this strange decision to introduce an own TERM value. Went back to iTerm2, its fonts are uglier but i dont have to change servers for 1 dev (me) using a niche product.
