### ISSUE TITLE
ssh kitten: terminfo only for ssh user, not other user (su - otheruser)

### ISSUE THREAD

**Issue by CastixGitHub** [kovidgoyal/kitty#2779]
**Is your feature request related to a problem? Please describe.**
it seems the terminfo is only applied to the user you specify in the ssh command, so if you change user terminfo is not there

**Describe the solution you'd like**
something like
cp ~/.terminfo/ /home/otheruser/.terminfo -r
in a su alias

**Comment by kovidgoyal** [comment]
Yes, the ssh kitten runs as a particular user, it cannot install terminfo
for other user accounts without elevated privileges.
