### ISSUE TITLE
Support text matching plugins / configuration

### ISSUE THREAD

**Issue by wez** [kovidgoyal/kitty#278]
One feature that I've used in urxvt and also Terminator is the ability to match text and make it clickable.
The nicest implementation I've seen so far has been that in Terminator; the matched text is rewritten as a URL and then becomes clickable.
 
The specific use-case for me is to rewrite tokens such as `T123` and have then turn into URLs that reference the task tracking system that we use.

Here's how terminator does it:
https://github.com/FreedomBen/terminator/blob/master/terminatorlib/plugins/url_handlers.py

Allowing for syntax like this in `kitty.conf` would do the job for me; there are two different things I want to match and rewrite as URLs, so this feature, if implemented, should support defining multiple transformations:

```
rewrite_as_url T[0-9]+ https://example.com/task/$1
rewrite_as_url P[0-9]+ https://example.com/paste/$1
```

Thoughts?

**Comment by kovidgoyal** [comment]
This doesn't seem like it belongs inside the terminal emulator. In kitty you can simply pipe the contents of the screen/scrollback buffer to another program in a new window/tab, which is what I use to to open URLs via the keyboard. For example, out-of-the-box pressing ctrl+shift+h will open the screen+scrollback in less.

Similarly you can simply write a short program called say my_program to scan stdin for patterns of interest and print the URLs. Then in kitty.conf, do something like:

```
map ctrl+shift+u new_window @text my_program
```

See kitty.conf for examples of the syntax/usage.

**Comment by kovidgoyal** [comment]
Oh and if you dont like using a new window/tab you can even do it in the current window by using the remote control feature (which is in master). Something like

kitty @ get-text --self --extent=screen | my_program

**Comment by kovidgoyal** [comment]
Oh and yet another option, double click the word to select it and use the shortcut for  pass_selection_to_program (see kitty.conf) to pass it to a program that converts it to a url and opens it in your browser.
