### ISSUE TITLE
kitty 0.18.0 won't run on OSX 10.13.x (High Sierra)

### ISSUE THREAD

**Issue by jwiede** [kovidgoyal/kitty#2783]
**Describe the bug**
The kitty 0.18.0 executable in the release DMG is built in such a way that OSX 10.13.6 (High Sierra) will not execute it, says "requires 10.14".  Since many OSX users with Nvidia graphics are "stuck" on High Sierra (10.13.6), maintaining support for 10.13 seems valuable.

**To Reproduce**
1. Download kitty 0.18.0 release binary DMG
2. Mount DMG
3. Note Finder puts "no go" overlay on .app
4. Attempt to execute on OSX 10.13.x, receive "requires 10.14" error.

**Expected behavior**
App executes as expected, no "no go" overlay.

**Screenshots**
![CleanShot 2020-06-21 at 13 55 01@2x](https://user-images.githubusercontent.com/5760862/85235060-e976e080-b3c6-11ea-8cac-57a9b019c368.png)
![CleanShot 2020-06-21 at 13 55 16@2x](https://user-images.githubusercontent.com/5760862/85235061-ebd93a80-b3c6-11ea-8770-a46c9f7f9f85.png)

**Enviroment details**
OS: macOS High Sierra Version 10.13.6 (17G12034)

```
Output of kitty --debug-config (n/a -- won't run)
```

**Comment by kovidgoyal** [comment]
kitty requires 10.14 or newer

**Comment by Luflosi** [comment]
Which commit broke compatibility with 10.13?

**Comment by kovidgoyal** [comment]
there is no commit, 0.17 was not compatible with it either.

**Comment by Luflosi** [comment]
Then I'm wondering, why we're getting the bug reports only now.

**Comment by kovidgoyal** [comment]
On Mon, Jun 22, 2020 at 02:09:07AM -0700, Luflosi wrote:
> Then I'm wondering, why we're getting the bug reports only now.

No idea and High Sierra is EOL in a few months anyway. If 0.18 is really
newly incompatible with it, people can simply stick with 0.17.4,
although as I said, as far as I know 0.17 was also incompatible.
Basically when Apple inroduced the new codesigning requirements in
preparation for notarization, getting it working on anything before
mojave was too difficult, so I moved all my mac build machines to
mojave. And that was a while ago.

**Comment by Luflosi** [comment]
@jwiede Did kitty 0.17.4 work for you?

**Comment by laggardkernel** [comment]
@Luflosi I'm on 10.13.6, and kitty 0.17.4 works for me.

**Comment by laggardkernel** [comment]
BTW, run the kitty executable (`/Applications/kitty.app/Contents/MacOS/kitty`) succeeded.  I exported an app which wrapped a bash script to call `kitty` executable with Automator. And the wrapped kitty app runs with no problem.

Here's the script I used

```
#!/bin/bash
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
/Applications/kitty.app/Contents/MacOS/kitty >/dev/null 2>&1 &
```

**Comment by kovidgoyal** [comment]
Yeah I dont think kitty uses any APIs from Mojave itself, its just the app bundle/codesigning/notarization gunk that does.

**Comment by snurbol** [comment]
> BTW, run the kitty executable (`/Applications/kitty.app/Contents/MacOS/kitty`) succeeded. I exported an app which wrapped a bash script to call `kitty` executable with Automator. And the wrapped kitty app runs with no problem.
> 
> Here's the script I used
> 
> ```
> #!/bin/bash
> export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
> /Applications/kitty.app/Contents/MacOS/kitty >/dev/null 2>&1 &
> ```
> 
> Steps to create this wrapper app,
> 
>     * open Automator and choose type Application
> 
>     * search "Run Shell Script" and add it into the workflow
> 
>     * copy the bash script and paste it into the "Run Shell Script"
> 
>     * save the application and run it

I think better solution is build kitty from the source (https://sw.kovidgoyal.net/kitty/build.html).
Worked fine! No idea why official binary don't running, but self builded binary is ok.
I'm using MacOS version 10.13.6.
P.S. I can share 10.13.x compatible binary, but it's bad idea. Official instruction for building works.

**Comment by laggardkernel** [comment]
The author dropped support for older macOS version on purpose. I don't there's anything related to API incompatibility to the old version macOS, considering kitty is just a terminal app. I've seen many app keeps doing this, like SourceTree, Contexts, Lingon, etc.

BTW, wezterm once has a similar problem. But the author added back 10.13 support after some trying. wez/wezterm#128. There's must be a way to achieve it.


> I think better solution is build kitty from the source (https://sw.kovidgoyal.net/kitty/build.html).
> Worked fine! No idea why official binary don't running, but self builded binary is ok.
> I'm using MacOS version 10.13.6.
> P.S. I can share 10.13.x compatible binary, but it's bad idea. Official instruction for building works.

Glad my former response helped you. As far I know, `make` will do a dynamic build. But for a static build, it's not that easy. [Building kitty.app on macOS from source](https://sw.kovidgoyal.net/kitty/build.html#building-kitty-app-on-macos-from-source) That's the reason I choose to use a wrapper app.
