### ISSUE TITLE
Prompt color messed up

### ISSUE THREAD

**Issue by michalens** [kovidgoyal/kitty#2784]
After upgrading to 0.18 colors of the prompt changed.

**Screenshots**
Here are the colors after updgrading.
![Screen Shot 2020-06-22 at 14 41 16](https://user-images.githubusercontent.com/42828375/85283695-76d53600-b496-11ea-875f-fdbcc089c216.png)

This is the expected colors. (screenshot from iTerm. Was same on kitty before upgrading
![Screen Shot 2020-06-22 at 14 41 24](https://user-images.githubusercontent.com/42828375/85283763-910f1400-b496-11ea-8bed-a852a8897924.png)

**Enviroment details**
MacOS Mojave 10.14.6

**Comment by kovidgoyal** [comment]
Nothing has changed in 0.18 regarding color handling. Does downgrading fix it?

**Comment by michalens** [comment]
works after restart
