### ISSUE TITLE
Atfer-image in neovim with file that contains emoji

### ISSUE THREAD

**Issue by nacknime-official** [kovidgoyal/kitty#2786]
**Describe the bug**
After-image in neovim that contains emoji

**To Reproduce**
1. `run nvim -u NORC` with a file that contains emojis
2. create new tab by `:tabnew <file>`
3. jump between these tabs a few times
4. See some symbols from the another tab

**Expected behavior**
don't show these symbols

**Screenshots**
See the video below
![afterimage_kitty](https://user-images.githubusercontent.com/34421603/85325037-9b9bce80-b4d3-11ea-9a6e-5ad157899f74.gif)

**Enviroment details**
OS: `Archlinux`
WM: `Sway (wayland)`
CPU: `Intel Core i7-8550U`
GPU: `Intel UHD Graphics 620 (rev 07)`
Driver: `mesa 20.1.1-1`
Kitty version: `kitty 0.18.0 created by Kovid Goyal`

**Comment by kovidgoyal** [comment]
I dont see how this can be a bug in kitty. Clearing the screen, etc are
operations performed by the client program not the terminal emulator.
Most likely nvim is assuming the wrong wcwidth() for that emoji. kitty
uses the wcwidth() prescribed by the current unicode standard. 

You can check wat width nvim assumes it to be by trying to edit
it/moving the cursor near it etc.

**Comment by nacknime-official** [comment]
> I dont see how this can be a bug in kitty. Clearing the screen, etc are
> operations performed by the client program not the terminal emulator.
> Most likely nvim is assuming the wrong wcwidth() for that emoji. kitty
> uses the wcwidth() prescribed by the current unicode standard.
> 
> You can check wat width nvim assumes it to be by trying to edit
> it/moving the cursor near it etc.

The width of the emoji is 2, but this is the same in `vim` and in `vim` there's no the bug.
Also I see that only in `Kitty`, in `st`, `Konsole` and `termite` there's no the bug so I thought that is the bug of the `kitty` 🤷‍♂️

**Comment by kovidgoyal** [comment]
On Mon, Jun 22, 2020 at 11:44:38PM -0700, nacknime wrote:
> > I dont see how this can be a bug in kitty. Clearing the screen, etc are
> > operations performed by the client program not the terminal emulator.
> > Most likely nvim is assuming the wrong wcwidth() for that emoji. kitty
> > uses the wcwidth() prescribed by the current unicode standard.
> > 
> > You can check wat width nvim assumes it to be by trying to edit
> > it/moving the cursor near it etc.
> 
> The width of the emoji is 2, but this is the same in `vim` and in `vim` there's no the bug.

Yes, vim and neovim have different wcwidth implementations.

> Also I see that only in `Kitty`, in `st`, `Konsole` and `termite` there's no the bug so I thought that is the bug of the `kitty` 🤷‍♂️

many terminals dont use standards based values for wcwidth() instead
delegating to the system C library which is woefully out of date.

**Comment by trygveaa** [comment]
> The width of the emoji is 2, but this is the same in vim and in vim there's no the bug.
Also I see that only in Kitty, in st, Konsole and termite there's no the bug so I thought that is the bug of the kitty

As far as I can see, there are bugs in all of these combinations, just different bugs.

kitty+nvim: The bug you mentioned, plus nvim thinks the cursor is in another position than it is (try moving to the last character on the line, or press ga on a character after the emoji).
kitty+vim, termite+vim, termite+nvim: The character immediately after the emoji is drawn underneath the emoji, so it's not visible.
konsole+vim, konsole+nvim: The emoji is drawn incorrectly, with a width of 1 instead of 2.
st: Crashes for me when it tries to display the emoji, so was not able to properly test it.

**Comment by nacknime-official** [comment]
Okay, I understood, thank you all. I'll create an issue in neovim's github.
