### ISSUE TITLE
Alert message when closing running terminal

### ISSUE THREAD

**Issue by adrienluitot** [kovidgoyal/kitty#2788]
**Is your feature request related to a problem? Please describe.**
If a program is running in the terminal and we close it using the window cross, the terminal will close instantly and stop the program. This could leads to big problems, for example if we do it during a package update or something like this.  

**Describe the solution you'd like**
If a program is running in the terminal and the user click on the window cross (close button) it could be nice to display a alert message (like a popup) to warn the user that a program is running in the terminal and ask if he really wants to close it.

**Comment by trygveaa** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close

**Comment by adrienluitot** [comment]
The problem is that it shows a message event if nothing (no command) is running in the terminal.

**Comment by kovidgoyal** [comment]
There is never no command running in a terminal, at the very least there
will be a shell.

**Comment by adrienluitot** [comment]
I know but if there is just a shell it can close without any problem. But the problem is when there is a "real" command.
I don't know if it's hard to detect but I know that, for example, the deepin terminal can handle it, and shows a popup if something else than just the shell is runnning.

**Comment by kovidgoyal** [comment]
I dont see why there should be "no problem" is a shell is the foreground process? There could be background processes (jobs), you could have valuable information stored in the scrollback buffer, etc etc.

**Comment by adrienluitot** [comment]
It can just be a little protection. If we can't check suspended processes, we can at least check for foreground programs. The idea is just to not always show a warning message when it's not necessary, and show a message when a foreground program is running.
Maybe you can check the gnome or the deepin terminals, they both have a warning message when you have a foreground process.

**Comment by kovidgoyal** [comment]
On Wed, Jun 24, 2020 at 03:44:09AM -0700, Adrien Luitot wrote:
> It can just be a little protection. If we can't check suspended processes, we can at least check for foreground programs. The idea is just to not always show a warning message when it's not necessary, and show a message when a foreground program is running.
> Maybe you can check the gnome or the deepin terminals, they both have a warning message when you have a foreground process.

Sorry, no.

1) it is impossible to know if the foreground process is a shell or not
robustly. Am guessing your other terminals just check if the process
name ends in sh and are not ssh. And that doesn't even consider the
shell-in-shell case or the shell in SSH case.

2) It is impossible to know if there are valuable background processes
in the process group. One could of course say that if there is more than
a single process in the process group, we dont auto-close it. But this
means that if you have a man page open or a file in less or similar
auto-close will not work. Or running a shell in ssh will not auto-close.

3) It is impossible to know if the scrollback contains valuable
information.

I am not willing to add half-baked features like this, that cannot, even
in principle work robustly.

**Comment by adrienluitot** [comment]
1) I think you can, I didn't make a lot of test but I think that there is always the terminal, then the shell and then sub processes (See first image below). So you could check for all processes under kitty, check if they have sub processes, in the image below we can see that the first tab (first /bin/zsh) doesn't not contain processes, whereas the second one has a htop process (this technique even work with suspended processes).
![image](https://user-images.githubusercontent.com/23219818/85563882-508dd280-b61d-11ea-9787-0c4a4c273466.png)
*(you can easily get subprocesses through `pgrep`)*

2) I think it's normal to not auto close a less or a ssh process.

3) What do you mean by scrollback ?

**Comment by kovidgoyal** [comment]
On Wed, Jun 24, 2020 at 06:23:27AM -0700, Adrien Luitot wrote:
> 1) I think you can, I didn't make a lot of test but I think that there is always the terminal, then the shell and then sub processes (See first image below). So you could check for all processes under kitty, check if they have sub processes, in the image below we can see that the first tab (first /bin/zsh) doesn't not contain processes, whereas the second one has a htop process (this technique even work with suspended processes).
> ![image](https://user-images.githubusercontent.com/23219818/85563882-508dd280-b61d-11ea-9787-0c4a4c273466.png)
> *(you can easily get subprocesses through `pgrep`)*

kitty python

not a shell. Can have subprocesses. 

kitty ssh

not a shell can have subprocesses

kitty zsh
zsh
bash

all are shells but the foreground sell has no subprocesses.

> 
> 2) I think it's normal to not auto close a less or a ssh process.

why? they are just as much a candidate for safe closure as a shell.

> 
> 3) What do you mean by scrollback ?

Press ctrl+shit+pgup

**Comment by adrienluitot** [comment]
I'm not sure I've understand the first part.

> why? they are just as much a candidate for safe closure as a shell.
I think it's what I said, they need also need an alert message if they are running.

> Press ctrl+shit+pgup
Oh okay, but we cannot check everything, I mean it's also normal to not cover everything.

**Comment by kovidgoyal** [comment]
On Wed, Jun 24, 2020 at 09:56:53AM -0700, Adrien Luitot wrote:
> I'm not sure I've understand the first part.
> 
> > why? they are just as much a candidate for safe closure as a shell.
> I think it's what I said, they need also need an alert message if they are running.

No an ssh connection to a server sitting at a shell is perfectly safe to
close. As is a pager display a file. There is nothing special about
running a shell by itself that makes it safe to close.

> 
> > Press ctrl+shit+pgup
> Oh okay, but we cannot check everything, I mean it's also normal to not cover everything.

That's the whole point you are basically asking for the arbitrary
feature, disregard windows that happen to be running programs with
certain names when checking what is safe to close.

**Comment by adrienluitot** [comment]
Well after-all you do what you want ^^ But I think that if we can cover at least a part of this it could be better than nothing. I think if developers on a project like gnome terminal did it, it's not for nothing, even if it's not perfect. I find it already super nice.
