### ISSUE TITLE
openbox ToggleMaximize vertical -> odd window positioning

### ISSUE THREAD

**Issue by wez** [kovidgoyal/kitty#279]
I have a hotkey defined in `~/.config/openbox/rc.xml`:

```
    <keybind key="W-m">
      <action name="ToggleMaximize">
        <direction>vertical</direction>
      </action>
    </keybind>
```

when pressed, the window is resized to fill the vertical space.  I have a panel at the top of my screen so this should result in:

```
[panel]
[kitty title bar]
[kitty client area]
```

However, kitty seems to interact poorly and what happens is that the kitty window gets positioned with the same height as it should above `(screen height - (decoration + client))` but the `y` position is at the origin; the kitty title bar is behind the panel and the bottom of the screen leaves a title bar sized gap at the bottom.

In case it is useful, here's the `xprop` and `xwininfo` output for `xterm` after performing this maximize operation:

```
 $ xprop
_NET_WM_ICON_GEOMETRY(CARDINAL) = 610, 0, 150, 26
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _OB_WM_ACTION_UNDECORATE
_KDE_NET_WM_FRAME_STRUT(CARDINAL) = 1, 1, 26, 5
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 26, 5
_NET_WM_STATE(ATOM) = 
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "xterm"
_OB_APP_GROUP_CLASS(UTF8_STRING) = "XTerm"
_OB_APP_GROUP_NAME(UTF8_STRING) = "xterm"
_OB_APP_CLASS(UTF8_STRING) = "XTerm"
_OB_APP_NAME(UTF8_STRING) = "xterm"
_OB_APP_ROLE(UTF8_STRING) = 
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "xprop -- wez@wez-tp:~"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "xprop -- wez@wez-tp:~"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
_NET_WM_PID(CARDINAL) = 32060
WM_CLIENT_LEADER(WINDOW): window id # 0x4400024
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLASS(STRING) = "xterm", "XTerm"
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
                bitmap id # to use for icon: 0x4400035
                bitmap id # of mask for icon: 0x4400037
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified size: 644 by 388
                program specified minimum size: 12 by 20
                program specified resize increment: 8 by 16
                program specified base size: 4 by 4
                window gravity: NorthWest
WM_CLIENT_MACHINE(STRING) = "wez-tp"
WM_COMMAND(STRING) = { "xterm" }
WM_ICON_NAME(STRING) = "xprop -- wez@wez-tp:~"
WM_NAME(STRING) = "xprop -- wez@wez-tp:~"

$ xwininfo
  Absolute upper-left X:  1275
  Absolute upper-left Y:  52
  Relative upper-left X:  1
  Relative upper-left Y:  26
  Width: 644
  Height: 1012
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1275+52  -1+52  -1-16  +1275-16
  -geometry 80x63-0-11

```

and here's the `xprop` and `xwininfo` output for `kitty`, with the icon rendition elided for brevity:

```
 $ xprop
_NET_WM_ICON_GEOMETRY(CARDINAL) = 458, 0, 150, 26
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _OB_WM_ACTION_UNDECORATE
_KDE_NET_WM_FRAME_STRUT(CARDINAL) = 1, 1, 26, 5
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 26, 5
_NET_WM_STATE(ATOM) = 
_NET_WM_ICON(CARDINAL) =        Icon (48 x 48):
        <snipped>
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "kitty"
_OB_APP_GROUP_CLASS(UTF8_STRING) = 
_OB_APP_GROUP_NAME(UTF8_STRING) = 
_OB_APP_CLASS(UTF8_STRING) = "kitty"
_OB_APP_NAME(UTF8_STRING) = "kitty"
_OB_APP_ROLE(UTF8_STRING) = 
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "vim ~/.config/openbox/rc.xml -- wez@wez-tp:~"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "vim ~/.config/openbox/rc.xml -- wez@wez-tp:~"
_NET_WM_ICON_NAME(UTF8_STRING) = "vim ~/.config/openbox/rc.xml -- wez@wez-tp:~"
_NET_WM_NAME(UTF8_STRING) = "vim ~/.config/openbox/rc.xml -- wez@wez-tp:~"
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "wez-tp"
WM_ICON_NAME(STRING) = "vim ~/.config/openbox/rc.xml -- wez@wez-tp:~"
WM_NAME(STRING) = "vim ~/.config/openbox/rc.xml -- wez@wez-tp:~"
XdndAware(ATOM) = BITMAP
WM_CLASS(STRING) = "kitty", "kitty"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                window gravity: Static
WM_HINTS(WM_HINTS):
                Initial state is Normal State.
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 31743
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING

$ xwininfo

  Absolute upper-left X:  1
  Absolute upper-left Y:  26
  Relative upper-left X:  1
  Relative upper-left Y:  26
  Width: 960
  Height: 1023
  Depth: 24
  Visual: 0xee
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x4000015 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1+26  -959+26  -959-31  +1-31
  -geometry 960x1023+1+26

```

**Comment by kovidgoyal** [comment]
Window positioning is not in kitty's control, kitty contains no code to manipulate window positions. Window positioning and window decorations for that matter, are done by the window manager. This looks to me like a bug in the window manager.

But if I am mistaken, patches are welcome. You will find all the window related code in a single C file, glfw.c the relevant callback is framebuffer_size_callback. All that callback does is adjust the OpenGL viewport to match the new window size.

**Comment by cdown** [comment]
This is probably due to XSizeHints: https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html

Terminals are kind of weird in that they have a very low-granularity sizing as each unit of sizing is one font glyph width, or font glyph height. My guess is that your window manager respects them and this results in this weird behaviour.

So there are two possible solutions:

1. Make it possible to turn off resize hints in kitty
2. Have your window manager ignore resize hints from kitty

Here's a patch someone seems to have written for #2: http://twily.info/stuff/openbox-size-hint-patch

**Comment by kovidgoyal** [comment]
As far as I know, kitty doesn't actually have a resize granularity. It will simply add/remove padding around the actual cell area when you resize windows.

**Comment by kovidgoyal** [comment]
Indeed, if you look at glfw/x11_window.c you will see that the width and height inc values are never set.

**Comment by cdown** [comment]
@kovidgoyal I'm not a kitty user, so my statement is without any testing, but the entire point of resize hints is that this is *before* the user does any resizing, not as an addition to that resizing.

GLFW, for example, does set resize hints as part of `updateNormalHints`. My guess is that a combination of this and `_glfwPlatformSetWindowPos` results in this strange behaviour.

**Comment by kovidgoyal** [comment]
Yes, it sets hints, but not the incremental size hints, which is (as far as I know) what could cause resizing granularity to be greater than 1px. i.e. `updateNormalHints` *does not* set either width_inc or height_inc

Grepping for height_inc in the entire source code yields no matches

Or maybe you mean something else?

**Comment by wez** [comment]
@cdown's intuition was correct; this issue is caused by the StaticGravity hint that is set by glfw.  You can see that this is one of the differences between the xterm hints and the kitty hints in my paste above.

According to https://tronche.com/gui/x/xlib/window/attributes/gravity.html:

> A bit-gravity of StaticGravity indicates that the contents or origin should not move relative to the origin of the root window. If the change in size of the window is coupled with a change in position (x, y), then for bit-gravity the change in position of each pixel is (-x, -y), and for win-gravity the change in position of a child when its parent is so resized is (-x, -y). Note that StaticGravity still only takes effect when the width or height of the window is changed, not when the window is moved.

Here's the trivial diff to resolve the problem in glfw, but I'm not sure how you might change this just at the kitty layer:

```
 $ git diff
diff --git a/glfw/x11_window.c b/glfw/x11_window.c
index 2b151c5..0f384e1 100644
--- a/glfw/x11_window.c
+++ b/glfw/x11_window.c
@@ -315,7 +315,7 @@ static void updateNormalHints(_GLFWwindow* window, int width, int height)
     }
 
     hints->flags |= PWinGravity;
-    hints->win_gravity = StaticGravity;
+    hints->win_gravity = NorthWestGravity;
 
     XSetWMNormalHints(_glfw.x11.display, window->x11.handle, hints);
     XFree(hints);
```

**Comment by kovidgoyal** [comment]
You should open a bug report for glfw, from git blame, the change to using staticgravity was to fix this: https://github.com/glfw/glfw/issues/800 so I dont think simply patching it to use northwestgravity is appropriate.
