### ISSUE TITLE
problem with vim folded lines + some unicode

### ISSUE THREAD

**Issue by teto** [kovidgoyal/kitty#2791]
**Describe the bug**
Folded line with unicode don't display well on kitty but termite displays them fine. The following is a copy/paste from https://github.com/vim/vim/issues/6311.

**To Reproduce**
with mbyte.txt:
```
å 语 x̨̣̘̫̲͚͎̎͂̀̂͛͛̾͢͟ العَرَبِيَّة
möre text

dadad
```
run  `vim -u NONE mbyte.txt` then `zfj` to create a fold containing the first and second line.
Instead of having the `fold` fillchar filling the rest of the line, kitty shows some gibberish. Termite/sublime-text show proper arabic (I think) characters.
Termite and neovim (vim too I think) use libc for wcwidth of characters while kitty use another source of truth so that may play a role but I would expect the glyph to cover eachother (not sure that's one should expect) but here the output is ugly.

**Expected behavior**
I would like kitty to show the same output as termite:
![2020-06-24-145154_954x47_scrot](https://user-images.githubusercontent.com/886074/85559740-4920f600-b62a-11ea-8ea6-1a8e6fbd3ea0.png)
instead of (kitty 0.18):
![85232779-1694b480-b402-11ea-8870-9bf1da53e6d3](https://user-images.githubusercontent.com/886074/85560459-f562dc80-b62a-11ea-8ef0-7c522c358c88.png)

**Environment details**
OS: nixos-unstable

```
Output of kitty --debug-config

kitty 0.18.0 created by Kovid Goyal
Linux jedha 5.6.16 #1-NixOS SMP Wed Jun 3 06:23:38 UTC 2020 x86_64
<<< Welcome to NixOS 20.09.git.20c39814832M (\m) - \l >>>

Run 'nixos-help' for the NixOS manual.
Loaded config files: /home/teto/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=0, green=43, blue=54)
color0                Color(red=7, green=54, blue=66)
color1                Color(red=220, green=50, blue=47)
color10               Color(red=88, green=110, blue=117)
color11               Color(red=101, green=123, blue=131)
color12               Color(red=131, green=148, blue=150)
color13               Color(red=108, green=113, blue=196)
color14               Color(red=147, green=161, blue=161)
color15               Color(red=253, green=246, blue=227)
color2                Color(red=133, green=153, blue=0)
color3                Color(red=181, green=137, blue=0)
color4                Color(red=38, green=139, blue=210)
color5                Color(red=211, green=54, blue=130)
color6                Color(red=42, green=161, blue=152)
color7                Color(red=238, green=232, blue=213)
color8                Color(red=0, green=43, blue=54)
color9                Color(red=203, green=75, blue=22)
cursor_blink_interval 0.5
enable_audio_bell     False
font_family           Inconsolata For Powerline 11
font_size             13.0
open_url_with         ['default', 'qutebrowser']
scrollback_lines      200000
scrollback_pager      ['nvim', '-R', '-c', ':set ft=terminal']
```

**Additional context**
I could reproduce it with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
Works fine for me other than that the arabic glyphs are not rendered but that has nothing to do with multibyte or folding. In general, given that kitty is a fixed character cell matrix like a hardware terminal, it is never going to render arabic well. This is with vim 8.2.814

![Screenshot_20200624_192812](https://user-images.githubusercontent.com/1308621/85570475-01fa2b80-b651-11ea-941e-6f4fd6c42d1b.png)
