### ISSUE TITLE
Kitty 0.18.1 fails to start with `ModuleNotFoundError: No module named 'encodings'`

### ISSUE THREAD

**Issue by varac** [kovidgoyal/kitty#2792]
**Describe the bug**

Kitty 0.18.1 fails to start with `ModuleNotFoundError: No module named 'encodings'`

**To Reproduce**
1. Download kitty 0.18.1 from github release page, unzip the archive
2. my kitty to a location in your PATH
3. run `kitty --config NONE` from cli

**Expected behavior**

kitty should start without errors

**Screenshots**

**Environment details**
OS: Ubuntu 20.04 (wayland), sway version 1.4-f681d529 (Jan 22 2020, branch 'heads/1.4')

**Additional context**

```
❯ kitty --config NONE
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'kitty'
  isolated = 1
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = '/home/varac/bin/kitty'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = '/home/varac/bin/kitty'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    '/home/varac/bin/../lib/python3.8',
    '/home/varac/bin/../lib/python3.8/lib-dynload',
    '/home/varac/bin/../lib/python3.8/site-packages',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f96c10a0740 (most recent call first):
<no Python frame>
```

**Comment by kovidgoyal** [comment]
That's not how you install kitty. You cannot move the binary, you
symlink to it instead. Or use the installer script. https://sw.kovidgoyal.net/kitty/binary.html
