### ISSUE TITLE
Improve "kitty @ ls" output

### ISSUE THREAD

**Issue by ahlinc** [kovidgoyal/kitty#2794]
**Is your feature request related to a problem? Please describe.**
Current implementation of `kitty @ ls` command just outputs a json list with many `env` keys which all have the same content because it's related to the first command in a window and more over as I suppose it's startup env that the command inherits from kitty process. So this *env* keys contains non actual command environments what seems not very useful.

If to look on the output without env keys:
```
kitty @ls | jq 'delpaths([paths(..)|select(.[-1]=="env")])'
```
It looks much shorter and allows easily to find need info visually.

**Describe the solution you'd like**
I don't know, a simplest solution is to drop this *env* keys or at least drop them if stdout is a tty.

**Describe alternatives you've considered**
A better solution for me has several items:
1. Add a `<-v|--verbose>` option and show *env* keys only when the option provided.
2. Show actual environment instead of startup version of it.
3. Also show environment for all running foreground commands.
4. As the json not the best human friendly output it would be nice to have an option that will output a brief info in some colorful multi line format with padding to mark hierarchy. This would be helpful to to make quick decision for what to look in more verbose json output.

**Comment by ahlinc** [comment]
@kovidgoyal I would be glad to know your opinion on the points above.

**Comment by kovidgoyal** [comment]
No, the environment is the live process environment, not the starting
environment. As such it can be different for different processes. The
JSON output will always be complete and verbose. However, I am open to
adding an option to produce human readable output, PRs are welcome,
relevant code is in rc/ls.py
