### ISSUE TITLE
Selection on Custom Kitten

### ISSUE THREAD

**Issue by d1ee** [kovidgoyal/kitty#2796]
Hi,

is there a way to get the current selection in a custom kitten? I searched the existing kittens, but it didn't help me further. Thanks for advices.

Best
Dongha

**Comment by trygveaa** [comment]
You can also get it with `w.text_for_selection()` where `w` is the window which you can see how to get in the first example on https://sw.kovidgoyal.net/kitty/kittens/custom.html.

**Comment by d1ee** [comment]
@trygveaa Thanks a lot, that was exactly what I was looking for. 😆
