### ISSUE TITLE
Find in current tab (CMD+F)

### ISSUE THREAD

**Issue by kakulukia** [kovidgoyal/kitty#2797]
**Problem**
I'm always frustrated when i cant find stuff

**Solution**
Please make CMD+F work in kitty.

**Comment by SolitudeSF** [comment]
`ctrl+shift+h` opens scrollback in your pager. you can search there.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/#scrollback

**Comment by kakulukia** [comment]
Okay, let me be more precise: id also like to have stuff highlighted as i continue doing other stuff for instance tailing a log file while specifically discarding everything else with e.g. grep .. how can that be done in kitty @kovidgoyal ?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/marks.html

**Comment by kakulukia** [comment]
i just tried that .. interesting .. but that opens up the next question: how do i do that on the fly? I'd have to do config changes and restart kitty .. this is way to complicated for a simple search.

But as the functionality kinda is existing, why not have CMD+F open a dialog to create a regex marker on the fly?
This would so much add to usability!

**Comment by SolitudeSF** [comment]
read literally the next paragraph.

**Comment by trygveaa** [comment]
You can try https://github.com/trygveaa/kitty-kitten-search. It's not perfect, but it's more convenient to use than the default interface for creating markers imo.

**Comment by kakulukia** [comment]
shame on me for not reading the next paragraph! ☺️

The whole point, tho: its not intuitive and i have to read and remember stuff that i take for granted in nearly all other apps and ALL functionality is actually there and working - awesome! 
Its just not easy nor obvious how to use it. :(

https://sw.kovidgoyal.net/kitty/search.html?q=find&check_keywords=yes&area=default
This is not listing anything helpful for some new user of kitty like me.

I understand this app if far from done with its 0.18 version number, but closing feature requests as quickly as this one also aint helping to polish it. I still see myself sticking with iTerm even though kitty is much faster .. which is a shame .. but spending my brain power on remember weird marker syntax is stuff i try to avoid. Tool shall help instead of making things more complicated, dont you think?
Im fine with: "its not on top of the todo list, maybe later" tho

**Comment by kovidgoyal** [comment]
What on earth? You want to search by far the most convenient way to do
it is to a pager. It present the same interface for searching as all
other command line toold, man pages, etc.

You want to search live, use marks. It requires remembering to prefix
your search expression by text 1 -- if that is too much cognitive load,
by all means stick with iTerm.

**Comment by kakulukia** [comment]
Now thats a very aggressive way of enforcing defaults.
