### ISSUE TITLE
[macos] closing an os_window does not focus remaining os_window

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#280]
First, this is probably a macOS specific error due to how cocoa window management works.
I completely understand if this is not something you want to bother with.

The issue:

After starting kitty, if I launch another os_window, and then close that os_window, it does not automatically focus the remaining window that is open (on the same workspace). The shortcut `cmd+´` to focus a different window of the application does not work either, although the application itself stays activated.

Because the application itself stays activated, I can't simply do a `cmd+tab` to get it back in focus, and have to click it using the mouse (or just hover the mouse above the window, as I have focus-follows-mouse functionality).

I will try to investigate this when I have time.

**Comment by kovidgoyal** [comment]
You probably just need to explicitly focus a window in destroy_os_window. Keep track of the last couple of window ids to receive focus in the focus callback so you know which window to focus if there are more than two.

**Comment by koekeishiya** [comment]
Confirmed working, however it doesn't track focus far enough.

If I launch kitty, open a window, open another window.
When closing the first window, I get focus on the next one automatically, but if i also instantly close that window, it does not focus the last one.
