### ISSUE TITLE
There was an error creating your Issue: title can't be blank. Now it isn’t. And now maybe a bit looooonger than needed.                            Also, some more words here.

### ISSUE THREAD

**Issue by zsugabubus** [kovidgoyal/kitty#2803]
**F**irst of all, thanks for the q**u**i**ck** response.

> What a farrago of nonsense Go read what I wrote again. Actually, better yet, dont. I dont have time to waste explaining elementary things to you.

A DECRC cannot be safely used unless the same program previously issued a DECSC. No matter whether it stacks or not. Or you angry or not. Or you lock the [thread](https://github.com/kovidgoyal/kitty/issues/1264) as spam or not.

So what does it solve? Apart from that it’s non-standard and breaks programs. 

Not that hard to reason about, so here is one more little example, hope it helps understand (with your stacking behavior):

> That seems very wrong to me. It would mean that if application A did a DECSC followed by a DECRC and quit. Then the meaning of DECRC for all subsequent applications is now changed, as it will restore cursor state to whatever application A saved it as.

“application A”: DECSC then crashes (no matching DECRC).
“all subsequent applications is now changed”: they expect DECRC will take them to (0, 0), but it will not be true at the first case. So we can concl**u**de that it’s just as bad as the non-stacking variant. Got it? :)

**Comment by kovidgoyal** [comment]
Go read what I wrote again, this time maybe after a few years of remedial english and remedial logic.
