### ISSUE TITLE
Wrong versioning on Mac OS x

### ISSUE THREAD

**Issue by marc-brouard** [kovidgoyal/kitty#2804]
Just updated to the latest version 0.18.1 using Homebrew on Mac OS X 10.13.6

Kitty will no longer run as it states it requires 10.14

Looking at the Homebrew Cask Formula it states that Mac OS X 10.12 or greater is required
https://formulae.brew.sh/cask/kitty

Could you confirm which is correct? I am guessing that 10.14 required is correct but the Homebrew has not been updated to reflect this

**Comment by kovidgoyal** [comment]
kitty itself will work fine on 10.12 but since apple introduced
code-signing, to get it to work I had to move my macOS build VMs to
10.14 so officially kitty is supported only on 10.14 and newer.  You
could probably run it by running the kitty executable directly instead
of the bundle.

**Comment by marc-brouard** [comment]
Thank you for taking the time to reply. 

Kitty is a great program and does everything I want it to. Currently can not update my current machine as in the middle of a large project. It is a shame that you are impacted by a situation outside your control. Thank you for producing a great product
