### ISSUE TITLE
Doesn't open on macOS Big Sur (Version: 11.0 Beta (20A4299v))

### ISSUE THREAD

**Issue by jdbrewer** [kovidgoyal/kitty#2805]
**Describe the bug**
Clicking on the application icon in the dock or launching from /Applications or from Spotlight does not open the application.

**To Reproduce**
1. Click on the dock icon, launch from spotlight, or open from /Applications.
2. Application fails to open.

**Expected behavior**
Application opens.

**Screenshots**
Terminal Command: 
```open -a Kitty```
Produces:
```LSOpenURLsWithRole() failed for the application /Applications/kitty.app with error 1.```

**Environment details**
OS:  macOS Big Sur Version: 11.0 Beta (20A4299v)

**Additional context**
Kitty can still be launched by navigating to /Applications, right clicking on kitty.app, selecting "Show Package Contents", navigating to /Contents/MacOS/, and double clicking the Unix Executable File "kitty".

**Comment by kovidgoyal** [comment]
I'm afraid I dont have the resources to support un-released versions of
macOS. Apple manages to break working applications with pretty much
every release of their OS. Hopefully they will fix whatever they have
broken before the final release. Since it seems like its something in
the bundle wrapper they dont like, not the actual program, its likely a
trivial one line fix. If they dont manage to fix it, I will take a look
as soon as the final version is released. In the meantime, patches are
most welcome.

**Comment by kchibisov** [comment]
I'll just cross link it here, since some kind of solution was posted on our tracker. https://github.com/alacritty/alacritty/issues/3880 . It's likely a macOS fault to some point, but it seems like there're some solutions already. I'm not saying that you should do anything, just FYI.

**Comment by kovidgoyal** [comment]
Thanks, more information is always helpful. However if I understand correctly the solution was setting MACOS_DEPLOYMENT_TARGET=10.16 and rebuilding. That's not a workable solution for pre-built binaries since it will break running on anything other than Big Sur. So really need to wait for Apple.

**Comment by alexanderniebuhr** [comment]
@kovidgoyal : I doubt it's just a mistake in the bundle. Some of the used API are deprecated now. For example NSUserNotification

**Comment by kovidgoyal** [comment]
no, kitty doesnt use any currently deprecated apis (apart from opengl) and apis newly deprecated for big sur, will be deprecated not removed. not to mention that the OP is able to run kitty fine, just not via the bundle wrapper.

**Comment by Luflosi** [comment]
I installed the beta version of macOS Big Sur in a VM but kitty fails to launch, most likely because I don't really have a GPU in the VM.
I'm getting an error that looks something like this:
```
NSGL: Failed to find a suitable pixel format
NSGL: Failed to find a suitable pixel format
Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

@kovidgoyal I can confirm what @alexanderniebuhr said about the deprecated APIs, I had to remove `-Werror` as a workaround for now.

**Comment by kovidgoyal** [comment]
On Wed, Jul 22, 2020 at 08:21:48PM +0000, Luflosi wrote:
> I installed the beta version of macOS Big Sur in a VM but kitty fails to launch, most likely because I don't really have a GPU in the VM.
> I'm getting an error that looks something like this:
> ```
> NSGL: Failed to find a suitable pixel format
> NSGL: Failed to find a suitable pixel format
> Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
> ```
> 
> @kovidgoyal I can confirm what @alexanderniebuhr said about the deprecated APIs, I had to remove `-Werror` as a workaround for now.

I'm sure there are APIs that are *newly* deprecated in Big Sur, but
these cannot prevent kitty from running. Deprecation just means the API
will be removed/stop working in the *future*. Other than OpenGL there are
no *currently* deprecated APIs.

And if you can post a log of the build with the deprecated APIs I will
replace them.

**Comment by alexanderniebuhr** [comment]
@kovidgoyal I understand what you mean. And as you said before, the NSUserNotification APIs are newly marked as deprecated with this release.
However, I always try to replace them as soon as they are marked, even if they might work for two or so future releases.

They might not prevent kitty from running, but they are very annoying while building. Also, I really would like to help out with any PR, unfortunately, I am just familiar with programs and apps using Xcode. As I see it, you are using python with Objective-C without Xcode, correct?

**Comment by Luflosi** [comment]
Yes, kitty is built without XCode. You could take a look at my PR above and see if you can figure out why it doesn't work.
