### ISSUE TITLE
Community?

### ISSUE THREAD

**Issue by cuppajoeman** [kovidgoyal/kitty#2808]
Hello, this could be the total wrong place to ask this, but I'm not sure where to ask questions to the community for kitty.

For example I wanted to know if anyone had implemented vim-like keybindings for movement about kitty (that way I don't have to re-implement if someone's done the work) but I realized I wasn't sure where to ask questions like this about kitty?

Usually when I run into situations like this I join an IRC channel or something of that sort to ask questions. Do we have an IRC channel? I didn't see it on the documentation...

Thanks!

**Comment by trygveaa** [comment]
You may be interested in this: https://github.com/knubie/vim-kitty-navigator

**Comment by kovidgoyal** [comment]
Ask here, eventually once github discussion comes out of beta that will
be the canonical place for questions/discussions.
