### ISSUE TITLE
Line-endings are consumed by kitty when copied to clipboard buffer

### ISSUE THREAD

**Issue by basiliscos** [kovidgoyal/kitty#2809]
**Describe the bug**

Line-endings are consumed by kitty when copied to buffer

**To Reproduce**
It is not 100% reproducible, but I usually do `git diff` on console, and then copy output somewhere... the larger is output, the greater is chance of the bug

**Screenshots**

https://i.imgur.com/z7aRa6V.png

https://i.imgur.com/76vjZQa.png

**Environment details**

void linux, awesome wm

uname -a
Linux localhost 5.4.49_1 #1 SMP PREEMPT Fri Jun 26 14:34:01 UTC 2020 x86_64 GNU/Linux

```
kitty --debug-configkitty 0.18.1 created by Kovid GoyalLinux localhost 5.4.49_1 #1 SMP PREEMPT Fri Jun 26 14:34:01 UTC 2020 x86_64
Void \r (\n) (\l)
Loaded config files: /home/b/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
scrollback_lines 20000
tab_bar_edge     1
term             xterm```

**Additional context**

the same behaviour I've seen on v0.17.x

**Comment by kovidgoyal** [comment]
I need some way to reproduce, you can run kitty with --dump-bytes,
reproduce the issue minimally (that means in a new kitty instance)
and attach the dump.

**Comment by basiliscos** [comment]
ok, I'll run with `--dump-bytes` by default, and as soon as I'll be able to catch it during my work, I'll attach it here.

**Comment by kovidgoyal** [comment]
Be aware the the dump will contain everything from the session, so dont attach it if your session has anything sensitive in it. It is best to repro the issue with as few steps as possible.

**Comment by basiliscos** [comment]
thank you for note. 

Please, download an sample from 

https://send.firefox.com/download/0275739d43dc63ff/#aDt8n_5doyq3HckwQ1DcWQ 

(this is one-time link, it will disappear after downloading). Let me know whether it is OK for your. 

(I noted buggy behavior on `git diff --relative` )

**Comment by kovidgoyal** [comment]
I downloaded it will take a look when I have a moment

**Comment by kovidgoyal** [comment]
For the record, here is a minimal reproducer from your dump (can be used with
```sh
kitty sh -c "kitty --replay-commands repro.txt; read"
```
[repro.txt](https://github.com/kovidgoyal/kitty/files/4844668/repro.txt)

**Comment by basiliscos** [comment]
yep, seems so.
