### ISSUE TITLE
Support text-input-method-unstable-v3 for wayland

### ISSUE THREAD

**Issue by LaserEyess** [kovidgoyal/kitty#2814]
**Is your feature request related to a problem? Please describe.**
Currently, kitty only supports a subset of IMEs (ibus only I think?) on wayland and Linux in general. It seems like great effort was expended on porting ibus to GLFW and [you're unwilling to support other IMEs via this method](https://github.com/kovidgoyal/kitty/issues/469#issuecomment-406475694).

**Describe the solution you'd like**
Add support for the [text-input-method-unstable-v3](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/unstable/text-input/text-input-unstable-v3.xml) protocol to support any and all IMEs that support wayland. This should also enable "free" IME support when using xwayland.

**Describe alternatives you've considered**
1. Use ibus and lose my current configurations, as well as gain the latency that comes with ibus
2. Use a different terminal. Really don't want to do this because kitty is by far the best terminal for unicode, nothing else comes close. Even alacritty still has no proper support for ZWJ, ZWS, ligatures, and various other annoyances that kitty can do well.

**Additional context**
I have a strong suspicion you will be inclined to reject this based on your previous comments about the burden of support for multiple OSes/IMEs as well as the issues of latency, but I would like to make a case for this. For Linux, at least, whether or not wayland is "ready" is irrelevant because the developers of X are perfectly happy to [stop development](https://blogs.gnome.org/uraeus/2019/06/24/on-the-road-to-fedora-workstation-31/) except for what is needed to support RHEL. So until you hear Red Hat back down and say "actually we changed our minds, we want to support Xorg", the future actually is wayland because all of the Xorg developers say so.

Both ibus and fcitx support input-method (the other half of getting IMEs to work in wayland) and therefore will work with any compositor that supports both input-method and text-input. Therefore, your maintenance burden goes down because you only have to support a single wayland protocol for functional IME support in wayland, and eventually on all of Linux.

**Comment by kovidgoyal** [comment]
Sounds like a good idea, patches are welcome :) Personally am not going
to spend time on a still unstable protocol that was extremely recently
revised and has gone through 3 revisions already. Let it mature a bit
more.

In the meantime if somebody else wishes to do the work, I will be happy
to provide any needed guidance.

**Comment by LaserEyess** [comment]
Not sure about your point about it being unstable, you are currently [using a bunch of unstable wayland protocols](https://github.com/kovidgoyal/kitty/blob/master/glfw/wl_platform.h#L57-L61) in kitty. The protocol, even v3, has existed since 2018.

I do, however, get your point about patches being welcome. Unfortunately I'm too dumb to understand C so maybe I'll try to trick someone into doing it for me.

**Comment by kovidgoyal** [comment]
Those are all v1 protocols, this particular one is a v3 protocol, which means it has been found deficient a couple of times already. Given that history, I prefer to let it mature. Not to mention that all those protocols are for minor/peripheral things not something as central to kitty's operation as text input, and most of those were added by other people, not me personally.
