### ISSUE TITLE
Open a new window and make zsh be ready are very slow

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#2815]
OS: macOS 10.15.5 (the latest)
kitty: 0.18.1 (installed via brew)

I launch kitty via a keybinding like `cmd - return : /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~ &> /dev/null`

This slowness happens when we do not touch kitty for a while. It has two situations:
1. If kitty is launched the first time, it will take around 2 seconds for the window to pop up and another 2~3 seconds for zsh to be ready. This slowness is more noticeable when we do not open kitty for a long time. I mean if we use `command-q` to close kitty and immediately launch kitty again, this slowness is not that prominent. 
2. If we already have some kitty windows open, and we just leave them there and do not use kitty for a while. Then suddenly we want to open a new kitty window. The startup of this window will be very slow, i.e., the same: slow window startup and slow zsh initialization. However, if I bear this slowness to open a new kitty window and then I try to open another new kitty window, it will be very fast.

Thanks.

**Comment by kovidgoyal** [comment]
I cannot replicate on my macOS machine, and there is certainly nothing
kitty can do to change zsh startup times. As for kitty startup times,
they are typically on the order of 0.2 seconds. If for some reason they
are longer on your machine, then the simple workaround is to use
--single-instance which will make kitty startup instant for all but the
first window.

**Comment by raylee** [comment]
A possible fix: I was having the same symptoms. plus it was slow to -close- windows, too. The latter seemed very strange. After doing some reading I tried the following which restored the open and close speed to be nearly instantaneous.

`defaults write net.kovidgoyal.kitty NSQuitAlwaysKeepsWindows -bool false`

The suggestion came from [this github comment](https://github.com/sveinbjornt/Platypus/issues/110#issuecomment-377398429) referenced from a [StackExchange answer](https://apple.stackexchange.com/questions/319896/slow-initial-app-window-opening-but-only-in-certain-situations).

**Comment by page-down** [comment]
@rjkaes 

> ... After kitty has been sitting for a few moments ... takes a second or more ...

Unfortunately I cannot reproduce this on my environment (hardware).

> ... menu item highlighted for an extended amount of time ...

This looks like it could have been blocked in the main thread for a while.

Did you try `kitty --config=NONE`, with minimal (default) configuration, to exclude potential affects?

Maybe try to compile from source and troubleshoot.
https://sw.kovidgoyal.net/kitty/build/#building-kitty-app-on-macos-from-source

I can't think of where it gets stuck at the moment, this is most likely related to your environment (hardware, GPU).
