### ISSUE TITLE
support multi-seat wayland

### ISSUE THREAD

**Issue by ec1oud** [kovidgoyal/kitty#2820]
I'm trying this with sway.  man sway-input tells how to associate different mice and keyboards with different seats, so I did this:
```
seat seat1 attach "1452:544:Apple,_Inc_Apple_Keyboard"
seat seat1 attach "1118:184:Microsoft_Microsoft_Optical_Mouse_by_Starck"
```
thus if I have those additional input devices plugged in, that mouse gets its own separate cursor.  When running two xfce4-terminal windows side-by-side, I can put one mouse into one and the other mouse into the other, and type simultaneously into the two terminals with two keyboards.  But if one or both terminals is kitty instead, then I can only type into either of them with the default seat's keyboard (seat0).

https://github.com/swaywm/sway/issues/5499 came up at the same time... I can't really get different cursor themes for the two mice (which would be nice), but again kitty behaves differently than xfce4-terminal.  The seat0 mouse cursor changes correctly to the i-beam cursor from the configured theme when entering the kitty terminal window, but the seat1 mouse cursor does not change at all; I guess kitty is completely ignoring that seat.  xfce4-terminal changes the cursor but uses only the plain X11 theme, not the configured one (also wrong).  weston-terminal is closer to being right: it uses the correct cursor from the seat0 theme with the seat1 mouse.

**Comment by kovidgoyal** [comment]
I'm afraid I dont have any interest in this, patches are welcome. 

I'm guessing xfce4-terminal is using XWayland, if you want to have the
same behavior in kitty, try the linux_display_backend setting in
kitty.conf.

**Comment by ec1oud** [comment]
I built up a gentoo system on which I'm attempting to minimize X11 dependencies, so no xwayland.
