### ISSUE TITLE
Unicode emoji not rendering correctly

### ISSUE THREAD

**Issue by zapling** [kovidgoyal/kitty#2821]
**Describe the bug**
Emojis are not always rendered correctly. 

**To Reproduce**
1. Open neovim with file containing with `⛅` emoji (https://emojipedia.org/sun-behind-cloud/)

**Expected behavior**
Emojis rendering correctly.

**Screenshots**
Opening the file via neovim in kitty terminal:
![Screenshot_2020-07-01_13-03-02](https://user-images.githubusercontent.com/15123086/86237259-bdfcae80-bb9b-11ea-83ac-6ed5fe131340.png)

And sometimes this, depending on terminal size.
![Screenshot_2020-07-01_13-14-27](https://user-images.githubusercontent.com/15123086/86237927-f3ee6280-bb9c-11ea-949c-1cbce39d859b.png)

Opening the file via neovim in xfce4-terminal:
![Screenshot_2020-07-01_13-02-37](https://user-images.githubusercontent.com/15123086/86237360-e8e70280-bb9b-11ea-838b-bbb1d069e4c9.png)

**Environment details**
OS: Manjaro (kernel 5.6.16-1-MANJARO)
WM: i3-gaps 4.18.1-2

```
Linux andreas-t560 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0.3
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"
Loaded config files: /home/andreas/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background           Color(red=39, green=39, blue=39)
bold_font            Bitstream Vera Sans Mono Bold
bold_italic_font     Bitstream Vera Sans Mono Bold Oblique
color0               Color(red=39, green=39, blue=39)
color1               Color(red=204, green=35, blue=28)
color10              Color(red=184, green=186, blue=37)
color11              Color(red=250, green=188, blue=46)
color12              Color(red=131, green=165, blue=151)
color13              Color(red=211, green=133, blue=154)
color14              Color(red=142, green=192, blue=123)
color15              Color(red=235, green=219, blue=178)
color2               Color(red=152, green=151, blue=25)
color3               Color(red=215, green=153, blue=32)
color4               Color(red=68, green=132, blue=136)
color5               Color(red=177, green=97, blue=133)
color6               Color(red=104, green=157, blue=105)
color7               Color(red=168, green=153, blue=131)
color8               Color(red=146, green=131, blue=115)
color9               Color(red=251, green=72, blue=51)
enable_audio_bell    False
font_family          Bitstream Vera Sans Mono
foreground           Color(red=235, green=219, blue=178)
italic_font          Bitstream Vera Sans Mono Oblique
selection_background Color(red=235, green=219, blue=178)
selection_foreground Color(red=101, green=91, blue=83)
url_color            Color(red=214, green=92, blue=13)
```

**Additional context**
I first thought that this issue was related to neovim, but it's working in `xfce4-terminal`.

**Comment by kovidgoyal** [comment]
This will be because neovim is assuming the incorrect width for that
emoji. kitty uses the latest unicode standard for emoji widths, I don't
know what neovim uses, given that it works in xfce4-terminal it will
most likely be because they are both using the buggy system libc
implementation of wcwidth()

Report the bug to neovim.

**Comment by Luflosi** [comment]
If you look closely, you can see, that there are issues with xfce4-terminal as well, the `'` at the end of the string is rendered over the emojis, one cell too far to the left.

**Comment by zapling** [comment]
Ye it looks better in `xfce4-terminal` but something is still off, but it might be neovim. I added my findings here https://github.com/neovim/neovim/issues/7151#issuecomment-652421539
