### ISSUE TITLE
dark greyed text is rendered as black (htop)

### ISSUE THREAD

**Issue by basiliscos** [kovidgoyal/kitty#2826]
**Describe the bug**
dark greyed text is rendered as black (htop)

**To Reproduce**
launch `htop`

**Expected behavior**

**Screenshots**

https://bianco.tv/video/3Fzr7 - this is how `htop` output looks like on my envronment

https://asciinema.org/a/v5O7Gjc1EyPJXSGJDJhvnNIWO - the same thing recorded with `asciinema`, but dark-grayed text is visible.

**Environment details**

Linux localhost 5.4.49_1 #1 SMP PREEMPT Fri Jun 26 14:34:01 UTC 2020 x86_64 GNU/Linux
void linux, `awesome` WM

```
kitty --debug-config
kitty 0.18.1 created by Kovid Goyal
Linux localhost 5.4.49_1 #1 SMP PREEMPT Fri Jun 26 14:34:01 UTC 2020 x86_64
Void \r (\n) (\l)
Loaded config files: /home/b/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
scrollback_lines 20000
tab_bar_edge     1
term             xterm
```

**Additional context**

With `kitty --config NONE` everything looks OK.

**Comment by kovidgoyal** [comment]
https://github.com/hishamhm/htop/issues/35
