### ISSUE TITLE
Internal Border (xterm.vt100.internalBorder in Kitty)

### ISSUE THREAD

**Issue by nezuSTDdos** [kovidgoyal/kitty#2830]
**Is your feature request related to a problem? Please describe.**
It's not a problem, rather it is a mix of question and request. I've used XTerm for a long time now and i recently switched to kitty and was wondering if there is a way of adding an internal border like in XTerm. I haven't found any Infortmation online or when i asked other people.  [...]

**Describe the solution you'd like**
If it's not yet a feature, maybe add an option/variable in the config like internal_border yes/no.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thanks in advance for reading and a possible solution! _~STDdos_

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.window_margin_width, is that what you're looking for?

**Comment by nezuSTDdos** [comment]
Yes, thank you a lot!
