### ISSUE TITLE
Layout splits is unknown

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#2833]
macOS: 10.15.5
kitty: 0.16.0

After I set the window layout to splits by `enabled_layouts splits`, it shows `splits` is unknown when I launch kitty. However, if I set it to other values like `tall`, no errors occurred. Thanks. 

![image](https://user-images.githubusercontent.com/11582667/86562144-078c2700-bf17-11ea-90b5-da376e20fb48.png)

**Comment by kovidgoyal** [comment]
Update kitty

**Comment by yanzhang0219** [comment]
Oh... I am so stupid. The homebrew ignored kitty. Sorry about this. You can delete this issue.
