### ISSUE TITLE
Visual Bell Color configurable

### ISSUE THREAD

**Issue by DLFW** [kovidgoyal/kitty#2834]
Problem: I use dark themes everywhere and every time the visual bell is triggered, my eyes get burned. It’s much too bright.

I hope I have not missed a configuration option, but I just searched in the documentation and did not find any option to change the color or intensity of the visual bell. So, adding an option to configure the visual bell color would be great.

Thanks for this amazing terminal emulator!

**Comment by Luflosi** [comment]
I skimmed the code a bit and it looks like the visual bell currently just inverts all colors.
@kovidgoyal I propose adding the ability to change the color of the entire screen to a solid configurable color instead of inverting all colors.

**Comment by kovidgoyal** [comment]
@Luflosi feel free, though a simple solution for the OP is to 
make his foreground color duller.

**Comment by kovidgoyal** [comment]
kitty has had the ability to customize visual_bell_color for years.

**Comment by page-down** [comment]
You can unify the highlights (including visual bell) are darker by specifying the option selection background color, for years.

If you need to set the visual bell color independently, upgrade to version 0.24+ and use the visual_bell_color configuration.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.visual_bell_color
