### ISSUE TITLE
Choose font weight for variable fonts

### ISSUE THREAD

**Issue by subnut** [kovidgoyal/kitty#2835]
**Is your feature request related to a problem? Please describe.**
No  

**Describe the solution you'd like**
Many fonts nowadays are Variable-weight fonts. It would be great if you could add a configuration option for setting the font weight.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by kovidgoyal** [comment]
You can do that already by simply specifying the full name fo the font
face.
