### ISSUE TITLE
Cursor color doesn't change 

### ISSUE THREAD

**Issue by subnut** [kovidgoyal/kitty#2836]
**Describe the bug**
When using neovim or vim, some colorschemes change the color of the terminal cursor. It doesn't seem to be working in kitty

**To Reproduce**
1. Install neovim
2. install Gruvbox colorscheme
3. Open kitty with white cursor color
4. Start up nvim
5. change to light mode (`set bg='light'`)

**Expected behavior**
The cursor color changes to a darker one, so that it remains visible

**Actual behaviour**
Cursor color remains white, rendering it nearly invisible

**Screenshots**

**Environment details**
OS: Name and version of operating system(s)
```
kitty 0.18.1 created by Kovid Goyal
Linux EndeavourPad 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=EndeavourOS
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="EndeavourOS Linux"
Loaded config files: /home/subhaditya/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity         0.8
color0                     Color(red=1, green=1, blue=1)
color16                    Color(red=1, green=1, blue=1)
dynamic_background_opacity True
font_family                Cascadia Code
font_size                  12.0
window_padding_width       FloatEdges(left=35.0, top=35.0, right=35.0, bottom=35.0)
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.
Bug not dependent on config.

**Comment by kovidgoyal** [comment]
Works fine for me

printf '\e]12;red\a'

gives a red cursor. You will need to figure out why your editor of
choice is not emitting the escape sequence to change cursor color.

**Comment by subnut** [comment]
hmm.... That's correct! Thank you @kovidgoyal !
  
Also, does kitty have a setting to set the cursor color to **reverse** ? If not, then do you plan to?

**Comment by kovidgoyal** [comment]
No I dont, patches welcome.
