### ISSUE TITLE
Mapping cmd key to ctrl key on MacOS?

### ISSUE THREAD

**Issue by sou-chon** [kovidgoyal/kitty#2838]
In iterm2 for example you can map the right or left cmd key to send ctrl modifier. I am wondering if this is possible in kitty because I cannot find the documentation for this. 

This allows me to not have to twist my hand pressing ctrl on Mac.

**Comment by kovidgoyal** [comment]
I'm afraid there is no modifier mapping in kitty. Might add a general
framework for it someday, but it's not a priority. Patches are welcome.
If you have a limited number of things you use the ctrl key with you can
manually map the cmd+whatever combinations in kitty.conf using send_text

**Comment by Sleepful** [comment]
karabiner elements is an alternative for OS-wide mapping
