### ISSUE TITLE
Font render behavior

### ISSUE THREAD

**Issue by glepnir** [kovidgoyal/kitty#2848]
**Describe the bug**
The font render with Operator mono lig book.  You can see this pic the left is iterm2, There is a clear gap between the letters in kitty, Iterm2 render it ok with 100 height and width.  i can fixed it by `adjust_column_width -1`. I want to know this is the  expected behavior in kitty?

**To Reproduce**
1. use Operator mono Lig book font

**Expected behavior**
Maybe don't need  set `adjust_column_width -1`?
**Screenshots**
![image](https://user-images.githubusercontent.com/41671631/87239626-dc886280-c443-11ea-9180-7713befcb178.png)

**Environment details**
OS: Name and version of operating system(s)

```
kitty 0.18.1 (4309e2371d) created by Kovid Goyal
Darwin stephendeiMac.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.5 BuildVersion:	19F101
Loaded config files: /Users/stephen/.config/kitty/kitty.conf

Config options different from defaults:
background              Color(red=27, green=43, blue=52)
bold_font               Operator Mono Lig Medium
bold_italic_font        Operator Mono Lig Medium Italic
copy_on_select          clipboard
cursor                  Color(red=124, green=172, blue=74)
cursor_blink_interval   0.0
font_family             Operator Mono Lig Book
font_size               17.0
foreground              Color(red=151, green=158, blue=171)
hide_window_decorations 2
italic_font             Operator Mono Lig Book Italic
mouse_hide_wait         3.0
```

**Comment by kovidgoyal** [comment]
Yes, it is expected behavior. cell width numbers come from the font
rendering system, in this case CoreText's glyphadvances function. This
is the correct metric to use when rendering. See cell_metrics() in
core_text.m

**Comment by glepnir** [comment]
@kovidgoyal  Thanks for your reply. I got it.  I am not font pro , but i want to know that i set this  `adjust_column_width -1`  is right?

**Comment by kovidgoyal** [comment]
Using negative values can lead to rendering artifacts see the docs of
that option

On Sun, Jul 12, 2020 at 03:04:42AM -0700, Raphael wrote:
> @kovidgoyal  Thanks for your reply. I got it.  I am not font pro , but i want to know that i set this  `adjust_column_width -1`  is right? 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/2848#issuecomment-657200896

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by glepnir** [comment]
I had read the doc. So is there has a new way to solve this problem instead of  `adjust_column_width -1`
>Change the size of each character cell kitty renders. You can use either numbers, which are interpreted as pixels or percentages (number followed by %), which are interpreted as percentages of the unmodified values. You can use negative pixels or percentages less than 100% to reduce sizes (but this might cause rendering artifacts).

**Comment by kovidgoyal** [comment]
No, its not a problem. The width while being different from iterm is what it is supposed to be as per coretext. If you dont like it you can use the adjust option, and take the risk that some glyph in the font wont fit and be chopped off/rescaled. If you are lucky there will be no such glyph that you use.
