### ISSUE TITLE
Kitty not opened when opening desktop file

### ISSUE THREAD

**Issue by chaitunya** [kovidgoyal/kitty#2851]
**Describe the bug**
When I open desktop files that use the terminal, gnome-terminal opens by default. If gnome-terminal isn't installed, the desktop file doesn't get opened properly. Applications like Vim won't be opened it kitty because of this.

**To Reproduce**
1. Open a .desktop file in GNOME with the value `Terminal=true` in it
2. See error

**Expected behavior**
Kitty should be opened when a .desktop file is opened instead of GNOME Terminal

**Environment details**
Output of `kitty --debug-config`:
```
Linux chaitu-ThinkPad-T480 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64
Ubuntu 20.04 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf
Running under: X11

Config options different from defaults:
update_check_interval 0.0
```
GNOME version 3.36.3

**Comment by kovidgoyal** [comment]
kitty has no control over what GNOME does when opening desktop files.
You will need to associate kitty with whatever filetype it is you are
trying to open and then GNOME will use it.
