### ISSUE TITLE
Is it possible to apply colors to tab_title_template config option?

### ISSUE THREAD

**Issue by sethwoodworth** [kovidgoyal/kitty#2853]
**Is your feature request related to a problem? Please describe.**
I am using the setting `tab_title_template "\ue0b6{title}\ue0b4"`
I would like to invert the background and foreground colors of the characters on either side of the tab's title.

**Describe the solution you'd like**
I would like to be able to apply colors and styles to sub-sections of my kitty theme template strings.

**Describe alternatives you've considered**
I've tried using ansi escape codes directly in the `tab_title_template`, but either applied them incorrectly, or that sort of rendering doesn't apply in this space.

**Comment by xieve** [comment]
I'm currently trying to achieve the same thing, specifically to use different powerline symbols (slant instead of "arrow"). I don't believe ANSI codes are applicable here, the ESC code was "handled" correctly (not shown) but the escaped sequence was instead shown in literals. I've also tried hijacking the f-string feature, to no avail.

**Comment by kovidgoyal** [comment]
Escape codes are not supported, therefore no colors, however you can use any unicode symbols you like, including powerline ones. And adding support for limited escape codes, say the SGR ones for colors should not be hard, patches welcome, look at the draw_title() function tab_bar.py. You would ned to parse out the sgr codes manually, use pis on the screen bject to change colors.

**Comment by xieve** [comment]
Well, powerline symbols require the color to be set in the tab title, not around it, at least when you want the inactive tabs to have a different background color than the active tab's foreground color. I'd like you to reopen this issue if you don't mind, as I might actually write a PR tomorrow.

**Comment by kovidgoyal** [comment]
Feel free to send a PR, and continue to comment on this issue. Note that there is a builtin powerline tab style.

**Comment by xieve** [comment]
I know, but I want to use the slant characters (\ue0b8 and following). I'm gonna look into whether I should modify it to include multiple powerline styles or just add ANSI support to the tab bar.

**Comment by sethwoodworth** [comment]
@kovidgoyal thank you for the pointers.  I agree this isn't a well written issue and should be closed.  But I'm very glad you're open to PRs for it and gave some helpful pointers.
@xieve I was digging through the source for tab_bar and would be happy to contribute/test/review!
