### ISSUE TITLE
option to prevent unintended close

### ISSUE THREAD

**Issue by smolin** [kovidgoyal/kitty#2857]
kitty is wonderful, thank you very much!

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I hit command-q or command-w and the window closes, losing my shell state.

**Describe the solution you'd like**
I would like a dialog open asking "do you really want to close this window? yes/no"

**Describe alternatives you've considered**
Um ... I've looked through the docs and issues and didn't see this as an option?

**Additional context**
MacOS 10.14.6, kitty 0.17.4

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close.

**Comment by smolin** [comment]
Thanks Luflosi! I shoulda updated first of course.

This is almost but not quite perfect - set to "1" it:

    - confirms closing the application with command-q
    - confirms closing windows when clicking on the red X circle button
    - confirms closing windows with command-w when there are more than one shell

but it does not confirm closing a window with command-w when there is only one shell. The description says "at least this number of kitty windows" so I think it's not counting correctly....

**Comment by kovidgoyal** [comment]
As I recall cmd+w is close_tab, correct? The option is for closing OS windows, not tabs. It might make sense to either extend it to also apply to tabs or to have a new option for tabs.
