### ISSUE TITLE
combining character support

### ISSUE THREAD

**Issue by Screwtapello** [kovidgoyal/kitty#286]
Steps to reproduce:

 1. Inside a kitty window, run:

        curl https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt

  2. Scroll back up to the section beginning "Thai (UCS Level 2)"

Expected result:

![image](https://user-images.githubusercontent.com/1450918/34916592-116cfbbe-f98f-11e7-8975-23644a3931b9.png)
(as reproduced by `gnome-terminal`; `xterm` only draws boxes unless you tell it to use a font with Thai characters, but the boxes do line up as expected)

Actual result:

![image](https://user-images.githubusercontent.com/1450918/34916588-ea6c12f2-f98e-11e7-8b64-52f0bf4b43ff.png)
(as reproduced at commit 872d39e on up-to-date Debian Testing)

**Comment by kovidgoyal** [comment]
I know nothing about Thai, but kitty uses libunistring to decide what characters are combining characters (and it handles all the combining characters I know of perfectly), see is_combining_char() in unicode-data.h. For example,  He͇̅llo̷, ŵor̆l͔d! (He\u0347\u0305llo\u0337, w\u0302or\u0306l\u0354d!) which even my browser doesn't render correctly, renders fine in kitty (see attached screenshot). So combining characters themselves are handled correctly. 

As far as I know, libunistring uses the combining character classes from the unicode standard. If Thai requires special handling, beyond the unicode standard, or if my use of libunistring is incomplete/incorrect then I welcome patches from people that understand Thai.

![screenshot_20180114_205626](https://user-images.githubusercontent.com/1308621/34917515-709c9d14-f96d-11e7-9517-70687c8a8169.png)

**Comment by craigbarnes** [comment]
The [UTF-8 demo](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt) file still renders very strangely in kitty 0.16.0 for me:

![kitty-th-1](https://user-images.githubusercontent.com/494077/75873798-7857f100-5e08-11ea-82d0-d11e0a9e168e.png)

![kitty-th-2](https://user-images.githubusercontent.com/494077/75873821-8574e000-5e08-11ea-87ac-83d14dbda4a8.png)

It seems like it's overlaying some other cached glyphs on top of the Thai characters. Perhaps something to do with `is_combining_char()` and `draw_combining_char()` not making a distinction between non-spacing/enclosing and _spacing_ marks (commit 804c4fbe19870fad7b7d6288145b4a0573ff2d15)...?

**Comment by pepa65** [comment]
I don't think you need to know Thai to fix this. For a starters, you can look how others have fixed this issue. As of now, kitty is completely broken for those who use Thai in the terminal. And it seems only Thai is affected. And it is not just combining character support.

**Comment by craigbarnes** [comment]
FWIW, I can no longer reproduce the issues I [mentioned](https://github.com/kovidgoyal/kitty/issues/286#issuecomment-594462001) above (using kitty 0.26.5). @pepa65 What version of kitty are you running?

**Comment by pepa65** [comment]
That is great news! My output was very similar on kitty 0.15.0-1ubuntu0.2 -- I think I just need to build it myself then..!
