### ISSUE TITLE
Symbols in fonts not rendering properly

### ISSUE THREAD

**Issue by eprislac** [kovidgoyal/kitty#2864]
**Describe the bug**
Specifically, I use Hasklig Nerd Font with Powerline Symbols (Hasklug), but I have seen it with others. On the left of my 1st screenshot is my prompt, rendered in iTerm2. To the right of the same pic, in Kitty. Below is a screenshot of the same font in MacTerm.

**Screenshots**
![Screenshot 2020-07-18 02 28 00](https://user-images.githubusercontent.com/11530791/87847486-571b0d00-c89e-11ea-827a-7096117a8a57.png)

![Screenshot 2020-07-18 02 31 38](https://user-images.githubusercontent.com/11530791/87847556-d6a8dc00-c89e-11ea-8e25-4b1abfe5bdbb.png)

**To Reproduce**
1. Symbols may render improperly with different symbol characters, especially curved lines and arrows. Use Hasklug Nerd Font to reproduce my results.

**Expected behavior**
Fonts should render properly.

**Environment details**
OS: MacOS 10.15.5

```
Darwin vault-13.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.5 BuildVersion:	19F101
Loaded config files: /Users/eddie/.config/kitty/kitty.conf
[200 02:37:16.253470] Ignoring unknown config key: bold_itali_font
[200 02:37:16.253520] Ignoring unknown config key: touch_scroll

Config options different from defaults:
background           Color(red=50, green=48, blue=47)
bold_font            Hasklug Nerd Font Bold
clipboard_control    frozenset({'no-append', 'read-primary', 'write-clipboard', 'write-primary'})
color0               Color(red=50, green=48, blue=47)
color1               Color(red=251, green=73, blue=52)
color10              Color(red=184, green=187, blue=38)
color11              Color(red=250, green=189, blue=47)
color12              Color(red=131, green=165, blue=152)
color13              Color(red=211, green=134, blue=155)
color14              Color(red=142, green=192, blue=124)
color15              Color(red=184, green=187, blue=38)
color2               Color(red=184, green=187, blue=38)
color3               Color(red=250, green=189, blue=47)
color4               Color(red=131, green=165, blue=152)
color5               Color(red=211, green=134, blue=155)
color6               Color(red=142, green=192, blue=124)
color7               Color(red=213, green=196, blue=161)
color8               Color(red=102, green=92, blue=84)
color9               Color(red=251, green=73, blue=52)
font_family          Hasklug Nerd Font Regular
font_size            14.0
foreground           Color(red=213, green=196, blue=161)
italic_font          Hasklug Nerd Font Italic
selection_background Color(red=0, green=0, blue=0)
selection_foreground Color(red=250, green=189, blue=47)
term                 xterm-256color-italic
Added shortcuts:
	super+p KeyAction(func='paste_from_clipboard', args=())
```

**Comment by kovidgoyal** [comment]
I dont see anything improper about it other than that your arrow symbol
is not vertically aligned, which is something that is impossible to do,
since the line and the arrow are from different fonts.To line up
properly, the arrow needs to be perfectly vertically centered in the
cell. Because kitty draw box drawing symbols (the line here) perfectly
centered. So the arrow needs to be fixed in whatever font it is coming
from.

And dont use patched fonts, they are broken badly. kitty can load
symbols from non-patched fonts, automatically. most likely simply not
using a patched font will fix it automatically.
