### ISSUE TITLE
Yakuake-like global for- and background-shortcurt

### ISSUE THREAD

**Issue by hersche** [kovidgoyal/kitty#2865]
**Is your feature request related to a problem? Please describe.**
I use https://kde.org/applications/en/system/org.kde.yakuake a lot. It allows to get a quick-access to the terminal by press F12.
I can set the wanted terminal, but with kitty, it opens a new window.

**Describe the solution you'd like**
As it makes sense to open a new window for using the gpu, it's maybe easier to implement this functionality simply to kitty.
A very basic version can put it by any key to for- or background, doesn't have to come from top down. This would be very useful on daily work.

**Describe alternatives you've considered**
The other solution would may be to integrate it to yakuake. The problem i see there is, that you cannot using kitty as a cli-app - or is that wrong?

**Additional context**
I've just explored your project today and like it very much. Thanks for creating this project!

**Comment by kovidgoyal** [comment]
dup of #45
