### ISSUE TITLE
Remote control: tab opens in wrong os window

### ISSUE THREAD

**Issue by tobiwild** [kovidgoyal/kitty#2869]
**Describe the bug**
I like to open a new os window and a new tab in this os window without losing the focus of the current os window.

I tried this:
```
kitty @ launch --match "id:$(kitty @ launch --type=os-window --keep-focus)" --type=tab
```

This opens a new tab in the current os window instead of the newly created os window.

Without `--keep-focus`, it works as expected (new tab in new os window):
```
kitty @ launch --match "id:$(kitty @ launch --type=os-window)" --type=tab
```

But maybe I'm doing it wrong.

**Environment details**
OS: macOS 10.15.6
kitty 0.18.1

**Comment by kovidgoyal** [comment]
--match takes the id of a tab not the id of a window. kitty @ launch
prints out the id of a window. So you cannot do it like that. Using
--type=tab always opens a new tab in the currently active OS window. So
dont use --keep-focus, instead get the id of the currently focused
window from kitty @ ls. Open your new OS window + tab and then use kitty @
focus-window to move focus back to the original window.
