### ISSUE TITLE
Support old alternate screen xterm code

### ISSUE THREAD

**Issue by Kody-Quintana** [kovidgoyal/kitty#2870]
When exiting a script that uses the Python TUI library [urwid](http://urwid.org/), content of the screen does not disappear until any newer content writes over it.
`[PARSE ERROR] Unsupported screen mode:  47 (private)` is emitted from kitty.
Any of the examples from the [here](https://github.com/urwid/urwid/tree/master/examples) will show this behavior. Would it be possible to get support for this screen mode? As a temporary work around I'm manually calling `clear` after exiting my urwid script.
edit: it looks like it could be as simple as adding the old code as an additional case, I submitted a PR

**Comment by kovidgoyal** [comment]
This is a bug in urwid, it needs to use terminfo to get the correct
escape code, namely the smcup and rmcup capabilities. You should report
it to them.
