### ISSUE TITLE
Wrong font size rendered for glyphs with negative right sidebearings

### ISSUE THREAD

**Issue by mekkablue** [kovidgoyal/kitty#2872]
**Describe the bug**
Ligatures in certain monospaced fonts are with the wrong font size (scaled down to fit into a single char width or whatever `adjust_column_width` is set to).

This has first been described in this issue:
https://github.com/MonoLisaFont/feedback/issues/15

MonoLisa is a monospaced font that uses a combo of <glyph with negative RSB>+<space> for rendering its ligatures. (For comparison: Fira uses <space>+<glyph with negative LSB>.)

**To Reproduce**
1. Download and install MonoLisa: 
2. Add `font_family MonoLisa` to kitty.conf
3. Restart Kitty.app
4. Type `***`

**Expected behavior**
Rendering of three asterisks like this:
![Screenshot 2020-07-22 at 14 43 37](https://user-images.githubusercontent.com/1103103/88177818-bf187d00-cc29-11ea-8305-7c7b43b8b939.png)

**Screenshots**
The three
![Screenshot 2020-07-22 at 14 44 45](https://user-images.githubusercontent.com/1103103/88177934-e4a58680-cc29-11ea-811e-1fe0ee2945cb.png)

**Environment details**
OS: macOS 10.14.6 (18G5033)

**Additional context**
Potential clue: Try `adjust_column_width 200%` and the ligatures get squeezed into two char widths.

**Comment by kovidgoyal** [comment]
dup of #2599
