### ISSUE TITLE
Line height config not work for emoji

### ISSUE THREAD

**Issue by hermanzhu** [kovidgoyal/kitty#2873]
Line height config not work for emoji

**To Reproduce**
 font_size 12
 adjust_line_height  17

**Expected behavior**
iterm2:
<img width="116" alt="image" src="https://user-images.githubusercontent.com/1592161/88260945-f5bcc900-ccf7-11ea-9c83-bfd2f1646c54.png">

**Screenshots**
kitty:
<img width="106" alt="WeChatWorkScreenshot_2658ed38-6464-4d96-b402-afad9264c64d" src="https://user-images.githubusercontent.com/1592161/88260682-70d1af80-ccf7-11ea-81be-c38bec7b43fa.png">

**Environment details**
OS: macOS big sur beta

```
adjust_line_height 17
background         Color(red=35, green=41, blue=45)
color0             Color(red=35, green=41, blue=45)
color1             Color(red=239, green=78, blue=124)
color10            Color(red=9, green=179, blue=153)
color11            Color(red=247, green=149, blue=50)
color12            Color(red=18, green=153, blue=173)
color13            Color(red=160, green=103, blue=171)
color14            Color(red=9, green=179, blue=153)
color15            Color(red=253, green=253, blue=253)
color2             Color(red=110, green=187, blue=130)
color3             Color(red=247, green=149, blue=50)
color4             Color(red=18, green=153, blue=173)
color5             Color(red=160, green=103, blue=171)
color6             Color(red=9, green=179, blue=153)
color7             Color(red=222, green=223, blue=223)
color8             Color(red=66, green=71, blue=75)
color9             Color(red=243, green=112, blue=85)
cursor             Color(red=80, green=115, blue=184)
font_family        jetbrainsmono nerd font
font_size          12.0
foreground         Color(red=253, green=253, blue=253)

```

**Additional context**

**Comment by kovidgoyal** [comment]
Probably from line 412 in core_text.m, might need to only do that
adjustment when adjust_line_height is not positive.

**Comment by glepnir** [comment]
@kovidgoyal  Maybe this is a related problem. There are some problems with the height of kitty rendering emoji.

**iterm2**
  ![image](https://user-images.githubusercontent.com/41671631/88299275-c2e4f600-cd34-11ea-850a-c1e1b00e9b10.png)
**kitty**
![image](https://user-images.githubusercontent.com/41671631/88299319-cd06f480-cd34-11ea-8c6b-cc69bb27baee.png)
