### ISSUE TITLE
I can't use my ed25519 key to login

### ISSUE THREAD

**Issue by AlphaJack** [kovidgoyal/kitty#2874]
**Describe the bug**
I can't use my ed25519 key to login.  
Since I can't directly use my OpenSSH private key, I tried converting it with PuTTYgen.  
I am prompted for my passphrase, but after I enter it correctly (otherwise KiTTY prompts me again) the window closes without any error.  
On my server `sshd` logs I only see:
```
Accepted publickey for jack from 192.168.1.100 port 50526 ssh2: ED25519 SHA256:HASHHASHHASHHASHHASHHASH
```

**To Reproduce**
1. Create an ed25519 key pair with `ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -C "comment"` and deploy the public key on the server
2. Convert the private key in PuTTY format
3. Enter your passphrase
4. See the window closing

**Expected behavior**

**Environment details**
OS: Windows 7 SP1
KiTTY: 0.74.0.2
Output of `kitty --debug-config`:
![ke](https://user-images.githubusercontent.com/19962243/88283382-c9468400-ccda-11ea-82d0-0bc4d46fc869.PNG)
Same for  `kitty --config NONE`  
There is no `kitty.conf` in my system

**Comment by kovidgoyal** [comment]
Wrong place: https://github.com/cyd01/KiTTY/
