### ISSUE TITLE
OSC color querying produces invalid response

### ISSUE THREAD

**Issue by aslpavel** [kovidgoyal/kitty#2887]
**Describe the bug**
OSC can be used to query different color settings, it does work but produces weird response. I think [report_color](https://github.com/kovidgoyal/kitty/blob/01be77e0bc20ed5e741054317346f8381bc7409b/kitty/window.py#L509-L513) function is to blame, for reason unknown to me it duplicates hex encoding and make is four characters wide (i.e "d7" is converted to "d7d7")

**To Reproduce**
```
$ cat
^[]4;1;?^[\

^[]4;1;rgb:cccc/2424/1d1d^[
```

**Expected behavior**
I am not sure about format of the response but I have tested it in a couple of terminals and I think response should be
```
$ cat 
^[]11;?^[\

^[]4;1;rgb:cc/24/1d^[
```
or
```
^[]11;?^[\

^[]4;1;#cc241d^[
```

**Comment by kovidgoyal** [comment]
As I recall it is correct, see the man page of XParseColor, or look at
the output from xterm.
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
