### ISSUE TITLE
Cursor size is broken

### ISSUE THREAD

**Issue by MatthiasCoppens** [kovidgoyal/kitty#2895]
**Describe the bug**
On my latest build of kitty, my cursor is bigger when hovering over a kitty window.

**To Reproduce**
1. Build kitty from source (master branch)
2. Open kitty window
3. Move cursor over window
4. Cursor changes size

**Expected behavior**
I expected my cursor to stay the same.

**Screen capture**
<https://nextcloud.mattcopp.duckdns.org/s/4YGFjea9AkGZZKs>

**Environment details**
Gentoo Linux
sway version 1.5-5c67d997 (Jul 31 2020, branch 'HEAD')

```
[216 10:20:35.471438] The option macos_show_window_title_in_menubar is deprecated. Use macos_show_window_title_in menubar instead.
kitty 0.18.2 (ab3c9658bd) created by Kovid Goyal
Linux gentoo-laptop 5.4.48-gentoo #1 SMP Sun Jun 28 15:37:00 CEST 2020 x86_64
This is \n.\O (\s \m \r) \t
DISTRIB_ID="Gentoo"
Loaded config files: /home/matthias/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
font_size                  10.0
select_by_word_characters  :@-./_~?&=%+#
single_window_margin_width FloatEdges(left=-1000.0, top=-1000.0, right=-1000.0, bottom=-1000.0)
update_check_interval      0.0
```

**Additional context**
The problem persists with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Set XCURSOR_SIZE env var to whatever size you want.

**Comment by MatthiasCoppens** [comment]
Is there a way to make it inherit the cursor size from the WM? It seems counterintuitive to have to define the cursor size for kitty separately from every other application.

**Comment by kovidgoyal** [comment]
Wayland uses Xcursor, XCURSOR_SIZE is the canonical way to specify the
size for Xcursor. I dont know what WM you use, but it should be setting
that env var, kitty is not going to grow code to read cursor size for
every window manager/desktop environment under the sun.

**Comment by duffydack** [comment]
Am seeing the same 'issue'.  Using Arch with release versions of Kitty and Sway.  So far I've tried, 
  setting 'export XCURSOR_SIZE=16' in .zprofile where all my variables get exported and sway is started,
  running 'XCURSOR_SIZE=16 kitty' from terminal,
  adding 'seat seat0 xcursor_theme Adwaita 16' to sway config, which exports the XCURSOR theme and size variables 
  correctly, yet kitty still uses larger cursor.

**Comment by MatthiasCoppens** [comment]
Changing XCURSOR_SIZE also doesn't seem to work on my end.

**Comment by MatthiasCoppens** [comment]
Did a quick bisect, commit 6f40b8d0a1462a000ddbe0261577884e4443f5f4 introduced this issue
