### ISSUE TITLE
wayland compositor on chromeos - transparency not working

### ISSUE THREAD

**Issue by sureshmnv** [kovidgoyal/kitty#2897]
**Describe the bug**
The "Terminator" and "xfce4-terminal" in the same environment have "transparency" working.  But kitty is throwing following error.  So many additional features in kitty are so amazing and compelling, but "transparency" is a starting point for me for any terminal application.  Lack of transparency is preventing me from trying anything else.

Thanks for creating such a feature-rich terminal application!!!

**To Reproduce**

Crostini on ChromeOS apparently uses Wayland, I'm not OpenGL expert, and uses an "external" compositor - sommelier.

https://chromium.googlesource.com/chromiumos/platform2/+/413a646b5b7067a989bab2ef9fca0c3a4515cc22/vm_tools/sommelier/README.md

has all details, although I don't understand most of it.

With single line change:

background_opacity 0.5

the following error:

kitty --start-as=fullscreen --config ~/.config/kitty.conf 
Your Wayland compositor does not support server side window decorations, disabling Wayland. You can force Wayland support using the linux_display_server option in kitty.conf See https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html for more information.
[216 22:10:02.493958] Failed to enable transparency. This happens when your desktop environment does not support compositing.

Modifying the line 

linux_display_server wayland

throws following new error:

kitty --start-as=fullscreen --config ~/.config/kitty.conf 
[216 22:14:21.439602] [glfw error 65544]: Wayland: Failed to find xdg-shell in your compositor
GLFW initialization failed

**Expected behavior**
background image or desktop background with expected transparency

**Screenshots**

**Environment details**

Chromebook Lenovo Yoga C630 running most recent official Chromeos

OS: Name and version of operating system(s):
Google Chrome: Version 84.0.4147.110 (Official Build)  (64-bit)
Platform: 13099.85.0 (Official Build) stable-channel nami
Channel: stable-channel
Firmware Version: Google_Nami.10775.108.31
ARC Enabled: true
ARC: 6687630
Enterprise Enrolled: false
Developer Mode: false

```
Output of kitty --debug-config

kitty --start-as=fullscreen --config ~/.config/kitty.conf --debug-config
kitty 0.18.2 (81bda736d8) created by Kovid Goyal
Linux penguin 5.4.40-04224-g891a6cce2d44 #1 SMP PREEMPT Tue Jun 23 20:21:29 PDT 2020 x86_64
Debian GNU/Linux 10 \n \l
Loaded config files: /home/sureshmnv/.config/kitty.conf
Running under: Wayland

Config options different from defaults:
background_opacity   0.5
copy_on_select       clipboard
linux_display_server wayland
tab_bar_style        hidden
```

**Additional context**

opengl part is fine, glxgears works fine.

glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Red Hat (0x1af4)
    Device: virgl (0x1010)
    Version: 19.2.8
    Accelerated: yes
    Video memory: 0MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Red Hat
OpenGL renderer string: virgl
OpenGL core profile version string: 4.3 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 19.2.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

Also, here are options from

Terminator:
[profiles]
  [[default]]
    background_darkness = 0.61
    background_type = transparent

xfce4-terminal:
BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT
BackgroundDarkness=0.490000

Above two terminals don't have background image, but are transparent with respect to the desktop default image, which is also fine with me for now.

**Comment by kovidgoyal** [comment]
According to that your wayland compositor is missing the xdg-shell
extension, without that kitty cannot function, as it has dropped support
for the legacy wl-shell, which is deprecated. Update to use a more
modern compositor and you will be fine, until then you have to live
without translarency.

**Comment by sureshmnv** [comment]
thanks for response...
looks like something had been addressed, but not sure if it made it to the official version yet.
997631 - chromium - An open-source project to help move the web forward. - Monorailhttps://chromium.googlesource.com/chromium/src.git/+/0d8f08315cb7165e46e93639699093dbae2c69d3



    On Tuesday, August 4, 2020, 12:18:20 AM PDT, Kovid Goyal <notifications@github.com> wrote:  
 
 


According to that your wayland compositor is missing the xdg-shell
extension, without that kitty cannot function, as it has dropped support
for the legacy wl-shell, which is deprecated. Update to use a more
modern compositor and you will be fine, until then you have to live
without translarency.

**Comment by tapayne88** [comment]
I found this occurring to me without the use of transparency. I can't quite pin down why it started occurring to me but here's what fixed it for me in case it's useful to someone else.

```conf
linux_display_server x11
```
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.linux_display_server

I found I had to force kitty to use `x11` instead of defaulting to `auto`. This seems to choose `wayland` on my setup. It had previously worked without this setting but something changed 🤷 

Context:
- Chrome OS 92.0.4515.66 (Official Build) beta
- [nix package manager](https://nixos.org/)
- kitty 0.20.3 running with [nixGL](https://github.com/guibou/nixGL)

**Comment by rahil627** [comment]
for my arch "crostini" (chromeos lxc container), kitty would start up either with the window inverted (completely black, wrong quadrant?) or a white vertical line (signifying no horizontal length), and i'd have to resize it to see it.

`linux_display_server x11`

this made the window appear in the correct quadrant, but so small that you can only make out a piece of the white bar on the top of the window.

`remember_window_size yes`

fixed that
