### ISSUE TITLE
Closing the terminal automatically kills all running processes w/o warnings

### ISSUE THREAD

**Issue by vkhodygo** [kovidgoyal/kitty#2902]
**Describe the bug**
The default behaviour for all other terminals is to let users know that there are some processes running in the terminal and closing it will kill them. Unfortunately, kitty doesn't do so which is quite inconvenient. 

**To Reproduce**
1. Start kitty
2. Run something, for example, start a bunch of ssh connections
3. Close kitty
4. See no error or warning.

**Expected behavior**
There should be a confirmation pop-up window.

**Screenshots**
None

**Environment details**

```
kitty 0.18.2 created by Kovid Goyal
Linux laptop 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/vlk/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
```

**Additional context**
None, the problems persists even with the default config.

**Comment by SolitudeSF** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close

**Comment by vkhodygo** [comment]
@SolitudeSF It's like the most default behaviour one can imagine, I've never seen a terminal that doesn't ask. 
On a side node, thanks for the link.

**Comment by vkhodygo** [comment]
I guess I need to ping @kovidgoyal one more time since I don't want to open a new issue.

**Comment by kovidgoyal** [comment]
Not sure what you are pinging me for. The default is what I think is appropriate, it's not going to change.
