### ISSUE TITLE
Kitty is slow on machines with no hardware acceleration

### ISSUE THREAD

**Issue by Kabouik** [kovidgoyal/kitty#2903]
**Describe the bug**
Not really a bug, I'm merely wondering if it is possible to run `kitty` on a machine with no hardware acceleration and still get a performance level similar to that of non-GPU terminal emulators. Are there features I could disable in `kitty.conf` that are particularly demanding and eat much GPU horsepower?

I run Debian in a LXC container on my hwkb phone and reproduced my whole `i3` desktop environment there, including most applications and `.bashrc`. It is like moving around with my usual full-fledged computer in my pocket, except `kitty` works but is not performing well on it compared to `tilix`. I would be happy if I could use `kitty` as I do on my desktop machines and benefit from image preview in `nnn` and other cool features.

**Comment by kovidgoyal** [comment]
No not really. Non hardware accelerated rendering demands a completely
different design from kitty's for performance. Kitty's design relies on
being able to store rendered chars on GPU and render them at appropriate
positions by simply sending a string to bits to the GPU and running
shaders to composite things on the GPU directly. If there is no hardware
accelerated GPU this will be very slow.
