### ISSUE TITLE
Kitty input lags (a lot) when full screen running under XWayland.

### ISSUE THREAD

**Issue by lsunsi** [kovidgoyal/kitty#2905]
**Describe the bug**
Kitty input lags (a lot) when full screen running under XWayland. If I run the windowed version, it runs fine. Pressing shift+F11 works fine, but each input lags about 2~3 seconds to appear and then multiple inputs appear at once.

**To Reproduce**
1. Open kitty in XWayland (Just open it on Fedora default DE, if you use Fedora)
2. Type something running the windowed (things will work fine)
3. Enter full screen
4. Type something (things will delay a lot)

**Expected behavior**
Full-screen kitty should work the same as windowed

**Environment details**
Fedora 32 fully up-to-date.
Kernel: 5.7.11-200.fc32.x86_64

```
kitty 0.18.0 created by Kovid Goyal
Linux fedora 5.7.11-200.fc32.x86_64 #1 SMP Wed Jul 29 17:15:52 UTC 2020 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: /home/lsunsi/.config/kitty/kitty.conf
Your Wayland compositor does not support server side window decorations, disabling Wayland. You can force Wayland support using the linux_display_server option in kitty.conf See https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html for more information.
Running under: X11

Config options different from defaults:
cursor_text_color       None
font_family             Fira Code
font_size               12.0
foreground              Color(red=248, green=248, blue=242)
inactive_tab_background Color(red=98, green=114, blue=164)
inactive_tab_foreground Color(red=40, green=42, blue=54)
selection_background    Color(red=248, green=248, blue=242)
selection_foreground    Color(red=68, green=71, blue=90)
tab_bar_edge            1
url_color               Color(red=255, green=184, blue=108)
Changed shortcuts:
	shift+control+t KeyAction(func='new_tab_with_cwd', args=())
```

**Additional details**
The problem apparently gets fixed if I set `sync_to_monitor no` on the kitty.conf. That said, I read on issues here that I should try to set this setting to true, and I see no reason why this fixes the issue. Maybe it's a clue to what the problem is.

**Comment by kovidgoyal** [comment]
I cannot reproduce under sway or weston, no idea what fedora uses, gnome/mutter possibly?
And kitty contains no special rendering paths for fullscreen windows,
they work exactly the same as normal windows as far as kitty is
concerned. This is most likely a bug in your XWayland implementation. I
suggest you use the kitty wayland backend instead and live with ugly
window decorations

https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.linux_display_server

**Comment by lsunsi** [comment]
@kovidgoyal I definitely rather use the wayland backend, but the full screen crashes for me! Hence the other opened issue. haha.

**Comment by apiraino** [comment]
I'm not sure my comment will be relevant but I had a similar problem when I first installed Kitty on a freshly configured Debian box. I don't use `xwayland`. I had a terrible lag on keyboard input and when switching from one Kitty window to another. High CPU usage. I had the same problem with Alacritty but not with a Wayland no-gpu-enabled terminal emulator (ex. `foot`).

I later discovered that I hadnt installed the Nouveu FOSS gpu drivers and my Nvidia GPU was the problem. Once installed the Nouveau drivers, GPU-enabled terminals run fine with a minimum CPU usage.
