### ISSUE TITLE
Kitty crashes when entering full screen on Wayland

### ISSUE THREAD

**Issue by lsunsi** [kovidgoyal/kitty#2906]
**Describe the bug**
When I force the display server to be wayland via `linux_display_server wayland`, kitty opens up all weird (borders look really off, just a white rectangle). I read that this is normal, but what I think might not be normal is that entering full screen crashes the whole app.

**To Reproduce**
1. Boot up kitty forcing wayland as the display server.
2. Try to enter full screen.
3. It just crashes.

**Expected behavior**
Enters full screen and keeps working.

kitty 0.18.0 created by Kovid Goyal
Linux fedora 5.7.11-200.fc32.x86_64 #1 SMP Wed Jul 29 17:15:52 UTC 2020 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: /home/lsunsi/.config/kitty/kitty.conf
Your Wayland compositor does not support server side window decorations, disabling Wayland. You can force Wayland support using the linux_display_server option in kitty.conf See https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html for more information.
Running under: X11

Config options different from defaults:
cursor_text_color       None
font_family             Fira Code
font_size               12.0
foreground              Color(red=248, green=248, blue=242)
inactive_tab_background Color(red=98, green=114, blue=164)
inactive_tab_foreground Color(red=40, green=42, blue=54)
linux_display_server wayland
selection_background    Color(red=248, green=248, blue=242)
selection_foreground    Color(red=68, green=71, blue=90)
sync_to_monitor         False
tab_bar_edge            1
url_color               Color(red=255, green=184, blue=108)
Changed shortcuts:
	shift+control+t KeyAction(func='new_tab_with_cwd', args=())
```

**Comment by kovidgoyal** [comment]
Also cannot reproduce. No weird rectangles, and no crashes. Judging from
your other bug report this is almost certainly something specific to
your system, probably your GPU drivers. Post the backtrace from the
crash, I will take a look, though I would be very surprised if the crash
is happening in kitty code.

**Comment by lsunsi** [comment]
@kovidgoyal It logs `[221 12:07:33.256993] [glfw error 65544]: Wayland: fatal display error: Invalid argument` after I try to enter full screen. Does this say anything to you?

**Comment by kovidgoyal** [comment]
That error just means talking to the wayland compositor failed. See
wl_window.c
