### ISSUE TITLE
Documentation for version field of remote control protocol is incorrect.

### ISSUE THREAD

**Issue by anicolao** [kovidgoyal/kitty#2911]
**Describe the bug**
The documentation https://sw.kovidgoyal.net/kitty/rc_protocol.html says that this is the form of the JSON payload for remote control:

```
{
    'cmd': "command name",
    'version': "kitty version",
    'no_response': Optional Boolean,
    'payload': <Optional JSON object>,
}
```

But it contains at least two problems: the version is an array, and the properties need to be double quoted.

**To Reproduce**
Here is a JSON payload that will work to create a new OS window:
```
{"cmd":"new-window","version":[0,18,2],"payload":{"window_type": "os"},"no_response": true}
```

To reproduce, try it with single quotes around "cmd" or with "0.18.2" as the version string, both of which seem to be implied more correct by the documentation.

Here is a trivial script to test with:
```
#!/bin/bash
echo -en "\033P@kitty-cmd"
cat - <<\EOF
{"cmd":"new-window","version":[0,18,2],"payload":{"window_type": "os"},"no_response": true}
EOF
echo -en "\033\\"
```

**Expected behavior**
Either the documentation could be updated or the code. Seems like a documentation bug to me.

**Comment by anicolao** [comment]
Thanks for fixing the version spec. I also still think that " are required by kitty's JSON parser, rather than ' around the attribute names.

**Comment by kovidgoyal** [comment]
Oh yeah, forgot that
