### ISSUE TITLE
Please consider adding escape sequences to resize OS Windows

### ISSUE THREAD

**Issue by anicolao** [kovidgoyal/kitty#2914]
**Is your feature request related to a problem? Please describe.**
It is difficult to control the size and position of OS Windows.

**Describe the solution you'd like**
Escape sequences to move and/or resize OS windows would be great.

**Describe alternatives you've considered**
Currently, I work around this by closing OS windows and re-opening them with command line arguments to set the size of the window. This requires an extra level of indirection over the remote protocol as remote launch also doesn't support setting size or position, so the remote protocol has to be used to launch `kitty` locally which then launches the window at the correct size but still the wrong position. I have not found any workaround to set the OS window position.

**Comment by kovidgoyal** [comment]
Sorry, no. Window placement is the responsibility of the window manager.
Use --class and setup rules in the window manager for it. Some window
managers such as tiling WMs and Wayland dont even allow changing window
sizes in application code.

**Comment by anicolao** [comment]
`--class` is not supported on my platform (Mac OS X).

**Comment by kovidgoyal** [comment]
Ah, yes, macOS, use a hammerspoon script to run and resize kitty,
windows ids are available to the programs running inside kitty as the
env var WINDOWID

**Comment by anicolao** [comment]
Ah! I will look into that. Meanwhile I also found an applescript answer at https://raw.githubusercontent.com/andrewgho/applescript/master/movewin which can be executed like this:
```
#!/bin/bash
ID=$(uuidgen)
kitty @ set-window-title $ID
/tmp/movewin $ID 10 10 500 300
```
but I'm guessing hammerspoon will work out better once I figure out what it is.
