### ISSUE TITLE
if background is transparent and a color matches background color then the color is transparent as well

### ISSUE THREAD

**Issue by mighty9245** [kovidgoyal/kitty#2917]
to be honest i have no idea how to name this issue properly because i can't describe it in a few words.

an excerpt from my configuration file:
```
background           #212121

background_opacity   0.7

color0               #212121
color8               #212121
```

as you can see there is background opacity and `color0` and `color8` match background color. in this case if i try to use `color0` or `color8` as background color for some text it'll be transparent:
![image](https://user-images.githubusercontent.com/52252283/89943581-202ee180-dc27-11ea-8b54-d999930b0dfc.png)

if i change these colors a little and set them to `#212122` just not to match background color then everything works as expected:
![image](https://user-images.githubusercontent.com/52252283/89943692-48b6db80-dc27-11ea-9c65-e4cd46c311fc.png)

this happens only to background colors, not foreground

```
woebook:~$ kitty --version
kitty 0.18.3 created by Kovid Goyal
```

hmu if you need any additional info

**Comment by kovidgoyal** [comment]
This is by design. Without it, you get sub-optimal results, like
applications that manually fill cells with the background color and
therefore should be transparent not being transparent. An example fo
this is alsamixer. See 2045055ae37eddf05aaa4c200c5552023d07cb8d

**Comment by Hendrikto** [comment]
Maybe this isn't the right place to ask, but it's the closest to my question I found.

Is it possible to make the foreground transparent? Even if the foreground matches the background color, it is simply drawn in that color, instead of being transparent.
