### ISSUE TITLE
Long pressing keys doesn't work

### ISSUE THREAD

**Issue by oddcoder** [kovidgoyal/kitty#292]
I hit an arrow inside vim, then hold it  and it doesn't keep moving in that direction, is there a way to make this work ?

**Comment by kovidgoyal** [comment]
Works for me. Make sure you are not using the wayland build, glfw on wayland does not support auto repeat of keys.

**Comment by myfreeweb** [comment]
GLFW on Wayland should support it now: https://github.com/glfw/glfw/pull/1210 please update the bundled copy of GLFW!

**Comment by kovidgoyal** [comment]
Works for me on my wayland system. Indeed, I was the one that tested the code in glfw in the first place https://github.com/glfw/glfw/issues/1108

**Comment by kovidgoyal** [comment]
Apparently, there was an additional regression introduced after I tested the code. See  https://github.com/glfw/glfw/issues/1108
