### ISSUE TITLE
Consider adding 'exec' in addition to 'launch'

### ISSUE THREAD

**Issue by anicolao** [kovidgoyal/kitty#2921]
**Is your feature request related to a problem? Please describe.**
In order to remote control window size, I have to run a script on the local host from within my SSH session. This is currently accomplished with `launch` which executes a `kitty -1 <resize script>` but this creates a pretty ugly flash on the local console.

**Describe the solution you'd like**
An option to just exec without starting a window, or alternately an option to delay window display so if the child process dies fast enough that the window is never visible, would create the seamless effect I'd like.

**Describe alternatives you've considered**
The best alternative I've come up with is to start a sacrificial window that I can target with --match and then minimize, so that kitty will run the exec without it being visible on my main screen as long as I don't accidentally close the extra terminal.

**Comment by kovidgoyal** [comment]
--type=background

https://sw.kovidgoyal.net/kitty/launch.html#cmdoption-launch-type

**Comment by anicolao** [comment]
Ah I didn't understand this option to have the desired effect, works great, thanks.
