### ISSUE TITLE
Support signing and/or encryption on the remote channel

### ISSUE THREAD

**Issue by anicolao** [kovidgoyal/kitty#2922]
**Is your feature request related to a problem? Please describe.**
I'm using remote control to enable pair programming with other shell users, but it's exceedingly dangerous as anyone can execute anything as anyone.

**Describe the solution you'd like**
Remote control should be able to take a list of public keys and validate that each incoming request is signed with the corresponding private key before accepting it.

**Describe alternatives you've considered**
This could be done more flexibly by enabling an arbitrary decoder on the remote control command. In such an implementation, the remote control command could be something like '{"cmd": "decode", "payload": "encoded string"} and the receiving kitty could have configuration for the 'decoder' which would be an arbitrary program to decode the encoded string, which would then be fed back into remote control for execution. So the extra decode thunk could do anything, not just validate the incoming data. This puts the security firmly in the hands of the user and provides arbitrarily powerful additional functionality to remote control, as the decode program could also implement extensions to the remote control protocol if desired. Of course, in such an option all other remote commands would need to be disabled, so remote control would be either 'on' or 'off' or 'mediated'.

**Comment by kovidgoyal** [comment]
Seems way to complicated to me. Just allow remote control only on a
local unix or tcp socket. And if you need programs running on a remote
host to access it, forward it via SSH or a similar service, inserting
whatever authentication mechanism you like for it.

**Comment by anicolao** [comment]
It is all running over ssh; multiple developers connected into a common container for their environment that they are collaborating on.

However each person is ssh'ing in from a computer running kitty. Unless they take the time to make a container on their remote system to sandbox kitty itself, they are vulnerable to everyone else in the shared session. The fact that everyone has an encrypted channel to the shared session does nothing to protect them from the others; and having to have every user who needs to collaborate figure out how to sandbox kitty for themselves seems unfortunate at best. Minimally kitty has to talk to everyone's window manager since kitty itself won't do window management operations like sizing or positioning windows; and once I can do that the attack surface is vast.

**Comment by kovidgoyal** [comment]
Set allow_remote_control in kitty.conf to only allow connections from a
socket. Forwrd the socket to the container wrapping it in whatever
authentication you like, and use it for control in the container.

**Comment by anicolao** [comment]
Yes, it's possible to do that way, I will try to script it up. On the remote host, -R port forwarding can take a port back to the local host. On the localhost `socat` can be used to take the TCP channel and write it to the kitty socket. The local Kitty can listen only on the socket. Between the socket that listens for TCP and the real kitty socket there could be arbitrary layers of socat with other programs to transform the input stream.
