### ISSUE TITLE
Please add Chinese input support！

### ISSUE THREAD

**Issue by KyleJKC** [kovidgoyal/kitty#2924]
**Is your feature request related to a problem? Please describe.**

Hello, I am a Chinese, so If my grammar is wrong, please forgive me
Here is my problem: I need input Chinese in my terminal, but kitty don't support it, I tried a lot of way, but they didn't working.
Kitty is the **BEST** terminal emulator I've ever seen, so I hope you can add this feature, thanks a lot !!!!! 

**Describe the solution you'd like**
I can type Chinese in Kitty

**Describe alternatives you've considered**
emm, I think this cannot be replaced, input Chinese is very important for me

**Additional context**
N/A

THANKS A LOT !!

**Comment by kovidgoyal** [comment]
kitty already supports chinese input, using iBus on Linux and macOS
native IM functionality.

**Comment by KyleJKC** [comment]
OK,thanks!

**Comment by Freed-Wu** [comment]
sorry, I use ibus-libpinyin and kitty 0.19.3, but cannot input any Asian CJK character. Is it need any special configuration?

**Comment by kovidgoyal** [comment]
set GLFW_IM_MODULE=ibus

**Comment by iysheng** [comment]
> kitty already supports chinese input, using iBus on Linux and macOS native IM functionality.

I installed kitty 0.29.2 on fedora 38, and with fcitx5 input method. But I can't input chinese with kitty, I wonder only ibus support with chinese input now in kitty ?

**Comment by kovidgoyal** [comment]
On Wed, Aug 06, 2025 at 06:23:40PM -0700, Yang sheng wrote:
> iysheng left a comment (kovidgoyal/kitty#2924)
>
> > kitty already supports chinese input, using iBus on Linux and macOS native IM functionality.
>
> I installed kitty 0.29.2 on fedora 38, and with fcitx5 input method. But I can't input chinese with kitty, I wonder only ibus support with chinese input now in kitty ?

You need to use wayland and an up to date version of kitty and fcitx5.
