### ISSUE TITLE
Question: compatibility option copy_on_select with vim option set mouse=a

### ISSUE THREAD

**Issue by shprotru** [kovidgoyal/kitty#2925]
**Is your feature request related to a problem? Please describe.**
Compatibility on `kitty` option `copy_on_select` with `vim` option `set mouse=a`, if you enable both `copy_on_select` feature will not work.

**Describe the solution you'd like**
Suggestion: add a modifier button(shift for example) to make `copy_on_select` compatible with vim `set mouse=a` option.

If this is possible, please update `FAQ`, `copy_on_select` section on vim `set mouse=a` option.

**Comment by kovidgoyal** [comment]
There already is: https://sw.kovidgoyal.net/kitty/#mouse-features

**Comment by shprotru** [comment]
`terminal_select_modifiers shift` works great! But if you do this:
```
copy_on_select yes
terminal_select_modifiers shift
```
then launch vim with `set mouse=a` everything works as expected, but if you launch vim just inside tmux - common vim selection(without kitty pressing) will look laggy, is way to avoid this or ticket on this?

**Comment by kovidgoyal** [comment]
Yeah, just dont use tmux.

**Comment by shprotru** [comment]
alternatives? screen?

**Comment by kovidgoyal** [comment]
Alternatives for what? kitty has all tmux functionality natively with
the exception of remote persistence, for which better solutions exist,
see #391

**Comment by trygveaa** [comment]
@shprotru: You can fix this by setting `ttymouse=sgr` in vim.

**Comment by shprotru** [comment]
@trygveaa wow! Works, like a charm! Thank you very much!
