### ISSUE TITLE
Home/End keys do not work in NeoVim when using Tmux

### ISSUE THREAD

**Issue by Frederick888** [kovidgoyal/kitty#2926]
**Describe the bug**
Home/End keys do not work in NeoVim when using Tmux.

This happens only to the combination of Kitty + Tmux + NeoVim. Without touching any configuration, it works all well if I use iTerm 2 or Alacritty. To be honest I've got no idea who's fault it is at the moment but since it's producible only when using Kitty so here the ticket is. Sorry if it's actually Tmux/NeoVim's problem.

Here are a few debug commands I ran in Kitty. They look exactly the same as what I got from iTerm 2/Alacritty.

```sh
# outside tmux
$ echo $TERM
xterm-kitty
$ cat -v
^[[H^[[F^C
$ tput home | cat -v
^[[H%
$ tput khome | cat -v
^[OH%

# inside tmux
$ echo $TERM
screen-256color
$ cat -v
^[[1~^[[4~^C
$ tput home | cat -v
^[[H%
$ tput khome | cat -v
^[[1~% 
```

I also tried putting `term xterm-256color` in Kitty's configuration, but still encountered the same problem. However, I noticed that after setting `term xterm-256color`, if I launch Tmux in iTerm2/Alacritty, then attach to it in Kitty, the problem's just magically gone.

**To Reproduce**
1. Start Kitty
2. `tmux` to start a new Tmux server & session
3. `nvim`
4. Home/End don't work

**Expected behavior**
Home/End keys work normally in NeoVim

**Environment details**
OS: macOS 10.15.6
Tmux: 3.1b
NeoVim: 0.4.4
Zsh: 5.8

```
kitty 0.18.3 created by Kovid Goyal
Darwin MAC-FREDERICK 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.6 BuildVersion:	19G2021
Loaded config files: /Users/frederick/.config/kitty/kitty.conf

Config options different from defaults:
background                         Color(red=18, green=18, blue=18)
background_opacity                 0.8
color0                             Color(red=18, green=18, blue=18)
color1                             Color(red=250, green=37, blue=115)
color10                            Color(red=176, green=224, blue=94)
color11                            Color(red=254, green=242, blue=108)
color12                            Color(red=0, green=175, blue=255)
color13                            Color(red=175, green=135, blue=255)
color14                            Color(red=80, green=205, blue=254)
color2                             Color(red=151, green=225, blue=35)
color3                             Color(red=223, green=212, blue=96)
color4                             Color(red=15, green=127, blue=207)
color5                             Color(red=135, green=0, blue=255)
color6                             Color(red=66, green=167, blue=207)
color7                             Color(red=187, green=187, blue=187)
color8                             Color(red=84, green=84, blue=84)
color9                             Color(red=245, green=102, blue=156)
copy_on_select                     clipboard
cursor                             Color(red=187, green=187, blue=187)
env                                {'SHELL': '/usr/local/bin/zsh'}
font_family                        BitstreamVeraSansMono Nerd Hybrid Font Mono Roman
font_size                          14.0
foreground                         Color(red=187, green=187, blue=187)
initial_window_height              (900, 'px')
initial_window_width               (1440, 'px')
macos_quit_when_last_window_closed True
macos_traditional_fullscreen       True
selection_background               Color(red=180, green=213, blue=255)
selection_foreground               Color(red=18, green=18, blue=18)
shell                              /usr/local/bin/zsh --login
strip_trailing_spaces              always
symbol_map                         {(9728, 131071): 'BitstreamVeraSansMono Nerd Hybrid Font Mono Roman'}
```

**Additional context**
The problem can be reproduced with `kitty --config NONE`, `nvim -u NONE` and Tmux without any special configuration.

**Comment by kovidgoyal** [comment]
Dont use tmux, or if you must use it, please report issues caused by it on
its bug tracker.

**Comment by Frederick888** [comment]
@kovidgoyal I actually just somehow solved the problem. Kitty's FAQ doc gave me the hint. I created `$HOME/.terminfo` then linked Kitty and Homebrew ncurses'es all relevant terminfo files into it. Finally after setting `export TERMINFO="$HOME/.terminfo"` in `.zshrc` and restarting Kitty everything's fine now.

**Comment by Sleepful** [comment]
```
# key codes necessary when using nvim + tmux + kitty
map home send_text all \x1b[7~
map end send_text all \x1b[8~
```
Basically you want to use `rxtv` codes instead of the `xterm-vt220` which kitty uses by default.
https://invisible-island.net/xterm/xterm-function-keys.html
