### ISSUE TITLE
Shift-Down key generates Shift-Up keycode in tmux

### ISSUE THREAD

**Issue by bbktsk** [kovidgoyal/kitty#2928]
**Describe the bug**
I'm running `kitty` on Ubuntu 20.04 laptop, `TERM=xterm-kitty`, connect using ssh to an Ubuntu 18.04 box (still `TERM=xterm-kitty`), run `tmux` there. Inside tmux I have `TERM=tmux-256color` (as expected. If I do `cat` there and press Shift-Up and Shift-Down, I get this:
```
[inside tmux on remote host] $ cat
^[[1;2A^[[1;2A
```
ie, the same keycode generated for both Shift-Up and Shift-Down.

Doing the same thing directly on the remote box (without tmux) and in the local shell works as expected:
```
[remote host] $ cat
^[[1;2A^[[1;2B
```

If set `TERM=xterm-256color` on the remote host before starting tmux and the do `cat` again inside the tmux, it works and I get different keycodes for Shift-Up and Shift-Down .

Non-shifted Up and Down works as expected.

**To Reproduce**
1. start `kitty`
2. ssh to a remote machine
3. start tmux there
4. run `cat` and press Shift-Up, then Shift-Down. Instead of two different keycodes, I get two same ones: `^[[1;2A^[[1;2A`

**Expected behavior**
I should get two different keycodes, `^[[1;2A^[[1;2B`

**Environment details**
Ubuntu 20.04 on workstation, Ubuntu 18.04 on the remote machine.
X11, i3wm
kitty 0.15.0
tmux 3.0a-2 on remote machine without any custom config
terminfo files for xterm-kitty are the same on both workstation and remote machine.

```
Output of kitty --debug-config
$ kitty --debug-config
kitty 0.15.0 created by Kovid Goyal
Linux bkpad 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/bkoutsky/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background   Color(red=248, green=248, blue=242)
background              Color(red=11, green=13, blue=15)
color1                  Color(red=255, green=149, blue=128)
color10                 Color(red=162, green=255, blue=153)
color11                 Color(red=255, green=255, blue=153)
color12                 Color(red=170, green=153, blue=255)
color13                 Color(red=255, green=153, blue=204)
color14                 Color(red=153, green=255, blue=238)
color2                  Color(red=138, green=255, blue=128)
color3                  Color(red=255, green=255, blue=128)
color4                  Color(red=149, green=128, blue=255)
color5                  Color(red=255, green=128, blue=191)
color6                  Color(red=128, green=255, blue=234)
color7                  Color(red=248, green=248, blue=242)
color8                  Color(red=76, green=89, blue=103)
color9                  Color(red=255, green=170, blue=153)
cursor                  Color(red=112, green=140, blue=169)
cursor_text_color       Color(red=255, green=255, blue=255)
enable_audio_bell       False
font_family             Iosevka Fixed Curly
font_size               12.0
foreground              Color(red=248, green=248, blue=242)
inactive_tab_background Color(red=76, green=89, blue=103)
inactive_tab_foreground Color(red=11, green=13, blue=15)
kitty_mod               12
selection_background    Color(red=65, green=77, blue=88)
update_check_interval   0.0
url_color               Color(red=0, green=92, blue=187)
visual_bell_duration    0.1
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` : Did that, same behavior.

**Comment by kovidgoyal** [comment]
Dont use tmux, and if you must, then report issues caused by it on its
bug tracker.

**Comment by bbktsk** [comment]
I d not think this is an tmux issue. If I try exactly the same thing using `xterm` or `gnome-terminal`, it works as expected.
