### ISSUE TITLE
Single width glyphs that occupy 2 columns (succeeded by U+FE0F) mess up command lines/vim/etc

### ISSUE THREAD

**Issue by Frederick888** [kovidgoyal/kitty#2929]
**Describe the bug**
For example ✏ (U+270F), if I copy it with U+FE0F, paste in Bash/Zsh/etc, and then move around the cursor and give it some random inputs, the command line just goes berserk.

**To Reproduce**
1. `python -c 'print(chr(0x270f)+chr(0xfe0f));'` and copy the printed pencil glyph
2. `bash`
3. Paste the glyph and then give it some random input
4. The command line behaves quite weirdly, especially when I type things from the middle of the character. In Vim when when prompt's got such a glyph, <kbd>Ctrl</kbd>+<kbd>U</kbd> clears out 1 more character than expected (e.g. if prompt is '✏ :', <kbd>Ctrl</kbd>+<kbd>U</kbd> clears out the `:` as well *visually*)

**Expected behavior**
How iTerm 2 handles it is not perfect but causes much fewer glitches:

![iTerm](https://user-images.githubusercontent.com/4507647/90705881-46afe500-e2d7-11ea-82e8-7424fe3705c1.gif)

They basically render such code points as double-column colourful glyphs, but leaves the responsibility of adding spaces after these glyphs to whoever use them. I'm not sure whether this is the 'standard' way or not but generally it provides a better experience.

**Screenshots**
![Kitty](https://user-images.githubusercontent.com/4507647/90705890-4d3e5c80-e2d7-11ea-8ada-961122665aaa.gif)

**Environment details**
OS: macOS 10.15.6

```
kitty 0.18.3 created by Kovid Goyal
Darwin MAC-FREDERICK 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:        10.15.6 BuildVersion:   19G2021
Loaded config files: /Users/frederick/.config/kitty/kitty.conf

Config options different from defaults:
background                         Color(red=18, green=18, blue=18)
background_opacity                 0.8
color0                             Color(red=18, green=18, blue=18)
color1                             Color(red=250, green=37, blue=115)
color10                            Color(red=176, green=224, blue=94)
color11                            Color(red=254, green=242, blue=108)
color12                            Color(red=0, green=175, blue=255)
color13                            Color(red=175, green=135, blue=255)
color14                            Color(red=80, green=205, blue=254)
color2                             Color(red=151, green=225, blue=35)
color3                             Color(red=223, green=212, blue=96)
color4                             Color(red=15, green=127, blue=207)
color5                             Color(red=135, green=0, blue=255)
color6                             Color(red=66, green=167, blue=207)
color7                             Color(red=187, green=187, blue=187)
color8                             Color(red=84, green=84, blue=84)
color9                             Color(red=245, green=102, blue=156)
copy_on_select                     clipboard
cursor                             Color(red=187, green=187, blue=187)
env                                {'SHELL': '/usr/local/bin/zsh'}
font_family                        BitstreamVeraSansMono Nerd Hybrid Font Mono
font_size                          14.0
foreground                         Color(red=187, green=187, blue=187)
initial_window_height              (900, 'px')
initial_window_width               (1440, 'px')
macos_quit_when_last_window_closed True
macos_traditional_fullscreen       True
selection_background               Color(red=180, green=213, blue=255)
selection_foreground               Color(red=18, green=18, blue=18)
shell                              /usr/local/bin/zsh --login
strip_trailing_spaces              always
```

**Additional context**
This issue can be reproduced using `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Such a glyph has to be rendered in two columns, which is what kitty
does. It does not add any spaces after it. vim and bash need to
learn how to handle U+FE0F and U+FE0E for that matter.

**Comment by Frederick888** [comment]
@kovidgoyal Sorry if it's a stupid question, but may I know if iTerm's approach any 'non-standard'? U+FE0F in iTerm still causes preceding single-column dingbats to be rendered in 2 columns, but for example if I type from the 'middle' of such glyphs, they just overlap instead of somehow getting hidden like in Kitty (in my gif when I moved cursor to the middle of the pencil glyph, there was a short 'pause' and I was actually typing).

**Comment by kovidgoyal** [comment]
You shouldn't be able to move your cursor into the middle of such glyphs
just like you cannot for "normal" emoji. That you can is a bug in
vim/shell and should be reported there. It is not the terminal emulators
job to second guess where the application tells it to move the cursor,
that way lies chaos. Try moving your cursor in bash over a normal emoji
it will not allow you to be in the middle. bash needs to recognize
U+FEOF and do the same with the pencil emoji.

**Comment by Frederick888** [comment]
@kovidgoyal Cool, thanks for the explanation!

**Comment by greneholt** [comment]
There seem to be some bugs in both the Linux and Darwin kernel's pty line discipline with regard to wide unicode characters as well. If you run `cat` and paste some wide characters like 🙌 into the input, it will not erase the entire line if you hold backspace.

**Comment by kovidgoyal** [comment]
Yes, kernels have pretty pathetic unicode support, dont expect that to
change anytime soon.
