### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by slavaGanzin** [kovidgoyal/kitty#293]
Hello again, Kovid.

I found that kitty uses 40% of one core to draw htop. But all gets even worse(till 400%) when i just move mouse over it.

For example urxvt never exceeds 2-3% of one core.

![out](https://user-images.githubusercontent.com/1011721/35338818-3034b69e-011f-11e8-881b-ceff8f8e2acc.gif)

Kitty version: ```kitty 0.7.0 created by Kovid Goyal``` compiled from master branch

Inxi:
```
 sudo inxi -v3
System:    Host: 7 Kernel: 4.14.14-1-ARCH x86_64 bits: 64 gcc: 7.2.1 Desktop: Awesome 4.2 Distro: Arch Linux
Machine:   Device: laptop System: ASUSTeK product: X510UNR v: 1.0 serial: HAN0CX264546437
           Mobo: ASUSTeK model: X510UNR v: 1.0 serial: QCCXKG20D74301415
           UEFI: American Megatrends v: X510UNR.300 date: 08/07/2017
Battery    BAT0: charge: 17.2 Wh 41.3% condition: 41.7/42.1 Wh (99%) model: ASUSTeK ASUS status: Charging
CPU:       Quad core Intel Core i5-8250U (-MT-MCP-) arch: Kaby Lake rev.10 cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 14404
           clock speeds: max: 3400 MHz 1: 800 MHz 2: 800 MHz 3: 800 MHz 4: 800 MHz 5: 800 MHz 6: 800 MHz
           7: 800 MHz 8: 800 MHz
Graphics:  Card-1: Intel Device 5917 bus-ID: 00:02.0
           Card-2: NVIDIA GP108M [GeForce MX150] bus-ID: 01:00.0
           Display Server: X.Org 1.19.6 driver: intel Resolution: 1920x1080@60.03hz
           OpenGL: renderer: llvmpipe (LLVM 5.0, 256 bits) version: 3.3 Mesa 17.3.2 Direct Render: Yes
Network:   Card: Intel Wireless 8265 / 8275 driver: iwlwifi bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: 44:03:2c:ea:c8:c9
Drives:    HDD Total Size: 256.1GB (32.9% used)
           ID-1: model: TOSHIBA_THNSNK25
Info:      Processes: 183 Uptime: 1:01 Memory: 3896.0/7863.6MB Init: systemd Gcc sys: 7.2.1
           Client: Shell (sudo) inxi: 2.3.56 
```

**Comment by kovidgoyal** [comment]
Moving the mouse will indeed cause high CPU usage because kitty is looking for URLs to underline. But with no mouse movement CPU usage on my system with htop is under 1%. Try running it with default config and see if that makes a difference.

**Comment by kovidgoyal** [comment]
FYI you can run kitty with default config easily using

kitty --config NONE

**Comment by kovidgoyal** [comment]
no followup

**Comment by slavaGanzin** [comment]
Same with default config:
![peek 2018-01-26 15-22](https://user-images.githubusercontent.com/1011721/35443930-0e4c10b0-02ad-11e8-9c4e-3d9339cca04e.gif)

**Comment by slavaGanzin** [comment]
@koekeishiya reopen, please

**Comment by kovidgoyal** [comment]
Hmm well this is definitely something specific to your system. The mouse handler runs in a single thread, there's no way it can use more than 100% CPU. That tells me that the CPU usage is being caused by something outside kitty, most likely the OpenGL driver on your system. You can try using the technique described in the README (in the performance section) to see which function calls have the highest CPU load.

**Comment by bradlyatc** [comment]
Looks like you're using software renderer.  OpenGL: renderer: llvmpipe (LLVM 5.0, 256 bits).

**Comment by kovidgoyal** [comment]
@bradlyatc good catch, I was fooled by the Direct rendering: Yes

Indeed, with a software OpenGL driver, kitty performance will fall off a cliff.
