### ISSUE TITLE
Alt-# in bash doesn't insert a comment

### ISSUE THREAD

**Issue by rory** [kovidgoyal/kitty#2930]
**Describe the bug**
<kbd>Alt</kbd>-<kbd>#</kbd> in bash doesn't insert a comment
 
**To Reproduce**
1. Open Kitty v0.18.3 and bash v4.4.20
2. Type something without pressing enter (e.g. `ls`)
3. Press <kbd>Alt</kbd>-<kbd>#</kbd>

**Expected behavior**
The line will be replaces with `#ls` and you'll go to a new line. It's as if you pressed <kbd>Home</kbd>, <kbd>#</kbd>, <kbd>Enter</kbd>

**Environment details**
Ubuntu Linux 18.04, Kitty v0.18.3 and bash v4.4.20

Output of kitty --debug-config
```
kitty 0.18.3 (4b0724530e) created by Kovid Goyal
Linux robinson 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64
Ubuntu 18.04.5 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
Loaded config files: /home/rory/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control y
background           Color(red=255, green=255, blue=221)
cursor               Color(red=0, green=0, blue=0)
foreground           Color(red=0, green=0, blue=0)
selection_background Color(red=0, green=0, blue=0)
selection_foreground Color(red=255, green=255, blue=255)
tab_bar_edge         1
Added shortcuts:
	 shift+page_up KeyAction(func='scroll_page_up', args=())
	 shift+page_down KeyAction(func='scroll_page_down', args=())
	 control+page_up KeyAction(func='previous_tab', args=())
	 control+page_down KeyAction(func='next_tab', args=())

```

**Additional context**
With `kitty --config NONE` the bug still happens.

I believe this feature is from `readline`, and is the `insert-comment` command, and they refer to the keycombo as <kbd>Meta</kbd>-<kbd>#</kbd> (aka <kbd>M</kbd>-<kbd>#</kbd>)

This works on `gnome-terminal`.

**Comment by kovidgoyal** [comment]
works for me, pressing alt+shift+3 comments the current line bash.

If you have a non-US keyboard with a dedicated key for # you might need
to map it specially in kitty.conf, use --debug-keyboard and see 
https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts
and
https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Send-arbitrary-text-on-key-presses

you will need to map it to \x1b#

**Comment by rory** [comment]
Thanks, that was it. I have a [UK keyboard layout](https://en.wikipedia.org/wiki/QWERTY#United_Kingdom_(Extended)_Layout), with <kbd>#</kbd> being to the left of the <kbd>Enter</kbd> key

For anyone else with this problem, I added this to my `~/.config/kitty/kitty.conf`:

    map alt+# send_text all \x1b#
