### ISSUE TITLE
[Bug] OSX tmux and tmuxp trigger yields terminfo error (but unclear where terminfo is in OX package/how to fix despite FAQ)

### ISSUE THREAD

**Issue by wakatara** [kovidgoyal/kitty#2932]
**Describe the bug**

After installing kitty (which I use on my linux system) on OSX 10.15.6 via homebrew, trying to use `tmuxp load ~/.tmuxp/e.yml` to load my standard tmux config and setup gives the following error:

```
open terminal failed: missing or unsuitable terminal: xterm-kitty
```
when launching `tmux` and when you use `tmuxp`, variation on the same though python stack dump:

```
 λ  ~ tmuxp load ~/.tmuxp/m.yaml
M is already running. Attach? [Y/n]: Y
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 8, in <module>
    sys.exit(cli.cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tmuxp/cli.py", line 814, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/local/lib/python3.8/site-packages/tmuxp/cli.py", line 527, in load_workspace
    _reattach(builder.session)
  File "/usr/local/lib/python3.8/site-packages/tmuxp/cli.py", line 393, in _reattach
    session.attach_session()
  File "/usr/local/lib/python3.8/site-packages/libtmux/session.py", line 112, in attach_session
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['open terminal failed: missing or unsuitable terminal: xterm-kitty']
```

I know this is related to the terminfo being set/not set but on POPOS or Arch normally the kitty-terminfo file is installed as part of the package. On OSX looking at the kitty.app/Contents directory, I am unsure where the terminfo may be.

note this is new because I am moving from iTerm2 to either kitty or alacritty to harmonize my config and workflow environments.

**To Reproduce**

1. `brew cask install kitty`
2. Launch kitty.app
3. fire up `tmux` or `tmuxp`
4. Produces error `open terminal failed: missing or unsuitable terminal: xterm-kitty`  (error slightly more elaborate with tmuxp since it launches python dump first, but same thing.).

I realize this is related to the [FAQ on ssh-ing and terminfo](https://sw.kovidgoyal.net/kitty/faq.html?highlight=terminfo#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer) but am unsure where the terminfo for OSX was installed/located in the bundle and normally in POPOS or Arch, the terminfo file is installed as a dependency. Currently echoing `$TERMINFO` comes up blank making me suspect it is missing cmpletely from the cask (homebrew is the command line OSX package manager, cask is for bundled .app apps rather than clis in case you're unfamiliar.). 

**Expected behavior**

Kitty launches tmux and my config normally.

**Screenshots**

Not necessary, though kitty looks nice with the nord.conf file and my fish Cousteau theme... =] 

**Environment details**

OS: OSX 10.15.6
shell: fish 3.1.2
Homebrew 2.4.13-39-g6df7420
Homebrew/homebrew-core (git revision ef74b3; last commit 2020-08-22)
Homebrew/homebrew-cask (git revision 8ec49f; last commit 2020-08-22)
kitty 0.18.3 created by Kovid Goyal

Output of kitty --debug-config
```
 λ ~ kitty --debug-config
kitty 0.18.3 created by Kovid Goyal
Darwin majid.lan 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.6 BuildVersion:	19G73
Loaded config files: /Users/daryl/.config/kitty/kitty.conf
[235 13:09:26.224516] Ignoring unknown config key: italic

Config options different from defaults:
background        Color(red=46, green=52, blue=64)
bold_font         Dank Mono Bold
color0            Color(red=59, green=66, blue=82)
color1            Color(red=191, green=97, blue=106)
color10           Color(red=163, green=190, blue=140)
color11           Color(red=235, green=203, blue=139)
color12           Color(red=129, green=161, blue=193)
color13           Color(red=180, green=142, blue=173)
color14           Color(red=143, green=188, blue=187)
color15           Color(red=236, green=239, blue=244)
color2            Color(red=163, green=190, blue=140)
color3            Color(red=235, green=203, blue=139)
color4            Color(red=129, green=161, blue=193)
color5            Color(red=180, green=142, blue=173)
color6            Color(red=136, green=192, blue=208)
color7            Color(red=229, green=233, blue=240)
color8            Color(red=76, green=86, blue=106)
color9            Color(red=191, green=97, blue=106)
cursor            Color(red=129, green=161, blue=193)
enable_audio_bell False
font_family       Dank Mono
font_size         13.5
foreground        Color(red=216, green=222, blue=233)
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Problem persists launching this way. Alacritty works normally installed similarly via cask (I kust prefer kitty tbh).

**Comment by indutny** [comment]
I'm getting exactly the same error when trying to start a new tmux session on a remote linux server through ssh. Would it make sense to reopen this issue?
