### ISSUE TITLE
make a kitten that changes font size based on terminal's width and height

### ISSUE THREAD

**Issue by wis** [kovidgoyal/kitty#2933]
**Is your feature request related to a problem? Please describe.**
No.
I want to make a kitten that changes font size automatically now I do it manually every time I open a terminal or change its size.

**Describe the solution you'd like**
a kitten that changes font-size setting based on terminal size

**Describe alternatives you've considered**
none that I can think of

is this possible to do with the kitten API?

**Comment by rickalex21** [comment]
Hello,

I'm looking to set the font for two monitors. My LG I want to increase the font and my other monitor
leave it with the default font. The problems are:

1. I can't resize with ctrl+shift+= when I use the watcher.
2. When I open on the big monitor and I close it then open on the small monitor it will open
in big font. However, when I close it and open another window it will open in the normal font as usual.

This is my watcher.py. If the width is bigger than 3800 increase the font.

```python
def on_resize(boss, window, data):
    width = data['new_geometry'].right
    lg  = 3800
    if width > lg:
        boss.set_font_size(50)
```

**Comment by Kody-Quintana** [comment]
Posting this here since this page was what I found when googling for this functionality.

I've expanded on the example wis made to have both auto-resizing and manual adjustment via the usual `ctrl+shift+equal` and `ctrl+shift+minus` key maps.

1. `~/.config/kitty/sessions/default`:
    ```
    launch --watcher ~/.config/kitty/kittens/autofontsize-watcher/main.py
    ```

1. `~/.config/kitty/kitty.conf`
    ```
    startup_session ~/.config/kitty/sessions/default
    map ctrl+shift+equal remote_control set-user-vars var:KITTY_ADJUST_FONT_SIZE_OFFSET=up
    map ctrl+shift+minus remote_control set-user-vars var:KITTY_ADJUST_FONT_SIZE_OFFSET=down
    ```

1. `~/.config/kitty/kittens/autofontsize-watcher/main.py`
    ```python
    def on_resize(boss, window, data=None):
        if getattr(boss, 'font_size_multiplier', None) is None:
            boss.font_size_multiplier = 0

        if data is None:
            data = boss.cached_geometry
        else:
            boss.cached_geometry = data

        fmax, fmin = 20, 8
        width = data['new_geometry'].right - data['new_geometry'].spaces.right

        # Still experimenting with the curve I like, but I printed the width and what
        # font size I wanted at different window geometry widths
        # and then plugged it into a calculator to fit this line
        new_font_size = (1288382 + (-1288374.287753) / (1 + (width / 4645727) ** 1.557926))

        if new_font_size < fmin:
            new_font_size = fmin
        elif new_font_size > fmax:
            new_font_size = fmax
        boss.set_font_size(new_font_size * (1 + (0.3 * boss.font_size_multiplier)))


    def on_set_user_var(boss, window, data):
        if getattr(boss, 'font_size_multiplier', None) is None:
            boss.font_size_multiplier = 0

        if data['key'] == 'var:KITTY_ADJUST_FONT_SIZE_OFFSET':
            value = data['value']
            if value == 'up':
                boss.font_size_multiplier += 1
            elif value == 'down':
                boss.font_size_multiplier -= 1

            on_resize(boss, window)
    ```

I launch new kitty windows via a [sxhkd](https://github.com/baskerville/sxhkd) keybind so I get a new session per kitty window, but I'd need to think of a way to get this working with a separate watcher per window if you open a new window with the built in key map
