### ISSUE TITLE
Keep the current directory when opening a new window

### ISSUE THREAD

**Issue by codic12** [kovidgoyal/kitty#2934]
**Is your feature request related to a problem? Please describe.**
Opening a new window goes back to your home folder, rather than using the same folder as the one you opened it from. If there's a way to configure this already, I can't find it, please share.

**Describe the solution you'd like**
An option for keeping the current directory when opening a new split/tab.

**Comment by SolitudeSF** [comment]
https://sw.kovidgoyal.net/kitty/launch.html

**Comment by codic12** [comment]
ahh, thanks.
