### ISSUE TITLE
vim rendering issue

### ISSUE THREAD

**Issue by sgon00** [kovidgoyal/kitty#2936]
OS: MX Linux KDE (Debian 10)
Vim version 8.1.1401

Hi, I am new to kitty and meeting vim rendering issue. You can see the gray bars/lines on the right hand side. I did try to find a solution before openning this issue, but no luck. 

The following screenshot is what it looks like in kitty:

![vim-kitty](https://user-images.githubusercontent.com/1555508/91173330-3ac98600-e710-11ea-80b4-cf511c5d370b.png)

The following screenshot is what it should look like:

![vim-expected](https://user-images.githubusercontent.com/1555508/91173348-44eb8480-e710-11ea-9917-3459d51ae6dd.png)

Thanks a lot for your help.

**Comment by trygveaa** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim

**Comment by sgon00** [comment]
@trygveaa Thanks a lot for the link. I missed that part. Closing the issue.
