### ISSUE TITLE
show window index for switching

### ISSUE THREAD

**Issue by thiefuniverse** [kovidgoyal/kitty#2938]
**Is your feature request related to a problem? Please describe.**
hi, when I try to jump to one window within one layout by first_window , second_window ... etc. I find that I can't show index in title for window. 

**Describe the solution you'd like**
I want to add index for title within window.

**Additional context**
you may understand me by this image.
![Snip20200827_3](https://user-images.githubusercontent.com/12184047/91438476-fcfa6800-e89d-11ea-9f60-43fa998f074c.png)

**Comment by kovidgoyal** [comment]
Not worth the effort for, patches welcome. Note that the numbers are
trivial to guess since they go from left to right and clockwise.
