### ISSUE TITLE
need help:mouse scroll and systemctl

### ISSUE THREAD

**Issue by fr233** [kovidgoyal/kitty#2939]
I have set 
PAGER=less --mouse
so that i can scroll down with mouse in 
$ systemctl list-unit-files (or other systemd command line tools)

that works with gnome-terminal / xterm / xfce-terminal / konsole / ....
,
but I notice that didn't work with kitty. 

I then set
PAGER=most
, now mouse scroll down works again.

Is it a problem of less ? or systemd ? or kitty ?
how to solve this problem? thanks.

**Comment by kovidgoyal** [comment]
Works fine for me both with --mouse and without, using

less --mouse setup.py

or

less setup.py

in the latter case kitty will send arrow key events, in the former it
will use whatever mouse reporting mode less asks for.

less version 551
kitty version 0.18.3

**Comment by fr233** [comment]
> Works fine for me both with --mouse and without, using
> 
> less --mouse setup.py
> 
> or
> 
> less setup.py
> 
> in the latter case kitty will send arrow key events, in the former it
> will use whatever mouse reporting mode less asks for.
> 
> less version 551
> kitty version 0.18.3

try $ systemctl -list-unit-files, that phenomenon only appear in command line tools of systemd

**Comment by trygveaa** [comment]
This is caused by kitty only sending scroll events to the application when the alternate screen is active.

You can set the environment variable `SYSTEMD_LESS` to something not including `X` to use the alternate screen (the default is `FRSXMK`, so e.g. `export SYSTEMD_LESS='FRSMK'`)

**Comment by kovidgoyal** [comment]
Then you should report the issue to them. They probably do some hackery
based on TERM variables. All I can tell you is kitty's
mouse protocol works fine, as evidenced by using less --mouse directly.

**Comment by fr233** [comment]
> This is caused by kitty only sending scroll events to the application when the alternate screen is active.
> 
> You can set the environment variable `SYSTEMD_LESS` to something not including `X` to use the alternate screen (the default is `FRSXMK`, so e.g. `export SYSTEMD_LESS='FRSMK'`)

thanks. 
Is this a design decison?

**Comment by fr233** [comment]
> Then you should report the issue to them. They probably do some hackery
> based on TERM variables. All I can tell you is kitty's
> mouse protocol works fine, as evidenced by using less --mouse directly.

yes.

**Comment by kovidgoyal** [comment]
wheel mouse events are used to scroll the scrollback buffer when not using the alternate screen.

**Comment by fr233** [comment]
> wheel mouse events are used to scroll the scrollback buffer when not using the alternate screen.

Oh I see.

**Comment by fr233** [comment]
I have tested your commit, It's works, but still a little mismatch with other terminals：

gnome-terminal：
$ less --mouse --wheel-lines=1 somefile   # scroll once down 1 line

kitty：
$ less --mouse --wheel-lines=1 somefile  # scroll once down 1 lines

but
gnome-terminal
$ less -X --mouse --wheel-lines=1 somefile  # scroll once down 1 lines

kitty：
$ less -X --mouse --wheel-lines=1 somefile  # scroll once down 5 lines

**Comment by kovidgoyal** [comment]
Should be fine now.
