### ISSUE TITLE
Shows a very simplistic terminal by default

### ISSUE THREAD

**Issue by InfiniteCoder** [kovidgoyal/kitty#294]
I'm not sure if this is an issue or its how its supposed to be, I get a very simple looking terminal.

![Screenshot of kitty](https://i.imgur.com/ZGZI7Hy.png)

If this is how it's supposed to be, what do I need to do to make it better looking?

**Comment by kovidgoyal** [comment]
A terminal by itself is a blank screen. What you see in it, depends on what programs you are running. Look at the screenshot on the front page for an example.

**Comment by InfiniteCoder** [comment]
I know that, I just thought it has some features like showing colors in prompt, or showing git branch in promt etc, by default 😅. Guess I have to set those things in shell instead.

**Comment by kovidgoyal** [comment]
All those features are functions of the shell, not the terminal emulator. The shell is an entirely separate program from the terminal emulator.
