### ISSUE TITLE
Extra unused spacing between window splits

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#2940]
I've found an issue with window splitting while using the latest version.
I've noticed extra unused spacing between splits that wasn't there in the previous version I was using.

So, I've done a little investigation and found that the bug was produced in version `0.17.3`.
To be more specific, the bug was generated by the following commit:
<pre>
commit  : c69b8870d29509332bcedff957a22377c642ee16
Author  : Kovid Goyal <kovid@kovidgoyal.net>
Date    : Sun Apr 19 09:36:26 2020 +0530
Message : Allow individually setting margins and padding for each edge (left, right, top, bottom)
</pre>

This is a pretty big commit with changes in multiple files, so I cannot offer more details, except for the following:

* `kitty.conf`
<pre>
enabled_layouts        Grid
window_border_width    2
draw_minimal_borders   yes
window_margin_width    0
placement_strategy     top-left
</pre>

* Machine
<pre>
MacBook Pro, 15in, Retina
macOS Mojave 10.14.6
</pre>

* Example of image that illustrates the reported issue:
<img width="1440" alt="bad" src="https://user-images.githubusercontent.com/7289591/91580394-b405ea80-e955-11ea-80ab-dfbc81b3d397.png">

* Example of image that illustrates the expected behavior:
<img width="1440" alt="good" src="https://user-images.githubusercontent.com/7289591/91580402-b6684480-e955-11ea-8e36-75471e135cbc.png">

Both images are produced from the `kitty.conf` provided above.

**Comment by kovidgoyal** [comment]
That's not unused spacing, its less than a cell width's worth, so it cannot be used. It's just distributed differently. It's possible placement strategy is no longer honored.

**Comment by kovidgoyal** [comment]
I tried it and I cannot reproduce, the active window border is flush left/top with the passive grid borders. Running kitty as:

```
kitty --config NONE -o enabled_layouts=Grid -o draw_minimal_borders=yes -o window_border_width=2 -o window_margin_width=0 -o placement_strategy=top-left
```

See attached screenshot:
![Screenshot_20200828_210628](https://user-images.githubusercontent.com/1308621/91585937-5c29ac80-e972-11ea-8023-928d6a8837fb.png)

Indeed, what version of kitty are you running? As in current kitty you will always have white borders between all slots in grid layout when using minimal borders.

**Comment by mihaicristiantanase** [comment]
I've ran the command you posted earlier and the spacing is still there. Please select the 2nd window (in your screenshot you've selected the 3rd one) to see the issue.
Here are the "before-and-after" screenshots:
* before
<img width="720" alt="working_version" src="https://user-images.githubusercontent.com/7289591/91596134-64cbb400-e96d-11ea-89d7-f71f31264fa5.png">

* after (latest version)
<img width="720" alt="latest_version" src="https://user-images.githubusercontent.com/7289591/91596139-66957780-e96d-11ea-863c-3c419b9d086d.png">

In previous versions, the empty space at the bottom of the 2nd window was not showing. 

At the moment, I'm using 0.18.3.

**Comment by kovidgoyal** [comment]
That's becuse in the before screenshot there happened to be no extra padding, now there is. Its not wasted space however, since it is shorter than a single cell, so it cannot be used.

**Comment by kovidgoyal** [comment]
Oh and you might be interested in: https://github.com/kovidgoyal/kitty/commit/7074f9f776c172a8a80647c1fbb0642b972598c4

**Comment by mihaicristiantanase** [comment]
I've make a built out of [7074f9f](https://github.com/kovidgoyal/kitty/commit/7074f9f776c172a8a80647c1fbb0642b972598c4) and the spacing is gone.

So, I'll wait for the next official release (assuming it will include this change).
Thank you for the info!
