### ISSUE TITLE
[Question] Fonts are not rendered as expected

### ISSUE THREAD

**Issue by subnut** [kovidgoyal/kitty#2944]
I am on `Arch Linux`
```
❯ kitty --version
kitty 0.18.3 created by Kovid Goyal
```

It is better if you see the screenshots. The image in the browser is [this](https://camo.githubusercontent.com/2fcf604967167347f15ca8be125d32b18db9bc28/687474703a2f2f692e696d6775722e636f6d2f476b496c38466e2e706e67) which is taken from [here](https://github.com/gruvbox-community/gruvbox#dark-mode). The font is clearly mentioned [here](https://github.com/gruvbox-community/gruvbox#attention) as `Fira Mono`, a part of [Fira](https://github.com/mozilla/Fira)
The font is correctly detected when `kitty list-fonts` and the terminal has been run by `kitty --detach -o font_family="Fira Mono Medium"`. I have adjusted the font till the Cursorline height matches the one in the picture. More details shall be provided if asked for.

![kitty_horizontal_1](https://user-images.githubusercontent.com/56714626/91667849-355fa780-eb25-11ea-9431-78511ddf6468.png)
![kitty_horizontal_2](https://user-images.githubusercontent.com/56714626/91667850-37296b00-eb25-11ea-8d27-2ce4ec5cd1a2.png)
![kitty_vertical](https://user-images.githubusercontent.com/56714626/91667852-385a9800-eb25-11ea-9169-20c2e9c10421.png)

I must be missing something. What might be it?

**Comment by kovidgoyal** [comment]
What is not as expected? Looks the same to me.

**Comment by subnut** [comment]
The letter spacing is more and the fonts are a little bit thinner in kitty when compared to the screenshot

> Looks the same to me

I am sorry for not being clearer, but in the third screenshot you can clearly see that the sentences' beginning `#` are aligned, but the end is not. It is most prominent when you look at the lines where the cursor is

@kovidgoyal I expected that the font rendered by kitty shall look exactly like the one in the picture

**Comment by kovidgoyal** [comment]
Sorry, but matching the font rendering of other applications is not a
design goal of kitty. Indeed given that kitty is a character cell based
display system, you will never get exactly identical rendering to any
non-charcell based rendering system.

**Comment by subnut** [comment]
Okay ..
Two (final) questions - 
 * You mean the application in the picture is not using charcells, ri8?
 * Are you aware of any terminal that does not use charcells?

**Comment by subnut** [comment]
For those coming from the future,
I managed to get (almost) the same rendering by using
```
adjust_line_height  99%
adjust_column_width 99%
```

Result -

![image](https://user-images.githubusercontent.com/56714626/94393092-c606c300-0177-11eb-98e0-efcbadeba9ea.png)

Also, it may be noted that the screenshot
that I was comparing kitty with is of 
iTerm2, as mentioned by morhertz [here](https://github.com/morhetz/gruvbox/issues/99#issuecomment-190535986)
