### ISSUE TITLE
save_cursor/restore_cursor escape sequences not working as expected

### ISSUE THREAD

**Issue by toazd** [kovidgoyal/kitty#2945]
**Describe the bug**
Neither of the following pairs of save/restore escape codes work as expected for me (Bash 5.0.18, builtin printf). Using either one of the restore saved cursor position escape codes after first saving a position always sends the cursor to 0,0 (top row, first column).
`\E7` and `\E8`
`\033[s` and `\033[u`

**To Reproduce**
I first noticed it using exactly (save cursor position)
`printf '%s\033[s' "Comparing files"` or `printf '%s\E7' "Comparing files"`
and lower down in the script (restore cursor position)
`printf '\033[u%s' "... ${progress_percent}%"` or `printf '\E8%s' "... ${progress_percent}%"`

The script I'm referring to is here (I don't recommend that you run it because it will save some files on your system):
https://github.com/toazd/ge-install-manager/blob/master/ge-install-manager and requires running the verify function (-V or -v version). Relevant lines are [1042](https://github.com/toazd/ge-install-manager/blob/85d37f159972fdaaece1c12fa59e6202ad79c2f0/ge-install-manager#L1042)/1043 and [1071](https://github.com/toazd/ge-install-manager/blob/85d37f159972fdaaece1c12fa59e6202ad79c2f0/ge-install-manager#L1071)/1072.

I have other scripts (eg. [recursive-sha512sum](https://github.com/toazd/recursive-md5sum)) that use the same escape codes and they all produce the same result as the aforementioned script (doesn't matter which pair of escape codes that I use for save_cursor and restore_cursor). recursive-sha512sum is more suitable as a test because the only files created are in the save_path (parameter 2, run without any parameters for "help" output). But, you will have to replace `\033[s` with `\E7` and `\033[u` with `\E8` (global replace will work).

**Expected behavior**
The cursor to return to the saved position.

**Environment details**
OS: GNU/Linux - Arch
kitty 0.18.3 (doesn't work as expected, neither pair of escape codes)
alacritty 0.5.0 (works as expected, both pairs)
gnome-terminal 3.36 (works as expected, both pairs)
konsole 20.08.0 (works as expected, both pairs)

**Output of kitty --debug-config**
```
$ kitty --debug-config
kitty 0.18.3 created by Kovid Goyal
Linux phoenix 5.8.5-toazd1 #1 SMP PREEMPT Sat Aug 29 17:51:41 EDT 2020 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/toazd/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity    0.7
editor                nvim
font_family           Fantasque Sans Mono
font_size             14.0
scrollback_lines      50000
strip_trailing_spaces smart
tab_bar_style         powerline
url_prefixes          ('http', 'https', 'file', 'ftp', 'www')
```

**Additional context**
`kitty --config NONE`
Same results.

```
$ infocmp | grep "\E7"
rmul=\E[24m, rs1=\E]\E\\\Ec, sc=\E7,
$ infocmp | grep "\E8"
kri=\E[1;2A, kund=, oc=\E]104\007, op=\E[39;49m, rc=\E8,
```

I'm not very knowledgeable on this topic so I don't know what else might be useful.

**Comment by kovidgoyal** [comment]
dup of #1264

**Comment by toazd** [comment]
Son of a ... I searched for awhile but I didn't find that one. Sorry.

**Comment by toazd** [comment]
Thanks for the detailed explanation in the other issue. It was interesting and informative to read some of the vt100 docs. All I have to do is send save_cursor after each instance of restore_cursor which in hindsight makes more sense considering older terminals.

**Comment by kovidgoyal** [comment]
You're welcome. Using save after every restore works with all terminals regardless of whether they use a stack or not for implementation.
