### ISSUE TITLE
play videos with kitty (in the terminal) like icat

### ISSUE THREAD

**Issue by therealadityashankar** [kovidgoyal/kitty#2947]
**Describe the solution you'd like**
`icat video.mpg`

**Describe alternatives you've considered**
`vcat video.mpg`

**Comment by therealadityashankar** [comment]
I don't know if its possible via loading images really quickly with icat

**Comment by SolitudeSF** [comment]
`hunter` file manager has video preview capabilities with kitty

**Comment by therealadityashankar** [comment]
thats awesome, I'll check it out !

thanks !

I  think there should be like a specific video playing function, like I don't want to install a whole app for that

also, I think, in theory, one should be able to run like an entire web-browser in kitty right, or something like that

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in developing a video player for kitty. Videos typically include sound as well. What you should do is ask the mpv or similar project to use the kitty graphics protocol as a backend, just as they already have ascii terminal backends.

Although really for efficient video display, one needs a protocol that allows partial frame updates, redrawing entire frames is rather inefficient.

**Comment by ura43** [comment]
I just opened a feature request for that on mpv, lets see how it goes. :+1:
