### ISSUE TITLE
Implicitly activate mark group with "scroll_to_mark" action

### ISSUE THREAD

**Issue by gerion0** [kovidgoyal/kitty#2948]
**Is your feature request related to a problem? Please describe.**
Currently, when using marks to scroll between prompts, you have to activate the marks first (or did I miss something?), so it adds a highlight. My prompt is already highlighted and it would be nice to be able to directly jump to the prompt (without activating first).

**Describe the solution you'd like**
The scroll_to_mark action (specialized on a mark_group) normally is mapped to a hotkey. Would it be possible to activate all marks of this group automatically when pressing this hotkey and also disable the highlight?

**Describe alternatives you've considered**
Alternative could be to trigger toggle_mark someway in the shell init file and disable colors for the group.

**Comment by kovidgoyal** [comment]
Use the combine action in kitty.conf to create a mapping that will
activate the marker, scroll and then de-activate. Note that the only
caveat is am not sure how well that will work for jumping to multiple
prompts. Alternatively, simply configure the mark foreground and
background colors so they blend with your normal prompt colors in
kitty.conf.

**Comment by gerion0** [comment]
That works nice, thank you. What exactly do you mean with jumping to multiple prompts? Triggering the combined actions multiple times works well.
