### ISSUE TITLE
Unexpected crash in peculiar circumstances on OSX

### ISSUE THREAD

**Issue by BlueDrink9** [kovidgoyal/kitty#2950]
**Describe the bug**
When running a tmux session on one space that is connected via `ssh` to several virtualbox headless
 VMs running on the machine, opening a new instance sometimes totally crashes kitty.

**To Reproduce**

Not deterministic. It has happened 5 times, but does not happen immediately upon reconnecting to the tmux environment then opening a new instance.

**Crash dump**
Attached as a text file
[kitty_crash2.log](https://github.com/kovidgoyal/kitty/files/5159266/kitty_crash2.log)

**Environment details**

OSX 10.15.5

```
kitty 0.18.3 created by Kovid Goyal
Darwin oucs1554.localdomain 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:    10.15.5 BuildVersion:   19F101
```

I've left out the config for now. Can add if you suspect it might be relevant.

**Additional context**

Haven't reproduced with minimal config yet, but will look at doing that next time I use it.

**Comment by kovidgoyal** [comment]
That's a crash in the GPU driver, not in kitty, you should report it to
Apple.
