### ISSUE TITLE
`scrollback_lines -1' will make kitty crash when running `time find ~/bigdir`

### ISSUE THREAD

**Issue by c02y** [kovidgoyal/kitty#2956]
**Describe the bug**

I was just testing how long it takes toi run `time find ~/bigdir` inside kitty, and kitty will definitely crash in the middle of running.

NOTE the `~/bigdir` contains a lot of files and dirs, the size of the directory is 43GB, it takes around 4min48s to finish running `time find ~/bigdir` in alacritty, without `scrollback_lines -1`, it takes around 3min45s in kitty.

**To Reproduce**
0. set `scrollback_lines -1` in kitty.conf
1. get a big dir
2. time find /path/dir
3. wait, it will be stuck, stop printing the result, crash silently after running for around 35s.
4. it crashes

I don't know it you can reproduce it since the `~/bigdir` is really big, and I just start to use kitty (came from xfce4-terminal/Yakuake).

**Expected behavior**

It shouldn't crash.

**Screenshots**

**Environment details**
OS: Name and version of operating system(s)

5.7.15-1-MANJARO

```
Output of kitty --debug-config
```

The only difference from the default config(/usr/share/doc/kitty/kitty.conf) is `scrollback_lines -1`

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I dont get a crash, and you dont need to use find, just run yes, like
this

kitty --config NONE -o scrollback_lines -1 yes

On my system kitty eventually gets killed by the kernel with SIGKILL for
using too much RAM, there is no crash. If you are getting an actual
crash build kitty from source with make debug and generate a backtrace
with

echo bt | coredumpctl gdb

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/build.html

**Comment by c02y** [comment]
> I dont get a crash, and you dont need to use find, just run yes, like
> this
> 
> kitty --config NONE -o scrollback_lines -1 yes
>

It is actually `kitty --config NONE -o scrollback_lines=-1 yes`, and yes, it got killed after several seconds since the memory of kitty got very big really quickly(in `top`).

I'm not sure if my problem can be described as `crash`, the whole kitty window is closed suddenly(when running `time find ~/bigdir` ), maybe it is just "SIGKILL" since the memory used by kitty in `top` is over 83%. 

I'll just use the limited value for `scrollback_lines` then.

**Comment by kovidgoyal** [comment]
Note that for really large scrollbacks use scrollback_pager_history_size in kitty.conf
