### ISSUE TITLE
When open a new tab cd old path

### ISSUE THREAD

**Issue by OmarElKhatibCS** [kovidgoyal/kitty#2957]
When I open a new tab using CTRL+SHIT+T it open a new one with path is HOME , isn't better if the new tab open in old path where I call to create new tab ,
like I was in "/home/user/bla/bla" when I open a new tab it should directly open at "/home/user/bla/bla" not in "/home/user/"

**Comment by SolitudeSF** [comment]
https://sw.kovidgoyal.net/kitty/launch.html

`map ctrl+shift+t launch --cwd=current --type=tab`

**Comment by OmarElKhatibCS** [comment]
Thanks <3
