### ISSUE TITLE
How do you set a launch title in startup_session?

### ISSUE THREAD

**Issue by stemid** [kovidgoyal/kitty#2958]
According to [this doc](https://sw.kovidgoyal.net/kitty/#startup-sessions) I can use startup_session to run commands like launch.

According to [this doc](https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-launch) the launch command can set a window title with --title.

But when I try to use a startup_session that does that I get this error: **Failed to launch child: --tab-title**

Here is my attempted startup_session file. I've tried both with --title and --tab-title but get the same error. How is launch used in startup_sessions? Is there a different command line syntax?

```
launch --tab-title "tmux shells" tmuxp load -y ~/.tmuxp/shells.yml
title tmux shells

new_tab tmux ssh
launch tmux new -As ssh

new_tab bash
```

_Doesn't feel right asking questions in Issues but I read [in another Issue](https://github.com/kovidgoyal/kitty/issues/436) that there is no community forum, just this._

**Comment by kovidgoyal** [comment]
sessions dont support the full launch command, it's on my TODO list. If
you want to set title's use title

title whatever
launch whatever
