### ISSUE TITLE
kitty 0.18.3 launch not working with backquotes

### ISSUE THREAD

**Issue by andreagrax** [kovidgoyal/kitty#2959]
**Describe the bug**
I'm mapping the `F5` key to a `launch` function to save all the buffer to a file.

**To Reproduce**
1. add the following line to kitty.conf `map f5 launch --type background --stdin-source @screen_scrollback tee /tmp/kitty_buffer_$(/bin/date +%Y-%m-%d_%H:%M:%S ).txt`
2. close and relaunch kitty
3. populate the buffer (i.e. `dmesg` )
4. check if the file have been created

**Expected behavior**
A file should be created under /tmp as kitty_buffer_$timestamp.txt
If I put a static file name ( like `/tmp/kitty_buffer.txt` ) the shortcut works just fine

**Environment details**
OS: kitty 0.18.03 under xubuntu 20.04

```
> kitty --debug-config
kitty 0.18.3 (4b0724530e) created by Kovid Goyal
Linux allanon 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Loaded config files: /home/andrea/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control y
background           Color(red=0, green=27, blue=33)
bell_on_tab          False
enable_audio_bell    False
scrollback_lines     20000
term                 xterm-256color
window_alert_on_bell False
Added shortcuts:
	f5 KeyAction(func='launch', args=['--type', 'background', '--stdin-source', '@screen_scrollback', 'tee', '/tmp/kitty_buffer_$(/bin/date', '+%Y-%m-%d_%H:%M:%S', ').txt'])
	control+right KeyAction(func='resize_window', args=['wider', 1])
	control+left KeyAction(func='resize_window', args=['narrower', 1])
	control+down KeyAction(func='resize_window', args=['shorter', 3])
	control+up KeyAction(func='resize_window', args=['taller', 1])
Changed shortcuts:
	shift+control+comma KeyAction(func='previous_window', args=())
	shift+control+period KeyAction(func='next_window', args=())
	shift+control+t KeyAction(func='new_tab_with_cwd', args=())
	shift+control+enter KeyAction(func='new_window_with_cwd', args=())
```

**Comment by kovidgoyal** [comment]
launch does not run a shell, if you want to run inside a shell use
launch sh -c "whatever"

**Comment by andreagrax** [comment]
> launch does not run a shell, if you want to run inside a shell use
> launch sh -c "whatever"

`sh` does not correctly handle STDIN , but I've got the point .
Will try with a wrapper script and link it there , just in case

**Comment by kovidgoyal** [comment]
Really? I'd be amazed if this did not work:

```
launch sh -c "exec tee /tmp/kitty_buffer_$(/bin/date +%Y-%m-%d_%H:%M:%S ).txt"
```

**Comment by andreagrax** [comment]
I was missing the `exec`

thank you!
