### ISSUE TITLE
Fira Code "*/" Ligature not rendering correctly

### ISSUE THREAD

**Issue by ivandaho** [kovidgoyal/kitty#296]
As per my screenshot, from top to bottom:
* Kitty
* Terminal.app
* Alacritty (I am aware that there is no ligature support)

I've tried setting `use_system_wcwidth` to both `yes` and `no` without any luck.

Note the `*/` ligature

![screen shot 2018-01-26 at 10 56 02 pm](https://user-images.githubusercontent.com/11155001/35445296-28747dc6-02ec-11e8-962a-250f07ce068a.png)

My [kitty.conf](https://gist.github.com/ivandaho/4dbe4018a66243007d32b97c98115ce9)

I understand the wider font width in Kitty is intentional due to the way text is rendered? Though I would like to know if there is currently a way to make it narrower and less fuzzy, like how the other terminals in the screenshot do it.

**Comment by ivandaho** [comment]
This is weird. I tried to set `use_system_wcwidth` to `yes` again and restarted kitty and it's rendering correctly for me.

Then I set `use_system_wcwidth` to `no` and it is still ok.

I actually can't reproduce this reliably

**Comment by kovidgoyal** [comment]
I cannot reproduce it either, so if you figure out how to reproduce it feel free to re-open the issue. As for the width of the cells that comes from the font, there is a setting to adjust cell height but not cell width (it should be a trivial 5 line patch to add a setting for height, pull request is welcome). The difference in rendering probably comes from sub-pixel anti-aliasing which kitty does not do, for reasons I have explained in other bug reports. If you have a non-retina screen then probably you prefer sub-pixel antialiasing, though on retina screens, IMO it is an unneccessary waste of resources.
