### ISSUE TITLE
Suggestion: Full screen window

### ISSUE THREAD

**Issue by jbiason** [kovidgoyal/kitty#2960]
**Is your feature request related to a problem? Please describe.**

Not really a problem, but a thing on my workflow:

Sometimes, when dealing with multiple windows, reading the content of one of them gets a bit hard; Tmux have a feature that you can make panes (their analogous of windows) a full-screen pane, taking the whole available space.

**Describe the solution you'd like**

This is pretty much close to detaching a window to a new tab, but with an "easy to re-attach" way.

One way to display those full-screen windows (and differentiate from a tab with a single window) would add the border, but taking the whole available space.

**Describe alternatives you've considered**

I thought about using detach, but I'd like to re-attach the window into the tab (and probably in its original position).

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/custom.html#using-kittens-to-script-kitty-without-any-terminal-ui

Use that example kitten
