### ISSUE TITLE
Move to tab by name, per-session

### ISSUE THREAD

**Issue by mredaelli** [kovidgoyal/kitty#2961]
When I'm working on a particular project, I often have one kitty session with `n` named tabs for various aspects of the project (think backend, frontend, ...), and I have a session file that starts kitty in just the right way.

What I'm missing would be a way to quickly go to the tab for, say, frontend, without having to think of what tab number that is.

In my optimal scenario, I would have:
- a command equivalent to `goto_tab`, but that takes the tab name
- the possibility to specify key bindings also inside the session file, local to the session.

That way I wouldn't have to worry about moving tabs in the session, thus changing the index, or repurposing a tab for something else (I can always rename it); nor about polluting the key binding with stuff I need only in one project.

**Comment by kovidgoyal** [comment]
Use the remote control facility, that has
kitty @ focus-tab -m title:whatever

And you can map it to key presses as described here:
https://sw.kovidgoyal.net/kitty/remote-control.html#mapping-key-presses-to-remote-control-commands

And while you cannot specify shortcuts in session files you can do so at
the command line

kitty -o 'map f1 whatever' --session whatever
