### ISSUE TITLE
"Broadcast" input

### ISSUE THREAD

**Issue by joelmarty** [kovidgoyal/kitty#2962]
**Is your feature request related to a problem? Please describe.**
As a part of my job, I often need to execute commands over multiple hosts to make checks. I noticed colleagues that do this with iterm2, that supports that feature. But I like kitty better :)

**Describe the solution you'd like**
- Upon pressing a keyboard shortcut and/or menu item, all panes of the currently active tab join a broadcast input group. All input is reproduced on all panes in the broadcast group.
- The mode is conserved when switching out and back in of a broadcast group.
- A visual indicator is displayed on the panes joined-in a broadcast group.
- Broadcast group can be terminated.
- As a second step, maybe we could choose which panes or tabs to join in broadcast input.

**Describe alternatives you've considered**
Not sure what alternative there is.

**Additional context**
Demo video on youtube (quality could be better): https://www.youtube.com/watch?v=gAiSFMdNM8I

**Comment by kovidgoyal** [comment]
Use https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by Felixoid** [comment]
Hey Kovid. Is there a way to limit it only to the currently active tab? It's quite dangerous to broadcast it to all windows on all tabs.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/broadcast/#options

**Comment by Felixoid** [comment]
Looks promising, but I fail to use it. What I've tried so far

```
map F1 launch --allow-remote-control kitty +kitten broadcast -t window_id:KITTY_WINDOW_ID
map F1 launch --allow-remote-control kitty +kitten broadcast -t window_id:$KITTY_WINDOW_ID
map F1 launch --allow-remote-control kitty +kitten broadcast -t window_id:"$KITTY_WINDOW_ID"
map F1 launch --allow-remote-control kitty +kitten broadcast -t window_id:${KITTY_WINDOW_ID}
map F1 launch --allow-remote-control kitty +kitten broadcast -t window_id:"${KITTY_WINDOW_ID}"
```

None of them expand the env variable. I've tried index, but it has only the static value, not the `current` id. Do I miss some easy way to achieve the current tab id?

**Comment by kovidgoyal** [comment]
There you go:
https://github.com/kovidgoyal/kitty/commit/433355252356c1f8b7a404a95bd220b34beda831

broadcast --match-tab=recent:0
