### ISSUE TITLE
Missing color (possible bug?)

### ISSUE THREAD

**Issue by matoxxx** [kovidgoyal/kitty#2963]
**Describe the bug**
This has me bugging me for a while now. It seems kitty is not displaying one color properly in ascii when compared to xterm. I have identical colors in .Xresources and kitty.conf. Not sure if this is a bug. Also Fonts displayed by kitty are noticeably smaller compared to xterm. Had to increase size to match xterm.

`$ kitty --debug-config  
kitty 0.18.3 created by Kovid Goyal
Linux legion 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/matoxxx/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=32, green=32, blue=32)
bold_font             Source Code Pro Bold
bold_italic_font      Source Code Pro Bold Italic
color0                Color(red=15, green=16, blue=16)
color1                Color(red=234, green=105, blue=98)
color10               Color(red=143, green=154, blue=82)
color11               Color(red=193, green=143, blue=65)
color12               Color(red=104, green=148, blue=138)
color13               Color(red=171, green=108, blue=125)
color14               Color(red=114, green=150, blue=108)
color15               Color(red=197, green=177, blue=141)
color2                Color(red=169, green=182, blue=101)
color3                Color(red=216, green=166, blue=87)
color4                Color(red=125, green=174, blue=163)
color5                Color(red=211, green=134, blue=155)
color6                Color(red=137, green=180, blue=130)
color7                Color(red=221, green=199, blue=161)
color8                Color(red=124, green=111, blue=100)
color9                Color(red=184, green=86, blue=81)
font_family           Source Code Pro
font_size             12.0
foreground            Color(red=212, green=190, blue=152)
italic_font           Source Code Pro Italic
update_check_interval 24.0`

`$ cat .Xresources 
XTerm.termName: xterm-256color
xterm*faceName: Source Code Pro
xterm*faceSize: 10
xterm*renderFont: true

*background: #202020
*foreground: #d4be98
*color0: #0f1010
*color1: #ea6962
*color2: #a9b665
*color3: #d8a657
*color4: #7daea3
*color5: #d3869b
*color6: #89b482
*color7: #ddc7a1
*color8: #7c6f64
*color9: #b85651
*color10: #8f9a52
*color11: #c18f41
*color12: #68948a
*color13: #ab6c7d
*color14: #72966c
*color15: #c5b18d
`

**To Reproduce**
1. kitty asciiquarium
2. xterm asciiquarium
3. compare

**Expected behavior**
Expecting to see all colors

**Screenshots**
Attached
![screen](https://user-images.githubusercontent.com/71211283/93015763-f5cc9d00-f5b3-11ea-8ae8-46cbf360c48f.png)

**Additional context**
Try to reproduce the problem with `kitty --config NONE`. Is the same, not displaying 'castle' color.

Thank you

**Comment by kovidgoyal** [comment]
kitty does not have special behavior for any individual color. Nor is matching xterms font rendering a goal for kitty. I dont know what asciiquarium is, but the difference in color will almost certainly be because asciiquarium is incorrectly using SGR bold to get intense colors instead of using the actual intense colors. https://github.com/hishamhm/htop/issues/35

**Comment by matoxxx** [comment]
Ah, ok. I was testing if my color scheme is valid besides standard term color check. Any comments on different font size compared to xterm, could this be because kitty uses gl render? If I use compositor (picom), the ui font size in awesomewm is changing too.
thanks for clarification

**Comment by dreua** [comment]
@matoxxx Did you ever find a solution to this? It's bugging me too, in gnome-terminal in my case so it's obviously not a kitty issue.

**Comment by page-down** [comment]
@dreua This code uses a black background color + black castle, which is of course invisible. Search for BLACK and replace it with WHITE. Please go to the project issue list to check the "background color" related issues and try the improved version.

kitty render the color correctly, there is nothing can be done here.
