### ISSUE TITLE
Iosevka: Capital umlaut characters are shifted by 1px

### ISSUE THREAD

**Issue by The-Compiler** [kovidgoyal/kitty#2964]
**Describe the bug**
When I have a text such as "Über Änderung ÖBB Öffentlichkeit" with Iosevka Nerd Font, the Ü and Ö characters are shifted down by one character, see the screenshots below.

**To Reproduce**
Use this config:

```ini
font_family Iosevka Nerd Font Complete
font_size 12
```

and paste a text like that. It only seems to happen with that font size, not when I zoom in or out a bit.

**Screenshots**
In kitty:

![image](https://user-images.githubusercontent.com/625793/93021588-b4ec7c80-f5e3-11ea-859f-c25da569fb36.png)

Note how Ü/Ö are out of place, but Ä as well as U/A/O are not.

Same font settings with Gedit:

![image](https://user-images.githubusercontent.com/625793/93021606-c7ff4c80-f5e3-11ea-9d7d-9daf33939c7b.png)

**Environment details**
OS: Archlinux, kitty 

```
kitty 0.18.3 created by Kovid Goyal
Linux aragog 5.8.7-arch1-1 #1 SMP PREEMPT Sat, 05 Sep 2020 12:31:32 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/florian/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
[...]
```

(not including the config options output here, because it is incorrect - it shows the output of my `/home/florian/.config/kitty/kitty.conf` despite having used `kitty -c debug.conf` with the config shown above. Should I open a separate issue for that?)

**Comment by kovidgoyal** [comment]
Hi Florian, long time no see :)

1) Dont use patched fonts, they are often broken, and there is no need,
simply install the standalone nerd fonts. kitty will pick up the symbols
from them automatically, and you can instruct it to do so manually via
symbol_map in kitty.conf as well.

2) My guess is those symbols are coming from a different font. Use
--debug-font-fallback to confirm. If this is the case, then you will
need to find a fallback font for those symbols that matches Iosevka's
metrics.

3) Alternatively, try increasing line height with adjust_line_height
in kitty.conf

If neither (1) nor (2) not (3) apply then feel free to post and I will re-open.

**Comment by kovidgoyal** [comment]
Oh and 

```
kitty -c /t/t.conf --debug-config
```

works for me, showing the output from t.conf not kitty.conf

**Comment by The-Compiler** [comment]
Heya and thanks for the quick answer! :)

> Dont use patched fonts, they are often broken, and there is no need, simply install the standalone nerd fonts. kitty will pick up the symbols from them automatically, and you can instruct it to do so manually via symbol_map in kitty.conf as well.

While kitty does display those characters, they are much smaller than with the patched font:

![image](https://user-images.githubusercontent.com/625793/93023349-9e97ee00-f5ee-11ea-9ef3-ca7c3daa5ccd.png)

![image](https://user-images.githubusercontent.com/625793/93023358-a8215600-f5ee-11ea-8602-87226499ec5a.png)

Though I suppose there's some way to change that which I haven't discovered yet? :slightly_smiling_face: Can I set different font sizes for different fonts somehow?

Either way, this wasn't the issue - with `font_family Iosevka` I still see the same:

![image](https://user-images.githubusercontent.com/625793/93023372-dacb4e80-f5ee-11ea-9b82-99f37daceef9.png)

> My guess is those symbols are coming from a different font. Use --debug-font-fallback to confirm. If this is the case, then you will need to find a fallback font for those symbols that matches Iosevka's metrics.

That shows:

```
[257 18:28:22.638670] Preloaded font faces:
[257 18:28:22.638702] normal face: /usr/share/fonts/TTF/Iosevka Nerd Font Complete.ttf:0
[257 18:28:22.638710] bold face: /usr/share/fonts/TTF/Iosevka Nerd Font Complete.ttf:0
[257 18:28:22.638717] italic face: /usr/share/fonts/TTF/Iosevka Italic Nerd Font Complete.ttf:0
[257 18:28:22.638723] bi face: /usr/share/fonts/TTF/Iosevka Nerd Font Complete.ttf:0
```

and doesn't log anything when printing that file, so I suppose that wasn't the issue either.

> Alternatively, try increasing line height with adjust_line_height in kitty.conf

That did the trick, thanks! With `adjust_line_height 2` those characters fit properly:

![image](https://user-images.githubusercontent.com/625793/93023412-19610900-f5ef-11ea-90ad-9ef1a75b8713.png)

So is that an issue with the font somehow not reporting the needed maximum size for characters properly or something?

> Oh and `kitty -c /t/t.conf --debug-config` works for me, showing the output from t.conf not kitty.conf

Err, that was a brainfart on my part, sorry! I did run `kitty --debug-config` inside the instance started with `-c`, but it makes sense that this would start a new instance so I'd have to pass `-c` again together with `--debug-config`. :sweat_smile:

**Comment by kovidgoyal** [comment]
On Sun, Sep 13, 2020 at 09:31:37AM -0700, Florian Bruhin wrote:
> Heya and thanks for the quick answer! :)
> 
> > Dont use patched fonts, they are often broken, and there is no need, simply install the standalone nerd fonts. kitty will pick up the symbols from them automatically, and you can instruct it to do so manually via symbol_map in kitty.conf as well.
> 
> While kitty does display those characters, they are much smaller than with the patched font:
> 
> ![image](https://user-images.githubusercontent.com/625793/93023349-9e97ee00-f5ee-11ea-9ef3-ca7c3daa5ccd.png)
> 
> ![image](https://user-images.githubusercontent.com/625793/93023358-a8215600-f5ee-11ea-8602-87226499ec5a.png)
> 
> Though I suppose there's some way to change that which I haven't discovered yet? :slightly_smiling_face: Can I set different font sizes for different fonts somehow?

Hmm that would imply that kitty is not using space after PUA rendering
for characters from fallback fonts, which would be a bug. Can you please
open a separate issue for that, and most the codepoints of a couple of
characters showing the issue, I will look into it when I have a moment.

> > Alternatively, try increasing line height with adjust_line_height in kitty.conf
> 
> That did the trick, thanks! With `adjust_line_height 2` those characters fit properly:
> 
> ![image](https://user-images.githubusercontent.com/625793/93023412-19610900-f5ef-11ea-90ad-9ef1a75b8713.png)
> 
> So is that an issue with the font somehow not reporting the needed maximum size for characters properly or something?

Yes, you can see the cell_metrics() function in freetype.c for how kitty
calculates cell height it is the maximum of the height reported by the
font and the height needed to flly render the underscore character (to
workaround some buggy fonts).

**Comment by kovidgoyal** [comment]
On my Linux system, using unpatched nerd fonts, I get bigger symbols when followed by a space, as expected.
![Screenshot_20200914_094946](https://user-images.githubusercontent.com/1308621/93043548-bcf1fe00-f66f-11ea-86f4-e39f705c6a08.png)

```
kitty --debug-font-fallback sh -c "printf '\ue5ff a\n\ue5ffa'; read"
```
