### ISSUE TITLE
The same font size looks different on different monitors/dimensions

### ISSUE THREAD

**Issue by c02y** [kovidgoyal/kitty#2965]
**Describe the bug**

I sync my dotfiles including kitty.conf to github, so I can share the same configs between different environments.

I set `font_size 13` in `kitty.conf` in one environment(1080P), but after I switch to another environment(2k), the font size is very small, I have to change the `font_size 15` to make it look better.

Please don't say that I should set global environment variable in other config file such as `~/.xinittc`, since I set the same font size for emacs and alacritty, they basically look the same on two environments, but not kitty, is there something with kitty. Is it a bug?

Actually this is the only reason I choose alacritty over kitty as my main terminal, but alacritty got its own issue, if this problem is fixed, I'll be happy to use kitty as my main terminal instead.

**To Reproduce**
1. XXX
2. YYY
3. ZZZ

**Expected behavior**

The same font_size should look the same on different monitors/dimensions.

**Screenshots**

**Environment details**
OS: Name and version of operating system(s)
Manjaro-XFCE(1080P)
Manjaro-KDE(2K)

```
Output of kitty --debug-config
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You need to set Xft.dpi

**Comment by c02y** [comment]
@kovidgoyal 
> Please don't say that I should set global environment variable in other config file such as ~/.xinittc, since I set the same font size for emacs and alacritty, they basically look the same on two environments, but not kitty, is there something with kitty. Is it a bug?

I don't need to set Xft.dpi for emacs and alacritty, why would I do it specifically for kitty, I would say this is a bug of kitty. 

Besides, if I set it, I don't know if it will cause problem for other programs.

**Comment by kovidgoyal** [comment]
Xft.dpi is THE way you specify DPI on X11 systems. Without it every
program will resort to different heuristics to guess the DPI of your
monitors. You just happen to be lucky that whatever heuaristics
alacritty/emacs use work for you.

**Comment by c02y** [comment]
Is the Xft.dpi the thing as the scale in System Settings? I wouldn't change it since KDE apps has bugs when I change the scale from 1.0 to other value like 1.2.

And why emacs and kitty with a fixed font size basically look the same and Kitty doesn't?

**Comment by kovidgoyal** [comment]
No clue, I wouldn't touch KDE/GNOME with a ten foot barge pole. Just set Xft.dpi

**Comment by c02y** [comment]
It seems Xft.dpi and the scale are the same things, from https://wiki.archlinux.org/index.php/HiDPI#Unsupported_applications, and it says I can set scale for specific programs using [run_scaled](https://github.com/kaueraal/run_scaled), I'll try that later.
