### ISSUE TITLE
Issues/Inconsistencies with nerd font characters

### ISSUE THREAD

**Issue by The-Compiler** [kovidgoyal/kitty#2966]
Splitting this off from #2964 - there, @kovidgoyal says:

> On my Linux system, using unpatched nerd fonts, I get bigger symbols when followed by a space, as expected.
> ![Screenshot_20200914_094946](https://user-images.githubusercontent.com/1308621/93043548-bcf1fe00-f66f-11ea-86f4-e39f705c6a08.png)
> 
> ```
> kitty --debug-font-fallback sh -c "printf '\ue5ff a\n\ue5ffa'; read"
> ```

Note however how the second folder icon is smaller than the first one - that seems weird, no?

Here's what I get - with unpatched fonts:

![image](https://user-images.githubusercontent.com/625793/93061301-aa79c380-f673-11ea-863f-ff69563d6cc9.png)

With patched fonts:

![image](https://user-images.githubusercontent.com/625793/93061379-c1201a80-f673-11ea-92a8-d326337b31e2.png)

Here's the config I use:

```
font_family Iosevka
# font_family Iosevka Nerd Font Complete
font_size 12
```

`--debug-config`:

```
kitty 0.18.3 created by Kovid Goyal
Linux aragog 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: debug.conf
Running under: X11

Config options different from defaults:
font_family Iosevka
font_size   12.0
```

**Comment by kovidgoyal** [comment]
No, its expected. Nerd fonts uses private unicode codepoints. These all have width 1. However kitty will render them in two or more cells *provided* they are followed by spaces. In my screenshot, there first one has spaces following, the second one does not, hence the rendering is as expected. I dont know whats going on with your unpatched font. If you want to debug that, run with --debug-font-fallback check with fonts are being used. It should be 3270Medium Nerd Font Mono

**Comment by The-Compiler** [comment]
Looks like it's falling back to the patched Iosevka:

```
[258 11:23:15.098209] Preloaded font faces:
[258 11:23:15.098240] normal face: /usr/share/fonts/TTF/iosevka-regular.ttf:0
[258 11:23:15.098251] bold face: /usr/share/fonts/TTF/Iosevka Bold Italic Nerd Font Complete Mono.ttf:0
[258 11:23:15.098259] italic face: /usr/share/fonts/TTF/iosevka-regular.ttf:0
[258 11:23:15.098266] bi face: /usr/share/fonts/TTF/Iosevka Bold Italic Nerd Font Complete Mono.ttf:0
U+e615 Face(family=Iosevka, style=Regular, ps_name=IosevkaNerdFontCompleteM-, path=/usr/share/fonts/TTF/Iosevka Nerd Font Complete Mono.ttf, index=0, is_scalable=True, has_color=False, ascender=977, descender=-272, height=1249, underline_position=-75, underline_thickness=50, strikethrough_position=265, strikethrough_thickness=51) (new face)
```

I have `ttf-nerd-fonts-symbols-mono` installed, which provides `/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf` and gets listed by kitty as:

```
Symbols Nerd Font
    Symbols-1000-em Nerd Font Complete
```

If I add:

```
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B Symbols-1000-em Nerd Font Complete
```

to my config, it looks better, but the "missing space" issue is even more pronounced than before:

Patched:

![image](https://user-images.githubusercontent.com/625793/93069852-6b04a480-f67e-11ea-8976-058f5d94e21d.png)

Unpatched with `symbol_map`:

![image](https://user-images.githubusercontent.com/625793/93069743-50cac680-f67e-11ea-865c-1f499c264689.png)

I first thought this was because folder names seem to be bold/italic now, but note how it also happens with the "debug.conf" as well...

**Comment by The-Compiler** [comment]
> It should be 3270Medium Nerd Font Mono

That seems odd, because that's a patched version of the [3270 font](https://github.com/rbanffy/3270font) - I thought the goal was not using patched fonts?

**Comment by kovidgoyal** [comment]
On Mon, Sep 14, 2020 at 02:51:33AM -0700, Florian Bruhin wrote:
> > It should be 3270Medium Nerd Font Mono
> 
> That seems odd, because that's a patched version of the [3270 font](https://github.com/rbanffy/3270font) - I thought the goal was not using patched fonts?

My mistake, I dont actually use nerd fonts, so this was proabbly lying
around from some previous testing I did.

**Comment by kovidgoyal** [comment]
What space issue? Remember it will render small without following space and large with following spaces. This is by design.

**Comment by The-Compiler** [comment]
I mean the space after the nerd font character being almost invisible - or is that by design, so that the icon fills the two adjacent cells without having to "shift" any other text around?

I thought that's what you meant in https://github.com/kovidgoyal/kitty/issues/2964#issuecomment-691770475 with

> Hmm that would imply that kitty is not using space after PUA rendering for characters from fallback fonts, which would be a bug

but apparently not then? Either way I don't really understand why the space after the gear icon would be smaller with the unpatched font compared to the patched one.

**Comment by RouNNdeL** [comment]
Would it be possible to implement a config option to disable this behavior? Right now kitty rendering those large icons means they are ugly off center:

![image](https://user-images.githubusercontent.com/22538735/99159401-42c80f00-26dc-11eb-9594-6e2b6c31a227.png)

How it looks like when rendered as one cell:

![image](https://user-images.githubusercontent.com/22538735/99159428-828ef680-26dc-11eb-9859-60b1b0c204e6.png)
