### ISSUE TITLE
Hyperlinks don't work in scrollback

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#2969]
**Describe the bug**
When the buffer is scrolled, the hover lines under a hyperlink appear in the wrong place, and clicking on it doesn't do anything.

**To Reproduce**
1. Fill the screen so you get some scrollback.
2. Print a hyperlink.
3. Print some more lines so the hyperlink isn't at the last line.
4. Scroll a bit up.
5. Hover over the hyperlink and try clicking on it.

**Expected behavior**
The hyperlink should work as it does when the buffer is not scrolled.

**Screenshots**
![image](https://user-images.githubusercontent.com/601966/93260022-10b03480-f7a1-11ea-82fb-a14b9022a124.png)

**Environment details**
OS: Arch Linux
kitty master
Happens with `--config NONE`

**Comment by trygveaa** [comment]
Now it works when scrolled for links that are not in the scrollback (i.e. what you see when not scrolled), but for links that are part of the scrollback (i.e. links you scroll into view) the issue is still present.

That is, print a link, fill the screen with lines so it scrolls out of view, scroll back up to it, and it doesn't work.

**Comment by kovidgoyal** [comment]
Should be fine now.

**Comment by trygveaa** [comment]
Yup, works correctly now :+1:
