### ISSUE TITLE
Hyperlinks to remote hosts files over multiple ssh connections tries to open from the wrong host

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#2971]
**Describe the bug**
When using nested ssh connections and using hyperlinks to local files on that host, kitty tries to open the file from the first host.

**To Reproduce**
1. ssh to one host.
2. From that host, ssh to another host.
3. Run `ls --hyperlinks=auto`.
4. Click on a link and select an action.

Kitty tries to download the file from the first machine you connected to, instead of the one the links refer to.

**Expected behavior**
Kitty should either download the files from the correct host, or display an error message that opening files in nested ssh connections is not supported.

**Environment details**
OS: Arch Linux
kitty master
Happens with `--config NONE`

**Comment by trygveaa** [comment]
Shouldn't the remote file kitten check that the hostname of the link and the host it connects to are the same?

**Comment by kovidgoyal** [comment]
There's no way to know. For instance,

ssh somewhere.something

hostname == something-else

ssh localhost -p 22002 (for a forwarded port)

hostname == something

ssh some-alias

hostname == somethingelse

And then there is no way to knowin general how to SSH to the hostname
reported in the hyperlink

**Comment by trygveaa** [comment]
You would have to check the hostname on the remote host, e.g. run the `hostname` command on the remote host and compare the value with the value in the link.

**Comment by kovidgoyal** [comment]
And do what if it is different?

**Comment by trygveaa** [comment]
Then it should show an error that opening remote files in nested ssh connections is not supported.

The spec says:
> Utilities that print hyperlinks are requested to fill out the hostname, and terminal emulators are requested to match it against the local hostname and refuse to open the file if the hostname doesn't match (or offer other possibilities, e.g. to download with scp as iTerm2 does).

I would say this means that you should also match remote hostnames and only open remote files if the hostnames match. Even though it only mentions matching the local hostname, I'm pretty sure the meaning of it would be to do the same when opening remote files.

**Comment by trygveaa** [comment]
It should probably match the link against both `hostname` and `hostname -f`, in case some applications use the fully qualified hostname.

**Comment by kovidgoyal** [comment]
It will cause false positives. As I said in my examples, the name used
to connect via ssh can be very different from the hostname reported by
the server, indeed, the two have no canonical connection at all, and
that's not even getting into ssh aliases.

As for copying from nested ssh hosts, for that, I have a different
solution in mind that wont work through hyperlinks. The remote_file kitten is
meant for convenience use, not as a fully robust solution.

**Comment by trygveaa** [comment]
> It will cause false positives. As I said in my examples, the name used
> to connect via ssh can be very different from the hostname reported by
> the server, indeed, the two have no canonical connection at all, and
> that's not even getting into ssh aliases.

Yes, you can't use the name used to connect to ssh. That's why I said you have to run `hostname` (or similar) on the remote host and use that value.

**Comment by kovidgoyal** [comment]
Totally confused. How am I going to run hostname on the remote host
without being able to connect to it?

**Comment by trygveaa** [comment]
You have to connect to it, you should just not open the link if the hostnames don't match.

**Comment by trygveaa** [comment]
I mean, you connect to the same host as you do now, run hostname on that machine, and check if it matches the hostname in the link.

**Comment by kovidgoyal** [comment]
what would be the point? I dont "just open" the link. If kitty believes
its a remote file, it asks the user what to do with it. Its up to the
user to decide if he wants kitty to open it or not at that point.

**Comment by trygveaa** [comment]
The behavior now is confusing when using nested ssh sessions. When you try to open the link, either kitty says "No such file or directory", or if the same filename exists on the first host you connected to, it opens the file from that host instead of the file from the host you're trying to open from.

**Comment by kovidgoyal** [comment]
On Wed, Sep 16, 2020 at 08:28:48AM +0000, Trygve Aaberge wrote:
> The behavior now is confusing when using nested ssh sessions. When you try to open the link, either kitty says "No such file or directory", or if the same filename exists on the first host you connected to, it opens the file from that host instead of the file from the host you're trying to open from.
> 


Sure it might be a bit confusing the first time it happens. But the
answer is not to have the kitten pre-emptively connect to the remote
host. Makes opening the kitten super slow, which is not acceptable. 
The best I can offer is display the hostname the kitten will connect to
at the top, where the file path and remote hostame are mentioned.

**Comment by trygveaa** [comment]
> Sure it might be a bit confusing the first time it happens. But the answer is not to have the kitten pre-emptively connect to the remote host. Makes opening the kitten super slow, which is not acceptable.

If that is the problem, the error could be displayed after selecting open/edit/save.

**Comment by kovidgoyal** [comment]
On Wed, Sep 16, 2020 at 01:35:03AM -0700, Trygve Aaberge wrote:
> > Sure it might be a bit confusing the first time it happens. But the answer is not to have the kitten pre-emptively connect to the remote host. Makes opening the kitten super slow, which is not acceptable.
> 
> If that is the problem, the error could be displayed after selecting open/edit/save.

Sure that's possible, but a fair bit of work, patches welcome, or wait
around and I will get to it eventually.

**Comment by trygveaa** [comment]
Alright :+1:

Thanks for this feature btw, it's really nice :)

**Comment by kovidgoyal** [comment]
You're welcome :) 

This feature was basically why I implemented hyperlinks, as otherwise I
dont have any use for it.

**Comment by kovidgoyal** [comment]
Note I havent tested it, I leave that to you

**Comment by trygveaa** [comment]
Thanks, it works great! Just a small issue, if you select open and press "No" to the continue question, it prints "Failed to copy file from remote machine" instead of just exiting like edit and save does.

**Comment by kovidgoyal** [comment]
Should be fine now.

**Comment by trygveaa** [comment]
Indeed it is, thanks :)
