### ISSUE TITLE
Kitty graphics protocol confusion

### ISSUE THREAD

**Issue by llight3** [kovidgoyal/kitty#2977]
Im trying to debug an application i wrote using the graphics protocol but it keeps hanging with no ability to ctrl+c out of it when i try to display an image. Whats the best way of debugging this in Kitty? Also does anyone know why ```echo "\u001B_Gf=100;$(base64 img.png | tr -d '\n' )\u001B\\"``` also has this behavior?

**Comment by kovidgoyal** [comment]
To quote from the standard:

The pixel data must first be base64 encoded then chunked up into chunks no larger than 4096 bytes

You cannot pass arbitrary binary data to a terminal, it can contain
escape codes that will change the terminal state in unexpected ways,
including, for instance turning on/off flow control.
