### ISSUE TITLE
Insert key does work on Mac

### ISSUE THREAD

**Issue by cdleonard** [kovidgoyal/kitty#2978]
The "insert" key does not work on mac, in vim or anywhere else.

I'm using a PC-style keyboard over USB and most keys work as expected (including mappings for "super" and "alt" and the home/end/pgup/pgdown keys). It works fine in iTerm2 or on Linux.

I tried ``kitty --debug-keyboard`` and it shows nothing when insert is pressed.

Version is kitty 0.18.3 from github dmg release but homebrew shows the same issue. I also tried to run without my config file and I get the same behavior.

**Comment by kovidgoyal** [comment]
If debug keyboard shows nothing for the key, that means cocoa is not
able to handle the key and therefore there is nothing kitty can do about
it, they key press is never reaching keyDown in glfw/cocoa_window.m

**Comment by cdleonard** [comment]
So how can it work in iTerm2 and vscode?

To be fair it does also fail in Terminal.app and MacVim

**Comment by kovidgoyal** [comment]
On Sun, Sep 20, 2020 at 11:13:27PM -0700, Leonard Crestez wrote:
> So how can it work in iTerm2 and vscode?

Feel free to read their source code and find out. Patches are most
welcome.
