### ISSUE TITLE
Looking for resources about rendering images in terminal text editors like vim

### ISSUE THREAD

**Issue by nscotto** [kovidgoyal/kitty#2982]
I see a lot of possible applications for terminal text editors using kitty's graphic ability.
I would like know if I can render images in text editors like vim using kitty terminal and it's API, I haven't find any resources on it.
As a first step I tried running `kitty +kiten icat ...` command directly in vim and got the error `OSError: [Errno 6] No such device address: '/dev/tty'`.

I would like to find some resources on how I can display images in text editors like vim.

**Comment by kovidgoyal** [comment]
You need to get vim to support kitty's graphics protocol.
https://sw.kovidgoyal.net/kitty/graphics-protocol.html
