### ISSUE TITLE
Uppercase accented characters are off with Fira Code

### ISSUE THREAD

**Issue by blehel** [kovidgoyal/kitty#2985]
The baseline of uppercase accented characters is off when using the font Fira Code.
This seems to affect only the font sizes 12 and 13.

For example, if I write "ÁRVÍZTŰRŐ TÜKÖRFÚRÓGÉP" at the prompt, this is what I get:
![fira-kitty](https://user-images.githubusercontent.com/45454608/94669280-4f9dc880-0311-11eb-805d-8f3ec6225a61.png)

Compare this to a libvte-based terminal emulator:
![fira-terminator](https://user-images.githubusercontent.com/45454608/94669315-5e847b00-0311-11eb-84fa-87aa241e5a26.png)

debug-config output:
```
kitty 0.18.3 created by Kovid Goyal
Linux aurora 5.8.9_1 #1 SMP Sun Sep 13 21:10:27 UTC 2020 x86_64
Void \r (\n) (\l)
Loaded config files: /home/blehel/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
bold_font                  Fira Code Medium
color1                     Color(red=205, green=0, blue=0)
color10                    Color(red=0, green=238, blue=0)
color11                    Color(red=255, green=255, blue=0)
color12                    Color(red=0, green=0, blue=255)
color13                    Color(red=255, green=0, blue=255)
color14                    Color(red=0, green=205, blue=205)
color2                     Color(red=0, green=205, blue=0)
color3                     Color(red=205, green=205, blue=0)
color4                     Color(red=0, green=0, blue=168)
color5                     Color(red=205, green=0, blue=205)
color6                     Color(red=0, green=168, blue=168)
color7                     Color(red=168, green=168, blue=168)
color8                     Color(red=84, green=84, blue=84)
color9                     Color(red=255, green=0, blue=0)
cursor                     Color(red=0, green=255, blue=0)
disable_ligatures          1
font_family                Fira Code
font_features              {'FiraCode-Regular': ('+ss03', '+ss05', '+ss07'), 'FiraCode-Medium': ('+ss03', '+ss05', '+ss07')}
font_size                  13.0
foreground                 Color(red=168, green=168, blue=168)
mouse_hide_wait            0.0
pointer_shape_when_grabbed hand
strip_trailing_spaces      smart
Added shortcuts:
	 shift+f12 KeyAction(func='paste_from_selection', args=())
	 shift+control+space KeyAction(func='new_os_window_with_cwd', args=())

```

**Comment by Luflosi** [comment]
Also see #2086.

**Comment by kovidgoyal** [comment]
Use adjust_line_height in kitty.conf. presumably whatever font those
characters are coming from has metrics not compatible with your main
font.

**Comment by trygveaa** [comment]
This isn't about different metrics for different fonts, it happens even when all the characters are coming from Fira Code.

**Comment by kovidgoyal** [comment]
Then Fira Code doesnt report correct metrics, kitty simply uses the
reported font metrics to calculate cell height, see calc_cell_height()

**Comment by charbelnicolas** [comment]
This is still an issue with kitty in 2023. Xterm and alacritty work fine.

Alacritty:
![20230729_174741](https://github.com/kovidgoyal/kitty/assets/14960414/6877a741-6bce-4b73-94ce-2e485a4268cb)

Xterm:
![20230729_174802](https://github.com/kovidgoyal/kitty/assets/14960414/89a3eac6-5f97-452b-a4a0-86d460f5663e)

Kitty:
![20230729_174755](https://github.com/kovidgoyal/kitty/assets/14960414/84df4a08-f0d1-40ec-8cf2-499d05da835c)

This is using Iosevka latest version from github.

**Comment by charbelnicolas** [comment]
> This is still an issue with kitty in 2023. Xterm and alacritty work fine.
> 
> Alacritty: ![20230729_174741](https://user-images.githubusercontent.com/14960414/257016374-6877a741-6bce-4b73-94ce-2e485a4268cb.png)
> 
> Xterm: ![20230729_174802](https://user-images.githubusercontent.com/14960414/257016405-89a3eac6-5f97-452b-a4a0-86d460f5663e.png)
> 
> Kitty: ![20230729_174755](https://user-images.githubusercontent.com/14960414/257016411-84df4a08-f0d1-40ec-8cf2-499d05da835c.png)
> 
> This is using Iosevka latest version from github.

This issue is now magically resolved for me today :P
