### ISSUE TITLE
QUESTION: Connection to KiTTY project?

### ISSUE THREAD

**Issue by sydbarrett74** [kovidgoyal/kitty#2987]
This is a question, and I didn't know whether to file it as a bug or a feature request.

Is your project in any way connected with the KiTTY project hosted at http://www.9bis.net/kitty/#!index.md? If not, you might want to consider renaming, or at least providing clarification for, your project in order to avoid confusion.

Regards.

**Comment by kovidgoyal** [comment]
dup of #9
