### ISSUE TITLE
kitty not building: xrandr doesn't have --cflags-only-I

### ISSUE THREAD

**Issue by yrizk** [kovidgoyal/kitty#299]
python3 setup.py 
CC: gcc (6, 3)
Package xrandr was not found in the pkg-config search path.
Perhaps you should add the directory containing `xrandr.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xrandr' found
The package xrandr was not found on your system
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1

I did more digging, and the issue is not that xrandr isn't installed (`which xrandr` is fine). 
its that xrandr doesn't have a flag called `--cflags-only-I`
And that's about as far as I can go on my own.

**Comment by yrizk** [comment]
It does compile with clang on mac

**Comment by kovidgoyal** [comment]
Youa re missing the xrandr pkg-config files, presumably because you have not installed the libxrandr-dev package as noted in the dependencies.
