### ISSUE TITLE
fancy ctrl z 

### ISSUE THREAD

**Issue by maxdevjs** [kovidgoyal/kitty#2990]
Hello,

this is a question/curiosity. I am fan of [fancy ctrl z](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh) but it does not work with `kitty`. I am curious to know what could be the reason.

Thank you

**Comment by trygveaa** [comment]
What do you mean with does not work, what happens? It seems to work fine for me.

**Comment by maxdevjs** [comment]
Do you use that function? `^Z` sends the program to background, but does not revert to foreground (I get a bell signal). `fg` works. This happens only with `kitty` :thinking: 

Currently:

```
kitty 0.18.3 
zsh 5.8 (x86_64-solus-linux-gnu)
```

**Comment by kovidgoyal** [comment]
Works fine for me, using the following .zshrc and --config NONE to kitty.

```
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line -w
  else
    zle push-input -w
    zle clear-screen -w
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

```

Pressing ctrl-z suspends vim. Pressing ctrl-z again resumes it, as expected.

**Comment by maxdevjs** [comment]
Thank you both, I tried on a different computer and it actually works. I will investigate about it.
