### ISSUE TITLE
cannot capture webcam from programs spawned from Kitty on MacOS

### ISSUE THREAD

**Issue by rwthompsonii** [kovidgoyal/kitty#2991]
**Describe the bug**
Cannot capture webcam from programs spawned from Kitty because Kitty does not request media access permissions from MacOS. 

**To Reproduce**
1. Install Kitty
2. run this python snippet: 
```import cv2

cam = cv2.VideoCapture(0)
print(cam.isOpened())
cam.release()```
3. see error:
```OpenCV: not authorized to capture video (status 0), requesting...
zsh: abort      python3
```
4. Subprocess crashes with abort because Kitty doesn't request media access permissions like the built in Terminal app does.

**Expected behavior**
Kitty pops up a GUI MacOS prompt that says "grant kitty access to camera in Preferences and restart app" or whatever, and then the next time it works.

**Screenshots**
n/a

**Environment details**
OS: MacOS 10.15

```
Output of kitty --debug-config
$ kitty --debug-config                                                                                                                                                                        10:13:33
kitty 0.18.3 created by Kovid Goyal
Darwin 
<snipped>
ProductName:	macOS <snipped>
Loaded config files: /Users/name/.config/kitty/kitty.conf

Config options different from defaults:
$
```

**Additional context**
I have no config set at all, this is a fresh install.  Here's a good post of when this feature was implemented in MacOS: https://stackoverflow.com/questions/56084303/opencv-command-line-app-cant-access-camera-under-macos-mojave

I'm not an expert on the development, but my understanding is that this can be resolved by adding the necessary permissions to the Apps info.plist like here: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/ef1db6d089530ceb6928e78398932df15c3f9403
