### ISSUE TITLE
Resize sometimes breaks in KDE+Wayland

### ISSUE THREAD

**Issue by ConnorJC3** [kovidgoyal/kitty#2994]
**Describe the bug**
On KDE a user can drag windows to the top of the screen to maximize them (or to the side of the screen to resize them to half the screen). Kitty, when running under KDE *using Wayland*, does not resize when dragged to the top or side of the screen.

**To Reproduce**
1. Launch kitty under KDE wayland
2. Drag kitty window to top of screen

**Expected behavior**
Kitty window is maximized (Actual behavior: it stays the same size).

**Environment details**
OS: Arch Linux (kernel 5.8.13-arch1-1)
GPU: NVIDIA GeForce GTX 1070
GPU Driver: Proprietary
DE/Compositor: KDE Plasma 5.19.5

```
~ $ kitty --debug-config
kitty 0.18.3 created by Kovid Goyal
Linux arch 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/user/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background           Color(red=50, green=50, blue=50)
color0               Color(red=37, green=37, blue=37)
color1               Color(red=190, green=116, blue=114)
color10              Color(red=151, green=187, blue=152)
color11              Color(red=254, green=253, blue=188)
color12              Color(red=159, green=189, blue=222)
color13              Color(red=152, green=154, blue=188)
color14              Color(red=111, green=187, blue=188)
color15              Color(red=254, green=255, blue=255)
color2               Color(red=112, green=151, blue=114)
color3               Color(red=152, green=151, blue=114)
color4               Color(red=113, green=153, blue=188)
color5               Color(red=114, green=115, blue=153)
color6               Color(red=113, green=152, blue=153)
color7               Color(red=127, green=127, blue=127)
color8               Color(red=85, green=85, blue=85)
color9               Color(red=255, green=153, blue=0)
cursor               Color(red=199, green=199, blue=199)
cursor_text_color    Color(red=254, green=255, blue=255)
enable_audio_bell    False
foreground           Color(red=200, green=200, blue=200)
selection_background Color(red=193, green=221, blue=255)
selection_foreground Color(red=62, green=62, blue=62)
window_margin_width  FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
```

**Additional context**
For some reason, sometimes, it will randomly work (I am yet unable to determine why this is the case). For me approximately 50% of the time it will not work.

Problem still occurs with `kitty --config NONE` (or a nonexistent config file on the disk). Other wayland windows (tested with firefox) are correctly resized, so likely a kitty bug rather than KDE. This bug does not occur under KDE using X (or under XWayland).

**Comment by kovidgoyal** [comment]
resizing windows is the responsibility of the window manager, not the
application. kitty doesn't even have window resize code in it, it only
reacts to resize events from the window system. As such, I'm afraid I
dont see how this can be a kitty issue. You should report it to plasma
instead.
