### ISSUE TITLE
disable_ligatures cursor not working as expected

### ISSUE THREAD

**Issue by sfeuga** [kovidgoyal/kitty#2995]
**Describe the bug**
With `disable_ligatures cursor` setup, not all ligatured character are disabled under the cursor

**To Reproduce**
1. Use a font with ligature
2. Set in the _kitty.conf_: `disable_ligatures cursor`
3. Restart kitty to use the latest `kitty.conf` file 
4. Type `==` or `!=` and move the cursor back, it work as expected
5. Type `=>` or `=/=` and move the cursor back, it not work as expected (always see the ligatured typo)

**Expected behavior**
Typing `=>` and move the cursor back (on `=` or `>`) should display each separate characters and not the ligatured character

**Screenshots**

***Working*** 
![Kitty Ligatures ok](https://user-images.githubusercontent.com/5821408/94991912-489ce180-05c1-11eb-8cc8-8313b8c83b56.png)

***Not Working*** 
![Kitty Ligatures ko](https://user-images.githubusercontent.com/5821408/94991911-46d31e00-05c1-11eb-9abf-510441c8d5a5.png)

**Environment details**
OS:
- GNU/Linux Fedora 32 (kernel 5.8.11-200.fc32.x86_64)
- GNOME Shell 3.36.6
- X11
- Nvidia version 450.57

***Output of `kitty --debug-config`***
```
kitty 0.18.3 created by Kovid Goyal
Linux fedora 5.8.11-200.fc32.x86_64 #1 SMP Wed Sep 23 13:51:28 UTC 2020 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: ~/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity         0.9
bold_font                  Fira Code Bold
bold_italic_font           Source Code Pro Bold Italic
disable_ligatures          1
dynamic_background_opacity True
font_family                Fira Code Retina
font_features              {'FiraCode-Retina': ('+zero',)}
italic_font                Source Code Pro Italic
tab_bar_min_tabs           1
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
This will be because in recent fira code arrow ligatures are not
implemented as calt ligatures. This needs to be fixed in Fira Code, see
also https://github.com/tonsky/FiraCode/issues/1050
