### ISSUE TITLE
How do you install this on ubuntu 16?

### ISSUE THREAD

**Issue by SeunLanLege** [kovidgoyal/kitty#300]
when i run 

```zsh
make
```

I get

```zsh
python3 setup.py 
CC: gcc (5, 4)
Package harfbuzz was not found in the pkg-config search path.
Perhaps you should add the directory containing `harfbuzz.pc'
to the PKG_CONFIG_PATH environment variable
No package 'harfbuzz' found
harfbuzz >= 1.5 is required, found version: not found
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1
```

I have no idea what this means or what it wants me to do. Having an installer script would be nice 🤷‍♂️

**Comment by koekeishiya** [comment]
The error is saying that you are missing a dependency required for *Kitty* to build.
You can find a list of all dependencies that must be installed first here: https://github.com/kovidgoyal/kitty#installation

You can install these dependences using the package manager that is distributed with ubuntu (apt-get I believe).

**Comment by SeunLanLege** [comment]
```zsh
➜ sudo apt-get install libpng zlib harfbuzz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libpng
E: Unable to locate package zlib
E: Unable to locate package harfbuzz
```

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in maintaining distro specific installers. A bit of googling will show you how to search for package names on ubuntu, or look at the ,travis.yml file in the repo for the list of package names used in ubuntu.
