### ISSUE TITLE
Docs: Desktop notifications missing on website

### ISSUE THREAD

**Issue by Nudin** [kovidgoyal/kitty#3005]
On the [site about the protocol extensions](https://sw.kovidgoyal.net/kitty/protocol-extensions.html), the chapter "Desktop notifications" is missing even though it is listed in the TOC and is present in the file in the repo.

**Comment by kovidgoyal** [comment]
It's present for me
![Screenshot_20201005_162550](https://user-images.githubusercontent.com/1308621/95071697-b6fbb400-0727-11eb-9545-f324e59a2c59.png)

**Comment by Luflosi** [comment]
I can confirm, it's present for me too.

**Comment by Nudin** [comment]
I checked – it's Ublock origin that hides the section on Firefox. Haven't found why.

**Comment by jirassimok** [comment]
This happens specifically because one of uBlock Origin's standard filter lists, the EasyList Notifications list, blocks elements with the ID `#desktop-notifications`, which happens to be the title of the page.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/21214ee7e6d4a0fde4318443cfd85af2d22ac315
