### ISSUE TITLE
text browser {e}links messes up font rendering until reset

### ISSUE THREAD

**Issue by bartkmq** [kovidgoyal/kitty#301]
![kitty.gif](https://user-images.githubusercontent.com/25273823/35652783-77866fa8-06e5-11e8-9d30-59b03c0bd41e.gif)
How to reproduce:
1) start links or elinks

distro: Arch
shell: fish (also reproducible with sh)
xdg_session_type: wayland
packages:
- kitty-git v0.7.1.r1.ga9be05c-1
- elinks 0.13-19 
- links 2.14-3
- lynx 2.8.8-5
- gnome-terminal 3.26.2-1  

notes: 
- works fine in gnome-terminal
- lynx (also a text browser) works

**Comment by kovidgoyal** [comment]
This is likely because it switches the terminal to non UTF-8 mode. I haven't really tested/implemented non-UTF8 modes in kitty, as they are basically legacy baggage. You can easily check that run

kitty --dump-commands links

and you should see screen_designate_charset in the dump, indicate links is changing the charset.

**Comment by bartkmq** [comment]
Yep looks like it.
```
screen_designate_charset 1 48
screen_save_cursor
screen_set_mode 1000 1
screen_set_mode 1002 1
screen_reset_mode 1005 1
screen_reset_mode 1015 1
screen_set_mode 1006 1
save_cursor 1001 1
[PARSE ERROR] CSI s in private mode not supportedscreen_set_mode 1000 1
screen_erase_in_display 2 0
screen_cursor_position 1 1
screen_cursor_position 1 1
select_graphic_rendition 0 
draw                                                                                 
screen_cursor_position 2 1
draw                                                                                 
screen_cursor_position 3 1
draw
[...]                                                                                 
```

> I haven't really tested/implemented non-UTF8 modes in kitty, as they are basically legacy baggage.

Just to make that clear, I only started elinks to compare it to lynx so it doesn't really matter to me if this feature is implemented.
