### ISSUE TITLE
Unicode kitten startup delay eats key-presses

### ISSUE THREAD

**Issue by TyberiusPrime** [kovidgoyal/kitty#3012]
**Describe the bug**
I have a custom keyboard that types e.g. ü by sending  ctrl-shift-u / release / f / release / c / release / enter / release key 'presses' basically as quickly as usb will accept the reports.
This works fine in other apps, but in kitty, all it does is open the unicode kitten.

If I add a delay (press/release ctrl 10 times. 5 is too short), it works correctly.

So the problem appears to be that during the 'kitten startup', the keys get ignored, 
instead of forwarded to the kitten eventually.

**Expected behavior**
I'd like either the kitten to see the key presses, or a way to disable the kitten and use good old X11 unicode input (https://en.wikipedia.org/wiki/Unicode_input#In_X11_(Linux_and_other_Unix_variants_including_Chrome_OS) ) (mapping ctrl-shift-u to no_op unsuprisingly get's you no unicode input whatsoever).

The delay is very noticable and annoying in other applications.

**Environment details**
OS: Ubuntu 20.04

kitty 0.19.0

happens wit --config NONE

**Comment by kovidgoyal** [comment]
Why would pressing f,c,enter cause anything to happen in the unicode
input kitten? There is no such keybinding in that kitten.

I suggest you setup IME and use that if you dont like the unicode input
kitten, or better if you want a particular keypress to always generate some
text, use the send_text mapping in kitty.conf.

**Comment by TyberiusPrime** [comment]
'fc' is the hex code of the character I want.
If I press manually, slowly, ctrl+shift+u (to trigger the kitten) then 'f' then 'c' (to select ü) then enter I get my ü.

But if I type it 'very fast', I don't. 
The 'f', 'c', and 'enter' don't make it to the kitten.

I can even trigger the 'eating fc' by hand.

**Comment by kovidgoyal** [comment]
In any case, why are you doing all this? If you want to press a key, and
get ü simply add

map <whatever key> send_text all ü

to kitty.conf, there is zero need to go through the unicode input kitten
at all.

**Comment by TyberiusPrime** [comment]
Because it is not about kitty. That physical key, sending that key sequence works in Firefox, office, any gtk or at app etc.
It does not work in kitty.

I'd happily remap the unicode kitty some place else it that made the x11 unicode input work.

**Comment by Luflosi** [comment]
Try putting `kitty_mod+u no_op` into your kitty.conf.

**Comment by Luflosi** [comment]
Put it at the very bottom to be on the safe side.

**Comment by kovidgoyal** [comment]
You say you have a physical key that generates multiple key presses? So
map the multiple key-presses in kitty.conf

map ctrl+u>f>c>enter send_text all whatever

And no kitty is never going to support "good old" X11 unicode input.

**Comment by trygveaa** [comment]
> Try putting kitty_mod+u no_op into your kitty.conf.

The input method he's talking about is GTK specific, so it won't work in kitty even if you unmap the unicode kitten.

> good old X11 unicode input

As far as I know, it's GTK specific, not anything standard in X11. Why don't you use something more generic, like xbindkeys and xdotool?

**Comment by kovidgoyal** [comment]
Oh and the original issue has nothing to do with startup delay, it's because the kitten discards pending input on the tty device at startup.

**Comment by TyberiusPrime** [comment]
> And no kitty is never going to support "good old" X11 unicode input.
But it already does! The unicode kitten, with it's default binding of ctrl-shift-u
follows exactly the second X11 method. 
It just has a timing issue if the hex codes / enter occur before the kitten has started.

>As far as I know, it's GTK specific, not anything standard in X11. Why don't you use something more generic, like xbindkeys and xdotool?

Because I use this keyboard on windows, linux and mac, with a toggle to choose the right unicode input method. I really don't want to have to define my keys in more places than my keyboard's firmware. 
And to be honest, kitty is the first piece of linux software I've found that didn't support it.

Now I totally understand that all this unicode-over-usb-input is arcane, historical terminally stupid (especially with the OS not having the same magic keycombos), and niche.
And I have a workaround for me by adding a delay.

But your 'kitten startup' eats key strokes. 
You decide whether that's acceptable in a terminal.

**Comment by kovidgoyal** [comment]
Using an interactive input method to automate input of special characters is pretty silly, and a big waste of resources. You should follow what @trygveaa advised you to do and use the actual facilities provided by X11 for programming input. However, if you inisist on doing things in this bone-headed fashion, I have changed the kitten to not discard pending input on startup do you should be fine.

**Comment by TyberiusPrime** [comment]
> However, if you inisist on doing things in this bone-headed fashion, I have changed the kitten to not discard pending input on startup do you should be fine.

I appreciate it.

And as for the 'X11 programming input methods':  I just prefer my keyboard not to be reliant on the host being configured especially for it.

**Comment by trygveaa** [comment]
> And to be honest, kitty is the first piece of linux software I've found that didn't support it.

Oh, given that you're saying this I guess you're using ibus? kitty supports that if you set `GLFW_IM_MODULE=ibus`.

**Comment by TyberiusPrime** [comment]
> Oh, given that you're saying this I guess you're using ibus? kitty supports that if you set `GLFW_IM_MODULE=ibus`.

That does disable the kitten for me and allows unicode input. 
Thank you.
