### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory when using listen_on remote control

### ISSUE THREAD

**Issue by historymaker118** [kovidgoyal/kitty#3013]
**Describe the bug**
Trying to update all running kitty instances with new colour scheme throws error when using sockets

**To Reproduce**

I have the following in my kitty.conf

allow_remote_control yes
listen_on unix:/tmp/mykitty

background #2F251E
foreground #DFC7B9

cursor #F8F1EC

selection_background #C59A81
selection_foreground #4B83A3

color0  #47392D
color8  #3F3228

color1  #BF8F73
color9  #CFAB96

color2  #B48B5C
color10 #C5A581

color3  #4F2214
color11 #572516

color4  #8A7E79
color12 #968B87

color5  #F8F7EC
color13 #FFFFFF

color6  #7A823C
color14 #8C9545

color7  #B46D5C
color15 #C58F81

I then run

kitty @ --to unix:/tmp/mykitty set-colors -a ~/.config/kitty/kitty.conf 

and I get the following error

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 121, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 117, in main
    func(sys.argv[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 23, in remote_control
    rc_main(args)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 187, in main
    response = do_io(global_opts.to, send, no_response)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 132, in do_io
    with io:
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 79, in __enter__
    self.socket.connect(self.address)
FileNotFoundError: [Errno 2] No such file or directory

**Expected behavior**
I expect for my colour scheme to update 

**Environment details**
OS: Linux Manjaro

**Comment by kovidgoyal** [comment]
Leave off the --to in your @ command and you will be fine.

**Comment by kovidgoyal** [comment]
As is noted in the docs of the listen_on config option, the actual path used has the PID of the kitty process added to it, so you cant specify it manually with --to. This is because the config file is shared by all kitty instances.

If you want to do that, use the --listen-on command line option instead.

**Comment by historymaker118** [comment]
I tried leaving off the --to flag but that only results in the current kitty window colours changing, if I have more than the one kitty terminal running, the colours do not update in those other windows which is what I want the command to do

**Comment by kovidgoyal** [comment]
Use --all

**Comment by historymaker118** [comment]
I'm using --all, still not getting anything other than the current kitty window updating.

**Comment by kovidgoyal** [comment]
--all works on all kitty windows in ONE kitty process. If you are
launching multiple kitty processes, then you will need separate commands
for each. Or alternately launch kitty with --single-instance then there
will be only a single kitty process, regardless of how many windows you
launch.

**Comment by historymaker118** [comment]
Brilliant that did the job! Thank you ever so much for your time and assistance I really appreciate it.
