### ISSUE TITLE
kitty killed when window unmapped => unable to use tdrop for pulldown mode

### ISSUE THREAD

**Issue by vapniks** [kovidgoyal/kitty#3016]
Hi,
    if I have kitty open, and issue the following command:
```
> xdotool search --class kitty windowunmap 
```
I get the following error, and the entire kitty process is killed:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x46e092
  Serial number of failed request:  478
  Current serial number in output stream:  478

[1]  + 29797 exit 1     kitty --config NONE
```
Normally this should just hide the window rather than kill the application.

This means that kitty doesn't work with tdrop (https://github.com/noctuid/tdrop) because tdrop uses xdotool to hide the window.
Is there any other way to hide the kitty window programmatically?

**Comment by kovidgoyal** [comment]
Works fine for me with kitty 0.19.1 on i3, with the following test:

```
kitty --config NONE --class test sh -c "sleep 1; xdotool search --class test windowunmap; read"
```

**Comment by vapniks** [comment]
I forgot to mention that I was using kitty version 0.16.0
kitty version 0.18.3 seems to work OK with xdotool.
