### ISSUE TITLE
tmux 3.2-rc2 fails to show truecolor under kitty, despite 3.1b working

### ISSUE THREAD

**Issue by mfontani** [kovidgoyal/kitty#3018]
**Describe the bug**

Using the bog-standard configuration of both tmux and (latest) kitty, tmux 3.1b properly shows a truecolor bar, whereas tmux 3.2-rc2 does not.

I think I've traced/bisected this to 2ab6f57159ac4b406148208e2972c6784f502f78, and specifically this part:

```
+    # Set RGB foreground color (non-standard used by neovim)
+    'setrgbf': r'\E[38:2:%p1%d:%p2%d:%p3%dm',
+    # Set RGB background color (non-standard used by neovim)
+    'setrgbb': r'\E[48:2:%p1%d:%p2%d:%p3%dm',
```

If I clone the kitty repo, comment-out those, `./build-terminfo` and copy the resulting updated `xterm-kitty` file in my home's location, all works in all tmux versions. That's what I'm doing right now but feels icky.  I'd like to understand what/who is causing which problem - tmux or kitty. Right now my guess is kitty, as undoing that recent change fixes things.

**To Reproduce**

I've created a Github repo containing all repro steps - from downloading and building the two versions of tmux, to running kitty in a docker container and showing the problem.  You can find it at https://github.com/mfontani/tmux-kitty-colors-bug

**Expected behavior**

A truecolor "bar" ought to be showable under both terminals, but isn't.

**Screenshots**

<img src="https://raw.githubusercontent.com/mfontani/tmux-kitty-colors-bug/master/kitty_0.19.1_tmux_3.1b__truecolor_ok.png">

<img src="https://raw.githubusercontent.com/mfontani/tmux-kitty-colors-bug/master/kitty_0.19.1_tmux_3.2-rc2__truecolor_not_ok.png">

**Comment by kovidgoyal** [comment]
That commit is over two years old, first appearing in kitty version
0.8.0. You are saying that tmux 3.1b works and tmux 3.2 doesn't, seems
pretty clear the bug is in tmux.

Report it to tmux, or better yet, stop using terminal multiplexers, they
are a plague: https://github.com/kovidgoyal/kitty/issues/391#issuecomment-638320745

**Comment by mfontani** [comment]
If someone ends up here looking for a fix, I think I've found one on the tmux side:

    set-option -as terminal-features ',xterm-kitty:RGB'

The above setting works on tmux 3.2-rc2 but is a "new" option that cannot be set on 3.1b.

**Comment by trygveaa** [comment]
I reported it to tmux, it's been fixed now: https://github.com/tmux/tmux/issues/2418

**Comment by kovidgoyal** [comment]
On Tue, Oct 13, 2020 at 12:49:35AM -0700, Trygve Aaberge wrote:
> I reported it to tmux, it's been fixed now: https://github.com/tmux/tmux/issues/2418

Thanks :)
