### ISSUE TITLE
Support for Unicode input?

### ISSUE THREAD

**Issue by wimstefan** [kovidgoyal/kitty#302]
Hi, I was searching quite some time now to see if  Unicode input as defined below is supported as it is in termite with `Ctrl+Shift+u+unicode_numbers`?

https://en.wikipedia.org/wiki/Unicode_input

**Comment by SolitudeSF** [comment]
im pretty sure that Ctrl+Shift+u is a gtk specific feature

**Comment by wimstefan** [comment]
@SolitudeSF  yes it is a GTK specific feature that I use regularly ...
Any idea how to mimic that in kitty?

**Comment by kovidgoyal** [comment]
Note that most applications have their own unicode input technique, for example in vim it is ctrl+v,u,hex code. In zsh you use insert-composed-char (http://zsh.sourceforge.net/FAQ/zshfaq05.html) etc.

**Comment by wimstefan** [comment]
Yes I'm aware of the Unicode input techniques for vim and zsh and I use them but I'd also like to be able to do that in weechat and I haven't found a possibility yet. Hence my question ...

**Comment by kovidgoyal** [comment]
Well, it shouldn't be too hard to add unicode input support using the new overlay windows facility I am working on right now. It should be much nicer than GTK's ctrl+shift+u since it will show you active previews of the character you are typing and could, in theory, also have a choose character by name mode.

**Comment by kovidgoyal** [comment]
ALso, if you have a limited set of unicode cahrs you want to input, you can simply define keyboard shortcuts for them in kitty.conf using the send_text feature.

**Comment by egmontkob** [comment]
> im pretty sure that Ctrl+Shift+u is a gtk specific feature

Nope, or at least not solely. Konsole (KDE/Qt), xterm (plain Xlib) etc. also support this shortcut. It's more like an IM (input method) thingy.

**Comment by kovidgoyal** [comment]
Note that current the unicode input widget is pretty barebones, it allows you to type in the hex code and shows you what character will be input. I'll add features to it to search by chjaracter name and to remember recently used chars later.

**Comment by wimstefan** [comment]
Thank you so much!!! That looks already very promising and I see that you're still refining it. Many thanks for that :)

**Comment by kovidgoyal** [comment]
You're welcome :)

**Comment by kovidgoyal** [comment]
I finished the unicode input widget. It allows searching for characters by name, by hex code, by recently used, and even an editable favorites list. This is now the coolest unicode input widget I have ever used :)

**Comment by kovidgoyal** [comment]
And all this with a pure keyboard based UI.
![screenshot_20180213_105622](https://user-images.githubusercontent.com/1308621/36134707-9ea81110-10ac-11e8-8593-c9010385d202.png)

**Comment by wimstefan** [comment]
It's getting better with all that kittens ... ;-)
