### ISSUE TITLE
desktop's custom mouse icon/cursor

### ISSUE THREAD

**Issue by jaeheum** [kovidgoyal/kitty#3020]
**Is your feature request related to a problem? Please describe.**

kitty 0.18.3 on Gnome/Fedora31 uses a thin I-beam mouse cursor that is too small for comfortable use.

**Describe the solution you'd like**

I have a custom mouse icon/cursor set in Gnome and I'd like to see that as mouse cursor in kitty.
I.e. if user has a custom mouse theme/icon set, use that before using the current default.

**Describe alternatives you've considered**

Thicker i-beam with different colors (seems more complicated than reusing existing prefered one from the desktop environment)

**Comment by kovidgoyal** [comment]
kitty already uses custom mouse cursors, if installed correctly using
the XDG specification (not GNOME/KDE/whatever). 

https://wiki.archlinux.org/index.php/Cursor_themes

**Comment by jaeheum** [comment]
Actually I had the cursor theme installed correctly -- I see my customized cursor shape `arrow` okay with
`pointer_shape_when_grabbed arrow`, However, the title and suggestion for solution were incorrectly stated.

My suggestion should've been: Can we have an option of `default_pointer_shape` with the valid values `arrow`, `beam` and `hand`? My problem is that unless the program running is grabbing the mouse, the cursor shape is always the beam. For example, `icat some.png` and mouse hovering on top of the image shows `beam` cursor. I'd rather see `arrow`, until I start sweeping/selecting text with the mouse. Thanks.

**Comment by kovidgoyal** [comment]
That would require both a setting for the default shape and code to
change it while dragging, doesnt seem worth the effort to me. Patches
welcome.
