### ISSUE TITLE
Kitty window is positioned incorrectly using wmctrl

### ISSUE THREAD

**Issue by myelsukov** [kovidgoyal/kitty#3023]
**Describe the bug**
I am using `wmctrl` to layout windows on the desktop. All applications but kitty behave as expected but kitty's window is not positioned correctly.

**To Reproduce**
I started 4 different terminal emulators then positioned them at the same "Y" (100).
All windows but kitty were vertically aligned.
The window title is configured 21 pixels high in my Windows Manager. Window border width is configured as 4 pixel.

```
[14:45 me@MyBox ~] > # List windows
[14:45 me@MyBox ~] > wmctrl -lxG
0x03000002  0 133  215  3380 1820 Alacritty.Alacritty   MyBox [me@MyBox] ~
0x03c0001e  0 158  240  484  316  xterm.UXTerm          MyBox [me@MyBox] ~
0x03e0001e  0 183  265  484  316  xterm.XTerm           MyBox [me@MyBox] ~
0x0400000e  0 208  290  2211 1201 kitty.kitty           MyBox [me@MyBox] ~
[14:45 me@MyBox ~] > # Position windows at the same "Y" (100)
[14:45 me@MyBox ~] > wmctrl -i -r 0x03000002 -e 0,100,100,1000,2000
[14:46 me@MyBox ~] > wmctrl -i -r 0x03c0001e -e 0,150,100,1000,2000
[14:46 me@MyBox ~] > wmctrl -i -r 0x03e0001e -e 0,200,100,1000,2000
[14:46 me@MyBox ~] > wmctrl -i -r 0x0400000e -e 0,250,100,1000,2000
[14:46 me@MyBox ~] > # List windows again
[14:50 me@MyBox ~] > wmctrl -lxG
0x03000002  0 108  142  1000 2000 Alacritty.Alacritty   MyBox [me@MyBox] ~
0x03c0001e  0 158  142  1000 2000 xterm.UXTerm          MyBox [me@MyBox] ~
0x03e0001e  0 208  142  1000 2000 xterm.XTerm           MyBox [me@MyBox] ~
0x0400000e  0 254  121  1000 2000 kitty.kitty           MyBox [me@MyBox] ~
[14:50 me@MyBox ~] >
```
So kitty's window was positioned 21 pixels (or window title height) above the other windows.
The "X" gap was supposed to be equal to 50, but kitty's window was positioned only 46 (4 pixels or window border width) pixels apart from the previous window's left edge. 

**Expected behavior**
kitty's window is positioned predictably similar to any other application.

**Screenshots**
![Screenshot_2020-10-11_14-48-36](https://user-images.githubusercontent.com/18082026/95691434-13514e80-0bd4-11eb-9db7-bec016c34c13.png)

**Environment details**
OS: Arch Linux
Display manager: JWM (https://github.com/joewing/jwm)

```
kitty 0.19.1 created by Kovid Goyal
Linux MyBox 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64
Antergos Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/me/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control               y
background                         Color(red=250, green=243, blue=227)
bold_font                          DejaVu Sans Mono Bold
bold_italic_font                   DejaVu Sans Mono
close_on_child_death               True
cursor                             Color(red=147, green=147, blue=161)
enable_audio_bell                  False
enabled_layouts                    ['stack', 'tall:bias=70', 'fat:bias=70', 'grid', 'horizontal', 'vertical']
font_family                        DejaVu Sans Mono
font_size                          16.0
foreground                         Color(red=0, green=0, blue=43)
initial_window_height              (48, 'cells')
initial_window_width               (170, 'cells')
italic_font                        DejaVu Sans Mono
macos_option_as_alt                3
macos_quit_when_last_window_closed True
open_url_modifiers                 2
remember_window_size               False
scrollback_lines                   10000
Added shortcuts:
	 shift+control+m > a KeyAction(func='create_marker', args=())
	 shift+control+m > n KeyAction(func='scroll_to_mark', args=[False, 0])
	 shift+control+m > p KeyAction(func='scroll_to_mark', args=[True, 0])
	 shift+control+m > r KeyAction(func='remove_marker', args=())
```

**Comment by kovidgoyal** [comment]
On X11 kitty does not draw its own titlebar, so I dont see what I can
possibly do about this. The window manager sends kitty its geometry
information and kitty draws in that area.

**Comment by myelsukov** [comment]
I don't know what you can possibly do about this, but I wonder if you are curious why 3 other well known terminal emulators behave the same way while kitty behaves differently? I f I would be the author, I would  definitely try to understand why it happens. I have couple of ideas but I am not in the position to advise you :grin:

**Comment by kovidgoyal** [comment]
No, I'm afraid I am not curious. But if you are, patches are most welcome.

**Comment by myelsukov** [comment]
Just F.Y.I. (even though you are not curious :grin: )
This happens because GLFW configures native window with [Static gravity](https://github.com/kovidgoyal/kitty/blob/master/glfw/x11_window.c#L276) while most of applications known to me configure their windows with NorthWest gravity. 
So it's a feature, not a bug.

**Comment by kovidgoyal** [comment]
Thanks for letting me know. I wasn't interested, because I was pretty
sure, it is not a bug, given that as I said, kitty does not draw
titlebars on X11, so cannot influence windo size calculations involving
them.

**Comment by myelsukov** [comment]
Can I convince you to do a one-line change here: https://github.com/kovidgoyal/kitty/blob/master/glfw/x11_window.c#L276 ?

`hints->win_gravity = NorthWestGravity;` 

There are very nice scripts based on [xdotool](https://github.com/jordansissel/xdotool). Unfortunately they do not work for kitty because of that `win_gravity` hint.

**Comment by kovidgoyal** [comment]
As a first step get it accepted into upstream glfw. I am not familiar
enough with glfw+X11 to be confident that change has no other implications.

**Comment by cayhorstmann** [comment]
This is a true pain for me as well. I have a tiling script based on `wmctrl`. Fortunately it is my own script and I was able to munge it. Just in case someone has to do this: For Kitty (and presumably any other apps with this screwy gravity setting, which you can recognize by calling `xprop -id $ID | grep "window gravity: Static"`), you need to offset the x- and y- coordinates of `wmctrl` by 
```
FRAME_EXTENTS=($(xprop _NET_FRAME_EXTENTS -id $ID | cut -d '=' -f 2 | tr ',' ' '))
XOFF=${FRAME_EXTENTS[0]}
YOFF=${FRAME_EXTENTS[2]}
```
