### ISSUE TITLE
Certain glyphs from Iosevka not being rendered

### ISSUE THREAD

**Issue by rookie1024** [kovidgoyal/kitty#3026]
**Describe the bug**
Using Iosevka with at least one character variant selected causes kitty to stop rendering certain glyphs or runs of glyphs correctly. 

**To Reproduce**
1. Install Iosevka 3.6.3
2. Install kitty 0.19.1
3. Run kitty with the MVE config posted below
4. Certain glyphs (notably `i`, `j`, and any run of non-whitespace glyphs following them) will not cause the corresponding cells to update, rendering as either blank or any previously-drawn contents of the cell

**Screenshots**
Kitty running the minimal config below, displaying "the quick brown fox jumps over the lazy dog":
![image](https://user-images.githubusercontent.com/6175424/95782935-ad250400-0c85-11eb-824b-72ee506ced34.png)

**Environment details**
* **OS:** Arch Linux x86_64
* **Host:** X570 AORUS ULTRA (BIOS F22)
* **CPU:** AMD Ryzen 9 3950X
* **Kernel:** 5.4.70-1-lts
* **Graphics drivers:** NVIDIA binary v455.28 (GeForce GTX 1080)

```
$ kitty --config /tmp/kitty.conf --debug-config
kitty 0.19.1 created by Kovid Goyal
Linux <hostname> 5.4.70-1-lts #1 SMP Wed, 07 Oct 2020 23:54:51 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /tmp/kitty.conf
Running under: X11

Config options different from defaults:
font_family   Iosevka
font_features {'Iosevka': ('+cv14',)}
```

**Additional context**
Config required to produce:
```cfg
font_family Iosevka
font_features Iosevka +cv14 # also occurred with +cv19 and/or +cv38
```

**Comment by rookie1024** [comment]
Forgot to mention that commenting out the second line in the above config results in all glyphs rendering correctly:
![image](https://user-images.githubusercontent.com/6175424/95783900-a39c9b80-0c87-11eb-9cdd-7f1cc2ea4ae5.png)

**Comment by kovidgoyal** [comment]
Iosevka is not a suitable font to use with kitty. It has infinite length ligatures. kitty supports a maximum of length 9 ligatures. You will get breakage with Iosevka. As such I'm afraid I am not motivated to look into rendering issues with it, sorry. Patches are, of course, welcome. See #297
