### ISSUE TITLE
images are not confined to "output" space and might overlay with terminal text after resize

### ISSUE THREAD

**Issue by FlorianLudwig** [kovidgoyal/kitty#3029]
**Describe the bug**

**To Reproduce**
1. icat image
2. resize window
3 during resize the image does not behave as expected
4. after resize - if line breaks change - image overlaps with text / moves / ...

**Expected behavior**
The image should be confined to the space between `icat` and the next prompt

**Screenshots**

![image](https://user-images.githubusercontent.com/432263/95978451-7df3cb80-0e1a-11eb-8a5e-6462cd6cdbe2.png)

After resize

![image](https://user-images.githubusercontent.com/432263/95978718-d6c36400-0e1a-11eb-9aa8-3178e2a7fd86.png)

**Environment details**

```
Linux knight1 5.8.13-200.fc32.x86_64 #1 SMP Thu Oct 1 21:49:42 UTC 2020 x86_64
\S
Kernel \r on an \m (\l)
Your Wayland compositor does not support server side window decorations, disabling Wayland. You can force Wayland support using the linux_display_server option in kitty.conf See https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html for more information.
Running under: X11

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
No, I'm afraid not. This is not feasible. Resizing reflows text, and there
is no concept of "prompt" in a terminal, that's an artifact of the
shell.
