### ISSUE TITLE
Some ligatures not correct in mysterious circumstances

### ISSUE THREAD

**Issue by NAlexPear** [kovidgoyal/kitty#303]
Running 0.7.1, I just noticed a regression in how two hyphens (`--`) are displayed. It appears 0.7.1 attempts (and fails) to treat the two hyphens as a ligature when using a ligature-enabled font (in my case Fira Code). Some screenshots:

0.6.x
![2018-02-01-113557_924x482_scrot](https://user-images.githubusercontent.com/9038489/35693640-60ff2f86-0744-11e8-8260-c206710cac9e.png)

0.7.1
![2018-02-01-113607_924x481_scrot](https://user-images.githubusercontent.com/9038489/35693654-6d5ac9d4-0744-11e8-9259-11592b09a4bd.png)

**Comment by kovidgoyal** [comment]
Works for me, with

```
kitty --config NONE -o "font_family=Fira Code" sh -c "echo '--'; read"
```

**Comment by NAlexPear** [comment]
Odd, this must have been a bug that started somewhere else along the pipeline... sorry for the clutter, and thanks for taking a look!

**Comment by wbthomason** [comment]
@NAlexPear For what it's worth, I am also seeing this behavior in Kitty with Fira Code, as well as oddities in rendering a few other ligatures. It is intermittent, and I haven't yet figured out what makes a ligature render correctly/incorrectly.

**Comment by kovidgoyal** [comment]
If you can figure out some steps to reproduce it, I will be most interested.

**Comment by wbthomason** [comment]
The other two ligatures I have noticed this behavior with (in addition to `--`) are `..` and `*/` (though I haven't tested the full set of ligatures to see if there are other regressions. I'm using Fish in tmux in Kitty. I see these regressed renderings in plain Fish and in Neovim (all I've tested so far).

Interestingly, after running the example @kovidgoyal gave above for `--`, I can no longer seem to reproduce that particular issue. The same seems to be true for `..` when I run the same example with that ligature instead of `--`, but trying this trick for `*/` seems to have no effect.

**Comment by kovidgoyal** [comment]
That's just strange, there is no font rendering data persisted between invocations of kitty. Incidentally what OS are you on?

**Comment by kovidgoyal** [comment]
Also is you have some set of steps to reproduce the bad rendering, you can use the --dump-bytes option to create a dump that I can use to try to reproduce.

**Comment by wbthomason** [comment]
I agree, it is very strange. I am on Arch Linux, fully updated. If I can ever figure out a consistent way to reproduce the issue, I'll report the steps and dump here.

**Comment by NAlexPear** [comment]
@wbthomason I'm on Arch as well, and haven't been able to reproduce since running that command from @kovidgoyal. Maybe it's an Arch-specific font caching issue?

**Comment by kovidgoyal** [comment]
I'm on Arch too, but I have not seen it.

**Comment by LeonardKoenig** [comment]
Got similar unpredictable results here, but mostly they can be triggered in ViM, as if the shell line-editor wouldn't be complex enough to trigger it often enough.

I'll try some bisecting

**Comment by kovidgoyal** [comment]
If you can trigger it use --dump-bytes and post the dump, that should allow me to reproduce it.

**Comment by kovidgoyal** [comment]
OK I'll take a look when I have a moment.
