### ISSUE TITLE
Error opening shared object file libxcb-xkb.so.1 while executing kitty

### ISSUE THREAD

**Issue by Visual-mov** [kovidgoyal/kitty#3033]
**Describe the bug**
I just downloaded the latest Linux x86 binary for Kitty, and it throws this error:
```
[288 12:39:13.603150] Traceback (most recent call last):
  File "kitty/main.py", line 345, in main
  File "kitty/main.py", line 333, in _main
  File "kitty/main.py", line 102, in init_glfw
  File "kitty/main.py", line 96, in init_glfw_module
RuntimeError: Failed to dlopen /home/visual/Downloads/kitty/lib/kitty/kitty/glfw-x11.so with error: libxcb-xkb.so.1: cannot open shared object file: No such file or directory
```
I've tried the second latest release (0.19.0) and got the same error. I'm new to Kitty, so I don't know if this is something on my part. Is there some dependency I'm missing?

**To Reproduce**
1. Download version 0.19.1 Linux x86 release binary.
2. Extract files into folder
3. `cd ./bin` and execute kitty.

**Environment details**
OS: Ubuntu 20.04 LTS, Linux kernel 5.4.0-51-generic.
(Don't know if this is relevant, but Python version is 3.8.5).

```
Output of kitty --debug-config:

kitty 0.19.1 (73db717a0c) created by Kovid Goyal
Linux visual-Spin-SP315-51 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Running under: X11

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
You are missing libxcb-xkb

**Comment by Visual-mov** [comment]
Ah okay! Does it say how to install the dependencies somewhere on the website? Because the impression I got was you just download and execute. I've now just installed it using apt instead.

**Comment by kovidgoyal** [comment]
Nothing in this world can just install and run. At a minimum you need a
working kernel, system libraries, etc. This libxcb-xkb is part of the X
server system libraries. How to install it depends on what linux distro
you are using.

**Comment by bheadmaster** [comment]
I'm sorry for commenting on the closed issue, but I'm having the same issue, so I thought I'd just continue here, so we would have a single place for everyone who searches for this particular issue.

Here's my `uname -a`:

    Linux thinkpad 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

After downloading kitty version `0.20.1`, the `Linux x86 binary bundle` and extracting it to `.local/bin/kitty.app`, running `kitty` command gives the following error:

    [116 09:08:10.791047] Traceback (most recent call last):
      File "kitty/main.py", line 328, in main
      File "kitty/main.py", line 316, in _main
      File "kitty/main.py", line 103, in init_glfw
      File "kitty/main.py", line 97, in init_glfw_module
    RuntimeError: Failed to dlopen /home/pasko/.local/kitty.app/lib/kitty-extensions/kitty.glfw-x11.so with error: libxcb-xkb.so.1: cannot open shared object file: No such file or directory

Running `apt search libxcb-xkb` prints the following output:

    libxcb-xkb1/focal,now 1.14-2 amd64 [installed,automatic]
      X C Binding, XKEYBOARD extension

And `locate libxcb-xkb.so.1` prints the following output:

    /opt/bitwig-studio/lib/bitwig-studio/libxcb-xkb.so.1
    /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1
    /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1.0.0

I am not familiar with technical details of how libraries are resolved on GNU/Linux, so I don't know what else to do. In my experience, the presence of the shared library in `/usr/lib/x86_64-linux-gnu/` directory was always enough for the linker to do its magic.

I have been using `kitty` from the Ubuntu repositories (0.15.0-1), and it worked fine, but I heard that version 0.17 introduced image backgrounds which made me want to try out a newer version.

Any input with the issue would be appreciated!

**Comment by kovidgoyal** [comment]
A failure to dlopen means loading the library failed not that it was not
found. Probably because the version of the library is too old or one of
its depeneddencies in turn is missing. You can
use the LD_DEBUG env var to get more information. But most likely you
will need to either update Ubuntu or build kitty from source yourself.
https://sw.kovidgoyal.net/kitty/build.html

**Comment by bheadmaster** [comment]
Thank you for your swift reply. I have built kitty from source and everything seems to work now. Cheers!
