### ISSUE TITLE
Support for bash process substitution in kitty diff

### ISSUE THREAD

**Issue by nzec** [kovidgoyal/kitty#3037]
**Is your feature request related to a problem? Please describe.**
Currently kitty diff doesn't work with process substitution in bash.
Example:
If i do something like:
```sh
kitty +kitten diff <(command1) <(command2)
```
it shows never shows any diff.

**Describe the solution you'd like**
I would like for it to work.

**Describe alternatives you've considered**
Process substitution does work if you use an external script to make a temp file or use process substitution on fish:
```sh
kitty +kitten diff (command1 | psub) <(command2 | psub)
```

**Additional context**
It might be because of bash's use of file-descriptors or something (it returns `/proc/[pid]/fd/[something]` while fish's psub returns `/tmp/.psub.[something]`) though I obviously have no clue.

Apparently `git diff` also doesn't work with bash process substitution: https://stackoverflow.com/q/22706714/7345209

**Comment by kovidgoyal** [comment]
Well the diff kitten uses git diff under the hood so if git diff doesnt
support it neither will the kitten. You can change the diff command https://sw.kovidgoyal.net/kitty/kittens/diff.html#opt-kitten-diff.diff_cmd

that might help.

**Comment by nzec** [comment]
Setting `git_cmd` to `diff -p -U _CONTEXT_ --` as is there in [kittens/diff/patch.py](https://github.com/kovidgoyal/kitty/blob/master/kittens/diff/patch.py) gives the error: `Could not find the diff -p -U 3 -- executable. Is it in your PATH?`.

Setting it to anything gives the same error.

**Comment by kovidgoyal** [comment]
Dont put quotes around it

**Comment by nzec** [comment]
Now it says:
```
diff: /proc/2171/fd/pipe:[31449]: No such file or directory
diff: /proc/2171/fd/pipe:[31451]: No such file or directory
```

I am guessing it is a problem with GNU diff.

I'll just not use some psub script. Sorry for bothering.
