### ISSUE TITLE
Add a flag to `kitty @ send-text` to slow down how quickly it sends text to a window?

### ISSUE THREAD

**Issue by cpdean** [kovidgoyal/kitty#3039]
This is a weird ask, but is there a way to slow down how fast the text streams into a terminal from `kitty @ send-text`?

I rely on a workflow that requires wiring my text editor to a remotely-controlled terminal window, sending selected text to it so that code executes in an interpreter.  I've found that in my database client, `psql`, if I send too much text at once, the client is not able to parse everything as it comes in and throws syntax errors.

I've tried modifying my script for sending text between windows by slowing down the input to `kitty @ send-text` but `send-text` seems to wait until the upstream command is done streaming text in slowly

```
#!/bin/bash
ruby -pe 'sleep 0.3' | kitty @ send-text --match=num:1 --stdin
```

For what it's worth, tmux's features for sending text between terminals also has this problem, flooding postgres's native client `psql` with SQL faster than it can reliably parse.

As a workaround, I can flatten my query to a single line and both tmux and kitty are able to flush the text to the client and it parses fine.  There isn't a great way to automate that solution, since single-line comments would break with a simple flatten, and for languages that cannot  be transposed to single lines it also poses a problem.

Alternatively -- is there a way I could implement `kitty @ send-text` as my own `kitten` plugin and put a small delay between lines flushed into a terminal? That might be a worthwhile workaround.

Thanks!
kitty is great and I'm really enjoying it so far!

Also, calibre is fantastic!!

Kitty 0.19.1
macOS 10.15.7

**Comment by kovidgoyal** [comment]
I'm afraid I am not going to add a slow down feature to send text, but
the solution seems simple to me. If you cannot modify psql to fix its
input handling bug, write your own wrapper script for it, and run that
instead of psql and have it do whatever is needed to process/delay the
input. This will work with any terminal implementation,
tmux/kitty/whatever.

Or alternately, a wrapper script for send text that chunks the text as
need, calls send text then sleeps after each chunk.

**Comment by cpdean** [comment]
> write your own wrapper script for it, and run that instead of psql and have it do whatever is needed to process/delay the input. This will work with any terminal implementation, tmux/kitty/whatever.

I'm probably not going to be able to figure out how to wrap `psql` in something that'll buffer input, as I'm using it as an interactive client.

> Or alternately, a wrapper script for send text that chunks the text as need, calls send text then sleeps after each chunk.

I had thought that this is what I was already doing, but I realize now that slowing the pipe streaming into `kitty @ send-text` wasn't working because `kitty @ send-text` would just wait until the pipe closed anyway.

I came up with this simple alternative, that works, but is very slow.  The query that was breaking `psql` is 392 lines long, and with `send-text` taking some time per invocation it would take about 3 seconds to send the query, but this was a mostly usable work around:

```
#!/bin/bash
while IFS= read -r line; do
    echo "$line" | kitty @ send-text --match=num:1 --stdin
done
```

I did some digging into how to batch lines up for `send-text` and came up with this in python:

```
#!/usr/bin/env python
import sys
import io
import subprocess

# warning: this buffers all of stdin into memory
lines = sys.stdin.readlines()
batch_size = 40

for i in range(0, len(lines), batch_size):
    batch = lines[i:i+batch_size]
    kitty = subprocess.run(
        ["kitty", "@", "send-text", "--match=num:1", "--stdin"],
        input=''.join(batch),
        encoding='ascii'
    )
```

And this works!  At about 50 lines per flush the parser in psql's repl starts to break, but 40 lines per flush is fast enough that it doesn't feel slow.

Thank you for your advice!  I hope others find the above useful, too.
