### ISSUE TITLE
Reducing the size of the window creates/deletes lines

### ISSUE THREAD

**Issue by bartkmq** [kovidgoyal/kitty#304]
When resizing vertically there are new lines being created and when resizing horizontally lines are deleted.
[Example](http://webmshare.com/wyz3a)

distro: Arch
shell: fish (also reproducible with sh)
xdg_session_type: wayland
packages:

    kitty-git v0.7.1.r1.ga9be05c-1
    elinks 0.13-19
    links 2.14-3
    lynx 2.8.8-5
    gnome-terminal 3.26.2-1

 - works fine in gnome-terminal

**Comment by kovidgoyal** [comment]
dup of #242
