### ISSUE TITLE
Text in Bengali language aren't rendered properly

### ISSUE THREAD

**Issue by cubte** [kovidgoyal/kitty#3045]
**Describe the bug**
Text in Bengali language aren't rendered properly. Sometimes they are not even rendered.

**To Reproduce**
Have a file containing text in Bengali and `cat` it.

**Expected behavior**
I should be able to see the file content.

**Environment details**
OS: Linux arch 5.9.1-arch1-1

**Comment by kovidgoyal** [comment]
kitty renders text in a character grid, for performance reasons, this
kind of rendering is never going to work well with scripts that dont fit
in a character grid, like Arabic or Indic languages. You are better off
using a different terminal emulator for this use case.

**Comment by cubte** [comment]
You are from India and you have done this to your program.
