### ISSUE TITLE
Option/alt + left click should move cursor to that location in the terminal

### ISSUE THREAD

**Issue by Jon-Schneider** [kovidgoyal/kitty#3046]
**Is your feature request related to a problem? Please describe.**
In the default Mac Terminal and iTerm option/alt + left clicking within text I have typed will navigate to that character.

**Describe the solution you'd like**
Kitty should also implement this functionality.

**Describe alternatives you've considered**
I use emacs bindings to move around text in kitty but with long commands (e.g. git commit message string literals from 'git commit -m') it would be nice to have.

**Additional context**
My sole platform is Mac, I haven't tested this in Linux Terminal or Linux iTerm

**Comment by kovidgoyal** [comment]
Sorry, this is not worth the effort for me. Patches welcome.

Indeed, I dont see how this could be implemented robustly in general
anyway. Moving the cursor in response to clicks behind the back of the
shell, will break things, since the shell will now have no idea where
the cursor is.
