### ISSUE TITLE
[glfw error 65544]: X11: The DISPLAY environment variable is missing  [headless]

### ISSUE THREAD

**Issue by mcondren** [kovidgoyal/kitty#3047]
**Describe the bug**
GLFW cannot initialize when launching kitty via SSH session.  My server is headless and I interact with it only over SSH.  Do I need to choose a different terminal replacement for xterm that doesn't use OpenGL?

**To Reproduce**
1. apt-get install kitty
2. use debian update-alternatives to make kitty the default x-terminal-emulator
3. run /usr/bin/kitty
4. [glfw error 65544]: X11: The DISPLAY environment variable is missing GLFW initialization failed

**Environment details**
OS: Debian 10.6
Headless server
No X-server

```
Output of kitty --debug-config
Same error as above

**Comment by kovidgoyal** [comment]
How do you expect an X11 program to work without X11?? If you want to
ssh into a server you run SSH inside the terminal, not the terminal
inside SSH. If you mean you want to run kitty locally on the server and
have it appear on your desktop via X11 forwarding, I have no idea why,
and I doubt OpenGL works over X11 forwarding.

**Comment by val-byte** [comment]
i have the same problem on my vm and i want help to fix it

**Comment by microfx** [comment]
same problem...

**Comment by sv866729** [comment]
Funny thread lol
