### ISSUE TITLE
Line height differs between retina/non-retina display

### ISSUE THREAD

**Issue by thomasjachmann** [kovidgoyal/kitty#305]
Got this on a Retina MacbookPro (2016) running macOS Sierra (10.12.6).

The line height is different on hidpi and lowdpi monitors. The character height seems to be the same, just the spacing between the lines is 1px off. Measured from bottom end of a 2 to the next two in the line below in the attached screenshots, the line height is 25px on a retina display and 26px on a non-retina display. This is nothing really serious, it's just a tiny quirk in the display. If you move a window between monitors, you also see the lines jump because of that just after you switched monitors. On bigger windows, this leads to more or less lines being visible.

Retina display:
<img width="520" alt="bildschirmfoto 2018-02-02 um 22 19 33" src="https://user-images.githubusercontent.com/3219/35755808-0bba7136-0869-11e8-951d-528675cb47ef.png">

Non-retina display:
![bildschirmfoto 2018-02-02 um 22 19 38](https://user-images.githubusercontent.com/3219/35755811-0e676d4e-0869-11e8-84f5-0ba360a1ba9d.png)

I'm using the font "Hack" (installable via `brew cask install font-hack`) in 11.0pt in the screenshots above, but this also happens with the standard monospace font.

**Comment by kovidgoyal** [comment]
I'm confused, why would the line height or, indeed, any dimension be the exact same on displays with different DPI? When a measurement, such as font size, is specified in pts it has to be converted to pixels for display based on the monitor's DPI. What should be (almost exactly) the same is the physical size. The reason the sizes can be different by 1px is because of rounding errors when representing a floating pt value (size in pts * dpi) as an integer (px). If you look at cell_metric() in core_text.m you will see the cell height comes entirely from dimensions specified by CoreText, all kitty does is take the number provided by CoreText and add them together and call ceilf() on the result.

**Comment by thomasjachmann** [comment]
I don't expect the line height to have the same

**Comment by thomasjachmann** [comment]
I don't expect the line height to be the same amount of physical pixels. But I'd expect it to be the same in terms of virtual pixels (2x2 on my retina screen equalling 1x1 pixel on my non-retina screen). If they don't, the window changes it's layout when switching monitors, for larger windows even up to having different amount of lines. This is a bit irritating.

I checked using `roundf` or even `floorf` instead of `ceilf`, but this didn't change anything. Unfortunately, I'm not into macos development and can't be of much help here.

If you can think of anything you could do outside of CoreText (or by configuring CoreText), I'd be happy to have the same layout on all monitors, like eg iTerm2 has. If this is too minor and not worth the effort, then ok.

**Comment by kovidgoyal** [comment]
Well you could just add code to update_cell_metrics() in fonts.c to adjust the cell height to be the same as the previous value, regardless of what coretext wants. Use a global variable (in global_state) that is set in update_os_window_viewport() that is read by the update_cell_metrics(). If set update_cell_metrics() should adjust cell_height to maintain previous value (scaled by viewport_y_ratio).

**Comment by kovidgoyal** [comment]
With https://github.com/kovidgoyal/kitty/commit/328f22adab77b671f2ba6d05a0b75a3a4ebea437 update_cell_metrics() now knows when it is called for a DPI change. The rest should be trivial to implement. I dont have any way to test multi-DPI so I am not going to do it. You just need to adjust cell_height to match scaling_factor * global_state.cell_height
