### ISSUE TITLE
Can `kitty @ send-text` send key commands like <ctrl-u>?

### ISSUE THREAD

**Issue by cpdean** [kovidgoyal/kitty#3050]
Tmux has a feature in its send-text equivalent command that allows you to send keyboard commands like `Delete` and `<ctrl-u>` (delete line) to a given terminal that it's managing.  Is there a way to do that with kitty's `send-text`?

While using kitty to manage interactive repls, occasionally you'll send a command that results in a pager opening, meaning you will not be able to evaluate another command until you switch to the terminal to close it and then switch back to your text editor for sending the next command.  A vim plugin for sending text to tmux terminals gets around this by [sending the text `q` followed by `<ctrl-u>`](https://github.com/benmills/vimux/blob/master/plugin/vimux.vim#L44) to delete the current entered line of text before sending the selected text to the terminal.  Tmux's send-text command reads `C-u` and interprets it as `<ctrl-u>` and sends that to the terminal instead of reading it literally as `C`, `-`, `u`. This way the plugin is able to send a sequence of keypresses that will exit out of most pagers if one is open, or otherwise it will type `q` and delete it before sending the text if a pager is not open.

Is there a way to send this kind of keyboard input to a kitty terminal remotely?

**Comment by kovidgoyal** [comment]
Yes, as is noted in the documentation for send-text you can use it to
send arbitrary bytes. Use showkey -a to find what bytes ctrl-u generates
and then use the python syntax of \xXX to send those bytes using
send-text

**Comment by cpdean** [comment]
I wasn't able to use `showkey -a` on macOS, but @rouge8 pointed me to https://wiki.bash-hackers.org/syntax/quoting and suggested `$'\cu'` to get `ctrl-u`, and that seems to be working!

Forcing bash to interpret the characters into the right bytes works inline:

```
- ❯❯❯ kitty @ send-text --match=num:1 q # write 'q' to the terminal
- - -
kitty 0
- ❯❯❯ kitty @ send-text --match=num:1 $'\cu'  # and now delete it
- - -
kitty 0
- ❯❯❯ kitty @ send-text --match=num:1 q$'\cu'  # both together (shouldn't look like anything happens)
```

I still wanted to figure out how to look up the correct bytes on macOS and found this trick with `sed -n l` and the above control character interpretation that bash does:

```
- ❯❯❯ echo $'\cu' | sed -n l
\025$
- - -
kitty 0
- ❯❯❯ kitty @ send-text --match=num:1 q # write 'q' to the terminal
- - -
kitty 0
- ❯❯❯ kitty @ send-text --match=num:1 \\025  # and now delete it
```
