### ISSUE TITLE
Issue copying terminfo

### ISSUE THREAD

**Issue by michaelmcdonald** [kovidgoyal/kitty#3052]
Not sure where I'm going wrong / what I need to correct. Attempted to copy the term info over after reading the faq and encountered the following:

```
michael@monolith:~$ kitty +kitten ssh michaelmcdonald@10.33.33.33
"/var/folders/06/ppvyl1cd2mj481bnmx_hyzn80000gn/T/tmp.n3gChb7t", line 2, col 22, terminal 'xterm-kitty': older tic versions may treat the description field as an alias
"/var/folders/06/ppvyl1cd2mj481bnmx_hyzn80000gn/T/tmp.n3gChb7t", line 2, terminal 'xterm-kitty': /Users/michaelmcdonald/.terminfo: permission denied (errno 13)
Connection to 10.33.33.33 closed.
```

Target / source machines are macOS 10.15. Kitty version is 0.19.1

**Comment by kovidgoyal** [comment]
You dont have permission to create/access the
/Users/michaelmcdonald/.terminfo directory on the server.

**Comment by michaelmcdonald** [comment]
Appreciate the fast reply and response. Is there a way I can manually copy the necessary information over? A utility I'm attempting to run after SSH'ing in is complaining, giving the error:

```
Error opening terminal: xterm-kitty.
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by michaelmcdonald** [comment]
Running that command on macOS:

```
michael@monolith:~$ infocmp xterm-kitty | ssh michaelmcdonald@10.33.33.33 tic -x -o \~/.terminfo /dev/stdin
tic: /dev/stdin is not a file
```

**Comment by Luflosi** [comment]
Then do it manually like this: `infocmp xterm-kitty > infocmp.txt`, copy the file to the other machine with scp or other means and run `tic -x -o \~/.terminfo infocmp.txt` there.

**Comment by michaelmcdonald** [comment]
@Luflosi : that did the trick! Thank you!

For reference: had to `sudo` the command `tic -x -o ~/.terminfo/ infocmp.txt` (probably a security aspect with macOS Catalina if I had to guess)

**Comment by Luflosi** [comment]
That's odd, I don't have to use sudo to change any files on my home directory on macOS Catalina. Try this: Go to System preferences -> Security -> Privacy -> Full disk access (translated from German) and add your terminal emulator (probably kitty).

**Comment by michaelmcdonald** [comment]
> That's odd, I don't have to use sudo to change any files on my home directory on macOS Catalina. Try this: Go to System preferences -> Security -> Privacy -> Full disk access (translated from German) and add your terminal emulator (probably kitty).

I'm assuming you wanted this run on the target / remote machine? Unfortunately that's at my office (which I haven't been to in awhile...thanks COVID-19); however I'll try that the next time I'm in or see if I can setup a dummy / test machine at home with an old Mac and try again.

Can't thank you enough for the help / direction!
