### ISSUE TITLE
ssh kitten requires spaces between option and argument

### ISSUE THREAD

**Issue by John-Colvin** [kovidgoyal/kitty#3053]
`kitty +kitten ssh root@some.host.com -p22` gives `Option -p cannot occur in the middle`, wheras `kitty +kitten ssh root@some.host.com -p 22` works. `openssh` supports both styles, in keeping with most unix tools.

It wasn't too hard to guess what the problem was, but the error message wasn't exactly helpful.

Ideally the ssh kitten would be a perfect match for normal ssh, fixing this would be a helpful step towards that.

**Comment by Luflosi** [comment]
@kovidgoyal The problem is, that `enumerate()` in `kittens/ssh/main.py` splits `p22` into `p`, `2` and `2`.
