### ISSUE TITLE
Remote control: allow filtering of allowable commands to reduce attack surface

### ISSUE THREAD

**Issue by jtyers** [kovidgoyal/kitty#3061]
**Is your feature request related to a problem? Please describe.**
Like #2083 and #2076 I want to change color schemes via a keybind, so I can change from dark to light colours if I am using my laptop in a bright environment.

The solution to #2083 and #2076 is to use remote control. I have misgivings about enabling remote control as it presents a big security hole: any process on my machine with access to the kitty socket can now **type commands into any of my open kitty windows** among other things. Given I might have `sudo` active in one terminal, or active credentials to a client's production cloud environment in another, it's an unecessarily big attack surface in my view.

**Describe the solution you'd like**
I think there are two potential solutions to this problem:

1) allow remote-control to be configured to only allow a subset of commands - that way, folks like me can filter it down to only allow color-scheme changes, while others can allow the full feature set of remote control.

2) allow color-scheme changes via a key-binding

I think (1) would be the best solution here: if the filter is configurable, it could satisfy other related use cases where remote control in its current form is too risky and allows it to be harnessed to its full potential while remaining secure where that is needed.

**Comment by kovidgoyal** [comment]
You can change color schemes using terminal escape codes. Or via a
keybinding. https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by kovidgoyal** [comment]
And for the sake of any intrepid googlers that land here: you can open a dedicated kitty shell window to do remote control without enabling general remote control:

https://sw.kovidgoyal.net/kitty/remote-control.html#the-builtin-kitty-shell
https://sw.kovidgoyal.net/kitty/remote-control.html#allowing-only-some-windows-to-control-kitty

You can use *any* remote control command via a key mapping, also without enabling remote control:

https://sw.kovidgoyal.net/kitty/remote-control.html#mapping-key-presses-to-remote-control-commands

All this and more is documented on the kitty remote control page.

**Comment by jtyers** [comment]
Thanks - was obviously looking in the wrong part of the docs
