### ISSUE TITLE
Whitespace is compressed in window titles

### ISSUE THREAD

**Issue by infokiller** [kovidgoyal/kitty#3062]
**Describe the bug**
When the window title has multiple consecutive spaces, Kitty compresses them to a single space.

**To Reproduce**

1. Set the title to something with multiple places, for example execute `printf '\e]0;%s\a' "test         whitespace" && sleep 5` (the sleep is there in case your shell changes the title)
2. See the window title as "test whitespace"

**Expected behavior**
Whitespace is preserved in window titles.

**Screenshots**

![image](https://user-images.githubusercontent.com/10516814/97164694-31e64680-178b-11eb-8683-dbad1f5c0a57.png)

**Environment details**
OS: Name and version of operating system(s)

`Linux 5.8.16.a-1-hardened`

```
Output of kitty --debug-config
```

This can be reproduced with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
It's a feature not a bug :) Use unicode nbsp or similar.

**Comment by infokiller** [comment]
That complicates the config of other software that sets the window title and only supports space padding. Is there a way to disable the whitespace compression?

**Comment by kovidgoyal** [comment]
No, there is no such option, a PR adding one is welcome.

**Comment by infokiller** [comment]
OK, I just tested unicode nbsp and it doesn't work: whitespace is still compressed. Example:

```sh
kitty --config NONE bash -c 'printf "\e]0;my \u00a0 \u00a0 \u00a0 test\a" && sleep 30'
```

And I'll look into adding such an option.

**Comment by kovidgoyal** [comment]
Look for sanitize_title()

**Comment by infokiller** [comment]
Will do. Should this issue be re-opened since the nbsp doesn't work?

**Comment by kovidgoyal** [comment]
Not really, I just guessed it might, but sanitization hapens via a
python regex space operator, presumably that matches nbsp as well.
