### ISSUE TITLE
how can i clear the margin between titlebar and terminal?

### ISSUE THREAD

**Issue by iwfan** [kovidgoyal/kitty#3064]
![image](https://user-images.githubusercontent.com/28853200/97315367-9e546900-18a3-11eb-982e-74fb7551f626.png)

my config as follows

```
window_border_width 0.5pt
window_margin_width 0
single_window_margin_width -1
window_padding_width 0
```

**Comment by kovidgoyal** [comment]
Make your window have a size that is an exact multiple of cell size. Or use placement_strategy top-left in kitty.conf

**Comment by Luflosi** [comment]
You may also find `resize_in_steps yes` and something like `initial_window_width 80c`, `initial_window_height 28c` helpful.
