### ISSUE TITLE
Unable to click to select certain URLs

### ISSUE THREAD

**Issue by qiujiangkun** [kovidgoyal/kitty#3065]
**Describe the bug**
I'm not able to double click a URL like `http://localhost:8888/` to select it. I can only select a part of it by double-clicking.
![image](https://user-images.githubusercontent.com/33482468/97337710-96082800-18bb-11eb-83a9-95af374da0ab.png)
![image](https://user-images.githubusercontent.com/33482468/97337737-9ef8f980-18bb-11eb-9243-cd3ea5550589.png)

**To Reproduce**
`echo https://localhost:8888/`
Then double click on it

**Expected behavior**
Select all part of the URL

**Comment by kovidgoyal** [comment]
Yes colons are not considered part of words except at the start for well
known URL prefixes. If you want to also select colons when double
clicking use the setting for it in kitty.conf.
