### ISSUE TITLE
small sized glyph of nerd fonts

### ISSUE THREAD

**Issue by eoli3n** [kovidgoyal/kitty#3072]
**Describe the bug**
Kitty seems to print nerd font small sized. I read some explanation on different issues, but that's not clear to me.
Why is kitty printing Nerd glyphs small sized when most other terms does not ?

**To Reproduce**
Copy paste this in terminal
```
☸
```

**Expected behavior**
Icon to be the good size

**Screenshots**
Top is kitty, bottom is alacritty
![alacritty](https://user-images.githubusercontent.com/14223657/97959389-8ef78300-1daf-11eb-987d-0438c668cdf3.png)

**Environment details**
OS: Archlinux up to date
Font: JetBrains Mono
Config file:
- https://github.com/eoli3n/dotfiles/blob/master/roles/kitty/templates/kitty.j2
- https://github.com/eoli3n/dotfiles/blob/master/group_vars/all.yml

```
kitty 0.19.1 created by Kovid Goyal
Linux osz 5.4.69-1-lts #1 SMP Thu, 01 Oct 2020 20:40:59 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/user/.config/kitty/kitty.conf
[308 08:36:04.582983] Shortcut: "" has unknown modifier, ignoring
Running under: Wayland

Config options different from defaults:
background              Color(red=32, green=32, blue=32)
background_opacity      0.9
color0                  Color(red=40, green=42, blue=54)
color1                  Color(red=255, green=92, blue=87)
color10                 Color(red=90, green=247, blue=142)
color11                 Color(red=243, green=249, blue=157)
color12                 Color(red=87, green=199, blue=255)
color13                 Color(red=255, green=106, blue=193)
color14                 Color(red=154, green=237, blue=254)
color15                 Color(red=241, green=241, blue=240)
color2                  Color(red=90, green=247, blue=142)
color3                  Color(red=243, green=249, blue=157)
color4                  Color(red=87, green=199, blue=255)
color5                  Color(red=255, green=106, blue=193)
color6                  Color(red=154, green=237, blue=254)
color7                  Color(red=239, green=240, blue=235)
color8                  Color(red=104, green=104, blue=104)
color9                  Color(red=255, green=92, blue=87)
cursor_shape            2
enable_audio_bell       False
font_family             JetBrains Mono
font_size               10.0
open_url_modifiers      0
scrollback_lines        10000
touch_scroll_multiplier 5.0
window_padding_width    FloatEdges(left=10.0, top=5.0, right=10.0, bottom=5.0)
Added shortcuts:
	control+down KeyAction(func='change_font_size', args=(False, '-', 1.0))
	control+up KeyAction(func='change_font_size', args=(False, '+', 1.0))
```

**Additional context**
Same problem with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by eoli3n** [comment]
I prefer to be able to add a space to the next char and have a normal sized glyph, than to be stucked with a small sized glyph.
You just explain that kitty acts differently than other terminal emulators, and its a problem a FAQ.

``Adding a space after a glyph`` is a workaround to ``glyph is greedy about the space`` when terminal emulator acts like others.
What is the workaround to ``glyph is too small`` when kitty acts like that ?

Why do not propose an option in config file to let user choose that behavior ?

**Comment by eoli3n** [comment]
You can see a lot of spaces before and after :
![2020-11-03T14:29:47,772435206+01:00](https://user-images.githubusercontent.com/14223657/97991018-17dae280-1de1-11eb-89ce-23d42b0f8194.png)

**Comment by alperyilmaz** [comment]
The FAQ states that overflow might produce terrible results but tiny glyphs are also not so pleasant. Below is gnome-terminal and kitty at same font size. I wish there was a (practical) workaround for this :disappointed: 

Gnome-terminal:

![Screenshot_2020-11-20_03-57-45](https://user-images.githubusercontent.com/410615/99742956-ad66b980-2ae5-11eb-8a62-5e7cd89f9070.png)

Kitty:

![Screenshot_2020-11-20_03-59-32](https://user-images.githubusercontent.com/410615/99742969-b48dc780-2ae5-11eb-80cd-f574d70ad73e.png)

**Comment by eoli3n** [comment]
That's not a bug, that's a feature

**Comment by maximoab** [comment]
symbol_map U+f101-U+f21d nonicons
