### ISSUE TITLE
Bulletproof the terminal bell.

### ISSUE THREAD

**Issue by mcourteaux** [kovidgoyal/kitty#3078]
**Is your feature request related to a problem? Please describe.**
My pulse audio server died, and kitty froze every time I pressed tab to auto complete something. Kitty was trying to play the bell sound, while being unable to actually do so, resulting in a freezing terminal for around 2 to 4 seconds, before it gives up. Actually, I am surprised that it even froze. A sound generating piece of code should not stall the actual terminal emulation, and -- I think -- should always be running on anther thread to minimize input delay after a sound is produced.

**Describe the solution you'd like**
Run the bell in a separate thread, and time the duration of the bell procedure or something to give some feedback to the user that this might be happening. I don't know how the feedback would be, without being too intrusive. However, I spent over an hour trying to debug what was happening. Finally figured it out using `kitty --dump-commands`.

**Additional context**
Other terminal emulators I have, didn't have this problem, as they were probably configured to not play an actual bell sound (or they ran it in a different thread).

**Comment by kovidgoyal** [comment]
Your sound system dying is not something I feel the need to make kitty
robust against. At some point applications need to depend on system
services and not implement endless workarounds for system instability
issues. If your sound system of choice is flaky, you should switch to a
better one.

That said, kitty itself does play beeps in the background, via
ca_context_play http://0pointer.de/lennart/projects/libcanberra/gtkdoc/libcanberra-canberra.html#ca-context-play

If it is not backgrounding on your system, then libcanberra is broken on
your system and you should report a bug against it.

**Comment by mcourteaux** [comment]
This is actually disastrous with a properly working pulse audio. By default PulseAudio suspends on idle: https://askubuntu.com/questions/218444/sound-output-starts-delayed

This has the same effect: kitty freezes for several seconds. How do I report bugs for libcanberra? That project seems dead since 2012...

**Comment by kovidgoyal** [comment]
Why do you think I am the maintainer for libcanberra?? And no, sound taking several seconds to play is not normal, regardless of whether suspend on idle is loaded or not.

**Comment by mcourteaux** [comment]
You seem offended; there's no need for that. I'm only asking for help on how to report a bug for libcanberra. I currently fixed it for myself by disabling the "suspend-on-idle" feature.
