### ISSUE TITLE
Tab bar height margin

### ISSUE THREAD

**Issue by fchpr** [kovidgoyal/kitty#3079]
**Is your feature request related to a problem? Please describe.**
As per configuration docs there is no explicit way of setting tab bar height margin.

**Describe the solution you'd like**
Like `tab_bar_margin_width` but for height, or a multiparameter version `tab_bar_margin`.

**Describe alternatives you've considered**
Setting VTE margin via GTK styles file.

**Additional context**
I am not using a GTK environment so I'm still missing the fix.

**Comment by kovidgoyal** [comment]
The tab bar is composed of terminal cells, so its height is always the
same as line height of the rest of the terminal. It is controlled by the
font_size option. If you mean you want to add extra blank space around
the tab bar, then that is in theory possible, but is not something I am
interested in implementing, aptches welcome.
