### ISSUE TITLE
window.send_text in kitten fails the first time but not for subsequent attempts

### ISSUE THREAD

**Issue by jorgsk** [kovidgoyal/kitty#3083]
This might not be a bug, but something that I don't understand. I had my first attempt at a kitten, trying to do what vim-test does for launching tests but instead for launching the application I'm working on.

This is the relevant section of the kitty
```
def get_window(boss, title: str):
    try:
        w = list(boss.match_windows(f'title:{title}'))[0]
    except IndexError:
        w = None

    return w


def handle_result(args: List[str], answer: str, target_window_id: int, boss) -> None:

    w_name = 'app_launcher'
    w = get_window(boss, w_name)
    if w is None:
        boss.launch(f'--window-title={w_name}')
        w = get_window(boss, w_name)

    w.send_text("normal", "Hello, app launcher\n")
```

This is mapped to the Alt-a key combination. When called for the first time, a new window will be created but no text is sent to it. This message appears in the terminal that launched kitty:
```
[314 15:39:50.145030] Failed to send resize signal to child with id: 2 (children count: 1) (add queue: 1)
Failed to write to child 3 as it does not exist
```
The new window gets id 3, so the first message could be checking the wrong id for some reason. 

For subsequent invocations the expected text is written to the window, and neither of the two error messages are written. What I'm wondering is: why does this fail for the first attempt? I tried adding a sleep step of 1 s between launching the window and getting it back but that did not change anything.

**Comment by kovidgoyal** [comment]
First no need to use send_text, just directly call write_to_child, send
the reason it fails the first time is that the child does not exist yet,
child creation happens after that function returns. Using a sleep wont
do the trick since it is all the same thread. Instead use add_timer to
call the function after is has passed. Grep the kitty source code for
examples of add_timer.
