### ISSUE TITLE
Issue with Burmese fonts in kitty terminal

### ISSUE THREAD

**Issue by min-wai** [kovidgoyal/kitty#3085]
**Describe the bug**
Can't see Burmese characters even though the right fallback font(Noto Sans Myanmar) was used. I am using vim in kitty terminal and Burmese fonts just look like a bunch of spaces put together.

**Screenshots**
This is what it looks like when I pasted Burmese characters.

![Screenshot from 2020-11-10 16-31-27](https://user-images.githubusercontent.com/32773659/98660419-addbb380-2373-11eb-8289-f426809ee395.png)

This is a screenshot of it on gnome-terminal. It doesn't look perfect but it is not spaces.

![Screenshot from 2020-11-10 16-51-32](https://user-images.githubusercontent.com/32773659/98661775-4aeb1c00-2375-11eb-95b2-b2edb72b33b8.png)

```
Output of kitty --debug-font-fallback

U+104b Face(family=Noto Sans Myanmar, style=Regular, ps_name=NotoSansMyanmar-Regular, path=/usr/share/fonts/truetype/noto/NotoSansMyanmar-Regular.ttf, index=0, is_scalable=True, has_color=False, ascender=1324, descender=-860, height=2184, underline_position=-125, underline_thickness=50, strikethrough_position=322, strikethrough_thickness=50)

```

**Comment by kovidgoyal** [comment]
kitty achieves its performance by rendering characters in a grid. This
involves assuming that every character can be rendered independently of
every other (with some minor caveats for ligatures). This form of
rendering is never going to work with complex scripts. If you need to
read scripts that cannot be represented in a grid, kitty is not suitable.

**Comment by ZayRTun** [comment]
@min-wai Brother did you find a solution for Myanmar font

**Comment by saturngod** [comment]
@ZayRTun  , you can try https://github.com/saturngod/myanso
