### ISSUE TITLE
URLs are truncated if the last characer is in a new line

### ISSUE THREAD

**Issue by agschaid** [kovidgoyal/kitty#3088]
**Describe the bug**
when an URL is broken into another line so that only the last character is in the new line that character is ommited when klicking the URL

**To Reproduce**
1. in kitty run `echo "https://github.com/kovidgoyal/kitty/issues"`
2. shrink the terminal window so "https://github.com/kovidgoyal/kitty/issue" is in one line and "s" is in the next one
3. klick the URL
4. only the first line gets underlined and "https://github.com/kovidgoyal/kitty/issue" is opened
 
(Note: as soon as there are two or more characters in the next line the behavior is as expected)

**Expected behavior**
Both lines should be underlined and "https://github.com/kovidgoyal/kitty/issues" should be opened.

**Environment details**
NixOS 20.03

```
kitty 0.19.1 created by Kovid Goyal
Linux langeoog 5.4.72 #1-NixOS SMP Sat Oct 17 08:11:24 UTC 2020 x86_64
<<< Welcome to NixOS 20.03.3185.6b5f85a62c4 (\m) - \l >>>

Run `nixos-help` for the NixOS manual.
Loaded config files: /home/agl/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control y
cursor_shape         2
enable_audio_bell    False
font_family          Victor Mono
font_size            12.0
```

**Additional context**
Issue is reproducable with `kitty --config NONE'.

**Comment by agschaid** [comment]
Hi.

Why did you close the issue? 
The effected kitty version is pretty resent and I did not find any duplicate issue.

**Comment by kovidgoyal** [comment]
Read the commit that closed the issue.

**Comment by agschaid** [comment]
jesus . . . sorry. Just glanced over it and missed that it was clossed by a commit (I am more used to issues being closed by MRs)

in that case: thank you for the extremely quick fix ;)
