### ISSUE TITLE
Konsole like highlighting new lines

### ISSUE THREAD

**Issue by PouriDev** [kovidgoyal/kitty#3089]
How can I have Konsole like highlighting new line. I mean something like this:

![highlightedlines](https://user-images.githubusercontent.com/61497342/98829724-c66ccc00-244e-11eb-99ff-b9fd1c140fb4.gif)
And when you type some commands or when you hit enter the are highlightings
Is there a way that I can do it?

**Comment by SolitudeSF** [comment]
just add them to your `PS1`

**Comment by PouriDev** [comment]
How?

**Comment by kovidgoyal** [comment]
This is a shell feature not a terminal one

**Comment by PouriDev** [comment]
But , I've that in Konsole, there isn't such thing in kitty

**Comment by PouriDev** [comment]
> This is a shell feature not a terminal one

Isn't it?

**Comment by Luflosi** [comment]
I think he means the blue bar on the very left. This doesn't look like a shell feature but a feature of Konsole instead. In this case I don't think @kovidgoyal will personally desire this feature and won't implement it himself. But somebody else is willing to do the work and make a PR, he probably won't object.

**Comment by PouriDev** [comment]
Yes, thank you for completing me

**Comment by kovidgoyal** [comment]
I have no clue, I dont have any such feature in konsole on my system. Wht is that blue line supposed to represent anyway?
