### ISSUE TITLE
Support for Ubuntu?

### ISSUE THREAD

**Issue by jasminabasurita** [kovidgoyal/kitty#309]
I've installed all the packages as specified,
However when running make I get the following error:
`kitty/freetype.c:13:19: fatal error: hb-ft.h: No such file or directory`

**Comment by kovidgoyal** [comment]
That indicates you are missing the development files for harfbuzz. (libharfbuzz-dev i think it is on ubunutu). See the .travis.yml file for the list of packages to install.
