### ISSUE TITLE
Directory and Document OSC escape sequences

### ISSUE THREAD

**Issue by lloeki** [kovidgoyal/kitty#3091]
**Describe the solution you'd like**

There's this macOS feature that adds semantic title bars. Terminal.app supports it through documented OSC escape sequences. It's really cool because an icon and a path (interpreted as such, and not just as a generic "title" string) is displayed by the OS, which is right-clickable to pop up the whole path, and clicking on any folder opens it in Finder right away.

As for the generic title string, there's also a distinction between tab title and window title.

In Kitty, implementing support for these escape sequences could enable additional placeholders for `tab_title_template`, such as `{wd}` and `{document}` in addition to the generic `{title}`. This would also make it possibly queryable as a property from kitty remote thus enabling clever scripting, and possibly, who, knows, help in someday implementing restoring windows cd'd into their initial directory.

**Describe alternatives you've considered**

- Parsing the title string back, but it's error-prone, brittle, and kind of ludicrous
- Use Terminal instead of Kitty ;)

**Additional context**

The inline doc for the sequences in Apple's Terminal:

<img width="416" alt="Screenshot 2020-11-12 at 11 28 17" src="https://user-images.githubusercontent.com/75445/98931117-e4cdd880-24dd-11eb-8bcf-d41df1d78fc8.png">
<img width="422" alt="Screenshot 2020-11-12 at 11 27 37" src="https://user-images.githubusercontent.com/75445/98931128-ea2b2300-24dd-11eb-84d3-d78ea18aeea9.png">

The UI leveraging this metadata in action (notice the change in icons):

<img width="446" alt="Screenshot 2020-11-12 at 12 06 16" src="https://user-images.githubusercontent.com/75445/98932354-873a8b80-24df-11eb-9519-c087bfde6304.png">
<img width="570" alt="Screenshot 2020-11-12 at 11 29 11" src="https://user-images.githubusercontent.com/75445/98931301-1e9edf00-24de-11eb-84fa-12d7b3cf0634.png">
<img width="569" alt="Screenshot 2020-11-12 at 11 29 17" src="https://user-images.githubusercontent.com/75445/98931305-1fd00c00-24de-11eb-80c4-9b17b65b2667.png">
<img width="570" alt="Screenshot 2020-11-12 at 11 29 39" src="https://user-images.githubusercontent.com/75445/98931308-2199cf80-24de-11eb-8175-4de3bb65a76a.png">
<img width="570" alt="Screenshot 2020-11-12 at 11 29 45" src="https://user-images.githubusercontent.com/75445/98931310-22326600-24de-11eb-8f43-cf8558526841.png">

Shell code that get called on working directory changes to set the "working directory" metadata, as well as the "window title" string (both get displayed independently in my current Terminal configuration, see example above):

```bash
set_term_title() {
    [[ -o interactive ]] || return
    # Bubble information up to the terminal
    case $TERM_PROGRAM in
        Apple_Terminal)
            local SEARCH=' '
            local REPLACE='%20'
            local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
            printf '\e]7;%s\a' "$PWD_URL"
            ;;
        *)
            # NOOP
            ;;
    esac
    case $TERM in
        screen*)
            #print -Pn "\ek%n@%m: %~\e\\" #breaks tmux
            print -Pn "\e]2;%n@%m: %~\a"
            ;;
        xterm*|*rxvt*)
            print -Pn "\e]2;%n@%m: %~\a"
            ;;
        *)
            # NOOP
            ;;
    esac
}
```

Vim code that sets the "document" metadata:

```vim
" Terminal title
set title
set t_ts=]6;  " literal 0x1B char a.k.a ^[
set t_fs=     " literal 0x07 char a.k.a ^G
if !exists("autocmd_terminal_title")
  let autocmd_terminal_title = 1
  autocmd BufEnter,BufRead * let &titlestring = "file://" . hostname() . expand("%:p")
endif
```

**Comment by kovidgoyal** [comment]
Not a big fan of OS specific things, and if I ever want to open a finder
window in the current working directory of the active window, I'd just
create a mapping for it in kitty.conf rather than clicking with the
mouse using https://sw.kovidgoyal.net/kitty/launch.html 

That said I wont refuse PR for it. Patches are most welcome. If you need
guidance with kitty's codebase, feel free to post on this thread and I
will help. You can get started with building kitty as described here:
https://sw.kovidgoyal.net/kitty/build.html 

Closing this bug report, if anyone wishes to implemet it, feel free to
comment further.

**Comment by kovidgoyal** [comment]
Oh and FYI kitty has comprehensive controls for setting window and tab titles and much much more, https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by kidonng** [comment]
FYI, this is called ["Proxy icon"](https://osxdaily.com/2014/08/20/open-files-new-app-proxy-icon-mac-os-x/) in macOS. Aside from Apple Terminal, iTerm2 also supports it ([10th image](https://iterm2.com/features.html#configurability).
