### ISSUE TITLE
Manual and automatic non-content-based line marks

### ISSUE THREAD

**Issue by lloeki** [kovidgoyal/kitty#3092]
**Describe the solution you'd like**

AIUI [marks](https://sw.kovidgoyal.net/kitty/marks.html) are content-based. They allow the user to visually highlight matched content and quickly jump from mark to mark.

Terminal.app has a ludicrously good line mark feature that I use all the time and sorely miss when using Kitty, comprised of two closely-related parts:

- manual line marks, placed with CMD+Return
- automatic line marks, placed automatically with Return, but only when an interactive prompt is reading on STDIN

Both are visually annotated with surrounding pair of thin `[` `]` placed outside of the terminal content area, in the margin/padding.

Jumping between any of those marks is achieved with CMD+UP/DOWN. It is crazy efficient to just launch a command which produces long output, then jump back to the command with CMD+UP. Similarly, with web development servers, one can start the server/tail a log, manuall mark a position, perform a request, mark again, and jump back and forth between both points.

Since there's no specific content to match, it seems this can't be implemented with Kitty's mark system, at least not as is.

But there's the [scroll to mark feature](https://sw.kovidgoyal.net/kitty/marks.html#scrolling-to-marks) already so I suppose it's "just" a matter of:

- having a way to add an entirely arbitrary mark at the line where the cursor is with a keyboard shortcut
- having a way to add a mark at the line where the cursor was when Return was pressed and an interactive program was listening on STDIN (how can that be achieved I don't quite know).

The in-margin visual aids are a nice bonus feature because they:

- don't alter the content visually
- allow for 1D eye scanning instead of 2D

(It makes me think it could be a cool terminal extension to be able to control such per-line out-of-content left+right margin glyphs/pixels, like vim's sign gutter)

**Describe alternatives you've considered**

This may be implemented using [arbitrary marker functions](https://sw.kovidgoyal.net/kitty/marks.html#arbitrary-marker-functions) if `def marker(text)` is augmented with a second (or more) argument, where it would be able to return mark info based on another criteria than text, such as line position in the scrollback:

```python
def marker(text, scrollback_pos=None):
    if scrollback_pos == scrollback_size:
      yield 0, term.width-1, 3
```

But it would be kind of inefficient to go through the whole scrollback just to mark -one- line whose position is well known.

**Additional context**

Example session with both automatic and manual line marks (note that the extra `[` and `]` are not content but in-margin):

<img width="572" alt="Screenshot 2020-11-12 at 12 43 33" src="https://user-images.githubusercontent.com/75445/98936123-d6cf8600-24e4-11eb-9b40-e87728cf9cfc.png">

Jumping to a line mark briefly highlights it (which is super useful with walls of text):

<img width="570" alt="Screenshot 2020-11-12 at 12 43 44" src="https://user-images.githubusercontent.com/75445/98936246-fc5c8f80-24e4-11eb-95fa-41dbf8af56e1.png">

**Comment by kovidgoyal** [comment]
I'm afraid this is of no interest to me. If you want to jump to prompt
lines the existing marks feature will do just that with a search for
whatever pattern your prompt uses. As for manual marks, if I need to do
that kind of exploration I prefer to use the open scrollback in
pager/editor feature.
