### ISSUE TITLE
Open new tab/window in same directory as current tab

### ISSUE THREAD

**Issue by lloeki** [kovidgoyal/kitty#3093]
**Is your feature request related to a problem? Please describe.**

Opening a new tab lands me in `~`, so every time I have to `cd` my way into the same place I am in the tab I just opened.

**Describe the solution you'd like**

Have an option to open new tabs in the same directory as the current one. A similar (but distinct) option can be applied to windows.

Kitty would need to know the current working directory, for which #3091 is very useful as it's designed to communicate it.

**Additional context**

Here's a similar option in Apple's Terminal. I seem to recall some other terminals like Gnome's may have the same kind of options.

<img width="394" alt="Screenshot 2020-11-12 at 13 14 31" src="https://user-images.githubusercontent.com/75445/98939105-329c0e00-24e9-11eb-87c9-7b0a8deccad1.png">

**Comment by AppMathIsRealMath** [comment]
Doesn't the kitty.conf option new_tab_with_cwd do this already?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/launch.html
