### ISSUE TITLE
OSC 52 clipboard escape code protocol appears to be dropping first base64 character

### ISSUE THREAD

**Issue by slzatz** [kovidgoyal/kitty#3095]
On two separate machines, running arch linux, I have encountered the following problem regarding the osc 52 clipboard escape code sequence: `"\x1b]52;c;?\a"`

The problem is that when it returns the base64 encoded text from the clipboard it drops the first base64 character.  This happens every time I use the sequence.

So for example, if "hello" is placed in the clipboard, it returns "GVsbG8=" instead of "aGVsbG8="

What makes this particularly confusing to me is that `kitty +kitten clipboard --get-clipboard` returns the correct result and it appears to be using the same escape sequence (and of course decoding the base64) to produce the result.

**Comment by kovidgoyal** [comment]
The get clipboard kitten uses OSC 52 to communicate, so if it is
working, kitty must be sending the correct data. Most likely whatever
code you are using to parse/display OSC escape codes is broken.

**Comment by slzatz** [comment]
No problem with your closing this and I am confused as well but this problem can be demonstrated by just typing `printf "\x1b]52;c;?\x07"` on the command line and decoding what comes back.

**Comment by kovidgoyal** [comment]
What comes back is processed by the shell, you cant trust that. If you want
to test it use a proper programming language. Write to /dev/tty then
read from /dev/tty. you will get the expected bytes.

**Comment by slzatz** [comment]
Thanks for the advice.  All is working now -- and thanks for your great work on kitty.
