### ISSUE TITLE
Running tmux inside kitty messes up colors

### ISSUE THREAD

**Issue by gnufied** [kovidgoyal/kitty#3098]
**Describe the bug**

When I run tmux inside kitty and open `vim` the colors are messed up. As shown in the screenshot. 

vim running inside kitty:

![Screenshot from 2020-11-13 10-15-02](https://user-images.githubusercontent.com/278/99087794-2d969780-2599-11eb-9e22-060617d4b72a.png)

In above screenshot the white area is visual selection within vim but other color highlights are messed up too.

For comparison without tmux:
![Screenshot from 2020-11-13 10-17-54](https://user-images.githubusercontent.com/278/99088072-8403d600-2599-11eb-8532-27c5fba69a18.png)

**To Reproduce**
1. Run kitty installed from fedora33 repo (`0.19.1-1.fc33`)
2. Run tmux inside kitty (`3.1`)
3. Open VIM with syntax enabled
4. See error above

**Expected behavior**
The colors should be accurate.

**Environment details**
OS: Name and version of operating system(s)

```
kitty 0.19.1 created by Kovid Goyal
Linux weathertop 5.8.18-300.fc33.x86_64 #1 SMP Mon Nov 2 19:09:05 UTC 2020 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: /home/hekumar/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_border_color  None
background           Color(red=34, green=34, blue=33)
color0               Color(red=33, green=33, blue=33)
color1               Color(red=183, green=20, blue=30)
color10              Color(red=122, green=186, blue=57)
color11              Color(red=254, green=233, blue=46)
color12              Color(red=83, green=164, blue=243)
color13              Color(red=169, green=77, blue=187)
color14              Color(red=38, green=186, blue=209)
color15              Color(red=216, green=216, blue=216)
color2               Color(red=69, green=123, blue=35)
color3               Color(red=245, green=151, blue=29)
color4               Color(red=19, green=78, blue=178)
color5               Color(red=85, green=0, blue=135)
color6               Color(red=14, green=112, blue=124)
color7               Color(red=238, green=238, blue=238)
color8               Color(red=66, green=66, blue=66)
color9               Color(red=232, green=58, blue=63)
cursor               Color(red=22, green=174, blue=201)
font_family          Fira Code
foreground           Color(red=228, green=228, blue=228)
inactive_text_alpha  0.6
selection_background Color(red=222, green=222, blue=222)
selection_foreground Color(red=34, green=34, blue=33)
tab_bar_edge         1
Added shortcuts:
         alt+1 KeyAction(func='goto_tab', args=(1,))
         alt+2 KeyAction(func='goto_tab', args=(2,))
         alt+3 KeyAction(func='goto_tab', args=(3,))
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by gnufied** [comment]
Now I know there are several similar issues opened in past and it has kind of resolved via changing TERM or tmux configuration. But I seem to be using it correctly.

output of `TERM` environment variable within tmux or without is - 

```
╰─~> echo $TERM
xterm-kitty
─~> echo $TERMINFO
/usr/lib64/kitty/terminfo
```

I have tried using following option:

```
set-option -as terminal-features ',xterm-kitty:RGB'
```

and changing tmux version to 3.2-rc3 but the problem remains.

**Comment by kovidgoyal** [comment]
So report it to tmux. Or better yet dont use tmux: https://github.com/kovidgoyal/kitty/issues/391#issuecomment-638320745

If I had to guess, you are using a true color theme in vim and you need
to configure tmux to enable true colors.
