### ISSUE TITLE
A way to deep link local files from interactive build tool

### ISSUE THREAD

**Issue by hedefalk** [kovidgoyal/kitty#3099]
I'm looking for a way to work with local file paths in output from build tools and in particular either to click into a file with line number or using keys like the hints kitty. I'm coming from iterm2 with the ability to cmd-click a local file path which I have configed to open it up in vscode. So if I have a build tool that reports a compile error on a file I would have simply clicked it.

I've tried using the hints kitty but the way it seems to work is by inserting the configured editor command into the current window. That doesn't work with an interactive build tool, for instance sbt that I'm using right now. Triggering local paths with ctrl-shift-p>n like:

![image](https://user-images.githubusercontent.com/116520/99105200-6313a300-25e2-11eb-98ab-0182c2aa3c19.png)

and then hitting 1 will get an insert of `vim` into my current sbt session which of course doesn't work, sbt doesn't understand vim :)

![image](https://user-images.githubusercontent.com/116520/99105377-b685f100-25e2-11eb-9e6f-5856a563c0cf.png)

I've also tried just adding "/" to url_prefixes like:

```
url_prefixes http https file ftp /
```

but that doesn't seem to do anything. I've read all I can on previous issues like #977, but I really can't understand a way to work around this need I have.

**Comment by kovidgoyal** [comment]
You want https://sw.kovidgoyal.net/kitty/kittens/hints.html#cmdoption-kitty-kitten-hints-linenum-action

to open vim in new new window/tab/os window

**Comment by hedefalk** [comment]
Just for reference:

```
#: Select something that looks like filename:linenum and open it in vscode
map kitty_mod+p>n kitten hints --type linenum --linenum-action=background /usr/local/bin/code -g {path}:{line}
```
