### ISSUE TITLE
Background opacity

### ISSUE THREAD

**Issue by fennecdjay** [kovidgoyal/kitty#31]
I really miss this one, tried to look in the code, but there I only see *cursor_opacity*.
Any hints?
Thanks for the work.

**Comment by kovidgoyal** [comment]
There is no background opacity -- this is not supported by glfw the windowing toolkit kitty uses. https://github.com/glfw/glfw/issues/197

**Comment by fennecdjay** [comment]
I'll give a look. Thanks for the precise answer.

**Comment by raspbeguy** [comment]
I really would like this feature to exist. I'll follow the glfw ticket.

**Comment by ibrokemypie** [comment]
If you use compton you can add `opacity-rule = ["85:class_g = 'kitty'"];` to compton.conf to use compositor transparency as a workaround

**Comment by ABitMoreDepth** [comment]
Upstream appears to have merged opacity, does that mean we can see opacity brought into Kitty?
https://github.com/glfw/glfw/issues/197

**Comment by kovidgoyal** [comment]
Sure once a version of glfw with transparency is released adding transparency to kitty should be a trivial change -- about ten lines of code.

**Comment by CatLover91** [comment]
For OSX users with chunkwm, modification in their .chunkwmrc utilizing commands similar to those referenced in koekeishiya/chunkwm#139 could accomplish this.

**Comment by kovidgoyal** [comment]
This is implemented in the win branch which will eventually become version 0.6.0
