### ISSUE TITLE
Is there an API for a per-window statusbar?

### ISSUE THREAD

**Issue by cpdean** [kovidgoyal/kitty#3101]
I'd like for there to be a way to render a string of text at the bottom of a given terminal window to provide per-window stats that may normally go in [a prompt](https://starship.rs/config/#git-branch), kind of like this extension to provide contextual information in [the tmux statusbar](https://github.com/arl/gitmux).

Is there a way to do that, either through `kitty @ ...` commands or through the API exposed to kitten plugins?

Thanks!

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/remote-control.html 

But for an actual docked status bar it would need #2391

**Comment by cpdean** [comment]
So the idea would be to implement a status bar as a 1 character high window and populate it with content via send-text?

**Comment by kovidgoyal** [comment]
yes.

**Comment by cpdean** [comment]
thanks! i will try working on something in this direction.
