### ISSUE TITLE
kitty color scheme washed out on macOS Catalina

### ISSUE THREAD

**Issue by jameshome** [kovidgoyal/kitty#3102]
On macOS Catalina, the kitty window is color shifted as if it has a layer of white at approximately 5% opacity positioned above it. 

This seems to be happening in kitty, because the OS window title bar **does** get the correct theme color when `macos_titlebar_color` is set to 1. 

In the screenshot below, `background` is set to #3c3836 and `macos_titlebar_color` is set to 1. The window is correctly setting the titlebar to #3c3836, but the rest of the kitty window is #44403E for some reason. 

![kitty-colorshift](https://user-images.githubusercontent.com/56417/99153631-2772ea80-266f-11eb-8d2e-dd40091af8da.png)

Here I'm only showing background for clarity, but this unexplained color shift happens to **all** of the theme colors, causing the interface to appear washed out.

**To Reproduce**
1. On macOS, set a `background` and `macos_titlebar_color 1`
2. Launch kitty and see that the title bar color is correct and the window background is not 

**Expected behavior**
kitty should display colors as specified in color scheme 

**Environment details**
macOS Catalina 10.15.7

```
Output of kitty --debug-config
kitty 0.19.2 created by Kovid Goyal
Darwin athene.lan 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H2
Loaded config files: /Users/jh/.config/kitty/kitty.conf

Config options different from defaults:
background           Color(red=60, green=56, blue=54)
macos_titlebar_color 1
```

**Comment by kovidgoyal** [comment]
How are you deducing the window color is incorrect and the titlebar color is correct? Seems far more likely to me that cocoa tints the titlebar color.

**Comment by kovidgoyal** [comment]
Oh and FYI the correct value for macos_titlebar_color is "background" not 1. And with it set to "background" i see no difference between background and titlebar colors on my mac. They match exactly

kitty --config NONE -o background=red -o macos_titlebar_color=background

**Comment by jameshome** [comment]
Screen capture and analysis in an image editor. I'm quite confident that the titlebar color is what is being set in the config file and the rest of the window is incorrect — I've tested it with a variety of colors and analysis methods.

**Comment by jameshome** [comment]
I do indeed have it set to "background" in my config file — I mistakenly cut and pasted from the --debug-config output in my bug description, sorry for the confusion.

The effect is less pronounced on colors at the extremes of the RGB scale. Can you please try the color I'm using and confirm that they match exactly? 

kitty --config NONE -o background=#3c3836 -o macos_titlebar_color=background

I think you might be surprised.

**Comment by kovidgoyal** [comment]
Colors are exactly the same with that as well. 
![colors](https://user-images.githubusercontent.com/1308621/99161367-9c99fa80-2717-11eb-8560-3df148427406.png)

**Comment by jameshome** [comment]
Interesting! Well, on the one hand I'm happy for you that it isn't a widespread problem, but on the other, I have no explanation for why it's happening to me. Any ideas at all? 

I thought it might be an issue with fish shell, but I specified `shell bin/zsh` and got the same results. I changed the various macOS appearance options to mirror yours — no help. I'm not running tmux or anything else particularly unusual.

Thanks for getting back to me anyway.

**Comment by kovidgoyal** [comment]
Run the command line posted above and add cat to the end of it. That
will eliminate any issues caused by shells or other programs running
inside kitty. If you still experience it, then there is something screwy
with your graphics/opengl drivers. There is no code in kitty that
modifies colors by 5% arbitrarily.

**Comment by jameshome** [comment]
Same result. I'll let this go for now, but if I learn more, I'll post about it here.
