### ISSUE TITLE
'$' leading words inherit wrong color?

### ISSUE THREAD

**Issue by browser-bug** [kovidgoyal/kitty#3103]
I've already asked this [here](https://github.com/zsh-users/zsh-syntax-highlighting/issues/780) and given the answer I'll ask here aswell. 
>Anytime I start typing something with a leading $ (which happens quite a lot if I need to cd inside a path referenced by an env variable), the syntax highlighting sets the word with the `color0` (that in my case happen to be the same of the background). I've tried it using `urxvt` and in that case it seems to be using `color8 `instead.

[Here's the answer](https://github.com/zsh-users/zsh-syntax-highlighting/issues/780#issuecomment-727202732). Is this something that can be affected by some internal kitty settings?

**Comment by kovidgoyal** [comment]
This will be because your color theme/shell is incorrectly using the bold
character attribute to mean "intense" color instead of bold font face.
Get it to use the actual intense colors and you will be fine.

**Comment by danielshahaf** [comment]
@kovidgoyal So, to be clear, the fact that bold black is unreadable on @browser-bug's setup is expected? That seems to be a fair question even if zsh-syntax-highlighting should be using intense black rather than bold black.

**Comment by kovidgoyal** [comment]
Of course it is expected. Is there any context other than a broken terminal where you would expect the bold variant of a font to have a different color than the on-bold variant? dup of #342

**Comment by danielshahaf** [comment]
Thanks for the reference.  There actually is plenty of precedent for bold implying intense (e.g., [xterm without the `+pc` option](https://sources.debian.org/src/xterm/362-1/XTerm-col.ad/#L37)), but I wasn't comparing the colours of the bold and non-bold variants.  Rather, I was comparing the standard 16 colours on the one hand to the default background colour on the other hand.  I find it useful to set default background colour to be something that's not one of the standard 16 colours, since that way I can't run into #342 in any terminal program.  If such functionality exists in kitty, it would constitute another possible workaround to @browser-bug's original problem.

**Comment by kovidgoyal** [comment]
You can set all 256 colors and background foreground cursor highlight,
etc etc colors in kitty.

**Comment by browser-bug** [comment]
>If such functionality exists in kitty, it would constitute another possible workaround to @browser-bug's original problem.

I've already tried tweaking some of kitty's color customization options but I find that [this](https://github.com/zsh-users/zsh-syntax-highlighting/issues/780#issuecomment-727546480) is still the only viable option in my case (in order to keep my original color scheme).

Just for reference, here's the color scheme:
```
# hard contrast: background #1d2021
background  #262626
# soft contrast: background #32302f
foreground  #ebdbb2

cursor #fbf1c7
url_color #83a598

# Black + DarkGrey
color0  #262626
color8  #928374
# DarkRed + Red
color1  #cc241d
color9  #fb4934
# DarkGreen + Green
color2  #98971a
color10 #b8bb26
# DarkYellow + Yellow
color3  #d79921
color11 #fabd2f
# DarkBlue + Blue
color4  #458588
color12 #83a598
# DarkMagenta + Magenta
color5  #b16286
color13 #d3869b
# DarkCyan + Cyan
color6  #689d6a
color14 #8ec07c
# LightGrey + White
color7  #a89984
color15 #ebdbb2
```

**Comment by trygveaa** [comment]
> I find it useful to set default background colour to be something that's not one of the standard 16 colours

> in order to keep my original color scheme

Well, if you want your current color scheme it is impossible for kitty to use a different color for the background and color0. You're explicitly setting them to the same color in your color scheme.

**Comment by browser-bug** [comment]
> Well, if you want your current color scheme it is impossible for kitty to use a different color for the background and color0. You're explicitly setting them to the same color in your color scheme.

That's from the [original](https://camo.githubusercontent.com/410b3ab80570bcd5b470a08d84f93caa5b4962ccd994ebceeb3d1f78364c2120/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67) color palette. And `color0` isn't supposed to be hooked to "black" anyway? Setting it light could messed up other programs color output or am I missing something?

**Comment by trygveaa** [comment]
Well, yes, normally they are the same color. That's why programs shouldn't use color0 without a different background color.

**Comment by danielshahaf** [comment]
@browser-bug There's no reason to set it color0 to light.  You can just change either background or color0, and naturally, there's every reason to set them to something close to their original value; even that will (necessarily) provide better contrast with the other one.  That's what I do, as I said [on the other issue (in the parenthetical)](https://github.com/zsh-users/zsh-syntax-highlighting/issues/780#issuecomment-727202732).
