### ISSUE TITLE
Please enable support for font weight in variable fonts

### ISSUE THREAD

**Issue by subnut** [kovidgoyal/kitty#3104]
Unlike regular fonts, variable fonts (e.g. Fira Code, Cascadia Code) do not have different variants like _Light_, _Extra Light_, _Medium_, _Extra Bold_, etc. Those different variants are supplied by a property called `font weight`. (See GIF below for demonstration)

![gifcast_201115091500](https://user-images.githubusercontent.com/56714626/99162864-94968680-2728-11eb-986f-7b9319e07f53.gif)

I see most modern fonts are shifting towards variable, because web developers always prefer variable fonts. 

**Describe the solution you'd like**
A configuration called `font_weight` that defines the font weight of the normal font, and another called `font_weight_bold` for the bold font.

**Comment by kovidgoyal** [comment]
All these fonts have variants, and you can choose those variants by specifying the full name of the font face in font_family. Use kitty +list-fonts, pick your variant name from it, and use it.

**Comment by inferiorhumanorgans** [comment]
> All these fonts have variants, and you can choose those variants by specifying the full name of the font face in font_family. Use kitty +list-fonts, pick your variant name from it, and use it.

While specifying the base family name (e.g. IBM Plex Mono) works, specifying the variant in the font_family key does not:

```
$ /Volumes/kitty-0.28.1/kitty.app/Contents/MacOS/kitty +list-fonts | grep 'Plex Mono Light'
    IBM Plex Mono Light
    IBM Plex Mono Light Italic
$ /Volumes/kitty-0.28.1/kitty.app/Contents/MacOS/kitty
[182 18:20:18.526838] The font IBM Plex Mono Light was not found, falling back to Menlo
[182 18:20:18.526918] The font IBM Plex Mono Light was not found, falling back to Menlo
[182 18:20:18.526963] The font IBM Plex Mono Light was not found, falling back to Menlo
[182 18:20:18.526990] The font IBM Plex Mono Light was not found, falling back to Menlo
```

**Comment by kovidgoyal** [comment]
On Sat, Jul 01, 2023 at 06:21:51PM -0700, inferiorhumanorgans wrote:
> > All these fonts have variants, and you can choose those variants by specifying the full name of the font face in font_family. Use kitty +list-fonts, pick your variant name from it, and use it.
> 
> While specifying the base family name (e.g. IBM Plex Mono) works, specifying the variant in the font_family key does not:
> 
> ```
> $ /Volumes/kitty-0.28.1/kitty.app/Contents/MacOS/kitty +list-fonts | grep 'Plex Mono Light'
>     IBM Plex Mono Light
>     IBM Plex Mono Light Italic
> $ /Volumes/kitty-0.28.1/kitty.app/Contents/MacOS/kitty
> [182 18:20:18.526838] The font IBM Plex Mono Light was not found, falling back to Menlo
> [182 18:20:18.526918] The font IBM Plex Mono Light was not found, falling back to Menlo
> [182 18:20:18.526963] The font IBM Plex Mono Light was not found, falling back to Menlo
> [182 18:20:18.526990] The font IBM Plex Mono Light was not found, falling back to Menlo
> ```

Works fine for me:
```
[183 07:43:33.821406] The font IBM Plex Mono Light was not found, falling back to Menlo
[183 07:43:33.821481] The font IBM Plex Mono Light was not found, falling back to Menlo
[183 07:43:33.821500] The font IBM Plex Mono Light was not found, falling back to Menlo
[183 07:43:33.821525] Preloaded font faces:
[183 07:43:33.821537] normal face: /Users/kovid/Library/Fonts/IBMPlexMono-Light.ttf
[183 07:43:33.821547] bold face: /System/Library/Fonts/Menlo.ttc
[183 07:43:33.821557] italic face: /System/Library/Fonts/Menlo.ttc
[183 07:43:33.821567] bi face: /System/Library/Fonts/Menlo.ttc
```

Look at the line which tell you what the normal face is. 

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by inferiorhumanorgans** [comment]
Yes, the base font name is "IBM Plex Mono" and it loads just fine.  "IBM Plex Mono Light" (and all of the other variants and variants for other fonts that load just fine e.g. Fira Code.

**Comment by kovidgoyal** [comment]
Let me post the relevant line for you:
```
[183 07:43:33.821537] normal face: /Users/kovid/Library/Fonts/IBMPlexMono-Light.ttf
```

Emphasis on **normal face** and **IBMPlexMono-Light.ttf**

**Comment by inferiorhumanorgans** [comment]
Ah, sorry I've already uninstalled kitty and gone back to iTerm.  Cheers.
