### ISSUE TITLE
SSH: infocmp: couldn't open terminfo file (null).

### ISSUE THREAD

**Issue by joaogui1** [kovidgoyal/kitty#3107]
**Describe the bug**
Tried to connect using `kitty +kitten ssh $server_address` per instructions, got the following error:

```
infocmp: couldn't open terminfo file (null).
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 119, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 110, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 68, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 63, in run_kitten
    run_kitten(kitten)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 103, in run_kitten
    runpy.run_module('kittens.{}.main'.format(kitten), run_name=run_name)
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/kittens/ssh/main.py", line 130, in <module>
    main(sys.argv)
  File "/usr/bin/../lib/kitty/kittens/ssh/main.py", line 117, in main
    terminfo = subprocess.check_output(['infocmp']).decode('utf-8')
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['infocmp']' returned non-zero exit status 1.
```

**Environment details**
OS: Ubuntu 20.04
Output of kitty --debug-config
```
kitty 0.15.0 created by Kovid Goyal
Linux Lab 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/joaogui/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=39, green=34, blue=34)
cursor                Color(red=39, green=170, blue=156)
font_family           Fira Code
update_check_interval 0.0
```
Where is terminfo supposed to be located?

**Comment by kovidgoyal** [comment]
That indicates running infocmp on your local machine is failing. Make
ure TERM is correctly set to xterm-kitty.

**Comment by joaogui1** [comment]
![image](https://user-images.githubusercontent.com/13261989/99267297-861c9d80-2802-11eb-8e3e-d4b2956db3a7.png)
@kovidgoyal

**Comment by kovidgoyal** [comment]
well then infocmp is failing for some other reason, I have no clue what
that might be, you'd have to ask its developers. You can always manually
copy over terminfo as described in the kitty FAQ.

**Comment by joaogui1** [comment]
I don't think I have a kitty terminfo, or at least it's not where it's supposed to be, do you know how can I get one?
![image](https://user-images.githubusercontent.com/13261989/99270861-7ce10000-2805-11eb-950a-3f862216efe9.png)

**Comment by kovidgoyal** [comment]
check the value of the terminfo env var it should be pointing to a
directory with the kitty terminfo

**Comment by benpm** [comment]
I was also having this issue, but, bizarrely, I managed to fix it by removing the Anaconda initialization from my zshrc. Here is the offending section of script:
```bash
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ben/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ben/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ben/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ben/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
Before removing:
```
(base) ➜  ~ infocmp xterm-kitty
infocmp: couldn't open terminfo file (null).
```
After:
```
➜  ~ infocmp xterm-kitty
#	Reconstructed via infocmp from file: /usr/share/terminfo/x/xterm-kitty
xterm-kitty|KovIdTTY,
	am, ccc, hs, km, mc5i, mir, msgr, npc, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
...
```
No idea what is happening here, but hey it works. Now I have a good excuse to purge Anaconda from my machine.

**Comment by kovidgoyal** [comment]
Probably conda.sh either changes or removes the TERMINFO env var

**Comment by vpmammana** [comment]
I had the same problem in a totally different context.

By typing infocmp I got the message that it could not open terminfo. But it also informed the path it was trying to get. What I did was simply creating that path with the right term there (xterm-256color). Using find * I found it in another directory and copied to the new directory.

**Comment by keremyldrr** [comment]
The locations infocmp checks when looking for terminfo changes when a conda environment is activated. You can check it by running `infocmp -D` both in and out of the conda environment.
I was able to fix this issue by copying kitty terminfo files to anaconda terminfo directory.
```bash 
 cp /usr/share/terminfo/x/xterm-kitty anaconda3/share/terminfo/x/ 
```

**Comment by tby321** [comment]
For conda users, after activating the conda environment, execute `infocmp -D` to check the terminfo path, and then copy the xterm-ghostty terminfo to the conda terminfo path.
