### ISSUE TITLE
ctrl+up and ctrl+right not working as expected

### ISSUE THREAD

**Issue by matthaeusheer** [kovidgoyal/kitty#3108]
**Describe the bug**
I added
```
map ctrl+left          neighboring_window left
map shift+left         move_window right
map ctrl+down          neighboring_window down
map shift+down         move_window up
```
to my kitty config as described [here](https://sw.kovidgoyal.net/kitty/).
The ctrl+down and ctrl+left commands work as expected. However, when using ctrl+up or ctrl+right to switch to windos on top or to the right side, nothing happens.

**To Reproduce**
1. Add configuration as described above
2. See error

**Expected behavior**
When I add two new windows (2 x ctrl+shift+enter), ending up with three windows, one taking the upper half and two sharing the lower half, I would like to be able to switch from one in the lower half directly to the one in the uppper half with ctrl+up. 

**Screenshots**

**Environment details**
OS: Ubuntu 20.04

**Comment by kovidgoyal** [comment]
I cannot replicate with the current kitty release, 0.19.2 running kitty with

```
kitty --config NONE -o enabled_layouts=fat -o 'map ctrl+up neighboring_window up' -o 'map ctrl+down neighboring_window down' -o 'map ctrl+left neighboring_window left' -o 'map ctrl+right neighboring_window right'
```

ctrl+up and ctrl+right work as expected, taking you to the upper and right windows, respectively.

**Comment by matthaeusheer** [comment]
Running your command opened a Kitty terminal in which the behaviour is indeed as expected. However, not when I use a config with the content as described above.

**Comment by matthaeusheer** [comment]
I see the error, didn't read it properly. There are move_window commands in there i assumed it would be all neighboring_*. Cheers
