### ISSUE TITLE
Make hints kitten support linebreak in file names…?

### ISSUE THREAD

**Issue by hedefalk** [kovidgoyal/kitty#3109]
As suggested in #3099 I'm using the hints kitten to link compile errors into my editor of choice. However, doing Scala development, the paths are pretty long at times:

![image](https://user-images.githubusercontent.com/116520/99497065-a456da80-2975-11eb-9e24-b9fe0bb4cd14.png)

The kitten doesn't seem to work correctly for these since it separates on the linebreaks :.(

**Comment by kovidgoyal** [comment]
I'm afraid this is not something I am interested in, such long filenames
are pretty rare in my experience, why doesnt the compiler output
relative paths? In any case, you can fully customize the hint detection,
as described here: 
https://sw.kovidgoyal.net/kitty/kittens/hints.html#completely-customizing-the-matching-and-actions-of-the-kitten

**Comment by hedefalk** [comment]
Thanks for the pointer, that's good enough for me!
