### ISSUE TITLE
Background rendering issue

### ISSUE THREAD

**Issue by wjakob** [kovidgoyal/kitty#311]
I've used Kitty for a few weeks now, and it is an amazing iTerm2 replacement. Latency is so much lower, I love it :)

One minor gripe: there is a problem in behavior when rendering colored backgrounds. On my end, it appears when using VIM with a theme that has a background color. In this case, the background gets messed up when scrolling downwards (via PgDown, i.e. Fn+Down key on an MBP), and it recovers when scrolling upwards again. This does not happen in iTerm2 & xterm.

See the following video to get an idea: https://www.dropbox.com/s/4p0arfm3gx0r8q2/kitty.mp4?dl=0. I'm just alternatingly pressing PgDown & PgUp.

I'd be happy to provide any additional information to help tracking this down.

**Comment by kovidgoyal** [comment]
Add the following to your vimrc

```vim
        " vim hardcodes background color erase even if the terminfo file does
        " not contain bce (not to mention that libvte based terminals
        " incorrectly contain bce in their terminfo files). This causes
        " incorrect background rendering when using a color theme with a
        " background color.
        let &t_ut=''
```

**Comment by wjakob** [comment]
Perfect! Thank you also for adding the FAQ entry on the main page.
