### ISSUE TITLE
--single-instance doesn't seem to work for me on MacOS Catalina

### ISSUE THREAD

**Issue by hedefalk** [kovidgoyal/kitty#3110]
I'm working on many projects with lots of log-tailing and builds with watches and all that so I really need to be able to script context switching. I've been using termocil/itermocil (https://github.com/TomAnthony/itermocil) previously for this need, and I'm trying to use an alias to support starting session's like I'm used to. One way I'm trying out are aliases like:

`kitty --single-instance --session ~/.config/kitty/my_project.session`

Not sure if this is a bug or if I'm misunderstanding the docs, but I still get a new OS application:
![image](https://user-images.githubusercontent.com/116520/99502904-01ef2500-297e-11eb-9f8d-5023c4836067.png)

**Expected behavior**
I expected the new OS window to be on the same application

**Environment details**
MacOS Catalina 10.15.7 (19H15)

```
❯ kitty --debug-config
kitty 0.19.1 created by Kovid Goyal
Darwin polina 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H15
Loaded config files: /Users/viktor/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control y
editor               /usr/local/bin/code
enabled_layouts      ['splits:split_axis=horizontal']
font_family          JetBrains Mono
font_size            13.0
open_url_modifiers   8
shell                /usr/local/bin/fish --login
tab_bar_edge         1
tab_bar_style        separator
url_prefixes         ('http', 'https', 'file', 'ftp', '/')
Added shortcuts:
	control+right KeyAction(func='neighboring_window', args=['right'])
	control+left KeyAction(func='neighboring_window', args=['left'])
	super+d KeyAction(func='launch', args=['--location=vsplit'])
Changed shortcuts:
	shift+control+p > n KeyAction(func='kitten', args=['hints', '--type linenum --linenum-action=background /usr/local/bin/code -g {path}:{line}'])
	shift+control+right KeyAction(func='resize_window', args=['wider', 1])
	shift+control+left KeyAction(func='resize_window', args=['narrower', 1])
	shift+control+down KeyAction(func='resize_window', args=['shorter', 3])
	shift+control+up KeyAction(func='resize_window', args=['taller', 1])
	super+1 KeyAction(func='goto_tab', args=(1,))
	super+2 KeyAction(func='goto_tab', args=(2,))
	super+3 KeyAction(func='goto_tab', args=(3,))
	super+4 KeyAction(func='goto_tab', args=(4,))
	super+5 KeyAction(func='goto_tab', args=(5,))
	super+6 KeyAction(func='goto_tab', args=(6,))
	super+7 KeyAction(func='goto_tab', args=(7,))
	super+8 KeyAction(func='goto_tab', args=(8,))
	super+9 KeyAction(func='goto_tab', args=(9,))
	super+t KeyAction(func='new_tab_with_cwd', args=())
	super+w KeyAction(func='close_window', args=())
	shift+super+d KeyAction(func='launch', args=['--location=hsplit'])
```

I've reported this as a bug since I expected the `--single-instance` switch to _not_ start another OS app, but a OS window within the same app.

But I'm also interested if there's any other way to do what I want - to script session startups with tabs and windows within kitty itself.

**Comment by kovidgoyal** [comment]
sessions and single instance have nothing to do with each other. You can
define multiple OS Windows in a session file. --single-instance means
that when you run kitty --single-instance, instead of a new OS window
being created in a new process, a new OS Window is created in a
previously running process of kitty --single-instance

**Comment by hedefalk** [comment]
@kovidgoyal I had some trouble understanding this. But ok, my misunderstanding was that I thought that running 

```kitty --single-instance``` would make it so that the new invocation was on the same pid as the invoker.

But ok, I need `--single-instance` on the of the root kitty invocation. That seemed to do the trick!

But since I want to be able to start kitty as a typical MacOS app from /Applications/kitty.app, in my case I'm using Alfred as a launcher for everything native:

![image](https://user-images.githubusercontent.com/116520/99506997-23064480-2983-11eb-8a53-b6734943b1fa.png)

 is there a way to add this flag in settings, could not find it? I mean, I don't want to have to open another terminal emulator like iterm2 just to be able to start kitty with a flag…?

It seems however, that what I really wanted was just https://sw.kovidgoyal.net/kitty/remote-control.html. Then I can just make shell-scripts with my sessions prepending `kitty @` to the startup session file I was intending to use. That way I probably don't need the `--single-instance` flag at all…

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos.

**Comment by patricorgi** [comment]
> See https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos.

This does not work any more.

**Comment by patricorgi** [comment]
I have the `~/.config/kitty/macos-launch-services-cmdline` file with following content

```
--single-instance
```

In the past, if I run separately (e.g. in the macOS native Terminal.app) `/Applications/kitty.app/Contents/MacOS/kitty --single-instance -- bash -l -c nvim`, neovim will open in a separate kitty window of the SAME instance. Now I'm getting a new instance of kitty.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/036241fc6c8a8d213542190052e152982aea30f7
