### ISSUE TITLE
glkitty - port of the OpenGL gears demo to kitty terminal graphics protocol

### ISSUE THREAD

**Issue by michaeljclark** [kovidgoyal/kitty#3111]
## _glkitty_

I was looking for an advanced terminal graphics protocol example in C and couldn't find much, so decided to write one. _glkitty_ could be added to a directory of the project, perhaps `contrib/glkitty`. Let me know and I can make a pull request.

Introducing _glkitty_...

![glkitty](https://github.com/michaeljclark/glkitty/raw/master/images/glkitty.gif)

### About this demo
_glkitty_ is an advanced demo of the kitty terminal graphics protocol showing off-screen OpenGL rendering with Mesa along with simultaneous console animation and keyboard input. It could be used to port simple OpenGL games to the console. It could also serve as a useful test case for the evolution of the terminal graphics protocol.

_glkitty_ was edited from the public domain gears demo in the GLFW distribution, originally derived from the Mesa gears demo. It has been modified to use the OpenGL ES2/ES3 programmable shader pipeline. The original gears demo is fixed function immediate mode. _glkitty_ thus allows testing of shaders on the command-line in kitty terminal.

_glkitty_ uses poll to capture keyboard input and kitty protocol responses while rendering and transmitting double-buffered Base64 encoded images. This is the first cut. It needs hardened error checking of kitty protocol responses and better lifecycle management for terminal image objects. 

### Notes and observations
- _glkitty_ currently alternates presentation between two image ids to avoid flicker.
- It would be interesting to explore the ability be able to _commit_ an update to an existing buffer instead of sending a new image along with cursor updates to display over the top of the last image. Cursor updates would not be required if we could _update_ an image. This needs some thought and experimentation. A surface is logically distinct from an image in EGL for example.
- The current approach wipes a previous image from the session history. It would be good to be able to query the assigned image id or to send a response without an id, and receive a new id, deleting the frame before last. Kitty does not appear to send the image id if there is no id passed with a request. It seems that if we want to get a new image id, we cannot find out what it is, as the query request requires an id.
- Sometimes kitty can spew back unexpected responses when quitting.

The lifecycle of image objects for animation needs some thought and experimentation. I would be interested to discuss. Is there a discord or gitter for kitty?

While a shared memory transports exists, I decided to use the Base64 RGBA protocol, because it works from remote, thus is a common denominator, and secondly, it's lower overhead than compressing frames which would be very expensive for local displays. We could perhaps add zlib, and perhaps also add a query for a shared memory transport and used shared memory when running on the same machine. A fast RLE frame difference update method would also be interesting to explore.

Anyhow thanks! kitty really is an interesting experiment and I hope a formal version of the graphics protocol will be adopted by the other major terminals.  Thank you for working on this. I think the graphics protocol has lots of potentials.

**Comment by Luflosi** [comment]
https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec should help with your need to update an image without flicker if I understood you correctly.

**Comment by michaeljclark** [comment]
@Luflosi neat. note my comment about the distinction between surface and image in EGL. while I am not suggesting kitty needs to add a surface object, it would make atomicity simpler and more robust to network delays. one could then atomically present the image id to the surface without worry of intervening background loading. the other issue is regards getting new ids. with a new id (i am using fixed ids), we could then delete past ephemeral images for our surface while retaining the last image of prior runs in the console history. sorry for the brief writing. i am writing from my phone.

**Comment by kovidgoyal** [comment]
I dont think this belongs in-tree, but I am happy to link to it from the
graphics protocol pages and the cool integrations pages inthe kitty
documentation.

Regarding animations, it is actually something I am going to add to the
graphics protocol soon-ish. I just need to find a week I can block out
from my other work to sit down and finish it.

There is already support for compression with zlib when transmitting RGB
data:
https://sw.kovidgoyal.net/kitty/graphics-protocol.html#compression

There is also support for querying if shared memory works.
https://sw.kovidgoyal.net/kitty/graphics-protocol.html#querying-support-and-available-transmission-mediums

As @Luflosi pointed out, you can avoid flicker by batching updates using
the existing escape code for it. However, this will be more robustly
solved by the animation extension to the protocol that I am mulling
over. There will basically be the ability to specify "frames" for an
image id, as well as a delay in milliseconds between frame changes. And
obviously the ability to atomically, add/update/remove frames.

As for discussion, just use this ticket, or a new one which I will open
when I finally begin work on the animation protocol.

On Thu, Nov 19, 2020 at 02:06:18PM -0800, Michael Clark wrote:
> ## _glkitty_
> 
> I was looking for an advanced terminal graphics protocol example in C and couldn't find much, so decided to write one. _glkitty_ could be added to a directory of the project, perhaps `contrib/glkitty`. Let me know and I can make a pull request.
> 
> Introducing _glkitty_...
> 
> ![glkitty](https://github.com/michaeljclark/glkitty/raw/master/images/glkitty.gif)
> 
> ### About this demo
> _glkitty_ is an advanced demo of the kitty terminal graphics protocol showing off-screen OpenGL rendering with Mesa along with simultaneous console animation and keyboard input. It could be used to port simple OpenGL games to the console. It could also serve as a useful test case for the evolution of the terminal graphics protocol.
> 
> _glkitty_ was edited from the public domain gears demo in the GLFW distribution, originally derived from the Mesa gears demo. It has been modified to use the OpenGL ES2/ES3 programmable shader pipeline. The original gears demo is fixed function immediate mode. _glkitty_ thus allows testing of shaders on the command-line in kitty terminal.
> 
> _glkitty_ uses poll to capture keyboard input and kitty protocol responses while rendering and transmitting double-buffered Base64 encoded images. This is the first cut. It needs hardened error checking of kitty protocol responses and better lifecycle management for terminal image objects. 
> 
> ### Notes and observations
> - _glkitty_ currently alternates presentation between two image ids to avoid flicker.
> - It would be interesting to explore the ability be able to _commit_ an update to an existing buffer instead of sending a new image along with cursor updates to display over the top of the last image. Cursor updates would not be required if we could _update_ an image. This needs some thought and experimentation. A surface is logically distinct from an image in EGL for example.
> - The current approach wipes a previous image from the session history. It would be good to be able to query the assigned image id or to send a response without an id, and receive a new id, deleting the frame before last. Kitty does not appear to send the image id if there is no id passed with a request. It seems that if we want to get a new image id, we cannot find out what it is, as the query request requires an id.
> - Sometimes kitty can spew back unexpected responses when quitting.
> 
> The lifecycle of image objects for animation needs some thought and experimentation. I would be interested to discuss. Is there a discord or gitter for kitty?
> 
> While a shared memory transports exists, I decided to use the Base64 RGBA protocol, because it works from remote, thus is a common denominator, and secondly, it's lower overhead than compressing frames which would be very expensive for local displays. We could perhaps add zlib, and perhaps also add a query for a shared memory transport and used shared memory when running on the same machine. A fast RLE frame difference update method would also be interesting to explore.
> 
> Anyhow thanks! kitty really is an interesting experiment and I hope a formal version of the graphics protocol will be adopted by the other major terminals.  Thank you for working on this. I think the graphics protocol has lots of potentials.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3111

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by michaeljclark** [comment]
> There is already support for compression with zlib when transmitting RGB

Okay. Thanks. I implemented compression. For the gears demo, it compresses approximately 30X (~97% efficient).

https://github.com/michaeljclark/glkitty/commit/d0f73dfc84ee47842cfd8ac19713d6fed1462a73

Regarding animation. I will review the material on synchronized updates and digest.

Regarding state. I would _possibly_ like to get an id assigned for my image. The problem is that I am a new program instance on the command line and don't have any knowledge about past commands that might have created graphics. This is a problem with the current approach to ids which results in overwriting. If I am assigned one by kitty, that's good, because kitty knows what objects it needs to draw. The command-line app doesn't. I mean kitty is already stateful. If I get a new object, I could delete an old one of _mine_.

There could also be a SHA-2 sum of an object which would facilitate several other things and be quite neat for various reasons (how git works internally and really neat remote delta caching ideas - this is a whole other interesting discussion, about state of the art in graph delta protocols - _git_ and _rsync_ basically - draw list array of SHA-2 sums - this is not a trade secret or patented which is good news - and with a content hash, my cursor object can be remembered so I don't need to transmit it).

I would like you to consider a slightly more sophisticated object model, similar to EGL/Vulkan, which is to separate `surface_id` and `image_id`, but for simplicity and compatibility, you could make them equal, unless the surface is animating. The persistent object is the surface, where some previous image happens to be presented to it. We could then schedule an `image` to be presented on a `surface` at a given frame. Anyhow. Keep it in mind. I am a user of the protocol and there is a contract with the program on the other end. Users. What I mean to say, is that there these protocols were previously ANSI, a national standards body, and there is a consensus of Users. Just consider. I am not trying to suggest to make things complicated. To the contrary.

Understanding that this is a pretty neat experiment.

Anyhow. Here is the code for id responses. As I understand it, if I don't pass an id in my upload request, then there is no response. Actually. This would be the MAC of the object, then problem solved, because any given state is _(practically)_ guaranteed to have a non-conflicting identity. It does mean ~256-bit ids tho. I guess you just have the image object pointer at present:

https://github.com/kovidgoyal/kitty/blob/9193a20b447de3c81d738c5f6c7fa0e6fa8905ef/kitty/graphics.c#L477-L489

**Comment by kovidgoyal** [comment]
If you are drawing images, simply dont care about previous image ids
from other programs. I know of no terminal state that is robust against
multiple non-coperating programs writing to the tty. The same is true 
for images.

On Fri, Nov 20, 2020 at 01:48:55AM -0800, Michael Clark wrote:
> > There is already support for compression with zlib when transmitting RGB
> 
> Okay. Thanks. I implemented compression. For the gears demo, it compresses approximately 30X (~97% efficient).
> 
> https://github.com/michaeljclark/glkitty/commit/d0f73dfc84ee47842cfd8ac19713d6fed1462a73
> 
> Regarding animation. I will review the material on synchronized updates and digest.
> 
> Regarding state. I would _possibly_ like to get an id assigned for my image. The problem is that I am a new program instance on the command line and don't have any knowledge about past commands that might have created graphics. This is a problem with the current approach to ids which results in overwriting. If I am assigned one by kitty, that's good, because kitty knows what objects it needs to draw. The command-line app doesn't. I mean kitty is already stateful. If I get a new object, I could delete an old one of _mine_.
> 
> There could also be a SHA-2 sum of an object which would facilitate several other things and be quite neat for various reasons (how git works internally and really neat remote delta caching ideas - this is a whole other interesting discussion, about state of the art in graph delta protocols - _git_ and _rsync_ basically - draw list array of SHA-2 sums - this is not a trade secret or patented which is good news - and with a content hash, my cursor object can be remembered so I don't need to transmit it).
> 
> I would like you to consider a slightly more sophisticated object model, similar to EGL/Vulkan, which is to separate `surface_id` and `image_id`, but for simplicity and compatibility, you could make them equal, unless the surface is animating. The persistent object is the surface, where some previous image happens to be presented to it. We could then schedule an `image` to be presented on a `surface` at a given frame. Anyhow. Keep it in mind. I am a user of the protocol and there is a contract with the program on the other end. Users. What I mean to say, is that there these protocols were previously ANSI, a national standards body, and there is a consensus of Users. Just consider. I am not trying to suggest to make things complicated. To the contrary.
> 
> Understanding that this is a pretty neat experiment.
> 
> Anyhow. Here is the code for id responses. As I understand it, if I don't pass an id in my upload request, then there is no response. Actually. This would be the MAC of the object, then problem solved, because any given state is _(practically)_ guaranteed to have a non-conflicting identity. It does mean ~256-bit ids tho. I guess you just have the image object pointer at present:
> 
> https://github.com/kovidgoyal/kitty/blob/9193a20b447de3c81d738c5f6c7fa0e6fa8905ef/kitty/graphics.c#L477-L489
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3111#issuecomment-731064236

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by Luflosi** [comment]
Let's say that the shell displays a fancy prompt using the image protocol. It uses the id 1. If you then run a program that displays an image with id 1 and then exits, the shell will try to display its fancy prompt again by reusing the image it sent previously but the image was replaced by the program. If the program had some way to query for a free image id, this wouldn't have happened.

**Comment by michaeljclark** [comment]
@Luflosi yes. anyhow, making an SHA-2 cryptographic hash is a near-perfect solution. The chance of some SHA-1 128-bit commit to the terminal has the same probability of a git commit id conflicting which has been estimated. Infinitesimally small. Also, we both know the hash of the object without transmitting anything, I mean if the terminal has cache, so we just respond to proofs that we already have it in cache, to speed up the client. The client with otherwise go ahead and share the payload, if we don't have it, then we can cache it. We can also blow away the cache and the client will start sending the payloads. This works and is in production. It's less heavyweight to compute a cryptographic hash of an image than it is to compress it. This is how we do it.

Anyhow. I am working on a delta canvas, so we can further compress shapes (maybe like [ReGIS](https://en.wikipedia.org/wiki/ReGIS)). I might be another standards implementor. I don't have a terminal but I have a pannable canvas. Also there is skia. This only works if we have standards btw so we kinda need to cooperate. It's what the Users are going to want, and I predict the content hash will be the most predictably computable ID for some object we possess, but impossible to know what the object is unless we have it, or access to information from someone who has is.

Fight! (but don't oversell 😂). We do have to agree on the same hash algo. Maybe truncated SHA-512. Just not MD5 or SHA1.

**Comment by michaeljclark** [comment]
I mean if we are just in RAM, the cost of the hash is low. We don't need to go to disk. We could, and warm cache at startup.

**Comment by kovidgoyal** [comment]
On Fri, Nov 20, 2020 at 03:37:49AM -0800, Luflosi wrote:
> Let's say that the shell displays a fancy prompt using the image protocol. It uses the id 1. If you then run a program that displays an image with id 1 and then exits, the shell will try to display its fancy prompt again by reusing the image it sent previously but the image was replaced by the program. If the program had some way to query for a free image id, this wouldn't have happened.

Shell prompts need to leave terminal global state in a well defined
state, otherwise they *will* break things for programs. That's why they
dont do things like adjust default colors, or alter other global state
(keyboard mode is one exception). 

The same is true of images. A shell prompt is a small thing, if its
going to use an image it would be a small one, and easily
re-transmitable. 

Querying for a free image id, is an extra roundtrip. So its not going to
happen. And I am definitely not going to hash every image or transmit
hashes, a complete waste of CPU cycles. What I might be willing to do
is allow a program to assign a provisional id and the terminal to reply
with the final id, which will be the provisional oneif no such ids have
been assigned, or a new one.

**Comment by kovidgoyal** [comment]
After spending some time thinking about this, here is the outline of what I intend to build:

1) You will be able to use a number as a non-unique id when sending an image to the terminal. Even if another image with the same number exists, a new image will be created, and hereafter all commands that reference this number will refer to the newest image. When doing this the terminal will send a reply with the number and the actual allocated id for the image. This allows the client program to send an image using its own number with multiple commands without needing to wait for a reply from the terminal. After it receives the reply it should switch to using the specified id from the terminal instead.

2) There will be the ability to add frames to any image along with a time interval after which the frame should be displayed.

3) There will be the ability to delete and edit the pixel data in frames or parts of frames

4) There will be the ability to create a new frame by specifying only a delta from the previous frame in terms of changed pixels (this is useful for saving data transmission, when one frame is similar to the previous one). This item will probably come later as it requires research on the best format for specifying these deltas.

Anyway this is the outline for what I intend. if it does not address your use case, please speak now.

**Comment by kovidgoyal** [comment]
Note that I have deliberately left out any consideration of client controlled animations, mainly becuse iven that the communication between client and terminal has unknown and variable latency, this is a difficult problem.
