### ISSUE TITLE
Feature Request: Keyboard Shortcut to show and hide tab bar

### ISSUE THREAD

**Issue by jsphnecclia** [kovidgoyal/kitty#3115]
I would rather not always show a tab bar, but still be able to use tabs often. 

Being able to toggle visibility of a tab bar on a particular instance with a keyboard shortcut is what I would like.

I've considered the hidden tab bar option and the minimum tabs number to show a tab bar option, but both have issues.
The former's issues are obvious - sometimes a tab bar is needed, or tab names are relevant! 
The minimum tabs number option is helpful - the tab bar appears when the tab number (and thus supposed complexity of the tabbed window) grows. However, some windows with as few as 2 tabs benefit from having a tab bar, and some with above 4 or 5 don't. 

The organizational use of tabs would definitely be helped by a toggle-able tab bar

I figured this as a feature request because it seems like it would be trivial to add, however it is far beyond my level of skill to do so

**Comment by kovidgoyal** [comment]
I'm not a fan of this, I dont really see why one's need for tabbars
would come and go. If you mean you only want to see a tab bar when
deciding which tab to switch to, then simply hide the tab bar and use
the tab picker action for it, which presents you with a list of tabs. 

That said, there is no actual hrm in having such an action, so patches
are welcome.

**Comment by jsphnecclia** [comment]
That tab picker action workflow you mentioned is what I meant. Is that available somewhere? I can't find it

**Comment by kovidgoyal** [comment]
ah, I was mis-remembering, the tab picker is present for the
detach_window action, not for actually choosing a tab to switch to.
You should be able to implement it very easily by simply cloning the
detach_window() function in boss.py to a new function named choose_tab
and instead of calling move_window_to at the end call set_active_tab.

You can create a PR for it, or even just implement it in a kitten for
yourself. https://sw.kovidgoyal.net/kitty/kittens/custom.html

**Comment by VioletJewel** [comment]
Yeah, this is something I used in tmux a lot before I switched to st with tabbed. I could do it with that, as well. I also need the tab bar to be able to "come and go". I mean, I could spend a long time studying kitty's source code before submitting a pull request, switch back to st+tabbed, or you could just use the knowledge you have of your own project to spend like 20 minutes adding this feature. Is there any reason this is WONTFIX?

**Comment by VioletJewel** [comment]
saddest part is it's probably easier to submit a PR than write a kitten.

I found this on accident: https://github.com/kovidgoyal/kitty/blob/6d2b17d87754a3d1e985cf4f2d157dcf28093cfb/kitty/tabs.py#L1344

However, I have no idea how to update that option (and refresh?) kitty with a kitten. Gotta go.

**Comment by kovidgoyal** [comment]
Jesus Christ. Do you really believe you are somehow entitled to other people's free labor? If writing a kitten is too much bother for you, use
```
map f1 remote_control load-config -o tab_bar_min_tabs=1
map f2 remote_control load-config -o tab_bar_min_tabs=2
```

**Comment by VioletJewel** [comment]
I didn't realize it was such a hassle. Do not worry. We will use something else. Thank you for an interesting spectacle. Maybe someone will use all of your free labor to build something people will want to use. I will move back to st and tabbed despite some difficulties with multi-width glyphs. Thanks for the renewed inspiration to finagle some convoluted C code. If things get to be too much, you can always take a break. Be well.
