### ISSUE TITLE
Web page cut off on mobile

### ISSUE THREAD

**Issue by jgarvin** [kovidgoyal/kitty#3116]
On Android all the text is shifted to the right so it's cut off, and there is no horizontal scroll.

![Screenshot_20201121-212443](https://user-images.githubusercontent.com/102322/99892938-27ab5100-2c40-11eb-8426-7ce83fe61b40.png)

**Comment by kovidgoyal** [comment]
You can scroll horizontally using two fingers. As for why there is a slight overflow, I have no idea, you'd have to ask the maintainers of the alabaster sphinx theme.
