### ISSUE TITLE
background color leaks

### ISSUE THREAD

**Issue by basedtho** [kovidgoyal/kitty#3119]
**Describe the bug**
sorry, i couldn't come up with a better title, this is a weird rendering bug, probably has to do with ansi escape codes or something. you can see it here https://0x0.st/iRAk.mp4 . this only happens in kitty

**To Reproduce**
1. add an rss feed to ~/.config/lidya/urls
2. run the binary from this page https://github.com/basedtho/lidya/actions/runs/361150926
3. press j or down until the last on the page is selected
4. if there's still room in the window it will turn white (or black, depending on your colorscheme

**Expected behavior**
background should stay black (or white)

**Screenshots**
![image](https://user-images.githubusercontent.com/60894565/99934462-e33cb580-2d12-11eb-8e58-fe28701a10f9.png)

**Environment details**
OS: archlinux, kitty 0.19.1, the library i build my program with is called crossterm you can find it [here](https://github.com/crossterm-rs/crossterm/). but the problem is not with it, because it works properply in other terminal (tried, alacritty, gnome-terminal and terminator)

```
kitty 0.19.1 created by Kovid Goyal
Linux unix 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64

Loaded config files: /home/tho/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
font_family           JetBrains Mono
font_size             9.0
open_url_modifiers    2
scrollback_lines      4294967295
update_check_interval 24.0
```

**Additional context**
reproducible with `kitty --config NONE`

here's minimal `~/.config/lidya/urls` (lidya will only create `~/.config/lidya/read` to store read articles)
```
https://www.phoronix.com/rss.php
```

**Comment by kovidgoyal** [comment]
Your program is almost certainly assuming the background color erase property. Which kitty does not support. You should assume this only if it is present in terminfo. It is not present in kitty's terminfo. https://sw.kovidgoyal.net/kitty/protocol-extensions.html#ext-styles
