### ISSUE TITLE
True color support not working in tmux

### ISSUE THREAD

**Issue by thomasjachmann** [kovidgoyal/kitty#312]
Got this on a Retina MacbookPro (2016) running macOS Sierra (10.12.6).

This is a follow-up for #306. After I was able to start tmux, I noticed it doesn't seem to know the terminal supports true colors, so it doesn't use the full palette.

in kitty (without tmux):
![bildschirmfoto 2018-02-06 um 11 43 28](https://user-images.githubusercontent.com/3219/35855292-0cf5c736-0b33-11e8-8c26-15ee8c27c0c7.png)

in tmux (inside kitty):
![bildschirmfoto 2018-02-06 um 11 43 01](https://user-images.githubusercontent.com/3219/35855282-07572a54-0b33-11e8-8bf9-e1db30486105.png)

This works in other terminals with the same tmux configuration, maybe the terminfo misses some information about true color support?

**Comment by kovidgoyal** [comment]
terminfo does not have any information about truecolor support. The terminfo maintainer refused to add it. I have no idea what tmux uses to guess if a terminal support true color or not, you'd have to ask its maintainers. It might be a custom terminfo capability or it might be hardcoded. If the former, I can probably add it to kitty's terminfo, if the latter tmux will need to be changed.

**Comment by thomasjachmann** [comment]
For documentation: After your answer, I remembered a way to tell tmux it should use true color support. You need to specify terminal-overrides in your tmux.conf:

```
set -ag terminal-overrides ",xterm-kitty:Tc"
```

You could also use `xterm-*` instead of xterm-kitty in order to set this for all xterm terminals.

**Comment by kovidgoyal** [comment]
You can do this in tmux:

```
set-option  -ga terminal-overrides  ",xterm-kitty:Tc"
```

**Comment by thomasjachmann** [comment]
duplicate comment :D

**Comment by MindTooth** [comment]
Don't know if something has changed, but I only need to set:

```tmux
set -g default-terminal "xterm-kitty"
```

And so far I've had no issue.

**Comment by wookayin** [comment]
@MindTooth But that won't work if one uses another terminal emulator, would it? (e.g., sometimes kitty, sometimes iTerm2)

**Comment by MindTooth** [comment]
> @MindTooth But that won't work if one uses another terminal emulator, would it? (e.g., sometimes kitty, sometimes iTerm2)

You're absolutly right.  I've updated my original post.  One should never use anything other than `screen*|tmux*` as default terminal inside `tmux`.

Seems `kitty` works with 24-bit color, but I've yet to make iTerm2 support it.

**Comment by tomasz-wiszkowski** [comment]
Sharing solution for anyone interested. Just got it working.

```
infocmp kitty > kitty.terminfo
echo '    setrgbb=\E[48;2;%p1%d;%p2%d;%p3%dm, ' >> kitty.terminfo
echo '    setrgbf=\E[38;2;%p1%d;%p2%d;%p3%dm, ' >> kitty.terminfo
tic -x -o ~/.terminfo kitty.terminfo
```

Local term caps will take precedence over system-wide capabilities, so this should work.

Kitty already defines `setaf` and `setab` term caps, but this is not what tmux is looking for (`setrgbf` and `setrgbb`). tmux tries the other variant, and when it can't find proper descriptors, it falls back to next available mode (256color, next 16 color).

I completely understand Kovid in this matter: there's a lot of bad fragmentation here and the `setrgb#` caps should not be invented, but alas, this is not an ideal world.

**Comment by kovidgoyal** [comment]
kitty's terminfo has had those capabilities for years https://github.com/kovidgoyal/kitty/commit/2ab6f57159ac4b406148208e2972c6784f502f78

**Comment by tomasz-wiszkowski** [comment]
Thanks for bringing this up Kovid. I did not realize this and `infocmp` does not dump these keys by default.

Looking a bit deeper it looks to me that there is one minor update that would help in the [documentation](https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer):

The documentation suggests to run:

```
infocmp xterm-kitty | ssh myserver tic -x -o \~/.terminfo /dev/stdin
```

but `infocmp` won't dump these keys by default:

```
% infocmp
#	Reconstructed via infocmp from file: /Applications/kitty.app/Contents/Resources/kitty/terminfo/78/xterm-kitty
xterm-kitty|KovIdTTY,
        ...
	rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l, rmso=\E[27m,
	rmul=\E[24m, rs1=\E]\E\\\Ec, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, tsl=\E]2;, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?%[;0123456789]c, u9=\E[c, vpa=\E[%i%p1%dd,
```

so these keys don't get pushed to remote machine (cloud, headless workstations etc).

now `infocmp -a` does is what helps:

```
 infocmp -a
#	Reconstructed via infocmp from file: /Applications/kitty.app/Contents/Resources/kitty/terminfo/78/xterm-kitty
xterm-kitty|KovIdTTY,
        ...
	rmul=\E[24m, rs1=\E]\E\\\Ec, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, tsl=\E]2;, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?%[;0123456789]c, u9=\E[c, vpa=\E[%i%p1%dd,
	kDC3=\E[3;3~, kDC4=\E[3;4~, kDC5=\E[3;5~, kDC6=\E[3;6~,
	kDC7=\E[3;7~, kDN=\E[1;2B, kDN3=\E[1;3B, kDN4=\E[1;4B,
	kDN5=\E[1;5B, kDN6=\E[1;6B, kDN7=\E[1;7B, kEND3=\E[1;3F,
	kEND4=\E[1;4F, kEND5=\E[1;5F, kEND6=\E[1;6F,
	kEND7=\E[1;7F, kHOM3=\E[1;3H, kHOM4=\E[1;4H,
	kHOM5=\E[1;5H, kHOM6=\E[1;6H, kHOM7=\E[1;7H,
	kIC3=\E[2;3~, kIC4=\E[2;4~, kIC5=\E[2;5~, kIC6=\E[2;6~,
	kIC7=\E[2;7~, kLFT3=\E[1;3D, kLFT4=\E[1;4D,
	kLFT5=\E[1;5D, kLFT6=\E[1;6D, kLFT7=\E[1;7D,
	kNXT3=\E[6;3~, kNXT4=\E[6;4~, kNXT5=\E[6;5~,
	kNXT6=\E[6;6~, kNXT7=\E[6;7~, kPRV3=\E[5;3~,
	kPRV4=\E[5;4~, kPRV5=\E[5;5~, kPRV6=\E[5;6~,
	kPRV7=\E[5;7~, kRIT3=\E[1;3C, kRIT4=\E[1;4C,
	kRIT5=\E[1;5C, kRIT6=\E[1;6C, kRIT7=\E[1;7C, kUP=\E[1;2A,
	kUP3=\E[1;3A, kUP4=\E[1;4A, kUP5=\E[1;5A, kUP6=\E[1;6A,
	kUP7=\E[1;7A, rmxx=\E[29m,
	setrgbb=\E[48\:2\:%p1%d\:%p2%d\:%p3%dm,
	setrgbf=\E[38\:2\:%p1%d\:%p2%d\:%p3%dm, smxx=\E[9m,
```

Pretty sure lots of us here got caught by this.

would it make sense to update the documentation to suggest running:

```
infocmp -a xterm-kitty | ssh myserver tic -x -o \~/.terminfo /dev/stdin
```

please? I am pretty confident this is what we're universally running into...

**Comment by kovidgoyal** [comment]
Sure, done.
