### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by WSLUser** [kovidgoyal/kitty#3120]
**Is your feature request related to a problem? Please describe.**
Currently any terminal not covered by GPL but MIT can't license wise port features of kitty such as NCBLIT_PIXEL. In order to improve the terminal ecosystem, using MIT will prove more helpful than GPL-3. In particular Microsoft doesn't particularly allow any type of GPL-3 code to be used with only small exceptions. I'd like to see features of Kitty be adopted by the Windows console and Windows Terminal. This will prove very difficult due to licensing.
**Describe the solution you'd like**
Switch licensing or add separate licensing allowing for this project to also be covered by MIT.
**Describe alternatives you've considered**
Somehow maintain a feature through a ton of refactoring beyond simply changing the programming language. This will likely result in bugs, perf issues, etc. as a result in any other terminal that tries to provide features that only Kitty has implemented so far.
**Additional context**

**Comment by kovidgoyal** [comment]
I dont know what NCBLIT_PIXEL is, if you mean the kitty graphics protocol, I dont see what the GPL has to do with it, unless Microsoft are planning to copy the actual kitty code, which is what is covered by the GPL not a protocol.
