### ISSUE TITLE
nnn preview from within kitty

### ISSUE THREAD

**Issue by ThomasBucaioni** [kovidgoyal/kitty#3123]
**Describe the bug**
When pressing `;p` from within `nnn`, _kitty_ answers:
```
The layout splits is unknown or disabled
vsplit is not a valid value for the --location option. Valid values are: neighbor, first, last
```

**To Reproduce**
1. set `NNN_FIFO='/tmp/nnn.fifo'` in `.bashrc`
2. set `NNN_PLUG='p:preview-tui'` in `.bashrc`
3. set `SPLIT="h"` or `"v"` in `.bashrc`
4. in kitty config (ctrl+shift+f2), set `allow_remote_control` to `yes`
5. in kitty config, set `enabled_layouts` to `all` or `splits`
6. copy the plugin `preview-tui'` in `~/.config/nnn/plugins/`
7. start `nnn` and press `;p`
8. quit `nnn`, an error message should show in the terminal

**Expected behavior**
The _kitty_ window should split and show a directory tree.

**Screenshots**
![nnn_kitty_split_2020-11-27_07-16-06](https://user-images.githubusercontent.com/63013654/100417780-eec90d00-3081-11eb-928b-b322a67107e1.png)
![nnn_kitty_split_2020-11-27_07-17-45](https://user-images.githubusercontent.com/63013654/100417789-f12b6700-3081-11eb-9e0b-e258ee411ba4.png)
![nnn_kitty_split_2020-11-27_07-19-09](https://user-images.githubusercontent.com/63013654/100417802-f4265780-3081-11eb-97ae-03488ddf3241.png)
![nnn_kitty_split_2020-11-27_07-37-35](https://user-images.githubusercontent.com/63013654/100418689-7ebb8680-3083-11eb-9fa9-90c4c5151cff.png)

**Environment details**
OS: Xubuntu 20

```
~ > kitty --debug-config
kitty 0.15.0 created by Kovid Goyal
Linux pc-user 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/user/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control  y
font_family           Hack Nerd Font Mono
font_size             10.0
update_check_interval 0.0
visual_bell_duration  0.1
window_border_width   2.5
Changed shortcuts:
	shift+control+0 KeyAction(func='next_window', args=())
	shift+control+9 KeyAction(func='previous_window', args=())
```

**Additional context**
Using `kitty --config NONE`, an `xterm` opens showing the directory tree.

**Comment by kovidgoyal** [comment]
Your version of kitty is too old.

**Comment by ThomasBucaioni** [comment]
It's the one installed with `sudo apt install kitty`... Then, I'll compile the source. Thank you for your help

**Comment by ThomasBucaioni** [comment]
Where can I find the package xinerama, maybe it's hidden in some library?
```
The package xinerama was not found on your system
```

**Comment by Luflosi** [comment]
Probably `sudo apt install libxinerama-dev`.

**Comment by ThomasBucaioni** [comment]
> Probably `sudo apt install libxinerama-dev`.

The last one I didn't see in the `sudo apt-cache search xinerama` list... Thank you

**Comment by ThomasBucaioni** [comment]
Now it breaks at wayland-scanner:
```
No package 'wayland-scanner' found
```
The package `wayland-scanner++` is installed, but it doesn't solve the compilation error

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/build.html for all the dependencies.

**Comment by ThomasBucaioni** [comment]
> See https://sw.kovidgoyal.net/kitty/build.html for all the dependencies.

Wonderful, it was `libpython3-dev` needed (there's a typo on the website). The preview works too now, many thanks
