### ISSUE TITLE
Font configuration is not working properly

### ISSUE THREAD

**Issue by tbrodbeck** [kovidgoyal/kitty#3124]
A question, I have followed this tutorial to set my font (https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Edit-config-file) and I do not get any errors that the font is not found. 
But still I get those weird characters instead of devicons in `ranger`:
![Screenshot 2020-11-27 at 12 45 49](https://user-images.githubusercontent.com/24418160/100446102-7d538380-30ae-11eb-85d6-b23d0feaf8b7.jpg)

This is my configuration:
```
font_family      Hack Nerd Font Mono Regular
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic
```
My font correctly such that it works everywhere?

```
kitty 0.19.2
ranger version: ranger 1.9.3
```

EDIT:
I found a strange workaround to get it running: I type `kitty fonts` in my Terminal.app and this opens another instance of kitty that I can reopen to get the font applied..

**Comment by kovidgoyal** [comment]
This has nothing to do with fonts. Most likely your LANG or some other environment variable is incorrect. Compare the output of env from the working and non-working kitties and fix whatever the difference is via either your shell rc files or env in kitty.conf

**Comment by tbrodbeck** [comment]
Ok I just used the default configuration, so I guess all environment variables are not set. 
"This has nothing to do with fonts." But which environment variables do I have to set to get fonts working? My LANG variables is not used and I already copied my PATH in the kitty.conf.

**Comment by tbrodbeck** [comment]
I actually copied the whole output of the working version `env` into my rc.conf but it does not change anything

**Comment by tbrodbeck** [comment]
```env TERM_PROGRAM=Apple_Terminal
env TERM=xterm-kitty
env SHELL=/bin/zsh
env TMPDIR=/var/folders/bh/jqqn3bsj5c933dvg40_n_4sc0000gn/T/
env HIGHLIGHT_STYLE=bright
env TERM_PROGRAM_VERSION=440
env TERM_SESSION_ID=F0E1177A-8649-40F4-B78D-5D80F2AC9989
env SDKMAN_PLATFORM=Darwin
env ZSH=/Users/tillmann/.oh-my-zsh
env USER=tillmann
env SDKMAN_CANDIDATES_API=https://api.sdkman.io/2
env SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.aRqzirTu5j/Listeners
env FZF_DEFAULT_OPTS=--height=70%
--reverse
--cycle
--bind alt-w:toggle-preview-wrap
--bind ctrl-d:half-page-down
--bind ctrl-k:kill-line
--bind ctrl-u:half-page-up
--bind ?:toggle-preview
--bind "ctrl-y:execute-silent(ruby -e 'puts ARGV' {+} | sed 's/[0-9]*  //' | pbcopy)+abort"
env PAGER=less
env LSCOLORS=Gxfxcxdxbxegedabagacad
env PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/kitty.app/Contents/MacOS:/Users/tillmann/res/bin:/usr/local/sbin:/Users/tillmann/Library/Python/3.8/bin:/Users/tillmann/go/bin:/usr/local/opt/openjdk/bin:/Users/tillmann/dev/flutter/bin:/usr/local/opt/fzf/bin:/Users/tillmann/res/bin:/usr/local/sbin:/Users/tillmann/Library/Python/3.8/bin:/Users/tillmann/go/bin:/usr/local/opt/openjdk/bin:/Users/tillmann/dev/flutter/bin:/usr/local/bin
env __CFBundleIdentifier=com.apple.Terminal
env PWD=/Users/tillmann/Desktop
env JAVA_HOME=/Users/tillmann/Library/Java/JavaVirtualMachines/adopt-openj9-11.0.9/Contents/Home
env HOMEBREW_GITHUB_API_TOKEN=ac8018f729043c823e6b8f8c1fef9a2c4a34aa8f
env SDKMAN_VERSION=5.9.1+575
env XPC_FLAGS=0x0
env XPC_SERVICE_NAME=0
env HOME=/Users/tillmann
env SHLVL=2
env IBMCLOUD_ANALYTICS=false
env LESS=-R
env LOGNAME=tillmann
env SDKMAN_DIR=/Users/tillmann/.sdkman
env VISUAL=nvim
env SDKMAN_CANDIDATES_DIR=/Users/tillmann/.sdkman/candidates
env __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2
env EDITOR=/usr/local/bin/nvim
env KITTY_WINDOW_ID=1
env WINDOWID=112887
env COLORTERM=truecolor
env TERMINFO=/Applications/kitty.app/Contents/Resources/kitty/terminfo
env OLDPWD=/Users/tillmann/Desktop
env LC_CTYPE=UTF-8
env _=/usr/bin/env```

**Comment by kovidgoyal** [comment]
Those charaacters are not font glyphs, they are normal ascii characters, so the question is why is ranger producing those, instead of what it should be producing. The most typical culprit is some env var. Do a diff between the two environments and find out what difference is. Or ask in the ranger issue tracker.

**Comment by tbrodbeck** [comment]
My question is not about ranger, it is about the font of the terminal. And somehow I am not able to set it with the configuration. I feel like my configuration is not even read correctly. 
Maybe Kitty just takes the preferences of Terminal.app when I launch from there, idk.. Why does the config not work though?..

**Comment by tbrodbeck** [comment]
> Do a diff between the two environments and find out what difference is. 

Thats what i did btw.
*Here some more research:*
kitty seems to know my font:
```sh
➜  Desktop kitty list-fonts
[...]
Hack Nerd Font Mono
    Hack Nerd Font Mono Bold
    Hack Nerd Font Mono Bold Italic
    Hack Nerd Font Mono Italic
    Hack Nerd Font Mono Regular
[...]
```
```sh
➜  Desktop kitty --debug-config
kitty 0.19.2 created by Kovid Goyal
Darwin MacBook-Pro 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.0.1 BuildVersion:	20B29
Loaded config files: /Users/tillmann/.config/kitty/kitty.conf

Config options different from defaults:
font_family Hack Nerd Font Mono
font_size   13.0
```

**Comment by kovidgoyal** [comment]
Like I said a while back, not a font issue.

**Comment by tbrodbeck** [comment]
> Like I said a while back, not a font issue.

What kind of issue is it then? I ruled out being a ranger and a env variable issue..

**Comment by kovidgoyal** [comment]
Like I said, those "weird symbols" of yours are ascii characters,
not the unicode code points that would produce nerd font icons. Why ranger is
producing those in some situations and not others, only the ranger
developers can tell you.

**Comment by tbrodbeck** [comment]
Ok thanks for the clarification. I will look into it!
