### ISSUE TITLE
Automatic Theme switching

### ISSUE THREAD

**Issue by tbrodbeck** [kovidgoyal/kitty#3125]
**Is your feature request related to a problem? Please describe.**
I like the automatic theme switching from day to night depending on the sun circle that is possible in recent versions of macOS.

**Describe the solution you'd like**
It would be great if kitty would support (automatic) theme switching as well. A day theme would be much appreciated.
 
**Describe alternatives you've considered**
It might be possible to adjust the color settings of kitty to get a light theme. But is it possible to allow kitty to apply other colors at dawn and daybreak?

This is inspired from Terminal.app and iTerm which support this.

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in implementing autmatic theme switching
in kitty itself, but kitty provides comprehensive APIs to change colors
dynamically, so you can setup a simple cron script or the like to do it
for you. 
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by tbrodbeck** [comment]
Thanks I have been able to fix it like this:
```sh
if [ `sunshine -s "@52.501730 13.421410"` == "day" ]; then
    kitty @ --to unix:`fd kitty /tmp/`  set-colors ~/.config/kitty/kitty-themes/themes/CLRS.conf
else
    kitty @ --to unix:`fd kitty /tmp/`  set-colors ~/.config/kitty/kitty-themes/themes/VibrantInk.conf
fi
```

**Comment by tbrodbeck** [comment]
Thanks I have been able to fix it like this:
```sh
if [ `sunshine -s "@lat long"` == "day" ]; then
    kitty @ --to unix:`fd kitty /tmp/`  set-colors ~/.config/kitty/kitty-themes/themes/CLRS.conf
else
    kitty @ --to unix:`fd kitty /tmp/`  set-colors ~/.config/kitty/kitty-themes/themes/VibrantInk.conf
fi
```
