### ISSUE TITLE
Any plans to make an macOS universal app?

### ISSUE THREAD

**Issue by screendriver** [kovidgoyal/kitty#3126]
**Is your feature request related to a problem? Please describe.**

Are there any plans to make an macOS universal app that includes both binaries for Intel as well as binaries for the new ARM64-based Apple M1 silicon chip?

**Comment by kovidgoyal** [comment]
Someday, sure.

**Comment by Luflosi** [comment]
@screendriver do you have a Mac with an Apple silicon chip?

**Comment by screendriver** [comment]
Yes 🙂

**Comment by kovidgoyal** [comment]
kitty is pretty trivial to build from source, do that any you will have
an ARM version. https://sw.kovidgoyal.net/kitty/build.html

**Comment by yingzhu146** [comment]
I've just tried to build it from source on a Macbook Air with M1.

I'm using the following flags:

```bash
CFLAGS='-arch arm64' CC="$(which clang)"
```

and running either

```bash
make
```

or 

```bash
python setup.py kitty.app
```

I'm running into 

```bash

❯ make
python3 setup.py 
CC: /usr/bin/clang (12, 0)
[1/1] Building launcher... done
[4/4] Linking kittens/choose/subseq_matcher ... done
Linking kittens/choose/subseq_matcher ...
/usr/bin/clang -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -D_FORTIFY_SOURCE=2 -arch arm64 -flto -Ikitty -I/Users/<user>/miniconda3/include/python3.9 -Wall -O3 -shared -flto build/subseq_matcher-charsets.c.o build/subseq_matcher-main.c.o build/subseq_matcher-output.c.o build/subseq_matcher-score.c.o build/subseq_matcher-unix_compat.c.o -ldl -framework CoreFoundation -L/Users/<user>/miniconda3/lib -lpython3.9 -Wl,-stack_size,1000000 -framework CoreFoundation -o build/kittens/choose/subseq_matcher.so
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```
Any idea how to get around here @kovidgoyal?  Not too much experience with compiling.

Happy to open separate issue too.

**Comment by kovidgoyal** [comment]
that is caused by a bug in miniconda. It has added -stack_size to the
cflags for building python extensions. Use a normal python and you
should be fine.

**Comment by mike-hearn** [comment]
FYI for anyone trying this, I was able to get it to build and run on an M1 Mac.

For me, the steps were:

1. Install the ARM version of Homebrew.

2. Install the ARM64 versions of all the required formula (for me this was python3, libpng, harfbuzz and little-cms2). I basically kept installing libraries via Homebrew until the compilation errors stopped.

3. In the kitty repo, run:

```sh
CFLAGS='-arch arm64 -target arm64-apple-macos11' CC="$(which clang)" /opt/homebrew/Cellar/python@3.9/3.9.0_1/bin/python3 setup.py kitty.app
```

(Note that I don't have `python3` linked so I had the full path to its binary, but you may just be able to use python3 directly assuming it's the ARM version.)

![image](https://user-images.githubusercontent.com/1016999/100693653-58d00380-335b-11eb-9951-d3f28bf41a51.png)

**Comment by dvcrn** [comment]
With the latest merge that is linked above this comment no extra steps are needed, just building with python3 setup.py kitty.app works. 

If you're getting `Package zlib was not found in the pkg-config search path.`, do something like 
```
export PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig
```

**Comment by osdiab** [comment]
I'm getting this issue, any tips? i don't know anything about Mac platform libraries, so not sure if I'm missing a dependency + therefore `Carbon.h` isn't present?

```
→ make app
python3 setup.py kitty.app 
CC: clang (12, 0)
[8/47] Compiling kitty/cocoa_window.m ... done
Compiling [cocoa] glfw/egl_context.c ...
clang -MMD -DNDEBUG -D_GLFW_COCOA -D_GLFW_BUILD_DLL -DGL_SILENCE_DEPRECATION -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -D_FORTIFY_SOURCE=2 -flto -fPIC -c glfw/egl_context.c -o build/glfw-cocoa-egl_context.c.o
In file included from glfw/egl_context.c:30:
In file included from glfw/internal.h:188:
glfw/cocoa_platform.h:30:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [app] Error 1
```

**Comment by dvcrn** [comment]
All right, I had to upgrade my kitty because I noticed some weird freezing after unlocking my screen after a while and went through the build steps again. 

No extra steps needed, just build it with a recent python build:

```
/opt/homebrew/Cellar/python@3.9/3.9.2_1/bin/python3 setup.py kitty.app
```

**Comment by osdiab** [comment]
I ended up switching to Alacritty whose build was easier to do on my M1 Mac, for anyone for whom the above fails for some reason.

**Comment by kovidgoyal** [comment]
Here's a universal kitty build: https://download.calibre-ebook.com/betas/kitty-0.20.2.dmg I have no wat to test it on apple silicon.

**Comment by kblcuk** [comment]
Fwiw I've installed `kitty` via homebrew today on MacBook Air M1, and it is running in native mode without any extra configuration 🎉

```
kitty --version
kitty 0.20.3 created by Kovid Goyal
```
![image](https://user-images.githubusercontent.com/5792253/119155755-2b3b5b80-ba5c-11eb-84d8-72b7c2d943e4.png)

**Comment by kovidgoyal** [comment]
The current release of kitty is a universal binary already.

**Comment by Luflosi** [comment]
Yes, that is sort of what he said since Homebrew just uses the precompiled app.
