### ISSUE TITLE
Silent graphic escape

### ISSUE THREAD

**Issue by schauveau** [kovidgoyal/kitty#3127]
When loading an image with index using a graphic escape sequence, the terminal always produces an answer such as `<ESC>_Gi=<id>;OK<ESC>\` in case of success or a more complex message in case of failure. This is really annoying especially when there is no error. In practice that means that the application need to be able to detect the sequence and then discard it without modifying the rest of the the user input. Failure to do so will cause the reply to be interpreted as user input.

In practice, that means that terminal replies are unsuitable for simple programs such as shell scripts. 

Consequently, the graphic protocol should provide a way to control how and when replies are produced.  That could take the form of a new optional argument (R for Reply or V for Verbosity?). The value could be either 0 (the default behavior), 1 (never produce a reply = silent), 2 (produce a reply only after an error) or 3 (always produce a reply).

**Comment by kovidgoyal** [comment]
Dont send an id, you wont get a reply. The only need to send an id is if
you plan to do something ore with the image afterwards. In which case
you are not a simple shell script anymore.

**Comment by schauveau** [comment]
I want the id. Forget the shell script. There are a lot of cases where it is not realistic to parse the input to remove the answer.

**Comment by kovidgoyal** [comment]
name one.

**Comment by schauveau** [comment]
My current goal is to display images in tintin++ (https://tintin.mudhalla.net/).

**Comment by kovidgoyal** [comment]
I'm going to need more detail. Why do you need the id, and if you do,
whats preventing you from waiting for the terminal to reply?

**Comment by schauveau** [comment]
why was the id feature provided?

**Comment by schauveau** [comment]
Never mind! I will patch my kitty repo to disable the OK answer.
