### ISSUE TITLE
No delete char outside of Scrollable Region 

### ISSUE THREAD

**Issue by schauveau** [kovidgoyal/kitty#3129]
TinTin++ (https://tintin.mudhalla.net/) is using the csr (change_scroll_region) escape to define an area for its prompt and other non-scrolling UI elements. I noticed that the BACKSPACE and DELETE key behaviors are inconsistent when using Kitty (0.19.1). I tracked the problem to the fact that the dch (delete_character) escape does nothing when used outside of the scrollable region. 
The expected effect is of course that the right side of the current line should be shifted left by the specified number of characters. That should work the same inside and outside of the scroll region.

There are multiple ways to reproduce the problem.

Method 1:
- install TinTin++
- execute `tt++`
- use the #split command to create the scrollable region.
- observe how BACKSPACE and DELETE keys are broken in the bottom prompt.

Method 2:
- Install the ncurses binary utilities (for tput, reset, ...)
- From a shell prompt, execute `reset ; tput csr 1 10 ; tput cup 20 1`
- That should define a scrollable region and place the shell prompt outside of that region
- Observe how BACKSPACE and DELETE keys are broken
- The result may vary depending of the shell. 

Method 3: 
- Install the ncurses binary utilities (for tput, reset, ...)
- Execute the attached bash script 
- The script defines the upper half of the screen as the scrolling area 
- Then it attempts to remove some characters on each line using `tput dch`
- With Kitty, the lines in the lower half of the screen are not modified thus showing that dch has no effect.

[bug-delete.bash.txt](https://github.com/kovidgoyal/kitty/files/5612038/bug-delete.bash.txt)

**Comment by kovidgoyal** [comment]
dup of #3090, #3096
