### ISSUE TITLE
How to set left option key ONLY to alt in MacOS?

### ISSUE THREAD

**Issue by emninger** [kovidgoyal/kitty#3130]
In the kitty instructions there is said:

#: Use the option key as an alt key. With this set to no, kitty will
#: use the macOS native Option+Key = unicode character behavior. This
#: will break any Alt+key keyboard shortcuts in your terminal
#: programs, but you can use the macOS unicode input technique. You
#: can use the values: left, right, or both to use only the left,
#: right or both Option keys as Alt, instead.

Now, i do not see, what would be the correct syntax to define ONLY the left option key as alt. I tried in several ways but unfortunately to no extent. 

'macos_option_as_alt yes' works (but that's not what i want, since i need access to the utf8 code).

Thanks a lot in advance for any pointer.

**Comment by kovidgoyal** [comment]
macos_option_as_alt left

**Comment by emninger** [comment]
Thanks a lot!!!! That simple ... ;-)
