### ISSUE TITLE
Nvim lsp pyls not working with --single-instance option

### ISSUE THREAD

**Issue by quantum-booty** [kovidgoyal/kitty#3131]
**Describe the bug**
I have a script that opens some files with nvim using kitty:
```
#!/usr/bin/env sh
nohup kitty --single-instance nvim $* &> ~/bin/nohupyes.out &
```
The pyls does not work when I use the option --single-instance.

**To Reproduce**
1. pip install python-language-server
2. Install Nvim nightly:
```
#!/bin/bash
cd ~
sudo rm -r neovim
git clone https://github.com/neovim/neovim
cd neovim
sudo make CMAKE_BUILD_TYPE=Release install
cd ~
sudo rm -r neovim
```
minimal init.vim:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
call plug#end()

autocmd BufEnter * lua require'completion'.on_attach()

lua <<EOF
require'lspconfig'.pyls.setup{}
EOF
```
3. run in the terminal:
`kitty --single-instance nvim test.py
`

**Expected behavior**
Expected no errors and for pyls to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/28958399/100637243-8ea8c400-332a-11eb-8f1f-eb608cb08108.png)

**Environment details**
Arcolinux

**Comment by kovidgoyal** [comment]
I'm afraid I dont know anything about pylsp. You should ask its
developers why it doesnt work.
