### ISSUE TITLE
Detect BG color of edge cells for window padding when window dimensions do not divide cleanly

### ISSUE THREAD

**Issue by oxysoft** [kovidgoyal/kitty#3134]
Hi! As we all know, the terminal is divided into cells and if the dimensions of the window does not divide cleanly, Kitty must add some padding on the edges of the window. Unfortunately, the color of the padding is fixed and always corresponds to Kitty's color scheme. So if I open Vim for example and the bg color does not match, the color of the padding will be different and it can look a bit jarring.

To handle this more cleanly, Kitty could render an extra row and column on all 4 directions where the bg of those cell automatically matches the nearest cell in the corresponding opposite direction. Obviously, these would be 'virtual' cells that are not part of the actual grid buffer.

Does that sound like a good idea?

**Comment by kovidgoyal** [comment]
The color of the padding is rendered to match the background color set
in the active window, if there is one window. You should configure vim 
to change the window background color, this will fix your issue and make
vim more performant as well. For instance this is what I have in my
colors.vim

```vim
hi Normal NONE
let &t_ti = &t_ti . "\033]10;" . s:fg . "\007\033]11;" . s:bg . "\007"
let &t_te = &t_te . "\033]110\007\033]111\007"
```

As for your idea, I will note that cells at the edges of the window can
have individually different colors , for example, shell prompts, command
output, status bar in vim, command bar in vim, borders, etc.

**Comment by oxysoft** [comment]
Hi, apologies for the late reply. It seems like this might not be supported in neovim? I see no difference after setting these variables in my init.vim and testing with a few different colors. Any ideas?

**Comment by kovidgoyal** [comment]
yeah neovim doesnt support it, you need to ask them if they are willing
to support it or create a wrapper script that does it before running
neovim.
