### ISSUE TITLE
Keyboard shortcuts don't work (or anything else)

### ISSUE THREAD

**Issue by KrayzeeKev** [kovidgoyal/kitty#3135]
I'm clearly missing something. Kitty is putty. I am yet to make it do anything putty doesn't. 
Layouts don't work or exist. Windows don't work or exist. Tabs don't work or exist.
None of the claimed default keyboard shortcuts work. 
According to the documentation, CTRL-SHIFT-L will switch layouts. Does not. CTRL-SHIFT-J/K should scroll. They don't. CTRL-SHIFT-ESC is supposed to open the command shell but that's the shortcut for the Windows Task Manager.
The only thing I managed to do is CTRL-SHIFT-F2 which is supposed to open the current selection in the text editor but, instead, it opens the entire window in the text editor.
What am I missing? 
Running KiTTY - 0.74.3.1 @ 07/11/2020 - 17:31:06(GMT)

**Comment by trygveaa** [comment]
You're in the wrong repo. This kitty is not the same as KiTTY for Windows, see http://www.9bis.net/kitty/
