### ISSUE TITLE
Writing custom kitten hints

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#3137]
I'm going through this example here: https://sw.kovidgoyal.net/kitty/kittens/hints.html?highlight=hint#completely-customizing-the-matching-and-actions-of-the-kitten

And I noticed that the handler will open a selection in the browser window which is something I don't want.

I would like to know how to do the simpler cases of simply making it appear in the shell's command line prompt, or saving it into the copy buffer?

**Comment by kovidgoyal** [comment]
Dont call open_url and it wont open in a browser. And if you want to
learn how to copy to clipboard or write to teminal look at the code of
the hints kitten.

**Comment by esn89** [comment]
@kovidgoyal 

Got a strange issue, now that I have successfully written the custom kitty hints like [so](https://pastebin.com/k61VzbrR)
With these settings to trigger it:

```
# Kubernetes resource highlighter (select and input)
map kitty_mod+q kitten hints --customize-processing custom-hints.py --program -

# Kubernetes resource highlighter (select and copy into clipboard)
map kitty_mod+s kitten hints --customize-processing custom-hints.py --program @
```

I notice that when I first start my terminal, it works and I can highlight/paste and use this.  However, throughout the day, a few hours later, the bindings themselves no longer trigger my script.  Any ideas?
