### ISSUE TITLE
Theme color is changes when using ranger shell

### ISSUE THREAD

**Issue by tbrodbeck** [kovidgoyal/kitty#3138]
**Describe the bug**
When running commands in `ranger` this changes the color scheme of `kitty`.

**To Reproduce**
1. Download and activate a bright color scheme like `CLRS`
2. open ranger
3. Use the ranger builtin shell tool
4. The overall color scheme of kitty changes (green color becomes bright yellow)

**Expected behavior**
`kitt` should not change its color theme globally

**Screenshots**
![output](https://user-images.githubusercontent.com/24418160/100916944-c6ed0580-34d6-11eb-9857-67f2ef9c582d.gif)

**Environment details**
OS: Name and version of operating system(s)
macOS
```
Output of kitty --debug-config
Darwin MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.0.1 BuildVersion:	20B29
Loaded config files: /Users/tillmann/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control y
color0               Color(red=134, green=134, blue=134)
color1               Color(red=255, green=102, blue=0)
color10              Color(red=0, green=255, blue=0)
color11              Color(red=255, green=255, blue=0)
color12              Color(red=0, green=0, blue=255)
color13              Color(red=255, green=0, blue=255)
color14              Color(red=0, green=255, blue=255)
color15              Color(red=229, green=229, blue=229)
color2               Color(red=204, green=255, blue=4)
color3               Color(red=255, green=204, blue=0)
color4               Color(red=68, green=179, blue=204)
color5               Color(red=153, green=51, blue=204)
color6               Color(red=68, green=179, blue=204)
color7               Color(red=244, green=244, blue=244)
color8               Color(red=84, green=84, blue=84)
color9               Color(red=255, green=0, blue=0)
cursor               Color(red=111, green=210, blue=252)
cursor_text_color    None
env                  {'LC_CTYPE': 'UTF-8', 'VISUAL': 'nvim'}
font_size            13.0
foreground           Color(red=255, green=255, blue=255)
listen_on            unix:/tmp/mykitty
macos_option_as_alt  3
selection_background Color(red=180, green=213, blue=255)
```
- I tested it without any `ranger` config files activated.
- This issue was not reproducible with `iTerm2` or `Terminal.app`.

**Additional context**
Again I am not completely sure if this is a `ranger` or a `kitty` issue. If you want, I can open a ticket over there again as well.

**Comment by kovidgoyal** [comment]
kitty does not change its theme color, unless something tells it do so.
Find out what is telling it to do so and stop it and you will be fine.

**Comment by tbrodbeck** [comment]
Okay I am assuming the only way is to use something variation of `kitty @ set-colors ~/.config/kitty/kitty-themes/themes/CLRS.conf`?
I cannot imagine how ranger should call something like that but I will ask them in their repo.

**Comment by kovidgoyal** [comment]
There are any ways to change colors in kitty, see the FAQ entry.

**Comment by tbrodbeck** [comment]
OK: https://github.com/ranger/ranger/issues/1983
