### ISSUE TITLE
Ligature issue inside tmux in 0.7.1

### ISSUE THREAD

**Issue by ahstro** [kovidgoyal/kitty#314]
Not sure if this has to do with kitty, but after updating form 0.6.1 to 0.7.1, one of the ligatures in FiraCode is broken, but only when using tmux inside kitty.

On 0.6.1, `--` looked like this, with and without tmux:
![ligature_no_bork](https://user-images.githubusercontent.com/3090888/35862425-eee017c4-0b4b-11e8-8ce5-ee499c648fd3.png)

Now, it looks like this when using tmux:
![ligature_bork_tmux](https://user-images.githubusercontent.com/3090888/35862424-eec40624-0b4b-11e8-8567-eda4913d360a.png)

Like I said, I don't even know if the problem is with kitty or tmux, but you might know what happened during the update that might've caused this?

**Comment by kovidgoyal** [comment]
dup of #303

**Comment by ahstro** [comment]
Oh, my bad. Thanks!
