### ISSUE TITLE
Bottom part of characters cut off with font size <11

### ISSUE THREAD

**Issue by tom-doerr** [kovidgoyal/kitty#3140]
**Describe the bug**
After I set the font size to <11, the bottom part of some characters is cut off. 
For example if I run `echo '_gq O$L'` the lower part of '_gq' is cut off.

**To Reproduce**
Set the font size to <11 or use the following config:
https://github.com/tom-doerr/dotfiles/blob/f7c5313a0973fa4cd25e2c9fb7a47758157c0012/kitty.conf

**Screenshots**
The command is  `echo '_gq O$L'`.
![image](https://user-images.githubusercontent.com/23431444/101051510-e131ec80-3585-11eb-8c24-4988a38da50b.png)

**Environment details**
On Linux-Mint and on Ubuntu 20.04. 

```
kitty 0.15.1 (97af84a063) created by Kovid Goyal
Linux tom-ThinkPad-L460-18 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64
Linux Mint 19 Tara \n \l
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19
DISTRIB_CODENAME=tara
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"
Loaded config files: /home/tom/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity 0.85
enable_audio_bell  False
font_size          9.0
scrollback_lines   10000
scrollback_pager   ['nvim', '-c', 'set ft=man', '-']
shell              zsh
Added shortcuts:
	alt+v KeyAction(func='launch', args=['--type=overlay', '--stdin-source=@screen_scrollback', 'nvim', '-c', 'set ft=man | :$ | :normal k', '-'])

```

**Additional context**
Minimal config:
```
font_size 10
```

**Comment by kovidgoyal** [comment]
Works fine for me on linux. This is almost certainly a font issue. Use
--debug-font-fallback to see what font is being used, and pick a
different font, with font_family in kitty.conf.
