### ISSUE TITLE
ssh kitten broken when remote login shell is non-POSIX compliant

### ISSUE THREAD

**Issue by gustafj** [kovidgoyal/kitty#3143]
The script used by the `ssh` kitten is not working whenever the remote shell is non-POSIX compliant (e.g. fish).

The reason is that the script is read line-by line as is and not executed through the _shebang_, this is the default behavior of `ssh` and is the case for other shells as well (that is the shebang is just read as a plain comment).

Error in fish is:
`fish: Unsupported use of '='. In fish, please use 'set tmp $(mktemp)'.`
From the use of `tmp=$(mktemp)`

https://github.com/kovidgoyal/kitty/blob/4a60413e0b88f2f484ee54583725474fcc419ebb/kittens/ssh/main.py#L15

**Comment by kovidgoyal** [comment]
The ssh kitten needs a POSIX compliant shell. There is no way on God's
green earth to write a script that works with any arbitrary shell.

This is noted in the FAQ, use the manual method for copying over
terminfo if the kitten doesnt work.
