### ISSUE TITLE
Mapping key presses to remote control send-text command fails

### ISSUE THREAD

**Issue by felixge** [kovidgoyal/kitty#3147]
**Describe the bug**

I'm trying to map a key to [send-text](https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-send-text). But when invoking the key I get the following error:

```
remote_control mapping failed

'NoneType' object has no attribute 'partition'
```

**To Reproduce**

1. Edit kitty.conf

```
allow_remote_control yes
map ctrl+enter remote_control send-text hi
```

2. Relaunch kitty
3. Hit ctrl+enter
4. Observe the error shown above.

**Expected behavior**

The text `hi` should appear in the active window.

**Environment details**

OS: Mac OS 10.15.7

```
$ kitty --debug-config --config kitty.conf 
kitty 0.19.2 created by Kovid Goyal
Darwin felix-mbp-2089.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H15
Loaded config files: kitty.conf

Config options different from defaults:
allow_remote_control y
Added shortcuts:
	control+enter KeyAction(func='remote_control', args=['set-spacing', 'margin=30'])
```

**Additional context**

I can reproduce the issue `kitty --config kitty.conf` that contains only the 2 lines of config shown above.

This issue seems to be specific to `send-text`. The following config works as expected:

```
allow_remote_control yes
map ctrl+enter remote_control set-spacing margin=30
```

Thanks for all your work on kitty, it's greatly appreciated!

**Comment by kovidgoyal** [comment]
If you want to send text do it directly like this:

map ctrl+enter send_text all hi

**Comment by felixge** [comment]
Thanks for the fast response @kovidgoyal! That fixes the example in this issue.

However, I had simplified the example to make the issue easier to understand. I'm actually trying to send this text to a specific window, i.e. `--match num:1`. I'm unable to figure out how to make this work via `send_text` (it's different from the remote control `send-text`, right?)

**Comment by kovidgoyal** [comment]
And note you dont need allow_remote_control when creating mappings with remote_control. And just for fun, if you want to do this using plain send_text you would do:

```
map whatever combine : first_window : send_text all hi : nth_window -1
```

**Comment by felixge** [comment]
@kovidgoyal thank you so much for the fix, I'll try it when the next release comes out. And thank you even more for showing me how to use the `combine` feature! I was able to make my shortcut work like this:

```
# repeat last command executed in second window
map ctrl+enter combine : second_window : send_text all \x1b\x5b\x41\n : previous_window
```
