### ISSUE TITLE
neighboring_window up and down work, but left and right do not

### ISSUE THREAD

**Issue by mvolkmann** [kovidgoyal/kitty#3148]
**Describe the bug**
The neighboring_window command works for up and down work, but not for left and right.
I have the default mappings in my kitty.conf file which are:

```text
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
```

**To Reproduce**
1. Create multiple windows using the splits layout.
2. Press ctrl+up and ctrl+down to move to windows above and below the current one and it works.
3. Press ctrl+left and ctrl+right to move to windows left and right the current one, but it doesn't work.

**Expected behavior**
ctrl+left and ctrl+right should move the cursor to the window to the left or right of the current one.

**Environment details**
OS: macOS 10.15.7

```
Output of kitty --debug-config
kitty 0.19.2 created by Kovid Goyal
Darwin rmv-macbook-16.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H2
Loaded config files: /Users/mark/.config/kitty/kitty.conf

Config options different from defaults:
enabled_layouts ['splits']
font_family     Cascadia Code
font_size       24.0
Added shortcuts:
	f5 KeyAction(func='launch', args=['--location=hsplit'])
	f6 KeyAction(func='launch', args=['--location=vsplit'])
	f7 KeyAction(func='layout_action', args=['rotate', ()])
	shift+right KeyAction(func='move_window', args=['right'])
	shift+left KeyAction(func='move_window', args=['left'])
	shift+down KeyAction(func='move_window', args=['bottom'])
	shift+up KeyAction(func='move_window', args=['top'])
	control+right KeyAction(func='neighboring_window', args=['right'])
	control+left KeyAction(func='neighboring_window', args=['left'])
	control+down KeyAction(func='neighboring_window', args=['bottom'])
	control+up KeyAction(func='neighboring_window', args=['top'])
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` - It's not clear to me what this means. I don't have a `kitty` command available in terminal.

**Comment by kovidgoyal** [comment]
It's up and down not top and bottom

**Comment by mvolkmann** [comment]
I think you misread my message. Up and down work for me. It's left and right that do not work.

**Comment by kovidgoyal** [comment]
I see, sorry.

**Comment by kovidgoyal** [comment]
Well, I tried it with the following steps and it works for me:

1) Run kitty as: kitty --config NONE -o 'map left neighboring_window left' -o 'map right neighboring_window right' -o enabled_layouts=splits
2) Press ctrl+shift+enter twice to create two new windows
3) press left and the middle window is selected
4) press right and the rightmost window is selected

I suggest you run kitty as kitty --debug-keyboard and make sure the key events are actually reaching kitty and being processed.
