### ISSUE TITLE
fzf bash tab completion not working

### ISSUE THREAD

**Issue by petobens** [kovidgoyal/kitty#3149]
**Describe the bug**
bash tab completion with fzf is not working.

**To Reproduce**
1. Install fzf with your package manager
2. Start bash without any config: bash --noprofile --norc
3. Source fzf completion: source ~/.fzf.bash
4. Type `kill`, press tab and selected one of the candidate (i.e press enter)

**Expected behavior**
After pressing enter, fzf closes and the selected candidate is completed (see first gif with alacritty). The second gif is with `kitty --config NONE` showing the problem

**Screenshots**
![alacritty](https://user-images.githubusercontent.com/2583971/101362195-8c8cbb00-387e-11eb-8c5f-aab756d071e0.gif)
![kitty](https://user-images.githubusercontent.com/2583971/101362222-957d8c80-387e-11eb-8861-049cd2f569c4.gif)

**Environment details**
OS: Arch linux
Kitty version: kitty 0.19.2

**Additional context**
The issue was also reported in the fzf repo https://github.com/junegunn/fzf/issues/1889.

**Comment by kovidgoyal** [comment]
Works fine for me, I dont see what the terminal emulator could possibly
have to do with wit how fzf works or not. The only thing that could be
relevant is the value ofTERM, make sure it is xterm-kitty.
