### ISSUE TITLE
kitty remote command to change the size of the kitty instance window

### ISSUE THREAD

**Issue by konomikitten** [kovidgoyal/kitty#3150]
**Is your feature request related to a problem? Please describe.**
You're able to set the initial size of the instance window of kitty with `initial_window_width` and `initial_window_height` but after that there's no way to change the size of the instance window.

**Describe the solution you'd like**
It would be nice if we had a remote kitty command such as `kitty @ resize-instance width height`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kovidgoyal** [comment]
This is the responsibility of the window manager, not individual
applications. Inddeed, for some window managers such as tiling ones,
this is not even possibe to do by the application. As such, I am not
interested in implementing it.

**Comment by konomikitten** [comment]
That seems like an odd position considering I thought it would also be the responsibility of the window manager to set the initial window size but we have a setting in the kitty.conf to do just that.
