### ISSUE TITLE
`kitty @ launch` start a shell and also run a command

### ISSUE THREAD

**Issue by prime31** [kovidgoyal/kitty#3151]
This is probably just my issue/misunderstanding/lack of knowledge. I am basically trying to fire off a new Kitty window from kakoune that loads up a second kakoune instance, but that is mostly not relevant. The main gist of things is need to launch a zsh shell then run kak in that shell. I've tried every combination of escaping that i can think of with no luck.

Essentially what I want to do is something like this:
`kitty @ launch kak some_file`

That doesn't work though because it seems `kitty @ launch` doesn't open a shell but just runs the command directly. Is there some way to `kitty @ launch`, open a shell and then run a command?

**Comment by kovidgoyal** [comment]
kitty @ launch zsh -c "whatever"

**Comment by prime31** [comment]
Thanks for the quick response. When I run something like `kitty @ launch zsh -c "ls && pwd"` or `kitty @ launch zsh -c "kak"` it seems like the new Kitty window opens then immediately closes.

Is there a way to get the new window to remain open? Apologies for the newb questions...

**Comment by kovidgoyal** [comment]
zsh -c "ls; read"

**Comment by aisamu** [comment]
For future reference: [`--hold`](https://github.com/kovidgoyal/kitty/issues/667) now exists!
