### ISSUE TITLE
Freeze when printing Unicode char U+009E

### ISSUE THREAD

**Issue by heitoriha** [kovidgoyal/kitty#3157]
**Describe the bug**
Kitty freezes when printing the unicode char U+009E.

**To Reproduce**
Print char U+009E to kitty. 
This can de done by running `printf '\xC2\x9E'` or `echo -e "\u009E"`, depending on your shell.

**Expected behavior**
The character should be printed and kitty shouldn't freeze

**Additional context**
```
$ kitty --debug-config
kitty 0.19.1 created by Kovid Goyal
Darwin mac70541 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H15

Config options different from defaults:

```

Can be reproduced with `kitty --config NONE`, the shell also doesn't seems to matter. Tested with zsh [5.8 (x86_64-apple-darwin18.7.0] and bash [version 3.2.57(1)-release (x86_64-apple-darwin19)] and both show the same behaviour.

**Comment by kovidgoyal** [comment]
kitty is not frozen, you can for instance open new windows by pressing
ctrl+shit+enter

U+009e is an escape code that starts what is known a PM code. These are
terminated by <es>backslash. kitty will keep waiting for that or until
the max escape code size is reached. Note that it is trivial to freeze
any terminal emulator by dumping raw bytes into it, that is why cat for
instance has a -v flag.
