### ISSUE TITLE
Minimal sub-standard for Kitty graphics protocol?

### ISSUE THREAD

**Issue by lf94** [kovidgoyal/kitty#3159]
With my holidays coming up, I'm looking at tackling some projects which I've wanted to for awhile now. One in particular is getting graphics support in alacritty.

After some research, it appears Sixel is not great for a variety of reasons. What does appear great is the thoughts behind the Kitty graphics protocol. One minor thing I really dislike is the native PNG support, but I digress.

Reviewing the protocol a few times, it appears to me that a sub-standard could be extracted. I'm looking at only implementing `<ESC>_Gf=24|32,s=<s>,v=<v>;<payload><ESC>\` , as this is the most minimal functionality required for many useful applications.

I was wondering if I could get some blessing, some extensions, or some suggestions to my proposal. I will begin next week.

One clarification I'd like is, should the payload always be base64? The document is not clear, as the python script uses base64 for chunking but the RGB/A section says it should use 8-bits per channel (so 3 or 4 bytes).

Thanks!

**Comment by kovidgoyal** [comment]
Yes, the payload is always base64, as specified in the standard:
https://sw.kovidgoyal.net/kitty/graphics-protocol.html#the-graphics-escape-code

And if you dont support PNG you will find transmitting indexed images,
such as GIF very inefficient, requiring 4x the bandwidth. Not to mention
that it becomes impossible to use the protocol from simple shell
scripts, since one needs a tool to convert arbitrary images to RGB data.
For actual real world examples of this use case, see for instance,
wttr.in, where you can simply curl a URL into kitty to display weather
information.

As for implementing some fraction of the protocol, I would encourage you
not to do that, because it will mean terminal programs can no longer
rely on having a standard to code against. The one part you can safely
leave out is shared memory support since that has to be queried for
ahead of time, anyway.

**Comment by kovidgoyal** [comment]
Oh and while this is none of my business, I would suggest you get buy in from the alacritty maintainers before spending time on this, as I recall, they are fairly resistant to adding features to their product.

**Comment by lf94** [comment]
Hey!

Thank you for the clarification about the payload. It is great to hear it is always base64!

It is ok that there is some inefficiency. Here I am aiming for simplicity with reasonable efficiency. Using Sixel for true color images is really not efficient at all (and IIRC, not truly possible). Having a tool to convert from whatever format to RGB data is not a problem.

> As for implementing some fraction of the protocol, I would encourage you
> not to do that, because it will mean terminal programs can no longer
> rely on having a standard to code against

This is why I'm asking if you may suggest a "sub-standard". Really just a sub-set of functionality of the current standard. I do not want to implement it all because I believe it is not all necessary (there is nothing in the document showing rationale behind requiring everything for example, which could change my mind).

> this is none of my business, I would suggest you get buy in from the alacritty maintainers before spending time on this, as I recall, they are fairly resistant to adding features to their product

That's ok, I don't expect anyone to adopt anything. I will maintain my own patch if need be. I like the philosophy behind alacritty!

Kitty is a fantastic project too and I look forward to continued support on it. While both kitty and alacritty both have overlap, I think they solve problems in different spaces :slightly_smiling_face: 

Thanks again for your help!

**Comment by lf94** [comment]
I want to mention I'm only aiming to reduce the *potential* friction which creating a non-blessed sub-standard may cause. It's most likely I'll be the only one to use this.

**Comment by kovidgoyal** [comment]
What feature in this spec do you think is not motivated, as far as I know they are all pretty well motivated. 

If you are making something for your personal use only,then feel free to do whatever you like, it's not going to cause any friction at all.

**Comment by lf94** [comment]
For example: clipping the image (x,y,w,h). Why is it important to implement this?

**Comment by kovidgoyal** [comment]
So that clients can send a single image and display different parts of
it efficiently. Think of sprites. Why would this be even slightly
controversial? It's ~ten lines of code to implement in the
terminal emulator for a very common use case.

**Comment by lf94** [comment]
> Why would this be even slightly controversial?

It's not? I'm just giving an example of what you asked for?...

Sorry, I find I am just causing frustration. There is no need to continue.

**Comment by kovidgoyal** [comment]
On Thu, Dec 10, 2020 at 08:33:48PM -0800, Lee wrote:
> > Why would this be even slightly controversial?
> 
> It's not? I'm just giving an example of what you asked for?...

I meant, why is this not obvious? And since it is not obvious,
feel free to send a PR to improve the spec document.

> 
> Sorry, I find I am just causing frustration. There is no need to continue.

Not at all. I am happy to improve/clarfiy the spec.

**Comment by lf94** [comment]
> Not at all. I am happy to improve/clarfiy the spec.

Ok :slightly_smiling_face: I will continue then.

Could you give a concrete example of when sprites would be useful?

Also, I'm not sure if it is possible, but can images be printed side-by-side or does a hack need to be done where two images are made into a single one using a tool like imagemagick and then displayed?

**Comment by kovidgoyal** [comment]
On Fri, Dec 11, 2020 at 10:08:53AM -0800, Lee wrote:
> > Not at all. I am happy to improve/clarfiy the spec.
> 
> Ok :slightly_smiling_face: I will continue then.
> 
> Could you give a concrete example of when sprites would be useful?

Transmit an image once, use different parts of it in different portion
of the user interface, at different times, without needing to
re-transmit.

> 
> Also, I'm not sure if it is possible, but can images be printed side-by-side or does a hack need to be done where two images are made into a single one using a tool like imagemagick and then displayed?

Yes it's possibly you can control image placement with cell or pixel
precision.

> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3159#issuecomment-743344473

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by lf94** [comment]
Quick question: when specifying c and r, should the image be displayed only when it's start coordinates or it's c,r coordinates are in view? And when no c,r , only the cell it started rendering on?

Sorry if that is a bit confusing!

I have been reading alacritty source and it is very cell-based, so this logic would be easiest to use... 

Could you also explain motivation behind delete intersecting cell, row, and col?

Also using X,Y for inner-cell positioning?

Thanks!

On December 11, 2020 9:33:08 p.m. EST, Kovid Goyal <notifications@github.com> wrote:
>On Fri, Dec 11, 2020 at 10:08:53AM -0800, Lee wrote:
>> > Not at all. I am happy to improve/clarfiy the spec.
>> 
>> Ok :slightly_smiling_face: I will continue then.
>> 
>> Could you give a concrete example of when sprites would be useful?
>
>Transmit an image once, use different parts of it in different portion
>of the user interface, at different times, without needing to
>re-transmit.
>
>> 
>> Also, I'm not sure if it is possible, but can images be printed
>side-by-side or does a hack need to be done where two images are made
>into a single one using a tool like imagemagick and then displayed?
>
>Yes it's possibly you can control image placement with cell or pixel
>precision.
>
>> 
>> -- 
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub:
>>
>https://github.com/kovidgoyal/kitty/issues/3159#issuecomment-743344473
>
>-- 
>_____________________________________
>
>Dr. Kovid Goyal 
>https://www.kovidgoyal.net
>https://calibre-ebook.com
>_____________________________________
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kovidgoyal/kitty/issues/3159#issuecomment-743683628

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kovidgoyal** [comment]
Any part of an image that is in view must be displayed. its start co-ordinates are irrelevant.

Motivation: remove images from a place on screen, without caring which images might be present where.

Motivation: Allow pixel perfect alignment of adjacent/overlapping images.

**Comment by lf94** [comment]
How does an image with only a start coordinate affect the cursor? How should the next cursor position be calculated?

On December 14, 2020 3:38:12 a.m. EST, Kovid Goyal <notifications@github.com> wrote:
>Any part of an image that is in view must be displayed. its start
>co-ordinates are irrelevant.
>
>Motivation: remove images from a place on screen, without caring which
>images might be present where.
>
>Motivation: Allow pixel perfect alignment of adjacent/overlapping
>images.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kovidgoyal/kitty/issues/3159#issuecomment-744276360

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kovidgoyal** [comment]
On Mon, Dec 14, 2020 at 10:40:37AM -0800, Lee wrote:
> How does an image with only a start coordinate affect the cursor? How should the next cursor position be calculated?

See my latest commit.

> 
> On December 14, 2020 3:38:12 a.m. EST, Kovid Goyal <notifications@github.com> wrote:
> >Any part of an image that is in view must be displayed. its start
> >co-ordinates are irrelevant.
> >
> >Motivation: remove images from a place on screen, without caring which
> >images might be present where.
> >
> >Motivation: Allow pixel perfect alignment of adjacent/overlapping
> >images.
> >
> >-- 
> >You are receiving this because you authored the thread.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/kovidgoyal/kitty/issues/3159#issuecomment-744276360
> 
> -- 
> Sent from my Android device with K-9 Mail. Please excuse my brevity.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3159#issuecomment-744632781

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________
