### ISSUE TITLE
unicode input

### ISSUE THREAD

**Issue by hjanuschka** [kovidgoyal/kitty#316]
being on `master`  running `C-S-u` results in (MacOS)

<img width="436" alt="bildschirmfoto 2018-02-09 um 11 32 51" src="https://user-images.githubusercontent.com/2891702/36023502-fc93470e-0d8c-11e8-9e0e-2dc71935d22e.png">

i tried adding a symlink

```
lrwxr-xr-x  1 hjanuschka  staff  44  9 Feb 09:50 /usr/local/bin/kitty -> /Applications/kitty.app/Contents/MacOS/kitty
```

built kitty from source.

btw: i  ❤️  kitty, keep up the good work! best terminal emulator so far!

**Comment by kovidgoyal** [comment]
kitty should be adding itself to the PATH automatically. What does

```
echo $PATH
and
which kitty
```

return?

**Comment by hjanuschka** [comment]
$PATH

```
echo $PATH
/Users/hjanuschka/.cargo/bin:/Users/hjanuschka/.rvm/gems/ruby-2.3.0/bin:/Users/hjanuschka/.rvm/gems/ruby-2.3.0@global/bin:/Users/hjanuschka/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/hjanuschka/.cargo/bin:/Users/hjanuschka/.rvm/gems/ruby-2.3.0/bin:/Users/hjanuschka/.rvm/gems/ruby-2.3.0@global/bin:/Users/hjanuschka/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/Applications/kitty.app/Contents/Frameworks/kitty/launcher:/Users/hjanuschka/.rvm/bin:/Users/hjanuschka/.composer/vendor/bin:/Users/hjanuschka/.composer/vendor/bin


```
/usr/local/bin/kitty
```


`/Applications/kitty.app/Contents/Frameworks/kitty/launcher` does not exist

**Comment by kovidgoyal** [comment]
Note that while I have fixed the issue with the launcher, the unicode input still wont work on macOS, until I make a couple of other changes. I'll update this bug report when that's done.

**Comment by kovidgoyal** [comment]
That should take care of it: https://github.com/kovidgoyal/kitty/commit/b6ed3951bcccea459ef40308042b01a8a1830e6e

I've tested it with the regular kitty dmg not the built from source one, but hopefully it works with that as well.
