### ISSUE TITLE
Documentation build is breaking package on Ubuntu

### ISSUE THREAD

**Issue by kesor** [kovidgoyal/kitty#3160]
**Describe the bug**
The changes introduced in https://github.com/kovidgoyal/kitty/commit/cd76d109f528ab2103818a428f22947ff8839309 are causing the build process on Ubuntu Focal to fail.

Ubuntu Focal has `python3-sphinx v1.,8.5-7ubuntu3` and `python3-pygments v2.3.1+dfsg-1ubuntu2` installed as system packages, and when building the documentation package for `kitty` it fails with the following error:

```
TypeError: lex() argument must be a lexer instance, not a class
```
raised by the code in Pygments https://github.com/pygments/pygments/blob/2.3.1/pygments/__init__.py#L38-L50

I checked the value of `lexer` in that function and after reverting `docs/conf.py` in `kitty` to using instances instead of classed it works again.

**To Reproduce**
1. work on Ubuntu Focal with package tools installed
2. `dget "https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/kitty/0.19.2-1/kitty_0.19.2-1.dsc"`
3. `cd kitty-0.19.2`
4. `debuild -b`
5. Error appears

**Environment details**
Trying to build `kitty-0.19.2` on `Ubuntu Focal 20.04`

**Comment by kovidgoyal** [comment]
So apply a patch for it in your build script. Using instances causes builds on sphinx 4+ to break. https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_lexer

Is Ubuntu Focal really going to ship wth such an outdated version of sphinx? I guess the other option is to version check sphinx and use class/instance appropriately. A PR for that is welcome.
