### ISSUE TITLE
Italic glyphs rendering - letters cut off on the sides

### ISSUE THREAD

**Issue by stepantubanov** [kovidgoyal/kitty#3161]
Hello! Thank you for creating kitty, I've just recently switched to using it and it works great! I have noticed a minor rendering issue which is described below.

**Describe the bug**
Italic glyphs for some of the characters are getting cut off (mostly on the left side of the glyph, some of them a little on the right too).

**To Reproduce**
1. Open text editor (terminal vim in the example).
2. Write something in italic.
3. Observe the error.

**Expected behavior**
Glyphs rendered correctly without being cut off.

**Screenshots**
Screenshot shows letters "X", "M", "K" appear cut on the left.
Letter "N"  seems to be cut on the right as well.

Left: kitty. Right:"Terminal" (standard Ubuntu app).
![Screenshot from 2020-12-11 15-35-08](https://user-images.githubusercontent.com/1050523/101904427-e0710a00-3bc6-11eb-952d-37ee77156aab.png)

**Environment details**
Ubuntu 20.04.1 LTS x86_64 (kernel 5.4.0-56-generic)
GPU: NVIDIA GeForce RTX 2060 SUPER

Font used: Hack FC Ligatured.

```
kitty 0.15.0 created by Kovid Goyal
Linux aorus 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/stepan/.config/kitty/kitty.conf
[346 15:40:20.163926] Could not find included config file: /home/stepan/.config/kitty/kitty-os.conf, ignoring
Running under: X11

Config options different from defaults:
background            Color(red=48, green=48, blue=48)
color0                Color(red=48, green=48, blue=48)
color1                Color(red=210, green=82, blue=82)
color10               Color(red=157, green=255, blue=145)
color11               Color(red=255, green=228, blue=139)
color12               Color(red=94, green=183, blue=247)
color13               Color(red=255, green=157, blue=255)
color14               Color(red=220, green=244, blue=255)
color2                Color(red=127, green=225, blue=115)
color3                Color(red=255, green=198, blue=109)
color4                Color(red=64, green=153, blue=255)
color5                Color(red=246, green=128, blue=255)
color6                Color(red=190, green=214, blue=255)
color7                Color(red=238, green=238, blue=236)
color8                Color(red=83, green=83, blue=83)
color9                Color(red=240, green=112, blue=112)
enable_audio_bell     False
font_family           Hack FC Ligatured
font_size             12.0
foreground            Color(red=255, green=255, blue=255)
tab_bar_style         powerline
update_check_interval 0.0
Added shortcuts:
	control+a > 0 KeyAction(func='goto_tab', args=(1,))
	control+a > 1 KeyAction(func='goto_tab', args=(2,))
	control+a > 2 KeyAction(func='goto_tab', args=(3,))
	control+a > 3 KeyAction(func='goto_tab', args=(4,))
	control+a > 4 KeyAction(func='goto_tab', args=(5,))
	control+a > 5 KeyAction(func='goto_tab', args=(6,))
	control+a > c KeyAction(func='new_tab', args=())
```

**Additional context**
Problem is reproducible with `kitty --config NONE`.

**Comment by stepantubanov** [comment]
I also have kitty installed on MacOSX machine, the same problem appears there, but a lot less noticeable and mostly on the right side of the glyph (take a look at "X" character).

<img width="344" alt="Screenshot 2020-12-11 at 15 51 25" src="https://user-images.githubusercontent.com/1050523/101905816-16af8900-3bc9-11eb-96e0-674ca51e65cb.png">

**Comment by kovidgoyal** [comment]
kitty renders characters in fixed size cells. You need to pick a font
family whose italic face is designed to fit in the same metrics as the
regular face, otherwise you will get cut off characters.
