### ISSUE TITLE
Resizing kitty windows causes glitches

### ISSUE THREAD

**Issue by sontran94** [kovidgoyal/kitty#3162]
**Describe the bug**
I installed a fresh arch. My GPU is RX 5700XT using mesa-git and lib32-mesa. When trying to resize kitty windows, glitches appears. Other apps (firefox, steam,...) do not show any glitches. Under kitty --config NONE, the glitches do not appear. Using the same configuration on my laptop (intel/intelHD) shows no glitches when resizing kitty windows.

Thanks for this great terminal emulator.

**To Reproduce**
1. Fresh install arch
2. Swaywm
3. Install kitty, either use floating mode while resize kitty or open multi kitty in tilting mode and resize
4. Glitches appear and disappear after 1s

**Screenshots**
![2020-12-12-122003](https://user-images.githubusercontent.com/12251943/101982566-30a6a580-3c75-11eb-919c-1d0e7bab333d.jpeg)

**Environment details**
OS: Kernel 5.9.13-arch1-1
CPU: Ryzen 3700X
GPU: RX 5700XT
Shell: ZSH with Oh-my-zsh and p10k.

```
kitty 0.19.2 created by Kovid Goyal
Linux homepc 5.9.13-arch1-1 #1 SMP PREEMPT Tue, 08 Dec 2020 12:09:55 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/sontran/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background                 Color(red=46, green=52, blue=64)
color0                     Color(red=59, green=66, blue=82)
color1                     Color(red=191, green=97, blue=106)
color10                    Color(red=163, green=190, blue=140)
color11                    Color(red=235, green=203, blue=139)
color12                    Color(red=129, green=161, blue=193)
color13                    Color(red=180, green=142, blue=173)
color14                    Color(red=143, green=188, blue=187)
color15                    Color(red=180, green=142, blue=173)
color2                     Color(red=163, green=190, blue=140)
color3                     Color(red=235, green=203, blue=139)
color4                     Color(red=129, green=161, blue=193)
color5                     Color(red=180, green=142, blue=173)
color6                     Color(red=136, green=192, blue=208)
color7                     Color(red=229, green=233, blue=240)
color8                     Color(red=76, green=86, blue=106)
color9                     Color(red=191, green=97, blue=106)
cursor                     Color(red=129, green=161, blue=193)
cursor_blink_interval      0.0
font_family                MesloLGS NF
foreground                 Color(red=216, green=222, blue=233)
scrollback_lines           200
select_by_word_characters  :@-./_~?&=%+#
touch_scroll_multiplier    3.0
update_check_interval      24.0
```

**Additional context**
Running `kitty --config NONE` only produces repeated prompts. NO glitches.

**Comment by kovidgoyal** [comment]
This looks like a driver issue to me, try running with stable mesa/downgrade a version or two. If that doesnt work, bisect kitty.conf to find what setting is causing it, possibly one of the sync_to_monitor or refresh rate related settings.

**Comment by sontran94** [comment]
You're absolutely right. Changing back to mesa and having no issue with the resizing glitches. Can you recommend me what is the next step to do: report the driver issue to mesa or live with the current glitches since I need the latest mesa-git to play Cyberpunk2077. Thanks a lot for your godspeed reply.

**Comment by kovidgoyal** [comment]
Report it to mesa am sure they would like to know of regressions.
