### ISSUE TITLE
Graphics protocol appears to make it hard to avoid deleting images sometimes

### ISSUE THREAD

**Issue by danieljabailey** [kovidgoyal/kitty#3163]
I have been playing with the graphics protocol in kitty, and have discovered an unexpected behaviour that's slightly annoying.

If I have a program that transmits an image with an ID and then displays it like so...

    <ESC>_Gs=20,v=20,i=1;<payload><ESC>/
    <ESC>_Ga=p,i=1;<ESC>/

...and then I run the program twice, so that the second instance transmits the same image again, to the same ID, and displays it just like before, then I don't end up with two copies of the image.

The ID is hard coded to 1 in my test program, If I change the ID between runs of the program then I can still see the previous images on the screen.

I'm guessing this is the intended behaviour, so that all images on the screen drawn from the same ID are surely the same image. That would make sense but if that's not the case then this might be a bug.

Assuming that this is intentional, then perhaps it would be nice to extend the graphics protocol so that this problem can be avoided somehow.

Or I'm totally misunderstanding the graphics protocol and there's already a way to do this?

Really liking kitty so far though :D 
Thanks.

**Comment by kovidgoyal** [comment]
See discussion in #3111
