### ISSUE TITLE
Disable automatic update check for packagers

### ISSUE THREAD

**Issue by TheJJ** [kovidgoyal/kitty#3164]
By default, I would like to suggest, kitty should not contact https://sw.kovidgoyal.net/kitty/current-version.txt when it is distributed by packages of e.g. Linux distros.

I think a good solution would be a configuration option at compiletime which enables or disables the update check.

The update check is of very little use if you install kitty through your distro, since it's up to the distro when to deploy and manage the update.

**Comment by trygveaa** [comment]
This already exists, e.g. Arch already uses it, see https://github.com/archlinux/svntogit-community/blob/packages/kitty/trunk/PKGBUILD#L22

**Comment by kovidgoyal** [comment]
Not to mention that this is described in the building kitty page in the
section on note for linux packagers.

https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers

**Comment by TheJJ** [comment]
Oh well, my bad, thanks for the hints :)
