### ISSUE TITLE
Failure to redraw undirtied windows on becoming visible

### ISSUE THREAD

**Issue by LSLeary** [kovidgoyal/kitty#317]
Undirtied windows are not redrawn on becoming visible again. So e.g. if I switch to another workspace then back to the one containing a kitty window, its rectangle will display whatever was there on the other workspace until I focus the kitty window or something dirties it. Since reproducing/testing for this may depend on WM, I'm using xmonad on X11 in Linux (Debian Testing). But it's probably the same with e.g. dwm or i3.

I presume this is due to 0c7d51d, as I checked out to the previous commit, reinstalled and it's no longer happening.

**Comment by LSLeary** [comment]
Also this should probably have its own issue, but is it supposed to be the case that kitty @ <cmd> only works from within a kitty instance? I'd be interested in something like kitty @ new-os-window that would work when called from anywhere and behave like urxvtc to urxvtd.

**Comment by kovidgoyal** [comment]
Yes, kitty @ only works from within kitty. The upside is that it also works over SSH :)
You dont need kitty @ new-os-window, just alias kitty as kitty --single-instance then every kitty invocation will create new OS windows. 

As for the redraw issue, I'll look into it, probably need to liten for expose events from glfw and mark the window dirty, I just hope that glfw actually exposes an API to do that.
