### ISSUE TITLE
vim crashes in kitty

### ISSUE THREAD

**Issue by souvikhaldar** [kovidgoyal/kitty#3170]
**Describe the bug**
KItty crashes when running vim (specially running `fzf` inside it)
**To Reproduce**
1. Open vim
2. Run any `fzf` related command (fzf- https://github.com/junegunn/fzf)
3. vim crashes SEGV

**Expected behavior**
A normal vim screen with expected output.
**Screenshots**
![image](https://user-images.githubusercontent.com/20991754/102102942-62289800-3e52-11eb-8b98-6499b47f490e.png)

**Environment details**
OS: Name and version of operating system(s)
MacOS Big Sur 11.0.1
```
Output of kitty --debug-config  

kitty 0.19.2 created by Kovid Goyal
Darwin Souviks-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.0.1 BuildVersion:	20B29
Loaded config files: /Users/souvikhaldar/.config/kitty/kitty.conf

Config options different from defaults:
bell_on_tab       False
enable_audio_bell False
font_family       FuraCode Nerd Font
font_size         14.0
```

**Comment by kovidgoyal** [comment]
If vim is segfaulting you need to report the issue to vim.

**Comment by souvikhaldar** [comment]
Now even if I'm clicking on kitty the following codes come up automatically.
![image](https://user-images.githubusercontent.com/20991754/102103361-ea0ea200-3e52-11eb-872e-5afd6f479ecc.png)
