### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by ejemba** [kovidgoyal/kitty#3171]
Hi o/
as stated there https://github.com/kovidgoyal/kitty/issues/436#issuecomment-378180484 there is no irc/mailinglist

So I have to ask here, sorry for the noise :s 

1. When doing « kitty_mod+e kitten hints » how can I replace the action "open url in navigator" by "copy url in clipboard" ?
2. Nothing happens when I click on a normal link → how can I debug this ?
3. Nothing happens when I click on an image link (should display the image in overlay) → how can I debug this ?

thank you

**Comment by kovidgoyal** [comment]
Use the discussions for this.

https://github.com/kovidgoyal/kitty/discussions
