### ISSUE TITLE
key repeat not working with wayland

### ISSUE THREAD

**Issue by insidewhy** [kovidgoyal/kitty#3175]
**Describe the bug**
When I switch quickly from one key, to holding a different key, the "repeat" does not work.

**To Reproduce**
1. press "j"
2. very quickly press and hold "k" after releasing "j"

**Expected behavior**
The terminal should output "j" and then output "k" continuously. Instead I get "j" then one "k" without any autorepeat.

If I type "k" then quickly press and hold "k" again right after, it works fine, "k" repeats forever. If I leave some time after switching from "j" to "k" then "k" will auto repeat properly.

**Environment details**
OS: archlinux, all packages fully up to date as of 16th december

```
Output of kitty --debug-config
```

```
kitty 0.19.2 created by Kovid Goyal
Linux lapchil 5.9.13-arch1-1 #1 SMP PREEMPT Tue, 08 Dec 2020 12:09:55 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/james/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background           Color(red=252, green=244, blue=231)
color3               Color(red=178, green=104, blue=24)
editor               nvim
enable_audio_bell    False
font_family          DejaVu Sans Mono
font_size            21.0
foreground           Color(red=0, green=0, blue=0)
selection_background Color(red=51, green=51, blue=51)
selection_foreground Color(red=255, green=250, blue=205)
Added shortcuts:
	 shift+page_up KeyAction(func='scroll_page_up', args=())
	 shift+page_down KeyAction(func='scroll_page_down', args=())
	 super+e KeyAction(func='send_text', args=['all', b'\x01h'])
	 super+n KeyAction(func='send_text', args=['all', b'\x01i'])
```

**Comment by insidewhy** [comment]
I think it's related to this:

I hold "j" and "j" will auto-repeat. Now will still holding "j" I press and hold "k" and "k" will auto-repeat. Now when I release "j", "k" stops auto-repeating. Whereas in X, "k" will keep auto-repeating even after I stop holding "j".

The X behaviour is much better.

**Comment by insidewhy** [comment]
Maybe this is a duplicate of https://github.com/kovidgoyal/kitty/issues/2191

**Comment by kovidgoyal** [comment]
dup of #2191
