### ISSUE TITLE
[PARSE ERROR] Unsupported screen mode:  7727 (private)

### ISSUE THREAD

**Issue by mckelly2833** [kovidgoyal/kitty#3177]
Hi,

Every time I run kitty I get these 2 lines -

[351 20:41:28.692011] [PARSE ERROR] Unsupported screen mode:  7727 (private)
[351 20:41:53.269516] [PARSE ERROR] Unsupported screen mode:  7727 (private)

Any idea what is the cause and if it should be resolved ?

I am using -
kitty 0.19.2
Ubuntu 18.04 with latest updates
A pretty standard kitty.conf I think

**Comment by mckelly2833** [comment]
I also see many (100s) of msgs such as this -
```
Dec 16 20:51:02 myhost org.gnome.Shell.desktop[2183]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x360000e (kitty)
```
Not sure if it is related ?

**Comment by kovidgoyal** [comment]
The cause is some terminal program you are running using
unsupported/terminal specific escape codes. It is harmless, ignore it.

**Comment by mckelly2833** [comment]
@kovidgoyal thx.
Is there a way for me to learn what those bad esc codes are ?
Are the many msgs of "... _NET_ACTIVE_WINDOW message with a timestamp of 0 ..." related or a problem ?
ty

**Comment by kovidgoyal** [comment]
They are unrelated, the error message tells you exactly what the escape
code causing the issue is. It is the escape code used to set screen
modes, which is a CSI h code, also known as SM.
