### ISSUE TITLE
Visual/mouse selection lost when horizontal split pane scrolls in tmux

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#3178]
Given a tmux window with two panes split horizontally, kitty will lose the visual selection (e.g. from having double-clicked a word) in the left pane, if the right pane scrolls down, i.e. with `for i in {1..100}; do echo $i; sleep 1; done`.

This does not happen with vertically split windows, i.e. it seems like kitty detects that the (whole) line where the selection is in was changed and discards it therefore?
If that's the case it would be great if it could detect that the selected text itself was not changed, which is often the case with selecting single words only.

In particular this is annoying when trying to select something via click-and-drag, while something like a build with lots of output is running in a vertically split pane.

I hope this is clear enough without more details, but I'm happy to provide those, of course.

kitty 0.19.2, Arch Linux

**Comment by kovidgoyal** [comment]
I'm afraid implementing this is way too resource intensive. One then has
to track the dirtied status of the selection instead of just lines
(which come for free since that is tracked anyway for other reasons),
which means every operation that touches even a single character now has
to be checked against the selection.

**Comment by blueyed** [comment]
> every operation that touches even a single character now has
> to be checked against the selection

Could this be only done if there is a selection in the first place?
Or would checking for that already be too expensive?
I mean that having no selection is the common mode, and it being slower when there is a selection would be a good trade-off for me.
If you are not interested in looking at it yourself, I'd appreciate some pointer into the responsible code to take a look myself maybe then.

**Comment by kovidgoyal** [comment]
It would be too expensive in the with selection case, in the no
selection case it would require benchmarking to see if the additional
overhead of a branch per operation is significant or not. 

There is no single bit of code responsible for this. You basically would
have to modify every single function in screen.c that alters the buffer
in any way. And maintain that in perpetuity, every time any new function
is added. Grep for linebuf_mark_line_dirty() to see all the places where
currently kitty tracks dirtied lines.

Much easier and more productive long term to just wean yourself off of
terminal multiplexers if you ask me.

**Comment by blueyed** [comment]
> Much easier and more productive long term to just wean yourself off of
> terminal multiplexers if you ask me.

I guess it also affects tui apps where you have split panes (e.g. tig), but of course there it is much more unlikely that it scrolls while you want to select something.

Thanks for the feedback/help here - I'm happy for know what the root cause of this annoying behavior is.
A good workaround is also to zoom the pane, of course.
