### ISSUE TITLE
Comment: 'xterm-kitty': unknown terminal type.

### ISSUE THREAD

**Issue by sklages** [kovidgoyal/kitty#3179]
- **Is your feature request related to a problem? Please describe.**
This is a real game-stopper, `'xterm-kitty': unknown terminal type` each time I connect to whatever server as whatever user.

- **Describe the solution you'd like**
A known terminal type :-)

- **Describe alternatives you've considered**
Just some other terminal emulator like `guake` .. but finally I'd probably stick with standard GNOME terminal :-(

- **Additional context**
As there are quite a few terminal emulators out there without that issue, I suspect there must be a way to avoid `'xterm-kitty': unknown terminal type` somehow ..

Last but not least, I like `kitty` and the way it works. But I have a bunch of accounts at work working on many different servers, so that `kitty +kitten ssh usera@serverb` things are getting annoying.

**Comment by kovidgoyal** [comment]
This is answered in the FAQ and umpteen other closed bug reports. Please dont spam.

**Comment by sklages** [comment]
@kovidgoyal  .. yes I read that FAQ, and yes, there are _workarounds_ mentioned, but yes, it is still annoying and IMHO not necessary. But if you consider than **spam** ... well, okay, fairwell ...
