### ISSUE TITLE
Scroll is very slow on swaywm in Wayland

### ISSUE THREAD

**Issue by zsolt-donca** [kovidgoyal/kitty#3180]
**Describe the bug**
Scrolling the buffer is much slower when running on [swaywm](https://github.com/swaywm/sway) in Wayland-native mode when compared to running on X11. I need to scroll 5 times with my mouse to actually scroll two rows in the terminal (it scroll one line after scrolling 3 times with my mouse, and then it scroll another one after 2 times, and this behavior repeats). Comparatively, on X11 it is scrolling like 3 separate lines in the terminal for each mouse scroll. If I do the math, it turns out that I have a slowdown factor of 7.5, which is subjectively quite annoying.

It is also scrolling very slow using my laptop's touchpad.

I don't experience a different scroll speed in any application other than kitty. This is the only application that displays this weird behavior when on swaywm/Wayland.

**To Reproduce**
1. Open kitty on swaywm, and I believe kitty should run out-of-the-box in native Wayland mode
2.  Execute some commands to fill up the scrollback buffer.
3. Scroll with the mouse upwards, and notice that is scroll very slow.

**Expected behavior**
I would like kitty to scroll the same way on swaywm as when on an X11-based window manager, such as i3wm, which is multiple lines for each mouse scroll.

**Environment details**
OS: Arch Linux, on the latest [sway-git](https://aur.archlinux.org/packages/sway-git/) package.

```
❯ kitty --debug-config
kitty 0.19.2 created by Kovid Goyal
Linux ROC01-HYMT373 5.9.14-zen1-1-zen #1 ZEN SMP PREEMPT Sat, 12 Dec 2020 14:36:44 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/zdonca/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
active_tab_background      Color(red=42, green=47, blue=56)
active_tab_font_style      (True, False)
active_tab_foreground      Color(red=225, green=227, blue=228)
allow_remote_control       y
background                 Color(red=42, green=47, blue=56)
background_opacity         0.95
color0                     Color(red=24, green=26, blue=28)
color1                     Color(red=255, green=101, blue=120)
color10                    Color(red=157, green=210, blue=116)
color11                    Color(red=234, green=203, blue=100)
color12                    Color(red=114, green=204, blue=232)
color13                    Color(red=186, green=156, blue=243)
color15                    Color(red=225, green=227, blue=228)
color2                     Color(red=157, green=210, blue=116)
color3                     Color(red=234, green=203, blue=100)
color4                     Color(red=114, green=204, blue=232)
color5                     Color(red=186, green=156, blue=243)
color6                     Color(red=246, green=156, blue=94)
color7                     Color(red=225, green=227, blue=228)
color8                     Color(red=130, green=138, blue=154)
color9                     Color(red=255, green=101, blue=120)
cursor                     Color(red=225, green=227, blue=228)
cursor_text_color          None
font_family                MesloLGS Nerd Font
foreground                 Color(red=225, green=227, blue=228)
inactive_tab_background    Color(red=42, green=47, blue=56)
inactive_tab_foreground    Color(red=225, green=227, blue=228)
scrollback_lines           100000
select_by_word_characters  :@-./_~?&=%+#
selection_background       Color(red=61, green=68, blue=85)
selection_foreground       Color(red=225, green=227, blue=228)
single_window_margin_width FloatEdges(left=-1000.0, top=-1000.0, right=-1000.0, bottom=-1000.0)
window_border_width        (1.0, 'pt')

```

**Additional context**
I can reproduce the problem with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Change touch_scroll_multiplier to whatever you like in kitty.conf.

**Comment by zsolt-donca** [comment]
Thanks @kovidgoyal for the quick response! I can confirm that the setting higher values to the config `touch_scroll_multiplier` you mentioned along with the related config `wheel_scroll_multiplier` does indeed help in my case.

But I still doubt that there isn't an issue here: shouldn't the app behave the same way on both Wayland and X11 with the same config? If the unit of measure for scrolling is just different on Wayland (or maybe just on sway), then I feel like it would be the best for `kitty` to expect this and interpret the same config differently, so that it produces the same user behavior. Other apps seem to do the same, as I don't experience anything being different with regards to scrolling on any app but on `kitty`.

Also, this very slow scrolling behavior seems to be the default on sway (as I did not touch these configs before), and I'd argue that it is a bad default behavior.

**Comment by apiraino** [comment]
Confirming that the workaround works on Wayland. My configuration is Wayland+Sway,  don't even have `xwayland` installed.

Funnily enough, setting `touch_scroll_multiplier` "fixes" both the touchpad and the mouse scrolling.

As specified in the documentation, [wheel_scroll_multiplier](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.wheel_scroll_multiplier) and [touch_scroll_multiplier](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.touch_scroll_multiplier) behave differently on "... high precision scrolling (...) such as macOS and Wayland". My uneducated guess is that input handling on Wayland is a completely different [can of worms](https://wayland-book.com/seat.html) and trying to make it work the same on both Xorg and Wayland would require a non-negligible amount of effort.
