### ISSUE TITLE
Highlighted text after pasting

### ISSUE THREAD

**Issue by petobens** [kovidgoyal/kitty#3181]
**Describe the bug**
After I paste some text from the clipboard it gets highlighted. I want to disable that feature.

**To Reproduce**
1. Copy some text into the clipboard
2. Open kitty using the following config:
```
map super+v paste_from_clipboard
background #24272e
foreground #abb2bf
```
3. Press super+v to paste the text.

**Expected behavior**
As it can be seen in the gif below the pasted text gets highlighted until the cursor moves. I would like to disable such highlighting.

**Screenshots**
![Peek 2020-12-19 10-25](https://user-images.githubusercontent.com/2583971/102690495-8c78ad80-41e4-11eb-9fcf-208548de3a9e.gif)

**Environment details**
OS: Arch Linux
kitty 0.19.3

**Comment by kovidgoyal** [comment]
the highlighting is done by your shell, not kitty. Run

kitty cat

and paste and you will see there is no highlighting.
