### ISSUE TITLE
Memory leak when compton (compositor) is used

### ISSUE THREAD

**Issue by linosgian** [kovidgoyal/kitty#3182]
**Describe the bug**
When [compton](https://github.com/chjj/compton) is used and I switch between i3 workspaces (kitty's workspace and some other), kitty's memory usage goes higher without opening any tabs or doing anything related to the terminal itself. I've notice that there were a lot of entries like the ones below in kitty's process' memory regions:

```
7f05bf4e8000-7f05bf4eb000 rw-s 00000000 00:2c 2763539                    /i915 (deleted)
7f05bf4eb000-7f05bf4ed000 rw-s 00000000 00:2c 1410343                    /i915 (deleted)
7f05bf4ed000-7f05bf4ef000 rw-s 00000000 00:2c 2800837                    /i915 (deleted)
7f05bf4ef000-7f05bf4f1000 rw-s 00000000 00:2c 2354349                    /i915 (deleted)
7f05bf4f1000-7f05bf501000 rw-s 00000000 00:2c 2797528                    /i915 (deleted)
7f05bf501000-7f05bf502000 rw-s 00000000 00:2c 1406575                    /i915 (deleted)
7f05bf502000-7f05bf505000 rw-s 00000000 00:2c 2355428                    /i915 (deleted)
```  
After looking that up, it turns out they are GEM objects (Graphical Execution Manager).
I've tried to debug this by reviewing X events, with and without the compositor but I couldn't narrow the issue down any further.
Lastly, as shown below (in the config I've added), the issue only manifests when `sync_to_monitor` is false.

Cases that the issue does not manifest:
1. switching between i3 windows in the same workspace (kitty and some other program/window)
2. Refreshing i3 multiple times when kitty is displayed
3. Toggling fullscreen on and off
4. compton (or picom another compton fork) is not used

It only seems to happen when I switch from another workspace to kitty's workspace, and kitty has the entire window.
 
**To Reproduce**
1. Open kitty on an i3 workspace
2. Fire up compton (default config)
3. Switch between kitty's workspace and some other workspace
4. Watch the RAM getting eaten by kitty
5. Kill compton and the RAM usage stops rising

**Environment details**
OS: Name and version of operating system(s)

```
Output of kitty --debug-config
kitty 0.19.2 (e06ef732d8) created by Kovid Goyal
Linux lgian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
Debian GNU/Linux 10 \n \l
Loaded config files: /home/lgian/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
sync_to_monitor False
```

**Additional context**
It seems that disabling `sync_to_monitor` triggers the issue.
```
# lgian[~] → lspci -v | grep -i vga -A15
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Lenovo UHD Graphics 620
	Flags: bus master, fast devsel, latency 0, IRQ 142
	Memory at 2ffa000000 (64-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by kovidgoyal** [comment]
Thats driver memory, not kitty memory. You should report it to the
maintainers of the GPU driver you are using.
