### ISSUE TITLE
Search text in output

### ISSUE THREAD

**Issue by xareelee** [kovidgoyal/kitty#3187]
**Is your feature request related to a problem? Please describe.**

In Terminal.app on macOS, there is a hotkey `cmd+F` to display a search bar and you could use it to search text in the history output.

**Describe the solution you'd like**

- A search bar showing up when pressing `cmd+F`, and hiding when pressing `esc`.
- Be able to easily jump between matched words.
- Support regex syntax mode with a toggle.

**Comment by kovidgoyal** [comment]
Press ctrl+shift+h and type / and your search expression.

**Comment by ujwal-setlur** [comment]
hmm...not working for me on Big Sur. ctrl-shift-h does not do anything...

**Comment by ujwal-setlur** [comment]
Sorry, I had changed kitty_mod. Works...
