### ISSUE TITLE
Ability to name OS Windows or Better way to distinguish them

### ISSUE THREAD

**Issue by risingtiger** [kovidgoyal/kitty#3188]
I've searched the documentation, and as far as I've seen, there isn't a way to name the actual OS window. I'm treating Kitty's OS X Windows similar to Tmux's sessions. I use session a lot to handle different code repos of the same overall project. When I switch between Kitty windows there is not enough information to distinguish which window is what and I end up going to the wrong one often (directory names aren't useful in my case). It would be super useful to be able to name those Windows. Thoughts on that?

**Comment by kovidgoyal** [comment]
Name it and have the name show up where? Simply set the window title
using the standard escape code for it, or the --title argument when
launching the window.
