### ISSUE TITLE
Weird default mapping on fr-latin9 keyboard

### ISSUE THREAD

**Issue by quej1976** [kovidgoyal/kitty#3189]
**Describe the bug**
In sway, i want to map ctrl+shift+eacute to 'goto_tab 2' on my fr-latin9 keyboard but it seems to be map to nth_window

**To Reproduce**
2. put only 'map ctrl+shift+eacute goto_tab 2' in kitty.conf
3. run kitty --debug-keyboard
4. result:
Press xkb_keycode: 0x3a clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press xkb_keycode: 0x2a clean_sym: Shift_L composed_sym: Shift_L mods: ctrl glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
Press xkb_keycode: 0x3 clean_sym: eacute composed_sym: 2 mods: ctrl+shift glfw_fallback_key: 50 (2) xkb_key: 50 (2)
Keypress matched action: nth_window
on_key_input: glfw key: 50 native_code: 0x32 action: PRESS mods: 0x3 text: '' state: 0 handled as shortcut
Release xkb_keycode: 0x3 clean_sym: eacute mods: ctrl+shift glfw_fallback_key: 50 (2) xkb_key: 50 (2)
on_key_input: glfw key: 50 native_code: 0x32 action: RELEASE mods: 0x3 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release xkb_keycode: 0x2a clean_sym: Shift_L mods: ctrl+shift glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: RELEASE mods: 0x3 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release xkb_keycode: 0x3a clean_sym: Control_L mods: ctrl glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: RELEASE mods: 0x2 text: '' state: 0 ignoring as keyboard mode does not allow release events

**Expected behavior**
 ctrl+shift+eacute to excute kitty command 'goto_tab 2'

**Environment details**
OS: Fedora 33
WM: Sway

```
Output of kitty --debug-config
```
Linux 820G2 5.9.15-200.fc33.x86_64 #1 SMP Wed Dec 16 19:14:35 UTC 2020 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: .config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
Added shortcuts:
	shift+control+key: -1 native_key: 233 KeyAction(func='goto_tab', args=(2,))

**Comment by kovidgoyal** [comment]
You want ctrl+shit+key_2

**Comment by quej1976** [comment]
Hi Kovid,

Thank you for your quick reply and awesome work on kitty and calibre.

Unfortunately kitty doesn't seems to like the key combination ctrl+shit+key_2:
[359 08:48:01.540774] Shortcut: ctrl+shift+key_2 has unknown key, ignoring

To add more details, the other shortcuts from the numbers row (ie &é"'(-è_çà) works perfectly as expected:
map ctrl+shift+ampersand goto_tab 1
map ctrl+shift+eacute goto_tab 2
map ctrl+shift+quotedbl goto_tab 3
map ctrl+shift+apostrophe goto_tab 4
map ctrl+shift+parenleft goto_tab 5
map ctrl+shift+minus goto_tab 6
map ctrl+shift+egrave goto_tab 7
map ctrl+shift+underscore goto_tab 8
map ctrl+shift+ccedilla goto_tab 9

Only the eacute one is executing nth_window shortcut (I have no idea where this shortcut come from).

**Comment by kovidgoyal** [comment]
oh make it ctrl+shift+2

**Comment by quej1976** [comment]
It works! Why didn't i tried this one before:(
Sorry to have disturbed you and thanks for everything you've done so far.
I wish you a very happy festive season
