### ISSUE TITLE
vim zenburn transparency and highlighting

### ISSUE THREAD

**Issue by 8FordPrefect8** [kovidgoyal/kitty#3191]
**Describe the bug**
I want to use vim and kitty and have consistent color scheme zenburn.
Additionally I want to have transparency in kitty and vim.
The important lines from vimrc are like that. Wtihout last line. I would get some transparency but only if scrolled and with opaque background for letters, so really glitchy.

```
    let g:zenburn_transparent = 1                                          
    colorscheme zenburn                                        
    let &t_ut=''     
```

My color related lines in kitty.conf are like this:
```
    background_opacity 0.9
    # Zenburn by jnurmine, https://github.com/jnurmine/Zenburn                  
    # This work is licensed under the terms of the GNU GPL license.             
    # For a copy, see http://www.gnu.org/licenses/gpl.html.                     
                                                                             
    background            #3f3f3f                                               
    foreground            #dcdccc                                               
    cursor                #dcdccc                                               
    #selection_background  #21322f                                              
    color0                #4d4d4d                                               
    color8                #709080                                               
    color1                #705050                                               
    color9                #dca3a3                                               
    color2                #60b48a                                               
    color10               #c3bf9f                                               
    color3                #f0deae                                               
    color11               #dfcf9f                                               
    color4                #506070                                               
    color12               #94bff3                                               
    color5                #dc8cc3                                               
    color13               #ec93d3                                               
    color6                #8cd0d3                                               
    color14               #93e0e3                                               
    color7                #dcdccc                                               
    color15               #ffffff                                               
    #selection_foreground #3f3f3f 
```
In all other terminals even with no user config my vimrc leads to following highlighting behavior. Background is dependent on font color. Font color is dark.
In kitty I only get the kitty highlighting colors. If I uncomment the colors from kitty.conf that I found in a kitty theme github page I have systemwide different highlighting (I think its not really zenburn), but it differs from other terminals vim behavior.

Second issue is that in vim with given vimrc I don't get transparent background. Only the borders are transparent.

I am really a noob when it comes to all of this config files and eye candy stuff. So sorry if my problem is not really a bug but misconfiguration.

**Comment by kovidgoyal** [comment]
There is no such thing as transparency in vim. In a terminal a single background color can be transparent. In kitty this is turned on by background_opacity and it makes cells that have the background color or no color have a transparent background instead. So if you want vim to have transparent background set the syntax highlighting color for the normal group in vim to whatever the background color is set in your kitty.conf. Or alternately for better performance, set it to none.

```
hi Normal NONE
```

**Comment by 8FordPrefect8** [comment]
Hmm, maybe I shouldn't have mixed two questions.

The transperency is one issue, the highlihting another.
I am talking about the colors when I select text with the mouse.

So regarding background color and transperency:
If I have a blank kitti.conf and have enabled zenurn in vim, I get a different background color defined by vimrc via zenburn.
There is this line in my vimrc ment for transparent terminals. It has definitely an influence as when present the window looks homogeniously. But not transparent.
I don't know how to edit my .vimrc to make it have no background color after loading zenburn.
If I comment the last line and have kitty transparent then everything beside areas with text are transparent.

Regarding the highlitghting:
This is completley unconnected to transparency. If I mark text with the cursor it behaves in kitty exactly the same as if with vim in kitty. For other terminals it's different. There I have one highlighting in the terminal and a different one in vim.

**Comment by kovidgoyal** [comment]
On Sun, Dec 27, 2020 at 04:01:27AM -0800, 8FordPrefect8 wrote:
> Regarding the highlitghting:
> This is completley unconnected to transparency. If I mark text with the cursor it behaves in kitty exactly the same as if with vim in kitty. For other terminals it's different. There I have one highlighting in the terminal and a different one in vim.

Are you using some ancient version of vim or kitty? In any case turn on
mouse mode in vimrc

set mouse=a

and you will be fine.

**Comment by 8FordPrefect8** [comment]
I am using arch and just installed vim and kitty from official repos. Kitty is in version 0.19.3 and vim in version 8.2.

If I set mouse=a then I have same behavior in vim in different terminals. But the highlighting if selected code looks different then. Maybe I am mislead and it's not vim but terminal related. The other behavior was quite nice. A font color dependent highlighting.

set mouse=a is also handy from a different because now line numbers are not selected and copied.

**Comment by 8FordPrefect8** [comment]
But I had to figure out that with set mouse=a marked text cant be pasted with middle mouse anymore.
If I should dive in to sway again I guess this is like a pre taste of all this clipboard foobar between wayland and x11.
Anyway thanks for your emulator and your support.

**Comment by kovidgoyal** [comment]
On Sun, Dec 27, 2020 at 07:45:27AM -0800, 8FordPrefect8 wrote:
> But I had to figure out that with set mouse=a marked text cant be pasted with middle mouse anymore.
> If I should dive in to sway again I guess this is like a pre taste of all this clipboard foobar between wayland and x11.
> Anyway thanks for your emulator and your support.

Yes, you can, you yank to the select register with "*y
Or hold down shift and select to use th enative terminal select.

**Comment by 8FordPrefect8** [comment]
Works thx.
