### ISSUE TITLE
MacOS delete key goes forward in SSH on Amazon Linux 2

### ISSUE THREAD

**Issue by aekrohn** [kovidgoyal/kitty#3192]
**Describe the bug**
Pressing the DELETE key on a MacOS keyboard moves the cursor forward while SSH'd into Amazon Linux 2 EC2 instance.

Executing `stty -a` shows the 'erase' character as `^?`. Checking the keycode sent to the remote terminal by pressing "ctrl+v, delete button" also shows `^?` as a result, so I'm not entirely sure how this behavior is happening.

I should add that the results of the quick test mentioned above are the same when using iTerm2, but the delete key behaves as expected.

**To Reproduce**
1. SSH to an Amazon Linux 2 EC2 instance
2. Press 'DELETE' key
3. Observe cursor moves forward

**Expected behavior**
Delete button should move backwards, deleting characters behind it

**Screenshots**
n/a

**Environment details**
OS: Amazon Linux 2, EC2 instance

```
$ kitty --debug-config
kitty 0.18.3 created by Kovid Goyal
Darwin -snip- 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.1 BuildVersion:	20C69
Loaded config files: /Users/-snip-/.config/kitty/kitty.conf

Config options different from defaults:
adjust_column_width  0.95
background           Color(red=36, green=51, blue=53)
color0               Color(red=116, green=116, blue=116)
color1               Color(red=130, green=93, blue=76)
color10              Color(red=152, green=217, blue=170)
color11              Color(red=250, green=230, blue=156)
color12              Color(red=121, green=195, blue=207)
color13              Color(red=214, green=178, blue=160)
color14              Color(red=172, green=223, blue=223)
color15              Color(red=223, green=223, blue=223)
color2               Color(red=113, green=139, blue=98)
color3               Color(red=172, green=160, blue=109)
color4               Color(red=76, green=123, blue=130)
color5               Color(red=138, green=113, blue=102)
color6               Color(red=113, green=148, blue=148)
color7               Color(red=223, green=223, blue=223)
color8               Color(red=138, green=138, blue=138)
color9               Color(red=207, green=146, blue=121)
copy_on_select       clipboard
cursor               Color(red=87, green=99, blue=121)
enable_audio_bell    False
font_family          SF Mono
font_size            12.0
foreground           Color(red=211, green=230, blue=211)
macos_thicken_font   0.55
scrollback_lines     250000
selection_background Color(red=255, green=255, blue=255)
selection_foreground Color(red=36, green=51, blue=53)
window_alert_on_bell False
Added shortcuts:
	shift+super+v KeyAction(func='paste_from_buffer', args=['a1'])```
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE`
- Problem still exists

**Comment by Luflosi** [comment]
This is because the Terminfo file is missing on the remote Server. To fix this, execute `kitty +kitten ssh myserver` once. See https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer.

**Comment by aekrohn** [comment]
That solved the problem, thank you!
