### ISSUE TITLE
kitty unexpectedly modifies $PATH

### ISSUE THREAD

**Issue by raylee** [kovidgoyal/kitty#3198]
First off, thank you for such a lovely tool. kitty has made my work life a lot happier.

I was surprised that it modifies my $PATH, however, and places the kitty bin directory at the front of $PATH:
https://github.com/kovidgoyal/kitty/blob/c486fbb7c39c5082ab368ac29adf5f87d334e073/kitty/main.py#L317

My question is, is there a way I can disable this behavior short of recompiling from source? kitty is already in my path as a symlink in ~/.local/bin:
```
readlink ~/.local/bin/kitty
/home/ray/.local/kitty.app/bin/kitty
```
and ~/.local/bin is already in my $PATH, so the addition is unnecessary:
```
echo $PATH | tr : '\n' | grep $HOME/.local/bin
/home/ray/.local/bin
```

Though I add that path in my .bash_profile, so when kitty first starts up it's not immediately available in my $PATH. I'm assuming that's why this logic is triggering even though it's redundant.

Regardless, I reserve the first path on my system for wrapper scripts, so I can modify the behavior of other commands, including, potentially, kitty. (This lets me hide host or platform differences when I swap between MacOS, Linux, or my herd of VMs.)

At minimum if the redundant addition can't be fixed, I think the path could be appended to the end rather than inserted at the beginning.

This is on Ubuntu 18.04, with kitty installed via the one liner on the website
```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
```

Thanks again for the lovely terminal emulator.

**Comment by kovidgoyal** [comment]
I'm afraid not. kitty wants to guarantee you can call the *correct* kitty from inside it as this is used for all sorts of functionality. The kitty executable is needed to provide many services to kitty, as such it is *not* user modifiable.
