### ISSUE TITLE
Kitty shows font using oblique face vs. book face

### ISSUE THREAD

**Issue by beaugunderson** [kovidgoyal/kitty#32]
I use 'Deja Vu Sans Mono for Powerline'; it comes in Book, Oblique, Bold, and Bold Oblique. When I specify the the family name that shows up in FontForge, e.g.:

```
font_family DejaVuSansMonoForPowerline Nerd Font
```

then kitty displays the Oblique font instead of the regular font (Book).

Any other combination I've tried results in a font that is too narrow to be used at all, so I'm not sure how to specify the Book style.

I tried:

```
font_family DejaVuSansMonoForPowerline Nerd Font Book
font_family DejaVuSansMonoForPowerlineNerdFontCompleteMono-Book  # (the font name shown in FontForge)
```

**Comment by beaugunderson** [comment]
I should also specify that this is on OS X using the Core Text API; I'm on e34f74fb7aa6e14b8993258460b058acee011961.

**Comment by kovidgoyal** [comment]
Hmm, I dont have an awful lot of experience with CoreText but I know of no reason why it should prefer the oblique to the regular face, see line 48 of core_text.m where the font descriptor is created, the only traits specified are bold, italic and monospace, bold and italic should give the bold and italic variants and when they are off it should give the normal variant. And in https://developer.apple.com/reference/coretext/ctfontsymbolictraits?language=objc I see no mention of oblique at all. So I'm not sure what else to do here. You can display the full name of the font CoreText resolves to, using the following command:

/Users/Shared/buildbot/sw/sw/bin/python3 /path/to/kitty -c "from kitty.fonts.core_text import *; set_font_family('DejaVuSansMonoForPowerline', 12, True); f=main_font[(False, False)]; print(f.family_name, f.full_name)"

**Comment by kovidgoyal** [comment]
no followup

**Comment by beaugunderson** [comment]
sorry for the slow response @kovidgoyal!

here's what you asked for (I updated to current git and rebuilt before running this):

```
$ /Users/Shared/buildbot/sw/sw/bin/python3 . -c "from kitty.fonts.core_text import *; set_font_family('DejaVuSansMonoForPowerline Nerd Font', 12, True); f=main_font[(False, False)]; print(f.family_name, f.full_name)"
[glfw error]: The GLFW library is not initialized
DejaVuSansMonoForPowerline Nerd Font
DejaVu Sans Mono Oblique for Powerline Nerd Font Complete Mono
$ /Users/Shared/buildbot/sw/sw/bin/python3 . -c "from kitty.fonts.core_text import *; set_font_family('DejaVuSansMonoForPowerline Nerd Font Book', 12, True); f=main_font[(False, False)]; print(f.family_name, f.full_name)"
[glfw error]: The GLFW library is not initialized
Helvetica
Helvetica
$ /Users/Shared/buildbot/sw/sw/bin/python3 . -c "from kitty.fonts.core_text import *; set_font_family('DejaVuSansMonoForPowerlineNerdFontCompleteMono-Book', 12, True); f=main_font[(False, False)]; print(f.family_name, f.full_name)"
[glfw error]: The GLFW library is not initialized
Helvetica
Helvetica
```

Notice that a family name of `'DejaVuSansMonoForPowerline Nerd Font` returns the `Oblique` face (not the `Book` one).

**Comment by kovidgoyal** [comment]
Probably, the font name you need is something like

DejaVu Sans Mono Book for Powerline Nerd Font Complete Mono

or 

Probably, the font name you need is something like

DejaVu Sans Mono Book for Powerline Nerd Font Complete Mono

or 
Probably, the font name you need is something like

DejaVu Sans Mono Book for Powerline Nerd Font Complete Mono

or 


Book for Powerline Nerd Font Complete Mono

or 
Probably, the font name you need is something like

DejaVu Sans Mono Book for Powerline Nerd Font Complete Mono

or 
Book for Powerline Nerd Font Complete Mono

or 
Probably, the font name you need is something like

DejaVu Sans Mono Book for Powerline Nerd Font Complete Mono

or 

DejaVu Sans Mono Regular for Powerline Nerd Font Complete Mono

or 

DejaVu Sans Mono for Powerline Nerd Font Complete Mono
