### ISSUE TITLE
{tab_activity_symbol} in the tab title template

### ISSUE THREAD

**Issue by exebook** [kovidgoyal/kitty#3200]
**Is your feature request related to a problem? Please describe.**
I want to choose where exactly to put the activity symbol, by default it's prepended to the title at the left. I woudl rather have it at the right. Besides I am using spaces in my title template like this: `"  {title}  "`. And the activity symbol looks awkward like that. 

**Describe the solution you'd like**
let me use `{activity}` in the title template.

**Describe alternatives you've considered**
Maybe also you can let me specify margin/gap/spacing for the title?

Forget about the symbol and just add an `activity_color` setting.

Add `{activity_png ~/icons/activity.png}` variable.

For now I used `>` as an activity symbol this serves as an arrow sort of to help me understand if the symbol regards the tab to the left or to the right of the sysmbol.

**Additional context**
There may be more to it, like how long ago the activity happened.

**Comment by kovidgoyal** [comment]
Not something I care to implement, patches welcome.

**Comment by exebook** [comment]
You confuse me here. If patches are welcome why to close the feature request?

**Comment by kovidgoyal** [comment]
Because I dont keep open feature requests for things I dont think are
particularly good/useful ideas. I will still accept a patch, however.

**Comment by exebook** [comment]
![Selection_050](https://user-images.githubusercontent.com/3821217/103450782-a5f21d00-4ced-11eb-885a-65df766c7a1c.png)

**Comment by exebook** [comment]
You are doing a great project here and I can only show a great respect and thank you for your work. I am just trying to understand your reasoning here. If you think the feature is not good/useful why you welcome the patch? Probably it's not that "useless" after all? :-)

**Comment by kovidgoyal** [comment]
Because I am a nice guy, and if this feature is important enough to
someone to spend the time to write the code, I will accept it provided
it has no significant performance/maintenance downsides.

**Comment by exebook** [comment]
That's indeed very nice of you to explain this! But how would others know there is such feature request and write the code if the issue is closed?  ¯\_(ツ)_/¯

**Comment by kovidgoyal** [comment]
Writing code does not require the existence of an issue.
