### ISSUE TITLE
Double clicking the tab bar to get a new tab opened

### ISSUE THREAD

**Issue by exebook** [kovidgoyal/kitty#3201]
**Is your feature request related to a problem? Please describe.**
This is very common to have this feature in tabbed apps.

**Describe the solution you'd like**
Double click the tab bar: the new tab opens.

**Describe alternatives you've considered**
Do not implement this feature and just press `Shift+Control+t`.

**Additional context**
Chrome, Firefox, and tabbed text editors have this.

**Comment by Arnaudv6** [comment]
Thanks @kovidgoyal: nice feature!
