### ISSUE TITLE
Output corruption on macOS

### ISSUE THREAD

**Issue by clangen** [kovidgoyal/kitty#3203]
**Describe the bug**
I work on a terminal-based music player that uses curses. It seems to work well on other major terminal emulators across macOS, Linux, and Windows. However, I'm seeing some output corruption when using line/box drawing characters with kitty v0.18.0 to v0.19.3, but only on macOS. Older versions of kitty (v0.17.4 and older) are fine.

Take a look at the following screenshot, which shows the corruption (towards the bottom of the screenshot, called out in purple text):

![screenshot-kitty-macos-v0 19 3](https://user-images.githubusercontent.com/2031666/103452410-0187c080-4c84-11eb-8684-8a01fc1c481e.png)

Using older versions of kitty, v0.17.4 and earlier, seem fine:

![screenshot-kitty-macos-v0 17 4](https://user-images.githubusercontent.com/2031666/103452415-16fcea80-4c84-11eb-8994-1108bdd1a2b9.png)

Interestingly, I have no problems with newer versions of kitty on Linux (middle screenshot):

![screenshots-linux](https://user-images.githubusercontent.com/2031666/103452419-25e39d00-4c84-11eb-9f7e-1bed65ffc7b3.png)

Things also seem fine with `terminator` and `rxvt-unicode`.

On macOS, `iTerm`, `Terminal.app` and `alacritty` seem fine:

![screenshots-macos](https://user-images.githubusercontent.com/2031666/103452430-47dd1f80-4c84-11eb-99ad-78caec7e920e.png)

On Windows (using PDCurses instead of ncurses), all is good using both the GDI and `cmd.com` variants, as well as WSL/Ubuntu with Microsoft's new Terminal app:

![screenshots-windows](https://user-images.githubusercontent.com/2031666/103452434-66431b00-4c84-11eb-9f2f-0cd0a33c1691.png)

Thankfully, kitty is super easy to compile, so I just used `git bisect` to test commits between the v0.17.4 and v0.18.0 tags, and found the following commit introduces the issue: https://github.com/kovidgoyal/kitty/commit/390e883ecfd461c23670017978d3673dd6d45cc2

If I revert this commit, re-run the `build-terminfo` command, then recompile kitty, the problem goes away.

I think this is some sort of strange edge-case bug, but unfortunately I have not been able to figure out how to generate a minimal code example to reproduce the issue. It's also entirely possible the bug is on my end, but the fact that I don't see the problem in other terminal emulators makes me suspect an issue with kitty.

**To Reproduce**
1. Install `musikcube` on macOS
    * `brew tap clangen/musikcube`
    * `brew install musikcube`
2. Install `kitty` v0.18.0 or newer
3. Run musikcube
4. Observe output corruption.

**Expected behavior**
No output corruption.

**Screenshots**
Screenshots are inline, above.

**Environment details**
macOS 10.15.7, kitty v0.18.0 to v0.19.3

```
kitty 0.19.3 (56ebc9fa92) created by Kovid Goyal
Darwin galizur.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:        10.15.7 BuildVersion:   19H114
Loaded config files: /Users/clangen/.config/kitty/kitty.conf

Config options different from defaults:

> 
```

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
If that commit is causing your issue, then it means that your application (or ncurses underneath) is using the REP capability and kitty is doing something in REP different from what your application/ncurses expect. If you can figure out what that might be, it should be an easy fix. The relevant code is a very short function screen_repeat_character in screen.c

You have two possible avenues of approach:

1) Modify the above function and see what character is being repeated and hopefully figure out what the issue is

2) Run kitty with --dump-commands and search the log file for screen_repeat_character to again 
trace the problem. Then edit this file to keep only a minimal set of commands to reproduce and replay with screen --replay-commands. Once you have that attach it and I should be able to fic the issue using it.

**Comment by kovidgoyal** [comment]
And see if this fixes it: https://github.com/kovidgoyal/kitty/commit/b3ed4c3f40e3f427ac3f93af8a242352caf75335

**Comment by clangen** [comment]
Unfortunately that patch does not fix the issue.

However, I've been playing around with it off and on today, and did manage to get a small example program that demonstrates the problem:

```c++
#include <string>
#include <curses.h>
#include <locale.h>

int main() {
    setlocale(LC_ALL, "");
    initscr();
    
    std::string temp = "o";
    for (int i = 0; i < 300; i++) {
        temp += "─";
    }

    while (true) {
        werase(stdscr);
        wmove(stdscr, 0, 0);
        waddstr(stdscr, temp.c_str());
        refresh();
        getch();
    }

    return 0;
}
```

Compile with `clang++ example.cpp -lcursesw` on macOS.

As you can see it tries to write the string `"o───────..."` with the `'─'` character repeated 300 times. However, the output looks like this:

![image](https://user-images.githubusercontent.com/2031666/103468539-cb435300-4d0e-11eb-9e33-3ad6a1ce5b7d.png)

After some more messing about it seems the conditions required to reproduce the issue are:
1. The repeating character cannot be the first in the string; that is, it needs to be prefixed by at least one other character (in this case, `'o'`)
2. The repeating character must be a multi-byte sequence, in this case the unicode `'─'`.

If you change the repeating character to a regular hyphen (`'-'`), all is good, as in this screenshot:

![image](https://user-images.githubusercontent.com/2031666/103468575-49075e80-4d0f-11eb-9ef1-420feed53eda.png)

**Comment by kovidgoyal** [comment]
That will almost certainly be a bug in the version of ncurses on macOS. Presumably the other terminals you tested on macOS dont support REP so ncurses does not use it there. I dont have access to a macOS machine at the moment, so cant check for myself, but use kitty --dump-bytes and attach the dump file and I can use it to confirm.

**Comment by kovidgoyal** [comment]
I tried it on my macOS system with up-to-date ncurses installed via homebrew:

clang++ test.cpp -L/usr/local/opt/ncurses/lib -lncursesw -o test

it worked fine. So update your ncurses and you should be fine.

**Comment by kovidgoyal** [comment]
And just to confirm your reproducer does indeed reproduce with the system ncurses (note that this is ncurses not ncursesw, as far as I know macOS does not ship with ncursesw)

**Comment by kovidgoyal** [comment]
And as a workaround I suggest interleaving the characters in your progress bar with the zero width space char u+feff which will hopefully prevent ncurses from using the REP optimisation.

**Comment by clangen** [comment]
Yep, just confirmed if I link against the version of ncurses provided by homebrew all is good. And also confirmed my other terminal emulators do not support `REP`. 

Thanks for your help tracking down this obscure bug.
