### ISSUE TITLE
ANSI escape code for "light" variants of a font decreases opacity of glyphs instead of switching to the appropriately weighted typeface

### ISSUE THREAD

**Issue by bool3max** [kovidgoyal/kitty#3204]
I am unsure whether this is a bug or an unimpleneted feature, but regardless: 

* `kitty --version`:  `kitty 0.19.3`, on Linux

I'm using FontAwesome 5 Pro, and I have 3 appropriate OTF files installed on my system: 

* `Font Awesome 5 Pro-Light-300.otf`
* `Font Awesome 5 Pro-Regular-400.otf`
* `Font Awesome 5 Pro-Solid-900.otf`

If I run `kitty --debug-font-fallback`, and paste the following in to the newly-spawned terminal: 

`echo -e "X \e[1m X \e[2m X"` - where X represents the Unicode glyph `U+F126` (the git branch icon from FontAwesome), the following is printed: 

![image](https://user-images.githubusercontent.com/12991998/103459402-78b66680-4d0f-11eb-88e2-b41a2f603d3e.png)

The first two characters are what is expected, the first is a regular glyph printed before any ANSI escape codes are applied, the second is a bold version of that same glyph, however **the third is just the bold version, but with decreased opacity**, instead of an actual light version (escape code `\e[2m`).

It seems that kitty doesn't recognize that the third glyph exists in `Font Awesome 5 Pro-Light-300.otf` for some reason. 

This is confirmed by looking at the output of `--debug-font-fallback`. 

```
U+f126 Face(family=Font Awesome 5 Pro, style=Regular, ps_name=FontAwesome5Pro-Regular, path=/usr/share/fonts/OTF/Font Awesome 5 Pro-Regular-400.otf, index=0, is_scalable=True, has_color=False, ascender=448, descender=-64, height=558, underline_position=-50, underline_thickness=25, strikethrough_position=132, strikethrough_thickness=25)
U+f126 bold Face(family=Font Awesome 5 Pro, style=Solid, ps_name=FontAwesome5Pro-Solid, path=/usr/share/fonts/OTF/Font Awesome 5 Pro-Solid-900.otf, index=0, is_scalable=True, has_color=False, ascender=448, descender=-64, height=558, underline_position=-50, underline_thickness=25, strikethrough_position=132, strikethrough_thickness=25)
U+f126 bold Face(family=Font Awesome 5 Pro, style=Solid, ps_name=FontAwesome5Pro-Solid, path=/usr/share/fonts/OTF/Font Awesome 5 Pro-Solid-900.otf, index=0, is_scalable=True, has_color=False, ascender=448, descender=-64, height=558, underline_position=-50, underline_thickness=25, strikethrough_position=132, strikethrough_thickness=25)
```
Kitty correctly chooses `Font Awesome 5 Pro-Regular-400.otf` for the first glyph, `Font Awesome 5 Pro-Solid-900.otf` for the second (bolded, `\e[1m`) glyph, but **doesn't pick up the Light-300 version to use for the third glyph** and instead just remains using the bolded version, but with decreased opacity. 

--- 

I've tried looking at the documentation of `symbol_map` however I don't think that can solve this problem as all 3 glyphs are the same codepoint.

**Comment by kovidgoyal** [comment]
SGR 2 is implemented as dim not light in kitty. As such decreased
contrast is the desired behavior.

**Comment by bool3max** [comment]
Is there any other way to change to a lighter-weight font at runtime?

**Comment by kovidgoyal** [comment]
No, fonts are initialized once at startup. You can choose a lighter
weight in kitty.conf, but that's it.
