### ISSUE TITLE
not passing 256 or 24bit colors when using terminal-kit

### ISSUE THREAD

**Issue by zcaudate** [kovidgoyal/kitty#3205]
**Describe the bug**
I don't know if it's my config problem in  kitty but there is a test for colors in terminal-kit(a js lib) that works(256 colors) in Alacritty and Terminal.app but not kitty.

![Screen Shot 2021-01-03 at 1 39 41 pm](https://user-images.githubusercontent.com/1455572/103472501-5bde6980-4dc9-11eb-8f55-3e37bff707c6.png)

**To Reproduce**
```bash
git clone https://github.com/cronvel/terminal-kit.git
cd terminal-kit
npm install
# then
node sample/24bits-colors-test.js
node sample/256colors-test.js
```

**Expected behavior**

**Screenshots**

**Environment details**
OS: OSX

```
Output of kitty --debug-config
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by zcaudate** [comment]
running the 24-bit test gives this output:

<img width="543" alt="Screen Shot 2021-01-03 at 1 43 50 pm" src="https://user-images.githubusercontent.com/1455572/103472545-b8418900-4dc9-11eb-964a-887e9e5446d8.png">

**Comment by kovidgoyal** [comment]
That will be a bug in that library. It is probably hardocding terminal
names instead of querying terminfo as it should. Inform the library
author of the bug.

**Comment by zcaudate** [comment]
thanks for that.
