### ISSUE TITLE
Some Nerd glyphs are not rendered correctly by Starship prompt

### ISSUE THREAD

**Issue by mil-ad** [kovidgoyal/kitty#3207]
I'm using [starship](https://starship.rs/) for my shell prompt which includes some glyphs in directories that are git repos to give indication of their status. 

I'm not 100% sure if this is a bug in starship or kitty but some of the glyphs I've configured there don't show up in my prompt correctly. However, _sometimes_ when I paste them directly in in the shell they're rendered fine:

![image](https://user-images.githubusercontent.com/686449/103485209-a58c7b80-4dec-11eb-9d4f-7eca9aef22c5.png)

The half-rendered character on the left of the `?` is the rubbish bin icon from Nerd collection.

Does anyone know what the cause might be?

```
kitty 0.19.3 created by Kovid Goyal
Linux milad-ryzen 5.4.85-1-MANJARO #1 SMP PREEMPT Mon Dec 21 21:38:53 UTC 2020 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
Loaded config files: /home/milad/.config/kitty/kitty.conf
[003 17:52:45.917512] Ignoring unknown config key: Clipboard
Running under: X11

Config options different from defaults:
background           Color(red=33, green=34, blue=45)
background_opacity   0.9
color0               Color(red=29, green=32, blue=33)
color1               Color(red=204, green=36, blue=29)
color10              Color(red=184, green=187, blue=38)
color11              Color(red=250, green=189, blue=47)
color12              Color(red=153, green=198, blue=202)
color13              Color(red=211, green=134, blue=155)
color14              Color(red=126, green=193, blue=110)
color15              Color(red=235, green=219, blue=178)
color2               Color(red=152, green=151, blue=26)
color3               Color(red=215, green=153, blue=33)
color4               Color(red=69, green=133, blue=136)
color5               Color(red=177, green=98, blue=134)
color6               Color(red=104, green=157, blue=106)
color7               Color(red=168, green=153, blue=132)
color8               Color(red=146, green=131, blue=116)
color9               Color(red=244, green=44, blue=62)
font_family          Cascadia Code PL
foreground           Color(red=242, green=229, blue=188)
term                 xterm-256color
window_padding_width FloatEdges(left=5.0, top=2.5, right=5.0, bottom=2.5)
Added shortcuts:
	shift+down KeyAction(func='scroll_line_down', args=())
	shift+up KeyAction(func='scroll_line_up', args=())
	shift+page_up KeyAction(func='scroll_page_up', args=())
	shift+page_down KeyAction(func='scroll_page_down', args=())
	shift+home KeyAction(func='scroll_home', args=())
	shift+end KeyAction(func='scroll_end', args=())
	control+minus KeyAction(func='change_font_size', args=(True, '-', 2.0))
	control+0 KeyAction(func='change_font_size', args=(True, None, 0.0))
	control+equal KeyAction(func='change_font_size', args=(True, '+', 2.0))
	alt+c KeyAction(func='copy_to_clipboard', args=())
	alt+v KeyAction(func='paste_from_clipboard', args=())
```

**Comment by mil-ad** [comment]
Actually, I think my font may have not been as patched as I thought it was.

I replaced with [Nerd's version](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode) and the problem has gone away.

**Comment by kovidgoyal** [comment]
Just FYI, you dont need patched fonts in kitty. Install the actual nerd
font as a standalone and kitty should pick up the symbols automatically,
or you can help it do so with

# Rule for Nerd Fonts
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B Symbols-1000-em Nerd Font Complete

in kitty.conf

**Comment by mil-ad** [comment]
Ahh 🤯  That's fantastic. Thanks!
