### ISSUE TITLE
Underline is too high for some fonts.

### ISSUE THREAD

**Issue by nertpinx** [kovidgoyal/kitty#3208]
**Describe the bug**
Some fonts are underscored too closely (the line is thick and high). I wanted to go back to using Fantasque Sans Mono (looks like it does not matter whether it is the Nerd Font variant or not), but the line almost covers full stops for example. I was chasing few misleading paths and then found out that this happens in kitty only.

**Screenshots**
![kitty-underline](https://user-images.githubusercontent.com/670528/103493196-130dcb80-4e30-11eb-9771-14b3c38c321e.png)
In this picture the upper line is kitty and the lower one is gnome-terminal with settings matching as closely as possible.

Output of `kitty --debug-config`
```
kitty 0.19.3 created by Kovid Goyal
Linux carol 5.10.3-gentoo-x86_64 #1 SMP Tue Dec 29 20:27:17 CET 2020 x86_64
This is \n.\O (\s \m \r) \t
Loaded config files: /home/nert/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background                Color(red=0, green=43, blue=54)
close_on_child_death      True
color0                    Color(red=7, green=54, blue=66)
color1                    Color(red=220, green=50, blue=47)
color10                   Color(red=88, green=110, blue=117)
color11                   Color(red=101, green=123, blue=131)
color12                   Color(red=131, green=148, blue=150)
color13                   Color(red=108, green=113, blue=196)
color14                   Color(red=147, green=161, blue=161)
color15                   Color(red=253, green=246, blue=227)
color2                    Color(red=133, green=153, blue=0)
color3                    Color(red=181, green=137, blue=0)
color4                    Color(red=38, green=139, blue=210)
color5                    Color(red=211, green=54, blue=130)
color6                    Color(red=42, green=161, blue=152)
color7                    Color(red=238, green=232, blue=213)
color8                    Color(red=88, green=110, blue=117)
color9                    Color(red=203, green=75, blue=22)
cursor                    Color(red=131, green=148, blue=150)
cursor_blink_interval     0.0
disable_ligatures         2
enable_audio_bell         False
enabled_layouts           ['grid', 'fat', 'horizontal', 'splits', 'stack', 'tall', 'vertical']
focus_follows_mouse       True
font_size                 14.0
foreground                Color(red=131, green=148, blue=150)
scrollback_lines          10000
select_by_word_characters :@-./_~?&=%+#
```

**Additional context**
- This happens with `kitty --config NONE` as well.
- Also `adjust_line_height` does not fix this.
- Other fonts work fine, although I think I have seen at least one other with the same behaviour, however I cannot find that one now.

**Comment by kovidgoyal** [comment]
Underline size and positioning information comes from the font, via
FreeType. kitty does not change or control it (beyond adjusting it to make
sure it does not go out of the bottom of the cell). I dont know what
gnome-terminal is going, presumably it does not use the font's metrics
for underlines, which is a bug in it. Relevant code is cell_metrics() in
freetype.c
