### ISSUE TITLE
Can kitty @ ls' performance be improved?

### ISSUE THREAD

**Issue by resolritter** [kovidgoyal/kitty#3209]
**Is your feature request related to a problem? Please describe.**

`kitty @ ls` doesn't perform as well as I'd like.

Suppose there's a command which does something based on the current active window - for instance, execute some code based on the window id. Doing `kitty @ ls` alone takes usually takes this long:

```
> time kitty >/dev/null @ ls

real	0m0.077s
user 0m0.057s
sys	0m0.014s
```

Then it's possible to select the active window with `jq`, which doesn't seem to affect the timings noticeably

```
> time kitty @ ls | jq '.[0].tabs[] | select(.is_focused==true) | .windows[] | select(.is_focused==true).id'

real	0m0.079s
user 0m0.071s
sys	0m0.020s
```

I'd like to know if there're ideas on how to improve the performance for this API or if you'd recommend another API. I am looking forward to a solution which lets me query the state very fast (below 10ms) as this code I've mentioned is part of a shortcut. Otherwise, I'll defer to the solution described in the alternatives section; I have not yet done so because I think this is  the most "proper" API for querying this data.

https://github.com/kovidgoyal/kitty/blob/2762488c817526036e362257fbd0aa2cd0566726/kitty/boss.py#L218-L219

https://github.com/kovidgoyal/kitty/blob/2762488c817526036e362257fbd0aa2cd0566726/kitty/child.py#L54

**Describe the solution you'd like**

I would think this API could be faster. For comparison, `i3-msg -t get_tree` dumps way more data and is almost instant.

```
> time i3-msg -t get_tree >/dev/null

real	0m0.001s
user 0m0.001s
sys	0m0.000s
```

**Describe alternatives you've considered**

For keeping track of which window is active, I thought I could also use a [watcher](https://sw.kovidgoyal.net/kitty/remote-control.html?highlight=launch#cmdoption-kitty-launch-watcher) and write to a file whenever the active window changes, which then could be read from another process. I have not yet tried this for the reasons I've mentioned in the previous topics.

**Comment by kovidgoyal** [comment]
That's just python startup time. Write a native code client that speaks
the protocol and you will get ~10ms roundtrip times. the protocol is
documented here: https://sw.kovidgoyal.net/kitty/rc_protocol.html

**Comment by kovidgoyal** [comment]
And just for completeness, here you go:

Start kitty with
```sh
kitty -o allow_remote_control=yes --listen-on unix@test
```

Now get nice pretty printed @ ls output in under 10ms
```sh
echo -n '\x1bP@kitty-cmd{"cmd":"ls","version":[0,19,3]}\x1b\' | socat - abstract:test | tail -c +13 | jq -c '.data | fromjson' 2>/dev/null | jq .
```

**Comment by resolritter** [comment]
> And just for completeness, here you go:
> 
> Start kitty with
> 
> ```shell
> kitty -o allow_remote_control=yes --listen-on unix:@test
> ```
> 
> Now get nice pretty printed @ ls output in under 10ms
> 
> ```shell
> echo -n '\x1bP@kitty-cmd{"cmd":"ls","version":[0,19,3]}\x1b\' | socat - abstract:test | tail -c +13 | jq -c '.data | fromjson' 2>/dev/null | jq .
> ```

Thanks, I needed this. Had to make a few adjustments on my end

- Needed the `-e` flag for `echo`
- Needed to trim both the start of the end of the input; for this I used `awk '{ print substr($0, 13, length($0) - 14) }'`


Overall, the full command

```
> time echo -en '\x1bP@kitty-cmd{"cmd":"ls","version":[0,19,3]}\x1b\' \
 | socat - abstract:test \
 | awk '{ print substr($0, 13, length($0) - 14) }' \
 | jq '.data | fromjson | .[0].tabs[] | select(.is_focused==true) | .windows[] | select(.is_focused==true).id'
4

real	0m0.020s
user 0m0.023s
sys	0m0.001s
```

It's 10ms for the socket interaction and another 10~14ms for jq.

Thanks!
