### ISSUE TITLE
dead keys and AltGr (again?)

### ISSUE THREAD

**Issue by dagbdagb** [kovidgoyal/kitty#3210]
**Describe the bug**
I cannot get my keyboard to produce dead keys in kitty. Appears to work a-ok in geany and firefox. I understand gtk and glfw are different beasts, but I had the impression that this exact problem was fixed in a glfw fork?

**To Reproduce**
1. Install components as listed under Environment below.
2. Verify that geany and firefox both allows entering the character 'Ñ' by means of AltGr+tilda, N in sequence
3. kitty provides a plain 'N' with the same sequence

**Expected behavior**
I would expect different toolkits under wayland having the same interpretation of keyboard input in terms of displayed text.

**Screenshots**
Pressing Right Alt
Press xkb_keycode: 0x64 clean_sym: ISO_Level3_Shift composed_sym: ISO_Level3_Shift mods: none glfw_fallback_key: 346 (RIGHT ALT) xkb_key: 65514 (Alt_R)
on_key_input: glfw key: 346 native_code: 0xffea action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release xkb_keycode: 0x64 clean_sym: ISO_Level3_Shift mods: none glfw_fallback_key: 346 (RIGHT ALT) xkb_key: 65514 (Alt_R)
on_key_input: glfw key: 346 native_code: 0xffea action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events

Pressing the ^/~/[double dot on top of character]-key.  
Press xkb_keycode: 0x1b clean_sym: dead_diaeresis composed_sym: dead_diaeresis mods: none glfw_fallback_key: 93 (RIGHT_BRACKET) xkb_key: 93 (bracketright)
on_key_input: glfw key: 93 native_code: 0x5d action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release xkb_keycode: 0x1b clean_sym: dead_diaeresis mods: none glfw_fallback_key: 93 (RIGHT_BRACKET) xkb_key: 93 (bracketright)
on_key_input: glfw key: 93 native_code: 0x5d action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events

**Environment details**
OS: gentoo linux 
Wayland protocol libs 1.18.91
Wayland protocol files 1.20
Wayfire 0.6.0
Libinput 1.16.4
Kitty 0.19.2

Wayfire keyboard config items:
xkb_layout = no
xkb_model = pc105
xkb_options = 
xkb_rules = evdev
xkb_variant = 
```
kitty 0.19.2 created by Kovid Goyal
Linux myhost 5.10.4-gentoo #11 SMP Sun Jan 3 20:01:22 CET 2021 x86_64
This is \n.\O (\s \m \r) \t
Loaded config files: /home/dagb/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
focus_follows_mouse True
```

**Additional context**
"Try to reproduce the problem with `kitty --config NONE` "
Same result. 

Characters not requiring a dead key is represented ok in kitty. ßð€® etc.

**Comment by dagbdagb** [comment]
Some fiddling with locales appears to fix this.
For the benefit of the ones following in my path:

1. ensure that your local locale is built. 
  a. Edit /etc/locale.gen to contain at least:
  C.UTF8 UTF-8
  nb_NO.UTF8 UTF-8

  b. run locale-gen

2. set LANG and LC_ALL (or a useful subset) to the right locale. In my case nb_NO.utf8.

The labyrinth of logic and aliases for locales is another topic. Likewise the spelling of UTF-8, UTF8, utf8.

**Comment by kovidgoyal** [comment]
geany and firefox are probably running under xwayland. Run kitty as

kitty -o linux_display_server=x11

nd see if your dead keys are working. And yes dead keys or ore correctly
compose keys work fine in kitty.

**Comment by dagbdagb** [comment]
both geany and firefox running under wayland, not xwayland. Or so xeyes will have me believe. There *is* a difference in the handling of locales between gtk and glfw. 
Got it working now, but discovered issues when connecting to another machine via ssh. All national characters are scrubbed from the terminal window. I.e. replaced with the empty string. Weird. Will try to find a combination of settings which works.

I so do hate locales, keyboards and utf8....
