### ISSUE TITLE
MacOS: Terminal Cursour doesn't respect the prompt.

### ISSUE THREAD

**Issue by notaduck** [kovidgoyal/kitty#3212]
**Describe the bug**
THe terminal cursour doesn't respect the prompt.

**To Reproduce**
Start kitty, presss enter.

**Expected behavior**
The terminal cursour should be right of `src` in my example.

**Screenshots**
<img width="395" alt="Screenshot 2021-01-05 at 08 34 54" src="https://user-images.githubusercontent.com/9454064/103618913-1177fc80-4f31-11eb-975c-abb7070232c1.png">

**Environment details**
MacOs BigSur 11.1

```
Darwin Daniels-MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.1 BuildVersion:	20C69

Config options different from defaults
```

**Additional context**
The config is default and `kitty --config NONE` doesn't do anything for me, as expected :)

**Comment by kovidgoyal** [comment]
You are probably using some cursor save/restore codes in your PS1/prompt render functions incorrectly. Fix it and you will be fine.

**Comment by notaduck** [comment]
> You are probably using some cursor save/restore codes in your PS1/prompt render functions incorrectly. Fix it and you will be fine.

I think I forgot to say that I use ZSH whit a standard theme!

```
PROMPT='%{$fg[magenta]%}[%c] %{$reset_color%}'

RPROMPT='%{$fg[magenta]%}$(git_prompt_info)%{$reset_color%} $(git_prompt_status)%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX=""
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY=""
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_GIT_PROMPT_ADDED="%{$fg[cyan]%} ‚úà"
ZSH_THEME_GIT_PROMPT_MODIFIED="%{$fg[yellow]%} ‚ú≠"
ZSH_THEME_GIT_PROMPT_DELETED="%{$fg[red]%} ‚úó"
ZSH_THEME_GIT_PROMPT_RENAMED="%{$fg[blue]%} ‚û¶"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[magenta]%} ‚úÇ"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[grey]%} ‚ú±"

```

So the chance is that anybody else will run into this issue is probably high.

**Comment by kovidgoyal** [comment]
Sorry, I cannot reproduce with
```
PROMPT='%{$fg[magenta]%}[%c] %{$reset_color%}'
```

Look deeper. And there is nothing standard about your config. All those git_prompt* functions are probably the culprit.
