### ISSUE TITLE
Trigger keyboard maps even if a window isn't open.

### ISSUE THREAD

**Issue by tammersaleh** [kovidgoyal/kitty#3213]
I'm not sure if this is a bug or feature, but I'd like to be able to trigger `map`'s when Kitty is running, but no window is open.  This is on MacOS, where it's common to have applications running without any windows open.

I have these in my `~/.config/kitty/kitty.conf`:

```
kitty_mod cmd
map kitty_mod+t new_tab
map kitty_mod+r launch --type=tab ssh -t ...
```

These work great when there's an existing window, but if I close all windows without quitting Kitty, then they no longer work.  Typing them triggers the MacOS error bell sound.  I have to instead open a local window (via `⌘-n`), and _then_ type `⌘-t` or `⌘-r` to trigger these `map`'s.

I'd like the `map`'s to trigger even if a window isn't open.

**Comment by kovidgoyal** [comment]
Without a window, key events dont get delivered to applications by macOS, so such maps are never going to work. The best that can be done is defining menu entries for the menubar, and given that this would require macOS specific config, it's not something I am interested in, but patches are welcome.

**Comment by tammersaleh** [comment]
ah, didn't realize that's how MacOS works.  Makes sense.
