### ISSUE TITLE
Backspacing some specific character will lead to prompt deletion

### ISSUE THREAD

**Issue by 1tszyau** [kovidgoyal/kitty#3214]
Typing character like 'ø', 'π', or any character that inputs by pressing OPTION + any character key, then backspacing them will lead to prompt deletion.

1. Open kitty
2. Type øøøø (by pressing option + o)
3. Hold 'delete' key
4. You will see the prompt get deleted

MacOS Terminal after backspacing those special character
<img width="682" alt="image" src="https://user-images.githubusercontent.com/58001628/103722104-34c2aa80-500a-11eb-91db-07fbb666a8c9.png">

Kitty Terminal after backspacing those special character
<img width="752" alt="image" src="https://user-images.githubusercontent.com/58001628/103722178-5e7bd180-500a-11eb-9267-eb8e1865ab1f.png">

I am running Kitty 0.19.3 on MacOS 11.1

**Comment by kovidgoyal** [comment]
Works fine for me on macOS with zsh 5.8. This will be caused by a bug in
your shell using incorrect width values for those characters, or your
LANG/locale being incorrect.
