### ISSUE TITLE
Opening a new window creates multiple shell prompts in the previous windows

### ISSUE THREAD

**Issue by kingedward35** [kovidgoyal/kitty#3215]
**Describe the bug**
If inside a tab and your press cmd+enter on MacOs, a new window will open, but the previous window now has multiple shell prompts inside of it.

**To Reproduce**
1. Open up a kitty instance
2. Press cmd+enter
3. See error

**Expected behavior**
The previous windows shell prompts should look no different than before the new window was opened

**Screenshots**
![image](https://user-images.githubusercontent.com/12418717/103723779-0ef8bf80-4f90-11eb-8821-b55ffb116fd6.png)

**Environment details**
OS: MacOs Catalina

```
Output of kitty --debug-config
kitty 0.19.2 created by Kovid Goyal
Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.5 BuildVersion:	19F101
Loaded config files: /Users/verlonsmith/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color  Color(red=11, green=175, blue=255)
bold_font            JetBrainsMono Nerd Font Bold
bold_italic_font     JetBrainsMono Nerd Font Bold Italic
font_family          JetBrainsMono Nerd Font Bold
font_size            17.0
italic_font          JetBrainsMono Nerd Font Italic
tab_bar_edge         1
tab_bar_style        powerline
window_margin_width  FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
window_padding_width FloatEdges(left=6.0, top=6.0, right=6.0, bottom=6.0)
Added shortcuts:
	super+d KeyAction(func='combine', args=(KeyAction(func='new_window', args=()), KeyAction(func='next_layout', args=())))
	super+left_bracket KeyAction(func='previous_window', args=())
	super+right_bracket KeyAction(func='next_window', args=())
Changed shortcuts:
	super+w KeyAction(func='close_window', args=())
```

**Additional context**
- Tried the `kitty --config NONE` command and still got the same result.

Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
This is a limitation of how shells work. When resizing windows,
depending on how complex your shell prompt is and at what speed your
sheel and terminal redraw things, you will get multiple prompts.
