### ISSUE TITLE
ctrl + shift + click doesn't open in the correct browser

### ISSUE THREAD

**Issue by Ulrar** [kovidgoyal/kitty#322]
Hi,

For some reason the wrong browser is used, not sure how kitty determines what browser to use but it'd be great to have a config option for that.

Also, a hint mode to open links without having to use the mouse (something like qutebrowser / vimperator ..) would be awesome. EDIT: Just saw that termite seems to have that, could be a good example

**Comment by SolitudeSF** [comment]
`open_url_with default` option in config

**Comment by Ulrar** [comment]
Oh yeah, missed that one, sorry. I searched for link, click and things like that, didn't think about url.

Still, a hint mode would be a great addition

**Comment by kovidgoyal** [comment]
Co-incidentally, a URL hint mode is next on my TODO list using the new overlay window facility, after I finish the unicode input facility.

**Comment by kovidgoyal** [comment]
URL hints now implemented in master. (ctrl+shift+e)
