### ISSUE TITLE
Confirmation of font issue

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#3220]
**Describe the bug**
`( ͡° ͜ʖ ͡°)` doesn't display properly. The arches (which I think come from music notation) for the eyebrows and mouth do not display but they do seem to affect the spacing of the other characters.

This is a rather silly kaomoji I saw on IRC and it made me wonder if these glyphs violate kitty's monospace constraints? Since they do seem to affect spacing I'm not sure. I don't really expect a fix but am hoping for a way to identify similar problematic characters and if there's a way to find a font that doesn't have these issues.

**To Reproduce**
1. Input `( ͡° ͜ʖ ͡°)` on the command line or have it output by any program (like an irc client).
2. The arches that represent "lenny"'s eyebrows and mouth aren't rendered but the spacing does seem to be affected.

**Expected behavior**
Ideally all symbols are rendered.

**Screenshots**
In weechat in kitty: ![Lenny face in kitty](https://user-images.githubusercontent.com/1486805/103813662-c3faad00-5060-11eb-906c-f7540ea35fba.png)
In weechat in alacritty (using a different font): ![Lenny face in alacritty](https://user-images.githubusercontent.com/1486805/103815751-1db0a680-5064-11eb-8cb3-6046b7757cdc.png)

**Environment details**
OS: ```
uname -mpv
Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64 i386
```

```
Output of kitty --debug-config
kitty 0.19.2 created by Kovid Goyal
Darwin terra 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.13.6 BuildVersion:	17G14042
Loaded config files: /Users/toonn/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity                 0.55
bold_font                          DejaVu Sans Mono Bold
bold_italic_font                   DejaVu Sans Mono Bold Oblique
color0                             Color(red=64, green=64, blue=64)
color1                             Color(red=183, green=87, blue=87)
color10                            Color(red=173, green=206, blue=141)
color11                            Color(red=206, green=206, blue=141)
color12                            Color(red=141, green=163, blue=206)
color13                            Color(red=206, green=141, blue=206)
color14                            Color(red=141, green=206, blue=206)
color2                             Color(red=135, green=183, blue=87)
color3                             Color(red=183, green=183, blue=87)
color4                             Color(red=87, green=119, blue=183)
color5                             Color(red=183, green=87, blue=183)
color6                             Color(red=87, green=183, blue=183)
color8                             Color(red=102, green=102, blue=102)
color9                             Color(red=206, green=141, blue=141)
font_family                        DejaVu Sans Mono Book
font_size                          12.0
initial_window_height              (347, 'px')
initial_window_width               (647, 'px')
italic_font                        DejaVu Sans Mono Oblique
macos_option_as_alt                3
macos_quit_when_last_window_closed True
remember_window_size               False
Added shortcuts:
	 shift+control+p > period KeyAction(func='kitten', args=['hints', '--hints-offset=0 --type path --program @'])
Changed shortcuts:
	 shift+control+e KeyAction(func='kitten', args=['hints', '--hints-offset=0'])
	 shift+control+o KeyAction(func='kitten', args=['hints', '--hints-offset=0 --program @'])
	 shift+control+p > f KeyAction(func='kitten', args=['hints', '--hints-offset=0 --type path --program -'])
	 shift+control+p > h KeyAction(func='kitten', args=['hints', "--hints-offset=0 --type regex --regex '(?m)\\b([0-9a-zA-Z]{7,64}|[0-9a-df-np-sv-z]{7,52})\\b' --program @"])
	 shift+control+p > l KeyAction(func='kitten', args=['hints', '--hints-offset=0 --type line --program -'])
	 shift+control+p > w KeyAction(func='kitten', args=['hints', '--hints-offset=0 --type word --program -'])
	 shift+control+p > shift+f KeyAction(func='kitten', args=['hints', '--hints-offset=0 --type path'])

```

**Additional context**
This reproduces with `kitty --config NONE` which means the default font also has this issue I believe.

**Comment by kovidgoyal** [comment]
Yes, these glyphs are never going to render properly given kitty's cell
based rendering model. Multi-cell combining glyphs are not possible
given the way kitty works.

**Comment by toonn** [comment]
And this is specific to multi-cell combining marks? Or does it apply to combining diacritical marks like accents as well?

**Comment by kovidgoyal** [comment]
multi-cell
