### ISSUE TITLE
kitty_prefix instead of kitty_mod for default mappings

### ISSUE THREAD

**Issue by ixil** [kovidgoyal/kitty#3222]
I would like to be able to define/map something like a `kitty_prefix` in the same vein as `kitty_mod` except it may be a full key sequence.

e.g.
   I wanted to define something like `kitty_prefix ctrl+b` so then I can define all my shortcuts in terms of `map kitty_prefix>c new_window`

At the moment `kitty_mod` fills a similar role, but can only use modifier keys. 
It would be an expansion term, but with some special handling of if the map/definition the following `>` or `+`

e.g.
```
# Is this ill formed? (I would say yes)
kitty_prefix ctrl+b>
map kitty_prefix>c new_window
# what happens if +
map kitty_prefix+c new_window
``` 

I wanted this to ease transitioning from tmux, where I used `ctrl+b` and other users `ctrl+a` as a prefix. Also when going between keyboard layouts on different machines then you could just change the prefix key which avoids accidental triggering within various terminal programs

**Comment by kovidgoyal** [comment]
I'm afraid I dont much see the point of this. Why would you want to press two keys instead of one for the shortcuts? For certain types of shortcuts, such as the ones for the hints kitten, using a multi-key shortcut makes sense, since you trigger the hints kitten with the first key which acts as a leader and select the mode of hint selection with the second key. 

And if you really want to do this, you can simply redefine all the shortcuts you want to use using a multi-key scheme to suit yourself.

**Comment by ixil** [comment]
I'm proposing that both are supported, e.g. you set
`kitty_prefix` to `ctrl+shift` and you have the current behavior, or you set it to `ctrl+b+` or `ctrl+b>`.
But I agree, it's simply a matter of redefining the existing shortcuts.

Since the issue I found `--debug-config` so now I can easily copy all the bindings to actually modify! I think this can be closed. 
It might be worthwhile explicitly adding a note about `kitty_mod` only taking modifiers (it's in the name, but coming from tmux I was confused until I ran debug-config).

---

Tangentially:
I looked briefly into how I might be able to output all the existing bindings, Does a kitty that finds  `Boss`'s `opts.keymap` the right direction?

**Comment by kovidgoyal** [comment]
I assume you mean a kitten to output keybindings. You dont need boss for
that. Indeed a kitten has no access to boss while it is running in main,
since that is a separate process. You can get the keymap object as is
donein kitty/main.py line 330 onwards.
