### ISSUE TITLE
Functionality of kitty send-text

### ISSUE THREAD

**Issue by JanosSarkoezi** [kovidgoyal/kitty#3227]
**Describe the bug**
I want to use vim-slime to play with REPL. At first vim-slimes Ctrl+C Ctrl+C doesn't sems to work. Some investigation in vim-slime plugin leads to use kittys send-text
```
kitty @ send-text --match id:2 --from-file /tmp/test.txt
```
If I try this on my kitty with $KITTY_WINDOW_ID = 1 nothing happened on $KITTY_WINDOW_ID = 2.

**To Reproduce**
1. Create a kitty terminal
2. Open a new Window with Ctrl+Shift+Enter
3. Call 'kitty @ send-text --match id:2 --from-file /tmp/test.txt' in Window with ID = 1
4. nothing happens in Window with ID = 2

**Expected behavior**
The content of the file /tmp/test.txt should pass to Window with ID = 2

**Environment details**
```
kitty 0.19.3 (3ce04c3e4b) created by Kovid Goyal
Linux saj-MS-7758 4.15.0-129-generic #132-Ubuntu SMP Thu Dec 10 14:02:26 UTC 2020 x86_64
Ubuntu 18.04.5 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
Loaded config files: /home/saj/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
enable_audio_bell False
font_size         12.0
scrollback_pager  ['nvim', '-c', 'autocmd TermOpen * normal G', '-c', 'silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - ']
Added shortcuts:
	shift+control+plus KeyAction(func='change_font_size', args=(True, '+', 0.5))
Changed shortcuts:
	shift+control+minus KeyAction(func='change_font_size', args=(True, '-', 0.5))
	shift+control+0 KeyAction(func='change_font_size', args=(True, None, 0.0))
```

**Additional context**
Did I something wrong or is this an issue?

**Comment by kovidgoyal** [comment]
Works fine for me. Remember to set allow_remote_control in kitty.conf

**Comment by JanosSarkoezi** [comment]
Thank you for your prompt reply. I turned the property on

```
...
Config options different from defaults:
allow_remote_control y
...
```

But if I try kitty with vim-slime, nothing has happened. I thought I'd do some little tests:

1. Call :echo system("ls") from vim. Works.
2. Call :echo system("kitty") from vim. Works.
3. Call :echo system("kitty @ send-text --match id:2 --from-file /home/saj/.slime_paste") from vim. Does not work.

I get an error:

```
Traceback (most recent call last):
  File "runpy.py", line 282, in run_path
  File "runpy.py", line 87, in _run_code
  File "__main__.py", line 127, in <module>
  File "__main__.py", line 123, in main
  File "__main__.py", line 23, in remote_control
  File "kitty/remote_control.py", line 188, in main
  File "kitty/remote_control.py", line 132, in do_io
  File "kitty/utils.py", line 429, in __enter__
OSError: Failed to open controlling terminal: /dev/tty (identified with ctermid()) with error: No such device or address
```

Please help.

**Comment by kovidgoyal** [comment]
you are using nvim, read the vim-slime docs, or see https://github.com/jpalardy/vim-slime/issues/234
