### ISSUE TITLE
System Day/Night mode support

### ISSUE THREAD

**Issue by dcow** [kovidgoyal/kitty#3228]
**Is your feature request related to a problem? Please describe.**
Many applications support setting the color scheme automatically based on the system light or dark mode. For example, vscode allows you to register a day and night color scheme.

**Describe the solution you'd like**
I'd like to be able to have a specific config file executed and applied depending on the system light or dark setting (especially relevant on macOS). For example, I'd like to set a dark color scheme at night and while I use a light color scheme during the day. I'd like kitty to evaluate the config and update or redraw the terminal while a session is running as the system shifts between color modes. That way the kitty windows stay up-to-date with the system as time progresses.

**Describe alternatives you've considered**
It seems the cleanest to simply be able to point kitty at a config file that should be included with the main config for day mode and and alternate file to be included for night mode. Within that file can be color commands but also any other config that the user may want to change between day and night. I haven't given much thought to an alternative. If there was a generic tool that could listen to the system day/night mode and then tell kitty to reload config or restart kitty as the transition happened I guess that could work, but sounds rather complicated to setup.

**Comment by kovidgoyal** [comment]
I'm afraid I dont have any interest in implementing this, as it is macOS
specific. That said, you can trivially implement it for yourself using a
script/key binding as described here:
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by dcow** [comment]
@kovidgoyal there are many other macOS-specific options in the config, though. And I don't believe it is entirely macOS specific. Ubuntu has light, standard, and dark modes. There's even an automation package that switches the theme across day/night cycles. I suspect it won't be long before linux adds more "official" support. And while it may be "trivial" to implement via a script (although this would have to be a daemon that listens to the events and then bumps kitty) it certainly would be a nicer UX if kitty supported it natively.

Would you be open to a PR adding support for this feature if someone else did the work? Or do you not wish to see such functionality land in `kitty` period?

**Comment by kovidgoyal** [comment]
On Tue, Jan 12, 2021 at 01:45:35PM -0800, David wrote:
> @kovidgoyal there are many other macOS-specific options in the config, though. And I don't believe it is entirely macOS specific. Ubuntu has light, standard, and dark modes. There's even an automation package that switches the theme across day/night cycles. I suspect it won't be long before linux adds more "official" support. 

That's extremely optimistic, to put it lightly. Linux gets "official"
things at the rate of about one a decade.


> And while it may be "trivial" to implement via a script (although this would have to be a daemon that listens to the events and then bumps kitty) it certainly would be a nicer UX if kitty supported it natively.
> 
> Would you be open to a PR adding support for this feature if someone else did the work? Or do you not wish to see such functionality land in `kitty` period?

Sure, but it needs to be behind an option defaulting to off. Many
terminal programs are not designed to cope well with colors being
switched out from under them on the fly.

**Comment by jian-lin** [comment]
> I'm afraid I dont have any interest in implementing this, as it is macOS specific.

FYI, light/dark mode has been standardized in xdg-desktop-portal as [org.freedesktop.appearance color-scheme][1], which is added in this [pr][2]. [GNOME42][3] and [KDE][4] has implemented this.

Basically, you can query current system's color scheme and get signals when it changes through d-bus.

[1]: https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings
[2]: https://github.com/flatpak/xdg-desktop-portal/pull/633
[3]: https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
[4]: https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/52

**Comment by jian-lin** [comment]
In some systems like NixOS, `~/.config/kitty/kitty.conf` is readonly, which makes `kitty +kitten themes` fail to change themes at runtime. Currently, the only way to do so is to use [OSC terminal escape codes](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) I guess.

Providing this feature will be a big improvement of UX.

**Comment by page-down** [comment]
@jian-lin

The relevant code is already there.
https://github.com/kovidgoyal/kitty/commit/c2bc24de35873f143c00523d51fbc5fa2ad9779f

Someone needs to implement the macOS part, plug in the linux part, design a way to specify the options in the configuration file, and add an option to enable the feature.

**Comment by kovidgoyal** [comment]
not to mention that if kitty.conf is read-only (which is rather strange, but different strokes for different folks), you can still use th einclude directove in it to load anther non-readonly config file. Or maybe NixOS wants you to have your entire computer readonly :)) Or you can use

kitty @ set-colors 

to change colors, no need for escape codes. As documented in  the FAQ https://sw.kovidgoyal.net/kitty/faq/#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by theotheroracle** [comment]
would it be possible to just set colors with a preference like 
`foreground_light #ffffff` 
for example, which would change when it receives the dbus message ?

**Comment by h-jia** [comment]
[Toggle Theme.zip](https://github.com/kovidgoyal/kitty/files/13237885/Toggle.Theme.zip)
I made this alfred workflow for those who want this feature.
