### ISSUE TITLE
Open a new tab in the same working directory by default (potentially as an option)

### ISSUE THREAD

**Issue by NiavlysB** [kovidgoyal/kitty#3229]
**Problem**
I'm always frustrated when I’m working in some directory, I open a new tab and that new tab opens in `~` instead of the directory I was in, and I have to `cd` back to the right directory. Pretty much every single time I open a new tab, it’s because I just ran a command that stays active, and I need to do something else in the same directory.

Even if the opposite behavior might be desirable sometimes, it’s much easier to have the default be to stay in the same directory, and you just type `cd` if needed, to get back to `~`.

**Solution**
When a new tab is opened, the working directory is set to whatever was the working directory in the previously active tab.

Alternatively, keep the current behavior and implement the behavior described above as a configuration option.

**Comment by kovidgoyal** [comment]
map ctrl+tab new_tab_with_cwd

**Comment by NiavlysB** [comment]
Awesome thank you!
