### ISSUE TITLE
Setting the edge color.

### ISSUE THREAD

**Issue by blueForestIcarus** [kovidgoyal/kitty#323]
It seems that the edge color is determined at startup by the background color, but changing the background color with an ASCII escape code does not change the edge color.
`printf '\033]11;rgb:ff/00/00\007'`
results in 
![2018-02-12t08 27 27](https://user-images.githubusercontent.com/6549542/36098876-a08c888c-0fce-11e8-9808-90f06253823d.png)

In urxvt this problem is solved by allowing the edge color to be set as color 708.
`printf '\033]708;rgb:ff/00/00\007'`

If there isn't a way to do this that I am not seeing, then I suggest a similar solution and as well as a separate config option for the edge color.

**Comment by kovidgoyal** [comment]
While I can somewhat see the use of a config option for edge color, I dont see how make it dynamic would work. Remember that kitty can display more than one window/tab in a single top-level window. So which window would it take the dynamically set color from? Once could imagine that it takes the color from the currently focused window, but it would look very odd in the case of more than one window being displayed and all windows not having the same dynamic color set. 

And even for a config option, why would you ever set it to anything other than the background color?

**Comment by blueForestIcarus** [comment]
I have different color schemes for different terminal tasks/programs (top, vim, bash, etc.) and changing the color scheme is accomplished through ASCII escape codes. As for the separate windows, you could have just one edge color and the ASCII escape in either one changes it. It is true that it wouldn't make much sense when using windows, but many people don't use their terminal's tab/window feature and instead rely on the window manager or a tmux like program for that functionality.

Having a different color scheme for terminal and vim is fairly common, I would expect this would be useful to other people as well. In fact I notice this problem in some of the vim screenshots in other issues, but they seem to be concerned with a different issue.

If you will consider accepting a pull request for this functionality then I will see if I can implement it.

**Comment by kovidgoyal** [comment]
I'm curious, how would this feature work with tmux? tmux will face exactly the same issue I described before. Different windows could have different background colors. So the border between them can match only one of the two windows. I just tried, it and that is indeed the case. The border between a window with black background and red background has a black background in tmux.

Also why use a separate escape code for it? Why not just use the dynamically set background color? I'd be willing to accept a PR that had the following behaviors:

1) If one window is currently visible (if only one window exists in the top-level OSWindow, or if we are using a layout such as Stack in the current tab), use its dynamically defined background color
2) If more than one window is visible, use the default background color

To implement this you would need to modify prepare_to_render_os_window() in child-monitor.c to return the current background color of the active window and if there is more than one visible window or not. Then use that information in draw_borders()

**Comment by blueForestIcarus** [comment]
I have implemented the functionality, but you seem to have a bug in your code and so I cannot tell if my stuff is working properly. 

How to reproduce:
1. Build and run your most recent commit
2. open a new window with ctrl+shft+enter
3. switch back to original window with ctrl+shift+[
4. close original window with ctrl+shift+w
5. the terminal does not update properly and the both windows remain visible

**Comment by kovidgoyal** [comment]
Fixed by: https://github.com/kovidgoyal/kitty/commit/0bb8ec61e57232f4cab988a09fc582aa0b7923f2

**Comment by blueForestIcarus** [comment]
I built and ran your code in the bg branch and it seems that it isn't quite working. Only the "Outer borders" were changing. However, If I resize the window the edges change as well.
Before Resizing:
![2018-02-16t11 49 45](https://user-images.githubusercontent.com/6549542/36319441-efc2fc8e-1310-11e8-8a3d-660f34296430.png)

After Resizing:
![2018-02-16t11 50 16](https://user-images.githubusercontent.com/6549542/36319426-e84b0172-1310-11e8-87d3-c56262e40eba.png)

**Comment by kovidgoyal** [comment]
It just needs a hook to relaying borders on bg color change I'll add it when I return

**Comment by sergei-dyshel** [comment]
Just tried `bg` and it works for me! (using i3-gaps with compton).
