### ISSUE TITLE
Prevent closing OS window (or tab, or kitty window?) if there’s is a program currently running

### ISSUE THREAD

**Issue by NiavlysB** [kovidgoyal/kitty#3230]
**Is your feature request related to a problem? Please describe.**
I’m used to having lots of open terminal windows, and I often need to close the ones I don’t need anymore. More often than not, I hit Alt-F4 by mistake on a kitty window where I still had a program running.

**Describe the solution you'd like**
When closing a kitty terminal (OS window), warn the user if there is a program currently running in the shell (in any of the tabs/windows in that OS window), before actually closing the window. 

Alternatively, keep the default behavior and offer this behavior as an option.

**Screenshots**
`gnome-terminal` does this via a GTK dialog box (example in French):
![image](https://user-images.githubusercontent.com/3757523/104121460-ac604480-533e-11eb-9993-07464fbb87e1.png)
But I guess here in `kitty` it would be something inside the window like the "change title" prompt:
![image](https://user-images.githubusercontent.com/3757523/104121576-a28b1100-533f-11eb-8a0d-fdb34b782697.png)

**Comment by kovidgoyal** [comment]
There is already such an option. Please read: https://sw.kovidgoyal.net/kitty/conf.html

**Comment by NiavlysB** [comment]
Ok nice, sorry! I actually spent some time in that page and I reread it just now, but I can’t find anything related to that issue, to be honest.

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close.

**Comment by NiavlysB** [comment]
> See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close.

Thanks for pointing me there, but I don’t see this command taking into account the fact that a command is currently running or not…

(And I’m not even able to make it work, with `confirm_os_window_close 1` in my `kitty.conf`, whether I have a command currently running or not, whether I have one or several open tabs or windows or OS windows.)

**Comment by kovidgoyal** [comment]
works fine for me, and there is no concept of "command running" in a
terminal emulator. A terminal emulator typically executes a long lived
shell process, which in turn runs short lives programs, that user often
call "commands".

kitty -o confirm_os_window_close=1

Press, ctrl+shift+q to close the tab and you will be asked if you are
sure or not.

**Comment by NiavlysB** [comment]
> works fine for me, and there is no concept of "command running" in a
> terminal emulator. A terminal emulator typically executes a long lived
> shell process, which in turn runs short lives programs, that user often
> call "commands".

Yes that’s why I wrote “if there is a program currently running in the shell” (in the description). I imagined it wasn’t so easy for the terminal to know if the shell is currently running a program or not. Still, other terminal emulators do it, so it must be doable, but maybe it would imply changing the architecture too much, I can understand that. 
 
> kitty -o confirm_os_window_close=1
> 
> Press, ctrl+shift+q to close the tab and you will be asked if you are
> sure or not.

~~Now this simply does not work on my machine~~
Ok I got it, I’m just running an out-of-date version (0.15).
