### ISSUE TITLE
Unmapping crtl+shift+r still blocks the renaming feature in nnn

### ISSUE THREAD

**Issue by p-mng** [kovidgoyal/kitty#3236]
**Describe the bug**
Some default keybindings like `ctrl+shift+r` conflict with other tools like the nnn file manager. Both the `map ctrl+shift+r ""` and `map ctrl+shift+r no_op` config options seem to still intercept the keycombo and thus block the nnn rename feature. `unmap` does not seem to be a thing. The same keycombo works just fine in alacritty.

**To Reproduce**
1. Use kitty (with the config options above) and alacritty with the default config
2. Use nnn
3. Press crtl+shift+r in both terminals

**Expected behavior**
Renaming works when ctrl+shift+r is pressed.

**Screenshots**
–

**Environment details**
Arch Linux (`Linux 5.10.6-110-tkg-pds`) + i3-gaps, `kitty 0.19.3 created by Kovid Goyal`

Output of `kitty --debug-config`
``` Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/patrick/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background                 Color(red=15, green=15, blue=15)
background_opacity         0.95
cursor_stop_blinking_after 0
disable_ligatures          2
font_family                Iosevka Medium Extended
foreground                 Color(red=250, green=250, blue=250)
mouse_hide_wait            0.0
Removed shortcuts:
	shift+control+r KeyAction(func='start_resizing_window', args=())
```

**Additional context**
`kitty --config NONE` just opens the resize dialog.

**Comment by kovidgoyal** [comment]
You cannot use ctrl+shift based bindings in terminal programs. THey are
not encodable using the traditional key encoding used in terminal
programs. Some terminals will produce the same bytes as for ctrl+letter
some, like kitty will produce nothing. You need to remap ctrl+r and use
that instead.
