### ISSUE TITLE
Add support for aarch64e (Apple Silicon)

### ISSUE THREAD

**Issue by dcow** [kovidgoyal/kitty#3238]
**Is your feature request related to a problem? Please describe.**
Kitty does not run natively on Apple Silicon machines. Kitty has to be executed in the translation environment `rosetta2` which makes kitty slower than need be. It also causes all the programs kitty launches to be the x86_64 variants rather than native aarch64e.

**Describe the solution you'd like**
Add support for `aarch64e` in the form of a universal ("fat") binary in the macOS release. Or, provide an alternate version that can be downloaded independently if the bloat of a universal binary is undesirable. 

**Describe alternatives you've considered**
The alternative is not supporting the M1 processor, which is not really an option for macOS software moving forward.

**Comment by kovidgoyal** [comment]
Build kitty from source and you will get native binaries. As for
pre-built ones, its on my todo list.

**Comment by hedefalk** [comment]
>Build kitty from source and you will get native binaries.

I'm trying to build from the provided nix-shell - maybe that's a bad idea in this case?

```
>nix-shell 
>make app  
>open kitty.app
```

Still no cigarr:

![image](https://user-images.githubusercontent.com/116520/110097006-d82c0380-7d9e-11eb-99b3-15002604dbf6.png)

Is it nix-shell that messes it up for me? I'd guess so:

```
✗ arch -arm64e make app                                                               nix-shell
arch: posix_spawnp: make: Bad CPU type in executable
```

I really do not want to bloat my machine with globals like python and stuff though.

**Comment by Luflosi** [comment]
I think your version of nixpkgs also needs to also be built for Apple Silicon. Are other binaries you installed via nixpkgs built for Apple Silicon? Try executing `file ~/.nix-profile/bin/bash` if you have bash installed or choose a different binary, it should print the architecture. I have never installed nix on a Mac with Apple Silicon but https://gist.github.com/angerman/cbe02d814d81a8e4d4ced56b19046c19 may help.

**Comment by Luflosi** [comment]
https://github.com/NixOS/nixpkgs/issues/95903 may also contain useful information but I haven't read most of it.

**Comment by hedefalk** [comment]
@Luflosi Yeah, the problem is nix. The instructions you linked are the ones I've used and they're based on Rosetta2.

I've tried to read that nixpgs thread but its too much and all mixed up,.

So I guess my only option is to actually install all the compile deps into my mac globally. But I think I'll just wait instead for either Nix or Kitty instead.
