### ISSUE TITLE
Massive CPU Usage (probably from pre-made bin)

### ISSUE THREAD

**Issue by ThatOneCalculator** [kovidgoyal/kitty#3239]
**Describe the bug**
Kitty is randomly using 13% of my Ryzen 3800X with just 2 windows open, idle.

**To Reproduce**
1. Open Kitty
2. View proccesses

**Expected behavior**
To not eat up most of my CPU

**Screenshots**
![image](https://user-images.githubusercontent.com/44733677/104391085-ffc7c380-54f3-11eb-97a3-03c22ae5b640.png)

**Environment details**
OS: Arch x86_64
CPU: Ryzen 3800X
RAM: 32GB

```
kitty 0.19.3 created by Kovid Goyal
Linux sonoma 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/kainoa/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control y
background           Color(red=34, green=31, blue=31)
bold_font            FiraCodeNerdFontComplete-Bold
bold_italic_font     FiraCodeNerdFontComplete-MediumItalic
color0               Color(red=34, green=31, blue=31)
color1               Color(red=173, green=157, blue=156)
color10              Color(red=172, green=140, blue=127)
color11              Color(red=170, green=123, blue=103)
color12              Color(red=118, green=160, blue=164)
color13              Color(red=53, green=141, blue=169)
color14              Color(red=197, green=181, blue=190)
color15              Color(red=199, green=199, blue=199)
color2               Color(red=172, green=140, blue=127)
color3               Color(red=170, green=123, blue=103)
color4               Color(red=118, green=160, blue=164)
color5               Color(red=53, green=141, blue=169)
color6               Color(red=197, green=181, blue=190)
color7               Color(red=199, green=199, blue=199)
color8               Color(red=89, green=87, blue=87)
color9               Color(red=173, green=157, blue=156)
cursor               Color(red=199, green=199, blue=199)
enable_audio_bell    False
font_family          FiraCodeNerdFontComplete-Medium
font_size            12.0
foreground           Color(red=199, green=199, blue=199)
italic_font          FiraCodeNerdFontComplete-Italic
window_padding_width FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

`kitty --config NONE` uses about as much CPU than expected (1%).
https://hatebin.com/lqooglvbbp <-- my kitty.conf

**Comment by ThatOneCalculator** [comment]
Also, building from source from `yay -S kitty-git` seems to fix the issues. It seems to be a problem with the pre-compiled binary.

**Comment by kovidgoyal** [comment]
I cannot reproduce. kitty doesnt use any CPU at all while sitting idle,
once the cursor blinking times out. I suggest you use strace or perf or
similar tools to see what the CPU usage is coming from, almost certainly
it will be a driver/window manager issue.

**Comment by kovidgoyal** [comment]
Also why are you using either AUR or the binaries? Arch has a decent kitty package.

**Comment by kovidgoyal** [comment]
no followup

**Comment by ThatOneCalculator** [comment]
Sorry for the lack of response. Turns out for whatever reason my computer was blaming the CPU usage of DarkTable on Kitty. Weird.
