### ISSUE TITLE
iterm2 to kitty key mappings

### ISSUE THREAD

**Issue by arnm** [kovidgoyal/kitty#324]
In iterm2 I have `ctrl-;` mapped to the action `Send Escape Sequence` `Esc + [1;5c` (`ctrl-right`).

How would this be replicated using the `send_text` functionality in kitty?

**Comment by kovidgoyal** [comment]
Something like

```
map ctrl+; send_text all \x1b[1;5c
```

**Comment by arnm** [comment]
Thank you it was the following (casing matters):

`map ctrl+; send_text all \x1b[1;5C`
