### ISSUE TITLE
Kitty opens a full-screen window on start, despite previous window size

### ISSUE THREAD

**Issue by dlo** [kovidgoyal/kitty#325]
`remember_window_size` is set to `yes` in my kitty.conf.

```
remember_window_size   yes
```

**Comment by kovidgoyal** [comment]
I cannot reproduce with current master. IIRC there was a bug that caused kitty to use the window width for the height when saving/restoring window sizes. Update and you should be fine.

**Comment by dlo** [comment]
Sounds great, thanks!
