### ISSUE TITLE
strange behavior with U+00AD SOFT HYPHEN

### ISSUE THREAD

**Issue by dankamongmen** [kovidgoyal/kitty#3254]
I'm not certain that this is a bug, but it surprises me. If I enter 'a', followed by Ctrl+Shift+'u', and enter 0041 (for 'A'), the result is 'aA' with the cursor to the right of the 'A'. if i then enter 'b', the result is 'aAb', as I would expect.

If I instead enter 00AD (for "Soft hyphen"), the result is 'a', with the cursor to the right. if i then enter 'b', the result is 'b', with the 'a' no longer visible (the 'b' has taken its place). If I then press enter, I get:

```
[schwarzgerat](0) $ b
bash: ab: command not found
[schwarzgerat](127) $ 
```

https://www.unicode.org/L2/L2002/02279-muller.htm indicates that SOFT HYPHEN may or may not be rendered, so the lack of a glyph (despite `wcwidth()` returning 1) seems perfectly fine. I don't understand why the 'b' is placed atop the 'a', though, or really what's going on here at all.

If I'm just emitting the character, things work fine:

```
[schwarzgerat](0) $ printf 'a\x41b\n'
aAb
[schwarzgerat](0) $ printf 'a\xc2\xadb\n'
ab  <------------- soft hyphen not rendered, but totally legal
[schwarzgerat](0) $ printf 'a\xc2\xadb\n' | xxd
00000000: 61c2 ad62 0a                             a..b.  <------------------ good, faithful, valid
[schwarzgerat](0) $ printf 'a\xc2\xa3b\n'
a£b
[schwarzgerat](0) $ 
```

**To Reproduce**
1. enter a character
2. enter a soft hyphen via Ctrl+Shift+'u', AD (U+00AD)
3. enter another character
4. first character is overwritten

**Expected behavior**
The first character ought remain visible. The soft hyphen ought or ought not be rendered. The third character ought appear to its right. The cursor ought appear to the right of both characters.

**Screenshots**

**Environment details**
OS: Debian Unstable

```
[schwarzgerat](0) $ kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Linux schwarzgerat 5.10.8nlb #1 SMP Sun Jan 17 13:21:52 EST 2021 x86_64
Debian GNU/Linux bullseye/sid \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/dank/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity    0.7
enable_audio_bell     False
font_family           Hack
update_check_interval 0.0
[schwarzgerat](0) $ 
```

**Additional context**
Reproduced with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
This is almost certainly a shell issue. When you do printf, your shell
is stripping out the soft-hyphen. When you insert it directly using the
kitten, it cant do that. You can confirm by repeating the experiment
with cat as your shell.

kitty cat

type a, insert the soft hyphen, type b
