### ISSUE TITLE
Add config option to set beep volume

### ISSUE THREAD

**Issue by Nudin** [kovidgoyal/kitty#3255]
**Is your feature request related to a problem? Please describe.**
The Visual bell is not sufficient to get notified when a "beep" occurs, using the audible bell is better, but the audible bell is very loud.

**Describe the solution you'd like**
A user setting that allows to change the volume.

**Describe alternatives you've considered**
I considered using Pulse Audio "magic" for this, but didn't succeed.

**Additional context**
For X11 an option to do this was introduced in 25d7668b704f3e3c8fff6534093388afbc02cca5 but removed again in d0f839bbd8d0727fcfef6a356a9a18e2a3182a0a. Is there any hopy that it will return (in a form independent of the desktop)? While the addition of the feature is mentioned in the changelog the removal isn't, I had to search git history to find what happened to the option.

**Comment by kovidgoyal** [comment]
The option was removed because x11 is no longer used to play the bell. libcanberra is used on linux these days. And you can customize the sound it plays however you like, a bit of googling will show you how. kitty itself has no influence on the volume.
