### ISSUE TITLE
Liberation Mono lowercase "L" is rendered with sharp edges instead of rounded edges.

### ISSUE THREAD

**Issue by tur1ngb0x** [kovidgoyal/kitty#3256]
**Describe the bug**
Lowercase "L" is rendered differently on kitty vs gnome-terminal

**Steps to reproduce the behavior**
1. Open gnome-terminal, type any command with lowercase "L"
2. Open kitty, type any command with lowercase "L"
3. Compare the results.

**Actual behaviour**
1. gnome-terminal renders lowercase "L" with rounded edges.
2. kitty renders lowercase "L" with sharp edges.

**Expected behavior**
1. kitty should render lowercase "L" with rounded edges

**Screenshots**
Left : kitty
Right : gnome-terminal
![Screenshot from 2021-01-22 17-59-29](https://user-images.githubusercontent.com/25666761/105491681-98a5ce00-5cae-11eb-8a2a-5815817141cc.png)

**Environment details**
OS: Ubuntu 20.04.1 Focal Fossa

**Output of kitty --debug-config**
```
kitty 0.15.0 created by Kovid Goyal
Linux a5 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64
Ubuntu 20.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/pd/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
copy_on_select             clipboard
cursor_blink_interval      1.0
cursor_shape               2
cursor_stop_blinking_after 0
editor                     nano
font_family                Liberation Mono
initial_window_width       (800, 'px')
mouse_hide_wait            0.0
remember_window_size       False
update_check_interval      0.0
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**~/.config/kitty/kitty.conf**
```
cat ~/.config/kitty/kitty.conf
# Fonts
font_size 11.0
font_family Liberation Mono
bold_font auto
italic_font auto
bold_italic_font auto
disable_ligatures never

# Cursor
cursor_shape beam
cursor_blink_interval 1
cursor_stop_blinking_after 0

# Notification
enable_audio_bell yes
window_alert_on_bell yes

# Window
remember_window_size no
initial_window_width 800
initial_window_height 400

# Misc
mouse_hide_wait 0
copy_on_select yes
editor nano
update_check_interval 0
```

**liberation font version**
```
dpkg -l | grep -i liberation
ii  fonts-liberation                           1:1.07.4-11                                          all          Fonts with the same metrics as Times, Arial and Courier
ii  fonts-liberation2                          2.1.0-1                                              all          Fonts with the same metrics as Times, Arial and Courier (v2)
```

**Comment by kovidgoyal** [comment]
You are almost certainly not using the font you think you are using. Use
--debug-font-fallback to check.

**Comment by tur1ngb0x** [comment]
It is the same font - Liberation Mono

![Screenshot from 2021-01-22 18-23-18](https://user-images.githubusercontent.com/25666761/105493102-d7d51e80-5cb0-11eb-9a69-856ff175bae2.png)

**Comment by tur1ngb0x** [comment]
@kovidgoyal 

Here is the character set of Liberation Mono font, it clearly has the rounded edge lowercase "L"
![Screenshot from 2021-01-22 18-29-59](https://user-images.githubusercontent.com/25666761/105493843-d2c49f00-5cb1-11eb-9bef-a771038bc996.png)

**Comment by kovidgoyal** [comment]
Yeah and it renders fine for me in kitty on linux with

kitty --config NONE -o 'font_family Libration Mono' -o 'font_size 22' sh -c 'echo l; read'

![Screenshot_20210122_183307](https://user-images.githubusercontent.com/1308621/105494139-5e552480-5ce0-11eb-9e76-3af77db1ac9f.png)


check your fontconfig configuration. You probably have a glyph override that kitty honors and gnome-terminal doesnt.
