### ISSUE TITLE
Having vertical split on fat layout cause graphical bug

### ISSUE THREAD

**Issue by NikoKS** [kovidgoyal/kitty#3258]
**Describe the bug**
When having a vertical split using the fat layout with 3 or more windows, the window doesn't stretch all the way down.

in this screenshot, you can see that with only 2 windows, it's working as expected:
![Screen Shot 2021-01-22 at 10 38 14 PM](https://user-images.githubusercontent.com/24285511/105571186-ee0bca80-5d02-11eb-866a-a4aa333db639.png)

but when I add a third window, this happens:
![Screen Shot 2021-01-22 at 10 32 04 PM](https://user-images.githubusercontent.com/24285511/105571192-ff54d700-5d02-11eb-9737-56d2bc5fe538.png)

The window doesn't stretch all the way down for some reason.

Also I notice that this only happen if I have multiple tab (tab bar is visible)

**To Reproduce**
1. create fat layout (haven't try on other layouts, but so far only notice it on fat layout)
2. have the tab bar visible
3. open 3 or more window

**Expected behavior**
windows stretch all the way to bottom and no graphical glitch visible

**Environment details**
OS: Mac OS Mojave

**Additional context**
Try to reproduce the problem with `kitty --config NONE`

After trying with no config as suggested, I think the problem is that kitty still thinks that there is a tab bar at the bottom even though I've set my tab bar at the top.

<img width="1680" alt="Screen Shot 2021-01-23 at 8 58 11 AM" src="https://user-images.githubusercontent.com/24285511/105608690-52f20f80-5d59-11eb-905f-b1a1ab1f5d92.png">

**Comment by kovidgoyal** [comment]
It cant stretch all the way to the bottom because there is not enough space left over for a complete row. When you add a third window, there is not a double border which takes more pixels, thereby causing the leftover space to appear. See the placement_strategy option in kitty.conf.

**Comment by NikoKS** [comment]
@kovidgoyal 
Changing the placement_strategy doesn't seem to work for me.
I've tried placement_strategy bottom, and pacement_strategy bottom-left. and the extra padding is still there.

also, no matter how I resize the kitty window, I can't get rid of that padding.
I really think that it's making extra space thinking that there's a tab bar at the bottom. Because the size of the padding is always around the height of the tab bar.

When you have the time, please consider looking into the matter.
Thank you for your help! Kitty is near perfect if not because of this for me.

**Comment by kovidgoyal** [comment]
OK, I will take a look at it when I have a moment
