### ISSUE TITLE
Questions about kitty for Apple M1 chip

### ISSUE THREAD

**Issue by croaky** [kovidgoyal/kitty#3259]
Hello! I've been a user of Kitty on macOS for awhile. Great software, thanks for writing and maintaining it!

I've been installing and updating Kitty through Homebrew, which has worked great.

On a new M1-based laptop, I can install Kitty through Homebrew:

```
% brew install kitty
==> Downloading https://github.com/kovidgoyal/kitty/releases/download/v0.19.3/kitty-0.19.3.dmg
Already downloaded: /Users/croaky/Library/Caches/Homebrew/downloads/57e62c53ada658dafbffc8272ae0e34f54f2bfcc0e3dc956f922cc3b3638e14e--kitty-0.19.3.dmg
==> Installing Cask kitty
==> Moving App 'kitty.app' to '/Applications/kitty.app'.
==> Linking Binary 'kitty.wrapper.sh' to '/opt/homebrew/bin/kitty'.
🍺  kitty was successfully installed!
```

But when I use Kitty, from the command line, it reports the Intel architecture instead of ARM:

```
% uname -m
x86_64
```

What needs to be done to be able to `brew install kitty` and have it install an architecture-compatible version?

I'm happy to help with testing or updating the Homewbrew formula but I'm not sure exactly what needs to be done.

I've seen some `if Hardware::CPU.arm?` conditionals in Homebrew formulas like Go's for example: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/go.rb

I don't see a similar conditional for Kitty's formula https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/kitty.rb

Thanks!

**Comment by kovidgoyal** [comment]
No idea, I dont use brew. kitty itself builds fine and works on MI as
a native binary. What needs to be done to get brew to do that, I have no
clue. You can simply build kitty from source yourself, it's not hard:
https://sw.kovidgoyal.net/kitty/build.html

**Comment by Luflosi** [comment]
Homebrew simply uses the prebuilt binary. As soon as that supports the M1 chip, it should just work. AFAIK, this is on @kovidgoyal s TODO list. Until then, just build kitty from source as he already said
