### ISSUE TITLE
Linux binary build missing icon in taskbar

### ISSUE THREAD

**Issue by namandixit** [kovidgoyal/kitty#3260]
**Describe the bug**
On Fedora 33 (with GNOME 3.38.3), downloading the binary release and launching through the `bin/kitty` command results in the taskbar having no icon.

The documentation [here](https://sw.kovidgoyal.net/kitty/binary.html#desktop-integration-on-linux) provides a way to add `.desktop` integration for icons. However, I am trying to create a portable development toolset that users could carry from one machine to another (say, on a USB stick), and would like not to make any changes to the host machine's existing environment. Due to this, it would be much better if the application set its own icon programatically through the Xlib APIs.

**To Reproduce**
1. Download the Linux binary build from "Releases" 
2. Unpack the archive and navigate to the `bin` directory
3. Run `kitty` command.
4. The taskbar entry will have no icon.

**Expected behavior**
When a terminal window is created, its taskbar entry should show the correct icon.

**Screenshots**
![Screenshot from 2021-01-25 16-49-49](https://user-images.githubusercontent.com/8736472/105699629-ad43c980-5f2d-11eb-81e4-2ca2ab671a14.png)

**Environment details**
Fedora 33, GNOME 3.38.3 (with Dash to Panel extension, removing which doesn't solve the issue)

```
kitty 0.19.3 (3ce04c3e4b) created by Kovid Goyal
Linux fedora 5.10.9-201.fc33.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: /home/naman/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
```

**Additional context**
`kitty --config NONE` does not solve the issue.

**Comment by kovidgoyal** [comment]
It does set its own icon, on X11. You are probably using wayland which
has no way for applications to set icons, as far as I know.

**Comment by namandixit** [comment]
No, I am running in X11 mode as shown below. Please reopen.

```
$ loginctl
SESSION  UID USER  SEAT  TTY 
      5 1000 naman seat0 tty3

1 sessions listed.
$ loginctl show-session 5 -p Type
Type=x11
```

**Comment by kovidgoyal** [comment]
Well, kitty asks glfw to set the window icon, if it isn't working, you'll
have to debug why glfw is failing to set the icon. See line 678 in
kitty/glfw.c

**Comment by kovidgoyal** [comment]
And in fact running the following inside a kitty window

xprop -id $WINDOWID -notype 32c _NET_WM_ICON

returns icon data, as expected

**Comment by namandixit** [comment]
> glfw

Sorry, can you explain what is happening in the [set_default_window_icon](https://github.com/kovidgoyal/kitty/blob/master/kitty/glfw.c#L398)? Where are we loading the icon's bitmap data from? (I am not familiar with Python's C API.)

> xprop

How did you view the resulting pixel dump? Using the command [here](https://superuser.com/a/1017500) results in the following error:

````
$   xprop -id $WINDOWID -notype 32c _NET_WM_ICON | perl -0777 -pe '@_=/\d+/g;
    printf "P7\nWIDTH %d\nHEIGHT %d\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n", splice@_,0,2;
    $_=pack "N*", @_;
    s/(.)(...)/$2$1/gs' | pamrgbatopng > the_icon.png
pamrgbatopng: End of file encountered when trying to read a row from input file.
````

Here is `xprop`'s output: [logo.txt](https://github.com/kovidgoyal/kitty/files/5866479/logo.txt) (warning: one single very long line, gedit chokes on it)

**Comment by kovidgoyal** [comment]
On Mon, Jan 25, 2021 at 04:26:23AM -0800, Naman Dixit wrote:
> > glfw
> 
> Sorry, can you explain what is happening in the [set_default_window_icon](https://github.com/kovidgoyal/kitty/blob/master/kitty/glfw.c#L398)? Where are we loading the icon's bitmap data from? (I am not familiar with Python's C API.)
> 

logo/kitty.rgba

> > xprop
> 
> How did you view the resulting pixel dump? Using the command [here](https://superuser.com/a/1017500) results in the following error:
> 
> ````
> $   xprop -id $WINDOWID -notype 32c _NET_WM_ICON | perl -0777 -pe '@_=/\d+/g;
>     printf "P7\nWIDTH %d\nHEIGHT %d\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n", splice@_,0,2;
>     $_=pack "N*", @_;
>     s/(.)(...)/$2$1/gs' | pamrgbatopng > the_icon.png
> pamrgbatopng: End of file encountered when trying to read a row from input file.
> ````
> 
> Here is `xprop`'s output: [logo.txt](https://github.com/kovidgoyal/kitty/files/5866479/logo.txt) (warning: one single very long line, gedit chokes on it)

I didnt view it I just checked that it exists. You probably need to fix
_glfwPlatformSetWindowIcon in glfw/x11_window.c

**Comment by namandixit** [comment]
Installing from Fedora's repo shows the icon properly, both when running from `kitty` command and from the `.desktop` menu entry; but running either the binary release or manually compiled build doesn't. This means that the bug is obviously not in GLFW, and is probably due to not being able to locate/load the icon. 

If there is a bug, it has to be in the `set_default_window_icon` function; however, I am still unable to trace how exactly is it getting the file path, etc. It does load in the `256` in the `logo.width` and `logo.height` members though, for what it is worth.

Debugging this any further will require more intimate understanding of this codebase than I possess.

**Comment by kovidgoyal** [comment]
If the file was not found, then nothing would be set, at all. In fact
kitty would not start. And if you want to see where the file is loaded
look at line 135 of kitty/main.py

And you cant test using a distro release, since they will be installing
the .desktop file globally. So regardless of how you start the installed kitty
binary the icon will probably get associated.

On Mon, Jan 25, 2021 at 05:23:50AM -0800, Naman Dixit wrote:
> Installing from Fedora's repo shows the icon properly, both when running from `kitty` command and from the `.desktop` menu entry; but running either the binary release or manually compiled build doesn't. This means that the bug is obviously not in GLFW, and is probably due to not being able to locate/load the icon. 
> 
> If there is a bug, it has to be in the `set_default_window_icon` function; however, I am still unable to trace how exactly is it getting the file path, etc. It does load in the `256` in the `logo.width` and `logo.height` members though, for what it is worth.
> 
> Debugging this any further will require more intimate understanding of this codebase than I possess.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3260#issuecomment-766812751

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________
