### ISSUE TITLE
kitty images should not block input

### ISSUE THREAD

**Issue by wis** [kovidgoyal/kitty#3263]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm using ranger to view a directory of images and pressing j (to select the next file/image below) but kitty doesn't capture my input.

**Describe the solution you'd like**
when kitty starts or while it is decoding and rendering the image it should still listen for input so the program stays responsive.

**Describe alternatives you've considered**
I found none.

**Additional context**
not necessary.

**Comment by kovidgoyal** [comment]
That's up to ranger to implement. kitty doesn't stop sending input to the
terminal program while displaying images.

If you are talking about the icat kitten, then yes that does throwaway
input while running, but that it pretty much the behavior of any program
that runs. Input you send it while running, is processed byt he program
not what comes after it.

**Comment by wis** [comment]
no, I'm not talking about the icat kitten.
So, Kitty still sends the key presses while it's decoding/+rendering and ranger blocks until it gets kitty's image preview protocol response that means "I'm done rendering"? (I'm not familiar how Kitty Image Previews work)

**Comment by kovidgoyal** [comment]
On Tue, Jan 26, 2021 at 03:02:51AM -0800, Wis wrote:
> no, I'm not talking about the icat kitten.

I'm afraid I'm not interested in having the kitten store and retransmit
input during its brief time of operation.

> So, Kitty still sends the key presses while it's decoding/+rendering and ranger blocks until it gets kitty's image preview protocol response that means "I'm done rendering"? (I'm not familiar how Kitty Image Previews work)

https://sw.kovidgoyal.net/kitty/graphics-protocol.html

**Comment by kovidgoyal** [comment]
Oh and if you want icat to not read anything from the tty, use --trasfer-mode=stream
