### ISSUE TITLE
Ghost typing when starting kitty as a single instance on sway.

### ISSUE THREAD

**Issue by bjonnh** [kovidgoyal/kitty#3266]
**Describe the bug**
Starting kitty with kitty --single-instance in sway when the mouse is already where the terminal will appear, the terminal
fills with the letter "d" (which on my keymap is equivalent to the letter i). This only happens when starting kitty with $mod+Enter (Logo-key is my mod). This does not happen with other programs.

**To Reproduce**
1. Start kitty --single-instance  with a Logo-key + Enter shortcut on Sway

**Expected behavior**
Behaves like without --single-instance or when using a different shortcut.

**Environment details**
OS: Archlinux

```
Output of kitty --debug-config

kitty 0.19.3 created by Kovid Goyal
Linux XYZ 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/xyz/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background_opacity 0.9
bold_font          Jetbrains Mono Bold
bold_italic_font   Jetbrains Mono Bold Italic
font_family        Jetbrains Mono
italic_font        Jetbrains Mono Italic
Added shortcuts:
	control+down KeyAction(func='previous_window', args=())
	control+up KeyAction(func='next_window', args=())
```

**Additional context**
Happens with --config NONE as well.

**Comment by kovidgoyal** [comment]
I cannot reproduce, using the following sway config

```
set $term kitty -1
bindsym $mod+Return exec $term
```

**Comment by bjonnh** [comment]
See it in action: https://www.bjonnh.net/share/2021-01-27_10-32-08.mkv 

Happens with a bepo keyboard layout, if I use a US layout it types i instead of d

**Comment by kovidgoyal** [comment]
Sorry without some way to reproduce I cant help you. I suggest starting with a minimal sway config and kitty config, and seeing what triggers it.

**Comment by bjonnh** [comment]
bug happens with no kitty config, and with the following "minimal" sway config:
````
input * xkb_layout "fr"
input * xkb_variant "bepo"
input * xkb_options "ctrl:nocaps"

set $mod Mod4

floating_modifier $mod

bindsym $mod+Control+r reload

bindsym $mod+Return exec kitty --single-instance

bar {
  swaybar_command waybar
}

````

Also happens without those xkb lines, just that it displays i instead of d

**Comment by bjonnh** [comment]
Also, if I press ctrl it stops typing, when I release it continues. if I press shift, it types D uppercase.

I restarted sway in debug mode will see what it says.

**Comment by kovidgoyal** [comment]
Sorry, that does not reproduce for me. Running sway 1.5.1 and kitty from
master.

**Comment by bjonnh** [comment]
Happens with kitty from master: kitty 0.19.3 (36ca3838a6)
Sway version 1.5.1

**Comment by kovidgoyal** [comment]
It seems pretty clear that your issue is the key repeat being triggered for the i key, why that is, I have no idea. You can run kitty with --debug-keyboard via a wrpper script and see exactly what key events kitty receives.

**Comment by kovidgoyal** [comment]
On wayland, IIRC there are no repeat events, instead the client has to run a repeat until a release event is received via a timer. I am guessing the --debug-keyboard log will show that kitty is receiving a key press for the i key and no corresponding release.

**Comment by bjonnh** [comment]
I had to start an instance, and restart multiple time for the bug to show up but here is the log:
````
Loading new XKB keymaps
Release xkb_keycode: 0x7d clean_sym: Super_L mods: super+numlock glfw_key: 57443 (LEFT_SUPER) xkb_key: 65515 (Super_L)
Press xkb_keycode: 0x3a clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 57441 (LEFT_CONTROL) xkb_key: 65507 (Control_L) alternate_key: 57358 (CAPS_LOCK)
on_key_input: glfw key: 57441 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow repeat events
Press xkb_keycode: 0x17 clean_sym: d composed_sym: d mods: ctrl+numlock glfw_key: 100 (d) xkb_key: 100 (d) alternate_key: 105 (i)
on_key_input: glfw key: 100 native_code: 0x64 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
Release xkb_keycode: 0x7d clean_sym: Super_L mods: super+numlock glfw_key: 57443 (LEFT_SUPER) xkb_key: 65515 (Super_L)
Press xkb_keycode: 0x3a clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 57441 (LEFT_CONTROL) xkb_key: 65507 (Control_L) alternate_key: 57358 (CAPS_LOCK)
on_key_input: glfw key: 57441 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow repeat events
Press xkb_keycode: 0x17 clean_sym: d composed_sym: d mods: ctrl+numlock glfw_key: 100 (d) xkb_key: 100 (d) alternate_key: 105 (i)
on_key_input: glfw key: 100 native_code: 0x64 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
Release xkb_keycode: 0x7d clean_sym: Super_L mods: super+numlock glfw_key: 57443 (LEFT_SUPER) xkb_key: 65515 (Super_L)
Press xkb_keycode: 0x7d clean_sym: Super_L composed_sym: Super_L mods: numlock glfw_key: 57443 (LEFT_SUPER) xkb_key: 65515 (Super_L)
on_key_input: glfw key: 57443 native_code: 0xffeb action: PRESS mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow repeat events
Release xkb_keycode: 0x7d clean_sym: Super_L mods: super+numlock glfw_key: 57443 (LEFT_SUPER) xkb_key: 65515 (Super_L)
Press xkb_keycode: 0x3a clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 57441 (LEFT_CONTROL) xkb_key: 65507 (Control_L) alternate_key: 57358 (CAPS_LOCK)
on_key_input: glfw key: 57441 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow repeat events
Press xkb_keycode: 0x17 clean_sym: d composed_sym: d mods: ctrl+numlock glfw_key: 100 (d) xkb_key: 100 (d) alternate_key: 105 (i)
on_key_input: glfw key: 100 native_code: 0x64 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
Release xkb_keycode: 0x7d clean_sym: Super_L mods: super+numlock glfw_key: 57443 (LEFT_SUPER) xkb_key: 65515 (Super_L)
Press xkb_keycode: 0x17 clean_sym: d composed_sym: d text: d mods: numlock glfw_key: 100 (d) xkb_key: 100 (d) alternate_key: 105 (i)
on_key_input: glfw key: 100 native_code: 0x64 action: REPEAT mods: 0x0 text: 'd' state: 0 sent text to child
Press xkb_keycode: 0x17 clean_sym: d composed_sym: d text: d mods: numlock glfw_key: 100 (d) xkb_key: 100 (d) alternate_key: 105 (i)
on_key_input: glfw key: 100 native_code: 0x64 action: REPEAT mods: 0x0 text: 'd' state: 0 sent text to child
Press xkb_keycode: 0x17 clean_sym: d composed_sym: d text: d mods: numlock glfw_key: 100 (d) xkb_key: 100 (d) alternate_key: 105 (i)
on_key_input: glfw key: 100 native_code: 0x64 action: REPEAT mods: 0x0 text: 'd' state: 0 sent text to child
[…] and that repeated over and over
````

**Comment by bjonnh** [comment]
I have trouble reproducing it everytime but here is what I had to do:
- start an instance ( with -i) on a workspace
- switch to a workspace with a single window (in my case chromium)
- put the mouse where kitty will appear
- start it with Mod4+Enter

**Comment by bjonnh** [comment]
doing that multiple time, after 3-4 tries, it starts displaying d's in the new window

**Comment by bjonnh** [comment]
correction: looks like it is not related to the shortcut I usein the end, it was just spurious correlation.

**Comment by bjonnh** [comment]
As the bug doesn't happen (tried hundreds of times) without "-i", I'll just stop using that flag.

**Comment by kovidgoyal** [comment]
Why is there a keypress for control in there?? Is pressing super+return
somehow getting mapped to ctrl+i for you?? Check your xkb rules/xkbcomp
setup, etc. In any case, seems pretty clear that kitty is receiving the
key eents from the window manager, so the bug is not in kitty.

**Comment by bjonnh** [comment]
This is when I closed other windows and reopened new ones. It never seem to happen for the first windows sharing that instance.

**Comment by bjonnh** [comment]
Ok I'll forward that to the Sway people then. Thanks a lot for your help with debugging that.

**Comment by bjonnh** [comment]
Digging deeper:
I ran ````libinput debug-events --show-keycodes````,  sway is not receiving any KEY_I (mapped to d on my keyboard)

Also the bug happen without any xkb settings (default US settings of sway) so unlikely to be related to xkb

**Comment by bjonnh** [comment]
Running kitty with WAYLAND_DEBUG=1 shows that it is not receiving repeated keystrokes from sway either… 
It is as if the d I typed when trying to exit one of the windows of my instance was still there somewhere in the instance and not processed (nor released)

**Comment by bjonnh** [comment]
````
[1190912.280]  -> wl_seat@15.get_keyboard(new id wl_keyboard@21)
[1190972.580] wl_keyboard@21.keymap(1, fd 7, 50744)
[1190982.915] wl_keyboard@21.repeat_info(25, 600)
[1191005.509] wl_keyboard@21.enter(25034, wl_surface@22, array)
[1191005.553] wl_keyboard@21.modifiers(25035, 0, 0, 16, 0)
[1191731.093] wl_keyboard@21.leave(25038, wl_surface@22)
[1194804.194] wl_keyboard@21.enter(25075, wl_surface@33, array)
[1194804.226] wl_keyboard@21.modifiers(25076, 64, 0, 16, 0)
[1194954.685] wl_keyboard@21.key(25077, 74822587, 125, 0)
[1194954.711] wl_keyboard@21.modifiers(25078, 0, 0, 16, 0)
[1195474.662] wl_keyboard@21.key(25081, 74823107, 58, 1)
[1195474.738] wl_keyboard@21.modifiers(25082, 4, 0, 16, 0)
[1195570.759] wl_keyboard@21.key(25083, 74823203, 23, 1)
[1195576.342] wl_keyboard@21.leave(25084, nil)
[1196322.464] wl_keyboard@21.enter(25101, wl_surface@33, array)
[1196322.541] wl_keyboard@21.modifiers(25102, 64, 0, 16, 0)
[1196394.708] wl_keyboard@21.key(25103, 74824027, 125, 0)
[1196394.738] wl_keyboard@21.modifiers(25104, 0, 0, 16, 0)
[1197170.623] wl_keyboard@21.key(25109, 74824803, 58, 1)
[1197170.693] wl_keyboard@21.modifiers(25110, 4, 0, 16, 0)
[1197314.626] wl_keyboard@21.key(25111, 74824947, 23, 1)
[1197320.458] wl_keyboard@21.leave(25112, nil)
[1197750.274] wl_keyboard@21.enter(25127, wl_surface@33, array)
[1197750.354] wl_keyboard@21.modifiers(25128, 64, 0, 16, 0)
[1197794.680] wl_keyboard@21.key(25129, 74825427, 125, 0)
[1197794.705] wl_keyboard@21.modifiers(25130, 0, 0, 16, 0)
[1198106.635] wl_keyboard@21.key(25133, 74825739, 58, 1)
[1198106.714] wl_keyboard@21.modifiers(25134, 4, 0, 16, 0)
[1198282.606] wl_keyboard@21.key(25135, 74825915, 23, 1)
[1198288.368] wl_keyboard@21.leave(25136, nil)
[1198679.997] wl_keyboard@21.enter(25151, wl_surface@33, array)
[1198680.060] wl_keyboard@21.modifiers(25152, 64, 0, 16, 0)
[1198680.375] wl_keyboard@21.key(25153, 74826307, 125, 0)
[1198680.406] wl_keyboard@21.modifiers(25154, 0, 0, 16, 0)
[1200059.133] wl_keyboard@21.leave(25159, wl_surface@33)
````

**Comment by kovidgoyal** [comment]
> Running kitty with WAYLAND_DEBUG=1 shows that it is not receiving repeated keystrokes from sway either…
> It is as if the d I typed when trying to exit one of the windows of my instance was still there somewhere in the instance and not processed (nor released)

You didnt mention pressing ctrl+d in your repro steps. Can you post more complete repro steps? And try this commit https://github.com/kovidgoyal/kitty/commit/0443e5ad7f07846e22286a0903ab026167048a7a  it might fix your issue.

**Comment by bjonnh** [comment]
It absolutely does fix it. Thanks a lot!

**Comment by kovidgoyal** [comment]
Cool, you are welcome :)
