### ISSUE TITLE
Recursive diff with SSH

### ISSUE THREAD

**Issue by nicegamer7** [kovidgoyal/kitty#3268]
**Is your feature request related to a problem? Please describe.**
I was hoping I'd be able to compare two folders on a remote server, but it seems kitty only supports files when using the `ssh` prefix.

**Describe the solution you'd like**
I'd like kitty's diff to be able to recurse even over SSH.

**Describe alternatives you've considered**
I've considered installing kitty on the remote server, but that's not possible in my current situation.

**Comment by kovidgoyal** [comment]
Not something I care to implement, but patches are welcome. Or just use sshfs.

**Comment by nicegamer7** [comment]
Thanks @kovidgoyal :)

**Comment by kovidgoyal** [comment]
You're welcome!

**Comment by alok** [comment]
@kovidgoyal i love how many times you close a feature request, i think nothing of it, and go to sleep, only to find you implemented the feature anyway by the time i woke up. =)

**Comment by kovidgoyal** [comment]
With these kinds of things, it usually happens because I get an idea
that lets me implement much more easily than I first thought when I
closed it.

**Comment by alok** [comment]
I know the feeling =)
