### ISSUE TITLE
Segmentation fault - scrollback_pager_history_size + font size

### ISSUE THREAD

**Issue by aorith** [kovidgoyal/kitty#3269]
**Describe the bug**

Segmentation fault happens when pipping the output to less with `ctrl+shift+h` with a small font size together with scrollback_pager_history_size configured and filled.

As I workaround I have disabled `scrollback_pager_history_size` which is a pity because it saves a lot of RAM.

**To Reproduce**

1. Create a small config file.
```
# cat /tmp/kitty.conf
scrollback_lines 10
scrollback_pager_history_size 1
```
2. Run kitty `kitty -c /tmp/kitty.conf`
3. Generate some output: `cd && tree`
4. Decrease font size significantly with `mod+-`
5. Press `ctrl+shift+h`, sometimes after moving a little bit the kitty OS window or increasing/decreasing the font size.
6. Segmentation fault.

If `scrollback_pager_history_size` is not defined the bug never happens.

I'm also experiencing this with other mappings that fetch the terminal output:

```
map ctrl+shift+s launch --stdin-source=@screen_scrollback --type=background ~/.scripts/pipe-as-file-open.py "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" -w
map ctrl+shift+v launch --stdin-source=@screen_scrollback --type=tab ~/.scripts/pipe-as-file-open.py vim -u ~/.vim/min-vimrc
map ctrl+shift+o launch --stdin-source=@screen_scrollback --type=background dd of="/tmp/kitty_output.log"
```

**Environment details**
OS: MacOs Big Sur 11.1

**Comment by kovidgoyal** [comment]
dup of #3049
