### ISSUE TITLE
Export current configuration

### ISSUE THREAD

**Issue by fladson** [kovidgoyal/kitty#3270]
Sorry, this is more a question than a bug.

I was playing with some scripts and overwrote my config but I still have a window open with the old config working normally.
Is it possible to locate the file that the current window is fetching the config or is it in the memory?

Thank you for the help.

**Comment by kovidgoyal** [comment]
it's in memory.

**Comment by fladson** [comment]
Thank you for the answer!

**Comment by CarterSnich** [comment]
@kovidgoyal How can it be exported if it's still in memory?
