### ISSUE TITLE
Layout tall:bias=XX ignored

### ISSUE THREAD

**Issue by cartesius82** [kovidgoyal/kitty#3273]
Simple `startup_session` with a customized `tall` layout:
```
enabled_layouts tall:bias=60
layout tall
launch nvim
focus
launch zsh
launch zsh
```

But in `kitty/layout/tall.py` on line say 68 `print(data)` gives `{}`, specifically **`bias` option is not parsed properly** and the default values `50` resp. `0.5` is used. Manually tweaking default 0.5 => 0.6 in the source file works perfectly. No config errors are printed.

**commit** 0fc93118f2ee60b563809abf2df4dd8d2731e546
Python 3.9.1 on Arch Linux

**Comment by kovidgoyal** [comment]
I presume you are using an outdated version of kitty before this feature
was implemented. Update and you will be fine.

**Comment by cartesius82** [comment]
Hi,
I double checked that and I am really using the *newest* version available from 29 January 2021, commit hash included in my report. Git-pulled yesterday.
I run it from the repo via:
`./kitty/launcher/kitty --session ~/.config/kitty/custom.conf`

and it really shows only the 50:50 split ignoring the `bias`.

**Comment by cartesius82** [comment]
Added the last line into `tall.py`:
```
class TallLayoutOpts(LayoutOpts):
    bias: Tuple[float, ...] = ()
    full_size: int = 1
    mirrored: bool = False

    def __init__(self, data: Dict[str, str]):
        print("Dict is empty: ", not bool(data))
```
prints `True`.

**Comment by kovidgoyal** [comment]
Works for me with
```
enabled_layouts tall:bias=80
launch cat
launch cat 
launch cat
```

**Comment by kovidgoyal** [comment]
remove the second layout tall line from your session.conf

**Comment by cartesius82** [comment]
Ohhhhh........ That's it! I thought that the scenario was:
1. In `enabled_layouts` list the enabled layouts, just one in my case, with all the arguments.
2. Start that **pre-defined** layout via `layout tall` in the session file...

**Comment by kovidgoyal** [comment]
On Sat, Jan 30, 2021 at 05:49:46AM -0800, cartesius82 wrote:
> Ohhhhh........ That's it! I thought that the scenario was:
> 1. In `enabled_layouts` list the enabled layouts, just one in my case, with all the arguments.
> 2. Start that **pre-defined** layout via `layout tall` in the session file...

If you want to use layout rather than enabled_layouts, you need

layout tall:bias=80

as well.
