### ISSUE TITLE
Why is this changing format/color?

### ISSUE THREAD

**Issue by CallumDowling** [kovidgoyal/kitty#3276]
![changing_format](https://user-images.githubusercontent.com/22888330/106349026-b44c4c80-631e-11eb-8265-0163f2690b9c.png)
Why does the prompt color, and new line for command change? How do you disable this, particularly the new line for command after cd? This is so annoying

kitty 0.19.3
zsh 5.8

**Comment by kovidgoyal** [comment]
prompts are drawn by shells not terminals. You need to ask the maintainers of zsh or more likely whatever package you have installed to give you fancy prompts in zsh.

**Comment by CallumDowling** [comment]
Cheers, thanks
