### ISSUE TITLE
"Badge" feature?

### ISSUE THREAD

**Issue by kbd** [kovidgoyal/kitty#3279]
I'm investigating switching from iTerm2. One thing I'll miss is [its badge feature](https://iterm2.com/documentation-badges.html) that allows you to overlay text on a window. For example, when working on a production server I'll set a bright red badge like "PROD" to help me be more careful. Is there any way to accomplish something like this in Kitty?

**Comment by kovidgoyal** [comment]
There are many ways to do things like this. The most dramatic is to set
the colors of the window to something different
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-change-the-colors-in-a-running-kitty-instance

However, if you use terminal programs like fullscreen ones, that set
their own colors, your colors will get overridden.

Alternately you can create the window with a fixed title or a tab with a
fixed title. See https://sw.kovidgoyal.net/kitty/launch.html
