### ISSUE TITLE
Disable sanitize

### ISSUE THREAD

**Issue by Ulrar** [kovidgoyal/kitty#328]
Hi,

For some reason, running "make" seems to try to turn on sanitize, even though I don't have libasan : 

```
CC: gcc (7, 3)
Package wayland-protocols was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-protocols.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-protocols' found
wayland-protocols >= 1.12 is required, found version: not found
Disabling building of wayland backend
Creating asan-launcher ...
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find libasan_preinit.o: No such file or directory
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lasan
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lasan
collect2: error: ld returned 1 exit status
```

I've tried with make, and directly running `python3 setup.py` and both times it tries to enable sanitize itself. Running 3.5.4-r1 if that matters

**Comment by kovidgoyal** [comment]
The sanitize launcher is always built, kitty itself is not built with sanitization unless you specify the --sanitize argument. If for some reason your system is missing the sanitization libraries, simply comment out line 665 to disable building of the sanitize launcher as well. I should probably make building that conditional on --sanitize as well.

**Comment by Ulrar** [comment]
Ah, I see. On gentoo gcc is built without sanitize by default, it is easy
enough to add but the option would be nice. I guess whoever packaged it
must have commented that line in the original ebuild. Thanks
