### ISSUE TITLE
Automatic timestamps

### ISSUE THREAD

**Issue by kbd** [kovidgoyal/kitty#3281]
Just switched from iTerm2 to Kitty and one of the features I'm going to miss the most is iTerm2's automatic timestamps. You hit ⌘⇧E and get the time each line of the terminal was printed shown on the right hand side. It's super valuable since you can see specifically when anything ran, even long after the fact. Putting the date in your prompt isn't a good substitute because it doesn't track during execution of a program.

**Comment by kovidgoyal** [comment]
I'm afraid I dont think this is a good idea, it means extra RAM to store
the dates per line, and extra CPU to process the dates on every new line
and extra code to support displaying overlaid text on terminal windows.

All that makes it not worth the tradeoff.
