### ISSUE TITLE
Native window decorations for GNOME Wayland

### ISSUE THREAD

**Issue by DiegoMagdaleno** [kovidgoyal/kitty#3284]
Hi, im a developer, and Im interested in kitty, I was sad when I saw it doesn't support client side decorations, since im a wayland gnome user, I would love to say I have other options, but sadly with my HiDPI monitor, it looks like wayland is my only option.

I would be glad to try to get to some extent some client side decorations working, what is kitty missing to support this feature? is it possible? is the possibility of supporting this good? 

Thanks! And of course thank you for your awesome software, it makes using the terminal much much better.

**Comment by kovidgoyal** [comment]
It supports client side decorations already, they are just simple white
borders without any functionality other than dragging/resizing. If you want
decorations with more functionality you would need to actually implement
it in wl_window.c. Possibly using something like libdecoration, or since
GNOME is the only window manager stupid enough to not implement server
side decorations, just directly use gtk libraries. But note that I am not
willing to have kitty require GTK as a hard dependency at either build
or run time. That means putting the code into a separate .so module that
is built only if gtk is found in setup.py via pkg-config and that is
loaded dynamically at runtime via dlopen.

**Comment by DiegoMagdaleno** [comment]
Thanks, I get into it! And yeah I respect your decision and it was actually what I had in mind!

**Comment by kovidgoyal** [comment]
Cool, all the best. Feel free to ask questions if you need clarification,
although I am no Wayland expert.

**Comment by LeonardKoenig** [comment]
Note that there's work on adding glfw CSD support via libdecoration already:
https://github.com/glfw/glfw/pull/1693

**Comment by kovidgoyal** [comment]
I looked into this and libdecoration is half baked, *at best*. It currently supports only a simple titlebar drawn using cairo, which is pointless since it wont be native anyway. And it hasn't even been released, *ever*.

If I were you I'd skip libdecoration entirely and just draw the titlebar using gtk libraries. Or better, stop using GNOME.

**Comment by DragonSWDev** [comment]
>It currently supports only a simple titlebar drawn using cairo, which is pointless since it wont be native anyway

There is some work in progress to implement GTK plugin for libdecoration which should integrate with desktop pretty nicely. Even without it it's probably still better to have simple cairo titlebar than non functional or even no titlebar at all.

There is also some interest in SDL to pickup libdecoration. When it will happen libdecoration probably will be available in repositories of popular distributions.

**Comment by kovidgoyal** [comment]
Is this work happening in a public repository somewhere? And there is no need for libcairo just to draw a title. kitty already includes both harfbuzz and fontconfig/freetype that are together perfectly capable of doing simple single line text layout/rendering. In fact, I think I will just add support for rendering titles to the current empty titlebar. Should be a day or so of work.

**Comment by DragonSWDev** [comment]
There is merge request about this on libdecoration GitLab. I also tested this and it worked pretty reliably. Not perfect but gives some preview how it should work in future.

Your solution sounds nice for now. libdecoration is fine (at least for me) but it's still WIP so maybe waiting for official support on GLFW side isn't bad idea.

**Comment by kovidgoyal** [comment]
In master now kitty has fully functional though non native decorations on GNOME.

**Comment by molaeiali** [comment]
After updating to 0.20.0 today on Arch Gnome 40, My window decorations are gone, is this related? Is this a feature or a bug? Is there any way to bring them back in the config?
![Screenshot from 2021-04-19 19-19-45](https://user-images.githubusercontent.com/12999682/115256324-5cb2c580-a144-11eb-9adf-92fd3b9eaab4.png)

**Comment by kovidgoyal** [comment]
They arent gone they are just not native. If you want native set linux_display_server to x11 in kitty.conf which was what it used to default to.

**Comment by ljrk0** [comment]
> After updating to 0.20.0 today on Arch Gnome 40, My window decorations are gone, is this related? Is this a feature or a bug? Is there any way to bring them back in the config?

These are window decorations!  They are "non native" in the sense of they aren't GNOME themed, but they are "there" ;)

Basically there are two camps when it comes to window decorations: client side and server side.  The latter is the more classical approach of having the window decorations be drawn by the desktop environment and the application itself is only responsible for the "content".  This was what everyone did in the X11 world, even GNOME.

With Wayland, GNOME deprecated support for server side decorations in their own software.  There are wayland compositors that allow for SSDs, Mutter doesn't.  That means, each Wayland application must draw its own CSDs in GNOME.

Before the latest update you ran kitty as XWayland application, and thus GNOME added SSDs due to backwards compatibility.
Kitty now defaults to wayland directly and brings their own CSDs which are more minimal than what GNOMEs X11 SSDs provided.

You can either switch back to Xwayland, implement "proper" CSDs in kitty yourself or nag the GNOME team to support SSDs again in Wayland :)

**Comment by RedDocMD** [comment]
> You can either switch back to Xwayland, implement "proper" CSDs in kitty yourself or nag the GNOME team to support SSDs again in Wayland :)

Yeah XWayland sounds good to me, as it is half of the applications that I use do that.


> In master now kitty has fully functional though non native decorations on GNOME.

How do I close the terminal? I don't see a close button or something like that. Is there a way to add that? (like what do I do to add that?)

**Comment by kovidgoyal** [comment]
On Mon, Apr 19, 2021 at 09:15:15PM -0700, Deep Majumder wrote:
> > In master now kitty has fully functional though non native decorations on GNOME.
> 
> How do I close the terminal? I don't see a close button or something like that. Is there a way to add that? (like what do I do to add that?)

This is a terminal, for use by keyboard afficionados. Type the close
window shortcut, or type exit and press enter. Or type ctrl+d. Or if you
really must use the mouse, right click the titlebar to access the
control.

**Comment by RedDocMD** [comment]
Is there any real advantage of using native Wayland over XWayland, as far as Kitty is concerned?

**Comment by stellarexplosions** [comment]
> After updating to 0.20.0 today on Arch Gnome 40, My window decorations are gone, is this related? Is this a feature or a bug? Is there any way to bring them back in the config?
> ![Screenshot from 2021-04-19 19-19-45](https://user-images.githubusercontent.com/12999682/115256324-5cb2c580-a144-11eb-9adf-92fd3b9eaab4.png)
> 

Is there a way to change the white colour for window decoration?

**Comment by metal3d** [comment]
Yes, really, please, give us a way to come back to the Gnome title... I loved kitty because It was really easy to integrate with colors and font, but this white bar is very ugly here...
![image](https://user-images.githubusercontent.com/100080/115952035-3befc480-a4e4-11eb-9ebe-ccbf5e14772a.png)

**Comment by RedDocMD** [comment]
> They arent gone they are just not native. If you want native set linux_display_server to x11 in kitty.conf which was what it used to default to.

This is what I think you are looking for

**Comment by metal3d** [comment]
OK...
```
# in ~/.config/kitty.conf
linux_display_server x11
```
Sorry for this :) Didn't seen this comment

**Comment by slrtbtfs** [comment]
> Is there any real advantage of using native Wayland over XWayland, as far as Kitty is concerned?

The most visible advantage of using Wayland is the window properly scales on HiDPI screens.

When using Xwayland, kitty will look blurry if window scaling is enabled.

**Comment by stellarexplosions** [comment]
> > They arent gone they are just not native. If you want native set linux_display_server to x11 in kitty.conf which was what it used to default to.
> 
> This is what I think you are looking for @metal3d and @stellarexplosions

It works, but I want to keep using Wayland. I just want to change the color of window decoration from white to something dark. AFAIK in Wayland window decorations are implemented by compositor and Gnome's Mutter only implements CSD. Is there like a setting that i can use to override the window decoration color?


![image](https://user-images.githubusercontent.com/11005389/115980404-19c07a00-a5aa-11eb-93d6-8989d6f82375.png)

**Comment by kovidgoyal** [comment]
On Sat, Apr 24, 2021 at 09:18:22PM -0700, Faizal Musthafa wrote:
> > > They arent gone they are just not native. If you want native set linux_display_server to x11 in kitty.conf which was what it used to default to.
> > 
> > This is what I think you are looking for @metal3d and @stellarexplosions
> 
> It works, but I want to keep using Wayland. I just want to change the color of window decoration from white to something dark. AFAIK in Wayland window decorations are implemented by compositor and Gnome's Mutter only implements CSD. Is there like a setting that i can use to override the window decoration color?
> 
> 
> ![image](https://user-images.githubusercontent.com/11005389/115980404-19c07a00-a5aa-11eb-93d6-8989d6f82375.png)

There you go: https://github.com/kovidgoyal/kitty/commit/62656b24eb8a0e25610e2c37db9aa518098136f3

And man, GNOME is a gift that just keeps on giving!

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.touch_scroll_multiplier.

**Comment by topazus** [comment]
@Luflosi after setting `touch_scroll_multiplier 5.0` in Gnome Wayland, the problem of scrolling cursor mutiple line by the mouse wheel is solved. but I wonder that the configuration parameter said that it `Modify the amount scrolled by a touchpad.` not mouse wheel.

btw, Is there a way to get the window title to mid position
![image](https://user-images.githubusercontent.com/77263945/116070646-78c3e300-a6bf-11eb-8c79-ada5b571ec5f.png)

**Comment by Luflosi** [comment]
There are basically high precision and low precision scroll inputs. The two different config options are for each one respectively. High precision scroll inputs tell an application (kitty in this case) how many pixels to scroll, possibly with an accuracy better than one pixel. Low precision ones just tell the application how many lines to scroll (I think). Which input is high precision or low precision is determined by some part of the OS. I don't know the situation on Wayland but on macOS, all input devices I have encountered were reported as being high precision by the OS, no matter if it's a touch pad or a regular mouse with discrete "steps" in the scroll wheel. This is done because macOS provides scroll acceleration. The faster one scrolls, the more scrolling is accelerated. Scroll acceleration would not really be possible when the OS reports the device as being low precision.

@kovidgoyal needs to answer the question about the window title.

**Comment by kovidgoyal** [comment]
No you cant center the window title

**Comment by vdrandom** [comment]
I have this weird issue when opening more than one kitty instance on Gnome 40: csd becomes very glitchy, clicks go through, graphic artifacts galore when moving the window.

Same issue can be reprodced with Alacritty, so it may well be not kitty's problem, but in case there is a common bug, it might be worth investigating?

PS. Great job developing and maintaining kitty, btw! Innovating and improving on a standard as ancient as terminal emulator is very much commendable.

**Comment by kovidgoyal** [comment]
Doesn't happen for me on GNOME 40, with two kitty instances.

**Comment by vdrandom** [comment]
Interesting. Launching multiple instances of kitty via command line (or even gnome's Alt+F2) does not result in the same glitch. But if I launch them from the mutter launcher, the second, third and so on instance reliably results in glitchy csd behaviour.

Seems like a gnome bug, especially since the application file does not launch kitty in any different way, Exec=kitty. Sorry to bother.

**Comment by berkentekin** [comment]
> If you want
decorations with more functionality you would need to actually implement
it in wl_window.c. Possibly using something like libdecoration, or since
GNOME is the only window manager stupid enough to not implement server
side decorations, just directly use gtk libraries. 

Hey, this may be off-topic but as a novice (university sophomore) programmer I would like to work on this. I have a basic knowledge of C. What resources should I look into in order to learn how to implement libdecoration?

**Comment by kovidgoyal** [comment]
On Thu, Jul 22, 2021 at 09:23:59AM -0700, Berken Tekin wrote:
> > If you want
> decorations with more functionality you would need to actually implement
> it in wl_window.c. Possibly using something like libdecoration, or since
> GNOME is the only window manager stupid enough to not implement server
> side decorations, just directly use gtk libraries. 
> 
> Hey, this may be off-topic but as a novice (university sophomore) programmer I would like to work on this. I have a basic knowledge of C. What resources should I look into in order to learn how to implement libdecoration?

First understand how client side decorations are drawn in kitty (mostly
wl_client_side_decorations.c, wl_window.c and wl_init.c) then look at the libdecoration
examples/source code.

**Comment by kovidgoyal** [comment]
And note that libdecor doesn't actually do native decorations either, since GTK doesn't provide the needed hooks to do that. So while you will get some decorations with libdecor they wont be native. https://gitlab.gnome.org/jadahl/libdecor/-/issues/6

**Comment by berkentekin** [comment]
@kovidgoyal Thanks for your advice, I'll see what I can do.

**Comment by renatolfc** [comment]
> 
> On Sat, Apr 24, 2021 at 09:18:22PM -0700, Faizal Musthafa wrote: > > They arent gone they are just not native. If you want native set linux_display_server to x11 in kitty.conf which was what it used to default to. > > This is what I think you are looking for @metal3d and @stellarexplosions It works, but I want to keep using Wayland. I just want to change the color of window decoration from white to something dark. AFAIK in Wayland window decorations are implemented by compositor and Gnome's Mutter only implements CSD. Is there like a setting that i can use to override the window decoration color? ![image](https://user-images.githubusercontent.com/11005389/115980404-19c07a00-a5aa-11eb-93d6-8989d6f82375.png)
> There you go: [62656b2](https://github.com/kovidgoyal/kitty/commit/62656b24eb8a0e25610e2c37db9aa518098136f3) And man, GNOME is a gift that just keeps on giving!

Actually, this is quite useful on Windows with WSLg, since it uses Wayland under the hood. So thanks for implementing!

**Comment by rmader** [comment]
> And note that libdecor doesn't actually do native decorations either, since GTK doesn't provide the needed hooks to do that. So while you will get some decorations with libdecor they wont be native. https://gitlab.gnome.org/jadahl/libdecor/-/issues/6

Native GTK-like styling is planned for release 0.2 of libdecor, see https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/43

**Comment by hellosway** [comment]
I think client side decorations are not important, if gnome is detected, the titlebar could always be drawn, without any decorations, especialy since client side decorations is broken in a number of tilling wm, sticking to ssd works and looks native every where except gnome

**Comment by demizer** [comment]
Ugh. Suffered for many months with this issue in Gnome Wayland, just found the time to fix it and come to find out it is a Gnome problem... sigh... Thanks to @kovidgoyal for the excellent explanation of the problem and actively helping to make it better (within reason). This is excellently maintained software. Thank you.

I have encountered an additional problem of the CSD title bar becoming unclickable with the mouse if the window is resized or moved from screen to screen. The mouse clicks just pass through the title bar. I switched to xwayland and it's fixed. Hopefully proper support can land some day! I'll buy whomever makes that happen a nice dinner! :D

**Comment by kovidgoyal** [comment]
I dont have multiple screens to test with but resizing the window doesnt prevent right clicking on the title bar from working under GNOME for me.

**Comment by Svadkos** [comment]
I had the same problem with titlebar in gnome wayland, but I don't know what triggered it, because i rarely drag windows around.

**Comment by adamwojt** [comment]
Had same issue with white, minimal window after Updating to Ubuntu 22.04. It's incredible how much love and attention this library gets and how promptly issues are resolved. I want to thank you @kovidgoyal

**Comment by kovidgoyal** [comment]
You are welcome

**Comment by numToStr** [comment]
I am using KDE Plasma w/ Wayland and `hide_window_decorations yes` doesn't seem to have any effect. Is this also one of the wayland quirks?

**Comment by kovidgoyal** [comment]
On Sun, Jun 19, 2022 at 12:31:43AM -0700, Vikas Raj wrote:
> I am using KDE Plasma w/ Wayland and `hide_window_decorations yes` doesn't seem to have any effect. Is this also one of the wayland quirks?

yes, hide_window_decorations will only work when using client side
decorations. Plasma uses server side decorations, so you should
configure hiding of decorations there.

**Comment by noizo** [comment]
Thanks, i guess it did a trick.

**Comment by noizo** [comment]
And how about native wayland decorations? Just asking @kovidgoyal

**Comment by hrqmonteiro** [comment]
This was my first time using kitty with wayland on Gnome 42. And, i mean, wtf is this? Is this a joke?

We need to have the default gnome titlebars on it. All apps have it, even terminals (alacritty, wezterm, etc.)

This looks terrible as shit, come on...

![Screenshot from 2022-09-26 17-33-44](https://user-images.githubusercontent.com/17055027/192374615-689125d6-faf6-4f85-80aa-2d625bc60835.png)

**Comment by lukurde** [comment]
[libdecor (library for client-side decorators on Wayland) just merged support for using GTK decorators!](https://www.reddit.com/r/linux/comments/ymh5ob/libdecor_library_for_clientside_decorators_on/)

https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/43

**Comment by hykilpikonna** [comment]
After enabling `linux_display_server x11`, the close button shows but not the minimize/maximize buttons, which were present when I launch Gnome in X11. Is there a solution for this?

![image](https://user-images.githubusercontent.com/22280294/210193146-4d9ac6f6-f02c-4bea-a456-21ce1243b915.png)

**Comment by Jeoshua** [comment]
Honestly, I would be fine with this wayland windowing style if it would just respect dark mode. White sticks out like a sore thumb, and I just can't be the only terminal aficionado who feels this way.

**Comment by metal3d** [comment]
> Honestly, I would be fine with this wayland windowing style if it would just respect dark mode. White sticks out like a sore thumb, and I just can't be the only terminal aficionado who feels this way.

On Linux, you can read dbus as I did it in fyne.io project:
https://github.com/fyne-io/fyne/blob/develop/app/app_xdg.go#L36

And the theme change event:
https://github.com/fyne-io/fyne/blob/develop/app/app_xdg.go#L167

**Comment by kovidgoyal** [comment]
On Thu, Jan 12, 2023 at 01:13:28PM -0800, Jeoshua wrote:
> Honestly, I would be fine with this wayland windowing style if it would just respect dark mode. White sticks out like a sore thumb, and I just can't be the only terminal aficionado who feels this way.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.wayland_titlebar_color

**Comment by rdtorres** [comment]
> After enabling `linux_display_server x11`, the close button shows but not the minimize/maximize buttons, which were present when I launch Gnome in X11. Is there a solution for this?
> 
> ![image](https://user-images.githubusercontent.com/22280294/210193146-4d9ac6f6-f02c-4bea-a456-21ce1243b915.png)

Just press `alt` + `space` and gnome will open a context menu from where you can do all operations : close, maximize, minimize and etc.

![image](https://user-images.githubusercontent.com/1977787/228620332-4d565f70-ee51-40bd-9b31-71a56017b3d4.png)

**Comment by sharpenedblade** [comment]
https://github.com/glfw/glfw/issues/1639 was just merged, so `glfw` can show proper client side decorations that look somewhat native.

**Comment by AniAggarwal** [comment]
@kovidgoyal do you think it would be an easy addition to add an option to change or at least remove the cat emoji from the minimal decorations kitty is currently doing? 
Thanks again for the huge number of features you are constantly adding!

**Comment by hrqmonteiro** [comment]
> @kovidgoyal do you think it would be an easy addition to add an option to change or at least remove the cat emoji from the minimal decorations kitty is currently doing? Thanks again for the huge number of features you are constantly adding!

That cat emoji is just awful

**Comment by RushingAlien** [comment]
libdecor main branch now has a GTK plugin, so now it can draw gtk-based window decorations to wayland clients.
I think it's worth another look : https://gitlab.freedesktop.org/libdecor/libdecor

**Comment by volpan** [comment]
> After enabling `linux_display_server x11`, the close button shows but not the minimize/maximize buttons, which were present when I launch Gnome in X11. Is there a solution for this?
> 
> ![image](https://user-images.githubusercontent.com/22280294/210193146-4d9ac6f6-f02c-4bea-a456-21ce1243b915.png)

This should be controlled by `gnome-tweaks`

**Comment by rlees85** [comment]
Is there any way to minimize Kitty? Like a shortcut key? Google is coming up short - just brings me to this thread but I don't understand what Wayland decorations have to do with the ability to minimize. I use lots of apps that don't have normal decorations under Gnome Wayland yet Kitty is the only one that won't minimize.

@rdtorres posted an image above and you can see for yourself - no minimize option.

**Comment by baco** [comment]
> Is there any way to minimize Kitty? Like a shortcut key? Google is coming up short - just 

The official combination is `Super`+`h`. It is working for me. I also **don't** use the following in Kitty's config:
```conf
linux_display_server x11
```
under GNOME+Wayland

**Comment by MrGamerDoesGames** [comment]
Surprised that after two years this still isn't a thing, it's a basic feature and if it was a thing it'd be my favorite terminal. It doesn't mix with my desktop and my tiling extension seems to not like it.

**Comment by hrqmonteiro** [comment]
> Surprised that after two years this still isn't a thing, it's a basic feature and if it was a thing it'd be my favorite terminal. It doesn't mix with my desktop and my tiling extension seems to not like it.

The mantainers of this project are kind of a joke. I abandoned this terminal for Wezterm cause of this lack of very basic things.

**Comment by Octelly** [comment]
> > Surprised that after two years this still isn't a thing, it's a basic feature and if it was a thing it'd be my favorite terminal. It doesn't mix with my desktop and my tiling extension seems to not like it.
> 
> The mantainers of this project are kind of a joke. I abandoned this terminal for Wezterm cause of this lack of very basic things.

unfortunately ended up doing the exact same thing

**Comment by MrGamerDoesGames** [comment]
> If I were you I'd skip libdecoration entirely and just draw the titlebar using gtk libraries. Or better, stop using GNOME.

Telling someone to just "stop using GNOME" is... _interesting_ to say the least, especially coming from the owner of the project. Have you tried thinking before typing extra unnecessary words?

**Comment by kovidgoyal** [comment]
I have now heard enough comments from morons, this thread has become an unmitigated waste of my time. If somebody wants to waste their lives catering to the dictates of GNOME, open a PR with code implementing libdecor integration and we can discuss, otherwise stop wasting my time.
