### ISSUE TITLE
Pressing Ctrl+Enter creates odd escape code

### ISSUE THREAD

**Issue by rien333** [kovidgoyal/kitty#3285]
**Describe the bug**
All terminals (e.g. st, vte) and shells (e.g. bash, fish) normally don't display any escape codes when one presses <kbd>Ctrl</kbd> <kbd>Enter</kbd>. Kitty didn't do so either, at least until  recent changes to keyboard-related code. Specifically, kitty changed this behavior  in some commit after  0.19.3, given that this version doesn't have this problem (I'm on git master, btw).

**To Reproduce**
1. kitty --config NONE bash
2. Press "Ctrl + Enter"
3. You should see ";5u"

**Expected behavior**
I expect nothing to be printed.

**Environment details**
OS: Name and version of operating system(s)

```console
$ kitty --debug-config
kitty 0.19.3 (c60d3af60b) created by Kovid Goyal
Linux bummer 5.10.12-arch1-1-custom #1 SMP PREEMPT Wed, 03 Feb 2021 19:54:31 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: [reproducible with"--config NONE"]
Running under: X11
```

**Additional context**
I can  reproduce the problem with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
This is deliberate. https://github.com/kovidgoyal/kitty/issues/3248#issuecomment-765841345
