### ISSUE TITLE
[RFC] Animated images

### ISSUE THREAD

**Issue by kovidgoyal** [kovidgoyal/kitty#3287]
I have implemented support for displaying animated images in master. The
graphics protocol has been extended to allow both client and terminal driven
animations.  To try it out build from master and run:

   kitty +kitten icat some-animation.gif

The spec for the animation protocol is at https://sw.kovidgoyal.net/kitty/graphics-protocol.html#animation The changes to the spec are fully backwards compliant, they are pure extensions.

If any of you have feedback on the spec or implementation in kitty, comments are welcome.
This is slated for release in the next kitty version.

**Comment by therealadityashankar** [comment]
I wonder if its possible to get more creative via this API, like running an entire browser inside a terminal (I'd love that), or something similar

**Comment by j-james** [comment]
@therealadityashankar That exists, although not with Kitty's protocol: https://github.com/browsh-org/browsh

**Comment by therealadityashankar** [comment]
@j-james that's very....pixellated, kitty's protocol would definitely make it more beautiful

**Comment by therealadityashankar** [comment]
I found this article that makes it seem like its not very difficult,
https://webscraping.com/blog/Webpage-screenshots-with-webkit/
let me try it

**Comment by therealadityashankar** [comment]
so its much more complicated than that, I've never used pyqt before....but yeah the framework has evolved alot from when that page was created,
still gonna try it

but from what I understand I need https://doc.qt.io/qt-5/qtwebengine-index.html

**Comment by therealadityashankar** [comment]
this link, shows how to take a screenshot 
https://stackoverflow.com/questions/55231170/taking-a-screenshot-of-a-web-page-in-pyqt5

**Comment by bawr** [comment]
Hey! Sorry for being late to the RFC party.

One thing feels a bit weird at the moment - one convenient format for pixel data is PNG, and Kitty already supports this. Now that we're in 2021, APNG has surprisingly wide support for animated images, particularly useful if the differences between frames aren't too big. There's some general overlap between APNG features and the animation payload features - would we want to support this format for animation payloads, or just ignore this overlap?

It seems like it would be handy to transfer an APNG as one image and then refer to frames from that one file, but there's probably other considerations here, just wanted to see how you're thinking about this.

**Comment by kovidgoyal** [comment]
I'm not a very big fan of adding support for different image formats.
For instance, APNG as I understand it would require the terminal
emulator to use yet another library since libpng doesnt handle it
natively. The animation protocol already supports sending small
differences between frames as efficient deltas, so the only thing APNG
support buys you is the ability to display apng images relatively easily
without needing to use kitty +icat. And if we are going to add another
image format why APNG and not GIF?

I dont think the gain is worth the cost.

**Comment by bawr** [comment]
Yeah, I was a bit on the fence about this until your brought up libpng issues - if doesn't have builtin support, then there's really little gain to be had here, and not worth the headache. Seems like apng support squarely belongs somewhere in kitty +icat, and not at this layer, despite a small feature overlap. I'll take a look at a PR for +icat, then!

Just in the realm of me being nerd-sniped - my original thinking was that apng beats gif because you're not forced to use a palette and Kitty already has some png support, and technically you could already send an apng as png data already, given that it's just extra chunks for frames after the first one, so it wouldn't be as big of a leap... but yes, now I agree that a better answer is probably "neither".

**Comment by kovidgoyal** [comment]
icat should already support apng out of the box, provided that
ImageMagick supports it.
