### ISSUE TITLE
Number size tooltip

### ISSUE THREAD

**Issue by profawk** [kovidgoyal/kitty#3289]
Some terminal have an awesome feature: when you right click a number the context menu shows it converted to human readable form.
Kitty doesn't have a context menu but maybe we can add a tooltip so when right clicking a number it will show it's human readable approximation. 
for example if I were to run ls -al . I could right click on a file size and instead of
2659545227 the tooltip will say 2.47Gi 
like a -h flag but only when I choose and for programs that don't support that too

this feature is awesome and something I'm feeling is missing

**Comment by kovidgoyal** [comment]
What programs do you run that dont support human friendly output?? In
any case, you can easily accomplish this by customizing the hints kitten
as described here: https://sw.kovidgoyal.net/kitty/kittens/hints.html#completely-customizing-the-matching-and-actions-of-the-kitten

Simply have it match on numbers, press the key to select the number you
want and write handle_result() in your customized kitten to convert to
human readable form and paste the output into the terminal or opena  new
window showing the output, or copy it to clipboard or set the window
title to it, or whatever you like.
