### ISSUE TITLE
Kitty not pulling the configuration

### ISSUE THREAD

**Issue by mordax777** [kovidgoyal/kitty#3294]
**Describe the bug**
I was unsure where to create this ticket because I do not know where the problem is coming from. But I have the problem that when I start Kitty via my keybindings in sway, it does not pull the configuration. I noticed this because the terminal does not look like how I specified it in the configuration. While researching, I found three strange things. Firstly, if I set the path to my config file in my sway keybinding with `--config`, it did not change anything. Secondly, If I am in the terminal and use `kitty --debug-config`, I can see the configuration, which is not being applied. Thirdly, if I start a second kitty process from the existing terminal just by using `$ kitty`, the configuration gets pulled, and I see the changes from the configuration. I am not sure if it's either Sway, Kitty, or even my Fish shell making these problems.
 
**To Reproduce**
1. Configure something like this in your Sway config: `$hyper+Return exec kitty`
2. Customize your Kitty config
3. Press the keybinding to start the terminal

**Expected behavior**
The configuration should have been pulled.

**Screenshots**
When starting with Sway keyboard shortcut:
![image](https://user-images.githubusercontent.com/27705384/107197629-67d6d000-69f4-11eb-9b3d-54bb104d319d.png)

When started from terminal with `$ kitty`:
![image](https://user-images.githubusercontent.com/27705384/107197647-702f0b00-69f4-11eb-84b8-9f0ddf965f37.png)

**Environment details**
OS: Arch Linux x86_64
Kernel: 5.10.13-arch1-2
Shell: fish 3.1.2
WM: sway version 1.5.1

```
❯ kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Linux xps13-9300 5.10.13-arch1-2 #1 SMP PREEMPT Sat, 06 Feb 2021 11:07:29 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/aljaz/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
active_border_color     Color(red=146, green=131, blue=116)
allow_remote_control    y
background              Color(red=40, green=40, blue=40)
close_on_child_death    True
color0                  Color(red=40, green=40, blue=40)
color1                  Color(red=204, green=36, blue=29)
color10                 Color(red=184, green=187, blue=38)
color11                 Color(red=250, green=189, blue=47)
color12                 Color(red=131, green=165, blue=152)
color13                 Color(red=211, green=134, blue=155)
color14                 Color(red=142, green=192, blue=124)
color15                 Color(red=235, green=219, blue=178)
color2                  Color(red=152, green=151, blue=26)
color3                  Color(red=215, green=153, blue=33)
color4                  Color(red=69, green=133, blue=136)
color5                  Color(red=177, green=98, blue=134)
color6                  Color(red=104, green=157, blue=106)
color7                  Color(red=168, green=153, blue=132)
color8                  Color(red=146, green=131, blue=116)
color9                  Color(red=251, green=73, blue=52)
cursor                  Color(red=235, green=219, blue=178)
enable_audio_bell       False
font_size               9.0
foreground              Color(red=235, green=219, blue=178)
mouse_hide_wait         0.0
scrollback_lines        100000
touch_scroll_multiplier 20.0
```

**Additional context**
My Sway config:
<details><pre>
# Set font
font pango: Taskbar, Cantarell 9

input type:keyboard {
	xkb_layout de-hyper,de
	xkb_variant ,nodeadkeys
	xkb_numlock enable
}

input type:touchpad {
    natural_scroll enabled
    tap enabled
    dwt enabled
}

seat * hide_cursor 10000

output * {
    bg "#222222" solid_color
}

# Gaps
gaps inner 5
smart_gaps on

# Borders
default_border pixel 2
default_floating_border none
hide_edge_borders --i3 none

# Disable cursor jumping
mouse_warping none
focus_follows_mouse no

# Workspaces
workspace_layout tabbed
set $workspace1 workspace number 1
set $workspace2 workspace number 2
set $workspace3 workspace number 3
set $workspace4 workspace number 4
set $workspace5 workspace number 5
set $workspace6 workspace number 6
set $workspace7 workspace number 7
set $workspace8 workspace number 8
set $workspace9 workspace number 9
set $workspace0 workspace number 10

# Specific window configuration
for_window    [app_id=".*"]                                     sticky enable
for_window    [window_role="pop-up"]                            floating enable
for_window    [app_id="udiskie"]                                floating enable
for_window    [instance="signal"]                               move to scratchpad, resize set width 60ppt height 80ppt
for_window    [instance="jami-gnome"]                           move to scratchpad, resize set width 60ppt height 80ppt
for_window    [app_id="telegramdesktop"]                        move to scratchpad, resize set width 60ppt height 80ppt
for_window    [class="Brave-browser"]                           move container to $workspace2, title_format "Brave"
for_window    [class="jetbrains-idea"]                          move container to $workspace3, title_format "Idea"
for_window    [app_id="kitty"]                                  move container to $workspace4, title_format "Kitty"
for_window    [class="Spotify"]                                 move container to $workspace10, title_format "Spotify"
for_window    [title="meet.google.com is sharing your screen."] floating enable
for_window    [app_id="dmenu.*"]                                floating enable, resize set width 60ppt height 80ppt
for_window    [app_id="dmenu-browser"]                          resize set height 20ppt
for_window    [app_id="dmenu-calc"]                             resize set width 40ppt height 30ppt
for_window    [app_id="qalculate-gtk"]                          floating enable

# Color scheme (Gruvbox dark)
set $color_normal_white  #a89984
set $color_bright_white  #ebdbb2
set $color_normal_gray   #222222
set $color_bright_gray   #3c3836
set $color_bright_yellow #d79921
set $color_normal_black  #282828
set $color_unused        #ff0000

# Colors                  border                 background             text                   indicator            child_border
client.focused            $color_bright_gray     $color_bright_gray     $color_bright_white    $color_bright_gray   $color_normal_black
client.focused_inactive   $color_bright_gray     $color_bright_gray     $color_bright_white    $color_bright_gray   $color_normal_black
client.unfocused          $color_normal_gray     $color_normal_gray     $color_normal_white    $color_normal_gray   $color_normal_black
client.urgent             $color_bright_yellow   $color_bright_yellow   $color_normal_black    $color_unused        $color_unused
client.placeholder        $color_unused          $color_unused          $color_unused          $color_unused        $color_unused

# Use Windows and Hyper as a modifier keys
set $win Mod3
set $hyper Mod4

# Use Mouse+$hyper to drag floating windows to their wanted position
floating_modifier $hyper

set $mode_audio "Audio"
mode $mode_audio {
    bindsym --to-code {
        s            exec pacmd set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-speaker, mode "default"
        h            exec pacmd set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-headphones, mode "default"
        r            exec pacmd set-default-sink alsa_output.usb-Razer_Razer_Kraken_7.1_V2_00000000-00.analog-stereo, mode "default"
        c            exec pacmd set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo, mode "default"
        b            exec "bluetoothctl "disconn"ect 70:26:05:3C:56:A7; bluetoothctl connect 70:26:05:3C:56:A7", mode "default"
        Shift+b      exec bluetoothctl disconnect, mode "default"
        Shift+i      exec pacmd set-source-port alsa_input.pci-0000_00_1f.3.analog-stereo analog-input-internal-mic, mode "default"
        Shift+h      exec pacmd set-source-port alsa_input.pci-0000_00_1f.3.analog-stereo analog-input-headset-mic, mode "default"
        Shift+m      exec pacmd set-source-port alsa_input.pci-0000_00_1f.3.analog-stereo analog-input-mic, mode "default"

        # back to normal: Enter or Escape
        Return mode default
        Escape mode default
    }
}

set $mode_resize "Resize window"
mode $mode_resize {
    bindsym --to-code {
        h            exec swaymsg resize grow   left 10 || swaymsg resize shrink right 10
        Ctrl+h       exec swaymsg resize grow   left 1  || swaymsg resize shrink right 1
        j            exec swaymsg resize shrink up   10 || swaymsg resize grow   down  10
        Ctrl+j       exec swaymsg resize shrink up   1  || swaymsg resize grow   down  1
        k            exec swaymsg resize grow   up   10 || swaymsg resize shrink down  10
        Ctrl+k       exec swaymsg resize grow   up   1  || swaymsg resize shrink down  1
        l            exec swaymsg resize shrink left 10 || swaymsg resize grow   right 10
        Ctrl+l       exec swaymsg resize shrink left 1  || swaymsg resize grow   right 1

        # back to normal: Enter or Escape
        Return mode default
        Escape mode default
    }
}

set $mode_system "System exit"
mode $mode_system {
    bindsym --to-code {
        e exec sway-exit exit, mode "default"
        l exec sway-exit lock, mode "default"
        s exec sway-exit suspend, mode "default"
        r exec sway-exit reboot, mode "default"
        h exec sway-exit shutdown, mode "default"

        # back to normal: Enter or Escape
        Return mode default
        Escape mode default
    }
}

set $mode_workspaces_monitors "Move workspace between monitors"
mode $mode_workspaces_monitors {
    bindsym --to-code {
        h exec swaymsg move workspace to output left, mode "default"
        l exec swaymsg move workspace to output right, mode "default"

        # back to normal: Enter or Escape
        Return mode default
        Escape mode default
    }
}

bindsym --to-code {
    # Terminal
    $hyper+Return exec kitty
    $win+Return exec kitty --config NONE
    $win+Shift+Return exec kitty --config NONE /bin/bash

    # Launcher
    $hyper+plus     exec bash -c "pkill -x qalculate-gtk || qalculate-gtk"
    $hyper+d        fullscreen disable, exec wofi
    $hyper+p        fullscreen disable, exec "wl-clipboard-manager lock; gopass ls --flat | wofi --dmenu | xargs --no-run-if-empty gopass show -c; wl-clipboard-manager unlock"
    $hyper+u        fullscreen disable, exec "wl-clipboard-manager lock; gopass ls --flat | wofi --dmenu | xargs -I _ --no-run-if-empty gopass show -c _ username; wl-clipboard-manager unlock"
    $hyper+a        fullscreen disable, exec "wl-clipboard-manager lock; ykman oath list | wofi --dmenu | xargs -I _ --no-run-if-empty ykman oath code _ -s | wl-copy; wl-clipboard-manager unlock"
    $hyper+m        fullscreen disable, exec udiskie-dmenu
    $win+grave      fullscreen disable, exec wl-clipboard-manager dmenu
    Print           exec sway-screenshot-area
    $hyper+Print    exec sway-gif-area
    $win+Print      exec sway-screenshare
    $hyper+n        fullscreen disable, exec "pgrep -x dmenu && pkill dmenu || networkmanager_dmenu"

    # Kill focused window
    $win+q kill

    # Change focus
    $hyper+h focus left
    $hyper+j focus down
    $hyper+k focus up
    $hyper+l focus right

    # Move focused window
    $win+h move left
    $win+j move down
    $win+k move up
    $win+l move right

    # Enter fullscreen mode
    $hyper+f fullscreen

    # Container layout: split
    $hyper+e layout toggle split

    # Container layout: tabbed
    $hyper+w layout tabbed

    # Split
    $hyper+s split toggle

    # Focus the parent container
    $hyper+c focus parent

    # Focus the child container
    $hyper+i focus child

    # Toggle tiling / floating
    $win+space floating toggle

    # Make the currently focused window a scratchpad
    $win+period move scratchpad

    # Show the first scratchpad window
    $hyper+period scratchpad show

    # Change focus between tiling / floating windows
    $hyper+space focus mode_toggle

    # Notification actions
    $hyper+q exec makoctl dismiss
    $hyper+o exec makoctl menu dmenu

    # Brightness control
    XF86MonBrightnessUp         exec light -A 1%
    XF86MonBrightnessDown       exec light -U 1%
    Shift+XF86MonBrightnessUp   exec light -A 5%
    Shift+XF86MonBrightnessDown exec light -U 5%

    # Media control
    XF86AudioPlay exec playerctl --player playerctld play-pause
    XF86AudioNext exec playerctl --player playerctld next
    XF86AudioPrev exec playerctl --player playerctld previous
    $hyper+Up     exec playerctl --player playerctld play-pause
    $hyper+Down   exec playerctl --player playerctld play-pause
    $hyper+Left   exec playerctl --player playerctld previous
    $hyper+Right  exec playerctl --player playerctld next

    XF86AudioMute        exec pamixer -t
    XF86AudioRaiseVolume exec pamixer -i 5
    XF86AudioLowerVolume exec pamixer -d 5
    $win+Up              exec pamixer -t
    $win+Down            exec pamixer -t
    $win+Right           exec pamixer -i 5
    $win+Left            exec pamixer -d 5
    $win+Shift+Up        exec pamixer -t --source alsa_input.pci-0000_00_1f.3.analog-stereo
    $win+Shift+Down      exec pamixer -t --source alsa_input.pci-0000_00_1f.3.analog-stereo
    $win+Shift+Right     exec pamixer -i 5 --source alsa_input.pci-0000_00_1f.3.analog-stereo
    $win+Shift+Left      exec pamixer -d 5 --source alsa_input.pci-0000_00_1f.3.analog-stereo

    # Reload the configuration file
    $win+r reload

    # Switch to workspace using number row
    $hyper+1 $workspace1
    $hyper+2 $workspace2
    $hyper+3 $workspace3
    $hyper+4 $workspace4
    $hyper+5 $workspace5
    $hyper+6 $workspace6
    $hyper+7 $workspace7
    $hyper+8 $workspace8
    $hyper+9 $workspace9
    $hyper+0 $workspace0

    # Switch to workspace using keypad
    $hyper+KP_1 $workspace1
    $hyper+KP_2 $workspace2
    $hyper+KP_3 $workspace3
    $hyper+KP_4 $workspace4
    $hyper+KP_5 $workspace5
    $hyper+KP_6 $workspace6
    $hyper+KP_7 $workspace7
    $hyper+KP_8 $workspace8
    $hyper+KP_9 $workspace9
    $hyper+KP_0 $workspace0

    # Move window to workspace using number row
    $win+1 move container to $workspace1
    $win+2 move container to $workspace2
    $win+3 move container to $workspace3
    $win+4 move container to $workspace4
    $win+5 move container to $workspace5
    $win+6 move container to $workspace6
    $win+7 move container to $workspace7
    $win+8 move container to $workspace8
    $win+9 move container to $workspace9
    $win+0 move container to $workspace0

    # Move window to workspace using keypad
    $win+KP_1 move container to $workspace1
    $win+KP_2 move container to $workspace2
    $win+KP_3 move container to $workspace3
    $win+KP_4 move container to $workspace4
    $win+KP_5 move container to $workspace5
    $win+KP_6 move container to $workspace6
    $win+KP_7 move container to $workspace7
    $win+KP_8 move container to $workspace8
    $win+KP_9 move container to $workspace9
    $win+KP_0 move container to $workspace0

    # Modes
    $win+a mode $mode_audio
    $hyper+r mode $mode_resize
    $win+e mode $mode_system
    $win+m mode $mode_workspaces_monitors
}

exec_always "pgrep -x signal-desktop || signal-desktop"
exec_always "pgrep -x telegram-desktop || telegram-desktop"

# Load systemd integration
include /etc/sway/config.d/*
exec systemctl --user start sway-session.target
</pre></details>

**Comment by kovidgoyal** [comment]
Works fine for me in sway. Most likely you have different values for
either XDG_CONFIG_HOME, XDG_CONFIG_DIRS or KITTY_CONFIG_DIRECTORY in the
two environments. Remeber that env vars you set in your users shell rc
files may not actually be present in the window managers environment.
Instead put the env vars in /etc/profile or similar system wide
locations.

**Comment by mordax777** [comment]
Hello @kovidgoyal 
I have set `XDG_CONFIG_HOME` to:
```
❯ printenv | grep XDG_CONFIG_HOME
XDG_CONFIG_HOME=/home/aljaz/.config
```

`XDG_CONFIG_DIRS` and `KITTY_CONFIG_DIRECTORY` are empty:
```
❯ printenv | grep XDG_CONFIG_DIRS

❯ printenv | grep KITTY_CONFIG_DIRECTORY

```

**Comment by kovidgoyal** [comment]
Yes, the question is *where* have you set it. Set it system-wide.

**Comment by mordax777** [comment]
I use the combination of `systemd environment.d` and a `fish` config.
In my `environment.d` folder I have a `20-xdg.conf` file:
```
XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
XDG_CACHE_HOME=$HOME/.cache
```

In my `fish` config I have:
```
for line in (systemctl --user show-environment)
    set key (echo "$line" | cut -d '=' -f 1)
    set value (echo "$line" | cut -d '=' -f 2- | tr -d \$\')
    set -g -x "$key" "$value"
end

set -g -x GPG_TTY "$TTY"
set -g -x SSH_AUTH_SOCK "$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh"
systemctl --user import-environment GPG_TTY SSH_AUTH_SOCK

# Running from tty1 start sway
set TTY1 (tty)
if test -z "$DISPLAY"; and test $TTY1 = "/dev/tty1"
	systemd-cat -t sway sway
	systemctl --user stop sway-session.target
end
```

I loop over all environment.d entries and import them into my fish shell via `set -g -x`

**Comment by mordax777** [comment]
@kovidgoyal Do you think fish is not pulling my environment variables in?

**Comment by kovidgoyal** [comment]
sway is important here not fish. you are running kitty from sway, so
what environment sway sees is important.

**Comment by mordax777** [comment]
@kovidgoyal but if you take a look at the above solution that I use for my environment variables, you think this does not work properly with sway? Is there a way to check which environment variables are set for sway to see?

**Comment by kovidgoyal** [comment]
No, idea, I dont use sway.

**Comment by kovidgoyal** [comment]
If I were you I'd just create a wraper script to run kitty

```
#!/bin/sh
exec kitty --config /full/path/to/kitty.conf
```

and run that in your sway bindings

**Comment by mordax777** [comment]
@kovidgoyal I would like to try avoiding a workaround for this.
I double checked it, Sway is successfully pulling my environment variables, since I have another application which relays on a variable works just fine.

**Comment by kovidgoyal** [comment]
nope, relevant code is here: https://github.com/kovidgoyal/kitty/blob/master/kitty/constants.py#L47

**Comment by mordax777** [comment]
@kovidgoyal I found out that it is for sure have to do something with fish, because if I start kitty from my sway keybindings with `kitty /bin/bash`, the kitty configuration is getting pulled.

**Comment by mordax777** [comment]
I took the function and ran it manually, in a similar way how I would start Kitty. It pulls the environment variables and builds the config file path correctly. Since I am in a bit of a dead end I think I am taking this issue to fish, maybe they can help me there.
