### ISSUE TITLE
Powerline font in prompt causes command to not wrap

### ISSUE THREAD

**Issue by dankox** [kovidgoyal/kitty#3295]
Hi,
I might be missing something or have some weird setup, but I cannot make powerline work in kitty without an issue of command not wrapping.

When I type command (or text in general) in the terminal with prompt from powerline, it will "wrap" a bit earlier than the end of line and it starts to overwrite the same line again.    
I found that colors have to be enclosed correctly `\[color\]` to not count towards line length (this was causing the same issue for me before), but when installing powerline and using it directly it adds `\xee82b0` characters and I guess that's causing the problem again.     
It should be the arrow character. It is displayed correctly, but the wrapping stops working. I can see that people are using it, so maybe there is something wrong on my system.

**To Reproduce**
This is minimal setup required for me to reproduce it:

Prompt setup (although the character is not visible here, it's visible in kitty):
```
PS1="my_comp\W $ "
```

1. run `kitty --config NONE -o "symbol_map=U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols" --debug-font-fallback /usr/local/bin/bash`
2. type long text/command
3. overwriting the current line as visible on the screenshot

**Expected behavior**
Not overwriting the same line.

**Screenshots**
![image](https://user-images.githubusercontent.com/39275087/107218871-877bf180-6a10-11eb-9bea-6ea62210735a.png)

**Environment details**
OS: macOS Big Sur 11.2

Here is kitty config, although the example shows the run without config

```
Output of kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Darwin XXXX.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2 BuildVersion:	20D64
Loaded config files: /Users/xxxx/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control               y
background                         Color(red=18, green=18, blue=18)
color0                             Color(red=27, green=29, blue=30)
color1                             Color(red=249, green=38, blue=114)
color10                            Color(red=190, green=237, blue=95)
color11                            Color(red=230, green=219, blue=116)
color12                            Color(red=51, green=147, blue=239)
color13                            Color(red=158, green=111, blue=254)
color14                            Color(red=163, green=186, blue=191)
color15                            Color(red=248, green=248, blue=242)
color2                             Color(red=166, green=226, blue=46)
color3                             Color(red=253, green=151, blue=31)
color4                             Color(red=51, green=147, blue=239)
color5                             Color(red=158, green=111, blue=254)
color6                             Color(red=94, green=113, blue=117)
color7                             Color(red=204, green=204, blue=198)
color8                             Color(red=80, green=83, blue=84)
color9                             Color(red=255, green=102, blue=157)
cursor                             Color(red=187, green=187, blue=187)
enable_audio_bell                  False
env                                {'COLORTERM': 'truecolor'}
font_size                          12.0
foreground                         Color(red=160, green=160, blue=160)
macos_quit_when_last_window_closed True
selection_background               Color(red=69, green=58, blue=57)
selection_foreground               Color(red=18, green=18, blue=18)
shell                              /usr/local/bin/bash
symbol_map                         {(57504, 57507): 'PowerlineSymbols', (57520, 57523): 'PowerlineSymbols'}
tab_bar_edge                       1
tab_bar_style                      powerline
window_padding_width               FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
```

**Additional context**
When I was trying to change the prompt to somehow ignore the length of the special character like this
```
PS1="my_comp\[\] \W $ "
```
it starts to "work" to certain extent. It was missing one character from the full text, but it was wrapping correctly and looked more or less ok.

**Comment by kovidgoyal** [comment]
Works fine for me with that PS1 and bash. Wrapping is controlled by the
shell, not the terminal. Most likely your versions of bash or
readline/libedit (which is what bash delegates prompts too) 
are too old or dont like that character. Try updating.

**Comment by dankox** [comment]
Thanks for the reply. 

I've updated bash recently because of kitty:
```
~ $ /usr/local/bin/bash --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin20.2.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I found out how to check readline for bash, on macos it should be linked statically:
```
~ $ gdb -quiet -ex 'print /x (int) rl_readline_version' -ex 'quit' /usr/local/bin/bash
Reading symbols from /usr/local/bin/bash...
(No debugging symbols found in /usr/local/bin/bash)
$1 = 0x801
```
Which should mean, that the version is `8.02`.

However, I found out, that when I start `kitty` from `iterm2` or from `Terminal.app`, it works nicely. But if I start it from Finder, it behaves as described above.    
I could live with this workaround, but I'm curious, if you don't have an idea what could be the cause in such case or where to look (some system setup?). If not, no worries, thanks anyway.

**Comment by kovidgoyal** [comment]
Will most likely be locale variables in that case. Check the differences
in env output in the two cases. You can set locale variables using the
env directive in kitty.conf.

**Comment by dankox** [comment]
You are totally right. Setting `env LC_CTYPE=UTF-8` in `kitty.conf` worked like a charm.

Thanks a bunch for your help and awesome work on the app. Have a nice day.
