### ISSUE TITLE
toggle_maximized not working

### ISSUE THREAD

**Issue by shaeinst** [kovidgoyal/kitty#3301]
**option to maximize/minimize a window not working**
i tried to map my alt with m ike:
`map alt+m toggle_maximized`
but it make no difference. i also tried with opter key, but no luck.
i think option "toggle_maximized" is not working

**Comment by kovidgoyal** [comment]
Works fine for me. Note that whether it works or not depends on whether
the window manager you are using honors the request or not. For example,
many tiling wndow managers do not.

**Comment by shaeinst** [comment]
i use DWM. tilix has this same feature and it works fine on it.

**Comment by kovidgoyal** [comment]
Sorry I've never used DWM so cant really help with that. kitty's maximize function uses glfw maximize function, which in turn on X11 use NET_WM_STATE. The window manager has to honor that. See line 2234 onwards in glfw/x11_window.c
