### ISSUE TITLE
configure like Tilix

### ISSUE THREAD

**Issue by shaeinst** [kovidgoyal/kitty#3302]
i am migrating from Tilix to kitty. and want some features/configs same as tilix to kitty.

**1. Ask before closing the window if there are process running**
i use alt+esc to close a window. because of my  habit, sometime i press alt+esc while editing on vim which kills current window, so to protect this i want to configure it in such way, it should ask for confirmation to close if any process is running.

**2. Open new tiled window in left/down direction**
i want  alt+left and alt+down  to open new tiled window in left and down side of current window 

**3. configure color**
i want to change the color of host/user/location/....etc

**4. disable all default map**
i want to disable all default key maps

i actaully read the doc. but i was unable to find soultions,

**Comment by SolitudeSF** [comment]
1. https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close

3. this is controlled by your shell prompt, not terminal
4. You can use the special action no_op to unmap a keyboard shortcut that is assigned in the default configuration:
```
map kitty_mod+space no_op
```

**Comment by Luflosi** [comment]
4. See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.clear_all_shortcuts

**Comment by shaeinst** [comment]
@SolitudeSF 1 and 2 are still not working

1. i maped like this:
`map alt+right launch --location=vsplit 
map alt+down launch --location=hsplit  
`
but pressing any of alt+right and alt+left gives same reasult. i.e it first opens window on horizontal and then on vertical

2. it only ask for confirmation on the basic of how many (tiled) windows are opened. but i want it on basic of process running.
suppose i have "htop application" running on a window, then when i try to close this window, it should ask for confirmation because some process are still running (htop, in this case)

**Comment by shaeinst** [comment]
1st one is  solved by placing this on my ~/.config/kitty/kitty.conf 
`enabled_layouts splits:split_axis=vertical`

**Comment by shaeinst** [comment]
also, how to map so that it will only change font of focused window
i tried with this
`map ctrl+equal change_font_size current +1.0`
but this changes font size of all splited/tiled windows, i only want to change for focused one

**Comment by kovidgoyal** [comment]
font sizes can be changed only per OS window. As is noted in the
documentation for change_font_size. Someday I might lift that
restriction, but given its a fair bit of work, its not a priority.

**Comment by shaeinst** [comment]
it only ask for confirmation on the basic of how many (tiled) windows are opened. but i want it on basic of process running.
suppose i have "htop application" running on a window, then when i try to close this window, it should ask for confirmation because some process are still running (htop, in this case)

and how to achive this?

**Comment by kovidgoyal** [comment]
There is always a process running for a window to be open. if no process
ws running, the window would close automatically.

**Comment by shaeinst** [comment]
i think you didn't get me.
let me explain,
i have config like this=>
```
map alt+esc close_window
confirm_os_window_close 1
```
which only ask for confirmation if there is opened atleast two tilled window.
but what i am asking is, if i have any process/command is running (suppose i have vim running) then if i press alt+esc .then it should ask for confirmation

**Comment by kovidgoyal** [comment]
yes, I got you. You always have some process running, namely your shell.
What you are asking is for kitty to detect when the foreground process
is not a shell and only count windows that have non-shells in them.
However, there is no robust way to detect if a program is a shell or
not.

**Comment by shaeinst** [comment]
but tilix has this feature.

**Comment by kovidgoyal** [comment]
If it has it, then it will be implemented in a non-robust manner. There
is literally no way to know this information robustly, just think of
running over ssh as the extreme case.

**Comment by shaeinst** [comment]
here is how tilix has implemented it. https://github.com/gnunn1/tilix/blob/de490e7de61e096f122510eddbf9257aa2b0730f/source/gx/tilix/closedialog.d#L65
