### ISSUE TITLE
Combined Unicode input? (ctrl-shift-u)

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3306]
As a contributor to Unicode, I find myself using Kitty's nice Ctrl+Shift+U feature a lot.

However, I find it annoying how it's artificially split into Code / Name / Emoji. (Favorites are fine I guess.)

(Doubly annoying due to my disability. I find F&#x200C;_n_ keys difficult to reach. Short arms&mdash;congenital deformity.)

I think that at least «Code» and «Name» can be easily combined. Perhaps the default tab should be a combined search, where if the first two characters are "U+" or "u+" it's a codepoint search, and if it's anything else it's a name search. Really, I think it's fine to even say that if first char is "+" alone it's a codepoint search. "+" doesn't exist in any character name.

I find "U+" or "+" much easier to input than F1/F2. (My laptop also has a `fn` key, making it even harder on me.)

Happy to contribute this, doubt it'd be hard, if you accept the motivation behind contribution

**Comment by kovidgoyal** [comment]
You are welcome to add searching by code for names starting with plus to
the name tab.
