### ISSUE TITLE
Black padding at the edges

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#331]
I see that when character size does not fit window size, kitty adds black padding. This padding is very visually distinct in my case, as I use semi-transparent background with background color set via escape sequence. Is it possible to make this padding have same transparency and color as the main window? If not, can it be made fully transparent so that visually it wouldn't be conceived as part of the window?

If you're not interested in adding such feature, can you please at least point me to the relevant place in the code so that I could try to hack it myself?
Thanks!

**Comment by kovidgoyal** [comment]
Dup of #323
