### ISSUE TITLE
Suggestion for a new icon

### ISSUE THREAD

**Issue by hristost** [kovidgoyal/kitty#3310]
Hello! I use kitty a lot and took the time to sketch a new icon that fits better among other apps I use. It is a _kitty_ sitting on  a [ADM-3A](https://en.wikipedia.org/wiki/ADM-3A) terminal's keyboard.

I've licensed it under the same license as kitty, so you are free to merge it if you wish. Currently, I only have it as an `.afdesign` source file, but I'm happy to try exporting to something more accessible if more people are interested.

![Proposed icon](https://raw.githubusercontent.com/hristost/kitty-new-icon/main/screenshot_new.png)

Here is a link to the repository: <https://github.com/hristost/kitty-new-icon>

**Comment by kovidgoyal** [comment]
Thanks, looks cool. However, as I have explained elsewhere, the kitty
logo has special significance for me. I drew it when my cat of 9 years
went missing, as a tribute. As such I am not going to change it. 

But I will say your version is my favorite alternative logo so far :)

**Comment by kabouzeid** [comment]
I actually love the current kitty icon! Only thing I would change for macOS is putting it inside of a squircle to match the Big Sur style :)

**Comment by kabouzeid** [comment]
<img width="873" alt="Bildschirmfoto 2021-04-09 um 2 43 07 PM" src="https://user-images.githubusercontent.com/7303830/114181531-e8a54000-9941-11eb-8c4a-1e119c20e229.png">

I tried out an automated tool for this (https://github.com/rikumi/iconsur), fits much better already :)

**Comment by kovidgoyal** [comment]
You are welcome to send a PR to change the icon on macOS to one inside a squircle. First add a kitty-macos.svg icon with the squircle in logo/. Then modify logo/make.py to use it to generate kitty.iconset. That should be all you need to do.

**Comment by yduman** [comment]
The current Big Sur icon is a little bit too large. If there is a way to shrink it a little bit, I would try to help. 
<img width="430" alt="kitty-icon" src="https://user-images.githubusercontent.com/11931774/116787232-5bb65800-aaa3-11eb-9101-83aaaac678a0.png">

**Comment by Luflosi** [comment]
This has already been fixed, see #3547.

**Comment by yduman** [comment]
Missed that one, thank you @Luflosi ! I suppose I have to wait for a new release then. I'm on v0.20.2.

**Comment by samholmes** [comment]
So it the icon never going to get a revision because of the sentimental aspect to the current one? No offense, but at some-point a professionally designed logo will help with the marketability and brand for this open source project.

**Comment by glensc** [comment]
you can change the icon yourself:
- https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon
