### ISSUE TITLE
Unicode 7.0 text characters aren't displayed / too wide 

### ISSUE THREAD

**Issue by schokotets** [kovidgoyal/kitty#3312]
I am experiencing an issue similar to #2677 : If I paste
```
echo '🅾  '
```
into the terminal, with a space removed each line, it renders like this:

![image](https://user-images.githubusercontent.com/13350549/107849064-e66aad80-6df8-11eb-89e7-10890dc40a8a.png)

So it looks like the character renders 5 fields wide if the space is available. If not, it's chopped off at the end.

It still happens with `kitty --config NONE`. Both the `Noto Color Emoji` and the `Twemoji` (as in screenshot) fonts are installed on my linux (Arch Manjaro X11 i3) system. When running with `kitty --debug-font-fallback`, I can see that the characters are coming from these fonts.

There are also issues with all the V7.0 emoji when `Default_Emoji_Style` (the second column of the [emoji list](https://www.unicode.org/Public/emoji/1.0//emoji-data.txt)) is `text`. You can try for your own using the following command:
```
curl -s https://www.unicode.org/Public/emoji/1.0//emoji-data.txt | grep V7
```
whose last lines render like this for me:

![image](https://user-images.githubusercontent.com/13350549/107849183-dbfce380-6df9-11eb-877d-d67b7556e783.png)

The issue may be in apparent in Emoji v7 emojis because many of them have `Default_Emoji_Style` `text`. Other Emoji with the same `Default_Emoji_Style` `text` are also not rendered. However, when viewing the file in a browser, my system is able to display the characters properly.

I modified the `kitty/kitty_tests/fonts.py` test so the `render_string` argument and `text` variable contain the extra 🅾 character and the test still succeeds. `wcwidth(ord("🅾"))` is `1`. So I assume the `wcwidth` function not to be the issue, or is a wrong one used?

Any ideas?

**Comment by kovidgoyal** [comment]
Works fine for me, what version of kitty? What operating system?

**Comment by schokotets** [comment]
I'm running
- kitty v0.19.3 (from pacman or current github master branch, both show the issue)
- Linux 5.10.7-3-MANJARO
- i3 (no compositor)

**Comment by kovidgoyal** [comment]
Same system as I am using. What does

kitty --debug-font-fallback sh -c "echo '🅾  '; read"

print

**Comment by schokotets** [comment]
funny that we're using the same system :)
```
[044 14:37:51.659720] Preloaded font faces:
[044 14:37:51.659764] normal face: /home/moritz/.local/share/fonts/JetBrainsMono-Regular.ttf:0
[044 14:37:51.659779] bold face: /home/moritz/.local/share/fonts/JetBrainsMono-ExtraBold.ttf:0
[044 14:37:51.659797] italic face: /home/moritz/.local/share/fonts/JetBrainsMono-Italic.ttf:0
[044 14:37:51.659808] bi face: /home/moritz/.local/share/fonts/JetBrainsMono-Bold-Italic.ttf:0
[044 14:37:51.765308] Failed to enable transparency. This happens when your desktop environment does not support compositing.
U+1f17e Face(family=Twemoji, style=Regular, ps_name=Twemoji, path=/usr/share/fonts/twemoji/twemoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

**Comment by kovidgoyal** [comment]
I have 
[044 18:57:39.368529] /usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf:0
U+1f17e Face(family=Noto Sans CJK JP, style=Regular, ps_name=NotoSansCJKjp-Regular, path=/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc, index=0, is_scalable=True, has_color=False, ascender=1160, descender=-288, height=1448, underline_position=-150, underline_thickness=50, strikethrough_position=325, strikethrough_thickness=50) (new face)
U+1f17e Face(family=Noto Sans CJK JP, style=Regular, ps_name=NotoSansCJKjp-Regular, path=/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc, index=0, is_scalable=True, has_color=False, ascender=1160, descender=-288, height=1448, underline_position=-150, underline_thickness=50, strikethrough_position=325, strikethrough_thickness=50)

try installing noto-cjk

**Comment by schokotets** [comment]
Yes, this fixes the display of the 🅾 character.
However, this fix only bypasses the use of the `Noto Color Emoji` or `Twemoji` fonts.
I still have isses with other Emoji V7.0 characters, like the printer emoji: 🖨
This one is rendered invisibly because - I assume - the top part that is rendered (as I experienced with the 🅾 character) is empty for this emoji.

When running `kitty --debug-font-fallback sh -c "echo '🖨 '; read"` I get:
```
U+1f5a8 Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

There must be an underlying issue.

**Comment by kovidgoyal** [comment]
Install symbola you will be fine.

**Comment by schokotets** [comment]
Well, I prefer the look of the other emoji fonts, which do produce many unicode characters correctly, just not a select few. `gnome-terminal` for example renders the characters correctly. Some time, I might dig deeper into `kitty`'s codebase to find where in the code the issue is caused.

**Comment by kovidgoyal** [comment]
That's not an emoji you are rendering, its the text presentation. The printer character has default text presentation. The emoji variant will be selected by following it with u+feof the emoji variation selector, and when you do that kitty will automatically use noto emoji for it. Install symbola and run

kitty python -c "print(''.join(map(chr, (0x1f5a8, 0x20, 0x1f5a8, 0xfe0f)))); input()" 

And you will see both variants perfectly renderd. If gnome-terminal is rendering that charaacter using noto emoji that is a bug in gnome terminal.
