### ISSUE TITLE
Open and close kitty result into segfault error in libxkbcommon.so.0.0.0

### ISSUE THREAD

**Issue by hooltoo** [kovidgoyal/kitty#3316]
See also: https://github.com/xkbcommon/libxkbcommon/issues/212

**Describe the bug**
I open/close many kitty terminal through sway hotkey {META+BACKSPACE} {META+Q} kitty crash,
to reproduce the following behaviour.

Feb 14 16:27:24 kernel: kitty[4868]: segfault at 80 ip 000077ac428aad00 sp 00007fffe76d1988 error 4 in libxkbcommon.so.0.0.0[77ac42891000+1c000]
Feb 14 16:35:52 kernel: kitty[5370]: segfault at 80 ip 0000721c9b882d00 sp 00007fffa09a12d8 error 4 in libxkbcommon.so.0.0.0[721c9b869000+1c000]
Feb 14 18:57:12 kernel: kitty[12684]: segfault at 80 ip 00007f8c617f5d00 sp 00007ffc70e6faa8 error 4 in libxkbcommon.so.0.0.0[7f8c617dc000+1c000]
Feb 14 18:57:13 kernel: kitty[12714]: segfault at 80 ip 00007f2455e59d00 sp 00007fff011e4848 error 4 in libxkbcommon.so.0.0.0[7f2455e40000+1c000]

I only got this but sway is also unresponsible. I have to restart the system.

**To Reproduce**
1. run sway
2. launch kitty terms by sway hotkey
3. close kitty terms by sway hotkey
4. kitty / sway crash, can't recover window manager

**Environment details**
OS: debian testing (bullseye) 
Linux 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
kitty-0.19.3-1
sway-1.5-7
libxkbcommon0-1.0.3-2

video output tested:
nouveau, radeon and amdgpu all crash.

```
kitty 0.19.3 created by Kovid Goyal
Linux 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64
Debian GNU/Linux bullseye/sid \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/user/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
font_size             9.0
update_check_interval 0.0
```

**Additional context**
The "Running under: X11" is misleading. I run sway with wayland only (xwayland disable).
It's my first bug report maybe someone could lead me what i can do more to resolve. I try to gdb and trace but the problem is i have to start many kitty terms and find the one who segfault.

**Comment by kovidgoyal** [comment]
What does this have to do with kitty? If your GPU drivers and window
manager are crashing your problem is in a layer much lower than an
application program.
