### ISSUE TITLE
How do I enable bold is bright option in kitty.conf? 

### ISSUE THREAD

**Issue by onlyvip** [kovidgoyal/kitty#3318]
I could not find bold is bright option in the Kitty documentation. And I want bold to have different colour a than normal. My colour theme has the necessary config but the kitty config isn't enabled for bold is bright so please help how do I enable bold is bright.

**Comment by kovidgoyal** [comment]
dup of #197

**Comment by onlyvip** [comment]
I read it all and I'm super confused. What should i change  to get bright bold according to you?  What's sgr color aixterm? How do I use sgr color format in my color theme? Please make it simple.
I know you closed this and I have read all the relevant info you have in #197 but still in super confused.
So please guide me how do I do it the right way according to you.

**Comment by Luflosi** [comment]
This is purposefully not possible in kitty. It is a bad design that would make it impossible for programs to rely on one behaviour or the other.

**Comment by onlyvip** [comment]
> This is purposefully not possible in kitty. It is a bad design that would make it impossible for programs to rely on one behaviour or the other.

Ok thanks for replying.

**Comment by slezica** [comment]
Third issue I read trying to find the solution to this (eg https://github.com/kovidgoyal/kitty/issues/197). That's ok, I can work around not having this feature, it's not critical for me.

**What I can't work around is your attitude**. What's up with the arrogant and condescending tone? Why all the patronizing and dismissive talk? When did you decide you had the only valid opinion on Earth about this, and why do you believe that gives you permission be aggressive and disdainful?

**I'm aborting my switch to Kitty**. I want the maintainers of the software I use to be respectful to their users, and that's clearly not the culture here. I'll find a better alternative.

**Comment by kovidgoyal** [comment]
Good, I am delighted to be spared having you as a user.
