### ISSUE TITLE
Escape characters when typing Ctrl-Left, PgeUp, Ctrl-Ins, ...

### ISSUE THREAD

**Issue by ThomasBucaioni** [kovidgoyal/kitty#3327]
How to activate Ctrl-Left and Ctrl-Right in the command line to jump one word (Alt-f and b work great though)?
Also, in some editors, PgeUp and PgeDown insert escape characters too. Is there a way to assign a command to those keystrokes? It's always possible to do without but habits are sometimes hard to change

**Comment by SolitudeSF** [comment]
this is supposed to be handled by your shell/whatever program you're running.

**Comment by ThomasBucaioni** [comment]
Then, nothing to do with Kitty... Thanks

**Comment by ThomasBucaioni** [comment]
> this is supposed to be handled by your shell/whatever program you're running.

Do you have an idea how to solve the issue? With _bash_, **Ctrl-Left** jumps a word but in _zsh_ it doesn't. Same for _emacs_ in cmdline

**Comment by SolitudeSF** [comment]
nobody really knows how to configure zsh, but we can steal.

https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh#L98

**Comment by ThomasBucaioni** [comment]
Perfect. Thank you very much for your help
