### ISSUE TITLE
Shift+Backspace sends `\e[127;2u`

### ISSUE THREAD

**Issue by eepp** [kovidgoyal/kitty#3329]
**Describe the bug**

When I press Shift+Backspace in kitty 2a96d262, I see `7;2u`.

Inspecting what's sent exactly with `showkey -a`:

```
^[[127;2u 	27 0033 0x1b
 	91 0133 0x5b
 	49 0061 0x31
 	50 0062 0x32
 	55 0067 0x37
 	59 0073 0x3b
 	50 0062 0x32
 	117 0165 0x75
```

Behaviour observed as of 2a96d262; nonexistent in 0.19.3.

In 0.19.3:

```
^? 	127 0177 0x7f
```

Considering [this](https://iterm2.com/documentation-csiu.html), is this expected or a regression? If so, how can I get the behaviour of 0.19.3?

**To Reproduce**

1. Launch `kitty --config=NONE` (2a96d262).
2. Press Shift+Backspace.

**Expected behavior**

The same as if you only press Backspace.

**Environment details**

```
Linux meow 5.10.13-arch1-2 #1 SMP PREEMPT Sat, 06 Feb 2021 11:07:29 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
dup of #3248

**Comment by eepp** [comment]
Quick fix for this one specifically:

```
map shift+backspace send_text all \b
```
