### ISSUE TITLE
What does "Supports ... graphics (images)..." mean?

### ISSUE THREAD

**Issue by bearcatsandor** [kovidgoyal/kitty#333]
The readme states "Supports all modern terminal features: graphics (images)", but doesn't state how.  I've got Kitty loaded up and it doesn't seem to give me thumbnails for graphics when doing an `ls` (like  https://github.com/billiob/terminology does) or have a way to display image files or movies within the terminal.

So, what does that mean?

Thank you.

**Comment by kovidgoyal** [comment]
See the section on graphics in the readme

**Comment by kovidgoyal** [comment]
It's under the section on protocol extensions, of which graphics is one
