### ISSUE TITLE
Standardize your terminal and add separate gui config---urator

### ISSUE THREAD

**Issue by SCCOBN** [kovidgoyal/kitty#3331]
As far as terminal goes right now, thumbs down, I did yay -R kitty on it just after 20 minutes. 

Okay..

1) Add compatibility switches.. Go ahead install terminator or gnome-terminal and all the switches it has go ahead implement. Including --geometry. I don't care if wayland does not support positioning, it should not concern you. You just implement switches and forget about it.. Otherwise you will get forked and forgotten about just like I just yay -R your kitty. NO AFTER THOUGHTS.

2) Implement GUI config. It could easily be a separate program which when APPLY is hit can call update kitty.config, poll all kitty instances, and send 'update' message to them. It's as easy as that.

The way it is now, your software is A_ not mature, and B_ highly amateurish.. This is why alacritty is recommended everywhere on the internet. Look at you, issue #3331... Normal software written by someone who knows what they doing does not have so many issues.

**Comment by kovidgoyal** [comment]
:rofl: What a moron.
