### ISSUE TITLE
Kitty Mod Inserts Character

### ISSUE THREAD

**Issue by lukesmurray** [kovidgoyal/kitty#3334]
**Describe the bug**

I want to use `ctrl+a` as my kitty_mod but when I press ctrl+a I get the characters `^a` in the editor as well as the `kitty_mod` behavior. It is possible to use `ctrl+a` as my kitty_mod without inserting the character `^a` into the editor? (This is probably not a bug in kitty but I'm not sure where else to ask!)

In addition, does kitty support key chords? For example I want to use `ctrl+a, -` and `ctrl+a, shift+-` to perform window splits. I don't necessarily want to make `ctrl+a` my kitty modifier but I'm not sure how to replicate key chord behavior without overriding kitty_mod.

Here are the relevant lines from my kitty config.

```
kitty_mod ctrl+a
map ctrl+a no_op
map kitty_mod+- launch --location=hsplit
map kitty_mod+shift+- launch --location=vsplit
enabled_layouts splits:split_axis=horizontal
```

**Comment by lukesmurray** [comment]
Resolved.  `>` can be used to for multi key shortcuts. These are called `chords` in vscode. Not sure if that is the common name but that's why I couldn't find it. Maybe documentation could be changed from `You can use multi-key shortcuts using the syntax shown below:` to `You can use multi-key shortcuts (also known as chords) using the syntax shown below:` 






```
map ctrl+a>- launch --location=hsplit
map ctrl+a>shift+- launch --location=vsplit
enabled_layouts splits:split_axis=horizontal
```

**Comment by kovidgoyal** [comment]
No kitty_mod has to be made of modifiers. And you can define multi-key
shortcuts using >
ctrl+a > b
