### ISSUE TITLE
Tab Title/Name: How to change template?

### ISSUE THREAD

**Issue by qazip** [kovidgoyal/kitty#3335]
How can one change the tab title/name template? By default, the tab title seems to be something like:

`user@pc_name: CWD`

Would it be possible to change it to `CWD` only, or something else? How would one go about doing this?

**Comment by kovidgoyal** [comment]
Look in kitty.conf

**Comment by shervinsahba** [comment]
@qazip 

You can manipulate tab titles with Python string formatting. For example, I wanted to eliminate `username@hostname` while on my home system but keep `other-username@remotename` while ssh-ing into another machine. In both cases, I wanted the CWD that follows in the tab title.

To do this I added the following to my kitty.conf:

`tab_title_template "{title.split('USERNAME@HOSTNAME:')[-1]}"`

This works, but the USER/HOSTNAME info is hard-coded. I'm unsure if you can make it more malleable to use system-wide.

**Comment by qazip** [comment]
> @qazip
> 
> You can manipulate tab titles with Python string formatting. For example, I wanted to eliminate `username@hostname` while on my home system but keep `other-username@remotename` while ssh-ing into another machine. In both cases, I wanted the CWD that follows in the tab title.
> 
> To do this I added the following to my kitty.conf:
> 
> `tab_title_template "{title.split('USERNAME@HOSTNAME:')[-1]}"`
> 
> This works, but the USER/HOSTNAME info is hard-coded. I'm unsure if you can make it more malleable to use system-wide.

Thanks for the help! I added the same as you to my kitty.conf though I saw no changes. I still see the "username@hostname: cwd". Does that really work for you?

**Comment by kovidgoyal** [comment]
The title is taken from what the shell sets. If you want to change it,
change it there. Google how to set window title in shell and you will
fnd the relevant information.

**Comment by shervinsahba** [comment]
@qazip Did you write the literal USERNAME and HOSTNAME? Try putting in your username and hostname. For example, mine would be

`tab_title_template "{title.split('shervin@mycomputer:')[-1]}"`

But @kovidgoyal is absolutely right. These are changes that ought to be made at the shell level - can't believe I missed that! Thank you for the reply Kovid, and thank you for the awesome software you put out!
