### ISSUE TITLE
Can't map ctrl+/

### ISSUE THREAD

**Issue by Sleepful** [kovidgoyal/kitty#3341]
try `ctrl+/`, it will print `^_`
ok
now try adding to your kittyrc:
```
map ctrl+/      no_op
```
or
```
map ctrl+slash     no_op
```
reload
press `ctrl+/`, you can see terminal still receives `^_`

**Comment by kovidgoyal** [comment]
Yes, no_op means there is no action in kitty taken for the shortcut, so
it will be sent to the terminal.

**Comment by Sleepful** [comment]
@kovidgoyal even if mapped to an action such as "new_tab" there are still bytes being sent to the terminal because I hear a bell coming from the terminal. Probably a macos issue.

**Comment by Sleepful** [comment]
Side note: It would also be *very* nice to have something similar to `no_op` but instead of kitty taking no action at all, letting kitty absorb the keybinding without doing anything. I believe this would be useful to avoid macOs default keybindings from within the config file, which is better than having to go into macOs settings.

**Comment by kovidgoyal** [comment]
The beep comes for other reasons run 

kitty --config NONE -o 'map ctrl+/ new_tab' cat

and you will see no bytes reported by cat.

I dont follow your use case for having a keypress not delivered to the
client program.

**Comment by kovidgoyal** [comment]
And if you want to test key bindings, the way to do that is run kitty as 

kitty --debug-keyboard

and it will print out detailed information on what key events it receives and what it does with them.
