### ISSUE TITLE
Can't override "kitty edit config" 

### ISSUE THREAD

**Issue by Sleepful** [kovidgoyal/kitty#3343]
I tried to do this
```
map cmd+comma no_op
map cmd+, no_op
```
but when I press `cmd+,` it still opens vim with `kitty.conf`

it should remove the mapping.

**Comment by kovidgoyal** [comment]
That shortcut works via the macOS global menubar, these are not
overridable using the normal mechanisms, thanks to Apple's stupid
key handling design in cocoa.

**Comment by kovidgoyal** [comment]
Actually, I forgot I had put in place a framework for this, fixed by: https://github.com/kovidgoyal/kitty/commit/52347ced85dfdf33810c2dace9a715a00382ca51

**Comment by Sleepful** [comment]
@kovidgoyal thank you, just tested it and it works.
