### ISSUE TITLE
Rendering math

### ISSUE THREAD

**Issue by jtrakk** [kovidgoyal/kitty#3346]
Sometimes there is LaTeX math in the terminal. 

![image](https://user-images.githubusercontent.com/43392409/109225752-91bd2000-7772-11eb-9283-3e2436c44a8b.png)

I wonder if kitty could render it somehow into pretty math.

Or maybe rendering mathml is a better idea, and I could pre-convert latex into mathml. 

Julia's `show(io, mime, x)` takes a MIME type parameter, so I can tell it how to output objects specifically for kitty. I suppose in this case I could just tell it to output images.

**Comment by kovidgoyal** [comment]
I'm afraid not. Adding a LaTeX renderer to kitty is out of scope. You
could have whatever you are using to view the file inside the terminal
render the LaTeX to PNG and  kitty can display that, like for example
termpdf works to read PDF files in kitty.
