### ISSUE TITLE
Warning: terminal is not fully functional (Mysql)

### ISSUE THREAD

**Issue by Maxcrazy1** [kovidgoyal/kitty#3348]
**Describe the bug**
Hi, my mistake is when try call some query, kitty show me **Warning: terminal is not fully functional**. 
I use Mycli to connect to mysql databases

**To Reproduce**
1. Connect to some DB through of Mycli
2. Execute some query. Example: (Select * from users)
3. Error: Print _terminal is not fully functional_

**Expected behavior**
The message is not printed on every query

**Screenshots**
![image](https://user-images.githubusercontent.com/49521193/109265071-53f4e180-77dc-11eb-87d0-373f37ace1e6.png)

**Environment details**
OS: Linux Mint 20 x64

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer
