### ISSUE TITLE
Using Emacs in console mode, keybindings with punctuation don't get the Ctrl key

### ISSUE THREAD

**Issue by ThomasBucaioni** [kovidgoyal/kitty#3349]
When running emacs in console mode with `emacs -nw`, some keybindings using punctuation don't trigger. 
The same happens with _Xfce4-terminal_ and _Terminator_ so nothing to do with _Kitty_.

---

To reproduce:

- create a `.emacs` file with:
```
(global-set-key (kbd "C-;") 'kill-line)
(global-set-key (kbd "C-'") 'save-buffer)
```
- run emacs in console mode with `emacs -nw file.txt`
- press `C-'` and `C-;`
- instead of calling the functions `kill-line` and `save-buffer`, emacs should add a quote and a semi-colon

Any idea where it can come from?

**Comment by kovidgoyal** [comment]
That is because traaditional terminal key encoding is not capable of
representing these. You should ask the emacs developers to add support
for an extended keyboard protocol, such as
https://sw.kovidgoyal.net/kitty/keyboard-protocol.html

**Comment by ThomasBucaioni** [comment]
Cheers, I'll do
