### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by coca44** [kovidgoyal/kitty#335]
Hi when I run 

> python3 .

 Or 

> ./kitty/laucher/kitty

 I've an error (make was run with no error)

My error is:

`ImportError: /home/brian/kitty/kitty/fast_data_types.so: undefined symbol: hb_ft_font_changed`

**Comment by kovidgoyal** [comment]
You are using an outdated version of harfbuzz, with that symbol missing. Presumably the version of harfbuzz you compiled against is different from the version of harfbuzz you are running against. Use LD_LIBRARY_PATH to remedy that.
