### ISSUE TITLE
Kitty unnecessarily spams logs for unavailable feature on wayland.

### ISSUE THREAD

**Issue by LaserEyess** [kovidgoyal/kitty#3350]
**Describe the bug**
On Wayland while using an IME via `GLFW_IM_MODULE=ibus`, kitty will warn **on every keystroke** that "The platform does not provide the window position". This is wholly unnecessary and just serves to spam logs. It is not a significant issue that wayland does not support this function and certainly not worth warning the user about.

**To Reproduce**
1. set `GLFW_IM_MODULE=ibus`
2. run `fcitx5` with something like anthy/mozc
3. type a random string of characters
4. Log is spammed with `Wayland: The platform does not provide the window position` equal to the number of keys you pressed.

**Expected behavior**
Kitty understands that wayland does not implement this feature and chooses to not forward the warning to stderr. 

**Screenshots**
N/A

**Environment details**
OS: GNU/Linux 5.11.1
WM: sway 0a94bee / wlroots 79284b78

```
kitty 0.19.3 created by Kovid Goyal
Linux mami 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/laser/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
cursor_blink_interval 0.0
enable_audio_bell     False
font_size             12.0
foreground            Color(red=250, green=250, blue=250)
linux_display_server  wayland
```

**Additional context**
This comes from https://github.com/kovidgoyal/kitty/blob/master/glfw/wl_window.c#L1004-L1019

It seems upstream GLFW ran into this problem and changed the code to accomodate downstream users when they needed to ignore such an error. https://github.com/glfw/glfw/commit/9a87c2a4b49808d3666c7b093b77e8512fa23908

Would it simply be possible to ignore `GLFW_FEATURE_UNAVAILABLE`? Even if it's just for wayland? There is no chance of window position information being exposed on wayland in the near future. I admit I haven't looked at kitty's code so I have no idea how difficult it would be to ignore warnings like this, or even fine tune it to a specific backend/function.

Also, is it really necessary for kitty to call that glfw function for every IME keystroke?

**Comment by kovidgoyal** [comment]
It's not kitty it's glfw. And a PR using a static variable to only print
this warning once is welcome.
