### ISSUE TITLE
Characters cannot be deleted in a ssh session

### ISSUE THREAD

**Issue by zackszhu** [kovidgoyal/kitty#3353]
**Describe the bug**
When I ssh into a server within kitty, the commands display weirdly:
- If I type in some characters and try deleting them with backspace, the cursor doesn't move backward. It actually moves forward, just like I typed a space
![2021-02-26 23 55 18](https://user-images.githubusercontent.com/7601610/109381266-31bb9c00-788e-11eb-8ef8-0ea9c57fa5c7.gif)

- If I try to go to the previous or the next command in the history using the up arrow or down arrow, the new command doesn't replace the old one. Instead, it's appended in the back of the line
![2021-02-26 23 52 48](https://user-images.githubusercontent.com/7601610/109381242-fb7e1c80-788d-11eb-8140-4d3888683aaf.gif)

**To Reproduce**
1. ssh to a server
2. type something
3. press backspace

**Expected behavior**
The characters should be removable (by a backspace, up arrow, down arrow, ctrl-u, ...)

**Screenshots**
See gifs above

**Environment details**
OS: macOS Big Sur 11.2.1 on MacBook Air (M1, 2020)

```
kitty 0.19.3 (57db384953) created by Kovid Goyal
Darwin Chaojies-MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	11.2.1 BuildVersion:	20D74

Config options different from defaults:
```

**Additional context**
It's reproducible with `kitty --config NONE`.

**Comment by SolitudeSF** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by zackszhu** [comment]
That works, thank you!
