### ISSUE TITLE
Entries to global menu bar that change tabs added delay to changing tabs

### ISSUE THREAD

**Issue by Sleepful** [kovidgoyal/kitty#3354]
Behavior introduced by: 81f144df155f6079c2cfa4f80f4524d65863211d

Changing tabs on kitty through the keyboard shortcut was instantaneous before the commit.

After the commit there is a slight delay, during the delay the macOs menu bar highlights the entry that corresponds to tab-change.

*Technically not-a-bug because this is how macOs expects their apps to behave, but less than ideal user experience.*

**Comment by Sleepful** [comment]
I find the delay and the menu-bar blue highlight rather distracting. :(

**Comment by kovidgoyal** [comment]
Not sure what I can do here, that's how apple's shortcuts work. Complain
to them. One workaround you can use is define multiple shortcuts for
next/previous_tab only the last one will be used for the apple global
menu.

**Comment by Sleepful** [comment]
@kovidgoyal first off, thanks for the workaround! 
iTerm2 doesn't suffer from the delay, so I am not sure it's entirely macOs.
Anyways, I submit an issue on your repo because obviously you are going to care 
a lot more than Apple ever will. Some options that come to mind:
You could remove the menu bar options, or add an option to the configuration to remove it.
I don't think this should be default behavior.
There's no reason to abide by macOs "standards" if they are poor design.
I wonder how other macOs users would feel that their tab-switching has a delay.
The workaround worked though! That's awesome. Thanks, again.

**Comment by kovidgoyal** [comment]
You're welcome. The default OS independent shortcuts for those actions
continue to exist and work as before. The macOS specific ones go though
the global menubar and that is the right thing to do since that is the
expectation of the host platform. As for doing it without delays in the
global menubar, I dont see how that's possible, but hey patches are most
welcome.

**Comment by kovidgoyal** [comment]
And I'll note that I can se eno delay on my mac when using ctrl+tab to change tabs.
