### ISSUE TITLE
MacOS 11.2.2 Cmd+c/v (or Ctrl+c/v if remmaped) and Shift+Ctrl+c/v whithin Tmux not working

### ISSUE THREAD

**Issue by fgr1986** [kovidgoyal/kitty#3355]
**Describe the bug**
Under MacOS 11.2.2, Cmd+c/v (or Ctrl+c/v if remmaped) and Shift+Ctrl+c/v whithin Tmux not working

**To Reproduce**
1. Update from 11.2.0 to 11.2.1 and 11.2.2 
2. Select/copy/paste from whithin kitty produces nothing, and nothing is copied to clipboard
3. Anything in the clipboard cannot be copied back to kitty, both with and without a tmux session (standard cmd-c/v, ctrl-c/v and tmux shift-ctrl-c/v).

**Expected behavior**
Being able to copy to and from clipboard.

**Environment details**
MacOS 11.2.2

```
Output of kitty --debug-config.
```
Kitty installed with brew:
```
 > kitty --debug-config
zsh: no such file or directory: /Users/fgarcia/.local/kitty.app/bin/kitty
```

**Comment by kovidgoyal** [comment]
Works fine for me on macOS. 

1) Install the official kitty binaries, not the homebrew package
2) Dont use tmux, although for this issue it is irrelevant.

**Comment by fgr1986** [comment]
Thanks @kovidgoyal 
Official binary works, thanks. Looking forward for the aarch64 MacOS builds.
Just as a note, in your webpage docs brew is also mentioned, so I assumed it was the same binary distributed through brew, thus incorporying auto-updating etc.
