### ISSUE TITLE
Kitty hangs on latest NixOS-unstable

### ISSUE THREAD

**Issue by rht** [kovidgoyal/kitty#3357]
**Describe the bug**
This is basically https://github.com/NixOS/nixpkgs/issues/111657. The gist is that after an upgrade to latest version, even Brave and Chromium hang, not just Kitty. But I got no response there, and was left on my own to figure the cause. Help appreciated!

**Environment details**
OS: nixos-unstable

More context:
```
 ~  LIBGL_DEBUG=verbose kitty                                              ~
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/rht/.drirc: No such file or directory.
libGL: using driver i915 for 5
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/rht/.drirc: No such file or directory.
libGL: using driver i915 for 5
libGL: pci id for fd 5: 8086:5917, driver iris
libGL: MESA-LOADER: dlopen(/run/opengl-driver/lib/dri/iris_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/rht/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/rht/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/rht/.drirc: No such file or directory.
libGL: Using DRI3 for screen 0
```

**Comment by rht** [comment]
More data point: xterm, urxvt, Firefox work fine.

**Comment by kovidgoyal** [comment]
This will be a regression in either your GPU drivers and/or mesa.
Downgrade them one by one and find the culprit.

**Comment by Luflosi** [comment]
You could also try bisecting nixpkgs to find exactly which commit introduces the hang but that will probably take a while and be really annoying.

**Comment by rht** [comment]
Thank you for isolating the problem. If that's true, I will bisect starting with the commit introduced in https://github.com/NixOS/nixpkgs/pull/111202.
