### ISSUE TITLE
Execute command in new instance

### ISSUE THREAD

**Issue by JodusNodus** [kovidgoyal/kitty#336]
How can i launch an instance with a command without a layout. Example: launch a new instance with a file in vim. Currently tested on macOs i can only pass it a binary but arguments aren't allowed.

Thanks for the Awesome work!

**Comment by kovidgoyal** [comment]
kitty vim /path/to/file

**Comment by kovidgoyal** [comment]
Oh and an macOS, you might need to use the full path to kitty, something like

/Applications/kitty.app/Contents/MacOS/kitty

Although from within kitty that is not needed since kitty adds itself to the PATH.

**Comment by JodusNodus** [comment]
aah, yes that does work thanks!
