### ISSUE TITLE
When connecting to AWS from kitty, the prompt is missaligned 

### ISSUE THREAD

**Issue by ThomasBucaioni** [kovidgoyal/kitty#3362]
Running emacs gives an error message that says:
```
$ emacs .bashrc
emacs: Terminal type xterm-kitty is not defined.
If that is not the actual type of terminal you have,
use the Bourne shell command 'TERM=...; export TERM' (C-shell:
'setenv TERM ...') to specify the correct type.  It may be necessary
to do 'unset TERMINFO' (C-shell: 'unsetenv TERMINFO') as well.
```
and it seems related to the prompt issue

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer and https://sw.kovidgoyal.net/kitty/faq.html#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo.

**Comment by ThomasBucaioni** [comment]
Cheers
