### ISSUE TITLE
--single-instance process remains after widow closes

### ISSUE THREAD

**Issue by focusaurus** [kovidgoyal/kitty#3363]
**Describe the bug**
The help docs state:

>    Normally, when using --single-instance, kitty will open a new window in
>    an existing instance and quit immediately.

I do not see this behavior. Instead, my `kitty` command line process continues to run in my shell after the GUI window is closed and until I kill it with ctrl-c.

**To Reproduce**

1. Start a main kitty window
2. from a shell in that window, run ` echo 'launch less /tmp/notify' | kitty --title HUD --session=- --single-instance`
3. exit the shell in the new window, which causes the window to close

**Expected behavior**
The kitty process launched in step 2 should exit and I should be back at my shell prompt.

**Environment details**
OS: macos 10.15.7 Name and version of operating system(s)

```
Output of kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Darwin RSG-50073 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H524
Loaded config files: /Users/peterlyons/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell False
font_family       JetBrains Mono
font_size         16.0
scrollback_lines  100000
Added shortcuts:
	 control+v KeyAction(func='paste_from_clipboard', args=())

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You need to start your first kitty instance with --single-instance as
well. Then the *second* time you run kitty with --single-instance, it
will open a new window in the *first* instance and quit immediately.
