### ISSUE TITLE
Solid-color emoji highlighting

### ISSUE THREAD

**Issue by radiolevity** [kovidgoyal/kitty#3364]
**Is your feature request related to a problem? Please describe.**
I want to use [Noto Emoji](https://www.google.com/get/noto/#emoji-zsye) with kitty, but I cannot highlight the characters.

**Describe the solution you'd like**
To have a way of highlighting solid color emoji.

**Describe alternatives you've considered**
I have tried using the kitty emoji picker with the 'text' and 'graphic' options, but these characters are not double-width.

**Additional context**
Here is how the snake emoji looks in kitty:
<img width="585" alt="kitty" src="https://user-images.githubusercontent.com/21144914/110069132-290f0e00-7d45-11eb-98ab-c3d968e0018e.png">

Here it is highlighted in the VSCodium terminal:
<img width="669" alt="vscodium" src="https://user-images.githubusercontent.com/21144914/110069126-26acb400-7d45-11eb-818e-af38b9b121a2.png">

If I'm missing some obvious way to accomplish this please let me know.

**Comment by kovidgoyal** [comment]
dup of #3211

**Comment by radiolevity** [comment]
By adding `U+FE0F` (as noted above, and in #3211) I can change the highlight color, but the emoji is single-width. Is there a way to have both double-width display and highlighting?

<img width="436" alt="image" src="https://user-images.githubusercontent.com/21144914/110076371-6201af80-7d52-11eb-9308-455b6117bb88.png">

**Comment by kovidgoyal** [comment]
Run from master.

**Comment by radiolevity** [comment]
Just built from master:
<img width="437" alt="Screen Shot 2021-03-05 at 2 39 14 AM" src="https://user-images.githubusercontent.com/21144914/110082901-fae8f880-7d5b-11eb-89b1-52f1b975aece.png">

**Comment by kovidgoyal** [comment]
Ah I think I got your problem. Color emoji are not colored by text attributes. They are rendered in whatever color comes from the font. If you want to color them, then you follow them by \ufe0e and they will be rendered as text, single-celled and colored by the current foreground color.

This is the way they are supposed to be rendered. If vscodium is doing it differently, then that is a bug in that program.

**Comment by radiolevity** [comment]
Got it. Thanks for the info!
