### ISSUE TITLE
emerge kitty fails (access denied) (funtoo linux)

### ISSUE THREAD

**Issue by brahambence** [kovidgoyal/kitty#3365]
**Describe the bug**
when running `emerge kitty` in Funtoo linux, the installer exits after compiling due to 2 ACCESS DENIED errors.

**To Reproduce**
1. run 'emerge -a kitty' on Funtoo linux and most likely Gentoo as well.
2. notice the ACCESS DENIED: mkostemp: [...] error message 

**Expected behavior**
Kitty should install successfully.

**Environment details**
OS: Funtoo Linux 1.4
Kernel version: 5.10.13_p1-debian-sources

**Comment by kovidgoyal** [comment]
I dont maintain distro specific kitty packages. Report this to your
distro. Or use the official kitty binaries.
https://sw.kovidgoyal.net/kitty/binary.html
