### ISSUE TITLE
Autodetect gemini URLs and allow clicking on them

### ISSUE THREAD

**Issue by lokesh-krishna** [kovidgoyal/kitty#3370]
Gemini is a new internet protocol about which you can learn more at [gemini.circumlunar.space](https://gemini.circumlunar.space).

Presently, kitty auto-detects URLs for a few internet protocols. It would be really nice if it would also autodetect gemini URLs (which are of the pattern `gemini://`) and allow clicking on them to open a browser that handles those links. 

Presently the only way to follow a gemini link is to manually highlight it and paste it into a browser.

**Comment by kovidgoyal** [comment]
Simply add it to url_prefixes in kitty.conf. The default value will add
gemini for the next release.
