### ISSUE TITLE
Visual Ligature Corruption Apple Silicon

### ISSUE THREAD

**Issue by pckilgore** [kovidgoyal/kitty#3372]
**Describe the bug**
When building kitty from source for Apple Silicon (darwin-arm64), ligatures do not appear as expected.  The appearance is correct when using amd64 downloaded builds of Kitty.

**To Reproduce**
1. Install tonsky/FiraCode TTFs
2. Configure Kitty to use Fira Code + Ligatures
3. Type characters that typically would transform via ligature.
4. Observe visual corruption

**Expected behavior**
For each tuple of characters forming a ligature, I would expect to see the correct ligature in its place.

**Screenshots**
GIFs are in nvim but the same effect appears everywhere. Note, I have configured kitty to hide ligatures when hovering over the characters, which helps to illustrate the issue in the GIFs below.

![kitty-ligature-1](https://user-images.githubusercontent.com/2559043/110250440-f0d41f00-7f40-11eb-937f-b73074262968.gif)
![kitty-ligature](https://user-images.githubusercontent.com/2559043/110250450-f3367900-7f40-11eb-8283-991e37938299.gif)

**Environment details**
OS: macOS Big Sur 11.2.2 (Apple M1

```
kitty 0.19.3 (958ccadc09) created by Kovid Goyal
Darwin patricks-air.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	11.2.2 BuildVersion:	20D80
Loaded config files: /Users/patrick/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color                Color(red=0, green=0, blue=255)
bold_font                          Fira Code SemiBold
copy_on_select                     clipboard
cursor                             Color(red=221, green=221, blue=255)
cursor_shape                       2
disable_ligatures                  1
editor                             nvim
font_family                        Fira Code Retina
font_features                      {'Fira': ('Code', '+zero', '+onum')}
font_size                          13.5
inactive_text_alpha                0.8
macos_option_as_alt                3
macos_quit_when_last_window_closed True
macos_thicken_font                 0.25
scrollback_lines                   10000
strip_trailing_spaces              smart
tab_bar_edge                       1
tab_bar_style                      powerline
Changed shortcuts:
	 shift+ctrl+n KeyAction(func='new_os_window_with_cwd', args=())
	 shift+ctrl+enter KeyAction(func='new_window_with_cwd', args=())
```

**Additional context**
Minimum config change to recreate:
```
kitty 0.19.3 (958ccadc09) created by Kovid Goyal
Darwin patricks-air.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	11.2.2 BuildVersion:	20D80
Loaded config files: /Users/patrick/.config/kitty/kitty.conf

Config options different from defaults:
font_family Fira Code Retina
```

**Comment by kovidgoyal** [comment]
There were a lot of changes to ligature support in master recently. Can you do the following:

1) Build the 0.19.3 commit rather than master and check if it works.
2) Build master with amd64 and check if it happens there

I dont really see why CPU architecture should affect this apart from compiler/CPU bugs, which would b very difficult to fix since I dont even have access to this hardware.

**Comment by pckilgore** [comment]
Building from tag v.0.19.3 rather than master fixed it.  

Embarrassing for me 😳

Thanks again for Kitty
