### ISSUE TITLE
Add optional dark theme to documentation

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kovidgoyal/kitty#3373]
https://sw.kovidgoyal.net

Using https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

I can do it.

**Comment by kovidgoyal** [comment]
The proper way to do it is to add support for it to the sphinx (the
documentation generator) theme, which is alabaster the default sphinx theme.

Do that and the kitty docs will get it automatically.
