### ISSUE TITLE
Resizing terminal vertically while some full screen app is running

### ISSUE THREAD

**Issue by safinaskar** [kovidgoyal/kitty#3377]
**Describe the bug**

**To Reproduce**
Generate lot of output in kitty. For example, execute `yes | head -n 1000`. Then type `less --help` to kitty and Press Enter. Make kitty window smaller vertically. Then exit from less. You will see `less --help` after bash prompt. I. e. one line somehow got eaten.

**Expected behavior**
I should see nothing after bash prompt.

**Screenshots**

**Environment details**
Recent debian sid amd64. Kitty 0.19.3-1.

```
Output of kitty --debug-config

kitty 0.19.3 created by Kovid Goyal
Linux throw 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 
Debian GNU/Linux bullseye/sid \n \l 
Loaded config files: /etc/xdg/kitty/kitty.conf 
Running under: X11

Config options different from defaults: 
update_check_interval 0.0
```

**Additional context**
`kitty --config NONE`: reproducible, too.

Other teminal emulators have this bug, too. But gnome-terminal 3.38.3-1 have not

**Comment by kovidgoyal** [comment]
It's not a bug. It's a limitation of resizing terminals and how shells draw prompts. Search a  bit and you will find other issues mentioning it. And it happens on *all* terminals, since it is timing dependent.
