### ISSUE TITLE
Thicken font feature for linux

### ISSUE THREAD

**Issue by reportaman** [kovidgoyal/kitty#3382]
I like the thicken font feature ``macos_thicken_font`` you have for macOS, my workflow requires working on both Linux & macOS. If it is possible, it would be nice to have a similar feature for Linux as well, that way one can use same font for both OSes and adjust them to make similarly comfortable to read. Thanks!

**Comment by kovidgoyal** [comment]
No that feature uses a macOS specific API, I'm afraid.
