### ISSUE TITLE
Privacy policy: Kitty tries to connect to kovidgoyal.net on launch, what kind of data is collected & tracked? Is there an opt-out?

### ISSUE THREAD

**Issue by reportaman** [kovidgoyal/kitty#3385]
Kitty tries to connect to kovidgoyal.net upon each launch. What kind of data is collected and/or tracked? Is there an opt-out? There is no information I could find on kitty's website, it would be good to put it there and on GitHub page.

> As a side-note: The launch time of Kitty on macOS is way slower than other similar terminal emulator apps like iTerm2 or Alacritty. Not sure if improving that is on the roadmap of Kitty.

"Notorious" kitty screenshot:
<img width="682" alt="notorious_kitty" src="https://user-images.githubusercontent.com/71736629/111008711-8d822c80-8346-11eb-8545-259dc8b0147e.png">

**Comment by Luflosi** [comment]
kitty is checking for updates. See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.update_check_interval for how to turn this off and #1342 for some discussion.
Your other questions need to be answered by @kovidgoyal as I don't know the answer to them.

**Comment by reportaman** [comment]
@Luflosi Thanks, setting it to 0 disables that connection. @kovidgoyal Document says that default is to check for update every 24 hours, though in my observation it checks for update every time kitty is quit and relaunched.

**Comment by kovidgoyal** [comment]
Every 24 hrs while running.
