### ISSUE TITLE
Vulkan Support

### ISSUE THREAD

**Issue by jorpilo** [kovidgoyal/kitty#3386]
Hello.

According to #3015, Kitty is not going to be ported to OpenGL ES 3.1. This leads devices such as raspberry pi or rockchip aarch64 without support to run Kitty.

As proposed by @kovidgoyal an alternative is to migrate to Vulkan. Raspberry Pi 4 recently got vulkan support and other devices such as Rock Pi 4 also support vulkan.

What is the status of the vulkan implementation? I have never developed in vulkan but I am willing to contribute in development/testing if necessary.

**Comment by kovidgoyal** [comment]
It's on my TODO list. I will get to it someday. If someone else wishes
to contribute, patches are most welcome.

**Comment by zachfi** [comment]
Did this get implemented?  I was trying to use kitty on SteamOS which has OpenGL 4.x, and so the OpenGL support doesn't match what looks like is the required 3.3 version.  Looking for alternative ways to run kitty in such an environment.

**Comment by kovidgoyal** [comment]
kitty requirees OpenGl >= 3.3 OpenGL 4 is just fine.

**Comment by leiserfg** [comment]
@kovidgoyal I haven't tested it but, theoretically, kitty should work in any Linux with Vulkan by leveraging Kopper to Zink.

**Comment by JechtShinryaku** [comment]
> @kovidgoyal I haven't tested it but, theoretically, kitty should work in any Linux with Vulkan by leveraging Kopper to Zink.

Hi, I'm trying to run Kitty on ArchLinux ARM on a Raspberry 4.
I have Mesa and Vulkan installed and the 'vulkan gears' test runs perfectly but Kitty keeps giving me the error 'Failed to create GLFWwindow'.
Can someone guide me?

**Comment by kovidgoyal** [comment]
Just for the record, kitty on Linux (as of 0.28.0) no longer needs OpenGL 3.3 it works with OpenGl 3.1 + extensions which means all these devices probably work out of the box. And no, kitty has no support for vulkan.

**Comment by tutacat** [comment]
To use Zink, an OpenGL implementation based on Vulkan, you have to install it, and set GALLIUM_DRIVER to use it.

**Comment by cos4ni2s** [comment]
Does Kitty use Vulkan now?

**Comment by BlPu** [comment]
> Does Kitty use Vulkan now?

No, kitty still doesn't support Vulkan.
