### ISSUE TITLE
Color Intensity

### ISSUE THREAD

**Issue by GGCristo** [kovidgoyal/kitty#3389]
Greeting, kitty is being a great experience, but at the time being there are 2 features that I miss, one is allows some workaround to allow glyphs overflow, but it's look like you already talked about that (https://github.com/kovidgoyal/kitty/issues/3072).
The other one is an option to intensify the colors, in kitty the colors looks too faded compared with other terminals.

kitty:
![kitty](https://user-images.githubusercontent.com/58046649/111027202-a17d6b00-83e6-11eb-99a5-d32a9920db8d.png)
konsole (no "draw intense colors in bold font"):
![konsoleFaded](https://user-images.githubusercontent.com/58046649/111027207-acd09680-83e6-11eb-95cc-296dc28a4dd8.png)
konsole (draw intense colors in bold font):
![konsoleIntense](https://user-images.githubusercontent.com/58046649/111027213-b2c67780-83e6-11eb-93dc-2b48af218e4a.png)

It is a very specific request, but it will make some dark themes more readable.

**Comment by kovidgoyal** [comment]
Colors are entirely configurable. You can define whatever you like for
every color in the 256 color table. See kitty.conf for details. 

As for glyph bleed, that is never going to happen as cell based
independent rendering is core to the design and performance of kitty.

**Comment by beauwilliams** [comment]
I can say the colours are washed out. I'm hesitant to use kitty for this reason. It's the only shell I noticed this with and a real PITA
