### ISSUE TITLE
on macOS, sometimes cmd-tabbing back to kitty shows different window

### ISSUE THREAD

**Issue by danp** [kovidgoyal/kitty#3390]
**Describe the bug**
Under macOS, sometimes when I cmd-tab away from kitty to another app, then cmd-tab back, a different kitty OS window is active.

**To Reproduce**

It doesn't always happen, but when it does the sequence goes something like this:

1. Have >1 OS window, with one active
2. cmd-tab to another application
3. cmd-tab back to kitty
4. See a window other than the one that was active in step 1

**Expected behavior**
I expect the same kitty window/tab/etc that was active when I cmd-tabbed away to still be active when I cmd-tab back.

**Environment details**
macOS Big Sur, on an M1 Air. I did compile from 62912a800a to produce an arm64 build.

```
kitty 0.19.3 (62912a800a) created by Kovid Goyal
Darwin MacBook-Air.localdomain 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	11.2.2 BuildVersion:	20D80
Loaded config files: /Users/dan/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 0.0
enable_audio_bell     False
font_size             12.0
macos_option_as_alt   3
visual_bell_duration  0.1
```

**Comment by kovidgoyal** [comment]
I'm going to need some way to reproduce to be able to help you.

**Comment by danp** [comment]
Understood, sorry for the lack of reproduction steps. It doesn't always happen and I'm not sure what makes it happen or not. If this isn't enough info to go on or doesn't sound like anything anyone else has seen, please feel free to close.

I'd also be happy to try debugging further if you have any tips. For example, is there a particular code path that happens during cmd-tab? I'll try to dig into this myself but have not yet.

**Comment by kovidgoyal** [comment]
On Sat, Mar 13, 2021 at 07:35:13AM -0800, Dan Peterson wrote:
> Understood, sorry for the lack of reproduction steps. It doesn't always happen and I'm not sure what makes it happen or not. If this isn't enough info to go on or doesn't sound like anything anyone else has seen, please feel free to close.

No worries, just that have never seen this and cant reproduce so there
isnt very much I can do to help.

> 
> I'd also be happy to try debugging further if you have any tips. For example, is there a particular code path that happens during cmd-tab? I'll try to dig into this myself but have not yet.

When cmd-tab happens the OS sends focus events to the application. These
are handled by glfw the toolkit kitty uses, which forwards them to kitty.
In the glfw folder the relevant file is cocoa_window.m look for keyin
and focus keywords. In kitty it is glfw.c look for
window_focus_callback()

**Comment by danp** [comment]
Thanks! I'll look into those places and see if I can debug when it happens. For now, I'll close this but maybe if someone else runs into it it'll show up in searches.

**Comment by dylan-chong** [comment]
This happens to me as well

```
> kitty -v
kitty 0.19.3 created by Kovid Goyal
```


Works perfectly fine if the 2 kitty windows are on the same display. If they are on different displays then Kitty seems to always pick one window

**Comment by kovidgoyal** [comment]
as far as I know, its the OS that chooses the window, not the application. See https://apple.stackexchange.com/questions/201972/osx-cmdtab-behavior-with-multiple-windows-monitors

**Comment by dylan-chong** [comment]
Ah this happens with chrome too! 😢 
But thanks for the link, will try unticking the "Displays have separate spaces" option

**Comment by dylan-chong** [comment]
Have tried this option. Very annoying because if you have a fullscreen window on one display it makes all the others black :/ . It also is annoying because the menu bar is only accessible on one display. However, it does fix the issue in question...
