### ISSUE TITLE
Kitty reports the wrong $SHELL on macOS

### ISSUE THREAD

**Issue by kevinsjoberg** [kovidgoyal/kitty#3397]
**Describe the bug**

Kitty reports my current shell as `fish` even though it's set to `bash`.

```console
~ $ chsh -s /usr/local/bin/bash kevinsjoberg
Changing shell for kevinsjoberg.
Password for kevinsjoberg: 
chsh: no changes made
~ $ ps -p $$
  PID TTY           TIME CMD
71809 ttys000    0:00.07 -bash
~ $ dscl . -read ~/ UserShell
UserShell: /usr/local/bin/bash
~ $ echo $SHELL
/usr/local/bin/fish
~ $ 
```

Any other terminal I've tried report `echo $SHELL` as `/usr/local/bin/bash`.

**Expected behavior**

I expect Kitty to report my actual shell, `bash` in this case.

**Environment details**
OS: macOS, `11.2.1`

```console
kitty 0.19.3 created by Kovid Goyal
Darwin Kevins-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2.1 BuildVersion:	20D74
Loaded config files: /Users/kevinsjoberg/.config/kitty/kitty.conf

Config options different from defaults:
font_family PragmataPro Mono Liga
font_size   14.0
```

**Comment by kevinsjoberg** [comment]
Follow up. So restarting my Mac solves the problem. But whenever you switch shell using `chsh` the problem persists until reboot.

**Comment by kovidgoyal** [comment]
kitty does not set the SHELL environment variable at all. Easily
confirmed by grepping the source code for \bSHELL\b

**Comment by wren** [comment]
I was actually coming here to report the same thing. I get that Kitty doesn't do anything to the `$SHELL` variable, so this is admittedly very weird. I'm seeing the exact same thing reported in the OP: Kitty shows the wrong output, but Terminal, Iterm2, and Alacritty all show the correct one.

**Comment by kovidgoyal** [comment]
Most likely you have something in some shell rc file that changes its behavior based on the TERM env var.
