### ISSUE TITLE
Customize visual bell color

### ISSUE THREAD

**Issue by gshpychka** [kovidgoyal/kitty#3399]
**Describe the solution you'd like**
A configuration entry to specify which color the terminal flashes on a bell event.

**Describe alternatives you've considered**
I'm using alacritty, which has this.

**Comment by kovidgoyal** [comment]
PR is welcome, I suggest you see the discussion in #2937 first though.
Making the color customisable is rather limited.

**Comment by gshpychka** [comment]
Thanks. What do you mean by "rather limited", though?

**Comment by kovidgoyal** [comment]
I mean changing the color is just one type of possible customization.

**Comment by gshpychka** [comment]
I guess it is. It's all I would use, though.
