### ISSUE TITLE
Feature Request: Horizontal scrolling (two finger swipe) in kitty

### ISSUE THREAD

**Issue by cookiengineer** [kovidgoyal/kitty#340]
Hey there,

I'm a long time user of kitty and a couple days ago I updated my kitty config file. I am yet unsure whether something like this is possible or not (speaking of term emulators in general).

Is there a way to support horizontal scroll with two fingers (so that you can move sideways e.g. in split views in VIM) in kitty?

I'm a total idiot when it comes into architectural details on how terminal emulators work in general, but I guess something like this would make the user experience much much better. Not sure on whether X/Wayland have to provide the details or whether the kitty process already gets the input event, but just ignores it.

(OS configuration is Arch Linux + GNOME, all as up-to-date as it can get)

**Comment by kovidgoyal** [comment]
terminals cannot in general perform actions inside programs like vim. All they can do is report input events to those programs, it is up to the programs to interpret them. And as far as I know vim does not have any support for understanding touch gestures.

**Comment by Antikyth** [comment]
> terminals cannot in general perform actions inside programs like vim. All they can do is report input events to those programs, it is up to the programs to interpret them. And as far as I know vim does not have any support for understanding touch gestures.

Neovim does, at least as of now. Is this possible in Kitty now? I have both a touchpad and a mouse with a horizontal scroll wheel, and I regularly use that horizontal scroll wheel in other software.

**Comment by Antikyth** [comment]
> > terminals cannot in general perform actions inside programs like vim. All they can do is report input events to those programs, it is up to the programs to interpret them. And as far as I know vim does not have any support for understanding touch gestures.
> 
> Neovim does, at least as of now. Is this possible in Kitty now? I have both a touchpad and a mouse with a horizontal scroll wheel, and I regularly use that horizontal scroll wheel in other software.

I have tested with `kitty --debug-input` and I can see that Kitty is indeed picking up my horizontal scrolling, so I'm assuming my issue is with Neovim.

**Comment by kovidgoyal** [comment]
You can run kitty +kitten mouse_demo and you will see the full range of input events kitty reports. it's up to individual terminal programs to add support for them.

**Comment by trygveaa** [comment]
Are you talking about two finger swipe on a touchpad or touchscreen. With a touchpad this is already working in vim in kitty for me. I swipe sideways with two fingers, kitty sends scroll left/right to vim, and vim scrolls sideways. I don't have a touchscreen, so don't know if that works differently.

Note that you need kitty >= 0.26.0 and vim >= 8.2.1108 (I don't know about neovim or other applications).
