### ISSUE TITLE
TAB completion is much slower than ubuntu's gnome-terminal using bash

### ISSUE THREAD

**Issue by minrui-hust** [kovidgoyal/kitty#3401]
kitty is great, however  I have a minor problem is that TAB completion is sometimes very slow in kitty (sometimes takes seconds), 
while the ubuntu16 gnome-terminal is much smoother. Do anyone have the same problem?

**Comment by kovidgoyal** [comment]
TAB completion is done by the shell, not the terminal.

**Comment by minrui-hust** [comment]
It seems I found a solution, after change default shell from '.' to explictly 'bash',  completion is much more smoother.
