### ISSUE TITLE
Mark regex matches break in neomutt

### ISSUE THREAD

**Issue by PhrantiK** [kovidgoyal/kitty#3403]
**Describe the bug**

Regex matches on marks break within neomutt. 

**To Reproduce**

1. Enable mark shortcut key:

````
map kitty_mod+0 toggle_marker regex 1 \bLD[0-9]{4}\b
````
2. fire up neomutt
3. Enable mark

**Expected behavior**

Regex matches seem to work fine for the first dozen or so matches but then break down and shift 16 chars. 

**Screenshots**

working:

<img width="271" alt="Screen Shot 2021-03-18 at 16 03 43" src="https://user-images.githubusercontent.com/45719263/111593909-6c698200-8805-11eb-80e1-5daa6a7c6b01.png">

Further down:

<img width="458" alt="Screen Shot 2021-03-18 at 16 04 01" src="https://user-images.githubusercontent.com/45719263/111594049-8acf7d80-8805-11eb-9e90-e48b46ada6be.png">

**Environment details**
OS: Name and version of operating system(s)

Created a blank config with only the shortcut key above with same results:

```
kitty 0.19.3 created by Kovid Goyal
Darwin gtd.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2.3 BuildVersion:	20D91
Loaded config files: /Users/hars/.config/kitty/kitty.conf

Config options different from defaults:
Changed shortcuts:
	shift+control+0 KeyAction(func='toggle_marker', args=['regex', ((1, '\\bLD[0-9]{4}\\b'),), re.UNICODE])
```

<img width="477" alt="Screen Shot 2021-03-18 at 16 24 09" src="https://user-images.githubusercontent.com/45719263/111595046-b010bb80-8806-11eb-8224-d3e63bb7f15a.png">

**Comment by kovidgoyal** [comment]
I'm going to need a better reproducer than that.  Press ctrl+shift+h to view the screen in less and save the screen to a text file by pressing s in less. And post that text file, assuming the issue is producible with it.

**Comment by PhrantiK** [comment]
Is there a way I can send it through privately? There's information on there I would rather not share publicly.

**Comment by kovidgoyal** [comment]
You can email it to me, my email address is at the top of most kitty source code files.

**Comment by kovidgoyal** [comment]
If the marking is failing only inside neomutt, then rather than using ctrl+shift+h run kitty with --dump-bytes and get to the point where the problem occurs and post the dump file instead.
