### ISSUE TITLE
Show on screen keyboard on focus

### ISSUE THREAD

**Issue by jghauser** [kovidgoyal/kitty#3406]
**Describe the bug**
I have a 2-in-1 laptop, and am trying to get the on screen keyboard (squeekboard) to show up automatically when kitty is focused as it does for most (?) other applications such as libreoffice and alacritty. Is this possible? I'm a bit confused about wayland input method, ibus etc. and am not sure whether there exists some way for this to work currently.

**To Reproduce**
1. Start squeekboard
2. Open kitty

**Expected behavior**
Squeekboard shows up.

**Actual behaviour**
Squeekboard doesn't show up.

**Environment details**
Latest Arch Linux with sway.

```

kitty 0.19.3 created by Kovid Goyal
Linux tiny 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/julian/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
active_border_color     Color(red=150, green=152, blue=150)
active_tab_background   Color(red=31, green=29, blue=29)
active_tab_foreground   Color(red=213, green=217, blue=215)
allow_remote_control    y
background              Color(red=31, green=29, blue=29)
color0                  Color(red=31, green=29, blue=29)
color1                  Color(red=204, green=102, blue=102)
color10                 Color(red=181, green=189, blue=104)
color11                 Color(red=240, green=198, blue=116)
color12                 Color(red=129, green=162, blue=190)
color13                 Color(red=178, green=148, blue=187)
color14                 Color(red=138, green=190, blue=183)
color15                 Color(red=213, green=217, blue=215)
color16                 Color(red=222, green=147, blue=95)
color17                 Color(red=163, green=104, blue=90)
color18                 Color(red=41, green=41, blue=41)
color19                 Color(red=55, green=59, blue=65)
color2                  Color(red=181, green=189, blue=104)
color20                 Color(red=180, green=183, blue=180)
color21                 Color(red=224, green=224, blue=224)
color3                  Color(red=240, green=198, blue=116)
color4                  Color(red=129, green=162, blue=190)
color5                  Color(red=178, green=148, blue=187)
color6                  Color(red=138, green=190, blue=183)
color7                  Color(red=213, green=217, blue=215)
color8                  Color(red=150, green=152, blue=150)
color9                  Color(red=204, green=102, blue=102)
cursor                  Color(red=213, green=217, blue=215)
enable_audio_bell       False
font_family             Source Code Pro
foreground              Color(red=213, green=217, blue=215)
inactive_border_color   Color(red=41, green=41, blue=41)
inactive_tab_background Color(red=40, green=42, blue=46)
inactive_tab_foreground Color(red=180, green=183, blue=180)
initial_window_height   (25, 'cells')
initial_window_width    (80, 'cells')
remember_window_size    False
selection_background    Color(red=213, green=217, blue=215)
selection_foreground    Color(red=31, green=29, blue=29)
url_color               Color(red=180, green=183, blue=180)
```

**Additional context**
Happens with `kitty --config NONE` also.

**Comment by kovidgoyal** [comment]
Sorry I have no clue either. I dont see how it could be the job of
individual applications to show/hide an OSK. At best there could be some
signal the application emits to indicate it wants text input. If there
is some wayland protocol for it, then if you can point me to some
docs/code I can implement it.

**Comment by jghauser** [comment]
After some searching online, I think that what kitty would need to do in order to get this to work is to support the wayland text-input protocol. I might be wrong though, most of this goes far over my head.

- I found this overview useful: https://dcz_self.gitlab.io/posts/input_method/
- Protocols are here: https://github.com/wayland-project/wayland-protocols/tree/master/unstable/text-input
- Apparently a v3 is in the making: https://github.com/wayland-project/wayland-protocols/commit/db152d7c6f53adb60db8dfc046604a487002d927
- If you're interested in implementing it, v3 would probably be the way to go. As mentioned [here](https://github.com/rust-windowing/winit/issues/952), it's already implemented in wlroots and gtk, and a patch for kde exists.

From some of your other comments, I can see that you're hesitant to implement unstable protocols, which is understandable. I think the (increasingly commonly used) feature might warrant an exception, but that's your call of course. I'm happy to use alacritty when I need my OSK to work.

**Comment by kovidgoyal** [comment]
I dont have any problems adding support for protocols that have been
around in wayland-protocols for a while. I do object to supporting
protocols whose definitions have to be carried around in kitty source.

So text input is eligible to be added. However given that kitty already
has a working IME solution based on DBUS, it's not a high priority for
me. That said feel free to open a separate issue to track support for
Wayland text input.

**Comment by jghauser** [comment]
Ok, I'll open an issue for adding wayland text-input. I'll be looking forward to the feature as I've not been able to get the OSK thing working with the DBUS method (I think it might not be possible). Thanks for the feedback!
