### ISSUE TITLE
macOS-Based Configuration Options (Mainly for Font Size)

### ISSUE THREAD

**Issue by trueheart78** [kovidgoyal/kitty#3408]
**Is your feature request related to a problem? Please describe.**

> I use _kitty_ on both my work Mac and my home Linux machine. The conflict I'm running into is that, due to screen sizes differing, I would prefer a different font size on each machine.

**Describe the solution you'd like**
> I'd like a way to declare a font size based off from the detected OS. There are some `is_mac` checks in the source code, and I'd love to have support for something like that. It does look like the `font_size` can be declared multiple times, with the last time being the the size utilized.

**Describe alternatives you've considered**
> Right now, I'm just leaving my Linux version of `kitty.conf` dirty with the desired font size. When I make a change to my shared config, I simply undo it, pull down the updates, and then change it back.

**Additional context**
> Thank you for your awesome work. 💖

**Comment by kovidgoyal** [comment]
Simply use conditional includes in kitty.conf to set font_size based on
the value of HOSTNAME. https://sw.kovidgoyal.net/kitty/conf.html

**Comment by trueheart78** [comment]
Awesome. Thank you! 💖
