### ISSUE TITLE
consider adding image scrolling control

### ISSUE THREAD

**Issue by dankamongmen** [kovidgoyal/kitty#3411]
When I blit an image that touches the lowermost, rightmost cell of the visual display (perhaps the "page area"; i'm not sure), the display scrolls a line. This seems a legal interpretation of https://sw.kovidgoyal.net/kitty/graphics-protocol.html, but makes it impossible (so far as I can tell) to draw a full-terminal (modulo any excess fringe pixels) image. It also behaves differently from writing text; I can write a regular old glyph to the bottommost, rightmost cell just fine without scrolling (I can't do so in the shell, but I can `cup` there and emit the character without scrolling, see below):

![2021-03-22-084826_938x589_scrot](https://user-images.githubusercontent.com/143473/111992107-6ae0d800-8aeb-11eb-9daa-bad20e4f5d56.png)

I understand why in the shell case, where the cursor needs move to the next line, you'd want to scroll, but clearly here no scrolling was necessary. Sorry if I don't understand the exact mechanisms/policies at work here.

I suggest/request that:
* images don't cause scrolling unless they actually exceed the bounding box,
* or if that is not possible, add an option to the graphics protocol effecting this,
* or alternatively, add a escape sequence simply disabling scrolling overall (probably not the best idea, and also possibly effected via a 0 page size? i'm unsure)

if there's already a way to do what i want, sorry to have bothered you!

**Comment by kovidgoyal** [comment]
Should be easy enough to add a field to the protocol to specify cursor movement policy, defaulting to current behavior and having an option to not move cursor, which will fix this.

**Comment by dankamongmen** [comment]
> Should be easy enough to add a field to the protocol to specify cursor movement policy, defaulting to current behavior and having an option to not move cursor, which will fix this.

this would definitely satisfy my needs. thanks!

**Comment by kovidgoyal** [comment]
On Mon, Mar 22, 2021 at 10:15:13AM -0700, Nick Black wrote:
> > Should be easy enough to add a field to the protocol to specify cursor movement policy, defaulting to current behavior and having an option to not move cursor, which will fix this.
> 
> this would definitely satisfy my needs. thanks!

already done.
