### ISSUE TITLE
Allow to launch the default action on a session file

### ISSUE THREAD

**Issue by thejavascriptman** [kovidgoyal/kitty#3414]
**Is your feature request related to a problem? Please describe.**
Please allow to configure the launch command to execute whatever is the kitty default action, for example:
* When running `kitty`, kitty would open the default shell
* When running `kitty htop`, kitty would open htop

This would allow kitty to execute stuff before the default action, for example consider the following session file
```
# enable plasma blur
launch sh -c 'xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $WINDOWID'

# feature request
launch --default
```

**Describe the solution you'd like**
* Basically I want to execute a command regardless of the way kitty is executed, to do this it would be nice to have a way to launch the default action kitty is supposed to execute

**Describe alternatives you've considered**
* Tried to add the `xprop` stuff on my `.bashrc` however it does not work when running commands like `kitty htop` or `kitty watch df -h` since `.bashrc` is never sourced
* Tried to use `launch bash` but does not work when passing a command to kitty (like `kitty htop`...)
* Also tried `launch --copy-cmdline` but it seems to not do what I need

**Additional context**
* kitty.conf has `startup_session` set

**Comment by kovidgoyal** [comment]
launch /bin/bash

**Comment by thejavascriptman** [comment]
@kovidgoyal thank you for the answer, however when using `launch /bin/bash` I can no longer pass other commands to kitty such as `kitty htop` (bash gets executed insted)

**Comment by kovidgoyal** [comment]
sorry I dont follow. You can have as many launch commands as you like in
your session file launching whatever you want.

**Comment by thejavascriptman** [comment]
Ah got it, I solved my issue by creating different bash aliases that launches kitty with different profiles.
Thank you for your support!
