### ISSUE TITLE
Some characters cause the input to reverse

### ISSUE THREAD

**Issue by mrossinek** [kovidgoyal/kitty#3415]
**Describe the bug**
I first encountered this issue a few months ago and was not sure where to place it. I opened two issues in other places but today, I finally learned that `kitty` seems to be the root of the problem. For reference, I am linking both of the other issues here ([1], [2]).

[1]: https://github.com/justinmk/vim-dirvish/issues/204
[2]: https://github.com/kyazdani42/nvim-web-devicons/issues/46

Now for the actual bug: some characters appear to cause the displayed text to be reversed, *when not followed by a space*. This may be a duplicate of #3330 but I am not sure and, hence, opening this issue.
I found the following characters as some examples of the problem. Both of them are taken from the [`nvim-web-devicons`](https://github.com/kyazdani42/nvim-web-devicons) project.
- tex icon: `ﭨ`
- webpack icon: `ﰩ`
- svg icon: `ﰟ`
- R icon: `ﳒ`

**To Reproduce**
1. Enter one of the characters above in the prompt. E.g.: `ﭨ`
2. Enter more characters immediately after. E.g. `test`
3. Observe the error

Note, that entering a `space` directly after the character, then followed by some text, does not cause the issue.
I.e. the following looks fine: `ﭨ test`

**Expected behavior**
I expect that the characters are shown in the order in which I entered them.

**Screenshots**
![screenshot_1616533096](https://user-images.githubusercontent.com/21973473/112217422-e98c6100-8c22-11eb-9bae-24c93d251e34.png)

**Environment details**
OS: Arch Linux
`uname -a: Linux ArchThinkPad 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64 GNU/Linux`

```
Output of kitty --debug-config:

kitty 0.19.3 (df7790fdfe) created by Kovid Goyal
Linux ArchThinkPad 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/max/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control y
background           Color(red=48, green=48, blue=48)
color0               Color(red=44, green=44, blue=44)
color1               Color(red=198, green=40, blue=40)
color10              Color(red=134, green=189, blue=71)
color11              Color(red=248, green=230, blue=58)
color12              Color(red=119, green=178, blue=246)
color13              Color(red=185, green=51, blue=168)
color14              Color(red=37, green=195, blue=220)
color2               Color(red=85, green=139, blue=46)
color3               Color(red=249, green=168, blue=37)
color4               Color(red=21, green=101, blue=193)
color5               Color(red=142, green=66, blue=190)
color6               Color(red=0, green=131, blue=143)
color7               Color(red=255, green=255, blue=255)
color8               Color(red=150, green=150, blue=148)
color9               Color(red=241, green=82, blue=80)
font_size            12.0
foreground           Color(red=242, green=242, blue=242)
listen_on            unix:/tmp/mykitty
symbol_map           {(61697, 61960): 'nonicon'}
```

**Additional context**
> Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

I observe this error with both, the `kitty` and `kitty-git` packages from the AUR.
Using `--config NONE` does not resolve the issue.

**Comment by kovidgoyal** [comment]
Presumably those projects are using code points marked as RTL for their
icons. Tell them not to do that, and use Private Use code points
instead. Or workaround it by setting force_ltr yes in kitty.conf.

**Comment by mrossinek** [comment]
Oh wow thanks for that workaround! I had not seen that in the documentation...
