### ISSUE TITLE
Resizing a window should optimise space for command history

### ISSUE THREAD

**Issue by refractalize** [kovidgoyal/kitty#3417]
**Is your feature request related to a problem? Please describe.**
When resizing a shell window, Kitty seems to keep the bottom of the current line the same distance from the *top* of the window. Tmux, on the other hand, keeps the current line the same distance from the *bottom* of the window.

In Kitty, this has the effect of not optimising the amount of space used for command history in a newly resized larger window.

Some screenshots to explain:

We start with the bottom window having more than one page of command history:

![image](https://user-images.githubusercontent.com/123917/112338379-0b3b2600-8cbf-11eb-943c-1a5df2feed95.png)

We resize the bottom window to full screen (stacked layout). Notice how the current line is in the middle of the page, it could be at the bottom, showing more history.

![image](https://user-images.githubusercontent.com/123917/112338471-1d1cc900-8cbf-11eb-8787-285938ffa08d.png)

Compare this with tmux, starting with a window (aka pane in tmux) with more than one page of history:

![image](https://user-images.githubusercontent.com/123917/112338749-55bca280-8cbf-11eb-8eda-b74cada4305e.png)

When we fullscreen it, the current cursor stays at the bottom of the screen showing more history:

![image](https://user-images.githubusercontent.com/123917/112338843-6bca6300-8cbf-11eb-9db1-761942aa09a8.png)

**Describe the solution you'd like**

I'd like the bottom of the output buffer to move with the **bottom** of the screen, not with the **top** of the screen, like tmux does. This has the effect of showing more command history.

**Comment by kovidgoyal** [comment]
dup of #3371
