### ISSUE TITLE
htop -- some text is not visible

### ISSUE THREAD

**Issue by xtknight** [kovidgoyal/kitty#342]
I'm not sure why this is happening but when comparing htop in MATE terminal(gnome-terminal) and kitty, kitty is missing some text. I think the text has simply become the same color as the background because the text shows up when I highlight a row in htop. See screenshot and WR_SYSC/RD_SYSC column (dark gray text). I'm using the default kitty terminal color configuration (haven't changed anything). Why might this be happening?

![htop-kitty-mate-terminal](https://user-images.githubusercontent.com/350525/36630182-8887cd6a-19a5-11e8-8ba9-bb7c246069df.png)

**Comment by kovidgoyal** [comment]
That's a bug in htop change the color scheme in htop to "broken gray" and it will be fine. https://github.com/hishamhm/htop/issues/35

**Comment by xtknight** [comment]
Okay~ thank you
