### ISSUE TITLE
Custom fonts are no longer used after updating to fontconfig 2.13.93-1 and newer on Arch Linux

### ISSUE THREAD

**Issue by xfzv** [kovidgoyal/kitty#3421]
**To Reproduce**

1. On Arch Linux, install [`nerd-fonts-jetbrains-mono` <sup>AUR</sup>](https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono/)
2. Enable testing repository and update `fontconfig` to 2.13.93-1 or newer (2:2.13.93-4 is available as I'm writting this)
3. Open a new Kitty instance, custom fonts are no longer used 
5. Downgrade `fontconfig` to 2:2.13.91+48+gfcb0420-2 (current version in extra repository as I'm writting this), problem is solved

I also have Alacritty installed using the same fonts and I don't have any issue after updating fontconfig.

**Expected behavior**

Custom fonts in `kitty.conf` should still be used after updating fontconfig

**Screenshots**
- Before, with `fontconfig` 2:2.13.91+48+gfcb0420-2:
![before](https://user-images.githubusercontent.com/78810647/112506539-c7f7ba80-8d85-11eb-881d-77f6c50b1258.png)

- After, with `fontconfig` 2:2.13.93-4:
![after](https://user-images.githubusercontent.com/78810647/112506551-c9c17e00-8d85-11eb-88a7-2f7550b17db3.png)

As you can see, no more ligatures, because JetBrains Mono Nerd Font Complete fonts are no longer used.

**Environment details**
- OS: Arch Linux
- `kitty --version`: kitty 0.19.3 created by Kovid Goyal
- `kitty --debug-config`:

```
Loaded config files: /home/username/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background      Color(red=200, green=204, blue=212)
active_tab_foreground      Color(red=40, green=44, blue=52)
adjust_line_height         3
background                 Color(red=30, green=30, blue=32)
bold_font                  JetBrains Mono Bold Nerd Font Complete
bold_italic_font           JetBrains Mono Bold Italic Nerd Font Complete
color0                     Color(red=40, green=44, blue=52)
color1                     Color(red=224, green=108, blue=117)
color10                    Color(red=152, green=195, blue=121)
color11                    Color(red=229, green=192, blue=123)
color12                    Color(red=97, green=175, blue=239)
color13                    Color(red=198, green=120, blue=221)
color14                    Color(red=86, green=182, blue=194)
color15                    Color(red=200, green=204, blue=212)
color2                     Color(red=152, green=195, blue=121)
color3                     Color(red=229, green=192, blue=123)
color4                     Color(red=97, green=175, blue=239)
color5                     Color(red=198, green=120, blue=221)
color6                     Color(red=86, green=182, blue=194)
color7                     Color(red=200, green=204, blue=212)
color8                     Color(red=171, green=178, blue=191)
color9                     Color(red=224, green=108, blue=117)
copy_on_select             clipboard
cursor                     Color(red=200, green=204, blue=212)
cursor_blink_interval      0.0
cursor_shape               3
cursor_text_color          Color(red=40, green=44, blue=52)
cursor_underline_thickness 1.0
disable_ligatures          1
enable_audio_bell          False
font_family                JetBrains Mono Medium Nerd Font Complete
font_size                  10.5
foreground                 Color(red=200, green=204, blue=212)
italic_font                JetBrains Mono Medium Italic Nerd Font Complete
open_url_modifiers         2
selection_background       Color(red=229, green=192, blue=123)
selection_foreground       Color(red=53, green=59, blue=69)
single_window_margin_width FloatEdges(left=-1000.0, top=-1000.0, right=-1000.0, bottom=-1000.0)
strip_trailing_spaces      smart
url_color                  Color(red=97, green=175, blue=239)
url_style                  1
window_margin_width        FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)
window_padding_width       FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)
Added shortcuts:
	key: -1 native_key: 65365 KeyAction(func='scroll_page_up', args=())
	key: -1 native_key: 65366 KeyAction(func='scroll_page_down', args=())
	control+c KeyAction(func='copy_or_interrupt', args=())
	control+l KeyAction(func='combine', args=(KeyAction(func='clear_terminal', args=['scroll', True]), KeyAction(func='send_text', args=['normal,application', b'\x0c'])))
	control+v KeyAction(func='paste_from_clipboard', args=())
	control+home KeyAction(func='scroll_home', args=())
	control+end KeyAction(func='scroll_end', args=())
```

**Comment by kovidgoyal** [comment]
Well if fontconfig is breaking something, youshould it report ti to
them. And generally speaking dont use patched fonts, they are
comepletely unneccessary with kitty. Uninstall it, instal the regular
font and the nerd fon separately, kitty will pick up the latter
automatically, or you can tell kitty to use it explicitly in kitty.conf
with:

symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B Symbols-1000-em Nerd Font Complete

**Comment by xfzv** [comment]
> Well if fontconfig is breaking something, youshould it report ti to them.

I'm also using JetBrains Mono Nerd Font Complete fonts in other programs (dunst, rofi, firefox, polybar, alacritty...) and kitty is the only one giving me this issue. That's why I opened an issue here and not on [fontconfig issue tracker](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues).

Anyway, I'll wait for `fontconfig` 2.13.93-4 or newer to hit extra repository on Arch and see what happens.
