### ISSUE TITLE
Weird graphical glitches/artifacts when closing kitty window

### ISSUE THREAD

**Issue by IronSideSec** [kovidgoyal/kitty#3423]
**Describe the bug**
When I have more than one kitty window open, and am closing one of them, weird graphical glitches/artifacts can be seen when the terminal is being closed..This does not happen when I have only one kitty window open, or if I have default kitty background (either no config file, or config is not touching colors).

**To Reproduce**
1. Change background colors in kitty.conf
2. Open more than one kitty window
3. Close one of them

**Expected behavior**
No glitches/artifacts when closing additional terminal windows.

**Screenshots**
https://ibb.co/jySyhxB

**Environment details**
OS: Arch Linux, latest (git) sway/wlroots/mesa (amd gpu)

```
Linux host 5.11.9-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 24 Mar 2021 18:53:59 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/user

https://user-images.githubusercontent.com/60072908/112634536-01d6c880-8e3b-11eb-965b-5ab5030a88d8.mp4

/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background           Color(red=46, green=52, blue=64)
color0               Color(red=55, green=62, blue=77)
color1               Color(red=148, green=84, blue=93)
color10              Color(red=128, green=149, blue=117)
color11              Color(red=178, green=158, blue=117)
color12              Color(red=104, green=128, blue=154)
color13              Color(red=140, green=115, blue=140)
color14              Color(red=109, green=150, blue=165)
color15              Color(red=174, green=179, blue=187)
color2               Color(red=163, green=190, blue=140)
color3               Color(red=235, green=203, blue=139)
color4               Color(red=129, green=161, blue=193)
color5               Color(red=180, green=142, blue=173)
color6               Color(red=143, green=188, blue=187)
color7               Color(red=236, green=239, blue=244)
color8               Color(red=76, green=86, blue=106)
color9               Color(red=191, green=97, blue=106)
cursor               Color(red=216, green=222, blue=233)
cursor_text_color    Color(red=46, green=52, blue=64)
enable_audio_bell    False
foreground           Color(red=216, green=222, blue=233)
input_delay          1
linux_display_server wayland
mouse_hide_wait      -1.0
scrollback_lines     10000
selection_background Color(red=76, green=86, blue=106)
selection_foreground Color(red=216, green=222, blue=233)
sync_to_monitor      False
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
This will be a driver bug. I cannot replicate on my Arch system with an
intel gpu, dont currently have an amd gpu to test with. See the long
history of mesa bugs causing graphical corruption in kitty. I suggest
trying older versions of mesa and amd drivers.

**Comment by IronSideSec** [comment]
Thanks for a prompt response, I should've mention that I tried downgrading to regular mesa but this have not solved it, sorry. But if you believe this is related to mesa, I'll try to report a bug report there.

**Comment by kovidgoyal** [comment]
Btw from your screenshot its not clear what exactly is corrupted. Is it the remaining window or the entire screen? If it is the entire screen it is *definitely* a driver or maybe compositor bug. If it is the remaining window, does it go away ifyou resize the window or do something else to cause it to redraw.

**Comment by IronSideSec** [comment]
I also tried to attach a short vid I created, that would show it better, but I think it is not getting attached.. Added it one more time, hopefully you will get it -  basically the glitches happen for like a split second when the kitty window is being closed, as soon as its fully gone the glitches does not occur in entire screen. just a part of kitty window. Resizing/moving kitty windows does not produce the same effect.

https://user-images.githubusercontent.com/60072908/112637144-23857f00-8e3e-11eb-8119-4b66464fed47.mp4

**Comment by kovidgoyal** [comment]
Yeah that's definitely a driver issue.

**Comment by IronSideSec** [comment]
OK, thanks. Off to mesa gitlab I go then.

**Comment by quietvoid** [comment]
I can consistently reproduce this when resizing kitty on sway, with mesa 21 and amdgpu.
The artifacts do not happen with `linux_display_server=x11`
