### ISSUE TITLE
? displayed instead of unicode character

### ISSUE THREAD

**Issue by jimrs** [kovidgoyal/kitty#3425]
**Describe the bug**
Hi, I installed kitty today through homebrew on macOS, I have some unicode characters in directory names and they are not displayed properly. On iTerm and the vanilla Terminal, it works ok.

**Expected behavior**
Show the characters.

**Screenshots**
<img width="651" alt="Screenshot 2021-03-27 at 19 37 46" src="https://user-images.githubusercontent.com/15998217/112730820-f0251c00-8f33-11eb-93d8-57c9479782bc.png">

**Environment details**
OS: macOS Mojave 10.14.6

```
kitty 0.19.3 created by Kovid Goyal
Darwin Jims-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.14.6 BuildVersion:	18G8022
Loaded config files: /Users/jim/.config/kitty/kitty.conf

Config options different from defaults:
```

**Additional context**
I tried `kitty --config NONE` and it *works*. What the hell is going on? I also tried `kitty --debug-font-fallback` and it *works*, but if I launch the application normally, it never works. I also tried changing the font family to Monaco (which works in iTerm) but that doesn't help.

This is `kitty --debug-font-fallback`
```
[086 19:42:42.347580] Preloaded font faces:
[086 19:42:42.347632] normal face: /System/Library/Fonts/Menlo.ttc
[086 19:42:42.347645] bold face: /System/Library/Fonts/Menlo.ttc
[086 19:42:42.347655] italic face: /System/Library/Fonts/Menlo.ttc
[086 19:42:42.347665] bi face: /System/Library/Fonts/Menlo.ttc
```

**Comment by jimrs** [comment]
To clarify, it should show
`OneDrive - Vysoká škola ekonomická v Praze`.

**Comment by kovidgoyal** [comment]
Set your LANG env var toa UTF-8 bsed one and you will be fine.

export LANG=en_US.UTF-8

for example.

**Comment by jimrs** [comment]
thank you sir, it seems to work now
