### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dluksza** [kovidgoyal/kitty#3428]
First of all, thank you for your hard work and dedication and most importantly creation of Kitty. This is an amazing piece of software.

Could we have a new release, please? The last official release was on the 19th of December 2020 which is over three months already and there was a lot of changes in the master branch since then. Would be really nice to have a new official build. Also would be amazing if you could include a version for M1 Macs.

Thank you in advance!

**Comment by kovidgoyal** [comment]
There will be a new release when the RFCs mature. As for M1 build, it's
on my TODO list.

**Comment by damnhipster** [comment]
For those who come by this, the M1 build of kitty relates to the following issue when trying to run homebrew from the kitty terminal: https://github.com/Homebrew/brew/issues/10313. Once kitty can run natively on M1, we shouldn't have to prefix homebrew commands with `arch -arm64` anymore.

**Comment by horta** [comment]
I've been compiling it on my my mac mini with M1 CPU. Let me know if you need help with it.

**Comment by kovidgoyal** [comment]
Building kitty itself for M1 is trivial, what I need is to buy an M1 machine for testing, and to add supports for building universal binaries for all of kitties dependencies to bypy.

**Comment by horta** [comment]
I can give you an ssh to my mac mini if that is easier for you...

**Comment by kovidgoyal** [comment]
No, not really, I'd need graphical access since kitty is a graphical
application and anyway I am not comfortable supporting software for
platforms which I dont have easy local access to.

On Mon, Apr 19, 2021 at 03:41:26PM -0700, Danilo Horta wrote:
> I can give you an ssh to my mac mini if that is easier for you...
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3428#issuecomment-822835889

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by horta** [comment]
Crowd founding wouldn't help with that?

**Comment by kovidgoyal** [comment]
Here's a universal kitty build: https://download.calibre-ebook.com/betas/kitty-0.20.2.dmg  I have no wat to test it on apple silicon.

**Comment by horta** [comment]
It works just fine! typing `arch` inside the terminal gives me "arm64" which must be the built it is running.
