### ISSUE TITLE
Change vim/nvim cursor based on current mode.

### ISSUE THREAD

**Issue by Pistrie** [kovidgoyal/kitty#3429]
**Is your feature request related to a problem? Please describe.**
I recently switched from Alacritty to kitty, and I noticed that my cursor doesn't change to the single line when in insert mode like it did in Alacritty. I like this single line cursor instead of always having the same cursor because it makes it more clear whether you are in insert mode or not.

**Describe the solution you'd like**
Allow vim/nvim to change the cursor based on the current mode.

**Describe alternatives you've considered**
Not applicable

**Additional context**
kitty:
![2021-03-30_10-37](https://user-images.githubusercontent.com/39904003/112959872-2802ae00-9144-11eb-961c-14c182639300.png)
alacrity:
![2021-03-30_10-38_1](https://user-images.githubusercontent.com/39904003/112959875-289b4480-9144-11eb-9f6a-c90c54817f25.png)
![2021-03-30_10-38](https://user-images.githubusercontent.com/39904003/112959877-2933db00-9144-11eb-8a5f-805db4ae1209.png)

**Comment by kovidgoyal** [comment]
```vimrc
        " Change the cursor in different modes
        let &t_SI = "\e[5 q"
        let &t_SR = "\e[3 q"
        let &t_EI = "\e[2 q"
```
