### ISSUE TITLE
Reload config on SIGUSR1

### ISSUE THREAD

**Issue by kdrag0n** [kovidgoyal/kitty#343]
It'd be great if there was a mechanism to reload the configuration on-the-fly, so new color schemes can be instantly applied.

**Comment by kovidgoyal** [comment]
Not something I care to implement, but patches are welcome. If all you want to do is change colors, you dont need to do it via the config, you can do it via escape codes. A bit of googling should get you the escape codes you need.

**Comment by kdrag0n** [comment]
I'm already using escape codes. They work, but don't affect the selection
colors, so selected text is very hard to read depending on the scheme.

**Comment by kovidgoyal** [comment]
IIRC there are escape codes to change the selection colors as well, though I may be mis-remembering.

**Comment by kdrag0n** [comment]
Doesn't seem like it. If that does exist, could you link a page describing
it?

**Comment by kovidgoyal** [comment]
http://invisible-island.net/xterm/ctlseqs/ctlseqs.html search the page for dynamic colors.

**Comment by kdrag0n** [comment]
I see, I'll try using that. Thanks for the reference!
