### ISSUE TITLE
Impossible to select correct text in backlog when output is printed

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#3431]
**Describe the bug**
If a process is generating output in kitty, and you scroll up and try to select text, what you select will not match where you placed the cursor. Specifically the start of the selection will often be a couple of lines above or below where the cursor were when you started the selection, while the end of the selection will follow the mouse correctly. Double clicking a word to select it will mark multiple lines instead. When a selection is active, a single click will select something else instead of removing the selection.

**To Reproduce**
1. Run a process that continuously generates output, e.g. `for i in {1..100000}; do echo $i; sleep 0.01; done`
2. Scroll up so you see a part of the backlog instead of the new output.
3. Try to select text.

**Expected behavior**
Selection should work the same way as when no output is printed.

**Screenshots**
Since this is very easy to reproduce for me, I don't think a screenshot/screencapture is necessary, but if you can't reproduce, tell me and I'll provide it.

**Environment details**
OS: Arch Linux

I ran with `--config NONE`, so `--debug-config` is just:

```
kitty 0.19.3 (1e6fe7785a) created by Kovid Goyal
Linux elaine 5.10.23-1-lts #1 SMP Thu, 11 Mar 2021 15:32:34 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11

Config options different from defaults:
```

**Comment by trygveaa** [comment]
Hm, it still doesn't work for me. See the attached video. This is with cb515157 and `--config NONE`.

https://user-images.githubusercontent.com/601966/113363888-6968a880-9352-11eb-8c23-26d8bbfa09f3.mp4

**Comment by trygveaa** [comment]
Perfect, thanks!

**Comment by zw963** [comment]
I confirm it works when install kitty-git from arch linux.
