### ISSUE TITLE
Request / question

### ISSUE THREAD

**Issue by fluffynuts** [kovidgoyal/kitty#3432]
When working with windows, I'd really like to direct where windows open - ie, whether to split vertically or horizontally. Whilst the automatic layout is quite clever, it doesn't necessarily choose what I want. Ideally, I'd like to bind `ctrl+shift+right` to split horizontally (ie open a window to the right) and `ctrl+shift+down` to split vertically (ie open a window below). I haven't seen how to do so from the documentation so this is either a question (how do I accomplish this?) or a request (please provide a way to accomplish this).

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/layouts.html#the-splits-layout

**Comment by fluffynuts** [comment]
sounds like what I want, but, (please excuse, newbie question)

I create `~/kitty.conf` containing:

```
enabled_layouts split
map kitty_mod+right launch --location=vsplit
map kitty_mod+down launch --location=hsplit
```

but ctrl+shift+right doesn't split vertically, nor does ctrl+shift+down split horizontally, so I'm left assuming that either I can't read the docs properly on what to put in my kitty.conf, _or_ it's read from somewhere other than ~/kitty.conf

if you have time, I'd really appreciate a pointer in the right direction

**Comment by kovidgoyal** [comment]
Are you actually running up-to-date kitty? Most likely your versio
of kitty is too old to support splits.

**Comment by fluffynuts** [comment]
I'm running from an emerge inside Gentoo, version 0.19.3, which seems to be the latest release on GitHub.

**Comment by kovidgoyal** [comment]
You have the wrong location for kitty.conf. Press ctrl+shift+f2 inside kitty to edit the config file or read the help for the --config option.

**Comment by fluffynuts** [comment]
Thanks - that's why I mentioned the location in one of the replies: I assumed that that my file was not in the expected location. I understand that the location may differ between platforms. It would really help if the default locations were documented at https://sw.kovidgoyal.net/kitty/index.html#configuring-kitty, which mentions `kitty.conf`, but not _where_ to find it.

**Comment by kovidgoyal** [comment]
That section links to https://sw.kovidgoyal.net/kitty/conf.html which
mentions the location in the first paragraph.

**Comment by fluffynuts** [comment]
the link you mention _does_ indeed mention the location

searching https://sw.kovidgoyal.net/kitty/index.html#configuring-kitty for `config/kitty.conf` yields no results. Perhaps something is out of date. 

At any rate, I've switched to my default console being kitty.

I'm not of any importance, but I can advise that reading & accepting user input as-is before defending might be to your own advantage. Twice, in this thread, I have clearly stated my observations and you've chosen defense over understanding.
