### ISSUE TITLE
Kitty hates /r/wallstreetbets and GME. Lacks true real diamond hands.

### ISSUE THREAD

**Issue by EvanCarroll** [kovidgoyal/kitty#3437]
So here I was in IRC. And I wanted to type **DIAMOND HANDS** 💎🤝 but I immediately ran into a road block. I couldn't find the glyphs I needed in my trusty unicode searching tool <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>U</kbd>. My emojis of choice were absent.

There is no 💎. Searching for _diamond_ all I found was 🔷 which is hardly worth anything.

Interestingly I could find 🧻. You don't go to the moon with 🧻🤝.... You need 💎🤝 if you want 🚀🚀🚀.

**Comment by kovidgoyal** [comment]
The name of that character in the unicode standard is "Gem stone"
https://www.compart.com/en/unicode/U+1F48E type gem and it will come up
fine. That said I can add diamond as a synonym for it to the index.
