### ISSUE TITLE
Drawn block cursor offset on one tab changes when opening new tab

### ISSUE THREAD

**Issue by xtknight** [kovidgoyal/kitty#344]
Steps to reproduce (at least, on my system):
  - Start kitty.
  - ('open new tab' keyboard shortcut)
  - ('go one tab left' keyboard shortcut)

The first tab then looks like this with the cursor butted up right against the '$' instead of spaced.  '$[]' instead of '$ []'. The second tab is fine (usually). When I start typing in the first tab, suddenly the cursor moves to the proper position.

![cursor-offset](https://user-images.githubusercontent.com/350525/36637120-352a98d2-1a18-11e8-8e1c-6cf6d7b1770f.png)

If I return to the second tab and perform 'open new tab' again there is no issue on the third tab. It's a kind of inconsistent issue but is always reproducible on my system in the steps I've outlined at the top.

**Comment by kovidgoyal** [comment]
I cannot replicate that on my machine. What happens is that when you open the first new tab, the tab bar becomes visible, so the shell running in the original tab receives a window resized signal. Most shells will redraw the prompt line when receiving this signal. For some reason your shell is not doing so. What shell is this, I tried both bash and zsh and they redraw as expected.

**Comment by xtknight** [comment]
I'm just using bash on Ubuntu 16.04.4 LTS.

    GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

I updated to master and tested, and it seems to work! I'm not sure if this means that you were able to reproduce and identify the issue or not, but it anyways seems to fix it on my end.

Thanks for your hard work and prompt response.

**Comment by kovidgoyal** [comment]
No, I wasn't able to reproduce, but it was quite easy to guess the cause.
