### ISSUE TITLE
Umlaut characters buggy

### ISSUE THREAD

**Issue by real-esekyl** [kovidgoyal/kitty#3443]
**Describe the bug**
When you use small umlaut characters ä,ö,ü, it prints it twice and puts the cursor in between. When you try to delete, it deletes the last character of your shell prompt as well.

Unfortunately this happens within the history as well, so moving through the history will delete characters of your prompt. Here, even the Tilde character deletes prompt characters, so every command involving the home directory weirdens the line more and more. 

Strangely it works quite well for capital letters Ä, Ö and Ü. You need to press BackSpace twice to delete them though... Both input and history of those characters are fine!

To Reproduce**
1. Type "ä" or "ö" or "ü" on German keyboard
2. Try to delete the character...
3. (optional) press cursor-up for history

**Expected behavior**
showing and deleting every character as shown on the keyboard.

**Environment details**
OS: Arch Linux x86_64
Shell: bash 5.1.4 / fish 3.2.1 both don't work
```
Output of kitty --debug-config
Running under: X11

Config options different from defaults:
background_opacity   0.8
force_ltr            True (<< tried that because of other threads)
foreground           Color(red=255, green=150, blue=22)
selection_background Color(red=255, green=150, blue=22)
```

`kitty --config NONE` did not work, force_ltr true did not work.

**Comment by kovidgoyal** [comment]
Works fine for me. Make sure your LANG env var is correct and the locale
it points to is properly generated.

**Comment by real-esekyl** [comment]
Found that my LANG var was wrong when I tried to fix something else! Thank you!
