### ISSUE TITLE
Unknown option: --detach

### ISSUE THREAD

**Issue by vpoiesz** [kovidgoyal/kitty#3447]
**Describe the bug**
Running kitty with the `--detach` flag produces an "Unknown option" error.

**To Reproduce**
1. run `kitty --detach`
1. See error

**Expected behavior**
Work as described [here](https://sw.kovidgoyal.net/kitty/invocation.html#cmdoption-kitty-detach).

**Environment details**
OS: macOS Big Sur 11.2

```
kitty 0.19.3 created by Kovid Goyal
Darwin <hostname> 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2 BuildVersion:	20D64
Loaded config files: /Users/<username>/.config/kitty/kitty.conf

Config options different from defaults:
font_size            12.0
macos_thicken_font   0.5
tab_bar_edge         1
window_padding_width FloatEdges(left=5.0, top=4.0, right=4.0, bottom=0)
Changed shortcuts:
	super+t KeyAction(func='new_tab_with_cwd', args=['!neighbor'])
```

**Additional context**
Installed via Homebrew

This is not a problem for me, just figured I would report the error.

**Comment by kovidgoyal** [comment]
--detach is linux specific.
