### ISSUE TITLE
Allow combining --session option with --single-instance

### ISSUE THREAD

**Issue by vpoiesz** [kovidgoyal/kitty#3448]
**Is your feature request related to a problem? Please describe.**
The `--single-option` flag has no effect when `--session` is specified as well.

**Describe the solution you'd like**
I would like to be able to start up a new session within the same application instance that is currently running. The current behavior opens a new instance which crowds the macOS dock and makes navigating more difficult. It also means that the child process is bound to the parent terminal window, so then I have to go through all the hoops to detach the process and redirect the output messages etc.

**Describe alternatives you've considered**
There's no workarounds as far as I can tell, unless the session script itself has a way to avoid forking a new application instance.

**Additional context**
Kitty 0.19.3 installed via Homebrew on macOS Big Sur 11.2

Thank you for this lovely piece of software! The level of customization is truly incredible. Getting the behavior of session scripts fine-tuned would really optimize my workflow!

**Comment by kovidgoyal** [comment]
Use remote control for that, it's a super set of session scripts.

https://sw.kovidgoyal.net/kitty/remote-control.html
