### ISSUE TITLE
Session script `launch` command should start an interactive shell first

### ISSUE THREAD

**Issue by vpoiesz** [kovidgoyal/kitty#3449]
**Is your feature request related to a problem? Please describe.**
If I put this in a session file:
```
new_tab 
cd ~/workspace/my_project
launch yarn test
```

When the command finishes it will close the tab. This isn't very helpful for most use cases. Instead I want to be dropped into a shell and see the output of the command. Even for long-running services (eg webserver), if the process crashes I want to be able to see it, not just have the tab closed.

Also if my command is just `launch zsh` as the examples show, we'll be at $SHLVL == 2 which is unnecessarily nested.

**Describe the solution you'd like**
The session file should have a way to launch an interactive shell, then run the commands as if I had typed them in myself.

**Describe alternatives you've considered**
I'm using the workarounds described in [this post](https://superuser.com/questions/91881/invoke-zsh-having-it-run-a-command-and-then-enter-interactive-mode-instead-of). It still places us in $SHLVL == 2.

**Additional context**
Kitty 0.19.3 installed via Homebrew on macOS Big Sur 11.2

Thanks so much for your consideration!

**Comment by kovidgoyal** [comment]
launch sh -c "whatever command you want; exec zsh --login"

**Comment by vpoiesz** [comment]
Thank you for the support, @kovidgoyal !
