### ISSUE TITLE
Ctrl+Alt+Key sends nothing for most keys

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#345]
Just noticed that some (rare) Ctrl+Alt+Key bindings I use don't work. `showkey -a` shows nothing for most keys (but not for all).

If this is not a bug but a feature, may be there should be some configuration option for Alt+<combination> to send ESC followed by key code for <combination> (our discussion on #264 may be relevant here).

**Comment by kovidgoyal** [comment]
Ctrl+alt (indeed multiple modifiers in general) are not useable with traditional terminal escape codes, see the keyboard handling section of https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc

Try it something like gnome-terminal, you will see all sorts of weird and inconsistent results, for example, Ctrl+Atl+4 and Ctrl+4 generate the exact same bytes, but Ctrl+alt+1 and Alt+1 generate the exact same bytes. 

You want to use multiple modifiers, you need to convince terminal program maintainers to add support for the extended keyboard protocol kitty uses. However, given that the entire terminal exocsystem is pretty solidly ossified I doubt you'll have a lot of luck.

**Comment by sergei-dyshel** [comment]
I agree with you on the fact that there many keys and combinations that don't have consistent or distinguishable codes: `Ctrl/Alt+<digit>`, Backspace/Delete, `Ctrl+Shift+<key>` and many many more.

They are, however, combinations which are consistent in (at least) majority of *modern* terminal emulators, such as `Ctrl+<letter>`, `Alt+<letter>`. This also holds for `Ctrl+Alt+<letter>` which is pretty solid key chord IMHO and is used as default binding in some popular console programs (see [emacs default keys](https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf) for example). Also tmux supports 'Ctrl+Alt+<letter>' bindings pretty well.

As for your protocol extension, I've read it and it looks well-thought and promising. One day I'll try to utilize it in my Vim configuration for complex chords (although as Vimmer I prefer to use less "chordy" bindings). 

But please think again about Ctrl+Alt+letter bindings :smile:

**Comment by kovidgoyal** [comment]
Really, Ctrl+alt+letter works differently in xterm, gnome-terminal and does not work at all in the linux console on my system. I'm amazed there are applications that actually use it, given how inconsistent it is. Not to mention the usual problem with alt based shortcuts of not being able to distinguish between esc,key and alt+key.

But sure, since you say it is actually used by some programs, it should do no harm to add it to kitty.
