### ISSUE TITLE
`kitty @ new-window --match window_id:<id>` does not seem to work

### ISSUE THREAD

**Issue by vpoiesz** [kovidgoyal/kitty#3451]
**Describe the bug**
I get error "No matching tabs for expression: window_id:<id>" even though there is a matching window 

**To Reproduce**
Create a script like so:

```
#!/bin/zsh

projectDir="~/workspace/my_project"
windowId1=$(kitty @ new-window --new-tab --cwd "$projectDir")
kitty @ ls
windowId2=$(kitty @ new-window --match window_id:$windowId1 --cwd "$projectDir")
```

Run the script and note the error message at the end. Review the json from `kitty @ ls` to see that a matching window_id should exist.

**Expected behavior**
A new tab should be created with two windows within it. According to [these docs](https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-new-window) `window_id` should be a valid match criteria.

**Screenshots**

Here is the output of my run of the script:

```
[
  {
    "id": 1,
    "is_focused": true,
    "platform_window_id": 18622,
    "tabs": [
      {
        "active_window_history": [
          1
        ],
        "id": 1,
        "is_focused": false,
        "layout": "fat",
        "title": "./start-project.sh",
        "windows": [
          {
            "cmdline": [
              "-zsh"
            ],
            "cwd": "/Users/<username>/.config/kitty",
            "env": {},
            "foreground_processes": [
              {
                "cmdline": [
                  "/Applications/kitty.app/Contents/MacOS/kitty",
                  "@",
                  "ls"
                ],
                "cwd": "/Users/<username>/.config/kitty",
                "pid": 19511
              },
              {
                "cmdline": [
                  "/bin/zsh",
                  "./start-project.sh"
                ],
                "cwd": "/Users/<username>/.config/kitty",
                "pid": 19482
              }
            ],
            "id": 1,
            "is_focused": false,
            "pid": 17143,
            "title": "./start-project.sh"
          }
        ]
      },
      {
        "active_window_history": [
          7
        ],
        "id": 6,
        "is_focused": true,
        "layout": "fat",
        "title": "zsh",
        "windows": [
          {
            "cmdline": [
              "-zsh"
            ],
            "cwd": "/Users/<username>/workspace/my_project",
            "env": {},
            "foreground_processes": [
              {
                "cmdline": [
                  "-zsh"
                ],
                "cwd": "/Users/<username>/workspace/my_project",
                "pid": 19485
              }
            ],
            "id": 7,
            "is_focused": true,
            "pid": 19485,
            "title": "zsh"
          }
        ]
      }
    ]
  }
]
No matching tabs for expression: window_id:7
```

We can see that tab id 1 is where I ran the script. Tab id 6 was created by the script and contains window id 7. Yet the final command fails unable to match on window_id:7.

**Environment details**
OS: macOS Big Sur 11.2

```
kitty 0.19.3 created by Kovid Goyal
Darwin <hostname> 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2 BuildVersion:	20D64
Loaded config files: /Users/<username>/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control y
font_size            12.0
macos_thicken_font   0.5
tab_bar_edge         1
window_padding_width FloatEdges(left=5.0, top=4.0, right=4.0, bottom=0)
Changed shortcuts:
	super+t KeyAction(func='new_tab_with_cwd', args=['!neighbor'])
```

Thank you!

**Comment by kovidgoyal** [comment]
id:whatever not window_id:whatever

**Comment by vpoiesz** [comment]
Hi @kovidgoyal, I based this report off of what is said in the docs, so maybe those are out of date now:

<img width="695" alt="match-option" src="https://user-images.githubusercontent.com/11723827/113968723-7d942600-97e8-11eb-8fac-da5fcd38d5f1.png">

What I would like to achieve is open a new tab and then put two windows inside it. Since there is no `@ new-tab` command, I create the first window with `--new-tab` option which returns the _window_ id. Then if I can do `@ new-window --match window_id:<id just created>` it would work perfectly to launch the window in the new tab that was created. Without this option I will have to issue the `@ ls` command and parse through the json to get the new tab id... which is a bunch of extra steps.

Is there another way to do this I am missing? Thank you!

**Comment by kovidgoyal** [comment]
window_id works when you are matching a tab. Not when you are matching
windows. If you want to open a new tab with two windows, use:

kitty @ launch --type tab; kitty @ launch

**Comment by vpoiesz** [comment]
Hi @kovidgoyal , thanks for the info and suggestion.

It seems like it might be good to update the documentation, since I am still pretty confused about the part in the screenshot. That is from the `new-window` section and it says "The tab to match." My goal is to launch the new window in a certain tab, so `--match` seems like the right option, and the filter `window_id:<a window id>` seems to imply that it will use the tab that contains an existing window id.

**Comment by kovidgoyal** [comment]
On Wed, Apr 07, 2021 at 09:54:08PM -0700, Victor Poiesz wrote:
> It seems like it might be good to update the documentation, since I am still pretty confused about the part in the screenshot. That is from the `new-window` section and it says "The tab to match." My goal is to launch the new window in a certain tab, so `--match` seems like the right option, and the filter `window_id:<a window id>` seems to imply that it will use the tab that contains an existing window id.

That is correct. If you use new-window then --match is to match tabs and
window_id will match a tab containing a window with that id.

**Comment by vpoiesz** [comment]
Hi @kovidgoyal, thanks for clarifying. Here is my script again:

```
windowId1=$(kitty @ new-window --new-tab --cwd "$projectDir")
windowId2=$(kitty @ new-window --match window_id:$windowId1 --cwd "$projectDir")
```

Is that the correct usage according to your description? This produces the error "No matching tabs for expression: window_id: <number>"

**Comment by kovidgoyal** [comment]
Yes, that is correct and it works fine for me. I end up with a new tab
with two windows in it, as expected.

**Comment by kovidgoyal** [comment]
First run from master and see if you can reproduce there. Or just use the launch commands I mentioned earlier which dont require an id at all.
