### ISSUE TITLE
Memory Leak in kitty

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#3455]
**Describe the bug**
When closing a new tab, kitty does not seem to release memory.  The resident memory keeps on climbing up.

**To Reproduce**
1. Launch kitty like this:
    ```
    kitty -o allow_remote_control=yes -o enabled_layouts=tall &
    ```
2. Take a note of memory usage.  I used:
    ```
    top -p `pidof kitty`
    ```
2. Within the kitty window, execute:
    ```
    for i in {1..50}; do kitty @ launch --type=tab --tab-title "Tab$i" bash; done; for i in {1..50}; do kitty @ close-tab; done
    ```
3. Take a note of memory usage

**Expected behavior**
Memory usage shall go back to the value in Step 2.

**Observed behavior**
Memory climbed up significantly.  The above example opens and closes 50 tabs.  I ran 500 tabs on my 32GB RAM machine and collected the following output:

**Screenshots**
```
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.2 us,  1.5 sy,  0.0 ni, 91.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  31896.4 total,  19023.8 free,   6545.3 used,   6327.3 buff/cache
MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.  22100.1 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  81471 salman    20   0 7245836   1.1g  46332 S   0.0   3.4   0:08.30 kitty 
```
Notice that resident memory climbed to 1.1GB!  Why doesn't it drop to 73MB, which is the starting point?

**Environment details**
OS: Name and version of operating system(s)

Ubuntu 20.04LTS.  kitty installed from standard repos.

```
$ kitty --debug-config
kitty 0.15.0 created by Kovid Goyal
Linux byteevo-scm 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf
Running under: X11

Config options different from defaults:
update_check_interval 0.0
```

**Comment by kovidgoyal** [comment]
I cannot reproduce. Your version of kitty is ancient. Update.

**Comment by salmankhilji** [comment]
I am able to reproduce this issue on kitty 0.19.3, which I downloaded and installed on Ubuntu 20.04:

```
$ kitty --debug-config
kitty 0.19.3 (3ce04c3e4b) created by Kovid Goyal
Linux byteevo-scm 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Running under: X11

Config options different from defaults:
```

I don't have any kitty.conf file.

After 500 iterations, my resident memory is at 1.1GB.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2482 salman    20   0 8250356   1.1g  47544 S   0.0   3.6   0:10.42 kitty
```

**Comment by salmankhilji** [comment]
It _could_ be that I do not understand how `top` reports memory usage.  When running the same experiment (50 iterations) with `valgrind --tool=massif`, I see that the memory usage dropped.

```
$ ms_print massif.out.48853 
--------------------------------------------------------------------------------
Command:            kitty -o allow_remote_control=yes -o enabled_layouts=tall
Massif arguments:   (none)
ms_print arguments: massif.out.48853
--------------------------------------------------------------------------------


    MB
804.0^                                                             ##         
     |                                                             #          
     |                                                          :::# :        
     |                                                         ::: # :        
     |                                                       @@::: # :        
     |                                                    @@@@ ::: # :::      
     |                                                   :@@ @ ::: # ::       
     |                                                  @:@@ @ ::: # :: :     
     |                                                @@@:@@ @ ::: # :: :     
     |                                                @@@:@@ @ ::: # :: :     
     |                                              ::@@@:@@ @ ::: # :: ::    
     |                                            @@: @@@:@@ @ ::: # :: ::    
     |                                            @ : @@@:@@ @ ::: # :: ::    
     |                                          @@@ : @@@:@@ @ ::: # :: ::    
     |                                         @@ @ : @@@:@@ @ ::: # :: ::    
     |                                         @@ @ : @@@:@@ @ ::: # :: :::   
     |                                       @@@@ @ : @@@:@@ @ ::: # :: :::   
     |                                      :@ @@ @ : @@@:@@ @ ::: # :: :::   
     |                                     @:@ @@ @ : @@@:@@ @ ::: # :: ::::  
     |                                    @@:@ @@ @ : @@@:@@ @ ::: # :: ::::: 
   0 +----------------------------------------------------------------------->Gi
     0                                                                   1.784

```

**Comment by salmankhilji** [comment]
Also with valigrind `memcheck` tool, I get

```
==50433== HEAP SUMMARY:
==50433==     in use at exit: 1,452,229 bytes in 3,705 blocks
==50433==   total heap usage: 140,137 allocs, 136,432 frees, 1,181,018,622 bytes allocated
==50433== 
==50433== LEAK SUMMARY:
==50433==    definitely lost: 0 bytes in 0 blocks
==50433==    indirectly lost: 0 bytes in 0 blocks
==50433==      possibly lost: 1,056 bytes in 2 blocks
==50433==    still reachable: 1,451,173 bytes in 3,703 blocks
==50433==         suppressed: 0 bytes in 0 blocks
```

So it could be that we are ok.

**Comment by kovidgoyal** [comment]
I have never understood how top reports memory usage. In fact, I dont
think process memory usage can be reported accurately on Linux at all.
For leak detection, I use ASAN. You can do the same by running

make asan

then asan will report all leaks at exit. There will be some, but that
amount will definitely not be 1GB

**Comment by kovidgoyal** [comment]
Actually thinking about it there might be something worth looking into here. Most likely the large top figures are caused by mmap(). It may be worth it to reduce those so people like you are not confused in the future :) 

It should be easy to verify my mmap hypothesis by using --pages-as-heap for massif

**Comment by kovidgoyal** [comment]
Yup, I was correct. Run
```
make debug && PYTHONMALLOC=malloc valgrind --tool=massif --pages-as-heap=yes kitty/launcher/kitty
```

and you get the same memory profile as in top. with memory consumption steady at ~ 1GB. This is just the libc's free not releasing memory that kitty allocated.

Now run 
```
make debug && PYTHONMALLOC=malloc MALLOC_MMAP_THRESHOLD_=64 valgrind --tool=massif --pages-as-heap=yes kitty/launcher/kitty
```

memory usage peaks at 1GB and falls to 700MB after tabs are closed. The remaining extra memory is all in arenas used by the glx and gpu drivers, not kitty code. Presumably they maintain their own memory arenas and dont return memory to the OS even though the application releases them.

**Comment by RedDofamine** [comment]
And....how to fix that!?

**Comment by Safari77** [comment]
Why does gnome-shell memory usage increase by 948 KiB when I just switch tab in kitty?
```
sma () 
{ 
    if [[ ! -z "${1}" ]]; then
        local _smPID=$(pidof -s "${1}");
        if [[ ! -z "${_smPID}" ]]; then
            cat /proc/"${_smPID}"/smaps_rollup;
        fi;
    fi
}
```
`sma gnome-shell | grep Pss_Shmem`

seems to be caused by adding 
`file=/memfd:glfw-shared\040(deleted) dirty=235 active=0 N0=235 kernelpagesize_kB=4`
visible in /proc/$(pidof -s gnome-shell)/numa_maps

gnome-shell's memory usage goes to normal when I quit kitty.  but why is there such a crazy memory usage increase?

**Comment by kovidgoyal** [comment]
That's the memory needed to render GNOME's stupid client side
decorations.

**Comment by kovidgoyal** [comment]
That will presumably be gnome shell never freeing older buffers when they are replaced by newer ones.

**Comment by Safari77** [comment]
Should kitty destroy the unused back buffers?
Or what's the way forward...
https://gitlab.gnome.org/GNOME/mutter/-/issues/2465

**Comment by kovidgoyal** [comment]
I dont follow. The memory leak is in gnome shell not in kitty, how would
kitty releasing buffers never attached fix a leak in gnome shell? If the
buffer is never attached it should not contribute to gnome shell's
memory usage at all, no? That said I am no expert in Wayland protocols
so if there is something kitty should be doing differently am happy to
accept a patch or more detailed description of what.

**Comment by kovidgoyal** [comment]
And this commit implements the suggestion in the mutter bug report, of explicitly destroying buffers that were never attached and committed. 

https://github.com/kovidgoyal/kitty/commit/6890e265b651835eb6168ef56a68315de4a54a52

In some brief testing it seems to cure the leak in gnome-shell.
