### ISSUE TITLE
Font rendering too thin

### ISSUE THREAD

**Issue by GustavoPrietoP** [kovidgoyal/kitty#3458]
I've been using alacritty and now i want to switch to kitty, however, I set the same font in alacritty and kitty (JetBrainsMono) but it seems like kitty renders the font way to thin.

alacritty is in the left and kitty is highlighted in green.
![Screenshot from 2021-04-08 15-23-11](https://user-images.githubusercontent.com/70907734/114087767-46725300-9882-11eb-90fa-19d00b585bf9.png)

i found this issue from 2020, https://github.com/kovidgoyal/kitty/issues/2580#issue-605861631 but the solution is macOS specific and i would like to know if there is a way to get something similar working in Linux?

**Comment by kovidgoyal** [comment]
dup of #3308

**Comment by GustavoPrietoP** [comment]
not really my problem

**Comment by Luflosi** [comment]
Can you elaborate? Why is this not the same problem? The PR above makes the font look thicker, possibly exactly as thick as Alacritty. Did you compile the code in the PR and see how it looks?

**Comment by AlRodriguezGar14** [comment]
Go to the preferences and write: 

macos_thicken_font 0.75
