### ISSUE TITLE
Resizing a window truncates long lines of text with `scrollback_fill_enlarged_window` set

### ISSUE THREAD

**Issue by refractalize** [kovidgoyal/kitty#3460]
**Describe the bug**

Long lines in the scrollback buffer are truncated when issuing `resize_window taller` keyboard shortcut.

**To Reproduce**

1. Set `scrollback_fill_enlarged_window yes` in config.
2. Create two windows, one on top of the other.
3. Enter the following command in the top window:
  ```zsh
  for i in {1..1000}
  do
   echo -n " $i"
  done
  ```
4. This will produce a long line ending with `... 998 999 1000`.
5. Resize the window a few times using `resize_window taller/shorter`. The truncation seems to happen only on `resize_window taller`.
6. You will see that the line now ends with something like `... 914 915 91` - it has been truncated.

This doesn't happen when `scrollback_fill_enlarged_window` is unset.

**Expected behavior**

Long wrapping lines are left unchanged no matter how the window is resized.

**Screenshots**

**Environment details**

macOS 11.2
commit: 0be5347e6aefc419e25fb77bc6a85ff9408458e1

**Comment by refractalize** [comment]
thank you!!

**Comment by kovidgoyal** [comment]
u r  welcome :)
