### ISSUE TITLE
"kitty.app" can not be opened.

### ISSUE THREAD

**Issue by iwfan** [kovidgoyal/kitty#3467]
**Describe the bug**

"kitty.app" can not be opened.

**To Reproduce**
1. `brew install --cask kitty`
2. open it.

**Screenshots**
![image](https://user-images.githubusercontent.com/28853200/114273884-8dad3f00-9a4e-11eb-8140-b87ef7af9c66.png)

**Environment details**
OS: MacOS Big Sur(11.2.3)

**Comment by kovidgoyal** [comment]
I dont support the homebrew version of kitty. Install the official
binary https://sw.kovidgoyal.net/kitty/binary.html

**Comment by iwfan** [comment]
hi @kovidgoyal , I tried to used Binary install, but encounter the same situation. it's still can not be opened.

**Comment by kovidgoyal** [comment]
Are you sure you are running the correct kitty? Run it from a terminal as

/Applications/kitty.app/Contents/MacOS/kitty
