### ISSUE TITLE
KP_Begin is not being recognized

### ISSUE THREAD

**Issue by dbivolaru** [kovidgoyal/kitty#3468]
**Describe the bug**
KP_Begin is not being recognized

**To Reproduce**
1. Open kitty
2. Ensure `NumLock` is disabled
3. Press `Ctrl+V` `Keypad 5`
4. Nothing is shown

**Expected behavior**
1. Open kitty
2. Ensure `NumLock` is disabled
3. Press `Ctrl+V` `Keypad 5`
4. Either `^[[E` or `^[OE` (if in DECKPAM mode) should be shown.

**Environment details**
OS: FC33
dnf info kitty
```
Installed Packages
Name         : kitty
Version      : 0.19.3
Release      : 1.fc33
Architecture : x86_64
Size         : 16 M
Source       : kitty-0.19.3-1.fc33.src.rpm
```

kitty --debug-config
```
kitty 0.19.3 created by Kovid Goyal
Linux localhost.localdomain 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64
\S
Kernel \r on an \m (\l)
Running under: X11

Config options different from defaults:

```

**Additional context**
The problem is present also with `kitty --config NONE`.

**Comment by alexshpilkin** [comment]
I know it’s been a long time, but: as listed in `docs/keyboard-protocol.rst` the sequence is `CSI 57427 ~`, not `... u`, unlike all other keypad keys. Despite the comment about automatic generation above the table, I don’t see anything in the code that would point to a special case here either. Was that just a typo?

**Comment by kovidgoyal** [comment]
Its listed as 1 E or 57427 ~  IIRC kitty uses E not ~ for it. Simply run kitty +kitten show_key -m kitty and press the key to see which code kitty is using for it.
