### ISSUE TITLE
Click to open new tab

### ISSUE THREAD

**Issue by kdato** [kovidgoyal/kitty#3469]
**Describe the solution you'd like**
I would like to be able to click on the tab bar to open a new tab. This does not necessarily need an extra button in the tab bar, like [New Tab]. Instead, the feature could be implemented by double-clicking on the empty space inside the tab bar.

**Describe alternatives you've considered**
I come form rxvt-unicode. It had the feature I am looking for in kitty. This helped me because I am not a keyboard-only user, I do both keyboard and mouse.

**Comment by Luflosi** [comment]
This is already implemented in master, see #3201.
To use the feature now, you need to build from source.

**Comment by kdato** [comment]
Thanks for the quick reply, Luflosi. I'll check it out.
