### ISSUE TITLE
Cannot run kitty from Desktop launcher

### ISSUE THREAD

**Issue by SeunLanLege** [kovidgoyal/kitty#347]
here's the desktop entry for ubuntu i created.

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon=/home/seun/kitty/kitty.png
Name=Kitty
Exec=/home/seun/kitty/__main__.py
Comment=Example Desktop Launcher For terminal
```

when i click on this, in my syslog  i can see an error.

```Feb 25 23:31:16 seun-TM1701 gnome-session[31194]: Traceback (most recent call last):
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:   File "/home/seun/kitty/__main__.py", line 68, in <module>
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:     main()
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:   File "/home/seun/kitty/__main__.py", line 61, in main
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:     from kitty.main import main
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:   File "/home/seun/kitty/kitty/main.py", line 11, in <module>
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:     from .borders import load_borders_program
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:   File "/home/seun/kitty/kitty/borders.py", line 8, in <module>
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]:     from .fast_data_types import (
Feb 25 23:31:16 seun-TM1701 gnome-session[31194]: ImportError: /home/seun/kitty/kitty/fast_data_types.so: undefined symbol: hb_ft_font_changed
```

The thing is i can run the program just fine from the terminal, just not from the desktop launcher.

**Comment by kovidgoyal** [comment]
That error indicates kitty is loading an outdated version of libharfbuzz. You need to set either LD_LIBRARY_PATH or LD_PRELOAD in your launcher to ensure that the correct libhatfbuzz is loaded.

**Comment by laoshaw** [comment]
same here, kitty.desktop can never be launched on ubuntu 20.04

**Comment by btctrl** [comment]
> same here, kitty.desktop can never be launched on ubuntu 20.04

same I can't run it either

I've tried giving it execute permissions, adding an absolute path for the exec key, setting the trusted metadata to true, adding terminal false and etc. Nothing
I don't see the "allow launching" option when right clicking either

It just opens in a text editor

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux

- Use the official install script, or download the latest version of release tarball from GitHub Releases.
- Copy `kitty.desktop` to `~/.local/share/applications/`.
- Option 1: Edit `kitty.desktop`
  - Change `TryExec`, `Exec` to `/your/absolute/path/to/kitty.app/bin/kitty`
  - Change `Icon` to `/your/absolute/path/to/kitty.app/share/icons/hicolor/256x256/apps/kitty.png`
- Option 2:
  - Create a symlink in PATH for `kitty`.
  - Copy `icons/hicolor/256x256/apps/kitty.png` under `kitty.app/share/` to `~/.local/share/<keep_the_same_path>`.
- The kitty icon will appear in the launcher and can be run by clicking on it.

Ubuntu 20.04 GNOME

- Copy the modified `kitty.desktop` to `~/Desktop`, right click, `Allow Launching`.

**Comment by btctrl** [comment]
> https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux
> 
> * Use the official install script, or download the latest release tarball from GitHub Releases.
> * Copy `kitty.desktop` to `~/.local/share/applications/`.
> * Option 1: Edit `kitty.desktop`
>   
>   * Change `TryExec`, `Exec` to `/your/absolute/path/to/kitty.app/bin/kitty`
>   * Change `Icon` to `/your/absolute/path/to/kitty.app/share/icons/hicolor/256x256/apps/kitty.png`
> * Option 2:
>   
>   * Create a symlink in PATH for `kitty`.
>   * Copy `icons/hicolor/256x256/apps/kitty.png` under `kitty.app/share/` to `~/.local/share/<keep_the_same_path>`.
> * The kitty icon will appear in the launcher and can be run by clicking on it.
> 
> Ubuntu 20.04 GNOME
> 
> * Copy the modified `kitty.desktop` to `~/Desktop`, right click, `Allow Launching`.

Thanks, I believe changing the tryexec field to an absolute path to the same value as exec did it

I had already done it for exec but didn't change it for tryexec

Yea i've already followed the documentation and if there's time I think it should be updated with the info you provided
I'm just using a symlink instead of cping it into the desktop

**Comment by dattran1232003** [comment]
Try this: 
```bash
cd ~/.local/bin; sudo ln -f kitty /usr/local/bin
```

**Comment by ioneliabuzatu** [comment]
i followed the 3 steps in the pre-build installation and it worked: https://www.linuxfordevices.com/tutorials/ubuntu/install-kitty

```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications
sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty.desktop

```

**Comment by alexisthual** [comment]
I just tried all setups introduced by @page-down and @ioneliabuzatu but none of them worked for me :(
I have a weird linux distro though haha
```
〉lsb_release -d
Description:	elementary OS 7 Horus
```
Could anyone using elementary get theirs to work?
