### ISSUE TITLE
[regression] Non text keys (Ctrl+something, HOME, END) are broken, and display some kind of character code

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#3471]
**Describe the bug**
Somewhere in between 0.19.3.r520.g c989a719 and 0.19.3.r526.g 8d743e95 , a regression was introduced breaking Ctrl+something (Ctrl+C, Ctrl+D, etc) combos

**To Reproduce**
1. `kitty --config NONE`
2. Press `Ctrl+C` (or `Ctrl+D`)

**Expected behavior**
A new prompt is given (or kitty exits, if Ctrl+D)

**Actual behavior**
Kitty prints `9;133u` (or `0;133u`, if Ctrl+D)

**Environment details**

```
Output of kitty --debug-config

kitty 0.19.3 (1aeafcaebf) created by Kovid Goyal
Linux t 5.11.13-1 #1 ZEN SMP PREEMPT Sat, 10 Apr 2021 20:47:18 +0000 x86_64
Arch Linux
Running under: X11
```

**Additional context**
Problem is reproducible with `kitty --config NONE`, both with bash and fish.

**Comment by ronjouch** [comment]
Renamed the issue, it's not just Ctrl+Something, it's all modifiers / "non-letters" keys. For example, pressing HOME displays `[1;129H` and pressing END displays `[1;129F`. Left shows `[1;129C` and right shows `[1;129D`

**Comment by kovidgoyal** [comment]
Works fine for me on current master:

kitty --config NONE showkey -a

press ctrl+c and see the output
^C 	 3 0003 0x03

You probably have something in your shell config or elsewhere that is
turning on the kitty extended keyboard protocol.

**Comment by ronjouch** [comment]
> You probably have something in your shell config or elsewhere that is
> turning on the kitty extended keyboard protocol.

@kovidgoyal I don't think so. I just renamed my {kitty, shell} config folders, so they're running with 100% defaults.

Also, I'm positive about the regression range. My package manager keeps old built version, and the problem didn't happen with 0.19.3.r520.g c989a71, but it does with 0.19.3.r526.g 8d743e9 . That's 6 commits; I'll do a bisect and come back with the precise faulty commit.

**Comment by kovidgoyal** [comment]
Run the command I posted. Do you get the correct output?

**Comment by ronjouch** [comment]
@kovidgoyal I finished bisecting, the problem started with commit 4c644b855649f9de29be4feac89cfeae1b981541 .

---

> Run the command I posted. Do you get the correct output?

Running `kitty --config NONE showkey -a` and pressing Ctrl+C results in output:

- In kitty 0.19.3.r520.g c989a719 (last GOOD version): `^C 	 3 0003 0x03`
- In kitty 0.19.3.r521.g 4c644b85 (first BAD version):

```
^[[99;133u 	27 0033 0x1b
 	91 0133 0x5b
 	57 0071 0x39
 	57 0071 0x39
 	59 0073 0x3b
 	49 0061 0x31
 	51 0063 0x33
 	51 0063 0x33
 	117 0165 0x75
```

**Comment by kovidgoyal** [comment]
Ah, presumably you have either numlock or capslock set

**Comment by ronjouch** [comment]
CapsLock: no, it's off
NumLock: I dunno, maybe (not sure how to check, I don't have a numpad on my keyboard)

**Comment by ronjouch** [comment]
@kovidgoyal hmmm no, both CapsLock and NumLock are off on my keyboard.

**Comment by ronjouch** [comment]
Fix confirmed. Thanks.

**Comment by kovidgoyal** [comment]
Are you sure you dont have either engaged, because that fix implies you do. What does
kitty --debug-keyboard

output if you press say the A key

**Comment by ronjouch** [comment]
> Are you sure you dont have either engaged, because that fix implies you do.

Yes I am 100% sure.

- CapsLock is off. If I turn it on, THEN I SHOUT WHEN I TYPE.
- NumLock is off too. If I turn it on, then keys behave very differently (I use a http://www.typematrix.com/ keyboard, and with numlock ON, the `J` key for example becomes `UP`).
- Also, both keyboard physical LEDs are off, and I turn the locks on they do turn on.

> What does `kitty --debug-keyboard` output if you press say the A key

```
Loading new XKB keymaps
Modifier indices alt:3 super:6 hyper:4294967295 meta:4294967295 numlock:4
Press xkb_keycode: 0x26 clean_sym: a composed_sym: a text: a mods: none glfw_key: 97 (a) xkb_key: 97 (a)
on_key_input: glfw key: 97 native_code: 0x61 action: PRESS mods: 0x0 text: 'a' state: 0 sent text to child
Release xkb_keycode: 0x26 clean_sym: a mods: none glfw_key: 97 (a) xkb_key: 97 (a)
on_key_input: glfw key: 97 native_code: 0x61 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

**Comment by kovidgoyal** [comment]
Strange it is inexplicable to me then why fix would work

**Comment by ronjouch** [comment]
> Strange it is inexplicable to me then why fix would work

Here's `kitty --debug-keyboard` output for the `a` key again, with your most recent commit `Output all modifier indices in debug`. Does it explain anything?

```
Loading new XKB keymaps
Modifier indices alt: 0x3 super: 0x6 hyper: 0xffffffff meta: 0xffffffff numlock: 0x4 shift: 0x0 capslock: 0x1
Press xkb_keycode: 0x26 clean_sym: a composed_sym: a text: a mods: none glfw_key: 97 (a) xkb_key: 97 (a)
on_key_input: glfw key: 97 native_code: 0x61 action: PRESS mods: 0x0 text: 'a' state: 0 sent text to child
Release xkb_keycode: 0x26 clean_sym: a mods: none glfw_key: 97 (a) xkb_key: 97 (a)
on_key_input: glfw key: 97 native_code: 0x61 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

**Comment by kovidgoyal** [comment]
No, not really

**Comment by ronjouch** [comment]
@kovidgoyal me again. Something remains unaddressed here.

- Summary of the above: on one machine (Arch Linux, Xorg, GNOME 40), the problem is fixed, for both Ctrl+Something and Home/End/Left/Right keys.
- ... but today I ran Kitty master on another machine (Ubuntu 20.10, Xorg, GNOME 3.38), and on this machine, in `kitty --config NONE` (and I also tried renaming my kitty/shell config folders, to be at 100% defaults),
    - Ctrl+C, Ctrl+D, Ctrl+L work fine...
    - ... but other "non-letter keys" don't work, and print char codes to the terminal. For example, `Home` prints `[1;129H`, `End` prints `[1;129F`, `Left Arrow` prints `[1;129D`, and `Right Arrow` prints `[1;129C`.
    - The above is in Fish. In bash, `Home` prints `29H`, `End` prints `29F`, `Left Arrow` prints `29D`, and `Right Arrow` prints `29C`

Here's some `debug-keyboard` output, if that helps. Available for more debug info.

```
09:16:55 ~ kitty --config NONE --debug-keyboard
Loading new XKB keymaps
Modifier indices alt: 0x3 super: 0x6 hyper: 0xffffffff meta: 0xffffffff numlock: 0x4 shift: 0x0 capslock: 0x1

# *** PRESSING Ctrl+L ***
Press xkb_keycode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 57442 native_code: 0xffe3 action: PRESS mods: 0x80 text: '' state: 0 ignoring as keyboard mode does not allow repeat events
Press xkb_keycode: 0x2e clean_sym: l composed_sym: l mods: ctrl+numlock glfw_key: 108 (l) xkb_key: 108 (l)
on_key_input: glfw key: 108 native_code: 0x6c action: PRESS mods: 0x84 text: '' state: 0 sent key to child
Release xkb_keycode: 0x2e clean_sym: l mods: ctrl+numlock glfw_key: 108 (l) xkb_key: 108 (l)
on_key_input: glfw key: 108 native_code: 0x6c action: RELEASE mods: 0x84 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release xkb_keycode: 0x25 clean_sym: Control_L mods: ctrl+numlock glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 57442 native_code: 0xffe3 action: RELEASE mods: 0x84 text: '' state: 0 ignoring as keyboard mode does not allow release events

# *** PRESSING Ctrl+C ***
Press xkb_keycode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 57442 native_code: 0xffe3 action: PRESS mods: 0x80 text: '' state: 0 ignoring as keyboard mode does not allow repeat events
Press xkb_keycode: 0x36 clean_sym: c composed_sym: c mods: ctrl+numlock glfw_key: 99 (c) xkb_key: 99 (c)
on_key_input: glfw key: 99 native_code: 0x63 action: PRESS mods: 0x84 text: '' state: 0 sent key to child
Release xkb_keycode: 0x36 clean_sym: c mods: ctrl+numlock glfw_key: 99 (c) xkb_key: 99 (c)
on_key_input: glfw key: 99 native_code: 0x63 action: RELEASE mods: 0x84 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release xkb_keycode: 0x25 clean_sym: Control_L mods: ctrl+numlock glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 57442 native_code: 0xffe3 action: RELEASE mods: 0x84 text: '' state: 0 ignoring as keyboard mode does not allow release events

# *** PRESSING HOME ***
Press xkb_keycode: 0x6e clean_sym: Home composed_sym: Home mods: numlock glfw_key: 57356 (HOME) xkb_key: 65360 (Home)
on_key_input: glfw key: 57356 native_code: 0xff50 action: PRESS mods: 0x80 text: '' state: 0 sent key to child
Release xkb_keycode: 0x6e clean_sym: Home mods: numlock glfw_key: 57356 (HOME) xkb_key: 65360 (Home)
on_key_input: glfw key: 57356 native_code: 0xff50 action: RELEASE mods: 0x80 text: '' state: 0 ignoring as keyboard mode does not allow release events

# *** PRESSING END ***
Press xkb_keycode: 0x73 clean_sym: End composed_sym: End mods: numlock glfw_key: 57357 (END) xkb_key: 65367 (End)
on_key_input: glfw key: 57357 native_code: 0xff57 action: PRESS mods: 0x80 text: '' state: 0 sent key to child
Release xkb_keycode: 0x73 clean_sym: End mods: numlock glfw_key: 57357 (END) xkb_key: 65367 (End)
on_key_input: glfw key: 57357 native_code: 0xff57 action: RELEASE mods: 0x80 text: '' state: 0 ignoring as keyboard mode does not allow release events

# *** PRESSING LEFT ***
Press xkb_keycode: 0x71 clean_sym: Left composed_sym: Left mods: numlock glfw_key: 57350 (LEFT) xkb_key: 65361 (Left)
on_key_input: glfw key: 57350 native_code: 0xff51 action: PRESS mods: 0x80 text: '' state: 0 sent key to child
Release xkb_keycode: 0x71 clean_sym: Left mods: numlock glfw_key: 57350 (LEFT) xkb_key: 65361 (Left)
on_key_input: glfw key: 57350 native_code: 0xff51 action: RELEASE mods: 0x80 text: '' state: 0 ignoring as keyboard mode does not allow release events

# *** PRESSING RIGHT ***
Press xkb_keycode: 0x72 clean_sym: Right composed_sym: Right mods: numlock glfw_key: 57351 (RIGHT) xkb_key: 65363 (Right)
on_key_input: glfw key: 57351 native_code: 0xff53 action: PRESS mods: 0x80 text: '' state: 0 sent key to child
Release xkb_keycode: 0x72 clean_sym: Right mods: numlock glfw_key: 57351 (RIGHT) xkb_key: 65363 (Right)
on_key_input: glfw key: 57351 native_code: 0xff53 action: RELEASE mods: 0x80 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

**Comment by ronjouch** [comment]
Extra information: on machine2, the problem happens on the laptop's keyboard too (not just on my TypeMatrix keyboard). CapsLock/NumLock are off.

**Comment by kovidgoyal** [comment]
You have numlock on in the problem machine see the line

```
Press xkb_keycode: 0x6e clean_sym: Home composed_sym: Home mods: numlock
```

and yes I forgot to fix the numlock encoding for some function keys. Will do it later today.

**Comment by ronjouch** [comment]
> You have numlock on in the problem machine see the line
> 
> ```
> Press xkb_keycode: 0x6e clean_sym: Home composed_sym: Home mods: numlock
> ```

@kovidgoyal still trying to understand this, because I don't see it ON here :shrug: . For my own understanding: is there a way for numlock/capslock to be "ON" via software means, means than are _not_ the keyboard buttons? Could something in my window manager / display manager / kernel set this flag to ON without it being really ON?

Because:

- I could see a way for numlock to be ON on my laptop keyboard (where there's no "NumLock" key and no LED )...
- ... but the logs you commented on above (with `Home mods: numlock`) were triggered by keypresses on my external physical keyboard, where I'm sure both numlock and capslock are OFF.

> and yes I forgot to fix the numlock encoding for some function keys. Will do it later today.

👍, thanks.

**Comment by kovidgoyal** [comment]
yes it can be on in software there is a kernel boot parameter for it, and IIRC X also has a setting for it.

**Comment by kovidgoyal** [comment]
Should be fine now.

**Comment by ronjouch** [comment]
Is fine now!
