### ISSUE TITLE
command text prepend to command output.

### ISSUE THREAD

**Issue by singlexyz** [kovidgoyal/kitty#3477]
e.g. execute `ls` command, then the command text `ls` will prepend before output.
every command does. The filename is `kitty.conf`, looks weird.

<img width="319" alt="截屏2021-04-13 下午10 21 36" src="https://user-images.githubusercontent.com/4456413/114568823-0e667800-9ca7-11eb-8b4f-e7be8da9b1e6.png">

**Comment by kovidgoyal** [comment]
Shell prompts are drawn by shells not terminal emulators. In general make
sure the TERM and LANG env vars are correct. Beyond that, ask the shell
developers for assistance.
