### ISSUE TITLE
New windows (or switching layouts) move vertical position

### ISSUE THREAD

**Issue by Amparose** [kovidgoyal/kitty#3480]
**Describe the bug**
When creating new window splits from an empty window Kitty is doing some weird scrolling up / duplicating cursor on previous splits. The result is an annoying mess to clean up.

**To Reproduce**
1. `kitty --config NONE`
2. `cmd_enter` many times

**Expected behavior**
Window splits without creating extra cursor artefacts.

**Screenshots**

![image](https://user-images.githubusercontent.com/949192/114609399-0e627a00-9c9f-11eb-94b2-5f622367a5b0.png)

vs

![image](https://user-images.githubusercontent.com/949192/114609422-14f0f180-9c9f-11eb-8e23-0e5586be7264.png)

**Environment details**
OS: MacOS 11.2.3
Ph My Zsh with p10k theme using Rainbow.

**Comment by Amparose** [comment]
Just discovered that it's worse: switching layouts also makes this happen and the windows don't have to be empty.

**Comment by kovidgoyal** [comment]
This is a limitation of your shell when using fancy prompts. Dont use
them and you will be fine. It affects all terminal emulators when windows
are resized. Google for more details and similar bug reports.
