### ISSUE TITLE
selecting text in kitty is impossible when some program is running cause kitty refreshing.

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#3482]
**Describe the bug**

I think the most clear description for this issue is a screenshot.

![image](https://user-images.githubusercontent.com/549126/114650988-be72ca00-9d15-11eb-826e-0fd09a474f85.png)

As above example, when i installing some package in my arch linux.
the console is refreshing constantly, which cause selecting text failed.

I used to use konsole for very long time, it works quite well for this case,
so i consider this is a bug for kitty

Thank you.

**Comment by kovidgoyal** [comment]
dup of #3431
