### ISSUE TITLE
Invisible cursor on sway 1.6 with certain output scale

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#3483]
**Describe the bug**

With sway 1.6, cursor is invisible with certain output scales.

Reported to sway https://github.com/swaywm/sway/issues/6166, they claim it's kitty issue.

mpv has the same issue, https://github.com/mpv-player/mpv/pull/8729 will apparently fix it.

From sway debug log:

```
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
```

![record_1617907022](https://user-images.githubusercontent.com/1177900/114079303-51d97480-98aa-11eb-9d36-9b03dd780de3.gif)

**To Reproduce**

- `swaymsg output eDP-1 scale 3`
- open a new kitty

See also https://github.com/swaywm/sway/issues/6166 for initial bug report and some discussion.

**Environment details**
OS: Arch Linux, sway 1.6, kitty from master with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
I dont see how that's possible, unless see setCursorImage() in
wl_window.c It checks the scale and calls glfw_wlc_theme_for_scale() the
theme is loaded at line 40 of wl_cursors.c where it calls
pixels_from_scale() to get the theme size and there it is explicitly
multiplied by scale.

The only way I can see this happening is if wl_cursor_theme_load() is
simply not loading a theme at the specified size and only loading
cursors at the available sizes of the current theme. Which would be a
bug in that library, not kitty. Feel free to add some printf() in the
indicated code paths to confirm.

I dont have sway 1.6 on my machine to test with.

**Comment by maximbaz** [comment]
Hmm `wl_cursor_theme_load` doesn't return a null answer at least...

```diff
--- a/glfw/wl_cursors.c
+++ b/glfw/wl_cursors.c
@@ -38,6 +38,7 @@ glfw_wlc_theme_for_scale(int scale) {
     const char* name;
     glfw_current_cursor_theme(&name, &factor);
     struct wl_cursor_theme *ans = wl_cursor_theme_load(name, pixels_from_scale(scale), _glfw.wl.shm);
+    printf("scale: %d, pixels: %d, ans: %d\n", scale, pixels_from_scale(scale), !!ans);
     if (!ans) {
         _glfwInputError(
             GLFW_PLATFORM_ERROR, "Wayland: wl_cursor_theme_load failed at scale: %d pixels: %d",
--- a/glfw/wl_init.c
+++ b/glfw/wl_init.c
@@ -138,6 +138,7 @@ static void setCursor(GLFWCursorShape shape, _GLFWwindow* window)
     if (!theme) return;
     cursor = _glfwLoadCursor(shape, theme);
     if (!cursor) return;
+    printf("theme: %d, cursor: %d\n", !!theme, !!cursor);
     // TODO: handle animated cursors too.
     image = cursor->images[0];
 
--- a/glfw/wl_window.c
+++ b/glfw/wl_window.c
@@ -116,6 +116,7 @@ setCursorImage(_GLFWwindow* window, bool on_theme_change) {
             struct wl_cursor *newCursor = NULL;
             struct wl_cursor_theme *theme = glfw_wlc_theme_for_scale(scale);
             if (theme) newCursor = _glfwLoadCursor(cursorWayland->shape, theme);
+            printf("theme: %d, newCursor: %d\n", !!theme, !!newCursor);
             if (newCursor != NULL) {
                 cursorWayland->cursor = newCursor;
                 cursorWayland->scale = scale;
```

This printed:

```
$ swaymsg output eDP-1 scale 2
$ ./kitty/launcher/kitty   # cursor is visible
scale: 2, pixels: 48, ans: 1
theme: 1, newCursor: 1
theme: 1, newCursor: 1
theme: 1, newCursor: 1

$ swaymsg output eDP-1 scale 3
$ ./kitty/launcher/kitty   # cursor is absent
scale: 3, pixels: 72, ans: 1
theme: 1, newCursor: 1
theme: 1, newCursor: 1
theme: 1, newCursor: 1
```

Do you think I should inspect contents of the returned struct somehow, or the loaded cursor object, or...?

**Comment by kovidgoyal** [comment]
Check the buffer size of the wl_buffer_t returned for the cursor.

**Comment by maximbaz** [comment]
Sorry I'm a bit rusty, did you mean something like this?

```diff
--- a/glfw/wl_window.c
+++ b/glfw/wl_window.c
@@ -116,6 +116,7 @@ setCursorImage(_GLFWwindow* window, bool on_theme_change) {
             struct wl_cursor *newCursor = NULL;
             struct wl_cursor_theme *theme = glfw_wlc_theme_for_scale(scale);
             if (theme) newCursor = _glfwLoadCursor(cursorWayland->shape, theme);
+            printf("theme: %d, newCursor: %d\n", !!theme, !!newCursor);
             if (newCursor != NULL) {
                 cursorWayland->cursor = newCursor;
                 cursorWayland->scale = scale;
@@ -131,6 +132,7 @@ setCursorImage(_GLFWwindow* window, bool on_theme_change) {
         if (!image) image = cursorWayland->cursor->images[0];
         if (!image) return;
         buffer = wl_cursor_image_get_buffer(image);
+        printf("buffer: w=%d h=%d\n", buffer->width, buffer->height);
         if (image->delay && window->cursor) {
             changeTimerInterval(&_glfw.wl.eventLoopData, _glfw.wl.cursorAnimationTimer, ms_to_monotonic_t(image->delay));
             toggleTimer(&_glfw.wl.eventLoopData, _glfw.wl.cursorAnimationTimer, 1);

```

That doesn't quite compile, think I'm missing a header or something.. or am I looking in a wrong direction?

**Comment by kovidgoyal** [comment]
as I recall wl_buffer_t is an opaque structure, you cant access its
members directly. However the image should have width and height you can
access and as per https://github.com/msteinert/wayland/blob/master/cursor/wayland-cursor.c#L153
the buffer just has that same width and height.

**Comment by maximbaz** [comment]
```diff
--- a/glfw/wl_cursors.c
+++ b/glfw/wl_cursors.c
@@ -16,6 +16,7 @@ pixels_from_scale(int scale) {
     int factor;
     const char* name;
     glfw_current_cursor_theme(&name, &factor);
+    printf("factor: %d, scale: %d, pixels: %d\n", factor, scale, factor * scale);
     return factor * scale;
 }
 
@@ -38,6 +39,7 @@ glfw_wlc_theme_for_scale(int scale) {
     const char* name;
     glfw_current_cursor_theme(&name, &factor);
     struct wl_cursor_theme *ans = wl_cursor_theme_load(name, pixels_from_scale(scale), _glfw.wl.shm);
+    printf("scale: %d, pixels: %d, ans: %d\n", scale, pixels_from_scale(scale), !!ans);
     if (!ans) {
         _glfwInputError(
             GLFW_PLATFORM_ERROR, "Wayland: wl_cursor_theme_load failed at scale: %d pixels: %d",
--- a/glfw/wl_window.c
+++ b/glfw/wl_window.c
@@ -116,6 +116,7 @@ setCursorImage(_GLFWwindow* window, bool on_theme_change) {
             struct wl_cursor *newCursor = NULL;
             struct wl_cursor_theme *theme = glfw_wlc_theme_for_scale(scale);
             if (theme) newCursor = _glfwLoadCursor(cursorWayland->shape, theme);
+            printf("theme: %d, newCursor: %d\n", !!theme, !!newCursor);
             if (newCursor != NULL) {
                 cursorWayland->cursor = newCursor;
                 cursorWayland->scale = scale;
@@ -131,6 +132,7 @@ setCursorImage(_GLFWwindow* window, bool on_theme_change) {
         if (!image) image = cursorWayland->cursor->images[0];
         if (!image) return;
         buffer = wl_cursor_image_get_buffer(image);
+        printf("image: w=%d h=%d\n", image->width, image->height);
         if (image->delay && window->cursor) {
             changeTimerInterval(&_glfw.wl.eventLoopData, _glfw.wl.cursorAnimationTimer, ms_to_monotonic_t(image->delay));
             toggleTimer(&_glfw.wl.eventLoopData, _glfw.wl.cursorAnimationTimer, 1);

```

```
$ swaymsg output eDP-1 scale 2
$ ./kitty/launcher/kitty
factor: 24, scale: 2, pixels: 48
scale: 2, pixels: 48, ans: 1
theme: 1, newCursor: 1
image: w=48 h=48

$ swaymsg output eDP-1 scale 3
$ ./kitty/launcher/kitty
factor: 24, scale: 3, pixels: 72
scale: 3, pixels: 72, ans: 1
theme: 1, newCursor: 1
image: w=64 h=64
```

So with scale 3, even though `pixels_from_scale()` says size should be 72, in fact we are getting 64x64 image, which is not divisible by 3, and sway doesn't like it. With scale 2, the size matches the expected value.

So do we conclude that it can only be a bug in `wl_cursor_theme_load()` itself?

**Comment by Dudemanguy** [comment]
If it helps, the problem in mpv was that the cursor wasn't redrawn/recreated when the output changed its scale. So internally it was still trying to use the cursor size from the old scale value. In some cases, this creates a compositor error if you update to a new scale value in a way that is not cleanly divisible value.

**Comment by kovidgoyal** [comment]
@maximbaz yes, as far as I can see this is a bug in wl_cursor or actually more properly a bug in sway. Given that wl_cursor does not do cursor image scaling, then the compositor needs to do that scaling if it is going to allow for odd scales. In any case it should not be the applications job to manually scale cursor images, which as far as I can see wl_cursor doesn't even provide an API for. It looks like wl_cursor simply loads the "closest" available size, and not the actually requested size. Indeed, given that cursor are not just simple images, but have an associated hotspot, I dont see how you can scale them arbitrarily. So yes this is either a bug in sway or wayland more generally if it cant deal with having cursors that are not multiple of the scale but allows arbitrary scales.

@Dudemanguy kitty already recreates the cursor image on scale changes, and in any case the bug exists in sway if you set the scale *before* launching the application, as demonstrated by maximbaz.

**Comment by kovidgoyal** [comment]
Oh and @maximbaz you can probably workaround this by using a cursor theme that has 72x72 images. Or not using odd scales. Or sticking to sway 1.5.
