### ISSUE TITLE
Cycle through os windows with a shortcut

### ISSUE THREAD

**Issue by mmzeeman** [kovidgoyal/kitty#3486]
**Problem**
I like to have separate os windows with terminal sessions in them. But also the ability to switch between kitty native os-windows with a shortcut. On MacOS I can't get to the window with <kbd>Alt</kbd><kbd>Tab</kbd>. It only selects the application. Therefor I need to use my mouse either to hunt down the window on my screen, or use kitty's window menu.

**Describe the solution you'd like**
Have a similar set of shortcuts like there are available to cycle through kitty windows (`kitty_mod+]` and friends).

**Describe alternatives you've considered**
I first thought the <kbd>kitty_mod</kbd><kbd>]</kbd> shortcuts described in the documentation where made to cycle through os windows, and almost considered writing a bug report because nothing was happening.

I could also setup something with Hammerspoon, but I think this will be a feature which other users might find handy too.

**Comment by kovidgoyal** [comment]
You use cmd+tab on macos to cycle through the windows of an application.

**Comment by mmzeeman** [comment]
No, <kbd>command</kbd><kbd>tab</kbd> cycles through applications.

But I found that <kbd>command</kbd><kbd>`</kbd> does cycle through windows of most applications.

Sorry for the noise.
