### ISSUE TITLE
zsh: illegal hardware instruction (core dumped)  kitty - on latest arch linux

### ISSUE THREAD

**Issue by lucabol** [kovidgoyal/kitty#3487]
Just running the program core dumps. Let me know if you need more info.

OS: 5.11.11-arch1-1

Arch Linux \r (\l)
Running under: X11

Config options different from defaults:

**Comment by kovidgoyal** [comment]
Post a backtrace

**Comment by lucabol** [comment]
I followed https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces to get traces, but not a lot of success (see below), does you have a better way?

  Reading symbols from /usr/bin/kitty...
  Starting program: /usr/bin/kitty /usr/bin/kitty
  [Thread debugging using libthread_db enabled]
  Using host libthread_db library "/usr/lib/libthread_db.so.1".
  [New Thread 0x7fffecf6e640 (LWP 162660)]
  [New Thread 0x7fffec76d640 (LWP 162661)]
  [New Thread 0x7fffebf6c640 (LWP 162662)]
  [New Thread 0x7fffeb76b640 (LWP 162663)]
  [New Thread 0x7fffeaf6a640 (LWP 162664)]
  [New Thread 0x7fffea769640 (LWP 162665)]
  [New Thread 0x7fffe9f68640 (LWP 162666)]
  [New Thread 0x7fffe9767640 (LWP 162667)]
  [New Thread 0x7fffe8e25640 (LWP 162668)]
  [New Thread 0x7fffcbfff640 (LWP 162669)]
  [New Thread 0x7fffcb7fe640 (LWP 162670)]
  [New Thread 0x7fffcaffd640 (LWP 162671)]
  [New Thread 0x7fffca083640 (LWP 162673)]
  [Detaching after fork from child process 162674]

  Thread 1 "kitty" received signal SIGILL, Illegal instruction.
  0x00007ffff728c030 in ?? ()

**Comment by kovidgoyal** [comment]
I'm guessing you are using a kitty binary that is not compatible with
your CPU architecture. I dont knwo of anything else that would cause
SIGILL. Try building kitty from source.

**Comment by lucabol** [comment]
Compiled from source. Still SIGILL. I give up.
