### ISSUE TITLE
Display border for single window

### ISSUE THREAD

**Issue by tigger04** [kovidgoyal/kitty#3488]
**Is your feature request related to a problem? Please describe.**
This is minor and cosmetic, but my OCD brain wants it. I cannot figure out what configuration I am missing to show borders for a single window - it may not be supported, just asking!

**Describe the solution you'd like**
To be able to show the window border and margin when there is only a single window being displayed

**Describe alternatives you've considered**
I think I have tinkered with nearly every option in the config that looks like it relates to display and layout, but maybe I have missed something

**Additional context**
Using the following config parameters

```
window_border_width 8.0
draw_minimal_borders no
window_margin_width 5.0
single_window_margin_width 5.0
window_padding_width 5.0
placement_strategy center
active_border_color   #007700
inactive_border_color #333333
bell_border_color     #ff5a00
```

3 and 2 window layouts look like:

(3 windows with tabs)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/43514058/115004419-b1351700-9e9e-11eb-928e-bac09ac2b030.png">

(2 windows no tabs)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/43514058/115004512-c7db6e00-9e9e-11eb-9e51-19146aa6fab7.png">

(1 window no tabs)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/43514058/115004572-da55a780-9e9e-11eb-9f62-83de4d56245b.png">

version(s) etc:

```
> kitty --version
kitty 0.19.2 created by Kovid Goyal

```

OS: MacOS 10.15.7

```
> uname -a
Darwin AMAC02ZPQSTMD6N 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

Probably not relevant
```
> $SHELL --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin19.6.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Comment by kovidgoyal** [comment]
The purpose of borders and margins is to separate multiple kityt windows
in a single tab. When there is only one window in a tab, they just waste
space and are therefore hidden.

**Comment by ksoltysik** [comment]
... unless you want the kitty to draw a border itself, when you don't want compositor's border & titlebar (& hiding just the titlebar is not really possible, for an example, in KDE with wayland).

Please consider adding the feature - I would love to have that because now I cannot see where my borderless kitty ends on the screen unless I have more than one window.

**Comment by tigger04** [comment]
> 

It is inconsistent, while kitty has assumed the role of window manager / tmux replacement (wrt UI at least), the logic behind it and when it steps in seems arbitrary. Whether it is a waste of space is subjective, isn't that why window borders are configurable in the first place?
