### ISSUE TITLE
"Equalize" windows?

### ISSUE THREAD

**Issue by MetroWind** [kovidgoyal/kitty#3489]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to "equalize" the size of the windows with the split layout. If I do 2 vsplits, I end up with 3 windows, with width 50%, 25%, and 25%. I want to be able to press a key and they will occupy equal space.

**Describe the solution you'd like**
Add a function to equalize the size of the windows, that I can bind a key to; probably as a layout action for the split layout. Something like Emacs's `balance-windows`.

**Describe alternatives you've considered**
Use an existing layout that is not split. I'm currently using the tall layout, but it's not possible to have this:
```
┌─────┬─────┬─────┐
│     │     │     │
│     │     │     │
├─────┤     ├─────┤
│     │     │     │
│     │     │     │
└─────┴─────┴─────┘
```

**Comment by kovidgoyal** [comment]
I'm afraid this is not worth the effort for me, but patches are welcome.
And you can already achieve the layout you describe by using 
a remote control script. Use the splits layout and then use

kitty @ ls 

to get the window sizes and then

kitty @ resize-window

to resize the windows as needed to become "balanced"

**Comment by MetroWind** [comment]
Could you elaborate on the remote control script approach? I tried `kitty @ ls`, but it didn’t tell me about size of windows and whether the windows were vsplit or hsplit. Was it added in a newer version? I’m using 0.19.3.

**Comment by kovidgoyal** [comment]
I just added sizes to kitty @ ls output. You should already know if a
given window is in a hsplit of vsplit since you would have created it in
your script.

**Comment by kovidgoyal** [comment]
And I just added output of layout state as well so you can (with a bit of work) figure the orientation of any split.

**Comment by codeasone** [comment]
The following is working well for me: 

```
map ctrl+' combine : launch --location=hsplit --cwd=current : kitten equalize_splits.py hsplit
map ctrl+/ combine : launch --location=vsplit --cwd=current : kitten equalize_splits.py vsplit
``` 

Where `equalize_spits.py` is as follows: 

```python
from kittens.tui.handler import result_handler


def main(args):
    pass


def count_axis_units(node, horizontal):
    """Count units along the given axis. Same-axis pairs are recursed into;
    cross-axis subtrees count as 1 (a column of N windows is still 1 column)."""
    if node is None:
        return 0
    if isinstance(node, int):
        return 1
    if node.horizontal == horizontal:
        return count_axis_units(node.one, horizontal) + count_axis_units(node.two, horizontal)
    return 1


def equalize(node, horizontal):
    """Equalise only splits along the given axis, leaving the other axis untouched."""
    if node is None or isinstance(node, int):
        return
    if node.horizontal == horizontal:
        left = count_axis_units(node.one, horizontal)
        right = count_axis_units(node.two, horizontal)
        total = left + right
        if total > 0:
            node.bias = left / total
    equalize(node.one, horizontal)
    equalize(node.two, horizontal)


@result_handler(no_ui=True)
def handle_result(args, answer, target_window_id, boss):
    tab = boss.active_tab
    if tab is None:
        return
    root = getattr(tab.current_layout, 'pairs_root', None)
    if root is None:
        return
    location = args[1] if len(args) > 1 else 'hsplit'
    # hsplit (C-') creates top-bottom pairs → horizontal=False
    # vsplit (C-/) creates side-by-side pairs → horizontal=True
    equalize(root, location == 'vsplit')
    tab.relayout()
``` 

Hopefully this helps the community.

**Comment by kovidgoyal** [comment]
You should contribute a PR adding an equalize layout action for the splits layout

**Comment by codeasone** [comment]
How about this https://github.com/kovidgoyal/kitty/pull/10091
