### ISSUE TITLE
How to remove margins when on (Neo)Vim while in full screen mode?

### ISSUE THREAD

**Issue by kdav5758** [kovidgoyal/kitty#3490]
## Screenshots
This is what I have (example with kitty on full screen mode. Red lines indicating the extra margin):

![image](https://user-images.githubusercontent.com/58336662/115116082-70e89e00-9f5d-11eb-9de4-4765a9c4e4a1.png)

This is what I *need* (example with IntelliJ IDEA on full scren mode):

![image](https://user-images.githubusercontent.com/58336662/115116152-c91fa000-9f5d-11eb-8e29-5ffed055db12.png)

## What I've tried so far
The config docs say that in order to make this work one should use [resize in steps](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.resize_in_steps) in combination with [initial_window_width  and initial_window_height](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.remember_window_size). This works:

![image](https://user-images.githubusercontent.com/58336662/115116255-4f3be680-9f5e-11eb-9f2a-b1d786b67e6b.png)

However, when the window is maximized/on full screen the margins appear.

#### NeoVim
```
NVIM v0.5.0-dev+1259-gfe808f02f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

#### Vim
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 11 2020 17:00:59)
Included patches: 1-716
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
```

[NeoVim config](https://github.com/kdav5758/NeoVim-Delightful),  [Vim config](https://github.com/kdav5758/the-supercalifragilisticexpialidocious-dots/blob/main/dotfiles/vim/vim/.vimrc)

### Current Kitty config
This is what I have in my config for the windows:
```
resize_in_steps yes
remember_window_size   no
window_margin_width    0
single_window_margin_width -1
initial_window_width   755
initial_window_height  410
window_padding_width 0
draw_minimal_borders no
```

As I said, this works every time but when the screen is maximized/on full screen.

### System
OS: Ubuntu 20.10 x86_64
Kernel: 5.11.0-051100-generic
Resolution: 1920x1080
DE: GNOME 3.38.2
WM: Mutter

## Question
How to remove margins when on (Neo)Vim while in full screen mode?

Any help would be truly appreciated.

**Comment by kovidgoyal** [comment]
Yes, there has to be a margin if the window size is not a multiple of
cell size. That is unavoidable since terminals dont have partial cells.
