### ISSUE TITLE
Configure text navigation in terminal map to option+left to move cursor by one word and cmd+ left to go to beginning of line.

### ISSUE THREAD

**Issue by nippyin** [kovidgoyal/kitty#3496]
**Describe the bug**
Unable to navigate text on terminal word by word.
Configure text navigation in terminal map to option+left to move cursor by one word and cmd+ left to go to beginning of line.

**To Reproduce**
1. Type in few lines on terminal.
2. Now try to move your cursor word by word rather each char by pressing option+left arrow key.

**Expected behavior**
Once configured we will be able to move backward & forward easily.

**Screenshots**

**Environment details**
OS: Name and version of operating system(s)

```
Output of kitty --debug-config
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Why would option+left move the cursor word by word. Moving word by word
is a feature of the shell not the terminal. Depending on the shell
and how it is configured different keystrokes will implement it. You can
use the send_text directive in kitty.conf to map option+arrow to the
required bytes.
