### ISSUE TITLE
double click on title bar to maximum kitty window on multi-monitor mode is not work as expected.

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#3497]
**Describe the bug**
double click on title bar to maximum kitty window on multi-monitor is not work as expected.

**To Reproduce**
I use arch linux newest, with GNOME40 + Wayland, but start kitty as x11 mode.(config: linux_display_server x11)

1.  start up my arch linux laptop and start to play with kitty. (without external monitor connected), all works well for now.
2. connect my laptop with a external monitor, use extended desktop, and use external monitor as my primary display.
3. move started kitty window from laptop monitor to external monitor.
4. double click on kitty title bar to maximum kitty on external monitor.
5. kitty window move to original laptop monitor again.
6.  above 3,4,5 can reproducible.

**Expected behavior**
It should be maximum on my external monitor instead of laptop monitor when i move kitty window into external monitor and try to max it.

for now, i have to close all my kitty process, and start it again to workaround this, but this is not acceptable because that will lost many work on kitty and histories.

Thank you.

**Comment by kovidgoyal** [comment]
This is not in kitty's control. The title bar is drawn by the window
manager under X11 and it handles double clicks and subsequent
maximization itself.

**Comment by zw963** [comment]
> This is not in kitty's control. The title bar is drawn by the window
> manager under X11 and it handles double clicks and subsequent
> maximization itself.

AFAK, i think this is a bug for kitty, because all others daily used applications, e.g. Firefox, Konsole, Emacs when i try to maximum current window, all can select the expected monitor correctly. that is, if move to external monitor, maximum it will full with external monitor, if move into laptop monitor, will full with laptop monitor for current case.

But, for kitty, if when open kitty time, open kitty, it's seem like saved some info, current exists only one monitor, so whatever monitor you move kitty into, when try to maximum, always fallback to laptop monitor, all others daily use program not work like this.

Thank you.

**Comment by zw963** [comment]
If i describe is not clearly? okay, let compile a simple version.

If i start kitty in arch linux which no external monitor attached, kitty can not work correctly on external monitor after attach a external monitor into this laptop, because when i try to maximum kitty window, it always move kitty into laptop monitor. 

For any others applications, no this issue for now.

**Comment by kovidgoyal** [comment]
On Sun, Apr 18, 2021 at 09:33:13PM -0700, Billy.Zheng wrote:
> AFAK, i think this is a bug for kitty, because all others daily used applications, e.g. Firefox, Konsole, Emacs when i try to maximum current window, all can select the expected monitor correctly. that is, if move to external monitor, maximum it will full with external monitor, if move into laptop monitor, will full with laptop monitor for current case.
> 
> But, for kitty, if when open kitty time, open kitty, it's seem like saved some info, current exists only one monitor, so whatever monitor you move kitty into, when try to maximum, always fallback to laptop monitor, all others daily use program not work like this.
> 
> Thank you.

Well, I havent a clue. Since that double click event is not even
delivered to kitty, I dont see where I could do anything at all about
it.

**Comment by kovidgoyal** [comment]
And am guessing your other applications are not running in X11. In any case, as I said, where a window is maximized is the responsibility ofthe window manager, not the application.

**Comment by zw963** [comment]
> Well, I havent a clue. Since that double click event is not even delivered to kitty, I dont see where I could do anything at all about it.

 Do you consider this is a kitty `detect current kitty window in external or builtin monitor` issue?  or, `kitty save some info when start kitty without attach a external monitor, but need refresh it when external monitor is attaching`, those just some clue, I am not capable enough for research it, sorry, but hope can help a little.

**Comment by zw963** [comment]
Sorry for confusing, i restart and try again, can't reproduce, i guess maybe because kitty window is too big, and cross two monitor, which cause maximum to unexpected monitor, i will keep a eye on it when this issue next happen, thank you.
