### ISSUE TITLE
Some GIF images don't seem to animate

### ISSUE THREAD

**Issue by printfn** [kovidgoyal/kitty#3498]
**Describe the bug**
Some GIF image files don't seem to animate in kitty 0.20.0, they just display a static image.
See https://github.com/printfn/kitty-gif-test for an example GIF that doesn't animate in kitty, but does show animation in Preview and in Safari.

**To Reproduce**
1. Open kitty 0.20.0
2. Run `kitty +kitten icat test.gif`
3. Image is displayed, but with no animation

**Expected behavior**
I expected the image to be animated. I uploaded the GIF file to https://github.com/printfn/kitty-gif-test.

**Screenshots**
<img width="863" alt="image" src="https://user-images.githubusercontent.com/1643883/115215073-3ea29080-a157-11eb-8609-94805aaca0b1.png">

**Environment details**
OS: macOS 11.2.3

```
kitty 0.20.0 created by Kovid Goyal
Darwin MacBook-Pro-2.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2.3 BuildVersion:	20D91
Loaded config files: /Users/printfn/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 0.0
cursor_shape          2
font_family           Monaco
font_size             12.0
initial_window_height (25, 'cells')
initial_window_width  (100, 'cells')
open_url_modifiers    1
remember_window_size  False
Added shortcuts:
	ctrl+k KeyAction(func='combine', args=(KeyAction(func='clear_terminal', args=['scrollback', True]), KeyAction(func='send_text', args=['normal,application', b'\x0c'])))
```

**Additional context**
Problem still occurs with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
That's a broken GIF image. It has no delay specified between *any*
frames and relies on broken behavior in some GIF displaying software
that inserts minimum gaps between frames to avoid excessive CPU
consumption. Thereby giving the appearance of being animated. Where are
you getting this image from?

**Comment by printfn** [comment]
I downloaded it from somewhere just to try out the new animation feature, but I didn't know the GIF itself was broken like that, sorry.

**Comment by kovidgoyal** [comment]
On Mon, Apr 19, 2021 at 04:29:24AM -0700, printfn wrote:
> I downloaded it from somewhere just to try out the new animation feature, but I didn't know the GIF itself was broken like that, sorry.

It's an old issue created, as most issues in our age, by browsers:
https://bugzilla.mozilla.org/show_bug.cgi?id=125137

It may be worthwhile for icat to check if a GIF has no delays at all and
in that case insert a default delay between all frames.

**Comment by printfn** [comment]
That was an interesting thread! Yeah, it probably makes sense for kitty to implement a similar delay.

**Comment by kovidgoyal** [comment]
already done. I dont want to have a minimum delay since there are legitimate uses for short and even zero delays between frames when using sophisticated frame composition techniques. I have however made kitty detect when the image has no delays at all and override every frame to have a 100ms delay which matches firefox.
