### ISSUE TITLE
snippet selection to copy-paste buffer awareness

### ISSUE THREAD

**Issue by sebosp** [kovidgoyal/kitty#35]
Usually, when working with several terminals, only one selection may be active and it is tied to the copy/paste buffer, somehow the text selected on other terminals becomes "unselected", in my WM when I select a string from a terminal I can paste it with the middle button on mouse (on both mouse buttons at the same time), currently kitty supports several highlighted snapshots to be active when several terminals are active. It becomes hard to know which text is actually bound to the copy/paste buffer.

**Comment by kovidgoyal** [comment]
I think you are saying you want different instances of kitty to communicate with each other and clear their selections? I dont see how that's possible without some kind of central service/daemon? Or at least a selection changed notification from the windowing system -- which as far as I know glfw does not support. Incidentally, of three terminals I tried:

1) xterm -- has the above behavior
2) konsole -- does not have the baove behavior
3) termite -- does not have this behavior

I'm guessing xterm implements it via a selection changed message from the X11 system -- but given that kitty is based on glfw and there is no such notification there, I dont think it can be implemented in kitty. 

What can be implemented is clearing the selection between different windows/tabs in the same kitty process. But I dont think that is what you are asking for.

**Comment by koterpillar** [comment]
While programs native to X11 indeed clear selection when something is selected elsewhere, most text editors, browsers and other applications do not.

**Comment by tmccombs** [comment]
> most text editors, browsers and other applications do not
That's true, but many do change the color of selection when the application loses focus

**Comment by kovidgoyal** [comment]
Given that this is X11 specific and requires API not exposed by glfw, I dont think this is worth implementing.
