### ISSUE TITLE
Synology compatibility

### ISSUE THREAD

**Issue by Amparose** [kovidgoyal/kitty#3502]
Not sure this is either a bug or a feature request. When connecting to a Synology box (DSM 6.4.2), the terminal is broken (CTRL-L doesn't clear, colours don't work etc). I assume this is a terminal compatibility issue with [xterm-kitty](https://github.com/kovidgoyal/kitty/issues/713) and that "the way others are doing [x] is wrong". I love Kitty and want to use it for all things so is there a way I can make it work with Synology products?

I tried the [FAQ suggestions](https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer) but I get "permission denied" errors or, for the Python solution (Python3 is installed via Package Center) "ssh: Could not resolve hostname use-python: nodename nor servname provided, or not known".

I will probably look a fool here as I don't quite know what I am doing, but I tried `infocmp xterm-kitty > xterm-kitty` on my Mac and then copying that file to `[Synology]~/.terminfo/x/` and reconnecting; it didn't work.

**Comment by kovidgoyal** [comment]
The ssh kitten has support for python only with kitty 0.20 so run that
version and you should be fine.

**Comment by kovidgoyal** [comment]
And if you want to copy it manually, the command to use is:
infocmp xterm-kitty | ssh myserver tic -x -o \~/.terminfo /dev/stdin

and I dont know what OS the synology uses, but if it is a termcap based one rather than terminfo, such as some bsds, then read the part of the FAQ that applies to them.

**Comment by Amparose** [comment]
> The ssh kitten has support for python only with kitty 0.20 so run that
> version and you should be fine.

Updated to Kitty 2.0 and still no go. It seems I don't have tic on the server. And as per my first post:

> I tried `infocmp xterm-kitty > xterm-kitty` on my Mac and then copying that file to `[Synology]~/.terminfo/x/` and reconnecting; it didn't work.

^^ is that how I _copy over your local file terminfo to the other system as ~/.terminfo/x/xterm-kitty_ from the FAQ?

The box has a `/usr/share/terminfo/` folder.

Shell is bash from what I can tell (`sh -> bash*`).

**Comment by kovidgoyal** [comment]
On Mon, Apr 19, 2021 at 11:30:52AM -0700, Amparose wrote:
> ^^ is that how I _copy over your local file terminfo to the other system as ~/.terminfo/x/xterm-kitty_ from the FAQ?
> 
> The box has a `/usr/share/terminfo/` folder.
> 
> Shell is bash from what I can tell (`sh -> bash*`).

No macs have a different terminfo database. You would need to copy it
from a linux machine assuming your Synology is running linux.

**Comment by Luflosi** [comment]
The only difference between the two terminfo files is the filename of the folder they are in AFAIK

**Comment by kovidgoyal** [comment]
Come to think off it the compiled versions of both terminfo files are in the kitty application bundle, see
ls $TERMINFO inside kitty. You should be able to just copy the contents of that folder over to ~/.terminfo on the synology or /usr/share/terminfo.

**Comment by Amparose** [comment]
Thank you for the help so far but I haven't been able to resolve this.

I copied from Mac `/Applications/Kitty.app/Contents/Resources/terminfo/78` to `Synology/~/.terminfo` and to `/usr/share/terminfo`, logged out and back in and doesn't work. I also tried copying the `/78/xterm-kitty` to `Synology/~/.terminfo/` in case but still no good.

I don't know if this is meaningful but if, on the Synology, I `printenv` I do get `TERM=xterm-kitty`.

**Comment by kovidgoyal** [comment]
Rename 78 to x after copying.

**Comment by Amparose** [comment]
Aha! Progress! `Synology/~/.terminfo/x/xterm-kitty` doesn't seem to do anything but copying xterm-kitty to `/usr/share/terminfo/x/` now lets me clear the screen. Colours are still not working.

`printenv` has an empty `LS_COLORS=`. In my .bashrc I have `eval "dircolors -b ~/.dircolors"`. Is there something I am missing for Kitty?

**Comment by kovidgoyal** [comment]
On Tue, Apr 20, 2021 at 06:19:20AM -0700, Amparose wrote:
> `printenv` has an empty `LS_COLORS=`. In my .bashrc I have `eval "dircolors -b ~/.dircolors"`. Is there something I am missing for Kitty?

kitty has nothing to do with it. That's all your shell.

**Comment by Amparose** [comment]
> kitty has nothing to do with it. That's all your shell.

Hmm, but file colours are showing with three other terminal apps. Kitty is the only one that doesn't.
