### ISSUE TITLE
weird  white panel at top since last  update  yesterday

### ISSUE THREAD

**Issue by r3k2** [kovidgoyal/kitty#3503]
weird  white panel at top since last  update  yesterday

it was  not  there  before,  now   it  overlaps over my  "sway+wayland"   top  bar... and cant see anything.

![swappy-20210419_171252](https://user-images.githubusercontent.com/5316229/115259870-8e229580-a132-11eb-8b7a-9a0f6cb604c6.png)

did   look   to see  if I can remove this, I only seen tab options  to move down and I  did,  but this are  not  tabs.

**Comment by kovidgoyal** [comment]
dup of #3501
