### ISSUE TITLE
A more accurate tab_title_template

### ISSUE THREAD

**Issue by ndavidq0** [kovidgoyal/kitty#3505]
**Is your feature request related to a problem? Please describe.**
I like using tabs but the title always say `bash` (unless when I'm on nvim).

**Describe the solution you'd like**
A more accurate tab_title_template (maybe called something like `job`) that looks at what binary you're currently using (for example `htop`  when I'm running htop :P)

**Comment by kovidgoyal** [comment]
kitty will show whatever title the shell sets. Setup your bash to set
the window title, a bit of googling will show you how.

**Comment by ndavidq0** [comment]
Alright thanks!
