### ISSUE TITLE
Kitty hangs on binary file output

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#3508]
**Describe the bug**
After printing the contents of this binary file (hexdump below), the terminal window hangs; all keyboard commands are ignored except for closing one (on my machine, CMD+W).

**To Reproduce**
1. cat kitty_hangs_binary_output.bin
2. See error

**Expected behavior**
The terminal window should resume to prompt after printing is complete.

**Environment details**
OS: MacOS Big Sur 11.0.1

```bash
kitty 0.20.1 created by Kovid Goyal
Darwin Mihais-MBP.lan 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.0.1 BuildVersion:	20B50

Config options different from defaults:
```

**Additional context**
```bash
$ hexdump /kitty_hangs_binary_output.bin 
0000000 1b 5e                                          
0000002
```

The issue is reproducible with  `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Any and all terminals can be trivially hung by catting binary data into
them. never do that. If you want to cat a binary file, use cat -v at a
minimum.

**Comment by mihaicristiantanase** [comment]
Of course `cat`-ing binary files should be avoided, but `cat` is a way I could easily illustrate the issue.
In the situation I'm facing, I don't have control of what is dumped to terminal (an application with logs enabled is writing stuff to stdout).

Also, I'll mention that I'm not seeing the issue in Mac's Terminal app.

**Comment by kovidgoyal** [comment]
You cannot write arbitrary binary data to any terminal, ever. Simply
dont it. If your application does this, pipe its output through cat -v

And yes, the set of escape codes kitty supports is different from those
terminal.app supports. So different binary dumps will freeze one and not
the other.
