### ISSUE TITLE
Entering unicode characters łąćż

### ISSUE THREAD

**Issue by jmalczak** [kovidgoyal/kitty#351]
Hi 

I have a question regarding entering unicode characters, especially Polish characters like łąćż. I use macOS and kitty 0.8.0 installed via brew. Whenever I try to type any of the characters above I can just hear bell and nothing besides that. I have locale set to pl_PL.UTF-8 and set Monaco font that I use in iterm2 with success. Could you please advise?

![shell 2018-02-27 19-42-53](https://user-images.githubusercontent.com/1000144/36747870-791cd5ac-1bf6-11e8-934c-0d12a6254dd6.png)

Thanks!

**Comment by kovidgoyal** [comment]
If you want to use the option key to enter unicode characters, you need to set macos_option_as_alt to no in your kitty.conf

**Comment by jmalczak** [comment]
Wow. Great. Thanks a lot!
