### ISSUE TITLE
Fonts look weird in ubuntu

### ISSUE THREAD

**Issue by misssprite** [kovidgoyal/kitty#352]
System: ubuntu 16.04
kitty version: lastest master commit: c93238d8c98ed933fb0d6b43df76e9b74d29ceaa

Some characters are smaller than others and some look like bold face.

Ubuntu Mono:

13.0 pts:
![image](https://user-images.githubusercontent.com/1622709/36792667-21d87112-1cd6-11e8-9e06-a331e005231c.png)

15.0 pts:
![image](https://user-images.githubusercontent.com/1622709/36792515-c10e1a30-1cd5-11e8-80a5-f2680c636c3a.png)

17.0 pts:
![image](https://user-images.githubusercontent.com/1622709/36792536-cd1f1572-1cd5-11e8-9223-65e386479f04.png)

Fira Code 13.0 pts:
![image](https://user-images.githubusercontent.com/1622709/36792562-d932b526-1cd5-11e8-9e03-78c25c3c6c3b.png)

**Comment by kovidgoyal** [comment]
That's just weird, it looks like characters are being chosen from different fonts. Something messed up in your fontconfig configuration, I'd guess. If you have a custom fonts.conf I suggest removing it and seeing. And what are you using in kitty.conf?

**Comment by misssprite** [comment]
I copied kitty.conf from kitty/kitty.conf to ~/.config/kitty and just changed line 14 from
``` font_family      monospace```
to
```font_family      Fira Code``` or ```font_family      Ubuntu Mono```.

I don't have a ~/.config/fontconfig, neither any ~/.font*
By the way, my fontconfig version is `2.11.94-0ubuntu1.1`.

The /etc/fonts are left as default. The content of /etc/fonts/fonts.conf is as follows:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- /etc/fonts/fonts.conf file to configure system font access -->
<fontconfig>

<!--
	DO NOT EDIT THIS FILE.
	IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
	LOCAL CHANGES BELONG IN 'local.conf'.

	The intent of this standard configuration file is to be adequate for
	most environments.  If you have a reasonably normal environment and
	have found problems with this configuration, they are probably
	things that others will also want fixed.  Please submit any
	problems to the fontconfig bugzilla system located at fontconfig.org

	Note that the normal 'make install' procedure for fontconfig is to
	replace any existing fonts.conf file with the new version.  Place
	any local customizations in local.conf which this file references.

	Keith Packard
-->

<!-- Font directory list -->

	<dir>/usr/share/fonts</dir>
	<dir>/usr/local/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>

<!--
  Accept deprecated 'mono' alias, replacing it with 'monospace'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>mono</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>monospace</string>
		</edit>
	</match>

<!--
  Accept alternate 'sans serif' spelling, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans serif</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Accept deprecated 'sans' alias, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Load local system customization file
-->
	<include ignore_missing="yes">conf.d</include>

<!-- Font cache directory list -->

	<cachedir>/var/cache/fontconfig</cachedir>
	<cachedir prefix="xdg">fontconfig</cachedir>
	<!-- the following element will be removed in the future -->
	<cachedir>~/.fontconfig</cachedir>

	<config>
<!--
  Rescan configuration every 30 seconds when FcFontSetList is called
 -->
		<rescan>
			<int>30</int>
		</rescan>
	</config>

</fontconfig>
```

**Comment by kovidgoyal** [comment]
Then I'm at a loss, sorry. I only have Ubuntu Artful to test in and kitty works fine in that. You can try using the --debug-font-fallback option I just added to see if fonts are really being used. If fallback fonts are used for any characters, that option will cause kitty to print out the used font to stdout.

**Comment by kovidgoyal** [comment]
That means fallbacks are not used, in which case, I really have no idea why your font rendering is so weird, sorry.

**Comment by misssprite** [comment]
Never mind, thanks for fast replies, though. Maybe there's something wrong with my font library. I'm not familiar with font configuration.

**Comment by kovidgoyal** [comment]
Looking a the code, I'd guess what is happening is that the cell is not wide enough for some characters. Why that is the case on your system, I dont know, but you should be able to work around it by setting the adjust_column_width option in kitty.conf.

**Comment by kovidgoyal** [comment]
If you want to investigate why the cell width is not wide enough, the relevant function is calc_cell_width() in freetype.c

**Comment by misssprite** [comment]
I have no luck with `adjust_column_width 120%`. Did you mean this?

**Comment by kovidgoyal** [comment]
Run kitty like this:

```
kitty --config NONE -o font_family=Ubuntu\ Mono -o adjust_column_width=10
```

The characters should all be the same size (but there will be lots of extra space between cells, which you can remove by adjusting the value of 10 above.

**Comment by misssprite** [comment]
Absolute value of 2 works fine for me. Thanks a lot!

**Comment by misssprite** [comment]
According to your suggestion about freetype, I build `freetype 2.9` from source and `kitty` works with default column width.
The `libfreetype6-dev` package from Ubuntu 16.04 is `2.8.1`, which seems the cause.

**Comment by kovidgoyal** [comment]
Interesting, I wonder what the problem in freetype 2.8 is.

**Comment by kovidgoyal** [comment]
With what font? cell widths are set based on metrics from the font. Presumably the font you are using does not report correct metrics. As I told misssprite you can work around it by adjusting the cell width, or if you are interested in debugging, look in the calc_cell_width function in freetype.c.

**Comment by kosciak9** [comment]
Also Fira Code - yes, it works with adjusted cell width. I might look into it.

**Comment by ariasuni** [comment]
You should have a look at how [Alacritty](https://github.com/jwilm/alacritty) does it: as Kitty, it renders with the GPU, but doesn’t have this problem. Since I do not have this bug in any other application, even Alacritty, I think it’s probably not a problem in the font.

Concerning the specific behavior of Kitty (I use Noto Mono and my w is incorrectly rendered): `adjust_column_width 1` or any superior value make my w looks fine but it’s a pain to read (characters are too far from each other). However any percentage I tried had no effect on this issue. This seems like a separate bug maybe?

**Comment by kovidgoyal** [comment]
Umm this is already fixed, just update to 0.8.3 and see the changelog.

**Comment by ariasuni** [comment]
0.8.3 is worse for me. I can’t have good spacing with badly rendered w anymore, because I can’t change the spacing to something less than what’s on the screenshot (using `adjust_column_width` I can only decrease line height), and the spacing is terrible like that for every font. :disappointed: 

![screenshot_20180329_121824](https://user-images.githubusercontent.com/2446451/38083921-495323b4-334b-11e8-90ae-7d54b8228463.png)

**Comment by ariasuni** [comment]
You’ll probably have better luck using Harfbuzz fonction [`hb_font_get_glyph_h_advance ()`](http://www.manpagez.com/html/harfbuzz/harfbuzz-1.0.4/harfbuzz-hb-font.php#hb-font-get-glyph-h-advance).

I tried to change the code source to use it but I can’t find where to get the glyph code point for the second parameter.

**Comment by kovidgoyal** [comment]
No, the current code is perfectly accurate since it uses actual rendered bitmap widths. You can use negative numbers in adjust_column_width, but beware that if you do that, some characters might be rendered resized. Something like adjust_column_width=-2

**Comment by ariasuni** [comment]
Oh, `adjust_column_width=-1` works. But then my w is screwed again. :/

**Comment by kovidgoyal** [comment]
I suggest you try a few different fonts until you find a font that has metrics you like.

**Comment by kovidgoyal** [comment]
Or alternately, you can use the symbol_map feature in kitty to have kitty render just the w from another font.

**Comment by ariasuni** [comment]
Well, I could use a different font, or a different terminal emulator but that’s not what I want. :/

The previous `calc_cell_width` code was correct, it’s neither a font nor a width issue; the problem arise later. The character seems to be either cropped, or rendered with an incorrect size… But I am not competent enough to investigate more and fix it myself.

**Comment by kovidgoyal** [comment]
It's simple, the character is resized or cropped if it does not fit in the cell width. Previously the cell width was calculated using glyph advances, since that is faster. But since there apparently exist various broken ass fonts that have advances that are smaller than the rendered glyph size, it has now been changed to use the rendered glyph size. The current code is the most correct it can be. It ensures the cell is wide enough to fit every glyph in the printable ascii range of the main font, therefore none of those glyphs will ever be resized or cropped.

That you dont like the look of your particular font when the cells are wide enough to accommodate the w  (which is usually the widest character) is not a bug in kitty.

**Comment by ariasuni** [comment]
Well, there is a bug somewhere since my font is rendered correctly elsewhere: either other applications include a workaround and I would gladly report a bug to the font author, or Kitty is doing something incorrectly.

But if you don’t want to investigate further this issue, I won’t insist.

**Comment by kovidgoyal** [comment]
No, rendering it in cell sizes smaller than the w glyph is not correct, you just happen to prefer it. As with most font preferences, it is entirely subjective and it will change if you stare at a different font rendering for a few days. Anyway, I'm done spending time on this issue, kitty's font rendering is correct as far as I am concerned. I'm sorry you dont like it, but...

**Comment by DonnieWest** [comment]
Hrm, I also noticed that my fonts started looking quite strange in 0.8.3

It looks "correct" in xterm and other terminals I happen to have installed, and thanks to @ariasuni for the workaround of reducing column width

**Comment by kovidgoyal** [comment]
Actually, it occurs to me there is another possible way to fix this issue -- go back to using the advances from the font and simply truncate the edges of characters too wide to fit. There are certain complications however, mainly that we only want to do this for glyphs from the main font not its italic/bold variants and not for fallback characters from another font.

**Comment by ariasuni** [comment]
This fixed my issue, thank you! I think I’ll still make a bug report to Noto Font, because it looks like a problem in their font.
