### ISSUE TITLE
Ctrl+C does not work on Workman Layout

### ISSUE THREAD

**Issue by Raghav-Dixit** [kovidgoyal/kitty#3521]
**Describe the bug**
Normally, to quit out of a process, I do `Ctrl+C`. This works in the standard qwerty layout, but I use the Workman keyboard layout. If I do `Ctrl+C`, it just types out "c" into the prompt. I don't think it is a problem with the layout, because the problem does not occur in iTerm and Terminal.app.

**To Reproduce**
1. Download Workman layout from workmanlayout.org.
2. Follow instructions for your operating system.
3. Run a command like that you might want to quit out of, like `tree` which may take a long time.
4. Try doing `Ctrl+c` in Workman (This does not stop tree from running).
5. Switch back to qwerty and do the same thing (This does work as expected for me).

**Expected behavior**
I expected the command that I ran to stop running and display the shell prompt.

**Environment details**
OS: macOS 11
Version: 0.20.1

**Comment by kovidgoyal** [comment]
I presume that is because c is mapped to something else in that layout.
You need to press ctrl And whatever key generates the c character. For
example, witht he builtin dvorak layout to get ctrl+c you actually type
ctrl+i

**Comment by kovidgoyal** [comment]
Actually never mind, this is a bug in the workman layout. dup of #835

**Comment by Raghav-Dixit** [comment]
I don't think it is a bug in the Workman Layout because other terminal emulators interpret the shortcut correctly.

**Comment by kovidgoyal** [comment]
In #835 I described exactly the problem and the lines of code where it is demonstrated, feel free to build kitty yourself and check. In workman ctrl+c is returning the text C. That is a bug in the layout.

**Comment by abecodes** [comment]
I have the same issue on macOS with the workman layout.

@qisaw had a similar issue in another place and created a [workman fork](https://github.com/qisaw/wasiqman) with working CTRL.

Enjoy
