### ISSUE TITLE
Allow referring to all 16 ANSI colors via names

### ISSUE THREAD

**Issue by ismay** [kovidgoyal/kitty#3522]
**Is your feature request related to a problem? Please describe.**

I use the 16 ANSI colors to set consistent colors for all my terminal applications, as per this post: https://jeffkreeftmeijer.com/vim-16-color. Now I've always used the numbered color codes in my vim theme (see [here](https://github.com/ismay/dotfiles/blob/453ea28f1efbb9149f7756afc4ffd608ab80613b/vim/colors/native.vim#L18)), which works fine with kitty.

I thought I'd make the theme easier to maintain and move my vim theme to use named colors (see [PR here](https://github.com/ismay/dotfiles/pull/6)). According to vim's help for 16 color terminals these names should be:

```
0 Black
1 DarkBlue
2 DarkGreen
3 DarkCyan
4 DarkRed
5 DarkMagenta
6 Brown, DarkYellow
7 LightGray, LightGrey, Gray, Grey
8 DarkGray, DarkGrey
9 Blue, LightBlue
10 Green, LightGreen
11 Cyan, LightCyan
12 Red, LightRed
13 Magenta, LightMagenta
14 Yellow, LightYellow
15 White
```
> From `:help cterm-colors`

However that doesn't seem to work for all colors in kitty. It did work for `red` and `yellow` for example, which makes me think that kitty isn't exposing the `dark-` variants of the colors as named colors. In the [docs](https://github.com/ismay/dotfiles/blob/453ea28f1efbb9149f7756afc4ffd608ab80613b/vim/colors/native.vim#L18) I also see only a single name for both variants.

**Describe the solution you'd like**

I would like to know if it's possible to refer to all the 16 ANSI colors via names instead of their numbers. And if it isn't, if it's in scope for kitty to add that feature.

**Describe alternatives you've considered**

I could continue to use the numbers. That works well. It's just a little more cumbersome, hence my request.

**Additional context**

For context, my TERM is set to `xterm-kitty` and I set my kitty theme colors on the fly with a simple [theme script](https://github.com/ismay/dotfiles/blob/453ea28f1efbb9149f7756afc4ffd608ab80613b/config/fish/functions/theme.fish), which (for example) will use `kitty @ set-colors --all --configured $theme_path` to apply the following kitty config:

```conf
background #1b182c
foreground #cbe3e7
color0 #3b3b4f
color1 #ff5458
color2 #62d196
color3 #ffb378
color4 #65b2ff
color5 #906cff
color6 #63f2f1
color7 #a6b3cc
color8 #807b8a
color9 #ff8080
color10 #95ffa4
color11 #ffe9aa
color12 #91ddff
color13 #c991e1
color14 #aaffe4
color15 #cbe3e7
url_color #65b2ff
cursor #a6b3cc
cursor_text_color #1b182c
selection_background #cbe3e7
selection_foreground #1b182c
active_tab_background #807b8a
active_tab_foreground #cbe3e7
inactive_tab_background #807b8a
tab_bar_background #807b8a
inactive_tab_foreground #a6b3cc
inactive_border_color #cbe3e7
bell_border_color #cbe3e7
```

So to me it seems like I'm setting all the colors correctly. For more details see [my configs here](https://github.com/ismay/dotfiles/tree/453ea28f1efbb9149f7756afc4ffd608ab80613b). When using color numbers everything works as expected, so to me it seems like certain color names are just missing.

**Comment by kovidgoyal** [comment]
there are no such things as color names in terminals. There is a *256*
color table whose actual color values are undefined, but can be
controlled in terminal configuration. In the case of kitty via color0
through color255 in kitty.conf.

A terminal application such as vim can request the emulator to render
text in a particular color by using an SGR escape code, in which the
*color number* is passed to the terminal emulator from 0 to 255. There
are no names involved. 

If you want to do some name to number matching, the place to do it is in
the terminal application, not the terminal.

**Comment by ismay** [comment]
I see. Ok so it's vim that is causing the bug here. Strange that colors without the `dark-` prefix don't work, and regular ones do. Anyway, thanks for the quick reply!

**Comment by ismay** [comment]
Ok, so turns out vim 8 has a little bit of a weird mapping, and their color names don't line up exactly with the ANSI colors for whatever reason. These are the corrected color names that worked for me in vim:

```
" 0 black
" 1 darkred
" 2 darkgreen
" 3 darkyellow
" 4 darkblue
" 5 darkmagenta
" 6 darkcyan
" 7 grey
" 8 darkgrey
" 9 red
" 10 green
" 11 yellow
" 12 blue
" 13 magenta
" 14 cyan
" 15 white
```
