### ISSUE TITLE
Font height incorrectly stretched

### ISSUE THREAD

**Issue by Draiken** [kovidgoyal/kitty#3524]
**Describe the bug**
My font is stretched higher than it should be.

I'm trying to move from terminator to kitty, and have the exact same font and size configured, but kitty renders it differently.

I checked and my font is correctly being listed under `kitty list-fonts`
```
➜  ~ kitty list-fonts | grep Bitstream
Bitstream Vera Sans Mono
    Bitstream Vera Sans Mono
    Bitstream Vera Sans Mono Bold
    Bitstream Vera Sans Mono Bold Oblique
    Bitstream Vera Sans Mono Oblique
BitstreamVeraSansMono Nerd Font
    Bitstream Vera Sans Mono Bold Nerd Font Complete
    Bitstream Vera Sans Mono Bold Oblique Nerd Font Complete
    Bitstream Vera Sans Mono Nerd Font Complete
    Bitstream Vera Sans Mono Oblique Nerd Font Complete
```

**Expected behavior**
The same font with same size should render the exact same output

**Screenshots**
![DeepinScreenshot_select-area_20210423081947](https://user-images.githubusercontent.com/287889/115864014-acc3ad80-a40c-11eb-89f3-b3bb1ccf01d4.png)

**Environment details**
OS: Arch Linux

```
kitty 0.20.1 created by Kovid Goyal
Linux valhalla 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/felipe/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=46, green=52, blue=54)
color0                Color(red=16, green=16, blue=16)
color1                Color(red=232, green=79, blue=79)
color10               Color(red=160, green=207, blue=93)
color11               Color(red=243, green=157, blue=33)
color12               Color(red=78, green=159, blue=177)
color13               Color(red=133, green=66, blue=255)
color14               Color(red=66, green=113, blue=123)
color15               Color(red=221, green=221, blue=221)
color2                Color(red=184, green=214, blue=140)
color3                Color(red=225, green=170, blue=93)
color4                Color(red=125, green=193, blue=207)
color5                Color(red=155, green=100, blue=251)
color6                Color(red=109, green=135, blue=141)
color8                Color(red=64, green=64, blue=64)
color9                Color(red=210, green=61, blue=61)
cursor                Color(red=182, green=182, blue=182)
cursor_text_color     None
font_family           BitstreamVeraSansMono Nerd Font
font_size             14.0
foreground            Color(red=215, green=208, blue=199)
selection_background  Color(red=215, green=208, blue=199)
selection_foreground  Color(red=46, green=52, blue=54)
update_check_interval 24.0
```

**Additional context**
For reference, my font config on terminator. The same shown on `kitty --debug-config`:
```
[profiles]
  [[default]]
   font = BitstreamVeraSansMono Nerd Font 14
```

**Comment by kovidgoyal** [comment]
Looking at your screen shots those are different fonts being used. You
can check what font kitty is using by the --debug-font-fallback command
line option. As for terminator I have no clue how to check what it uses.
Am guessing it is using a bitmapped variant or similar.

And in any case rendering text identically to terminal XYZ is a non-goal
for kitty.

**Comment by Draiken** [comment]
I don't understand why the configured font is not used if it's listed under `list-fonts` and correctly configured. Is there a way to figure out why it's falling back to another font?

Am I right in assuming that this font won't ever work with kitty as it is?

**Comment by kovidgoyal** [comment]
I'm saying your other terminal is using some other font, not kitty. And
you can check that by using --debug-font-fallback

**Comment by rosshadden** [comment]
I have this same problem. I was trying to find other people talking about kitty making fonts taller and eventually ended up here. I was vetting switching from Termite but I don't like how much screen real estate I lose. When I have the same tmux session open in both terminals side by side I get far more lines rendered in Termite.

@draiken did you ever come up with a way to fix this?

**Comment by kovidgoyal** [comment]
You are almost certainly using different fonts in the terminals. I posted above how to check what font kitty is actually using. Follow the instructions. And change the font size or use adjust_line_height in kitty.conf till you get a font size you are comfortable with.

**Comment by Luflosi** [comment]
Can you try building from source and see if anything has changed compared to the version you're using now? See https://sw.kovidgoyal.net/kitty/build.html for instructions.
