### ISSUE TITLE
Hotkey window

### ISSUE THREAD

**Issue by mTvare6** [kovidgoyal/kitty#3527]
**Is your feature request related to a problem? Please describe.**
I have used iTerm it has hetkey mode, but its slower than kitty, so I switched to kitty, it would be nice it kitty has hotkey

**Describe the solution you'd like**
When I press a particular keybind, I wish kitty to popup

**Additional context**
Pressed `cmd` + ` launches iTerm and pressing the same closes it

https://user-images.githubusercontent.com/57838468/115905202-65c4cf00-a483-11eb-8584-6816f55b83c5.mov

**Comment by kovidgoyal** [comment]
dup of #45
