### ISSUE TITLE
Invoking kitty from shell commands

### ISSUE THREAD

**Issue by CarlosEvo** [kovidgoyal/kitty#353]
I am on `macOS` and I am trying to send command to kitty via AppleScript, i.e. without Kitty being opened. When I use the following applescript:

```applescript
on alfred_script(q)
	tell application "System Events"
		do shell script "/Applications/kitty.app/Contents/MacOS/kitty @ new-window --new-tab --keep-focus " & q
	end tell
end alfred_script

alfred_script("ls")
```

I got an error:

![image](https://user-images.githubusercontent.com/11689106/36823664-10e070b2-1cb3-11e8-911e-13d4b386adfa.png)

When I tried it in `terminal.app`, I got the following errors:
```shell
$ /Applications/kitty.app/Contents/MacOS/kitty @ new-window --new-tab --keep-focus ls
@kitty-cmd{"cmd": "new-window", "version": [0, 8, 0], "payload": {"match": null, "title": null, "cwd": null, "new_tab": true, "tab_title": null, "keep_focus": true, "args": ["ls"]}}Failed to receive response from kitty
```

Am I doing it correctly?

**Comment by kovidgoyal** [comment]
As is noted on the remote control page, the remote control commands work only from within kitty. If you want to open a new window in an existing kitty instance from outside kitty, you use --single-instance

**Comment by CarlosEvo** [comment]
I see. Thank you for your help. Sorry for not finishing the doc.

**Comment by kovidgoyal** [comment]
FYI, I just added the ability to control kitty over UNIX or TCP sockets as well, so you can now even control kitty instances running on different computers :) See the remote control help page for details.

**Comment by evantravers** [comment]
@CarlosEvo did you ever get this to work reliably? I'm hunting down the same path (triggering kitty from Alfred) and I'd love to see what you wound up with.
