### ISSUE TITLE
Allow setting environment variables via remote control

### ISSUE THREAD

**Issue by adrusi** [kovidgoyal/kitty#3532]
On macOS, there's no good way to launch kitty using the system launcher with the correct environment. This is a problem for kitty launching other programs, as they might not be found in the path, and once they are launched they similarly do not have the correct environment.

A common practice for mac applications is to figure out what the user's default environment probably is by spawning a login shell and copying its env vars. This is a hack, and probably not the hack most appropriate to kitty.

What I suggest is to add a remote-control command called, say, `put-env` which lets scripts modify the environment variables kitty will use to exec other programs. Users can then do something to the effect of `kitty @ put-env PATH="$PATH"` in their shell startup script to feed the correct environment to kitty. This might plausibly have some other use cases, but I'm not sure what they are.

Alternatively, a remote-control command called something like `inherit-env` which causes kitty to read all environment variables from the invoking process (ignoring the kitty variables like `KITTY_WINDOW_ID`) and load them into the kitty process.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos

And use -o env=whatever -o env=whatever2

Also this is a dup of #3529

**Comment by adrusi** [comment]
I am not quite sure what the requester in #3529 is suggesting, it may be a dup.

But this is not achievable by setting command line options as described in the FAQ, as with that method, kitty's config needs to be altered

**Comment by kovidgoyal** [comment]
On Sun, Apr 25, 2021 at 09:01:44AM -0700, Adrian Sinclair wrote:
> I am not quite sure what the requester in #3529 is suggesting, it may be a dup.

It is a dup and is already implemented for the next release.

**Comment by kovidgoyal** [comment]
And I dont see why it cant be implemented as I suggested.

**Comment by adrusi** [comment]
I am not quite sure what the requester in #3529 is suggesting, it may be a dup.

But this is not achievable by setting command line options as described in the FAQ, as with that method, kitty's config needs to be altered every time the user makes changes to their environment, requiring the same change to be made in `.profile` and `.config/kitty/macos-launch-services-cmdline`.

**Comment by kovidgoyal** [comment]
I'm afraid I dont really understand your use case. Simply set your environment variables system wide, the the kitty process will inherit them just like any other process and pass them on to shells it runs. I am guessing what you really want to do is have a central place to define environment variables. And yeah macOS being rather poorly designed, makes this unnecessarily difficult. If I was stuck on macOS, I would simply write a startup service that has the canonical definitions and runs on boot writing those definitions to the various files they are needed in. Which would be the kitty startup file and sshd config files if you intend to ssh into the box.

And again, this is a dup if you dont understand the issue, read the documentation that was part of the commit that closed the issue.

**Comment by adrusi** [comment]
Yes, 89fd726 implements the change I requested, sorry for missing
that, and thanks for implementing it, even if in response to a
different request!

I think you understand my use case; yes, I prefer to have each
environment variable defined in exactly one place, to guard against
confusing situations where the variable is updated in one place and
not others. MacOS makes this unreasonably hard, and I'm stuck on macOS
at work. Your hack would work, I just prefer a different one, which
89fd726 enables.

Thanks for your work on kitty, by the way, it's a great piece of software!
