### ISSUE TITLE
Is it possible set $TERM to xterm-kitty when used with docker?

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#3533]
**Is your feature request related to a problem? Please describe.**
Maybe check this link is the most easy way to undertand why this is a issue.

https://gitlab.com/craigbarnes/dte/-/issues/117#note_559801272

For a brief description, when use kitty with ssh, it set $TERM env automatically
on remote VPS. (i am not sure if this done by kitty or ssh, anyway, it very useful)
especially for dte, a editor, which use `OSC 52 escape sequence` feature.

but, when use with docker, it not work, $TERM always is `term`.

**Describe the solution you'd like**
set $TERM to xterm-kitty when use with docker.

e.g.  when run following docker command within kitty

```sh
docker run -it -e debian:jessie /bin/bash
root@54956eb7348d:/# echo $TERM                                                                                                                                
xterm  # expect this is xterm-kitty
```

**Comment by kovidgoyal** [comment]
Pass the TERM env var through in docker, presumably it has some config
for that. Or set it in bashrc inside the container.
