### ISSUE TITLE
Word boundary regex in toggle_marker is broken

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#3536]
**Describe the bug**
A regex containing `\b` word boundary specifiers, does not work with `toggle_marker`.

**To Reproduce**
1. Add the following to `kitty.conf`:
    ```
    map f1 toggle_marker iregex 1 ERROR 2 WARNING
    ```
2. Start kitty and verify that the above marks work by typing: `error warning` and then `F1`.
3. Now change `kitty.conf` to:
    ```
    map f1 toggle_marker iregex 1 \bERROR\b 2 WARNING
    ```
4. Repeat Step 2

**Expected behavior**
Both words shall get highlighted in Step 3.

**Observed behavior**
Only the word without the boundary marker is highlighted.

**Environment details**
Ubuntu 20.04 LTS

```
$  kitty --debug-config
kitty 0.20.1 (d374af4341) created by Kovid Goyal
Linux byteevo-scm 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /home/precor/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
adjust_line_height    1
font_family           Hack
initial_window_height (32, 'cells')
initial_window_width  (128, 'cells')
remember_window_size  False
tab_bar_style         powerline
Added shortcuts:
	f1 KeyAction(func='toggle_marker', args=['regex', ((1, 'bERROR:?'), (2, 'bWARNING:?'), (3, '^FAILED')), re.UNICODE])
	ctrl+l KeyAction(func='combine', args=(KeyAction(func='clear_terminal', args=['scrollback', True]), KeyAction(func='send_text', args=['normal,application', b'\x0c'])))
	ctrl+tab KeyAction(func='next_window', args=())
	ctrl+page_up KeyAction(func='previous_tab', args=())
	ctrl+page_down KeyAction(func='next_tab', args=())
	shift+ctrl+tab KeyAction(func='previous_window', args=())
Changed shortcuts:
	shift+ctrl+t KeyAction(func='launch', args=['--type=tab', '--cwd=current'])
	shift+ctrl+enter KeyAction(func='new_window_with_cwd', args=())
```

**Additional context**
- kitty is built from source.  `master` branch @ `d374af43`.

**Comment by kovidgoyal** [comment]
Use \\b

**Comment by salmankhilji** [comment]
> \b

I am.  I copied and pasted the following straight from the docs:

```
map f1 toggle_marker iregex 1 \bERROR\b 2 \bWARNING\b
```

and it does not work.

**Comment by kovidgoyal** [comment]
With two slashes, github seems to eat up the double backslash.

**Comment by salmankhilji** [comment]
> With two slashes, github seems to eat up the double backslash.

Yes, double backslashes work.  Shall I file a separate issue to fix the docs?

**Comment by kovidgoyal** [comment]
On Mon, Apr 26, 2021 at 04:48:57AM -0700, salmankhilji wrote:
> > With two slashes, github seems to eat up the double backslash.
> 
> Yes, double backslashes work.  Shall I file a separate issue to fix the docs?

no need

**Comment by trygveaa** [comment]
> With two slashes, github seems to eat up the double backslash.

If you surround it in backticks, it's shown correctly on github.
