### ISSUE TITLE
"xterm fallback mode" (for SSH connections, docker etc.)

### ISSUE THREAD

**Issue by weeman1337** [kovidgoyal/kitty#3537]
:exclamation: please don't just close this with "read the FAQ".  
This is a serious feature request targeting a daily driver problem.

**Is your feature request related to a problem? Please describe.**

I am connecting to a bunch of Virtual machines, Vagrant boxes and remote SSH servers all the time. Unfortunately kitty requires the target system to know about how to talk to it. This is described in the [FAQ](https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer).

Using the kitty SSH may solve it for simple use cases. It starts getting worse if `sudo` or connection hops comes into play. But this is reality when managing remote machines or development boxes. Furthermore it is not always possible to write files to the remote machines for every user. Like when managing machines with very harsh organisational restrictions.

If possible I am using the kitty SSH or install the `kitt-terminfo` package. It is the best solution. That is where I agree to the FAQ and previous discussions. But I would be great if kitty could work out of the box in these environments as well. Not all fancy (kitty) feature are required. Just a working terminal is enough.

It seems to be a problem for many people. For example see #434, #1613, #1139

**Describe the solution you'd like**

Some kind of fallback or compatibility mode to make kitty work in these environments. No fancy kitty stuff is required. Just a terminal. For me it would be okay to actively enable that by a command.

**Describe alternatives you've considered**

* Using kitty SSH (breaks if `sudo` or another hop is done)

**Comment by kovidgoyal** [comment]
As I have explained umpteen times before, what you are asking for is for
me to implement a mini-xterm inside kitty. That is simply not something
I have the interest/motivation to do. Especially given that in a few
years once the slow moving linux distros distribute kitty-terminfo in
their base images, it will be completely unnecessary. Since your out of
the box XYZ machines will have the kitty terminfo already.

**Comment by weeman1337** [comment]
Thanks for the answer @kovidgoyal . I understand and respect that you don't want to implement that.

Somthing to consider is: Even all the distros will ship `kitty-terminfo` at one day it may be impossible for me to install it as I have to get every package confirmend before.

**Comment by kovidgoyal** [comment]
On Mon, Apr 26, 2021 at 09:52:05AM -0700, Michael Weimann wrote:
> Somthing to consider is: Even all the distros will ship `kitty-terminfo` at one day it may be impossible for me to install it as I have to get every package confirmend before.

No I am saying kitty-terminfo will be included in the main ncurses
package in your distro. Which you have to install for *any* terminal to
work.

**Comment by weeman1337** [comment]
:+1: thanks for the clarification!

**Comment by trygveaa** [comment]
> No I am saying kitty-terminfo will be included in the main ncurses package in your distro. Which you have to install for *any* terminal to work.

I thought the name in ncurses was different (kitty instead of xterm-kitty), and that the file there was somewhat outdated? Has this changed?

**Comment by kovidgoyal** [comment]
On Tue, Apr 27, 2021 at 08:49:54AM -0700, Trygve Aaberge wrote:
> > No I am saying kitty-terminfo will be included in the main ncurses package in your distro. Which you have to install for *any* terminal to work.
> 
> I thought the name in ncurses was different (kitty instead of xterm-kitty), and that the file there was somewhat outdated? Has this changed?

Nope that's still the case. I expect distros will eventually realize
ncurses is umm badly maintained, and start patching it to add terminfo
for terminals they have in the repos.
