### ISSUE TITLE
notcurses pixel images stopped working in version 20.1

### ISSUE THREAD

**Issue by joseluis** [kovidgoyal/kitty#3539]
coming from https://github.com/dankamongmen/notcurses/issues/1599 ...

**Describe the bug**

I can no longer show pixels with notcurses in kitty 20.1 (and 20.0). It does work with 19.3 very well. I've tried both the compiled binaries and latest master from today.

**To Reproduce**

I can reproduce it with any notcurses program that displays pixels

e.g.
```sh
export TERM=xterm-kitty
git clone https://github.com/dankamongmen/notcurses

# example 1
cd notcurses/build
./pixel ../data/chunli38.png

# example 2
cd -
cd notcurses/rust/examples
cargo re pixel-cell
```

**Expected behavior**
The images should be shown. It does work for me with 19.3.

**Environment details**

Output of kitty --debug-config
```
$ ./kitty-20.1 --debug-config
kitty 0.20.1 (f3726023c2) created by Kovid Goyal
Linux devluiso 5.10.27-051027-generic #202103310028 SMP Thu Apr 1 02:16:48 UTC 2021 x86_64
Linux Mint 20.1 Ulyssa \n \l
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"
Running under: X11

Config options different from defaults:
```

**Additional context**

The problem is the same with `kitty --config NONE`.  And I'm running both kitty versions from a build directory in my home, without installing them globally.

using  kitty 20.1 keeps repeating: `OSError: [Errno 95] Operation not supported: '/home/myuser/.cache/kitty'` each time a sprixel should be shown.

The output of strace of 20.1 gives this additional info:
`openat(AT_FDCWD, "/home/myuser/.cache/kitty", O_RDWR|O_EXCL|O_CLOEXEC|O_TMPFILE, 0600) = -1 EOPNOTSUPP (Operation not supported)`

And after the invoked program finishes the following text is outputted to the terminal:
```
pixel-cellGi=1;ENOSPC:Failed to store image data in disk cache pixel-cellGi=2;ENOSPC:Failed to store image data in disk cache pixel-cellGi=3;ENOSPC:Failed to store image data in disk cache
```

**Comment by kovidgoyal** [comment]
From that bug report the problem is clear. kitty cant find disk space to
store the images in the new on disk cache, which is present in 0.20+ and
not in 0.19. As I said there, the directory kitty uses is ~/.cache/kitty
for this. Make sure you have disk space there, or set the
KITTY_CACHE_DIR env var to have kitty use some other location for its
cache.

**Comment by joseluis** [comment]
Hi Kovid, thanks but that really doesn't solve my problem:

1. I have 98 GB of space in there as reported by `df -h ~/.cache/kitty`.
2. when setting KITTY_CACHE_DIR env var to another location it still fails with **exactly** the same error (and path), like if it's ignoring the setting.

```$ env | grep KIT
KITTY_WINDOW_ID=1
KITTY_CACHE_DIR=/tmp/kitty
```

Do you have any other suggestion?

**Comment by kovidgoyal** [comment]
You need to set KITTY_CACHE_DIR before launching kitty. Is there something unusual about your home directory, some reason O_TMPFILE is failing on it? Is it a networked filesystem or similar?

**Comment by kovidgoyal** [comment]
And see if this helps: https://github.com/kovidgoyal/kitty/commit/ae1df38c889282608a909e834e85059726ab8ec6

**Comment by joseluis** [comment]
> You need to set KITTY_CACHE_DIR before launching kitty.

I did...

Is there something unusual about your home directory, some reason O_TMPFILE is failing on it? Is it a networked filesystem or similar?

Well, it is encrypted using [ubuntu home encryption](https://help.ubuntu.com/community/EncryptedHome#Encrypted_Home) maybe that affects it somehow?

**Comment by kovidgoyal** [comment]
On Tue, Apr 27, 2021 at 12:09:01AM -0700, José Luis Cruz wrote:
> > You need to set KITTY_CACHE_DIR before launching kitty.
> 
> I did...

Aaah sorry the correct name is KITTY_CACHE_DIRECTORY

> 
> Is there something unusual about your home directory, some reason O_TMPFILE is failing on it? Is it a networked filesystem or similar?
> 
> Well, it is encrypted using [ubuntu home encryption](https://help.ubuntu.com/community/EncryptedHome#Encrypted_Home) maybe that affects it somehow?

I have no idea why that should break O_TMPFILE, but I wouldn't be
surprised, Linux is full of such half baked things. In any case I have
added a fallback to use mkostmp instead whenn O_TMPFILE fails.

**Comment by joseluis** [comment]
> And see if this helps: [ae1df38](https://github.com/kovidgoyal/kitty/commit/ae1df38c889282608a909e834e85059726ab8ec6)

I just tried the latest master... nothing changes.

Well.. the only change seems to be the outputted error now is `OSError: [Errno 22] Invalid argument: '/home/myuser/.cache/kitty`, but the one shown in strace is the same as before.

> Aaah sorry the correct name is KITTY_CACHE_DIRECTORY

Ok I was very puzzled by this lol....

using that variable it DOES WORK for me now, thank you :)

**Comment by kovidgoyal** [comment]
Well if mkostemp is also failing then I dont really have any solution. Can you create any files in ~/.cache/kitty at all?

**Comment by joseluis** [comment]
Yes, without problem. In fact even kitty version 20.1 does create a main.json inside that dir on exit, no matter what I put in KITTY_CACHE_DIRECTORY

**Comment by kovidgoyal** [comment]
On Tue, Apr 27, 2021 at 12:34:14AM -0700, José Luis Cruz wrote:
> Yes, without problem. In fact even kitty version 20.1 does create a main.json inside that dir on exit, no matter what I put in KITTY_CACHE_DIRECTORY

kitty does not produce a file named main.json as far as I know.

**Comment by joseluis** [comment]
```
$ cat ~/.cache/kitty/main.json
{"window-size": [1920, 1056]}
```

when I resize the window and exit it gets updated....

**Comment by kovidgoyal** [comment]
ah you have the option to remember window size on I guess, forgot about
that. Yeah then I can only conclude whatever the encryption driver you
are using is preventing the creation of temp files. So just set the env
var to somewhere else.

**Comment by joseluis** [comment]
Works for me, thanks. I added this to my ~/.bashrc:
```bash
if [[ -n "${KITTY_WINDOW_ID}" ]]; then
    export TERM=xterm-kitty
    export KITTY_CACHE_DIRECTORY=/foolprooftmpdir
fi
```
