### ISSUE TITLE
Only 8 colors showing up in theme.

### ISSUE THREAD

**Issue by meskarune** [kovidgoyal/kitty#354]
I installed kitty using the arch linux AUR package, and then downloaded the default kitty.conf and ran the terminal. Only the first 8 colors of the terminal color scheme seem to show up:

![kittytermcolors](https://user-images.githubusercontent.com/153029/36872282-c2df7b68-1d72-11e8-8337-cb81ed55e14c.png)

but other colors in vim work just fine. Am I doing something wrong? I used wget to download the kitty.conf file and it isn't edited.

    kitty 0.8.0 created by Kovid Goyal

**Comment by kovidgoyal** [comment]
The first 8 colors use the SGR codes 30-38 for foreground and 40-48 for background. For the next 8 you need to use the codes 90-98 and 100-108. See https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters
