### ISSUE TITLE
Splitter in tall layout is not dead centered

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#3540]
**Describe the bug**
The splitter when tall layout is used is not dead centered.

**To Reproduce**
1. Launch an instance of kitty like this:
    ```
    kitty -o enabled_layouts='tall:bias=50;full_size=1;mirrored=false' &
    ```
2. CTRL+SHIFT once to create a new window.
3. Launch another instance of kitty like this:
    ```
    kitty -o enabled_layouts='splits:split_axis=horizontal' &
    ```
4. CTRL+SHIFT once to create a new window.
5. Compare the two windows.

**Expected behavior**
Both windows within the tall layout shall have identical pixel sizes.

**Observed behavior**
- The splitter within the `tall` layout is not dead centered.
- The splitter within the `splits` layout is indeed dead centered.
- It also odd that there is more padding at the top within the `tall` layout.

**Screenshots**

![splits](https://user-images.githubusercontent.com/40219235/116154545-a304a900-a69d-11eb-96db-03b2a9235815.png)
![tall](https://user-images.githubusercontent.com/40219235/116154551-a435d600-a69d-11eb-99f3-d5a87e8e2d03.png)

**Environment details**
Ubuntu 20.04 LTS

```
$ kitty --debug-config
kitty 0.20.1 (162e498347) created by Kovid Goyal
Linux byteevo-scm 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /home/precor/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
adjust_line_height    1
font_family           Hack
initial_window_height (32, 'cells')
initial_window_width  (128, 'cells')
remember_window_size  False
tab_bar_style         powerline
Added shortcuts:
	 f1 KeyAction(func='toggle_marker', args=['regex', ((1, '\\bERROR:?'), (2, '\\bWARNING:?'), (3, '^FAILED')), re.IGNORECASE|re.UNICODE])
	 f8 KeyAction(func='launch', args=['--stdin-source=@screen_scrollback', '--type=overlay', 'gvim', '-'])
	 ctrl+l KeyAction(func='combine', args=(KeyAction(func='clear_terminal', args=['scrollback', True]), KeyAction(func='send_text', args=['normal,application', b'\x0c'])))
	 ctrl+tab KeyAction(func='next_window', args=())
	 ctrl+page_up KeyAction(func='previous_tab', args=())
	 ctrl+page_down KeyAction(func='next_tab', args=())
	 shift+ctrl+tab KeyAction(func='previous_window', args=())
Changed shortcuts:
	 shift+ctrl+t KeyAction(func='launch', args=['--type=tab', '--cwd=current'])
	 shift+ctrl+enter KeyAction(func='new_window_with_cwd', args=())
```

**Additional context**
kitty is compile from source. `master` branch @ `162e4983`.

**Comment by kovidgoyal** [comment]
That's because the two layouts handle the extra padding caused by window
sizes not being exact multiples of cell sizes differently. There is no
requirement that they should be the same.
