### ISSUE TITLE
tmux over ssh

### ISSUE THREAD

**Issue by leier69** [kovidgoyal/kitty#3541]
OS: Arch Linux (btw)
Bug is on x11 and wayland.
Bug is not present using alacritty, or gnome terminal.

Bug:

I ssh and tmux works as expected on my server, but when I try to do control shortcusts in tmux or bash it does not work and prints random characters. Example bellow.

```
[2000][leier@serverhost][] /home/leier$ 7;5uc7;5uc7;5u9;5u9;5u9;5u9;5u9;5u7;5uc8;5u8;5u8;5u8;5u
-bash: 7: command not found
-bash: 5uc7: command not found
-bash: 5uc7: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u7: command not found
-bash: 5uc8: command not found
-bash: 5u8: command not found
-bash: 5u8: command not found
-bash: 5u8: command not found
-bash: 5u: command not found
[2001][leier@serverhost][] /home/leier$ 
```

```
❯ kitty --debug-config 
kitty 0.20.1 created by Kovid Goyal
Linux arch 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/leier/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=10, green=15, blue=20)
bold_font             Hack Bold
bold_italic_font      Hack Bold Italic
draw_minimal_borders  False
font_family           Hack
font_size             13.0
initial_window_height (650, 'px')
initial_window_width  (900, 'px')
italic_font           Hack Italic
linux_display_server  x11
remember_window_size  False
term                  xterm-256color
window_border_width   (0, 'pt')
Added shortcuts:
	ctrl++ KeyAction(func='change_font_size', args=(True, '+', 2.0))
	ctrl+- KeyAction(func='change_font_size', args=(True, '-', 2.0))
```

**Comment by leier69** [comment]
For specificity: It happens when I try to do any ctrl+anything shortcut. both bash and tmux shortcuts.

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#i-am-using-tmux-and-have-a-problem

And I can tell you that doing ssh and then running tmux and pressing
either ctrl+c or ctrl+d works as expected on my arch system.

**Comment by leier69** [comment]
@kovidgoyal I love that its you maintaining kitty. Your so awesome man. Thanks for quick answer!

**Comment by kovidgoyal** [comment]
You're welcome :)

**Comment by leier69** [comment]
Wait... That did not answer me tho. I really need tmux over ssh for my work. I tried reading up on doc and various issues, but the issue still remain tho. Is there any work around? @kovidgoyal

**Comment by Luflosi** [comment]
See what `echo $TERM` prints inside and outside of tmux.

**Comment by leier69** [comment]
outside tmux or ssh:
```
❯ echo $TERM    
xterm-256color```

when I ssh to server:
```
[2002][leier@server][] /home/leier$ echo $TERM
xterm-256color
```

when I tmux:
```
[2004][leier@server][] /home/leier$ echo $TERM
screen
```

**Comment by Luflosi** [comment]
Set it to `xterm-kitty` outside of tmux.

**Comment by leier69** [comment]
I get this when I ssh into the server then @Luflosi 
```
tput: unknown terminal "xterm-kitty"
```

**Comment by leier69** [comment]
Then when trying to start tmux, I get this:
```
open terminal failed: missing or unsuitable terminal: xterm-kitty
```

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer.

**Comment by Luflosi** [comment]
Does tmux print this error? Does `infocmp xterm-kitty` print something on the server?

**Comment by leier69** [comment]
`infocmp xterm-kitty` shows the same on the remote host inside and outside tmux after using  `kitty +kitten ssh myserver`.

That fixed the color issue. But ctrl+l or any tmux command still does not work. @Luflosi. And I appriciate you taking out time to help the ones with special needs

**Comment by Luflosi** [comment]
Is `TERM` set to `xterm-kitty` on your local machine, outside of SSH?

**Comment by kovidgoyal** [comment]
What ctrl keys are you pressing?

**Comment by leier69** [comment]
local machine or plain kitty:
```
❯ echo $TERMINFO $TERM
/usr/lib/kitty/terminfo xterm-kitty
```
Inside ssh without tmux:
```
[2002][leier@server][] /home/leier$ echo $TERMINFO $TERM
xterm-kitty
```
Inside ssh with tmux:
```
[2002][leier@server][] /home/leier$ echo $TERMINFO $TERM
screen
```

**Comment by leier69** [comment]
@koekeishiya Im pressing forexample ctrl+l to clear the terminal, or ctrl+a AKA my tmux modifier.

**Comment by kovidgoyal** [comment]
And this happens only inside tmux, not if you just ssh and press those
keys?

**Comment by leier69** [comment]
yea :(

**Comment by leier69** [comment]
[2000][leier@serverhost][] /home/leier$ 7;5uc7;5uc7;5u9;5u9;5u9;5u9;5u9;5u7;5uc8;5u8;5u8;5u8;5u
-bash: 7: command not found
-bash: 5uc7: command not found
-bash: 5uc7: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u9: command not found
-bash: 5u7: command not found
-bash: 5uc8: command not found
-bash: 5u8: command not found
-bash: 5u8: command not found
-bash: 5u8: command not found
-bash: 5u: command not found
[2001][leier@serverhost][] /home/leier$

**Comment by kovidgoyal** [comment]
Then its likely something in your tmux config, bisect it to find the
culprit.

**Comment by crepppy** [comment]
I am also getting this issue, only started happening after updating kitty, not sure which commit caused the error

**Comment by trygveaa** [comment]
@leier69, @crepppy: Have you tried removing your tmux and shell config? It sounds like you have something enabling the new [keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol.html) introduced in version 0.20.0.

**Comment by nerdrew** [comment]
I also started seeing this with the recent kitty update (0.20.0). No control keys work for me (e.g. C-c, C-z).

**Comment by nerdrew** [comment]
I'm not sure if `showkey` is the right way to show this, but here's the `showkey` output for `C-c`:

outside tmux:
```
> showkey -a

Press any keys - Ctrl-D will terminate this program

^C 	 3 0003 0x03
```

inside tmux:
```
> showkey -a

Press any keys - Ctrl-D will terminate this program

^[[99;5u         27 0033 0x1b
         91 0133 0x5b
         57 0071 0x39
         57 0071 0x39
         59 0073 0x3b
         53 0065 0x35
        117 0165 0x75
```

**Comment by trygveaa** [comment]
@nerdrew: Please read my comment and try that:

> Have you tried removing your tmux and shell config? It sounds like you have something enabling the new keyboard protocol introduced in version 0.20.0.

Your showkey output does indeed confirm that the new keyboard protocol is enabled inside tmux for you.

**Comment by nerdrew** [comment]
Looking now. FWIW, I don't have a shell or tmux config for my user. Do you know how to only use default configs for tmux?

**Comment by nerdrew** [comment]
What would enable the new keyboard protocol? That might be easier for me to search for in the running config :)

**Comment by nerdrew** [comment]
From what I can tell, this happens with the default settings for my tmux (version 1.8). I.e. there is no `~/tmux.conf` , `/etc/tmux.conf` and it still happens when I start bash with `sh` or `bash --noprofile --norc`

**Comment by trygveaa** [comment]
Hm, okay. It does not happen for me with tmux 3.1c or 3.2. Version 1.8 is very old (8 years), so you should probably try upgrading it.

You can provide an empty config for tmux with the `-f` option, though if tmux is already running you have to use `-L` or `-S` so it doesn't connect to the existing session and uses that config. E.g.

```
tmux -f /dev/null -L tmux-test
```

You can see how the protocol is enabled in the docs i linked:

> Emit the escape code CSI > 1 u at application startup or when entering alternate screen mode

So e.g. `printf '\e[>1u'`, though it doesn't have to be enabled with this exact command of course.

**Comment by nerdrew** [comment]
Upgrade: LOL. I wish. Appears to still be broken when starting tmux with `tmux -f /dev/null new-session sh`

**Comment by trygveaa** [comment]
Do you have tmux running? As I said, you have to use `-L` or `-S`, otherwise it will use the same config as the running tmux (even if you use new-session).

**Comment by nerdrew** [comment]
no, tmux is not running

**Comment by kovidgoyal** [comment]
You need to ask the tmux developers why your version of tmux is doing that. And you can turn off extended keyboard mode with ```printf '\e[<u'```

**Comment by nerdrew** [comment]
Interesting. `printf '\e[>1u'` doesn't fix it.

**Comment by nerdrew** [comment]
If I start `screen` and then start `tmux`, everything works...

**Comment by nerdrew** [comment]
Derp. I mean `printf '\e[<u'` doesn't fix it.

**Comment by kovidgoyal** [comment]
Try doing it multiple times since its a stack.

**Comment by nerdrew** [comment]
LOL. I needed to do `printf "\033Ptmux;\033\033[<u\033\\"` to get it past the tmux filtering of unknown escape codes...

**Comment by nerdrew** [comment]
Thanks!

**Comment by benpro** [comment]
> LOL. I needed to do `printf "\033Ptmux;\033\033[<u\033\\"` to get it past the tmux filtering of unknown escape codes...

I have the same bug... And this resolve it.
This is a regression as previous version of Kitty were working fine. Seems not backward compatible!
