### ISSUE TITLE
support for Emoji 13.1

### ISSUE THREAD

**Issue by dankamongmen** [kovidgoyal/kitty#3542]
The Emoji 13.1 supplement to Unicode 13.0 added a handful of generally worthless (IMHO) emoji:

http://www.unicode.org/emoji/charts/emoji-released.html

they don't yet appear to be in `emoji-sequences.txt`, where i imagine you're getting your naming from. just wanted to let you know in case you hadn't seen them--I notice they're not present in the unicode input picker compiled from the tip of `master`.

just a friendly note =]

**Comment by kovidgoyal** [comment]
It's auto-generated by gen-wcwidth.py and yes that reads its data from emoji-sequences.txt for emoji when the new emoji are added there, ping me and I will update.
