### ISSUE TITLE
My favourite fonts look ugly (antialiasing issue or something?)

### ISSUE THREAD

**Issue by beelze** [kovidgoyal/kitty#3545]
Usually my monospace fonts are Consolas and Fire Code Retina. They are looks good and accurate (to be honest, everywhere except in Kitty). What I'm doing wrong?
Left side is another terminal, right side – Kitty. Same font (Fire Code Retina) but different appearance.
![20210428-1318](https://user-images.githubusercontent.com/5619507/116363222-b8580f80-a824-11eb-964d-8680d1e7073e.png)

**Comment by kovidgoyal** [comment]
dup of #214
