### ISSUE TITLE
[minor] New macOS icon is bigger than it should be 

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#3547]
**Describe the bug**
New macOS icon is bigger than it should be

**To Reproduce**
1. Make sure you have `0.20.2` version
2. New App icon is bigger than the rest of the apps

**Expected behavior**
To match the macOS guidelines https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon

**Screenshots**
<img width="1248" alt="Screenshot 2021-04-28 at 12 41 09" src="https://user-images.githubusercontent.com/63876/116391309-46c99280-a81f-11eb-8b75-39675bc19b2b.png">
<img width="306" alt="Screenshot 2021-04-28 at 12 37 06" src="https://user-images.githubusercontent.com/63876/116391311-48935600-a81f-11eb-80fe-8cff2529af81.png">

**Environment details**
OS: macOS 11.2.3

```
kitty 0.20.2 created by Kovid Goyal
Darwin <redacted machine name> 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2.3 BuildVersion:	20D91
Loaded config files: /Users/ahmedelgabri/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color          None
adjust_line_height           2
allow_remote_control         y
background                   Color(red=17, green=17, blue=17)
bold_font                    PragmataPro Mono Liga Bold
bold_italic_font             PragmataPro Mono Liga Bold Italic
clipboard_control            frozenset({'write-primary', 'write-clipboard', 'no-append'})
color0                       Color(red=29, green=31, blue=33)
color1                       Color(red=204, green=102, blue=102)
color10                      Color(red=153, green=204, blue=153)
color11                      Color(red=255, green=204, blue=102)
color12                      Color(red=102, green=153, blue=204)
color13                      Color(red=204, green=153, blue=204)
color14                      Color(red=102, green=204, blue=204)
color15                      Color(red=221, green=221, blue=221)
color2                       Color(red=181, green=189, blue=104)
color3                       Color(red=240, green=198, blue=116)
color4                       Color(red=129, green=162, blue=190)
color5                       Color(red=178, green=148, blue=187)
color6                       Color(red=138, green=190, blue=183)
color7                       Color(red=197, green=200, blue=198)
color8                       Color(red=51, green=51, blue=51)
color9                       Color(red=242, green=119, blue=122)
cursor                       Color(red=32, green=187, blue=252)
cursor_stop_blinking_after   0
enable_audio_bell            False
font_family                  PragmataPro Mono Liga
font_size                    12.0
force_ltr                    True
foreground                   Color(red=197, green=200, blue=198)
hide_window_decorations      1
inactive_tab_background      Color(red=29, green=31, blue=33)
italic_font                  PragmataPro Mono Liga Italic
kitty_mod                    8
macos_custom_beam_cursor     True
macos_option_as_alt          3
macos_thicken_font           1.1
macos_traditional_fullscreen True
rectangle_select_modifiers   1026
scrollback_lines             20000
select_by_word_characters    :@-./_~?&=%+#
strip_trailing_spaces        smart
tab_activity_symbol          ▲
tab_bar_edge                 1
window_alert_on_bell         False
window_margin_width          FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
window_padding_width         FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added shortcuts:
	 ctrl+i KeyAction(func='send_text', args=['application', b'H'])
	 shift+cmd+h KeyAction(func='show_scrollback', args=())
Changed shortcuts:
	 cmd+, KeyAction(func='move_tab_backward', args=())
	 cmd+h KeyAction(func='previous_window', args=())
	 cmd+u KeyAction(func='input_unicode_character', args=())
	 cmd+w KeyAction(func='close_window', args=())
```

**Additional context**

**Comment by kovidgoyal** [comment]
This should be an easy fix for someone on macOS, simply adjust the icon in kitty-framed.svg shrinking the opaque part and this adding some transparent borders. The run python logo/make.py to generate the iconset. Since I cant find any documentation for how much padding there should be, it will require experimentation, and as I dont use macs, this will be pretty painful for me.

**Comment by MindTooth** [comment]
![Icon-256](https://user-images.githubusercontent.com/33870508/116406341-d6c40800-a830-11eb-8519-fda16bc86342.png) 
![Icon-256](https://user-images.githubusercontent.com/33870508/116406833-61a50280-a831-11eb-9945-6f808a75e57f.png)


Can something like this work?  Based on this Figma [template](https://www.figma.com/community/file/857303226040719059).

**Comment by kovidgoyal** [comment]
I dont know, you tell me :) I think you need to make the white background area smaller and have transparency around it.

**Comment by MindTooth** [comment]
![Screen Shot 2021-04-28 at 14 58 20](https://user-images.githubusercontent.com/33870508/116407615-3b339700-a832-11eb-84cf-6ff5d201a677.png)

Well, I'm not really the one to ask either. 😝   But, from the image above, you can see that it is smaller and contains transparency.  So I believe that it fits.  I'll try to replace the icon for my own app.

**Comment by ahmedelgabri** [comment]
@MindTooth I'd vote for the first one icon.

**Comment by MindTooth** [comment]
![Screen Shot 2021-04-28 at 15 19 18](https://user-images.githubusercontent.com/33870508/116410500-23a9dd80-a835-11eb-94a0-4b02b1dbacc5.png)

Seems to work nicely.

**Comment by kovidgoyal** [comment]
Fine by me feel free to send a PR
