### ISSUE TITLE
Ctrl+Shift+left cannot be unmapped

### ISSUE THREAD

**Issue by greenfoo** [kovidgoyal/kitty#3554]
**Context**
I know something similar has been reported before (#3236 and #2670) and the answer in both cases was that `You cannot use ctrl+shift based bindings in terminal programs` (the reason being that `ctrl+shift+<something>` generates the same key codes as `ctrl+<something>`), which is true... **except** for when `<something>` is an arrow key.

This is the sequence returned by `showkey -a` in each case:
```
ctrl+shift+<left_arrow>  --> 0x1b 0x5b 0x31 0x3b 0x36 0x44
ctrl+<left_arrow>        --> 0x1b 0x5b 0x31 0x3b 0x35 0x44

ctrl+shift+<right_arrow> --> 0x1b 0x5b 0x31 0x3b 0x36 0x43
ctrl+<right_arrow>       --> 0x1b 0x5b 0x31 0x3b 0x35 0x43
```

**Bug description**
Because of what was just explained, it should be possible to unmap the  `ctrl+shift+<arrow_key>` shortcuts in `kitty.conf`, like this:
```
map ctrl+shift+left no_op
map ctrl+shift+right no_op
```
...so that they can be used by the program running inside kitty (in my particular use case, that would be "tmux").
However, in the current version of kitty those two lines have no effect.

**Workaround**
There is a workaround to achieve the same result, which consists in remapping those shortcuts to the real byte sequence, by adding these two lines to `kitty.conf`:
```
map ctrl+shift+left  send_text \x1b\x5b\x31\x3b\x36\x44
map ctrl+shift+right send_text \x1b\x5b\x31\x3b\x36\x43
```
So... please feel free to discard this issue if you consider this workaround is good enough.

Thanks!

**Comment by kovidgoyal** [comment]
I cannot replicate this, running:

kitty --config NONE -o 'map ctrl+shift+left no-op' showkey -a

and pressing ctrl+shift+left

generates the expected output in showkey, showing the key press was
indeed passed to the terminal. And note that your send_text mapping is
incorrect, you forgot the mode for it, so it will be ignored by kitty.
you need

map ... send_text normal ...
map ... send_text application ...

**Comment by greenfoo** [comment]
Ok... I know what is going on. First of all, you are right, **this is not a bug and kitty works as expected**, sorry for the noise.

I've been reviewing my bash history to check what my tests were and turns out I was using the "all" keyword backwards:
1. I used "all" where I shouldn't : `map ctrl+shift+left all no_op`
2. I didn't use "all" where I should: `map ctrl+shift+left  send_text \x1b\x5b\x31\x3b\x36\x44`

Because of this, (1) didn't have any effect and the key press was not passed to the terminal (which is why I thought there was a bug) and (2), even if also incorrect, made kitty pass the key press to the terminal (which is why I thought this was a work-around while, in reality, any other invalid mapping such as `map ctrl+shift+left hello_world` would have had the same effect).

So, again, sorry for the confusion, and for any one else reading this, the conclusion is that you can unmap "ctrl+shift+<arrow_key>" with "no_op" as expected: `map ctrl+shift+left no_op`
