### ISSUE TITLE
remember font scaling for dual monitor when returning to previous ?

### ISSUE THREAD

**Issue by mckellygit** [kovidgoyal/kitty#3565]
Hi,
Thank you for kitty.
If I have a laptop and an external monitor with different resolutions -
I have a setup on the external monitor and then switch to laptop monitor - the kitty terminal scales down, as makes sense.
But when switching back to the external monitor kitty terminal remains at the smaller window size and font.
I think perhaps with wayland we cannot position and size the window so there is no chance ?
If I use x11 instead of wayland, when I switch back to larger external monitor the window returns to its previous position and size but the font scale does not return to what it was.  I have to reload my X resources to change the font.
With x11, is it possible to return the font size/scale to what it was before ?
thx

**Comment by kovidgoyal** [comment]
Yes, on wayland the compositor is responsible for window positioning.
And on X11 DPI is a single global setting not per monitor, which is what
gets changed when you reload resources.

Your best bet is to use a wayland compositor that behaves as you would
like.

**Comment by mckellygit** [comment]
Thanks.
I reload resources to resolve the too large font size after going to the larger monitor.
