### ISSUE TITLE
Support remote control when running tmux

### ISSUE THREAD

**Issue by luisdavim** [kovidgoyal/kitty#3566]
There's a solution in  https://github.com/wookayin/kitty-tmux would you consider supporting this officially?

**Comment by kovidgoyal** [comment]
It works already, just use a socket. As for using a passthrough escape
code, sure I will accept a PR to add a --passthrough option to kitty @
to avoid using a socket.

**Comment by kovidgoyal** [comment]
And note that the solution you linked to does not actually work. remote control in general requires two way communication, from the client to the terminal and back. tmux passthrough will work for client to terminal, but the terminal to client half may or may not work depending on whether tmux passthrough works in that direction or not. And it defintiely wont work if there are multiple tmux windows in sone kitty window, and the communication is not from the currently focused window.

**Comment by luisdavim** [comment]
Is this documented somewhere?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/remote-control.html
