### ISSUE TITLE
stty contains "-brkint"

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#3570]
When using kitty `stty` shows:
```
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
```

Whereas with urxvt it shows:
```
speed 38400 baud; line = 0;
iutf8
```

FWIW xfce4-terminal shows:
```
speed 38400 baud; line = 0;
-brkint -imaxbel
```

The problematic thing there for me currently is `-brkint`, which causes `firefox` (and `chromium`) to not detach from the terminal / to the background (apparently) when being started (for the first time - without a running instance), i.e. it will cause Vim/Neovim to hang then when opening an URL from there, and `Ctrl-C` will kill the browser then.

**Environment details**
OS: Arch Linux

```
% kitty-dev --config=/dev/null --debug-config
kitty 0.20.2 (b570dfcd09) created by Kovid Goyal
Linux hostname 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /dev/null
Running under: X11

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
The settings for the tty device are controlled by the application
running in the terminal, not the terminal. The initial settings are set
by the kernel. And you most definitely want your tty to have brkint
unless you are using it in raw mode, otherwise pressing ctrl-c will not
cause a SIGINT. 

If you want to run graphical programs and have them detach from the
controlling terminal you should use the proper technique for it. Many
GUI programs come with something like a --detach command line flag for
this. If your GUI program is not considerate enough to provide such a
flag, you can partially fake it by doing, for example::

    firefox </dev/null &>/dev/null 2&>/dev/null & disown

This is by no means complete, for a more comprehensive solution, see
https://software.clapper.org/daemonize/

However the above will prevent firefox from getting SIGINT

**Comment by blueyed** [comment]
> The initial settings are set by the kernel.

Probably urxvt is doing something special then on top?

From a quick grep it looked like kitty might do something based on termios and/or `cfmakeraw`..?

> And you most definitely want your tty to have brkint
unless you are using it in raw mode, otherwise pressing ctrl-c will not
cause a SIGINT.

Yeah, that's what I've thought.  But I am not supposed to do `stty sane` in my shell config, am I?

How does it work for you / where is brkint set normally then?

**Comment by kovidgoyal** [comment]
On Tue, May 04, 2021 at 09:50:14AM -0700, Daniel Hahler wrote:
> > The initial settings are set by the kernel.
> 
> Probably urxvt is doing something special then on top?

No clue, I have never read the urxvt source code. 

> 
> From a quick grep it looked like kitty might do something based on termios and/or `cfmakeraw`..?

There's lot of code in kitty that uses raw terminal mode just not any
that does from the terminal side. The code that creates the terminal
device is in child.py look for openpty(), the only thing it sets is
iutf-8. It could be that the python library function openpty() is
setting it, though seems unlikely to me. The rest of the code that
spawns the child process is in child.c look at the spawn function, again
doesnt do anything via termios.

> 
> > And you most definitely want your tty to have brkint
> unless you are using it in raw mode, otherwise pressing ctrl-c will not
> cause a SIGINT.
> 
> Yeah, that's what I've thought.  But I am not supposed to do `stty sane` in my shell config, am I?

No, and at least on my system ctrl-c generates sigint as expected,
despite what stty claims.

> 
> How does it work for you / where is brkint set normally then?

How does what work? Ctrl-c does generate SIGINT and I detach GUI
programs using a technique similar to what i posted before.

**Comment by kovidgoyal** [comment]
Oh and incidentally, on my system, *every* terminal other than urxvt and the linux kernel console has -brkint. I highly doubt browsers have special case code to detach only when running from urxvt.
