### ISSUE TITLE
0.20.1 broke GTK integration

### ISSUE THREAD

**Issue by bendem** [kovidgoyal/kitty#3572]
**Describe the bug**
After upgrade to `0.20.1-1.fc33`, kitty window is small has custom decoration and doesn't respect desktop font size

**To Reproduce**
Open kitty with new version

**Expected behavior**
The previous behavior

**Screenshots**
before:
![image](https://user-images.githubusercontent.com/2681677/117039519-28750280-ad09-11eb-958c-c9c55af1179b.png)
after:
![image](https://user-images.githubusercontent.com/2681677/117039654-4fcbcf80-ad09-11eb-838e-06ecc8eca483.png)

**Environment details**
OS: Fedora 33 

```
kitty 0.20.1 created by Kovid Goyal
Linux fedora-kwak 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: /home/bendem/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background           Color(red=17, green=17, blue=17)
enable_audio_bell    False
tab_bar_style        powerline
visual_bell_duration 1.0
```

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
kitty never respected desktop font size, you just happened to have the
font size in kitty.conf and your desktop match. As for the rest see
#3284

**Comment by bendem** [comment]
Ah, I see this is more CSD vs SSD. Thanks gnome... Sorry you have to deal with this BS.

**Comment by bendem** [comment]
As for the font size, it seems switching to wayland made kitty not respect the scaling factor anymore. I've added a font_size (unset before) to `desktop_size * scaling_factor` and I'm back to the previous size.

**Comment by kovidgoyal** [comment]
On Wed, May 05, 2021 at 12:27:45AM -0700, bendem wrote:
> Ah, I see this is more CSD vs SSD. Thanks gnome... Sorry you have to deal with this BS.

Yeah, GNOME are being really very stupid about this.

**Comment by kovidgoyal** [comment]
On Wed, May 05, 2021 at 12:31:23AM -0700, bendem wrote:
> As for the font size, it seems switching to wayland made kitty not respect the scaling factor anymore. I've added a font_size (unset before) to `desktop_size * scaling_factor` and I'm back to the previous size.

It definitely does. Try changing the scale dynamically and you will see
it auto adjust.

**Comment by bendem** [comment]
As you can see here, it doesn't.

https://user-images.githubusercontent.com/2681677/117148823-e6a29580-adb6-11eb-910f-d2f763c9f5fb.mp4

**Comment by kovidgoyal** [comment]
Then open a separate bug report for that.

**Comment by kovidgoyal** [comment]
Actually I looked at your video and while my screen is too small to see the details very clearly it looks correct to me. Changing the scale does change the font size in both your browser and kitty by roughly the same amount, as expected.

**Comment by bendem** [comment]
> Then open a separate bug report for that.

Done

> Actually I looked at your video and while my screen is too small to see the details very clearly it looks correct to me. Changing the scale does change the font size in both your browser and kitty by roughly the same amount, as expected.

Made a better version with only one monitor, the font size of kitty doesn't change.
