### ISSUE TITLE
macOS Icon Size

### ISSUE THREAD

**Issue by jawang35** [kovidgoyal/kitty#3573]
**Describe the bug**
The new icon looks oversized on the dock. The framed icon also looks rounder than the conventional macOS icon frame. I personally think the unframed icon looked better. I think this was introduced in https://github.com/kovidgoyal/kitty/commit/3fcf83e685e715522c85cd13a3337aff31781776.

**Screenshots**
![Screen Shot 2021-05-04 at 1 25 42 PM](https://user-images.githubusercontent.com/5923395/117065436-5d1e9500-acdc-11eb-8854-f13b80885759.png)

**Environment details**
OS: macOS Mojave 10.14.6

**Comment by Luflosi** [comment]
This is already fixed, see #3547.

**Comment by jawang35** [comment]
Thanks. Sorry I missed that commit.
