### ISSUE TITLE
Reasons why I use Kitty instead of Alacritty

### ISSUE THREAD

**Issue by sujay1844** [kovidgoyal/kitty#3577]
This is not a bug. It's my opinion only. I thought this info might be useful to someone and I wanted to appreciate the developer @kovidgoyal for a great project
### Reasons I prefer Kitty over alacritty:
- **Kitty is made by an Indian!!**
- Configuring Kitty is much easier than configuring Alacritty. 
It takes time to understand which code is under which block in the `alacritty.yml`. In fact, I ended up spending 1.5 hours to configure my colors. The issue was that the hex codes had an extra of two spaces and so were under the wrong section.
- It's faster.
My measure of speed is rendering text. 
When I do `time tree /` on both terminals, Alacritty takes `25.41 secs` while Kitty takes `10.22 secs`
This method of measuring performance can be lame since I'm never gonna tree my root directory.
In real life, I don't feel the difference between any of the terminal emulator. (Exception: `xterm` is slow af)
- The aim of the project
Alacritty wants to be minimal and I get that. But Kitty is full of features that you may or may not use, that's more of my style.
- (Minor) Icon of kitty is better.

**Comment by kovidgoyal** [comment]
Cool, thanks :)
