### ISSUE TITLE
Scaling factor ignored in gnome

### ISSUE THREAD

**Issue by bendem** [kovidgoyal/kitty#3578]
**Describe the bug**
The scaling factor is ignored in gnome (cf #3572).

**To Reproduce**
1. Open tweaks
2. Go to font tab
3. play around with scaling
4. see all other apps change font size except kitty

**Expected behavior**
I expect kitty to respect scaling like other apps.

**Screenshots**

https://user-images.githubusercontent.com/2681677/117165030-6fc0c900-adc5-11eb-9365-e054c119edbd.mp4

**Environment details**
OS: Fedora 33, gnome 3.38

```
kitty 0.20.1 created by Kovid Goyal
Linux fedora-kwak 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64
\S
Kernel \r on an \m (\l)
Loaded config files: /home/bendem/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background           Color(red=17, green=17, blue=17)
enable_audio_bell    False
font_family          Fira Code Retina
font_size            16.0
tab_bar_style        powerline
visual_bell_duration 1.0
```

**Comment by kovidgoyal** [comment]
Ah, I have no clue what the scaling factor in GNOME is. What kitty respects is the Wayland scale factor. I dont know if GNOME allows you to adjust that, but if it does, then you can adjust it and see kitty respond. I have no clue what "scaling factor" the scaling in gnome tweaks refers too, but it defintely isnt the Wayland DPI scaling.

**Comment by kovidgoyal** [comment]
See https://wiki.archlinux.org/title/HiDPI#GTK+_vs_Gnome_Shell_elements_on_Xorg

**Comment by kovidgoyal** [comment]
And for reference here is how you change the actual wayland scaling factor:

```sh
gsettings set org.gnome.desktop.interface scaling-factor 2
```

**Comment by bendem** [comment]
Didn't realise it was a different thing, I just tried changing wayland's scaling factor, but all the UI elements become way too big (window decorations are much larger than when tweaking the font scaling factor). I've changed the platform font size and set the same size in kitty.conf. It's really too bad there isn't one central place to set this up.

Thank you for your time.
