### ISSUE TITLE
Turning off keyboard protocol in configuration file

### ISSUE THREAD

**Issue by vp1981** [kovidgoyal/kitty#3582]
**Is your feature request related to a problem? Please describe.**
With new keyboard protocol feature turned on by default many simple terminal program aren't work correctly with many "special" keyboard combination. For instance, if one configured super+space for keyboard layout change (in X world) and try to switch to other layout in simple shell (bash) then not only the layout changed but also spurious characters typeset in command line. This is worst if one run vim (imagine git commit in terminal) and try to switch layout.

**Describe the solution you'd like**
It would be nice to either have that feature (keyboard protocol) switched off by default and enabled if one desires it or have a configuration option to switch it off.

**Describe alternatives you've considered**
Use another terminal emulator.

**Comment by kovidgoyal** [comment]
Update to 0.20.3 where super+space is recognized as a layout change key
and ignored.
