### ISSUE TITLE
Backspace on superuser behaves seemingly incorrectly

### ISSUE THREAD

**Issue by DISN-kolo** [kovidgoyal/kitty#3583]
When I go `sudo bash` and try to erase anything I typed in the shell using the backspace key, my cursor moves right (looks like a single space is inserted) and the character doesn't appear to be deleted. That being said, if I ignore what is shown and instead just assume that deletion of characters works like it should I am able to enter commands like normal.

For example,
`$ sudo bash`
`# catt`
A mistake! I should erase it by pressing the backspace key:
`# catt ` (the real stuff written should be `# cat`)
Okay, now type the file that I need to cat..
`# catt  file2cat` (there should be a double space but markdown refuses to show it; that's from using backspace key + the space between the command and the argument)
Aaaand it works just like `# cat file2cat`!

This error does not happen when not in superuser or after exiting the sudo shell.
![error4github_kitty](https://user-images.githubusercontent.com/82868527/117273496-dc3ed500-ae64-11eb-8211-50869db77278.png)

**Environment details**
Ubuntu 20.04.2 LTS x86_64
Linux 5.8.0-50-generic

**kitty --debug-config**

```
kitty 0.20.3 (c891432c9d) created by Kovid Goyal
Linux pcnamehidden4privatereason 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/dfm/.config/kitty/kitty.conf
[126 12:17:42.516221] Ignoring invalid config line: selection_foreground
Running under: X11

Config options different from defaults:
background                 Color(red=253, green=246, blue=227)
color0                     Color(red=7, green=54, blue=66)
color1                     Color(red=220, green=50, blue=47)
color10                    Color(red=88, green=182, blue=117)
color11                    Color(red=181, green=181, blue=131)
color12                    Color(red=131, green=148, blue=210)
color13                    Color(red=108, green=113, blue=196)
color14                    Color(red=147, green=177, blue=161)
color15                    Color(red=253, green=249, blue=239)
color2                     Color(red=133, green=153, blue=0)
color3                     Color(red=181, green=137, blue=0)
color4                     Color(red=38, green=139, blue=210)
color5                     Color(red=211, green=54, blue=130)
color6                     Color(red=42, green=161, blue=152)
color7                     Color(red=238, green=232, blue=213)
color8                     Color(red=0, green=43, blue=54)
color9                     Color(red=203, green=75, blue=22)
copy_on_select             clipboard
cursor                     Color(red=63, green=63, blue=63)
cursor_text_color          None
font_family                Ubuntu Mono
font_size                  14.0
foreground                 Color(red=101, green=123, blue=131)
scrollback_lines           8000
select_by_word_characters  :@-./_~?&=%+#
selection_background       Color(red=255, green=255, blue=170)
single_window_margin_width FloatEdges(left=-1000.0, top=-1000.0, right=-1000.0, bottom=-1000.0)
url_color                  Color(red=255, green=255, blue=255)
url_style                  1
window_border_width        (1.0, 'pt')
```

**Additional context**
This happens with `kitty --config NONE`, too.
This does not happen in xterm or GNOME terminal.
Also, I've noticed that my colours in the superuser are gone. This is strange, since in xterm or GNOME terminal I have them (due to .bashrc).

**Comment by trygveaa** [comment]
I'm guessing this is caused by kittys terminfo only being installed for your user, and not system-wide or for the root user.

**Comment by Luflosi** [comment]
Also see https://sw.kovidgoyal.net/kitty/faq.html#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo. Installing the `kitty-terminfo` package with your package manager might be all that is required.

**Comment by DISN-kolo** [comment]
thanks!

**Comment by scarlehoff** [comment]
Is there a way of getting this behavior on the ssh kitten "somehow"? If I ssh-in to some remote computer and then become superuser there, if I don't have `kitty-terminfo` installed in that computer I get this problem.

Of course I can just install it (I can by definition if I am seeing this problem) but I wonder whether the ssh kitten could be made to do something about it?

**Comment by kovidgoyal** [comment]
On Sat, May 08, 2021 at 12:51:30AM -0700, Juan M. Cruz-Martinez wrote:
> Is there a way of getting this behavior on the ssh kitten "somehow"? If I ssh-in to some remote computer and then become superuser there, if I don't have `kitty-terminfo` installed in that computer I get this problem.
> 
> Of course I can just install it (I can by definition if I am seeing this problem) but I wonder whether the ssh kitten could be made to do something about it?

Like what?

**Comment by scarlehoff** [comment]
I don't know, if I had an idea already I would've suggested it. I'm just wondering whether it would be possible _at all_

**Comment by kovidgoyal** [comment]
On Sat, May 08, 2021 at 12:57:53AM -0700, Juan M. Cruz-Martinez wrote:
> I don't know, if I had an idea already I would've suggested it. I'm just wondering whether it would be possible _at all_

Not as far as I know. it runs as the logged in user, who does not have
permission to change the files system wide or for other users. And
sudo/su dont pass throught the TERMINFO env var by default. So that
leaves, nothing to be done.
