### ISSUE TITLE
triple click - select from mouse pointer to end of the line

### ISSUE THREAD

**Issue by theguly** [kovidgoyal/kitty#3585]
I recently found this killer settings (based on my workflow of course) in Konsole:
![2021-05-06_16-29](https://user-images.githubusercontent.com/1745802/117316047-8845e780-ae88-11eb-9307-edf5df9f5a00.png)

the behaviour is:
- double click on a word to select it, like almost every other terminal emulator
- triple click to select current word and expand the selection to the end of the line

i found this very useful when selecting just a part of the line, or one line of code (automatically skipping vim line number for example) and also to copy shell commands because i can easily skip $PS1

do you think it's a feature you can sooner or later?

**Comment by kovidgoyal** [comment]
If and when I get around to creating a general framework for mapping mouse events to actions, it will be pretty easy to create an action for doing this which you can then map to the triple click or whatever else you like. I dont however want a separate option for this.

**Comment by salmankhilji** [comment]
I have the latest kitty from `master` branch @ `c6c203da`, and this feature does not work.

**Comment by kovidgoyal** [comment]
You need to press ctrl+alt as well. the default triple click still selects the full line.

**Comment by salmankhilji** [comment]
> You need to press ctrl+alt as well. the default triple click still selects the full line.

My bad.  I have been holding `CTRL+SHIFT` in so many other places that my eyes misread the `CTRL+ALT` as `CTRL+SHIFT`.
