### ISSUE TITLE
Wrong ESC-sequences for F-keys F1-F4

### ISSUE THREAD

**Issue by dimitrik-fr** [kovidgoyal/kitty#3586]
**Describe the bug**
Both `xtrerm-ketty`and `xterm-256color` terminfo are having F1-F4 keys as :
* F1: kf1=\EOP 
* F2: kf2=\EOQ
* F3: kf3=\EOR
* F4: kf4=\EOS

while kitty is returning on these keys pressing the following : 
* F1 : \EP
* F2 : \EQ
* F3 : \ER
* F4 : \ES

e.g. there was somewhere missed "O" in output sequences..
and, curiously, this is happening only with F1-F4 keys, any other F-keys are working just fine.

**To Reproduce**

you can observe the problem with any Terminal app which is able to report pressed keys, and for me the most simple is to use "micro" for this : 
1. start "micro" in kitty
2. type Ctrl-e
3. type `raw` in command line
4. now type any F-key and observe the received ESC-sequence 
5. check F1-F4 keys, etc.
6. type Ctrl-q to leave "raw" mode
7. type Ctrl-q to leave "micro"

**Expected behavior**
the expected behavior is to see the sequences matching terminfo.

**Environment details**
OS: OSX Catalina (but I don't think OS plays any role here)

**Comment by kovidgoyal** [comment]
I cannot replicate this with kitty 0.20.3, running:

kitty kitty +kitten show_key -m application

and pressing F1 correctly displays

^[OP

as expected.

**Comment by kovidgoyal** [comment]
Oh and just for completeness, same without using the showkey kitten
```
printf '\x1b[?1h'; cat -v
```

also prints ^[OP as expected for F1

**Comment by dimitrik-fr** [comment]
Hmm.. -- seems like you're right (and probably there are some issues in "micro" then)..

also, to have "third party" test check, I've also tried "vi", and it was printing <F2><F3><F4> when F2, F3, F4 are pressed, so I'll open a bug report for "micro", let's see..

thank you for prompt support !

Rgds, -Dimitri

**Comment by trygveaa** [comment]
If you don't set the terminal in Application Cursor Keys mode (don't print `\x1b[?1h`), kitty will send `^[[P` instead of `^[OP` and so on, so I assume micro doesn't set it in this mode.

@kovidgoyal: Why does Application Cursor Keys mode change the function keys, not just the arrow keys in kitty? E.g. xterm sends `^[OP` for F1 regardless of this mode.

**Comment by kovidgoyal** [comment]
Ah, that is indeed a regression, although note that cursor key mode
affects the cursor keys, home, end and the KP_BEGIN key. Just not F1-F4 :)

**Comment by trygveaa** [comment]
> note that cursor key mode affects the cursor keys, home, end and the KP_BEGIN key

Right, "just the arrow keys" wasn't completely accurate.
