### ISSUE TITLE
Remote file kitten fails silently on a remote Ubuntu host

### ISSUE THREAD

**Issue by sheriferson** [kovidgoyal/kitty#3589]
**Describe the bug**

ssh-ing to a remote Ubuntu host, I run `ls --hyperlink=auto`, and try to <kbd>Shift + Ctrl +</kbd> click the filename, the cursor changes to the pointing index finger indicating a link, but nothing happens.

I tried running `kitty` from another shell to see if any error messages pop up, but I saw nothing.

**To Reproduce**
1. `ssh <host IP>` (I have password-less ssh set up with host and IdentityFile set up in `~/.ssh/config`)
2. I tried this in both `bash` and `fish` shells on the remote host.
3. `ls --hyperlink=auto`
4. Click on filename
5. Nothing happens

**Expected behavior**

The behavior described [here](https://sw.kovidgoyal.net/kitty/kittens/remote_file.html). I _have_ been able to get this to work in other situations involving a different Mac computer ssh-ing to a different host.

**Environment details**

- Mac OS Big Sur 11.3.1
- Remote host: Ubuntu 20.04.2
- `ls -version` on remote host: ls (GNU coreutils) 8.30
- I build `kitty` locally on a Mac running 11.3.1. I run Python 3.9 installed using Homebrew. 

```
echo $EDITOR                                                                                                                                                                                         
vim
```

```
kitty 0.20.3 (dd0130180b) created by Kovid Goyal
Darwin Unknown.domain 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.3.1 BuildVersion:	20E241
Loaded config files: /Users/sherif/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color        Color(red=0, green=95, blue=135)
active_tab_font_style      (False, False)
active_tab_title_template  {fmt.fg.purple}{index} {fmt.fg.black}{title}
background                 Color(red=238, green=238, blue=238)
color0                     Color(red=255, green=255, blue=255)
color1                     Color(red=203, green=39, blue=53)
color10                    Color(red=5, green=151, blue=125)
color11                    Color(red=254, green=195, blue=29)
color12                    Color(red=0, green=125, blue=188)
color13                    Color(red=224, green=92, blue=132)
color14                    Color(red=5, green=151, blue=125)
color15                    Color(red=61, green=71, blue=82)
color2                     Color(red=121, green=182, blue=63)
color3                     Color(red=254, green=195, blue=29)
color4                     Color(red=0, green=125, blue=188)
color5                     Color(red=224, green=92, blue=132)
color6                     Color(red=5, green=151, blue=125)
color7                     Color(red=80, green=92, blue=106)
color8                     Color(red=230, green=230, blue=230)
color9                     Color(red=242, green=140, blue=0)
cursor_beam_thickness      2.0
cursor_shape               2
draw_minimal_borders       False
font_family                PragmataPro Mono Liga
font_size                  13.0
foreground                 Color(red=80, green=92, blue=106)
inactive_tab_background    Color(red=0, green=95, blue=135)
inactive_tab_foreground    Color(red=211, green=211, blue=211)
macos_custom_beam_cursor   True
macos_option_as_alt        3
macos_show_window_title_in none
macos_titlebar_color       1
scrollback_lines           20000
tab_bar_background         Color(red=0, green=95, blue=135)
tab_bar_min_tabs           1
tab_bar_style              powerline
tab_title_template         {index} {title}
url_prefixes               ('http', 'https', 'file', 'ftp')
url_style                  2
window_border_width        (1.0, 'pt')
window_padding_width       FloatEdges(left=4.0, top=4.0, right=4.0, bottom=4.0)
Added shortcuts:
	 f11 KeyAction(func='create_marker', args=())
	 f12 KeyAction(func='remove_marker', args=())
	 ctrl+h KeyAction(func='previous_window', args=())
	 ctrl+l KeyAction(func='next_window', args=())
	 shift+ctrl+y KeyAction(func='new_window', args=['@ansi', 'less', '+G', '-R'])
	 shift+cmd+l KeyAction(func='set_tab_title', args=())
Changed shortcuts:
	 cmd+- KeyAction(func='change_font_size', args=(True, '-', 1.0))
	 cmd+= KeyAction(func='change_font_size', args=(True, '+', 1.0))
```

**Additional context**

I can reproduce the problem using `kitty --config NONE`

How can I help debug what is failing here?

**Comment by kovidgoyal** [comment]
Works fine for me on a linux host, though not Ubuntu, I dont have any
ubuntu machines currently. Look in window.py at the open_url function to
debug further.

**Comment by sheriferson** [comment]
I tried logging out `remote_hostname` [right here](https://github.com/kovidgoyal/kitty/blob/62656b24eb8a0e25610e2c37db9aa518098136f3/kitty/window.py#L550) and it's `localhost`. I assume it's supposed to be the IP address of the host instead. I tried hardcoding it to the correct IP and I got presented with the prompt described in the doc page.

Any tips on what might be causing getting remote hostname to fail? I'm not using nested ssh sessions fwiw.

**Comment by kovidgoyal** [comment]
The hostname is set by the utility generating the hyperlinks, in this
case ls. It in turn probably uses gethostname(). So configure the
hostname correctly on the remote server and you will be fine.

**Comment by sheriferson** [comment]
Thanks for the tip. Configuring the hostname to be the IP address does solve it, although I get this interesting prompt from kitty:

```
The remote hostname Agent pid 30583
xx.xx.xx.xx does not match the
hostname in the hyperlink xx.xx.xx.xx
This indicates that kitty has not connected to the correct remote machine.
This can happen, for example, when using nested SSH sessions.
The hostname kitty used to connect was: xx.xx.xx.xx

Do you want to continue anyway?
Yes	No
```

All occurrences of `xx.xx.xx.xx` above are the same exact IP address.

**Comment by sheriferson** [comment]
In my fish `config.fish` file I was running `ssh-agent` which was printing `Agent pid 30583` on login, and I think that's the reason for the weird prompt. Once I redirected that output to `/dev/null` the prompt from kitty went away.
It might be a bug to fix since the IP addresses were not actually different. Thanks for your help.

**Comment by kovidgoyal** [comment]
Well if you print random stuff on login, then there is no way for kitty to know what that random stuff is and strip it out. Although since the command being run is `ssh xxx hostname -f`  I dont know why ssh would be executing your login shell at all.

**Comment by kovidgoyal** [comment]
This might help: https://github.com/kovidgoyal/kitty/commit/f110a01ffe761ba99f4f862cf73939b2cf426c76
