### ISSUE TITLE
iBeam cursor difficult to see on dark backgrounds

### ISSUE THREAD

**Issue by acheronfail** [kovidgoyal/kitty#359]
When using kitty with a dark background on macOS, it's difficult to see where the cursor is since it is also dark - I find myself struggling to find the cursor and waving it around like mad until I find it.

This is what I mean:
<img width="200" alt="screen shot 2018-03-06 at 6 22 47 pm" src="https://user-images.githubusercontent.com/34289614/37019212-92494acc-216b-11e8-8615-329b1590fcb3.png">

The native Terminal app and iTerm2 both solve this by using a different image for the cursor ([you can find iTerm2's cursor here](https://github.com/gnachman/iTerm2/blob/master/images/IBarCursor%402x.png)).

I think that it would be nice if we had a hybrid dark/light cursor like iTerm2's, or at least a cursor that is easier to see with light/dark backgrounds. I'd also be interested in making the PR myself if you could point me in the right direction. 😄

**Comment by kovidgoyal** [comment]
Doesn't Apple allow you to change your mouse theme? It should not be the job of every application to provide its own mouse cursor. Personally, I like to use white mouse cursors with a black outline and a slight black shadow. Works well on all background colors, like this: http://www.rw-designer.com/cursor-set/opensuse-oxygen

**Comment by acheronfail** [comment]
Unfortunately I believe Apple restricts changing the mouse themes. It used to be possible in versions of macOS < 10.10, but since SIP they've cracked down a lot more on System restrictions.

I also prefer white cursors - and while I agree that it shouldn't be the job of every application to provide its own mouse cursor, that doesn't make me like the situation Apple places us in since we can't change the mouse theme.

**Comment by kovidgoyal** [comment]
Wow, that's bad. Well OK, I suppose we have to workaround Apple's control freakyness. If you do want to implement a custom cursor in kitty, the relevant place would be in kitty/glfw.c see set_mouse_cursor()
 (googling should tell you what API to use for glfw custom cursors). 

Note that kitty uses three different cursor types (ibeam, hand, arrow). IMO, the way this should work is:

1) Allow user to define a mouse cursor theme in the config directory so they can customize the cursor images to whatever they want. I have the opposite philosophy to Apple :) 

2) On macOS only use special cursor images shipped with kitty by default.

**Comment by acheronfail** [comment]
Okay, I'll give that a crack when I get the chance. 😄

**Comment by kovidgoyal** [comment]
I didn't bother with making it configurable, I leave that as an exercise for whoever is interested.

**Comment by dylan-chong** [comment]
Is anyone else having the issue where they cannot see the beam cursor added in commit 4313531? I am using the latest kitty 0.12.1

**Comment by kovidgoyal** [comment]
The custom cursor was disabled, because it caused the mouse cursor to become invisible on dual GPU machines.

**Comment by gibfahn** [comment]
Is it possible to just not use the I-beam at all on macOS? I find the normal cursor pretty easy to see (especially if you increase the cursor size in the System Preferences -> Accessibility -> Display -> Cursor Size).

<img width="675" alt="image" src="https://user-images.githubusercontent.com/15943089/45292846-5bca4980-b4ee-11e8-95ad-c99a21c71232.png">

**Comment by kovidgoyal** [comment]
Not out of the box, someone would have to create a config option to select the default mouse cursor shape from the list of standard shapes.
