### ISSUE TITLE
Fallback fonts

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#3591]
**Is your feature request related to a problem? Please describe.**
Sometimes the font you prefer doesn't quite cover all the characters you commonly encounter.

**Describe the solution you'd like**
Other applications seem to fall back to whichever is the next font to contain a missing glyph. It seems like kitty may not (yet?), hence the feature request.

Is this inherent to kitty's handling of fonts or is there an issue like both fonts would need to be the exact same width or something? Any ways I can troubleshoot why it's not working in my particular case? (It involves emoji so I don't 100% expect it to work but kitty doesn't seem to have a problem with emoji, just the ones missing from my default emoji font.)

**Comment by kovidgoyal** [comment]
kitty implements font fallback. If a glyph is missing in a
font, kitty will query the system to find an alternate font for it. In
addition, if you dont like the default font kitty finds, you can specify
you own via symbol_map in kitty.conf.

https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.symbol_map


Finally, you can check what fallbacks kitty is using with
--debug-font-fallback

**Comment by toonn** [comment]
Thanks. My system seems to select the wrong font. Kitty reports the font doesn't actually contain the glyph. So you're saying it's not kitty's but the system's responsibility to suggest the proper font?

**Comment by kovidgoyal** [comment]
Yeah, every application is not supposed to scan every font file on its
own to determine which one has which glyphs. They system is supposed to
maintain a cache of that information, which all applications are
supposed to use.

**Comment by toonn** [comment]
But why does the system propose the correct font to other applications. Just not kitty?

**Comment by kovidgoyal** [comment]
No clue, it would help if you gave some more details about what the
problem is you are having exactly.

**Comment by kovidgoyal** [comment]
Aah, you are on macOS. On macOS kitty hardcodes AppleColorEmoji for
emoji since that is the standard font. I suppose I can add a check to
see if it has the emoji and use a fallback if not.

**Comment by vpeopleonatank** [comment]
> kitty implements font fallback. If a glyph is missing in a
> font, kitty will query the system to find an alternate font for it. In
> addition, if you dont like the default font kitty finds, you can specify
> you own via symbol_map in kitty.conf.
> 
> https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.symbol_map
> 
> Finally, you can check what fallbacks kitty is using with
> --debug-font-fallback

Can I specify what font fallback kitty use? Because my main font in config is JetBrainMono, It doesn't have some glyps (from patched nerd fonts), sometimes system correctly "choose" my installed Dejavu Nerd font, then it show icon correctly but now system doesn't choose right font (currently check `--debug-font-fallback` It show JetBrainMono)

**Comment by pinpox** [comment]
> Can I specify what font fallback kitty use?

Same issue here. I use an unpatched font and would like to specify the fallback font which will be used for things like emoji or symbols.

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map.
