### ISSUE TITLE
kitty windows sometimes turn black after resume

### ISSUE THREAD

**Issue by sersorrel** [kovidgoyal/kitty#3598]
**Describe the bug**
On resume, some kitty windows turn completely black. Switching workspaces or windows to/from the offending kitty window, or clicking inside the window, fixes it.

**To Reproduce**
1. Open some kitty windows
2. Suspend
3. Resume
4. Hopefully at least one window turned black, otherwise try again

**Expected behavior**
kitty windows should retain their previous contents on resume, like other applications

**Screenshots**
![image](https://user-images.githubusercontent.com/9433472/117572163-861e9b80-b0c9-11eb-954b-f578583e3cd8.png)

**Environment details**
OS: Ubuntu 18.04

```
$ kitty --debug-config
kitty 0.20.3 (c891432c9d) created by Kovid Goyal
Linux what 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64
Ubuntu 18.04.5 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
Loaded config files: /home/ash/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
adjust_line_height    2
background            Color(red=249, green=245, blue=215)
close_on_child_death  True
color0                Color(red=251, green=241, blue=199)
color1                Color(red=204, green=36, blue=29)
color10               Color(red=121, green=116, blue=14)
color11               Color(red=181, green=118, blue=20)
color12               Color(red=7, green=102, blue=120)
color13               Color(red=143, green=63, blue=113)
color14               Color(red=66, green=123, blue=88)
color15               Color(red=60, green=56, blue=54)
color2                Color(red=152, green=151, blue=26)
color3                Color(red=215, green=153, blue=33)
color4                Color(red=69, green=133, blue=136)
color5                Color(red=177, green=98, blue=134)
color6                Color(red=104, green=157, blue=106)
color7                Color(red=124, green=111, blue=100)
color8                Color(red=146, green=131, blue=116)
color9                Color(red=157, green=0, blue=6)
command_on_bell       ['flock', '-n', '/usr/share/sounds/freedesktop/stereo/bell.oga', 'paplay', '/usr/share/sounds/freedesktop/stereo/bell.oga']
cursor                Color(red=60, green=56, blue=54)
cursor_beam_thickness 0.5
cursor_blink_interval 0.0
cursor_text_color     None
disable_ligatures     2
font_family           Iosevka
font_size             10.0
foreground            Color(red=60, green=56, blue=54)
mouse_hide_wait       -1.0
open_url_modifiers    4
scrollback_lines      10000
selection_background  Color(red=60, green=56, blue=54)
selection_foreground  Color(red=249, green=245, blue=215)
strip_trailing_spaces smart
window_padding_width  FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
Added shortcuts:
	shift+page_up KeyAction(func='scroll_page_up', args=())
	shift+page_down KeyAction(func='scroll_page_down', args=())
	shift+home KeyAction(func='scroll_home', args=())
	shift+end KeyAction(func='scroll_end', args=())
	shift+super+enter
```

**Additional context**
The problem is reproducible with `--config NONE`; I can also reproduce it without picom running.

**Comment by salmankhilji** [comment]
Sorry, unrelated to this topic: is it the kitty tab bar at the top?  How did u get this look?

**Comment by kovidgoyal** [comment]
This is almost certainly a driver problem. kitty has no knowledge of the system doing suspend/resume. It gets no events for it and runs no code in response to it. It's up to the system to restore application state when doing a restore. So I dont really see what I can do about this, sorry. I can tell you it doesnt happen on my system, with an Intel GPU with up-t-date drivers. I can suggest you try updating your gpu drivers, but given that ubuntu is not a rolling release distro that would require a full system upgrade, so...

**Comment by sersorrel** [comment]
fair enough – I was hoping that (since it only seems to happen with kitty) you might have some insight, but if it's just a driver bug then I guess there's not much you can do.

for posterity's sake, I'm currently using the proprietary nvidia drivers, version 460.73.

@salmankhilji: it's from [i3](https://i3wm.org/).
