### ISSUE TITLE
[linux] kitty.conf should get installed in /etc/

### ISSUE THREAD

**Issue by Arnaudv6** [kovidgoyal/kitty#360]
I installed kitty on gentoo. It rocks, thanks.
Tabs look apart, it is beautiful. Plus it is light, fast And depends not on vte!

I opened this bug on gentoo and was sent to upstream:
https://bugs.gentoo.org/649436

Basically, one would expect to find kitty.conf in /etc/.
Is there something you can do please?

**Comment by kovidgoyal** [comment]
I dont see why. kitty is not a system program/daemon. It uses XDG_CONFIG_HOME for its config files, as such, I dont think it is appropriate for it to look for a config file in /etc. No terminal emulator I know of puts config files in /etc. What is your actual use case?

**Comment by Arnaudv6** [comment]
Okay, I think I get your point:
Your kitty.conf file is not so much a system-wide config file than a example-config-file.

Granted. But my point stands: I am no unix guru, but I feel like its place is somewhere like
/usr/share/doc/
not where I actually find it:
/usr/lib64/kitty/kitty/kitty.conf

**Comment by kovidgoyal** [comment]
Well someday I might make a man page for kitty and at that point there can be a man page for kitty.conf as well, but that time is not now, kitty is changing too rapidly at the moment :) For the time being, the best place to look for the example kitty.conf is in the github repo.
