### ISSUE TITLE
open new tab as a session and lauch ssh to an oher server with a key binding

### ISSUE THREAD

**Issue by kristoferus75** [kovidgoyal/kitty#3601]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I like to open a new tab on already opened kitty with a key binding and lauch ssh to a other server -> currently i use a startup session config file with a new tab but i want to bind this new tab to key binding to open more tabs like this

```
new_tab firma
cd ~
launch ssh a.b.c.d
layout tall
```

like open more tabs with all launch ssh to an other server

**Describe alternatives you've considered**
i can bind a key binding on my wm to open kittty with --session x.conf
but than i open more instances of kitty and its not in same window

**Additional context**
no

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/launch.html

**Comment by jnmcfly** [comment]
The launch command don't solve this requirement. 

When using launch, there is no documented way to hand over a session file for a new tab/window.

**Comment by kovidgoyal** [comment]
A session file is just a collection of launch commands with a little bit of extra functionality which you can accomplish using remote control. So use combine to combine all these actions and map to a key press.
