### ISSUE TITLE
Nerd fonts rendered incorrectly

### ISSUE THREAD

**Issue by michaljanocko** [kovidgoyal/kitty#3608]
**Describe the bug**
Nerd fonts are being rendered too big compared to other terminals. Alacritty, st, wezterm work as expected.

**To Reproduce**
I used JetBrains Mono as the font and I have global Nerd Font packages for Arch Linux installed

**Expected behavior**
I expected the battery symbol (and others) to be rendered the same size as other characters.

**Screenshots**
Alacritty:
![image](https://user-images.githubusercontent.com/33790048/117907525-98046800-b29c-11eb-8f7f-4ee2b97bc3b9.png)
Kitty:
![image](https://user-images.githubusercontent.com/33790048/117907551-a0f53980-b29c-11eb-8229-adddab171195.png)

**Environment details**
Arch Linux

**Comment by kovidgoyal** [comment]
No, kitty use extra spaces after PUA glyphs that dont fit in one cell to render them properly. THis is by design. I suggest you get the other terminals you name to do it right as well. https://sw.kovidgoyal.net/kitty/faq.html#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by michaljanocko** [comment]
Can we actually get this as a config option? I personally don't care what any specification says—it just looks ugly.

**Comment by kovidgoyal** [comment]
Not something I care about. And there is a battery symbol in proper
unicode with proper width specifications already. Why are you using the
nerd font hackery for it anyway? https://www.compart.com/en/unicode/U+1F50B

**Comment by michaljanocko** [comment]
I am using Starship for my prompt and even though, I can easily replace it here, I use Nerd Fonts in Vim to show language icon next to files and for some visual flair.

**Comment by kovidgoyal** [comment]
So then if you want the battery or any other symbol to fit in one cell,
then get the NERD fonts maintainer to redraw that symbol with the
correct aspect ratio and size to fit in one cell. Or use a different
font for those symbols that looks like you prefer. See symbol_map in
kitty.conf. There's absolutely no reason for terminal emulators to
artificially limit all PUA characters to one cell only, because you
prefer them to be in one cell.

**Comment by jandamm** [comment]
I use the following config to make it look as I'd expect it (coming from Alacritty):
```
font_family JetBrains Mono
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B JetBrainsMono Nerd Font
```

Using just JetBrainsMono Nerd Font would result in a different appearance since there seem to be some broken/changed characters in the Nerd Fonts as well (e.g. ❯)
