### ISSUE TITLE
When output some special character into console cause hung on kitty.

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#3609]
**Describe the bug**

Following is two screenshot when i use redboxed ruby command to output some html content into konsole/kitty.

konsole works as expected, puts is just print the html content to console.

![image](https://user-images.githubusercontent.com/549126/117928783-9d11f780-b32e-11eb-8aff-18882133b13e.png)

but kitty will hang on there, and flush the REPL command output.

![image](https://user-images.githubusercontent.com/549126/117928640-69cf6880-b32e-11eb-9453-1e9d9e4c1f2a.png)

 i have to run Ctrl+C several times to quit it.

![image](https://user-images.githubusercontent.com/549126/117929140-042fac00-b32f-11eb-9981-ea50507fb2bb.png)

**To Reproduce**

I guess you can use any way to output the response of website https://myip.ipip.net/
to kitty to reproduce this issue.

**Expected behavior**
it should output the content to console as konsole did, at least, it should not hang on there

**Environment details**
arch linux

```
 ╰─ $ kitty --debug-config
kitty 0.20.3 created by Kovid Goyal
Linux lggram 5.12.1-arch1-1 #1 SMP PREEMPT Sun, 02 May 2021 12:43:58 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/zw963/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
enable_audio_bell     False
font_family           Inconsolata
font_size             13.5
linux_display_server  x11
open_url_modifiers    4
scrollback_lines      20000
tab_activity_symbol   ❓
tab_bar_edge          1
tab_bar_style         powerline
update_check_interval 24.0
url_prefixes          ('http', 'https', 'file', 'ftp')
Added shortcuts:
	alt+0 KeyAction(func='next_tab', args=())
	alt+1 KeyAction(func='first_window', args=())
	alt+2 KeyAction(func='second_window', args=())
	alt+3 KeyAction(func='third_window', args=())
	alt+4 KeyAction(func='fourth_window', args=())
	alt+5 KeyAction(func='fifth_window', args=())
	alt+6 KeyAction(func='sixth_window', args=())
	alt+7 KeyAction(func='seventh_window', args=())
	alt+8 KeyAction(func='eighth_window', args=())
	alt+9 KeyAction(func='previous_tab', args=())
	alt+n KeyAction(func='scroll_line_down', args=())
	alt+p KeyAction(func='scroll_line_up', args=())
	alt+v KeyAction(func='scroll_page_up', args=())
	alt+w KeyAction(func='copy_to_clipboard', args=())
	shift+alt+, KeyAction(func='scroll_home', args=())
	shift+alt+. KeyAction(func='scroll_end', args=())
	ctrl+- KeyAction(func='change_font_size', args=(True, '-', 2.0))
	ctrl+= KeyAction(func='change_font_size', args=(True, '+', 2.0))
	ctrl+v KeyAction(func='scroll_page_down', args=())
	ctrl+y KeyAction(func='paste_from_clipboard', args=())
	ctrl+enter KeyAction(func='new_window_with_cwd', args=())
	ctrl+f2 KeyAction(func='edit_config_file', args=())
	alt+ctrl+0 KeyAction(func='move_tab_forward', args=())
	alt+ctrl+9 KeyAction(func='move_tab_backward', args=())
	alt+ctrl+b KeyAction(func='move_window_backward', args=())
	alt+ctrl+f KeyAction(func='move_window_forward', args=())
Changed shortcuts:
	shift+ctrl+0 KeyAction(func='goto_layout', args=['tall'])
	shift+ctrl+9 KeyAction(func='goto_layout', args=['fat'])
	shift+ctrl+f KeyAction(func='show_scrollback', args=())
	shift+ctrl+k KeyAction(func='clear_terminal', args=['reset', True])

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You cannot output random binary data into terminals. That is not safe on
any terminal, ever. kitty has not hung, its simply waiting for some
incomplete escape code in your binary data to be be completed. Or
the data contained the flow control on/off escape code. In either case
just press ctrl+shift+delete to reset the terminal.

**Comment by zw963** [comment]
I guess it flush my terminal title too, and when i want to exit this terminal, it hung again.

![image](https://user-images.githubusercontent.com/549126/117931901-5920f180-b332-11eb-84ff-036deef16395.png)

> You cannot output random binary data into terminals. That is not safe on any terminal, 

I think this issue never happen on konsole anyway.
