### ISSUE TITLE
Window size info is remembered even after a window is closed

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#3613]
**Describe the bug**
kitty does not seem to properly clear the size of a window that has been deleted.

**To Reproduce**
1. Replace the contents of your `kitty.conf` file with:
    ```
    enabled_layouts tall
    map kitty_mod+\ combine : new_window : new_window : resize_window shorter 12
    ```
2. Start kitty like this: `kitty --start-as=fullscreen`
3. `CTRL+SHIFT+\`.
4. Observe the sizes of the 3 windows, especially that of the bottom-right one.
5. `CTRL+d` twice to close the right-most two windows.
6. `CTRL+SHIFT+\`.
7. Observe again.

**Expected behavior**
The sizes of windows in Step 7 shall be exactly the same as the one observed in Step 4.

**Observed behavior**
The bottom-right window is smaller the second (and each subsequent) time.

**Screenshots**
Step 4:
![Step4](https://user-images.githubusercontent.com/40219235/118010319-c5383100-b303-11eb-8d32-97a953da37de.png)

Step 7:
![Step7](https://user-images.githubusercontent.com/40219235/118010346-cbc6a880-b303-11eb-8291-8dae6f14394a.png)

**Environment details**
OS: Name and version of operating system(s)
Ubuntu 20.04 LTS

```
$ kitty --debug-config
kitty 0.20.3 (f64b4e0e56) created by Kovid Goyal
Linux byteevo-scm 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /home/precor/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
enabled_layouts ['tall']
Added shortcuts:
	shift+ctrl+\ KeyAction(func='combine', args=(KeyAction(func='new_window', args=()), KeyAction(func='new_window', args=()), KeyAction(func='resize_window', args=['shorter', 12])))
```

**Additional context**
kitty is compiled from source.  `master` branch @ `f64b4e0e`.

**Comment by kovidgoyal** [comment]
this is by design, sizes are not actually window sizes, but layout
sizes, and the common case is adjusting a layout to your liking and then
wanting it to remain that way.
