### ISSUE TITLE
Instructions of using broadcast are incomplete or wrong

### ISSUE THREAD

**Issue by jimsnab** [kovidgoyal/kitty#3614]
**Describe the bug**
Following the directions for `broadcast` leads to `No kitten named broadcast`. https://sw.kovidgoyal.net/kitty/kittens/broadcast.html

**To Reproduce**
1. Install `kitty`
2. `kitty +kitten broadcast ls`

**Expected behavior**
The command does something other than say there is no kitten named `broadcast`. The instructions for an `F1` key to broadcast to all windows should work.

**Environment details**
OS: Ubuntu 20.04

```
kitty 0.15.0 created by Kovid Goyal
Linux jims-salido-nuc 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/jims/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control  y
background            Color(red=0, green=43, blue=54)
font_size             9.0
foreground            Color(red=219, green=219, blue=219)
update_check_interval 0.0
Added shortcuts:
	f1 KeyAction(func='launch', args=['--allow-remote-control', 'kitty', '+kitten', 'broadcast'])
```

**Comment by SolitudeSF** [comment]
your kitty version is too old

**Comment by jimsnab** [comment]
Installation instructions say `You can also use your favorite package manager to install the kitty package.`

That installs 0.15.0 with Ubuntu 20.04.

Since that's not up to date, instructions should be clarified.

**Comment by kovidgoyal** [comment]
I'm afraid I am not going to annotate every piece of documentation in
kitty with what version it was released in.

**Comment by jimsnab** [comment]
Consider fixing the installation instructions to mention the package manager might have a quite old version.

**Comment by SolitudeSF** [comment]
that should be obvious if you're using ubuntu

**Comment by jimsnab** [comment]
Maybe but most packages are kept up to date.

**Comment by kovidgoyal** [comment]
Most certainly not. Ubuntu packages are almost always woefully out of date. for all software that it packages They consider using old/broken/insecure (rebranded as stable) software a feature. In any case have added a sentence warning that some Linux distros have woefully outdated packages.

**Comment by jimsnab** [comment]
Then package manager really shouldn't be recommended by kitty instructions.

Good chat.

**Comment by kovidgoyal** [comment]
On Thu, May 13, 2021 at 05:36:56AM -0700, jimsnab wrote:
> Then package manager really shouldn't be recommended by kitty instructions.

Why on earth would I penalize every Linux distribution's users because
there are some that have outdated packages? Not to mention non Linux
package repositories that are typically much more up-to-date than
Debian/Ubuntu.

> 
> Good chat.

Indeed, the best I've had in a loooong time.
