### ISSUE TITLE
Petition to change the official logo to this one

### ISSUE THREAD

**Issue by kdav5758** [kovidgoyal/kitty#3618]
Granted, this is not a real feature for the terminal it self. I just wanted to know if it would be possible to change the official logo to this one:
<p align="center">
    <img
        width="360"
        src="https://i.imgur.com/p50OLZg.png"
        alt="Logo"
    />
</p>

This was [originally posted](https://www.reddit.com/r/KittyTerminal/comments/nb3ubm/just_for_fun_an_alternative_kitty_icon_to_spice/) in r/KittyTerminal. Oh and also, this the the repo of the author: https://github.com/DinkDonk/kitty-icon

**Comment by kovidgoyal** [comment]
dup of #3310

**Comment by kdav5758** [comment]
But it's not the same icon?

**Comment by kovidgoyal** [comment]
yes, but my reason for not changing the icon remains the same.

**Comment by kutsan** [comment]
@kovidgoyal You should really reconsider changing the logo. I understand the emotional aspect of it but still...

Or maybe adding an option to changing the current logo to alternative ones such as this one to make community and yourself happy?

**Comment by page-down** [comment]
> ... to changing the current logo to alternative ones ...

This has been listed in the official FAQ, with detailed steps to do it.

https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon

You can't change it with options under macOS, you need to compile, package, and sign your own app.

On Linux, just replace the logo png image.

**Comment by Luflosi** [comment]
Well, if you have the logo in the .icns format, you can select the kitty app in Finder, press <kbd>⌘</kbd>+<kbd>i</kbd> and drag&drop the logo over the old logo at the top, no need to recompile anything.
The tricky part is to convert the logo into the .icns format. The easiest is probably to clone the kitty repo, replace `logo/kitty.svg` and `logo/kitty-framed.svg` with your own versions, then execute `logo/make.py` and finally `iconutil -c icns logo/kitty.iconset -o logo/kitty.icns`.
