### ISSUE TITLE
Dynamically resize layout panes

### ISSUE THREAD

**Issue by ashiklom** [kovidgoyal/kitty#362]
Is it possible to dynamically resize the width of multiple open window panes (analogously to tmux's `resize-pane` command)? It would be nice to have the flexibility to resize panes after they have been opened. Perhaps something like:

```
# Set pane width/height in columns/rows
kitty @ set-pane-width 35
kitty @ set-pane-height 17

# Increase/decrease pane width/height in columns/rows
kitty @ pane-width-increase 5
kitty @ pane-height-decrease 10

# Create new window with specified width/height
kitty @ new-window --width 30
kitty @ new-window --height 20
```

My understanding is that currently, the only way to achieve this is to create a new layout. If I'm mistaken, sorry! I searched through the past issues and the documentation and couldn't find any mention to a feature like this.

Otherwise, _huge_ fan of this project! Kitty became my favorite terminal emulator within about 30 seconds of opening it for the first time.

**Comment by kovidgoyal** [comment]
Not something I am particularly interested in, but patches are welcome. You'd basically need to create a new layout that allowed for custom window sizes (in layout.py), then add some code to remote_control.py to control the custom layout.

**Comment by metalelf0** [comment]
Would love this too. Right now, tmux being able to resize panes is the biggest thing keeping me from switching to kitty multiplexing ability. I'm used to 70/30 like split ratio, so I can have a big window for the editor and a smaller one for tests. Would love to see this implemented, python ain't my main language but I might take a look into this someday.

**Comment by kovidgoyal** [comment]
If all you want is a 70/30 split ratio, you dont need to implement dynamic sizing for that, just modify the Tall layout to use that ratio instead of 50/50 along the horizontal axis. You can make it a config option.

**Comment by kovidgoyal** [comment]
@metalelf0 FYI I just pushed code to enable customization of the Tall layout so that you can specify how the width is split.

**Comment by metalelf0** [comment]
Thanks! I'll check it out ASAP :)

**Comment by kovidgoyal** [comment]
Never mind, I decided to implement this myself after all.

**Comment by metalelf0** [comment]
Thanks a lot! :) Now I'll switch to kitty for the terminal multiplexing part. :) Great work!

**Comment by ManyEyedFox** [comment]
@kovidgoyal so you implemented the resizing of windows? I don't see this anyone in the current documentation

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/#layouts
