### ISSUE TITLE
Backspace with ssh bash shell

### ISSUE THREAD

**Issue by lioaslan** [kovidgoyal/kitty#3621]
**Describe the bug**
I used kitty to ssh to an Amazon Linux 2 machine. However, I can't use backspace for editing commands. In particular, when I type some commands and press backspace, it only shows space instead of deleting the last character, although the shell still recognizes the command deleted character. 
Sorry for the poor English but you can look at the screenshot to understand what they were.

**Config**
```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
```

**To Reproduce**
1. SSH to an Amazon Linux 2
2. Type `abcdefgh`
3. Press backspace
4. `abcdefgh ` (with space)

**Expected behavior**
Delete the last character

**Screenshots**
![simplescreenrecorder-2021-05-14_10 15 04](https://user-images.githubusercontent.com/24852182/118216368-9229a500-b49d-11eb-9037-2a06323c9902.gif)

**Environment details**
OS: Amazon Linux 2

```
kitty 0.15.0 created by Kovid Goyal
Linux KhaiTran 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
Linux Mint 20 Ulyana \n \l
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/leo/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
font_size             12.0
update_check_interval 0.0
Added shortcuts:
	f5 KeyAction(func='launch', args=['--location=hsplit'])
	f6 KeyAction(func='launch', args=['--location=vsplit'])
	shift+right KeyAction(func='move_window', args=['right'])
	shift+left KeyAction(func='move_window', args=['left'])
	shift+down KeyAction(func='move_window', args=['bottom'])
	shift+up KeyAction(func='move_window', args=['top'])
	control+right KeyAction(func='neighboring_window', args=['right'])
	control+left KeyAction(func='neighboring_window', args=['left'])
	control+down KeyAction(func='neighboring_window', args=['bottom'])
	control+up KeyAction(func='neighboring_window', args=['top'])
	alt+1 KeyAction(func='goto_tab', args=(1,))
	alt+2 KeyAction(func='goto_tab', args=(2,))
	alt+3 KeyAction(func='goto_tab', args=(3,))
	alt+4 KeyAction(func='goto_tab', args=(4,))
	alt+5 KeyAction(func='goto_tab', args=(5,))
	alt+6 KeyAction(func='goto_tab', args=(6,))
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by greenmang0** [comment]
With `kitten ssh myserver` the `$TERM` on `myserver` was correctly being set as `xterm-kitty`, but I was still seeing this same issue. 

I installed `xterm-kitty` package on the server and it fixed the problem.
