### ISSUE TITLE
Wondering if the curly underline thickness can be adjusted?

### ISSUE THREAD

**Issue by npearson72** [kovidgoyal/kitty#3622]
Here's what it looks like for me:

<img width="541" alt="Screen Shot 2021-05-14 at 6 37 34 PM" src="https://user-images.githubusercontent.com/1323414/118294685-a7292700-b4e3-11eb-99f3-4b25c91828bc.png">

It's visible but really light. Would be great if there was a config option for this or at least a slight bump in thickness.

**Comment by kovidgoyal** [comment]
Looks fine to me, thicker wavy underlines look pretty bad to my eyes.
That said a PR for adding such an option is welcome.
