### ISSUE TITLE
kitty +kitten ssh skips welcome banner

### ISSUE THREAD

**Issue by boizoe** [kovidgoyal/kitty#3623]
When I set alias ssh='kitty +kitten ssh' remote login with ssh skips welcome banner.

**To Reproduce**
1. Have remote machine with welcome banner enabled.
2. Login to that machine with 'kitty +kitten ssh user@host'.
3. Login successful, but no banner.

**Expected behavior**
Banner printed before after the login

**Screenshots**
Plaintext output:
boizoe@t460s:~$ kitty +kitten ssh root@172.17.0.2
root@f9d6013be946:~# logout
Connection to 172.17.0.2 closed.
boizoe@t460s:~$
boizoe@t460s:~$
boizoe@t460s:~$ ssh root@172.17.0.2
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.10.0-6-amd64 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.
Last login: Fri May 14 19:51:31 2021 from 172.17.0.1
root@f9d6013be946:~# logout
Connection to 172.17.0.2 closed.

**Environment details**
OS: Machines with kitty - Debian(kitty from apt) and macOS (kitty from brew)

```
Output of kitty --debug-config:
kitty 0.19.3 created by Kovid Goyal
Linux t460s 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64
Debian GNU/Linux bullseye/sid \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/boizoe/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
enabled_layouts       ['grid', 'fat', 'tall', 'horizontal', 'splits', 'stack', 'vertical']
font_family           Fira Code
font_size             13.0
linux_display_server  wayland
scrollback_lines      9999
tab_activity_symbol   
update_check_interval 0.0

```

**Additional context**
'kitty --config NONE' produces same output - no banner with +kitten

**Comment by kovidgoyal** [comment]
I know of no way to do that.

**Comment by kovidgoyal** [comment]
IIRC on Ubuntu you can see it via cat /etc/motd if you really want to. However the ssh kitten is not ubuntu specific and in general the motd can come from many different places.

**Comment by boizoe** [comment]
yes, it's possible to get it via `cat /etc/motd`. But my issue was why does kitty suppresses it, because I expect `alias kitty='kitty +kitten ssh'` behave exactly the same was as plain `ssh`

**Comment by kovidgoyal** [comment]
The ssh kitten is not magic. It has to work with the limitations of SSH.
Read the source code if you wish to understand why.
