### ISSUE TITLE
Optionally include cursor in `get-text --ansi` 

### ISSUE THREAD

**Issue by copy** [kovidgoyal/kitty#3625]
**Is your feature request related to a problem? Please describe.**

I'm working on a tool to display local terminal contents on a website (like [gotty](https://github.com/yudai/gotty), but more secure and optionally broadcasted through a server) by polling `get-text --ansi`. Here's a work in progress: https://copy.sh/stream-tty/. It works extremely well. The only missing bit is the cursor.

**Describe the solution you'd like**

I'd like for `get-text` to include the cursor styling via ansi codes. I don't care if it's enabled by default or if there is a new flag, but other users of `get-text` might have an opinion.

**Describe alternatives you've considered**

I've tested an alternative approach of a `get-cursor` api command. The main issue is latency: Every api call through the socket takes 70ms on my machine.  Thus making two api calls (`get-text` and `get-cursor`) doubles the latency.  Furthermore kitty already knows how to style the cursor and knows about line wrapping.

One downside of this approach is that not all cursor styles are renderable using ansi codes (e.g. blinking or the unfocused cursor shape). That's not an issue for my use-case.

**Additional context**

Here's a screenshot of kitty and a browser rendering it side-by-side with only the cursor missing on the right:

![Screenshot_2021-05-14_21-01-01](https://user-images.githubusercontent.com/1816456/118345105-abc8fc00-b532-11eb-8078-ab8eb26672b1.png)

**Comment by kovidgoyal** [comment]
First, the latency is just python startup time, write the get-text call in a compiled language via the remote control protocol and you will get just a few ms of latency, see the example and protocol description here, https://sw.kovidgoyal.net/kitty/rc_protocol.html 

As for reporting cursor position, it should be a fairly trivial addition. Though if you want it in get-text it will be ANSI only which means you will get just the three cursor shapes (bar, block, underline) not cursor blinking/unfocused data.
