### ISSUE TITLE
"auto" mode for `c` and `r` graphics keys

### ISSUE THREAD

**Issue by devsnek** [kovidgoyal/kitty#3628]
**Is your feature request related to a problem? Please describe.**

It is finicky and frustrating to manually calculate image dimensions for display. The graphics docs start out by suggesting you should use `TIOCGWINSZ` and do the math yourself, however...

**Describe the solution you'd like**

There are `c` and `r` keys to specify that the image should be resized to fit a certain number of columns and/or rows. This is almost perfect, except that specifying only one is not useful here, and specifying both almost always results in a slightly warped image. I'd like to suggest that one of `c` or `r` may be set to the some value like `auto`, if the other is specified as a number value. For example: `c=10,r=auto` would display the image over 10 columns, with the rows being calculated by the term as it performs the resize, and as such the result would not be warped.

**Describe alternatives you've considered**

`TIOCGWINSZ`

**Additional context**

**Comment by kovidgoyal** [comment]
I dont follow, what is finicky and frustrating about it? It's two lines
of code. And why would specifying both cause the image to be warped?
Along with the ability to specify in cell offset placements you can
get pixel perfect images.

Not to mention that what you are asking for implies that the
terminal is now responsible for dynamically resizing images, which is
a whole can of worms, since doing so can cause text to scroll/be
covered/etc. Only the application can know what the correct way to
resize the screen contents is.

**Comment by devsnek** [comment]
@kovidgoyal Sorry, maybe I didn't explain this right...

> And why would specifying both cause the image to be warped?
Along with the ability to specify in cell offset placements you can
get pixel perfect images.

If you have an image that isn't the exact aspect ratio of the terminal's cells, it would be slightly warped (shorter and wider than the pixel perfect one in this screenshot):

![](https://gc.gy/88829169.png)

> Not to mention that what you are asking for implies that the
terminal is now responsible for dynamically resizing images, which is
a whole can of worms, since doing so can cause text to scroll/be
covered/etc.

Maybe I'm misunderstanding what "dynamic" means here. If you use `c` and/or `r`, the terminal dynamically calculates the width and height based on the device screen info (and the cursor is even updated)

In my above example, if I were to provide `c=auto,r=7`, I could get something where the width would just be scaled along the column axis proportionally to however much the terminal scaled it to reach 7 rows.

**Comment by kovidgoyal** [comment]
On Sat, May 15, 2021 at 05:22:22PM -0700, devsnek wrote:
> @kovidgoyal Sorry, maybe I didn't explain this right...
> 
> > And why would specifying both cause the image to be warped?
> Along with the ability to specify in cell offset placements you can
> get pixel perfect images.
> 
> If you have an image that isn't the exact aspect ratio of the terminal's cells, it would be slightly warped (shorter and wider than the pixel perfect one in this screenshot):
> 
> ![](https://gc.gy/88829169.png)

That's why I said use the in cell offsets as well, namely the X and Y
keys, to compensate for this. 

> 
> > Not to mention that what you are asking for implies that the
> terminal is now responsible for dynamically resizing images, which is
> a whole can of worms, since doing so can cause text to scroll/be
> covered/etc.
> 
> Maybe I'm misunderstanding what "dynamic" means here. If you use `c` and/or `r`, the terminal dynamically calculates the width and height based on the device screen info (and the cursor is even updated)

Ah, my mistake. I thought you wanted the terminal to resize images
when the screen is resized in "auto" mode.

So you basically want to have the terminal resize the image for you
instead of resizing it before transmission? Seems a waste, why transmit
all the extra image data?

**Comment by devsnek** [comment]
> That's why I said use the in cell offsets as well, namely the X and Y
keys, to compensate for this.

Maybe I'm misunderstanding the docs, but they say that X and Y control the origin of the image. I'm not sure how that helps in this case.

> So you basically want to have the terminal resize the image for you
instead of resizing it before transmission? Seems a waste, why transmit
all the extra image data?

Yep! Not all programming environments provide an easy way to call fnctl :smile:. In the worst case I could shell out to python or similar, but that seems a bit contrived. It also seems silly to have to calculate and resize the image when the terminal already has that info (and can likely do it much faster).

**Comment by kovidgoyal** [comment]
On Sat, May 15, 2021 at 05:50:11PM -0700, devsnek wrote:
> > That's why I said use the in cell offsets as well, namely the X and Y
> keys, to compensate for this.
> 
> Maybe I'm misunderstanding the docs, but they say that X and Y control the origin of the image. I'm not sure how that helps in this case.

As I recall the final height of the image will be r * cell_height - Y
and final width will be c * cell_width - X thereby allowing any aspect
ratio to be displayed correctly.

> 
> > So you basically want to have the terminal resize the image for you
> instead of resizing it before transmission? Seems a waste, why transmit
> all the extra image data?
> 
> Yep! Not all programming environments provide an easy way to call fnctl :smile:. In the worst case I could shell out to python or similar, but that seems a bit contrived. It also seems silly to have to calculate and resize the image when the terminal already has that info (and can likely do it much faster).

What programming environment is this? A shell? If so, call 

kitty +kitten icat --print-window-size

shelling out to utilities for tasks that cant be performed natively is
pretty much the ethos of shell scripts. Doesn't seem at all contrived to
me.

**Comment by devsnek** [comment]
It is Node.js actually. Good to know that `kitty +kitten icat --print-window-size` exists though, very much preferable to assuming the right python is available.

**Comment by kovidgoyal** [comment]
On Sat, May 15, 2021 at 06:09:15PM -0700, devsnek wrote:
> It is Node.js actually. Good to know that `kitty +kitten icat --print-window-size` exists though, very much preferable to assuming the right python is available.

It will work with any python. But yes, you can rely on kitty instead,
unless your script is running on a server over ssh with no kitty
installed.
