### ISSUE TITLE
Missing strokes in font

### ISSUE THREAD

**Issue by minhduc0711** [kovidgoyal/kitty#3629]
**Describe the bug**
Strokes in certain letters are not visible when using [MesloLGS NF font family](https://github.com/romkatv/powerlevel10k#manual-font-installation).

**To Reproduce**
1. Set font family to the said font in `kitty.conf`
2. Run `echo -e "\e[3mM m H N\e[0m"`

**Expected behavior**
All strokes are visible.

**Screenshots**
In Kitty:
![image](https://user-images.githubusercontent.com/34294427/118384784-2711d700-b633-11eb-8512-e8c0c920992c.png)
And in Alacritty
![image](https://user-images.githubusercontent.com/34294427/118384816-69d3af00-b633-11eb-82ec-97eb91daf374.png)

**Environment details**

```
kitty 0.20.3 created by Kovid Goyal
Linux acer-aspire-a5 5.12.2-arch1-1 #1 SMP PREEMPT Fri, 07 May 2021 15:36:06 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/minhduc0711/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background            Color(red=249, green=245, blue=215)
color0                Color(red=251, green=241, blue=199)
color1                Color(red=204, green=36, blue=29)
color10               Color(red=121, green=116, blue=14)
color11               Color(red=181, green=118, blue=20)
color12               Color(red=7, green=102, blue=120)
color13               Color(red=143, green=63, blue=113)
color14               Color(red=66, green=123, blue=88)
color15               Color(red=60, green=56, blue=54)
color2                Color(red=152, green=151, blue=26)
color3                Color(red=215, green=153, blue=33)
color4                Color(red=69, green=133, blue=136)
color5                Color(red=207, green=149, blue=175)
color6                Color(red=104, green=157, blue=106)
color7                Color(red=124, green=111, blue=100)
color8                Color(red=146, green=131, blue=116)
color9                Color(red=157, green=0, blue=6)
copy_on_select        clipboard
cursor                Color(red=60, green=56, blue=54)
cursor_blink_interval 0.0
cursor_text_color     None
font_family           MesloLGS NF
font_size             13.0
foreground            Color(red=60, green=56, blue=54)
selection_background  Color(red=189, green=174, blue=147)
selection_foreground  Color(red=249, green=245, blue=215)
Changed shortcuts:
	 shift+ctrl+n KeyAction(func='new_os_window_with_cwd', args=())
```

**Comment by kovidgoyal** [comment]
Yes you need to use an italic font whose metrics match the metrics of your main font. kitty *will not* render the contents of a cell outside the cell, which is how alacritty is doing that rendering. Which means that if the previous cells was filled, you would get the same cutoff or a bleed instead.

**Comment by minhduc0711** [comment]
> you need to use an italic font whose metrics match the metrics of your main font
Uhh sorry, what does that mean? I'm already using the italic version of the same font family.
Or do I need to raise this issue to the font provider, or use another font instead?

**Comment by kovidgoyal** [comment]
Yes, you need a font family whose italics are designed to fit in the
same bounding box as the non-italic face. I believe common choices are
Operator Mono, Jetbrains Mono.
