### ISSUE TITLE
url hints don't seem to work?

### ISSUE THREAD

**Issue by rattboi** [kovidgoyal/kitty#363]
When I try to use the new url hints kitten feature, it doesn't do anything except flash the screen. Not sure what is going on, or how to give you useful information. I would really like to use this feature, as this was a killer feature of urxvt that I miss. 

If I try using it on a buffer with no urls, it does correctly say "No URLs found", but when there is a URL on the screen, it just flashes instead.

Sorry to not have lots to work from. Tell me how to get better debug output, and I'll fill in more info.

**Comment by kovidgoyal** [comment]
Oh and create a file /tmp/urls with the contents:

```
http://one.com
https://two.com
```

Then in kitty run:

```
kitty +runpy 'from kittens.url_hints.main import main; main()' /tmp/urls
```

Does it work? Does it give an error?

**Comment by rattboi** [comment]
I'm on kitty 0.8.0 on MacOs 10.12.6

> Run kitty in a terminal and see if any messages are displayed and what OS are you on? What kitty version? Try it with a default kitty config file.
>
> kitty --config NONE

Strangely, this launches a window that immediately closes on my laptop, if run from kitty. If I launch it from Terminal.app instead (/Applications/kitty.app/Contents/MacOS/kitty --config NONE), I do get a single line response.

`[PARSE ERROR] Unknown OSC code: 7`

> Oh and create a file /tmp/urls with the contents:
>
> http://one.com
> https://two.com
>
> Then in kitty run:
>
> `kitty +runpy 'from kittens.url_hints.main import main; main()' /tmp/urls`
>
> Does it work? Does it give an error?

To add to the strangeness, this doesn't fail, and does what is expected. I get the hints with 0 and 1. Pressing either opens the link in my default browser.

I see there's a new commit associated with this. I'll see if I can get it built myself. I've been only running built binaries so far.

**Comment by rattboi** [comment]
I've successfully built kitty from HEAD, and it still has the same behavior as before. I don't believe your latest commit has fixed the issue. 

Working:
```kitty +runpy 'from kittens.url_hints.main import main; main()' /tmp/urls```

Ctrl+Shift+E with urls on the screen:
(Screen flashes/refreshes, but nothing else)

Ctrl+Shift+E with no urls on screen:
```No URLs found, press Enter to abort.```

**Comment by kovidgoyal** [comment]
Works for me, on my macOS machine. And a couple of commits before I added code that would show an error if it fails. So I dont think you are actually running from HEAD.

**Comment by rattboi** [comment]
You were right. I uninstalled kitty via brew, and put my built version in it's place, and now url hints are working! 👍

**Comment by kovidgoyal** [comment]
Cool. I'm curious though, you used to use urxvt on macs? Using an X server or is there a port of urxvt to cocoa?

**Comment by rattboi** [comment]
I historically have used Linux for personal and work, but my new job doesn't support linux laptops, so I'm using a MacOs laptop. So no, I'm not using urxvt on mac. Sorry for the confusion.
