### ISSUE TITLE
Weird horizontal spacings with JetBrains Mono Italic font

### ISSUE THREAD

**Issue by minhduc0711** [kovidgoyal/kitty#3630]
**Describe the bug**
Using JetBrains Mono, I noticed that the letter `f` has weird horizontal spacings when it is in italic.
Is it because of the font family again?

**Screenshots**
In kitty (font size 13):
![image](https://user-images.githubusercontent.com/34294427/118392683-006c9400-b665-11eb-81f2-abb2d1dc5e7e.png)

Looks a bit better when I increase font size (14):
![image](https://user-images.githubusercontent.com/34294427/118392724-30b43280-b665-11eb-9458-848a7975633e.png)

In VScode (font size 13):
![image](https://user-images.githubusercontent.com/34294427/118392660-e7fc7980-b664-11eb-8c29-1efa228d15e2.png)

**Comment by kovidgoyal** [comment]
Are you saying there isnt enough leading, i.e. space at the left edge? And yes letter positioning is specified by the font, most likely what happens is that the letter as specified in the font overflows the right side of the cell, so kitty moves it back a bit to make it fit, which has the effect of reducing the leading space. I'm afraid I dont really see a good way to fix this, short of editing the font to change the metrics of that character.
