### ISSUE TITLE
Kitty ends before calling disown

### ISSUE THREAD

**Issue by y0ast** [kovidgoyal/kitty#3631]
When calling kitty directly with a command, it exists right after `&` is called instead of executing disown.

```
kitty sh -c 'nohup kitty >/dev/null 2>/dev/null & disown'
```
I expect a new kitty window to open and remain open, but it doesn't. Instead a window opens/closes very quickly.

Directly calling:
```
sh -c 'nohup kitty >/dev/null 2>/dev/null & disown'
```
from an open kitty terminal works fine, and I can close the original terminal without issue.

I am attempting to use kitty as a dmenu style file opener with `xdg-open` but this behavior prohibits that use case.

kitty 0.20.3 on Linux arch 5.12.3-arch1-1 and same problem appears with `--config NONE`

**Comment by kovidgoyal** [comment]
disown is executed by the shell not by the program you are running. And
if you want to detach kitty from the controlling terminal, use

kitty --detach
