### ISSUE TITLE
Integrated vs Discrete GPU switch / option missing and no way to reliably tell which is being utilised.

### ISSUE THREAD

**Issue by pm5k** [kovidgoyal/kitty#3640]
Hello,

I realise this does not really fit in the issue categories you have templated, but I was checking for an option to explicitly tell Kitty(.20.3) which GPU to use in my system (discrete over intel UHD) and found no such option. Now it may very well be that Kitty is clever enough to grab the discrete GPU if it exists and default to integrated if not, but I could not find anything to state this in the docs and no such option seems to exist anywhere.

Let me know if this is something I have overlooked or if more info is needed from my side.

Thanks

**Comment by kovidgoyal** [comment]
There is no such option. Indeed kitty has no functionality to select
GPUs at all. The system will assign GPUs using whatever OS level
policies it has. kitty has no control over it. kitty simply advertises
that it is capable of using either GPU. So on a typical system as long
as no other application is requesting the discrete gpu kitty will use
the low power one.
