### ISSUE TITLE
I'd like to be able to 1) Select All 2) Copy 3) Paste (into a text editor)

### ISSUE THREAD

**Issue by Raytle** [kovidgoyal/kitty#3643]
I'd like to be able to 1) Select All 2) Copy 3) Paste (into a text editor).

Use case: I want to edit some text from Kitty. Currently I need to click, hold, and drag with my mouse to select text.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/index.html#the-scrollback-buffer

**Comment by Raytle** [comment]
Thanks for taking the time to respond quickly and send me the following link...

https://sw.kovidgoyal.net/kitty/index.html#the-scrollback-buffer

I read it.

I also read this...

https://github.com/kovidgoyal/kitty/issues/719

I am hoping that you might provide me with an explanation similar to (but of course different than)...

1. To select all of your text, that is, to Select All, press `ctrl+a`.
2. To copy all of your text, that is, to Copy, press `ctrl+c`.
3. Then open your text editor
4. Finally, to paste all of your text, that is, to Paste, press `ctrl+v`.

===================

Here. I'll get you started....


Let's say kitty is located at `/usr/bin/kitty` and let's say you want to view the entire contents of your terminal in a text editor, such as mousepad  located at `/usr/bin/mousepad `or kwrite located at `/usr/bin/kwrite`

1. Do this..
2. Then do this...
3. Then do this...
4. Finally do this...

If you were to put that explanation in...

https://sw.kovidgoyal.net/kitty/#scrollback

you would help non-technical people (like me) figure out how to paste the entire contents of their terminal into another application (such as a text editor).

Finally, I am baffled that I am unable to map `ctrl+a` to Select All in kitty. Sure. Yeah. I get it. "Terminals don't work that way." or -"Unix was designed in the mid-1960s". But really. I mean really. Think about it. Why shouldn't non-technical people (like me) be able to press `ctrl+a` to Select All in kitty? 

Every developer claims to strongly believe in standardization... by strictly adhering to some non-standard way of doing things that makes sense to them and other developers. Yeah. I'm being sardonic. But seriously. Why do developers insist that non-developers learn technical details that are important for developers but unimportant for non-developers?

It's not 1960. Choosing `ctrl+a` to Select All is a standard for non-technical users. Giving them this option would make kitty feel like a "regular application" instead of an "unapproachable, techie, hassle."

**Comment by kovidgoyal** [comment]
kitty is not for non-technical people, I suggest you stick to graphical user interfaces, you will be much happier. Why would you imagine terminals are an interface for non-technical users? What about an empty black screen with a  blinking cursors screams I am a point and grunt interface suitable for gorillas to you?

**Comment by Raytle** [comment]
Kitty is the best terminal I have found. And, yes. Sure. Of course, I usually avoid using a terminal. Really. I do. But sometimes it's easier for me to use a terminal. 

For example, earlier ​today I found out that  `apt install flameshot` caused me to have flameshot-0.6 instead of flameshot-0.9. And. Of course. flameshot-0.9 has a feature I want that is missing in flameshot-0.6.

Therefore, I followed the dev's instructions by downloading `flameshot-0.9.0-1.debian-10.amd64.deb`. Instead of trying to figure out which GUI application to use to install it, I did a quick Google search to remind myself that I could install it by prepending `sudo dpkg -i` to it.

By the way, if you've never tried it, [flameshot](https://github.com/flameshot-org/flameshot) is [the bees knees](https://www.ecenglish.com/learnenglish/lessons/idiom-day-the-bees-knees#:~:text=When%20you%20refer%20to%20something,are%20a%20number%20of%20theories). Also, [CopyQ](https://hluk.github.io/CopyQ/) is an amazing  "...advanced clipboard manager with editing and scripting features."

If you would like me to give more concrete several examples of how I use a terminal, then I will. 

In kitty...

1. when I press `ctrl+c` it copies,
2. when I press `ctrl+v` it pastes,
3. yet when I press `ctrl+a` nothing happens.

Isn't there some way I can press `ctrl+a` to select all? Is there a technical limitation that makes that difficult? Can't kitty write everything that is entered into something like a text file (in real-time, that is, as it is entered) and then, when a user presses `ctrl+a`, select all of that text?

I've worked with many devs over the years. Therefore, I become [inured](https://en.wiktionary.org/wiki/inure#:~:text=(transitive)%20To%20cause%20someone%20to,of%20one%20or%20more%20unpleasantries.%20%5B) to assertions such as, "You can't get there from here" (which, your case, was expressed as, "kitty is not for non-technical people"). Devs trot that sort argument out almost reflexively. It's as predictable as the sun rising in the east. Instead of playing the role of the curmudgeon, how about solving a problem that will help your sworn enemies: non-technical users? I am almost certain that it is not technically difficult to cause `ctrl+a` to choose Select All because I am almost certain that as text is entered into a terminal can be stored on the user's local drive and concomitantly later read back into memory.

**Comment by Luflosi** [comment]
I'll see how much work this is to implement when I find some time this weekend

**Comment by trygveaa** [comment]
Not sure if selecting all text is possible with a simple key binding, you might have to write a kitten. But to copy all the text from the terminal into the clipboard you can map a key like this:

```
map ctrl+a launch --type=clipboard --stdin-source=@screen_scrollback
```

`ctrl+a` doesn't do nothing by default btw, it moves the cursor to the start of the line.

**Comment by Raytle** [comment]
> I'll see how much work this is to implement when I find some time this weekend

I think I came up with a workable kludge.

Something more or less like my explanation below should be put into...

https://sw.kovidgoyal.net/kitty/#scrollback

## Do you want to be able to edit the text that appears in Kitty in a text editor? 
### Here's one solution.

First, install [Kwrite](https://apps.kde.org/kwrite/). It's a simple text editor. If you want something more robust the following instructions will also presumably work with Kwrite's "big brother" [Kate](https://github.com/KDE/kate) or presumably many other applications such as VIM that allow piping.

1. Install `kwrite` (For buntu users try `sudo apt install kwrite`)
2. Open `~/.config/kitty/kitty.conf`
3. Enter the following line... **map ctrl+a pipe @text tab /usr/bin/kwrite -i**
4. Save and close `~/.config/kitty/kitty.conf`.
5. Smile! That's all there is to it.

To test it...

1. Open Kwrite
2. Type some gibberish text such as 'safdlksdflk`
3. Press the `Enter` key.
3. Press `ctrl+a`
4. If it worked you will see the gibberish text in a Kwrite document.

Many developers like @kovidgoyal are sooooo out of touch with reality sometimes that they disgust me. They will spend countless hours fighting like selfish little children defending their nonsensical assertions instead of spending a fraction of that time to simply solve a simple problem.

**Comment by Raytle** [comment]
> Not sure if selecting all text is possible with a simple key binding, you might have to write a kitten. But to copy all the text from the terminal into the clipboard you can map a key like this:
> 
> ```
> map ctrl+a launch --type=clipboard --stdin-source=@screen_scrollback
> ```
> 
> The documentation for this type of mapping is here: https://sw.kovidgoyal.net/kitty/launch.html
> 
> `ctrl+a` doesn't do nothing by default btw, it moves the cursor to the start of the line.

Thank you! I'll need to test it, but think your solution is better than the one I came up with. After I noticed in the docs that `pipe` had been deprecated, I tried to use `launch` but I failed.

**Comment by Raytle** [comment]
> map ctrl+a launch --type=clipboard --stdin-source=@screen_scrollback

I just tested it. That worked for me! Thank you very much for your help.

How can I use `launch` to do what the following does...

`map ctrl+a pipe @text tab /usr/bin/kwrite -i`

Personally, I couldn't care less about using `launch` vs `pipe`. I'm not a dev and I find this technical stuff remarkably tedious and, well, uninteresting. But whenever I see "XYZ [in this case `pipe`]has been deprecated" I've learned to look for another solution.

**Comment by trygveaa** [comment]
> Many developers like @kovidgoyal are sooooo out of touch with reality sometimes that they disgust me. They will spend countless hours fighting like selfish little children defending their nonsensical assertions instead of spending a fraction of that time to simply solve a simple problem.

This is very rude. @kovidgoyal is providing this software for free and uses a lot of his own time on development and support. Helping users takes a lot of time, which is why he has written documentation and refers to that. Even so, he answers all issues very fast, and is very helpful when the issue is not covered by the documentation.

> How can I use `launch` to do what the following does...
> 
> `map ctrl+a pipe @text tab /usr/bin/kwrite -i`

The equivalent launch command would be this:

```
map ctrl+a launch --type=tab --stdin-source=@screen_scrollback /usr/bin/kwrite -i
```

Using `--type=background` would be better, so you don't get an extra useless tab, but that doesn't work in the current version, so you'll have to wait for the next release for that.

**Comment by Raytle** [comment]
> > How can I use `launch` to do what the following does...
> > `map ctrl+a pipe @text tab /usr/bin/kwrite -i`
> 
> The equivalent launch command would be this:
> 
> ```
> map ctrl+a launch --type=tab --stdin-source=@screen_scrollback /usr/bin/kwrite -i
> ```

Thank you! That works very well for me.


> Using `--type=background` would be better, so you don't get an extra useless tab, but that doesn't work in the current version, so you'll have to wait for the next release for that.

I see. Thanks for letting me know


> > Many developers like @kovidgoyal are sooooo out of touch with reality sometimes that they disgust me. They will spend countless hours fighting like selfish little children defending their nonsensical assertions instead of spending a fraction of that time to simply solve a simple problem.
> 
> This is very rude. 

"If the shoe fits... wear it."


> @kovidgoyal is providing this software for free and uses a lot of his own time on development and support. Helping users takes a lot of time, which is why he has written documentation and refers to that. Even so, he answers all issues very fast, and is very helpful when the issue is not covered by the documentation.

That is true.

Yet none, and I mean **none**, of that obviates the  tyrannical behavior of @kovidgoyal. These petty little despots who rule of their little FOSS kingdoms sicken me. When a user makes a reasonable request these vanguards of "science for humanity" often throw a tantrum. Everything I asked for was simple, obvious, and reasonable... to a sane person. @kovidgoyal could have simply given an answer similar to the one you gave me or, at least, posted a response like, "Hey that's a good idea. Can someone respond with an answer. I'm busy with other tasks at the moment." Make no mistake about it: @kovidgoyal behaved badly. Sharp engineers like @kovidgoyal notoriously act like "enfant terrible." I'm having none of it.

**Comment by kovidgoyal** [comment]
On Thu, May 20, 2021 at 08:05:26PM -0700, Raytle wrote:
> Yet none, and I mean **none**, of that obviates the  tyrannical behavior of @kovidgoyal. These petty little despots who rule of their little FOSS kingdoms sicken me. When a user makes a reasonable request these vanguards of "science for humanity" often throw a tantrum. Everything I asked for was simple, obvious, and reasonable... to a sane person. @kovidgoyal could have simply given an answer similar to the one you gave me or, at least, posted a response like, "Hey that's a good idea. Can someone respond with an answer. I'm busy with other tasks at the moment." Make no mistake about it: @kovidgoyal behaved badly. Sharp engineers like @kovidgoyal notoriously act like "enfant terrible." I'm having none of it.


Man, I tried to ignore you, but this is too much. What a fucking entitled
asshole. You were told how to do what you wanted within a few
minutes of you asking the question. That you are both too stupid and
too lazy to read and find the answer even when pointed to exactly where to
look, indicates just how much af a parasite and waste of oxygen you
are.

You have been blocked. Dont let the door hit your fat ass on the way
out.
