### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by jehuamanna** [kovidgoyal/kitty#3650]
I am trying to compile from source. I have satisfied all the library dependecies for kitty.

I get the following error. Please let me know if additional details are required.

> $ python3 setup.py linux-package
> CC: gcc (7, 0)
> [32/98] Compiling [x11] glfw/context.c ... done
> Compiling kitty/freetype_render_ui_text.c ...
> gcc -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=20 -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -D_FORTIFY_SOURCE=2 -fPIC -flto -pthread -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/python3.6m -c kitty/freetype_render_ui_text.c -o build/fast_data_types-freetype_render_ui_text.c.o
> In file included from /usr/include/harfbuzz/hb-blob.h:34:0,
>                  from /usr/include/harfbuzz/hb.h:35,
>                  from /usr/include/harfbuzz/hb-ft.h:32,
>                  from kitty/freetype_render_ui_text.h:10,
>                  from kitty/freetype_render_ui_text.c:8:
> /usr/include/harfbuzz/hb-common.h:79:29: error: enumerator value for ‘_HB_SCRIPT_MAX_VALUE’ is not an integer constant expression [-Wpedantic]
>  #define HB_TAG(c1,c2,c3,c4) ((hb_tag_t)((((uint8_t)(c1))<<24)|(((uint8_t)(c2))<<16)|(((uint8_t)(c3))<<8)|((uint8_t)(c4))))
>                              ^
> /usr/include/harfbuzz/hb-common.h:83:20: note: in expansion of macro ‘HB_TAG’
>  #define HB_TAG_MAX HB_TAG(0xff,0xff,0xff,0xff)
>                     ^~~~~~
> /usr/include/harfbuzz/hb-common.h:328:29: note: in expansion of macro ‘HB_TAG_MAX’
>    _HB_SCRIPT_MAX_VALUE    = HB_TAG_MAX, /*< skip >*/
>                              ^~~~~~~~~~
> /usr/include/harfbuzz/hb-common.h:79:29: error: ISO C restricts enumerator values to range of ‘int’ [-Wpedantic]
>  #define HB_TAG(c1,c2,c3,c4) ((hb_tag_t)((((uint8_t)(c1))<<24)|(((uint8_t)(c2))<<16)|(((uint8_t)(c3))<<8)|((uint8_t)(c4))))
>                              ^
> /usr/include/harfbuzz/hb-common.h:83:20: note: in expansion of macro ‘HB_TAG’
>  #define HB_TAG_MAX HB_TAG(0xff,0xff,0xff,0xff)
>                     ^~~~~~
> /usr/include/harfbuzz/hb-common.h:328:29: note: in expansion of macro ‘HB_TAG_MAX’
>    _HB_SCRIPT_MAX_VALUE    = HB_TAG_MAX, /*< skip >*/
>                              ^~~~~~~~~~
>

**Comment by kovidgoyal** [comment]
Your compiler is too old, use the --ignore-compiler-warnings option when
calling ./setup.py build
