### ISSUE TITLE
Compose Keyboard Keys Not Working

### ISSUE THREAD

**Issue by engblom** [kovidgoyal/kitty#3655]
**Describe the bug**
A composed keyboard character requires two key presses as a sequence. For example ' followed by "a" gives "á" or ~ followed by "n" gives "ñ" or " followed by "o" gives "ö". All these sequences do not work with KiTTY.

**To Reproduce**
setxkbmap fi
press ' (which is the key to the left of backspace on fi keyboard) followed by an "a" and you will get just "a" instead of "á".

**Environment details**
OS: Ubuntu 21.04

```
Output of kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Linux kitlle 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64
Ubuntu 21.04 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/lars/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=255, green=255, blue=255)
enable_audio_bell     False
font_size             12.0
foreground            Color(red=0, green=0, blue=0)
update_check_interval 0.0
```

**Comment by kovidgoyal** [comment]
Compose keys have worked fine in kitty for years. Presumably there is
some issue with xkb on your system. First of all update kitty to 0.20.3,
which has much improved keyboard diagnostics and run kitty as

kitty --debug-keyboard

and see what events are generated

And at least on my system setting xkbmap to fi causes ' to generate ä
and ~ to generate ½ in both xterm and kitty. So I dont know why you
think those keys are compose keys.

**Comment by engblom** [comment]
You did not do exactly as I said in how to reproduce: after changing to Finnish keyboard you need to really press the **key to the left of backspace** (regardless of what label it got on your keyboard) because with the Finnish keyboard it will expect one key more to follow and then it should compose a character. If you press there where you have your ' label you will not get a compose sequence but ä as you wrote. Please give it a try more!

**Comment by kovidgoyal** [comment]
Pressing = followed by a gives me á, as expected in kitty.

**Comment by engblom** [comment]
I started up kitty from another terminal and found this:

xkbcommon: ERROR: couldn't find a Compose file for locale "en_DK.UTF8"

Keyboard compose is working in every other terminal I have tried (xterm, gnome-terminal, xfce-terminal etc). KiTTY apparently does something differently.

**Comment by engblom** [comment]
Just wanted to add that even if I am using en_DK.UTF8 as locale, when using Finnish keyboard map (setxkbmap fi) it should use /usr/share/X11/locale/fi_FI.UTF-8/Compose for handling compose sequences. Even the xkb map file for fi tells to use that Compose file.

**Comment by kovidgoyal** [comment]
On Tue, May 25, 2021 at 11:59:31AM -0700, engblom wrote:
> Just wanted to add that even if I am using en_DK.UTF8 as locale, when using Finnish keyboard map (setxkbmap fi) it should use /usr/share/X11/locale/fi_FI.UTF-8/Compose for handling compose sequences. Even the xkb map file for fi tells to use that Compose file.

No, it shouldn't. Compose tables are loaded from locales not keyboard
maps. See https://xkbcommon.org/doc/current/group__compose.html

If you want to use a different compose file from your locale for some
reason, then set the XCOMPOSEFILE env var. man 5 Compose
