### ISSUE TITLE
Add `{user}`, `{host}`, and `{cwd}` to `tab_title_template` config option

### ISSUE THREAD

**Issue by Antagonym** [kovidgoyal/kitty#3656]
Isolating the current username, host, or working directory from the tab title is a hassle involving numerous `.split('...')[...]`. This rather wordy and quickly makes the `tab_title_template` config option quite hard to read if one wishes to process these things individually. Having access to additional `{user}`, `{host}`, and `{cwd}` replacements would alleviate this issue and make working with them individually much more convenient.

An easy way to use the explicitly set tab-title if available or fall back to a default title would also be nice.

**Comment by kovidgoyal** [comment]
I dont follow. kitty has no knowledge of what user/host you are
connected to/running as so where would those values come from?

The correct way to control tab titles is to simply use the escape codes
to set titles to whatever you like in your shell. A bit of googling will
show you how to do that.

**Comment by csimpi** [comment]
@kovidgoyal 
He meant environment variables, like $HOME, $CWD. It would be great to be able to customize the title logic this way. 
For example {user}@{host} {title}

**Comment by page-down** [comment]
For example, if you connect to `root@10.0.0.1` using ssh and change the current user to `nobody` via sudo, and cd to `/tmp`, kitty will not know the username or hostname or cwd at this point.

So the best way is to set them in the shell by escape code.
If you have other tab bar customization needs, you can use the new custom tab bar feature in version 0.24.

**Comment by csimpi** [comment]
@page-down this is just finding excuses. 
1. I still can set those variables if I really want
2. You bring up a rare and not real-life daily situation 
3. It works perfectly with Alactritty, so it's not impossible, and not that difficult to implement either

**Comment by page-down** [comment]
> this is just finding excuses

If you can respect others and recognize that you may have misunderstandings, then you will be able to listen to others' sincere words and learn more.

Also you need to understand that to achieve your purpose, you should have a positive attitude. If your words are not helpful in achieving your goal, all your attempts will be wasted.

> I would even expand this request with being able to add any variables to the title format template ...

Please see the last line of my reply and see the new features added in the latest version. Write your own `tab_bar.py` and draw the tab bar however you want.

> how would you solve the escaping thing? How can I catch the event I changed a folder or something else that the title should be changed too?

You need to understand SSH, the shell, the environment in which the user process is running, and the environment in which kitty is running.

In a general scenario, depending on the shell you are using, you can configure to execute arbitrary code when pwd changes, at which point you can use `ESC ] 2 ; <string> <ST>` to set the title.

You can also manually install the shell integration feature (added in the latest version) on the SSH host.

https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration

**Comment by kovidgoyal** [comment]
On Wed, Jan 12, 2022 at 05:53:23PM -0800, Peter wrote:
> > If you can respect others and recognize that you may have misunderstandings, then you will be able to listen to others' sincere words and learn more.
> I came here for that, but I've got a zero valuable answer with zero intent of assisting at all. What you said it just finding excuses, since this is working perfectly with Alactritty for example. 

No, it doesnt. SSH into a server in alacritty and watch the title being
wrong. There is a simple *fact* here. The terminal emulator *cannot*
know what host the client program is logged into, that is actually
impossible. The client program can do SSH, rsh, telnet, any new protocol
you dream of, can do jup ssh over ultiple hsts, there is simply *no* way
for a terminal to keep track of that. 

The *only* way this can work is if the client program informs the
emulator of the host. And the *best* way to do that is to add the escape
codes to your shell configuration on the remote computer, to update the
terminal windows title. Which has already been explained before. Stop
wasting people's time.


> 
> `Write your own tab_bar.py and draw the tab bar however you want.`
> Tab bar is not the title bar and has nothing to do with that at all. This topic is about the window's title. 
> If you would have read the OP instead of jumping in you would have realized that even the original question explains why the approach you are coming up with is a bad approach.
> 
> Still, OP and I both are looking for a ready-to-use and configurable solution, not something I can do whatever I use. If I would want to handle it on my own I wouldn't have come here in the first place. 
> 
> You need to learn about how to communicate properly and effectively, also how to read and understand basic user requests. 
> I have given good press for Kitty because of the community, but I'm going to update my article that I was wrong.

Kindly fuck off. And in the future do not *ever* try
to make threats against open source projects.
