### ISSUE TITLE
Font scaling changes when switching workspaces (Wayland, dual monitor with 200/100 scalings)

### ISSUE THREAD

**Issue by fnune** [kovidgoyal/kitty#3657]
**Describe the bug**
With the following setup:

- Ubuntu/Gnome on Wayland
- Dual monitors
- Primary monitor on 100% scaling, secondary monitor on 200%
- Fractional scaling disabled
- `linux_display_server` set to `wayland`

There are two related issues:

- I need to set a font size much bigger than normal for it to look OK
- When I switch to another workspace and come back to the workspace where Kitty is (on my primary screen, 100% scaling), Kitty flashes from a huge font size back to normal (for about 20-30ms?)

**To Reproduce**
1. Reproduce the setup described above
2. Place Kitty on the primary monitor with the smaller font scaling
3. Change to a workspace where Kitty is *not*
4. Change back to the workspace containing the Kitty window

**Screenshots**
Regular, OK size:
![image](https://user-images.githubusercontent.com/16181067/119643655-4ae7d080-be1c-11eb-8dbb-6504b6b241b2.png)

This is how it looks for a split second (I had to mimic this by zooming, since I can't record my screen on Wayland):
![image](https://user-images.githubusercontent.com/16181067/119643850-8d111200-be1c-11eb-92dc-e0fdb42e3ac4.png)

**Environment details**
OS: Name and version of operating system(s)
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

`kitty --debug-config`
```
Linux maedhros 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64
Ubuntu 21.04 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/fausto/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
bold_font               Cascadia Code SemiBold
bold_italic_font        Cascadia Code Italic SemiBold
enable_audio_bell       False
font_family             Cascadia Code SemiLight
font_size               18.0
hide_window_decorations 1
italic_font             Cascadia Code Italic SemiLight
update_check_interval   0.0
Added shortcuts:
         ctrl++ KeyAction(func='change_font_size', args=(True, '+', 1.0))
         ctrl+- KeyAction(func='change_font_size', args=(True, '-', 1.0))
         ctrl+0 KeyAction(func='change_font_size', args=(True, None, 0.0))

```

**Additional context**
- This still happens with `kitty --config NONE`
- This can be worked around by setting `linux_display_server` to `x11`
- It can also be worked around by having the same scaling on both monitors, or just using one monitor

**Comment by kovidgoyal** [comment]
kitty has no control over this. It will simply react to scale change
events from the compositor. If you are seeing an unwanted scale change
during workspace transitions, the bug will be in the compositor. You can
see the events kitty receives from the compsoitor by running it with
--debug-rendering

**Comment by fnune** [comment]
Understood. I'm having a lot of difficulty finding an existing upstream issue.

Either way, thank you for your time and your software! <3

**Comment by stelcodes** [comment]
@fnune I was experiencing the same issue with Sway when using multiple monitors with different scaling factors, I found that setting `resize_draw_strategy scale` fixed it.
