### ISSUE TITLE
AsciiDoc URL Selection with Trailing Brackets

### ISSUE THREAD

**Issue by kleutzinger** [kovidgoyal/kitty#3659]
**Is your feature request related to a problem? Please describe.**
Asciidoc links are written as such `https://powerman.name/doc/asciidoc-compact[AsciiDoc Cheatsheet]`
which is equivalent to the markdown `(https://powerman.name/doc/asciidoc-compact)[AsciiDoc Cheatsheet]`

The link hovering improperly includes the text after and including the first `[` until it hits a space.
Same problem with kitty_mod + e url-selection.

**Describe the solution you'd like**
Allow clicking on these links without including the trailing `[...`.

**Describe alternatives you've considered**
Add kitty setting to specify URL delimiters / separators / ending-characters. (not sure the proper name).

**Additional context**

![image](https://user-images.githubusercontent.com/6435727/119865272-5d234680-bed0-11eb-9f91-9863c1b7ec0d.png)

Thank you

**Comment by kovidgoyal** [comment]
There is no way to robustly detect such a link. [ is perfectly valid
character in urls. The fact that asciidoc chose not to delimit their
urls properly unlike markdown, rst, etc. is a bug in its design. 

That said, if you want to customize URL detection to handle this, use
the hints kitten which lets you specify regexes or even python programs
to detect URLs. https://sw.kovidgoyal.net/kitty/kittens/hints.html
