### ISSUE TITLE
Minor suggestion on macOS: implement ⌘+, to open settings

### ISSUE THREAD

**Issue by MindTooth** [kovidgoyal/kitty#366]
Hi,

On macOS — and have been for as long as I can understand, when pressing `⌘+,`, will open the settings screen, or whatever way to change settings.

Would that be trivial to implement something like that?  Pressing the combo would use the default editor and open the config file.

I know it's a just navigate to folder, or edit using Vim via the terminal.  But would fall in line with the standard on macOS, and make it easier to change settings desired.

Thoughts?  Wish I were able to submit a PR for this, but I don't have the skills.

**Comment by MindTooth** [comment]
Wow, nice!  Thank you so much 😊

**Comment by MindTooth** [comment]
Experienced that this opened the system Vim on macOS, instead of the one I've installed via Homebrew.

Am I doing something wrong?  Do kitty read some other variable than the EDITOR of the current user?  Also, if I use the `open` command via the terminal, the file is opened via my default editor for `.conf` files (in this case CotEditor).

**Comment by kovidgoyal** [comment]
It reads EDITOR and if no EDITOR is defined, it uses vim. Which vim willl be used will depend on your PATH

**Comment by MindTooth** [comment]
```shell
~ $ echo $EDITOR
vim
~ $ echo $PATH
/usr/local/sbin /Applications/kitty.app/Contents/MacOS /usr/local/bin /usr/bin /bin /usr/sbin /sbin
~ $ type -a vim
vim is /usr/local/bin/vim
vim is /usr/bin/vim
```

Still opened vim under `/usr/bin/vim`.  Thanks for replying.

**Comment by kovidgoyal** [comment]
Why is your PATH space separated? it should be separated by colons. And the PATH inside the terminal is not the relevant path, as that is modified by your shells rc files. The PATH used by launch services is the relevant path. You might need to add /usr/local/bin to that.

**Comment by MindTooth** [comment]
That's how fish-shell outputs it I guess.  With semicolons when using `env`:
```
PATH=/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Seems like local should already come first:
```
~ $ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by kovidgoyal** [comment]
Oh and when I say launch kitty I mean run /Applications/kitty.app/Contents/MacOS/kitty

**Comment by MindTooth** [comment]
That worked.  So I don't how to solve this.  Searched and read at least 40 pages on how to change the system path, but nothing conclusive.

Tried:

>sudo launchctl config user path /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

and 

> launchctl setenv PATH /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

But still no go.  Oh well, I don't plan on edit to much the config file ;)  Thanks at least!

**Comment by kovidgoyal** [comment]
https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite

Either set PATH or set EDITOR to a full PATH like /usr/sbin/vim
