### ISSUE TITLE
Customize keybindings within +kitten unicode_input

### ISSUE THREAD

**Issue by Kabouik** [kovidgoyal/kitty#3660]
**Is your feature request related to a problem? Please describe.**
I bound <kbd>^[</kbd> and <kbd>^]</kbd> to prev/next tab in kitty, but those key combinations appear to be the default keys for mode changing in `kitty +kitten unicode_input`. I would be happy to remap mode changing to some other keys, but I can't seem to find in the documentation what would be the commands I could use in my `kitty.conf`.

**Describe the solution you'd like**
Add or document commands for mode changing and other sub-functions of `unicode_input`, like add to favourites, _etc._ I am really sorry if those commands already exist and are documented.

**Comment by Kabouik** [comment]
Thank you @kovidgoyal. So my understanding from the commit is there were alternate keybindings already (unfortunately not available on my setup either, I need them for my WM) but they are not customizable unless I patch the source, correct? That's not a critic, just asking confirmation before I try to look in the code where this could be patched.

**Comment by kovidgoyal** [comment]
yes, they are not customizable, I'm afraid I am not interested in adding
customization to the kitten just for this. And if you want to patch it
code is in unicode_input/main.py

**Comment by Kabouik** [comment]
I understand, no worries. I think it's perfectly fine since it can be patched locally for those who need other keybindings than those already defined (and there are multiple ones already, I just happen to be in a case where none is available for me). Thanks!
