### ISSUE TITLE
tab bar colours don't update with set-colors

### ISSUE THREAD

**Issue by chipaca** [kovidgoyal/kitty#3662]
**Describe the bug**

When changing the colours using `kitty @ set-colors`, the tab bar colours don't update. Restarting kitty (or even starting a new ... frame? using `kitty @ detach-window`, or a new `kitty -1`) has the new tab bar with the colours correct.

**To Reproduce**
1. Start kitty with a dark theme, with remote-control enabled. The minimal config to reproduce the issue is
   ```
   allow_remote_control yes
   ```
2. `kitty @ set-colors -a -c` to a light theme, e.g. [Solarized_Light.conf](https://github.com/dexpota/kitty-themes/blob/master/themes/Solarized_Light.conf).
3. See tab bar not change colour.

(the light/dark switch is just so it's clearly visible)

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/1543430/119951276-aa1c2100-bf93-11eb-95cb-6ff764754767.png)
After:
![image](https://user-images.githubusercontent.com/1543430/119951314-b6a07980-bf93-11eb-84dd-9254f3723e1b.png)
After detaching or otherwise restarting:
![image](https://user-images.githubusercontent.com/1543430/119951411-d5067500-bf93-11eb-9c73-f48f1da28510.png)

**Environment details**
OS: Ubuntu 20.04.2 LTS

```
kitty 0.20.3 (bc6e819396) created by Kovid Goyal
Linux fleet 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /tmp/min.conf
Running under: X11

Config options different from defaults:
allow_remote_control y
```

**Comment by kovidgoyal** [comment]
Works for me, with the following two conf files:

```
tab_bar_background green
active_tab_foreground black
active_tab_background white
inactive_tab_foreground #333
inactive_tab_background #aaa
```

```
tab_bar_background red
active_tab_foreground white
active_tab_background black
inactive_tab_foreground #aaa
inactive_tab_background #333
```

and current kitty master.
