### ISSUE TITLE
Add set mark feature which make copy marked content on kitty more easy (as done in many editor, no mouse need)

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#3663]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When i input some command in kiity, sometimes, i want to copy some content into clipboard, this feature
very useful when used with some  REPL for copy some code to somewhere without need mouse.

e.g. i want copy following content `Stock.order(:percent_of_institutions).reverse.first(10)` into clipboard.or 

![image](https://user-images.githubusercontent.com/549126/119956173-647f4880-bfd3-11eb-805b-8f6d483ef938.png)

For now, i have to do is, use mouse/touchpad select all content like this, then copy it use a shortcut key.

![image](https://user-images.githubusercontent.com/549126/119956316-8e386f80-bfd3-11eb-9ada-e02acc354805.png)

if I it possible to add some shortcut key, e.g. like emacs, `Ctrl+Space`, will activate the mark mode, then when cursor moving with 
`Ctrl + F`, all passing place will selected as done use mouse to select, or another solution, as most editor does,  permit press shift to select content when moving,  e.g. Shift+Ctrl+F, will moving cursor forward and make passing place selected.

Thank you.

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/#the-scrollback-buffer

**Comment by zw963** [comment]
> See https://sw.kovidgoyal.net/kitty/#the-scrollback-buffer

Sorry,  i think this is not what i want, use the scrollback buffer, we can only select content from history i guess, but for my case, i just want to select/copy the last inputing content.

**Comment by kovidgoyal** [comment]
you can open the contents of the current screen, or the
screen+scrollback in any program you like including your fav editor,
with a single keypress, and then do whatever selection/copying/etc you
want to do.
