### ISSUE TITLE
draw powerline tab bar separator (alt symbol) in tab bar background colour

### ISSUE THREAD

**Issue by chipaca** [kovidgoyal/kitty#3664]
**Is your feature request related to a problem? Please describe.**

The powerline tab bar alt symbol is currently drawn with the foreground colour, but that seems to me to result in something that calls too much attention to itself, rather than just helping separate the tabs:

![image](https://user-images.githubusercontent.com/1543430/120009660-1c145a80-bfd4-11eb-9658-4ce853a0cc54.png)

**Describe the solution you'd like**

I think it would be better, barring it having its own colour setting, to draw it using the bar background colour instead:

![image](https://user-images.githubusercontent.com/1543430/120009788-4108cd80-bfd4-11eb-94d5-baa20ccf6398.png)

**Describe alternatives you've considered**

having its own setting for a colour would also work, but not sure if it's worth it?

**Additional context**

have i mentioned kitty rocks

**Comment by kovidgoyal** [comment]
Whether the foreground or the background works better depends on both the colors used for the tab bar and the users subjective color preferences. For example, with the default color scheme, background is black and foreground is less black so using background would actually have more contrast. 

What I suggest is have the code dynamically pick either the foreground or the background color based on which has less contrast with inactive_tab_background. Avoids using another conf option for something so small. 

Should be a simple patch, PR is welcome, code is in draw_tab_with_powerline()

**Comment by salmankhilji** [comment]
> What I suggest is have the code dynamically pick either the foreground or the background color based on which has less contrast with inactive_tab_background. Avoids using another conf option for something so small.
> 

+1
