### ISSUE TITLE
Background color missing in vim

### ISSUE THREAD

**Issue by marekmaskarinec** [kovidgoyal/kitty#3665]
**Describe the bug**
Background color disappearing in vim. (works as expected in st)

**To Reproduce**
1. Have vim setup with theme containing custom background color
2. Open a buffer longer than your screen
3. Scroll

**Screenshots**
![Peek 2021-05-29 13-46](https://user-images.githubusercontent.com/42782325/120069300-7e796380-c085-11eb-8e3f-27e06d9120a0.gif)

**Environment details**
Happens even in kitty without config.

```
kitty 0.20.1 created by Kovid Goyal
Linux main 5.10.25_1 #1 SMP 1616262869 x86_64
Void \r (\n) (\l)
Loaded config files: /home/marek/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity 0.6
```

**Additional context**
Vimrc:
```vim
call plug#begin()
Plug 'calviken/vim-gdscript3'
Plug 'luochen1990/rainbow'
Plug 'wadackel/vim-dogrun'
Plug 'hugolgst/vimsence'
Plug 'dhruvasagar/vim-table-mode'
Plug 'marekmaskarinec/vim-umka'
Plug '~/dev/vim-sheedoc'
Plug 'ollykel/v-vim'
Plug 'kovisoft/slimv'
call plug#end()

colorscheme dogrun
:set number

inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

:set tabstop=2

let g:slimv_swank_cmd = '! xterm -e sbcl --load /home/marek/.vim/plugged/slimv/slime/start-swank.lisp &'
let g:paredit_mode=0
```

**Comment by Luflosi** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim

**Comment by marekmaskarinec** [comment]
Thank you! That works.
