### ISSUE TITLE
"Ignoring unknown config key: open_url_modifiers" warning

### ISSUE THREAD

**Issue by browser-bug** [kovidgoyal/kitty#3667]
I'm on the last commit at the time of writing this issue. It appears that the `open_url_modifiers` option is not recognized anymore. It appears to be back to default behavior (i.e. `ctrl+shift`).

Output of kitty --debug-config
```
kitty 0.20.3 (39b3d3de0f) created by Kovid Goyal
Linux #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/bernardo/.config/kitty/kitty.conf
[149 21:28:32.212128] Ignoring unknown config key: open_url_modifiers
Running under: X11
```
Update:
I suppose this is related to the changelog of version `0.21.0`
- **Backward incompatibility**: The options to control which modifiers keys to
  press for various mouse actions have been removed, if you used these options,
  you will need to replace them with configuration using the new
  :ref:`mouse actions framework <conf-kitty-mouse.mousemap>` as they will be
  ignored. The options were: ``terminal_select_modifiers``,
  ``rectangle_select_modifiers`` and ``open_url_modifiers``.
  
 So are some details about the new mouse actions framework available in order to configure the option or is it still under development?

**Comment by kovidgoyal** [comment]
Yes, it has been superseeded, read the changelog in docs/changelog.rst

**Comment by kovasap** [comment]
Hit this too, looks like the docs at https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.open_url_modifiers are not updated.  Is there a doc page that describes this new feature on the web docs?

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/blob/master/kitty/options/definition.py#L437

Or build kitty locally and read man 5 kitty.conf

**Comment by kovasap** [comment]
Ok thanks.  Looks like ctrl+shift+left click opens urls like my previous `open_url_modifiers ctrl` did.  Following the examples, I added:

```
mouse_map ctrl+left click grabbed,ungrabbed mouse_click_url
```

which works for me!  Still a bit confused about what "grabbed" means in this context (and why the builtin `click_url_or_select`) doesn't seem to work for me.

**Comment by kovidgoyal** [comment]
ctrl+shift should work fine. And grabbed means the program running int he terminal has grabbed the mouse, aka, asked for mouse events.

**Comment by kovasap** [comment]
Ah ok makes sense!

**Comment by browser-bug** [comment]
Just a minor comment. The mapping proposed by @kovasap , at least on my hand, doesn't work as smoothly as the default `ctrl+shift+left` which seems to be left enabled only for legacy compatibility. When the `event-type` is ``release`` instead of ``click`` the whole process is fine. Using `click` prevents a link to be opened up when for instance I press the key combination without hovering first on the link, moreover is just a way slower process.

**Comment by rightaway** [comment]
@browser-bug What version are you seeing `kitty --debug-config` on? I don't have this command.

@kovidgoyal I see the documentation of the many new mouse actions but what's the way to get the old functionality back if using `open_url_modifiers shift`?

**Comment by rightaway** [comment]
@kovidgoyal I see the documentation of the many new mouse actions but what's the way to get the old functionality back if using `open_url_modifiers ctrl`?

**Comment by kovidgoyal** [comment]
Define the relevant mouse_maps

**Comment by rightaway** [comment]
@kovidgoyal I added `mouse_map left doubleclick grabbed,ungrabbed mouse_click_url` for double clicking on a link to open it but that doesn't work. Is it the wrong syntax?

**Comment by kovidgoyal** [comment]
You need to map the single click to no_op as well, otherwise it will
continue to work.
