### ISSUE TITLE
image is cleared when space still seems available in storage quota

### ISSUE THREAD

**Issue by dankamongmen** [kovidgoyal/kitty#3669]
**Describe the bug**

I understand a storage quota to be available for displayed images. I would expect that if I:

* display one image I_a, occupying let's say 1/4 of that space (1/4 total occupied)
* display a second image I_b, occupying 2/3 of the space (11/12 total occupied)
* destroy I_b (1/4 total occupied)
* display a third image I_c, occupying 2/3 of the space (11/12 total occupied)
* destroy I_c (1/4 total occupied)
... and so on ...

that at the end of this sequence, I_a would remain visible. it seems possible, however, to evict I_a from the storage quota (causing it to be hidden) by a series of displays + destroys that never exceed the quota. Basically, there seems to be fragmentation at work, or a ring buffer, or something.  **I'm not yet certain that I'm not inadvertently clearing the image myself, so if this seems impossible, don't spend much time on it.**

**To Reproduce**
1. Load an image
2. Load a secondary image
3. Destroy the secondary image
4. Repeat
5. The original image will at some point be cleared

I doubt that this works for all possible images. I noticed this while displaying `worldmap.png` 860x475 in the lower left corner, and running the video `notcursesIII.mkv` 1920x1080, 487 frames from the Notcurses source.

**Environment details**
OS: Debian unstable, Linux 5.12.7nlb

```
[schwarzgerat](0) $ kitty --debug-config
kitty 0.20.3 (39b3d3de0f) created by Kovid Goyal
Linux schwarzgerat 5.12.7nlb #1 SMP Wed May 26 13:14:22 EDT 2021 x86_64
Debian GNU/Linux 11 \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/dank/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=0, green=34, blue=17)
background_opacity    0.7
enable_audio_bell     False
font_family           Hack
initial_window_height (72, 'cells')
initial_window_width  (132, 'cells')
update_check_interval 0.0
[schwarzgerat](0) $ 
```

**Additional context**
I'll look into this, but first let me verify that this isn't due to some stupidity or oversight of mine. Just wanted to give you a heads-up.

**Comment by kovidgoyal** [comment]
I cant think of a mechanism for that. The cache is a flat file, not a
ring buffer. Fragmentation can occur, however, the cache limit is
enforced using the nominal size not the on disk size, and there is a
defrag that automatically cleans up the cache file when its size goes
beyond twice the nominal size.

**Comment by kovidgoyal** [comment]
closing, feel free to update if you have more evidence.
