### ISSUE TITLE
disable anti-aliasing

### ISSUE THREAD

**Issue by 257** [kovidgoyal/kitty#367]
i dunno how but kitty manages to escape this in my ```fonts.conf```:
```
	<match target="font">
		<edit name="antialias" mode="assign">
			<bool>false</bool>
		</edit>
	</match>
```
as a result, fonts are blur. any idea?

**Comment by kovidgoyal** [comment]
IIRC kitty does not respect that setting. kitty does not support bitmapped fonts and with scalable fonts antialiasing is required. That said, I wont refuse a PR to add support for that setting, but given that IMO non-antialiased scalable fonts look awful, it's not something I am going to spend time on.

**Comment by 257** [comment]
perhaps this should be kept open with a ```PR's are welcome``` tag or something.

**Comment by kovidgoyal** [comment]
I dont want to actually want to encourage people to implement this :) As I said, I wont refuse it, but I dont actually think it is a good idea.

**Comment by 257** [comment]
would you accept PR for supporting bitmap fonts?

**Comment by kovidgoyal** [comment]
No, bitmap fonts dont work with kitty's design (which calls for arbitrary, changeable font sizes). Bitmap fonts only work if you are willing to restrict what font sizes you allow.

**Comment by volth** [comment]
> IMO non-antialiased scalable fonts look awful,

there are plenty of people whose opinion is exactly the opposite

== xterm ==
![](http://i.imgur.com/Oa9w0MU.png)
== kitty ==
![](http://i.imgur.com/qD1txto.png)

And this is TTF font, not bitmap

**Comment by kovidgoyal** [comment]
And your point is? I never said everyone agreed with me, that is why I am willing to accept a PR for respecting the setting. And FYI kitty does not do subpixel aliasing.

**Comment by volth** [comment]
Yes, it might be something different.
But you see, on the ```xterm``` image the pixels of each letter have only 2 colors - background and foreground, while ```kitty``` introduces half-tones.

**Comment by kovidgoyal** [comment]
Yes, that is anti-aliasing. Anti-aliasing is different from subpixel anti-aliasing. Kitty does the former and does not do the latter.

**Comment by dwrodri** [comment]
Would you be opposed to a PR that added an option to toggle subpixel anti-alising?

**Comment by dwrodri** [comment]
Apologies, I might have been unclear in my previous post. I meant to ask if there's a way to disable anti-aliasing globally (the one kitty already does). I read both threads, and I've "ctrl+f"ed around the documentation to search for how to disable this. Am I just missing something obvious, or is this not something that can be disabled?

**Comment by Luflosi** [comment]
Oh, sorry, I thought you meant sub-pixel anti aliasing, my bad. I don't know if @kovidgoyal would want an option to toggle anti-aliasing, we'll have to wait for his answer.

**Comment by kovidgoyal** [comment]
I already said I am fine with an option for turning off anti-aliasing.

**Comment by petrmanek** [comment]
Bumping this thread. Anyone working on a PR for this feature?

**Comment by jaccc** [comment]
Microsoft TTF fonts look fine without anti-aliasing.

**Comment by jaccc** [comment]
bug still exists in 0.17.2

**Comment by ReneFroger** [comment]
> anti-alias



> Yes, that is anti-aliasing. Anti-aliasing is different from subpixel anti-aliasing. Kitty does the former

@kovidgoyal how do you enable anti-aliasing? It's not described in the Kitty documentation. All my fonts are being displayed as smoothened.
