### ISSUE TITLE
[dev] `Linking kitty/fast_data_types` step slow

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3675]
Hello!

Development is slowed down on my machine by how long the `Linking kitty/fast_data_types` step takes.

If I change no lines of code, but just add a line of whitespace to any C file (e.g. `kitty/desktop.c`) and run `time make -j9`, I get…

```
python3 setup.py 
CC: gcc (10, 2)
[1/1] Compiling kitty/desktop.c ... done
[1/1] Linking kitty/fast_data_types ... done

real	0m15.456s
user	0m15.073s
sys	0m0.470s
```

This seems very slow to me, compared to the equal operation in FontForge. Any ideas for speeding it up?

**Comment by kovidgoyal** [comment]
Something is broken on your system, after making a whitespace
change to desktop.c on my system::

```
time make debug                                                                                                  master 
python3 setup.py build  --debug
CC: gcc (11, 1)
[1/1] Compiling kitty/desktop.c ... done
[1/1] Linking kitty/fast_data_types ... done

real	0.644
user	0.536
sys	0.127
maxmem	47 MB
faults	0
```

that's under a second.

**Comment by ctrlcctrlv** [comment]
Interesting. I opened this because it happened on my old Arch Linux system as well. Hmm…

**Comment by kovidgoyal** [comment]
I'm on arch as well, FYI.

**Comment by ctrlcctrlv** [comment]
It's the difference between `time make -j9` and `time make debug -j9`. Thanks.

```
python3 setup.py build  --debug
CC: gcc (10, 2)
[1/1] Compiling kitty/desktop.c ... done
[1/1] Linking kitty/fast_data_types ... done

real	0m0.639s
user	0m0.518s
sys	0m0.132s
```
