### ISSUE TITLE
Can't seem to set window title via `--title` or using `title` in a session file

### ISSUE THREAD

**Issue by fenetikm** [kovidgoyal/kitty#3676]
**Describe the bug**
I am trying to open a new window using a shell (zsh) script and I can't seem to set the title to a static value. It seems to just end up as whatever is running in the shell e.g. neovim. I have set `DISABLE_AUTO_TITLE=true` in my .zshrc.

This used to work before updating kitty recently (not sure which version I came from, apologies).

Using kitty 0.20.3.

EDIT: ok, I have checked, it works fine in 0.19.3.

**To Reproduce**
Script is as follow:
```
#!/bin/zsh

/Applications/kitty.app/Contents/MacOS/kitty --title="vimwiki" --config="/Users/mjw/.config/kitty/kitty.conf" --session="/Users/mjw/.config/kitty/vimwiki_session" --directory="/Users/mjw/vimwiki" &
```

Contents of `vimwiki_session`:
```
cd ~/vimwiki
title vimwiki
launch /bin/zsh -c "nvim index.md; /bin/zsh"
```
...and then the window title ends up as `zsh`.

If I change the launch line to `launch nvim index.md` then the window title ends up as `nvim`

I I change to the config to `NONE` I still get zsh as the window title.

**Environment details**
OS: macOS Catalina

**Comment by kovidgoyal** [comment]
Use

launch --title=whatever 

in your session file. It's quite possible that the standalone title
setting no longer works since the session file got full support for
launch syntax
