### ISSUE TITLE
How to increase stack size in kitty terminal?

### ISSUE THREAD

**Issue by j0k4rX** [kovidgoyal/kitty#3677]
Hi @kovidgoyal,
I just wanted to know how to increase stack size in the kitty terminal for cpp programs.
should I include this code ```ulimit -s unlimited``` in kitty.conf? 
or in .bashrc in the home directory?

**Comment by kovidgoyal** [comment]
You dont increase stack size in a terminal. You do it in a shell.

**Comment by j0k4rX** [comment]
@kovidgoyal if I am using only kitty terminal, which one will be the shell then?

**Comment by SolitudeSF** [comment]
probably bash. question you're asking isn't related to terminal at all.
