### ISSUE TITLE
Add support for OSC 9;4 for progress reporting

### ISSUE THREAD

**Issue by dancojocaru2000** [kovidgoyal/kitty#3679]
Windows Terminal adopted ConEmu's OSC 9;4 progress reporting escape sequence. I think it would be useful to add this in Kitty as well (and keep only OSC 99 or maybe add OSC 777 for notifications #1474).

I'm not sure if Kitty should display the progress in a specific way in the terminal itself (Windows Terminal replaces the icon in the tab with a circular progress bar), but the OS specific way to report progress should probably be used in order to show the progress in the taskbar/dock:

![Progress on Windows Task Bar](https://user-images.githubusercontent.com/9626761/120374041-b6043c00-c321-11eb-9233-e12f18920bf6.png)
![Windows Terminal showing the progress inside the tab](https://user-images.githubusercontent.com/9626761/120374590-696d3080-c322-11eb-8454-f38b72384c8e.png)

While there wasn't much progress since 7 months ago, [terminal-wg discussed this too in issue 29](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/29).

Here is the Windows Terminal pull request describing the sequence: [microsoft/terminal#8055](https://github.com/microsoft/terminal/pull/8055).

**Comment by kovidgoyal** [comment]
I dont see the point. Only windows has any standard way of showing
progress and kitty does not run on windows. So what would kitty do with
the progress reports?

**Comment by dancojocaru2000** [comment]
Unity's D-Bus Launcher API is a de-facto standard on Linux. KDE Plasma, for example, supports it, and so does GNOME with the dash to dock plugin.

As for Mac, I'm not sure why I had a feeling that there was a built in way to do it.

**Comment by kovidgoyal** [comment]
That API is supported only by GNOME/KDE as far as I know. Most kitty users use other window managers. The recommended way to use it is via libunity which is deprecated and not even packaged on say Arch. Qt for instance has no support for it as far as I know. Doesnt seem like much of a standard. According to its own documentation:

https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry

the dbus api is not stable and not recommended for use.

And then there is the problem of the escape code clash. Notifications are more widely supported and useful. Not going to repurpose an existing escape code number for a less widely used feature.
