### ISSUE TITLE
don't beep!

### ISSUE THREAD

**Issue by 257** [kovidgoyal/kitty#368]
i have ```xset b off``` and it works in my other terminal emulator ```st```. ```kitty```, or perhaps ```GLFW``` seems to not honer the setting!

**Comment by nealot** [comment]
Setting "enable_audio_bell no" in your kitty.conf should resolve this issue.

**Comment by kovidgoyal** [comment]
As far as I know, st does not respect that setting either, it just defaults to having the bell off. Looking at the st sourcecode, it unconditionally calls XkbBell if bellvolume from its config is non-zero. glfw and therefore kitty also call XkbBell.
