### ISSUE TITLE
[graphics API] please add a way to call `get_free_client_id`

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3681]
As different programs can interact with the graphics protocol, the idea that most programs should be deciding on their own image ID's is, I think, not right.

For example, imagine running `kitty +icat` immediately followed by another program with kitty graphics support. If both assume they can start counting from `1` this will result in bad consequences.

There should be a way to query next available image ID, or ask `kitty` for a free image ID even if it's not necessarily the next free one.

**Comment by kovidgoyal** [comment]
There is: https://sw.kovidgoyal.net/kitty/graphics-protocol.html#requesting-image-ids-from-the-terminal

**Comment by ctrlcctrlv** [comment]
Oh, thank you. Sorry, overlooked that, didn't understand exactly what image numbers were for  :-)
