### ISSUE TITLE
mouse-draggable window margin/padding

### ISSUE THREAD

**Issue by rinkjames** [kovidgoyal/kitty#3683]
As far as I can tell this hasn't been covered elsewhere. I've disabled the titlebar using `hide_window_decorations titlebar-only` in my kitty.conf file, but now I can't move the os_window using my mouse. I do something very similar in atom, but I use a package called [no-title-bar](https://atom.io/packages/no-title-bar) to enable 'liberal window dragging' which means I can drag the window from any empty space, like in the below image.

Is something like this possible in kitty, making use of `window_margin` or `window_padding` maybe?

<img width="855" alt="dad294de-cd24-11e6-9fee-6e4809cc86a7" src="https://user-images.githubusercontent.com/13288151/120455338-f781ff00-c394-11eb-99b1-cdf4f902caa2.png">

**Comment by Luflosi** [comment]
See https://github.com/kovidgoyal/kitty/issues/84#issuecomment-768214513.

**Comment by rinkjames** [comment]
Thanks, I was able to drag it. However, the draggable space with `hide_window_decorations titlebar-only` is _really_ tiny from what I can tell (see short video). It also sits outside the window and is invisible. I couldn't click the correct area consistently even when focussing on what I'm doing.

So I mainatin that dragging from window margin or window padding would be significantly better UX. Not a viable feature?

https://user-images.githubusercontent.com/13288151/120467215-39fd0900-c3a0-11eb-93db-2052d96d2740.mov

**Comment by Luflosi** [comment]
I found a way to implement this. I will need to write some code to determine if the drag started in the padding or margin, then it should work. I'll try to implement it this weekend. If I haven't made a PR in two weeks yet, please remind me again.

**Comment by kovidgoyal** [comment]
while I have no objection to implementing dragging from outside margins
(inside margins will probably someday be used to resize windows via
dragging), have you considered simply, not hiding the titlebar, instead
making it the window background color and hiding the buttons.

**Comment by rinkjames** [comment]
Do you mean using `macos_titlebar_color background`? Ideally there'd be a solution that doesn't affect `background_opacity` but I'd be happy with this for my purpsoses, except how do I hide the buttons?

**Comment by kovidgoyal** [comment]
maybe I am misremembering, or maybe there was a setting for hiding the
buttons, but then Apple broke it and it was removed.

**Comment by rinkjames** [comment]
The other thing I just noticed is that even if the buttons were hidden, tabs would display in a row underneath the titlebar. Basically, I'm looking to make my kitty window look like my atom window tabs at top and with a reasonably-sized mouse-draggable space, e.g. like the window margins or padding etc. See image of windows side-by-side:

<img width="771" alt="Screenshot 2021-06-02 at 13 24 04" src="https://user-images.githubusercontent.com/13288151/120472316-058c4b80-c3a6-11eb-9525-bc0f6c4b0709.png">

**Comment by rinkjames** [comment]
> I found a way to implement this. I will need to write some code to determine if the drag started in the padding or margin, then it should work. I'll try to implement it this weekend. If I haven't made a PR in two weeks yet, please remind me again.

Hey, how is that PR going?

**Comment by towry** [comment]
> Thanks, I was able to drag it. However, the draggable space with `hide_window_decorations titlebar-only` is _really_ tiny from what I can tell (see short video). It also sits outside the window and is invisible. I couldn't click the correct area consistently even when focussing on what I'm doing.
> 
> So I mainatin that dragging from window margin or window padding would be significantly better UX. Not a viable feature?
> 
>  Screen.Recording.2021-06-02.at.12.26.40_new2.mov

Off-topic. 

Do you mind sharing the conf how to make the kitty looks like in the video? mine is weird like this:

![截屏2022-11-30 12 26 13](https://user-images.githubusercontent.com/8279858/204708270-9cff3e80-47ce-400e-bcc2-31c97f2d6b18.png)

**Comment by thi-marques** [comment]
For Linux users, in Fedora and Ubuntu is possible to drag by clicking in anywhere of the window while holding the `Super` key.

**Comment by raydenz** [comment]
> For Linux users, in Fedora and Ubuntu is possible to drag by clicking in anywhere of the window while holding the `Super` key.

it works on arch linux thank you
i want to find the shortcut to maximize and reduce the window

**Comment by thi-marques** [comment]
> > For Linux users, in Fedora and Ubuntu is possible to drag by clicking in anywhere of the window while holding the `Super` key.
> 
> it works on arch linux thank you i want to find the shortcut to maximize and reduce the window

In Gnome you can set them whatever you want on:
Settings -> Keyboard -> View and Customize Shortcuts

These are the defaults:

Restore window - `Super + down`
Maximize window - `Super + up`
Toggle maximization state - `Alt + F10`
Resize window - `Alt + F8`

**Comment by PrethamMuthappa** [comment]
> For Linux users, in Fedora and Ubuntu is possible to drag by clicking in anywhere of the window while holding the `Super` key.

Thanks , this seems to work for me :)

**Comment by tdarshana** [comment]
You can try this for MacOS - 
https://www.reddit.com/r/KittyTerminal/comments/1710di6/comment/k3q5r8q

in brief,
set `hide_window_decorations titlebar-only` in the kitty.conf.
Run `defaults write -g NSWindowShouldDragOnGesture YES`
Restart Kitty.
Now you should be able drag the window by holding ctrl+cmd

**Comment by kovidgoyal** [comment]
Closing as one can now drag OS windows on both macOS and Linux using OS provided facilities so no need to implement this in kitty itself.

**Comment by caiodelgadonew** [comment]
> You can try this for MacOS - https://www.reddit.com/r/KittyTerminal/comments/1710di6/comment/k3q5r8q
> 
> in brief, set `hide_window_decorations titlebar-only` in the kitty.conf. Run `defaults write -g NSWindowShouldDragOnGesture YES` Restart Kitty. Now you should be able drag the window by holding ctrl+cmd

Did you manage to get it to work on macos? 
I simply cant move the window... only resize it

**Comment by chen78** [comment]
> hide_window_decorations titlebar-only

it doesn't work for me

**Comment by lb-oai** [comment]
> You can try this for MacOS - [reddit.com/r/KittyTerminal/comments/1710di6/comment/k3q5r8q](https://www.reddit.com/r/KittyTerminal/comments/1710di6/comment/k3q5r8q)
> 
> in brief, set `hide_window_decorations titlebar-only` in the kitty.conf. Run `defaults write -g NSWindowShouldDragOnGesture YES` Restart Kitty. Now you should be able drag the window by holding ctrl+cmd

Note this does *only* work with `hide_window_decorations titlebar-only`; it does *not* work with `hide_window_decorations yes` or `hide_window_decorations titlebar-and-corners`. I would really prefer to use the "yes" option but have the window be draggable.
