### ISSUE TITLE
font_size specified in secondary config not handled properly

### ISSUE THREAD

**Issue by khughitt** [kovidgoyal/kitty#3689]
**Describe the bug**

Attempting to modify the `font_size` setting from a secondary (included) config does not take effect.

Calling `kitty --debug-config` does show the expected value, but no matter what the value is set to, the font size is unchanged.

Setting the value in the main kitty.conf, however, works fine.

**To Reproduce**

_kitty.conf_:

```
include test.conf
```

_test.conf_:

```
font_size: 20.0
```

Try modifying the specified font-size to different values; it will not have any effect.

Verify that the secondary config setting was properly parsed with `kitty --debug-config`

**Environment details**

```
kitty 0.20.3 created by Kovid Goyal
Linux europa 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/keith/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background                 Color(red=40, green=44, blue=52)
bold_font                  Fira Code Bold Nerd Font Complete
bold_italic_font           Source Code Pro Bold Italic
color0                     Color(red=92, green=99, blue=112)
color1                     Color(red=224, green=108, blue=117)
color10                    Color(red=152, green=195, blue=121)
color11                    Color(red=209, green=154, blue=102)
color12                    Color(red=97, green=175, blue=239)
color13                    Color(red=198, green=120, blue=221)
color14                    Color(red=86, green=182, blue=194)
color15                    Color(red=62, green=68, blue=82)
color2                     Color(red=152, green=195, blue=121)
color3                     Color(red=229, green=192, blue=123)
color4                     Color(red=97, green=175, blue=239)
color5                     Color(red=198, green=120, blue=221)
color6                     Color(red=86, green=182, blue=194)
color7                     Color(red=171, green=178, blue=191)
color8                     Color(red=75, green=82, blue=99)
color9                     Color(red=190, green=80, blue=70)
cursor                     Color(red=171, green=178, blue=191)
cursor_stop_blinking_after 0
cursor_text_color          Color(red=92, green=99, blue=112)
default_pointer_shape      arrow
enable_audio_bell          False
font_family                Fira Code Retina Nerd Font Complete
font_features              {'FiraCode-Retina': ('+ss02', '+ss03', '+ss04', '+ss05', '+zero')}
font_size                  20.0
foreground                 Color(red=171, green=178, blue=191)
italic_font                Source Code Pro Italic
scrollback_lines           8192
selection_background       Color(red=171, green=178, blue=191)
selection_foreground       Color(red=92, green=99, blue=112)
strip_trailing_spaces      smart
```

**Additional context**

FYI, I also tried using the most recent version of kitty from Github, but in that case, none of my external config files (including my `colors.conf` which is handled fine now) appear to be loaded.

Thanks for all of your hard work on kitty! It is much appreciated.

**Comment by SeluMesu** [comment]
don't put colon I think it should be font_size 20.0 not font_size: 20.0

**Comment by SeluMesu** [comment]
don't put colon it should be **font_size 20.0**

**Comment by khughitt** [comment]
Whoops! Apologies, there should not have been a colon there -- I accidentally added it when made the mistake of manually typing the example conf.

The problem persists even without the colon. (edited example in original post to remove it as well.)

**Comment by khughitt** [comment]
Okay, I think I tracked down the issue -- it appears to relate to how I was including the secondary config file in my actual use:

`#include ${HOSTNAME}.conf`

The problem is that, depending on how I launch kitty, the `HOSTNAME` variable that I define in my zsh config may or may not be exported:

- launching kitty from another kitty terminal works
- launching kitty from i3 or rofi results in the secondary config not being parsed

Looks like I need to define HOSTNAME at an earlier point / using a different approach.

You can keep this issue closed; only posting these notes here in case it helps anyone else.
