### ISSUE TITLE
Goto Layout

### ISSUE THREAD

**Issue by arubertoson** [kovidgoyal/kitty#369]
I've only had a quick look but I don't think there's any support for goto layout. What I'm looking for is a possibility for:

```bash
# kitty.conf
map ctr+shift+s    goto_layout stack
map ctr+shift+g    goto_layout grid
# just as the goto_tab
map ctrl+shift+1   goto_tab 1 
```

Would that be a trivial implementation? Or is there any other methods to achieve the same results?

**Comment by kovidgoyal** [comment]
Well, there is `ctrl+shift+l` to switch layouts. I typically only have a couple of layouts active, so I have never felt the need to have dedicated shortcuts for individual layouts. See enabled_layouts in the sessions section of the readme. 

But yeah, it should be pretty trivial to implement.
