### ISSUE TITLE
Support for bitmapped fonts.

### ISSUE THREAD

**Issue by pveentjer** [kovidgoyal/kitty#3690]
Kitty doesn't support bitmapped fonts.

Kitty is very fast if properly configured. But the font options are just horrible; I can't watch at my terminal and I'm looking 8+ hours a day at my terminal so the font needs to be perfect.

https://int10h.org/oldschool-pc-fonts/
https://github.com/Tecate/bitmap-fonts

But even terminus looks like a disgrace on Kitty.

So currently Kitty isn't a realistic option and I'm using qterminal.

**Comment by kovidgoyal** [comment]
This has already been discussed, please dont open duplicate issues.

**Comment by pveentjer** [comment]
Just add a flag to allow for it.

https://aur.archlinux.org/cgit/aur.git/tree/Allow-bitmap-fonts.patch?h=kitty-bitmap

Kitty just looks aweful.

**Comment by kovidgoyal** [comment]
On Sat, Jun 05, 2021 at 10:04:40PM -0700, Peter Veentjer wrote:
> Just add a flag to allow for it.
> 
> https://aur.archlinux.org/cgit/aur.git/tree/Allow-bitmap-fonts.patch?h=kitty-bitmap
> 
> Kitty just looks aweful. 

Then feel free not to use it. And stop wasting other people's time.
