### ISSUE TITLE
Different font size based on different display/output

### ISSUE THREAD

**Issue by kantord** [kovidgoyal/kitty#3697]
**Is your feature request related to a problem? Please describe.**
At home I use my laptop with an external screen, but on the go I use it with it's built in screen. Sometimes I use both screens at the same time. While the 2 screens have similar DPI in my case, I would still need different font scaling/font size, since generally when I use the external screen, it's much farther and more difficult to see.

**Describe the solution you'd like**
I would like to be able to either define a custom font size for different displays, or define scaling factors for each display. Preferably these would be applied without restarting kitty, and in an ideal world it would be applied when I move a window from one screen to the other.

**Describe alternatives you've considered**
Having some kind of external script that tells individual kitty instances to change their font size, based on the display they are on.

**Additional context**
I use Arch Linux with i3 (X11)

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in implementing per display font size
configuration. As for external scripts to do it, I am sure you can cook
up something on your own using
https://sw.kovidgoyal.net/kitty/remote-control.html
