### ISSUE TITLE
keys for 'delete everything before cursor'

### ISSUE THREAD

**Issue by rinkjames** [kovidgoyal/kitty#3698]
I can't seem to find the correct key mapping for ctrl-u, which as far as I understand is supposed to delete everything before the cursor in zsh. In kitty this seems to clear the entire line, including words/characters after the cursor. What's the correct config for this?

**Comment by kovidgoyal** [comment]
This is a function of the shell not the terminal emulator. Configure it
in zshrc. And make sure your TERM env var is xterm-kitty and the kitty
terminfo files are present on the computer zsh is running on.
