### ISSUE TITLE
Devanagari fonts are not rendered properly

### ISSUE THREAD

**Issue by quaintdev** [kovidgoyal/kitty#3701]
First of all, great job on Kitty! I love it.

**Describe the bug**
If you paste below text in kitty it is not rendered properly
```
देव तारी त्यास कोण मारी
```

**Screenshots**
![image](https://user-images.githubusercontent.com/59229571/121398764-54704d00-c973-11eb-8737-cf2656271ea8.png)

**Environment details**
`I am using kitty on debian

**Additional context**
Am I missing something? Do I need to configure some fonts? 

Thanks in advance.

**Comment by kovidgoyal** [comment]
Sadly, support for complex scripts is not possible in kitty, as kitty is
designed to render text as a grid of equal sized cells, each of which is
rendered in parallel on the GPU for performance. This means that complex
scripts that arent monospaced will not render correctly.
