### ISSUE TITLE
Support `send_text` in startup sessions

### ISSUE THREAD

**Issue by francislavoie** [kovidgoyal/kitty#3702]
**Is your feature request related to a problem? Please describe.**
When I first boot my machine, there's certain things I'd like to prepare for some of the tabs/windows I open up via my session file. Some of those things aren't possible until after I've done something else on my system, e.g. unlocking my SSH key (which requires copying the password from my password manager first), or connecting to a VPN to gain access to SSH to some machines.

What I'd like is to be able to send some text to the command prompt _but not run it_ so that when I go to that tab/window, I can then just hit enter to do the thing. For example, send the text `ssh francis@some-server` to my tab named `some-server`, so that after being connected to the VPN, I can go to that tab and just hit enter and have it happen on my own terms.

**Describe the solution you'd like**
It would be great if I could do this in the session file:

```
new_tab some-server
cd ~
launch bash
send_text all ssh francis@some-server
```

Which would launch bash, then type out `ssh francis@some-server`, and then that tab would contain at my prompt:

```
francis@laptop:~$ ssh francis@some-server
```

With the cursor at the end, waiting for me to hit enter.

**Describe alternatives you've considered**
I tried using `send_text` immediately after a `launch` in the session file, but that fails. Clearly that's not supported, and it looks like session files have a very primitive set of things they can do according to https://github.com/kovidgoyal/kitty/blob/0bbc4462fd294bdf63b89389f6909332e87432fa/kitty/session.py#L106

I scoured the docs, but couldn't really find any options for `launch` that would let me do this either. I don't think `bash` supports specifying some text to put at the prompt either. I dunno.

Maybe I could make bash invoke a script which does a `read` to wait for me to hit enter before doing the thing, but that'd require having scripts in separate files (or one fancy script with arguments, etc) instead of just having this all done in the session file. :thinking: Maybe there's some obvious easy solution that I'm missing.

**Comment by kovidgoyal** [comment]
launch bash -c "sleep 5s; /bin/echo -n whatever; bash --login"

**Comment by francislavoie** [comment]
That doesn't work, it just flashes "whatever" on the screen then bash replaces it, with an empty prompt.

**Comment by kovidgoyal** [comment]
launch bash -c "sleep 5s; /bin/echo -n whatever & bash --login"

**Comment by francislavoie** [comment]
That does the exact same thing. Flashes "whatever" on the screen, then replaces it with a bash shell with an empty prompt.

**Comment by kovidgoyal** [comment]
Sorry too early in the morning for me:
bash -c "bash -c 'sleep 3s; echo -n whatever' & bash --login"

**Comment by francislavoie** [comment]
Aha! That does work. Neat!

**Comment by francislavoie** [comment]
Spoke too soon. That _displays_ `whatever` but it's not part of the prompt. If I hit enter, it doesn't try to run "whatever" as a command.

**Comment by kovidgoyal** [comment]
Never mind, I was overthinking things

bash -c "echo -n whatever; read; whatever"

**Comment by francislavoie** [comment]
That doesn't work too well either, cause it doesn't actually give me a bash shell to return to.

Anyways, did some more digging and found a viable solution. Bit annoying because it requires some outside setup, but it works well.

Need to install `expect` (my system didn't have it anyway, so `sudo apt install expect`), then made a script like this (saved it to `/usr/local/bin/filledprompt`):

```bash
#!/usr/bin/expect

#trap sigwinch and pass it to the child we spawned
#this allows the gnome-terminal window to be resized
trap {
 set rows [stty rows]
 set cols [stty columns]
 stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

set arg1 [lindex $argv 0]

# Get a Bash shell
spawn -noecho bash

# Wait for a prompt
expect "$ "

# Type something
send $arg1

# Hand over control to the user
interact

exit
```

Credit to https://askubuntu.com/a/16836/718886

Then in my session file, I can do:

```
launch filledprompt "ssh whatever"
```

And I get a prefilled bash prompt. :+1:

**Comment by kovidgoyal** [comment]
bash -c "echo -n whatever; read; whatever; bash --login"

**Comment by kovidgoyal** [comment]
launch bash -c "echo -n whatever1; read; whatever1; bash --login"
launch bash -c "echo -n whatever2; read; whatever2; bash --login"

**Comment by dj-foxxy** [comment]
> launch bash -c "echo -n whatever1; read; whatever1; bash --login" launch bash -c "echo -n whatever2; read; whatever2; bash --login"

Thanks for getting back to me. I might be doing something wrong but I have to manually press return to execute the command. With `send_text` I can send a `\r` at the end of the command to execute it. Not sure how to do that here.

**Comment by kovidgoyal** [comment]
On Mon, Jun 20, 2022 at 07:58:23AM -0700, Peter Sutton wrote:
> > launch bash -c "echo -n whatever1; read; whatever1; bash --login" launch bash -c "echo -n whatever2; read; whatever2; bash --login"
> 
> Thanks for getting back to me. I might be doing something wrong but I have to manually press return to execute the command. With `send_text` I can send a `\r` at the end of the command to execute it. Not sure how to do that here.

If what you want to do is run a command and then get a prompt, all you
need is

bash -c "whatever; bash --login"

**Comment by dj-foxxy** [comment]
Thanks again but this isn't quite the same, e.g., after `whaterver` has ran pressing the up arrow doesn't bring back the same `whatever` command. This is our main use case, launch a of tools and make it easy to edit and relaunch.

**Comment by kovidgoyal** [comment]
launch bash -c "history -s whatever; whatever; bash --login"

**Comment by dj-foxxy** [comment]
Tried a couple of variations of this but nothing worked.

```
launch bash -c 'history -s htop; htop; history -a; bash'
launch bash -c 'history -s python; python; history -a; bash'
```

**Comment by kovidgoyal** [comment]
Read the bash man page so you understand what you are doing.
This will work

bash -ic "history -s meow; history -a; bash --login"


meow will be the first item in history.

**Comment by dj-foxxy** [comment]
Thanks again. I'm gonna go with @francislavoie's `expect` solution because it's more general (e.g., we actually use zsh).

**Comment by kovidgoyal** [comment]
The same thing will work with zsh as well, you just need to change the
commands to those zsh uses to update its history file.
