### ISSUE TITLE
Please support non-interactive mode in the diff kitten

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#3704]
**Is your feature request related to a problem? Please describe.**
I'd like to show differences between two files on the console in non-interactive mode. i.e., show the differences in the terminal without entering a pager/viewer.  Kind of like `icdiff` and [delta](https://github.com/dandavison/delta).

**Describe the solution you'd like**
Something like a `--non-interactive` command option to the kitten.

**Describe alternatives you've considered**
I currently use delta in my workflow.  Unfortunately, delta 0.8 broke my workflow where I can no longer diff using fd's like this:

```
$ delta -s <(seq 10) <(seq 15)

comparing: /dev/fd/63 ⟶   /dev/fd/62
───────────────────────────────────────────────────────────────────────────────

───┐
8: │
───┘
│ 8  │8                                │ 8  │8
│ 9  │9                                │ 9  │9
│ 10 │10                               │ 10 │10
│    │                                 │ 11 │11
│    │                                 │ 12 │12
│    │                                 │ 13 │13
│    │                                 │ 14 │14
│    │                                 │ 15 │15
```

**Additional context**
Our diff kitten also does not yet support fds.  My workflow involves showing a diff with the existing file when overwriting an existing file without _explicity_ creating a tmp file.  If you choose to implement this feature request, please also make the kitten be able to read from fds.

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but patches are welcome.
