### ISSUE TITLE
macOS Big Sur: Notifications Not Working

### ISSUE THREAD

**Issue by AprilArcus** [kovidgoyal/kitty#3707]
I used the `printf '\x1b]99;;Hello world\x1b\\'` command to send a test notification, and was prompted to give kitty permission to display a notification. I granted permission.

Subsequent attempts to issue the test notification command produce no notification.

macOS 11.3, kitty 0.20.3

**Comment by numbcoder** [comment]
Just tested on my MBP, it works well
macOS 11.4, kitty 0.20.3

**Comment by kovidgoyal** [comment]
IIRC now-a-days Apple requires applications to be signed/notarized for
notifications. And there are a bunch of notification policies that
control how notifications are displayed. So check that you are
using the official kitty build from
https://sw.kovidgoyal.net/kitty/binary.html and that your notification
policies are set to allow notifications from kitty
