### ISSUE TITLE
kitty @ focus-tab --match index:2

### ISSUE THREAD

**Issue by daniel-pfeiffer** [kovidgoyal/kitty#3708]
Since the only information documented as addable to a tab-title is the index, the above syntax would be very handy!

_Trying to build, I got harfbuzzed :-o and replacing boss.pyc by a modified boss.py has no effect.  Actually the whole .local/kitty.app/lib/python3.9/kitty directory seems superfluous (removed it and kitty still works.)  Not sure what magic that is._

So, may I suggest adding/adapting these lines to boss.match_tabs?  Untested, and not sure about the 2nd line, the like of which I searched for on StackOverflow.  Apparently something intuitive like `self.all_tabs[pat]` would have made people's lives too easy:
```python
        elif field == 'index':
            next((tab for i, tab in enumerate(self.all_tabs) if i == pat), None)
            if tab:
                yield tab
                found = True
```

**Comment by kovidgoyal** [comment]
kitty loads its python code from a single mmapped file as optimized
bytecode for performance. So you cant monkeypatch it easily. If you
want to you can modify the python only parts of kitty, as described
here: https://github.com/kovidgoyal/kitty/blob/master/docs/build.rst
in the note near the top
