### ISSUE TITLE
Why is it valid to half-select an emoji?

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3709]
![image](https://user-images.githubusercontent.com/838783/121734825-4893a080-cac3-11eb-8f5c-fc3cff462e2d.png)

**Comment by kovidgoyal** [comment]
Why not? What problem does it cause? It's a bunch of extra code for a relatively minor/harmless thing.

**Comment by ctrlcctrlv** [comment]
I find it annoying that selecting the right half of the emoji only copies a space. I wouldn't mind were in consistent, that if either half is selected it's selected. As it stands I have to look carefully to make sure that the left half is selected.

**Comment by kovidgoyal** [comment]
Not a problem that's ever bothered me, but if you find it annoying, a
patch is most welcome, relevant code is in mouse.c and screen.c, you
would need to mostly adjust screen_start_selection() and
screen_update_selection() under EXTEND_CELL
