### ISSUE TITLE
Unicode input tool name mode selection-by-index does not work as documented

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3710]
**Describe the bug**
The [doc](https://sw.kovidgoyal.net/kitty/kittens/unicode-input.html) states…

> In `Name` mode you instead type words from the character name and use the arrow keys/tab to select the character from the displayed matches. You can also type a space followed by a period and the index for the match if you don’t like to use arrow keys.

This doesn't work. I am attempting to select "face palm", index z.

![Peek 2021-06-11 14-57](https://user-images.githubusercontent.com/838783/121736518-ab863700-cac5-11eb-9813-73e6fd914f28.gif)

**Environment details**
```
kitty 0.19.1 (5d3ac649ba) created by Kovid Goyal
Linux laptop 5.12.9-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 03 Jun 2021 11:36:07 +0000 x86_64
Arch Linux \r (\l)
Loaded config files: /home/fred/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=38, green=38, blue=38)
bold_font             Fira Code Medium
cursor_blink_interval 0.0
disable_ligatures     2
enable_audio_bell     False
font_family           Fira Code Medium
font_size             12.0
visual_bell_duration  0.2
```

**Additional context**
Confirmed, also happens with `--config NONE`.

**Comment by kovidgoyal** [comment]
dup of #3219
