### ISSUE TITLE
Window padding width changes after opening new window

### ISSUE THREAD

**Issue by kidonng** [kovidgoyal/kitty#3714]
**Describe the bug**
When kitty's window size is at certain numbers, the window padding width will become wider after opening a new window.

**To Reproduce**
1. Launch kitty
2. Resize kitty and open a new window
3. Repeat until the problematic window size appears

**Screenshots**
Initial state:

![Screen Shot 2021-06-12 at 16 58 14](https://user-images.githubusercontent.com/44045911/121771180-6551d600-cba0-11eb-9aa2-6ff18093adc1.png)

After opening a new window:

![Screen Shot 2021-06-12 at 16 58 17](https://user-images.githubusercontent.com/44045911/121771171-53703300-cba0-11eb-9b38-9c63f53dc9e9.png)

**Additional context**

The screenshot shown above is using `{"window-size": [526, 459]}` on a 1920x1080 screen.

Font size seems to affect this issue as well. For example, the issue also appears with the default window size (640x480) and a font size of 13.

**Comment by kovidgoyal** [comment]
thats not padding, thats the leftover space when the number of cells *
cell_size is not an exact multiple of the available space. How much
extra is lft over depends on the cell and window sizes.
