### ISSUE TITLE
strip_trailing_spaces no longer accepts auto as a value

### ISSUE THREAD

**Issue by gotgenes** [kovidgoyal/kitty#3715]
**Describe the bug**
kitty no longer accepts `auto` as a valid configuration value for `strip_trailing_spaces` in `kitty.conf`.

**To Reproduce**
1. Set `strip_trailing_spaces auto` in `kitty.conf`
2. Start kitty version 0.21.0
3. Observe the following error

   ```
   Errors in kitty.conf

   11:The value auto is not a valid choice for strip_trailing_spaces in line: strip_trailing_spaces auto

   Press Enter to close.
   ```

**Additional context**

It's possible [this changeset for kitty 0.21.0](https://github.com/kovidgoyal/kitty/commit/6d7df1c5e8515e64e700a17f3deacfcb00eca43f#diff-d1c3f030af2e7cc7b46e6323c083d893438d6e67771362af6724cf2364ccc8d9R1134) (see also the [typings](https://github.com/kovidgoyal/kitty/commit/6d7df1c5e8515e64e700a17f3deacfcb00eca43f#diff-d7571714fc118ef48dd0969f877adcbeb32ff250b1f09b9415ced1d903fd1e0bR24)) changed the value name from `auto` to `smart`. This change does not appear in [the CHANGELOG](https://sw.kovidgoyal.net/kitty/changelog.html) for 0.21.0.

**Comment by kovidgoyal** [comment]
It have never accepted auto, see the original commit where it was created: https://github.com/kovidgoyal/kitty/commit/5787b472c0e0b6304dedbf212a42f32d13472079
