### ISSUE TITLE
Font features break Iosevka Term

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#3716]
**Describe the bug**
Enabling any font feature for Iosevka Term makes some characters invisible.

**To Reproduce**
`kitty -c none -o font_family='Iosevka Term' -o font_features='Iosevka-Term +cv82=6'`
characters `iog` and probably some more stop being displayed.
after some random typing no character is being displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/10168645/121786582-5af80200-cbc9-11eb-8f8f-a4259665a082.png)

**Additional context**
Iosevka 7.0.4

**Comment by kovidgoyal** [comment]
This is a bug in Iosevka Term. It has a glyph name of .gid9171.join-r
for one of the == glyphs. Which means it is requesting the special
ligature handling @b5invis requested in https://github.com/be5invis/Iosevka/issues/1007

However when that font feature is turned on the i character becomes a
ligature of dotlessi and u0307 these glyphs do not have the .join-x
naming scheme, which breaks ligature handling as per the above scheme. 

Either Iosevka Term should not indicate it wants the .join-x based
ligature handling, or it needs to modify the names of all glyphs that
participate in ligatures to have .join-x suffixes.

**Comment by be5invis** [comment]
@kovidgoyal @SolitudeSF 
The problem is `cv82=6`. When any `cv`/`ss` feature gets enabled, all diacritic letters will be decomposed into their base and diacritics with a one-to-many substitution. This behavior is by design, otherwise, Iosevka will have too many glyphs, not being able to fit in OT (it already has >21000 glyphs).

**Comment by kovidgoyal** [comment]
Then how would you suggest kitty handle that. These ligatures involve
glyphs without the naming scheme we discussed.

**Comment by be5invis** [comment]
@kovidgoyal Can you try whether this works? I added `.join-l` for all marks.
[iosevka-regular.zip](https://github.com/kovidgoyal/kitty/files/6643340/iosevka-regular.zip)

**Comment by be5invis** [comment]
You can try this string, and any glyphs with width = 0 should have `.join-l`
```
i$Ͼ®🆓≝
```

**Comment by kovidgoyal** [comment]
kitty --debug-font-fallback --config NONE -o font_family='Iosevka' -o font_features='Iosevka +cv82=1' sh -c "printf 'i$Ͼ® 🆓≝'; read"
![iosevka](https://user-images.githubusercontent.com/1308621/121796868-ea3cfe00-cc39-11eb-992f-84c918c15aa0.png)

**Comment by be5invis** [comment]
Um, looks fine, though the diacritics (like the dot in `i`) are slightly shifting left (maybe rounding error)?

**Comment by kovidgoyal** [comment]
No clue, those come from harfbuzz/freetype.

**Comment by be5invis** [comment]
7.1 should have this fixed.
