### ISSUE TITLE
How to keep the previous behaviour or kitty_mod + click to open URLs?

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#3718]
`0.21.0` removed `ctrl+shift+click` to open URLs, but that's not working inside tmux, so how can I preserve the old behavior? Because that was working fine in tmux which I use heavily.

**Comment by kovidgoyal** [comment]
ctrl+shift+click still works to open URLs. And if you wish to customize
mouse actions there is now a comprehensive framework for it, the docs
for which are linked from the changelog.

**Comment by ahmedelgabri** [comment]
> ctrl+shift+click still works to open URLs.

It's not working for me after the update. That's why I opened the issue. Not sure if it's a regression or that I need to do something, because nothing changed from my side.

**Comment by kovidgoyal** [comment]
does it not work with --config NONE

**Comment by ahmedelgabri** [comment]
> does it not work with --config NONE

Just tested it, it works even inside tmux. One last info, I changed `kitty_mod` to be CMD & that was working fine with URLs, looks like this might be the issue then?

**Comment by kovidgoyal** [comment]
Yes, you need to add

```
mouse_map cmd+left release grabbed,ungrabbed mouse_click_url
mouse_map cmd+left press grabbed mouse_discard_event
```

**Comment by ahmedelgabri** [comment]
> Yes, you need to add
> 
> ```
> mouse_map cmd+left release grabbed,ungrabbed mouse_click_url
> mouse_map cmd+left press grabbed mouse_discard_event
> ```

Tried that, doesn't work. Weirdly enough `CTRL+SHIFT+Click` still works, although my `kitty_mod` is remapped to `CMD`

**Comment by kovidgoyal** [comment]
kitty_mod doesnt have anything to do with mouse actions anymore.

**Comment by ahmedelgabri** [comment]
clear, but even copying the snippets above verbatim didn't work.

**Comment by kovidgoyal** [comment]
works for me with 
cat kitty.conf
mouse_map cmd+left release grabbed,ungrabbed mouse_click_url

**Comment by ahmedelgabri** [comment]
How can I debug this further then?

**Comment by kovidgoyal** [comment]
Run with --debug-input and you will see what events are being processed.

**Comment by ahmedelgabri** [comment]
This what I get when I use `CMD+click` 

```
on_key_input: glfw key: 0xe064 native_code: 0x37 action: RELEASE mods: super text: '' state: 0 updateIMEState: 33.000000, 102.500000, 6.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
Press mouse_button: 0 mods: super grabbed: 0
on_mouse_input: press button: left mods: super grabbed: 0
Release mouse_button: 0 mods: super grabbed: 0
on_mouse_input: release button: left mods: super grabbed: 0
on_mouse_input: click button: left mods: super grabbed: 0
```

I tried this also after seeing `super`

```
mouse_map super+left release grabbed,ungrabbed mouse_click_url
mouse_map super+left press grabbed mouse_discard_event
```

But same result.

This is with `CTRL+SHIFT+click` 

```
on_key_input: glfw key: 0xe062 native_code: 0x3b action: PRESS mods: ctrl text: '' state: 0 updateIMEState: 33.000000, 102.500000, 6.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
on_key_input: glfw key: 0xe061 native_code: 0x38 action: PRESS mods: ctrl+shift text: '' state: 0 updateIMEState: 33.000000, 102.500000, 6.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
Press mouse_button: 0 mods: ctrl+shift grabbed: 0
on_mouse_input: press button: left mods: ctrl+shift grabbed: 0
Release mouse_button: 0 mods: ctrl+shift grabbed: 0
on_mouse_input: release button: left mods: ctrl+shift grabbed: 0
MouseEvent matched action: mouse_click_url
updateIMEState: 0.000000, 0.000000, 0.000000, 0.000000
on_key_input: glfw key: 0xe062 native_code: 0x0 action: RELEASE mods: none text: '' state: 0 updateIMEState: 33.000000, 102.500000, 6.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
on_mouse_input: click button: left mods: ctrl+shift grabbed: 0
```

**Comment by kovidgoyal** [comment]
super and cmd are the same thing (aliases of each other). That log shows
nothing is matching which would imply your config change is not being
picked up. Are you actually quitting and restarting kitty (with cmd+q).

**Comment by ahmedelgabri** [comment]
> super and cmd are the same thing (aliases of each other).

Yes, I know. I just wanted to see if one string will be picked over the other or not

> Are you actually quitting and restarting kitty (with cmd+q).

Yes, 100% I did that at least 5 times since yesterday.

**Comment by ahmedelgabri** [comment]
I also realized that I have the same issue with `rectangle_select_modifiers` works with `CTRL+SHIFT+ALT` but not with `CMD+ALT`

This works

```
mouse_map ctrl+shift+alt rectangle_select_modifiers
```

This doesn't (used to work also)
```
mouse_map cmd+alt rectangle_select_modifiers
```

**Comment by kovidgoyal** [comment]
You want

mouse_map cmd+left press ungrabbed mouse_selection rectangle

Please read the relevant section in the docs. mouse_map cmd+left release grabbed,ungrabbed mouse_click_url

**Comment by ahmedelgabri** [comment]
Yeah sorry, missed that. But this is also not working.

> mouse_map cmd+alt+left press ungrabbed mouse_selection rectangle

**Comment by kovidgoyal** [comment]
Then I have no idea, sorry.

**Comment by ahmedelgabri** [comment]
Just wanted to update the thread, that it's working now. Not sure if that's related to `0.21.1` or because I restarted my machine.
