### ISSUE TITLE
Unable to set kitty as my default terminal with update-alternatives

### ISSUE THREAD

**Issue by eXsoR65** [kovidgoyal/kitty#3726]
Perhaps this not an issue but that I just don't know how else to set it. But I install Kitty from the Binary and integrated it with gnome but when trying to use `update-alternatives --config x-terminal-emulator` it not listed as an option. 

Any help with this is appreciated.

**Comment by kovidgoyal** [comment]
Please move this to discussions, as its not a kitty issue. https://github.com/kovidgoyal/kitty/discussions
