### ISSUE TITLE
macOS: `adjust_line_height` cuts off text since commit 39b3d3d

### ISSUE THREAD

**Issue by ytang** [kovidgoyal/kitty#3728]
**Describe the bug**
Commit 39b3d3d lowered the text baseline, therefore `adjust_line_height` would cut off the text instead of the margin.

**Old, expected behavior (before commit 39b3d3d)**
The font [Operator Mono SSm](https://www.typography.com/fonts/operator/styles/screensmart) has a large vertical margin, so I set `adjust_line_height 85%`. It used to work perfectly, as in this screenshot:

<img width="721" alt="Screen Shot 056d1601 85" src="https://user-images.githubusercontent.com/88049/121977952-2618b600-cd55-11eb-9da5-4f61a55ed4fe.png">

**New, undesirable behavior (since commit 39b3d3d)**
The baseline is lowered, resulting in a large top margin. The option `adjust_line_height 85%` cuts off the text at the bottom instead of trimming the top margin. See this screenshot with the same configuration:

<img width="721" alt="Screen Shot 39b3d3de 85" src="https://user-images.githubusercontent.com/88049/121977971-32047800-cd55-11eb-8d93-18a5c09416b8.png">

Setting `adjust_line_height 0` isn't a good solution either, since it leaves a large top margin and hence a large gap between lines that I really don't like. See this screenshot:

<img width="721" alt="Screen Shot 39b3d3de 0" src="https://user-images.githubusercontent.com/88049/121977984-3761c280-cd55-11eb-8f86-7f941c90bf61.png">

**Environment details**
```
kitty 0.20.3 (39b3d3de0f) created by Kovid Goyal
Darwin Yangs-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.4 BuildVersion:	20F71
Loaded config files: /Users/ty/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height                 0.85
allow_remote_control               y
background                         Color(red=46, green=52, blue=64)
background_opacity                 0.95
bold_font                          Operator Mono SSm Bold
bold_italic_font                   Operator Mono SSm Bold Italic
color0                             Color(red=59, green=66, blue=82)
color1                             Color(red=191, green=97, blue=106)
color10                            Color(red=163, green=190, blue=140)
color11                            Color(red=235, green=203, blue=139)
color12                            Color(red=129, green=161, blue=193)
color13                            Color(red=180, green=142, blue=173)
color14                            Color(red=143, green=188, blue=187)
color15                            Color(red=236, green=239, blue=244)
color2                             Color(red=163, green=190, blue=140)
color3                             Color(red=235, green=203, blue=139)
color4                             Color(red=129, green=161, blue=193)
color5                             Color(red=180, green=142, blue=173)
color6                             Color(red=136, green=192, blue=208)
color7                             Color(red=229, green=233, blue=240)
color8                             Color(red=76, green=86, blue=106)
color9                             Color(red=191, green=97, blue=106)
confirm_os_window_close            1
cursor                             Color(red=216, green=222, blue=233)
font_family                        Operator Mono SSm Book
font_size                          14.0
foreground                         Color(red=216, green=222, blue=233)
initial_window_height              (24, 'cells')
initial_window_width               (80, 'cells')
italic_font                        Operator Mono SSm Book Italic
macos_option_as_alt                3
macos_quit_when_last_window_closed True
mouse_hide_wait                    3.0
remember_window_size               False
resize_in_steps                    True
selection_background               Color(red=216, green=222, blue=233)
selection_foreground               Color(red=46, green=52, blue=64)
strip_trailing_spaces              smart
tab_bar_style                      powerline
Added mouse actions:
	 shift+ctrl+b1 press grabbed KeyAction(func='mouse_discard_event', args=())
Added shortcuts:
	 shift+ctrl+' KeyAction(func='scroll_to_mark', args=[False, 0])
	 shift+ctrl+/ KeyAction(func='create_marker', args=())
	 shift+ctrl+; KeyAction(func='scroll_to_mark', args=[True, 0])
	 shift+ctrl+\ KeyAction(func='remove_marker', args=())
	 shift+ctrl+f5 KeyAction(func='load_config_file', args=())
	 shift+ctrl+f6 KeyAction(func='debug_config', args=())
Changed shortcuts:
	 cmd+0 KeyAction(func='goto_tab', args=(10,))
	 cmd+1 KeyAction(func='goto_tab', args=(1,))
	 cmd+2 KeyAction(func='goto_tab', args=(2,))
	 cmd+3 KeyAction(func='goto_tab', args=(3,))
	 cmd+4 KeyAction(func='goto_tab', args=(4,))
	 cmd+5 KeyAction(func='goto_tab', args=(5,))
	 cmd+6 KeyAction(func='goto_tab', args=(6,))
	 cmd+7 KeyAction(func='goto_tab', args=(7,))
	 cmd+8 KeyAction(func='goto_tab', args=(8,))
	 cmd+9 KeyAction(func='goto_tab', args=(9,))
	 cmd+t KeyAction(func='new_tab_with_cwd', args=['!neighbor'])
```

**Additional context**
Here is a minimal `kitty.conf` that reproduces the problem:
```
font_family      Operator Mono SSm Book
bold_font        Operator Mono SSm Bold
italic_font      Operator Mono SSm Book Italic
bold_italic_font Operator Mono SSm Bold Italic
font_size 14.0
adjust_line_height  85%
```

This issue is related to #2022, which has its own merits. I think the ideal solution would be to provide a way to adjust the top and bottom margins separately, instead of relying on a single `adjust_line_height` option. Thank you very much.

**Comment by kovidgoyal** [comment]
The current baseline calculation matches that of macOS. It's not going
to change. If you dislike having a low baseline, it should be fixed in
the font, not worked around in every application.

**Comment by ytang** [comment]
What you said isn't technically wrong, but since there are many fonts with similar issues, I wouldn't count on every font designer to fix it, especially commercial fonts such as Operator Mono.

When something used to work stops working, instead of blaming each and every font designer, maybe consider adding an option to let users adjust the baseline?

What I dislike isn't the low baseline, but the large gap between lines, which couldn't be fixed through `adjust_line_height`. Adding an option to let users adjust the baseline would suffice, for example, adding a configurable offset to [`bounds_ascent`](https://github.com/kovidgoyal/kitty/blob/39b3d3de0f97d921ad8ccf0191b95ab40ba18076/kitty/core_text.m#L370). I would be totally happy if you could do something like this.

I wouldn't agree on the "not worked around in every application" part. Software systems are full of workarounds. Although an ideal solution is better than a workaround, a workaround is way better than being broken. FWIW, [Alacritty](https://github.com/alacritty/alacritty) renders it just fine, like what kitty used to be before 39b3d3d.

**Comment by kovidgoyal** [comment]
Just because something worked accidentally because of a bug doesn't mean
that bug should be preserved forever. And its trivial to patch a font to
adjust the baseline using something like fontforge yourself, if you cant
get your font designer to do it for you.

As for an option to adjust the baseline, sure, PR is welcome.
