### ISSUE TITLE
better documentation for terminfo support

### ISSUE THREAD

**Issue by ahh** [kovidgoyal/kitty#373]
I use kitty on machine A where I often ssh to machine B where kitty isn't installed. This causes a lot of problems for my shell which can't figure out how to clear, less, etc because of an unknown TERM type.

I believe I fixed this by copying over the file kitty/terminfo/kitty.terminfo and running `tic kitty.terminfo` and now everything seems to work.  However, I'm not sure this was the best practice, and it's undocumented in any case.  

Could you add instructions for doing this properly to the README?

**Comment by bradlyatc** [comment]
This is answered In bold with a full paragraph on the main page under FAQ.

**Comment by kovidgoyal** [comment]
It's already in the FAQ.
