### ISSUE TITLE
Middle mouse button to paste not working on MacOS anymore?

### ISSUE THREAD

**Issue by tobiwild** [kovidgoyal/kitty#3730]
**Describe the bug**
With the current version (0.21.1) I'm not able to paste from the clipboard by using the middle mouse button anymore on Mac OS. With version 0.20.3 it worked fine.

**To Reproduce**
- Put something in the system clipboard
- Use middle mouse button to paste
- Nothing happens

**Comment by kovidgoyal** [comment]
Add 

mouse_map middle release ungrabbed paste_from_clipboard

to kitty.conf
