### ISSUE TITLE
Doesn't display "🏎" (U+1F3CE) from color emoji fonts

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#3739]
**Describe the bug**

If I try to print the "🏎" (U+1F3CE) character in kitty, it just appears as a blank block, like space. `--debug-font-fallback` prints this:

```
U+1f3ce Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

If I configure joypixels to be used instead, it prints this:

```
U+1f3ce Face(family=JoyPixels, style=Regular, ps_name=JoyPixels, path=/usr/share/fonts/joypixels/JoyPixels.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

If I remove both of those fonts, it uses `Noto Sans Symbols2`, and then I see a black and white version of it. `--debug-font-fallback` prints this:

```
U+1f3ce Face(family=Noto Sans Symbols2, style=Regular, ps_name=NotoSansSymbols2-Regular, path=/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf, index=0, is_scalable=True, has_color=False, ascender=1069, descender=-630, height=1699, underline_position=-125, underline_thickness=50, strikethrough_position=322, strikethrough_thickness=50) (new face)
```

**To Reproduce**
1. Install Noto Color Emoji or Joypixels.
2. Print `🏎` to kitty.
3. See it rendered as a space instead of the emoji.

**Environment details**
I ran kitty with `--config NONE`

```
kitty 0.21.1 created by Kovid Goyal
Linux george 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
I cannot reproduce

printf '\U1f3ce\ufe0f'

prints a colored racing car in two cells, as expected, close to the bottom of the cell,
from Noto Sans Emoji.

printf '\U1f3ce' prints a black and white version of it in one cell from
the Symbola font, as expected. Install the Symbola font for better
symbol glyphs.

Note that this glyph is typically very wide and short and low down, so
depending on font sizes it might not render very well, especially in one
cell.

**Comment by trygveaa** [comment]
> printf '\U1f3ce\ufe0f'

Right, this shows the color emoji.

> printf '\U1f3ce' prints a black and white version of it in one cell from
the Symbola font, as expected. Install the Symbola font for better
symbol glyphs.

Even if I don't have symbola I still have a font with the black and white version. If I remove my color emoji fonts, a black and white version from `Noto Sans Symbols2` is shown as mentioned. But apparently kitty tries to use the glyph from `Noto Color Emoji` even when I don't include U+fe0f, as shown by the debug output.

**Comment by trygveaa** [comment]
If I install Symbola, I see the black and white version, but why wasn't the one from `Noto Sans Symbols2` selected when I didn't have Symbola?

And wouldn't it be better to fall back to the color version instead of a space if the black and white version isn't available?

**Comment by kovidgoyal** [comment]
You'd have to ask the developers of fontconfig. Font fallback is
controlled by fontconfig on linux. As for why noto color emoji is
rendering as blank, its probably because th glyph is too low/wide
to render in one cell.
