### ISSUE TITLE
no way to control linux package launcher linking

### ISSUE THREAD

**Issue by arubertoson** [kovidgoyal/kitty#374]
in the `linux_package_launcher` is there a reason we can't add libraries to the linker?

When building the `python setup.py linux-package --prefix=<install prefix>` there seems to be a linking error unless I have the library in my system paths.

```bash
 > ldd kitty                                                                    
        linux-vdso.so.1 =>  (0x00007ffc87de7000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f68c9cfd000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f68c9af9000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f68c98f5000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f68c96ed000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f68c93eb000)
        libpython3.6m.so.1.0 => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007f68c9027000)
        /lib64/ld-linux-x86-64.so.2 (0x000055caa4b9d000)
```
The way to get around that is to use LD_LIBRARY_PATH, but I much rather have control how the libraries are resolved by setting the rpath.

Is there a reason we have no control over the linker through LDFLAGS? If not, do you have a preferred way how this would be specified?

**Comment by kovidgoyal** [comment]
LDFLAGS is used already, see line 191 of setup.py

**Comment by kovidgoyal** [comment]
Never mind, I think you mean the launcher and not the kitty module?

**Comment by arubertoson** [comment]
Tested and it works great! Thank you
