### ISSUE TITLE
Additional parameters for cursor customization

### ISSUE THREAD

**Issue by invertigo** [kovidgoyal/kitty#3741]
**Is your feature request related to a problem? Please describe.**
No, this is pure fun.  I want more knobs to tweak the cursor blinkiness.  Specifically to set up a fluctuating gradient between the "on" and "off" colors

**Describe the solution you'd like**
A few new parameters for the cursor blink rate, inspired by analog synthesizer low-frequency oscillator (LFO) controllers

`cursor_blink_mod_rate` - Frequency (Hz) at which a cursor parameter is modulated
`curson_blink_mod_shape` - Shape of the modulation affecting cursor blink (e.g. square, pwm, triangle, forward/backward sawtooth, random)
`cursor_blink_mod_repetitions` - (mutually exclusive with `cursor_stop_blinking_after`) how many times the modulation will occur after keyboard activity stops.

This stuff can get fun - later additions might include a modulator for the modulator, so the blink speed can accelerate or decelerate.

**Describe alternatives you've considered**
This is 100% would-be-fun stuff.

**Additional context**

![image](https://user-images.githubusercontent.com/389982/122432010-f2ab7680-cf62-11eb-8c22-8f9c4a7b5180.png)

**Comment by kovidgoyal** [comment]
While I can appreciate playing with these knobs might be fun for you,
I'm afraid Creating/maintaining them is not fun for me, sorry.

**Comment by invertigo** [comment]
Fair enough, that's what forks are for :)
