### ISSUE TITLE
Cannot disable extended key reporting for alternate screen while not on it

### ISSUE THREAD

**Issue by greenfork** [kovidgoyal/kitty#3742]
**Describe the bug**
After quitting [Kakoune code editor](https://github.com/mawww/kakoune) the terminal is in a broken state, other ncurses applications don't work properly. However it works perfectly fine in iTerm, Alacritty. I don't know the exact reason and details but please see the discussion of [this commit](https://github.com/mawww/kakoune/commit/47c0d2038807757207cde3b3e00fbc1ca9448178).

**To Reproduce**
```
git clone https://github.com/mawww/kakoune.git
cd kakoune/src
make
./kak
:q<enter>
```

Now try interacting with any other ncurses application like fzf. For example, while active in fzf `ctrl-c` inserts `99;5u`.

**Environment details**
```
kitty 0.21.1 created by Kovid Goyal
Linux pisec 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  /home/grfork/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control               y
clipboard_control                  ('write-clipboard', 'read-clipboard')
copy_on_select                     clipboard
cursor_blink_interval              0.0
enable_audio_bell                  False
enabled_layouts                    ['splits', 'stack', 'horizontal', 'vertical']
focus_follows_mouse                True
font_family                        Fantasque Sans Mono
initial_window_height              (768, 'px')
initial_window_width               (1024, 'px')
macos_option_as_alt                3
macos_quit_when_last_window_closed True
remember_window_size               False
scrollback_pager_history_size      52428800
select_by_word_characters          @-./_~?&=%+#:
strip_trailing_spaces              smart
Added shortcuts:
	alt+ctrl+h KeyAction('neighboring_window', ('left',))
	alt+ctrl+j KeyAction('neighboring_window', ('bottom',))
	alt+ctrl+k KeyAction('neighboring_window', ('top',))
	alt+ctrl+l KeyAction('neighboring_window', ('right',))
	shift+alt+ctrl+h KeyAction('move_window', ('left',))
	shift+alt+ctrl+j KeyAction('move_window', ('bottom',))
	shift+alt+ctrl+k KeyAction('move_window', ('top',))
	shift+alt+ctrl+l KeyAction('move_window', ('right',))
```

**Additional context**
`kitty --config NONE` does same thing.

**Comment by kovidgoyal** [comment]
This is a bug in kakoune. As is noted in https://sw.kovidgoyal.net/kitty/keyboard-protocol.html#quickstart
the application has to pop the keyboard mode for alternate screen
before leaving it. 

keyboard modes in kitty are managed in a stack, and the main and
alternate screens have separate stacks. This is exactly how there are
separate stacks for tabstops, graphics and cursor save points.

**Comment by kovidgoyal** [comment]
Oh and in case it isnt obvious, the motivation for this design is: It allows alternate screen based applications to use whatever keyboard encoding they like *without affecting the encoding used by the min screen applications such as the shell*. Without this design, an alternate screen application has to query what the main screen keyboard mode is and then restore to that mode on exit to avoid breaking the shell.

**Comment by greenfork** [comment]
Alright, thanks for explaining!
