### ISSUE TITLE
Mouse Action documentation examples

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#3743]
The new version of Kitty means kitty_mod is no longer required to click urls. I prefer this behavior as I constantly accidentally click urls when clicking in the terminal window to make sure I'm not focused on something else.

**Describe the solution you'd like**
Reading the docs I thought the following might disable the new behavior:
```
mouse_map left click grabbed no-op
```

Left because this happens on a regular click, grabbed because urls are only triggered when the window's focused and no-op as the suggested way to unmap an action.

**Describe alternatives you've considered**
Since this change may affect several people who got used to the old behavior maybe an explicit example showing how to get back to the old behavior would be acceptable?

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Click-the-link-under-the-mouse-cursor-when-no-selection-is-created

replace the action with no-op there to disable it.

**Comment by toonn** [comment]
Why would the mode be "ungrabbed?" Doesn't that mean the window is *not* focused when the click happens? I feel like the modes at least need some more documentation to make this clearer.

**Comment by toonn** [comment]
Either grabbed/ungrabbed is about something other than window focus or the "un" prefix is unintuitively swapped.

Changing "grabbed" to ungrabbed in my suggested map *does* do what I want. It's just weird that *un*grabbed = focused window, while grabbed must then mean *un*focused window.

**Comment by kovidgoyal** [comment]
Look at the commit after the commit that closed this issue.

**Comment by toonn** [comment]
Ah, thank you. I needed that clarification!

Is a focus modifier possible? Being able to `kitty_mod+click` urls when a terminal window isn't focused would be nice.

**Comment by kovidgoyal** [comment]
No, I'm afraid not.
