### ISSUE TITLE
Pressing ctrl-shift-F13 inserts 376;6u

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#3748]
**Describe the bug**
This is not quite a bug but not quite a feature request either. Since macOS lacks a "compose key" I have used Karabiner-Elements to "remap" right CMD to an obscure key sequence `ctrl-shift-F13`. And then I can have that behave like a compose key using `~/Library/KeyBindings/DefaultKeyBinding.dict`.
This works great in GUI programs. In Kitty pressing this rebound CMD used to insert a capital P. Since updating to 0.21 it is showing this newer behavior of inserting `376;6u`, which is a bit less convenient to delete every time I use the functionality.

I would like to understand why this happens and whether there's a way around the terminal inserting what I assume are some sort of escape codes.

**To Reproduce**
1. Press `ctrl-shift-F13`.
2. See `376;6u` inserted at point.

**Comment by kovidgoyal** [comment]
map ctrl+shift+f13 mouse_discard_event

**Comment by toonn** [comment]
Thank you, this gets much closer. Though Kitty still receives and enters all the keys leading up to the composition. I don't expect that to be easily solved though.
