### ISSUE TITLE
`icat` claims kitty does not support the kitten protocol

### ISSUE THREAD

**Issue by nonchip** [kovidgoyal/kitty#3749]
**Describe the bug**

Trying to run `kitty +kitten icat some_picture.jpg` in kitty returns:

> This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it

while the kitty terminal itself outputs on its *outside* stderr:
```
OSError: [Errno 22] Invalid argument: '/home/kyra/.cache/kitty'
OSError: [Errno 22] Invalid argument: '/home/kyra/.cache/kitty'
OSError: [Errno 22] Invalid argument: '/home/kyra/.cache/kitty'
OSError: [Errno 22] Invalid argument: '/home/kyra/.cache/kitty'
```

that folder exists, and contains only a `main.json` containing `{"window-size": [640, 400]}`

**To Reproduce**
1. `kitty` (running the terminal)
2. `kitty +kitten icat some_picture.jpg`
3. See error

**Environment details**
```
kitty 0.21.1 created by Kovid Goyal
Linux firefly 5.12.12_1 #1 SMP 1624132767 x86_64
Void \r (\n) (\l)
Running under:X11

Config options different from defaults:
```
That `kitty` version is installed via void linux's package manager, see: https://github.com/void-linux/void-packages/blob/master/srcpkgs/kitty/template

Also, I'm using zsh 5.8 with the oh-my-zsh "config framework", `$TERM` is reported as `xterm-kitty`

**Comment by kovidgoyal** [comment]
That will be because creating a tmpfile in that directory is failing,
probably because you have it mounted on a broken filesystem. Try setting
the KITTY_CACHE_DIRECTORY env var to something with a normal filesystem
and you should be fine (note that the env var has to be set system wide
not in your shell's rc files, as kitty runs before the shell).

**Comment by nonchip** [comment]
ok yeah, so if zfs is a "broken filesystem" that literally every other program ever works just fine with, then you're probably right.
setting that var to a ramdisk "unbroke" it.

so i guess you calling that a "broken filesystem" and closing the issue without waiting for a reply means `wontfix` then...

**Comment by kovidgoyal** [comment]
Yup, ZFS is a broken filesystem. Proof: https://github.com/openzfs/zfs/issues/12060

Dont buy the hype you are sold about filesystems.

**Comment by Luflosi** [comment]
I'm running OpenZFS 2.1.0-rc7 and it works fine for me. This was fixed in OpenZFS 2.1.0-rc6. You could also downgrade your kernel.

**Comment by Luflosi** [comment]
You're probably running OpenZFS 2.0.4, which is explicitly not compatible with Linux 5.12 ("Linux: compatible with 3.10 - 5.11 kernels").

**Comment by revoltez** [comment]
i fixed it by changing the ownership of home/user/.cache/ folder (recursively including kitty)
`chown -R userName /home/userName/.cache`

**Comment by rahul-rakshit** [comment]
I have the same problem on macOS and I don't really have a choice for filesystem. Would it be ok to re-open the issue?
