### ISSUE TITLE
Kitty does not respect the currently selected layout

### ISSUE THREAD

**Issue by aignas** [kovidgoyal/kitty#375]
I have two English layouts on my PC: dvorak US and standard US, which is set as the default layout. When I try to press Ctrl+D to exit terminal when the Dvorak layout is active kitty does not understand this. Instead I need to use the QWERTY layout to hit shortcuts no matter which layout is active. I would expect Kitty to honour the currently active layout or at least to have a switch on enabling such feature as I know that some people do prefer to current behaviour.

**EDIT**: This is actually breaking vim quite hard because any key combination with `Ctrl` does not work as expected (i.e. pressing `Ctrl+C` in dvorak does not forward `Ctrl+C` to `vim`).

That said I quite like the speed of the emulator and would love to switch to it if not for this issue.

**Comment by kovidgoyal** [comment]
This needs to be fixed in glfw https://github.com/glfw/glfw/issues/1140
