### ISSUE TITLE
[Help] Keymap for kitty @launch

### ISSUE THREAD

**Issue by danstewart** [kovidgoyal/kitty#3752]
I'm having issues getting a key bind working with `kitty @launch`

I've tried the following
```bash
map ctrl+shift+t  bash -c 'kitty @launch --type=tab --cwd=current --copy-env'
map ctrl+shift+t  'kitty @launch --type=tab --cwd=current --copy-env'
map ctrl+shift+t  kitty @launch --type=tab --cwd=current --copy-env
```

The keybind opens in a new tab but not in the same directory or with the env vars.
The command works perfectly when running from the terminal directly.

For some background I want to copy the `$VIRTUAL_ENV` env var when opening new tabs when working with python venv.

Thanks

**Comment by kovidgoyal** [comment]
map whatever launch --type=tab --cwd=current --copy-env

**Comment by danstewart** [comment]
I tried that too - sorry should have mentioned that.

That set the right tab but the env wasn't copied - I saw in another issue vars set in the shell aren't copied since kitty runs before the shell.

I also tried that by explicitly passing `--env VIRTUAL_ENV=${VIRTUAL_ENV}` - but that set it to the string `"${VIRTUAL_ENV}"`.

**Comment by kovidgoyal** [comment]
yes kitty has no access to the environment variables you set in a shell,
as the shell does not export those variables process wide. --copy-env
can only copy the environment variables accessible via

/proc/pid/environ

When you run it via remote control, you are running the command within
the shell and so it has access to those environment variables.

Do export FOO=BAR in your shell, then do

cat /proc/self/environ and you will see that the shell has not exported
the env vars.

**Comment by danstewart** [comment]
That makes sense - thanks.

That's why I'm trying to set up my keybind to use remote control - is that possible?

**Comment by kovidgoyal** [comment]
well, you cant run arbitrary code inside unrelated processes. You could
use send_text to send the command as text and run it, but that will only
work when you are at an empty prompt.

**Comment by danstewart** [comment]
If I run `kitty @launch --type=tab --cwd=current --copy-env` in my shell it does what I want, I just want to run that from a keybind - is that running arbitrary code in an unrelated process?


It half works using `map ctrl+shift+t  kitty @launch --type=tab --cwd=current --copy-env` - it opens the tab but doesn't set the cwd or env.

**Comment by kovidgoyal** [comment]
In one case you are running kitty @ launch *inside the shell* in the
other you are running it as a background process. Completely unrelated.

**Comment by danstewart** [comment]
Ah right - I understand.

Thanks for your help.

**Comment by danstewart** [comment]
I've got a workaround for my use case.

I auto-activate the venv when `cd`-ing - I've just called `cd .` in my `.bashrc`, so the new tab will activate the venv.

```bash
function cd() {
	builtin cd "$@"

	# If env folder is found then activate the virtualenv
	if [[ -d ./venv ]] ; then
		source ./venv/bin/activate
	fi

	# If we are no longer within our active venv then deactivate
	if [[ -n "$VIRTUAL_ENV" ]] ; then
		venvparent="$(dirname "$VIRTUAL_ENV")"
		if [[ "$(pwd -P)"/ != "$venvparent"/* ]] ; then
			deactivate
		fi
	fi
}

cd .
```
