### ISSUE TITLE
"Open in kitty" Nautilus context menu on Linux

### ISSUE THREAD

**Issue by rdtq** [kovidgoyal/kitty#3753]
In Nautilus file manager on Linux (e.g., Ubuntu), if you right-click on empty space in any folder, there's "open in Terminal" option, which opens folder in Gnome-terminal. 

It would be cool if there would be "Open in kitty" when you install kitty.

**Comment by kovidgoyal** [comment]
The kitty installer doesn't know anything about desktop environments and
integration with them as I cant be bothered maintaining that code,
sorry. You will basically have to write a desktop file for kitty and
integrate it with your desktop environment. There are hints how to do
that at: https://sw.kovidgoyal.net/kitty/binary.html

**Comment by Luflosi** [comment]
I think kitty ships with a desktop file. If you figure out the correct changes, please propose a PR with your changes applied in setup.py.

**Comment by Luflosi** [comment]
Or maybe copying the kitty.desktop file to the correct location is all that is needed and will do what you want.
