### ISSUE TITLE
Get current config via command line

### ISSUE THREAD

**Issue by kidonng** [kovidgoyal/kitty#3756]
**Is your feature request related to a problem? Please describe.**

`--debug-config` was removed in v0.21.1 (4a71afaf963a40921445f11b068e3f7ef2bd5821), however I can't find an alternative solution to get the current config via command line.

**Describe the solution you'd like**

A function to get the current config in kittens.

**Describe alternatives you've considered**

I tried to call the internal `debug_config` function via `kitty +kitten`, but kitty doesn't run the `handle_result` function in the kitten, so I have no access to `boss` and thus the `debug_config` function. Then I tries to directly call it:

```py
from kitty.debug_config import debug_config
from kitty.fast_data_types import get_options

def main(args):
    debug(debug_config(get_options()))
```

But I get `RuntimeError: Must call set_options() before using get_options()`.

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
The reason --debug-config was removed is precisely because it *doesnt*
give you the current configuration. Only what the configuration would be 
if you ran kitty with no commandline args and env vars changing its
behavior.

What is it you are actually trying to do?

**Comment by kidonng** [comment]
neofetch uses `kitty --debug-config` to get current terminal font: https://github.com/dylanaraps/neofetch/blob/bbbb68f8b2eb70651a6b33343f97eeb1b223a4b8/neofetch#L3430-L3436
This apparently doesn't work in the latest version of kitty, and I'm trying to fix it.

**Comment by kovidgoyal** [comment]
grep font_family ~/.config/kitty/kitty.conf | cut -d" " -f2,3,4,5,6,7,8,9

**Comment by kovidgoyal** [comment]
Oh and programmatically, the equivalent of --debug-config:

kitty +runpy 'from kitty.cli import *; print(create_default_opts().font_family)'

**Comment by Luflosi** [comment]
This is probably the better option because the first one doesn't handle the case where the config file is in a different location. On macOS for example it may be in ~/Library/Preferences.

**Comment by kidonng** [comment]
> kitty +runpy 'from kitty.cli import *; print(create_default_opts().font_family)'

`+runpy` is what I actually needed. Thanks!

**Comment by christianparpart** [comment]
> This is probably the better option because the first one doesn't handle the case where the config file is in a different location. On macOS for example it may be in ~/Library/Preferences.

Xterm has a VT sequence for that: `OSC 50 ; ? ST` and it replies with `OSC 50 ? <your_font_here> ST`. Kitty does not implement that (just tried), but that would be too good, because it's also working over the network, would work on any platform, and doesn't care about where your config file is located, and if that's still equal to what font your *current* terminal is running.

**Comment by kovidgoyal** [comment]
Seems pretty insufficient to me, as with most xterm escape codes. There can be more than one font face involved, kitty currently has four (regular, bold, italic, bold-italic). And the OP would need to query font size as well, which xterm has no escape code for. If I wanted to implement this, I would do it via https://sw.kovidgoyal.net/kitty/kittens/query_terminal.html
