### ISSUE TITLE
pango-like markup in tab title template?

### ISSUE THREAD

**Issue by chipaca** [kovidgoyal/kitty#3763]
**Is your feature request related to a problem? Please describe.**

Currently my `tab_title_template` has the *very hacky* (avert your eyes!),
```
tab_title_template "{fmt.nobold}{'¹²³⁴⁵⁶⁷⁸⁹'[index-1]}{fmt.bold}{title}"
```
(this relies on how kitty falls back to the default `{title}` when the custom one throws an error)
This is particularly useful for me because I've bound <kbd>alt</kbd>+<kbd>1</kbd> through <kbd>alt</kbd>+<kbd>9</kbd> to the first 9 tabs (and <kbd>alt</kbd>+<kbd>0</kbd> to the last)

**Describe the solution you'd like**

It would be nice to be able to have some kind of markup in there (thinking pango markup, but that would be a rather big new dependency).

**Describe alternatives you've considered**

My current approach is probably *fine*.

**Additional context**
123 all the things
![image](https://user-images.githubusercontent.com/1543430/123394425-0aa07d00-d597-11eb-94cb-0c455c3188f0.png)

**Comment by kovidgoyal** [comment]
Not sure I follow, what would pango markup get you that the current markup doesnt? You can set bold/italics/fg/bg colors with the current markup. And that is all the formatting the underlying implementation supports. There are no super/sub scripts in terminal text. If you want that it should be a fairly trivial patch in the current code, without needing a new markup language for it

**Comment by chipaca** [comment]
I'd use it mostly for size control and positioning (but superscript would be enough), but it would also let you change fonts and that sort of thing. I was trying to generalize from _my_ problem (hacky superscripts) to something more people might find useful :-)

**Comment by kovidgoyal** [comment]
The tab bar is rendered by an actual terminal, it supports only the formatting terminals support, nothing else.

**Comment by chipaca** [comment]
oooh, does `ssupm` work in kitty?

**Comment by kovidgoyal** [comment]
nope there is no support for superscript/subscript mode in kitty.

**Comment by chipaca** [comment]
aw well. I can see doing it well would be a pain from the width of rendered text pov.

Thank you.

**Comment by chipaca** [comment]
![image](https://user-images.githubusercontent.com/1543430/123404983-4e987f80-d5a1-11eb-9c7f-a41cd1c6b48d.png)

thank you!
