### ISSUE TITLE
[aws] WARNING: terminal is not fully functional

### ISSUE THREAD

**Issue by ThomasBucaioni** [kovidgoyal/kitty#3771]
On AWS, I have a free tiers RedHat `Linux 4.18.0-305.3.1.el8_4.x86_64` running. When I type `sudo less somefile`, it says:

```
WARNING: terminal is not fully functional
somefile  (press RETURN)
```
and then the arrows or the pgeup, pgedown don't work. Both `ssh` and `kitty +kitten ssh` return the same message. Here is a screenshot:
![2021-06-27_14-30-54](https://user-images.githubusercontent.com/63013654/123544806-3cf7d900-d755-11eb-817c-fe973fbba476.png)

It takes to add `export TERM=xterm-256color` in the `.bashrc` file to solve the problem (I still opened the issue so it's somewhere if someone else looks for it)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

https://sw.kovidgoyal.net/kitty/faq.html#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo

**Comment by ThomasBucaioni** [comment]
When I type `infocmp -a xterm-kitty | ssh  -i "~/.ssh/key.pem" user@ec2-a-b-c-d.eu-west-3.compute.amazonaws.com tic -x -o \~/.terminfo /dev/stdin`, it says:
```
"/dev/stdin", line 2, col 22, terminal 'xterm-kitty': older tic versions may treat the description field as an alias
```

**Comment by kovidgoyal** [comment]
and that's fine, it means it worked.
