### ISSUE TITLE
Issue with Fira Code

### ISSUE THREAD

**Issue by AckslD** [kovidgoyal/kitty#3772]
**Describe the bug**
I'm having some issues with Fira Code font rendering. I opened an [issue](https://github.com/tonsky/FiraCode/issues/1258) in the fira code repo. It was [suggested](https://github.com/tonsky/FiraCode/issues/1258#issuecomment-869061960) that "I've read that Kitty draws its own boxes, and ignores the ones provided by the font. You could investigate this the truth of this with the Kitty dev..." Is this the case and is there some way to solve it?

**To Reproduce**
See screenshots below.

**Screenshots**
![image](https://user-images.githubusercontent.com/23341710/123545810-4df71900-d75a-11eb-95c9-54b8737d9207.png)
![image](https://user-images.githubusercontent.com/23341710/123545817-551e2700-d75a-11eb-95b5-e30e62e28082.png)
![image](https://user-images.githubusercontent.com/23341710/123545824-5bac9e80-d75a-11eb-84f2-8afe8d6c5060.png)
(the character before the right `+`s is a `-` even though it looks like a ` `)

**Environment details**
```
kitty 0.21.1 (2ba015d0be) created by Kovid Goyal
Linux l390 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  /home/axel/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control  socket-only
background            Color(red=40, green=40, blue=40)
cursor                Color(red=146, green=131, blue=116)
enable_audio_bell     False
font_family           Fira Code
font_size             13.0
foreground            Color(red=235, green=219, blue=178)
initial_window_height (800, 'px')
initial_window_width  (1280, 'px')
listen_on             unix:/tmp/kitty
remember_window_size  False
selection_background  Color(red=60, green=56, blue=54)
selection_foreground  Color(red=146, green=131, blue=116)
Added shortcuts:
	alt+/ KeyAction('launch', ('--allow-remote-control', 'kitty', '+kitten', 'kitty_search/search.py', '@active-kitty-window-id'))
	alt+g KeyAction('kitten', ('kitty_grab/grab.py',))
	ctrl+enter KeyAction('new_os_window_with_cwd')
Removed shortcuts:
	shift+ctrl+w KeyAction('close_window')
```

**Additional context**
Config
```
include ./kitty-themes/themes/gruvbox_dark.conf

enable_audio_bell no

font_family      Fira Code
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

remember_window_size  no
initial_window_width  1280
initial_window_height 800

map ctrl+enter   new_os_window_with_cwd
map alt+/        launch --allow-remote-control kitty +kitten kitty_search/search.py @active-kitty-window-id
map alt+g        kitten kitty_grab/grab.py
map ctrl+shift+w noop

allow_remote_control socket-only
listen_on unix:/tmp/kitty
```

**Comment by kovidgoyal** [comment]
Those arent issues with box drawing characters, those are issues with the new infinite length ligatures in fira code not lining up with the non-ligature glyphs. If you want to draw boxes, use the actual box drawing charaters https://en.wikipedia.org/wiki/Box-drawing_character  

Infinite length ligatures are not really a  substitute for actual box drawing characters, precisely because there is no longer any guarantee they will line up.

**Comment by AckslD** [comment]
I see, thanks a lot for the clarification @kovidgoyal!

**Comment by AckslD** [comment]
@kovidgoyal Just FYI, I tried using https://aur.archlinux.org/packages/alacritty-ligatures/ and there they do line up (without using box drawing characters).
