### ISSUE TITLE
Kitty colours are a lot lighter and washed

### ISSUE THREAD

**Issue by beauwilliams** [kovidgoyal/kitty#3775]
**Describe the bug**
Kitty does not display colours correctly. They are washed out.

**To Reproduce**
Open vim, compare with another shell such as iTerm

**Screenshots**
iTERM = left
Kitty = right
![image](https://i.ibb.co/bdQWgym/Screen-Shot-2021-06-28-at-3-12-56-pm.png)

**Environment details**

 kitty --debug-config does not work not the key shortcut (OSX)

**Additional context**
I just want the colors darker and to increase the contrast a bit, if I can just get it a bit closer to my old terminal, without having to write and entire theme for both vim and kitty to match.

**Comment by kovidgoyal** [comment]
Matching other terminals colors is not a goal for kitty. Again, if you
want to change the colors, you are free to do so via the config, if you
cant be bothered to do that, that is your problem.
