### ISSUE TITLE
Add support for non-shader-based highlighting

### ISSUE THREAD

**Issue by SvenKiljan** [kovidgoyal/kitty#3780]
I attempted to use Kitty on a Pinebook Pro. The Pinebook Pro [has incomplete OpenGL 3.3 support](https://wiki.pine64.org/wiki/Pinebook_Pro#OpenGL_3.3_support). Most notably, geometry shaders are missing.

Due to this, highlighting does not work correctly in Kitty. When highlighting text, it does not appear highlighted, or in some circumstances it will make all text on the screen appear highlighted, while in reality only a single word or line is highlighted. There is a discrepancy between what Kitty thinks is highlighted and what actually gets highlighted.

Other OpenGL terminals such as Alacritty do not have this issue, because they use software-based inverse highlighting. This is a feature request for an option that allows this in Kitty (which should be disabled by default, of course).

I understand that this is a limitation of the hardware and not of Kitty. Nevertheless, it would be great if Kitty could facilitate this.

**Comment by kovidgoyal** [comment]
Highlighting isn't implemented using a geometry shader. All text rendering is
done in a single pass using just vertex and fragment shaders.
Highlighting is implemented as a vertex array that informs the vertex
shader if a cell is highlighted or not. If highlighted, the highlight
colors are applied. See cell_vertex.glsl

Presumably there is some other limitation in your
GPU drivers, most likely a bug with the VAOs or fixed location layouts.
So this isn't kitty using a feature your GPU drivers dont implement, its
an actual bug in the GPU drivers, which should be fixed there.

I'm afraid this is not something I think is worth working around in
kitty code.
