### ISSUE TITLE
Kitty launched from Gnome Dock isn't movable.

### ISSUE THREAD

**Issue by williamspatrick** [kovidgoyal/kitty#3782]
**Describe the bug**
If I add Kitty to the Gnome Dock (as a favorite for example) and launch it, it cannot be moved.  The title bar is rendered but it is unclickable (either left or right click).

Gnome 40 + Wayland

**To Reproduce**
1. Add Kitty as Dock Favorite on Gnome.
2. Launch Kitty.
3. Observe application unmovable by attempting to left-click on title bar.
4. Observe right-click on title bar is sent to desktop rather than Kitty.

**Screenshots**

**Environment details**

(Ctrl-Shift-F6 seems to do nothing in my install.)

Gentoo + Gnome 40 + Wayland
Kitty: tried both 0.20.3 from portage and compiled from git.

**Additional context**

**Comment by kovidgoyal** [comment]
You are presumably running an outdated version of kitty, if
shift+ctrl+f6 is not doing anything for you. And as far as I know GNOME
40 doesnt even have a dock.

In any case, in kitty.conf set linux_display_backend to x11 and you
should be fine.

**Comment by williamspatrick** [comment]
> In any case, in kitty.conf set linux_display_backend to x11 and you should be fine.

Yes.  You are correct that `linux_display_backend x11` does create a window which can be moved.  I'd personally rather use `wayland` and just deal with the immovability because:
- You added `wayland_titlebar_color`, which works well enough.
- The `x11` window doesn't honor Gnome's dark-mode settings and creates a light colored window.

> You are presumably running an outdated version of kitty, if shift+ctrl+f6 is not doing anything for you.

Apologies here.  You are right that the version in portage (kitty-0.20.3) did not support `shift+ctrl+f6`.  I thought I had trouble running it with the current git revision as well, but it seems to work.  I've switched the OS-level installed version to be from git as well to confirm this wayland issue is not fixed already.

```
kitty 0.21.2 (050c31094b) created by Kovid Goyal
Linux heinlein 5.4.85-gentoo-x86_64 #1 SMP PREEMPT Tue Dec 29 14:43:49 CST 2020 x86_64
This is \n.\O (\s \m \r) \t
Running under:Wayland
Loaded config files:
  /home/apwillia/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_background   Color(red=38, green=139, blue=210)
active_tab_font_style   (False, False)
active_tab_foreground   Color(red=7, green=54, blue=66)
allow_remote_control    y
background              Color(red=0, green=43, blue=54)
close_on_child_death    True
cursor                  Color(red=131, green=148, blue=150)
font_family             Liberation Mono
foreground              Color(red=131, green=148, blue=150)
inactive_tab_background Color(red=0, green=43, blue=54)
inactive_tab_foreground Color(red=131, green=148, blue=150)
initial_window_height   (51, 'cells')
initial_window_width    (80, 'cells')
remember_window_size    False
scrollback_lines        10000
selection_background    Color(red=131, green=148, blue=150)
selection_foreground    Color(red=0, green=43, blue=54)
tab_activity_symbol     ✓
tab_bar_edge            1
tab_bar_min_tabs        1
tab_bar_style           powerline
tab_title_template      {index}: {title}
wayland_titlebar_color  892679426
Added shortcuts:
	alt+ctrl+0 KeyAction('goto_tab', (10,))
	alt+ctrl+1 KeyAction('goto_tab', (1,))
	alt+ctrl+2 KeyAction('goto_tab', (2,))
	alt+ctrl+3 KeyAction('goto_tab', (3,))
	alt+ctrl+4 KeyAction('goto_tab', (4,))
	alt+ctrl+5 KeyAction('goto_tab', (5,))
	alt+ctrl+6 KeyAction('goto_tab', (6,))
	alt+ctrl+7 KeyAction('goto_tab', (7,))
	alt+ctrl+8 KeyAction('goto_tab', (8,))
	alt+ctrl+9 KeyAction('goto_tab', (9,))
```
> And as far as I know GNOME 40 doesnt even have a dock.

Attached is a screenshot.  Maybe I'm using the wrong word for the thing on the left hand side.  I am running Gnome 40.1 per the screenshot as well.

![Screenshot from 2021-07-01 09-09-22](https://user-images.githubusercontent.com/105009/124141001-9e1df600-da4e-11eb-8631-9d19815051f8.png)

**Comment by kovidgoyal** [comment]
I'm not a GNOME user, there is no dock on my gnome install, can you
provide me instructions on how to get it there and how to add kitty to
it.

**Comment by Luflosi** [comment]
I think moving the mouse cursor to the top left corner will do what you want.

**Comment by kovidgoyal** [comment]
On Thu, Jul 01, 2021 at 07:52:28AM -0700, Luflosi wrote:
> I think moving the mouse cursor to the top left corner will do what you want.

That shows a task picker for me.

**Comment by Luflosi** [comment]
I'm not entirely sure, what you mean by task picker. I'm assuming it's the Gnome equivalent of what macOS calls "Mission Control", where all the windows are shown in an overview and the virtual desktops can also be seen.
If I remember correctly, last time I used Gnome 40 it also showed the dock on the left. And if you look closely at the screenshot above, you can see that task picker is indeed active.

**Comment by kovidgoyal** [comment]
Aah for me its at the bottom not the left, so I didnt realize that is what was meant. And how do I add kitty to it? Create a .desktop file somewhere?

**Comment by Luflosi** [comment]
I think right click and then add to favourites.

**Comment by kovidgoyal** [comment]
On Thu, Jul 01, 2021 at 08:14:05AM -0700, Luflosi wrote:
> I think right click and then add to favourites.

Yeah I got that much, but for that there needs to be a .desktop file
without it right clicking doesnt give an option to add to favorites

**Comment by kovidgoyal** [comment]
So I tried the following steps:

1) Press windows key to show the task picker
2) Serch for kitty in the search bar
3) right click the kitty icon and choose add to favorites
4) click the favorites button to run kitty
5) resulting kitty window has a fully functional titlebar for me

**Comment by kovidgoyal** [comment]
I am guessing you likely have multiple kitties installed on your system and when launching from the dock it is launching an older one, in which the wayland titlebar is not functional.

**Comment by williamspatrick** [comment]
> I am guessing you likely have multiple kitties installed on your system and when launching from the dock it is launching an older one, in which the wayland titlebar is not functional.

No.  I’ve checked /proc/<PID> to ensure the expected executables are being launched. But, you can’t recreate, that is fine. I’ll debug and open a PR if I figure anything out.
