### ISSUE TITLE
Support Multiple Fonts

### ISSUE THREAD

**Issue by jrock2004** [kovidgoyal/kitty#3783]
I am starting to like Kitty but for the font I want to specify multiple just in case the font I want to use is not on that computer. I tried font_family  Comic Code, Dank Mono, Victor Mono. When I do this and run kitty --debug-font-fallback it shows me an error that font Comic Code, Dank Mono, Victor Mono is not found.

**Comment by kovidgoyal** [comment]
You cannot specify multiple fonts. If the font you specify is not found
kitty will automatically fallback to one that is found. Indeed if you
want per computer font specification, you can do so by either leaving
font_family as monospace and then kitty will use the default monospace
font or include hostname specific config in kitty.conf, see man
kitty.conf for how to use include.
