### ISSUE TITLE
macOS /etc/paths.d PATH scheme is not supported

### ISSUE THREAD

**Issue by gaydenko** [kovidgoyal/kitty#3787]
macOS /etc/paths.d PATH scheme is not supported

**Comment by kovidgoyal** [comment]
Supported for what? kitty does not setup the PATH environment variable, your shell
does that.

**Comment by gaydenko** [comment]
The thing is I have tried (with the same zsh shell) system Terminal and Alacritty and have not got any problems. So it is logical to guess all is Ok with the shell.

**Comment by kovidgoyal** [comment]
I highly doubt those terminal emulators read paths.d and setup an
environment vairable, easily confirmed by grepping their source code for
paths.d ost likey your shell rc files have some conditional behavior
based on TERM

**Comment by gaydenko** [comment]
At both cases with other terminals `echo $PATH` output includes those paths.

**Comment by kovidgoyal** [comment]
Again, grep their code for paths.d. And again, your SHELL RC FILES likely have some TERM SPECIFIC CODE that is reading those paths based on the value of the TERM variable or some other heuristic.

**Comment by allemangD** [comment]
I'm not as familiar with shells on macos, but is it possible alacritty/iterm are launching a login shell while kitty is not; or vice versa? https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.shell

**Comment by kovidgoyal** [comment]
nope kitty runs the shell as a login shell by default, it has a whole bunch of code to do exactly that, on macOS because of the historically incorrect usage of shells on that platform. See the fork() function in child.py. If you override shell in kitty.conf, you are responsible for adding --login to its invocation.

**Comment by gaydenko** [comment]
> Again, grep their code for paths.d. And again, your SHELL RC FILES likely have some TERM SPECIFIC CODE that is reading those paths based on the value of the TERM variable or some other heuristic.

I have just temporary renamed `~/.zshrc` - nothing changed. That is it isn't  "SHELL RC FILES" a reason of the problem. Moreover, all other terminals are starting having exactly the same conditions with the same shell. I don't change anything before starting this or that terminal emulator.

**Comment by kovidgoyal** [comment]
man zsh to find out just how many places shell rc files exist, you will be amazed. And I just tested this on my mac, zsh reads /etc/paths.d just fine in kitty.

**Comment by gaydenko** [comment]
> man zsh to find out just how many places shell rc files exist, you will be amazed. And I just tested this on my mac, zsh reads /etc/paths.d just fine in kitty.

Thanks, I have localized the problem:
```
❯ cat /etc/zprofile                                             
# System-wide profile for interactive zsh(1) login shells.

# Setup user specific overrides for this in ~/.zprofile. See zshbuiltins(1)
# and zshoptions(1) for more details.

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```
So I have guessed this script is not calling for some reason on kitty starting up (probably some operations ordering). To workaround I have added this `path_helper` call to `~/.zshrc`.
