### ISSUE TITLE
Ctrl-_ doesn't work in neovim

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#3790]
**Describe the bug**
In Neovim, I am using a plugin called [tcomment_vim](https://github.com/tomtom/tcomment_vim) to do the comment thing. It has some keybindings whose prefix is `CTRL-_`, e.g., `CTRL-_` + `b` in insert mode to insert a block comment. However, in kitty, when I am in insert mode and I press `CTRL-_`, `-` is inserted instead of hanging there for another key. 

I tested it in Alacritty and iTerm2. In both of them, after pressing `CTRL-_`, it will hang there for me and I can press b to insert a block comment.

**Environment details**
```
macOS version: 11.3
kitty version: 0.21.2
```

Thank you very much.

**Comment by kovidgoyal** [comment]
Ctrl+_ on US keyboards is ctrl+shift+- which in kitty is mapped to
reduce font size. If you want to use it in your terminal programs unmap
it in kitty.conf by mapping it to no-op

**Comment by yanzhang0219** [comment]
It doesn't work. 
I tried `map ctrl+shift+- no_op`. And then in vim, I press and hold `ctrl` key and at the same time I press `-` key, `-` is still inserted. My expectation is that press `ctrl+_` should hang there waiting for another key. 

Thank.

**Comment by kovidgoyal** [comment]
Works fine for me:

kitty -o 'map ctrl+shift+- no-op' showkey -a

press ctrl+shift+- and shokey prints ^_ as expected, indicating the key
has been properly reported.

**Comment by yanzhang0219** [comment]
Yes. After put `map ctrl+shift+- no_op` and in the terminal when I press `ctrl-_`, `^_` is printed on the prompt. However, the issue I describe happens in vim. In the insert mode of vim, when I press`ctrl-_`, `-` appears on the screen. This is not my expectation. [tcomment_vim](https://github.com/tomtom/tcomment_vim) plugin use `ctrl-_` + `b` to insert a comment block. But after I press `ctrl-_` + `b`, `-b` is printed on the screen. 

In Alacritty and iTerm2, it works well. Thank you.

**Comment by kovidgoyal** [comment]
You will need to report the bug to vim. As showkey demonstrates, kitty
is producing the correct bytes for that key.

**Comment by yanzhang0219** [comment]
Thanks. But it is not a bug of vim because Alacritty and iTerm work well.

**Comment by kovidgoyal** [comment]
I proved that kitty is sending the correct bytes, I dont know what more
to tell you. If you dont want to report the bug to vim, that's your
choice, I am done here.

**Comment by yanzhang0219** [comment]
I see. Anyway, thanks for your help and patience.
