### ISSUE TITLE
Kitty instantly crashes on startup with segfault error

### ISSUE THREAD

**Issue by ProspectPyxis** [kovidgoyal/kitty#3791]
After an OS update on my part, kitty seems to be crashing instantly on startup. Tried both a clean install and `kitty --config NONE` and neither worked.

Running kitty via command line with another terminal emulator (konsole) returns a segfault error, before returning this after about a second:
```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Using the latest version of kitty (0.21.2) and running Pop!_OS 21.04.

**Comment by kovidgoyal** [comment]
Probably a bug in the gpu drivers. Generate a backtrace and you will see
exactly where the crash is occurring. I am not familiar with POP OS so
cant tell you what the procedure for generating backtraces there is.
Generally on modern distros it is

echo bt | coredumpctl gdb

**Comment by ProspectPyxis** [comment]
It was a GPU driver issue indeed. Turns out the driver somehow got uninstalled during the OS update - kitty works fine again after reinstalling the drivers and a computer restart.

Thank you for the help!
