### ISSUE TITLE
Kitty Image Protocol not working for me

### ISSUE THREAD

**Issue by PoisonFrog** [kovidgoyal/kitty#3793]
I'm using Fedora 34 and I have Kitty and imagemagick (the one from Fedora repositories) installed, but when I try to use "kitty +kitten icat image/path" I get this output:

`This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it`

I'm using kitty terminal... Also, when I set up ranger file manager to use kitty image protocol as default for image preview it doesn't work too.

Anyone knows why this happens and what I could do to fix it?

**Comment by kovidgoyal** [comment]
Run kitty from another terminal and the error messages will be printed
out there. Most likely you have broken filesystem that doesnt work with
O_TMPFILE such as ZFS.

**Comment by PoisonFrog** [comment]
> Run kitty from another terminal and the error messages will be printed
> out there. Most likely you have broken filesystem that doesnt work with
> O_TMPFILE such as ZFS.

It says:
`OSError: [Errno 22] Invalid argument: '/home/myuser/.cache/kitty'`
This directory does exist, and it has only a main.json file.
I'm using btrfs as filesystem and it seems to be working fine. It is pretty much the default Fedora installation.

**Comment by kovidgoyal** [comment]
Yes, that indicates creating a tmpfile is failing. kitty uses a tmpfile
to cache image data. I've never used btrfs so I cant help with debugging
it, but check your mount options or tell kitty to use some other
location for its cache via the KITTY_CACHE_DIRECTORY env var. For
example, use /tmp (assuming /tmp is mounted on RAM).

**Comment by PoisonFrog** [comment]
> Yes, that indicates creating a tmpfile is failing. kitty uses a tmpfile
> to cache image data. I've never used btrfs so I cant help with debugging
> it, but check your mount options or tell kitty to use some other
> location for its cache via the KITTY_CACHE_DIRECTORY env var. For
> example, use /tmp (assuming /tmp is mounted on RAM).

It actually worked. I changed the location of KITTY_CACHE_DIRECTORY to my mounted pen drive that has an ext4 filesystem and it works now.

Sorry for opening the thread again, but posting this might help people running into the same issue. The problem is Fedora's btrfs.

**Comment by kovidgoyal** [comment]
Yeah it's amazing how many of these "modern" filesystems are broken. See
#3749 for the same bug in ZFS that was recently fixed. I am glad I have
stuck with ext4 :)
