### ISSUE TITLE
Terminal display issues with Python files in Neovim

### ISSUE THREAD

**Issue by yudhiesh** [kovidgoyal/kitty#3795]
**Describe the bug**
Whenever I use a Python file and try to run commands such as `!python3 <file_name.py>` my entire screen gets an odd effect where it seems like the entire terminal is mirrored over the original screen. This only happens with Python and not with any other language. You can see in the linked images where the bottom of the screen has the airline tab twice and some lines of code are repeated over. Exiting and entering the file again fixes it but it messes my entire workflow with Python. 

**To Reproduce**
1. Create a python file using neovim
2. Run the python file using `:python3 <file_name.py>`
3. Screen starts looking very odd

**Screenshots**
![Screenshot 2021-07-04 at 10 58 40 PM](https://user-images.githubusercontent.com/55042754/124390202-10c3f580-dd1d-11eb-8b65-5a886ef2b735.png)

The actual code that is in the file is:
```
# Prefer raising exceptions over returning None
def careful_divide(a: float, b: float) -> float:
    """
    Divides a by b
    Raises:
        ValueError: When the inputs cannot be divided
    """
    try:
        return a / b
    except ZeroDivisionError as e:
        raise ValueError("Invalid Inputs")


x, y = 5, 0
try:
    result = careful_divide(x, y)
except ValueError:
    print("Invalid inputs")
else:
    print("Result is %.1f" % result)
```

**Environment details**
NVIM v5.0.0
kitty 0.21.2
Python 3.7
macOS Big Sur Version 11.4
[Link to kitty.conf](https://github.com/yudhiesh/Vim-Stuff/blob/master/kitty.conf) I tried running `kitty --debug-config` but I get this issue `Unknown option: --debug-config`. 

**Additional context**
I tried the same scenario with `kitty --config NONE` and the issue still persists. At this point I am not sure if this is an issue with Kitty or something else.

**Comment by kovidgoyal** [comment]
I dont see what this has to be with the terminal emulator. You should report it to nvim.
