### ISSUE TITLE
Telemetry documentation and configuration

### ISSUE THREAD

**Issue by bone-baboon** [kovidgoyal/kitty#3802]
@kovidgoyal thank you for your work on kitty and for publishing it
under a free libre open source license.

Reading kitty's [readme file][readme], [website][website] and
[frequently asked questions][faq] I see no mention of kitty using
telemetry.

[readme]: https://github.com/kovidgoyal/kitty/blob/master/README.asciidoc
[website]: https://sw.kovidgoyal.net/kitty/
[faq]: https://sw.kovidgoyal.net/kitty/faq.html

In [pull request 3544][pull-request] you acknowledged that kitty has
telemetry on by default and clearly expressed that telemetry would
remain on by default in kitty.

[pull-request]: https://github.com/kovidgoyal/kitty/pull/3544

That kitty has telemetry on by default would come as a surprise for
many kitty users.

As kitty is a cross platform program I can see how having telemetry
for updates may be useful for users of Windows or macOS.  However
[GNU/Linux][gnu-linux] as well as [BSD][bsd] users would expect
package updates to be handled by their operating system package
manager.

[gnu-linux]: https://www.gnu.org/gnu/linux-and-gnu.en.html
[bsd]: https://en.wikipedia.org/wiki/List_of_BSD_operating_systems

There is a [group of operating systems][fsdg-distros] that follow the
[Free System Distribution Guideline][fsdg].  The Free System
Distribution Guideline require telemetry to be off default.

[fsdg-distros]: https://www.gnu.org/distros/free-distros.html
[fsdg]: https://www.gnu.org/distros/free-system-distribution-guidelines.html

It would be helpful to remove the surprise that kitty has on by
default telemetry for user and packagers of kitty.  This could be done
by adding a section describing all of kitty's telemetry in it's readme
file as well as on it's website.  Adding a telemetry section to the
web page would be helpful to users who read the website but do not look
at the source code repository.  Adding a telemetry section to the
readme file in kitty's source code repository would be helpful for
volunteers packaging kitty for different operating systems.

You clearly expressed your position on having telemetry on by default.
While respecting that position I would like to suggest that kitty
provide a configuration setting that allows the user to turn off all
of kitty's telemetry.  This configuration setting to turn off all
telemetry could then be documented in kitty's configuration
documentation as well as the telemetry section of the readme file and
the kitty website.

A configuration setting to disable all telemetry benefits many groups
interested in kitty:

- It allows kitty development efforts to continue to benefit from
  receiving telemetry as most users will not disable the on by default
  telemetry because of the [default effect][default].
- It also allows Windows and macOS users to continue to benefit from
  kitty's update telemetry.
- It allows any user that wants to disable all telemetry to be able to
  do so.
- It provides an easy way for packagers of kitty to patch kitty so
  that it has all telemetry off by default by turning off kitty's
  telemetry in the kitty configuration file.

[default]: https://en.wikipedia.org/wiki/Default_effect

Thank you for considering these two suggestion.

**Comment by kovidgoyal** [comment]
1) kitty has no **telemetry** of any kind whatsoever.
2) What it does have is a check for the up-to-date version
3) That check can be turned off in kitty.conf https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.update_check_interval
4) There are explicit instructions in the kitty manual for linux packagers on how to turn it off in a packaged build of kitty. https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers

Kindly take a moment to educate yourself before blindly regurgitating BS you read on <insert name of social media society destroying platform of choice>.

**Comment by bone-baboon** [comment]
@kovidgoyal thank you for your helpful response.

For clarification when I use the word telemetry I am using it as it is
described in this [telemetry wikipedia article][wiki] which says
"Telemetry is the in situ collection of measurements or other data at
remote points and their automatic transmission to receiving equipment
(telecommunication) for monitoring."

My interpretation of your response is that kitty's only telemetry is
the update checking.

Those links you shared for how packagers and users can turn off the
update checking telemetry are helpful.

[wiki]: https://en.wikipedia.org/wiki/Telemetry

**Comment by SolitudeSF** [comment]
its not telemetry, since kitty doesnt send any information.

**Comment by kovidgoyal** [comment]
I'm afraid wikipedia, or you, dont get to redefine the meaning of words.
kitty or I DO NOT COLLECT ANY DATA WHATSOEVER, FOR ANY PURPOSE. So
kindly stop misusing words.
