### ISSUE TITLE
autocomplete inserts command at start of line on Zsh

### ISSUE THREAD

**Issue by marcvanheerden** [kovidgoyal/kitty#3803]
**Describe the bug**
When hitting tab to autocomplete, if there is more than one autocomplete option the command gets inserted at the start of the terminal as a piece of text that you cannot remove. 

For example if you type:
`cd Do` then hit tab you get this on your command line:
`cdcd Do` and if you backspace you can't remove the first `cd`. 

**To Reproduce**
1. autocomplete by pressing tab for a starting text that has more than one possible autocomplete e.g. `cd Do` that could be `cd Downloads` or `cd Documents`.

**Screenshots**
before hitting tab:
<img width="304" alt="Screenshot 2021-07-05 at 21 08 48" src="https://user-images.githubusercontent.com/11750833/124511004-580dbd00-ddd5-11eb-8a80-ebde9c6eeabd.png">
after hitting tab:
<img width="256" alt="Screenshot 2021-07-05 at 21 08 55" src="https://user-images.githubusercontent.com/11750833/124511033-68259c80-ddd5-11eb-9656-12337b32daa4.png">
the added text cannot be removed and doesn't affect the next command:
<img width="296" alt="Screenshot 2021-07-05 at 21 09 10" src="https://user-images.githubusercontent.com/11750833/124511053-72479b00-ddd5-11eb-97a4-739026b7ef15.png">

**Environment details**
```
zsh 5.8 (x86_64-apple-darwin20.0)

vim keybindings on

kitty 0.21.2 created by Kovid Goyal
Darwin JOHMAC-41745-2 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.4 BuildVersion:	20F71
Loaded config files:
  /Users/41745/.config/kitty/kitty.conf

Config options different from defaults:

```

**Additional context**
No kitty config options set

**Comment by kovidgoyal** [comment]
I cannot replicate. And autocompletions are handled by the shell, not
the terminal.

**Comment by marcvanheerden** [comment]
Fully understand why you have closed this, just want to mention that for the exact same shell the issue does not occur in iTerm2 and since the inserted text is not editable I think this might be a display issue and not an issue in the shell.

**Comment by kovidgoyal** [comment]
Set your TERM env var to xterm-kitty.
