### ISSUE TITLE
Running `./gen-config.py` results in unstaged changes.

### ISSUE THREAD

**Issue by williamspatrick** [kovidgoyal/kitty#3805]
Using current master commit (46fbf78da542703aecb3e6c46aba2ffbd2ea55d8), if you run `gen-config.py` it modifies `kitty/options/types.py`.  I suspect this isn't intended and some changes got into `kitty/options/types.py` without corresponding changes in `kitty/options/definition.py`.

**Comment by kovidgoyal** [comment]
It is intended, options/types.py and options/parser.py are
auto-generated by gen-config. See the comment at the top of the files.

**Comment by Luflosi** [comment]
@kovidgoyal I think you misread. As I understood @williamspatrick he knows that the file is auto grnerated and is saying that you should run gen-config.py because the auto-generated files are out of sync with the manually written files.

**Comment by williamspatrick** [comment]
> @kovidgoyal I think you misread. As I understood @williamspatrick he knows that the file is auto generated and is saying that you should run gen-config.py because the auto-generated files are out of sync with the manually written files.

Right. Exactly this. 

I was introducing a new config and ran the script. It broke http link selection and I did some investigation and realized the file had way more changes than I expected.

**Comment by kovidgoyal** [comment]
Ah, ok, now fixed.
