### ISSUE TITLE
Kitty diff results in `ValueError: line too long`

### ISSUE THREAD

**Issue by igorepst** [kovidgoyal/kitty#3806]
Hello Kovid,
I tried to run `kitty +kitten diff` on 2 directories, but had a crash, using `kitty 0.21.2` on ArchLinux:

    Exception in callback DiffHandler.generate_diff.<locals>.diff_done({'/home/vasya/.../xmobar/build': <kittens.diff...x7feea33b9d90>, '/home/vasya/.6
    Traceback (most recent call last):
    File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 154, in diff_done
    self.render_diff()
    File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 202, in render_diff
    self.diff_lines: Tuple[Line, ...] = tuple(render_diff(self.collection, self.diff_map, self.args, self.screen_size.cols, self.image_manager))
    File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 543, in __call__
    yield from ans
    File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 367, in lines_for_diff
    yield from lines_for_chunk(data, hunk_num, chunk, cnum)
    File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 328, in lines_for_chunk
    ll.extend(render_half_line(
    File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 291, in render_half_line
    lines: Iterable[str] = split_with_highlights(line, available_cols, highlights, bg_highlight)
    File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 215, in split_with_highlights
    return _split_with_highlights(line, truncate_pts, highlights, bg_highlight)
    ValueError: line too long

I run `kitty --dump-bytes dump.bin --config NONE` and from then `kitty +kitten diff /home/vasya/.config/xmobar/ /home/vasya/.config/xmonad/` where both directories has some sub-folders with git submodules (named `...-git`) + `hiedb` and `dist-newstyle` subdirs generated by Haskell compiler + a bit of source code and project definitions in each.
Both compared directories are links to `~/dotfiles-reboot/links/config/xmo{nad,bar}`
Attached are `tree` output of the directories and `dump.bin` renamed to `dump.txt`.
Thanks!
[xmonad.txt](https://github.com/kovidgoyal/kitty/files/6772112/xmonad.txt)
[xmobar.txt](https://github.com/kovidgoyal/kitty/files/6772113/xmobar.txt)
[dump.txt](https://github.com/kovidgoyal/kitty/files/6772117/dump.txt)

**Comment by kovidgoyal** [comment]
That indicates that one of the diffed files has a very long single line,
the kitten has a limit on very long lines. I might get around to
removing that someday, but its not a priority for me, patches welcome.

**Comment by kovidgoyal** [comment]
Now fixed in master

**Comment by igorepst** [comment]
@kovidgoyal Works perfectly. I tested with the same directories. Thank you!
