### ISSUE TITLE
Question: On Mouse Support and Multiple Configurations

### ISSUE THREAD

**Issue by HaoZeke** [kovidgoyal/kitty#381]
Hi.

Coming from `tilda`, I'm having trouble understanding how to use the mouse here.
I run a `tmux` session within kitty, however I can't seem to copy anything.
The mouse simply highlights text.

Also does `kitty` support multiple configuration files? I've set it up with `tdrop` however, I have a mini terminal whose font I ideally wish to keep smaller than my main scratchpad.

Thanks in advance!

**Comment by kovidgoyal** [comment]
Use --config and see kitty.conf for the key combination to copy or a setting to copy on highlight.
