### ISSUE TITLE
Simple contribution: a kitty terminal cheasheet

### ISSUE THREAD

**Issue by jmcastagnetto** [kovidgoyal/kitty#3813]
You can find the PDF, latex file and Rmarkdown document at https://github.com/jmcastagnetto/kitty-terminal-cheatsheet
Basically lifted the documentation from your site, cut some details, and reformatted into RMarkdown. 

A small token of thanks for the great terminal application you've made.

**Comment by kovidgoyal** [comment]
Looks useful, thanks!
