### ISSUE TITLE
Kitty crashes Cinnamon window manager

### ISSUE THREAD

**Issue by mcarans** [kovidgoyal/kitty#3814]
**Describe the bug**
This project looks great, but I cannot get it to work. When I install Kitty and launch it, the window manager stops working. All I can do is go to the login shell, kill kitty and then restart Cinnamon.

**To Reproduce**
1. Install Kitty
2. Launch it
3. Crash

**Environment details**
It crashes whether I use the version of Kitty from the Ubuntu repository or the one from
`curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin`

System:    Kernel: 5.11.0-22-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.4 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
           
Graphics:  Device-1: Intel vendor: ASUSTeK driver: i915 v: kernel bus ID: 0000:00:02.0 
           chip ID: 8086:9a49 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
           resolution: 2560x1440~60Hz 
           OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 20.2.6 
           direct render: Yes

**Comment by kovidgoyal** [comment]
This will be a bug in your window manager/graphics drivers. Update them
and/or report the bug against them.

**Comment by mcarans** [comment]
@kovidgoyal I had a look in /var/log/syslog and saw this:
```
Jul  9 15:25:05 Holly kernel: [21399.426828] Asynchronous wait on fence 0000:00:02.0:cinnamon[2374]:63928 timed out (hint:intel_atomic_commit_ready [i915])
Jul  9 15:25:09 Holly kernel: [21403.270546] i915 0000:00:02.0: [drm] GPU HANG: ecode 12:1:84dffffc, in kitty [49028]
Jul  9 15:25:09 Holly kernel: [21403.373546] i915 0000:00:02.0: [drm] Resetting rcs0 for stopped heartbeat on rcs0
Jul  9 15:25:09 Holly kernel: [21403.373585] i915 0000:00:02.0: [drm] kitty[49028] context reset due to GPU hang
```

Does this look like a windwo manager or graphics driver problem as I'm not sure which to raise this against?

**Comment by kovidgoyal** [comment]
Graphics driver

**Comment by mcarans** [comment]
Thanks, I found someoen else had [the same problem](https://gitlab.freedesktop.org/drm/intel/-/issues/2700) and I installed a newer version of Mesa which fixed it
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update
sudo apt install mesa
```
