### ISSUE TITLE
Implement a process guard

### ISSUE THREAD

**Issue by quentinhill** [kovidgoyal/kitty#3819]
**Is your feature request related to a problem? Please describe.**
There are times when I have a long running and/or important process running in a terminal. Closing one of these windows at the wrong time could lead to anything from lost time to data loss.

**Describe the solution you'd like**
I would like Kitty to ask confirmation before closing windows if a process is running inside it.

**Describe alternatives you've considered**
There is an existing [confirm_os_window_close](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close) setting, but it applies to all open windows, regardless of process running status.

**Comment by kovidgoyal** [comment]
There is no way to do that. You can ssh into a computer and run a
process or a shell, and there is no way for the terminal emulator to know
which. Similarly you could background a process in a shell.

So either you confirm for all windows or you dont confirm.
