### ISSUE TITLE
Fatal crash solvable only by a reboot on Intel 11th gen CPUs utilizing Intel IRIS XE GPU

### ISSUE THREAD

**Issue by mpilka** [kovidgoyal/kitty#3820]
**Describe the bug**
When launching Kitty on an Intel 11th generation CPU, it crashes X server, only viable option is reboot.

**To Reproduce**
1. Launch Kitty on an Intel 11th generation CPU (utilizes IRIS XE GPU)
2. Screen will start to flicker, while cursor still moves, one is unable to interact with any GUI elements. Only reboot helps (not even killing Kitty process in a console, where it is still possible to switch).

**Screenshots**
N/A

**Environment details**
N/A

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
This will be a bug in the GPU driver, report it to mesa.

**Comment by mpilka** [comment]
Hello Kovid,

yes, it might be a case that bug is in Mesa. However please note that Kitty is the only program crashing on these two new ThinkPads using Intel i7 Gen 11.

Closing this without any investigation seems like a premature judgment to me - next time I will rather not report anything.

Cheers,
Martin

**Comment by kovidgoyal** [comment]
So? There have been lots of bugs in mesa that have caused kitty to crash. And checking that the crash is in mesa is trivial, get a backtrace from the crash, you will see it is in mesa's drivers. If you find it is in kitty code, feel free to update.
