### ISSUE TITLE
macOS: Text colors are rendered in display-native colorspace instead of sRGB

### ISSUE THREAD

**Issue by AprilArcus** [kovidgoyal/kitty#3823]
Colors are specified in the kitty config file as 24-bit hexadecimal RGB triplets. Without any colorspace information, hex RGB triplets are ambiguous, and have conventionally been interpreted within the sRGB color space (e.g. in the W3C CSS standard, starting with [version 1.0](https://www.w3.org/TR/CSS1/#color-units) in 1996 and persisting in the [current version](https://www.w3.org/TR/2021/WD-css-color-4-20210601/#resolving-sRGB-values).

Modern displays cover color spaces vastly larger than sRGB. If interpreted within the display's native space without correction, highly saturated colors appear excessively vibrant, impair legibility, and do not match color-corrected presentations in native OS apps, web views, Electron apps, etc. Unfortunately, this is currently the case in kitty on macOS:

The pure red tile #FF0000 is rendered relative to the display's native color space
<img width="684" alt="Screen Shot 2021-07-11 at 12 18 50 AM" src="https://user-images.githubusercontent.com/2045543/125186204-cc819b00-e1dd-11eb-9e92-1f5c2f3178ea.png">

In sRGB space, the color values are reported as "clipped", correctly representing their actual overbright appearance.
<img width="726" alt="Screen Shot 2021-07-11 at 12 22 15 AM" src="https://user-images.githubusercontent.com/2045543/125186256-25513380-e1de-11eb-9275-d65b9fed7552.png">

Here is the same test pattern rendered in macOS terminal. The bright red is "underbright" in native space,
<img width="702" alt="Screen Shot 2021-07-11 at 12 26 42 AM" src="https://user-images.githubusercontent.com/2045543/125186340-c344fe00-e1de-11eb-9026-87d146bb7ea8.png">

but correct in sRGB space (within the error of rounding), and the overall presentation is correct and matched to web content.
<img width="723" alt="Screen Shot 2021-07-11 at 12 28 39 AM" src="https://user-images.githubusercontent.com/2045543/125186552-cb516d80-e1df-11eb-9a59-06de5644c368.png">

Note that due to the nature of screen capture software, image formats, color profile tagging, varying display performance, calibration, and human vision, it may be difficult to appreciate the difference between these renderings in these images, but the effect is perceptible on recent Mac systems with large-gamut displays.

It would be ideal if kitty interpreted the RGB hex format in sRGB space by default. The W3C has introduced a [new syntax](https://www.w3.org/TR/2021/WD-css-color-4-20210601/#color-function), `color()`, which allows triplets to be tagged with color profiles, and which a future version of kitty could adopt in order to intentionally display colors outside the sRGB gamut.

**Comment by kovidgoyal** [comment]
dup of #2249

**Comment by kovidgoyal** [comment]
And also #3692

**Comment by AprilArcus** [comment]
Hi @kovidgoyal, I read that issue and opened this one since it was closed and the linked PR appeared to only address the rendering of PNG files, not text. If there is now a means to set a color profile for kitty, it is not mentioned in https://sw.kovidgoyal.net/kitty/#configuring-kitty, and my issue reproduces on the current version 0.22.2.

**Comment by AprilArcus** [comment]
Although I could define a config file matching each of the 240 indexed colors (besides my theme colors) to an sRGB equivalent, this solution would
  1. Be tailored to a specific display's colorspace, and become incorrect when attaching an external display with different characteristics.
  2. Not address true color values printed to terminal interfaces, which would remain over-saturated.

**Comment by kovidgoyal** [comment]
As is noted on those issues: Historically terminal colors are
interpreted as device dependent colors, not sRGB colors, one cant just
unilaterally decide to change how they are interpreted at this late
date. Remember colors are not just set in kitty.conf but can also be
directly specified in terminal applications.

**Comment by AprilArcus** [comment]
> one cant just unilaterally decide to change how they are interpreted at this late date

That is a valid interpretation of an underspecified data format (a historical intepretation); another valid interpretation is a pragmatic one: the principle of least surprise, that the observed behavior should match the user's naïve expectation.

As a user, I expect that the same color hex triplets I enter in e.g. a VSCode or Sublime Text theme can be used in a terminal theme and will yield a color-matched result. In practice this is the case with respect to nearly all terminals, as they use OS native color structs or web views which are interpreted in sRGB space by one means or another. kitty's use of display native colors is unusual in this day and age.

**Comment by kovidgoyal** [comment]
On the contrary all terminals I have ever come across interpret RGB colors as device dependent colros. And it would be extremely surprising to me if kitty interpreted rgb colors to match VS Code and Sublime Text rather than say the linux console or the DEC terminals

**Comment by AprilArcus** [comment]
I can't speak to other platforms, but Hyper and VSCode's built-in terminal use sRGB (via web views) and macOS Terminal.app and iTerm use profiled NSColor objects. It is very unusual to ever deal with native display values on a Mac; I can't think of any application which does apart from color calibration software.

**Comment by kovidgoyal** [comment]
Umm #2249 shows that PNG images with color profiles are rendered
correctly and the rgb colors for text match those colors, which
indicates the text colors are rendered correctly as well. If you
disagree I suggest you argue on that issue. 

And think outside the apple ecosystem, there are literally thousands of
terminals that have existed since long before sRGB, they cant have been
using sRGB.

**Comment by kovidgoyal** [comment]
And in https://github.com/kovidgoyal/kitty/issues/2249#issuecomment-671938755 @Luflosi  says kitty and iterm colors match differeing at most by 1 for the same rgb specification, according to digital color meter.

**Comment by AprilArcus** [comment]
> And in [#2249 (comment)](https://github.com/kovidgoyal/kitty/issues/2249#issuecomment-671938755) @Luflosi says kitty and iterm colors match differeing at most by 1 for the same rgb specification, according to digital color meter.

I don't observe this to be the case. Here I've set Monokai Pro's "Magenta" shade (`#ff6188`) in both iTerm and kitty:

![image](https://user-images.githubusercontent.com/2045543/125189054-39e7f880-e1eb-11eb-9513-05474f01eaa9.png)

iTerm renders the correct sRGB values:

<img width="449" alt="Screen Shot 2021-07-11 at 1 57 02 AM" src="https://user-images.githubusercontent.com/2045543/125189166-89c6bf80-e1eb-11eb-8899-7a41b915c733.png">

kitty is overbright in sRGB:

<img width="430" alt="Screen Shot 2021-07-11 at 1 59 23 AM" src="https://user-images.githubusercontent.com/2045543/125189197-b8dd3100-e1eb-11eb-8218-dd4ce9ff90a7.png">

because it is targeting the display's colorspace:

<img width="424" alt="Screen Shot 2021-07-11 at 2 00 49 AM" src="https://user-images.githubusercontent.com/2045543/125189237-e629df00-e1eb-11eb-89de-5421609c5b8e.png">

**Comment by AprilArcus** [comment]
As for the test image linked in #2249, when I imgcat the PNG and compare it to the rendering in Chrome, I again see that the colors have been transposed into display native space and over-brightened / lost calibration.

<img width="898" alt="Screen Shot 2021-07-11 at 2 12 02 AM" src="https://user-images.githubusercontent.com/2045543/125189574-9d732580-e1ed-11eb-8e11-cc9445fcfe20.png">

Chrome (reported as sRGB, correct)
<img width="363" alt="Screen Shot 2021-07-11 at 2 15 07 AM" src="https://user-images.githubusercontent.com/2045543/125189636-e5924800-e1ed-11eb-8774-51d8023a76c2.png">

kitty (reported as sRGB, overbright)
<img width="428" alt="Screen Shot 2021-07-11 at 2 16 06 AM" src="https://user-images.githubusercontent.com/2045543/125189653-022e8000-e1ee-11eb-9468-db62eb3fcca9.png">

kitty (reported as display native)
<img width="313" alt="Screen Shot 2021-07-11 at 2 17 28 AM" src="https://user-images.githubusercontent.com/2045543/125189687-37d36900-e1ee-11eb-8fc6-de9ce76ab241.png">
native)

**Comment by kovidgoyal** [comment]
Like I said argue it in the existing issue with the people that tested it there.

**Comment by Luflosi** [comment]
When I tested it with my 2012 MacBook Air, the colors were pretty much correct but I don't have a modern display and the display color space is probably very similar to sRGB. This is why I came to the incorrect conclusion that kitty handles this correctly.

**Comment by kovidgoyal** [comment]
@Luflosi: So you are saying this needs a fix? Can you try the setting of
srgb colorspace on window and see it does what's needed?
