### ISSUE TITLE
Characters for hints should start with home-row keys and/or be configurable

### ISSUE THREAD

**Issue by con-f-use** [kovidgoyal/kitty#3824]
Currently, when using a function that displays hints (e.g. `kitten hints --type path --program -`), the characters used as hints start with the numbers 1-9, like so:

![image](https://user-images.githubusercontent.com/11145016/125204876-a4e30f00-e27f-11eb-8232-4d42195ecd3b.png)

It would be more accessible and quicker to type for most users to have the first hints be the characters on home row keys.

These should be first, by default (but customizable):
 
<kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd>
<kbd>j</kbd><kbd>k</kbd><kbd>l</kbd><kbd>;</kbd>

Especially, because some keyboard layouts (AZERTY?) require using the <kbd>Shift</kbd> key, or other modifier keys in order to reach the numbers. Home row keys should be the default in my opinion. **Which letters in what order are used for hints should be configurable**, because keyboard layouts and user preferences differ.

**Comment by kovidgoyal** [comment]
They already are configurable, with --alphabet

**Comment by con-f-use** [comment]
Ah my bad, sorry. I see it in the changelog for v0.14.4 and the [documentation for the Hints](https://sw.kovidgoyal.net/kitty/kittens/hints.html). Very good.

How would I use that in the kitty config file?

**Comment by con-f-use** [comment]
I tried to make this a little more obvious in the hint documentation via https://github.com/kovidgoyal/kitty/pull/3826
