### ISSUE TITLE
Support standard mouse interaction like moving cursor on mouse click

### ISSUE THREAD

**Issue by mcarans** [kovidgoyal/kitty#3825]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the mouse to click where I want the cursor to be and to use the right click menu to copy and paste as is common in other applications and in terminals on other OSes.

**Describe the solution you'd like**
Click mouse button, cursor moves to position. Drag to select text, right click, copy.

**Describe alternatives you've considered**
[DomTerm](http://domterm.org/Tips.html#move-cursor-with-mouse) supports using the mouse to move cursor and it is the main reason I use it. Due to limitations with bash readline, the author of DomTerm translates the click position to arrow key presses.

**Additional context**
Another user also asked about the right click copy paste menu in Kitty [here](https://www.reddit.com/r/linux4noobs/comments/iuv58s/how_can_i_enable_the_right_click_mouse_menu_in/).

**Comment by kovidgoyal** [comment]
You can map the right click action to whatever you like, including
copy/paste https://sw.kovidgoyal.net/kitty/conf.html#mouse-actions

There are going to be no right click menus. 

And as for mouse support to move the cursor, use a shell that supports mouse 
interaction, such as zsh. https://developpaper.com/tips-using-the-mouse-to-locate-the-cursor-in-zsh-is-simple-and-direct-saves-time-and-improves-the-efficiency-of-command-line-operation/

**Comment by mcarans** [comment]
@kovidgoyal Thanks. I'm aware that it's possible in other shells. I tried raising it on the bash mailing list which seems to be the only way to raise issues against bash that I could find and I got nowhere. It is one of those features which is standard in the terminals/shells of other OSes and makes Linux look a bit dated since bash is the default shell on most distributions.

**Comment by kovidgoyal** [comment]
On Sun, Jul 11, 2021 at 07:01:28PM -0700, Mike wrote:
> @kovidgoyal Thanks. I'm aware that it's possible in other shells. I tried raising it on the bash mailing list which seems to be the only way to raise issues against bash that I could find and I got nowhere. It is one of those features which is standard in the terminals/shells of other OSes and makes Linux look a bit dated since bash is the default shell on most distributions.

kitty is not the default terminal emulator on any Linux distribution
either, so adding a hack like this for mouse support wouldn't help
Linux's image either. 

Frankly, in this day and age no one should be using bash. There are
much better alternatives, starting with zsh.

**Comment by kovidgoyal** [comment]
This is now implemented, see #3948
