### ISSUE TITLE
kitty terminal should be on snapstore also!

### ISSUE THREAD

**Issue by j0k4rX** [kovidgoyal/kitty#3828]
**Is your feature request related to a problem? Please describe.**
I am on Ubuntu 20.04 LTS and still what am I getting is:  the 2 years old 15.0 version.

**Describe the solution you'd like**
Launch it in snapstore so that we can access the latest version with bugfixes!

**Describe alternatives you've considered**
Try to put some documentation for building kitty from source.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/binary.html 
https://sw.kovidgoyal.net/kitty/build.html

**Comment by j0k4rX** [comment]
@kovidgoyal but still it isn't in snapstore.
What about that?

**Comment by kovidgoyal** [comment]
I have no interest in app stores
