### ISSUE TITLE
Hotkeys not working?

### ISSUE THREAD

**Issue by ChadTaljaardt** [kovidgoyal/kitty#383]
Hello, 

I don't know if I'm doing something wrong, but I'm struggling to use this terminal. 

For instance, on my mac, I try and follow the guide where it tells me to access the settings through the hotkeys ctrl+shift+f2, however, this doesn't do anything for me. 

Hardly any of they hotkeys work for me and I'm not sure if I'm just missing something?

Could anyone assist?

Thanks!

**Comment by kovidgoyal** [comment]
ctrl+shift+f2 is only implemented in master, so if you are using a released version it will not work. All the other shortcuts work fine. Remember that pressing ctrl means pressing the "Control" key on your mac not the Cmd key.
