### ISSUE TITLE
Kitty crashes Laptop.

### ISSUE THREAD

**Issue by Nils75owo** [kovidgoyal/kitty#3830]
I just installed kitty and when i try to open it it crashes my laptop. Even thoug i reinstalled kitty and ubuntu i still have this issue

Video: (sorry for the bad quallity but once i open kitty my pc freezes and the only thing i can do is to move my mouse)
https://user-images.githubusercontent.com/81255505/125497153-2f737713-a3ee-4458-b94f-90137189a3ef.mp4

Versions:
kitty:         0.15.0
i3:            4.16.1
ubuntu:    20.04.2 LTS
terminal:  alacritty 0.9.0-dev

i tried running kitty with the debug options but it didnt work because it froze my pc :/

output of sudo lshw: [lshw.txt](https://github.com/kovidgoyal/kitty/files/6810872/lshw.txt)

sorry this is my first real bug report so just let me know if you need more information (i tried my best please dont be mad:<)

**Comment by kovidgoyal** [comment]
dup of #3814
