### ISSUE TITLE
Ctrl-Shift+C writing `84;6u` into buffer instead of copying selected text sometimes

### ISSUE THREAD

**Issue by BLucky-gh** [kovidgoyal/kitty#3831]
**Describe the bug**
###### A clear and concise description of what the bug is.

Whenever I ctrl-shift+C to copy something kitty sometimes just writes `84;6u` into the terminal. 
It doesn't always happen which complicates the "steps to reproduce part" for me, but I noticed it can happen regardless of whether I just started kitty or not, and closing and reopening the window doesn't help. Waiting a bit helps though. (Also yes, ctrl-shift is my kitty prefix key)

**To Reproduce**
###### Steps to reproduce the behavior:
1. Press ctrl-shift + C (selecting something is not necessary happens regardless)
2. maybe see `84;6u` in the terminal

**Screenshots**
###### If applicable, add screenshots to help explain your problem.
here's me spaming ctrl-shift+c
![image](https://user-images.githubusercontent.com/41377306/125574147-c35f07c4-b7ad-4c60-841b-f074dd3dfb9d.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+, on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

ctrl-shift+f6 didn't seem to work for me so here's --debug-config

```kitty 0.20.3 created by Kovid Goyal
Linux manjaro 5.12.9-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:56:42 UTC 2021 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.7
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
Loaded config files: /home/blucky/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control            y
background                      Color(red=40, green=40, blue=40)
background_opacity              0.9
color1                          Color(red=204, green=36, blue=29)
color10                         Color(red=184, green=187, blue=38)
color11                         Color(red=250, green=189, blue=47)
color12                         Color(red=131, green=165, blue=152)
color13                         Color(red=211, green=134, blue=155)
color14                         Color(red=142, green=192, blue=124)
color15                         Color(red=235, green=219, blue=178)
color2                          Color(red=152, green=151, blue=26)
color3                          Color(red=215, green=153, blue=33)
color4                          Color(red=69, green=133, blue=136)
color5                          Color(red=177, green=98, blue=134)
color6                          Color(red=104, green=157, blue=106)
color7                          Color(red=168, green=153, blue=132)
color9                          Color(red=251, green=73, blue=52)
cursor                          Color(red=254, green=128, blue=25)
cursor_text_color               None
editor                          nvim
enable_audio_bell               False
font_family                     MesloLGSDZ Nerd Font Mono
font_size                       10.0
foreground                      Color(red=235, green=219, blue=178)
inactive_text_alpha             0.8
mouse_hide_wait                 -1.0
resize_draw_strategy            3
scrollback_fill_enlarged_window True
scrollback_pager                ['bat']
select_by_word_characters       @-./_~?&%+#
strip_trailing_spaces           smart
tab_activity_symbol             ACT
tab_bar_edge                    1
tab_bar_margin_width            1.0
tab_bar_style                   powerline
tab_title_template              {index}:{title}
url_color                       Color(red=131, green=165, blue=152)
visual_bell_duration            0.1
window_padding_width            FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)


```

**Additional context**
###### Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Since the issue doesn't always happen I'm not sure if it's not happening with NONE or if it's just not happening at the moment. Also kitty is being spawned by [tdrop](https://github.com/noctuid/tdrop) via ``tdrop -ma -w 80% -h 60% -y "$height" -x 10% kitty --name "dropdown" --config ~/.config/kitty/kitty-drop.conf`` and the kitty-drop.conf is different from kitty.conf only by the window properties (no borders, no decorations, etc) if that makes any difference, otherwise no idea

**Comment by kovidgoyal** [comment]
You are probably running an old version of tmux that has the bug that
turns on kitty's extended keyboard protocol. Update tmux and you will be
fine. Or if you cant do that run 

printf '\e[<u\e[<u'

to turn it off.

**Comment by BLucky-gh** [comment]
Sorry for the late response. I'm not even running tmux since kitty's tabs and windows already do the job for me, so it's definitely not tmux (and tmux is the latest version anyways already even if that were true)

**Comment by kovidgoyal** [comment]
Then something else is trigerring it, some shell/prompt/etc. in any case
the fix remains the same.
