### ISSUE TITLE
Per-window font sizes

### ISSUE THREAD

**Issue by adb-luna** [kovidgoyal/kitty#3832]
Feature:
Just discovered kitty. Like it very much so far! I have an idea that I think is consistent with kitty's goals: I would like to be able to have several windows in a layout, with one being my "main" terminal and the others showing status, etc. I would like to be able to make the "status" windows have a smaller font than the "main" window.

Solution:
Pressing ctrl+shift+equal and ctrl+shift+minus changes the font size of just the current window.

Alternatives:
Haven't thought of any.

Additional context:
None that I can think of.

**Comment by kovidgoyal** [comment]
I'm afraid not, for technical reasons, implementing a per widow font
size is a lot of effort, more than I am willing to put in. Note that
kitty already has per OS window font sizes.
