### ISSUE TITLE
Keyboard resize (ctrl-shift-R) doesn't work

### ISSUE THREAD

**Issue by egnor** [kovidgoyal/kitty#3835]
**Describe the bug**
Keyboard window resizing (with ctrl-shift-R) looks spiffy but I can't get it to work.

**To Reproduce**
1. Launch kitty
2. Press ctrl-shift-R
3. Press any of the resize keys (W, N, T, S)
4. Nothing happens

The Esc key is still handled, and the size changes if the window is resized in the GUI. This seems to be true whether using Wayland or X11 display.

**Screenshots**
![image](https://user-images.githubusercontent.com/279819/125922839-baa776bf-289c-4043-a7b4-c2369ea2fa87.png)
(Not pictured: Me wildly stabbing W, N, T, S; nothing happening.)

**Environment details**
```
kitty 0.21.2 (90164dfee7) created by Kovid Goyal
Linux ostrich 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64
Ubuntu 21.04 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
Running under:X11
Loaded config files:
  /home/egnor/.config/kitty/kitty.conf

Config options different from defaults:
background            Color(red=64, green=0, blue=80)
background_opacity    0.85
font_size             8.0
initial_window_height (25, 'cells')
initial_window_width  (40, 'cells')
linux_display_server  x11
remember_window_size  False
```

**Additional context**
Problem reproduces with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
window resizing refers to the resizing of kitty windows not OS windows.
i.e. of windows internal to kitty managed by layouts
https://sw.kovidgoyal.net/kitty/layouts.html
