### ISSUE TITLE
Kitty opens history viewer from history viewer from...

### ISSUE THREAD

**Issue by Felixoid** [kovidgoyal/kitty#3837]
**Describe the bug**
Kitty does not prevent the opening of history viewer from history viewer. So it can be opened a hundred times. I reached 430 nested windows. **UPD**: ok, it seems like a limit is 512 windows per instance(?).

**To Reproduce**
1. Press `ctrl+shift+h` many times

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux hostname 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64
Arch Linux \r (\l)
Running under:X11
Loaded config files:
  /home/felixoid/.config/kitty/kitty.conf

Config options different from defaults:
background           Color(red=32, green=32, blue=32)
bold_font            Consolasligaturizedv2-Bold
bold_italic_font     Consolasligaturizedv2-BoldItalic
cursor               Color(red=208, green=208, blue=208)
enable_audio_bell    False
font_family          Consolasligaturizedv2
font_size            14.0
foreground           Color(red=208, green=208, blue=208)
italic_font          Consolasligaturizedv2-Italic
scrollback_lines     70000
selection_background Color(red=144, green=144, blue=144)
selection_foreground Color(red=32, green=32, blue=32)
tab_bar_min_tabs     1
tab_title_template   {index}:{fmt.fg.blue}{num_windows}{fmt.fg.default} {title}
Added shortcuts:
        alt+left KeyAction('previous_window')
        alt+right KeyAction('next_window')
        shift+ctrl+z KeyAction('kitten', ('zoom_toggle.py',))
Changed shortcuts:
        shift+ctrl+t KeyAction('new_tab_with_cwd')
        shift+ctrl+enter KeyAction('launch', ('--cwd=current',))
```

**Additional context**
The issue is reproducible even with `--config NONE`.  
Maybe it's a completely different topic, but is it fine that windows counter `{num_windows}` considers history as another window? I don't feel like it's correct, but it is more just thoughts. **UPD**: ok, it make absolutely sense after some more research.

**Comment by kovidgoyal** [comment]
That's by design. The history viewer window is nothing special, its just
a regular overlay window, you can configure it to do pretty much
anything you want, including opening an editor or other program. So
there is no reason to prevent further overlays on it.

As for num_windows it will always count the total number of windows. I
have added a new variable num_window_groups for the count excluding
overlay windows.

**Comment by Felixoid** [comment]
Thank you for clarification and impovement!
