### ISSUE TITLE
New OS window and Close window not work in macos

### ISSUE THREAD

**Issue by thetruechar** [kovidgoyal/kitty#3838]
my conf:
 kitty_mod ctrl+shift
 map kitty_mod+n new_os_window
 map kitty_mod+w close_window

but these two commands have no effect

**Comment by kovidgoyal** [comment]
I cannot replicate on my macOS machine, with

kitty --config NONE -o 'map kitty_mod+n new_os_window'

pressing ctrl+shift+n creates a new OS window, as expected.
