### ISSUE TITLE
Character cell rendering discrepancy compared to other terminals

### ISSUE THREAD

**Issue by wincent** [kovidgoyal/kitty#3844]
**Describe the bug**

Compared to other terminals, Kitty seems to lack a pixel of padding inside its character cells. I wouldn't have noticed this, except for one character (`U+2505`), which renders noticeably different in Kitty compared to other terminals (and for example, compared to this browser too).

**To Reproduce**

1. Paste single (┅) or multiple (┅┅┅) "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL (U+2505, UTF-8: E2 94 85)" characters into the terminal.
2. See no gap between adjacent characters, leading the run of multiple `U+2505` characters to have a "bunched up" appearance.

**Screenshots**

Kitty rendering a run of `U+2505`:

<img width="664" alt="kitty" src="https://user-images.githubusercontent.com/7074/126081053-9514655d-6c19-42cf-9441-179b66d15b5a.png">

(Above screenshot taken on macOS Big Sur with Adobe Source Code Pro font, but I get the same with different fonts, and also on different OS — eg. Arch Linux.)

iTerm2 rendering a run of `U+2505`:

<img width="536" alt="iterm" src="https://user-images.githubusercontent.com/7074/126081055-68fd0288-ae08-4685-be4a-eb866f8aa249.png">

FWIW; here's how Chrome renders the above on this machine:

<img width="292" alt="Screenshot 2021-07-18-222616-VoK1c34Z@2x" src="https://user-images.githubusercontent.com/7074/126081229-239edbca-b0ee-4da5-bca0-c11651fd6604.png">

Another way of looking at it — note how the glyph extends right up to the edge of the character cell (indicated by the cursor) in Kitty:

<img width="332" alt="kitty-padding" src="https://user-images.githubusercontent.com/7074/126081083-9abf25cf-64d5-43ae-8f91-5b57ab22e0c6.png">

In iTerm, the glyph has a small amount of padding between the outer edges of the dashes and the character cell:

<img width="328" alt="iterm-padding" src="https://user-images.githubusercontent.com/7074/126081087-44f65dda-7a93-4d50-a119-49e71c9476c7.png">

I also looked at this in Terminal.app on macOS, and in st on Arch Linux; basically all of them render the same way, except for kitty.

I also ran kitty with `kitty --debug-font-fallback` to confirm that it really is using Adobe Source Code Pro front for this glyph and not some other random thing; it is using the font. The macOS font viewer says that character is supposed to look like this (note the padding on the left and right edges):

<img width="137" alt="font" src="https://user-images.githubusercontent.com/7074/126081168-72ba101f-3112-4f90-9740-5305b7841713.png">

**Environment details**

```
kitty 0.21.2
```

(Sorry, couldn't get the debug info shortcut to work, but this is on a new copy of Kitty installed today via Homebrew on macOS, and a recent install of Kitty on Arch Linux.)

**Additional context**

I don't know if this is a "bug" or not, but it is a discrepancy in the way Kitty renders relative to other terminals.

Workaround: seeing as I am only using this glyph to indicate tab stops in Vim, I am just going to switch to a different glyph so as to avoid the clumped appearance.

**Comment by wincent** [comment]
Forgot to mention; this behavior isn't affected by `adjust_column_width`; I've got it at `0` in those screenshots, but if I increase it to `1` or `2`, it makes each cell wider, but the glyph still extends all the way to the edge of the cell.

**Comment by kovidgoyal** [comment]
kitty doesn't draw those characters from fonts, they are rendered
programmatically, see box_drawing.py. The algorithm for them currently does
not include side gaps, as they are treated the same as the similar box
drawing chars without holes. I dont really have an opinion on whether
that is the "correct" rendering for them or not. Generally the whole
point of box drawing characters is that they must extend to cell
boundaries and line up perfectly, however I can see a case for adding
gaps to these, sadly the standard doesn't specify how they should be
rendered: https://unicode.org/charts/PDF/U2500.pdf

**Comment by wincent** [comment]
Thanks @kovidgoyal!
