### ISSUE TITLE
MacOS: new_os_window doesn't work when valid arg is provided

### ISSUE THREAD

**Issue by markmcb** [kovidgoyal/kitty#3846]
Consider this in kitty.conf:
map kitty_mod+n 		new_os_window "/some/simple/menu.sh"

In Linux, this works fine and opens a new window with that shell script running. In MacOS, the new window appears and then immediately closes. No error is visible.

Note 1: if you use a bad path, e.g., "/this/path/is/wrong.sh" the window will appear, stay open, and report the path error. (As expected. Just calling this out to call out that a bad path is not the problem above.)

Note 2: that same menu.sh works just fine in startup_session.conf 

Version 0.21.2
Confirmed on MacOS 12 Beta and MacOS 10.15.7

**Comment by kovidgoyal** [comment]
Your script is exiting. If you want to read the error messages, if any,
run it like this

new_os_window sh -c "/your/script.sh; read"

**Comment by markmcb** [comment]
Boy do I feel dumb. Indeed I was missing a dependency on both laptops. I won't bore you with the details, but both had completely unrelated events that removed the dependency.  ¯\_ (ツ)_/¯

Thanks for the quick response.
