### ISSUE TITLE
TerminessTTF Font "antialiasing" bug

### ISSUE THREAD

**Issue by raven2cz** [kovidgoyal/kitty#3847]
**Describe the bug**
I'm using kitty with TerminessTTF Nerd Font. See attached screenshot with kitty font configuration and with bug too. The problem is font italic which is wrongly process. There are missing many parts of letters like B, M, F, etc. It seems that it is the problem of the antialiasing algorithm which is used.
I tried to compare results with urxvt, alacritty and others, the font is correct in all next terminals without kitty.
But I'm using primary kitty :(

**To Reproduce**
See screenshot with settings and bug.

**Screenshots**
Screenshot attached.

**Environment details**
```
OS: Arch Linux x86_64 
Kernel: 5.12.15-arch1-1
WM: awesome
kitty 0.21.2 created by Kovid Goyal
aur/nerd-fonts-terminus 2.1.0-4 [+8 ~0.19]
```

**Additional context**
Not necessary.

![kitty-font-italic-antialiasing-bug](https://user-images.githubusercontent.com/20504243/126270792-72c9197a-31e8-4cf7-8004-bb2e7227519a.png)

**Comment by kovidgoyal** [comment]
That will be because the italic face has metrics that dont fit in a
cell. Use a font that has monospaced italics/bold faces. Or if you
really want to stick with this font, use adjust_cell_width in kitty.conf
to increase the cell size.
