### ISSUE TITLE
Mac: keyboard shortcut opens new instance of app always

### ISSUE THREAD

**Issue by prabhu-madanagopal** [kovidgoyal/kitty#385]
Thanks for the great app!

In Mac, the keyboard shortcut always seem to open a new instance of the app, this hangs the app as each time a new instance is created.

My ~/.skhdrc:

```
# open terminal, blazingly fast compared to iterm/hyper
cmd - return : open -a /Applications/Kitty.app
cmd - d      : open -a /Applications/IntelliJ\ IDEA.app
cmd - i      : open -a /Applications/Safari.app

```
Please note the sample skhdrc config had open command with -na option which is supposed to open a new instance anyway, that didn't work too, it hanged. So I changed to open -a which expected to work, but doesn't, that is the problem.

Only custom setting I have is,  I had to edit the kitty.app/Contents/MacOS/Info.plist file to pass the --config to override the default config. Will that be a problem?

**Comment by kovidgoyal** [comment]
If you want to open new windows in an existing kitty instance when invoking kitty, use the --single-instance argument. See kitty --help for details.

**Comment by prabhu-madanagopal** [comment]
@kovidgoyal --single-instance (and --instance-group) does not behave as expected.

This is my startup command that I use in Info.plist of Mac App bundle:

```
#!/usr/bin/env bash
/Applications/kitty.app/Contents/MacOS/kitty_cmd --single-instance --instance-group=my_group --config ~/.config/kitty/kitty.conf &

```

When open -a /Applications/Kitty.app is invoked, the expected behavior is open a new application if it is not already opened else 'focus' on a existing app that is already running.

With --single-instance (and/or --instance-group) although I get the focus after an one second lag (maybe due new window creation), the real problem is after I switch between Kitty and Safari 3 times, Kitty is super slow (it seems every time I switch using --single-instance something is created).

Having a direct keyboard shortcut to Kitty is super important as it is the most frequently used app for me. The open -a iTerm.app command works for iTerm. I have explored solutions from tiling window manager to get the focus although they provide relative focus from left, right and so on, for direct focus shell command is needed.

Thanks for your help!

**Comment by kovidgoyal** [comment]
I have no idea what you are doing. If you want to have a single key press to launch kitty, you bind that keypress to

```
/Applications/kitty.app/Contents/MacOS/kitty --single-instance
```

That will cause every such keypress to create a new kitty window in the single kitty instance. 

Using open -a kitty will cause either:

1) kitty to start if not already running
2) kitty to become the foreground application if it is already running

That is exactly the same as for Terminal.app or iTerm2

**Comment by prabhu-madanagopal** [comment]
Problem solved! Thank you!
For some reason Mac was opening new Kitty app on open -a if I use a launcher script in application bundle. So I put back the config file from ~/.config (where I wanted) back to original location in ~/Library and removed the launcher script from app bundle. And it works!

**Comment by kovidgoyal** [comment]
You can just create a symlink from ~/Library/Preferences/kitty to ~/.config/kitty
