### ISSUE TITLE
Add to the FAQ another option for TERM=xterm-kitty issue

### ISSUE THREAD

**Issue by Felixoid** [kovidgoyal/kitty#3853]
**Is your feature request related to a problem? Please describe.**
In #713 it's a quite hot discussion without an actual solution for a problem. But there is a solution coming in https://github.com/openssh/openssh-portable/commit/f64f8c00d158acc1359b8a096835849b23aa2e86

**Describe the solution you'd like**
Since OpenSSH version 8.7 (I assume) the `SetEnv TERM=any-string-here` will work as expected, so it's a good thing to add in FAQ

**Comment by kovidgoyal** [comment]
That's not a solution, that's just setting TERM to something
incompatible with kitty which will break things. The solution, as
mentioned in the FAQ is to use the ssh kitten, or some other means, to
get the kitty terminfo file to the remote machine. 

It's nice that openssh is getting a way to specify per host TERM
overrides, but that is not an actual solution, just a bandaid. As is
noted here: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.term
I do not recommend setting TERM to anything other than xterm-kitty.

As I said in the FAQ entry
https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer 
the real solution is for OpenSSH to do what
the ssh kitten does and transport the terminfo file to the remote host
when connecting with a tty.

**Comment by Felixoid** [comment]
Sorry, but your FAQ has the wrong state `ssh kitten takes all the same command line arguments as ssh`:

```
$ kitty +kitten ssh host -- test .
Unknown option: -- # exit code 1
$ ssh ssh host -- test .
$ # exit code 0
```

I'd gladly have the full fixed and shiny world w/o legacy, but world has a lot of flaws. And most of us must find work around them. :-j

So OpenSSH is not able to handle all cases in the modern world. As well as the ssh kitten is not a 100% replacement, since it is not executed by, for example, rsync and all the things that uses ssh under the hood. Alias is not really a solution, it should be a binary.. and the rabbit hole is quite deep already.

As `kitty +kitten ssh` already has some exceptions in the FAQ, like `python is not installed on the host...` and `for FreeBSD...`, my humble opinion is that the new capabilities of OpenSSH itself are worth to be mentioned in FAQ too.

with best wishes!

**Comment by kovidgoyal** [comment]
The point is setting TERM is not a solution. It will *break* things.

**Comment by kovidgoyal** [comment]
Oh and the issue with -- is now fixed. And rsync doesn't need to use the ssh kitten, because it does run an interactive session, it's perfectly fine using plain old ssh.

**Comment by Felixoid** [comment]
> the issue with -- is now fixed

Thank you

> it's perfectly fine using plain old ssh.

I assume the same would be a valid point for things like parallel executers like pdsh or polysh too. Sounds good. Thank you once again.

**Comment by kovidgoyal** [comment]
Yes, the only time you need to use the ssh kitten is if you are starting an interactive session, hence aliasing ssh to it is the perfect solution.
