### ISSUE TITLE
mouse_click_url_or_select stopped working

### ISSUE THREAD

**Issue by Felixoid** [kovidgoyal/kitty#3859]
**Describe the bug**
On left-clicking the terminal does nothing

**To Reproduce**
1. Open the terminal as `kitty --config NONE`
2. Insert any url
3. The URL is highlighted and has underlined, but the click does nothing. The shift+ctrl_click works

**Screenshots**

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux felix-lm 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64
Arch Linux \r (\l)
Running under:X11

Config options different from defaults:
```

**Additional context**
I am not sure if it's my or kitty's problem. I am mostly sure, that it's mine. But then I'd like to help with debugging it. Is there additional information I can give?

**Comment by kovidgoyal** [comment]
Run 

kitty --debug-input

and click the url and post the log

**Comment by Felixoid** [comment]
I removed the same lines from the log `Move mouse_button: -1 mods: none grabbed: 0`, there is the rest
[kitty-debug-input.log](https://github.com/kovidgoyal/kitty/files/6870582/kitty-debug-input.log)

**Comment by kovidgoyal** [comment]
Turn off numlock, does it work then?

**Comment by Felixoid** [comment]
Yes, it helped. Just built the code from master.

Thank you!
