### ISSUE TITLE
How to change the focused window color

### ISSUE THREAD

**Issue by zkwinkle** [kovidgoyal/kitty#3863]
The default green for the focused window is fine, but i'd like to configure it to work better with my overall pink theme i got going for my system, is there a way to change it? Couldn't find it in the docs or in any other issue.
![image](https://user-images.githubusercontent.com/4276704/126883413-223e8768-8737-4ea4-8f37-436c3c8453a6.png)

Sorry if this issue is a little small and silly, but I'm following in the steps of what was said in [this issue asking about where to ask](https://github.com/kovidgoyal/kitty/issues/436).

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.active_border_color
