### ISSUE TITLE
[Feature request] Add a command palette to kitty

### ISSUE THREAD

**Issue by tddschn** [kovidgoyal/kitty#3865]
**Is your feature request related to a problem? Please describe.**
kitty has many amazing features, but 
- Some of them are not very discoverable without reading the doc.
- I always forgot the keyboard shortcut for some infrequently used features and have to consult the doc when I try to use them.

**Describe the solution you'd like**
I wish there's a Command Palette in kitty, like the ones in VS Code / Chrome DevTools, where users can
- Typing in command names to look up the keyboard shortcuts
- Discover features they haven't used before
- Use features without having to remember keyboard shortcuts
- Use features the shortcuts for which are conflict with the OS's global (user-defined) keyboard shortcuts

**Describe alternatives you've considered**
To help discovering features and looking up keyboard shortcuts, add an option to `kitty` that outputs features, short description of features, and corresponding keyboard shortcuts, like so:
```
$ kitty --help-features

feature                description                                keyboard shortcuts
Reload kitty.conf	   Reload config without restarting kitty     ctrl+shift+f5 (also ⌘+option+f5 on macOS)
...
```

**Additional context**
An screenshot of Command Palette in VS Code: 
<img src=https://user-images.githubusercontent.com/45612704/126981817-303cded8-f5ef-4ff8-bd8b-49c991e7173d.png width=600>

**Comment by kovidgoyal** [comment]
This has been on my TODO list for the longest time, however I have too
many higher priority things that only I can do. This should be simple
enough for someone else to tackle. PRs welcome and I am happy to give
any tips needed. 

Note you can browse the list of kitty shortcuts (and config options)
via man 5 kitty.conf and use search there to quickly find what you are
looking for, however its not quite as convenient as a dedicated search
tool obviously. Or of course use: https://sw.kovidgoyal.net/kitty/conf/ 

Or use the cheatsheet here: https://github.com/jmcastagnetto/kitty-terminal-cheatsheet

**Comment by olejorgenb** [comment]
https://github.com/kovidgoyal/kitty/discussions/8317#discussioncomment-12135019 (TLDR; press ctrl+shift+esc and `action <tab-to-complete>` It has some quirks, but decent)
