### ISSUE TITLE
[Feature request] Ability to open tabs with custom shell

### ISSUE THREAD

**Issue by tddschn** [kovidgoyal/kitty#3866]
**Is your feature request related to a problem? Please describe.**
I mainly use `zsh`, with a long .zshrc and it starts slow.
Sometimes I want to go to a new tab to do something simple, and I'd like to use `bash` in that tab because it starts super fast. I don't want to wait for a few seconds for the new tab to load `zsh` and than do `exec bash` (or something like that).

**Describe the solution you'd like**
Add a keyboard shortcut bound to a command that when invoked, prompt user to choose from a list of shells for use in the new tab. If the user chooses `$CHOSEN_SHELL`, a new tab is opened with that shell.

**Describe alternatives you've considered**
Like described above, but instead of providing a list of shell for users to choose, let user choose what to run in the new shell. If the user types in `sh`, a new tab is opened and rans `sh` directly.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/launch/

**Comment by tddschn** [comment]
@kovidgoyal Thank you, 
is there a way I can `launch` arbitrary command using the `kitty` command?
(Without registering them in the config and binding keyboard shortcuts)

E.g. `kitty --launch sh`

**Comment by allemangD** [comment]
The command would look like `kitty @launch sh`. You can check `kitty @launch --help` for more options.

**Comment by kovidgoyal** [comment]
kitty sh

**Comment by tddschn** [comment]
I think on macOS `kitty sh` or `kitty $cmd` is just the same as `kitty`, which opens a new kitty (GUI) window, and doesn't run `$cmd`.

**Comment by kovidgoyal** [comment]
No, it isn't. Make sure you are running the actual kitty binary and not
some wrapper script.

**Comment by tddschn** [comment]
@allemangD Thank you! This works. :)
