### ISSUE TITLE
Some Font Sizes Cut Off Bottom of Text

### ISSUE THREAD

**Issue by CaptainKraft** [kovidgoyal/kitty#387]
With font size set to 13, text is fine. At 14, 15, etc. bottom of text is cut off. For example, underscores are not visible.

Changing the font family doesn't seem to change anything.

Edit: Just "fixed" the issue by changing line height from 0 to 1

**Comment by kovidgoyal** [comment]
With what font? On what OS? cell height calculation is done via metrics from the font. If the font you are using has incorrect metrics, then this can happen, you can workaround it using the adjust_line_height setting in kitty.conf

**Comment by fenetikm** [comment]
...actually that didn't work out so well and instead setting it to `-1` totally did the trick.

**Comment by kovidgoyal** [comment]
dup of #1173
