### ISSUE TITLE
Ligatures are multicolored 

### ISSUE THREAD

**Issue by shaunsingh** [kovidgoyal/kitty#3879]
Firstly, thank you for this excellent terminal emulator. Loving it so far, its the only gpu-accelerated terminal that supports ligatures I've found. 

**Describe the bug**
Ligatures with fish syntax highlighting are multicolored

**To Reproduce**
1. Download kitty on macOS
2. Set the font to a ligature supported font (I'm using FiraCode Nerd Font)
3. See multicolored ligatures 

**Screenshots**
<img width="278" alt="image" src="https://user-images.githubusercontent.com/71196912/127393008-06e947d0-6498-4d09-bcad-7a48949b8fd5.png">

Compared to iterm: 
<img width="156" alt="image" src="https://user-images.githubusercontent.com/71196912/127393317-1be15970-2c4a-48cd-b2c8-f1035bf93633.png">

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+, on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
```

(cmd+option+F6 produces the following output: 
```
~
❯ [17;11~
```
Please let me know if I'm doing anything wrong 

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

I can reproduce it using the following config: 
```
font_family      FiraCode Nerd Font Retina
italic_font      FiraCode Nerd Font Light
bold_font        FiraCode Nerd Font Bold
bold_italic_font FiraCode Nerd Font SemiBold
```

**Comment by kovidgoyal** [comment]
That's a feature. Or more exactly that is a consequence of how terminals
work. A ligature is spread over multiple cells, each cell can have its
own formatting. It's the responsibility of the terminal program to not
color the cells in a potential ligature differently. Of course the
terminal emulator could potentially override this, but this would mena
that terminal programs that do have legitimate reasons to color parts of
a ligature differently cannot do so anymore.
