### ISSUE TITLE
Set font to specific value in running terminal

### ISSUE THREAD

**Issue by ashiklom** [kovidgoyal/kitty#388]
I know it's possible to resize fonts by X amount with Control + Shift + +/i, but is there a way (via remote command, or otherwise) to set the font size of a running terminal to a specific value? Perhaps something like:

```
kitty @ set-font-size 10
```

If not, this seems fairly straightforward to implement given the existence of font size controls already.

**Comment by kovidgoyal** [comment]
Sure it's pretty easy, I'll leave it to you ;) To get you  started, look in remote_control.py to define a new remote command. The actual implementation of the command is just one line:

```py
boss.change_font_size(max(MINIMUM_FONT_SIZE, requested_font_size))
```

**Comment by kovidgoyal** [comment]
You can use the existing set_tab_title command as a template it is a simple command

**Comment by ashiklom** [comment]
This is awesome, thank you!
