### ISSUE TITLE
Shell script icons in nerd font are no longer renderd correctly 

### ISSUE THREAD

**Issue by desilinguist** [kovidgoyal/kitty#3884]
**Describe the bug**
Starting with v0.21.2, some of the icons for shell scripts (I am using `lsd` with the Operator Mono font patched to use ligatures) are not rendered correctly. They were rendered correctly in v0.19.0 though so perhaps it's been broken for a while and I didn't notice until today. 

**Screenshots**
Here's the v0.19.0 screenshot (notice the icons next to `start_tunnel.sh` etc.)
<img width="1043" alt="Screen Shot 2021-07-29 at 09 38 02" src="https://user-images.githubusercontent.com/161680/127502564-427d3827-db89-417f-a7e0-de2f11a52878.png">

And here is the screenshot for the same directory listing from v0.21.2 (and v0.22.0 too, I checked):
<img width="1043" alt="Screen Shot 2021-07-29 at 09 40 08" src="https://user-images.githubusercontent.com/161680/127502701-5753c130-d58b-4f34-ac4b-d323ee8feedf.png">

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Darwin M-AI812931 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.4 BuildVersion:	20F71
Loaded config files:
  /Users/nmadnani/.config/kitty/kitty.conf

Config options different from defaults:
background                 Color(red=34, green=34, blue=34)
bold_font                  Operator Mono for Powerline Book
bold_italic_font           Operator Mono for Powerline Book Italic
clipboard_control          ('write-clipboard', 'write-primary', 'read-clipboard', 'read-primary')
cursor                     Color(red=247, green=241, blue=255)
cursor_text_color          Color(red=0, green=0, blue=0)
dim_opacity                1.0
font_family                Operator Mono for Powerline Book
font_size                  18.0
foreground                 Color(red=247, green=241, blue=255)
hide_window_decorations    1
italic_font                Operator Mono for Powerline Book Italic
macos_show_window_title_in menubar
macos_thicken_font         0.75
selection_background       Color(red=247, green=241, blue=255)
selection_foreground       Color(red=54, green=53, blue=55)
tab_bar_style              powerline
tab_powerline_style        slanted
Added shortcuts:
	alt+left KeyAction('send_text', ('all', b'\x1bb'))
	alt+right KeyAction('send_text', ('all', b'\x1bf'))
Changed shortcuts:
	cmd+1 KeyAction('goto_tab', (1,))
	cmd+2 KeyAction('goto_tab', (2,))
	cmd+3 KeyAction('goto_tab', (3,))
	cmd+4 KeyAction('goto_tab', (4,))

```

**Comment by kovidgoyal** [comment]
That looks like it is being rendered in a different font, you can check
with --debug-font-fallback. I suggest the following:

1) Dont use a patched font, it is unnecessary with kitty
2) Instead simply install the nerd fonts on your system and add the
following to kitty.conf to make sure they are used

# Rule for Nerd Fonts
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B Symbols Nerd Font

And you should be fine.

**Comment by desilinguist** [comment]
Great, thank you!
