### ISSUE TITLE
Disable a kitten?

### ISSUE THREAD

**Issue by 2ver** [kovidgoyal/kitty#3886]
Hi, I'd like to disable the `unicode_input` kitten because of very specific use case and I can't seem to find a way to simply turn off a kitten. 

Without going into too much detail, I have a custom keymap created with QMK that inputs Shavian (·𐑖𐑱𐑝𐑾𐑯) characters in programs with the "`control+shift+u` and some numbers that correspond to the code point" keybinding (eg. GTK programs like pcmanfm and Electron ones like Element). It works perfectly in those apps but, in `kitty`, I have to press `return` after each indivial keypress because `unicode_input` doesn't convert the code point to its actual symbol until after that. 

Ideally, I should just be able to do `control+shift+u` + `10450` (not pressing `return` afterwards), for example, and get `𐑐` printed in the `kitty` window.

I tried doing something like this with `map ctrl+shift+u > p send_text all 𐑐` in `.config/kitty/kitty.conf` as a test but that doesn't work because it just pulls up the kitten. 

Essentially, I need either to make `unicode_input` convert the unicode characters immediately or to disable it (or the keybinding to bring it up) so I can use the "key chord" syntax.

Thanks in advance!

**Comment by kovidgoyal** [comment]
If you want to unmap something, you do it by mapping it to no_op
https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

**Comment by 2ver** [comment]
@kovidgoyal, thanks for the tip! Can't believe I missed that last night in my reading of the documentation. Now it works *almost™* perfectly. 

I added the `map ctrl+shift+u no_op` line and then used this syntax: `map ctrl+shift+u>1>0>4>5>0    send_text all 𐑐` to add cases for all the Shavian characters [here](https://github.com/2ver/dotfiles/blob/main/.config/kitty/kitty.conf#L137-L196).

Unfortunately, there is still something wonky with it. A space gets inserted after each of these combos.

![image](https://user-images.githubusercontent.com/71196144/127728785-422791ef-0181-4adf-ad4c-c0ae5fe200b9.png)
It should look like the second line in this image (I had to manually backspace after each keypress to write it) but it comes out as the first line.

I can't see any trailing whitespace (except a newline character) at the end of those lines from my config in my editor so I'm just confused now. 

User error?

**Comment by kovidgoyal** [comment]
Works fine for me with

kitty --config NONE -o 'map kitty_mod+u no_op' -o 'map kitty_mod+u>1>0>4>5>0 send_text all 𐑐' cat

**Comment by 2ver** [comment]
Alright, it was my mistake. I didn't realize QMK unicode input (on Linux) outputs a space after the numbers (presumably because GTK, Electron, ibus, etc. expect one).

Now that I know that, I'm just doing: `map ctrl+shift+u>1>0>4>5>0>space    send_text all 𐑐` so that it gets "eaten" by kitty.

Works great and is *exactly* what I wanted! Thanks for saying it worked correctly for you so I could go in and see what could be different between our setups :)
