### ISSUE TITLE
"Reboot" a split

### ISSUE THREAD

**Issue by resolritter** [kovidgoyal/kitty#3887]
**Is your feature request related to a problem? Please describe.**

Suppose I am running some command in a shell split. Sometimes I am unable to abort it with Control+C if the command becomes unresponsive for some reason, then the split gets stuck in a useless state. As a result I end with a "dead split" and am forced to either

1. Relaunch the terminal
 
or

1. Go to the split
2. Kill it
3. Create a new one
4. Reorganize the tab manually (not only the sizes but also the order of splits, as it was before)

It would be much better if I could just scrap whatever is running in a given split and start a new command - in this case I could simply say something like `kitty @ reboot --match id:4` and the unresponsive split would be usable again with a brand new shell.

**Describe the solution you'd like**

I would like to have a way of "rebooting" a split, which effectively means: replace its command with another new one, but maintain ID, position, size, etc. i.e. only the split's contents are reinitialized but everything else stays as it is.

This is useful for the case I've mentioned of dealing with an unresponsive split without having to close it, open a new one and recreate a tab's organization. I can imagine such command also being useful for quickly reusing a split for different monitoring tools e.g. `top`, `nethogs`, etc. through shortcuts, without having to kill the current foreground program and type the replacement in the shell.

For my case particularly, having to recreate the splits is unwanted also because it will generate new IDs for them and that would complicate some of my scripts.

Note: for my use-case it would not be needed to save the initial command if that's a hassle, I'm perfectly fine with specifying a `--reboot-command` manually.

**Describe alternatives you've considered**

Recreating the splits and resetting the layout is the closest, I believe, but not as clean as rebooting then in-place.

**Comment by kovidgoyal** [comment]
Simply kill -9 the misbehaving program from another terminal window.

**Comment by resolritter** [comment]
> Simply kill -9 the misbehaving program from another terminal window.

I had not considered this. Thanks.

FWIW this is one command one can use to get the foreground process' PID for the window ID 2: `kitty @ ls | jq -r '.[].tabs[].windows[] | select(.id==2) | .foreground_processes[0].pid'`
