### ISSUE TITLE
Artifacts in window shading after changing border type in sway

### ISSUE THREAD

**Issue by bhepple** [kovidgoyal/kitty#3888]
**Describe the bug**
There are artifacts in the window shading after changing the border type in sway.

**To Reproduce**
1. Open a fresh kitty instance
2. Change border type with
```
swaymsg 'border toggle'
```
3. Toggle between floating and regular containers
```
swaymsg 'floating toggle'
```
4. Repeat 2. and 3. (depending on what your window's starting state is)
5. You may also need to
```
swaymsg 'floating enable, resize set 700 900, move position center, border normal'
```
6. Artifacts appear

**Screenshots**
![image](https://user-images.githubusercontent.com/6417002/127718146-c77a59b7-217e-4cd2-a9f4-62a916fbf1db.png)

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux achar 5.12.13-200.fc33.x86_64 #1 SMP Wed Jun 23 16:20:26 UTC 2021 x86_64
\S
Kernel \r on an \m (\l)
Running under:Wayland
Loaded config files:
  /home/bhepple/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    y
focus_follows_mouse     True
font_size               10.0
listen_on               unix:/tmp/kitty-socket
selection_background    Color(red=221, green=221, blue=221)
tab_bar_edge            1
tab_bar_min_tabs        1
tab_bar_style           powerline
touch_scroll_multiplier 16.0
Added shortcuts:
	shift+page_up KeyAction('scroll_page_up')
	shift+page_down KeyAction('scroll_page_down')
	shift+ctrl+f1 KeyAction('launch', ('xdg-open', 'https://sw.kovidgoyal.net/kitty'))
Changed shortcuts:
	shift+ctrl+0 KeyAction('change_font_size', (True, None, 0.0))
	shift+ctrl+tab KeyAction('prev_tab')
```

**Additional context**
Also happens with 'kitty --config NONE'

CPU: Quad Core Intel Core i7-2630QM (-MT MCP-) speed/min/max: 1516/800/2900 MHz 
Kernel: 5.12.13-200.fc33.x86_64 x86_64

sway-1.6-1.fc34.x86_64
wlroots-0.13.0-1.fc34.x86_64
kitty-0.21.2-1.fc34.x86_64

**Comment by kovidgoyal** [comment]
kitty doesn't support turning client side decorations on and off, which
is what border toggle in sway appears to do. If you really need this
functionality for some reason, patches are welcome. Relevant code is in
glfw/wl*

**Comment by bhepple** [comment]
So I now need to script around 'border csd'. Here's what I came up with - [sway-border-tweak](https://gitlab.com/wef/dotfiles/-/blob/master/bin/sway-border-tweak). I bindsym it to $mod+k so I can adjust borders in-flight.

**Comment by kovidgoyal** [comment]
Actually, this should take care of it: 
https://github.com/kovidgoyal/kitty/commit/6bfb704f6f7dc3a35a1e118608ea9687eb8ca778

at least it seems to work in my basic testing on sway.

**Comment by bhepple** [comment]
Thanks for that - impressive turnaround!! I'll try to build and test later today.
