### ISSUE TITLE
Launching a kitty process with ssh/ssh-agent will flush credentials if the EDITOR variable is not set

### ISSUE THREAD

**Issue by stsquad** [kovidgoyal/kitty#3889]
**Describe the bug**

I have my i3/sway environment launch a new kitty process with the ssh command to have a remote shell onto another machine. If the EDITOR variable is not set through a mechanism I haven't quite figured out yet causes my active ssh-agent session to get flushed causing the passphrase to be prompted for.

**To Reproduce**
1. start an ssh-agent
2. set -x SSH_AUTH_SOCK /path/to/sock
3. ssh-add <enter pass phrase>
4. kitty --detach kitty +kitten ssh HOST
5. exit
6. set -e EDITOR
7. kitty --detach kitty +kitten ssh HOST

observe the prompting for pass phrase. Note other agents have also lost their credentials:

8: ssh-add -l

**Environment details**
```
➜  kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Linux zen 5.10.0-8-amd64 #1 SMP Debian 5.10.46-3 (2021-07-28) x86_64
Debian GNU/Linux 11 \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/alex/.config/kitty/kitty.conf
[212 18:04:42.862524] Ignoring unknown config key: adjust_baseline
[212 18:04:42.862813] Ignoring unknown config key: scrollback_fill_enlarged_window
[212 18:04:42.862938] Ignoring invalid config line: url_excluded_characters
[212 18:04:42.863066] Ignoring unknown config key: mouse_map
[212 18:04:42.863084] Ignoring unknown config key: mouse_map
[212 18:04:42.863100] Ignoring unknown config key: mouse_map
[212 18:04:42.863118] Ignoring unknown config key: mouse_map
[212 18:04:42.863139] Ignoring unknown config key: mouse_map
[212 18:04:42.863166] Ignoring unknown config key: mouse_map
[212 18:04:42.863208] Ignoring unknown config key: mouse_map
[212 18:04:42.863248] Ignoring unknown config key: mouse_map
[212 18:04:42.863282] Ignoring unknown config key: mouse_map
[212 18:04:42.863308] Ignoring unknown config key: mouse_map
[212 18:04:42.863336] Ignoring unknown config key: mouse_map
[212 18:04:42.863362] Ignoring unknown config key: mouse_map
[212 18:04:42.863388] Ignoring unknown config key: mouse_map
[212 18:04:42.863404] Ignoring unknown config key: mouse_map
[212 18:04:42.863420] Ignoring unknown config key: mouse_map
[212 18:04:42.863438] Ignoring unknown config key: mouse_map
[212 18:04:42.863462] Ignoring unknown config key: mouse_map
[212 18:04:42.863473] Ignoring unknown config key: mouse_map
[212 18:04:42.863713] Ignoring unknown config key: tab_bar_margin_height
[212 18:04:42.863809] Ignoring unknown config key: tab_powerline_style
[212 18:04:42.864238] Ignoring unknown config key: wayland_titlebar_color
Running under: X11

Config options different from defaults:
font_family  "LiterationMono Nerd Font"
font_size    14.0
url_prefixes ('http', 'https', 'file', 'ftp', 'gemini', 'irc', 'gopher', 'mailto', 'news', 'git')
Added shortcuts:
         shift+control+f5 KeyAction(func='load_config_file', args=())
         shift+control+f6 KeyAction(func='debug_config', args=())
         shift+super+w KeyAction(func='close_os_window', args=())
Changed shortcuts:
         shift+control+e KeyAction(func='open_url_with_hints', args=())
```

**Additional context**

There also seems to be some looseness with the shared SSH_AUTH_SOCK despite not trying to run a single kitty process (no -1) as even with a debug ssh-agent set up it would flush the main one.

**Comment by stsquad** [comment]
I'm not sure if this has some relation to #1869 but it's one of the few places that it cares about EDITOR.

**Comment by kovidgoyal** [comment]
When the EDITOR variable is not set, kitty will run your shell to check
if it is set in there. Presumably you have something in your shell's rc
files causing that. Although, IIRC kitty will only do this if the editor
variable is actually needed for something.

**Comment by stsquad** [comment]
That does leave a few questions.

  - Why does it need to know EDITOR if I'm just using it to contain a ssh session
  - How does it determine which shell to use (SHELL?)
  - Why is it being called with --interactive/--login?

**Comment by kovidgoyal** [comment]
On Sat, Jul 31, 2021 at 11:54:19PM -0700, Alex Bennée wrote:
> That does leave a few questions.
> 
>   - Why does it need to know EDITOR if I'm just using it to contain a ssh session

https://sw.kovidgoyal.net/kitty/glossary/#envvar-VISUAL
and it has no clue what you intend to do with it in the future.

>   - How does it determine which shell to use (SHELL?)

The same way it determines what shell to run when you start it with no
arguments.

>   - Why is it being called with --interactive/--login?

Because lots of people put variable definitions in rc
files that are only sourced by --interactive/--login shells. And of
course VISUAL/EDITOR are actually interactive programs, so it makes
sense if they are defined only for interactive sessions.

**Comment by stsquad** [comment]
> Because lots of people put variable definitions in rc
> files that are only sourced by --interactive/--login shells. And of
> course VISUAL/EDITOR are actually interactive programs, so it makes
> sense if they are defined only for interactive sessions.

It is a bit of a bear trap to have it happen under your feet. In my case a new login shell flushes ssh-agent credentials because they should only be coming in from actual logins.

**Comment by kovidgoyal** [comment]
On Sun, Aug 01, 2021 at 12:09:53AM -0700, Alex Bennée wrote:
> It is a bit of a bear trap to have it happen under your feet. In my case a new login shell flushes ssh-agent credentials because they should only be coming in from actual logins.

To recap, for example, for zsh:

~/.zprofile is read only for login shells
~/.zshrc is read only for interactive shells

If you have a better way to figure out the value of EDITOR on systems
where it is defined only in ~/.zshrc or ~/.zprofile or similar, patches
are most welcome.

And note this is documented https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.editor

**Comment by stsquad** [comment]
In my case (fish) there is only config.fish and I check it's interactivity and login state in the startup. I appreciate this is documented but it took some time to figure out what was going on. Perhaps there is somewhere else to surface this information (FAQ?) so it's more prominent when people are trying to figure out what the breakage could be caused by. I have a workaround for now but ideally I think the probing by sub-shell should be a non-default setting for the editor option (following the principle of least surprise).

**Comment by kovidgoyal** [comment]
I'm afraid the number of people that would be surprised by kitty using the wrong editor to edit their files is much larger than the number of people that would be surprised by kitty running a login shell in the background. In fact on some platforms, for example, macOS, it is the convention to run all shells started in terminal emulators in login mode.
