### ISSUE TITLE
kitty won't exit if there are background jobs

### ISSUE THREAD

**Issue by stelonix** [kovidgoyal/kitty#389]
If I run "lxpanel &" and attempt to exit kitty, it'll echo "exit" but it won't close the window. The shell will be gone but I have to manually close it.

Steps to reproduce:
1) Run a command in the background eg. "lxpanel &"
2) Exit the shell with either CTRL+D or "exit" command
3) Window will not close

Expected behavior: Upon shell exit, the window should close

**Comment by kovidgoyal** [comment]
dup of #378
