### ISSUE TITLE
Implement frame damage tracking on Linux

### ISSUE THREAD

**Issue by Xyene** [kovidgoyal/kitty#3898]
Currently, when kitty calls `SwapBuffers`, it implicitly marks the whole terminal region as having changed from the previous frame. This has cascading effects; a compositor (if any) has to do more compositing work than it needs to, as does any VNC or RDP connection attached to the machine, and this increases both typing latency and power usage.

On Linux, [`EGL_EXT_swap_buffers_with_damage`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_swap_buffers_with_damage.txt) can be used to specify damaged rectangles upstream. This has been supported in Mesa since ~2014, and works for both X11 and Wayland without needing display-server-specific code paths.

On the power-reducing front, [`EGL_EXT_buffer_age`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_buffer_age.txt) can be used to query how many frames it's been since the current backbuffer was last written to. Combined with damage tracking, this can be used to avoid a `glClear` before every frame. Anecdotally, in another project I was involved with where we implemented `EGL_EXT_buffer_age`, it dropped the power draw of an RX 480 GPU from ~60W to ~50W when continually updating ~20% of a frame. This optimization was straightforward to implement after adding support for  `EGL_EXT_swap_buffers_with_damage`.

It would be nice to see these optimization in kitty.

Miscellaneous other things:
* [This](https://emersion.fr/blog/2019/intro-to-damage-tracking/) is a nice article on the topic.
* https://github.com/alacritty/alacritty/pull/2724 is a partial implementation of the above (implementing just the `EGL_EXT_swap_buffers_with_damage` optimization) in alacritty. The consensus from the comments is that this noticeably improved typing latency there.
* There is an unspoken upper limit to the number of damage rectangles an application should report for one frame, probably because performance degrades with too many sparse rectangles. For instance, GDK damages the whole frame if it exceeds 15 individual rectangles, and Sway damages the whole output if the sum of damaged regions in it exceeds 20. I feel like short of running something silly like `cmatrix`, a typical terminal workload should be well within these bounds.

**Comment by kovidgoyal** [comment]
On Tue, Aug 03, 2021 at 09:33:41PM -0700, Tudor Brindus wrote:
> Currently, when kitty calls `SwapBuffers`, it implicitly marks the whole terminal region as having changed from the previous frame. This has cascading effects; a compositor (if any) has to do more compositing work than it needs to, as does any VNC or RDP connection attached to the machine, and this increases both typing latency and power usage.

Unless the terminal is semi-transparent a compositor has to do nothing
but a simple blit, there is no composition involved. Though I agree that
with semi-transparent windows, there is some work.

> 
> On Linux, [`EGL_EXT_swap_buffers_with_damage`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_swap_buffers_with_damage.txt) can be used to specify damaged rectangles upstream. This has been supported in Mesa since ~2014, and works for both X11 and Wayland without needing display-server-specific code paths.

That is certainly better than per display server work. I doubt it is
supported on macOS though. That's not a blocker, but does make it less
worthwhile.

> 
> On the power-reducing front, [`EGL_EXT_buffer_age`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_buffer_age.txt) can be used to query how many frames it's been since the current backbuffer was last written to. Combined with damage tracking, this can be used to avoid a `glClear` before every frame. Anecdotally, in another project I was involved with where we implemented `EGL_EXT_buffer_age`, it dropped the power draw of an RX 480 GPU from ~60W to ~50W when continually updating ~20% of a frame. This optimization was straightforward to implement after adding support for  `EGL_EXT_swap_buffers_with_damage`.

This needs more careful thought/benchmarking. The case where damage
rectangles are useful is when only a small portion of the screen
changes. In a terminal that pretty much only happens when typing at a
prompt, or typing in an editor that does not have a modeline that shows
cursor positions or similar. These changes happen at human typing speed,
which is a lot slower than 60FPS, therefore the power/bandwidth savings
will likely be fairly minimal. kitty already is designed to send just a
few bytes per cell to the GPU when updating the screen, so bandwidth
savings will be insignificant. There could be some savings from not
having to do compositing, but how large remains to be seen.

And on the flip side the terminal now has to do damage tracking which
will cause some performance/memory/CPU utilization loss and will likely
lead to rendering bugs.

I could be wrong and there could be significant savings but I would need
to see some numbers. 

> 
> It would be nice to see these optimization in kitty.

I have no objection to this, but its not something I am going to spend
time on as I am not convinced its worthwhile. But I am happy to help
if you wish to try to implement it yourself. I am going to close this
issue as I don't think its worth my time, but feel free to
continue the discussion and if you are willing to work on it yourself, I
will be happy to provide any needed guidance.

**Comment by Xyene** [comment]
> Unless the terminal is semi-transparent a compositor has to do nothing
but a simple blit, there is no composition involved. Though I agree that
with semi-transparent windows, there is some work.

Agreed in principle, but in practice the time taken for the blit even in the non-transparent case is nontrivial on high-resolution screens.

> That is certainly better than per display server work. I doubt it is
supported on macOS though. That's not a blocker, but does make it less
worthwhile.

The extension itself isn't, but partial updates are supported on macOS and Windows as well (just via different interfaces). For example, they're crucial for things like video playback in browsers on mobile devices to drain less battery (only the video region is damaged rather than the whole browser window). Whatever damage-tracking infrastructure is built for the Linux case could likely easily be generalized for those platforms.

> These changes happen at human typing speed,
which is a lot slower than 60FPS, therefore the power/bandwidth savings
will likely be fairly minimal. kitty already is designed to send just a
few bytes per cell to the GPU when updating the screen, so bandwidth
savings will be insignificant. There could be some savings from not
having to do compositing, but how large remains to be seen.

Agreed, but this isn't so much about power savings (though those exist) as it is about typing latency.

On a VNC connection, the difference between damage tracking and not is night-and-day (hundreds of milliseconds in kitty compared to tens of milliseconds in xterm; trying to use kitty over VNC was what prompted me to write this post).

Even on a local machine, the difference between damage-tracked typing updates and full-frame updates is human-noticeable. I'm happy to provide numbers to back this claim.

I'm currently travelling and away from my PC, but when I get back in a few weeks I could measure kitty's current key-to-photon latency (measured as per [this](https://thume.ca/2020/05/20/making-a-latency-tester/)). Then, I could write up a quick hack that makes kitty damage only the last row of cells to simulate the damage regions kitty might produce if it had damage-tracking support (of course this would totally break rendering, but it'd provide an upper bound on the improvement possible through damage tracking, sans any CPU time spent computing the damage).

Would those be the numbers you'd like to see? I can also benchmark other damage-tracking terminals with their damage tracking turned on/off if you're interested in prior work.

> And on the flip side the terminal now has to do damage tracking which
will cause some performance/memory/CPU utilization loss and will likely
lead to rendering bugs.

Definitely agree, this trades a little CPU time for a lot more GPU time, so we'd usually come out ahead. The rendering bugs are likely, though.

> I have no objection to this, but its not something I am going to spend
time on as I am not convinced its worthwhile. But I am happy to help
if you wish to try to implement it yourself.

I wish I could, unfortunately I don't think I'd have the time to pick up such a change in an unfamiliar codebase anytime soon. I am however happy to provide benchmarks for the potential improvements on the table, in case that may convince you that it is worthwhile (or encourage someone with more free time to pick this up) :)

**Comment by kovidgoyal** [comment]
You are most welcome to provide benchmarks, they will do more than
anything else to convince me. I agree this makes sense over VNC, however
I am pretty sceptical it will make any noticeable key-to-screen latency
difference locally, unless you are driving a full screen terminal on a
huge 5K display, with an anemic GPU. But, I am happy to be proven wrong
and if the difference is significant enough it might even motivate me to
do it.

If you are going to benchmark, I would like to see the following
benchmarks comparing kitty with hack that only damages a single line
rectangle vs normal kitty.

1) with a "regular sized" opaque kitty window (say the classic 80x25
terminal)

2) with a fullscreen window on whatever highest resolution monitor you
have available

I am not particularly interested in benchmarks for other terminals as
kitty has a pretty unique rendering pipeline, where it renders every
cell on the screen independently, in parallel. So I am sceptical of the
relevance of benchmarking other terminals.

If you need help with pointers to where to insert your hack let me know.
