### ISSUE TITLE
Path not decoded correctly in fish shell when launching kitty with Unicode path parameters from macOS GUI apps

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#3899]
**Describe the bug**
When calling kitty from the macOS GUI with Unicode path param, the path obtained by the fish shell is not decoded correctly.

Calling kitty from the command line works fine.

Some macOS apps can only set `kitty.app` as an external terminal and cannot call kitty from command line.

Using kitty's own Services in Finder to open folders containing Unicode can reproduce this issue.

macOS Terminal and iTerm2 can correctly launch the shell with a Unicode path param.

**To Reproduce**
1. Install fish shell and make sure that no configuration is used.
https://github.com/fish-shell/fish-shell

2. Config kitty default shell
```shell
echo "shell /usr/local/bin/fish" > ~/.config/kitty/kitty.conf
```

3. Create a folder with Unicode characters
```shell
mkdir "/tmp/①②③④⑤⑥⑦⑧⑨"
```

4. Make sure kitty is exited.
```shell
osascript -e 'quit app "kitty.app"'
```

5. Select the folder in Finder and choose `New kitty Tab Here` in the Services context menu.
6. There is a decoding issue in the current path of the fish shell.
```
user@host /p/t/â â¡â¢â£â¤â¥â¦â§â¨> pwd
/private/tmp/â â¡â¢â£â¤â¥â¦â§â¨
```

**Screenshots**

Select kitty in the Services context menu to open the folder path.
![launch-kitty-gui](https://user-images.githubusercontent.com/57713011/128126841-57d61aae-6916-4c9e-8b68-68708f157d51.png)

The path containing Unicode was decoded incorrectly.
![kitty-pwd-issue](https://user-images.githubusercontent.com/57713011/128127081-a80e00c3-b0d5-46ec-868f-ca29d881ff4a.png)

Launch kitty in macOS Terminal, Unicode path decoding is normal at this time.
You must exit all instances first, otherwise there are still decoding issues.
```open -a "kitty" "/tmp/①②③④⑤⑥⑦⑧⑨"```
![kitty-pwd-correct](https://user-images.githubusercontent.com/57713011/128127206-8a42c6a1-35d5-4a48-828f-4521e8daee0c.png)

**Environment details**
```
kitty 0.22.2 created by Kovid Goyal
Darwin <HOST> 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.5.1 BuildVersion:	20G80
Loaded config files:
  /Users/<USER>/.config/kitty/kitty.conf

Config options different from defaults:
shell /usr/local/bin/fish
```

**Additional context**
No config for fish shell.

Open kitty on the command line in the following environment and the Unicode path is normal.
```
PWD=/tmp/①②③④⑤⑥⑦⑧⑨
__CFBundleIdentifier=com.apple.Terminal
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=440
TERM=xterm-256color
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LC_CTYPE=UTF-8
LANGUAGE=en_US:en
...
```
Launch command in Apple macOS Terminal
```shell
osascript -e 'quit app "kitty.app"'
open -a "kitty" "/tmp/①②③④⑤⑥⑦⑧⑨"
```
result:
```
user@host /p/t/①②③④⑤⑥⑦⑧⑨> pwd
/private/tmp/①②③④⑤⑥⑦⑧⑨
```

Launch kitty in macOS Launchpad GUI, then execute commands in kitty. There is a problem decoding Unicode paths at this point.
```
PWD=/tmp/①②③④⑤⑥⑦⑧⑨
TERM=xterm-kitty
TERMINFO=/Applications/kitty.app/Contents/Resources/kitty/terminfo
COLORTERM=truecolor
COMMAND_MODE=unix2003
__CFBundleIdentifier=net.kovidgoyal.kitty
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
XPC_SERVICE_NAME=application.net.kovidgoyal.kitty.5331012.5331018
XPC_FLAGS=0x0
KITTY_WINDOW_ID=1
WINDOWID=1611
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LANGUAGE=en_US:en
...
```

Launch command in kitty
```shell
open -a "kitty" "/tmp/①②③④⑤⑥⑦⑧⑨"
```

result:
```
user@host /p/t/â â¡â¢â£â¤â¥â¦â§â¨> pwd
/private/tmp/â â¡â¢â£â¤â¥â¦â§â¨

user@host /p/t/â â¡â¢â£â¤â¥â¦â§â¨> env
PWD=/private/tmp/â â¡â¢â£â¤â¥â¦â§â¨
COLORTERM=truecolor
COMMAND_MODE=unix2003
TERMINFO=/Applications/kitty.app/Contents/Resources/kitty/terminfo
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
XPC_SERVICE_NAME=application.net.kovidgoyal.kitty.5331012.5331018
WINDOWID=1741
__CFBundleIdentifier=net.kovidgoyal.kitty
XPC_FLAGS=0x0
LANG=en_US.UTF-8
TERM=xterm-kitty
KITTY_WINDOW_ID=3
PATH=/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LANGUAGE=en_US:en
...

user@host /p/t/â â¡â¢â£â¤â¥â¦â§â¨> cd "/tmp/①②③④⑤⑥⑦⑧⑨/"
user@host /t/①②③④⑤⑥⑦⑧⑨> pwd
/tmp/①②③④⑤⑥⑦⑧⑨
```

Start with a new instance
```shell
kitty --directory "/tmp/①②③④⑤⑥⑦⑧⑨"
```

result:
```
user@host /p/t/①②③④⑤⑥⑦⑧⑨> pwd
/private/tmp/①②③④⑤⑥⑦⑧⑨
```

The paths obtained by the fish shell in macOS Terminal and iTerm2 are normal for both GUI and command line startups.

**Comment by kovidgoyal** [comment]
That has nothing to do with kitty. kitty is correctly setting the path
of the working directory, since if it wasnt, fish would not be in that
directory. As for the display issue in fish, it will be because of a
missing LANG variable. 

https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

Add

env LANG=en_US.UTF-8

to kitty.conf and you will be fine.

**Comment by page-down** [comment]
Thank you very much. This is solved by defining `env` in `kitty.conf`.

The reason why the configuration is invalid in fish is that the working path is resolved before fish loads the configuration file containing the lang config.

I was curious why macOS Terminal and iTerm2 are working properly, after troubleshooting, I found a difference in the default configured environment variables.

macOS Terminal and iTerm2
```
LC_CTYPE=UTF-8
```

Would it be a good idea to also use this as an envvar for kitty's child processes when launching from macOS GUI?

(Only if neither LC_ALL nor LC_CTYPE is defined.)

Launching an app from the macOS GUI will not come with any language and character set-related environment variables, and using the same conventions as Apple's own apps seems like a good way to go.

**Comment by kovidgoyal** [comment]
kitty already does so. See ensure_macos_locale() and coca_get_lang()

**Comment by page-down** [comment]
I found the reason why the `LANG` from `ensure_macos_locale()` is not taking effect.

When the macOS language is set to English and the locale is set to a region other than the UK, US, etc., such as Japan (`en_JP`), the locale test will fail and `LANG` will be `None`.

https://github.com/kovidgoyal/kitty/blob/v0.22.2/kitty/cocoa_window.m#L581
```objc
static PyObject*
cocoa_get_lang(PyObject UNUSED *self) {
    @autoreleasepool {
    // ...

    // locale = "en_JP"
    const char* locale_utf8 = [locale UTF8String];
    locale_t test_locale = newlocale(LC_ALL_MASK, locale_utf8, NULL);
    // test failed, return: None
    if (!test_locale) { Py_RETURN_NONE; }

    // ...
    }
}
```

I would suggest configuring the default character set to `UTF-8` regardless of language and region.


---

Anyway, configuring the language and character set in the shell doesn't work, it's a fish shell bug, nothing to do with kitty.

macOS Terminal and iTerm2 just happen to provide the default `LC_CTYPE=UTF-8` environment variable, so it doesn't seem to be a issue. (Those Terminals just cover up the root of the issue.)

Thank you very much.

**Comment by kovidgoyal** [comment]
On Wed, Aug 04, 2021 at 03:06:38AM -0700, page-down wrote:
> I found the reason why the `LANG` from `ensure_macos_locale()` is not taking effect.
> 
> When the macOS language is set to English and the locale is set to a region other than the UK, US, etc., such as Japan (`en_JP`), the locale test will fail and `LANG` will be `None`.

Yes, don't do that, or if you want to do it, define your own LANG via
kitty.conf.

> 
> https://github.com/kovidgoyal/kitty/blob/v0.22.2/kitty/cocoa_window.m#L581
> ```objc
> static PyObject*
> cocoa_get_lang(PyObject UNUSED *self) {
>     @autoreleasepool {
>     // ...
> 
>     // locale = "en_JP"
>     const char* locale_utf8 = [locale UTF8String];
>     locale_t test_locale = newlocale(LC_ALL_MASK, locale_utf8, NULL);
>     // test failed, return: None
>     if (!test_locale) { Py_RETURN_NONE; }
> 
>     // ...
>     }
> }
> ```
> 
> I would suggest configuring the default character set to `UTF-8` regardless of language and region.

UTF-8 is not a valid value for LC_CTYPE. It just happens to work on
macOS only. If you ssh into a linux server with LC_CTYPE set to UTF-8
and the ssh daemon is configured to forward LC_* variables (which many
Linux distros do) you will get errors.
See the POSIX specification for LC_ variables in https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/V1_chap08.html

> 
> 
> ---
> 
> Anyway, configuring the language and character set in the shell doesn't work, it's a fish shell bug, nothing to do with kitty.

It has to be set before running the shell, so the place to configure it
is kitty.conf

> 
> macOS Terminal and iTerm2 just happen to provide the default `LC_CTYPE=UTF-8` environment variable, so it doesn't seem to be a issue. (Those Terminals just cover up the root of the issue.)

Yes, I know those terminals fallback to setting LC_CTYPE to utf-8 when
unable to derive a valid LANG value, however, I am not keen to do that
in kitty, because of the SSH problem I mentioned above.

However, thinking about it, it may be worth doing. People will get
errors, but at least those errors will not be reported to me, since the
other macOS terminals also behave like that :)

**Comment by kovidgoyal** [comment]
Oh and before I forget more reasons to not set LC_CTYPE=utf-8  #1233
