### ISSUE TITLE
Image preview not working with ranger

### ISSUE THREAD

**Issue by pkail** [kovidgoyal/kitty#3905]
**Describe the bug**
There is no preview window.

**To Reproduce**
Highlight .png file in Ranger.

ranger-stable 1.8.1
kitty 0.22.2
Installed pillow 8.3.1
ImageMagick 7.1.0-4 Q16 x86_64

**Environment details**
In rc.config:
set preview_images true
set preview_images_method kitty

Tried using --config NONE, but got the same result.
kitty +kitten icat image.jpeg works.

**Comment by kovidgoyal** [comment]
Works fine for me. You need to report it to ranger.

**Comment by pkail** [comment]
It works for some people, but it would be great if it worked for everyone.

**Comment by kovidgoyal** [comment]
And why is that my problem? The kitty imag protocol is fully documented
and implemented correctly. If ranger is not working with it, it needs to be
reported there. You have likely misconfigured it, I am not going to help
you debug ranger.

**Comment by pkail** [comment]
It's such a pity that you are so insecure about feedback.  You are a brilliant programmer, and you have a fantastic project.  But your hostile attitude is even mentioned in YouTube videos as a reason not to use kitty.

**Comment by kovidgoyal** [comment]
I see so now unless I waste my time helping you debug your incorrect use of some third party program I know nothing about, I am hostile. What an entitled moron.
