### ISSUE TITLE
clear_all_shortcuts analogue for mouse_maps

### ISSUE THREAD

**Issue by bdeshi** [kovidgoyal/kitty#3907]
**Is your feature request related to a problem? Please describe.**
This is new feature request; not related to any problem.

**Describe the solution you'd like**
I wanted to have only the `mouse_map`s I have defined and nothing extra. But to achieve this, I needed to `no-op` all `mouse_map`s that are in the factory defaults. So I'm requesting a config option analogue to `clear_all_shortcuts` that clears all `mouse_map`s set by default.

**Describe alternatives you've considered**
One workaround is to duplicate all default `mouse_map` definitions in my kitty.conf with `no-op` action. But this workaround requires me actively monitor if new `mouse_map`s are added to factory defaults in the future.

**Additional context**
n/a

**Comment by kovidgoyal** [comment]
Not something I am interested in implementing, but PRs are welcome.
