### ISSUE TITLE
Input chinese in macos，but no work in linux

### ISSUE THREAD

**Issue by feedoom** [kovidgoyal/kitty#3908]
my system is manjaro.
I can input chiese in macos, but no work in manjaro.

**Comment by kovidgoyal** [comment]
You need to setup ibus and export the GLFX_IM_MODULE=ibus variable
system wide.

**Comment by newptcai** [comment]
I have set this in my `.profile` by

```
# For kitty
export GLFX_IM_MODULE=ibus
```

I still cannot type Chinese in kitty.
