### ISSUE TITLE
Set/reset key modifier options behavior

### ISSUE THREAD

**Issue by scandum** [kovidgoyal/kitty#3912]
https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys

When this mode is enabled through \e[>4;1m kitty sends special escape sequences for enter, backspace, and arrow keys. Xterm does not, and kitty's behavior seems contrary to xterm's specification.

ctrl-a, ctrl-b, etc, seem affected as well, where as xterm is not.

**Comment by kovidgoyal** [comment]
kitty sends the same keys for enter and the arrow keys under that mode
as under legacy modes (it is the first level of progressive enhancement
in the kitty keyboard protocol).

And xterm doesnt have a spec, kitty does, which it follows:
https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by scandum** [comment]
The full sequence being used is `\e[?1004h\e=\e[>4;1m`, not sure if that makes a difference.

**Comment by kovidgoyal** [comment]
Running:

kitty --config NONE sh -c 'printf "\e[?1004h\e=\e[>4;1m"; showkey -a'

and pressing enter and up and down, gives:

```
Press any keys - Ctrl-D will terminate this program

^M 	13 0015 0x0d
^[[A 	27 0033 0x1b
 	91 0133 0x5b
 	65 0101 0x41
^[[B 	27 0033 0x1b
 	91 0133 0x5b
 	66 0102 0x42
```

as expected.
