### ISSUE TITLE
background color causes shell-less terminal

### ISSUE THREAD

**Issue by McAllaster** [kovidgoyal/kitty#3914]
**Describe the bug**
Setting the `background` color option to `#FAFAFA` (or other colors) inconsistently causes a new terminal window to spawn without a prompt. Typing will produce characters in the window, but there is no shell/prompt, and commands are unable to be executed.

Setting the background color to `#FFFFFF`, or using the default value, seems to prevent this unexpected behavior.

**To Reproduce**
1. Create a kitty configuration file containing `background #FAFAFA`
2. Launch `kitty`
3. See a terminal without a shell/prompt (possibly)

**Environment details**
```
kitty 0.21.1 created by Kovid Goyal
Linux <HOSTNAME> 5.13.8_1 #1 SMP Wed Aug 4 15:28:27 UTC 2021 x86_64
Void \r (\n) (\l)
Running under:Wayland
Loaded config files:
  /home/<USERNAME>/.config/kitty/kitty.conf

Config options different from defaults:
background Color(red=250, green=250, blue=250)
```

I am running [Void Linux](https://voidlinux.org/) using [`musl`](https://musl.libc.org/), with [`sway`](https://github.com/swaywm/sway) as my Wayland compositor / desktop environment.

**Comment by kovidgoyal** [comment]
Does not reproduce for me with 
kitty --config NONE -o "background=#FAFAFA"

And background can have no bearing on whether a shell runs or not.
Presumably you shell prompt is using a whitish color for thext that is
invisible with background #FAFAFA

**Comment by McAllaster** [comment]
Running that command, even with different shells, produces the same issue.

The prompt is not simply invisible due to the color scheme. For example, a command launching a GUI application like `firefox` will not be invoked when typed in a bugged terminal instance -- while it _does_ work in one of the few that don't bug out.

I'm guessing that this issue is at a lower level, most likely due to `musl`, or some interaction with it and the system (I have been getting some other weird terminal/application behaviors after opening this issue).

That being said, you can leave this closed if you would like. I'll re-attempt on a `glibc` system installation.

**Comment by kovidgoyal** [comment]
I'm afraid I dont see anything in kitty code that could possibly cause a
particular value for background color that could prevent a shell from
running. But if you really believe that's what's happening, build kitty
with make asan and run it with the sanitizers. That will catch most
memory/ub issues.
