### ISSUE TITLE
Mac, Install kitty via brew => missing "PlugIns" Directory

### ISSUE THREAD

**Issue by ChrisGitIt** [kovidgoyal/kitty#3915]
**Describe the bug**
Hi all, I just installed kitty via brew (brew install --cask kitty).
This places a "Kitty.app" in my Applications folder. But when I want to start kitty via "Kitty.app", its not starting.

In the syslog, there is the following error:
`Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "Die Datei „PlugIns“ konnte nicht geöffnet werden, da sie nicht existiert." UserInfo={NSURL=PlugIns/ -- file:///Applications/kitty.app/Contents/, NSFilePath=/Applications/kitty.app/Contents/PlugIns, NSUnderlyingError=0x7f823260c3f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`
A normal shell LS shows that the "PlugIns" Directory is actually not existing in /Applications/kitty.app/Contents/

I tried adding "PlugIns" Directory manually, but no luck (different errors, but I think there are other Mac Protections that causes those errors).

**To Reproduce**
1. brew install --cask kitty
2. Try start "Kitty.app" via Finder
3. See error in syslog.

**Environment details**
```
kitty 0.22.2 created by Kovid Goyal
Darwin ******* 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H1323
Loaded config files:
  /Users/*******/.config/kitty/kitty.conf

Config options different from defaults:
font_family   Fira Code
font_features:
{'FiraCode-Retina': ('+zero', '+onum', '+calt')}
font_size     12.0
```

**Comment by Luflosi** [comment]
@kovidgoyal Let me translate "Die Datei „PlugIns“ konnte nicht geöffnet werden, da sie nicht existiert." for you: "The File „PlugIns“ could not be opened since it does not exist.".

**Comment by Luflosi** [comment]
@ChrisGitIt See if https://github.com/kovidgoyal/kitty/issues/3534#issuecomment-828643051 solves your problem.

**Comment by kovidgoyal** [comment]
kitty doesn't use a PlugIns directory, there isnt one in a normal kitty
install. This will likely be some interaction between homebrew and macOS
gatekeeper or similar. I suggest you try @Luflosi's suggestion and if
that doesnt work use the official kitty binaries rather than the
homebrew one.
