### ISSUE TITLE
[Bug] : `zsh-autosuggestion` color not detect with tmux

### ISSUE THREAD

**Issue by ayoubelmhamdi** [kovidgoyal/kitty#3916]
when i use kitty only i get color of autosuggestion 
![kitty-1](https://user-images.githubusercontent.com/34358145/128751701-5dfbcf8c-244c-457c-bc96-d8f310638a9a.png)
but when i use tmux i can not get color of autosuggestion
![kitty-2](https://user-images.githubusercontent.com/34358145/128751771-7d93ddd9-2c8e-40ba-ac58-110e530c9fd1.png)

**Comment by trygveaa** [comment]
You need `set -g default-terminal tmux-256color` in your `.tmux.conf`.

**Comment by ayoubelmhamdi** [comment]
when i search in `terminfo`, i don't have `tmux-256color`
```sh
$ ls /usr/share/terminfo/x | grep "tmux\|kitty"

xterm-kitty
```
but it fix with `set -g default-terminal xterm-kitty` in my `.tmux.conf` , instant of `tmux-256color`

**Comment by trygveaa** [comment]
> when i search in terminfo, i don't have tmux-256color

It shouldn't appear there, it's internal to tmux.

> but it fix with set -g default-terminal xterm-kitty in my .tmux.conf , instant of tmux-256color

That's definitely the wrong solution, and will probably cause something else to break. `default-terminal` in the tmux config is the term that will be used inside tmux, and should never be set to something not starting with `screen` or `tmux`. From the tmux manual:

> default-terminal terminal
>             Set the default terminal for new windows created in this session - the default value of the TERM environment variable. For tmux to work correctly, this must be set to ‘screen’, ‘tmux’ or a derivative of them.

If you don't believe me that setting it to `tmux-256color` is the correct thing to do, see the official documentation for tmux here: https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal

**Comment by ayoubelmhamdi** [comment]
i have `screen-256color` in `/usr/share/terminfo/s` and it work too, tmux not located in `terminfo dirs`
> That's definitely the wrong solution, and will probably cause something else to break. `default-terminal` in the tmux config is the term that will be used inside tmux, and should never be set to something not starting with `screen` or `tmux`. From the tmux manual:
