### ISSUE TITLE
Custom Ligatures

### ISSUE THREAD

**Issue by dwdwdan** [kovidgoyal/kitty#3917]
**Is your feature request related to a problem? Please describe.**
I write a decent amount of latex in the terminal, and it would be easier to read if something like `\geq` was replaced by the ligature shown for `>=`

**Describe the solution you'd like**
It would be nice to have a way to define custom text to render as a ligature. This would probably also be useful for languages that have weird syntax.

**Comment by kovidgoyal** [comment]
ligature definitions come from fonts. You would need to convince someone
to produce a font for your use case, in which case it will work across
all applications, not just kitty.

**Comment by dwdwdan** [comment]
Oh okay, I didn't know that. Thanks
