### ISSUE TITLE
Feature Request: visual_bell_color (instead of inverted colors)

### ISSUE THREAD

**Issue by cookiengineer** [kovidgoyal/kitty#3919]
Kitty is amazing! I'm using it for years now and I'm amazed by its flexibility and configuration options.

Lately though, I've tried to figure out whether it's possible to configure the visual terminal bell differently. So, instead of using inverted colors (which makes the screen totally white in my case), I wanted to define a not-so-invasive color for the background and foreground that's not flashing so brightly in my face when making mistakes.

Is that possible? I've seen no `man` entry that goes more into detail when looking for `visual_bell_...`, so I'm assuming this is a feature request?

**Describe the solution you'd like**

```
visual_bell_foreground = #ffffff
visual_bell_background = #222222
```

**Comment by cookiengineer** [comment]
I don't understand why the issues get closed when the PR from over a year ago can't be merged due to necessary discussion of how to implement it?

**Comment by kovidgoyal** [comment]
Because I like to track things in one place. The PR is the place for this issue.
