### ISSUE TITLE
Quake mode

### ISSUE THREAD

**Issue by Jomik** [kovidgoyal/kitty#392]
Would be amazing if you could implement a Quake Mode that would run on Wayland.
It is sort of related to #391, as we would need to completely hide the window when the drop down is hidden, but pull it back and resume where we left off when you show it again.

**Comment by kovidgoyal** [comment]
This is not the purview of individual applications. It is the job of the window manager to show and hide windows on key presses. A bit of googling will show you scripts for various window managers to achieve this, and of course if you use a tiling window manager, it is available out of the box.

**Comment by Jomik** [comment]
I agree, I suppose :+1: May require #391 to get the effect of being able to resume a completely hidden session then.
I haven't really figured out how to get a quakemode dropdown on Gnome :cry: Used to use Tilix, but they disabled the behavior for Wayland.

**Comment by kovidgoyal** [comment]
You dont need #391 for that. A simple minimize will do the trick. I use a similar technique with a tiling window manager all day long. I can call up various kitty windows with special keypresses instantly, I simply have my window manager distribute kitty windows to different "groups" based on their window class/role.

**Comment by noctuid** [comment]
@Jomik Fwiw, [tdrop](https://github.com/noctuid/tdrop) supports kitty and Gnome.

**Comment by santhoshtr** [comment]
This is what I do in my KDE:
Install tdrop. It involves cloning out the [repo](https://github.com/noctuid/tdrop), and running `sudo make install`.

Then in KDE, Navigate: 
Settings -> Keyboard -> Shortcuts. Add New -> Command or Script
Then 
```
KITTY_DISABLE_WAYLAND=1 tdrop kitty
```

Assign a shortcut too. I use F12. Save. Done.

You need to use KITTY_DISABLE_WAYLAND=1 since tdrop does not work with wayland. This flag forces kitty ot use XWayland.

**Comment by kovidgoyal** [comment]
Using X11 just to have tdrop work is pretty sad, so I added native
support for this via the panel kitten on wayland:
https://github.com/kovidgoyal/kitty/commit/85d58de035517c5c4b69546691167cfcd69e803e
