### ISSUE TITLE
Scroll multiple lines for: scroll_line_up & scroll_line_down

### ISSUE THREAD

**Issue by freeo** [kovidgoyal/kitty#3920]
**Is your feature request related to a problem? Please describe.**
I try to work mouse free, but when in need of scrolling up (not the scrollback buffer!), I often find myself reaching for the mousewheel (or open scrollback pager, which often introduces too many keypresses compared to using the mouse).

**Describe the solution you'd like**
Add this option for kitty.conf:
```
scroll_lines 3
```
Pressing the shortcuts for `scroll_line_up` & `scroll_line_down` will scroll 3 lines instead of just 1.

**Describe alternatives you've considered**
```
scroll_speed 3
```

**Additional context**
I'm very much used to this behaviour due to these vim bindings:
```
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
```
I guess many vimmers might feel alike.

**Thank you *so much* for kitty!**
![kitty](https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/giphy.gif)

**Comment by trygveaa** [comment]
You can use the combine mapping in your config to accomplish this. I have these mappings:

```
map kitty_mod+k     combine : scroll_line_up : scroll_line_up : scroll_line_up : scroll_line_up : scroll_line_up
map kitty_mod+j     combine : scroll_line_down : scroll_line_down : scroll_line_down : scroll_line_down : scroll_line_down
```

**Comment by freeo** [comment]
@trygveaa interesting! I didn't know about `combine`, yet.

Still interested, if this should be solved with a native kitty.conf option though.
