### ISSUE TITLE
SSH error only on specific apps (nano) 

### ISSUE THREAD

**Issue by alexandrestein** [kovidgoyal/kitty#3921]
**Describe the bug**
I'm not sure it's a bug; sorry :worried: 
On remote servers, the `sudo` command associated with `nano` fails.
`nano` fails also from root.

**To Reproduce**
1. work with Kitty
2. connect to remote system
3. run "some" command with sudo or from root

**Screenshots**
![Screenshot from 2021-08-11 13-15-51](https://user-images.githubusercontent.com/5431025/129019909-abd5a593-863c-4d2c-980d-de6057125a98.png)

**Environment details**
```
kitty 0.22.2 (13e59df1f8) created by Kovid Goyal
Linux pinguRiderDDN 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
Debian GNU/Linux 10 \n \l
Running under:Wayland
Loaded config files:
  /home/alexandre/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       socket-only
background_opacity         0.9
dynamic_background_opacity True
font_family                Fira Code
font_size                  10.0
listen_on                  unix:/tmp/kittys
Added shortcuts:
	f1 KeyAction('launch', ('--allow-remote-control', 'kitty', '+kitten', 'broadcast'))
	shift+ctrl+" KeyAction('third_window')
	shift+ctrl+$ KeyAction('move_window_to_top')
	shift+ctrl+& KeyAction('first_window')
	shift+ctrl+' KeyAction('fourth_window')
	shift+ctrl+( KeyAction('fifth_window')
	shift+ctrl+) KeyAction('change_font_size', (True, '-', 2.0))
	shift+ctrl+* KeyAction('next_window')
	shift+ctrl+; KeyAction('move_tab_forward')
	shift+ctrl+_ KeyAction('eighth_window')
	shift+ctrl+à KeyAction('tenth_window')
	shift+ctrl+ç KeyAction('ninth_window')
	shift+ctrl+è KeyAction('seventh_window')
	shift+ctrl+é KeyAction('second_window')
	shift+ctrl+ù KeyAction('previous_window')
Changed shortcuts:
	shift+ctrl+- KeyAction('sixth_window')
Colors:
	color0                     #fff0f5   
	color1                     #ed2f2f   
	color2                     #8fce10   
	color3                     #e6db74   
	color4                     #0d56ca   
	color5                     #f92672   
	color6                     #56b6c2   
```

**Additional context**
Error reproduced with `kitty --config NONE`

My understanding is that the best way to fix those kind of issues is to add `xterm-kitty` to the `xterm` system and to add some patch to openssh-client.
How can we help/push in this direction. If every affected users has a "simple" way to show his interest into your great terminal application, maybe we could have it solved quickly. :crossed_fingers: 

Sorry if I missed something, I never really played with special feature from terminal before.
Thanks for you great work.

**Comment by kovidgoyal** [comment]
See the FAQ

https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo
