### ISSUE TITLE
not allowing me to select fully

### ISSUE THREAD

**Issue by xenoterracide** [kovidgoyal/kitty#3924]
**Is your feature request related to a problem? Please describe.**

kitty keeps unselecting sporadically. I debugged with libinput I don't see anything that would be causing this, or any other misbehaving applications.

**Describe the solution you'd like**

... fix it!

**Describe alternatives you've considered**

use a different TE which is what I'm going to do for now

**Additional context**
```
kitty 0.22.2 created by Kovid Goyal
```
```
font_family FiraCode-Retina
font_features FiraCode-Retina +ss07
scrollback_lines 10000
copy_on_select yes
strip_trailing_spaces smart
enable_audio_bell never
bell_on_tab no
tab_activity_symbol *
tab_title_template "{title} {index}"
linux_display_server x11
wayland_titlebar_color system
enabled_layouts vertical
```
actually, my display server is Wayland, but I was fixing/working around some other issue, and I have xwayland.

[webm screencast of issue in zip](https://github.com/kovidgoyal/kitty/files/6969890/kitty.zip)

oh, and if you supported vim mode, this *might* not be an issue as I would just visual yank ;)

**Comment by xenoterracide** [comment]
hmm... I'm not certain now, investigating other possibilities further.

**Comment by kovidgoyal** [comment]
On Wed, Aug 11, 2021 at 09:19:15AM -0700, Caleb Cushing wrote:
> **Is your feature request related to a problem? Please describe.**
> 
> kitty keeps unselecting sporadically. I debugged with libinput I don't see anything that would be causing this, or any other misbehaving applications.

Unselection happens if and only if
something on the screen changes, typically on one of the lines
the selection spans. If you have some other scenario where unselection
happens, a reproducer is needed.

> 
> **Describe the solution you'd like**
> 
> ... fix it!

Let me get right on that, since you asked so nicely.

> 
> **Describe alternatives you've considered**
> 
> use a different TE which is what I'm going to do for now

Enjoy.

**Comment by xenoterracide** [comment]
did you watch the video? I'm able to reproduce this fairly consistently, like every time I select by dragging. I just sent libinput logs to their devs asking them to see if anything weird was going on.

**Comment by kovidgoyal** [comment]
A video is not a reproducer. Run kitty with --dump-commands, see what
commands the terminal application that you are running 
is sending when an unselect happens. As I said the only way for an
unselect to happen is for something to change on screen
