### ISSUE TITLE
Background color not covering entire background image

### ISSUE THREAD

**Issue by codedbyjordan** [kovidgoyal/kitty#3933]
**Describe the bug**
The background color seems to have extra padding that is preventing it from covering the entire background image

**To Reproduce**
1. Set background image
2. Set background color
3. Set background image layout to scaled, and set background tint and background opacity

**Screenshots**
![image](https://user-images.githubusercontent.com/62375480/129490595-ea1ad081-517a-4d04-8f22-358eebe6f6cf.png)

**Environment details**
```
kitty 0.22.2 created by Kovid Goyal
Linux jordan-manjaro 5.10.56-1-MANJARO #1 SMP PREEMPT Thu Aug 5 10:51:27 UTC 2021 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.0
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under:Wayland
Loaded config files:
  /home/jords/.config/kitty/kitty.conf

Config options different from defaults:
background_image        /usr/share/img/treefrog.png
background_image_layout scaled
background_tint         0.7
Added shortcuts:
	f1 KeyAction('launch')
```

**Comment by kovidgoyal** [comment]
That will happen when the OS window size is not an exact multiple of
cell size.

**Comment by HARSH-SHETH** [comment]
> That will happen when the OS window size is not an exact multiple of cell size.
Hi, what setting should I change to avoid this ?

**Comment by CastixGitHub** [comment]
Hello, can this be reopened?
it is `window_padding_width` because setting an higher value will accentuate it.
and playing with `placement_strategy` moves the padding around.
It is clear that the padding is required. but it should also inherit the opacity tint

**Comment by kovidgoyal** [comment]
Not something I care about, patches are welcome.

**Comment by Asday** [comment]
Agree that this is really budget, but the workaround is easy enough - tint the image yourself and remove the tint from the options.  In Krita, open your image, make a new layer above it, fill it with your Kitty background colour, then set the opacity to whatever your tint value was (multiplied by a hundred), then save the image out.  It's worth keeping the Krita file around too for changing the background tint colour or opacity.

Also really easy to do in Photoshop, blender, and I imagine the particularly motivated could do it in GIMP.

**Comment by patrykk21** [comment]
I'd like to tackle this problem, @kovidgoyal .

Could you suggest me where to start looking? I've never worked on this project. Seems fairly big

**Comment by CastixGitHub** [comment]
@patrykk21
each cell (character) have their own background tint, so the area outside (padding) cannot be colored out that way.
You can instead use Pillow to manipulate the background image as suggested by Asday

**Comment by patrykk21** [comment]
> @patrykk21 each cell (character) have their own background tint, so the area outside (padding) cannot be colored out that way. You can instead use Pillow to manipulate the background image as suggested by Asday

Not really... by applying a manual backdrop you incur into issues when resizing/zooming and stuff.
I'm not into losing pixel quality ~ :(

**Comment by Asday** [comment]
> cannot be colored out *that way*

Sure but Patrykk's intent is to change the source code such that the padding _can_ be tinted, rather than to just set his own background.  It doesn't matter if the way the code currently does stuff is inadequate because it's that inadequacy he aims to fix.

**Comment by patrykk21** [comment]
You're awesome. I'm crying of joy. I'll finally be able to have my anime girls holding programming books in the background like a real nerd should.

Just waiting for the homebrew build to finish and I'm testing it!

**Comment by kovidgoyal** [comment]
Enjoy. I haven't tested it very much and that too only in Linux, but
hopefully it works.

**Comment by Asday** [comment]
Linux is all that matters anyway :)

I'll poke in thread if there's an issue but I don't imagine one of course.

**Comment by patrykk21** [comment]
![HURRAY](https://user-images.githubusercontent.com/39259934/193692984-a59d3098-3abf-4c0f-a3ce-bb3848657719.png)

**Comment by patrykk21** [comment]
Thank you!!!
