### ISSUE TITLE
Start kitty with predefined window layout

### ISSUE THREAD

**Issue by hexploder** [kovidgoyal/kitty#3934]
Hi everyone, 

I don't know if what I'm asking could be a new feature or I just don't know how to do it.
But here is my workflow.
I normally just open a terminal to do simple stuff, I open the Tall layout (I used enabled_layout to define Tall as default). then I open 2 windows, and resize the left to be wider, and the top right to be taller, then I open bpytop in the top right, cava in the lower right and the left I do what ever I need, this is because I have two monitors and I use kitty basically fullscreen in one of them.
Is there a way to start kitty with those 3 window already resized and if its not too much to have the windows in the right already with bpytop and cava open?, I was thinking that maybe have a second kitty.conf with an include of the main conf and the extra config to make that happen so the I can make a shortcut (with a custom shortcut in kde for example) like mod+T to open kitty with the --config option, in this way I could actually make a bunch of different configs with different needs, maybe a 3 vertical layout and on each I do a ssh to a specific server, this can be very usefull for my work for example.

Regards.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/overview/#startup-sessions
