### ISSUE TITLE
Backspace key is broken over ssh

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#3935]
**Describe the bug**
The Backspace key moves the cursor _forward_ within an ssh session.  (I can not use the key to delete characters.)

**To Reproduce**
1. `ssh username@localhost`
2. `ls -l` (Do not hit ENTER.)
3. Backspace key a few times.

**Observed Behavior**
The cursor moves _forward_ with each key press instead of erasing _backwards_.

**Environment details**
```
kitty 0.23.0 (827b6598b2) created by Kovid Goyal
Linux byteevo-scm 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Running under:X11

Config options different from defaults:
```

**Additional context**
- This bug also reproduces with kitty version `0.22.2`.
- For comparison, the Backspace key works fine over ssh within GNOME Terminal.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo

**Comment by rosefloase** [comment]
hi it's been ~4 years and this ssh bug still exists
luckily there is still a fix for this bug! [you gotta use a kitten now](https://sw.kovidgoyal.net/kitty/kittens/ssh/)
