### ISSUE TITLE
Support for blinking text

### ISSUE THREAD

**Issue by bczsalba** [kovidgoyal/kitty#3940]
**Is your feature request related to a problem? Please describe.**
The blink ANSI sequences (`\x1b[5m` & `\x1b[6m`) don't seem to be doing performing their function (set blinking mode).

**Describe the solution you'd like**
Implementation of these sequences & modes, or a reason against it (that's okay too, I'm just curious).

**Describe alternatives you've considered?**
I tried both `blink` modes, neither of which work. `gnome-terminal` supports them, `Terminal.app` supports `\x1b[5m`, while `iTerm` supports neither.

**Comment by kovidgoyal** [comment]
I'm afraid not, I am not a fan of blinking text and implementing it is much harder than other types of formatting, making it particularly not worth it, as the implementation would have unusually high performance costs, even when unused.

**Comment by bczsalba** [comment]
That's unfortunate, but understandable. If someone were to make a patch that exposed a config option to allow blinking, would you accept it? I probably won't, but someone at some point might.

**Comment by kovidgoyal** [comment]
I would have to see what the runtime overhead and code complication
implications of the patch would be to decide.

**Comment by zakkor** [comment]
Just chiming in to say that there are other functional uses for blinking text, not just for decorative purposes.
For example TUI text editors that want to offer multiple cursors need blinking in order to show the cursors, because otherwise you can only have 1 "real" cursor represented using the terminal cursor.

**Comment by kovidgoyal** [comment]
On Wed, Oct 12, 2022 at 11:49:49AM -0700, zakkor wrote:
> Just chiming in to say that there are other functional uses for blinking text, not just for decorative purposes.
> For example TUI text editors that want to offer multiple cursors need blinking in order to show the cursors, because otherwise you can only have 1 "real" cursor represented using the terminal cursor.

Not at all, they can blink the cursor themselves using escape codes, and
in the case of kitty they can use the graphics protocol instead. This
will allow them to actually render nice blinking cursors of different
shapes.

**Comment by keithbowes** [comment]
> I'm afraid not, I am not a fan of blinking text

Indeed.  The only real purpose of supporting it would be to allow users to override it with something less annoying (like bold or italic text in a different color), so that you can still see that the text is supposed to stand out somehow but doesn't have an annoying blinking effect.
