### ISSUE TITLE
Ability to mirror windows

### ISSUE THREAD

**Issue by cwqt** [kovidgoyal/kitty#3941]
Would be nice if there was a `layout_action` for mirroring the current windows across the x / y plane

e.g. given some key combination would mirror the following windows from top to bottom

<img width="1152" alt="Screenshot 2021-08-16 at 23 33 59" src="https://user-images.githubusercontent.com/61694629/129637489-c0f4e9ba-a284-497d-9096-3f9f8190c9e1.png">
<img width="1152" alt="Screenshot 2021-08-16 at 23 34 27" src="https://user-images.githubusercontent.com/61694629/129637491-dc0be8f7-6efd-414c-a47b-632c85bae873.png">

**Comment by kovidgoyal** [comment]
umm, why?

**Comment by kovidgoyal** [comment]
no followup
