### ISSUE TITLE
macOS: Launch Kitty with single child process (e.g. `vim`), and exit Kitty when child process exits

### ISSUE THREAD

**Issue by jrop** [kovidgoyal/kitty#3944]
**Is your feature request related to a problem? Please describe.**

I would like use use Kitty as a GUI wrapper for Vim.  Specifically, I want to use Vim with Joplin, and Joplin allows setting an "external editor".  For example, I can set this use launch Alacritty with NeoVim as its child process:

![image](https://user-images.githubusercontent.com/1404053/129756604-80105905-ec00-49ad-9f41-04ad0090ca7a.png)

From Alacritty, I can edit the document using Vim, and then `:wq`, and the Alacritty window will close (and the process exits).  However, when I try to use Kitty, after `:wq`, Vim exits, and Kitty will remain running (as windowed apps usually do on macOS).

**Describe the solution you'd like**

I would like a way to tell Kitty to "exit the entire app after your child-process exits", specifically on macOS.  It does what I would expect on Linux.

**Describe alternatives you've considered**

1. An additional `Command+Q` to exit Kitty after Vim exits
2. Use another terminal emulator instead :(
3. `--single-instance` / `--wait-for-single-instance-window-close` - on macOS these exhibit the same issue: the entire app remains "running" until it is quit

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_quit_when_last_window_closed.

**Comment by jrop** [comment]
@Luflosi Boom!  That was easy!  Thanks

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_quit_when_last_window_closed
