### ISSUE TITLE
Is it possible to handle custom escape codes?

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#3945]
**Is your feature request related to a problem? Please describe.**
For unofficial private escape codes, can they be handled by kitten?

One usage scenario is to transfer binary data via escape code, but customize the way the data is handled.

Currently clipboard kitten writes data to the clipboard, but there are times when you don't want the clipboard to be modified and instead write the data directly to a file.

The remote file kitten relies on the ssh service.

iTerm2 can transfer files using the following commands. A download confirmation box pops up and the transfer progress is displayed in the OS menu.

```shell
#!/bin/sh
printf '\e]1337;File=name=%s;size=%d:' $(printf "$1"|base64 -w0) $(stat -c%s "$1")
base64 -w0 <"$1"
printf '\a'
```

There are also escape code for file upload request initiation, receiving and writing files at the remote end.

In addition, there are other similar custom usage scenarios for non-file transfers.

For example, a trusted remote command line program can dynamically request private encrypted data from the Terminal side, especially when it is not convenient to establish other direct communication channels.

**Describe the solution you'd like**
Provides the ability to develop and register private escape code handlers.

**Describe alternatives you've considered**
Provides the ability for remote file kitten to send and receive files via escape code, and does not store all data in memory, but streams it directly to the file. (This only addresses the file transfer scenario.)

**Additional context**
Referring to the way clipboard kitten is implemented, there are currently two parts, and kitten is only the half that the user calls from the command line.

In addition, kitten is mainly used to provide a command line interface, initiated by the user, and cannot be registered as an event handler. (as by design)

I want to address these customization needs in kitty and not rely on iTerm2's user-defined actions.

Thank you very much.

---
Question: For private non-standard escape code, should it be defined under ESC _ APC? Which scope of code should be used without causing conflicts for future enhancements?

**Comment by kovidgoyal** [comment]
Your use case appears to be simply file transfer over the tty device. I prefer to solve that using a dedicated escape code, that is well designed, specced and integrated with the terminal. I dont want to end up with a situation like urxvt's plugins that implemented poorly thought out custom escape codes. As such, I am going to refuse this request. I will however eventually design a protocol extension for file transfer, at which time you are welcome to contribute to the design to meet your needs. Look for an RFC for it in the kitty issue tracker.

**Comment by tmccombs** [comment]
Another use case for this is implementing a kitten that replicates iterm2's tmux integration. Basically, detecting a `\033P1000p` DSC sequence that's generated by running `tmux -CC`, and then translating the tmux control protocol to kitty commands. 

The use case I'm particularly interested in for this is when I ssh to a host and then realize I need multipe shells on that host, and would like to muliplex the connection and/or run a command persistently.

**Comment by kovidgoyal** [comment]
file transfer over tty is implemented in the file transfer kitten (though not fully tested and debugged). As for creating multiple shells on a host the ssh kitten takes care of that by simply mapping a key to new_window_with_cwd or launch --cwd=current

As such there are no outstanding use cases for this
