### ISSUE TITLE
macOS: Way to define startup session?

### ISSUE THREAD

**Issue by stormsilver** [kovidgoyal/kitty#395]
Thanks for making kitty! I've been playing with it for the past week and it's quite nifty!

I'd like to start using it as my primary terminal but I really need it to start with a defined layout and so on. Startup sessions are perfect for this, except that you have to specify the file via the `--session` switch. On macOS, this would require me to open Terminal.app, enter `/path/to/kitty.app/Contents/MacOS/kitty --session ...`, and then quit Terminal.app, which is somewhat less than ideal :)

Apologies if this is already solved - I couldn't find anything in the readme, config file, or source code.

The best way I can think of to handle this is to add a config called `default_startup_session` which defines a path to a session file. Kitty would then read this on every invocation.

Even as I type that, I can see cases where you _wouldn't_ want to read the default session file every time - perhaps it would necessitate a `--no-default-session` switch or it could be inferred based on other switches. On macOS the expected behavior would probably be "If I hold the option key while opening kitty.app, it doesn't read the default session file"

**Comment by kovidgoyal** [comment]
Isn't the usual solution to the lack of ability to use command arguments in macOS to create a wrapper script and run that instead? A bit of googling should show you how to wrap a script into a wrapper .app you can use to launch it from the GUI.

**Comment by kovidgoyal** [comment]
That said, I dont mind adding a startup_session config variable to kitty.conf

**Comment by legallyrobert** [comment]
Hello, sorry if I'm clueless but how do I make a session file to use? The docs point towards it and the sample config hints at it, but nothing says what extension to use. My apologies if this is obvious.

**Comment by kovidgoyal** [comment]
There is no extension -- use whatever you like or use none at all, kitty does not care.

**Comment by danielsellergren** [comment]
Updating here for anyone still having trouble.

I created a file `~/.config/kitty/startup.conf` (in the same directory as my `kitty.conf` and then updated my `kitty.conf` to point to it using the `startup_session` variable.

```startup_session ./startup.conf```

**Comment by Arelav** [comment]
Maybe this will be helpful:
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-specify-command-line-options-for-kitty-on-macos

**Comment by ramanshsharma2806** [comment]
@danielsellergren your approach was helpful, thanks!

I still need help with making the ``startup.conf`` file. I am not able to launch new windows through the startup file.

More specifically, I want the first window to go into a certain directory, a second window into a further subdirectory, and a third window at the first window's directory (I can hard code all these in the conf file). The problem I am facing is with launching windows, setting their title, etc. If I can figure this out then I can easily also change the layouts myself.

A bit unusual to ask for this but it would be really helpful if someone can write a few lines of the ``conf`` file here to show an example of how to achieve this. Thank you!

![image](https://user-images.githubusercontent.com/24642071/137450552-bdec2946-f8e1-4402-9920-d8120187561a.png)

**Comment by page-down** [comment]
@ramanshsharma2806 

> More specifically, I want the first window to go into a certain directory and launch vim, a second window into a further subdirectory, and a third window at the first window's directory (I can hard code all these in the conf file). The problem I am facing is with launching windows, setting their title, etc. If I can figure this out then I can easily also change the layouts myself.
>
> A bit unusual to ask for this but it would be really helpful if someone can write a few lines of the `conf` file here to show an example of how to achieve this. Thank you!

```text
layout horizontal

# first kitty window
cd /path/to/dir
launch --title "left-1" vim .

# second kitty window
cd /path/to/dir/subdir
launch --title "middle-2"

# third kitty window
cd /path/to/dir
launch --title "right-3"
```

Use the following command to try.
```shell
kitty --session path/to/session-file
```

Here is the link to the document.
https://sw.kovidgoyal.net/kitty/overview/#startup-sessions
https://sw.kovidgoyal.net/kitty/remote-control/#kitty-launch

If you have any questions, you can also discuss them on GitHub Discussion.

**Comment by ramanshsharma2806** [comment]
Thank you for your detailed recommendations @page-down!

The git status output is working now.

I will make the startup session the default one so that only one Kitty window will be used instead of a new one opening.

For making a Kitty window full screen through kitty command line, could you please share the command with me 🙏? I tried finding it in the remote control documentation but could not :(

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/remote-control/#cmdoption-kitty-resize-os-window-action

You can run the following command to try.

```shell
kitty -o startup_session=none -o allow_remote_control=socket-only --listen-on unix:~/.local/main-kitty.sock bash -c "kitty @ goto-layout horizontal; kitty @ resize-os-window --action toggle-fullscreen; kitty @ launch --cwd /tmp vim .; kitty @ launch --cwd /tmp; kitty @ launch --cwd /tmp bash -c 'echo hello; read -p PressEnterToExit';"
```

With `socket-only`, only local processes with access rights can control kitty.
So when you use ssh to connect to a remote host, no arbitrary commands will be executed locally by the remote host.

**Comment by page-down** [comment]
> But I can't make this be the "default" startup session right?

Those remote control commands are just called through bash. Write whatever you want to the bash script file, then put that executable after `launch` in the session file.

```bash
#!/usr/bin/env bash
kitty @ resize-os-window --action toggle-fullscreen
kitty @ launch --title do-whatever-you-want
```

Give executable permissions to the script `chmod +x startup.sh`, or call the script file in the session file using an executable that exists in the PATH.

startup_session.conf
```text
launch /absolute/path/to/startup.sh
```

kitty.conf
```text
startup_session startup_session.conf
allow_remote_control socket-only
listen_on unix:~/.local/kitty-{kitty_pid}.sock
```
