### ISSUE TITLE
backspace acts as space in chroot environment

### ISSUE THREAD

**Issue by dancer69** [kovidgoyal/kitty#3950]
When use chroot(I'm in arch linux and use arch-chroot script), backspace doesn't work as expected and behaves as space instead. This happens only on kitty, I tried xfce4-terminal and there there is no problem. I found a similar older issue but I it didn't help. The os I chroot to, has the /usr/share/terminfo directory and it's not empty. 
echo $TERMINFO outputs:
/usr/lib/terminfo
both as user and as root via su.

**Comment by Luflosi** [comment]
Shouldn't echo $TERMINFO output /usr/share/terminfo? Also check that echo $TERM outputs xterm-kitty.

**Comment by dancer69** [comment]
I don't know. How to change it?
Yes, echo $Term outputs xterm-kitty

**Comment by kovidgoyal** [comment]
Install kitty-terminfo in the chroot
