### ISSUE TITLE
Something like `tab_bar_begin_template` and `tab_bar_end_template`?

### ISSUE THREAD

**Issue by ryanerwin** [kovidgoyal/kitty#3953]
**Is your feature request related to a problem? Please describe.**
I'm trying to emulate my [tmuxline.vim](https://github.com/edkolev/tmuxline.vim) style status bar in Kitty
![image](https://user-images.githubusercontent.com/2156415/130010529-40adcf83-2c7c-4a99-b8a3-8a51a2e7b2f2.png)

**Describe the solution you'd like**
I would like to have options similar to `tab_title_template` that apply to the beginning and end of the status line.

For example, at the beginning of the line I would like to have the kitty window number, and at the end of the line, I would like to have the system name. Anything that you would put in a vim statusline or i3bar might be a good candidate for the status bar. 

**Describe alternatives you've considered**
This is just a nice to have.... Would be nice include more information into the status bar.
Of course we can use kitty productively without that - just a nice to have. 

**Additional context**
The current `tab_title_template` works great! Currently I'm using:

```
tab_title_template "{index}  {title[:5]}"
```

On top is my tmux statusline. On the bottom is my Kitty tab bar
![image](https://user-images.githubusercontent.com/2156415/130061229-8864130c-0707-43a7-b5d1-e0397a2b6dfe.png)

**Comment by kovidgoyal** [comment]
This isnt something that's worth the effort to me, but a PR is welcome.
Note that as far as status lines are concerned, my plan is to implement
something along the lines of: #2391 for a general solution
