### ISSUE TITLE
Iosevka glyphs not properly rendered

### ISSUE THREAD

**Issue by marromlam** [kovidgoyal/kitty#3954]
**Describe the bug**
After Iosevka was fixed to work fine with kitty I tried to start using it as my main font. Soonish I saw I have problems with some glyphs https://github.com/be5invis/Iosevka/issues/1188. I honestly do not know if this is an issue with kitty shrinking glyphs, or it is in the font side.

Thanks a lot!

**To Reproduce**
We can see it basically printing the glyphs
```bash
printf "\U02776 " # works nicely
printf "\U1F150 " # wrong
```

**Screenshots**
![Screenshot 2021-08-09 at 02 23 09](https://user-images.githubusercontent.com/41004396/128650217-a4c01b28-9f9f-42b9-aec3-ab4bdf476cbb.png)

**Environment details**
```
# Iosevka font {{{

font_family      Iosevka
bold_font        Iosevka Bold
italic_font      Iosevka Italic
bold_italic_font Iosevka Bold Italic
font_features    Iosevka -calt +dlig cv93=3

adjust_line_height 2

# }}}
```

**Comment by kovidgoyal** [comment]
The rendering is correct. U+1f150 is single width and is supposed to be
rendered in one cell. This has nothing to do with font used. If you
didnt have Iosevka that symbol would be rendered from something like
Noto Sans CJK

**Comment by marromlam** [comment]
Really? Then I don't understand why with Victor Mono is looks as the 1:

![Screenshot 2021-08-19 at 18 30 47](https://user-images.githubusercontent.com/41004396/130107269-16f48793-0e87-417f-9ede-55697cf200d7.png)

**Comment by kovidgoyal** [comment]
Ah I didnt notice the space after the symbol. And I cannot reproduce with Iosevka, with a space it renders in two cells, using the space.

**Comment by kovidgoyal** [comment]
Ah, never mind, I think I know whats going on. Iosevka's special ligature strategy turns of the space based ligatures. So setting iosevka as the main font will break some space ligatures.

**Comment by kovidgoyal** [comment]
Bloody pain in the ass font. I will look into adding support for space based ligatures to the iosevka ligature strategy someday when I have nothing better to do. In the meantime patches are welcome.

**Comment by marromlam** [comment]
> Ah, never mind, I think I know whats going on. Iosevka's special ligature strategy turns of the space based ligatures. So setting iosevka as the main font will break some space ligatures.

Makes sense to me.



> Bloody pain in the ass font. I will look into adding support for space based ligatures to the iosevka ligature strategy someday when I have nothing better to do. In the meantime patches are welcome.

I think in the mean time it is better to use other font.
Thanks a lot for the prompt replies!

**Comment by kovidgoyal** [comment]
Its already fixed, see the commit that closed this issue.
