### ISSUE TITLE
Mouse wheel event handler

### ISSUE THREAD

**Issue by ZappaBoy** [kovidgoyal/kitty#3959]
I tried to map font size up/down with mouse wheel but it doesn't seem possible to map it. 
I noticed that if i run `kitty` with input debug option `kitty --debug-input` there is no output on mouse wheel event.

It would be nice to add wheel mouse event as a "mappable" event.

P.S.: kitty is wonderful.

**Comment by kovidgoyal** [comment]
There is no mouse wheel event. In general wheels are just one very
particular type of input device. Think of laptops with touchpads or
sticks, they have no wheel events. As such this is not going to happen.
There are already keybindings to change font size, you will have to be
content with those.
