### ISSUE TITLE
Fish Shell autocompletions

### ISSUE THREAD

**Issue by Jomik** [kovidgoyal/kitty#396]
Working on completions for the fish shell here https://github.com/Jomik/kitty-completions
Wondering if the pull request should be submitted here or at fish-shell. When installing kitty you can put 'vendor' auto-completions in `/usr/share/fish/vendor_completions.d/kitty.fish`. Exa does this on my system, I've noticed.

**Comment by kovidgoyal** [comment]
The best place would be fish, that way it will work even on platforms where there is no installation, such as macOS. If they refuse, ping me, and I'll  look into adding them to kitty, at least on linux.
