### ISSUE TITLE
Regression: confirm_os_window_close=x stopped to work

### ISSUE THREAD

**Issue by Felixoid** [kovidgoyal/kitty#3960]
**Describe the bug**
The setting is ignored and window/tab is closed silently

**To Reproduce**
1. `kitty --config NONE -o confirm_os_window_close=1`
2. Open a few more windows and tabs
3. Try to close a tab with few windows, it's closed w/o confirmation
4. Try to close an OS window with few tabs, it's closed too

**Environment details**
```
kitty 0.23.1 (8397970bf8) created by Kovid Goyal
Linux felix-lm 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64
Arch Linux \r (\l)
Running under:X11
Loaded config overrides:
  confirm_os_window_close 1

Config options different from defaults:
confirm_os_window_close 1

```

**Comment by kovidgoyal** [comment]
Works for me. Note that if you are running from master, it will ignore
windows that are sitting at a prompt.

**Comment by Felixoid** [comment]
Here's a screencast of a mentioned behavior  
https://user-images.githubusercontent.com/3025537/130208940-8dc2d1fc-1562-4364-b53b-4ff74c2f1012.mp4

**Comment by kovidgoyal** [comment]
Those are all windows sitting at prompts.

**Comment by Felixoid** [comment]
Ok, it seems I didn't get your idea. But how can I now prevent the terminal from unsafe closing the tab or window?

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.confirm_os_window_close does this documentation misleading now?

**Comment by kovidgoyal** [comment]
On Fri, Aug 20, 2021 at 03:57:22AM -0700, Mikhail f. Shiryaev wrote:
> Ok, it seems I didn't get your idea. But how can I now prevent the terminal from unsafe closing the tab or window?

You dont need to do anything: https://github.com/kovidgoyal/kitty/commit/5bc569c4dde5ceab10cba7ee992d052e7154d92c

> 
> https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.confirm_os_window_close does this documentation misleading now?

The documentation refers to the released version, it will change when
the next version is released.

**Comment by Felixoid** [comment]
Oh, thanks. It works now
