### ISSUE TITLE
Run without a Window Manager

### ISSUE THREAD

**Issue by BTrey** [kovidgoyal/kitty#3962]
I am doing something that is probably a bit unusual. I am running Xorg without a windows manager in an Arch linux Virtualbox VM. I do not need Xorg per se but the Linux console from the kernel is very limited in terms of fonts, color, etc. I want to run zsh, prezto, powerline10k prompt, etc. and as I understand it the Linux console simply doesn't have the features to support those capabilities. The solution is to run Xorg without a window manager and with a decent xterm as the sole running application. I can run kitty via: "startx /usr/bin/kitty" but I can only run it in 80x24. It appears in a small box in the top left of the screen and the rest of the screen is blank. Attempting to start it in full screen, I get "[glfw error 65544]: X11: Failed to toggle fullscreen, the window manager does not support it: 0" Since there is no window manager running, that makes sense. Starting maximized results in the same 80x24 box. I've can do this with plain old xterm: "startx /usr/bin/xterm -geometry 1856x1392" results in an xterm window that takes advantage of the full window. But xterm is, well, xterm. I've tried starting xterm and starting kitty from there. It doens't matter if I start if with no args, with start-as fullscreen or maximized, the results in that sad little 80x24 box in the corner. Using the fullscreen or maximized hotkeys do not change anything. Am I missing something or does kitty require a window manager to work at anything other than base resolution? If that is the case, I'd like to request the ability to run without one.

**Comment by kovidgoyal** [comment]
Use -o with 
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remember_window_size
