### ISSUE TITLE
VSCode indent not working properly with Monolisa font

### ISSUE THREAD

**Issue by AliBayatMokhtari** [kovidgoyal/kitty#3963]
I use Monolisa font for programming and I saw that indentation in VSCode is wrong with Monolisa font. I have no problem with other fonts in VSCode. Here is a screenshot from my VSCode settings.json file and the circles with yellow border shows the indentation which has too small width.

**OS: Mac OS X**

![Screen Shot 2021-08-21 at 00 26 15](https://user-images.githubusercontent.com/40760750/130287738-22534fc0-03d2-4a1a-9005-43876cd2253b.png)

**Comment by kovidgoyal** [comment]
This is an issue tracker for kitty not vscode.
