### ISSUE TITLE
I have to click the link several times before the link is opened in my default browser

### ISSUE THREAD

**Issue by amikai** [kovidgoyal/kitty#3965]
**Describe the bug**
I use this setting `mouse_map cmd+left  click ungrabbed mouse_click_url_or_select`. See the following gif,  i have to click the link several times before the link is opened in my default browser.

GIF link: https://cln.sh/fMiiU8

**Environment details**
```
kitty 0.23.0 created by Kovid Goyal
Darwin amikai-macbook.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.1 BuildVersion:	20C69
Loaded config files:
  /Users/amikai_chuang/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select       clipboard
font_family          Hack Nerd Font
font_size            18.0
macos_option_as_alt  3
url_style            1
Added mouse actions:
	 cmd+b1 -2 ungrabbed KeyAction('mouse_click_url_or_select')
Changed shortcuts:
	shift+ctrl+- KeyAction('change_font_size', (True, '-', 1.0))
	shift+ctrl+= KeyAction('change_font_size', (True, '+', 1.0))
Colors:
	background           #282828   
	color0               #282828   
	color1               #cc241d   
	color10              #b8bb26   
	color11              #fabd2d   
	color12              #83a598   
	color13              #d3869b   
	color14              #8ec07c   
	color15              #928374   
	color2               #98971a   
	color3               #d79921   
	color4               #458588   
	color5               #b16286   
	color6               #689d6a   
	color7               #a89984   
	color8               #928374   
	color9               #fb4934   
	cursor               #928374   
	cursor_text_color    #000000   
	foreground           #ebdbb2   
	selection_background #3c3836   
	selection_foreground #928374   

```

**Comment by kovidgoyal** [comment]
Works fine on my macOS machine, though the best mapping is actually:

mouse_map cmd+left press ungrabbed,grabbed mouse_click_url

and note that you can simply click urls without any modifiers to open
them.

**Comment by amikai** [comment]
Thanks, use this setting `mouse_map cmd+left press ungrabbed,grabbed mouse_click_url` solve my problem.

**Comment by amikai** [comment]
@kovidgoyal  What is different between  using`press` and `click` event type in this mapping.

**Comment by jdhao** [comment]
@kovidgoyal  It seems that the command `mouse_click_url` is not documented in https://sw.kovidgoyal.net/kitty/overview/#configuring-kitty.  Where Can I find the documentation for it?

**Comment by kovidgoyal** [comment]
On Sat, Aug 21, 2021 at 10:56:52AM -0700, jdhao wrote:
> @kovidgoyal  It seems that the command `mouse_click_url` is not documented in https://sw.kovidgoyal.net/kitty/overview/#configuring-kitty.  Where Can I find the documentation for it?

https://sw.kovidgoyal.net/kitty/actions/#mouse-click-url

**Comment by kovidgoyal** [comment]
On Sat, Aug 21, 2021 at 10:34:09AM -0700, amikai wrote:
> @kovidgoyal  What is different between  using`press` and `click` event type in this mapping.

See https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.click_interval

**Comment by XSAM** [comment]
> On Sat, Aug 21, 2021 at 10:34:09AM -0700, amikai wrote: @kovidgoyal What is different between using`press` and `click` event type in this mapping.
> See https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.click_interval

I am facing the same problem with kitty `0.23.1` in Ubuntu `20.04.3`. 

Changing `click_interval` to  0.1 will solve this problem. Not sure it might impact the performance of kitty.

**Comment by trygveaa** [comment]
@kovidgoyal: The issue here is that if you click on the link and move the mouse away from the link before `click_interval` has passed, the link will not be opened. I think the link should be opened, even if you move the mouse afterwards.

**Comment by kovidgoyal** [comment]
On Sun, Sep 12, 2021 at 11:44:35PM -0700, Trygve Aaberge wrote:
> @kovidgoyal: The issue here is that if you click on the link and move the mouse away from the link before `click_interval` has passed, the link will not be opened. I think the link should be opened, even if you move the mouse afterwards.

I cannot repro in master, running:
kitty -o click_interval=10 sh -c "echo http://moo.com; cat"

click the link move the mouse off into some blank space and wait ten
seconds, moo.com opens

**Comment by XSAM** [comment]
> The issue here is that if you click on the link and move the mouse away from the link before click_interval has passed, the link will not be opened. I think the link should be opened, even if you move the mouse afterwards.

I can reproduce this in my environment. More interesting, If I click an empty place then move the cursor to a link, kitty will open that link.

**Comment by kovidgoyal** [comment]
See f61b8608ded9f81fac276e048e8c0a043ba917db
