### ISSUE TITLE
Escape key on macOS registers with 1s delay

### ISSUE THREAD

**Issue by phaazon** [kovidgoyal/kitty#3969]
**Describe the bug**
Hitting the escape key feels laggy (~1s). Noticed that in neovim first so I tried in fzf and the `show_key` kitten and the lag is still there.

**To Reproduce**
1. Open an interactive program in Kitty, such as `fzf`, an editor, `kitty +kitten show_key -m kitty`, etc.
2. Press the escape key.
3. Notice how it feels laggy and registers after only a delay has occurred. I guess the delay depends on the machine, but on mine it’s almost 1s.

**Screenshots**
N/A

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal

(I can’t get the output with the keyboard shortcut, it doesn’t seem to work)
```

**Additional context**
I do reproduce without configuration.

**Comment by kovidgoyal** [comment]
I cannot replicate with 

kitty --config NONE kitty +kitten show_key -m kitty

on my mac. Most likely there is something configured either at your OS 
level or in kitty.conf causing it.
