### ISSUE TITLE
How to let Ctrl+Space work in system level (for change typing language) but not kitty itself

### ISSUE THREAD

**Issue by pythonwood** [kovidgoyal/kitty#3975]
**Describe the solution you'd like**
I would like to save some keybind event so that system can catch them. 

in my another linux terminal:
Ctrl+Space  => switch typing language in my system
Ctrl+;         =>  show 5 history copied word in clipboard 

**Additional context**
kitty is good, but doc is a little hard to understand. [keyboard-protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#progressive-enhancement)

**Comment by kovidgoyal** [comment]
Your system catches events before they reach the terminal emulator. So if you want to catch events system wide, catch them system wide. Ad the relevant documentation for how to do keyboard event mapping in kitty is: https://sw.kovidgoyal.net/kitty/conf/  scroll to the keyboard section

**Comment by backtolife2021** [comment]
Kitty seems to prevent some software registered shortcut keys from taking effect, such as rime shortcut keys for switching input methods: ctrl + space
