### ISSUE TITLE
Unicode Input: no character inserted when input_delay > 12

### ISSUE THREAD

**Issue by smeikx** [kovidgoyal/kitty#3980]
**Describe the bug**
When `input_delay` is set to anything higher than 12, pressing enter after selecting a character exits unicode input but does not insert any character. 

**To Reproduce**
1. start kitty with `input_delay` set to anything higher than 12
1. enter unicode input with `Ctrl+Shift+U`
2. choose any character in any mode
3. press enter
4. back to regular shell, nothing happened

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin 10.0.0.11 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.5 BuildVersion:	20G71
Loaded config files:
  /Users/smeikx/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 0.0
input_delay           32
repaint_delay         64
```

**Comment by kovidgoyal** [comment]
Yes, because I have not bothered to implement flushing of pending input
on child death, since there isnt any use case that I know of, for large
input delays. 

Why are you using such large input delays?

**Comment by smeikx** [comment]
Oh, okay.

Honestly, when first configuring kitty I wanted to see how far I could increase the delay without noticing any negative impact. I just left it at this (seemingly?) high value as some kind of micro-optimisation, keeping CPU usage to a minimum. 

I have no need to keep it that high though, I just thought it wouldn’t hurt either.

**Comment by kovidgoyal** [comment]
input delay increases latency so you typically dont want it larger than
a few ms, as otherwise the delay when you type becomes noticeable.

Still I suppose it wont hurt to flush the input queue when a child dies,
I'll look into that when I have a moment.
