### ISSUE TITLE
Ctrl shift f2 does not work what am I doing wrong.. I can't even find the config files.

### ISSUE THREAD

**Issue by Etzio-TUI** [kovidgoyal/kitty#3981]
Press ctrl+shift+f2 and edit the config file that will open and you will be fine.

_Originally posted by @kovidgoyal in https://github.com/kovidgoyal/kitty/issues/1375#issuecomment-462857166_

**Comment by kovidgoyal** [comment]
I dont know what you are doing wrong, it could be any number of things.
In any case the kitty config file is ~/.conf/kitty/kitty.conf which you
can see by reading kitty --help for the --config option.

**Comment by code-IM-perfect** [comment]
Was facing the same issue, it turns out `Ctrl+Shift+Fn+F2` and `Shift+Fn+Ctrl+F2` and `Ctrl+Fn+Shift+F2`, etc work but pressing Fn first doesn't work for whatever reason so if you're on a laptop do keep that in mind

**Comment by kovidgoyal** [comment]
Fn+Ctrl+Shift+F2 works on my linux laptop under X11 as does Ctrl+Shift+Fn+F2

**Comment by code-IM-perfect** [comment]
IDK maybe it has something to do with the manufacturer/model, mine is a Lenovo Ideapad

**Comment by heaveaxy** [comment]
Same thing. I used left ctrl+shift. If I use right ones - config opens.
MSI GK30
