### ISSUE TITLE
Unable to launch alias cmds

### ISSUE THREAD

**Issue by ota0912** [kovidgoyal/kitty#3982]
When I try to launch a `.bashrc` alias command using `kitty -e aliascmd`, it reports the error 
`Failed to launch child: aliascmd With error: No such file or directory` 
Why does this happen even though am able to run the alias command directly?

**Comment by kovidgoyal** [comment]
aliases are shell specific. When you are running a program in kityt it
needs to be a binary in your PATH not an alias in your shell.
