### ISSUE TITLE
copytree() got an unexpected keyword argument 'dirs_exist_ok' in setup.py with Python 3.7

### ISSUE THREAD

**Issue by invakid404** [kovidgoyal/kitty#3989]
**Describe the bug**
When compiling kitty from source with a Python interpreter, older than 3.8, the setup.py script will fail due to the `dirs_exist_ok` argument not existing for `copytree()`.

**To Reproduce**
1. Use Python <3.8
2. Compile kitty from source
3. Run setup.py
4. Observe the error

**Environment details**
The key here is that `dirs_exist_ok` was only [added in Python 3.8+](https://github.com/kovidgoyal/kitty/blob/6daee3a0b5d667d221054200f53f35dee0d04c18/setup.py#L1103) (see "New in version 3.8"), so using a Python version older than that, 3.7 for example, is enough to reproduce this error.

**Additional context**
We ran into this issue with our kitty package in Funtoo Linux, since we still run Python 3.7 as our default Python interpreter. We've found a temporary workaround, which involves simply removing the flag from the copytree call on [this](https://github.com/kovidgoyal/kitty/blob/6daee3a0b5d667d221054200f53f35dee0d04c18/setup.py#L1103) line. Kitty still appears to install fine without the argument.

The question here is whether this is intentional and whether it would mean that Kitty now requires Python >=3.8 to install. If so, the Python version requirements should be updated. If not, I hope you can look into getting rid of the argument as a whole or replacing it with a backward-compatible equivalent if any.

**Comment by invakid404** [comment]
@kovidgoyal Thank you for the quick reaction! In relation to this issue, I've noticed that your CI doesn't run the setup.py script and this is how this issue slipped past your radar. Perhaps running it as well would prevent such things in the future and I hope you'd consider doing it.

**Comment by kovidgoyal** [comment]
It does run setup.py, it just does not run all of it under every python
version.

**Comment by invakid404** [comment]
Ah, I see. Well, it'd make sense to run it for every Python version then IMHO. Such random things can slip past the CI in the future otherwise.
