### ISSUE TITLE
How can one change the unfilled block cursor (when the windows is not focused) to an empty cursor shape?

### ISSUE THREAD

**Issue by magnusrandom** [kovidgoyal/kitty#3990]
First, sorry for asking this type of question but I just can't find a way to hid the unfilled block cursor when my mouse is not focused on the specific terminal (see picture bellow). I had some hours of search but could not find anything. 

![image](https://user-images.githubusercontent.com/25163864/131909899-17aee3f5-6570-4a0a-980a-14e2c29191f3.png)

It should be something as simple as changing the cursor shape but I can't find info about it anywhere. Is there any way to do this that I'm missing? A huge thanks to the kitty dev and community for this software.

**Comment by kovidgoyal** [comment]
You can change the overall cursor shape with https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape  however, there is no way to change the shape used for unfocused window cursors.

**Comment by magnusrandom** [comment]
Thanks for the words Kovidgoyal! Have a nice weekend.
