### ISSUE TITLE
mouse selection highlighting

### ISSUE THREAD

**Issue by justinesmithies** [kovidgoyal/kitty#3993]
I have always used Kitty as it's fantastic but usually on my main with Arch & i3 but i'm currently testing on a PineBook Pro with Arch and Sway so no X and I have one small issue which I cannot seem to find the answer for.
If i use the mouse to select text under i3 it obviously highlights the text being selected but under Sway it does not highlight anything in the terminal yet shift+ctrl c and v still work you just can't see what's being highlighted.
Am I being stupid or is this an actual issue ?

**Comment by kovidgoyal** [comment]
Highlighting works fine under sway for me. Its most likely something in
your kitty.conf. Run with 

kitty --config NONE 

to confirm.

**Comment by justinesmithies** [comment]
Nope still doesn't work as already tried that.

**Comment by kovidgoyal** [comment]
I cant think of anything that could cause it other than something in kitty.conf, I'm afraid.
