### ISSUE TITLE
Kitty Installation Directory

### ISSUE THREAD

**Issue by rationalthinker1** [kovidgoyal/kitty#3994]
I installed kitty a while back. I know I installed kitty in a custom directory, but I cannot find it, I tried `sudo find / -type d -name "kitty*"` and tried looking manually myself. Whenever I tried to install it myself, a new instance is downloaded in `~/.local`, but I want to override it, not install another. One thing that I would suggest is have the folder shown on `kitty --debug-config`

How do I find out the kitty installation directory?

**Comment by kovidgoyal** [comment]
Use find to find the kitty executable. And you dont need to know the installation
directory unless you move it, the installer script automatically
replaces the old installation. https://sw.kovidgoyal.net/kitty/binary/
