### ISSUE TITLE
Doing an SSH from Kitty causes a weird echo of typed chars.

### ISSUE THREAD

**Issue by vimishra** [kovidgoyal/kitty#3996]
**Describe the bug**
On SSHing to a remote computer, the characters that are being typed appear more than once (sometimes). The below screenshot shows what I am talking about. 

**To Reproduce**
1. ssh remoteuser@remotehost
2. Type a command
3. Removing kitty config doesn't seem to make a difference. 

**Screenshots**
See the attached screenshot to see the issue. 
<img width="665" alt="Screen Shot 2021-09-06 at 2 01 45 PM" src="https://user-images.githubusercontent.com/252368/132186183-12e1d43d-f22f-45d7-83a7-611c1738a6ab.png">

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin vikasmis-mac07.local 21.1.0 Darwin Kernel Version 21.1.0: Thu Aug 19 02:54:46 PDT 2021; root:xnu-8019.40.29~26/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.0 BuildVersion:	21A5506j

Config options different from defaults:
```

**Additional context**
Ran with kitty --config NONE and still see the same issue. Earlier I had deleted `~/.config/kitty` folder and there was no difference in the occurrence of the issue.

**Comment by kovidgoyal** [comment]
install the kitty terminfo file on your remote computer, see the kitty
FAQ.

**Comment by vimishra** [comment]
Thanks for the super prompt response. That was the issue.
