### ISSUE TITLE
Triple-click selection : should allow multiple lines selection

### ISSUE THREAD

**Issue by paxal** [kovidgoyal/kitty#400]
Hi ! First of all thanks for this project, now I can use emojis easily in my git commits :+1: 

I tried to select multiple lines, and usually I triple-click on a line and then move the mouse up/down to select a ~~few~~ lines before or after.

The triple click works, but after the triple click release. If I triple click and let the left click down, it acts as if I only had clicked once.

**Comment by kovidgoyal** [comment]
I'm not sure I understand. A line is selected after you triple click. Which means you press *and* release the mouse button three times. So how are you extending the selection after that? In any case, if you run from master, you can now extend selections by simply right clicking at the extension point, no need to drag.

**Comment by paxal** [comment]
Well, I have the same issue for double click : when the double click is pressed but not yet released, in common desktop apps, it will make the selection from the word you made your double click from (not released) to the word where the click is released. Same behavior with lines for triple click.

Here is an example : if kitty writes on the terminal 
```
The quick brown fox jumps over the lazy dog
```

If I double click on `quick`, without releasing the second click, move the mouse to `lazy`, and release there, then it will select `quick brown fox jumps over the lazy`. This is common behavior we also have in browsers, you can give it a try :)

Here is a small GIF : ![double_click](https://user-images.githubusercontent.com/1848817/37662484-70116a2e-2c57-11e8-9196-abd14b65065a.gif)

**Comment by kovidgoyal** [comment]
You can extend double click selections using a right click as well.

**Comment by paxal** [comment]
Yes you're right, what I like is the "helper" that automatically selects the whole word, and the second thing is having the same behavior than in other desktop apps :)

**Comment by kovidgoyal** [comment]
If you right click after double clicking it automatically selects complete words. I'm not particularly interested in compatibility with other desktop apps in this case, as IMO right click to extend selection is much easier to use than dragging (other desktop apps dont do this because they have right click menus). That said I wont refuse a patch to implement the drag to extend behavior as well.
