### ISSUE TITLE
make sample kitty.conf file more obviously available

### ISSUE THREAD

**Issue by CouldBeThis** [kovidgoyal/kitty#4002]
I'd like to suggest that on the [kitty.conf documentation](https://sw.kovidgoyal.net/kitty/conf/), the [section](https://sw.kovidgoyal.net/kitty/conf/#sample-kitty-conf) linking to the sample file be moved close to the **top** rather than at the very end as currently. 

reason: it will be obvious right away a lot of needless copy/pasting can be avoided.

**And/or**

include it with installation as `~/.config/kitty/kitty.sample.conf` or a more appropriate file name. 

reason: it would be found by someone even if they were zipping around the documentation. it is already where it needs to be.

**Comment by kovidgoyal** [comment]
It is already included with the installation. When no config file is
present,pressing ctrl+shift+f2 or cmd+, will create a default config file
and open it in your editor.

And note that there is no need to copy paste anything. Only keep entries
in your config file that you want to be different from defaults.
