### ISSUE TITLE
kitty renders double-width nerd icons with no extra space in bold, italic, and bold italic

### ISSUE THREAD

**Issue by EdwarKenedy** [kovidgoyal/kitty#4004]
**Describe the bug**
kitty tries to render double width nerd icons when there is no extra space cutting the nerd icon.

**To Reproduce**
1. ```echo -e "\e[1m\uf0f6bold\e[0m"```
2. ```echo -e "\e[3m\uf0f6italic\e[0m"```
3. ```echo -e "\e[3m\e[1m\uf0f6bold italic\e[0m"```

**Screenshots**
![image](https://user-images.githubusercontent.com/36998912/132588502-0e600527-25b3-46b7-961b-55cf7d01381a.png)

**Environment details**
```
kitty 0.23.1
macOS 11.5.2
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty
