### ISSUE TITLE
General purpose set-spacing (entering/leaving any terminal application)

### ISSUE THREAD

**Issue by maxdevjs** [kovidgoyal/kitty#4005]
Today I did set a bit up my `Kitty` configuration and started to use `margin` and `padding`.

I checked #1915 and found that nowadays is possible to easily solve the situation described in the issue: https://github.com/kovidgoyal/kitty/issues/1915#issuecomment-915773668

The solution that I found so far is restricted to `nvim` and I'd like to reset/set `margin` and `padding` when entering/leaving any terminal application.

There is something that I can explore in `Kitty` api that could help me to identify when entering/leaving any terminal application?

Also, `cmds.py` is now spread in https://github.com/kovidgoyal/kitty/tree/master/kitty/rc, right?

**Comment by kovidgoyal** [comment]
kitty has no knowledge of you running terminal applications, that is
done by the shell. Look in your shell docs for hooks to run things
before and after running commands.

And yes rc/ is where remote control commands are defined.
