### ISSUE TITLE
Option to choose default shell only and only for kitty terminal

### ISSUE THREAD

**Issue by j0k4rX** [kovidgoyal/kitty#4008]
**Describe the feature you'd like**
I want a feature: option to choose default shell for kitty

for example:
on macOS, i have both **default terminal** and **kitty terminal**. 
And I don't want `zsh` to be default in those two.
via this feature, `bash` will be default shell in kitty whereas `zsh` is already by-default in macOS terminal.

**Describe alternatives you've considered**
found no solution

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.shell

**Comment by ianb-mp** [comment]
I just installed Kitty on Mac OS via [Homebrew](https://brew.sh/) and found that kitty would not run bash shell (also installed via brew). Terminal was using bash fine, but Kitty continued to use zsh even though the output of `env` showed `SHELL=/opt/homebrew/bin/bash` (inside Kitty).

I fixed the issue by explicitly setting `shell /opt/homebrew/bin/bash` in my `kitty.conf`.

**Comment by bsr-blinkit** [comment]
I tried both the approaches but neither are working. My default shell is already to `SHELL=/opt/homebrew/bin/bash`.

I am using Macbook M4 with MacOS Sequoia (Version 15.6.1 (24G90)) 

If someone had any luck with it, please let me know.

**Comment by junegunn** [comment]
FYI. Kitty kept starting zsh even after I ran `chsh`, but logging out and back in fixed it for me.
