### ISSUE TITLE
TERM Backwards Compatibility

### ISSUE THREAD

**Issue by adrianmace** [kovidgoyal/kitty#4009]
**Is your feature request related to a problem? Please describe.**
I just moved to Kitty from alternatives on macOS, however when I `ssh` into my first server I see that backspace doesn't work. Not to worry, you have [an FAQ](https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer) about this and give a suggestion, but this requires making modifications to the server. I can't do that - my user is read only. What are my options here?

**Describe the solution you'd like**
I'd like the ability for Kitty to work in a 'backwards-compatible' mode with `xterm-256color` or some other terminfo that is standard across a large range of distros.

**Describe alternatives you've considered**
- Using terminal.app for these connections
- Setting `term xterm-256color` in `kitty.conf` (but I risk breaking other things here)

**Additional context**
This has been discussed at length in other issues but the concensus is always that you should just include the terminfo in the remote server - again, this is not possible in all cases.

**Comment by kovidgoyal** [comment]
As I have said before, this is not going to happen. If I wanted to write
an xterm clone, I would never have bothered at all.

**Comment by allemangD** [comment]
@adrianmace There's a bunch of discussion about working around this here: https://github.com/kovidgoyal/kitty/discussions/3873#discussioncomment-1067362. To be clear none of this is "supported", but in read-only or similar cases there's not much choice. 

> Setting term xterm-256color in kitty.conf (but I risk breaking other things here)

As you can see in the linked comment, _generally_, you'll be fine, but will miss out on most of the kitty's extra features (ie. images, text decorations, etc) similar to the issues people see with tmux.

So I would suggest setting `TERM=xterm-256color` _only_ for your problematic servers, and install the `xterm-kitty` definition on servers where you are able. This way you still get full compatibility everywhere but your problematic servers - that's the big problem with setting it in `kitty.conf`, you break compatibility _everywhere_.

The easiest thing may be something like `alias ssht='TERM=xterm-256color ssh'`. Depending on your ssh client version and server configuration you may be able to add `SetEnv TERM=xterm-256color` to your `.ssh/config` - [see here](https://serverfault.com/questions/986847/ssh-behavior-of-setenv-for-term-variable).
