### ISSUE TITLE
Multiple themes - toggle

### ISSUE THREAD

**Issue by Jomik** [kovidgoyal/kitty#401]
I'd like to be able to toggle between themes as it would be nice to be able to use a light and a dark theme.
Perhaps have theme files in `config_dir` that contain the values for all color config options.

**Comment by kovidgoyal** [comment]
You can switch colors ina ll modern terminals using escape codes, which you can put into shell scripts. A bit of googling should get you information on that.

**Comment by Jomik** [comment]
I've google, and I can't seem to find anything that does what I'm expecting. First - I'd like to theme the background, the active window, the tabs, etc. Also, kitty seems to remove these escapes after the command has been run. So it doesn't stick.

**Comment by kovidgoyal** [comment]
kitty most definitely does not remove the escapes. If they are being reset then it is likely you have some config in your shell that is doing it. The background in kitty automatically follows the active window background if there is a single window.

**Comment by Jomik** [comment]
Yeah, they're being removed by my prompt. But my idea was being able to change the color of the background, tabs, and the highlight we use to show active window.
Also, what do you mean it goes the active window? The way I set the color was by editing kitty.conf

**Comment by kovidgoyal** [comment]
If you set the default background color via an escape code and there is only one window kitty will use that color for the background of the padding margin around the window. See #323 for a discussion.

You can set the highlight colors and cursor colors using escape codes as well. That leaves only the tab bar colors. It's not worth it for just those two colors, IMO. Just pick colors that work well with both your themes.

**Comment by Jomik** [comment]
Really! Okay, I'll try that. I guess my Google skills need work.

**Comment by kovidgoyal** [comment]
Search http://invisible-island.net/xterm/ctlseqs/ctlseqs.htmlthis page for dynamic colors.

**Comment by Jomik** [comment]
Oh. So the reason https://github.com/morhetz/gruvbox/blob/master/gruvbox_256palette.sh seemingly does nothing, is because it's setting color numbers > 15.

**Comment by kovidgoyal** [comment]
You can set all 256 colors in kitty in using the appropriate OSC code, look in the OSC codes section of the link I posted earlier. I have no idea what that shell script is doing, reading shell makes my eyes bleed, but from briefly glancing at it, its likely doing things based on the value of TERM, since it does not know about TERM=xterm-kitty it will need adjustment.
