### ISSUE TITLE
Kitty has lower FPS/refresh rate when fullscreen with Freesync on

### ISSUE THREAD

**Issue by ManInTheSuit** [kovidgoyal/kitty#4013]
**Describe the bug**
When Kitty is fullscreen with monitor Freesync enabled, kitty has lower FPS/refresh rate. This is visible through mouse moving really slow within window.

Note that kitty doesn't have such a problem when it isn't fullscreen (e.g. it has a tittle, or another window on desktop). I tested Alacritty and gnome-terminal and they do not exhibit the same issue.

**To Reproduce**
1. Launch kitty on an empty desktop, make sure kitty window is fullscreen (no gaps, window decorations or borders).

**Screenshots**
-

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux tao 5.13.12-193.current #1 SMP PREEMPT Fri Aug 20 14:21:44 UTC 2021 x86_64
[[ Solus Operating System ]]
LSB_VERSION=1.4
DISTRIB_ID=Solus
DISTRIB_DESCRIPTION="Solus"
DISTRIB_RELEASE=4.3
DISTRIB_CODENAME=fortitude
Running under:X11
Loaded config files:
  /home/supcom/.config/kitty/kitty.conf

Config options different from defaults:
bold_font                       Hack Bold
bold_italic_font                Hack Bold Italic
cursor_blink_interval           0.0
cursor_shape                    2
font_family                     Hack Regular
font_size                       13.0
italic_font                     Hack Italic
scrollback_fill_enlarged_window True
tab_bar_edge                    1
tab_bar_margin_height           TabBarMarginHeight(outer=6.66, inner=0)
tab_bar_margin_width            3.33
tab_bar_style                   slant
update_check_interval           24.0
url_style                       1
window_padding_width            FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added shortcuts:
	shift+super+w KeyAction('close_os_window')

```

**Additional context**
I tried changing syncing to refresh rate to no, but it doesn't fix it. The WM is BSPWM

**Comment by Luflosi** [comment]
I don't have the hardware to test this myself but try playing with https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.repaint_delay.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.sync_to_monitor

**Comment by ManInTheSuit** [comment]
> https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.sync_to_monitor

I opened this bug because the linked option doesn't prevent the input lag when set to no.

**Comment by Luflosi** [comment]
Did you try my suggestion?

**Comment by ManInTheSuit** [comment]
> Did you try my suggestion?

I tried fiddling a bit with the setting, increasing it and decreasing, and it seems that _changing the value itself_ makes the input lag just a tiny bit smoother, but nothing significant. Could be just placebo though.

**Comment by kovidgoyal** [comment]
I dont know what freesync is presumably some amd specific thing? kitty does not have any code to interact with it. On X11 which is what you are on, sync_to_monitor is implemented by the system drivers, not kitty (kitty just calls swapbuffers and the X11 driver is responsible for syncing the buffer swap). So the issue is happening in some layer under kitty, probably the graphics driver/mesa/egl.

Since X11 is no longer maintained, I suggest you try wayland or turn off freesync. Other than that, I dont have any suggestions, and given I dont have the requisite hardware, no way to debug either. You are welcome to investigate the issue yourself, Feel free to ask for code pointers if you need them.

**Comment by ManInTheSuit** [comment]
Alright, I will workaround it by simply making kitty not spawn fullscreen.

**Comment by kovidgoyal** [comment]
Or just add it to the VRR blacklist https://wiki.archlinux.org/title/Variable_refresh_rate#Remove_applications_from_Blacklist

**Comment by ManInTheSuit** [comment]
I thought about adding it to blacklist, but wouldn't drivers overwrite it on update/changes? Since the file is read only.

In that case I'd also have to make some kind of post-update hook for my package manager too.

**Comment by kovidgoyal** [comment]
Just open an issue with mesa to add it to the upstream blacklist.

**Comment by ManInTheSuit** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5340 done

**Comment by Luflosi** [comment]
Consider also linking to this issue there.
