### ISSUE TITLE
Copy Paste large text performance degrades exponentially

### ISSUE THREAD

**Issue by nigurr** [kovidgoyal/kitty#4016]
**Describe the bug**
Copy pasting any large text causes terminal slow down incredibly.
First 1-2 lines are pretty fast and then subsequent lines are slow and after 10 lines, each word takes a second.

**To Reproduce**
1. Copy paste any large text 

**Screenshots**

https://user-images.githubusercontent.com/15208679/132940701-25e92616-16f0-4c3e-8f1d-49ac4cb5a31c.mp4

**Environment details**
```
kitty 0.23.1 (cd7b4fcd8e) created by Kovid Goyal
Linux pop-os 5.13.13-051313-generic #202108261440 SMP Thu Aug 26 14:50:08 UTC 2021 x86_64
Pop!_OS 21.04 \n \l
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0
```

**Additional context**
If I press Ctrl+Shift+x while this operation is happening, the paste is super fast and almost gets finished in second.

**Comment by kovidgoyal** [comment]
This will be an issue with your shell. Run

kitty cat

and do the paste and it will be instantaneous.

**Comment by nigurr** [comment]
@kovidgoyal thanks for directing me on that. `zsh-syntax-highlighting` is causing this issue (for future ref)
