### ISSUE TITLE
Can't Swicth Themes from a bash script.

### ISSUE THREAD

**Issue by pegromdev** [kovidgoyal/kitty#4017]
Hi, I am calling themes from within a bash Script, when single words themes are call it works fine but
when any other with more then one word is call I get "No theme named: 1984\  Dark" .
I am grabbing the names from the top of a file and inserting it into a bash Varieble call:
KITTYTHEME="$(head -n 1 $THEMETOLOAD)"
So when echoing KITTYTHEME and manually executing `kitty +kitten themes --reload-in all 1984\  Dark` Works fine...

**To Reproduce**
1. Create a file with any of the kitty themes name that has more then one word and put it  in the first line.
2.  Bash Script:

```
THEMETOLOAD="PATH TO YOUR FILE"
KITTYTHEME="$(head -n 1 $THEMETOLOAD)"
kitty +kitten themes --reload-in all $KITTYTHEME 

```
No theme named: 1984\ Dark

**Additional context**
Try to reproduce the problem with `kitty --config NONE` 
##  kitty --config NONE

Failed to launch child: +kitten
With error: No such file or directory
Press Enter to exit.

Thanks in advanced for taking time to look into this..

**Comment by kovidgoyal** [comment]
Remove the back slash
