### ISSUE TITLE
ctrl+shift does not work

### ISSUE THREAD

**Issue by iharh** [kovidgoyal/kitty#4020]
ctrl+shift combinations does not work in my kitty, but works in other terminals (like qterminal)

**Environment details**
OS: Lubuntu 21
Kitty: 0.23.1 (installed from the latest binaries)
WM: aweseome (built from sources)

$ kitty --config NONE -o 'map kitty_mod+n new_os_window' --debug-keyboard
Loading new XKB keymaps
Modifier indices alt: 0x3 super: 0x6 hyper: 0xffffffff meta: 0xffffffff numlock: 0x4 shift: 0x0 capslock: 0x1
Press xkb_keycode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 0xe062 native_code: 0xffe3 action: PRESS mods: none text: '' state: 0 ignoring as keyboard mode does not support encoding this event
Press xkb_keycode: 0x32 clean_sym: Shift_L composed_sym: ISO_Next_Group  is a keyboard layout shift key, ignoring.
Press xkb_keycode: 0x39 clean_sym: n composed_sym: n mods: ctrl glfw_key: 110 (n) xkb_key: 110 (n)
on_key_input: glfw key: 0x6e native_code: 0x6e action: PRESS mods: ctrl text: '' state: 0 sent key to child
Release xkb_keycode: 0x39 clean_sym: n mods: ctrl glfw_key: 110 (n) xkb_key: 110 (n)
on_key_input: glfw key: 0x6e native_code: 0x6e action: RELEASE mods: ctrl text: '' state: 0 ignoring as keyboard mode does not support encoding this event
Release xkb_keycode: 0x32 clean_sym: Shift_L mods: ctrl glfw_key: 57441 (LEFT_SHIFT) xkb_key: 65505 (Shift_L)
Release xkb_keycode: 0x25 clean_sym: Control_L mods: ctrl glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 0xe062 native_code: 0xffe3 action: RELEASE mods: ctrl text: '' state: 0 ignoring as keyboard mode does not support encoding this event

**Comment by kovidgoyal** [comment]
ctrl+shift does not work in any terminal. Some terminal just ignore the
shift and produce the same bytes as pressing only ctrl, easily verified
by running showkey -a

kitty does not do that.

**Comment by iharh** [comment]
Which key combination do you recommend (taking kitty behavior into account)?

**Comment by kovidgoyal** [comment]
Just use ctrl instead of ctrl+shi there is no benefit to be gained from
pressing the extra modifier.

**Comment by iharh** [comment]
Thank you. I've just tried "ctrl+space" and it works fine with kitty
