### ISSUE TITLE
Turning OSC 52 selection reading on (and off) on the fly

### ISSUE THREAD

**Issue by dluciv** [kovidgoyal/kitty#4022]
**The matter**
OSC 52 is quite useful to work with, but, when logging into untrusted remote hosts, it lacks a security: remote software can read local selsctions without notifying the user.

It is not a Kitty issue (so not posting it as a security problem), but rather all terminals, supporting OSC 52 for selection sharing. Being first to handle this in the right way, Kitty can set a good example to others.

**Possible solutions**
Either make selection reading switchable in runtime (probably be by the kitten invoked for a hotkey) or, on the first per-session attempt to read user selection, ask the user if they want to allow or disallow it. Actually the both approaches look very friendly to the user.

**Comment by kovidgoyal** [comment]
Reading the clipboard is disabled by default. And is fairly useless
anyway. https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.clipboard_control

**Comment by kovidgoyal** [comment]
And actually while I am here, I might as well implement the ask for permissions on read behavior, it should be a trivial patch.

**Comment by dluciv** [comment]
This is great, thank you!

No matter how often it is used, in any case this is the safiest solution.
