### ISSUE TITLE
Is it possible to stop default shortcut key?

### ISSUE THREAD

**Issue by j0k4rX** [kovidgoyal/kitty#4026]
**Describe the feature you'd like**
I want some default shortcut key specifically not to work in kitty.
How do i do that?

PS: I have read the `clear_all_shortcuts yes` but it doesn't meet my requirements. 
'cause i only need some keys to not work

**Comment by kovidgoyal** [comment]
Read https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts paying
special attention to no_op

**Comment by pydolan** [comment]
Update: Look for "discard_event" in the above links. e.g.,
```
# completely ignore a keyboard event
map ctrl+alt+f1 discard_event
```

**Comment by koaydemir** [comment]
I'm still having this problem. kitty 0.36.0. macos sonoma 14.6.1. adding clear_all_shortcuts yes on top of my config file breaks all shortcuts. Things like copy paste, and all the shortcuts that i define AFTER clear_all_shortcuts
