### ISSUE TITLE
Font is really bold when using Kitty

### ISSUE THREAD

**Issue by creativecreature** [kovidgoyal/kitty#4027]
Hi,

I've been trying out Kitty, but I can't make the font render nicely.  See the comparison of what it looks like in Alacritty:

![alacritty](https://user-images.githubusercontent.com/12787673/133248024-e5b062f9-7a28-407c-838a-e50faed63852.png)

and in Kitty:
![kitty](https://user-images.githubusercontent.com/12787673/133248030-6df73e4e-0105-4dbf-ac28-18c6b7e9903a.png)

Do you have any suggestions? I'm on Ubuntu 21 and this is my `fonts.conf`:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
 <alias>
  <family>monospace</family>
  <prefer>
    <family>OperatorMono Nerd Font</family>
    <family>Noto Color Emoji</family>
    <family>Noto Emoji</family>
   </prefer>
 </alias>
</fontconfig>
```

**Comment by kovidgoyal** [comment]
The two are using different fonts. If you want to see what font kitty is
using, use --debug-font-fallback. And set the font you want in
kitty.conf

**Comment by creativecreature** [comment]
This is the output I get from using that flag:
```
[257 13:23:24.101474] Ignoring unknown config key: open_url_modifiers
[257 13:23:24.149236] Preloaded font faces:
[257 13:23:24.149270] normal face: /home/c.conner/.local/share/fonts/Operator Mono Bold Nerd Font Complete.otf:0
[257 13:23:24.149281] bold face: /home/c.conner/.local/share/fonts/Operator Mono Bold Nerd Font Complete.otf:0
[257 13:23:24.149290] italic face: /home/c.conner/.local/share/fonts/Operator Mono Bold Italic Nerd Font Complete.otf:0
[257 13:23:24.149301] bi face: /home/c.conner/.local/share/fonts/Operator Mono Bold Italic Nerd Font Complete.otf:0
U+2601 U+fe0f emoji_presentation Face(family=Noto Color Emoji, style=Regular, ps_name=NotoColorEmoji, path=/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf, index=0, is_scalable=False, has_color=True, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0, strikethrough_position=530, strikethrough_thickness=102) (new face)
U+276f bold Face(family=DejaVu Sans Mono, style=Bold, ps_name=DejaVuSansMono-Bold, path=/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf, index=0, is_scalable=True, has_color=False, ascender=1901, descender=-483, height=2384, underline_position=-85, underline_thickness=90, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

**Comment by kovidgoyal** [comment]
Yup you are using Operator Mono Bold as your normal font.

**Comment by creativecreature** [comment]
How is it choosing that though? Even if I set this in the kitty.conf: `font_family SFMono` I still get the same output with the --debug-font-fallback flag

**Comment by kovidgoyal** [comment]
It uses fontconfig. If you want to set a font, run kitty + list-fonts then pick a font family name from there and use it. 

And as general advice, dont use patched fonts, they are not needed in kitty, and patching often breaks them. kitty will pick the nerd symbols automatically if you have the actual nerd font installed, or you can tell it to use a particular font for them via symbol_map. https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map

**Comment by kovidgoyal** [comment]
Oh and read https://sw.kovidgoyal.net/kitty/conf/#fonts  it even uses Operator Mono as an example.

**Comment by creativecreature** [comment]
Thanks a lot for your time and help, I really appreciate it. Running kitty with list-fonts was really helpful - it was just a mismatch with the names.
