### ISSUE TITLE
Kitty emits diagnostic messages when starting/exiting midnight commander

### ISSUE THREAD

**Issue by moosotc** [kovidgoyal/kitty#4028]
**Describe the bug**
[257 14:23:23.658830] [PARSE ERROR] Unknown CSI s sequence with start and end modifiers: '?' '' and 1 parameters
[257 14:23:24.544932] [PARSE ERROR] Unknown CSI r sequence with start and end modifiers: '?' '' and 1 parameters
**To Reproduce**
1. start some terminal emulator
2. start kitty
3. start midnight commander
4. exit midnight commander (F10 Esc-0)
5. see 2 diagnostic messages

**Additional context**
What i see is reproducible with --config NONE
```
- kitty --version 
kitty 0.23.1 created by Kovid Goyal
- cd rcs/git/kitty 
~/x/rcs/git/kitty
- git describe --tags
v0.23.1-179-gb1322fbe
```

**Comment by kovidgoyal** [comment]
yes, mc is using escape codes kitty does not recognize. kitty reports
all such escape codes.

**Comment by kovidgoyal** [comment]
Oh and since I had a few minutes I added support for this escape code: https://github.com/kovidgoyal/kitty/commit/2a8fd278c15bfd9527e3aa321ef8ab72217339bb
