### ISSUE TITLE
Ability to specify initial window position

### ISSUE THREAD

**Issue by moosotc** [kovidgoyal/kitty#4029]
There are initial_window_(width|height) options, i'm accustomed to being able to set the position too (e.g. rxvt-unicode
has geometry argument that can do that)

**Describe alternatives you've considered**
Considered xdotool(1)ing inside the wrapper script around kitty, but that's, AFAICT - racy.

**Comment by kovidgoyal** [comment]
Use wmctrl, it's not the job of applications to position windows, its the
job of the window manager. Indeed, setting window positions is not even
possible on tiling window managers, and any window manager under
wayland.

**Comment by moosotc** [comment]
Kovid Goyal ***@***.***> writes:

> Use wmctrl, it's not the job of applications to position windows, its the
> job of the window manager. Indeed, setting window positions is not even
> possible on tiling window managers, and any window manager under
> wayland.

Yet you have initial_window_width/height when it's the job of the window
manager. Yes i can do what i want with xdotool (never used wmctrl), but,
as the original report says, i don't know how to do that in a race free
manner.

**Comment by kovidgoyal** [comment]
Applications know what size they need to be, window managers know where
they need to be. And hey if you want to argue, argue with the developers
of Wayland and tiling window managers. I am not willing to implement
things in kitty that work some of the time, in some places, and then I
have to be forever on the hook for dealing with bug reports about them. 

I have no clue what race you are referring to. This is a window
position, it can be changed and adjusted at any time, the worst that can
happen is a window is momentarily positioned at the wrong place. You
know the PID of the kitty process, from that you can trivially get the
window id using wmctrl -l -p and from that you can move the window
around however you like, again using wmctrl.

**Comment by moosotc** [comment]
Kovid Goyal ***@***.***> writes:

> Applications know what size they need to be, window managers know where
> they need to be. And hey if you want to argue, argue with the developers
> of Wayland and tiling window managers. I am not willing to implement
> things in kitty that work some of the time, in some places, and then I
> have to be forever on the hook for dealing with bug reports about them. 
>
> I have no clue what race you are referring to. This is a window
> position, it can be changed and adjusted at any time, the worst that can
> happen is a window is momentarily positioned at the wrong place. You
> know the PID of the kitty process, from that you can trivially get the
> window id using wmctrl -l -p and from that you can move the window
> around however you like, again using wmctrl.
>

I've completely forgotten about _NET_WM_PID, thanks pushing me into the
right direction.

```xdotool search --pid $PID _ windowmove $X $Y```should work, cheers.
