### ISSUE TITLE
Fcitx input problem

### ISSUE THREAD

**Issue by Menchen** [kovidgoyal/kitty#403]
kitty seem have a problem with fcitx, when I type with fcitx and delete with backspace, it also delete word in kitty, and this make me near impossible to use vim with fcitx, a gif may explain better, konsole seem work without problem.

![konsole and kitty](https://user-images.githubusercontent.com/6707265/37560738-220caf20-2a3e-11e8-84da-da739ccd0305.gif)

* fcitx-googlepinyin as input method engine
* Archlinux 
* using least kitty-git

**Comment by kovidgoyal** [comment]
see #171

**Comment by cycoe** [comment]
hey bro, how to enable fcitx support in kitty?

**Comment by kovidgoyal** [comment]
Write the code for it, or use ibus instead.

**Comment by hyiltiz** [comment]
While fcitx support is not planned, it seems a PR for it is welcome. Maybe consider giving it a few appropriate tags, and keep it open?

**Comment by kovidgoyal** [comment]
I dont keep bugs open for things that I dont think are a particularly good idea. I will review and possibly merge the code for fcitx support if someone were to implement it. But frankly supporting multiple input methods is not something I think is worth it.

**Comment by qwIvan** [comment]
`GLFW_IM_MODULE=ibus` works for me with fcitx5.

**Comment by nouh** [comment]
> `GLFW_IM_MODULE=ibus` works for me with fcitx5.

it really works
