### ISSUE TITLE
Newline added to fish prompt

### ISSUE THREAD

**Issue by OmegaLambda1998** [kovidgoyal/kitty#4032]
**Describe the bug**
When using fish with anything other than the default prompt, a newline is added between the prompt and the cursor.
Initially submitted as an issue with fish: https://github.com/fish-shell/fish-shell/issues/8297 (where a lot more information can be found), who believe kitty is adding this newline

**To Reproduce**
1. Install fish
2. Change `fish_prompt`
3. Cursor is now offset from prompt

**Screenshots**
![1631703062_grim](https://user-images.githubusercontent.com/20032885/133420569-867da7c7-c070-44de-817c-4b817f9c18c3.png)

The expected behaviour is:
```
/home/patricka
>newline
```

**Environment details**
```
kitty 0.23.1 (5916bbd5b3) created by Kovid Goyal
Linux Archbox 5.14.3-arch1-1 #1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/patricka/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0
bold_font               FiraCode Nerd Font Mono Bold
clipboard_control       ('write-clipboard', 'write-primary')
cursor_blink_interval   0.0
cursor_text_color       None
enable_audio_bell       False
font_family             FiraCode Nerd Font Mono
update_check_interval   24.0
Changed mouse actions:
	 b1 -2 ungrabbed KeyAction('mouse_click_url_or_select')
	 shift+b1 -2 ungrabbed KeyAction('mouse_click_url_or_select')
	 shift+b1 -2 grabbed KeyAction('mouse_click_url_or_select')
	 shift+ctrl+b1 repeat ungrabbed KeyAction('mouse_click_url')
	 shift+ctrl+b1 repeat grabbed KeyAction('mouse_click_url')
Added shortcuts:
	shift+super+w KeyAction('close_os_window')
Colors:
	active_tab_background   #f8f8f2   
	active_tab_foreground   #282a36   
	background              #282a36   
	color0                  #21222c   
	color1                  #ff5555   
	color10                 #69ff94   
	color11                 #ffffa5   
	color12                 #d6acff   
	color13                 #ff92df   
	color14                 #a4ffff   
	color2                  #50fa7b   
	color3                  #f1fa8c   
	color4                  #bd93f9   
	color5                  #ff79c6   
	color6                  #8be9fd   
	color7                  #f8f8f2   
	color8                  #6272a4   
	color9                  #ff6e6e   
	cursor                  #f8f8f2   
	foreground              #f8f8f2   
	inactive_tab_background #6272a4   
	inactive_tab_foreground #282a36   
	mark1_background        #ff5555   
	mark1_foreground        #282a36   
	selection_background    #44475a   
	selection_foreground    #ffffff   
	url_color               #8be9fd   

```

**Additional context**
Cursor still offset with `kitty --config NONE`
![1631703363_grim](https://user-images.githubusercontent.com/20032885/133421367-1032ba15-5172-4eb4-92fd-608237ad765c.png)

**Comment by kovidgoyal** [comment]
kitty doesnt draw prompts. The shell does. From your screen shot you are running

```
echo ">"
```

what you should be running is

```
echo -n "> "
```

or really

```
printf "$PWD\n> "
```

**Comment by OmegaLambda1998** [comment]
Sorry to open this again, however this doesn't solve my issue.
If you look at the original issue: https://github.com/fish-shell/fish-shell/issues/8297
You'll see that this issue occurs for every prompt (including well established ones like [pure](https://github.com/pure-fish/pure) and [tide](https://github.com/IlanCosman/tide)) not just my mwe one. The people over at fish referred me to kitty being the cause of the issue.

**Comment by kovidgoyal** [comment]
As I said, kitty does not draw prompts, the shell does. There is nothing kitty can do about what the shell chooses to draw. And running

kitty --config NONE -o shell=fish

with the fish_prompt set to ```printf "$PWD\n> "``` works fine for me.

**Comment by kovidgoyal** [comment]
And looking at your issue this is with regards to shell integration? which is not released yet?

**Comment by OmegaLambda1998** [comment]
I'm not sure, I just installed kitty and fish today and am just trying to get them to play nice together.

So what would the next step be? If it is shell integration, how do I remove that from my kitty install?

**Comment by kovidgoyal** [comment]
shell integration in kitty is not released. So where did you get kitty from? In any case if you want to disable it, use shell_integration disabled in kitty.conf.

**Comment by OmegaLambda1998** [comment]
I installed `kitty-git` from the arch user repository (https://aur.archlinux.org/packages/kitty-git/). And yes `shell_integration disabled` fixed the issue. Thanks for your patience!

**Comment by kovidgoyal** [comment]
And this will fix it even with shell integration: https://github.com/kovidgoyal/kitty/commit/a0739369974f5f5edf0305d65b1e4b20cc26f8a8

for future reference, please mention the version of kitty you are using.

**Comment by faho** [comment]
Let me explain the problem, @kovidgoyal:

Fish executes fish_prompt, and then trims a trailing newline from its output. This is so simple prompts like

```fish
function fish_prompt
    echo $PWD '>'
end
```

work without us having to constantly explain to use `echo -n`.

However, because kitty adds more output after the actual prompt output, the newline now isn't trailing anymore, so fish won't remove it. Ideally, you'd be trimming the trailing newlines yourself, or we'd find some other way to add your prompt marker.

>And this will fix it even with shell integration: a073936

It won't. It'll break every newline prompt, because fish splits command substitutions on newlines.

**Comment by OmegaLambda1998** [comment]
My apologies, is `kitty 0.23.1 (5916bbd5b3) created by Kovid Goyal` from the output of `ctrl+shift+f6` not the kitty version?

**Comment by kovidgoyal** [comment]
On Wed, Sep 15, 2021 at 04:30:14AM -0700, Fabian Homborg wrote:
> Let me explain the problem, @kovidgoyal:
> 
> Fish executes fish_prompt, and then trims a trailing newline from its output. This is so simple prompts like
> 
> ```fish
> function fish_prompt
>     echo $PWD '>'
> end
> ```
> 
> work without us having to constantly explain to use `echo -n`.

Yes, I understood the issue.

> 
> However, because kitty adds more output after the actual prompt output, the newline now isn't trailing anymore, so fish won't remove it. Ideally, you'd be trimming the trailing newlines yourself, or we'd find some other way to add your prompt marker.
> 
> >And this will fix it even with shell integration: a073936
> 
> It won't. It'll break every newline prompt, because fish splits command substitutions on newlines.

I dont use fish, so I'm not familiar with its stdlib, however simply
doing (_ksi_original_fish_prompt | string collect)

instead of (_ksi_original_fish_prompt) will fix that, I think. Or are
there any other footguns I'm missing?

**Comment by kovidgoyal** [comment]
And @faho since you are around, any interest in integrating shell integration natively in fish. It will work with more than just kitty, at least iterm2 and wezterm also support it.

**Comment by faho** [comment]
>Or are
there any other footguns I'm missing?

`string collect` will trim *any number of* trailing newlines, so if you *want* to have a prompt that leaves you on a newline, e.g.

```fish
function fish_prompt
   echo $PWD '>'
   echo
end
```

it won't work (this should possibly be changed, but at the moment that's the way it is).

Really, I think writing the last line out separately is the best choice here.


>And @faho since you are around, any interest in integrating shell integration natively in fish. It will work with more than just kitty, at least iterm2 and wezterm also support it.

I'm okay with adding a *lot* of stuff, by default. However, I've explained my conditions before:

- Either it has to *not break* everywhere (including awful things like emacs' ansi-term), or
- where it works has to be trivially detectable (e.g. TERM is xterm-kitty, ITERM_PROFILE is set, whatever wezterm does)
- The sequence should ideally have the same form everywhere, no `;` in that term and `:` in that other one

If there's gonna be a bunch of these sequences, there could even just be a $NUTERM variable that y'all could set, and it would guarantee to fish that these things would be safe to send.

I've really lost my appetite for complicated terminal detection and bug reports for poorly behaving terminals, so if we're gonna add something I want it to not cause more problems.

If that's given, sure, send the docs or (better) a patch.

**Comment by faho** [comment]
In case you're only reading email: I've edited in how to write it out in my comment before.

**Comment by kovidgoyal** [comment]
> My apologies, is `kitty 0.23.1 (5916bbd5b3) created by Kovid Goyal` from the output of `ctrl+shift+f6` not the kitty version?

It is but I havent memorized commit hashes, so when you are running from master its best to mention that fact or I wont notice.

**Comment by kovidgoyal** [comment]
On Wed, Sep 15, 2021 at 06:01:52AM -0700, Fabian Homborg wrote:
> In case you're only reading email: I've edited in how to write it out in my comment before. 

Thanks, that helped. But in my testing I discovered another bit of
weirdness. A double trailing newline seems to insert a number of blanks
on the last line, corresponding to the number of printable characters on the
previous line. A test case:

```fish
function fish_prompt
    echo one
    echo -e "\e33m>>>>"
    echo
end
```

Gives a prompt:

```
one
>>>>
    <cursor>
```

Notice that fish seems to insert a number of spaces equal to the number
of characters in the previous line at the start of the last line. And
this is number of printable characters, not string length. Is this
intended behavior? 

If I use my wrapper function, this doesn't happen anymore:

```fish
    function _ksi_end_prompt
        set --local cmd_status "$status"
        set --local op (_ksi_original_fish_prompt) 
        if set -q op[2]
            printf '%s\n' $op[1..-2] 
        end
        printf '%s' $op[-1] 
        set --global _ksi_prompt_state "prompt_end"
        _ksi_mark "B"
        return "$cmd_status" # preserve the value of $status
    end
```

gives

```
one
>>>>
<cursor>
```

I dont understand why. Any hints?

**Comment by kovidgoyal** [comment]
And using

```fish
    function fish_prompt
        echo one
        echo -e "\e[33mXXXX"
        echo
        echo
    end
```

gives a prompt of:

```
one
XXXX

<cursor>
```

No inserted spaces on the last line. So to summarise, with two trailing newlines, one gets inserted spaces on the last line, with three or more one does not.

**Comment by faho** [comment]
Ah, okay. I can reproduce that, even without an escape. It seems we're mistakenly starting at the last line's width instead of the beginning of the line in that case.

It's a fish bug that I don't think you need to concern yourself with.

**Comment by kovidgoyal** [comment]
OK then thanks for your help I have committed the pure printf based
solution: https://github.com/kovidgoyal/kitty/commit/f277cbf3f3fe03cecaec7e619bf8d8970d945dfa
