### ISSUE TITLE
sudo infocmp xterm-kitty: couldn't open terminfo file xterm-kitty. 

### ISSUE THREAD

**Issue by psdon** [kovidgoyal/kitty#4034]
**Describe the bug**
xterm-kitty is not detected by `infocmp` if I run it on `sudo`

**To Reproduce**
1. `sudo infocmp xterm-kitty`

**Screenshots**
Working without sudo:
![2021-09-16_05-11](https://user-images.githubusercontent.com/31410348/133510109-fc40e39d-a978-4042-8913-4cdcb43971e5.png)

With sudo
![2021-09-16_05-12](https://user-images.githubusercontent.com/31410348/133510183-84af3f91-01d9-4f3f-a6bb-7fdb46e79bd3.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux arch 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo
