### ISSUE TITLE
kitty @ launch doesn't accept arbitrary shell command

### ISSUE THREAD

**Issue by nikitabobko** [kovidgoyal/kitty#4035]
**To Reproduce**
1. run `kitty "sleep 1"`
EXP: run new kitty window which shows for 1 second
ACT: `Failed to launch child: sleep 1`
Note that at the same time `kitty sleep 1` works as expected
Not allowing to run shell command with quotes is bad because I can't use shell syntax like `kitty "sleep 1 && echo foo"`

Same for `kitty @ launch "sleep 1 && echo foo"`
Same for `launch` used in session file

**Comment by kovidgoyal** [comment]
yes you can

kitty sh -c "sleep 1 && echo whatever"
