### ISSUE TITLE
Make it possible to include window borders even when only one window is visible

### ISSUE THREAD

**Issue by andrey-ib** [kovidgoyal/kitty#4037]
First, thanks for kitty! It's a great terminal emulator.

I use kitty with a bare minimum of OS chrome. Usually this is great. However, if I have several OS windows open, and they don't have multiple kitty windows in them, and the OS windows are overlaid, it becomes hard to see the bounds of the OS windows. For example, compare these two screenshots, which have the same OS windows:

![image](https://user-images.githubusercontent.com/60625003/133543534-94476bc9-7269-4fa8-bcc3-9fbe7798ae6f.png)

![image](https://user-images.githubusercontent.com/60625003/133543575-2aca44b7-2e56-4e50-9e46-dcf619aabc29.png)

This is the relevant part of my kitty config:

```
window_margin_width 1
single_window_margin_width 1
window_padding_width 2
window_border_width 1
```

It would be great if there were a config option like `single_window_always_include_border`. The usability feature is, I would like there to always be a visible border around my OS window -- when I have multiple kitty windows open in a single OS window, I get this from the kitty window borders.

**Comment by andrey-ib** [comment]
Another screenshot:

![image](https://user-images.githubusercontent.com/60625003/133543816-59fa65ed-295c-4c7d-8cf1-62d729903cbd.png)

**Comment by kovidgoyal** [comment]
Not something I care to spend time on. If you want OS window borders,
the logical place to draw them is in the window manager, not individual
applications. I suggest using a window manager that allows you to
customize the borders for classes of windows.

Using kitty window borders for this is not an appropriate solution as
they only work as OS window borders when there is a single kitty window
displayed, otherwise they will not be a an actual os window border.

**Comment by linusrachlis** [comment]
Hi, I think I realized why on MacOS one feels this need. Even though most other apps don't have much of a border, there's a convention of windows having drop shadows, and this provides a subtle but useful cue as to the border. For some reason this doesn't render for Kitty windows.

Comparison of Firefox overlapping Kitty ...
![Screen Shot 2021-11-10 at 3 31 39 PM](https://user-images.githubusercontent.com/1476078/141189857-ea929b0e-a62e-4dc2-a906-d6bfe2ddda2a.png)

vs. the other way around...

![Screen Shot 2021-11-10 at 3 31 55 PM](https://user-images.githubusercontent.com/1476078/141189874-c72c8127-0d43-4c00-a3c7-97f0ef8a982c.png)

**Comment by Luflosi** [comment]
I presume you set `hide_window_decorations` to `yes`. Try setting it to `titlebar-only` instead. Maybe this will work for your use-case. See https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.hide_window_decorations for more info.

**Comment by linusrachlis** [comment]
Thanks for your message Luflosi. I didn't have it set at all (it was in the default commented state). I tried setting to `no` and also `titlebar-only`, and quitting and restarting Kitty, but didn't notice any drop shadow show up.

**Comment by kovidgoyal** [comment]
On macOS kitty windows with default config definitely have shadows.

**Comment by linusrachlis** [comment]
My apologies. I compared to default config and narrowed it down to `dynamic_background_opacity`, which I didn't mean to have turned on in the first place. Turning this off brought back the drop shadow.

**Comment by liebkne** [comment]
When `background_opacity` is set, shadows are still missing.

**Comment by devidw** [comment]
one way to get borders w/o a wm on macos is https://github.com/FelixKratz/JankyBorders

**Comment by Kamyil** [comment]
> one way to get borders w/o a wm on macos is [FelixKratz/JankyBorders](https://github.com/FelixKratz/JankyBorders)

Yeah, I used exactly this trick to render somewhat similar to native macOS borders
`borders active_color=0xff666565 inactive_color=0xff555353 width=1.0`

<img width="2378" height="1278" alt="Image" src="https://github.com/user-attachments/assets/81d43764-6c97-4307-8ecb-90d9a038262c" />

It's not perfect, but it's more than enough for me. Thanks @devidw !
