### ISSUE TITLE
Jpeg Xl (.jxl) support for icat

### ISSUE THREAD

**Issue by hellosway** [kovidgoyal/kitty#4039]
I have a lot of pictures archived as JPEG xl files. I would like to icat it in kitty, but kitty does not support this. JPEG xl is new next generation image format, that con losslessly transcode JPEG, and has smaller file sizes.

Add support for JPEG xl images to the icat kitten

Converting to a more supported format would increase file sizes, cause re encoding loss, and might not be possible.

libjxl is the reference implementation, you can just use it, even though there is no official standard yet.

**Comment by kovidgoyal** [comment]
Image format support in kitty comes from ImageMagick. So get jxl support
added there and kitty will pick it up automatically.

**Comment by hellosway** [comment]
Does Kitty bundle ImageMagick, on the website jpeg xl is on the supported formats list.

**Comment by trygveaa** [comment]
No, kitty does not bundle ImageMagick. JPEG XL support is not enabled in ImageMagick by default, you need to compile it with the `--with-jxl` option. Additionally, currently there is an issue where it silently disables JPEG XL unless you disable static builds (`--enable-static=no`), see https://github.com/ImageMagick/ImageMagick/issues/4029.

If you build and install ImageMagick with JPEG XL support, it will work with icat. You can check if your ImageMagick installation supports JPEG XL by running `identify <path to a jpeg xl file>`.

**Comment by hellosway** [comment]
Homebrew imagemagick doesnt enable jpeg xl, compiling with it makes it display, I will submit a pr to the homebrew formulae soon.
