### ISSUE TITLE
Nerd fonts are expanding the full line height

### ISSUE THREAD

**Issue by creativecreature** [kovidgoyal/kitty#4040]
Hi,

I've been trying to make this work for a while now, but I can't solve an issue I'm having with some nerdfont symbols. Whenever I add a space to some of these glyphs they seem to expand the entire line:

https://user-images.githubusercontent.com/12787673/133761598-a8172232-c50a-4a44-ac62-cacea82f8657.mp4

Also, if I increase the `adjust_line_height` setting they seem to take up the entire line:
![kitty-line-height](https://user-images.githubusercontent.com/12787673/133761524-6c4186cf-daef-4a18-bd0f-a2dae3c2d87f.png)

This does not happen in Alacritty if I add spaces behind it using the same font:
![alacritty-space](https://user-images.githubusercontent.com/12787673/133761658-7f63cb3c-77c4-4d67-b1cc-702f0fc191ee.png)

Also with increased line height in alacritty it does not take up the entire line height:
![alacritty-no-expand](https://user-images.githubusercontent.com/12787673/133761751-678381cd-d842-4f47-9110-3cd0cb18b46c.png)

I'm on Ubuntu 21 and this happens to me with a minimal config like this one:
```
# Reload config file with
map ctrl+shift+enter load_config_file

# Font family and line height
font_family      SF Mono
adjust_line_height  15
adjust_column_width 0

disable_ligatures never

# Font size (in pts)
font_size        8.5
```

To debug this I'm running kitty with the `--debug-font-fallback` flag. When it hits the light bulb symbol which has the u+f400 unicode it fallbacks to "DroidSansMono Nerd Font` which I  have installed using these instructions from the nerdfont repo: https://github.com/ryanoasis/nerd-fonts#linux

This is the output from running kitty with the --debug-font-fallback:
```
❯ kitty --debug-font-fallback
[260 10:21:30.229155] Preloaded font faces:
[260 10:21:30.229187] normal face: /home/c.conner/.local/share/fonts/SFMono-Regular.otf:0
[260 10:21:30.229199] bold face: /home/c.conner/.local/share/fonts/SFMono-Bold.otf:0
[260 10:21:30.229208] italic face: /home/c.conner/.local/share/fonts/SFMono-RegularItalic.otf:0
[260 10:21:30.229218] bi face: /home/c.conner/.local/share/fonts/SFMono-BoldItalic.otf:0
U+f400 Face(family=DroidSansMono Nerd Font, style=Book, ps_name=DroidSansMonoNerdFontComplete-, path=/home/c.conner/.local/share/fonts/Droid Sans Mono for Powerline Nerd Font Complete.otf, index=0, is_scalable=True, has_color=False, ascender=1901, descender=-483, height=2384, underline_position=-205, underline_thickness=102, strikethrough_position=498, strikethrough_thickness=102)
```

**Comment by kovidgoyal** [comment]
That is by design. Those symbols are square so if there is space for
them, they will be redered in two cells. https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty

And no, they dont change the line height. They just look larger because
when they become wider they also become taller (within the bounds of the
line height).

**Comment by creativecreature** [comment]
Thanks for your reply. I noticed that this only occurs on Linux. My colleague who is using a Mac did not face the same problem as me. If he changed the `adjust_line_height` to 20 the unicode symbols did not expand to fill the entire line the same way it does in my video.

Therefore, I compared the output of the font fallback when we encounter those unicode characters. On Linux, it loads the font with `is_scalable=True`, on Mac it doesn't. 

To get that same behaviour on Linux you can create a custom font configuration and set `scalable` to `false`. You can then assign that font for the unicode characters inside your `kitty.conf` file. That way the unicode characters will stay the same height as the text, rather than growing to the height of the line
