### ISSUE TITLE
The 'clear' command returns a message 'xterm-kitty': unknown terminal type rather than clearing the screen

### ISSUE THREAD

**Issue by mesa123123** [kovidgoyal/kitty#4043]
**Describe the bug**

**To Reproduce**
1. Launch Kitty
2. Type 'clear'
3. Push <CR>

**Screenshots**
![image](https://user-images.githubusercontent.com/22901019/133927301-6d724cf1-7cbb-48c2-83fc-51dafbbd139c.png)

**Environment details**

**Additional context**
Running kitty --config NONE has the same effect

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by mesa123123** [comment]
I'm not trying to ssh into anywhere...
Though I believe this actually has nothing to do with kitty itself but my system so please close
