### ISSUE TITLE
Fill inner border with background color of outermost cells

### ISSUE THREAD

**Issue by smeikx** [kovidgoyal/kitty#4046]
**Is your feature request related to a problem? Please describe.**
No, it would just make things prettier.

**Describe the solution you'd like**
When the character grid and the window size do not exactly match, the gap between content and window border is currently being painted in the `background` color as specified in the config. 
Instead the gap could be painted in the same background color as the nearest cell.

**Additional context**
In the screenshot of the tiny window kitty’s background is set to white while the running program has a dark color scheme, to illustrate what I mean.
The white gap between the dark border and the dark content of the window could instead take the background color of the outermost cell (in this example: green near the green bar at the bottom, not so dark blue next to the other bar above the green one, dark blue everywhere else).
![20210921_18h04m04s_grim](https://user-images.githubusercontent.com/6908653/134206604-d2c78b8d-dd6c-4cf0-8e6d-4c74e3f6aaea.png)

Is this doable in an efficient way?

**Comment by kovidgoyal** [comment]
no, it isnt. Instead I suggest you add the following to your vimrc

```
	hi Normal NONE
        let &t_ti = &t_ti . "\033]10;" . s:fg . "\007\033]11;" . s:bg . "\007"
        let &t_te = &t_te . "\033]110\007\033]111\007"
```

that will change the background color of kitty and have vim not set a background color which is also more efficient otherwise. Replace s:fg and s:bg above with whatever colors you want to use.

**Comment by smeikx** [comment]
Thank you for the snippet! 
For anyone else reading this: nvim does not support `t_ti` and `t_te` or any other of the `t_xx` options.

**Comment by kovidgoyal** [comment]
For nvim you use a wrapper script that changes the colors using printf
first then runs nvim and then restores the colors when nvim quits.

Though really both vim and nvim should just gain native support for
this. It's a big efficiency win, since the normal highlight now requires
no color changes.

**Comment by smeikx** [comment]
Sorry for bumping this again. Just wanted to let you know that I have written a small plugin for neovim that takes care of matching colors between kitty and neovim. Maybe it is somewhat interesting to you. It is far from perfect, but it is a start.

https://github.com/smeikx/kitty-color-control
