### ISSUE TITLE
Disable menu bar in full screen like Alacritty

### ISSUE THREAD

**Issue by cole-wilson** [kovidgoyal/kitty#4047]
**Describe the solution you'd like**
On MacOS, on Alacritty (which I don't really use, just noticed this once), moving the mouse to the top of the screen does not show the menu bar. Showing the menu bar is the default MacOS behavior for all applications, but somehow Alacritty disables this by default.

I would like to be have kitty do this as well, so moving the mouse to the top of the screen does NOT show the menu bar.

**Examples**
Here are two videos, one is kitty, and another is Alacritty.

https://user-images.githubusercontent.com/49500253/134264080-271d8f78-bdc1-44a1-b439-2c98f7999f89.mov

https://user-images.githubusercontent.com/49500253/134264042-c8261581-e047-49c2-9a8a-415d0d1197ad.mov

**Comment by kovidgoyal** [comment]
A PR adding an option for this feature is welcome.
