### ISSUE TITLE
Last newline of the screen's text is not captured by get-text

### ISSUE THREAD

**Issue by resolritter** [kovidgoyal/kitty#4049]
**Describe the bug**

I'm sending a request (in my case `{"cmd":"get-text","version":my_version,"payload":{"match":"id:2", "extent":"all"}}`) through remote control to [get-text](https://github.com/kovidgoyal/kitty/blob/master/kitty/rc/get_text.py) and noticing that trailing newlines are not included in the response, if there's one.

Suppose you have a screen with the following:

```
>

```

i.e. a single newline after the prompt as the last character. In that scenario the empty newline is not included in the response.

If you have multiple trailing newlines:

```
>


```

Then only the last one is omitted and the other ones are included.

**To Reproduce**

1. Create an empty newline at the end of a screen using e.g. `echo -e '\n'`
2. Send a remote request to get the output of said screen
3. The trailing newline will be missing from the response

**Environment details**

- kitty 0.20.3
- Linux 5.14.2-arch1-2 x86_64
- Arch Linux

**Comment by resolritter** [comment]
I found out this is happening because line_as_unicode

https://github.com/kovidgoyal/kitty/blob/43c04df98ad6487a9b2cebeeb06cdfac64ad8814/kitty/line.c#L258

is returning an unexpected (I think) value for the last line when it is a newline.

By trial-and-error I found that putting the following code in `as_text_generic` works for my scenario but I don't know if it's proper and can't reason about it.

```
    if (lines) {
        Line *last_line = get_line(container, lines - 1);
        t = line_as_unicode(last_line, false);
        if (t == NULL) goto end;
        if (PyUnicode_GetLength(t) == 0) {
            ret = PyObject_CallFunctionObjArgs(callback, nl, NULL);
            if (ret == NULL) goto end;
            Py_CLEAR(ret);
        }
    }
```

**Comment by kovidgoyal** [comment]
I'm afraid I dont follow. as_text_generic() returns a newline *for every* non continued line on the screen. Indeed in your test case you will get a whole bunch of trialing newlines, as is easily demonstrated by the one liner:

```
kitty --config=NONE -o allow_remote_control=y sh -c "echo >; kitty @ get-text --extent=all | python -c 'import sys; print(repr(sys.stdin.read()))'; cat"
```
will print out
```
moo
'moo\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
```

here the number of trailing \n is equal to the number of lines on the screen.

**Comment by resolritter** [comment]
It works as intended when I use a script similar to yours so it must be something related to my setup.

I'll try to isolate the issue and find clean reproduction steps.

Thank you for the time.
