### ISSUE TITLE
Feature: Independent font sizes between windows and splits

### ISSUE THREAD

**Issue by ddrscott** [kovidgoyal/kitty#405]
When changing fonts sizes with `increase_font_size` or `decrease_font_size` all windows change at the same time.

It would be wonderful if Kitty could support independent font sizes.

**Current behavior in Kitty:**
![kitty_same_font_size](https://user-images.githubusercontent.com/1975119/37604049-1d411078-2b5e-11e8-8cd7-a5c0ffffb0aa.gif)

**Desired behavior in iTerm2:**
![kitty_independent_font_size](https://user-images.githubusercontent.com/1975119/37604082-2bf0d0a4-2b5e-11e8-8b95-3209becfe302.gif)

**Comment by kovidgoyal** [comment]
This is by design. By sharing the font size across all windows, kitty can use a single glyph cache on the GPU, thereby saving VRAM. You can, of course use two kitty instances to have two terminals with different font sizes.

**Comment by ddrscott** [comment]
Ah, that makes sense. TIme to get https://github.com/koekeishiya/kwm setup on the Mac.

**Comment by ddrscott** [comment]
Ghostty didn't work out of the box as advertised. I need to post an issue over there.
