### ISSUE TITLE
Yet another issue about small sized special symbols.

### ISSUE THREAD

**Issue by BayLee4** [kovidgoyal/kitty#4050]
**Describe the bug**

Yes I read https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty, and no the workaround to use a space after the special symbol does NOT work : ```The exception is if these characters are followed by a space or empty cell in which case kitty makes use of the extra cell to render them in two cells.```

Quoting from #3072 :

You can see a lot of spaces before and after :
![2020-11-03T14:29:47,772435206+01:00](https://user-images.githubusercontent.com/14223657/97991018-17dae280-1de1-11eb-89ce-23d42b0f8194.png)
@kovidgoyal ping

_Originally posted by @eoli3n in https://github.com/kovidgoyal/kitty/issues/3072#issuecomment-721116163_

**Expected behavior**

Icon to be the good size

**Comment by kovidgoyal** [comment]
It works fine

**Comment by BayLee4** [comment]
@kovidgoyal At this point it's just a plain lie.

**Comment by kovidgoyal** [comment]
Nice, thanks.
