### ISSUE TITLE
Document how to handle switching users with `kitty +kitten ssh`

### ISSUE THREAD

**Issue by tmccombs** [kovidgoyal/kitty#4051]
**Describe the bug**
`kitty +kitty ssh` doesn't work if you run switch to a different user after connecting with ssh.

**To Reproduce**
1. ssh using `kitty +kitty ssh`
2. change users using for example `sudo su`
3. TERM is is still xterm-kitty, but the different user (ex root) doesn't know where to find the terminfo file, so many things are broken
4. 

**Environment details**
kitty 0.15.0 created by Kovid Goyal
Linux thayne.dev.lucidvpc.com 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64
Ubuntu 20.04.3 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Running under: X11

Config options different from defaults:
```

**Additional context**
I'm not really sure how this could be fixed until https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/8 is standardized and widely deployed.  But maybe https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer should call out this limitation. And sadly I think if I don't want to have to manually copy files around every time I use sudo (and clean them up when I'm done) I'll need to use a TERM of xterm-256color.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo
