### ISSUE TITLE
Arabic letters order is correct but word order is left to right

### ISSUE THREAD

**Issue by thenoobtester** [kovidgoyal/kitty#4055]
Hi,

I just recently discovered kitty, it's a great terminal and I love it. I have an issue though with Arabic text, it only partially works. Meaning, the words' letters are written correctly (letters are correctly glued right to left) however the sentence is composed left to right. For example "Sky News Arabic" will be written like this:
عربية نيوز سكاي
Instead of this:
سكاي نيوز عربية

Which is funny because if I copy-paste عربية نيوز سكاي (the wrongly ordered sentence) from Kitty to this comment box, then it is pasted in the correct order (I had to manually reverse the order of the words to show the issue) and the other way around if I take the incorrectly ordered text from this box and paste it into kitty it is then reversed and displayed correctly. This means kitty does something where it correctly orders the word letters but not the words.

I hope it's clear :)

1. Copy سكاي نيوز عربية into your terminal and it should display as عربية نيوز سكاي which is incorrect

Screenshots:
![2021-09-23-123451_1920x1080_scrot](https://user-images.githubusercontent.com/18335104/134493517-592836c8-172c-475c-b9f0-3b32403a749c.png)

**Environment details**
```
kitty 0.23.1 (43c04df98a) created by Kovid Goyal
Linux slax 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64

Running under:X11
Frozen: True
Paths:
  kitty: /home/Downloads/bin/kitty
  base dir: /home/Downloads/lib/kitty
  extensions dir: /home/Downloads/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/.config/kitty/kitty.conf

Config options different from defaults:
font_family Hack Nerd Font Mono
font_size   12.0

```

This is all there is is my conf :

font_family Hack Nerd Font Mono
font_size   12.0

Thank you.

**Comment by kovidgoyal** [comment]
dup of #2109

**Comment by thenoobtester** [comment]
Thanks for the reply, I now use BiCon - The Bidirectional Console which can be run inside kitty when I have to work with arabic text for a long time. Thank you again for this great terminal emulator and for providing binaries that run on my old Debian Stretch :+1:
