### ISSUE TITLE
keyboard maestro macro, permission?

### ISSUE THREAD

**Issue by tjallemaal** [kovidgoyal/kitty#4056]
hi, i've been using a macro for opening my `terminal.app` with keyboard maestro (see screenshot below).
so just yesterday i switched to `kitty`.

this is not really a bug but i wouldn't know how to ask this otherwise!

**the problem:**
i changed the app in my macro to "kitty".
in my dock ( i'm on macOS) the kitty app symbol starts jumping. 
but the little black dot which indicates the program running doesn't appear, 
in short: keyboard maestro cannot open kitty but i can see it tries to.

**so my question is:** 
upon installing kitty, did i miss some admin permission or sth like that?
sorry for the wording, i'm not too tech savvy ...
btw i installed kitty via `brew`...

thx in advance

![Screenshot 2021-09-23 at 13 10 25](https://user-images.githubusercontent.com/69585777/134497227-8c277c77-919c-4f14-9d05-71b5dcb8077e.png)

**Comment by Luflosi** [comment]
Does kitty open as expected when you start it from Finder?

**Comment by tjallemaal** [comment]
> Does kitty open as expected when you start it from Finder?

yes,sure.

just KM seems to not have access to it ...?
