### ISSUE TITLE
How to bind shortcuts to Mac ⌘ key?

### ISSUE THREAD

**Issue by ddrscott** [kovidgoyal/kitty#406]
As a Mac user, I'd like to setup shortcuts to common Mac idioms.
- ⌘-equal for `increase_font_size`
- ⌘-minus for `decrease_font_size`
- etc.

**Comment by kovidgoyal** [comment]
Use either super or cmd as the modifier name.

**Comment by ddrscott** [comment]
`super` didn't work, but `cmd` did the trick.
Thanks for the quick response time!

By the way, `cmd` wasn't listed as an option in http://www.glfw.org/docs/latest/group__mods.html

**Comment by kovidgoyal** [comment]
Really? cmd is just an alias for super see line 53 of kitty/config.py

**Comment by ddrscott** [comment]
I just tested again with `super` and it still worked. Not sure what I did wrong the first time.

Thanks get getting back to me on this and the other issues.
