### ISSUE TITLE
Scroll in emoji selection, unicode input

### ISSUE THREAD

**Issue by dusanx** [kovidgoyal/kitty#4064]
In unicode input, search by name (F2), number of emojis that fit the filter can be significant. When that happens all the emojis are displayed but they don't fit the screen, even with significantly reduced font size. For instance, searching for 'arrow' shows list few times larger than the screen, arrow or tab navigation can go trough the entire list but the list itself is cut off by the screen size.

I am aware this is not critical in any form but it would be nice if we could scroll the list to see all the emojis that fit the filter. PgUP/PgDOWN or any other key combination can drive this by scrolling by 3-5-10 lines, anything that moves the list will be good enough. Thank you.

**Comment by kovidgoyal** [comment]
Scrolling through large lists is pretty inefficient, I prefer to narriw
the list by adding more search terms. So this is not worth the effort to
me, but a PR is welcome.
