### ISSUE TITLE
Tab name cannot be changed

### ISSUE THREAD

**Issue by kenan-rhoton** [kovidgoyal/kitty#407]
There is no key-binding I've found that lets you change the tab title of the current tab you're in. This would be extremely useful to me and is the main issue that's stopping me from ditching tmux altogether and just using plain kitty goodness.

I might take a stab at the code myself if needed 🙃

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/kitty/blob/master/remote-control.asciidoc
that procides commands to do many things, including rename tabs.
