### ISSUE TITLE
Can't deselect normally when double clicking and dragging

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#4070]
**Describe the bug**
When using double click and then drag to select something, if you drag to the line below the initial selection, and move up again the line is not deselected. If you double click and drag to the right, then up, then down, the line above is not deselected. It is possible to deselect it, but you have to move back to the initial word and to the opposite side of it, which is not intuitive.

**To Reproduce**
1. Print some lines, e.g. `echo -e '123 456 789\nabc def ghi'`
2. Double click on `456` and keep holding the mouse button down.
3. While holding the button, move to `def`.
4. While still holding the button, move up to `456` again.

At this point, only `456` should be selected, but everything from `456` to `def` is still selected, like it was after step 3.

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux george 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11

Config options different from defaults:

```

**Additional context**
The issue was introduced in commit dbc7e8e85d097a0e3bb1c48911fbab05ef1f9776. I tested this in master too (in addition to v0.23.1) and the bug is still present there.

**Comment by trygveaa** [comment]
Thanks! There is still an issue if you move left before down and up, or right before up and down. I.e.

1. Print some lines, e.g. `echo -e '123 456 789\nabc def ghi'`
2. Double click on `456` and keep holding the mouse button down.
3. Move to `123`.
4. Move down to `abc`.
5. Move up to `123` again.

Now everything from `123` to `abc` is still selected, like after step 4, instead of just `123 456`.

Or

1. Print some lines, e.g. `echo -e '123 456 789\nabc def ghi'`
2. Double click on `def` and keep holding the mouse button down.
3. Move to `ghi`.
4. Move up to `789`.
5. Move down to `ghi` again.

Now everything from `789` to `ghi` is still selected, like after step 4, instead of just `def ghi`.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/7d41aca0e4615c2bab486eb7d80f811aed06ac2a

**Comment by trygveaa** [comment]
Hm, it still doesn't behave as I would expect it to. If you with the same text start with `def`, move to `ghi` and then to `789`, `ghi` will still be selected. While if you start with `def`, move to `456` and then to `789`, `ghi` will not be selected. I don't expect the path you take with the mouse to change what is selected, only the start and end position, and I wouldn't expect `ghi` to be selected in either of these cases (like in other applications).

**Comment by kovidgoyal** [comment]
The behavior is correct to me. I like the path dependence. In any case I
have spent as much time as I care too on this.

**Comment by trygveaa** [comment]
This is different behavior from every other application I've tried, but okay.
