### ISSUE TITLE
Add mouse support to `confirm_os_window_close`

### ISSUE THREAD

**Issue by jack1142** [kovidgoyal/kitty#4071]
**Is your feature request related to a problem? Please describe.**
I have set up `confirm_os_window_close` option to make sure I don't close the terminal accidentally when I have multiple tabs open *but* I usually close windows by clicking the X button in the top right corner with a mouse. This means that whenever I do actually want to close the window, I am required to use the keyboard in order to close the terminal even though I already am using mouse and it would be quicker for me to just click on "Yes" rather than move my another hand over the keyboard and hitting the Y key.

**Describe the solution you'd like**
I think it would be great if this prompt supported clicking on "Yes"/"No" text with a mouse:
![image](https://user-images.githubusercontent.com/6032823/134923864-f1020897-3e2a-41ef-afed-08abb0e8776d.png)

**Describe alternatives you've considered**
Native dialog I guess? It doesn't seem in line with how kitty operates so using the terminal's mouse support seems like a better solution anyway.

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
Given that kitty is targeted at keyboard power users, this is not
something I care to spend time on personally, but patches are most
welcome. Relevant code is in kittens/ask/main.py

**Comment by kovidgoyal** [comment]
Never mind, I had a minute to implement it myself since I was anyway working on mouse support in the kittens.

**Comment by jack1142** [comment]
Awesome! I like the improved mouse support in the Handler class too, it took me a bit to figure out that I need to enable SGR when I was initially *trying* to implement this on my own and the improvements you've done abstract it nicely :)
