### ISSUE TITLE
Neovim statusline is glitched when scrolling buffer with certain emoji characters and Normal highlight group that has background color

### ISSUE THREAD

**Issue by zeertzjq** [kovidgoyal/kitty#4077]
**Describe the bug**
Neovim statusline glitches when scrolling buffer with certain emoji characters and Normal highlight group that has background color.

**To Reproduce**
1. Download <https://raw.githubusercontent.com/ms-jpq/coq_nvim/c71517fe9c7f9f09494f613e69d2531b3d2e1b15/locale/en.yml>
2. Run `kitty --config=/dev/null -e nvim --clean en.yml`
3. Run in Neovim `:hi Normal ctermbg=black guibg=black`, some text in buffer are already glitched:
![Screenshot_20210929_191219](https://user-images.githubusercontent.com/35768171/135258101-0919cfd4-e4bd-4fc2-b918-20a18a908ef5.png)
4. Press `CTRL-L` to refresh, the glitch is cleared:
![Screenshot_20210929_191244](https://user-images.githubusercontent.com/35768171/135258197-71269740-6bb6-4a2c-bfd2-89c2d4303b5f.png)
5. Press `CTRL-E` several times to scroll a emoji into view, the first character on the statusline is glitched:
![Screenshot_20210929_191307](https://user-images.githubusercontent.com/35768171/135258322-23de4683-535d-48f2-bf5d-419ea54d2cc3.png)
6. Press `CTRL-F` to scroll a page, a large part of the statusline is glitched:
![Screenshot_20210929_191332](https://user-images.githubusercontent.com/35768171/135258420-85e8c948-8165-48fd-8a2f-4a53fe6eac33.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux b01001011 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  /dev/null

Config options different from defaults:

```

**Additional context**
Neovim doesn't behave like this in other terminal emulators, so I think this is a kitty bug.

**Comment by kovidgoyal** [comment]
This is not a kitty issue. Report it to neovim. Most likely it will be because neovim is using incorrect widths for those emoji. kitty uses widths based on the latest unicode standard.

**Comment by zeertzjq** [comment]
Oh, I checked `strdisplaywidth()` and it is indeed the case.
