### ISSUE TITLE
Inconsistent font rendering on OS X

### ISSUE THREAD

**Issue by metov** [kovidgoyal/kitty#4079]
It seems like kitty on OS X renders fonts differently from other native Mac programs. I believe there is a long standing, historical difference in font rendering between Macs and non-Macs - I don't really follow all the details, but I gather that this is why text on Macs looks "fatter".

Personally I'm not a huge fan of Macs or how they render text, but unfortunately sometimes I am forced to use them. While kitty appears to render text the way I like even on a Mac, I would prefer if it didn't - because my eyes are used to every other Mac program rendering the text "fat" and it is actually a bit jarring to switch to kitty. Obviously kitty is doing nothing wrong here, in my opinion every other Mac app renders text wrong - but setting aside the question of whether "fat" text or normal text is nicer, having a mix of both seems worse than either.

Is there a setting in kitty that makes it render "fat" text like the rest of Mac programs? Or is there an inherent limitation here? I saw issue #214 which seems possibly related, but not quite the same thing.

Here is a screenshot:

![Screen Shot 2021-09-29 at 3 27 16 PM](https://user-images.githubusercontent.com/51468504/135357205-14112547-b318-432b-84ca-8779fd938c65.png)

Kitty is on the right, iterm2 on the left. Both are set to 18pt font. `kitty --config None` looks identical, except for the text being smaller.

**Comment by metov** [comment]
Small mistake - the font is actually 17pt for kitty and 18pt for iterm2 in the screenshot, which is why the text doesn't line up.

**Comment by kovidgoyal** [comment]
If you want the fonts thicker use the setting for it in kitty.conf

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_thicken_font

**Comment by metov** [comment]
That was indeed the option I was looking for, thank you! Sorry for not checking the docs more carefully.
