### ISSUE TITLE
mixed dpi support for multiple windows

### ISSUE THREAD

**Issue by thomasjachmann** [kovidgoyal/kitty#408]
When you create multiple windows using `new_os_window` and move one of them to a screen with a different dpi value, that window and all others are resized to accomodate the new dpi. The others, non-moved windows should not change their appearance.

I know you don't have a way to test this, so could you give me a pointer to where in the code to look for a solution for this? Or is the shared setting to deeply ingrained to be changed easily?

**Comment by kovidgoyal** [comment]
I doubt it will be an easy change. DPI and font size are currently global, you'd have to make them per-window and also deal with the fact the glyph cache is global (all windows share the same on GPU glyph cache to mimize VRAM consumption). Different DPI will require differently sized glyphs (in pixels). 

In thoeory you could probably do this, but I doubt it's practical.

**Comment by thomasjachmann** [comment]
Well, not having the ability to have two windows on two different screens each with their correct scaling is rather impractical as well. ;) Is there some workaround? This is a serious issue for multi monitor/multi dpi use that shouldn't be dismissed so easily.

**Comment by kovidgoyal** [comment]
Simply use two kitty instances.

**Comment by thomasjachmann** [comment]
OK, a workaround. I don't know for other OSes but on macOS, that feels very non-os-like, though You usually have one app instance with multiple windows. You can switch between windows of an app with a standard shortcut. You only have one app icon in the app selector (Cmd-Tab), simply because you only have one instance. And I think there's no easy way to map a standard shortcut (Cmd-N) to create a new window.

**Comment by kovidgoyal** [comment]
Sure, but then, that's the cost of using such an inflexible OS. I for one think the amount of effort to implement this is not worth the use case. If you feel differently, patches are welcome. Personally, if I was stuck on macOS, I'd just ditch its default desktop shell and switch to using a tiling window manager, like chunkWM, at least as long as Apple continues to allow people to switch out the desktop shell, which going by their past history is not going to be much longer.

**Comment by kovidgoyal** [comment]
FYI this should now work automatically thanks to the recent implementation of support for different font sizes on different top level windows
