### ISSUE TITLE
Local git repository branch indicator on the right side of the screen moves in-wards when deleting characters inside of quotation marks

### ISSUE THREAD

**Issue by mdeslippe** [kovidgoyal/kitty#4082]
**Describe the bug**
Whenever I am working in a local repository, if I type in quotation marks and erase characters inside the quotation marks, it causes the git branch indicator on the right side of the screen to move inwards along with it. However, this issue does not happen when I am not typing in quotation marks.

**To Reproduce**
1. cd into a local git repository.
2. Type characters inside quotation marks.
3. Delete characters inside quotation marks.
4. See error.

**Screenshots**
![](https://i.imgur.com/aGSvp5j.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux linux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64
Arch Linux \r (\l)
Running under:X11
Loaded config files:
  /home/myles/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.8
bold_font          FreeSans Bold
bold_italic_font   FreeSans Bold Oblique
font_family        FreeSans Regular
font_size          12.0
italic_font        FreeSans Oblique
```

**Additional context**
This error is reproducible with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
This will be a bug in your shell. The shell draws the prompt not the
terminal emulator.
