### ISSUE TITLE
Timeout for mouse action

### ISSUE THREAD

**Issue by rightaway** [kovidgoyal/kitty#4083]
When I click on several links very fast to open them all and then immediately switch away from kitty, sometimes only the last of the links opens in the browser and sometimes none of them open. Is there a timeout that can be disabled so that links get opened as soon as they are clicked and even if you switch away from kitty? For links to open reliably I have to click each one and wait up to a second for all them to open.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.click_interval

and hold ctrl+shift and click if you dont want any interval at all

**Comment by rightaway** [comment]
I'm trying to disable the interval because I don't have any other mouse actions that use double or triple click. But when I right click the links don't open at all. Is this the right way?

```
click_interval 0
mouse_map left click ungrabbed no-op
mouse_map right click ungrabbed mouse_click_url
```

**Comment by kovidgoyal** [comment]
You want 

mouse_map right press ungrabbed mouse_click_url
mouse_map right release ungrabbed discard_event

**Comment by rightaway** [comment]
It works most of the time but in some applications like vim nothing happens when I right click. Is there something else I need to do to make it work?
