### ISSUE TITLE
Why no PPA/deb pkgs for easily updating to the latest version on Ubuntu LTS?

### ISSUE THREAD

**Issue by agrawalsourav98** [kovidgoyal/kitty#4088]
**Is your feature request related to a problem? Please describe.**
I currently use Ubuntu 20.04 LTS and I am on kitty 0.15. I would love to use the latest version of kitty with the convenience of apt

**Describe the solution you'd like**
A ppa or deb repo for apt would likely solve the issue

**Describe alternatives you've considered**
Currently, I believe there is the pre-build binary option

**Additional context**
If any extra effort is required, I am ready to help regarding that!

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in maintaining distro specific packages.
