### ISSUE TITLE
Color options for `tab_activity_symbol` and `tab_separator`

### ISSUE THREAD

**Issue by kidonng** [kovidgoyal/kitty#4089]
**Is your feature request related to a problem? Please describe.**

Currently the color for `tab_activity_symbol` is hard-coded as red:

https://github.com/kovidgoyal/kitty/blob/2080b3d7fa72fdbe55b393c552fcde1ad2218686/kitty/tab_bar.py#L421

This may be fine for most people/themes, but it looks weird and out of place in my setup (notice the prominent red dot):

<img width="927" alt="Screen Shot 2021-10-03 at 19 51 17" src="https://user-images.githubusercontent.com/44045911/135752888-99d3c3f6-c951-40e9-aad5-1636350fa2e7.png">

I'd also like to use `tab_bar_style separator` but `tab_separator` is colored just like ordinary text, while I want to dim it.

**Describe the solution you'd like**
A `tab_activity_color` option to control the color of `tab_activity_symbol`, so I can change the symbol to match the text color or whatever.

And a `tab_separator_color` option to control the color of `tab_separator`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
In the next release you can write your own python function to render
tabs however you like.
