### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by jubalh** [kovidgoyal/kitty#409]
Since you already have a Makefile which calls `setup.py` why not also add an `install` section to it? :)

**Comment by kovidgoyal** [comment]
Because there is no need to install kitty. It runs directly from source.

**Comment by jubalh** [comment]
Erm.. okay.

In case you didn't notice, please check the following:
[aur package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kitty#n27) line 27
[nixpkg](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/kitty/default.nix#L38) line 38
[gentoo package](https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-terms/kitty/kitty-9999.ebuild?id=91247cd2fbe3257fbd2396ca0d8165d53c4b154d#n82) line 82

All of them install the thing by hand because you don't provide a normal `make install` ;)

> No need to install

Thats something very funny to say..

**Comment by kovidgoyal** [comment]
Yes, and they should install things by hand, that's the way installation in prefixes works. No halfway decent linux packaging script will every install things directly into the filesystem, it will install in a prefix and copy from there. Which kitty supports beautifully with ./setup.py linux-package which you would know if you read the README note to linux packagers.

And its not funny, its awesome. The fact that software as complex as kitty can be designed to run without needing installation, is absolutey beuatiful.

**Comment by jubalh** [comment]
It seems you are a bit confused here.

> Which kitty supports beautifully with ./setup.py linux-package which you would know if you read the README note to linux packagers.

I indeed read the README, maybe you notice the words:
> This will install kitty into the directory linux-package. You can run kitty with linux-package/bin/kitty. All the files needed to run kitty will be in linux-package/lib/kitty. The terminfo file will be installed into linux-package/share/terminfo. Simply copy these files into /usr to install kitty

Did you read the word **install** ?
Because this is exactly whats happening there.

And the things that the above mentioned packages do by hand, or you yourself describe in that README, which is copying the files into a location, is exactly what you could automate in the `make install` section.

**Comment by kovidgoyal** [comment]
Yes, and I dont want to, because, and I quote myself: "No halfway decent linux packaging script will ever install things directly into the filesystem, it will install in a prefix and copy from there" 

linux-package is there for linux pacjkagers. The makefile is there for kitty users. Anyway I am done wasting time arguing with you.

**Comment by jubalh** [comment]
> No halfway decent linux packaging script will ever install things directly into the filesystem, it will install in a prefix and copy from there

Actually all decent software provides standard ways to compile and install it.
If  you provide a Makefile, the standard way would be to support the `install` target.

Makefiles are there to automate tasks.

Have you ever compiled software from source and seen that you can use `make && make install` ? Often they support a `DESTDIR` or `--prefix`.

Unfortunately you remind me of a certain [fosdem talk](https://ftp.osuosl.org/pub/fosdem/2018/K.3.201/how_to_make_package_managers_cry.webm), with the exception that you hold on so strongly to your beliefs that  you don't even try to read up on what could be improved here.

**Comment by jamessan** [comment]
FWIW, as a packager, it would be useful if `setup.py linux-package` didn't also do the build.  It's much easier/cleaner to do a build, test with those artifacts and only then actually install things into a relevant directory.  This is especially true given that one can't run the tests on the directory created by `setup.py linux-package`.
