### ISSUE TITLE
Media keys are interpreted as text

### ISSUE THREAD

**Issue by pushqrdx** [kovidgoyal/kitty#4091]
**Describe the bug**
Pressing Previous/PlayPause/Next/Volume keys is interpreted as text in kitty for instance previous prints `436u`, this doesn't happen in Alacritty, 

**To Reproduce**
1. Press media keys on Linux
2. Key prints text value in terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/25884937/135772559-f9b811d8-32be-4deb-a751-15f0eb6cbb87.png)

**Environment details**
```
kitty 0.23.1 (7d41aca0e4) created by Kovid Goyal
Linux debian 5.10.0-7-rt-amd64 #1 SMP PREEMPT_RT Debian 5.10.38-1 (2021-05-20) x86_64
Debian GNU/Linux bookworm/sid \n \l
Running under:X11
Frozen: True
Paths:
  kitty: /tmp/.mount_terminSGjWR7/usr/bin/kitty
  base dir: /tmp/.mount_terminSGjWR7/usr/lib/kitty
  extensions dir: /tmp/.mount_terminSGjWR7/usr/lib/kitty-extensions
  system shell: /usr/bin/bash
Loaded config files:
  /home/pushqrdx/.config/kitty/kitty.conf

Config options different from defaults:
dynamic_background_opacity True
font_family                JetBrains Mono
font_size                  13.0
```

**Additional context**
Happens without configs

**Comment by kovidgoyal** [comment]
No they are not interpreted as text, they are sent as escape codes, in
accordance with: https://sw.kovidgoyal.net/kitty/keyboard-protocol/ 

Your shell doesnt handle them, run cat and then press the keys to see
the escape codes.

**Comment by pushqrdx** [comment]
@kovidgoyal then why doesn't this happen with neither alacritty or xterm, same shell (bash)?

**Comment by pushqrdx** [comment]
@kovidgoyal any work around to make kitty swallow these keys, i tried binding them to noop but it didn't work. i am just using bash btw

**Comment by kovidgoyal** [comment]
On Mon, Oct 04, 2021 at 08:44:05AM -0700, Ahmed Tarek wrote:
> @kovidgoyal then why doesn't this happen with neither alacritty or xterm, same shell (bash)? 

Because those terminal emulators send nothing at all for those key presses, meaning
they are completely unusable. When you want to investigate key issues
use: showkey -a or kitty +kitten show_key

**Comment by pushqrdx** [comment]
@kovidgoyal makes sense. i want to workaround this though, is there anyway i can make kitty handle/noop these keys, i tried binding them to noop but that didn't work

**Comment by kovidgoyal** [comment]
Bind them to discard_event

**Comment by pushqrdx** [comment]
Thanks, this works

**Comment by Animeshz** [comment]
@pushqrdx do you have a working example for this?

**Comment by Animeshz** [comment]
Oh actually it worked, took key names from [Comprehensive keyboard handling in terminals](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions)

e.g. `map LOWER_VOLUME discard_event`
