### ISSUE TITLE
[Feature request] Can a command over ssh trigger a local command?

### ISSUE THREAD

**Issue by marco-venuti** [kovidgoyal/kitty#4096]
I usually have emacs running as a daemon on my laptop and open files inside it using `emacsclient`. I also use my local emacs to edit remote files via ssh (using tramp mode), for example like so 
```
emacsclient /ssh:<host>:<remote file>
```
It's often annoying, when I'm browsing files on a remote shell, to go back to my local emacs and retype the path of the file I need to edit.

The feature I'm thinking of is the possibility of issuing a custom command over ssh (like `edit <remote file>`), which is captured by kitty, which instead issues a command on my local machine (like `emacsclient /ssh:<host where the command was called>:<remote file>`).

I don't know kitty's internals, so I can't tell whether or not this is feasible.

**Comment by kovidgoyal** [comment]
I'm not a fan of allowing remote software to issue arbitrary commands on
the local machine, it means a compromised remote can takeover the local
machine. As for editing remote files, it is trivial to do in kitty
already, see https://sw.kovidgoyal.net/kitty/kittens/remote_file/ 

And: https://sw.kovidgoyal.net/kitty/open_actions/ which allows you to
define arbitrary commands to run per file type.

**Comment by page-down** [comment]
Kitty already has the remote control feature. If the `remote_file` kitten is not sufficient, or if you need to run custom commands, it is perfectly possible to run any command locally using remote control on a trusted device.

https://sw.kovidgoyal.net/kitty/remote-control/

```shell
# Start a remote control instance.
kitty -o allow_remote_control=yes

# Or bind to a hotkey to open a new tab that allows remote control.
# map f1 launch --type=tab --allow-remote-control

# Connect to a trusted remote host in a window that has allowed remote control.
ssh user@host

#  Run remote control commands. (kitty should have been installed)
# You can set it to alias or use a custom script.
kitty @ launch --type=overlay emacsclient /ssh:${HOSTNAME}:/path/to/file
```
