### ISSUE TITLE
Remap symbols using `symbol_map`

### ISSUE THREAD

**Issue by 4e554c4c** [kovidgoyal/kitty#4097]
**Is your feature request related to a problem? Please describe.**
`symbol_map` "Avoids the need for patched fonts", however one of the advantages about patched fonts is that they can rearrange codepoints for the fonts they include. For example, both Font Awesome and weather icons use the PUA codepoint U+F000 for different glyphs. The popular font patcher Nerd fonts [gets around this](https://github.com/ryanoasis/nerd-fonts/blob/master/font-patcher#L521-L543) by patching these fonts to different codepoints.

**Describe the solution you'd like**
It would be nice if `symbol_map` could actually remap these codepoints, e.g. If I had the lines
```
symbol_map U+F000-U+F2E0 FontAwesome
symbol_map U+E300-U+E3EB to U+F000-U+F0EB weathericons-regular
```
then it would replicate the behavior of U+F000 rendering as U+F000 in FontAwesome, and U+E300 rendering as U+F000 in weathericons

**Describe alternatives you've considered**
The main alternative is font patching, weather _bundling_ each of these fonts into one font as FontAwesome does, or patching each individual font to map the codepoints.

The former seems to be discouraged by kitty, and the latter seems a bit difficult to burden each user with.

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in implementing this. If you have fonts
that use the same codepoint for different glyphs, the correct solution
is to decide for yourself which is the correct glyph for that codepoint
and pick that font for that codepoint. Or better, work with the upstream
fonts to resolve the conflict.
