### ISSUE TITLE
Several kitty.conf ?

### ISSUE THREAD

**Issue by ghost** [kovidgoyal/kitty#4107]
**Problem:**
My `kitty.conf` is nearly 200 lines long, and it's only growing in size. 

**So:**
Could kitty use several `kitty.conf`? For example:
```
 ~/.config/   
   └── kitty/
          ├── kitty_keyboard.conf
          ├── kitty_colorscheme.conf
          └── kitty_general.conf

```

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/conf/?highlight=include#kitty-conf.
