### ISSUE TITLE
Request to have the Window Title %%h token return the name of the serial port name when the active connection type is Serial

### ISSUE THREAD

**Issue by leifclaesson** [kovidgoyal/kitty#4108]
As I work on many different projects at different times, I have a few "shortcut" sessions saved where the session name does not change but the _host name_ or _serial port_ of the session changes.

I have shortcut keys set up to start KiTTY with saved session "Debug1", "Debug2", "Debug3" etc.
Then, when I start working on a different project, I simply change the Session IP address, or even change the Session Protocol to Serial, enter for example COM12, and save to session "Debug2". Then, I press the shortcut key to launch kitty with the "Debug2" session, it comes right up.

Unfortunately, the **KiTTY Window Title** will actually show the previously used stale **ip address** even when you're connected to a Serial terminal, instead of showing **COM12** which it's actually connected to!

I can see how this would happen if %%h is the default window title, and indeed %%h means host name, but I don't think that's actually useful behavior -- I think it would be more useful to return **COM12** than a completely unrelated IP address.

Thank you for your attention.

**Comment by kovidgoyal** [comment]
You want https://github.com/cyd01/KiTTY

**Comment by leifclaesson** [comment]
> 
> 
> You want https://github.com/cyd01/KiTTY

Oops! My bad, thank you!
