### ISSUE TITLE
The kitty shell default shortcut does not work under macOS

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4109]
**Describe the bug**
The default shortcut for `kitty shell` is `kitty_mod+escape` (Ctrl+Shift+ESC).
However, nothing happens when you press this key combination under macOS. It works fine under Linux.

I wonder if there is a special reason why the bound action is not executed.

**To Reproduce**
1. Press `Ctrl+Shift+ESC` under macOS
2. No kitty shell window.

**Screenshots**
n/a

**Environment details**
- macOS 11.6
- kitty from master branch

**Additional context**
```shell
kitty --config=NONE -o "map ctrl+shift+escape kitty_shell window" --debug-input
```

```
...
# ESC
on_key_input: glfw key: 0xe000 native_code: 0x35 action: PRESS mods: none text: '' state: 1 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
updated pre-edit text: ''
Press: native_key: 0x35 (<cc>) glfw_key: 0xe000 mods: none char_count: 1 deadKeyState: 0 repeat: 0 text: <none> glfw_key: ESCAPE marked_text: 
on_key_input: glfw key: 0xe000 native_code: 0x35 action: REPEAT mods: none text: '' state: 0 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
sent encoded key to child
Release: native_key: 0x35 (<cc>) glfw_key: 0xe000 mods: none 
on_key_input: glfw key: 0xe000 native_code: 0x35 action: RELEASE mods: none text: '' state: 0 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
ignoring as keyboard mode does not support encoding this event

# Ctrl+Shift+ESC
on_key_input: glfw key: 0xe062 native_code: 0x3b action: PRESS mods: ctrl text: '' state: 0 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
on_key_input: glfw key: 0xe061 native_code: 0x38 action: PRESS mods: ctrl+shift text: '' state: 0 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
Release: native_key: 0x35 (<cc>) glfw_key: 0xe000 mods: ctrl+shift 
on_key_input: glfw key: 0xe062 native_code: 0x3b action: RELEASE mods: shift text: '' state: 0 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
on_key_input: glfw key: 0xe061 native_code: 0x38 action: RELEASE mods: none text: '' state: 0 updateIMEState: 189.000000, 6.000000, 7.000000, 13.000000
ignoring as keyboard mode does not support encoding this event
```

It seems that any modifier key with the ESC key suffers from this issue.

**Comment by kovidgoyal** [comment]
This will almost certainly be because cocoa is intercepting
esc+modifier. From the debug log, it is clear that the esc keypress is
not reaching kitty. I'm nt a macOS user so I'm not sure, but is there
some cocoa global shortcut with esc+ctrl ??

You can also add a print around line 514 in cocoa_init.m to see if the
keypress is reaching at least till there.

**Comment by page-down** [comment]
> but is there some cocoa global shortcut with esc+ctrl ?

I don't recall any default cocoa OS window shortcuts related to Ctrl and ESC, except for the system-wide Cmd+Opt+ESC to force quit applications.

It is not globally intercepted by the OS or other software.

> You can also add a print around line 514 in cocoa_init.m to see if the keypress is reaching at least till there.

Event with ESC keycode reaches `keydown_block`.

Thanks, confirmed that the following patch solves the ESC related shortcut issue under macOS, keyup responds normally so no changes are made.

```diff
diff --git a/glfw/cocoa_init.m b/glfw/cocoa_init.m
index a43aa24e..b9a7fbc0 100644
--- a/glfw/cocoa_init.m
+++ b/glfw/cocoa_init.m
@@ -471,6 +471,19 @@ - (void)render_frame_received:(id)displayIDAsID
     return false;
 }
 
+
+static bool
+is_modifiers_esc(NSEvent *event, NSEventModifierFlags modifierFlags) {
+    if (event.keyCode != kVK_Escape) return false;
+    if (
+            (modifierFlags & NSEventModifierFlagControl) != 0 ||
+            (modifierFlags & NSEventModifierFlagShift) != 0 ||
+            (modifierFlags & NSEventModifierFlagOption) != 0 ||
+            (modifierFlags & NSEventModifierFlagCommand) != 0
+       ) return true;
+    return false;
+}
+
 GLFWAPI GLFWapplicationshouldhandlereopenfun glfwSetApplicationShouldHandleReopen(GLFWapplicationshouldhandlereopenfun callback) {
     GLFWapplicationshouldhandlereopenfun previous = handle_reopen_callback;
     handle_reopen_callback = callback;
@@ -511,7 +524,7 @@ int _glfwPlatformInit(void)
     NSEvent* (^keydown_block)(NSEvent*) = ^ NSEvent* (NSEvent* event)
     {
         NSEventModifierFlags modifierFlags = [event modifierFlags] & NSEventModifierFlagDeviceIndependentFlagsMask;
-        if (is_ctrl_tab(event, modifierFlags) || is_cmd_period(event, modifierFlags)) {
+        if (is_ctrl_tab(event, modifierFlags) || is_cmd_period(event, modifierFlags) || is_modifiers_esc(event, modifierFlags)) {
             // Cocoa swallows Ctrl+Tab to cycle between views
             [[NSApp keyWindow].contentView keyDown:event];
         }

```

The modifiers and ESC key events can be seen as normal with `kitty +kitten show_key -m kitty` .

**Comment by kovidgoyal** [comment]
On Sun, Oct 10, 2021 at 03:59:14PM -0700, page-down wrote:
> Also, if you have pressed the macOS default function shortcut that switches the focus, you need to click the mouse in the window, regain the focus, and press the keys again to get the response. In my tests, I also found that pressing the function shortcut key one after another did not work, and I found that the focus was cut off, and it was hard to notice.

What shortcut is that? As far as I know cmd+tab is the macOS shortcut to
switch focus between applications and cmd+` to switch focus between
windows of an application. Both work in kitty. 

> 
> ---
> 
> The issue caused by the current changes can be reproduced by these steps.
> 
> - Enable "Move focus to the menu bar (Ctrl+F2)" on macOS System Preferences.
> - Press Ctrl+F2
> - Cannot focus on menu bar.

I have fixed this by only overriding ctrl+shift+function key

The proper solution is written in the comment in https://github.com/kovidgoyal/kitty/commit/dc11b76bea8cc6b268b4afbdb1c7fba6861ab6a4
but is a bit too much work, at least for me as it involves reading a
preference and then reverse engineering  bunch of numbers to detect
"important" shortcuts which should be passed through to cocoa.

**Comment by page-down** [comment]
In addition to the problem with the ESC shortcut mentioned above, I also found another problem with key events being sent repeatedly.

Please note that the previous message mentioned: with previous commit `2b9408c`, Ctrl+Option+ESC `REPEAT`
```text
# Ctrl + Option + ESC
Alt+Ctrl+ESCAPE REPEAT 
CSI 27 ; 7 : 2 u
```

Here is the last change `dc11b76`, after executing the `kitty --debug-input kitty +kitten show_key -m kitty` command, the **first time** the ctrl+shift + function shortcut is pressed the `REPEAT` action appears, is this caused by the key event being sent repeatedly?

Take Ctrl+Shift+F1 as an example.

```text
Press any keys - Ctrl+C or Ctrl+D will terminate
Ctrl+LEFT_CONTROL PRESS 
CSI 57442 ; 5 u

Shift+Ctrl+LEFT_SHIFT PRESS 
CSI 57441 ; 6 u

Shift+Ctrl+F1 REPEAT 
CSI 1 ; 6 : 2 P

Shift+Ctrl+F1 RELEASE 
CSI 1 ; 6 : 3 P

Ctrl+LEFT_SHIFT RELEASE 
CSI 57441 ; 5 : 3 u

LEFT_CONTROL RELEASE 
CSI 57442 ; 1 : 3 u
```

Subsequent presses of shortcuts seem to be normal.

```text
Shift+Ctrl+F1 PRESS 
CSI 1 ; 6 P
Shift+Ctrl+F1 RELEASE 
CSI 1 ; 6 : 3 P
```

Is this an acceptable result?

**Comment by kovidgoyal** [comment]
Both issues should now be fixed in master.
