### ISSUE TITLE
kitty on CPU only server

### ISSUE THREAD

**Issue by xiangpeng2008** [kovidgoyal/kitty#4116]
Hi,

Would kitty run on CPU only server ? In my firm we have only machines without GPU and machines with good GPU for big data computing, the latter are located in other regions, which I can't use to launch kitty due to high geographic latency. 

**Is your feature request related to a problem? Please describe.**
Kitty is claimed for "GPU based terminal emulator", does this mean it won't run on CPU only machine ?
I tried to install and run it, but got error 
```
[286 10:49:10.568426] [glfw error 65542]: GLX: GLX version 1.3 is required
[286 10:49:10.568475] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

And my colleague told me OpenGL is used to interact with GPUs.

Thanks,

**Comment by kovidgoyal** [comment]
You dont want to run the terminal on the computer you are connecting to. Run an ssh daemon there, run the terminal on your local machine and connect to the remote machine via ssh. Using VNC to run a terminal on a remote machine is a bit rube goldberg-esque.

And someday when kitty gets a remote daemon you could actually run the kitty daemon on the remote computer and connect it to kitty on the local machine.

**Comment by xiangpeng2008** [comment]
> You dont want to run the terminal on the computer you are connecting to. Run an ssh daemon there, run the terminal on your local machine and connect to the remote machine via ssh. Using VNC to run a terminal on a remote machine is a bit rube goldberg-esque.

This sounds nice, I will try this tmr. 
> 
> And someday when kitty gets a remote daemon you could actually run the kitty daemon on the remote computer and connect it to kitty on the local machine.

I will use kitty for now on my mac, and do same in office when we got a kitty daemon. But would it work in the same way as kitty running locally without dependence on the real terminal on local machine ?

**Comment by kovidgoyal** [comment]
It runs fine under wsl and probably would run in daemon mode even without wsl with only minor adjustments.

**Comment by xiangpeng2008** [comment]
I will try on wsl

**Comment by xiangpeng2008** [comment]
I don't have administrator right on the Windows 10, so can't use wsl ..
I will wait for the daemon mode, but would the daemon mode works in on my local Windows 10 where there's no kitty ? It would shock me to have Graphics, windows splitting things with just kitty daemon on linux and another brand of terminal running Windows 10.

**Comment by xiangpeng2008** [comment]
After I follow https://www.planetminecraft.com/blog/glfw-error-65543-glx-failed-to-create-context-glxbadfbconfig-solution/ to do 
`export MESA_GL_VERSION_OVERRIDE=4.3`
kitty could be open with mobaxterm, but performance is indeed not good. There's a huge lagging.

**Comment by ctrlcctrlv** [comment]
As Kovid said, you will never have good performance running Kitty on a CPU-only computer, no matter how advanced the CPU. Put a GPU in your server or run kitty on your client.

**Comment by xiangpeng2008** [comment]
The performance issue may come xterm forwarding rather than CPU. Because it's very lagging.
I will try to run it on WSL on local machine, instead of remote machine + vnc/mobaxterm/xming

**Comment by ctrlcctrlv** [comment]
You mean X11 forwarding over SSH, right? I don't think such forwarding normally uses the GPU even if available. The more layers you add, the more places GPU can be turned off. Best to keep it simple.
