### ISSUE TITLE
Change the enabled layouts via remote control

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4129]
**Is your feature request related to a problem? Please describe.**
Currently the enabled layout can be configured in the configuration file and startup session, however there are times when the enabled layouts of the current tab needs to be changed to make it easier for `ctrl+shift+l` to switch between layouts.

**Describe the solution you'd like**
Add a new command to change enabled layout for remote control. There may be option to change the default layouts (for new tabs), or to change the enabled layouts of the matching tab only.

It also supports binding the keyboard as a complement to the `Layout Management` feature set.
https://sw.kovidgoyal.net/kitty/conf/#layout-management

**Describe alternatives you've considered**
n/a

**Additional context**

This suggestion is mentioned in:
https://github.com/kovidgoyal/kitty/issues/4110#issuecomment-945082137

**Comment by kovidgoyal** [comment]
IMO this is not a common enough action to warrant a default mapping and
without that, it wont be particularly discoverable anyway.

**Comment by kovidgoyal** [comment]
You want

kitty --config=NONE -o 'enabled_layouts=tall:mirrored=true'

**Comment by kovidgoyal** [comment]
On Thu, Oct 21, 2021 at 01:02:41AM -0700, page-down wrote:
> This is perhaps too much to ask. It would be great if you could consider it.
 
Sure done

**Comment by page-down** [comment]
> Sure done

Thanks. Is there going to be a new `get-enabled-layouts` command for getting all the layouts that are enabled for matching tabs? I'll try it later.

With the latest commit, the current activated layout parameters are available in `kitty @ ls`. I'll do another conversion to enabled_layouts syntax.

---
I found in my recent usage that switching between layout `mirrored=true` and `mirrored=false` (ctrl+shift+l), there is a serious delay.
```shell
kitty --config=NONE -o enabled_layouts=tall:mirrored=false,tall:mirrored=true
```
Open three kitty windows after startup. Press ctrl+shift+l to toggle the layout. There is a noticeable delay when switching layouts. The same problem with `fat:mirrored=true/false`.

However, switching between different layouts like `tall:mirrored=false,fat:mirrored=true,grid` and so on, there is no any delay.

I have only found this problem under macOS and have not been able to reproduce it under Linux.

I tried `make profile`. However, after kitty exits, there are a lot of error messages. The final profile log file /tmp/kitty-profile.log seems to have no function names in it.

```text
error: .../otool-classic: can't open file: /usr/lib/.../***.dylib  (No such file or directory)
error: .../otool-classic: can't open file: /System/Library/Frameworks/.../***.dylib  (No such file or directory)
Total: 103 samples
      35  34.0%  34.0%       35  34.0% 0x00007fff2037d2ba
      18  17.5%  51.5%       18  17.5% 0x00007fff2037d3f2
       6   5.8%  57.3%        6   5.8% 0x00007fff2037fcde
       5   4.9%  62.1%        5   4.9% 0x00007fff2037d25a
...
```

Do you have any thoughts on the delays here? Thank you.

**Comment by page-down** [comment]
> What delay? I can see about a second of delay while the shell responds to the window being resized and redraws the prompt. But that's it.

It's that lag. Compare with `tall:mirrored=false,fat:mirrored=true,grid,vertical` or switch between any other layout.
Any other switch between layouts is done instantly. For example, with 3 empty windows. `map f1 launch read`

**Comment by kovidgoyal** [comment]
you can try building with make debug-event-loop and see if rendering is
delayed after the resize for some reason.

**Comment by page-down** [comment]
> See if `e18b0cd` fixes it.

Yes, the window layout is re-rendered immediately after switching.
