### ISSUE TITLE
Can't use monospace font with Kitty (even after reading the FAQ)

### ISSUE THREAD

**Issue by goobleplax** [kovidgoyal/kitty#4141]
**Describe the bug**

Monospaced (and non-monospaced) fonts are not working.

**To Reproduce**
1. Download and install King Plus Monospaced font. (https://quikscript.neocities.org/qprojects/qfonts.htm)
2. Follow steps in FAQ under "kitty is not able to use my favorite font?¶" (https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font)
3. Remain unable to use font in Kitty.
4. Request help on Github after seeing pages of users with similar problems.

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by hellosway** [comment]
I suspect these taken from the website feature list :
` All ligeratures (-er, -ar, -or, you, -ere, -ia, -ear)
All half-letters (letters h, y, t, d, z, p, w, wh)
The 4 "optional" characters (Ll, loCH, & the two "X's") `
It is probably not truly monospaced becuase of this, every charterer is not one cell.

**Comment by kovidgoyal** [comment]
The place to request help is discussions not issues. And when you
request help at least take the time to document your environment, the
things you actually did try and keep the passive aggressive shit to a
minimum.
