### ISSUE TITLE
Support passing stdin through kitty @ launch

### ISSUE THREAD

**Issue by kbd** [kovidgoyal/kitty#4158]
Currently you can pass the screen contents to the child process using [`--stdin-source`](https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-stdin-source). I'd like to be able to pass through the stdin of `kitty` to the child process.

Use case: in database CLIs like [LiteCLI](https://litecli.com/) you can configure the pager for results. I'd like the pager to open in a new kitty window with `kitty @ launch` and pass the results to the pager in the new window.

**Comment by kbd** [comment]
Thanks @page-down! I actually immediately had a similar idea of using named pipes but wanted to mess with it myself before responding.

Tried my own thing for a while but haven't been able to get it to work properly. Could you please explain why `KITTY_LISTEN_ON` is necessary? That would mean I need to change how I'm launching my main kitty window?

**Comment by page-down** [comment]
This environment variable is equivalent to the `--to` parameter of the remote control command `kitty @ --to=`.
In the previous command, kitty starts by listening to the UNIX socket for remote control.

To perform remote control:
- Make sure the program can make `kitty @` send the correct escape sequences to the terminal.
- Use sockets for communication, either UNIX sockets or network TCP sockets.

**Comment by kbd** [comment]
I don't understand why the remote control is needed in the first place. Why does `kitty @ launch` need to be told which parent instance to talk to? I'd expect all communication go through the named pipe, so why does it need to talk at all?

**Comment by kbd** [comment]
Got it working (see above linked commit. No socket configuration necessary):

![Screen Shot 2021-10-30 at 8 03 58 PM](https://user-images.githubusercontent.com/728060/139563726-66ed9128-cacc-49b3-9946-6fa7bc613ae7.png)

Now I don't need slow GUI db tools as much 👍

(That `ModuleNotFoundError` [is unrelated](https://github.com/saulpw/visidata/issues/1145).)
