### ISSUE TITLE
Bring `open_url_modifiers` back

### ISSUE THREAD

**Issue by escorponox** [kovidgoyal/kitty#4159]
I'm always frustrated when I accidentally click on an URL and it opens in the URL

On previous versions I had `open_url_modifiers kitty_mod` on my config and there wasn't unexpected URL openings

The current behavior could be maintained if you don't have `open_url_modifiers` set.

Thank you so much for this amazing terminal

**Comment by gruvw** [comment]
For me it does not work :(
I (correctly) can't open links with the left click alone, but ctrl+left is not opening either.

**Comment by rmehner** [comment]
To be fair, I've tested this with CMD on macOS and assumed that `ctrl` will behave the same.

My config (those are the only two `mouse_map` commands in the whole config):

```kitty
mouse_map left click ungrabbed no_op
mouse_map cmd+left click grabbed,ungrabbed mouse_handle_click selection link prompt
```
