### ISSUE TITLE
Error opening terminal: xterm-kitty.

### ISSUE THREAD

**Issue by mizzunet** [kovidgoyal/kitty#4164]
**Describe the bug**
Showing an error while for some TUI programs such as htop, powertop. But not for nmtui

**To Reproduce**
1. Install kitty https://sw.kovidgoyal.net/kitty/binary/#binary-install
2. Configure icon https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux
3. Make kitty default terminal according to thishttps://github.com/kovidgoyal/kitty/issues/1101#issuecomment-617100609
```
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator `which kitty` 50
sudo update-alternatives --config x-terminal-emulator
```
4. Run command `htop`, `sudo powertop` or `reset`
5. See the error `Error opening terminal: xterm-kitty.`

**Environment details**
```
kitty 0.23.1 (cd7b4fcd8e) created by Kovid Goyal
Linux debian 5.14.15-xanmod1 #0~git20211027.052f7ad SMP Wed Oct 27 16:49:58 UTC 2021 x86_64
Debian GNU/Linux bookworm/sid \n \l
Running under:X11

Config options different from defaults:
```

**Comment by up-to-you** [comment]
Why does `export TERM=kitty` solved every issue i had with sudo and nested ssh ???
I'm using `alias ssh="kitty +kitten ssh"` and no need to preserve TERMINFO via `sudo visudo` if TERM=kitty and NOT xterm-kitty.

**Comment by mizzunet** [comment]
Kovid, I switched to Arch and kitty in it, no issue there. So, I might've messed something in Debian ;)

**Comment by up-to-you** [comment]
I have bunch of Ubuntu servers and literally solved all issues i had by using:
`alias ssh="TERM=xterm-256color ssh"`
So, on my client Mac machine:
```bash
echo $TERM
xterm-kitty
```
on server:
```bash
echo $TERM
xterm-256color ssh
```
I'm **so happy** i got rid of all this f**** `terminal is not fully functional`.

P.s. `kitty +kitten ssh` | `kitty +kitten ssh use-python` didn't work for me. However, best terminal ever !

**Comment by eosemeyko** [comment]
It helped me, try it, and on the remote server under the root login it also worked and now all the commands that gave an error are opened

add line to you home rc file
`
# Fix ssh kitty
alias ssh='TERM="xterm-256color" kitty +kitten ssh'
`

**Comment by olsonperrensen** [comment]
See #1613, worked for me.

**Comment by quintanaplaca** [comment]
The best answer! :)

**Comment by ross96D** [comment]
i fix the issue installing `kitty-terminfo` package. See https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work
