### ISSUE TITLE
Shell integration: additional features for getting command output

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4166]
**Is your feature request related to a problem? Please describe.**
Unable to use shortcuts to quickly open command output in pager that ctrl+shift+z/x jumped to.
Currently only the output of the last executed command is available.

**Describe the solution you'd like**
Take advantage of the benefits of shell integration by extending the capabilities of command output related features.
- Gets the first command output from the screen. (pager/stdin source/rc)
- Get the command output at any line from the screen. (hints/mouse selection extend)

**Describe alternatives you've considered**
n/a

**Additional context**

This feature was previously discussed in the Shell integration thread.

## What I have accomplished:

- Extend the original `last_cmd_output` to support searching up, around, and down for command output at a specific screen line.
- Get the first command output of the screen.
  - Only the first `OUTPUT_START` in the screen will be fetched. Anything else is returned as an empty string.
  - Keyboard action, stdin input source, remote control, etc. associated with this function.
- Fix `last_cmd_output` stdin-source formatting issue.

However, I'm not sure how the assigning shortcuts section should be handled, so it's currently commented out. (`kitty/options/definition.py`)

This currently works great with ctrl+shift+z/x.

You can use shortcuts to open the command output in a newly created kitty window or os window, after a quick ctrl+shift+z/x jump. As an side-by-side reference.

## Function Parameters

```c
static bool find_cmd_output(Screen *self, OutputOffset *oo, index_type start_y, int direction, bool on_screen_only) {}
```

- `int direction`: `-1` search upwards, `0` search around, `1` search downwards
- `bool on_screen_only`: When searching for the command output downwards, this parameter will limit the search to only within the screen.

## Features still to be done

However, the feature about using the command line output around the line has not yet been implemented. My idea is to use the keyboard and mouse related features.

Is it possible to:
- Keyboard: Use hints to select and quickly select(copy) the command output on the screen, without editor pager.
- Mouse: Extend text selection to whole command output (when clicking with modifier keys). Handy for mouse users to quickly select and copy. No more painful manual text selection. (Mouse operation)

I have yet to find a way to make it happen.

If this feature could be added to kitty, it would be a small addition to the Shell integration and shows its convenience.

Thank you very much.

## Patch

<details>
<summary>Click to expand ...</summary>
<p>

```patch
diff --git a/docs/kittens/custom.rst b/docs/kittens/custom.rst
index 0cadd9ea..cfd69431 100644
--- a/docs/kittens/custom.rst
+++ b/docs/kittens/custom.rst
@@ -93,9 +93,11 @@ instead. If you want line wrap markers as well, use ``screen-ansi``
 or just ``screen``. For the scrollback buffer as well, use
 ``history``, ``ansi-history`` or ``screen-history``. To get
 the currently selected text, use ``selection``. To get the output
+of the first command run in the shell on screen, use ``first-output``
+or ``first-output-ansi`` or ``first-output-screen-ansi``. To get the output
 of the last command run in the shell, use ``output`` or ``output-ansi``
-or ``output-screen-ansi``. Note that using ``output`` requires
-:ref:`shell_integration`.
+or ``output-screen-ansi``. Note that using ``first-output``
+or ``output`` requires :ref:`shell_integration`.
 
 
 Using kittens to script kitty, without any terminal UI
diff --git a/kitty/boss.py b/kitty/boss.py
index e1121cfb..ee26a5de 100755
--- a/kitty/boss.py
+++ b/kitty/boss.py
@@ -107,6 +107,10 @@ def as_text(**kw: bool) -> str:
         return as_text(as_ansi=True, alternate_screen=True)
     if arg == '@ansi_alternate_scrollback':
         return as_text(as_ansi=True, alternate_screen=True, add_history=True)
+    if arg == '@first_cmd_output_on_screen':
+        return w.first_cmd_output_on_screen(add_wrap_markers=add_wrap_markers)
+    if arg == '@ansi_first_cmd_output_on_screen':
+        return w.first_cmd_output_on_screen(as_ansi=True, add_wrap_markers=add_wrap_markers)
     if arg == '@last_cmd_output':
         return w.last_cmd_output(add_wrap_markers=add_wrap_markers)
     if arg == '@ansi_last_cmd_output':
@@ -1180,6 +1184,9 @@ def _run_kitten(
                     data = sel.encode('utf-8') if sel else None
                 elif type_of_input is None:
                     data = None
+                elif type_of_input in ('first-output', 'first-output-screen', 'first-output-screen-ansi', 'first-output-ansi'):
+                    q = type_of_input.split('-')
+                    data = w.first_cmd_output_on_screen(as_ansi='ansi' in q, add_wrap_markers='screen' in q).encode('utf-8')
                 elif type_of_input in ('output', 'output-screen', 'output-screen-ansi', 'output-ansi'):
                     q = type_of_input.split('-')
                     data = w.last_cmd_output(as_ansi='ansi' in q, add_wrap_markers='screen' in q).encode('utf-8')
diff --git a/kitty/fast_data_types.pyi b/kitty/fast_data_types.pyi
index e58f1549..0b387a05 100644
--- a/kitty/fast_data_types.pyi
+++ b/kitty/fast_data_types.pyi
@@ -1115,6 +1115,7 @@ class Screen:
         pass
     as_text_non_visual = as_text
     as_text_alternate = as_text
+    first_cmd_output_on_screen = as_text
     last_cmd_output = as_text
 
     def scroll_until_cursor(self) -> None:
diff --git a/kitty/launch.py b/kitty/launch.py
index 494331b6..5518b516 100644
--- a/kitty/launch.py
+++ b/kitty/launch.py
@@ -123,15 +123,16 @@ def options_spec() -> str:
 --stdin-source
 type=choices
 default=none
-choices=none,@selection,@screen,@screen_scrollback,@alternate,@alternate_scrollback,@last_cmd_output
+choices=none,@selection,@screen,@screen_scrollback,@alternate,@alternate_scrollback,@first_cmd_output_on_screen,@last_cmd_output
 Pass the screen contents as :code:`STDIN` to the child process. :code:`@selection` is
 the currently selected text. :code:`@screen` is the contents of the currently active
 window. :code:`@screen_scrollback` is the same as :code:`@screen`, but includes the
 scrollback buffer as well. :code:`@alternate` is the secondary screen of the current
 active window. For example if you run a full screen terminal application, the
-secondary screen will be the screen you return to when quitting the
-application. :code:`@last_cmd_output` is the output from the last command run in the shell,
-this needs :ref:`shell_integration` to work.
+secondary screen will be the screen you return to when quitting the application.
+:code:`@first_cmd_output_on_screen` is the output from the first command run in the shell on screen,
+:code:`@last_cmd_output` is the output from the last command run in the shell,
+this two needs :ref:`shell_integration` to work.
 
 
 --stdin-add-formatting
@@ -322,7 +323,7 @@ def launch(
     if opts.stdin_source != 'none':
         q = str(opts.stdin_source)
         if opts.stdin_add_formatting:
-            if q in ('@screen', '@screen_scrollback', '@alternate', '@alternate_scrollback'):
+            if q in ('@screen', '@screen_scrollback', '@alternate', '@alternate_scrollback', '@first_cmd_output_on_screen', '@last_cmd_output'):
                 q = '@ansi_' + q[1:]
         if opts.stdin_add_line_wrap_markers:
             q += '_wrap'
diff --git a/kitty/options/definition.py b/kitty/options/definition.py
index ab2c5ba5..49a851db 100644
--- a/kitty/options/definition.py
+++ b/kitty/options/definition.py
@@ -2995,6 +2995,16 @@
 '''
     )
 
+map('Browse output of the first shell command on screen in less',
+    '', #'show_first_command_output_on_screen kitty_mod+g show_first_command_output_on_screen',
+    long_text='''
+Requires :ref:`shell_integration` to work. You can pipe the output
+of the first command run in the shell on screen using the :doc:`launch` function.
+For example, the following opens the output in less in an overlay window::
+
+    map f1 launch --stdin-source=@first_cmd_output_on_screen --stdin-add-formatting --type=overlay less +G -R
+''')
+
 map('Browse output of the last shell command in less',
     'show_last_command_output kitty_mod+g show_last_command_output',
     long_text='''
diff --git a/kitty/rc/get_text.py b/kitty/rc/get_text.py
index 06182ad5..7c0b6b57 100644
--- a/kitty/rc/get_text.py
+++ b/kitty/rc/get_text.py
@@ -17,7 +17,7 @@ class GetText(RemoteCommand):
 
     '''
     match: The tab to focus
-    extent: One of :code:`screen`, :code:`last_cmd_output`, :code:`all`, or :code:`selection`
+    extent: One of :code:`screen`, :code:`first_cmd_output_on_screen`, :code:`last_cmd_output`, :code:`all`, or :code:`selection`
     ansi: Boolean, if True send ANSI formatting codes
     cursor: Boolean, if True send cursor position/style as ANSI codes
     wrap_markers: Boolean, if True add wrap markers to output
@@ -28,11 +28,13 @@ class GetText(RemoteCommand):
     options_spec = MATCH_WINDOW_OPTION + '''\n
 --extent
 default=screen
-choices=screen, all, selection, last_cmd_output
+choices=screen, all, selection, first_cmd_output_on_screen, last_cmd_output
 What text to get. The default of :code:`screen` means all text currently on the screen.
 :code:`all` means all the screen+scrollback and :code:`selection` means the
-currently selected text. Finally, :code:`last_cmd_output` means the output of the last
-command that was run in the window, which requires :ref:`shell_integration` to be enabled.
+currently selected text. :code:`first_cmd_output_on_screen` means the output of the first
+command that was run in the window on screen. Finally, :code:`last_cmd_output` means
+the output of the last command that was run in the window. The last two requires
+:ref:`shell_integration` to be enabled.
 
 
 --ansi
@@ -73,6 +75,11 @@ def response_from_kitty(self, boss: Boss, window: Optional[Window], payload_get:
         window = self.windows_for_match_payload(boss, window, payload_get)[0]
         if payload_get('extent') == 'selection':
             ans = window.text_for_selection()
+        elif payload_get('extent') == 'first_cmd_output_on_screen':
+            ans = window.first_cmd_output_on_screen(
+                as_ansi=bool(payload_get('ansi')),
+                add_wrap_markers=bool(payload_get('wrap_markers')),
+            )
         elif payload_get('extent') == 'last_cmd_output':
             ans = window.last_cmd_output(
                 as_ansi=bool(payload_get('ansi')),
diff --git a/kitty/screen.c b/kitty/screen.c
index f9817c2a..95760bf2 100644
--- a/kitty/screen.c
+++ b/kitty/screen.c
@@ -2591,6 +2591,7 @@ as_text_alternate(Screen *self, PyObject *args) {
 typedef struct OutputOffset {
     Screen *screen;
     int start;
+    unsigned num_lines;
 } OutputOffset;
 
 static Line*
@@ -2599,37 +2600,111 @@ get_line_from_offset(void *x, int y) {
     return range_line_(r->screen, r->start + y);
 }
 
+static bool
+find_cmd_output(Screen *self, OutputOffset *oo, index_type start_y, int direction, bool on_screen_only) {
+    bool found_prompt = false, found_output = false, found_next_prompt = false;
+    int start = 0, end = 0;
+    int y1 = start_y, y2 = start_y;
+    const int upward_limit = -self->historybuf->count;
+    const int downward_limit = self->lines - 1;
+    const int screen_limit = -self->scrolled_by + downward_limit;
+
+    // find around
+    if (direction == 0) {
+        Line *line = range_line_(self, start_y);
+        if (line->attrs.prompt_kind == PROMPT_START) {
+            found_prompt = true;
+            // change direction to downwards to find command output
+            direction = 1;
+        } else if (line->attrs.prompt_kind == OUTPUT_START) {
+            found_output = true; start = start_y;
+            found_prompt = true;
+            // keep finding the first output start upwards
+        }
+        y1 = start_y - 1; y2 = start_y + 1;
+    }
+
+    // find upwards
+    if (direction <= 0) {
+        // find around: only needs to find the first output start
+        // find upwards: find prompt after the output, and the first output
+        while (y1 >= upward_limit) {
+            Line *line = range_line_(self, y1);
+            if (line->attrs.prompt_kind == PROMPT_START) {
+                if (direction == 0) {
+                    // find around: stop at prompt start
+                    start = y1 + 1;
+                    break;
+                }
+                found_next_prompt = true; end = y1;
+            } else if (line->attrs.prompt_kind == OUTPUT_START) {
+                start = y1;
+                break;
+            }
+            y1--;
+        }
+        if (y1 < upward_limit) {
+            start = upward_limit;
+        } else {
+            // resizing screen can cause multiple consecutive output start lines,
+            // so find the first one
+            while (start > upward_limit) {
+                Line *line = range_line_(self, start - 1);
+                if (line->attrs.prompt_kind != OUTPUT_START) break;
+                start--;
+            }
+        }
+        found_output = true;
+        found_prompt = true;
+    }
+
+    // find downwards
+    if (direction >= 0) {
+        while (y2 <= downward_limit) {
+            if (on_screen_only && !found_output && y2 > screen_limit) break;
+            Line *line = range_line_(self, y2);
+            if (line->attrs.prompt_kind == PROMPT_START) {
+                if (!found_prompt) found_prompt = true;
+                else if (found_output && !found_next_prompt) {
+                    found_next_prompt = true; end = y2;
+                    break;
+                }
+            } else if (line->attrs.prompt_kind == OUTPUT_START && found_prompt && !found_output) {
+                found_output = true; start = y2;
+            }
+            y2++;
+        }
+    }
+
+    if (found_next_prompt) {
+        oo->num_lines = end - start;
+    } else if (found_output) {
+        oo->num_lines = (direction < 0 ? start_y : downward_limit) - start;
+    } else return false;
+    oo->start = start;
+    return true;
+}
+
 static PyObject*
-last_cmd_output(Screen *self, PyObject *args) {
+first_cmd_output_on_screen(Screen *self, PyObject *args) {
     if (self->linebuf != self->main_linebuf) return PyUnicode_FromString("");
 
     OutputOffset oo = {.screen=self};
-    unsigned num_lines = 0;
-    int prompt_pos = self->cursor->y, y = self->cursor->y;
-    const int limit = -self->historybuf->count;
-    while (y >= limit) {
-        Line *line = range_line_(self, y);
-        if (line->attrs.prompt_kind == PROMPT_START) prompt_pos = y;
-        if (line->attrs.prompt_kind == OUTPUT_START) {
-            oo.start = y;
-            num_lines = prompt_pos - y;
-            break;
-        }
-        y--;
+    if (find_cmd_output(self, &oo, -self->scrolled_by, 1, true)) {
+        return as_text_generic(args, &oo, get_line_from_offset, oo.num_lines, &self->as_ansi_buf);
     }
-    if (y < limit) {
-        oo.start = limit;
-        num_lines = prompt_pos - limit;
-    } else {
-        // resizing screen can cause multiple consecutive output start lines,
-        // so find the first one
-        while (oo.start > limit) {
-            Line *line = range_line_(self, oo.start - 1);
-            if (line->attrs.prompt_kind != OUTPUT_START) break;
-            oo.start--; num_lines++;
-        }
+    return PyUnicode_FromString("");
+}
+
+static PyObject*
+last_cmd_output(Screen *self, PyObject *args) {
+    if (self->linebuf != self->main_linebuf) return PyUnicode_FromString("");
+
+    OutputOffset oo = {.screen=self};
+    if (find_cmd_output(self, &oo, self->cursor->y, -1, false)) {
+        return as_text_generic(args, &oo, get_line_from_offset, oo.num_lines, &self->as_ansi_buf);
     }
-    return as_text_generic(args, &oo, get_line_from_offset, num_lines, &self->as_ansi_buf);
+    return PyUnicode_FromString("");
 }
 
 
@@ -3622,6 +3697,7 @@ static PyMethodDef methods[] = {
     MND(as_text, METH_VARARGS)
     MND(as_text_non_visual, METH_VARARGS)
     MND(as_text_alternate, METH_VARARGS)
+    MND(first_cmd_output_on_screen, METH_VARARGS)
     MND(last_cmd_output, METH_VARARGS)
     MND(tab, METH_NOARGS)
     MND(backspace, METH_NOARGS)
diff --git a/kitty/window.py b/kitty/window.py
index 267cce63..8e9c2f70 100644
--- a/kitty/window.py
+++ b/kitty/window.py
@@ -1039,6 +1039,11 @@ def as_text(
     ) -> str:
         return as_text(self.screen, as_ansi, add_history, add_wrap_markers, alternate_screen, add_cursor)
 
+    def first_cmd_output_on_screen(self, as_ansi: bool = False, add_wrap_markers: bool = False) -> str:
+        lines: List[str] = []
+        self.screen.first_cmd_output_on_screen(lines.append, as_ansi, add_wrap_markers)
+        return ''.join(lines)
+
     def last_cmd_output(self, as_ansi: bool = False, add_wrap_markers: bool = False) -> str:
         lines: List[str] = []
         self.screen.last_cmd_output(lines.append, as_ansi, add_wrap_markers)
@@ -1072,6 +1077,16 @@ def show_scrollback(self) -> None:
         data = self.pipe_data(text, has_wrap_markers=True)
         get_boss().display_scrollback(self, data['text'], data['input_line_number'])
 
+    @ac('cp', '''
+        Show output from the first shell command on screen in a pager like less
+
+        Requires :ref:`shell_integration` to work
+        ''')
+    def show_first_command_output_on_screen(self) -> None:
+        text = self.first_cmd_output_on_screen(as_ansi=True, add_wrap_markers=True)
+        text = text.replace('\r\n', '\n').replace('\r', '\n')
+        get_boss().display_scrollback(self, text, title='First command output on screen', report_cursor=False)
+
     @ac('cp', '''
         Show output from the last shell command in a pager like less
 
diff --git a/kitty_tests/screen.py b/kitty_tests/screen.py
index ceea3322..c8b84b2f 100644
--- a/kitty_tests/screen.py
+++ b/kitty_tests/screen.py
@@ -957,6 +957,11 @@ def mark_output():
         self.assertTrue(s.scroll_to_prompt())
         self.ae(str(s.visual_line(0)), '$ 0')
 
+        def fco():
+            a = []
+            s.first_cmd_output_on_screen(a.append)
+            return ''.join(a)
+
         def lco():
             a = []
             s.last_cmd_output(a.append)
@@ -965,6 +970,7 @@ def lco():
         s = self.create_screen()
         s.draw('abcd'), s.index(), s.carriage_return()
         s.draw('12'), s.index(), s.carriage_return()
+        self.ae(fco(), '')
         self.ae(lco(), 'abcd\n12')
         s = self.create_screen()
         mark_prompt(), s.draw('$ 0')
@@ -973,4 +979,5 @@ def lco():
         s.draw('abcd'), s.index(), s.carriage_return()
         s.draw('12'), s.index(), s.carriage_return()
         mark_prompt(), s.draw('$ 1')
+        self.ae(fco(), 'abcd\n12')
         self.ae(lco(), 'abcd\n12')
```

</p>
</details>

**Comment by page-down** [comment]
I found that the scroll to prompt function jumps to the first of multiple concatenated prompts. This is due to the need to handle multiple lines of prompt.

However, when multiple commands are executed that do not return output, this results in a jump to a prompt that is not associated with output. When the continuous execution of commands with no output exceeds one screen, it is impossible to see the output of that jump to.

Is it possible to mark the prompt that distinguishes each command execution? I can't think of a way to handle multi-line prompt compatibility at the moment.

> last jumped to command (can be implemented by storing its line number
when jumping)

If the content is cleared beyond the scrollback limit when the output continues, the last jump line number will be incorrect. There are also cases where the window changes size.

I think the most appropriate thing to do in this case is to clear the value. Is there a suitable place to do the dirty check and reset?

**Comment by kovidgoyal** [comment]
On Thu, Nov 04, 2021 at 08:49:40PM -0700, page-down wrote:
> I found that the scroll to prompt function jumps to the first of multiple concatenated prompts. This is due to the need to handle multiple lines of prompt.
> 
> However, when multiple commands are executed that do not return output, this results in a jump to a prompt that is not associated with output. When the continuous execution of commands with no output exceeds one screen, it is impossible to see the output of that jump to.
> 
> Is it possible to mark the prompt that distinguishes each command execution? I can't think of a way to handle multi-line prompt compatibility at the moment.

Not with the current protocol, no. You would need to modify it to have
something like a generation number for each prompt start or alternately
have a way to mark prompt ends. Getting the various shells to do this
reliably will be a fair bit of work. And you will need to modify kitty's
data structures to store this extra information.

Neither is really worth it IMO. Having the jump jump to the first in a
series of prompts without output is not exactly a catastrophic failure.
And executing tons of commands continuously with no output is not 
a common case. Still I wont refuse a patch for it.

> 
> > last jumped to command (can be implemented by storing its line number
> when jumping)
> 
> If the content is cleared beyond the scrollback limit when the output continues, the last jump line number will be incorrect. There are also cases where the window changes size.
> 
> I think the most appropriate thing to do in this case is to clear the value. Is there a suitable place to do the dirty check and reset?

You mean for a resize? You can do that in screen_resize().  I dont think
we need to worry about the line number going off the scrollback buffer.
In this case, just return incorrect output. But if you do want to worry
about it, the pace to add the check is in the INDEX_UP macro.

**Comment by page-down** [comment]
I solved the prompt jump issue, since I expect this function to jump precisely.

But I don't want to introduce unique id, and I agree with you that scrollback should not be the most accurate basis for output. If needed, you should use pipe or redirect stdout, stderr to file in the shell.

**Comment by page-down** [comment]
The features mentioned here have been implemented and merged into the master branch.

https://github.com/kovidgoyal/kitty/pull/4237
https://github.com/kovidgoyal/kitty/pull/4242

**Comment by kovidgoyal** [comment]
I suggest adding another mouse action mouse_show_command_output which opens the clicked on output in a pager.

**Comment by page-down** [comment]
> I suggest adding another mouse action mouse_show_command_output which opens the clicked on output in a pager.

My personal suggestion is to guide the user to achieve the goal by combining and reusing existing features, rather than adding separate mappable actions for each combination.
What do you think?

The following capabilities are already available and can be used immediately. And it's not just limited to command output.

Want to perform a copy operation as well? Hold down Ctrl when releasing the mouse.
Want to open with pager? Hold down Option when releasing the mouse.

```shell
kitty \
    -o 'mouse_map right press ungrabbed mouse_select_cmd_output' \
    -o 'mouse_map ctrl+right release ungrabbed copy_to_clipboard'

kitty \
    -o 'mouse_map right press ungrabbed mouse_select_cmd_output' \
    -o 'mouse_map opt+right release ungrabbed launch --stdin-source=@selection --stdin-add-formatting --type=window less +G -R'
```

I can add it to the documentation if you endorse this approach.

But I think it's a bit hacky to use `release` to get there.
It would be nice if you could refactor it to do something like `combine` when you have some spare time. :)

Of course, if you use combine, you can't select the behavior by modifier keys as you can in the above `release` way.

**Comment by page-down** [comment]
Is it possible to freely configure a certain action to force it to not go to the clipboard? (in Screen -> selections)

This can match any action, and the user can fine-tune the configuration so that, for example, a certain mouse button combination is never automatically copied to the clipboard. This is also not just for command output.

Selections have a unique visual feedback, the user can clearly understand what exactly is selected and then do the next step. I think this makes sense.
Hope you don't mind.

**Comment by kovidgoyal** [comment]
No, there is no such capability. You could add one by adding an extra
field to the selections struct and then adding an extra parameter to the
mouse selection actions to control that. And an extra parameter to the
mouse_select_cmd_output action and whatever other actions create
selections.

**Comment by kovidgoyal** [comment]
Oh and note that using selection for this is not suitable additionally because it does not contain ansi formatting codes and wrap markers.

**Comment by page-down** [comment]
Thanks for the reminder that this is indeed the case.
So, the output range of the clicked command output should be kept as a record and then fetched and used in other actions.
The user can specify the source for "copy to clipboard" and can specify "last clicked command output" for stdin-source.

**Comment by page-down** [comment]
I want to add a special launch, similar to alias, that calls the default pager and can be configured with stdin-source to reduce duplicate launch pager configurations. There should be no such mappable action now, right?

Since the configuration is already starting to get a bit complicated, I don't mind adding a `mouse_show_cmd_output` for quick configuration.

Also, do you prefer to use `cmd` or `command`? I would like to unify the names. Right now the function names in shell-integration.rst also don't match the actual ones.

**Comment by kovidgoyal** [comment]
On Tue, Nov 16, 2021 at 06:57:15PM -0800, page-down wrote:
> I want to add a special launch, similar to alias, that calls the default pager and can be configured with stdin-source to reduce duplicate launch pager configurations. There should be no such mappable action now, right?

Look at kitten_alias, you can create a launch_alias similarly.

> 
> Since the configuration is already starting to get a bit complicated, I don't mind adding a `mouse_show_cmd_output` for quick configuration.

Yes, I think that's a good idea.

> 
> Also, do you prefer to use `cmd` or `command`? I would like to unify the names. Right now the function names in shell-integration.rst also don't match the actual ones.

I dont really care, my slight preference would be for cmd.

**Comment by kovidgoyal** [comment]
In fact I think we can add a default binding of ctrl+shift+right press for mouse_show_cmd_output

**Comment by page-down** [comment]
> The user can specify the source for "copy to clipboard" and can specify "last clicked command output" for stdin-source.

This has been done by reusing the `last visited command output`.

> Look at kitten_alias, you can create a launch_alias similarly.

Thanks. This will be dealt with in a separate PR and will not be discussed here.

> In fact I think we can add a default binding of ctrl+shift+right press for mouse_show_cmd_output

This has been added.

---

I want to add parameters to `mouse_show_command_output` to configure plain text format for stdin. (as_ansi, add_wrap_markers)
Where is the best place to put `options_spec`? (use `kitty/cli.py parse_args` to parse)

**Comment by kovidgoyal** [comment]
On Wed, Nov 17, 2021 at 06:49:58AM -0800, page-down wrote:
> I want to add parameters to `mouse_show_command_output` to configure plain text format for stdin. (as_ansi, add_wrap_markers)
> Where is the best place to put `options_spec`? (use `kitty/cli.py parse_args` to parse)

The various show_command* actions are meant to display in the pager. the
pager has a fixed output format so I dont think they should be
parametrized.

If parametrization is needed it can be done in launch with
--stdin-source

**Comment by page-down** [comment]
> ... the pager has a fixed output format so I dont think they should be
parametrized.

Yes, that's what it's called "scrollback pager".

I should continue the way I mentioned earlier.
Add a new mouse click action to update only the last visited cmd output, without selection, or select with "don't copy" param.
Then pair it with `launch --stdin-source=@last_visited_cmd_output`.

**Comment by kovidgoyal** [comment]
yes, that seems most sensible.

**Comment by page-down** [comment]
> Look at kitten_alias, you can create a launch_alias similarly.

I looked through the code and found that `kitten_alias` is literally `action_alias`.

May I ask if the name should be changed to something more appropriate? Instead of just kitten.

I've done the name change, but I don't know whether kitty should deprecate kitten_alias. So it's better to discuss your opinion here first.

**Comment by kovidgoyal** [comment]
Just leave it around as an alternate name for action_alias for backwards
compat. You can deprecate it in options/definition.py with
add_deprecation()

**Comment by page-down** [comment]
I found that in the commented config, options with `add_to_default=False` cannot be distinguished from the default added ones. The config file generation has recently been improved, so is it appropriate to distinguish it here as well? For example, mark it as `#:`.

```text
#: Those that are not added to default cannot be distinguished.::

# symbol_map U+... PowerlineSymbols
# kitten_alias hints hints --hints-offset=0
...
```

> Just leave it around as an alternate name

Yes, it definitely needs to stay for backward compatibility. `action_alias` will be preferred in future versions. Please correct me if I have misunderstood.

**Comment by kovidgoyal** [comment]
On Fri, Nov 19, 2021 at 08:53:14PM -0800, page-down wrote:
> I found that in the commented config, options with `add_to_default=False` cannot be distinguished from the default added ones. The config file generation has recently been improved, so is it appropriate to distinguish it here as well? For example, mark it as `#:`.

Sure, but maybe better to use:

#:eg:
