### ISSUE TITLE
Kitty use another font for rendering w when using Noto Mono

### ISSUE THREAD

**Issue by ariasuni** [kovidgoyal/kitty#417]
I’m using Kitty 0.8.2 on Arch Linux.

Here is the rendering in Kitty (it doesn’t change whether I let Kitty use default monospace, if I set the font as `monospace` or if I set it to `Noto Mono`):
![screenshot_20180326_192553](https://user-images.githubusercontent.com/2446451/37921997-afaaea9c-312b-11e8-84be-c09650b92ace.png)

Here is the rendering in Konsole for reference:
![screenshot_20180326_192623](https://user-images.githubusercontent.com/2446451/37922007-bb6b914c-312b-11e8-81f2-92da31a0cf17.png)

I don’t have this issue with any GTK, Qt app, Firefox, Thunderbird or LibreOffice, so I guess that’s not a font or fontconfig issue.

**Comment by kovidgoyal** [comment]
dup of #352

**Comment by ariasuni** [comment]
I don’t know why, but today I don’t have this problem anymore. I will report on the linked duplicate if I found why the behavior did change.
