### ISSUE TITLE
Job Control Broken

### ISSUE THREAD

**Issue by YoloClin** [kovidgoyal/kitty#4171]
**Describe the bug**
After a fresh install of Linux, kitty will not close on `exit` after an X application is backgrounded and disowned. On exit, kitty hangs.

Observed on 0.19.x but also recreated on 0.23.1

**To Reproduce**
1.  `./kitty/launcher/kitty --config NONE /bin/bash --noprofile --norc`
2. `/usr/bin/emacs & disown`
3. `exit`
4. shell does not close.

I do see an error message related to dbus - `(emacs:417311): dbind-WARNING **: 19:06:25.471: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.` but similar is not show for other X applications - I can reproduce similar behavior with xeyes.

**Screenshots**

**Environment details**
```
% kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021 x86_64
Ubuntu 21.10 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
Loaded config files: /etc/xdg/kitty/kitty.conf, ~/.config/kitty/kitty.conf
Running under: X11
Linux
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death

**Comment by benjamin051000** [comment]
I was perplexed by this issue until I came across this thread. Would it potentially be wise to either (a) display some kind of warning that kitty won't exit normally until child/disowned process closes its fds, or (b) maybe indicate somewhere in the titlebar that there are still processes using this terminal window despite the shell no longer being in control of any background jobs?
