### ISSUE TITLE
Color terminfo confusion: Co, initp, setab, setaf!

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#4172]
Kitty's terminfo seems very unreliable when it comes to reporting its actual color capabilities.

For the purposes of this issue, I will refer repeatedly to the [`terminfo(5)` manpage](https://invisible-island.net/ncurses/man/terminfo.5.html#h3-Predefined-Capabilities).

Let's consider the case of `Co`, `colors`:

```
$ infocmp -1 | grep colors
	colors#0x100,
```

So, Kitty reports being able to display only 256 colors at a time. (`Co` being `maximum colors on screen`.) Clearly this is not so, Kitty supports truecolor. So, I'd expect:

```
	colors#0x1000000,
```

`initp` is altogether missing, despite the fact that `init_pair` works as expected in ncurses. What?

`setab` and `setaf` contain:

```
$ infocmp -1 | grep seta[bf]
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
```

However, as mentioned, we know it is a fact that Kitty supports truecolor, i.e., `xterm-direct`. So, I'd expect this output instead:

```
$ infocmp xterm-direct -1 | grep seta[bf]
	setab=\E[%?%p1%{8}%<%t4%p1%d%e48\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e38\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m,
```

Perhaps frustrated users of ncurses library aren't to blame for color related bugs in Kitty—that's my opinion upon seeing these terminfo shortcomings.

**Comment by kovidgoyal** [comment]
See the discussion in https://github.com/kovidgoyal/kitty/commit/18fe2e8dfa34038aabd5c3a2fdb3624e2b27932a#diff-3091d3f08f050cbbcda88a41bb4e36fa64179bd14b89d4dfd7ad8c943f47b2f7

To summarize, one cannot have both 256 and direct color support in one
terminfo file.

Frustrated users of the ncurses library have only themselves to blame,
for choosing to use such a bad library.

**Comment by ctrlcctrlv** [comment]
In that case I'm wondering why we can't distribute termcap files like `kitty-256color`, `kitty-direct`? I might end up making some unofficial ones, but am not sure why they can't be in this repository too.

**Comment by kovidgoyal** [comment]
They can be, but what would be the point? Changing the TERM variable is
a dead end approach that is not sustainable. Are we really going to be
expecting users to set TERM before launching different programs?

What actual software do you use that requires a -direct terminfo? And if
there is some I suggest you get it updated to not require one.
