### ISSUE TITLE
Disable dynamic title

### ISSUE THREAD

**Issue by carlosala** [kovidgoyal/kitty#4179]
Hi!

I know that maybe this is a silly question, but I don't find the solution in the documentation.
I am using gnome, and in the window title appears something like `user@host:pathWhereIAm`.
I would like to have just `kitty`, instead of that big string of text.
Is this possible?
Thanks!

**Comment by kovidgoyal** [comment]
Run kitty with --title or configure your shell to set the window title
to whatever you like.
