### ISSUE TITLE
Cursor shape not works proper in git version

### ISSUE THREAD

**Issue by NextAlone** [kovidgoyal/kitty#4182]
**Describe the bug**
Cursor shape not works proper in git version. Configed underline, but show 

**To Reproduce**
1. Just build the latest version

**Screenshots**
git version
![image](https://user-images.githubusercontent.com/12210746/139792021-31800ab4-e2ad-4b4b-9e47-6f24b45012f3.png)
released version
![image](https://user-images.githubusercontent.com/12210746/139792037-69b12c1f-e7f5-4b67-bb91-a86a09907987.png)

**Environment details**
```
kitty 0.23.1 (46625d207b) created by Kovid Goyal
Linux next 5.14.15-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 27 Oct 2021 23:38:11 +0000 x86_64
Arch Linux 5.14.15-zen1-1-zen (pts0)

LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Frozen: False
Paths:
  kitty: /home/nextalone/Downloads/kitty/kitty/launcher/kitty
  base dir: /home/nextalone/Downloads/kitty
  extensions dir: /home/nextalone/Downloads/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/nextalone/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       y
background_opacity         0.7
copy_on_select             clipboard
cursor_blink_interval      0.0
cursor_shape               3
cursor_stop_blinking_after 0
disable_ligatures          1
enable_audio_bell          False
font_family                Fira Code Light
font_size                  12.0
linux_display_server       x11
mouse_hide_wait            -1.0
remember_window_size       False
scrollback_lines           4294967295
strip_trailing_spaces      smart
window_padding_width       FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Added shortcuts:
	shift+super+w KeyAction('close_os_window')
Colors:
	background                 #2e3440   
	color0                     #3b4252   
	color1                     #bf616a   
	color10                    #a3be8c   
	color11                    #ebcb8b   
	color12                    #81a1c1   
	color13                    #b48ead   
	color14                    #8fbcbb   
	color15                    #eceff4   
	color2                     #a3be8c   
	color3                     #ebcb8b   
	color4                     #81a1c1   
	color5                     #b48ead   
	color6                     #88c0d0   
	color7                     #e5e9f0   
	color8                     #4c566a   
	color9                     #bf616a   
	cursor                     #81a1c1   
	foreground                 #d8dee9   

```

config

```
cursor #cccccc
cursor_text_color #111111
cursor_shape underline
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_stop_blinking_after 0
```
**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
The unreleased version comes with a new Shell Integration feature. This is done by adding to your shell rc file and changing the cursor to bar by default when using the shell. This behavior can be turned off by adding the `no-cursor` option to shell_integration in the configuration.

---

However, I think the `cursor_shape` option has lost its meaning in the case of using a shell, since this configuration will be useless(with the supported shell) whenever shell integration is enabled by default, no matter how the user configures it.

This definitely adds confusion rather than respecting options that already existed in previous versions and were configured by the user.

I would prefer to pursue a clear and unambiguous approach for kitty configuration.

As more and more config options become available, the complexity of various combinations of different configurations increases.

**Comment by kovidgoyal** [comment]
cursor_shape never applied to programs running in the terminal as they
could always override the cursor shape. The only change now is that
this will happen more frequently because of shell configuration and the
documentation for cursor_shape has already been updated to point that
out.

**Comment by NextAlone** [comment]
i tried change this option to `no-cursor`, and found the file `shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish` didn't install with aur PKGBUILD. Now everything works fine. Thanks for your work. 

So with this feature enable, how to change cursor inside shell 

i also find that the config now seems complex

**Comment by page-down** [comment]
> cursor_shape never applied to programs running in the terminal as they could always override the cursor shape. 

Thanks for pointing that out, it makes sense.

> So with this feature enable, how to change cursor inside shell

You need to disable the feature and then manually load the integration script. In the case of the fish shell, it is one environment variable, or two symlinks.

Look at the no-cursor related code in the file you pointed out and write your own shell config.

https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
```text
CSI Ps SP q
          Set cursor style (DECSCUSR), VT520.
```

**Comment by NextAlone** [comment]
> > cursor_shape never applied to programs running in the terminal as they could always override the cursor shape.
> 
> Thanks for pointing that out, it makes sense.
> 
> > So with this feature enable, how to change cursor inside shell
> 
> You need to disable the feature and then manually load the integration script. In the case of the fish shell, it is one environment variable, or two symlinks.
> 
> Look at the no-cursor related code in the file you pointed out and write your own shell config.
> 
> https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
> 
> ```
> CSI Ps SP q
>           Set cursor style (DECSCUSR), VT520.
> ```

ok, i'll have a look, thanks

**Comment by page-down** [comment]
@NextAlone 
> ok, i'll have a look, thanks

Actually, just write `shell_integration enabled no-cursor` in the configuration, you don't need to disable it completely. Then just add a script to `.config/fish/conf.d` that changes the cursor shape.

.config/fish/conf.d/custom-cursor.fish
```fish
function __cursor_underline --on-event fish_prompt
    printf "\e[3 q"
end
function __cursor_block --on-event fish_preexec
    printf "\e[2 q"
end
```

> the documentation for cursor_shape has already been updated to point that out

The documentation mentions `shell_integration sets cursor shape to bar at shell prompts`, and I thought `bar` was an alias for `beam`.

`2:Invalid cursor shape: bar allowed values are block, beam, underline in line: cursor_shape bar`

Here it obviously means the shape of the cursor, not the value of the option variable.
I don't think anyone would be curious enough to set it to `bar`. :)
