### ISSUE TITLE
Can't paste in some situations when using Wayland

### ISSUE THREAD

**Issue by mdeneen** [kovidgoyal/kitty#4183]
**Describe the bug**
Paste function does not always paste

**To Reproduce**
1. Copy from a Wayland application, such as Geany
2. run wl-paste, you can see that the contents are in the buffer
3. Try to paste into Kitty (nothing happens)

**Screenshots**
Copying:
![image](https://user-images.githubusercontent.com/1242848/139875117-c5333fb3-3caa-4e47-9216-9659f05aab90.png)

Attempting to paste (nothing happens) and you can see the contents with wl-paste
![image](https://user-images.githubusercontent.com/1242848/139875269-b5bd400f-3bcb-424f-b387-6a9580c3c4b2.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux mdeneen 5.14.15-arch1-1 #1 SMP PREEMPT Wed, 27 Oct 2021 23:38:14 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:Wayland
Loaded config files:
  /home/mdeneen/.config/kitty/kitty.conf

Config options different from defaults:
term xterm-256color

```

**Additional context**

Using wl-copy within kitty and then pasting will work until a selection is copied in Geany, at which point nothing happens when I paste.  Executing ```wl-paste | wl-copy``` allows me to paste the content which was previously copied in Geany.

![image](https://user-images.githubusercontent.com/1242848/139879277-8183999c-2a5b-41f5-8169-cb1be988e2b1.png)

Copying data from geany to other Wayland terminal emulators, such as gnome-terminal, works as expected.

I also noticed that when copying from geany, the offered types are:

```
wl-paste -l
STRING
UTF8_STRING
```

but when copying from Kitty itself, these types are offered:

```
UTF8_STRING
STRING
TEXT
text/plain;charset=utf-8
text/plain
application/glfw+clipboard-36277
```

I have a feeling that this is the root of my problem.

Incidentally, STRING/UTF8_STRING are the only offers from Java-based applications as well.  These Java applications also do not paste into Kitty.

**Comment by mdeneen** [comment]
The plain text mime type for working pastes is "text/plain;charset=utf-8", and the mime type from Java / Geany is simply "text/plain".

**Comment by mdeneen** [comment]
Thanks, @kovidgoyal !

**Comment by mdeneen** [comment]
I hate to bring this up again, but I still can't copy and paste with this change.  I added some debug code to wl_window.c and it looks like, while looping through the offers, there is a clipboard offer type with a null mime type and a primary selection offer type with a `text/plain;charset=utf-8` mime type.

The following is the output of `id`, `offer_type`, and `plain_text_mime` in that loop after copying text in dbeaver (java-based database tool)

```
(nil), 0, (null)
0x56226f58c8e0, 1, (null)
0x56226edb9300, 3, text/plain;charset=utf-8
(nil), 0, (null)
(nil), 0, (null)
(nil), 0, (null)
(nil), 0, (null)
(nil), 0, (null)
```

Prior to your change the output looked like this:

```
0x5589dfd0a440, 1, text/plain
```

**Comment by kovidgoyal** [comment]
Should be fine now.

**Comment by mdeneen** [comment]
Thanks, @kovidgoyal, I can confirm that this works as expected!
