### ISSUE TITLE
What Color Is This?

### ISSUE THREAD

**Issue by wgmayer0** [kovidgoyal/kitty#4184]
I cannot tell what color in the kitty.conf file controls the color of the white bar in vifm running fzf:
![1635912700](https://user-images.githubusercontent.com/73801421/140009108-d5372fd1-daad-4952-bb74-a822e8e8e4e4.png)

**Comment by wgmayer0** [comment]
Also I do not want the top bar to be white but when I change color7 to black, it changes the top bar and all of the bolded text. xterm doesn't do this.

![1635912700](https://user-images.githubusercontent.com/73801421/140009169-0555fe53-c61d-4a43-9262-db9dc6f9b088.png)

**Comment by kovidgoyal** [comment]
You'd have to ask the developers of vifm or do a binary search on
kitty.conf changing the colors one by one.

**Comment by wgmayer0** [comment]
In bash, I get this:

What color is this in ls? Are you sure this is not kitty defined

**Comment by kovidgoyal** [comment]
ls's colors come from the LC_COLORS environment variable not the
terminal emulator.
