### ISSUE TITLE
colour updating issue on vim with certain colour theme

### ISSUE THREAD

**Issue by xiangpeng2008** [kovidgoyal/kitty#4186]
**Describe the bug**
With [dracula-theme](https://github.com/dracula/dracula-theme) them in vim. I get strange colour updating behaviour: as we could see when I paste block, the background colour is not well updated: some of the new lines are "deep dark".
![kitty](https://user-images.githubusercontent.com/15676035/140036073-63104657-f49a-4c72-8fee-bcc3264efa4c.gif)

I don't have this problem on native Mac terminal.

**To Reproduce**
1. open vim in kitty
2. install dracula-theme `Plug 'dracula/vim', { 'as': 'dracula' }` 
3. enable it `colorscheme dracula`
4. pasting multiple times lines of codes 

**Environment details**
```
kitty 0.23.1 (68ad513dd5) created by Kovid Goyal
Darwin 35.8.126.129.static.m1net.com.sg 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.0.1 BuildVersion:	21A559
Frozen: False
Paths:
  kitty: /Users/xiangpeng/Documents/kitty/kitty.app/Contents/MacOS/kitty
  base dir: /Users/xiangpeng/Documents/kitty/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/xiangpeng/Documents/kitty/kitty.app/Contents/Resources/kitty/kitty
  system shell: /opt/homebrew/bin/bash
Loaded config files:
  /Users/xiangpeng/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control     y
confirm_os_window_close  3
enabled_layouts          ['splits', 'tall']
font_size                14.0
listen_on                unix:/tmp/mykitty
macos_option_as_alt      3
scrollback_pager         ['nvim', '-u', 'NONE', '-c', 'set nonumber nolist showtabline=0 foldcolumn=0 laststatus=0', '-c', 'autocmd TermOpen * normal G', '-c', 'map q :qa!<CR>', '-c', 'set clipboard+=unnamedplus', '-c', 'silent write! /tmp/kitty_scrollback_buffer | te echo -n "$(cat /tmp/kitty_scrollback_buffer)" && sleep 1000 ']
tab_bar_edge             1
tab_bar_style            slant
tab_title_template       {fmt.fg.red}{index}{fmt.fg.default} {title}
window_border_width      (1.0, 'px')
window_resize_step_cells 1
window_resize_step_lines 1
Added shortcuts:
	alt+n KeyAction('show_scrollback')
	alt+p KeyAction('focus_visible_window')
	alt+t > 0 KeyAction('move_window_to_top')
	alt+t > _ KeyAction('launch', ('--location=hsplit',))
	alt+t > | KeyAction('launch', ('--location=vsplit',))
```

**Additional context**
I reported equally in theme repo https://github.com/dracula/dracula-theme/issues/645#issue-1043272595

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim.

**Comment by xiangpeng2008** [comment]
adding `let &t_ut=''` solves .vimrc solves exactly my issue.

**Comment by benknoble** [comment]
Check your `$TERM` environment variable. It needs to match the capabilities of the terminal you use. So, _e.g._, if it says `xterm-256color` but Kitty is not 100% compatible with that protocol, you might want to have Kitty set a different value (and/or compile a Kitty-specific terminfo file).

Or you could litter your configs with stuff like "if on Kitty, set this special terminal sequence to this special value," but that's the whole point of `TERM` and terminfo. Plus, how are you going to detect Kitty without `TERM`?

**Comment by Luflosi** [comment]
He already wrote that he resolved his issue. The FAQ entry I linked above also mentions the TERM environment variable.
