### ISSUE TITLE
bad image display behaviour after resizing window

### ISSUE THREAD

**Issue by xiangpeng2008** [kovidgoyal/kitty#4187]
**Describe the bug**

After `kitty +kitten icat path/image.png`, and change whole kitty window size. The position of image changes vertically.

**To Reproduce**
1. enter full screen mode of kitty APP window
2. open multiple kitty windows
3. `kitty +kitten icat path/image.png` in one of kitty windows
4. 
<img width="844" alt="Screenshot 2021-11-03 at 5 34 52 PM" src="https://user-images.githubusercontent.com/15676035/140037969-3d58afe1-a6de-4461-835d-f27ad4f96bf6.png">

4. quite full screen mode 
<img width="812" alt="Screenshot 2021-11-03 at 5 35 24 PM" src="https://user-images.githubusercontent.com/15676035/140037938-bde5cbe1-01a1-4b10-9c32-a7de84e7afbb.png">
 

**Environment details**
```
kitty 0.23.1 (68ad513dd5) created by Kovid Goyal
Darwin 35.8.126.129.static.m1net.com.sg 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.0.1 BuildVersion:	21A559
Frozen: False
Paths:
  kitty: /Users/xiangpeng/Documents/kitty/kitty.app/Contents/MacOS/kitty
  base dir: /Users/xiangpeng/Documents/kitty/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/xiangpeng/Documents/kitty/kitty.app/Contents/Resources/kitty/kitty
  system shell: /opt/homebrew/bin/bash
Loaded config files:
  /Users/xiangpeng/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control     y
confirm_os_window_close  3
enabled_layouts          ['splits', 'tall']
font_size                14.0
listen_on                unix:/tmp/mykitty
macos_option_as_alt      3
scrollback_pager         ['nvim', '-u', 'NONE', '-c', 'set nonumber nolist showtabline=0 foldcolumn=0 laststatus=0', '-c', 'autocmd TermOpen * normal G', '-c', 'map q :qa!<CR>', '-c', 'set clipboard+=unnamedplus', '-c', 'silent write! /tmp/kitty_scrollback_buffer | te echo -n "$(cat /tmp/kitty_scrollback_buffer)" && sleep 1000 ']
tab_bar_edge             1
tab_bar_style            slant
tab_title_template       {fmt.fg.red}{index}{fmt.fg.default} {title}
window_border_width      (1.0, 'px')
window_resize_step_cells 1
window_resize_step_lines 1
Added shortcuts:
	alt+n KeyAction('show_scrollback')
	alt+p KeyAction('focus_visible_window')
	alt+t > 0 KeyAction('move_window_to_top')
	alt+t > _ KeyAction('launch', ('--location=hsplit',))
	alt+t > | KeyAction('launch', ('--location=vsplit',))

```

**Additional context**

This looks not easy to fix, and it's not a problem unless we change often window size. So please give low priority.

**Comment by kovidgoyal** [comment]
the position of images after resize is not defined. Someday I might
extend the graphics protocol to define it, but there are various
complications with doing so, if you search you will find the relevant
discussions.
