### ISSUE TITLE
screen clear ought hide graphics, not delete them

### ISSUE THREAD

**Issue by dankamongmen** [kovidgoyal/kitty#4189]
**Is your feature request related to a problem? Please describe.**
When I issue a screen clear, all graphics in the cache are deleted, as suggested by the spec and #33. While I agree that the clear semantics ought hide all graphics, actually deleting them seems a bit much, and makes it difficult to do a "refresh". For instance, let's say I have a scene up with a graphic. A message from the kernel comes in, resulting in some scrolling and other damage. The user presses ctrl+'L' to force a redraw. I clear the screen, and would ideally just re-'p'resent the expected images. Due to these semantics, I must instead reload and then re-present them.

**Describe the solution you'd like**
A screen clear (`\e[H\e[2J` in kitty) ought hide on-screen graphics rather than deleting them. A full terminal reset should probably continue to clear the cache--I certainly have no problem with that behavior.

**Describe alternatives you've considered**
I must otherwise (a) refrain from clearing the screen on such a redraw or (b) ensure I keep a copy of all source graphics around after loading them. If i don't perform a true clear, certain pathological cases can lead to an incomplete refresh.

An alternate control sequence that cleared only text is i think strange--the current clear has the semantics right, display-wise--and doesn't help me if the graphic has been scrolled outside of my control.

**Additional context**
It's not of critical importance or anything, but it would be nice, unless I'm missing some other way to handle this. If worst comes to worst, I can keep a copy of the graphic for reloading.

This bug arose in Notcurses issue 1948: https://github.com/dankamongmen/notcurses/issues/1948.

**Comment by kovidgoyal** [comment]
As a user I definitely dont want the clear command run at a shell to leave any images residing in memory where I have no way to even delete them, since they were put there by some now exited program. 

Note that 2J clears all images from the screen and 3J clears them from screen and scrollback. 

What you are asking for is a way to clear the screen of text and hide the graphics. You can do that by using 1J and then 0J instead of 2J, then using a graphics delete command to achieve exactly the delete semantics you need.

**Comment by dankamongmen** [comment]
awesome, i wasn't aware of 1J/0J (i don't see them in the terminfo database), thanks! yes that will work perfectly.

**Comment by kovidgoyal** [comment]
yes they are not in terminfo, but they are defined for the VT100 https://vt100.net/docs/vt510-rm/ED.html
