### ISSUE TITLE
Unrecognized DCS and CSI code when opening python files with XDG-open

### ISSUE THREAD

**Issue by isak102** [kovidgoyal/kitty#4191]
**Describe the bug**
When I try to open a .py file with xdg-open (my default editor is VIM) it spawns two terminals, one terminal with an error message as shown in the screenshot and one teminal with the file im trying to open. Xdg-open seems to be working as expected on other text files that arent python files. 

**To Reproduce**
1. use xdg-open to open a python file
2. See error

**Screenshots**
![Screenshot of the bug](https://user-images.githubusercontent.com/90389894/140356266-58c0393b-27c9-4ba8-bfb7-9627409ea391.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux ACER3ISAK 5.14.15-arch1-1 #1 SMP PREEMPT Wed, 27 Oct 2021 23:38:14 +0000 x86_64
Arch Linux \r (\l)
Running under:X11
Loaded config files:
  /home/isak102/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.4
enable_audio_bell    False
font_family          Cascadia Mono SemiBold
font_size            16.0
window_padding_width FloatEdges(left=3.0, top=3.0, right=3.0, bottom=3.0)

```

**Comment by kovidgoyal** [comment]
Presumably you have configured your default application for vim as kitty kitty vim rather than kitty vim

**Comment by isak102** [comment]
Can you help me and describe what you mean? My vim.desktop is the default one and as  I said it works fine with kitty in everything but python files so I don't really understand what you mean

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. You need to figure out why xdg-open
is running

kitty kitty vim file.py

instead of

kitty vim file.py

on your system.
