### ISSUE TITLE
Malayalam is not rendering properly in kitty

### ISSUE THREAD

**Issue by AbhinavKDev** [kovidgoyal/kitty#4194]
**Describe the bug**
Malayalam is not rendering properly

**To Reproduce**
past some malayalam text in kitty

**Screenshots**
![2021-11-05-171108_1920x1080_scrot](https://user-images.githubusercontent.com/62714538/140505406-029eeef7-ebdf-453e-9c10-e80569bfcf03.png)

**Comment by kovidgoyal** [comment]
dup of #3045

**Comment by cshintov** [comment]
is there any terminal out there that renders malayalam and other indic languages proper? iterm2 also doesn't work.

**Comment by pratikmullick** [comment]
> is there any terminal out there that renders malayalam and other indic languages proper? iterm2 also doesn't work.

AFAIK, only Konsole has support for Indic font rendering.
