### ISSUE TITLE
CMake output not in color

### ISSUE THREAD

**Issue by BigfootN** [kovidgoyal/kitty#420]
Hello,

I just switched from urxvt to kitty, and I really love it. Everything works great, but the only problem is that when compiling with cmake, the output isn't in color (only in black and white). It works perfectly under urxvt.

System information:
Distribution: `Archlinux`
Kernel: `4.15.12-1-ARCH`
Kitty version: `0.8.2`

The kitty configuration is exactly the same as the default one, except the colors:

```
background_opacity 1.0

background #262626
foreground #ebdbb2
# Black + DarkGrey
color0  #282828
color8  #928374
# DarkRed + Red
color1  #cc241d
color9  #fb4934
# DarkGreen + Green
color2  #98971a
color10 #b8bb26
# DarkYellow + Yellow
color3  #d79921
color11 #fabd2f
# DarkBlue + Blue
color4  #458588
color12 #83a598
# DarkMagenta + Magenta
color5  #b16286
color13 #d3869b
# DarkCyan + Cyan
color6  #689d6a
color14 #8ec07c
# LightGrey + White
color7  #a89984
color15 #ebdbb2
# }}}
```

And I also modified the font:

```
font_family      Iosevka Term Compressed
font_size         19.0
```

Thank you very much in advance for any help.

**Comment by kovidgoyal** [comment]
That's a bug in cmake. It probably hardcodes color detection based on TERM values. You should open a  bug report with them to add xterm-kitty as a TERM that cmake recognizes. And you can workaround it by doing

```
TERM=xterm-256color make
```

Note that you should not change kitty's TERM value even though you can do so in the config file, as this will cause other, properly designed terminal applications to fail.

**Comment by BigfootN** [comment]
Thank you very much for your help.

**Comment by samcoult** [comment]
For those coming from google, cmake acknowledges xterm-kitty as a colour term in version 3.12 onwards.
