### ISSUE TITLE
Option to set the number of columns and lines when launching kitty from another terminal or shortcut

### ISSUE THREAD

**Issue by PoisonFrog** [kovidgoyal/kitty#4213]
I tried to find an option to choose the number of lines and columns in the man page and tried to search on the internet but couldn't find anything. I know you can set this in kitty.conf but I use kitty to launch ncmpcpp, nvim, ranger and other apps using shortcuts and I want to open kitty with a different number of lines and columns in each of them. I tried devilspie2 and it kinda works, but it's not that great because when devilspie2 resizes your windows it messes up with the positioning set up by your window manager and now you also have to use devilspie2 to position windows.

Honestly, it's not a big deal, but it would be nice if this feature could be added to kitty or even better if it already exists and I just could not find it.

**Comment by kovidgoyal** [comment]
You can specify any setting form kitty.conf on the command line with
--override

And there are settings in kitty.conf to select initial window size.
