### ISSUE TITLE
Control kitty from scripts - ValueError

### ISSUE THREAD

**Issue by kuntiik** [kovidgoyal/kitty#4217]
**Describe the bug**
Kitty fails to launch a new window after series of commands:
```
kitty -o allow_remote_control=yes -o enabled_layouts=tall  // Opens new kitty terminal 
kitty @ launch --title Output --keep-focus cat

```

**To Reproduce**
I have a clean installation of kitty installed via `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin`.
I open a new terminal using `kitty -o allow_remote_control=yes -o enabled_layouts=tall`  and in the terminal run following command `kitty @ launch --title Output --keep-focus cat`
**Screenshots**
![image](https://user-images.githubusercontent.com/43137698/141010204-d5a4636e-2c58-4d2d-9f6f-8bb182bb1503.png)
**Environment details**
```
kitty 0.23.1 (cd7b4fcd8e) created by Kovid Goyal
Linux kuntik 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64
Ubuntu 20.04.3 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Running under:X11
Loaded config files:
  /home/kuntik/.config/kitty/kitty.conf
Loaded config overrides:
  allow_remote_control yes
  enabled_layouts tall

Config options different from defaults:
allow_remote_control y
enabled_layouts      ['tall']

```

**Comment by kovidgoyal** [comment]
Something in your environment is setting the KITTY_LISTEN_ON env var to an invalid value. Find what that is and stop it from doing so.
