### ISSUE TITLE
Image preview in tmux

### ISSUE THREAD

**Issue by ibeex** [kovidgoyal/kitty#422]
Hi,
System:    Host: Kernel: 4.15.13-1-ARCH x86_64 bits: 64 Console: tty 5 Distro: Arch Linux
Display Server: X.org 1.19.6 driver: modesetting unloaded: fbdev,intel,vesa tty: 213x57
tmux 2.6
Reproducing problem:
inside tmux start
```shell
$ kitty icat ~/Dropbox/Shitbull_by_stane.jpg
Terminal does not support reporting screen sizes via the TIOCGWINSZ ioctl
```

**Comment by kovidgoyal** [comment]
dup of #413
