### ISSUE TITLE
Weird behavior over ssh with zsh-autosuggestions

### ISSUE THREAD

**Issue by xeruf** [kovidgoyal/kitty#4224]
**Describe the bug**

When I use ssh into a remote running zsh via kitty, I get weird artifacts.
I suspect it to be related to https://github.com/zsh-users/zsh-autosuggestions

Here I only typed `echo test` and then `ech`:
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/13354331/141354993-a00c021b-0c01-4886-a263-c0391a7b28c5.png">

Note that this happens only in Kitty, here for example Konsole:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/13354331/141348397-c72c2b6e-10c4-4535-8bcf-7c9763baabb0.png">

A video best illustrates this fully:
https://user-images.githubusercontent.com/13354331/141348316-16874901-248d-4c59-8db9-08162c7031ae.mp4

**To Reproduce**
1. Install zsh and zsh-autosuggestions on a remote server
2. SSH into it from Kitty
3. Type

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux elephant-arch 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  /home/janek/.config/kitty/kitty.conf
```

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/faq/

Please check the faq for solutions to ssh-related problems and see if this solves your problem.

**Comment by xeruf** [comment]
`kitty +kitten ssh` works. Is this not possible without modifying the host? This feels weird.

**Comment by page-down** [comment]
Basically, you only need to install it once, you don't need to run it every time. You can see my answer at the following GitHub Discussion link.

https://github.com/kovidgoyal/kitty/discussions/4223
