### ISSUE TITLE
Is there an option to disable the `unicode_input` shortcut on macOS?

### ISSUE THREAD

**Issue by heygarrett** [kovidgoyal/kitty#4227]
I can't figure how to use the macOS emoji picker with the default shortcut `cmd+ctrl+space` because kitty uses the same shortcut for `unicode_input`. I searched both the documentation and the issues here, but I haven't been able to find a workaround.

**Comment by Luflosi** [comment]
You can disable it by mapping the keyboard shortcut to `no-op` but this won't help you because the macOS emoji picker doesn't work in kitty since support for it hasn't yet been implemented.

**Comment by heygarrett** [comment]
Ah, okay. Thank you.
