### ISSUE TITLE
Tabs sometimes fail to close

### ISSUE THREAD

**Issue by durka** [kovidgoyal/kitty#4228]
**Describe the bug**
Sometimes, tabs fail to close even when the underlying shell does. That is, I'll type exit or press Ctrl-D, but the tab remains open. See below:

![image](https://user-images.githubusercontent.com/47007/141599079-86f0ca17-2a42-4223-a6be-9bf6791be4ec.png)

Because there's no GUI to close or move a tab, I'm stuck, so this is super annoying.

**Environment details**
Ctrl-shift-F6 just prints some escape sequences in the terminal.
```
$ kitty --debug-config
kitty 0.18.3 created by Kovid Goyal
Linux burkapad 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64
Ubuntu 20.10 \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/alex/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
allow_remote_control  y
font_family           Ubuntu Mono with Numderline
font_size             12.0
update_check_interval 0.0
Added shortcuts:
	control+page_up KeyAction(func='previous_tab', args=())
	control+page_down KeyAction(func='next_tab', args=())
Changed shortcuts:
	shift+control+0 KeyAction(func='kitten', args=['reload.py'])
	shift+control+s KeyAction(func='set_tab_title', args=())
```

**Additional context**
This is not reproducible even with my config as it is so it's hard to debug further or see what effect configuration has. I have some of the frozen tabs open now and I rarely reboot my computer so let me know if there is anything I can glean from the running process.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death
