### ISSUE TITLE
os x "Cannot read termcap database" and "Cannot open terminfo database file"

### ISSUE THREAD

**Issue by winmillwill** [kovidgoyal/kitty#423]
I got the termcap error for things like `cat` and the terminfo error for `emacsclient`.

I followed the directions for passing the terminfo to a remote host, and that solved my issue, so it seems that the terminfo inside the app Resources directory is somehow inscrutable to emacsclient. This could easily be a bug on the emacs side, but I'm not sure about `cat`.

**Comment by kovidgoyal** [comment]
The way to test if terminfo is accessible is to run infocmp. If it outputs the terminal description, it is accessible. If it does not then you have to install it. On local machines it is always accessible, since kitty sets the TERMINFO env var to its location, unless you override the TERMINFO env var in your shell startup scripts.

**Comment by kovidgoyal** [comment]
As for emacsclient, presumably it is not passing the TERMINFO env var to the server process. So either it needs to be fixed ortr you can workaround it by installing kittys terminfo files system wide or in ~/.terminfo

**Comment by winmillwill** [comment]
Interesting. I can see that TERMINFO does point to the file in the App directory, and infocmp is clearly working since that's how I did the workaround. I'm still not sure this explains why something simple like `cat` would throw an error without updating ~/.terminfo.

**Comment by kovidgoyal** [comment]
I'd be amazed if cat read terminfo at all, I doubt very much that cat cares enough about terminals for that. I cant see any references to terminfo in cat's source code: https://opensource.apple.com/source/text_cmds/text_cmds-87/cat/cat.c

**Comment by neverfox** [comment]
I'm having this problem too whenever I run the `brew upgrade` or `brew cask upgrade` commands (i.e. Homebrew). Given that these are such common commands to run, it comes up a lot. I have no trouble running infocmp and getting back info the xterm-kitty description.

**Comment by neverfox** [comment]
Solved. See #310.

**Comment by bfad** [comment]
This was resolved for me by starting the Emacs daemon from a kitty terminal.

**Comment by exoticus** [comment]
@bfad nope doesn't work, @neverfox no it isn't solved i still get this with emacs/brew

**Comment by neverfox** [comment]
@exoticus Well, that was a long time ago and things change. Did you try to suggested `ln -s /Applications/kitty.app/Contents/Frameworks/kitty/terminfo ~/.terminfo` that I used at the time? I haven't had the issue recur since.
