### ISSUE TITLE
transmission-cli's output is "corrputed"

### ISSUE THREAD

**Issue by moosotc** [kovidgoyal/kitty#4231]
Reproducer:
#include <stdio.h>

int main (void)
{
    printf ("\r%-*s", 80, "string 1");
    printf ("\r%-*s", 80, "string 2");
}

**Comment by kovidgoyal** [comment]
Doesn't reproduce for me, running in an 80 cell kitty window I see a
single line with string 2 on it, as expected. You are going to have to
provide more details on what your problem is.

**Comment by moosotc** [comment]
Kovid Goyal ***@***.***> writes:

> Doesn't reproduce for me, running in an 80 cell kitty window I see a
> single line with string 2 on it, as expected. You are going to have to
> provide more details on what your problem is.
>

- cd tmp/c
- cat ./kit.c 
#include <stdio.h>

int main (void)
{
    printf ("\r%-*s", 80, "string 1");
    printf ("\r%-*s", 80, "string 2");
}
- clang -Weverything -Werror -o kit kit.c
- ./kit
string 1
string 2
%
- cd ~/x/rcs/git/kitty 
- git describe --tags
nightly-5-g181178b0
-

system is uptodate arch linux. Configuration files at:
https://github.com/moosotc/snippets/

**Comment by kovidgoyal** [comment]
Still does not reproduce for me. If you have a window that is 80 cells wide, it prints a single line, if you have a window that is less than 80 cells wide it prints two lines, as expected. Check the output of tput cols to see how many cells are in your window.

**Comment by moosotc** [comment]
Kovid Goyal ***@***.***> writes:

> Still does not reproduce for me. If you have a window that is 80 cells
> wide, it prints a single line, if you have a window that is less than
> 80 cells wide it prints two lines, as expected. Check the output of
> tput cols to see how many cells are in your window.
>

Thanks, 'tput cols' does indeed report 74.

**Comment by moosotc** [comment]
(For posterity) I suppose hard-coded LINEWIDTH 80 in
https://github.com/transmission/transmission/blob/254d837ddf84e8254f9106bae2f337db028f25af/cli/cli.cc#L65
is really the culprit here.
