### ISSUE TITLE
Cursor doesn't blink inside Vim

### ISSUE THREAD

**Issue by chdiza** [kovidgoyal/kitty#4234]
**Describe the bug**
The cursor blinks in Kitty when I'm not running Vim, but as soon as I'm in Vim it stops blinking.

**To Reproduce**
1. `kitty --config NONE`  (kitty version 0.23.1 on Ubuntu 20.04)
2. Observe a blinking cursor at the shell prompt.
3. `vim -u NONE`
4. Observe the cursor failing to blink.

**Environment details**
```
kitty 0.23.1 (cd7b4fcd8e) created by Kovid Goyal
Linux somehostname 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64
Ubuntu 20.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
Running under:X11

Config options different from defaults:
```

**Additional context**
Kitty is the only terminal on my machine that does this.  Uxterm, konsole, and tilix all blink in Vim.  Sakura blinks neither at the shell prompt nor in Vim.

Also, once I quit Vim, kitty goes right back to blinking the cursor.

**Comment by chdiza** [comment]
On a lark, I set aside this version of kitty and tried 0.15.0, which is what `apt` will install.  On that older kitty, there is no problem with blinking inside Vim.

**Comment by chdiza** [comment]
Possibly related: If I start kitty from uxterm so that it doesn't fork, then when I start Vim in kitty, the following gets shown in uxterm:

```
[317 15:27:07.991618] [PARSE ERROR] Unrecognized DCS code: 0x7a
[317 15:27:07.991636] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '' and end_modifier: '%' and parameters: '0'
```
Perhaps kitty is choking on Vim's attempts to detect terminal capabilities?

**Comment by kovidgoyal** [comment]
dup of #3906

**Comment by chdiza** [comment]
I'm confused as to how this is a dupe.  What does the present report have to do with tmux?

Is the idea that this is somehow a bug in Vim?  Every other terminal I've tried that has a blinking cursor retains the blink inside of Vim.

**Comment by kovidgoyal** [comment]
As does kitty. In fact I am typing this response in vim, in kitty, with
a blinking cursor. Just make sure you are running kitty version before that
bug was introduced or kitty versions after it was fixed. And as a bonus,
here is what you should have in vimrc for the best editing experience
with kitty:

```vim
if $TERM == "xterm-kitty"
    set mouse=a
    try
        " undercurl support
        let &t_Cs = "\e[4:3m"
        let &t_Ce = "\e[4:0m"
    catch
    endtry
    " Change the cursor in different modes
    let &t_SI = "\e[5 q"
    let &t_SR = "\e[3 q"
    let &t_EI = "\e[1 q"
    " vim hardcodes background color erase even if the terminfo file does
    " not contain bce. This causes incorrect background rendering when
    " using a color theme with a background color.
    let &t_ut=''
endif
```

**Comment by chdiza** [comment]
Thank you.  I copied the `t_SI`, `t_SR`, and `t_EI` settings into my vimrc.

Now in Vim there is no blinking cursor until I enter insert mode, after which it starts blinking, and it remains blinking after going back to normal mode.  Is there a way to have the blinking active when vim first starts up?  Otherwise Vim has the appearance of being frozen.  (Plus it's hard to see where the cursor is if I've told Vim to open a file at a certain line.)

Sorry for the simple questions!  I've been vimming for 16 years and never had to set any "t_" business for anything cursor-related before, so this is all new to me.   (Then again, I suppose `&term` for me has always been either `xterm-{,256}color` or `builtin_gui`.)

**Comment by kovidgoyal** [comment]
```vim 
let &t_ti = &t_ti . "\e[1 q"
```

**Comment by chdiza** [comment]
`let &t_ti = &t_ti . "\e[1 q"`

Thanks, but that doesn't seem to work over here.

**Comment by chdiza** [comment]
> Thanks, but that doesn't seem to work over here.

This indeed doesn't work on Ubuntu, but it *does* work on macOS.  I wonder if there's a bug in the Ubuntu version of kitty.

**Comment by page-down** [comment]
> Now in Vim there is no blinking cursor until I enter insert mode ...

Set the cursor shape at vim startup.

```vim
if $TERM == "xterm-kitty"
    " ...

    " initialize cursor shape
    autocmd VimEnter * silent !echo -ne "\e[1 q"

    " disable modifyOtherKeys
    let [&t_TI, &t_TE] = ['', '']
endif
```

Or enter insert mode at startup and then return to normal mode. If echo does not work, use this approach.

```vim
autocmd VimEnter * normal! :startinsert :stopinsert
```

**Comment by chdiza** [comment]
Thanks, I'd already played around with a variant of the `norm! :startinsert...` approach.

Seems like there shouldn't be a need for that workaround though, if I'm understanding things correctly.

**Comment by page-down** [comment]
> Is there a way to have the blinking active when vim first starts up? Otherwise Vim has the appearance of being frozen. ...
> This indeed doesn't work on Ubuntu, but it does work on macOS.

>  ... Seems like there shouldn't be a need for that workaround though ...

If you are using different versions of vim / kitty, then maybe you need this workaround.

I'm testing on Ubuntu 20.04 LTS, vim 8.1.2269, kitty 0.23.1 and nightly version. If it's just for the cursor, then just the following three lines are needed and the cursor blinks immediately after startup.

```vim
let &t_SI = "\e[5 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[1 q"
```

However, the above and `t_ti` does not work on my macOS vim 8.2.2029, the cursor does not blink after startup.

So you need to troubleshoot your environment as well.

**Comment by chdiza** [comment]
I'm using Ubuntu 20.04, kitty 0.23.1 (but the release version on github, not a nightly), and Vim 8.2.3701.  It does not blink at first startup.

Using the same kitty (but the macOS version) and the same Vim version on macOS, it blinks at first startup.
