### ISSUE TITLE
URL hints don't work

### ISSUE THREAD

**Issue by ibeex** [kovidgoyal/kitty#424]
System: Host: Kernel: 4.15.13-1-ARCH x86_64 bits: 64 Console: tty 5 Distro: Arch Linux
Display Server: X.org 1.19.6 driver: modesetting unloaded: fbdev,intel,vesa tty: 213x57

when I pres ctrl+shift+e kitty finds links but presing nummber only flash screen, ctrl+shift+mouse works also as stated in https://github.com/kovidgoyal/kitty/issues/363
`kitty +runpy 'from kittens.url_hints.main import main; main()' /tmp/urls` works OK

**Comment by kovidgoyal** [comment]
Works for me on my arch system. What version of kitty are you running?

**Comment by ibeex** [comment]
``` shell
[I] ➜ kitty --version
kitty 0.8.3 created by Kovid Goyal
```

**Comment by ibeex** [comment]
@kovidgoyal I hawe no idea kow to do that? xdg-open is only one I found and it logs nothing, what program for urls is on your system?

**Comment by kovidgoyal** [comment]
I have my own custom xdg-open :)

Just write a script named xdg-open and put it somewhere in your PATH ahead of the system xdg-open. Something like:

```
#!/usr/bin/python
import sys, subprocess
print(sys.argv, file=open('/tmp/log', 'a'))
```

Now it will log the arguments passed to it in /tmp/log
