### ISSUE TITLE
F1, F2, F3, F4 are binded, so I can't change tabs in Unicode (Ctrl-Shift-U) Menu

### ISSUE THREAD

**Issue by iacchus** [kovidgoyal/kitty#4247]
**Is your feature request related to a problem? Please describe.**
Both; as in titlle, F1, F2, F3, F4 are binded, so I can't change tabs in Unicode (Ctrl-Shift-U) Menu.

**Describe the solution you'd like**
Maybe allowing to bind other keys to these tabs.

**Describe alternatives you've considered**
Maybe use a more specific keyboard shortcut.

**Additional context**

![ksnip_20211117-030314](https://user-images.githubusercontent.com/881531/142143820-865d5a49-d42b-4bbd-9e33-5158c160e833.png)

**Comment by kovidgoyal** [comment]
As is noted in the docs:
https://sw.kovidgoyal.net/kitty/kittens/unicode-input/ you can use other
keybindings to change tabs as well.
