### ISSUE TITLE
How to choose kitty as my default terminal

### ISSUE THREAD

**Issue by SandWoodJones** [kovidgoyal/kitty#425]
I use linux mint and i'd like to know if there's any way to launch kitty instead of the gnome-terminal in the drop-down menu of nemo (Open in terminal)

**Comment by kovidgoyal** [comment]
No idea, you'd have to ask on a linux Mint forum on how to change default programs. THough you can probably hack it by a shell script named gnome-terminal to your PATH that actually launches kitty.
