### ISSUE TITLE
Dotted symbol are not rendered

### ISSUE THREAD

**Issue by yosinlpet** [kovidgoyal/kitty#4253]
Hi,
While programming in Julia using Nvim and Julia-vim package, single/double dotted variables (standing for first/second time derivatives of the variable) are not rendered. It works for some chars like `t` giving `ṫ` and `ẗ`. But for others like `r`, only the single-dot version is rendered. For greek letters, none is rendered correctly.
Other terminals like the native Mac OS terminal or iTerm2 does not exhibit the issue.

 I tried other fonts but it does not affect the outcome. Am I missing something?
 Thanks

**Comment by kovidgoyal** [comment]
Works fine for me in macOS Monterey with the following steps:

1) kitty --config=NONE
2) Press ctrl+shift+u
3) Press f2
4) type alpha
5) See a whole bunch of correctly rendered alpha symbols with dots and
various other decoration above and below them

**Comment by yosinlpet** [comment]
It works fine with the built-in macOS terminal, i can render \theta\ddot nicely with the juliaMono font in a julia REPL or in a .jl file in Neovim.

On Kitty it just does not want to...

**Comment by page-down** [comment]
Do you have the same issue as the link below? 
https://github.com/kovidgoyal/kitty/issues/5541

> On Kitty it just does not want to...

I would suggest providing reproducible steps when giving feedback on issues, rather than ignoring and removing all the instructions in the bug reporting template.

**Comment by yosinlpet** [comment]
It is not, even for characters smaller than the cell size, like `x`,  it does not allow dotted versions.
Well, the issue was posted when there was no reporting template.
