### ISSUE TITLE
cursor doenst change color

### ISSUE THREAD

**Issue by Ahanaf-Ether** [kovidgoyal/kitty#4259]
Issue: The cursor doesnt change color when using terminal apps like: neovim, vim etc.

To reproduce: Install kitty-terminal, open neovim with theme like gruvbox where the expected cursor color is background text color like in any other terminal.

Info:              ether@B450MH
OS: Arch Linux [x86_64]
Host: B450M H
Kernel: 5.10.80-xanmod1-1-lts
Uptime: 4 mins
Packages: 682 (pacman)
Shell: fish 3.3.1
Resolution: 1920x1080 @ 60Hz
WM: i3 (X11)
Theme: Adwaita [GTK2/3/4]
Icons: Adwaita [GTK2/3/4]
Font: Cantarell (11pt) [GTK2/3/4]
Cursor: Adwaita
Terminal: kitty
CPU: AMD Ryzen 5 3400G with Radez
GPU: AMD ATI Picasso
Memory: 1451MiB / 6946MiB (20%)
Disk (/): 6GB / 100GB (6%)
Disk (/home): 1GB / 109GB (0%)
Locale: en_US.UTF-8

**Comment by kovidgoyal** [comment]
I cannot reproduce.

printf "\e]12;red\a" && cat

the cursor color is red as expected.

**Comment by Ahanaf-Ether** [comment]
How Is that? Did u use the color scheme I mentioned:
"Gruvbox"

**Comment by Ahanaf-Ether** [comment]
Expected behavior is the cursor color to cahnge depending on text foreground, how did you achieve it to change. There was even a reddit post about this:
https://www.reddit.com/r/neovim/comments/pmwrva/cursor_colors_are_not_set_correctly_in_kitty/

**Comment by kovidgoyal** [comment]
The code I posted demonstrates that changing cursor colors in kitty works fine. I have no clue about what neovim is doing, you will need to ask its developers.

**Comment by Ahanaf-Ether** [comment]
How did you manage to have your done?

**Comment by Ahanaf-Ether** [comment]
Confirm, it seems to me xfce4 terminal and most terminal have an to have no cursor color defined and neovim seems to rely on that feature, can you please add a feature like that?

**Comment by Ahanaf-Ether** [comment]
![Screenshot_20211122-120223_Chrome](https://user-images.githubusercontent.com/88607362/142808735-df81965f-a5db-4e78-95f1-690452246d6c.jpg)

**Comment by Ahanaf-Ether** [comment]
@kovidgoyal

**Comment by kovidgoyal** [comment]
Kindly stop pinging me. There is no bug in kitty. All terminals have a cursor color defined. It is meaningless to say they dont. If they didnt, the cursor would not render. And I have already proved that kitty allows changing of cursor colors via escape code. Go bother the neovim developers if you need to bother somebody.
