### ISSUE TITLE
Kitty seems to prevent some software registered shortcut keys from taking effect, such as fcitx5 shortcut keys for switching input methods: ctrl + space

### ISSUE THREAD

**Issue by backtolife2021** [kovidgoyal/kitty#4268]
https://github.com/kovidgoyal/kitty/issues/3975#issue-981697829

**Comment by kovidgoyal** [comment]
The way keyboard handling works in Operating systems is the keyboard
events are delivered first to the window manager and from there to the
paplications. So applications cannot intercept key events system wide.

**Comment by backtolife2021** [comment]
Redirected to https://github.com/kovidgoyal/kitty/issues/777
