### ISSUE TITLE
Mouse scrolling in tmux does not work depending on how the session is started

### ISSUE THREAD

**Issue by Ivan1248** [kovidgoyal/kitty#4271]
**Describe the bug**
Mouse scrolling in tmux works when the session is started by clicking on the "Open" button but not when started by clicking on the "Start" button or by running `kitty -load <session_name>`. This happens in version 0.76.0.2. In version 0.76.0.1 everything works fine.

**To Reproduce**
1. Set up mouse scrolling in tmux on the host by adding `set -g mouse on` to `.tmux.conf`, start tmux, overfill the vertical space with text inside tmux so that it can be scrolled (e.g. run `seq 200`) and close the SSH session.
2. For both versions 0.76.0.1 and 0.76.0.2:
   1. Select the session and press "Open" in the "KITTY Configuration" window.
   2. Run `tmux a` in the host shell, and try to scroll inside tmux with the mouse.
   3. Observe that mouse scrolling works in both versions.
2. For both versions 0.76.0.1 and 0.76.0.2:
    1. Run 
        * `kitty -load <session_name>` or 
        * select a session and press "Start" in the "KITTY Configuration" window or
        * select a session, press "Load" and press "Open" in the "KITTY Configuration" window.
    2. Run `tmux a` in the host shell, and try to scroll inside tmux with the mouse.
    3. Observe that mouse scrolling works only in version 0.76.0.1.

**Screenshots**
![kitty-tmux-scrolling](https://user-images.githubusercontent.com/8408581/143285920-8ef68375-b26d-4945-a8f0-5b22a0e72902.png)
![tmux-scrolling](https://user-images.githubusercontent.com/8408581/143286103-3eaed2f3-6fac-4b56-bb68-7ec602037b10.png)

**Environment details**
(Pressing Ctrl+Shift+F6 to copy debug output didn't work for me.)

**Additional context**
[sess.zip](https://github.com/kovidgoyal/kitty/files/7597522/sess.zip) contains my session configuration from `Computer\HKEY_CURRENT_USER\SOFTWARE\SimonTatham\PuTTY\Sessions\`.

**Comment by kovidgoyal** [comment]
You want https://github.com/cyd01/KiTTY/

**Comment by Ivan1248** [comment]
Oops. Thank you!
