### ISSUE TITLE
Document/Implement codes to remap Apple/Command key

### ISSUE THREAD

**Issue by iluvcapra** [kovidgoyal/kitty#4272]
**Is your feature request related to a problem? Please describe.**

I'm having trouble figuring out how to remap the apple command key and option key.

**Describe the solution you'd like**
The documentation should give the symbolic name or key codes for these and maybe an example!

**Describe alternatives you've considered**
I've gone to the URLs in the example .conf file and they don't document the codes for the Apple keys.

**Comment by kovidgoyal** [comment]
You cannot remap modifier keys in kitty. You can map entire key
sequences. How to do that is already documented.
