### ISSUE TITLE
Issue with vertical alignment of icons and text in the terminal

### ISSUE THREAD

**Issue by vishytk** [kovidgoyal/kitty#4274]
I am using lsd (LSDeluxe) that displays file type icons in ls output.

In kitty the vertical alignment of icon and text is not proper. I have tried adjust_baseline with no luck.

![tilix-kitty](https://user-images.githubusercontent.com/534818/143379374-0b4c1153-5659-495b-aa79-ead3b05a8c54.png)

**Comment by page-down** [comment]
I tested with the default Menlo font with `symbol_map` Symbols Nerd Font and everything works fine.
What configurations are you using?

**Comment by kovidgoyal** [comment]
Use a better icon font. I'm afraid I am not interested in implementing
per font alignment in kitty.

**Comment by vishytk** [comment]
I am using Fira Code which is a fairly popular font. Can `symbol_map` be used to adjust the icon position ?

**Comment by vishytk** [comment]
Also, tried Menlo font and having same issue.

**Comment by kovidgoyal** [comment]
Use a better **icon font**. Not normal font. AKA install Nerd font and use it symbol_map

**Comment by page-down** [comment]
I just tested Fira Code with Symbols Nerd Font and everything works fine.

symbol_map will only change the font used for the characters, not the position.

Please refer to the following link on how to configure symbol_map with nerd font.

https://github.com/kovidgoyal/kitty/issues/3884#issuecomment-889195612

**Comment by vishytk** [comment]
Got it, using Fira Code Nerd font and is working fine.
