### ISSUE TITLE
Strip trailing spaces in rectangular select

### ISSUE THREAD

**Issue by seirl** [kovidgoyal/kitty#4284]
**Is your feature request related to a problem? Please describe.**
One of the most common reasons to use rectangular select is when you're in a ncurses app with a vertical split (e.g vim, weechat, tmux...) and you want to select some part of one of the panes. If you use a normal selection, you will select the content of the other vertical panes:

![image](https://user-images.githubusercontent.com/4927883/143588260-c46d8d0c-60d4-44bb-881b-d75b62e181dc.png)

Instead, by using a rectangular select, we can select the content from a single pane:

![image](https://user-images.githubusercontent.com/4927883/143588413-67e12225-70a3-4345-8b55-d8f902ee2a3f.png)

However, doing this in Kitty doesn't remove trailing whitespaces, so the output will be a rectangle filled with whitespaces at the end of each line. Here is the output, in my editor which shows trailing whitespaces:

![image](https://user-images.githubusercontent.com/4927883/143588542-e6d8aebd-362e-4e3e-b4f3-fae7335144e8.png)

**Describe the solution you'd like**
Urxvt strips all trailing whitespaces from rectangular select. I think this would be a good idea to implement in Kitty. The UI also indicates this by having a different selection display for the trailing whitespaces that will be stripped:

![image](https://user-images.githubusercontent.com/4927883/143588809-925ff28e-b1cc-4af1-9901-8ebdc777fb78.png)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.strip_trailing_spaces

**Comment by seirl** [comment]
Thanks, I don't know how I missed that!
