### ISSUE TITLE
When using comprehensive keyboard handling and typing using XCompose on Linux a release event is only reported when the terminal window focus is lost.

### ISSUE THREAD

**Issue by 8bitkitkat** [kovidgoyal/kitty#4285]
**Describe the bug**
When using comprehensive keyboard handling and typing using XCompose on Linux a release event is only reported when the terminal window focus is lost.

**To Reproduce**
1. Launch `kitty +kitten show_key -m kitty`
2. Type something using XCompose, such as <kbd>e</kbd>, <kbd>;</kbd>
3. Loose focus of the terminal window
4. See release reported

**Environment details** (`kitty --config NONE`)
```
kitty 0.23.1 created by Kovid Goyal
Linux xla-Manjaro 5.12.19-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021 x86_64
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.6
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under:X11

Config options different from defaults:
```

**Additional context**
Reproducible with both my config and the default, the details are from the default.

`~/.XCompose` File
```
include "/usr/share/X11/locale/en_US.UTF-8/Compose"
```

**Comment by kovidgoyal** [comment]
Post the log from

kitty --debug-input

when you reproduce the issue. Most likely the issue is simply the
release event isn't delivered to kitty until focus is switched.

**Comment by 8bitkitkat** [comment]
```
Press xkb_keycode: 0x24 clean_sym: Return composed_sym: Return mods: none glfw_key: 57345 (ENTER) xkb_key: 65293 (Return)
on_key_input: glfw key: 0xe001 native_code: 0xff0d action: PRESS mods: none text: '' state: 0 sent key to child
Release xkb_keycode: 0x24 clean_sym: Return mods: none glfw_key: 57345 (ENTER) xkb_key: 65293 (Return)
on_key_input: glfw key: 0xe001 native_code: 0xff0d action: RELEASE mods: none text: '' state: 0 ignoring as keyboard mode does not support encoding this event
Press xkb_keycode: 0x87 clean_sym: Multi_key compose not complete, ignoring.
Release xkb_keycode: 0x87 clean_sym: Multi_key mods: none glfw_key: 0 (UNKNOWN) xkb_key: 65312 (Multi_key) alternate_key: 57363 (MENU)
on_key_input: glfw key: 0x0 native_code: 0xff20 action: RELEASE mods: none text: '' state: 0 ignoring release event for previous press that was handled as shortcut
Press xkb_keycode: 0x1a clean_sym: e compose not complete, ignoring.
Release xkb_keycode: 0x1a clean_sym: e mods: none glfw_key: 101 (e) xkb_key: 101 (e)
Press xkb_keycode: 0x2f clean_sym: semicolon composed_sym: U0119 composed_text: ę mods: none glfw_key: 281 (ę) xkb_key: 16777497 (U0119) shifted_key: 59 (;) alternate_key: 59 (;)
on_key_input: glfw key: 0x119 native_code: 0x1000119 action: PRESS mods: none text: 'ę' state: 0 sent key to child
Release xkb_keycode: 0x2f clean_sym: semicolon mods: none glfw_key: 59 (;) xkb_key: 59 (semicolon)
** Lose focus **
on_key_input: glfw key: 0x119 native_code: 0x1ea action: RELEASE mods: none text: '' state: 0 sent key to child
```

> Most likely the issue is simply the
> release event isn't delivered to kitty until focus is switched

So would this be an issue with glfw rather than kitty?

**Comment by kovidgoyal** [comment]
On Sun, Nov 28, 2021 at 12:10:38AM -0800, Ketan Reynolds wrote:
> > Most likely the issue is simply the
> > release event isn't delivered to kitty until focus is switched
> 
> So would this be an issue with glfw rather than kitty?

kitty has its own glfw fork, so it's an issue in that fork (glfw itself
has no support for compose at all).

It's been a while since I used XCompose, so refresh my memory please,
what exactly do I need to do to setup a reproducer. Create ~/.XCompose
obviously, but do I need to designatea compose key somehow as well?

**Comment by 8bitkitkat** [comment]
I use `setxkbmap -option compose:menu` making the menu key my compose key.
`xmodmap -e "keysym Menu = Multi_key"` should also work, but I have not tried it myself.

You can use `localectl list-x11-keymap-options` to list all the `setxkbmap -option`s
Otherwise any changes in `~/.XCompose` will take effect on an application restart.

**Comment by kovidgoyal** [comment]
OK thanks. Will look into it when I have some time. I have a vague
memory that glfw stores key press state and sends a release event on
focus change, probably the compose handling needs to hook into that and
stop it from happening.

**Comment by 8bitkitkat** [comment]
Cool.
Question: would you consider no release event or an immediate release event the expected behavior?

**Comment by kovidgoyal** [comment]
On Sun, Nov 28, 2021 at 07:33:53AM -0800, Ketan Reynolds wrote:
> Cool.
> Question: would you consider no release event or an immediate release event the expected behavior?

I would generally expect a press event to be followed by a release
event. If there is press event sent to kitty there should be a
corresponding release event. How easy that is to implement will have to
be seen. Unless the key numbers match up for the two events, there isn't
much point sending the release event.
