### ISSUE TITLE
Opening URLs is slow (~ 1s)

### ISSUE THREAD

**Issue by rixx** [kovidgoyal/kitty#4288]
**Describe the bug**

Opening a URL with Kitty by clicking on it is noticeably slow on my system. It takes a full second for the new tab to show up.

I noticed this because I'm switching from Terminator, and everything else is faster in Kitty, but opening URLs is pretty much instantaneous in Terminator, and a second is a noticeable delay with Kitty.

**Additional Context**

I'm running the latest Kitty release on Arch Linux. The opening browser is Firefox. Opening a URL does get faster by about half a second when I specify ``open_url_with firefox``, but the delay is still very much there (slower than running ``xdg-open`` on a URL manually).

**Environment details**

Running ``kitty --config NONE`` didn't make a difference, neither did specifying `xdg-open` as URL opening command. I also tested building from source and it didn't make a difference.

```
kitty 0.23.1 created by Kovid Goyal
Linux cordelia 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  /home/rixx/.config/kitty/kitty.conf

Config options different from defaults:
```

**Comment by page-down** [comment]
Please configure `click_interval`, or use shift+cilck.

kitty has double click, triple click and other event configurations, so the current default is a longer click_interval time, which you can adjust as needed.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.click_interval
