### ISSUE TITLE
Unable to issue remote kitty commands from python script.

### ISSUE THREAD

**Issue by TheFoolishPupil** [kovidgoyal/kitty#4291]
I am trying to issue the `kitty @ set-colors` from another terminal, I am met with `OSError: Failed to open controlling terminal: /dev/tty (identified with ctermid()) with error: Device not configured`

```
Traceback (most recent call last):
  File "lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "lib/python3.9/runpy.py", line 87, in _run_code
  File "lib/python3.9/kitty_main.py", line 153, in <module>
  File "lib/python3.9/kitty_main.py", line 149, in main
  File "lib/python3.9/kitty_main.py", line 23, in remote_control
  File "lib/python3.9/kitty/remote_control.py", line 188, in main
  File "lib/python3.9/kitty/remote_control.py", line 132, in do_io
  File "lib/python3.9/kitty/utils.py", line 442, in __enter__
OSError: Failed to open controlling terminal: /dev/tty (identified with ctermid()) with error: Device not configured
```

**Environment details**
This is running as a subprocess of a script in MacOS where I am unable to obtain the environment details.

**Additional context**
I am evoking the following python script using this: https://github.com/bouk/dark-mode-notify
```python
os.system("/usr/local/bin/kitty @ set-colors -a ~/.config/kitty/light-theme.conf")
```

**Comment by page-down** [comment]
There are two ways to control remotely, one is in kitty terminal, you need tty device and send escape code directly. the other way is through socket, which can be controlled in other programs.

Please listen for UNIX socket or TCP socket for remote control. Then call `kitty @ --to <SOCKET>` in other programs.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.listen_on
https://sw.kovidgoyal.net/kitty/remote-control/#cmdoption-kitty-to

**Comment by TheFoolishPupil** [comment]
Thanks for the reply, It seems like the second option is what I am after. I will give it a try.

**Comment by TheFoolishPupil** [comment]
It worked! partially at least. It works if if launch kitty from the command line with `kitty -o allow_remote_control=socket-only --listen-on unix:/tmp/kitty`. However with the following in my `kitty.conf`, no socket is created at /tmp/kitty when I run kitty.

I now have the following in my kitty.conf:
```
allow_remote_control socket-only
listen_on unix:/tmp/kitty
```

However there doesn't seem to be a socket made at /tmp/kitty. I have also tried running via the command line with `kitty -o allow_remote_control=socket-only --listen-on unix:/tmp/kitty
```

**Comment by page-down** [comment]
Please check the documentation and cd to the corresponding path to see the actual UNIX sockets listening.

Since kitty can run many instances, and if listen_on is defined in the configuration file, then the process pid is automatically appended to the filename.

You may want to run the command to change the color in all running kitty processes.

**Comment by kovidgoyal** [comment]
Note that you dont even need remote control to change colors
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by kovidgoyal** [comment]
Although I should note that unless you run from master on macos
reloading via the themes kitten is currently broken (#3952)
