### ISSUE TITLE
Wacom pen mouse unusable on Wayland

### ISSUE THREAD

**Issue by inducer** [kovidgoyal/kitty#4297]
**Describe the bug**

When using kitty under Wayland with my Wacom tablet,
* (most of the time) no mouse cursor is shown for the tablet pen, and
* I am not able to interact with Kitty via the pen at all (e.g. highlighting things).

I am using Gnome Shell 41.1-1 from Debian, which relies on Wayland 1.19. Kitty's `kitty/glfw-wayland.so` is linked against libwayland-client0 version `1.19.0-2+b1`, also from Debian.

For context, Wayland shows two mouse cursors, one driven by all the "relative" pointing devices on the system (mice/trackballs/touchpad), and another for the Wacom tablet. This occurs also with `kitty --config NONE`. The bug does not seem specific to the model of pen/tablet I have. It occurs with both a Wacom CTH-480 and a Huion HS64.

**To Reproduce**
1. Start kitty under Wayland
2. Move pen mouse cursor over kitty window
3. Watch cursor disappear
4. Observe that highlighting doesn't work using the pen cursor. (Works just fine using the "main" pointer driven by the mouse.)

**Environment details**
```
kitty 0.23.1 (cd7b4fcd8e) created by Kovid Goyal
Linux lightning 5.15.0-1-amd64 #1 SMP Debian 5.15.3-1 (2021-11-18) x86_64
Debian GNU/Linux bookworm/sid \n \l
Running under:Wayland
Loaded config files:
  /home/andreas/.config/kitty/kitty.conf
  /home/andreas/.config/kitty/theme-brewer-light-v2.conf
  /home/andreas/.config/kitty/kitty-lightning.conf

Config options different from defaults:
bold_font                  Iosevka Term Bold
click_interval             0.5
cursor_blink_interval      0.5
cursor_stop_blinking_after 3.0
font_family                Iosevka Fixed
font_size                  12.0
inactive_text_alpha        0.7
initial_window_height      (1200, 'px')
initial_window_width       (1800, 'px')
macos_option_as_alt        3
repaint_delay              20
scrollback_lines           20000
scrollback_pager           ['less', '+G', '-R']
select_by_word_characters  :@-./_~?&=%+#
window_border_width        (0, 'pt')
Added shortcuts:
	ctrl+- KeyAction('decrease_font_size')
Changed shortcuts:
	shift+ctrl+0 KeyAction('restore_font_size')
	shift+ctrl+= KeyAction('increase_font_size')
	shift+ctrl+e KeyAction('kitten', ('hints',))
	shift+ctrl+p > f KeyAction('kitten', ('hints', '--type path --program @'))
	shift+ctrl+p > l KeyAction('kitten', ('hints', '--type line --program @'))
	shift+ctrl+p > w KeyAction('kitten', ('hints', '--type word --program @'))
	shift+ctrl+u KeyAction('input_unicode_character')
Colors:
	background                 #fcfdfe   
	color0                     #0c0d0e   
	color1                     #e31a1c   
	color10                    #ffa74f   
	color11                    #ffa74f   
	color12                    #459de0   
	color13                    #9aaeea   
	color14                    #9dd7ff   
	color15                    #fcfdfe   
	color2                     #31a354   
	color3                     #dca060   
	color4                     #3182bd   
	color5                     #756bb1   
	color6                     #739fbd   
	color7                     #b7b8b9   
	color8                     #737475   
	color9                     #ff0000   
	cursor                     #515253   
	foreground                 #515253   
```

**Comment by kovidgoyal** [comment]
I'm afraid someone with access to this hardware is going to have to
develop support for it in glfw (the graphics toolkit kitty uses),
as I dont have access to such. If you are willing to try let me know and
I will guide you as to where and how to get started.
