### ISSUE TITLE
Fedora 35 libpython3.9.so.1.0

### ISSUE THREAD

**Issue by pietryszak** [kovidgoyal/kitty#4299]
**Describe the bug**
Newest Kitty installed by installer.sh is not usable in the newest Fedora 35.

**To Reproduce**
1. Install by script curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
2. Try to start kitty
3. See error : kitty: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

Kitty from fedora repo 0.21.2 working fine

**Comment by kovidgoyal** [comment]
Run it with LD_DEBUG=libs and post the output. I really dont feel like
creating a fedora 35 VM to see what they screwed up.

**Comment by pietryszak** [comment]
> LD_DEBUG=libs

![image](https://user-images.githubusercontent.com/45850093/143901850-210a2330-c717-48a8-8ccd-b1d4dd3cd21e.png)

**Comment by Luflosi** [comment]
I think he meant `LD_DEBUG=libs kitty`.

**Comment by kovidgoyal** [comment]
LD_DEBUG=libs kitty

**Comment by pietryszak** [comment]
> LD_DEBUG=libs kitty

`LD_DEBUG=libs kitty
      9155:	find library=libpthread.so.0 [0]; searching
      9155:	 search path=/usr/bin/../lib/glibc-hwcaps/x86-64-v3:/usr/bin/../lib/glibc-hwcaps/x86-64-v2:/usr/bin/../lib/tls/haswell/x86_64:/usr/bin/../lib/tls/haswell:/usr/bin/../lib/tls/x86_64:/usr/bin/../lib/tls:/usr/bin/../lib/haswell/x86_64:/usr/bin/../lib/haswell:/usr/bin/../lib/x86_64:/usr/bin/../lib		(RPATH from file kitty)
      9155:	  trying file=/usr/bin/../lib/glibc-hwcaps/x86-64-v3/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/glibc-hwcaps/x86-64-v2/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/tls/haswell/x86_64/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/tls/haswell/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/tls/x86_64/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/tls/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/haswell/x86_64/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/haswell/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/x86_64/libpthread.so.0
      9155:	  trying file=/usr/bin/../lib/libpthread.so.0
      9155:	 search cache=/etc/ld.so.cache
      9155:	  trying file=/lib64/libpthread.so.0
      9155:	
      9155:	find library=libpython3.9.so.1.0 [0]; searching
      9155:	 search path=/usr/bin/../lib		(RPATH from file kitty)
      9155:	  trying file=/usr/bin/../lib/libpython3.9.so.1.0
      9155:	 search cache=/etc/ld.so.cache
      9155:	 search path=/lib64/glibc-hwcaps/x86-64-v3:/lib64/glibc-hwcaps/x86-64-v2:/lib64/tls/haswell/x86_64:/lib64/tls/haswell:/lib64/tls/x86_64:/lib64/tls:/lib64/haswell/x86_64:/lib64/haswell:/lib64/x86_64:/lib64:/usr/lib64/glibc-hwcaps/x86-64-v3:/usr/lib64/glibc-hwcaps/x86-64-v2:/usr/lib64/tls/haswell/x86_64:/usr/lib64/tls/haswell:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/haswell/x86_64:/usr/lib64/haswell:/usr/lib64/x86_64:/usr/lib64		(system search path)
      9155:	  trying file=/lib64/glibc-hwcaps/x86-64-v3/libpython3.9.so.1.0
      9155:	  trying file=/lib64/glibc-hwcaps/x86-64-v2/libpython3.9.so.1.0
      9155:	  trying file=/lib64/tls/haswell/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/lib64/tls/haswell/libpython3.9.so.1.0
      9155:	  trying file=/lib64/tls/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/lib64/tls/libpython3.9.so.1.0
      9155:	  trying file=/lib64/haswell/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/lib64/haswell/libpython3.9.so.1.0
      9155:	  trying file=/lib64/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/lib64/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/glibc-hwcaps/x86-64-v3/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/glibc-hwcaps/x86-64-v2/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/tls/haswell/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/tls/haswell/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/tls/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/tls/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/haswell/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/haswell/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/x86_64/libpython3.9.so.1.0
      9155:	  trying file=/usr/lib64/libpython3.9.so.1.0
      9155:	
kitty: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
`

**Comment by kovidgoyal** [comment]
You are running /usr/bin/kitty not ~/.local/kitty.app/bin/kitty

**Comment by pietryszak** [comment]
Yes, i see that, sorry

**Comment by eo1989** [comment]
Not to reopen a dead thread unnecessarily, but I just ran across this same problem trying to upgrade my wsl2 ubuntu 22.04 to kitty 0.27.1.
After running the curl command (which resulted in a PROTOCOL_ERROR (err 1))
"
 curl -# https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=nightly
################################################################################################################################# 100.0%
Installing to /home/rocket/.local/kitty.app
Downloading from: https://github.com/kovidgoyal/kitty/releases/download/nightly/kitty-nightly-x86_64.txz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 19 19.1M   19 3888k    0     0  29234      0  0:11:25  0:02:16  0:09:09 16.1M
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
/home/rocket/.local/kitty.app/bin/kitty: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
"

resulted in this after running the recommended debug env variable:
"
 LD_DEBUG=libs kitty
     41194:	find library=libpthread.so.0 [0]; searching
     41194:	search path=/home/rocket/.local/kitty.app/bin/../lib/glibc-hwcaps/x86-64-v3:/home/rocket/.local/kitty.app/bin/../lib/glibc-hwcaps/x86-64-v2:/home/rocket/.local/kitty.app/bin/../lib/tls/x86_64/x86_64:/home/rocket/.local/kitty.app/bin/../lib/tls/x86_64:/home/rocket/.local/kitty.app/bin/../lib/tls/x86_64:/home/rocket/.local/kitty.app/bin/../lib/tls:/home/rocket/.local/kitty.app/bin/../lib/x86_64/x86_64:/home/rocket/.local/kitty.app/bin/../lib/x86_64:/home/rocket/.local/kitty.app/bin/../lib/x86_64:/home/rocket/.local/kitty.app/bin/../lib		(RPATH from file kitty)
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/glibc-hwcaps/x86-64-v3/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/glibc-hwcaps/x86-64-v2/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/tls/x86_64/x86_64/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/tls/x86_64/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/tls/x86_64/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/tls/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/x86_64/x86_64/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/x86_64/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/x86_64/libpthread.so.0
     41194:	 trying file=/home/rocket/.local/kitty.app/bin/../lib/libpthread.so.0
     41194:	search cache=/etc/ld.so.cache
     41194:	 trying file=/lib/x86_64-linux-gnu/libpthread.so.0
     41194:	
     41194:	find library=libpython3.9.so.1.0 [0]; searching
     41194:	search cache=/etc/ld.so.cache
     41194:	search path=/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/lib/x86_64-linux-gnu/tls/x86_64/x86_64:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/x86_64/x86_64:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/usr/lib/x86_64-linux-gnu/tls/x86_64/x86_64:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/x86_64/x86_64:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/glibc-hwcaps/x86-64-v3:/lib/glibc-hwcaps/x86-64-v2:/lib/tls/x86_64/x86_64:/lib/tls/x86_64:/lib/tls/x86_64:/lib/tls:/lib/x86_64/x86_64:/lib/x86_64:/lib/x86_64:/lib:/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib/tls/x86_64/x86_64:/usr/lib/tls/x86_64:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/x86_64/x86_64:/usr/lib/x86_64:/usr/lib/x86_64:/usr/lib		(system search path)
     41194:	 trying file=/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/tls/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64-linux-gnu/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/tls/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0
     41194:	 trying file=/lib/glibc-hwcaps/x86-64-v3/libpython3.9.so.1.0
     41194:	 trying file=/lib/glibc-hwcaps/x86-64-v2/libpython3.9.so.1.0
     41194:	 trying file=/lib/tls/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/tls/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/lib/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/glibc-hwcaps/x86-64-v3/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/glibc-hwcaps/x86-64-v2/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/tls/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/tls/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/tls/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/x86_64/libpython3.9.so.1.0
     41194:	 trying file=/usr/lib/libpython3.9.so.1.0
     41194:	
kitty: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
    ~                                                                                                            gen 3.10.8  17:05:06
❯ kitty --version
kitty: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
"

**Comment by page-down** [comment]
@eo1989
Looking at your log, the download is incomplete, only 19%.
Re-run the installer command.
Or manually download the tarball from GitHub Releases and extract it.

@kovidgoyal
https://github.com/kovidgoyal/kitty/blob/v0.27.1/docs/installer.sh#L122

It looks like the installation could be improved under linux.

- Successfully downloaded, or die.
- Successfully extracted, or die.
  - e.g. halfway through unpacking, so only some of the files are from the new version.
- Replace `kitty.app` with the fully extracted folder, or move failed.
