### ISSUE TITLE
Add mouse selection support in padding area 

### ISSUE THREAD

**Issue by gustafj** [kovidgoyal/kitty#430]
When selecting multiple lines of text, or the beginning of a line it would be convenient if the padding area would belong to the line being selected.
As it is now the selection has to be done on the first character on the line (which can be hard to see when it is spaces).
For instance selection would be possible from the *red* dot, and not only the *green* as it is now.
![lorem_ipsum](https://user-images.githubusercontent.com/882479/38172260-43331f2e-35a9-11e8-8177-d5c21d325d0e.png)

**Comment by kovidgoyal** [comment]
This would actually require architectural changes since windows don't have any knowledge of padding and mouse selection happens a the window level. Given that, it's not worth the effort, at least for me, patches are welcome.
