### ISSUE TITLE
Enable extended keyboard protocol

### ISSUE THREAD

**Issue by anuvyklack** [kovidgoyal/kitty#4303]
Is extended keyboard protocol enabled by default or I should somehow turn it on?

My kitty version is **0.23.1**, and the next keybindings don't work by default:
```
Ctrl+Tab
Ctrl+Shift+Tab
Ctrl+;
```

I have to manually add these lines to my `kitty.conf` to make them work:
```
map ctrl+tab       send_text all  \x1b[9;5u
map ctrl+shift+tab send_text all  \x1b[9;6u
map ctrl+;         send_text all  \x1b[59;5u
```

**Comment by kovidgoyal** [comment]
Extended keyboard protocol has to be turned on by the program running in
the terminal, if it is capable of supporting it.
