### ISSUE TITLE
Kitty running tmux in amazonlinux is broken

### ISSUE THREAD

**Issue by ianliu** [kovidgoyal/kitty#4305]
**Describe the bug**

Kitty combined with amazonlinux and tmux 1.8 sends all kinds of gibberish to the terminal when pressing <kbd>Enter</kbd>, <kbd>Escape</kbd>, and control sequences, such as <kbd>Ctrl-b</kbd>. Here is an example of characters sent to the terminal:

| Key Pressed       | What I see |
|-------------------|------------|
| <kbd>Return</kbd> | `;129u`    |
| <kbd>Escape</kbd> | `;129u`    |
| <kbd>Ctrl-b</kbd> | `8;133u`   |

**To Reproduce**
1. `kitty --config NONE`
2. `docker run --rm -ti amazonlinux /bin/bash`
3. `yum install tmux`
4. `tmux`
5. Press <kbd>Enter</kbd> and other characters

**Screenshots**

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux polita 5.15.5-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 25 Nov 2021 22:09:35 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11

Config options different from defaults:
```

**Additional context**
I didn't test uploading the terminfo to the docker image, but I have an ec2 server running which I did copy the terminfo, and the exact same problem happens. Also, I've tested the suckless `st` terminal and it works correctly on amazonlinux with tmux.

**Comment by kovidgoyal** [comment]
dup of #3541
