### ISSUE TITLE
Avoid overriding user LESS environment variables when displaying help

### ISSUE THREAD

**Issue by tpoliaw** [kovidgoyal/kitty#4306]
**Is your feature request related to a problem? Please describe.**
Running `kitty --help` brings up the help text in less in a way that doesn't use the alternate screen and therefore fills the terminal history.

**Describe the solution you'd like**
Help text to be shown in less using the user defined settings (via `LESS` environment variable). The minimal change to fix this issue would be to remove the `FX` flags but leaving all (except possibly `R` to allow colours to be displayed) might be preferable,

**Describe alternatives you've considered**
Explicitly piping help to less works but you lose the colour and formatting. As the arguments are passed in directly to the command, I'm not aware of a method of overriding them,

**Additional context**
The relevant `XF` flags were added in [this](https://github.com/kovidgoyal/kitty/commit/ddb2e413521bcfb9f84ce14372822d042d0ac127) commit about removing argparse and doesn't mention the paging config. Was there anything motivating the change?

I'm only just getting started using kitty but am really liking it so far. Thanks for your work on it.

**Comment by kovidgoyal** [comment]
This is by design. I want the help text to remain on screen after
quitting the pager, just as it remains on screen when running --help in
most programs.

**Comment by tpoliaw** [comment]
Fair enough, I'm happy to pipe to less for now. 

I would like to question the 'most programs' idea though. I can't think of any other program that leaves only part of the help on screen. They either print it all letting the user scroll back to refer to it, or they use a pager with the alternate screen, leaving no help visible - see `less --help` or `git clone --help` for example. Using `less -X` is a halfway that leaves the help text only partially printed unless the user scrolls to the bottom of the page. Users wishing to maintain the current behaviour would still be able to add ``X` to `LESS`.

Thanks for responding though. I appreciate a direct response rather than an issue being left open and ignored.

**Comment by kovidgoyal** [comment]
The halfway house is a feature. The idea is you find what you are looking
for and leave that on screen to refer to as you type future commands.
And yes no other program does exactly that. I wish they did.
