### ISSUE TITLE
Escape keys for C-1 ... C-9

### ISSUE THREAD

**Issue by goschevski** [kovidgoyal/kitty#4307]
Hi,

Sorry for the noob question. In tmux I have mappings to switch between windows by using C-1, C-2 ... C-9, but in order for that to work, I had to remap keys in iTerm2 by sending escape sequences:

C-1 -> [27;5;49~
C-2 -> [27;5;50~

etc.

I tried adding something similar inside the kitty.conf but it doesn't seem to work.

map ctrl+1 send-text all \x1b[27;5;49~
map ctrl+2 send-text all \x1b[27;5;50~

Can anyone help?

**Comment by kovidgoyal** [comment]
send_text not send-text

**Comment by goschevski** [comment]
Ah, sorry about that.

Thanks!
