### ISSUE TITLE
display tmux status line missing, or scrolls by a single line on tmux status line redraws

### ISSUE THREAD

**Issue by karlmutch** [kovidgoyal/kitty#4310]
**Describe the bug**
The tmux status line is not drawn on initial entry into a shell session.

When the poweline10K prompt theme on oh-my-zsh redraws the clock on the tmux status bar the status window is scrolled up and then the new bar is drawn on the line above the terminals last line.  

The very last line of the terminal display is left blank and never contains any content. 

Lines that scroll off the top of the screen on redraws are lost.

The cursor remains where it was originally being drawn.

**To Reproduce**
I am not sure this will help but ...

1. Begin an on-my-zsh terminal window and use the powerline10k with a clock segment
2. On start observe the lost tmux status bar ****
3. wait one minute for the prompt to be redrawn
4. the tmux status line will appear at the bottom of the terminal + 1 line ****
5. wait another minute for another redraw and see the existing status line get redrawn and scroll other lines up
6. etc etc

**Screenshots**

![Screen Shot 2021-12-02 at 9 25 28 AM](https://user-images.githubusercontent.com/1184005/144472537-e595ac8b-40d6-4e85-aa6b-536972d6abb3.png)

![Screen Shot 2021-12-02 at 9 26 35 AM](https://user-images.githubusercontent.com/1184005/144472503-c8e4c9db-d17c-417c-8f44-8a274b4a4e5c.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin FR-1978 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.0.1 BuildVersion:	21A559
Loaded config files:
  /Users/karlmutch/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select clipboard
font_size      16.0
```

**Additional context**
iTerm2 does not replicate the problem

**Comment by kovidgoyal** [comment]
I'm afraid I dont see how this is a terminal bug and I dont have the
time/interest to debug tmux issues. Report it to the software involved
and if they can isolate what it is about the terminal they dont like, I
will be happy to take a look at it. I will need something along the
lines of "we send X escape code and expect Y to happen but kitty does Z
instead".
