### ISSUE TITLE
Command to run when preventing closing OS window.

### ISSUE THREAD

**Issue by Icelk** [kovidgoyal/kitty#4319]
**Is your feature request related to a problem? Please describe.**
The current prevention of "accidentally" closing Kitty shows text inside Kitty. This doesn't integrate well with DEs.

**Describe the solution you'd like**
Add a option in kitty.conf to set a program that will be run when this prevention is handled. If the program's exitcode `!= 0`, don't close.

**Comment by kovidgoyal** [comment]
I'm afraid DE integration is not a goal for kitty. All of kitty's
interface is drawn as text within kitty. Kitty is for people that use
text as their primary interface. Not to mention that using an external
process means either blocking the entire UI or writing some inelegant
polling code.

**Comment by Icelk** [comment]
I see. 👍
Btw, great work! I love using kitty. The new technologies you’ve developed are awesome.

In theory, regarding handling another process, can’t we spawn a thread which handles the prevention if the config option is specified?

**Comment by kovidgoyal** [comment]
On Sun, Dec 05, 2021 at 08:34:00AM -0800, Icelk wrote:
> I see. 👍
> Btw, great work! I love using kitty. The new technologies you’ve developed are awesome.
> 
> In theory, regarding handling another process, can’t we spawn a thread which handles the prevention if the config option is specified?

sure, but given the amount of pain involved, not worth it.
