### ISSUE TITLE
Feature Request: Ability to strip escape sequences from shell title

### ISSUE THREAD

**Issue by gf3** [kovidgoyal/kitty#4325]
I use escape sequences in my shell title because they can be rendered by the tab bar, however they're unable to be rendered in the application titlebar:

![Screenshot](https://screenshot.pics/s/2m22mC2m22mf2m22marowana2m22m1moctograph22m0m__2021-12-07_12-01-06.png)

It would be nice to be able to translate or strip these escape sequences for use in the MacOS menubar.

**Comment by gf3** [comment]
thank you @kovidgoyal 🎉

**Comment by gf3** [comment]
@kovidgoyal i think there has been a regression here in the latest release:

![Screenshot](https://screenshot.pics/s/Cfarowana__2022-02-08_12-59-18.png)

**Comment by page-down** [comment]
I can reproduce this regression in the master branch.

Also, recently `macos_menubar_title_max_length` has been introduced. This should truncate the characters after removing the escape sequence, right? (I haven't tried it yet.)

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/0dbe27438d7e8e5119caa242a5d35067f0471b87

**Comment by gf3** [comment]
amazing @kovidgoyal 🙌
