### ISSUE TITLE
diff: Syntax highlighting is impossible to get working

### ISSUE THREAD

**Issue by arandomliz** [kovidgoyal/kitty#4326]
**Description**
When using the precompiled binaries for Linux - it seems to be impossible to get syntax highlighting with kitty-diff working.
The reason seems to be that it is impossible to install pygmetize for kitty, as the kitty app will not look for it. 

When looking further into the issue, it seems like that the `sys.path` variable will be cleared / set to empty somewhere. Even using `PYTHONPATH` - which should result in an additional entry in `sys.path` - doesn't change the fact that the path is empty. (`PYTHONPATH` was readable from inside the python runtime).

Of course, pygments is install locally as running `python3 -c "import pygments"` or `pygmentize` proofs

Lines I've used for debugging
```bash
# sys.path
kitty +runpy "import sys; print(sys.path)"

# PYTHONPATH
PYTHONPATH="whatever" kitty +runpy "import os; print(os.environ['PYTHONPATH')"
```
**To Reproduce**
1. Use the precompiled binary for linux
2. run `kitty +runpy "from kittens.diff.highlight import main; main()" file`
3. see the error `no module named pygments`

**Future**
As the documentation doesn't really state how to install `pypygments` / where to install it and my analysis showed that there wasn't an obvious (for me) way either. I think that it is impossible in the precompiled binary, but maybe that's unjust to say and I just haven't found the trick. 
But I think forcing the usage of the `import pygments`, instead of just using the `pygmentize` binary, is the problem here.

**Comment by kovidgoyal** [comment]
pygmentize is included in the pre-compiled binaries already. 

bin/kitty +runpy 'import pygments; print(pygments)'                                                                              
<module 'pygments' (/t/k/lib/kitty-extensions/python-lib.bypy.frozen/pygments/__init__.pyc)>

**Comment by arandomliz** [comment]
Well that is interesting, because in the Linux pre-compiled ones it doesn't seem to be.

**Comment by kovidgoyal** [comment]
That output is from a Linux pre-compiled one.

**Comment by page-down** [comment]
The current 0.23.1 version does report no pygments after running.
```shell
./bin/kitty --version
kitty 0.23.1

./bin/kitty +runpy 'import pygments; print(pygments)'
...
ModuleNotFoundError: No module named 'pygments'
```

You can download and use the nightly version and it should work fine.

```shell
./bin/kitty +runpy 'import pygments; print(pygments)'
<module 'pygments' (.../lib/kitty-extensions/python-lib.bypy.frozen/pygments/__init__.pyc)>
```

I wonder if it is possible to give new unreleased version number for the master compiled version and the nightly version.
Executing `kitty --version` all shows '0.23.1'.
