### ISSUE TITLE
Installer shell script errors on Apple M1 systems

### ISSUE THREAD

**Issue by gpoole** [kovidgoyal/kitty#4332]
**Describe the bug**

When running the recommended install script the following error is shown:

> You are running on an ARM system. The kitty binaries are only available for x86 systems. You will have to build from source.

From what I can tell the M1 is now fully supported in the release version and this message isn't necessary. Installing from homebrew works fine (`brew install --cask kitty`).

**To Reproduce**
1. Run the recommended install script on an Apple ARM system: `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin`

**Environment details**
macOS 12.0.1
Apple M1

**Comment by kovidgoyal** [comment]
This is already fixed in master, and will be made live after the next
kitty release.
