### ISSUE TITLE
Argument Persistence for Tabs and Windows

### ISSUE THREAD

**Issue by thatfatblackcat** [kovidgoyal/kitty#4333]
Opening a new tab or window for an existing instance doesn't reuse the arguments I specified when launching Kitty.
Eg. Launching Kitty with `kitty bash --rcfile .config/bash/bashrc` in my `kitty.desktop` works fine only for the first instance.

I won't ask you to change the default behavior of Kitty, especially if you are happy with how it works now.
All I'm asking is an option like `argument_persistence yes/no` that I can enable in my `kitty.conf`.

I'm currently running Kitty 0.19.3 because Pop!_OS 21.04 ships with that now.

**Comment by page-down** [comment]
You should install the latest released version. You can use the installation script on the official website or just download and extract the tarball to any location.

You should use the `shell` option in kitty.conf to specify the shell parameters.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.shell

And you can use the `kitty --single-instance` parameter as needed.
https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-single-instance

Does this solve your problem?

**Comment by kovidgoyal** [comment]
kitty -o "shell bash whatever"
