### ISSUE TITLE
supporting mosh style intermittent connectivity

### ISSUE THREAD

**Issue by xiangpeng2008** [kovidgoyal/kitty#4338]
**Is your feature request related to a problem? Please describe.**

Currently if my connection to the internet is interrupted, the connection to remote server using "kitty +kitten ssh" would be dropped too, and if I have an open python session there, it would get killed.

**Describe the solution you'd like**

https://mosh.org has a very robust solution for remote connection, is it possible to have these kind of features in kitty ?

**Describe alternatives you've considered**

I can always use mosh in kitty, but the "kitty +kitten icat" won't work in the remote server I logged with mosh, with following errors:
<img width="874" alt="Screenshot 2021-12-10 at 4 45 31 PM" src="https://user-images.githubusercontent.com/15676035/145544388-6c4200e7-918b-4aea-82b3-8a3be090a17f.png">

```
This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty
that does support it

```

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in implementing mosh. I suggest you
petition the mosh developers to add support for the graphics protocol.

**Comment by albertz** [comment]
I reported that upstream here: https://github.com/mobile-shell/mosh/issues/1248
