### ISSUE TITLE
SSH wrong keyboard

### ISSUE THREAD

**Issue by hdriqi** [kovidgoyal/kitty#434]
I built kitty from source and its work great! 

but, when I do ssh to my server some key are not mapped correctly such as backspace become space arrow unusabled etc.

Any fix for this?

**Comment by SolitudeSF** [comment]
[FAQ](https://github.com/kovidgoyal/kitty#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer)

**Comment by jessebett** [comment]
This was closed, and the FAQ linked above is dead. 

However, I have `ssh`d into a remote server on kitty, no configuration on the server, standard bash.

If I type `backspace` it doesn't work.

`showkey -a` and then `backspace` gives `^?`.

**Comment by Luflosi** [comment]
Here is the new link: https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by comod** [comment]
I dont understand the Documentation https://sw.kovidgoyal.net/kitty/faq.html#id5 . Can somebody help me out?

**Comment by Luflosi** [comment]
Programs need to know which features are supported by the terminal emulator (kitty in this case). They can do this if the `TERM` environment variable is set to `xterm-kitty` and they find the `xterm-kitty` file. To find it, the file needs to be in a special location on the filesystem, such as `~/.terminfo/x/xterm-kitty` (for programs that run as your normal user) or `/root/.terminfo/x/xterm-kitty` (for programs run as root). If you log into a server via SSH, you can use `kitty +kitten ssh myserver` once (or more often). This will copy the file to `~/.terminfo/x/xterm-kitty` in your home directory. There is also a special global location, usually `/usr/share/terminfo/x/xterm-kitty`, where programs run as any user can find the file (can be installed on most systems by installing the `kitty-terminfo` package, e.g. `sudo apt install xterm-kitty`). As an alternative to putting the file in the right place, you can also set the `TERMINFO` environment variable to the absolute path of the `.terminfo` directory. This can for example be used if the file is only in your home directory but you want to run programs as root with sudo. The documentation you mentioned talks about different ways to set this environment variable in this case, such as `sudo TERMINFO=$HOME/.terminfo bash -i`. In my opinion, you should just install the `xterm-kitty` package if your Linux distribution provides it, that seems like the easiest solution.

@kovidgoyal what are the three dots `…` in the faq supposed to indicate?

**Comment by comod** [comment]
Ah kitty +kitten ssh myserver put a file on the hom directory of the remote server - now i get it. But i must act as root there. And other users as well. I cant put such files there. xterm-kitty isnt available for ubuntu. sudo TERMINFO=$HOME/.terminfo bash -i OR TERMINFO=$HOME/.terminfo bash -i have no effect. yeah the three dots are confusing, exactly :-) ... any other options?

**Comment by Luflosi** [comment]
Ah, sorry, I meant `sudo apt install kitty-terminfo` instead of `sudo apt install xterm-kitty`.

**Comment by comod** [comment]
kitty-terminfo was installed. But even after remove and reinstall: If i go to my remote server and change user to root i still have the problem :-(

**Comment by Luflosi** [comment]
Did you install it on the remote server as well?

**Comment by comod** [comment]
No i cant install anything on the remote server.

**Comment by comod** [comment]
Thank you for you Answers @Luflosi , but is there no other Option to get this work, without install anything on the remote(s)?

**Comment by kovidgoyal** [comment]
@Luflosi the three dots indicate any other arguments you might want to pass to sudo.

**Comment by comod** [comment]
Sorry i still dont understand the Docs:
`Make sure the TERM environment variable, is xterm-kitty. And either the TERMINFO environment variable points to a directory containing x/xterm-kitty or that file is under ~/.terminfo/x/.`

What should i save where?

**Comment by cglewis** [comment]
Another workaround I've found is running tmux in kitty then sshing from inside tmux, fwiw.

**Comment by felixvo** [comment]
add `export TERM=xterm-256color` to `.zshrc` works for me

**Comment by Jim-Johnson** [comment]
If you just want to set it for ssh sessions rather than exporting it into your local env via `.zshrc` and clobbering the default value of `xterm-kitty` (that seems to mess with undercurls in nvim), you can set it in `~/.ssh/config` for all hosts like this 

```
Host *
  SetEnv TERM=xterm-256color
```

[Looks like this option is only available in openssh 8.6 or greater](https://www.openssh.com/txt/release-8.6), so might need to check the version of and update your ssh client `ssh -V`

**Comment by carica** [comment]
> Thank you for you Answers @Luflosi , but is there no other Option to get this work, without install anything on the remote(s)?

Unfortunately, no. You have either to grab sudo privileges & install kitty-terminfo or copy terminfo to remote server manually. Set TERM=xterm-kitty alone will not work.

**Comment by mkaz** [comment]
Thanks @Jim-Johnson that solution works great and doesn't require installing anything remotely. 👍

**Comment by EXG1O** [comment]
Thanks @Jim-Johnson, this works great!
