### ISSUE TITLE
Small note for Karabiner users

### ISSUE THREAD

**Issue by phanhaiquang** [kovidgoyal/kitty#4342]
This is not a bug. I want to share my issue and hope we could add some note in document so that everyone could avoid same mistake.

Summary:
- I am Mac user and using iTerm2 for a long time
- I also using Karabiner to make some config such as 
  I mapped "Ctrl-F" in applications that not terminal to "search" feature. Ex: 
```
       {
            "description": "Ctrl+F => Cmd+F (Find)",
            "manipulators": [
              {
                "conditions": [
                  {
                    "bundle_identifiers": [
                     .....
                      "^com\\\\.apple\\.Terminal$",
                      "^com\\.googlecode\\.iterm2$",
                    ],
                    "type": "frontmost_application_unless"
                  }
                ],
```

Then, I want to give Kitty a try, and it makes the problem with my VIM. Because VIM uses "ctrl-f" to next page, so that it does not work. I spent few hours to trial map/unmap/.. in Kitty config, but then I realized that it is my Karabiner issue.

Kitty document is very clear, and I believe author/contributor made excellent job to keep it updated. So that I hope we could add this in document because I think that many users could avoid my issue.

This is my update: I added to all config that is using for "iterm2". Then, my Kitty works fine.
                      "^net\\.kovidgoyal\\.kitty$"

Thanks for the application !

**Comment by kovidgoyal** [comment]
Thanks for the heads up. I'm afraid I dont think information about
configuring third party software belongs in the kitty docs, but
hopefully others stuck with this issue will find your post.

**Comment by phanhaiquang** [comment]
Yeah, I hope people could find it useful.
Thanks @kovidgoyal for prompt response !
