### ISSUE TITLE
Kitty fails to start after update

### ISSUE THREAD

**Issue by ThomasTraineau** [kovidgoyal/kitty#4353]
**Describe the bug**
Kitty doesn't start, using another terminal to start kitty I get this output : 

```
kitty: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Start kitty

**Environment details**

Using artix linux, kitty v.0.23.1-2

**Additional context**
Same error with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
You need to rebuild kitty since you have updated the python on your
system.

**Comment by ThomasTraineau** [comment]
I never built kitty, is it going to be fixed in the next update ?

**Comment by kovidgoyal** [comment]
You will need to ask whoever built the kitty you are using. Presumably
your linux distribution. The official kitty binaries dont use system
python.

**Comment by kovidgoyal** [comment]
And looks like this is a bug in artix. They updated python programs without updating python itself. https://github.com/qtile/qtile/discussions/3090
