### ISSUE TITLE
CTRL-D Not Recongized in TinTin++

### ISSUE THREAD

**Issue by prg318** [kovidgoyal/kitty#4354]
**Describe the bug**
Background information:  TinTIn++ is a very popular cross-platform MUD client.  Normally, CTRL-D on an empty line is used to quit tintin++ (or alternatively, the #end command).  I've tested that this works with xterm, urxvt, and konsole.  When trying to do this with kitty, the following sequence is displayed when pressing CTRL-D instead of quitting the client: "\e[100;133u".  Here is an example of the terminal output when running tintin++ with kitty:
```
 $ echo $TERM       
xterm-kitty
 $ tt++

                Legends of Kallisti - http://www.KallistiMUD.com                

One of the longest running, most feature rich MUDs in the world with decades    
of development. Kallisti boasts a massive original world, great atmosphere of   
players, excellent combat system including group formations, ranged combat,     
optional PK and arena PvP, extensive character customization, player lineages,  
clans, customizable player houses, item crafting, extensively customizable UI,  
Mud Sound Protocol, extensive blind player support, MSDP, and so much more.     
                                                                                
This is an amazing game that you could literally play for a decade and still    
discover more - you won't be disappointed!                                      

To connect to Legends of Kallisti enter: #session LoK kallistimud.com 4000      

      ####################################################################
      #                                                                  #
      #                    T I N T I N + +   2.02.12                     #
      #                                                                  #
      #      Code by Peter Unold, Bill Reis, and Igor van den Hoven      #
      #                                                                  #
      ####################################################################

\e[100;133u
\e[100;133u
\e[100;133u
```

This seems to occur with "xterm-kitty" terminfo as well as just normal "xterm" terminfo

**To Reproduce**
1. Use kitty as a terminal emulator
2. Launch tintin++ 
3. Attempt to quit with CTRL-D
4. See that tintin++ does not quit, but instead prints "\e[100;133u"

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux g15 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  /home/lukas/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.85
close_on_child_death       True
dynamic_background_opacity True
enable_audio_bell          False
font_family                Hack
font_size                  12.0
initial_window_height      (600, 'px')
initial_window_width       (940, 'px')
remember_window_size       False
Added mouse actions:
	 ctrl+b1 repeat ungrabbed KeyAction('mouse_click_url')
	 ctrl+b1 repeat grabbed KeyAction('mouse_click_url')
	 ctrl+b1 press grabbed KeyAction('discard_event')
Added shortcuts:
	shift+super+w KeyAction('close_os_window')
Changed shortcuts:
	shift+ctrl+e KeyAction('kitten', ('hints',))
```

**Additional context**
This problem occurs with an empty kitty configuration as well as an empty tintin++ configuration.  No special configuration is required to reproduce this issue.

Let me know if there is anything else I can do to assist in resolving this issue.  I realize that tintin++ isn't a mission critical application, but if kitty is behaving differently from most other terminals then perhaps there is something worth looking into here.  Thanks!

**Comment by page-down** [comment]
Cannot be reproduced in kitty nightly releases, Ubuntu Latest LTS, tintin++ Latest.

To me it seems you need the correct terminfo.

https://sw.kovidgoyal.net/kitty/faq/

**Comment by prg318** [comment]
I can confirm that using the latest git sources fixes this issue for me, but the issue is still present on v0.23.1.

I can confirm that I absolutely have the correct terminfo (xterm-kitty) and that it has been installed properly, so while I also thought to check the terminfo before posting this, it doesn't seem to be the case here.

If the issue has been fixed in the latest git master branch, then it's probably OK to close this since it should be fixed in the next kitty release.

Thanks all

**Comment by page-down** [comment]
XTMODKEYS will no longer be supported in future releases.

https://github.com/kovidgoyal/kitty/issues/4075

The author of tintin has reported a similar problem here and has also advised that the program needs to be updated to support the kitty keyboard protocol.
