### ISSUE TITLE
Q: Can I clear screen fully?

### ISSUE THREAD

**Issue by cathaysia** [kovidgoyal/kitty#4355]
When I use clear to clear screen, then use mouse scroll, I can see output before. Can I clear screen fully?
![Peek 2021-12-14 16-41](https://user-images.githubusercontent.com/42114817/145963404-8e6cfb01-1067-4036-bf77-ba9fc21e8823.gif)

1. cat .zshrc && cat .zshrc to fill the screen
2. then run clear
3. use mouse scroll up.

Then I can things that be shown before.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal
