### ISSUE TITLE
xterm-kitty is not set on remote

### ISSUE THREAD

**Issue by adrianmihalko** [kovidgoyal/kitty#4358]
**Describe the bug**
For some reason Kitty on the remote (Ubuntu 18.04) defaults to xterm-color:

```
$ echo $TERM
xterm-color
```

I red the FAQ, "`kitty +kitten ssh myserver`" should copy terminfo files. It did not, $TERM was still the default and nothing was copied into ~/.terminfo.

I then ran "`infocmp -a xterm-kitty | ssh myserver tic -x -o \~/.terminfo /dev/stdin`" which copied the files into:

```
$ ls .terminfo/x/
xterm-color  xterm-kitty
```

...but $TERM is still not set to xterm-kitty after connecting trough ssh.

I only want xterm-kitty on the remote, because without it viu is displaying images as half-blocks only.

**Comment by kovidgoyal** [comment]
kitty has no control of the TERM variable. Your shell's rc files and or
SSH are the places where it will be changed.
