### ISSUE TITLE
Add configuration option for Mac OS to extend the kitty window beyond obscured display areas in full screen mode

### ISSUE THREAD

**Issue by mrincredibleu** [kovidgoyal/kitty#4359]
**Is your feature request related to a problem? Please describe.**

On a 14 or 16 inch M1 Macbook Pro I would like to be able to extend the content area of the kitty window into the area that is covered by the camera cutout when kitty is in full screen mode (beyond the safeAreaInsets https://developer.apple.com/documentation/appkit/nsscreen/3882821-safeareainsets to the edge of the screen). For me personally the benefit of the additional usable screen space would greatly outweigh the detriment of having parts of the kitty window obscured by the cutout.

**Describe the solution you'd like**

Add a Mac OS specific option to kitty that increases the screen area occupied by the kitty window in full screen mode beyond the camera cutout.

**Describe alternatives you've considered**

Disabling 'Scale to fit below built-in camera' as described in https://support.apple.com/en-us/HT212842 and https://developer.apple.com/documentation/bundleresources/information_property_list/nsprefersdisplaysafeareacompatibilitymode results in kitty only getting extended up to the camera cutout in full screen mode, but not beyond it.

**Additional context**

The black bar at the top of this screenshot, taken in full screen mode, represents the area that contains the camera cutout  on a 14 inch M1 Macbook Pro.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/22705872/146171226-4c42d903-85aa-4b33-a531-f389311e0039.png">

Mac OS 12.1
Kitty 0.23.1

**Comment by kovidgoyal** [comment]
Not something I am going to spend time on personally, but a PR
is welcome.
