### ISSUE TITLE
Just Curious

### ISSUE THREAD

**Issue by levone1** [kovidgoyal/kitty#4362]
Just wondering about this - https://github.com/atanunq/viu/issues/45 - if you wouldn't mind taking a look.

Thanks for your work

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#i-am-using-tmux-and-have-a-problem

**Comment by levone1** [comment]
> https://sw.kovidgoyal.net/kitty/faq/#i-am-using-tmux-and-have-a-problem

Interesting...  One program I have found that also displays images nicely, is an abandoned Cargo project called Hunter, (sort of a Ranger alternative), which has a companion program, hunter-media, which does that part.  I guess that probably does the job because what you said here - https://github.com/tmux/tmux/issues/1391#issuecomment-403267557 - is implemented...

So, could someone possibly tinker with Tmux (or other) source code, and make it work similarly?

**Comment by levone1** [comment]
Update -  never mind about my comment about Hunter - I just realized that I've been using it with Kitty...

Anyway, my question still stands...

Thanks
