### ISSUE TITLE
Some nerd font icon glyphs don't expand to fill available space

### ISSUE THREAD

**Issue by harrisonthorne** [kovidgoyal/kitty#4364]
**Describe the bug**

Using Iosevka Nerd Font, It seems at least one glyph isn't expanding to fill any space in front of it. In the image below, the "closed folder" icon fills available space as expected, but the "open folder" icon (`nf-mdi-folder_open`, code `fc6e`) is still squished, no matter how many spaces there are in front of it.

![20211216-001000-s](https://user-images.githubusercontent.com/33523827/146317785-f3cddf23-4856-461d-800c-845ddd14fb8e.png)

**To Reproduce**

1. Using Iosevka Nerd Font, paste the following text into kitty and view the result: `ﱮ folder`.
2. Try adding or removing spaces after the folder icon and observe that the issue doesn't change.

**Environment details**

```
kitty 0.23.1 created by Kovid Goyal
Linux nixoslaptop 5.10.84 #1-NixOS SMP Wed Dec 8 08:03:30 UTC 2021 x86_64
<<< Welcome to NixOS 22.05.20211215.3c52ea8 (\m) - \l >>>

Run 'nixos-help' for the NixOS manual.
Running under:Wayland
Loaded config files:
  /home/harrison/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.9
bold_font               Iosevka Muse Bold
bold_italic_font        Iosevka Muse Bold Italic
font_family             Iosevka Muse
font_size               12.0
italic_font             Iosevka Muse Italic
Colors:
	active_border_color     #657b83   
	active_tab_background   #002b36   
	active_tab_foreground   #93a1a1   
	background              #002b36   
	color0                  #002b36   
	color1                  #dc322f   
	color10                 #859900   
	color11                 #b58900   
	color12                 #268bd2   
	color13                 #6c71c4   
	color14                 #2aa198   
	color15                 #93a1a1   
	color16                 #cb4b16   
	color17                 #d33682   
	color18                 #586e75   
	color19                 #657b83   
	color2                  #859900   
	color20                 #eee8d5   
	color21                 #fdf6e3   
	color3                  #b58900   
	color4                  #268bd2   
	color5                  #6c71c4   
	color6                  #2aa198   
	color7                  #839496   
	color8                  #073642   
	color9                  #dc322f   
	cursor                  #93a1a1   
	foreground              #93a1a1   
	inactive_border_color   #073642   
	inactive_tab_background #073642   
	inactive_tab_foreground #839496   
	selection_background    #93a1a1   
	selection_foreground    #002b36   
	tab_bar_background      #073642   
	url_color               #839496   

```

**Additional context**

Problem was able to be reproduced with `kitty --config NONE`.

Edit: Note: The Iosevka nerd font is a fallback to my main `Iosevka Muse` font. `Iosevka Muse` isn't patched; instead, Iosevka Nerd Font is installed alongside it.

**Comment by kovidgoyal** [comment]
U+fc6e is a defined character in unicode (as of version 1.1), the arabic ligature Beh. Using
it as a symbol is not going to work. Report the bug to nerd fonts.

https://www.compart.com/en/unicode/U+FC6E

**Comment by page-down** [comment]
This has been placed on the Nerd Fonts 3.0 WIP list (yesterday).

> Nerd Fonts 3.0.0 Target Features (WIP)
> - Remap all non-PUA glyphs so that they do not conflict with official unicode

https://github.com/ryanoasis/nerd-fonts/discussions/716

However, in my opinion, you still need to wait for the various (or, this) software updates to support nerd fonts 3.0, or patch the font and program yourself.

**Comment by harrisonthorne** [comment]
That explains a lot! I was also running into [this issue](https://github.com/ryanoasis/nerd-fonts/issues/574#issuecomment-964103697) where some icons would reverse an entire line of code.

Thanks!
