### ISSUE TITLE
Error activation tab bar

### ISSUE THREAD

**Issue by zzhaolei** [kovidgoyal/kitty#4367]
**Describe the bug**
When you click on the border at the bottom of the window, the top corresponding tab is activated.

**To Reproduce**
...

**Screenshots**
![image](https://user-images.githubusercontent.com/17561793/146502172-518ef25c-0138-4f23-a4da-d6e4fd153901.png)

**Environment details**
```
kitty --config=NONE -o tab_bar_edge top
```

**Additional context**
...

PS: Sorry, My English is terrible

**Comment by kovidgoyal** [comment]
I cannot reproduce running from master. I suggest you try the kitty
nightly build.

**Comment by page-down** [comment]
Oh, good catch. I can reproduce the issue under macOS.

```shell
kitty --config=NONE -o tab_bar_edge=top
```

- Create a new tab and a new kitty window.
- Switch to the tab with the two kitty windows.
- Click on the bottom edge of the window shown at the screenshot.

There is about 1px ~ 2px, and clicking the mouse will switch the tab on the top tab bar corresponding to the x-coordinate.

**Comment by zzhaolei** [comment]
Night builds have the same problem. I made a video

https://user-images.githubusercontent.com/17561793/146511876-f14c77c2-3bb8-4226-9535-06f91ef6df33.mp4

**Comment by zzhaolei** [comment]
I found another problem. In the full screen, place the mouse in the bottom left corner of the screen and double-click the left mouse button. This creates a new tab:

https://user-images.githubusercontent.com/17561793/146512847-26e5ea9d-1fec-4136-9cb8-43d787be1caa.mp4

**Comment by zzhaolei** [comment]
Both problems are more likely to recur in full screen mode

**Comment by kovidgoyal** [comment]
@page-down since you can repro it it should be an easy fix, relevant code is in mouse.c window_for_event

**Comment by Luflosi** [comment]
The problem was introduced in caa44b3d4a0c531cd85d8d865dc33827638bd26d, specifically the change to `window_for_event()`. Another side-effect of this change is that scrolling with the mouse wheel doesn't work in kitty when a different application is focused on macOS.

**Comment by kovidgoyal** [comment]
Note, I have not tested the fix, so please test.

**Comment by page-down** [comment]
I can confirm that the latest commit fixes this issue.
When another window gets focus, scrolling the mouse wheel in the window (with cursor focused) also responds properly.

However, it does not respond when the mouse is scrolled over a non-last active kitty window. (only works with the single last active kitty window in all OS windows)

**Comment by kovidgoyal** [comment]
I'm afraid I am not particularly a fan of the wheel-over-unfocused-window
thing, so I dont want to spend time on it, but patches are welcome.

**Comment by Kavantix** [comment]
@page-down Your fix is sadly only a partial fix. It does indeed correctly handle which window the mouse is on but it does not pass the new mouse position to the shell so for instance a vim split cannot be scrolled if the mouse wasn't over it last.

**Comment by page-down** [comment]
Oh, I didn't notice this. I rarely use the vim multi-panel feature.

The cursor position can be updated, hopefully this will not cause performance issues, or side effects.
