### ISSUE TITLE
Grid to fill entire window

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#4368]
Hello,

kitty, like any other terminal emulator, draws characters in a grid of cells. The size of each each, from what I can deduce, is determined by the font size (`font_size`) and the adjustment options (`adjust_line_height`  and `adjust_column_width`). This means, that the chance to have a grid that fully stretches from left to right and from top to bottom is small (most of the time, resulting in an unused space).

Can an option be added so that the size of each cell is adjusted so that the grid fills the entire size of the window?

If this feature is already implemented via some configuration option, please point me to it.

Thanks,
Mihai

**Comment by kovidgoyal** [comment]
You cannot do that since the window size may not be a multiple of the
cell size. If it is a multiple it will be filled. If not it wont.

**Comment by mihaicristiantanase** [comment]
So the cell size cannot be adjusted?

**Comment by kovidgoyal** [comment]
No, it cant, in general. The window size could be a prime number. And
even when it isnt, the adjustments to the cells sizes would be pretty
large, I would guess about 10% in pathological cases.

Use https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.resize_in_steps
instead. Though of course this wnt help you if you use Wayland or a
tiling WM.

**Comment by mihaicristiantanase** [comment]
If the size of a cell cannot be adjusted, then what's with the `adjust_line_height` and `adjust_column_width` options?

**Comment by kovidgoyal** [comment]
The size cannot be adjusted to make it a divisor of a prime number. That
would be mathematically impossible. https://en.wikipedia.org/wiki/Prime_number

**Comment by mihaicristiantanase** [comment]
I thought it's obvious: I'm referring to a *dynamic* size adjustment.

**Comment by mihaicristiantanase** [comment]
Probably you were to quick on dismissing the issue and hitting the *Close Issue* button.

**Comment by mihaicristiantanase** [comment]
Maybe someone else could suggest a better solution, but I'm thinking of a equal distribution of size to all cell up to the last and, the last cell gets what's left.

**Comment by kovidgoyal** [comment]
I dont know how else to say this. So let me ask you a simple question. Suppose the window is 929px wide. tell me what the cell width should be to make a whole number of cells fill the 929 pixels.

**Comment by kovidgoyal** [comment]
> Maybe someone else could suggest a better solution, but I'm thinking of a equal distribution of size to all cells up to the last and, the last cell gets what's left.

I have no interest in rendering partial cells, that would mean cut off text.

**Comment by mihaicristiantanase** [comment]
Cells are not cut, they are added to.

**Comment by kovidgoyal** [comment]
> Cells are not cut, they are added to.

Jesus christ. Again, window is 929x929 pixels wide, tell me what the cell size should be.
