### ISSUE TITLE
Kitty segfaults if iBus is killed

### ISSUE THREAD

**Issue by ariasuni** [kovidgoyal/kitty#437]
On GNU/Linux, iBus is used to type language with complex scripts, e.g. Japanese. If my system is configured to use iBus and that iBus works inside kitty; killing iBus make kitty crash with a segfault.

This is annoying because even if iBus crashing is rare, one need to restart iBus to apply some configuration change, and this cause kitty to crash. Also, kitty shouldn’t crash if the configured IME is buggy or unreliable.

**Comment by kovidgoyal** [comment]
From the next release kitty will not be using IME at all, for this amongst other reasons see #171
