### ISSUE TITLE
Extending selection by word behaves in a non-standard way

### ISSUE THREAD

**Issue by nertpinx** [kovidgoyal/kitty#4372]
**Describe the bug**
When drag-selecting by words (double click with the second click being a drag) the dragging extends the selection always in the nearest direction despite this not being a right-click extension.

**To Reproduce**
1. Start word-selection with dragging (double click drag) in the middle of the line
2. Move the cursor left to extend the selection left
3. Move the cursor down to extend the selection down
4. See that selection end moved properly, but selection start (abs_start.x) stays unchanged, while it should move to the original start ( abs_initial_start.x).

**Screenshots**
![2021-12-17-171949_3440x1440_scrot-edited](https://user-images.githubusercontent.com/670528/146576388-2421d18c-f215-4e97-b53e-2a56036cf1fb.png)
Sorry for the bad quality, hope that helps

**Environment details**
```
kitty 0.23.1 (81753706d3) created by Kovid Goyal
Linux wheatley 5.15.7-gentoo-dist #1 SMP Mon Dec 13 16:00:26 CET 2021 x86_64

This is wheatley.O (Linux x86_64 5.15.7-gentoo-dist) 17:53:22

Running under:X11
Frozen: False
Paths:
  kitty: /home/nert/dev/kitty/kitty/launcher/kitty
  base dir: /home/nert/dev/kitty
  extensions dir: /home/nert/dev/kitty/kitty
  system shell: /bin/fish

Config options different from defaults:
```

**Additional context**
I tried this with current master (commit 81753706d3d38c27639431d0666bb1d7a88f16fb) and --config NONE, also bisected the code and it got broken with commit e732df46b898e0eedea7643f4fca28ac51673945. Before that commit the right click extension worked the same way double-click drag should work, which is wrong and that commit fixed it, but double-click-drag worked properly. I tried finding out which part of the code to adjust, but unfortunately failed.

**Comment by kovidgoyal** [comment]
That's by design, as it is the way I like it.

**Comment by page-down** [comment]
I can understand why this is particularly troublesome sometimes.

There will be text on the direct mouse movement path.

![kitty_selection_1](https://user-images.githubusercontent.com/57713011/146660427-94f666da-a06b-4e68-9db3-58dd2612050a.png)

![kitty_selection_2](https://user-images.githubusercontent.com/57713011/146660441-5d2285fb-1bcc-48bb-a751-43bd4fe53543.png)

Take neovim as an example:

![neovim_selection](https://user-images.githubusercontent.com/57713011/146660453-2469221d-b5eb-4ae2-ae33-842f8930aedd.png)

**Comment by kovidgoyal** [comment]
Sure, I have no objections to an option.
