### ISSUE TITLE
Borders for a single window

### ISSUE THREAD

**Issue by medanimohamedakram** [kovidgoyal/kitty#4373]
I like using kitty with no title bar and only borders visible for a single window layout
so i set hide_window_decorations to yes but the borders are visible for me
I set single_window_margin_width 5 but the color for it is the same as the background
and I have no idea how to set the color for it

**Comment by kovidgoyal** [comment]
There are no borders for a single window. And if you dont want borders
at all you can hide them via kitty.conf. Yes margins are in the
background color what other color would they be in?

**Comment by medanimohamedakram** [comment]
any custom colors
but i mostly use dracula theme so purple would be fine

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in having separate margin colors, sorry.

**Comment by medanimohamedakram** [comment]
:)
