### ISSUE TITLE
prevent themes kitten from writing `theme_name` to kitty-config

### ISSUE THREAD

**Issue by zkamvar** [kovidgoyal/kitty#4375]
**Is your feature request related to a problem? Please describe.**

I use kitty on multiple computers and [I synch `kitty.conf` on them via a git repository](https://github.com/zkamvar/config-files/blob/master/kitty/kitty.conf).

When I run `kitty +kitten themes <theme name>`, the `kitty.conf` file is updated to state the theme name in the comments and creates a kitty.conf.bak file, which creates unstaged changes in my git repo. I like to switch between dark and light themes regularly and this adds an extra step in my workflow. 

**Describe the solution you'd like**

Add some configuration or indicator for the themes kitten to skip the following chunk of code:

https://github.com/kovidgoyal/kitty/blob/d65ed5993cdb2f2df2f428a5154f59e56b204406/kittens/themes/collection.py#L30-L36

**Describe alternatives you've considered**

Before the themes kitten, I had a keyboard shortcut that would load a specific theme.

**Comment by kovidgoyal** [comment]
Simply invoke it as

KITTY_CONFIG_DIRECTORY=/path/to/gitignored/directory kitty +kitten themes

And in kitty.conf add

include /path/to/gitignored/directory/kitty.conf

**Comment by kovidgoyal** [comment]
Oh and if you dont like setting env vars or using a directory, use

kitty + kitten themes --dump-theme theme name > /path/to/gitignoredfile.conf

and in kitty.conf include the above file.

**Comment by zkamvar** [comment]
I have created a directory in .config/kitty/ignore/ and have added `include ignore/kitty.conf` in my configuration file (while removing the kitty theme), but now I am finding that when I run

```bash
KITTY_CONFIG_DIRECTORY=~/.config/kitty/ignore/ kitty +kitten themes
```

and select a theme and select "m" to modify the config file, kitty crashes and I have to restart the session.

**Comment by kovidgoyal** [comment]
Make sure ~/.config/kitty/ignore/ exists before running the kitten

**Comment by zkamvar** [comment]
It does exist, but it still crashes. 

This is what the tree of my config looks like (the `theme.conf` file is from an earlier version of kitty where I had created a remote-control shortcut to symlink themes from the kitty-themes folder):

```
$ tree -lL 2 ~/.config/kitty/
~/.config/kitty/
├── ignore -> ~/config-files/kitty/ignore/
│   ├── catppuccin.conf
│   ├── current-theme.conf
│   ├── kitty.conf
│   └── kitty.conf.bak
├── kitty-themes
│   ├── CONTRIBUTING.md
│   ├── LICENSE.md
│   ├── README.md
│   └── themes
├── kitty.conf -> ~/config-files/kitty/kitty.conf
└── theme.conf -> ./kitty-themes/themes/3024_Day.conf
```

**Comment by kovidgoyal** [comment]
Doesn't crash for me, although the term "crash" is completely
ill-defined. I assume you mean it exits with an error, post the error.
Or just use --dump-theme instead.

**Comment by zkamvar** [comment]
## Crash only happens with the interactive menu for the themes kitten 

"crash" in this case means that all of the windows in the current kitty session close, so there was no error message to be had. If I start a new kitty session from the terminal and execute the command to cause the "crash", this is the output I get:

```
[355 13:49:54.441306] WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation
User defined signal 1: 30
```

## using `--dump-theme`

If I add the theme name as suggested (e.g. `kitty +kitten themes --dump-theme PaperColor Light > /path/to/theme.conf`), then the theme is written and I need to invoke `kitty @ set-colors --all path/to/theme.conf` to set the colors. This works, but I have to know the theme name in advance and remember the exact spelling, which is not ideal, but it will work.  

However, the crash behaviour also happens if I use `kitty +kitten themes --dump-theme > /path/to/theme.conf` (without the theme name).

**Comment by kovidgoyal** [comment]
dup of #3952
