### ISSUE TITLE
flatpak appimage support

### ISSUE THREAD

**Issue by rickysarraf** [kovidgoyal/kitty#438]
It would be nice to have kitty available as a flatpak or appimage monolithic bundle.
Flatpak and AppImage are new, distribution independent methods of shipping software, that can be closely in line with the way upstream wants to ship software.

https://flatpak.org/
https://appimage.org/

**Comment by kovidgoyal** [comment]
Not worth the effort to me. kitty will become available in most distro repositories (I know of existing packages for arch, gentoo, nixos, opensuse and upcoming packages for debian and fedora) over the coming year and in addition it is trivial to build and run directly from source.  

As such, I dont find the effort of building standalone binaries worthwhile. If someone wishes to contribute them, they are welcome. You'd do it by creating a kitty packager similar to the current macOS build system (see the kitty branch of https://github.com/kovidgoyal/build-calibre).

**Comment by kovidgoyal** [comment]
See #595

**Comment by kovidgoyal** [comment]
Standalone binaries of kitty are already available at: https://sw.kovidgoyal.net/kitty/binary/
