### ISSUE TITLE
Can't get Kitty to render icons correctly

### ISSUE THREAD

**Issue by mattdanhall** [kovidgoyal/kitty#4381]
Kitty won't display icons correctly no matter what I try.
I've tried using [icons-in-terminal](https://github.com/sebastiencs/icons-in-terminal), patched Nerd Fonts, and unpatched Nerd Fonts as per the [guidance here](https://github.com/kovidgoyal/kitty/issues/3884#issuecomment-889195612).
I'm using the [Monofonto font](https://typodermicfonts.com/monofonto/), and the standalone Nerd Font icons for that attempt.

Comparison of Kitty and GNOME terminal using icons-in-terminal for reference:
![terminal_comparison](https://user-images.githubusercontent.com/33754538/146953264-e9a270ce-a96b-4b6b-b061-5f68389fb8af.png)

How Kitty looks using symbol_map:
![symbol_map](https://user-images.githubusercontent.com/33754538/146956678-4efb907e-9fd4-4bc7-b06f-fbc2ebd773cd.png)

My config is as follows:
```
font_family             Monofonto
symbol_map              U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B Symbols Nerd Font
font_size               10.0
scrollback_lines        2000
window_padding_width    12
enable_audio_bell       no
adjust_line_height      8
tab_bar_min_tabs        2
cursor_shape            underline
allow_remote_control    true
window_border_width     2.0pt
```

`$ locale`
returns the following:
```
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```
But it works on GNOME terminal, so I'm not sure whether that is relevant, but saw it in other issues.

Any help/advice is much appreciated.

Kitty version 0.23.1

**Comment by kovidgoyal** [comment]
Did you actually install Symbols Nerd Font? Run with --debug-font-fallback and see what font is used when rendering a problematic symbol. That will tell you what the issue is.

**Comment by mattdanhall** [comment]
I did - I can see it on the list of fonts installed.
However, --debug-font-fallback is throwing up quite a few other fonts being used.

Do you have any idea why icons-in-terminal wouldn't work? It's a very neat solution so would be great to be able to use.

**Comment by kovidgoyal** [comment]
I have no idea what icons-in-terminal is. Assuming you setup the
symbol_map correctly and you have Symbols Nerd Font installed, you can
simply printf '\u<unicode code>' to see the symbol in the terminal.
Replace <unicode code> above with an actual code for a symbol you want
to see

**Comment by mattdanhall** [comment]
Using --debug-font-fallback I'm seeing that the apps I'm trying to use are using different Unicode to Nerd Fonts, despite claiming compatibility.
Thanks for your help and have a great day

**Comment by mattdanhall** [comment]
And [icons-in-terminal](https://github.com/sebastiencs/icons-in-terminal) allows you to get any fonts in your terminal without replacing or patching your font.

**Comment by kovidgoyal** [comment]
Ah ok. You dont need to patch fonts to use icons in kitty, anyway.
