### ISSUE TITLE
Kitty shrinks itself after computer idle.

### ISSUE THREAD

**Issue by patrickfenn** [kovidgoyal/kitty#4382]
**Describe the bug**
When accessing my computer after a long idle time (like after I sleep), the Kitty terminal will somehow minimize itself to no bigger than the red circle you see on the top of the window bar. Like the only thing I see is the small red dot (which of course if I click would just close it). Has anyone encountered this? 

**To Reproduce**
1. Leave pc for multiple hours (no hibernation or anything)
2. Access PC
3. Kitty will be shrunk to small red dot.

**Screenshots**
https://i.imgur.com/w07JHhk.png

**Environment details**
I'm on fedora 35.

kitty 0.21.2 created by Kovid Goyal
Linux 155-186-112-169.res.spectrum.com 5.15.10-201.fsync.fc35.x86_64 #1 SMP Sun Dec 19>
\S
Kernel \r on an \m (\l)
Running under:Wayland
```

**Comment by kovidgoyal** [comment]
That will be something your window manager is doing, not kitty.
