### ISSUE TITLE
PermissionError n.13

### ISSUE THREAD

**Issue by thatfatblackcat** [kovidgoyal/kitty#4385]
## Detailed Description
Kitty is trying to access a directory that the user can't read or execute.
Eg. When you access root shell with `sudo -i` and try to open a tab from `/root` instead of `$HOME`.

```
Traceback (most recent call last):
  File "kitty/child.py", line 205, in __init__
  File "kitty/child.py", line 49, in cwd_of_process
  File "posixpath.py", line 391, in realpath
  File "posixpath.py", line 439, in _joinrealpath
PermissionError: [Errno 13] Permission denied: '/proc/25897/cwd'
```

## How to Reproduce
1. Create the conditions where the user can't read/execute a directory.
2. Open the system journal following the output with `journalctl -f`.
3. Open a new tab or window from the directory created on step (1).
4. Check if the exception is printed on the journal as expected.

Just updated and tested on Kitty 0.23.1 (Pop!_OS 21.10).

**Comment by kovidgoyal** [comment]
You are asking kitty to open a new window in the cwd of the current
window. To do that kitty must read the cwd of that process, for which it
doesnt have prmission. So that error is entirely to be expected.
