### ISSUE TITLE
Kitty Config per OS system?

### ISSUE THREAD

**Issue by rationalthinker1** [kovidgoyal/kitty#4387]
I save my kitty config on github. I use kitty on Mac and on Linux. However, the shortcuts are different on both of them. On Mac , I use `meta` instead of `ctrl` on Windows. I always have to modify it on Mac whenever I'm using it from ctrl to meta in the config. Is there any solution to this?

**Comment by kovidgoyal** [comment]
Use 

include ${HOSTNAME}.conf

and put your host specific config in those config files. Assuming
HOSTNAME is defined in whatever environment you are running kitty from.
