### ISSUE TITLE
Kitty freezes randomly

### ISSUE THREAD

**Issue by glazenbol** [kovidgoyal/kitty#4391]
**Describe the bug**
Since a few days, kitty randomly freezes, and also freezes other processes for a while. Other programs recover and become responsive again, but kitty doesn't. It then also doesn't respond to SIGTERM and has to be killed with SIGKILL. It also freezes when it is hidden. The strange part about the bug is that it also happens when I am using alacritty, which is also GPU based. I think it has something to do with that. Any help would be appreciated.

**To Reproduce**
1. Run kitty (with or without default config)
2. After a while, it freezes and becomes completely unusable.

**Environment details**
kitty 0.23.1 created by Kovid Goyal
Linux orange 5.15.9_1 #1 SMP Thu Dec 16 17:16:21 UTC 2021 x86_64
Void \r (\n) (\l)
Running under:X11
Loaded config files:
  /home/glazenbol/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style (True, False)
disable_ligatures     1
font_family           Fira Code
tab_bar_min_tabs      1
tab_bar_style         separator
tab_separator         
tab_title_template     {title} 
Colors:
	active_tab_background #073642   
	active_tab_foreground #eee8d5   
	background            #fdf6e3   
	color0                #073642   
	color1                #dc322f   
	color10               #586e75   
	color11               #657b83   
	color12               #839496   
	color13               #6c71c4   
	color14               #93a1a1   
	color15               #fdf6e3   
	color2                #859900   
	color3                #b58900   
	color4                #268bd2   
	color5                #d33682   
	color6                #2aa198   
	color7                #eee8d5   
	color8                #002b36   
	color9                #cb4b16   
	cursor                #586e75   
	foreground            #657b83   
	selection_background  #475b62   
	selection_foreground  #eae3cb

**Comment by kovidgoyal** [comment]
THis will be a GPU driver issue. Probably mesa related. If either your
GPU dirvers or mesa were updated recently, rollback the updates and you
should be fine.

**Comment by glazenbol** [comment]
Thank you for the quick response!
