### ISSUE TITLE
Support short link urls

### ISSUE THREAD

**Issue by 0jrp0** [kovidgoyal/kitty#4396]
**Is your feature request related to a problem? Please describe.**
Our company intranet defines extremely short hostnames as shortcuts to various internal services. It's quite common to refer to these links without any protocol. Some examples (using >> to mean redirect):

  * b/1234 >> http://b/1234 >> http://fqdn/1234

**Describe the solution you'd like**

The code here requires :// to be a part of URLs:
https://github.com/kovidgoyal/kitty/blob/93dbcab10a1f44b4dc01da2dd50d3bd3c88fc05f/kitty/line.c#L50

I'd like to be able to specify a list of `short_url_names` that linkifies bare URLs in the terminal. This means that I can click on 'b/1234' and then http://b/1234 is what's sent to the browser. Short URL names will always use HTTP protocol.

**Describe alternatives you've considered**

The alternative is to do nothing and make code comments / Markdown docs, etc. conform to requiring http:// in the URL.

The implementation will have caveats ... there may be the occasional false positive. However, in my experience, the upside will outweigh any risks in false positive links.

**Comment by page-down** [comment]
You can do something similar to what you described by using kitten hints and hyperlink open-actions.

But I don't think it makes sense to identify any text with a slash as an http-only link as an config option.

**Comment by 0jrp0** [comment]
Thanks! I'll take a look at hints and open-actions.

For clarity, I wasn't proposing "to have characters with slashes recognized as http only links".

I was proposing "to have an explicit user-specified allowlist of valid non-fqdn hostnames that precede a slash bounded by word boundaries and potentially trailing invalid url characters as implicit http links".

Example text where links would be applied (assuming issue and build were added to the allowlist):

  * Here is a sample sentence talking about issue/4396
  * Another one that talks about build/foo/123. (in this case, only build/foo/123 is highlighted since it's common to end a sentence with a period but not include it in url)

Example text where links would not be applied:

  * There's a problem in /path/to/issue/4396 (the slash preceding issue would disqualify it as a link)
  * Let's make sure the regular expression group works: (build/foo/\d+|build/bar/\d+) (the parentheses and pipe would disqualify it)

**Comment by kovidgoyal** [comment]
As @page-down hinted, you can use the hints kitten to do this. I am not willing to support custom regexes for link detection on mouse movement. https://sw.kovidgoyal.net/kitty/kittens/hints/

**Comment by page-down** [comment]
I noticed that hints does not yet support mouse clicks.

For detecting arbitrary regular expressions on mouse movement, I think it would make more sense to have kitten hints support mouse-click confirmation and perform custom action when selected.

@kovidgoyal Do you think this is acceptable?

**Comment by kovidgoyal** [comment]
I have nothing against it.
