### ISSUE TITLE
also check width of arrow keys, backspace and del when enable internal wcwidth

### ISSUE THREAD

**Issue by xhebox** [kovidgoyal/kitty#44]
e.g. `😂` will remain the left part when typing **backspace <-**.

**Comment by kovidgoyal** [comment]
Internal wcwidth should only be used if the program you are running in the terminal is also using an up to date wcwidth. It is not the terminal's responsibility to make backspace, etc. work with wide characters, it is the client program that has to send the correct number of backspaces, cursor movement commands and so on. 

You can test this by using some wide character known to your system wcwidth, then you will see that backspace, etc work correctly in shells, vim, etc. 

If the terminal started changing how backspace, cursor movement, etc command worked based on the wcwidth implementation, then it would break for all characters in which the system wcwidth and the internal wcwidth agree.
