### ISSUE TITLE
More powerful zoom capabilities

### ISSUE THREAD

**Issue by piggyslasher** [kovidgoyal/kitty#440]
This is more of a feature request / enhancement. I've searched the docs.
1) Is it possible to include zoom level as a command line argument?
2) Would it be feasible to let kitty windows have their own zoom level? Rather than have one set shared zoom level? This is one thing I can't do in Tmux but use all the time in iterm. Simple because I like having having different zooms for windows that are running webpack and running vim. Various programs work best at certain zoom levels
3) Related to (2) - Can we set zoom level in the session file? This would be the icing on the cake.

**Comment by kovidgoyal** [comment]
1. -o font_size=whatever
2. No, all windows share the same font cache to reduce VRAM memory usage. You can however have different font sizes in different kitty instances.
3. No, since (2) is not possible.
