### ISSUE TITLE
Color Bugged?

### ISSUE THREAD

**Issue by logan-lieou** [kovidgoyal/kitty#4400]
**Describe the bug**
Output from gtest is no color: google/googletest#3455

**To Reproduce**
1. Write google test
2. Run google test
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/20232318/147648837-3adea8b0-a856-4b80-9db7-a50e2b14ce00.png)

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Kernel \r on an \m (\l)
Running under:X11
Loaded config files:
  $HOME/kitty/kitty.conf

Config options different from defaults:
background           Color(red=40, green=40, blue=40)
cursor               Color(red=146, green=131, blue=116)
font_family          Fira Code
font_size            12.0
foreground           Color(red=235, green=219, blue=178)
selection_background Color(red=60, green=56, blue=54)
selection_foreground Color(red=146, green=131, blue=116)

```

**Additional context**
Other terminals working (gnome terminal) is this bug w way kitty handle colors?:
![image](https://user-images.githubusercontent.com/20232318/147649000-60465152-0812-47ee-9ca9-f4f249340bd8.png)

**Comment by page-down** [comment]
This has nothing to do with kitty. I found the root of the issue after a brief look at the documentation.

https://github.com/google/googletest/blob/release-1.11.0/docs/advanced.md

> You can set the `GTEST_COLOR` environment variable or ... to `yes`, `no`, or `auto` (the default) ...
> When the value is `auto`, googletest will use colors **if and only if** ... the `TERM` environment variable is set to `xterm` or `xterm-color`.

Please report this back to the googletest maintainers and suggest them to use a better way to detect color support.
