### ISSUE TITLE
double left click to copy a file name with column number instead of only file name.

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#4401]
**Is your feature request related to a problem? Please describe.**

I want copy a line with line number.  e.g. assume following line content exists in
kitty.

```
test/graphql/mutations/chat_mutations/send_red_packet_test.rb:240:in `block in <class:SendRedPacketTest>'
```

when i double click left key on this line, i want to copy following content: (as in konsole)

```
test/graphql/mutations/chat_mutations/send_red_packet_test.rb:240:in
```

But for now, kitty is do a smart optimize to only copy those content before `:`, like this:

```
test/graphql/mutations/chat_mutations/send_red_packet_test.rb
```

Can i fallback to use old behavior?

Thank you.

**Comment by trygveaa** [comment]
See https://sw.kovidgoyal.net/kitty/conf/?highlight=word#opt-kitty.select_by_word_characters

**Comment by zw963** [comment]
It works after add `:` into it `select_by_word_characters`, thank you!
