### ISSUE TITLE
Unable to set tab title with ctrl+shift+alt+t on Ubuntu 20.04 [Fixed]

### ISSUE THREAD

**Issue by aphivantrakul** [kovidgoyal/kitty#4403]
**Describe the bug**
Unable to set the tab title using ctrl+shift+alt+t on Ubuntu 20.04. When the keys are pressed, nothing happens. Fix is to go to Settings -> Keyboard Shortcuts -> Launchers -> disable "Launch terminal (Ctrl + Alt + T)" shortcut. This is not really a bug, but I just wanted to bring awareness that new Kitty users may be experiencing this issue and may not know how to solve it.

**To Reproduce**
1. Open kitty terminal
2. Press ctrl+shift+t to open a new tab
3. Press ctrl+shift+alt+t to try to set title of new tab but nothing happens.

**Environment details**
Ubuntu 20.04.3 LTS
GNOME version 3.36.8

**Comment by kovidgoyal** [comment]
Not sure why this is a kitty bug. kittyha no control over window manager level keyboard shortcuts.
