### ISSUE TITLE
Ctrl+z in Vim don't work with hyperlinked_grep

### ISSUE THREAD

**Issue by Louis-dM** [kovidgoyal/kitty#4406]
**Describe the bug**
`Ctrl+z` does not work in Vim when a linked is opened with the `hyperlinked_grep` kitten. Usually in Vim, when in Normal mode, `Ctrl+z` takes you into a terminal. A bit like `:!` but you can do multiple commands before returning to Vim (which is done by entering `fg` into the terminal).

**To Reproduce**
1. Perform a search with the `hyperlinked_grep` kitten
2. `Shift+Ctrl+Click` one of the links to open the link in Vim
3. Make sure you are in Normal mode, then press `Ctrl+z`. The screen flickers briefly, but other than that, nothing happens.

To reproduce the expected behaviour:
1. Open a file with Vim the "usual" way i.e. typing `vim filename` into the terminal
2. Making sure you are in Normal mode, press `Ctrl+z`. You should be taken to a terminal window.

**Environment details**
Kitty version: 0.23.1
OS: Fedora 35 workstation
Kitty config: empty
Other notes: I pretty much exactly followed the setup instructions for `hyperlinked_grep` at this link: https://sw.kovidgoyal.net/kitty/kittens/hyperlinked_grep/ (except for using a different alias, not that the alias name matters). The contents of `~/.config/kitty/open-actions.conf` is identical to what's on the website.

**Comment by page-down** [comment]
If you configured `open-actions.conf` according to the documentation, then obviously vim will open in a kitty window (overlay), where there is no shell, so ctrl+z will not work.

https://sw.kovidgoyal.net/kitty/kittens/hyperlinked_grep/

If you expect to run vim from the shell, then you should configure the `send_text` action in `open-actions.conf`.

**Comment by Louis-dM** [comment]
Sorry, I'm new to Linux (and to using terminals in this much depth) so it's not obvious to me!

> If you expect to run vim from the shell, then you should configure the `send_text` action in `open-actions.conf`.

How do I do this? I've tried replacing both occurences with `action launch --type=overlay` with `send_text` but that doesn't work - it opens the file in gedit instead (and this happens even when I try replacing `${EDITOR}` with `vim`, and even when I add `export EDITOR=vim` to my bashrc...)

The file I'm testing this is on is just my `kitty.conf`, if that's relevant.

**Comment by page-down** [comment]
Try replacing the sample configuration in the documentation with the following.

open-actions.conf

```text
protocol file
fragment_matches [0-9]+
action send_text normal vim +${FRAGMENT} ${FILE_PATH}\r
```

This configuration means that the vim command is sent to the current window with a carriage return key in the current shell. Note that your cursor should be at the prompt, and that no other text is entered.

**Comment by Louis-dM** [comment]
@page-down that works perfectly, thank you! But where is the documentation for this? I wasn't able to find it anywhere on the website.

And... is the default behaviour intentional? What's the advantage of running vim in an overlay?

**Comment by page-down** [comment]
send_text
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Send-arbitrary-text-on-key-presses
https://sw.kovidgoyal.net/kitty/remote-control/#kitty-send-text

launch
https://sw.kovidgoyal.net/kitty/launch/

This is because it runs vim accurately and is not affected by shell situations. Using send_text does not ensure accurate execution. For example, if you type `echo` and then click on the link output by hyperlinked_grep, the vim command will be echoed out as is.

The default configuration is always the one that ensures that it will work properly. If there is something more needed, it is up to the user to configure.

**Comment by Louis-dM** [comment]
I see. Is there a way to send keys like `ctrl` before sending the text? In particular, `ctrl+u` clears the text on the prompt, which would prevent your `echo` example (or other text in the prompt) from going wrong.

On the second of your links I've seen it says
> The text follows Python escaping rules. So you can use escapes like x1b to send control codes
but I can't figure out the syntax for the control codes (asuming it is possible)

**Comment by page-down** [comment]
Run the following command and press the key combination you need. These are the terminal escape codes and you can search for additional information if you want to know.

kitty +kitten show_key

**Comment by Louis-dM** [comment]
> Run the following command and press the key combination you need. These are the terminal escape codes and you can search for additional information if you want to know.
> 
> kitty +kitten show_key

Oh that's perfect, thank you! All working as expected now :)
