### ISSUE TITLE
Unicode Regional Letters brake rendering / movement

### ISSUE THREAD

**Issue by arandomliz** [kovidgoyal/kitty#4407]
**Describe the bug**

Using Unicode Regional Letters results in a broken output.

**To Reproduce**
1. Copy this code in e.g. `ipython3` or similar:
```python
"🇩🇪🇪🇨".replace("🇪🇪", "🇬🇦")
```
2. see output
3. try to move cursor

What happens is that rendering is broken, especially when going to the start of the line one can see that kitty interprets the beginning of the text to be somewhere completely else. Even trying to use `echo` and that line above has some issues when trying to move around. Especially the rendering gets mixed up trying to do so by new characters being written in places with a huge offset. (e.g. when scroll to left and ipython doesn't highlight the brackets anymore)

There is no such behavior in Gnome Terminal, the movement inside the line is quite deterministic. 

**Screenshots**
Comparison Gnome Terminal (left) vs. Kitty (right) with the same line

![image](https://user-images.githubusercontent.com/14364148/147794937-a9449b71-4e41-450b-9874-2a22b74bfd3b.png)

**Environment details**
I've tried using the `Ubuntu Mono` font which is used by the Gnome Terminal and activated ligatures without any change in behavior. It seems to be a general problem.

**Comment by page-down** [comment]
kitty_tests/datatypes.py

```python
class TestDataTypes(BaseTest):
    def test_utils(self):
        # ...
        # Regional indicator symbols (unicode flags) are defined as having
        # Emoji_Presentation so must have width 2
        self.ae(tuple(map(w, '\U0001f1ee\U0001f1f3')), (2, 2))
```

I tested `printf "\U0001f1ee\U0001f1f3"` and it doesn't render under macOS, and opening the file containing a flag sequence in neovim shows blank.
