### ISSUE TITLE
EDITOR not recognized via edit_config_file when using a config

### ISSUE THREAD

**Issue by dcraig327** [kovidgoyal/kitty#4409]
**Describe the bug**
edit_config_file is launching nano and not EDITOR or VISUAL.
when using kitty --config NONE it works properly.

**To Reproduce**
1. export EDITOR=nvim
in ~/.bashrc
2. open kitty
3. ctrl+shift+F2

**Screenshots**

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux box 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64
EndeavourOS Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=EndeavourOS
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME=rolling
Running under:X11
Loaded config files:
  $HOME/.config/kitty/kitty.conf

Config options different from defaults:
none. fresh install.  the user config is the default 100% commented out config.
```

**Additional context**
verified EDITOR and VISUAL are set in the environment.
```
$ set|grep EDITOR; set|grep VISUAL
EDITOR=nvim
VISUAL=nvim
_=VISUAL=nvim
$ ls -la `which nvim`
-rwxr-xr-x 1 root root 5076112 Dec 29 15:43 /usr/bin/nvim
```

`kitty --config NONE` 
works properly

**Comment by kovidgoyal** [comment]
~/.bashrc has no effect since it controls the environmnet in *bash* not
kitty. You want to set EDITOR *systemwide* aka in /etc/environment or
whatever your distro uses or in kitty.conf
