### ISSUE TITLE
MesloLGS NF font icons clipped on macOS

### ISSUE THREAD

**Issue by devkvlt** [kovidgoyal/kitty#4411]
**Describe the bug**
Font icons are slightly clipped / shifted to the left.
- Font: MesloLGS NF (https://github.com/romkatv/powerlevel10k-media)
- OS: macOS Monterey 12.1

**To Reproduce**
1. Install powerlevel10k (https://github.com/romkatv/powerlevel10k)
2. Open the terminal

**Screenshots**
![](https://s2.loli.net/2022/01/01/RXCMzseBnqGxb4J.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin Heavensky 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Loaded config files:
  /Users/aa/.config/kitty/kitty.conf

Config options different from defaults:
bold_font        MesloLGS NF Bold
bold_italic_font MesloLGS NF Bold Italic
font_family      MesloLGS NF Regular
italic_font      MesloLGS NF Italic

```

**Additional context**
The issue can't be reproduced with zero config.
Minimal config:
```
bold_font        MesloLGS NF Bold
bold_italic_font MesloLGS NF Bold Italic
font_family      MesloLGS NF Regular
italic_font      MesloLGS NF Italic
```
I should also mention that I use the same font on iTerm and Alacritty and there is no issue.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by devkvlt** [comment]
Thanks for the quick reply.
I've actually already read that but it only explains the problem without providing a fix.
Is there no fix at all?

**Comment by kovidgoyal** [comment]
1) Dont use patched fonts
2) Use symbols from the PUA unicode area
3) Ensure there is a space character after the symbol and kitty will use
two cells to render it

**Comment by devkvlt** [comment]
I guess I'll just stick to Alacritty.
