### ISSUE TITLE
Connect directly to video card and keyboard

### ISSUE THREAD

**Issue by beroal** [kovidgoyal/kitty#4413]
I wonder whether Kitty can connect directly to a video card and a keyboard similar to virtual terminals in the Linux kernel. Comparing to virtual terminals in the Linux kernel, Kitty is more pleasant. On machines where a command-line interface is enough, it wouldn't require to install and configure a desktop environment just to show one terminal window.

**Comment by kovidgoyal** [comment]
Not as far as I know, patches are welcome.
