### ISSUE TITLE
run kitty.desktop directly on GNOME + Wayland,  a cat icon appear on on the top-left corner, and could not find this process from `wmctrl -lx`.

### ISSUE THREAD

**Issue by zw963** [kovidgoyal/kitty#4414]
**Describe the bug**

When i start kitty directly from GNOME + Wayland use normal way, e.g. pressing Win key, and then search kitty, run it.

i get kitty like this

![image](https://user-images.githubusercontent.com/549126/147869454-1fbbaec6-0c0d-4d5c-89f9-7ed06d30d885.png)

as you can see, a cat appear on top-left corner, but, current process not visible when i run `wmctrl -lx`.

Then, when i ruby kitty from command line,  new started kitty works as expected.

![image](https://user-images.githubusercontent.com/549126/147869508-870be812-3c95-4c29-b3cb-6deb5be053fd.png)

I guess this maybe a environment variable issue? anyway, i create this issue for report this unexpected behavior.

thank you.

**Comment by kovidgoyal** [comment]
You are running kitty under X in one case and Wayland in the other. I have no idea why, read whatever desktop file you are using.

**Comment by zw963** [comment]
Yes, i knew it, thank you, i force to run on X11 with:

linux_display_backend "x11", it works now.

**Comment by zw963** [comment]
The reason cause this is: i set KITTY_DISABLE_WAYLAND=1 environment somewhere, the latter kitty process can use this env.
