### ISSUE TITLE
kitty doesn't exit when a zsh session is ended within it

### ISSUE THREAD

**Issue by ogost** [kovidgoyal/kitty#4415]
**Describe the bug**
I'm really not sure how to reproduce this bug. Occasionally, when I press CTRL+D to exit, the zsh session within will exit, but the kitty will remain open. Couldn't pin down the exact cause for this behavior - seems to be very random.

**To Reproduce**
Unable to reproduce

**Screenshots**
Not applicapable

**Environment details**
```
kitty 0.19.3 created by Kovid Goyal
Linux t480 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64
Debian GNU/Linux 11 \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/tsogoo/.config/kitty/kitty.conf
Running under: Wayland

Config options different from defaults:
background_opacity    0.8
enable_audio_bell     False
update_check_interval 0.0
```

**Additional context**
Not sure if it's a configuration error on my end (if so please excuse me and close the issue), but it doesn't happen on foot and other  terminals.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death
