### ISSUE TITLE
Kitty wont launch

### ISSUE THREAD

**Issue by K4LCIFER** [kovidgoyal/kitty#4416]
**Describe the bug**
When launching kitty, either from running `kitty` from the command line or clicking the destkop icon, a transparent window will flash into existance for a brief moment then instantly crash.

**To Reproduce**
1. Install Kitty
2. Try and launch kitty
3. Observe crash

**Screenshots**
![unshtastknown](https://user-images.githubusercontent.com/7829231/147900897-41c15889-5128-40ef-962c-09c982c26aee.png)

![unknown](https://user-images.githubusercontent.com/7829231/147900899-95b8cff8-aa87-4f29-b184-c32e998e59c0.png)

**Additional context**
launching kitty from the command line yields the follwowing output
```
[002 21:03:56.716951] [glfw error 65544]: on_gnome_cursor_theme_read: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
[002 21:03:56.716980] [glfw error 65544]: on_gnome_cursor_size_read: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
zsh: segmentation fault (core dumped)  kitty
```

Gnome Wayland on Arch Linux
Nvidia GTX 1080 with proprietary driver 495

**Comment by kovidgoyal** [comment]
This will almost certainly be a gpu driver bug, but generate a backtrace
and post it to be sure.

**Comment by K4LCIFER** [comment]
> This will almost certainly be a gpu driver bug, but generate a backtrace
> and post it to be sure.

How do I generate a backtrace?

**Comment by kovidgoyal** [comment]
That will depend on your distro, assuming it is setup correctly, the
most common way is

echo bt | coredumpctl gdb

**Comment by kovidgoyal** [comment]
no followup
