### ISSUE TITLE
kitten hints cannot remove quotes when matching file names

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4419]
**Describe the bug**
When using kitten hints to match filenames, filenames wrapped in quotation marks will be matched with leading quotation marks.

**To Reproduce**
```text
echo '"textfile.txt"'
# press ctrl+shift+p>f (kitten hints --type path --program -)
# select
# This will output: "textfile.txt
```

**Screenshots**
n/a

**Environment details**
kitty from master branch

**Additional context**

Because the end quotes will not be matched when matching file names, post_processors will not work effectively to remove the matching quotes.

```python
    elif args.type == 'path':
        pattern = r'(?:\S*?/[\r\S]+)|(?:\S[\r\S]*\.[a-zA-Z0-9\r]{2,7})'
        post_processors.extend((brackets, quotes))
```

```python
@postprocessor
def brackets(text: str, s: int, e: int) -> Tuple[int, int]:
    # Remove matching brackets

@postprocessor
def quotes(text: str, s: int, e: int) -> Tuple[int, int]:
    # Remove matching quotes
```

I suspect the same issue exists with pairwise removal of brackets.

I see that version 0.24 has been released, but I haven't solved this issue yet, so I decided to post it.

**Comment by page-down** [comment]
Actually, this issue was discovered when I was trying to match file names with spaces in them.

Currently the kitten hints default rule does not match file names with spaces, I tried the following ls command.

```shell
ls --quoting-style=c
ls --quoting-style=escape
```

```text
'text file.txt'
text\ file.txt
```

Only the last part with the extension can be matched.

And for paths starting with / enclosed in quotation marks, the entire path cannot be matched either.

```text
"/tmp/text file.txt"
-> "/tmp/text
-> file.txt
```

Escape style:

```text
/tmp/text\ file.txt
-> /tmp/text\
-> file.txt
```

**Comment by kovidgoyal** [comment]
You cannot match arbitrary filenames, that will lead to too many false positives, since filenames are basically completely free form text. If you are trying to get it to work with ls, use ls --hyperlink=auto and ctrl+sjift+p>y

**Comment by page-down** [comment]
Yes, for example, in escape style, many characters have escaping possibilities. So it is not suitable as a default rule.

For me personally, it is enough to handle only spaces `\ ` (escape style), and I can use custom regular expressions for that.
