### ISSUE TITLE
Option to anchor background image to screen coordinates

### ISSUE THREAD

**Issue by trathborne** [kovidgoyal/kitty#4425]
**Is your feature request related to a problem? Please describe.**
The origin of a tiled background image is at the origin (top left) of the window, so the background image moves with the window. I would like the option to keep the background image aligned with the screen, so that as the window moves around the background stays in place.

**Describe the solution you'd like**
I'd like to see a new option `background_image_anchor window|screen` (default to screen)

**Additional context**
I used to do this in gnome-terminal on a non-composited desktop. I set the gnome background to a blurred, shaded, and otherwise processed version of some wallpaper, then overrode the actual background with `xv -root`. This allowed me to have fake translucent windows. I don't want transparent terminals, because I don't want to see other windows under my terminal. I want to see a processed background. See attached example from 2003 (!)

![infrared-terminals](https://user-images.githubusercontent.com/1091889/148065287-61719f67-3ddd-4dca-b7ed-38f6f5ed6b89.png)

**Comment by kovidgoyal** [comment]
Not something I am interested in, but patches are welcome.
