### ISSUE TITLE
Font icons become inappropriately larger

### ISSUE THREAD

**Issue by c02y** [kovidgoyal/kitty#4427]
**Describe the bug**
I don't know why this happens, font icons in kitty used to work fine like alacritty, but they suddenly become inappropriately larger in kitty. 
- I tried kitty v0.23 and v0.24,
- I tried to reboot my OS
- I tried to use the default kitty.conf
- I tried to use the same font as alacritty, but alacritty with the default config or with my config, it works the fine as kitty used to

**To Reproduce**
1. try `ranger` (with icons enabled)
2. try `lsd -l`
3. try `exa --icons -l`

**Screenshots**
In the first screenshot, alacritty and kitty are both using default config, if I set font of them to the same which is Cascadia Mono PL in my config for both terminal, the result is the same, one is bigger, one is appropriate.

![image](https://user-images.githubusercontent.com/2135996/148070192-e3dc5a10-7483-4016-81ea-bf53284cdfcc.png)

In the second screenshot, both alacritty and kitty are using the same font `Cascadia Mono PL` and my own config file which I use daily.
![image](https://user-images.githubusercontent.com/2135996/148071714-3cd531c3-7456-4a1e-a4ed-22b119f05c9d.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Dont put spaces after your icons, then they will be rendereded in a
single cell. https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by c02y** [comment]
> Dont put spaces after your icons

How can I control this?

I got your another solution from https://github.com/kovidgoyal/kitty/issues/4411#issuecomment-1003557042
```
> 1. Dont use patched fonts
> 2. Use symbols from the PUA unicode area
> 3. Ensure there is a space character after the symbol and kitty will use
>    two cells to render it
```

1. I use default font from default kitty.conf or use `Cascadia Mono PL` from its official website, not patched, it has the same problem.
2. and 3
3. how can I do these, from an end user's perspective?


It works fine for old kitty, is it impossible to restore it?

There are dozens of similar issues that you posted the FAQ link, so maybe kitty itself can fix it once for all instead of workarounds

Did you have this kind of issue, how did you fix it exactly? Is there anything I can use directly to fix this, such as your kitty.conf?

**Comment by kovidgoyal** [comment]
Not sure what you are asking. kitty will render PUA symbols in two cells if the font they come from says they are wide icons and a space is present after the icon. If you want narrow icons, you either use a font that has narrow versions of the icons or you ensure there are no spaces after the icons. 

Rendering wide icons in available space is a *feature* and is the correct thing to do. That it leads to results you dont like in this case is unfortunate, but doesnt change that.

**Comment by c02y** [comment]
Anyway, I just tried font `CaskaydiaCove Nerd Font Mono`, it works fine now, `BUT` is it patched version of `Cascadia Mono PL`

For anyone has the same kind of issue, solution is:
1. install nerd-fonts-cascadia-code package if you are using Archlinux or grab CascadiaCode.zip file from https://github.com/ryanoasis/nerd-fonts/releases/
2. set `CaskaydiaCove Nerd Font Mono` as the font in kitty.conf, not `CaskaydiaCove Nerd Font`, it won't fix this issue
