### ISSUE TITLE
ZSH issues with v0.24.0

### ISSUE THREAD

**Issue by ldelossa** [kovidgoyal/kitty#4431]
**Describe the bug**
I build kitty from source. 

When upgrading to v0.24.0 zsh now complains when entering directories. 

```
🖭  cd c
_zsh_highlight_call_widget: maximum nested function level reached; increase FUNCNEST?
~/git/c
```

When I downgrade back to v0.23.1 this error goes away. 

I'm not a zsh expert but it appears that Kitty maybe recursively execing the shell process in 24.0? 

**To Reproduce**
* Use Zsh
* Use kitty 0.24.0
* Open a directory which will cause zsh to trigger its highlight call widget function

**Screenshots**

**Environment details**
```
Key action failed

debug_config
(25, 'Inappropriate ioctl for device')

Press Enter to close.
```

**Additional context**

The problem does go away when "kitty --config NONE" is used, but this also does not open "zsh" and instead opens bash first, and makes me shell int zsh, which I don't think demonstrates the issue well.

**Comment by kovidgoyal** [comment]
dup of #4428
