### ISSUE TITLE
Make the chorded keys discovereable like "which-key"

### ISSUE THREAD

**Issue by chmouel** [kovidgoyal/kitty#4432]
**Is your feature request related to a problem? Please describe.**

It could be nice to be able to discover all the "chorded keys"  so when we forget which binding has been set we can easily see them

**Describe the solution you'd like**

with the same UI kitty has for emoji or others, we could show all  keys following the chorded keys. Editors has that same concept like [emacs](https://github.com/justbur/emacs-which-key) or [vim](https://github.com/liuchengxu/vim-which-key)/[nvim](https://github.com/folke/which-key.nvim), for example on neovim when pressing the leader key and wait for a bit it would show all possible keybinding that can go right after 

![image](https://user-images.githubusercontent.com/98980/148081491-3859ee7a-e1d0-4a5c-b5ea-fdaede594237.png)

maybe a timeout would be good or just a ? after the chord key?

**Describe alternatives you've considered**

grep the bindings in my kitty/config file :)

**Additional context**

**Comment by Luflosi** [comment]
On macOS an alternative would be to add more of the bindings to the menu bar, where they can be searched and the key bindings are easily visible.

**Comment by kovidgoyal** [comment]
this can be implemented as a kitten. I might get around to doing it
someday, but its not a high priority for me, patches are welcome in the
meantime.

**Comment by kovidgoyal** [comment]
And if someone does want to implement it, I will be happy to provide any
needed guidance.

**Comment by page-down** [comment]
The key list is a feature I've thought about, and after configuring a lot of keys, I can't remember all of them myself.

If the floating window, status bar related features mentioned in other issues can be implemented, similar helper features can be better done in kitty.

Currently I bind all "chorded keys" with the question mark key `modifiers+key>? ` and display the grep result in the overlay when pressed.

```shell
kitty -o 'map kitty_mod+p>? launch --type=overlay sh -c \'rg "map kitty_mod\\+p>" ~/.config/kitty/kitty.conf; read\''
```

**Comment by thanhph111** [comment]
This is a good friendly-beginner feature. I think we can integrate into the (planned) command palette (#3865) so we don't have to scatter user behaviors. Before that, a discussion to decide on a good design for floating windows base (as page-down mentioned) might be a good idea.
