### ISSUE TITLE
cursor_text_color doesn't seem to properly work

### ISSUE THREAD

**Issue by ndavd** [kovidgoyal/kitty#4433]
version: `kitty 0.24.0`

Hi, I have the following settings on my `kitty.conf`:
```conf
cursor #cccccc
cursor_text_color #111111
```

Until recently, when using vim, the cursor text color was `#111111` but now it seems to be whatever is underneath.

![image](https://user-images.githubusercontent.com/74260683/148092047-4598c433-3ade-4e15-9e4e-5461e7940099.png)

**Comment by tigerjack** [comment]
Not sure if it's related, but with the latest update of kitty and kitty-terminfo on Arch Linux (`0.23.1-2 -> 0.24.0-1`) the cursor stops working properly. For once, as reported by OP, the color changed randomly. Also, the cursor displayed by default changed to beam even if I explicitly commented out the `cursor_shape block` line in the config file. Finally, inside vim, the shape of the cursor doesn't change to beam when switching to insert mode.

**Comment by kovidgoyal** [comment]
if you dont eant a beam cursor at your shell, use

shell_integration no-cursor 

in kitty.conf

I cannot reproduce cursor not changing to beam in vim.

**Comment by page-down** [comment]
If you run vim in kitty with the default settings `vim -u NONE`, the cursor will not change to beam when you enter insert mode.

This must be configured for vim.

https://github.com/kovidgoyal/kitty/issues/4234#issuecomment-968204329

I think the above recommended configuration for vim could be considered to be included in the FAQ.

**Comment by kovidgoyal** [comment]
On Tue, Jan 04, 2022 at 09:46:52AM -0800, page-down wrote:
> If you run vim in kitty with the default settings `vim -u NONE`, the cursor will not change to beam when you enter insert mode.
> 
> This must be configured for vim.

That's always been the case, nothing about it has changed in 0.24.0

> 
> https://github.com/kovidgoyal/kitty/issues/4234#issuecomment-968204329
> 
> I think the above recommended configuration for vim could be considered to be included in the FAQ.

This is basically the case in vim for all terminals, it isnt kitty
specific as far as I know.

**Comment by page-down** [comment]
> That's always been the case, nothing about it has changed in 0.24.0
> This is basically the case in vim for all terminals, it isnt kitty specific as far as I know.

Yes, you are right.

Anyway, just configure vim as suggested above and the cursor will work fine.

**Comment by tigerjack** [comment]
@kovidgoyal @page-down thanks for the help, using the shell_integration option and adding the configuration lines to vim fixed my issue.

**Comment by ndavd** [comment]
yeah that doesn't seem to be related with this issue. glad you have figured it out though :]

**Comment by ndavd** [comment]
glad you figured it out :]
I don't think my issue is related to that though

**Comment by kovidgoyal** [comment]
I cannot replicate this with:

```
kitty --config=NONE -o cursor=\#ccc -o cursor_text_color=\#111 vim setup.py
```

The text under the block cursor is black as expected regardless of the
color of the text.

**Comment by ndavd** [comment]
@kovidgoyal the issue occurs with termguicolors and I'm pretty sure this wasn't happening on the previous kitty version since I didn't change my vim config

**Comment by kovidgoyal** [comment]
What's termguicolors? I am going to need aminimal reproducer to help you
further.

**Comment by ndavd** [comment]
okay so the problem is not with termguicolors after all sorry.
I use neovim and I have this setting (block cursor in all modes, horizontal bar in insert and replace):
```vim
set guicursor=a:block-Cursor,i-r:hor20-Cursor
```
If it comment that out it behaves normally.

**Comment by ndavd** [comment]
hmm removing the `a:block-Cursor` part made it work normally. Thanks!
