### ISSUE TITLE
Double click should select whole word when it is placed on two lines

### ISSUE THREAD

**Issue by kapsh** [kovidgoyal/kitty#444]
When long path or url was wrapped to second line (e.g. terminal width is too small) double click selects only one part of it.

![image](https://user-images.githubusercontent.com/144717/38470432-519ee058-3b6b-11e8-96f5-baa806217321.png)
In this example the whole "/usr/.../xwe" should be selected.

**Comment by kovidgoyal** [comment]
you're welcome :)
