### ISSUE TITLE
Support alpha channel in set-tab-color

### ISSUE THREAD

**Issue by kbd** [kovidgoyal/kitty#4441]
I've been playing with the new `set-tab-color` and thought it'd be fun to write a `direnv` hook to automatically set the color of the tab to the colors set in my vscode workspace (set with the [Peacock extension](https://www.peacockcode.dev/)).

This bit of `jq` will take your vscode workspace settings if they exist and set the kitty tab color:

```bash
[[ -f .vscode/settings.json ]] && <.vscode/settings.json jq -r '."workbench.colorCustomizations" | {
  active_fg: (."titleBar.activeForeground"[:7] // "NONE"),
  active_bg: (."titleBar.activeBackground"[:7] // "NONE"),
  inactive_fg: (."titleBar.inactiveBackground"[:7] // "NONE"),
  inactive_bg: (."titleBar.inactiveBackground"[:7] // "NONE"),
} | to_entries | map("\(.key)=\(.value)")[]' | xargs kitty @ set-tab-color
```

Only, the colors set by Peacock use the alpha channel, and kitty doesn't support that. I truncated the colors (`[:7]` above) to remove the alpha channel to get it to work, but of course then the colors don't look right. It works great otherwise!

It looks like you intend to support an alpha channel (in `fast_data_types.Color`) but don't currently. It would be nice if this was supported so I could send RGBA colors to `set-tab-color` without conversion.

**Comment by kovidgoyal** [comment]
tabs are rendered using a terminal screen internally. Terminals dont
really support alpha channels for colors. Changing that would require
completely changing color handling on terminals or changing how the tab
bar is rendered. Either of those is too large a change for thisuse case,
sorry.

**Comment by kbd** [comment]
Without changing the rendering, would it be possible to still support color codes with alpha by converting internally from RGBA->RGB?

**Comment by kovidgoyal** [comment]
It's possible, but why?

**Comment by kbd** [comment]
Because there are many times when you have an existing color code with alpha (eg. it's supported in CSS, and in my example above where I'd like to use color codes directly from my vscode config) and it would be wonderful to be able to use them directly within kitty.

I don't know much about color spaces, but it looks like it's [not too involved to convert](https://stackoverflow.com/questions/2049230/convert-rgba-color-to-rgb), so it'd be great if kitty could accept #grba or #rrggbbaa and convert them to #rgb #rrggbb.

**Comment by kovidgoyal** [comment]
Doesnt seem a very compelling use case to me, but patches are welcome.

**Comment by kittywitch** [comment]
It would be appreciated if kitty got RGBA support so that I could have an explicitly transparent background without resorting to background_opacity settings. My system is already supposed to do this, but kitty renders it as entirely black instead.
