### ISSUE TITLE
Starship prompt doesnt draw aws cloud icon in 0.24 (but does in 0.23.1)

### ISSUE THREAD

**Issue by clue44** [kovidgoyal/kitty#4444]
**Describe the bug**
Kitty 0.24 has a regression in how it renders the cloud icon in the starship prompt (not related to starship prompt of course, just an example of the bug appearing). In version 0.23.1 of kitty it renders a cloud icon and in version 0.24 it renders underline characters instead.

**To Reproduce**
1. Install starship prompt (from starship.rs) and use it with zsh shell in kitty 0.24.
2. The prompt is missing the cloud icon (see screenshot 2)
3. Switch back to kitty 0.23.1:

In arch linux I use pacman to revert to previous package versions like this:
`sudo pacman -U kitty-0.23.1-2-x86_64.pkg.tar.zst kitty-terminfo-0.23.1-2-x86_64.pkg.tar.zst`

4. After restart of kitty, the prompt has the cloud icon again (see screenshot 1)

**Screenshots**
![image](https://user-images.githubusercontent.com/42569344/148208461-260f334d-4583-481b-bfa0-0f5a69ec15c6.png) (kitty 0.23.2 - has cloud icon)
![image](https://user-images.githubusercontent.com/42569344/148209180-0b7703b0-1b44-49bb-837f-87e87e64accf.png) (kitty 0.24 - has underline characters instead of cloud icon)

**Environment details**
```
kitty 0.24.0 created by Kovid Goyal
Linux archstation 5.15.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 29 Dec 2021 12:04:52 +0000 x86_64
Arch Linux 5.15.12-zen1-1-zen (pts0)

Running under:Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

This debug output has been copied to the clipboard
```

**Additional context**
I can reproduce this issue with `kitty --config NONE` as well. 

So something changed in version 0.24. I can switch back and forth between kitty 0.24 and 0.23.1 with config = NONE and see the cloud icon appear and disappear between versions and not changing anything else. So I feel confident its a regression bug in kitty causing this.

**Comment by Slotos** [comment]
Nerd Font icons don't draw at all with the new version. Which might not be a statement against kitty, given nerd fonts issues over the years.
I did try to check functionality with constituent fonts: IEC power symbols, devicons. Instead of nothing being drawn, empty boxes were displayed. Which I'm not sure how to interpret.

Here's minimal reproduction case for those who know how to work with fonts better than I do.

### Reproduction:

Glyph fonts:

https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-1000-em%20Nerd%20Font%20Complete.ttf
https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf

Kitty config:

```
symbol_map U+E5FA-U+E62B Symbols Nerd Font Mono
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
symbol_map U+E200-U+E2A9 Symbols Nerd Font Mono
symbol_map U+F500-U+FD46 Symbols Nerd Font Mono
symbol_map U+E300-U+E3EB Symbols Nerd Font Mono
symbol_map U+F400-U+F4A8,U+2665,U+26A1,U+F27C Symbols Nerd Font Mono
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CC-U+E0D2,U+E0D4 Symbols Nerd Font Mono
symbol_map U+23FB-U+23FE,U+2b58 Symbols Nerd Font Mono
symbol_map U+F300-U+F313 Symbols Nerd Font Mono
symbol_map U+E000-U+E00D Symbols Nerd Font Mono
symbol_map U+f101-U+f208 Symbols Nerd Font Mono
```

Test string (zsh, fish, maybe newer bash versions):

```zsh
printf '\uF07C\n\uf121\n\ue004\n\uf310\n\u2b58\n'
```

**Comment by page-down** [comment]
`kitty +list-fonts` to confirm that the fonts can be listed.
`kitty --debug-font-fallback` to confirm which fonts are loaded.

Is it possible to install the font properly under Linux?

```text
~/.local/share/fonts/Symbols-1000-em Nerd Font Complete.ttf
```
I run `fc-list` under Ubuntu and it doesn't list the font.

**Comment by kovidgoyal** [comment]
Icons that are properly in the PUA blocks (private use) will render fine. Icons that repurpose actual unicode code points may or may not render. Depending on the code point in question. Using assigned unicode code points is really a bug in nerd fonts and needs to be fixed there.

I dont know what codepoint the cloud is from, but the following tst works fine for me in Linux:

```
kitty --debug-font-fallback --config=NONE sh -c "printf '\uF07C  \uf121  \ue004  \uf310  \u2b58  '; read"

U+f07c Face(family=Symbols Nerd Font, style=1000-em, ps_name=SymbolsNerdFontComplete-1000-em, path=/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf, index=0, is_scalable=True, has_color=False, ascender=800, descender=-200, height=1000, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49) (new face)
U+f121 Face(family=Symbols Nerd Font, style=1000-em, ps_name=SymbolsNerdFontComplete-1000-em, path=/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf, index=0, is_scalable=True, has_color=False, ascender=800, descender=-200, height=1000, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
U+e004 Face(family=Symbols Nerd Font, style=1000-em, ps_name=SymbolsNerdFontComplete-1000-em, path=/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf, index=0, is_scalable=True, has_color=False, ascender=800, descender=-200, height=1000, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
U+f310 Face(family=Symbols Nerd Font, style=1000-em, ps_name=SymbolsNerdFontComplete-1000-em, path=/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf, index=0, is_scalable=True, has_color=False, ascender=800, descender=-200, height=1000, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
U+2b58 Face(family=Symbols Nerd Font, style=1000-em, ps_name=SymbolsNerdFontComplete-1000-em, path=/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf, index=0, is_scalable=True, has_color=False, ascender=800, descender=-200, height=1000, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
```
![screenshot](https://user-images.githubusercontent.com/1308621/148237689-e77640a2-f298-4490-b887-9271560d5988.png)

**Comment by page-down** [comment]
I can reproduce this issue under Linux. It works fine under macOS.

```text
e2 98 81 ef b8 8f
```

```shell
printf '\xe2\x98\x81\xef\xb8\x8f'
```

**Comment by kovidgoyal** [comment]
On Wed, Jan 05, 2022 at 08:22:30AM -0800, page-down wrote:
> I can reproduce this issue under Linux. It works fine under macOS.

If the font isnt showing up under fc-list for you then it will
not render in kitty either. You need to fix that first:

fc-list| grep -i nerd                                                                                                                    
/usr/share/fonts/TTF/Symbols-1000-em Nerd Font Complete.ttf: Symbols Nerd Font:style=1000-em

**Comment by page-down** [comment]
For now, let's not worry about why I can't install this font on my Ubuntu.

I mean, this looks clearly like an emoji `U+2601`. Does Emoji need this font too?

The hex code above is what I found from the possible variable values in starship.

**Comment by kovidgoyal** [comment]
If U+2601 is the cloud character in question, then that's not from NERD fonts and this entire issue is moot. You simply need to have a font with the glyph for that. On my system that's 

```
U+2601 bold Face(family=DejaVu Sans Mono, style=Bold, ps_name=DejaVuSansMono-Bold, path=/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf,
```

Install that and make sure its higher priority that Noto CJK, iether via font config or symbol_map in kitty.conf and you will be fine. I believe symbola will also have that symbol if you dont want to use dejavu

**Comment by kovidgoyal** [comment]
Or is the issue actually with \u2601\ufeof i.e. with the variation selector to convert \u2601 to emoji presentation?

**Comment by page-down** [comment]
U+23ce is the <return> of the fish shell, so don't worry about it yet.

`\u2601\ufeof` This seems to be the problem.

**Comment by Slotos** [comment]
Reproduction still results in no output on macOS.
However, it seems to be linked to 2048em variant of Symbols font.

With both font variants installed (empty output):
```
❯ kitty --debug-font-fallback zsh -c "printf '\uF07C\uf121\ue004\uf310\u2b58'; read"
[006 12:43:57.530012] Preloaded font faces:
[006 12:43:57.530040] normal face: /System/Library/Fonts/Menlo.ttc
[006 12:43:57.530050] bold face: /System/Library/Fonts/Menlo.ttc
[006 12:43:57.530058] italic face: /System/Library/Fonts/Menlo.ttc
[006 12:43:57.530065] bi face: /System/Library/Fonts/Menlo.ttc
[006 12:43:57.530074] Symbol map faces:
[006 12:43:57.530082] /Library/Fonts/Symbols-2048-em Nerd Font Complete Mono.ttf
```

With only 1000em font installed:
```
❯ kitty --debug-font-fallback zsh -c "printf '\uF07C\uf121\ue004\uf310\u2b58'; read"
[006 12:45:09.958586] Preloaded font faces:
[006 12:45:09.958613] normal face: /System/Library/Fonts/Menlo.ttc
[006 12:45:09.958623] bold face: /System/Library/Fonts/Menlo.ttc
[006 12:45:09.958631] italic face: /System/Library/Fonts/Menlo.ttc
[006 12:45:09.958638] bi face: /System/Library/Fonts/Menlo.ttc
[006 12:45:09.958646] Symbol map faces:
[006 12:45:09.958656] /Library/Fonts/Symbols-1000-em Nerd Font Complete Mono.ttf
```

kitty.conf:
```
font_size 14.0

symbol_map U+E5FA-U+E62B Symbols Nerd Font Mono
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
symbol_map U+E200-U+E2A9 Symbols Nerd Font Mono
symbol_map U+F500-U+FD46 Symbols Nerd Font Mono
symbol_map U+E300-U+E3EB Symbols Nerd Font Mono
symbol_map U+F400-U+F4A8,U+2665,U+26A1,U+F27C Symbols Nerd Font Mono
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CC-U+E0D2,U+E0D4 Symbols Nerd Font Mono
symbol_map U+23FB-U+23FE,U+2b58 Symbols Nerd Font Mono
symbol_map U+F300-U+F313 Symbols Nerd Font Mono
symbol_map U+E000-U+E00D Symbols Nerd Font Mono
symbol_map U+f101-U+f208 Symbols Nerd Font Mono
```
