### ISSUE TITLE
[idea] Support including config from another file

### ISSUE THREAD

**Issue by kapsh** [kovidgoyal/kitty#445]
Kitty has really lot of settings and quite lenghty config file. And sometimes can be useful to have logically separated parts of configuration in different files - one for basic settings, another for keybindings and so on.

Another use case. Let's imagine that someone wants to play with color schemes. Currently he have to edit configuration and remember what was changed or comment/uncomment experimental parts. I think it would be convenient change single line (something like `include cool-colors.conf`) instead.

**Comment by SolitudeSF** [comment]
[already implemented](https://github.com/kovidgoyal/kitty/commit/1c78633d1a45d9f15d6365566328353d265b6467) in master

**Comment by kapsh** [comment]
@SolitudeSF thank you for pointing this out. I assumed that there is no such feature by using current release.
