### ISSUE TITLE
Drag & Drop text is not working

### ISSUE THREAD

**Issue by EliasTheDev** [kovidgoyal/kitty#4450]
**Drag & Drop text is not working**

Hi! I recently re-installed arch linux on my machine, I used to normally drag and drop text from my browser to the terminal, when I installed it this time, it didn't work for me. Any reason why? Thanks!

**Environment details**
```
kitty 0.24.0 created by Kovid Goyal
Linux arch 5.15.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 29 Dec 2021 12:04:52 +0000 x86_64
Arch Linux 5.15.12-zen1-1-zen (/dev/tty2)

Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/enigma/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.3
dynamic_background_opacity True
font_family                Hack Nerd Font
```

**Comment by kovidgoyal** [comment]
Works fine for me from chromium to kitty under Arch, X11. There havent been any changes to this functionality in a long time as far as I know.
