### ISSUE TITLE
Can creating a window split pane automatically resize all panes so that vertical or horizontal space is split evenly ?

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#4453]
Is it be possible for terminal window split panes to be automatically resized so that vertical space and horizontal space is split evenly between panes ? else can this be added somehow ?

---

iTerm offers a great example of this:

![Jan-05-2022 21-52-57](https://user-images.githubusercontent.com/36056254/148288645-6615dad5-a36b-4dab-baa6-57f9cd44fb58.gif)

Notice how when there's one vertical pane, it takes up 100%, then when there is two panes they each take 50%, then when there's three, they each take 33%, then when there's 4 each take 25%,... you get the point. this also applies for horizontal panes and it also applies to "nested" panes (whatever you wanna call them), i.e the bottom panes within the second vertical pane.

**Describe alternatives you've considered**

I've tried all the layouts, with `bias` but cannot get what I want, so far I have it like this: 

```properties
enabled_layouts splits:bias=50;split_axis=horizontal
```

And achieve this: (this is kitty)

![Jan-05-2022 21-56-27](https://user-images.githubusercontent.com/36056254/148288887-ca99ff57-3763-481c-83ca-12246bc1f788.gif)

It's nice and close, but not quite what's sought for. here each subsequent pane takes up half the current pane space it is created from.

**Comment by page-down** [comment]
You can use either horizontal or vertical layout.

https://sw.kovidgoyal.net/kitty/layouts/#the-horizontal-layout
https://sw.kovidgoyal.net/kitty/layouts/#the-vertical-layout

If you want the split layout to achieve an even layout, then this feature has not been implemented yet.

https://github.com/kovidgoyal/kitty/issues/4212

**Comment by kovidgoyal** [comment]
dup of #4212

**Comment by akharrou** [comment]
Is there any possibility of combining `vertical` and `horizontal` layouts ? to have the freedom of splitting like `splits` ?
