### ISSUE TITLE
Is it possible to have an iTerm like hotkey window ?

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#4454]
Sometimes you're quickly going back and forth between spaces and programs and it would be really nice if you could, from anywhere, instantly toggle kitty in and out of view and focus.

**Describe the solution you'd like**
iTerm offers a great example solution with its hotkey feature: `Preferences > Profile > Keys > Configure Hotkey Window`. At a press of a key, or double press of a modifier key, the terminal just appears (or fades) into view and focus, and at when pressed again, disappears (or fades out), returning focus to whatever you were doing.

---

**Describe alternatives you've considered**

So far I've tried using Alfred's: `Alfred > Workflows > Launch Apps (Toggle visibility for apps)`, which essentially seems to trigger a "Hide" and "Open" on the program it is configured to trigger.

#### Issue `#1`: quickly toggle kitty in and out of view/focus

It works great. however it only works great when `macos_hide_from_tasks` is set to `no`, but doesn't toggle out of focus when it is set to `yes`, understandably because it is hidden, but this is unfortunate because, that option is rather desirable, as it keeps kitty clear from docks and tab app switcher.

I also tried setting `macos_hide_from_tasks` to `yes` and using Alfred to toggle it into view/focus and kitty's native macos "Hide kitty" command (normally `cmd+h`) to toggle it out of view/focus, but for some reason, the hide can't be triggered...

#### Issue `#2`: don't get relocated spaces upon toggling in and out of view/focus

Also, another issue that kitty has, and that iTerm somehow doesn't have, is that, when you toggle the terminal into view/focus, you get moved to the space the kitty window was initially in, which is quite frustrating, especially if you move a lot because you have to move back to the correct space every time. iTerm doesn't have this issue, in iTerm, when you switch to the terminal, from whatever space you're in, the window just appears within that space, without moving you anywhere, this is very ideal.

---

Here's iTerm's hotkey window in action: (toggled via pressing a keybinding)

![Jan-05-2022 23-22-43](https://user-images.githubusercontent.com/36056254/148297994-7e291105-e82e-4415-b13a-6f23631a7906.gif)

**Comment by page-down** [comment]
I recommend using hammerspoon.

https://github.com/Hammerspoon/hammerspoon

```lua
hs.hotkey.bind({'option'}, '1', function() hs.application.launchOrFocusByBundleID('net.kovidgoyal.kitty') end)
```

**Comment by kovidgoyal** [comment]
this is the job of the window manager not individual applications. There is an existing issue that describes the solutions for this for various window managers already. As for switching to the space, on macOS switching to a window switches to its space as far as I know, that's the native behavior intended by Apple. There maybe some way to overrideit, if so a patch adding an option for it to kitty is welcome.

**Comment by akharrou** [comment]
> I recommend using hammerspoon.
> 
> https://github.com/Hammerspoon/hammerspoon
> 
> ```lua
> hs.hotkey.bind({'option'}, '1', function() hs.application.launchOrFocusByBundleID('net.kovidgoyal.kitty') end)
> ```
> 
> For the second issue you mentioned, maybe try to see if it can be achieved.

Hey, thanks for the suggestion, I tried the shortcut, and it works to get kitty into view and focus, but doesn't seem to print it out of focus. Am I doing something wrong, or is there another command to get it out of view and focus ?

**Comment by page-down** [comment]
Sorry I couldn't give the full script here, but more scripts are needed if you want to implement the toggle feature.

Please refer to the following links

https://github.com/kovidgoyal/kitty/issues/45

https://github.com/jhkuperus/dotfiles/blob/master/hammerspoon/init.lua

Or look for solutions in the Hammerspoon project community.

**Comment by akharrou** [comment]
✅  https://github.com/kovidgoyal/kitty/issues/45#issuecomment-573196169
