### ISSUE TITLE
Cursor does not stay the same as configured

### ISSUE THREAD

**Issue by r2dev2** [kovidgoyal/kitty#4456]
**Describe the bug**
When I open kitty in bash, the cursor is a vertical line, when I type in sudo password, it's a block, and when I'm in vim, it's an underline. I have set the cursor to be an underline in my kitty configuration.

**To Reproduce**
1. run `kitty` to open kitty, notice the vertical cursor
2. run anything requiring user input like `python3`, notice the block cursor
3. run vim, notice the underline cursor

**Screenshots**
![vertical bash cursor](https://user-images.githubusercontent.com/50760816/148333356-3261e876-25c5-46f1-b65e-cd313d59c480.png)
![block python cursor](https://user-images.githubusercontent.com/50760816/148333394-19e4a59f-4af2-4002-966f-fa28e4f792ef.png)
![underline vim cursor](https://user-images.githubusercontent.com/50760816/148333428-38f7ba47-3905-41aa-8f64-c3838b6dc9ac.png)

**Environment details**
```
kitty 0.24.0 created by Kovid Goyal
Linux ar2ch 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64
Arch Linux 5.15.12-arch1-1 (pts0)

Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:
```

I run arch linux with XFCE desktop environment. The bug started during the update when these packages were upgraded to the following versions: xorg v21.1.3, kitty v0.24.0, qt v5.15.2.

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

With `kitty --config NONE` I get the unintended change to a block cursor when starting `python3`.

**Comment by kovidgoyal** [comment]
The cursor wil be bar only at the shell prompt, courtesy of kitty's shell interation. Everywhere else the cursor will be the default or whatever that program has set it to be.

**Comment by r2dev2** [comment]
Sorry, I figured out that this is a duplicate of #4445 right after posting this. Fix is to add `shell_integration disabled` to kitty conf.

It would be nice if there was a warning upon upgrading from an earlier version to add this.

**Comment by page-down** [comment]
If you just don't like the cursor being changed, you can also configure `shell_integration  no-cursor`.

https://sw.kovidgoyal.net/kitty/shell-integration/
