### ISSUE TITLE
Updated to 0.24.0 and cursor_shape block stopped working

### ISSUE THREAD

**Issue by jn-novasol** [kovidgoyal/kitty#4458]
**Describe the bug**
I have the setting "cursor_shape block" set and it was working.
Then I updated Kitty and now I get the straight line instead.

**To Reproduce**
Updated Kitty to latest version on Arch.

**Environment details**
```

~ took 2s ❯ pacman -Ss kitty | grep installed
community/kitty 0.24.0-1 [installed]
community/kitty-terminfo 0.24.0-1 [installed]

~ ❯ kitty -v
kitty 0.24.0 created by Kovid Goyal

~ ❯ uname -srm
Linux 5.15.12-arch1-1 x86_64

~ ❯ cat .config/kitty/kitty.conf
shell zsh
enable_audio_bell no
allow_remote_control yes
include ./theme.conf
cursor_shape block

**Comment by page-down** [comment]
The new shell integration feature changes the shape of the cursor.

If you just don't like the cursor being changed, you can configure `shell_integration  no-cursor`.

https://sw.kovidgoyal.net/kitty/shell-integration/

**Comment by jn-novasol** [comment]
That works, thanks a bunch @kovidgoyal

**Comment by tranquangdat-w** [comment]
thanks, that worked
