### ISSUE TITLE
macOS "Open With kitty.app"

### ISSUE THREAD

**Issue by cole-wilson** [kovidgoyal/kitty#4460]
**Is your feature request related to a problem? Please describe.**
This feature request is *not* related to a problem.

**Describe the solution you'd like**
I would like to be able to set kitty as the default opener for certain file types (like `*.txt` files). Once kitty has "opened" the document, it would pass the filename(s) off to a program of the user's choice (like their `$EDITOR`).

For example: 
    1. A user opens Finder on MacOS
    2. The user "double clicks" a text file
    3. kitty would then launch `vim %s` in a new window or tab, substituting the path

This feature likely be useful for Linux as well, although I am only a macOS user.

**Describe alternatives you've considered**
I have tried bundling my own custom `*.app`s that will launch kitty themselves, but they are very cumbersome to use and require XCode. In addition, they meet Gatekeeper issues with launching external executables. I believe that this feature would be a good addition to kitty, rather than using eternal tools.

**Example Screenshot:**
![image](https://user-images.githubusercontent.com/49500253/148423887-551ae852-6277-4edf-b142-97736f6056bd.png)

**Comment by cole-wilson** [comment]
Note (if easy enough to develop): It would also be great if custom file icons could be applied (such as the Chrome icon on the .html file) by users.

**Comment by kovidgoyal** [comment]
This is very much macOS specific, on Linux you can just create a wrapper
script or .desktop file and use it to launch files with any program and
any command line you like. 

It's only Apple that makes this difficult. As such I am not very
motivated to implement this. Having kitty interpret command line
arguments as files to open instead of programs to run has a cost, it
makes command line processing more difficult to reason about.

That said, one probably can detect files passed to kitty via launch services on
macOS and special case them.

**Comment by page-down** [comment]
(Reply before the latest changes.)

It looks like the code is already there.

kitty/child-monitor.c
```c
process_cocoa_pending_actions(void) {
    // ...
    if (cocoa_pending_actions_data.open_files_count) {
        // ...
```

While this feature looks great, I also think the potentially inconsistent behavior will cause confusion.

For example, for a .sh file, should kitty execute it directly, or open it in a text editor? For different types of files, should kitty open them as configured in open-actions?

For now open the .sh file and kitty will execute it in a new window.

---

@kovidgoyal 

I found an issue where `text.txt`, which does not have execute permission, will be executed when opened with kitty.app. Do you think this is an issue that needs to be addressed?

(Tested before the latest commit.)

Also, to get kitty.app to appear in the file type list, it also requires registration of various file types in macOS for kitty.

**Comment by page-down** [comment]
I tested the latest commit, which resulted in not being able to run the .sh file with kitty.

**Comment by kovidgoyal** [comment]
see the next commit

**Comment by page-down** [comment]
I tested the latest commit and .sh is executed with zsh.

```bash
#!/usr/bin/env bash
echo "${BASH_VERSION}"
```

Some open source projects have `.command` files that cannot be executed.

```text
#!/usr/bin/env python
import os
# ...
```

Also for file type registration, I don't know how to register all file types yet. Since the file types are not registered, it is not possible to drag a text file to the kitty Dock icon to open it. And of course it doesn't appear in the "open with" list yet.

Also do you think it's worth checking the executable permissions of the file? Then execute it or open it with a text editor.

**Comment by kovidgoyal** [comment]
Executable permissions are already checked. And shell scripts are launched with the default shell unless they have a defined file extension such as .zsh, .bash or .fish.

**Comment by page-down** [comment]
Strange, currently I am trying to open a .sh file with no execute permissions and it will be executed directly.

**Comment by kovidgoyal** [comment]
Yes, like I said, script files will be opened with the default shell,
unless they are executable, in which case they are executed directly.

**Comment by page-down** [comment]
Oh, it's pretty clearly that I missed the beginning of the `open_file()`. Thanks for the reminder.

Do you have any good ideas for files like `Makefile`, `LICENSE`, `setup.cfg`, `shell.nix`, etc.? Currently these files cannot be opened.

For example, is it possible to prefer user-configured open-actions.

open-actions.conf
```text
protocol file
ext nix 
action launch --type os-window vi ${FILE_PATH}
```

**Comment by kovidgoyal** [comment]
On Fri, Jan 07, 2022 at 01:31:44AM -0800, page-down wrote:
> Oh, it's pretty clearly that I missed the beginning of the `open_file()`. Thanks for the reminder.
> 
> Do you have any good ideas for files like `Makefile`, `LICENSE`, `setup.cfg`, `shell.nix`, etc.? Currently these files cannot be opened.

Any file that has a mimetype of text/ will be edited. You can add mime
types in the mime.types file in the kitty config directory.

**Comment by page-down** [comment]
> ... You can add mime types in the mime.types file in the kitty config directory.

I forgot about this feature.

```text
text/plain nix Makefile
```

I tried it and the nix file opens fine, but the Makefile still doesn't work. Is there a good way to handle this?

**Comment by page-down** [comment]
Also are there any security issues?

- Name a file `cat.jpg` with the actual contents as an executable binary or script. Offer it to the victim for download.
- Guide the victim to save to a special file system location, to make this file with executable permissions. (For example, some macOS shared volumes are mounted with file permissions of `777` and cannot be modified.)
- The victim opens it with kitty, at this point the payload is successfully executed.

I did not test the above.

To be honest, I'm really not sure I like this approach. : /

**Comment by kovidgoyal** [comment]
On Fri, Jan 07, 2022 at 03:46:57AM -0800, page-down wrote:
> Also are there any security issues?
> 
> - Name a file `cat.jpg` with the actual contents as an executable binary or script. Offer it to the victim for download.
> - Guide the victim to save to a special file system location, to make this file with executable permissions. (For example, some macOS shared volumes are mounted with file permissions of `777` and cannot be modified.)
> - The victim opens it with kitty, at this point the payload is successfully executed.

I dont follow, the victim can double click the file to execute it if its
executable. Or run it in a shell. Or a hundred different ways to execute
it. Once you mark a file executable it means you intend to execute it. I
dont see how its the job of kitty to prevent you from executing a file
you have marked executable.  

By that token I can make a shell script and name it image.jpg and have it
executed by kitty after marking it executable, even before this feature was
implemented. Since before, kitty would unconditionally try to execute
anything passed to it.

**Comment by page-down** [comment]
> Since before, kitty would unconditionally try to execute anything passed to it.

- Clone the repository using git clone with permissions, where the file will not carry the macOS quarantine flag.
- The `cat.jpg` file has execute permissions in git.
- When opened with kitty, it will be executed. However, the user thinks that kitty will act as an image viewer and just display the image.

At this point kitty has two identities at the same time, a picture viewer that does not execute code, or a terminal with full privileges.

Hopefully, the user will understand what he is doing.

Maybe I am overthinking it, if you are not worried then I have no problem with it.

**Comment by kovidgoyal** [comment]
well, I dont actually mind not having the open_file() function execute
things. It means you can drag exectuables to kitty or open then directly
with kitty from finder, but there is not much point to doing that
anyway.

**Comment by page-down** [comment]
Thank you. I tested the latest changes and all the issues I mentioned have been resolved.

Perhaps the last one:
I tested after uninstalling imagemagick and the error message flashed (window closed), the user may not know what went wrong and how to fix it.

Not a big deal, but it would be nice if `--hold` (and perhaps all places where hold is used) could be configured to hold only when exiting with a non-zero. This allows to use `launch --hold` even when running icat, and does not conflict with icat's hold.

**Comment by kovidgoyal** [comment]
On Fri, Jan 07, 2022 at 09:18:31AM -0800, page-down wrote:
> Thank you. I tested the latest changes and all the issues I mentioned have been resolved.
> 
> Perhaps the last one:
> I tested after uninstalling imagemagick and the error message flashed (window closed), the user may not know what went wrong and how to fix it.

I dont follow, can you explain.

> 
> Not a big deal, but it would be nice if `--hold` (and perhaps all places where hold is used) could be configured to hold only when exiting with a non-zero. This allows to use `launch --hold` even when running icat, and does not conflict with icat's hold.

The meaning of hold is to hold, regardless of exit code. If you want
a hold dependent on exit code that would need to be a separate option.
Once can use launch --hold even when running with icat already. Since in
the icat case you want an unconditional hold

**Comment by page-down** [comment]
>> I tested after uninstalling imagemagick ...
>
> I dont follow, can you explain.

```conf
# from `def default_launch_actions()`:
action launch --type=os-window kitty +kitten icat --hold $FILE_PATH
```

When imagemagick is not installed, kitten icat exits after outputting an error message and the OS window is closed immediately. Here is what I see with `launch --hold`.

```text
ImageMagick is required to process images

Press Enter to exit
```

> If you want a hold dependent on exit code that would need to be a separate option.

Yes, it makes perfect sense.

**Comment by ahmedelgabri** [comment]
@kovidgoyal thanks for this feature.

I have a question & a problem.

#### Question: 

Do I need to add all extensions/files I want to be opened to `mime.types` file? I'm on macOS & some of the files I want to open already have `text/plain` when I check with `file -I <file>`

---

#### Problem: 

I have this inside my `open-actions.conf`

```
protocol file
mime text/*
action launch --type=overlay $EDITOR $FILE_PATH
```

And my `$EDITOR` is set to `nvim`, and I have some plugins & configs that depends on some programs being in my `$PATH`. But when I double click a file, I get errors that neovim can't find the binary in my `$PATH`. Although, when I run `r! which <binary>` it returns the correct path. While inside normal kitty panes/tabs everything works fine. So I'm not sure what's the difference here?

**Comment by ahmedelgabri** [comment]
I also have

```
protocol file
mime image/*
action launch --type=overlay kitty +kitten icat --hold ${FILE_PATH}
```

And have ImageMagic installed, yet it errors out saying 

```
ImageMagick is required to process images

Press Enter to exit
```

**Comment by page-down** [comment]
> Do I need to add all extensions/files I want to be opened to mime.types file? I'm on macOS & some of the files I want to open already have text/plain ...

If it is already recognized in the system, then no special configuration is needed.

> ... `open-actions.conf`

Note that this feature is not related to `open-actions.conf`. It's `launch-actions.conf`. And there are some default configurations already in place.

https://github.com/kovidgoyal/kitty/blob/v0.24.2/kitty/open_actions.py#L222-L245

> ... my $EDITOR is set to nvim ...
> ... have ImageMagic installed, yet it errors out saying ...

Where did you configure it? What you need to configure is kitty's environment variables, and configuring them in shell rc is of course invalid. Because at this point neovim will be executed directly by kitty and has nothing to do with the shell.

https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

debug kitty's env vars:
```conf
map f1 show_kitty_env_vars
```

It is not easy to configure environment variables for GUI software under macOS. You can add the paths of your other plugins to $PATH by using `exe_search_path`.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

This should solve all your program execution problems.

**Comment by ahmedelgabri** [comment]
> Note that this feature is not related to `open-actions.conf`. It's `launch-actions.conf`.

Not sure that this is correct, all examples in the docs are mentioning `open-actions.conf` https://sw.kovidgoyal.net/kitty/kittens/hyperlinked_grep/?highlight=open%20actions%20conf#hyperlinked-grep unless I'm missing something.

> Where did you configure it? What you need to configure is kitty's environment variables, and configuring them in shell rc is of course invalid. Because at this point neovim will be executed directly by kitty and has nothing to do with the shell.
> 
> https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal
> 
> debug kitty's env vars:
> 
> ```
> map f1 show_kitty_env_vars
> ```
> 
> It is not easy to configure environment variables for GUI software under macOS. You can add the paths of your other plugins to $PATH by using `exe_search_path`.
> 
> https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path
> 
> This should solve all your program execution problems.

Thanks, it's a bit unfortunate though because this means extra work to keep everything in sync (shell rc & kitty config).

**Comment by page-down** [comment]
> ... unless I'm missing something ...

The one you gave is for configuring the behavior of clicking on links within kitty.

However, this post is about a new feature in 0.24.2 to open files with kitty under macOS via open with. This feature is configured using launch-actions.conf .

**Comment by ahmedelgabri** [comment]
Ok, I have been playing with different options for the last hour with no results.

- Seems like kitty is still picking up `$EDITOR` from my shell env somehow even if I set `env EDITOR=nvim --noplugin` inside `kitty.conf`, I tried also `env EDITOR="nvim --noplugin"`, doesn't even show in the output of `show_kitty_env_vars`
- To set my expectations correctly, opening files from within kitty should or shouldn't pick up shell rc env variables? because it seems that it's not picking them up too. 

Example using GNU `ls`, when I run `ls --hyperlink=auto` & then click on a file, I _expect_ that this will pick up my shell environment properly. But it's not, I get the same errors when I open files using "Open with".

**Comment by page-down** [comment]
- Click on hyperlink within kitty -> `open-actions.conf`
- Right-click on the file in macOS, select Open With and choose kitty -> `launch-actions.conf`
- `env` in `kitty.conf`
  - The environment variables configured via `env` in the configuration file are for the programs running in kitty, not for kitty itself.
  - Parsing of `{open,launch}-actions.conf` (expanding env vars) is done in kitty itself.
- Environment variables in `*-actions.conf`
  - All environment variables will come from kitty (debug with `map f1 show_kitty_env_vars`)
- $EDITOR in `{open,launch}-actions.conf`
  - This special environment variable will be overridden by using kitty's built-in resolution.
  - For priorities please see: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.editor

---
> ... kitty is still picking up $EDITOR from my shell env somehow even if I set env EDITOR= ...

This is working as expected.
I guess you don't have `editor` configured, please refer to the documentation.
If you don't have editor configured and kitty's environment variable doesn't have editor, kitty will execute shell rc and get EDITOR from it.

> ... I tried also `env` ... doesn't even show in the output of show_kitty_env_vars

Please see the documentation. These are not for kitty.

> ... opening files from within kitty should or shouldn't pick up shell rc env variables?

`EDITOR` and `SHELL` are two special environment variables in `{open,launch}-actions.conf`.
For the others, kitty does not read the environment variables in shell rc.

> ... click on a file, I expect that this will pick up my shell environment properly.

In macOS, kitty is executed by launchd, and the shell rc environment variable is not known unless kitty invokes the shell every time, but does not do so. In the actions profile, all programs will be run directly by kitty and have nothing to do with shell rc.

My guess is that you need the following configuration.

```conf
editor nvim
exe_search_path /your/path/to/executables/dir
```

or

```conf
editor /abs/path/to/nvim
```

**Comment by MihiroH** [comment]
I tried several methods, but they didn't work.  
The following script works with Automator.  

This method is very simple. It opens Kitty if it isn't already running and types `"nvim "` followed by the file path.  
Additionally, if Kitty is already open, it creates a new tab before typing the command.

#### **How to set it up:**
1. Open Automator in macOS.
2. Select "Application".
3. Type "run" in the search bar.
4. Drag and drop "Run AppleScript" into the right panel.
5. Paste the following script, then save it.
6. Open System Settings, then go to "Privacy & Security" > "Accessibility".
7. Add the application you just created.
8. Right-click a file, then select "Open With" > [Application Name].

```sh
on run {input, parameters}
    set myPath to POSIX path of input
    set q to quoted form of myPath
    
    --Check if Kitty is running
    tell application "System Events"
        set isKittyRunning to (exists (processes where name is "kitty"))
    end tell
    
    tell application "kitty"
        activate
        
        delay 0.5
        
        -- Create a new tab only if Kitty is already running
        if isKittyRunning then
            tell application "System Events"
                keystroke "t" using command down
            end tell
            delay 0.5
        end if
        
        -- Send as keystroke
        tell application "System Events"
            keystroke "nvim " & q
            keystroke return
        end tell
    end tell
end run
```

**Comment by antoniorodr** [comment]
Spot on @MihiroH its working like a charm!

Do you know if it's possible to do the same with "open in terminal" option from Finder?

**Comment by MihiroH** [comment]
@antoniodr Thanks for trying!
Sorry, I don’t know for sure, but it might work if you replace "kitty" with "terminal" in the Automator script instead of using the "open in terminal" option directly in Finder.

**Comment by farawayisland** [comment]
If anyone is interested in a Quick Action workflow (particularly for a keyboard shortcut version) of [MihiroH's Automator script](https://github.com/kovidgoyal/kitty/issues/4460#issuecomment-2677434820), here's my modified version where I added configurable window- and tab-name options for the file to be opened in Neovim. Hopefully someone else finds this useful. (Make sure to give Automator access.)

```
-- AppleScript to open file in Neovim inside kitty
--
-- Source:
-- https://github.com/kovidgoyal/kitty/issues/4460#issuecomment-2677434820
-- 
-- Open Automator, create a Quick Action (must later be saved in "~/Library/Services"), and select the "Run AppleScript" workflow action before pasting this script with the following configuration:
-- 
-- - Workflow receives: files or folders
-- - In: Finder.app

on run {input, parameters}
	set thePath to POSIX path of input
	set q to quoted form of thePath
	set parentPath to do shell script "dirname " & q
	set q1 to quoted form of parentPath
	set filename to do shell script "basename " & q
	set q2 to quoted form of filename
	set windowTitle to quoted form of ("Neovim | " & filename)
	set tabTitle to quoted form of filename
	
	--Check if Kitty is running
	tell application "System Events"
		set isKittyRunning to (exists (processes where name is "kitty"))
	end tell
	
	tell application "kitty"
		activate
		
		delay 0.5
		
		-- Create a new tab only if Kitty is already running
		if isKittyRunning then
			tell application "System Events"
				keystroke "t" using command down
			end tell
			delay 0.5
		end if
		
		-- Send as keystroke
		tell application "System Events"
			keystroke "kitten @ set-window-title " & windowTitle & " && kitten @ set-tab-title " & tabTitle & " && cd " & q1 & " && nvim " & q2
			keystroke return
		end tell
	end tell
end run

-- Finally, go to System Settings > Keyboard > Keyboard Shortcuts > Services > Files and Folders and assign a keyboard shortcut to your Quick Action workflow.
```
