### ISSUE TITLE
Having a vertical split layout only for 2 (of many) windows

### ISSUE THREAD

**Issue by ramanshsharma2806** [kovidgoyal/kitty#4461]
Hello,
I have 3 windows in my kitty terminal. One at root level of a project, two within a few subfolders (I need two because I run multiple scripts at the same time).

I've been trying to use the splits layout to get the 2 subfolder windows in a vertical split, but I **do not** want the root folder window in the same layout. Please allow me to explain.
<img width="1440" alt="Screen Shot 2022-01-07 at 9 48 36 AM" src="https://user-images.githubusercontent.com/24642071/148490966-9e0de1dc-b099-4ff2-8a73-ba767c7e95d5.png">

With the splits layout (in above screenshot), I cannot find a way to have the 2 subfolder windows in a vertical split **and** move the root folder window (covering the left half) to a different window. I apologize for my vague use of the word window. I wish to have two windows, navigated with ```Cmd+1``` and ```Cmd+2```, where the first window is the root folder terminal and the second window has the two subfolder terminals in the vertical split. Basically these two:
<img width="1440" alt="Screen Shot 2022-01-07 at 9 43 35 AM" src="https://user-images.githubusercontent.com/24642071/148491205-8817c374-801c-493a-a87c-70be6ce3e944.png">

===========================================================================

<img width="1440" alt="Screen Shot 2022-01-07 at 9 44 53 AM" src="https://user-images.githubusercontent.com/24642071/148491209-b930981a-4b7e-462b-bf6d-98559a6a01af.png">

I am sure this is possible. Could someone please help me get the correct kitty.conf commands to make this happen. Right now, following the docs, I have these lines in my kitty.conf relating to this:
```
map shift+5 launch --location=hsplit
map shift+6 launch --location=vsplit
map shift+7 layout_action rotate

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

enabled_layouts stack, splits:split_axis=horizontal
```

Thank you!

**Comment by page-down** [comment]
> I wish to have two windows, navigated with Cmd+1 and Cmd+2, where the first window is the root folder terminal and the second window has the two subfolder terminals in the vertical split.

I can not understand, this is obviously 3 kitty window. It is not possible to contain two kitty windows inside a virtual container (switched by cmd+2). 

> I cannot find a way to have the 2 subfolder windows in a vertical split
> and move the root folder window (covering the left half) to a different window.

Where do you want to move this window to? You can upgrade to 0.24+ and then press the default shortcut ctrl+shift+f8 to swap the first window with the other windows. Is this the "move" you need?

**Comment by ramanshsharma2806** [comment]
> I can not understand, this is obviously 3 kitty window. It is not possible to contain two kitty windows inside a virtual container (switched by cmd+2).

Ah, then I suppose it's not possible what I was thinking.

> You can upgrade to 0.24+ and then press the default shortcut ctrl+shift+f8 to swap the first window with the other windows. Is this the "move" you need?

No, I don't think that is it. What I want to have are two kitty windows running two different scripts simultaneously in a layout I can look at their results at the same time, **and** a code kitty window in a separate layout. This is so I wouldn't have to navigate to two places to see the results for two scripts and I would be able to keep the code window in the full maximum area (unlike the splits layout which only gives a small portion to the code window).

**Comment by kovidgoyal** [comment]
Use two separate OS windows or two separate tabs for that. One with our two windows and one with your root window.

**Comment by page-down** [comment]
It is worth noting that in version 0.24+ you can define shortcuts to switch to the specified OS window.

https://sw.kovidgoyal.net/kitty/actions/#nth-os-window

So you can put up two OS windows, and then cmd+1, cmd+2 switches between the two.

**Comment by ramanshsharma2806** [comment]
Thank you for the suggestion guys. I think that would be a good way for me to implement this.

Question about os windows, how do I make a startup conf file that would open two different OS windows? I have this right now but it doesn't work.

![image](https://user-images.githubusercontent.com/24642071/148500100-3dcf02e0-66b4-4936-abe4-b4de9f52098e.png)

**Comment by kovidgoyal** [comment]
Read the example at https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

**Comment by page-down** [comment]
I already answered a similar question to the one you asked on October 16, 2021.
Please refer to my previous reply, you just need to make a little modification.

**Comment by ramanshsharma2806** [comment]
Got it working now. Thank you for the help guys 🙏
