### ISSUE TITLE
variant of 'scrolled-by' which counts text lines instead of screen lines

### ISSUE THREAD

**Issue by omgold** [kovidgoyal/kitty#4462]
When launching a program and passing it the scrollback buffer (e.g. to copy text to selection via keyboard), to scroll the editor identically to the terminal, the variable `@scrolled-by` can be passed on the commandline of the executed program. 

This only works correctly, though, when the editor counts lines the same way as the terminal. It seems `@scrolled-by` counts screen lines, but editors tend to count lines of the passed text (effectively the number of newline characters). With unicode, double-width characters and such, the translation between these line counts is far from trivial to do in a wrapper script. 

Sure, one can use `--stdin-add-line-wrap-markers`, but for copying multi-line text, this is not desirable.

Thus I think adding variables that allow to pass "topmost text line on the screen" and "bottommost text line on the screen" (with respect to the current scrolling) would be useful to have.

**Comment by page-down** [comment]
I also encountered this issue when using the custom pager feature.

Because of the pager program line count calculation and unicode processing, there is a difference in the number of lines, making it impossible to accurately locate the line that starts in the screen.

```conf
scrollback_pager /path/to/pager.sh 'INPUT_LINE_NUMBER' 'CURSOR_LINE' 'CURSOR_COLUMN'
```

**Comment by florian-hild** [comment]
I'm not sure if it is the same issue but after updating today from 0.74.4.13p to 0.76.0.7 I can't scroll anymore in my tmux panel it just scrolls the hole windows. The settings are the same on both kitty sessions

**Comment by page-down** [comment]
@florian-hild 

You are looking for KiTTY, a fork of PuTTY.

https://github.com/cyd01/KiTTY
