### ISSUE TITLE
Lost contents when window splits

### ISSUE THREAD

**Issue by liuerfire** [kovidgoyal/kitty#4463]
**Describe the bug**

The old window lost some outputs when split.

**To Reproduce**
1. kitty --config NONE
1. a window keeps printing something like `while true; do echo 1; sleep 1; done`
2. create a new window

**Screenshots**

A record: https://imgur.com/a/xJSKuDm

**Environment details**

OS & DE: Archlinux + KDE + Wayland

Kitty version: 0.24.0 while 0.23 didn't have this issue.

P.S. I got this error when press Ctrl+Shift+F6

```
Key action failed

debug_config
(25, 'Inappropriate ioctl for device')

Press Enter to close.
```

**Comment by kovidgoyal** [comment]
I cannto reproduce with those steps. From your video it looks like shell integration is not working properly for your shell, causing the output to not be marked, which will cause it to be deleted when the window is resized as kitty assumes it is part of the prompt. What shell are you using?

**Comment by liuerfire** [comment]
oh, you're right. I use zsh with [powerlevel10k](https://github.com/romkatv/powerlevel10k). This issue is gone if I disable powerlevel10k. 

Thank you.
