### ISSUE TITLE
Comprehensive keyboard: basic key codes broken by Num Lock

### ISSUE THREAD

**Issue by yurikhan** [kovidgoyal/kitty#4465]
**Describe the bug**
When comprehensive keyboard protocol is used with the minimal flags and <kbd>Num Lock</kbd> is turned on, keys such as <kbd>Enter</kbd>, <kbd>Tab</kbd>, and <kbd>Backspace</kbd> are reported in the new format.

**To Reproduce**
1. execute `echo $'\e[>1u'` at bash prompt
2. ensure <kbd>Num Lock</kbd> is on
3. press <kbd>Enter</kbd> <kbd>Backspace</kbd> <kbd>Tab</kbd>

**Expected behavior:** <kbd>Enter</kbd> executes an empty command; <kbd>Backspace</kbd> at empty prompt has no effect; <kbd>Tab</kbd> at empty prompt has no effect.

**Observed behavior:** <kbd>Enter</kbd> and <kbd>Tab</kbd> append `;129u` to the command line; <kbd>Backspace</kbd> appends `7;129u`. The command line appears unusable unless one turns off <kbd>Num Lock</kbd>.

**Environment details**
Ubuntu 20.04, Kitty 0.24.1 and I don’t think any further details matter much.

**Impact**
As far as I understand, the idea of the minimal mode was to preserve the behavior of the most basic keys so software would continue to work even if not adapted to the new protocol. Since <kbd>Num Lock</kbd> is basically always on for every non-Mac user who has dedicated <kbd>←</kbd><kbd>↓</kbd><kbd>↑</kbd><kbd>→</kbd> keys, this goal is not achieved.

**Comment by kovidgoyal** [comment]
No, not really, the point of minimal mode is to disambiguate keys that
are ambiguous in the legacy encoding, make key events much easier to
parse for applications with minimal changes. It's certainly not meant to
be useable with legacy programs. The name of the mode is even
"Disambiguate escape codes". 

The actual legacy mode (which encodes many keys not encodeable in
traditional terminal programs) is meant for this. And in that mode
numlock does not affect anything.

**Comment by trygveaa** [comment]
@kovidgoyal: But why would num lock affect enter, backspace and tab in any mode? Those keys aren't on the num pad and I would think they should mean the same regardless of num lock.

**Comment by kovidgoyal** [comment]
num lock and caps lock are modifiers. They are reported as such.
