### ISSUE TITLE
Tab/window title has no hostname when local (despite being in my bash prompt)

### ISSUE THREAD

**Issue by somody** [kovidgoyal/kitty#4466]
**Describe the bug**
Tab title has no hostname when local

**To Reproduce**
1. Open new tab
2. Look at title of window/tab
3. It's merely "\~", when it used to be the same as my prompt ("username@hostname:\~")
4. If you ssh to another host, the full prompt is shown in the tab title
5. If you use a different terminal client, the full prompt is shown even for local directories

**Screenshots**
![Screenshot from 2022-01-07 16-12-58](https://user-images.githubusercontent.com/7962018/148564033-e2defc6e-a0fb-4494-bcd6-87ffd8bbb29f.png)

**Environment details**
```
Key action failed

debug_config
(25, 'Inappropriate ioctl for device')

Press Enter to close.
```

**Additional context**
Happens also with ```kitty --config NONE```

**Comment by kovidgoyal** [comment]
Add

shell_integration no-title

to kitty.conf

**Comment by somody** [comment]
This solution worked since January, but the problem is back now even with that line in kitty.conf.

**Comment by somody** [comment]
Hm, I don't understand. So is it intentional that the ```shell_integration
no-title``` option doesn't have the same effect anymore?

**Comment by kovidgoyal** [comment]
shell)integration not-title 

works fine. You just have manual sourcing of the shell integration in
your .bashrc. Remove it from there and you will be fine.

**Comment by somody** [comment]
Thanks!
