### ISSUE TITLE
bground transparency

### ISSUE THREAD

**Issue by tjallemaal** [kovidgoyal/kitty#4470]
Hey there, sorry to bother,

I looked through the documentation, I don't how to make my background opaque.
This is what I have in my `kitty.conf`

font_size 14.0

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

```
background            #20232c
foreground            #b2b8c2
cursor                #b2b8c2
selection_background  #15171e
color0                #000000
color8                #000000
color1                #af4b57
color9                #af4b57
color2                #87b279
color10               #87b279
color3                #e5c078
color11               #e5c078
color4                #7c8fa3
color12               #7c8fa3
color5                #a37996
color13               #a37996
color6                #84a6a4
color14               #84a6a4
color7                #b2b8c2
color15               #fffefe
selection_foreground #20232c
```

danyavad

**Comment by npearson72** [comment]
background_opacity 1.0

**Comment by tjallemaal** [comment]
Sorry I'm an idiot! i meant transparent lol

**Comment by npearson72** [comment]
Change the value of `background_opacity` to something less than `1.0`

**Comment by tjallemaal** [comment]
Got it ; `ctrl+cmd+,` didnt work immediately , I had to relaunch the emulator. thanks pearson
