### ISSUE TITLE
macOS "Secure Keyboard Entry" doesn't persist across app restarts

### ISSUE THREAD

**Issue by jzelinskie** [kovidgoyal/kitty#4471]
**Describe the bug**
Secure Keyboard Entry is functionality in macOS doesn't remain across application restarts.

**To Reproduce**
1. Open kitty.app
2. In the menubar, kitty > Secure Keyboard Entry or press option+cmd+s
3. In the menubar, kitty > Quit kitty or press cmd+q
4. Open kitty.app
5. Notice that in the kitty menu, Secure Keyboard Entry is not still enabled

**Comment by page-down** [comment]
In addition, the "Secure Keyboard Entry" shortcut is not customizable and cannot be removed.

These two have been on my list for a while.

**Comment by kovidgoyal** [comment]
This is not something I care about. Patches are welcome. I don't even
know what "secure keyboard entry" is supposed to accomplish, given that
any program running as the same user can read traffic on the tty pipe.

And to make it persistent, it would need to be stored on the filesystem,
where again any malicious app running as the same user can change it at
will. 

So I really dont know what this "security" feature secures one from.
That said, I have no objection to a patch making it persist, should be
easy using NSUserDefaults in kitty/cocoa_window.m

https://developer.apple.com/documentation/foundation/nsuserdefaults

**Comment by page-down** [comment]
The security risks that this feature can defend against are quite limited.

- Software that is restricted by the macOS sandbox (cannot read arbitrary files)
- and that gives accessibility rights (reads the keyboard)

In my opinion, when such software is installed, it is already a serious security problem. This is a "feature" that provides a false sense of security.

The reasonable usage scenarios I can think of are as follows
- Do-not-disturb mode
  - When this feature is on no other program can get the user focus, including cli commands such as "open".
- Using screen recording software, but do not want to display the on-screen keys when entering specific content.

Honestly, all I care about is how to remove that hard-coded shortcut key combination.

**Comment by chmouel** [comment]
I ran into this and the solution seems to be: 

```
defaults write net.kovidgoyal.kitty SecureKeyboardEntry -bool false
```

which would disable secure keyboard by default
