### ISSUE TITLE
Fish shell integration with block cursor.

### ISSUE THREAD

**Issue by dsully** [kovidgoyal/kitty#4473]
Unless `shell-integration no-cursor` is set, Kitty's fish vendor_conf will always set a bar cursor, even if `cursor_shape block` is set.

From: https://github.com/kovidgoyal/kitty/blob/master/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish#L38

```
if not contains "no-cursor" $_ksi
        function _ksi_bar_cursor --on-event fish_prompt
            printf "\e[5 q"
        end
        function _ksi_block_cursor --on-event fish_preexec
            printf "\e[2 q"
        end
        _ksi_bar_cursor
    end
```

Should this set a different cursor shape based on the config in `kitty.conf` ?

**Comment by page-down** [comment]
No, I think this is a feature.

If you don't like it, as you mentioned, you can set `shell_integration no-cursor`, or disable it completely, and write your own integration script.

**Comment by dsully** [comment]
I've of course already set `no-cursor`, but you seem unsure about what the behavior should be with the word "think". 

Is that correct?

**Comment by page-down** [comment]
Yes, I, as a user, have read many of the author's responses to the related questions.

I understand your point of view, however, I think it is unlikely that this design will be changed in the near future.

This is one of the most frequently asked questions recently, since the release of the new version.

**Comment by kovidgoyal** [comment]
No, it's working as intended. Read the docs for cursor_shape. 
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape
