### ISSUE TITLE
Sharing success w/ shell integration for a jupyter console workflow

### ISSUE THREAD

**Issue by randomgeek78** [kovidgoyal/kitty#4475]
I recently upgraded to 0.24 and explored the shell integration features. I was delighted with these features and thought it would be great within my nvim + jupyter console workflow. My current workflow requires a lot of cut+paste from `jupyter console` to a text file. I was able to hack jupyter console so it works well with the shell integration features. Now, when I run a command, I no longer have to select and then paste. I just get the entire output selected using shell integration and then paste it where I wanted. This required me to insert the [escape codes](https://sw.kovidgoyal.net/kitty/shell-integration/#notes-for-shell-developers) at the right locations in the jupyter_console/ptshell.py file. Everything works like a charm now. I am the relevant patches below for others to try-

```shell
  if [[ -e "$site_packages"/jupyter_console/ptshell.py ]]; then
    echo "Patching $site_packages/jupyter_console/ptshell.py"
    perl -0777 -pi -e "$(cat <<'_E_'
s{\Q
        if PTK3:
            text = await self.pt_cli.prompt_async(default=default)
\E}
{
        def sys_write\(\):
            import sys
            sys.stdout.write\(u"\\u001b\\u005d133;A\\u001b\\u005c"\)
        pre_run = sys_write

        if PTK3:
            text = await self.pt_cli.prompt_async(default=default, pre_run=pre_run)
}gsx
_E_
)" "$site_packages"/jupyter_console/ptshell.py

    perl -0777 -pi -e "$(cat <<'_E_'
s{\Q
        while self.client.iopub_channel.msg_ready():
            sub_msg = self.client.iopub_channel.get_msg()
            msg_type = sub_msg['header']['msg_type']
\E}
{
        while self.client.iopub_channel.msg_ready():
            sub_msg = self.client.iopub_channel.get_msg()
            msg_type = sub_msg['header']['msg_type']

            if msg_type in ['execute_input', 'execute_result']:
                sys.stdout.write(u"\\u001b\\u005d133;C\\u001b\\u005c")
}gsx
_E_
)" "$site_packages"/jupyter_console/ptshell.py
  fi
```

```
# kitty.conf
mouse_map shift+right press ungrabbed paste_from_selection
mouse_map right press ungrabbed mouse_select_command_output
map kitty_mod+s  paste_from_selection
```

**Comment by kovidgoyal** [comment]
Cool, I have added a link to this issue in the shell integration docs
under third party integrations.

**Comment by randomgeek78** [comment]
Thank you.

**Comment by eo1989** [comment]
Where do we copy pasta the above code into?

**Comment by ces42** [comment]
I think the idea is you set the `site_packages` variable and run the code in a shell - it will modify ipython's source files (probably not a great things but it works). The code looks for certain spots in the ipython source files, but it might be an old version of ipython -- on my system I had to search for the spots in `interactiveshell.py` that look similar to those in randomgeek78's patch script and manually add `sys.stdout.write(u"\u001b\u005d133;A\u001b\u005c")` there.
