### ISSUE TITLE
Add an option to dump config

### ISSUE THREAD

**Issue by lcheylus** [kovidgoyal/kitty#4479]
**Is your feature request related to a problem? Please describe.**
When I modify my Kitty configuration, I like to know the current value for specific keys before modifying it.

**Describe the solution you'd like**
It's possible to dump current Kitty configuration with CTRL+SHIFT+F6. But I would like to have an option to dump it via command-line : `kitty --dump-config` or `kitty --show-config`.

**Comment by page-down** [comment]
Based on your description, it seems more intuitive to view the current config file directly.

You can also write kitten to export debug_config to a file.

If you need to export the configuration of a running kitty to stdout by executing it from the command line, then what you are asking is a remote control command.

**Comment by kovidgoyal** [comment]
Why? ctrl+shift+f6 gets you the current config in a pager, less by
default. If you need it in a file simply save it in the pager, which is
done by pressing s in less.
