### ISSUE TITLE
Tmux style kitty prefix?

### ISSUE THREAD

**Issue by zbirenbaum** [kovidgoyal/kitty#4482]
I have looked through the docs and haven't found any way of doing this, but it would be super helpful if kitty had a mappable 'cmd' prefix for splits like tmux does. The last update fixed some issues I was using tmux to cope with and now I want to completely remove it from my workflow (as it is just adding in issues at this point) but with vim, i3, and kitty, my keymaps are running short. Being able to do ctrl-a and then press s or v and letting go of the original prefix keys is really helpful. 

Right now I have to press all 3 keys at once which feels like it is giving me mild carpal tunnel after just a few minutes.

**Comment by kovidgoyal** [comment]
read about multi-key shortcuts here: https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

**Comment by page-down** [comment]
Have you tried multi-key shortcuts?

https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

**Comment by zbirenbaum** [comment]
This is perfect! Thank you  very much, I am not sure how I missed it. I remember seeing that portion of the docs but must have misunderstood what I was looking at.
