### ISSUE TITLE
cursor is hidden after opening kitty

### ISSUE THREAD

**Issue by adamwojt** [kovidgoyal/kitty#4486]
**Describe the bug**
After updating from `0.23.1` > `0.24.0`. When opening terminal, cursor is not visible. It appears again after executing arbitrary commands, ex. `nvim $FILE`. Tried downgrading but it seems that I would have to downgrade Python too. I guess because how it's packaged for Arch. 
What resolves this issue is putting this into my `~/.zshrc` -> `echo -en "\e[?25h"` https://unix.stackexchange.com/a/512630

**To Reproduce**
1. Open Kitty
2. Cursor is invisible
3. Enter Neovim and exit
4. Cursor appears again.

**Environment details**
```
OS: Arch Linux x86_64
Host: 21A0000CMH ThinkPad P14s Gen 2a
Kernel: 5.15.13-arch1-1
Shell: zsh
Resolution: 3840x1080
Terminal: kitty
CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics (16) @ 4.505GHz               
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE`: -> **Same thing happens without config**

**Comment by kovidgoyal** [comment]
Update to 0.24.1

**Comment by adamwojt** [comment]
> Update to 0.24.1

This seems to work although now cursor shape is ignored. It seems to always default to white beam. Which is something I don't personally care about but just throwing it here.

Notice that correct shape appears for millisecond before turning to beam, similarly to how it was hidden before updating. You would be able to see it for millisecond.  Cursor color is also ignored but that was same with previous version too.

https://user-images.githubusercontent.com/45100954/148699083-3876ea90-b644-4095-a9c7-e2ded24ece97.mp4

**Comment by kovidgoyal** [comment]
If you dont want the cursor shape to change, use

shell_integration no-cursor
