### ISSUE TITLE
Issue with Kitty when using Espanso text expander

### ISSUE THREAD

**Issue by jakeprice-dev** [kovidgoyal/kitty#4487]
I regularly use [Espanso](https://espanso.org/) to expand text shortcuts. If I expand a shortcut in Kitty (even if I start with `--config NONE`) the colons `:` are replaced with semi-colons `;` and the square brackets are replaced with `89`.

This happens from the prompt (with my bashrc disabled), Vim (with `vim -u NONE` to ignore `vimrc`), and even Nano. So it doesn't appear to be anything obvious I've set.

1. Install Espanso 0.7.3
2. Edit `~/.config/espanso/default.yml` and append the below to the file:

```yaml
  - trigger: ":kitty"
    replace: "This : is [] a test ;"
```

3. Open Kitty, and type `:kitty` which should output `This : is [] a test ;` but instead, in Kitty, outputs `this ; is 89 a test ;`.

Screenshot below:

![kitty_espanso_issue](https://user-images.githubusercontent.com/88721839/148689672-c006f5c0-57cb-40fa-8a38-705e17201e40.png)

**Environment details**

Fedora Linux 35 (Workstation) running GNOME desktop environment.

```
kitty 0.21.2 created by Kovid Goyal
Linux pavilion 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64
\S
Kernel \r on an \m (\l)
Running under:X11
Loaded config files:
  /home/jprice/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height         2
background                 Color(red=0, green=36, blue=81)
cursor                     Color(red=198, green=255, blue=0)
font_family                Ubuntu Mono
font_size                  15.0
foreground                 Color(red=255, green=255, blue=255)
macos_show_window_title_in window
macos_thicken_font         0.25
macos_titlebar_color       572662274
selection_background       Color(red=0, green=63, blue=142)
window_padding_width       FloatEdges(left=10.0, top=0, right=10.0, bottom=5.0)
```

**Comment by kovidgoyal** [comment]
I'm afraid I dont have the time/interest to debug espanso.

**Comment by jakeprice-dev** [comment]
I should have clarified that this _only happens in Kitty_ hence why I raised it. Espanso works in the way I expect in GNOME Terminal etc, just not Kitty? But I understand if you still don't have the interest/time. Not a problem.

**Comment by kovidgoyal** [comment]
it will use some horrible hack or the other to inject key events into
X11 applications, probably the XTEST extension, via something like
xdotool, supporting this is really not of interest to me, but patches
are most welcome.

**Comment by kovidgoyal** [comment]
And I will note that on my system

xdotool key colon
and
xdotool key semicolon
both work fine in kitty

**Comment by jakeprice-dev** [comment]
No problem, thanks!

**Comment by jakeprice-dev** [comment]
For future reference as per [here](https://github.com/federico-terzi/espanso/issues/579) adding `force_clipboard: true` in your Espanso config file fixes this behaviour.

```yml
  - trigger: ":kitty"
    force_clipboard: true
    replace: "This : is [] a test ;"
```

**Comment by Netpilgrim** [comment]
This workaround no longer works for me with Kitty 0.25.0 (not sure at which version it changed).
force_clipboard now replaces every match with the character "v", possibly a remnant of `<CTRL>+<SHIFT>+<V>`, which would paste from the clipboard in Kitty.

**Comment by svonjoi** [comment]
> This workaround no longer works for me with Kitty 0.25.0 (not sure at which version it changed). force_clipboard now replaces every match with the character "v", possibly a remnant of `<CTRL>+<SHIFT>+<V>`, which would paste from the clipboard in Kitty.

same

**Comment by chenyuntc** [comment]
I solve this issue in X11 by adding it to `.config/espanso/config/default.yml`:
```
disable_x11_fast_inject: true
```

**Comment by markcst** [comment]
> I solve this issue in X11 by adding it to `.config/espanso/config/default.yml`:
> 
> ```
> disable_x11_fast_inject: true
> ```

I confirm that this works (but with [these adjustments](https://github.com/espanso/espanso/issues/281#issuecomment-1404795033) by another honorable gentleman) even on Kitty `0.42.2 [2025-07-16]`, of course on X11. Thanks, thanks, thanks to both!

(I noticed that I can reduce the delay and it still works for me, at least)

EDIT: Sadly, when `backend: Clipboard` it's there, it breaks Espanso elsewhere, like in text editors (i.e.: Xed)

**Comment by Plautin** [comment]
**Environment**
- OS: Debian Trixie (testing)
- Session: X11
- Espanso version: 2.4.0
- Terminal: Kitty 0.41.1
- Keyboard layout: French AZERTY (fr, oss or latin9)

**Problem**
When using the `Inject` backend, Espanso fails to send modifier keys (Shift, AltGr, Ctrl, Alt) 
to Kitty. Only unshifted/base-layer characters are correctly injected. All shifted 
characters are downgraded to their base-layer equivalent.

**Examples (AZERTY)**
- Expected: "170546" → Got: "&èà('-"
- Expected: "Hello" → Got: "hello"
- Expected: "What?" → Got: "what,"

**Root cause hypothesis**
Kitty's keyboard protocol (CSI u) expects explicit modifier bits in key events. 
XTest synthetic events generated by Espanso appear to lose or mis-encode modifier 
state when crossing into Kitty's input path.

**Workaround**
Using `backend: Clipboard` with `paste_shortcut: CTRL+SHIFT+V`  doesn't bypasse the issue, 
even if clipboard paste is supposed not travel through the keycode translation layer.

**Reference**
Related: kovidgoyal/kitty#4487
