### ISSUE TITLE
Panels show in the wrong places

### ISSUE THREAD

**Issue by johnharris85** [kovidgoyal/kitty#4488]
**Describe the bug**
When following the example for a simple panel, the panel shows in incorrect positions on the screen. Both `bottom` and `top` show the panel at the top. Both `left` and `right` show it on the left. Almost like it's wrapping or something?

**To Reproduce**
1. `$ kitty +kitten panel --lines 2 --edge bottom sh -c 'printf "\n\n\nHello, world."; sleep 5s'`.
2. See error, panel appears at top of the screen (even though there is a displaced area at the bottom like it's trying to put something there?).

**Screenshots**
![bottom](https://user-images.githubusercontent.com/746221/148702822-ed183e9f-98e1-43a6-ac1d-c96d62b6f103.png)
![top](https://user-images.githubusercontent.com/746221/148702826-39bfa63e-71b7-4af2-87c9-461898b36421.png)
![left](https://user-images.githubusercontent.com/746221/148702832-77b77a2d-493b-43ff-b369-04e0ab289366.png)
![right](https://user-images.githubusercontent.com/746221/148702833-1120008d-e5d9-4f45-956e-f8e162e7b00f.png)

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux jharris-laptop 5.10.0-1053-oem #55-Ubuntu SMP Sun Dec 12 01:58:07 UTC 2021 x86_64
Ubuntu 20.04.3 LTS jharris-laptop /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Running under:X11
Frozen: True
Paths:
  kitty: /home/john/.local/kitty.app/bin/kitty
  base dir: /home/john/.local/kitty.app/lib/kitty
  extensions dir: /home/john/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/john/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.9
confirm_os_window_close 1
enable_audio_bell       False
enabled_layouts         ['horizontal', 'vertical', 'grid', 'tall', 'fat']
font_family             MesloLGS NFo
tab_bar_style           powerline
update_check_interval   0.0
```

**Additional context**
Reproduces identically with `--config NONE`.

**Comment by kovidgoyal** [comment]
Doesnt repro for me. This is likely something specific to your window manager, it doesn't support _NET_WM_STRUT_PARTIAL properly. Probably it forces dock type windows to top/left. 

The relevant code is very simple, it just calls xprop see kittens/panel/main.py
