### ISSUE TITLE
Cursor disappears on unfocused kitty after switching i3 workspaces

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#449]
This doesn't happen every time, but it happens often enough to be annoying.

Using these steps I could get almost 100% reproducibility:

1. Close all windows on all workspaces
2. On workspace 1, open two kitty side by side
3. Switch to workspace 2, open two kitty side by side
4. Switch back to workspace 1, try to move cursor above both kitty windows

When cursor is above the unfocused kitty, it disappears.

![kitty-cursor-issue](https://user-images.githubusercontent.com/1177900/38497298-f07f2ad0-3c00-11e8-8c45-1abef2f934eb.gif)

I saw you use i3 too, can you reproduce?

**Comment by cyrinux** [comment]
I have the same problem on archlinux + i3 too. 
i3 4.15.0.1 
Kitty 0.8.4.

**Comment by maximbaz** [comment]
Apparently this bug is related to `mouse_hide_wait` option, which has a default value of `3.0`.

The workaround is to set `mouse_hide_wait 0` in the config.

**Comment by kovidgoyal** [comment]
I haven't seen it as far as I can recall, and if you set mouse_hide_wait to zero you disable hiding of the mouse cursor, which will of course prevent the mouse cursor from ever being hidden.

**Comment by kovidgoyal** [comment]
Looking at the code, I dont see any possibility of a bug in kitty. kitty calls show_mouse_cursor() whenever glfw reports any mouse event. SO even if the mouse cursor is hidden, simply moving it around will call show_mouse_cursor(). This can be easily verified by putting printf() into show_mouse_cursor() and hide_mouse() in glfw.c

**Comment by maximbaz** [comment]
That is true, the bug happens only with unfocused windows - and when I click on the window to bring it back to focus, the cursor will immediately show up.

So it seems the bug cannot be fixed due to glfw's limitations of changing the cursor visibility for non-focused windows?

**Comment by kovidgoyal** [comment]
Sure it can be fixed, one just has to fix glfw :)

**Comment by kovidgoyal** [comment]
For instance, this patch should take care of it, since as far as I can tell the requirement that the window be focused to change the mouse cursor is Apple only:

```diff
diff --git a/glfw/input.c b/glfw/input.c
index e78a8c12..0a1b1f0f 100644
--- a/glfw/input.c
+++ b/glfw/input.c
@@ -620,7 +620,9 @@ GLFWAPI void glfwSetInputMode(GLFWwindow* handle, int mode, int value)
                                   &window->virtualCursorPosX,
                                   &window->virtualCursorPosY);
 
+#ifdef __APPLE__
         if (_glfwPlatformWindowFocused(window))
+#endif
             _glfwPlatformSetCursorMode(window, value);
     }
     else if (mode == GLFW_STICKY_KEYS)
```

**Comment by maximbaz** [comment]
Huh, I thought the glfw is an external library 🙂 I confirm that it does fix the issue!

**Comment by kovidgoyal** [comment]
It is an external library, kitty just has its own forked copy with various improvements.

**Comment by kovidgoyal** [comment]
Reported upstream as: https://github.com/glfw/glfw/issues/1247
