### ISSUE TITLE
How to get hints on compiler errors ? And jump into editor on error file and line ?

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#4491]
Consider this:

```zsh
❯ gcc -Wall main.c
main.c:6:3: error: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [-Werror,-Wimplicit-function-declaration]
  printf("Hello world\n");
  ^
main.c:6:3: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
main.c:4:7: warning: unused variable 'bla' [-Wunused-variable]
  int bla;
      ^
1 warning and 1 error generated.
```

How can you get [hints](https://sw.kovidgoyal.net/kitty/kittens/hints/) on just `main.c:6` and open `vim` directly on that line ?

---

Bonus: can you additionally include columns in this ? i.e hint selection would include them and `vim` opens cusor directly in that file, on that line, on that column.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/hints/#cmdoption-kitty-kitten-hints-linenum-action

**Comment by akharrou** [comment]
> https://sw.kovidgoyal.net/kitty/kittens/hints/#cmdoption-kitty-kitten-hints-linenum-action

I tried this:

```properties
# kitty.conf

map super+y kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}
```

...but I keep getting "`No matches found, press Enter to quit.`"

**Comment by akharrou** [comment]
I also tried this:

```properties
# kitty.conf
    map super+y _hints --linenum-action=window --type=regex --regex="\b(?P<filepath>.+):(?P<line>\d+):(?P<column>\d+)" --program="nvim +{line} {filepath}"
```

Which gives me matches on more than just what I need, by matching the command prompt paths, and doesn't seem to do anything once I select a hint... something wrong with my usage of `--program`  ?

![Screen Shot 2022-01-10 at 11 03 39 AM](https://user-images.githubusercontent.com/36056254/148734275-38a083e6-bb07-4866-88bc-62cc048cdca6.png)

So I also tried removing `--program …` like in other examples...

```properties
# kitty.conf
    map super+y _hints --linenum-action=window --type=regex --regex="\b(?P<filepath>.+):(?P<line>\d+):(?P<column>\d+)" nvim +{line} {filepath}
```
...but that doesn't work either and I get: "`Extra command line arguments present: vim + (line} {filepath} Press Enter to quit`"

**Comment by page-down** [comment]
`main.c` cannot be matched by the default rules (ext 2~7). This issue has also been on my list for a while.

```python
def linenum_marks(...)
    # ...
    regex = r'(?P<path>(?:\S*/\S+?)|(?:\S+[.][a-zA-Z0-9]{2,7})):(?P<line>\d+)'
```

@kovidgoyal 
Is there a negative impact if we add single-letter `c`, `h`, `m` files?

**Comment by kovidgoyal** [comment]
On Mon, Jan 10, 2022 at 12:12:55AM -0800, page-down wrote:
> `main.c` cannot be matched by the default rules (ext 2~7). This issue has also been on my list for a while.
> 
> ```python
> def linenum_marks(...)
>     # ...
>     regex = r'(?P<path>(?:\S*/\S+?)|(?:\S+[.][a-zA-Z0-9]{2,7})):(?P<line>\d+)'
> ```
> 
> @kovidgoyal 
> Is there a negative impact if we add single-letter `c`, `h`, `m` files?

Should be ok to add aother branch to the regex of the form:
(?:\S+[.][hcm])
