### ISSUE TITLE
Kitty uses the wrong font variant of Fira Code

### ISSUE THREAD

**Issue by pxeger** [kovidgoyal/kitty#4498]
**Describe the bug**

I have set
```
font_family Fira Code
```
But Kitty renders only Fira Code Light. I have tried setting the font to `Fira Code Retina`, `Fira Code Medium`, etc., but none of them have any effect.

Kitty still uses the Bold variant correctly for text marked as bold in the terminal stream.

**To Reproduce**
1. Install Fira Code (specifically I'm using the Arch Linux package `community/ttf-fira-code 6.1-1`)
2. Set `font_family Fira Code`
3. Run Kitty
4. See that only the light variant is being used

**Screenshots**

Here is a comparison with Konsole configured to use Fira Code Retina (which is what it's supposed to look like):

![2022-01-12_08-31](https://user-images.githubusercontent.com/67427173/149091707-3de06042-2acc-4637-afb2-4aae60afa4e0.png)

Here is a comparison with Konsole configured to use Fira Code Light:

![2022-01-12_08-30](https://user-images.githubusercontent.com/67427173/149091539-c4fe893a-af74-44da-b018-4bc5caac3b13.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux [...] 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Loaded config files:
  [...]/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 0.0
editor                nvim
enable_audio_bell     False
font_family           Fira Code Medium
shell                 tmux
Added shortcuts:
	ctrl+  KeyAction('send_text', ('all', b'\x00\x00'))
	shift+ctrl+a KeyAction('send_text', ('all', b'\x00p'))
	shift+ctrl+d KeyAction('send_text', ('all', b'\x00n'))
	shift+ctrl+z KeyAction('send_text', ('all', b'\x00z'))
Removed shortcuts:
	shift+ctrl+a > 1 KeyAction('set_background_opacity', ('1',))
	shift+ctrl+a > d KeyAction('set_background_opacity', ('default',))
	shift+ctrl+a > l KeyAction('set_background_opacity', ('-0.1',))
	shift+ctrl+a > m KeyAction('set_background_opacity', ('+0.1',))
	shift+ctrl+r KeyAction('start_resizing_window')
	shift+ctrl+escape KeyAction('kitty_shell', ('window',))
Changed shortcuts:
	shift+ctrl+0 KeyAction('send_text', ('all', b'\x00%'))
	shift+ctrl+9 KeyAction('send_text', ('all', b'\x00"'))
	shift+ctrl+q KeyAction('close_window')
	shift+ctrl+t KeyAction('send_text', ('all', b'\x00c'))
	shift+ctrl+w KeyAction('send_text', ('all', b'\x00xy'))
Colors:
	background            #282828   
	color0                #282828   
	color1                #cc241d   
	color10               #b8bb26   
	color11               #fabd2f   
	color12               #83a598   
	color13               #d3869b   
	color14               #8ec07c   
	color15               #ebdbb2   
	color2                #98971a   
	color3                #d79921   
	color4                #458588   
	color5                #b16286   
	color6                #689d6a   
	color7                #a89984   
	color8                #928374   
	color9                #fb4934   
	cursor                #ebdbb2   
	foreground            #ebdbb2   
	selection_background  #ebdbb2   
	selection_foreground  #282828   
```

**Additional context**

Output of `strace -fo kitty_fonts.strace.log kitty; grep ttf kitty_fonts.strace.log` proves that only Fira Code Light is being used:

```
8140  openat(AT_FDCWD, "/usr/share/fonts/TTF/FiraCode-Light.ttf", O_RDONLY) = 21
8140  openat(AT_FDCWD, "/usr/share/fonts/TTF/FiraCode-Bold.ttf", O_RDONLY) = 21
8140  openat(AT_FDCWD, "/usr/share/fonts/TTF/FiraCode-Light.ttf", O_RDONLY) = 21
8140  openat(AT_FDCWD, "/usr/share/fonts/TTF/FiraCode-Bold.ttf", O_RDONLY) = 21
```

**Comment by pxeger** [comment]
Ah, `kitty list-fonts` only shows Fira Code Light and Bold, so maybe this is a duplicate of #1968; I'll try the workaround there

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by pxeger** [comment]
Don't you just hate it when your pacman mirror suddenly stops being updated, so you think it can't just be out-of-date packages...

**Comment by page-down** [comment]
When I saw the version you mentioned, I got worried for a second.
Isn't it possible that after Archlinux has not been updated for a while, there could be problems when it is updated again? I'm just curious.

**Comment by pxeger** [comment]
I don't think that was the problem; just whichever mirror I had configured previously must have suddenly stopped being maintained. I switched to another one and it's all fixed now (although now I've got 400 packages to update...)

**Comment by kovidgoyal** [comment]
> When I saw the version you mentioned, I got worried for a second. Isn't it possible that after Archlinux has not been updated for a while, there could be problems when it is updated again? I'm just curious.

The only time this causes problems in my experience is if the arch package or repository format changes and then usually there a static binaries of pacman available to get you over the hump. I had issues with some of my arch servers when arch switched to zstd for packages, but easily enough fixed.
