### ISSUE TITLE
Graphic display with btop tool

### ISSUE THREAD

**Issue by lcheylus** [kovidgoyal/kitty#4499]
**Describe the bug**
I'm using btop tool https://github.com/aristocratos/btop/ to monitor my Linux system. This tool is a "modern" version of top/htop to display CPU, memory, processes, disk usage with graphic representation in terminal.

btop uses some graphic characters to print graphs (see code in https://github.com/aristocratos/btop/blob/main/src/btop_draw.cpp).

I have some difference with graphics using Kitty terminal and other VTE terminal (Terminator).

**Screenshots**
btop screenshot with Kitty 0.24.1
![Screenshot_Kitty](https://user-images.githubusercontent.com/3294998/149168287-0a436c8d-f424-49a9-b0ab-52836db7c799.png)

btop screenshot with Terminator 2.1.1
![Screenshot_Terminator](https://user-images.githubusercontent.com/3294998/149168299-d965000a-2e2d-4eb2-b2c5-ffabb78b78a5.png)

**Environment details**
Linux Debian testing (bookworm) on amd64.

```
Kitty config (partial)
kitty 0.24.1 created by Kovid Goyal
Linux echoes 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) x86_64
Debian GNU/Linux bookworm/sid echoes /dev/tty

Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/fox/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 0.0
disable_ligatures     2
enable_audio_bell     False
enabled_layouts       ['splits:split_axis=horizontal']
font_family           DejaVuSansMono Nerd Font Mono
font_size             9.0
update_check_interval 0.0
```

**Comment by kovidgoyal** [comment]
Matching another terminals rendering of a character is not a design goal for kitty. if you feel some character is not rendered correctly as per the unicode standard by kitty, feel free to post that character an what you think is wrong with its rendering. The characters here are all rendered correctly by kitty as far as I can see. by doing

echo " ", "░", "░", "▒", "▒""⡇", "⡏", "⡟", "⡿", "⣿"; read

if there is some other character you think is not rendered properly do an echo of it and post a screenshot. And I will examine in more detail.

**Comment by page-down** [comment]
Please note that the font you use also affects the rendering.
I actually tried this program under macOS with the fonts I am using and all I can say is that btop is working perfectly.

You can also use symbol_map to apply a different font to these characters.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map

**Comment by page-down** [comment]
Oh, maybe I didn't understand this well enough. Thanks for pointing that out.

**Comment by kovidgoyal** [comment]
That's to be expected. If the cell height is not an even multiple of 8 (there are 8 rows in a  braille character) there will be some left over. Causing an extra gap at the bottom. One could in theory distribute that extra left over among the the gap rows to avoid it, but I am not at all sure that would actually look better. But sure if you wish to try it, it should be a fun and simple patch to the function braille_dot in box_drawing.py

**Comment by lcheylus** [comment]
It's also my issue : there is a vertical gap between braille characters => see my screenshot with Kitty in my first post.

**Comment by page-down** [comment]
Thanks. I tried the latest changes and it renders quite nice.

**Comment by lcheylus** [comment]
Thanks, I applied your modifications for `fonts/box_drawing.py` : no more vertical gap between braille characters => rendering in Kitty with `btop` tool is perfect.

**Comment by clort81** [comment]
I see now the many special cases handled in
/usr/lib/kitty/kitty/fonts/render.py
While it is perhaps laudable that you attempt to 'fix' box and block drawing for your users, I reccommend providing a means to disable this behavior in kitty.conf.
"I will override user font choices" is not respecting your users.
In particular, braille characters are useful as box-drawing characters. We view these glyphs on screens, with our eyes.
Blind people do not need to read braille on screens, with their eyes, which don't work, because they are blind.
Terminal users do need to have control over their font rendering.
Please add an option to disable your overriding user font choices in kitty.conf
