### ISSUE TITLE
Questions about hints multi-select mode

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4500]
When using the kitten hints multi-select mode, multiple presses on the same item will produce multiple duplicate option results.
Is this how it is designed?

Is it possible to toggle whether the option is selected or not, using a different color to mark it? Currently when selected, hints will disappear and cannot be deselected.

Also is it possible to use `enter` to confirm the multiple selection and `esc` to exit as in single select mode?
Perhaps it would be easier for users if `esc` in single-select and multi-select modes unified to indicate cancellation of the operation.

I'd like to improve this feature and the docs, so I'll ask for your opinion first.

**Comment by kovidgoyal** [comment]
On Wed, Jan 12, 2022 at 07:45:58AM -0800, page-down wrote:
> When using the kitten hints multi-select mode, multiple presses on the same item will produce multiple duplicate option results.
> Is this how it is designed?

Dont remember, I dont use this feature myself so I dont really have an
opinion on this. Offhand I cant think of many uses for selecting the
same item multiple times, so toggling makes sense.

> 
> Is it possible to toggle whether the option is selected or not, using a different color to mark it? Currently when selected, hints will disappear and cannot be deselected.

Possible, sure, patches are welcome.

> 
> Also is it possible to use `enter` to confirm the multiple selection and `esc` to exit as in single select mode?

You need enter if you want to select a single item in a multiple
selection and that item's hint is a prefix of another hint. I suppose
you could use and enter with no partial selection to mean finish, but
its fairly confusing. And changing it now would be backwards
incompatible so if you really want to do it at least make it
configurable.

> Perhaps it would be easier for users if `esc` in single-select and multi-select modes unified to indicate cancellation of the operation.
> 
> I'd like to improve this feature and the docs, so I'll ask for your opinion first.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/4500
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by kovidgoyal** [comment]
Closing as not really an issue feel free to continue the discussion.
