### ISSUE TITLE
Deadkeys stop working properly after reboot (BR-ABNT2)

### ISSUE THREAD

**Issue by C07733** [kovidgoyal/kitty#4502]
On my current keyboard layout(BR-ABNT2) "~" is a dead-key that allows me to form characters like "ã", but after a reboot it has stopped working together with all other ones (´, ^, ...)

This is the second time this has happened on two different Arch installs, this time on a fresh install.
After the first reboot it stops working, and no other consecutive reboot fixes the issue, it persists.

You can still insert the Deadkeys symbols by pressing AltGr but they wont form the special characters, I usually inserted them by pressing space, so "\~" + "space" would lead to "~", that does not work anymore.

**1.** Install Kitty
**2.** Reboot 
**3.** Set keyboard layout to br (setxkbmap br), might work with deadkeys from other languages
**4.** Deadkeys cannot be placed to form the special characters, and can only be inserted with AltGr

**Environment details**
```
kitty 0.24.1 (17cada7a6a) created by Kovid Goyal
Linux pc01 5.15.13-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 05 Jan 2022 16:21:01 +0000 x86_64
Arch Linux 5.15.13-zen1-1-zen (/dev/tty)

Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh

Config options different from defaults:

```
Running without a config and even under a clean xorg environment (startx /usr/bin/kitty) the problem persists.

I ran other terminal emulators, and I could insert dead-keys without issue.

I uninstalled it, installed a different package from AUR (kitty-git) and the problem persists.

Any ideas?

**Comment by kovidgoyal** [comment]
Works on my arch system with the following steps:

1) Run kitty
2) setxkbmap br
3) press the ' key on my us layout keyboard and then the a key
4) ã is inserted, as expected.

I dont have the same keyboard as you obv to test with but as far as I
can see the dead keys are working fine.
