### ISSUE TITLE
Add new options to config file on upgrade

### ISSUE THREAD

**Issue by dimaqq** [kovidgoyal/kitty#4503]
Apologies if this was asked for and I was unable to find it.

I've started with kitty from `apt install`, which brought in a pretty old version.
I've edited the config.
Then I've installed new kitty from official shell script and removed the apt version.

I'd love it if the new config options (e.g. `visual_bell_color`) were automatically added (commented out) to my config.

Without that, I'm not sure what can in fact be configured...

**Comment by kovidgoyal** [comment]
All configurable options are documented at
https://sw.kovidgoyal.net/kitty/conf/ 

If you want to generate an up to date commented kitty.conf simply rename
the existing one and press ctrl+shift+f2
