### ISSUE TITLE
Shell integration bug: my cursor_shape is block, but kitty still sets it to beam without `shell_integration no-cursor`.

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#4504]
**Describe the bug**
I hope this wasn't on purpose, as it was annoying to debug without context (wasn't even aware shell integrations are a thing now).

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux budou 5.15.13-arch1-g14-1 #1 SMP PREEMPT Sat, 08 Jan 2022 14:47:06 +0000 x86_64
Arch Linux 5.15.13-arch1-g14-1 (/dev/tty)

Running under:Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/fred/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control  y
box_drawing_scale     (0.1, 1.0, 1.5, 2.0)
clipboard_control     ('write-clipboard', 'write-primary')
cursor_blink_interval 0.0
enable_audio_bell     False
font_family           Fira Code
font_size             12.0
shell_integration     frozenset({'no-cursor'})
tab_separator          â<U+0094><U+0087>
visual_bell_duration  0.3
Changed mouse actions:
         b1 -2 ungrabbed mouse_click_url_or_select
         shift+b1 -2 ungrabbed mouse_click_url_or_select
         shift+b1 -2 grabbed mouse_click_url_or_select
         shift+ctrl+b1 repeat ungrabbed mouse_click_url
         shift+ctrl+b1 repeat grabbed mouse_click_url
Added shortcuts:
        shift+super+w close_os_window
Changed shortcuts:
        shift+ctrl+e kitten hints
Colors:
        color10               #00ff00   
        color2                #008800   

This debug output has been copied to the clipboard
```

**Comment by kovidgoyal** [comment]
Yes, it's by design. cursor_shape does only controls the cursor shape
when the client program doesnt set it. shell_integration by default sets
an appropriate cursor shape for the current editing mode. This is
documented in the docs for cursor_shape https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape

**Comment by ctrlcctrlv** [comment]
Sorry but that's really strange, and of course if your kitty.conf is old you won't have this new comment.

**Comment by ctrlcctrlv** [comment]
I came up with a compromise. _If `shell_integration` is unset_, then consider it `no_cursor` (hint that user has old `kitty.conf`). This just hit Arch and I promise you I won't be the only one confused when it starts hitting more popular distros...

**Comment by kovidgoyal** [comment]
I dont think so. I am fine with dealing with some short term confusion.
It hit arch several days ago, and there have already been about 6 issues
about it. I just have an auto-response for them :))

I definitely dont want to introduce magic behavior like the absence of a
setting giving it a value.

**Comment by ctrlcctrlv** [comment]
What about a config file updater? I wrote one for MFEKglif—when config is out of date, you're warned and told what's missing.

![image](https://user-images.githubusercontent.com/838783/149303047-47298a22-0b5a-4982-be26-2faf9437bbb8.png)

Probably Kitty shouldn't use defaults for all, MFEKglif just does because keybinds are especially sensitive and can conflict and it's unclear what the "right" answer is when they do.

**Comment by kovidgoyal** [comment]
You are welcome to write a config file updater, though doing so robustly is going to be pretty difficult given that config file comments are free form text. The default generated kitty.conf has all settings set to default values but commented out.

**Comment by ctrlcctrlv** [comment]
Well, what are we interested in preserving between versions? I don't see why we can't just handle this in another OS thread. Write a file in the config dir called e.g. `version`, and if that's mismatched, read all config options, and rewrite the file with new comments and current values, destroying any commented out line that's not from us, but no values.

**Comment by kovidgoyal** [comment]
I would be pretty annoyed if software updating nuked comments I had
added to a config file to exaplin something to myself. And of course
then you will have the whole pitchforks and torches crowd who will want
to lynch you for daring to update a config file that they have put in
version control during a software update.
