### ISSUE TITLE
DejaVu Sans Mono only renders as italics

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#451]
This is really weird and I'm not completely sure that this is something to do with kitty, but this behavior doesn't appear in iTerm. If I set my font family as `font_family DejaVu Sans Mono`, all the text is rendered in italics.

If you have any tips on troubleshooting this, that'd be great.

**Comment by Alok** [comment]
FWIW, this behavior did not appear on kitty 0.5.1 and macos 10.11, but does appear on the same version of kitty and any higher one on macos 10.13.

**Comment by kovidgoyal** [comment]
Presumably coretext is choosing the oblique variant of deja vu sans mono as the regular.  I'm afraid I have no idea why it might be doing that. What does 

kitty +list-fonts

output?

**Comment by kovidgoyal** [comment]
You probably need to use the full name

DejaVu Sans Mono Book

**Comment by Alok** [comment]
Yep, fixed it. Wonder why it never threw an error before.
