### ISSUE TITLE
adjust_line_height does not take HiDPI into account

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4511]
**Describe the bug**

The `adjust_line_height` (and possibly `adjust_column_width`) do not seem to take the screen density into account.  As a result window layout on my 4K display is different than the rest of the teammates, who run 1920x1080.

**To Reproduce**

With screen scale set to 100%:

1. `kitty -c none --start-as=fullscreen`
2. `echo $LINES`
3. CTRL+D
4. `kitty -c none --start-as=fullscreen -o adjust_line_height=1`
5. `echo $LINES`
6. CTRL+D

Now Repeat with screen scale set to 200%.

**Observed Behavior**

| Screen Resolution  | Step 2 | Step 5
| ------------------ | ------ | ------
| 3840x2160 @200%    | 60     | 58
| 1920x1080 @100%    | 60     | 56

**Expected Behavior**

The screen layout shall be identical regardless of the screen density.

**Environment details**

```
kitty 0.24.1 created by Kovid Goyal
Linux byteevo-scm 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64
Ubuntu 20.04.3 LTS byteevo-scm /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Running under:X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  adjust_line_height 1

Config options different from defaults:
adjust_line_height 1
```

**Additional context**

1. So one pixel here and there might not seem like a big deal.  However, I have a set of scripts that run on my machine as well as on my teammates machines.  Some of my scripts open a kitty window with splits and adjust their size.  The fact that the window layout is different between my machine and the rest means that I now have to compensate for this within my scripts (because one window within a tab comes out smaller on my machine with the same number of steps adjustment made by the script).

1. While we are at it, we may also want to double-check `tab_bar_margin_height` as the tab bar is one pixel off between my machine and rest with the following in `kitty.conf`.

    ```
    tab_bar_margin_height 8 8
    ```

**Comment by kovidgoyal** [comment]
adjust_* take either pixels or percentages. pixels means actual pixels,
not logical pixels. If you want DPI independent adjustments, use
percentages or manually adjust the pixel value for your scale.
