### ISSUE TITLE
icat: rotate, mirror, alpha

### ISSUE THREAD

**Issue by dagbdagb** [kovidgoyal/kitty#4513]
**Is your feature request related to a problem? Please describe.**
I have discovered the icat kitty. I love it. I have found some minor usability issues with it:

- occasionally an image is rotated the wrong way. The ability to fix  that with an option to icat removes the need to modify the image.
- mirroring is just a logical extension of the above item
- I have found that various PDF readers handle PDFs with transparent backgrounds differently. icat honors the transparency. So if a PDF with black text on a transparent background is icat'ed in a terminal with a black background, there is no visible text. Looks perfectly fine in some PDF readers, so the issue may very well not be obvious to users. Apart from image not showing up in the terminal.

**Describe the solution you'd like**
Options '--mirror <hor|vert>' and '--rotate [NN]' (NN=degrees, range -360 - 360, 'cw'/'ccw' as aliases for 90/270) sounds like natural choices for the first two options. That said, I do notice there is some kind of automagic going on for rotation, depending on terminal width/height. 

Regarding alpha, I am not sure if this applies to PDFs only? '--alpha 'somesolidcolor' might be a sufficient user interface for handling this? Only assuming IM can be called with the right options to fix this. Also, maybe a (default?) warning if someone icats an image with alpha to a terminal with black background? Not sure if additional heuristics for a warning is hard to implement.

**Describe alternatives you've considered**
The alternative implies using a utiltiy to modify the sources prior to icat'ing them. And that kind of defeats the purpose of icat, I think.

**Additional context**
Linux, Wayland, wayfire, kitty 0.23.1.

Thank you for kitty!

**Comment by allemangD** [comment]
You can already pipe output from ImageMagick to icat to do what you describe.

    convert photo.png -rotate 90 - | kitty +kitten icat

The options you've listed are: 

- `-flip` vertical mirror
- `-flop` horizontal mirror
- `-rotate <deg>`

Since icat already uses ImageMagick to load images, I imagine it would be fairly straightforward to add such functionality, however since the piping method already gives you access to _all_ of ImageMagick's features it seems superior to me.

----

How are you using icat to view pdfs?

**Comment by dagbdagb** [comment]
@allemangD  thank you for the piping example. I'll make a note of it, but l'll eave the FR open. 

IM handles PDFs "natively", but ghostscript had a security bug which made distributions disable PDFhandling in IM for a while. You may have to edit your policy.xml.    See https://bugs.gentoo.org/664236 for example.

**Comment by dagbdagb** [comment]
Thank you,

Rotation would be easier to implement if clamped to 90 degrees CW or CCW only, right? Just need to transpose width/height and otherwise go with the regular code. This would also cover 99.9% of all use-cases.  😬

**Comment by kovidgoyal** [comment]
I was talking about transposition only. For non-square images that still
changes image dimensions.
