### ISSUE TITLE
Resizing kitty in floating mode briefly shows large black areas before re-rendering

### ISSUE THREAD

**Issue by samEngineering** [kovidgoyal/kitty#4517]
Greetings. First off, great job on this program! Kitty is super awesome :)
My issue is that if kitty is launched in a floating window and I use the mouse or keyboard to resize the window, then large areas of the window are black for a second before kitty renders again. It seems like kitty is the only program I know of that does this on my system.
I tried recreating this situation with and without the following programs/settings:

picom,
dt's shell color scripts,
sync_to_monitor yes/no (in kitty.conf)

Unfortunately, the issue persists regardless. Here is some info about my system:

OS: ArcoLinux 
Kernel: 5.15.13-arch1-1 
GPU: NVIDIA GeForce GTX 1050
two monitors, Dell and Asus: each 60Hz

Thanks in advance!

**Comment by kovidgoyal** [comment]
This is by design. Continuous resizes are very inefficient for terminal
programs as they have to hanfle the SIGWNCH signal for every resize and
essentially redraw. SO kitty will only send SIGWNCH once resizing is
done.
