### ISSUE TITLE
Too many hints produces ones with overlapping names

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#4520]
> regarding the `hint` kitten, I use: `--alphabet "alskdjfghnvcmbxzpqwoeiruyt1029384756"`

![Screen Shot 2022-01-15 at 12 23 34 PM](https://user-images.githubusercontent.com/36056254/149616889-fb2186cc-6fe6-4d13-87a7-d95dce79410a.png)

After pressing `l` it just waits for another character...

![image](https://user-images.githubusercontent.com/36056254/149616894-cadcd3f6-7d6e-4396-bcda-661f3235b5a0.png)

**Comment by kovidgoyal** [comment]
press enter after pressing l. https://sw.kovidgoyal.net/kitty/kittens/hints/

**Comment by akharrou** [comment]
@kovidgoyal I don't see it in the docs, but regardless, ones without overlapping names works without pressing enter. Can't the hint names extend to more characters ?

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/b32edf54f8a704946cccf332251236dbaa2df34b

esc *cancels/ends*. enter selects. This is pretty basic UI across everything. But I have added a note about it. And you can have as many characters as you want via --alphabet

**Comment by akharrou** [comment]
@kovidgoyal I meant like, the hints all have at most 2 characters on the screen in the screenshot. but couldn't it be that instead of having single character hints names that clash with 2 letter hints names, couldn't the hints names only have single character names only if no future permutation will clash, else have only single character names for the ones that don't clash and 2 character names for the ones that would, else 3, else 4, etc. E.g. vimium does this:

![image](https://user-images.githubusercontent.com/36056254/149617665-7ca6c501-0779-48a4-815c-fdb298714fa6.png)

**Comment by akharrou** [comment]
But I understand your busy... the pressing the "enter" key isn't that bad.

**Comment by akharrou** [comment]
@kovidgoyal actually, can you add the press "Enter" for `hints --multiple` as well ? rn you can only press `Esc` to stop selecting.

**Comment by kovidgoyal** [comment]
no, you need enter to select overlapping selections in multiple mode too

**Comment by davidscotson** [comment]
A couple of config based workarounds for people that don't like hitting enter:

you can set --hints-offset to the same number as the count of characters in your --alphabet. This then starts from double characters and you don't get overlapping prefixes until you've used number of characters squared.

Or, if you still like to use a single character when possible, you can put a few sacrificial letters at the start of the list, and use hints-offset to skip them. You'll use the rest of the characters as single letters, and when it starts using double letters, it'll start with the ones you skipped, delaying the point where overlaps happens to an adjustable amount, depending on the number of characters skipped.
