### ISSUE TITLE
Blinking pipe cursor instead block shape

### ISSUE THREAD

**Issue by mikaelz** [kovidgoyal/kitty#4521]
**Describe the bug**
Hi, please help. After some update I have a blinking pipe and not the block shape in zsh with https://github.com/ohmyzsh/ohmyzsh/
In .config/kitty/kitty.conf I have `cursor_shape block`

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux t440p 5.16.0-arch1-1 #1 SMP PREEMPT Mon, 10 Jan 2022 20:11:47 +0000 x86_64
Arch Linux 5.16.0-arch1-1 (/dev/tty) | 1 user logged in | Sat Jan 15 2022 11:01:22
Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/mike/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height         1
click_interval             0.5
clipboard_control          ('write-clipboard', 'write-primary')
cursor_blink_interval      0.5
enable_audio_bell          False
font_family                DejaVu Sans Mono
font_size                  10.0
macos_option_as_alt        3
open_url_with              ['brave']
scrollback_lines           10000
select_by_word_characters  :@-./_~?&=%+#
single_window_margin_width FloatEdges(left=-1000.0, top=-1000.0, right=-1000.0, bottom=-1000.0)
window_border_width        (1.0, 'pt')

```

**Additional context**
Tried `kitty --config NONE` but the same

**Comment by page-down** [comment]
The new shell integration feature changes the shape of the shell prompt cursor.

https://sw.kovidgoyal.net/kitty/shell-integration/

For `cursor_shape` please refer to the following link.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape

If you just don't like the cursor being changed, you can configure `shell_integration  no-cursor`.

**Comment by mikaelz** [comment]
Huge thank you. Adding `shell_integration disabled` to kitty.conf solved it
