### ISSUE TITLE
How to properly `send_text` CSI sequence keys ?

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#4524]
What's the proper syntax for sending CSI sequences ? E.g. I'd like to do something along the lines of:

```plaintext
# kitty.conf
map … send_text all ^[[1;9A
map super+u send_text all ^[[117;9u
```

but this seems to only send literal text to the shell. I tested it with this:

```zsh
$ function myzshfunc() { echo works }; zle -N myzshfunc; bindkey $'^[[117;9u' myzshfunc
```

and the function doesn't get triggered.

**Comment by akharrou** [comment]
This seems to work:

```plaintext
# kitty.conf
map super+up send_text all \x1b[1;9A
map super+down send_text all \x1b[1;9B
map super+u send_text all \x1b[117;9u
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Send-arbitrary-text-on-key-presses

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program
