### ISSUE TITLE
Vim background not displayed correctly

### ISSUE THREAD

**Issue by valacar** [kovidgoyal/kitty#4526]
**Describe the bug**
In Vim, the background doesn't seem to be displayed properly after scrolling with the j/k keys or Ctrl-d and Ctrl-u (possibly other methods). Where the text characters are displayed, the background color is correct, but everywhere else in the blank areas of the window it's incorrectly drawn in black after scrolling back.

I don't have this issue with any other terminals. Tested with xterm, st, xfce4-terminal, alacritty, and wezterm which all work properly.

**To Reproduce**
1. Compile kitty (I'm on 0.24.1 (71106bcd39)) with simply `make`.
2. Compile [Vim](https://github.com/vim/vim) (I'm on the latest 8.2 patch 4118). Compiled with `CFLAGS='-O2 -march=native -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1' ./configure` followed by `make -j` and `sudo make install`.
3. Run `./kitty/launcher/kitty --config NONE` from where kitty was compiled.
4. In kitty terminal, run `vim -u NONE -c 'colo blue' /usr/share/doc/kitty/kitty.conf` to open a text file with no Vim configuration, and apply the default "blue" colorscheme that comes with Vim.
5. Scroll down with the `j` key or `Ctrl-d`. Then scroll back up with the `k` key or `Ctrl-u`. `:ver` will also give the same effect.
6. Notice that the background is drawn in two different color, black and blue, when it should just be all blue.

**Screenshots**
![Screenshot_2022-01-16_17-05-09-opt](https://user-images.githubusercontent.com/8539935/149685957-2475f280-cbf1-42f7-8f59-54bcaa1672ff.png)

**Environment details**
```
kitty 0.24.1 (71106bcd39) created by Kovid Goyal
Linux linux-pc 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64
Manjaro Linux 5.15.12-1-MANJARO  (linux-pc) (/dev/tty)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.1
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under:X11
Frozen: False
Paths:
  kitty: /disk2/compile/kitty/kitty/launcher/kitty
  base dir: /disk2/compile/kitty
  extensions dir: /disk2/compile/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

-----------

inxi -G output:

Graphics:
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 495.44
  Display: x11 server: X.Org 1.21.1.2 driver: loaded: nvidia
    resolution: 2560x1440~144Hz
  OpenGL: renderer: NVIDIA GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 495.44


```

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim

**Comment by valacar** [comment]
Ah, I didn't see the FAQ... sorry. `let &t_ut=''` does indeed fix it. Thanks.
