### ISSUE TITLE
Using windows key in kitty_mod?

### ISSUE THREAD

**Issue by amca01** [kovidgoyal/kitty#4527]
On my Linux system, I already use ctrl+shift to move between virtual desktops, so I need another key combination for kitty.  I thought of using ctrl+windows, as the windows key is unused.  However, when testing the keys in kitty with

    kitty +kitten show_key -m kitty

the windows key doesn't register.  I've checked it with "showkey" and "xev" and its keycode is 125.  I've tried using "super" as recommended in the documentation, so having this in my config file:

    kitty_mod ctrl+super

but it doesn't work - and I expect for the reason I mentioned above - that the windows key for some reason is not recognized in kitty.  

Is there any way of using the windows key in the modifier?

**Comment by kovidgoyal** [comment]
I cannot reproduce with current kitty on Linux. Steps I tried

1) kitty --config=NONE kitty +kitten show_key -m kitty
2) Press the windows key
3) Observe output
```
Press any keys - Ctrl+C or Ctrl+D will terminate
LEFT_SUPER PRESS
CSI 57444 u

Super+LEFT_SUPER RELEASE
CSI 57444 ; 9 : 3 u
```
