### ISSUE TITLE
Kitty autocompletes automatically without me pressing Tab or right arrow

### ISSUE THREAD

**Issue by thatlittleboy** [kovidgoyal/kitty#4530]
**Describe the bug**
As title says. When using the mouse to click different windows and entering one letter (say, 'k'), it just accepts the autocomplete suggestion (say, 'kitty --config NONE' if that was the suggestion) without me pressing Tab or right arrow.

Note: I know there are keyboard shortcuts to switch windows, and I use those too, though sometimes I use the mouse / trackpad out of habit.

**To Reproduce**
1. Open kitty (reproducible on config NONE): `kitty --config NONE`
2. Cmd+Enter to open another window. (cursor jumps to the new window below).
3. Use your mouse to click the top window (the window the cursor is **not** on).
4. Immediately start typing ONE letter, say 'k'. (assuming there is autocomplete set up and there exists a command starting with k that the shell is autosuggesting).

Then, without me pressing any other keys, observe that kitty carries on with autocompleting on its own accord. If you were typing something else, say "kubectl", you would then get "kitty --config NONEubectl".

**Screenshots**
A gif of the steps described above:

![kapture](https://user-images.githubusercontent.com/30731072/149777105-a3be0c92-2a7a-4918-b64e-6fb26979708a.gif)

Please believe me when I say, I only entered "k" and "kubectl" respectively in the gif, and nothing else.

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Darwin xxx-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/zsh
Loaded config files:
  /Users/xxx/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell          False
font_family                Ubuntu Mono
font_size                  14.0
macos_show_window_title_in window
shell_integration          frozenset({'no-cursor'})
tab_bar_edge               1
tab_bar_margin_height      TabBarMarginHeight(outer=3.0, inner=2.0)
tab_bar_style              slant
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
I mentioned this before.

https://github.com/kovidgoyal/kitty/issues/4128

If you want to use the mouse click functionality that comes with shell integration, the current approach is to not enter text immediately after clicking.

**Comment by page-down** [comment]
It is also possible to turn on focus following the mouse, if that is acceptable to you.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.focus_follows_mouse

These are workarounds, to solve the root of the problem, we need the shell's line editor to support native cursor movement.

**Comment by thatlittleboy** [comment]
Thanks for the response and for providing workaround options. I'll take a look at them. Apologies for the duplicate.
