### ISSUE TITLE
Notification kitten similar to notifications on terminal bell

### ISSUE THREAD

**Issue by yar-fed** [kovidgoyal/kitty#4531]
**Is your feature request related to a problem? Please describe.**
I have a few minutes of build time. I use notify-send utility to get notification when it is finished. But then I noticed that there is a notification on bell for kitty that can additionally focus the window on click (in gnome at least).

**Describe the solution you'd like**
Is it possible to have the same notification as a kitten with ability to choose a message and severity?

**Describe alternatives you've considered**
I tried notify-send and kitty's bell notification.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/desktop-notifications/
