### ISSUE TITLE
Wildcard expansion in kitty.conf `include` doesn't work

### ISSUE THREAD

**Issue by glibg10b** [kovidgoyal/kitty#4533]
**Is your feature request related to a problem? Please describe.**
kitty.conf: `include kitty.d/**/*.conf` doesn't include anything. I'd like it to include all *.conf files under kitty.d and subdirectories recursively

**Describe the solution you'd like**
Parse globs just like bash does (`**` requires `shopt -s globstar` in bash)

**Additional context**
Relevant function: https://github.com/kovidgoyal/kitty/blob/f9a4b6bb0d3fb1da39cd489f7d6d6cfb47f6d352/kitty/conf/utils.py#L158

**Comment by page-down** [comment]
I think this needs a new configuration option.

Currently `include *.conf` loads the file `*.conf` correctly, and changing this would break backwards compatibility.

**Comment by kovidgoyal** [comment]
I dont see a need for this. You will need to explain your use case in
more detail.

**Comment by glibg10b** [comment]
@kovidgoyal Having one `include *.conf` that includes all .conf files in a directory is nice ([vim](https://gitlab.com/glibg10b/config/-/blob/main/vim/sysinit.vim#L10) and [zsh](https://gitlab.com/glibg10b/config/-/blob/main/zsh/zshrc#L1) allow it)

Having to do [this](https://gitlab.com/glibg10b/config/-/blob/main/kitty/kitty.conf) instead is annoying

**Comment by kovidgoyal** [comment]
My question was not why using a glob pattern is better than including individual files, it was why are you splitting your conf file into so many individual files. And in any case this is already implemented, see the commit that closed the issue.

**Comment by glibg10b** [comment]
It's just more organized this way: finding the settings I'm looking for is easier, and so is sharing or deleting e.g. only my color theme
