### ISSUE TITLE
Browse last cmd output doesn't always work

### ISSUE THREAD

**Issue by aryklein** [kovidgoyal/kitty#4536]
**Describe the bug**
`ctrl+shift+g` doesn't work as you describe in the documentation in Linux (Arch Linux). With some commands the pager is empty, for example with `ls`.

While `ctrl+shift+g` doesn't work for some command, `ctrl+shift+right-click` always works perfect.

**To Reproduce**
1. execute `ls` command
2. press `ctrl+shift+g`
3. See error

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux 4lcl6d3 5.16.1-arch1-1 #1 SMP PREEMPT Sun, 16 Jan 2022 11:39:23 +0000 x86_64
Arch Linux 5.16.1-arch1-1 (/dev/tty)

Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/ary/.config/kitty/kitty.conf

Config options different from defaults:
cursor_text_color       None
enable_audio_bell       False
enabled_layouts         ['splits:split_axis=horizontal']
font_family             DejaVuSansMono Nerd Font Mono
shell                   zsh
tab_activity_symbol     ❯ 
tab_bar_edge            1
tab_bar_style           powerline
url_style               1
window_padding_width    FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)
Added shortcuts:
	f1 launch --location=hsplit
	f2 launch --location=vsplit
	f3 layout_action rotate
	shift+left move_window left
	shift+right move_window right
	shift+up move_window up
	shift+down move_window down
	alt+h neighboring_window left
	alt+j neighboring_window down
	alt+k neighboring_window up
	alt+l neighboring_window right
	shift+alt+h resize_window narrower 3
	shift+alt+j resize_window shorter 3
	shift+alt+k resize_window taller 3
	shift+alt+l resize_window wider 3
Colors:
	active_tab_background   #f8f8f2   
	active_tab_foreground   #282a36   
	background              #282a36   
	color0                  #21222c   
	color1                  #ff5555   
	color10                 #69ff94   
	color11                 #ffffa5   
	color12                 #d6acff   
	color13                 #ff92df   
	color14                 #a4ffff   
	color2                  #50fa7b   
	color3                  #f1fa8c   
	color4                  #bd93f9   
	color5                  #ff79c6   
	color6                  #8be9fd   
	color7                  #f8f8f2   
	color8                  #6272a4   
	color9                  #ff6e6e   
	cursor                  #f8f8f2   
	foreground              #f8f8f2   
	inactive_tab_background #6272a4   
	inactive_tab_foreground #282a36   
	mark1_background        #ff5555   
	mark1_foreground        #282a36   
	selection_background    #44475a   
	selection_foreground    #ffffff   
	tab_bar_background      #444444   
	url_color               #8be9fd   

On older versions of kitty, run kitty --debug-config instead
```

**Comment by aryklein** [comment]
With an empty zshrc it works.
I will try to find what the problem is. I have also the same issue with bash

**Comment by aryklein** [comment]
This is my zshrc config file
https://github.com/aryklein/dotfiles/blob/main/zsh/.zshrc

**Comment by kovidgoyal** [comment]
Mos tlikely its powerlevel10k you need to update it and its config, see
the powerlevel10k readme.

**Comment by aryklein** [comment]
It seems to be powerlevel10k but it's up-to-date and I ran again the wizard without luck. Maybe this feature is not compatible with powerlevel10k.

**Comment by aryklein** [comment]
@kovidgoyal I checked and I'm running the latest version of pwelevel10k with a standard config created by the wizard. Any other idea?

**Comment by kovidgoyal** [comment]
You would need to ask the author of powerlevel10k. Ping @romkatv

**Comment by romkatv** [comment]
Cannot reproduce. My guess is that you aren't using the latest version of powerlevel10k. Since you are on Arch Linux, see https://github.com/romkatv/powerlevel10k#arch-linux.

For context: The built-in zsh shell integration in kitty doesn't work with all prompts. In particular, it doesn't work with powerlevel10k. Prior to the release of kitty 0.24.0 I've made two changes in powerlevel10k:

- When powerlevel10k detects that kitty is about to enable shell integration, it asks kitty to not do it (it wouldn't work anyway) and enables shell integration of its own.
- In addition, I added `POWERLEVEL9K_TERM_SHELL_INTEGRATION` parameter. If you set it to `true`, powerlevel10k will enable shell integration even when there is no indication that kitty is requesting it. This allows you to retain shell integration in subshells, in ssh, or when you start zsh from bash, or when you run `sudo zsh`, etc.

**Comment by aryklein** [comment]
Hey @romkatv, thanks for helping. I almost sure I'm using the latest version as I'm using the AUR package `zsh-theme-powerlevel10k-git`:

```
~ ❯ sudo pacman -Qm zsh-theme-powerlevel10k-git
zsh-theme-powerlevel10k-git r4000.3d994b0-1
```

You say that powerlevel10k doesn't support Kitty shell integration, but I see many integrations working fine, like `ctrl+shift` and right-click on any command output in the scrollback to view it in a pager, the cursor feature and the current working directory or the command being executed in the tab title. From my side the only feature that doesn't work is the output of the last command in a pager with `ctrl+shift+g`, but it's weird because some commands work and some don't. For example `find /` or `top` works fine.

Do you recommend to disable the Kitty shell integrations?

**Comment by romkatv** [comment]
> You say that powerlevel10k doesn't support Kitty shell integration

That's not what I wrote. It's almost the opposite.

> Do you recommend to disable the Kitty shell integrations?

I recommend to keep it -- it's very useful. Add `POWERLEVEL9K_TERM_SHELL_INTEGRATION =true` to `~/.p10k.zsh` so that you have integration all the time and not lose it when you restart zsh, etc.

**Comment by page-down** [comment]
Maybe you can start with a minimal configuration and make sure it works first.
For example, a brand new configuration with just zsh + kitty.
Then add your original configuration gradually.
You might be able to figure out what the problem is.

**Comment by romkatv** [comment]
> I don't manage this topic and I had understood that shell integration didn't work with powerlevel10k.

Integration between the shell and the terminal requires both parties to cooperate: both the terminal and the shell should have some code in it. Kitty has all necessary terminal-related code for this to work. It also can inject shell code into zsh. The latter is best effort and doesn't work with all zsh configs. In particular, it doesn't work with powerlevel10k. This isn't a problem because powerlevel10k has builtin code that does work.

**Comment by aryklein** [comment]
Fixed by @romkatv - https://github.com/romkatv/powerlevel10k/issues/1749
Thanks
