### ISSUE TITLE
"titlebar-only yes" breaks mouse gestures on MacOS for kitty windows only

### ISSUE THREAD

**Issue by zakrywilson** [kovidgoyal/kitty#4538]
**Describe the bug**
If `titlebar-only` is active, mouse gestures on my Logitec MX Master do not work for kitty windows.

**Setup**
- MacOS Monterey
- [Logitec MX Master 3 for Mac](https://www.logitech.com/en-us/products/mice/mx-master-3-mac-wireless-mouse.910-005693.html)
- Kitty (version 0.23.1)

**To Reproduce**
Steps to _not_ reproduce the behavior:
1. Launch Kitty with no config
2. See that you can open Mission Control with the mouse

1. Launch kitty with `titlebar-only yes`
2. Ensure kitty is selected (in the foreground)
2. Attempt to open Mission Control with the _up_ gesture on the Logitec mouse
4. See nothing happens (expected behavior is Mission Control opens)

**Logs**
[kitty-debug-input.log](https://github.com/kovidgoyal/kitty/files/7891070/kitty-debug-input.log)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin [redacted] 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Loaded config files:
  /Users/[redacted]/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height      2
allow_remote_control    y
font_family             SauceCodePro Nerd Font
font_size               16.0
hide_window_decorations 1
listen_on               unix:/tmp/mykitty
macos_option_as_alt     3
macos_thicken_font      0.6
window_padding_width    FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Removed shortcuts:
	shift+ctrl+- KeyAction('change_font_size', (True, '-', 2.0))
	shift+ctrl+= KeyAction('change_font_size', (True, '+', 2.0))
	shift+ctrl+enter KeyAction('new_window')
	shift+ctrl+backspace KeyAction('change_font_size', (True, None, 0.0))
Colors:
	# omitted for brevity 
```

**Additional context**
I first wrote this issue up because I wasn't able to get gestures to work. I then tried to reproduce with `kitty --config NONE` and noticed that it started working. Then I disabled what seems like a flag that isn't relevant to MacOS; however, it seems like a bug that it affects MacOS behavior.

**Comment by page-down** [comment]
Which keyboard shortcut does your mouse gesture bind to? Is it `ctrl+up`?

Try the following command to start kitty, try the gesture and see if there are keyboard events in the log.

```shell
kitty --config=NONE -o hide_window_decorations=titlebar-only --debug-input
```

You can also try the nightly version and see if the issue is solved.

**Comment by zakrywilson** [comment]
For which command the mouse is invoking, I'm not entirely sure – I would have to do some investigation. I can say that on my Mac, `Ctrl-Up` is the key command I use to open Mission Control. `Ctrl-Left` and `Ctrl-Right` were also broken and those commands switch between Mac "desktops."

I ran kitty with that config and used the mouse to try to open Mission Control, as well as switch desktops.

[kitty-config-NONE-titlebar-only.txt](https://github.com/kovidgoyal/kitty/files/7891419/kitty-config-NONE-titlebar-only.txt)

**Comment by page-down** [comment]
Can you set the keyboard shortcut to be pressed when the gesture is triggered in the mouse? Try binding to ctrl+up.

My guess is that the Logitech mouse driver directly invokes macOS system functions, yet something went wrong.
kitty just hides the title bar, sets the window style, and does nothing else special.

**Comment by zakrywilson** [comment]
That's interesting.

Okay, so I mapped the gesture button to `Ctrl-Up`, ran the command, and clicked the button a few times in the window. Hopefully, this is more helpful:

[kitty-log-3.log](https://github.com/kovidgoyal/kitty/files/7891552/kitty-log-3.log)

**Comment by kovidgoyal** [comment]
According to that log ctrl+up is being sent to the child, not intercepted by cocoa. Whatever hack the logitechmouse driver uses to inject that keyboard event into coca breaks when the titlebar is hidden. You should report it to logitech.
