### ISSUE TITLE
Set value update_check_interval to 0

### ISSUE THREAD

**Issue by D1sturbing** [kovidgoyal/kitty#4546]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when kitty makes network connection without my knowledge or consent

**Describe the solution you'd like**
change the value of the variable update_check_interview to 0

**Describe alternatives you've considered**
Switching to a terminal emulator that doesn't have surveillance features enabled by default.

edit: removing the example text i accidentally left in the issue report

**Comment by kovidgoyal** [comment]
Dont waste my time opening duplicate issues.

**Comment by Luflosi** [comment]
See #1342.

**Comment by Luflosi** [comment]
Also #3385.

**Comment by dmhowcroft** [comment]
I arrived here because I was also very surprised by the automatic check for updates implemented in kitty. I generally enjoy using kitty, but I don't understand why my terminal needs to phone home every time I launch it. Shouldn't this be opt-in the first time we run kitty?
