### ISSUE TITLE
Entering vi-mode in Fish add a new line

### ISSUE THREAD

**Issue by angelus2014** [kovidgoyal/kitty#4553]
**Describe the bug**
When I enter (or exit) the vi-mode in Fish, Kitty always adds a new line. It doesn't matter if it's a multiline or single line prompt. I don't see this behaviour in other terminals on my Mac (iTerm, Alacritty).

**To Reproduce**
1. Install Fish and start this shell (or in my case, make it the default)
2. Start typing a command
3. Press ESC to enter (or leave) the vi-mode
4. Kitty prints a new line
<img width="152" alt="Screenshot 2022-01-23 at 9 15 40" src="https://user-images.githubusercontent.com/7578963/150668535-42a00890-5e5a-4996-b897-d6e74beac639.png">
<img width="151" alt="Screenshot 2022-01-23 at 9 15 47" src="https://user-images.githubusercontent.com/7578963/150668537-8c0c9df6-1566-4b0e-b56e-1ebe4943b38b.png">

**Environment details**
kitty 0.24.1 created by Kovid Goyal
Darwin orac.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
ProductName:    macOS ProductVersion:   12.1 BuildVersion:      21C52
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/angelo/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style   (True, False)
bold_font               MesloLGSDZ Nerd Font Mono Bold
enable_audio_bell       False
font_family             MesloLGSDZ Nerd Font Mono Regular
font_size               13.0
inactive_tab_font_style (True, False)
macos_option_as_alt     2
macos_thicken_font      0.25
macos_titlebar_color    370548226
selection_foreground    None
shell                   /opt/homebrew/bin/fish --login
tab_fade                (1.0,)
window_alert_on_bell    False
window_padding_width    FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Colors:
        active_border_color     #3d59a1   
        active_tab_background   #16161e   
        active_tab_foreground   #3d59a1   
        background              #1a1b26   
        bell_border_color       #e0af68   
        color0                  #414868   
        color1                  #f7768e   
        color10                 #73daca   
        color11                 #e0af68   
        color12                 #7aa2f7   
        color13                 #bb9af7   
        color14                 #7dcfff   
        color15                 #c0caf5   
        color2                  #73daca   
        color3                  #e0af68   
        color4                  #7aa2f7   
        color5                  #bb9af7   
        color6                  #7dcfff   
        color7                  #c0caf5   
        color8                  #414868   
        color9                  #f7768e   
        cursor                  #c0caf5   
        cursor_text_color       #1a1b26   
        foreground              #a9b1d6   
        inactive_border_color   #101014   
        inactive_tab_background #16161e   
        inactive_tab_foreground #787c99   
        selection_background    #28344a   
        tab_bar_background      #101014   
        url_color               #9ece6a   

**Additional context**
> Try to reproduce the problem with `kitty --config NONE` 

It also happens in this scenario.

---
With regards,

Angelo Machils

**Comment by kovidgoyal** [comment]
dup of #4508

**Comment by angelus2014** [comment]
That one is closed without any solution... When will this be fixed?


---
With regards,

Angelo Machils

**Comment by kovidgoyal** [comment]
When it is fixed in starship.

**Comment by angelus2014** [comment]
It also happens in other prompt (Pure for example and Tide). And as I said, it doesn't happen in other terminals.

**Comment by kovidgoyal** [comment]
They presumably all copied the same broken code from each other.
I suggest you decide which is more important to you, a prompt or shell
integration. If the former add 

shell_integration disabled

to kitty.conf

if the latter, find a non-broken prompt fish function.

**Comment by angelus2014** [comment]
So, your reasoning is that even though (at least) 3 other terminals don't show this issue *and* it happens with multiple, totally different prompts (from the very simple Pure to the elaborate Tide), it's the prompt(s) that are broken?!

Oh yes `shell_integration disabled` doesn't help.

Thank you.

**Comment by kovidgoyal** [comment]
Ah you arent talking about shell integration. In that case the dup is not #4508 it is https://github.com/starship/starship/issues/1271 and https://github.com/fish-shell/fish-shell/issues/3481
