### ISSUE TITLE
Wrong interaction of mouse clicks while using the Tilde editor in Kitty

### ISSUE THREAD

**Issue by ryanrms** [kovidgoyal/kitty#4557]
**Describe the bug**
Instead of allowing you to select text or click the ncurses menus in the Tilde editor (https://github.com/gphalkes/tilde), when using Kitty the mouse actions lead to garbage printed in the editor.  Clicking and releasing the left mouse button inserts ` f'#f'`, the right mouse button `"I+#I+` but these values seem to be affected by where you click inside the terminal.   Other terminal applications that use the mouse appear to be fine, such as weechat (clicking buffers switches to them).  GNOME Terminal doesn't exhibit this issue with the Tilde editor.

**To Reproduce**
1. Install kitty, I tried the version included in Ubuntu 21.10 and the one from the website
2. Install tilde, which is included as a package on Debian and Ubuntu (can be more difficult to install on other distros)
3. Run tilde, click anywhere.  

**Screenshots**
![Screenshot from 2022-01-23 17-19-34](https://user-images.githubusercontent.com/2936638/150704291-6a0d8e14-9bbc-47c5-8add-6efb5d2726b1.png)
Screenshot showing some of the garbage inserted into the file from clicking around.

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux mumei 5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64
Ubuntu 21.10 mumei /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
Running under:Wayland
Frozen: True
Paths:
  kitty: /home/rdr/.local/kitty.app/bin/kitty
  base dir: /home/rdr/.local/kitty.app/lib/kitty
  extensions dir: /home/rdr/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0

```

**Additional context**
I removed (well, moved) my config file and the issue persists.  Could be a quirk of the editor but it seems to work fine in GNOME Terminal (and related VTE terminal emulators) and Konsole, these are the ones I've tried besides kitty.

**Comment by kovidgoyal** [comment]
This will be a bug in tilde, most likely that it is not handling the SGR
mouse reporting protocol.
