### ISSUE TITLE
cursor_shape not working after 0.24.1 update

### ISSUE THREAD

**Issue by henrikstroem** [kovidgoyal/kitty#4560]
**Describe the bug**
After updating to version 0.24.1 via homebrew the cursor is displayed as a beam cursor even when configured to show block:

`cursor_shape block`

Same problem on two Apple Mac.
![Screenshot 2022-01-25 at 15 24 07](https://user-images.githubusercontent.com/907338/150995946-5546ed9f-71c7-4e37-b162-7144432c639d.png)

**To Reproduce**
1. Run `brew upgrade` on macOS 10.12.1
2. Open kitty
3. See error

**Screenshots**

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Darwin minime.lan 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/henrik/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.888888885
cursor_blink_interval   0.0
enable_audio_bell       False
font_size               20.0
hide_window_decorations 1
mouse_hide_wait         1.0
window_padding_width    FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Colors:
	cursor                  #ff8c00   
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

This displays a white beam cursor.

**Comment by Luflosi** [comment]
See https://github.com/kovidgoyal/kitty/issues/4438#issuecomment-1005200809.

**Comment by kovidgoyal** [comment]
Read https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape
