### ISSUE TITLE
Can't erase what i writed in kitty only if i'm connected to SSH

### ISSUE THREAD

**Issue by DARKBOW923** [kovidgoyal/kitty#4561]
**Describe the bug**
Can't erase anything writed in the terminal via SSH

**To Reproduce**
1. Open Kitty
2. Login into another machine via SSH
3. Write something and try to erase it using the return button.
4. You will see you can't erase, instead of, it makes the effect of the spacebar.

**Screenshots**
![image](https://user-images.githubusercontent.com/59940188/151007887-c1def363-a324-4cea-b685-c7f38fcd5c97.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

kitty 0.23.1 created by Kovid Goyal
Linux gentoo 5.15.10-gentoo-dist #1 SMP Fri Dec 17 13:05:30 -00 2021 x86_64
This is \n.\O (\s \m \r) \t
Running under:X11

Config options different from defaults:

None.

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
you need to install the kitty terminfo files on the remote machine. https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by DARKBOW923** [comment]
> you need to install the kitty terminfo files on the remote machine. https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

I've just tried it right now, the problem persist.

**Comment by DARKBOW923** [comment]
> you need to install the kitty terminfo files on the remote machine. https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

I did what you suggested me, however the problem persist.

Also, i readed the su or sudo part regarding the backspace, home, etc.. it doesn't work too.

**Comment by page-down** [comment]
Did you get your kitty terminfo file installed?

```shell
# kitty 0.23.1
curl -o $HOME/.terminfo/x/xterm-kitty --create-dirs -fSL https://github.com/kovidgoyal/kitty/raw/v0.23.1/terminfo/x/xterm-kitty
```

Disconnect SSH and reconnect. Try again to confirm that it works properly.

sudo
```shell
sudo mv $HOME/.terminfo/x/xterm-kitty /usr/share/terminfo/x/xterm-kitty
exit
```

If you upgrade to 0.24, you need to update it again.
