### ISSUE TITLE
Font rendering is ugly on external display on Mac

### ISSUE THREAD

**Issue by jseppanen** [kovidgoyal/kitty#4564]
**Describe the bug**
The font rendering looks different on the laptop screen and on an external monitor, see attached screenshots. The rendering on the external display looks ugly/jagged.

**To Reproduce**
1. run `kitty --config NONE` and print some text
2. move kitty window to laptop screen => rendering is OK
3. move kitty window to external monitor => rendering is ugly

**Screenshots**
photo of MacBook Air laptop screen (taking a screenshot actually ended up being jagged as well):

![laptop_screen](https://user-images.githubusercontent.com/83203/151163029-38a06fef-218b-4220-b843-856c51c947ae.jpg)

screenshot from Dell external monitor:

![external_monitor](https://user-images.githubusercontent.com/83203/151161080-429eaada-d258-4f27-b632-326f5c13c1ac.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin sp4753 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:05 PST 2021; root:xnu-7195.141.14~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	11.6.2 BuildVersion:	20G314

Config options different from defaults:

```

**Additional context**
I'm using a MacBook Air M1 with MacOS 11.6.2 and a Dell U3818DW external monitor

Edit: forgot to mention that other programs like Terminal or VS Code look the same on both screens

**Comment by kovidgoyal** [comment]
I am guessing your external monitor is low DPI. kitty doesnt do subpixel anti alias which you need for low DPI displays. I'ma fraid I have no interest in support subpixel AA, for reasons discussed elsewhere.

**Comment by jseppanen** [comment]
cool, thanks for your answer! Yeah this one has old pixels

**Comment by page-down** [comment]
I remember that Apple abandoned sub-pixel rendering long ago.

related to this discussion
https://github.com/kovidgoyal/kitty/discussions/4485

You can use the following options to thicken the font. 
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_thicken_font

The fonts rendered by kitty at HiDPI are still not "strong" enough. I don't know if it can be fine-tuned a bit more.
