### ISSUE TITLE
My own config is merged with default one even though it shouldn't

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#457]
`kitty -h` says this:

> --config=CONFIG
>   Specify a path to the configuration file(s) to use. Can be specified
>   multiple times to read multiple configuration files in sequence, which
>   are merged.  Use the special value NONE to not load a config file.
>   
>    If this option is not specified, config files are searched for in the
>   order: "$XDG_CONFIG_HOME/kitty/kitty.conf",
>   "~/.config/kitty/kitty.conf", "$XDG_CONFIG_DIRS/kitty/kitty.conf". The
>   first one that exists is used as the config file.
>   
>   If the environment variable "KITTY_CONFIG_DIRECTORY" is specified,
>   that directory is always used and the above searching does not happen.
>   
>   **If "/etc/xdg/kitty/kitty.conf" exists it is used as a base config file
>   onto which any user config files are merged.**

Which is exactly the behavior that I want! However, it doesn't seem to work like that, or I'm confused somewhere.

Since the configs merge happens only happens if `/etc/xdg/kitty/kitty.conf` exists, I make sure it doesn't:

```
❯ stat /etc/xdg/kitty/kitty.conf
stat: cannot stat '/etc/xdg/kitty/kitty.conf': No such file or directory
```

I have my own config in `~/.config/kitty/kitty.conf`, I expect that only things defined in this config are used. However, defaults still seem to come from somewhere else.

For example, a recent addition is this binding:

```
map ctrl+shift+p>f       run_kitten text hints --type path --program -
```

I **don't** have it in my `~/.config/kitty/kitty.conf`, and yet kitty still has it!

I know of the existence of `no_op`, however that way 70% of my config consists of `no_op` if I choose this approach, and also I'm forced to constantly monitor new mappings and disable them again.

Instead, I'd like kitty to only load the bindings from my own config, as described in `kitty -h`. So that I can keep my config minimal and don't be surprised by new mappings.

I tried `kitty --config ~/.config/kitty/kitty.conf`, and this binding is still there.

----

If `kitty -h` is outdated and the observed behavior is the desired one, can we at least have a way to override it? Maybe a `--nodefault` option to kitty?

**Comment by kovidgoyal** [comment]
No the defaults are always loaded. The order is:

defaults
/etc
one or more user config files.


I dont understand what the problem with the default mapping is. You cannot use ctrl+shift in terminal programs anyway, so if you dont want to use them there is no need to no-op them, just ignore them. Similarly, if any new bindings come along, you can ignore them.

**Comment by maximbaz** [comment]
Then I suggest at least adding this info to the `kitty -h` to keep the docs consistent. It's a bit unusual behavior, but I can live with it.

**Comment by maximbaz** [comment]
The problem with always loading default mappings is that when I add this to my `~/.config/kitty/kitty.conf`:

```
map ctrl+shift+l>u>o      run_kitten text hints --type url
```

It doesn't work, because there is a default mapping `ctrl+shift+l`. So I have to add `map ctrl+shift+l no_op` as well to make the above mapping work.

If only my config was respected, I would not had to hunt for default mappings for `ctrl+shift+l`. Or if kitty could detect that I defined `ctrl+shift+l>...` mapping and thus not load the default `ctrl+shift+l` one. Continuing this train of thought, if I add a `ctrl+shift+r>a` mapping today, and tomorrow you introduce a new default mapping `ctrl+shift+r`, things will mysteriously break for me, until I find out that a new default mapping was introduced that I have to `no_op`.
