### ISSUE TITLE
Copy to local clipboard without remote X11

### ISSUE THREAD

**Issue by joshvoigts** [kovidgoyal/kitty#4570]
tmux is able to copy arbitrary regions of the screen with ctrl+b, ]. This is helpful when using vim on a headless remote server without x11. kitty's normal copy/paste operations don't work in this scenario inside of vim.

It would be helpful in this scenario to have a "raw copy" mode to be able to copy arbitrary regions of the window bypassing vim's selection. In macos terminal, this used to be possible by holding the option key while dragging. Either that or there might be a way to communicate with the system clipboard despite missing the X clipboard?

**Comment by page-down** [comment]
> ... to be able to copy arbitrary regions of the window bypassing vim's selection ...

https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Start-selecting-text-even-when-grabbed

With the default configuration, shift+drag, you can select any text that is on the screen.

I don't know if the region you are talking about is to select the block range.

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Start-selecting-text-in-a-rectangle

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/overview/#mouse-features
