### ISSUE TITLE
unwanted automatic suggestion completion

### ISSUE THREAD

**Issue by eoli3n** [kovidgoyal/kitty#4574]
**Describe the bug**
```bash
➜ kitty --version
kitty 0.24.1 created by Kovid Goyal

➜ fish --version
fish, version 3.3.1
```
Since the last upgrade, when I start typing a command, the suggestion auto complete before I end to type my command, without using "->" key. The bug is random, can't reproduce at each command.

**To Reproduce**
1. Start typing "cl"
2. It auto-complete the "clear" suggestion, but you're still typing
3. Ending with the command "clearear"

**Screenshots**

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux osz 5.15.16_1 #1 SMP Thu Jan 20 17:19:29 UTC 2022 x86_64
Void 5.15.16_1 (osz) (/dev/tty)

Running under:Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.9
cursor_shape            2
enable_audio_bell       False
font_family             jetbrains mono
font_size               10.0
open_url_with           ['firefox']
scrollback_lines        10000
shell_integration       frozenset({'no-cursor'})
touch_scroll_multiplier 5.0
window_padding_width    FloatEdges(left=10.0, top=5.0, right=10.0, bottom=5.0)
Added shortcuts:
	ctrl+up change_font_size current +1.0
	ctrl+down change_font_size current -1.0
Colors:
	background              #202020   
	color0                  #282a36   
	color1                  #ff5c57   
	color10                 #5af78e   
	color11                 #f3f99d   
	color12                 #57c7ff   
	color13                 #ff6ac1   
	color14                 #9aedfe   
	color15                 #f1f1f0   
	color2                  #5af78e   
	color3                  #f3f99d   
	color4                  #57c7ff   
	color5                  #ff6ac1   
	color6                  #9aedfe   
	color7                  #eff0eb   
	color8                  #686868   
	color9                  #ff5c57   

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

The bug is random, hard to reproduce, it occurs 1/20 maybe, less sometimes.

**Comment by page-down** [comment]
Do you open a new window, click the mouse to switch focus, and then type immediately?

https://github.com/kovidgoyal/kitty/issues/4530

The mouse-click positioning cursor feature in shell integration is implemented by emulating the left and right keys. You can avoid this issue by not typing commands immediately, or by adjusting the mouse click interval.

**Comment by eoli3n** [comment]
> You can avoid this issue by not typing commands immediately
Is that a serious workaround ?

I tried with 
```
click_interval -1.0
```
But I still get the issue. How to configure kitty to work as before the upgrade breaks it ?

**Comment by kovidgoyal** [comment]
Add

shell_integration disabled

to kitty.conf
