### ISSUE TITLE
ctrl+tab and ctrl+shift+tab doesn't work after upgrade to macOS Monterey 12.2

### ISSUE THREAD

**Issue by zachy-ho** [kovidgoyal/kitty#4578]
**Describe the bug**
`ctrl+tab` and `ctrl+shift+tab` doesn't work for next_tab and previous_tab respectively anymore. I think it might be after I upgraded to macOS Monterey 12.2 (was working fine in 12.1 and before).

Tried running with `kitty --config NONE`, and it works for some reason Also reassigned next_tab and previous_tab to something like `ctrl+i` and `ctrl+shift+i` and those work fine. I don't think I have a complex config but here's mine https://github.com/zachy-ho/dotfiles/tree/master/kitty

I wonder if it's related to https://github.com/kovidgoyal/kitty/issues/801.

**Environment details**
cmd+option+comma doesn't work, neither does `kitty --debug-config` :(

**Comment by kovidgoyal** [comment]
Works fine for me on monterey 12.2. If it works with --config=NONE then its something in your config file. comment out sections of it till you find the culprit.

**Comment by page-down** [comment]
With macOS 12.2, kitty 0.24.1, the following configuration will not switch tabs.

```shell
kitty --config=NONE --debug-input -o clear_all_shortcuts=yes -o 'map ctrl+tab next_tab' 
```

Recently, many improvements have been made to macOS keyboard event handling, and this issue could not be reproduced in the master branch.

You can use the nightly release, which will work fine.

**Comment by zachy-ho** [comment]
@page-down Yeah I don't know why I set `clear_all_shortcuts` to yes. Thanks for the tip!

> The last one will be used as a shortcut to the menu

I'm not sure what you mean by 'menu' here though.

**Comment by page-down** [comment]
> I don't know why I set clear_all_shortcuts to yes ...

Yes, if you remove this item, then it will also work fine.

> I'm not sure what you mean by 'menu' here though.

- At the very top of macOS is the menu bar.
- The shortcut to a menu item is defined by the last shortcut key of the corresponding action in the configuration.
- When you write a configuration `map ctrl+tab next_tab`, it will actually try to execute the menu item `next tab` when the shortcut is pressed, however it doesn't seem to work.
- This issue has been resolved in the master branch.
