### ISSUE TITLE
Rendering issue after resize

### ISSUE THREAD

**Issue by TJohnW** [kovidgoyal/kitty#458]
I noticed some strange behavior if Kitty is resized while it doesn't have focus. The sizes at which this occur are seemingly random 😕, but it happens consistently while resizing smaller and on the left side of the screen.

I'm running from master and on OSX 10.13.4

Also, the program I am using to resize is the window manager https://github.com/koekeishiya/chunkwm

![kittyresize](https://user-images.githubusercontent.com/836609/38692255-347d9a44-3e51-11e8-8412-e32a844dfe54.gif)

**Comment by kovidgoyal** [comment]
I cannot reproduce (albeit on linux, though the window refresh code is the same), does this happen if you run kitty with the default config? 

kitty --config NONE

And @koekeishiya might be interested since it involves chunkwm

**Comment by TJohnW** [comment]
Default config is the same. I also tried on a different laptop running OSX 10.12 and recreated the problem using Hammerspoon instead of chunkwm to resize kitty while it didn't have focus.

![hammerspoon](https://user-images.githubusercontent.com/836609/38715929-1da2c00a-3eac-11e8-9820-d8c376abf248.gif)

Hammerspoon script used:
```
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "R", function()
  hs.grid.resizeWindowThinner(hs.appfinder.windowFromWindowTitle("kitty"))
end)
```

**Comment by TJohnW** [comment]
I looked into it a little, [these quick changes](https://github.com/TJohnW/kitty/commit/cfef8d7e9d329e4656d883c4a68f0ebe20a19ca9) changes seem to fix it for me locally. Not entirely sure whats going on but from a quick glance: it seems like the glfw wait timeout is being set to -1 when focus is lost. Then the resize flags / `RESIZE_DEBOUNCE_TIME` is effectively ignored.

**Comment by kovidgoyal** [comment]
See if this fixes it. I cannot reproduce, so I cannot test
```diff
diff --git a/kitty/child-monitor.c b/kitty/child-monitor.c
index a43bd542..9a2a1f89 100644
--- a/kitty/child-monitor.c
+++ b/kitty/child-monitor.c
@@ -726,8 +726,10 @@ process_pending_resizes(double now) {
     for (size_t i = 0; i < global_state.num_os_windows; i++) {
         OSWindow *w = global_state.os_windows + i;
         if (w->has_pending_resizes) {
-            if (now - w->last_resize_event_at >= RESIZE_DEBOUNCE_TIME) update_os_window_viewport(w, true);
-            else {
+            if (now - w->last_resize_event_at >= RESIZE_DEBOUNCE_TIME) {
+                update_os_window_viewport(w, true);
+                set_maximum_wait(0);
+            } else {
                 global_state.has_pending_resizes = true;
                 set_maximum_wait(RESIZE_DEBOUNCE_TIME - now + w->last_resize_event_at);
             }
```

**Comment by kovidgoyal** [comment]
That would imply there's a bug in glfw, the main loop is definitely supposed to tick when events are delivered, the resize event being one type of event. You can test that by looking in glfw/cocoa_window.m

See the function _glfwPlatformWaitEvents(void)

This si what is called when there is a timeout of -1. See if that is indeed where it is hanging. 

Also, see if this commit helps: https://github.com/kovidgoyal/kitty/commit/612fb3b59666ec8b550357bd52c6e1949bfc8d04

**Comment by kovidgoyal** [comment]
Oh and to answer your question, yes I do see a timeout of -1 when kitty is unfocused. But the main_loop wakes up for me when I trigger the hammerspoon resize event.

**Comment by kovidgoyal** [comment]
See https://github.com/tomaka/winit/issues/219#issuecomment-315830359 and https://stackoverflow.com/questions/30410998/cocoa-event-loop-blocks-while-tracking-a-menu

apparently cocoa sometimes spins up sub-loops in sendEvent, which can prevent it from returning. That is presumably what is happening in your case. I have no idea why it happens for you only. Presumably some systemwide setting/addon? 

Anyway I dont see any way to fix this. Cocoa and glfw have fundamentally mismatched APIs. glfw expects to be able to poll for events and return. cocoa expects to be in control of the event loop.

**Comment by kovidgoyal** [comment]
Since posting an empty event in the resize callback seems to cause the sub-loop to quit for you, I suppose we can use that as a hacky work-around.

**Comment by TJohnW** [comment]
Okay cool, that fix works fine for me on both laptops. Thanks for the help 👍
