### ISSUE TITLE
kitty as linux console terminal

### ISSUE THREAD

**Issue by dagbdagb** [kovidgoyal/kitty#4580]
**Is your feature request related to a problem? Please describe.**
More a 'long-term idea' than an actual request. But would like to ask anyway:    What would it take to have kitty run on the bare linux console? Either as an application or as a getty replacement.

**Describe the solution you'd like**
Being able to run kitty on the bare console and split and reorganize the console as with a terminal window under x11/wayland. Preferably with the same config file and hotkeys.

**Describe alternatives you've considered**
I have considered screen/tmux. And it is *possible* these can be reconfigured for the same keyboard hotkeys as kitty. Haven't really tried yet. https://ianthehenry.com/posts/how-to-configure-tmux/.   

**Additional context**
 I understand glfw is a prerequisite for kitty. 
[directfb2]( https://directfb2.github.io/) is underway, permitting OpenGL.
Is it naiive to think that this could be a target for glfw, and thus allow for kitty on the bare linux console?

**Comment by kovidgoyal** [comment]
No idea, I've never looked into the state of opengl on the linux
console. Assuming you can get opengl 3.3 and key and mouse input, there
is no reason you can write a glfw backend for it. If you do that, then
in theory kitty should work with relatively little effort. 

But let me be clear, *I* have no interest in doing this work personally.
Given such a glfw backend I will be happy to assist in the effort to get
kitty to use it.
