### ISSUE TITLE
Crashes with ctrl-shift+click and xonsh shell

### ISSUE THREAD

**Issue by Techcable** [kovidgoyal/kitty#4582]
**Describe the bug**
Hi! My kitty terminal crashes if I use `ctrl`+`shift` + click to try and view the output of anything but the last command.

Thing is:
1. I use a custom shell ([xonsh](https://xon.sh)) that's kind of in beta (although we have many users)
2. have a third-party plugin for kitty support [xontrib-term-intergrations](https://github.com/jnoortheen/xontrib-term-integrations) by @jnoortheen

Sometimes, 

**To Reproduce**
1. Clone the latest dev version of xonsh with `git clone https://github.com/xonsh/xonsh.git` 
    - NOTE: The latest release (`0.11.0`) doesn't work with the term integration plugin
2. Install `xontrib-term-integrations` with `pip install xontrib-term-integrations`
   - Edit your `~/.xonshrc` to add one line: `xontrib load term_integration`
   - Alternatively, you can copy [my `.xonshrc`](https://raw.githubusercontent.com/Techcable/dotfiles/master/.xonshrc)
3. Run at least two commands, each with their own output.
4. Try and `ctrl`+`shift`+click on the output of the second to the last command
   - NOTE: `ctrl`+`shift`+`g` works fine though

This bug seems extremely intermittent, but I was able to reproduce it 3 times.

It happens mostly when using colored output (specifically from `clang` and `git status`).

The first two times (`crash1.txt` and `crash2.txt`) I was using a custom wrapper process ([wrap-shell](https://github.com/Techcable/wrap-shell)) that runs `xonsh` as a subprocess with `fork`+`exec`

I have ruled that out, because it happened a third time without it.

However the third time it crashed (`crash3.txt`) *I was running xonsh directly*. This means that wrap-shell/`fork` is *not* the problem although the `fork`+`exec` may have exacerbated things.

As an aside, when I run kitty as a subprocess (with xonsh) I see
```
027 20:43:05.886534] [PARSE ERROR] Unknown OSC code: 1337
[027 20:43:05.886550] [PARSE ERROR] Unknown OSC code: 1337
```
In the output of kitty.

When I try to spawn kitty as a subprocess

**Environment details**
Here is a gist with my output of the kitty debug info and the MacOS crash report:

https://gist.github.com/Techcable/f8ea1f62ecdf94068d3bac4500df0560

**Additional context**
I have not yet been able to reproduce the "minimal" l kitty config to run into this issue. Same with the "minimal" `~/.xonshrc` (I want my themes 😆 ).

However, here is a [diff](https://gist.github.com/Techcable/cd50b4234ed22f0f08c1c39de5061790) between my kitty config and the default one.

Here is a link to [my current `kitty.config`](https://github.com/Techcable/dotfiles/blob/cfe9dd597b9d54e66381588b236bbb4da22c71cd/.config/kitty/kitty.conf) and a link to [my current `~/.xonshrc`](https://github.com/Techcable/dotfiles/blob/cfe9dd597b9d54e66381588b236bbb4da22c71cd/.xonshrc)

I will tell you if I'm able to reproduce this bug with anything more minimal.

To be clear my (old) `wrap-shell` script isn't the problem, because I have since disabled it (see my diff) and I still get the crashes (`crash3.txt` specifically) 😦 

This is one sort of bizzare three-way interaction between kitty + [xonsh](https://github.com/xonsh/xonsh) + @jnoortheen 's [xontrib-term-integration](https://github.com/jnoortheen/xontrib-term-integrations).

**Comment by Techcable** [comment]
Crash report \#4 with `ctrl`+`shift`+click, also *without* wrap-shell: https://gist.github.com/Techcable/1c83915d0423ac9e52508d2c5d724aa1

**Comment by kovidgoyal** [comment]
Build kitty with ASAN
make asan
see https://sw.kovidgoyal.net/kitty/build/
and post the backtrace after getting it to crash

**Comment by page-down** [comment]
You can also try the nightly release to see if it still reproduces your problem easily.

I have recently resolved a crash issue for getting command output.

**Comment by page-down** [comment]
@kovidgoyal 

```c
PyObject* as_text_generic(PyObject *args, void *container, get_line_func get_line, index_type lines, ANSIBuf *ansibuf);
```

Crashes when the `container` bounds are exceeded (requested number of `lines`). If I recall correctly.

I make sure the number of requested lines is correct, but didn't touch this.

**Comment by kovidgoyal** [comment]
@page-down not sure I understand, its the responsibility of get_line and lines to iterate over the lines, not as_text_generic. That is the caller has to ensure get_line() returns a valid line pointer from 0 to lines-1. Are you saying you want as_text_generic to check the return value of get_line and abort if NULL?

**Comment by page-down** [comment]
> ... its the responsibility of get_line and lines to iterate over the lines ...
> That is the caller has to ensure get_line() returns a valid line pointer from 0 to lines-1. ...

Yes, that's why I don't think I should touch as_text_generic.

I just wondered if there is a need for a final check somewhere, and obviously there is no need for that, and there is no such place.

**Comment by Techcable** [comment]
I've already compiled the v0.24.1 release with address sanitizer and I'm using it right now. I should be able to get a more detailed report by tomorro. 😄 

It's very possible this is a xonsh specific issue. My guess would be that kitty is encountering escape codes that the other shells aren't sending, and it's triggering some sort of rare corner-case in the code ;)


@page-down 
> You can also try the nightly release to see if it still reproduces your problem easily.

After I reproduce the bug in address sanitizer, I'll try nightly next to see if that fixes the problem :)

**Comment by Techcable** [comment]
@kovidgoyal 
I reproduced the crash with Address Sanitizer 😄 

https://gist.github.com/Techcable/84ef90e0082f83a6415e2d0bdb6344cf

Let me know if there's anything else you need :)

**Comment by kovidgoyal** [comment]
dup of #4430

**Comment by Techcable** [comment]
Yes. Looks like it. I will try latest nightly + address sanitizer and see if it reproduces again 😄
