### ISSUE TITLE
Clipboard or kitty-buffer macros

### ISSUE THREAD

**Issue by codemedic** [kovidgoyal/kitty#4588]
**Is your feature request related to a problem? Please describe.**

I am originally a konsole user and obviously comes with a baggage! One of the very handy features in konsole I loved was the ability to select something on the terminal and then hit keyboard shortcut search, which would pre-populate the search popup and also start highlighting the occurrences of the text.

I know that is quite a niche feature WRT what kitty offers. I think with a little extra magic, [kitty marks](https://sw.kovidgoyal.net/kitty/marks/) can be improved to achieve the same, along with much more.

**Describe the solution you'd like**

If you could add a way to access primary / selection, the clipboard and kitty buffers via some sort of macro `${primary_clipboard}`, `${clipboard}`, `${kitty_buffer:1}`, etc then this can be combined with kitty marks.

This feature can go even further; for example opening `vim` from the output of a `grep` where user selects the file path and hits a keyboard shortcut, which triggers a new kitty tab or window with `vim path/to/file`.

**Describe alternatives you've considered**

An alternative I considered was to use `pyperclip` or something similar to kick off a python script; but I am a newbie when it comes to python.

**Additional context**

None

**Comment by kovidgoyal** [comment]
You can do this (and much more) already. Simply use the kitty feature to
browse the scrollback in a program of your choice. You can pass the
selection to that program as a command line argument. See
https://sw.kovidgoyal.net/kitty/launch/ and https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer

**Comment by codemedic** [comment]
Thanks @kovidgoyal; those are great options; learn something new about kitty everyday!

I might not have explained my use case well.

I tend to "tail" logs from backend services, waiting for a specific pattern to appear. Being able to load the scrollback buffer into something like `less` is very useful, but that would mean that I will have to load the scrollback every often to search for something. If it was possible to pass the current selection to `create_marker` or `toggle_marker`, then it makes it possible to search / highlight pattern live as they happen.

**Comment by kovidgoyal** [comment]
I dont see how that would work. If you are tailing a log, presumably it is scrolling continuously, so you would anyway need to pause to select things. So whats the problem with presing ctrl+shift+h and then browsing the log?

**Comment by codemedic** [comment]
May be it is just the way I use it. I will give that usage pattern a try and see how I get on.
