### ISSUE TITLE
shift+left click selection

### ISSUE THREAD

**Issue by horseinthesky** [kovidgoyal/kitty#4589]
**Is your feature request related to a problem? Please describe.**
I'm new for kitty so maybe I just can't find in the docs But if it is possible to select lagre (like 30 pages of text for instanse) output with SHIFT+left click as it is possible in pretty much any other terminal app?

**Describe the solution you'd like**
Select any number of symbols with mouse SHIFT+left click of a mouse selects text from already selected to the click position.

**Describe alternatives you've considered**
ouldn't find any.

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/overview/#mouse-features

First use the left button to select a part, then scroll to the corresponding position and click the right mouse button.

You can use the right button to move  ( extend to ) the start position or the end position.

For related config, please refer to `mouse_map` `extend`.

**Comment by horseinthesky** [comment]
> First use the left button to select a part, then scroll to the corresponding position and click the right mouse button.

That's it. Thank you. Is it possible to remap the extention to the left click?

**Comment by page-down** [comment]
> Is it possible to remap the extention to the left click?

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Extend-the-current-selection

See the default config and the docs, and then try your own preferred key combinations.

**Comment by horseinthesky** [comment]
@page-down Will play with it to find the most comfortable behavior. Thanks again.
