### ISSUE TITLE
XIM input method support.

### ISSUE THREAD

**Issue by crocket** [kovidgoyal/kitty#459]
I use ibus-anthy for japanese input. The ibus input area is shown at the bottom left corner.
When I press enter in ibus input area, `Enter` is sent to both ibus and kitty.
As a result, kitty receives `Enter` before ibus sends its text to kitty.

![kitty-ibus-01](https://user-images.githubusercontent.com/748856/38768165-4e21585c-402a-11e8-9283-105107af334d.png)
![kitty-ibus-02](https://user-images.githubusercontent.com/748856/38768182-807842ac-402a-11e8-90c4-65742248d86c.png)

In xfce4-terminal, there is no separate ibus input area, and ibus-anthy works flawlessly because it uses Gtk input method.

In alacritty, ibus input area is shown, but it is shown at the correct position.

![alacritty-ibus-01](https://user-images.githubusercontent.com/748856/38768237-485044c8-402b-11e8-93b3-bbe1b82c3760.png)
![alacritty-ibus-02](https://user-images.githubusercontent.com/748856/38768238-4893570e-402b-11e8-8dc0-1fb7c12cfa06.png)

**Comment by kovidgoyal** [comment]
XIM is going away completely in kitty, see #171

**Comment by crocket** [comment]
I read it. Is GLFW going to replace XIM? Is it going to work with ibus on X11?

**Comment by kovidgoyal** [comment]
As far as I know, no it isn't. But you are welcome to contribute patches to glfw for it.

**Comment by kovidgoyal** [comment]
No, there isn't. Although since kitty supports XCompose, you can simply use that to input as many languages as you like, once you setup the mappings for it.
