### ISSUE TITLE
Inconsistent splits

### ISSUE THREAD

**Issue by Kiran-Raj-Dev** [kovidgoyal/kitty#4591]
**Describe the bug**
In my kitty.conf if I have `enabled_layouts Vertical` or `enabled_layouts splits:split_axis=vertical` then the first layout is a horizontal split.
and if I keep `enabled_layouts splits:split_axis=horizontal` then the first layout is a vertical split.

I think this is a little counter-intuitive.

System Specification:
I am on MacOS running the lastest release

**Comment by page-down** [comment]
The `enable_layouts` you mentioned is invalid, it should be `enabled_layouts`. This config works fine.

And for `splits` layout, `split_axis` refers to the direction of the separator split, not the placement of the layout.
Here is the layout action, and what is configured here are the parameters for that action (`split`).

Yes, I also thought it was strange when I first used this layout.

**Comment by Kiran-Raj-Dev** [comment]
Whoops sorry that was a typo I meant `enabled_layouts`

**Comment by kovidgoyal** [comment]
I'm afraid thats not going to change. split_axis has no relationship
with vertical or horizontal layouts.

**Comment by Kiran-Raj-Dev** [comment]
It would be great if you could add that detail in the docs!

**Comment by page-down** [comment]
I've added the docs and haven't submitted it yet.

I still have a question

```text
map f1 launch --location=hsplit
```

`launch --location=` should refer to how the new window will be placed (the location, where is the new window).
However, it actually creates a `vertical layout` (windows will be placed vertically one after the other).

This means that the current window will be cut horizontally and the new window will be placed below the horizontal of the original window.

Do I understand it correctly?
