### ISSUE TITLE
resize-os-window gets the line height wrong on mac os

### ISSUE THREAD

**Issue by anicolao** [kovidgoyal/kitty#4593]
## Expected Behavior
When using `kitty @resize-os-window --width 80 --height 10` I am expecting the window to have 10 lines.

## Current Behavior
The resulting window has 9 lines.

## Steps to Reproduce
Start a fresh instance:
```
$ kitty -v
kitty 0.23.1 created by Kovid Goyal
$ kitty --config NONE --override='allow_remote_control=yes'
```
Inside the fresh instance:
```
$ kitty @resize-os-window --width 80 --height 10
$ echo $LINES
9
```

## Your Environment
Darwin mercury 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin mercury 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control y
```

**Comment by page-down** [comment]
Update to the latest version. Check out changelog.

https://github.com/kovidgoyal/kitty/issues/4114#issuecomment-940981196
