### ISSUE TITLE
Shell-integrations not working on TMUX

### ISSUE THREAD

**Issue by arpangreat** [kovidgoyal/kitty#4599]
**Describe the bug**
The bug is not working when I am running it inside Tmux. I did set the shell integrations manually but it also not doing any thing too. 

**To Reproduce**
1. I deleted my tmux config file. But still it's no running. it's showing a empty buffer of less.
2. Openning it without tmux is working fine though.

**Screenshots**

Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
kitty 0.24.1 created by Kovid Goyal
Linux arpangreat 5.16.4-zen1-1-zen #1 ZEN SMP PREEMPT Sat, 29 Jan 2022 19:08:11 +0000 x86_64
Arch Linux 5.16.4-zen1-1-zen (/dev/tty)

LSB_VERSION=1.4
DISTRIB_ID=ArcoLinux
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="ArcoLinux"
Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/arpangreat/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.7
background_tint            0.85
bold_font                  Operator Mono Bold
bold_italic_font           Operator Mono Bold Italic
copy_on_select             clipboard
cursor                     None
cursor_blink_interval      0.0
cursor_shape               2
dynamic_background_opacity True
editor                     /usr/local/bin/nvim
enable_audio_bell          False
font_family                Operator Mono Lig Light
font_features:
{'FiraCodeNerdFontComplete-Retina': ('+zero', '+onum', '+calt')}
font_size                  16.5
italic_font                Operator Mono Lig Light Italic
shell_integration          frozenset({'disabled'})
tab_bar_style              slant
Added shortcuts:
	shift+ctrl+p scroll_page_up
	alt+ctrl+1 goto_tab 1
	alt+ctrl+2 goto_tab 2
	shift+super+v paste_from_buffer a1
Removed shortcuts:
	shift+ctrl+p > f kitten hints --type path --program -
	shift+ctrl+p > h kitten hints --type hash --program -
	shift+ctrl+p > l kitten hints --type line --program -
	shift+ctrl+p > n kitten hints --type linenum
	shift+ctrl+p > w kitten hints --type word --program -
	shift+ctrl+p > y kitten hints --type hyperlink
	shift+ctrl+p > shift+f kitten hints --type path
Changed shortcuts:
	shift+ctrl+n scroll_page_down
Colors:
	active_tab_background      #7aa2f7   
	active_tab_foreground      #1f2335   
	background                 #2e3440   
	color0                     #1d202f   
	color1                     #f7768e   
	color10                    #9ece6a   
	color11                    #e0af68   
	color12                    #7aa2f7   
	color13                    #bb9af7   
	color14                    #7dcfff   
	color15                    #c0caf5   
	color16                    #ff9e64   
	color17                    #db4b4b   
	color2                     #9ece6a   
	color3                     #e0af68   
	color4                     #7aa2f7   
	color5                     #bb9af7   
	color6                     #7dcfff   
	color7                     #a9b1d6   
	color8                     #414868   
	color9                     #f7768e   
	foreground                 #919298   
	inactive_tab_background    #292e42   
	inactive_tab_foreground    #545c7e   
	selection_background       #364a82   
	selection_foreground       #c0caf5   
	url_color                  #73daca

**Comment by arpangreat** [comment]
also the ctrl+shift+z and ctrl+shift+x not working

**Comment by kovidgoyal** [comment]
This is by design. shell integration by default nly works with shells
started by kitty. If you want it to work with tmux, you have to set it
up manually as described in:
https://sw.kovidgoyal.net/kitty/shell-integration

**Comment by page-down** [comment]
> ... I did set the shell integrations manually but it also not doing any thing too.

As far as I know, the shell integration does not work because kitty is not deeply integrated with tmux via tmux control mode.

> tmux control mode
> https://github.com/tmux/tmux/wiki/Control-Mode
> ... designed and written by George Nachman and allows his iTerm2 terminal to interface with tmux ...

So even if you configure it manually, it won't work. (iTerm2's shell integration is turned off by default, as it does not work in tmux default mode as well.)

The reason is that tmux wraps the shell, and kitty needs to read the original data and manipulate the scrollback, which it can't do. kitty doesn't know how to send tmux commands to manipulate it.

For why tmux is not integrated, please see the following link.

https://sw.kovidgoyal.net/kitty/faq/#i-am-using-tmux-and-have-a-problem

Still waiting for kitty daemon mode to fill in the last piece.

**Comment by arpangreat** [comment]
@page-down as you said , even manually intregration doesn't working , so I have to assume I must sacrifice something to use the best terminal ❤️🌝
