### ISSUE TITLE
Quit suddenly when Chinese charaters are involved

### ISSUE THREAD

**Issue by bash-horatio** [kovidgoyal/kitty#46]
OS: Debian 9 (Stretch)
Desktop Enviroment: LXQT
GLFW Verion: 3.2.1

With all dependent packages installed, the compilation was supper easy and kitty is a very nice terminal! Howerver, when I type `ls` in a directory with a flie whose name contains Chinese charaters, kitty just quits sharply.

I am not familliar to Python and C, and found nothing helpful by googling. Here is the stacktrace, and I missed something?

```
Unable to parse the pattern
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/Gits/APPS/kitty/__main__.py", line 7, in <module>
    main()
  File "~/Gits/APPS/kitty/kitty/main.py", line 175, in main
    run_app(opts, args)
  File "~/Gits/APPS/kitty/kitty/main.py", line 120, in run_app
    boss.render()
  File "~/Gits/APPS/kitty/kitty/boss.py", line 392, in render
    self.sprites.render_dirty_cells()
  File "~/Gits/APPS/kitty/kitty/shaders.py", line 93, in render_dirty_cells
    self.backend.render_dirty_cells(self.render_cell, self.send_to_gpu)
  File "~/Gits/APPS/kitty/kitty/shaders.py", line 87, in render_cell
    first, second = render_cell(text, bold, italic)
  File "~/Gits/APPS/kitty/kitty/fonts/render.py", line 41, in render_cell
    first, second = rc(text, bold, italic)
  File "~/Gits/APPS/kitty/kitty/fonts/freetype.py", line 176, in render_cell
    bitmap_char = render_char(text, bold, italic, width)
  File "~/Gits/APPS/kitty/kitty/fonts/freetype.py", line 97, in render_char
    font = font_for_char(text[0], bold, italic)
  File "~/Gits/APPS/kitty/kitty/fonts/freetype.py", line 43, in font_for_char
    return find_font_for_character(current_font_family_name, char, bold, italic)
  File "~/Gits/APPS/kitty/kitty/fonts/fontconfig.py", line 40, in find_font_for_character
    return get_font(q, bold, italic)
  File "~/Gits/APPS/kitty/kitty/fonts/fontconfig.py", line 21, in get_font
    raw = subprocess.check_output(['fc-match', query, '-f', '%{file}\x1e%{hinting}\x1e%{hintstyle}']).decode('utf-8')
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['fc-match', 'monospace:charset=597d:scalable=true:outline=true', '-f', '%{file}\x1e%{hinting}\x1e%{hintstyle}']' returned non-zero exit status 1
[glfw error]  The GLFW library is not initialized
```

The result of `ls` in Terminator:
```
$ ls
pulse-PKdhtXMmr18n                     您好
ssh-CNZEb3xJcOpv
```

**Comment by kovidgoyal** [comment]
The error means that fontconfig is unable to find a font to display that character. WHat does running the following on your system return?

```
fc-match query 'monospace:charset=597d:scalable=true:outline=true' -f '%{file} %{hinting} %{hintstyle}'
```

**Comment by kovidgoyal** [comment]
Sorry, I got the command wrong, above, this is the correct one:
 find a font to display that character. WHat does running the following on your system return?

```
fc-match  monospace:charset=597d:scalable=true:outline=true
```


On my system it returns, 

arialuni.ttf: "Arial Unicode MS" "Regular"

And kitty renders those characters fine.

**Comment by kovidgoyal** [comment]
Most likely you dont have a ttf/otf font on your system capable of rendering that character. Install one and you should be fine. Presumably Terminator falls back to using bitmap fonts -- kitty currently does not do that.

**Comment by bash-horatio** [comment]
In my system, it returns:
```
$ fc-match  'monospace:charset=597d:scalable=true:outline=true'
Unable to parse the pattern
```

Additional fonts  already intalled in my system are showed below, but I can't find a monospace font working for English and Chinese both. 
```
$ ls ~/.fonts
arialbd.ttf  arial.ttf   courbi.ttf  mplus-fonts-master  msyh.ttc     simkai.ttf   timesbi.ttf  ubuntu-mono
arialbi.ttf  ariblk.ttf  couri.ttf   msyhbd.ttc          simfang.ttf  simsun.ttc   timesi.ttf   wps-office
ariali.ttf   courbd.ttf  cour.ttf    msyhl.ttc           simhei.ttf   timesbd.ttf  times.ttf    zfull-for-yosemite-master
```

I also tried `Arial Unicode MS`, just the similar error
```
subprocess.CalledProcessError: Command '['fc-match', 'Arial Unicode MS:charset=597d:scalable=true:outline=true', '-f', '%{file}\x1e%{hinting}\x1e%{hintstyle}']' returned non-zero exit status 1
[glfw error]  The GLFW library is not initialized
```

**Comment by kovidgoyal** [comment]
fontconfig on your system is too old, update it and you should be fine.

**Comment by bash-horatio** [comment]
In the end, I find `Inziu Iosevka CL` works perfectly. Thanks!

**Comment by kovidgoyal** [comment]
You dont need a  font with both english and chinese -- kitty searches for fallback fonts when the primary font does not contain the glyphs it needs. The problem is that on your system, the fontconfig version is too old, so it is not understanding the :charset command line argument used to search for the fallback font.

But, since you found a font with the coverage you need, you dont have to worry about it.

**Comment by bash-horatio** [comment]
Thanks a lot! I can use monospace after updating the codes
