### ISSUE TITLE
Rapidly clicking on two links only opens the last

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#4603]
**Describe the bug**
If I click on two links with the mouse in kitty right after each other, only the last link is opened in the browser.

**To Reproduce**
1. Type e.g. `https://github.com https://google.com` in kitty.
2. Click on one of them, and then the other right after.
3. Observe that only the last clicked opens in the browser. If I wait a second or so between clicking the links, both opens.

**Environment details**
```
kitty 0.24.1 (2c0269930f) created by Kovid Goyal
Linux george 5.16.3-arch1-1 #1 SMP PREEMPT Thu, 27 Jan 2022 14:18:25 +0000 x86_64
Arch Linux 5.16.3-arch1-1 (/dev/tty)

LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /home/trygve/dev/kitty/kitty/launcher/kitty
  base dir: /home/trygve/dev/kitty
  extensions dir: /home/trygve/dev/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Environment variable names seen by the kitty process:
	ANDROID_HOME
	ANDROID_NDK
	ANDROID_NDK_HOME
	BROWSER
	CASROOT
	CLOUDSDK_PYTHON
	CLOUDSDK_PYTHON_ARGS
	CLOUDSDK_ROOT_DIR
	COLORTERM
	CSF_DrawPluginDefaults
	CSF_EXCEPTION_PROMPT
	CSF_IGESDefaults
	CSF_LANGUAGE
	CSF_MDTVTexturesDirectory
	CSF_MIGRATION_TYPES
	CSF_OCCTResourcePath
	CSF_PluginDefaults
	CSF_SHMessage
	CSF_STEPDefaults
	CSF_ShadersDirectory
	CSF_StandardDefaults
	CSF_StandardLiteDefaults
	CSF_TObjDefaults
	CSF_TObjMessage
	CSF_XCAFDefaults
	CSF_XSMessage
	CSF_XmlOcafResource
	DBUS_SESSION_BUS_ADDRESS
	DISPLAY
	DOTNET_BUNDLE_EXTRACT_BASE_DIR
	DOTNET_ROOT
	DRAWDEFAULT
	DRAWHOME
	EDITOR
	FZF_CTRL_T_COMMAND
	FZF_DEFAULT_COMMAND
	GOOGLE_CLOUD_SDK_HOME
	GTK_MODULES
	HOME
	JQ_COLORS
	KITTY_INSTALLATION_DIR
	KITTY_PID
	KITTY_WINDOW_ID
	LANG
	LC_MEASUREMENT
	LC_PAPER
	LC_TIME
	LESS
	LOGNAME
	LS_COLORS
	MAIL
	MMGT_CLEAR
	MOTD_SHOWN
	OLDPWD
	PAGER
	PATH
	PWD
	RIPGREP_CONFIG_PATH
	SHELL
	SHLVL
	SYSTEMD_LESS
	TERM
	TERMINFO
	USER
	WINDOWID
	WINDOWPATH
	XAUTHORITY
	XDG_RUNTIME_DIR
	XDG_SEAT
	XDG_SESSION_CLASS
	XDG_SESSION_ID
	XDG_SESSION_TYPE
	XDG_VTNR
	_
```

**Additional context**

I tried with `--config NONE`, same issue.

**Comment by kovidgoyal** [comment]
That will be because of click_interval. Two rapid clicks are
indistinguishable from a double cick if the mouse pointer does not move
far. I suggest you click while pressing ctrl+shift, this opens the URL
on the press rather than the click event, and so does not suffer
thisissue.

**Comment by trygveaa** [comment]
Can I configure how far the mouse can move so it's not interpreted as a double click?

**Comment by trygveaa** [comment]
Can I configure how far the mouse can move so it's not interpreted as a double click? I typically don't move the mouse at all when I double click, or at least not more than a few pixels, so I don't want it counted as a double click if I move several characters left/right or a line up/down.

And if it's counted as a double click, why is the last link opened rather than text being selected?

**Comment by kovidgoyal** [comment]
No, that's hardcoded, IIRC

**Comment by kovidgoyal** [comment]
What happens is the first press+release is not recognized as a click since it has a following press, then the second press + release is recognized as a click, since I assume you moved your mouse far enough for it not to be a double click. Thus the second click is all thats registered.

**Comment by trygveaa** [comment]
That sounds like a bug to me. If it determines that the second click isn't a double click, then the first click should be a normal click as well in my opinion.

**Comment by kovidgoyal** [comment]
You are welcome to send a patch for it.

**Comment by trygveaa** [comment]
Thanks! This is better, though I see that if I click on two links directly under each other it double clicks instead of opening them unless I click the first one at the top of the line and the second at the bottom of the line. I would prefer if it never counted it as a double click if I've moved to a new line, or if the click radius was just a few pixels.

As far as I can see, I now have to move more than one line height to not make it a double click, which seems too much to me.

**Comment by trygveaa** [comment]
> there hasto be some threshold. touchpads in particular generate lots of spurious movement between taps. I can countenance reducing it a bit

I suppose how much threshold is necessary may vary between users and devices. I tested a bit with wev now and see that most of the time it doesn't move at all when I double click, a few times it moves around a pixel. So yeah, reducing it to 5 pixels, or half a line height or something would be great.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/3be00bd712e212f314d1db97a0693a3d5476b40b

**Comment by trygveaa** [comment]
Perfect, thank you very much!
