### ISSUE TITLE
Shell integration `show_last_command_output` not working with custom pager

### ISSUE THREAD

**Issue by kovasap** [kovidgoyal/kitty#4604]
**Describe the bug**
When I try to use `scrollback_pager` to set a custom pager, I don't get any output from `show_last_command_output`.

**To Reproduce**
Run kitty with this config:
```
scrollback_pager less
# scrollback_pager nvim  # also doesn't work
map ctrl+shift+r show_scrollback
shell_integration enabled
map ctrl+shift+k show_last_command_output
```

`ctrl+shift+r` works to show all my command output, but `ctrl+shift+k` shows an empty buffer in every program I've tried to use.  I'm using zsh, and other Shell Integration features seem to work.  Specifically, I can use `ctrl+shift+rightclick` to view output for a single command in my custom pager no problem.

My kitty version is `0.24.1`.

**Comment by kovidgoyal** [comment]
Cannot reproduce with:

```
kitty --config=NONE -o scrollback_pager=less -o 'map ctrl+shift+k show_last_command_output'
```

Running ls and then pressing ctrl+shift+k shows the last command output,
as expected. The output includes escaped ANSI codes, to avoid those use

```
kitty --config=NONE -o 'scrollback_pager=less --RAW-CONTROL-CHARS' -o 'map ctrl+shift+k show_last_command_output'
```

**Comment by kovasap** [comment]
Your command does not work for me; my less contains no `ls` output after running it and pressing ctrl+shift+k :(.  There must be something strange about my setup.  Any tips on where to poke around to try to debug this?

**Comment by kovidgoyal** [comment]
I dont really see how its possible that setting scrollback_pager
prevents last command output from working. Not setting it simply means
it uses a default value of less anyway. Are you sure it actually works
without setting it?

**Comment by kovasap** [comment]
You're right, `kitty --config=NONE -o 'map ctrl+shift+k show_last_command_output'` also reproduces my problem.  Sorry for the red herring!

Anyway, there still must be some difference between our setups somewhere.

FWIW, `ctrl+shift+rightclick` does work under `kitty --config=NONE -o 'map ctrl+shift+k show_last_command_output'`.

**Comment by kovidgoyal** [comment]
Try the nightly build. Some issues with show_last_command_output were
fixed in master.

**Comment by kovasap** [comment]
Same behavior :/.

**Comment by kovidgoyal** [comment]
Then try with an empty zshrc

**Comment by kovidgoyal** [comment]
More accurately empty rc file for whatever shell you are using.

**Comment by kovasap** [comment]
That works.  Now to figure out why...

**Comment by kovidgoyal** [comment]
The most common reason is powerlevel10k, but in general just bisect your
zshrc

**Comment by romkatv** [comment]
@kovidgoyal My apologies for causing all these issues filed against you. I've been on the receiving end of this and I know how it feels. Sorry!

(The bug in p10k should be fixed now.)

**Comment by kovidgoyal** [comment]
No worries, this is inevitable when disparate projects try to co-operate
closely and is well worth the price.
