### ISSUE TITLE
long prompt with Nerd fonts causes text to appear on wrong line

### ISSUE THREAD

**Issue by dark-ether** [kovidgoyal/kitty#4611]
**Describe the bug**
i have a bash prompt with `PS1='\[\e[34m\][\u@\h $(smartpwd)]\$ \[\e(B\e[m\]'
` as you can see my prompt properly wraps the non printable characters with \\[ and \\] so this bug isn't caused by that. smartpwd is a bash function defined on my .bashrc that calls pwd and then sed to modify $HOME to ~. When i cd to a long directory structure such as ~/Documents/recursos\ academicos/computação/calculo\ numerico\ falcudade/trabalho1/ the prompt gets really long and  starts to bug causing text to appear in the wrong line, when i type something the first letter shows on the current line and all other text goes on the next line.

**To Reproduce**
1. set a nerd font as the font(i tested with Ubuntu, Roboto, Hack and Sauce Code Pro) 
1. create a really long prompt or increase text size until the prompt covers most of the line or more than one line
2. type a command
3. see that text appears on a different line than it should

**Screenshots**
here is it working normally https://imgur.com/SdTiVfG
here is the bug https://imgur.com/EXBKIPc
here is the bug with big text https://imgur.com/3BALkfG

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux eldritch 5.16.3-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 27 Jan 2022 14:18:27 +0000 x86_64
Arch Linux 5.16.3-zen1-1-zen (/dev/tty)

LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/eldritch/.config/kitty/kitty.conf

Config options different from defaults:
bold_font        Sauce Code Pro Bold Nerd Font Complete
bold_italic_font Sauce Code Pro Bold Italic Nerd Font Complete
font_family      Sauce Code Pro Black Nerd Font Complete
italic_font      Sauce Code Pro Black Italic Nerd Font Complete

```

**Additional context**
i tried to reproduce  with `kitty --config NONE`  but was unable to. i thought it was related to my font not being monospaced so i tried the mono variation of the font but it didn't fix the bug, then i tried other nerd fonts(roboto and Hack also monospaced) and the bug still appeared, this leads me to believe the bug is nerd font related, i tested with other terminal emulators(konsole and alacritty) but they didn't exhibit the bug

**Comment by kovidgoyal** [comment]
kitty doesn't draw the prompt, bash (or more correctly readline) does.
You will need to report the bug there. And note that choice fo font is
irrelevant, it will not change how many cells a particular character
takes up in kitty.
