### ISSUE TITLE
releasing mouse outside of window during selection does not copy

### ISSUE THREAD

**Issue by biwhite** [kovidgoyal/kitty#4617]
**Describe the bug**
Selecting text to copy, if you release the mouse button once it's already left the window, the selection isn't copied.

**To Reproduce**
Start selection a portion of text
Continuing to hold the LMB, move cursor outside of window.
Release LMB outside of window.
Try and paste.
Selection will either still be populated with previous paste, or empty.

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux gatsby 5.16.2-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 20 Jan 2022 16:18:31 +0000 x86_64
Arch Linux 5.16.2-zen1-1-zen (/dev/tty)

LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/ben/.config/kitty/kitty.conf

Config options different from defaults:
bold_font               Victor Mono
bold_italic_font        Victor Mono
copy_on_select          clipboard
disable_ligatures       1
enable_audio_bell       False
font_family             Victor Mono
font_size               14.0
italic_font             Victor Mono
term                    xterm-256color
touch_scroll_multiplier 2.5
update_check_interval   24.0
visual_bell_duration    0.2
Added shortcuts:
	super++ change_font_size all +2.0
	super+, edit_config_file
	super+- change_font_size all -2.0
	super+0 change_font_size all 0
	super+1 first_window
	super+2 second_window
	super+3 third_window
	super+4 fourth_window
	super+5 fifth_window
	super+6 sixth_window
	super+7 seventh_window
	super+8 eighth_window
	super+9 ninth_window
	super+= change_font_size all +2.0
	super+n new_os_window
	super+r start_resizing_window
	super+t new_tab
	super+w close_tab
	super+enter new_window
	super+up scroll_line_up
	super+down scroll_line_down
	super+page_up scroll_page_up
	super+page_down scroll_page_down
	super+home scroll_home
	super+end scroll_end
	shift+super+- change_font_size all -2.0
	shift+super+= change_font_size all +2.0
	shift+super+[ previous_tab
	shift+super+] next_tab
	shift+super+d close_window
	shift+super+i set_tab_title
	shift+super+w close_os_window
	alt+super+, debug_config
	alt+super+r clear_terminal reset active
	alt+super+page_up scroll_line_up
	alt+super+page_down scroll_line_down
	ctrl+super+  kitten unicode_input
	ctrl+super+, load_config_file
```

**Additional context**
Problem still exists with config NONE

**Comment by kovidgoyal** [comment]
Works fine for me under X11. Wayland probably doesn't deliver mouse events
to windows once the mouse leaves the window (it indulges in a lot of
security theater). Easily confirmed by (assuming you have xwayland
installed)

kitty -o linux_display_server=x11

**Comment by kovidgoyal** [comment]
actually given this is wayland it's probably compositor specific as
well. It works for me under GNOME.

**Comment by biwhite** [comment]
Looks like it works under X11, however I don't have this issue with other wayland based terminals such as alacritty/foot.  Their behaviour is as expected and clipboard is populated whether you release mouse button inside or outside their window.
Compositor is sway.

Running with --debug-input, I can see the terminal gets this upon LMB release, when outside or inside the window, so it's definitely getting the event that the selection has finished.

`Release mouse_button: 0 mods: numlock handled as drag end`

Running with other debug flags didn't produce anything more useful.  There doesn't appear to be clipboard related debug possible?

**Comment by kovidgoyal** [comment]
I tried it in sway, and it works fine for me with the following steps:

1) Run kitty
2) run ls inside kitty
3) drag a line of the ls output
4) keep dragging till the mouse leaves the kitty window and goes over
another window
5) leave the mouse button
6) middle click in another window
7) the dragged text is pasted as expected

**Comment by biwhite** [comment]
Ok, my behaviour is definitely different.  Performing the actions in your list I still hit the issue. Neither primary nor clipboard are updated with new content.  Performing same actions with alacritty/foot the clipboard is populated as you'd expect.

I'll see what extra debugging I can do.  clipman and WAYLAND_DEBUG=1 options might reveal what's going on more.
