### ISSUE TITLE
CKJ Input Support

### ISSUE THREAD

**Issue by crocket** [kovidgoyal/kitty#462]
CKJ means Chinese, Korean, Japanese.

Although XCompose can input many languages, I think I cannot manually map keystrokes to every chinese character used in china, korea, and japan through XCompose.

**Comment by kovidgoyal** [comment]
So write a script to do it for you. I dont know what you are asking for here. I already told you glfw does not support XIM.

**Comment by crocket** [comment]
It's very likely that a script won't be enough, either.
The number of chinese characters that japanese people use everyday is 2,200.
There are a lot more than 2,200.

**Comment by kovidgoyal** [comment]
Well, yes, if you are not willing to do any actual work, you are not going to be able to use CJK input in kitty. Expecting other people who have neither the interest nor the language knowledge to do the work for you is not going to get you anywhere. 

If I were you, I'd simply implement a kitten like the existing unicode input kitten that allows you to type pinyin and convert that to unicode characters. You can probably even just add a tab to the existing kitten for pinyin input. Of course, to do that you have to spend the time creating the tables to map pinyin to unicode.

**Comment by dsewnr** [comment]
I made a tool but only for vim in linux. You can modify it to fit your need.

https://github.com/dsewnr/linux-kitty-vim-cjk-input-tool
