### ISSUE TITLE
Clear screen + scrollback via Cmd+K on macOS

### ISSUE THREAD

**Issue by jab** [kovidgoyal/kitty#4625]
Both Terminal.app and iTerm.app on macOS come with the Command+K keyboard shortcut for clearing the screen and all the scrollback. Out of 15+ years of muscle memory, I keep hitting Cmd+K in Kitty to clear and then get `[107;9u` printed instead. What do you think of adding this default shortcut to Kitty.app, so it's that much easier for users migrating from Terminal and iTerm?

Thanks for your consideration and for the great work on Kitty!

**Comment by kovidgoyal** [comment]
You can add them for yourself in kitty.conf
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal

**Comment by page-down** [comment]
I'm curious how the other terminals are implemented.

I tested Terminal.app (`Clear to Start`) and iTerm2 (`Clear Buffer`) and their Cmd+K doesn't seem to reset, it just clears the scrollback.
It maintains the last prompt after pressed (not sure if it's redrawn).

Pressing it in a program such as vim will clear it all in iTerm2.
In Terminal.app the line where the cursor is still displayed is preserved. It looks pretty broken to me.

But here is a suggestion if such a default shortcut could be considered.

**Comment by page-down** [comment]
Since we have marked shell prompt, is it possible to clean up to the line before the marker?
This will preserve the last prompt.

**Comment by kovidgoyal** [comment]
Sure should be a simple patch, a PR is welcome. You check if the screen
has an active marked prompt and then scroll upto there, if not fallback
to scrolling upto the cursor line

**Comment by page-down** [comment]
Thank you, I see that it has been implemented.
Comparing different terminals, this feature is functioning properly.
And it works well with multi-line prompt.

**Comment by jab** [comment]
Thanks for adding this so quickly! This will make the Kitty experience on Mac even more 😻
