### ISSUE TITLE
Manual Shell Integration documentation is confusing.

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#4626]
In the shell integration configuration section it says that `no-rc` is useful if you want to set it up manually https://sw.kovidgoyal.net/kitty/shell-integration/#configuration but in the Manual shell integration section https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration it says that you should add `shell_integration disabled`

So I'm confused which one should I use if I want to manually enable the integration?

**Comment by page-down** [comment]
Either of these can be used.

If `no-rc` is configured, the execution environment or bash's rc file will not be modified, but the options configured here will still be passed in as `KITTY_SHELL_INTEGRATION` environment variable.

If `disabled` is configured, then even the above environment variable will not be passed in.

> `no-rc` ... Useful if you prefer to manually enable integration.

`useful` means that you don't have to configure the `KITTY_SHELL_INTEGRATION` environment variable yourself, if you don't need to use it remotely (SSH).

In general, you can configure `disabled` and then set `KITTY_SHELL_INTEGRATION` environment variable in the shell configuration and source the integration script.

If you use similar projects like zsh powerlevel10k, then they have their own way to integrate with kitty.
