### ISSUE TITLE
turn off window and tab titles for running commands

### ISSUE THREAD

**Issue by alperyilmaz** [kovidgoyal/kitty#4627]
**Describe the bug**

onwards of version 0.24, when I run a command, I see the command being executed shown in tab title and also in window title.

Your release notes indicate that "The current working directory or the command being executed are automatically displayed in the kitty window titlebar/tab title"

is it possible to just having **current working directory** because each time I run a command the changing titles is distracting

I know shell integration is discussed in previous issues and especially #4476 touches on this topic but it looks like I couldn't find a config option to turn off **command being executed** part.

So, is it possible to just have working directory in tab/window titles? 

**To Reproduce**
1. install kitty 0.24 and above
2. run a command like `sleep 5` and observe changes in tab/window titles

**Environment details**
```
Linux y540 5.15.11-76051511-generic #202112220937~1640185481~21.04~b3a2c21-Ubuntu SMP Mon Jan 3 16:5 x86_64
Pop!_OS 21.04 \n \l
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
Running under:X11
Loaded config files:
  /home/alper/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 1.0
font_family           FiraCode NF
font_size             17.0
inactive_text_alpha   0.8
strip_trailing_spaces smart
tab_activity_symbol   
tab_bar_style         separator
window_padding_width  FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
Added shortcuts:
        ctrl+f > 2 KeyAction('set_font_size', (20.0,))
```

**Comment by page-down** [comment]
You need to configure `shell_integration no-title` and then output the title yourself in the shell. Or copy the integration script locally from the git repository and modify and configure it yourself. There is currently no configuration that specifically controls the output of the command.

Only very small changes are needed.

zsh: commented out:
https://github.com/kovidgoyal/kitty/blob/v0.24.2/shell-integration/zsh/kitty-integration#L237-L238

bash: commented out:
https://github.com/kovidgoyal/kitty/blob/master/shell-integration/bash/kitty.bash#L90

fish: No changes will be made to the title. Just configure fish's own `fish_title.fish` directly.
https://fishshell.com/docs/current/cmds/fish_title.html

**Comment by maykel535** [comment]
Hi, reopen this thread...

I try the enable shell_integration no-title but not work for me:


`shell zsh`
`shell_integration no-title`

When I executed for example:

`watch -n0.1 uptime`

The command appear in the tab

[https://i.imgur.com/Qae005z.png](url)

**Comment by kovidgoyal** [comment]
Then you have something else in your zshrc setting the title

**Comment by maykel535** [comment]
Hi, thans for your soon response.

My .zshrc config is very basic:

[https://pastebin.com/5HtFuwET](url)

**Comment by maykel535** [comment]
Hi, with the .zshrc empty, the problem is the same... Using bash, works well.

I love kitty and I like solve this problem...

Is there any way to fix it? it's quite annoying

**Comment by kovidgoyal** [comment]
Look in all your zsh init files zshrc is not the only one. Regardless, I can tell you that shell_integration no-title works as expected.

**Comment by maykel535** [comment]
Thanks for your response.

My zshrc configuration is based solely on that file, I don't touch anything else. Plus the plugins I install.

The same .zshrc configuration in konsole I do not have this problem in the tab.

Is there any way to know what is causing it to not work correctly? launching kitty in debug mode could you see something?

**Comment by fernando535** [comment]
I have tried creating a new user on my Ubuntu using zsh by default, without installing anything plugins...etc in zsh () and I confirm that the same thing happens, it does not work.

If you run the command:

watch -n0.1 uptime

appears in the tab

[https://i.imgur.com/wy0rmK2.png](https://i.imgur.com/wy0rmK2.png)

**Comment by fernando535** [comment]
More info:

[https://i.imgur.com/Hk5UMhi.png](https://i.imgur.com/Hk5UMhi.png)
