### ISSUE TITLE
0.24.2 macOS DMG seems to be broken "no mountable file systems"

### ISSUE THREAD

**Issue by terrywang** [kovidgoyal/kitty#4629]
**Describe the bug**

0.24.2 macOS DMG seems to be broken, manually mounting the DMG failed with the same error `no mountable file systems`

```bash
brew install --cask kitty
==> Downloading https://github.com/kovidgoyal/kitty/releases/download/v0.24.2/kitty-0.24.2.dmg
Already downloaded: /Users/terry.wang/Library/Caches/Homebrew/downloads/daaf060d63c16bc54547d8d140a02a5c60f649087a453dcf56ac8127bc2eea48--kitty-0.24.2.dmg
==> Installing Cask kitty
hdiutil: attach failed - no mountable file systems
==> Purging files for version 0.24.2 of Cask kitty
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20220204-54310-1m7xrbr /private/tmp/d20220204-54310-1m7xrbr/daaf060d63c16bc54547d8d140a02a5c60f649087a453dcf56ac8127bc2eea48--kitty-0.24.2.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems
```

**To Reproduce**
1. `brew install --cask kitty`

**Screenshots**
NA

**Environment details**
```
macOS 11.6.3
```

**Additional context**
It worked fine with 0.24.1, previously macOS binary was provided in form of zip file. Can't remember when DMG came into play as I've been using homebrew cask to manage.

Signature verified BTW
```bash
gpg --verify kitty-0.24.2.dmg.sig
gpg: assuming signed data in 'kitty-0.24.2.dmg'
gpg: Signature made Thu  3 Feb 17:37:03 2022 AEDT
gpg:                using RSA key 3CE1780F78DD88DF45194FD706BC317B515ACE7C
gpg: Good signature from "Kovid Goyal (New longer key) <kovid@kovidgoyal.net>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 3CE1 780F 78DD 88DF 4519  4FD7 06BC 317B 515A CE7C
```

**Comment by page-down** [comment]
I don't have macOS 11, but I downloaded dmg from GitHub Releases and double-clicked to open it on a lower version of macOS without any problems.

I did not use homebrew nor did I test the `hdiutil attach` command.

**Comment by terrywang** [comment]
@page-down Thanks for testing. I just tried again to manually download 0.24.1 DMG and it is failed to be mounted as well, weird (more like an issue with this specific machine running some big bro agents). I'll test it on my own Mid 2015 MBP and report back.

**Comment by kovidgoyal** [comment]
reboot your computer. And if that doesnt work then uninstall whatever
kernel extension you have installed that is causing this.

**Comment by terrywang** [comment]
It worked fine on my other Mac, weird. So the solution is to reboot macOS (Windows?).
