### ISSUE TITLE
Theme unexpectedly overwrites values

### ISSUE THREAD

**Issue by lxhom** [kovidgoyal/kitty#4633]
**Is your feature request related to a problem? Please describe.**
I've tried to use `background-color none`/`foreground-color none`, but it didn't work at first because my theme was overwriting it. For example, this does not apply `background-color none`/`foreground-color none` to the terminal because the include overwrites the value:

```
selection_foreground none   
selection_background none
# BEGIN_KITTY_THEME
# Nord
include current-theme.conf  
# END_KITTY_THEME
```

Yet this works perfectly fine:

```
# BEGIN_KITTY_THEME
# Nord
include current-theme.conf  
# END_KITTY_THEME
selection_foreground none   
selection_background none
```

**Describe the solution you'd like**
It might be useful to set the priority of `background-color none`/`foreground-color none` higher than the theme overwrites

**Describe alternatives you've considered**
Maybe some kind of hint when something gets overwritten would be useful, or a small warning in the docs that themes tend to overwrite this

**Additional context**
None

P.S.: Thanks for the work on kitty, genuinely the best terminal I've ever used. Thank you so much <3

**Comment by kovidgoyal** [comment]
The priority is simple, later settings override earlier ones. 

If you want to override the colors in a theme, simply put the overrides
after the include, not before. Though you are better off creating a
custom theme, as described in
https://sw.kovidgoyal.net/kitty/kittens/themes/

**Comment by lxhom** [comment]
Haven't looked into custom themes, will check them out. Thanks for the fast reply!
