### ISSUE TITLE
Will italics cutoff ever be fixed

### ISSUE THREAD

**Issue by xsrvmy** [kovidgoyal/kitty#4635]
I use a narrow font (Iosevka) so that CJK characters do not have spaces between them. Unfortunately narrow fonts are basically incompatible with fitting italics within a rectangular (as opposed to slanted) bounding box, as doing so requires more horizontal space than usual between characters. Also, for this exact same reason, I don't believe it is actually the expectation that italics should fit within the same rectangular box as the upright version, especially bold italics.

Will this ever be fixed, or is there a technical reason why it cannot? Alacritty can handle it, and foot actually fixed this problem.

BTW are there any fonts you are aware of that actually has non-negative bearings in italics and bold italics as a design goal?

**Comment by kovidgoyal** [comment]
No, it will not. alacritty does not handle it, it just bleeds characters
into neighboring cells. That is not handling it. I have no idea what
foot does, but if it has indeed "fixed" it then it is no longer a
character cell based display. And the vast majority of monospace fonts
render fine in the bounding boxes of the regular face. If you want to
use some font combination that does not, the use adjust_cell_width to
make space.

**Comment by xsrvmy** [comment]
> alacritty does not handle it, it just bleeds characters into neighboring cells.

That IS the proper way of handling monospace italics. It is what you get if you perform a skew transformation on the text. It is also the same way it would be displayed if you entered it in a word processor.

> I have no idea what foot does, but if it has indeed "fixed" it then it is no longer a character cell based display.
What do you mean by "character cell based display"? Foot still aligns characters to a grid if I try and pass it a proportional font. The only terminal that does not do this is Konsole, and by extension QTerminal.

> And the vast majority of monospace fonts render fine in the bounding boxes of the regular face.
Actually, this is completely false. Most fonts will fail this on the letters W, X, A or m. The only free font that I found which does not go outside the rectangular bounding box in italics and bold italics is B612 mono. It also happens to not be recognized by kitty as monospace. A paid font seems to not go outside as well but that's only due to an option to artificially add spacing.
Of course there is the other alternative is to use a different font to represent italics instead (eg. Recursive Mono + Recursive Mono with casual style).

The whole point is that monospace has always been about constant advance and not the actual width of the glyph.

**Comment by kovidgoyal** [comment]
TERMINALS are character cell displays. That means EVERY CHARACTER is displayed INDEPENDENTLY IN A CELL. kitty leverages this fact TO RENDER EVERY CELL INDEPENDENTLY. That allows it to exceed the performance of something like alacritty while having a hundred times the features. Having characters bleed into neighboring cells LOOKS LIKE UTTER SHIT when the neighboring cells have a different color or a glyph that reaches the edge of the cell. If you think that is the "correct" solution I suggest you go use some other terminal emulator. This has all be explained ad nauseum in issues and even the FAQ. Search the FAQ for character cell.

References: 
character cell rendering in parallel:
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
https://github.com/kovidgoyal/kitty/issues/2022#issuecomment-850782462
Performance:
https://github.com/kovidgoyal/kitty/issues/2701#issuecomment-636497270
