### ISSUE TITLE
SIGUSR1 kills kitty terminal

### ISSUE THREAD

**Issue by hafeoz** [kovidgoyal/kitty#4636]
**Describe the bug**
Signaling SIGUSR1 will kill kitty terminal, even with a empty config

**To Reproduce**
1. kitty --config NONE
2. killall -s SIGUSR1 kitty
4. kitty terminates with "User defined signal 1"

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux rbq 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64
Arch Linux 5.16.4-arch1-1 (/dev/tty)

Running under:Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
Does not reproduce for me on Linux, with current kitty.

**Comment by hafeoz** [comment]
I did some testing and it seems to be related to wayland: when running `unset WAYLAND_DISPLAY` before starting `kitty`, kitty will capture SIGUSR1 and behave normally. If started using `WAYLAND_DISPLAY="wayland-1" kitty`, then kitty will exit when SIGUSR1 is received.

**Comment by hafeoz** [comment]
If specifying `linux_display_server x11` in the configuration file, then the kitty will run normally. It's definitely caused by some code specific to wayland.

**Comment by hafeoz** [comment]
Strange... I used [this script](https://unix.stackexchange.com/a/85365) to check which the signal is captured (blocked) and it indicates that SIGUSR1 is actually used by `kitty` under wayland but somehow it's still triggering a exit.

Output of `bash check_sig.sh PID_OF_KITTY_UNDER_WAYLAND`:
```
SigPnd:
SigBlk: INT(2) USR1(10) TERM(15) CHLD(17)
SigIgn: PIPE(13) XFSZ(25)
SigCgt: INT(2) (32) (33)
```

**Comment by hafeoz** [comment]
It's now getting even more strange... the build I downloaded from github release page works, but the binary distributed by Arch Linux doesn't.

**Comment by kovidgoyal** [comment]
Report it to arch then. SIGUSR1 is used by kitty to reload its config
file.

**Comment by Selmer443** [comment]
I'm still noticing this issue on Wayland , was wondering if there is a possible workaround? SIGUSR1 signal just kills kitty, I tried one of the releases on github instead of installing kitty with pacman. However still ran into the same issue.

**Comment by kovidgoyal** [comment]
Does not replicate for me with

kill -SIGUSR1 $KITTY_PID

in wayland or x11.

**Comment by Selmer443** [comment]
I'm using Hyprland on wayland, here is my kitty config:
window_padding_width 30
font_size 14
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
confirm_os_window_close 1
enable_audio_bell no
allow_remote_control yes

**Comment by kovidgoyal** [comment]
Yes, works fine for me on Hyprland. In any case the window manager has
no effect on how kityt handles SIGUSR1

**Comment by Selmer443** [comment]
what distribution are you currently running? I'm on arch personally

**Comment by kovidgoyal** [comment]
So am I.

**Comment by Selmer443** [comment]
What would be the next step for me to understand if there is a possible error on my end? is there a logfile I could attach here after sending SIGUSR1 signal?

**Comment by kovidgoyal** [comment]
kitty does not log receipt of signals. Make sure you are running up-to-date kitty and run it fomr another terminal you might see something useful printed to stderr though I doubt it.

**Comment by Selmer443** [comment]
Is there any chance you could send me a list of your installed packages? And what DE/WM are you using? My kitty is up to date, I've tried all the releases I could find and built from source

**Comment by kovidgoyal** [comment]
I'm afraid I am not willing to share that much information about my
environment. But I use i3 in X11.

**Comment by Selmer443** [comment]
sorry for my late response, I have installed i3 now and observed SIGUSR1 correctly reloading the config. One thing I noticed is that on Wayland/Hyprland I get this error when starting kitty from a terminal: 
[340 03:54:21.272906] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

This error is not present on X11/I3, and is the only difference i have found so far in terms of logging.

**Comment by Selmer443** [comment]
I'm using a desktop portal now, however SIGUSR1 still kills kitty unfortunately. What DE/WM are you using on Wayland when you are unable to reproduce the issue?

**Comment by kovidgoyal** [comment]
All of them.

**Comment by kovidgoyal** [comment]
The one thing I can think of is for some reason on your system libwayland is starting a thread. Since kitty's display backed is initialized before its signal handlers are installed, if that is the case that thread wont have the signals blocked and the kernel could be delivering the signals to that thread causing the abort. However, I can find no documentation suggesting libwayland uses threads and searching for pthread_create in its code base finds only some tests. https://github.com/wayland-project/wayland/search?q=pthread_create

**Comment by kovidgoyal** [comment]
And this commit will mask the signals before the braphics backend is initialized: https://github.com/kovidgoyal/kitty/commit/9cb0e4d09d7638163db94c4b7f14acad906f9eff

**Comment by Selmer443** [comment]
I built the latest commit and it is working now :) thank you so much for your work on the project.

**Comment by Hubro** [comment]
Still happens as of kitty 0.26.5. Will this be in the next patch release?

**Comment by kovidgoyal** [comment]
use the nightly builds or wait for th enext release.
