### ISSUE TITLE
Dynamic Link Error

### ISSUE THREAD

**Issue by zib0** [kovidgoyal/kitty#464]
Hi I am using a Macbook Pro with OS 10.12.6, and I followed the instruction until I do the step `python3 .`, and I caught 

> python3 .
dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

[1]    11443 abort      python3 .

**Comment by kovidgoyal** [comment]
That's a symbol in the system OpenGL framework that is missing. It indicates your system OpenGL libraries are broken or the dyld cache on your system is corrupted/incomplete. See for exxample: https://github.com/RyuKojiro/novafix/issues/11
