### ISSUE TITLE
`_ksi_prompt_command: command not found` appears at the prompt in other terminals 

### ISSUE THREAD

**Issue by meddario** [kovidgoyal/kitty#4655]
**Describe the bug**

**To Reproduce**
1. Install new version of Kitty with shell integration
2. Open a shell in another terminal (e.g. VSCode integrated terminal)
3. Message `_ksi_prompt_command: command not found` appears at every prompt (actually, on my pc it's in Italian, but the meaning is the same).

**Screenshots**

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux my-laptop 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64
Ubuntu 20.04.3 LTS my-laptop /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/myuser/.local/kitty.app/bin/kitty
  base dir: /home/myuser/.local/kitty.app/lib/kitty
  extensions dir: /home/myuser/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/myuser/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style   (True, False)
bell_on_tab             
bold_font               JetBrains Mono Bold
bold_italic_font        JetBrains Mono Bold Italic
clipboard_control       ('write-clipboard', 'write-primary', 'no-append')
enabled_layouts         ['splits:split_axis=vertical', 'stack']
font_family             JetBrains Mono Medium
font_size               9.5
inactive_tab_font_style (False, True)
initial_window_height   (40, 'cells')
initial_window_width    (120, 'cells')
italic_font             JetBrains Mono Italic
remember_window_size    False
scrollback_lines        50000
shell                   /bin/bash --login
strip_trailing_spaces   smart
tab_bar_edge            1
term                    xterm-256color
Added shortcuts:
	f1 → create_marker
	f2 → remove_marker
	f7 → layout_action rotate
	shift+left → neighboring_window left
	shift+right → neighboring_window right
	shift+up → neighboring_window up
	shift+down → neighboring_window down
	alt+" → launch --cwd=current --location=vsplit
	alt+% → launch --cwd=current --location=hsplit
	ctrl+n → scroll_to_mark next
	ctrl+p → scroll_to_mark prev
Changed shortcuts:
	ctrl+shift+t → new_tab_with_cwd !neighbor
	ctrl+shift+enter → new_window_with_cwd
Colors:
	background              #1c262b   
	color1                  #ee2a29   
	color10                 #70be71   
	color11                 #fef063   
	color12                 #53a4f3   
	color13                 #a94dbb   
	color14                 #42c6d9   
	color15                 #fffefe   
	color2                  #3fa33f   
	color3                  #fee92e   
	color4                  #1d80ef   
	color5                  #8800a0   
	color6                  #16aec9   
	color7                  #a4a4a4   
	color9                  #dc5b60   
	cursor                  #b2b8c3   
	foreground              #c1c8d6   
	selection_background    #6dc1b8   
	selection_foreground    #1c262b   

Environment variable names seen by the kitty process:
	AUTOJUMP_ERROR_PATH
	AUTOJUMP_SOURCED
	DBUS_SESSION_BUS_ADDRESS
	DESKTOP_SESSION
	DISPLAY
	GDMSESSION
	GEM_HOME
	GEM_PATH
	GIO_LAUNCHED_DESKTOP_FILE
	GIO_LAUNCHED_DESKTOP_FILE_PID
	GJS_DEBUG_OUTPUT
	GJS_DEBUG_TOPICS
	GNOME_DESKTOP_SESSION_ID
	GNOME_SHELL_SESSION_MODE
	GPG_AGENT_INFO
	GTK_MODULES
	HOME
	IM_CONFIG_PHASE
	INVOCATION_ID
	IRBRC
	JOURNAL_STREAM
	LANG
	LOGNAME
	MANAGERPID
	MY_RUBY_HOME
	PATH
	PROMPT_COMMAND
	PROMPT_RUNNER_DIR
	PWD
	QT_ACCESSIBILITY
	QT_IM_MODULE
	RUBY_VERSION
	SESSION_MANAGER
	SHELL
	SHLVL
	SSH_AGENT_PID
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	USER
	USERNAME
	WINDOWPATH
	XAUTHORITY
	XDG_CONFIG_DIRS
	XDG_CURRENT_DESKTOP
	XDG_DATA_DIRS
	XDG_MENU_PREFIX
	XDG_RUNTIME_DIR
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SESSION_TYPE
	XMODIFIERS
	_
	rvm_bin_path
	rvm_path
	rvm_prefix
	rvm_version

```

**Additional context**
I think that this could be related to shell integration, since the `_ksi_prompt_command` comes from a shell integration file from what I see. I don't know if it can be related with `$TERM` set to `xterm-256color` (i did this because I had problems with SSH, for example, no colors).

**Comment by kovidgoyal** [comment]
Does not reproduce for me with those steps. The kitty shell integration
script only takes effect if the KITTY_SHELL_INTEGRATION env var is set.
Which only kitty sets. If you have added it to your bashrc, remove it
and you will be fine.

**Comment by meddario** [comment]
Hi @kovidgoyal , thanks for the quick response, in my bashrc i have (I'm quite sure to not have added it myself):

```sh
# BEGIN_KITTY_SHELL_INTEGRATION
if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION
```
If I comment that line (`if test ...`), and then i close and reopen Kitty, the line reappears uncommented. Same thing if i delete the whole block (including the comments before and after).

Could it be related?

**Comment by kovidgoyal** [comment]
No, that just loads the script, the script doesnt do anythingunless KITTY_SHELL_INTEGRATION is set

**Comment by meddario** [comment]
Ok, is there a way to debug this? `$KITTY_SHELL_INTEGRATION` is empty both in kitty and VSCode terminal if I do an `echo`.

I also checked with `printenv`:

In Kitty:

```
printenv | grep -i kitty
KITTY_PID=55084
KITTY_WINDOW_ID=1
TERMINFO=/home/myuser/.local/kitty.app/lib/kitty/terminfo
KITTY_INSTALLATION_DIR=/home/myuser/.local/kitty.app/lib/kitty
GIO_LAUNCHED_DESKTOP_FILE=/home/myuser/.local/share/applications/kitty.desktop
```
In VSCode terminal:

```
printenv | grep -i kitty
KITTY_PID=49857
KITTY_WINDOW_ID=1
TERMINFO=/home/myuser/.local/kitty.app/lib/kitty/terminfo
KITTY_INSTALLATION_DIR=/home/myuser/.local/kitty.app/lib/kitty
GIO_LAUNCHED_DESKTOP_FILE=/home/myuser/.local/share/applications/kitty.desktop
```

The script shouldn't do nothing, but then how is `_ksi_prompt_command` called? If I delete the lines and then start VSCode e.g. from Gnome Terminal the message doesn't appear.

**Comment by kovidgoyal** [comment]
KITTY_SHELL_INTEGRATION gets unset by the script, its a pretty simple script, just read it for yourself.

**Comment by page-down** [comment]
I checked how many `export PROMPT_COMMAND` is on GitHub.

https://github.com/microsoft/vscode/blob/1.64.0/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh

Can only be related to this similar one.

**Comment by meddario** [comment]
This evening I'll check these scripts more in depth, I'll update here if I'll find something useful! Thanks to both!

**Comment by kovidgoyal** [comment]
Yeah that would do it. If there is another script that exports
PROMPT_COMMAND in the bash running in kitty, and then you launch vscode
from there, it will inherit the PROMPT_COMMAND and that PROMPT_COMMAND
will contain the call to _ksi_prompt_command, which will fail since it
isnt defined in vscode.

Long story short, exporting PROMPT_COMMAND is a very bad idea.

**Comment by kovidgoyal** [comment]
And this will take care of it: https://github.com/kovidgoyal/kitty/commit/7457f637a20ab3c9ed903a97f3fdb106a0b57fd5

**Comment by meddario** [comment]
Hi, thank you very much, the problem is solved with the latest version!
