### ISSUE TITLE
sending text with send-text to second window also sends it to current window

### ISSUE THREAD

**Issue by lacygoill** [kovidgoyal/kitty#4656]
**Describe the bug**

I'm currently following the [tutorial](https://sw.kovidgoyal.net/kitty/remote-control/?highlight=controlling#tutorial) to learn how to send text to a second window.  It works as expected in bash, but not always in zsh.  In the latter, the text is sometimes unexpectedly sent to the current window.

**To Reproduce**

Run these shell commands:

    kitty --config=NONE -o allow_remote_control=yes zsh
    kitty @ launch --title Output --keep-focus cat
    echo 'foobar' | kitty @ send-text --match title:Output --stdin

`foobar` is sent to the second window: this is expected.
`foobar` is also sent to the current window: this is not expected.

**Environment details**

    kitty 0.24.2 (7448789951) created by Kovid Goyal
    Linux ubuntu 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64
    Ubuntu 20.04.3 LTS ubuntu /dev/tty

    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
    Running under: X11
    Frozen: False
    Paths:
      kitty: /usr/local/bin/kitty
      base dir: /usr/local/lib/kitty
      extensions dir: /usr/local/lib/kitty/kitty
      system shell: /usr/bin/zsh
    Loaded config overrides:
      allow_remote_control yes

    Config options different from defaults:
    allow_remote_control y

    Important environment variables seen by the kitty process:
            PATH                                /home/lgc/.local/bin:/home/lgc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
            LANG                                en_US.UTF-8
            LC_TIME                             en_US.UTF-8
            LC_MONETARY                         en_US.UTF-8
            LC_ADDRESS                          en_US.UTF-8
            LC_TELEPHONE                        en_US.UTF-8
            LC_NAME                             en_US.UTF-8
            LC_MEASUREMENT                      en_US.UTF-8
            LC_IDENTIFICATION                   en_US.UTF-8
            LC_NUMERIC                          en_US.UTF-8
            LC_PAPER                            en_US.UTF-8

Version of zsh:

    zsh 5.8 (x86_64-ubuntu-linux-gnu)

**Additional context**

Regression introduced in commit https://github.com/kovidgoyal/kitty/commit/725ec57bee427f557f3f61a4c4d0e8f47b646e84

---

Setting the `shell_integration` option to `no-rc` or `disabled` fixes the issue.

---

This is probably not the right fix, but commenting these lines makes the issue disappear:
```diff
diff --git a/shell-integration/zsh/kitty-integration b/shell-integration/zsh/kitty-integration
index 7c786f19..65e365d8 100644
--- a/shell-integration/zsh/kitty-integration
+++ b/shell-integration/zsh/kitty-integration
@@ -234,8 +234,8 @@ _ksi_deferred_init() {
         # for us.
         functions[_ksi_precmd]+="
             builtin print -rnu $_ksi_fd \$'\\e]2;'\"\${(%):-%(4~|…/%3~|%~)}\"\$'\\a'"
-        functions[_ksi_preexec]+="
-            builtin print -rnu $_ksi_fd \$'\\e]2;'\"\${(V)1}\"\$'\\a'"
+        # functions[_ksi_preexec]+="
+        #     builtin print -rnu $_ksi_fd \$'\\e]2;'\"\${(V)1}\"\$'\\a'"
     fi
 
     # Enable cursor shape changes depending on the current keymap.
```

**Comment by page-down** [comment]
What is a title and how to set one, see:
https://wiki.archlinux.org/title/zsh#xterm_title

Shell integration features:
> ... or the command being executed ... title ...

https://sw.kovidgoyal.net/kitty/shell-integration/#features

send-text match:
> ... Match specifications are of the form: field:regexp ...

https://sw.kovidgoyal.net/kitty/remote-control/#kitty-send-text

As you surely know, you are running a command that comes with `Output`.

Just match the beginning.

```text
--match title:^Output
```

**Comment by lacygoill** [comment]
> As you surely know, you are running a command that comes with Output.
   >
   > Just match the beginning.
   >
   > --match title:^Output

I can confirm that this also fixes the issue, thank you.  Not sure why it's only necessary for zsh, and only when the shell integration is enabled.  Anyway closing the issue, since it appears not to be a bug.  Although, at some point, the tutorial could be updated to use the `^` anchor in the regex.  I'll try to submit a PR later.

**Comment by page-down** [comment]
> Not sure why it's only necessary for zsh

If you are not running another shell directly through kitty, then it is likely that the shell integration is not actually loaded.

> ... and only when the shell integration is enabled.

Because the shell integration sets the title for the command being run, this is already documented in the link above.

**Comment by lacygoill** [comment]
> If you are not running another shell directly through kitty, then it is likely that the shell integration is not actually loaded.

It must have been since the first way I found to fix the issue was by setting `shell_integration` to `disabled`.
