### ISSUE TITLE
tab_bar_style seems to be ignored in 0.24.2

### ISSUE THREAD

**Issue by angelus2014** [kovidgoyal/kitty#4660]
**Describe the bug**
tab_bar_style seems to be ignored in 0.24.2

**To Reproduce**
Open a second tab and the tab bar appears, even though I have set `tab_bar_style hidden`

I'm running Kitty on macOS 12.2

---
With regards,

Angelo Machils

**Comment by page-down** [comment]
I can't reproduce this under macOS.

```shell
kitty -o tab_bar_style=hidden
```

**Comment by angelus2014** [comment]
Weird......
<img width="674" alt="Screenshot 2022-02-09 at 6 28 17" src="https://user-images.githubusercontent.com/7578963/153122038-af02cd23-0200-46e9-afa6-e7436817cfa1.png">

**Comment by page-down** [comment]
Didn't you leave a colon and forget to delete it?

**Comment by angelus2014** [comment]
No, that's just 'more' I guess. It's not in the file when I vi it.

**Comment by page-down** [comment]
Try the following command and see if it works.

```shell
kitty --config=NONE -o tab_bar_style=hidden
```

**Comment by angelus2014** [comment]
Yes, then the tab bar stays hidden.....

**Comment by page-down** [comment]
Then you need to clear the configuration file and find out what the problem is.
Or just type the command `kitty`, run a new instance and look at the error log.

**Comment by angelus2014** [comment]
As I already wrote, the configuration is the same as with 0.24.1 and then there was no problem. With 0.24.2 there is however, so how can it be the configuration? Unless something has been changed there on the application side, but I didn't see any mention in the change log.

**Comment by page-down** [comment]
Since you didn't provide `ctrl+shift+f6` debugging information as instructed by the issue template,
then you need to provide a way how to reproduce the issue.

Otherwise I don't know how to solve it.

**Comment by angelus2014** [comment]
kitty 0.24.2 created by Kovid Goyal
Darwin orac.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.2 BuildVersion:	21D49
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/angelo/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style      (True, False)
bold_font                  JetBrains Mono NL Medium
bold_italic_font           JetBrains Mono NL Medium Italic
enable_audio_bell          False
font_family                JetBrains Mono NL Light
font_size                  13.0
hide_window_decorations    1
inactive_tab_font_style    (True, False)
italic_font                JetBrains Mono NL Light Italic
macos_thicken_font         0.25
macos_titlebar_color       370548226
selection_foreground       None
shell                      /opt/homebrew/bin/fish --login
shell_integration          frozenset({'disabled'})
single_window_margin_width FloatEdges(left=0.0, top=0.0, right=0.0, bottom=0.0)
tab_bar_margin_width       5.0
tab_fade                   (1.0,)
window_alert_on_bell       False
window_border_width        (0, 'pt')
window_padding_width       FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Added shortcuts:
	opt+1 → goto_tab 1
	opt+2 → goto_tab 2
	opt+3 → goto_tab 3
	opt+4 → goto_tab 4
	opt+5 → goto_tab 5
	opt+6 → goto_tab 6
Changed shortcuts:
	ctrl+shift+t → select_tab
Colors:
	active_border_color        #3d59a1   
	active_tab_background      #16161e   
	active_tab_foreground      #3d59a1   
	background                 #1a1b26   
	bell_border_color          #e0af68   
	color0                     #414868   
	color1                     #f7768e   
	color10                    #73daca   
	color11                    #e0af68   
	color12                    #7aa2f7   
	color13                    #bb9af7   
	color14                    #7dcfff   
	color15                    #c0caf5   
	color2                     #73daca   
	color3                     #e0af68   
	color4                     #7aa2f7   
	color5                     #bb9af7   
	color6                     #7dcfff   
	color7                     #c0caf5   
	color8                     #414868   
	color9                     #f7768e   
	cursor                     #c0caf5   
	cursor_text_color          #1a1b26   
	foreground                 #a9b1d6   
	inactive_border_color      #101014   
	inactive_tab_background    #16161e   
	inactive_tab_foreground    #787c99   
	selection_background       #28344a   
	tab_bar_background         #101014   
	url_color                  #9ece6a   

Environment variable names seen by the kitty process:
	COMMAND_MODE
	HOME
	LANG
	LOGNAME
	PATH
	SHELL
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	TMPDIR
	USER
	XPC_FLAGS
	XPC_SERVICE_NAME
	__CFBundleIdentifier
	__CF_USER_TEXT_ENCODING

**Comment by angelus2014** [comment]
How to reproduce it: just put _any_ option after tab_bar_style *in the config file*, not with -o when starting Kitty.

**Comment by page-down** [comment]
On the debug info, you can see that there is no `tab_bar_style`.

And in my case, it can be seen
```text
Config options different from defaults: 
tab_bar_style hidden
```

You can try this:
Exit kitty completely, rename the config file and write a new one with only `tab_bar_style hidden`.

**Comment by angelus2014** [comment]
Why is this issue closed? For the third time, the same config worked on 0.24.1, but shows this on 0.24.2. I've just tested it on my other M1 Mac which hasn't updated to .2 yet, checked, config works. Update to .2 and the setting is ignored. I did create the file as you requested and then yes, the setting works. Now do you expect me to put back all the changes one by one and see what happens? Why did it work in .1 but not in .2?

Well, as the 'maintainer' writes so often himself, I neither have the time nor interest to spend this kind of time on finding something that worked before.

Thank you @page-down for your assistance. And @kovidgoyal, perhaps you should try *not* to close issues so quickly?!

**Comment by kovidgoyal** [comment]
On Tue, Feb 08, 2022 at 09:26:04PM -0800, angelus2014 wrote:
> Why is this issue closed? 

Because you have provided no information that actually points to an
issue other than your "claims". Your debug output shows no setting.
Trying to replicate it with a minimal config file fails. 

> For the third time, the same config worked on 0.24.1, but shows this on 0.24.2. I've just tested it on my other M1 Mac which hasn't updated to .2 yet, checked, config works. Update to .2 and the setting is ignored.

You havent even bothered to provide a full config file forget about
a minimal one that reproduces the issue. You didnt even provide the
information the issue template asked for until you were prodded to do
so, by people providing you free support because you are too fucking lazy
to do a minimum of due diligence yourself.

> I did create the file as you requested and then yes, the setting works. Now do you expect me to put back all the changes one by one and see what happens? Why did it work in .1 but not in .2?

Yes, that is what I expect. Not entitled whining. Do you think you are
doing someone a favor by using kitty?

> 
> Well, as the 'maintainer' writes so often himself, I neither have the time nor interest to spend this kind of time on finding something that worked before.
> 
> Thank you @page-down for your assistance. And @kovidgoyal, perhaps you should try *not* to close issues so quickly?!

Perhaps you should try to not use kitty.

**Comment by jtrees** [comment]
I am experiencing the same issue. I opened a new bug report here: #4669
