### ISSUE TITLE
Different sizes of icons: `symbol_map` vs fallback

### ISSUE THREAD

**Issue by anuvyklack** [kovidgoyal/kitty#4670]
When I set icons explicitly with `symbol_map`, they are rendered much smaller than when kitty automatically set them with a fallback mechanism.

I am using kitty `0.24.2` and icons only nerd font: [Symbols-2048-em Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/NerdFontsSymbolsOnly/complete)

Icons are set explicitly with:
```conf
# F655 : 
# E615 : 
# F0F6 : 
symbol_map U+F655,U+E615,U+F0F6 Symbols Nerd Font
```
With this settings I get

![Screenshot-20220209205939-1480x64](https://user-images.githubusercontent.com/13056013/153300204-77c30ba1-e37c-4b72-aaf7-449a0e8c4fce.png)

When I comment out the snippet above and let kitty make all the job, I get

![Screenshot-20220209205904-1494x64](https://user-images.githubusercontent.com/13056013/153300440-954b2503-742d-4c22-acb1-1626882296f2.png)

I use Ubuntu 21.10.

`kitty --debug-font-fallback` output:

```
U+f655 italic Face(family=Symbols Nerd Font, style=2048-em,
ps_name=SymbolsNerdFontComplete-2048-em,
path=/home/anuvyklack/.local/share/fonts/Unknown Vendor/TrueType/Symbols Nerd Font/Symbols_Nerd_Font_2048_em.ttf,
index=0, is_scalable=True, has_color=False, ascender=1638, descender=-410, height=2048, underline_position=-306,
underline_thickness=102, strikethrough_position=530, strikethrough_thickness=102)

U+e615 italic Face(family=Symbols Nerd Font, style=2048-em,
ps_name=SymbolsNerdFontComplete-2048-em,
path=/home/anuvyklack/.local/share/fonts/Unknown Vendor/TrueType/Symbols Nerd Font/Symbols_Nerd_Font_2048_em.ttf,
index=0, is_scalable=True, has_color=False, ascender=1638, descender=-410, height=2048, underline_position=-306,
underline_thickness=102, strikethrough_position=530, strikethrough_thickness=102)
```

The same problem I have with **Material Design Icons** icons only font.

I read that when fallback kitty use `fontconfig` cache. My `$HOME/.config/fontconfig` directory is empty.
How to make font rendering uniform between these two cases? And if icons can be rendered bigger or smaller how can I control their size?

**Comment by kovidgoyal** [comment]
This will be because different fonts are being used in the two cases.
Most likely in one case Symbols Nerd Fonts 2048em and the other 1000em.
Look at the --debug-font-fallback output when using symbol map as well.

And no there is no way to control their size other than using different
fonts.

**Comment by anuvyklack** [comment]
> This will be because different fonts are being used in the two cases.
> Most likely in one case Symbols Nerd Fonts 2048em and the other 1000em.

I thought about it before I opened an issue and  I have no other fonts except **Inconsolata LGC**, which I use as main, and **Symbols Nerd Font 2048em** in `$HOME/.local/share/fonts` folder.  I don't even have a copy of **Symbols Nerd Fonts 1000em** file on my computer.

The `kitty --debug-font-fallback` output when `symbol_map` set:

```
[041 18:20:34.552240] Preloaded font faces:
[041 18:20:34.552315] normal face: /home/anuvyklack/.local/share/fonts/InconsolataLGC.otf:0
[041 18:20:34.552330] bold face: /home/anuvyklack/.local/share/fonts/InconsolataLGC-Bold.otf:0
[041 18:20:34.552352] italic face: /home/anuvyklack/.local/share/fonts/InconsolataLGC-Italic.otf:0
[041 18:20:34.552380] bi face: /home/anuvyklack/.local/share/fonts/InconsolataLGC-BoldItalic.otf:0
[041 18:20:34.552393] Symbol map faces:
[041 18:20:34.552403] /home/anuvyklack/.local/share/fonts/Unknown Vendor/TrueType/Symbols Nerd Font/Symbols_Nerd_Font_2048_em.ttf:0
[041 18:20:34.552425] /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
[041 18:20:34.552452] /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
```

**Comment by kovidgoyal** [comment]
Well, I know of no way font size can be influenced by which method is used to select the font. I suggest you try the official kitty build from here: https://sw.kovidgoyal.net/kitty/binary/

**Comment by anuvyklack** [comment]
I am using the official build. I have an [Ansible role](https://github.com/anuvyklack/dotfiles/blob/master/roles/kitty/tasks/main.yml) which do the next:

```
$ curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest=$HOME/.local/stow launch=n
$ cd $HOME/.local/stow
$ stow --restow kitty.app
```

**Comment by anuvyklack** [comment]
I have exectly the same problem with **Material Design Icons** font. When `symbol_map` set, the icons are smaller:

![Screenshot-20220210231653-928x154](https://user-images.githubusercontent.com/13056013/153490209-c54bda4a-807c-40f0-af92-b0732dea33a2.png)

![Screenshot-20220210231910-890x142](https://user-images.githubusercontent.com/13056013/153490217-569707b1-e96b-49f5-87c5-0130544c40ac.png)

`kitty --debug-font-fallback`:

```
U+f13ab italic Face(family=Material Design Icons, style=Regular, ps_name=MaterialDesignIcons,
Rath=/home/anuvyklack/.local/share/fonts/Unknown Vendor/TrueType/Material Design Icons/Material_Design_Icons_Regular.ttf,
index=0, is_scalable=True, has_color=False, ascender=448, descender=-64, height=512,
underline_position=5, underline_thickness=0, strikethrough_position=132, strikethrough_thickness=25)

U+f051b italic Face(family=Material Design Icons, style=Regular, ps_name=MaterialDesignIcons,
path=/home/anuvyklack/.local/share/fonts/Unknown Vendor/TrueType/Material Design Icons/Material_Design_Icons_Regular.ttf,
index=0, is_scalable=True, has_color=False, ascender=448, descender=-64, height=512,
underline_position=5, underline_thickness=0, strikethrough_position=132, strikethrough_thickness=25)
```

**Comment by kovidgoyal** [comment]
Ah, I think I know whats going on. This will be the code to use trailing spaces for symbols and dingbats.

**Comment by anuvyklack** [comment]
I checked the latest nightly build:
> Nightly release, generated on: 2022-02-11 21:22:34 UTC from commit: 9222d00

with
```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest=$HOME/.local/stow launch=n installer=nightly
```
Nothing have changed :{

**Comment by kovidgoyal** [comment]
THis should take care of it: https://github.com/kovidgoyal/kitty/commit/263d121f3ee5e11c0eedb8417ce0bf324f163313
