### ISSUE TITLE
Keep colors when using the `hints` kitten

### ISSUE THREAD

**Issue by cole-h** [kovidgoyal/kitty#4673]
**Is your feature request related to a problem? Please describe.**
I'm attempting to switch to kitty, but one thing that really bothers me is that using any of the `hints` bindings clears all the colors from my buffer while I'm in that kitten.

**Describe the solution you'd like**
I'd like some way to prevent the clearing of the coloring.

**Describe alternatives you've considered**
There aren't really any alternatives to this (that I've thought of, at least).

**Additional context**
N/A.

**Comment by kovidgoyal** [comment]
This is by design. The idea is that only the highlighted links should be
prominent, the rest of the text fades.

**Comment by cole-h** [comment]
A bit unfortunate, but I suppose I'll get used to it. Thanks for the quick response!
