### ISSUE TITLE
Strange character display

### ISSUE THREAD

**Issue by Yarnus** [kovidgoyal/kitty#4676]
**Describe the bug**

My Kitty was newly installed but when i type `config` it would map `if` to a phone icon. (please find my screenshot.)

**To Reproduce**
1. newly installed kitty
2. type `config`

**Screenshots**

<img width="393" alt="image" src="https://user-images.githubusercontent.com/18589312/153377813-2914d57c-5dc3-4b41-9e90-d955f32f4b55.png">

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

kitty 0.24.2 created by Kovid Goyal
Darwin YarnusdeMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.14.6 BuildVersion:	18G1012
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/yarnus/.config/kitty/kitty.conf

Config options different from defaults:
font_family        Monaco Nerd Font Mono
font_size          15.0
shell_integration  frozenset({'disabled'})
tab_bar_edge       1
tab_bar_min_tabs   1
tab_separator       |
tab_title_template {title}

Environment variable names seen by the kitty process:
	Apple_PubSub_Socket_Render
	DISPLAY
	HOME
	LANG
	LOGNAME
	PATH
	SHELL
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	TMPDIR
	USER
	XPC_FLAGS
	XPC_SERVICE_NAME
	__CF_USER_TEXT_ENCODING

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/18589312/153378890-e45f2920-6f06-483f-93fd-a46473f5a054.png">

hi there, it would be better on this case but actually i didn't have any `kitty.conf` on `~/.config/kitty/`

**Comment by kovidgoyal** [comment]
that will be a ligature from your font. You appear to be using a patched
font Monaco Nerd Font Mono dont do that. Instead use the unpatched font
and install the nerd font separately, kitty will use it automatically.
See the note here https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
