### ISSUE TITLE
Scrollback speed affect scrolling speed in vim (and neovim)

### ISSUE THREAD

**Issue by xsrvmy** [kovidgoyal/kitty#4680]
**Describe the bug**
When wheel_scroll_multiplier or touch_scroll_multiplier is set, vim scrolls way too fast.

**To Reproduce**
1. Set wheel_scroll_multiplier or touch_scroll_multiplier to 9
2. Open a large file in vim (or just enter a lot of lines and turn on line numbers)
3. Notices that it scrolls 9 lines at once instead of the usual 3

It seems that vim is receiving multiple scroll events per scroll. Does this have anything to do with terminfo?

In other terminals:
- less is affected by scrollback settings
- vim is not affected by scrollback settings

In kitty:
- less is affected by scrollback settings
- vim is affected by scrollback settings

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux <redacted> 5.16.7-arch1-1 #1 SMP PREEMPT Sun, 06 Feb 2022 16:47:29 +0000 x86_64
Arch Linux 5.16.7-arch1-1 (/dev/tty)

LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/<redacted>/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell       False
font_family             ISVK
font_size               12.0
initial_window_height   (30, 'cells')
initial_window_width    (100, 'cells')
remember_window_size    False
touch_scroll_multiplier 9.0
url_style               1
Colors:
	background              #191c25   
	color0                  #2e313d   
	color1                  #cf8164   
	color10                 #92c47e   
	color11                 #d2b45f   
	color12                 #a0b9d8   
	color13                 #c6aed7   
	color14                 #7dc2c7   
	color15                 #f0ecfe   
	color2                  #76a065   
	color3                  #ab924c   
	color4                  #8296b0   
	color5                  #a18daf   
	color6                  #659ea2   
	color7                  #b5b4c9   
	color8                  #5b5f71   
	color9                  #fe9f7c   
	foreground              #b5b4c9   
	selection_background    #b5b4c9   
	selection_foreground    #191c25   
	url_color               #cccccc   

Environment variable names seen by the kitty process:
	CHR_WAYLAND_FLAGS
	DBUS_SESSION_BUS_ADDRESS
	DESKTOP_SESSION
	DISPLAY
	HOME
	I3SOCK
	KWIN_DRM_DEVICES
	LANG
	LOGNAME
	MAIL
	MOTD_SHOWN
	MOZ_ENABLE_WAYLAND
	OLDPWD
	PAM_KWALLET5_LOGIN
	PATH
	PWD
	QT_QPA_PLATFORMTHEME
	SAL_USE_VCLPLUGIN
	SHELL
	SHLVL
	SSH_AUTH_SOCK
	SWAYSOCK
	USER
	WAYLAND_DISPLAY
	WLR_DRM_DEVICES
	XCURSOR_SIZE
	XDG_CURRENT_DESKTOP
	XDG_DATA_DIRS
	XDG_RUNTIME_DIR
	XDG_SEAT
	XDG_SEAT_PATH
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SESSION_ID
	XDG_SESSION_PATH
	XDG_SESSION_TYPE
	XDG_VTNR
	_
	__EGL_VENDOR_LIBRARY_FILENAMES

```

Note: ISVK is a custom-compiled version of Iosevka with lower italic angle fixing italics being cutoff.

**Comment by kovidgoyal** [comment]
set mouse=a in vim

**Comment by xsrvmy** [comment]
I have `mouse=a` in vim settings already.

**Comment by xsrvmy** [comment]
Actually I found something that did work: `set ttymouse=xterm`.
The default setting that vim is picking up from terminfo is `set ttymouse=sgr`.

However `ttymouse` is no longer configurable in neovim.

**Comment by kovidgoyal** [comment]
Both vim and nvim auto-detect kitty for years. Are you using some ancient versions? In any case, this is not a kitty issue, the multipler settings take effect when the terminal program does not grab the mouse, kitty cannot force programs to grab the mouse, they haveto decide to do that themselves.

**Comment by xsrvmy** [comment]
Actually I don't think this fixes the issue completely either. Now the scrolling is way too slow. The problem here is that low precision scroll wheels are still handled as high precision on wayland but we don't know how many pixels one click scrolls by. So there needs to be a configuration value for this.
I was actually going to send in a PR for this, but I couldn't get the python script for generating a new configuration to work.
