### ISSUE TITLE
Support relative direction resizing in start_resizing_window with custom mappings

### ISSUE THREAD

**Issue by chancez** [kovidgoyal/kitty#4684]
**Is your feature request related to a problem? Please describe.**

Currently `start_resizing_window` allows you to select from "wider", "narrower", "taller", "shorter". I would like to be able to define mappings that resize based on a direction, eg: "left", "right", "up", "down" directions for resizing. Additionally, I'd like to be able define custom mappings for those resizing directions (eg: hjkl for vim bindings). Overall, this would behave somewhat similar to resizing a vim window, if you're familiar. 

**Describe the solution you'd like**

For for example, using https://sw.kovidgoyal.net/kitty/layouts/#the-tall-layout as the example, if we label the windows, 1-4 starting on the left window as 1, then going from the top down on the right hand side for 2-4.

If I'm resizing window 1, and I wanted to resize "right", it would act the similar to "wider", "left" would be "narrower" and up/down would do nothing, like "taller" and "shorter". 

However, it is not an exact mapping if a window is surrounded, and probably other cases. If we were resizing window 3, the middle window on the right side, then left->wider, right->narrower, up->taller but by growing the lower portion, down->taller, but growing the top portion.

**Describe alternatives you've considered**
So I considered that all I may need is the ability to define custom key mappings for the current resize actions, like mentioned in https://sw.kovidgoyal.net/kitty/layouts/#resizing-windows, however, I realized that I want something "relative" to the position the window is in, and the current resizing actions are more like "absolute".

**Comment by kovidgoyal** [comment]
Layouts dont have directional sizing. Or in other words you cannot
resize edges in general.

**Comment by chancez** [comment]
I don't need layout directional sizing, I only need directions relative to the current window.

**Comment by kovidgoyal** [comment]
There is no meaning of left and right as you yourself point out. Making left=narrower and right=wider is completely arbitrary and can seem natural or not depending on an individual layout.

**Comment by chancez** [comment]
There is a meaning of left and right, that's not what I said, it's that it's relative, depending on if there is a column/row above/below the current window. It's not that different than how neighboring_window works. An example:

```
def resize_relative(direction: str):
  neighbor = neighboring_window(direction)
  if direction == 'left'
    if neighbor != None:
      resize_window('narrower')
    else:
      resize_window('wider')

  if direction == 'right'
    if neighbor != None:
      resize_window('wider')
    else:
      resize_window('narrower')

  if direction == 'up'
    if neighbor != None:
      resize_window('taller')
    else:
      resize_window('shorter')

  if direction == 'down'
    if neighbor != None:
      resize_window('shorter')
    else:
      resize_window('taller')
```

**Comment by kovidgoyal** [comment]
That's an arbitrary meaning you have chosen, not an intrinsic one. If you like this meaning feel free to implement it as a kitten, it shouldnt be too hard.

**Comment by page-down** [comment]
Do you need this feature below? (not yet implemented)

https://github.com/kovidgoyal/kitty/issues/4239

My idea is to move the edge of the window. (The usual case is the lower right corner of the window, unless the window is taped to the edge.)

**Comment by chancez** [comment]
> Do you need this feature below? (not yet implemented)
> 
> #4239
> 
> My idea is to move the edge of the window. (The usual case is the lower right corner of the window. It's like holding down that point to move. Unless the window is near the edge.)

It looks like it might be, it's basically how resizing works in any other windowing system I've used, which tmux is one of them. So probably.

**Comment by chancez** [comment]
> That's an arbitrary meaning you have chosen, not an intrinsic one. If you like this meaning feel free to implement it as a kitten, it shouldnt be too hard.

I've started working on this, but I don't see any way to check if there's a neighboring window. The `neighboring_window` seems to select the neighboring window if it exists, but I need something like `neighboring_group_id`.

**Comment by chancez** [comment]
So far I got the kitten working how I wanted: https://github.com/chancez/dotfiles/commit/52da974ecd561afaf97de66a3f1c41ae1fe5165e

I'll try to see how I can use `self.current_layout.neighbors_for_window`. How do I get `all_windows`?

Also, I realized my logic in the above comment was wrong, so maybe that's why you thought it was arbitrary hah.

**Comment by kovidgoyal** [comment]
There is already a neighboring_group_id(which) function. See line 589 in
tabs.py for the active window. Look at its implementation to learn how
to generalize it for any window.

**Comment by chancez** [comment]
> There is already a neighboring_group_id(which) function. See line 589 in
> tabs.py for the active window. Look at its implementation to learn how
> to generalize it for any window.

I'm using `neighboring_group_id(which)`, is there any reason I can't just keep using it?

**Comment by chancez** [comment]
Of the following approaches, is any particular one a 'better' one for my kitten:


```
    neighbor = boss.active_tab.neighboring_group_id(neighbor_direction)
    has_neighbor = neighbor is not None
```


```
    window = boss.window_id_map.get(target_window_id)
    neighbors = boss.active_tab.current_layout.neighbors_for_window(window, boss.active_tab.windows)
    has_neighbor = len(neighbors.get(neighbor_direction,[])) != 0
```

```
    neighbors = boss.active_tab.current_layout.neighbors(boss.active_tab.windows)
    has_neighbor = len(neighbors.get(neighbor_direction,[])) != 0
```

**Comment by kovidgoyal** [comment]
On Thu, Feb 10, 2022 at 07:13:40PM -0800, Chance Zibolski wrote:
> Of the following approaches, is any particular one a 'better' one for my kitten?:
> 
> 
> ```
>     neighbor = boss.active_tab.neighboring_group_id(neighbor_direction)
>     has_neighbor = neighbor is not None
> ```

This is what I would recommend.
