### ISSUE TITLE
Colorspace Options

### ISSUE THREAD

**Issue by typkrft** [kovidgoyal/kitty#4686]
**Is your feature request related to a problem? Please describe.**
I saw this [issue](https://github.com/kovidgoyal/kitty/issues/2249) and suspect this to be related. In my experience colors look a bit washed out or faded when compared to Wezterm and VSCode. Maybe it's possible I missed a configuration option somewhere. When using `Digital Color Meter.app` Kitty and iTerm2 differ, but it is imperceptible to me. Wezterm and VSCode match exactly. The swatches on Dracula's [website](https://draculatheme.com/contribute) seem to be somewhere in between kitty and others, but subjectively closer to Wezterm or VSCode.

**Describe the solution you'd like**
If this is expected, and this relates to the other thread than an option would be ideal. Though considering none of the colors match up perfectly I'm not sure there is an perfect solution, what I'd like to see is getting as close to the reported values on dracula's website. Though syncing up with Wezterm and VSCode would be in improvement in my eyes, obviously very subjective.

**Describe alternatives you've considered**
Color shifting the entire theme for kitty seems excessive, though if there's an easy way to do this, that would be acceptable. I am not particularly familiar with how colors work or are displayed.  

**Additional context**
I'm not sure if some kind of compression is occurring on github, but the differences are significantly more subtly than they are in the actual screenshots I took. 

__Kitty on the left, Wezterm on the right__
![Colors](https://user-images.githubusercontent.com/12100960/153529555-2e945883-e453-45f2-b832-154ff8da5769.jpg)
__Wezterm on the Bottom, Kitty on the top__ The Reds seem to be the most off. 
![colors2](https://user-images.githubusercontent.com/12100960/153532091-0caa02f9-bb36-4570-98c5-74224261d8b2.jpg)

**Comment by kovidgoyal** [comment]
It is expected and as I said on #2249 as far as I can tell, the color rendering is the *correct* expected color rendering on macOS. Matching the rendering of Wezterm or VSCode or XYZ is not a goal for kitty. Matching the color rendering of the OS is, and it does that already as far as can be determined. Adjusting colors to make X look more like Y will just mean that somebody else complains that A looks less like B. Not a gme I wish to be playing, sorry.

**Comment by kovidgoyal** [comment]
You just revert the srgb patch referenced in the issue, which was a one line patch.

**Comment by typkrft** [comment]
A note just in case anyone stumbles across this.

Setting `glfw/cocoa_window.m` From 
```objc
    [window->ns.object setColorSpace:[NSColorSpace sRGBColorSpace]];
```
to
```objc
    [window->ns.object setColorSpace:[NSColorSpace displayP3ColorSpace]];
```
or simply removing the line all together as mentioned above and in the other thread referenced above and building results in colors matching Wezterm identically and subjectively, but significantly more vibrant colors. It appears that P3 is the default color space that macOS defaults for at least built in displays. 

__A few references :__
- [New Macbook Pro P3 Color Space](https://larryjordan.com/articles/configure-the-new-macbook-pro-to-p3-color-space/)
- [A List of Colorspaces that can be used](https://developer.apple.com/documentation/appkit/nscolorspace/1412071-srgbcolorspace)
- [Explaining macOS Color Gamut](http://www.astramael.com/)
> Apple's target P3 colorspace can cover fewer teals and greens (light shaded area). However, P3 is stronger in yellow-green, yellow, orange, red, and magenta (dark shaded area). If instead we compare P3 to the standard sRGB colorspace, the differences are even more significant

**Comment by jrmoulton** [comment]
> A note just in case anyone stumbles across this.
> 
> Setting the below line in `glfw/cocoa_window.m` From
> 
> ```objc
>     [window->ns.object setColorSpace:[NSColorSpace sRGBColorSpace]];
> ```
> 
> to
> 
> ```objc
>     [window->ns.object setColorSpace:[NSColorSpace displayP3ColorSpace]];
> ```

Ahhh this finally fixed it! Thanks!

**Comment by ciscohack** [comment]
Does anyone knows how to use the macos_colorspace option added in the nightly build 

is this config correct

macos_colorspace    'srgb'
or
macos_colorspace     srgb

**Comment by slve** [comment]
Hi @ciscohack it's `macos_colorspace srgb`
see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_colorspace

**Comment by kovidgoyal** [comment]
On Thu, May 12, 2022 at 10:31:46AM -0700, ciscohack wrote:
> Does anyone knows how to use the macos_colorspace option added in the nightly build 
> 
> is this config correct
> 
> macos_colorspace    'srgb'
> or
> macos_colorspace     srgb


No quotes.
