### ISSUE TITLE
Incompatibility with bitbake

### ISSUE THREAD

**Issue by jclsn** [kovidgoyal/kitty#4689]
**Describe the bug**
When running Yocto's bitbake I get the follwing message and the bitbake output is not displayed right.

```
$TERM has an unrecognized value of "xterm-kitty". The interactive terminal may not behave appropriately
```

**To Reproduce**
1. Clone [poky](https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html) 
2. Set up the bitbake environment
3. See the error

I can circumvent the issue by setting ``TERM=xterm``, but then colors are broken. 

I think kitty should have a fully functional xterm compatibility mode. All the software in the world will not adjust itself to work with kitty. Kitty must adjust itself to all the other software. Else it will never be fully usable. Like this, I can't use it for work without living with complications or broken features.

**Comment by jclsn** [comment]
And I think that you know perfectly well what I mean. xterm-kitty has features that xterm has not and vice versa. If you xterm-kitty you run into issues like this, which you obviously don't care about. Then, if people just use xterm, you warn them that other things might break. So whatever you choose, you will have breakage.

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.term

> ... Changing this can break many terminal programs,
> only change it if you know what you are doing, ...

```shell
kitty -o term=xterm-256colors ssh legacy-device
```

This already exists and has been warned in the docs. What else do you want.

**Comment by jclsn** [comment]
I read all of that and there is no SSH involved in this case. This is also not "some program", but Yocto which is the leading embedded Linux build system. I will investigate though and ask others in that project if they have the same issue or if it can be fixed from bitbake's side.

I am just wondering what the need for ``xterm-kitty`` is in the first place. It must have some more advanced features. I have not realized any broken features using ``xterm-256color`` so far.
