### ISSUE TITLE
--detach option removed?

### ISSUE THREAD

**Issue by eirikrye** [kovidgoyal/kitty#4690]
Hello,

Running kitty 0.24.2 installed using macOS Homebrew (`brew install kitty`). I am trying to set up a session that I may launch from the command line. Currently, using `kitty --session <session>`, the launching terminal will remain blocked until the launched kitty instance quits, and closing the terminal will kill the child instance.

There are mentions of a `--detach` flag in the documentation for older versions, as well as in some issues here from last year. Was this option removed?

```
rye@w ~ % kitty --version
kitty 0.24.2 created by Kovid Goyal
rye@w ~ % kitty --session session.conf --detach
Unknown option: --detach
```

**Comment by kovidgoyal** [comment]
--detach is linux only. If you want to launch a GUI app from a shell in
general, do

kitty & disown

**Comment by kovidgoyal** [comment]
And since you are on macOS, the macOS native way to do it is

open -a kitty.app

**Comment by ecerulm** [comment]
For reference, on macOS  if you use the  `open -a kitty.app`  to pass arguments like `--session xxxx` you need to use `--args` like so: 

`open -a kitty.app -n --args --session session.conf` 

`-n` wil open a new instance of the application even if one is already running 
`--args` to pass arguments to kitty itself.
