### ISSUE TITLE
Mac OS: Standard "Cycle Thru Windows" Command Doesn't Work

### ISSUE THREAD

**Issue by atomdmac** [kovidgoyal/kitty#4693]
**Describe the bug**
Previously, using `` CMD+` `` to cycle through OS windows worked with Kitty.  As of the latest release, pressing this key combo causes the input `9;9u` to appear at the prompt.

This may be less of a bug and more of a recent feature change.  I'd be happy to simply provide my own mapping (something like `map cmd+` `` next_os_window`) but I don't believe there is a "next/previous OS window" command currently.

**To Reproduce**
1. Open 2 separate OS windows in Kitty
2. Attempt to cycle thru them using `` cmd+` ``
3. Notice that window focus does not change.

**Screenshots**

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Darwin Adams-MBP.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/amacumber/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close            1
enable_audio_bell                  False
enabled_layouts                    ['splits']
font_family                        Hasklug NF
font_size                          14.0
macos_option_as_alt                3
macos_quit_when_last_window_closed True
scrollback_lines                   4000
tab_bar_edge                       1
tab_bar_style                      slant
visual_bell_duration               0.25
window_margin_width                FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
Added shortcuts:
	cmd+d → detach_tab ask
	cmd+f → launch --type=overlay --stdin-source=@screen_scrollback less
	cmd+left → neighboring_window left
	cmd+right → neighboring_window right
	shift+cmd+f → launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i
Changed shortcuts:
	cmd+1 → goto_tab 1
	cmd+2 → goto_tab 2
	cmd+3 → goto_tab 3
	cmd+4 → goto_tab 4
	cmd+5 → goto_tab 5
	cmd+6 → goto_tab 6
	cmd+7 → goto_tab 7
	cmd+8 → goto_tab 8
	cmd+9 → goto_tab 9
	cmd+n → new_os_window_with_cwd
	cmd+up → neighboring_window up
	cmd+down → neighboring_window down
Colors:
	background                         #333333   
	inactive_border_color              #000000   

Environment variable names seen by the kitty process:
	COMMAND_MODE
	HOME
	LANG
	LOGNAME
	PATH
	SHELL
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	TMPDIR
	USER
	XPC_FLAGS
	XPC_SERVICE_NAME
	__CFBundleIdentifier
	__CF_USER_TEXT_ENCODING

```

**Additional context**
Was able to reproduce with a blank `kitty.conf`.

**Comment by page-down** [comment]
Open `System Preferences`, Keyboard, Shortcuts, Keyboard.
Disable and enable `Move focus to next window`.

https://github.com/kovidgoyal/kitty/issues/4657

**Comment by aron-bordin** [comment]
as a reference for anyone facing this issue, for me, disabling and enabling the shortcut didn't work, I had to map it to a different keystroke and then map it to cmd+` again

**Comment by page-down** [comment]
@aron-bordin
This issue has been fixed in a later release.
Are you still experiencing this in the latest version?

**Comment by aron-bordin** [comment]
Hi @page-down, I'm using 0.25.0 and I was experiencing this issue :/ I had to re-map the keystroke to get it working. It is working now, so I'm no longer able to reproduce the issue, so no idea what happened here. 
And as I said, disabling and enabling the shortcut didn't work for me, I had to re-map the shortcut to get it working.

**Comment by d96litz** [comment]
@aron-bordin how did you manage to remap the keys without third party plugin? I still experience the issue 😢

**Comment by fcanedo** [comment]
@d96litz, if you double-click on the shortcut, it allows you to change it.
