### ISSUE TITLE
Kitty not displaying bold text anymore

### ISSUE THREAD

**Issue by PoisonFrog** [kovidgoyal/kitty#4696]
Okay this is a very stupid, but I was playing around with my fonts using the font manager (I wasn't editing them or anything, just reinstalling some fonts) but then all of a sudden my terminal was not displaying bold fonts anymore. I don't know what I did and I don't know how to fix it. This is only affecting kitty.  I didn't edit anything in kitty.conf I even deleted the configuration file but the new one didn't fix it. I know this is a stupid issue but I really don't know how to fix it.

**Comment by kovidgoyal** [comment]
--debug-font-fallback to use which fonts are used. And you might need
to specify bold_font manually if whatever you did ispreventing
auto-detection of a bold face.

**Comment by jtrees** [comment]
@PoisonFrog I came to report the same thing but worked around it with the following config:

```
font_family      Fira Code
bold_font        auto
italic_font      auto
bold_italic_font auto
```

Interestingly, replacing `Fira Code` with `monospace` causes the same regular font to be used, but the bold font breaks that way. Omitting the config entirely also leads to the broken behaviour.

It might be related to NixOS doing funky things with fonts. When I run `kitty --debug-font-fallback`, I get this, regardless of my config:

```
U+21e1 Face(family=FreeSerif, style=Regular, ps_name=FreeSerif, path=/nix/store/y1hybm8h1kln0hg06c42m4g1wsblc0ig-freefont-ttf-20120503/share/fonts/truetype/FreeSerif.ttf, index=0, is_scalable=True, has_color=False, ascender=900, descender=-200, height=1200, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
U+276f Face(family=FreeSerif, style=Regular, ps_name=FreeSerif, path=/nix/store/y1hybm8h1kln0hg06c42m4g1wsblc0ig-freefont-ttf-20120503/share/fonts/truetype/FreeSerif.ttf, index=0, is_scalable=True, has_color=False, ascender=900, descender=-200, height=1200, underline_position=-150, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
```

**Comment by sethlivingston** [comment]
I had the same problem, but restarting Kitty (not just reloading the config) fixed it.
