### ISSUE TITLE
Kitty takes very long to load

### ISSUE THREAD

**Issue by EysseW** [kovidgoyal/kitty#4697]
Hi, I have recently been starting to use kitty. Since a very short while ago, tho, it has started to launch very very slow. I am talking 3 seconds. Other terminal applications launch really quickly. I have done some reseach myself already. You guys told these people to use --single-instance. That does absolutely nothing for me. Could you help me?

**Comment by kovidgoyal** [comment]
I dont see how its possible for --single-instance to do nothing.
--single-instance means a new window is opening in an existing process.
And as for slow starts it will be because of GPU power management
issues, as mentioned in the kitty FAQ

**Comment by EysseW** [comment]
If that's the case, then how come it worked flawlessly before?

**Comment by EysseW** [comment]
As a side note, the FAQ solutions didnt help at all and I can't help the fact you don't see how --single-instance doesn't work. I am not trying to be cocky, but I have the feeling you are marking my issue as 'once again a user too lazy to figure things out himself', which is just not the case.

**Comment by page-down** [comment]
Not sure how I can help you, too little information provided.

Overall you need to rule out hardware, system environment ...  make sure it's not caused by other factors first. For example, have you tried booting from a livecd system and then installing kitty?

**Comment by EysseW** [comment]
Thanks for being nice. I went ahead and tried some things. I was able to move the old config file and create a new one. However, it would be useful to know what caused the issue.

**Comment by page-down** [comment]
You didn't give your original configuration. I'm sure you can figure out why.

**Comment by EysseW** [comment]
> You didn't give your original configuration. I'm sure you can figure out why.

Yeah, see, the problem there is that I am not able to access the config file of my old kitty instance. Even nat with a different terminal emulator.
