### ISSUE TITLE
Mouse right click actuates both on press and release

### ISSUE THREAD

**Issue by ryanrms** [kovidgoyal/kitty#4698]
**Describe the bug**
My setup:  kitty running in a Kinoite (Fedora Silverblue 35, but KDE) toolbox, and running ncmpcpp to interface with mpd everything running inside the same toolbox.
I specify ncmpcpp because it is the only ncurses program I have that interacts with a right click, namely, a right click on the playlist should play a track, and centre the display around the track.  On Konsole (host), entering the toolbox and running ncmpcpp the right click works as expected, which is simply to play the track, with no action on release.  However, on kitty, it first starts playing the track when you click, and then the screen moves as expected, but then when you release the "click" event actuates again, playing a song you didn't mean to click on.  This also happens when clicking on the text towards the bottom left of the terminal that says "Playing:" - clicking this should pause playback, but clicking and releasing with the left mouse button actuates on both press AND release, causing the track to pause only for the length the mouse is clicked in (unless the mouse is moved and clicks elsewhere)

**To Reproduce**
1. Install kitty (possibly related to running in the toolbox?)
2. run the Music Player Daemon (mpd) audio setup not really required as long as you can see the "wrong" track is being played
3a. run ncmpcp and create a playlist with a >1 page list of tracks (easy to do if you have tracks in the library with \` s 50 Enter)
4a. Right click to play a song in the middle of the playlist
5a. See error

3b. Start playing a song
4b. left click where it says "Playing" on the bottom left
5b. See error

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux toolbox 5.16.7-200.fc35.x86_64 #1 SMP PREEMPT Sun Feb 6 19:53:54 UTC 2022 x86_64
S
Kernel 5.16.7-200.fc35.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /var/home/rdr/.config/kitty/kitty.conf

Config options different from defaults:
bold_font               Source Code Pro Bold
cursor_text_color       None
font_family             Source Code Pro Regular
font_size               10.0
window_margin_width     FloatEdges(left=30.0, top=30.0, right=30.0, bottom=30.0)
Colors:
	active_tab_background   #f8f8f2   
	active_tab_foreground   #282a36   
	background              #2f343f   
	color0                  #21222c   
	color1                  #ff5555   
	color10                 #69ff94   
	color11                 #ffffa5   
	color12                 #d6acff   
	color13                 #ff92df   
	color14                 #a4ffff   
	color2                  #50fa7b   
	color3                  #f1fa8c   
	color4                  #bd93f9   
	color5                  #ff79c6   
	color6                  #8be9fd   
	color7                  #f8f8f2   
	color8                  #6272a4   
	color9                  #ff6e6e   
	cursor                  #f8f8f2   
	foreground              #f8f8f2   
	inactive_tab_background #6272a4   
	inactive_tab_foreground #282a36   
	mark1_background        #ff5555   
	mark1_foreground        #282a36   
	selection_background    #44475a   
	selection_foreground    #ffffff   
	url_color               #8be9fd   

Environment variable names seen by the kitty process:
	DBUS_SESSION_BUS_ADDRESS
	DESKTOP_SESSION
	DISPLAY
	DISTTAG
	FGC
	HOME
	HOSTNAME
	LC_CTYPE
	NAME
	PATH
	PWD
	SHELL
	SHLVL
	SSH_AUTH_SOCK
	TERM
	TOOLBOX_PATH
	USER
	VERSION
	WAYLAND_DISPLAY
	XAUTHORITY
	XDG_CURRENT_DESKTOP
	XDG_DATA_DIRS
	XDG_MENU_PREFIX
	XDG_RUNTIME_DIR
	XDG_SEAT
	XDG_SESSION_DESKTOP
	XDG_SESSION_ID
	XDG_SESSION_TYPE
	XDG_VTNR
	container
```

**Additional context**
I was able to reproduce it with kitty --config NONE as well, but I'm wondering if there's a mouse setting I can change as I don't really understand them.

**Comment by kovidgoyal** [comment]
Terminal mouse protocols have no click events. Only press and release. the click event is an internal event used by kitty, it is not sent to terminal programs. If you need to test mouse interaction with terminal programs use:

kitty --debug-input kitty +kitten mouse_demo

Your --debug-input output is exactly as expected. There is a press and a release and the pair of press and release are treated as a click.  And it has a grabbed: 0 which indicates ncmcpp is not asking for mouse events (assuming you were running it when you generated that trace). So I have no idea how it is supposed to respond to a right click.

As for unmapping them, you need to use discard_event not no-op.no-op means dont perform any kitty action, the event will thus be sent to the terminal program. If you dont want the terminal program to receive an event, use discard_event.

**Comment by ryanrms** [comment]
Thanks for the quick response, I was using debug in a normal kitty window with nothing running, that's why it said "ungrabbed", you're correct in thinking that the ncmpcpp program "grabs" the mouse clicks.

```
mouse_map right release grabbed,ungrabbed discard_event
mouse_map left release grabbed,ungrabbed discard_event
```

Seems to provide the behaviour that I am used to, where a click actuates the event and the release does nothing.  Perfect! Thank you for your help.
