### ISSUE TITLE
Question: which characters are rendered by kitty rather than from the font?

### ISSUE THREAD

**Issue by xsrvmy** [kovidgoyal/kitty#4700]
I know about box drawing, but are there anything else? I wonder if this should be documented.

The reason I am asking is that the prompt character from zsh looks way thinner on kitty for some reason.

**Comment by kovidgoyal** [comment]
The only characters rendered by kitty are in box_drawing.py

**Comment by xsrvmy** [comment]
My mistake. I was comparing two different versions of a font.
