### ISSUE TITLE
Touchpad scrolling does not scale with monitor scale

### ISSUE THREAD

**Issue by xsrvmy** [kovidgoyal/kitty#4703]
The handling for touchpad scrolling in `mouse.c` uses the line height in physical pixels, which means scrolling is slower on hidpi screens. This is especially apparent in mixed dpi environments using wayland. It was mentioned in another issue that this might not be as obvious on macOS, but that might be due to the way macOS handles mixed dpi rendering.

The better way to handle this is probably to divide the line height by the monitor scale.

(Note: I am using dpi and scale interchangably. Kitty doesn't seem to respect dpi on X anyways.)

**Comment by xsrvmy** [comment]
This is a density-dependent pixel vs physical pixel problem. A touchpad's input is based on physical length, which means it should be mapped to density-dependent pixels, but the code in `mouse.c` uses physical pixels from the cell rendering instead.

BTW, the number reported by wayland is just some arbitrary unit of measurement, not pixels. For example a mouse wheel scroll sends 15 which is actually in degrees.

Regarding Xft.dpi, does kitty only read .Xresources and not .Xdefaults or something? Because I do have Xft.dpi set to 192.

**Comment by xsrvmy** [comment]
I don't know what QT does, but alacritty uses winit which scales the pixel size of the input event before it even reaches alacritty. I'm guessing wayland expects this hidpi conversion to be handled by the windowing library. So if we want to do the equivalent, it would be done in `wl_init.c` in glfw again.

**Comment by kovidgoyal** [comment]
From https://github.com/qt/qtwayland/blob/e68f0f05daca454a2c793c5862b78f78d100a805/src/client/qwaylandinputdevice.cpp

as far as I can tell Qt does not scale the pixels.

**Comment by kovidgoyal** [comment]
And just for giggles I did some related reading and apparently axis_discrete is going to be deprecated: https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/72  

Coming to this issue, I think it is OK to scale the pixels if the following is true: Does the same motion produce the same event stream from the compositor regardless of the scale of the current monitor? It would be good to be able to test this with at least a couple of major wayland compositors. If it is true they I guess we need to scale in application code.

**Comment by xsrvmy** [comment]
I can't actually tell exactly what konsole is doing actually. It seems like it might be doing something with QT's scrollbar though which presumably uses density-dependent pixels already.

Whether this should be handled by the application or the windowing/ui library is really a matter of convention I think. Handling it it in glfw is actually very easy for wayland, and I have no idea if macOS actually needs this fix. The only possible concern is the recent change to ignore the touch multiplier for alternate mouse control which could make the touchpad way too slow.

**Comment by xsrvmy** [comment]
"Does the same motion produce the same event stream from the compositor regardless of the scale of the current monitor?"

I'm getting slower scrolling on my hi dpi screen when testing on gnome (with and without frame buffer scaling), KDE and sway, so I believe yes.

**Comment by page-down** [comment]
> Someone with mixed monitors on macOS needs to check there what the behavior is.

Under macOS, scrolling speed is consistent across different DPI screens using Trackpad (or mouse) and everything works fine.
Any changes should not affect the way macOS works now.

One question, using the mouse wheel under macOS, a single scroll is always one scrollback row.
The scroll multiplier only affects the scroll acceleration.
I wonder if I can set it to scroll three scrollback rows in one scroll. However, my scrolling has acceleration, so it is not very needed.

This is the only problem about scrolling under macOS, in my opinion.

**Comment by kovidgoyal** [comment]
On Sun, Feb 13, 2022 at 09:15:11AM -0800, Rui Ming (Max) Xiong wrote:
> "Does the same motion produce the same event stream from the compositor regardless of the scale of the current monitor?"
> 
> I'm getting slower scrolling on my hi dpi screen when testing on gnome (with and without frame buffer scaling), KDE and sway, so I believe yes. 

OK then feel free to send a PR scaling it in wl_init.c

**Comment by kovidgoyal** [comment]
On Sun, Feb 13, 2022 at 05:33:18PM -0800, page-down wrote:
> > Someone with mixed monitors on macOS needs to check there what the behavior is.
> One question, using the mouse wheel under macOS, a single scroll is always one scrollback row.
> The scroll multiplier only affects the scroll acceleration.
> I wonder if I can set it to scroll three scrollback rows in one scroll. However, my scrolling has acceleration, so it is not very needed.

What is one scroll here? Is this with a wheel with clicks?

**Comment by page-down** [comment]
> What is one scroll here? Is this with a wheel with clicks?

Yes, scroll wheel with clicks.

**Comment by xsrvmy** [comment]
That's a different issue I think.
There is a comment in the code about mouse generating very small scrolling events, but the scaling is applied before that.

**Comment by kovidgoyal** [comment]
On Sun, Feb 13, 2022 at 05:47:40PM -0800, page-down wrote:
> > What is one scroll here? Is this with a wheel with clicks?
> 
> Yes, scroll wheel with clicks.

You can probably fix this at line 893 in mouse.c by using the scale
value instead of 1 and -1
