### ISSUE TITLE
Chinese characters too small

### ISSUE THREAD

**Issue by skysky97** [kovidgoyal/kitty#4707]
**Describe the bug**
Chinese characters are much more smaller than those in gnome-terminal.

**Screenshots**
![IMG_20220214_142347](https://user-images.githubusercontent.com/18086458/153812930-43b6450c-0365-455d-86f2-d7fd6826513a.jpg)
![IMG_20220214_142308](https://user-images.githubusercontent.com/18086458/153812936-d9efba43-1ed2-4f1f-9889-506b4f2c7411.jpg)

**Environment details**
kitty 0.24.1 (2151969ae5) created by Kovid Goyal
Linux ubuntu 5.4.0-26-generic

**Additional context**
Try to reproduce the problem with `kitty --config NONE`, the same problem.

**Comment by kovidgoyal** [comment]
How big they are depends on the font used for them. Pick a different
font for chinese characters using the symbol_map directive in
kitty.conf, or using fontconfig.

**Comment by skysky97** [comment]
I have only 'noto' font installed. I don't know which font gnome-terminal actually used. Can you help me? @kovidgoyal

**Comment by kovidgoyal** [comment]
If its the same font then its most likely that gnome terminal is rendering it at a higher font size. kitty scales fallback fonts so that their reported height fits within the cell height. You can try using adjust_line_height in kitty.conf to increasethe cell height.

**Comment by skysky97** [comment]
Increasing the cell height does help. But it wastes some space...

**Comment by page-down** [comment]
I can reproduce the issue.

Some (e.g. Noto) two character width fonts used with mono fonts (e.g. Hack, the OS default one) are particularly small at standard font size (e.g. font_size=10).
Although it seems to have a very sufficient height.

The font combination works fine in Konsole, filling the entire line height.
I don't have this problem in macOS, it is pretty well filled.

**Comment by kovidgoyal** [comment]
Yeah, there isn't much that can be done about that, essentially one would
need to fine tune the metrics of the involved fonts to make them more
compatible. In theory I could add a config parameter to do this in
kitty, maybe some rainy day.
