### ISSUE TITLE
add an option to install kitty terminfo only

### ISSUE THREAD

**Issue by invakid404** [kovidgoyal/kitty#4715]
**Is your feature request related to a problem? Please describe.**
In the Gentoo/Funtoo world, we split kitty into two packages: kitty and kitty-terminfo. The reason is that we want to be able to install the kitty terminfo in headless environments, without having to pull in the entirety of kitty.

As a maintainer of the kitty packages in Funtoo, it's always frustrating when the patch we use for this breaks on an update since we have to go and do the exact same changes over and over again and make a new patch. I'm hoping that it'd be possible to get this in the upstream setup.py to avoid the frustration.

**Describe the solution you'd like**
We currently have a patch for this ([located here](https://github.com/funtoo/desktop-kit/blob/e3728b99cbd27bd1fdc5d1ab4c2585810e8efb8b/x11-terms/kitty-gen/files/kitty-terminfo-setup-0.23.1.20211001.patch)), it adds a new 'linux-terminfo' target which handles the terminfo building and installing. I suppose it wouldn't be a problem to upstream it since it's not a massive change.

**Describe alternatives you've considered**
I've tried fixing the patch every time it breaks, it's annoying :)

**Additional context**
BTW, forgive me if this has been discussed/rejected before, I skimmed through the existing issues and couldn't find anything.

**Comment by kovidgoyal** [comment]
Oh and if the problem is that you cant use build-terminfo because kitty doesnt exist when packaging kitty-terminfo, then simply call tic yourself on terminfo/kitty.terminfo.

Also note that you should nowadays have a kitty-shell-integration package as well. See https://sw.kovidgoyal.net/kitty/build/#notes-for-linux-macos-packagers

**Comment by invakid404** [comment]
Ah, that's even better! Forgive my ignorance, we inherited this way of installing the terminfo from Gentoo and we thought it's absolutely required to build it before installing it. I'll fix our ebuilds shortly.

**Comment by invakid404** [comment]
> Also note that you should nowadays have a kitty-shell-integration package as well. See https://sw.kovidgoyal.net/kitty/build/#notes-for-linux-macos-packagers

Alright, noted. I guess this issue can be closed now. Thanks for the quick response :)
