### ISSUE TITLE
Disabling MonoLisa ligatures but keep calt makes contextual alternatives small

### ISSUE THREAD

**Issue by nickwynja** [kovidgoyal/kitty#4721]
**Describe the bug**
As mentioned in the docs, I'd like to "Disable the normal ligatures, but keep the `calt` feature" for MonoLisa.

**To Reproduce**
Minimal config to reproduce the behavior:

```
font_family       MonoLisa
font_features MonoLisa-Regular -liga +calt
```

When using `font_features MonoLisa-Regular +calt`, this is how `[|` (calt) and `-->` (ligature) render:

<img width="133" alt="image" src="https://user-images.githubusercontent.com/1012017/154808617-9bcd7e7c-bf29-48cb-bf76-6b3e315e99b8.png">

But I'd like to remove the ligatures and only use the contextual alternatives with `font_features MonoLisa-Regular +calt -liga`:

<img width="77" alt="image" src="https://user-images.githubusercontent.com/1012017/154808524-811ebeef-88b7-4d68-b9dc-105e3ed5e884.png">

This appropriately disables the ligature but incorrectly sizes the contextual alternatives.

Likewise for `###` the three character calt shrinks in one cell:

<img width="49" alt="image" src="https://user-images.githubusercontent.com/1012017/154809368-13aabd4d-a7ba-429f-be2d-9b494ea0f437.png">

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Darwin Nicks-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H1323
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/nick/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style              (True, False)
allow_remote_control               y
click_interval                     0.25
cursor_blink_interval              0.0
enable_audio_bell                  False
enabled_layouts                    ['tall', 'stack']
font_family                        MonoLisa
font_features:
{'MonoLisa-Regular': ('+liga',)}
hide_window_decorations            1
macos_option_as_alt                3
macos_quit_when_last_window_closed True
mouse_hide_wait                    -1.0
scrollback_pager                   ['/Users/nick/.dotfiles/bin/scrollb']
shell                              zsh
shell_integration                  frozenset({'disabled'})
single_window_margin_width         FloatEdges(left=2.0, top=0.0, right=2.0, bottom=0.0)
startup_session                    /Users/nick/.config/kitty/./startup.conf
strip_trailing_spaces              smart
tab_bar_style                      separator
tab_separator                      
tab_title_template                   {title}  
touch_scroll_multiplier            0.0
url_style                          1
wheel_scroll_multiplier            0.0
window_alert_on_bell               False
Added shortcuts:
	opt+j → combine : nth_window -1 : send_text all j : nth_window -1
	opt+k → combine : nth_window -1 : send_text all k : nth_window -1
	ctrl+\ → nth_window -1
	ctrl+h → kitten pass_keys.py neighboring_window left   ctrl+h
	ctrl+j → kitten pass_keys.py neighboring_window bottom ctrl+j
	ctrl+k → kitten pass_keys.py neighboring_window top    ctrl+k
	ctrl+l → kitten pass_keys.py neighboring_window right  ctrl+l
	ctrl+z → toggle_layout stack
	cmd+\ → goto_tab -1
	cmd+b → launch --copy-colors --type tab ~/.dotfiles/kitty/switch.sh
	shift+cmd+b → launch --copy-colors --type tab ~/.dotfiles/kitty/view.sh
	shift+cmd+e → launch --type overlay zsh -c "echo 'enter event: (event description, natural datetime, optional duration)'; read INPUT; ~/.dotfiles/bin/event $INPUT;"
	shift+cmd+f → launch --type background hl "@selection"
	shift+cmd+g → launch --copy-env --type background zsh ~/.dotfiles/kitty/views/gmail.sh
	shift+cmd+h → show_scrollback
	shift+cmd+j → scroll_line_down
	shift+cmd+k → scroll_line_up
	shift+cmd+m → launch --copy-env --type background zsh ~/.dotfiles/kitty/views/mutt.sh
	shift+cmd+t → launch --type tab --title twin zsh ~/.dotfiles/taskwarrior/in.sh
	shift+cmd+u → scroll_page_up
	shift+cmd+left → resize_window narrower
	shift+cmd+right → resize_window wider
	ctrl+cmd+s → launch --type overlay zsh ~/.dotfiles/bin/yinyang
	ctrl+cmd+t → launch --type overlay
	ctrl+cmd+w → launch --type overlay --title 'fzf: wiki' ~/.dotfiles/kitty/wiki-lookup.sh
Changed shortcuts:
	ctrl+shift+up → resize_window taller
	ctrl+shift+down → resize_window shorter 3
	cmd+enter → launch --cwd current
Colors:
	active_border_color                #268bd2   
	active_tab_background              #93a1a1   
	active_tab_foreground              #fdf6e3   
	background                         #fdf6e3   
	color0                             #073642   
	color1                             #dc322f   
	color10                            #586e75   
	color11                            #657b83   
	color12                            #839496   
	color13                            #6c71c4   
	color14                            #93a1a1   
	color15                            #fdf6e3   
	color155                           #eee8d5   
	color2                             #859900   
	color255                           #93a1a1   
	color3                             #b58900   
	color4                             #268bd2   
	color5                             #d33682   
	color6                             #2aa198   
	color7                             #eee8d5   
	color8                             #002b36   
	color9                             #cb4b16   
	cursor                             #839496   
	cursor_text_color                  #fdf6e3   
	foreground                         #657b83   
	inactive_border_color              #93a1a1   
	inactive_tab_background            #eee8d5   
	inactive_tab_foreground            #93a1a1   
	selection_background               #475b62   
	selection_foreground               #eae3cb   
	tab_bar_background                 #eee8d5   

Environment variable names seen by the kitty process:
	BAT_THEME
	COMMAND_MODE
	FZF_DEFAULT_OPTS
	HOME
	KITTY_LISTEN_ON
	LANG
	LOGNAME
	LaunchInstanceID
	PATH
	SECURITYSESSIONID
	SHELL
	SOLR_PROFILE
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	TMPDIR
	USER
	XPC_FLAGS
	XPC_SERVICE_NAME
	__CF_USER_TEXT_ENCODING
```

**Comment by kovidgoyal** [comment]
I'm not sure what you expect kitty to do here. It can turn on/off the features in the font. It cant control howthe font chooses to render things after those features are toggled.

**Comment by nickwynja** [comment]
My expectation is that `liga` and `calt` can be toggled separately and have the respective font feature work independently of the other feature. This screenshot shows how MonoLisa supports independently toggling `liga` and `calt` in HTML and CSS:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1012017/154849300-643a7c9e-3b43-4b0b-a5b5-8aafee74ab5d.png">

```html
<style>
p {
font-family: "MonoLisa";
}
</style>

<p style="font-feature-settings: 'calt' 1; font-feature-settings: 'liga' 0;">
calt 1 liga 0: ==> [| ###
</p>

<p style="font-feature-settings: 'liga' 1; font-feature-settings: 'calt' 0;">
liga 1 calt 0: ==> [| ###
</p>

<p style="font-feature-settings: 'liga' 1;">
liga 1 calt _: ==> [| ###
</p>
```

The first line of the above screenshot is my expected outcome when using `font_features   MonoLisa-Regular -liga +calt
`.

This gif shows the unexpected small or shrinking issue better than the previous screenshots:

![Kapture 2022-02-20 at 08 56 03](https://user-images.githubusercontent.com/1012017/154849357-bd1ab055-c059-43c2-80bf-683f007fa655.gif)

Seeing how kitty is able to render the calts properly when `+liga` is on, I'd expect the same to be possible when `-liga +calt` but just independently toggle off ligatures:

![Kapture 2022-02-20 at 09 00 37](https://user-images.githubusercontent.com/1012017/154849486-0547407b-60fa-4f88-9d90-5aad8c20751e.gif)

**Comment by kovidgoyal** [comment]
Sorry, I am not particularly interested in debugging this font with this usage scenario, it's getting a little too specific to be worth my time. Patches are welcome, relevant rendering code is in fonts.c. I'd guess that turning off liga causes harfbuzz shaping to report the calt ligatures as a single character rather than three characters. And since kitty fits single characters into single cells, they are getting resized to fit in a cell.

**Comment by nickwynja** [comment]
Thanks for pointing me in the right direction! I figured out where the issue lies but could use some direction on a solution.

https://github.com/kovidgoyal/kitty/blob/dac9b07f1630ded42e7d2113e38462e34fd2954e/kitty/fonts.c#L828-L854

`detect_spacer_strategy` uses `===` to check for how the harfbuzz has rendered the ligature and then uses that strategy throughout all renderings. In this case where I have ligatures off but contextual alternatives on, `===` renders 'normally' so uses the default `font->spacer_strategy = SPACERS_BEFORE;` 

If, for example, I change `detect_spacer_strategy` to check `###`, the correct spacer strategy is determined and `calts` render properly while `-liga -dlig`. 

`===` seems like a common ligature so changing the check to `###` seems like it wouldn't cover as many cases. I could repeat a check on `###` after the check on `===` to see if it's any different to cover more cases but that seems repetitive. Changing the default `font->space_strategy` to `SPACERS_AFTER` seems like another option but I don't know how commonly fonts use spaces after versus before for ligatures.

Happy to submit a patch but would like to confer on a strategy first.

**Comment by kovidgoyal** [comment]
It should be fine to fallback to using ### if === is not a ligature in
the font.
