### ISSUE TITLE
Can't select trailing newline

### ISSUE THREAD

**Issue by stephentalley** [kovidgoyal/kitty#4724]
**Describe the bug**
In other terminals I've worked with (alacritty, urxvt, xterm), I am able to include a trailing newline in my selection using any of the standard mechanisms (mouse drag, right click, etc.). The terminal indicates that the trailing newline is part of the selection by extending the selection color to the end of the terminal line.

But in kitty the trailing newline of the last line in the selection is never included in the selected text, no matter what. This means, for example, that when pasting a command from one terminal to another, I have to hit enter after the paste. If I copy from other terminals, the newline is included and I don't have to manually add it after pasting.

**To Reproduce**
The attached images show attempts to select the trailing newline in a drag-to-select gesture.

**Screenshots**
With urxvt:
![urxvt-include-trailing-newline](https://user-images.githubusercontent.com/3507182/154817597-cb0b65af-a241-4024-8664-c4395c94ea0c.gif)

With kitty:
![kitty-include-trailing-newline](https://user-images.githubusercontent.com/3507182/154817757-e7f15f86-b148-44de-8a44-ea819b785bec.gif)

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux myhost 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64
Ubuntu 20.04.4 LTS myhost /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/me/dist/Linux/x86_64/ubuntu/20.04/pkgs/kitty-0.24.2/bin/kitty
  base dir: /home/me/dist/Linux/x86_64/ubuntu/20.04/pkgs/kitty-0.24.2/lib/kitty
  extensions dir: /home/me/dist/Linux/x86_64/ubuntu/20.04/pkgs/kitty-0.24.2/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/me/.config/kitty/kitty.conf
Loaded config overrides:
  initial_window_width 100c
  initial_window_height 27c
```

**Additional context**
This is reproducible running `kitty --config NONE`.

Is there an option to control this? Apologies if I've missed something in the docs.

**Comment by kovidgoyal** [comment]
This is by design. I absolutely dont want pasting to run a command
without a chance to check if the pasted command is correct.

**Comment by stephentalley** [comment]
Could we maybe have an option, for folks that expect/prefer a different behavior?

**Comment by kovidgoyal** [comment]
Not something I care about, but patches are welcome to add an option.
