### ISSUE TITLE
Triple-click doesn't include leading/trailing whitespace in selection

### ISSUE THREAD

**Issue by stephentalley** [kovidgoyal/kitty#4725]
**Describe the bug**
In other terminals I've worked with (alacritty, urxvt, xterm), triple-clicking a  line includes any leading or trailing whitespace (including [newline](https://github.com/kovidgoyal/kitty/issues/4724)) in my selection:

![urxvt-triple-click](https://user-images.githubusercontent.com/3507182/154818154-18fe864b-ae12-435f-829c-546c30f1d95f.gif)

But in kitty, leading/trailing whitespace is not included in the selected text on triple click:

![kitty-triple-click](https://user-images.githubusercontent.com/3507182/154818160-aa3c1da8-2568-4937-9d8d-b30541316dd1.gif)

Oddly, if I select multiple lines with triple-click, the first line lacks the leading whitespace, and the last line lacks the trailing whitespace. This means when I paste the selection, those lines aren't aligned with each other:

![screenshot-2022 02 19 15 39 33](https://user-images.githubusercontent.com/3507182/154818300-e3050144-53f6-43df-a88a-29073e9145f1.png)

**To Reproduce**
The attached images show attempts to select the full line with triple click, using urxvt and kitty.

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux myhost 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64
Ubuntu 20.04.4 LTS myhost /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/me/dist/Linux/x86_64/ubuntu/20.04/pkgs/kitty-0.24.2/bin/kitty
  base dir: /home/me/dist/Linux/x86_64/ubuntu/20.04/pkgs/kitty-0.24.2/lib/kitty
  extensions dir: /home/me/dist/Linux/x86_64/ubuntu/20.04/pkgs/kitty-0.24.2/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/me/.config/kitty/kitty.conf
Loaded config overrides:
  initial_window_width 100c
  initial_window_height 27c
```

**Additional context**
This is reproducible running `kitty --config NONE`.

Is there an option to control this? Apologies if I've missed something in the docs.

**Comment by kovidgoyal** [comment]
On Sat, Feb 19, 2022 at 12:43:10PM -0800, Stephen Talley wrote:
> **Describe the bug**
> In other terminals I've worked with (alacritty, urxvt, xterm), triple-clicking a  line includes any leading or trailing whitespace (including [newline](https://github.com/kovidgoyal/kitty/issues/4724)) in my selection:

This is by design.


> 
> ![urxvt-triple-click](https://user-images.githubusercontent.com/3507182/154818154-18fe864b-ae12-435f-829c-546c30f1d95f.gif)
> 
> But in kitty, leading/trailing whitespace is not included in the selected text on triple click:

Yes, why would you want it to be?

> 
> ![kitty-triple-click](https://user-images.githubusercontent.com/3507182/154818160-aa3c1da8-2568-4937-9d8d-b30541316dd1.gif)
> 
> Oddly, if I select multiple lines with triple-click, the first line lacks the leading whitespace, and the last line lacks the trailing whitespace. This means when I paste the selection, those lines aren't aligned with each other:

Indeed, if you want to select an aligned block you use rectangular
selection (press ctrl+alt while selecting). https://sw.kovidgoyal.net/kitty/overview/#mouse-features

**Comment by stephentalley** [comment]
Thanks for the quick reply.

> > But in kitty, leading/trailing whitespace is not included in the selected text on triple click:
>
> Yes, why would you want it to be?

Because I want to preserve it wherever I paste. Copying/pasting text from one document to another, for example. I'd like to retain the indent and trailing newlines.

> > Oddly, if I select multiple lines with triple-click, the first line lacks the leading whitespace, and the last line lacks the trailing whitespace. This means when I paste the selection, those lines aren't aligned with each other:
>
> Indeed, if you want to select an aligned block you use rectangular selection (press ctrl+alt while selecting).

Holding modifier keys and dragging a precise rectangular block defeats the simplicity of triple-clicking a line. Plus it appears to add extra whitespace that isn't there, to the end of the selection.

Could we maybe have an option, for folks that expect/prefer a different behavior?

**Comment by kovidgoyal** [comment]
On Mon, Feb 21, 2022 at 08:18:59AM -0800, Stephen Talley wrote:
> Thanks for the quick reply.
> 
> > > But in kitty, leading/trailing whitespace is not included in the selected text on triple click:
> >
> > Yes, why would you want it to be?
> 
> Because I want to preserve it wherever I paste. Copying/pasting text from one document to another, for example. I'd like to retain the indent and trailing newlines.

So after triple clicking right click to extend the selection to where
you want it to be.

> 
> > > Oddly, if I select multiple lines with triple-click, the first line lacks the leading whitespace, and the last line lacks the trailing whitespace. This means when I paste the selection, those lines aren't aligned with each other:
> >
> > Indeed, if you want to select an aligned block you use rectangular selection (press ctrl+alt while selecting).
> 
> Holding modifier keys and dragging a precise rectangular block defeats the simplicity of triple-clicking a line. Plus it appears to add extra whitespace that isn't there, to the end of the selection.
> 
> Could we maybe have an option, for folks that expect/prefer a different behavior?

Again not something I care about, but patches are welcome.

**Comment by SolitudeSF** [comment]
> So after triple clicking right click to extend the selection to where you want it to be.

that still doesnt preserve trailing whitespace
