### ISSUE TITLE
The font I used over the last 3 years is not recognized anymore

### ISSUE THREAD

**Issue by realestninja** [kovidgoyal/kitty#4726]
**Describe the bug**
After a recent system update, my font was changed. I am using the Meslo Nerd Font and I haven't changed anything on my font setup in 3 years. The Meslo Nerd Fonts can be found here: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Meslo/M/Regular/complete

When I look for the font, it shows up as a system font, but kitty can't find it.
```
~ $ fc-list | grep Meslo
/usr/share/fonts/TTF/Meslo LG M Regular Nerd Font Complete.ttf: MesloLGM Nerd Font:style=Regular
~ $ 
```
```
~ $ kitty list-fonts | grep Meslo
~ $ 
```

**To Reproduce**
1.
```
mkdir ~/Downloads/fonts
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf -P ~/Downloads/fonts
sudo cp ~/Downloads/fonts/*.ttf /usr/share/fonts/TTF/
fc-cache
```
2.
```
fc-list | grep Meslo
kitty list-fonts | grep Meslo
```

**Environment details**
Manjaro Linux with the latest updates as of Feb 20th 2022.
```
~ $ kitty -v
kitty 0.24.2 created by Kovid Goyal
```

**Additional context**
I have this line in my kitty.conf since 3 years:
```
font_family MesloLGM Nerd Font
```

I am just thinking: if the Meslo font is not declared as a mono font but kitty only looks for mono fonts, could that be the reason? Or is this more a Manjaro Linux related problem?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by realestninja** [comment]
Thanks! 🙏🏾
I don't know how I missed that. I got it fixed ✌🏾
