### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: '/home/*me*/.config/kitty/kitty.conf/kitty.conf'

### ISSUE THREAD

**Issue by krezefal** [kovidgoyal/kitty#4732]
**Describe the bug**
When I try to launch kitty terminal by entering `kitty` into any terminal, I get the following output:

```
[054 02:14:49.783619] Traceback (most recent call last):
  File "kitty/main.py", line 401, in main
  File "kitty/main.py", line 384, in _main
  File "kitty/cli.py", line 775, in create_opts
  File "kitty/config.py", line 169, in load_config
  File "kitty/conf/utils.py", line 264, in load_config
NotADirectoryError: [Errno 20] Not a directory: '/home/krezefal/.config/kitty/kitty.conf/kitty.conf'
```

**To Reproduce**
1. Input `kitty` to any terminal (check **Additional context** below for some significant info)

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux fedora 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021 x86_64
S
Kernel 5.15.6-200.fc35.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: True
Paths:
  kitty: /home/krezefal/.local/kitty.app/bin/kitty
  base dir: /home/krezefal/.local/kitty.app/lib/kitty
  extensions dir: /home/krezefal/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /home/krezefal/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.9
dynamic_background_opacity True

Environment variable names seen by the kitty process:
	DBUS_SESSION_BUS_ADDRESS
	DEBUGINFOD_URLS
	DESKTOP_SESSION
	DISPLAY
	EDITOR
	GDMSESSION
	GDM_LANG
	GIO_LAUNCHED_DESKTOP_FILE
	GIO_LAUNCHED_DESKTOP_FILE_PID
	GJS_DEBUG_OUTPUT
	GJS_DEBUG_TOPICS
	GNOME_SETUP_DISPLAY
	HISTCONTROL
	HISTSIZE
	HOME
	HOSTNAME
	INVOCATION_ID
	JOURNAL_STREAM
	LANG
	LESSOPEN
	LOGNAME
	MAIL
	MANAGERPID
	MOZ_GMP_PATH
	OLDPWD
	PATH
	PWD
	QT_IM_MODULE
	SESSION_MANAGER
	SHELL
	SHLVL
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	SYSTEMD_EXEC_PID
	USER
	USERNAME
	WAYLAND_DISPLAY
	XAUTHORITY
	XDG_CURRENT_DESKTOP
	XDG_DATA_DIRS
	XDG_MENU_PREFIX
	XDG_RUNTIME_DIR
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SESSION_TYPE
	XMODIFIERS
	which_declare

```

**Additional context**
I am sure that this problem exists only in my case, and in typical case it is unreproducible bug. In my case, this is a second time installation after the using yum package manager (I'm using Fedora as I wrote above). This error began to appear after the second installation of the kitty. Both installations I did according to the [documentation](https://sw.kovidgoyal.net/kitty/binary/) steps and installed kitty into default directory. My `kitty.conf` file is fully default (except the occurrence variable, but this is irrelevant, I think).

I see two ways of fast fixing this bug (as I did):
1. Set the alias: `alias kitty="kitty -c=/home/krezefal/.config/kitty/kitty.conf"`
2. Move the `kitty.conf` to required path by the stderr (`/home/krezefal/.config/kitty/kitty.conf/kitty.conf`)

But both of them are not a true solution, ofc.

I'll be glad if someone helps me to understand this thing and/or helps get rid of this.

**Comment by kovidgoyal** [comment]
Read the help for the --config flag in kitty --help it will tell you all
you need to know to debug this.
