### ISSUE TITLE
macOS: Dragging multiple files on the terminal does not separate them

### ISSUE THREAD

**Issue by alappe** [kovidgoyal/kitty#4734]
**Describe the bug**
When I drag multiple files from the finder onto the terminal, the file paths are listed, but they are not separated with a space, thus rather unusable. I am unsure, but I'd say this has worked before and it certainly is the behaviour in other terminals.

**To Reproduce**
1. Open a Finder window with some files in it.
2. Drag two or more onto your terminal.
3. See error

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Darwin style.fritz.box 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
ProductName:    macOS ProductVersion:   12.2.1 BuildVersion:    21D62
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE`: Same behaviour.

**Comment by page-down** [comment]
Also paths do not escape characters such as spaces, or use quotation marks. This also makes it difficult to use with multiple files.

However I like the file path to remain as it is when dragging single file. ( without escaping )

I' m not sure if the style should be unified or treated differently.

**Comment by page-down** [comment]
Line breaks will cause paths to be executed as commands in unsupported shells, or shells that cannot be integrated.

Even in a text editor, it may be possible to run the built-in "terminal mode".

Maybe space-separated is a better default.

**Comment by kovidgoyal** [comment]
On Thu, Feb 24, 2022 at 09:55:06PM -0800, page-down wrote:
> Line breaks will cause paths to be executed as commands in unsupported shells, or shells that cannot be integrated.

So what? Drag and drop is a highly intentional action, not something
easily triggered accidentally. I want multiple urls on different lines
when dropping anywhere except at a shell. Nowhere else would you want
multiple urls on a single line, and if you use space as a separator, it
is ambiguous since file paths can have spaces. (Technically they can
have line breaks as well, but that is almost never seen)

**Comment by kovidgoyal** [comment]
Oh an dmodern shells support bracketed paste, so unless they are badly configured, pasted newlines dont cause command execution.

**Comment by page-down** [comment]
So command-line programs like busybox sh or others that do not support `bracketed paste` are not supported.

If some users have such special needs, they should use other terminals for these drag-and-drop tasks.

Personally, I would never drag and drop content into these programs.
