### ISSUE TITLE
Include option for a cursor guide

### ISSUE THREAD

**Issue by sollymay** [kovidgoyal/kitty#4740]
**Is your feature request related to a problem? Please describe.**

For visibility purposes, it would be great to have a setting to highlight the current cursor line (as iTerm2 does). In iTerm2 this setting is known as Cursor guide and I have it set to a slightly lighter (and transparent) tone that lets me find the cursor really fast, especially useful with vertically oriented screens.

<img width="1506" alt="Screen Shot 2022-02-23 at 12 20 47 PM" src="https://user-images.githubusercontent.com/6496698/155372555-ee1c2388-b5a1-4ac7-afbc-81ac3bee734f.png">

**Describe the solution you'd like**

An option in the config to be able to set the color (transparency should be allowed for the color) and the setting should ideally work irrespective of the program opened on the Kitty terminal.

**Describe alternatives you've considered**

I tried looking at the docs to find something similar I could configure, but all the highlights/etc are related to the cursor itself but not to the cursor line. Having the line allows me to quickly move my head and find the cursor in no time.

**Additional context**
I opened this feature request because I couldn't find an option to set cursor guides, but if there is an option, sorry about opening this and hope you can point me in the right direction as to how to achieve a similar behavior.

**Comment by kovidgoyal** [comment]
Not something I care about, as I have never had difficulty finding the
cursor anywhere except in editors, most of which already have this
facility. However, patches are welcome to implement such an option.
