### ISSUE TITLE
kitty fails several tests in vttest

### ISSUE THREAD

**Issue by dtwilliamson** [kovidgoyal/kitty#4742]
**Describe the bug**
How closely is kitty intended to emulate xterm (and VT series terminals)? Kitty 0.24.2 fails numerous tests in [vttest](https://invisible-island.net/vttest/).

**To Reproduce**
1. Download and untar vttest
2. Compile vttest (`./configure && make`)
3. `./vttest` (in kitty and for comparison in other emulators - xterm, Terminal.app, Gnome Terminal)
4. Go through the menu options

Note that many emulators fail some tests ([comparisons](https://invisible-island.net/xterm/xterm.faq.html#compare_versions) and [discussions](https://invisible-island.net/xterm/xterm.faq.html#known_bugs)).

**Comment by kovidgoyal** [comment]
Yes, I know. VT emulation is not a goal. A lot of VT behaviors are
extremely poorly designed. I will emulate them only if not emulating
them causes significant real world problems.
