### ISSUE TITLE
vim background color display error

### ISSUE THREAD

**Issue by skysky97** [kovidgoyal/kitty#4750]
**Describe the bug**
When background color of kitty is different from background color of vim,  scroll screen, the text background is correct, but background of blank area is the same with kitty background.

**To Reproduce**
1. kitty --config=none, background is black.
2. vim xxx, open a file, large enough so that lines exceed window height.
3. set vim color scheme, make sure the background is not black.
4. press 'j' and move cursor down, until screen scroll. Some area are black.

**Comment by kovidgoyal** [comment]
Read the FAQ: https://sw.kovidgoyal.net/kitty/faq/
