### ISSUE TITLE
Completely transparent window when waking PC from sleep

### ISSUE THREAD

**Issue by ad-on-is** [kovidgoyal/kitty#4751]
Just noticed something strange.After waking my laptop from sleep, kitty is completely transparent. The content returns when I click into the window.

![image](https://user-images.githubusercontent.com/9553253/155749746-e60023ec-fe90-485f-af0f-98d39ad13359.png)

**Comment by kovidgoyal** [comment]
This will be an issue with your graphics stack. kitty has no code to
deal with sleep/wake. Restoring windows after sleep is the job of the
graphics stack.

**Comment by ad-on-is** [comment]
@kovidgoyal Could you please point me into the right direction where and what to debug?

Back then I used GNOME, but I switched to awesomeWM in the meantime, and I still have a similar issue. Unlike on GNOME, the kitty window now only renders with the specified background-color and no text-output after waking from sleep. All other windows render just fine.

**Comment by kovidgoyal** [comment]
It will be an issue in your GPU drivers, how to debug them is specific to the driver. You can try using software rendering via the MESA env var whose name escapes me at the moment.

**Comment by ad-on-is** [comment]
Since I'm using nvidia, my best guess is to just submit an issue on their newly released open-source github. Is there anything specific about kitty compared to xterm/alacritty, etc. since these render just fine after waking up from sleep?

**Comment by kovidgoyal** [comment]
xterm is not GPU based, so very different graphics path. As for alacritty the difference is likely to be in underlying gpu libraries, glfw in kitty and wininit in alacritty. It should be relatively trivial for nvidia engineers to diagnose this and either fix it themselves or tell us what needs to be done to workaround it in kitty. But given I dont even have any nvidia hardware there's not much I can do to help you

**Comment by ad-on-is** [comment]
Thanks a lot! I'll submit an issue there, and If they provide a workaround, I can debug it on my end and submit a PR, if that's OK.

**Comment by kovidgoyal** [comment]
Yes, PRs are most welcome.
