### ISSUE TITLE
Open hyperlinks with ctrl+shift + click only

### ISSUE THREAD

**Issue by ljnsn** [kovidgoyal/kitty#4752]
I believe that before 0.24.0 the default behaviour for links was to only open a link with ctrl+shift + click and it has now changed to open the link on click by default. I am aware of the `allow_hyperlinks` option, but, as far as I am aware, this only makes it possible to either not allow links or to ask before opening them.

Is there a way to restore the previous behaviour, so to open links **without** asking on ctrl+shift + click and to not open them at all on simple click?

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

Configure the mouse actions in the way you like.

**Comment by ljnsn** [comment]
Thanks!
