### ISSUE TITLE
Minimise to Tray keybind

### ISSUE THREAD

**Issue by Latrolage** [kovidgoyal/kitty#4755]
**Describe the solution you'd like**
Configurable keybind which can minimise the focused kitty terminal to the system tray.

**Comment by kovidgoyal** [comment]
kitty has no tray icon, and I dont see why a terminal emulator would
need a tray icon in any case. If you mean you want to minimize the
window, that is the job of th ewindow manager and I am sure whatever
window manager you are using already has shortcuts for it.
