### ISSUE TITLE
How to generate the default config?

### ISSUE THREAD

**Issue by pkeroulas** [kovidgoyal/kitty#4767]
Hi,
I got my initial config from the Ubuntu package, but now, I build from source.
I don't see how to get a fresh new config in order to benefit from all the great new stuff and merge with my old config.
Please can you help?
Thanks,
PK

**Comment by page-down** [comment]
Rename or remove the configuration file `~/.config/kitty/kitty.conf`.
Restart kitty and press `ctrl+shift+f2`.

**Comment by kovidgoyal** [comment]
And also: https://sw.kovidgoyal.net/kitty/conf/#sample-kitty-conf

**Comment by pkeroulas** [comment]
Perfect, thanks!
