### ISSUE TITLE
Enter key with modifiers

### ISSUE THREAD

**Issue by ssoriche** [kovidgoyal/kitty#477]
In my Vim/NeoVim configuration I have configured:

```
inoremap <c-cr> <esc>A<cr>
inoremap <s-cr> <esc>A:<cr>
```

Which should trigger moving to the end of the current line and appending a carriage return to move to the next line. Unfortunately what is happening is just the carriage return is being sent.

From the looks of it, Kitty is passing the enter key onto Vim/NeoVim without the modifier. Is it possible to have the modifier passed through?

**Comment by kovidgoyal** [comment]
The standard terminal keybaord protocol does not support ctrl+enter. Try it in any terminal, run

showkey -a


and then  type enter and then ctrl+enter you will see the same bytes being sent in each case. For what you want you have to convince vim/neovim to add support for the extended keyboard protocol described here: https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc
