### ISSUE TITLE
launch does not set PATH from /etc/paths

### ISSUE THREAD

**Issue by khaveesh** [kovidgoyal/kitty#4774]
**Describe the bug**
The `launch` command does not seem to set the PATH env variable to the system-wide PATH variable, which in the case of macOS is read from `/etc/paths` & `/etc/paths.d/*`.

**To Reproduce**
1. `kitty @ launch dash`
2. In the new pane, `echo $PATH`
3. See: `/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin`

Expected output: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/kitty.app/Contents/MacOS`

**Environment details**
```
kitty 0.24.3 created by Kovid Goyal
Darwin Khaveeshs-MBP.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.2.1 BuildVersion:	21D62
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/khaveesh/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       y
copy_on_select             a1
cursor_blink_interval      0.0
enabled_layouts            ['splits', 'stack']
font_family                Consolas
font_size                  13.5
macos_option_as_alt        3
macos_show_window_title_in window
macos_thicken_font         0.5
mouse_hide_wait            -1.0
scrollback_pager           ['nvim', '+Man!', '+INPUT_LINE_NUMBER']
shell                      /usr/local/bin/fish --login --interactive
strip_trailing_spaces      smart
update_check_interval      0.0
url_style                  1
Added shortcuts:
	ctrl+opt+z → toggle_layout stack
	cmd+d → launch --location=vsplit --cwd current
	cmd+h → neighboring_window left
	cmd+j → neighboring_window down
	cmd+l → neighboring_window right
	cmd+p → paste_from_buffer a1
	cmd+s → launch --location=hsplit --cwd current
	shift+cmd+h → move_window left
	shift+cmd+j → move_window down
	shift+cmd+k → move_window up
	shift+cmd+l → move_window right
Changed shortcuts:
	cmd+k → neighboring_window up
	cmd+t → new_tab_with_cwd
Colors:
	background                 #121212   
	color0                     #161616   
	color1                     #ef3a3a   
	color10                    #abe05a   
	color11                    #ffd141   
	color12                    #0092ff   
	color13                    #9a5feb   
	color14                    #67ffef   
	color2                     #11cd11   
	color3                     #e5e513   
	color4                     #2eaeee   
	color5                     #d086f5   
	color6                     #11d4d4   
	color7                     #eeeeee   
	color8                     #444444   
	color9                     #ff273f   
	cursor                     #ff0017   
	foreground                 #f2f2f2   
	selection_background       #dbf1fc   
	selection_foreground       #161616   
	url_color                  #44a2f9   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                khaveesh
```

**Additional context**
- Reproducible even with `kitty --config NONE`.
- **And I noticed that the path in the debug output too is wrong. So this may not be limited to only the launch command.**
- Fixed by `--copy-env` flag. But when using from launch-actions.conf it does not have any effect.
- Related issues #3787, #1018 and #1721.

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

When using `launch`, kitty runs the program directly with its own environment, without calling the shell.

Under macOS, if you launch kitty from another app, such as Hammerspoon, Alfred, etc., the PATH does not contain `/usr/local/bin`, as you have shown.
Only through Launchpad or Dock or Spotlight, then kitty will get `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`.

The following option `exe_search_path` is specially designed for this situation.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

Also, when looking for executables, kitty will look at `/etc/paths`, but will not alter the PATH.
In this case you should use `env` to configure it.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.env

**Comment by khaveesh** [comment]
Thank you. I was able to rectify by manually setting the PATH using the env command. 

Is there any reason, why kitty doesn't set it from `/etc/paths`. It is the recommended way to set system-wide paths in macOS, if I'm not mistaken.

**Comment by kovidgoyal** [comment]
launch does not do things behind your back. If you want env vars from /etc/paths, use --env or launch with a shell wrapper

launch zsh -il -c "your command"
