### ISSUE TITLE
Unable to "open shell" from different programs

### ISSUE THREAD

**Issue by pasdechance** [kovidgoyal/kitty#4776]
This is not a *bug* with kitty, I believe. I think I somehow did not set something up correctly.

**Describe the bug**
Different programs that I use for teaching purposes, Thonny and Geany most often, have an "open in shell" or "execute in shell" option. When using Kitty as my default terminal, I receive similar errors from both. 

Thonny returns:

```
Failed to launch child: bash -c "/usr/bin/python3 /usr/lib/python3/dist-packages/thonny/plugins/system_shell/explain_environment.py; exec bash -i"
With error: No such file or directory
Press Enter to exit.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Thonny, for example
2. Tools > Open system shell
3. See message

**Environment details**

[-will add later-]

**Additional context**
Running `bash -c "/usr/bin/python3 /usr/lib/python3/dist-packages/thonny/plugins/system_shell/explain_environment.py; exec bash -i"`

Running Debian Sid

**Comment by kovidgoyal** [comment]
I dont see what this has to do with kitty. You need to figure out what geany and thonny are executing to run their "shell". And then you will know why that fails. Also IIRC geany has an embedded libvte terminal. This has nothing to do with kitty at all.

**Comment by pasdechance** [comment]
You are right. It has nothing to do with Kitty at all. I was just asking for help because when I set *any* other terminal as default (except for qterminal) everything works fine.

Geany can use the embedded terminal, but can also execute scripts in a regular terminal. Again, works fine everywhere else.

I was just asking for help, you know, as one does when they are having trouble making things work. I'll figure it out.

**Comment by kovidgoyal** [comment]
A good place to ask for help is in the
https://github.com/kovidgoyal/kitty/discussions 

Although really, in this case you should be asking for help in the
community of geany/etc.

**Comment by page-down** [comment]
@pasdechance 

> I was just asking for help ...

You can check the following code. I have tested and confirmed that it works with some modifications.

https://github.com/thonny/thonny/blob/v3.3.14/thonny/terminal.py

```python
def _run_in_terminal_in_linux(cmd, cwd, env, keep_open):
    # ...
    # subprocess.Popen(["kitty", "... whatever ...", "..."], ...)

def _get_linux_terminal_command():
    return "kitty"
```

Sorry, I will not continue this discussion, please go to the respective project to report the issue.

**Comment by pasdechance** [comment]
OK. I got that far on my own. But, I don't know anything about programming and didn't get very far. Thanks for replying anyway.
