### ISSUE TITLE
ctrl+shift+u opens a new window

### ISSUE THREAD

**Issue by derfalx** [kovidgoyal/kitty#478]
Hey,
I'm using the lateste git version of kitty with oh-my-zsh. When pressing `ctrl+shift+u` instead of the unicode-widget another terminal window opens. Am I missing some configuration?

**Comment by kovidgoyal** [comment]
Presumably you have re-mapped that keyboard shortcut in your kitty.conf. Use 

kitty --config NONE 

to check.

**Comment by derfalx** [comment]
I've tried this already, did not solve the Problem. Remapping the function to `ctrl+shift+l` showed the same problem with the changed shortcut.

**Comment by kovidgoyal** [comment]
What OS and kitty version?

**Comment by kovidgoyal** [comment]
And post the output of running:

```
which kitty
kitty --debug-config
```

**Comment by derfalx** [comment]
```
kitty 0.9.0 (bb939ed4f8) created by Kovid Goyal
Linux stuxnet 4.9.94-1-MANJARO #1 SMP PREEMPT Fri Apr 13 23:25:10 UTC 2018 x86_64
Running under: X11
Manjaro Linux \r  (\n) (\l)
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.1.8
DISTRIB_CODENAME=Hakoila
DISTRIB_DESCRIPTION="Manjaro Linux"
Loaded config files: /home/falx/.config/kitty/kitty.conf

Config options different from defaults:
```

I've installed it manually by cloning it from github to`/opt/kitty/` and start a new session by calling `python3 /opt/kitty`

**Comment by kovidgoyal** [comment]
You've forgotten the output of running

```
which kitty
```

from inside kitty.

**Comment by derfalx** [comment]
```
which kitty
> /bin/kitty
cat /bin/kitty
> #! /bin/bash
> python3 /opt/kitty/
```

**Comment by kovidgoyal** [comment]
You've got a space after `#!`

And you dont need /bin/kitty at all. kitty willa dd a launcher for itself to the PATH when it is running automatically.

**Comment by kovidgoyal** [comment]
Oh and if you want to create a script to launch kitty, it should look like this:

```sh
#!/bin/sh

exec python3 /path/to/kitty "$@"
```

**Comment by kovidgoyal** [comment]
Or even better
```py
#!/usr/bin/env python3

import runpy
runpy.run_path('/home/kovid/work/kitty', run_name='__main__')
```

**Comment by derfalx** [comment]
I've fixed the sh-script the way you mentioned, now it works!

Could you explain why it works now?

**Comment by kovidgoyal** [comment]
You had a space after your #! which meant your script was running a shell instead of kitty. The script I posted will actually run kitty and pass the comamnd line arguments to it, which is needed by the kittens system.
