### ISSUE TITLE
Test test_zsh_integration fails in CI

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#4782]
**Describe the bug**
The test test_zsh_integration (kitty_tests.shell_integration.ShellIntegration) fails in the Nixpkgs CI.

**To Reproduce**
Unfortunately I haven't been able to reproduce the problem locally.

**Additional context**
Here is the log that shows the test failure: https://logs.nix.ci/?key=nixos/nixpkgs.162215&attempt_id=b6781468-899d-47e8-889c-d7c7b51dae70
The log is from building and testing v0.24.4 but this also happens with v0.24.3. It also happens on x86_64 and aarch64.
The assert that fails is here: https://github.com/kovidgoyal/kitty/blob/90ed5959de1a48b5775924ad50686c2ec86aa730/kitty_tests/shell_integration.py#L110
In the test the actual screen contents are
```
left>                                                                    <right
```
While the tests expects one more space:
```
left>                                                                     <right
```
Should I try to bisect this? Or add a few `print()` statements in the test to see what the contents of some variables like `pty.screen.columns` are?

**Comment by page-down** [comment]
Please see my fish test code below.

When I was testing the fish integration, there was nothing on the screen at all when the cursor shape changed.
You can also adjust this by adding a suitable wait_till condition.

**Comment by Luflosi** [comment]
Unfortunately, that did not fix the problem. [Here is the new log](https://logs.nix.ci/?key=nixos/nixpkgs.162215&attempt_id=6ea00876-dfe7-41ed-b325-9c85712f63ef).
How can I help to debug this?

**Comment by page-down** [comment]
In this case, is it possible that zsh is not recognizing the same columns as kitty?
I cannot reproduce this issue in any of my environments.

Is it possible to start the test for changing the window size first and then continue with the other tests?

**Comment by kovidgoyal** [comment]
have zsh echo the value of ZLE_RPROMPT_INDENT it is set to 0 by the test
code but maybe something in the environment is overriding it.

**Comment by kovidgoyal** [comment]
ANd see if my latest commit helps where I set that var in zshrc instead of in the environment.

**Comment by kovidgoyal** [comment]
On Thu, Mar 03, 2022 at 01:43:22PM -0800, Luflosi wrote:
> Yep, your latest commit fixed it 🎉. Thanks.
> Would You still like me to echo ZLE_RPROMPT_INDENT to see what the value is? Is that sill interesting? How do I do that?

No need, the value is 1 given the off by one result in the test. As for
how to echo it, something like

pty.send_command('echo "zri=$ZLE_RPROMPT_INDENT"')
pty.wait_till(lambda: 'zri' in pty.screen_contents())
print(pty.screen_contents())

**Comment by Luflosi** [comment]
I confirmed it's indeed 1. Thanks for your help again.
