### ISSUE TITLE
Symlinked bashrc not sourced correctly anymore

### ISSUE THREAD

**Issue by Mithrandir2k18** [kovidgoyal/kitty#4783]
**Describe the bug**
My bashrc is a symlink to my dotfiles repo. Kitty doesn't source it correctly anymore, while xfce4-terminal does.

**To Reproduce**
1. Move .bashrc somewhere
2. link to .bashrc from $HOME
3. launch new kitty window
4. bashrc won't be sourced

**Environment details**
```
kitty 0.24.3 created by Kovid Goyal
Linux archws 5.16.11-arch1-2 #1 SMP PREEMPT Mon, 28 Feb 2022 10:17:30 +0000 x86_64
Arch Linux 5.16.11-arch1-2 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell False
shell_integration frozenset()

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/opt/jdk-11.0.6/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                user
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 qtile
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/user
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      5
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Comment by page-down** [comment]
I cannot reproduce the issue. The symbolic link for .bashrc loads fine.
(But I found a case of infinite sourcing .bashrc.)

Try upgrading to 0.24.4 and removing the integration section from .bashrc (no longer needed in the new version).

**Comment by kovidgoyal** [comment]
Doesn't reproduce for me either. In fact, my regular .bashrc is a symlink
(as are all my dotfiles).

Form your config dump you seem to have an empty shell_integration
although that shouldnt be possible. In any case remove it from your
kitty.conf and you should be fine.

**Comment by Mithrandir2k18** [comment]
Found the issue. I had played around with different bash prompts on another machine and when copying over to this one that didn't work. The issue was not sourcing it though, but a typo in my settings. I had `no_cursor` instead of `no-cursor` in the shell integration setting.
