### ISSUE TITLE
Cannot disable visual_bell_duration

### ISSUE THREAD

**Issue by atsuya** [kovidgoyal/kitty#479]
Hi Kovid,

It seems like I can't disable visual bell. I have visual_bell_duration set to 0.0 as the documentation says, but it still flashes the screen.

Environment:
- Kitty version: 0.9.0
- OS and OS version: Arch Linux with kernel 4.16.3-1.
- Kitty config: https://gist.github.com/atsuya/b68dfd979ad3ab22152584952c1cb96f

Let me know if there is anything you want me to test. Thanks!

**Comment by kovidgoyal** [comment]
Works for me. Can you see if you can isolate a minimal config file to reproduce it? I tried with

kitty --config NONE -o enable_audio_bell=no

and got no visual bell.

**Comment by atsuya** [comment]
I was referring to the flash I see in vim (the one you see when you tries to scroll down after reaching the the end of line for the file), but maybe it's vim issue. I don't see the flash on Gnome Terminal, so I assumed this is caused by Kitty, but I might be wrong.

How did you confirm that it worked for you? I can try that on my end to see what I get.

**Comment by atsuya** [comment]
With regards to the flash I'm referring to, I still see it with `kitty --config NONE -o enable_audio_bell=no`.

**Comment by kovidgoyal** [comment]
You trigger a bell with

printf '\a'

If you set visual_bell_duration to greater than 0 it will cause the screen to flash. If you dont it wont. As for vim, I cannot reproduce a flash when reaching the end of a scroll, all I can suggest is make sure you follow the advice in the kitty FAQ about vim.

**Comment by atsuya** [comment]
I executed ```printf '\a'``` with ```kitty --config NONE -o enable_audio_bell=no```, and I indeed don't see a flash.

However, I don't see the flash either when I do the same with ```kitty --config NONE -o enable_audio_bell=yes``` or ```kitty --config NONE -o enable_audio_bell=1.0```.

It could be the bug wasn't about not being able to disable visual bell, but visual bell not being working.

**Comment by kovidgoyal** [comment]
You want

```
kitty -o visual_bell_duration=0.2
```

**Comment by atsuya** [comment]
I confirm ```kitty -o visual_bell_duration=0.2``` does show a flash, and ```kitty -o visual_bell_duration=0.0``` doesn't. What I was referring to must be a vim thing.

Thanks Kovid!

**Comment by ArbitRandomUser** [comment]
ive been playing around with this a bit and i seem to be getting visual bells in some cases
on archlinux 
i have in my .zshrc
`export LESS="-Q -R -M " `
less documents -Q option ..,
` -Q or --QUIET or --SILENT
              Causes  totally  "quiet"  operation:  the terminal bell is never rung.  If the terminal has a "visual bell", it is used in all cases where the terminal bell would have been
              rung.`
i still get the visual bell triggered when i try to scroll up past the top of the page 
(doesnt happen while scrolling past the bottom of the page)

**Comment by ArbitRandomUser** [comment]
the terminal does seem to triggered by the visual bell in some cases 
inspite of setting `visual_bell_duration=0.0`
for example even with  in less with -Q
man less says ...
`-Q or --QUIET or --SILENT
              Causes  totally  "quiet"  operation:  the terminal bell is never rung.  If the terminal has a "visual bell", it is used in all cases where the terminal bell would have been
              rung.`
i have 
`export LESS=-Q`
and i still see the visual bell when trying to scroll up past the top of the page.

**Comment by kovidgoyal** [comment]
The visual bell is triggered only when the program running in the terminal
sends a bell character to it. You are probably confusing less' visual bell with the terminals.

**Comment by ArbitRandomUser** [comment]
but the documentation says `If the terminal has a "visual bell", it is used in all cases where the terminal bell would have been rung` , so isnt it ringing the terminals bell ?
i can confirm that `less` is triggering the terminal bell because when `visual_bell_duration` is set to say 5 i get a 5 second visual bell in less , but when i set visual_bell_duration to 0 i still get a brief visual flash

**Comment by kovidgoyal** [comment]
so if less is trigerring the bell and you dont want it to, contact the
developer of less.

**Comment by ArbitRandomUser** [comment]
less seems to be working as documented, if -Q it disables audible bell and triggers a visual bell instead.
isn't the question now is if the terminal decides to show the visual bell or not.

neverthless isnt this a bug in kitty ? 
setting `visual_bell_duration=0.0` i should never see a terminal bell, and yet i do see a terminal bell .

**Comment by kovidgoyal** [comment]
On Mon, Nov 01, 2021 at 02:33:02AM -0700, ArbitRandomUser wrote:
> less seems to be working as documented, if -Q it disables audible bell and triggers a visual bell instead.
> isn't the question now is if the terminal decides to show the visual bell or not.

There is no such thing as a trigerrable visual bell!! The terminal can
choose to interpret an audio bell as making a beep or flashing the
screen or both or either or neither.

> 
> neverthless isnt this a bug in kitty ? 
> setting `visual_bell_duration=0.0` i should never see a terminal bell, and yet i do see a terminal bell .

Cannot reproduce. Steps I tried:

1) Run kitty 
2) printf '\a'
Heard an audio bell, saw no visual flash

**Comment by ArbitRandomUser** [comment]
okay yes printf '\a' doesnt show any visual flash , could you try to reproduce these steps 

1. configure kitty with `visual_bell_duration=0.0`
2. `export LESS="-Q"`
3. `man man`
4. scroll up to the to `g`
5. try scrolling up again
expected behavior: no visual bell
what happens: terminal flashes

**Comment by kovidgoyal** [comment]
If there is no flash with printf '\a' there can be no flash with less,
less has to do a printf '\a' to make the terminal flash. if you are
seeing a flash it is coming from less not kitty.

**Comment by page-down** [comment]
@ArbitRandomUser 
> what happens: terminal flashes

No need to argue, just run it and see the result.

After running the following command, run printf '\a' in the window and you will see a red 2s blink, which is kitty's visual bell.
```shell
kitty --config=NONE -o visual_bell_duration=2.0 -o selection_background=#ff0000
```

Set the duration to 0, run `less` in the following window and compare for yourself if it is a red colored kitty visuall bell.
```shell
kitty --config=NONE -o visual_bell_duration=0.0 -o selection_background=#ff0000
```

**Comment by ArbitRandomUser** [comment]
yes , confirmed thank you , it is from `less` and not kitty ;
thank you for explaining @kovidgoyal @page-down
