### ISSUE TITLE
Select_tab should not change key-tab mapping

### ISSUE THREAD

**Issue by andersbetner** [kovidgoyal/kitty#4792]
This is more of a question about a design decision. 
**Is your feature request related to a problem? Please describe.**
I have three tabs open (tab1, tab2, tab3)
When I hit the mapped key for `select_tab` I get presented with different "jump keys" depending on which tab I am jumping from.

```
# Active tab == tab1
select_tab shows:
1 tab2
2 tab3
# I have to press 1 to get to tab2
```
```
# Active tab == tab2
select_tab shows:
1 tab1
2 tab3
# I have to press 1 to go to tab1
# I have to press 2 to go to tab3
```
```
# Active tab == tab3
select_tab shows:
1 tab1
2 tab2
# I have to press 2 to go to tab2
```
**Describe the solution you'd like**
It would be better for the muscle memory to keep the list the same in all tabs.
There is a higher cognitive load to either remember which tab has which shortcut depending of the active tab or to have to scan the list every time.
Would it be possible to present list list like this?
```
Active tab == tab1
select_tab shows:
1 tab1
2 tab2
3 tab3
```
```
Active tab == tab2
select_tab shows:
1 tab1
2 tab2
3 tab3
```
Yes you would be able to jump to the current tab, but just let me do that. I can handle it.

**Describe alternatives you've considered**
-

**Additional context**
-
If I'm not too far off, the only thing needed wold be to get rid of the condition in the list comprehension here https://github.com/kovidgoyal/kitty/blob/cf520646a9261f6dada07d7a6735e10f6c1b27a2/kitty/boss.py#L2169
I'm aware this would mess with peoples brains at first, but wouldn't it be a better design?

**Comment by page-down** [comment]
I had made a similar suggestion for the visual window selection feature.
I also don't really like the fact that the selection keys changes dynamically in this usage scenario.
The current tab can be grayed out in the list.

This way the order of tab candidates in the list is consistent with the actual order, which will improve the user experience.
