### ISSUE TITLE
Ctrl+R when Kitty is moving the cursor from a mouse click causes fzf to crash from too many cursor inputs

### ISSUE THREAD

**Issue by ZimbiX** [kovidgoyal/kitty#4799]
**Describe the bug**

I first [reported this issue on fzf](https://github.com/junegunn/fzf/issues/2748), but it appears to be a bug with Kitty instead.

I use [fzf](https://github.com/junegunn/fzf), to have a fancy shell history on Ctrl+R. When I press Ctrl+R at the exact moment that the Kitty shell integration is trying to move the cursor after a mouse click, a massive number of left cursor key inputs is generated, which crashes fzf.

**To Reproduce**

It took me a while to figure out how to reproduce it. From the previous issue:

> One of the features of Kitty's [shell integration](https://sw.kovidgoyal.net/kitty/shell-integration/) is:
> 
> > Click with the mouse anywhere in the current command to move the cursor there
> 
> When I click, it waits about a second, and then it moves the cursor. If I press Ctrl+R just as it is moving the cursor, fzf crashes.
> 
> I've recorded a video demo. It tries to move the cursor no matter whether there's a current command written (and I think no matter where you click in the terminal), but I've demonstrated it with one, in order to be able to visualise the timing of the cursor move, so as to demonstrate and reproduce the issue more easily. Instead of redacting, I've simplified my shell prompt and moved my `~/.zsh_history` file.
> 
> I would have recorded a smaller window, but it seems to need the terminal to be decently large to reproduce the issue.
> 
> https://user-images.githubusercontent.com/2916331/157018827-40df4d30-1c1c-4ce7-89ed-0f1542ef7923.mp4

Also reproducible with `kitty --config NONE` with my `~/.zshrc` removed, configuring [just fzf](https://github.com/ZimbiX/dotfiles/blob/master/system/fzf.zsh).

Thanks for making Kitty! <3

**Comment by kovidgoyal** [comment]
That's a feature, not a bug. When you click at a prompt kitty will output
a number of left or right keypresses to move the cursor to the clicked
point. fzf crashing because it gets a number of left or right arrow
presses is a bug in fzf. Simply dont click before running fzf or wait
for the cursor to finish moving before running fzf.

**Comment by junegunn** [comment]
> a number of left or right keypresses

How many and for how long? fzf decides to abort because it's getting thousands of left key presses (10KiB buffer limit reached). That many key presses are probably 
not necessary in this scenario.

**Comment by kovidgoyal** [comment]
Depends on the distance in cells between the click point and the current cursor
position. Which will never be larger than the width * height of the
screen.

**Comment by ZimbiX** [comment]
> Which will never be larger than the width * height of the screen

That might explain why I couldn't reproduce it at a smaller window size

**Comment by ZimbiX** [comment]
> Simply dont click before running fzf or wait for the cursor to finish moving before running fzf.

I click on my terminal to focus the window. I don't consider that a solution - sounds like the "you're holding it wrong" response, tbh. If this can't be resolved, I'll have to disable the feature, which would be unfortunate.

**Comment by kovidgoyal** [comment]
On Tue, Mar 08, 2022 at 06:53:08PM -0800, Brendan Weibrecht wrote:
> > Simply dont click before running fzf or wait for the cursor to finish moving before running fzf.
> 
> I click on my terminal to focus the window. I don't consider that a solution - sounds like the "you're holding it wrong" response, tbh. If this can't be resolved, I'll have to disable the feature, which would be unfortunate.

Feel free to disable it. If you have some "better" solution to moving
the cursor at a shell prompt on a click, feel free to suggest that as
well. Or just wait for fzf to raise its max input buffer size. Or use
focus follows mouse to avoid having to be always clicking to change
focus.

**Comment by kovidgoyal** [comment]
Although this use case is already handled in kitty https://github.com/kovidgoyal/kitty/blob/master/kitty%2Fwindow.py#L1013

Make sure you are running an up to date version.

**Comment by ZimbiX** [comment]
> Although this use case is already handled in kitty

Interesting. Though I do click out of habit on already focused windows to ensure that the focus is where I expect it to be, since a window can generally have multiple areas that could be focused. So I don't think that would fully solve it.

> Or just wait for fzf to raise its max input buffer size.

I think the fzf resolution question here was around whether the number of cursor navigation characters produced by Kitty is indeed finite - as opposed to keeping going until the cursor reaches the desired position, which, with fzf taking control, it may never reach. It sounds like you're saying it is finite, which is good; so perhaps this can be worked around in fzf.

**Comment by ZimbiX** [comment]
Although this wouldn't be a complete fix either, how about only attempting the move the cursor when the click occurs within the text of the current command?

**Comment by kovidgoyal** [comment]
On Tue, Mar 08, 2022 at 07:20:52PM -0800, Brendan Weibrecht wrote:
> > Although this use case is already handled in kitty
> 
> Interesting. Though I do click out of habit on already focused windows to ensure that the focus is where I expect it to be, since a window can generally have multiple areas that could be focused. So I don't think that would fully solve it.
> 
> > Or just wait for fzf to raise its max input buffer size.
> 
> I think the fzf resolution question here was around whether the number of cursor navigation characters produced by Kitty is indeed finite - as opposed to keeping going until the cursor reaches the desired position, which, with fzf taking control, it may never reach. It sounds like you're saying it is finite, which is good; so perhaps this can be worked around in fzf.

Yes, it is finite. kitty doesnt keep trying if the cursor doesnt reach
the intended position.

**Comment by kovidgoyal** [comment]
On Tue, Mar 08, 2022 at 07:25:13PM -0800, Brendan Weibrecht wrote:
> Although this wouldn't be a complete fix either, how about only attempting the move the cursor when the click occurs within the text of the current command?

There is no way for th eterminal emulator to know what the text of the
current command is.

**Comment by ZimbiX** [comment]
> There is no way for the terminal emulator to know what the text of the current command is.

As in, it can't distinguish between the prompt and the command?

**Comment by kovidgoyal** [comment]
On Tue, Mar 08, 2022 at 10:28:16PM -0800, Brendan Weibrecht wrote:
> > There is no way for the terminal emulator to know what the text of the current command is.
> 
> As in, it can't distinguish between the prompt and the command?

There can potentially be left prompts, right prompts, sub prompts, etc.

The best that can be done is use a heuristic like if there are more
than X blank lines between the click position and the cursor, abort.
But that's just a bandaid. The proper fix is for fzf to not
choke. Or if they are not willing to do that, and you want to continue
using fzf, dont randomly click on windows, or turn off the kitty mouse
action that moves the cursor on clicks.

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Click-the-link-under-the-mouse-or-move-the-cursor

**Comment by junegunn** [comment]
Okay, in that case, we can consider raising the limit. 

https://github.com/junegunn/fzf/blob/5f385d88e0a786f20c4231b82f250945a6583a17/src/tui/light.go#L26

We have the limit only because we don't want fzf to hang consuming CPU resources in anomalous situations, so raising it to 100KB or even 1MB should not be a problem.
