### ISSUE TITLE
Hinting settings in fonts.conf cause set_font to fail

### ISSUE THREAD

**Issue by mlochbaum** [kovidgoyal/kitty#480]
After I try to run kitty on Arch Linux, it gives the following error and dies:

    [112 14:47:41.815577] Traceback (most recent call last):
      File "./kitty/main.py", line 186, in main
        _main()
      File "./kitty/main.py", line 179, in _main
        run_app(opts, args)
      File "./kitty/main.py", line 53, in run_app
        boss = Boss(window_id, opts, args, cached_values)
      File "./kitty/boss.py", line 102, in __init__
        set_font_family(opts)
      File "./kitty/fonts/render.py", line 55, in set_font_family
        render_box_drawing, sm, sfonts, sz, *faces
    SystemError: <built-in function set_font> returned NULL without setting an error

My .config/fontconfig/fonts.conf:

    <?xml version="1.0"?>
    <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
    <fontconfig>
            
            <match target="font">
                    <test name="hintstyle" compare="eq">
                            <const>hintslight</const>
                    </test>
                    <edit name="hintstyle" mode="delete"/>
            </match>
    </fontconfig>

When I remove either the `test` or `edit` element, kitty starts correctly.

The error happens with the `kitty` or `kitty-git` AUR packages, as well as when building from the latest source. Possibly relevant packages are:

    linux 4.15.3-2
    freetype2 2.9-2
    fontconfig 2.13.0+10+g58f5285-1

As suggested by the comment in fonts.conf, I can remove /etc/fonts/conf.d/10-hinting-slight.conf to get the same effect as this fonts.conf. But it will be back when I update again, so I would really prefer to be able to use fonts.conf for this. It's entirely possible that my configuration is wrong in some way that most applications don't care about, in which case knowing how to set it correctly would work equally well for me.

**Comment by kovidgoyal** [comment]
The correct way to do it would be to use mode="assign" to change the value to what you want, presumably hintmedium or hintfull. In any case, kitty should handle this more gracefully.

**Comment by mlochbaum** [comment]
Thanks! Using mode="assign" doesn't cause a crash, and that commit fixes the crash with my old configuration as well.
