### ISSUE TITLE
cursor save state possibly broken with rows

### ISSUE THREAD

**Issue by devsnek** [kovidgoyal/kitty#4814]
**Describe the bug**

I'm trying to figure out if I'm using save states wrong or if kitty has a bug. This script seems to work in xterm but not in kitty:

```js
'use strict';

process.stdout.write('hello world');
process.stdout.moveCursor(-3);
process.stdout.write('\x1b7\nmeow\x1b8');

setTimeout(() => {}, 500000000);
```

**To Reproduce**
1. DECSC
2. introduce newlines
3. DECRC
4. cursor goes to correct column but stays on the same row?

**Screenshots**

kitty
![](https://gc.gy/114675418.png)

xterm
![](https://gc.gy/114675435.png)

**Environment details**
```
kitty 0.24.3 created by Kovid Goyal
Linux ferris 5.16.11-arch1-2 #1 SMP PREEMPT Mon, 28 Feb 2022 10:17:30 +0000 x86_64
Arch Linux 5.16.11-arch1-2 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/snek/.config/kitty/kitty.conf

Config options different from defaults:
cursor_shape 2
font_family  JetBrains Mono

Important environment variables seen by the kitty process:
	PATH                                /home/snek/.cargo/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/platform-tools:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/fish
	DISPLAY                             :0
	USER                                snek
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/snek
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000

```

Also I love using kitty, thanks for all the work you've put into it.

**Comment by kovidgoyal** [comment]
works for me with:

```
printf "\x1b7"
echo one
echo two
printf "\x1b8"
read
```

kitty sh test.sh

cursor is at 1,1
after script has run, as expected. I doubt node is doing what you think
its doing. Use --dump-commands to see what commands are actually being
sent to kitty.

**Comment by devsnek** [comment]
it seems that this occurs when the window scrolls between the save and restore, as the cursor position is just relative to the term window, not the contents. do you know if there's a clean way to deal with this? even if i take newlines i'm printing into account, i don't know how i would know whether those newlines caused the terminal to scroll.

**Comment by kovidgoyal** [comment]
I dont understand what it is you are trying to do? You want to move the
cursor to some content? The only way to do that reliably is to switch to
alternate screen and manage the scrollback yourself.

**Comment by devsnek** [comment]
I'm working on a REPL that can print out autocompletes as you type, so basically at any point while you're typing it might save the cursor location, print out `\n{some eval completion}\n`, and then restore the cursor position.

![Peek 2022-03-11 23-43](https://user-images.githubusercontent.com/5952481/158005612-edd9b4dd-5e0e-4f14-8818-6a92648f1500.gif)

you can see it works until it reaches the bottom of the screen, at which point the saved cursor position starts changing relative to the text, since the entire emulator view is scrolling as more newlines are printed out, so jumping back to where the user is typing stops working and everything gets corrupted.

What does switching to an alternate screen mean?

**Comment by kovidgoyal** [comment]
For this you want the unscroll extension: https://sw.kovidgoyal.net/kitty/unscroll/  but its kitty specific. For a non kitty specific solution use the alternate screen, which is what full screne programs like editors use. A quick google of terminal alternate screen 1049 will tell you more.

**Comment by devsnek** [comment]
thanks for the info.
