### ISSUE TITLE
Fish Shell Rendering Issue.

### ISSUE THREAD

**Issue by JayaswalPrateek** [kovidgoyal/kitty#4822]
**Describe the bug**
Here is a my empty shell prompt in tilix vs kitty terminal
![kity](https://user-images.githubusercontent.com/77295140/158028706-69f5c297-0eff-4096-a96f-d38131ed6e6b.png)
Fonts are same, Font Size is same. ">>>" is not bold in kitty. Can kitty make it bold ?

Issue persists even after `kitty --config NONE`

**Environment details**
kitty 0.24.4 created by Kovid Goyal
Linux Lenovo 5.16.0-14.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.16-18ubuntu1~focal (2022-03-11) x86_64
elementary OS Jólnir Lenovo /dev/tty

DISTRIB_ID=elementary
DISTRIB_RELEASE=6.1
DISTRIB_CODENAME=jolnir
DISTRIB_DESCRIPTION="elementary OS 6 Jólnir"
Running under: X11
Frozen: True
Paths:
  kitty: /home/prateek/.local/kitty.app/bin/kitty
  base dir: /home/prateek/.local/kitty.app/lib/kitty
  extensions dir: /home/prateek/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/prateek/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       y
bold_font                  Fira Code Bold
cursor_beam_thickness      1.0
cursor_blink_interval      0.0
cursor_shape               2
cursor_stop_blinking_after 0
cursor_text_color          None
editor                     nano
enable_audio_bell          False
font_family                Fira Code Retina
font_features:
{'FiraCode-Retina': ('+zero',)}
initial_window_height      (30, 'cells')
initial_window_width       (100, 'cells')
input_delay                0
mouse_hide_wait            5.0
remember_window_size       False
repaint_delay              15
scrollback_lines           1000
shell                      fish
single_window_margin_width FloatEdges(left=0.0, top=0.0, right=0.0, bottom=0.0)
strip_trailing_spaces      smart
sync_to_monitor            False
Colors:
	active_border_color        #50fa7b   
	active_tab_background      #f8f8f2   
	active_tab_foreground      #282a36   
	background                 #0f1417   
	bell_border_color          #ffb86c   
	color0                     #21222c   
	color1                     #ff5555   
	color10                    #69ff94   
	color11                    #ffffa5   
	color12                    #d6acff   
	color13                    #ff92df   
	color14                    #a4ffff   
	color2                     #50fa7b   
	color3                     #f1fa8c   
	color4                     #bd93f9   
	color5                     #ff79c6   
	color6                     #8be9fd   
	color7                     #f8f8f2   
	color8                     #3b4252   
	color9                     #ff6e6e   
	cursor                     #ffffff   
	foreground                 #ffffff   
	inactive_border_color      #ffffff   
	inactive_tab_background    #6272a4   
	inactive_tab_foreground    #282a36   
	mark1_background           #ff5555   
	mark1_foreground           #282a36   
	selection_background       #44475a   
	selection_foreground       #ffffff   
	url_color                  #8be9fd   

Important environment variables seen by the kitty process:
	PATH                                /home/prateek/.cargo/bin:/home/prateek/.local/bin:/usr/src/linux-headers-5.16.0-14.1-liquorix-amd64/tools/power/x86/x86_energy_perf_policy:/usr/src/linux-headers-5.16.0-14.1-liquorix-amd64/tools/power/x86/turbostat:/usr/src/linux-headers-5.16.0-14.1-liquorix-amd64/tools/power/cpupower:/usr/src/linux-headers-5.16.0-14.1-liquorix-amd64/tools/perf:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                prateek
	LC_TIME                             en_IN.UTF-8
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	LC_MONETARY                         en_IN.UTF-8
	XDG_SESSION_CLASS                   user
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_ADDRESS                          en_IN.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_MENU_PREFIX                     gnome-
	XDG_CURRENT_DESKTOP                 Pantheon
	LC_TELEPHONE                        en_IN.UTF-8
	XDG_SESSION_DESKTOP                 pantheon
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/prateek
	LC_NAME                             en_IN.UTF-8
	LC_MEASUREMENT                      en_IN.UTF-8
	LC_IDENTIFICATION                   en_IN.UTF-8
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-pantheon:/etc/xdg
	XDG_DATA_DIRS                       /usr/share/gnome:/usr/share/pantheon:/home/prateek/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
	LC_NUMERIC                          en_IN.UTF-8
	LC_PAPER                            en_IN.UTF-8

**Comment by kovidgoyal** [comment]
How it renders depends on the font. Pick a font for bold_family that has those characters in it and they will render bold.
