### ISSUE TITLE
can't use vi edit mode in ssh unraid system

### ISSUE THREAD

**Issue by lilarcor** [kovidgoyal/kitty#4827]
using mac os 0.24.4 version, intel version cpu

ssh to unraid system
#vi
use a/i/o to enter edit mode, system will say "segmentation fault" then exit vi

**Comment by kovidgoyal** [comment]
What has this got to do with kitty? If vi is segfaulting on the remote
system that will be a bug in vi there. And make sure the kitty terminfo
files are available ont he remote system, as documented in the kitty
FAQ.

**Comment by lilarcor** [comment]
As I tested many terminal clients but got this issue with Kitty. I try to dig more.

**Comment by page-down** [comment]
The vi on slackware is `elvis`.
`elvis` version 2.2.0 is from 2003, two decades ago.
I suggest not wasting time here, just install vim or neovim instead.
