### ISSUE TITLE
launch command with formatting includes internal codes from kitty shell integration

### ISSUE THREAD

**Issue by omgold** [kovidgoyal/kitty#4829]
**Describe the bug**

When I run an external command with `launch --stdin-add-formatting  --stdin-source @screen_scrollback` and shell integration is enabled for bash, kitty escapes (\e]133)  are included in the input stream.

I don't think they should be there, as apparently nothing except kitty can interpret these.

For example, I run emacs in ansi-color mode with the launch command above, which then shows some garbage at the start of each line.

**To Reproduce**

1. enable kitty shell integration

my PS1 is 

`\[\e]133;k;start_kitty\a\]\[\e]133;A\a\]\[\e]133;k;end_kitty\a\]\[\e[1;38;5;4m\]\h \[\e[0;1m\]\W\[\e[0m\] \[\e]133;k;start_suffix_kitty\a\]\[\e[5 q\]\[\e]2;\w\a\]\[\e]133;k;end_suffix_kitty\a\]`

3. run bash in kitty
4. execute an external command with the launch options above and check the contents binary stream

With kitty integration on I get this hexdump for the last line:

```
00000000  1b 5b 6d 1b 5d 31 33 33  3b 41 1b 5c 1b 5b 31 3b  |.[m.]133;A.\.[1;|
00000010  33 34 6d 68 6f 6d 65 20  1b 5b 33 39 6d 7e 1b 5b  |34mhome .[39m~.[|
00000020  32 32 6d 20                                       |22m |
```

while without kitty integration I get:

```
00000000  1b 5b 6d 1b 5b 31 3b 33  34 6d 68 6f 6d 65 20 1b  |.[m.[1;34mhome .|
00000010  5b 33 39 6d 7e 1b 5b 32  32 6d 20                 |[39m~.[22m |
```

I think it should always be the latter.

**Environment details**

Kitty version is 0.24.4

**Comment by kovidgoyal** [comment]
They are used to mark prompt locations, and many things can interpret them other than kitty. This prompt marking protocol is over a decade old, it was pioneered IIRC by ExtraTerm. And these escape codes are a specific instance of OSC escape codes, which are half a century old. emacs needs to learn to filter them out, if it has no use for them. Note that the scrollback will contain OSC codes for marking hyperlinks as well if any are present.

If you cant get emacs to strip them out, then use a wrapper script that does it for you, its a trivial regexp, sed or something similar should be able to do it wiht no problems.
