### ISSUE TITLE
Specifically disable audio bell for different scenarios

### ISSUE THREAD

**Issue by aarav2you** [kovidgoyal/kitty#4830]
**Is your feature request related to a problem? Please describe.**
I am frustrated when the audio bell is invoked when I am using the `Tab` key to use automatic path suggesting and such, as well as the `Escape` key

**Describe the solution you'd like**
Kitty option/configuration to unmap audio bell or other solution.

**Describe alternatives you've considered**
Disabling the audio bell all-together

**Comment by page-down** [comment]
> Disabling the audio bell all-together

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.enable_audio_bell

**Comment by kovidgoyal** [comment]
the bell is sounded by your shell in those situations, you need to
configure it there. As for disabling it altogether, there is already an
option for it in kitty.conf.

**Comment by aarav2you** [comment]
@kovidgoyal Sorry for the re-open but may I ask how and where exactly can I configure these settings? I cannot find any documentation listing audio bell options for the shell. As for the disabling it altogether, it was an alternative I considered but it would be inconvenient and useless for other scenarios.

**Comment by kovidgoyal** [comment]
You would need to ask the developers of whatever shell you are using.

**Comment by page-down** [comment]
> ... how and where exactly can I configure these settings ...

Take Zsh as an example.

https://zsh.sourceforge.io/Doc/Release/Options.html

```zsh
unsetopt BEEP
```

Other shells may or may not have this setting.
In any case, if you want fine control, you need to do it within the program.
