### ISSUE TITLE
A way for the hints kitten to match across wrapped lines without including the newlines

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#4840]
**Is your feature request related to a problem? Please describe.**
I'm trying to expand my hash-matching hint mapping to match SHA-256 SRI hashes as well. This is my current attempt, `map kitty_mod+p>h kitten hints --hints-offset=0 --type regex --regex '(?m)\b((?:[0-9a-zA-Z]{7,64}|[0-9a-df-np-sv-z]{7,52})\b|sha256-[0-9a-zA-Z+/]{43}=)' --program -`. This works well enough as long as the hash isn't wrapped. But as soon as the hash is wrapped, which is fairly likely given the length of 51 characters, it breaks.

Side note: Experimenting with grouping I noticed that including more than one numbered capture group breaks matching. I assumed the hints kitten would just pick the first numbered capture group but it doesn't seem to. This is totally valid behavior but it would be really nice if the documentation made it crystal clear that you can include *at most one* numbered capture group and maybe mention to use `(?:...)` for grouping without capture if necessary.

**Describe the solution you'd like**
I'd like to be able to write my hints mappings without having to worry about line wrapping.

**Describe alternatives you've considered**
I assume this can be done by explicitly allowing a newline in the matching pattern but this isn't ideal since it would end up in the output.

**Additional context**
Here's an example of a scrollback where the hash gets wrapped in a terminal of 80 columns wide:

```
Welcome to fish, the friendly interactive shell
toonn@terra ~> nix-hash --type sha256 --to-base32 sha256-uctZxqbajPTb7l27Vpx8yVpnQTkuaQU1ROD0CxWrmtU=
1mcsmcahpx708hshas9f750nfnn9gjf5dfsxxvdz936slv35kjxr
```

**Comment by kovidgoyal** [comment]
When there is no explicit line-break it will match fine. When there are
explicit line breaks, you will need to modify your regex to include the
null \x00 and newline \n chars.

For example, 

kitty -o 'map f1 kitten hints --type=regex --regex "start[a-zA-Z\x00\n]+end" --program -' sh -c 'echo startXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYZZZZZZZZ; echo LLLLLLLLLLLLLLLLLLLLLLLend; read'

This will match the echoed text even though there is an explicit line
break.

**Comment by toonn** [comment]
Then why does my regex work if I run it on a file with the contents I listed in the OP, like this `cat test.kitty | kitty +kitten hints --hints-offset=0 --type regex --regex '(?m)\b((?:[0-9a-zA-Z]{7,64}|[0-9a-df-np-sv-z]{7,52})\b|sha256-[0-9a-zA-Z+/]{43}=)' --program @`. But not when I invoke the mapping with the same contents in the terminal, presumably because of the wrapped line?

**Comment by kovidgoyal** [comment]
Because the shell is inserting a hard line break

**Comment by toonn** [comment]
Adding `\n` to the character class doesn't help though, I tried that before. And even if it can be done that means the newline is included in the match. Is there nothing Kitty can do to detect the wrapping?

Alternatively, is it possible to pipe the match through a command when using `-` and `@`?

**Comment by kovidgoyal** [comment]
On Fri, Mar 18, 2022 at 05:35:17AM -0700, toonn wrote:
> Adding `\n` to the character class doesn't help though, I tried that before. And even if it can be done that means the newline is included in the match. Is there nothing Kitty can do to detect the wrapping?

You need \n and \0 

> 
> Alternatively, is it possible to pipe the match through a command when using `-` and `@`?

I suggest you write a custom matcher as described here:
https://sw.kovidgoyal.net/kitty/kittens/hints/#completely-customizing-the-matching-and-actions-of-the-kitten

**Comment by adrian-gierakowski** [comment]
@kovidgoyal any idea why would fish insert a line break in this case? On my system it does it but only when used with kitty (it doesn't do it when ran in konsole). Bash doesn't do it in either. I've been using fisth+kitty since a couple of years and I'm sure it didn't used to happen, so I think it's due to some relatively recent changes in fish or kitty. Thanks!

**Comment by kovidgoyal** [comment]
Sorry, I am not a fish user so I have very little knowledge about it.
