### ISSUE TITLE
[FR] CRT effects?

### ISSUE THREAD

**Issue by vanfanel** [kovidgoyal/kitty#4842]
**Is your feature request related to a problem? Please describe.**
Hi! I have found that Kitty comes VERY close to my ideal/dream terminal emulator for Wayland (it even works as a Wayland compositor itself, which is beyond awesome!!!)

However, I am missing an small/big detail: CRT effects.
Since Kitty does everything regardding graphics on the GPU, can it please support GLSL shaders?
The RetroArch project has hundreds of them, with curvature effects, scanlines, masks... you name it.

Here's a (seemingly abandoned) terminal emulator that has GLSL shader support: https://github.com/carld/crt-term

**Describe the solution you'd like**
Since Kitty already has it's own shaders, maybe it could support loading GLSL shaders, which would look very, very good.

**Describe alternatives you've considered**
Maybe, instead of loading GLSL shaders, a simple fixed curvature+scanlines+mask shader would be enough?

**Additional context**
CRT-look adds "life" and an organic feel to the console: text becomes "alive" and is very pleasant to look at and work with, at least if using 80 columns :)

**Comment by kovidgoyal** [comment]
Not something I am interested in, sorry.

**Comment by rogueai** [comment]
@vanfanel perhaps this is close to what you're looking for https://github.com/Swordfish90/cool-retro-term

**Comment by vanfanel** [comment]
> @vanfanel perhaps this is close to what you're looking for https://github.com/Swordfish90/cool-retro-term

That depends on too much stuff... :( Will never make it to Wayland.
