### ISSUE TITLE
[bug] When tmux's status line update, ibus input method window will change its position.

### ISSUE THREAD

**Issue by Freed-Wu** [kovidgoyal/kitty#4849]
**Describe the bug**
A very weird bug. When tmux's status line update, ibus input method window will change its position.

**To Reproduce**
1. tmux config is as following:
```
set -g status-right "%S"
```

'%S' is the current second. By default, tmux will update status line after 15 second.

2. Open tmux, by default, tmux will open a shell. Any shell is OK, even if you open a vim in the shell. You can also watch this bug.

3. Change your input method. I use ibus-libpinyin. As this picture. I input some characters.
![Screenshot from 2022-03-19 23-39-46](https://user-images.githubusercontent.com/32936898/159128299-8f7b80f9-c568-4126-a9fe-a043581d7925.png)

4. Wait tmux update its status line. ibus input method window will change its position. It is confused, the change of position make me cannot use input method conveniently.
![Screenshot from 2022-03-19 23-39-31](https://user-images.githubusercontent.com/32936898/159128311-a422c361-177d-4c2c-b899-0c534a99afe9.png)

**Environment details**

```
kitty 0.24.4 created by Kovid Goyal
Linux arch 5.16.15-arch1-1 #1 SMP PREEMPT Thu, 17 Mar 2022 00:30:09 +0000 x86_64
Arch Linux 5.16.15-arch1-1 (/dev/tty)
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/wzy/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.75
bold_font                  JetBrains Mono Bold Nerd Font Complete Mono
bold_italic_font           JetBrains Mono Bold Italic Nerd Font Complete Mono
dynamic_background_opacity True
font_family                JetBrains Mono Regular Nerd Font Complete Mono
font_features:
{'FiraCode-Regular': ('+ss06', '+ss07')}
font_size                  10.0
italic_font                JetBrains Mono Italic Nerd Font Complete Mono
tab_bar_style              powerline
Added shortcuts:
	shift+enter → send_text all \x1b[13;2u
	ctrl+enter → send_text all \x1b[13;5u
	ctrl+shift+space → next_tab
	ctrl+shift+d → scroll_page_down
Changed shortcuts:
	ctrl+shift+g → scroll_home
	ctrl+shift+u → scroll_page_up
	ctrl+shift+z → scroll_end

Important environment variables seen by the kitty process:
	PATH                                /home/wzy/Applications:/home/wzy/.local/bin:/home/wzy/.local/share/nautilus/scripts:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	VISUAL                              vi
	EDITOR                              vi
	SHELL                               /bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :1
	USER                                wzy
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
```

By the way, `$GLFW_IM_MODULE` is `ibus`.

**Additional context**

If I use other terminal, like `gnome-terminal`, the bug will not happen. And If my recall is right, I think this bug don't happen in the former kitty. I found this bug in the past, but I don't know what program make it in that time.

**Comment by page-down** [comment]
This is because during typing, the pre-edit text will be updated to the latest cursor location, and the ime position will be updated.

Perhaps a debounce mechanism could be added, which could be configured by the user. For example, ignore (delay) frequent updates within 0.2 seconds.
(User can adapt dynamically based on the running program via watcher or other means.)

I have found in other programs that will update multiple locations periodically that the pre-edit text will only keep the last character and will not redraw when the leading characters are cleared.

**Comment by kovidgoyal** [comment]
IME is a horrible hack. There's no way to fix this in general. IME window has to follow the cursor position and terminal programs have to move the cursor to update their UI. Therefore, any program that updates UI while the user is typing is going to be broken. One can try workarounds like debounce etc but they are just bandaids. You are welcome to send a PR for debounce and I will review, but in general I dont think this can be fixed. The fundamental design of terminals and IME are incompatible.

**Comment by Freed-Wu** [comment]
This bug will not occur in other terminal (gnome-terminal), although I don't know why:smile:

**Comment by kovidgoyal** [comment]
Who knows maybe they special case it or debounce it or something.

**Comment by kovidgoyal** [comment]
See if this commit helps: https://github.com/kovidgoyal/kitty/commit/5a36fbfe7bee43830586ed06bb6b2a2dc5843550

**Comment by page-down** [comment]
> See if this commit helps: `5a36fbf`

Thanks, this definitely helps.
In the specified scenario, I don't see the pre-edit text flying around anymore.
