### ISSUE TITLE
After installing kitty "xdg-open ." opens directory in a new terminal

### ISSUE THREAD

**Issue by LoyalPotato** [kovidgoyal/kitty#4850]
**Describe the bug**
After installing the kitty terminal emulator and running `xdg-open .` opens the current directory in a new kitty terminal. Previously it would open in the regular interface of manjaro (I'm sorry I don't know the technical term :)).

Running the command `xdg-mime query default inode/directory` returns kitty-open.desktop.
But I never changed it to kitty-open.

**To Reproduce**
1. Install kitty
2. Execute `xdg-open .`
3. New terminal opens with that directory

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux LoyalPotatoPC 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64
Manjaro Linux 5.15.28-1-MANJARO  (LoyalPotatoPC) (/dev/tty)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.5
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/loyalpotato/.config/kitty/kitty.conf

Config options different from defaults:
background_image        /home/loyalpotato/Pictures/Wallpapers/FLCL/29.png
background_image_layout scaled
background_opacity      0.8
background_tint         0.4
disable_ligatures       2
font_family             CaskaydiaCove Nerd Font
font_size               12.0

Important environment variables seen by the kitty process:
	PATH                                /home/loyalpotato/.nvm/versions/node/v16.13.2/bin:/home/loyalpotato/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/loyalpotato/.yarn/bin:/home/loyalpotato/Android/Sdk/emulator:/home/loyalpotato/Android/Sdk/tools:/home/loyalpotato/Android/Sdk/tools/bin:/home/loyalpotato/Android/Sdk/platform-tools
	EDITOR                              vim
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                loyalpotato
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/loyalpotato/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```
**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
In the latest version of kitty, the ability to open directory is defined.

/usr/share/applications/kitty-open.desktop
```text
[desktop]
# ...
MimeType=image/*;application/x-sh;inode/directory;text/*;x-scheme-handler/kitty;
```

You need to configure the default open program yourself.

https://wiki.archlinux.org/title/Xdg-utils#xdg-mime

```shell
grep directory /usr/share/applications/mimeinfo.cache
xdg-mime default my-default-app.desktop inode/directory
```

**Comment by LoyalPotato** [comment]
Sorry for the trouble, but I ended up arriving at your solution too hahaha. Realised that my user config was just using the wrong program name for inode/directory and because of that it used kitty-open.desktop.

Thanks for the help :)

**Comment by ShivamJoker** [comment]
I am still facing this issue please help, I removed the cache file
