### ISSUE TITLE
Disable font type face bold for bold txt and line height and letter spacing setting

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#4854]
Hello expert,

I am new to kitty terminal. It's awesome and thanks for such a great tool. Second i need some help i checked the documentation and tried multiple setting but nothing helping so thought to take experts help.

I have noticed in Kitty bold text get highlighted in extra bold txt like below screenshot .. this is "ls -halt" command output and see my folders name looks super thick.. i don't want this how to let kitty not add extra bold for bold txt 

Second i also wants to know about line height and line spacing to increase vertical space between 2 lines and letter spacing.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/11479557/159179643-056fd504-4223-4f76-8da4-5a758ed7b45d.png">

One more issue i have noticed in my macbook. i can also not able to use my alt key as option in tmux to copy txt  i have that setting turn on in config 

macos_option_as_alt yes

**Comment by kovidgoyal** [comment]
Look in kitty.conf for bold_family and adjust_line_height

**Comment by ciscohack** [comment]
@kovidgoyal Thanks for the response i checked and tried but still it was showing me bold ..will try again line_height setting seem different as i sent value 2 but not seen any effect of that .. would please help me to know why in my macOS alt key not work as option to select lines/words in tmux..

**Comment by ciscohack** [comment]
@kovidgoyal Sorry my friend for to many query  but one last help if you could suggest would be a big help.

How can i remove or hide this black think border around my terminal.. i tried border width to 0 but that not solving the problem..

<img width="131" alt="image" src="https://user-images.githubusercontent.com/11479557/159209047-65de40c2-bc1e-486b-a77a-e396a5e6dc28.png">

**Comment by page-down** [comment]
> I don't see option like ...

See the following documentation for all options. That's `bold_font`.
https://sw.kovidgoyal.net/kitty/conf/

> ...  i sent value 2 but not seen any effect of that ...

You need to set more than the current cell height for the difference to appear.

>  ... i can also not able to use my alt key as option in tmux to copy txt ...
> macos_option_as_alt yes

I don't know what key you are pressing.
With this option set, tmux's default shortcut `C-b, M-Left/Right` to adjust pane width works fine.
You need to try it yourself and adjust the key mapping. If needed, you can also configure it in kitty to have key combinations send the desired key escape sequences.
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program

> How can i remove or hide this black think border around my terminal ...

The size of each cell in kitty is the same, and blank margins will appear when the total width does not match the window width and cannot be avoided. It is also unavoidable if multiple windows are created in one OS window. If it is not a full screen window, you can try `resize_in_steps` to make sure there are no extra margins when resizing the window.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.resize_in_steps

You can also mitigate this problem by not using a different background color in your program (e.g. vim).

**Comment by ciscohack** [comment]
@kovidgoyal Thanks my fried for detailed update but sorry to say i still seeing issue. i tried below settings with yes/no but whenever i change theme with kitty +kitten theme and pick theme it shows a thick border around the terminal not looks good also i have observed theme by click enter move like layer curtain flow.

it's like window within window 

macos_window_resizable no
resize_in_steps no

<img width="294" alt="image" src="https://user-images.githubusercontent.com/11479557/159419175-23cf3819-9514-4c2b-9c87-b5f2752d44aa.png">

I also love to know the option to hide my tmux window on top of menu bar.  I know there is one setting for macOS to disable it but it breaking some functionality in my terminal 

macos_show_window_title_in all <<---- with this setting i am able to hide it but this cause some other issue for my environment. Can't we get simple option just to hide that only 

<img width="721" alt="image" src="https://user-images.githubusercontent.com/11479557/159419619-96b51435-af19-4885-bdf7-6954a1583540.png">


<img width="236" alt="image" src="https://user-images.githubusercontent.com/11479557/159419256-2510a583-18f2-499e-acfc-37ce679d051d.png">

**Comment by ciscohack** [comment]
@kovidgoyal Okay i figure out the setting was causing the problem. below setting was causing this issue.

macos_show_window_title_in none
hide_window_decorations yes

But i need one help from you. first how to hide the traffic light button on terminal left side and titlebar to make my terminal looks minimal.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/11479557/159422648-7325677d-bc5c-4e1a-b762-f895e4c644f6.png">

**Comment by ciscohack** [comment]
@kovidgoyal Thanks once again for amazing tool .. just only issue is people have to read lots of doc to understand 😜 but it' awesome.. I have fixed the issue and understand it now also.

One think i would like to check "kitty +kitten theme" command way theme selection work but it not persist after restart theme went away.. how can i make it persistent.

**Comment by ciscohack** [comment]
@kovidgoyal I thought i fixed the issue completely but it seems there is some issue with layout whenever i choose theme from kitty +kitten theme .. border still shows some extra width and unsyn and looks bad

<img width="298" alt="image" src="https://user-images.githubusercontent.com/11479557/159437243-92ee784b-65d6-4c78-be5c-88f07804e6f9.png">

**Comment by Luflosi** [comment]
Try to set `initial_window_width` and `initial_window_height` to a value with `c` at the end, for example
```
remember_window_size  no
initial_window_width  80c
initial_window_height 28c
```
See https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remember_window_size.
To keep the window size a multiple of the cell size when resizing use
```
resize_in_steps yes
```
To hide the window title and make the top part of the window the same color as the rest, try
```
macos_show_window_title_in none
macos_titlebar_color background
```
To instead hide the title bar completely including the three buttons, try
```
hide_window_decorations titlebar-only
```

**Comment by ciscohack** [comment]
@Luflosi Thanks a lot

**Comment by ciscohack** [comment]
@Luflosi Now i have the exact config what you just suggested in my kitty.conf and now behaviour is like this 

below 3 config i put in my kitty.conf :--
resize_in_steps yes
macos_show_window_title_in none
macos_titlebar_color background

Now bottom of terminal have empty space rest all other corner is now okay
