### ISSUE TITLE
Victor Mono NF looks wider than expected?

### ISSUE THREAD

**Issue by starptr** [kovidgoyal/kitty#4859]
**Describe the bug**
Victor Mono looks like it gets rendered wider than shown on its demo page.

**To Reproduce**
1. Install VictorMono NF.
2. Compare sizes of each letter.

**Screenshots**
Size of cell on kitty: 
![image](https://user-images.githubusercontent.com/10691605/159386350-ca901cc5-ae53-493f-83ab-7b70924a9305.png)

Size of cell on demo:
![image](https://user-images.githubusercontent.com/10691605/159386447-c10fef44-ff75-44b7-8dcf-a606e4a0532d.png)

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Darwin MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.0.1 BuildVersion:	21A559
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/yuto/.config/kitty/kitty.conf

Config options different from defaults:
font_family VictorMono Nerd Font Mono Regular
font_size   14.0

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                yuto
```

**Additional context**
This should be reproducible by using the config:
```
font_family      VictorMono Nerd Font Mono Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
```

**Comment by page-down** [comment]
Don't use patched fonts. Instead, use the standalone Symbols Nerd Font.

https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

Try to adjust the cell width.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.adjust_line_height

**Comment by starptr** [comment]
Hm I can't get it to quite work using the unpatched font either:
![image](https://user-images.githubusercontent.com/10691605/159388910-1eff3d05-8a26-42d3-9cf6-1c62bbce9053.png)

with
```
kitty 0.24.4 created by Kovid Goyal
Darwin MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.0.1 BuildVersion:	21A559
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/yuto/.config/kitty/kitty.conf

Config options different from defaults:
adjust_column_width -1
font_family         Victor Mono Regular
font_size           14.0

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                yuto
```

I tried to adjust the `adjust_column_width` as well but it's still not quite right; I can get close to the demo width but then each character shrinks .. in the wrong way? 
![image](https://user-images.githubusercontent.com/10691605/159389137-cd24433d-d61e-48da-b44b-560d5cf9fede.png)

**Comment by page-down** [comment]
In kitty, each cell is rendered in parallel and cached.
You need to make sure the width can fit bold, italic, or it will be cropped.
It is not possible to achieve the same font rendering results as your browser.
