### ISSUE TITLE
Incomplete font list

### ISSUE THREAD

**Issue by wavexx** [kovidgoyal/kitty#486]
Are there some restrictions done by kitty to the list of available fonts?
The list shown by 'list-fonts' is just a fraction of the fonts I normally can use.
I'm trying to use "PragmataPro", which is a commercial monospace ttf.
The font is is listed by "fc-list", so I wonder why it isn't usable by kitty.

**Comment by kovidgoyal** [comment]
It has to report itself as monospace, that is have a spacing property 100 not 90 or 110 which some badly designed monospace fonts report. 

```
fc-list : family spacing | grep spacing
```

**Comment by wavexx** [comment]
On Mon, Apr 23 2018, Kovid Goyal wrote:
> It has to report itself as monospace, that is have a spacing property
> 100 not 90 or 110 which some badly designed monospace fonts report.

Ok, it turns out most of the fonts I'm interested are actally
dual-width.

Is there a plan to support those?
