### ISSUE TITLE
Mouse cursor large when on the kitty window under GNOME

### ISSUE THREAD

**Issue by hellobbn** [kovidgoyal/kitty#4860]
**Describe the bug**
I am using a system running GNOME 42.0 (Wayland). The mouse cursor becomes large when it is
moved to the kitty window.

The scaling factor of the screen is 1, while I do enable [Fractional Scaling](https://wiki.gnome.org/Initiatives/FracionalScaling) on the other screen with a scaling factor 1.25.

The kitty does print some error messages, see the logs below

**To Reproduce**
1. Run under GNOME 42.0
2. Open kitty
3. Observe the mouse cursor size

**Screenshots**
Mouse cursor on kitty:
![image](https://user-images.githubusercontent.com/10683168/159412383-3e8148bb-9016-427c-87fa-9b27b5e7ce74.png)

Mouse cursor on other applications:
![image](https://user-images.githubusercontent.com/10683168/159412431-b9aac877-8792-4d98-9ad7-3cffe38f4743.png)

**Environment details**
The logs from kitty `kitty --debug-gl`
```
[081 13:17:49.447111] Ignoring unknown config key: open_url_modifiers
[081 13:17:49.447208] Ignoring unknown config key: rectangle_select_modifiers
[081 13:17:49.447224] Ignoring unknown config key: terminal_select_modifiers
Created decoration buffers at scale: 1 vertical_height: 836 horizontal_width: 824
top-level configure event: size: 0x0 states: 
final window content size: 800x800
Setting window geometry in configure event: x=0 y=-24 800x824
GL version string: '4.6 (Core Profile) Mesa 21.3.7' Detected version: 4.6
top-level configure event: size: 800x824 states: TOPLEVEL_STATE_ACTIVATED 
final window content size: 800x800
Setting window geometry in configure event: x=0 y=-24 800x824
Resizing framebuffer to: 800x800 at scale: 1
prompt_marking: x=0 y=0 op='A'
prompt_marking: x=4 y=0 op='B'
[081 13:17:49.659322] [glfw error 65544]: on_gnome_cursor_theme_read: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
[081 13:17:49.659337] [glfw error 65544]: on_gnome_cursor_size_read: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
prompt_marking: x=0 y=0 op='A'
prompt_marking: x=4 y=0 op='B'
top-level configure event: size: 800x824 states: 
final window content size: 800x800
Setting window geometry in configure event: x=0 y=-24 800x824
```

Kitty Version: `kitty --version`:
```
kitty 0.24.4 created by Kovid Goyal
```

**Additional context**
I can reproduce the error with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
kitty does not integrate with GNOME. Given that GNOME is a PoS that
breaks things with every release and cant provide even basic
features like window decorations (#3284), or a working window manager
(#4802), I dont have any interest in maintaining GNOME integration. 
There is currently some code in kitty that queries GNOME via DBUS for
cursor sizes but it's quite likely GNOME broke that in 42, patches
welcome, see linux_desktop_settings.c

Assuming the DBUS queries are indeed brokem, you can control the mouse
cursor size in kitty with the freedesktop.org XCURSOR_SIZE environment
variable.

**Comment by zvonkok** [comment]
@hellobbn Can you try to start `kitty` from a shell and look for errors? On my system I see: 

```
083 13:23:28.622763] [glfw error 65544]: on_gnome_cursor_theme_read: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
[083 13:23:28.622777] [glfw error 65544]: on_gnome_cursor_size_read: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
```

The resolution for that, is to install `xdg-desktop-portal` and `xdg-desktop-portal-gtk` after that your mouse cursor should be the same size in `kitty` and GNOME. 

@kovidgoyal FYI ^^ (BTW great terminal emulator 🥇 )

**Comment by guidosti** [comment]
Hi, for future users of gnome who have the same issue. For me the solution was set linux_display_server in x11 value. That syncronized the gnome theme with kitty and resolved my mouse cursor issue. Hope it work for you.

**Comment by JasonBoyett** [comment]
@guidosti
mind dropping a shell command to do that?

**Comment by guidosti** [comment]
> @guidosti mind dropping a shell command to do that?

there is non. You have to put that value in the config file of kitty, as far as I remember.
