### ISSUE TITLE
Inconsistent behavior from "New OS WIndow"

### ISSUE THREAD

**Issue by codevbus** [kovidgoyal/kitty#4864]
**Describe the bug**
When clicking "New OS Window" or using `ctrl+shift+n` on MacOS after Kitty has been launched, the options in `macos-launch-services-cmdline` no longer seem to apply.

**To Reproduce**
1. Set some options in `macos-launch-services-cmdline`. In my case: `--single-instance tmux new-session -A -s main`
3. Launch a fresh instance of Kitty, works as expected.
4. Use the GUI/Dock to launch a "New OS Window", or use `ctrl+shift+n`. 
5. Subsequent opened windows do not read from this file. 

In order to eliminate `tmux` as a possible culprit, I also tried a simplistic config with `--single-instance sh -c "echo 'foo'"`, the observed behavior was the same.

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Darwin ip-192-168-0-182.us-west-1.compute.internal 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.2.1 BuildVersion:	21D62
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/mike/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    y
background_opacity      0.85
font_family             Hack Nerd Font Mono
font_size               14.0
hide_window_decorations 1
Colors:
	active_border_color     #545862   
	active_tab_background   #282c34   
	active_tab_foreground   #abb2bf   
	background              #282c34   
	color0                  #282c34   
	color1                  #e06c75   
	color10                 #98c379   
	color11                 #e5c07b   
	color12                 #61afef   
	color13                 #c678dd   
	color14                 #56b6c2   
	color15                 #c8ccd4   
	color16                 #d19a66   
	color17                 #be5046   
	color18                 #353b45   
	color19                 #3e4451   
	color2                  #98c379   
	color20                 #565c64   
	color21                 #b6bdca   
	color3                  #e5c07b   
	color4                  #61afef   
	color5                  #c678dd   
	color6                  #56b6c2   
	color7                  #abb2bf   
	color8                  #545862   
	color9                  #e06c75   
	cursor                  #abb2bf   
	foreground              #abb2bf   
	inactive_border_color   #353b45   
	inactive_tab_background #353b45   
	inactive_tab_foreground #565c64   
	selection_background    #abb2bf   
	selection_foreground    #282c34   
	tab_bar_background      #353b45   
	url_color               #565c64   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                mike

```

**Comment by page-down** [comment]
This works as expected. That option is only applied when launched by macOS launchd.

If you need to specify the window at startup, you can use `startup_session`.
https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

If you want to use shortcuts to run some program, you should set up key mapping.

**Comment by codevbus** [comment]
> This works as expected. That option is only applied when launched by macOS launchd.
> 
> If you need to specify the window at startup, you can use `startup_session`. https://sw.kovidgoyal.net/kitty/overview/#startup-sessions
> 
> If you want to use shortcuts to run some program, you should set up key mapping.

Ah. I misunderstood the functionality then. Thanks for clearing it up.

Can you confirm that I should be able to achieve the desired behavior by specifying a default session file in `kitty.conf` with the same configuration?

**Comment by page-down** [comment]
You can try the following configuration.

```conf
# kitty.conf
startup_session startup_session.conf
map ctrl+shift+n launch --type=os-window tmux new-session -A -s main
```

```conf
# startup_session.conf
launch tmux new-session -A -s main
```

The first one is already the default new OS window, so `new_os_window`, `focus` are redundant.
You need to use `launch` in the session file to run the specified program, `tmux ...` is invalid.

**Comment by codevbus** [comment]
Thanks for the suggestion. With your config, `ctrl+shift+n` behaves as expected, attaching a new window with the tmux session properly attached. 

However, "Create New OS Window", from either clicking on the Dock icon or `⌘N`, still does not read any settings from either `macos-launch-services-cmdline` or `startup_session.conf`

**Comment by page-down** [comment]
> However ... still does not read any settings from ...

The new OS window is not the same as the new kitty instance (process), so the `inconsistent behavior` you are referring to is not valid.

As I said, this works as expected.

You may find that there is an `action_alias` configuration option that can override existing actions, but this does not work for menu items.
For now, the macOS menu items (including the Dock icon context menu) are not customizable.

```conf
action_alias new_os_window launch --type=os-window tmux new-session -A -s main
map ctrl+shift+n new_os_window
map cmd+n new_os_window

# The last one will be used as a menu shortcut and will act as the default behavior.
map opt+cmd+n new_os_window
```

**Comment by codevbus** [comment]
> > However ... still does not read any settings from ...
> 
> The new OS window is not the same as the new kitty instance (process), so the `inconsistent behavior` you are referring to is not valid.
> 
> As I said, this works as expected.
> 
> You may find that there is an `action_alias` configuration option that can override existing actions, but this does not work for menu items. For now, the macOS menu items (including the Dock icon context menu) are not customizable.
> 
> ```
> action_alias new_os_window launch --type=os-window tmux new-session -A -s main
> map ctrl+shift+n new_os_window
> map cmd+n new_os_window
> 
> # The last one will be used as a menu shortcut and will act as the default behavior.
> map opt+cmd+n new_os_window
> ```

Thank you. This gets me part of the way there, however cmd+n is now completely unresponsive if I try to launch a new window if I'm not on the workspace where an existing kitty terminal is. Looks like I'll probably need some kind of wrapper script to get the behavior I want.
