### ISSUE TITLE
Explain how to multiplex (tmux like)

### ISSUE THREAD

**Issue by metal3d** [kovidgoyal/kitty#4865]
**Is your feature request related to a problem? Please describe.**
The problem is explain in #391 and #2422

**Describe the solution you'd like**
This is what I often need:
- laptop ssh to server
- in the server I launch a "tmux" session to start a long calculation (machine learning training)
- I can now detach the session and disconnect ssh server

Later:
- laptop ssh server
- tmux attach-session

In the tmux session, I sometimes need to work with neovim, check GPU usage, and so on. Each time, using kitty, it makes other terminals very slow.

I understand that you provides daemon and protocols to make this possible. But I really don't understand how to do. Mentionned issues seems to explain how to create multiplex session in the same computer, not on a server (I can install kitty on the server)

So, it could be great to explain how to avoid the use of tmux in a distant server for this kind of workflow ;)

**Comment by page-down** [comment]
> ... using kitty, it makes other terminals very slow.

I have not experienced kitty taking up a lot of CPU or GPU resources.

> I understand that you provides daemon and protocols to make this possible. ... I can install kitty on the server ...

Unfortunately, kitty's daemon mode is not available yet.
I still need to use tmux daily.

**Comment by kovidgoyal** [comment]
dup of #391

**Comment by metal3d** [comment]
> > ... using kitty, it makes other terminals very slow.
> 
> I have not experienced kitty taking up a lot of CPU or GPU resources.

I'm not the only one if I trust #391 - as soon as a tmux session is displayed (via ssh), others terminal as a lot of problems (cursor is hard to move in neovim, typing command or text is slow...)

> 
> > I understand that you provide daemon and protocols to make this possible. ... I can install kitty on the server ...
> 
> Unfortunately, kitty's daemon mode is not available yet. I still need to use tmux daily.

I can also use `screen` but there are other problems (terminal width is not well defined), maybe I could find another multiplexing solution :(
