### ISSUE TITLE
ECMA-48 SGR 1 not handled correctly

### ISSUE THREAD

**Issue by neilg** [kovidgoyal/kitty#4868]
Text is hard to read in darker themes because SGR 1, as defined in ECMA-48 is not handled correctly. SGR 1 means "bold or increased intensity". Most terminals handle this with brighter colours, bold text and brighter colours, or allow the user to choose between bold or bright. Kitty should provide the option to choose to map SGR 1 to bold, to bright, or to both bold and bright. I understand from discussions in #197 and #512 that Kitty uses SGR 90-97, which I believe are non-standard IBM extensions.

The definitions of SGR codes I'm using come from [ECMA-48](https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf) page 61.

**To Reproduce**
1. Configure Alacritty and Kitty to use gruvbox dark
2. See that the text is much harder to read in Kitty (see screenshot)

**Screenshots**
On the right Alacritty with birght clear text, on the left Kitty which is much harder to read.
![Screenshot-2022-03-23T13:36:44,873456947+00:00](https://user-images.githubusercontent.com/563627/159713044-9207ed12-1d92-4ac4-83c2-585361e26b4b.png)

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux pinot 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64
Arch Linux 5.16.16-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/fish
Loaded config files:
  /home/neil/.config/kitty/kitty.conf

Config options different from defaults:
font_family            Comic Mono
font_size              9.0
initial_window_height  (48, 'cells')
initial_window_width   (80, 'cells')
remember_window_size   False
wayland_titlebar_color 1
Colors:
	background             #282828   
	color0                 #282828   
	color1                 #cc241d   
	color10                #b8bb26   
	color11                #fabd2f   
	color12                #83a598   
	color13                #d3869b   
	color14                #8ec07c   
	color15                #ebdbb2   
	color2                 #98971a   
	color3                 #d79921   
	color4                 #458588   
	color5                 #b16286   
	color6                 #689d6a   
	color7                 #a89984   
	color8                 #928374   
	color9                 #fb4934   
	cursor                 #ebdbb2   
	foreground             #ebdbb2   

Important environment variables seen by the kitty process:
	PATH                                /home/neil/.local/bin:/home/neil/.cargo/bin:/usr/bin/vendor_perl:/usr/local/sbin:/usr/local/bin:/usr/bin
	LANG                                en_GB.UTF-8
	EDITOR                              /usr/bin/kak
	SHELL                               /bin/fish
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                neil
	XCURSOR_SIZE                        24
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      4
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Comment by kovidgoyal** [comment]
Please dont open duplicate issues and waste my time.

**Comment by neilg** [comment]
The rationale you gave in other issues for not addressing this is incorrect. The standard way of applying brightness is SGR 1.

**Comment by kovidgoyal** [comment]
You stating things are incorrect doesnt make them incorrect
