### ISSUE TITLE
Draw off-screen to the left?

### ISSUE THREAD

**Issue by lf94** [kovidgoyal/kitty#4870]
Is it possible to draw an image a bit off the screen to the left?

**Comment by kovidgoyal** [comment]
You can choose whatever part of the image to draw in whatever part of
the screen you like. See
https://sw.kovidgoyal.net/kitty/graphics-protocol/

**Comment by lf94** [comment]
Aaaah yes, sorry, I couldn't put two-and-two together and simply adjust with w and h!
