### ISSUE TITLE
Keep aspect ratio while scaling?

### ISSUE THREAD

**Issue by lf94** [kovidgoyal/kitty#4872]
It would be nice if when scaling, there is an option to keep aspect ratio.

Here's an example of where this would be nice:

![1648101858](https://user-images.githubusercontent.com/547923/159852695-905c6f75-cb54-4425-bff2-4c9228341eb8.png)

While it's ok the smaller images don't keep aspect ratio, the very large one could really use it.

I'm scaling using the c and r options as the TUI library I'm using is based on columns and rows (tui-rs).

**Comment by kovidgoyal** [comment]
Simply specify the region to be scaled with the aspect ratio you want.
