### ISSUE TITLE
Optional confirmations for multi-line paste and very long paste

### ISSUE THREAD

**Issue by rebane2001** [kovidgoyal/kitty#4873]
**Is your feature request related to a problem? Please describe.**
Pasting into a terminal can cause security issues when the clipboard content is multiline, and performance issues when the content is too long.

**Describe the solution you'd like**
As many other terminals do, it would be great to have an (optional) confirmation when pasting multiline or long content, preferably with  a preview. Here is an example of how it can be implemented:

![image](https://user-images.githubusercontent.com/6316541/159889403-dc8a29f9-9029-444e-a320-de4f91534081.png)
![image](https://user-images.githubusercontent.com/6316541/159889428-73f842bd-cd2b-4a27-82af-51e02a0d8b2c.png)

Of course it wouldn't have to be an external dialog box, this is just an example.

**Describe alternatives you've considered**
The bracketed paste feature can protect a shell, but this is dependent on the shell supporting it. This is a non-issue for your local shell, but it becomes a problem when SSHing into servers with bracketed paste not enabled. For example, bash in a default Ubuntu Server install does not have bracketed paste enabled, and the busybox sh binary does not support the feature at all. Doing the paste-checking in the terminal emulator instead applies the protection everywhere.

**Additional context**
This should be an optional configurable feature, as some people find bracketed paste sufficient.

**Comment by kovidgoyal** [comment]
Not something I care about personally. I have never seen an actual
problem caused by pasting anything in a shell in real world usage in over
thirty decades despite all the internet fulminations about it. So I lack
the motivation to implement this. But patches are most welcome. You can
use the confirmation for allowing programs to read from the clipboard as
a guide to implementing it.

**Comment by page-down** [comment]
Thanks for adding this new feature.
This looks like it could be applied to drag and drop files (URLs with or without newline).

https://github.com/kovidgoyal/kitty/issues/4734

If you don't have a need for this, do you have a suggestion for a more generic name?

**Comment by linnabraham** [comment]
Seems like the feature doesn't work now. 
This is my kitty conf
```
shell_integration enabled
paste_actions quote-urls-at-prompt,confirm
```

The quoting url thing works. But I dont get any confirmation dialog when pasting multiline text.

**Comment by kovidgoyal** [comment]
Newlines are confirmed only if bracketed paste is not enabled by the
program running in the terminal, as they are not dangerous when
bracketed paste is on.

**Comment by linnabraham** [comment]
I don't know exactly what bracketed paste is. 

But let me ask this,  my issue is that sometimes when copy pasting commands into a terminal,  there is an extra new line which causes cmds to be executed before i have edited it. 

I am not concerned about security issues but just convenience. So does kitty allow this?

**Comment by rebane2001** [comment]
Bracketed paste does not execute the command if you paste multiple lines.

**Comment by kovidgoyal** [comment]
Turn on bracketed paste in your shell, this has nothing to do with
kitty.

**Comment by linnabraham** [comment]
I am using zsh, I cannot find a proper resource documenting this bracketed paste and how to use. Most of the discussions are surrounding bash and readline .

**Comment by rebane2001** [comment]
zsh uses bracketed paste by default in most configurations, just look up "zsh bracketed paste" or something. This has nothing to do with the terminal emulator.
