### ISSUE TITLE
Allow start-as-fullscreen be configured in kitty.conf

### ISSUE THREAD

**Issue by Freed-Wu** [kovidgoyal/kitty#4882]
**Describe the solution you'd like**
In kitty.conf, add a new option to configure the start-as:

```
start_as fullscreen
```

Command line will be prior than kitty.conf

Because kitty.conf cannot control start-as method, so I have to write `~/.local/share/applications/kitty.desktop` to override `/usr/share/applictions/kitty.desktop`. It is troublesome. I think configure it in kitty.conf is a good idea.

**Comment by kovidgoyal** [comment]
It's fairly unusual to always want to start your terminal fullscreen, as
such I dont think this belongs in kitty.conf. As it its, it is easy
enough to achieve that result using --start-ass and modifying the
launcher.
