### ISSUE TITLE
Kitty on macOS not identify the installed fonts and throw font not found error

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#4884]
Hello Expert,

Seems kitty is not well optimised for macOS. I have many nerd fonts installed and working fine but just noticed kitty not identified those fonts and fallback to default setting.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/11479557/160228162-079d26e0-db28-43c1-98bb-76c9495372ab.png">

What is this error and how can i fix it.
[085 12:07:14.359894] WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation

kitty list-fonts      << This command only list this much font and in this only also it highlight the fonts in blue color which i feel kitty able to detect and rest all it's use Menlo font 

```
agave Nerd Font
    agave Nerd Font r

Andale Mono
    Andale Mono Regular

Anonymice Nerd Font
    Anonymice Nerd Font Regular

CaskaydiaCove Nerd Font
    CaskaydiaCove Nerd Font Book

Consolas NF
    Consolas NF Bold
    Consolas NF Book

Courier New
    Courier New Bold
    Courier New Bold Italic
    Courier New Italic
    Courier New Regular

DroidSansMono Nerd Font
    DroidSansMono Nerd Font Book

DroidSansMono NF
    DroidSansMono NF Book

Fantasque Sans Mono
    Fantasque Sans Mono Bold
    Fantasque Sans Mono Bold Italic
    Fantasque Sans Mono Regular

FantasqueSansMono Nerd Font
    FantasqueSansMono Nerd Font Bold
    FantasqueSansMono Nerd Font Regular

Fira Code
    Fira Code Bold
    Fira Code Bold
    Fira Code Light
    Fira Code Medium
    Fira Code Medium
    Fira Code Regular
    Fira Code Retina
    Fira Code Retina
    Fira Code SemiBold
    Fira Code SemiBold

Fira Code iCursive S12
    Fira Code iCursive S12 Bold
    Fira Code iCursive S12 Regular

FiraCode Nerd Font Mono
    FiraCode Nerd Font Mono Medium
    FiraCode Nerd Font Mono Regular
    FiraCode Nerd Font Mono SemiBold

Lantinghei TC
    Lantinghei TC Demibold
    Lantinghei TC Extralight
    Lantinghei TC Heavy

Menlo
    Menlo Bold
    Menlo Bold Italic
    Menlo Italic
    Menlo Regular

MesloLGS NF
    MesloLGS NF Bold
    MesloLGS NF Bold Italic
    MesloLGS NF Italic
    MesloLGS NF Regular

Monaco
    Monaco Regular

Monoid Nerd Font
    Monoid Nerd Font Bold
    Monoid Nerd Font Italic
    Monoid Nerd Font Regular
    Monoid Nerd Font Retina

mononoki Nerd Font Mono
    mononoki Nerd Font Mono Bold
    mononoki Nerd Font Mono Regular

Office Code Pro D
    Office Code Pro D Medium Italic
    Office Code Pro D Regular
    Office Code Pro D Regular Italic

Operator Mono
    Operator Mono Bold
    Operator Mono Bold Italic
    Operator Mono Book
    Operator Mono Book Italic
    Operator Mono Medium Italic

Operator Mono Lig
    Operator Mono Lig Book
    Operator Mono Lig Book Italic
    Operator Mono Lig Light
    Operator Mono Lig Light Italic
    Operator Mono Lig Medium
    Operator Mono Lig Medium Italic

PCMyungjo
    PCMyungjo Regular

PowerlineSymbols
    PowerlineSymbols Medium

PT Mono
    PT Mono Bold
    PT Mono Regular

SpaceMono Nerd Font
    SpaceMono Nerd Font Bold
    SpaceMono Nerd Font Regular

Spot Mono
    Spot Mono Bold
    Spot Mono Medium
    Spot Mono Regular

UbuntuMono Nerd Font
    UbuntuMono Nerd Font Bold
    UbuntuMono Nerd Font Italic
    UbuntuMono Nerd Font Regular
```

I also like to take help about below error and how to mitigate and fix it.

```
[085 12:29:09.733590] [PARSE ERROR] Unknown OSC code: 1337
[085 12:29:09.733633] [PARSE ERROR] DCS sequence contained ESC without trailing \ ignoring the sequence
[085 12:29:09.733653] [PARSE ERROR] Unknown char after ESC: 0x1b
[085 12:29:09.733768] [PARSE ERROR] Unknown char after ESC: 0x5c
[085 12:29:09.733796] [PARSE ERROR] Unknown OSC code: 1337
[085 12:29:09.733818] [PARSE ERROR] DCS sequence contained ESC without trailing \ ignoring the sequence
[085 12:29:09.733840] [PARSE ERROR] Unknown char after ESC: 0x1b
[085 12:29:09.733872] [PARSE ERROR] Unknown char after ESC: 0x5c
[085 12:29:09.733896] [PARSE ERROR] Unknown OSC code: 1337
[085 12:29:09.733915] [PARSE ERROR] DCS sequence contained ESC without trailing \ ignoring the sequence
[085 12:29:09.733940] [PARSE ERROR] Unknown char after ESC: 0x1b
[085 12:29:09.733974] [PARSE ERROR] Unknown char after ESC: 0x5c
[085 12:29:09.733997] [PARSE ERROR] Unknown OSC code: 1337
[085 12:29:09.734016] [PARSE ERROR] DCS sequence contained ESC without trailing \ ignoring the sequence
[085 12:29:09.734036] [PARSE ERROR] Unknown char after ESC: 0x1b
[085 12:29:09.734064] [PARSE ERROR] Unknown char after ESC: 0x5c
[085 12:29:09.734087] [PARSE ERROR] Unknown OSC code: 1337
[085 12:29:09.734108] [PARSE ERROR] DCS sequence contained ESC without trailing \ ignoring the sequence
[085 12:29:09.734131] [PARSE ERROR] Unknown char after ESC: 0x1b
[085 12:29:09.734159] [PARSE ERROR] Unknown char after ESC: 0x5c
[085 12:29:09.885164] [PARSE ERROR] DCS sequence contained ESC without trailing \ ignoring the sequence

```

**Comment by page-down** [comment]
Don't use patched fonts. You don't need them in kitty. Use the standalone Symbols Nerd Font.
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

> What is this error and how can i fix it.
> ... OpenGL implementation does not have glCopyImageSubData ...

This is literally what it means.
You can't "fix" macOS, and you don't need to workaround.

> I also like to take help about below error ...
> Unknown OSC code: 1337 ...

I believe you have the shell integration for iTerm2 installed and unconditionally enabled. You should not enable it in kitty.
The easiest way to do this is to remove the relevant code in the shell rc file.

**Comment by ciscohack** [comment]
@page-down Thanks for response but if i try other fonts i get very thick font which i don't like. second i tried many other font and kitty complain font not identified.

check this very think font.. i have trying this setting "macos_thicken_font 0.2" not helped and why kitty not recognised other installed font that is big question.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/11479557/160240256-f02adee3-fa51-4ce3-851a-7569a97b8135.png">

I let try the suggestion. yes i have iterm2 2 integration enabled. One more help if you could help me out.
 i want to setup my kitty terminal layout  like this.. how can i make my terminal look like this.

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/11479557/160240433-caabb202-c4fd-40dd-a9d1-d4c633e6fe50.png">

**Comment by ciscohack** [comment]
Check this font not found error  and  

<img width="892" alt="image" src="https://user-images.githubusercontent.com/11479557/160240570-55a0fea1-593c-48e0-a004-9eecb43843d5.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/11479557/160240604-ddb2bcbf-50bd-49b4-90e4-b4cc6530c8ac.png">

and very thick font becoz it fallback to Menlo who's bold size is super thick . 😒😞

**Comment by kovidgoyal** [comment]
The FAQ link tells you what fonts kitty can use. If you dont like a particular face use bold_font in kitty.conf to specify a different face.

**Comment by ciscohack** [comment]
@kovidgoyal  i ran this command kitty list-fonts and it printed below output which i believe kitty supports right and  below is my configuration. This should work ideally right but it's not working. unfortunately none of the font working for me except inbuilt macOS font. So as i now understand Nerd font not work fine with kitty but my favorite font Operator Mono not working and other font also i see very thick typeface

font_family  Operator Mono Book
bold_font  Operator Mono Book

```
agave Nerd Font
    agave Nerd Font r

Andale Mono
    Andale Mono Regular

Anonymice Nerd Font
    Anonymice Nerd Font Regular

CaskaydiaCove Nerd Font
    CaskaydiaCove Nerd Font Book

Consolas NF
    Consolas NF Bold
    Consolas NF Book

Courier New
    Courier New Bold
    Courier New Bold Italic
    Courier New Italic
    Courier New Regular

DroidSansMono Nerd Font
    DroidSansMono Nerd Font Book

DroidSansMono NF
    DroidSansMono NF Book

Fantasque Sans Mono
    Fantasque Sans Mono Bold
    Fantasque Sans Mono Bold Italic
    Fantasque Sans Mono Regular

FantasqueSansMono Nerd Font
    FantasqueSansMono Nerd Font Bold
    FantasqueSansMono Nerd Font Regular

Fira Code
    Fira Code Bold
    Fira Code Bold
    Fira Code Light
    Fira Code Medium
    Fira Code Medium
    Fira Code Regular
    Fira Code Retina
    Fira Code Retina
    Fira Code SemiBold
    Fira Code SemiBold

Fira Code iCursive S12
    Fira Code iCursive S12 Bold
    Fira Code iCursive S12 Regular

FiraCode Nerd Font Mono
    FiraCode Nerd Font Mono Medium
    FiraCode Nerd Font Mono Regular
    FiraCode Nerd Font Mono SemiBold

Lantinghei TC
    Lantinghei TC Demibold
    Lantinghei TC Extralight
    Lantinghei TC Heavy

Menlo
    Menlo Bold
    Menlo Bold Italic
    Menlo Italic
    Menlo Regular

MesloLGS NF
    MesloLGS NF Bold
    MesloLGS NF Bold Italic
    MesloLGS NF Italic
    MesloLGS NF Regular

Monaco
    Monaco Regular

Monoid Nerd Font
    Monoid Nerd Font Bold
    Monoid Nerd Font Italic
    Monoid Nerd Font Regular
    Monoid Nerd Font Retina

mononoki Nerd Font Mono
    mononoki Nerd Font Mono Bold
    mononoki Nerd Font Mono Regular

Office Code Pro D
    Office Code Pro D Medium Italic
    Office Code Pro D Regular
    Office Code Pro D Regular Italic

Operator Mono
    Operator Mono Bold
    Operator Mono Bold Italic
    Operator Mono Book
    Operator Mono Book Italic
    Operator Mono Medium Italic

Operator Mono Lig
    Operator Mono Lig Book
    Operator Mono Lig Book Italic
    Operator Mono Lig Light
    Operator Mono Lig Light Italic
    Operator Mono Lig Medium
    Operator Mono Lig Medium Italic

PCMyungjo
    PCMyungjo Regular

PowerlineSymbols
    PowerlineSymbols Medium

PT Mono
    PT Mono Bold
    PT Mono Regular

SpaceMono Nerd Font
    SpaceMono Nerd Font Bold
    SpaceMono Nerd Font Regular

Spot Mono
    Spot Mono Bold
    Spot Mono Medium
    Spot Mono Regular

UbuntuMono Nerd Font
    UbuntuMono Nerd Font Bold
    UbuntuMono Nerd Font Italic
    UbuntuMono Nerd Font Regular

```

**Comment by page-down** [comment]
> i want to setup my kitty terminal layout like this ...

The panel feature is not supported for macOS. This layout is private and is not suitable for general use.

> ... Nerd font not work fine with kitty ...

No, Symbols Nerd Font works fine.

> ... but my favorite font Operator Mono not working ...

I'm pretty sure this font works fine under macOS.

```conf
font_family Operator Mono Book
bold_font Operator Mono Bold
italic_font Operator Mono Book Italic
bold_italic_font Operator Mono Bold Italic
```

Run the command `kitty --debug-font-fallback` and you can see exactly which font is loaded.

One trick about configuration is to start debugging from scratch by running `kitty --config=NONE -o "some config here" -o "another config"`.

All I can tell you is that everything works fine with kitty on macOS and the configuration is not something special.

I have seen you post a lot of questions already, you need to read the documentation carefully and continue to practice, everything is explained in the documentation.
Or re-evaluate whether the time you put in is worth it. Pick the one that works for you.

**Comment by ciscohack** [comment]
@page-down Thanks once again and agree i posted lots of query as recently moved and in love with this terminal except few things which i am easily able to do on other terminal here i am struggling.. I went through the doc and tried all setting one by one some setting i now understand some still not able to and may think not able to make it work. So feel to take help from experts like you. But i am sorry for this.

This terminal has hell lot of features and i am not even using 1% in video i have seen many coolest productive feature but not able to setup or make it work.😞

I just tried a very basic config change by following the doc. icon of kitty and did exact steps but it's not working 😞 on macOS 12.3

"The panel feature is not supported for macOS. This layout is private and is not suitable for general use."
I really loved the panel and  frankly i moved on kitty by seeing the video and panel 😜 but then i saw how fluid this terminal is 👌🏻.. Thanks for you all.  I hope we will have this panel  setting one day for all.
 
Once again thanks for your time and help.

**Comment by page-down** [comment]
> I really loved the panel

You can use custom tab bar functionality to achieve similar information display, see the github discussions.

> Auto font fallback can be change to some specific font type?

You can use symbol_map to explicitly specify what font to use. It's called auto because you don't have to specify it manually. So ...

**Comment by ciscohack** [comment]
@page-down Thanks!

**Comment by ciscohack** [comment]
@kovidgoyal  Sorry for silly question but can you please help me to know what theme is this in your demo kitty video

![image](https://user-images.githubusercontent.com/11479557/161442472-57588c47-4842-4085-b346-f4a55d7c493b.png)

I thought this is gruvbox theme but it's seems different i need exact same contrast background and colors
I tried gruvbox but it's producing totally different colors and also background black color is little less contrasty as oppose to video one.

![image](https://user-images.githubusercontent.com/11479557/161442587-459afbfa-6911-4e75-a9b7-40338d414000.png)

Please do help me to know about theme and if this is your custom color theme please do share link to use. Thanks

**Comment by kovidgoyal** [comment]
Dimmed Monokai, IIRC

**Comment by ciscohack** [comment]
> 

@kovidgoyal thanks a lot .. i tried Dimmed Monokai but this theme is not what kitty demo video have.. what is IIRC. is there any Kitty IRC channel i don't think we have.

Dimmed Monokai
![image](https://user-images.githubusercontent.com/11479557/161482097-39861711-22bb-4db5-aaf5-463e81ae42b1.png)

**Comment by kovidgoyal** [comment]
IIRC = If I Recal Correctly and as far as I know that was the theme I
used

**Comment by kovidgoyal** [comment]
If you mean you want your output from ls colored, use the LS_COLORS env var via the dircolors program. It has nothing to do with terminal theme.

**Comment by ciscohack** [comment]
@kovidgoyal Ah okay i thought you referring IIRC but not find the theme.. No my friend no referring LS_COLORS that is now days by default handled in ZSH shell. 

The theme you used for your demo is very well balanced and soothing for eyes..  see below screenshot of your video demo.. 

![image](https://user-images.githubusercontent.com/11479557/161483067-ff160ed6-900b-4300-8b89-53a48a651e84.png)

**Comment by kovidgoyal** [comment]
Sorry then I dont remember which one it was

**Comment by ciscohack** [comment]
> Sorry then I dont remember which one it was

okay😞

**Comment by ciscohack** [comment]
Thanks once again @kovidgoyal you are awesome man!

**Comment by ciscohack** [comment]
@kovidgoyal  is this setting "macos_thicken_font -2" reduce the font width to -2 block. i have tried this setting but not seeing any major change and impact.. can please help me to understand is negative  value is bad value and kitty will ignore or we can use negative value

**Comment by kovidgoyal** [comment]
Negative values are the same as zero.

**Comment by ciscohack** [comment]
@kovidgoyal oh! means no effect and useless. Thanks for the update
