### ISSUE TITLE
Cursor does not blink in micro editor

### ISSUE THREAD

**Issue by lsoksane** [kovidgoyal/kitty#4886]
I am using Kitty 0.24.4 and [Micro](https://micro-editor.github.io/) 2.0.10. Cursor blinks in Micro as expected in Mate Terminal but not in Kitty.

**Comment by page-down** [comment]
```shell
echo -en '\e[1 q' && micro
```

```text
screen_set_cursor 1 32
// alt screen, bracketed paste, mouse tracking ...
screen_reset_mode 25 1
// cur pos, sgr , draw ...
screen_reset_mode 12 1
screen_set_mode 25 1
// ...
```

kitty.terminfo
```text
civis=\E[?25l,
cnorm=\E[?12h\E[?25h,
cvvis=\E[?12;25h,
```

https://github.com/zyedidia/tcell/blob/v2.0.8/terminfo/x/xterm_kitty/term.go
```text
ShowCursor:    "\x1b[?12l\x1b[?25h",
HideCursor:    "\x1b[?25l",
```

It seems to me that it explicitly disables cursor blinking.
kitty is working fine. This is an issue with that editor, report it there.
