### ISSUE TITLE
macos_option_as_alt not working

### ISSUE THREAD

**Issue by ilyaradko** [kovidgoyal/kitty#4887]
OS: macOS Monterey 12.0.1
kitty 0.24.4

I am trying to navigate the command line with Alt+arrows, but instead I get output ;3D or ;3C. Option `macos_option_as_alt` has absolutely no effect. I tried options yes, no, both, left, right. No matter what, pressing Alt+Left generates ;3D and Alt+right outputs ;3C

**Comment by Luflosi** [comment]
Try
```
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66
```

**Comment by ilyaradko** [comment]
Thank you, that works.

But then I will need to map all other possible combinations of Alt+key. It would be much better to make Alt key work globally. This is one of the basic functionality of a terminal. Is there a way to fix `macos_option_as_alt`?

**Comment by page-down** [comment]
> ... Option macos_option_as_alt has absolutely no effect. ...

If you want to check whether `macos_option_as_alt` works or not, you can run `kitty --debug-input kitty +kitten show_key -m kitty`.
You can see that the keys are responding properly.
This configuration option works as expected.

If you are running a program that does not support it and expects ESC + Keys, then you need to change the key mapping.

> ... make Alt key work globally ...
> This is one of the basic functionalities of a terminal.

There is currently no configuration option to change the modifier key mapping.

**Comment by kovidgoyal** [comment]
alt+arrow keys are supposed to generate ^[[1;3C etc These are mapped to cursor movemt in terminfo. If your prgram is expecting something else it is buggy and needs to be fixed there.
