### ISSUE TITLE
Ctrl+L (new page ASCII code) cuts off previous lines

### ISSUE THREAD

**Issue by sinistersnare** [kovidgoyal/kitty#4890]
**Describe the bug**
When using `ctrl+l`, I have seen a couple of behaviors

1. Fully wipe the history of the terminal, and put the prompt at the top
2. Put the prompt at the top without wiping history

Kitty does a little bit of both. It wipes some of the most recent lines and puts the prompt at the top.

**To Reproduce**

You can see this yourself by typing something like `echo hi` and then `ctrl+l` to get a new-page. Scroll up and you will see the `echo hi` command gone. 

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux subook 5.14.0-1029-oem #32-Ubuntu SMP Fri Mar 18 13:27:43 UTC 2022 x86_64
Ubuntu 20.04.4 LTS subook /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under:X11
Frozen: True
Paths:
  kitty: ~/.local/kitty.app/bin/kitty
  base dir: ~/.local/kitty.app/lib/kitty
  extensions dir: ~/local/kitty.app/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  ~/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.6
shell              zsh

```

**Additional context**
This reproduces even with `kitty --config NONE`

Thanks for your time!

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal

**Comment by sinistersnare** [comment]
edit: ahh I see the remaping of ctrl+l there. Not my favorite way to do it, but it works I guess.

**Comment by page-down** [comment]
> ... It seems bad that a cross-terminal feature is just plain broken in Kitty.

What you call `ctrl+l` is generally a shell function and not directly done by the terminal.
The behavior is the same regardless of which terminal you use zsh on.

> ... `clear_terminal scroll active ` also places the prompt in the scrollback, which it shouldnt.

This action performs its behavior as described in the documentation, works as expected.
What you need is the following:

```conf
map cmd+k clear_terminal to_cursor active
```

In my opinion, it is the best one after comparing with the same feature in different terminals.
