### ISSUE TITLE
terminals database is inaccessible

### ISSUE THREAD

**Issue by ZyberSE** [kovidgoyal/kitty#4896]
When I try to open for example nano in sudo mode I get this error on macOS 12.3, doing the exact same thing from the built in terminal works fine.

**To Reproduce**
1. Open Kitty on macOS 12.3
2. Run: sudo nano /private/etc/hosts
3. Type in your password

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Darwin ******-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.3 BuildVersion:	21E230
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/*********/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.85
editor             nano
font_family        MesloLGS NF
font_size          12.0

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                **********
```

**Additional context**
I tried with `kitty --config NONE` but got the same issue.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo

**Comment by ZyberSE** [comment]
I've read the documentation but I'm sorry to say I can't understand how to resolve my problem.

My TERMINFO points to: /Applications/kitty.app/Contents/Resources/kitty/terminfo
In that folder there is a 78 folder which contains xterm-kitty

I've tried to updated so it includes /78 but that made no difference.
Please advice what I need todo :)

**Comment by page-down** [comment]
Follow the instructions in the FAQ: `... And either the TERMINFO ... or that file is under ~/.terminfo/x/.`
Copy the terminfo database to `~/.terminfo/x/xterm-kitty`.

```shell
mkdir -p ~/.terminfo/{x,78}
cp $TERMINFO/78/xterm-kitty ~/.terminfo/x/xterm-kitty
ln -snf $HOME/.terminfo/x/xterm-kitty ~/.terminfo/78/xterm-kitty
```

Try `sudo nano` again.

> I've tried to updated so it includes /78 ...

In macOS this should not contain `/78`, just leave it untouched.

**Comment by ZyberSE** [comment]
That @page-down worked perfectly, a big thank you!
