### ISSUE TITLE
Builds but fails: undefined symbol: XineramaQueryScreens

### ISSUE THREAD

**Issue by skosch** [kovidgoyal/kitty#49]
Kitty compiles fine, but running or testing it results in
```
ImportError: /tmp/kitty/kitty/fast_data_types.so: undefined symbol: XineramaQueryScreens
```
... even after following @Robgambrill's suggestion (in #23) to add the required linker flags:
```
ldflags.append('-lXinerama')
ldflags.append('-lXcursor')
ldflags.append('-lXrandr') 
```
All of those packages are installed, and I can't even find any reference to `XineramaQueryScreens` in the kitty source code. I would be grateful for any pointers.

**Comment by kovidgoyal** [comment]
kitty does not use xinerama -- most probably glfw (which kitty uses) is the one that links against it, see for example: https://stackoverflow.com/questions/30662824/build-a-program-with-glfw3-on-linux

Probably glfw on your system is incorrectly built. If you are using a pre-compiled distro package, try building it from source instead.

**Comment by kovidgoyal** [comment]
And you should add -lXinerama to ldpaths not ldflags (the build script has changed since #23)

**Comment by skosch** [comment]
Thanks for replying so quickly! Indeed, all I had to do was recompile glfw3 with `BUILD_SHARED_LIBS` turned on, and I was able to run kitty without problems. Thanks again!
