### ISSUE TITLE
Kitty process/jobs Management

### ISSUE THREAD

**Issue by troubas** [kovidgoyal/kitty#490]
I use [https://www.passwordstore.org/](pass) as my password manager. When copying a password to the clipboard the kitty window refuses to close until either 
 - the password gets cleaned automatically after the timeout period
 - or I copy a new password from a different window.

I assume this has something to do with the way kitty handles its open processes. I personally would prefer the behaviour of urxvt.

urxvt warns about open jobs the first time you try to exit and if you type exit again closes the terminal leaving the open jobs (for example a mupdf window) open. However pass wil not keep a urxvt window open. It is not registered as an open job.

I've never dealt with processes personally so I'm unsure how to approach the subject but if you need me to test something I'd be glad to help.

I find especially annoding that currently the exit command gets honored but the window refuses to close without indication which job I've forgotten. It probably would be easy to check these before exiting.

**Comment by SolitudeSF** [comment]
i assume its handled by `close_on_child_death` option

**Comment by kovidgoyal** [comment]
kitty will not close as long as there are processes using the input/output pipe. Presumably the developer of you password manager doesn't understand how to properly detach processes from their environments. If you are stuck using such broken software set close_on_child_death to yes in kitty.conf. Then kitty will close as soon as the shell dies, regardless of whether there are still processes using the pipe.

And job control is not done by terminals, it is done by the shell running in the terminal. Terminals have no concept of jobs.

**Comment by kovidgoyal** [comment]
Oh and see #229

**Comment by troubas** [comment]
I'm sorry to have neglected the appropriate research before opening an issue.

> Presumably the developer of you password manager doesn't understand how to properly detach processes from their environments. If you are stuck using such broken software set close_on_child_death to yes in kitty.conf

No reason to get offensive. Pass intentionally keeps the input/output pipe open in order to clear the password after a certain timeout period. There may be better ways to achieve that goal but broken software seems a bit harsh.

I will inform the developers of the issue, thanks for clarifying.

**Comment by kovidgoyal** [comment]
There is no reason to keep the pipes open to clear the password. Clearing a password requires access to the clipboard, which has nothing to do with stdout/stderr/stdin. 

When daemonizing a process in unix, if it is well behaved, it needs to detach from its environment, which means redirecting output to /dev/null, changing working directory to /, creating its own session, etc. This is all basic Unix stuff, a simple google for "unix daemon detach" will get all the information.
