### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by dostoievsky** [kovidgoyal/kitty#4900]
**Describe the bug**
Using a feature of [vim-jukit](https://github.com/luk400/vim-jukit), that renders  graphics of libs like mathplot.lib I get the tittle error.
I've opened a on the refered repo (luk400/vim-jukit#2) and the owner pointed me as that as Kitty bug, so I'am reporting here now. 

**To Reproduce**
1. run on kitty terminal:
` kitty +kitten icat --print-window-size`

**Screenshots**
![2022-03-30-134730_769x640_scrot](https://user-images.githubusercontent.com/56840514/160888308-c4e8a8da-2907-401b-a286-c65a2e64c922.png)

**Comment by page-down** [comment]
This has been fixed in master, you can try nightly release.

https://github.com/kovidgoyal/kitty/pull/4818

**Comment by dostoievsky** [comment]
Thank you since its already fixed I'll be closing the issue.
