### ISSUE TITLE
Enable font features for entire families

### ISSUE THREAD

**Issue by mizlan** [kovidgoyal/kitty#4901]
**Is your feature request related to a problem? Please describe.**
I can't seem to enable a font feature for all font faces within a font family.

**Describe the solution you'd like**
A notation that can be used to enable a font feature for all faces. e.g.,

`font_features JetBrainsMono-* +zero`

**Describe alternatives you've considered**
Listing out all faces didn't seem to work either.

**Comment by kovidgoyal** [comment]
Specify the rule multiple times once per face.
