### ISSUE TITLE
copy terminfo for other users

### ISSUE THREAD

**Issue by erazor-de** [kovidgoyal/kitty#4906]
Kitty is a more exotic terminal emulator where the according terminfo is not always available on a system per default. Every user account that is accessed by kitty needs access to the terminfo. This led to the invention of the ssh-kitten which copies the terminfo to the remote users account. My problem is when kitty or its terminfo is installed per user, when I change users with 'su -l' I don't have the terminfo on that users account.

This leads to some questions:

Would a su-kitten make sense which locally copies the terminfo to the destination user analog to what ssh-kitten does remote?

How often does kitties terminfo change? Would it be feasible to install it globally without the fear that it's outdated soon or that different users using different kitty versions have issues? In this case would you think a terminfo-kitten makes sense which copies the terminfo into /usr using su?

**Comment by kovidgoyal** [comment]
The kitten cannot copy terminfo for other users, since it doesnt run as
root. And feel free to install terminfo globally. Infact nowadays, most
linux distributions come with kitty-terminfo packages, just use those.
