### ISSUE TITLE
"macos_option_as_alt left" does not treat left Opt vs. right Opt key differently

### ISSUE THREAD

**Issue by miguno** [kovidgoyal/kitty#4908]
**Describe the bug**

* Expected: When `macos_option_as_alt left`, then only LeftOpt is treated as `Alt`, whereas RightOpt is treated as`Opt` (e.g., for entering Unicode characters).
* Actual: Both LeftOpt and RightOpt are treated as `Alt` key.

I set `macos_option_as_alt left` to get the effect "Use only the left Option key as Alt" as per the [docs](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt).

**To Reproduce**

0. Steps below must be run on a macOS device, doh. In my case that is a M1 MBP 14", running the latest macOS Monterey 12.3 and latest kitty 0.24.4 from homebrew.

1. Set `macos_option_as_alt left` in the config.

2. Define a key bind that uses `alt`, such as `map alt+t new_tab`, with the idea that it applies to the physical LeftOpt key only.

3. Fully restart kitty (no left-over processes) to ensure that the `macos_option_as_alt` config setting is applied properly, because the docs say "Changing this setting by reloading the config is not supported."

4. In kitty, test the behavior by pressing LeftOpt+t vs. RightOpt+t. What actually happens is that both LeftOpt+t and RightOpt+t create a new tab. This is correct for LeftOpt+t. The expected behavior for RightOpt, however, is that RightOpt+t should give a `†` Unicode character.

```sh
# For comparison, this is the output of RightOpt+t when run in iTerm,
# which I configured to treat the Left/Right Opt keys as Opt keys (not as Alt).
$ cat -v
†
```

**Environment details**

A minimal `kitty.conf`:

```
# vim:fileencoding=utf-8:foldmethod=marker
macos_option_as_alt left
map alt+t new_tab
```

produces:

```
kitty 0.24.4 created by Kovid Goyal
Darwin wonder.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.3 BuildVersion:	21E230
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/zsh
Loaded config files:
  /Users/miguno/.config/kitty/kitty.conf

Config options different from defaults:
macos_option_as_alt 2
Added shortcuts:
	opt+t → new_tab

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                de_CH.UTF-8
	SHELL                               /opt/homebrew/bin/zsh
	USER                                miguno
```

PS: Thanks so much for the great work on kitty (code, docs, community work/support)!

**Comment by page-down** [comment]
> ... with the idea that it applies to the physical LeftOpt key only.

No. This will bind actions for both the left and right Option keys.

The option `macos_option_as_alt` specifies the default behavior for programs running in terminal, when no shortcut is set.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt

Whenever a shortcut is set, the shortcut action will be executed first.

It would be nice to be able to explicitly bind shortcuts for all the left and right modifier keys, rather than having to bind them both.

**Comment by miguno** [comment]
I think what you are saying "behavior as intended"?

If so, then I think the docs are misleading and should be rephrased:
> Use the option key as an alt key. With this set to no, kitty will use the macOS native Option+Key = unicode character behavior. This will break any Alt+key keyboard shortcuts in your terminal programs, but you can use the macOS unicode input technique. You can use the values: left, right, or both to use only the left, right or both Option keys as Alt, instead. Changing this setting by reloading the config is not supported.

My expectation was certainly that, with the config set to "left", that the LeftOpt vs. RightOpt keys are treated differently (Alt vs. Opt) throughout kitty.

**Comment by page-down** [comment]
In kitty's source code, the `Option` key is `Alt`, and there is no other special `Option` here.

https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers
> ... The `alt` key is the `option` key on mac keyboards. ...

When mapping actions the mapped keys are on both sides, I would love to be able to bind the right modifiers separately.
So that's why you can no longer enter Unicode characters with `Option`.

Maybe the documentation could be a little clearer, but obviously revising the documentation won't solve your problem.

**Comment by miguno** [comment]
> In kitty's source code, the Option key is Alt, and there is no other special Option here.
> https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers

If, for example, the mapping of physical keys (like RightOpt) to "virtual keys" (like Opt vs. Alt) happens before the protocol, then the lack of separate `LOption` vs. `ROption` (or `LAlt` and `RAlt`) is not a limitation.  I am not familiar with the kitty code base, so I can't tell.

I found `kitty +kitten show_key -m kitty` in the doc link you shared, and here's what I see when I run the command within kitty, and pressing the LeftOpt and RightOpt keys: they are detected as different keys (still with the setting `macos_option_as_alt left`). They are detected as Alt though, not Option, which I suppose is because of "The alt key is the option key on mac keyboards." ([docs](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers)).

```
Press any keys - Ctrl+C or Ctrl+D will terminate
ENTER RELEASE 
CSI 13 ; 1 : 3 u

Alt+LEFT_ALT PRESS 
CSI 57443 ; 3 u

LEFT_ALT RELEASE 
CSI 57443 ; 1 : 3 u

Alt+RIGHT_ALT PRESS 
CSI 57449 ; 3 u

RIGHT_ALT RELEASE 
CSI 57449 ; 1 : 3 u
```

But maybe this is orthogonal to the issue at hand, and goes back to what you said before?

> Maybe the documentation could be a little clearer, but obviously revising the documentation won't solve your problem.

Well, improving the documentation would certainly help other users trying to use the `macos_option_as_alt` setting to accomplish similar setups than mine, and learning that this is not the way to go.

Maybe there is another solution though?  If LEFT_ALT and RIGHT_ALT can be distinguished, maybe escape codes could be used to turn RIGHT_ALT back into a macOS Option key?  (Though I guess there is probably a technical limitation that prevents such shenanigans...)

> The following are my usage scenarios.
>
>    LeftOption + T -> new_tab
>    RightOption + Arrow keys -> send alt+arrow_keys to programs

👍

**Comment by miguno** [comment]
In case this helps, here is a screenshot of the iTerm settings, where you can configure different behavior for LeftOpt vs. RightOpt.

<img width="347" alt="iterm-settings" src="https://user-images.githubusercontent.com/294849/161249846-7751dc4b-0770-47eb-9455-eb5dde302224.png">

**Comment by miguno** [comment]
I found an older discussion from 2018, where @kovidgoyal [says](https://github.com/kovidgoyal/kitty/issues/1022#issuecomment-435919458) "Simply set `macos_option_as_alt` to no in your kitty.conf".

Back then, this didn't help the users participating in the thread for similar reasons as discussed here:

> Still it, this cuts me from all ALT chords. Ideal would be to use one ALT as Escape code prefix and second as a AltGr.
https://github.com/kovidgoyal/kitty/issues/1022#issuecomment-435925807

The partial workaround then was to manually create mappings for any Unicode characters (that you would normally enter with `Option+<key>`) as `alt+<key>`, with the hope that the user would only need a few of these Unicode chars / would only need a few `alt` shortcuts for kitty because the Option (unicode) and Alt keyspaces overlap in this scenario (you can't configure both Option+t and Alt+t, for example).

- https://github.com/kovidgoyal/kitty/issues/1022#issuecomment-436809049
- https://github.com/kovidgoyal/kitty/issues/1022#issuecomment-449104063

**Comment by kovidgoyal** [comment]
I dont follow what you are saying.

macos_option_as_alt left 

will mean that if you press a left option key + something else combo
that normally results in a unicode character from macos, then it will
not work and instead the alt+key combination will be passed to the
terminal program (assuming you have not declared any shortcuts that
intefere in kitty.conf). You will have to use hte right option key +
something else to get the unicode character., The left option key will 
act as alt in all circumstances.

Option and alt are the same thing. The only difference is if
macos_option_as_alt is not set, pressing option+some keys will result in
unicode chars.

**Comment by miguno** [comment]
>  (assuming you have not declared any shortcuts that intefere in kitty.conf)

This is the key info that is missing in the docs for `macos_option_as_alt`. Because, for for me as a new user, the current docs text suggests the user can do sth like the following:

```
macos_option_as_alt left

map alt+t new_tab   # create new tab with LeftOpt+t
map opt+t close_tab # close tab with RightOpt+t
```

This is not possible in practice, however, as you and @page-down said.

Perhaps the docs can be improved and reworded to sth like the following:

> Use the Option key as an Alt key. With this set to no, kitty will use the macOS native Option+Key = unicode character behavior. This will break any Alt+key keyboard shortcuts in your terminal programs, but you can use the macOS unicode input technique. You can use the values: left, right, or both to use only the left, right or both Option keys as Alt, instead. Note that kitty itself always treats Option the same as Alt. This means you cannot use this setting to configure different kitty shortcuts for Option+Key vs. Alt+Key on macOS. Also, any kitty shortcuts using Option/Alt+Key will take precedence, so that any such key presses will not be passed to terminal programs running inside kitty. Changing this setting by reloading the config is not supported.

(FWIW it's ok if the functionality itself cannot be implemented.)

**Comment by kovidgoyal** [comment]
You are welcome to send a PR to improve the docs.

**Comment by miguno** [comment]
PR up at https://github.com/kovidgoyal/kitty/pull/4912.

Thanks again for the quick responses, everyone.
