### ISSUE TITLE
Slow "experienced speed" while displaying image 

### ISSUE THREAD

**Issue by nkh** [kovidgoyal/kitty#4909]
Thanks for kitty, just installed it to replace Konsole as it handles, for me, displaying with w3mimgdisplay better (no banding).

I use https://github.com/stefanhaustein/TerminalImageViewer to display images using ASCII,

with image from https://github.com/nkh/ftl/tree/main/screenshots, the time reported by /bin/time is the same but the experienced speed is at the disadvantage of Kitty, which "feels" ten times slower. 

It could be due to how Konsole buffers output, or maybe and now I am just guessing based on what I read in the docs, that the characters used by tiv are not cached in kitty.

**Comment by nkh** [comment]
The preview is part of another program and kitty is sluggish when using tiv even compared to Konsole (which is far from a speed daemon).

**Comment by kovidgoyal** [comment]
So open a bug report with tiv asking it to use the kitty graphics
protocol instead of whatever hackery it is doing.

**Comment by nkh** [comment]
tiv output ___ASCII___ text and in this case kitty is sluggish displaying ASCII text

**Comment by kovidgoyal** [comment]
Why on earth would you want to view ASCII text when you can view the
__actual image__? And I find the claim that kitty is slower than konsole
on *anything* pretty hard to believe. Especially one based on
"perception". Indeed as of a few weeks ago konsole has even added
partial support for kitty's graphics protocol, so you really should get
tiv updated.

If you can come up with some minimal reproducer where kitty is slower
than konsole based on an actual measurement, feel free to update this
ticket with the details. Until then, I'm afraid I am not interested.

**Comment by nkh** [comment]
Because not everybody on earth wants to make kitty specific software but everybody on earth expects ASCII to be displayed at a normal speed.

After further testing ... it's not just tiv, even vim also displays at a "perceived" slower speed than Konsole (probably because , as I wrote in my first comment, Konsole buffers output), one can see each line being drawn rather than the text appearing instantly. I believe vim is a pretty common application and you could try for yourself. I'm happy to make a video showing the speed difference if it helps.

if you've heard before the claim that Konsole output is "perceived" to be faster than this is one more reason to look into it.

A possibility about the vim sluggishness, is that it's the handling of "clear screen", one can see the screen go black and each line drawn one after the other, fast but not fast enough to not see it. I think a video would make very obvious and I can make one later today if it is of help.

I have another terminal application, which certainly __DOES__ feel faster in Kitty and there's nothing specific to kitty in it. Furthermore using w3mimgdisplay in Kitty doesn't suffer from a banding problem found in Konsole, probably because the whole screen is first cleared than re-displayed in Kitty, but you'd know better.

**Comment by nkh** [comment]
I use tmux and I ran the test within and without tmux, same result.

**Comment by kovidgoyal** [comment]
I use vim all day long, indeed I wrote kitty because all other terminal
emulators at the time were too slow for vim (in fact konsole is by far
one of the slowest of terminal emulators, which a bit of googling for
terminal benchmarks will show you). So sorry, but if you are finding vim
too slow in kitty, then it will be because of something specific to your
system.

Again, I would like a *reproducible* *benchmark* otherwise, this is just
system specific handwaving.

**Comment by kovidgoyal** [comment]
I would check your GPU drivers/ OpenGL setup. It may be you are running with software rendering.

**Comment by nkh** [comment]
I will check that and if that fails I'll install a fresh OS, Kitty, Konsole and vim and compare.

**Comment by nkh** [comment]
Setup says it's running Nvidia driver

> ubuntu-drivers devices
vendor   : NVIDIA Corporation
model    : GM204M [GeForce GTX 970M]

> nvidia-detector
nvidia-driver-510

Is there a way to get information from Kitty that would be helpful for finding the cause?

**Comment by kovidgoyal** [comment]
--debug-rendering will output some information about opengl version
