### ISSUE TITLE
`pass_selection_to_program_with_cwd`

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#491]
a bit verbose, but would be useful, for example, to `ls` in the directory and quickly open files without typing out the filename, especially with when they named like `baO34kX4AwzASL.jpg bduE1fd4AERrCX.jpg bduE2dsUAEW8Kh.jpg`, so autocomplete is not very useful.

**Comment by kovidgoyal** [comment]
The terminal cannot in general know what the working directory of a program running in it is (technically it can ask the OS, but this may or may not work, depending on many things). If you are going to be runing ls wont it run in the same directory as whatever program generated the filenames in the first place? In which case you can simply use the hints kitten (press ctrl+shift+p and then f) and choose the filename it will get inserted into the terminal at the shell prompt.

**Comment by SolitudeSF** [comment]
trying to implement this with the help of shell. is there a way to invoke a kitten from shell?

**Comment by kovidgoyal** [comment]
Use the remote control API. https://github.com/kovidgoyal/kitty/blob/master/remote-control.asciidoc

**Comment by SolitudeSF** [comment]
Thank you.

as an offtopic since i dont know if im misusing the feature: `kitty @ get-text` returns nothing with any combination of parameters.

**Comment by kovidgoyal** [comment]
Works for me. remeber that you have to enable remote control in kitty.conf first and restart kitty after that.

**Comment by SolitudeSF** [comment]
other commands work as expected. im not on master, maybe thats the reason.

**Comment by kovidgoyal** [comment]
WHat that command does is output the current contents of your screen, so it might look like noth has happened, try redirecting its output to a file and open the file in an editor instead.

**Comment by SolitudeSF** [comment]
i thought i tested it, but that was exactly the case, thank you.
