### ISSUE TITLE
Allow overriding theme kitten's upstream themes repo

### ISSUE THREAD

**Issue by ismay** [kovidgoyal/kitty#4911]
**Is your feature request related to a problem? Please describe.**

The quality of the themes in the kitty-themes repo is somewhat variable to my eyes (mainly contrast issues). This has led me to create variants of the themes I like best. I know that I can override themes by having them locally, but I like the idea of maintaining my kitty themes in a separate repo. It would allow me to separate the management of my dotfiles from the management of my themes, which I personally like.

**Describe the solution you'd like**
A way to override the repo that the themes kitten pulls the themes from https://github.com/kovidgoyal/kitty/blob/master/kittens/themes/collection.py#L339. I'm fine with this allowing only github repos, and only repos that follow the conventions outlined by the kitty-themes repo. I'm also fine with my custom repo integration breaking if kitty decides to change the convention.

**Describe alternatives you've considered**
Local theme overrides. The kitty theme kitten still pulls in a ton of themes that I'd rather not have to deal with at all. Plus, I think the suggested solution could also lighten the maintenance burden a little, since the themes kitten is no longer bottlenecked by just what's in the kitty-themes repo. Users could set up their own, specialized kitty themes repo that caters to specific needs.

**Comment by kovidgoyal** [comment]
I dont see much point. If you want to maintain your custom themes in a
repo, just do that, and checkout the repo into your kitty config folder.
I dont see what using a separate repo is going to get you. Note that you
can tell the kitten not to download themes from the repo if that bothers
you by using --cache-age=-1

**Comment by ismay** [comment]
> I dont see much point. If you want to maintain your custom themes in a
repo, just do that, and checkout the repo into your kitty config folder.
I dont see what using a separate repo is going to get you.

Yeah fair enough.

> Note that you can tell the kitten not to download themes from the repo if that bothers you by using --cache-age=-1

Ah nice, that helps. In that case I can manage without the custom repo. Thanks!
