### ISSUE TITLE
light/dark theme based on system?

### ISSUE THREAD

**Issue by hanoii** [kovidgoyal/kitty#4915]
**Is your feature request related to a problem? Please describe.**
I normally use a dark setting systemwide, but also sometimes I am outdoors and prefer a light theme for most and I would like a light one on kitty.

**Describe the solution you'd like**
I'd like a setting to set a default theme, a light theme and and or a dark theme. You could have a setting to enable this but I assume it's redundant, if you only select a default theme, there would be no change, if there's a light/dark theme configured, it will favour that over the default depending on the system setting.

**Comment by kovidgoyal** [comment]
Not something I care enough to implement. It's trivially easy to
implement this yourself by using the themes kitten. Simply have your
system run a script when the theme changes and in that script call the
themes kitten to change the theme in all kitty instances.

**Comment by hanoii** [comment]
How didn't I think of that!

Looking around it seems https://github.com/bouk/dark-mode-notify for osx is a kickstart I'll be trying out, if anyone stumbles upon something different/better let me know.

**Comment by Joxtacy** [comment]
@hanoii Did you manage to figure out a solution? 
How often/when do you run your script to check the `$DARKMODE` variable?

The slightly annoying thing with this approach is all the separate moving parts to it.

**Comment by hanoii** [comment]
@Joxtacy yes, it was sorted out by what explained in the other post. I don't have to `poll` anything, that small program linked https://github.com/kovidgoyal/kitty/issues/4915#issuecomment-1088016786 runs the script whenever the setting changes. It's just one tiny think on top of the thousands I manage :)

**Comment by rkshthrmsh** [comment]
Hi @hanoii, I was able to build and test dark-mode-notify with Kitty from command line, but for some reason I'm unable to get the [Background Agent](https://github.com/bouk/dark-mode-notify#background-agent) `launchctl load -w` to automatically listen, launch, and execute the command on system mode change. Any help is appreciated.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>ke.bou.dark-mode-notify</string>
    <key>KeepAlive</key>
    <true/>
    <key>ProgramArguments</key>
    <array>
       <string>/usr/local/bin/dark-mode-notify</string>
       <string>/bin/zsh</string>
       <string>-c</string>
       <string>/Users/rr/ws/sandbox/system_based_theme.zsh</string>
    </array>
</dict>
</plist>
```

**Comment by ZelvStudio** [comment]
For people using Gnome, I made a script that does it: https://github.com/ZelvStudio/kitty-gnome-lightdark-mode-switcher
Probably easy to adapt to KDE too. It feels very hacky but works for me so far.

**Comment by jannis-baum** [comment]
I case anyone is interested: I made a script that lets you generate your own color-schemes (for Kitty, Vim, and other programs) that allow you to reload the colors entirely dynamically, i.e. the entire scrollback is adjusted and you never have to worry about reloading anything but kitty!

The repo also includes instructions for how to make Kitty automatically change the theme in sync with the macOS system dark/light mode.

See [Chameleon](https://github.com/jannis-baum/Chameleon).

**Comment by h-jia** [comment]
[Toggle Theme.zip](https://github.com/kovidgoyal/kitty/files/13237860/Toggle.Theme.zip)
I make an alfred workflow to do this.

**Comment by iclanzan** [comment]
Curiously Kitty is already tracking changes to the system theme but all it does is print the string "system color theme changed: dark/light".

**Comment by kovidgoyal** [comment]
Nothing curious about it, the tracking is used to change the window decoration colors on GNOME Wayland. 

And see https://github.com/kovidgoyal/kitty-fosshack2024/issues/3

**Comment by klmcwhirter** [comment]
@kovidgoyal what makes it curious is that you stopped there. But you already explained that - like me you probably do not use the OS feature that often. You were managing scope to just the GNOME (not sure what else) system windows decoration changes.

Regardless, the place where you are logging - boss.py::on_system_color_scheme_change - seems to be a good place to make that change. Is there a reason to not do that? Note I have just started looking at the kitty code.

And, FYI, to prepare for potential implementation (sometime in the future if it is requested) of the common high contrast accessibility feature, other editors separate the config items.

For example VS Code has these config items for dark/light scheme following system:
window.autoDetectColorScheme
workbench.preferredLightColorTheme
workbench.preferredHighContrastColorTheme
workbench.preferredHighContrastLightColorTheme
workbench.preferredDarkColorTheme

So it might be prudent to keep them separated.

But your proposal (from kovidgoyal/kitty-fosshack2024/issues/3) would be "the simplest thing that can work":

light_and_dark_mode_themes theme name 1, theme name 2

Anyway, this was just an FYI.

I'll continue thinking about this and will move discussion to kovidgoyal/kitty-fosshack2024/issues/3.

Thanks.

**Comment by kovidgoyal** [comment]
Dont see why? If someone want to use a high contrast theme for light/dark they could just set that as the light or dark theme. I know of no OS that auto switches between 4 different color themes, do you?

**Comment by klmcwhirter** [comment]
Yes, this is supported on Fedora 41 . High Contrast is an accessibility option at the OS level.

**Comment by kovidgoyal** [comment]
It isnt exposed over DBUS so even if the OS supports it, kitty would not
be able to use it.

**Comment by klmcwhirter** [comment]
Correct. And that is why VS Code exposes separate settings like they do.

Like I said, it was just a "what if" type of suggestion.

Starting with your idea to simply configure a "dark" and "light" theme option is a good place to start.

In a pinch one could just use the themes kitten manually to handle the high contrast use case for now.

**Comment by kovidgoyal** [comment]
I still dont follow. What would a separate setting achieve? kitty cannot
know if the OS is in high contrast mode or not. So how would it ever use
such a setting.

**Comment by klmcwhirter** [comment]
Yes it can. But I suspect there may be some other mechanism required to detect it.

To support it VS Code supplies separate settings.

This info is only useful to try to future proof the design of the settings now to just support dark / light switching. If they are separate settings now, using whatever convention you come up with, it might be easier to expand the concept later to include high contrast, etc. support later.

That is all I was trying to say.

But it is not that important.

**Comment by kovidgoyal** [comment]
On Sun, Nov 03, 2024 at 07:12:06PM -0800, klmcwhirter wrote:
>
> Yes it can. But I suspect there may be some other mechanism required to detect it.

There is no DE independent mechanism that I know of. Indeed as far as I
know there is no DE independent high contrast setting available in
Linux. The best you can get is a "high contrast" icon theme.

>
> To support it VS Code supplies separate settings.

This will almost certainly be legacy code inherited to support Windows'
high contrast themes.

>
> This info is only useful to try to future proof the design of the settings now to just support dark / light switching. If they are separate settings now, using whatever convention you come up with, it might be easier to expand the concept later to include high contrast, etc. support later.

I doubt there will ever be a need for them. High contrast is a holdover
from Linux DEs trying to copy windows which used to have these. But
regardless, if it ever became a thing one could simply add two more
optional entries to the list of themes in the kitty setting, specifying
different themes for high contrast mode.

**Comment by klmcwhirter** [comment]
As I said, this discussion is unimportant. I was just trying to get you to think a little more about settings design. I am hoping to use an approach that honors the Open-Closed Principle to achieve what I need.

But not in this issue.

**Comment by klmcwhirter** [comment]
FYI

I have an implementation of a kitty "watcher" that is doing the job of monitoring the dark/light color scheme system changes for me. I am hesitant to share the code because it is an unorthodox approach; but it works for me.

Assumptions:
- this is a big one - I side-stepped the suggestion for a mutex because I only ever have a single instance of kitty open at a time. I have been working this way for years. But if I were using a tiling window manager and open a news instance (instead of just a tab / window), this design would not work reliably.

- No new configuration needed; and cooperates with the themes kitten. It works by assuming a sub-dir named `~/.config/kitty/themes` where there exists 1 and only 1 file for each of `themes/dark-*.conf` and `themes/light-*.conf`.  As system changes occur the appropriate file is copied to `~/.config/kitty/current-theme.conf` and `load_config_file` is called.

That way the themes to use can be managed on the filesystem (perhaps via themes --dump-theme outputting to the appropriate named file) and I can use the themes kitten to occasionally select a higher contrast theme.

Let me know if there is any interest in the code.
