### ISSUE TITLE
right click menu for terminal hyperlinks

### ISSUE THREAD

**Issue by gknittl** [kovidgoyal/kitty#4917]
First of all thanks so much for your work in creating Kitty. You are expanding the boundaries of terminal applications in very creative and productive ways.

**Is your feature request related to a problem? Please describe.**
Terminal hyperlinks are a wonderful concept and I'm glad Kitty supports them. However, Gnome Terminal supports right clicking on terminal hyperlinks to show a menu. I haven't been able to locate this function in Kitty. For example left clicking on a .txt file will open it in gedit, but I might want to open it in "less" or just copy the file name.

**Describe the solution you'd like**
The Gnome Terminal implementation would be a start, but I would also like to be able to customize the context menu based on the hyperlink.

**Describe alternatives you've considered**
I considered searching the Kitty docs further in case there is already a way to do this but I think the right click menu should be available out of the box like it is on Gnome Terminal

**Additional context**
Sample Gnome Terminal menu after right click on terminal hyperlink
![Screenshot from 2022-04-04 03-13-48](https://user-images.githubusercontent.com/102946889/161494552-be819143-e516-4fb2-8bd3-7bf80264469d.png)

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/open_actions/

**Comment by gknittl** [comment]
Thanks for the quick response, but open actions appear to apply only to the left click. I don't see how to define actions for the right click, nor do I see how to put up an option menu....

**Comment by kovidgoyal** [comment]
A menu is ameans of selecting an action. You can pre-select the actions
using open-actions. If you really want a menu then have the action be
running a program that presents a menu.

**Comment by gknittl** [comment]
My first thought is that it is reasonable orthogonal design to me to treat a menu as just another action, although it would be nice to have a sample to work from... Still, that doesn't address supporting the left mouse click so that I can left click a text file to directly edit and right click to present a menu of options like "less", copy filename etc And perhaps yet other actions for other mouse clicks.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

**Comment by kovidgoyal** [comment]
And incidentally if I wanted to perform a not preconfigured action on a hyperlink in kitty I would do it via the keyboard not a menu, which you can do with the hints kitten: https://sw.kovidgoyal.net/kitty/kittens/hints/
