### ISSUE TITLE
Window doesn't stay maximized with hidden window decorations on GNOME/Wayland

### ISSUE THREAD

**Issue by jamielinux** [kovidgoyal/kitty#4918]
Thank you for this great terminal.

I've come across a bug that seems consistently reproducible. The workaround is to set `hide_window_decorations no`.

**Describe the bug**
The kitty window doesn't stay maximized after you launch another application (eg, kitty or a web browser window etc). The kitty window goes back to its original size.

When this happens, the kitty window seems to be in a weird state where the window manager still thinks kitty is maximized (ie, if you press Super+Right Click on the kitty window to get the menu, there is no `Maximize` option anymore).

**To Reproduce**
1. Launch Fedora 36 Beta (or Fedora 35)
2. `dnf install kitty`
3. Create `~/.config/kitty/kitty.conf` with `hide_window_decorations yes`
4. Launch kitty
5. Maximize kitty (eg, Super+Right Click on the kitty window and select Maximize)
6. Launch any application (eg, firefox) on the same desktop
7. Kitty window is no longer maximized

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux localhost-live 5.17.0-0.rc7.116.fc36.x86_64 #1 SMP PREEMPT Mon Mar 7 23:10:19 UTC 2022 x86_64
S
Kernel 5.17.0-0.rc7.116.fc36.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/liveuser/.config/kitty/kitty.conf

Config options different from defaults:
hide_window_decorations 1

Important environment variables seen by the kitty process:
        PATH                                /home/liveuser/.local/bin:/home/liveuser/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
        LANG                                en_US.UTF-8
        EDITOR                              /usr/bin/nano
        SHELL                               /bin/bash
        DISPLAY                             :0
        WAYLAND_DISPLAY                     wayland-0
        USER                                liveuser
        XDG_MENU_PREFIX                     gnome-
        XDG_SESSION_DESKTOP                 gnome
        XDG_SESSION_TYPE                    wayland
        XDG_CURRENT_DESKTOP                 GNOME
        XDG_SESSION_CLASS                   user
        XDG_RUNTIME_DIR                     /run/user/1000
        XDG_DATA_DIRS                       /home/liveuser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

**Additional context**
I see last year there was a similar issue (but not quite the same) that has been fixed: https://github.com/kovidgoyal/kitty/issues/3507

In the case I described, switching desktops has no impact. This bug only happens when opening a new window on the same desktop.

**Comment by kovidgoyal** [comment]
dup of #4797
