### ISSUE TITLE
Triple click should select wrapped lines

### ISSUE THREAD

**Issue by RedBeard0531** [kovidgoyal/kitty#492]
This is common in several other applications, and very helpful in a terminal. One specific use case I often have is selecting a giant JSON blob that is in on a single "line" that may span many screenfulls. This is much harder if I have to scroll and find the bounds when highlighting.

**Comment by kovidgoyal** [comment]
Already exists and you can even do it using just the keyboard using the hints kitten. See the readme.

**Comment by RedBeard0531** [comment]
Actually, I think there is at least one bug here. Triple-click works fine for short lines that fit on one screen line, but doesn't for lines that wrap. Visually it looks like nothing was selected, but it the selection copy buffer gets updated with the **screen** line rather than the full line. I checked and the kitten seems to copy the full line, unless it goes past the bottom of the screen, due to scrolling up, then it only uses the visible portion.

Can you reopen this issue or would you rather I file a new one?

**Comment by RedBeard0531** [comment]
Thanks for quickly fixing addressing this. It improves the situation where the text wraps. Unfortunately there are still issues if the line is only partially on screen (this sounds odd, but it is somewhat common for our program to output fairly large json blobs on a single line in the middle of stdout, and it is useful for me to get them into the X11 selection buffer quickly). Here is a simple repro. It is easiest to see if you have a window running `watch -n 0.1 'xclip  -o| wc -c'` so you can see the selection change in real time.

1. run `for i in $(seq 10000); do echo -n x; done` to generate a giant line that is > 1 screen full. (use a higher number if your screen is massive)
2. triple-click the visible portion and note that the selection count doesn't equal 10,000
3. scroll up so the bottom of the line isn't visible and repeat. Still not 10,000, and the selection flashes off implying that the transition from double to triple-click de-selected text. (That implies there is a similar issue with double click when a single *word* doesn't fit on screen, but that seems like less of a real issue)
4. scroll up so the top of the line is visible and repeat. Behavior is the same as when neither is visible.
5. Select the whole line by scrolling while clicking. This is the proof that giant selections are supported and can work correctly, although they are painful to do.

Thanks again
(I know you've only heard complaints from me, but I do really like kitty!)

**Comment by kovidgoyal** [comment]
Triple click will only select text visible on the screen. This is by design as I dont like selection extending invisibly. If you want to select text that is not visible on the screen, you either:

1) Double click followed by a mouse press and then drag to scroll and select
2) Right click to extend the current selection
