### ISSUE TITLE
Diff Kitten not respecting opacity value

### ISSUE THREAD

**Issue by jonas-w** [kovidgoyal/kitty#4920]
**Describe the bug**
When there is a background opacity set (lower than 1) in kitty, the diff kitten doesn't respect it and i can't set alpha values to the color theme in `diff.conf`.

**To Reproduce**
1. Set kitty opacity to lower than 1
2. Open diff kitten with files to compare
4. The add/removed margin and text isn't transparent

**Screenshots**
![image](https://user-images.githubusercontent.com/32615971/161636171-bda050a2-7781-4944-8222-e4584b0f8cc5.png)

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux samsung-pro360 5.17.1-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 28 Mar 2022 21:56:46 +0000 x86_64
EndeavourOS Linux 5.17.1-zen1-1-zen (/dev/tty)

DISTRIB_ID=EndeavourOS
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME=rolling
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/citrus/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.8
enable_audio_bell    False
font_family          MesloLGS NF
font_size            15.0
visual_bell_duration 0.4
Colors:
	visual_bell_color    #110000   

Important environment variables seen by the kitty process:
	PATH                                /sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                citrus
	XCURSOR_SIZE                        24
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Additional context**

| With everything set to black it works, but that defeats the purpose i guess

![image](https://user-images.githubusercontent.com/32615971/161636114-4bd87581-32ef-43f4-be93-1f4aee468755.png)

No diff.conf set for the first (white) screenshot

Every background color is set to black in the second (dark) screenshot

Also when selecting text, the selected text doesn't have transparent background

**Comment by kovidgoyal** [comment]
opacity can only make *one* color transparent, the background.
