### ISSUE TITLE
hyperlinked_grep : FileNotFoundError: [Errno 2] No such file or directory: 'rg'  in Linux (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by moisestohias** [kovidgoyal/kitty#4923]
**Describe the bug**
Running hyperlinked_grep in Linux system (Ubuntu 20.04 LTS) generates: **FileNotFoundError: [Errno 2] No such file or directory: 'rg'**  

**To Reproduce**
kitty +kitten hyperlinked_grep --smart-case

**Screenshots**
"""
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "kitty_main.py", line 185, in <module>
  File "kitty_main.py", line 176, in main
  File "kitty_main.py", line 129, in namespaced
  File "kitty_main.py", line 112, in run_kitten
  File "kittens/runner.py", line 120, in run_kitten
  File "runpy.py", line 213, in run_module
  File "runpy.py", line 87, in _run_code
  File "kittens/hyperlinked_grep/main.py", line 67, in <module>
  File "kittens/hyperlinked_grep/main.py", line 26, in main
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'rg'
"""

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux Dell 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64
Ubuntu 20.04.4 LTS Dell /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/moises/.local/kitty.app/bin/kitty
  base dir: /home/moises/.local/kitty.app/lib/kitty
  extensions dir: /home/moises/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /home/moises/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    y
background_opacity      0.7
cursor_text_color       None
font_family             Fira Code Light
font_size               14.0
hide_window_decorations 1

Important environment variables seen by the kitty process:
    PATH                                /home/moises/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    LANG                                en_US.UTF-8
    SHELL                               /usr/bin/fish
    DISPLAY                             :0
    USER                                moises
    LC_TIME                             ar_DZ.UTF-8
    XDG_SESSION_TYPE                    x11
    LC_MONETARY                         ar_DZ.UTF-8
    XDG_SESSION_CLASS                   user
    LC_ADDRESS                          ar_DZ.UTF-8
    XDG_RUNTIME_DIR                     /run/user/1000
    XDG_MENU_PREFIX                     gnome-
    LC_TELEPHONE                        ar_DZ.UTF-8
    XDG_CURRENT_DESKTOP                 ubuntu:GNOME
    XDG_SESSION_DESKTOP                 ubuntu
    LC_NAME                             ar_DZ.UTF-8
    LC_MEASUREMENT                      ar_DZ.UTF-8
    LC_IDENTIFICATION                   ar_DZ.UTF-8
    XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
    XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
    LC_NUMERIC                          ar_DZ.UTF-8
    LC_PAPER                            ar_DZ.UTF-8
```

**Comment by page-down** [comment]
You need to make sure that `rg` is in the PATH.

https://sw.kovidgoyal.net/kitty/kittens/hyperlinked_grep/

https://github.com/BurntSushi/ripgrep

**Comment by moisestohias** [comment]
@page-down thanks, 
ripgrep was missing

for reference, if you people encounter an error while installing **ripgrep** via package manager in debian based  system: install it this way instead
apt-get download ripgrep
sudo dpkg --force-overwrite -i ripgrep*.deb
