### ISSUE TITLE
macOS full screen mode: use sides of notch

### ISSUE THREAD

**Issue by amanvm** [kovidgoyal/kitty#4924]
It would be nice to have a config option to be able to use sides of notch in fullscreen mode. This would allow using more space on the screen with a category of apps where it is acceptable that notch hides a portion of line (user can can always scroll up if they want to see what's there). Moreover, on a 16 inch screen, the notch starts at 100+ characters from the left edge of screen, and a lot of text out there is typeset to not use beyond 80 characters per line anyway. Advantage: This will give an extra line or two of code/text on the screen in full screen mode.

**Comment by kovidgoyal** [comment]
I'm afraid this is of no interest to me. Patches welcome.
