### ISSUE TITLE
Mouse button semantics change depending on whether pixel resolution is enabled

### ISSUE THREAD

**Issue by dankamongmen** [kovidgoyal/kitty#4925]
**Describe the bug**
Consider a mouse button press, followed by a mouse movement while holding down that button, followed by release of the button.

If pixel resolution is enabled for mouse events, the events corresponding to movement will indicate no button pressed. Without pixel resolution, the events corresponding to movement will indicate the original button, as well as the new coordinates.

This former behavior seems incorrect to me; the mouse movement events ought still indicate that the button is held IMHO.

**To Reproduce**
1. Enable pixel-resolution mouse events via `\e[>1s\e[?1002;1016h`
2. Press a mouse button and continue to hold it down.
3. Move the mouse while continuing to hold down the button.

**Screenshots**
https://github.com/dankamongmen/notcurses/issues/2628 contains my notes on the problem as investigated.

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux grimes 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64
Arch Linux 5.16.16-arch1-1 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/dank/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.7
enable_audio_bell     False
font_family           Hack
font_size             12.0
initial_window_height (1410, 'px')
initial_window_width  (132, 'cells')
remember_window_size  False
scrollback_lines      20000
symbol_map:
        U+29d1 - U+29d2 → Unifont
        U+29d4 - U+29d5 → Unifont
Colors:
        background            #080808   
        foreground            #ffffff   

Important environment variables seen by the kitty process:
        PATH                                /opt/local/bin:/opt/local/sbin:/home/dank/.cargo/bin:/home/dank/.local/bin:/usr/local/s>
        LANG                                en_US.UTF-8
        EDITOR                              vim
        SHELL                               /bin/bash
        DISPLAY                             :0.0
        USER                                dank
        XDG_CONFIG_DIRS                     /etc/xdg
        XDG_MENU_PREFIX                     xfce-
        XDG_SEAT                            seat0
        XDG_SESSION_TYPE                    tty
        XDG_CURRENT_DESKTOP                 XFCE
        XDG_SESSION_CLASS                   user
        XDG_VTNR                            4
```

**Additional context**
I'm just getting back to Notcurses work after two months doing other stuff, so my brain might be a bit rusty--apologies if I've done anything stupid or overlooked something here!

**Comment by kovidgoyal** [comment]
I agree it should match the behavior of the non-pixel mode. However, I
am currently travelling so will investigate in more detail when I
return.

**Comment by dankamongmen** [comment]
no problem at all; i hope it's a fun trip!

**Comment by dankamongmen** [comment]
i confirm that, even with pixel mode enabled, we now get the button press when holding it down while moving the mouse. thanks!
