### ISSUE TITLE
Kitty doesn't render with iPad Sidecar screen

### ISSUE THREAD

**Issue by blissdev** [kovidgoyal/kitty#4930]
**Describe the bug**
When using an iPad as an external screen using [Sidecar](https://support.apple.com/en-us/HT210380) Kitty doesn't seem to render content as expected. When instantiated on the external Sidecar screen, the screen appears as below. If the Kitty window is instantiated on a non-Sidecar screen it works fine, but when moved to the Sidecar screen it no longer updates. Dragging it back to a non-Sidecar screen will allow it to update again.

**Screenshots**

![CleanShot 2022-04-06 at 12 57 43@2x](https://user-images.githubusercontent.com/3456/162080212-ce5d68e8-7596-402b-9aed-1fc9c685ee9d.png)

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Darwin Jordans-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.3.1 BuildVersion:	21E258
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/fish
Loaded config files:
  /Users/bliss/.config/kitty/kitty.conf

Config options different from defaults:
cursor_text_color       None
enable_audio_bell       False
font_family             JetBrainsMono Nerd Font Mono Bold
font_size               18.0
window_padding_width    FloatEdges(left=15.0, top=15.0, right=15.0, bottom=15.0)
Colors:
	active_tab_background   #f8f8f2   
	active_tab_foreground   #282a36   
	background              #282a36   
	color0                  #21222c   
	color1                  #ff5555   
	color10                 #69ff94   
	color11                 #ffffa5   
	color12                 #d6acff   
	color13                 #ff92df   
	color14                 #a4ffff   
	color2                  #50fa7b   
	color3                  #f1fa8c   
	color4                  #bd93f9   
	color5                  #ff79c6   
	color6                  #8be9fd   
	color7                  #f8f8f2   
	color8                  #6272a4   
	color9                  #ff6e6e   
	cursor                  #f8f8f2   
	foreground              #f8f8f2   
	inactive_tab_background #6272a4   
	inactive_tab_foreground #282a36   
	mark1_background        #ff5555   
	mark1_foreground        #282a36   
	selection_background    #44475a   
	selection_foreground    #ffffff   
	url_color               #8be9fd   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /usr/local/bin/fish
	DISPLAY                             /private/tmp/com.apple.launchd.bXvdKwgjLV/org.xquartz:0
	USER                                bliss
```

**Additional context**
> Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

I have the same issue with NONE config.

**Comment by page-down** [comment]
This is obviously because Apple doesn't care about OpenGL and can't render on Sidecar.
Unless support for rendering with Metal is introduced, I don't think it will work.

Apple has deprecated OpenGL, and it's only a matter of time before it no longer works anymore in the future. Sigh.

**Comment by kovidgoyal** [comment]
Someday i will move kitty to vulkan at which point one can use the
vulkan-on-metal shim to get it to run on metal. Until then, this is a
wontfix.
