### ISSUE TITLE
Strange bash_complition behavior

### ISSUE THREAD

**Issue by MiloLug** [kovidgoyal/kitty#4934]
**The bug**
I have installed the `bash-completion` package. Of course, it has added itself to `/etc/bash/bashrc.d/`. And bash definitely sources the completion since I can use it in TTY or xterm. But i doesn't work in Kitty until I source it with hands. 

**To Reproduce**
1. On Void Linux install `bash-completion` package
2. Try to use it (with git, for example)
3. It doesn't work

**Environment details**
```
kitty 0.24.4
```

**Comment by kovidgoyal** [comment]
Works for me on Arch. I'm afraid I am not going to install a whole distro just
to test this. Steps I tried:

1) kitty --config=NONE -o shell=bash
2) At the prompt type git st and press Tab
3) Shows completions with "stage stash status"

It could be that void patches bash to load distro bash packages and that
patching is incompatible with shell integration in kitty, so you might
need to source the completion explicitly, try adding it to ~/.bashrc

[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion
