### ISSUE TITLE
Command output collapse/expand

### ISSUE THREAD

**Issue by larskotthoff** [kovidgoyal/kitty#4936]
**Is your feature request related to a problem? Please describe.**

Output from some commands can be very long, making it hard to see what was happening before running that command.

**Describe the solution you'd like**

Allow to collapse and expand or fold (in vim terminology) output from commands, e.g. only the last line of the output a particular command produced would be shown instead of hundreds of lines, with the ability to expand. This could work similar to code folding that e.g. vim supports.

**Comment by kovidgoyal** [comment]
I'm afraid this is not of interest to me. You can already use keyboard
shortcuts to jump to previous commands if you need to see them or their
output. https://sw.kovidgoyal.net/kitty/shell-integration 

And you can open the scrollback in an editor where you can
define folds based on the prompt pattern already.
https://sw.kovidgoyal.net/kitty/overview/ (see the section on
scrollback).
