### ISSUE TITLE
Desktop integration files not working on vanilla GNOME on Arch

### ISSUE THREAD

**Issue by gitaarik** [kovidgoyal/kitty#4938]
Hi there,

I just installed Arch for the first time, installed GNOME, and kitty. To get the kitty icon to appear in the applications in GNOME, I followed these instructions in the docs:

https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux

However, it didn't seem to work for me. After some research I found out that if I make the values of the `Exec` and `TryExec` fields in `kitty.desktop` absolute paths, then the icon would show up and work.

https://github.com/kovidgoyal/kitty/blob/master/setup.py#L973-L974=

I don't know why it needs to be absolute paths on this installation. Before this I used Ubuntu, and it worked there without absolute paths. But on a fresh Arch install with vanilla GNOME it doesn't seem to work. The `kitty` binary is on my `$PATH`, and I can execute it from another terminal. But GNOME apparently can't find it.

So, don't know why it doesn't work without absolute paths, but in any case, wouldn't it be better to make the paths absolute anyway? Similar to [the instructions in the docs](https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux) for updating the path to the kitty icon, you can also make the paths to the executables absolute:

```bash
sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
```

That could make sure that some edge cases like mine will work.

**Comment by kovidgoyal** [comment]
That will be because your *system-wide* PATH does not include
~/.local/bin. Use a directory that is present in your system wide PATH
for the kitty symlink. Or you can use absolute paths in the desktop
file. Changing the instructions to use absolute paths is fine, feel free
to send a PR for it.

**Comment by gitaarik** [comment]
Cool. Just a question, why would a user's home folder be on the system wide PATH? Doesn't that make no sense?

**Comment by kovidgoyal** [comment]
On Sun, Apr 10, 2022 at 01:14:00PM -0700, Rik wrote:
> Cool. Just a question, why would a user's home folder be on the system wide PATH? Doesn't that make no sense?

Because sensible system admins/distro packagers include system-wide
shell rc files that add $HOME/.local/bin to the PATH early in the shell's
startup cycle.
