### ISSUE TITLE
Kitty terminal is dull compare to native macOS terminal

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#4941]
Hello Experts,

today will doing some work and test i have noticed kitty terminal rendering is little dull and text is also sometime not very crisp and high quality as appose to native macOS terminal. for this test  i used same theme on both terminal and ran side by side screenshot is below you can see the clear different. Both running Dracula theme and kitty terminal is way dull in rendering ..

is kitty compromising the terminal and text quality over performance. I have seen on reddit also someone observed same behaviour against Alacrity .. even iterm2 terminal is also dull but if you see the native terminal is very crisp and high quality in rendering ..which is good for eyes. Hope this can be further improved in future releases .. i have also observed bold font rendering for many typeface looks very weird in kitty ..little blur and fuzzy

![image](https://user-images.githubusercontent.com/11479557/162517876-134729af-3113-478d-af99-cc5f923c6007.png)

**Comment by kovidgoyal** [comment]
dup of #4686

**Comment by ciscohack** [comment]
@kovidgoyal so you think text rendering is also expected. I saw the dup post so colorspace config seem solved the issue for many and it's now part of kitty code. but test rendering is if you see on native terminal is more eye pleasing and crisp.

**Comment by numbcoder** [comment]
hi @kovidgoyal, P3 is the default colorspace for Mac's build in display, I had to build kitty locally with the one line patch every time when kitty released a new version. Perhaps there are many kitty fans like me who are being annoyed by this. I think it will be better to add an option like `macos_colorspace` for users who can custom colorspace to adapt to their displays.
Thanks!

**Comment by ciscohack** [comment]
> hi @kovidgoyal, P3 is the default colorspace for Mac's build in display, I had to build kitty locally with the one line patch every time when kitty released a new version. Perhaps there are many kitty fans like me who are being annoyed by this. I think it will be better to add an option like `macos_colorspace` for users who can custom colorspace to adapt to their displays. Thanks!

@numbcoder Agree with your suggestion.. seems many experts patch kitty locally. I also feel font render quality can also be improved near future

**Comment by ciscohack** [comment]
Hello Experts,

@kovidgoyal just check this same theme on kitty and alacritty and the color difference is not minor but huge. on kitty, the terminal background looks more on the black side on kitty and very dull too.

I have also noticed a minor performance issue on the latest kitty... I use chromaterm syntax highlighter and sometimes kitty lag while reading a big log file... you might ignore this but I tested the same on alacritty and no such issue on alacritty, it's the fastest... so thought to share with experts. But the color shift is huge that needs some work.

![image](https://user-images.githubusercontent.com/11479557/163436804-0c5c9594-e2db-444b-bc37-ac7155c049c0.png)

**Comment by kovidgoyal** [comment]
As I said before, colors in kitty have already been determined to be correct. You endlessly repeating the same thing is not going to change that.

**Comment by numbcoder** [comment]
> As I said before, colors in kitty have already been determined to be correct. You endlessly repeating the same thing is not going to change that.

As I said before, P3 is the default colorspace for Mac's build-in display, but kitty set it to sRGB, I don't think it's correct.
