### ISSUE TITLE
`--start-as=fullscreen` initially renders as a regular window for a fraction of a second

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4949]
**Describe the bug**
When launching kitty with the `--start-as=fullscreen` option, kitty initially renders as a normal window for a split-second and then finally goes to fullscreen.

My expectation is that the `--start-as=fullscreen` option shall apply even on the first frame kitty renders.

**To Reproduce**
1. `kitty -c NONE --start-as=fullscreen`

**Screenshots**
Here are the relevant frames from a video I recorded.
![kitty_089](https://user-images.githubusercontent.com/40219235/162629952-e09413a0-9f9f-4242-a159-448674193da8.png)
![kitty_090](https://user-images.githubusercontent.com/40219235/162629955-de648bc9-bf9d-4d27-8966-a8875118cce2.png)
![kitty_091](https://user-images.githubusercontent.com/40219235/162629956-6bf8f77d-15fe-4149-bd74-37d792a1d8fb.png)
![kitty_092](https://user-images.githubusercontent.com/40219235/162629958-59cac606-ba95-4cf2-b66a-c74f6ddf374e.png)
![kitty_093](https://user-images.githubusercontent.com/40219235/162629960-810fa1c6-c01c-49c0-8577-c823192c77e6.png)
![kitty_094](https://user-images.githubusercontent.com/40219235/162629962-86ffba1f-6f25-4594-81fd-21d42fa2217a.png)

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux byteevo 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64
Ubuntu 20.04.4 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
Running a nightly from a couple of days ago.  However, the issue has been there since the day I started using kitty (0.19.3, I believe).

I know I'm being nit-picky.  Though its been bugging for a long.  If this is hard to fix, feel free to close it.

**Comment by kovidgoyal** [comment]
Not something I care about. Patches welcome.
