### ISSUE TITLE
The Prompt is discolored in Debian 11

### ISSUE THREAD

**Issue by prateekamana** [kovidgoyal/kitty#4950]
**Describe the bug**
The prompt has no colors, it is working with xterm and gnome terminal emulators smh 
Kitty:
![image](https://user-images.githubusercontent.com/41776584/162631574-5247a7da-a87b-4b08-84a6-afd95538948f.png)
Gnome Term:
![image](https://user-images.githubusercontent.com/41776584/162631629-edf70c4b-6d31-43b7-b062-a5ab3bd31c14.png)

**To Reproduce**
1. Install kitty on Debian 11 with curl as instructed on the kitty website

**Additional context**
Same output with kitty --config NONE, except  the background is black.

**Comment by kovidgoyal** [comment]
This will be an incompatibility between whatever prompt you are using and shell_integration. Either fix the prompt or turn off shell integration in kitty.conf.

**Comment by prateekamana** [comment]
@kovidgoyal How can I see what prompt I am using? I am using BASH so will I have to change the PS1 in .bashrc? If I turn off shell integration wouldn't I lose out on history of commands used previously?

**Comment by kovidgoyal** [comment]
No shell integration enables the features described in:
https://sw.kovidgoyal.net/kitty/shell-integration 

As for the prompt you will need to check PROMPT_COMMAND and PS1

**Comment by page-down** [comment]
/etc/skel/.bashrc from Debian 11 / Ubuntu LTS.

```bash
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes
```

It's just this really stupid default configuration, perhaps because of compromises made in terms of backward compatibility or performance.
I don't expect any improvements in these Linux distributions for this.

**Comment by kovidgoyal** [comment]
On Sun, Apr 10, 2022 at 11:05:53PM -0700, page-down wrote:
> It's just this really stupid default configuration, perhaps because of compromises made in terms of backward compatibility or performance.
> I don't expect any improvements in these Linux distributions for this.

Yeah the entire idea of Linux distributions modifying upstream software
is so deeply flawed. They are horrible at it. 

@OP: Just stick 

color_prompt=yes

at the top of your bashrc. The chances that you will ever run a terminal
emulator that does not support 256 colors is remote bordering on
ridiculous.

**Comment by prateekamana** [comment]
That fixed it, thank you so much @page-down and kovid ❤️
