### ISSUE TITLE
Sixel Support

### ISSUE THREAD

**Issue by anoduck** [kovidgoyal/kitty#4952]
**Is your feature request related to a problem? Please describe.**
I personally have come across terminal applications that require sixel support, and would like to use those apps with my prefered terminal emulator. Furthermore, the availability of terminal emulators for OpenBSD that support sixel is a grand total of two, neither of which come close to kitty's robustness. 

**Describe the solution you'd like**
Add support for the sixel graphical library and graphics format. Which should available, and should be easy to accomplish since kitty already supports images in the terminal.

**Describe alternatives you've considered**
Considered writing a plugin that would accept graphics in sixel format and translate them to kitty's graphical format

**Additional context**
Checkout lsix, it is a pretty cool way to view a folder of images in your terminal. https://github.com/hackerb9/lsix

**Comment by kovidgoyal** [comment]
dup of #2511

**Comment by anoduck** [comment]
Sorry about that. I did search for sixel in issues. Thanks for the awesome job creating kitty.

**Comment by kovidgoyal** [comment]
No worries and you are most welcome.
