### ISSUE TITLE
`kitty @ close-tab --self` is broken in 0.25

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4954]
**Describe the bug**
`kitty @ close-tab --self` no longer works.

**To Reproduce**
1. `kitty -c NONE -o allow_remote_control=yes`
2. `CTRL+SHIFT+T` a couple of times to open new tabs.
3. `kitty @ close-tab --self` within one of the tabs.

**Observed Behavior**
The command does not close the current tab.

**Expected Behavior**
The current tab shall close.

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux byteevo 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64
Ubuntu 20.04.4 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control y

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
I am running with `kitty --config NONE`.

**Comment by page-down** [comment]
I'm wondering if we can use `--self` to specify that the target window is the active window or the window the command is running on, without the two `others` and `unactive` (why not use the word `inactive`, which is already used a lot in kitty?)

The reason I didn't implement it was because I was considering whether it should be implemented in `match: Which tab to close` instead of adding a new parameter.

Currently `target-group` is somewhat unintuitive and needs to be considered in combination with other parameters.

**Comment by kovidgoyal** [comment]
On Mon, Apr 11, 2022 at 05:29:51PM -0700, page-down wrote:
> I'm wondering if we can use `--self` to specify that the target window is the active window or the window the command is running on, without the two `others` and `unactive` (why not use the word `inactive`, which is already used a lot in kitty?)
> 
> The reason I didn't implement it was because I was considering whether it should be implemented in `match: Which tab to close` instead of adding a new parameter.

You cant since natch is used for many different actions and the
appropriate groups for match are not the same across all actions.

**Comment by kovidgoyal** [comment]
There can be only one active window and one active tab. so using
inactive means all the rest will be closed.

And inverting a match will not allow you to close all but the current
active tab without first getting its id separately.

**Comment by salmankhilji** [comment]
Please consider apply the following patch:

[kitty.zip](https://github.com/kovidgoyal/kitty/files/8472329/kitty.zip)

(Its idiotic that GitHub does not allow me to attach a `.patch` file.  I have to zip it.)

The current documentation for the newly added `--target-group` option has minor grammatical errors where a couple of `.` (periods) are missing, merging two distinct sentences.  I didn't just add the missing periods, but also colored the options.  Not sure whether you like the coloring.  Here is how it looks now:

![Screenshot from 2022-04-12 04-15-58](https://user-images.githubusercontent.com/40219235/162948722-5e107068-3f54-40bf-a193-6ffe6194eb2f.png)

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/5876ce084596ffc43550a090e151e9cfba46ed05
