### ISSUE TITLE
How to open new tab/window with the current tab/window's Conda Environment?

### ISSUE THREAD

**Issue by AniAggarwal** [kovidgoyal/kitty#4959]
When I create a new tab or window, I would like it to have the same conda virtual environment activated.
Is there a way to do this currently? I tried using the launch command didn't have any luck.

**Comment by page-down** [comment]
This state is stored in the shell (or subshell), and the best way to do this is to write a function to open a new window via kitty remote control and then activate the virtual environment. Bind a shortcut to this function in the shell.

If you try to store this information to the kitty window when activating or de-activating the virtual environment, you may get some out-of-sync situations.

Currently kitty does not have deep integration and requires scripting or writing kitten.

**Comment by kovidgoyal** [comment]
Use remote control: https://sw.kovidgoyal.net/kitty/remote-control/ 

 kitty @ launch --env=VENV=$VENV /path/to/script/that/setsup/venv 

Add whatever env vars you need.

**Comment by kovidgoyal** [comment]
Actually atleast for the python stdlib venvs (dont know how conda ones work) sinly doing

kitty @ launch --copy-env --cwd=current

should be enough

**Comment by page-down** [comment]
I decided not to worry about being out of sync.
The following is the way to do it without remote control and works with ssh kitten.
A window with cwd will be created when no virtual environment is activated.

~/.config/fish/conf.d/kitten-new-cwd.fish
```fish
status is-interactive && set -q KITTY_WINDOW_ID || return 0
if set -q KITTY_SHELL_INTEGRATION
    set KITTY_SHELL_INTEGRATION "$KITTY_SHELL_INTEGRATION no-cwd"
end
function __kitten_new_cwd_setup --on-event fish_prompt
    functions -e __kitten_new_cwd_setup
    function __update_cwd_osc --on-variable PWD --on-variable CONDA_PREFIX -d "Report PWD changes to kitty"
        not status is-command-substitution || return
        set -l fragment
        if set -q CONDA_PREFIX
            set fragment "#KITTEN_ENV_CONDA_PREFIX="(string escape --style=url $CONDA_PREFIX)
        end
        printf '\e]7;file://%s%s%s\a' $hostname (string escape --style=url $PWD) $fragment
    end
    __update_cwd_osc

    if set -q KITTEN_ENV_CONDA_PREFIX                                                                                                                           
        conda activate "$KITTEN_ENV_CONDA_PREFIX"                                                                                                               
        __update_cwd_osc                                                                                                                                        
        set -e KITTEN_ENV_CONDA_PREFIX                                                                                                                          
    end                                                                                                                                                         
end    
```

~/.config/kitty/kitten_new_cwd.py
```python
from urllib.parse import urlparse, parse_qs

from kitty.launch import launch, parse_launch_args
from kitty.window import CwdRequest
from kitty.utils import path_from_osc7_url

from kittens.tui.handler import result_handler
from kittens.ssh.main import set_cwd_in_cmdline


def main(args):
    pass


def set_or_remove_env_in_cmdline(name, value, argv):
    for i, arg in enumerate(tuple(argv)):
        if arg.startswith(f'--kitten=env={name}'):
            if value:
                argv[i] = f'--kitten=env={name}={value}'
            else:
                del argv[i]
            return
        elif i > 0 and argv[i-1] == '--kitten' and (arg.startswith(f'env={name}') or arg.startswith(f'env {name}')):
            if value:
                argv[i] = f'env={name}={value}'
            else:
                del argv[i-1]
                del argv[i]
            return
    idx = argv.index('ssh')
    argv.insert(idx + 1, f'--kitten=env={name}={value}')


def get_env_from_window_osc7_url(window, env_name):
    if window.at_prompt and window.screen.last_reported_cwd:
        url = window.screen.last_reported_cwd
        if url.startswith('file://'):
            fragment = urlparse(url).fragment
            if fragment:
                env_value = parse_qs(fragment).get(env_name)
                if env_value:
                    return env_value.pop() or None
    return None


@result_handler(no_ui=True)
def handle_result(args, answer, target_window_id, boss):
    w = boss.active_window
    if w is not None and args:
        env_name = args.pop()
        env_value = get_env_from_window_osc7_url(w, env_name)
        ssh_kitten_cmdline = w.ssh_kitten_cmdline()
        if ssh_kitten_cmdline:
            set_or_remove_env_in_cmdline(env_name, env_value, ssh_kitten_cmdline)
            if w.at_prompt and w.screen.last_reported_cwd:
                set_cwd_in_cmdline(path_from_osc7_url(w.screen.last_reported_cwd), ssh_kitten_cmdline)
            opts, args_ = parse_launch_args(args)
            launch(boss, opts, ssh_kitten_cmdline)
            return
        else:
            tab = boss.active_tab
            if tab is not None and env_value:
                tab.new_window(cwd_from=CwdRequest(w), env={env_name: env_value})
                return

    boss.new_window_with_cwd()
```

~/.config/kitty/kitty.conf
```conf
shell fish
shell_integration no-cwd
map f1 kitten kitten_new_cwd.py KITTEN_ENV_CONDA_PREFIX
```

@kovidgoyal 
Do you think it would be worthwhile to allow in ssh kitten to explicitly set certain last reported environment variables that will be copied when a window or tab is opened with cwd?
It can even be used for `launch` (with explicit reporting of some).

Also I see that iTerm2 has OSC 1337 to set user variables.
`OSC 1337 ; SetUserVar=[Ps1]=[Ps2] ST`
Might come in handy for use elsewhere, especially when writing kitten, not just with "cwd".

**Comment by kovidgoyal** [comment]
@page-down: See https://github.com/kovidgoyal/kitty/commit/c19e69855affe684f72b5e42510543420df9d529

**Comment by AniAggarwal** [comment]
Thanks so much for the prompt response and the code!
Unfortunately, I wasn't able to get either solution to work.

# Using remote control
> kitty @ launch --copy-env --cwd=$(pwd)

This does not seem to work. 
Output from window 1:
```
$ which python
/home/ani/miniconda3/envs/yolo/bin/python
$ kitty @ launch --copy-env --cwd=$(pwd)
4
```
Output from window 2 (the new one opened by `kitty @ launch --copy-env --cwd=$(pwd)`):
```
$ which python
/home/ani/miniconda3/bin/python
```
Here's a screenshot to hopefully make it a bit more clear:
![Screenshot from 2022-04-14 10-30-10](https://user-images.githubusercontent.com/52252926/163442257-4f0c08c0-cfa6-438f-98b8-a51efadab424.png)

# Using @page-down's solution 
I use Bash and know very little Bash or Fish scripting.
That said, I followed your steps and switched to Fish just for testing your code.
![Screenshot from 2022-04-14 10-37-02](https://user-images.githubusercontent.com/52252926/163443478-23a4fad0-390e-48a7-92bc-0bd52ebdce75.png)

Additionally, using Bash and just renaming `kitten-new-cwd.fish` to `kitten-new-cwd.sh` doesn't work. I know there is a difference between Fish and Bash syntax but I know far too little to understand how to convert them properly. 

I think to make this work, all that would be needed is to store the current conda env before creating the new window and then activate it after creating the window.
For instance, we could just store `CONDA_DEFAULT_ENV` which is just `yolo` in this case, and then run `conda activate $CONDA_DEFAULT_ENV`.
But I don't really know what I'm talking about. Let me know if I did any of my above steps incorrectly..

**Comment by kovidgoyal** [comment]
--copy-env wont work since most shells dont export the env vars to their own process only to child processes. So you will need to set the required env vars one by one. As I said I dont use conda but most likely you just need to copy PATH

kitty @ launch --env=PATH=$PATH --cwd=$PWD

**Comment by AniAggarwal** [comment]
Unfortunately copying the whole path didn't work. 

I have no issues waiting, thanks again for making this whole project free!

**Comment by kovidgoyal** [comment]
Didn't work as in? Is it because your shell rc files re-arrange the
PATH? Whats the output of which python in the original and cloned
shells?

**Comment by AniAggarwal** [comment]
Output of `which python` is same as before.
![Screenshot from 2022-04-15 09-54-31](https://user-images.githubusercontent.com/52252926/163598631-6aa9403e-5ccc-47c0-946b-ef4e7e811408.png)


This is what Conda adds to the `.bashrc` file:
```bash
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ani/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ani/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ani/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ani/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

For reference, this is the contents of `/home/ani/miniconda3/etc/profile.d/conda.sh`:
```bash
export CONDA_EXE='/home/ani/miniconda3/bin/conda'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='/home/ani/miniconda3/bin/python'

# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause

__add_sys_prefix_to_path() {
    # In dev-mode CONDA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -n "${_CE_CONDA}" ] && [ -n "${WINDIR+x}" ]; then
        SYSP=$(\dirname "${CONDA_EXE}")
    else
        SYSP=$(\dirname "${CONDA_EXE}")
        SYSP=$(\dirname "${SYSP}")
    fi

    if [ -n "${WINDIR+x}" ]; then
        PATH="${SYSP}/bin:${PATH}"
        PATH="${SYSP}/Scripts:${PATH}"
        PATH="${SYSP}/Library/bin:${PATH}"
        PATH="${SYSP}/Library/usr/bin:${PATH}"
        PATH="${SYSP}/Library/mingw-w64/bin:${PATH}"
        PATH="${SYSP}:${PATH}"
    else
        PATH="${SYSP}/bin:${PATH}"
    fi
    \export PATH
}

__conda_exe() (
    __add_sys_prefix_to_path
    "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
)

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix "$@")" || \return
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix reactivate)" || \return
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    \local cmd="${1-__missing__}"
    case "$cmd" in
        activate|deactivate)
            __conda_activate "$@"
            ;;
        install|update|upgrade|remove|uninstall)
            __conda_exe "$@" || \return
            __conda_reactivate
            ;;
        *)
            __conda_exe "$@"
            ;;
    esac
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    # In dev-mode CONDA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -n "${_CE_CONDA:+x}" ] && [ -n "${WINDIR+x}" ]; then
        PATH="$(\dirname "$CONDA_EXE")/condabin${PATH:+":${PATH}"}"
    else
        PATH="$(\dirname "$(\dirname "$CONDA_EXE")")/condabin${PATH:+":${PATH}"}"
    fi
    \export PATH

    # We're not allowing PS1 to be unbound. It must at least be set.
    # However, we're not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi
```

**Comment by kovidgoyal** [comment]
Yup conda screws with the PATH in bashrc. So it's not going to work. This is unlike the python stdlib venv which does not modify bashrc at all. I suppose one workaround could be to add PATH to a list of special variables when cloning and have the shell integration script set it after the rc files have been sourced.

**Comment by AniAggarwal** [comment]
Let me know if I can help provide any other info to make the clone-in-kitty support conda

**Comment by kovidgoyal** [comment]
clone-in-kitty now has explicit support for both python stdlib and conda venvs. The prompt decoration and deactivate both work.

**Comment by page-down** [comment]
I nuked those poorly written `activate` shell scripts. Wondering how to work together instead of not being able to use clone-in-kitty by default (in my environment).
Personally, I don't like to keep adding stuff to the integration scripts, it gives me headaches. :(
(Because of the stupid implementation from other projects.)

Since we can't use `env -i clone-in-kitty`, is it possible to have an option that doesn't inherit any environment variables? Then it would work with `clone-in-kitty --dont-inherit-env --env=whatever`.
Something like `kitty -o clear_all_shortcuts=yes ...`.

Also when messing with ... shell, ENV, PATH, virtual environments enabled by default, I started to worry about unauthorized code execution.

It would be nice if, similar to `allow_remote_control`, you could configure `\eP@kitty-clone|` in kitty.conf to completely disable environment variables and maybe only allow those in the whitelist specified in the configuration file.

**Comment by kovidgoyal** [comment]
On Sat, Apr 16, 2022 at 05:18:55AM -0700, page-down wrote:
> I nuked those poorly written `activate` shell scripts. Wondering how to work together instead of not being able to use clone-in-kitty by default (in my environment).
> Personally, I don't like to keep adding stuff to the integration scripts, it gives me headaches. :(
> (Because of the stupid implementation from other projects.)
> 
> Since we can't use `env -i clone-in-kitty`, is it possible to have an option that doesn't inherit any environment variables? Then it would work with `clone-in-kitty --dont-inherit-env --env=whatever`.
> Something like `kitty -o clear_all_shortcuts=yes ...`.

Not sure I follow. The only reason to use clone-in-kitty at all is that
it copies env vars automatically, otherwise you can just use 

launch --cwd=last_reported 

If you want to use clone-in-kitty but filter the env vars, you can do so
by adding some code in your shells rc files to check if
KITTY_IS_CLONE_LAUNCH is set and if it is filter out the env vars you
dont want copied.

> 
> Also when messing with ... shell, ENV, PATH, virtual environments enabled by default, I started to worry about unauthorized code execution.


I dont see how. I am guessing your concern is some program that can
trigger the clone facility. But if it can do that, it can just as well
directly execute whatever it wants to. The important thing to note about
clone is that it run on the same machine, so while cross user execution
is possible, this is already possible by simply allowing the facility at
all. One can set arbitrary env vars and arbitrary env vars can control
what files the shell executes. And if you disallow the env vars then
what's the point. 

> 
> It would be nice if, similar to `allow_remote_control`, you could configure ***@***.***|` in kitty.conf to completely disable environment variables and maybe only allow those in the whitelist specified in the configuration file.

Seems overly pessimistic. Security concerns can be alleviated by simply 
asking the user for permission before launching, just as is done for
example when a program tries to write to the system clipboard via OSC 52

**Comment by kovidgoyal** [comment]
And thinking about the security issue some more, we can alleviate the risk of passing arbitrary env vars by not setting them in the child environment directly but instead   having the shell integration script set the env vars after sourcing the rc files.

**Comment by AniAggarwal** [comment]
Sorry if this is obvious, but how can I use the clone in kitty? 
I updated kitty via `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin`. Do I need to build from source to get the update?

Once I have the latest update, how should create a new tab/window to have it clone the conda env?

**Comment by kovidgoyal** [comment]
You need to install the nightly. And then run

clone-in-kitty 

in your shell.

**Comment by kovidgoyal** [comment]
And tomorrow, since the nightly wont have the final things I implemented today.

**Comment by AniAggarwal** [comment]
Ok sounds good, I'll check back in tomorrow. Thanks!

**Comment by AniAggarwal** [comment]
Using the latest nightly build worked!
It currently asks if I would like to allow the program to clone.

I assume once this nightly build is migrated to a stable one there will be full integration allowing me to use keymaps (e.g. `ctrl+shift+enter`) to open a new window with a prompt?

**Comment by kovidgoyal** [comment]
On Sat, Apr 16, 2022 at 08:54:50PM -0700, AniAggarwal wrote:
> Using the latest nightly build worked!
> It currently asks if I would like to allow the program to clone.

If you dont want to be asked use the allow_cloning option in kitty.conf

> 
> I assume once this nightly build is migrated to a stable one there will be full integration allowing me to use keymaps (e.g. `ctrl+shift+enter`) to open a new window with a prompt?

No, you have to run clone-in-kitty.

**Comment by page-down** [comment]
> ... The only reason to use clone-in-kitty at all is ...

OK, when a feature disables the most convenient capability, it will be meaningless.

> ... asking the user for permission before launching ...
> ... alleviate the risk of passing arbitrary env vars by ... 
> ... having the shell integration script set the env vars after sourcing the rc files.

This makes sense. Thanks, I think that's good enough.

I found that running `kitty` in an environment with python stdlib venv activated, the shell in the kitty window does not have venv activated (neither PATH nor prompt has venv, but apparently inherits VIRTUAL_ENV), and running clone-in-kitty will activate it in a new window.

Do you have any good ideas for this?

**Comment by kovidgoyal** [comment]
On Sun, Apr 17, 2022 at 03:00:18AM -0700, page-down wrote:
> > ... The only reason to use clone-in-kitty at all is ...
> 
> OK, when a feature disables the most convenient capability, it will be meaningless.
> 
> > ... asking the user for permission before launching ...
> > ... alleviate the risk of passing arbitrary env vars by ... 
> > ... having the shell integration script set the env vars after sourcing the rc files.
> 
> This makes sense. Thanks, I think that's good enough.
> 
> I found that running `kitty` in an environment with python stdlib venv activated, the shell in the kitty window does not have venv activated (neither PATH nor prompt has venv, but apparently inherits VIRTUAL_ENV), and running clone-in-kitty will activate it in a new window.
> 
> Do you have any good ideas for this?

See my latest commit.

**Comment by AniAggarwal** [comment]
> No, you have to run clone-in-kitty.

Is there no way to map that at all?
I was trying to play around with `launch` and mappings but I can't seem to find a way to map `kitty_mod+enter` to clone-in-kitty.
Is that something you plan to add in the future?

**Comment by AniAggarwal** [comment]
Actually I realized I can map the `send_text` command to send clone-in-kitty but I haven't yet figured out how to get the control code that is the same as pressing the enter key.

**Comment by kovidgoyal** [comment]
\r

**Comment by AniAggarwal** [comment]
Thanks!

Reference for anyone else who is trying to do something similar to me.
In my `kitty.conf`, mapping `kitty_mod+enter` to creating a new window with the same Conda env and cwd
```
allow_cloning yes
map kitty_mod+enter      send_text normal clone-in-kitty\r
```
If you want to be able to create new windows while in other applications this solution won't work (but maybe there is a workaround I'm not aware of).
