### ISSUE TITLE
no_op is broken

### ISSUE THREAD

**Issue by cfal** [kovidgoyal/kitty#496]
Reassigning no_op to keys with defaults is broken after https://github.com/kovidgoyal/kitty/commit/bd0382830ae9847cd3c81553270c924f9cf7103e

Tested using "map ctrl+shift+equal no_op" on a macOS.

**Comment by kovidgoyal** [comment]
Use 

```
map kitty_mod no_op
```

instead. I suppose I could add some code to resolve and remove no_ops in a separate pass at the end for backwards compatibility.

**Comment by cfal** [comment]
Thanks!
