### ISSUE TITLE
tmux compatible split window with current dir

### ISSUE THREAD

**Issue by ttys3** [kovidgoyal/kitty#4961]
**Is your feature request related to a problem? Please describe.**

I already read https://github.com/kovidgoyal/kitty/issues/952#issuecomment-420075784
and https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-cwd

I found that kitty can not split window with current layout cwd just like tmux.

I have a simple `Makefile` to demo the problem:

```makefile
all:
	@test -d subdir001 || mkdir subdir001
	@cd subdir001 ;\
	echo "current dir is: $$PWD"; \
	echo "begin sleep 10 seconds"; \
	sleep 10; \
	cd ../; \
	echo "current dir is: $$PWD"; \
	echo "all done"
```

```shell
mkdir /tmp/test-kitty-new-window
```
and then put above `Makefile` under `/tmp/test-kitty-new-window`

```
cd /tmp/test-kitty-new-window
```

run `make`, and split window one time, kitty will split a new window with cwd=`/tmp/test-kitty-new-window/subdir001`
after the command run, it change back to the original cwd. this time, if split with kitty, kitty will split a new window with cwd=`/tmp/test-kitty-new-window`

but in tmux, both time will split window with cwd=`/tmp/test-kitty-new-window`

**Describe the solution you'd like**

split with cwd like tmux. 

**Describe alternatives you've considered**

**Additional context**

with kitty:
![image](https://user-images.githubusercontent.com/41882455/163145972-250a9db5-7bb4-4e23-8313-982ded39ce98.png)

with tmux:
![image](https://user-images.githubusercontent.com/41882455/163146141-1f6ac336-1c35-4965-97e2-60279c3ee2bc.png)

**Comment by kovidgoyal** [comment]
I am afraid behavior compatible with tmux is not a goal for kitty. Using --cwd=current will use the cwd from the foreground process associated with the tty device with the highest PID. If you want some to use the cwd of the shell instead, make sure shell integration is enabled and use --cwd=last_reported

**Comment by ttys3** [comment]
actually it is not related to tmux.
I use tmux just for simply discribe the feature.
the problem is I like the feature. 

I found that in my config `shell_integration enabled` is set. but the shell integration actually not enabled.
don't know how.

how does the kitty automatic shell integration work?  I want to resolve the problem so that I could use `--cwd=last_reported`

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/shell-integration

**Comment by ttys3** [comment]
by the way, I tested `Manual shell integration`, it works.

**Comment by ttys3** [comment]
so what is "The automatic shell integration " for zsh ?

I set `shell_integration enabled` it does not work.

only "Manual shell integration" works

**Comment by kovidgoyal** [comment]
The link above tells you exactly what it is.

**Comment by ttys3** [comment]
OK. I see this:
https://github.com/kovidgoyal/kitty/blob/7788f48dd5f09506953c73f77cb71ce7f1b2f897/shell-integration/ssh/bootstrap.py#L218

```python
def exec_zsh_with_integration():
    zdotdir = os.environ.get('ZDOTDIR') or ''
    if not zdotdir:
        zdotdir = HOME
        os.environ.pop('KITTY_ORIG_ZDOTDIR', None)  # ensure this is not propagated
    else:
        os.environ['KITTY_ORIG_ZDOTDIR'] = zdotdir
    # dont prevent zsh-newuser-install from running
    for q in ('.zshrc', '.zshenv', '.zprofile', '.zlogin'):
        if os.path.exists(os.path.join(zdotdir, q)):
            os.environ['ZDOTDIR'] = shell_integration_dir + '/zsh'
            os.execlp(login_shell, os.path.basename(login_shell), '-l')
    os.environ.pop('KITTY_ORIG_ZDOTDIR', None)  # ensure this is not propagated
```
it should set `ZDOTDIR` env var. but I see it is empty

**Comment by kovidgoyal** [comment]
ZDOTDIR will be restored to its original value by the integration
script. So it being empty is correct.

**Comment by ttys3** [comment]
OK. got it. my problem resolved.

auto shell_integration works.

**Comment by ttys3** [comment]
the first time it does not work, it is because the window created is via session file.

the session file has the zsh launch command, I think this is the problem.

for new created window, the auto shell_integration works.
