### ISSUE TITLE
Closing a split in "The Splits Layout"

### ISSUE THREAD

**Issue by MDangleben** [kovidgoyal/kitty#4963]
There is no mapping for closing a split in the example config provided for the [Splits Layout](https://sw.kovidgoyal.net/kitty/layouts/#the-splits-layout).

Can anyone point me in the correct direction for the appropriate documentation for this.

**Comment by dimitris-triantafyllidis** [comment]
Search for "Actions" in kitty's online documentation. This should work:
https://sw.kovidgoyal.net/kitty/actions/?highlight=actions#action-close_window

**Comment by MDangleben** [comment]
This action closes the entire window instead of an individual pane.

**Comment by dimitris-triantafyllidis** [comment]
I just put these in my config and it works as expected, so I don't know what might be wrong in your case :-/ Maybe you are overriding this mapping later in your configuration `to close_os_window`?
```
map kitty_mod+enter new_window
map kitty_mod+l goto_layout splits
map kitty_mod+w close_window
```

**Comment by MDangleben** [comment]
Got it, thanks for the assistance.
