### ISSUE TITLE
Are you sure you want to close this OS window?

### ISSUE THREAD

**Issue by port19x** [kovidgoyal/kitty#4965]
**Describe the bug**
This is a breaking UX change, so I regard it as a bug.
This bug first appeared after I updated my arch machine yesterday.
Annoying confirmation prompt pops up every time I try to close my terminal window.

**To Reproduce**
1. launch kitty
2. run some commands (even ones that cleanly exit)
3. try closing the window
4. See unwelcome prompt

**Screenshots**
![whytho](https://user-images.githubusercontent.com/82055622/163264112-f25387c0-a126-43a8-9752-2fe417c3c9c8.png)

**Environment details**
Arch linux, latest version.
Can't copy paste right now as I'm on my debian machine.

**Additional context**
Likely caused by #4944
#734 is related
I see the value of this functionality, but it should be opt-in

**Comment by page-down** [comment]
This has nothing to do with the PR you listed.

See
https://github.com/kovidgoyal/kitty/discussions/4956
https://github.com/kovidgoyal/kitty/commit/00c1802319083c0176fc33d40960aca45f0efd98

Unfortunately this change is not logged in the changelog.

> I see the value of this functionality, but it should be opt-in

After I saw this change, I can already foresee that many people will be quite angry.
Do users who close their windows by mistake deserve some love?
Or is it better to stay on `0`? I think kovid has already made the choice.

**Comment by kovidgoyal** [comment]
It breaks nothing. The reasons for the change were outlined in the PR,
as pointed out by @page-down.

**Comment by avalonv** [comment]
this should not have been auto-enabled

**Comment by port19x** [comment]
> It breaks nothing. The reasons for the change were outlined in the PR, as pointed out by @page-down.

I fear you misunderstood.

**Comment by port19x** [comment]
I am not opposed to this feature existing, I'm opposed to it being the default.
I will have to transition to a different terminal emulator if you make me hit an unnecessary enter every time I want to close my terminal.
It breaks the UX. It should be opt in

**Comment by port19x** [comment]
> This has nothing to do with the PR you listed.
> 
> See #4956 [00c1802](https://github.com/kovidgoyal/kitty/commit/00c1802319083c0176fc33d40960aca45f0efd98)
> 
> Unfortunately this change is not logged in the changelog.
> 
> > I see the value of this functionality, but it should be opt-in
> 
> After I saw this change, I can already foresee that many people will be quite angry. Do users who close their windows by mistake deserve some love? Or is it better to stay on `0`? I think kovid has already made the choice.

I really hope he hasn't. I would miss icat over on [alacritty](https://github.com/alacritty/alacritty)

**Comment by port19x** [comment]
Regarding "it breaks nothing" in particular:
The average user, even among kitty users, opens a terminal to run a few commands and then close it again.
You could literally remove all kittens and replace gpu acceleration with a VTE-base and it would be less obvious of a change.
The only thing more breaking would be hardcoding a specific font or color scheme / changing the defaults for them too

**Comment by dimitris-triantafyllidis** [comment]
My god, what a disaster. Dead workflows everywhere...

**Comment by Freed-Wu** [comment]
I found a weird behavior: When I set `confirm_os_window_close 0` and not use tmux, this confirm dialog can be disabled. However, if I use tmux, this confirm dialog always enabled, whatever `confirm_os_window_close`. Is it a bug?

**Comment by eboody** [comment]
any update on this? can we turn this feature off..?

**Comment by port19x** [comment]
> any update on this? can we turn this feature off..?

Put `confirm_os_window_close 0` into your config file.
If you're not very invested in this terminal emulator you may wanna check out wezterm for a very feature rich emulator, foot for wayland native, or alacritty for equal speed

**Comment by metov** [comment]
What's the logic behind enabling this by default? Were there users asking for it, or did @kovidgoyal or someone else just decide that it's better? Is there really no hope of reconsidering?

>Put confirm_os_window_close 0 into your config file.

It's not fun to play whack-a-mole with strange defaults every version. It's much nicer if you don't fix what isn't broken.

Incidentally, the prompt is quite inconsistent. When I open a terminal and close it again without typing anything, sometimes I get the confirmation and sometimes I don't. It should make it clear what program specifically is preventing the close.

**Comment by dagorander** [comment]
It is a good thing I found this, because this anti-feature very nearly made me drop kitty completely and go back to alacritty.

If I press the key combination to close a window... it means I want to close the window. Right? @kovidgoyal this is the exact opposite of every terminal-centric workflow on the planet. Which is what we use high-performance terminal emulators for. Having to change my workflow from "Ctrl-Shift-C" to close active window to typing "exit" to have a terminal that's running absolutely nothing without needing to see a stupid popup is horrible. Having to trawl the internet and a 2241 line default config file (hoping I use the correct search term) is even worse.

Default should be 0. Because the default workflow is to open terminal and type shit like "ls" and "doas pkg_delete kitty". Not having some rando background thing running that you forgot about.

Listen to your users.

**Comment by sharpicx** [comment]
> What's the logic behind enabling this by default? Were there users asking for it, or did @kovidgoyal or someone else just decide that it's better? Is there really no hope of reconsidering?
> 
> > Put confirm_os_window_close 0 into your config file.
> 
> It's not fun to play whack-a-mole with strange defaults every version. It's much nicer if you don't fix what isn't broken.
> 
> Incidentally, the prompt is quite inconsistent. When I open a terminal and close it again without typing anything, sometimes I get the confirmation and sometimes I don't. It should make it clear what program specifically is preventing the close.

i couldnt agree more.

but imo, it aint 'incosistent' anymore. it just tell u that u have to stay on 0 `echo $0`. i know if it's trash, but at least u just need to add the `confirm_os_window_close 0` if u dont like the new updated feature.

**Comment by criptixo** [comment]
``confirm_os_window_close should`` be set to ``0`` by default

**Comment by criptixo** [comment]
``confirm_os_window_close`` should be set to ``0`` by default.

**Comment by hacker-DOM** [comment]
The way this should have been done is as an option to `close_os_window.`

**Comment by DD1TTY** [comment]
Just came across this thread when I began encountering this behavior using kitty on macOS. I used Command + , to open kitty.conf in vim, added confirm_os_window_close 0, hit esc, :wq and now the additional dialog does not show up. Phew!

**Comment by AnonymousVX** [comment]
> > any update on this? can we turn this feature off..?
> 
> Put `confirm_os_window_close 0` into your config file. If you're not very invested in this terminal emulator you may wanna check out wezterm for a very feature rich emulator, foot for wayland native, or alacritty for equal speed

thanks bro! I use kitty... for anyone wondering, it's the same for kitty i.e `confirm_os_window_close 0`.
