### ISSUE TITLE
Windows size issue in Gnome 42

### ISSUE THREAD

**Issue by mfgbhatti** [kovidgoyal/kitty#4966]
**Describe the bug**
After updating to gnome 42. Some how i am facing this issue. kitty is decreasing its windows size when you go to over view or app grid. I tried to play with `remember_window_size`. if it is yes and no `initial_window_width` and `initial_window_height` is provided this decreasing of size will happen. But if you maximise and then restore. This behaviour stops. It was working fine with gnome 42 until updated to 25

**Screenshots**
![Screenshot from 2022-04-14 14-29-22](https://user-images.githubusercontent.com/13787498/163401849-86739087-2395-42ec-9ed5-3b1bf94314d8.png)
![Screenshot from 2022-04-14 14-29-35](https://user-images.githubusercontent.com/13787498/163401854-735fb536-5269-432d-91bf-5901f221835f.png)
![Screenshot from 2022-04-14 14-29-58](https://user-images.githubusercontent.com/13787498/163401860-7f378876-7f80-48c1-9de6-cbd643f78eea.png)

**Environment details**
- Linux archlinux 5.15.33-1-lts
- gnome-desktop 1:42.0-1
- gnome-shell 1:42.0-1

Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
```kitty 0.25.0 created by Kovid Goyal
Linux archlinux 5.15.33-1-lts #1 SMP Fri, 08 Apr 2022 13:43:36 +0000 x86_64
Arch Linux 5.15.33-1-lts (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/farhan/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.7
draw_minimal_borders       False
dynamic_background_opacity True
font_family                Hack Nerd Font
font_size                  14.0
hide_window_decorations    1
initial_window_height      (1484, 'px')
initial_window_width       (2780, 'px')
remember_window_size       False
scrollback_pager           ['less', '+G', '-R']
shell_integration          frozenset({'no-cursor'})
tab_bar_style              powerline
url_prefixes               ('http', 'https', 'file', 'ftp', 'gemini', 'irc', 'gopher', 'mailto', 'news', 'git')
window_border_width        (0, 'pt')
window_padding_width       FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Changed shortcuts:
	ctrl+shift+f → toggle_maximized
	ctrl+shift+w → close_tab
	ctrl+shift+backspace → restore_font_size
	ctrl+shift+up → increase_font_size
	ctrl+shift+down → decrease_font_size
Colors:
	color1                     #d44d53   
	color10                    #b9c949   
	color11                    #e6c446   
	color12                    #79a6da   
	color13                    #c396d7   
	color14                    #70c0b1   
	color15                    #fffefe   
	color2                     #b9c949   
	color3                     #e6c446   
	color4                     #79a6da   
	color5                     #c396d7   
	color6                     #70c0b1   
	color7                     #fffefe   
	color8                     #000000   
	color9                     #d44d53   
	cursor                     #e9e9e9   
	foreground                 #e9e9e9   
	selection_background       #424242   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/usr/local/sbin:/home/farhan/.dotnet/tools:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_GB.UTF-8
	EDITOR                              nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                farhan
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

I was not able to reproduce the above problem with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
If you cant reproduce the problem with --config=NONE bisect kitty.conf till you find the culprit. My guess would be hide_window_decorations. 

On a general note, GNOME is not the best choice (it refuses to implement server side decorations, its wayland compositor, mutter, is full of bugs and it keeps breaking things with every release), so I would suggest using something else, or using linux_display_backed x11 in kitty.conf to workaround mutter.

**Comment by kovidgoyal** [comment]
no followup
