### ISSUE TITLE
Add `adjust_line_height` to the kitty remote

### ISSUE THREAD

**Issue by evantravers** [kovidgoyal/kitty#4968]
I love using Kitty to create workspaces for specific tasks… and one of those is for prose only. I use a combination of vim, tmux, and kitty to enter a "prose mode" with different colors, margin, and font size just for writing prose as opposed to code.

I'd love to be able to programmatically bump the line height to `150%` or something when fi enter the prose mode… I can change the text size… it'd be nice to do the same using zen-mode.nvim.

I played around with:
- launching kitty with a new config file ala `kitty --config zen.conf`
- trying to send a command to it
- creating a custom theme that included the `adjust_line_height` (ignored the command)

**Comment by evantravers** [comment]
An example of how nice this would be… 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/62209/163430548-3fbb732e-2c3f-4cea-8131-e7299f4494b1.png">

**Comment by kovidgoyal** [comment]
kitty -o adjust_line_height=whatever

**Comment by evantravers** [comment]
Does that let me adjust all the open sessions ala remote? I can open a new one, but I was hoping to adjust the running session and then swap it back.

(also… thank you for creating so much of my programming experience!!)

**Comment by kovidgoyal** [comment]
Add

include linehight.conf

to kitty.conf

Then use

echo 'adjust_line_height whatever' > ~/.config/kitty/lineheight.conf
pkill -SIGUSR1 kitty
