### ISSUE TITLE
Open new tabs/windows/os-windows with the working directory of the current one

### ISSUE THREAD

**Issue by RedBeard0531** [kovidgoyal/kitty#497]
On linux you can get this from `/proc/PID_OF_SHELL/cwd`. Alternatively you could do something like vte and put something in /etc/profile.d to snoop the directory in `PROMPT_COMMAND`: https://github.com/GNOME/vte/blob/master/src/vte.sh (or lie and claim to be vte to that script and use the same protocol...)

**Comment by kovidgoyal** [comment]
Already implemented, search kitty.conf for with_cwd

**Comment by SolitudeSF** [comment]
`new_tab_with_cwd`
`new_os_window_with_cwd`
`new_window_with_cwd`

**Comment by rightaway** [comment]
Where can I see all the configuration options available? I don't see it on the website anymore.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html
