### ISSUE TITLE
Allow desaturating inactive kitty windows

### ISSUE THREAD

**Issue by ismay** [kovidgoyal/kitty#4974]
**Is your feature request related to a problem? Please describe.**

`inactive_text_alpha` is very useful for when you want to be able to quickly identify which kitty window has focus. However, it decreases the legibility of the inactive text. I often have multiple windows open, and I still want to be able to read the text in the inactive windows.

**Describe the solution you'd like**

An option to desaturate inactive kitty windows, say `inactive_window_saturation` would be perfect. I could partially desaturate the inactive windows, which would clearly indicate the active window (the one with all the colors). And I could then still easily read the text in the inactive windows.

**Describe alternatives you've considered**

I've tried using other ways of indicating focus, but this seemed like a very elegant solution to me.

**Additional context**

A kitty instance with multiple windows open. Fairly difficult to see which window has focus at a glance:

![Screenshot from 2022-04-15 19-41-12](https://user-images.githubusercontent.com/7355199/163603483-35e6f26f-0068-46c7-96db-ece51d31c6bf.png)

Here it's a lot easier already, with the saturation turned down on inactive windows:

![Screenshot from 2022-04-15 19-41-12 2](https://user-images.githubusercontent.com/7355199/163603582-9a53b627-8a35-4aee-b3b1-ca52e0028f8d.png)

For illustration, this is with the saturation turned completely down:

![Screenshot from 2022-04-15 19-41-12 3](https://user-images.githubusercontent.com/7355199/163603725-249e050f-8c96-44fb-a976-12745985297e.png)

Now most likely most people won't turn down the saturation completely. Just like most people won't turn down the inactive text alpha completely. But even if you do turn down the saturation, everything is still very legible. And it is extremely clear to see which window has focus.

I can imagine this setting wouldn't affect background color, like it does in the images (judging from the option name inactive_**text**). Would be nice if that were possible as it does a lot for the effect. If not, then the question is how much of an effect turning down the saturation would still have. I can imagine it would still help a lot.

**Comment by kovidgoyal** [comment]
This would only work if your windows were highly colored in the first place. For typical terminal text which is white on black (or largely monochrome/2-color) this will have little effect.

**Comment by ismay** [comment]
> This would only work if your windows were highly colored in the first place. For typical terminal text which is white on black (or largely monochrome/2-color) this will have little effect.

That’s true. However, for those that do use color it would be very effective I think. And judging from the popularity of terminal color schemes I think that a lot of people fall in that category.

**Comment by ismay** [comment]
Maybe my editor (kakoune) is also to blame though. As you can see it shows a cursor by default in all open windows. Unlike vim or neovim which only show the cursor in the active buffer.

So maybe the problem is not as common for others, or worth solving in kitty.

**Comment by kovidgoyal** [comment]
Yes, that is fairly weird. Cursor is usually the primary way to
distinguish focused window. You can also try making the window borders
thicker in kitty though that is somewhat ugly.

**Comment by kovidgoyal** [comment]
Thinking about this since this issue is caused by the kakoune editor, a
better solution would be to fix it there. I dont know if it has
FocusGained and FocusLost events like vim does. But if it does, you
could possibly simply change the color scheme in the editor, and/or hide
the cursor on these events. Indeed, maybe suggest to the kakoune
developers that they hide the cursor in unfocused windows by default or
at least provide and option to do so.

**Comment by ismay** [comment]
Yeah I think you're right. I was looking to handling this in kitty as a one-size-fits-all solution, but it does seem like a problem solely caused by kakoune.

> You can also try making the window borders thicker in kitty though that is somewhat ugly.

Yeah. Plus the minimal borders still make it a little hard to distinguish the active window sometimes, even if they're thicker. I tried using full borders as well, but there the border alignment was off sometimes, which doesn't matter functionally but did bother me visually.

> Thinking about this since this issue is caused by the kakoune editor, a better solution would be to fix it there. I dont know if it has FocusGained and FocusLost events like vim does. But if it does, you could possibly simply change the color scheme in the editor, and/or hide the cursor on these events.

Yeah, it does, and I agree that that does seem like the best fix. Thanks for the feedback and for all the good work 👍
