### ISSUE TITLE
Font is rendered differently in kitty and xfce-terminal

### ISSUE THREAD

**Issue by XenGi** [kovidgoyal/kitty#4976]
![image](https://user-images.githubusercontent.com/1043980/163607703-6d045c86-446e-4bd8-b10f-8bbcf6dce364.png)
![image](https://user-images.githubusercontent.com/1043980/163615473-84256d5d-2e7c-4fe0-a37f-ff50c3fd6d5c.png)

I'm using the same font in both terminals. So I would assume it looks the same but the font has 1px more height in the middle of letters in kitty.

`~/.config/kitty/kitty.conf`:
```
font_family         DejaVu Sans Mono
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size           10
adjust_line_height  0
adjust_column_width 0
adjust_baseline     0
placement_strategy  top-left
```
`~/.config/xfce4/terminal/terminalrc`:
```ini
[Configuration]
FontName=DejaVu Sans Mono 10
```

My guess is that the GPU renders the font slightly different and the result of that line is basically on a different pixel when rendered that way.

**Comment by kovidgoyal** [comment]
I'm afraid amtching the rendering of xfce4 is not a goal for kitty.

**Comment by XenGi** [comment]
How do you know that kitty is the one rendering the font correctly? Thx for nothing I guess. Would at least been interested in the reason why it is different.

**Comment by kovidgoyal** [comment]
On Sat, Apr 16, 2022 at 12:21:20PM -0700, Ricardo Band wrote:
> How do you know that kitty is the one rendering the font correctly? 

Because I wrote the code that renders the fonts for kitty.


> Thx for nothing I guess. Would at least been interested in the reason why it is different.

So now you expect me to go read xfce4's codebase and understand it and
then report to you what it does wrong, for free? Get a grip.

**Comment by XenGi** [comment]
No I expect you to give that answer in the first place. How would I know that you wrote that code?
If you implemented it to the standard and not to your liking which has slightly different characters or something then the rendering mistake is probably in xfce terminal. Or like I said, it's probably just a difference in how things work under the hood and not a mistake at all.
Sorry for the rude comment.
