### ISSUE TITLE
show_key kitten does not catch kitty_mod+T or N

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4978]
**Describe the bug**
When using the `show_key` kitten, `kitty_mod+T` or `kitty_mod+N` creates new tabs and OS windows, respectively, instead of printing the key combo.

**To Reproduce**
1. `kitty --config NONE`
2. `kitty +kitten show_key`
3. `kitty_mod+T` or `kitty_mod+N`

**Observed Behavior**
New tab or OS window gets created.

**Expected Behavior**
The `show_key` kitten shall intercept these combos and print them without creating new tabs and or OS windows.

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux byteevo 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64
Ubuntu 20.04.4 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
Since the kitten intercepts a more powerful combo like `CTRL+C`, I'd also expect it to intercept Tab/Window related key combos.

**Comment by kovidgoyal** [comment]
Yes, show_key shows keys that reach the terminal program. Shortcuts used for actions in kitty never reach terminal programs. Use clear_all_shortcuts or map individual ones you need to see to no_op

**Comment by salmankhilji** [comment]
> Yes, show_key shows keys that reach the terminal program. Shortcuts used for actions in kitty never reach terminal programs. Use clear_all_shortcuts or map individual ones you need to see to no_op

Makes sense.  You may want to update [the FAQ entry](https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program) with this info.
