### ISSUE TITLE
Support for adding new escape sequences

### ISSUE THREAD

**Issue by fdw** [kovidgoyal/kitty#498]
I'd like to map Ctrl+Enter to a new escape sequence so that I can use it in zsh. However, I'm not sure if this is even supported by Kitty yet.
As far as I understand the documentation, I have to use the [extended protocol](https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc#keyboard-handling), but I'm not sure how to proceed:
* Is this even the correct approach?
* How can I calculate the correct modifier - I have to encode the modifier (0x2) to base64?
* To what should I map this escape sequence, so that zsh can pick it up?

I have seen #477 and #94, but it seems (to me, at least) that zsh can already handle new escape sequences, I just need to define them in the emulator.

Thanks you :)

**Comment by kovidgoyal** [comment]
Use send_text see the default kitty.conf for examples.

**Comment by fdw** [comment]
Thanks for the pointer. Unfortunately, I have not got it to work.
According to the docs, something like this should work: `map <ESC>_KrEz<ESC>\ send_text special auto_suggest_run`. However, ctrl+enter still sends the same keys as enter alone (based on `showkey -a`).
Also variants like `map ctrl+enter` didn't work either, but I expected that.

**Comment by kovidgoyal** [comment]
No you want

```
map ctrl+enter send_text all \x1b_KreX\x1b\
```

**Comment by kovidgoyal** [comment]
Sorry should be \\ at the end not a single \

**Comment by kovidgoyal** [comment]
Oh and you should not use all (instead use normal and application only as you dont want this mapping in kitty's extended keyboard mode, which supports ctrl+enter out of the box).

**Comment by fdw** [comment]
That worked. Thank you so much! :)
