### ISSUE TITLE
confirm_os_window_close negative value not honored in M1 mac (apple silicon)

### ISSUE THREAD

**Issue by fhfuih** [kovidgoyal/kitty#4980]
**Describe the bug**
I am using an M1 mac, and I have set `confirm_os_window_close` to a negative value, e.g. -1.
When I attempted to close a kitty OS window which contains only one kitty window at zsh prompt, it still confirms before exiting. According to the kitty.conf documentation, when I only have one kitty window sitting at shell prompt, the exit action shall require no confirmation.

**To Reproduce**
1. Launch kitty. 
2. Explicitly `confirm_os_window_close` to -1 to ensure. And make sure the new config is loaded
3. Check that zsh integration in enabled by `echo $KITTY_SHELL_INTEGRATION`
4. Click the close button of the app window. Will see confirmation.5. 

Alternatively, before 3, launch a new kitty instance by the command `kitty --config NONE zsh --no-rcs`. Perform 3 & 4 in that kitty instance. The problem persists.

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Darwin ZeyuBook-4.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.3 BuildVersion:	21E230
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/zeyu/.config/kitty/kitty.conf

Config options different from defaults:
font_family          Cascadia Code PL
font_features:
{'CascadiaCodePL': ('+calt', '+ss01'),
 'CascadiaCodePL-BoldItalic': ('+calt', '+ss01'),
 'CascadiaCodePL-ExtraLightItalic': ('+calt', '+ss01'),
 'CascadiaCodePL-Italic': ('+calt', '+ss01'),
 'CascadiaCodePL-LightItalic': ('+calt', '+ss01'),
 'CascadiaCodePL-SemiBoldItalic': ('+calt', '+ss01'),
 'CascadiaCodePL-SemiLightItalic': ('+calt', '+ss01')}
font_size            12.0
symbol_map:
	U+23fb - U+23fe → Symbols Nerd Font
	U+2665 - U+2665 → Symbols Nerd Font
	U+26a1 - U+26a1 → Symbols Nerd Font
	U+2b58 - U+2b58 → Symbols Nerd Font
	U+e000 - U+e00a → Symbols Nerd Font
	U+e0a3 - U+e0a3 → Symbols Nerd Font
	U+e0b4 - U+e0c8 → Symbols Nerd Font
	U+e0ca - U+e0ca → Symbols Nerd Font
	U+e0cc - U+e0d4 → Symbols Nerd Font
	U+e200 - U+e2a9 → Symbols Nerd Font
	U+e300 - U+e3eb → Symbols Nerd Font
	U+e5fa - U+e631 → Symbols Nerd Font
	U+e700 - U+e7c5 → Symbols Nerd Font
	U+ea60 - U+ebeb → Symbols Nerd Font
	U+f000 - U+f2e0 → Symbols Nerd Font
	U+f300 - U+f32d → Symbols Nerd Font
	U+f400 - U+f4a9 → Symbols Nerd Font
	U+f500 - U+fd46 → Symbols Nerd Font
Colors:
	background           #111213   
	color0               #323232   
	color1               #c22832   
	color10              #8ec43d   
	color11              #e0c64f   
	color12              #43a5d5   
	color13              #8b57b5   
	color14              #8ec43d   
	color2               #8ec43d   
	color3               #e0c64f   
	color4               #43a5d5   
	color5               #8b57b5   
	color6               #8ec43d   
	color7               #eeeeee   
	color8               #323232   
	color9               #c22832   
	cursor               #e2be21   
	foreground           #cacecd   
	selection_background #303233   
	selection_foreground #111213   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                zh_HK.UTF-8
	SHELL                               /bin/zsh
	USER                                zeyu
```

**Additional context**
~~Try to reproduce the problem with `kitty --config NONE`~~ Ooops, mentioned above.

**Comment by page-down** [comment]
> Check that zsh integration in enabled by echo $KITTY_SHELL_INTEGRATION

When the shell integration takes effect correctly, this environment variable will not exist after initialization.

> ... zsh --no-rcs

This will indirectly disable shell integration.

You can try `kitty --config=NONE -o shell=/bin/zsh -o confirm_os_window_close=-1`.

I cannot reproduce the issue.

**Comment by fhfuih** [comment]
Hi, thanks for the reply. Your command did work. I also tried removing those cmd args one-by-one and found that simply `kitty` a new kitty instance from any other terminal will honor this config entry, whereas the kitty launched by clicking the app icon or kitty.app entry in spotlight will not.

Also I haven't modify cursor styles in kitty config, but in `kitty` kitty it is a line, whereas in icon kitty it is a block.

The font settings are honored in either kitty...

**Comment by kovidgoyal** [comment]
You have something in your system env vs the env when running from the sheel that is affecting what config files kitty is loading. Figure out what that is, by looking at the difference in the output from the kitty config debug dump.

**Comment by page-down** [comment]
> ... whereas the kitty launched by clicking the app icon or kitty.app entry in spotlight will not.

https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

> Also I haven't modify cursor styles in kitty config ...

This works as expected.

https://sw.kovidgoyal.net/kitty/shell-integration/

See the pinned issue for reasons and related discussions.

**Comment by fhfuih** [comment]
Thanks for the replies! As a record, in my case kitty does honor its config file, but the zsh shell integration seems not working when I click-open kitty from its app icon, thus all shell-integration-related configs, e.g. confirm_os_window_close and cursor shapes, are not working.

Solution: Instead of changing the system env (and I didn't find any info regarding how to change system env to make shell integration work), I added the following snippet to my `.zshrc` and it works.
```
if test -n "$KITTY_INSTALLATION_DIR"; then
    export KITTY_SHELL_INTEGRATION="enabled"
    autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
    kitty-integration
    unfunction kitty-integration
fi
```

 This snippet is documented in the comments of kitty's [zsh shell integration source code](https://sw.kovidgoyal.net/kitty/shell-integration/#how-it-works), and mentioned in [the pinned post](https://github.com/kovidgoyal/kitty/issues/4438#issuecomment-1095596787). But later comments suggested not manually providing this snippet in bashrc to prevent redundant sourcing. Not sure if it is really a bash-vs-zsh difference, or linux-vs-mac issue.

And I think my case is applicable to any other macOS users (12 Monterey so far) as my config is minimal.

**Comment by fhfuih** [comment]
But I would also like to ask the following questions:

1. In the pinnerd issue, some users' debug print is more verbose than mine. Did they use something else than pure opt+cmd+,? They can even see whether the shell integration is enabled or not, but mine above didn't tell. How can I know whether shell inegration is enabled or not, either in the debug or at runtime (so I can change prompt or print something to warn unsuccessful integration)

2. What system-wide envs can possibly confuse the shell integration process? Because online information on mac systemenv is very scattered and it seems mac itself changes behavior from time to time. I believe I haven't touched system env, so I would love to see the root cause of this issue on macOS. Some ideas on this may help us users debug this issue.

**Comment by page-down** [comment]
Regarding zsh, one possibility comes to my mind.
When no zsh configuration file such as `.zshrc` exists under HOME, shell integration will not be enabled, and as I recall `zsh-newuser-install` will not run under macOS.
It looks like zsh is running fine, but no shell integration.

> ... simply kitty a new kitty instance from any terminal (including an existing kitty) will honor this config entry ...
> ... but the zsh shell integration seems not working when I click-open kitty from its app icon ...

However, based on your description, it does not appear to be related to the above.

> But later comments suggested not manually providing this snippet in bashrc ...

This is the manual configuration script, which is described in detail in my link above. What is mentioned in the pinned issue is that the scripts **automatically added** by previous versions of kitty can now be removed.

If you are interested, you can start with empty configs to troubleshoot exactly why the automatic shell integration is not working. For example move `.zshrc` and `kitty.conf` and create empty ones.

Under macOS, you may also want to add some path to `PATH` using the following configuration, otherwise kitty will not find the executable you expect when launched from the Dock, Launchpad, Spotlight, or other apps.

(From your config debug I can see that the kitty process was started by another app.)

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path
```conf
exe_search_path /usr/local/bin
exe_search_path /opt/homebrew/bin
```

> In the pinnerd issue, some users' debug print is more verbose than mine. ...

Those are their custom configs (different from the default). There isn't another special debug feature, it's just that they configure more things.

> What system-wide envs can possibly confuse the shell integration process? ...

You can try the `show_kitty_env_vars` mentioned in the FAQ link above to check the environment variables seen by kitty.
If it's launched via macOS launchd, I don't think there are any more environment variables that can affect shell auto-integration, because this thing can't easily set system-wide environment variables. There are only a very limited number of environment variables.

**Comment by kovidgoyal** [comment]
This issue definitely does not affect macos users in general. As I said,
use the debug facilities in kitty to see whats different. You can add

map f1 show_kitty_env_vars

to kitty.conf the press F1 to see hwats different in the environments.

**Comment by fhfuih** [comment]
Hi all, thanks for the guidance. I suspect for me it is [fig](https://fig.io/) who somehow prevented the kitty integ. Will report a issue on their side.
