### ISSUE TITLE
Kitty command on latest 0.25.0 macOS version causing traceback

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#4981]
Hello Experts,

if I run the command kitty on the terminal. it causes a traceback and does not start after the upgrade to 0.25.0. It was working on version 0.24.0. Any idea why it's failing as I haven't changed anything in my kitty.conf . how could I fix this issue?

![image](https://user-images.githubusercontent.com/11479557/163713600-fec7c450-16f6-49df-8a93-9be79ea5ff00.png)

**Comment by kovidgoyal** [comment]
That error indicates you are using listen_on and it is pointing to a
directory that does not exist. Remove it and you will be fine.

**Comment by ciscohack** [comment]
@kovidgoyal Thank you, sir issue resolved, accidentally extra character add and caused the issue

**Comment by ciscohack** [comment]
@kovidgoyal needs your help is this error also. this does not look due to the previous config issue 

![image](https://user-images.githubusercontent.com/11479557/163925177-b0ef9fe6-beac-4740-9062-67b5593fbacb.png)

**Comment by page-down** [comment]
> ... i ran kitty +kitten diff command and got this error

I believe the above issue is fixed in the following commit.
You might want to try the next nightly release.

https://github.com/kovidgoyal/kitty/commit/402fac3edf6bb1817a3f7372f12f97bd4c04829b

**Comment by ciscohack** [comment]
> > ... i ran kitty +kitten diff command and got this error
> 
> I believe the above issue is fixed in the following commit. You might want to try the next nightly release.
> 
> [402fac3](https://github.com/kovidgoyal/kitty/commit/402fac3edf6bb1817a3f7372f12f97bd4c04829b)

my saviour @page-down  thank you my friend once again. I changed my config thought some config causing conflict :P

**Comment by ciscohack** [comment]
Issue not resolved in new nightly...

![image](https://user-images.githubusercontent.com/11479557/164151313-d64c3376-3a61-4d5e-ad85-55c3ca591fb6.png)

**Comment by kovidgoyal** [comment]
You need to provide a way to reproduce the error.

**Comment by ciscohack** [comment]
I have 2  big log files with thousands of line logs comparing them with kitty kitten+ diff  <file_name.log> vs <file_name2.log> and traceback generated. So basically I am not doing any thing fancy just using the builtin tool to compare  2 files and getting traceback 

below is the command.

kitty kitten+ diff 20220406-063833608_10.48.66.196_20220406_143408_sh_tech_non.txt 20220411-045528766_5512LAB

**Comment by kovidgoyal** [comment]
Do some bisecting on the two log files and find small subsets of them that reproduce the error.
