### ISSUE TITLE
Set theme only in OS window

### ISSUE THREAD

**Issue by rotu** [kovidgoyal/kitty#4989]
**Is your feature request related to a problem? Please describe.**

I was trying to change my theme when I ssh into a particular host and had a hard time doing so.

**Describe the solution you'd like**

A feature in the themes kitten to change the theme in the current window without modifying any config files.
And for such a feature to be easily discoverable at [Changing kitty colors](https://sw.kovidgoyal.net/kitty/kittens/themes/#changing-kitty-colors).

**Describe alternatives you've considered**

The most obvious substitute is:
```sh
kitty +kitten themes --reload-in=parent 1984 Orwellian
```
But:
1. it changes the config file so the changes are persistent
2. it changes the theme in all open OS windows (maybe bug?).

The best substitute I could find is:
```sh
kitty +kitten themes --dump-theme 1984\ Orwellian > /tmp/kittytheme.conf
kitty @ launch --type=os-window --color=/tmp/kittytheme.conf ssh somehost
```

But:
1. unlike the `+kitten themes` requires editing allow_remote_control
2. it's far from intuitive.

**Comment by rotu** [comment]
It looks like https://github.com/kovidgoyal/kitty/commit/dd331ca12efcb753ae3d8a6cce04d7c078601195 may make this largely unneeded. Still, it might bear mention on the "Changing kitty colors" page.

**Comment by rotu** [comment]
It looks like my particular use case is largely addressed by recent changes to [`+kitten ssh`](https://sw.kovidgoyal.net/kitty/kittens/ssh/?highlight=ssh#opt-kitten-ssh.color_scheme). I did not discover this since `kitty +kitten ssh --help` brings up help for the underlying ssh command, not for the ssh kitten.

Still, it might bear mention on the "Changing kitty colors" page.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.color_scheme

**Comment by rotu** [comment]
@kovidgoyal I did eventually discover that. Is there a reason the themes kitten doesn’t support merely setting the theme on the current window and not writing it to config? That’s what I expected `--reload-in=parent` to do (and I can’t think of a use case where the existing behavior is desired).

https://sw.kovidgoyal.net/kitty/kittens/themes/#changing-kitty-colors

**Comment by kovidgoyal** [comment]
The themes kitten is meant to make permanent changes not temporary ones.
If you want temporary changes use the terminal escape codes for it,
documented in the FAQ
