### ISSUE TITLE
Mouse cursor movement triggers scrolling in vim

### ISSUE THREAD

**Issue by twouters** [kovidgoyal/kitty#4992]
**Describe the bug**
After updating from 0.24.4 to 0.25.0 I noticed that vim scrolls up when moving the mouse cursor. See below screencast.  
![screencast-2022-04-20_10-37-38](https://user-images.githubusercontent.com/170895/164256932-4806a94a-30ae-40a9-82ed-8ff8fff2b9ac.gif)

A similar issue has been reported to vim but it's not clear whether it's a vim or terminal bug, but it's suspicious that two terminals exhibit similar behavior: https://github.com/vim/vim/issues/9863

**To Reproduce**
1. Install kitty 0.25.0
2. Install vim >= 8.2.4106 (not sure if older versions are not impacted)
3. Create clean vimrc file with below content
4. Run vim with clean rc: `vim --clean -u vimrc`
5. Insert a few lines to exceed terminal size
6. Scroll down a bit and move mouse
7. Notice that vim scrolls upwards

Minimal vimrc to reproduce:

```
set mouse=a
set ttymouse=xterm2
set balloonevalterm
```

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux titanic 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000 x86_64
Arch Linux 5.17.3-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/twouters/.pyenv/plugins/pyenv-virtualenv/shims:/home/twouters/bin:/home/twouters/.pyenv/shims:/home/twouters/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/twouters/.cabal/bin
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                twouters
	XDG_CONFIG_HOME                     /home/twouters/.config
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    tty
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      3
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Comment by kovidgoyal** [comment]
You want

ttymouse=sgr

**Comment by twouters** [comment]
@kovidgoyal I tried that earlier today but it didn't help as far as I remember. I'll try again in a bit.

**Comment by twouters** [comment]
@kovidgoyal can you reopen? It's the same with ttymouse=sgr

**Comment by kovidgoyal** [comment]
I cannot repro with a vimrc containing only

set mouse=a
set ttymouse=sgr

vim version 8.2.4651
kitty running from master

**Comment by kovidgoyal** [comment]
Or are you saying the issue is with balloonevalterm?
