### ISSUE TITLE
middle click pastes clipboard even after mapping to `no_op`

### ISSUE THREAD

**Issue by BLucky-gh** [kovidgoyal/kitty#4994]
**Describe the bug**
Middle clicking pastes the current clipboard contents, but I want it to paste the contents of a buffer, so I tried this
```
copy_on_select selection

mouse_map middle click ungrapped no_op
mouse_map middle click ungrabbed paste_from_buffer selection
mouse_map shift+middle click grabbed paste_from_buffer selection
```
but when I select something and then middle click it first pastes the current *clipboard* contents, and then after a short delay inserts the contents of the `selection` buffer

**To Reproduce**
1. add the aforementioned config to `kitty.conf`
2. select something
3. middle click

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Darwin bluckymac.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.3.1 BuildVersion:	21E258
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/blucky/.config/kitty/kitty.conf

Config options different from defaults:
background_image                   /Users/blucky/backgrounds/bg.png
background_image_layout            scaled
background_opacity                 0.8
background_tint                    0.85
close_on_child_death               True
copy_on_select                     selection
font_family                        RobotoMono Nerd Font Mono
font_size                          10.0
inactive_text_alpha                0.8
macos_hide_from_tasks              True
macos_option_as_alt                3
macos_quit_when_last_window_closed True
mouse_hide_wait                    -1.0
pointer_shape_when_grabbed         hand
resize_draw_strategy               3
resize_in_steps                    True
scrollback_fill_enlarged_window    True
scrollback_lines                   4096
scrollback_pager_history_size      8388608
shell_integration                  frozenset({'no-rc'})
strip_trailing_spaces              smart
tab_activity_symbol                碌 (note from me: this is supposed to be a nerd-font icon)
tab_bar_edge                       1
tab_bar_margin_height              TabBarMarginHeight(outer=0, inner=0.1)
tab_bar_style                      slant
tab_title_template                 {index}:{fmt.fg.tab}{title.split()[0]} {fmt.fg.red}{bell_symbol}{activity_symbol}
visual_bell_duration               0.1
window_logo_alpha                  0.4
Added mouse actions:
	middle click ungrabbed → paste_from_buffer selection
	shift+middle click grabbed → paste_from_buffer selection
Colors:
	active_border_color                #c9cbff   
	active_tab_background              #575268   
	active_tab_foreground              #f5c2e7   
	background                         #1e1e2e   
	bell_border_color                  #fae3b0   
	color0                             #6e6c7e   
	color1                             #f28fad   
	color10                            #abe9b3   
	color11                            #fae3b0   
	color12                            #96cdfb   
	color13                            #f5c2e7   
	color14                            #89dceb   
	color15                            #d9e0ee   
	color2                             #abe9b3   
	color3                             #fae3b0   
	color4                             #96cdfb   
	color5                             #f5c2e7   
	color6                             #89dceb   
	color7                             #d9e0ee   
	color8                             #988ba2   
	color9                             #f28fad   
	cursor                             #f5e0dc   
	cursor_text_color                  #1e1e2e   
	foreground                         #d9e0ee   
	inactive_border_color              #575268   
	inactive_tab_background            #1e1e2e   
	inactive_tab_foreground            #d9e0ee   
	mark1_background                   #96cdfb   
	mark1_foreground                   #1e1e2e   
	mark2_background                   #f5c2e7   
	mark2_foreground                   #1e1e2e   
	mark3_background                   #b5e8e0   
	mark3_foreground                   #1e1e2e   
	selection_background               #575268   
	selection_foreground               #d9e0ee   
	tab_bar_background                 #161320   
	url_color                          #f5e0dc   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.gOHXlhw209/org.xquartz:0
	USER                                blucky
```

**Comment by kovidgoyal** [comment]
See the mouse actions docs, paying special attention to the difference
between press and click events.

**Comment by BLucky-gh** [comment]
> paying special attention to the difference between press and click events.
The docs don't specify the difference between events, only that they are separate events. I tried unmapping both press and click and it still pastes on middle click. 

It would be nice to see all the default shortcuts (as in those that are present even without a `kitty.conf`) since I checked all the `mouse_mod middle` lines in my `kitty.conf` and the ones I showed above are the only 3 lines

**Comment by page-down** [comment]
I tried the following and it worked fine.

```shell
kitty -o copy_on_select=a1 -o "mouse_map middle release ungrabbed paste_from_buffer a1" -o "mouse_map shift+middle release u
ngrabbed,grabbed paste_from_buffer a1"
```
> ... didn't find a list of all the implicit defaults

All you see in the documentation is the "default".

https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

Sample (default) `kitty.conf` are also available at the bottom of the page.

**Comment by kovidgoyal** [comment]
On Thu, Apr 21, 2022 at 02:00:57AM -0700, BLucky wrote:
> > Sample (default) kitty.conf are also available at the bottom of the page.
> 
> I have checked the entirety of the sample kitty.conf and there was nothing.
> here is the only line starting with `mouse_map middle` in the sample conf:
> `mouse_map middle release ungrabbed paste_from_selection`

I have no clue what you are checking. the sample kitty.conf does have
all the defaults including paste.

> 
> where, as I have just checked and found out, `paste_from_selection` unintuitively pastes from clipboard, and is actually a duplicate action of `paste_from_clipboard`, even though both actions have their default keyboard shortcuts that are different. Also I commented that line out of the sample kitty.conf file just in case, thinking it would solve it and when it didn't, I considered it unrelated due to the misleading name.


paste_from_selection is not a duplicate of paste_from_clipbaord.
paste_from_selection will paste from primary selection if there is
something present there and from the clipboard otherwise.

> 
> > I tried the following and it worked fine.
> 
> Thanks, that one worked, tho I wish there was a better way to do it than having to check every event option and check every used mappable action in case the name is misleading in this case

You have to check nothing other than the section on mouse actions, to
change a mouse action.

**Comment by kovidgoyal** [comment]
On Thu, Apr 21, 2022 at 01:05:32AM -0700, BLucky wrote:
> > paying special attention to the difference between press and click events.
> 
> The docs don't specify the difference between events, only that they are separate events. I tried unmapping both press and click and it still pastes on middle click. 
> 
> It would be nice to see all the default shortcuts (as in those that are present even without a `kitty.conf`) since I checked all the `mouse_mod middle` lines in my `kitty.conf` and the ones I showed above are the only 3 lines

All the default shortcuts are present in the docs. The you want in
particular is https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Paste-from-the-primary-selection
