### ISSUE TITLE
Not working --cwd=current --type=tab  and new_tab_with_cwd 

### ISSUE THREAD

**Issue by guilhermeprokisch** [kovidgoyal/kitty#4996]
**Describe the bug**
Suddenly my configs for open tab and panes in current dir are not working. I updated the kitty these days (not sure if this could be related)

**To Reproduce**
All my configs that uses current cwd  options are not working anymore

map ctrl+alt+n new_tab_with_cwd (also tried change to map ctrl+alt+n launch --cwd=current --type=tab)
map ctrl+alt+, launch --location=hsplit --cwd=current
map ctrl+alt+/ launch --location=vsplit --cwd=current

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Darwin LionKing.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.2.1 BuildVersion:	21D62
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/guilherme/.config/kitty/kitty.conf
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control       y
background_opacity         0.9
bold_font                  Comic Code Ligatures Bold
bold_italic_font           Comic Code Ligatures Bold Italic
confirm_os_window_close    0
cursor                     None
dim_opacity                1.0
dynamic_background_opacity True
editor                     vim
enabled_layouts            ['splits:split_axis=horizontal']
font_family                Comic Code Ligatures
font_features:
{'FiraCode-Retina': ('+zero', '+onum')}
font_size                  19.0
hide_window_decorations    1
italic_font                Comic Code Ligatures Italic
listen_on                  /tmp/mykitty
macos_custom_beam_cursor   True
tab_bar_align              center
tab_bar_edge               1
tab_bar_margin_width       20.0
tab_bar_style              separator
tab_fade                   (0.95, 0.95, 0.95, 1.0)
tab_separator               ⋮ 
tab_title_template         {title.split('/')[-1].replace(" - - ", " - ").split(" - ")[-1].lower()}
window_margin_width        FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
window_padding_width       FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added shortcuts:
	shift+left → move_window left
	shift+right → move_window right
	shift+up → move_window up
	shift+down → move_window down
	ctrl+0 → set_background_opacity default
	ctrl+8 → set_background_opacity +0.25
	ctrl+9 → set_background_opacity -0.25
	ctrl+h → kitten pass_keys.py neighboring_window left   ctrl+h "^.* - nvim$"
	ctrl+j → kitten pass_keys.py neighboring_window bottom ctrl+j "^.* - nvim$"
	ctrl+k → kitten pass_keys.py neighboring_window top    ctrl+k "^.* - nvim$"
	ctrl+l → kitten pass_keys.py neighboring_window right  ctrl+l "^.* - nvim$"
	ctrl+opt+, → launch --location=hsplit --cwd=current
	ctrl+opt+/ → launch --location=vsplit --cwd=current
	ctrl+opt+0 → increase_background_opacity
	ctrl+opt+9 → decrease_background_opacity
	ctrl+opt+f → toggle_fullscreen
	ctrl+opt+h → previous_tab
	ctrl+opt+l → next_tab
	ctrl+opt+m → close_tab
	ctrl+opt+n → launch --cwd=current --type=tab
	ctrl+opt+r → set_tab_title
Changed shortcuts:
	cmd+k → send_text terminal,application \x63\x6C\x65\x61\x72\x0A
Colors:
	active_border_color        #c74545   
	active_tab_background      #f2e5bc   
	active_tab_foreground      #764e37   
	background                 #f2e5bc   
	color0                     #bdae93   
	color1                     #c74545   
	color10                    #6c782e   
	color11                    #b47109   
	color12                    #47747e   
	color13                    #945e80   
	color14                    #4c7a5d   
	color15                    #764e37   
	color2                     #6c782e   
	color3                     #c55b03   
	color4                     #47747e   
	color5                     #945e80   
	color6                     #4c7a5d   
	color7                     #764e37   
	color8                     #928374   
	color9                     #c74545   
	foreground                 #764e37   
	inactive_border_color      #bdae93   
	inactive_tab_background    #f2e5bc   
	inactive_tab_foreground    #7c6f64   
	selection_background       #764e37   
	selection_foreground       #f2e5bc   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.xYbnZ8wXZr/org.xquartz:0
	USER                                guilherme

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
> ... open tab and panes in current dir are not working ...

How does it "not work"?
Is the new tab not opened in the current path?
Does it "not work" when running other programs, or at a shell prompt?

I can't reproduce this.

```shell
kitty --config=NONE -o 'map f1 new_tab_with_cwd'
```

If you have tried the above command and the new tab still does not open in the current path, then you can try the following command.

```shell
kitty --config=NONE -o shell_integration=no-cwd -o 'map f1 new_tab_with_cwd'
```

@kovidgoyal 
I noticed that currently `*_with_cwd` or `launch --cwd=current` will not use the last reported cwd by default, is this expected?

Is the newly added `--cwd=last_reported` worth logging in the 0.25.0 changelog?

**Comment by kovidgoyal** [comment]
On Thu, Apr 21, 2022 at 07:00:35PM -0700, page-down wrote:
> @kovidgoyal 
> I noticed that currently `*_with_cwd` or `launch --cwd=current` will not use the last reported cwd by default, is this expected?

Yes, last_reported is not suitable as default for reasons I explained
before. Basically imagine running vim from a shell and doing cd in it.

> 
> Is the newly added `--cwd=last_reported` worth logging in the 0.25.0 changelog?

Feel free to send a PR

**Comment by kovidgoyal** [comment]
I cannot reproduce either.

**Comment by page-down** [comment]
> Yes, last_reported is not suitable as default for reasons I explained before.

I suspect that OP is unable to automatically enable shell integration for any reason, however some software outputs OSC 7 once in the window and exit and then gets stuck at this `reported_cwd` forever.

Since `reported_cwd` is never used by default, there is no such possibility.

So without more information, I can't think of anything else that might cause a problem.

**Comment by kovidgoyal** [comment]
Yup last_reported_cwd is used only if the cursor is currently sitting at a marked prompt or the user explicitly requested last_reported. See the cwd_of_child function in window.py

**Comment by page-down** [comment]
>>> ... currently `*_with_cwd` or `launch --cwd=current` will not use the last reported cwd by default ...
>>
>> Yes, last_reported is not suitable as default for reasons I explained before.
>
> ... last_reported_cwd is used only if the cursor is currently sitting at a marked prompt or ...

I would like to make sure I didn't misunderstand your idea.

I modified the shell integration script:

```fish
echo -en "\e]7;kitty-shell-cwd://$hostname/tmp\a"
```

Run the following command and press F1, which opens `$HOME` instead of `/tmp`, and this works as expected.

```shell
kitty --config=NONE -o shell_integration=enabled -o shell=fish -o 'map f1 new_window_with_cwd'
```

**Comment by page-down** [comment]
I tried the latest commit `714461d` and the above mentioned issue is fixed. So my assumption will be valid now.

```shell
kitty --config=NONE -o shell_integration=no-cwd -o 'map f1 new_tab_with_cwd'
```

If any program outputs OSC 7 once and exits, it will be stuck at `last_reported_cwd` forever, as sitting on the marked prompt.

```shell
echo -en "\e]7;kitty-shell-cwd://localhost/tmp\a"
```

There is no golden solution to this problem, so good luck to everyone who messes with this.
As a user, all you can do is try to use well-behaved programs (only).

Since we have `oldest`, maybe we could provide `newest` (the original `current` behavior) that skips `last_reported_cwd`, which users can use at their own when they are out of luck.

**Comment by kovidgoyal** [comment]
On Thu, Apr 21, 2022 at 08:29:41PM -0700, page-down wrote:
> I tried the latest commit `714461d` and the above mentioned issue is fixed. So my assumption will be valid now.
> 
> ```shell
> kitty --config=NONE -o shell_integration=no-cwd -o 'map f1 new_tab_with_cwd'
> ```
> 
> If any program outputs OSC 7 once and exits, it will be stuck at `last_reported_cwd` forever, as sitting on the marked prompt.

No it isnt. If the prompt is marked then it is marked by an integration
script, and the integration script updates the reported cwd.

**Comment by page-down** [comment]
> ... the integration script updates the reported cwd ...

You can see that this is explicitly turned off in my command above (with `no-cwd`).

It is also possible that some users are using other integrations (OSC 133) that are not included in the officially supported shell (CWD reporting has not been added), or have disabled automatic integration and checked the (old) shell integration script into Git and specified the path.

**Comment by kovidgoyal** [comment]
On Thu, Apr 21, 2022 at 08:51:57PM -0700, page-down wrote:
> > ... the integration script updates the reported cwd ...
> 
> You can see that this is explicitly turned off in my command above (with `no-cwd`).

Why would you turn it off and if you do, then either dont use OSC 7 (I
dont know of anything that natively uses it) or add it to your shell
yourself.

> 
> It is also possible that some users are using other integrations (OSC 133) that are not included in the officially supported shell (CWD reporting has not been added), or have disabled automatic integration and checked the (old) shell integration script into Git and specified the path.

Anything is possible. It's not our job to cater to every imaginable
scenario. Just likely ones.
