### ISSUE TITLE
Word corruption in weechat input bar

### ISSUE THREAD

**Issue by NetSysFire** [kovidgoyal/kitty#4999]
**Describe the bug**

When editing a word just at the point where weechat would scroll, the word will become messed up. This is not a weechat issue, I spoke with the devs and I could not reproduce this in another terminal, such as alacritty. This only happens in kitty.

**To Reproduce**

First of all, make sure `weechat.bar.input.size` is set to 1. Without that the input bar expands vertically and does not scroll horizontally, which does not trigger the bug. This is the only option you need to change in the default config of weechat.
I recorded a video of me reproducing this bug:

https://user-images.githubusercontent.com/59517351/164702455-84454efd-0ea7-4d90-8b14-30810b938242.mp4

You can see the weirdness there.

**Screenshots**

n/a

**Environment details**

```
kitty 0.24.2 created by Kovid Goyal
Linux archlinux 5.15.14-1-lts #1 SMP Tue, 11 Jan 2022 15:37:45 +0000 x86_64
archlinux /dev/tty (4 | 6)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.7
bell_on_tab                
cursor_shape               3
cursor_stop_blinking_after 10.0
cursor_underline_thickness 1.0
draw_minimal_borders       False
dynamic_background_opacity True
enable_audio_bell          False
font_family                Inconsolata
font_size                  12.0
mouse_hide_wait            1.0
shell_integration          frozenset({'disabled'})
strip_trailing_spaces      smart
term                       xterm-256color
window_alert_on_bell       False
window_border_width        (0, 'pt')
Added shortcuts:
	shift+page_up → scroll_page_up
	shift+page_down → scroll_page_down
	ctrl++ → change_font_size all +1.0
	ctrl+- → change_font_size all -1.0
	ctrl+0 → change_font_size all 0
Colors:
	color1                     #a80000   
	color10                    #9bc516   
	color11                    #ffce41   
	color12                    #83a598   
	color13                    #d3869b   
	color14                    #8ec07c   
	color15                    #ebdbb2   
	color2                     #6f920d   
	color3                     #f9c93f   
	color4                     #458588   
	color5                     #b16286   
	color6                     #689d6a   
	color7                     #a89984   
	color8                     #555753   
	color9                     #e80000   
	cursor                     #aaaaaa   

Environment variable names seen by the kitty process:
	DBUS_SESSION_BUS_ADDRESS
	DESKTOP_SESSION
	DISPLAY
	GDMSESSION
	GIO_LAUNCHED_DESKTOP_FILE
	GIO_LAUNCHED_DESKTOP_FILE_PID
	HOME
	LANG
	LOGNAME
	MAIL
	MOTD_SHOWN
	NO_AT_BRIDGE
	PATH
	PWD
	QT_PLATFORMTHEME
	QT_PLATFORM_PLUGIN
	QT_QPA_PLATFORMTHEME
	SHELL
	SHLVL
	SSH_AUTH_SOCK
	USER
	XAUTHORITY
	XCURSOR_THEME
	XDG_GREETER_DATA_DIR
	XDG_RUNTIME_DIR
	XDG_SEAT
	XDG_SEAT_PATH
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SESSION_ID
	XDG_SESSION_PATH
	XDG_SESSION_TYPE
	XDG_VTNR
```

**Additional context**

Config does not seem to be the issue here. I am able to reproduce this with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Sorry I am not going to debug weechat. You will need to provide more information about what the weechat devs think the bug is. What escape code are they sending and what are they expecting to happen that does not happen. If you can provide that information, I will be happy to look into it. Alternatively, you can run kitty with --dump-commands to produce a log file which can be replayed with --replay-commands. Produce that log file and post it along with the terminal size it was generated at and I will see if I can reproduce. If you do I will re-open
