### ISSUE TITLE
Changing window size makes content disappear

### ISSUE THREAD

**Issue by ecopoesis** [kovidgoyal/kitty#500]
On macOS with a partially transparent window, chaining the window size makes the contents of the window disappear while the window is being resized.

This only happens with `background_opacity` set to < 1.0.

macOS High Sierra 10.13.4 on a MacBook Pro (Retina, 15-inch, Mid 2015)

GIF of the bug: 
![changing_size_disappear](https://user-images.githubusercontent.com/1123109/39375313-ecdc4736-4a1b-11e8-9d76-f859265ec0b3.gif)

**Comment by kovidgoyal** [comment]
This is a limitation of glfw https://github.com/glfw/glfw/issues/1251
