### ISSUE TITLE
doc? bug

### ISSUE THREAD

**Issue by recal30404** [kovidgoyal/kitty#5006]
**Describe the bug**
https://sw.kovidgoyal.net/kitty/kittens/unicode_input/

Doc implies 2 ways for same results:

1. You can input unicode characters by name, hex code, recently used and even an editable favorites list. Press [ctrl+shift+u](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Unicode-input) to start the unicode input widget, shown below.

2. Command Line Interface
kitty +kitten unicode_input [options]

Problem is for choice 1, the unicode character is pasted to the terminal, but, for choice 2, there seems to be no pasting.

from main.py at /usr/lib64/kitty/kittens/unicode_input, the following code seems not to execute for choice 2:

@result_handler()
def handle_result(args: List[str], current_char: str, target_window_id: int, boss: BossType) -> None:
    w = boss.window_id_map.get(target_window_id)
    if w is not None:
        w.paste(current_char)

**To Reproduce**
1. ctrl+shift+u
2. select character
3. see it on your terminal.
4. kitty +kitten unicode_input 
5. no output pasted to terminal

**Environment details**
standard fedora linux environment

**Additional context**

this may be part of the design of kittens - ie, may need to map to a key to get the handle_result functionality.
maybe the handle_result is a work in progress?

Additional documentation defining the correct expectations may solve this issue, but, would be nice for both methods to paste the character to the terminal.

**Comment by page-down** [comment]
> ... for choice 2, there seems to be no pasting ...

This will be output in stdout, which is provided for use by scripts or other programs and will not be entered in the terminal window.

When using the shortcut, kitten will be executed in the terminal process, so it is possible to "paste" into any window.

**Comment by recal30404** [comment]
is it possible to run
kitty +kitten unicode_input
or some similar command line "in the terminal process" so that it would paste to a window ?

like the "source schellscript.sh" functionality instead of as you imply running the command line in a separate process ?

**Comment by page-down** [comment]
You can use remote control to execute kitten in the kitty process.

https://sw.kovidgoyal.net/kitty/remote-control/#kitty-kitten

```shell
kitty -o allow_remote_control=yes
```

```shell
kitty @ kitten unicode_input
```

You can also script the shell you are using to have the unicode_input kitten output inserted into the command line editor (this is where you type the commands in the shell).

**Comment by kovidgoyal** [comment]
The command line in question here is the command line you use in map
directives in kitty.conf. Some kittens are designed to run in an
existing session (such as icat or ssh) some in a new window such as
unicode_input or remote_files.
