### ISSUE TITLE
Disable confirm to quit dialog

### ISSUE THREAD

**Issue by parasbhanot** [kovidgoyal/kitty#5008]
Hi, 

I have recently updated the kitty now when i try to close kitty when some command is running it displays confirmation dialog which is annoying . so i want to disable this feature . 

So i want to know how to disable it .

**Comment by parasbhanot** [comment]
I get it now we just have add the following line in conf file .

confirm_os_window_close 0

**Comment by samox73** [comment]
`confirm_os_window_close 0` should really be the default behavior imo

**Comment by toonn** [comment]
Reading the docs you can also enable `shell_integration` with supported shells so windows that are sitting at a command prompt are not counted while windows with a running command are.

The documentation says this is an optional feature of `shell_integration` but I can't find a way to toggle this specific behavior.

**Comment by kovidgoyal** [comment]
It is on by default, as long as shell_integration is itself enabled,
which is also on by default.

**Comment by toonn** [comment]
@kovidgoyal, this phrasing, [found here](https://sw.kovidgoyal.net/kitty/shell-integration/#shell-integration):

> When confirming a quit command if a window is sitting at a shell prompt, it is optionally, not counted (see confirm_os_window_close)

Led me to believe it's possible to toggle that behavior independently from the other integrations.

**Comment by kovidgoyal** [comment]
Yes if you use positive numbers for confirm_os_window_close it wont use information about shell prompts. If you use negative numbers it will.  See the documentation of confirm_os_window_close

**Comment by toonn** [comment]
Ah, it must not've sunk in when reading that paragraph. Because that is where I found the link to the `shell_integration` page.

Maybe the bullet point on that page could mention the "optionally" refers to using positive or negative numbers?

**Comment by emilyzugel** [comment]
confirm_os_window_close 0 works for me
