### ISSUE TITLE
`new_tab/window_with_cwd` does not appear to open new tabs/windows in the same directory.

### ISSUE THREAD

**Issue by worthless443** [kovidgoyal/kitty#5011]
### Describe the bug
`new_tab/windwo_with_cwd` does not appear to open new tabs/windows in the same directory. 

**To Reproduce**
1. try appending the new binding to kitty.conf `tee -a ~/.config/kitty/kitty.conf <<<"map ctrl+shift+b new_tab_with_cwd"`.
2. relaunch kitty & set  `KITTY_CONFIG_DIRECTORY` to `~/.config/kitty/kitty.conf`.
3. try the new binding, `Ctrl+Alt+b` 
4. Not opening in the same dir

**Screenshots**

![image](https://i.imgur.com/M9CgNAv.png)

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux localhost 5.17.2-gentoo-x86_64 #1 SMP PREEMPT Wed Apr 20 16:11:43 IST 2022 x86_64

This is localhost.O (Linux x86_64 5.17.2-gentoo-x86_64) 02:28:26

DISTRIB_ID="Gentoo"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/aissy/.config/kitty/kitty.conf

Config options different from defaults:
Changed shortcuts:
	ctrl+shift+b → new_tab_with_cwd
	ctrl+shift+enter → new_window_with_cwd

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin
	LANG                                en_US.utf8
	EDITOR                              /bin/nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                aissy
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 i3
	XDG_SESSION_CLASS                   greeter
	XDG_VTNR                            7
	XDG_SESSION_ID                      c11
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I cannot reproduce

Steps:

1) kitty --config NONE -o 'map f1 new_tab_with_cwd'
2) cd /tmp
3) Press F1
4) new window in new tab opens with cwd set to /tmp
