### ISSUE TITLE
Themes don't save

### ISSUE THREAD

**Issue by lukepighetti** [kovidgoyal/kitty#5012]
I tried to use `kitty +kitten themes`, selecting Atom One Light, and then tapping `M` (also tried `P` then `M`), and the theme selection doesn't take. All new windows use the default theme.

-Kitty `0.25.0`
-macOS `12.2.1 (21D62)`

https://user-images.githubusercontent.com/666539/164998965-8a11b4f0-f919-47d2-949f-c787e82f9d16.mov

**Comment by kovidgoyal** [comment]
I cannot reproduce. Steps I tried:

1) Run kitty +kitten themes
2) Select Atom One Light
3) Press M
4) terminal color changes as expected
5) Press ctrl+shift+n to create a new window
6) new window is light colored, as expected

**Comment by lukepighetti** [comment]
This was installed with `brew`, maybe that's a contributing factor?

**Comment by kovidgoyal** [comment]
No idea, I dont support third party kitty builds. Use the official
binaries.

**Comment by SamuelWeese** [comment]
Found this while searching for solution, using official install through curl fixes brew install.
