### ISSUE TITLE
Key actions failing: ”invalid literal for int() with base 10: ''“

### ISSUE THREAD

**Issue by tylerbrostrom** [kovidgoyal/kitty#5017]
**Describe the bug**

Attempting key actions results in the following:

```
Key action failed

show_last_command_output
invalid literal for int() with base 10: ''

Press Enter to close
```

**To Reproduce**
1. `kitty --config=NONE`
2. debug config (`ctrl` + `shift` + `F6`)

1. `kitty --config=NONE`
2. show last command (`ctrl` + `shift` + `G`)

**Environment details**
|||
-- | --
| OS | MacOS 10.15.7 |
| shell | zsh |
| kitty version | 0.25.0 |

**Comment by kovidgoyal** [comment]
Does not reproduce for me with those steps. Look at the stderr of kitty
are any errors printed there.

**Comment by tylerbrostrom** [comment]
Yes, stderr shows the following:
```
[116 01:21:02.303915] WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation
```

**Comment by kovidgoyal** [comment]
This commit should print more info on stderr for this failure. https://github.com/kovidgoyal/kitty/commit/e80cd36237afae156f931cd004f442d2f848aa58

**Comment by tylerbrostrom** [comment]
FYI: this issue no longer occurs in 0.25.1
