### ISSUE TITLE
adjust_column_width support float

### ISSUE THREAD

**Issue by guolimin1995** [kovidgoyal/kitty#5018]
can support adjust_column_width to set 0.7(float).
int can be set for now.
thanks.

**Comment by kovidgoyal** [comment]
There is no such thing as a fractional pixel. Line heights have to be a
whole number of pixels.

**Comment by kovidgoyal** [comment]
On Tue, Apr 26, 2022 at 08:30:24AM -0700, page-down wrote:
> It seems to happen before reaching `to-c.h`, `adjust_line_height(...)`, `#define read_adjust(...)`.


That's coming from your shell. Quote it.
