### ISSUE TITLE
`env` items do not apply to kitty process itself, only its children

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#5033]
#469 continues to annoy, but a workaround is to launch kitty with `GLFW_IM_MODULE=ibus`.

Because I launch kitty multiple ways, I thought it'd be clever to include in its config:

```
env GLFW_IM_MODULE=ibus
```

This does not work, but if you launch kitty inside this new kitty, it does.

`env` items should apply to kitty too, either optionally or always.

**Comment by page-down** [comment]
Regarding env, the previous discussion:

https://github.com/kovidgoyal/kitty/issues/4324

> ... env items should apply to kitty too ...

In any case, I personally do not think it is appropriate to add options to change the behavior of `env`. At a minimum, a new config option is needed (e.g. `kitty_env`).

**Comment by kovidgoyal** [comment]
Not a fan of this idea. It means kitty has to start, parse the config
file, check if env is defined, then set that env and re-run itself. This
is a huge cost. GLFW_IM_MODULE is needed only byt he subset of people
that use ibus on x11, its not worth the tradeoff.

**Comment by ctrlcctrlv** [comment]
Disappointing, but https://github.com/kovidgoyal/kitty/issues/469#issuecomment-1113201384 expands the solution to the .desktop file case.
