### ISSUE TITLE
Mouse hiding doesn't work consistently on GNOME+Wayland

### ISSUE THREAD

**Issue by YorickPeterse** [kovidgoyal/kitty#5035]
**Describe the bug**

When `mouse_hide_wait` is set to `-1.0`, the mouse is never hidden (instead of the moment when you start typing). When set to a positive value, the mouse appears to only be hidden _if_:

1. The cursor was in such a position that when you start Kitty it's already within the window boundary (i.e. Kitty starts in the middle, and your cursor is also already in the middle)
2. You wait at least `mouse_hide_wait` seconds _after_ starting Kitty _before_ typing anything. If you type anything after starting Kitty right away, it appears mouse hiding never works until you close said Kitty instance

In addition, mouse hiding appears to stop working when you move the cursor out of the Kitty window, requiring a restart of Kitty to get it to work again.

This can be seen in the following recording:

https://user-images.githubusercontent.com/86065/165986103-d2f6d256-132d-45fe-8da8-8b24074c35ac.mp4

**To Reproduce**

I used this configuration:

```
font_family Source Code Pro
font_size 8
disable_ligatures always
placement_strategy top-left

cursor_blink_interval 0
mouse_hide_wait 1.0
```

The font settings aren't needed, and just make things a bit easier on the eyes.

In the recording I started Kitty through the GUI, but it behaves the same when started from another terminal (e.g. GNOME Terminal).

To reproduce the cases outlined in the recording:

1. Start Kitty such that the cursor is already within the window boundaries, then wait 1-2 seconds before doing anything. Observe how the mouse hides as expected
2. Start Kitty, but with the mouse in e.g. the top left corner. Move the mouse into the window, observe how no amount of waiting results in the mouse being hidden
3. Start Kitty with the cursor in the window boundaries (as step 1), then move the cursor out of it and back. Observe that again the cursor is never hidden from this point on

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux sharkie 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64
Arch Linux 5.17.4-arch1-1 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/yorickpeterse/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval 0.0
disable_ligatures     2
font_family           Source Code Pro
font_size             8.0
mouse_hide_wait       1.0
placement_strategy    top-left

Important environment variables seen by the kitty process:
	PATH                                /home/yorickpeterse/.rubies/ruby-2.7.5/bin:/home/yorickpeterse/bin:/home/yorickpeterse/.cargo/bin:/home/yorickpeterse/.local/bin:/home/yorickpeterse/.local/share/ivm/bin:/home/yorickpeterse/.local/share/ienv/bin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              /home/yorickpeterse/bin/nvim
	SHELL                               /usr/bin/fish
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                yorickpeterse
	XDG_MENU_PREFIX                     gnome-
	LC_MONETARY                         en_NL.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            en_NL.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      en_NL.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_NL.UTF-8
	XDG_DATA_DIRS                       /home/yorickpeterse/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	LC_NUMERIC                          en_NL.UTF-8
```

**Comment by kovidgoyal** [comment]
Aaaah Wayland! And GNOME! Warms my heart whenever I see these in a bug
report. 

Sarcasm aside, probably Wayland only allows applications to hide mouse
cursor when it is over one of their windows. The glfw Wayland backend
probably only sets the cursor state to hidden once and not again
everytime the mouse enters the window, because all the other backends
dont need this. I'll look into it when I have a moment, or in the
meantime patches welcome, it should be fairly trivial in wl_window.c and
wl_init.c

**Comment by YorickPeterse** [comment]
@kovidgoyal Thanks! It's indeed frustrating how GNOME/Wayland do things their own way, and not always necessarily a better way. If there's any extra details I can provide please let me know :smiley:

**Comment by YorickPeterse** [comment]
As a poor man's debugger, I added this:

```diff
diff --git a/glfw/wl_window.c b/glfw/wl_window.c
index 71ec777a..0e2ac6ad 100644
--- a/glfw/wl_window.c
+++ b/glfw/wl_window.c
@@ -1408,6 +1408,7 @@ static bool isPointerLocked(_GLFWwindow* window)

 void _glfwPlatformSetCursor(_GLFWwindow* window, _GLFWcursor* cursor)
 {
+    debug("cursor mode: %i\n", window->cursorMode);
     if (!_glfw.wl.pointer)
         return;

```

This reveals the following: when you move the cursor out of the window, it seems Kitty still tries to toggle the cursor state to hidden. But since the cursor is not in the window boundaries, this isn't applied (I guess that's a Wayland thing so random applications can't hide an out of focus mouse pointer).

When you move the cursor back into the window, it seems the state sort of gets messed up. That is, the first time you move the cursor out of the window and back, it remains present. To "fix" this it seems I have to move the cursor out and back in again, though it's a bit tricky to reproduce properly.

I also noticed that when you move the mouse into the window, it appears to set the state to `GLFW_CURSOR_NORMAL` twice. For example, if I start Kitty with the cursor somewhere in the corner and move it into the window, the debug output is as follows:

```
cursor mode: 212993
cursor mode: 212993
cursor mode: 212994
cursor mode: 212993
cursor mode: 212993
```

**Comment by YorickPeterse** [comment]
Maybe not related (or maybe it is): but I also noticed that if the mouse is hidden, it doesn't show up again until you move the mouse out of the window. If you keep it in the window you can move it all you want, but it doesn't show up again.

**Comment by tru0067** [comment]
I think also related (I was going to create a separate issue but I'll wait and see if this fixes it). On Wayland + Sway, when full-screening a window the system's cursor sometimes toggles from the I beam to the pointer. This disables scrolling with trackpad gesture until the cursor is moved (and becomes the I beam again). This behavior is dependent on the cursor's position when the full-screen is performed.

More than happy to more fully investigate this behavior and create a proper issue with a MWE if they turn out to be unrelated.

**Comment by kovidgoyal** [comment]
As far as I can tell this is *yet another* bug in mutter. Easily
demonstrated by the following. Apply this patch:

```patch

diff --git a/glfw/wl_init.c b/glfw/wl_init.c
index 7f91e4e1..c8caa577 100644
--- a/glfw/wl_init.c
+++ b/glfw/wl_init.c
@@ -147,6 +147,7 @@ static void setCursor(GLFWCursorShape shape, _GLFWwindow* window)
     buffer = wl_cursor_image_get_buffer(image);
     if (!buffer)
         return;
+    printf("Calling wl_pointer_set_cursor with surface: %p\n", (void*)surface);
     wl_pointer_set_cursor(_glfw.wl.pointer, _glfw.wl.serial,
                           surface,
                           image->hotspot_x / scale,
diff --git a/glfw/wl_window.c b/glfw/wl_window.c
index 71ec777a..182544d7 100644
--- a/glfw/wl_window.c
+++ b/glfw/wl_window.c
@@ -147,6 +147,7 @@ setCursorImage(_GLFWwindow* window, bool on_theme_change) {
         cursorWayland->yhot = image->hotspot_y;
     }
 
+    printf("Calling wl_pointer_set_cursor with %p\n", (void*)surface);
     wl_pointer_set_cursor(_glfw.wl.pointer, _glfw.wl.serial,
                           surface,
                           cursorWayland->xhot / scale,
@@ -1397,6 +1398,7 @@ static void lockPointer(_GLFWwindow* window)
     window->wl.pointerLock.relativePointer = relativePointer;
     window->wl.pointerLock.lockedPointer = lockedPointer;
 
+    printf("Calling wl_pointer_set_cursor with NULL\n");
     wl_pointer_set_cursor(_glfw.wl.pointer, _glfw.wl.serial,
                           NULL, 0, 0);
 }
@@ -1408,6 +1410,7 @@ static bool isPointerLocked(_GLFWwindow* window)
 
 void _glfwPlatformSetCursor(_GLFWwindow* window, _GLFWcursor* cursor)
 {
+    printf("111111111 _glfwPlatformSetCursor hidden: %d\n", window->cursorMode == GLFW_CURSOR_HIDDEN);
     if (!_glfw.wl.pointer)
         return;
 
@@ -1417,6 +1420,7 @@ void _glfwPlatformSetCursor(_GLFWwindow* window, _GLFWcursor* cursor)
     // the next time the pointer enters the window the cursor will change
     if (window != _glfw.wl.pointerFocus || window->wl.decorations.focus != CENTRAL_WINDOW)
         return;
+    printf("22222222\n");
 
     // Unlock possible pointer lock if no longer disabled.
     if (window->cursorMode != GLFW_CURSOR_DISABLED && isPointerLocked(window))
@@ -1433,6 +1437,7 @@ void _glfwPlatformSetCursor(_GLFWwindow* window, _GLFWcursor* cursor)
     }
     else if (window->cursorMode == GLFW_CURSOR_HIDDEN)
     {
+        printf("Calling wl_pointer_set_cursor with NULL\n");
         wl_pointer_set_cursor(_glfw.wl.pointer, _glfw.wl.serial, NULL, 0, 0);
     }
 }
```

this prints out whenever kitty calls wl_pointer_set_cursor(). Now run

```
make debug && kitty -o mouse_hide_wait=-1
```

move the mouse over the new kitty window. Start typing, you will see
that the last call from kitty to wl_pointer_set_cursor() is with NULL
but the pointer remains visible, showing that mutter ignored the
request.

I suppose one could workaround it by using a 1x1 transparent pixel
pointer image, but I have worked around enough GNOME bugs that I am
not particularly motivated to do so. Report it to mutter and pray that
they either fix their bug or tell you why mutter is ignoring the hide
request and what we can do to prevent it from doing so.

**Comment by kovidgoyal** [comment]
@tru0067 your issue doesnt have anything to do with this. For one thing in wayland land every bug is compositor specific and for another mouse cursor shape has nothing to do with whether scroll events are processed or not. Your issue seems like the compositor is not keeping focus to the full screen window after the transition. But I will need a proper reproducer to confirm.

**Comment by kovidgoyal** [comment]
With my latest commit, you dont need the patch, just

make debug && kitty --debug-rendering -o mouse_hide_wait=-1

**Comment by YorickPeterse** [comment]
@kovidgoyal Thanks for looking into this :smiley: , too bad this is an issue in Mutter. I'll see if there's another way around this, or if maybe there's already an existing Mutter/Gnome issue for this somewhere.

**Comment by tru0067** [comment]
@kovidgoyal Thanks for the info! I'll continue to investigate the issue. I had thought it may be that the full-screened window is not being focused, but I haven't been able to reproduce it consistently. Thanks again!

**Comment by sabah1994** [comment]
I have exact same issue and I am on Ubuntu
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

Has this been addressed?
