### ISSUE TITLE
Get display position of current cursor

### ISSUE THREAD

**Issue by yingzhu146** [kovidgoyal/kitty#5038]
`kitty @ get-text --match "id:$KITTY_WINDOW_ID"   --add-cursor` returns the ansi code of the current cursor position.
How does one go about translating that into a pixel position? I want to generate a webview at the current cursor position as a hack to display svg/html 

Thanks a ton - and sorry if this is the wrong place for questions - the discussion categories didn't seem the right place either

**Comment by kovidgoyal** [comment]
Discussions is the appropriate place. And you cant convert the output of
get_text to a pixel position. If you want cursor position, you use the
escape code to query for it (a bit of googling will tell you what that
escape code is) and then you use the TIOGWINSZ ioctl to get the geometry
of the terminal window and use that to convert the answer from the
escape code which will be in terms of cells into pixels.

**Comment by yingzhu146** [comment]
these pointers are much appreciated and saved me and whoever comes to this issue hours - so thank you - and thanks for kitty!
