### ISSUE TITLE
P@kitty-cmd suddenly appears after command

### ISSUE THREAD

**Issue by ImALoooserOk** [kovidgoyal/kitty#5045]
**Describe the bug**
`P@kitty-cmd{"ok": false, "error": "Remote control is disabled. Add allow_remote_control to your kitty.conf"} ` suddenly appears after using a command

**To Reproduce**
1. open zsh on kitty
2. use `wpg -m` (wpgtk)
3. `P@kitty-cmd{"ok": false, "error": "Remote control is disabled. Add allow_remote_control to your kitty.conf"}` appears

**Screenshots**
with my config
![image](https://user-images.githubusercontent.com/63460105/166140896-da98b17b-6292-46c3-b485-9504609d9222.png)

with `--config NONE`
![image](https://user-images.githubusercontent.com/63460105/166141361-a6821bb4-02ac-410b-82d8-eff99112dcef.png)

**Environment details**
control + shift + f6 doesn't work for me for whatever reason, but I'm on Arch, dwm, with `kitty-0.25.0-1` installed with pacman

**Additional context**
the `P@kitty-cmd{"ok": false, "error": "Remote control is disabled. Add allow_remote_control to your kitty.conf"} ` doesn't always appear, only sometimes

**Comment by kovidgoyal** [comment]
That will be because  wpg (whatever that is) is running a kitty remote control command. And you have not enabled remote control in kitty.conf. So either stop wpg from doing that or turn on remote control

**Comment by ImALoooserOk** [comment]
i see, thanks for the help!
