### ISSUE TITLE
Vertically align content to top instead of center

### ISSUE THREAD

**Issue by frangio** [kovidgoyal/kitty#505]
As reported in #416, when the window height is not a multiple of cell height the content is centered veritcally, and thus produces a row of empty pixels at the top and bottom.

I think it would be better if it were aligned to the top, and the empty pixels were all at the bottom. This seems to be how other terminals handle this.

**Comment by kovidgoyal** [comment]
I prefer it aligned in the center. That said, I wont refuse a PR for an option to change its alignment, but it is not something I am interested in implementing myself.

**Comment by frangio** [comment]
Got it. Would you be able to point out where I'd need to look if I wanted to implement this?

**Comment by kovidgoyal** [comment]
IIRC layout.py

**Comment by dylan-chong** [comment]
It would be good if there was an option to configure aligning to top or centre

**Comment by dylan-chong** [comment]
iterm2 aligns to the top. I definitely think it looks better, because every non terminal window will align to the top. The user is more likely to look at the top of the screen than the bottom of the screen anyway. Aligning to the centre looks very very strange

<img width="840" alt="screen shot 2018-08-19 at 3 50 57 pm" src="https://user-images.githubusercontent.com/17482349/44305269-c0025d80-a3c7-11e8-8ec2-5d7fb9267841.png">

**Comment by copy** [comment]
Here's a patch that removes the padding from the top and left:

```diff
diff --git a/kitty/layout.py b/kitty/layout.py
index cf6c1a16..b93f5c79 100644
--- a/kitty/layout.py
+++ b/kitty/layout.py
@@ -85,8 +85,8 @@ def window_geometry(xstart, xnum, ystart, ynum):
 
 
 def layout_single_window(xdecoration_pairs, ydecoration_pairs):
-    xstart, xnum = next(layout_dimension(central.left, central.width, cell_width, xdecoration_pairs))
-    ystart, ynum = next(layout_dimension(central.top, central.height, cell_height, ydecoration_pairs))
+    xstart, xnum = next(layout_dimension(central.left, central.width, cell_width, xdecoration_pairs, left_align=True))
+    ystart, ynum = next(layout_dimension(central.top, central.height, cell_height, ydecoration_pairs, left_align=True))
     return window_geometry(xstart, xnum, ystart, ynum)
 
```

**Comment by dylan-chong** [comment]
@copy Thanks for investigating this! Could you submit a pr? I think it is a bit too inconvenient for most people to sort out compiling the terminal from source
