### ISSUE TITLE
Attach to running kitty over SSH

### ISSUE THREAD

**Issue by rosejn** [kovidgoyal/kitty#5053]
**Is your feature request related to a problem? Please describe.**
I've got a software development project with nvim and a set of live builds active on a home desktop, and I'd like to be able to SSH into this machine from a laptop and continue working.  I've seen Kovid mention that kitty removes the need for TMUX, so I'm thinking maybe this is possible already, or it could be?

**Describe the solution you'd like**
Ideally I could ssh to my home machine, and then do something like "kitty --attach" to attach to the kitty terminal session already running on that machine.  (Also using kitty on my laptop.)

**Describe alternatives you've considered**
tmux

**Comment by kovidgoyal** [comment]
remote persistence is the only use case of tmux that kitty does not
currently cover. See #391
