### ISSUE TITLE
ssh-kitten: remote kitty is not executable

### ISSUE THREAD

**Issue by purpleKarrot** [kovidgoyal/kitty#5055]
I have `remote_kitty if-needed` in `~/.config/kitty/ssh.conf`.
When I ssh into a remote host with ` kitty +kitten ssh ...`, the value `~/.local/share/kitty-ssh-kitten/kitty/bin` is in the $PATH. This directory exists and contains a script called `kitty`. However, this script is not executable.

When I make it executable with `chmod +x`, I can run it:
```
$ kitty --version
~/.local/share/kitty-ssh-kitten/kitty/bin/kitty: 27: [: 0: unexpected operator
[124 07:18:57.415110] Failed to set locale with LANG: en_US.UTF-8
kitty 0.25.0 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
dup of #5025
