### ISSUE TITLE
Remote File Transfer broken when using ProxyJump

### ISSUE THREAD

**Issue by PeterStolz** [kovidgoyal/kitty#5058]
**Describe the bug**
[Remote file transfer](https://sw.kovidgoyal.net/kitty/kittens/transfer/) over ssh does not work when using the `ProxyJump` ssh option.
The prompt after pressing the hyperlink says:
```
Could not handle remote file

No SSH connection data found in: {args}
```
**To Reproduce**
1. ssh _user_@_host_  -o ProxyJump=_proxyssh_    
 or simply add the line ProxyJump _proxyssh_ to ypur ssh config
3. ls --hyperlink=auto
4. click on a file
5. See error

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

kitty 0.24.2 created by Kovid Goyal
Linux P14 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64
Ubuntu 20.04.4 LTS P14 /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/peter/.local/kitty.app/bin/kitty
  base dir: /home/peter/.local/kitty.app/lib/kitty
  extensions dir: /home/peter/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/peter/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.9
update_check_interval 0.0
Added shortcuts:
	alt+h → neighboring_window left
	alt+j → neighboring_window down
	alt+k → move_window up
	alt+l → move_window right
	ctrl+home → resize_window reset
	ctrl+f2 → detach_window
	ctrl+f3 → detach_window new-tab
	ctrl+f4 → detach_window tab-prev
	ctrl+f10 → detach_window tab-left
	ctrl+f11 → detach_window tab-right
	ctrl+alt+left → resize_window narrower
	ctrl+alt+right → resize_window wider
	ctrl+alt+up → resize_window taller
	ctrl+alt+down → resize_window shorter

Environment variable names seen by the kitty process:
	DBUS_SESSION_BUS_ADDRESS
	DESKTOP_SESSION
	DISPLAY
	GDMSESSION
	GPG_AGENT_INFO
	GTK_MODULES
	HOME
	KDED_STARTED_BY_KDEINIT
	KDE_FULL_SESSION
	KDE_SESSION_UID
	KDE_SESSION_VERSION
	LANG
	LC_ADDRESS
	LC_IDENTIFICATION
	LC_MEASUREMENT
	LC_MONETARY
	LC_NAME
	LC_NUMERIC
	LC_PAPER
	LC_TELEPHONE
	LC_TIME
	LIBVIRT_DEFAULT_URI
	LOGNAME
	PATH
	PWD
	QT_ACCESSIBILITY
	QT_AUTO_SCREEN_SCALE_FACTOR
	SESSION_MANAGER
	SHELL
	SHLVL
	SSH_AGENT_PID
	SSH_AUTH_SOCK
	SSL_CERT_FILE
	USER
	USERNAME
	WINDOWPATH
	XAUTHORITY
	XCURSOR_THEME
	XDG_CONFIG_DIRS
	XDG_CURRENT_DESKTOP
	XDG_DATA_DIRS
	XDG_RUNTIME_DIR
	XDG_SEAT
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SESSION_ID
	XDG_SESSION_TYPE
	XDG_VTNR

```

**Comment by cdelledonne** [comment]
> It's on my todo list to re-write this
kitten so it works with the new ssh kitten which will make it work with
proxyjump transparently and make it faster.

Has this been done actually? I'm facing the same problem as the OP, running kitty 0.26.5 and using the SSH kitten.

The [remote files documentation](https://sw.kovidgoyal.net/kitty/kittens/remote_file/) claims that

> For best results, use this kitten with the [ssh kitten](https://sw.kovidgoyal.net/kitty/kittens/ssh/). Otherwise, nested SSH sessions are not supported.

which seems to suggest that nested SSH sessions *are* supported when using the SSH kitten. However the next sentence in the documentation says

> The kitten will always try to copy remote files from the first SSH host. This is because, without the ssh kitten, there is no way for kitty to detect and follow a nested SSH session robustly.

which to me is confusing with respect to the previous sentence. What's the status of things? What is the documentation trying to suggest?

Looking at the code in [`Window.handle_remote_file()`](https://github.com/kovidgoyal/kitty/blob/e4baca6d97178a1d8b12858e1e95af0966fc576a/kitty/window.py#L984), it seems that `ssh_cmdline` is extracted from the foreground process with the *highest PID* (line 992 at the link above). However, when I run the SSH kitten, the sorted list of foreground processes looks something like the following:
1. The lowest PID is the one of the kitten command run by the user
    ```python
    {'pid': 420801, 'cmdline': ['kitty', '+kitten', 'ssh', '<end_host>'], 'cwd': ...}
    ```
2. Then there's the process that instantiates the connection to the end host (I guess spawned by the kitten?)
    ```python
    {'pid': 420804, 'cmdline': ['/usr/bin/ssh', '-t', ..., '--', '<end_host>', ...}
    ```
3. The highest PID is the one that instantiates the connection to the jump server
    ```python
    {'pid': 420805, 'cmdline': ['/usr/bin/ssh', '-W', '[<end_host>]:<port>', '<jump_host>'], 'cwd': ...}
    ```

The next `if` test (line 993 at the link above) checks if `'ControlPath=' in ' '.join(ssh_cmdline)`, which I guess is never true, given that the cmdline is the one at point 3. above.

Am I misinterpreting something?

**Comment by kovidgoyal** [comment]
On Mon, Apr 17, 2023 at 08:54:18AM -0700, cdelledonne wrote:
> > It's on my todo list to re-write this
> kitten so it works with the new ssh kitten which will make it work with
> proxyjump transparently and make it faster.
> 
> Has this been done actually? I'm facing the same problem as the OP, running kitty 0.26.5 and using the SSH kitten.

Don't recall, nowadays I use the transfer kitten myself rather than the
remote files kitten. So I doubt I ever got around to doing this. Look at
the git log for the kitten folder should tell you.

> 
> The [remote files documentation](https://sw.kovidgoyal.net/kitty/kittens/remote_file/) claims that
> 
> > For best results, use this kitten with the [ssh kitten](https://sw.kovidgoyal.net/kitty/kittens/ssh/). Otherwise, nested SSH sessions are not supported.
> 
> which seems to suggest that nested SSH sessions *are* supported when using the SSH kitten. However the next sentence in the documentation says

jump proxies and nested ssh are different. Jump proxies use -J nested
ssh means run ssh on the intermediate machine after logging into the
intermediate machine normally.

> 
> > The kitten will always try to copy remote files from the first SSH host. This is because, without the ssh kitten, there is no way for kitty to detect and follow a nested SSH session robustly.
> 
> which to me is confusing with respect to the previous sentence. What's the status of things? What is the documentation trying to suggest?
> 
> Looking at the code in [`Window.handle_remote_file()`](https://github.com/kovidgoyal/kitty/blob/e4baca6d97178a1d8b12858e1e95af0966fc576a/kitty/window.py#L984), it seems that `ssh_cmdline` is extracted from the foreground process with the *highest PID* (line 992 at the link above). However, when I run the SSH kitten, the sorted list of foreground processes looks something like the following:
> 1. The lowest PID is the one of the kitten command run by the user
>     ```python
>     {'pid': 420801, 'cmdline': ['kitty', '+kitten', 'ssh', '<end_host>'], 'cwd': ...}
>     ```
> 2. Then there's the process that instantiates the connection to the end host (I guess spawned by the kitten?)
>     ```python
>     {'pid': 420804, 'cmdline': ['/usr/bin/ssh', '-t', ..., '--', '<end_host>', ...}
>     ```
> 3. The highest PID is the one that instantiates the connection to the jump server
>     ```python
>     {'pid': 420805, 'cmdline': ['/usr/bin/ssh', '-W', '[<end_host>]:<port>', '<jump_host>'], 'cwd': ...}
>     ```
> 
> The next `if` test (line 993 at the link above) checks if `'ControlPath=' in ' '.join(ssh_cmdline)`, which I guess is never true, given that the cmdline is the one at point 3. above.
> 
> Am I misinterpreting something?

In that case it isnt using the ssh kitten. The nice thing about the ssh
kitten is that the remote files kitten (assuming it is rewritten to work
with it) can reuse the ControlMaster of the ssh kitten so it doesnt need
to establish its own connection. It can just piggyback (multiplex) on
the connection established by the ssh kitten.
