### ISSUE TITLE
/home/ketan/.local/kitty.app/bin/kitty: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)

### ISSUE THREAD

**Issue by ket000** [kovidgoyal/kitty#5059]
Trying to Start Kitty on Oracle Linux 7.9 aka Red Hat Linux 7.9 gives below

/home/abc/.local/kitty.app/bin/kitty: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/abc/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)
/home/abc/.local/kitty.app/bin/kitty: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /home/abc/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)
/home/abc/.local/kitty.app/bin/kitty: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/abc/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)

It seems that GLIBC_2.27 is missing. 

ldd ~/.local/kitty.app/bin/../lib/libpython3.9.so.1.0
/home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)
/home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)
/home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/ketan/.local/kitty.app/bin/../lib/libpython3.9.so.1.0)
        linux-vdso.so.1 =>  (0x00007ffff9abd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2796e40000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2796c30000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f2796a10000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2796700000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2796330000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2797800000)

**Comment by kovidgoyal** [comment]
kitty does not bundle libc you need a system with a new enough version
of glibc to run the binaries. If you dont have sucha  system, you can
always build from source: https://sw.kovidgoyal.net/kitty/build/
