### ISSUE TITLE
Failure to build Kitty From Source on Oracle Linux 7.9 WSL Windows sub system for Linux

### ISSUE THREAD

**Issue by ket000** [kovidgoyal/kitty#5062]
After I downloaded all the required dependencies including Python 3.7 that is required running make gives below error.

 make
python3 setup.py
CC: ['gcc'] (4, 8)
wayland-protocols >= 1.17 is required, found version: 1.14
Disabling building of wayland backend
[24/64] Compiling kitty/charsets.c ... done
Compiling kitty/unicode-data.c ...
gcc -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=25 -DXT_VERSION="0.25.0" -Wextra -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -Wno-missing-braces -pipe -march=native -fvisibility=hidden -D_FORTIFY_SOURCE=2 -fPIC -flto -DKITTY_HAS_RS_SIG_ARGS -pthread -I/usr/include/libpng15 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/local/include/python3.7m -c kitty/unicode-data.c -o build/fast_data_types-unicode-data.c.o
In file included from kitty/unicode-data.c:3:0:
kitty/data-types.h:145:9: error: type of bit-field ‘width’ is a GCC extension [-Wpedantic]
         uint16_t width : 2;
         ^
kitty/data-types.h:146:9: error: type of bit-field ‘decoration’ is a GCC extension [-Wpedantic]
         uint16_t decoration : 3;
         ^
kitty/data-types.h:147:9: error: type of bit-field ‘bold’ is a GCC extension [-Wpedantic]
         uint16_t bold : 1;
         ^
kitty/data-types.h:148:9: error: type of bit-field ‘italic’ is a GCC extension [-Wpedantic]
         uint16_t italic : 1;
         ^
kitty/data-types.h:149:9: error: type of bit-field ‘reverse’ is a GCC extension [-Wpedantic]
         uint16_t reverse : 1;
         ^
kitty/data-types.h:150:9: error: type of bit-field ‘strike’ is a GCC extension [-Wpedantic]
         uint16_t strike : 1;
         ^
kitty/data-types.h:151:9: error: type of bit-field ‘dim’ is a GCC extension [-Wpedantic]
         uint16_t dim : 1;
         ^
kitty/data-types.h:152:9: error: type of bit-field ‘mark’ is a GCC extension [-Wpedantic]
         uint16_t mark : 2;
         ^
kitty/data-types.h:179:9: error: type of bit-field ‘continued’ is a GCC extension [-Wpedantic]
         uint8_t continued : 1;
         ^
kitty/data-types.h:180:9: error: type of bit-field ‘has_dirty_text’ is a GCC extension [-Wpedantic]
         uint8_t has_dirty_text : 1;
         ^
kitty/data-types.h:181:9: error: type of bit-field ‘prompt_kind’ is a GCC extension [-Wpedantic]
         PromptKind prompt_kind : 2;
         ^
kitty/data-types.h:260:9: error: type of bit-field ‘type’ is a GCC extension [-Wpedantic]
         DynamicColorType type: 8;
         ^
make: *** [all] Error 1

**Comment by kovidgoyal** [comment]
Your version of gcc is probably too old. You can likely work around it
by removing -Wpedantic from setup.py

**Comment by ket000** [comment]
I searched for -Wpedantic in setup.py

grep -n -i pedantic setup.py

333:    werror = '' if ignore_compiler_warnings else '-pedantic-errors -Werror'
711:    unsafe = {'-pthread', '-Werror', '-pedantic-errors'}
835:    werror = '' if args.ignore_compiler_warnings else '-pedantic-errors -Werror'

But I could not find it.

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by kovidgoyal** [comment]
Its -pedantic-errors

**Comment by ket000** [comment]
I changed lines as below
333
    werror = '' 
    # if ignore_compiler_warnings else '-Werror'

Line 835
    werror = '' 
    # if args.ignore_compiler_warnings else '-Werror'

now getting below

[45/71] Compiling kitty/ringbuf.c ... done
Compiling kitty/disk-cache.c ...
gcc -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=25 -DXT_VERSION="0.25.0" -Wextra -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -O3 -fwrapv -fstack-protector-strong -Wno-missing-braces -pipe -march=native -fvisibility=hidden -D_FORTIFY_SOURCE=2 -fPIC -flto -DKITTY_HAS_RS_SIG_ARGS -pthread -I/usr/include/libpng15 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/local/include/python3.7m -c kitty/disk-cache.c -o build/fast_data_types-disk-cache.c.o
In file included from kitty/disk-cache.c:16:0:
kitty/cross-platform-random.h:13:18: error: missing binary operator before token "("
 #if __has_include(<sys/random.h>)
                  ^
make: *** [all] Error 1

**Comment by kovidgoyal** [comment]
You are going to needed a newer compiler.
