### ISSUE TITLE
Kitty not starting after upgrading to Ubuntu 22.04

### ISSUE THREAD

**Issue by VariabileAleatoria** [kovidgoyal/kitty#5063]
After the dist upgrade to the latest LTS of Ubuntu this is what I get trying to run kitty

```
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a 
[126 19:41:10.815348] [glfw error 65544]: Wayland: fatal display error: Protocol error
```
Let me know how I can provide more significant infos for the issue

**Comment by kovidgoyal** [comment]
Post the information asked for in the issue template. And what wayland
compositor you are running. If by chance it is GNOME, then this issue is
caused by a bug in mutter the GNOME compsitor. Set linux_display_backend
to x11 in kitty.conf and you will be fine.

**Comment by VariabileAleatoria** [comment]
I'm sorry but the issue template says to press Ctrl+Shift+F6 in kitty, but if it doesn't run it's a bit of an issue :)
By the way yes, I'm running GNOME in Wayland.
For those having the same issue the config key to set is `linux_display_server`
