### ISSUE TITLE
Wrong output in pager command ouptut

### ISSUE THREAD

**Issue by nadapez** [kovidgoyal/kitty#5066]
**Describe the bug**
When showing command output in pager some  strange code appears in the text.

**To Reproduce**
1. open kitty window
2. type in `echo hello`
3. press ctrl+shift+g
What shows up is:
> 133;Chello

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux bd 5.10.57-antix.1-amd64-smp #1 SMP PREEMPT Sun Aug 8 11:11:51 EEST 2021 x86_64
Welcome to antiX. Powered by Debian.
PRETTY_NAME="antiX-21 Grup Yorum"
DISTRIB_ID=antiX
DISTRIB_RELEASE=21
DISTRIB_CODENAME=bullseye
DISTRIB_DESCRIPTION="antiX 21"
Running under: X11
Frozen: True
Paths:
  kitty: /home/np/.local/kitty.app/bin/kitty
  base dir: /home/np/.local/kitty.app/lib/kitty
  extensions dir: /home/np/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/np/.local/kitty.app/bin:/usr/local/bin:/usr/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/home/np/.local/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0.0
	USER                                np
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_CACHE_HOME                      /home/np/.cache
	XDG_DOCUMENTS_DIR                   /home/np/Documents
	XDG_VIDEOS_DIR                      /home/np/Videos
	XDG_STATE_HOME                      /home/np/.local/state
	XDG_DESKTOP_DIR                     /home/np/Desktop
	XDG_MUSIC_DIR                       /home/np/Music
	XDG_SESSION_CLASS                   greeter
	XDG_SESSION_ID                      1
	XDG_PICTURES_DIR                    /home/np/Pictures
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 icewm
	XDG_DATA_HOME                       /home/np/.local/share
	XDG_CONFIG_HOME                     /home/np/.config
	XDG_VTNR                            7
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_DATA_DIRS                       /usr/local/share/:/usr/share/
	XDG_DOWNLOAD_DIR                    /home/np/Downloads

```

**Additional context**
My operative system is **antiX 21 "Grup Yorum"**
I installed kitty with the installer script.

**Comment by kovidgoyal** [comment]
Whatever pager you are using does not have support for OSC control
sequences. Use an up-to-date version of less as pager.

**Comment by nadapez** [comment]
My less version is updated. (version) 
```
$ apt policy less
less:
  Installed: 551-2
  Candidate: 551-2
  Version table:
     590-1~bpo11+1 100
        100 http://deb.debian.org/debian bullseye-backports/main amd64 Packages
 *** 551-2 500
        500 http://ftp.de.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

Also I can get working hyperlinks in less, but only if using `-r` flag. For example:
`echo -e "\e]8;;https://hola.com\e\\hola"|less -r`

**Comment by nadapez** [comment]
Ok, I  fixed it! 

The less command needed the `--raw-control-chars`  flag.


The less command line made by kitty have the upper case version `--RAW-CONTROL-CHARS` which holds only for ANSI codes.
I guess in the source code it should be changed for the lower case version which holds for any escape code.

Temporary solution:  put a fake `less` command in in the path with this content:

```
#/usr/bin/sh
/usr/bin/less "$@" --raw-control-chars
```
Tried with an alias but didn't work. I guess kitty use `command`

**Comment by kovidgoyal** [comment]
--RAW-CONTROL-CHARS also ignores OSC hyperlink codes in new enough less.
--raw-control-chars is not recommended.

echo -e "a\e]133;C\e\\b" | less -R

works fine with less version 590

And if you want to change the command kitty uses simply change the value
of scrollback_pager in kitty.conf
