### ISSUE TITLE
Graphical problems with vim if vimrc is set to maximize windows

### ISSUE THREAD

**Issue by raffaem** [kovidgoyal/kitty#5070]
**Describe the bug**

If `.vimrc` contains certain lines supposed to maximize the vim windows (see
"Additional context"), it
will result in graphical problems when running `vim` inside a kitty instance.

For example, this is how a part ofthe bottom of `.bashrc` is displayed by vim
running inside kitty: see Screenshot 1.

And this is how it's displayed by gvim: see Screenshot 2.

Other problems include not being able to go to the start of the file: `gg`
will go below the start of the file.

**To Reproduce**
1. Put the lines in "Additional context" in `.vimrc`
2. Open a file with vim, ex. `vim .bashrc`

**Screenshots**
 Screenshot 1
![vim_kitty](https://user-images.githubusercontent.com/54762742/167299447-32de6fa7-fc27-4d06-bd87-4dc7ef20453b.png)

Screenshot 2
![gvim](https://user-images.githubusercontent.com/54762742/167299455-d0c02845-1dd6-4b85-b4ef-a897f500bf39.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

kitty 0.25.0 created by Kovid Goyal
Linux raffadora 5.17.5-200.fc35.x86_64 #1 SMP PREEMPT Thu Apr 28 15:41:41 UTC 2022 x86_64
S
Kernel 5.17.5-200.fc35.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: True
Paths:
  kitty: /home/raffaele/.local/kitty.app/bin/kitty
  base dir: /home/raffaele/.local/kitty.app/lib/kitty
  extensions dir: /home/raffaele/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/raffaele/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    y
confirm_os_window_close 0
font_family             FiraCode Nerd Font Mono
font_size               14.0
listen_on               unix:/tmp/kitty
Added shortcuts:
	super++ → change_font_size all +2.0
	super+, → edit_config_file
	super+- → change_font_size all -2.0
	super+0 → change_font_size all 0
	super+1 → first_window
	super+2 → second_window
	super+3 → third_window
	super+4 → fourth_window
	super+5 → fifth_window
	super+6 → sixth_window
	super+7 → seventh_window
	super+8 → eighth_window
	super+9 → ninth_window
	super+= → change_font_size all +2.0
	super+k → clear_terminal to_cursor active
	super+n → new_os_window
	super+r → start_resizing_window
	super+t → new_tab
	super+w → close_tab
	super+enter → new_window
	super+up → scroll_line_up
	super+down → scroll_line_down
	super+page_up → scroll_page_up
	super+page_down → scroll_page_down
	super+home → scroll_home
	super+end → scroll_end
	shift+super+- → change_font_size all -2.0
	shift+super+= → change_font_size all +2.0
	shift+super+[ → previous_tab
	shift+super+] → next_tab
	shift+super+d → close_window
	shift+super+i → set_tab_title
	shift+super+w → close_os_window
	alt+super+, → debug_config
	alt+super+r → clear_terminal reset active
	alt+super+s → toggle_macos_secure_keyboard_entry
	alt+super+page_up → scroll_line_up
	alt+super+page_down → scroll_line_down
	ctrl+super+space → kitten unicode_input
	ctrl+super+, → load_config_file
	ctrl+super+f → toggle_fullscreen

Important environment variables seen by the kitty process:
	PATH                               ABRIDGED 
	LANG                                en_US.UTF-8
	VISUAL                              vim
	EDITOR                              ed
	SHELL                               /bin/bash
	DISPLAY                             :1
	USER                                raffaele
	XDG_MENU_PREFIX                     gnome-
	LC_MONETARY                         en_GB.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    x11
	LC_PAPER                            en_GB.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      en_GB.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_GB.UTF-8
	XDG_DATA_DIRS                       ABRIDGED
	LC_NUMERIC                          en_GB.UTF-8

**Additional context**

It happens if `.vimrc` contains the following lines. Moving those lines in
`.gvimrc` seems to fix the problem:
```
" === MAXIMIZE WINDOWS ===
" see: https://vim.fandom.com/wiki/Maximize_or_set_initial_window_size
if has("gui_running")
  " GUI is running or is about to start.
  " Maximize gvim window (for an alternative on Windows, see simalt below).
  set lines=999 columns=999
else
  " This is console Vim.
  if exists("+lines")
    set lines=50
  endif
  if exists("+columns")
    set columns=100
  endif
endif
```

**Comment by kovidgoyal** [comment]
kitty does not support terminal programs resizing windows. I assume vim is assuming this operation suceeds without checking. That will be a bug in vim.

**Comment by raffaem** [comment]
thanks for checking!

Can we put this information in the docs maybe? :)

**Comment by kovidgoyal** [comment]
Given this is the first time its come up in five years, doesn't seem common enough to bother documenting a bug in an external program.
