### ISSUE TITLE
Kleisi arrow ligature in Iosevka not rendered correctly

### ISSUE THREAD

**Issue by alternateved** [kovidgoyal/kitty#5072]
**Describe the bug**
The Kleisi arrow ligature `>=>` is not rendered correctly when using Iosevka font. This issue appears with standard version of Iosevka installed from repository as well as with private build with `export-glyph-names` set to `true`. Even though `>=>` ligature seems broken, `<=<` looks correct as can be seen in below screenshot.

**To Reproduce**
1. Install Iosevka 15.3.0
2. Install kitty 0.25.0
3. Run kitty with config posted below

**Screenshots**
![Screenshot_20220508_190357](https://user-images.githubusercontent.com/45176912/167307149-a4c1fee4-434a-4fc5-a4e8-637498a4b444.png)
**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux teishi 5.17.4-1-default #1 SMP PREEMPT Wed Apr 20 07:43:03 UTC 2022 (75e9961) x86_64
Welcome to openSUSE Tumbleweed 20220506 - Kernel 5.17.4-1-default (/dev/tty).

Running under: X11
Frozen: False

Config options different from defaults:
font_family   Iosevka
font_features:
{'Iosevka': ('-calt', '+HSKL')}
font_size     13.0
```

**Additional context**
Minimal config:
```
font_family Iosevka
font_size 13
font_features Iosevka -calt +HSKL
```
File cat'ed:
```
-<< -< -<- <-- <--- <<- <- -> ->> --> ---> ->- >- >>-
=<< =< =<= <== <=== <<= <= => =>> ==> ===> =>= >= >>=
<-> <--> <---> <----> <=> <==> <===> <====> -------->
<~~ <~ ~> ~~> :: ::: == != /= ~= <> === !== =/= =!=
:= :- :+ <* <*> *> <| <|> |> <. <.> .> +: -: =: :> >=> <=<
(* *)  [| |] {| |} ++ +++  \\/  /\\ |- -| <!-- <!--- <***>
```

**Comment by kovidgoyal** [comment]
Report the issue to Iosekvka. And only with export glyph names turned
on. kitty will draw whatever ligatures the font instructs it to.
