### ISSUE TITLE
Config refresh don't work for listen_on

### ISSUE THREAD

**Issue by raffaem** [kovidgoyal/kitty#5074]
1. Open kitty.conf. Make sure there is no `listen_on` directive. If there is, remove it and restart kitty
2. Put a `listen_on` directive there and save the file
3. Refresh config with CTRL+SHIFT+F5
4. Kitty does not create the KITTY_LISTEN_ON environmental variable
5. Restart kitty and watch it create the environmental variable

**Comment by kovidgoyal** [comment]
Read the documentation of that option. It says that reloading it is not
supported.
