### ISSUE TITLE
The title bar only shows the tilde for a non-root user.

### ISSUE THREAD

**Issue by ooonea** [kovidgoyal/kitty#5079]
**Describe the bug**
The title bar shows only a tilde for the home directory. Once any command is run, the username and hostname disappear from the title bar.
**To Reproduce**
1. Start Kitty
2. Run a command in the terminal.
3. See error.

**Screenshots**
Just started.
![immagine](https://user-images.githubusercontent.com/35407790/167513285-f4226eba-b294-4dc2-ad63-1afb2c9b0d1e.png)

After executing a command.
![immagine](https://user-images.githubusercontent.com/35407790/167513024-c007487e-bafe-4675-bf3b-3e78d712ed25.png)

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
FreeBSD oooneabox 13.1-RC6 FreeBSD 13.1-RC6 releng/13.1-n250146-cd651fcc491 GENERIC amd64
Running under: X11
Frozen: False
Paths:
  kitty: /usr/local/bin/kitty
  base dir: /usr/local/lib/kitty
  extensions dir: /usr/local/lib/kitty/kitty
  system shell: /usr/local/bin/zsh
Loaded config files:
  /home/ooonea/.config/kitty/kitty.conf

Config options different from defaults:
cursor_beam_thickness      10.0
cursor_stop_blinking_after 0
cursor_text_color          None
font_family                FiraCode
font_features:
{'FiraCode-Retina': ('+zero', '+onum')}
font_size                  12.0
Added shortcuts:
	shift+super+x → next_tab
	shift+super+z → previous_tab
Changed shortcuts:
	ctrl+shift+x → next_window
	ctrl+shift+z → previous_window
Colors:
	active_tab_background      #f8f8f2   
	active_tab_foreground      #282a36   
	background                 #282a36   
	color0                     #21222c   
	color1                     #ff5555   
	color10                    #69ff94   
	color11                    #ffffa5   
	color12                    #d6acff   
	color13                    #ff92df   
	color14                    #a4ffff   
	color2                     #50fa7b   
	color3                     #f1fa8c   
	color4                     #bd93f9   
	color5                     #ff79c6   
	color6                     #8be9fd   
	color7                     #f8f8f2   
	color8                     #6272a4   
	color9                     #ff6e6e   
	cursor                     #f8f8f2   
	foreground                 #f8f8f2   
	inactive_tab_background    #6272a4   
	inactive_tab_foreground    #282a36   
	mark1_background           #ff5555   
	mark1_foreground           #282a36   
	selection_background       #44475a   
	selection_foreground       #ffffff   
	url_color                  #8be9fd   

Important environment variables seen by the kitty process:
	PATH                                /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/ooonea/bin
	LANG                                it_IT.UTF-8
	SHELL                               /usr/local/bin/zsh
	DISPLAY                             :0.0
	USER                                ooonea
	XDG_MENU_PREFIX                     xfce-
	XDG_RUNTIME_DIR                     /tmp/1001-runtime-dir
	XDG_CURRENT_DESKTOP                 XFCE


```

**Additional context**
The problem occurs even when starting with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
The title comes from your shell. Use an empty shell rc file and it will
go away. FIgure out what in your shell rc file is causing it, probably
something that is interfering with kitty's shell integration. Bisect it
to find the culprit.

**Comment by ooonea** [comment]
It doesn't look like the rc file is the culprit. I've tried disabling both my .zshrc and my .zprofile, but nothing changes. If I switch to the root user with "su" everything works normally, and  I can display both username and hostname in the title bar.
I attach the .zprofile and the .zshrc file of the normal user and the diff between the root zshrc and the normal user zshrc.
[rc.zip](https://github.com/kovidgoyal/kitty/files/8663447/rc.zip)
[diff.txt](https://github.com/kovidgoyal/kitty/files/8663456/diff.txt)

**Comment by kovidgoyal** [comment]
Something in your zsh startup files is causing the issue. Look at man
zsh to see all the files zsh sources, and empty them all.
