### ISSUE TITLE
Prompt when closing kitty 

### ISSUE THREAD

**Issue by CaglarDeniz** [kovidgoyal/kitty#5082]
I've recently updated kitty and started encountering this prompt when closing my terminal and couldn't really figure out how that option was enabled. Is this a feature that was newly added or a default setting that was changed recenty? 

![prompt](https://user-images.githubusercontent.com/55607471/167757477-469b5c4d-e3a2-40e1-a013-6a0b370658cc.png)
I've provided some details about my system below.

Distro: Fedora
Kernel Version: 5.17.5
WM: i3
Compositor: picom
Terminal: kitty

Here's my kitty.conf for reference

[kitty.conf.txt](https://github.com/kovidgoyal/kitty/files/8666294/kitty.conf.txt)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.confirm_os_window_close
