### ISSUE TITLE
SSH kitten doesn't complete shell integration for Fish

### ISSUE THREAD

**Issue by groves** [kovidgoyal/kitty#5085]
**Describe the bug**
When I use the SSH kitten to ssh into my NixOS host with a Fish shell, OSC 7 isn't emitted despite having Kitty's shell integration on.

If I run `echo $KITTY_SHELL_INTEGRATION` in that shell, it prints `enabled`. I think that both indicates that it should have added the OSC 7 emitting and that the shell integration code didn't finish running to unset the variable. 

The integration code is written to `~/.local/share/kitty-ssh-kitten`. If I run `source ~/.local/share/kitty-ssh-kitten/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish`, OSC 7 is emitted as indicated by running `kitty --dump-commands`.

I _think_ that means that the shell integration code is getting copied correctly and that it works, but that the bootstrap is blowing up before getting to it. I'm not seeing any errors in the startup though.

**To Reproduce**
1. `kitty --config NONE --dump-commands`
2. From the spawned kitty
    a. `kitty +kitten ssh jojr`
    b. `echo $KITTY_SHELL_INTEGRATION` and see enabled instead of it being unset
    c. `source ~/.local/share/kitty-ssh-kitten/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish`, cd into a new directory, and see the `process_cwd_notification` command being emitted in the containing kitty.

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Darwin baladi.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.3.1 BuildVersion:	21E258
Frozen: True
Paths:
  kitty: /Users/groves/kitty-nightly/kitty.app/Contents/MacOS/kitty
  base dir: /Users/groves/kitty-nightly/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/groves/kitty-nightly/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Users/groves/.pyenv/shims:/Users/groves/.cargo/bin:/Users/groves/zig/zig-macos-aarch64-0.10.0-dev.1452+911c839e9:/Users/groves/nvim/bin:/opt/homebrew/sbin:/nix/var/nix/profiles/default/bin:/Users/groves/bin:/Users/groves/.poetry/bin:/Users/groves/.pyenv/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/groves/kitty-nightly/kitty.app/Contents/MacOS
	LANG                                en_US.UTF-8
	EDITOR                              invim
	SHELL                               /opt/homebrew/bin/fish
	USER                                groves

```

**Additional context**
I'm running Fish 3.4.1 in my NixOS host. It works correctly in Fish 3.4.1 on an Ubuntu 20.04 host I can also SSH into.

**Comment by kovidgoyal** [comment]
Works for me with

kitty --config=NONE -o shell=fish
kitty +kitten ssh --kitten=login_shell=fish localhost

Running ls in the ssh prompt and then pressing shift+ctrl+g shows the
output of ls in a pager, as expected if shell integration is working

**Comment by kovidgoyal** [comment]
It's a simple script, just insert echo statements wherever you like in
kitty-shell-integration.fish and bootstrap.sh

**Comment by groves** [comment]
Thanks for the pointer! I was able to track it down with that.

It turned out to be a [gnarly interaction between fish and bash on NixOS](https://github.com/NixOS/nixpkgs/issues/173421). If anyone else hits this, the tl;dr to fix it is to add `programs.fish.useBabelfish = true;` to your configuration.nix for NixOS.

**Comment by kovidgoyal** [comment]
You're welcome sounds like it was fun to tack down ;)
