### ISSUE TITLE
Add scroll-to-center option kitty diff kitten with n and p keys

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#5090]
**Is your feature request related to a problem? Please describe.**
When navigating a diff using the diff kitten, the `n` and `p` keys scroll the corresponding hunk to the top of the screen.  This makes it difficult to see the context around the current hunk and I constantly find myself using the mouse to scroll above the current hunk to reveal additional context.

**Describe the solution you'd like**
Perhaps we can add an option to have the `n` and `p` keys keep the current hunk vertically centered?

**Comment by kovidgoyal** [comment]
You dont need to use the mouse, just press j to scroll down. Moving the
search result to the center of the screen is certainly possible, but I
am not a fan of it as it makes it difficult to know what result you are
at. That said I wont refuse a PR to add a jump to next at center of
screen action.
