### ISSUE TITLE
cursor option not working

### ISSUE THREAD

**Issue by anuvyklack** [kovidgoyal/kitty#5091]
`cursor` option in `kitty.conf` file doesn't do anything.

I'm using kitty 25 and neovim 0.7.
If in neovim set
```
set guicursor=i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50
```
it in normal mode use terminal settings for cursor shape and color.

And my cursor is always of `#cccccc` color despite the `cursor` option value. Neighter
`cursor none` nor `cursor #777777` takes any effect, while the `cursor_text_color` option is still working.

**Comment by kovidgoyal** [comment]
cursor color can be overridden by terminal applications. Get neovim to
not override the cursor color and you will be fine.

**Comment by anuvyklack** [comment]
This is definitely what I did with my `guicursor` option.
And my cursor color is `#cccccc` which is nowhere used in my colors scheme, but kitty's default value.

**Comment by kovidgoyal** [comment]
I cant help you with neovim. But this proves its not a kitty issue:

1) kitty --config NONE -o cursor=red
2) cursor is red as expected
3) printf '\e]12;green\e\'
4) cursor is green as expected.

**Comment by anuvyklack** [comment]
No. After 3rd step cursor is still red

**Comment by kovidgoyal** [comment]
It's green for me.

**Comment by kovidgoyal** [comment]
Dont forget the trailing slash in the printf.

**Comment by anuvyklack** [comment]
Yes, trailing slash makes the difference.
