### ISSUE TITLE
ls | grep

### ISSUE THREAD

**Issue by foolofdestiny** [kovidgoyal/kitty#5093]
kitty control shell window (ctrl+shift+esc) cli  interfaace   deely

be able to use grep to filter window ident info

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in implementing that, patches welcome.

**Comment by kovidgoyal** [comment]
Oh and you can do it easily enough by simply running ls and pressing
ctrl+shift+g and then searching for whatever you want in the ls output.
