### ISSUE TITLE
Man page "Tabs" table is malformatted.

### ISSUE THREAD

**Issue by mobotsar** [kovidgoyal/kitty#5095]
**Describe the bug**
Parts of the table meant to contain info in the "Tabs" section are somehow malformed. When viewing from within kitty, it's transposed downward into "Windows" and overlapping content in that section. When viewing in gnome-terminal (and other vte terminals such as tilix), they appear to be missing altogether.

**To Reproduce**
Just run `man kitty`.

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux fedora 5.17.7-300.fc36.x86_64 #1 SMP PREEMPT Thu May 12 14:56:44 UTC 2022 x86_64
S
Kernel 5.17.7-300.fc36.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_US.UTF-8
	EDITOR                              /home/al/.local/bin/nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                al
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/al/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

**Additional context**
This is with no configuration specified, i.e. the bug is reproducible immediately after installing kitty.

**Screenshots**
Gnome Terminal:
![image](https://user-images.githubusercontent.com/77617365/168382397-a0f9a804-9fe4-4bfe-944c-3d2ad3daadf6.png)
Kitty:
![image](https://user-images.githubusercontent.com/77617365/168382438-e0b0d6a3-0ed9-4001-8ca3-3be3604302cc.png)

**Comment by kovidgoyal** [comment]
Use a decent man pager. Here is how it looks on my system.
![screenshot](https://user-images.githubusercontent.com/1308621/168406891-fa9be1b8-8418-4b7b-b49c-ea6834b2274f.png)

Here is the script I use as a manpager
```py
#!/usr/bin/env python3

import os

# Blink -> Bold + GREEN
os.environ['LESS_TERMCAP_mb'] = "\033[1;32m"
# Bold -> Bold + CYAN
os.environ['LESS_TERMCAP_md'] = "\033[1;36m"
# Reset all attributes
os.environ['LESS_TERMCAP_me'] = "\033[0m"
# Standout -> Bold + yellow on blue
os.environ['LESS_TERMCAP_so'] = "\033[1;33;44m"
# End standout
os.environ['LESS_TERMCAP_se'] = "\033[22;39;49m"
# Underline -> Italic + red
os.environ['LESS_TERMCAP_us'] = "\033[3;31m"
# End underline
os.environ['LESS_TERMCAP_ue'] = "\033[23;39m"
# Dim mode
os.environ['LESS_TERMCAP_mh'] = "\033[90m"

os.execlp('less', 'less', '-R')
```

**Comment by mobotsar** [comment]
I get that man pages are lower priority, but I shouldn't need to reconfigure my environment and know the exact ANSI code magic of your system to get a man page to render. This behavior is the out-of-the-box experience (with `less`) and persists with `more`, `bat`, and `most`, all of which are "decent" pieces of software — it seems like something worth addressing.

**Comment by kovidgoyal** [comment]
I am afraid I have no interest in degrading the man pages to conform to
whatever broken out-of-the-box experience the default less provides.

Simply using less -R

as your manpager is sufficient. 

And, these arent "custom ANSI codes specific to my system". They are standard
ANSI codes respected by 99% of terminals out there. Use them or your own
preferences, or use the HTML documentation instead.

**Comment by meowcoder** [comment]
To fix the table borders I changed `center;` to `box center;` and removed the vertical and horizontal rules (lines) that were used as the table borders.
<details>
  <summary>diff</summary>

```diff
--- share/man/man1/kitty.1	2023-09-18 07:18:38.847064000 +0500
+++ kitty.1	2023-09-25 18:17:24.148771202 +0500
@@ -189,9 +189,8 @@
 window manager. The keyboard controls (which are \fI\%all customizable\fP) for tabs and windows are:
 .SS Scrolling
 .TS
-center;
-|l|l|.
-_
+box center;
+l|l.
 T{
 Action
 T}	T{
@@ -257,7 +256,6 @@
 T}	T{
 \fI\%ctrl+shift+g\fP (see \fI\%Shell integration\fP)
 T}
-_
 .TE
 .sp
 The scroll actions only take effect when the terminal is in the main screen.
@@ -266,9 +264,8 @@
 terminal.
 .SS Tabs
 .TS
-center;
-|l|l|.
-_
+box center;
+l|l.
 T{
 Action
 T}	T{
@@ -322,13 +319,11 @@
 T}	T{
 \fI\%ctrl+shift+alt+t\fP (also \fB⇧+⌘+i\fP on macOS)
 T}
-_
 .TE
 .SS Windows
 .TS
-center;
-|l|l|.
-_
+box center;
+l|l.
 T{
 Action
 T}	T{
@@ -408,7 +403,6 @@
 (also \fB⌘+1\fP, \fB⌘+2\fP ... \fB⌘+9\fP on macOS)
 (clockwise from the top\-left)
 T}
-_
 .TE
 .sp
 Additionally, you can define shortcuts in \fBkitty.conf\fP to focus
@@ -501,9 +495,8 @@
 The full list of actions that can be mapped to key presses is available
 \fI\%here\fP\&.
 .TS
-center;
-|l|l|.
-_
+box center;
+l|l.
 T{
 Action
 T}	T{
@@ -635,7 +628,6 @@
 T}	T{
 \fI\%ctrl+shift+a>d\fP
 T}
-_
 .TE
 .SH SEE ALSO
 .sp
```
</details>

The table borders were messed up in `foot` as well, in both terminals which tables were rendered incorrectly depended on the window size, with certain sizes everything was okay.
After the fix no problems in either terminal with any window size.

![kitty](https://github.com/kovidgoyal/kitty/assets/287868/828f545d-b42a-4045-8678-c276486e6ed5)

And to add colors I had to `export GROFF_NO_SGR=1`.
