### ISSUE TITLE
Kitty Embedding option. Allow Kitty to be embedded into an existing window.

### ISSUE THREAD

**Issue by bennybenjaman** [kovidgoyal/kitty#5098]
**Is your feature request related to a problem? Please describe.**
Does Kitty support embedded window ID?
**Describe the solution you'd like**
Terminals like xterm and rxvt offer options -into and -embed to select which window the terminal instance will open in. This can be hand when embedding a terminal in an application. This would be especially useful for a terminal like kitty when playing videos inside the terminal.

**Additional context**
Is there any way to implement this as it stands with kitty?

**Comment by kovidgoyal** [comment]
No it isn't and I'm afraid I have no interest in implementing such an
X11 specific feature given that X11 is on its way out.
