### ISSUE TITLE
Terminal bell and window manager hits

### ISSUE THREAD

**Issue by nh2** [kovidgoyal/kitty#51]
The visual bell (e.g. `echo -e '\a'`) and the corresponding alert state for the window manager is a key feature for me, would it be diffucult to implement?

**Comment by kovidgoyal** [comment]
The terminal bell is curently implemented as an audio bell. As for taskbar notifications, glfw, the windowing toolkit kitty uses does not currently support that, see https://github.com/glfw/glfw/issues/732

When that changes, support for it should be trivial to add in kitty. 

As for a visual bell, that is not particularly hard, but as I prefer audio bells myself (I find the whole screen flashing very distracting), it's not something I am particularly motivated to implement, patches are welcome.

**Comment by nh2** [comment]
Nice.

> but as I prefer audio bells myself

Agreed, but for very silent or very loud areas where you can't wear headpones, there's no alternative.

Thanks for adding it! And looking orward for GLFW to implement the WM hint.

**Comment by kovidgoyal** [comment]
Now implemented in glfw
