### ISSUE TITLE
changing kitty option based on context

### ISSUE THREAD

**Issue by mosaleh52** [kovidgoyal/kitty#5101]
The way kitty Handel RTL text was very good at least for my usage until I have started nvim which have its own RTL implementation 
changing ```force_ltr  yes``` solve the problem in nvim but not outside it 
is there any way to stop it inside nvim only so I can get best of both sides

**Comment by kovidgoyal** [comment]
No kitty in general has no way to know when a particular program is
running. You can simply have a script change that setting in kitty.conf
and the have kitty reload its config by killing it with SIGUSR1

**Comment by mosaleh52** [comment]
is there any way to change ```force_ltr``` without restarting kitty

**Comment by kovidgoyal** [comment]
Yes, as I said, modify kitty.conf and reload the config.

**Comment by mosaleh52** [comment]
Could  you kindly provide me with some guidance or hints to achieve this
 I am planning to make zsh script aliased to nvim that change config, reload it and open nvim

**Comment by kovidgoyal** [comment]
write a script to change the value in kitty.conf and use killall with
-SIGUSR1 to make all kitty instances reload their configuration

**Comment by mosaleh52** [comment]
Ok, thanks for your support ;)
