### ISSUE TITLE
Handle combining character. 

### ISSUE THREAD

**Issue by ericwq** [kovidgoyal/kitty#5102]
**Is your feature request related to a problem? Please describe.**
on the terminal command line: type 
```
$ echo "Chin\u0308\u0308\u0308a 🏖 is where I live. 国旗🇳🇱Fun with Flag🇧🇷."
```
for kitty, you got 
<img width="922" alt="Screen Shot 2022-05-16 at 14 35 43" src="https://user-images.githubusercontent.com/1501146/168533339-28395683-780f-4405-afb7-5ab7def966c3.png">

**Describe the solution you'd like**
The correct result should be:
<img width="937" alt="Screen Shot 2022-05-16 at 14 35 21" src="https://user-images.githubusercontent.com/1501146/168533395-75dfde2f-aa9e-4417-9cd7-74cf7ee8a258.png">

Please note, the "n" character is added with one \u0308 combining character.
**Describe alternatives you've considered**
no

**Additional context**
you can try to echo the test string in different terminal emulator.  Please also note the "island" glyph should be a color version.

**Comment by kovidgoyal** [comment]
kitty handles combining characters fine. Just not more than two of them, though in the next release that limit is increased to three. And as for your non-colored island glyph that will be because it has default text presentation. Follow it with a VS16 variation selector to get it to render as an emoji.

**Comment by ericwq** [comment]
For single combining character, the result is not good. There should be two dot on the top of "n". the position of combining character is not as good as expected.
<img width="417" alt="Screen Shot 2022-05-16 at 16 01 54" src="https://user-images.githubusercontent.com/1501146/168556597-c114b5f8-677a-4b9a-8f96-9dfaf0ecc112.png">

**Comment by kovidgoyal** [comment]
The position of the combining character is decided by harfbuzz not
kitty.
