### ISSUE TITLE
Not possible to set full xterm mode in Kitty

### ISSUE THREAD

**Issue by jclsn** [kovidgoyal/kitty#5107]
**Describe the bug**
Vimspector has an issue where it scrolls up when moving the mouse inside windows. The developer says because it is not xterm. I tried setting xterm. or xterm-256color or xterm-kitty. In all cases this bug occurs.

No issues with e.g. Konsole

**To Reproduce**
1. Use Kitty
2. Install VIm and [Vimspector](https://github.com/puremourning/vimspector)
3. Set the ``set mouse=a`` setting in ``.vimrc`` to get mouse support in Vim
4. Start a debug session
5. See how windows scroll up when just hovering the mouse

**Screenshots**
Will not help since it is a problem of motion.

**Environment details**
Ubuntu Jammy
https://pastebin.com/9wt0hFkC

**Comment by kovidgoyal** [comment]
kitty is not xterm, in fact nothing other than xterm is xterm. If the
developers of vimspector wants their software to work only on xterm, that's
their issue.

If there is some specific escape code they would like support for, they
are welcome to post here with details. And note that kitty explicitly
does not support bce (background color erase) and says so in its
terminfo. Most likely simspector is ignoring terminfo and using it
anaway. See the kitty FAQ.

**Comment by puremourning** [comment]
Please be very clear, this is nothing to do with vimspector. It's vim that's misbehaving due to the user having informed it that its terminal is xterm, whereas it's actually kitty.

**Comment by puremourning** [comment]
no, there is no bug in vim. there is no bug in vimspector. there is probably no bug in kitty. whether or not kitty supports all event mouse tracking according to the xterm specification is up the kitty author. whether or not your terminfo is correct and your TERM environment is set correctly is between you, your sys admin and the author of the terminfo file/terminal.

**Comment by jclsn** [comment]
@kovidgoyal Is there a possibility to implement this event mouse tracking in xterm-kitty?

**Comment by kovidgoyal** [comment]
If the issue is about mouse events, which has nothing to do with xterm,
it is likely a duplicate of #4992. Use a nightly build of kitty and you
will be fine.

**Comment by puremourning** [comment]
Confirmed works with nightly kitty.

**Comment by jclsn** [comment]
Yes, I can also confirm that. Thanks
