### ISSUE TITLE
Ligatures look strange when using Noto mono font

### ISSUE THREAD

**Issue by MachFour** [kovidgoyal/kitty#511]
Hello, I'm not sure if this is an issue with Kitty or with the Noto mono font itself, but the ligatures 'fi' and 'fl' (and ffi) are rendered strangely when in Kitty.

Here's a screenshot:
![kitty-ligatures-noto](https://user-images.githubusercontent.com/5557146/39474533-c7a1cd90-4d97-11e8-896e-c6eb163becb8.png)

I'm using Kitty 0.9.0. Let me know if there's any other information that would be helpful

**Comment by kovidgoyal** [comment]
kitty needs an actual monospaced font. A font that creates a ligature out of neighboring characters that has a width different from the original characters is not monospaced and is not suitable for use in kitty. Mostly you should use monospaced fonts with ligatures designed for use in a terminal, such as fira code or operator mono lig or hasklig etc.

**Comment by MachFour** [comment]
Thanks for the explanation!

For anyone that likes Noto fonts, there's a relevant issue open on the GitHub page, at https://github.com/googlei18n/noto-fonts/issues/1021 

Amazingly, someone actually posted a patched set of Noto Mono fonts which disables ligatures and is a good workaround to use in Kitty. Link below:
https://github.com/googlei18n/noto-fonts/files/1690450/noto-sans-mono-patched-ligatures.zip

**Comment by freed00m** [comment]
hi @MachFour  how did you set up the font in kitty.conf ?

`kitty list-fonts` is not showing it :| and I am unable to configure it so kitty would use the patched font

**Comment by MachFour** [comment]
@freed00m for me, Noto Sans still doesn't show up in `kitty list-fonts`.
But I just use `font_family Noto Sans` in my `kitty.conf` and it works fine anyway xD

They've released some other patched versions upstream (if you look near the end of https://github.com/googlei18n/noto-fonts/issues/1021 there's a link) but I haven't tried them yet. Feel free to give it a go and let me know if they're any better/different.

**Comment by Snuggle** [comment]
@freed00m Your workaround isn't working for me. :/
Still getting weird ligatures when I type `fi`.

![image](https://user-images.githubusercontent.com/26250962/44135774-004f4aae-a05a-11e8-9485-03bf68fc5b76.png)

**Comment by freed00m** [comment]
@Snuggle I also use the github patched at `~/.local/share/fonts/NotoSansMono` these [files](https://github.com/googlei18n/noto-fonts/tree/0f75e8ff47de154699408b6d4f75517ec9830063/phaseIII_only/unhinted/otf/NotoSansMono) maybe it had something to do it with also, but I don't think so. Have you rebooted your device or maybe your fontcache is not refreshed automatically ?

**Comment by freed00m** [comment]
@Snuggle - I fear it's not a bug but rather brainfart of the designer.
