### ISSUE TITLE
fast_data_types.FreeTypeError: Failed to load glyph, with error: invalid size handle

### ISSUE THREAD

**Issue by jszhao** [kovidgoyal/kitty#5116]
**Describe the bug**
Some color emoji, for example 🉑️ and ❤️️ can not display correctly. When input after the prompt, error appears:
```
fast_data_types.FreeTypeError: Failed to load glyph, with error: invalid size handle
```

**To Reproduce**
1. launch the kitty from another term
2. input 🉑️ after the prompt
3.  the glyph is not correctly displayed

**Screenshots**
The right window is `kitty`,  the left window show the debug info.

![kitty-emoji](https://user-images.githubusercontent.com/12680518/169654883-cb722cb4-65d0-4e59-844f-2bfe8614888b.png)

**Environment details**
```
kitty 0.19.3 created by Kovid Goyal
Linux 10 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64
Debian GNU/Linux 11 \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf
Running under: X11

Config options different from defaults:
update_check_interval 0.0
```

**Comment by kovidgoyal** [comment]
Your version of kitty is ancient, update.
