### ISSUE TITLE
fira code v6 liguature not working in terminal

### ISSUE THREAD

**Issue by hrdkmishra** [kovidgoyal/kitty#5124]
**Describe the bug**
just downloaded firacode from offical github repo v6 and i noticed ```=>``` is not working as it suppose to in the terminal.

im on arch xfce and using the latest kitty
![image](https://user-images.githubusercontent.com/87580981/170075697-470cb95b-8952-4a64-96dc-4ec7adda13d8.png)

kitty lists-font
![image](https://user-images.githubusercontent.com/87580981/170075898-078718cf-dff0-4b6f-9b6b-e2cd71da8c3c.png)

kitty config
![image](https://user-images.githubusercontent.com/87580981/170076106-f2f64f0b-0477-477e-b21e-7a9ade172ae1.png)

**Comment by kovidgoyal** [comment]
look at your screenshot, one of the characters is bold and one is not.
you cant have ligatures across different font faces.
