### ISSUE TITLE
Too bright colors in 0.25.1 on MacOS

### ISSUE THREAD

**Issue by evmorov** [kovidgoyal/kitty#5129]
**Describe the bug**

The colours in 0.25.1 are too bright/saturated compared to all the previous releases.

I'm aware of the new `macos_colorspace`. I've tried `srgb`, `default` and `displayp3`. But nothing seems to work to make it how it was.

**Screenshots**

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/1059480/170496382-22607fb1-87f4-44ae-90a4-9bc52a71f5ae.png">

**Comment by kovidgoyal** [comment]
There have been no changes to color rendering in 2.5.1 that I know of.
2.5.0 and 2.5.1 (by default) both use the sRGB colorspace. Try inserting
a printf at line 1733 in in glfw/cocoa_window.m to verify.

**Comment by evmorov** [comment]
@kovidgoyal am I correct that you understood the problem and fixed it in cb55878efd73e031b911cecd1d36cb63b5a63de8?

**Comment by kovidgoyal** [comment]
yes

**Comment by evmorov** [comment]
> Looks like this is still broken in 0.25.2.

Same for me.

@kovidgoyal can you reopen?

**Comment by kovidgoyal** [comment]
Man, this setting is cursed. Here you go: https://github.com/kovidgoyal/kitty/commit/80ad596d3db0c1181d93b5bdbdb3fc44f09196bc
