### ISSUE TITLE
macOS: App Shortcut does not work

### ISSUE THREAD

**Issue by henryhchchc** [kovidgoyal/kitty#5132]
**Describe the bug**
Setting shortcuts via the App Shortcut in System Preferences does not work only for kitty.

**To Reproduce**
1. Open **System Preferences**
2. Navigate to **Keyboard -> Shortcuts -> App Shortcuts**
3. Add a mapping from **[Opt+Control+H]** to **[Window->Tile Window to Left of Screen]** (the brackets are not included, see Fig 1)
4. It does not apply to the menu item of kitty only (see Fig 2, Fig 3, and Fig 4)

**Screenshots**
<img width="673" alt="image" src="https://user-images.githubusercontent.com/5498199/170613378-b37b9ab2-fc7f-4d4f-a980-6f46438346ca.png">
Fig 1: Shortcut configuration

<img width="600" alt="image" src="https://user-images.githubusercontent.com/5498199/170613555-cccda380-4d82-42e5-9ce9-4fcc55d8d526.png">
Fig 2: Working for Finder

<img width="789" alt="image" src="https://user-images.githubusercontent.com/5498199/170613674-4eecc9a0-897e-4bda-8d80-d9f3b229a1c3.png">
Fig 3: Working for VS Code

<img width="406" alt="image" src="https://user-images.githubusercontent.com/5498199/170614214-99612380-7025-464b-845e-d1ff91814c4c.png">
Fig 4: Does not work for kitty

**Environment details**
```
kitty 0.25.1 created by Kovid Goyal
Darwin hc-lab-box.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/henry/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height                 1.2
bell_on_tab                         
bold_font                          SFMono Nerd Font Bold
bold_italic_font                   SFMono Nerd Font Bold Italic
cursor_blink_interval              0.0
enabled_layouts                    ['splits']
font_family                        SFMono Nerd Font Regular
italic_font                        SFMono Nerd Font Regular Italic
macos_colorspace                   default
macos_quit_when_last_window_closed True
macos_show_window_title_in         window
macos_thicken_font                 0.3
macos_titlebar_color               -2
repaint_delay                      8
scrollback_lines                   30000
tab_activity_symbol                ● 
tab_bar_style                      powerline
tab_powerline_style                slanted
tab_title_template                 {fmt.fg.orange}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title}
url_style                          1
Added mouse actions:
	cmd+left click ungrabbed → mouse_handle_click selection link prompt
	cmd+left click grabbed → mouse_handle_click selection link prompt
Removed mouse actions:
	left click ungrabbed → mouse_handle_click selection link prompt
Added shortcuts:
	cmd+[ → previous_tab
	cmd+] → next_tab
	cmd+w > h → neighboring_window left
	cmd+w > j → neighboring_window down
	cmd+w > k → neighboring_window up
	cmd+w > l → neighboring_window right
	opt+cmd+enter → launch --location=hsplit
Removed shortcuts:
	cmd+w → close_tab
Changed shortcuts:
	cmd+enter → launch --location=vsplit
Colors:
	active_border_color                #44475a   
	active_tab_background              #5e81ac   
	active_tab_foreground              #eceff4   
	background                         #1e1e1e   
	color0                             #3b4252   
	color1                             #bf616a   
	color10                            #c3e88d   
	color11                            #ffcb6b   
	color12                            #82aaff   
	color13                            #c792ea   
	color14                            #89ddff   
	color15                            #eeffff   
	color2                             #a3be8c   
	color3                             #ebcb8b   
	color4                             #81a1c1   
	color5                             #b48ead   
	color6                             #88c0d0   
	color7                             #eceff4   
	color8                             #4c566a   
	color9                             #f07178   
	cursor                             #81a1c1   
	foreground                         #e5e9f0   
	inactive_border_color              #282a36   
	inactive_tab_background            #3b4252   
	inactive_tab_foreground            #d8dee9   
	tab_bar_background                 #4c566a   
	url_color                          #88c0d0   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                henry
```

**Additional context**
- The problem can be reproduced with `kitty --config NONE`.
- [Create keyboard shortcuts for apps on Mac (Apple Docs)](https://support.apple.com/en-hk/guide/mac-help/mchlp2271/mac)

**Comment by kovidgoyal** [comment]
kitty does not contain code for OS window management, that is the job of the window manager. I know that apple's window manager is particularly underpowered, so I suggest you install something like Hammerspoon to perform these tasks instead.

**Comment by henryhchchc** [comment]
No it is not about window management, it is about keyboard shortcuts.

**Comment by kovidgoyal** [comment]
The keyboard shortcut you are asking for *is about window management*.
Keyboard shortcuts dont exist magically. The action they correspond to
has to actually be implemented by the application.

**Comment by henryhchchc** [comment]
This menu item it provided by macOS and it works when I click on it. As such, I don't think kitty needs to implement anything for it.

The problem is that we can not assign a shortcut for it via System Preference.
The keyboard shortcut in System Preference works by assigning a hotkey to the corresponding menu item. The matching is done by parsing the menubar items kitty reports to macOS. Therefore I suspect that kitty did not correctly report the cascading hierarchy of the menu items. #5004 may be related. 

Specifically, this code change:  https://github.com/kovidgoyal/kitty/pull/5004/files#diff-ceebd918eb25a8fb4cdce4e7382cb7a536997134616f8511342600eeab2a73ddR652

**Comment by kovidgoyal** [comment]
It's not provided my macOS. Ever application needs to add it to its
menus. And implement it. It may well be cocoa provides some api to make
implementing it easier, which is why many macos applications have it,
but as I said, kitty is not in the business of managing OS window
positioning.

**Comment by henryhchchc** [comment]
> Ever application needs to add it to its menus.

I have some reservation on this, because kitty does have such menu items.

**Comment by henryhchchc** [comment]
Sorry for my inaccurate wording, it is called [Split View](https://support.apple.com/en-us/HT204948) by Apple.

**Comment by henryhchchc** [comment]
> Therefore I suspect that kitty did not correctly report the cascading hierarchy of the menu items.

The reason why I mention this is that, I tried to change [Window->Tile Window to Left of Screen] to [Tile Window to Left of Screen] in System Preference and it works. Therefore, I think kitty did not tell macOS that the menu items are under the [Window] menu.

**Comment by kovidgoyal** [comment]
On Thu, May 26, 2022 at 07:32:02PM -0700, Henry Chu wrote:
> > Ever application needs to add it to its menus.
> 
> I have some reservation on this, because kitty does have such menu items.

If it already has the menu items then you are right and they are indeed
put there by the OS. Since I know for a fact that kitty does not contain
any code for tiling of OS Windows. Actually, thinking about it this is
not at all surprising, Apple keeps pulling stupid stunts like this.

Since kitty has its own comprehensive keyboard shortcut system, OS
injected application shortcuts are not going to work. You could
theoretically add support for them by reverse engineering whatever plist
apple maintains for application shortcuts, like @page-down and I did for
the global shortcuts, but I'm afraid that's too much work for just these
shortcuts. If you wish to send a PR I will be happy to review it. See
how global_shortcuts is implemented in glfw/cocoa_init.m

**Comment by kovidgoyal** [comment]
On Thu, May 26, 2022 at 07:38:34PM -0700, Henry Chu wrote:
> > Therefore I suspect that kitty did not correctly report the cascading hierarchy of the menu items.
> 
> The reason why I mention this is that, I tried to change [Window->Tile Window to Left of Screen] to [Tile Window to Left of Screen] in System Preference and it works. Therefore, I think kitty did not tell macOS that the menu items are under the [Window] menu.

kitty does not even create these menu items, all menu items it creates
are in cocoa_create_global_menu()

**Comment by henryhchchc** [comment]
Thanks for the explanation. Kitty is a great piece of software and I am glad to help. I need to spend sometime to figure it out before I can submit a PR.
