### ISSUE TITLE
Disabling "click to move cursor" without disabling other prompt mark functionality

### ISSUE THREAD

**Issue by VorpalBlade** [kovidgoyal/kitty#5134]
**Is your feature request related to a problem? Please describe.**

It appears that the "click to move cursor" functionality interacts poorly with https://github.com/zsh-users/zsh-autosuggestions where it will suggest a completion from history and then when left arrow is pressed insert that. I have found that a simple click for focus in the kitty window will trigger this more often than not when I have a partial command written in the window. Thus I want the ability to disable this "click to move cursor" function, or rebind it so that it needs shift-click or similar. I can't figure out how to do so.

All I found was a mention of shell integration `no-prompt-mark`, but I do want the other functionality of prompt mark, and besides it doesn't seem to *do anything* when I try it, even if I open a new tab after reloading the config (I considered that it might not affect existing tabs). (This might however be the result of using zsh4humans which reworks a lot of shell startup code.)

**Describe the solution you'd like**
I want an option to rebind specifically "click to move cursor" to say shift-click or ctrl-click. As far as I can tell from reading the docs that is currently not possible.

**Describe alternatives you've considered**
Disabling zsh-autosuggestions is really not an option for me, I would rather switch to a different terminal emulator if that was the option. 

**Additional context**

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

**Comment by VorpalBlade** [comment]
@kovidgoyal I did read that but I did not see an action specifically for "move cursor". There is click, but rebinding that would break clicking in ncurses programs as well as I understand it? There doesn't seem to be a clear list of all possible actions and what they do.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Click-the-link-under-the-mouse-or-move-the-cursor

simply remove prompt from the end

**Comment by VorpalBlade** [comment]
@kovidgoyal Ah, thank you. It would be helpful to present all the available actions in a table in the documentation and list what they mean instead of just showing examples of various combinations of actions.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/actions/#mouse-actions

**Comment by VorpalBlade** [comment]
I stand corrected.
