### ISSUE TITLE
Different behavior between config options and command line options

### ISSUE THREAD

**Issue by TheFoolishPupil** [kovidgoyal/kitty#5136]
**Describe the bug**
I'm attempting to send commands to kitty with `allow_remote_control socket-only` and `listen_on unix:/tmp/kitty`. I am able to issue commands to kitty as expected if I run kitty from the command line as `kitty -o allow_remote_control=socket-only  --listen-on unix:/tmp/kitty` but not if set the options in the config file and run the app regularly.

Here's the error I get when attempting to issue the remote commands when running kitty without the command line options:
```
Traceback (most recent call last):
  File "lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "lib/python3.9/runpy.py", line 87, in _run_code
  File "lib/python3.9/kitty_main.py", line 185, in <module>
  File "lib/python3.9/kitty_main.py", line 181, in main
  File "lib/python3.9/kitty_main.py", line 22, in remote_control
  File "lib/python3.9/kitty/remote_control.py", line 242, in main
  File "lib/python3.9/kitty/remote_control.py", line 151, in do_io
  File "lib/python3.9/kitty/remote_control.py", line 98, in __enter__
FileNotFoundError: [Errno 2] No such file or directory
```

**Environment details**
This is when run regularly with the app icon:
```
kitty 0.25.1 created by Kovid Goyal
Darwin gerty.home 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/shot/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    socket-only
enable_audio_bell       False
font_family             iosevka
hide_window_decorations 2
listen_on               unix:/tmp/kitty
window_padding_width    FloatEdges(left=6.0, top=6.0, right=6.0, bottom=6.0)

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                shot
```

This is when run with the options set via the command line:
```
kitty 0.25.1 created by Kovid Goyal
Darwin gerty.home 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/shot/.config/kitty/kitty.conf
Loaded config overrides:
  allow_remote_control socket-only

Config options different from defaults:
allow_remote_control    socket-only
enable_audio_bell       False
font_family             iosevka
hide_window_decorations 2
listen_on               unix:/tmp/kitty
window_padding_width    FloatEdges(left=6.0, top=6.0, right=6.0, bottom=6.0)

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/shot/.cargo/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                shot
	LC_CTYPE                            UTF-8
```

**Comment by kovidgoyal** [comment]
Works for me replacing step 2 above with either

KITTY_LISTEN_ON=unix:/tmp/kitty-488432 kitty @ ls
or
kitty @ --to=unix:/tmp/kitty-488432 ls

Remember that if you use listen_on in the config file the actual path
will contain the process PID as well, see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.listen_on

**Comment by TheFoolishPupil** [comment]
Ah I hadn't noticed that the pid is appended to socket, thanks for pointing that out. This could very well explain the difference in behavior I see. Do you know what the simplest workaround for me to be able to statically point to this socket when configured in the config file? Maybe its possible to prevent the appending of the pid, or is it possible to wildcard it in my remote command like this perhaps ?
```
kitty @ --to unix:/tmp/kitty-* ...
```

**Comment by kovidgoyal** [comment]
The reason for the pid is that you can run multiple kitties. You need to figure out which kitty you want to control and append its pid. If you are only ever going to be running one kitty then use the command line arg which you can also do via  config file on macOS, see the FAQ.

**Comment by TheFoolishPupil** [comment]
Okay, thank you.

**Comment by TheFoolishPupil** [comment]
Are there additional docs on how to use macos-launch-services-cmdline? Do I simply provide the command line arguments as I would specify them on the command line like this `allow_remote_control=socket-only  --listen-on unix:/tmp/kitty` or do they need to specified some other way?

**Comment by TheFoolishPupil** [comment]
nvm, got it. Thanks again.

**Comment by craigmac** [comment]
@shot-codes How did you specify the options in the macos-launch-services-cmdline file? I'm having the same issue.
