### ISSUE TITLE
bind-key repeat support?

### ISSUE THREAD

**Issue by kohnish** [kovidgoyal/kitty#5137]
**Is your feature request related to a problem? Please describe.**

tmux supports `bind-key r` option which is useful for repeating commands without prefix. `bind -r h resize-pane -L 5` would only require pressing prefix one time and you can keep pressing h within the timeout. 

**Describe the solution you'd like**

Something like `map r:ctrl+k>h resize_window wider 5` to allow repeat.  
Maybe also `key_repeat_timeout 500` to override timeout. 

**Describe alternatives you've considered**

Run tmux on kitty, which I'd like to avoid if possible.

**Comment by kovidgoyal** [comment]
Dont see the point. If there is some action you want to press
repeatedly, simply assign it to a single key shortcut.

**Comment by silvio** [comment]
Hi @kovidgoyal.

Can we reopen this? I have this use case: I often have very sick Windows layouts like this one:

```
+--------------+---------------+---------------+
| A            |               |               |
|              +---------------+               |
|              |               |               |
+--------------+---------------+---------------+
|                              | B             |
|                              |               |
+------------------------------+---------------+
```
To jump from "B" to "A" I had to press (depending on which pane was activated last time a bit different): `Ctrl+A>left`, `Ctrl+A>up`, `Ctrl+A>left`.
On `tmux` with `bind-key -r`/`repeat-time` I can press: `Ctrl+A>left`, `up`, `left`.
Which is more elegant.

Even a simpler setup is more expressfull.
```
+--------------+---------------+
|              | A             |
|              |               |
+------------------------------+
|              |               |
+------------------------------+
|              |               |
+------------------------------+
|              |               |
+------------------------------+
| B            |               |
+------------------------------+
```

From `A` to `B` on kitty: `Ctrl+A>Down`, `Ctrl+A>Down`, `Ctrl+A>Down`, `Ctrl+A>Down`, `Ctrl+A>left`
Tmux: `Ctrl+A>Down`, `Down`, `Down`, `Down`, `Left`.

The setup of the windows often varies greatly, so I cannot store this as a command sequence.:wa

**Comment by kovidgoyal** [comment]
Not something I want to spend time on but I will promise to review a PR

**Comment by silvio** [comment]
Would be good to reopen it?

**Comment by kovidgoyal** [comment]
I dont leave issues open that I dont intend to fix myself, they just go
stale. If you or anyone else wants to implement this feature, feel free
to post here for guidance, or open a PR.
