### ISSUE TITLE
Tab name display

### ISSUE THREAD

**Issue by rightaway** [kovidgoyal/kitty#514]
I have some requests for the display of tab name which were really useful features coming from other programs I've used. Maybe you could consider if they would be useful for kitty too.

- When a process is running, the tab name should change to be the name of the process. It helps to easily tell which tab is which when you have multiple tabs and multiple programs running. For example if the active window of a tab has a process running like `sleep 10`, the tab name should change to be `sleep` while it's running. If a tab title is set then the title could be prefixed, e.g. `custom_title: sleep`. If nothing is running it should be name of the tab title e.g. `custom_title`, and if no title was set then the name of the shell like `zsh`.
- If any content changes in a tab that isn't active, the tab title should change to a configurable color. This is useful for example if you start a long running process that has results printed to the console once in a while, it's useful to know when that is without having to keep checking back. So if you trigger a process then switch to another tab, when the first tab's content changes it's tab title color changes. You know something has changed in that tab so you switch to it and the color changes back to the original.
- When a bell goes off in any window of a tab, the tab title should change to a configurable color and remain that way until you switch to the window of the tab where the bell went off. So if you do `sleep 5; tput bel` in a tab then switch to another tab, in 5 seconds you'll see the tab title of the first tab change color until you switch back to it. The window flash feature doesn't work as it doesn't remain until you switch to the tab, it's only temporary, and it's quite a jarring effect so I haven't enabled it.

I miss these features in kitty and would love to finally get rid of my other terminals and tmux which I'm only still using because of little things like these.

**Comment by kovidgoyal** [comment]
1) Not a fan of this. The vast majority of the time, the process name doesn't tell you anything useful. It would be bash or vim or mutt or similar, which just adds noise to the tab bar. And for the rest of the time you can manually name the tab to whatever you want (ctrl+shift+alt+t)

2) Not a fan, this has a fairly significant performance hit (scrolling performance is a key feature of kitty and I like to avoid things that affect it negatively) and for the cases where it is needed it can be implemented by piping output through a filter that rings the bell on new data, in combination with (3) 

3) Sure, this I like.
