### ISSUE TITLE
Edit remote files owned by root when logged in as one of sudoer users

### ISSUE THREAD

**Issue by jack1142** [kovidgoyal/kitty#5147]
**Is your feature request related to a problem? Please describe.**
Currently, it is impossible for me to edit a file (using remote file integration) that the user I logged into when starting the ssh session doesn't have edit permissions for:
![image](https://user-images.githubusercontent.com/6032823/170870385-393824aa-bca8-4b84-a29b-972453acab85.png)

**Describe the solution you'd like**
I'd like to be able to still such files, provided that I confirm that I want to edit it with elevated perms.

**Describe alternatives you've considered**
I suppose I could log into the proper user when starting the ssh session *but* that would require me to allow logging into the root user through ssh which isn't really a good idea. + the lack of confirmation that I in fact want to edit a root-owned file isn't ideal either.

And of course, another alternative would be to just use `nano` or some other text editor but that doesn't use the remote file integration and is obviously less convenient.

**Additional context**
None

**Comment by kovidgoyal** [comment]
there is no way for that to work. Just use the nightly kitty build and do

sudo chown $USER whatever; edit-in-kitty; sudo chown root whatever
