### ISSUE TITLE
[Suggestion] Explain what problems an incorrect TERM=x variable via SSH causes

### ISSUE THREAD

**Issue by phiresky** [kovidgoyal/kitty#515]
Since I ssh into many servers and there is no nice way to always have the correct termcap file on the server, I usually just set `TERM=xterm-256color` because that terminfo always exists.

This seems to fix problems with opening screens, less, git logs etc, but it's unclear what problems exactly setting `TERM=screen` or similar causes, apart from loosing true color support.

The readme only mentions how to copy the termcap file, which is fine but far more complicated than just running `TERM=xxx` when some program fails. I think it would be helpful to mention you can also override TERM and what side effects that causes.

**Comment by kovidgoyal** [comment]
What side effects it causes depends on what programs you run. They can range from keys not working to rendering artifacts. 

And all you need to do to ensure the terminfo file is always available on the server is create a script call ~/bin/myssh that copies the terminfo file before sshing into the server and use that to ssh.
