### ISSUE TITLE
Feature request: allow invoking kitty to focus on the current window, instead of creating a new one

### ISSUE THREAD

**Issue by bnoctis** [kovidgoyal/kitty#5158]
**Is your feature request related to a problem? Please describe.**

Using kitty 0.25.1 on macOS 12.3.1.

I'm used to opening an app with Alfred to focus on it, rather than `Command+Tab`-ing through the long list. This works for almost all apps, but kitty would create a new window when doing so.

**Describe the solution you'd like**

Provide an option to focus on the current window, rather than creating a new one.

**Describe alternatives you've considered**

**Additional context**

**Comment by kovidgoyal** [comment]
If you want to focus an existing window switch to it using your window
manager controls. If you are expecting running kitty to focus an
existing window, that's never going to happen. If you want to run a
command to focus a particular kitty window, use the kitty remote control
feature.

**Comment by bnoctis** [comment]
To clarify a bit: this doesn't happen now. Not sure whose fault this is, but the need disappeared.
