### ISSUE TITLE
Kitty can't open scripts with no extension in MacOS

### ISSUE THREAD

**Issue by DUOLabs333** [kovidgoyal/kitty#5160]
**Describe the bug**
If you try to open an executable/script with no extension with Kitty via the "Open With" menu, it will fail with `Unknown URL type, cannot open:`

**To Reproduce**
1. Make an exectuable with no extension
2. Right click to open it with Kitty
3. See error

**Screenshots**

**Environment details**
```
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/system/.config/kitty/kitty.conf

Config options different from defaults:
Added shortcuts:
        ctrl+c → copy_to_clipboard
        ctrl+t → new_tab
        ctrl+v → paste_from_clipboard
        ctrl+w → close_tab

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/u
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                system
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You didnt post the full debug output so I dont know what version of
kitty you are running. I cannot reproduce with kitty 0.25.1

echo "echo hello world\nread" > test.sh
open -a kitty test.sh

opens a kitty window showing hello world as expected.

**Comment by DUOLabs333** [comment]
Sorry, I should have specified "if the script has no extension".

**Comment by kovidgoyal** [comment]
yes, there is no way to create a file association for filenames without
extensions as far as I know.

**Comment by DUOLabs333** [comment]
But I can associate iTerm2 with such files, or is that a special case?

**Comment by kovidgoyal** [comment]
In kitty, open associations work by file extension/mime type. See https://sw.kovidgoyal.net/kitty/open_actions/#scripting-the-opening-of-files-with-kitty-on-macos

there is no mime-type/extension for filenames without extensions so you
cant associate them. I suppose one could add a custom mimetype like
application/executable to the matching rules for this.

**Comment by snoblenet** [comment]
Could the `open-actions.conf` file perhaps allow us to specify a fallback application for otherwise unmatched files?

**Comment by kovidgoyal** [comment]
the mime matcher supports wildcards, so use */*
