### ISSUE TITLE
Resizing on Wayland is broken

### ISSUE THREAD

**Issue by zmike** [kovidgoyal/kitty#5162]
**Describe the bug**
Resizing a Kitty window on Wayland causes the resized redraw of the window to be a black rectangle.

**To Reproduce**
1. Run Kitty on Wayland
2. Resize the window with the mouse
3. Black flickering rectangle during resize

**Environment details**
```
Kitty v0.25.1, unmodified configuration
```

**Additional context**
See also https://gitlab.freedesktop.org/wayland/weston/-/issues/624 wherein more info about buffer handling issues can be found.

**Comment by kovidgoyal** [comment]
resizing kitty windows works perfectly fine under GNOME, KDE, SWAY (for
floating windows). I'm afraid I dont have any interest in Weston.
Patches welcome.

**Comment by fooishbar** [comment]
It should be reasonably straightforward: don't destroy a `wl_buffer` until the `release` event has arrived. Otherwise you're forcing the compositor to do an allocation & copy for you, which is suboptimal.

**Comment by kovidgoyal** [comment]
Except this is Wayland. Changing something like destruction order will
break some other corner case on some other compositor and even if it
doesn't, making such a change means testing ten different
compositors+versions. Waaaaay too much effort for the payoff.

Not to mention that the entire codebase has only 3 calls to
wl_buffer_destroy, one for mouse cursor and two for client side
decorations. The problem as I understand it has to do with drawing
the window surface not CSD or mouse cursors, and the window surface is
drawn via OpenGL. So presumably something would need to be changed in
whatever piece of code is responsible for bridging OpenGL to Wayland.
That code isnt in kitty however.

**Comment by fooishbar** [comment]
No, it's the client-side decorations, not GL.

Changing kitty from its current behaviour of violating the spec (destroying buffers before the release event arrives) to new behaviour of not violating the spec (waiting until after the release event arrives) is risk-free.

**Comment by kovidgoyal** [comment]
Ah, client side decorations, the best thing since sliced bread. I dont understand why destroying a CSD surface should cause flickering in rendering of the main window surface but I will take your word for it. I will say however, that I get no flickering resizing kitty windows on weston with kitty 0.25.1 and weston 10.0.0.

**Comment by fooishbar** [comment]
It doesn’t make the main surface flicker, but the decorations do constantly flicker to black. This is caused by the wl_buffers being immediately destroyed when new ones are created; you need to listen for the wl_buffer release event and defer destruction until they are unused.

**Comment by kovidgoyal** [comment]
On Thu, Jun 02, 2022 at 09:45:50PM -0700, Daniel Stone wrote:
> It doesn’t make the main surface flicker, but the decorations do constantly flicker to black. This is caused by the wl_buffers being immediately destroyed when new ones are created; you need to listen for the wl_buffer release event and defer destruction until they are unused.

They dont flicker for me. And the buffer being destroyed is followed
immediately by the creation of a new buffer. Still, I dont mind
deferring buffer deletion, that I agree, is risk free.
