### ISSUE TITLE
Ctrl+C doesn't work in micro on MacOS if `map ctrl+c copy_to_clipboard` is set

### ISSUE THREAD

**Issue by DUOLabs333** [kovidgoyal/kitty#5163]
**Describe the bug**
Title

**To Reproduce**
1. Set `map ctrl+c copy_to_clipboard` in `kitty.conf`
2. Install `micro`
3. Open a new file in `micro`
4. Try to copy any text
5. See error

**Screenshots**

**Environment details**
```
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/system/.config/kitty/kitty.conf

Config options different from defaults:
Added shortcuts:
        ctrl+c → copy_to_clipboard
        ctrl+t → new_tab
        ctrl+v → paste_from_clipboard
        ctrl+w → close_tab

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/u
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                system
```

**Additional context**
This is with Kitty 0.25.1. Even if `map ctrl+v paste_from_clipboard` is set, Ctrl+V works as expected. Ctrl+C works on the shell itself.

**Comment by kovidgoyal** [comment]
If you map ctrl+c to copy_on_clipboard it is not sent to terminal
programs, so it wont work for anything other than copying kitty
selections. You want to map it to https://sw.kovidgoyal.net/kitty/actions/#action-copy_or_interrupt
