### ISSUE TITLE
[Question] Why does the cursor turn into an empty block when the Terminal window loses focus?

### ISSUE THREAD

**Issue by sph3** [kovidgoyal/kitty#5166]
![image](https://user-images.githubusercontent.com/59633047/171769492-1c554c9f-59f8-431a-b515-8e5e0a8bd497.png)

I just wanted to know why this happens.\

**Comment by kovidgoyal** [comment]
As an indication that focus is lost.

**Comment by pranavsetpal** [comment]
Is there a way to disable this?
My system, like most I would expect, has separate means to show if a window is in focus, and I really prefer using underline as the cursor and so it just ends up becoming a distraction for me.
