### ISSUE TITLE
unicode input kitten

### ISSUE THREAD

**Issue by anuvyklack** [kovidgoyal/kitty#5169]
I'm on kitty 0.25.1

When I type `ctrl+shift+u` I get the next:

https://user-images.githubusercontent.com/13056013/172006238-5bde45a2-88d5-46e5-9645-747266bfa902.mp4

I guess, that, I can type symbol code and get it, but this is not what is [shown in the documentation](https://sw.kovidgoyal.net/kitty/kittens/unicode_input/)

Is `unicode_input` kitten is changed and documentation is outdated, or should set some option?

**Comment by kovidgoyal** [comment]
That is not from kitty. The kitty unicode input tool looks exactly like
what is shown in the documentation.

**Comment by karunsiri** [comment]
@anuvyklack it's depending on the OS. I'm on Fedora and also have this problem. The solution is to remap the short to something else other than `ctrl+shift+u` in `kitty.conf`. For example:

```
# kitty.conf
map kitty_mod+g input_unicode_character
```

Where `kitty_mod` defaults to `ctrl+shift`.

Hope this helps.
