### ISSUE TITLE
Questions regarding `kitty +complete setup`

### ISSUE THREAD

**Issue by kidonng** [kovidgoyal/kitty#5173]
I get that shell integration is the way to go, but I guess there are still people who doesn't know about or simply missed it. I got a few questions about `kitty +complete setup`:

- Should it be deprecated in favor of shell integration?
- Should [the completion scripts](https://github.com/kovidgoyal/kitty/blob/cd7751681d15d665cf817918b88f42938f724b12/kitty/complete.py#L148-L184) be updated to use the ones from shell integration?

  Notably, using `kitty +complete setup fish2` (in contrast to `kitty +complete setup fish`) gives you the updated completion script, but:

  - Why only `fish2` but not `bash2` or `zsh2`?
  - Why not update `fish` directly, instead of creating a new `fish2`?

**Comment by kovidgoyal** [comment]
Manual completion was removed a while back from the docs, unless I
missed it somewhere. It remains in the code for
backward compatibility. shell integration automatically enables
completion. fish2 is incompatible with fish.
