### ISSUE TITLE
[Feature Request] Option to Make Foreground Selection Transparent

### ISSUE THREAD

**Issue by amarakon** [kovidgoyal/kitty#5176]
I want to have the foreground selection transparent and only set the background selection color. I don't think this is currently possible in the configuration file.

**Comment by kovidgoyal** [comment]
Simply set the foreground and background selection colors to the same color.

**Comment by amarakon** [comment]
Sorry, I meant to prevent selection from changing the text color.

**Comment by kovidgoyal** [comment]
Read the docs: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.selection_foreground

**Comment by amarakon** [comment]
Thanks, I just had to set `selection_foreground none`.
