### ISSUE TITLE
Slow startup on mac even with single instance

### ISSUE THREAD

**Issue by alok** [kovidgoyal/kitty#518]
This is odd.

Running kitty 0.9.0 on macOS 10.13.4.

`time kitty --single-instance sh -c exit ` gives stats of `1.12s user 0.15s system 77% cpu 1.629 total`. I always get this behavior on my mac. Any advice on how to profile this?

**Comment by kovidgoyal** [comment]
Instructions for profiling are in the performance section of the readme. And remember that you need to actually have an already running instance of kitty --single-instance before suubsequent invocations will be fast. 

Also time kitty --single-instance is pretty meaningless. It simply sends a message to the running `kitty -1` instance and then exits. Unless no running kitty -1 instance is found, in which case it starts a new kitty instance.

**Comment by alok** [comment]
I do have another instance of kitty running. Made sure of that.

**Comment by kovidgoyal** [comment]
Not another instance, another instance started with --single-instance
