### ISSUE TITLE
Image preview in vifm file manager stopped working with 0.25.2

### ISSUE THREAD

**Issue by economix70** [kovidgoyal/kitty#5182]
**Describe the bug**
I have been using kitty's image viewing functionality to preview image files in the vifm file manager. This has stopped working with the latest version.

**To Reproduce**
In vifm you can preview files using the e command (preview in same pane) or w command (preview in opposite pane)
To preview images I have the following in the vifmrc:

fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm,*.tiff,*.tif
        \ kitty icat --place=%pwx%ph@%pxx%py --silent %c
	\ %pc
	\ kitty icat --clear --silent %pd
"        \ identify %f

With 0.25.2 it does not work, with the following output:

raceback (most recent call last):   
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "kitty_main.py", line 7, in <module> 
  File "kitty/entry_points.py", line 185, in main 
  File "kitty/entry_points.py", line 13, in icat 
  File "kittens/runner.py", line 112, in run_kitten  
  File "runpy.py", line 213, in run_module 
  File "runpy.py", line 87, in _run_code  
  File "kittens/icat/main.py", line 619, in <module> 
  File "kittens/icat/main.py", line 529, in main 
OSError: [Errno 6] No such device or address: '/dev/tty'

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux cecilbuntu 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64
Ubuntu 22.04 LTS cecilbuntu /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/cecilia/.local/kitty.app/bin/kitty
  base dir: /home/cecilia/.local/kitty.app/lib/kitty
  extensions dir: /home/cecilia/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/cecilia/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.8
bold_font          Ubuntu Mono Bold
bold_italic_font   Ubuntu Mono Bold Italic
font_family        Ubuntu Mono
font_size          13.0
italic_font        Ubuntu Mono Italic
Added shortcuts:
	f5 → goto_layout horizontal
	shift+left → move_window left
	shift+right → move_window right
	shift+up → move_window up
	shift+down → move_window down
	ctrl+left → neighboring_window left
	ctrl+right → neighboring_window right
	ctrl+up → neighboring_window up
	ctrl+down → neighboring_window down

Important environment variables seen by the kitty process:
	PATH                                /opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
	LANG                                en_AU.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :1
	USER                                cecilia
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 i3
	XDG_SESSION_DESKTOP                 i3
	XDG_VTNR                            2
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-i3:/etc/xdg
	XDG_DATA_DIRS                       /usr/share/i3:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/var/lib/snapd/desktop

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` 
Reproduced with kitty --config NONE

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. vifm is running the image previewer
program without a controlling terminal, so there is no way for image display to
work.

**Comment by Mrfiregem** [comment]
For anyone stumbling upon this thread, `vifm` versions greater than 0.12.1 have a [new macro](https://github.com/vifm/vifm/issues/731#issuecomment-954803638) (%N) to support `icat`.
