### ISSUE TITLE
"Failed to find xdg-shell in your compositor" as user, but works fine as root

### ISSUE THREAD

**Issue by levone1** [kovidgoyal/kitty#5184]
**Describe the bug**
Above error shows when running from $[user], but kitty launches and runs fine with "sudo kitty"

My setup is arm64 Debian lxc container running on SailfishOS (mobile) host.

I'm fine using it as root, but I get the same error running on host side, which I assumed was just a correct error message, having to do with older Wayland, libs, etc., (even though wayland-protocols is installed and xdg-shell files are present). When it happened in Debian container, it made me think maybe there's a workaround to get it to work on Sailfish side...

What/where is kitty lookin at/for to conclude no xdg-shell?

**To Reproduce**
1. Download bin
2. cd to download dir
3. ./kitty as normal user

**Screenshots**
![Screenshot_20220609_002](https://user-images.githubusercontent.com/43003405/172846277-caad8ad7-a6f9-4db1-818d-4cd52e11ee61.png)
![Screenshot_20220609_003](https://user-images.githubusercontent.com/43003405/172846283-a1ca3452-13c6-475f-8b18-d62a01b5d4b6.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
kitty 0.21.2 created by Kovid Goyal
Linux c1 4.14.254-gadd31cf4ca50 #1 SMP PREEMPT Sat Apr 9 14:56:16 EEST 2022 aarch64
Debian GNU/Linux bookworm/sid \n \l
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

no change with ...config NONE. I'm using default/example config included in download.

**Comment by kovidgoyal** [comment]
xdg-shell comes from the compositor, as do all wayland protocols.
wayland applications request the compositor for what it supports and 
parse its response, in this case it will xdg_wm_base

**Comment by levone1** [comment]
> xdg-shell comes from the compositor, as do all wayland protocols. wayland applications request the compositor for what it supports and parse its response, in this case it will xdg_wm_base

why does it find it as root, but not as user?

**Comment by levone1** [comment]
> No clue.

Not sure what it means, but if it's helpful to know, I figured out that it launches fine with `env -u WAYLAND_DISPLAY kitty` even though setting 'wayland' in kitty.conf has no effect ...

**Comment by kovidgoyal** [comment]
On Sat, Jun 11, 2022 at 08:41:50PM -0700, levone1 wrote:
> > No clue.
> 
> Not sure what it means, but if it's helpful to know, I figured out that it launches fine with `env -u WAYLAND_DISPLAY kitty` even though setting 'wayland' in kitty.conf has no effect ...

unsetting wayland_display prevents kitty from using wayland, so obviously
it will work fine. If you want to do that set linux_display_server to
x11 in kitty.conf

**Comment by levone1** [comment]
> On Sat, Jun 11, 2022 at 08:41:50PM -0700, levone1 wrote: > No clue. Not sure what it means, but if it's helpful to know, I figured out that it launches fine with `env -u WAYLAND_DISPLAY kitty` even though setting 'wayland' in kitty.conf has no effect ...
> unsetting wayland_display prevents kitty from using wayland, so obviously it will work fine. If you want to do that set linux_display_server to x11 in kitty.conf

Sorry - that's what I meant... Setting 'x11' in kitty.conf has no effect, (still get error), but launching with env -u...  works.

**Comment by kovidgoyal** [comment]
Then you are either using a very old version of kitty before that setting was introduced or you are editing the wrong kitty.conf
