### ISSUE TITLE
Backspace , MacOS , ssh

### ISSUE THREAD

**Issue by nobrowser** [kovidgoyal/kitty#5186]
**Summary**
When I ssh from kitty on MacOS into a Linux server, the backspace key doesn't work.

**To Reproduce**

1. Start kitty
2. ssh my-server.example.com
3. type `ls<backspace><backspace>`
4. cursor moves forward as if a tab has been typed, instead of backward and erasing

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin Ians-MBP 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.6.6 BuildVersion:	20G624
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.D5Lo3mm2pE/org.xquartz:0
	USER                                itz
```

**Additional context**
Fresh kitty install, no local configuration.

It seems that the *input* to the remote shell is in fact erased as expected (ie. after I hit `<return>` in the above scenario, the shell behaves as if it got an empty line). So it is just a problem with echoing. Backspacing works ok in a local shell.

**Comment by nobrowser** [comment]
> This is addressed in the kitty FAQ

Really? Can you give me a specific link?

If you mean the one about terminfo not available on the remote, I can assure you I had taken care of  that before trying to connect.

**Comment by kovidgoyal** [comment]
On Thu, Jun 09, 2022 at 08:24:02PM -0700, Ian Zimmerman wrote:
> > This is addressed in the kitty FAQ
> 
> Really? Can you give me a specific link?
> 
> If you mean the one about terminfo not available on the remote, I can assure you I had taken care of  that before trying to connect.

If you had actually taken care of that you wouldnt have this problem.
