### ISSUE TITLE
Backspace while SSH'ed displays as a space

### ISSUE THREAD

**Issue by matt-boris** [kovidgoyal/kitty#5189]
**Describe the bug**
During an SSH session, all backspace (delete) keys are _displayed_ as additional spaces, but all the correct keys are still being sent to the device you're SSH'ed into, despite what `kitty` displays.

**To Reproduce**
1. SSH onto a separate machine (in my case, this is a Raspberry Pi)
2. Type some characters, such as `echo test`
3. Go to delete the word `test`
4. See how the command now shows `echo test____` (underscores representing additional spaces)
5. If you run this now, you'll notice it's essentially running the command `echo` with no args, suggesting the correct keys are still being passed to the device

**Screenshots**
![image](https://user-images.githubusercontent.com/92693437/173080606-916533b3-7877-4239-8119-5905cc3ff935.png)

In the first case, I wrote out `sudo apt update` then deleted the `e`, then added it back and you can see the command worked. Last line I started with `sudo apt`, deleted it all, then put `man grep`, deleted that too, then did `echo "test"` and you can see it echoed out `test`.

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin Matts-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                mboris

```

**Additional context**
Can reproduce with `kitty --config NONE` as well.

**Comment by matt-boris** [comment]
After changing the `TERM` variable with `export TERM=xterm-256color`, the issue is no longer reproducable.

**Comment by kovidgoyal** [comment]
This is addressed in the kitty FAQ.
