### ISSUE TITLE
On-Screen Keyboard Not Showing Predictions

### ISSUE THREAD

**Issue by levone1** [kovidgoyal/kitty#5191]
**Is your feature request related to a problem? Please describe.**
maybe - no predictions show when using screen keyboard in kitty, (but it's not just kitty).
**Describe the solution you'd like**
predictions would show 
**Describe alternatives you've considered**
just be ok with it
**Additional context**
e.g. Tilix, (or Mate Term, et al):

![Screenshot_20220610_001](https://user-images.githubusercontent.com/43003405/173084730-ff82995a-3d24-485b-acdf-ea85bd4aecd9.png)

and Kitty, (et al):

![Screenshot_20220610_003](https://user-images.githubusercontent.com/43003405/173084871-8158bad3-e112-40eb-ad55-e02c712b4aa6.png)

In general, I've seen that some apps and certain situations will show suggestions, and some not. I don't know what makes the difference, but wish I could have it in Kitty...
Thanks

**Comment by kovidgoyal** [comment]
kitty doesnt draw the onscreen keyboard so I have no idea what I can do
here.

**Comment by kovidgoyal** [comment]
try contacting the developers of the keyboard app, maybe they can tell us what's needed. It might be some wayland protocol or the other.
