### ISSUE TITLE
cursor size is not proportional to font size on wayland gnome

### ISSUE THREAD

**Issue by vbauerster** [kovidgoyal/kitty#5197]
I just installed kitty (version 0.25.2) on fresh arch linux (gnome on wayland) and its cursor size is not proportional to font size, see screenshot below:

![Screenshot from 2022-06-15 11-28-10](https://user-images.githubusercontent.com/2206533/173758710-9c23fa01-7d88-41ea-97a2-ea7a957ca586.png)

I have no custom kitty.conf so it's default behavior. Also I tried launching kitty like `XCURSOR_SIZE=8 kitty` with different numbers, but nothing is changing.

**Comment by kovidgoyal** [comment]
I dont see a mouse cursor in your screenshot, which is what XCURSOR_SIZE
controls. If you mean the text cursor, that is the size of a cell. The
font you are using defines lots of space below the baseline. Use a
different font whose metrics you prefer.

**Comment by vbauerster** [comment]
Sorry for that I'm new to kitty, changing font fixed it. Thanks for explanation.
