### ISSUE TITLE
Unicode character messes up other character's order in a word

### ISSUE THREAD

**Issue by ziontee113** [kovidgoyal/kitty#5200]
**Describe the bug**
We have these Unicode characters:
```
["for_statement"] = "ﭜ",
["while_statement"] = "ﯩ",
["switch_statement"] = "ﳟ",
```
When they are in the same "word" as other characters, they mess up (reverse) the characters' order.

**Screenshots**
![Screenshot from 2022-06-16 17-51-34](https://user-images.githubusercontent.com/102876811/174067093-62f71854-6025-40d8-adc0-feceed3d7d40.png)

There is a short video on this reddit post describing this issue:
https://www.reddit.com/r/neovim/comments/vdj04k/bizarre_unicode_character_visual_bug_when_using/

**Comment by kovidgoyal** [comment]
That's because they are RTL characters. Dont use RTL characters as symbols. If you really want to do that, add force_ltr yes to kitty.conf.

**Comment by ziontee113** [comment]
Thank you @kovidgoyal , it worked. Thank you for the amazing program :)
