### ISSUE TITLE
Make `kitty.app/lib/kitty/terminfo` accessible to all users

### ISSUE THREAD

**Issue by demicuz** [kovidgoyal/kitty#5201]
As described [here](https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo) in the FAQ, you can fix strange behavior of some keys when using `sudo`. It works with just `sudo`. But if you try to log in as another user (e.g. `sudo -i -u postgres`) and Kitty is installed locally, `terminfo` is not accessible, so that fix doesn't work.

A solution could be to Install by default in `/opt` or some other directory, accessible to all users.

**Comment by kovidgoyal** [comment]
su or sudo are typically used to run as root. root can read all
directories. The problem as described in the FAQ is they dont pass
through the TERMINFO variable. There is nothing kitty can do about that.
