### ISSUE TITLE
Is there any option like initial_window_position?

### ISSUE THREAD

**Issue by liuyinz** [kovidgoyal/kitty#5204]
Machine: Macos 12.4

@kovidgoyal 

I would like to use it in quake way, so I prefer to call the kitty.app and initalize it's position on top half  of the screen.
However, there isn't any option to customize it, only size could be initialised. Every time I choose `New OS window`, it appear in the middle of my screen. `kitty --start-as` is for size only, too.
```
# window
remember_window_size  no
initial_window_width  1440
initial_window_height 450
```
By the way, another question, I press `cmd+ctrl+t` to show or hide the kitty window, how could I change the keybindings?
If I hide the kitty from tasks , the keybinding would failed.
```
macos_hide_from_tasks yes # cmd+ctrl+t  from here
```
Thanks.

**Comment by kovidgoyal** [comment]
dup of #45
