### ISSUE TITLE
GL test isn't detecting an unsupported configuration

### ISSUE THREAD

**Issue by jamessan** [kovidgoyal/kitty#521]
In https://github.com/kovidgoyal/kitty/commit/f7e84df33278eacdfd17d97daac4352ea3a6055c you added detection for reporting when the OpenGL support isn't sufficient.  However, in https://bugs.debian.org/897381 the user is seeing the same "GLX: Failed to create context: GLXBadFBConfig" error.

Their glxinfo summary is:

```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ironlake Mobile  (0x46)
    Version: 17.3.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 17.3.6
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

which seems to be similar to #258.  Are there additional checks that can be done to provide a more useful error to the user?

**Comment by kovidgoyal** [comment]
That indicates the code to get the gl version is not working. That comes from https://github.com/Dav1dde/glad see the find_coreGL function in gl-wrapper.c which in turn comes from https://github.com/Dav1dde/glad/blob/master/glad/lang/c/loader/gl.py#L183

Presumably on this user's system, glGetString(GL_VERSION) is returning something unexpected by the version parsing code. Not sure what I can do about it. If you can get the string that it returns on that system, it should be easy to fix the parsing code in glad, and hence in kitty. It's kind of insane that there is no more reliable way to get opengl versions. I tried using the API described here: https://www.khronos.org/opengl/wiki/OpenGL_Context#OpenGL_version_number

and it returned incorrect versions on my system which is presumably why glad does not use it.

**Comment by jamessan** [comment]
Would it be possible to add some diagnostics into kitty, possibly in "kitty --debug-gl", so that there's at least a way to collect the necessary information from users?

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/f69ed984a4214f4c37510efb03942256f9055d0d

**Comment by jamessan** [comment]
Unfortunately, `--debug-gl` doesn't seem to work in this situation.  Another user [followed up](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897381#29) on the bug and `kitty --debug-gl` simply reported:

```
$ kitty --debug-gl 
[198 20:29:21.578824] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig 
[198 20:29:21.578907] Failed to create GLFW temp window!
```

---
```
$ glxinfo -B 
name of display: :0 
display: :0  screen: 0 
direct rendering: Yes 
Extended renderer info (GLX_MESA_query_renderer): 
   Vendor: Intel Open Source Technology Center (0x8086) 
   Device: Mesa DRI Intel(R) 965GM  (0x2a02) 
   Version: 18.1.4 
   Accelerated: yes 
   Video memory: 384MB 
   Unified memory: yes 
   Preferred profile: compat (0x2) 
   Max core profile version: 0.0 
   Max compat profile version: 2.1 
   Max GLES1 profile version: 1.1 
   Max GLES[23] profile version: 2.0 
OpenGL vendor string: Intel Open Source Technology Center 
OpenGL renderer string: Mesa DRI Intel(R) 965GM  
OpenGL version string: 2.1 Mesa 18.1.4 
OpenGL shading language version string: 1.20 

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.1.4 
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

**Comment by kovidgoyal** [comment]
I dont think anything can be done about that. The problem is glad can only be loaded after glfw initialization succeeds as it requires an active opengl context and there is no way to use opengl functions in kitty without it. The proper place for extended error reporting for this would be glfw, not kitty.

**Comment by kovidgoyal** [comment]
This might help a little https://github.com/kovidgoyal/kitty/commit/e7cc654bb4728357e5ad9a70c9cc3eab2d64d3bb
