### ISSUE TITLE
Run show_key in the background, outputting to a file

### ISSUE THREAD

**Issue by carrascomj** [kovidgoyal/kitty#5213]
**Is your feature request related to a problem? Please describe.**
Displaying key presses (for instance with [screenkey](https://gitlab.com/screenkey/screenkey)) in Wayland has to be either implemented by the window or provided by the compositor, which is not the case for Gnome (from what I understand).

**Describe the solution you'd like**
Since the functionality is already there, I would like to run the kitten `show_key` in the background, writing to a file. This way I could maybe pipe it to another program that shows it in the screen somehow. I have tried 

```bash
kitty +kitten show_key > log.txt &
```

but the program simply gets suspended automatically.

**Describe alternatives you've considered**
It is really not a kitty problem, so I guess this could/should be implemented by a code editor or the actual wayland gnome compositor, but maybe there is an easier workaround that I can use from kitty.

**Comment by kovidgoyal** [comment]
show_key runs inside a terminal and interprets escape codes coming over
a tty pipe and displays them. It cant be used to intercept keys presses
going to another process.
