### ISSUE TITLE
Add ability to hide cat emoji from title bar (non native window decorations)

### ISSUE THREAD

**Issue by Philipp-Codes** [kovidgoyal/kitty#5215]
**Is your feature request related to a problem? Please describe.**
As far as I know there is no config entry option to disable the cat emoji that is displayed in the title bar in top left hand corner of kitty windows with non native windows decorations (on Wayland) yet. 
This cat emoji does not go well with how I set up my terminal visually and I think kitty users should have a way to hide it if desired. 

**Describe the solution you'd like**
Please add an option in the config that makes it possible to hide the cat emoji from the title bar.

**Describe alternatives you've considered**
An alternative for me personally would be to provide an option to hide the title bar but retain the ability to resize a terminal window somehow. 
Right now disabling window decorations also makes it impossible to resize the window.
However I don't know if this is even possible. 

**Additional context**
[Screenshot](https://i.redd.it/rys757m78d591.png)
Fedora 36 | Gnome 42 | Wayland | Mutter
I'm not too sure but I think the cat emoji is hard-coded in [[kitty/glfw.c] at line 518](https://github.com/kovidgoyal/kitty/blob/80ad596d3db0c1181d93b5bdbdb3fc44f09196bc/kitty/glfw.c#L518)

**Comment by kovidgoyal** [comment]
Use fontconfig to map that symbol to a font that renders it as text or doesnt render it at all. Or better use a decent Wayland DE rather than GNOME.
