### ISSUE TITLE
UPDATE DOCUMENTATION: Use /bin/bash as shell in kitty

### ISSUE THREAD

**Issue by theasteve** [kovidgoyal/kitty#5222]
**DOCUMENTATION:**

Currently in the Kitty advance documentation there is an **Advance** section with a subsection for `shell` ([shell documentation](https://sw.kovidgoyal.net/kitty/conf/?highlight=shell#advanced)

However, it can be improved by adding code snippets or guidance on how to configure.

**PROBLEM**

I would like to use `/bin/bash` as my shell when using Kitty. I would also like to not have to run `/bin/bash --login` in every new tab. When I run `echo $SHELL` in the Kitty terminal I get:
```
$ echo $SHELL
/bin/sh
```
Even after setting in the kitty.conf the shell to:
```
shell /bin/bash --login
```
After adding the configuration to kitty.conf, I still need to manually run `/bin/bash --login` in the terminal session.

**SOLUTION**
To be able to set shell to `/bin/bash` via the kitty.conf file with `--login` and find how to in the documentation.

**Comment by kovidgoyal** [comment]
I cannot replicate

kitty --config=NONE -o 'shell=/bin/bash --login'

works fine.
