### ISSUE TITLE
Kitty doesn't run on Python 3.11.0b3

### ISSUE THREAD

**Issue by Nanotwerp** [kovidgoyal/kitty#5223]
**Describe the bug**
Kitty fails to run, giving the error

> Fatal Python error: Unknown value for option -X
 Python runtime state: preinitialized

**To Reproduce**
1. Attempt to run Kitty
2. Experience this error!

I'm thinking that maybe a value for the -X option that's used in Kitty was deprecated in this recent update, maybe.

**Comment by kovidgoyal** [comment]
This is a bug in python 3.11

Quoting from their own documentation https://docs.python.org/3.11/using/cmdline.html#cmdoption-X

"It also allows passing arbitrary values and retrieving them through the
sys._xoptions dictionary."

kitty uses this facility. Report the bug to the python developers.

**Comment by kovidgoyal** [comment]
https://github.com/python/cpython/issues/89608
