### ISSUE TITLE
Kitty is not rendering any of the nerdfonts glyphs correctly

### ISSUE THREAD

**Issue by hrqmonteiro** [kovidgoyal/kitty#5224]
**Describe the bug**
Kitty is not rendering any of the nerdfonts glyphs correctly

**To Reproduce**
1. Just try to set a nerd font and watch the glyphs

**Screenshots**

Here's FiraCode Nerd Font on Kitty:
![Screenshot from 2022-06-22 22-31-51](https://user-images.githubusercontent.com/17055027/175188284-6538b21a-f6c2-4bae-86ed-a55ca8e19cbe.png)

And here's on Wezterm:
![Screenshot from 2022-06-22 22-34-02](https://user-images.githubusercontent.com/17055027/175188410-dac586ee-3a56-4f18-9dec-24d1edc6379c.png)

**Environment details**
```
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/minutrade/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_background      Color(red=248, green=248, blue=242)
active_tab_foreground      Color(red=40, green=42, blue=54)
adjust_column_width        -1
adjust_line_height         3
background                 Color(red=46, green=52, blue=64)
cursor                     Color(red=248, green=248, blue=242)
cursor_text_color          None
draw_minimal_borders       False
font_family                FiraCode Nerd Font
font_size                  13.5
foreground                 Color(red=216, green=222, blue=233)
inactive_tab_background    Color(red=98, green=114, blue=164)
inactive_tab_foreground    Color(red=40, green=42, blue=54)
mark1_background           Color(red=255, green=85, blue=85)
mark1_foreground           Color(red=40, green=42, blue=54)
single_window_margin_width FloatEdges(left=0.0, top=0.0, right=0.0, bottom=0.0)
update_check_interval      0.0
window_border_width        (0, 'pt')
window_padding_width       FloatEdges(left=14.0, top=2.0, right=14.0, bottom=2.0)

This debug output has been copied to the clipboard
```

**Additional context**
Same thing happens with minimal config

**Comment by kovidgoyal** [comment]
Renders fine for me, as is noted in the FAQ DO NOT USE PATCHED FONTS. https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by hrqmonteiro** [comment]
> Renders fine for me, as is noted in the FAQ DO NOT USE PATCHED FONTS. https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

What do you mean "is fine for me?" 

I am using the same font for years, and i never had problems with Nerd Fonts. This time, when i updated my Ubuntu, this version of kitty started not rendering any of them correctly.

So.. Any help, please??

**Comment by kovidgoyal** [comment]
Seems pretty clear, NERD fonts render fine for me, with all versions of kitty going back at least 4 years. All the help you need with using them is in the FAQ entry I linked for you. Read it.
