### ISSUE TITLE
Glyphs lose the 1:2 aspect ratio when zooming out, causing streatching artifacts.

### ISSUE THREAD

**Issue by cloud11665** [kovidgoyal/kitty#5226]
**Describe the bug**
Glyphs lose the 1:2 aspect ratio when zooming out, causing streatching artifacts on terminal video players (mpv)

**To Reproduce**
1. Load up mpv with `-vo=tct`
2. Zoom out
4. See squashed image

**Screenshots**
* 7x15 glyphs
![kitty_2](https://user-images.githubusercontent.com/59028866/175282737-f96e104a-07b6-4791-bde7-1ea3ee7785f4.png)
* 6x11 glyphs
![kitty_1](https://user-images.githubusercontent.com/59028866/175282839-fd42fd90-a543-4f65-9b08-9f3ba9f2abbd.png)

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux mokou 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64
Ubuntu 22.04 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0
```

**Additional notes**
The image is quantized using an experimental algorithm for the upcoming sextant+ mpv blitter that uses a nonlinear layout:
![image](https://user-images.githubusercontent.com/59028866/175283156-8262e22d-ac42-4f4f-b8e5-6e35baa3b81a.png)

**Possible fixes**
1. Make scaling keep the 1:2 aspect ratio.
    - *This would greatly limit the scaling steps, and would be a net negative for the average user*
2. Add a way to query the glyph size (in pixels).
    - *This would add yet another escape sequence, but wouldn't impact average users' workflow and would add a way for the rasterizer to compensate for the squashing*

**Comment by kovidgoyal** [comment]
the aspect ratio is not fixed at 1:2, indeed if your blitter is relying on that, you will find issues with it in many terminal emulators. As for querying the aspect ratio, you can do that already without even needing an escape code. Just use TIOCGWSZ, see https://sw.kovidgoyal.net/kitty/graphics-protocol/#getting-the-window-size  

There is also an escape code for it described at the link above.

Finally, why not just output actual pixels using the graphics protocol. No need for all these headaches.
