### ISSUE TITLE
Setting ZSH terminal title has stopped working on MacOS.

### ISSUE THREAD

**Issue by Louis-C-Leon** [kovidgoyal/kitty#5228]
**Describe the bug**
I like to have my terminals named after the current directory, so that I can tell them apart at a glance in the tab bar. I have been using the solution that I found in this older issue: https://github.com/kovidgoyal/kitty/issues/930
I added the line: `precmd () {print -Pn "\e]0;%1d\a"}` to my .zshrc, and this worked as I expected to set the title.

I recently had to do a factory reset of my MacBook and re-install my dev software. After the reset, my terminal titles are not being set. They show the FULL directory path if no processes are running, and the process name if something is running.

When I use the default MacOS terminal, the window title is set to what I want: the current working directory, without the full path. When I use Kitty with the same `kitty.conf` file on my Linux machine, the title is also set correctly.

**To Reproduce**
1. Install kitty (using Homebrew) on a new MacOS Monterey install.
2. Add `precmd () {print -Pn "\e]0;%1d\a"}` to .zshrc file
3. Source .zshrc file
4. Windows are not renamed as expected.

**Screenshots**
Here is my current tab title config, and the tab bar. 
`tab_title_template " {index}:{title}({num_windows}) "`

<img width="595" alt="Screen Shot 2022-06-24 at 10 16 30 AM" src="https://user-images.githubusercontent.com/45052872/175610684-1e921e0c-eb01-481d-ae24-8dfd9f6fe0b6.png">

**Environment details**
OS: MacOS 12.4
Kitty version: 0.25.2
ZSH version: zsh 5.8.1 (x86_64-apple-darwin21.0)

**Additional context**
I do not think this is related to the Kitty config file. I reproduced the issue using `kitty --config NONE`.

Thanks for reading! This is my first issue, so I'm sorry if I missed something here.

**Comment by page-down** [comment]
You want to disable the title from the shell integration.

```
shell_integration no-title
```

https://sw.kovidgoyal.net/kitty/shell-integration/

**Comment by Louis-C-Leon** [comment]
> You want to disable the title from the shell integration.
> 
> ```
> shell_integration no-title
> ```
> 
> https://sw.kovidgoyal.net/kitty/shell-integration/

Thanks a ton! I didn't see that option before.
