### ISSUE TITLE
Background emacs client editor fail to redraw after moving to foreground

### ISSUE THREAD

**Issue by nonamestreet** [kovidgoyal/kitty#5234]
**Describe the bug**
If two or more emacsclient editors runs in backgound, activating some of the backgound editor would make the terminal window blank.
It only affects emacsclient, but not standalone emacs editor.

**To Reproduce**
1. Run "emacsclient aaa", and press Ctrl-Z to send it to background as job 1
2. Run "emacsclient bbb", and press Ctrl-Z to send it to background as job 2
3. do a "fg" to bring up job2 and exit the emacs client (ctrl-x ctrl-c).
4. do a "fg" to bring up job1 and the terminal turn blank. If you press any key or swich window focus, the terminal redraw and return to normal.

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux lin-desk 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64
Ubuntu 22.04 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/sunlin/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color     Color(red=128, green=128, blue=128)
active_tab_background   Color(red=30, green=30, blue=63)
active_tab_foreground   Color(red=199, green=199, blue=199)
background              Color(red=30, green=30, blue=63)
cursor                  Color(red=199, green=199, blue=199)
editor                  emacs -nw
enable_audio_bell       False
font_family             MonoLisa
foreground              Color(red=199, green=199, blue=199)
inactive_border_color   Color(red=67, green=212, blue=38)
inactive_tab_background Color(red=67, green=212, blue=38)
inactive_tab_foreground Color(red=104, green=113, blue=255)
selection_background    Color(red=199, green=199, blue=199)
selection_foreground    Color(red=30, green=30, blue=63)
tab_bar_background      Color(red=67, green=212, blue=38)
tab_bar_edge            1
update_check_interval   0.0
url_color               Color(red=104, green=113, blue=255)
Removed shortcuts:
	shift+ctrl+- KeyAction('change_font_size', (True, '-', 2.0))

```

**Additional context**
I have tested it with  `kitty --config NONE`, the bug still exists.

**Comment by kovidgoyal** [comment]
I dont see what this has to do with kitty. kitty will draw whatever the
client running in it asks it to draw. If the client isnt clearing the
screen, thats a bug in the client.
