### ISSUE TITLE
Inconsistent IBus cursor location commands

### ISSUE THREAD

**Issue by squili** [kovidgoyal/kitty#5241]
**Describe the bug**
When running Kitty, `SetCursorPosition` only seems to be emitted when focusing in and out of the app.
I hooked `glfw_dbus_call_method_no_reply` and I only got output when focusing out and in. Here's an example:
```
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, FocusOut)
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, FocusIn)
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, SetCursorLocation)
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, FocusIn)
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, SetCursorLocation)
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, SetCursorLocation)
glfw_dbus_call_method_no_reply(org.freedesktop.IBus, /org/freedesktop/IBus/InputContext_259, org.freedesktop.IBus.InputContext, SetCursorLocation)
```
This means that IMEs that require cursor position can only update their cursor position when a user tabs out and tabs back in

**Environment details**
```
kitty 0.25.2 (7fc1735a21) created by Kovid Goyal
Linux mia-framework 5.18.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 16 14:51:11 UTC 2022 x86_64
S
Kernel 5.18.5-200.fc36.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /home/mia/Sources/kitty/kitty/launcher/kitty
  base dir: /home/mia/Sources/kitty
  extensions dir: /home/mia/Sources/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/mia/Sources/kitty/kitty/launcher:/home/mia/.fly/bin:/home/mia/Apps/google-cloud-sdk/bin:/home/mia/.local/bin:/home/mia/.fig/bin:/home/mia/.yarn/bin:/usr/lib64/ccache:/home/mia/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/mia/.fig/bin:/home/mia/.local/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /usr/bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :1
	USER                                mia
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/mia/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

**Additional context**
I'm using the Fig for Linux alpha - this could be messing with something, as it starts a shim layer called figterm that intercepts events. LMK if you have trouble reproducing and I can get you a copy of the alpha.

**Comment by kovidgoyal** [comment]
As I recall this is done deliberately, since some IMEs on Linux tend to move
their window with every key press. On macOS, IME position is updated
with every key press, on Linux only on focus change and when the text
input system sends some preedit text. See the calls to
update_ime_position() in keys.c 

And note you dont need to use dbus to monitor it. Indeed under wayland
dbus is not used at all. Instead run kitty with --debug-input

**Comment by squili** [comment]
Are you sure that's the standard? We use this method for all other terminals to get the required data (specifically under X11, hence me monitoring dbus).

**Comment by kovidgoyal** [comment]
There is no standard, this was simply what users reported worked best
with the widest variety of IME methods. And who is we, here? What are
you trying to accomplish?

**Comment by squili** [comment]
We is [Fig](https://fig.io). We need the cursor position data in order to position things correctly. Without constant updates to the cursor location, as is what happens in most supported terminals, the window position lags behind. In Kitty's case, this results in the autocomplete window only being correctly positioned when the terminal window goes out of then back into focus.

**Comment by kovidgoyal** [comment]
Interesting, how are you planning to make this work with Wayland where
random processes cannot intercept key events?

**Comment by squili** [comment]
We have an interceptor that goes between your shell and the terminal that processes keystrokes and context data. We actually do have support for wayland on one platform - sway - though wayland support elsewhere is much more work due to missing standards.

**Comment by kovidgoyal** [comment]
On Tue, Jun 28, 2022 at 10:24:00PM -0700, Mia wrote:
> We have an interceptor that goes between your shell and the terminal that processes keystrokes and context data.

That wont give you position information, though.

> We actually do have support for wayland on one platform - sway - though wayland support elsewhere is much more work due to missing standards.

Out of curiosity, what protocol are you using in sway to achieve this?

And coming back to the topic at hand, I am not very inclined to cause
regressions for IME users in order to support a non-IME use case. 

Also I'd like to fix this properly for both X11 and Wayland, i.e.
independent of relying on windowing system/IBUS. What happens if the
user is using a different IME system? I have a feeling you will be
dealing with support issues forever if you try to make it work with
existing infrastructure. 

The obvious solution would be to simply report IME events to a socket or
via dbus to some address on the session bus, when available.

**Comment by squili** [comment]
To clarify, we're using an ibus engine, not an ibus client, to extract the data. I assume ibus engines will be allowed to know caret positioning in wayland as well.

> That wont give you position information, though.

I must have misinterpreted. We get caret positioning through ibus on wayland as well.

> Out of curiosity, what protocol are you using in sway to achieve this?

For caret positioning, ibus - but, for the thing sway has that others don't, there's a protocol we need to get the current focused window to decide when to show/hide autocomplete

> And coming back to the topic at hand, I am not very inclined to cause regressions for IME users in order to support a non-IME use case.

Could you link to some of the issues that the typical solution causes? If not too hard, would it be possible to add a config option for this?

> What happens if the user is using a different IME system?

We can expand to using other protocols in the future, but for now we require ibus. If you need another IME system, they you can install that as well

> I have a feeling you will be dealing with support issues forever if you try to make it work with existing infrastructure.

The way I see it, the most probable outcome of trying to push a new protocol onto everyone is adding yet another competing protocol to the mix. We don't want to make the Linux ecosystem more complex.

> The obvious solution would be to simply report IME events to a socket or via dbus to some address on the session bus, when available.

If you mean to send caret positioning data directly to Fig, we have a system for that. If you'd like, I can give you info on that.

**Comment by brendanfalk** [comment]
Hey @kovidgoyal - we are planning on launching Fig for Linux very soon. Would love to have Kitty as one of the supported terminals in the announcement.

Any update on when the next build will be released?

**Comment by kovidgoyal** [comment]
I dont have a timeline, basically, just waiting for some testing for the
new prewarm feature, see the RFC issue.

**Comment by kovidgoyal** [comment]
On Tue, Jun 28, 2022 at 10:49:04PM -0700, Mia wrote:
> To clarify, we're using an ibus engine, not an ibus client, to extract the data. I assume ibus engines will be allowed to know caret positioning in wayland as well.

So you mean you run whatever the users actual IBUS engine is behind the
scenes and intercept traffic to it?

> 
> > That wont give you position information, though.
> 
> I must have misinterpreted. We get caret positioning through ibus on wayland as well.
> 
> > Out of curiosity, what protocol are you using in sway to achieve this?
> 
> For caret positioning, ibus - but, for the thing sway has that others don't, there's a protocol we need to get the current focused window to decide when to show/hide autocomplete
> 
> > And coming back to the topic at hand, I am not very inclined to cause regressions for IME users in order to support a non-IME use case.
> 
> Could you link to some of the issues that the typical solution causes? If not too hard, would it be possible to add a config option for this?

I reviewed it and I cant find any issues beyond https://github.com/kovidgoyal/kitty/issues/4849
which inclines me towards allowing cursor position updates on linux as
well as macOS. Might be worth turning it on and seeing if people
complain and then re-visiting.

**Comment by squili** [comment]
> So you mean you run whatever the users actual IBUS engine is behind the
scenes and intercept traffic to it?

What we do now is we ensure that IBus is running and then intercept the reports that applications give to IBus over DBus

> I reviewed it and I cant find any issues beyond [#4849](https://github.com/kovidgoyal/kitty/issues/4849)
which inclines me towards allowing cursor position updates on linux as
well as macOS. Might be worth turning it on and seeing if people
complain and then re-visiting.

It has been working great on Linux since the change, but MacOS is not my area of expertise

**Comment by YerongLi** [comment]
Did you find a fix?

I encountered a similar error and input bar appears at the left-bottom corner of the screen.
![Screenshot from 2023-03-26 15-34-11](https://user-images.githubusercontent.com/13112023/227803271-79bb13fb-ad79-4a9e-b135-530c11f34fe9.png)
