### ISSUE TITLE
MonoLisa only italic

### ISSUE THREAD

**Issue by Davincible** [kovidgoyal/kitty#5242]
I know kitty only supports mono fonts, but was surprised to only see the italic variants of [MonoLisa](https://onehack.us/t/get-monolisa-font-for-free-1/94692) are supported. 

```bash
$ kitty list-fonts | grep -i lisa
MonoLisa
    MonoLisa-BlackItalic
    MonoLisa-BoldItalic
    MonoLisa-ExtraLightItalic
    MonoLisa-LightItalic
    MonoLisa-MediumItalic
    MonoLisa-RegularItalic
    MonoLisa-ThinItalic
```

Is this something that can be fixed?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
