### ISSUE TITLE
exit command hangs up

### ISSUE THREAD

**Issue by CarloCattano** [kovidgoyal/kitty#5243]
**Describe the bug**
exit doesnt work

1. Open kitty
2. do your work 
3. type exit
4. Hangs up and requires forced close

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux x 5.15.44-1-rt46-MANJARO #1 SMP PREEMPT_RT Mon Jun 6 13:47:12 CEST 2022 x86_64 GNU/Linux
KDE plasma

```

![image](https://user-images.githubusercontent.com/17380530/176374254-188f4bfe-4dac-47b0-a800-435c9428cf2c.png)

![image](https://user-images.githubusercontent.com/17380530/176374335-f19efccc-3a6c-4004-ae55-1ec4f842abee.png)

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. 

Happens also with config NONE

**Comment by page-down** [comment]
If there are still background processes running, the window will not be closed.
The following config option can change this. However the background processes will still be running, see the description.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death

I would suggest looking at the process tree to find out what that is and handle it properly.

**Comment by CarloCattano** [comment]
Got it ! Its cause by a script I run on my .zshrc so all good , not a problem of kitty then. Thanks for the info !
