### ISSUE TITLE
Ctrl+/ doesn't work in neovim

### ISSUE THREAD

**Issue by joesitton** [kovidgoyal/kitty#5244]
**Describe the bug**
The `<C-_>` (ctrl + /) keybind is not working in neovim, instead of doing the assigned mapping neovim tries to start a search pattern.

**To Reproduce**
1. Map `<C-_>` to something
2. Press `<C-_>` 
3. ???

**Environment details**
```
kitty 0.25.2 (4f8ef05058) created by Kovid Goyal
Linux zeta 5.18.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:03 +0000 x86_64
Arch Linux 5.18.7-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/joe/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style   (False, False)
background_opacity      0.98
disable_ligatures       2
enable_audio_bell       False
font_family             Iosevka Custom
font_size               16.5
```

**Comment by kovidgoyal** [comment]
So report it to neovim. Running showkey -a in kitty shows that kitty
sends the correct bytes for it.

**Comment by joesitton** [comment]
I mean, sure, but I've tested other terminals and kitty is the only one that has an issue

**Comment by kovidgoyal** [comment]
Report it to neovim, I dont know how many way to say the same thing. kitty produces the correct bytes for that keypress. neovim is obviously turning on the enhanced keyboard protocol and then misinterpreting the results. alacritty doesnt even have an enhanced keyboard protocol to turn on.
