### ISSUE TITLE
Broken keypad input in Neovim with kitty

### ISSUE THREAD

**Issue by isopropyletherperoxide** [kovidgoyal/kitty#5245]
Hello! The Enter key on my laptop's keyboard is broken, therefore I'm using my keypad enter key, but recently I've ran into an issue using it in neovim in kitty, whenever I press it with numlock off, all i get in insert mode and normal mode is an  "(æ)" character, and with numlock on the key does not register whatsoever. 
The issue is not in my config and not in neovim, as it has the same issue with default configs. The key in neovim is completely functional in other terminals like WezTerm, Alacritty, Konsole and urxvt.

SPECS: 
OS: Arch Linux x86_64
Kernel: 5.18.7-arch1-1 
Neovim Version: v0.7.2
Kitty Version: 0.25.2

**Comment by kovidgoyal** [comment]
Yes that will be because neovim has enabled kitty's extended keyboard
protocol without actually supporting it fully. Report it to them.
