### ISSUE TITLE
Remote color commands not always changing tabs background

### ISSUE THREAD

**Issue by Davincible** [kovidgoyal/kitty#5246]
**Describe the bug**
Setting terminal colors with `kitty @ set-colors -a -c ./somepath/colors-kitty.conf` works. However, I am running this command in a post-script after changing my background and colorscheme.

The problem I am seeing is that when executed from this postscript, my terminal background color successfully changes, but not my tab bar background color.

However, when I run this same command from within a kitty tab, it all works fine.

Any idea why tab background color would change with the one but not the other? while the rest of the color-changing works fine for both.

**To Reproduce**
Run kitty set colors in a wpg/pywal post script

I start my terminals with `kitty --single-instance --listen-on='unix:/tmp/kitty.sock'`, and have remote control enabled in settings.

Version: `kitty 0.25.2`

**Comment by page-down** [comment]
I cannot reproduce the issue with the following commands.

```shell
```

**Comment by kovidgoyal** [comment]
Does not reproduce for me either and I dont see how it's possible, since
the code path for changing colors is the same in either case.  Make sure
you are using the correct --to argument.
