### ISSUE TITLE
Can't open Kitty via .desktop in Enlightenment

### ISSUE THREAD

**Issue by delkano** [kovidgoyal/kitty#525]
I have recently switched to Enlightenment as a desktop environment, and I've found out that I not longer can launch Kitty from the menus or launcher. It works if I open any other terminal and then write `kitty` in them.

This is the only software it happens, which kind a makes it a Kitty issue, but it only happens on Enlightenment, so it could be an issue with the DE. 
I honestly don't even know where to look. It doesn't give any error message (other than "exit code 1"). 

Kitty v.0.9.1
Enlightenment v.0.22.3

**Comment by kovidgoyal** [comment]
I'm not an enlightment user, so I have no iea how to debug it. Typically look at ~/.xsession-errors though I have no idea whether enlightenment respects that convention or not. If not then create a wrapper script to run kitty that redirects stdout/stderr to a file and use that to debug.

In any case, you can editing the kitty desktop file changing the Exec key to

```
kitty --detach
```

which should make kitty more robust against whatever is broken in enlightenment.

**Comment by delkano** [comment]
There's no output at all (even with the wrapper) and nothing about Kitty in the logs besides the exit code.

**Comment by kovidgoyal** [comment]
In that case I doubt kitty is running at all. Most likely the PATH that enlightenment is using is different from the PATH in your shell and something else called kitty is running. Use an absolute path in the  .desktop file to fix that.

**Comment by delkano** [comment]
That'd be weird since it's in /usr/bin, as most other binaries. In any case, even after switching to an absolute path, it doesn't change anything. 
I'll keep looking for... not answers yet, maybe the right question, since I have nothing; and report it here if I manage to find the reason.

**Comment by kovidgoyal** [comment]
I dont know of any way that kitty would just quit without printing ome error message. But just because I dont know of it, doesn't mean it does not exist. You can try the --debug-gl argument to make it report any erorrs from OpenGL but I doubt it is even getting that far.

**Comment by kovidgoyal** [comment]
Kitty does not use Qt so those lines are not coming from it.

**Comment by prototype99** [comment]
yeah i didn't think so but it was worth a try. i'm going to try and find out how kmenu launches applications, because that can't do it, but then launching it in konsole works perfectly fine

**Comment by zx9w** [comment]
I have the same problem in xmonad on nixos, can only launch kitty from another terminal. I'm not sure how to troubleshoot, I tried to take a look at my path and $PATH has the location that 'which kitty' gives me.

Launchers work for all other programs btw, only kitty has this problem but once I launch it from xterm it behaves fine and works well (after I did the black magic thing with 'export LC_ALL=C').

**Comment by nroi** [comment]
I ran into a similar issue with i3 and the `dmenu_run` launcher. In my case, the problem was that `EDITOR` was defined only in my `~/.zshrc`, not in `~/.xprofile`. So I was able to run kitty from another terminal like `xterm` (which runs zsh and sources `.zshrc`), but I wasn't able to run it with the launcher.
Make sure that `EDITOR` is defined in whatever file is sourced by your display manager, or put something like this in your `PATH` and try to run it with the launcher:
```bash
#!/bin/sh

export EDITOR='/usr/bin/vim'
exec /usr/bin/kitty
```
