### ISSUE TITLE
Pasting bug if PS1 has ASCII Color Escape Codes

### ISSUE THREAD

**Issue by ShadiestGoat** [kovidgoyal/kitty#5251]
**Describe the bug**
Pasting any text which is at least 11 in length (eg. `FooBarFooBa`) into kitty causes a weird displacement. The interesting part is that the length of the minimum string to paste depends on the length of PS1. So, in the minimal example I use, `\033[30m\033[0m`, if not counting the `[` & the `\`, then the length is 11. If using `\033[30;1m\033[0m`, the minimum is 13. Also, this is a visual-only bug. See screenshot for reference, but you can't delete the highlighted text, and it doesn't count towards the 'input'

**To Reproduce**
1. Copy any text of 11+ characters, eg. `FooBarFooBa`
2. Set PS1 to be something like `\033[30m\033[0m`
  - This does nothing by itself, but this is a minimal reproduction of it
4. Paste the text into kitty
5. Press an arrow key to move to the right-most position
6. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/48590492/177293933-48413922-ac4c-464f-bb37-2880ff248095.png)

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux shadygoat 5.18.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 29 Jun 2022 23:03:08 +0000 x86_64
Arch Linux 5.18.8-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/shady/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.65
cursor_blink_interval 0.0
disable_ligatures     1
shell_integration     frozenset({'no-cursor'})
Colors:
	background            #000b11   
	color0                #454545   
	color1                #b35959   
	color10               #99ffcc   
	color11               #ffcc99   
	color12               #99b8ff   
	color13               #f799ff   
	color14               #99ffff   
	color2                #59b386   
	color3                #cc8e5c   
	color4                #5974b3   
	color5                #ab59b3   
	color6                #59b3b3   
	color7                #999999   
	color8                #808080   
	color9                #ff9999   
	cursor                #ffffff   
	foreground            #ffffff   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/home/shady/go/bin:/opt/android-ndk:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/home/shady/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/shady/go/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                shady
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_GB.UTF-8
```

**Additional context**

This is reproducible in `kitty --config NONE`. Also, side note but `urxvt-unicode` has the same bug

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. pasting simply writes the pasted
bytes to the stdin of the process running in the terminal, which in your
case is bash. What the process chooses to do with it after that is not
upto the terminal in any fashion. I suggest you report the issue to
bash. Or use a different shell.

**Comment by ShadiestGoat** [comment]
Hmm ok, thanks!

**Comment by trygveaa** [comment]
@ShadiestGoat: With bash you have to surround non-printing characters in PS1 with `\[` and `\]`. If you don't, you'll get issues like these. See `PROMPTING` in `bash(1)`:

```
\[     begin a sequence of non-printing characters, which could be used to embed a terminal control sequence into the prompt
\]     end a sequence of non-printing characters
```
