### ISSUE TITLE
bind cmd-backspace to '^[u'

### ISSUE THREAD

**Issue by jubishop** [kovidgoyal/kitty#5255]
**Is your feature request related to a problem? Please describe.**
Historically with iTerm i was able to execute 

```
bindkey '^[u' backward-kill-line # cmd backspace
```

In my `.zshrc` file and then cmd+backspace would delete the entire line for me.

**Describe the solution you'd like**
Some `map` command in `kitty.conf` that lets me map cmd+backspace to the same '^[u' escape sequence.

**Describe alternatives you've considered**
I've searched the docs but I can't figure out how to make this work, (or if there's a better way)

**Additional context**
I have a bunch of others like this in my .zshrc file, and I'm unsure if the others all work either:

```
bindkey '\e\e[D' backward-word # alt <-
bindkey ';5D' backward-word # ctrl <-
bindkey '\e\e[C' forward-word # alt ->
bindkey ';5C' forward-word # ctrl ->
bindkey '^[a' beginning-of-line # cmd <-
bindkey '^[e' end-of-line # cmd ->
bindkey '^[w' backward-delete-word # alt/ctrl backspace
bindkey '^[u' backward-kill-line # cmd backspace
bindkey '^z' undo # undo
bindkey '^x' kill-word # cut forward to word break
bindkey '^v' yank # paste
bindkey '^t' transpose-words # swap previous two words
```

thanks so much for any help!

**Comment by jubishop** [comment]
nvm i think i solved my problem with `kitty +kitten show_key`

I noticed that for whatever reason, cmd+backspace is sending the same unix command as normal backspace, so i remapped it to the syntax for cmd+delete, then used that in zsh.

in other words:

in kitty.conf i added:

```
map cmd+backspace send_text normal,application \x1b[3;9~
```

and then in my .zshrc i put:

```
bindkey '^[[3;9~' backward-kill-line # cmd backspace
```

and that works!  thanks for the awesome shell.

**Comment by kovidgoyal** [comment]
This is described in the kitty FAQ
