### ISSUE TITLE
Kitty ignores system remapping of Option and Command keys

### ISSUE THREAD

**Issue by oyarsa** [kovidgoyal/kitty#5257]
**Describe the bug**
I have Option and Command swapped in System Preferences > Keyboard > Modifier Keys. I set Option to Command and Command to Option. However, Kitty does not recognise that. I still have to use the original Option key to use Alt shortcuts. If I use (native) Command (remapped to Option) plus another key, I get the default Option behaviour. This is not what happens with Terminal.app, which demonstrates the correct behaviour.

**To Reproduce**
I'm referring to keys as they are on the keyboard (native version):
1. In Kitty, I press Command + d and get ∂. In Terminal.app, I get the behaviour of Alt + d (kill next word)
2. In Kitty, I press Command + d and get the behaviour of Alt + d. If I press Option + d, I get the Terminal's behaviour for Command + d.

I'm sorry if this is a bit confusing, but the TL;DR is that Kitty is not recognising my swapped Option to Command key as Alt, but Terminal.app does that correctly.

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin Lurga.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/italo/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close 0
font_family             JetBrains Mono SemiBold
font_size               14.0
macos_option_as_alt     3
window_padding_width    FloatEdges(left=5.0, top=5.0, right=5.0, bottom=0)
Colors:
	background              #403e41   
	color0                  #403e41   
	color1                  #ff6188   
	color10                 #a9dc76   
	color11                 #ffd866   
	color12                 #fc9867   
	color13                 #ab9df2   
	color14                 #78dce8   
	color15                 #fcfcfa   
	color2                  #a9dc76   
	color3                  #ffd866   
	color4                  #fc9867   
	color5                  #ab9df2   
	color6                  #78dce8   
	color7                  #fcfcfa   
	color8                  #727072   
	color9                  #ff6188   
	cursor                  #fcfcfa   
	cursor_text_color       #000000   
	foreground              #fcfcfa   
	selection_background    #fcfcfa   
	selection_foreground    #403e41   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_GB.UTF-8
	SHELL                               /opt/homebrew/bin/fish
	USER                                italo

```

**Additional context**
The problem also happens with `kitty --config NONE`, with the addition that pressing the native Option key + d yields `[100;9u` instead of Alt + d.

**Comment by page-down** [comment]
I can't reproduce this.

```shell
kitty --config=NONE --debug-input kitty +kitten show_key -m kitty
```

Select the correct keyboard in `Modifier keys` and configure the modifier keys, which will take effect immediately.
The `show_key` kitten and the debug log show the modifier keys as the expected keys.
I believe this key swap is relatively low level and kitty's key handling is above that. Not sure what else would cause this.

**Comment by oyarsa** [comment]
Never mind, I completely misread the documentation on how Option/Alt behaviour worked with Kitty. I initially understood that default to be turning Option into Alt, but that's not the case. Setting `macos_option_as_alt yes` fixed my issues. 

I'm sorry for wasting your time.
