### ISSUE TITLE
Kitty v0.25.2 causes several issues on different GNOME extensions

### ISSUE THREAD

**Issue by D3vil0per** [kovidgoyal/kitty#5259]
**Describe the bug**
Hello!
For first thanks for this wonderful terminal. I switched to Kitty today and I like it a lot.

Today I was testing it in my environment, an Arch Linux (5.18.10-arch1-1) with GNOME 42 and XWayland.

In my environment, I installed three separated GNOME Extensions: Ubuntu-Dock (a branch of dash-to-dock project), Desktop Icons NG and Desktop Icons Neo.

Let's take as example Desktop Icons NG extension (https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/)

If you install and enable it, you will have Home and Trash folder appearing on the Desktop. If you install Kitty, and double click on one of these two folders, it will spawn Kitty terminal. If I remove Kitty, the extension works well and open the folders with my File Manager (Nautilus). This happens also for the other two extensions (that have different developers).

So, I'm thinking the issue should be related to the presence of Kitty. Furthermore, on the logs of these extensions (by `journalctl /usr/bin/gnome-shell -f -o cat`), while Kitty is installed, and I double click on one of these folders, I get the following log:
```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x120000f
```

**Comment by page-down** [comment]
kitty declares that it can open directory (inode/directory) resources.
Maybe you need to configure the default program for directory.

https://wiki.archlinux.org/title/Xdg-utils#xdg-mime

**Comment by kovidgoyal** [comment]
kitty advertises that it can open folders. Why your desktop environment
is defaulting to use kitty for it, only the developers of your desktop
environment can tell you. Figure out how to change file associations in
that environment and change them to whatever program you want.

**Comment by D3vil0per** [comment]
@kovidgoyal @page-down thanks guys, setting Nautilus as default solved the issue. What I don't understand is that, I did a new test on a fresh machine, and I got the same issue. Could it mean that, during the installation, kitty sets itself as default application for inode/directory?

**Comment by page-down** [comment]
> Could it mean that, during the installation, kitty sets itself as default application for inode/directory?

During installation or use, kitty will not set itself as the default, it will simply be listed as a program available for use.
It is likely to be used in environments where the user (or this OS distribution) does not explicitly specify the default program for directory.

**Comment by kovidgoyal** [comment]
kitty has no installation. It doesn't even install a .desktop file you
have to do that manually. https://sw.kovidgoyal.net/kitty/binary/ 

If you mean the kitty distro package, you will need to ask whoever
maintains that package.

**Comment by D3vil0per** [comment]
Ah ok, clear! Thanks!
