### ISSUE TITLE
Ligatures not rendered correctly when using Iosevka

### ISSUE THREAD

**Issue by MVarga12** [kovidgoyal/kitty#526]
I apologize if this is a duplicate, I didn't see anything related to it. I'm using macOS High Sierra 10.13.4 and Kitty 0.9.1 (issue existed on 0.9.0 as well). My kitty.conf is essentially stock, with only fonts changed.

The font ligatures in the Iosevka family are not being rendered properly. You can see this here:
<img width="499" alt="iosekva_kitty" src="https://user-images.githubusercontent.com/7471178/39733465-cde99f7c-5240-11e8-9ea4-29d7cc717553.png">

compared to iTerm2:
<img width="463" alt="iosevka_iterm" src="https://user-images.githubusercontent.com/7471178/39733475-d58726e6-5240-11e8-954d-574502f89c89.png">

And as a control, here is Fira Code in Kitty:
<img width="610" alt="fira_code_kitty" src="https://user-images.githubusercontent.com/7471178/39733479-de1a7f7e-5240-11e8-9b70-29c92810c2c7.png">

**Comment by kovidgoyal** [comment]
dup of #297
