### ISSUE TITLE
Kitty only recognizing the italicized version of a font

### ISSUE THREAD

**Issue by dobeye** [kovidgoyal/kitty#5261]
**Describe the bug**
when setting up my kitty.conf file I tried loading the font MonoLisa, A font I downloaded manually into my fonts folder. After reloading my kitty instance using ctrl shft f5, all the text in the conf file became italicized. I assumed this was a problem with the font I downloaded, but when trying it in both xterm and alacritty they managed to recognise the font correctly, so I'm sure this is an issue with kitty. when trying kitty +list-fonts I saw that kitty only recognized the italicised version of the font:
[dobeye@phi kitty]$ kitty +list-fonts
Fira Code
    Fira Code Bold
    Fira Code Light
    Fira Code Medium
    Fira Code Regular
    Fira Code Retina
    Fira Code SemiBold

FreeMono
    FreeMono
    FreeMono Bold
    FreeMono Bold Oblique
    FreeMono Oblique

MonoLisa
    MonoLisa-BlackItalic
    MonoLisa-BoldItalic
    MonoLisa-ExtraLightItalic
    MonoLisa-LightItalic
    MonoLisa-MediumItalic
    MonoLisa-RegularItalic
    MonoLisa-ThinItalic

**To Reproduce**
1. Download a custom font manuallly to your computer (in my case arch linux)
2. Load this font into kitty using either the config file or using kitty +list-fonts
3. See error

**Additional context**
my kitty.conf file includes the singular uncommented line
font_family MonoLisa

I have attempted to add Fonts {{{ at the beginning and }}} at the end, I tried setting the bold_font italic_font and bold_italic_font both on auto and manually, nothing seems to have helped

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

You can try MonoLisa version 1.808+ (February 28, 2022), maybe this bug has been solved.
