### ISSUE TITLE
Ability to ignore directories when using copy in the kitten ssh

### ISSUE THREAD

**Issue by mat813** [kovidgoyal/kitty#5264]
**Is your feature request related to a problem? Please describe.**
In my ssh.conf I have, for example:

```
copy --exclude .git --exclude '*.zwc' --exclude '*history' ~/.config/zsh
```

I use zim to manage the zsh plugins, and what zim does is run git clone, so in .config/zsh/.zim/modules/ I have a bunch of repositories, which I manage and update on my laptop.
The problem is that there is currently no way in the ssh kitten to ignore a directory, so when I run `kitty +kitten ssh some-server` it copies a bunch of `.git` directories, that I don't need on the remotes, and that amount for about 70% of the data transfered.

**Describe the solution you'd like**
What would be best would be `copy --exclude foo` to exclude file and directories named foo. But it would be ok to have a different option.

**Describe alternatives you've considered**
The main alternative is waiting while kitty transfer a bunch of data, and, be happy that it happens magically.  Another would be to create a local "export" of the directories I want to copy without the .git directories, but I would have to find a way to automate the updates.

**Comment by kovidgoyal** [comment]
Those are glob patterns, so use

*/.git/*

**Comment by mat813** [comment]
So, I changed my ssh.conf file from :

```
copy --exclude .git --exclude '*.zwc' --exclude '*history' ~/.config/zsh
```

to

```
copy --exclude /.git/ --exclude '*.zwc' --exclude '*history' ~/.config/zsh
```

And it does not change anything, the .git directories get transfered again on the next connection. :disappointed:

**Comment by kovidgoyal** [comment]
You forgot the asterisks.
