### ISSUE TITLE
Terminal protocol extension for changing fonts

### ISSUE THREAD

**Issue by 4e554c4c** [kovidgoyal/kitty#5268]
**Is your feature request related to a problem? Please describe.**
I use neovim in kitty, for my job, to edit all of my code. There are many neovim plugins that depend on the [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) project to show icons. I appreciate this because it makes things more user friendly, but i very much disagree with how they are implemented ([as does the maintainer of this project](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font), from what i can tell). In particular, it wants you to use a patched font (like nerd fonts) for everything in your terminal. I disagree with this on several levels, the primary of which being that
* you have to use a bloated nerd font for everything
* the nerd font overwrites glyphs not in private use

Kitty users are expected to get around this by using the standard (unpatched) nerd font, and redirecting all "nerd font glyphs" (which overwrite some already in-use codepoints) to the nerd font.

**Describe the solution you'd like**
There is a clear way around this, and that is to use an extension to the terminal protocol. For example, we could use the [terminal graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/#) to instead draw the icons on the screen.
The problem with the graphics protocol is
* the devicons project would have to define what all the icons look like
* they would not be very customizable
* they would not play nice with all colorschemes like fonts do

A solution to *these* issues would be something like a wingdings font, but how is that different than a nerd font?
The answer is that a wingdings font is only for icons, is *specifically opted-into for specific text locations which contain icons* and it doesn't matter if it uses public codepoints.
This is how icons are done on the web in many places as well. You don't just import an icon "font" for your whole website, but you label specific text elements with that font in order to show icons.  

In particular, we would need a terminal extension to set the *font* of specific pieces of text, just like we are already able to set the text decorations (color, styled overlines) of that text.

From what I can tell, these CSI codes already exist in a limited capacity. For example, [CSI codes 11-19](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters) seem already used for this purpose, we would just need a way to control them.

**Describe alternatives you've considered**
An alternative could be to use the terminal graphics protocol, outlined above

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
I dont much see the need for this. You dont need to use patched fonts
since kitty has symbol_map. You can adjust your symbol_map to only
override those glyphs you care about. As for NERD using non private use
areas that is a bug in it that I believe is slated to be fixed for NERD
3. In the meantime you can workaround it by either usong fontconfig to
give NERD the lowest fallback priority if you are on Linux or using
symbol_map to tell kitty to explicitly oad some other font for the non
private use glyphs.

Not to mention that allowing terminal programs to set fonts doesn't
really work since once this capability exists, programs will use it 
to set fonts for normal text not just symbols and then there are issues
with sizing to consider since different fonts dont have compatible
metrics and so cant be used easily in a monospaced rendering model.

And finally, you would need buy in from terminal program developers
otherwise this would just be code kitty carries around for no practical
benefit.

**Comment by 4e554c4c** [comment]
I agree that using public codepoints for NERD is a bug, but I disagree that this should be the solution even if NERD only used private use codepoints.
Private use codepoints shouldn't be necessary to show icons. Showing icons is a fairly routine job of a terminal, and shouldn't require users to give up all of their private codepoints to do so. Private codepoint use cause issues because it can necessarily cause conflicts with anything else that uses private codepoints. Thus private codepoints should only be used in niche, vendor specific environments (you can't just say "these codepoints belong to NERD" because that would require specifying them in unicode. vendor specific means vendor specific).
A great example of this I came across recently was when some weather icons used the same codepoints as fontawesome icons, which I both used. The only way to reconcile these was to use NERD which compiles them both into different codepoints, but a better option would be to specifically opt-in to the weather font or fontawesome.



> Not to mention that allowing terminal programs to set fonts doesn't
really work since once this capability exists, programs will use it
to set fonts for normal text not just symbols and then there are issues
with sizing to consider since different fonts dont have compatible
metrics and so cant be used easily in a monospaced rendering model.

Any issues that are caused here also occur because of font fallbacks---unless I am understanding the issues wrong.

> And finally, you would need buy in from terminal program developers
otherwise this would just be code kitty carries around for no practical
benefit.

I tried to give a nice example of why this wouldn't necessarily be the case. Almost all of the neovim ecosystem gets its icon code from one project, [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons), and a small change their could allow for change across the ecosystem for kitty (there's not really n*m work required here).
Furthermore, using CSI codes would be a fairly interoperable solution. Not only one that could benefit other terminals, but also one that is easy to integrate into existing text-styling code in terminal programs (I imagine something like a "icon style" string is all that is necessary).

**Comment by kovidgoyal** [comment]
On Tue, Jul 12, 2022 at 07:18:37PM -0700, Calvin Lee wrote:
> I agree that using public codepoints for NERD is a bug, but I disagree that this should be the solution even if NERD only used private use codepoints.
> Private use codepoints shouldn't be necessary to show icons. Showing icons is a fairly routine job of a terminal, and shouldn't require users to give up all of their private codepoints to do so. Private codepoint use cause issues because it can necessarily cause conflicts with anything else that uses private codepoints. Thus private codepoints should only be used in niche, vendor specific environments (you can't just say "these codepoints belong to NERD" because that would require specifying them in unicode. vendor specific means vendor specific).
> A great example of this I came across recently was when some weather icons used the same codepoints as fontawesome icons, which I both used. The only way to reconcile these was to use NERD which compiles them both into different codepoints, but a better option would be to specifically opt-in to the weather font or fontawesome.

You need to think more carefully. Expecting terminal programs to specify
fonts to use is pretty bad design, since a terminal program could be
running over ssh and has no idea what fonts are available to the
terminal emulator. To make it robust you would need

1) Some way to actually send font data to a terminal emulator
2) Some way to query the terminal emulator for what font faces it has
available locally. 

And there are security implications to both these problems that require
careful thought. These issues are *far* larger than a possible conflict
in private use space. And the solution to that is to simply move more
icons into the public space so they can be relied upon.  

> 
> 
> 
> > Not to mention that allowing terminal programs to set fonts doesn't
> really work since once this capability exists, programs will use it
> to set fonts for normal text not just symbols and then there are issues
> with sizing to consider since different fonts dont have compatible
> metrics and so cant be used easily in a monospaced rendering model.
> 
> Any issues that are caused here also occur because of font fallbacks---unless I am understanding the issues wrong.

You are ignoring the fact that once such a capability exists, it will be
used far more than for just fallback fonts, thereby making the problem
much *bigger*.

> 
> > And finally, you would need buy in from terminal program developers
> otherwise this would just be code kitty carries around for no practical
> benefit.
> 
> I tried to give a nice example of why this wouldn't necessarily be the case. Almost all of the neovim ecosystem gets its icon code from one project, [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons), and a small change their could allow for change across the ecosystem for kitty (there's not really n*m work required here).

That's one editor. And have you got any buy in from the developers of
nvim-web-devicons?

> Furthermore, using CSI codes would be a fairly interoperable solution. Not only one that could benefit other terminals, but also one that is easy to integrate into existing text-styling code in terminal programs (I imagine something like a "icon style" string is all that is necessary).

:)) If you think creating new terminal escape codes is interoperable,
you havent been in this space long enough. It's filled with people that
prefer to bikeshed rather than get anything done. It would be at best
years, more likely decades and most likely never that a new escape code
protocol would be widely adopted.

**Comment by 4e554c4c** [comment]
I agree with you on many of these points, and I think we are somewhat talking past each-other.
I think this is my fault, for starting this issue with "terminal protocol extension" when none is required.
I hope that if I explain the specific implementation I am thinking about, this will become more clear:

I propose that we use the *standard SGR codes 11-19, as specified in ECMA-48 as `FONT SELECTION` (FNT)* to allow for alternative fonts.
In particular, these codes *do not allow specifying a font by name*, only by fallback number.
For example, the following command should print "test" in the first fallback font, and then revert to the default font: 
```
printf "\e[11mtest\e[10m"
```
These would be easily usable in kitty by adding a line such as 
```
alternative_font_1 UnifontMedium
```
to kitty.conf

From what I understand of your concerns, this will not cause any security issue; as these codes do not allow for specifying font by name, only fallback number. One can expect that if a fallback font is not listed, kitty will use its default font and the terminal program will gain no knowledge of the terminal, installed fonts or anything else about the system.

> That's one editor. And have you got any buy in from the developers of nvim-web-devicons?

I have not, but this is not even necessary for this feature to be useful. For example, in my neovim config I could easily set every icon string `$s` to be `"\e[11m$s\e[10m"` and it would work. This is the same as any project which allows decorations to be specified as strings. For example, weechat allows you to specify strings for, e.g. channel indent. These are often used with unicode box-drawing characters to give the look of a tree, but if these box drawing characters were in another font they could easily be surrounded with the proper escape codes in a weechat config.

> :)) If you think creating new terminal escape codes is interoperable,
you havent been in this space long enough. It's filled with people that
prefer to bikeshed rather than get anything done. It would be at best
years, more likely decades and most likely never that a new escape code
protocol would be widely adopted.

I appreciate your experience and input. However this is _already a standard escape code_, by implementing it, kitty would work no less well with standard terminal programs as it already does.

**Comment by trygveaa** [comment]
> For example, weechat allows you to specify strings for, e.g. channel indent. These are often used with unicode box-drawing characters to give the look of a tree, but if these box drawing characters were in another font they could easily be surrounded with the proper escape codes in a weechat config.

Well, you can't use escape codes directly to format text in weechat, so that won't work. You would have to get support for the escape code implemented in weechat (and ncurses, which weechat uses). I wouldn't be surprised if that's the case for neovim as well, but don't know.

**Comment by kovidgoyal** [comment]
Not a fan of this. The only case where this can work is if the user
configures the terminal and then configures the program running in it.
Which basically means every program has to be configured to make use
of it. It's not scale able.

**Comment by 4e554c4c** [comment]
> Well, you can't use escape codes directly to format text in weechat, so that won't work. You would have to get support for the escape code implemented in weechat (and ncurses, which weechat uses). I wouldn't be surprised if that's the case for neovim as well, but don't know.
ah gotcha

neovim certainly has escape code support, and it is already used by tons of projects (like this devicons project)

anyway, it seems to me like if this doesn't make sense, the next step is to try to use the kitty graphics terminal to directly draw icons. Pretty sure this would be a more scalable solution. I'll try experimenting with it upstream in my spare time.

**Comment by rebelot** [comment]
https://github.com/neovim/neovim/pull/21888

**Comment by Thesola10** [comment]
OSC 11~19 apparently already exist as "standard" font switching codes
