### ISSUE TITLE
Ability to not close kitty window on process death if it exited with non-zero code

### ISSUE THREAD

**Issue by jack1142** [kovidgoyal/kitty#5269]
**Is your feature request related to a problem? Please describe.**
I like to launch ssh (and sometimes also other processes) in a separate tab using a command like:
```
kitty @ launch --type=tab kitty +kitten ssh 0.0.0.0
```
However, if ssh fails to connect for whatever reason, I'm not able to see the reason why that happened because the tab closes before I had the chance to look at the error.

**Describe the solution you'd like**
An option that prevents kitty from closing a kitty tab/window when the process running in that tab/window finishes IF it exited with non-zero code. It might make some sense to also allow it to be set in such a way that it also doesn't close a kitty tab/window if the exit code was zero *but* I personally wouldn't need it.

**Describe alternatives you've considered**
In this specific instance, I could do something like:
```
kitty @ launch --type=tab sh -c 'kitty +kitten ssh 0.0.0.0 || (echo "Press ENTER to exit" && read REPLY)'
```
but it's quite complicated and would require me to do this whenever I want to launch some process in a separate tab if I want to be sure that I can see its output if it ends up failing.

**Additional context**
I thought that the `close_on_child_death no` option would at least make it so the tab isn't closed until I do it myself (regardless of the exit code) but this is already the default value and it does not prevent this from happening. Reading the description of the option, I imagine its use case is different so that makes sense but I'm just mentioning it since it's the only option I could find that seemed somewhat similar to what I'm looking for.

**Comment by page-down** [comment]
You can use the following argument, but the window will not close automatically when the exit code is zero.

```shell
kitty @ launch --hold
```

https://sw.kovidgoyal.net/kitty/remote-control/#cmdoption-kitty-launch-hold

**Comment by kovidgoyal** [comment]
The canonical way to do this is to use a script wrapper, as you already discovered, since exactly what behavior one wants can vary. If you just want the window to stick around unconditionally, use --hold as @page-down pointed out.
