### ISSUE TITLE
Can't use monospace Nerd Fonts

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#527]
I'm trying to use fonts from [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) project, which is popular among Vim users. All these fonts have a special "Mono" version which is supposed to be monospaced and purposed specifically for programs requiring monospace fonts (e.g. Kitty). However these fonts does not show up in `kitty list-fonts`. The ones I've tried are: `Inconsolata`, `Iosevka` and `Fura Code` but I suspect that the situations is same for rest of fonts.

AFAIU there is no single definition of "monospaced". What are Kitty's requirements for such fonts? Is it some hardcoded property in font's description or does Kitty looks at dimensions of each glyph and compares them? Should I open an issue in Nerd Fonts repository?

**Comment by kovidgoyal** [comment]
The font needs to report a spacing of 100 not 90 or 110

**Comment by sergei-dyshel** [comment]
How can I see spacing of font? Tried `fc-match -v` but it didn't return any `spacing` field (and it's indeed present for other fonts that are recognized by Kitty).

**Comment by kovidgoyal** [comment]
If it is not present, that means its value os zero and its not a monospace font.

**Comment by sicr0** [comment]
Same problem, when using the `nerd-fonts-fira-code` AUR package the glyphs delete part of the terminal prompt

**Comment by danielb2** [comment]
has anyone gotten this to work? especially with iosevka
