### ISSUE TITLE
Handle interrupt signal on ssh kitten when connecting

### ISSUE THREAD

**Issue by zasdaym** [kovidgoyal/kitty#5271]
**Is your feature request related to a problem? Please describe.**
When the ssh kitten is connecting to the ssh server, pressing Ctrl+C does not cancel or interrupt the ssh connection in progress.

**Describe the solution you'd like**
The ssh kitten immediately cancels the connection with the ssh server when Ctrl+C is pressed.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kovidgoyal** [comment]
It's not possible to do this given the way the ssh kitten operates.

**Comment by page-down** [comment]
I sometimes encounter this too.
When ssh is unable to connect for a long time, for example when the host is not powered on, it will keep hanging and kitty will eventually output the encoded data into the shell (command prompt).

```text
fish: Unknown command: ...
fish: Unknown command: ...
...
```

Currently I only use the default configuration for certain hosts and ask before sending for others.

```shell
kitty +kitten ssh --kitten="askpass ssh"
```

Maybe the current process of the window can be checked before sending the encoded data.

**Comment by kovidgoyal** [comment]
The encoded data is sent *before* and *independently* of ssh. It sits in
the pipe waiting for ssh to read it. There is no way to have ssh signal,
the terminal to start sending data. If you want that behavior you can
set askpass to ssh in ssh.conf then kitty will wait for the connection
to be established, and only once it gets a request from the remote
machine will it send the data. This means ctrl-c will work and you wont
get data spillover into the terminal when ssh fails, but at the cost of
an extra roundtrip before data transmission can start, meaning a big
increase in time-to-prompt ready.
