### ISSUE TITLE
Integration with tmux control mode

### ISSUE THREAD

**Issue by MaxRenaud** [kovidgoyal/kitty#5274]
**Is your feature request related to a problem? Please describe.**
tmux supports [Control mode](https://github.com/tmux/tmux/wiki/Control-Mode) which can multiplex virtual tmux windows to a single stream for the terminal to display naively. In practice, that means opening multiple tmux windows in a single session can map to multiple tabs in kittyterm. This is how [iTerm2 does it](https://iterm2.com/documentation-tmux-integration.html)

**Describe the solution you'd like**
The MVP would be for KittyTerm to listen to the \033P1000p DSC sequence and implement enough of the [control mode protocol](https://github.com/tmux/tmux/wiki/Control-Mode) to map windows to tabs. Future features could implement more of the protocol as demand grows (window renaming, etc)

**Describe alternatives you've considered**
I'm using both iTerm2 on my Mac laptop and tmux naively on my Linux desktop. I prefer the look and feel of showing tmux windows as native tabs.

**Additional context**
I'm a bit rusty on Python but if this FR gets approved, I can get started on an implementation. Ideally I'd like to get agreement that this is worthwhile and agree on the MVP before I start sending PRs.

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in this. It is one of my goals to make
terminal multiplexers obsolete. Other than remote persistence kitty can
already do everything tmux can, natively.

**Comment by MaxRenaud** [comment]
Thanks for the quick reply. My primary use case was indeed remote persistence due to remote work but I understand your position. Have  a good day!
