### ISSUE TITLE
On MacOS, scroll sometimes stops working

### ISSUE THREAD

**Issue by thom-nic** [kovidgoyal/kitty#5281]
**Describe the bug**

I have usually have multiple tabs / terminal sessions open in kitty. Sometimes in one tab, using the mouse scroll starts to iterate through command history instead of scrolling through the buffer.  Cmd-Up/Down, and Cmd-Fn-Up/Down also no longer work for buffer scrolling.  Once this starts occurring, the only solution I have found is to close that session.
Unfortunately I haven't been able to figure out what triggers it.  

**To Reproduce**
Unsure.  It usually happens at least once a day.  There may be some correlation to SSH session usage? However even after terminating the SSH session, I still cannot scroll the buffer in that tab.

**Screenshots**

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Darwin neon-3804.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.3.1 BuildVersion:	21E258
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/thom/.config/kitty/kitty.conf

Config options different from defaults:
font_family                   FiraCode Nerd Font
font_size                     14.0
macos_option_as_alt           3
scrollback_pager_history_size 10485760
tab_bar_edge                  1
term                          xterm-256color
Added shortcuts:
	opt+left → send_text normal,application \x1bb
	opt+right → send_text normal,application \x1bf
Changed shortcuts:
	ctrl+shift+[ → previous_tab
	ctrl+shift+] → next_tab
	ctrl+shift+t → launch_tab
	cmd+1 → goto_tab 1
	cmd+2 → goto_tab 2
	cmd+3 → goto_tab 3
	cmd+4 → goto_tab 4
	cmd+5 → goto_tab 5
	cmd+t → launch_tab
Colors:
	background                    #121212   
	color0                        #121212   
	color1                        #fa2573   
	color10                       #b0e05e   
	color11                       #fef26c   
	color12                       #00afff   
	color13                       #af87ff   
	color14                       #50cdfe   
	color2                        #97e123   
	color3                        #dfd460   
	color4                        #0f7fcf   
	color5                        #8700ff   
	color6                        #42a7cf   
	color7                        #bbbbbb   
	color8                        #545454   
	color9                        #f5669c   
	cursor                        #bbbbbb   
	foreground                    #bbbbbb   
	selection_background          #b4d5ff   
	selection_foreground          #121212   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.X2h5fXGcGc/org.macosforge.xquartz:0
	USER                                thom
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
> ... using the mouse scroll starts to iterate through command history ...

It sounds like the program you are using entered the alternate screen and did not exit.

> ... the only solution I have found is to close that session ...

You can use the shortcut `Option+Command+R` to reset the terminal.

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal

Or send an escape sequence to exit the alternate screen.

```shell
tput rmcup
```

kitty is working as expected, you need to find out which program you are using that is causing the problem.

**Comment by kovidgoyal** [comment]
This will be some program you are running not restoring the keyboard
mode on ext. Simply type rest and press enter.
