### ISSUE TITLE
Running a sub-shell using sudo results in a not fully functional terminal

### ISSUE THREAD

**Issue by tcoliver** [kovidgoyal/kitty#5288]
**Describe the bug**
Using sudo to run a sub-shell such as bash or zsh appears to results in a not fully functional terminal. The result is not always consistent but I have experienced the following in most cases:
 - The `clear` command displays an error ("terminals database is inaccessible") and does not clear the terminal.  
   <img width="277" alt="image" src="https://user-images.githubusercontent.com/9102481/179437960-6e667c8f-1d31-4461-907d-908d436ca791.png">
 - backspace does not work, but instead moves the cursor forward one space. Most likely a result of the control character not being recognized.
 - attempting to display a man page results in an error but then displays correctly. The error is not always the same
   <img width="313" alt="image" src="https://user-images.githubusercontent.com/9102481/179438133-5bf77542-62cf-4897-8abf-f21ce73a0d2c.png">

I have experienced this on two different machines. Both are arm64 based processors. I have not had the chance to test on a intel machine yet. 
1) MacBookAir10,1 running 12.4
2) MacBookPro18,1 running 12.4

**To Reproduce**
1. open kitty
2. run `sudo zsh`
3. type `clear` or `man <some man page>` or `<any text> and then backspace`.

**Screenshots**
Included above

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin Macbook-Air.attlocal.net 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/trent/.config/kitty/kitty.conf

Config options different from defaults:
bold_font             Hack Nerd Font Mono Bold
bold_italic_font      Hack Nerd Font Mono Bold Italic
enable_audio_bell     False
font_family           Hack Nerd Font Mono
initial_window_height (600, 'px')
initial_window_width  (900, 'px')
italic_font           Hack Nerd Font Mono Italic
remember_window_size  False

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                trent
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

The problem persists in the with the kitty config set to NONE.

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/faq/#keys-such-as-arrow-keys-backspace-delete-home-end-etc-do-not-work-when-using-su-or-sudo

Put the `xterm-kitty` terminfo database under root's `$HOME/.terminfo/78/` & `$HOME/.terminfo/x/`, or under `/usr/local/share/terminfo/{78,x}/`, or `/usr/share/terminfo/78/`.
