### ISSUE TITLE
cannot zoom to a single terminal

### ISSUE THREAD

**Issue by Cris-lml007** [kovidgoyal/kitty#5291]
Kitty incorporates a zoom system for the terminals of which in the documentation indicates that it requests two parameters (terminal application, the increase) I see that the increase to a single terminal is not working quite well, being that when I zoom, this applies to all terminals regardless of whether you put the argument of `current` in my kitty.conf, there is some way to fix it?, this is how my mapping is defined:
```
map ctrl+plus change_font_size current +2.0
map ctrl+minus change_font_size current -2.0
map ctrl+equal change_font_size current 0
```

**Comment by kovidgoyal** [comment]
Font size is not a property of a kitty window but of an OS window. As is
noted in the docs. So current means the current OS window which may
contain one or more tabs and one or more kitty windows, all of whose
font sizes will change.

**Comment by Cris-lml007** [comment]
> Font size is not a property of a kitty window but of an OS window. As is noted in the docs. So current means the current OS window which may contain one or more tabs and one or more kitty windows, all of whose font sizes will change.

ok, I understand, but you could not implement that function for future versions, since I see it very useful, since you do not always want to modify the size of all terminals but only one.  Also a functionality that I see it does not have and it would be great if it were implemented would be a single terminal maximizer.

**Comment by kovidgoyal** [comment]
No I have no plans to implement per kitty window font sizes. And you can
already maximize single kitty windows, https://sw.kovidgoyal.net/kitty/actions/#action-toggle_layout
