### ISSUE TITLE
keep remote session alive

### ISSUE THREAD

**Issue by kulak** [kovidgoyal/kitty#5292]
This is a request for functionality of tmux that people actually is tmux for.

When connecting to remote machine and starting a long running application like OS update it is undesirable to have that process and connection killed in the middle of operation.  tmux like application keeps work safe. Examples for connection loss:

- accidentally closed terminal window
- closed laptop terminates connection
- bad WiFi connection from laptop

I have experienced all 3 above multiple times and at times more than I wish.  For example, WiFi resets would kill remote session.  Without tmux it would be a disaster.

I am aware of existing and closed request about tmux functionality, but it did get out of control.  Thus, I am focusing this request only on one feature: that is keep underlying session alive.

**Comment by kovidgoyal** [comment]
Unless you are willing to write code for it, dont waste my time opening duplicate issues.
