### ISSUE TITLE
[SEARCH] - search particular word/sentence

### ISSUE THREAD

**Issue by codesnail21** [kovidgoyal/kitty#5293]
### Feature requested

- need a search in the terminal based on sentence/word.
- Search throughout the terminal via shortcut

**Comment by page-down** [comment]
Duplicate of https://github.com/kovidgoyal/kitty/issues/718

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Browse-scrollback-buffer-in-pager

There are other GitHub issues discussed about this feature request.

**Comment by codesnail21** [comment]
@page-down okay thanks

**Comment by codesnail21** [comment]
https://sw.kovidgoyal.net/kitty/#scrollback
