### ISSUE TITLE
How do I do scroll_line_up with more lines on a single keystroke?

### ISSUE THREAD

**Issue by Invertisment** [kovidgoyal/kitty#5294]
I'm not sure if this is not a feature request because it could also already exist if it's possible to repeat a kitty command. I think that it doesn't exist so I ask whether there is a possibility to scroll several lines up or down.
I want this because this way I could read text more clearly after I do page scrolls and I want to see only the several next/previous lines of the output.

I'm not sure what "solution" I would like because this could be implemented in various ways.
I could do a macro on my side that repeats the key multiple times or it could be a repeat argument to the kitty terminal (something as in bash shell when I press `Alt+number`). It could also simply be a hardcoded number of lines to be scrolled like this: `map alt+k scroll_line_up 5`.
It could also probably work if I could do this (too hacky, probably you don't want to do this kind of parsing because it may interfere with other command parsing):
`map alt+k scroll_line_up; scroll_line_up; scroll_line_up; scroll_line_up`

Currently I press the keys multiple times to scroll lines multiple times.

**Comment by page-down** [comment]
Currently you can use the `combine` action to achieve the second way.

https://sw.kovidgoyal.net/kitty/actions/#action-combine

```conf
map f1 combine : scroll_line_up : scroll_line_up : scroll_line_up
```

You can also scroll any line or page in the first way by binding the remote control action `scroll-window`.
https://sw.kovidgoyal.net/kitty/remote-control/#kitty-scroll-window

```conf
map f1 remote_control scroll-window 3-
```

**Comment by Invertisment** [comment]
I'll have this config for now (I use home-row only):
```
## Line up/down
map alt+k scroll_line_up
map alt+j scroll_line_down

# Page up/down
map alt+u remote_control scroll-window 25- # 25 lines
map alt+d remote_control scroll-window 25+ # 25 lines
map alt+U scroll_page_up
map alt+D scroll_page_down

```

**Comment by page-down** [comment]
> Is it possible to scroll by half of a window?
> ... this fails when the integer is parsed.

Not at the moment, I think this feature is useful and can be added.

For now, you can write a custom kitten to achieve that.
https://sw.kovidgoyal.net/kitty/kittens/custom/
Calculate the number of lines and scroll.

**Comment by kovidgoyal** [comment]
It should be a pretty simple patch to scroll_window.py PRs welcome
