### ISSUE TITLE
SSH that works by default without kittens

### ISSUE THREAD

**Issue by rosejn** [kovidgoyal/kitty#5299]
**Is your feature request related to a problem? Please describe.**
My team has a bunch of scripts that use terraform and vault to ssh on to AWS instances where our web apps and distributed services are running.  I basically can't use kitty with our system because of this terminfo issue, and it would be really laborious to have to dig through all the scripts to figure out how to manually ssh on with the kitten in order to get terminfo setup properly.

**Describe the solution you'd like**
Have some kind of setting where by default when sshing onto a remote machine a normal xterm can be used without transmitting a terminfo db.  It would be ideal if the kitten and special kitty terminfo were ways to upgrade a remote session's capabilities rather than fix a broken one.

**Comment by kovidgoyal** [comment]
please dont open duplicate issues
