### ISSUE TITLE
New Tabs should respect some session settings or is it possible to open a new tab with a session file source?

### ISSUE THREAD

**Issue by somebehemoth** [kovidgoyal/kitty#53]
In my kitty session (opened with '--session') I have:
`cd ~/`

When I open new windows in my session they are in the same directory as the current window.  When I open a new tab kitty uses default directory.  I prefer to have some control over the working directory in newly opened tabs (preferably via session).

Thank you for making kitty. It is very nice!

**Comment by kovidgoyal** [comment]
You use the new_tab command in the session file to open a new tab. And if you want it to open at a particular directory, you add a cd command after new_tab. See the example session file in the readme. 
Is that what you want?

**Comment by kovidgoyal** [comment]
Oh and note that you can control the starting directory used for all new tabs created inside kitty by the --directory argument to kitty.

**Comment by somebehemoth** [comment]
All of this is what I want.  I will look more closely at readme next time. Thank you!
