### ISSUE TITLE
Setting `cursor_stop_blinking_after` to 0, just stops the cursor from blinking

### ISSUE THREAD

**Issue by FrancescoMagliocco** [kovidgoyal/kitty#530]
### Issue
- [ ] Setting **Option** `cursor_stop_blinking_after` to 0, in `kitty.conf`, results in the cursor not blinking at all.

### Notes:
I am not sure if this is still an issue with the recent commits as I have not tested.  This issue is however the reason why I found the alignment problem fixed with PR #522 

### Update
I can confirm that it is still happening even with the latest commit.

**Comment by kovidgoyal** [comment]
That is what it is supposed to do. Quoting from kitty.conf:

```
# The interval (in seconds) at which to blink the cursor. Set to zero to
# disable blinking. Note that numbers smaller than repaint_delay will be
# limited to repaint_delay.
```

**Comment by kovidgoyal** [comment]
Sorry wrong option help text (it's too early in the morning) :)

**Comment by FrancescoMagliocco** [comment]
I just opened a PR too thinking there was a typo in kitty.conf.  lol.
