### ISSUE TITLE
LMDE 5 not opening after fresh install.

### ISSUE THREAD

**Issue by baeverjo** [kovidgoyal/kitty#5303]
**Describe the bug**
The Kutty terminal will not open after fresh install on new system.

**To Reproduce**
1. Fresh installation of LMDE 5
2. Fresh install of Kitty through terminal as described on Kitty homepage. 
3. No error message during install,  and mo messages about why it do not open.
4. No visible error message. 

**Screenshots**

**Environment details**
```
System: LMDE 5, computer Presario CQ71, Compaq.

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I dont know what LMDE is, assuming it is some kind of desktop
environmnet? In any case, there is no way kitty can just not do
anything.

Run it from another terminal and it will print errors to its stderr.
At the very least run it and get its exit code:

kitty; echo $?
