### ISSUE TITLE
Brand new xubuntu (xfce) with all dependencies cannot start: GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by philipsd6** [kovidgoyal/kitty#5311]
**Describe the bug**
All methods of installing kitty result in the following error on launch:

```
[205 18:28:52.715202] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[205 18:28:52.715265] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```
But I *have* OpenGL installed.

**To Reproduce**

I reproduced this with:
* `apt install kitty` (installs an older version)
* `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin`
* `git clone https://github.com/kovidgoyal/kitty; cd kitty; make`

I installed all known dependencies:
* `sudo apt install libdbus-1-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libgl1-mesa-dev libxkbcommon-x11-dev libfontconfig-dev libx11-xcb-dev liblcms2-dev libpython3-dev librsync-dev`
* `sudo apt install libglfw3-dev imagemagick python3-pygments fontconfig wayland-protocols`

**Environment details**

n/a, as Kitty doesn't launch

**Additional context**

`kitty --config NONE` results in the same error.

```sh
echo "linux_display_server x11" > ~/.config/kitty/kitty.conf
./kitty/launcher/kitty --config ~/.config/kitty/kitty.conf
```
...also results in the same error.

**Comment by page-down** [comment]
Did you check the version of OpenGL? As stated in the log, kitty requires OpenGL version 3.3 or higher.
It will not work with some older hardware or in virtual environments that do not support OpenGL 3.3+, such as virtualbox.

Try to run with CPU software rendering.

https://github.com/kovidgoyal/kitty/discussions/4241#discussioncomment-1649653

**Comment by philipsd6** [comment]
Actually, when disabling the VirtualBox "Enable 3D Acceleration" display option, kitty works fine, and glxinfo reports a higher OpenGL version:

```
glxinfo | grep OpenGL | grep -v ':$'
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 13.0.1, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.0.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.0.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

With the "Enable 3D Acceleration" option select, the result is:

```
glxinfo | grep OpenGL | grep -v ':$'
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL version string: 2.1 Mesa 22.0.1
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 22.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
