### ISSUE TITLE
Asian characters and characters with accents not displaying properly

### ISSUE THREAD

**Issue by bvvt** [kovidgoyal/kitty#5318]
Asian Characters and characters with accents are not displaying properly on Kitty, this does not happen in terminal

**To Reproduce**
1. Open KITTY
2. Navigate to a location with a folder or file with an asian character 
3. . See error

**Screenshots**

<img width="1655" alt="_screenshot 2022-07-26 a las 13 39 06" src="https://user-images.githubusercontent.com/91846322/181014497-a166be46-551f-4691-bb39-077aaa1edc46.png">
Notice that Röyksopp is displayed as R?yksopp

![image](https://user-images.githubusercontent.com/91846322/181014425-bb1b11bb-b57f-4810-a2e7-1f83ad6f70d5.png)

Showing correctly on terminal.app
<img width="1186" alt="_screenshot 2022-07-26 a las 13 38 06" src="https://user-images.githubusercontent.com/91846322/181014578-dff5d153-959c-4b5a-a264-4a7d92a57f95.png">

Showing correctly on terminal

**Environment details**
```
Kitty 0.25.2 created by Kovid Goyal
Darwin user.home 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.14>
ProductName:    macOS ProductVersion:   12.5 BuildVersion:      21G72
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/user/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.93
font_family          iA Writer Mono V
Colors:
        background           #403838   
        color0               #403838   
        color1               #fd6883   
        color10              #adda78   
        color11              #f9cc6c   
        color12              #f38d70   
        color13              #a8a9eb   
        color14              #85dacc   
        color15              #fff1f3   
        color2               #adda78   
        color3               #f9cc6c   
        color4               #f38d70   
        color5               #a8a9eb   
        color6               #85dacc   
        color7               #fff1f3   
```

**Additional context**
Error still shows up with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
This will be because whatever program you are running inside kitty is
not calculating string lengths as per the unicode standard. Fix it to do
so and it will work fine.

**Comment by bvvt** [comment]
> This will be because whatever program you are running inside kitty is not calculating string lengths as per the unicode standard. Fix it to do so and it will work fine.

How is LS not calculating string lengths as per the unicode standard

**Comment by kovidgoyal** [comment]
That referred to your first screenshot. As for ls, your LC_CTYPE and/or LANG are wrong/unset/not utf8 values. Fix those and that will be fine too.

**Comment by bvvt** [comment]
> That referred to your first screenshot. As for ls, your LC_CTYPE and/or LANG are wrong/unset/not utf8 values. Fix those and that will be fine too.

Fixed, I had the `locale LANG` set to `es_CH` which does not exist, however  I had to add  
`export LANG="en_US.UTF-8"` to the `.zshrc` file  it wouldn't do it with any other setting other than that one.

Writing it here in case anyone else stumbles upon the same problem
