### ISSUE TITLE
Have shell completion for kssh work the same as ssh

### ISSUE THREAD

**Issue by grimm26** [kovidgoyal/kitty#5322]
**Is your feature request related to a problem? Please describe.**
First off, I use zsh.
I would like command completion for kssh work the same as when I use ssh. For instance, when I start typing `kssh some.host -i ~/.ssh/` and hit <tab>, nothing happens. If I change `kssh` to `ssh` then go to the end of the line and hit <tab> I get completion for the directories and files under `~/.ssh`.

**Describe the solution you'd like**
Have command completion for kssh work like that of ssh.

I've tried just doing `compdef _ssh kssh` but that did not help.

**Comment by grimm26** [comment]
> If that's the completion you are getting for ssh that completion is incorrect. Arguments after the host name are executed on the remote host, so it is meaningless to complete them from local files and directories.

I beg to differ. The `-i` option is to reference the private key on the client side that you need to authenticate to the server. To complete against local files is proper.

**Comment by kovidgoyal** [comment]
You cannot specify arguments to ssh after the hostname.

man ssh

is your friend.

Use kssh -i whatever<TAB>

and it will work fine. And I suggest you go open a bug report against
whoever maintains the completions for whatever shell you are using.

**Comment by grimm26** [comment]
```
mnk-hpbook in ~ on  (oh) 
12:05:28 ❯ ssh 192.168.15.6 -i ~/.ssh/id_rsa -o Port=23 uname -m
ssh: connect to host 192.168.15.6 port 23: Connection refused

mnk-hpbook in ~ on  (oh) 
12:05:30 ✖255 ❯ ssh 192.168.15.6 -i ~/.ssh/id_rsa uname -m           
x86_64
```

**Comment by grimm26** [comment]
and my completions work fine for ssh, but not for kssh. Hence me opening the issue here.

**Comment by kovidgoyal** [comment]
Then report the bug to ssh since the way it parses its command line is
in contravention to its own documentation.

ssh -h
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command [argument ...]]
