### ISSUE TITLE
Font fallbacks

### ISSUE THREAD

**Issue by augustocdias** [kovidgoyal/kitty#5323]
I'd like to suggest adding font fallbacks for the codepoints are not present in a current font.

I know this could be achieved with the `symbol_map` but it would be way easier to be able to just setup fallbacks...

How do I find what codepoints a specific font has anyway? I use a patched font already so most characters are covered by them, but I'd like to configure the codicons font as well... How do I know what are the codepoints I should configure for it?

**Comment by kovidgoyal** [comment]
kitty already has automatic font fallback. See --debug-font-fallback
