### ISSUE TITLE
Tab stop settings being reset at startup

### ISSUE THREAD

**Issue by kbtz** [kovidgoyal/kitty#5324]
If I put `tabs 2; cat somefile` as the last line on my .bashrc, cat runs and tab width is correct. However if I run cat again, as my first command in the prompt, I can see that tab width got back to the default size of 8.

Things that I tried:
- issue persists with shell integration disabled
- issue doesn't happen on xterm
- issue doesn't happen if I hold my .bashrc with `sleep 1; tabs 2`

**Comment by kovidgoyal** [comment]
kitty does not spontaneously reset tab width, something in your bash
config is causing it, presumably something that behaves differently
based on TERM. Bisect your bash config to find it.
