### ISSUE TITLE
Different keybindings per running foreground process

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#5325]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use a program like `nvim`, `less`/`bat`, `fzf`, etc and want to use a keybinding that I'm used to, but can't because I've already mapped the key for a keybinding in `kitty`.

**Describe the solution you'd like**

Would it be possible to specify specific contexts in which we would like a keybinding to be active and contexts in which we do not want keybindings to be active. For the specific problem stated above, this would be specifically contexts regarding the currently running foreground process (e.g. `nvim`, `bat`, `fzf`, etc) in the current active pane.

For example, vscode keybindings look like: `{ "key": "KEY", "command": "ACTION", "when": "BOOLEXPR" }`, where `"when"` allows a user to specify when they want a keybinding to be active and triggered and when they don't, and `BOOLEXPR` is the boolean expression with which they express that condition. `BOOLEXPR` contains [comparison operators and boolean operators](https://code.visualstudio.com/api/references/when-clause-contexts#conditional-operators) applied to [vscode-specific contexts](https://code.visualstudio.com/api/references/when-clause-contexts#available-contexts) (e.g. `editorFocus == true`, `editorFocus == true && panelVisible != true`); there are litterally hundreds if not thousands of these contexts (you can get a comprehensive look at all the context keys available by opening developer tools and running the `Developer: Inspect Context Keys` vscode command).

for kitty perhaps this could look like, and this is just an example i don't know what the syntax should actually be:

```zsh
// kitty.conf
  map super+t new_tab_with_cwd when 'foreground_process == zsh'
```
>- now, the `super+t` keybinding will only work when the foreground process is `zsh`, i.e when in command line prompt, freeing/allowing us to remap `super+t` in any other context (e.g. we might want super+t to open a new tab in nvim, and do other things when in emacs, or tmux, or ssh, or fzf, etc, etc).

**Describe alternatives you've considered**

- maybe a hook to unmap certain keybindings upon launch of certain progams (e.g. nvim, bat, fzf)

**Additional context**

>- potentially any meta information kitty holds or has access to about the terminal, the shell, etc, could also be used as contexts. it would be cool perhaps to have contexts like: current directory, current file being edited, number of tabs, windows, current programs running in current tabs, current host logged into using ssh, comparison of shell environment variable values, etc.
>- vscode keybindings: https://code.visualstudio.com/docs/getstarted/keybindings
>- vscode contexts: https://code.visualstudio.com/api/references/when-clause-contexts#available-contexts
<details><summary>get a comprehensive list of vscode contexts:</summary>

![Jul-28-2022 14-16-47](https://user-images.githubusercontent.com/36056254/181493498-c832346a-4dc5-49ab-9c5f-49b82daa3be1.gif)

</details>

**Comment by kovidgoyal** [comment]
Doesn't seem worth the effort to me. Setup the keybindings in kitty however
you like so as not to conflict with your regularly used programs, once,
and forget about it. For example, the default kitty keybings use
ctrl+shift precisely because these are not used in most terminal
programs. 

That said, I dont have anything against this, so patches welcome.

**Comment by akharrou** [comment]
> Doesn't seem worth the effort to me. Setup the keybindings in kitty however you like so as not to conflict with your regularly used programs, once, and forget about it. For example, the default kitty keybings use ctrl+shift precisely because these are not used in most terminal programs.
> 
> That said, I dont have anything against this, so patches welcome.

Well, you're right you can do that, and it's not that bad when your setup is fairly simple, but when you're setup is fairly advanced it can get quite hairy, complicated, completely unmnemonic/unmemerable, awkward hand gestures, and many times you even run out of keys to even bind.

Consider a user with a setup that includes multiple layers of keybinding shortcuts:
1. computer keybinding global shortcuts (e.g. macos specific things like spotlight, open notifications bar, sleep, restart, shutdown, file explorer)
1. computer application global shortcuts (e.g. window manager shortcuts, email client, task manager, application launcher, password manager, etc ...)
1. keyboard modifier shortcuts (e.g. karabiner, skhd)
1. kitty terminal application keybinding shortcuts (including all the terminal window management shortcuts ... and hints and the whole nine yards that kitty offers)
1. shell (zsh, bash, ...) specific keybinding shortcuts
1. terminal foreground process specific shortcuts (e.g. nvim, emacs, tmux, fzf, less/bat, and the list goes on; some of which could be standalone applications on their own with full keybindings)

@kovidgoyal now what do you do ?

**Comment by kovidgoyal** [comment]
I have exactly that kind of setup, havent noticed any issues.
