### ISSUE TITLE
Difficulty building from source on M1 due to Python runtime error

### ISSUE THREAD

**Issue by rohan-n** [kovidgoyal/kitty#5326]
**Describe the bug**
I've tried numerous times with many tweaks to my python and environment configuration to install kitty from source on my new M1 mac but continuously get the error message `Fatal Python error: _PyInterpreterState_Get(): no current thread state`. Reading around in forums it seemed like the issue might have been related to different versions of python being used to compile each brew formulae, but I re-installed all the packages to the same result. 

**To Reproduce**
Follow the instructions from https://sw.kovidgoyal.net/kitty/build/
```
/Applications/kitty (master) > brew list
==> Formulae
autoconf		fontconfig		git			harfbuzz		libffi			librsync		libxau			libxext			lzo			pcre			pkg-config		readline
ca-certificates		freetype		glib			icu4c			libpng			libtiff			libxcb			libxrender		m4			pcre2			popt			xorgproto
cairo			gettext			graphite2		jpeg-turbo		libpthread-stubs	libx11			libxdmcp		little-cms2		openssl@1.1		pixman			pyenv			zlib
/Applications/kitty (master) > make
python3 setup.py 
CC: ['clang'] (13, 0)
[65/65] Compiling kitty/gl-wrapper.c ... done
[6/6] Linking kittens/choose/subseq_matcher ... done
/Applications/kitty (master) > ./kitty/launcher/kitty
Fatal Python error: _PyInterpreterState_Get(): no current thread state
Python runtime state: unknown

Abort trap: 6
/Applications/kitty (master) > pyenv versions
  system
* 3.8.13 
```

**Comment by kovidgoyal** [comment]
This will be different python versions. Just build using your system
python. There is no need to futz around with brew and pyenv and all the
associated paraphernalia that just makes things harder.

You can pass the include and lib flags for the C libraries you installed
from brew with the -I and -L flags as usual when running ./setup.py
build.
