### ISSUE TITLE
Please add a separate keycode for shift+escape

### ISSUE THREAD

**Issue by RedBeard0531** [kovidgoyal/kitty#533]
[mintty](https://github.com/mintty/mintty/wiki/Keycodes#special-keys) uses 0x9B, so that seems like a reasonable choice. While you are at it, it may be worth adding any missing codes from that page, but shift+escape is the only one I personally use.

I use this in [vim](https://github.com/RedBeard0531/dot_files/blob/936b7ec701c5e1be72be89fa292236abac762b01/vimrc#L248-L250) (the 0x9B char is hidden on github) to exit from vim's terminal mode, and I'd like to be able to use it with kitty too.

**Comment by kovidgoyal** [comment]
I have no idea why mintty uses that code, it comes from no standard I know of and is supported by no programs I know of. I dont think adding them to kitty is a goode idea. 

You can map arbitrary key presses to generate arbitrary bytes in kitty, see the default kitty.conf (search for send_text) for examples. Feel free to use that for whatever custom mappings you need.
