### ISSUE TITLE
Installing Kitty through the OpenBSD Ports doesn't setup xterm-kitty correctly.

### ISSUE THREAD

**Issue by boecker** [kovidgoyal/kitty#5336]
So the issue I'm having with the xterm-kitty is that apparently it doesn't exist on the system.  Or at least it's not being detected by my `TERM=xterm-kitty`, when I run a command such as `doas pkg_add neofetch`.  It shows "failed to lookup on xterm-kitty at /usr/libdata/perl5/OpenBSD/ProgressMeter/Term.pm line 113".  I tried referring to FAQ and the issues here.  But none have seemed to solve the issue.

**Comment by kovidgoyal** [comment]
Report the issue to whoever maintains that kitty package. Instructions
for building kitty packages are here:
https://sw.kovidgoyal.net/kitty/build.html#note-for-linux-macos-packagers 

Ans search the kitty FAQ for BSD
