### ISSUE TITLE
Strikethrough line is too low

### ISSUE THREAD

**Issue by ShadiestGoat** [kovidgoyal/kitty#5340]
**Describe the bug**
The line for the strike through is very low, I'd say middle of last quarter

**To Reproduce**
1. In bash, `echo -e "\e[9mstrikethrough\e[0m"`
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/48590492/182017145-2d8da219-4a04-4ae9-b67f-2e28c7c40ccf.png)
![image](https://user-images.githubusercontent.com/48590492/182017155-b7b5b675-2434-4f4c-9b28-4dfbe9706c95.png)

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux shadygoat 5.18.14-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000 x86_64
Arch Linux 5.18.14-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/home/shady/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/shady/go/bin
	LANG                                en_US.UTF-8
	EDITOR                              nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                shady
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      2
	LC_CTYPE                            en_US.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_GB.UTF-8
	LC_ALL                              en_US.UTF-8
```

**Additional context**
This works with --config NONE.
In case it matters, I'm using `tonsky/FiraCode`, not patched.

**Comment by kovidgoyal** [comment]
The position of the strikethrough comes from the font's metrics, and if
you run kitty nightly you can adjust it using the new adjust_font
setting.

**Comment by page-down** [comment]
> you can adjust it using the new adjust_font setting.

For anyone reading this, I believe kovid is referring to `modify_font`, and here is the documentation in the source code.

https://github.com/kovidgoyal/kitty/blob/aedda4bf9bc1c92caa2d3c8db6af6c9bcad1cae8/kitty/options/definition.py#L192-L214
