### ISSUE TITLE
duplicate output from send-text

### ISSUE THREAD

**Issue by gknittl** [kovidgoyal/kitty#5345]
I've been wanting for a long time to be able to write a draft command to the command line from a shell script, that I can then edit manually before executing. For example a first pass at an SQL query that I then fine tune manually on the command line before executing.

kitty @ send-text finally allows this! and it works! However, when running in the same kitty window as the output, send-text duplicates the output both before and after the command prompt as follows:

port1$ kitty @ send-text "set up draft command"
set up draft commandport1$ set up draft command

or
port1$ kitty @ send-text  --match state:focused "set up draft command"
set up draft commandport1$ set up draft command

matching on pid still leaves the duplication

desired output would include only the second copy of the text
port1$ kitty @ send-text "set up draft command"
port1$ set up draft command

Duplication does not occur when writing text to a different window than the script is executing in. 

environment

port1$ kitty -v
kitty 0.25.2 created by Kovid Goyal

port1$ echo $BASH_VERSION
5.0.17(1)-release

port1$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Thanks so much for your wonderful terminal emulator!
Greg

**Comment by kovidgoyal** [comment]
Yes, that is to be expected. You are writing text into the tty's 
pipe. This is echoed on the terminal screen by the kernels tty line
discipline. And whether it appears at the prompt or not depends on
timing issues and how the shell you are using works. 

You can do 

x=$(stty -g); stty -echo; kitty @ send-text "test me"; stty "$x"

to prevent the echo, but whether the text will show up at the prompt or
not is very much shell and timing dependent.

When you send it to another window, the other window is already waiting
at a shell prompt and the shell can thus read the text as though you had
typed it. With the same window the text arrives before the shell resumes
control. It's as though your run 

sleep 5

and type some text

you will see the text both before and after the shell prompt

**Comment by gknittl** [comment]
Thanks so much for the explanation! Putting the kitty @ send-text in the background works for me

port1$ kitty @ send-text  --match state:focused "set up draft command" &
[1] 11881
port1$ set up draft command

in case of timing delay this also works

port1$ { sleep .1; kitty @ send-text  --match state:focused "set up draft command"; } &
[1] 11897
port1$ set up draft command

Super product and super support!

**Comment by gknittl** [comment]
send-test can also position the cursor on the command line using terminal escape codes. Here is an example using escape-D to simulate pressing the left arrow key:

kitty @ send-text "test test\x1b[D\x1b[D" &

which moves the cursor 2 positions left from the default end of line position
