### ISSUE TITLE
new_tab_with_cwd and copy don't seem to work together

### ISSUE THREAD

**Issue by ledhed2222** [kovidgoyal/kitty#5346]
**Describe the bug**

The first terminal to a new remote works great. If I try and use `new_tab_with_cwd` on that remote, however, the terminal crashes. Unfortunately the terminal crashes and clears the screen so fast that I can't actually see the output. If you have any ideas on how to prevent the screen from clearing let me know!

**To Reproduce**
1. Following config:

Context kitty.conf:

```conf
map cmd+t new_tab_with_cwd !neighbor
```

and ssh.conf

```conf
copy .zshrc
```

3. `ssh` into any machine and leave this terminal open
4. cmd+t to open a new tab
5. See error

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin <redacted> 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.5 BuildVersion:	21G72
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/<redacted>/.config/kitty/kitty.conf

Config options different from defaults:
clipboard_control                  ('write-clipboard', 'write-primary')
copy_on_select                     clipboard
cursor_stop_blinking_after         1.0
font_family                        PragmataPro Mono
font_size                          16.0
macos_quit_when_last_window_closed True
Changed shortcuts:
	cmd+k → clear_terminal reset active
	cmd+t → new_tab_with_cwd !neighbor

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                <redacted>

```

**Comment by kovidgoyal** [comment]
Does not reproduce for me. First of all share_connections belongs in
ssh.conf and defaults to on anyway. 

I highly doubt the terminal is crashing, but if so post a stack trace.
Or alternatively run kitty from another terminal and see what is printed
to its stderr.

**Comment by ledhed2222** [comment]
This is embarassing - it no longer repros for me either 😅

thanks anyway - love kitty. user since 2018!

**Comment by ledhed2222** [comment]
@kovidgoyal can we re-open this? I've determined the cause. Strangely, I cannot reproduce this when `kitty` was launched from another terminal emulator (in my case I tried Terminal.app). However, it will reproduce when kitty is launched normally.

The issue seems to be that the remote machine tries to copy files to itself when opening a second terminal with a shared connection. In this case, and since I'm using `--dest` with the copy command, the source path does not exist on the remote machine, causing the copy to fail and the tab to close.

This should be in your kitty.conf:
```
map cmd+t new_tab_with_cwd !neighbor
```

This should be in your ssh.conf
```
copy --dest zshrc_copy .zshrc
```

in this config, `.zshrc` from the host machine will be copied to `zshrc_copy` on the remote. This works fine. However, when you execute `new_tab_with_cwd !neighbor` via the keybinding, the remote will try to copy `.zshrc` to `zshrc_copy`, but the former file does not exist.

**Comment by kovidgoyal** [comment]
Does not reproduce for me with those settings. The remote never tries to
copy anything. And you can delete zshrc_copy before pressing cmd+t and
you will see it is re-created when you press cmd+t, showing that the
copy is of local .zshrc to zshrc_copy, as expected.
