### ISSUE TITLE
Use of --posix for bash integration causes unwanted side effects

### ISSUE THREAD

**Issue by dcolascione** [kovidgoyal/kitty#5349]
**Describe the bug**

Kitty's addition of `--posix` to bash command line for integration injection makes the injection non-transparent and can break user scripts. In particular, `--posix` causes bash to enable the `inherit_errexit` shell option. `inherit_errexit` remains enabled even after `kitty.bash` resets the `posix` shell option.

`inherit_errexit` being unexpectedly enabled can break sourced shell functions in subtle and hard-to-guess ways.

**To Reproduce**
1. Launch bash in kitty with integration enabled
2. Run `shopt -p inherit_errexit`
3. Observe that `inherit_errexit` is enabled
4. Run the same command in xterm and observe that `inherit_errexit` is disabled

**Comment by kovidgoyal** [comment]
That's a bug in bash, it should reset the setting when resetting posix.
In any case its trivial to workaround, simply have kitty.bash reset it.
Feel free to send a PR.

**Comment by dcolascione** [comment]
Why are you closing this bug? User shell code is still broken. Whether or not bash _should_ reset options set as a side effect of using `--posix`, it _doesn't_, and even if we changed bash's behavior today, it'd be years before a version of bash with that change propagated to users.

**Comment by kovidgoyal** [comment]
Because its already fixed.
