### ISSUE TITLE
│& other characters don't display properly while running tmux

### ISSUE THREAD

**Issue by bokwoon95** [kovidgoyal/kitty#535]
OS: macOS

I use the vertical box character u2502 '│' for vim vertical splits and it renders fine in kitty, but not tmux+kitty (shows up as a '_' in neovim, & '\~T\~B' in vim). 

I've tried it with iTerm2 & Terminal.app and both have no issues rendering '│' in tmux vim/neovim.

___

To replicate:
Paste `│` in vim while running tmux. Also applies to the `·` character (which I use for trailing whitespaces)

**Comment by kovidgoyal** [comment]
Works fine for me, using tmux 2.7 and vim 8.0.1542

From your description, it is likely tmux is not operating in UTF-8 mode on your system, fix that and you should be fine.

**Comment by bokwoon95** [comment]
Thanks, adding the `-u` flag to my tmux alias made it work 😄 .

`the -u flag explicitly informs tmux that UTF-8 is supported.`
