### ISSUE TITLE
Setting Custom Window Size On Launch

### ISSUE THREAD

**Issue by VihagChaturvedi** [kovidgoyal/kitty#5350]
Sorry if this option exists somewhere already, I cannot seem to find it in the documentation.
I want Kitty to launch with a custom terminal size instead of fullscreen.

`initial_window_height` and `initial_window_width` options don't seem to work

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remember_window_size

**Comment by VihagChaturvedi** [comment]
Sorry to re-open this, but the the `remember_window_size yes` doesn't seem to actually remember the window size either

here is a snippet of my `kitty.conf` 

```
include ./themes.conf

remember_window_size  yes
initial_window_width  80
initial_window_height 24
```
Kitty opens in fullscreen mode regardless, ignoring my configuration. Other features such as `background_opacity` seem to work

OS: Fedora SIlverblue 36
Compositor: Wayland

**Comment by kovidgoyal** [comment]
If it doesnt work then it will be because your window manager is not
respecting window size requests.

**Comment by VihagChaturvedi** [comment]
Have there so far been any issues documented regarding GNOME 42 and Kitty?

Can try and test on other distributions if that's the case
