### ISSUE TITLE
reverse-i-search via Ctrl+r

### ISSUE THREAD

**Issue by CarwynNelson** [kovidgoyal/kitty#5354]
**Is your feature request related to a problem? Please describe.**
I have it ingrained in my muscle memory to use ctrl+r (reverse-i-search) to run commands in my zsh history.

Every other terminal seems to support this, and honestly, I thought it was a feature of the shell but it does not seem to work in kitty so I'm assuming it is a feature of the emulator?

I have tried to search around for a solution but I am unable to find one.

**Describe the solution you'd like**
When I press `ctrl+r` I would like `reverse-i-search` to pop up so I can easily search through my shell history.

**Describe alternatives you've considered**
I have ended up installing zsh-autosuggestions to help a little bit, but it's not a perfect solution.

**Additional context**
I am using zsh as my shell.

**Comment by kovidgoyal** [comment]
It's a feature of the shell and it works fine in kitty with zsh. You
likely have something in your zshrc conditioned on TERM. Bisect the
zshrc to find it.

**Comment by CarwynNelson** [comment]
Thanks for the response, it looks like I was missing

`bindkey -e` in my `.zshrc` to enable emacs style keybindings which also explains some other issues I was having..

For others experience this issue, I believe `bindkey '^R' history-incremental-search-backward` would also enable that if you use `bindkey -v` for vim style bindings, or it is otherwise not working.
