### ISSUE TITLE
Arabic text support

### ISSUE THREAD

**Issue by asahaf** [kovidgoyal/kitty#536]
Arabic characters are displayed as blanks

**Comment by kovidgoyal** [comment]
You need a font capable of displaying arabic characters on your system.

**Comment by kovidgoyal** [comment]
Although I should add that even with an appropriate font, arabic text is never going to look very good in kitty, as kitty is designed to work as a character grid. Scripts such as arabic that cannot be represented ina a character grid are never going to display very well.

**Comment by asahaf** [comment]
The font I'm using is Fira Code. It supports Arabic. Other terminals display Arabic text as disconnected letters, but that's ok. Kitty on the other hand, shows blank

**Comment by ahmedelgabri** [comment]
I came here with the same exact issue, I use https://github.com/soimort/translate-shell to translate text from the terminal. And Kitty is the only terminal that is not showing Arabic text.

Here are screenshots from iterm, alacritty & kitty all using Iosevka nerd font

kitty:
<img width="570" alt="kitty" src="https://user-images.githubusercontent.com/63876/39970118-72013594-56e6-11e8-8352-b079aa4ca35c.png">

alacritty
<img width="599" alt="alacritty" src="https://user-images.githubusercontent.com/63876/39970119-76d93aee-56e6-11e8-9dc8-d92e595a34aa.png">

iterm
<img width="625" alt="iterm" src="https://user-images.githubusercontent.com/63876/39970120-7b89367a-56e6-11e8-94cf-87a630d70812.png">

from your last comment it seems that you have no plans to add this support, am I right?

**Comment by kovidgoyal** [comment]
Umm I'd be very surprised if either Fira Code or Iosevka has arabic glyphs. What you are seeing is font fallbacks in action. What is the actual font that has those arabic glyphs?

**Comment by ahmedelgabri** [comment]
> Umm I'd be very surprised if either Fira Code or Iosevka has arabic glyphs.

You are right Iosevka doesn't have Arabic glyphs https://be5invis.github.io/Iosevka/specimen.html 

> What you are seeing is font fallbacks in action. What is the actual font that has those arabic glyphs?

I honestly don't know, I assume maybe OS fallback? will try to see

**Comment by kovidgoyal** [comment]
If you can figure it out I will install that font and see if I can reproduce. You can also workaround the issue by directly telling kitty to use that font using the symbol_map directive in kitty.conf.

**Comment by kovidgoyal** [comment]
You need to use a font that has actual arabic glyphs in symbol map, Ubuntu Mono does not. There's no need to restrict yourself to monospaced fonts.

**Comment by kovidgoyal** [comment]
I copied over Arial Unicode MS from my windows machine and tried with that, and I can reproduce the issue. But it is not an easy one to fix. Basically, kitty uses harfbuzz to position the character glyphs in cells and harfbuzz shapes arabic text by re-ordering the glyphs to render right-to-left. This makes splitting them up into cells very difficult, since the harfbuzz API has no way to detect when the re-ordering is performed. 

This patch will improve the situation, but as I said originally, Arabic is never going to render very well
https://github.com/kovidgoyal/kitty/commit/1760fb9db2cf054f0ff16b744510eabc7433059e

With that patch and using DejaVu Sans Mono (which does have arabic glyphs) here is a screenshot.
![screenshot_20180516_065749](https://user-images.githubusercontent.com/1308621/40091651-92116a9c-58d6-11e8-934c-f222d03ca292.png)

**Comment by asahaf** [comment]
Great. I'm gonna try the patch. Actually, that's good enough, I can read it.

Thanks,,

**Comment by ahmedelgabri** [comment]
Thanks for working on a fix _according to the changelog_ but there is one issue the letters are flipped LTR instead of RTL

<img width="534" alt="screen shot 2018-05-30 at 21 39 28" src="https://user-images.githubusercontent.com/63876/40743492-f52fadb0-6451-11e8-9e88-e5f1fcc5791d.png">

**Comment by asahaf** [comment]
On my Linux machine, the words are written correct, but the order of the words themselves are left to right. I assume it depends on the OS behavior. Did you do this test on a Mac?

**Comment by ahmedelgabri** [comment]
Yeah I'm testing on a mac

**Comment by kovidgoyal** [comment]
Like I said, kitty is never going to have perfect support for arabic. It's just not a god fit with the rendering model of a character grid. I'm afraid what you get now is about as good as you are going to get. There are terminals that specialise in rendering comple scripts (they have other problems but if reading arabic in your terminal is important to you, you should use one of them). For example mlterm.

**Comment by mihaicristiantanase** [comment]
Hi,
I've tried displaying Arabic text in version 0.13.3, but it does not work.
Text: العَرَبِيَّة‎‎
Font: DejaVu Sans Mono

Result:
<img width="425" alt="kitty-arabic" src="https://user-images.githubusercontent.com/7289591/54107022-a286f680-43e0-11e9-9bc7-8f9b93f56546.png">

I've tried various other fonts, but the results are identical.
Is there something I'm missing here?

Thanks,
Mihai

**Comment by kovidgoyal** [comment]
That test appears to be composed of private use characters such as U+e002 

The test phrase 
عندما يريد العالم أن ‪يتكلّم ‬ ، فهو يتحدّث بلغة يونيكود. تسجّل الآن 

renders in kitty for me.

**Comment by ahmedelgabri** [comment]
> That test appears to be composed of private use characters such as U+e002
> 
> The test phrase
> عندما يريد العالم أن ‪يتكلّم ‬ ، فهو يتحدّث بلغة يونيكود. تسجّل الآن
> 
> renders in kitty for me.

This is what I get in Kitty using that phrase. Font is PragmataPro which does support Arabic.

<img width="747" alt="Screen Shot 2019-03-11 at 10 27 36" src="https://user-images.githubusercontent.com/63876/54113330-5475f100-43e8-11e9-8451-4864bffda1ee.png">

**Comment by kovidgoyal** [comment]
Yeah that's close to what I get as well. As I said Arabic is not going to render perfectly, but it does render. @mihaicristiantanase phrase does not render at all.

**Comment by MagedSaeed** [comment]
> I came here with the same exact issue, I use https://github.com/soimort/translate-shell to translate text from the terminal. And Kitty is the only terminal that is not showing Arabic text.
> 
> Here are screenshots from iterm, alacritty & kitty all using Iosevka nerd font
> 
> kitty:
> <img alt="kitty" width="570" src="https://user-images.githubusercontent.com/63876/39970118-72013594-56e6-11e8-8352-b079aa4ca35c.png">
> 
> alacritty
> <img alt="alacritty" width="599" src="https://user-images.githubusercontent.com/63876/39970119-76d93aee-56e6-11e8-9dc8-d92e595a34aa.png">
> 
> iterm
> <img alt="iterm" width="625" src="https://user-images.githubusercontent.com/63876/39970120-7b89367a-56e6-11e8-94cf-87a630d70812.png">
> 
> from your last comment it seems that you have no plans to add this support, am I right?

can you please let us know how did you set alacritty to ouptut Arabic letters connected? I am unable to do so.

**Comment by eyadsibai** [comment]
> Thanks for working on a fix _according to the changelog_ but there is one issue the letters are flipped LTR instead of RTL
> 
> <img alt="screen shot 2018-05-30 at 21 39 28" width="534" src="https://user-images.githubusercontent.com/63876/40743492-f52fadb0-6451-11e8-9e88-e5f1fcc5791d.png">

the problem is simple ... you have two tools trying to fix the bidi thing ... alacritty doesn't support rtl in the first place

trans command support rtl built-in ... u just need to write this instead

```trans -no-bidi :ar hello``` in kitty and it would work

**Comment by ahmedelgabri** [comment]
> > Thanks for working on a fix _according to the changelog_ but there is one issue the letters are flipped LTR instead of RTL
> > <img alt="screen shot 2018-05-30 at 21 39 28" width="534" src="https://user-images.githubusercontent.com/63876/40743492-f52fadb0-6451-11e8-9e88-e5f1fcc5791d.png">
> 
> the problem is simple ... you have two tools trying to fix the bidi thing ... alacritty doesn't support rtl in the first place
> 
> trans command support rtl built-in ... u just need to write this instead
> 
> `trans -no-bidi :ar hello` in kitty and it would work

@eyadsibai For me it works fine without `-no-bidi`, actually in my case `-no-bidi` breaks it. Not sure if it's a font issue or not, because the only difference between this screenshot & the one I posted earlier is the font (of course also the kitty version)

<img width="816" alt="Screenshot 2021-05-09 at 19 21 47" src="https://user-images.githubusercontent.com/63876/117581180-dd3d6400-b0fb-11eb-89be-ee9b96f8489d.png">
