### ISSUE TITLE
feat: do not dim certain characters

### ISSUE THREAD

**Issue by exincore** [kovidgoyal/kitty#5361]
**Is your feature request related to a problem? Please describe.**
Nerd Font characters (mainly powerline) can make the prompt look really neat by taking advantage of differing background and foreground colors. However, whenever characters are dimmed, the background is not also dimmed.

**Describe the solution you'd like**
Allow configuration to specify a map/list/range of characters — just like with `symbol_map` — which are never dimmed.

**Describe alternatives you've considered**
Tweak the GL shader's behavior of backgrounds to apply dimming to them as well. This could have consequences where that behavior (dimmed foreground is also dimmed background) is not expected, so it would have to be up to the user to configure.
- While it would fix some visual weirdness, and perhaps add a nice visual mechanic for some users, this would not fix the screenshot below where foreground characters are colored as the background — the foreground will still be dimmed, and no longer match the background.
- This does not conflict with the main solution, and if both were added, would allow another aesthetic option for some users.
- I expect this could have a performance impact greater than the main solution, which may only need to do work at the moment a character is printed and not every frame of rendering as this one does.

**Additional context**
The following images are with Kitty's dim on unfocus, 75%.

![Beautiful prompt](https://user-images.githubusercontent.com/44628275/183446641-5ac19e42-48b2-418f-a3d6-17be8fc8b1c5.png)
Normal prompt above.
![Aah, what happened!](https://user-images.githubusercontent.com/44628275/183446883-ed2fb2eb-7e32-47d2-af11-80f129548340.png)
Dimmed prompt above; Powerline characters that mimic the background color but are actually foreground are dimmed as normal, but this is undesirable.

**Mockups**
The following images have the normal prompt in the top 30%, for comparison
![solution1slice](https://user-images.githubusercontent.com/44628275/183460609-b547e894-807d-488e-8344-70f6918fdfef.png)
Solution above. Powerline characters are not dimmed.
![solution2slice](https://user-images.githubusercontent.com/44628275/183460639-0f2e807c-9111-4128-b01e-e00e7bd50daf.png)
Alternative above. All characters *and backgrounds* are dimmed.
![solution1and2slice](https://user-images.githubusercontent.com/44628275/183460665-0c5e9bc6-4040-4b20-903b-1b8da8a349bf.png)
Both solutions combined above. All backgrounds and some characters are dimmed.

**Comment by kovidgoyal** [comment]
Umm I dont understand the use case. Just dont dim the text in your
prompt if you dont like how it looks? 

If you mean the dimming caused by inactive_text_alpha
the whole point of it is that the windows are de-emphasized. I dont
think adding a whole new lookup table just to make prompts in
de-emphasized windows look a little better is worth it. Not to mention
that your proposed solution would mean that if those chars are used
somewhere other than in a prompt, dimming will not work for them as
expected. 

Maybe I misunderstand your problem, explain a bit more.
