### ISSUE TITLE
Build Error: libcrypto not found on M1 mac

### ISSUE THREAD

**Issue by Kiran-Raj-Dev** [kovidgoyal/kitty#5364]
I was trying to build kitty (`HEAD`) from source on an M1 mac and got the following error
`Package libcrypto was not found in the pkg-config search path.`

And I think the following line is the reason:
https://github.com/kovidgoyal/kitty/blob/0a6276b0070924bb6f496b8af7347d37c1106e94/setup.py#L130

On M1 macs the packages are hosted under `/opt/homebrew/` and not `/usr/local/` since that behaviour is only on intel macs

I believe if you searched for openssl there as well then the error wouldn't occur.
And manually running `export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"` does indeed solve the build error.

**Comment by page-down** [comment]
I've noticed a few things about this.

Every time `make` outputs the following to stderr, even if openssl is later found in `/usr/local/opt`.

```text
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
```

However it has actually been found and used, which will lead to confusion.

"openssl" is listed in `Brewfile`, however this will currently install "openssl@3" by default. The default Python versions in Homebrew (including 3.10) still rely on "openssl@1.1", perhaps resulting in two openssl versions being installed.

Perhaps "openssl" in `Brewfile` could be commented out and state that it is already a python dependency.

**Comment by kovidgoyal** [comment]
@page-down: Installing python does not install openssl headers with
brew, you have to install openssl as well.

**Comment by page-down** [comment]
> ... Installing python does not install openssl headers with brew ...

I cannot reproduce this.
After running `brew install python`, the headers will be located at `/usr/local/opt/openssl@1.1/include/openssl/`.
And `brew install openssl` will install `openssl@3`, so now there are two.

Anyway, hopefully there are no compatibility issues across major openssl releases.

**Comment by kovidgoyal** [comment]
On Tue, Aug 09, 2022 at 11:15:11PM -0700, page-down wrote:
> > ... Installing python does not install openssl headers with brew ...
> 
> I cannot reproduce this.
> After running `brew install python`, the headers will be located at ***@***.***/include/openssl/`.
> And `brew install openssl` will install ***@***.***`, so now there are two.

Well that's what happens on CI, where without having openssl in Brewfile
it's not present. I have changed it to only brew install openssl on CI
not in the Brewfile.

> 
> Anyway, hopefully there are no compatibility issues across major openssl releases.

Who knows, given the general software engg quality in OpenSSL I am not
very sanguine, but this is mitigated by the fact that the actual kitty
binary builds use only one openssl and even otherwise, kitty doesnt use
the ssl python module much, so hopefully nothing will break.
