### ISSUE TITLE
In CSI u mode alt+key does not send CSI u command

### ISSUE THREAD

**Issue by potmo** [kovidgoyal/kitty#5365]
**Describe the bug**
After entering `CSI u` mode with `CSI > 1 u` (where `CSI` is `\e\[` i.e. bytes `0x1b 0x5b`) I should be in the first level of progressive enhancement according to [this kitty doc about keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). At least that is how I interpret the docs even if there seems to be a maybe different CSI-code to start the progressive enhancement (`CSI = 1 u`) but it produces the same result.

sending `CSI ? u` to inquire the current progressive enhancement level makes kitty write `CSI ? 1 u` back as expected (although that seems to just respond whatever I set so setting 11 will make kitty respond with 11 but thats another bug)

I have turned on raw mode by setting the `ICANON` flag.
I have then entered alternative screen mode with `\e[?1047h`

I press for example `ALT+p` (on my mac its called option) i read two separate bytes from standard in with `getchar()` namely `207` and `128` that I think is the two unicode bytes for `π`.

I would expect that I'd get back a `CSI u` command and not three separate bytes.

Have I misunderstood the protocol or is this a bug? 

**To Reproduce**
1. see above

**Screenshots**
N/A

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin Nisses-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             /private/tmp/com.apple.launchd.TZ0BBV9cRx/org.macosforge.xquartz:0
	USER                                xxx

```

**Additional context**
N/A

**Comment by potmo** [comment]
btw `ALT+TAB` responds with a proper `CSI u` command so that is at least working

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt
