### ISSUE TITLE
Do not expand kitty_mod in debug_config

### ISSUE THREAD

**Issue by krissi** [kovidgoyal/kitty#5367]
debug_config shows all added and changed and removed shortcuts which is a pretty nice overview. Unfortunately, when kitty_mod is changed from the default ctrl+shift, all default shortcuts are listed as removed shortcuts with ctrl+shift as well as in the added shortcuts list with the new kitty_mod. This clutters the output and makes the lists unusable for me.

As a solution I think it could be possible to literally list "kitty_mod" instead of expanding it to its actual value and show the actual value like the other settings.

**Comment by kovidgoyal** [comment]
Not something I care about, patches welcome. Relevant code is in
debug_config.py
