### ISSUE TITLE
Cursor position update doesn't consider the preedit cursor position

### ISSUE THREAD

**Issue by wengxt** [kovidgoyal/kitty#5370]
**Describe the bug**
In text input v3 protocol, there's a range used to define the cursor position in preedit. It's not necessary to be always same as preedit length.
https://wayland.app/protocols/text-input-unstable-v3#zwp_text_input_v3:event:preedit_string:arg:cursor_begin

For a message like 
[4187366.576] zwp_text_input_v3@18.preedit_string("ni hao", 0, 6)
The cursor rect is expected to be the rect with left equals to the left of "n", and width equal to "ni hao", 

**To Reproduce**
Type with latest fcitx5 under kwin wayland in kitty.

**Screenshots**

kwrite: 
![image](https://user-images.githubusercontent.com/259684/184255540-837c33e1-e4c2-4a73-bb61-eb124f2e656c.png)
kitty:
![image](https://user-images.githubusercontent.com/259684/184255576-720918ae-7af3-474f-9d9a-57531369bd5a.png)

**Environment details**
git master with #5369 5369 applyed on kwin wayland

**Comment by kovidgoyal** [comment]
I'm afraid I dont understand the actual issue. From your screenshots the only difference I can see is the suggestion box is closer to the actual cursor position in kitty than in kwrite, which is a good thing.

**Comment by page-down** [comment]
> I'm afraid I dont understand the actual issue.

The candidate box should be aligned with the beginning of the pre-edit text, as this indicates the selection of a candidate for the unconfirmed code.

The pre-edit text may also contain both the selected candidate words and the unconfirmed part. On platforms with more sophisticated APIs, the candidate box will appear in the corresponding position by moving the cursor located on the pre-edit text, which can be used to reselect the word. So the candidate box may be at the very beginning, or anywhere in the middle of the text, but never at the end.

This is also where the input method candidate box is displayed on macOS and Windows.

> ... closer to the actual cursor position ... which is a good thing.

When the cursor is moved to the second line, for example when the window width is narrow, the candidate box position remains at the initial position, which is likely to obscure the incoming pre-edit text.

By the way, under macOS, after the candidate box appears, no matter how you ask to update the position, the candidate box will never change its position. That is, at the very beginning of the pre-edit text.

**Comment by kovidgoyal** [comment]
Seems like a wash to me. Both approaches have advantages and
disadvantages. And I dont feel like refactoring kitty just to add
support for this particular Wayland quirk. Patches welcome.
