### ISSUE TITLE
prewarm-launcher.c fails to build on macOS MSG_NOSIGNAL undefined

### ISSUE THREAD

**Issue by derekschrock** [kovidgoyal/kitty#5371]
**Describe the bug**
No MSG_NOSIGNAL on macOS

**To Reproduce**
1. Build on macOS
2. See error

**Screenshots**
```
clang -DKITTY_LIB_PATH="../Resources/kitty" -Wall -pedantic-errors -Werror -fpie -O3 -I/opt/local/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -I /opt/local/include -c prewarm-launcher.c -o build/prewarm-launcher.o
prewarm-launcher.c:467:59: error: use of undeclared identifier 'MSG_NOSIGNAL'
    while ((n = sendmsg(socket_fd, &launch_msg_container, MSG_NOSIGNAL)) < 0 && errno == EINTR);
                                                          ^
prewarm-launcher.c:629:77: error: use of undeclared identifier 'MSG_NOSIGNAL'
    ssize_t n = safe_send(socket_fd, send_on_socket.buf, send_on_socket.sz, MSG_NOSIGNAL);
```

*** Solutions ***
- Like [kitty/child-monitor.c:38](https://github.com/kovidgoyal/kitty/blob/master/kitty/child-monitor.c#L38) add `#ifndef` to `prewarm-launcher.c` or `#define MSG_NOSIGNAL 0` to the `#ifdef __APPLE__` block
- Move `#ifndef` to a `.h` that's shared between the two
- build time define in `setup.py`

**Comment by kovidgoyal** [comment]
It builds fine on macOS, kitty is built on macOS CI for every commit. What version of macOS are you building on?

**Comment by derekschrock** [comment]
10.15.7 (19H2026)
