### ISSUE TITLE
Possible bug with icat

### ISSUE THREAD

**Issue by Luticus** [kovidgoyal/kitty#5372]
**Describe the bug**
after using the kitty +kitten icat any.image command the picture will display but the prompt looks a bit broken afterwards and command output is janky, Have to run reset in the terminal to fix it.

I'm using a self compiled version of the latest 25.2 release.

I'm using powerlevel10k with a zsh shell.

Also apparently happens in stock bash as well

I'm using Debian 11

Happens on local system, does not need to be over ssh. I feel like I must be doing something wrong.

**To Reproduce**
1. kitty +kitten icat any.image
2. try the ls command
3. observe prompt is janky

**Screenshots**
![image](https://user-images.githubusercontent.com/7807109/184408787-7f5cefc4-d6a3-4729-a6e2-5c1bcc43111d.png)
In the top image you can see the ls (technically it's lsd) command working as expected. In the bottom shot you can see ls after an image is displayed in the terminal. I have also tried this in bash with normal ls and it still breaks. I feel like I must have mis-configured something.

**Environment details**
```
ikitty 0.25.2 (9bb2c1a27b) created by Kovid Goyal
Linux master 5.18.0-0.bpo.1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1~bpo11+1 (2022-06-14) x86_64
Debian GNU/Linux 11 master /dev/tty

Running under: X11
Frozen: False
Paths:
  kitty: /opt/kitty/kitty/launcher/kitty
  base dir: /opt/kitty
  extensions dir: /opt/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/username@Example.com/.config/kitty/kitty.conf

Config options different from defaults:
bold_font             MesloLGS NF Bold
bold_italic_font      MesloLGS NF Bold Italic
enable_audio_bell     False
font_family           MesloLGS NF Regular
font_size             14.0
italic_font           MesloLGS NF Italic
scrollback_lines      4000
strip_trailing_spaces smart
Added shortcuts:
	kitty_mod+tab →  previous_tab
	shift+super+escape →  kitty_shell window
Removed shortcuts:
	ctrl+shift+tab →  previous_tab
Colors:
	background            #31313a   
	cursor                #ffffff   
	cursor_text_color     #000000   
	foreground            #fcfcfc   
	selection_background  #ccccff   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                username
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     /home/username@Example.com/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/username@Example.com/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_RUNTIME_DIR                     /run/user/1358601108
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      3
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    x11
	XDG_VTNR                            7


```

**Additional context**
This still occurs even with kitty --config NONE
![image](https://user-images.githubusercontent.com/7807109/184409821-cdde0656-a5e7-4048-b7ef-fed3bfbee43d.png)
*ignore the white blocks in the bash prompt, I'm redacting the user/host

**Comment by kovidgoyal** [comment]
That looks like your terminal is not being restored to canonical mode. Confirm by running stty sane and see if it restores it. As to why that's happening I have no idea, I cannot reproduce.

**Comment by Luticus** [comment]
yep it does fix it, that's odd. Is there a way to trigger that command after running the icat as a workaround? I mean that's probably a hacky way of fixing it though.  :) 

Not sure what's going on. I kinda figured if it was a big issue it would have been reported already, etc. So I've kind of just assumed that it was some misconfig on my part.

During compilation it didn't seem to complain about anything so I'm not sure what's up.

**Comment by kovidgoyal** [comment]
It's most likely something in your shell rc files that is interfering.
You can try bisecting them.

As for a workaround, create a wrapper script

```sh
#!/bin/sh

kitty +kitten icat "$@"
stty sane
```

you can of cource make it nicer, preserve the icat exit code etc.

**Comment by Luticus** [comment]
Yea i'd be all for that shell rc file thing if it was just happening in zsh, those configs are gnarly, but my bash setup is very basic, stock debian really. I dunno, perhaps I can try on a different user or machine.

What I did for now was set up a function in ~/.aliasesrc which I have sourced into my ~/.zshrc:
```
function icat() {
  kitty +kitten icat "$@"
  stty sane
}
```

**Comment by Luticus** [comment]
OK, i made some headway. I still don't fully understand WHY this is happening, but I have a lead. So what I was doing was downloading the tarball to ~/downloads, extracting, and compiling. Then I would move the application to /opt to "install" it. This is apparently where I went wrong, I guess. If I instead created a place in /opt to download and compile, then adjust perms/ownerships, the issue is gone. This leads me to believe something about the compile process is dependent on the path where the compilation took place. Also I have discovered that this happens with ALL kittens and other weird behavior also occurs like the ssh remote file open feature failing to ever load the remote file.

Not sure if this info ultimately helps, and I know the issue is closed but I thought I'd post the info just in case someone else runs into this issue.

**Comment by kovidgoyal** [comment]
You didnt tell me anything about how you compiled. The way to do it is

python setup.py linux-package

and then copy the contents of linux-package to /usr/local or wherever.
It works fine.

I am guessing you likely have mutliple kitty exes on your system causing
issues.

**Comment by Luticus** [comment]
Hah, that'll do it. Yep I totally just ran make like a goof.  :)
Fortunately while I might be completely new to kitty, I am also pretty handy with 'nix. I'm sure I don't have multiple kitty binaries running around. I think the python script is just working some magic that the make command isn't all by itself.

I'll try recompiling via the python script and see where that gets me.

Thanks so much for your help! I'm definitely enjoying learning about this terminal.

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/build/#notes-for-linux-macos-packagers
