### ISSUE TITLE
Kitty doesn't respect some keyboard mappings in X11

### ISSUE THREAD

**Issue by kovasap** [kovidgoyal/kitty#5375]
I was playing with some keyboard remappings by changing my `/usr/share/X11/xkb/symbols/us` file.  When changing my "space" key mapping like this:

```
    key <SPCE> { 
          type="PC_CONTROL_LEVEL2",
          symbols[Group1]=[    space,        BackSpace] };
```

to make ctrl+space map to BackSpace, I was surprised to see my new binding work in Chrome, but not in kitty.  Before and after my change, `showkey -a` in kitty always shows `^@` for ctrl+space.  

This also happened for other keymaps, like shift+space:

```
    key <SPCE> { [  space, BackSpace, space, space ] };
```

Is this intentional?  Is kitty overriding x11 keymaps somehow?

**Comment by kovidgoyal** [comment]
kitty uses libxkb, and it supports whatever libxkb supports, which
definitely includes key mappings, though you typically override them
with compose files. See --debug-input to get the stream of events libxkb
feeds to kitty.

**Comment by kovasap** [comment]
Interestingly, kitty does seem to be getting my "Backspace" signal, but as a "shifted_key":

```
> kitty --debug-input
Loading new XKB keymaps
Modifier indices alt: 0x3 super: 0x6 hyper: 0xffffffff meta: 0xffffffff numlock: 0x4 shift: 0x0 capslock: 0x1
Move x: 274.0 y: 228.0 grabbed: 0
Press xkb_keycode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: 57442 (LEFT_CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 0xe062 native_code: 0xffe3 action: PRESS mods: numlock text: '' state: 0 ignoring as keyboard mode does not support encoding this event
Press xkb_keycode: 0x41 clean_sym: space composed_sym: BackSpace mods: ctrl+numlock glfw_key: 32 ( ) xkb_key: 32 (space) shifted_key: 57347 (BACKSPACE)
on_key_input: glfw key: 0x20 native_code: 0x20 action: PRESS mods: ctrl+numlock text: '' state: 0 sent encoded key to child
```

Is there a way to tell kitty to use this key instead of the pure "xkb_key"? 

All these other programs receive backspace correctly: chrome, gnome settings, gnome terminal, xterm.

**Comment by kovasap** [comment]
Maybe https://github.com/kovidgoyal/kitty/blob/df3846fbb83eba02de6a0388e911e5615dd825f1/glfw/xkb_glfw.c#L934 should return the shifted keycode if it exists?

**Comment by kovidgoyal** [comment]
shifted keys and unshifted keys are needed for shortcut matching. without them you cannot robustly make shortcuts like ctrl+plus work, which could be either ctrl+(and actual plus key) or ctrl+shift+equal.

**Comment by kovasap** [comment]
Ah darn.  Is there a way to tell kitty to turn ctrl+space into backspace in the config file?  I couldn't find one in my read of the docs, but maybe I missed it.

**Comment by kovasap** [comment]
```
map ctrl+space send_text all :
map alt+space send_text all \x7f  # Backspace
```

This works for me!
