### ISSUE TITLE
Location of fish integration script

### ISSUE THREAD

**Issue by mkastner** [kovidgoyal/kitty#5380]
**Is your feature request related to a problem? Please describe.**
Don't know yet. I am experiencing cwd problems with fish shell.

**Describe the solution you'd like**
Maybe add the actual location of fish integration script in "how it works section"

https://sw.kovidgoyal.net/kitty/shell-integration/#how-it-works

to documentation.

**Describe alternatives you've considered**
Maybe I need to place the fish integration code into ~/.config/fish myself and source it from config.fish . Not sure, if that's the idea.

**Comment by page-down** [comment]
> ... the actual location of fish integration script ...

Already described in the documentation.

https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration

> Maybe I need to place the fish integration code into ...

The fish integration will be automatically enabled by default. You can also enable it manually according to the documentation. No need to copy to `~/.config/fish`.

> I am experiencing cwd problems with fish shell.

Try using an empty fish configuration folder with no kitty configuration. Please describe the attempts you made and the symptoms you encountered.

The value `last_reported` will use the reported CWD and can be used to troubleshoot problems.

```text
launch --cwd=last_reported
```

https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-cwd

**Comment by mkastner** [comment]
Thanks for your quick reply help. I will give it a shot.

And thanks for kitty!!!

**Comment by kovidgoyal** [comment]
You are welcome and if you can find a bug feel free to update this report, closing for the moment, since there is nothing actionable here
