### ISSUE TITLE
Request: Configuration for kitty shown in demo video

### ISSUE THREAD

**Issue by gandalf0079** [kovidgoyal/kitty#5382]
Kindly provide configuration for the kitty shown in demo video on the link [https://download.calibre-ebook.com/videos/kitty.mp4](https://download.calibre-ebook.com/videos/kitty.mp4)
Thanks

**Comment by kovidgoyal** [comment]
there is no configuration beyond colors and fonts. I cant recall what
the color scheme was, but the font used is Operator Mono, IIRC

**Comment by gandalf0079** [comment]
Is it running inside tmux or is that top bar part of kitty ?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/panel/

**Comment by gandalf0079** [comment]
Thanks a lot

**Comment by gandalf0079** [comment]
Would you be able to provide its config ? Thanks

**Comment by kovidgoyal** [comment]
There is no config, its a program that runs inside the top bar. And that
program is specific to my environment not for general use.
