### ISSUE TITLE
kitty @ detach-window  always opens a new OS window

### ISSUE THREAD

**Issue by HazemElmahy** [kovidgoyal/kitty#5383]
kitty @ detach-window  always opens a new OS window
I tried 
`kitty @ detach-window -t new `
`kitty @ ls` then `kitty @ detach-window -t  id:1 `
always new window

**Comment by kovidgoyal** [comment]
Works for, steps I tried:

1) kitty -o allow_remote_control=y -o enabled_layouts=tall
2) kitty @ new-window (so that there are two windows in the current tab)
3) kitty @ detach-window -t new

A second tab is created, as expected.
