### ISSUE TITLE
Add undercurl_position and undercurl_thickness

### ISSUE THREAD

**Issue by serhez** [kovidgoyal/kitty#5399]
It would be nice and consistent to have these config options that are also available for `underline` and `strikethrough`.

**Comment by kovidgoyal** [comment]
undercurl is a type of underline its position and thickness are derived
from the values for underline.

**Comment by kovidgoyal** [comment]
The undercurl has to be rendered in the space available for the underline, it cannot be the same thickness of line.

**Comment by serhez** [comment]
I see the problem now 🤔 But could we render a thicker undercurl occupying the same vertical space (thicker line, less wavy perhaps)? Do you think this is hard to implement?

**Comment by serhez** [comment]
Or, if we split up `underline_thickness` and `undercurl_thickness`, we could achieve a more visually consistent result. I would say the code below would result in more consistent visuals:

```
modify_font underline_thickness 100%
modify_font undercurl_thickness 300%
```

I attach below an underline with `underline_thickness 100%` and an undercurl with `underline_thickness 300%`; they look visually consistent to me:

<img width="238" alt="Screenshot 2022-08-22 at 15 49 58" src="https://user-images.githubusercontent.com/18057093/185951086-503111bd-33aa-4067-a9c3-650b0ed05b03.png">  <img width="94" alt="Screenshot 2022-08-22 at 15 49 29" src="https://user-images.githubusercontent.com/18057093/185951270-5b3e9b7e-02a3-4984-ac34-2c28636958ef.png">

**Comment by kovidgoyal** [comment]
Not something I am interested in, you are welcome to try relevant
function is add_curl()
And remember that your result has to look better at a wide variety of
pixel sizes/resolutions.
