### ISSUE TITLE
Can't see anything

### ISSUE THREAD

**Issue by ecosta1020** [kovidgoyal/kitty#54]
I've installed kitty to have a grasp of it, but no matter if I use the in-source version, or if I compile it to `linux-package', it doesn't respect colors in the configuration file, and all I'm shown is a black screen I can only type exit and press enter.

`glfw' examples run fine though. This is the output of `LIBGL_DEBUG=verbose MESA_DEBUG=1 bin/kitty':

libGL: Can't open configuration file /home/usr/.drirc: No such file or directory.
libGL: pci id for fd 6: 10de:0407, driver nouveau
libGL: OpenDriver: trying /usr/X11R6/lib/dri/tls/nouveau_dri.so
libGL: OpenDriver: trying /usr/X11R6/lib/dri/nouveau_dri.so
libGL: Can't open configuration file /home/usr/.drirc: No such file or directory.
libGL: Can't open configuration file /home/usr/.drirc: No such file or directory.
libGL: Using DRI3 for screen 0
Mesa: User error: GL_INVALID_ENUM in glTexBuffer(internalFormat GL_RGB32UI)

**Comment by kovidgoyal** [comment]
See the last line in the debug you posted. Apparently your gl driver does not implement glTexBuffer with GL_RGB32UI correctly. According to the opengl docs: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexBuffer.xhtml this is implemented for OpenGL >= 3.1 which is almost a decade old I think. Update your drivers and you should be fine.

**Comment by kovidgoyal** [comment]
I just committed a command line option --debug-gl that does what MESA_DEBUG does, but aborts kitty with a nice traceback on failure.

**Comment by ecosta1020** [comment]
All I can say is that I have just compiled xorg (including mesa, opengl, etc) just to run kitty, so it's all mainstream software. These are some excerpts of glxinfo's output:

    Vendor: nouveau (0x10de)
    Device: NV84 (0x407)
    Version: 17.1.0
    Accelerated: yes
    Video memory: 247MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0

OpenGL version string: 3.0 Mesa 17.1.0-devel (git-94e7b59)
OpenGL shading language version string: 1.30

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.1.0-devel (git-94e7b59)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

So, any chance I could run kiity or should I discard it?

Regards,

**Comment by kovidgoyal** [comment]
All I can say is that the graphics driver you are using does not support an eight year old OpenGL API (OpenGl 3.1 is from 2009). Not much kitty can do about that. I know of no alternate API for glTexBuffer. 

If you have updated nouveau and mesa also make sure you update glew and glfw and that all the newly updated packages are actually being used. Other than that, I am out of ideas.

**Comment by kovidgoyal** [comment]
And the precise item to test for in glx info is GL_ARB_texture_buffer_object_rgb32

```
glxinfo| grep GL_ARB_texture_buffer_object_rgb32                                
    GL_ARB_texture_buffer_object, GL_ARB_texture_buffer_object_rgb32
```

**Comment by kovidgoyal** [comment]
I've added a test for that ARB, since there are apparently systems missing it: https://github.com/kovidgoyal/kitty/commit/54e79a6901c7e9455c724684dce9616be3226ed0

**Comment by kovidgoyal** [comment]
Reference to ARB: https://khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_buffer_object_rgb32.txt

Dated Dec, 2009

**Comment by ecosta1020** [comment]
Thanks so much for your time and effort.

I'l try to track down whether this is a problem of the driver I use or what.

Regards,

**Comment by ecosta1020** [comment]
It seems nouveau (open source nvidia driver) doesn't support this at this point, or either that my hardware (NVIDIA GeForce 8600M GT) is just too old for this, not really sure, but cannot use kitty any way I've tried.

Thanks so much again for your time anyways,

Regards,
