### ISSUE TITLE
Support blinking text

### ISSUE THREAD

**Issue by RedBeard0531** [kovidgoyal/kitty#540]
I noticed this because the lightning bolts from `curl wttr.in` weren't blinking.

Example that blinks in gnome-terminal but not kitty: `echo  -e "normal|\e[5mblink\e[0m|normal"`

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in supporting blinking text. It is a feature that has a large overhead for a very limited use case.

**Comment by BornstellarEternal** [comment]
Any updates on whether you plan to support blinking text?

**Comment by jctratt** [comment]
The limited use case for blinking text is at times a critical feature; I happen to need the feature.

**Comment by ppwwyyxx** [comment]
Some users prefer rich features over speed - although kitty are already very strong on both.

Would be great if owners can reconsider this feature, even if it's disabled by default with a warning on performance.

**Comment by residualmind** [comment]
I really love kitty. But these opinionated choices make it really hard to finally adopt the kitty. No ability to disable bold (historically, the ANSI bold tag has been used to render *bright* text - that is why many (most) applications use the tag to render bright text, not bold - which is a very valid reason to disable bold rendering in a terminal. I mean, it's still a terminal, not a graphical WYSIWYG word processor.) And now I find out blink is not supported.. sad puppy.

**Comment by yermulnik** [comment]
Author is [so disgustingly pompous](https://github.com/kovidgoyal/kitty/issues/8030#issuecomment-2561952762) speaking to people in general 😒 Sadly making `kitty` less attractive 🙁

**Comment by kovidgoyal** [comment]
Excellent, another issue to lock down. Blinking text is an awesome filter.

**Comment by kovidgoyal** [comment]
Implemented in #8551
