### ISSUE TITLE
macos open command on a script not load properly

### ISSUE THREAD

**Issue by adumat** [kovidgoyal/kitty#5401]
**Describe the bug**
On macos the `open` command in a script handled by kitty not load properly all env variables and other things usually contained inside `.zshrc`.
kitty needs to be set as default app of script type file.

**To Reproduce**
1. create a test script with command like `echo $PATH`
2. execute with `./<SCRIPT>` and `open ./<SCRIPT>`
3. note different result between two execution

**Screenshots**
the content of script:
```
#!/bin/bash

echo $SHELL
echo $PATH
```

result using `./test.command`:
![image](https://user-images.githubusercontent.com/6348767/185903904-43a07714-4ab7-4c16-a362-be48e0fbbd97.png)

result using `open ./test.command`:
![image](https://user-images.githubusercontent.com/6348767/185903757-13892516-db99-4cac-b60a-8f0b6e880843.png)

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin Matteos-MacBook-Pro 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.5 BuildVersion:	21G72
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                matteoaduso

```

**Additional context**
with `kitty --config NONE` this issue not happen, but actually the file config of kitty not exist. 🤷

**Comment by kovidgoyal** [comment]
open comes from the OS, it has nothing to do with kitty. And its
environment is set by LaunchServices.

**Comment by adumat** [comment]
but why when i execute kitty with `--config NONE` all works fine?

**Comment by kovidgoyal** [comment]
Bisect your kitty.conf and find out

**Comment by adumat** [comment]
i don't have a kitty.conf -.-'

**Comment by kovidgoyal** [comment]
Then --config=NONE can make no difference to anything

**Comment by adumat** [comment]
yes, i'm agree with you.
but if i launch kitty without the option, the issue happen. with the config option the issue not happen anymore.

**Comment by kovidgoyal** [comment]
Because in one case you are launching kitty from a shell which means it inherits the shell variables in the other case you are launching it via Launch Services.

**Comment by adumat** [comment]
perhaps i've missed some steps...

i try to explain better the issue.

CASE 1
1 launch kitty as normal, using launchpad or from finder.
2 execute the script using `open SCRIPT` not work (with `./SCRIPT` yes)

CASE 2
1 from terminal of osx, launch kitty using `kitty --config NONE`
2 execute the script using `open SCRIPT` WORKS (and also `./SCRIPT`)

normally with other terminal emulator this issue not happen (other terminal like iterm, hyper or default osx terminal)
