### ISSUE TITLE
kitty shell: characters are overwritten

### ISSUE THREAD

**Issue by gnarendran** [kovidgoyal/kitty#5402]
**Describe the bug**
In a fresh installation, entered kitty shell using ctrl+shift+esc, and then typed help. All characters appearing on the screen, including the cursor, stay put, even when new characters appear in their place, right over them.

**To Reproduce**
1. sudo dnf install kitty  # Also reproduced in kitty nightly build
2. LIBGL_ALWAYS_SOFTWARE=1 GALLIUM_DRIVER=llvmpipe kitty
3. type keys ctrl+shift+esc to spawn the kitty shell - no issues so far
4. type "help" - even as we type we see the cursor rendering is not cleared as the characters are typed - so it appears like "|h|e|l|p|". Subsequently the entire output, as it scrolls, is overwritten in place and looks garbled. "ctrl+l" to clear the window takes the prompt to the top of the kitty shell window, but does not clear the garbled output. So also, backspace does not clear the previous character though the cursor moves back.

**Screenshots**
Typing "help" in kitty shell:
![typedHelp-kitty-shell](https://user-images.githubusercontent.com/23692893/185923683-f220bf14-0c29-4621-9cf6-59ba4feaf1a2.jpg)
Output of "help" in kitty shell:
![charactersOverwritten-kitty-shell](https://user-images.githubusercontent.com/23692893/185923761-f4fd8b85-b50b-4019-a2c7-6efc6fe04dba.jpg)

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux fedora 5.18.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 16 14:51:11 UTC 2022 x86_64
S
Kernel 5.18.5-200.fc36.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/gnarendran/bin:/home/gnarendran/bin/proj:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/games:.
	LANG                                en_US.UTF-8
	VISUAL                              /usr/bin/vimx -n
	EDITOR                              /usr/bin/vimx -n
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                gnarendran
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 i3
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_COLLATE                          C
	XDG_DATA_DIRS                       /home/gnarendran/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

**Additional context**
Problem is also reproduced with kitty --config NONE.

**Comment by kovidgoyal** [comment]
This will be an issue with your GPU drivers, which from your
reproductions steps appears to be a software renderer, llvmpipe. Nothing
kitty can do about it. the kitty shell will likely be triggering the bug
because it uses multipass rendering to have the kitty logo. If for some
reason you want to use llvmpipe and the kitty sheel you can workaround
it with

map kitty_mod+esc launch --allow-remote-control kitty @

which will give you a shell without the logo.

**Comment by gnarendran** [comment]
Thanks, the workaround removed the character garbling in the kitty shell.
