### ISSUE TITLE
kitty @ launch is giving a Python FileNotFoundError on macOS

### ISSUE THREAD

**Issue by garymh** [kovidgoyal/kitty#5407]
**Describe the bug**
Hi! I'm trying to run a `kitty @ launch` command using 0.25.2 on macOS 12.5.1 but I'm getting the following stack trace:

```sh
❯ kitty @ launch --title=Vim vim
Traceback (most recent call last):
  File "lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "lib/python3.9/runpy.py", line 87, in _run_code
  File "lib/python3.9/kitty_main.py", line 7, in <module>
  File "lib/python3.9/kitty/entry_points.py", line 185, in main
  File "lib/python3.9/kitty/entry_points.py", line 23, in remote_control
  File "lib/python3.9/kitty/remote_control.py", line 242, in main
  File "lib/python3.9/kitty/remote_control.py", line 151, in do_io
  File "lib/python3.9/kitty/remote_control.py", line 98, in __enter__
FileNotFoundError: [Errno 2] No such file or directory
```

**To Reproduce**
1. Run kitty with the config:
```conf
allow_remote_control socket-only
listen_on unix:/tmp/mykitty
```

2. `kitty @ launch --title=Vim vim`
3. See error

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin DarkKnight 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.5.1 BuildVersion:	21G83
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/gary/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control     socket-only
bold_font                Iosevka Mayukai Codepro Bold
bold_italic_font         Iosevka Mayukai Codepro Bold Italic
confirm_os_window_close  0
enable_audio_bell        False
font_family              Iosevka Mayukai Codepro Semibold
font_size                20.0
italic_font              Iosevka Mayukai Codepro Italic
listen_on                unix:/tmp/mykitty
macos_custom_beam_cursor True
macos_thicken_font       0.65
macos_titlebar_color     1
symbol_map:
	U+f101 - U+f208 → nonicons
tab_bar_edge             1
tab_bar_margin_width     5.0
tab_bar_style            powerline
tab_powerline_style      round
Added shortcuts:
	f3 → show_kitty_env_vars
	opt+backspace → send_text all \x17
	opt+left → send_text all \x1b\x62
	opt+right → send_text all \x1b\x66
	cmd+[ → prev_window
	cmd+] → next_window
	cmd+d → new_window_with_cwd
	cmd+u → kitten hints --type url
	cmd+z → pipe @ansi_alternate_scrollback os_window less +G -R
	cmd+backspace → send_text all \x1bw
	cmd+left → send_text all \x01
	cmd+right → send_text all \x05
Changed shortcuts:
	ctrl+shift+n → kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}
	ctrl+shift+w → send_text all \x1b[87;5u
	cmd+k → send_text all \x1bR
	cmd+n → new_tab
	cmd+w → close_window_with_confirmation ignore-shell
	shift+cmd+[ → prev_tab
	shift+cmd+d → new_window_with_cwd
Colors:
	color0                   #161821   
	color1                   #e27878   
	color10                  #c0ca8e   
	color11                  #e9b189   
	color12                  #91acd1   
	color13                  #ada0d3   
	color14                  #95c4ce   
	color15                  #d2d4de   
	color2                   #b4be82   
	color3                   #e2a478   
	color4                   #84a0c6   
	color5                   #a093c7   
	color6                   #89b8c2   
	color7                   #c6c8d1   
	color8                   #6b7089   
	color9                   #e98989   
	tab_bar_background       #40404a   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                gary
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
You can check if `/tmp/mykitty-*` still exists.
macOS will clean up the contents of '/tmp/' occasionally, so don't expect the files in the temporary folder to be there for long.

```text
https://github.com/kovidgoyal/kitty/pull/4794#issuecomment-1064095711
```

> kovidgoyal commented:
>
> /tmp has its files deleted periodically, not just at reboot, so no, it's not appropriate.
> macOS will happily delete our sockets out from under us.

Also note that `launch` will find the `vim` executable from `... :/usr/bin:/bin:/usr/sbin:/sbin` (`PATH` given by macOS launchd).
You may want to use `exe_search_path` to add other bin folder paths under macOS.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

**Comment by garymh** [comment]
@page-down Thanks for the quick reply! Is there a better directory for the socket file on macOS? I tried moving it to something like `~/.config/kitty/socket` but that didn't seem to work. 🤔 

re: `exe_search_path`: I tried just using `ls` instead of `vim` and that didn't seem to work either... I'm guessing it's something specific with the socket.

**Comment by garymh** [comment]
Oh, perhaps I should set `KITTY_LISTEN_ON` manually if changing the `listen_on` option? Or should kitty detect that?

**Comment by kovidgoyal** [comment]
That error indicates your socket file is not present. Dont use /tmp. Use an absolute path  for the socket, if you are running kitty @ outside of kitty you will need to use kitty @ --to and dont forget that the process PID is added to the path you provide in kitty.conf

**Comment by page-down** [comment]
@garymh

> Is there a better directory for the socket file on macOS?

I would put it in `~/.local/state/kitty/`.
You can also use the default cache folder `~/Library/Caches/kitty/`.

> ... I'm guessing it's something specific with the socket.

Config option `exe_search_path` is not relevant to this issue.
Just a reminder that when you run `launch`, the executable will not be looked for from the PATH under the current environment.
