### ISSUE TITLE
Rendering issue in (neo)vim

### ISSUE THREAD

**Issue by MachFour** [kovidgoyal/kitty#542]
I have noticed a rendering bug in kitty where lines of text in neovim are blanked out and the background is the wrong colour. It seems like the line below the cursor is never drawn or something.

I have found a way to reproduce this bug on my machine (which probably relies on some particular part of my config file, and maybe plugins), which basically consists of opening a .c file in insert mode with filetype plugin and indent on, and having a map so that when I type `{<enter>', the following text is inserted:
```
{
    <cursor here, indented>
}
```

If I press enter again, a new line is inserted:
```
{
    <indent>
    <cursor here, indented>
}
```

However, after I do this, the fourth line (containing the '}') is blank, and its colour doesn't match the normal background colour I've set.

I've attached a screenshot, as well as --debug-gl and --dump-bytes outputs too.
Let me know if I can clarify anything.

And also, thanks for all your hard work on Kitty! I've recently migrated from Termite ;)

[kitty-debug-gl.txt](https://github.com/kovidgoyal/kitty/files/2009449/kitty-debug-gl.txt)
[kitty-dump.bin.zip](https://github.com/kovidgoyal/kitty/files/2009450/kitty-dump.bin.zip)
![2018-05-16-23 42 08](https://user-images.githubusercontent.com/5557146/40122070-53900fb8-5966-11e8-802a-4dd52afcc891.png)

**Comment by kovidgoyal** [comment]
You're welcome and see the FAQ in the readme about using vim with a background color theme. As for neovim it has other bugs as well, do  search of neovim in the closed bug reports in kitty and you should find the details.

**Comment by kovidgoyal** [comment]
Just by-the-way I used to be a termite user too, before I decided to write kitty :)

**Comment by MachFour** [comment]
I see this issue is quite the can of worms. However, even with the workaround in your FAQ and latest (git) builds of kitty and Neovim, this issue still persists for me.
Are you saying that this is a bug in Neovim?

**Comment by kovidgoyal** [comment]
Yes, it is a bug in neovim.

**Comment by MachFour** [comment]
After several hours stepping though the source of both Neovim and Kitty in GDB, I'm going to come back and say that I actually think this might be a bug in Kitty.

Neovim never actually touches the line that gets blanked out, or any of the lines below it. However, all of the lines _below_ the one that becomes blank are properly rendered when the new line is inserted.

See my last post in https://github.com/neovim/neovim/issues/8400 for some details.

Happy to do some more digging if you can point me to the right function, but those macros in parser.c are pretty hard to navigate if you don't know what you're looking for ;P

**Comment by kovidgoyal** [comment]
First switch to usig a color theme with no background. Does the error still occur? If not, then it is almost certainly a bug in neovim. Then check if the blank line is actually blank (or is the text simply the same color as the background, you can check that wby selecting with the mouse while pressing shift)

The way to debug these kinds of things is to take the output of --dump-commands and edit it by hand, creating a minimal set that reproduces the issue (you can replay the commands with --replay-commands) Use some bisection to delete as many command from the dump as possible.

**Comment by kovidgoyal** [comment]
kitty --replay-commands /path/to/dumpfile

**Comment by kovidgoyal** [comment]
So you would do something like:

```
kitty sh -c "kitty --replay-commands /path/to/dump/file; read"
```

This will open a new kitty window which will replay the commands in the specified file and then wait for you to press enter.

**Comment by MachFour** [comment]
It doesn't seem to work...

```kitty sh -c "kitty --replay-commands /home/max/kitty-debug/nvim-init-cmds.txt; read"```

just opens a new kitty window, completely blank with a blinking cursor in the top left corner.

I can't work on this any more now, but I've attached a zip file containint the four kitty command-dump files, having split them up into the various relevant parts. The blank line only appears after the fourth, final batch of commands.

[blank-line-cmds.zip](https://github.com/kovidgoyal/kitty/files/2013537/blank-line-cmds.zip)

**Comment by kovidgoyal** [comment]
That will be becasue the dump contains code to switch to the alternate screen and then back, which means you wont see anything. Try only replaying a subset of the commands upto some draw command that you recognize and you should see the output.

**Comment by MachFour** [comment]
Okay I have made a minimal example and found the offending line.
If you delete line 47, `set margins 4 37`, then it renders the text properly. Otherwise it doesn't.

What do you make of this?

[minimal-example.zip](https://github.com/kovidgoyal/kitty/files/2015113/minimal-example.zip)

**Comment by kovidgoyal** [comment]
I'll look at it when I have a few moments.

**Comment by MachFour** [comment]
That's weird. I just tried it it xterm and termite, and they both render it correctly.... 

![2018-05-19-07 06 53](https://user-images.githubusercontent.com/5557146/40257915-4286bf90-5b33-11e8-87cc-5d7f44d6a832.png)

**Comment by kovidgoyal** [comment]
My mistake, I was looking at the empty 3rd and fourth lines, which were the same.

**Comment by MachFour** [comment]
Thank you!!!
