### ISSUE TITLE
 bug report env in conf

### ISSUE THREAD

**Issue by lilarcor** [kovidgoyal/kitty#5420]
Hello,
I am using the 0.25.2 version kitty and I setup env PS like below. When I call it in kitty, it said "cd: no such file or directory:". But If I manually call cd /Users/Joey/SeaDrive/My\ Libraries/bak/scripts/ps/, it's working. 
`env PS=/Users/Joey/SeaDrive/My\ Libraries/bak/scripts/ps/`

**Comment by kovidgoyal** [comment]
The env program is not provided by kitty, unless you mean in kitty.conf.
In which case, remove the backslash and you will be fine.

**Comment by lilarcor** [comment]
Thanks for your quick reply, it works
