### ISSUE TITLE
Hyperlinks only included in final screen of output with ansi-history

### ISSUE THREAD

**Issue by groves** [kovidgoyal/kitty#5427]
**Describe the bug**
When using `@result_handler(type_of_input='ansi-history')` in a kitten, the input sent to the kitten's stdin only contains OSC 8 hyperlinks for hyperlinks in the final screen's worth of output. Regardless of what lines are scrolled to in the history, only the final `tput lines` worth of lines have hyperlinks included. Previous lines are returned including other ANSI codes like OSC 133, they just don't have the OSC 8s.

If using `type_of_input='ansi'`, the hyperlinks for the lines shown are returned, regardless of where we're scrolled. Kitty is also able to show hyperlinks in the history on mouseover. It's only `ansi-history` that's missing the earlier ones.

**To Reproduce**
1. Run this python to create 100 links
```create_links.py
for i in range(100):
    print(f"\x1b]8;;file://blah\x1b\\{i}\x1b]8;;\x1b\\")
```
2. Run this kitten to print the first link found in `ansi-history`
```print_ansi_history.py
from sys import stdin
from re import search
from kittens.tui.handler import result_handler
from time import sleep

OSC_8_START = f'\x1b]8;(?P<params>.*?);(?P<url>.+?)(?:#(?P<fragment>.*?))?\x1b\\\\'

def main(args):
    text = stdin.read()
    m = search(OSC_8_START, text)
    print("First found", text[m.end():m.end() + 3], flush=True)
    sleep(100)

@result_handler(type_of_input='ansi')
def handle_result(args, data, target_window_id, boss):
    pass
```
3. See that it prints the first line on your screen, not 0

**Screenshots**
This shows me:
1. Running the python above to produce links
2. Using F6 to run a kitten like the above with `type_of_input='ansi'` swapped in. It finds the first link on the screen correctly
3. Scrolling and using F7 to run with `type_of_input='ansi'` again. It finds the first link on the screen after scrolling correctly
4. Using F6 to run the kitten above with `type_of_input='ansi-history'`. It finds the first link on the screen, not the 0 at the beginning of history
5. Scrolling and running the F7 `ansi-history` kitten again. It still finds 66 despite the scrolling.

https://user-images.githubusercontent.com/12270/186987946-d2735cef-87d7-4589-a620-fe35c6c88e12.mp4

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Darwin baladi.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.5 BuildVersion:	21G72
Frozen: True
Paths:
  kitty: /Users/groves/kitty-nightly/kitty.app/Contents/MacOS/kitty
  base dir: /Users/groves/kitty-nightly/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/groves/kitty-nightly/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /Users/groves/.nix-profile/bin/fish
Loaded config files:
  /Users/groves/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control               yes
bold_font                          CascadiaMonoPLRoman-Bold
bold_italic_font                   CascadiaMonoPLItalic-Bold
enabled_layouts                    ['tall:bias=68']
font_family                        CascadiaMonoPLRoman-SemiLight
font_features:
{'CascadiaMonoPLItalic-Bold': ('+ss19',),
 'CascadiaMonoPLItalic-SemiLight': ('+ss19',),
 'CascadiaMonoPLRoman-Bold': ('+ss19',),
 'CascadiaMonoPLRoman-SemiLight': ('+ss19',)}
font_size                          12.0
italic_font                        CascadiaMonoPLItalic-SemiLight
macos_option_as_alt                3
macos_quit_when_last_window_closed True
single_window_margin_width         FloatEdges(left=0.0, top=0.0, right=0.0, bottom=2.25)
tab_bar_style                      powerline
tab_powerline_style                slanted
window_border_width                (3.0, 'pt')
Added shortcuts:
	ctrl+opt+\ →  previous_window
	ctrl+opt+] →  next_window
	f4 →  kitten reterm.py
	f5 →  kitten find_and_edit.py
	f6 →  kitten print_links.py
	f7 →  kitten print_links_ansi_history.py
	f8 →  kitten linky.py
Changed shortcuts:
	cmd+enter →  launch --cwd=current
Colors:
	active_border_color                #b7bdf8   
	active_tab_background              #c6a0f6   
	active_tab_foreground              #181926   
	background                         #24273a   
	bell_border_color                  #eed49f   
	color0                             #494d64   
	color1                             #ed8796   
	color10                            #a6da95   
	color11                            #eed49f   
	color12                            #8aadf4   
	color13                            #f5bde6   
	color14                            #8bd5ca   
	color15                            #a5adcb   
	color2                             #a6da95   
	color3                             #eed49f   
	color4                             #8aadf4   
	color5                             #f5bde6   
	color6                             #8bd5ca   
	color7                             #b8c0e0   
	color8                             #5b6078   
	color9                             #ed8796   
	cursor                             #f4dbd6   
	cursor_text_color                  #24273a   
	foreground                         #cad3f5   
	inactive_border_color              #6e738d   
	inactive_tab_background            #1e2030   
	inactive_tab_foreground            #cad3f5   
	mark1_background                   #b7bdf8   
	mark1_foreground                   #24273a   
	mark2_background                   #c6a0f6   
	mark2_foreground                   #24273a   
	mark3_background                   #7dc4e4   
	mark3_foreground                   #24273a   
	selection_background               #f4dbd6   
	selection_foreground               #24273a   
	tab_bar_background                 #181926   
	url_color                          #f4dbd6   

Important environment variables seen by the kitty process:
	PATH                                /Users/groves/kitty-nightly/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /Users/groves/.nix-profile/bin/fish
	USER                                groves

```

**Comment by kovidgoyal** [comment]
I don't have time to look into this right now, but here's some info to
get you started, from a brief look:

The relevant code is as_text() in window.py

The difference between ansi-history and history happens in line 255.
These functions are defined in screen.c. The only difference between
them seems to be usage of get_range_line vs get_visual_line. I dont see
how that makes a difference, but since you have a reproducer already
setup, you can check this theory easily.

**Comment by groves** [comment]
Thanks for the pointer! Digging into it, I believe the problem is actually a little further down at https://github.com/kovidgoyal/kitty/blob/e330c38d4aec485b322ac5bbd925551ed2fe901d/kitty/window.py#L273

When as_text is called on historybuf, it creates a new ANSIBuf for rendering the lines: https://github.com/kovidgoyal/kitty/blob/e330c38d4aec485b322ac5bbd925551ed2fe901d/kitty/history.c#L487

That ANSIBuf doesn't have access to Screen's hyperlink pool, so nothing will be hyperlinked in line_as_ansi:
https://github.com/kovidgoyal/kitty/blob/e330c38d4aec485b322ac5bbd925551ed2fe901d/kitty/line.c#L353

It seems like the way to fix this would be to share the ANSIBuf or hyperlink pool between screen and historybuf. As far as I can tell, historybuf's lifetime is entirely contained inside screen's, so it would be possible for screen to give historybuf either of those. That doesn't seem great though as screen and historybuf don't have any real dependency in lifetime now and that would introduce one.

Another option would be to pass the ANSIBuf or hyperlink pool into as_text when calling it on historybuf. That would unlink their lifetimes, but it would make calling as_text more awkward.

Do you have a preference between those approaches? Or is there another approach you'd prefer?

**Comment by groves** [comment]
Works! Thanks!
