### ISSUE TITLE
page_up/page_down in move_tab_forward/move_tab_backward unexpected behavior

### ISSUE THREAD

**Issue by 2xer** [kovidgoyal/kitty#5429]
Not sure if this is a bug or intended behavior but here's the issue.

The default bindings:
`map kitty_mod+. move_tab_forward`
`map kitty_mod+, move_tab_backward`
work as I'd expect it to, it moves the tab forward/backward **only once or by 1 unit/tab**.

Instead if I set the bindings to:
`map ctrl+shift+page_up move_tab_forward`
`map ctrl+shift+page_down move_tab_backward`
whenever I try to move a tab forward/backward it goes to the **beginning/end of all the tabs**.

I'd like to mention I use `kitty_mod ctrl+shift` in my config so I tried replacing ctrl+shift with kitty_mod but it still produces the same issue.
I also use
`map ctrl+page_down next_tab`
`map ctrl+page_up previous_tab`
in my config and these work fine, they go to the next/previous tab as I'd expect it to.

**Comment by kovidgoyal** [comment]
Post all the information asked for in the issue template

**Comment by 2xer** [comment]
My bad, wasn't sure if this is a bug or expected behavior. Anyways, closing since I just decided to use , and . instead for this.
