### ISSUE TITLE
Touchscreen scrolling in terminal on Wayland enabled desktops

### ISSUE THREAD

**Issue by Luticus** [kovidgoyal/kitty#5432]
**Is your feature request related to a problem? Please describe.**
Enable touch screen based scrolling in kitty. This would make kitty more usable with touch screen enabled devices, particularly touch screen enabled laptops and tablets.

**Describe the solution you'd like**
Two finger gesture scrolling would be preferable, but if that's too much to implement, then any touch based scrolling would be better than nothing. I think the KDE terminal Konsole now supports single finger touch and drag based scrolling now.

**Describe alternatives you've considered**
The alternative is to find a different means of scrolling. This is fine on a laptop which generally sports a trackpad and keyboard, but with tablets it's particularly inconvenient. 

**Additional context**
In my case I'm using KDE and Wayland, so those are the environments I'm personally interested in it working under, but of course I'd like to see this functionality where ever possible.

**Comment by kovidgoyal** [comment]
This is not something I am interested in, but patches are welcome. You
would need to add touch support to glfw first.

**Comment by Freed-Wu** [comment]
I use gnome on Wayland. Seem that currently only alacritty support touch screen. <https://github.com/wez/wezterm/issues/4347>
