### ISSUE TITLE
Alt based nvim shortcut's for characters that require Shift not working

### ISSUE THREAD

**Issue by mokafolio** [kovidgoyal/kitty#5436]
**Describe the bug**
When hitting `alt + shit + , or .` in order to create a vim keybinding of the nature `A-<` or `A->` (which means `alt + <` and `alt + >`), this mapping won't work in kitty.

**To Reproduce**
Map something to `A-<` in vim and hit `Alt + Shift + ,`. It wont' work in kitty :(.
The output of `kitty --debug-keyboard` when pressing that combination is: ```Press xkb_keycode: 0x3b clean_sym: comma composed_sym: less mods: alt+shift glfw_key: 44 (,) xkb_key: 44 (comma) shifted_key: 60 (<)
on_key_input: glfw key: 0x2c native_code: 0x2c action: REPEAT mods: alt+shift text: '' state: 0 sent encoded key to child```

My suspicion is that the empty resulting text might be the culprit of the problem. (While it is correct behavior for text output, I don't think it is when it comes to key mappings of that nature). Just a wild guess though.

**Environment details**
I am on a us keyboard (QWERTY)
ubuntu 20.04, Kitty 0.26.0
zsh
NVIM v0.8.0-dev

I am new to kitty, let me know if I am missing something obvious. Thanks for the amazing work!

**Comment by page-down** [comment]
You mention vim in the title, yet Neovim is mentioned in the environment details, so I assume you are referring to `nvim`.

`Alt+Shift+,` works as expected with neovim nightly.

```shell
kitty --config=NONE -o macos_option_as_alt=yes nvim -u NORC -c 'map <M-S-,> :echo 1<CR>' -c 'map <A-S-.> :echo 2<CR>'
```

In insert mode press `Ctrl+V`, then `Shift+Alt+,` to get `<M-S-,>`.

For vim, the following works.

```vimscript
map ^[< :echo 1<CR>
map ^[> :echo 2<CR>
```

Press `Ctrl+V Alt+Shift+,` in vim's insert mode to insert `^[<` (terminal escape code).

**Comment by mokafolio** [comment]
Yes, my bad, I am referring to `nvim`. Your sample seems to work, so I am not quite sure what is wrong. I have the following in my nvim `init.lua` which works fine in the gnome terminal: `map('n', '<A-<>', '<Cmd>BufferMovePrevious<CR>', opts)`. After I changed it to `<A-S-,>` things work in Kitty, too. I am by no means a vim/nvim expert, so maybe the initial version I had is just not portable (as the shift is only implied?). I am not quite sure what the expected behavior is in this case. Thanks for the quick help!

**Comment by page-down** [comment]
> Your sample seems to work, so I am not quite sure what is wrong.

Because neovim added initial support for the kitty keyboard protocol in a recent version, enabling the first level of progressive enhancements.

https://sw.kovidgoyal.net/kitty/keyboard-protocol/#progressive-enhancement

When used in kitty, nvim will ask to enable and get a confirmation reply.
The GNOME terminal does not support this advanced keyboard protocol.

> I have the following in my nvim init.lua which works fine in the gnome terminal ... '<A-<>' ...
> I am not quite sure what the expected behavior is in this case.

As for why `A-<` doesn't work, I think it's because nvim will never see `<` in this keyboard mode.

You can close this GitHub issue yourself when replying, as kitty has no issues regarding this.
