### ISSUE TITLE
Underscore not visible for a some font sizes

### ISSUE THREAD

**Issue by nanangarsyad** [kovidgoyal/kitty#544]
I set kitty font size to 10.0 but makes the underscore character not visible. But increase or decrease the size made underscore visible again. 

Here's the screencast
![kitty-bug](https://user-images.githubusercontent.com/7588442/40153657-fbd6f710-59b4-11e8-99ce-dc1b9ceb1075.gif)

The only setting in `kitty.conf` I changed were these:
```
font_family     UbuntuMonoDerivativePowerline Nerd Font Regular
font_size        10.0

```

Thank you

**Comment by kovidgoyal** [comment]
This is a bug in the font, you can workaround it by using a different font or by using adjust_line_height in kitty.conf. And note that font_family can take only a single value, not fallbacks. If you want to use powerline symbols dont use a patched font, these are usually broken in various ways. Use symbol_map in kitty.conf instead.
