### ISSUE TITLE
Auto-save and resurrect session

### ISSUE THREAD

**Issue by turbothinh** [kovidgoyal/kitty#5448]
**Is your feature request related to a problem? Please describe.**
I am working on multiple projects and use start up session to seed the initial sessions when starting up Kitty. When I use the terminal, I often have multiple panes opening. I normally open only the main pane at the start for each session, then add more when I am working as needed, most of the time, the panes are opening different folders.

Sometimes, I would accidentally close the app and all the running scripts would stop, and when I open the app, I have to remember what panes has been closed and redo the entire session.

**Describe the solution you'd like**
When I used Tmux, one useful plugin was [Tmux Resurrect](https://github.com/tmux-plugins/tmux-resurrect) which solves exactly this same problem. In the case when the terminal (I used Iterm2) is closed, Tmux Resurrect actually can keep the scripts running when opening Tmux again. Not sure if this "feature" is good or bad.

I know we have discussed that it would be difficult to restore window size, etc, but personally, I think being able to preserve the session state is far more important.

**Describe alternatives you've considered**
Tmux + Tmux Resurrect

**Comment by kovidgoyal** [comment]
dup of #1197 

or if you are worried about accidental closures, use confirm_os_window_close 1
