### ISSUE TITLE
Changelog doesn't link to PRs

### ISSUE THREAD

**Issue by gerrywastaken** [kovidgoyal/kitty#545]
I was just reading through the changelog and it was hard for me to work out what exactly the changelog was referring to as it doesn't link to the associated PR.

For instance this here:
https://github.com/kovidgoyal/kitty/commit/a1ce29aab99028c74940f10cce151ced26851625#diff-de0a9b67ffe2874a076b5fdb15bad484R33

I really don't know if this fixes issues I've had with url hints or what exactly was fixed as there is no associated PR. A link to the PR would be great. I was thinking something like this:
https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md

Thoughts?

**Comment by kovidgoyal** [comment]
kitty development does not happen via PRs. I develop directly in master, IMO the PR dance is not worth the overhead. If you want to see if your issue is fixed, simply try it and see. kitty can be run directly from the source code folder, so it is trivial to try new changes.

**Comment by gerrywastaken** [comment]
@kovidgoyal 
> IMO the PR dance is not worth the overhead
How about commits SHAs? It doesn't need to be a PR.

> If you want to see if your issue is fixed, simply try it and see.
Sometimes, in fast moving projects, the documentation on how things work is sparse or out of date and so it can be very helpful to look at the code that has changed or associated tickets that were fixed.

**Comment by kovidgoyal** [comment]
There is rarely only a single commit that implements all but the most trivial bug fixes, and I am really not going to spend the time to cross reference changelog entries with lists of commits. But hey, if you wish to add references to the changelog to commits/SHAs/issue numbers feel free to send a PR, I will be happy to merge it. What gives kitty its fast moving nature is that I enjoy working on it, doing this kind of administrivia will reduce that joy and reduce the development pace of kitty. Definitely not worth the tradeoff.

If you want to browse code use git log, that's what it is for. For instance the change you are interested in actually required refactoring the entire kittens sub-system over several, non-neighboring commits (the refactoring brought many other un-related benefits).

**Comment by gerrywastaken** [comment]
Such a task can only realistically be done by the person who writes the change log as they already have this understanding of what commits represent which changes. But don't worry about it, I'm clearly not going to change your mind here and this is no longer an issue for me.

**Comment by kovidgoyal** [comment]
I wont worry about it.

**Comment by gerrywastaken** [comment]
Your changelog started adding links to PRs two releases after this request. How has the "PR dance" worked out?

![image](https://github.com/user-attachments/assets/aaf39c07-d883-4eb4-974e-00e0d7535cc9)

**Comment by kovidgoyal** [comment]
Nope, it does not. It links to pull requests from *other people* to give them credit for their work.
