### ISSUE TITLE
Custom app icon is lost on update (macOS)

### ISSUE THREAD

**Issue by tmillr** [kovidgoyal/kitty#5461]
## Describe the bug

For macOS, the [officially recommended way to update](https://sw.kovidgoyal.net/kitty/binary/#binary-install) is via:

```sh
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
```

> To update kitty, simply re-run the command.

However, running this command overwrites my custom kitty application icon (the icon that is shown in Finder, on the desktop, in the dock, etc.). Am I going to have to manually restore my custom application icon every time I update? That would be very annoying.

## To Reproduce

1. Install kitty on macOS
2. Change the app icon via [the instructions from the kitty website](https://sw.kovidgoyal.net/kitty/faq/?highlight=icon#i-do-not-like-the-kitty-icon)
3. Wait until a new version of kitty is published/released (although this step might not be unnecessary)
4. Update kitty via the officially recommended way to update (see above)

## Additional context

My system is macOS Big Sur (version 11.6.8). I am not sure whether this issue is specific to macOS or not.

I'm hoping this either gets fixed in the sh install script, or that there is another trivial, non-hacky way to keep this from happening every time I update kitty.

**Comment by kovidgoyal** [comment]
All that the install script does is mount the dmg and copy kitty.app
into /Applications for you. If that is removing the custom icon, then
you will need to take it up with Apple.

**Comment by tmillr** [comment]
Darn. Alright. 

It sounds like the app icon is stored within kitty.app (the app package/bundle, or whatever Apple calls it) itself. It appears that dragging and dropping the .icns file, in order to change/customize the app icon, simply creates a file named /Applications/kitty.app/Icon? within kitty.app.

```
/Applications/kitty.app/Icon?
```

I'm guessing that this is my custom icon I just dragged and dropped, and that it gets overwritten when updating kitty.

It sounds like I will have to figure something out myself to keep this from happening every time I update.

**Comment by tmillr** [comment]
> > It sounds like the app icon is stored within ...
> > ... a file named `Icon?` ...
> 
> No, that file is `Icon` followed by a carriage return character.

You're right about it being a carriage return, but I'm 99% sure this file is somehow associated with the app's icon because it only appears after changing the app's icon via the canonical drag & drop method. 

(I finally gave in and did some research on it, and found [this](https://superuser.com/questions/298785/icon-file-on-os-x-desktop).)

Finder is displaying the `\r` as `?`. I'm not sure why Apple is using a literal `\r` in this file's filename but whatever.

> > ... I doubt Apple is going to change where they store ...
> 
> I would suggest using the framework's API rather than messing around with low-level implementations, although the official API may still be deprecated in the future.

Which api?

> > I'm hoping ... that there is another trivial, non-hacky way ...
> 
> Save the installation command you posted as a script file. Add the steps to set the icon after the install command. You can back up and restore the custom app icon, or just set the icon again.
> 
> For example, use the command in the associated PR above to set the custom icon again after the update.

Well, here's a quick bash snippet I came up with for the time being. It relies on both the curl installation method, and the `https://sw.kovidgoyal.net/kitty/installer.sh` url, staying valid however (maybe it'd be better to use a GitHub url instead?). From now on I guess I'll just use this shell function whenever I want or need to update, and hopefully it will persist the custom icon (as you can see in the code below I'm now also using a different method to set the app icon - i.e. simply overwriting the default `kitty.icns` file within the `kitty.app` directory).

```bash
updatekitty() (
    set -euo pipefail

    local latest="$(curl -s -H 'Accept: application/vnd.github+json' https://api.github.com/repos/kovidgoyal/kitty/releases/latest | jq -r .tag_name)"

    case "$(kitty -v)" in
        *"${latest##[Vv]}"*)
            printf '%s\n' 'kitty is already up to date'
            return 0
            ;;
    esac

    if isunix; then
        if curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin; then
            if isdarwin; then
                # Mac app name convention
                mv -f /Applications/kitty.app /Applications/Kitty.app

                # Backup/keep old/default icon
                cp /Applications/Kitty.app/Contents/Resources/kitty.icns /Applications/Kitty.app/Contents/Resources/kitty.old.icns

                cp -f ~/appicons/kitty.icns /Applications/Kitty.app/Contents/Resources/kitty.icns

                # Update dock and Finder
                touch /Applications/Kitty.app
                sudo killall Finder && sudo killall Dock
            fi
        fi
    else
        printf '%s\n' "Error: updatekitty(): unsure how to install/update on non-unix system"
        return 1
    fi
)
```

I'd open a pr to change the install.sh script to handle the custom icon case on darwin only, but it sounds like @kovidgoyal does not want that. I guess it does add one more thing to maintain if/when Apple ever changes how custom Finder/Dock app icons are stored.

**Comment by page-down** [comment]
> Well, here's a quick bash snippet ...

This will break the signature of the app bundle, and then you might find that some features don't work.
If you really want to use some custom shell scripts. You just need to backup that `Icon\r` file and the extended attributes of the app bundle (folder), and then restore them. Finally check the signature `codesign -vv /Applications/kitty.app`.

> ...  change the install.sh script to ...

Not necessary, more discussion in the linked PR. However I need to find some time to finish that.

**Comment by tmillr** [comment]
Oh boy I didn't even consider that. I actually yanked that solution off of some blog post (from 2016? I think). Thanks for the info @page-down, that seems like a much better and more straightforward solution for the time being.
