### ISSUE TITLE
Apply settings for custom applications

### ISSUE THREAD

**Issue by UserDev987** [kovidgoyal/kitty#5463]
Hello,
How can I add custom configs for specific applications, for example I have a default width padding of 15 in my kitty.conf, but for neovim that looks ugly, so I need to change it back to 0 when a neovim instance is running.

**Comment by page-down** [comment]
I believe it is not easy to apply instance or OS window-wide configuration options for the program being run.

You can try using the watcher feature to check the current foreground application when the focus changes and apply the desired kitty configuration options and repaint.

https://sw.kovidgoyal.net/kitty/launch/#watchers
