### ISSUE TITLE
nohup and & are not functioning properly 

### ISSUE THREAD

**Issue by scristian9** [kovidgoyal/kitty#5465]
```shell
$ nohup kitty --session ~/.config/kitty/laravelup.conf >/dev/null 2>&1 &
$ exit
# my child session also close, old versions worked success.
````
I read that should set close_on_child_death no, but still keeps the bug.

My version is 0.26.0

**Comment by kovidgoyal** [comment]
I dont know what you are trying to do. If you want to run kitty detached
from the current session use

kitty --detach

and nohup works fine for me.
