### ISSUE TITLE
kitty_tests.crypto.TestCrypto fails on PowerPC

### ISSUE THREAD

**Issue by Blarse** [kovidgoyal/kitty#5466]
**Describe the bug**
======================================================================
```
ERROR: test_elliptic_curve_data_exchange (kitty_tests.crypto.TestCrypto)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/kitty-0.26.1/kitty_tests/crypto.py", line 18, in test_elliptic_curve_data_exchange
    alice_secret = alice.derive_secret(bob.public)
    AES256GCMDecrypt = <class 'fast_data_types.AES256GCMDecrypt'>
    AES256GCMEncrypt = <class 'fast_data_types.AES256GCMEncrypt'>
    CryptoError = <class 'fast_data_types.CryptoError'>
    EllipticCurveKey = <class 'fast_data_types.EllipticCurveKey'>
    alice = <fast_data_types.EllipticCurveKey object at 0x7fffb7f008b0>
    bob = <fast_data_types.EllipticCurveKey object at 0x7fffb7903730>
    self = <kitty_tests.crypto.TestCrypto testMethod=test_elliptic_curve_data_exchange>
OSError: [Errno 12] Cannot allocate memory
```

**To Reproduce**
1. Build kitty on ppc64le
2. run tests

**Environment details**
```
ALT Linux
Linux localhost.localdomain 5.10.53-std-def-alt1 #1 SMP Mon Jul 26 09:30:30 UTC 2021 ppc64le GNU/Linux
ppc64le-alt-linux-gcc (GCC) 12.1.1 20220518 (ALT Sisyphus 12.1.1-alt1)
Python 3.10.6
OpenSSL 1.1.1q
```

**Comment by kovidgoyal** [comment]
Sadly I dont know anything about this platform, so someone that does is
going to have to contribute a patch. Relevant code is in crypto.c

**Comment by kovidgoyal** [comment]
And if I had to guess, it is the call to mlock that is failing on this system, easy to test by commenting them out, which allows the secrets to be swapped out but does nto affect functionality in any other way.

**Comment by Blarse** [comment]
> And if I had to guess, it is the call to mlock that is failing on this system, easy to test by commenting them out, which allows the secrets to be swapped out but does nto affect functionality in any other way.
Yes, you are exactly right.

The actual problem was that PowerPC uses 64k pages (at least in my case), and RLIMIT_MEMLOCK is also 64k, so the first call to `mlock` is using all the limit, and the following `mlock`s fail with `Cannot allocate memory`

Any ideas how to fix this, other than raising the limits?

**Comment by kovidgoyal** [comment]
No, not really. If the system is incapable of using mlock() more than
once then the system is broken and should be fixed. I could make mlock
optional in kitty but that's just insecure as kitty is a long lived
process, quite likely to be swapped, and I would rather avoid doing so.

**Comment by Blarse** [comment]
I agree, this is my build environment issue. I will just disable this test case for now, and hope that the limit is bigger on the user's system. Thank you for your help.

**Comment by ogayot** [comment]
Hello. We have the same issue when building for ppc64el in Ubuntu. I will send the following patch for review in Ubuntu to disable the test:

```diff
Index: kitty-0.26.5/kitty_tests/crypto.py
===================================================================
--- kitty-0.26.5.orig/kitty_tests/crypto.py     2023-02-01 13:17:33.662880021 +0100
+++ kitty-0.26.5/kitty_tests/crypto.py  2023-02-01 13:38:34.667603266 +0100
@@ -3,12 +3,19 @@
 
 
 import os
+import resource
+import unittest
 
 from . import BaseTest
 
 
+memlock_limit, _ = resource.getrlimit(resource.RLIMIT_MEMLOCK)
+pagesize = resource.getpagesize()
+
+
 class TestCrypto(BaseTest):
 
+    @unittest.skipIf(memlock_limit <= pagesize, "RLIMIT_MEMLOCK is too low")
     def test_elliptic_curve_data_exchange(self):
         from kitty.fast_data_types import (
             AES256GCMDecrypt, AES256GCMEncrypt, CryptoError, EllipticCurveKey
```

It probably needs more work for compatibility with other OSes. Assuming we can make it work, is this a patch you would be inclined to take for kitty upstream?

Thanks

**Comment by kovidgoyal** [comment]
Yes, I am ok with it in principle
