### ISSUE TITLE
kittens.tui does not pass Ctrl+C and Ctrl+D keys to Handler.on_key_event

### ISSUE THREAD

**Issue by yurikhan** [kovidgoyal/kitty#5469]
**Describe the bug**

@alkim0 attempted to add vim-like key bindings to my kitty_grab kitten and discovered that [`map ctrl+d move page down` does not work](https://github.com/yurikhan/kitty_grab/issues/23).

They traced the issue to [these lines in `kittens.tui.loop`](https://github.com/kovidgoyal/kitty/blob/607bc845fc327c375643daa0f66b81172e6ebe2a/kittens/tui/loop.py#L333-L339) where <kbd>Ctrl</kbd>+<kbd>C</kbd> and <kbd>Ctrl</kbd>+<kbd>D</kbd> are unconditionally routed to `on_interrupt` and `on_eot` methods of the `Handler` class rather than `on_key_event`.

The consequence is that kittens cannot practically provide users with means to map a <kbd>Ctrl</kbd>+<kbd>C</kbd> or <kbd>Ctrl</kbd>+<kbd>D</kbd> key to any in-kitten command, or have to incorporate [ugly kludges](https://github.com/yurikhan/kitty_grab/pull/24/files).

I suggest that all keys should be passed to the normal `on_key_event` method for the kitten to process as it sees fit.

**To Reproduce**

1. Create a file `~/.config/kitty/diff.conf` with the following contents:
   ```
   # vim-like paging
   map ctrl+d scroll_to next-page
   map ctrl+u scroll_to prev-page

   # emacs-like paging
   map ctrl+v scroll_to next-page
   map alt+v  scroll_to prev-page
   ```
2. `kitty +kitten diff ` any two long and very different files
3. Try to scroll using Emacs-like keys: <kbd>Ctrl</kbd>+<kbd>V</kbd> <kbd>Ctrl</kbd>+<kbd>V</kbd> <kbd>Alt</kbd>+<kbd>V</kbd>
4. Observe that they work as expected
5. Try to scroll using Vim-like keys: <kbd>Ctrl</kbd>+<kbd>U</kbd> <kbd>Ctrl</kbd>+<kbd>D</kbd>
6. Observe that scrolling up works but on trying to scroll down the kitten quits

**Comment by kovidgoyal** [comment]
I decided to change the fix slightly, https://github.com/kovidgoyal/kitty/commit/5bf5454dbedfa5331cb41b6c7947c01f620a1dd9
