### ISSUE TITLE
Ubuntu package?

### ISSUE THREAD

**Issue by sssilver** [kovidgoyal/kitty#547]
Hello,

Having an Ubuntu package that we could `$ sudo apt install kitty` would be great. Cloning a source into some directory, manually installing build dependencies, and symlinking a script to invoke a binary you've compiled by yourself surely works, but it's not good system management hygiene. Package managers exist for a reason, they cleanly install/uninstall/purge software on your machine, without you having to remember "Oh yeah I installed harfbuzz to be able to build kitty, now that I don't need kitty anymore, I should remember to uninstall it".

Let's put together an Ubuntu package!

**Comment by kovidgoyal** [comment]
Look in the README, there is a link to a debian package, simply use that, since IIRC ubuntu just copies debian packages anyway.

Personally, I have better things to do than maintain millions of packages for the millions of distros out there, but feel free to contribute a ubuntu package to ubuntu if you wish, all the other linux packages of kitty are contributed by users to their respective distros.

**Comment by phocean** [comment]
Just a suggestion: snap/flatpack packaging would solve this millions of distros issue.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/binary.html

**Comment by phocean** [comment]
I know it, I am not looking for help. I am compiling it myself anyway, because I don't like such binary installs.

I am just telling you : a snap package is universal and offer advantages like direct distribution to the user and automatic updates for ALL Linux distributions.

https://snapcraft.io/

**Comment by kovidgoyal** [comment]
It's amusing that you think snap packages work on all distributions. Let
alone offer auto-updates, on all distributions. For instance, I use Arch
Linux and unless you set it up manually snapd an AppArmor are not going to be around. 

https://wiki.archlinux.org/index.php/Snap

I'd be amazed if a snap package actually worked on more distributions
than the binaries I provide.

**Comment by SolitudeSF** [comment]
> ALL Linux distributions.
snap depends on systemd

**Comment by phocean** [comment]
I understand the concept of universal is relative and will remain like this for a while. Yes, this is not going to work magically everywhere all the sudden and there will be always some distros apart.

But, it is a start.

But nevermind if you are not convinced and don't like it. I don't want to open a debate here and I am not complaining about anything. That was just a friendly suggestion.

Keep up the good work with Kitty. Just started to look at this and it is very nice so far.

**Comment by gaui** [comment]
> I'd be amazed if a snap package actually worked on more distributions
> than the binaries I provide.

Why not both? I love Snap!

**Comment by kovidgoyal** [comment]
On Tue, Jun 23, 2020 at 11:57:42AM -0700, Gudjon wrote:
> > I'd be amazed if a snap package actually worked on more distributions
> > than the binaries I provide.
> 
> Why not both? I love Snap!

Because I love my free time!
