### ISSUE TITLE
Mappable action for copy_on_select.

### ISSUE THREAD

**Issue by gnarendran** [kovidgoyal/kitty#5470]
**Is your feature request related to a problem? Please describe.**
To be able to map normal mouse left press (without shift) to copy to primary, and shifted mouse left press to copy to clipboard, keeping primary and clipboard independent, along the following lines:

1. `mouse_map left press grabbed,ungrabbed  combine : set_copy_on_select no : mouse_selection normal`
2. `mouse_map middle release grabbed,ungrabbed paste_from_selection`
...
3. `mouse_map shift+left press grabbed,ungrabbed combine : set_copy_on_select clipboard : mouse_selection normal`
4. `mouse_map shift+middle release grabbed,ungrabbed paste_from_clipboard`

In the above 2. and 4. are currently doable. But 1. and 3. are not, as copy_on_select is not a mappable action.

**Describe the solution you'd like**
It seems if there is a mappable action `set_copy_on_select <no|clipboard|a1...>` 1. and 3. could be achieved.

**Describe alternatives you've considered**
First copy to primary, and then use the copy_to_clipboard mapping (kitty_mod+c), then make another selection to copy to primary - this alternative has the disadvantage that it is impossible to copy to clipboard without clobbering the primary as well.

**Comment by kovidgoyal** [comment]
The semantics of primary selection are that any selection you do with a
mouse gets copied to the primary register, as soon as the selection is
done. This is a system wide convention in X11, and kitty respects it. 
I'm afraid I am not interested in making these semantics configurable.

**Comment by gnarendran** [comment]
OK, thanks for the prompt reply.
