### ISSUE TITLE
test_bash_integration fails env test

### ISSUE THREAD

**Issue by jamessan** [kovidgoyal/kitty#5473]
**Describe the bug**
The test added in e71b9091a3 is consistently failing for me both on 0.26.1 and master, in my Debian sid environment.

**To Reproduce**
1. `python3 setup.py build`
2. `python3 setup.py test`
3. See error

```
======================================================================
FAIL: test_bash_integration (kitty_tests.shell_integration.ShellIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/shell_integration.py", line 371, in test_bash_integration
    self.ae(env.get('ES'), 'a\n `b` c\n$d')
    env = {'BASH_SILENCE_DEPRECATION_WARNING': '1', 'KITTY_INSTALLATION_DIR': '/<<PKGBUILDDIR>>', 'LANG': 'C.UTF-8', 'PATH': '/<<PKGBUILDDIR>>/kitty/launcher:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
n:/bin:/usr/games', 'PYTHONDONTWRITEBYTECODE': '1', 'TERM': 'xterm-kitty', 'TERMINFO': '/<<PKGBUILDDIR>>/terminfo'}
    ps1 = 'line1\nprompt> '
    pty = <kitty_tests.PTY object at 0x7f7baaa334c0>
    q = '/tmp/tmpnhdocdqj/testing-cwd-notification-🐱'
    redrawn = <function ShellIntegration.test_bash_integration.<locals>.redrawn at 0x7f7ba73b4c10>
    run_test = <function ShellIntegration.test_bash_integration.<locals>.run_test at 0x7f7ba73b4b80>
    self = <kitty_tests.shell_integration.ShellIntegration testMethod=test_bash_integration>
    setup_env = <function ShellIntegration.test_bash_integration.<locals>.setup_env at 0x7f7ba73b67a0>
AssertionError: None != 'a\n `b` c\n$d'
```

## Bash version
```
% bash --version
GNU bash, version 5.2.0(1)-rc2 (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

## Python3 version
3.10.6

**Comment by kovidgoyal** [comment]
And this sommit should give us more info when the test fails: https://github.com/kovidgoyal/kitty/commit/c455fea72919aab26a2e82d8ea0e4353ab74c59c

**Comment by kovidgoyal** [comment]
Does the clone-in-kitty command work for you in kitty itself when using
bash as the shell?

**Comment by kovidgoyal** [comment]
That looks like your bash is built in debug mode, I am not familiar
enough with bash to know all the side effects of that, but presumably if
you get hold of a normal bash it should work.

**Comment by kovidgoyal** [comment]
And make sure you have a working base64, other than that I dont have any suggestions. This what you should see with a normal bash:

```
'[bash.bashrc]\nclone-in-kitty\nline1\nprompt> clone-in-kitty\nline1\nprompt> '
```

**Comment by jamessan** [comment]
This is the normal Debian bash binary, although it _is_ an RC release which seems to [make it build](https://sources.debian.org/src/bash/5.2~rc2-2/configure.ac/#L43-L45) with `-DDEBUG`.  Maybe the test should be skipped if `bash --version` reports a "debug" version to avoid this flakiness.

**Comment by kovidgoyal** [comment]
Feel free to send a PR to skip the test for DEBUG bash, I will merge.

**Comment by kovidgoyal** [comment]
You would need to add your check to the bash_ok() function.

**Comment by kerneis-anssi** [comment]
Unfortunately it doesn't break only the tests. On my recently updated Debian (where bash now is a DEBUG build), I get the following line whenever I open a kitty terminal:
```
bash: DEBUG warning: command_builtin: running execute_command for `base64'
```
This impacts at least kitty 0.24, 0.26.3, but not 0.21.2 (the version shipped by Debian).
