### ISSUE TITLE
Wrong Font Size on Mixed Monitor Scaling Setup

### ISSUE THREAD

**Issue by philschenker** [kovidgoyal/kitty#5476]
**Describe the bug**
I use kitty on a Manjaro Gnome installation which is up-to-date. The Monitor setup I use is as follows:
* Notebook 14" 3840x2160 at **200%** scale
* 40" 3840x2160 at **100%** scale (used as primary monitor in gnome)

If I open kitty it shows on my primary monitor (40", 100% scaling) but it shows double the font-size that I have set it up to. after issuing the shortcuts:

```
change_font_size all -2.0
change_font_size all 0
```

The font is scaled correctly.

Another way to recover the font-size is to drag kitty to the notebook screen and back to the 40" screen.

I would expect kitty to start having the correct font-size on the monitor is being started on.

**To Reproduce**
1. Setup two different monitors in Gnome
2. Setup the (in settings) second monitor to 100% and (in settings) first monitor to 200% scaling
3. Use the 100% scaling monitor as your primary monitor in Gnome settings
4. Start kitty
5. I expect the font size to be twice as large as it would be on the 200% scaled monitor

** Screenshots **
Not really applicable, I could only show that the font-size changes which I already described in detail

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux philippe-pc 5.19.1-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 13 06:34:52 UTC 2022 x86_64
Manjaro Linux 5.19.1-3-MANJARO  (philippe-pc) (/dev/tty)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.3.7
DISTRIB_CODENAME=Ruah
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/pschenker/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.9
box_drawing_scale          (0.001, 1.0, 1.5, 1.0)
dynamic_background_opacity True
font_family                Cantarell
linux_display_server       wayland
scrollback_lines           50000
select_by_word_characters  @-./_~?&=%+
Added shortcuts:
	ctrl+shift+$ → set_background_opacity default
	ctrl+shift+ä → set_background_opacity +0.02
	ctrl+shift+ö → set_background_opacity -0.02
Changed shortcuts:
	ctrl+shift+, → change_font_size all -2.0
	ctrl+shift+- → change_font_size all 0
	ctrl+shift+. → change_font_size all +2.0
Colors:
	background                 #181818   
	color0                     #485867   
	color1                     #b38686   
	color10                    #6eb36c   
	color11                    #aab386   
	color12                    #868cb3   
	color13                    #b386b2   
	color14                    #1ec3c3   
	color15                    #e3efef   
	color2                     #6eb36c   
	color3                     #aab386   
	color4                     #868cb3   
	color5                     #b386b2   
	color6                     #1ec3c3   
	color7                     #b0c5c8   
	color8                     #8299a1   
	color9                     #b38686   
	foreground                 #b0c5c8   

Important environment variables seen by the kitty process:
	PATH                                /home/pschenker/.local/bin:/home/pschenker/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/vim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                pschenker
	XDG_MENU_PREFIX                     gnome-
	LC_ADDRESS                          de_CH.UTF-8
	LC_NAME                             de_CH.UTF-8
	LC_MONETARY                         de_CH.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            de_CH.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   de_CH.UTF-8
	LC_TELEPHONE                        de_CH.UTF-8
	LC_MEASUREMENT                      de_CH.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             de_CH.UTF-8
	XDG_DATA_DIRS                       /home/pschenker/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	LC_NUMERIC                          de_CH.UTF-8

```

**Additional context**
`kitty --config NONE` shows the same issue.

**My kitty.conf**
Without all the comments
```
background #181818
background_opacity 0.9
bold_font        auto
bold_italic_font auto
box_drawing_scale 0.001, 1, 1.5, 1
    color0   #485867
    color10  #6eb36c
    color11  #AAB386
    color12  #868CB3
    color13  #B386B2
    color14  #1ec3c3
    color15  #E3EFEF
    color1   #B38686
    color2   #6eb36c
    color3   #AAB386
    color4   #868CB3
    color5   #B386B2
    color6   #1ec3c3
    color7   #B0C5C8
    color8   #8299A1
    color9   #B38686
dynamic_background_opacity yes
enabled_layouts *
font_family      Cantarell
foreground #B0C5C8
italic_font      auto
linux_display_server wayland
map kitty_mod+$    set_background_opacity default
map kitty_mod+ä    set_background_opacity +0.02
map kitty_mod+,     change_font_size all -2.0
map kitty_mod+.     change_font_size all +2.0
map kitty_mod+delete clear_terminal reset active
map kitty_mod+minus change_font_size all 0
map kitty_mod+ö    set_background_opacity -0.02
remember_window_size  yes
scrollback_lines 50000
select_by_word_characters @-./_~?&=%+
```

**Comment by kovidgoyal** [comment]
Provide the information asked for in the issue template

**Comment by kovidgoyal** [comment]
Not sure I understand your issue. Font sizes in kitty are specified in points which is a physical unit, 1/72 of an inch. That means a font at a particular size is rendered the same physical size regardless of monitor scaling. So the font will look the same size on both monitors. If you mean something else, let me know.

**Comment by philschenker** [comment]
Yes I mean something else :slightly_smiling_face:. It does indeed look the same, but please try to reproduce it how I described it. The issue is that initially kitty does not check on which scaling monitor it is and depending where it is opened shows the wrong font size.
When dragging between the two screens the issue resolves itself. That's why I believe some hook somewhere is missing.

**Comment by kovidgoyal** [comment]
On startup in wayland there is no way for a client to know which monitor
it is on until the window is displayed. However once the window is
displayed the compositor is supposed to send the client events notifying
it of this. I am fairly certain your issue is caused by the mutter
compositor not doing this, or by the existing workaround in kitty for
mutter's initial empty configuration event. You can run kitty with
--debug-rendering to get a log. I'm afraid I dont currently have an
extra monitor to test this with, and my patience with GNOME+Wayland
issues is anyway wearing very thin, so patches are most welcome.

**Comment by philschenker** [comment]
Thanks for the feedback!

**Comment by philschenker** [comment]
Thanks for the feedback! I tried now using Sway and it works. Thanks anyway for your patience and the great work on kitty! It seems I will again use Sway a bit more again..

**Comment by kovidgoyal** [comment]
you are welcome. if you feel like debugging/working arnd the issue with
mutter, let me know I will give you pointers where to start.

**Comment by enewbury** [comment]
Understand that gnome/wayland isn't a priority, but adding a screencast here for additional documentation.  Would it make sense to reopen the issue in case someone in the community has the knowledge/time to contribute?


https://user-images.githubusercontent.com/4422419/190506979-5add69c4-5a21-4ef1-9c72-3eeecacfc8a3.mp4

**Comment by kovidgoyal** [comment]
They are welcome to do so, the closed status of the issue doesn't prevent
anyone from sending a PR. I will be happy to review such a PR and/or
provide any needed guidance.
