### ISSUE TITLE
kitty 0.26.0 broke background opacity control

### ISSUE THREAD

**Issue by fieraoh** [kovidgoyal/kitty#5479]
OS: Fedora 36 Linux

The background is fully opaque, ignoring whichever value set in the config file.

I can verify that the 0.25.2 binary does work while other versions and up to 0.26.2 have broken support.

**Comment by kovidgoyal** [comment]
I cannot reproduce with

kitty --config NONE -o background_opacity=0.5

not to mention there were no opacity related changes in the entire 0.26
series.

**Comment by fieraoh** [comment]
well, could you reproduce using wayland, it is working fine on xorg.

**Comment by kovidgoyal** [comment]
Yes, I tested it on wayland, under 3 different compositors.

**Comment by vars1ty** [comment]
> Yes, I tested it on wayland, under 3 different compositors.

tried it on Hyprland? worst case I'll go through the commit history by hand and see what breaks it.

**Comment by kovidgoyal** [comment]
Nope, there are limits to how many hoops I am willing to jump through
for the idiocy that is wayland. It works under sway, kwin and mutter. If
it doesnt work in hyprland, report it there.

**Comment by TKasperczyk** [comment]
This commit broke it: https://github.com/kovidgoyal/kitty/commit/fa823a37aed99ce3f1cc43f9b21b3e2952535613
When I switch the repo to the one before it, i.e. 17f67fbe28ea678104d55a905abbc6fdaf6d5a51 , it works perfectly fine.

**Comment by kovidgoyal** [comment]
That would imply hyprland is broken for all glfw using applications.
https://github.com/glfw/glfw/commit/6281f498c875f49d8ac5c5a02d968fb1792fd9f5

Report it there.

**Comment by fieraoh** [comment]
It's not working under mutter 42.4. Could you share with me the version of mutter you've tested this on?

**Comment by kovidgoyal** [comment]
42.4

**Comment by fieraoh** [comment]
Good grief, could it be an Nvidia driver issue? What really puzzles me is that the previous versions of kitty definitely do work and I am using the exact same configuration file.

**Comment by kovidgoyal** [comment]
Hard to say, there have been no changes in kitty rendering code. There was one in glfw which @TKasperczyk found, you can try if that is causing your issue.

**Comment by kovidgoyal** [comment]
Also make sure you are running under wayland not x11. press ctrl+shift+f6

**Comment by fieraoh** [comment]
Yeah looks like I would have to do so, I have set it to explicitly use Wayland through the config file, also, it's not like you could miss the native window decorations  🐱

**Comment by kovidgoyal** [comment]
I tested it on hyprland as well, works for me. I am guessing this is some GPU driver specific bug in the egl present opaque extension. Both of you must be on nvidia?? I am on an intel gpu

**Comment by fieraoh** [comment]
I am using Nvidia (515.65.01)
