### ISSUE TITLE
Is it possible to show tabbar in place of menubar?

### ISSUE THREAD

**Issue by singlexyz** [kovidgoyal/kitty#5485]
When using vim, the tabbar always occupies a line, but not having a tabbar affects me again.

<img width="1440" alt="截屏2022-09-07 20 39 38" src="https://user-images.githubusercontent.com/4456413/188880477-a14d68df-d432-47bf-9c39-44bd98804f91.png">

**Comment by kovidgoyal** [comment]
No, it isnt.

**Comment by singlexyz** [comment]
> No, it isnt.

Can cover the tabbar in the upper right corner without occupying the position?
Like overlay.
