### ISSUE TITLE
Send text on click -> crash

### ISSUE THREAD

**Issue by locriacyber** [kovidgoyal/kitty#5488]
**Describe the bug**
I was making a `self:` to echo back the link clicked to STDIN. However, using `send_text` action on click would crash Kitty.

**To Reproduce**
1. append to `~/.config/kitty/open-actions.conf`
```
# self:// - echo back link clicked
protocol self
#action remote_control send-text ${URL}
action  send_text all \x1b[5noooo'
```

2. Open new kitty window
3. Run `printf '\e]8;;self://example.com\e\\This is a link\e]8;;\e\\\n'`
4. Click the lick
5. kitty crash with SIGSEGV

**Env**
```
kitty 0.26.2 created by Kovid Goyal
Linux x17 5.19.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 03 Sep 2022 15:26:49 +0000 x86_64
Artix Linux 5.19.6-zen1-1-zen (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
allow_hyperlinks 3
Removed mouse actions:
	left click ungrabbed →  mouse_handle_click selection link prompt

Important environment variables seen by the kitty process:
	PATH                                :)
	LANG                                en_US.UTF-8
	EDITOR                              kak
	SHELL                               /usr/bin/fish
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :0
	USER                                user
	XDG_SEAT                            seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      1
	XDG_VTNR                            1
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SESSION_TYPE                    tty
```

**Comment by kovidgoyal** [comment]
Does not crash for me, I get ooo echoed to the terminal, as expected.
And if I run cat -v before clicking the link, I get

^[[5noooo

also as expected.

I see you are running a distro package, try using the official kitty
binaries, or otherwise build from source with make debug and post a
backtrace.

https://sw.kovidgoyal.net/kitty/build/

**Comment by locriacyber** [comment]
It didn't crash this time, but still didn't work.

I have `allow_hyperlinks ask`, and it worked when I set it to `yes`

**Comment by kovidgoyal** [comment]
That will be because the window the text is being sent to is the
confirmation popup window.
