### ISSUE TITLE
Mac OS alt arrow

### ISSUE THREAD

**Issue by monouser7dig** [kovidgoyal/kitty#549]
pressing alt+ arrow left/ right inserts 3D/3C into the terminal instead of moving one word left/ right (as default Mac terminal does).
I tried `macos_option_as_alt yes` and `macos_option_as_alt no`, both have the same behavior.

thanks in a advance for any help !

macOS 10.13.4 
kitty 0.9.1

(additionally if you set a opacity < 1, macos_titlebar_color background is ignored)

**Comment by kovidgoyal** [comment]
That is by design. alt+arrow in kitty acts the same way on all operating systems. 

And read the help text for macos_titlebar_color in kitty.conf.

**Comment by monouser7dig** [comment]
> And read the help text for macos_titlebar_color in kitty.conf.

thanks for the heads up
