### ISSUE TITLE
Update broke QMK auto-shift

### ISSUE THREAD

**Issue by herschelrs** [kovidgoyal/kitty#5492]
A recent (ish?) update broke QMK's auto-shift in kitty. QMK is a custom keyboard firmware which has a feature where keys can be made to automatically send a shifted keycode if held for longer than a defined length of time. Kitty is ignoring the shift in these presses, and is the only program on my computer, under windows or linux, to do so. I'm running kitty 0.21.2 on ubuntu 22.04. This happened after I ran an apt-upgrade, and canonicals repos are likely decently far behind the development version of kitty, so this might have been due to an update from quite some time ago. I imagine that the change is downstream of [the changes here](https://sw.kovidgoyal.net/kitty/keyboard-protocol/)

Running `kitty +kitten show_key -m kitty`:
normal m key press:
```
NumLock+m PRESS m
CSI 109 ; 129 ; 109 u

NumLock+m RELEASE 
CSI 109 ; 129 : 3 u
```

normal shift+m (from my laptop's internal keyboard, no auto-shift possible):
```
NumLock+LEFT_SHIFT PRESS 
CSI 57441 ; 129 u

Shift+NumLock+m PRESS M
CSI 109 : 77 ; 130 ; 77 u
Shifted key: M 

Shift+NumLock+m RELEASE 
CSI 109 : 77 ; 130 : 3 u
Shifted key: M 

Shift+NumLock+LEFT_SHIFT RELEASE 
CSI 57441 ; 130 : 3 u
```

auto-shifted m:
```
Shift+NumLock+LEFT_SHIFT PRESS 
CSI 57441 ; 130 u

NumLock+m PRESS m
CSI 109 ; 129 ; 109 u

NumLock+m RELEASE 
CSI 109 ; 129 : 3 u

NumLock+LEFT_SHIFT RELEASE 
CSI 57441 ; 129 : 3 u
```

**Comment by kovidgoyal** [comment]
I'm afraid I have no way to debug issues with custom keyboard firmware.
If you want help you will need to build kitty from source and be
prepared to write code. https://sw.kovidgoyal.net/kitty/build/ 
And your version of kitty is ancient. Run up-to-date binaries, at least:
https://sw.kovidgoyal.net/kitty/binary/
