### ISSUE TITLE
Alternating colors for tab bar

### ISSUE THREAD

**Issue by krissi** [kovidgoyal/kitty#5499]
To have a better overview about the current tabs, it would be nice to have alternating colors for background tabs. This would help especially when using a slim delimiter.

![image](https://user-images.githubusercontent.com/436758/189705540-2e90d5ae-2fd1-492b-87c0-a91f166fbc9d.png) (Tab D is selected)

Thanks for considering

**Comment by kovidgoyal** [comment]
Not something I am interested in implementing. it will require a new config value just for this. But you can customize tab bar drawing however you like yourself, see #4447
