### ISSUE TITLE
line wraps insert new lines when copying

### ISSUE THREAD

**Issue by mmlb** [kovidgoyal/kitty#55]
I have kitty open and I'll type in a command that is longer than the terminal is wide, so the line wraps. I press enter to run the command and it all works fine.

If I press the up key, zsh will go through history and pressing enter works.

But if I select with mouse, copy with Control-C, and paste with Control-V, new lines are inserted where the lines wrapped.
![bad-kitty](https://cloud.githubusercontent.com/assets/708570/23773142/e42b233a-04eb-11e7-95cb-fbe19be6f19b.gif)

**Comment by debugloop** [comment]
This appears to be the case again on `0.26.5` with `-c NONE`. It does not affect command output, just when selecting the actual command.

**Comment by page-down** [comment]
> ... when selecting the actual command.

@debugloop

Are you using the fish shell?
You can try the nightly release, which has solved the issue.

**Comment by debugloop** [comment]
I am, thanks for the hint, will do!
