### ISSUE TITLE
Support for tmux extended keys

### ISSUE THREAD

**Issue by hovsater** [kovidgoyal/kitty#5508]
**Is your feature request related to a problem? Please describe.**

I'm currently using [Iterm2](https://iterm2.com/) and I have [extended-keys](
https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys) enabled in `.tmux.conf`. The benefit of this is that iTerm2 automatically enters `modifyOtherKeys Mode 1` upon entering [tmux](https://github.com/tmux/tmux/wiki). This is nice because it allow me to use keybindings such as `C-enter` and `C-S-enter` in my [editor](https://gitlab.com/craigbarnes/dte) of choice. dte does support Kitty's protocol but I can only ever make use of it outside of tmux. While I understand that [Kitty's keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) is superior, it does not look like tmux supports it yet.

**Describe the solution you'd like**

Some sort of compatibility with tmux's extended keys option. xterm, mintty, iTerm2 and most recently WezTerm all support it.

**Describe alternatives you've considered**

The alternative would be not to use tmux.  While a solutiin, it's not a realistic one. I use tmux heavily in my workflow (especially having sessions I can switch between).

**Additional context**

While digging through previous issues I found https://github.com/kovidgoyal/kitty/issues/4075. My understanding is that there was backwards compatibility previously but it was eventually removed. If so, I guess there's not much that can be done here except reaching out to tmux and ask them to support Kitty's protocol.

**Comment by page-down** [comment]
> ... I found # 4075 ... there's not much that can be done here except ...

You've already found the answer, which is described in the GitHub issues you pointed out.
Maybe someday kitty can support daemon mode to replace tmux.
