### ISSUE TITLE
map kitty_mod+1 first_window does not work under MacOS

### ISSUE THREAD

**Issue by mdbevilacqua** [kovidgoyal/kitty#5509]
It seems to me that the binary I downloaded using `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin` will not allow me to change the key map settings. I'd like to map command+1 to first_window, etc. 

MacOS version: 12.5.1

Kitty Version:
kitty 0.26.2 created by Kovid Goyal

Relevant entries from my kitty.conf:
kitty_mod ctrl+shift

map kitty_mod+1 first_window
map kitty_mod+2 second_window
map kitty_mod+3 third_window
map kitty_mod+4 fourth_window
map kitty_mod+5 fifth_window
map kitty_mod+6 sixth_window
map kitty_mod+7 seventh_window
map kitty_mod+8 eighth_window
map kitty_mod+9 ninth_window
map kitty_mod+0 tenth_window

-------
I have tried multiple variances of the following codes and nothing changes:

super 0x37
kitty_mod 0xe064
super 0xe064

map super+0x12 first_window
map super+0x13 second_window
map super+0x14 third_window

map super+0x31 first_window
map super+0x32 second_window
map super+0x33 third_window

map 0x37+0x31 first_window
map 0x37+0x32 second_window
map 0x37+0x33 third_window

map 0x37+0x12 first_window
map 0x37+0x13 second_window
map 0x37+0x14 third_window

**Comment by page-down** [comment]
Please give more information based on the GitHub issue template and don't ignore those instructions.

> ... I'd like to map command+1 to first_window ...

Then configure this key instead of `ctrl+shift+1`.
Also, under macOS, `cmd+1` performs the `first_window` action by default, no need to configure it.
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.First-window

Exit kitty completely and run it again to take effect.

**Comment by mdbevilacqua** [comment]
Thank you. This works for me.

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
