### ISSUE TITLE
url detection when followed by a parenthesis

### ISSUE THREAD

**Issue by roylez** [kovidgoyal/kitty#551]
One IRC channel I am in everyday has a bot from time to time sends links like `(https://xxx.com/xxxxxxxx)`, in this case kitty regards `)` as part of url. I have to fix the url every time after clicking it.

Parenthesis may be valid character to be kept in a url, but if it is the last character of a url, it could be very likely a mistake.

**Comment by kovidgoyal** [comment]
I cannot replicate this with current master, hovering mouse over (http://moo.com) does not highlight the trailing parenthesis.

**Comment by ssoriche** [comment]
I have seen this too, hovering the mouse works correctly, but using `<ctrl><shift>e` to parse the URLs and allow me to select them, extra characters like the aforementioned `)`, or timestamps from the next line, often appear.

They end up requiring editing the URL in the browser to strip the characters, if the site doesn't redirect on errors.

**Comment by kovidgoyal** [comment]
I dont understand what you are saying. Why shouldn't `http://www.cbc.ca/news/world/explosive-eruption-hawaii-kilauea-big-island-volcano-plume-1.466717615:06%3Cnick%3E` be sent to the browser? There is no a-priori reason kitty should remove <nick> from the URL

**Comment by ssoriche** [comment]
Sorry, let me capture what the actual conversation looks like in IRC:
```
14:44<othernick> Kilauea popped -
                                http://www.cbc.ca/news/world/explosive-eruption-hawaii-kilauea-big-island-volcano-plume-1.4667176
15:06<nick> Wow!
```
When detecting the URL, kitty is including the timestamp from the next message and the `<nick>` indicator as part of the URL.

`<ctrl><shift><click mouse>` captures the URL correctly (terminated at the `1.4667176`). While `<ctrl><shift>e` terminates at the space before `Wow!`.

**Comment by kovidgoyal** [comment]
I dont see how that's possible, the url hints kitten only searches for URLs in a single line at a time. Try capturing the screen contents by pressing ctrl_shift_h which will open the screen in less and then pressing s to save to a file. Post the cpature.

**Comment by kovidgoyal** [comment]
Actually dont do that, instead run kitty with 

```
kitty --dump-bytes=/tmp/kitty.bin
```

then when this problem occurs post /tmp/kitty.bin

**Comment by kovidgoyal** [comment]
And I created a simple test case for this:

save the following as url.py
```py
from kitty.utils import screen_size_function

screen_size = screen_size_function()()

print('http://'.ljust(screen_size.cols, 'a'))
input('bbbb')
```

Then run it with

```
kitty kitty +launch url.py
```

Press ctrl+shift+e

see that detected URL stops at the end of the first line.

Are you sure you are running up-to-date kitty?

**Comment by ssoriche** [comment]
I've restarted kitty with the parameters requested above and now it's not doing it. Which isn't a surprise really as the last time I restarted kitty it functioned properly for a while. I'll keep it running and see what happens.

**Comment by ssoriche** [comment]
Does this help:

```
set_title Choose URL
screen_cursor_position 1 1
screen_erase_in_display 2 0
select_graphic_rendition 90 
draw  ❐ irc  ssoriche  1  irssi   2 nvim   3 su   4 zsh   5 nvim   6 docker                             thundercracker   
select_graphic_rendition 39 
screen_carriage_return
screen_linefeed
select_graphic_rendition 90 
draw 10:06<scruffy> 
select_graphic_rendition 39 
select_graphic_rendition 30 
select_graphic_rendition 42 
select_graphic_rendition 1 
draw 1
select_graphic_rendition 39 
select_graphic_rendition 49 
select_graphic_rendition 22 
select_graphic_rendition 97 
select_graphic_rendition 1 
draw ttp://www.michaelgeist.ca/2018/05/worldsworstpricing/10:06<AzDesktop>
select_graphic_rendition 39 
select_graphic_rendition 22 
select_graphic_rendition 90 
draw  wish he'd back it up a bit to make you feel like you are IN the truck10:06<AzDesktop> wow
select_graphic_rendition 39 
screen_carriage_return
screen_linefeed
select_graphic_rendition 90 
```

I noticed this after switching tmux panes. I'm running kitty 0.9.1.

**Comment by kovidgoyal** [comment]
That just shows your URL does not have a line break after it, which we already know. The question is why does it not have a line break after it? Presumably that is what your IRC program is outputting.

**Comment by ssoriche** [comment]
This is what I see:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/19838/40244806-ddfba5aa-5a91-11e8-93b8-e8c9841915d5.png">

**Comment by kovidgoyal** [comment]
That doesn't really help, I need the output from --dump-bytes

**Comment by kovidgoyal** [comment]
Oh and I just noticed you are using tmux. tmux tends ot screw lots of things up, see if you running outside tmux fixes it.

**Comment by kovidgoyal** [comment]
This commit should also help: https://github.com/kovidgoyal/kitty/commit/ad1109b6fe0a6802ca4f77182a7a0b36086b3e9f

Since it now uses the screen geometry it should never continue a URL that ends before the end of the line.

**Comment by vorburger** [comment]
FYI I'm still seeing this problem, with a build tool that prints e.g. ` (see https://errorprone.info/bugpattern/UnnecessaryFinal)` into a `tmux 3.3a` session inside `kitty 0.26.5`, the URL sent to the Browser still includes the trailing `)`.

**Comment by kovidgoyal** [comment]
Nowadays, this is user configurable https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.url_excluded_characters  if you dont want parentheses add it to the setting. But the actually correct solution is to use terminal hyperlinks for urls, thereby removing the need for the terminal to guess the extent of the URL.
