### ISSUE TITLE
Kitty can not open gemini links with `kitty +open` but clicking links are perfectly okay

### ISSUE THREAD

**Issue by roylez** [kovidgoyal/kitty#5510]
**Describe the bug**

Kitty does not know how to open gemini links with `kitty +open` but clicking links are perfectly okay.

**To Reproduce**

- Install amfora, and put the following in open-actions.conf

```
protocol gemini
action launch --type=tab --tab-title GEMINI amfora ${URL}
```

- Run this command and it will fail with a `Open URL Error`, however, clicking the url directly it will bring up amfora as expected.

```
kitty +open gemini://gemini.circumlunar.space/docs/gemtext.gmi
```

**Comment by page-down** [comment]
> ... open gemini links with `kitty +open` ...

You are looking at the wrong config file name, it is `launch-actions.conf`.

https://sw.kovidgoyal.net/kitty/open_actions/

**Comment by roylez** [comment]
Thanks a lot. This makes sense now. However it looks like `--type=tab` does not work in `launch-options.conf` and I do not if this is by design.

**Comment by kovidgoyal** [comment]
--type works fine in launch-actions.conf

If it isnt for you then post a complete reproducer.
