### ISSUE TITLE
Escape sequence for custom scroll points

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#5515]
**Is your feature request related to a problem? Please describe.**
When searching in files with e.g. grep/rg I sometimes get large results, so it would be nice to be able to press a key to scroll to the next/previous match.

**Describe the solution you'd like**
After you added support for scrolling to next/previous shell prompt I've been using it a lot and realized it's a really nice feature. However, it has made me want the same thing for search results from grep/rg and potentially other programs.

It would be nice if there was some escape sequence a program can output so the terminal emulator can scroll to these points the same way as it scrolls to shell prompts.

**Describe alternatives you've considered**
An alternative would be to just output the start shell prompt escape sequence from the program. However, it would be nice to be able to separate shell prompts and other scroll points so it was still possible to jump directly to the next/previous shell prompt.

I haven't talked to any others about getting support for this into e.g. grep/rg, which would be nice to do after an escape sequence is settled, but even without support in those programs it would be possible to use it by inserting them myself e.g. like this:

```
rg -p --colors path:fg:0,0,0 <pattern> | sed 's/\x1b\[38;2;0;0;0m/\x1b]133;A\a\x1b[35m/g'
```

**Comment by trygveaa** [comment]
Thanks for the suggestion. You're right, that works. Would still be nice to have a dedicated escape sequence for it, so it could be built into tools, but I suppose it's a long shot.

If anyone is interested, here is the kitten I made for scrolling to next/previous link (the one you linked didn't do what I wanted as far as I could see):

```
import re
from typing import List, Optional

from kittens.tui.handler import result_handler
from kitty.boss import Boss

OSC8_START = re.compile("\x1b]8;;[^\x1b]")


def main(args: List[str]) -> Optional[str]:
    pass


@result_handler(no_ui=True)
def handle_result(
    args: List[str], answer: str, target_window_id: int, boss: Boss
) -> None:
    upwards = len(args) < 2 or args[1] != "-1"
    window = boss.window_id_map.get(target_window_id)
    if window is None:
        return

    scrolled_by_top = window.screen.scrolled_by + window.screen.lines
    scrollback = window.as_text(as_ansi=True, add_history=True, add_wrap_markers=True)
    lines = scrollback.split("\r")

    relevant_lines = (
        lines[: -scrolled_by_top - 1] if upwards else lines[-scrolled_by_top:]
    )
    lines_in_direction = reversed(relevant_lines) if upwards else relevant_lines

    for i, line in enumerate(lines_in_direction):
        if OSC8_START.search(line):
            window.screen.scroll(i + 1, upwards)
            break
```

**Comment by kovidgoyal** [comment]
Considering that the maintainer of rg has so far refused to add support
for even hyperlinks, you will have a long road ahead to get a new escape
code implemented. That said, if you do get buy in from the maintainers
of some reasonably popular grep program, I am open to collaborating to
design such an escape code.
