### ISSUE TITLE
Kitty ssh kitten `bootstrap-utils.sh` not found

### ISSUE THREAD

**Issue by Davincible** [kovidgoyal/kitty#5516]
**Describe the bug**
I've been experiencing some issues with the ssh kitten lately. I've used it fine before.

```
environment: line 101: /root/.kitty-ssh-kitten-untar-cqIqQ8yYxXbf/bootstrap-utils.sh: No such file or directory
```

I wasn't able to find any open issues about this.

**To Reproduce**
ssh with kitten into newly installed server

```
kitty 0.26.2
```

**Comment by kovidgoyal** [comment]
Doesn't reproduce for me with those steps. That error indicates
untarring is failing. Do you have tar and a POSIX compatible shell on
the server? You can try setting the interpreter to python in ssh.conf
if python is available on the server, it will give you better diagnostic
messages.

**Comment by kovidgoyal** [comment]
Like this:
kitty +kitten ssh --kitten interpreter=python servername

**Comment by Davincible** [comment]
Turns out my cloud provider doesn't install tar by default.

Perhaps showing error messages if required utils aren't installed would be good, so it's clear what the error is?

**Comment by kovidgoyal** [comment]
There are over a dozen used utilities, with fallbacks. Checking for all
of them up-front is too much work, at least for me, but patches are most
welcome.

**Comment by ta3pks** [comment]
i have the same issue how to get this fixed ?
