### ISSUE TITLE
Feature request to log terminal session output in log file

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#5519]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to log all my command line output in a log file automatically as iterm2 and SecureCRT terminal do

**Describe alternatives you've considered**
Currently I am using iterm2 and SecureCRT for logging my terminal logs when needed

Hi Team,

shall we have a feature where kitty automatically logs the terminal session at startup to analyse the network devices offline at any time?

**Comment by kovidgoyal** [comment]
Use --dump-bytes

**Comment by ciscohack** [comment]
> Use --dump-bytes

Thanks, Kovid for your prompt response as always. So please help me to implement this. is below command is correct to put in my kitty.conf file but then I have to run this in a separate window terminal. how kitty knows which tab output I am wanna save? Do we get a timestamp also for the saved log?

kitty sh -c "kitty --dump-bytes /path/to/dump/file; write"

**Comment by kovidgoyal** [comment]
You cant use it with multiple tabs. You just run

kitty --dump-bytes /path/to/log

and use that kitty instance with only one window/tab. The log will contain
all the bytes received by kitty. You can simply cat it in another
kitty instance to replay the entire session.

No, there are no timestamps.

**Comment by ciscohack** [comment]
@kovidgoyal Thanks so you mean I ran this command first "kitty --dump-bytes ~/Documents/kitty.log" then it will open another kitty window in my case on MacBook. so now I have to run all the commands on the open window to store logs.. 


" You can simply cat it in another
kitty instance to replay the entire session."

Any demo short video to see how to do that

**Comment by kovidgoyal** [comment]
cat kitty.log

**Comment by ciscohack** [comment]
Ah, I thought something else ......  anyway I tried this and a dump-byte log is not useful for me in fact not in nicely readable format due to some tmux config reasons

**Comment by MrVodinn** [comment]
Hello. 
@kovidgoyal Thank you for the great app!

I have tried to use the command "kitty --dump-bytes ~/Documents/kitty.log". but the log files contains a lot of junk simbols (cods of color and etc.) Can you please take a look and create feature with logging like /log/%H-%M%D%Y-%T.log?

Thank you.

**Comment by kovidgoyal** [comment]
SO run it through sed to remove the escape codes. Or use a pre built tool like ansifilter http://www.andre-simon.de/doku/ansifilter/en/ansifilter.php

**Comment by MrVodinn** [comment]
Thank you for advice, but usually I have a lot of logs from different machines. I mean, the logs are about 2-3 gigabytes and it would be great to have a feature that would make the task easier, and with this command it will take more time to solve.

NB: Kitty (win), Iterm2, Xshell, XMobil have this feature. 

for example:
![image](https://user-images.githubusercontent.com/6102635/203746115-42f367ab-23ab-4535-8166-dc1794b9ebd7.png)

**Comment by ciscohack** [comment]
@kovidgoyal I know you have suggested a couple of options but this seems very simple but must have a feature ask to have the session log saved in readable format automatically instead of doing lots of manual work after dumping the log. I request a review and try to add this feature to kitty
