### ISSUE TITLE
convert-reg doesn't work properly

### ISSUE THREAD

**Issue by phate89** [kovidgoyal/kitty#5520]
Hello,
 I started using kitty a year ago in portable mode and it works well.. Lately I started using winscp and I discovered that with registry mode i can use kitty instead of putty for terminal sessions straight from winscp.
The problem is converting to registry mode since I have a lot of stuff.
So I discovered "-convert-reg" command that should move everything from files and folders to registry. 
I tried and at first it seemed it worked well, I found all my sites. The problem is that when I load them there's nothing. So I looked in the registry and it seems at least all "Hostname" keys are empty so something went wrong with the import. I don't know if anything else it's missing.
Is it a known problem? There aare workarounds? I have several websites and manual would be a lot of work.
Thanks

**Comment by kovidgoyal** [comment]
https://github.com/cyd01/KiTTY/
