### ISSUE TITLE
ssh kitten: value needs to be entered twice in password prompt

### ISSUE THREAD

**Issue by antoineco** [kovidgoyal/kitty#5523]
**Describe the bug**

My employer has a central Certificate Authority that issues [short-lived SSH certificates](https://www.hashicorp.com/blog/managing-ssh-access-at-scale-with-hashicorp-vault) over SSH, via injection to the SSH agent.
Upon connecting to the SSH server responsible for delivering those short-lived certificates, the user is asked for credentials to some identity service: a password and a 2FA token.

While using the ssh kitten to access that system, the password needs to be entered **twice**, consistently. (The 2FA token needs to be entered only once.)
That is not the case while accessing the same system directly with OpenSSH.

Example session:

```console
$ kitty +kitten ssh -A ssh.example.com
Welcome to central authority

Password: admin1234
Password: admin1234    <--- second prompt
2FA Token: 012345

Success
```

**To Reproduce**

This requires setting up a similar server so I'm aware the issue might not be trivial to reproduce.

1. Connect to the server responsible for issuing SSH certificates
2. Enter the user password while prompted
3. Notice that the password is consistently prompted a second time

**Screenshots**

![Screenshot 2022-09-22 at 10 56 34](https://user-images.githubusercontent.com/3299086/191706662-eccc3076-c252-4134-b2da-7d9e9e97072f.png)

**Environment details**

```
kitty 0.26.3 created by Kovid Goyal
Darwin acotten-mbp13 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64
ProductName:    macOS ProductVersion:   12.6 BuildVersion:      21G115
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/acotten/.config/kitty/kitty.conf

Config options different from defaults:
disable_ligatures       1
font_family             Cascadia Code
font_size               15.0
initial_window_height   (32, 'cells')
initial_window_width    (140, 'cells')
remember_window_size    False
Colors:
    <omitted>

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                acotten
```

**Additional context**

**Comment by kovidgoyal** [comment]
The user is asked by what for a password? And I suggest you update kitty
your version is rather old, there have been various fixes to the ssh
kitten since 0.25.2

**Comment by antoineco** [comment]
Good point, I didn't even notice my version wasn't up-to-date because Kitty was blocked in my OS notifications settings.
I just updated to 0.26.3 like you suggested and the issue pesists.

The prompt seems to come from some server-side agent called [Okta Advanced Server Access](https://help.okta.com/asa/en-us/Content/Topics/Adv_Server_Access/docs/sftd-configure.htm) (`sftd` due to previous product name "ScaleFT"). The doc mentions that the server agent modifies `SSHDConfigFile`, so I believe there is PAM module under the hood.
Unfortunately I don't have access to the details of the server installation, but I suspect a very similar setup can be reproduced using [Teleport Server Access](https://goteleport.com/docs/server-access/introduction/) (which has a Community Edition).

In case that helps, here what I get when I `tee` the output of the command:

```
[38;2;248;248;242mhPassword: 
Password: 
2FA Token: 

A new regular SSH certificate has been added to your agent.
A new temporary key has been added to your agent.

Closing connection.
```

I see no such leading escape when I use OpenSSH directly:

```
Password: 
2FA Token: 

A new regular SSH certificate has been added to your agent.
A new temporary key has been added to your agent.

Closing connection.
```

**Comment by kovidgoyal** [comment]
The escape code is setting colors, and that is probably happening because
the ssh kitten forwards the COLORTERM env var, which regular ssh does
not. I am guessing that is breaking this utility, which is really a bug
in the utility. You can try running it after manually unsetting
COLORTERM to check.

**Comment by antoineco** [comment]
That is not it unfortunately. Same output with `COLORTERM` unset:

```console
$ cat -v /tmp/ssh_output_kitty
^[[?s^[[?19997hPassword: ^M
Password: ^M
2FA Token: ^M
^M
A new regular SSH certificate has been added to your agent.^M
A new temporary key has been added to your agent.^M
^M
Closing connection.^M
^M
^[[?r%
```

**Comment by kovidgoyal** [comment]
Unsetting COLORTERM before sshing is not going to work, as the kitten
will always set it. You need to unset it on the remote side before
invoking whatever the binary that is prompting you for the password is,
or you can override it via the env directive in ssh.conf see the docs of
the ssh kitten.

**Comment by antoineco** [comment]
I tried the second method, using `ssh.conf`, without success:

**Syntax 1, remove var**

```console
$ cat ~/.config/kitty/ssh.conf
hostname ssh.example.com
env COLORTERM
```

> Specifying only the name (e.g. `env VAR`) will remove the variable from the remote shell environment.
> -- https://sw.kovidgoyal.net/kitty/kittens/ssh/

```console
$ kitty +kitten ssh -A ssh.example.com | tee /tmp/ssh_output_kitty
```

(same output)

**Syntax 2, empty var**

```console
$ cat ~/.config/kitty/ssh.conf
hostname ssh.example.com
env COLORTERM=
```

```console
$ kitty +kitten ssh -A ssh.example.com | tee /tmp/ssh_output_kitty
```

(same output)

**Comment by kovidgoyal** [comment]
Then I am out of ideas, without access to this program/PAM
module/whatever, it's impossible to say what is tripping it up.

**Comment by kovidgoyal** [comment]
There is no way for anyone to find that out, since there is no way to
know what whatever that tool is, is doing. If you can provide access to
its source code, I will be happy to investigate.

**Comment by antoineco** [comment]
Actually, it's most likely the kitten itself that is sending the escape sequence, and that sequence seems to get swallowed by the first prompt.

I retried both commands (kitten / openssh) with `-vvv`, and I see the escape _before_ a connection is even established:

```diff
--- /usr/bin/ssh
+++ kitty +kitten ssh

1c1
< OpenSSH_8.6p1, LibreSSL 3.3.6^M
---
> ^[[?s^[[?19997hOpenSSH_8.6p1, LibreSSL 3.3.6^M
10a11,12
> debug1: auto-mux: Trying existing master^M
> debug1: Control socket "/tmp/kssh-rdir-501/kssh-67192-26223ddf520a86aa0622886de3619e9237df0f3b" does not exist^M
122c124
< Logging in as "user", session ID: 1000001
---
> Logging in as "user", session ID: 1000002
< debug2: fd 7 setting O_NONBLOCK^M
< debug3: fd 8 is O_NONBLOCK^M
< debug1: channel 0: new [client-session]^M
< debug3: ssh_session2_open: channel_new: 0^M
< debug2: channel 0: send open^M
< debug3: send packet: type 90^M
---
> debug1: setting up multiplex master socket^M
> debug3: muxserver_listen: temporary control path /tmp/kssh-rdir-501/kssh-67192-26223ddf520a86aa0622886de3619e9237df0f3b.TgMbP8MPZAbIDl4B^M
> debug2: fd 6 setting O_NONBLOCK^M
> debug3: fd 6 is O_NONBLOCK^M
> debug3: fd 6 is O_NONBLOCK^M
> debug1: channel 0: new [/tmp/kssh-rdir-501/kssh-67192-26223ddf520a86aa0622886de3619e9237df0f3b]^M
> debug3: muxserver_listen: mux listener channel 0 fd 6^M
> debug2: fd 5 setting TCP_NODELAY^M
> debug3: set_sock_tos: set socket 5 IP_TOS 0x20^M
> debug1: control_persist_detach: backgrounding master process^M
> debug2: control_persist_detach: background process is 68839^M
> debug2: fd 6 setting O_NONBLOCK^M
> debug1: forking to background^M
139c148,173
< debug1: pledge: filesystem full^M
---
> debug1: pledge: id^M
[...]
```

**Comment by kovidgoyal** [comment]
That's not the color escape sequence, that's part of the kittens
implementation. The kitten absolutely does not change colors.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/ssh/#how-it-works

**Comment by antoineco** [comment]
That's the escape sequence I've been observing all along. The first one I posted was incorrectly rendered by `bat` (which colored my output). Sorry if that was misleading in my original post.

Are you suggesting the escape has nothing to do with the broken prompt?

**Comment by kovidgoyal** [comment]
Yes, it doesn't. It's a escape sent to kitty to turn on a mode (signal
on interrupt keypress), it has no bearing on future programs executed by ssh.

**Comment by kovidgoyal** [comment]
Oh and if you set askpass to ssh the kitten wont transmit data till after the connection is established. Though I doubt it will make a difference.

kitty +kitten ssh --kitten askpass=ssh whatever

**Comment by antoineco** [comment]
That one works 🎉

**Comment by kovidgoyal** [comment]
Nothing is. When you use kitty's builtin askpass, SSH is supposed to
delegate asking for the password to that askpass program. Whatever weirdness the
system you are using is doing, is causing ssh to not use kitty's askpass
and instead try to read from the terminal. The ssh kitten assumes
nothing will read from the terminal expect itself and the script it runs
on the remote host, since your system is breaking that assumption, it is
breaking. The kitten uses that assumption as a performance optimization,
starting to send data over the tty without wiating for a roundtrip from
the remote side.

When you set askpass to ssh, then the kitten knows that ssh
might read from the terminal so it does not write to it until the remote
script is run, which indicates that ssh is done using the terminal. I
have no idea how the system you are using is supposed to work and I lack
the time to investigate it, but I am guessing it is somehow breaking the
use of

SSH_ASKPASS_REQUIRE=force

which is how invoking programs are supposed to tell SSH to delegate its
askpass to the program set in the SSH_ASKPASS env var.

**Comment by antoineco** [comment]
Alright, appreciate the clarifications!
