### ISSUE TITLE
Keeping aspect ratio of background image

### ISSUE THREAD

**Issue by LinUwUxCat** [kovidgoyal/kitty#5525]
**Is your feature request related to a problem? Please describe.**
Currently, background images have 4 layouts : tiled, mirror-tiled, scaled and clamped. However, i did not find an option that would allow me to have the image resized while keeping its aspect ratio, as the image stretches when the kitty window isn't in the image's aspect ratio.

**Describe the solution you'd like**
obviously kitty cannot create a new part of the image by itself, so it would be good if it could fill the parts that are not covered by the image by a color set by the user.

**Describe alternatives you've considered**
The color could also be filled by the color at the edge of the image, but i'm not sure about this one.

**Additional context**
See examples : 
Normal kitty window with normal aspect ratio
![image](https://user-images.githubusercontent.com/46047705/191957455-5eb03bae-5b93-47df-b57b-df792f817410.png)
Stretched kitty window, current behavior:
![image](https://user-images.githubusercontent.com/46047705/191957521-8ee2d6c5-35f7-4ebf-9eed-eadfe9a08af9.png)
What i would like to happen when stretching : 
![image](https://user-images.githubusercontent.com/46047705/191957964-5e368d65-f0ff-4c7d-ae88-950490813397.png)

**Comment by kovidgoyal** [comment]
Use clamped and set the background color to whatever color you want via
background

**Comment by LinUwUxCat** [comment]
The issue with that is it doesn't scale the image if it is bigger...
![image](https://user-images.githubusercontent.com/46047705/191958753-27267019-2bd4-4250-8973-ed0dbbccc780.png)

**Comment by kovidgoyal** [comment]
As far as I recall OpenGL has no texturing primitive that both clamps and
scales. So use an image that is larger than the resolution of your
largest monitor.

**Comment by kovidgoyal** [comment]
The scaling was highdpi specific, it should be fixed by https://github.com/kovidgoyal/kitty/commit/4d80427908b3d54ed6f48a57a250f404b1951984
Now clamped should render the image in the upper left corner of the window, at natural size

**Comment by mathiaslovnes** [comment]
@kovidgoyal I have the same issue as the creator of this issue - I set background_image_layout to clamped and it still zooms in... what can I do? The image is the same res as my monitor

**Comment by kovidgoyal** [comment]
Does not reproduce for me with

```
kitty -o background_image=kitty.png -o background_image_layout=clamped
```

**Comment by mathiaslovnes** [comment]
This:
<img width="756" height="68" alt="Image" src="https://github.com/user-attachments/assets/4a3cfa3c-3859-42a8-91ba-f775763f703f" />

Produces:

<img width="1723" height="1140" alt="Image" src="https://github.com/user-attachments/assets/56152bae-803e-4b4d-b3dc-682dcd104b8c" />

Original pic:

<img width="1750" height="1143" alt="Image" src="https://github.com/user-attachments/assets/fb96d860-a0ca-4182-a351-3cce4ec74c22" />

**Comment by kovidgoyal** [comment]
Start by updating kitty. And if you still have an issue, open a bug report with all the requested data in the issue template and a way to reproduce your issue.

**Comment by mathiaslovnes** [comment]
if anyone else encounters the same issue:
setting 
"background_image_layout cscaled"
fixed it for me
