### ISSUE TITLE
Kitty can't transfer to other apps.

### ISSUE THREAD

**Issue by ttw1018** [kovidgoyal/kitty#5533]
When i type `open .` or something in macos, It should transfer to finder or other targeted apps, but it still focus on kitty.
How can i  config kitty to realize it or just because kitty doesn't support that.

**Comment by kovidgoyal** [comment]
kitty has no control on what application the OS decides to focus. And a
t least on my macbook running open . in kitty moves the focus to finder
as expected.

**Comment by ttw1018** [comment]
The reason for that problem thanks to I opened the secure keyboard entry.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/48583236/192131331-23d3e60a-0488-4c66-8c58-20c65d3ee3b1.png">

**Comment by kovidgoyal** [comment]
yes, that's how secure keyboard entry works, it prevents other applications from stealing keyboard focus.
