### ISSUE TITLE
Errors with bash and shell integration

### ISSUE THREAD

**Issue by lcheylus** [kovidgoyal/kitty#5534]
**Bug description**

On my Debian testing/amd64 desktop, I have kitty-0.26.3 (built from sources) and bash shell. Shell integration for kitty is enabled via manual integration in my `.bashrc` file.

When I opened a new Kitty terminal, I have the error : 

`bash: DEBUG warning: command_builtin: running execute_command for 'base64'`

I have also an error with bash completion for Kitty : 

```
kitty <TAB>
bash: DEBUG warning: command_builtin: running execute_command for 'kitty'
```

**Reproduction**
1. Kitty v0.26.3 built from sources on Debian testing/amd64
```
$ kitty -v
kitty 0.26.3 created by Kovid Goyal
```
2. Latest Bash version for Debian/testing : 
```
$ bash --version
GNU bash, version 5.2.0(1)-rc2 (x86_64-pc-linux-gnu)
```
3. Manual integration for shell with Kitty in `.bashrc` according to documentation
```
# Shell integration with Kitty
if test -n "$KITTY_INSTALLATION_DIR"; then
    export KITTY_SHELL_INTEGRATION="enabled"
    source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"
fi
```

`KITTY_INSTALLATION_DIR=/usr/lib/kitty`

4. Errors when I tried to open a new Kitty terminal or to use shell completion for `kitty` command.
5. If I disabled shell integration for Kitty in my `.bashrc` file, no error.

**Comment by kovidgoyal** [comment]
If you want to use manual integration dont forget to set
shell_integration no-rc in kitty.conf or you will be running double
integration. There is no reason to use manual integration these days in
any case.

**Comment by lcheylus** [comment]
I have the same errors with : 

- `shell_integration no-rc` in `kitty.conf` and manual integration in my `.bashrc` file
- `shell_integration enabled` in `kitty.conf` and no manual integration

**Comment by kovidgoyal** [comment]
Your bash is built with DEBUG enabled. use a proper bash built without DEBUG and you will be fine.
