### ISSUE TITLE
Maximize only one window keybinding.

### ISSUE THREAD

**Issue by iulian-birlica** [kovidgoyal/kitty#5539]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to maximize a single window, and then set it back to its original size.

**Describe the solution you'd like**
I would like a keybinding that would do this.

**Describe alternatives you've considered**
Most other advanced terminal emulators have this functionality, as well as window managers, even though I know kitty is not a window manager.

**Additional context**
I searched everywhere through issues, `kitty.conf` and the larger web. I could find nothing about such a feature, so I am sorry if it already exists. There is some confusion with the maximization of the larger, OS, window.

**Comment by page-down** [comment]
Looks like all you need is to switch the layout to `stack`.

https://sw.kovidgoyal.net/kitty/conf/#layout-management
https://sw.kovidgoyal.net/kitty/actions/#action-toggle_layout
