### ISSUE TITLE
XKB redirect actions are not correctly handled

### ISSUE THREAD

**Issue by benoit-pierre** [kovidgoyal/kitty#554]
For example the following mapping (which simulate a `Shift+Insert`) is not correctly handled:
```
 key <AB09> { [ NoSymbol, NoSymbol, NoSymbol, NoSymbol ], actions = [ NoAction(), NoAction(), Redirect(key= <INS>, mods=Shift, clearmods=Mod5) ] };
```
Similarly, my numlock-like layer does not work (see full keymap is [here](https://github.com/benoit-pierre/config-x11/blob/master/xkb/symbols/bpierre)).

Possibly related libxkbcommon issue:  https://github.com/xkbcommon/libxkbcommon/issues/18

For now, I've monkeypatched my copy of kitty like this:
```diff
diff --git a/glfw/x11_window.c b/glfw/x11_window.c
index 63ad189..83105d3 100644
--- a/glfw/x11_window.c
+++ b/glfw/x11_window.c
@@ -1242,7 +1242,22 @@ static void processEvent(XEvent *event)
     {
         case KeyPress:
         {
+            XkbStateRec state_rec;
+
+            XkbGetState(_glfw.x11.display, XkbUseCoreKbd, &state_rec);
+
+            glfw_xkb_update_modifiers(
+                        &_glfw.x11.xkb,
+                        event->xkey.state, 0, 0,
+                        state_rec.base_group, state_rec.latched_group, state_rec.locked_group);
+
             glfw_xkb_handle_key_event(window, &_glfw.x11.xkb, event->xkey.keycode, GLFW_PRESS);
+
+            glfw_xkb_update_modifiers(
+                        &_glfw.x11.xkb,
+                        state_rec.base_mods, state_rec.latched_mods, state_rec.locked_mods,
+                        state_rec.base_group, state_rec.latched_group, state_rec.locked_group);
+
             return;
         }
 
```

**Comment by kovidgoyal** [comment]
Not sure what I can do about this. Fundamentally, unless libxkb adds support for Redirect, kitty cannot support it, as using various hacks to try to support it will break something else/be fragile.

Note that instead of monkey patching, you can use the send_text directive in kitty.conf to generate arbitrary bytes on arbitrary keypresses. Of course, thi will only work if the original key event is actually reaching kitty (which means it is a key that GLFW knows about).

**Comment by benoit-pierre** [comment]
I looked at mapping the combo to `paste_from_selection/paste_from_clipboard` in `kitty.conf` but GLFW does not seem to know about the `ISO_Level3_Shift` modifier either...

**Comment by kovidgoyal** [comment]
If you search for compose in the closed kitty tickets there are some posts with people using the neo keyboard that uses a level 5 modifier (IIRC) and they were able to get it to work with kitty (at least after the changes I made to use libxkb).
