### ISSUE TITLE
colors are broken with current debian

### ISSUE THREAD

**Issue by montanero** [kovidgoyal/kitty#5540]
**Describe the bug**
After upgrading my debian system (including kitty) to current versions, colors in kitty are broken.
I'm using debian sid,  kitty version 0.25.2.

Colors are not displayed correctly, especially I cannot see any red or green. See example in attached screen shot.

**To Reproduce**
remove kitty.conf to avoid configuration effects
start kitty
printf '\x1b]11;#800000\x1b\\', see strange greenish color instead of expected red
kitty +kitten themes, see broken color schemes

**Screenshots**
![image](https://user-images.githubusercontent.com/1765011/192574601-21946f69-4c7a-4cfa-8f30-4321481d7a22.png)

![image](https://user-images.githubusercontent.com/1765011/192565759-a1494f0e-4166-4faf-bd83-ce1f121fe32f.png)
**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux debian 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64
Debian GNU/Linux bookworm/sid debian /dev/tty

Running under: X11
Frozen: True
Paths:
  kitty: /home/bergler/.local/kitty.app/bin/kitty
  base dir: /home/bergler/.local/kitty.app/lib/kitty
  extensions dir: /home/bergler/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0

Important environment variables seen by the kitty process:
	PATH                                /home/bergler/.local/kitty.app/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                bergler
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SESSION_DESKTOP                 lightdm-xsession
	XDG_GREETER_DATA_DIR                /var/lib/lightdm/data/bergler
	XDG_VTNR                            7
	XDG_DATA_DIRS                       /usr/share/gnome:/usr/local/share/:/usr/share/
	XDG_CURRENT_DESKTOP                 X-Cinnamon

```

**Additional context**
kitty --config NONE shows the same problem.
Also tested with kitty 0.26.3, same problem

**Comment by kovidgoyal** [comment]
I'm afraid I don't have the time/interest to debug distro kitty packages.
Use the official kitty binaries and you should be fine. I fnot let me
know.

**Comment by page-down** [comment]
> Use the official kitty binaries ...

I see `Frozen: True ` and `~/.local/kitty.app/bin` in the debug info.

@montanero
You can try to install the dependencies and compile kitty from source.
https://sw.kovidgoyal.net/kitty/build/

**Comment by kovidgoyal** [comment]
0.25.2 is very old for a binary. In that case update to 0.26.3

**Comment by montanero** [comment]
problem remains with  0.26.3 from kitty download page

**Comment by kovidgoyal** [comment]
Then this will likely be a GPU driver issue. Run the following

```
LIBGL_ALWAYS_SOFTWARE=true GALLIUM_DRIVER=llvmpipe kitty --hold --config NONE kitty +runpy 'print("\x1b[41mXXXX")'
```

what color is the background of XXXX

**Comment by montanero** [comment]
Background is red
![image](https://user-images.githubusercontent.com/1765011/192976646-eec46753-b60e-49f4-bd9b-dc75aaeb45d6.png)

**Comment by kovidgoyal** [comment]
Then its working as expected. You likely have something in your shell rc
files that is redefinig colors.
