### ISSUE TITLE
Many diacritics do not show/aren't anchored properly on MacOS

### ISSUE THREAD

**Issue by crthpl** [kovidgoyal/kitty#5541]
**Describe the bug**
Diacritics on characters that ascend and/or descend do not show.

**To Reproduce**
Print characters with diacritics (I am using FiraCode).

**Screenshots**
HTML with fallback font disabled (boxes are diacritics that are unsupported by FiraCode): ![firacode_diacritics_html](https://user-images.githubusercontent.com/56052645/192608905-a8aa123f-e4be-4bb9-9346-955e57c0fe6d.png)

Kitty with fallback font disabled:
<img width="564" alt="Screen Shot 2022-09-27 at 11 32 48" src="https://user-images.githubusercontent.com/56052645/192609425-c8324e74-135a-4948-a2e1-976aa28cff1a.png">
<img width="565" alt="Screen Shot 2022-09-27 at 11 33 24" src="https://user-images.githubusercontent.com/56052645/192609423-2f8e4d22-685a-4e05-8f62-43c6bce107c9.png">
<img width="566" alt="Screen Shot 2022-09-27 at 11 33 38" src="https://user-images.githubusercontent.com/56052645/192609421-dcea9b18-2f87-4b73-a252-052867e2d692.png">
<img width="567" alt="Screen Shot 2022-09-27 at 11 33 46" src="https://user-images.githubusercontent.com/56052645/192609411-dae80f9c-965f-4b8f-a5a7-7b546b10612a.png">

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Darwin crthpls-MacBook-Pro-3.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.6.4 BuildVersion:	20G417
Frozen: True
Paths:
  kitty: /Users/username/Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Users/username/Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/username/Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/fish
Loaded config files:
  /Users/username/.config/kitty/kitty.conf

Config options different from defaults:
bold_font        Fira Code Bold
bold_italic_font Fira Code Retina
editor           nvim
font_family      Fira Code Regular
font_size        15.0
italic_font      Fira Code Light
mouse_hide_wait  3.0
symbol_map:
	U+0041 - U+007a → Fira Code Regular
	U+0300 - U+0370 → Fira Code Regular # This is to disable falling back to Menlo, which doesn't solve the problem, though U+33f, U+361 and some others change to menlo and work-ish
Added shortcuts:
	cmd+f5 →  load_config_file
	cmd+f6 →  debug_config
Changed shortcuts:
	cmd+enter →  launch --cwd=current
	kitty_mod+enter →  launch --cwd=current
	kitty_mod+t →  new_tab_with_cwd
Colors:
	background       #2e3440   
	color0           #3b4252   
	color1           #bf616a   
	color10          #a3be8c   
	color11          #ebcb8b   
	color12          #81a1c1   
	color13          #b48ead   
	color14          #8fbcbb   
	color15          #eceff4   
	color2           #a3be8c   
	color3           #ebcb8b   
	color4           #81a1c1   
	color5           #b48ead   
	color6           #88c0d0   
	color7           #e5e9f0   
	color8           #4c566a   
	color9           #bf616a   
	cursor           #81a1c1   
	foreground       #d8dee9   

Important environment variables seen by the kitty process:
	PATH                                /Users/username/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /usr/local/bin/fish
	DISPLAY                             /private/tmp/com.apple.launchd.zRTaMDtIZX/org.xquartz:0
	USER                                username
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I dont feel like reading through those lists. Can you post two or three characters that dont work for you? And is this specific to Fira code?

**Comment by crthpl** [comment]
HTML uses all diacritics that Fira code provides, and places them correctly above the letters.
kitty places diacritics on many letters, but for taller letters such as `b`, `d` and `f` they are simply deleted. Fira code has all upper case letters the same height, yet diacritics are only placed on upper case characters whose corresponding lower case character do place diacritics (such as `Aa`, `Ee` and `Ww`). Some diacritics are only placed on very few letters, such as U+030A COMBINING RING ABOVE, which is only placed above `auAU`: `åůÅŮ`, while some diacritics are placed on half the alphabet.

Also, on Linux, all diacritics are placed, but for some the letter itself is moved down to make space for the diacritic, for others the diacritic is place on top of the letter, and for some the diacritic is correctly moved down onto a lower character.

Characters that are used in writing systems are much more likely to work, though I am using this for IPA, where there are much more combinations.

Using Menlo on MacOS improves things a bit, but far from completely. On Linux, using Menlo looks the same as it does in chrome (everything works).

**Comment by page-down** [comment]
@kovidgoyal
I am not familiar with diacritical marks, but have some questions about fallback fonts.

Note the following `e`.
```shell
printf "a\u0300e\u030d\n"
```

Linux:

```log
kitty --config=NONE --debug-font-fallback
Preloaded font faces:
[271...] normal face: /usr/share/fonts/truetype/hack/Hack-Regular.ttf:0
[271...] bold face: /usr/share/fonts/truetype/hack/Hack-Bold.ttf:0
[271...] italic face: /usr/share/fonts/truetype/hack/Hack-Italic.ttf:0
[271...] bi face: /usr/share/fonts/truetype/hack/Hack-BoldItalic.ttf:0
U+65 U+30d Face(family=Hack, style=Bold, ps_name=Hack-Bold, path=/usr/share/fonts/truetype/hack/Hack-Bold.ttf, index=0, is_scalable=True, has_color=False, ascender=1901, descender=-483, height=2384, underline_position=-265, underline_thickness=90, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

The diacritical mark `\u030d` shows normal. However, the `e` becomes bold at this point. See the last line of the log above.
Does it mean that Hack(Regular) does not support the diacritical mark?
Is it possible to keep the style instead of using bold? (just show `e` without diacritical mark)

macOS:
If the default `Menlo` font is used, then `\u030d` will not be displayed, which I believe is a font issue.
```shell
kitty --config=NONE
#  default: Menlo
```

However, if I use a font that supports that diacritical mark, such as `Iosevka`, then it will display normally and `e` will not become bold.
```shell
kitty --config=NONE -o 'font_family Iosevka Term' --debug-font-fallback 
```

So, how to point these to another font using `symbol_map`? (instead of defaulting back to the broken `Menlo`).
Linux: Suppose the Hack(Regular) font does not support this diacritical mark, can it fall back to another font of the same style, instead of falling back to bold?

**Comment by crthpl** [comment]
@page-down this is another issue I noticed: When checking to use a fallback font, it looks at the entire thing, including diacritics and finds a font that supports it (sometimes unsuccesfully). However, when using `symbol_map`, it looks only at the first character to check if it uses the mapped font, so it is impossible to redirect chararcters with diacritics to another font.

**Comment by crthpl** [comment]
Also to note: multiple diacritics support is nearly non-existent.

**Comment by kovidgoyal** [comment]
You need to use a combination of fonts whose metrics are compatible. Or
use adjust_font to increase the line height and you will be fine.

**Comment by kovidgoyal** [comment]
@page-down What font is chosen as fallback comes from coretext on macOS kitty doesn't have much control over the process. symbol_map only works with single code points, so you cant really use it to force a font. Generally speaking on macOS things are much more dependent on coretext. On linux kitty has more control, since fontconfig/freetype are more flexible.

**Comment by crthpl** [comment]
@kovidgoyal How would i use a combination of fonts and what do you mean by compatible metrics? Also, `modify_font cell_height 200%` doesn't fix the diacritics, though adds lots of space.

How come iTerm2 and Terminal.app do this fine? What API do they use?

As for symbol_maps only working with single code points, could you change `in_symbol_maps` to accept `cpu_cell` instead of just `ch` (the base character) https://github.com/kovidgoyal/kitty/blob/cd8f2e5cc6efbfb1bc7e18300956a7e2bb02a1dd/kitty/fonts.c#L548 so that you could do something like `symbol_map U+41-U+7A & U+300-U+370 SuperDiacriticFont` to configure diacritics.

Why are only 3 combiners allowed? https://github.com/kovidgoyal/kitty/commit/2b3be147e6ecd08286cb0630b7af4f767a031b16

Also for me only one diacritic works:
Kitty:
<img width="249" alt="Screen Shot 2022-09-28 at 13 43 54" src="https://user-images.githubusercontent.com/56052645/192902447-2cca51f8-3c01-4350-ae8a-7601e3cc69c8.png">
(Only shows first diacritic)

iTerm2:
<img width="274" alt="Screen Shot 2022-09-28 at 13 43 30" src="https://user-images.githubusercontent.com/56052645/192902486-1a2a0aee-001e-415c-984c-b469511b4707.png">

Terminal.app
<img width="226" alt="Screen Shot 2022-09-28 at 13 43 45" src="https://user-images.githubusercontent.com/56052645/192902537-1c1df6bf-a3d1-4121-8a74-b2fffc57a5bb.png">

Both just stack diacritics on top of each other.

**Comment by kovidgoyal** [comment]
On Wed, Sep 28, 2022 at 03:55:45PM -0700, crthpl wrote:
> @kovidgoyal How would i use a combination of fonts and what do you mean by compatible metrics? Also, `modify_font cell_height 200%` doesn't fix the diacritics, though adds lots of space.

They all need to fit in the cell width/height selected by the primary
font. I find it highly unlikely it wont work with adjust_font, I am
travelling at the moment so dont have access to a macbook, but I will
check that when I return.

> 
> How come iTerm2 and Terminal.app do this fine? What API do they use?

They dont render in fixed size cells.

> 
> As for symbol_maps only working with single code points, could you change `in_symbol_maps` to accept `cpu_cell` instead of just `ch` (the base character) https://github.com/kovidgoyal/kitty/blob/cd8f2e5cc6efbfb1bc7e18300956a7e2bb02a1dd/kitty/fonts.c#L548 so that you could do something like `symbol_map U+41-U+7A & U+300-U+370 SuperDiacriticFont` to configure diacritics.

I could, but its a lot of work for not much gain.

> 
> Why are only 3 combiners allowed? https://github.com/kovidgoyal/kitty/commit/2b3be147e6ecd08286cb0630b7af4f767a031b16

Performance.

> 
> Also for me only one diacritic works:

In that case it will be something CoreText specific.

> Kitty:
> <img width="249" alt="Screen Shot 2022-09-28 at 13 43 54" src="https://user-images.githubusercontent.com/56052645/192902447-2cca51f8-3c01-4350-ae8a-7601e3cc69c8.png">
> (Only shows first diacritic)
> 
> iTerm2:
> <img width="274" alt="Screen Shot 2022-09-28 at 13 43 30" src="https://user-images.githubusercontent.com/56052645/192902486-1a2a0aee-001e-415c-984c-b469511b4707.png">
> 
> Terminal.app
> <img width="226" alt="Screen Shot 2022-09-28 at 13 43 45" src="https://user-images.githubusercontent.com/56052645/192902537-1c1df6bf-a3d1-4121-8a74-b2fffc57a5bb.png">
> 
> Both just stack diacritics on top of each other.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/5541#issuecomment-1261545908
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by crthpl** [comment]
I've found the issue: setting both cell_height *and* cell_width to 200% causes this
<img width="944" alt="Screen Shot 2022-09-28 at 20 56 57" src="https://user-images.githubusercontent.com/56052645/192935545-2df55880-3f0d-4b09-b362-5c7e9a4b88ac.png">
The reason the diacritics weren't rendering was because the diacritics were placed next to the character (hidden outside the 100%x100% cells), instead of being correctly anchored on top.

This also shows that all diacritics after the first one are also placed next to the character, were they are stacked on each other (and as expected only up to three diacritics).

I think if the diacritics are correctly rendered on top, they would still fit within the default cell size. The reason I am using multiple diacritics is for things like h̪͆ (which is unfortunately unsupported by both Menlo and Fira Code).

**Comment by kovidgoyal** [comment]
Definitely a CoreText specific issue in that case. Will look into it
when I next have access to a mac.
