### ISSUE TITLE
Render Issue on macOS

### ISSUE THREAD

**Issue by taozhang-tt** [kovidgoyal/kitty#5543]
I use ssh to telnet to my MacBook Pro(10.15.7), i found some render problem.

when i tap "ls", it render "lss"
i tap "cd", it render "cdd"

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/37895749/193016901-4a33bf31-3b97-4003-9762-f69bf7f1d4f5.png">

macOS(10.15.7)
kitty(0.23.0)

**Comment by taozhang-tt** [comment]
BTW, I try to use iterm2 just now, everything is ok.

**Comment by kovidgoyal** [comment]
You need the correct terminfo on your server. https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by taozhang-tt** [comment]
Thanks a lot
