### ISSUE TITLE
Error launching new remote window with --cwd=current if remote home directory is different

### ISSUE THREAD

**Issue by fossrob** [kovidgoyal/kitty#5547]
**Describe the bug**
I am using `kitty +kitten ssh` and `launch --cwd=current` to allow new windows to be opened already ssh'd into the remote system. The system has a different path to home directories and the username is different.

In my case on my local system the home directory is `/home/robin` but on the remote it is `/net/homes/redser`.

When opening a new window everything appears to work except I get an error and the CWD isn't maintained:

```
/net/homes/redser/.kitty-ssh-kitten-untar-Px23lNtGp7XW/bootstrap-utils.sh: line 217: cd: /home/robin: No such file or directory
```

**To Reproduce**
1. Use ssh kitten to connect to remote `kitty +kitten ssh remote`
2. Use keyboard shortcut to `launch --location=vsplit --cwd=current`
3. See error

**Environment details**
```
kitty 0.26.2 created by Kovid Goyal
Linux xps 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Fri Sep 2 16:07:40 EDT 2022 x86_64
S
Kernel 5.14.0-70.26.1.el9_0.x86_64 on an x86_64

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/robin/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.9
dynamic_background_opacity True
enabled_layouts            ['splits']
font_family                DroidSansMono Nerd Font
hide_window_decorations    1
strip_trailing_spaces      smart
window_border_width        (1.0, 'px')
window_padding_width       FloatEdges(left=2.0, top=1.0, right=2.0, bottom=1.0)
Added shortcuts:
	alt+down →  neighboring_window down
	alt+left →  neighboring_window left
	alt+right →  neighboring_window right
	alt+up →  neighboring_window up
	ctrl+down →  resize_window shorter
	ctrl+home →  resize_window reset
	ctrl+left →  resize_window narrower
	ctrl+page_down →  next_tab
	ctrl+page_up →  previous_tab
	ctrl+right →  resize_window wider
	ctrl+up →  resize_window taller
	shift+down →  move_window down
	shift+left →  move_window left
	shift+right →  move_window right
	shift+up →  move_window up
Changed shortcuts:
	kitty_mod+e →  launch --location=vsplit --cwd=current
	kitty_mod+o →  launch --location=hsplit --cwd=current
Colors:
	active_border_color        #14b814   
	background                 #1e1e1e   
	inactive_border_color      #2f2f2f   

Important environment variables seen by the kitty process:
	PATH                                /home/robin/.local/bin:/home/robin/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_GB.UTF-8
	EDITOR                              vim
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                robin
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome-xorg
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/robin/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/

```

**Additional context**

The issue is reproducible with a minimal config consisting only of the keyboard shortcuts used:

```
map ctrl+shift+e launch --location=vsplit --cwd=current
map ctrl+shift+o launch --location=hsplit --cwd=current

```

**Comment by kovidgoyal** [comment]
Doesn't reproduce for me with those steps. The only way I know of for
what you are describing to happen is if shell integration is not working
on the remote machine, so kitty does not know what directory is current
on the remote side.

What shell is on the remote machine? Is shell integration working? Does
pressing ctrl+shift+g show the output fo the last command?

**Comment by fossrob** [comment]
I'll try poke around in the shell integration to see if I can figure it out thank you.

> What shell is on the remote machine?
```
bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```
> Is shell integration working? Does pressing ctrl+shift+g show the output fo the last command?
`ctrl+shift+g` does indeed work 🤔

**Comment by fossrob** [comment]
However `ctrl+shift+z` / `ctrl+shift+x` do not work. This could be because `HISTCONTROL='ignoreboth'` is set 🤔

**Comment by fossrob** [comment]
Thanks so much for the responses. I seem to have resolved it by explicitly enabling `shell_integration` 🤔 

I had assumed it was enabled by default because `ctrl+shift+g` was working, and because the default (although commented out) was enabled?

```
# shell_integration enabled

shell_integration enabled
```
That seems to be all it need 🤔 

Sorry for the trouble! Thank you for this terminal though I'm really enjoying using it!

**Comment by kovidgoyal** [comment]
yes, shell_integration enabled is the default, so adding it should have
no effect unless it was being turned off elsewhere in the config
