### ISSUE TITLE
kitty cannot use fcitx5 to input chinaese or japan languages

### ISSUE THREAD

**Issue by newyorkthink** [kovidgoyal/kitty#5549]
the kitty cannot other languages,
I use fcitx5 ,

i test hyper terminal is working 
![image](https://user-images.githubusercontent.com/87791643/193493473-d0818aa1-f114-4c97-be28-8fc7d4160fa3.png)

kitty is not working:
![image](https://user-images.githubusercontent.com/87791643/193493533-0f467107-4577-4bcd-bfc3-c519f71ae9b9.png)

every tutorial is tell us add the following:
export XIM="fcitx"
export XIM_PROGRAM="fcitx"
export GTK_IM_MODULE="fcitx"
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE="fcitx"

but it dont woring to kitty.

i other browser file manager is work use fcitx

**Comment by kovidgoyal** [comment]
kitty supports ibus not fcitx. IIRC fcitx has an IBUS compatibility
mode, use it, and set GLFW_IM_MODULE=ibus

**Comment by cloorc** [comment]
For anyone may need:

```bash
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus
export XMODIFIER=@im=fcitx5
```

In Wayland/XWayland on KDE, former environments will tell kitty to use IBus frontend from Fcitx5. It's working on my Ubuntu 25.10 with KDE desktop.
