### ISSUE TITLE
Keyboard select (once again)

### ISSUE THREAD

**Issue by omgold** [kovidgoyal/kitty#5550]
Sorry for bringing this up again, but what I badly miss is the ability to select text on the screen with the keyboard.

I'm well aware that it has been discussed several times already (#719, #1698, #5049) with the advice to use the scrollback buffer and an external editor, but (despite no lack of trying hard), I could not find a way for this to actually replace a builtin selection mode - in a way working accurately and smoothly enough to not be a source of annoyance.

To elaborate, it seems no available editor is able to handle the decorative terminal escape codes accurately enough to not produce a result different from kitty itself. (I don't want to start on kitty extensions like showing images, as I could survive with issues when using these) Having kitty pass the scrollback buffer split as screen lines allows at least to editor to know how kitty split the text lines, but then multi-line selection is broken. Passing the scrollback buffer as text lines make it hopeless for the editor to figure that out, resulting in offsets of the scrollback position and cursor location (its in particular bad when the screen has not been filled, yet).

Depending on the editor and size of the scrollback, the noticeable delay and flicker during startup of the editor is unpleasant for me, too. Emacs (which I like) is especially bad there.
 
I tried crazy things like fixing kitty_grab to allow multiline-select (along the lines discussed here https://github.com/yurikhan/kitty_grab/issues/19), but there are still things which confuse kitty_grab like wide characters.

To only thing I could imaging to work is to re-use the terminal emulator part of kitty in a new select-mode kitten, but it seems the API isn't easily accessible (like having a separate libkitty with an interface for that), so I gave up on that.

So I would ask whether it really were that troublesome to provide a way to control the selection with the keyboard. Maybe an API to move the cursor and change the selection range (accessible to kittens) would suffice, also.

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in doing so. I will say it is on my TODO
list to write a pager for kitty which will solve your accuracy and
flicker problems.

**Comment by omgold** [comment]
> it is on my TODO list to write a pager for kitty which will solve your accuracy and flicker problems.

I'm not sure I understand. Maybe you could you elaborate what you mean by pager? I would be curious whether it could be used to implement accurately-rendered keyboard select as a kitten.

**Comment by kovidgoyal** [comment]
On Mon, Oct 03, 2022 at 06:21:59AM -0700, omgold wrote:
> > it is on my TODO list to write a pager for kitty which will solve your accuracy and flicker problems.
> 
> I'm not sure I understand. Maybe you could you elaborate what you mean by pager? I would be curious whether it could be used to implement accurately-rendered keyboard select as a kitten.

A pager like less, except with more advanced features, including text
selection by keyboard and mouse.

It wont need a kitten, it will just work out of the box. And be useful
in many more contexts than just text selection in the scrollback. I
just need to find the time to write it. 

Or you can write one yourself if you don't want to wait.

**Comment by omgold** [comment]
> A pager like less, except with more advanced features, including text selection by keyboard and mouse.

Ah, yes, that would be awesome. Seems exactly what I want.

> Or you can write one yourself if you don't want to wait.

Don't know right how, how I would go about it. Seems to be necessary to rather deeply integrate it with the kitty code.

**Comment by kovidgoyal** [comment]
On Tue, Oct 04, 2022 at 12:50:25AM -0700, omgold wrote:
> > A pager like less, except with more advanced features, including text selection by keyboard and mouse.
> 
> Ah, yes, that would be awesome. Seems exactly what I want.
> 
> > Or you can write one yourself if you don't want to wait.
> 
> Don't know right how, how I would go about it. Seems to be necessary to rather deeply integrate it with the kitty code.

No, no integration is required. You just use the standard terminal
escape codes to do things, including some kitty pioneered extensions, if
needed, which are all documented in the kitty website.

You do need to know how to program for terminals though.

**Comment by omgold** [comment]
> No, no integration is required. You just use the standard terminal escape codes to do things,

Okay, I see.

But do all the needed control codes actually exist already? Okay, I see the kitty extensions for pasting into the clipboard or moving up the scrollback buffer, which would likely be needed. But what about controlling the selection, or alternatively querying screen contents? After a bit of googling, I couldn't find anything in that vein. That latter way would probably not a good idea for security reasons anyway. So which control codes would I use for this?

**Comment by kovidgoyal** [comment]
On Tue, Oct 04, 2022 at 04:36:30AM -0700, omgold wrote:
> > No, no integration is required. You just use the standard terminal escape codes to do things,
> 
> Okay, I see.
> 
> But do all the needed control codes actually exist already? Okay, I see the kitty extensions for pasting into the clipboard or moving up the scrollback buffer, which would likely be needed. But what about controlling the selection, or alternatively querying screen contents? After a bit of googling, I couldn't find anything in that vein. That latter way would probably not a good idea for security reasons anyway. So which control codes would I use for this?

You dont need to query the screen contents, the screen contents are
passed to you by kitty over stdin. And you manage your own selections,
and you own mouse and keyboard interactions.

**Comment by omgold** [comment]
> You dont need to query the screen contents, the screen contents are passed to you by kitty over stdin. And you manage your own selections, and you own mouse and keyboard interactions.

Well, isn't that exactly what kitty_grab does? Which results in the nightmare mentioned above of trying to align the location of the cursor on the screen with the position in the byte stream you get passed on stdin.

**Comment by omgold** [comment]
> you just count soft and hard line breaks till you get to the line with the cursor, then you use wcswidth to position the cursor on that line.

That is what kitty_grab does, (when applying the patch I posted there), but it still messed up often enough that I gave up on it. So I feel it would be much easier to have a keyboard selector which just accesses the information kitty has readily available internally.

**Comment by kovidgoyal** [comment]
I dont see how it could be messed up, the information is the same as kitty has internally, it's not like kitty is keeping secrets. If there is further information needed, just ask for it and I will be happy to provide a way to pass it to the pager.

 In any case, if you cannot get it to work, then you need to wait for me to implement it. I can assure you I will get it to work 100% robustly.

**Comment by omgold** [comment]
Honestly I don't know how exactly it stilled messed up.

I think I will just look forward to the new pager. It probably is best if the same person who develops kitty to implements and maintains it to have it work accurately.

**Comment by amosbird** [comment]
> I'm afraid I have no interest in doing so. I will say it is on my TODO list to write a pager for kitty which will solve your accuracy and flicker problems.

Apologies for revisiting this old issue, but I'm afraid that using a pager reading from stdin wouldn't resolve the flickering problem when the scrollback buffer is excessively large.

I've noticed some initial work has been done under `kitty/kittens/pager`. I'm curious whether it's feasible to leverage shared memory to enable this pager to instantly render the entire scrollback buffer of kitty.

**Comment by kovidgoyal** [comment]
On Wed, May 29, 2024 at 02:45:28AM -0700, Amos Bird wrote:
> > I'm afraid I have no interest in doing so. I will say it is on my TODO list to write a pager for kitty which will solve your accuracy and flicker problems.
>
> Apologies for revisiting this old issue, but I'm afraid that using a pager reading from stdin wouldn't resolve the flickering problem when the scrollback buffer is excessively large.

Why are you afraid of that? The pager uses SIMD so should be able to
parse at ~ 1GB/s

>
> I've noticed some initial work has been done under `kitty/kittens/pager`. I'm curious whether it's feasible to leverage shared memory to enable this pager to instantly render the entire scrollback buffer of kitty.

You dont need to render the entire scrollback buffer. Just one screen at
atime and you can get to the correct starting line by searching through
the text for newlines + carriage returns which is done using SIMD.

**Comment by amosbird** [comment]
> Why are you afraid of that? The pager uses SIMD so should be able to parse at ~ 1GB/s

I'm uncertain whether fast throughput alone is sufficient to prevent flickering. I'm using the default pager with the following options: `scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER`. When I test with a scrollback buffer of 10,000 lines, it flickers every time I use the `show_scrollback` command. It's possible that there's an inherent fixed latency that cannot be eliminated by spawning and reading from stdin.

**Comment by parisni** [comment]
Hi @kovidgoyal the new pager you are working on sounds good. FYI there is the [ov pager written in go](https://github.com/noborus/ov) that might be of interest as a basis.
