### ISSUE TITLE
Build error: 'UniformTypeIdentifiers/UniformTypeIdentifiers.h' file not found

### ISSUE THREAD

**Issue by templateK** [kovidgoyal/kitty#5556]
**Describe the bug**
v0.26.3 build error on macOS mojave. 

**To Reproduce**
1. ```git clone https://github.com/kovidgoyal/kitty.git```
2. ```git checkout v0.26.3```
3. ```cd kitty; LDFLAGS=-L/libs/librsync/lib python3 setup.py --extra-include-dirs /libs/librsync/include```
4. Result
> clang -MMD -DNDEBUG -D_GLFW_COCOA -D_GLFW_BUILD_DLL -DGL_SILENCE_DEPRECATION -Wextra -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidden -D_FORTIFY_SOURCE=2 -flto -I/libs/librsync/include -DKITTY_HAS_RS_SIG_ARGS -fPIC -c glfw/cocoa_window.m -o build/glfw-cocoa-cocoa_window.m.o
glfw/cocoa_window.m:34:9: fatal error: 'UniformTypeIdentifiers/UniformTypeIdentifiers.h' file not found
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>

**Environment details**
```
Build Environment
OS: macOS mojave(10.14.5) 
macOS SDK version(10.14)
Apple clang version 11.0.0 (clang-1100.0.33.17)
```

**Additional context**
I looked ```UniformTypeIdentifiers.h``` up on the my local machine sdk directory if it exists and I found out there's no such file.
So looked it up online then It seems it exists only on the ```macOS sdk version >= 11.0```. 

The latest successful commit is 9a99554ed323d07cb75b22c9598d3a6d3d9094cc on the above environment.

**Comment by kovidgoyal** [comment]
So use a macos 11 SDK they are free to download as far as I know.

**Comment by templateK** [comment]
While it is free for download the macOS 11 SDK, it's not installable on macOS mojave.

The latest installable ```xcode command line tools``` version on macOS mojave is ```11.3.1``` which contains 
only macOS SDK version ```10.14``` unless there is some magic which can bypass the version restriction.

I know it's outdated OS.  So I have no problem with dropping support on this macOS version.

Cheers.

**Comment by kovidgoyal** [comment]
Ah well, that's unfortunate, but yes, kitty's minimum macOS version is
currently 10.15, so mojave is not officially supported, sorry.
