### ISSUE TITLE
Bold Text Color

### ISSUE THREAD

**Issue by cyansprite** [kovidgoyal/kitty#5559]
**Is your feature request related to a problem? Please describe.**

This isn't a "problem" per se, and I've seen other requests/issues shot down based on asking for normal colors being turned bright for bold text, this is not what I'm asking. I understand using 90\~97 instead of 30\~37 for ansi codes, this is not what I'm asking.
I'm asking for whenever normal colored text is bold, making it a different color.

Why? A picture is worth a thousand word (see additional content below), this is using the program `man` in kitty on left, and gnome-terminal on the right.
Notice how the bold text comes forward much more when it's a color? This is VERY helpful using classic tools like man, or even just reading stdout logs. You can't always control what an application will output. 

Thanks for your time and if this falls in line with your opinion on the bright bold colors that's your decision, your application.

**Describe the solution you'd like**
Normal text that is bold uses a specific color set in a color theme file or kitty.conf

**Describe alternatives you've considered**
A different terminal emulator but I like this one.

**Additional context**
![image](https://user-images.githubusercontent.com/25287750/194154928-92e76da6-0884-4629-a7a6-112eb79e17d6.png)

**Comment by kovidgoyal** [comment]
Except that you can control the output of man. here's a screenshot of man kitty on my system in kitty:
![screenshot](https://user-images.githubusercontent.com/1308621/194200723-c9b56d14-2b26-4947-87db-ff6a544e0b23.png)

Putting ill-thought out hacks into terminal emulators is not the way. Set MANPAGER to this script

```py
#!/usr/bin/env python3

import os

# Blink -> Bold + GREEN
os.environ['LESS_TERMCAP_mb'] = "\033[1;32m"
# Bold -> Bold + CYAN
os.environ['LESS_TERMCAP_md'] = "\033[1;36m"
# Reset all attributes
os.environ['LESS_TERMCAP_me'] = "\033[0m"
# Standout -> Bold + yellow on blue
os.environ['LESS_TERMCAP_so'] = "\033[1;33;44m"
# End standout
os.environ['LESS_TERMCAP_se'] = "\033[22;39;49m"
# Underline -> Italic + red
os.environ['LESS_TERMCAP_us'] = "\033[3;31m"
# End underline
os.environ['LESS_TERMCAP_ue'] = "\033[23;39m"
# Dim mode
os.environ['LESS_TERMCAP_mh'] = "\033[90m"

os.execlp('less', 'less', '-R')
```

**Comment by cyansprite** [comment]
Not sure I'd call it a hack but fair enough.

Thanks for the comment! I didn't actually know you can alter less colors like this but I did know of less -R.

Here is a bash example, you could also export MANPAGER to "less -R" rather than aliasing, but I would prefer less always give me color.

```bash
# enter blinking mode - red
export LESS_TERMCAP_mb=$'\e[00;31m'
# enter double-bright mode - bright cyan
export LESS_TERMCAP_md=$'\e[01;95m'
# enter standout mode - bright yellow
export LESS_TERMCAP_so=$'\e[01;93m'
# enter underline mode - underscore, bright cyan
export LESS_TERMCAP_us=$'\e[04;96m'

# turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_me=$'\e[0m'
# leave standout mode
export LESS_TERMCAP_se=$'\e[0m'
# leave underline mode
export LESS_TERMCAP_ue=$'\e[0m'

# use color output for less
alias less="less -R"
```

**Comment by alkaris2** [comment]
This doesn't make any sense at all, how can you tell Kitty to display color for Man Pages? Simply creating the script alone isn't enough and doing in the Kitty config `MANPAGE=/path/to/script/pager.py' it just does nothing, nor does it execute and display how it should.

I really think it be much easier and simpler if there was a better way of setting the color of Bold text simply by adding a line that says `font_bold_color #3C43C4` into your kitty.conf so any text that is just default color with Bold formatting to it, becomes the color you choose. So if by default bold text that is `#FFFFFF` you can just change it to be `#3C43C4` or some other color unless overridden with another color it should display.

**Comment by kovidgoyal** [comment]
That's because the environment variable is MANPAGER not MANPAGE.
