### ISSUE TITLE
Where in the code does it allow you to change the PPI?

### ISSUE THREAD

**Issue by FrancescoMagliocco** [kovidgoyal/kitty#556]
This isn't an issue, but rather a question.  I have done a quick search, searching for `dpi` because I'm curious as to if I'm able to set the *dpi/ppi* manually.

I'm basically asking if there is a way to override the *dpi/ppi*.  I'm not asking for it to be implemented because I know everyone case will be different than mine, I'm just merely asking where in the code I can do such a thing so I can just customize my code for my needs.

Once I find this out, I will eventually work on a way for this to be implemented so it does it automatically given which Window Kitty is open on as I know I have read in one of the remarks that there is no current policy to do this.

**Comment by kovidgoyal** [comment]
DPI is queries from the OS, it is not manually settable and it is changed automatically if the DPI of th emonitor is changed/kitty is moved to another monitor. The only limitation is that kitty supports only a single global DPI not a per window one. Look for logical_dpi_x to see how it is set/used.
