### ISSUE TITLE
macOS: cannot drag/resize kitty window with tools like Easy Move+Resize

### ISSUE THREAD

**Issue by jfchevrette** [kovidgoyal/kitty#5561]
**Describe the bug**
I use tools like [Easy Move+Resize](https://github.com/dmarcotte/easy-move-resize) which allows me to move and resize windows using a keyboard key and the mouse by clicking anywhere within the window

With kitty this does not work. It is possible that the way kitty does windowing on macOS is incompatible with these tools. It is also possible that kitty captures keyboard or mouse events in such a way that prevents the tool from recognizing the keyboard & mouse events and thus prevent the drag or resize events from happening

I use a lot of different apps and tools on macOS and this has never happened before

**To Reproduce**
1. Install Easy Move+Resize
2. Open an app, observe that you can drag and resize the window using the keyboard shortcut and the mouse left & right click
3. Open kitty, observe that the kitty window cannot be dragged or resized using the same key+mouse combo

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Darwin jchevret-mac 22.1.0 Darwin Kernel Version 22.1.0: Tue Sep 27 22:07:43 PDT 2022; root:xnu-8792.41.6~5/RELEASE_ARM64_T8103 arm64
ProductName:            macOS ProductVersion:           13.0 BuildVersion:              22A5365d
Frozen: True
```

I have tested with and without the following config
```
clear_all_mouse_actions yes
clear_all_shortcuts yes
```

**Additional context**
I've tried to troubleshoot by starting kitty with `--debug-input` and whenever I hit the Easy Move+Resize keys and click & drag the mouse, the click or move mouse events do not show the debug output

**Comment by kovidgoyal** [comment]
kitty does not do any special windowing. As for keyboard handling, yes
kitty does special keyboard handling, but that is needed and I'm afraid
that is not going to change.
