### ISSUE TITLE
Window border

### ISSUE THREAD

**Issue by justaskz** [kovidgoyal/kitty#5564]
I am using option `macos_titlebar_color background` and have dark background. Now I noticed a thin line on the window border. Is it possible to remove it?

<img width="1422" alt="Screenshot 2022-10-08 at 20 57 07" src="https://user-images.githubusercontent.com/11331183/194721057-82843d2e-69cc-4e6b-8f16-2dbeeaa0afb6.png">

**Comment by kovidgoyal** [comment]
That's drawn by the OS not kitty, it cannot be controlled by kitty. You
can hide the windows decorations completely in which case only kitty
draws.
