### ISSUE TITLE
Confirm on close, but only for tabs, if tab number > 1

### ISSUE THREAD

**Issue by nosvagor** [kovidgoyal/kitty#5565]
**Is your feature request related to a problem? Please describe.**

As far as I can tell, `confirm_on_window_close 1` is the only way to trigger this event. I don't use kitty’s windows management&mdash;my tiling window manager does (I love my objectively useless, but pretty, animations)&mdash;so I only use kitty's tabs. 

I don't want to be asked to confirm on close if I only have one tab, even if an application is running. However, like typical web browsers, I'd like the option to confirm on close if multiple tabs are open, since sometimes I kill the window on accident due to muscle memory of closing tiled terminals. 

I used to use tmux for this issue, as I could reattach to the session after closing it on accident. But I'm moving away from tmux now and learning kitty (thanks, by the way. Kitty is definitely a better solution than tmux). 

**Describe the solution you'd like**
A simple boolean setting under tab management would do, similar to maybe: `confirm_multiple_tabs_close true/false` 

**Describe alternatives you've considered**
I will be diving into the codebase to figure out how confirm_os_window_close is implemented, and maybe call the function if the number of tabs is greater than 1, but I'd bet others might find a config setting easier, and the implementation doesn't sound terribly complex (forgive my ignorance, if not).  

Perhaps I could also create persisting kitty sessions like tmux, but as of now I am not sure how to do that. Also, I don't always want to make sessions just to avoid this issue, as sometimes I have two or more tabs open in some random terminal for a random thing I'm working on.

**Comment by page-down** [comment]
> I don't use kitty’s windows management—my tiling window manager does ... so I only use kitty's tabs.
> I don't want to be asked to confirm on close if I only have one tab, even if an application is running.

- `confirm_on_window_close` counts the number of windows (not tabs).
- You won't create any kitty windows in a tab. So the number of tabs is equal to the number of windows.
- Configure `confirm_on_window_close 2`.
- Done.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.confirm_os_window_close

> ... create persisting kitty sessions ...

Currently kitty does not support daemon mode.

**Comment by kovidgoyal** [comment]
As @page-down said if you are not using windows inside tabs,
confirm_os_window_close already does what you need.

**Comment by nosvagor** [comment]
Ops, thanks. I thought 0/1 mean true/false; I did not know it was an integer. 

Totally solves the issue.
