### ISSUE TITLE
can you support fcitx5 in future

### ISSUE THREAD

**Issue by newyorkthink** [kovidgoyal/kitty#5566]
fcitx5 is modern input tools, it can useful with i3wm env.

**Comment by kovidgoyal** [comment]
fcitx already provides ibus compatibility. So it will work out of the
box.

**Comment by Freed-Wu** [comment]
I have add these in `~/.xprofile`

```sh
export GLFW_IM_MODULE=ibus
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```

But, fcitx still cannot work in kitty (it can work for other program). Does other something need to do?

**Comment by kovidgoyal** [comment]
No idea, I dont use fcitx, probably you need to enable its ibus
compatibility mode.
