### ISSUE TITLE
kitty doesn't detect Pragmata Pro

### ISSUE THREAD

**Issue by tilda** [kovidgoyal/kitty#557]
Hi! I've recently decided to start using kitty as a terminal because I'm looking around for one.
I generally use Pragmata Pro for monospace fonts, but kitty doesn't seem to detect it.
`kitty list-fonts`:
![screenshot 2018-05-20 15-58-21](https://user-images.githubusercontent.com/8301262/40283612-aadcae56-5c46-11e8-8324-acfdbdd3c392.png)

`fc-match "PragmataPro"`:
![screenshot 2018-05-20 16-00-19](https://user-images.githubusercontent.com/8301262/40283626-efbb3aba-5c46-11e8-8362-fc90b1931c66.png)

**Comment by anirudhb** [comment]
Does using kitty with Pragmata Pro, despite it not being there, work?
Also, how have you installed it?

**Comment by anirudhb** [comment]
If you have root access, maybe try installing into /usr/share/fonts
Also, try editing the fontconfig config file (if you have one)

**Comment by anirudhb** [comment]
Either way this is a bug

**Comment by kovidgoyal** [comment]
Kitty will only use monospace fonts, that is fonts that report having a spacing of 100. Presumably your font is not one of them.

```
fc-list : family spacing | grep spacing
```

**Comment by MarSoft** [comment]
Similar problem here. But in my case it is `Iosevka` which cannot be detected.
I have installed `Iosevka` in `$HOME/.local/share/fonts`. `fc-list` can see it:

```
$ fc-list : family spacing | grep -i iosevka
Iosevka StFW,Iosevka StFW Thin:spacing=90
Iosevka StFW:spacing=90
Iosevka StFW,Iosevka StFW Heavy:spacing=90
Iosevka StFW,Iosevka StFW Medium:spacing=90
Iosevka StFW,Iosevka StFW Oblique:spacing=90
Iosevka StFW,Iosevka StFW Heavy Oblique:spacing=90
Iosevka StFW,Iosevka StFW Extralight Oblique:spacing=90
Iosevka Nerd Font
Iosevka StFW,Iosevka StFW Extralight:spacing=90
Iosevka StFW,Iosevka StFW Light:spacing=90
Iosevka StFW,Iosevka StFW Medium Oblique:spacing=90
Iosevka StFW,Iosevka StFW Thin Oblique:spacing=90
Iosevka StFW,Iosevka StFW Light Oblique:spacing=90
Iosevka StFW,Iosevka StFW Bold Oblique:spacing=90
```
But `kitty list-fonts` cannot see it:
```
$ kitty list-fonts
Courier New
    Courier New

Cousine
    Cousine
    Cousine Bold
    Cousine Bold Italic
    Cousine Italic

DejaVu Sans Mono
    DejaVu Sans Mono
    DejaVu Sans Mono Bold
    DejaVu Sans Mono Bold Oblique
    DejaVu Sans Mono Oblique

DejaVu Sans Mono for Powerline
    DejaVu Sans Mono for Powerline
    DejaVu Sans Mono for Powerline Bold
    DejaVu Sans Mono for Powerline Bold Oblique
    DejaVu Sans Mono for Powerline Oblique

Droid Sans Mono
    Droid Sans Mono

Fira Code
    Fira Code Bold
    Fira Code Bold
    Fira Code Light
    Fira Code Light
    Fira Code Medium
    Fira Code Medium
    Fira Code Regular
    Fira Code Regular
    Fira Code Retina
    Fira Code Retina

Fira Mono
    Fira Mono
    Fira Mono
    Fira Mono Bold
    Fira Mono Bold
    Fira Mono Medium
    Fira Mono Medium

FreeMono
    FreeMono
    FreeMono Bold
    FreeMono Bold Oblique
    FreeMono Oblique

Liberation Mono
    Liberation Mono
    Liberation Mono Bold
    Liberation Mono Bold Italic
    Liberation Mono Italic

Monoid
    Monoid Bold
    Monoid Italic
    Monoid Regular
    Monoid Retina

Nimbus Mono PS
    NimbusMonoPS-Bold
    NimbusMonoPS-BoldItalic
    NimbusMonoPS-Italic
    NimbusMonoPS-Regular

Source Code Pro
    Source Code Pro
    Source Code Pro Black
    Source Code Pro Black Italic
    Source Code Pro Bold
    Source Code Pro Bold Italic
    Source Code Pro ExtraLight
    Source Code Pro ExtraLight Italic
    Source Code Pro Italic
    Source Code Pro Light
    Source Code Pro Light Italic
    Source Code Pro Medium
    Source Code Pro Medium Italic
    Source Code Pro Semibold
    Source Code Pro Semibold Italic

Triplicate T4
    Triplicate T4
```
Installed package versions:
`kitty 0.10.0-r21 g6fbb953` (from git)
`fontconfig 2.13.0+10+g58f5285`

I tried to track it down myself but it looks like the code for kitty's `fc_list` function and fontconfig's `fc-list` executable is basically the same.

**Comment by dsifford** [comment]
@kovidgoyal Any tips at all as to how to make known monospace fonts appear as monospace to kitty?

I've tried for probably the last 2 hours to get my beloved Monaco font to show up by adding changes to my user fontconfig file to no avail.

Specifically, this does not work:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

    <match target="font">
        <test name="family"><string>Monaco</string></test>
        <edit name="spacing" mode="assign"><const>mono</const></edit>
        <edit name="spacing" mode="assign"><int>100</int></edit>
    </match>

</fontconfig>
```

I'm going to be so sad if I can't use Monaco with kitty. Borderline dealbreaker for me.

Any help you can afford me is greatly appreciated.

**Comment by kovidgoyal** [comment]
Edit the font in fontforge to change its spacing property to be 100.

**Comment by dsifford** [comment]
No dice. Unless I'm totally oblivious, that property doesn't exist anywhere in fontforge. I checked with a working monospace font as well and to the best of my knowledge both match up.

Total bummer.

**Comment by kovidgoyal** [comment]
fontconfig has to be reading some property from the font file to
determine the value of spacing. You just need to figure out what that
property it is, a quick grep in the fontconfig sources should tell you
the answer.

**Comment by kovidgoyal** [comment]
For example: https://github.com/google/fonts/issues/225

**Comment by kovidgoyal** [comment]
There you go: https://github.com/behdad/fontconfig/blob/a8a6efa805fc03e790214e8a0bc55843a258d774/src/fcfreetype.c#L2348-L2415

**Comment by kovidgoyal** [comment]
So apparently fontconfig checks the actual glyph advances so if it says a font is not monosaced it means the font contains glyphs with different advances. So what you need to do is track down what those glyphs are and remove them from the font with fontforge.

**Comment by kovidgoyal** [comment]
Trying to shoehorn the rendering of variable width characters into monospaced form is ugly -- any typography expert will tell you never to do that. I am not going to do it either. If you want monospaced characters use a real monospaced font -- there are hundreds of them out there, it's not like we are suffering from some kind of shortage of them.

**Comment by andreypopp** [comment]
afaik PragmataPro ships a variant with “Mono” suffix which is detected fine
by kitty. I use it.

**Comment by Althorion** [comment]
Yes, but it doesn’t use ligatures, and those are one of the selling features of kitty.

**Comment by andreypopp** [comment]
Have you tried it? I use it and I have ligatures.

**Comment by Althorion** [comment]
I don’t have it, but [their very website](https://www.fsd.it/shop/fonts/pragmatapro/) states

> PragmataPro Mono is a very monospaced without ligatures.

**Comment by andreypopp** [comment]
Maybe they worded it wrong on a website — essential doesn’t have features
while mono variant certainly has them. This is my kitty.conf —
https://gist.github.com/andreypopp/75510787f5d62ab6df4317eb36ade337

Also mono variant comes for free with all versions but essential (which
already without ligatures), check your downloaded archive.

**Comment by andreypopp** [comment]
@Althorion well, I don't what we are arguing about — I use Mono variant (see the config I linked above) and **have** ligatures (see screenshot):
<img width="752" alt="screen shot 2018-07-07 at 10 52 37" src="https://user-images.githubusercontent.com/30594/42408336-c5f65da6-81d3-11e8-888a-129359314e61.png">

**Comment by andreypopp** [comment]
That's what I have in the archive download from the store — they have Mono and non-Mono variants both with ligatures and w/o:
<img width="882" alt="screen shot 2018-07-07 at 10 54 54" src="https://user-images.githubusercontent.com/30594/42408365-34163dc4-81d4-11e8-8510-b5a0cb04d64a.png">

**Comment by Althorion** [comment]
Thanks. It looks like they changed that some time ago and forgot to update their website.

**Comment by klardotsh** [comment]
Even using @andreypopp's config, I can't seem to use `kitty` with PragmataPro. It's not detected at all by `kitty list-fonts`, probably because the spacing is listed as 90 (which is apparently "dual spacing", whatever that means - I'm guessing that's something to do with Unicode support - CJK? emojis?)

This is basically a showstopper bug for what otherwise appears to be an awesome terminal - I'd strongly agree with @anirudhb (https://github.com/kovidgoyal/kitty/issues/557#issuecomment-403190110) that allowing an advanced mode override would be wonderful here.

**Comment by klardotsh** [comment]
I just brute-forced `PragmataPro Mono` by overriding the `monospace` fallback in kitty/fonts/fontconfig.py:L65, and it worked beautifully. However, this is a ridiculous hackaround - the cleaner option is probably going to be allowing `FC_DUAL` spacing on my local branch and seeing what breaks.

**Comment by kovidgoyal** [comment]
No, kitty is not going to support non-monospaced fonts. It might work "beautifully" for you, but it cannot work in general and you are not the one that has to provide support for kitty. I refuse to implement broken by design features into software I am responsible for.
