### ISSUE TITLE
desktop notifications do not work when tmux is used

### ISSUE THREAD

**Issue by arturo-salinas** [kovidgoyal/kitty#5570]
**Describe the bug**

**To Reproduce**
1. XXX
2. YYY
3. ZZZ

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by page-down** [comment]
That's because tmux doesn't recognize the escape sequence, so it's not forwarded to kitty.
You need to wrap it manually using the tmux passthrough escape sequence.

https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it

Note that this feature is disabled by default in tmux 3.3.
> - The passthrough escape sequence is now controlled by an option (allow-passthrough), default is off (recommended).

**Comment by arturo-salinas** [comment]
It does not seem to work. I used:
echo '\033Ptmux;\033\033]\x1b]99;;tmux! Work finished!\x1b\\\07\033\\'

Is there something wrong?

**Comment by trygveaa** [comment]
@arturo-salinas: See this script for how to do it: https://gist.github.com/trygveaa/e304621f53c62c792864faeedfddb86b

**Comment by arturo-salinas** [comment]
I tested the script and it doesn't work.

Thank you and best regards

**Comment by trygveaa** [comment]
If you use tmux 3.3 or newer you have to set the config option `allow-passthrough` to `on`. Also note that it won't work if the pane isn't visible. In the next release of tmux you can set it to `all` to make it work in invisible panes.

**Comment by arturo-salinas** [comment]
Strange! I use tmux 3.2 and the script does not work.

But the problem is just over ssh. Locally, it works fine.
