### ISSUE TITLE
Kitty 0.26.3 seems to break custom hints scripts

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#5573]
**Describe the bug**
0.26.3 Kitty breaks custom python hint scripts.   It shows an error like this:

```
Traceback (most recent call last):
  File "lib/python3.9/kittens/hints/main.py", line 513, in run
  File "lib/python3.9/kittens/hints/main.py", line 451, in load_custom_processor
  File "lib/python3.9/runpy.py", line 268, in run_path
  File "lib/python3.9/runpy.py", line 97, in _run_module_code
  File "lib/python3.9/runpy.py", line 87, in _run_code
  File "/Users/evng/.config/kitty/custom-hints.py", line 3, in <module>
    from kitty.fast_data_types import set_clipboard_string
ImportError: cannot import name 'set_clipboard_string' from 'kitty.fast_data_types' (/Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions/kitty.fast_data_types.so)
Press Enter to quit
```

**To Reproduce**
1. Copy [this gist](https://gist.github.com/esn89/6e900abf4e131988a9c162068545aeb1) into `custom-hints.py` inside of: `~/.config/kitty/`
2. Add these 2 lines into your `~/.config/kitty/kitty.conf`:
```
map kitty_mod+q kitten hints --customize-processing custom-hints.py --program -
map kitty_mod+s kitten hints --customize-processing custom-hints.py --program @
```
3. Find a string in your terminal which resembles a kubernetes resources:

```
pod-asdf-1234
deployment-fdsa-asdf
something-cool-hint
```

**Screenshots**

<img width="1438" alt="Screen Shot 2022-10-10 at 9 20 28 AM" src="https://user-images.githubusercontent.com/1475220/194911503-d0abacff-cce0-4d5d-81d5-2cba1bcda2c0.png">

**Comment by kovidgoyal** [comment]
set_clipboard_string needs to be imported from kitty.clipboard now.

**Comment by esn89** [comment]
@kovidgoyal thank you, it works.
