### ISSUE TITLE
macOS: startup session breaks when launched from Spotlight but works from command line

### ISSUE THREAD

**Issue by okuuva** [kovidgoyal/kitty#5575]
**Describe the bug**
I have the following in my `startup.session`:
```
cd ~/gits/dotfiles/
launch abduco -fA nvim-dotfiles fish --interactive --login --init-command nvim

new_tab nvim nvim
cd ~/gits/nvim/
launch abduco -fA nvim-nvim fish --interactive --login --init-command nvim
```
The idea is to have [abduco](https://github.com/martanne/abduco) sessions for projects I have always open.
The problem is that if I try to start `kitty` from Spotlight the startup session isn't working. I get a glimpse of `kitty` window opening before it closes again.
Running `abduco` on the commandline shows that there aren't any sessions open:
```bash
oula-buutti-mbp in ~/.config/skhd
❯ abduco
Active sessions (on host oula-buutti-mbp.spike.fi)
oula-buutti-mbp in ~/.config/skhd
❯
```
Kitty is still running according to `pgrep`:
```bash
oula-buutti-mbp in ~/.config/skhd
❯ pgrep -lf kitty
758 /Applications/kitty.app/Contents/MacOS/kitty
760 /Applications/kitty.app/Contents/MacOS/kitty
6849 git diff --submodule --no-ext-diff --unified=3 --color=always --cached -- kitty
oula-buutti-mbp in ~/.config/skhd
❯
``` 

But if I run `kitty` from command line (either just `kitty` or `open -a kitty`) it works. After that launching from Spotlight works too so it is not entirely to blame here.

**To Reproduce**
1. This probably has something to do with `abduco` so have that installed
1. Use the `session` file described above as a startup session
2. Try to launch with Spotlight
3. `kitty` window flashes on the screen and then goes away but `kitty` is still running
4. Quit `kitty`
5. Run `kitty` from cmd line (either `kitty` or `open -a kitty`)
6. `kitty` behaves as expected

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Darwin oula-buutti-mbp.spike.fi 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.6 BuildVersion:	21G115
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/fish
Loaded config files:
  /Users/oula/.config/kitty/kitty.conf

Config options different from defaults:
cursor                          None
font_family                     JetBrainsMono Nerd Font Regular
font_size                       19.0
kitty_mod                       shift+cmd
macos_colorspace                displayp3
macos_hide_from_tasks           True
macos_option_as_alt             3
macos_thicken_font              0.5
scrollback_pager_history_size   1073741824
selection_background            None
selection_foreground            None
startup_session                 /Users/oula/.config/kitty/startup.session
tab_bar_min_tabs                1
tab_bar_style                   custom
tab_title_template              {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}{sup.index}
visual_window_select_characters AOEUIDHTN1234567890

*Dropped colors and keyboard shortcuts as irrelevant*

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/local/Cellar/pyenv-virtualenv/HEAD-c537bff/shims:/Users/oula/.pyenv/shims:/usr/local/opt/gnu-sed/libexec/gnubin:/opt/X11/bin:/Users/oula/gits/go/bin:/Users/oula/bin:/usr/local/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/Cellar/pyenv-virtualenv/HEAD-c537bff/shims:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/oula/.local/bin:/Users/oula/.local/bin
	LANG                                en_US.UTF-8
	EDITOR                              nvim
	SHELL                               /usr/local/bin/fish
	USER                                oula
	LC_TERMINAL_VERSION                 3.4.16
	LC_CTYPE                            UTF-8
	LC_ALL                              en_US.UTF-8
	LC_TERMINAL                         iTerm2
	XDG_CONFIG_HOME                     /Users/oula/.config

```

**Additional context**
This does reproduces with `--config NONE`:
1. put `--config NONE --session <path to session file>` at the beginning of `macos-launch-services-cmdline` Other flags didn't seem to have effect as I tried this with and without them.
2. Spotlight launch fails still
3. `open -a kitty --args "--config NONE --session <path to session file>"` works

`abduco` doesn't have any config afaik. If it has I'm using the default config.

**Comment by okuuva** [comment]
Ok, false alarm. This has something to do with `$PATH`. I tried changing the `fish --interactive ...` with `bash` and that works from Spotlight as well but instead of `bash` 5.2 installed with Homebrew it launches the 3.2 version shipped along with macOS. Now I need to figure out how to make Spotlight respect my settings...

**Comment by page-down** [comment]
https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

> Now I need to figure out how to make Spotlight respect my settings...

You may want to use `exe_search_path` to add more bin paths under macOS.
This will take effect when the launch action looks for executable files.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

You can also configure `env PATH` for child process.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.env

**Comment by okuuva** [comment]
Ah, I only checked old issues but didn't run to any relevant ones with just "Spotlight" and forgot completely to check faq, my bad. Thanks for pointing me to right direction @page-down !
