### ISSUE TITLE
Allow hints on all windows

### ISSUE THREAD

**Issue by chmouel** [kovidgoyal/kitty#5577]
**Is your feature request related to a problem? Please describe.**

We are currently able to select hints (url, words, regexp, etc...	) on the current windows. When we have windows splitted it could be nice to have the selection happening on all windows in the current layout.

**Describe the solution you'd like**

A flag to `kitty +kitten hints` to let the user say i want to select a pattern on any windows in the current layout

**Describe alternatives you've considered**

**Additional context**

**Comment by kovidgoyal** [comment]
kittens run in a single window at a time, as such they cannot be used to
select text from multiple windows.
