### ISSUE TITLE
Have a custom configuration in bashrc for kitty

### ISSUE THREAD

**Issue by aurelien-m** [kovidgoyal/kitty#5578]
**Is your feature request related to a problem? Please describe.**
I would like to have a slightly different configuration for kitty in my `.bashrc` (or `.profile`, `.bash_profile`, whichever is used). This is because I use [oh-my-posh](https://ohmyposh.dev/docs/) and it doesn't work well in the bash gnome-terminal.

**Describe the solution you'd like**
It would be nice if I could do something like this in my `.bashrc`:
```bash
if kitty then;
    eval "$(oh-my-posh init bash)"
fi
```

If there's any way of doing this, I would also like to hear it! I also saw that `kitty.conf` exists but I couldn't find how to input commands like this. Thanks

**Comment by kovidgoyal** [comment]
The usual way to do this is to check $TERM

**Comment by aurelien-m** [comment]
Thanks!
