### ISSUE TITLE
Faster scroll with some key pressed

### ISSUE THREAD

**Issue by psydvl** [kovidgoyal/kitty#5580]
**Is your feature request related to a problem? Please describe.**
Now scroll is slow and smooth and there are some issues and PR's improved this
But sometimes you need just to scroll a big part of text fast. 

**Describe the solution you'd like**
It will be useful to implement fast scroll with some key pressed like Ctrl or Alt or Shift.
And it can be not smooth, I think.

**Describe alternatives you've considered**
Scrollbar maybe can solve this issue too, but when your terminal output become very long it can be not enough precise.

**Comment by kovidgoyal** [comment]
If you want to explore large scrollbacks, the best way to do it is using
the scrollback buffer. Preff ctrl+shift+h, then you can use page up/page
down or other customizable bindings to scroll by screen fulls
