### ISSUE TITLE
Kitty always wants to be at the front even when chosing apps behind it in stage-view macos

### ISSUE THREAD

**Issue by ad-chaos** [kovidgoyal/kitty#5587]
**Describe the bug**
When you have kitty at the very front in the app ordering, it'll try to come to front, even if you've chosen some other app from stage view.

**To Reproduce**
1. Open kitty, and some other apps as well
2. Make Sure kitty is at the top
3. Use the three fingers gesture to open stage view
4. Choose any other app window (other than a kitty window) and see kitty showing up instead of the chosen app.

**Screenshots**

https://user-images.githubusercontent.com/90276965/195969945-d2f53b0b-23a5-474c-9ef4-e93a91ed4503.mp4

**Environment details**
```
kitty 0.26.3 (6890e265b6) created by Kovid Goyal
Darwin ad-chaoss-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.5 BuildVersion:	21G72
Frozen: False
Paths:
  kitty: /Users/ad-chaos/git-repos/kitty/kitty/launcher/kitty.app/Contents/MacOS/kitty
  base dir: /Users/ad-chaos/git-repos/kitty
  extensions dir: /Users/ad-chaos/git-repos/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /Users/ad-chaos/.config/kitty/kitty.conf

Config options different from defaults:
bold_font               JetBrains Mono Bold
bold_italic_font        JetBrains Mono Medium Italic
cursor_beam_thickness   1.75
cursor_blink_interval   0.0
enabled_layouts         ['splits:split_axis=horizontal']
font_family             JetBrains Mono Medium
font_size               17.5
italic_font             JetBrains Mono SemiBold Italic
macos_option_as_alt     2
url_excluded_characters ↲
Added shortcuts:
	cmd+/ →  show_kitty_doc overview
	cmd+[ →  previous_tab
	cmd+] →  next_tab
Changed shortcuts:
	cmd+enter →  launch --cwd=current
	cmd+t →  launch --cwd=current --type=tab
	shift+cmd+[ →  neighboring_window left
	shift+cmd+] →  neighboring_window right
Colors:
# I don't think colors matter :)

Important environment variables seen by the kitty process:
	PATH                                /Users/ad-chaos/git-repos/kitty/kitty/launcher/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                ad-chaos
	LC_CTYPE                            UTF-8
```

**Additional context**
This reproduces on `kitty --config NONE` as well.

**Comment by page-down** [comment]
I don't believe there is an implementation in the kitty code that relates to this. Windows are managed by macOS.

The problem will occur with other apps as well.
https://apple.stackexchange.com/questions/29705/cmdtab-switches-to-the-correct-space-but-doesnt-bring-app-up-to-front

You can try using another third-party switcher to actually switch to the window, or report this bug to Apple (which is usually ignored and gets no helpful answer).

**Comment by ad-chaos** [comment]
Hmm, but as you see in the video, neither the app nor the window switches. I would've thought it was an apple bug if I experienced this with other apps as well, but I have yet not seen such a behaviour with any other apps, only when I have kitty open does this bug appear with apps behind kitty, where instead of switching to it, it just keeps kitty. Though, admittedly this bug is not consistently reproducible, but frequent enough to be a minor pain.

Would you mind pointing me where in the code does kitty handle window switching?

**Comment by kovidgoyal** [comment]
kitty does not handle window switching at all, that is an OS function.
You have most likely turned on secure keyboard entry, which makes apple
play games with focus stealing prevention. Turn it off under the kitty
menu in the global menu bar.

**Comment by ad-chaos** [comment]
Oh! Thank you so much, that was exactly the problem. I have no idea how that thing got turned on, oh well at least now its fixed 😅

**Comment by page-down** [comment]
@ad-chaos

> I have no idea how that thing got turned on, ...

I remembered that I submitted a PR just to disable this useless default shortcut.
https://github.com/kovidgoyal/kitty/pull/4478

In version 0.24.2 and later, the following can be configured.

```conf
map opt+cmd+s no_op
```

**Comment by ad-chaos** [comment]
Oh! I think that is most likely the coz, that I mispressed `opt+cmd+a` (which used to create a vertical split but I later just modified the `cmd+enter` behaviour with `enabled_layouts splits:split_axis=horizontal` ) as `opt+cmd+s`, didn't know that that was already bound to `secure keyboard input` :(

But, I have updated kitty a couple times since, so I wonder why was this option persistent, are some options cached?

Thanks for the suggestion! I think triggering this *bug* by mistake is no longer possible :)

**Comment by page-down** [comment]
> ... I wonder why was this option persistent ...

Preserving the state of this feature was also implemented in version 0.24.2.
https://github.com/kovidgoyal/kitty/issues/4471

This persistence is very annoying when running multiple kitty processes, and is stored immediately after toggle.
When you just want to temporarily enable it for the current kitty process, opening a new kitty process immediately will also enable it by default.
However I believe this feature does not worth more fine grained configuration options.

I'm glad this worked for you.

**Comment by ad-chaos** [comment]
Infact this also fixed the espanso problem for me! :D
Which makes sense, given secure keyboard entry restricts access to keyboard input to just kitty.

And yeah, I agree, its not worth putting in more effort into making this. Though having it documented would be nice. Currently, This [section](https://sw.kovidgoyal.net/kitty/actions/#action-toggle_macos_secure_keyboard_entry) currently doesn't say that the option is persistent for example. Also are there other options that are persistent as well?

**Comment by dgmora** [comment]
I was caught by the same thing and I was wondering what was happening. My config had these lines (commented)

```
#: Toggle macOS secure keyboard entry

# map opt+cmd+s toggle_macos_secure_keyboard_entry
```
I only installed kitty 1-2 months ago, but the default shortcut was still present and working. Is that expected? I thought this default mapping was removed. I was able to remove it by doing:

```
map opt+cmd+s ''
```

**Comment by kovidgoyal** [comment]
commented lines have no effect. They dont indicate a setting is not
applied, they show the default value of a setting. The default value is
still in effect. To unmap a shortcut you map it to no_op

**Comment by dgmora** [comment]
Would it make sense to remove this default mapping, or make it a more complicated one as a default? Is it used by many people? It feels like it's too easy to misclick.

**Comment by kovidgoyal** [comment]
It requires pressing 3 keys and is the same mapping as that for terminal.app IIRC.

**Comment by dgmora** [comment]
It is similar enough to other possible mappings that users may have. Or a user may have this mapping in another app and click it in kitty. And it does something that isn't visually noticeable. 

Not insisting more on this, just saying that it's not rare that users click it by mistake in kitty 🙂

**Comment by TrevorSayre** [comment]
> and is the same mapping as that for terminal.app IIRC.

<img width="266" alt="image" src="https://github.com/kovidgoyal/kitty/assets/421548/3c921f20-25e2-41ac-9b5f-397812762b56">

This appears to no longer be the case. This is after a fresh macOS install of Sonoma.
