### ISSUE TITLE
issue with displaying certain symbols

### ISSUE THREAD

**Issue by kamkow1** [kovidgoyal/kitty#5589]
Hello,
I'll try my best to describe the problem. When editing text files inside of kitty, I've encountered an issue with displaying these symbols: 
!= 
-> 
=> 
<=

Here's a screenshot:
![kitty](https://user-images.githubusercontent.com/84928696/195988281-a526b6f6-79ce-46fd-b946-f1247fb59bfb.png)

I'm new to kitty and I'm still learning it. How can I disable this and make kitty display these symbols normally?

**Comment by page-down** [comment]
Run `kitty --debug-font-fallback` to check the loaded fonts.

Install and configure a font that supports ligatures.
https://sw.kovidgoyal.net/kitty/conf/#fonts

If you want to disable ligatures:
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.disable_ligatures

**Comment by kamkow1** [comment]
> 

huge thanks! I've successfully managed to disable ligatures
