### ISSUE TITLE
duplicated characters in nix-shell

### ISSUE THREAD

**Issue by niyue** [kovidgoyal/kitty#5595]
**Describe the bug**
I use `devbox` (https://github.com/jetpack-io/devbox) for development. After launching devbox shell with `devbox shell`, I will get duplicated characters for all the chars I enter. For other terminals like iTerm2, there is no such issue.

**To Reproduce**
1. Install devbox
2. Run `devbox shell`
3. Enter some characters in the shell
4. You will see duplicated characters with different colors

**Screenshots**
I entered only `hello` in the prompt, but it shows multiple `h`/`e`/`l`
<img width="542" alt="image" src="https://user-images.githubusercontent.com/27754/196067944-1f2da5c6-3db1-4b60-aec7-aeaf61ed33dd.png">

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Darwin sac 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.6 BuildVersion:	21G115
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ss/.config/kitty/kitty.conf

Config options different from defaults:
font_family          Fira Code
font_size            15.0
Colors:
	background           #1c1c1c   
	color0               #3d352a   
	color1               #cd5c5c   
	color10              #88aa22   
	color11              #ffa75d   
	color12              #87ceeb   
	color13              #996600   
	color14              #b0c4de   
	color15              #ddccbb   
	color2               #86af80   
	color3               #e8ae5b   
	color4               #6495ed   
	color5               #deb887   
	color6               #b0c4de   
	color7               #bbaa99   
	color8               #554444   
	color9               #cc5533   
	cursor               #e2bbef   
	foreground           #ddeedd   
	selection_background #4d4d4d   
	selection_foreground #1c1c1c   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                ss
```

**Additional context**
I tried reproducing the problem with `kitty --config NONE`, and the problem still exists. I got some error printed on the terminal like below:
```
[290 08:53:27.868237] [PARSE ERROR] Unknown OSC code: 1337
[290 08:53:27.868251] [PARSE ERROR] Unknown OSC code: 1337
[290 08:53:27.868255] [PARSE ERROR] Unknown OSC code: 1337
[290 08:53:28.052679] [PARSE ERROR] Unknown OSC code: 1337
[290 08:53:28.052710] [PARSE ERROR] Unknown OSC code: 1337
2022-10-17 08:53:28.894 kitty[16360:122728] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
[290 08:53:29.575255] [PARSE ERROR] Unknown OSC code: 1337
```

**Comment by kovidgoyal** [comment]
This will be an issue with the shell configuration. I'm afraid I dont have the time/interest to learn enough about devbox to try to debug it. If you can figure out what shell it is running, with what configuration and post a minimal reproducer I will take a look.

**Comment by niyue** [comment]
> figure out what shell it is running

`echo "$SHELL"` shows It is using zsh on macOS. 

> with what configuration
Do you have any suggestion on what kind of configuration I should look for for investigating this kind of issue? For configuration, do you mean file `~/.zshrc` (which seems the only zsh shell configuration file I've ever touched on my system)?
