### ISSUE TITLE
Make margin tint optional, i.e. bring "bug" 3933 back as configurable option

### ISSUE THREAD

**Issue by cmcallister** [kovidgoyal/kitty#5596]
**Is your feature request related to a problem? Please describe.**
It's not really an problem but recently https://github.com/kovidgoyal/kitty/issues/3933 was "fixed" but I actually had set wide margins not realizing this was considererd a bug; it worked at giving a "gaps" like feel that you see in a lot of tiling WM.

**Describe the solution you'd like**
a config option that either toggles on the former lack of tinting on margins or an option that allows for setting the value for margins separately. The former seems simpler and certainly sufficient.

It feels like since this was considered a bug it's not likely to be brought back but I liked it

**Comment by kovidgoyal** [comment]
Not something I care to spend time on personally, but it should be a
very simple patch. Basically, line 970 in shaders.c tint_opacity should
be set to zero to avoid a tint over the gaps area. 

I will accept a patch adding an option such as 

background_tint_gaps (default 1.0)

then the final value of tint_opacity should be OPT(background_tint) * OPT(background_tint_gaps)
