### ISSUE TITLE
Alt key does not behave the native way on macos

### ISSUE THREAD

**Issue by splintah** [kovidgoyal/kitty#560]
Although I've specified `macos_option_as_alt yes` in my [config](https://github.com/splintah/dotfiles/blob/master/kitty/kitty.conf), kitty interprets combinations with alt as the 'classic' terminal shortcuts.
After some (little) investigation, I found this happens since v0.9.1, and did work with v0.9.0.

Do you have any idea why this could be?
If you want, I can test some commits between v0.9.0 and v0.9.1 to find out what commit broke it.

**Comment by kovidgoyal** [comment]
If you want alt to insert unicode characters, you have to set `macos_option_as_alt no`
