### ISSUE TITLE
kitty segfaults when pasting in some programs under KDE Plasma on Wayland

### ISSUE THREAD

**Issue by saucyfox** [kovidgoyal/kitty#5603]
**Describe the bug**
kitty crashes when I copy text from the terminal and paste into some programs (pasting within kitty works fine). I'm using it in a KDE Plasma session under Wayland on Arch. So far I've observed the behavior with Firefox and LibreOffice. Pasting within the Kate editor works fine, strangely, and I've verified that all of these are running under wayland (and not xwayland) by checking with `xwininfo`.

I'm honestly not sure whether this is a bug in kitty, plasma, or the programs I'm pasting to, but kitty is the only application I've noticed this behavior with.

**To Reproduce**
1. Select some text in kitty and copy it.
2. Paste in Firefox.
3. kitty segfaults with the error message `Aborted (core dumped)`

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Linux hostname 6.0.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:51 +0000 x86_64
Arch Linux 6.0.2-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/username/.config/kitty/kitty.conf

Config options different from defaults:
cursor_text_color       None
font_family             Hack
font_size               10.0
Colors:
	active_tab_background   #f8f8f2   
	active_tab_foreground   #282a36   
	background              #282a36   
	color0                  #21222c   
	color1                  #ff5555   
	color10                 #69ff94   
	color11                 #ffffa5   
	color12                 #d6acff   
	color13                 #ff92df   
	color14                 #a4ffff   
	color2                  #50fa7b   
	color3                  #f1fa8c   
	color4                  #bd93f9   
	color5                  #ff79c6   
	color6                  #8be9fd   
	color7                  #f8f8f2   
	color8                  #6272a4   
	color9                  #ff6e6e   
	cursor                  #f8f8f2   
	foreground              #f8f8f2   
	inactive_tab_background #6272a4   
	inactive_tab_foreground #282a36   
	mark1_background        #ff5555   
	mark1_foreground        #282a36   
	selection_background    #44475a   
	selection_foreground    #ffffff   
	url_color               #8be9fd   

Important environment variables seen by the kitty process:
	PATH                                /home/username/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/username/bin
	LANG                                en_US.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/bash
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                username
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     /home/username/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/username/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      8
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session6
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            2
```

**Additional context**
The issue persists with `kitty config=NONE`. I also tried using the [kitty-git AUR package](https://aur.archlinux.org/packages/kitty-git) to see if this was fixed in a development version, and I saw the same behavior. Note that the revision on the AUR page isn't accurate - that's just bumped manually by the maintainer periodically so people using AUR helper scripts can detect an update. The actually revisions for kitty/related packages were:
```
local/kitty-git 1:r10605.g03fe928e-1
    Modern, hackable, featureful, OpenGL based terminal emulator
local/kitty-shell-integration-git 1:r10605.g03fe928e-1
    Shell integration scripts for kitty, an OpenGL-based terminal emulator
local/kitty-terminfo-git 1:r10605.g03fe928e-1
    Terminfo for kitty, an OpenGL-based terminal emulator
```
I've attached the latest coredump if that's helpful.
[kitty.dump.gz](https://github.com/kovidgoyal/kitty/files/9815630/kitty.dump.gz)

Edit: an update to kitty version 0.26.4 was made available on the Arch repos very shortly after I submitted this report, and the issue still persists in that version.

**Comment by kovidgoyal** [comment]
That's an abort in libwayland not a crash, run kitty from another
terminal, there should be some information printed there. Also I cannot
reproduce with the following steps under KDE wayland

1) Start kitty
2) Run ls and copy some text
3) STart firefox
4) Paste into the address bar

Wrks as expected

**Comment by saucyfox** [comment]
I should have mentioned - firefox runs with xwayland by default. You have to set `MOZ_ENABLE_WAYLAND=1` in your environment to force it to use Wayland natively. I think some distros do that by default now, but as is typical for Arch it's the user's responsibility in this case. When I unset that variable and run firefox, I'm not able to reproduce it either.

Here's a short recording of the behavior: https://www.youtube.com/watch?v=ih7uhOV3DaE

**Comment by kovidgoyal** [comment]
seems to be KDE specific. Doesn't abort under sway or gnome. So report it
to kwin. The error from libwayland is listener function for opcode 0 of wl_data_source
is NULL I have no idea what that means. kitty always adds listeners for
data sources, indeed if it didn't copy/paste would not work at all. It
could be complaining about some of the fields in the wl_data_source
struct being null, which is silly, since the NULL fields are used for
drag and drop not copy paste and this is a copy/paste source.

**Comment by python-wizard** [comment]
I have exactly the same issue on Fedora 36 KDE Plasma 5.25.5 on Wayland with Nvidia drivers 520.56.06-1.
It appeared just after updating to Kernel 6.0.5 from Kernel 5.19 - but before restart, not sure whether the update impacted the system before restart on Fedora.
But I also don't copy from Kitty to Firefox every day. But it has to be reasonably recent.

I can post more info if you tell me what command to run.

Also, just confirmed, when I copy to Kwrite, there is no problem, only copying to Firefox causes a problem.
MOZ_ENABLE_WAYLAND is set to 1 in about:support.

**Comment by kovidgoyal** [comment]
this is already fixed in master, see the commit that closed the issue.
