### ISSUE TITLE
Can not change command line color under light theme

### ISSUE THREAD

**Issue by taozhang-tt** [kovidgoyal/kitty#5606]
**Describe the bug**
I want to use light theme，so i edit the .config/kitty/kitty.conf file and append some content:

color0 #fbf1c7
color1 #9d0006
color2 #79740e
color3 #b57614
color4 #076678
color5 #8f3f71
color6 #427b58
color7 #3c3836
color8 #9d8374
color9 #cc241d
color10 #98971a
color11 #d79921
color12 #458588
color13 #b16186
color14 #689d69
color15 #7c6f64
background #fbf1c7
selection_foreground #fbf1c7
cursor #282828
foreground #282828
selection_background #282828

it shows:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37895749/196678143-4c00e79e-8779-4875-b113-7e4a390d381a.png">

the command color is light green, how can i change it?

the same config under iterm2, it shows:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37895749/196678337-77beee90-3f9d-4bf8-a343-5bf271a20f3b.png">

something is wrong?

**Comment by kovidgoyal** [comment]
Whatever you are using to configure colors in zsh is probably special casing on TERM, giving you different colors in different terminal emulators. Fix that and you will be fine. Setting colors in kitty works fine, as you can test for yourself by any of the many scripts around that output terminal colors.
