### ISSUE TITLE
tmux status is not displayed correctly.

### ISSUE THREAD

**Issue by niketkandya** [kovidgoyal/kitty#561]
When I start tmux on kitty on my local mac, the status line is off by 1 character. Since the status line keeps getting redrawn, it tenders kitty unusable with tmux.

If I run tmux on a remote linux server, then the rendering is correct.

The same problem does not occur on iTerm.
<img width="1680" alt="tmux_local_macos" src="https://user-images.githubusercontent.com/2848862/40333233-6380cd00-5d0c-11e8-84d7-381443e06f84.png">
![tmux_remote_linux](https://user-images.githubusercontent.com/2848862/40333234-6396c2ea-5d0c-11e8-8d41-1940c17446d9.png)
See the images attached.

**Comment by kovidgoyal** [comment]
What versions of kitty and tmux? And does it happen with default configs for each?

**Comment by kovidgoyal** [comment]
no followup
