### ISSUE TITLE
Ligature in any font 

### ISSUE THREAD

**Issue by tamaki03** [kovidgoyal/kitty#5610]
Font ligature is great but I don't like Fire code ,Victor mono or SF Mono :( ... I want ligatures on kitty but use it with my favorite font
I found this repo and it work well in vscode , first font is "base ligature font" ( just have ligature ) , second is font you use 
It be very nice if kitty does it.

_The repo_ : https://github.com/nguyenvanlongweb/Font-Base-Ligatures

**Screenshots**
![image](https://user-images.githubusercontent.com/90030004/196854888-e997c1eb-5531-4124-b8f8-ec2d0993054d.png)
![image](https://user-images.githubusercontent.com/90030004/196855422-13dcf54c-5fba-41ad-934c-4d08d7f7a310.png)

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in supporting this.
