### ISSUE TITLE
kitty becomes unresponsive after drawing UTF-8 characters

### ISSUE THREAD

**Issue by hejops** [kovidgoyal/kitty#5611]
**Describe the bug**
First off, I'm not sure what the correct term for such characters should be, so correct me if I'm wrong. In any case, attempting to display a UTF-8 character causes kitty to become unresponsive.

**To Reproduce**
1. Copy the character in the first row, third column of [this page](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=10112&number=128&utf8=char); any of the characters in the third column should produce similar behaviour. I'm not sure how to reproduce the offending character in this (github's) text box, or with `XCompose`. My browser is Firefox.
1. `kitty --config NONE --dump-commands --debug-gl --debug-input --debug-keyboard --debug-font-fallback > kitty.log 2> kitty.log`
1. In the newly opened kitty window, paste the character (Ctrl+Shift+v).
1. kitty no longer responds to keypresses.
1. See debug log [here](https://gist.githubusercontent.com/hejops/fbe35a5f5c0a85684f89c6e17c046412/raw/473f1c29663d9f3ceb6b3beda862644a76d3158d/kitty.log)

- I don't think this is a font-specific issue (Fira Mono), because the issue occurs in `kitty` with the default font, and in `urxvt`, the same procedure with the same font does not lead to unresponsive behaviour (despite some rendering glitches).
- Pasting the character into vim produces `â` (displayed as `â<9e><80>`), without unresponsive behaviour.

**Environment details**
```
kitty 0.26.4 created by Kovid Goyal
Linux user 6.0.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Oct 2022 18:58:49 +0000 x86_64
Arch Linux 6.0.1-arch2-1 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
background_tint         1.0
clipboard_control       ('write-clipboard', 'write-primary')
close_on_child_death    True
confirm_os_window_close 0
cursor_blink_interval   0.0
dim_opacity             1.0
disable_ligatures       2
draw_minimal_borders    False
enable_audio_bell       False
font_family             Fira Mono
hide_window_decorations 1
inactive_text_alpha     0.8
modify_font:
    cell_height 0
    cell_width -1
mouse_hide_wait         0.0
open_url_with           ['xdg-open']
remember_window_size    False
strip_trailing_spaces   smart
tab_title_template      {title}
url_prefixes            ('http', 'https', 'file', 'ftp')
url_style               1
Added shortcuts:
	ctrl+e →  launch --cwd=current --type=os-window
	ctrl+g →  kitten hints --type url --program xdg-open
	f1 →  launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay less +G -R
Changed shortcuts:
	kitty_mod+e →  kitten hints
	kitty_mod+enter →  launch --cwd=current --type=os-window
	kitty_mod+h →  change_font_size current -2.0
	kitty_mod+j →  scroll_page_down
	kitty_mod+k →  scroll_page_up
	kitty_mod+l →  change_font_size current +2.0
Colors:
	background              #1d2021   
	color0                  #3c3836   
	color1                  #cc241d   
	color10                 #b8bb26   
	color11                 #fabd2f   
	color12                 #83a598   
	color13                 #d3869b   
	color14                 #8ec07c   
	color15                 #fbf1c7   
	color2                  #98971a   
	color3                  #d79921   
	color4                  #458588   
	color5                  #b16286   
	color6                  #689d6a   
	color7                  #a89984   
	color8                  #928374   
	color9                  #fb4934   
	cursor                  #bdae93   
	cursor_text_color       #665c54   
	foreground              #ebdbb2   
	selection_background    #d65d0e   
	selection_foreground    #ebdbb2   
	url_color               #458588   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/.local/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                user
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    tty
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Comment by kovidgoyal** [comment]
That's not kitty becoming unresponsive, that's bash. Run 
kitty cat
or
kitty zsh

instead and you will be fine. Or press ctrl+shift+enter to opena  new
kitty window to check that kitty is indeed not unresponsive.

As for why bash is becoming unresponsive,
you will need to ask the bash developers.

**Comment by kovidgoyal** [comment]
I took a slightly deeper look and the reason is that the characters in that column include the UTF-8 encoding for the C1 PM escape code, (U+009e encoded as 0xc2 0x9e in UTF-8) and bash is echoing that back to the terminal. The terminal then waits for that escape code to be completed, which requires the ST (string terminator) bytes to be sent to it. This is a general hazard with terminal. Once you start an escape code that requires a string terminator, the terminal will just put everything into that escape code till it sees an ST. I am guessing urxvt doesnt support C! escape codes.

And note that the text on that page is invalid. The correct UTF-8 encoding of  U+2780 is 0xe2 0x9e 0x80 but that page has a2c3 9ec2 80c2

**Comment by hejops** [comment]
Thanks for the info, good to know!
