### ISSUE TITLE
OS window with fixed size

### ISSUE THREAD

**Issue by locriacyber** [kovidgoyal/kitty#5615]
**Is your feature request related to a problem? Please describe.**
I want to use kitty as custom popup window to display ascii art.

**Describe the solution you'd like**
Add `--columns` and `--rows` as kitty startup options.

**Describe alternatives you've considered**
`kitty +kitten panel`: can't make the window not stick to screen border.
`kitty -o initial_window_width=20c`: Not working with my WM (Qtile).

**Additional context**
The spawned X window should not be resizable. (because it has fixed column and width)
Its position is handled by window manager with `--class`.

**Comment by kovidgoyal** [comment]
You can set initial window size using the initial_window_width/height
options. Also remember to turn off the remember_window_size option.
Whether your window manager respects that is up to it, since under X11,
the final decision of a window's size is upto the window manager not the
application. With tiling window managers like Qtile you should make the
window "floating".

As for making the window non-resizable, I have no interest in that, since
anyway, again it's upto the window manager. Simply dont resize it.

**Comment by locriacyber** [comment]
This is from `src/x11_window.c:596` in https://github.com/glfw/glfw.git
```
    XSetWindowAttributes wa = { 0 };
    wa.colormap = window->x11.colormap;
    wa.event_mask = StructureNotifyMask | KeyPressMask | KeyReleaseMask |
                    PointerMotionMask | ButtonPressMask | ButtonReleaseMask |
                    ExposureMask | FocusChangeMask | VisibilityChangeMask |
                    EnterWindowMask | LeaveWindowMask | PropertyChangeMask;

    _glfwGrabErrorHandlerX11();

    window->x11.parent = _glfw.x11.root;
    window->x11.handle = XCreateWindow(_glfw.x11.display,
                                       _glfw.x11.root,
                                       xpos, ypos,
                                       width, height,
                                       0,      // Border width
                                       depth,  // Color depth
                                       InputOutput,
                                       visual,
                                       CWBorderPixel | CWColormap | CWEventMask,
                                       &wa);
```

You can see that GLFW doesn't set WM_CLASS when a window is first created, so Qtile treats it as normal window.

Later, in the same file `WM_CLASS` is set:

```
        XSetClassHint(_glfw.x11.display, window->x11.handle, hint);
```

There is no way for Qtile to handle this cleanly. So I think Kitty should set the window size again after window creatiion.

**Comment by kovidgoyal** [comment]
There is no API in Xlib to set window class when creating a window. And other tiling managers handle this just fine. So for example in i3

kitty -o initial_window_width=80c -o initial_window_height=24c -o remember_window_size=n --class=floating

results in a 80x24 cells window, as expected.
