### ISSUE TITLE
Background colour glitches out when scrolling in Vim

### ISSUE THREAD

**Issue by Reiddragon** [kovidgoyal/kitty#5617]
**Describe the bug**
when scrolling text in Vim, the background of lines coming in view is glitched out, selecting lines in Visual Mode then deselecting seems to fix the specific lines that were selected

**To Reproduce**
1. set a vim colourscheme (the exact scheme and the state of `termguicolour` doesn't matter)
2. start scrolling a buffer with text in it
3. the lines coming into view from the top/bottom have the wrong background colour for any space characters

**Screenshots**
![Screenshot_20221022_145219](https://user-images.githubusercontent.com/40322297/197337712-2a92ceec-b1b1-4fa9-8ac2-792451eb5bd5.png)

**Environment details**
```
kitty 0.26.4 created by Kovid Goyal
Linux snow-raptor 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64
Arch Linux 6.0.2-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/home/reid/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_GB.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                reid
	XCURSOR_SIZE                        24
	LC_MEASUREMENT                      ro_RO.UTF-8
	LC_MONETARY                         ro_RO.UTF-8
	XDG_CONFIG_DIRS                     /home/reid/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      6
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session3
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            3
```

**Additional context**
I have not been able to reproduce this with any other program running in Kitty, or with Vim running in any other terminal, this seems to only happen with the specific Kitty + Vim combo (possibly also NeoVim but I haven't tested)

**Comment by kovidgoyal** [comment]
see the kitty FAQ

**Comment by coaxial** [comment]
For people with this issue and using tmux, you can add this to your bashrc:

`[ -z "$TMUX" ] && export TERM=xterm-kitty`

It will set `TERM` to the right value while letting tmux do its thing. Fixed this issue (not in vim, but in pretty much every other command) using tmux 3.0a and kitty 0.26.4 on Mint 20.04.
