### ISSUE TITLE
paste + previous/following input: overlapping text display

### ISSUE THREAD

**Issue by kitsunaynay** [kovidgoyal/kitty#5619]
I ran into it multiple times now, result is always a non clear text display in which you cant clearly navigate (cursor does not fit text) and text is overlapping.

**To Reproduce**
1. resize terminal so its not fullscreen/fullsize
2. paste (long?, f.e. url) command with control+shift+v into terminal and enter
3. use up/down arrow keys (for previous/following input)
=> should result in mixed commands text, also interferes with new lines if command longer than the line (writes over naynay@NayNaysBisquit ~, etc)

![image](https://user-images.githubusercontent.com/115988284/197393068-52a23f15-3448-457f-b5e4-47bb479e0b99.png)
^ cursor placement is the furthest I can go back in the command
![image](https://user-images.githubusercontent.com/115988284/197393382-017d7914-cc8b-4dd6-a845-8e3ef79ae626.png)

sometimes the cursor placement bug is fixed by going into fullscreen, although it does not reverse weird command interference/mix

**Environment details**
OS: EndeavourOS Linux x86_64 
Kernel: 6.0.2-zen1-1-zen
Packages: 924 (pacman), 4 (flatpak) 
Shell: bash 5.1.16 
WM: i3 
Terminal: kitty 

**Additional context**
kitty.conf:
```
include current-theme.conf
```

current-theme.conf from "black metal" theme

**Comment by kovidgoyal** [comment]
The terminal does not draw the prompt, the shell does. Presumably
something in your bash config is causing it. Bisect your bashrc to find
out what it is. I can tell you that it does not happen with vanilla bash
and kitty.
