### ISSUE TITLE
Kitty 0.26.4 - Opening Kitty with linux_display_server x11 in kitty.conf weird behavior in XWayland environment

### ISSUE THREAD

**Issue by D3vil0p3r** [kovidgoyal/kitty#5620]
**Describe the bug**
Hello, all this time, in Arch Linux, GNOME Wayland (with XWayland) I used Kitty by using `linux_display_server x11` in `kitty.conf` because I would like to work with a dark top bar with the "close", "maximize", "reduce to icon" buttons.

Today, I noted that, after updates of several packages, when I opened a new kitty terminal, it started to press automatically "Enter" keyboard button and the prompt shell in Kitty terminal goes down indefinitely due to the "Enter" key pressing:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/83867734/197408330-c1b970c2-acd2-4394-9eb5-8e2c5c81ca94.png">

Then, if I move the cursor of the mouse on Visual Studio Code, it continues to press "Enter" also there, until I don't stop by `CTRL+C`.

For solving this issue, I need only to set `linux_display_server` as `auto` or `wayland` but in this manner I cannot use dark top bar with the three window buttons.

Since I read it is not possible to use directly dark top bar on Wayland, it is possible to fix this issue since it worked all this time (because, I think, I'm working with XWayland)?

Thanks

**Comment by kovidgoyal** [comment]
Well downgrade whatever packages you upgraded. Since they broke xwayland
for you. I can tell you that kitty with xwayland continues to work fine
for me in arch linux GNOME, upgraded right now.

**Comment by D3vil0p3r** [comment]
> Well downgrade whatever packages you upgraded. Since they broke xwayland for you. I can tell you that kitty with xwayland continues to work fine for me in arch linux GNOME, upgraded right now.

Thanks @kovidgoyal I did a full upgrade of all the entire universe of packages they have been upgraded, so won't be easy, but I will do. I think you are not getting the issue because, by a "pacman -Syyu` the system will upgrade only packages that don't break dependencies. My case was different, because I started with a clean Arch Linux machine with all latest package versions, and there I got the issue. On my old machines where I did a full upgrade it continues to work.

So just be aware for those users create new clean Arch machines.

**Comment by page-down** [comment]
> ... started with a clean Arch Linux machine with all latest package versions ... got the issue ...

No, this will not happen in a really clean archlinux without any other packages besides the default installation (with GNOME).

> PS: I edited the post above with these evidences because not clear.

I recommend starting by not ignoring GitHub issue templates and providing reproducible steps, with minimal reproducible configuration ( including minimal shell configuration or other affected software).

> ... move the cursor of the mouse on Visual Studio Code ... continues to press "Enter" ...

Run `show_key` kitten to see that there are no "Enter" keys being sent.

```shell
kitty --config=NONE kitty +kitten show_key -m kitty
```

**Comment by kovidgoyal** [comment]
I tested with xorg-xwayland 22.1.4 and gnome 42.5 I dont think doing a clean install will get me any newer versions, those are the current versions as per the arch repositories. If you can figure out how to reproduce, I will be happy to investigate further, at the moment its looking like something is broken on this specific machine.

**Comment by D3vil0p3r** [comment]
Thank you @kovidgoyal @page-down I used a different physical machine with WMware Workstation where I set up a fresh Arch Linux. Step by step:
* I downloaded the latest ISO of Arch Linux (archlinux-2022.10.01-x86_64.iso),
* After the boot, I run `archinstall` for installing the system.
* The system has been installed with a standard configuration. In the specific I selected GNOME as Desktop Environment
* After the installation, I login on the installed Arch system. The version of GNOME is 42.4 with GNOME Wayland
* Then, `sudo pacman -Syy kitty` by gnome-terminal
* Then, always by gnome-terminal, and assuming all kitty windows are closed, I executed `kitty --config=NONE -o linux_display_server=x11 kitty +kitten show_key -m kitty` and I'm getting these input automatically:
![image](https://user-images.githubusercontent.com/83867734/197524620-2c178798-05e2-4b85-b392-51ded67eeb94.png)

Note: for reproducing this issue, you need to run `kitty` commands in a terminal different by Kitty terminal itself (here I used gnome-terminal). At the beginning, if you run kitty command, could happen that this weird behavior does not appear, so if it does not appear, close Kitty terminal and always by gnome-terminal, run again `kitty --config=NONE -o linux_display_server=x11 kitty +kitten show_key -m kitty`. For example, in my machine it started to behave in that strange way after the 3rd time I run that kitty command on gnome-terminal.

When I come back home, I can also record a video of the entire steps.

**Comment by page-down** [comment]
Thanks for the detailed steps, I don't think a video recording is needed.
What is different from the above steps is that I used the **official release**.

However I noticed the above description:
> ... after the 3rd time I run that kitty command ...

I tested again and reproduced the issue.

- Run the above command in kitty (wayland).
- Press `Ctrl+D` to exit kitty (x11).
- Run kitten again, and the `D` key appears to be held down all the time. So pressing Ctrl at this point will simply end the show_key kitten and kitty (x11) process.

**Comment by D3vil0p3r** [comment]
Sorry if I explained this issue not good at the beginning. I'm glad you are able to reproduce it. I did also these last steps you wrote, and yes, if I press `Ctrl+D` for exiting kitty (x11) I get `D` key appearing to be held down repeatedly.

If then I press `Ctrl` it will end the show_key kitten, but if before pressing `Ctrl` I press another key, like `UP` arrow, and then I press `Ctrl`, it does not exit from show_key kitten.

**Comment by kovidgoyal** [comment]
Sorry I still cant repro it steps I tried:

0) Open a kitty wayland terminal

1) Run 

kitty --config=None -o linux_display_server=x11 kitty +kitten show_key -m kitty

2) Press ctrl+d

3) the kitty started in step 1 exits, as expected

4) in the kitty wayland terminal no key is pressed down. I can type
normally as expected.

5) This is with the official kitty binaries not the arch package, as I
dont support distro specific packages, there's too much monkey patching
that distros do.

And given that this bug is under xwayland and not in plain x11 I dont see
how it could be a kitty bug. kitty contains no special code for
xwayland. It's upto xwayland to behave the same as x11.

**Comment by D3vil0p3r** [comment]
> Sorry I still cant repro it steps I tried:
> 
> 0. Open a kitty wayland terminal
> 1. Run
> 
> kitty --config=None -o linux_display_server=x11 kitty +kitten show_key -m kitty
> 
> 2. Press ctrl+d
> 3. the kitty started in step 1 exits, as expected
> 4. in the kitty wayland terminal no key is pressed down. I can type
>    normally as expected.
> 5. This is with the official kitty binaries not the arch package, as I
>    dont support distro specific packages, there's too much monkey patching
>    that distros do.
> 
> And given that this bug is under xwayland and not in plain x11 I dont see how it could be a kitty bug. kitty contains no special code for xwayland. It's upto xwayland to behave the same as x11.

Hello @kovidgoyal don't run the `kitty --config=None -o linux_display_server=x11 kitty +kitten show_key -m kitty` because the bug assumes that all the kitty terminal processes are down.

You need to call `kitty --config=None -o linux_display_server=x11 kitty +kitten show_key -m kitty` command by another terminal different from kitty, for example gnome-terminal.

The first times you run that command, it will run good. When you start to run that command after the 3rd or the 4th time (always in a different terminal than kitty, for example gnome-terminal), you will reproduce the issue.

**Comment by kovidgoyal** [comment]
Ah, OK. I can reproduce it when running from another terminal. But I
dont see what I can do about it. Add --debug-input to the command above
and you will see that kitty is actually being delivered these events
from XWayland. So it looks like a regression in XWayland. I have no clue why
XWayland has suddenly started doing this, maybe report the bug to them
perhaps they can offer some insight.

**Comment by D3vil0p3r** [comment]
> Ah, OK. I can reproduce it when running from another terminal. But I dont see what I can do about it. Add --debug-input to the command above and you will see that kitty is actually being delivered these events from XWayland. So, it looks like a regression in XWayland. I have no clue why XWayland has suddenly started doing this, maybe report the bug to them perhaps they can offer some insight.

You're right, indeed according to my last tests, if I downgrade `xorg-xwayland` to `22.1.3`, and I reboot the machine, Kitty works correctly. If I update `xorg-xwayland` to `22.1.4` (latest), and I reboot the machine, Kitty works bad with the configuration above.

The issue for Xwayland should be opened in GNOME Gitlab or Wayland Gitlab? I don't see dedicated pages.

**Comment by kovidgoyal** [comment]
I don't think this is specific to GNOME, I can reproduce it under KDE as
well.

**Comment by D3vil0p3r** [comment]
> I don't think this is specific to GNOME, I can reproduce it under KDE as
> well. 
> 

I see Kitty is not the only impacted application: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1395

I will open our ticket to xorg Gitlab project.
