### ISSUE TITLE
Slow (or noticeable) font resize when resizing a window

### ISSUE THREAD

**Issue by kormosi** [kovidgoyal/kitty#5623]
**Describe the bug**
When resizing a window in which kitty runs, there's around 0.5 seconds delay before the font "snaps" into it's correct and epxected
size. 

I don't remember this happening before.

**To Reproduce**
1. Quickly resize the kitty window (or spawn/close another window that causes kitty to resize)
3. See error

**Screenshots**

1. Two kitty windows opened side-to-side:
![image](https://user-images.githubusercontent.com/53222723/198028911-5f6c5217-12be-4ffa-9ac7-51250d882e21.png)

2. Kill the right window, i3 tries to fill the whole screen with kitty window, the font gets stretched:
![image](https://user-images.githubusercontent.com/53222723/198029501-8ad0d443-dde1-44ac-95a4-6c3586f0c732.png)

3. After around 0.5 seconds, the font "snaps" back to proper size:
![image](https://user-images.githubusercontent.com/53222723/198029604-1e053757-9150-45fe-9d4b-7e9ecfcc165e.png)

**Environment details**
```
kitty 0.26.4 created by Kovid Goyal
Linux arch 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64
Arch Linux 6.0.2-arch1-1 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/patres/code/shell:/home/patres/code/screenlayout:/home/patres/.cargo/bin:/home/patres/.local/bin:/home/patres/.pyenv/shims:/home/patres/.pyenv/bin:/home/patres/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                patres
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    tty
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Additional context**
I was able to reproduce the problem with `kitty --config NONE`.
I run kitty under archlinux, X11, with the `picom` compositor. I was able to reproduce the issue even when I disabled `picom`.
Other windows (programs) under i3 don't show this resizing problem, that's why I think this is kitty.

**Thank you very much for this awesome and reliable piece of software and thank you for your help!**

**Comment by kovidgoyal** [comment]
dup of #5601
