### ISSUE TITLE
Search across wrapped lines in scrollback

### ISSUE THREAD

**Issue by GavinFrazar** [kovidgoyal/kitty#5626]
(I wasn't sure if this was a "bug" or some kind of intentional trade-off, so I've made this a feature request.)

**Is your feature request related to a problem? Please describe.**
I frequently use the scrollback `ctrl+shift+h` to search command output in scrollback. Unfortunately, I've noticed that when an output line wraps, it fails to be found by searching with `/`. For example, suppose the scrollback looks like this:
```
$ some_cmd
long line of output....foo-bar
-baz
```
If I search `/` for "foo-bar-baz", the search fails to match because the line wrapped the -baz suffix to the next line.

**Describe the solution you'd like**
If not too much effort, allow searches across wrapped lines.

**Describe alternatives you've considered**
If this would cause some performance problem (I have no idea), then it could be a configurable option to remember wrapped lines instead of inserting newline characters? It seems like kitty is already aware of lines that have wrapped, since it is able to intelligently resize the scrollback text when I open/close new window splits.

**Additional context**
Screenshots of me searching the scrollback for "74 75":
* when the window is wide, it finds the string:
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/16846283/198170246-7d085422-b347-4ef1-8cfc-041051f5df3b.png">

* After splitting the window, the line wraps earlier, and now "74 75" is not found:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/16846283/198170316-0316dc20-ffd8-4f47-9619-7594a4a88d6b.png">

**Comment by page-down** [comment]
You need to feed the scrollback content without the line wrap to the pager.

```conf
# Do not use the `launch --stdin-add-line-wrap-markers` option

map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting less +G -R
```

https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer

The default will wrap longer lines to ensure the presentation in the pager.
You can try using other more advanced pager (which I don't know about) with `launch` or custom kitten.
Until kitty's built-in pager is implemented, I don't think there's much more that can be done.

**Comment by kovidgoyal** [comment]
The searching here is done by the pager (default less), not kitty. As @page-down said,
you can tell kitty not to pass wrap markers to the pager or use a pager
that ignores them when searching. 

If and when kitty gets its own modern replacement for less, this will of
course work out of the box.

**Comment by GavinFrazar** [comment]
Thanks!
