### ISSUE TITLE
Avoid xscreensaver?

### ISSUE THREAD

**Issue by 097115** [kovidgoyal/kitty#5627]
(I'm probably missing something very obvious, so I do apologize in advance :)

I have xscreensaver installed, and I use it. However, for one particular task run in kitty I would like to keep xscreensaver deactivated. For example, when using `mpv`, the common advice is to add to mpv's scripts directory a simple lua script like this:

    local utils = require 'mp.utils'
    mp.add_periodic_timer(30, function()
        utils.subprocess({args={"xscreensaver-command", "-deactivate"}})
    end)

Now, is it possible somehow to make one particular instance of kitty to send a similar message to xscreensaver?

I tried opening kitty like this (with MYTASK being a command like `mutt` or `mc`):

    kitty --title MYTASK  sh -c 'while sleep 60; do xscreensaver-command --deactivate; done & ; MYTASK'

...and it didn't work out.

But may be you could advise something here?

Thank you.

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. If you run sh -c 'whatever' kitty
will run it as specified. You presumably have some bug in your shell
script, just froma  cursory look at it, you are using -- instead of -
for flags to xscreensaver-command

**Comment by 097115** [comment]
@kovidgoyal 

The problem is, kitty doesn't even spawn an instance with this command (opens and immediately exits, to be precise). Probably I can't form a command this way? Sending one part of it to the background, and then running the second part?

How would you address a task when you want to open a specific instance of kitty with some script running in the background for this particular instance?

**Comment by kovidgoyal** [comment]
kitty sh -c 'whatever & read'

**Comment by 097115** [comment]
This! I said it was something very stupid, I had an extra `;` between `&` and second part of the command :)

Thanks!
