### ISSUE TITLE
Fatal build-time error due missing header file on macOS 10.15 and below

### ISSUE THREAD

**Issue by judaew** [kovidgoyal/kitty#5628]
**Describe the bug**
Kitty does not build on macOS 10.15 and below. This is due to the missing `UniformTypeIdentifiers/UniformTypeIdentifiers.h` header. This header and this feature appeared only in [macOS 11+](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype?language=objc).

This header is used in `glfw/cocoa_window.m`. As you can see on the following lines, there is a check for the version of macOS.

https://github.com/kovidgoyal/kitty/blob/3847837bd0fbed3b462c10f6041a4dc8edbb3061/glfw/cocoa_window.m#L2515-L2534

... But the header is included here anyway which did not exist in older versions of macOS. Therefore, some workaround solution is needed for this.

https://github.com/kovidgoyal/kitty/blob/3847837bd0fbed3b462c10f6041a4dc8edbb3061/glfw/cocoa_window.m#L34

**To Reproduce**
1. Try to build on macOS 10.15 or below.
2. Get fatal error: 'UniformTypeIdentifiers/UniformTypeIdentifiers.h' file not found

**Logs**

See https://trac.macports.org/ticket/66066.

[logs.txt](https://github.com/kovidgoyal/kitty/files/9879042/logs.txt)

**Comment by kovidgoyal** [comment]
dup of #5556
