### ISSUE TITLE
Actually convenient ssh

### ISSUE THREAD

**Issue by rosejn** [kovidgoyal/kitty#5634]
**Is your feature request related to a problem? Please describe.**
SSH is broken without the kitten.  More broken than in any other terminal.  A "truly convenient SSH" would work well without any extra stuff, or otherwise be sophisticated enough to do whatever it needs to do without manual intervention or script editing.  This requirement means many of us can't use the same scripts as our teammates who don't use kitty.

**Describe the solution you'd like**
Ideally Kitty could:
* have a setting which said to always use the kitten when using SSH by default via an alias or something
* work at least as well as a normal terminal otherwise

**Describe alternatives you've considered**
Change terminals

**Additional context**
I love kitty and think you've created something great, but this is the primary weakness

**Comment by kovidgoyal** [comment]
So add

alias ssh="kitty +kitten ssh"

to whatever shell rc files you use.
