### ISSUE TITLE
Ctrl+Alt+number keys don't send anything

### ISSUE THREAD

**Issue by mbunkus** [kovidgoyal/kitty#564]
I'm using e.g. Ctrl+Alt+6 in Emacs for something similar to `delete-indentation` (with `delete-indentation` on  Alt+6). kitty doesn't send anything for any of the Ctrl+Alt+<number> combinations, whereas VTE-based programs (e.g. terminator) and konsole do send various codes.

I've tested this with kitty 0.10.0 at fe65b346c1c0ffa80828a5aa390529f2a8b64a2f.

**Comment by kovidgoyal** [comment]
ctrl+alt+number (and ctrl+number) is unuseable in terminals. Use showkey -a and you will see that in VTE based terminals it generates the same bytes as Alt+number. So if you want to use it in kitty, simply press Alt+number instead, which is one less chord. Or use the send_text directive in kitty.conf to manually map them to send the same bytes as alt+number.

Or convince the emacs maintiners to exit the stone age and add support for a proper terminal keyboard protocol, as documented here: https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc

**Comment by mbunkus** [comment]
At least konsole differentiates between all three variants, and Emacs does recognize those as M-6, C-6 and C-M-6 respectively:

![deepinscreenshot_konsole_20180522122634](https://user-images.githubusercontent.com/414282/40357252-e02d28a8-5dbb-11e8-95fd-b1a44ea563a0.png)

terminator doesn't differentiate between Ctrl+6 and Ctrl+Alt+6, though. It does differentiate between Ctrl+6 and Alt+6, though, same way kitty does.

**Comment by kovidgoyal** [comment]
Try it with 1, 9 or 0 instead of 6. As I said, the only modifier you can use reliably with number keys is alt.
