### ISSUE TITLE
Mapping to discard_event doesn't work

### ISSUE THREAD

**Issue by Itay123TheKing** [kovidgoyal/kitty#5641]
My config has the following two lines:
```
map ctrl+shift+j discard_event
map ctrl+shift+k discard_event
```
but pressing either of those key combos does not get passed on to the running app.

**Comment by kovidgoyal** [comment]
That is because the traditional key encoding used by terminals does not
suppport ctrl+shift as a modifier. You need to use a program that
supports the kitty keyboard protocol.

**Comment by page-down** [comment]
If you want kitty not to use certain key combinations as action shortcuts, but to send them directly to the program, they should be mapped to the `no_op` action.

If mapped to `discard_event`, the key will be ignored completely and will not be sent to the program.

https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

**Comment by Itay123TheKing** [comment]
@page-down oh wow I misread that to mean the opposite. thank you
