### ISSUE TITLE
full width/height horizontal/vertical splits

### ISSUE THREAD

**Issue by rebelot** [kovidgoyal/kitty#5643]
Sometimes, using the `splits` layout, I need to create a tall full-height window, or a wide full-width one.

Say I am starting from this configuration:

<img width="1310" alt="Screenshot 2022-11-03 at 08 55 54" src="https://user-images.githubusercontent.com/36300441/199672934-2fcf58f2-4757-4f99-8a2a-7f5f580b85c0.png">

I did not find a way to open windows to make it look like this, ___unless I plan it from the beginning___ which is not what I want.

### full height split
<img width="1310" alt="Screenshot 2022-11-03 at 08 57 22" src="https://user-images.githubusercontent.com/36300441/199673168-3cf88c60-3a57-47d4-a162-2e94adb7a0ea.png">

### full width split
<img width="1310" alt="Screenshot 2022-11-03 at 08 56 49" src="https://user-images.githubusercontent.com/36300441/199673172-e725bef9-3795-4611-91c0-a49a879243a7.png">

thus it would be great if the `launch` command could take the `--full` option, e.g, `launch --location=hsplit --full` would create a full width horizontal window that splits the existing layout in halves.

Thanks a lot for your hard work on this!

**Comment by kovidgoyal** [comment]
I'm afraid there are an infinite number of "things I would like to do" from an infinite number of "current states". Trying to encode these as operations on launch is not feasible, at least for me. If you wish to develop a DSL for describing split layouts and how to transform them arbitrarily, then patches are most welcome.

**Comment by rebelot** [comment]
I am sorry, I thought this splitting pattern was somehow popular enough not to be considered a whim of mine. Could this be encoded as a `layout_action` instead? The basic idea is to split the os window in half, horizontally or vertically. Every existing window will be then resized by halving its height or width. All these operations seem doable, since they are already implemented by other layouts. If you give me some pointers, I could try fiddling with `splits.py`

**Comment by kovidgoyal** [comment]
Yes, a layout action is definitely do-able.

**Comment by kovidgoyal** [comment]
Relevant function is layout_action() in splits.py. You will want
something like

map f1 layout_action move_to_screen_edge left|right|top|bottom

then for your use case you can do

map f1 combine : launch : layout_action move_to_screen_edge right

**Comment by rebelot** [comment]
That's awesome thank you so much!
