### ISSUE TITLE
Mac monterey can not use zsh, stacking!

### ISSUE THREAD

**Issue by vintmd** [kovidgoyal/kitty#5644]
**Describe the bug**
Use zsh 5.8 (x86_64-apple-darwin21.0) to send file, stack after shift+ctrl+@ .

**To Reproduce**
1. zssh user@host -p 22
2. sz -bye file
3. shift+ctrl+@
4. stack

**Screenshots**
<img width="407" alt="image" src="https://user-images.githubusercontent.com/61688729/199714923-c76eada1-4f80-419e-9d01-96996cdab3c6.png">

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

kitty 0.25.2 created by Kovid Goyal
Darwin MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T
ProductName:    macOS ProductVersion:   12.2.1 BuildVersion:    21D62
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ton/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select       clipboard
enable_audio_bell    False
macos_option_as_alt  3
Colors:
        background           #282828   
        color0               #3c3836   
        color1               #cc241d   
        color10              #b8bb26   
        color11              #fabd2f   
        color12              #83a598   
        color13              #d3869b   
        color14              #8ec07c   
        color15              #fbf1c7   
        color2               #98971a   
        color3               #d79921   
        color4               #458588   
        color5               #b16286   
        color6               #689d6a   
        color7               #a89984   
        color8               #928374   
        color9               #fb4934   
        cursor               #bdae93   
        cursor_text_color    #665c54   
        foreground           #ebdbb2   
        selection_background #d65d0e   
        selection_foreground #ebdbb2   
        url_color            #458588   

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                zh_CN.UTF-8
        SHELL                               /bin/zsh
        USER                                ton

This debug output has been copied to the clipboard

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I dont know what sz or stack is. And the legacy terminal protocol does not support ctrl+shift modifiers. You need to press ctrl+Space to generate a zero byte not ctrl+shift+space.

**Comment by vintmd** [comment]
> I dont know what sz or stack is. And the legacy terminal protocol does not support ctrl+shift modifiers. You need to press ctrl+Space to generate a zero byte, not ctrl+shift+space.

sorry my poor English, stack -> stuck,  sz is the command to send the file.
I use ctrl+Space+@ can normally process, but ctrl+Space also switch input method, 
Only can bound switch input method to other keys to avoid this issue?

**Comment by vintmd** [comment]
@kovidgoyal

**Comment by kovidgoyal** [comment]
Read the kitty FAQ it will tell you how to map key presses to produce
different bytes.

**Comment by vintmd** [comment]
OK， thanks！
