### ISSUE TITLE
Problem with accents ` and ', and ^¨, and Del key

### ISSUE THREAD

**Issue by sjkl90** [kovidgoyal/kitty#5649]
**Describe the bug**
When I try to put any of these keys, they are not written in the kitty terminal but in any other program or another terminal

**To Reproduce**
My environment is a 12 th i7 Laptop, and GNOME.

**Environment details**
```
![imagen](https://user-images.githubusercontent.com/64540881/200492247-65ddfb5d-41df-478e-8eda-ae52d5fea597.png)

**Comment by kovidgoyal** [comment]
All those keys work fine for me with kitty in GNOME. If you need more
assistance, fill up all the information asked for in the issue template.

**Comment by sjkl90** [comment]
Exactly what information do you need to know about the system?
