### ISSUE TITLE
Map OS resize without remote control

### ISSUE THREAD

**Issue by psydvl** [kovidgoyal/kitty#5657]
**Is your feature request related to a problem? Please describe.**
I'd like to map OS window resize to keyboard shortcut, but now only exist `kitty @ resize-os-window` that required `allow_remote_control=yes`

**Describe the solution you'd like**
There should be option resized current OS window

**Describe alternatives you've considered**
I'd like to move and resize detached tab, so I want something like 
```
map ctrl+f2 combine : detach_tab -o initial_window_width=24c -o initial_window_height=80c : set_background_opacity 0.7
map ctrl+f2 combine : detach_tab -c floating.conf
map ctrl+f2 combine : detach_tab : resize_os_window --width 80c --height 24c --top 40 --right 15 : set_background_opacity 0.7
# or ideally
map ctrl+f2 combine : detach_tab -o "map ctrl+f2 combine : detach_tab ask : resize_os_window --fullscreen : set_background_opacity 1.0" : resize_os_window --width 80c --height 24c --top 40 --right 15 : set_background_opacity 0.7
```

**Additional context**
I'm on GNOME Wayland

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/remote-control/#mapping-key-presses-to-remote-control-commands

**Comment by psydvl** [comment]
`without remote control` in title

**Comment by kovidgoyal** [comment]
yes actually red what written in that link I posted.
