### ISSUE TITLE
`--start-as maximized` broke `remote_control resize-os-window`

### ISSUE THREAD

**Issue by psydvl** [kovidgoyal/kitty#5659]
**Describe the bug**
If kitty launched with `--start-as maximized` `resize-os-window` will not work
(actually, it works but instantly maximized back, and if you spam command, it might win one moment 😅)

**To Reproduce**
1. ```
	kitty --start-as maximized -c NONE -o "map ctrl+f2 remote_control resize-os-window --width 80"
	```
2. Press <kbd>Ctrl</kbd>+<kbd>F2</kbd>

**Environment details**
<details>
<summary>Details</summary>

```
kitty 0.26.5 created by Kovid Goyal
Linux localhost.localdomain 6.0.7-1-default #1 SMP PREEMPT_DYNAMIC Fri Nov 4 07:35:08 UTC 2022 (9068830) x86_64
Welcome to openSUSE Tumbleweed 20221108 - Kernel 6.0.7-1-default (/dev/tty).

enp0s20f0u1: 4{enp0s20f0u1} 6{enp0s20f0u1}
wlp1s0: 4{wlp1s0} 6{wlp1s0}

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config overrides:
  map ctrl+f2 combine : detach_tab : remote_control resize-os-window --width 80

Config options different from defaults:
Added shortcuts:
	ctrl+f2 →  combine : detach_tab : remote_control resize-os-window --width 80

Important environment variables seen by the kitty process:
	PATH                                /home/nixi/.cargo/bin:/home/nixi/miniconda3/condabin:/home/nixi/.local/bin:/usr/local/bin:/usr/bin:/bin:/home/nixi/go/bin:/home/nixi/.npm-packages/bin:/home/nixi/.local/share/JetBrains/Toolbox/scripts
	LANG                                en_US.UTF-8
	VISUAL                              /usr/bin/vim
	EDITOR                              /usr/bin/vi
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                nixi
	XDG_CONFIG_DIRS                     /etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	LC_MONETARY                         ru_RU.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            ru_RU.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      ru_RU.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             ru_RU.UTF-8
	XDG_DATA_DIRS                       /home/nixi/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	LC_NUMERIC                          ru_RU.UTF-8

```
</details>

**Comment by kovidgoyal** [comment]
yes, you cant resize maximized windows, since they are, maximized. You
have to un-maximize them first.

**Comment by psydvl** [comment]
But I can: just press and wait here

<details>
<summary>video</summary>

[Kooha-2022-11-10-14-08-20.webm](https://user-images.githubusercontent.com/43755002/201075981-b015da71-cdc6-4495-9342-3ed20613a591.webm)

</details>
