### ISSUE TITLE
Terminal being unknown fix on MacOS

### ISSUE THREAD

**Issue by emprovements** [kovidgoyal/kitty#566]
Hi,

I am trying to use the fix
`infocmp xterm-kitty | ssh $1 tic -x -o \~/.terminfo /dev/stdin && ssh $1`
on Mac but /dev/stdin is missing there. I tried but I cannot figure out how to modify the comamnd to get it up and running.

May I ask how to do that?
Thanks!

**Comment by kovidgoyal** [comment]
/dev/stdin is mandated by POSIX. If it si missing on your machine, something is very wrong. You can split up the command into multiple commands, something like:
```
infocmp xterm-kitty > /tmp/kitty.terminfo && ssh $1 tic -x -o \~/.terminfo /tmp/kitty.terminfo && ssh $1
```

**Comment by emprovements** [comment]
If anyone need it I got it up and running by `infocmp | ssh $1 "tic -" && ssh $1`
