### ISSUE TITLE
Calling kitty and sub commands from within VIM terminal

### ISSUE THREAD

**Issue by tricarte** [kovidgoyal/kitty#5661]
**Describe the bug**
I'm sure this is not a bug, at least for me. But what is the technical reason behind that I cannot run kitty commands such as `kitty @ launch htop` successfully from within vim terminal. It just times out.

Edit: `allow_remote_control` is enabled.

![kitty-from-within-vim-terminal](https://user-images.githubusercontent.com/3023026/201461523-761e6089-aa33-4217-8a4c-2f0279e01995.png)

Calling just `kitty` inside vim terminal creates a new OS window as expected.

This is not important at all. I just wanted to learn. I really enjoy using kitty. Keep up the good work.

**Comment by kovidgoyal** [comment]
remote control by default works by sedning commands over the terminal
device. vim terminal is its own terminal device, it's not connected to
kitty. To use remote control from there, you will need to setup socket
baed remote control, see --listen-on
