### ISSUE TITLE
This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it

### ISSUE THREAD

**Issue by newyorkthink** [kovidgoyal/kitty#5666]
![image](https://user-images.githubusercontent.com/87791643/201569812-7e194a3a-ad7c-484e-b300-d01a7244f14d.png)

icat not working

**Comment by page-down** [comment]
Please provide details based on the GitHub Issue template.
Not sure how you can get help if you don't provide a detailed description and steps to reproduce it.

In my case icat works fine.

**Comment by kovidgoyal** [comment]
You are presumably using it through some terminal multiplxer or the
other that breaks it.
