### ISSUE TITLE
draw_minimal_border affects active boders

### ISSUE THREAD

**Issue by leclairm** [kovidgoyal/kitty#5668]
When activating `draw_minimal_borer yes` in kitty.conf, all borders are "minimized" instead of only inactive ones so that the border of the active pane in only partially drawn: 
![draw_minimal_yes](https://user-images.githubusercontent.com/16205240/201630211-fa82e93b-d2e8-4771-bdcd-16b3e0596c82.png)

In order to see the full active border I need to set `draw_minimal_borer no` but then of course,  all common borders are duplicated:
 ![draw_minimal_no](https://user-images.githubusercontent.com/16205240/201629778-326acd25-2ccc-40af-be2b-6149c79d9968.png)

This behavior contradicts with the `draw_minimal_border` documentation saying _only the borders that separate the inactive window from a neighbor are drawn_.

I'm running Kitty version 0.26.4-1 under Manjaro with the gnome desktop manager and the wayland compositor.

**Comment by kovidgoyal** [comment]
the documentation does not say that, it says

"This means that only the borders that separate the inactive window from a neighbor are drawn"

The same is true for active windows. I can possibly remove the word
inactive from that sentence to make it clear.

**Comment by kovidgoyal** [comment]
No, there isnt. When drawing minimal borders there is no space allocated
for per window borders, drawing a per window border only when a window
becomes active would thus change its size.

**Comment by leclairm** [comment]
Thanks, got it. I might have a look ta the code to check if that is implementable without too much change and only python knowledge.

I think it'd be a nice feature to have. At the moment, the `active_border_color` setting is not very useful with `draw_minimal_border` activated, especially when the tab is split in 2 windows only.

Still, thanks for the great work and responsiveness in the issues!
