### ISSUE TITLE
Setting kitty clipboard as vim clipboard tool

### ISSUE THREAD

**Issue by Nohac** [kovidgoyal/kitty#5669]
**Describe the solution you'd like**
I would like to use the built in clipboard tool `kitty +kitten clipboard` with vim to enable copy/paste from ssh.

**Describe alternatives you've considered**
I've tried to set the clipboard tool in vim to kitty:
```
let g:clipboard = {
     \    'name': 'kittyclip',
     \    'copy': {
     \      '+': 'kitty +kitten clipboard --wait-for-completion',
     \      '*': 'kitty +kitten clipboard --wait-for-completion',
     \    },
     \    'paste': {
     \      '+': 'kitty +kitten clipboard --get-clipboard',
     \      '*': 'kitty +kitten clipboard --get-clipboard',
     \    },
     \    'cache_enabled': 1,
     \ }
```
If I now try to copy text from vim using `"+yy`, I get the following error:
```
clipboard: error invoking kitty: Traceback (most recent call last):   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main     retu...rd/main.py", line 126, in main     tty_fd = os.open(os.ctermid(), os.O_RDWR | os.O_CLOEXEC) OSError: [Errno 6] No such device or address: '/dev/tty' 
```
That's unfortunately all of the error I managed to get from vim.

I followed the vim manual `:h clipboard-tool`, but still not sure if I'm doing it correctly.

**Comment by kovidgoyal** [comment]
the clipboard kitten needs an actual terminal to talk to. You are
running it in a context without a terminal device (no /dev/tty).
In any case you dont need this,
just use the oscyank.vim or similar plugin. Or use neovim which has
support for osc 52 builtin.
