### ISSUE TITLE
Diff kitten incorrect display

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#567]
launched with from git it displays 
![image](https://user-images.githubusercontent.com/10168645/40388479-599432ac-5e18-11e8-875a-30ba3f70d2ca.png)
while plain `git diff` displays correct info 
![image](https://user-images.githubusercontent.com/10168645/40388509-6d77bbae-5e18-11e8-8f1b-8bd596b76963.png)

**Comment by alok** [comment]
This looks correct to me. Both show that 3 lines have been added. The diff kitten just does it github-style rather than coloring the text green.

**Comment by kovidgoyal** [comment]
I agree with @alok, looks OK to me. What's the problem? The extra blank line?

**Comment by SolitudeSF** [comment]
well, yes, i dont understand the logic there.

**Comment by kovidgoyal** [comment]
blank lines are inserted to make sure the left and right content is of the same number of lines. Exactly why it is inserted in this case, I cannot tell you without looking at the two diffed files in question.

**Comment by SolitudeSF** [comment]
it not inserting white filler line, its inserting the green one. ill see if i can reproduce.

**Comment by kovidgoyal** [comment]
If you can reproduce, attach the two files and I will take a look

**Comment by SolitudeSF** [comment]
okay, i just played myself again. its working properly. sorry for bothering.
