### ISSUE TITLE
Use standardized $TERM environment variable

### ISSUE THREAD

**Issue by Binary141** [kovidgoyal/kitty#5673]
When using kitty with an ssh jump box when I try issuing the `clear` command it pops up saying that kitty is an unknown terminal environment. The current workaround is for me to add `export TERM=xterm-256color` at the end of my ~/.zshrc file. After that is inserted then I no longer receive any issues on remote machines.

I do know that the command `kitty +kitten ssh` exists and that only works on the jump box, and doesn't translate to any other vm that I ssh to from there

**Comment by kovidgoyal** [comment]
Not to mention that using a jump host works fine with the ssh kitten. It
supports the -J flag the same way ssh does.
