### ISSUE TITLE
chinese display is incomplete

### ISSUE THREAD

**Issue by zzhaolei** [kovidgoyal/kitty#5675]
I use `Consolas` font on the `macOS 13.0.1`, but chinese display is incomplete (iTerm2 is correct)

kitty version `0.26.5`.

 - `kitty --config NONE -o "font_family Consolas" -o "font_size 18"`

![left](https://user-images.githubusercontent.com/17561793/202130323-ead80683-accd-4fa4-b608-21787943c143.png)

 - `kitty --config NONE -o "font_size 18"`

![right](https://user-images.githubusercontent.com/17561793/202130338-d949f33f-229a-4b2c-bdab-af392978f47f.png)

You can see that the top of the `致命错误` character is not displayed correctly

ps: translate to english, sorry

**Comment by kovidgoyal** [comment]
Pick a main font whose metrics are compatible the font you use for
chinese, or alternately, use modify_font to increase the cell height
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font

**Comment by page-down** [comment]
It looks like the metrics of the font is not compatible.

I have another issue that has been on my list for a long time that looks similar.
When SGR style is applied, some Unicode characters are cropped instead of scaled.

```shell
kitty --config=NONE -o font_size=20 --hold --debug-font-fallback bash -c 'echo -e "sgr-①\\e[1m②③\\e[0m-test"'
```

@kovidgoyal Is there a feasible solution for this?

**Comment by kovidgoyal** [comment]
cropping happens when the overflow is "small". scaling happens when it is larger. I dont know what you mean by a solution. Do you mean you want to always scale? Note that scaling can lead to characters not properly aligned on the baseline which looks much worse for most characters.

**Comment by page-down** [comment]
> cropping happens when the overflow is "small" ...

![](https://user-images.githubusercontent.com/57713011/202148484-ecbedce1-6fc1-44ec-a71c-4af00c89ac6b.png)

So 2 and 3, after applying bold, the overflow is not large enough compared to 1, so they are cropped.

> ... I dont know what you mean by a solution. ...

This seems odd, I was just wondering if there was a better way to improve the character rendering to be more visually uniform, either by consistent cropping or scaling.

**Comment by kovidgoyal** [comment]
Your issue is basically a font choice issue. Whatever bold face corefonts is picking for 2 and 3 has very different glyphs than the non-bold one. You might consider using symbol_map to force a single font for these. Here is how it looks on my system, where both the plain and bold symbols come from the Consolas family (use --debug-font-fallback).

![screenshot](https://user-images.githubusercontent.com/1308621/202152269-c05ac759-c48d-44ab-ad2d-e3b6c40a3648.png)
