### ISSUE TITLE
kitty doesn't honor overrides in /etc/fonts/conf.d

### ISSUE THREAD

**Issue by Tyilo** [kovidgoyal/kitty#568]
I have installed nerd fonts symbols using the AUR package [`ttf-nerd-fonts-symbols`](https://aur.archlinux.org/packages/ttf-nerd-fonts-symbols/)`.

It places the file [`10-nerd-font-symbols.conf`](https://raw.githubusercontent.com/ryanoasis/nerd-fonts/2.0.0/10-nerd-font-symbols.conf) in `/etc/fonts/conf.d`, which should override (almost) all monospace fonts to prefer using the symbols from nerd fonts instead of their own symbols.

This works fine in my current default terminal emulator (termite), but kitty seems to ignore this.

Am I doing something wrong?

**Comment by kovidgoyal** [comment]
kitty uses fontconfig to resolve font names. In any case, you should not use patched fonts, they are often buggy. Instead use a normal font and add a symbol_map directive to kitty.conf to use symbols from a different font (see the default kitty.conf for examples).
