### ISSUE TITLE
set GLFW_IM_MODULE=ibus not working

### ISSUE THREAD

**Issue by newyorkthink** [kovidgoyal/kitty#5683]
this is long question.

https://github.com/kovidgoyal/kitty/issues/5549

![image](https://user-images.githubusercontent.com/87791643/202371331-bbdddf5e-444c-4baf-b7c5-2e15a86d7719.png)

I try use set GLFW_IM_MODULE=ibus ,
not work,

kitty cannot input other langugages

can you detail how to set fcitix5 in kitty

**Comment by kovidgoyal** [comment]
It works fine. As for fcitx5 I have no idea, I dont use it.
