### ISSUE TITLE
Allow defining split size for splits layout

### ISSUE THREAD

**Issue by hermitmaster** [kovidgoyal/kitty#5687]
**Is your feature request related to a problem? Please describe.**
I would like to be able to map a keybinding that creates an hsplit that uses a percentage of the available height.

**Describe the solution you'd like**
Override the `resize_window` command that takes a percentage or float in place of taller, shorter, etc.

**Describe alternatives you've considered**
Currently I'm doing this: `map ctrl+/ combine : launch --cwd=current --location=hsplit : resize_window shorter 10`. It works, but it's not really ideal.

**Additional context**
This is basically replicating a similar capability from tmux. See: `bind z split-window -l 25% -v -c "#{pane_current_path}"`

I'd be happy to create a PR for this, but I'm not proficient in Python. If directed to the relevant code, I could probably sort it out.

**Comment by kovidgoyal** [comment]
You cant really resize a split as a percentage of screen width. Splits are a
tree, and given split could be a top level one or inside another split,
which in turn could be inside another split and so on.

Resizing as a percentage of window size would work only for top level
splits. You can define resize as a percentage of parent split size. 

But note that adding support for percentages to resize_window means you
then have to implement that support in all the layouts not just splits.
This is too much work at least for me, patches welcome. The relevant
code is all in the layout/ sub-directory and the resize_window function
in tabs.py
