### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by koterpillar** [kovidgoyal/kitty#57]
When presenting, for example, it is desirable to quickly control the terminal font size without changing the global settings. Zoom is supported in Gnome Terminal, Konsole, Terminator and Termite, all with bindings of `Ctrl-Shift-{+,-,0}`, would be nice to have the same in Kitty.

**Comment by johnnyutahh** [comment]
Does Kitty still offer no keyboard binding (hotkeys, etc) for real-time font zooming?

I'm running 0.16.0 on macOS 10.14.6 and can not find any such feature.

**Comment by johnnyutahh** [comment]
Apologies, just found it: <ctrl-shift-+>. Works well, thanks. Closing.
