### ISSUE TITLE
set_tab_title with empty default

### ISSUE THREAD

**Issue by raffaem** [kovidgoyal/kitty#5703]
**Is your feature request related to a problem? Please describe.**
The default tab title is the full path where I'm in. Since I use tab quite a lot, I frequently need to rename them. To do so I call `set_tab_title` in the "interactive usage" mode, but it starts with the title the tab currently has, and I have to delete all of it.

**Describe the solution you'd like**
Have an interactive mode for `set_tab_title` that starts with an empty string

**Describe alternatives you've considered**
Well, to have vim keybindings on it but I don't know how :D

**Comment by kovidgoyal** [comment]
Press ctrl+u to clear the text. (this is the standard readline binding
unless you have modified ~/.inputrc)

**Comment by raffaem** [comment]
Thanks! That works!

**Comment by indutny** [comment]
@kovidgoyal sorry to revive the issue, but `set_tab_title` used to always start with empty prompt and if I'm being entirely honest I got so used to it that adding an extra keystroke in the middle of the process is mildly frustrating. Do you think you could add an option to make it start with an empty string again?

**Comment by ad-chaos** [comment]
There already is such an option, pass a string with a space in it `" "`
https://sw.kovidgoyal.net/kitty/actions/#action-set_tab_title

so you can do,
`map shift+cmd+i set_tab_title " "` if you are on macos or
`map ctrl+shift+alt+t set_tab_title " "` everywhere else to change the default behaviour

**Comment by indutny** [comment]
Ah, that definitely works. Thank you!
