### ISSUE TITLE
Weird line height while using Fira Code

### ISSUE THREAD

**Issue by boltlessengineer** [kovidgoyal/kitty#5704]
**Describe the bug**
Some additional height is added when using the font `Fira Code`

**To Reproduce**
Open kitty with minimal config below, and compare with other editors

```conf
font_family      Fira Code
font_size 16.0
```

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/60088301/203837601-bd6e680d-1c78-4e4c-88eb-9ea9f2d4a230.png">

Left is kitty with this config, and right side is in iTerm2

iTerm2 is using `Fira Code Light` font in 16pt, lineheight 100%

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin MacBook-Pro-3.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
ProductName:            macOS ProductVersion:           13.0.1 BuildVersion:            22A400
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/boltless/.config/kitty/kitty.conf

Config options different from defaults:
font_family Fira Code
font_size   16.0

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                ko_KR.UTF-8
        SHELL                               /opt/homebrew/bin/fish
        USER                                boltless

This debug output has been copied to the clipboard
```

**Comment by kovidgoyal** [comment]
The line height comes from whatever the font reports its line height
should be. I'm afraid matching iTerm's rendering is not a goal for
kitty. You can adjust the line height in kitty.conf using modify_font
but note that shrinking line heights can lead to rendering glitches with
some glyphs.
