### ISSUE TITLE
Certain Startup Sequences Do Not Work in MacOS

### ISSUE THREAD

**Issue by surmeier** [kovidgoyal/kitty#5706]
**Describe the bug**
When using a `startup.conf` file, certain commands on MacOS do not work properly. It seems to be dependent on the program and whether or not kitty was opened via shell or launching the app normally. 

**To Reproduce**

The following startup code works fine: 
```
cd ~/Example
launch --title "Shell" fish
launch --title "Vim" vim
```
The following does not, at least when opening the app directly:
```
cd ~/Example
launch --title "Shell" fish
launch --title "Tasks" taskwarrior-tui
```

At least on my machine, the right window where `taskwarrior-tui` should be does not open. When running the `kitty` command a new window is opened with the right behavior.

**Comment by kovidgoyal** [comment]
Use absolute paths. Or fix the *systemwide* PATH variable which is what
kitty sees not whatever PATH is set in your shell rc files.

**Comment by page-down** [comment]
> ... certain commands on MacOS do not work ...

For convenience you may want to configure `exe_search_path`.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

> Or fix the systemwide PATH variable ...

I believe that the PATH from launchd is almost impossible to "fix" due to various security restrictions.

> ... at least when opening the app directly ...

https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

**Comment by surmeier** [comment]
Using absolute paths and launching kitty from the system launcher still does not produce the right behavior. Certain TUI applications work and some don't; as in the example I gave 'launch /opt/local/bin/taskwarrior-tui` does not work.  I appreciate the sources, but have set `exe_search_path` already.

**Comment by kovidgoyal** [comment]
then taskwarrior-tui depends on some other env var which you will need
to set system wide.

**Comment by page-down** [comment]
> ... some other env var which you will need to set system wide.

Or via the `env` configuration option or `launch --env`, which is more practical under macOS.

https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-env
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.env

**Comment by surmeier** [comment]
Thanks. It seems that this is an issue with a couple of programs I run. 

Is there a way of debugging a kitty instance launched directly? I also want to look at the stderr of certain programs that fail on startup. I usually debug issues by running kitty in another kitty instance, but this issue isn't effecting nested kitty instances.

**Comment by kovidgoyal** [comment]
stderr for kitty launched via launch services goes to console.app
Though you can just do

env -i kitty

from another terminal to reproduce.

**Comment by page-down** [comment]
> env -i kitty

That will be missing some environment variables, the following command will get the values from the current env, basically the same as launching from launchd.

```shell
env -iS 'USER="${USER}" LOGNAME="${LOGNAME}" HOME="${HOME}" SHELL="${SHELL}" TMPDIR="${TMPDIR}" SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' /Applications/kitty.app/Contents/MacOS/kitty -o 'map f1 show_kitty_env_vars'
```
