### ISSUE TITLE
Option to set line height by absolute value

### ISSUE THREAD

**Issue by boltlessengineer** [kovidgoyal/kitty#5707]
**Is your feature request related to a problem? Please describe.**
Based on #5704. I want to set my font's height to 100% (relative to font size).

**Describe the solution you'd like**
It would be really nice for kitty to have an option to set line height by absolute value.

This can be implemented by adding an additional option for absolute line height or adding `+` sign to `modify_font cell_height` when adjusting the value relatively to distinguish relative and absolute values.

**Describe alternatives you've considered**
I can adjust the line height of font using `modify_font cell_height`, but it only allows me changing line height _relatively_ to font's original line height. When I set `modify_font cell_height 100%`, it changes nothing and when I set `modify_font cell_height 16`, it _adds_ 16pt to original value.

I couldn't find an option to **set** the line height of font in kitty.

**Additional context**

Even I could find a right value to adjust the lineheight and baseline to 100% (relative to font size), I still think this feature is necessary to kitty. With only `modify_font cell_height` option, I have to adjust the value every time when I change the font.

**Comment by kovidgoyal** [comment]
I dont see the point. The correct line height depends on the font, aka
the original line height.

**Comment by boltlessengineer** [comment]
I mean, I want to set line height with absolute value, not decrease/increase it's original value.

For example, I want to set line height exact `16pt`, not increase original line height `+ 16pt`.

`modify_font cell_height` option has a limitation because as you said, _"The correct line height depends on the font"_, I have to know the _original line height_ and calculate the to set line height to `16pt` regardless the font I'm using.

**Comment by kovidgoyal** [comment]
I am saying there is no value I can see to setting the line height to an exact
number. There is no way to arrive at an absolute number for line height
for a given font unless you are trying to mimic some other program,
which is, as I said, not a goal for kitty.
