### ISSUE TITLE
--single-instance on MacOS seems to ignore alt key

### ISSUE THREAD

**Issue by alok** [kovidgoyal/kitty#571]
# Steps to reproduce

1. Open kitty (running version 0.10.0)
2. Run `kitty -1`
3. Type something like alt-t

Unicode shows up, against what `macos_option_as_alt yes` should do.

**Comment by alok** [comment]
None of my kitty config has that option set to `no`. It's explicitly set to `yes` in my kitty config.

It's odd because the original instance (and I made sure it was the only running instance with `ps aux`) respects alt, and so do new instances opened with `kitty`. But if I open a new window with `kitty -1`, the new window's option key is not treated as alt.

**Comment by kovidgoyal** [comment]
Oh you mean in subsequent windows, that was not clear from your original description. Does it happen if you open new windows using, ctrl+shift+n?

**Comment by alok** [comment]
`new_window` -> works as expected
`new_os_window` -> doesn't work

the `with_cwd` variants show the same behavior.

**Comment by alok** [comment]
Fastest hand in the west with the bugfixes you are. Fixed it before I could even finish typing my reply.

Now I just have to wait for the new minor release to use this.

**Comment by alok** [comment]
[Thanks.](https://github.com/kovidgoyal/kitty/releases/tag/v0.10.1)
