### ISSUE TITLE
so i got a glfw error and it is not fixed

### ISSUE THREAD

**Issue by val-byte** [kovidgoyal/kitty#5710]
**Describe the bug**
the display environment variable is missing glfw initialization failed

**To Reproduce**
1. unknown

**Additional context**
dont know

**Comment by kovidgoyal** [comment]
You need a working X11 environment in which to run kitty. Create one and
you wont have this problem.

**Comment by val-byte** [comment]
> You need a working X11 environment in which to run kitty. Create one and you wont have this problem.

well i have X11-common but it doesnt work

**Comment by kovidgoyal** [comment]
Having X11 common is meaningless. You need to run an actual xx server
and run kitty from inside it. I suggest you spend some time
familiarising yourself with how graphics work in Linux.

**Comment by val-byte** [comment]
kitty is hard to understand i'll just use rxvt-unicode

**Comment by meowzzie** [comment]
**ik this is closed but**
1. define display environment variable
DISPLAY=:0
export DISPLAY
2. start x server 
startx
3. right click > select kitty
4. if 3 fails change to another tty shell and run kitty
5. change back to tty1 (where x is running)
6. kitty achieved
