### ISSUE TITLE
Re: Japanese input bug?（#3330）

### ISSUE THREAD

**Issue by ghsable** [kovidgoyal/kitty#5716]
- https://github.com/kovidgoyal/kitty/issues/3330
  - https://github.com/kovidgoyal/kitty/issues/3330#issuecomment-1273590741
  - https://github.com/kovidgoyal/kitty/issues/3330#issue-812568792
    - `vim` -> NG, `nano` -> OK

**Comment by astralhpi** [comment]
PR #5886 seems to be able to solve it. Can you check if it reproduces in the code in my repo? https://github.com/astralhpi/kitty

**Comment by page-down** [comment]
The current nightly release now contains IME related fixes and is available to try.

https://github.com/kovidgoyal/kitty/releases/tag/nightly

@ompugao

I see that you reported the problem in original issue 3330,
and it would be helpful if you could try to see if this issue can still be reproduced.
Thanks.

**Comment by ompugao** [comment]
The problem I commented before has been fixed!
Thank you for your contribution!
