### ISSUE TITLE
Kannada (All Indic) fonts with ligatures get garbled for certain characters

### ISSUE THREAD

**Issue by vwulf** [kovidgoyal/kitty#5717]
**Describe the bug**
I understand that terminal emulators have issues with unicode standards, particularly Indic scripts with ligatures. I tried Kitty and found it to be much better than xterm for running vim, when editing/rendering Kannada text. Certain characters are downsized - That's perfectly ok to me and a great solution compared to other terminal emulators that try to render it like a monospace font and make it unreadable.
However Kannada characters get messed up when done on a shell or within vim.

https://www.cl.cam.ac.uk/~mgk25/unicode.html seemed to indicate that it's infeasible but Kitty's rendering was surprisingly good - barring the issues listed below.

ಕ works
ಕಾ doesn't work - ಕ + ್ + ಾ
ಕಿ doesn't works - ಕ + ್ + ಿ
ಕೀ doesn't work - ಕ + ್ + ೀ
ಕು doesn't work - ಕ + ್ + ು
ಕೂ doesn't work - ಕ + ್ + ೂ
ಕೃ doesn't work - ಕ + ್ + ೃ
ಕೆ doesn't work - ಕ + ್ + ೆ
ಕೇ doesn't work - ಕ + ್ + ೇ
ಕೈ doesn't work - ಕ + ್ + ೈ
ಕೊ doesn't work - ಕ + ್ + ೊ
ಕೋ doesn't work - ಕ + ್ + ೋ
ಕೌ doesn't work - ಕ + ್ + ೌ
ಕಂ doesn't work - ಕ + ್ + ಂ
ಕಃ doesn't work - ಕ + ್ + ಃ

Essential consonants:
 ಕಗ
 ಚಜ
 ಟಡಣ
 ತದನ
 ಪಬಮ
 ಯರಲವಶಸಹಳ
 
Essential vowels 
ಅ
ಆ  ಾ
ಇ  ಿ
ಈ  ೀ
ಉ  ು
ಊ  ೂ
ಎ  ೆ
ಏ  ೇ
ಒ  ೊ
ಓ  ೋ
 ಂ

Compound characters don't work:
Formed by ಕ + ್ + Essential Consonants listed above
 ಕ್ಕಕ್ಗ
 ಕ್ಚಕ್ಜ
 ಕ್ಟಕ್ಡಕ್ಣ
 ಕ್ತಕ್ದಕ್ನ
 ಕ್ಪಕ್ಬಕ್ಮ
 ಕ್ಯಕ್ರಕ್ಲಕ್ವಕ್ಸಕ್ಶಕ್ಹಕ್ಳ

Same pattern applies for the remaining consonants.

**To Reproduce**
nix-shell -p kitty
kitty
// Type in the character set listed above

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
kitty 0.26.2 created by Kovid Goyal
Darwin Smritis-MacBook-Air.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 x86_64
ProductName:	macOS ProductVersion:	11.4 BuildVersion:	20F71
Frozen: False
Paths:
  kitty: /nix/store/g9slljbminf4cpz6x60kki3fz9vkbz9v-kitty-0.26.2/Applications/kitty.app/Contents/MacOS/kitty
  base dir: /nix/store/g9slljbminf4cpz6x60kki3fz9vkbz9v-kitty-0.26.2/Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /nix/store/g9slljbminf4cpz6x60kki3fz9vkbz9v-kitty-0.26.2/Applications/kitty.app/Contents/Resources/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /nix/store/g9slljbminf4cpz6x60kki3fz9vkbz9v-kitty-0.26.2/Applications/kitty.app/Contents/MacOS:/nix/store/g9slljbminf4cpz6x60kki3fz9vkbz9v-kitty-0.26.2/bin:/nix/store/cr25w1c2h4hn42vz5cy9nrzifb5g4msf-imagemagick-7.1.0-52/bin:/nix/store/sqlajwphxm8r7zj2i4mpl1h79bv4bamw-ncurses-6.3-p20220507-dev/bin:/nix/store/zglrmq6r0h2baq0rbvbha60lsm3n27gr-bash-interactive-5.1-p16/bin:/nix/store/xazz27ylsw2304sifcn3d8y2n9vjjy0w-clang-wrapper-11.1.0/bin:/nix/store/c17nslfb851lqfklscmbc29vaw96154q-clang-11.1.0/bin:/nix/store/6kdjfbqcrqxgs06823q78r4v834qh7nl-coreutils-9.1/bin:/nix/store/d7h6bd8j9xqdzgk215jzsbkvx3y30ajl-cctools-binutils-darwin-wrapper-973.0.1/bin:/nix/store/4sf9v2xkn1b2yqwh8hdr3wzvwdl0f94d-cctools-binutils-darwin-973.0.1/bin:/nix/store/2a9csjasn3m2ykck5r7sfynxsgmicbh7-python3-3.10.8/bin:/nix/store/vxflqjbdaw7vwqmnkrxb453i4k1qh5sh-neovim-0.8.1/bin:/nix/store/qh6spgaiah1vz1zh9rxaw374pwvrxxv3-nodejs-18.12.1/bin:/nix/store/6qvhn39r6i3z0vsh6il9ihwyxnyrc17g-screen-4.9.0/bin:/nix/store/6kdjfbqcrqxgs06823q78r4v834qh7nl-coreutils-9.1/bin:/nix/store/jsrnj5c772181hsb21am5bnl2vbbhw2f-findutils-4.9.0/bin:/nix/store/41qzi27van5yj879r8r23rrcaqax9hml-diffutils-3.8/bin:/nix/store/9lcy37azxn5nb4ql0kvkh1j8ni4jcayg-gnused-4.8/bin:/nix/store/9zk09gvqp87xdp6c28q2gkdwjg6ksw9s-gnugrep-3.7/bin:/nix/store/blx623gv59i6j87vk65s2wgr5sj29ril-gawk-5.1.1/bin:/nix/store/vrlj4r4lizw8gz7q99bz4h96q2piaay4-gnutar-1.34/bin:/nix/store/4bhr3bjn5qzs33xvjw13nfqbp1cfm66s-gzip-1.12/bin:/nix/store/lw2d7xypxyj10sx7w10bn1qf7k9kbl5z-bzip2-1.0.8-bin/bin:/nix/store/xxh3fmjl7780jf5fpn4v30yiyf8fg16d-gnumake-4.3/bin:/nix/store/1bsjl5incfnszv7scdh4d02sh45vw2w1-bash-5.1-p16/bin:/nix/store/h33ssdq7xwww13dfqj1rfrpkmvxrn4p0-patch-2.7.6/bin:/nix/store/098l3nnsxxl6l2b82148ch0p8xhzj5vv-xz-5.2.7-bin/bin:/nix/store/pkfwxrm8b1c9naff75igd5kk12cfy10l-file-5.43/bin:/Users/vishwas/.nix-profile/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /nix/store/zglrmq6r0h2baq0rbvbha60lsm3n27gr-bash-interactive-5.1-p16/bin/bash
	USER                                username
	XDG_DATA_DIRS                       


On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by vwulf** [comment]
The question really is : Is there a way to get small characters instead of truncated characters for the character combinations mentioned?

Some special symbols are rendered small/truncated in kitty?

The number of cells a Unicode character takes up are controlled by the Unicode standard. All characters are rendered in a single cell unless the Unicode standard says they should be rendered in two cells. When a symbol does not fit, it will either be rescaled to be smaller or truncated (depending on how much extra space it needs). This is often different from other terminals which just let the character overflow into neighboring cells, which is fine if the neighboring cell is empty, but looks terrible if it is not.

Some programs, like Powerline, vim with fancy gutter symbols/status-bar, etc. use Unicode characters from the private use area to represent symbols. Often these symbols are wide and should be rendered in two cells. However, since private use area symbols all have their width set to one in the Unicode standard, kitty renders them either smaller or truncated. The exception is if these characters are followed by a space or empty cell in which case kitty makes use of the extra cell to render them in two cells. This behavior can be turned off for specific symbols using [narrow_symbols](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.narrow_symbols).

**Comment by kovidgoyal** [comment]
Adjust the cell width using the modify_font directive in kitty.conf to make it a bit wider and truncated will not be truncated at the cost of extra space. There is no way to force particular characters to be truncated/scaled, its determined purely algoruthmically based on what fraction of the glyph bleeds out of the cell.
