### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by degva** [kovidgoyal/kitty#572]
Hi all, today I've found that kitty is using >75% of CPU while not doing much.

![screenshot from 2018-05-24 09-17-15](https://user-images.githubusercontent.com/2955578/40491347-6e1cb444-5f33-11e8-877e-76e8193672db.png)

I thought that it probably was because it was CPU rendering, but even when I enable GPU rendering (with `DRI_PRIME=1`) I still get the same result (the image is with GPU rendering)

Also, I've tried `kitty --config NONE` and I've got the same result.
Not sure where to look at this point.

Thanks!

**Comment by kovidgoyal** [comment]
The only way I know of for kitty to use that much CPU is either:

1) You are using CPU rendering
2) Your X server is generating lots of spurious events (#426)

For (1) I cant help you as I'm not familiar with your system. For (2) you can check using xev to see what events are being set by the server.

I can tell you that even on a 4 year old laptop with integrated intel graphics kitty uses less than 2% CPU to render htop, so it is definitely somethig specific to your system.
