### ISSUE TITLE
Fallback font not working as expected on Linux, works on macOS

### ISSUE THREAD

**Issue by sseneca** [kovidgoyal/kitty#5722]
**Describe the bug**
If I understand correctly, Kitty will fallback to another font when it needs to. I have kitty set up to use Fira Code, and I want it to fallback to use `Symbols Nerd Font` for other icons. This works fine on macOS but on Arch Linux I see the screenshot attached below.

**To Reproduce**
1. Install Symbols Nerd Font (`sudo pacman -S ttf-nerd-fonts-symbols-1000-em ` on arch, `brew install --cask font-symbols-only-nerd-font` on macOS)
2. `font_family      Fira Code` in kitty conf
3. Open e.g. neovim configured to use nerd fonts/codicons
4. See below screenshot on Linux, renders correctly on macOS (I can include this screenshot if you want)

**Screenshots**
![2022-11-29T22:17:59,195869428+00:00](https://user-images.githubusercontent.com/25619071/204660649-e0cad87b-f00e-432a-9cc0-2646569bf057.png)

**Environment details**

Linux: https://gist.github.com/sseneca/e862023216f69a7d09af658d9a61bf99

**Additional context**

The problem is worse with `kitty --config NONE` (on Linux at least), more fonts things are broken I assume because Fira Code is being set.

**Comment by kovidgoyal** [comment]
If you want to use a nerd font, the best way is to set it using
symbol_map in kitty.conf. See the kitty FAQ. Otherwise you need to
configure fontconfig to fallback to it correctly.

**Comment by kovidgoyal** [comment]
As I said, it's in the FAQ, here's a link to it 
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by kovidgoyal** [comment]
On Wed, Nov 30, 2022 at 10:02:16AM -0800, sseneca wrote:
> This doesn't address why Kitty isn't falling back to the correct font. Doing `kitty +list-fonts` shows it can find the font (`Symbols Nerd Font`) just fine.

kitty doesnt do fallback, fontconfig does.

> 
> > kitty should pick up symbols from it automatically and you can tell it to do so explicitly in case it doesn’t with the symbol_map directive
> 
> This workaround does work, but why do I have to do that extra step in Linux when it works as expected in macOS?

Because you have not configured fontconfig properly.
