### ISSUE TITLE
<type>66</ty when using delete key in ssh in Kitty

### ISSUE THREAD

**Issue by ramanshsharma2806** [kovidgoyal/kitty#5723]
Hello. Recently, I have been using ssh to log into a remote computer from Kitty. When I use the delete key (or other special keys on my mac), I get the following character printed instead of the desired effect of the key:

```<type>66</ty```

After this, I have to wait until it disconnects me from the compute node back to a login node. Does anyone know in general how to fix this problem?

**Comment by ramanshsharma2806** [comment]
The full error I get is
``<type>66</tyerror: error running IJS server: "could not get remote execution state"``
which appears after a few seconds from the first error.

**Comment by kovidgoyal** [comment]
See the kitty FAQ https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by ramanshsharma2806** [comment]
Thank you. The ``kitty +kitten ssh myserver`` command fixed it. 

To make an alias, this goes into my ``.bashrc`` or ``.zshrc`` file, right?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/24642071/205005251-943c514b-b293-4adc-bec3-15b36e5e8574.png">

**Comment by ramanshsharma2806** [comment]
Never mind, figured it out :)
