### ISSUE TITLE
ctrl+u and ctrl+k being sent without ctrl

### ISSUE THREAD

**Issue by mskar** [kovidgoyal/kitty#5730]
**Describe the bug**
Kitty sends ctrl+k and ctrl+u without the modifier.

**To Reproduce**
1. open a document with vim
2. press ctrl+u
Vim will undo the previous change (if it exists otherwise it shows a message: `Already at oldest change`) instead of going up one page.
**Screenshots**
<img width="639" alt="image" src="https://user-images.githubusercontent.com/13444106/205363573-d8494284-eaff-4887-8abe-5581e97ee004.png">

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
<img width="244" alt="image" src="https://user-images.githubusercontent.com/13444106/205363699-c504f298-25b7-4788-875f-3423075a1261.png">

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by mskar** [comment]
I see the same issue in Alacritty, but not iTerm2, Tabby, or Hyper.

**Comment by kovidgoyal** [comment]
This is a bug in vim. Update it.

**Comment by mskar** [comment]
The same thing happens outside of vim. If I figure out why everything works in iTerm2, Tabby, and  Hyper, but not kitty or alacritty, I'll post here.

**Comment by kovidgoyal** [comment]
there you go: https://github.com/vim/vim/issues/11638

**Comment by mskar** [comment]
Thank you! The problem in my case was my custom keyboard layout. When I switch back to the default keyboard layout, the problem goes away. Switching back to the custom keyboard layout recreates the problem.
