### ISSUE TITLE
Autostart: Kitty CLI argument to open/execute a program

### ISSUE THREAD

**Issue by cookiengineer** [kovidgoyal/kitty#5732]
This is a feature request.

Other terminal emulators usually have a CLI argument that allows executing a specific program/argument combination in the shell, in a specific folder.

```bash
gnome-terminal --working-directory=/home/cookiengineer/Software -- bash -c "sleep 3s; vim";
```

This feature allows to spawn a terminal, and different folder/program combinations on specific screens on computer startup (in the sense of autostart).

It would be nice to have such a feature for kitty, so that it also can be used for scripted autostart situations.
I know that kitty can be spawned in a specific working directory via the `-d` argument, but the help and a quick search in this repository didn't lead to a parameter that would allow to start a program.

Is there a possibility to do this with kitty as a terminal emulator, too?

The easiest way to do this would be a `-c command` flag that would simply just try to execute the binary path directly, and not via `bash -c "..."` or other complicated-to-parse arguments. In that case users could just write little wrapper scripts to have the same functionality.

```bash
kitty -d /home/cookiengineer/Software -c vim;
```

**Comment by kovidgoyal** [comment]
kitty -d whatever sh -c "whatever"

**Comment by cookiengineer** [comment]
Oof, I didn't see that in the man page. Thank you and sorry <3
