### ISSUE TITLE
a keymapping issue and some suggest.

### ISSUE THREAD

**Issue by TinyProbe** [kovidgoyal/kitty#5735]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I wanna using cmd+t to new_tab_with_cwd.

So i mapping:
map cmd+t new_tab_with_cwd

but doesn't work to my wanna be. (in macbook air m2)
but allocated another key, it does work.

and suggest is ... unmap key func!
if I don't want default key mapping.
I want remove that key mapping.
but it's not exist in my opinion.

thank you always.

**Comment by kovidgoyal** [comment]
Works fine on my macbook. And there is already a way to unmap keys, read
the documentation.

**Comment by TinyProbe** [comment]
i found the reason why doesn't work that. cause cmd + t was already binding by zsh built-in shortcuts. so i unmapped zsh shortcut about that cmd + t(new tab). now that does work that i mapped key.
