### ISSUE TITLE
Kitty creates new tmux session instead of attaching existing session

### ISSUE THREAD

**Issue by mskar** [kovidgoyal/kitty#5736]
**Describe the bug**
Kitty creates a new tmux session instead of attaching an existing session

**To Reproduce**
1. install tmux
2. edit `kitty.conf` to set kitty shell to attach or create tmux session
`shell /usr/bin/zsh -lc tmux attach || tmux new`
3. start kitty at least twice (a new session is created each time)

I also tried kitty sessions but experienced the same problem.

**Environment details**

<img width="244" alt="image" src="https://user-images.githubusercontent.com/13444106/205363699-c504f298-25b7-4788-875f-3423075a1261.png">

**Comment by mskar** [comment]
I ran `kitty tmux attach` and it worked the way I wanted.

**Comment by mskar** [comment]
I added `kitty tmux attach` to a shell script and set that as the shell, but kitty again creates a new session instead of attaching an existing one...

**Comment by page-down** [comment]
Do not set it as a shell, but use the startup session feature.

https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-session
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.startup_session

> I added `kitty tmux attach` to a shell script ...

Running `kitty <exec>` will start a GUI program (kitty), and you do not want to set the shell as a GUI program.
I think what you need now is to write a script that will correctly attach or create a tmux session, and then open it as the first window when kitty starts, or set it on a shortcut key.
A simple search will show that there are ready-made script examples on the Internet for guidance.
