### ISSUE TITLE
Sending unwanted input to vim?

### ISSUE THREAD

**Issue by gerritzen** [kovidgoyal/kitty#5739]
**Describe the bug**
Whenever I press enter or escape, vim interprets this as `u` and undoes whatever I did.

**To Reproduce**
1. open kitty
2. run `vim`
3. Enter insert mode with `i`, type something and press escape or enter
4. The previously typed characters vanish
5. Press escape again, `Already at oldest change` appears at the bottom of the screen
6. Type `:q` to quit vim, it won't work

**Screenshots**

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Linux hostname 6.0.9-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 16 17:36:22 UTC 2022 x86_64
S
Kernel 6.0.9-300.fc37.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                user
	XDG_DATA_DIRS                       /home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland

```

**Additional context**
Starting kitty with `kitty --config NONE` and vim with `vim -u NONE`, I get a slightly different behaviour. I can enter the line, but repeated presses of escape or enter make the line vanish and reappear. There is a message at the bottom alternating between `1 more line; after #1  2 seconds ago` and `1 line less; before #1  3 seconds ago` (the number of seconds increases as expected).

**Comment by kovidgoyal** [comment]
Update vim.

**Comment by gerritzen** [comment]
It works in gnome-terminal, alacritty, terminator and xterm. Don't you think, this could be a kitty problem? I'm using vim 9.0.963, the latest available in the Fedora repos. To what version am I supposed to upgrade to make vim work with that one terminal emulator that behaves differently?

**Comment by kovidgoyal** [comment]
Sigh. The version of vim after the bug in vim was fixed. Since you apparently have the time to test it in ten emulators but not actually follow the advice given to you by somebody that knows what they are talking about, let me search the vim issue tracker for you: https://github.com/vim/vim/issues/11638
