### ISSUE TITLE
2 ideas for diff kitten

### ISSUE THREAD

**Issue by alok** [kovidgoyal/kitty#574]
I'm not sure how feasible either of these are with the current architecture, so feel free to ignore.

1. Enable pager-like search in the overlay.
2. Enable mouse copy for each column. If I select a region with the mouse, it selects across both columns instead of just one, but generally I only want to select one column (without the line numbers).

**Comment by kovidgoyal** [comment]
I have implemented searching. As for mouse select by column, you can do that already by just pressing the Ctrl+Alt keys while selecting with the mouse, which will select in rectangular blocks.
