### ISSUE TITLE
systemd-oomd kill due to memory pressure

### ISSUE THREAD

**Issue by chapmanjacobd** [kovidgoyal/kitty#5743]
**The problem**
I don't have a reproducible example and I wouldn't call this a bug per se but it is annoying when it happens. Kitty gets killed by systemd-oomd once a week or so. It only happens when I run programs that use a lot of disk/memory I/O even if they don't display much.

I believe this is mainly an issue with Fedora. I have not experienced this with OpenSuSE. I don't believe kitty itself is using much memory so I don't think my specific issue is [related to GPU](https://github.com/kovidgoyal/kitty/issues/5015) or rendering--but I could be wrong.

```sh
journalctl --since "280 minutes ago" $argv | grep -i kitty
Dec 04 20:15:55 fedora systemd-oomd[970]: Killed /user.slice/user-1000.slice/user@1000.service/app.slice/app-kitty-47f7730eb1474ba3848f1b5d6135a33f.scope due to memory pressure for /user.slice/user-1000.slice/user@1000.service being 77.97% > 50.00% for > 20s with reclaim activity
Dec 04 20:15:55 fedora systemd[1348]: app-kitty-47f7730eb1474ba3848f1b5d6135a33f.scope: systemd-oomd killed 65 process(es) in this unit.
Dec 04 20:15:55 fedora systemd[1348]: app-kitty-47f7730eb1474ba3848f1b5d6135a33f.scope: Consumed 5h 50min 18.998s CPU time.
Dec 04 20:16:23 fedora systemd[1348]: Started app-kitty-3ddf661aff0d47e9b722372807496e5d.scope - kitty - Terminal emulator.
Dec 04 20:16:23 fedora kded5[2492626]: [338 20:16:23.532088] Failed to load libstartup-notification-1.so with error: libstartup-notification-1.so.0.0.0: cannot open shared object file: No such file or directory. This has two main effects: There will be no startup feedback and when using --single-instance, kitty windows may start on an incorrect desktop/workspace.
Dec 04 23:16:48 fedora systemd-oomd[970]: Killed /user.slice/user-1000.slice/user@1000.service/app.slice/app-kitty-3ddf661aff0d47e9b722372807496e5d.scope due to memory pressure for /user.slice/user-1000.slice/user@1000.service being 70.47% > 50.00% for > 20s with reclaim activity
Dec 04 23:16:48 fedora systemd[1348]: app-kitty-3ddf661aff0d47e9b722372807496e5d.scope: systemd-oomd killed 62 process(es) in this unit.
Dec 04 23:16:48 fedora systemd[1348]: app-kitty-3ddf661aff0d47e9b722372807496e5d.scope: Consumed 15min 2.657s CPU time.
Dec 04 23:16:54 fedora systemd[1348]: Started app-kitty-473a086c803d4fd288a6f87e87dd8c3c.scope - kitty - Terminal emulator.
Dec 04 23:16:54 fedora kded5[2566333]: [338 23:16:54.855459] Failed to load libstartup-notification-1.so with error: libstartup-notification-1.so.0.0.0: cannot open shared object file: No such file or directory. This has two main effects: There will be no startup feedback and when using --single-instance, kitty windows may start on an incorrect desktop/workspace.
Dec 05 00:27:30 fedora systemd[1348]: Started app-kitty-80d8eac05c994a7fabc04528b516086a.scope - kitty - Terminal emulator.
Dec 05 00:27:30 fedora kded5[2576467]: [339 00:27:30.626751] Failed to load libstartup-notification-1.so with error: libstartup-notification-1.so.0.0.0: cannot open shared object file: No such file or directory. This has two main effects: There will be no startup feedback and when using --single-instance, kitty windows may start on an incorrect desktop/workspace.
```

**Solutions and alternatives**
kitty is the only program I have which this has happened to but it seems like other people have an issue with [KDE Konsole](https://old.reddit.com/r/Fedora/comments/rhsuhx/is_there_a_way_to_make_systemdoomd_a_little_bit/hot1kkh/).

The solution is likely to tweak systemd-oomd and/or convince the Fedora people to make similar changes but there is a possibility that something could be done in kitty like run each tab in its own cgroup (does that happen already?) Then only a single tab would get killed instead of the whole thing? Maybe that is a lot of work. I don't know.

My main purpose in submitting this issue is to have a placeholder so that when it happens again and I can reproduce the situation reliably, or if I find a solution, then I will document it here.

**Additional context**

- [systemd-oomd kills wrong application](https://bugzilla.redhat.com/show_bug.cgi?id=1941340) 
- [Is there a way to make systemd-oomd a *little* bit more granular? Maybe don't start by whacking entire cgroups?](https://old.reddit.com/r/Fedora/comments/rhsuhx/is_there_a_way_to_make_systemdoomd_a_little_bit/)
- [systemd-oomd kills anaconda in the middle of system install](https://bugzilla.redhat.com/show_bug.cgi?id=1929856) LOL!
- [Systemd-oomd very aggressive in killing apps](https://bugzilla.redhat.com/show_bug.cgi?id=1941170)

**Comment by kovidgoyal** [comment]
Tabs are not isolated in kitty. But you are free to start as many
individual kitty processes as you like instead, which will be in top
level windows rather than tabs.

Also unless there is an actual memory leak in kitty, this is a bug in the
OOM killer. It needs to be killing whatever process is using excessive
amounts of memory. 

If you can find a way to get kitty to reproducably leak memory while
keeping the number of kitty windows constant, do let me know, otherwise, this
is not a kitty issue.
