### ISSUE TITLE
Excessive GPU usage after large application output on macOS Intel

### ISSUE THREAD

**Issue by mikkelfj** [kovidgoyal/kitty#5748]
**Describe the bug**
After absorbing large amounts of log from a terminal application, the GPU remains highly active after said application terminates, unless switching to a Kitty window with a text editor controlling the entire Kitty display area. The GPU spins up again immediately when switching back, but the GPU spins back up again immediately when switching tab back to the terminal, as monitored on macOS Activity Monitor GPU history display, and laptop fan noise. The original application is not in the process list, and CPU usage is then low.

**To Reproduce**

0. On macOS MacBook Pro laptop with Intel Iris integrated graphics.
1. Start a Kitty terminal with Fish shell.
2. Run a custom built console localhost socket web server application driven by a benchmark program like ab or wrk that dumps debug logs for about a million requests at a rate of about 6K/s.
3. ... or probably any other application with massive console output.
4. Wait until it completes, or terminate the app after GPU usage spikes for a while / laptop fan noise becomes audible.
5. Make sure the original app is closed and not burning cycles anywhere any more.
6. Start a tab with the Helix text editor (or probably most other editor applications controlling the full Kitty window).
7. Observe GPU history drop to zero nearly instantly and fan noise spin down shortly after.
7. Switch back to the Kitty terminal tab that is now silent.
8. Observer GPU spin up again almost immediately.
9. Switch back the editor and observe the GPU spin down.
10. repeat as often as you like.
11. Exit the Kitty application.
12. Start the Fish terminal Window, and the Helix editor tab.
13. Switch back and worth, and observe that the GPU is now nearly idle.

**Screenshots**
I didn't take any, but imagine a noisy square wave on the GPU history correlating with switching back and forth between the two Kitty tabs.

**Environment details**

Observe that the shell is fish, version 3.3.1 via Kitty.conf although the OS shell is zsh.
Helix editor is Helix 22.08.1 (66276ce6), official release.
macOS 11.7.1 Big Sur.
MacBook Pro Intel, driving an external 4K display at 60Hz via display port in clam shell mode.

```
kitty 0.26.4 created by Kovid Goyal
Darwin Bedrock 20.6.0 Darwin Kernel Version 20.6.0: Thu Sep 29 20:15:11 PDT 2022; root:xnu-7195.141.42~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.7.1 BuildVersion:	20G918
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/mikkelfj/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.9
bold_font               IBM Plex Mono Semibold
bold_italic_font        IBM Plex Mono Semibold Italic
editor                  /usr/local/bin/hx
font_family             IBM Plex Mono
font_size               10.0
italic_font             IBM Plex Mono Italic
macos_option_as_alt     3
shell                   /usr/local/bin/fish
Colors:
	active_tab_background   #4c566a   
	active_tab_foreground   #e5e9f0   
	background              #2e3440   
	color0                  #3b4252   
	color1                  #bf616a   
	color10                 #a3be8c   
	color11                 #ebcb8b   
	color12                 #81a1c1   
	color13                 #b48ead   
	color14                 #88c0d0   
	color15                 #e5e9f0   
	color2                  #a3be8c   
	color3                  #ebcb8b   
	color4                  #81a1c1   
	color5                  #b48ead   
	color6                  #88c0d0   
	color7                  #e5e9f0   
	color8                  #4c566a   
	color9                  #bf616a   
	cursor                  #d8dee9   
	cursor_text_color       #4c566a   
	foreground              #d8dee9   
	inactive_tab_background #3b4252   
	inactive_tab_foreground #d8dee9   
	mark1_foreground        #d08770   
	mark2_foreground        #d08770   
	mark3_foreground        #d08770   
	selection_background    #3b4252   
	selection_foreground    #d8dee9   
	url_color               #e5e9f0   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.fkfD9cXuJM/org.macosforge.xquartz:0
	USER                                mikkelfj

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Kitty.conf is nearly standard. Just setting terminal to fish and choosing "nord" theme.

**Comment by mikkelfj** [comment]
Note that I have edited the issue since your comment to make it clearer, but in essence:

> I dont understand your issue. If you are rendering text continuously its
going to take system resources.

The point is that I do not render continously. Kitty does when it should not. The application under test has long terminated. But Kitty keeps burning GPU with a completely inactive terminal view.

**Comment by mikkelfj** [comment]
I might add that the fact my test was possibly at all at a rate of 6Kreq/s. with multiple log lines per request, was pretty impressive (in release build with no logs, the rate would be far higher, but still). I do not object to Kitty burning GPU while the test is running.

**Comment by kovidgoyal** [comment]
kitty will only render text when an application sends it text. I
absolutely cannot replicate kitty "burning GPU" or indeed using GPU at
all when no text is being sent to it.

**Comment by mikkelfj** [comment]
All I can say is that I did observe it that it happened. I realize it might be hard to reproduce, but I am absolutely certain the GPU activity happened with no visual output and no application running. So rather than ignoring this issue, maybe another approach is to logically consider what application flow internal to Kitty might trigger such a behaviour?

**Comment by kovidgoyal** [comment]
I did consider it, and cant think of any. kitty's event loop doesnt even
tick when there is no input, once the cursor stops blinking. So if you
have a reproducer I will be happy to investigate, otherwise, I have
higher priority things to spend my time on.

**Comment by mikkelfj** [comment]
> I have higher priority things to spend my time on.

Fair enough, I am just providing the information, and maybe you one day stumble on something that makes sense.

Actually the cursor is blinking in fish, and I briefly suspected that might be the cause (this is why I switched to Helix editor in the first place because it's cursor does not blink), but that is not it since there is no problem blinking in a fresh Kitty/fish session.

Also, at some point I suspected the choice of font might have some impact, but I have no knowledge of that.

**Comment by mikkelfj** [comment]
Forgot to mention, background is 10% transparency.
I also cannot reproduce, which does not mean that it does not exist. I might be a race condition, or even an OS driver bug. Either way I would have appreciated if you waited to close the issue until you actually understood it.

**Comment by mikkelfj** [comment]
This issues is recurring, just not on demand.
It seems that if helix window is closed, the GPU remains peg for quite some time but eventually quiets down.
Cursing stops blinking after 15s by default and seems to have no effect.
When this has happened, it easily happens again by starting helix and having a busy terminal, but it can take quiet some time to happen, but soon enough to be annoying. Quitting and restarting Kitty entirely can make the problem go away for much longer. Or at least that is my subjective impression.
