### ISSUE TITLE
Can't seem to understand how to change the input and output encoding [OSX]

### ISSUE THREAD

**Issue by TheTharin** [kovidgoyal/kitty#575]
Hello! I'm on OS X and I really like the fact that kitty is so fast and awesome. Tried iTerm2, but ranger file manager performs poorly and lags/freezes. It never happens in kitty but I'm from Russia and some of the Russian language appears not right, input not working properly at all and I can't seem to understand how to change the encoding of the terminal.
Take a look:

**This is Kitty:**
![image](https://user-images.githubusercontent.com/9999276/40518470-731c9168-5fc3-11e8-96fd-ac5d5be059d5.png)
![image](https://user-images.githubusercontent.com/9999276/40518526-c8582142-5fc3-11e8-999e-a832423539fe.png)

**This is iTerm2:**
![image](https://user-images.githubusercontent.com/9999276/40518488-964e988e-5fc3-11e8-806a-a03e6974c5c7.png) 
![image](https://user-images.githubusercontent.com/9999276/40518500-a99eb32e-5fc3-11e8-87ae-f24934ed13ad.png)

**Comment by kovidgoyal** [comment]
kitty uses UTF-8 encoding which is perfectly capable of supporting all scripts including cyrllic. WHat it does not support is various legacy encodings. So if you can figure out how to convince whatever program you are using to output UTF-8 you will be fine.

**Comment by peaceant** [comment]
I had similar problem with different language and I had to set `locale` in my `.bashrc` by adding these two lines:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by Peiprjs** [comment]
I had a similar issue (accents not displaying) and the above two lines fixed it for me, thanks

**Comment by marcusluissilva** [comment]
For Brazilian users (or anyone using Portuguese/ABNT2 layouts) struggling to type the "ç" or "~" character in Kitty, here is a step-by-step guide to fix it:

**1. Set your Locale (Linux & macOS)**
As @kovidgoyal said, Kitty uses UTF-8 to process accented characters correctly. So, ensure your shell environment is configured by adding these lines to your ~/.bashrc or ~/.zshrc: (Thanks, @peaceant)

```
export LANG=pt_BR.UTF-8
export LC_ALL=pt_BR.UTF-8
```

**2. Specific Fix for macOS**
If you are on macOS and use the Option key for accents, add this to your kitty.conf:

`macos_option_as_alt no`

**3. Apply Changes**
After saving the files, restart Kitty completely. For good measure, source your config file in the terminal:

`source ~/.bashrc  # or source ~/.zshrc`
