### ISSUE TITLE
After resize, prompt set in center of term screen

### ISSUE THREAD

**Issue by n1rdeks** [kovidgoyal/kitty#5751]
Kitty - 0.26.5
Distro - Arch.
WM - Xmonad and DWM.

Kitty started by command ```kitty -1```

After change master window in WM, prompt jump on center terminal screen.
In another alternatives, such as Urxvt and patched ST - all work fine and prompt and cursor set in bottom of term window.

![shit_happens](https://user-images.githubusercontent.com/63796667/206735466-6296d606-98f6-4836-a747-85a9f31ad816.gif)

And kitty.conf
```
scrollback_lines 2000

font_family      Pragmata Pro Mono Liga
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

disable_ligatures never
cursor_blink_interval 0
cursor_shape block
shell_integration no-cursor

background_opacity 0.86

foreground #93a1a1
background #00181f
cursor #528BFF
```

**Comment by kovidgoyal** [comment]
kitty reflows terminal and scrollback contents on resize. This is by
design. Presumably neither st nor urxvt do that.

**Comment by kovidgoyal** [comment]
Oh and you can use https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.scrollback_fill_enlarged_window  

to control this.

**Comment by n1rdeks** [comment]
Ah, I dont see u answer. I try...

**Comment by n1rdeks** [comment]
>Oh and you can use https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.scrollback_fill_enlarged_window to control this.

After add this option in conf - ALL work has expected. Thanks for help.
