### ISSUE TITLE
Bottommost hint isn't selectable

### ISSUE THREAD

**Issue by duganchen** [kovidgoyal/kitty#5752]
I'm trying to use hints to select git hashes, and I'm finding that the bottommost hint isn't selectable.

I have the following in kitty.conf:

    map ctrl+shift+p>g kitten hints --program @ --type regex --regex "\b([0-9a-f]{6}|[0-9a-f]{7}|[0-9a-f]{8}|[0-9a-f]{40})\b"

Pressing Ctrl+shift+p and then g gives me what I expect:

<img width="928" alt="Screen Shot 2022-12-09 at 6 00 48 PM" src="https://user-images.githubusercontent.com/447610/206823472-67c42984-22f1-44c4-b7f5-0ff3cf26e45b.png">

Pressing "1" gives me this:

<img width="928" alt="Screen Shot 2022-12-09 at 6 01 38 PM" src="https://user-images.githubusercontent.com/447610/206823485-f05d80de-c3ae-4dd5-a1ec-2e4a5ba10497.png">

The number for the bottommost match seems be blank. How do I select it?

**Comment by page-down** [comment]
This case is described in the documentation.

> Pressing the second letter will select that hint or press **Enter** or **Space** to select _the empty hint_.

https://sw.kovidgoyal.net/kitty/kittens/hints/
