### ISSUE TITLE
Something wrong with OSC52 yanking (randomly crashes kitty)

### ISSUE THREAD

**Issue by amanjitsk** [kovidgoyal/kitty#5756]
**Describe the bug**
There is a bug with OSC52 based yanking on kitty, that causes it to crash (randomly, sometimes it does, other times it doesn't)

**To Reproduce**
1. Put file `yank` on your `$PATH`  with contents
```
#!/bin/sh
#
# Usage: yank [FILE...]
#
# Copies the contents of the given files (or stdin if no files are given) to
# the terminal that runs this program.  If this program is run inside tmux(1),
# then it also copies the given contents into tmux's current clipboard buffer.
# If this program is run inside X11, then it also copies to the X11 clipboard.
#
# This is achieved by writing an OSC 52 escape sequence to the said terminal.
# The maximum length of an OSC 52 escape sequence is 100_000 bytes, of which
# 7 bytes are occupied by a "\033]52;c;" header, 1 byte by a "\a" footer, and
# 99_992 bytes by the base64-encoded result of 74_994 bytes of copyable text.
#
# In other words, this program can only copy up to 74_994 bytes of its input.
# However, in such cases, this program tries to bypass the input length limit
# by copying directly to the X11 clipboard if a $DISPLAY server is available;
# otherwise, it emits a warning (on stderr) about the number of bytes dropped.
#
# See http://en.wikipedia.org/wiki/Base64 for the 4*ceil(n/3) length formula.
# See http://sourceforge.net/p/tmux/mailman/message/32221257 for copy limits.
# See http://sourceforge.net/p/tmux/tmux-code/ci/a0295b4c2f6 for DCS in tmux.
#
# Written in 2014 by Suraj N. Kurapati <https://github.com/sunaku>
# Also documented at https://sunaku.github.io/tmux-yank-osc52.html

put() {
  esc=$1
  test -n "$TMUX" -o -z "${TERM##screen*}" && esc="\033Ptmux;\033$esc\033\\"
  printf "$esc"
}

# copy via OSC 52
buf=$( cat "$@" )
len=$( printf %s "$buf" | wc -c ) max=74994
test $len -gt $max && echo "$0: input is $(( len - max )) bytes too long" >&2
put "\033]52;c;$( printf %s "$buf" | head -c $max | base64 | tr -d '\r\n' )\a"
```

Run in the shell something like `ls | yank`, 
and see kitty crash (if not, I don't know what else to try because the same 
command crashes kitty sometimes, other times it doesn't.)

**Comment by kovidgoyal** [comment]
Doesnt reproduce for me, running kitty from master. You havent filled in any of the information the issue template asks for. And post a backtrace from the crash.

**Comment by amanjitsk** [comment]
Yup, I wanted to see if there is a reliable way of reproducing the problem. 
How can I get the backtrace from the crash?
I have managed to reproduce it (still random) when running `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Depends on your distro, search its documentation. Typically

echo bt full | coredumpctl gdb

and for the backtrace to be truly useful you should build from source
https://sw.kovidgoyal.net/kitty/build/ 

Preferably with make asan.
and fill in the rest of the information asked for in the issue template.

**Comment by kovidgoyal** [comment]
no followup
