### ISSUE TITLE
How to execute a command in a new window?

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#5771]
The following starts a new shell and prints hi

```zsh
zsh -l -i -c 'echo hi'
```

The following creates a new window and starts a new shell

```zsh
kitty @ launch zsh -l -i
```

Putting these two together, I would expect (and it doesn't happen), that this will open a window, start a shell and print hi (instead the new window briefly flashes and is closed immediately.)

```zsh
kitty @ launch zsh -l -i -c 'echo hi'
```

**Comment by rysson** [comment]
You miss another a (default) interactive shell launched by the kitty. Then you have
* kitty
    * shell (interactive)
        * zsh
            * echo

When `echo` is finished, `zsh` finishes too. You see the interactive shell.

If you call `zsh` directly in the `kitty`, `echo` is fished, then `zsh` is finished, then... `kitty` is finished. There is no interactive shell to keep `kitty` open.

I've found a solution for bash (see section *Another solution* in https://unix.stackexchange.com/a/123192/455586), I hope, you can adopt it.

Bash script `~/.local/bin/bash-cmd`
```bash
#!/bin/bash
START_COMMAND="$@" exec bash
```

And the end of the bash initial script:
```bash
# Start command
if [[ -n "START_COMMAND" ]]; then
  start_command="$START_COMMAND"
  unset START_COMMAND
  eval "$start_command"
fi
```

This allows me to execute command in a session file
```
new_tab
launch bash-cmd echo hi
```

**Comment by kovidgoyal** [comment]
You want

kitty @ launch zsh -c 'echo hi; zsh -l -i'
