### ISSUE TITLE
[question] launch new_os_window with class name

### ISSUE THREAD

**Issue by rysson** [kovidgoyal/kitty#5772]
How to launch `new_os_window` in a session file with a os-window class name (xorg)?
I have a few windows and I need to mark them.

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

**Comment by kovidgoyal** [comment]
Simply start your session file with 

new_tab my title

similarly putting

os_window_class whatever

at the start will change the class of the first os window.

**Comment by rysson** [comment]
OK, I missed that `new_tab [TITLE]` works, thank you.


But `os_window_class` seems have no any effect:

```
WM_CLASS(STRING) = "kitty", "kitty"
```

**Comment by kovidgoyal** [comment]
Works fine for me. Make sure you are running up to date kitty.

**Comment by rysson** [comment]
My fault, I ran kitty from Debian Bullseye (0.21.2).

Built from master (0.26.5) it woks
```
WM_CLASS(STRING) = "kitty", "class1"
```

Thanks a lot for your awesome work!
