### ISSUE TITLE
Is it possible to set font size separately?

### ISSUE THREAD

**Issue by NEX-S** [kovidgoyal/kitty#5775]
**Is your feature request related to a problem? Please describe.**
Is it possible to set font size separately?

For example

```
font_size 11
italic_font_size 20  <----------- Set italic font size separately
```

the reason I wanna do this is that sometimes we will get a large gap between different font sizes
![image](https://user-images.githubusercontent.com/97107165/207585816-d8865eb0-9494-4cc0-9b15-630bfdb8380a.png)

**Comment by kovidgoyal** [comment]
No you cant set the font size for different faces independently. You can adjust gaps using modify_font but that will apply to all fonts.
