### ISSUE TITLE
ctrl+^ does not work

### ISSUE THREAD

**Issue by Arvedui** [kovidgoyal/kitty#578]
I use `kitty 0.10.1` on linux. I can reproduce this with the default config.

Pressing ctrl+^ does not register at all (`showkey -a` does not print anything).
Doing the same in xterm or termite yields `^^       30 0036 0x1e`.

**Comment by kovidgoyal** [comment]
Works for me on master in linux.
![screenshot_20180527_080646](https://user-images.githubusercontent.com/1308621/40581978-ee40e78c-6184-11e8-8479-f9611a3fe89b.png)


You can run kitty with GLFW_DEBUG_KEYBOARD=1 and it will print more detailed output about what keypresses it sees.

**Comment by Arvedui** [comment]
Does not work with current master(c8756612f7) either.

The keypress is registed by glwf though.

    scancode: 0x25 release: 0 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: LEFT CONTROL
    scancode: 0x31 release: 0 clean_sym: asciicircum composed_sym: asciicircum mods: ctrl+numlock glfw_key: UNKNOWN
    scancode: 0x31 release: 1 clean_sym: asciicircum mods: ctrl+numlock glfw_key: UNKNOWN
    scancode: 0x25 release: 1 clean_sym: Control_L mods: ctrl+numlock glfw_key: LEFT CONTROL

**Comment by kovidgoyal** [comment]
According to that you have a XKB composition rule converting ctrl+6 into the circumflex unicode symbol. Remove that rule and you will be fine.

**Comment by Arvedui** [comment]
No. Circumflex is the primary assignment of the left most key in the number row on the german keyboard layout.

**Comment by Arvedui** [comment]
That does not seem to be the problem since the circumflex key itself works as expected. Just not with the modifier. Which seems to be a general problem with kitty.
Many keys that are not found on the english keyboard or are in different positions do not yield the expected keycode when used with ctrl.
I entered a sequence of keys with ctrl pressed in xterm, termite, qterminal and kitty these are the results:

Key | xterm | termite | qterminal | kitty
------|---------|--------------|--------------|-------
^ | `^^       30 0036 0x1e` | `^^ 	 30 0036 0x1e` | `^^       30 0036 0x1e` | -
1 | `1        49 0061 0x31` | `1 	 49 0061 0x31` | `1        49 0061 0x31` | `1        49 0061 0x31`a modifier (or at least ctrl).
2 | `^@        0 0000 0x00` | `^@        0 0000 0x00` | `^@        0 0000 0x00` | `2        50 0062 0x32`
3 | `^[       27 0033 0x1` | `^[       27 0033 0x1` | `^[       27 0033 0x1` | `3        51 0063 0x33`
4 | `^\       28 0034 0x1c` | `^\       28 0034 0x1c` | `^\       28 0034 0x1c` | `4        52 0064 0x34`
5 | `^]       29 0035 0x1d` | `^]       29 0035 0x1d` | `^]       29 0035 0x1d` | `5        53 0065 0x35`
6 | `^^       30 0036 0x1e` | `^^       30 0036 0x1e` | `^^       30 0036 0x1e` |  `^^       30 0036 0x1e`
7 | `^_ 	 31 0037 0x1f` | `^_ 	 31 0037 0x1f` | `^_ 	 31 0037 0x1f` | `7        55 0067 0x37`
8 | `^?      127 0177 0x7f` | `^?      127 0177 0x7f` | `^?      127 0177 0x7f` | `8        56 0070 0x38`
9 | `9        57 0071 0x39` | `9        57 0071 0x39` | `9        57 0071 0x39` | `9        57 0071 0x39`
0 | `0        48 0060 0x30` | `0        48 0060 0x30` | `0        48 0060 0x30` | `0        48 0060 0x30`
ß | - | `ß       195 0303 0xc3`<br>`        159 0237 0x9f` | `ß 	195 0303 0xc3`<br>`159 0237 0x9f` | -
` | - | `´ 	194 0302 0xc2` <br> ` 	180 0264 0xb4` | `´ 	194 0302 0xc2` <br> ` 	180 0264 0xb4` | -
ü | - | `ü 	195 0303 0xc3` <br> ` 	188 0274 0xbc` | `ü 	195 0303 0xc3` <br> ` 	188 0274 0xbc` | -

This is the coresponding glfw log

	scancode: 0x25 release: 0 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: LEFT CONTROL
	scancode: 0x31 release: 0 clean_sym: asciicircum composed_sym: asciicircum mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x31 release: 1 clean_sym: asciicircum mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0xa release: 0 clean_sym: 1 composed_sym: 1 mods: ctrl+numlock glfw_key: 1
	scancode: 0xa release: 1 clean_sym: 1 mods: ctrl+numlock glfw_key: 1
	scancode: 0xb release: 0 clean_sym: 2 composed_sym: 2 mods: ctrl+numlock glfw_key: 2
	scancode: 0xb release: 1 clean_sym: 2 mods: ctrl+numlock glfw_key: 2
	scancode: 0xc release: 0 clean_sym: 3 composed_sym: 3 mods: ctrl+numlock glfw_key: 3
	scancode: 0xc release: 1 clean_sym: 3 mods: ctrl+numlock glfw_key: 3
	scancode: 0xd release: 0 clean_sym: 4 composed_sym: 4 mods: ctrl+numlock glfw_key: 4
	scancode: 0xd release: 1 clean_sym: 4 mods: ctrl+numlock glfw_key: 4
	scancode: 0xe release: 0 clean_sym: 5 composed_sym: 5 mods: ctrl+numlock glfw_key: 5
	scancode: 0xe release: 1 clean_sym: 5 mods: ctrl+numlock glfw_key: 5
	scancode: 0xf release: 0 clean_sym: 6 composed_sym: 6 mods: ctrl+numlock glfw_key: 6
	scancode: 0xf release: 1 clean_sym: 6 mods: ctrl+numlock glfw_key: 6
	scancode: 0x10 release: 0 clean_sym: 7 composed_sym: 7 mods: ctrl+numlock glfw_key: 7
	scancode: 0x10 release: 1 clean_sym: 7 mods: ctrl+numlock glfw_key: 7
	scancode: 0x11 release: 0 clean_sym: 8 composed_sym: 8 mods: ctrl+numlock glfw_key: 8
	scancode: 0x11 release: 1 clean_sym: 8 mods: ctrl+numlock glfw_key: 8
	scancode: 0x12 release: 0 clean_sym: 9 composed_sym: 9 mods: ctrl+numlock glfw_key: 9
	scancode: 0x12 release: 1 clean_sym: 9 mods: ctrl+numlock glfw_key: 9
	scancode: 0x13 release: 0 clean_sym: 0 composed_sym: 0 mods: ctrl+numlock glfw_key: 0
	scancode: 0x13 release: 1 clean_sym: 0 mods: ctrl+numlock glfw_key: 0
	scancode: 0x14 release: 0 clean_sym: ssharp composed_sym: ssharp mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x14 release: 1 clean_sym: ssharp mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x15 release: 0 clean_sym: acute composed_sym: acute mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x15 release: 1 clean_sym: acute mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x22 release: 0 clean_sym: udiaeresis composed_sym: udiaeresis mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x22 release: 1 clean_sym: udiaeresis mods: ctrl+numlock glfw_key: UNKNOWN
	scancode: 0x25 release: 1 clean_sym: Control_L mods: ctrl+numlock glfw_key: LEFT CONTROL


I pressed all keys in the number row form left to right and the `ü` key at the end while holding ctrl.


I't seems i was wrong about what ctrl+6 is supposed to do in my layout, but still there are a lot of keys that behave differently in kitty than in other terminals.

**Comment by kovidgoyal** [comment]
Ctrl key + number is not well defined in terminals. Look at your table above. Notice how Ctrl+1 and 1 produce the same bytes. Same for 0 and Ctrl+0 and for Ctrl+6 and Ctrl+^ . Similarly Ctrl+8 and backspace produce the same bytes. And ctrl+3 and Ctrl+[ produce the same bytes and ctrl+2 and ctrl+shift+2 produce the same bytes and so on.

Which is why kitty basically ignores the Ctrl in the Ctrl+number combinations. I could modify kitty to behave the same way as the other terminals, but there isn't much point since you cannot actually use those keys reliably in terminal programs, as multiple key presses map to the same end bytes. Still I am open to doing that for at least the number keys, if for no other reason than to avoid the duplicate bug reports about it :)

If you want to use these and many other key combinations that are not possible in traditional terminal programs, the solution is to get those programs to adopt a modern keyboard protocol for terminals, such as the one kitty supports https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc

Similarly ctrl+<language specific unicode character> is not meaningful. I know of no standard that specifies how that should behave, there are no terminfo entries for them and as far as I know it behaves completely differently in different terminals, which you can see in your table above (add in a few terminal programs from other OSes and the variations get even more pronounced).

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/7332561d8e432026e0bad1742e106ae71229eeac

**Comment by Arvedui** [comment]
Thank you very much especially for the explanation, but my initial problem ist still not solved. I'm sorry that I still have to bother you. Pressing ctrl+^ is still not registered by the application when running in kitty.

**Comment by kovidgoyal** [comment]
Just press ctrl+6 instead o ctrl+^ and you will get the same bytes. There is no way to represent the ^ key in GLFW, so it cannot work in kitty. See the line

```
scancode: 0x31 release: 0 clean_sym: asciicircum composed_sym: asciicircum mods: ctrl+numlock glfw_key: UNKNOWN
```

In particular glfw_key: UNKNOWN

that means glfw has no way to represent this key, therefore kitty has no way to process it either. This can be confirmed by looking here: http://www.glfw.org/docs/latest/group__keys.html

**Comment by Arvedui** [comment]
That is quite unfortunate, as I use that key combination quite often and ctrl+^ is much easier to reach for me.

Thanks anyway.
