### ISSUE TITLE
Cursor Text color does not correspond to terminal output

### ISSUE THREAD

**Issue by MohamedAliChabani** [kovidgoyal/kitty#5781]
I want the text inside the block to be always black
Although cursor_text_color is set to #111111 it does not correspond to what I get in the terminal.
![2022-12-15-130006_1920x1080_scrot](https://user-images.githubusercontent.com/66540604/207854059-7809a627-29dd-4af4-b365-837c1d310a09.png)
As you can see in this image the letter c is hidden because the cursor is white and the text is white, I want the letter to be black.

**Comment by kovidgoyal** [comment]
You need to provide all the information asked for in the issue template
if you want assistance.

**Comment by kovidgoyal** [comment]
no followup
