### ISSUE TITLE
Kitty is reading all skhd external shortcuts (Mac OS)

### ISSUE THREAD

**Issue by iortego42** [kovidgoyal/kitty#5788]
Something is going wrong, every shortcut I add on other configuration, kitty tries to recognize it beforeother process can read the input.
I have tried bunch of thing like enabling and disabling option as alt, and starting a new empty kitty.conf to know if was something about an hidden option I have which I didn't noticed. 
Is there any solution better than adding all the external shortcuts to the kitty.conf ? Because it is the only thing I think it could work.

**Comment by kovidgoyal** [comment]
kitty does not read shortcuts, it responds to key events sent to it by
the system. Run kitty --debug-input and you will see that any shortcut
it responds to is being sent to it.

**Comment by iortego42** [comment]
Okay thank you very much I have understood that. I have done it and the keyboard events appear on the debug terminal but I fail to understand why kitty is responding to that events previously than the shortcuts app, because after kitty responds (doing nothing or writing some numbers on the prompt because of the combination of keys), the other app can not read that input

**Comment by kovidgoyal** [comment]
kitty will respond to any and all key events it receives. That's its job. Your question should be why the system is sending it events for something you want some other app to handle.

**Comment by iortego42** [comment]
Oh okey, so I must focus on telling the system to send that events first to another app? I thought it would be something about kitty because I have try it with other terminals and they don't have that issue

**Comment by iortego42** [comment]
It was something stupid. On the top bar kitty menu on MacOS, it has an Secure Keyboard Input, so just disabling that it is solved. Thank you very much by the way !!!
