### ISSUE TITLE
unicode_input copy to clipboard

### ISSUE THREAD

**Issue by chmouel** [kovidgoyal/kitty#5789]
**Is your feature request related to a problem? Please describe.**

I really like the unicode_input and use it as my emoji picker. I could not find a way to let it to copy in clipboard the characters, only let you paste it in the terminal window (after selection).

The `hints` allows you to do that (copy selected hints to the clipboard), would you be open to have that feature in kitty?

Thanks

**Describe the solution you'd like**

add a `--program` argument the same way we have it for hints, with the @ and - arguments

**Describe alternatives you've considered**

**Additional context**

**Comment by kovidgoyal** [comment]
map f1 launch --type=overlay sh -c "kitty +kitten unicode_input | kitty +kitten clipboard"
