### ISSUE TITLE
the underline turned into a wavy line

### ISSUE THREAD

**Issue by aklk1ng** [kovidgoyal/kitty#5792]
![2022-12-18_15-07](https://user-images.githubusercontent.com/94452368/208286035-24fbca2c-f3a6-45d8-a1d2-b0b5c24f486e.png)

**Hey,why the underline turned into a wavy line when the lsp report the warning,the condition only appear in the kitty terminal and my simple terminal and alacritty are normal.**

![2022-12-18_15-07_1](https://user-images.githubusercontent.com/94452368/208286020-e8432d6d-b8e7-43f9-92f7-0d637560403d.png)

**I just annotated a few lines of configuration for the above image,then the underline disappear,but when i resetting the configuration, the situation has not changed.**

**Comment by kovidgoyal** [comment]
Presumably because those two dont support wavy underlines, a feature
pioneered by kitty.
