### ISSUE TITLE
getting command not found: font_size 

### ISSUE THREAD

**Issue by Nivethan-Ar** [kovidgoyal/kitty#5794]
**Describe the bug**
I'm using ubuntu and  zsh terminal, i installed kitty and pressed ctrl+shift+f2 and created a kitty.config file. but if i uncomment any options on the config i get an error for example 
`command not found: font_size`

**To Reproduce**
1. install kitty on ubuntu
2. create the config file
3. change any config options

**Screenshots**
![image](https://user-images.githubusercontent.com/63112138/208389579-24e4f25b-ed46-4b59-b565-eb8c4346a7a3.png)

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
ubuntu 22.04
```

**Comment by page-down** [comment]
You need to press `ctrl+shift+f5` to reload the configuration, or quit and run kitty again.

The configuration file is not a shell rc file and is not loaded via `source`.

**Comment by Nivethan-Ar** [comment]
@page-down thanks for the quick reply, i tried quitting but getting the same error when i run the 
`source .config/kitty/kitty.conf` and font size also not changing.

**Comment by page-down** [comment]
> getting the same error when i run the `source ...` ...
> edit: i restarted my laptop and checked getting the same response.!

Ok, I'll try to phrase it differently, don't do that, don't ever try to run the command you're talking about.

If you wish to completely reload the modified `kitty.conf`, end the kitty process, which is the GUI program you have in front of you, and then run it again.
If you do not wish to exit, then the default shortcut `ctrl+shift+f5` will reload most of the configurations.

**Comment by Nivethan-Ar** [comment]
@page-down gahh i'm feeling like an idiot! thank you so much, it works now!
