### ISSUE TITLE
Url detection in neovim's floating window

### ISSUE THREAD

**Issue by NEX-S** [kovidgoyal/kitty#5799]
![image](https://user-images.githubusercontent.com/97107165/208732903-7b01c573-2b41-4e55-aa9d-89b3ba207118.png)

![image](https://user-images.githubusercontent.com/97107165/208733218-3b7cf713-8bf4-428a-b211-ff92d2c946f1.png)

it seems the URL detection might not work correctly in neovim's floating window, should I open an issue in neovim too?

**Comment by kovidgoyal** [comment]
There is no such thing as a "floating window" as far as the terminal emulator is concerned. Its all one window. A URL will be detected if there is a continuous sequence of characters that look like a URL see the url_prefixes and url_excluded_characters options in kitty.conf.

If a terminal program is outputting URLs that are not continuous ranges of characters that are valid in URLs then it should mark the URL using the OSC 8 escape code.
