### ISSUE TITLE
Kitty no longer works with vim's &termguicolors option

### ISSUE THREAD

**Issue by chdiza** [kovidgoyal/kitty#5801]
Very recently, Bram made two patches specifically for kitty (9.0.1073, and I think 9.0.1080).  The former has broken the ability to use &termguicolors in vim.  I reported this at the Vim repo (https://github.com/vim/vim/issues/11729), and Bram says:

>You need to set t_8f and t_8b:                                                  
>                                                                             
>        let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"                                 
>        let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"                                 
>                                                                              
>These are apparently missing from the kitty terminfo entry.                     
>Before they were coming from the built-in xterm termcap entries, but since      
>it turned out that kitty is not xterm compatible these should not be used. 

I don't know what the correct move is here, but carrying that around in my vimrc is bulkier than what I carry around now for kitty, namely  `set t_ut=""`.

**Comment by kovidgoyal** [comment]
Yes, I told Bram his patch was wrong. He refuses to listen. Nothing I can do about that.  https://github.com/vim/vim/issues/11716
