### ISSUE TITLE
test_single_key fails on big-endian systems

### ISSUE THREAD

**Issue by jamessan** [kovidgoyal/kitty#5802]
```
FAIL: test_single_key (kitty_tests.datatypes.TestDataTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/datatypes.py", line 556, in test_single_key
    self.assertNotEqual(hash(SingleKey(key=1, mods=2)), hash(SingleKey(key=1)))
    GLFW_MOD_KITTY = 256
    GLFW_MOD_SHIFT = 1
    SingleKey = <class 'fast_data_types.SingleKey'>
    m = 1
    s = SingleKey(mods=1)
    self = <kitty_tests.datatypes.TestDataTypes testMethod=test_single_key>
AssertionError: 1 == 1
```

Encountered on Debian's [hppa](https://buildd.debian.org/status/fetch.php?pkg=kitty&arch=hppa&ver=0.26.5-1&stamp=1671652623&raw=0) and [powerpc](https://buildd.debian.org/status/fetch.php?pkg=kitty&arch=powerpc&ver=0.26.5-1&stamp=1671651634&raw=0) builds.

**Comment by kovidgoyal** [comment]
Unfortunately I dont have access to such a system to test on. The relevant code will be in keys.c starting from line 296 probably the bitfield operations need adjustment for endianness.

**Comment by kovidgoyal** [comment]
Most likely the SingleKey_set_vals function
