### ISSUE TITLE
Protocol extension to change mouse pointer shape.

### ISSUE THREAD

**Issue by Dragon-Hatcher** [kovidgoyal/kitty#5806]
**Is your feature request related to a problem? Please describe.**
Not really a problem just something that would be nice to have for TUI applications.

**Describe the solution you'd like**
Add support for an escape sequence to change the shape of the mouse pointer. I see two options. One is to use something similar to the escape code for changing the cursor shape (i.e. a list of shapes selected from with a number). The second option is to extend the graphics protocol to support writing an image that is used as the mouse pointer. This would be more flexible.

**Describe alternatives you've considered**
I considered drawing the cursor using the existing graphics api and the SGR-pixels mouse mode however this has two problems. 1) The drawn cursor will lag behind the real cursor and 2) the real cursor will appear over the drawn cursor (unless there is a way to hide the mouse pointer that I'm not aware of).

**Additional context**
This would be useful for TUI applications.

**Comment by kovidgoyal** [comment]
I don't have a use for this personally, so maybe speak a bit more about
the use case. Is there a particular TUI application that wants to use
it? And why an escape code to change it rather than say an SGR attribute
to set the shape per cell. 

Also using custom shapes is likely a bridge too far.

**Comment by Dragon-Hatcher** [comment]
I hadn't considered setting it per cell. That seems like a perfectly fine solution.

As for what it would be usefule for: There's no particular TUI I had in mind but it just generally makes a UI feel better when the mouse cursor reacts. Pointer cursor for buttons, I bar for text fields, double arrows to represent resizable objects, hand to represent draggable objects. So just it improves the feel of TUIs in general. 

I agree custom images would be to much.

Perhaps no cursor (hidden) could also be one of the available cursors?

**Comment by kovidgoyal** [comment]
On Thu, Dec 22, 2022 at 08:48:19PM -0800, Dragon-Hatcher wrote:
> I hadn't considered setting it per cell. That seems like a perfectly fine solution.

Not necessarily it means carrying around another attribute per cell
which increases memory consumption for a very marginal use case. Which
approach is better depends very much on what the actual use case is.

> 
> As for what it would be usefule for: There's no particular TUI I had in mind but it just generally makes a UI feel better when the mouse cursor reacts. Pointer cursor for buttons, I bar for text fields, double arrows to represent resizable objects, hand to represent draggable objects. So just it improves the feel of TUIs in general. 

Well, sure. But everything has a cost, in this case, my time and effort.
So unless there is some actual significant application/TUI library that
says they are willing to add support for it, it isn't worth the effort to
me, as I don't see much use for it in any of the TUI applications I
write.

> 
> I agree custom images would be to much.
> 
> Perhaps no cursor (hidden) could also be one of the available cursors?

Yes, this can be one of the enum values.

**Comment by Dragon-Hatcher** [comment]
> Well, sure. But everything has a cost, in this case, my time and effort.
So unless there is some actual significant application/TUI library that
says they are willing to add support for it, it isn't worth the effort to
me, as I don't see much use for it in any of the TUI applications I
write.

That's perfectly reasonable. I wouldn't want to impose upon your time for a feature that is, as you say, very niche. I would try to implement it myself but I don't have much C++ experience. How difficult would you estimate it to be?

> Which approach is better depends very much on what the actual use case is.

I don't see either method being more difficult from the application side. I suppose the change the cursor globally method might be better for the sake of efficiency then.

**Comment by kovidgoyal** [comment]
kitty is written in Python and C not C++. And it would be fairly
difficult because the graphics toolkit kitty uses glfw only has about 5
cursor shapes, so you would first need to add those and implement them
in all 3 backends. Then you would have to implement changing of mouse
cursor shape over kitty windows. There can be more than one kitty window
per OS window and escape codes can only set the shape for one window. 

And of course you would have ot design an escape code protocol for it.
I am closing this as I dont intend to implement it personally, but feel
free to post further if you want to.
