### ISSUE TITLE
Using remote control features, can I change cursor shape or blink?

### ISSUE THREAD

**Issue by ahungry** [kovidgoyal/kitty#5807]
I found that I can change the cursor color using the `set-color` command, but I can't find a command to remotely set/change the cursor shape or blink interval.

Overly verbose story leading me to this request for info on how to do it (or feature if not able):

The reason I need this is that in my Emacs with tty mode, Kitty doesn't seem to handle the cursor the same as URxvt (where my settings end up allowing it to swap between a blinking cursor, and a solid unblinking one, based on the state of my evil mode).

As I can't find a way for Emacs to send raw terminal ANSI codes straight to kitty for interpretation (as how a `printf` may do in the terminal, where I can toggle the cursor via the proper escape codes) my idea was to have emacs shell out to run a remote kitty command in a sub-shell, that'd apply to my Emacs + kitty in my active window, and dynamically change the cursor.

**Comment by ahungry** [comment]
While I would still like this feature, in particular the ability to control blink properly (the escape codes I saw mentioned in 2 other tickets do not seem to work for me) I did find a workable solution for my own Emacs (if any other readers cared - sorry for the slightly offtopic comment):

```
(defun my-evil-kitty-cursor-fix ()
  (interactive)
  (if (eq 'insert evil-state)
      (send-string-to-terminal "\033[6 q")
    (send-string-to-terminal "\033[2 q")))

(run-with-timer 0 1 #'my-evil-kitty-cursor-fix)
```
As those particular codes do get interpreted (finding the way to send from Emacs straight to the term was the problem here).

**Comment by kovidgoyal** [comment]
I dont see the point there are already escape codes to set these, remote
control also works via escape code (unless you setup a socket for it).
And now that you have figured out how to send escape codes in emacs
there is no need.
