### ISSUE TITLE
[macOS] Unable to change Application Icon in Stage Manager on macOS 13.1

### ISSUE THREAD

**Issue by Shirk** [kovidgoyal/kitty#5817]
**Describe the bug**
The application icon for Kitty in Stage Manager on macOS 13.x does not reflect the actual icon.
The icon shown is the default Kitty icon regardless if the user changed the application icon.
This is a very minor issue, I'm only reporting it for the sake of "if you allow changing the icon it should affect all icons".

**To Reproduce**
1. install kitty on a system running macOS 13.0 or later
2. change the application icon as described [here](https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon)
3. enable Stage Manager

**Screenshots**
![Screenshot 2022-12-24 at 17 41 46@2x](https://user-images.githubusercontent.com/304352/209444644-74cc73f1-a73c-46cb-8652-a8a59f8f8703.png)
<img width="170" alt="Screenshot 2022-12-24 at 17 42 22@2x" src="https://user-images.githubusercontent.com/304352/209444553-f80f9533-0812-4d28-9cbb-7676fc897939.png">
<img width="394" alt="Screenshot 2022-12-24 at 17 42 37@2x" src="https://user-images.githubusercontent.com/304352/209444567-1e34a16e-cfb2-4122-b1d4-ad3c1ad03a27.png">

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin Kazuki.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductName:            macOS
ProductVersion:           13.1
BuildVersion:              22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/meeeeee/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.75
dynamic_background_opacity True
font_family                Comic Code Ligatures

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                meeeeee

This debug output has been copied to the clipboard
```

**Additional context**
I am using the default kitty.conf as it ships with the brew cask for kitty.

**Comment by page-down** [comment]
This is a bug in macOS 13, and there is nothing kitty can fix.

- Report it to Apple, I'm sure there are already enough user reports.
- Replace your own icon and compile kitty from source code. This will solve your problem right away.

https://sw.kovidgoyal.net/kitty/build/#building-kitty-app-on-macos-from-source
