### ISSUE TITLE
[help][macOS] No clipboard (Cmd+C/Cmd+V) support?

### ISSUE THREAD

**Issue by danylo-dubinin** [kovidgoyal/kitty#582]
Hello. I'm giving a try to Kitty, but I can't get the basic clipboard working. I've found these options in the config:
```
clipboard_control write-clipboard read-clipboard write-primary read-primary
```
but enabling it doesn't seem to affect anything. 

*How can I just select some text, copy and paste it?*

[macOS 10.12.6]

**Comment by kovidgoyal** [comment]
The keyboard shortcut to use for copy/paste is ctrl+shift+c to copy and ctrl+shift+v to paste. You can change it to whatever you like in kitty.conf.
