### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by tiudvek** [kovidgoyal/kitty#5823]
**Is your feature request related to a problem? Please describe.**
Yes. On Debian/Ubuntu, and many others, Kitty is outdated. I want to use Kitty, but the packages are too outdated.

**Describe the solution you'd like**
Update the packages.

**Describe alternatives you've considered**
Alacritty, Terminator, Tilix, ST.

**Additional context**
Kitty 0.19 is decent, but when I try to select text, it does not select the first 5 characters. And honestly, thats a deal breaker for me.

**Comment by kovidgoyal** [comment]
I am not a Debian maintainer, nor do I intend to become one. Use the
official kitty binaries instead of distro specific packages.
https://sw.kovidgoyal.net/kitty/binary/
