### ISSUE TITLE
Can't remap Alt+j

### ISSUE THREAD

**Issue by sheijk** [kovidgoyal/kitty#5826]
**Describe the bug**
I've bound alt+j in zsh to go to the parent directory. This works in most shells (Terminal.app, Gnome-terminal, etc.) but in Kitty pressing alt+j produces the symbol ∆. This is how OS X apps/text input behaves so I guess that's intentional.

I've tried following the steps [here](https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program) to remap this and got the following line:

`map alt+j send_text all \xc3\xa2\xc2\x88\xc2\x86`

However now pressing alt+j in zsh produces the string "Ã¢Â^ÈÂ^Æ".

**To Reproduce**
Put the following into ~/.zshrc

```
cd_parent () {
  builtin cd ..
  zle reset-prompt
  zle -R
}
zle -N cd_parent
bindkey "^[j" cd_parent
```

and the following into kitty.conf

```
map alt+j send_text all \xc3\xa2\xc2\x88\xc2\x86
```

Start zsh and press alt-j. In Terminal.app this goes to the parent dir, in Kitty it inserts "Ã¢Â^ÈÂ^Æ".

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin airblub 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.6.1 BuildVersion:	21G217
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/jr/.config/kitty/kitty.conf

Config options different from defaults:
shell_integration frozenset({'no-cursor'})
tab_bar_edge      1
tab_bar_style     slant
Added shortcuts:
	opt+j →  send_text all \xc3\xa2\xc2\x88\xc2\x86
Colors:
	background        #ffffff   
	foreground        #000000   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/jr/.opam/default/bin:/Users/jr/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
	LANG                                en_US.UTF-8
	EDITOR                              nano
	SHELL                               /bin/zsh
	USER                                jr
	XDG_CONFIG_DIRS                     /Users/jr/.nix-profile/etc/xdg:/run/current-system/sw/etc/xdg:/nix/var/nix/profiles/default/etc/xdg
	XDG_DATA_DIRS                       /Users/jr/.nix-profile/share:/run/current-system/sw/share:/nix/var/nix/profiles/default/share
```

**Comment by sheijk** [comment]
Note: I've enabled 'Use option as meta key' in Terminal.app. Without this all alt keybindings get passed to OS X's text input system there, too

**Comment by page-down** [comment]
> Note: I've enabled 'Use option as meta key' in Terminal.app. ...

Then also configure `macos_option_as_alt` in kitty, this will solve your problem without the need to use `send_text`.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt

**Comment by sheijk** [comment]
Thanks, that works. Thought that's already happening as Alt-f/b etc. work even without it
