### ISSUE TITLE
Segmentation fault on exit

### ISSUE THREAD

**Issue by aIRisius** [kovidgoyal/kitty#583]
Just downloaded kitty, launched and to close wrote `exit`.
Segmentation fault appears in terminal, where I launched kitty.

P.S.: Running on Ubuntu 18.04

**Comment by cyrinux** [comment]
Same thing here, on archlinux
`
...
[121283.728592] kitty[29080]: segfault at 6048dffd0cc0 ip 00006048dffd0cc0 sp 000075266a650118 error 14 in libXfixes.so.3.1.0[6048e0900000+5000]
[121284.435787] kitty[27690]: segfault at 6650ab66ccc0 ip 00006650ab66ccc0 sp 000075b57ed54d98 error 14 in libXfixes.so.3.1.0[6650abf9c000+5000]
...`

**Comment by kovidgoyal** [comment]
I cannot replicate on arch. I t would help if you posted an actual backtrace.

**Comment by aIRisius** [comment]
I'm running on Ubuntu 18.04.

![Some gif](https://user-images.githubusercontent.com/24653981/40620998-ae3130e6-62a3-11e8-99da-1b8ca389fa90.gif)

**Comment by kovidgoyal** [comment]
Again, a backtrace would help, an animation showing what you have already described is pretty useless :)

**Comment by aIRisius** [comment]
GDB stacktrace of `python /path/to/kitty`:
```
#0  0x00007ffff0051cc0 in ?? ()
#1  0x00007ffff596b7f1 in finalize.lto_priv () from /usr/share/kitty/kitty/fast_data_types.so
#2  0x0000000000426a02 in ?? ()
#3  0x0000000000441c22 in Py_Main ()
#4  0x0000000000421ff4 in main ()
```
Do you need output of some other debugger?

**Comment by kovidgoyal** [comment]
Build kitty with 

make debug

and then post the backtrace, that should tell me what I need tro know

**Comment by aIRisius** [comment]
```
#0  0x00007ffff0051cc0 in ?? ()
#1  0x00007ffff59180e8 in free_texture (tex_id=tex_id@entry=0x1920cf4) at /home/maxim/kitty/kitty/gl.h:80
#2  0x00007ffff5918231 in free_sprite_map (sm=0x1920cd0) at /home/maxim/kitty/kitty/shaders.c:52
#3  0x00007ffff5972a9c in del_font_group (fg=0xc7a6c0) at /home/maxim/kitty/kitty/fonts.c:364
#4  free_font_groups () at /home/maxim/kitty/kitty/fonts.c:372
#5  finalize () at /home/maxim/kitty/kitty/fonts.c:1157
#6  0x0000000000426a02 in ?? ()
#7  0x0000000000441c22 in Py_Main ()
#8  0x0000000000421ff4 in main ()
```
