### ISSUE TITLE
Make dimmed reversed text more clearly dimmed

### ISSUE THREAD

**Issue by ilyagr** [kovidgoyal/kitty#5831]
**Is your feature request related to a problem? Please describe.**
The problem is that in a file manager `lf`, we would like to dim the cursor in an inactive pane. We first tried to hardcode a gray color as its background, but that turned out to be invisible on some 16-colored themes.

**Describe the solution you'd like**

We'd like to use dimmed text for this, but currently the difference is not visible enough in Kitty.

Currently, for dimmed reversed text, Kitty only dims the background color. 
Here is a screenshot. Compare reversed non-dimmed text on the left with 
reversed dimmed on the right.

![image](https://user-images.githubusercontent.com/4123047/209764813-b8062884-8d8e-40fd-ab78-4aba161aa319.png)

I would like both background and foreground to be dimmed. Here's same situation in xterm.js. Alacritty behaves similalry.

![image](https://user-images.githubusercontent.com/4123047/209764922-f004c1c2-1eb4-44c5-948b-deba2d2be80d.png)

**Describe alternatives you've considered**
See above and the discussion in https://github.com/gokcehan/lf/issues/1038

**Additional context**
Thanks for making Kitty!

**Comment by kovidgoyal** [comment]
As far as I know DIM means dim only the foreground color, not foreground and background. See for example here: https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters

where dim is defined as decreased intensity which is exactly how it is implemented in kitty. It causes the foreground text to blend into the background color (decreased opacity for the foreground color). I dont even know what dim would mean for a background color. What color does the background color blend into?

If you want a grayed out look for a pane simply set the background and foreground colors using either 255 or true color escape codes. In kitty, you can even do it with a single escape code https://sw.kovidgoyal.net/kitty/deccara/

Am closing this as I dont really understand the request, but feel free to post further if needed.

**Comment by ilyagr** [comment]
I think you understood the request perfectly but think it's a bad idea. That's fair enough, thanks for your thoughts.

**Comment by p-ouellette** [comment]
Sorry for commenting on an old issue.
I agree that the xterm.js behavior of decreasing the opacity of both the foreground and background when using dim+reverse doesn't make much sense, but that's not what xterm, VTE, or Alacritty do either.
In those other terminals, with dim+reverse fg and bg are flipped, so the background becomes the dim fg color and the text becomes the bg color. However in Kitty, dim always affects the text color even with reverse set, which means dim+reverse isn't the reverse of dim. Maybe it would make sense for Kitty to always reduce the opacity of the foreground color, rather than reducing the opacity of the text color (which is fg color normally, bg color if reverse is set). This would be more consistent with xterm and VTE.

**Comment by ilyagr** [comment]
I'm no expert on what makes sense, but Paul's suggestion would make the dimmed attribute more useful to me.

**Comment by kovidgoyal** [comment]
Are you saying the algorithm for reverse+dim you want is

1) blend foreground and background into a new color call it dimmed
2) Set dimmed as the background
3) set the background as the foreground

I dont really see why that is preferable to

1) Reverse bg and fg
2) Blend new fg into new bg

Which looks better will depend very much on the colors involved. It *might* be worth doing but I would need to see a PR to decide. Relevant code is in cell_vertex.glsl

**Comment by p-ouellette** [comment]
Yes, that's accurate. The reason would be to make it possible to dim the background.
