### ISSUE TITLE
"page_down and page_up" overrides not only kitty behavior, but also programs opened inside kitty

### ISSUE THREAD

**Issue by Zeioth** [kovidgoyal/kitty#5839]
**Describe the bug**
map page_down scroll_page_down works correctly for kitty, but it also overrides pagination of vim. Which doesn't happen in other terms like foot.

**To Reproduce**
1.  kitty conf → map page_down scroll_page_down
2. run vim → try to paginate
3. Pagination keys won't work

**Comment by page-down** [comment]
After configuring a shortcut, kitty will perform the action and not send the keystroke event to the program in the window.
You can use kitten to check and choose whether to perform the action or send the keystroke.

https://sw.kovidgoyal.net/kitty/kittens/custom/#kittens-created-by-kitty-users
https://github.com/yurikhan/kitty-smart-scroll
