### ISSUE TITLE
Tab Padding/Margin?

### ISSUE THREAD

**Issue by johnallen3d** [kovidgoyal/kitty#584]
I may be missing something but I can't seem to find any options for padding around tabs. I'm using `chunkw` (with the border plugin) to indicate the active application and because the tab text is so close to the edge the first character is slightly cut off.

<img width="183" alt="kitty 2018-05-28 11-47-31" src="https://user-images.githubusercontent.com/184915/40622255-9e7ec454-626e-11e8-8feb-937910fa58b0.png">

Here's my complete [kitty.conf](https://gist.github.com/johnallen3d/9b13de956a90275cb391af8917cab24c).

**Comment by johnallen3d** [comment]
Wahoo!!! 🎉 👏 👍 

<img width="184" alt="kitty 2018-05-28 12-51-13" src="https://user-images.githubusercontent.com/184915/40623623-d5493094-6275-11e8-809b-e608781e09af.png">

**Comment by andersfylling** [comment]
Answer: add this to your kitty config "window_padding_width 4"
To whoever else ends up in this issue
