### ISSUE TITLE
[BUG] - Kitty receiving extra keystrokes after running pacman, read and gsettings commands

### ISSUE THREAD

**Issue by D3vil0p3r** [kovidgoyal/kitty#5843]
**Describe the bug**
In Arch Linux environment with GNOME 43 (Wayland), if on Kitty specific bash commands are run, some keystrokes (like `ENTER`) are automatically injected to Kitty. In particular, it occurs when a package is installed by pacman, the `read -p` statement is used and `gsettings` command is used for setting a new GTK theme. An example scenario is the following:

Let's suppose we have two GNOME 43 themes: 
* Graphite: https://www.gnome-look.org/p/1598493/ (Graphite-Dark.tar.xz that we can unzip and copy to `/usr/share/themes`)
* TokyoNight: https://www.gnome-look.org/p/1681315 (TokyoNight-Dark-BL.zip that we can unzip and copy to `/usr/share/themes`)

If we run `kitty --config=NONE` and run a script called `test.sh` with the following content:
```
#theme_name="Graphite-Dark"
theme_name="Tokyonight-Dark-B"
sudo pacman -Syy --noconfirm  nmap
read -p "Random string? Y/N" ans;
gsettings set org.gnome.desktop.interface gtk-theme $theme_name
```
Tokyonight-Dark-B will be applied on GTK windows and after this process, Kitty will suffer ENTER-like keystrokes:
![image](https://user-images.githubusercontent.com/83867734/210163700-f85f6b8d-ddb8-45ea-826a-c1582ad693b2.png)

Then, if we uncomment the first row of the script and comment the 2nd one in order to apply a different theme, and run the script, we get the same behavior.

This behavior occurs only on Kitty and not on other terminals. I tested it by BASH and FISH shell.

I would like to trace what are the specific keystrokes that are injected but I dont know if I can use `kitty --config=NONE -o linux_display_server=x11 kitty +kitten show_key -m kitty` along with a running bash script like the one above.

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

        url_color               #73daca   

Important environment variables seen by the kitty process:
        PATH                                /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/>
        LANG                                en_US.UTF-8
        VISUAL                              nano
        EDITOR                              /usr/bin/vim
        SHELL                               /usr/bin/fish
        DISPLAY                             :0
        WAYLAND_DISPLAY                     wayland-0
        USER                                athena
        LC_ADDRESS                          it_IT.UTF-8
        LC_IDENTIFICATION                   it_IT.UTF-8
        LC_MEASUREMENT                      it_IT.UTF-8
        LC_MONETARY                         it_IT.UTF-8
        LC_NAME                             it_IT.UTF-8
        LC_NUMERIC                          it_IT.UTF-8
        LC_PAPER                            it_IT.UTF-8
        LC_TELEPHONE                        it_IT.UTF-8
        LC_TIME                             it_IT.UTF-8
        XDG_RUNTIME_DIR                     /run/user/1000
        XDG_CURRENT_DESKTOP                 GNOME
        XDG_MENU_PREFIX                     gnome-
        XDG_SESSION_CLASS                   user
        XDG_SESSION_DESKTOP                 gnome-wayland
        XDG_SESSION_TYPE                    wayland

This debug output has been copied to the clipboard
```
If need more details, let me know.

**Comment by kovidgoyal** [comment]
kitty does not inject keystrokes. If you are seeing keystrokes they are
coming from the system. Easily verified by running

kitty --debug-input

**Comment by D3vil0p3r** [comment]
> kitty does not inject keystrokes. If you are seeing keystrokes they are coming from the system. Easily verified by running
> 
> kitty --debug-input

Ok, I tried, maybe they are not keystrokes because on the debug window, when the shell is repeating, I don't see any keystroke... strange fact.

**Comment by kovidgoyal** [comment]
Exactly, so its coming from one of the commands you ran.
