### ISSUE TITLE
Can't unlock OpenPGP using pass

### ISSUE THREAD

**Issue by Randalix** [kovidgoyal/kitty#5844]
If I want to use pass to unlock OpenPGP I get :
```
gpg: public key decryption failed: Screen or window too small
gpg: decryption failed: Screen or window too small
```
**To Reproduce**
1. `pass show xyz`
2. See error

This happens not with macOS Terminal and Alacritty.
**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin Gringotts 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.6.1 BuildVersion:	21G217
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/joe/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
copy_on_select       clipboard
enable_audio_bell    False
enabled_layouts      ['tall']
font_family          Hermit
font_size            13.0
open_url_with        ['[firefox]']
shell_integration    frozenset({'disabled'})
tab_bar_style        powerline
tab_powerline_style  slanted
window_border_width  (0, 'pt')
window_padding_width FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added shortcuts:
	ctrl+space →  launch --type=overlay zsh -ic "kitty @ ls | jq -r '.[0].tabs | map(.title) | .[]' | fzf | xargs -I _ kitty @ focus-tab --match title:_"
	kitty_mod+space →  combine : nth_window -1 : move_window_to_top
	opt+h →  launch --type=overlay --cwd=current
Colors:
	background           #1b1818   
	color0               #1b1818   
	color1               #ca4949   
	color10              #4b8b8b   
	color11              #a06e3b   
	color12              #7272ca   
	color13              #8464c4   
	color14              #5485b6   
	color15              #f4ecec   
	color2               #4b8b8b   
	color3               #a06e3b   
	color4               #7272ca   
	color5               #8464c4   
	color6               #5485b6   
	color7               #8a8585   
	color8               #655d5d   
	color9               #ca4949   
	cursor               #8a8585   
	foreground           #8a8585   
	selection_background #a06e3b   
	selection_foreground #1b1818   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                joe

```

**Additional context**
Same behaviour with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
Not sure what I can do about that. You would need to contact the
developers of pass.

**Comment by Randalix** [comment]
I'm sorry that I thought it was a kitt bug at first.. I got this impression because it works in the other terminal emulators I've tried.

**Comment by kovidgoyal** [comment]
No not really. That error is gpg failing to get the window size. kitty most definitely reports its window size correctly, as evidenced by the thousands of other programs that work in it. Why gpg is failing for you, only the gpg developers can tell you. I can tell you that gpg works fine in kitty for me.

**Comment by Randalix** [comment]
ok, thank you!

**Comment by glensc** [comment]
this could be arm64 issue or macos > 11, as I tried on this os and it works fine

```
kitty 0.27.1 () created by Kovid Goyal
Darwin vinagre.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H2026
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                *redacted*
	LANG                                en_US.UTF-8
	VISUAL                              /usr/local/bin/nvim
	EDITOR                              /usr/local/bin/nvim
	SHELL                               /usr/local/bin/bash
	DISPLAY                             /private/tmp/com.apple.launchd.8mdZw7fMDZ/org.macosforge.xquartz:0
	USER                                glen
	LC_TERMINAL_VERSION                 3.3.5beta2
	LC_CTYPE                            en_US.UTF-8
	LC_TERMINAL                         iTerm2
	LC_TIME                             et_EE.UTF-8

```

**Comment by glensc** [comment]
The `gpg` command pass invokes internally:

```
$ gpg -d --quiet --yes --compress-algo=none --no-encrypt-to $HOME/PasswordStore/token.gpg
$ gpg --version
gpg (GnuPG) 2.4.0
libgcrypt 1.10.1
```

**Comment by glensc** [comment]
is there way to see what gpg is trying to call to report the terminal size? i tried dtrace/truss. but failed to get anything useful from it.

```
$ sudo dtruss gpg -d --quiet --yes --compress-algo=none --no-encrypt-to $HOME/PasswordStore/token.gpg                  
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args)            = return
gpg: WARNING: unsafe ownership on homedir '/Users/glen/.gnupg'
gpg: public key decryption failed: Screen or window too small
gpg: decryption failed: Screen or window too small
```

**Comment by kovidgoyal** [comment]
No idea, I am not a macOS person. On Linux I would use strace -f, given the
age of gpg I would guess it is reading env vars. Try
the usual LINES/COLS nonsense that some shells thought was a good idea
way back when. Or just grep for that error message in the gpg source
code and see what leads to it. Or report the bug to the gpg developers.

**Comment by glensc** [comment]
fixed: tl;dr: `killall gpg-agent`

----

I tried `$LINES`, `$COLUMS`, also stty size, no luck

but I found something interesting. when trying to set `pinentry-program` in `~/.gnupg/gpg-agent.conf` and found that that stupidity doesn't re-read its config, so, I killed `gpg-agent` process and after that `pinentry-curses` started to work (re-tested with removing the config i added). like if the background process is started outside kitty terminal, for example iterm, it gives that nonsense error.

I found also existing bugs and questions:
- https://dev.gnupg.org/T5322
- https://unix.stackexchange.com/questions/635877/strange-error-with-gnupg-claims-no-secret-key-when-terminal-is-too-small

from there tried `pinentry-curses` directly and it works fine

```
$ pinentry-curses  
OK Pleased to meet you
getpin
D 123
OK
```

run with `-v` flag

```
$ gpg -v -d --quiet --yes --compress-algo=none --no-encrypt-to $HOME/PasswordStore/token.gpg
gpg: enabled compatibility flags:
gpg: public key is *redacted*
gpg: pinentry launched (26068 curses 1.2.1 /dev/ttys004 xterm-kitty /private/tmp/com.apple.launchd.*redacted*/org.xquartz:0 20620/502/4 502/20 0)
gpg: public key decryption failed: Screen or window too small
gpg: decryption failed: Screen or window too small

$ killall gpg-agent

$ gpg -v -d --quiet --yes --compress-algo=none --no-encrypt-to $HOME/PasswordStore/token.gpg
gpg: enabled compatibility flags:
gpg: public key is *redacted*
gpg: no running gpg-agent - starting '/opt/homebrew/Cellar/gnupg/2.4.0/bin/gpg-agent'
gpg: waiting for the agent to come up ... (5s)
gpg: connection to the agent established
gpg: pinentry launched (26093 curses 1.2.1 /dev/ttys004 xterm-kitty /private/tmp/com.apple.launchd.*redacted*/org.xquartz:0 20620/502/4 502/20 0)
gpg: AES256.CFB encrypted data
gpg: original file name=''
```

**Comment by julienmartinlevrai** [comment]
in my case I had to use `pinentry-tty`

```
$ cat .gnupg/gpg-agent.conf
pinentry-program /usr/bin/pinentry-tty
killall gpg-agent
```

and it worked.

**Comment by LaansDole** [comment]
I have also resolved this error of `Screen too small` on mac. I simply just `CMD + -` to resize the font on the terminal (I am using iTerm2) and re-run the command `gpg --full-generate-key`. It worked

**Comment by trinitronx** [comment]
Adding another workaround solution here (due to good SEO searching for this issue & #6018).

In my case, I was trying to use `gpg` + `pinentry-curses` or `pinentry-tty` _inside_ a docker container with Yubikey & `gpg-agent` running on the host and sockets volume mounted into the container.

It turns out that both `pinentry-curses` and `pinentry-tty` did not work for each their own reasons:

- `pinentry-curses` threw the error: `Screen or window too small` (Same as #6018)
  - In my case, I had no way of resizing the terminal larger on that machine.
- `pinentry-tty` seemed to launch, but hung
  - Probably due to [oddities of `GPG_TTY=$(tty)` inside the container][1] being different numbering & permissions from the host's `/dev/pts/NN` devices
  - It hung waiting for input from somewhere else... who knows which actual tty? :shrug:

# Workaround Solution: `--pinentry-mode=loopback`

The solution was to invoke the `gpg` inside the container with: `--no-autostart --pinentry-mode=loopback`

```console
docker run --rm \
  -v $SSH_AUTH_SOCK:/root/.gnupg/S.gpg-agent.ssh:rw -e SSH_AUTH_SOCK=/root/.gnupg/S.gpg-agent.ssh \
  -v $(gpgconf --list-dirs agent-extra-socket | tr -d '\n'):/root/.gnupg/S.gpg-agent.extra:rw \
  -v /run/user/1000/gnupg/S.scdaemon:/root/.gnupg/S.scdaemon:rw \
  -v $(gpgconf --list-dirs agent-socket | tr -d '\n'):/root/.gnupg/S.gpg-agent:rw \
  -ti ubuntu:22.04 /bin/bash

/# apt-get update -qq
/# apt-get install -yq gpg scdaemon
## Configure /root/.gnupg with secret key handles (`private-keys-v1.d`), `gpg.conf`, `gpg-agent.conf` settings
/# gpg -v --no-autostart --pinentry-mode=loopback  --clear-sign  /tmp/test-file-to-sign.txt
gpg: using pgp trust model
gpg: using "2689A459B1568D09" as default secret key for signing
gpg: using subkey 2689A459B1568D09 instead of primary key 187B4A9F09F02FCD
gpg: writing to '/tmp/test-file-to-sign.txt.asc'
Enter passphrase:
gpg: RSA/SHA512 signature from: "2689A459B1568D09 James Cuzella (lyraphase.com software signing key) <james.cuzella@lyraphase.com>"
```

Note that this solution was for an interactive use-case at the terminal.

For non-interactive, you'd probably want to use some other non-interactive method to input the PIN.

It turns out that GPG's `--passphrase-fd` flag works with `--pinentry-mode=loopback` to input the Yubikey smart card PIN by reading it from a file descriptor.

```console
# Example to read Yubikey's PIN from STDIN (file descriptor 0)
# read -s -p 'Enter SmartCard PIN: ' SC_PIN ; echo -n "$SC_PIN" | gpg -v --no-autostart --pinentry-mode=loopback  --clear-sign --passphrase-fd 0  /tmp/test-file-to-sign.txt
```

You can probably get creative with Docker's [Build Secrets][2] if doing this during a docker image build[^1]:

```Dockerfile
RUN --mount=type=secret,id=sc_pin \
    SC_PINFILE=/run/secrets/sc_pin \
    cat "$SC_PINFILE" | gpg -v --no-autostart --pinentry-mode=loopback  --clear-sign --passphrase-fd 0  /tmp/test-file-to-sign.txt
```

[^1]: Getting the `~/.gnupg/S.*` sockets into the _build container_ however, is another story...

[1]: https://github.com/containers/crun/issues/1158
[2]: https://docs.docker.com/build/building/secrets/
