### ISSUE TITLE
wayland error. can't open kitty

### ISSUE THREAD

**Issue by ryannewcomer** [kovidgoyal/kitty#5845]
**Describe the bug**
i am in window 11 wsl ubuntu and i use `sudo apt install kitty` and run kitty and get this :

**To Reproduce**
1. `sudo apt install kitty`
2. `sudo apt update && sudo apt upgrade`
3. `kitty`
4. see error

**Screenshots**
![image](https://user-images.githubusercontent.com/88273136/210173360-786704a3-5066-4422-91ff-c5d911914e7c.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
**can't use.**

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

i run that and :
![image](https://user-images.githubusercontent.com/88273136/210173500-20c3da27-0b77-4116-87cc-6ab542e63491.png)

**Comment by ryannewcomer** [comment]
![image](https://user-images.githubusercontent.com/88273136/210173569-48abdfb3-2b3d-4e84-8358-48049cdd527e.png)

**Comment by kovidgoyal** [comment]
Read the error message. You are missing libwayland-cursor.

**Comment by ryannewcomer** [comment]
thanks! I found i should install glfw. i can now open it. thanks
