### ISSUE TITLE
Doesn't launch on MacOS Ventura

### ISSUE THREAD

**Issue by remy727** [kovidgoyal/kitty#5849]
**Describe the bug**
kitty is not launching on MacOS Ventura.

**To Reproduce**
1. Install kitty by running `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin`
2. Open the kitty
3. It doesn't launch.

**Screenshots**
Shared the logs in the Console app.
![image](https://user-images.githubusercontent.com/69775411/210324679-7ef90228-cab0-41b4-bf80-2a4dd5107c7f.png)

**Comment by kovidgoyal** [comment]
That's an error from tccd which is a system process. Presumably
something is broken on your system, I'm not a macOS user so cant help you
much more, but, in general check if you have some third part kexts or
filter software or similar that is interfering.
