### ISSUE TITLE
Add Option to Enable Gamma-Corrected/SRGB Rendering

### ISSUE THREAD

**Issue by ewhac** [kovidgoyal/kitty#5850]
**Is your feature request related to a problem? Please describe.**
*[NOTE: I am ***not*** trying to start a fight about mathematically or perceptually correct rendering -- a fight that appears to inevitably break out whenever the topic of gamma-corrected font rendering is raised.]*

On X11 systems, even the best fixed-width outline fonts look thin and anemic.  Vertical stems in particular are dim.

Based on my own admittedly spotty and subjective research, the problem appears to be that gamma correction is not applied when rendering anti-aliased fonts.

**Describe the solution you'd like**
A configuration option in Kitty that will enable gamma-corrected or SRGB rendering.

**Describe alternatives you've considered**
Applying a gamma correction to the X display, either via `xgamma` or via `xrandr`.  However, this will affect the entire display, leaving everything (subjectively) too bright.

**Additional context**
I applied the following patch to Kitty:

```diff
diff --git a/kitty/gl.c b/kitty/gl.c
index 21435bd0..c667ef05 100644
--- a/kitty/gl.c
+++ b/kitty/gl.c
@@ -64,6 +64,7 @@ gl_init() {
             fatal("OpenGL version is %d.%d, version >= 3.3 required for kitty", gl_major, gl_minor);
         }
     }
+    glEnable (GL_FRAMEBUFFER_SRGB);
 }
 
 void
```

Here are the results.  Note that how these images appear to you will be affected by your own monitor's gamma settings, your desktop/display server gamma settings, and your browser's rendering.  In my case:
  * Monitor gamma: 2.2
  * X11 server gamma: 1.0
  * NVIDIA driver gamma: 1.0
  * X11 server dots-per-inch: 96

The font being used is [Iosevka Extended](/be5invis/Iosevka) v17, font size 9.  The first image is from stock Kitty; the second is with the patch applied.  Pay particular attention to the vertical stems, such as in lower-case 'm', 'n', and 'l':

![Screenshot_2023-01-03_11-29-58](https://user-images.githubusercontent.com/2722614/210430503-5831a2d2-62ea-4fd3-b659-fbe2422c8488.png) ![Screenshot_2023-01-03_11-30-17](https://user-images.githubusercontent.com/2722614/210430537-1887e3f5-a71f-4cd7-90e6-f33770408dcc.png)

Personally, I find the second image far more readable, and the stroke widths more uniform.

This solution, of course, has side-effects, most notably on color themes.  Here's Neovim running inside both Kittys, editing a Python file with the [Dracula theme](https://draculatheme.com/vim):

![Screenshot_2023-01-03_11-32-11](https://user-images.githubusercontent.com/2722614/210431708-bb4c2fef-71c9-4800-b05d-5906128edf66.png) ![Screenshot_2023-01-03_11-32-26](https://user-images.githubusercontent.com/2722614/210431747-ee69d079-fb5b-4e52-9a3b-a3f4573ab2d9.png)

The font rendering looks great, but now all the colors are far too bright.  So anyone using this option would have to "un-gamma" their various color themes.

Further Reading:  [Freetype.org: On Slight Hinting, Proper Text Rendering, Stem Darkening and LCD Filters](https://freetype.org/freetype2/docs/hinting/text-rendering-general.html).  This article is about eight years old, but is still largely relevant, and helps illustrate that rendering anti-aliased fonts well isn't so simple.

**Comment by ewhac** [comment]
Furhter further reading (turns out it's a deep topic):
  * https://learnopengl.com/Advanced-Lighting/Gamma-Correction
  * https://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/

**Comment by page-down** [comment]
I see there seems to be an open PR (5423) discussing this. You might want to try it.

**Comment by kovidgoyal** [comment]
dup of #5423

**Comment by ewhac** [comment]
> dup of #5423

(*visits PR*)
(*pulls PR into working tree*)
(*fixes merge conflicts*)
(*builds*)

Oooo!  Lovely!  I'll have that; thanks!
