### ISSUE TITLE
Draggable File Hyperlinks

### ISSUE THREAD

**Issue by 0xTadash1** [kovidgoyal/kitty#5851]
**Is your feature request related to a problem? Please describe.**
It is annoying to launch a GUI file manager every time to upload a file to the web or open in desktop app.

**Describe the solution you'd like**
Make `file://` texts or hyperlinks (e.g. **`ls --hyperlink`**) being able to drag-and-drop.\
For example, when a hyperlink for an image file is dragged from kitty and dropped it to some painting app, the painting app open it.

**Describe alternatives you've considered**

**Additional context**
Since there are tools such as [ripdrag](https://github.com/nik012003/ripdrag) and [dragon](https://github.com/mwh/dragon) that allow drag-and-drop without leaving the terminal as much as possible, I think there is a demand for them, though it may be small.

**Comment by kovidgoyal** [comment]
Not something I am interested in. Simply running open filename is a lot
easier and more efficient than drag and drop.

**Comment by trygveaa** [comment]
> Simply running open filename is a lot easier and more efficient than drag and drop.

That's not the same functionality though. If you want to e.g. upload a file to a web page, you can't run open filename, you have to drag it or open the file picker in the browser and select it. I've even encountered web pages which requires dragging the file, and doesn't have the option to open the file picker.

**Comment by kovidgoyal** [comment]
On Wed, Jan 04, 2023 at 02:21:47AM -0800, Trygve Aaberge wrote:
> > Simply running open filename is a lot easier and more efficient than drag and drop.
> 
> That's not the same functionality though. If you want to e.g. upload a file to a web page, you can't run open filename, you have to drag it or open the file picker in the browser and select it. I've even encountered web pages which requires dragging the file, and doesn't have the option to open the file picker.

Ah, websites trying to be applications, the greatest things since sliced
bread. I'm afraid that's too niche a usecase for me to bother, but I
will accept a PR that adds a mouse action for this.

**Comment by kovidgoyal** [comment]
A mouse action means a configurable action that performs the drag and drop. See https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

**Comment by kovidgoyal** [comment]
Implemented in master.
