### ISSUE TITLE
Second key mappings using DECCKM seems to overwrite the first 

### ISSUE THREAD

**Issue by bartheerman** [kovidgoyal/kitty#5857]
**Describe the bug**
I configured two mappings behind the same key (cmd+L). The second seems to overwrite the first.

**To Reproduce**

Configure two shortcuts:
```
map cmd+l send_text application APPLICATION
map cmd+l send_text normal NORMAL
```
Reload the config. On the shell prompt, type CMD-L. "Normal" appears.

Reconfigure the shortcuts as follows:
```
map cmd+l send_text normal NORMAL
map cmd+l send_text application APPLICATION
```
Reload the config. On the shell prompt, type CMD-L. Nothing happens, while "NORMAL" should appear.

**Comment by kovidgoyal** [comment]
Yes, you can only map one key to one action. If you need to dispatch a different key based on the current mode you will need to write a kitten to do it. It should be a very simple kitten. Something like

```
from kittens.tui.handler import result_handler
from kitty.keys import keyboard_mode_name

@result_handler(no_ui=True)
def handle_result(args: List[str], answer: str, target_window_id: int, boss: Boss) -> None:
    window = boss.active_window
    if window is not None:
           mode = keyboard_mode_name(window.screen)
           if mode == 'application':
                window.write_to_child('APPLICATION')
           elif mode == 'normal':
                window.write_to_child('NORMAL')

 ```
See https://sw.kovidgoyal.net/kitty/kittens/custom/

**Comment by bartheerman** [comment]
OK, Thx!

**Comment by kovidgoyal** [comment]
Indeed, with a kitten you dont even need to rely on keyboard names, you can use window.child.foreground_cmdline to condition the bytes you send based on the actual running foreground program.
