### ISSUE TITLE
Config option to disable font ligatures

### ISSUE THREAD

**Issue by mhartington** [kovidgoyal/kitty#586]
Hi there! I was wondering if you had any thoughts on disabling font ligatures through a config option?
I would happily submit a PR to support this, but curious if you are interested in this feature.

Also, where would be a good place in the code base to look into this?

**Comment by kovidgoyal** [comment]
Just use a font that does not have ligatures, the vast majority of monospace fonts do not.

**Comment by kovidgoyal** [comment]
Oh and if you do want to add such an option, the place to do it is fonts.c (you would basically need to pass options to harfbuzz to tell it not to use the various opentype features that are used to implement ligatures such as calt, liga etc.

**Comment by richin13** [comment]
How about a key binding for toggling font ligatures? Is that something that can be accomplished currently?

Sorry for commenting on an old issue

**Comment by Luflosi** [comment]
Unfortunately this is currently not possible.

**Comment by richin13** [comment]
I understand. Thank you
