### ISSUE TITLE
Please support secondary clipboard

### ISSUE THREAD

**Issue by asdf8dfafjk** [kovidgoyal/kitty#5861]
Like this: http://www.cs.man.ac.uk/~lindsec/secondary.html

**Comment by asdf8dfafjk** [comment]
This isn't entirely applicable in the sense that cursor doesn't move when doing primary selection in a terminal but one keypress + one mouse press + one mouse unpress + one key unpress is easier than 2 mouse press + mouse unpress cycles.

**Comment by kovidgoyal** [comment]
I'm afraid I am not interested in adding support for something X11
specific. And kitty already has support for infinite internal named
clipboards. https://sw.kovidgoyal.net/kitty/overview/#multiple-copy-paste-buffers

**Comment by asdf8dfafjk** [comment]
That makes sense. Thanks for reading.
