### ISSUE TITLE
specify to start in fullscreen from session file?

### ISSUE THREAD

**Issue by rionda** [kovidgoyal/kitty#5863]
This is a question: is there a way to specify in a session file that the OS window should be fullscreen?

I tried with `toggle_fullscreen` and `startaas fullscreen`, but it gives me errors.

More generally, it is unclear to me what commands can go in a session file (e.g., the [docs](https://sw.kovidgoyal.net/kitty/overview/#startup-sessions) use `focus_os_window` which is not documented anywhere).

**Comment by kovidgoyal** [comment]
Nope. Every command that can go in a session file is documented at https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

**Comment by ad-chaos** [comment]
In that case, would you mind changing
https://github.com/kovidgoyal/kitty/blob/397ac36011ac13cefef2c205ca6bc14563e3f4a0/docs/overview.rst?plain=1#L127-L130

to say something like the following, or something similar to it?
```rst
You can control the :term:`tabs <tab>`, :term:`kitty window <window>` layout,
working directory, startup programs, etc. by creating a *session* file and using
the :option:`kitty --session` command line flag or the :opt:`startup_session`
option in :file:`kitty.conf`. An example utilising all the options:
```

**Comment by rionda** [comment]
That seems a good idea. I would suggest: instead of "all the options", say "all the commands that can be used in a session file, including some specific only to such files".
