### ISSUE TITLE
Terminal ASCII table doesn't look right

### ISSUE THREAD

**Issue by farzadmf** [kovidgoyal/kitty#5864]
**Describe the bug**
I'm running `jest` tests, and they show a coverage table at the end, but the ASCII table doesn't look right in Kitty

**To Reproduce**
1. Open Kitty
2. Run a `jest test` command that produces the coverage table
3. See the table looking out of sorts

**Screenshots**
![kitty-terminal-table-issue](https://user-images.githubusercontent.com/5768792/211030584-cb000ae0-269c-4bd3-92ac-58928244cfbb.png)

Same output in Alacritty (which doesn't support ligatures):
![image](https://user-images.githubusercontent.com/5768792/211034058-e12cb451-ec17-4deb-a241-1cf277208bae.png)

Same output in WezTerm (which does support ligatures):
![image](https://user-images.githubusercontent.com/5768792/211034170-93abf9ba-5ff6-45c5-83f6-325d497df08f.png)

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin 88665a375db5.ant.amazon.com 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.6.2 BuildVersion:	21G320
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/farzadmf/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.9
dynamic_background_opacity True
enable_audio_bell          False
enabled_layouts            ['horizontal', 'fat', 'grid', 'vertical', 'splits', 'tall', 'stack']
font_family                Fira Code
font_size                  12.0
hide_window_decorations    2
macos_hide_from_tasks      True
macos_option_as_alt        3
macos_thicken_font         0.4
modify_font:
    baseline 3
    cell_height -3
    cell_width 90%
scrollback_pager           ['nvim', '--noplugin', '-u', 'NONE', '-c', 'silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - ']
term                       xterm-256color
window_padding_width       FloatEdges(left=15.0, top=5.0, right=15.0, bottom=5.0)
Added shortcuts:
	kitty_mod+opt+h →  previous_tab
	kitty_mod+opt+l →  next_tab
Changed shortcuts:
	kitty_mod+- →  change_font_size all -1.0
	kitty_mod+= →  change_font_size all +1.0
	kitty_mod+z →  kitten zoom_toggle.py
Colors:
	background                 #1d2021   
	color0                     #746960   
	color1                     #cc241d   
	color10                    #b8bb26   
	color11                    #fabd2f   
	color12                    #83a598   
	color13                    #d3869b   
	color14                    #8ec07c   
	color15                    #ebdbb2   
	color2                     #98971a   
	color3                     #d79921   
	color4                     #458588   
	color5                     #b16286   
	color6                     #689d6a   
	color7                     #a89984   
	color8                     #928374   
	color9                     #fb4934   
	cursor                     #93a1a1   
	foreground                 #ebdbb2   
	selection_background       #81908f   
	selection_foreground       #002831   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_CA.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.ZD1tnNcLWj/org.xquartz:0
	USER                                farzadmf
```

**Additional context**
Seems like doing `kitty --config NONE` doesn't have that issue
![image](https://user-images.githubusercontent.com/5768792/211066034-6b8d0d79-9c68-4de0-95cd-9adad5c5e88a.png)

but at the same, it doesn't seem to be using the font I'm using and everything, so not exactly sure what's happening

This might help as well from my config:
```
font_size 12.0
# font_family FiraCode Nerd Font Medium
# bold_font   FiraCode Nerd Font Bold

font_family Fira Code
# bold_font   Fira Code Bold

macos_thicken_font 0.40
macos_hide_from_tasks yes

modify_font cell_width 90%
modify_font baseline 3
modify_font cell_height -3px
```

**Comment by kovidgoyal** [comment]
1) Dont use patched fonts you dont need them with kitty https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

2) If you are going to modify cell sizes it will mess with alignment. And more generally, using ligatures for lines will mess with vertical alignment as well

**Comment by farzadmf** [comment]
Thank you @kovidgoyal for your answer.

> Dont use patched fonts
I thought I'm not doing that actually; I installed Fira Code using `brew install font-fira-code`, and I thought it should be the non-patched version (because I've also installed Fira Code NF and alike)

> If you are going to modify cell sizes it will mess with alignmen
I completely understand, however, without those, things seem a bit off in Kitty
![image](https://user-images.githubusercontent.com/5768792/211130060-3a85c12e-eb9f-486b-b223-b089520bc3f5.png)

![image](https://user-images.githubusercontent.com/5768792/211130067-f01501b4-66ea-48c7-bd14-fd9a47cc9606.png)

- In the first image, the characters seem to be too far apart, I like them to be closer to each other
- In the second image, if you look, the text and the icons seem to be bottom aligned, and adjust cell height seemed the way to go

As a comparison, similar screenshots with Alacirtty look like this:
![image](https://user-images.githubusercontent.com/5768792/211130162-a67acb1c-954d-4bbe-a0ac-a19ebcc9a102.png)

![image](https://user-images.githubusercontent.com/5768792/211130196-150ec183-7765-42ca-8983-d4c62fe7f7f6.png)
 
Maybe for the first image, it's just because the font itself seems a bit thicker compared to Kitty, but the second one is "center aligned" as you can see

**Comment by kovidgoyal** [comment]
You have to choose which is more important to you. If you adjust cell
sizes there is no way things can line up. Of course the proper solution
to this is to update jest to draw tables using Unicode box drawing
characters which always line up perfectly. They have existed for decades
and are very widely supported there is no reason not to use them
anymore.

**Comment by farzadmf** [comment]
> to update jest to draw tables using Unicode box drawing characters
Good point, but I don't think that's a solution I can do 😆

BTW, I disabled all those manipulations in my config, and the table still didn't align properly (not as bad as before, but still)

**Comment by kovidgoyal** [comment]
On Fri, Jan 06, 2023 at 08:59:48PM -0800, Farzad Majidfayyaz wrote:
> > to update jest to draw tables using Unicode box drawing characters
> 
> Good point, but I don't think that's a solution I can do 😆
> 
> BTW, I disabled all those manipulations in my config, and the table still didn't align properly (not as bad as before, but still)

Yes, with ligatures whether it aligns or not is a matter of luck. The
way ligatures work is that the terminal asks the font to render the
ligature in the combined space of all the cells for one line and in the
next line just the glyph for | is rendered in a cell. So there is no
intrinsic mechanism to line things up.

**Comment by farzadmf** [comment]
So, may I ask how come it looks aligned in WezTerm, which also uses ligatures (Alacritty doesn't support them, so that's a different story I guess)

**Comment by kovidgoyal** [comment]
Like I said it is a matter of luck. If things happen to align at the
fonts and sizes you choose, then they align.

**Comment by farzadmf** [comment]
> it is a matter of luck

WezTerm seems to be displaying those ligatures correctly in all the cases (at least I haven't seen an issue when using it), so maybe there's something involved other than luck maybe? 🤔

**Comment by kovidgoyal** [comment]
On Sat, Jan 07, 2023 at 01:00:38PM -0800, Farzad Majidfayyaz wrote:
> > it is a matter of luck
> 
> WezTerm seems to be displaying those ligatures correctly in all the cases (at least I haven't seen an issue when using it), so maybe there's something involved other than luck maybe? 🤔

If so, I cant think what it could be given what I know of font
rendering. But patches are most welcome, relevant code is in fonts.c

**Comment by farzadmf** [comment]
No worries, thank you for the discussion @kovidgoyal . I'm a Web developer, so I rather not try doing anything this low level 😆

For now at least, I ended up disabling ligatures, although it could be really nice to have them
