### ISSUE TITLE
Duplicated initial text in terminal

### ISSUE THREAD

**Issue by AleFarneda** [kovidgoyal/kitty#5866]
![image](https://user-images.githubusercontent.com/117171359/211153695-d72e0773-c095-463d-94b4-55373555d118.png)

![image](https://user-images.githubusercontent.com/117171359/211153765-25d87979-a730-42b7-9155-4208701a203c.png)

This happens to me since the very first day of using Kitty, ive tried to load different .conif but never goes away. Any ideas?

**Comment by kovidgoyal** [comment]
This will be something in your shell rc files. Bisect them to find out what.
