### ISSUE TITLE
Unbracketed pastes of > 1024 characters on macos drop or repeat characters

### ISSUE THREAD

**Issue by jimparis** [kovidgoyal/kitty#5869]
**Describe the bug**
Unbracketed pastes of > 1024 characters on macos drop or repeat characters.

I was originally trying to paste a large clipboard containing something like this into my shell, which has bracketed paste disabled:

```
cat >file.c <<EOF
/* Lots of C source code */
EOF
gcc -o file file.c
```
and it was as mess -- including dropped and repeated characters.

The same paste works fine in alacritty, so I don't suspect MacOS or the shell are at fault.

**To Reproduce**
1. `kitty --config NONE zsh -f -i`
2. Fill clipboard with more than 1024 bytes:
```
python3 -c 'print("\n".join([c * 64 for c in "abcdefghijklmnopqrs"]))' | kitty +kitten clipboard
```
3. Run a command at the prompt to ensure shell isn't interfering and that bracketed paste isn't being used:
```
cat >/tmp/testfile
```
4. Paste clipboard contents with ⌘V
5. Around the 1024 byte mark, characters are missing (the `pppp` line)  See screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/204930/211359215-4a429a1e-898a-4dea-8600-97e33461d8be.png)

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin XXXXXX 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.0.1 BuildVersion:		22A400
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                XXXXX
	LANG                                en_US.UTF-8
	VISUAL                              emacs -nw
	EDITOR                              emacs -nw
	SHELL                               /bin/bash
	USER                                XXXXX
```

**Comment by ad-chaos** [comment]
does not reproduce with `cat <<eof > /tmp/testfile`

**Comment by ppwwyyxx** [comment]
I'm running into a similar problem where clipboard contents seem to be broken after certain length.
To reproduce with `kitty -c NONE` using the latest nightly on a x64 debian machine:
```
seq 1 2000 > raw.txt
cat raw.txt| kitty +kitten clipboard
xclip -selection clipboard -o 
```

**Comment by kovidgoyal** [comment]
@ppwwyyxx this has nothing to do with the OP's bug, see https://github.com/kovidgoyal/kitty/commit/bf8d0c973243aaca7c26a9fd5583a7f399d5506f

As for the original bug I will look at it next time I am on a mac, I cant repro it in linux,.

**Comment by jimparis** [comment]
Thanks for looking into this.  That's interesting about the 1024 byte kernel buffer, however, I think there's still more going on here.  For example, I **do** see this when pasting directly into a shell, where the tty is in raw mode -- that's where I originally ran into it, and the `cat` was just an attempt as a simpler reproduction.

One useful finding is what @ad-chaos [edited to add above](https://github.com/kovidgoyal/kitty/issues/5869#issuecomment-1376035597): the data **does** make it into the file.  I see the same here.  So it's *not* actually being discarded by the kernel in that test!

Just to reiterate how bracketed paste affects it, and that it has problems pasting into raw-mode at the shell: if you fill the clipboard with the same contents (`aaaa`, `bbbb`, etc), and paste directly into zsh:
- With `set zle_bracketed_paste`, it works fine (lots of expected `command not found`)
- With `unset zle_bracketed_paste` -- the output is messy of course, but you can see that something got corrupted by looking at `history -20`:
```
   90  unset zle_bracketed_paste
   91  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
   92  bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
   93  cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
   94  dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
   95  eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
   96  ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
   97  gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
   98  hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
   99  iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
  100  jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
  101  kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
  102  llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
  103  mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
  104  nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
  105  oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
  106  ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppprrpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppsssssssssssssssss
```
That's more `p`s than we sent so this isn't just discarded data.

**Comment by jimparis** [comment]
In `Terminal.app`, the `cat` testcase shows the same behavior, but unbracketed pastes into `zsh` work fine.  So maybe the `cat` test is showing something different, like tty echo getting dropped in the kernel.  For pasting into shell: iTerm2, Alacritty,  and Terminal.app all work as expected.

**Comment by jimparis** [comment]
Yes, I can confirm that kitty appears to be passing the right data to `write()` and doing the right thing based on the return value.  It is weird that both bash and zsh show repeated/lost data.  That suggests some sort of kernel bug to me.

WezTerm works because it sends pastes in chunks of 1024 if the buffer is larger than that.  I don't think there's an explicit delay.
iTerm2 splits it up into 667 byte chunks with 15.3ms delay between them by default.
I don't know why alacritty and Terminal.app work.

**Comment by kovidgoyal** [comment]
On Tue, Jan 10, 2023 at 12:22:48PM -0800, Jim Paris wrote:
> Yes, I can confirm that kitty appears to be passing the right data to `write()` and doing the right thing based on the return value.  It is weird that both bash and zsh show repeated/lost data.  That suggests some sort of kernel bug to me.

Or it could be in the shells. Something like this should test it

```py
import tty, sys, os
tty.setraw(1)
while True:
    data = sys.stdin.buffer.read(1)
    if not data or data == b'\x0c':
        break
    sys.stdout.buffer.write(data)
```

> 
> WezTerm works because it sends pastes in chunks of 1024 if the buffer is larger than that.  I don't think there's an explicit delay.
> iTerm2 splits it up into 667 byte chunks with 15.3ms delay between them by default.
> I don't know why alacritty and Terminal.app work.

This will be all timing related.

**Comment by jimparis** [comment]
Yes, it is in the shells.  This script includes more output while the paste is coming in and still works fine with kitty:
```import tty, sys, termios
old = termios.tcgetattr(1)
try:
  tty.setraw(1)
  prompt = b'\x1b[0;1m>>> \x1b[0m'
  sys.stdout.buffer.write(prompt)
  while True:
    sys.stdout.buffer.flush()
    data = sys.stdin.buffer.read(1)
    if not data or data == b'\x03':
      break
    sys.stdout.buffer.write(data)
    if data == b'\r':
      sys.stdout.buffer.write(b'\n' + prompt)
finally:
  termios.tcsetattr(1, termios.TCSADRAIN, old)
  print()
```
