### ISSUE TITLE
backslash on mac does not work

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#587]
Typing backslash on my mac does not work, instead of a backslash it moves the cursor back. Forward slash works ok. I type `Option-Shift-7` on my Norwegian mac keyboard to type backslash. In the `vis editor` it prints out `<M-&>`. Without backslash i cannot escape chars in regular expressions.

**Comment by kovidgoyal** [comment]
Use send_text in kitty.conf to map whatever key press is being generated by your keyboard to send a backlash instead. See the default kitty.conf for examples. And if you want to debug the issue run kitty with GLFW_DEBUG_KEYBOARD=1 and look in glfw/cocoa_window.m for what is happening.

**Comment by kovidgoyal** [comment]
Oh, I forgot, since you are using a norwegian keyboard, you should turn off the macos_option_as_alt setting in kitty.conf
