### ISSUE TITLE
How to enable more than 1 font for ligature

### ISSUE THREAD

**Issue by iortego42** [kovidgoyal/kitty#5870]
I was reading all the wiki files and some github closed issues and I wonder if it's possible to make kitty to use ligature with more than 1 font or with a secondary font. The reason of that is because I have a personal font with uses ligatures for every icon it is on the font, but the font just have icons. Is there any way I can map this font or use it with another font_family font enabled?
In addition, when  I execute kitty +list-fonts my personal icon fonts does not appear

**Comment by kovidgoyal** [comment]
No, ligatures dont work with symbol_map fonts. And see the FAQ for why
your font wont appear.
