### ISSUE TITLE
Compile failed on macOS

### ISSUE THREAD

**Issue by akahanaton** [kovidgoyal/kitty#5874]
Hi, 

```
MacBook :: ~/Downloads/kitty ‹master*› % make                                                                                                          1 ↵
python3 setup.py 
[66/66] Compiling kitty/gl-wrapper.c ... done
[7/7] Linking launcher ... done
tools/cmd/completion/kitty_generated.go:7:8: //go:build comment without // +build comment
tools/cli/markup/prettify.go:13:2: //go:build comment without // +build comment
tools/tui/graphics/command.go:17:2: //go:build comment without // +build comment
make: *** [all] Error 1
```
I believe that comes from this command:
`/usr/local/bin/go build -v -ldflags '-X '"'"'kitty.VCSRevision=44866a6e79ae5562b392a4c36d53c407ac396bc0'"'"' -s -w' -o kitty.app/Contents/MacOS/kitty-tool /Users/mingwen/Downloads/kitty/tools/cmd`

I don't know GO at all, can you give me some hint to solve this, thanks

**Comment by kovidgoyal** [comment]
That error message makes no sense there are no go:build comments in any
of the referenced files. Are you using Go >= 1.19?

**Comment by akahanaton** [comment]
my go version is:
`go version go1.16.6 darwin/amd64 `

**Comment by akahanaton** [comment]
after upgrade Go to go1.19.4, the problem is solved, thanks a lot :)
