### ISSUE TITLE
load_config_file action not usable for remote control

### ISSUE THREAD

**Issue by otizonaizit** [kovidgoyal/kitty#5875]
I am trying to get rid of all my uses of tmux by heavily relying on kitty and its remote control features, a.k.a. `kitty @`.

I am trying to write a script which sets up up a special environment, and among other things needs to load a special configuration file. The script will be run from within a kitty window, so I don't want to start a new kitty instance with `kitty --config path_to_file`. A session file is not appropriate in this case, as I am doing things that can only be done within `kitty.conf`.

I noticed that I can map the action `load_config_file` to a keyboard shortcut, but the equivalent command is not available for use with kitty remote control with `kitty @`.

Is there a deep technical reason why this is the case or could `load_config_file` be added to the already amazing list of actions that can be triggered remotely?

Thanks for this terminal: after 20 years I am almost ready to give up xterm+tmux ;-)

**Comment by kovidgoyal** [comment]
Well, the reason is that config files have include directives that work
from the environment variables, local file paths, etc. They can also
refer to resources on the local filesystem. Remote control could be
coming from a remote system so those resources would not be available.

What is it you are trying to change in the config file exactly. Might be
possible to add remote control commands for that specifically if one
doesnt already exist.

**Comment by otizonaizit** [comment]
I am using `map` to have special keyboard shortcuts and reconfiguring the tab bar by setting `bell_on_tab`, `tab_activity_symbol`, `tab_title_template`, and `active_tab_title_template`...

**Comment by otizonaizit** [comment]
I'll describe my use case. I typically start a OS-window with kitty using a keyboard shortcut defined in my desktop environment. These kitties are started with `kitty --single-instance`, so they are fast and all share the same "daemon".

The general goal is to have a email-client running in one terminal os-window containing several tabs, each showing one email account. This email-client was until now a combination of tmux and several instances of mutt. I want this to become a combination of kitty and mutt.

On one of this os-window I start a script which creates several tabs. On each tab a mutt instance is started, one for each email account I use. This os-window needs to have a tab bar different from the one I use for normal kitty os-windows: it shows just the title and a bell-symbol (mutt takes care of setting the title to the name of the mail account). It also needs special keyboard-shortcuts, which are used to send global keystrokes to all mutts. For example, `ctrl+q` in this window sends `q` to mutt, which then triggers all running mutts to quit. `ctrl+s` sends `s` to mutt, to force all running mutts to do a IMAP re-syncing . But of course I want `ctrl+q` and `ctrl+s` in other terminals to still be the usual terminal output "freeze"/"unfreeze" keystrokes.

When using tmux I just start it in the script by loading a special configuration file, and then let tmux create windows with mutts. All the configuration happens in the special tmux configuration file.

To get rid of tmux, I can use kitty to create tabs and run mutt inside them, but at the moment the script needs to be called from a specially crafted kitty, started by another kitty terminal by passing the `--config` option. My goal is to start my "email client" buy just calling the script in an arbitrary kitty os-window, without having to first start a special kitty.

The whole thing seems super complicated when I write it, but it is quite neat and easy to use in practice ;-)

**Comment by kovidgoyal** [comment]
Yeah for this case you have to launch a new instance of kitty there's no
way to set mappings and tab bar properties for just one OS Window.  You
can have your script launch a new kitty instance and then quit. Or map a
different shortcut in your window manager to run kitty with the
appropriate command line flags.

**Comment by page-down** [comment]
@otizonaizit
> My goal ... just calling the script in an arbitrary kitty os-window ...

Your goals are achievable, however there is indeed no easy way to do it, it is complicated.

Write a kitten that sets a special property to mark the current OS window as special purpose. Or just launch a new OS window and set the flag.

> ... have a tab bar different from ...

Configure `tab_bar_style custom` and check if the current window is a special OS window when drawing and apply a different `title_template`.

See the following discussion to learn how to write your own tab bar.
https://github.com/kovidgoyal/kitty/discussions/4447

> ... needs special keyboard-shortcuts ...

If you have few special keys, then you can write a kitten to check if you are currently in a special OS window and perform the corresponding action. Bind all the keys involved to that wrapper kitten.

See the following project to learn how to perform different actions conditionally.
https://github.com/yurikhan/kitty-smart-scroll

If you have more shortcuts, then perhaps you can use the global watcher feature to swap the full set of keys or any configuration when switching OS windows.
However this would make things complicated and a bit expensive.
