### ISSUE TITLE
activity_symbol is unconditionally shown in tabs with multi-window layouts

### ISSUE THREAD

**Issue by lyokha** [kovidgoyal/kitty#5881]
**Describe the bug**
`activity_symbol` is unconditionally shown in tabs with multi-window layouts. Even in the active window.

**To Reproduce**

1. The minimal config
   ```
   tab_activity_symbol         " "
   ```
   (this is a `bell` from the Nerd fonts, but you can put here anything.)
2. Open kitty.
3. Open a new window (`ctrl+shift+enter`).
4. Open a tab (`ctrl+shift+t`). Now the activity symbol (a red bell) is shown at the first tab title. Which seems to be wrong.
5. Open a new window in the current tab (`ctrl+shift+enter`). Now even the active tab shows the activity symbol in the title.

**Screenshots**

![kitty](https://user-images.githubusercontent.com/1219667/212149861-52dd2ce0-5d20-4108-a681-075496dc1707.png)

**Environment details**
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

```
kitty 0.26.5 created by Kovid Goyal
Linux localhost.localdomain 6.0.18-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:10:00 UTC 2023 x86_64
S
Kernel 6.0.18-300.fc37.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/lyokha/.config/kitty/kitty.conf

Config options different from defaults:
tab_activity_symbol  S

Important environment variables seen by the kitty process:
	PATH                                /home/lyokha/.cabal/bin:/home/lyokha/perl5/bin:/home/lyokha/.local/bin:/home/lyokha/bin:/home/lyokha/geant4/bin:/home/lyokha/.local/bin:/home/lyokha/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/opt/puppetlabs/bin
	LANG                                ru_RU.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                lyokha
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 mate
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 MATE
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/lyokha/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

On older versions of kitty, run kitty --debug-config instead

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by lyokha** [comment]
Here is even a simpler scenario:

1. Open kitty.
2. Open the second tab -> tab bar appears, the first tab has the activity symbol!
3. Now open the second window in the current (second) tab -> the activity symbol appears in the current (active) tab!
4. After visiting all windows in all tabs (with `ctrl-shift-]` and `ctrl-shift-left`) the activity symbols disappear.

**Comment by kovidgoyal** [comment]
That is to be expected. An activity symbol is drawn when kitty receives data from the child program running in a window that is not focused. When the tab bar first appears the window is resized, causing your shell to redraw the prompt causing activity. Similarly when a second window is opened, the first window in the tab is resized unless you use the stack layout.

**Comment by lyokha** [comment]
Thanks! This works perectly!
