### ISSUE TITLE
Add commands to get and set scrollback in a window/tab

### ISSUE THREAD

**Issue by mrzv** [kovidgoyal/kitty#5887]
**Is your feature request related to a problem? Please describe.**
I'm contemplating whether it's possible to create a very simple terminal multiplexer, integrated with kitty. I'm imagining something like [dtach](https://github.com/crigler/dtach), but that saves and restores scrollback. I wonder if this would be simple to do if there were commands like `kitty @ get-scrollback` and `kitty @ set-scrollback`. The former would be called when detaching; the latter, when reattaching.

**Describe the solution you'd like**
Add commands `kitty @ get-scrollback` and `kitty @ set-scrollback` that would do what they say for the current window/tab.

**Describe alternatives you've considered**
The closest I found to what I want is [tab-rs](https://github.com/austinjones/tab-rs/). It's usable, but has some bugs and seems a little more complicated compared to `dtach`. Some of the complexity (and bugs) come from scrollback management, which kitty already does.

**Comment by kovidgoyal** [comment]
kitty @ get-text --help

As for setting scrollback you simply send the text over the tty device
or use

kitty @ send-text --help

**Comment by mrzv** [comment]
Great! Any chance for a short example. I'm not following "The text follows Python escaping rules. So you can use escapes like \x1b to send control codes." in the `send-text` documentation.

If I get something via:
```
kitty @ get-text --ansi > out
```
and it includes for example an image, how do I send it back with `send-text`?

**Comment by kovidgoyal** [comment]
cat out

or

kitty @ send-text --from-file out

But images are not supported.

**Comment by mrzv** [comment]
`cat out` works (without images). `kitty @ send-text --from-file out` fills screen with gibberish.

Are images completely off the table? Can this issue become "add support for images" in `send-text`, or some more explicit `set-scrollback` command?

**Comment by kovidgoyal** [comment]
Not something I care to implement. Storing images in text streams is
extremely inefficient.
