### ISSUE TITLE
Fullscreen on Gnome 3.28

### ISSUE THREAD

**Issue by xvzf** [kovidgoyal/kitty#589]
The fullscreen mode does not seem to work in the latest gnome release on linux. When switching workspaces and going back to the workspace where kitty is in fullscreen mode, it does not focus and also block the view of other workspaces when switching again!

It can be replicated e.g. with the latest ubuntu 18.04 release!

**Comment by kovidgoyal** [comment]
You should report this to the glfw project (the toolkit kitty uses). Or just use whatever native fullscreen capability your window manager provides.
