### ISSUE TITLE
Launch kitty in a new process

### ISSUE THREAD

**Issue by MihailoIsakov** [kovidgoyal/kitty#5898]
**Is your feature request related to a problem? Please describe.**
I heavily use the `launch --cwd=current --copy-env --type=os-window` command to clone a terminal in the same directory with the same active virtual environment. Typically I either am in the terminal, or in nvim. Right now, I believe kitty opens the new window as a child process, so running xprop on either the original or the new kitty window will return the parent kitty PID (`_NET_WM_PID(CARDINAL)` field). This prevents me from knowing which kitty process is focused.

Additionally, it seems that all children processes share the zoom level, so I cannot launch a new kitty instance, move it to e.g., a lower DPI monitor and modify only its zoom level without also modifying the parent.

**Describe the solution you'd like**
Adding a `--detach-process` flag to the  `launch` command would help distinguish between different kitty terminals.

**Describe alternatives you've considered**
Right now, I have to quit nvim to run a command to start a detached kitty instance.
When I want to have different zoom levels on different terminals, I have to start a new detached instance and navigate to the right location, activate venvs, etc.

Is there a smarter way of acomplishing this, and am I missing something?

**Comment by kovidgoyal** [comment]
Every OS window can have its own font size.
https://sw.kovidgoyal.net/kitty/conf/#font-sizes


And use the KITTY_WINDOW_ID env var to distinguish windows.
