### ISSUE TITLE
Releasing mouse outside Kitty while dragging leaves the dragging mode stuck on

### ISSUE THREAD

**Issue by koterpillar** [kovidgoyal/kitty#59]
How to reproduce:
* Have a wall of text in Kitty
* Start selecting it
* Holding the mouse, move it outside Kitty window
* Release the mouse button
* Move the mouse back inside

Actual behavior:
* Once the mouse is back in, even though it's not pressed, the selection continues to update. The only way to leave selection mode is press and release the mouse button again.

Expected behavior:
* The selection doesn't keep changing when moving the mouse back inside Kitty window.

Termite and XTerm continue tracking the mouse outside their windows, and copy it when the mouse button is released, even outside.

**Comment by kovidgoyal** [comment]
Tracking mouse events outside the application window is an artifact of the X window systems complete lack of security. It will go away once linux moves to wayland. In other words it is X specific behavior. As such, I have no interest in implementing it in kitty.
