### ISSUE TITLE
alt+shift+, and alt+shift+. absorbed by kitty with no way to unmap this behaviour

### ISSUE THREAD

**Issue by sirwobin** [kovidgoyal/kitty#5901]
**Describe the bug**
Kitty appears to be using shift+alt+. and shift+alt+, and it does not appear to be possible to unmap that behaviour.  When these keys are typed at a command prompt, some text that may be related to previous commands appears to be pasted.  I have tried both of the following in my kitty.conf with no observed change:

```
map shift+alt+. no_op
map shift+alt+, no_op
```
in case the order of modifiers was important I also tried

```
map alt+shift+. no_op
map alt+shift+, no_op
```

I have mapped this key sequence in my editor but the editor cannot receive these key presses.  If I switch to alacritty with no other changes at all to my environment, the editor can receive those key sequences correctly.

**To Reproduce**
1. Run vim or nvim
2. Create a vim key binding such as `:map <A->> <Cmd>echo 'yay'<CR>` and `:map <A-<> <Cmd>echo 'yipee'<CR>`
3. Press key sequence alt+shift+. which should print the text 'yay' in the command line at the bottom of the screen.
4. No text appears at the bottom of the screen.  Other strange behaviour may result depending on what text is injected by kitty. (first way to see the bug)
5. Quit vim with `:q`
6. On the command line enter the key sequence and see some reaction which is not dependent on the editor.  Sometimes text appears that might have been a previous command. (second way to see the bug)

**Screenshots**
n/a

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Linux rl-nixtop 5.15.86 #1-NixOS SMP Sat Dec 31 12:14:48 UTC 2022 x86_64

<<< Welcome to NixOS 23.05pre440068.a518c771485 (x86_64) - /dev/tty >>>

Run 'nixos-help' for the NixOS manual.

DISTRIB_CODENAME=stoat
DISTRIB_DESCRIPTION="NixOS 23.05 (Stoat)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="23.05"
LSB_VERSION="23.05 (Stoat)"
Running under: X11
Frozen: False
Paths:
  kitty: /nix/store/4r5zlcrmacc04mg4a4s4j1rrclnlvfmm-kitty-0.26.5/bin/kitty
  base dir: /nix/store/4r5zlcrmacc04mg4a4s4j1rrclnlvfmm-kitty-0.26.5/lib/kitty
  extensions dir: /nix/store/4r5zlcrmacc04mg4a4s4j1rrclnlvfmm-kitty-0.26.5/lib/kitty/kitty
  system shell: /run/current-system/sw/bin/zsh
Loaded config files:
  /home/robin/.config/kitty/kitty.conf

Config options different from defaults:
font_family Fantasque Sans Mono
font_size   20.0

Important environment variables seen by the kitty process:
        PATH                                /nix/store/4r5zlcrmacc04mg4a4s4j1rrclnlvfmm-kitty-0.26.5/bin:/nix/store/3q6hxl7cxk9cn5s3xm5359w29010yv5h-imagemagick-7.1.0-57/bin:/nix/store/nd9lrc8pqsib5bz9l1i224jgs6ljxykg-ncurse>
        LANG                                en_GB.UTF-8
        EDITOR                              nano
        SHELL                               /run/current-system/sw/bin/zsh
        DISPLAY                             :0
        USER                                robin
        XDG_CONFIG_DIRS                     /etc/xdg:/home/robin/.nix-profile/etc/xdg:/etc/profiles/per-user/robin/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
        XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
        LC_ADDRESS                          en_GB.UTF-8
        LC_NAME                             en_GB.UTF-8
        LC_MONETARY                         en_GB.UTF-8
        XDG_SEAT                            seat0
        XDG_SESSION_DESKTOP                 none+i3
        XDG_SESSION_TYPE                    x11
        XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/robin
        LC_PAPER                            en_GB.UTF-8
        XDG_CURRENT_DESKTOP                 none+i3
        XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
        XDG_SESSION_CLASS                   user
        LC_IDENTIFICATION                   en_GB.UTF-8
        LC_TELEPHONE                        en_GB.UTF-8
        LC_MEASUREMENT                      en_GB.UTF-8
        XDG_VTNR                            7
        XDG_SESSION_ID                      1
        XDG_RUNTIME_DIR                     /run/user/1000
        LC_TIME                             en_GB.UTF-8
        XDG_DATA_DIRS                       /nix/store/3qa3jwjknjwp0k66v25rmwc2f606yfzj-desktops/share:/home/robin/.nix-profile/share:/etc/profiles/per-user/robin/share:/nix/var/nix/profiles/default/share:/run/current-system>
        LC_NUMERIC                          en_GB.UTF-8
```

**Additional context**
The problem also exists when `kitty --config NONE` is used.

**Comment by kovidgoyal** [comment]
I cannot reproduce, steps I tried

1) Run kitty --config=NONE
2) Run showkey -a
3) Press alt+shift+.
4) Got expected output

```
^[> 	27 0033 0x1b
 	    62 0076 0x3e
```
5) Now try it with the kitty keyboard protocol
6) kitty +kitten show_key -m kitty
```
Shift+Alt+. PRESS
CSI 46 : 62 ; 4 u
Shifted key: >
```
Also as expected.

And with neovim --clean

1) enter insert mode
2) press ctrl-v
3) press alt+shift+.
4) get <M-S-.> as expected.

You need to bind that not <A->> or open a bug report with neovim asking
it to add support for shifted keys.

As for vim it just recently got support for the kitty keyboard protocol
but that support is full of bugs, you should report it there.
