### ISSUE TITLE
kitty does not use ControlMaster socket for transferring files

### ISSUE THREAD

**Issue by nick-robo** [kovidgoyal/kitty#5902]
**Describe the bug**

When editing, opening or saving a file on a remote host that is connected to through ssh multiplexing, kitty will open a new connection to the server, prompting, in my case, a 2FA request to be triggered.

**To Reproduce**
1. Disable `share_connections`, since it interferes with my prior `ssh` config.
2. Connect to the host using the ssh kitty.
3. Click a remote file link and choose to save, edit or open.
4. kitty opens a new connection and causes a new 2FA request to be triggered.

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Linux nick-latitude5430 6.1.6-arch1-3 #1 SMP PREEMPT_DYNAMIC Mon, 16 Jan 2023 12:51:23 +0000 x86_64
EndeavourOS Linux 6.1.6-arch1-3 (/dev/tty)

DISTRIB_ID=EndeavourOS
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME=rolling
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/nick/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select clipboard
font_family    Hack Nerd Font Mono
font_size      16.0
shell          fish
Colors:
	background     #282a36   
	foreground     #eff0eb   

Important environment variables seen by the kitty process:
	PATH                                /home/nick/.local/bin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_AU.UTF-8
	EDITOR                              vim
	SHELL                               /usr/bin/fish
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                nick
	LC_ADDRESS                          en_AU.UTF-8
	LC_IDENTIFICATION                   en_AU.UTF-8
	LC_MEASUREMENT                      en_AU.UTF-8
	LC_MONETARY                         en_AU.UTF-8
	LC_NAME                             en_AU.UTF-8
	LC_NUMERIC                          en_AU.UTF-8
	LC_PAPER                            en_AU.UTF-8
	LC_TELEPHONE                        en_AU.UTF-8
	LC_TIME                             en_AU.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland

```

**Additional context**

My ssh config looks like this.

```
Host *
  ControlPath ~/.ssh/%r@%h:%p

Host jump
  HostName hostname.org
  User user
  # localforward ports
  ...
  ControlMaster auto
  ControlPersist 1h

Host target
  HostName target
  User user
  ProxyJump jump
```

**Comment by kovidgoyal** [comment]
kitty knows nothing about your ssh configuration, so how is it supposed
to re-use the ControlMaster. If you want ControlMaster re-use, use the
ssh kitten with share_connections enabled.

**Comment by nick-robo** [comment]
Unfortunately, `share_connections` did not work as expected when interacting with a jump server and forwarding ports, therefore I had to turn off the setting. 

Clearly, kitty reads `.ssh/config` because when using the ssh kitten it uses my configuration. The ssh kitten has no problems using my configuration when opening new connections to the server while reusing the ControlMaster socket.

I do not see why it shouldn't be able to do so with the file transfers.

**Comment by kovidgoyal** [comment]
On Wed, Jan 18, 2023 at 09:26:59PM -0800, Nick R. wrote:
> Unfortunately, `share_connections` did not work as expected when interacting with a jump server and forwarding ports, therefore I had to turn off the setting. 

the ssh kitten runs ssh, I dont see how using jump servers matters could
matter to it.

> 
> Clearly, kitty reads `.ssh/config` because when using the ssh kitten it uses my configuration. The ssh kitten has no problems using my configuration when opening new connections to the server while reusing the ControlMaster socket.

Nope, the ssh kitten runs ssh it does not read ssh/config. 

> 
> I do not see why it shouldn't be able to do so with the file transfers.

Because I have zero interest in implementing an ssh config file parser.

**Comment by nick-robo** [comment]
> Nope, the ssh kitten runs ssh it does not read ssh/config.

What does it do when initiating a file transfer? If it was just using, it wouldn't be creating a new connection because ssh would just use ControlMaster again.

> Because I have zero interest in implementing an ssh config file parser.
This doesn't seem necessary. All it has to do is use `ssh` in all circumstances.

**Comment by kovidgoyal** [comment]
On Wed, Jan 18, 2023 at 09:40:13PM -0800, Nick R. wrote:
> > Nope, the ssh kitten runs ssh it does not read ssh/config.
> 
> What does it do when initiating a file transfer? If it was just using, it wouldn't be creating a new connection because ssh would just use ControlMaster again.

Remote file transfers require multiple roundtrips, therefore it
uses its *own* control master since it has no way of knowing you have
setup control masters, unless you use the ssh kitten.

> 
> > Because I have zero interest in implementing an ssh config file parser.
> 
> This doesn't seem necessary. All it has to do is use `ssh` in all circumstances. 

It is necessary. I suggest instead of asserting what is necessary or
not you actually read the code or better yet send a PR.

**Comment by nick-robo** [comment]
> uses its *own* control master since it has no way of knowing you have
> setup control masters, unless you use the ssh kitten.

I am using the ssh kitten, as stated in the original post.

> It is necessary. I suggest instead of asserting what is necessary or
> not you actually read the code or better yet send a PR.

I wasn't asserting, just reflecting on the fact that using `ssh` (via the ssh kitten) after my first connection functions as expected, no login required. Sorry if it came off that way.

Furthermore, I don't really have the time nor expertise to submit a PR, hence the bug report to let you know about the issue.
