### ISSUE TITLE
Some keys such as Enter, Backspace produce weird output after running external commands in vim then quitting

### ISSUE THREAD

**Issue by tricarte** [kovidgoyal/kitty#5903]
This is probably related to my setup. But I don't know which setting of vim (or kitty) causes this. After running external commands in vim with the exclamation mark and quitting, if I press Enter, Backspace or Ctrl+L to clear the screen, weird characters appear. Normal characters, numbers and spacebar work as usual. Tested in other terminals and it's OK with them.

It happens also with `kitty --config NONE`.

**Video**

https://user-images.githubusercontent.com/3023026/213424656-20fafe00-df82-4725-9dac-f203a290037c.mp4

**Comment by kovidgoyal** [comment]
That is a bug in vim not restoring the keyboard mode on exit.

**Comment by tricarte** [comment]
I just compiled the latest version of vim (v9.0.1221) and it looks it's already fixed. Sorry.
