### ISSUE TITLE
cannot move kitty windows on macos without decorations using easy move & resize app

### ISSUE THREAD

**Issue by alzedd** [kovidgoyal/kitty#5905]
**Describe the bug**
Basically, what I do is use this app on mac which mimics the alt + click for moving windows and alt + right click for resizing like I used to do on linux.
Using  `hide_window_decorations yes` and alt + click on the kitty windows does nothing because I think mouse events are catched and they not _bubble up_ (sorry for my English :P )

**To Reproduce**
1. empty kitty.conf with just `hide_window_decorations yes` or ` hide_window_decorations titlebar_only`
2. install easy move & resize app
3. try to move or resize kitty
4. See error ==> nothing happens

edit:  https://github.com/dmarcotte/easy-move-resize

**Comment by kovidgoyal** [comment]
Yes, there is an existing discussion of this. It's not something I care
to spend time on, patches welcome.
