### ISSUE TITLE
kitty_mod+j not working with fish shell integration

### ISSUE THREAD

**Issue by Schweber** [kovidgoyal/kitty#5906]
**Describe the bug**
I can define keybindings for ctrl+alt+j and ctrl+alt+k successfully with shell integration disabled. As soon as i enable shell integration (i am using `fish` shell) they no longer work. Other shortcuts like ctrl+alt+w, ctrl+alt+l etc. still work as expected.

**To Reproduce**
1. add the following to `kitty.conf`:`kitty_mod ctrl+alt`, `map kitty_mod+j scroll_page_down`, `map kitty_mod+J scroll_end` and `shell_integration enabled`.
2. restart kitty
3. ctrl+alt+j/J will no longer work

**Environment details**
```
Ctrl+Shift+F6 brings up the last command, not the debug info. `kitty --debug-config` does not work either.
```

**Additional context**
The problem can't be reproduced with `kitty --config NONE` as the shell integration is disabled by default.

**Comment by kovidgoyal** [comment]
Then your issues are caused by Nix. Use the official binary, I'm afraid
I dont have the time/interest to debug things broken by distributors.

And the default for shell_integration is enabled:
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.shell_integration
