### ISSUE TITLE
[syntax highlighting] wrong color / unreadable

### ISSUE THREAD

**Issue by tjallemaal** [kovidgoyal/kitty#5907]
As in title;
not sure what I'm doing wrong.
in latex, the highlighting is identical with font color in 'subscript/superscript' -environments.

It may be a vim issue ...
see line 1:
<img width="461" alt="Screenshot 2023-01-20 at 12 04 04" src="https://user-images.githubusercontent.com/69585777/213726748-b214bdbd-6a8c-49cf-b797-2bccc8664c0e.png">

bug report:

kitty 0.23.1 created by Kovid Goyal
Darwin 
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H2026
Loaded config files:
  /Users/brian/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.9
font_size               14.0
Colors:
	active_border_color     #e7e7e7   
	active_tab_background   #3a3d41   
	active_tab_foreground   #ffffff   
	background              #1e1e1e   
	color1                  #f14c4c   
	color10                 #0dbc79   
	color11                 #e5e510   
	color12                 #2472c8   
	color13                 #bc3fbc   
	color14                 #11a8cd   
	color15                 #e5e5e5   
	color2                  #23d18b   
	color3                  #f5f543   
	color4                  #3b8eea   
	color5                  #d670d6   
	color6                  #29b8db   
	color7                  #e5e5e5   
	color8                  #666666   
	color9                  #cd3131   
	cursor                  #ffffff   
	cursor_text_color       #1e1e1e   
	foreground              #cccccc   
	inactive_border_color   #414140   
	inactive_tab_background #1e1e1e   
	inactive_tab_foreground #858485   
	selection_background    #264f78   
	selection_foreground    #cccccc

**Comment by kovidgoyal** [comment]
This will be an issue in whatever program is doing the syntax highlighting. kitty uses whatever colors it is told to use.
