### ISSUE TITLE
xcape  (keyboard modifier under Linux) does not work with Kitty

### ISSUE THREAD

**Issue by mlongval** [kovidgoyal/kitty#5909]
Hi there.
I just started using Kitty a few days ago. Very nice project! Congratulations!
I have a problem however.
I have used 'xcape' for years now to map a tap on the CapsLock key to ESC with this:

```
# make CapsLock behave like Ctrl:
setxkbmap -option ctrl:nocaps
# make short-pressed Ctrl behave like Escape:
xcape -e 'Control_L=Escape'
```
The setxkbmap part works (ie CapsLock becomes Ctrl), but the 'xcape' part does not (ie tapping the CapsLock - now Ctrl - does not issue an ESC.

I use this all the time in Zsh and Vim.

Is there any way of fixing this problem.

Thanks for any help, and thanks again for a great terminal emulator!

Cheers from Canada!

**Comment by clort81** [comment]
Hello mlongval thanks for your post.

Bug confirmed: not limited to xcape 

I achieve similar remapping of capslock with an ~/.Xmodmap file containing e.g.
```
!remove Lock = Caps_Lock
clear lock
! set the CapsLock to act as Mode_Switch
! activates 3rd (without shift) or 4th (with shift) Symbol
keycode  66 = Mode_switch
keycode  10 = 1 exclam U1fb48
keycode  11 = 2 at U1fb44                                                                                                                                       

! Checkmark normal and bold ✓ ✔
keycode  54 = c C 0xaf3 U2714
```
this is activated with command **xmodmap ~/.Xmodmap**

This lets me use CapsLock as a modifier to get customized characters, e.g. checkmarks.

Works in all terminals, browsers, editors - except kitty.

**Comment by kovidgoyal** [comment]
I'm afraid I dont have any interest in dealing with the myriad ways you can mixup keys in X11. Patches welcome. And note that kitty uses libxkb to handle key events. So whatever xcape is doing presumably does not work with it.
