### ISSUE TITLE
nvim is unable to set titlestring after using `kitty @ set-window-title`

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#592]
- Run kitty so that you can see its title (e.g. in tabbed mode in i3wm)
- Open `nvim` (regular `vim` will probably work too)
- Execute `:set titlestring=abc`
- Observe that kitty's title is correctly changed to `abc`
- Exit `nvim`
- Run `kitty @ set-window-title fixed`
- Observe that kitty's title is correctly changed to `fixed`
- Open `nvim` again
- Execute `:set titlestring=def`

Expected: title is changed to `def`
Actual: title remains to be `fixed`

**Comment by kovidgoyal** [comment]
That is by design. set-window-title overrides any title set by programs running in the terminal. Use the escape codes directly if you want to set the title in a way that can be overriden.
