### ISSUE TITLE
On macOS keyboard shortcut Command+` dons't work when starting Kitty terminal with kitty command.

### ISSUE THREAD

**Issue by MathiasHH** [kovidgoyal/kitty#5921]
**Describe the bug**
On macOS Ventura 13.1 keyboard shortcut "Move focus to next window", that by default is mapped to: ```Command+` ``` dosn't work for me, when starting Kitty terminal with `kitty` command from Kitty terminal.

**To Reproduce**
1. open kitty terminal
2. Type: `kitty`
    Or type: `kitty --config=NONE` 
    Or type: `kitty --session <some session>`
3. A new kitty terminal is opened. 
4. Shortcut ```Command+` ``` dosn't  go to next Kitty terminal. 
It cannot go to next Kitty terminal from that newly opened kitty terminal. Also it cannot go to that newly created kitty terminal from any other kitty terminals.
If Kitty terminal instead are opened with Kitty keyboard shortcut `Ctrl+Shift+n` or ```Command+n` ``` then it works as expected. 
On Ubuntu 22.04 it works as expected with shortcut "Switch windows of an app directly" that by default is mapped to Alt+F6

**Environment details**
kitty 0.26.5 created by Kovid Goyal
Darwin Mathiass-MacBook-Pro.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.1 BuildVersion:		22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Users/mhh/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/kitty.app/Contents/MacOS
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /opt/homebrew/bin/bash
	USER                                mhh

**Comment by kovidgoyal** [comment]
command+` cycles betwene OS windows in a *single kitty process*. If you
want to run kitty and have the newly created windows part of the same
instance, use --same-instance

**Comment by MathiasHH** [comment]
What is the syntax?

`kitty --same-instance`
returns:
`Unknown option: --same-instance`

**Comment by kovidgoyal** [comment]
--single-instance

Use kitty --help
