### ISSUE TITLE
Bell even when enable_audio_bell no

### ISSUE THREAD

**Issue by josham** [kovidgoyal/kitty#5924]
**Describe the bug**
The bell is audible even when disabled.

**To Reproduce**
1. Run `kitty --config NONE -o enable_audio_bell=n -o "map=ctrl+shift+up layout_action move_to_screen_edge top"`
2. hit `ctrl+shift+up` a few times in a row
3. If  I add `--dump-commands` or above I see `screen_bell` showing when hitting `ctrl+shift+up`

**Environment details**
kitty 0.26.5 on Linux 6.1.3-arch1-1

**Comment by kovidgoyal** [comment]
already fixed in master
