### ISSUE TITLE
Cursor shape bash vi normal mode

### ISSUE THREAD

**Issue by Paul-Aime** [kovidgoyal/kitty#5927]
I use kitty (0.26.2) + tmux (3.0) + bash (5.0.17) on Ubuntu (20.04.5)

I have the following `~/.config/readline/inputrc` (corresponding `INPUTRC` set):

```
$include /etc/inputrc  # default Ubuntu 20.04.5 LTS

set editing-mode vi
set show-mode-in-prompt on
set vi-cmd-mode-string "\1\e[2 q\2"
set vi-ins-mode-string "\1\e[6 q\2"
```

The cursor shape behavior is broken when in kitty alone:

In kitty + tmux:

- Normal mode: █
- Insert mode: |

In kitty alone:

- Normal mode: |     ----- Error here
- Insert mode: |

It works as expected in gnome-terminal.

It also works if I am in a subshell (by calling `bash` after opening kitty).

Setting `shell_integration no_cursor` does nothing.

I also noticed that the `cursor_shape` setting is not applied, whatever value I set it to (despite the `kitty.conf` file being corretly loaded, at least for fonts etc, window decoration etc.)

And the bug remains for `kitty --config NONE`.

Any idea why this happens?

**Environment details**
```
kitty 0.26.2 created by Kovid Goyal
Linux xxxxxxxx 5.14.0-1056-oem #63-Ubuntu SMP x86_64
Ubuntu 20.04.5 LTS xxxxxxxx /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: ~/.local/lib/kitty.app/bin/kitty
  base dir: ~/.local/lib/kitty.app/lib/kitty
  extensions dir: ~/.local/lib/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  ~/.config/kitty/kitty.conf

Config options different from defaults:
bold_font              Fira Code Bold Nerd Font Complete Mono
bold_italic_font       Fira Code Bold Italic
font_family            Fira Code Regular Nerd Font Complete Mono
italic_font            Fira Code Italic
wayland_titlebar_color 1
Removed shortcuts:
        kitty_mod+enter →  new_window
        kitty_mod+r →  start_resizing_window
```

**Comment by kovidgoyal** [comment]
If you want to control cursor shape via inputrc, add no-cursor to
shell_integration in kitty.conf
