### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by BigfootN** [kovidgoyal/kitty#593]
Hello,

Is there a repository / web site where I can get premade kitty themes (GUI) ? Or if there is any other way.

Such as solarized theme, monokai, ...

Thank you very much in advance.

**Comment by kovidgoyal** [comment]
Not that I know of, but it should be trivial to port a theme from any other software to the kitty color settings. In fact, IIRC the kitty color settings syntax is identical to that of termite. So you can simply use a termite theme directly in kitty.

**Comment by BigfootN** [comment]
Thank you very much for your quick answer.
