### ISSUE TITLE
Kitty pastes from primary no matter what

### ISSUE THREAD

**Issue by 875d** [kovidgoyal/kitty#5938]
I used my compositor config option to rebind middle-mouse button to noop. See [hyprland #1437](https://github.com/hyprwm/Hyprland/issues/1437).

This works in Firefox and LibreOffice Writer, for instance, for which the middle mouse button triggers only the new behavior (noop, notify-send, or whatever).

But in kitty, the middle mouse button triggers both the old behavior (pasting from primary) as well as the new behavior.

**Comment by 875d** [comment]
Of course I didn't re-bind it in `kitty.conf`

**Comment by kovidgoyal** [comment]
kitty will react to whatever events it receives. If it is pasting on
middle mouse then it is because it is receiving that event. It cannot
magically paste of its own volition.

kitty --debug-input

**Comment by 875d** [comment]
It says:

```
Release mouse_button: 2 mods: none grabbed: 0
MouseEvent matched action: paste_from_selection
on_mouse_input: release button: middle mods: none grabbed: 0 handled_in_kitty: 1
Press xkb_keycode: 0x7d clean_sym: Super_L composed_sym: Super_L mods: none glfw_key: 57444 (LEFT_SUPER) xkb_key: 65515 (Super_L)
```

How did it match `paste_from_selection`?

I think this is an internal kitty command.

kitty is receiving the middle mouse click and it maps it to `paste_from_selection`. No?

**Comment by 875d** [comment]
I did put the following in my `kitty.conf`:

```
mouse_map middle release ungrabbed no_op
```

and now it doesn't paste from primary anymore.

So indeed kitty was intercepting the "middle mouse release" event and bound it to paste from primary on its own, no? @kovidgoyal

**Comment by 875d** [comment]
The guys at Hyprland says that if the key is bound, the compositor does *not* send it to the app.

So it looks like kitty is intercepting keys on its own, somehow?

**Comment by kovidgoyal** [comment]
kitty has mouse *release* bound to paste you have blocked only mouse
press in your compositor. Block both. This is a bug neither in kitty nor
in hyprland.

**Comment by 875d** [comment]
> kitty has mouse _release_ bound to paste you have blocked only mouse press in your compositor. Block both. This is a bug neither in kitty nor in hyprland.

Thank you very very much. Blocking the release does indeed prevent kitty from pasting primary with middle mouse button.

But I don't understand what's happening anymore.

Both Firefox and LibreOffice Writer seems to also bind primary buffer paste to middle mouse button **release**.
In fact, if you press the middle mouse button, nothing appears on screen until you release it.
But for them clocking the middle button **press** is sufficient to prevent action.

Either that or I don't know what hyprland is really doing.
