### ISSUE TITLE
Under wayland backend, scrolling direction is flipped

### ISSUE THREAD

**Issue by aenda** [kovidgoyal/kitty#594]
Hi again - thanks for your help in allowing kitty to run as a native wayland app. I've been using it as my daily driver and it works fine except for the fact that the scrolling direction will be the opposite of other applications. For example, if I run it in weston with natural scroll disabled, it will behave as if it is enabled, or if I run it in sway with natural scroll enabled, it will act as if it is disabled. I would appreciate you looking into this or just pointing me in the right direction, thanks!

**Comment by kovidgoyal** [comment]
Again, a glfw issue :) Look at pointerHandleAxis() in glfw/wl_init.c

Feel free to report it upstream. Hopefully this time they will give us less run-around before accepting it is a bug.
