### ISSUE TITLE
Keyboard text selection

### ISSUE THREAD

**Issue by defdefred** [kovidgoyal/kitty#5943]
To be able to copy-paste without using mouse.

Maybe Crtl-Shift+Arrows to make the text selection as Crtl-Shift+[CV] are used next.

**Comment by kovidgoyal** [comment]
Simply use a program such a vim with support for this as your scrollback
pager. https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer

**Comment by ad-chaos** [comment]
There was a discussion a while ago on this, you could try using this [grab kitten](https://github.com/yurikhan/kitty_grab)
