### ISSUE TITLE
[FR] Get rid of "Press Enter or Esc to exit"

### ISSUE THREAD

**Issue by raffaem** [kovidgoyal/kitty#5945]
I don't understand how this feature works.

If I have kitty open another program, the kitty OS window will close when that other program exit.
The same if I spur a subshell.

But, if I have kitty run a script file, when the script file exits kitty will prompt "Press Enter or Esc to exit" before closing the OS window.

How does this feature work, and how I can get rid of that prompt and close the OS window directly?

Example below:

```bash
printf "Hello" > temp.txt
# This closes the OS window when moar exit
kitty moar temp.txt
# So does this
kitty sh -c "moar temp.txt"
# This triggers the prompt instead
printf "moar temp.txt" > temp.sh
kitty temp.sh
```

**Comment by kovidgoyal** [comment]
You cant get rid of it. It exists so that you can see the output of
running the shell script. If you dont need to see the output dont run it
in a kitty window at all. Or run

kitty sh myfile.sh

and you wont see the press enter messgae.

**Comment by raffaem** [comment]
Thank you Kovid.

**Comment by page-down** [comment]
@raffaem
Add shebang to the script file and give executable permission.

If this is a non-executable text file, then kitty will guess from the file extension and execute it using a shell, with `hold` enabled.

In fact, kitty can choose not to run it and report errors. In my opinion this feature is purely for convenience.

**Comment by raffaem** [comment]
> @raffaem Add shebang to the script file and give executable permission.
> 
> If this is a non-executable text file, then kitty will guess from the file extension and execute it using a shell, with `hold` enabled.
> 
> In fact, kitty can choose not to run it and report errors. In my opinion this feature is purely for convenience.

You are right, with this precautions it doesn't prompt anymore.

Thanks!
