### ISSUE TITLE
Throw `Error opening terminal: xterm-kitty.` when running nethogs

### ISSUE THREAD

**Issue by sdifru** [kovidgoyal/kitty#5947]
**Describe the bug**
Kitty throw error when I run `sudo nethogs`.

**To Reproduce**
1. Run `sudo nethogs`
2. It throws `Error opening terminal: xterm-kitty.`

**Environment details**
kitty 0.26.5 created by Kovid Goyal
Linux john-desktop 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64
Linux Mint 21.1 Vera john-desktop /dev/tty

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
Running under: X11
Frozen: True
Paths:
  kitty: /home/john/.local/kitty.app/bin/kitty
  base dir: /home/john/.local/kitty.app/lib/kitty
  extensions dir: /home/john/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /home/john/.config/kitty/kitty.conf

Config options different from defaults:
font_family             Liberation Mono
font_size               11

Colors:
	active_border_color     #7287fd   
	active_tab_background   #8839ef   
	active_tab_foreground   #eff1f5   
	background              #eff1f5   
	bell_border_color       #df8e1d   
	color0                  #5c5f77   
	color1                  #d20f39   
	color10                 #40a02b   
	color11                 #df8e1d   
	color12                 #1e66f5   
	color13                 #ea76cb   
	color14                 #179299   
	color15                 #bcc0cc   
	color2                  #40a02b   
	color3                  #df8e1d   
	color4                  #1e66f5   
	color5                  #ea76cb   
	color6                  #179299   
	color7                  #acb0be   
	color8                  #6c6f85   
	color9                  #d20f39   
	cursor                  #dc8a78   
	cursor_text_color       #eff1f5   
	foreground              #4c4f69   
	inactive_border_color   #9ca0b0   
	inactive_tab_background #9ca0b0   
	inactive_tab_foreground #4c4f69   
	mark1_background        #7287fd   
	mark1_foreground        #eff1f5   
	mark2_background        #8839ef   
	mark2_foreground        #eff1f5   
	mark3_background        #209fb5   
	mark3_foreground        #eff1f5   
	selection_background    #dc8a78   
	selection_foreground    #eff1f5   
	tab_bar_background      #bcc0cc   
	url_color               #dc8a78   

Important environment variables seen by the kitty process:
	PATH                                /home/john/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                john
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	LC_MONETARY                         id_ID.UTF-8
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      c2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_ADDRESS                          id_ID.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TELEPHONE                        id_ID.UTF-8
	XDG_CURRENT_DESKTOP                 X-Cinnamon
	XDG_SESSION_DESKTOP                 cinnamon
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/john
	LC_NAME                             id_ID.UTF-8
	LC_MEASUREMENT                      id_ID.UTF-8
	LC_IDENTIFICATION                   id_ID.UTF-8
	XDG_VTNR                            7
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-cinnamon:/etc/xdg
	XDG_DATA_DIRS                       /usr/share/cinnamon:/usr/share/gnome:/home/john/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	LC_NUMERIC                          id_ID.UTF-8
	LC_PAPER                            id_ID.UTF-8

**Comment by kovidgoyal** [comment]
Search the kitty FAQ for sudo

**Comment by sdifru** [comment]
It works @kovidgoyal . Thank you!
