### ISSUE TITLE
spacing option for `overlay` windows is ignored

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#5948]
**Describe the bug**
The `launch` command ignores the `--spacing` option for `overlay` windows.

**To Reproduce**
1. Launch kitty like this: `kitty --config NONE -o 'allow_remote_control yes'`.
2. `kitty @ launch --type overlay --spacing margin=20`

**Observed Behavior**
No margins

**Environment details**
```
kitty 0.26.5 () created by Kovid Goyal
Linux byteevo 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64
Ubuntu 20.04.5 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  allow_remote_control yes
  map f1 launch --spacing margin=20

Config options different from defaults:
allow_remote_control yes
Added shortcuts:
	f1 →  launch --spacing margin=20

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
- Nightly release, generated on: 2023-01-29 21:40:41 UTC from commit: https://github.com/kovidgoyal/kitty/commit/18fc8dad37c944e9f3cfe708df8648ac234ac3c8.
- Though I am using remote-control, one can confirm by adding the `-o 'map f1 launch --type overlay --spacing margin=20'` to kitty options that the issue is with the launch command itself, not the command line argument parsing of the remote control command.

**Comment by kovidgoyal** [comment]
Yes overlay windows cannot have spacing different from the window they
are overlaying.

**Comment by kovidgoyal** [comment]
Although it might be possible to change that, I will look into it when I
have a moment.

**Comment by salmankhilji** [comment]
> Although it might be possible to change that, I will look into it when I have a moment.

Its not important, really.  Now that I think of it, it probably makes sense to resolve this ticket as-designed based on what you said earlier.

**Comment by kovidgoyal** [comment]
A margin would not be transparent. Popups are a different use case from overlays and would require a separate code path/design.
