### ISSUE TITLE
How can I remove that cat icon from title-bar of wayland or xwayland?

### ISSUE THREAD

**Issue by Rid1-fz-06** [kovidgoyal/kitty#5949]
I love Kitty terminal more than Alacritty or any other GUI-accelerated terminal. But I'm not too fond of that cat Icon on the title bar of Wayland's session. Is there any way to remove that icon?

![image](https://user-images.githubusercontent.com/92540820/215448444-a0fd1eea-8e02-425c-a41b-d14e6f63b08e.png)

**Comment by kovidgoyal** [comment]
Set linux_display_server x11 in kitty.conf
