### ISSUE TITLE
Is it possible to remap media keys?

### ISSUE THREAD

**Issue by zomgugoff** [kovidgoyal/kitty#5953]
I am trying to stop the media keys on my keyboard from creating output in the terminal. I thought I could do this with a map command:

map \x1b[57428u discard_event

However, it doesn't appear to be catching anything like this. Am I doing this incorrectly?

**Comment by kovidgoyal** [comment]
The kitty FAQ tells you how to remap keys.
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program

**Comment by zomgugoff** [comment]
I have followed this. However, Kitty is not catching the CSI code. Is it not possible for Kitty to capture CSI codes to be mapped to other functions?

**Comment by kovidgoyal** [comment]
CSI codes are sent to programs running in the terminal, not to
terminals. You need to specify the actual keys you want in kitty.conf.
