### ISSUE TITLE
kitty cli option `--detach` does not work

### ISSUE THREAD

**Issue by tigion** [kovidgoyal/kitty#5954]
**Describe the bug**
The kitty command line interface option `--detach` does not work.

(A quick search of the existing issues shows nothing about this. I hope I didn't miss a hint about this.)

**To Reproduce**
1. open terminal
2. run: `kitty --detach`
3. See error: 
    ```sh
    ❯ kitty --detach
    Unknown option: --detach
    ```

**Environment details**
* kitty 0.27.0 and 0.26.5
* macOS 13.1 (X86_64) and macOS 11.7.3 (X86_64)
* installed via `brew install --cask kitty`

**Comment by kovidgoyal** [comment]
--detach is Linux only. If you do kitty --help in macOS you will not see
it.

**Comment by tigion** [comment]
Thanks for the quick clarification. I had looked in `man kitty` and not `kitty --help` in macOS.

**Comment by Malian** [comment]
I'm bringing this up because I tried to use the `--detach` option on macOS and it didn't work.

How can I, on macOS, launch a kitty terminal from another kitty terminal without them being linked.

My use case is to be able to launch `kitty --session /path/to/my/project/kitty.conf` but not have a terminal open unnecessarily.

Thanks

**Comment by kovidgoyal** [comment]
If you want to open new windows and tabs in an existing kitty instance,
you use remote control. If you want to open a new instance simply run
kitty. I dont know what you mean by you dont want a new terminal to
popup. If you are running kitty you are creating a new instance
regardless of whether you use --detach or not.

**Comment by Malian** [comment]
@kovidgoyal sorry if I wasn't clear, and thanks for your answer.

Let's say that I open my kitty terminal with spotlight/alfred/raycast/... I am on macOS. In that OS window (number 1), I execute the `kitty` command. It opens a new kitty OS window (number 2).

If I close the OS window 1, the OS window 2 also closes automatically. I would like to have a new OS window that lives independently from the other. It's what I meant by "without them being linked". I thought that was the purpose of the `--detach` option.

In the meantime I found this command: `kitty @ launch --type=os-window` not sure it's the right way to do, but it seems to work for my use case.

**Comment by kovidgoyal** [comment]
macOS has the tools to do this built-in. You do something like

open -a kitty.app -n

See man open for details
