### ISSUE TITLE
Clipboard kitten can not copy `bind -p` from bash

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#5955]
**Describe the bug**
The clipboard kitten fails to copy the output of command `bind -p`.

**To Reproduce**
1. Launch kitty like this: `kitty --config NONE`.
2. `bind -p | kitty +kitten clipboard`.
3. Attempt to paste into another app.

**Observed Behavior**
Can not paste.  Clipboard is empty.

**Environment details**
```
kitty 0.27.0 () created by Kovid Goyal
Linux byteevo 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64
Ubuntu 20.04.5 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**

- `echo foo | kitty +kitten clipboard` works.
- This also works: `bash --version | kitty +kitten clipboard`

```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by salmankhilji** [comment]
Attaching output of: `bind -p >my-bindings.txt`

[my-bindings.txt](https://github.com/kovidgoyal/kitty/files/10546157/my-bindings.txt)

**Comment by kovidgoyal** [comment]
Works for me, steps I tried

1) kitty --config NONE -o shell=bash
2) bind -p | kitten clipboard
3) kitten clipboard -g

output of bind -p as expected (after allowing the paste)

Changing step (2) above to 

kitten clipboard < my-bindings.txt also works for me

**Comment by salmankhilji** [comment]
It appears to be an encoding issue.

Though `kitten clipboard -g` or `kitty +kitten clipboard -g` shows that I have text on the clipboard in all cases, I can not paste the available text into gedit or meld.  (Perhaps other GNOME or GTK apps are also affected.)  Pasting into GVIM works; however, a specific line range does not appear correctly.

On my system, the output of the following command creates **ISO-8859** text.

```
$ bind -p >my-bindings-ISO-8859.txt
precor@byteevo:~/Scratch$ file my-bindings-ISO-8859.txt
my-bindings-ISO-8859.txt: ISO-8859 text
```

If I open the above file in gedit or gvim, select all, new buffer, paste and save, then the resulting file is **UTF-8** text:

```
$ ll my-bindings-*
-rw-rw-r-- 1 precor precor 11196 Jan 31 18:22 my-bindings-ISO-8859.txt
-rw-rw-r-- 1 precor precor 11293 Jan 31 18:02 my-bindings-UTF-8.txt
precor@byteevo:~/Scratch$ file my-bindings-*
my-bindings-ISO-8859.txt: ISO-8859 text
my-bindings-UTF-8.txt:    UTF-8 Unicode text
```

_Data copied to the clipboard using the kitten can only be pasted into gedit or meld if I copy from `my-bindings-UTF-8.txt`._

### Offending Line Range

It is a specific line range that is offending.

Line 317 pastes into gedit just fine:
```
sed -n 317p my-bindings-ISO-8859.txt | kitty +kitten clipboard
```

Line 318, however, does not paste into gedit at all:
```
sed -n 318p my-bindings-ISO-8859.txt | kitty +kitten clipboard
```

Attempting to paste Line 318 into gvim produces:
![Screenshot from 2023-01-31 18-33-58](https://user-images.githubusercontent.com/40219235/215931371-7081c82e-1730-40a9-ac7c-646d5376146b.png)

### xsel

I can paste the resulting text into gedit if I copy to clipboard using `xsel`.  However, it probably does some character translation that I am reproducing below:

```
$ bind -p | sed -n 317p | xsel -bi; xsel -bo | hd
00000000  22 5c 32 33 37 22 3a 20  73 65 6c 66 2d 69 6e 73  |"\237": self-ins|
00000010  65 72 74 0a                                       |ert.|
00000014
precor@byteevo:~/Scratch$ bind -p | sed -n 317p | xsel -bi; xsel -bo; kitty +kitten clipboard -g -m . /dev/stdout
"\237": self-insert
text/plain
precor@byteevo:~/Scratch$ bind -p | sed -n 318p | xsel -bi; xsel -bo | hd
00000000  22 a0 22 3a 20 73 65 6c  66 2d 69 6e 73 65 72 74  |".": self-insert|
00000010  0a                                                |.|
00000011
precor@byteevo:~/Scratch$ bind -p | sed -n 318p | xsel -bi; xsel -bo; kitty +kitten clipboard -g -m . /dev/stdout
"": self-insert
text/plain
```

### Attachments
- [my-bindings-UTF-8.txt](https://github.com/kovidgoyal/kitty/files/10552760/my-bindings-UTF-8.txt)
- [my-bindings-ISO-8859.txt](https://github.com/kovidgoyal/kitty/files/10552759/my-bindings-ISO-8859.txt)

**Comment by salmankhilji** [comment]
I have started to read about default encoding on Linux systems.  Though I get this on my system:

```
$ printenv LANG
en_US.UTF-8
```

I do not understand why `bind -p`, when saved to a file, is **ISO-8859** instead of **UTF-8**.

**Comment by kovidgoyal** [comment]
Well the kitten only works with UTF-8, it has no support for other text
encodings. It's up to the user to ensure it is given only UTF-8.

**Comment by salmankhilji** [comment]
So it looks 

> This problem does not exist in the latest bash, at least under macOS, with `en_US.UTF-8`. I see `\200 ~ \377` in `bind -p`.
> 
> So, convert it to UTF-8 and then feed it to kitten?

Not sure if we can rely on the user figuring out whether a particular command generates UTF-8 or some other encoding.  The impatient ones are likely to try another program, like `xsel` or `xclip` before digging into encoding.

The issue, however, does not appear to be with kitty: `xclip` also gets it wrong.  As you can see from the output below, `xclip` recognizes Line 317 as UTF8, correctly so.  Line 318, which as some weird characters, is incorrectly recognized as UTF8.  And yes, I have the same problem: I can not paste the text into gedit.  Pasting into GVIM works albeit with some character translation.

```
precor@byteevo:~$ bind -p | sed -n 317p | xclip -selection clipboard
precor@byteevo:~$ xclip -selection clipboard -o -t TARGETS
TARGETS
UTF8_STRING
precor@byteevo:~$ bind -p | sed -n 318p | xclip -selection clipboard
precor@byteevo:~$ xclip -selection clipboard -o -t TARGETS
TARGETS
UTF8_STRING
```

**Comment by kovidgoyal** [comment]
There is no way to robustly tell what encoding a stream of bytes
is in. Any utility that copies to the clipboard will have the same
problem, this has nothing to do with kitty. It is up to the user to
ensure that they supply valid data to whatever program is transferring
that data to the clipboard.
