### ISSUE TITLE
kitten icat GIF seems corrupted over ssh

### ISSUE THREAD

**Issue by jarbus** [kovidgoyal/kitty#5958]
**Describe the bug**
`kitten icat GIF.gif` works as expected on the machine running the kitty process, but when connecting through the ssh kitten, the frames seem to get corrupted
**To Reproduce**
1. SSH to remote server that has the below gif on it
2. `kitten icat GIF.gif`

Expected gif:
![neat](https://user-images.githubusercontent.com/42819002/215867839-fbc85fa0-19a7-4d1b-9076-5fe3348ae739.gif)

Last frame over ssh:
![image](https://user-images.githubusercontent.com/42819002/215868208-d3cdb7ad-9c96-4331-87fd-c301e8839136.png)

**Environment details**
```
kitty 0.27.0 () created by Kovid Goyal
Linux archlinux 6.1.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 Jan 2023 21:07:04 +0000 x86_64
Arch Linux 6.1.8-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: True
Paths:
  kitty: /home/jack/.local/kitty.app/bin/kitty
  base dir: /home/jack/.local/kitty.app/lib/kitty
  extensions dir: /home/jack/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /home/jack/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    yes
enable_audio_bell       False
font_family             Unifont
font_size               24.0
listen_on               unix:/tmp/mykitty
```

**Comment by kovidgoyal** [comment]
I'll look at this when I have a moment, but can you do a quick test. When running locally, does using --transfer-mode stream replicate the issue?

**Comment by page-down** [comment]
> ... does using --transfer-mode stream replicate the issue?

Yes, I can reproduce the issue with `--transfer-mode stream`.

**Comment by jarbus** [comment]
Epic response time, thank you!
