### ISSUE TITLE
Problem starting a kitty instance & run a cmd with a system wide keyboard shortcut on KDE

### ISSUE THREAD

**Issue by lyndhurst** [kovidgoyal/kitty#5960]
**Describe the bug**

I am trying to create a few popup kitty terminals to quickly search through my notes. To manage my notes, I use [zk](https://github.com/mickael-menu/zk) which itself runs a `fzf` search in the terminal.

Running `kitty zk list -i -f notes` from a kitty terminal, or from a script works fine in both cases.

When I try to bind it to a keyboard shortcut using KDE Shorcut feature, I got a kitty window that opens, but with the following error message:

```
Failed to launch child: zk
With error: No such file or directory
Press Enter to exit.
```

Searching through the issues here, I read (and tried) about remote control and the `@ launch` commands, but I do not think it is related.

I do use a system wide shortcut to launch kitty without running a command on a daily basis, and it works fine. 

I guess I am missing something, or maybe it is a kde issue, in which case I am sorry to waste your time, but I ran out of ideas to investigate this issue further.

Thank you for your help.

**Environment details**
```
kitty 0.24.2 created by Kovid Goyal
Linux 5.4.0-137-generic #154~18.04.1-Ubuntu SMP Tue Jan 10 16:58:20 UTC 2023 x86_64
Ubuntu 18.04.6 LTS  /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: ~/.local/kitty.app/bin/kitty
  base dir: ~/.local/kitty.app/lib/kitty
  extensions dir: ~/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  ~/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control  y
font_family           Meslo LG M for Powerline
font_size             14.0
update_check_interval 0.0
```

**Comment by lyndhurst** [comment]
After investigating further, I think there is an issue with loading the `.zshrc` or `.bashrc` file (I tried both shells with the same results. I am wondering if the shell has the time to load the path and be aware of what the `zk` command is..

That still does not explain (to me) why issuing the command from another kitty terminal would work.

I also tried with `konsole`, and I have the same problem. So I guess it is NOT a `kitty` issue. Any tip would still be greatly appreciated ! Thanks.

**Comment by kovidgoyal** [comment]
Use an absolute path to zk

**Comment by page-down** [comment]
> ... why issuing the command from another kitty terminal would work ...

https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

If you want to use `zk` instead of absolute path, set your system wide PATH, not just in your shell rc.

**Comment by lyndhurst** [comment]
I feel very dumb since I was almost there in my last post.
I thank you both @kovidgoyal  , @page-down for taking the time, and having the patience.
