### ISSUE TITLE
can't use `sp` to change Neovim's  strikethrough color in kitty

### ISSUE THREAD

**Issue by NEX-S** [kovidgoyal/kitty#5968]
**Describe the bug**
seems kitty dont support using `sp` to change Neovim's  strikethrough color, I test it in neovide it works fine.
neovim's config
```
api.nvim_set_hl(0, "Normal", { sp = "#ffffff", strikethrough = true }
```

**To Reproduce**
1. `lua vim.api.nvim_set_hl(0, "Normal", { sp = "#ffffff", strikethrough = true }`
2. the strikethrough's color is not `#ffffff`

**Screenshots**
![Screenshot from 2023-02-02 15-26-45](https://user-images.githubusercontent.com/97107165/216259090-514b74e3-1a8e-4f06-adda-0a3dbc6faa13.png)

**Comment by kovidgoyal** [comment]
terminals dont support independent colors for strikethrough
