### ISSUE TITLE
Menu Key not working

### ISSUE THREAD

**Issue by ghost** [kovidgoyal/kitty#597]
I need some help. I cannot get the <MENU> key to work (the one between the right Alt and right Ctrl key). `xev` gives mit this:

    KeyRelease event, serial 28, synthetic NO, window 0x3800001,
        root 0x110, subw 0x3800002, time 57236319, (54,56), root:(1340,119),
        state 0x0, keycode 135 (keysym 0xff67, Menu), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

I can map the key to something else without problem like this in the config:

    map menu send_text all test

and it will work very good. But the default configuration for the key does not. For example emacs in terminal mode will not recognize the key at all, even thought it works fine it normal mode. If I map it, to send some kind of text, it works, but the key does not seem to properly forward the normal keybinding.

Any idea how to solve this?

**Comment by neutronst4r** [comment]
Thank you for your help. I got it working with @kovidgoyal's suggestion. If someone else is interested in the solution:
I mapped the key to \uff67 in the kitty.conf:

    map menu send_text all \uff67

It will print the character `ｧ` in terminal now. Mapping that character in the terminal application is trivial.
I added this in my emacs config:

    (use-package ibuffer
      :bind ([menu] . ibuffer-call)
            ("ｧ" . ibuffer-call)
      [...]
    )

**Comment by yurikhan** [comment]
@kovidgoyal I see you had once decided to support xterm’s encoding for the Menu key, but it got dropped while implementing the comprehensive keyboard protocol (commits of 2021-01-11/12). In 0.24.1, it is reported as `CSI 57363 [; modifiers] u` even in the legacy mode. Would you care to encode it as `CSI 29 [; modifiers] ~` again?

**Comment by kovidgoyal** [comment]
Not myself, but a patch is welcome.

**Comment by kovidgoyal** [comment]
Actually I had 5 mins so here you go: https://github.com/kovidgoyal/kitty/commit/34e939f9a19456685e25feea67813a443700b17b
