### ISSUE TITLE
query: displaying images in ncmpcpp

### ISSUE THREAD

**Issue by emacsomancer** [kovidgoyal/kitty#598]
Context: [`ncmpcpp`](https://rybczak.net/ncmpcpp/) is an ncurses based client for [`mpd`](https://www.musicpd.org/) which runs in a terminal. The configuration file for `ncmpcpp` allows for arbitrary commands to be executed on track changes, so people have found ways of using this to display album/cover art. [The method described here for `urxvt`](https://marcocheung.wordpress.com/2015/08/09/showing-album-cover-in-ncmpcpp/) runs a bash script which searches the directory of the currently playing album for an appropriate file, resizes this to a particular size, then executes `printf "\e]20;${COVER};30x30+1+50:op=keep-aspect\a"`, using `printf "\e]20;;100x100+1000+1000\a"` to reset the background.  

It seems to me that this method could be adapted to work in `kitty` fairly easily, just requiring the `printf` commands to be replaced with the appropriate functions/commands. I tried using `kitty icat --place 40x100@0x20 $COVER` and similar in the bash script while running `ncmpcpp` in `kitty`, but this does not seem to function the way I was hoping (though I can get `kitty` to display images otherwise, just not in the `ncmpcpp` script). 

Obviously this a fairly minor query, but I was wondering if anyone had figured out some way of getting this to work, or if anyone had suggestions for one might do so.  (It would be great to be able to use `kitty` in this way, since `urxvt` doesn't have the same sort of font display capacities of `kitty`.)

**Comment by kovidgoyal** [comment]
I'm not a ncmcpp user, so I cannot help you with that. If you look at https://sw.kovidgoyal.net/kitty/graphics-protocol.html you will see links to various utilitites that make use of kitty's image protocol. In particular, I believe termpdf is an actual bash script that uses kitty icat rather than using the protocol directly. That  might give you some inspiration.

One thing to keep in mind is that unlike the urxvt hack you linked to, kitty's image support is integrated with terminal operations,so if the terminal program does a clear screen or scrolls the screen, etc, the image will be cleared/scrolled along with it. So you might need deeper integration with ncmcpp to get it to work

**Comment by johnallen3d** [comment]
I should mention that my implementation was inspired by [this post](https://old.reddit.com/r/unixporn/comments/9bifne/ncmpcpp_with_cover_art_ueberzug_tmux_edition/) and isn't exactly the same as the what @emacsomancer was looking for...

I've been able to hide the prompt (hakcy?). Of course this is starting a new bash session every time the track changes. 😕

```sh
kitty @ send-text \
  --match title:cover \
  "PS1='' bash --init-file <(echo 'clear && kitty icat /tmp/cover.png') \r"
```

<img width="354" alt="ncmpcpp 2018-08-31 16-30-05" src="https://user-images.githubusercontent.com/184915/44934522-22018200-ad3b-11e8-9833-ea3e3e5e39a5.png">

I'm still seeing some output that I previously thought was from ffmpeg but it turns out it [this line in kitty](https://github.com/kovidgoyal/kitty/blob/4d2d9d55749948a18f73e3676b66664dfe57e1d6/kittens/icat/main.py#L208).

**Comment by johnallen3d** [comment]
Ok, one more update. I can avoid the codepath that prints that message by specifying a `--transfer-mode` like so:

```sh
#! /usr/bin/env bash

kitty @ send-text \
  --match title:cover \
  "
    PS1='' bash --init-file <(echo '
      clear && \
        kitty icat --transfer-mode=stream /tmp/cover.png
    ') \r
  "
```

😁 

<img width="514" alt="ncmpcpp 2018-08-31 16-43-12" src="https://user-images.githubusercontent.com/184915/44934993-f7182d80-ad3c-11e8-9c0a-4974e5a84fec.png">

**Comment by kovidgoyal** [comment]
Cool :) Seems like what would make this more simple/robust is a kitty @ icat remote control command.

**Comment by kovidgoyal** [comment]
Oh and you can avoid the need to start a new bash by starting the initial
kitty window like this:

```
kitty env PS1="" sh
```

that way there will be no prompt in the window.

**Comment by kovidgoyal** [comment]
Or simply change your ~/bin/music script to

```sh
#! /usr/bin/env bash

kitty @ set-tab-title music
kitty @ set-window-title cover
kitty @ new-window --title ncmpcpp ncmpcpp
kitty @ resize-window --increment 93
source "$HOME/bin/set-current-cover"
export PS1=""
exec sh
```

**Comment by johnallen3d** [comment]
Thanks for the tips @kovidgoyal. Based on your advice I was able to re-jigger my `~/bin/music` script like so:

```bash
#! /usr/bin/env bash

kitty @ new-window --new-tab --tab-title music --title cover sh
kitty @ send-text 'export PS1="" \r'
change_cover
kitty @ new-window --title ncmpcpp ncmpcpp
kitty @ resize-window --increment 93
```

I condensed the whole thing down to one script with a couple of functions:

```bash
#! /usr/bin/env bash

function launch_player() {
  kitty @ new-window --new-tab --tab-title music --title cover sh
  kitty @ send-text 'export PS1="" \r'
  change_cover
  kitty @ new-window --title ncmpcpp ncmpcpp
  kitty @ resize-window --increment 93
}

function change_cover() {
  kitty @ send-text \
    --match title:cover \
    'clear && kitty icat --transfer-mode=stream /tmp/cover.png \r'
}

function extract_cover() {
  music_dir="$HOME/Music/iTunes/iTunes Music/Music"
  temp_song="/tmp/current-song"

  cp "$music_dir/$(mpc --format %file% current)" "$temp_song"

  ffmpeg \
    -hide_banner \
    -loglevel 0 \
    -y \
    -i "$temp_song" \
    -vf scale=400:-1 \
    "/tmp/cover.png" > /dev/null 2>&1

  rm "$temp_song"
}

if [[ $1 == "extract" ]]; then
  extract_cover
  change_cover
else
  launch_player
fi
```

Now my ncmpcpp config is simply `execute_on_song_change = "~/bin/music extract"`.

**Comment by kovidgoyal** [comment]
Much nicer :)

**Comment by SamDc73** [comment]
> Thanks for the tips @kovidgoyal. Based on your advice I was able to re-jigger my `~/bin/music` script like so:
> 
> ```shell
> #! /usr/bin/env bash
> 
> kitty @ new-window --new-tab --tab-title music --title cover sh
> kitty @ send-text 'export PS1="" \r'
> change_cover
> kitty @ new-window --title ncmpcpp ncmpcpp
> kitty @ resize-window --increment 93
> ```
> 
> I condensed the whole thing down to one script with a couple of functions:
> 
> ```shell
> #! /usr/bin/env bash
> 
> function launch_player() {
>   kitty @ new-window --new-tab --tab-title music --title cover sh
>   kitty @ send-text 'export PS1="" \r'
>   change_cover
>   kitty @ new-window --title ncmpcpp ncmpcpp
>   kitty @ resize-window --increment 93
> }
> 
> function change_cover() {
>   kitty @ send-text \
>     --match title:cover \
>     'clear && kitty icat --transfer-mode=stream /tmp/cover.png \r'
> }
> 
> function extract_cover() {
>   music_dir="$HOME/Music/iTunes/iTunes Music/Music"
>   temp_song="/tmp/current-song"
> 
>   cp "$music_dir/$(mpc --format %file% current)" "$temp_song"
> 
>   ffmpeg \
>     -hide_banner \
>     -loglevel 0 \
>     -y \
>     -i "$temp_song" \
>     -vf scale=400:-1 \
>     "/tmp/cover.png" > /dev/null 2>&1
> 
>   rm "$temp_song"
> }
> 
> if [[ $1 == "extract" ]]; then
>   extract_cover
>   change_cover
> else
>   launch_player
> fi
> ```
> 
> Now my ncmpcpp config is simply `execute_on_song_change = "~/bin/music extract"`.

is this script still working ? 
because it is acting very strange.
