### ISSUE TITLE
kitty complete 'not a valid entrypoint' in 0.27.0

### ISSUE THREAD

**Issue by gpbenton** [kovidgoyal/kitty#5980]
I get this error after compiling 0.27.0 from source.  The complete entrypoint is there when I revert to 0.26.5

Has complete functionality been removed from 0.27.0 intentionally?  I don't see it in the release notes, so I think not.

**Comment by page-down** [comment]
If you still use `kitty +complete`, you should replace it with `kitten __complete__`.
However, `kitten __complete__ setup` is not implemented in 0.27.0.

In the next release `kitty +complete` will be delegated to `kitten` to maintain backward compatibility, but it is not recommended for further use.
https://github.com/kovidgoyal/kitty/pull/5977

For users, you should delete/modify `kitty +complete` in your shell rc files.
For packagers, in version 0.27.0 you can introduce the relevant patches and use `kitten __complete__` instead.

**Comment by kovidgoyal** [comment]
Youa re using an obsolete form of complete that was deprecated many
years ago. Just remove any references to kitty completion from your shell rc
files.
