### ISSUE TITLE
Cursor size is not updated when loading xorg resource file

### ISSUE THREAD

**Issue by HakonHarnes** [kovidgoyal/kitty#5982]
**Describe the bug**
When changing the cursor size by setting `Xcursor.size` in `~/.Xresources` and loading the resource file with `xrdb ~/.Xresources`, Kitty does not update the cursor size. Kitty has to be quit and relaunched to respect the new cursor size. It does seem to update the `Xft.dpi` immediately after running `xrdb ~/.Xresources`, without relaunching, and that is the behavior I would like for `Xcursor.size` as well. 

**To Reproduce**
1. Launch Kitty. 
2. Change `Xcursor.size` in `~/.Xresources`.
3. Run `xrdb ~/.Xresources`. The cursor size is not updated unless Kitty is relaunched. 

**Environment details**
```
kitty 0.27.0 () created by Kovid Goyal
Linux arch 6.1.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:39 +0000 x86_64
Arch Linux 6.1.9-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/fish
Loaded config files:
  /home/hakon/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close 0
cursor_blink_interval   0.0
font_family             Hack Nerd Font
font_size               10.0
Colors:
	background              #282c34   
	color0                  #282c34   
	color1                  #e06c75   
	color10                 #98c379   
	color11                 #e5c07b   
	color12                 #61afef   
	color13                 #c678dd   
	color14                 #56b6c2   
	color15                 #dcdfe4   
	color2                  #98c379   
	color3                  #e5c07b   
	color4                  #61afef   
	color5                  #c678dd   
	color6                  #56b6c2   
	color7                  #dcdfe4   
	color8                  #5d677a   
	color9                  #e06c75   
	foreground              #dcdfe4   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nvim
	SHELL                               /bin/fish
	DISPLAY                             :0
	USER                                hakon
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/hakon
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Comment by kovidgoyal** [comment]
As far as I know there is no X11 event when xresources are updated. If
there is one then you are welcome to send a patch for it, relevant code
will be in the glfw/x11* files.

**Comment by HakonHarnes** [comment]
> As far as I know there is no X11 event when xresources are updated.

You're right, and that sucks. 

However, most GTK apps listen for the `notify::gtk-xft-dpi` signal which is sent when setting xorg resources in `~/.xsettingsd` and executing `killall -HUP xsettingsd`. I've successfully gotten all of my GTK apps to instantly refresh the DPI and cursor size settings this way. Before I even attempt to make a path for Kitty, is it even possible for Kitty to listen to the `notify::gtk-xft-dpi` signal? 

Is there some way to programmatically tell all running Kitty instances to "refresh" by rereading the xorg resource file, possibly with a keybinding, or even through remote control?

**Comment by kovidgoyal** [comment]
On Sun, Feb 05, 2023 at 02:42:10AM -0800, Håkon Harnes wrote:
> > As far as I know there is no X11 event when xresources are updated.
> 
> You're right, and that sucks. 
> 
> However, most GTK apps listen for the `notify::gtk-xft-dpi` signal which is sent when setting xorg resources in `~/.xsettingsd` and executing `killall -HUP xsettingsd`. I've successfully gotten all of my GTK apps to instantly refresh the DPI and cursor size settings this way. Before I even attempt to make a path for Kitty, is it even possible for Kitty to listen to the `notify::gtk-xft-dpi` signal? 
> 
> Is there some way to programmatically tell all running Kitty instances to "refresh" by rereading the xorg resource file, possibly with a keybinding, or even through remote control?

You can get kitty to re-read its config anytime by sending it SIGUSR1
it's not going to re-read xrdb though. As for the notify::... signal no
idea what that is, I dont do GTK programming. If it's something on DBUS,
then it can be used in kitty see the existing support for instance for 
dark/light change notification.
