### ISSUE TITLE
background_image path doesn't display an image, but works when set from remote using set-background-image

### ISSUE THREAD

**Issue by ManneWas** [kovidgoyal/kitty#5983]
**Describe the bug**
This might just be user error on my part, but no matter how I try and set the background_image, It doesn't get displayed. However if I allow_remote_control, and use `kitty @ set-background-image ~/.config/assets/wallpapers/alena-aenami-escape.png` it works.

**To Reproduce**
1. set background_image path, in my case it's:
```
background_image ~/.config/assets/wallpapers/alena-aenami-escape.png
``` 
2. see no background image
3. set
```
allow_remote_control yes
```
4. run 
```
kitty @ set-background-image ~/.config/assets/wallpapers/alena-aenami-escape.png
```
5. see background image

**Screenshots**
<img width="830" alt="image" src="https://user-images.githubusercontent.com/85845002/216800998-a216754c-0661-477f-b96b-d16f4ae172a6.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/85845002/216801110-da91b327-0b20-4bbb-b3f2-e1a9e8bddaca.png">

**Environment details**
```
kitty 0.27.0 () created by Kovid Goyal
Darwin Manuels-MacBook-Air.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		13.1 BuildVersion:		22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/manne/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
background_image     /Users/manne/.config/assets/wallpapers/alena-aenami-escape.png

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                manne
	XDG_CONFIG_HOME                     /Users/manne/.config

```

**Additional context**
didn't run with --config NONE for the screenshots, seeing as it wouldn't really be applicable to the issue. I've tried placing the image in the kitty config folder and used both path from root and relative to the kitty config directory itself, neither seemed to work. Again this might just be user error on my end, thanks in advance.

Debug output after setting background image using remote. I'm unsure if it's useful, seeings as it's essentially identical, but figured it would be better to include.

```
kitty 0.27.0 () created by Kovid Goyal
Darwin Manuels-MacBook-Air.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		13.1 BuildVersion:		22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/manne/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
background_image     /Users/manne/.config/assets/wallpapers/alena-aenami-escape.png

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                manne
	XDG_CONFIG_HOME                     /Users/manne/.config

```

**Comment by kovidgoyal** [comment]
Only way I can see that happening is if $HOME is incorrect/not defined
in whatever environment you are starting kitty. Try using an absolute
path in kitty.conf

**Comment by ManneWas** [comment]
Same behavior is happening sadly. I've commented out everything except the background_image part to make sure the config is as clean as can be

<img width="703" alt="image" src="https://user-images.githubusercontent.com/85845002/216801932-b9ef38d0-600a-4fe7-8334-91522f895965.png">

```
kitty 0.27.0 () created by Kovid Goyal
Darwin Manuels-MacBook-Air.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		13.1 BuildVersion:		22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/manne/.config/kitty/kitty.conf

Config options different from defaults:
background_image /Users/manne/.config/assets/wallpapers/alena-aenami-escape.png

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                manne
	XDG_CONFIG_HOME                     /Users/manne/.config

```

**Comment by kovidgoyal** [comment]
Run kitty from another terminal and see if any errors are printed to
stderr

**Comment by ManneWas** [comment]
Well that clears some things up. Although it's a pretty freshly set up m1 mac so I find that strange.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/85845002/216802130-5fafd2b1-5899-4f45-a416-62a923e6fd51.png">

**Comment by kovidgoyal** [comment]
Yeah that's not a valid PNG image, probably some other format with a png file extension. Remote control auto converts other image formats to png.

**Comment by ManneWas** [comment]
Ah alright, I'll go see if converting it fixes the issue, if I don't send any reply then just consider this as solved. Thank you very much for your time and effort.
