### ISSUE TITLE
Gcloud CLI

### ISSUE THREAD

**Issue by skar395** [kovidgoyal/kitty#5985]
Hello everyone,
I know that to use remote servers it is recommended to use kitty +kitten ssh myserver command.

i use gcloud cli and i have problem when i connect, how can i deal with it?

**Comment by kovidgoyal** [comment]
I have no idea what that is. The kitty ssh kitten docs tell you what you can do if you have problems connecting to a particular server. https://sw.kovidgoyal.net/kitty/kittens/ssh/#manual-terminfo-copy
