### ISSUE TITLE
Font jumps?

### ISSUE THREAD

**Issue by dR3b** [kovidgoyal/kitty#5988]
**Describe the bug**
Why does the font jump like this when I resize the window?

**To Reproduce**
1. Resize window with mouse

**Screenshots**
https://user-images.githubusercontent.com/9670938/217191008-fb88b826-acb6-4f0b-8ec0-d2aa4c899d08.mp4

**Environment details**
```
kitty 0.27.0 () created by Kovid Goyal
Arch Linux 6.1.9-arch1-1 (/dev/tty)
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/HOME/.config/kitty/kitty.conf
Config options different from defaults:
background_opacity        0.9
click_interval            0.3
cursor_blink_interval     0.0
enable_audio_bell         False
font_family               UbuntuMono
mouse_hide_wait           0.0
remember_window_size      False
repaint_delay             100
scrollback_lines          10000
scrollback_pager          ['less', '+G', '-R']
select_by_word_characters :@-./_~?&=%+#
shell_integration         frozenset({'no-cursor'})
tab_bar_edge              1
term                      xterm-256color
window_border_width       (1.0, 'pt')
window_margin_width       FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)
```
PS: Great work! Love this project!

**Comment by page-down** [comment]
When the window size cannot be divided by the cell size exactly and you want the window to be centered, then the margins will change.

Configure the following option if you want the window to be placed in the upper left corner.
(So the text doesn't "jump".)
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.placement_strategy

**Comment by dR3b** [comment]
This setting helps but is still not perfect:
```
placement_strategy top-left
```
