### ISSUE TITLE
More code documentation and a better CONTRIBUTING.md

### ISSUE THREAD

**Issue by axelkar** [kovidgoyal/kitty#5989]
**Is your feature request related to a problem? Please describe.**
I'm looking to improve Kitty but find its code confusing due to lack of comments and other documentation.

**Describe the solution you'd like**
See title. Perhaps there could be a file documenting Kitty's overall architecture such as the launcher, python, FFI, rendering on different platforms and child processes/threads.

**Additional context**
Have you considered other languages than C like Rust or Go? I feel like they would be more self-documenting and memory-safe.

**Unrelated question but is code related**
In `fonts.c` on the line `render_run(fg, line->cpu_cells + i, line->gpu_cells + i, num_spaces + 1, cell_font_idx, true, center_glyph, -1, disable_ligature_strategy);` should the local `cpu_cell` and `gpu_cell` variables be used instead?

**Comment by kovidgoyal** [comment]
On Tue, Feb 07, 2023 at 06:00:27AM -0800, Axel Karjalainen wrote:
> **Is your feature request related to a problem? Please describe.**
> I'm looking to improve Kitty but find its code confusing due to lack of comments and other documentation.

You are welcome to ask questions if there is something specific you want
to do.

> 
> **Describe the solution you'd like**
> See title. Perhaps there could be a file documenting Kitty's overall architecture such as the launcher, python, FFI, rendering on different platforms and child processes/threads.

Not something I care to write, but contributions are most welcome.

> 
> **Additional context**
> Have you considered other languages than C like Rust or Go? I feel like they would be more self-documenting and memory-safe.

No, I am extremely happy with the combination of Python and C for core
kitty. If you like writing Go work on the kitten part of kitty it is in
Go.

> 
> **Unrelated question but is code related**
> In `fonts.c` on the line `render_run(fg, line->cpu_cells + i, line->gpu_cells + i, num_spaces + 1, cell_font_idx, true, center_glyph, -1, disable_ligature_strategy);` should the local `cpu_cell` and `gpu_cell` variables be used instead?

Sure, assuming i and those variables are not changed before reaching
that point, I am away from my computer so cant check.
