### ISSUE TITLE
Vagrant SSH backspace troubles

### ISSUE THREAD

**Issue by reed-jones** [kovidgoyal/kitty#599]
When I connect to local virtual machines using VirtualBox & Vagrant, using the command `vagrant ssh` my backspace/delete key doesn't appear to work. The characters do in fact get deleted from the buffer, however it looks like I am pressing space/tab with the cursor incrementing to the right, and my mistyped commands remaining. I have also noticed it only appears to happen using ZSH in the virtual machine. Using bash results in the expected behaviour.

Kitty Version: 0.10.1
OS: MacOS
OS Version: 10.13.4
Minimal Config: none
Vagrant Version: 2.1.1
VirtualBox 5.2.12
VirtualMachine: Ubuntu 16.04

**Comment by kovidgoyal** [comment]
These kinds of things are typically caused by whatever shell you are running on the remote machine (in your case the virtual machine) not having access to the kitty terminfo files. You can remedy that by using the ssh kitten, see the entry in the kitty FAQ about it.

**Comment by lfuelling** [comment]
If you only use kitty, you can simply add this alias to your shell rc:

```bash
alias ssh="kitty +kitten ssh"
```

**Comment by gavinhoward** [comment]
Commenting that this fixed my issue with `kitty` and `ssh`, to boost its search engine results.
