### ISSUE TITLE
Setting to automatically save/restore sessions

### ISSUE THREAD

**Issue by jclsn** [kovidgoyal/kitty#5991]
**Is your feature request related to a problem? Please describe.**
Before working I have to create a workspace with several tabs open. I have to do this again after each reboot.

**Describe the solution you'd like**
It would be nice if you could save and restore sessions automatically with all tabs and windows opened.

**Comment by kovidgoyal** [comment]
dup of #1197

**Comment by jclsn** [comment]
Man you are fast
