### ISSUE TITLE
Support disabling leftclick-to-open-url WITHOUT disabling leftclick-to-move-cursor

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#5997]
**Is your feature request related to a problem? Please describe.**
I'm in a Kitty conundrum:
1. I love the [_"Click with the mouse anywhere in the current command to move the cursor there"_ Shell Integration feature](https://sw.kovidgoyal.net/kitty/shell-integration/).
2. I dislike left-click opening URLs. (Reason: I end up accidentally clicking a bit of text I just meant to select, and I accidentally open it. I'm fine Ctrl+Shift+Leftclicking an URL when I actually want to open it)

→ I want leftclick-to-move-cursor, but I don't want leftclick-to-open-url. However, reading the docs and the default kitty.conf, the way to disable leftclick-to-open-url is to `mouse_map left click ungrabbed no_op`, which sadly disables leftclick-to-move-cursor 😕.

**Describe the solution you'd like**
Is there a way to configure kitty.conf to disable leftclick-to-open-url **without** disabling leftclick-to-move-cursor ?

**Describe alternatives you've considered**
None comes to mind

**Additional context**
kitty 0.27.1 + fish 3.6.0 on Linux.
Thanks for kitty 🙂.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Click-the-link-under-the-mouse-or-move-the-cursor


you can slect whatever set of actions you wnat tried.

**Comment by ronjouch** [comment]
Fantastic, thanks Kovid. `mouse_map left click ungrabbed mouse_handle_click selection prompt` is what I want.
