### ISSUE TITLE
When selecting, whitespace at the end of lines disappears

### ISSUE THREAD

**Issue by koterpillar** [kovidgoyal/kitty#60]
When selecting text in Kitty, any whitespace present at the end of a line isn't considered part of the selection.

### Steps to reproduce

* Execute:
```shell
echo; echo 'one            '; echo 'two'; echo
```
* Select and copy the whole output, including blank lines before "one" and after "two".
* Paste elsewhere and examine the contents.

### Expected result

(Note: spaces replaced by dots to illustrate)

```
one............
two
```

### Actual result

```
one
two
```

Termite and XTerm both copy the spaces properly.

I think copying the output exactly is important for a terminal, because, for example, redirecting the above commands to a file will preserve spaces, and so should the terminal.

I started looking at fixing #58, but it seems a proper fix is impossible while `Line` doesn't retain this information.

**Comment by kovidgoyal** [comment]
kitty does not track that information, so this cannot be fixed without extensive changes (basically the unused cell characters are currently a space it would need to be changed to something else) , which IMO are totally not worth it. In thirty years of using terminal I cannot recall a single instance of needing to copy trailing spaces on lines. For that matter, I have vim set to auto-delete trailing spaces on lines on save on all files. Basically trailing spaces on lines are useless everywhere (there probably exist some corner cases where they are useful, but as I said, that is not worth the overhead of tracking unused cells).
