### ISSUE TITLE
`remote_control scroll-window` broken in 27.0 release

### ISSUE THREAD

**Issue by Invertisment** [kovidgoyal/kitty#6000]
**Describe the bug**
I was using this keybind in my config:

```
map alt+u remote_control scroll-window 30- # 30 lines
map alt+d remote_control scroll-window 30+ # 30 lines
```
The release `27.0` has changed something and now I get this error:
```
remote_control mapping failed

Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 721, in call_remote_control
    opts, items = parse_subcommand_cli(c, items)
  File "/usr/bin/../lib/kitty/kitty/rc/base.py", line 423, in parse_subcommand_cli
    raise SystemExit(f'Must specify exactly {command.args.args_count} argument(s) for {command.name}')
SystemExit: Must specify exactly 1 argument(s) for scroll-window

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 701, in remote_control
    self.call_remote_control(self.active_window, args)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 724, in call_remote_control
    raise Exception(str(e)) from e
Exception: Must specify exactly 1 argument(s) for scroll-window


Press e to see detailed traceback or any other key to exit
```

**To Reproduce**
1. Put the specified mapping in config under any key (alt+u is not essential here)
2. trigger the mapping
3. See error

**Additional context**
It worked in 26th version but I don't remember which exact one.

**Comment by Invertisment** [comment]
This issue is probably related to this fix: https://github.com/kovidgoyal/kitty/issues/5294

**Comment by page-down** [comment]
Using `#` at the end of a configuration line to comment is not supported.

https://sw.kovidgoyal.net/kitty/conf/

> Comments can be added to the config file as lines starting with the # character. This works only if the # character is the first character in the line.

Remove those `# 30 lines'.

> I tried to use
> remote_control scroll-window 0.5p-
> ...
> Is this possible to do?

The feature you requested was implemented in version 0.26 (6 months ago) and is not related to this.

**Comment by Invertisment** [comment]
Yes, the feature was implemented and it's actually very good. I didn't even know that it got implemented. Thank you very much.
But `#` worked before that without any issues. That's very weird.
Did you decide to not allow it?

**Comment by page-down** [comment]
> But # worked before ... That's very weird.
> Did you decide to not allow it?

This has never been allowed.

In 0.27, the remote control client is implemented in Go, and the part implemented in Python does more checks on the parsing of arguments rather than discarding unrecognized ones.

You can think of it as a bug, and then the bug is unfortunately fixed in a way that alerts you that there's a problem with your configuration.

**Comment by Invertisment** [comment]
When it says `Must specify exactly 1 argument(s) for scroll-window` I'd like to instead have "needed 1 arg, got 2". Because what I thought was "hey I've sent 0 arguments, there is a bug in the reader"
