### ISSUE TITLE
Error: OpenGL version string retrieval is broken

### ISSUE THREAD

**Issue by anoduck** [kovidgoyal/kitty#6007]
**Describe the bug**
Sometimes you run a simple update, and your entire world falls apart. :cry: 

After a standard system update, kitty stopped working. It output the following error: 

```bash
[042 05:39:44.798560] [glfw error 65544]: OpenGL version string retrieval is broken
[042 05:39:44.799070] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```
I receive the same errors when `kitty --debug-rendering` is executed. Since I run OpenBSD (sighs), guessing I am out of luck until py3-opengl is updated to 3.3.

OS: OpenBSD 7.2 CURRENT
Kitty Version: 0.26.4
OpenGL Version string: 1.4
py3-opengl Version: 3.1.3b2p5

**Comment by Nemris** [comment]
Out of curiosity, did you update the graphics driver? In my case, rebooting was necessary when mine was updated - although that was on Arch.

**Comment by kovidgoyal** [comment]
Dont know what py3-opengl has to do with kitty. kitty does not use it.
kitty calls OpenGL functions directly via C code.

This looks like a driver issue. As the other poster suggested, first try
rebooting your computer. If that does not fix it, then downgrade the GPU
drivers to whatever the last working version was.

**Comment by anoduck** [comment]
> Dont know what py3-opengl has to do with kitty. kitty does not use it. kitty calls OpenGL functions directly via C code.
> 
> This looks like a driver issue. As the other poster suggested, first try rebooting your computer. If that does not fix it, then downgrade the GPU drivers to whatever the last working version was.

Somehow, I feel I am stuck in an episode of "The IT Crowd". 

@Nemris OpenBSD and ArchLinux have different release schedules. What will come through as a driver update on Linux, will hit most distros within a matter of days, but will take months or a year to complete testing, benchmarking, and hardening before released on OpenBSD. OpenBSD also does not support nonfree third party drivers.

@kovidgoyal For the record, my driver hasn't been updated in 7 months. The C lib for OpenGL is around 1.x. Regardless if it is a driver issue, I am probably out of luck, since it is the only driver compatible for my graphics card in OpenBSD.

Hopefully, an update will come through the ports tree and fix it.

**Comment by sthen** [comment]
Part of the recent Mesa update has been backed out in OpenBSD (https://marc.info/?l=openbsd-cvs&m=167842171027689&w=2) which has worked around this issue.

**Comment by anoduck** [comment]
@sthen Thank, God! Running sysupdate now.
