### ISSUE TITLE
working with tmux on Mac?

### ISSUE THREAD

**Issue by sthtodo** [kovidgoyal/kitty#601]
When I run tmux, it gives me this, mac osx 10.13.5
`~ tmux   
open terminal failed: can't find terminfo database
open terminal failed: can't find terminfo database`

**Comment by kovidgoyal** [comment]
tmus works fine on the mac with kitty. That error means tmux is unable to find the kitty terminfo files. If you are sshing into a different computer then this is in the kitty FAQ. If not, then see #310

**Comment by ipstone** [comment]
I encountered the same problem on mac osx 10.12.6; in which tmux session was started before starting kitty. 

After fully closing the tmux sessions; and restart tmux in a kitty window, everything works fine. Just want to keep a note here in case others encounter this in the future.
