### ISSUE TITLE
Double Width Characters in Tab Titles Are Not Centered

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#6013]
**Describe the bug**
With just a single character in tab titles, certain double-width Unicode characters do not appear dead-centered.

**To Reproduce**
1. Download and install FontAwesome for Desktop 5:
    ```
    $ curl -C - -O https://use.fontawesome.com/releases/v5.15.4/fontawesome-free-5.15.4-desktop.zip
    $ unzip fontawesome-free-5.15.4-desktop.zip
    $ cp fontawesome-free-5.15.4-desktop/otfs/Font\ Awesome\ 5\ Free-Solid-900.otf ~/.local/share/fonts/
    $ fc-cache -f -v ~/.local/share/fonts/
    ```
2. Launch kitty like this:
    ```
    kitty --config NONE -o 'symbol_map U+E005-U+F8FF Font Awesome 5 Free Solid' -o 'allow_remote_control yes'
    ```
4. `kitty @ set-tab-title $'\uf013'`
5. `kitty @ launch --type=tab --tab-title=$'\uf015'`

**Screenshots**
![Screenshot from 2023-02-12 22-06-37](https://user-images.githubusercontent.com/40219235/218385860-c38c75f3-a0b7-44be-bce7-83d28323fbab.png)
![Screenshot from 2023-02-12 22-06-27](https://user-images.githubusercontent.com/40219235/218385863-bd9b28fe-3581-4902-a3b3-e4e230f69a98.png)

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Linux byteevo 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64
Ubuntu 20.04.5 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  symbol_map U+E005-U+F8FF Font Awesome 5 Free Solid
  allow_remote_control yes

Config options different from defaults:
allow_remote_control yes
symbol_map:
	U+e005 - U+f8ff → Font Awesome 5 Free Solid

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
- This issue does _not_ reproduce when using the Debian provided `fonts-font-awesome` package in Ubuntu 20.04 LTS.  The built-in Debian package, however, uses FontAwesome 4, an older version with different looking glyphs and different licensing.
- As a workaround, I tried adding a trailing space to account for the spacing that double-width characters need with no luck, like this: 
    ```
    kitty @ set-tab-title $'\uf013 '
    kitty @ set-tab-title $'\uf013\u00a0'
    ```

**Comment by salmankhilji** [comment]
On the contrary, this glyph renders centered:

```
kitty @ set-tab-title $'\u26a0\ufe0f'
```

Not sure if its a FontAwesome issue or kitty.

**Comment by kovidgoyal** [comment]
These will be symbols that are official width one. But kitty will render them in an adjacent space if available. So simply add a trailing space after the symbol, or use narrow_symbols in kitty.conf. See https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty

**Comment by salmankhilji** [comment]
> These will be symbols that are official width one. But kitty will render them in an adjacent space if available. So simply add a trailing space after the symbol, or use narrow_symbols in kitty.conf. See https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty

Actually, in my scenario, all I have is a symbol with no text following it. i.e., the entire tab title is a single Unicode character.

If I add a space after the single-letter symbol, the space gets truncated.  (Unless, of course, if I add another character after the space.)  As you can see, I unsuccessfully tried adding a trailing space (and a trailing Unicode non-breaking space, like this:

```
kitty @ set-tab-title $'\uf013 '
kitty @ set-tab-title $'\uf013\u00a0'
```

(Thinking out aloud: I wonder if I can use a non-printable character after the space to trick kitty into not trimming the space.)

**Comment by kovidgoyal** [comment]
In that case your best bet is indeed to use a non-printing character.

**Comment by 3rd** [comment]
Commenting to help anyone who encounters this issue and uses `narrow_symbols` to prevent certain PUA glyphs from expanding more than they should.

You might run into this **glyphs not vertically centered** issue when using `narrow_symbols` and following the official recommendation of using **"Symbols Nerd Font Mono"**.
To fix it **just use a patched font** instead of "Symbols Nerd Font Mono", just for the symbols.

I haven't encountered any issues with nerd fonts patching breaking anything myself, but it's funny that in this case using a patched font fixes the rendering instead of breaking it.
