### ISSUE TITLE
gpg: Screen or window too small

### ISSUE THREAD

**Issue by glensc** [kovidgoyal/kitty#6018]
**Describe the bug**

gpg agent askpass refuses to run.

**To Reproduce**

```
$ brew install pass gnupg
$ ... setup pass and gpg agent
$ echo RELOADAGENT | gpg-connect-agent  # in case agent already cached token
$ pass show -c secret
gpg: public key decryption failed: Screen or window too small
gpg: decryption failed: Screen or window too small
$  echo $LINES $COLUMNS
32 91
$ gpg-agent --version
gpg-agent (GnuPG) 2.4.0
libgcrypt 1.10.1
```

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Darwin grenouille 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.1 BuildVersion:		22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH  *redacted*
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.CQic1NST36/org.xquartz:0
	USER                                glen
	LC_TERMINAL_VERSION                 3.5.0beta6
	LC_TERMINAL                         iTerm2
```

**Comment by page-down** [comment]
dup of https://github.com/kovidgoyal/kitty/issues/5844

Try using `pinentry-tty` or `pinentry-mac`.

**Comment by glensc** [comment]
I definitely searched for "Screen or window too small" before making issue, I wonder why I got no results. I searched again and now both these issues pop up:
- https://github.com/kovidgoyal/kitty/search?q=%22Screen+or+window+too+small%22

**Comment by liangyepianzhou** [comment]
I found the same issue. Wait a while and try again, and the GPG runs success.

Issue: GPG fails to sign with the error "Screen or window too small" due to the terminal window being too small to display the necessary user interface.

Solution: You can try adjusting the size of the terminal window by dragging its edges or corners to make it larger. If the problem persists, wait for a while and try again to ensure that the terminal window is large enough. Alternatively, you can try using other terminal applications such as iTerm2 or PuTTY to see if they can solve this issue.

**Comment by glensc** [comment]
the answer is in duplicate issue:
- https://github.com/kovidgoyal/kitty/issues/5844#issuecomment-1438039666

**Comment by Kate941-su** [comment]
@glensc 
I encountered the same problem and I tried to execute the following command.

I could solve the problem

```
gpgconf --kill gpg-agent
gpgconf --launch gpg-agent
```

**Comment by KENILSHAHH** [comment]
THanks much @Kate941-su

**Comment by ZuzkaP** [comment]
gpg --armor --export cherrypeak-aws-dev@cherrypeak.eu

how to save it as file asc

**Comment by michft-v** [comment]
The above `gpgconf --kill` worked for me. Mine is if I had a cmux (ghostty) terminal open across shutdowns, the running and non-running agents got out of sync AFAICT.
