### ISSUE TITLE
Not always starting with maximized window  Mac OS

### ISSUE THREAD

**Issue by marcoSven** [kovidgoyal/kitty#6021]
**Describe the bug**
I am trying to always launch with a maximized window. 

When launching Kitty from the Dock for the first time the window is maximized. 

The problem is when I launch another window with keyboard shortcuts 

```
map cmd+t new_os_window_with_cwd
map cmd+n new_os_window

```

or from the Dock with right click "new OS Window".

The issue is related to the `hide_window_decorations` set to `titlebar-only` when set to `no` the window is always fully maximized. 

It appears that the removed titlebar is not considered when trying to fully maximize the window - see screen recording.

Running `kitty --start-as maximized` always opens the window fully maximized. 

How can we open a new window via `new_os_window` and `new_os_window_with_cwd` fully maximized too?

**Screenshots**

Launching a second new window via `map cmd+n new_os_window`

https://user-images.githubusercontent.com/3860298/218876232-5a7c9320-be64-496a-9cf7-408d24d2ae19.mov

**Environment details**
```
mac 13.1 (22C65)
kitty 0.27.1
```

**Additional context**
``` 
# kitty.config
hide_window_decorations titlebar-only
remember_window_size  yes

allow_remote_control yes

```

```
# macos-launch-services-cmdline
--start-as maximized

```

**Comment by marcoSven** [comment]
The window is always fully max when I change this setting to `no` or `yes` 

> It appears that the removed titlebar is not considered when trying to fully maximize the window 

`hide_window_decorations no`

<img width="1438" alt="Screenshot 2023-02-14 at 15 01 23" src="https://user-images.githubusercontent.com/3860298/218883118-99c17443-27aa-41f6-968b-47a5ead6adf6.png">

`hide_window_decorations yes`

<img width="1440" alt="Screenshot 2023-02-14 at 15 02 47" src="https://user-images.githubusercontent.com/3860298/218883291-8a5447c6-0b20-45a8-b479-90673a9f531d.png">


Ideally, I would like to keep the rounded window borders only to keep it consistent with other applications.

**Comment by page-down** [comment]
The OS window needs to be resized again after hiding the title bar to try to reach the remembered window size.
This might also involve moving the window position.

Until launch adds more fine-grained controls, you can use `combine`, `toggle_maximized` to maximize the window.

```shell
kitty -o 'map f1 combine : launch --type os-window : toggle_maximized'
```

https://sw.kovidgoyal.net/kitty/actions/#action-toggle_maximized

**Comment by marcoSven** [comment]
Yes thank you that is my current workaround
 
```
# map cmd+t new_os_window_with_cwd
map cmd+t combine : launch --type=os-window --cwd=current : toggle_maximized
# map cmd+n new_os_window
map cmd+n combine : launch --type=os-window : toggle_maximized

```

But this is not ideal because of the window "zoom" animation 😄

**Comment by page-down** [comment]
> But this is not ideal because of the window "zoom" animation

Reducing the time might make you feel better, though still not maximizing the window before it shows up.

```shell
defaults write net.kovidgoyal.kitty NSWindowResizeTime -float 0.001
```

**Comment by marcoSven** [comment]
Thank you I appreciate it

**Comment by marcoSven** [comment]
> The OS window needs to be resized again after hiding the title bar to **try to reach the remembered window size**.

What is interesting to me is the fact that when launching the first instance via the GUI the window is fully maximized even with this setting `hide_window_decorations titlebar-only`

> try to reach the remembered window size

I was hoping that changing this setting `remember_window_size` to `no` would help but all subsequent windows are now sized based on the width height setting. 

I also tried setting the window sizes ( with pixels or columns). Even when setting the height to a larger value than is available on my screen, the window height is always missing the title bar's height ( the same as you can see in my recordings above ). 

Would be great if there could be a configuration in the config similar to this 

```
# macos-launch-services-cmdline
--start-as maximized
```

**Comment by kovidgoyal** [comment]
This is a limitation of macOS' window manager. Nothing kitty can do to fix it, other than adding hacks to try to workaround the broken sizing from the window manager or actually adding controls for os window state to launch. I dont mind adding those controls but I am not particularly motivated to do so personally, patches are welcome.

**Comment by page-down** [comment]
> ... the removed titlebar is not considered ...
> ... I would like to keep the rounded window borders ...

This issue has been fixed in master, and you can enjoy your rounded borders without `--os-window-state maximized`.

> But this is not ideal because of the window "zoom" animation

This one has also been improved, no more "zoom" animations, only when using `launch --os-window-state`.
You can compile from source to try it out, or wait for an updated nightly release.
