### ISSUE TITLE
no title visible in polybar 

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [kovidgoyal/kitty#6022]
**How to set window title in polybar? **
When I use VS code or any tab in browser, it shows the description in polybar. Like this - 

![Screenshot_20230215_104829](https://user-images.githubusercontent.com/76522725/218939491-30289ce4-7fae-4a02-bd1d-811b01246597.png)

But it isnt showing anything while using kitty terminal :( , it is showing default desktop. How to set it ? if its possible to set it?
Is it an issue related to kitty or polybar or kwin window manager or kde related? what to do?
![Screenshot_20230215_105324](https://user-images.githubusercontent.com/76522725/218940141-ed83c108-2611-43e3-92b9-add835bb2c45.png)

**Environment details**
OS - arch  kde-plasma wayland

**Comment by page-down** [comment]
I don't believe polybar supports native wayland, if that's the reason for not being able to get the title.

You can try the following configuration, I'm not sure it helps, you need to ask in the polybar project.

```shell
kitty -o linux_display_server=x11
```

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.linux_display_server

**Comment by piush-terminalwitchcraft** [comment]
thanks ! it worked
