### ISSUE TITLE
Add launch command "--start-as" option  

### ISSUE THREAD

**Issue by marcoSven** [kovidgoyal/kitty#6026]
**Is your feature request related to a problem? Please describe.**
See issue #6021

**Describe the solution you'd like**
Add `--start-as` to the [launch command option](https://sw.kovidgoyal.net/kitty/launch/#options) to control how the initial kitty window is created. 
Default: normal 
Choices: fullscreen, maximized, minimized, normal

example to launch with a maximized window.
`launch --type=os-window --start-as=maximized`

The `--start-as` option is already available in the CLI https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-start-as

**Comment by kovidgoyal** [comment]
As I said in the previous issue, this is not something thats worth the
effort to me, but patches are welcome.

**Comment by page-down** [comment]
@kovidgoyal
How do I set the value for `wndconfig->maximized`?
If we can get the following code to work when the window is created, the window will be displayed in the maximized state. So the maximizing animation will not appear.

```objc
if (wndconfig->maximized)
    [window->ns.object zoom:nil];
```

I believe that the function glfwCreateWindow needs extra parameters for this purpose.

Related issue:
https://github.com/kovidgoyal/kitty/issues/4949

**Comment by kovidgoyal** [comment]
On Thu, Feb 16, 2023 at 03:11:26AM -0800, page-down wrote:
> @kovidgoyal
> How do I set the value for `wndconfig->maximized`?

glfwWindowHint()

> If we can get the following code to work when the window is created, the window will be displayed in the maximized state. So the maximizing animation will not appear.
> 
> ```objc
> if (wndconfig->maximized)
>     [window->ns.object zoom:nil];
> ```
> 
> I believe that the function glfwCreateWindow needs extra parameters for this purpose.

No, you can just call glfwWindowHint() before calling
glfwCreateWindow(). Since its global it will eed to be called for every
glfwCreateWindow().

> 
> Related issue:
> https://github.com/kovidgoyal/kitty/issues/4949
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/6026#issuecomment-1432921733
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by marcoSven** [comment]
🙏 Thank you @kovidgoyal - I was planning to look into it this weekend.
