### ISSUE TITLE
How to hide KITTY_DATA when using ssh ? 

### ISSUE THREAD

**Issue by violin0622** [kovidgoyal/kitty#6027]
`kitty +kitten ssh ` is very good , i like it , but one small thing:

when I login into remote server, kitty will print a lot annoying encoded data between `KITTY_DATA_BEGIN` and `KITTY_DATA_END` , like this:

![截屏2023-02-16 11 46 41](https://user-images.githubusercontent.com/6880156/219263751-4713a220-9ae9-415f-86be-3dc345d7150f.png)

Is there any method or config for hiding it ?

**Comment by violin0622** [comment]
PS: `sph` is a simple wrapper of `kitty +kitten ssh `

**Comment by kovidgoyal** [comment]
That's how the ssh kitten transmits data. If its showing up on your screen something is broken on your remote server. Read the ssh kitten docs https://sw.kovidgoyal.net/kitty/kittens/ssh/
