### ISSUE TITLE
Vim like interactive search and highlight

### ISSUE THREAD

**Issue by violin0622** [kovidgoyal/kitty#6028]
**Is your feature request related to a problem? Please describe.**
I think search and highlight feature of kitty is strong in function but weak in experience. 
When I want to highlight some text, I have to open a new panel , input  a command (maybe pretty long), and go back.
If  misinput, I have to repeat steps above. 

![截屏2023-02-16 12 11 58](https://user-images.githubusercontent.com/6880156/219266662-b4fe5cea-75fd-4aab-962c-5556efd6849e.png)

**Describe the solution you'd like**
I known it's hard for a GPU accelerate terminal emulator to open a flowing window which iTerm does.
But i think a vim like approach of interactive search (with incsearch and highlight option) is practical. 
I found another terminal emulator `WezTerm`  has done it , 
therefor, may Kitty implement something similar ? 

![截屏2023-02-16 12 13 33](https://user-images.githubusercontent.com/6880156/219266839-18fac373-2ab1-497f-a357-7300d7299914.png)

**Comment by kovidgoyal** [comment]
You can use actual vim to do it in kitty.

https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer
