### ISSUE TITLE
Support of shell integrating like it was made at iTerm2

### ISSUE THREAD

**Issue by vkravets** [kovidgoyal/kitty#603]
See https://www.iterm2.com/documentation-shell-integration.html

**Comment by kovidgoyal** [comment]
Most of these are all things that should be done by the shell, and indeed are done by modern shells anyway. As such I am not particularly interested in this list. Of course, I may have missed some use case, if so feel free to describe those in more details.

Just for fun, here is how you would do some of these things in kitty, withoutneeding any special integration:

1) Marks: Simply open the scrollback buffer in less using ctrl+shift+h and type /\$ to jump from one shell prompt to the next (might need to change the exact search expression to suit your actual prompt

2) Alert: Press Ctrl+Z; then run fg; printf '\a'
kitty will beep when the long running command finishes (if you want a modal dialog replace printf '\a' with
kitty sh -c 'printf command finished press enter to quit; read'

3) Previous command status: This can be done by the shell, simpl have it display previous command status in the prompt (prefereable on the right side of the screen if your shell supports it, which most do)

4) scp: That there is no direct anaolog of, you would have to type in the scp command manually

5) command history/completion: All managed perfectly well by the shell itself.The only limitation being you cannot access the history for a server you cannot sshin into at the moment

The remaining all seem to be GUI things that dont fit with kitty anyway.
