### ISSUE TITLE
Random UI freezes on MacBook 13'' M1

### ISSUE THREAD

**Issue by indutny** [kovidgoyal/kitty#6034]
**Describe the bug**

Hello! Thanks for an excellent app!

I don't have a clear repro, but my Kitty terminal frequently stops redrawing UI altogether even though the underlying app (vim or zsh) still receives the keystrokes. I'm happy to run any debug tooling to help investigate this, but might need pointers!

What's interesting is that if I switch macOS spaces from and back to Kitty - it self-heals, but it a bit annoying to do so I'd love to see it fixed!

**To Reproduce**
1. Use the latest Kitty (0.27.1)
2. Have multiple tabs open
3. Have vim in one of the tabs
4. Edit code and observe random freezes of Kitty's UI

**Screenshots**

Sorry, screenshots won't really help here, but if you are really interested in it - I could try recording a screencast.

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Darwin Fedors-MBP.lan 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		13.2.1 BuildVersion:		22D68
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/indutny/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close 1
enable_audio_bell       False
font_family             Monaco Regular
font_size               15.0
tab_bar_edge            1
tab_bar_style           powerline
tab_switch_strategy     left
Added shortcuts:
	cmd+f →  show_scrollback
	cmd+left →  previous_tab
	cmd+right →  next_tab
Changed shortcuts:
	cmd+1 →  goto_tab 1
	cmd+2 →  goto_tab 2
	cmd+3 →  goto_tab 3
	cmd+4 →  goto_tab 4
	cmd+5 →  goto_tab 5
	cmd+6 →  goto_tab 6
	cmd+7 →  goto_tab 7
	cmd+8 →  goto_tab 8
	cmd+9 →  goto_tab 9
Colors:
	background              #002b36   
	color0                  #073642   
	color1                  #dc322f   
	color10                 #586e75   
	color11                 #657b83   
	color12                 #839496   
	color13                 #6c71c4   
	color14                 #93a1a1   
	color15                 #fdf6e3   
	color2                  #859900   
	color3                  #b58900   
	color4                  #268bd2   
	color5                  #d33682   
	color6                  #2aa198   
	color7                  #eee8d5   
	color8                  #00495c   
	color9                  #cb4b16   
	foreground              #839496   
	selection_background    #073642   
	selection_foreground    #93a1a1   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                indutny
```

**Additional context**
~~Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.~~

**Comment by kovidgoyal** [comment]
This will be some issue with your graphics drivers/GPU setup. Probably
something related to CVDisplayLink and multiple monitors/graphics cards,
if I had to guess.

You can run kitty with --debug-rendering and that will show more
information. This is something specific to your setup, so closing. Feel
free to continue posting, if you find more information or a reproducer.

**Comment by indutny** [comment]
I'm not using any external GPU or monitor. This is a stock MBP 13'' M1 with stock macOS. I'll give it a go with `--debug-rendering`, but FWIW it also happens to my friend: https://mastodon.xyz/@saghul/109881561408505597 .

**Comment by indutny** [comment]
@kovidgoyal this is what is written to the debug log: https://gist.github.com/indutny/69b25d6fcbcde28e792492d534d6ec60

**Comment by indutny** [comment]
Hm... looks like this is triggered by a bunch of `applicationDidChangeScreenParameters:`. I wonder why this event happens all of a sudden, and why a bunch of them happen in the row?

**Comment by kovidgoyal** [comment]
That's a notification from the OS that the connected displays have
changed or been re-configured: https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428424-applicationdidchangescreenparame?language=objc

As I said this is multi-monitor related. In your case if it isnt actual
hardware monitors either the current monitor is being reconfigured
repeatedly by something or you have a malfunctioning driver.

**Comment by indutny** [comment]
Yeah, it seems to be the case. I'm not sure if I run any custom drivers except maybe Parallels does?

**Comment by kovidgoyal** [comment]
Sorry I am not a mac user so I dont have a lot of insight to offer.
If you wish to investigate further I can point you to where in the kitty code
to look.

**Comment by indutny** [comment]
No problem at all, and thanks for an amazing terminal! I patched the code already and waiting for the issue to reproduce. Will let you know how it goes!
