### ISSUE TITLE
Open In KItty option in the context menu

### ISSUE THREAD

**Issue by AyushSehrawat** [kovidgoyal/kitty#6037]
**Is your feature request related to a problem? Please describe.**
I want to add an option in the context menu ( which can be opened when you go to the file manager and right click ) which says `Open In Kitty` ( similar to Open in Terminal option shown by default ).

**Describe the solution you'd like**
A way to do it. I know it's not a kitty related feature request , rather ubuntu related, but i didn't find anything about it.
What i want - Able to show Open in Kitty which opens kitty in the directory of where i clicked , like i go to `~/.config` in Files ( file manager ) and right click , it shows `Open in Kitty` , clicking it opens kitty in the same directory ( i.e `~/.config` )

**Describe alternatives you've considered**
NIL

**Additional context**
NIL

**Comment by kovidgoyal** [comment]
You should ask for help in a ubuntu forum. Or post in the discussions. THis is not an issue.
