### ISSUE TITLE
unwanted trailing empty line when kitty +kitten icat writes into rightmost cell on screen

### ISSUE THREAD

**Issue by gknittl** [kovidgoyal/kitty#6039]
Thank you for kitty and kitty +kitten icat in particular. I find icat makes the terminal in some ways more powerful than dedicated image viewers like feh.

This is a very small issue with icat, but I'm bringing it to your attention in the hopes it's easy to eliminate.
As far as I can tell icat uses terminal space in increments of character cells, not pixels. 
When icat writes an image that is exactly as wide as the screen it appends a newline.
icat appends a newline for all images that are wider than the width of the terminal in character cells minus 1 character cell.
This also occurs with  --align left.
![Screenshot from 2023-02-19 22-31-34](https://user-images.githubusercontent.com/102946889/220010728-5ad61957-c8f1-4df3-90f3-d101be277f32.png)
[test.sh.txt](https://github.com/kovidgoyal/kitty/files/10779637/test.sh.txt)

I would like to be able to write images to the full terminal width without a mandatory newline. Since icat also uses integral values of cell heights, in most cases there is already some unused vertical space that is enough (to my taste) to separate images vertically.

script to reproduce attached as test.sh.txt
#!/bin/bash
set -x
IFS=x read pix_width pix_height < <(kitty +kitten icat --print-window-size)
term_width=$(tput cols)
term_height=$(tput lines)
cell_width=$((pix_width/term_width))
cell_height=$((pix_height/term_height))
echo unwanted trailing line
convert -size ${pix_width}x$cell_height canvas:white png:-|kitty +kitten icat
echo no trailing line
convert -size $((pix_width-cell_width))x$cell_height canvas:white png:-|kitty +kitten icat
echo unwanted trailing line
convert -size $((pix_width-cell_width+1))x$cell_height canvas:white png:-|kitty +kitten icat

screenshot attached as Screenshot from 2023-02-19 22-31-34.png

kitty --config NONE
kitty --version 0.27.1

convert -version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

**Comment by kovidgoyal** [comment]
Use --place then it wont. Basically the graphics protocol requires the
cursor to move to the cell after the image, unless C=1 (no cursor
movement) is specified. --place does that (as of kitty version 0.27.0).

**Comment by gknittl** [comment]
Thanks as always for your prompt responses. The issue with --place is that it leaves the cursor at the top of the image. When I'm done filling up the window with images, I typically want to be at an exposed command prompt to do something with the images. 

convert -size 0x0 canvas:transparent png:-| kitty +kitten icat --place 0x0@50x50 will move the prompt to any arbitrary location including above the current prompt or convert -size 0x190 canvas:transparent png:-| kitty +kitten icat, will advance the cursor by the number of lines corresponding to 190 pixels which works around that issue since 190 could be any arbitrary number.  Echo can advance an arbitrary number of lines.  This function may also be accessible from terminal command codes...

I will also experiment with z-index and writing over image backgrounds, but that can be hard to read depending on the image. It would be nice to conserve window real estate by overwriting and this is something that image viewers like feh just can't do. Could the command line font automatically contrast with the underlying image pixel by pixel?

As usual you have provided a lot of powerful function and it takes me a while to wrap my mind around all the possibilities. I still think something is missing in the icat interface to the underlying image protocol. How about the ability to specify --place and optionally advance the cursor to the next line after the image without the convert hack? Or maybe a helper function or example to write the image protocol directly from icat. or how about kitty +kitten icat --place syntax to place the command prompt independently of an image without the convert hack?

None of this is urgent, You have already provided plenty of function. I understand you have limited time and you want to keep the code as simple as possible and so you should. No need to respond. This is mainly for the benefit of anyone else that is experimenting with icat.

**Comment by kovidgoyal** [comment]
On Mon, Feb 20, 2023 at 03:30:23PM -0800, gknittl wrote:
> Thanks as always for your prompt responses. The issue with --place is that it leaves the cursor at the top of the image. When I'm done filling up the window with images, I typically want to be at an exposed command prompt to do something with the images. 

Do some maths in your script. Use icat --print-window-size to get the
screen size in pixels. Then calculate the size of a cell in pixels since
you know how many cells there are in the screen using LINES/COLS or
whatever other mechanism. Then after --place simply output that many
newlines.

> 
> convert -size 0x0 canvas:transparent png:-| kitty +kitten icat --place ***@***.*** will move the prompt to any arbitrary location including above the current prompt or convert -size 0x190 canvas:transparent png:-| kitty +kitten icat, will advance the cursor by the number of lines corresponding to 190 pixels which works around that issue since 190 could be any arbitrary number.  Echo can advance an arbitrary number of lines.  This function may also be accessible from terminal command codes...
> 
> I will also experiment with z-index and writing over image backgrounds, but that can be hard to read depending on the image. It would be nice to conserve window real estate by overwriting and this is something that image viewers like feh just can't do. Could the command line font automatically contrast with the underlying image pixel by pixel?

No, there is no automatic contrast like that, it would look pretty
horrible and be very slow perfomance wise. The usual solution for
displaying text over images is either to simply display a semi opaque
black/white rectangle over the regions where there is going to be text
and write text over that. Rather like have a transparent terminal.
