### ISSUE TITLE
kitten diff - pygments_style option not working

### ISSUE THREAD

**Issue by miguelbarao** [kovidgoyal/kitty#6042]
**Describe the bug**
The `pygments_style` option in `diff.conf` doesn't seem to be working, always shows the default theme for any valid pygments style.
Trying an invalid style and kitty complains with `pygments style "fjdklsfjd" not found`, so the option is seems to be running.

**To Reproduce**
Add `pygments_style perldoc` in `~/.config/kitty/diff.conf` and run `kitty +kitten diff file1 file2`.
Colors stay at the default.

**Environment details**

kitty 0.27.1
Ubuntu 22.04.2 LTS
wayland

**Additional context**
The problem persists with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
pygments_style does not change the colors of the kitten, only the colors
used by syntax highlighting. To change colors, use the rest of the color
settings.
