### ISSUE TITLE
map ctrl+space autosuggest-accept unbinds after ssh

### ISSUE THREAD

**Issue by jiriks74** [kovidgoyal/kitty#6046]
**Describe the bug**
I use `map ctrl+space autosuggest-accept` to bind `zsh-autosuggestions` completion. It's in my `kitty.conf` and works as expected.

But after using ssh (`kitty +kitten ssh`) the keybind is unmapped and I have to restart kitty for it to work again

**To Reproduce**
1. Use ZSH with autosuggestions
2. Add this line to `kitty.conf`: `map ctrl+space autosuggest-accept`
3. Reload kitty
4. Use `ctrl+space` to complete a suggestion
5. Connect to a server using `kitty +kitten ssh`
6. Exit the server and try using `ctrl+space` to complete a suggestion

<details>
<summary><b>Environment details</b></summary>

```
kitty 0.27.1 () created by Kovid Goyal
Linux jirka-GarudaArch 6.1.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:11 +0000 x86_64
Garuda Linux 6.1.12-zen1-1-zen (/dev/tty)

DISTRIB_ID=Garuda
DISTRIB_RELEASE=Soaring
DISTRIB_DESCRIPTION="Garuda Linux"
DISTRIB_CODENAME="Talon"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/jirka/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.925
Added shortcuts:
	ctrl+space →  autosuggest-accept
Colors:
	active_border_color     #b4befe   
	active_tab_background   #cba6f7   
	active_tab_foreground   #11111b   
	background              #1e1e2e   
	bell_border_color       #f9e2af   
	color0                  #45475a   
	color1                  #f38ba8   
	color10                 #a6e3a1   
	color11                 #f9e2af   
	color12                 #89b4fa   
	color13                 #f5c2e7   
	color14                 #94e2d5   
	color15                 #a6adc8   
	color2                  #a6e3a1   
	color3                  #f9e2af   
	color4                  #89b4fa   
	color5                  #f5c2e7   
	color6                  #94e2d5   
	color7                  #bac2de   
	color8                  #585b70   
	color9                  #f38ba8   
	cursor                  #f5e0dc   
	cursor_text_color       #1e1e2e   
	foreground              #cdd6f4   
	inactive_border_color   #6c7086   
	inactive_tab_background #181825   
	inactive_tab_foreground #cdd6f4   
	mark1_background        #b4befe   
	mark1_foreground        #1e1e2e   
	mark2_background        #cba6f7   
	mark2_foreground        #1e1e2e   
	mark3_background        #74c7ec   
	mark3_foreground        #1e1e2e   
	selection_background    #f5e0dc   
	selection_foreground    #1e1e2e   
	tab_bar_background      #11111b   
	url_color               #f5e0dc   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                jirka
	XCURSOR_SIZE                        24
	LC_ADDRESS                          cs_CZ.UTF-8
	LC_IDENTIFICATION                   cs_CZ.UTF-8
	LC_MEASUREMENT                      cs_CZ.UTF-8
	LC_MONETARY                         cs_CZ.UTF-8
	LC_NAME                             cs_CZ.UTF-8
	LC_NUMERIC                          cs_CZ.UTF-8
	LC_PAPER                            cs_CZ.UTF-8
	LC_TELEPHONE                        cs_CZ.UTF-8
	LC_TIME                             cs_CZ.UTF-8
	XDG_CONFIG_DIRS                     /home/jirka/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/jirka/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session3
	XDG_SESSION_TYPE                    x11
	XDG_VTNR                            1
```

</details>

**Additional context**
I have `bindkey '^ ' autosuggest-accept` in my `.zshrc` but that does not work for kitty (works for everything else). The same zsh configuration is on the server I'm connecting to. Could be that it's rebound by the config on the server but that should not be the case as it does not work on the local config. The configs are completely same.

**Comment by page-down** [comment]
> I have bindkey '^ ' ... but that does not work for kitty ...

Remove your `map ctrl+space ...` in kitty.conf.
Any configured shortcut key will perform the specified action and will not be sent to the running process.
The action `no_op` can be used to unmap a shortcut key.

https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

> ... works as expected.
> ... But after using ssh ... the keybind is unmapped ...
> ... I have to restart kitty ...

You need to make sure that any key sequences sent by this alias are recognized on the remote host.
Since you didn't give details of the configuration, I'm guessing that your alias sends another key that is not bound in the remote system's zsh.

No, running ssh kitten will not unbind shortcuts.

@kovidgoyal
The aliases are not listed in debug_config.

**Comment by kovidgoyal** [comment]
On Mon, Feb 20, 2023 at 06:18:45PM -0800, page-down wrote:
> @kovidgoyal
> The aliases are not listed in debug_config.

Since invalid mappings are ignored its not going to show up in 
kitty.conf.

@OP: You need to map ctrl+space in zshrc. ctrl+space in the legacy
terminal key encoding is the null byte. So map that to whatever action
you want. Then configure the ssh kitten to copy zshrc to remote hosts
automatically and it will work on your remote host as well.

**Comment by page-down** [comment]
> Since invalid mappings are ignored its not going to show up in kitty.conf.

Oh, It is true that the keys do not appear. I forgot about that.
But all the `actions_alias` are indeed not listed, and I specifically tested that when I replied.

**Comment by kovidgoyal** [comment]
kitty -o 'action_alias launch_tab launch --type=tab --cwd=current' -o 'map f1 launch_tab'

and f1 -> launch_tab

shows up in debug config.  Do you mean launch_tab is not expanded? I dont see the need for it.

**Comment by page-down** [comment]
> Do you mean launch_tab is not expanded?

Something like `env`.
Might be a little bit useful when troubleshooting problems.

```log
Config options different from defaults:
env:
{'DEBUG': 'test'}
```

It's nice to have that, but it's not anything important.

> Since invalid mappings are ignored its not going to show up ...

```shell
kitty -o 'map f1 not-exists' kitty +kitten show_key -m kitty
```

```log
Added shortcuts:                                                                                                                                                
        f1 →  not-exists
```

It looks like the "invalid" mappings are listed without a problem.

Configuring a non-existent action for a shortcut is not considered invalid and does not report any errors.
An unrecognized action will not prevent the keys from being sent to child.

@jiriks74

> But after  ... I have to restart kitty for it to work again
> ... should not be the case as it does not work on the local config.

- The zsh shell run directly by kitty responds to ctrl+space(NUL) normally.
- Exit after running ssh (or ssh kitten).
- The zsh run directly by kitty is not responsive to ctrl+space, need to restart kitty to get local shell working.

You can check what this shortcut actually sends when it "doesn't work properly".
Some how this sounds like it entered some keyboard mode in ssh and then didn't exit (reset).

Try to reset the terminal using the default key `ctrl+shift+delete`.
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal

**Comment by jiriks74** [comment]
@kovidgoyal
> You need to map ctrl+space in zshrc. ctrl+space in the legacy
terminal key encoding is the null byte. So map that to whatever action
you want. Then configure the ssh kitten to copy zshrc to remote hosts
automatically and it will work on your remote host as well.

As I said, I have it mapped in `.zshrc`. Here are all the binds I had to add for zsh to work with all the basic shortcuts:
```bash
# Custom ZSH Binds
bindkey '^ ' autosuggest-accept
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey  "^[[3~"  delete-char
```

The `ctrl+space` works in every single terminal apart from kitty when I exit ssh. I have the same zsh config on the remote server as I access it from machines that do not have kitty installed and I do not have the privileges to install.

**Comment by jiriks74** [comment]
@page-down 
> You need to make sure that any key sequences sent by this alias are recognized on the remote host.
Since you didn't give details of the configuration, I'm guessing that your alias sends another key that is not bound in the remote system's zsh.

If you want to take a look at the complete zsh config I have it's [on my github](https://github.com/jiriks74/zsh). But the relevant section is the one mentioned above:
```zsh
# Custom ZSH Binds
bindkey '^ ' autosuggest-accept
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey  "^[[3~"  delete-char
```
It works in every single terminal but kitty has some problems after disconnecting from ssh. Konsole, terminator, yakuake, etc. do not have such problems. I added the map in my kitty.conf to try to resolve the issue but that didn't work - it's not in there anymore as it didn't help.

**Comment by jiriks74** [comment]
@page-down 
> Try to reset the terminal using the default key ctrl+shift+delete.
This one is able to solve the problem. Though it's quite annoying to loose all my history just to get a shortcut working.

**Comment by kovidgoyal** [comment]
I cannot replicate. With the following steps:

1) Run kitty as kitty --config=NONE
2) Run showkey -a and press ctrl+space See the output of ^@ as expected
3) Run kitty +kitten ssh localhost
4) Repeat step (2)
5) Press ctrl-d to exit the ssh session
6) repeat step (2)

In 6) we same the same output as in (2) showing that kitty is sending
the correct bytes for ctrl+space

**Comment by page-down** [comment]
>> Try to reset the terminal ...
>
> This one is able to solve the problem. ...

Try to start with an empty zshrc at the remote.
Disconnect immediately after connecting, can you still use the shortcut?
If you can, try adding back your original zshrc lines until something goes wrong.

**Comment by mehalter** [comment]
I also have been experiencing this where `'^ '` binding gets unset after i close an ssh session created with `kitten ssh`. I can see that it's still receiving the correct output in `showkey -a` of `^@` but it's no longer executing the original command it was bound to

**Comment by mehalter** [comment]
@jiriks74 this should be fixed in the latest commit on kitty :)

**Comment by mehalter** [comment]
Sorry this is sort of a false alarm @jiriks74 , it still is broken if you terminate an ssh session before a full connection is made. Such as accidentally running `ssh` and then doing `ctrl+c` before it connects.

**Comment by jiriks74** [comment]
Thanks @mehalter. I cannot test it now as I've dropped kitty because of this. I'm using Konsole as of now.

If I could help you I can install kitty again and do some testing for you.

**Comment by mehalter** [comment]
No problem! I also was looking to drop kitty since this issue kept getting reported but closed as not broken.

It seems that it may have been fixed, but I haven't fully tested the new fix out yet. Hopefully it is good by the next release if you want to give using kitty a try again.

**Comment by jiriks74** [comment]
Installed `kitty-git` from the AUR and so far it looks like it's solved

**Comment by mehalter** [comment]
Thanks for testing as well @jiriks74 ! I also can confirm that it seems to be quite stable both in closing successful SSH connections and cutting an ssh connection early before full connection.
