### ISSUE TITLE
Input stream is closed (Diff kitten)

### ISSUE THREAD

**Issue by alok** [kovidgoyal/kitty#605]
fzf,kitty,zsh versions: 0.17.3, 0.10.1, 5.5.1

This snippet uses fzf and zsh to get a git commit id and then pass it to kitty to run a diff against HEAD.

```
_fzf_get_git_commit_hash() {
    # TODO handle multiple parents
    # parent_commits=("${(@f)$(git rev-list --max-parents=0 master)}")
    git log \
        --all \
        --color \
        --format=$'%h %C(red)%D%C(reset) %s %C(cyan)[%cn]%C(reset)' \
        "$(git rev-list --max-parents=0 master)".. |
        # `with-nth=2..` hides the commit hash but doesn't remove it. `cut ..` returns just the hash
        fzf --with-nth=2.. --ansi --no-multi --preview 'git show --color {1}' | cut -d ' ' -f1
}

git-difftool-widget() {
    if _in_git_repo; then
        commit_id="$(_fzf_get_git_commit_hash)"
        if ! git diff --quiet "$commit_id";then
            git difftool --no-symlinks --dir-diff "$commit_id"
        fi
    fi
}

zle -N git-difftool-widget
bindkey '\eg' git-difftool-widget
```

Pressing `alt-g` activates it. But if I do that, I get the following error (for a commit that actually has a diff against HEAD, since the script exits early otherwise):

```
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 76, in <module>
  File "kitty/__main__.py", line 67, in main
  File "kitty/__main__.py", line 43, in namespaced
  File "kitty/__main__.py", line 38, in run_kitten
  File "kitty/runner.py", line 87, in run_kitten
  File "Python/runpy.py", line 208, in run_module
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/main.py", line 416, in <module>
  File "kitty/main.py", line 404, in main
  File "kitty/loop.py", line 410, in loop
  File "kitty/loop.py", line 429, in _report_error_
loop
  File "kitty/loop.py", line 209, in _read_ready
EOFError: The input stream is closed
```

If I run the widget by name (type `git-difftool-widget` on the command line), there's no issue.

I'm not entirely sure if this is a kitty or zsh issue, but maybe someone has some insight.

**Comment by kovidgoyal** [comment]
That error implies that the stdin is closed, presumably because it has been redirected somewhere. The kitten needs stdin as it reads keystrokes from there. Use git difftool -g instead and you should be fine, the downside being that the diff will open in a new window. Or figure out why the stdin is redirected/closed. Or use a wrapper to launch git difftool that redirects /dev/tty to stdin

**Comment by alok** [comment]
Adding the redirection `< "$TTY"` fixes the issue, so thanks for the last sentence. Passing the gui flag gives the following error, which I see constantly when trying to run the gui difftool (configured like in the docs)

```
Traceback (most recent call last):
  File "kitty/loop.py", line 192, in _run_job
  File "kitty/main.py", line 41, in generate_diff
  File "kitty/collect.py", line 144, in data_for_path
  File "kitty/collect.py", line 134, in raw_data_for_path
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/52/pd9v2v217dqdkj574btgbn4h0000gp/T/git-difftool.V0Owgw/left'

Press Enter to quit.^[_Gi=1;EBADF:Failed to open file /var/folders/52/pd9v2v217dqdkj574btgbn4h0000gp/T/kitten-images-_zqnlnhr/tmprsk_ng28 for graphics transmissiongi with error: [2] No such file or directory^[\
```

**Comment by kovidgoyal** [comment]
That error indicates something is deleting the temp files git uses to pass data to the difftool. Which most likely is because the kitty process is backgrounding itself/opening a new window in an existing kitty process. So git sees the difftool process exit/detach and cleans up the temp files. invoking kitty by default will not do that, unless you have set it up that way.

**Comment by alok** [comment]
It was `--single-instance` that was the issue. I was using it since it made starting up the guitool much faster, but like you said, git ended up cleaning out the temp files.

**Comment by kovidgoyal** [comment]
That is easily worked around by using a wrapper script that gets the pid of the process with a cmdline containing the first argument to the script (this will be the diff kitten process). Then wait for that pid to exit, and only then exit the script.

**Comment by kovidgoyal** [comment]
And this makes the diff kitten work even with re-directed stdin/stdout https://github.com/kovidgoyal/kitty/commit/8a1a45b0671e475a503e9935348317aa5b9eda09

**Comment by alok** [comment]
Thanks for https://github.com/kovidgoyal/kitty/commit/8a1a45b0671e475a503e9935348317aa5b9eda09
