### ISSUE TITLE
Build: tools/cmd outside main module or its selected dependencies

### ISSUE THREAD

**Issue by glensc** [kovidgoyal/kitty#6051]
Build error on PLD Linux with golang 1.18.7:

```
...
/usr/libexec/ccache/x86_64-pld-linux-gcc build/kitty-launcher-main.o -lcrypt -ldl -lm -lm -L/usr/lib64 -l
python3.10 -Xlinker -export-dynamic -o /home/users/glen/tmp/kitty-0.27.1-x86_64-root-glen/usr/bin/kitty 

Updating Go generated files...         
directory ../../../BUILD/x86_64-linux/kitty-0.27.1/tools/cmd outside main module or its selected dependen
cies
/usr/bin/go build -v -ldflags '-X '"'"'kitty.VCSRevision='"'"'' -o /home/users/glen/tmp/kitty-0.27.1-x86_64-root-glen/usr/bin/kitten /home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/tools/cmd
error: Bad exit status from /home/users/glen/tmp/rpm-tmp.nsBMsj (%install)
```

**Comment by kovidgoyal** [comment]
kitty requires golang 1.20

**Comment by glensc** [comment]
Same message with go 1.20

```
➔ go version
go version go1.20.1 linux/amd64
```

**Comment by kovidgoyal** [comment]
What build command did you use?

**Comment by kovidgoyal** [comment]
Does not repro for me in master doing:

make clean
make linux-package

I am not familiar enough with the Go build tool to be able to guess what its
complaining about, looks like something with paths.

**Comment by glensc** [comment]
the on one system fthis fails (vserver guest):

```
/usr/bin/go build -v -mod=vendor -ldflags '-X '"'"'kitty.VCSRevision='"'"'' -o /home/users/glen/tmp/kitty-0.27.1-x86_64-root-glen/usr/bin/kitten /home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/tools/cmd
```

but on another system (docker guest) this succeeds:
```
/usr/bin/go build -v -mod=vendor -ldflags '-X '"'"'kitty.VCSRevision='"'"'' -o /var/tmp/kitty-0.27.1-x86_
64-root-builder/usr/bin/kitten /home/builder/rpm/BUILD/kitty-0.27.1/tools/cmd
```

i think the `--prefix` has something to do with the problem  but i can't really reproduce. i.e what's the difference of two different environments

**Comment by kovidgoyal** [comment]
Definitely looks path related

**Comment by glensc** [comment]
here's log of non-failing build:
- https://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=1&name=kitty&id=e40261ec-9569-4c73-8daf-257e0f32cbe9&action=tail

I'm guessing go has something extra allowed in /tmp or /var/tmp, considers it as allowed path, as the succeeding builds had prefix set to /tmp or /var/tmp, but /home was failure.

i tried resetting $HOME to common paths. no avail

**Comment by glensc** [comment]
finally made it build but resetting all env, but it needed HOME, so I set GOCACHE instead:

```
➔ env -i GOCACHE=/home/users/glen/rpm/BUILD/x86_64-linux
/kitty-0.27.1/.gocache PATH=$PATH /usr/bin/go build -v -ldflags '-X '"'"'kitty.VCSRevision='"'"'' -o /hom
e/users/glen/tmp/kitty-0.27.1-x86_64-root-glen/usr/bin/kitten /home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/tools/cmd
...
kitty/tools/wcswidth
```

**Comment by kovidgoyal** [comment]
So which env var was causing the issue?

**Comment by glensc** [comment]
bisected... `env -u PWD`. wtf go?!

- https://github.com/pld-linux/kitty/commit/2bda90d8d86f44cf4de9d08ea4e3b4901a0cb8b1

**Comment by kovidgoyal** [comment]
That will be because of https://github.com/golang/go/blob/master/src/os/getwd.go#L27

I am guessing there are symlinks involved and go build does not resolve
symlinks when comparing paths.

**Comment by glensc** [comment]
ah yes. `$PWD` and `$(pwd)` don't match, as the build dir is a symlink:

```
➔ ls -l /home/users/glen/rpm/packages/BUILD.x86_64-linux           
lrwxrwxrwx 1 glen users 21 Jan 26  2014 /home/users/glen/rpm/packages/BUILD.x86_64-linux -> ../BUILD/x86_64-linux/
```

**Comment by kovidgoyal** [comment]
Should be fixed by https://github.com/kovidgoyal/kitty/commit/79e99f7e3ac8561648b117fbaae7f246ddad4605
