### ISSUE TITLE
diff: ValueError: Left side line mismatch

### ISSUE THREAD

**Issue by glensc** [kovidgoyal/kitty#6052]
**Describe the bug**

Ran a diff or two composer vendor dirs.

```
~/Downloads/s ✖ alias dif='kitty +kitten diff'
~/Downloads/s ✖ dif /tmp/vendor vendor 
Traceback (most recent call last):
  File "lib/python3.9/kittens/diff/patch.py", line 251, in __call__
  File "lib/python3.9/kittens/diff/patch.py", line 213, in parse_patch
  File "lib/python3.9/kittens/diff/patch.py", line 154, in finalize
ValueError: Left side line mismatch 9 != 3

Parsing diff for /tmp/vendor/swagger-api/swagger-ui/dist/swagger-ui-standalone-preset.js vs. /Users/glen/Downloads/s/vendor/swagger-api/swagger-ui/dist/swagger-ui-standalone-preset.js failed
Press Enter to quit.
```

**To Reproduce**
1. download [file1.js.txt](https://github.com/kovidgoyal/kitty/files/10812016/file1.js.txt)
2. download [file2.js.txt](https://github.com/kovidgoyal/kitty/files/10812017/file2.js.txt)
3. `kitty +kitten diff file1.js.txt file2.js.txt`

**Environment details**

- Kitty 0.27.1 on macOS
- Reproduced with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
The diff kitten is not designed for giant lines. It's a line oriented
diff so diffing files that contain just a single giant line is pretty
pointless. As such I am afraid I dont have the time/interest to debug
this.

**Comment by glensc** [comment]
At least it should put `[Not rendered]` there and render what it knows, not crash the whole diffing.

**Comment by kovidgoyal** [comment]
You are most welcome to submit a PR to make it do that.
