### ISSUE TITLE
Independent size of fonts in single instance

### ISSUE THREAD

**Issue by piotr-sikora-v** [kovidgoyal/kitty#6058]
It will be nice to have independent resizing font (cmd +/-) in terminal
Now when I resize one window it also resize in other windows.

**Comment by kovidgoyal** [comment]
Every OS windows can have its own font size. individual tabs and kitty
windows inside an OS window all have the same font size.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#font-sizes
