### ISSUE TITLE
how i can open a new tab or windows with current path with sudo su

### ISSUE THREAD

**Issue by jopcode** [kovidgoyal/kitty#6059]
Hello, i dont find how i can open a new windows or tab with current path using sudo (like root).
for example iam in /home/user/desktop/someonefolder/ (like root) and when i open a new tab or windows these open in home folder without sudo (root), have anyway to make it possible ?

**Comment by kovidgoyal** [comment]
Use the launch command to launch whatever program you like.
https://sw.kovidgoyal.net/kitty/launch/ 

If you mean you want kitty to automatically run sudo/su for you, then no
that's not possible.
