### ISSUE TITLE
Support GPUs without OpenGL 3.3+ drivers

### ISSUE THREAD

**Issue by D3vil0p3r** [kovidgoyal/kitty#6064]
It is long time I used Kitty as main terminal emulator because it has all a user needs imho and I would like to not move to other terminals because they have several non-functional drawbacks that kitty does not have (i.e., I appreciate the performance of Kitty than other term emulators).

I would like to know if there is some plan for older hardware. I work on other older laptops where kitty cannot run due to older GPUs.

I think it could be a good approach to support also older hardware if possible. If it cannot be implemented, I can understand.

I read that Alacritty some years ago started to support older GPUs even though I prefer Kitty. I report some useful links about this issue faced on Alacritty if it can be helpful:

https://github.com/alacritty/alacritty/issues/128
https://github.com/kchibisov/alacritty/commit/4a6a0d622f7be0980fde2a8e10dbe29e01ce590d

**Comment by kovidgoyal** [comment]
dup of #2790

**Comment by palontologist** [comment]
I cannot use Kitty to since I am on old hardware
