### ISSUE TITLE
Prompt at the top, content scrolls down 

### ISSUE THREAD

**Issue by Henry78** [kovidgoyal/kitty#6066]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd love to see a feature, that inverts the usual operation of shells:

> It always shows the command prompt at the top of the screen and pushes command output down instead of letting it scroll up.

Cited from [demoshell README](https://github.com/dhellmann/demoshell).

**Describe alternatives you've considered**
None

**Additional context**
Yeah, demoshell again, but the GIF they created very clearly shows what I'd like to see: https://github.com/dhellmann/demoshell/blob/master/demo.gif

**Comment by page-down** [comment]
In my opinion, based on how terminal / CLI programs currently work,
it is impossible to robustly achieve this in terminal to allow **ANY** shells to do this when running **ANY** program.

So I don't see this feature (with glitches) being implemented in kitty in the foreseeable future.

Your best bet is to ask in:
https://github.com/warpdotdev/Warp

This fancy feature is perhaps more to the taste of that project.

**Comment by kovidgoyal** [comment]
Shells are free to implement any kind of interaction they want. If some
shell wants to implement this kind of thing and they need some feature
from the terminal interpreter that doesnt yet exist, they are welcome to
contact me and we can discuss it. But this kind of thing cant be
implemented by the terminal emulator alone.

**Comment by wyuenho** [comment]
It appears that Warp uses a combination precmd/preexec hooks in various different shells (injecting iterm2's shell integrations for bash),  giving each command it's own separate grid for each command using Alacritty's grid model, and custom DCS codes with embedded JSON to achieve blocks and pinning the prompt at the bottom. This doesn't seem to require cooperation from shell authors. Perhaps @kovidgoyal you can revisit this?

https://www.warp.dev/blog/how-warp-works

**Comment by wyuenho** [comment]
With 2.1k issues it's very difficult for me to discern which is a problem with user config and which is an actual Warp bug. I randomly picked a few of them and I could reproduce them. Anyway, I do appreciate kitty's 2 digit issue count tho :)
