### ISSUE TITLE
Hide titlebar on X/Wayland?

### ISSUE THREAD

**Issue by lxcode** [kovidgoyal/kitty#607]
Similar to on MacOS, the titlebar on GNOME (and presumably other environments) just takes up space when you're operating maximized. I'd rather not use fullscreen, as that hides the top bar with the clock and all. Right now I'm using the xprop hack to hide the titlebar (https://gist.github.com/zenozeng/8897839), but could there be a more general option to hide titlebar regardless of platform?

**Comment by kovidgoyal** [comment]
The titlebar is not drawn by applications in linux, but by window managers. So the correct place to configure an application to not have titlebars is in your window manager's configuration. Most window managers have some way of defining rules for this based on a  windows class/role, which you can control in kitty via command line applications. 

And note that according to the standards, MOTIF_WM_HINTS is not supported and may or may not work depending on window manager.. In X what you have is _NET_WM_WINDOW_TYPE there is no direct way to control titlebar presence/absence that is blessed by the specs.

https://standards.freedesktop.org/wm-spec/wm-spec-latest.html

As for Wayland, I haven;t the faintest clue.

**Comment by kovidgoyal** [comment]
On second thoughts, I think I should implement an option to hide window decorations, since glfw has an API for it. Whether ti works or not will depend on iwndow manager/compositor, but that is pretty much the case for everything on X11.

**Comment by smesko85** [comment]
@kovidgoyal It looks like it doesn't have any effect on the Gnome 3 with Xorg

**Comment by kovidgoyal** [comment]
Not much I can do about that. As I said, whether it works or not is highly window manager dependent. The correct way to do this is by creating rules in the window manager to not show window decorations for specific windows.

**Comment by smesko85** [comment]
@kovidgoyal The real issue I have is that on multi monitor setup I can't use kitty fullscreen. Usually I have a terminal running in one monitor, and the web browser in another one. If the kitty is fullscreen, as soon as I click in the browser, the kitty hides itself. I thought this flag could address that. 

Do you have any idea how to solve this?

**Comment by kovidgoyal** [comment]
That's because fullscreen in kitty uses a "real" fullscreen, that is it takes over the GPU bypassing the window manager. If you want a normal fullscreen, then that has to be done by the window manager. I'm not a gnome user so I cant help with that, sorry.

**Comment by unkwn1-repo** [comment]
Sorry for reviving this, but I've had that ugly gnome title bar I wanted to ditch. For anyone else on gnome who wants to ditch the window title bar `hide_window_decorations yes` worked for me :)

Thanks for all your hard work @kovidgoyal I absolutely love Kitty.

**Comment by khoulyy** [comment]
> Sorry for reviving this, but I've had that ugly gnome title bar I wanted to ditch. For anyone else on gnome who wants to ditch the window title bar `hide_window_decorations yes` worked for me :)
> 
> Thanks for all your hard work @kovidgoyal I absolutely love Kitty.

where do i add the `hide_window_decoration yes` ?
