### ISSUE TITLE
black font (with color background) are more thin than white or color font

### ISSUE THREAD

**Issue by zhengkai** [kovidgoyal/kitty#6072]
**Describe the bug**
black font (with color background) are more thin than white or color font

**To Reproduce**
always

**Screenshots**
font color 0  
![Screenshot from 2023-02-28 10-51-57](https://user-images.githubusercontent.com/247015/221741198-8bda451f-ee85-41e7-92ae-5e37221fef85.png)  
font color 8  
![Screenshot from 2023-02-28 10-54-55](https://user-images.githubusercontent.com/247015/221741748-09d67adc-7dca-4ebb-9e85-f1b847c981ac.png)  
font color 15  
![Screenshot from 2023-02-28 10-51-50](https://user-images.githubusercontent.com/247015/221741192-c8e097af-0241-4cf6-8460-8952734b4709.png)

**Environment details**
I forgot which version before, when I updated to 0.27.1 yesterday, I found black font is changed. Is there new config about this ?

**Additional context**
I use linux, Ubuntu 22.04

**Comment by kovidgoyal** [comment]
There are no changes to font rendering in 0.27.x

And anti-aliasing means fonts will look different on different
background colors. That has always been the case. If you run kitty from
master/antialiasing however, font rendering has indeed been changed and
you can control thickness, see the relevant PR.

**Comment by zhengkai** [comment]
@kovidgoyal Sorry, how to set font weight by color? I think the current rendering of the black text is not right

**Comment by kovidgoyal** [comment]
You dont set font weight by color, you choose what curve you want gamma
correction to use, see the associated PR. And if you want the previous
behavior, use the legacy option.

**Comment by kovidgoyal** [comment]
See #5969

**Comment by zhengkai** [comment]
@kovidgoyal Maybe no effect in linux, that's why it looks ugly in Linux / no retina monitor

**Comment by page-down** [comment]
@zhengkai
If you are using the nightly release or compiled from master, you should configure the option `text_composition_strategy`.
Running `kitty` in the shell will show you the error message `Ignoring unknown config key: ...` from stderr.

See the description of this option in `kitty/options/definition.py` and PR 5969 to learn how to tweak it.

> Maybe no effect in linux, ...

No, it works under Linux when you have configured the correct option.

**Comment by zhengkai** [comment]
@page-down Solved, thanks

This option cannot take effect through reload_config. After restarting a few times, I found a comfortable value.

![Screenshot from 2023-03-01 11-00-23](https://user-images.githubusercontent.com/247015/222034107-8c35c8e0-7fb7-4bd9-9dc9-0a7ed60e9788.png)
