### ISSUE TITLE
Add option to toogle timestamps for terminal output lines

### ISSUE THREAD

**Issue by benner** [kovidgoyal/kitty#6074]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add ability to track and then toggle timestamps of each new terminal line. Similar functionality is implemented in `tio` serial terminal and OS X terminal program iTerm2.

**Describe alternatives you've considered**
Maybe this can be kitten extension?

**Additional context**
---

**Comment by kovidgoyal** [comment]
Not something I am interested in implementing, sorry.
