### ISSUE TITLE
Placement strategy bottom-center

### ISSUE THREAD

**Issue by zoriya** [kovidgoyal/kitty#6075]
**Is your feature request related to a problem? Please describe.**
In vim, there is a bar at the bottom. Since kitty has gaps when the window's size is not divisible by the cell's size, the bar seams to float. I would like the bar to be anchored at the bottom of the window and display the padding at the top of the window instead.

**Describe the solution you'd like**
Add the setting option  `placement_strategy bottom-left`

**Describe alternatives you've considered**
Keeping the gap.

**Comment by kovidgoyal** [comment]
Not something I care about, patches are welcome.
