### ISSUE TITLE
Multiple Terminals Cause 100% CPU

### ISSUE THREAD

**Issue by shoober420** [kovidgoyal/kitty#608]
I have this same issue with the alacritty terminal, which also uses the GPU for rendering. Since kitty supports tabs without the need of tmux, there is really no reason to have more then one kitty terminal open to being with.

So with this realization, this isn't a serious issue if you use the terminal how its supposed to be used (single terminal, multiple tabs). I used to use st terminal, and spawn a new terminal for each process. In practice, this isn't very logical, as it has multiple processes running for each terminal emulator spawned, which is kind of dumb.

I then went with alacritty and tmux, but ran into problems with tmux. So now, here I am using kitty, and its such a great terminal emulator. I just thought I would bring this to your attention, but at the same time, it should be discouraged to use a terminal emulator in the way of creating a new terminal process for each desired program. Tabs or tmux should be used instead.

**Comment by kovidgoyal** [comment]
You presumably dont have hardware rendering enabled on your system. With properly functioning GPU drivers, on a four year old laptop, opening 20 kitty windows used under 2% of CPU.

**Comment by shoober420** [comment]
You're right, there is something else going on here.
