### ISSUE TITLE
Some emoji characters get displayed double width in PragmataPro font

### ISSUE THREAD

**Issue by VitGottwald** [kovidgoyal/kitty#6085]
**Describe the bug**
When using _PragmataPro_ and specifying `symbol_map` to use PragmataPro font for various emoji characters (to avoid [falling back](https://github.com/kovidgoyal/kitty/issues/6084) to _Apple Color Emoji_) the characters get printed double width and bold.

**To Reproduce**
1. Install [PragmataPro](https://github.com/fabrizioschiavi/pragmatapro/blob/master/useful_files/All_chars.png) font
2. Create a kitty config `/tmp/kitty.conf` with the following two lines
```
font_family PragmataPro Mono Liga
symbol_map U+231a,U+231b PragmataPro Mono Liga
```
3. start kitty by running `kitty --config /tmp/kitty.conf`
4. inside kitty run `curl https://raw.githubusercontent.com/fabrizioschiavi/pragmatapro-semiotics/main/Symbols.csv 2>/dev/null | head -n 34 | tail -n 4`
5. See that _watch_ and _hourglass_ symbols get printed double width and bold

**Screenshots**
![image](https://user-images.githubusercontent.com/19686979/222745848-0aceca59-1f2f-483f-ae30-e43eff3e92f2.png)

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Darwin PP69WP66CY 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.2.1 BuildVersion:		22D68
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /tmp/kitty.conf

Config options different from defaults:
font_family PragmataPro Mono Liga
symbol_map:
	U+231a - U+231a → PragmataPro Mono Liga
	U+231b - U+231b → PragmataPro Mono Liga

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /bin/zsh
	USER                                vit
	LC_CTYPE                            UTF-8
```

**Additional context**
Reproduced with minimal `/tmp/kitty.conf` containing only two lines 
```
font_family PragmataPro Mono Liga
symbol_map U+231a,U+231b PragmataPro Mono Liga
```

**Comment by VitGottwald** [comment]
Similar issue happens when using [Iosevka Term](https://github.com/be5invis/Iosevka) font (however, it looks like Iosevka does not implement these chars).

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/19686979/222754160-4d56d795-90c3-4ce8-b38b-f0953a161325.png">

**Comment by kovidgoyal** [comment]
The width of characters is fixed by the unicode standard. You cannot control it. If users could change the width of characters then it would be impossible for terminal programs to draw any text with any fidelity.

**Comment by VitGottwald** [comment]
I did not know that. But when I open text with these charactes in TextEdit and use the font it does not look any wider than other characters 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/19686979/222773312-a41eb5e3-ce40-4235-a561-93076ea4fbe6.png">
