### ISSUE TITLE
Smart Select

### ISSUE THREAD

**Issue by VitGottwald** [kovidgoyal/kitty#6086]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to do a block select. I click, start dragging and then realise that I get line select. I kill the selection and try to remember what key modifier I need to press to go into _block select mode_. I try a few of them and eventually I get it right. But it takes focus from what I am doing.

**Describe the solution you'd like**
After _mouse down_ if I start moving the cursor to _left_ or _right_ I will get line selection. If I start moving the cursor _up_ or _down_ I will get block select. 

**Describe alternatives you've considered**
I can use the key modifier for block select today, but for some reason I always forget it.

**Additional context**
I used an emulator a while back whose name I no longer remember and it had this feature. It was very natural to use it and worked great for me.

**Comment by kovidgoyal** [comment]
Not a fan of this concept, sorry. It's too magical and can lead to lot
of confusion. You will get used to the block select modifiers with a few
days of usage or a concerted effort to memorise them.

**Comment by VitGottwald** [comment]
Is it then possible to have block select as a _default_ and switch to line select with a modifier? I rarely want to select whole lines.

**Comment by kovidgoyal** [comment]
You can map mouse actions to whatever you like. https://sw.kovidgoyal.net/kitty/conf/#mouse-actions
