### ISSUE TITLE
Srolling (ctrl-h) on a buffer using graphic protocol (e.g using viu or tpix) doesn’t show them

### ISSUE THREAD

**Issue by tshirtman** [kovidgoyal/kitty#6094]
**Describe the bug**

**To Reproduce**
1. install viu (https://github.com/atanunq/viu) or tpix (https://github.com/jesvedberg/tpix/) as explained in the documentation (https://sw.kovidgoyal.net/kitty/graphics-protocol/)
2. be amazed
3. wonder if scrollback will work, press ctrl-shift-h
4. images using the graphic protocol become invisible while scrolling.

**Screenshots**
before scrolling 
![afbeelding](https://user-images.githubusercontent.com/22759/223156387-def7c199-df77-4555-b855-ff282dcb8ecd.png)
after pressing ctrl-shift-h
![afbeelding](https://user-images.githubusercontent.com/22759/223156530-8210b325-0bcf-4035-b15b-9a3903742b9b.png)

**Environment details**
```
itty 0.27.1 () created by Kovid Goyal
Linux Laptop390 4.4.0-17763-Microsoft #2268-Microsoft Thu Oct 07 16:36:00 PST 2021 x86_64
Ubuntu 18.04.6 LTS Laptop390 /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/gabriel/.local/kitty.app/bin/kitty
  base dir: /home/gabriel/.local/kitty.app/lib/kitty
  extensions dir: /home/gabriel/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /home/gabriel/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell    False
font_family          Input Mono Compressed
visual_bell_duration 0.05

Important environment variables seen by the kitty process:
        PATH                                /home/gabriel/.volta/bin:/home/gabriel/.local/bin/:/home/gabriel/.local/bin/:/home/gabriel/.pyenv/shims:/home/gabriel/.pyenv/shims:/home/gabriel/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local
        LANG                                C.UTF-8
        EDITOR                              vim
        SHELL                               /usr/bin/fish
        DISPLAY                             :0
        USER                                gabriel
        XDG_CURRENT_DESKTOP                 Unity
        XDG_DATA_DIRS                       /usr/local/share:/usr/share:/var/lib/snapd/desktop
```
In case it turns out to be important, note that i’m using kitty in WSL1.0 (ubuntu) with an X11 window (mobaXterm), connecting to a remote machine using ssh, and running tpix/viu in there, i can try reproducing in a more conventiennal setup later if needed.

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

The issue can be reproduced with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
Yeah there is currently no support for images in the scrollback, adding
such support first depends on writing a pager that can display images.

**Comment by tshirtman** [comment]
Ok, is it a realistic feature request? It’s fine if not, but it would be nice to have :).

**Comment by kovidgoyal** [comment]
As I said, someday when I get around to writing a pager to replace less,
assuming I add support for images to that pager, then yes this will be a
fairly easy feature to implement. But until that time, it's a wontfix
