### ISSUE TITLE
copy_on_select doesn't work without first focusing Kitty

### ISSUE THREAD

**Issue by mburz** [kovidgoyal/kitty#6095]
Given the following configuration in Kitty:

```
copy_on_select clipboard
mouse_map left click ungrabbed no-op
mouse_map left press ungrabbed mouse_selection normal
```

copy_on_select works as expected, when Kitty is focused.
When the focus resides on a different application, selecting text with the mouse inside of Kitty will also focus Kitty, and the text selection works as expected, but the selected text is not copied to the clipboard or primary selection. Same feature works as expected using other terminals. First clicking on Kitty then selecting the text also works as expected.

The issue is reproducible using `kitty 0.21.2` bundled with Ubuntu and `kitty 0.27.1` released on GitHub.
The issue is also reproducible using `kitty --config NONE` with both of these versions.
Tried on Ubuntu 22.04 and 22.10.

**Comment by page-down** [comment]
I can reproduce this under Wayland and it works fine under x11.

After selecting the text and releasing the mouse button, I see:
```log
Release mouse_button: 0 mods: none grabbed: 0
on_mouse_input: release button: left mods: none grabbed: 0 handled_in_kitty: 0
```

However it should be:
```log
Release mouse_button: 0 mods: none handled as drag end
```

So `mouse.c`->`end_drag()` is not called, `screen.c`->`self->selections.in_progress` will always be true, and `call_boss(set_primary_selection, NULL)` will not be executed.
After the mouse button is released, `screen_update_selection()` is run over and over again.

**Comment by kovidgoyal** [comment]
Works for me in GNOME wayland (mutter 43.3) . Steps I tried:

1) kitty -o 'copy_on_select clipboard'
2) focus another window
3) drag some text in the kitty window from step 1
4) paste from clipboard in another application. works as expected.

Which compositor and version are we talking of? Given wayland's brain dead design saying "Wayland" is pretty useless.

**Comment by page-down** [comment]
> Which compositor and version are we talking of? ...

KDE kwin 5.27.2
