### ISSUE TITLE
OSC52 stops working after certain strings

### ISSUE THREAD

**Issue by cfal** [kovidgoyal/kitty#6099]
I'm on MacOS Ventura 13.2.1 running Kitty 0.27.1, tested using zsh/bash.

```
$ printf "\033]52;c;$(echo "01234567890123456789012345678901234567890123456789012345" | base64)\a"
(copies string to clipboard)
$ printf "\033]52;c;$(echo "012345678901234567890123456789012345678901234567890123456" | base64)\a"
(string is not copied to clipboard, osc52 sequences stop working)
```

it seems like after 56 characters, things break.

another interesting bug is that URLs that were put on the clipboard using OSC52 don't seem to paste correctly in kitty, although they are fine in other apps.

```
$ printf "\033]52;c;$(echo "http://abc.com/def/ghi/jklmn" | base64)\a"
```

if you paste this string immediately in kitty, you get:
```
'http://abc.com/def/ghi/jklmn
'
```

while it would show up as a single-line URL without quotes if pasted in another app.
when URLs are copied onto the clipboard via other apps, they paste correctly in kitty.

i could be wrong, but i believe this is a regression - as i frequently used OSC52 for long URLs previously.

**Comment by kovidgoyal** [comment]
There are various bugs in how you are using OSC 52. I suggest you use
the clipboard kitten, it will do the heavy lifting for you.
https://sw.kovidgoyal.net/kitty/kittens/clipboard/

**Comment by kovidgoyal** [comment]
the kitten works with any terminal emulator that supports OSC 52 in
filter mode. Only kitty supports copying of non textual data to the
clipboard.

And just off the top of my head, you aren't outputting the correct
padding for base64. And you are missing -n on your echo invocations.

**Comment by kovidgoyal** [comment]
Forget the padding, base64 outputs newline separated base64 data. You cannot
use its output directly. I really hope those snippets are not indicative
of the general code quality in Chromium.
