### ISSUE TITLE
command is sometimes echoed on first line of stdout

### ISSUE THREAD

**Issue by mmlb** [kovidgoyal/kitty#61]
```
# ok
~
❯ printf "$IFS" | hexdump -C
00000000  20 09 0a 00                                       | ...|
00000004

# bad
~
❯ printf "$IFS\r" | hexdump -C
r" | hexdump -C00000000  20 09 0a 00 0d                                    | ....|
00000005
```

**Comment by kovidgoyal** [comment]
I cannot replicate that. I tried the above command 20 times at different font and windows sizes.

**Comment by mmlb** [comment]
hmm, with zsh?

**Comment by mmlb** [comment]
I did compare this with alacritty and pangoterm, both were fine. It does look like something to do with zsh though since I can't reproduce with bash on kitty.

**Comment by mmlb** [comment]
Yup it does seem to be something with zsh, let me try to whittle it down.

**Comment by kovidgoyal** [comment]
Yes, with zsh -- zsh is my primary shell.

**Comment by mmlb** [comment]
ok looks to be something to do with my prompt: https://github.com/molovo/filthy

**Comment by kovidgoyal** [comment]
You should be ablet ocreate a dump of commands kitty sees using --dump-commands

Then replay it with 

--replay-commands

and if that reproduces it, attach the dump here.

Note that the dump/replay functionality is not fully implemented, so it may not work.

**Comment by mmlb** [comment]
hmm kitty is throwing an exception while trying to rplay the commands, I ran it like `kitty --replay-commands kitty-commands`. I'm attaching the dumped commands

[kitty-commands.zip](https://github.com/kovidgoyal/kitty/files/894050/kitty-commands.zip)

**Comment by mmlb** [comment]
also, here's the stacktrace for the exception:
```
kitty --replay-commands kitty-commands                                                                                                                                                                                                             
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 7, in <module>
    main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 230, in main
    main(args.replay_commands)
  File "/usr/bin/../lib/kitty/kitty/client.py", line 89, in main
    replay(raw)
  File "/usr/bin/../lib/kitty/kitty/client.py", line 84, in replay
    globals()[cmd](*rest)
KeyError: 'screen_linefeed' 
```

**Comment by kovidgoyal** [comment]
I have committed the missing functionality to replay, please regenerate the dump (and do it by redirecting the output to a file as if you copy/paste from the terminal trailing spaces will be removed, which are needed). Also try to do only the minimal amount of typing to generate the problem when creating the dump.

**Comment by kovidgoyal** [comment]
Actually, I just added --dump-bytes which will dump the actual raw bytes received from the child process. Use that instead of --dump-commands. (You will have to recompile kitty for it to work).

**Comment by mmlb** [comment]
Here is the `--dump-bytes` file, all I did was paste the `printf` command and type exit.
[kitty-dump.zip](https://github.com/kovidgoyal/kitty/files/894164/kitty-dump.zip)

**Comment by kovidgoyal** [comment]
If I cat the attached file, I see no problems in either kitty or any other terminal. Opening the dump file in a hex editor shows it is missing the \r character from your initial post

**Comment by mmlb** [comment]
:tada: thanks @kovidgoyal

**Comment by kovidgoyal** [comment]
you're welcome :)
