### ISSUE TITLE
Kitty uses a full CPU core all the time

### ISSUE THREAD

**Issue by ronjouch** [kovidgoyal/kitty#6105]
**Describe the bug**
Something in db972f344 ... 7acc6bdeb causes Kitty to use a full CPU core all the time.

**To Reproduce**
1. `kitty --config NONE`
2. `htop`

- Expected: kitty mostly idle
- Actual: 100% CPU usage (one full core)

**Screenshots**

![screenshot_kitty-fullcpu_2023-03-10-12:38:14](https://user-images.githubusercontent.com/522085/224385219-3737537c-180f-41e1-baf6-76990105a2bc.png)

**Environment details**

```
kitty 0.27.1 (7acc6bdeb8) created by Kovid Goyal
Linux t 6.2.2-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 08 Mar 2023 04:07:25 +0000 x86_64
Arch Linux 6.2.2-zen2-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :1
	USER                                ronj
	LC_MEASUREMENT                      en_DK.UTF-8
	LC_MONETARY                         en_DK.UTF-8
	LC_NUMERIC                          en_DK.UTF-8
	LC_PAPER                            en_DK.UTF-8
	LC_TIME                             en_DK.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome-xorg
	XDG_SESSION_TYPE                    x11
```

**Additional context**

- Problem 100% reproducible with `kitty --config NONE`
- Is a regression somewhere this week, in db972f344 ... 7acc6bdeb (I had no problem with db972f344). I can bisect to a precise commit if that's useful.
- Built via [AUR / `kitty-git`](https://aur.archlinux.org/packages/kitty-git). See [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kitty-git).

**Comment by amanjitsk** [comment]
Can confirm same issue here on master!
