### ISSUE TITLE
Powerline10k Shading doesn't render nicely (Unicode block elements e.g U+2591)

### ISSUE THREAD

**Issue by Dadams2** [kovidgoyal/kitty#6108]
**Describe the bug**
I just did my powerline10k config for Zsh and noticed kitty was not rendering the shading characters nicely like it does for block characters.

I have a strong suspicion this might be a known issue/decision something along the lines of "This is how Unicode presents the character so we are going to display it as such" but I was unable to find a similar issue that had already been marked as a duplicate. At the very least I will be happy if this is marked as dup as it may help others answer this question. 

Specifically the characters: 
U+2591 | ░ | Light shade
U+2592 | ▒ | Medium shade
U+2593 | ▓ | Dark shade

Are not smooth. 

I also apologies if this is something to do with sub-pixel rendering which I know is an issue of contention and in the works.

However if there is a nice workaround with `symbol_map` or something I would be very happy to hear it 

**To Reproduce**
1. `p10k configure` 
2. choose unicode prompt
3. select blurred prompt heads/tails

**Screenshots**
Example in regular kitty (without tmux) 
![image](https://user-images.githubusercontent.com/37862994/224483210-0fc09e4e-04f5-4755-bca4-44dca4deaead.png)

Example in default alacritty:
![image](https://user-images.githubusercontent.com/37862994/224483229-b2747898-c8ac-4ddb-8fa7-1eb63b483329.png)

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Linux effervescence 6.2.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 03 Mar 2023 15:58:31 +0000 x86_64
Arch Linux 6.2.2-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/dadams/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.9
clipboard_control       ('write-clipboard', 'write-primary', 'no-append')
font_family             Fira Code
hide_window_decorations 1
shell                   /bin/zsh -l -c "tmux attach || tmux"
Colors:
	background              #2e3440   
	color0                  #3b4252   
	color1                  #bf616a   
	color10                 #a3be8c   
	color11                 #ebcb8b   
	color12                 #81a1c1   
	color13                 #b48ead   
	color14                 #8fbcbb   
	color15                 #eceff4   
	color2                  #a3be8c   
	color3                  #ebcb8b   
	color4                  #81a1c1   
	color5                  #b48ead   
	color6                  #88c0d0   
	color7                  #e5e9f0   
	color8                  #4c566a   
	color9                  #bf616a   
	cursor                  #81a1c1   
	foreground              #d8dee9   

Important environment variables seen by the kitty process:
	PATH                                /home/dadams/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                dadams
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 herbstluftwm
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/dadams
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000

```

** Additional 
I do have a suspicion this might be a symbol_map issue or a unicode issue as the kitty tabs make use of these characters...

![image](https://user-images.githubusercontent.com/37862994/224483616-42e6bd1a-f603-4956-ab00-5e1e0835d08a.png)

The workaround I am following for the moment is https://github.com/romkatv/powerlevel10k/issues/537#issuecomment-592960982

**Comment by page-down** [comment]
> I have a strong suspicion ... "This is how Unicode presents the character so we are going to display it as such" ...

I don't know if there are other uses for these characters, but for scenes where the foreground and background colors are mixed for gradients, it seems that they can be drawn with the alpha blended directly.
It is no longer necessary to blend by changing the size of the character area as it was done in the ancient terminals.

Since kitty has done optimization for many other characters, this seems reasonable.

> ... this might be a symbol_map issue ...

No, this is drawn by code, no font is used.

**Comment by kovidgoyal** [comment]
Yes this is by design. They have a fixed appearance defined in the
standard.
