### ISSUE TITLE
Use environment variables in tab names

### ISSUE THREAD

**Issue by dyj216** [kovidgoyal/kitty#611]
Maybe this is already available, and I just can't figure out how to do it. 

I want to set the title of my tabs, but also want to show the current working directory in them. Currently, when I open a new tab, it shows the username@domainname and the working directory. I want to keep that and add a string before it. Can I do that? If so, how?

Thanks for your help!

**Comment by kovidgoyal** [comment]
The tab shows whatever window title the program running in the currently active window in the tab sets. Presumably your shell is setting username@domainname and the working directory. You just need to configure the shell to set whatever window title you want.

**Comment by kovidgoyal** [comment]
And see #610
