### ISSUE TITLE
(Feature Request) SDL2 support.

### ISSUE THREAD

**Issue by hardBSDk** [kovidgoyal/kitty#6112]
There are systems that don't support X11/Wayland, a SDL2 support for windowing dependency would be nice as SDL2 has a lot of backends and it's more simple to port/implement.

I want to make Kitty run in [Redox OS](https://www.redox-os.org/) (which support SDL2/orbclient as windowing systems.

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in implementing support for SDL2, sorry.
