### ISSUE TITLE
File completion doesn't work after +kitten

### ISSUE THREAD

**Issue by bitwombat** [kovidgoyal/kitty#6117]
**Describe the bug**
Hitting tab to auto-complete after `+kitten` in bash doesn't work:

```
$ kitty +kitten icat [tab]
Command 'kitten' not found, did you mean:

  command 'kiten' from deb kiten (4:19.12.3-0ubuntu1)

Try: sudo apt install <deb name>
```

**To Reproduce**
1. Start a bash shell
2. Type `kitty +kitten icat`
3. Hit the tab key
4. See OS misinterpret the action and offer to install a package

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Linux server 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64
Ubuntu 20.04.5 LTS server /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/me/.local/kitty.app/bin/kitty
  base dir: /home/me/.local/kitty.app/lib/kitty
  extensions dir: /home/me/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/me/.asdf/shims:/home/me/.asdf/bin:/opt/bin:/home/me/bin:/home/me/miniconda3/bin:/home/me/.cabal/bin:/home/me/.ghcup/bin:/home/me/.cabal:/home/me/.composer/vendor/bin:/opt/node/bin:/home/me/go/bin:/home/me/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/me/.fzf/bin
	LANG                                en_AU.UTF-8
	VISUAL                              vim
	EDITOR                              vim
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                me
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-awesome:/etc/xdg
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 awesome
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      4
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/awesome:/home/me/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop



```

**Additional context**
Can reproduce with  `kitty --config NONE`

**Comment by kovidgoyal** [comment]
Works fine for me. You likely have something in your bashrc interfering.
Try with an empty bashrc.

**Comment by bitwombat** [comment]
Thanks for testing on your side.
It's something in my env.
Future googlers: Run like this:

```
env -i DISPLAY=:0 ./bin/kitty --config=NONE bash --noprofile -l -i
```
That'll give you a completely clean environment, and a default bash (no startup files run).

@kovidgoyal dying to ask you - in your demo vid, you have some interesting patterns. Why do you like to only load dircolours via env/bin/ls? Just because it's clutter to have that var always set (e.g. in .zshrc) ?

**Comment by kovidgoyal** [comment]
On Sun, Mar 19, 2023 at 03:28:56AM -0700, Bit Wombat wrote:
> @kovidgoyal dying to ask you - in your demo vid, you have some interesting patterns. Why do you like to only load dircolours via env/bin/ls? Just because it's clutter to have that var always set (e.g. in .zshrc) ?

yes, env vars are copied to all child processes. It offends my
parsimonious soul to have it copied everywhere for every child process,
vs generating it on the fly for the far smaller number of times ls is
invoked. LS_COLORS is over a kilobyte on my system. It's damn silly that
ls doesnt have the ability to read such config from the file system. I
just havent found the time to send patch upstream, given I highly
suspect a bunch of people will bikeshed it to death.
