### ISSUE TITLE
`shopt -s failglob` in bashrc interferes with shell integration?

### ISSUE THREAD

**Issue by chdiza** [kovidgoyal/kitty#6119]
**Describe the bug**
I'm trying to play around with shell integration, which I've always disabled thus far.  With shell integration enabled, a new kitty window always has the the following above the first shell prompt: `bash: no match: _ksi_prompt[start_mark]`.  Not only is this annoying, but I'm pretty sure it means shell integration never actually gets enabled.  I bisected my bashrc/profile and found that if I comment out the line `shopt -s failglob`, the issue goes away and shell integration works.

**To Reproduce**
1. Move all kitty conf stuff out of the way, so that kitty is running "out of the box".
2. Have bashrc or profile consisting of nothing but `shopt -s failgob`.
3. Start kitty by e.g. being in uxterm and typing `kitty` at the prompt.
4. Observe `bash: no match: _ksi_prompt[start_mark]` at the very top of the newly appearing kitty os window.

**Environment details**
```
kitty 0.27.1 () created by Kovid Goyal
Linux odin 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64
Ubuntu 20.04.5 LTS odin /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/chdiza/sw/kitty-0.27.1/bin/kitty
  base dir: /home/chdiza/sw/kitty-0.27.1/lib/kitty
  extensions dir: /home/chdiza/sw/kitty-0.27.1/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/chdiza/.config/kitty/kitty.conf

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/chdiza/sw/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                chdiza
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-awesome:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session7
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      109
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/awesome:/usr/local/share/:/usr/share/
```

**Additional context**
I'm hoping that if nothing else, somewhere in the shell integration code for bash, there can be a save-and-restore of the user's setting for `failglob`.   I see that there's one in there for `extglob`, for example.

**Comment by chdiza** [comment]
Thanks so much!

**Comment by ionenwks** [comment]
>  BASH aborts the entire script when doing unset with failglob set, somebody should report this upstream

Well, there's globs that are failing. unset still gets expansion like any other commands, e.g. you could `unset var{1,2}` to unset var1 and var2. `unset var[12]` checks if var1 and var2 files exists, and if they don't trigger failglob (if they do, then it attempts to unset var1 and var2 rather than unset var[12]).

Likely want quoted `unset 'var[index]'` to avoid globbing.

**Comment by kovidgoyal** [comment]
On Sat, Mar 25, 2023 at 06:17:49PM -0700, Ionen Wolkens wrote:
> >  BASH aborts the entire script when doing unset with failglob set, somebody should report this upstream
> 
> Well, there's globs that are failing. unset still gets expansion like any other commands, e.g. you could `unset var{1,2}` to unset var1 and var2. `unset var[12]` checks if var1 and var2 files exists, and if they don't trigger failglob (if they do, then it attempts to unset var1 and var2 rather than unset var[12]).

Yes, I figured out why unset fails because of failglob, my point is it should
not. Doing so is completely unexpected. Unsetting something that isnt set
should be a no-op. Anyway, I don't really care. I don't use bash. It's
already worked around in kitty.bash

**Comment by ionenwks** [comment]
Without quoting, it could have unexpected results if the files existed though, it's trying to match file patterns.

**Comment by kovidgoyal** [comment]
I am fine with using quoting instead, assuming it actually fixes the
original issue, feel free to send a PR.
