### ISSUE TITLE
previous_layout action

### ISSUE THREAD

**Issue by cor** [kovidgoyal/kitty#6121]
Same as [`next_layout`](https://sw.kovidgoyal.net/kitty/actions/#action-next_layout), but instead goes to the previous layout

**Additional context**
I often find myself wanting to go back to a previous layout, rather than cycling through all of my layouts to go back again when I've accidentally used the `next_layout` keybinding one too many times

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/actions/#action-last_used_layout

**Comment by cor** [comment]
Thanks for this! However, it is not quite the same as `previous_layout`. Imagine if you have layouts `A, B, C, D, E, F`. You start at layout `B`, then invoke `next_layout` 3 times. You end up on layout `E`. Now if I invoke `previous_layout` 2 times, i expect to end up on layout `C`. This would match the behavior of navigating tabs.

However, if you invoke `last_used_layout` instead of `previous_layout` in the example above, you end up on layout `E`.
