### ISSUE TITLE
Default password file is not working

### ISSUE THREAD

**Issue by perseas12** [kovidgoyal/kitty#6127]
kitty version: 0.27.1

Remote control with password is enabled in the minimal configuration file:

```console
$ cat $HOME/.config/kitty/kitty.conf
allow_remote_control password
remote_control_password "my_password"
```

Create the default password file:

```console
$ printf "my_password" > $HOME/.config/kitty/rc-pass
```

Open a new kitty OS Window and run a kitty command:

```console
$ kitty @ ls
Error: Remote control is disabled. Add allow_remote_control to your kitty.conf
```

The command has failed. However, providing the password file explicitly, works:

```console
$ kitty @ --password-file $HOME/.config/kitty/rc-pass ls
```

**Comment by kovidgoyal** [comment]
remote_control_password does not specify the name of a file to read
passwords from.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remote_control_password

You need to either use --password-file or use the default password
filename of rc-pass

**Comment by olejorgenb** [comment]
I'm facing the same issue. I want to use the remote control, and having a password file with strict permissions seems like a ok tradeoff security-wise.

But typing the `--password-file ...` every time is too much, and since the argument need to go after the `@` using an shell alias does not work. 

> You need to either use --password-file or use the default password filename of rc-pass

But he was using the the default password filename, no?

```
$ printf "my_password" > $HOME/.config/kitty/rc-pass
```

I tried various combinations without success. I always get "Error: Remote control is disabled. Add allow_remote_control to your kitty.conf" when running eg.: `kitten @ create-marker text 1 kitten`

> You can even supply the password via the [...], or the file ~/.config/kitty/rc-password to avoid having to type it repeatedly.

Here the docs say "rc-password" which does not work either.

To be sure: with the correct password file path it should work to not specify `--password-file` at all, correct?

---

kitty version: 0.42.1

**Comment by kovidgoyal** [comment]
On Fri, Jul 04, 2025 at 01:57:45PM -0700, Ole Jørgen Brønner wrote:
> olejorgenb left a comment (kovidgoyal/kitty#6127)
>
> I'm facing the same issue. I want to use the remote control, and having a password file with strict permissions seems like a ok tradeoff security-wise.
>
> But typing the `--password-file ...` every time is too much, and since the argument need to go after the `@` using an shell alias does not work.

I dont follow why would it being after @ prevent you from using an
alias?
alias x="kitten @ --to=unix:/tmp/test"
x ls

works fine. No reason --password-file wont work too.

>
> > You need to either use --password-file or use the default password filename of rc-pass
>
> But he was using the the default password filename, no?
>
> ```
> $ printf "my_password" > $HOME/.config/kitty/rc-pass
> ```
>
> I tried various combinations without success. I always get "Error: Remote control is disabled. Add allow_remote_control to your kitty.conf" when running eg.: `kitten @ create-marker text 1 kitten`

That error message is quite clear you need to actually enable remote
control as well. Here is a one liner for you to demonstrate it actually
works:

```
kitty -o allow_remote_control=y -o remote_control_password=test sh -c "echo -n test > ~/.config/kitty/rc-pass; kitten @ ls; read"
```

>
> > You can even supply the password via the [...], or the file ~/.config/kitty/rc-password to avoid having to type it repeatedly.
>
> Here the docs say "rc-password" which does not work either.

That is indeed a typo and now fixed.

>
> To be sure: with the correct password file path it should work to not specify `--password-file` at all, correct?

Do kitten @ --help and look at the docs of the --password-file flag to
see the real default value.

**Comment by a3lem** [comment]
Kitty version: v0.45.0
OS: macOS

I'm similarly struggling to get the default password to work. My setup is the same as in the original post.

Just as OP observed, including the full path to `rc-pass` is the only thing that seems to work, e.g.

```
$ kitty @ --password-file $HOME/.config/kitty/rc-pass ls
```

Things that don't work:

```
kitten @  ls  # Error: Remote control is disabled [...]
kitten @ --password ls   # drops into kitten shell
kitten @ --password-file ls  # drops into shell
kitten @ --password-file=rc-pass ls  # Error: Remote control is disabled. [...]
```

I experimented with the one-liner in the previous response. As far as I can tell it enables remote control wholesale. All actions succeed regardless of the password set, defeating the purpose.

My use case (for the curious): I'm running untrusted code (AI agents) in a VM sandbox that I'm logged into with the ssh kitten. In my quest to replace TMUX, I want to try giving these agents *limited* access to kitty remote control. So what I'm trying to achieve is:

- On the host OS, kitty can just do whatever, using the default `rc-pass` with broad permissions.
- That password is unavailable inside the VM. Any attempts to use kitty remote control will have to be accompanied by a strictly scoped password.

Sorry for adding to a closed issue. It seemed better to keep the context in one place.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/10273d5aa23530d26f32e57112786161a3061254

**Comment by a3lem** [comment]
Thanks for looking at this! :)The nightly is crashing at startup right now, but I'll try again in a couple of days

**Comment by kovidgoyal** [comment]
Crashing with what error? As far as I know nothing that could possibly cause crashing at startup was done in master for a while.

**Comment by a3lem** [comment]
Here's the crash report: https://gist.github.com/a3lem/80b4cee6f9f28d5cbc5f2c6bae252cf2

I installed by doing

```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    installer=nightly
```

**Comment by kovidgoyal** [comment]
No I meant any output that's written from the kitty process to its
stdout/stderr when launched from another terminal, for instance, or
otherwise in console.app

**Comment by kovidgoyal** [comment]
Or alternately build with debug symbols that will at least tell us which function in kitty code the crash is happening in. https://sw.kovidgoyal.net/kitty/build/

**Comment by a3lem** [comment]
> or otherwise in console.app

That's the same as the crash report in my gist.

If I launch Kitty nightly from Kitty stable, the process exits with a segfault.

```
❯ /Applications/kitty-nightly/kittynightly.app/Contents/MacOS/kitty
fish: Job 1, '/Applications/kitty-nightly/kit…' terminated by signal SIGSEGV (Address boundary error)
```
