### ISSUE TITLE
Escape file path of a file when dragging it into a kitty window

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#613]
I often drag files into a kitty window, for example to change directories. If the path contains special characters like a space, the shell interprets the one string as two strings, which is not what I want. To prevent this, I would like to have an option to tell kitty to escape the file path.
Steps to reproduce:
1. Create a new directory named "a b" (without the quotes)
2. Open a kitty window with a bash compatible shell and type "cd " (without the quotes)
3. Drag the directory into the kitty window
4. Press enter
5. The shell will pass two arguments two cd

Adding a backslash in front of the space would prevent this issue. There might be a few more characters with special meaning, that need to be escaped.
If you think that not everybody wants this behaviour, then being able to enable or disable this behaviour in the config file would be nice.

Tested using kitty built from source, with the latest source code at the time of writing, on macOS 10.13.5.

**Comment by kovidgoyal** [comment]
Seems dicey to me. How is kitty to know what the correct escaping semantics are? What if the user is running a non POSIX shell, or an editor, or some other program for which the escape character is not \
or no escaping is needed?

Why not just type a quote after cd before doing the drag and drop? You are typing cd anyway, might as well type cd "

**Comment by kastaren** [comment]
This is the way it works in Terminal.app an iTerm2 though, so I think many Mac users new to Kitty will expect this functionality. I constantly switch between these applications and it would be really nice not to have to think about this. A setting would be nice.

**Comment by kovidgoyal** [comment]
Sorry, but "other applications do it this way" is not really a good enough reason to import broken behavior into kitty. I appreciate it can be annoying when switching between applications, but that is not a sufficient reason, I'm afraid.

**Comment by Luflosi** [comment]
You can use my quick-and-dirty patch that escapes spaces if you want: https://github.com/Luflosi/kitty/commit/61a60bdbe199eab643e545857ad9170ce8f42339

**Comment by kovidgoyal** [comment]
You are free to patch kitty for it if you like. I can totally understand the frustration of having to re-learn an ingrained behavior.

**Comment by Luflosi** [comment]
I can also understand @kovidgoyal's position and why he won't put this functionality into kitty.
I know that for copy&pasting there is a bracketed paste mode. Couldn't we do something similar for file paths? Maybe another protocol extension?

**Comment by kovidgoyal** [comment]
you'd need to get the developers of shells to use this extension, but sure I would be happy to do that in principle.

**Comment by kpcee** [comment]
Instead of escaping special characters, it would be sufficient to put paths automatically in quotation marks. If a space would be added automatically as well, you could easily add several files one after the other. This is how xfce4-terminal it does and works without problems and is very comfortable.

With kitty, as far as I can see, you not only have to put the quotation marks manually, but also add a space manually after each drag and drop.

**Comment by kovidgoyal** [comment]
@kpcee that works fine in a shell, assuming the shell uses the standard quote characters for quoting. (non POSIX shells have a wide variety of shell specific quoting rules). But what if you are in an editor or a pager, then automatic quoting will be undesired. Again, the correct fix for this is to get shell developers to support a protocol for pasting of file paths. If and when they do, I will be happy to add support for it to kitty.

**Comment by kpcee** [comment]
Okay, but I don't think there will ever be such a protocol, so a feature like this would be a great thing, at least optionally.
