### ISSUE TITLE
Seperate, independently-controlled window zoom levels

### ISSUE THREAD

**Issue by colindean** [kovidgoyal/kitty#6134]
**Is your feature request related to a problem? Please describe.**

When I adjust the zoom, e.g. with `⌘+` or `⌘-` on macOS, I expect the zoom to affect just the window in the foreground. Instead, it affects the zoom on all windows.

**Describe the solution you'd like**

I'd like for window zooming, e.g. with `⌘+` or `⌘-` on macOS, to affect only the foreground window, or to have another keyboard combination that would adjust the zoom in that way.

**Additional context**

I've got a short video taken with my phone camera. Screenshots don't really show the problem adequately, because they can't reflect the difference in DPI.

I'm using a 2021 MBP 16" with a [XEBEC Tri-Screen 2](https://www.thexebec.com/products/xebec-tri-screen-2) mobile monitor pair. On the left monitor in this picture, the screen resolution is set to the 1920x1080. On the right, it's 960x600. The center is 1728x1117, which of course is macOS' Retina something for 3456x2234 or something like that.

![Picture](https://user-images.githubusercontent.com/197224/227747492-1bd833c9-66ab-4491-8677-40bb4a6de14f.jpg)

Note that the terminal text in the center and right is readable, but the left is barely readable squinted to my 20-20 vision eyes.

You can really notice the problem in this video:

https://user-images.githubusercontent.com/197224/227747493-c8d9089d-764d-4125-a48a-3481809dd12c.mp4

Most of the time, when using Kitty, I keep my terminals on one screen. So, I've not noticed this problem before. I'm trialing a new setup with some mobile monitors with wildly different DPI at their native settings and trying out an arrangement with a primary terminal on one screen and a secondary on another, while a third has _something TBD_.

In order to be usable on _both_ physical screen sizes, I have to set the resolution on the smaller screen to a HiDPI setting (physical is 1900x1200, set to 960x600 HiDPI mode in macOS). What I'd like to is to keep the smaller monitor at its higher resolution, but I'd need for Kitty to have **independently controllable window zoom levels**.

Checking others, both iTerm2 and Apple Terminal allow setting window zoom level independently for each window with the `⌘+` or `⌘-` keyboard shortcuts.

**Comment by page-down** [comment]
> ... to affect only the foreground window, or to have another keyboard combination ...

You can change the font size of each OS window.

https://sw.kovidgoyal.net/kitty/conf/#font-sizes

For your use case, you can configure the shortcut key to set the specified font size for current active OS window without having to press it several times.

**Comment by colindean** [comment]
@page-down Perfection. Thank you. I don't know how I missed that in searching.

**Comment by marco-venuti** [comment]
Is it also possible to independently change the font size of different terminals within a single OS window?
