### ISSUE TITLE
Usage: MacOS shortcut to spawn new instance or new window

### ISSUE THREAD

**Issue by tim-hilt** [kovidgoyal/kitty#6137]
I switched to MacOS a week ago and want to make Kitty behave as similar as possible to the setup I had on Linux. One of the most important parts of my Linux-setup was spawning a new terminal window with a shortcut.

On MacOS application-windows seem to be tied to one instance of the application. I have read in other issues, that the `--single-instance` flag basically circumvents the default MacOS behavior, so I've set up a Karabiner-rule, that runs

``` bash
/opt/homebrew/bin/kitty --single-instance
```

if I press a hotkey.

However, it seems like pressing the button repeatedly kills the first terminal window and spawns a new one. I'm pretty sure I've misunderstood how `--single-instance` works.

Could you clarify how this is intended to work and how I can make the "press shortcut to spawn new terminal everytime"-behavior working?

**Comment by kovidgoyal** [comment]
Single instance makes all kitty windows belong to one kitty process. You
just need to run kitty without any flags if you want multiple instances.

**Comment by tim-hilt** [comment]
Thanks for the fast response. Just to clarify the intended workflow:

1. Press shortcut
2. new kitty-window created
3. Press shortcut again
4. Second kitty window created
5. ...

I tried removing the `--single-instance`-flag, but kitty is still spawning a single window when pressing the shortcut repeatedly. Any idea why this might be the case? I'll happily provide more systems information if it adds any benefit to the discussion.

**Comment by kovidgoyal** [comment]
I have no clue what your system config is. Do this:

1) Start kitty
2) Inside kitty run kitty
3) Observe a new instance being created

You need to figure out how to get whatever system you are using to run
the kitty executable just as happens in step (2) above.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

**Comment by tim-hilt** [comment]
Alright - I tried the following:

```
map f1 show_kitty_env_vars
```

as described in the page you linked to, compared the output of `show_kitty_env_vars` to the output of `env`, pasted all the environment-vars that were output by `env` into a plist-file (according to https://stackoverflow.com/a/26586170/9076590).

Still - doesn't work. The last kitty instance is killed and another one is spawned if the shortcut is pressed repeatedly. Do you know of any more guides / things I can try out to make this work on MacOS?
