### ISSUE TITLE
Ligatures not displayed correctly

### ISSUE THREAD

**Issue by 23TNC** [kovidgoyal/kitty#6138]
**Describe the bug**
When I type the cursor will advance, even if there is a replacement.

Here we have a screenshot from kitty where the glyphs are miss aligned
![image](https://user-images.githubusercontent.com/20226280/228053883-d02afe38-eefc-45bc-84b6-801a8d27545f.png)

Here we have a screenshot from a text editor where the glyphs are aligned properly
![image](https://user-images.githubusercontent.com/20226280/228053977-c05e691c-205b-45c1-b543-381c8200b0bd.png)

Here we have the text in another font
![image](https://user-images.githubusercontent.com/20226280/228054017-84a11df5-0168-4041-ba48-904aac1f856c.png)

Kitty will make the correct substitutions, but retain the additional character width. I have not yet identified how to solve this.

Every character in this mono width font is exactly 1152.  The only issue here is when more then one character is collapsed to a single character, as the additional width is retained and displayed.  

Here is an example from above:
![image](https://user-images.githubusercontent.com/20226280/228055452-69064b6d-44c3-406f-bc97-01737325a41c.png) => ![image](https://user-images.githubusercontent.com/20226280/228055547-83867d44-d3fe-4404-8863-f0d921066d5f.png)

Thank you for your time.

**Environment details**
```
wolf@Latitude-7424:~$ kitty --version
kitty 0.27.1 created by Kovid Goyal
wolf@Latitude-7424:~$ kitty --debug-config
Unknown option: --debug-config

wolf@Latitude-7424:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by kovidgoyal** [comment]
kitty displays text in a monospaced grid. That emans for a font to work in kitty it has to have monospaced glyphs and any ligatures in it have to result in combined glyphs that have a width close to the width of the uncombined glyphs. If your font has ligatures that dont fit this pattern it wont work in kitty. Turn it off with the font_features setting in kitty.conf.
