### ISSUE TITLE
kitty @set-tab-title behaviour

### ISSUE THREAD

**Issue by neyuki** [kovidgoyal/kitty#614]
kitty @ set-tab-title foobar

After giving this command, I get following output: ^[P@kitty-cmd{"ok": true}^[\

Then it waits some time, and print: Failed to receive response from kitty

Tab title is changed though. Is that normal? (kitty from master on linux)

**Comment by kovidgoyal** [comment]
Works for me on linux. For some reason on your system, the response from kitty is not being read, it doesn't really matter since setting tab title never fails barring catastrophic errors. So just ignore it.

**Comment by kovidgoyal** [comment]
Note that since I cannot replicate the issue I cannot be sure I have fixed it. So please test.
