### ISSUE TITLE
Tweak window decoration to "transparent titlebar" with buttons

### ISSUE THREAD

**Issue by bric3** [kovidgoyal/kitty#6144]
**Is your feature request related to a problem? Please describe.**
I would like to have a "transparent title bar" with button controls (close, minimize, maximize).

Thanks in advance for considering this.

**Describe the solution you'd like**
I would like to have a "transparent title bar" with button controls (close, minimize, maximize).

**Describe alternatives you've considered**
Currently I only have this partially with 

1. set `hide_window_decorations titlebar-only`
2. set `window_padding_width 28 5 5`

**Additional context**
<img width="982" alt="image" src="https://user-images.githubusercontent.com/803621/228512435-ab36e399-0224-45aa-974e-bb58ba4425ca.png">

E.g. something like 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/803621/228512566-92495451-4ef3-4eee-b424-1d958ee12e5b.png">

**Comment by kovidgoyal** [comment]
titlebars on macOS are drawn by the OS. They can only be customized so
much.

**Comment by bric3** [comment]
Yes but apparently some programs manage that, even in Java (using Swing) this is possible.

**Comment by bric3** [comment]
I would do it if it was the ecosystem I was proficient enough.
Thanks for considering this though.
