### ISSUE TITLE
Weird rendering (unusable) with X11+nvidia 525.89.02 on linux

### ISSUE THREAD

**Issue by afranchuk** [kovidgoyal/kitty#6145]
**Describe the bug**
Yesterday I updated my nvidia drivers to the latest version on x86-64 linux (525.86.02). After restarting the system, kitty no longer renders correctly. It _does_ take input correctly (for instance if I type a GUI application in and hit enter that executes as expected). However the kitty window stays blanked to my configured background color. The only time it (sometimes) renders correctly is when the window is first opened and when the window is resized. Otherwise, the window just displays the background color as I type input of any kind.

Bugs of this nature may not be kitty's fault, but I'm putting this here in case others see similar behavior (or not) to try to narrow down what's to blame.

**To Reproduce**
1. Install the latest nvidia x86-64 linux drivers.
2. Open a kitty terminal.
3. Type anything

**Environment details**
I could kind of view environment details only by resizing the window after pressing Ctrl+Shift+F6, however the issue is present with `kitty --config NONE` so those details are likely not pertinent.

OS: void-linux
Kernel: linux 6.1.21
Display: xorg 7.6
Graphics Driver: nvidia 525.86.02
Terminal: kitty 0.26.5 (I tried 0.27.1 as well, same result)

**Comment by kovidgoyal** [comment]
This will be a driver issue, downgrade your drivers and report the bug
there. Thanks for the heads up.

**Comment by afranchuk** [comment]
Yeah, that's basically what I thought. It looks like it affects a few other applications as well (at the time I submitted the bug I hadn't encountered issues in other applications).
