### ISSUE TITLE
Blinking cursor animations

### ISSUE THREAD

**Issue by MaxenceDC** [kovidgoyal/kitty#6147]
I think a modern and interesting feature could be the addition of different cursor blinking animations, like in the VSCode IDE

Examples:

_Smooth_
![Smooth](https://i.imgur.com/tousmVO.gif)

_Expand_
![Expand](https://res.cloudinary.com/practicaldev/image/fetch/s--9vbS87WJ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://cdn.hashnode.com/res/hashnode/image/upload/v1598896814528/zHTpqERwC.gif)

-------
By the way, I love this terminal emulator and the work you put into it, thank you!

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but patches are welcome.
