### ISSUE TITLE
Support adjusting OS window size when changing font size

### ISSUE THREAD

**Issue by ericvw** [kovidgoyal/kitty#6149]
**Is your feature request related to a problem? Please describe.**

As I migrate to kitty from iTerm2, there is a setting/behavior to [adjust window when changing font size](https://iterm2.com/documentation-preferences-general.html) I would like to achieve, and I couldn't discover how to do this when reading/searching the documentation.

With iTerm2, I have two profiles depending if I am working on my laptop or a 4k display — the only difference between the two is the font size (16pt vs 20pt). Depending on the monitor, I launch the respective profile. With the iTerm2 setting enabled, the OS window is scaled appropriately (by cell) according to the font size. Also, the OS window is scaled accordingly when changing the font size through keyboard shortcuts.

As I am getting accustomed to kitty, whenever I change the font size via the keyboard shortcuts, I am manually adjusting the OS window size. I could be just doing this incorrectly.

**Describe the solution you'd like**

A `kitty.conf` option to scale the OS window when changing the font size.

Otherwise, I am happy to use a different approach to achieving similar behavior.

**Describe alternatives you've considered**

I'm still new to kitty, and this may be possible with some of the more advanced features to script/extend kitty. I was hoping there as built-in functionality for such a feature and wanted to start there first.

**Comment by kovidgoyal** [comment]
You can use remote control to do this in your own script. 
https://sw.kovidgoyal.net/kitty/remote-control/

Or alternately write a kitten to do it for you:
https://sw.kovidgoyal.net/kitty/kittens/custom/

As for an option to have kitty do it automatically, I'm not a fan as
this will not work robustly in all situations. What if the wndow is full
screen? Or the user is using a tiling window manager. In neither case
will resizing the OS window from within kitty work.

**Comment by ericvw** [comment]
Thank you for the response. I'll read up further and explore remote control and kittens.
