### ISSUE TITLE
Change your README and website to clearly state that Windows is NOT SUPPORTED.

### ISSUE THREAD

**Issue by 256k** [kovidgoyal/kitty#6161]
I think it's absolute bullshit that you claim this is a "cross-platform" terminal while leaving out entirely Windows as if it's not a huge part of the platform ecosystem. I'm not a windows fan and i wish i could never use it again, but i do use it for work and it's almost insulting to read "cross platform" but then don't even see windows mentioned.

**Comment by kovidgoyal** [comment]
No.

**Comment by garak92** [comment]
People still use Windows in 2023?
