### ISSUE TITLE
[097 18:03:26.512507] Unknown uniform in borders program: _main_pos_map_0[0]

### ISSUE THREAD

**Issue by MrMic** [kovidgoyal/kitty#6162]
**Describe the bug**
Crash after start

$> kitty
[097 18:03:26.512507] Unknown uniform in borders program: _main_pos_map_0[0]

$> kitty --debug-config
kitty 0.15.0 created by Kovid Goyal
Linux bureau2-localdomain-local 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64
Ubuntu 20.04.6 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf
Running under: X11

Config options different from defaults:
update_check_interval 0.0

**Comment by kovidgoyal** [comment]
This is a bug in the graphics drivers on your system. Try updating them.

**Comment by MrMic** [comment]
My system is already updated !

**Comment by kovidgoyal** [comment]
You are running a years old version of kitty on a years old OS. I dont know on what planet you consider that updated, it isnt on this one.

**Comment by MrMic** [comment]
I have found another way with:
https://www.linuxfordevices.com/tutorials/ubuntu/install-kitty
Sorry for the noise!
