### ISSUE TITLE
Dragging should happen with a mouse grab

### ISSUE THREAD

**Issue by dcolascione** [kovidgoyal/kitty#617]
Right now, kitty tracks mouse presses and releases manually without grabbing the mouse, which 1) occasionally leads to unexpected mouse selections when we receive spurious release events, and 2) prevents dragging working when the mouse cursor moves outside the bounds on the window. The program should be using an X11 mouse grab like most other programs and activate the selection only on a release event *with grab held*, which would solve the problem.

Re #1: Suppose we mark a window dirty (resetting the selection to 0/0) and then receive a spurious release event somewhere in the window. We think that this event is a release corresponding to a drag end and so highlight the window from the start of the screen to wherever the spurious release event happened to be.

**Comment by kovidgoyal** [comment]
I dont think glfw has this functionality, the closest I could find is http://www.glfw.org/docs/latest/group__input.html#gaa92336e173da9c8834558b54ee80563b
which grabs the mouse but also hides the cursor. 

One could of course add it, but it would be X11 only, and I like to avoid backend specific behaviors as much as possible. Indeed, under some backends, such as wayland (and maybe also cocoa) I dont think grabbing the cursor is even possible.

As for 1) it should be possible to fix the issue without needing to grab the mouse, we will discuss it on your PR. If not, then I can probably add the requisite API to my fork of glfw for X11.

And for (2) I'm ok with selections not being updated when the mouse leaves the window, if it is a problem for someone, adding window padding in kitty.conf should mitigate the issue.
