### ISSUE TITLE
kitty does not detect fn key

### ISSUE THREAD

**Issue by executionByFork** [kovidgoyal/kitty#6177]
I just installed kitty on MacOS Monterey, and I can't seem to figure out why the fn key is not being detected. I would like to use fn+left arrow to jump to the beginning of a line, and added the following into my kitty config file.
```
map fn+left send_text all \x01
map fn+right send_text all \x05
```

When running kitty as shown
`kitty +kitten show_key -m kitty`
I can see it is picking up the ctrl, alt, and cmd keys just fine. Pressing fn does nothing. Additionally, holding fn and pressing another key shows only the other key as detected, as if fn was not pressed at all.

**Comment by kovidgoyal** [comment]
That will be because this key is not passed to kitty by the OS. Fn is not a modifier in macOS. Easily checked by running 

kitty --debug-input
