### ISSUE TITLE
Mac Hardware: Text near top of screen will disappear behind camera housing.

### ISSUE THREAD

**Issue by Love-chan5252** [kovidgoyal/kitty#6178]
When you type text that starts near the top of the screen when using fullscreen mode or when the tool bar is hidden, text will disappear behind the camera housing that "dips" down into the display.

Perhaps configuration for "dead zones" could be added? Zones in which text/rendering will be skipped over to the end of the dead zone.

Steps to reproduce:
1. Set Kitty to full screen on a Macbook Pro or other computer where the camera obscures part of the screen.

Picture (forgive the g*nshin background):
![IMG_1935](https://user-images.githubusercontent.com/65145836/231617784-342b84ed-008f-4e82-badf-312a93c7233f.jpg)

**Comment by kovidgoyal** [comment]
I'm afraid not. A terminal is a fixed width grid of characters, it
cannot have dead zones at random point in the middle of lines. Use a
window margin/padding.
