### ISSUE TITLE
Option doesn't work as Alt

### ISSUE THREAD

**Issue by cherrypiejam** [kovidgoyal/kitty#6180]
**Describe the bug**
I run skhd as my hotkey daemon for some tasks. It works fine with other apps focused (i.e. firefox), but when a Kitty window is focused, Kitty instead prints special symbols if I press a hotkey that contains Option. For example, Option + X is configurated in skhd to launch a new instance of Kitty, but in Kitty the hotkey prints `≈`. I suspect it's a bug in Kitty because the hotkeys work fine in other settings. 

**To Reproduce**
1. Set a hotkey that uses Option as the modifier in skhd
2. Start a skhd daemon
3. Start a Kitty instance and focus it
4. Press the hotkey

**Screenshots**

**Environment details**
```
Kitty 0.27.1, m1 mac
```

**Additional context**
Same with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
kitty will only print a character if it receives that character.
Presumably your other programs start up so slowly they dont receive the
character. You need to followup with skhd.
