### ISSUE TITLE
kitten for lxc shell itegration or allow to pass the pid of the windows that runs launch to a script.

### ISSUE THREAD

**Issue by alkeryn** [kovidgoyal/kitty#6181]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
so you know how we have the ssh kitten that allows to for example spawn new windows in connected to ssh with the same cwd and other things, would it be possible to do something similar for lxd containers ?
i often use command such as `lxc exec containername -- su - <username>` it would be neat that if i want to open a new kitty window, it opens the new window, and run the same lxc command but also move to the desired path.
**Describe alternatives you've considered**

i did some scripting to be able to get the path from the lxc container attached to a specific shell pid, i could probably be able to build that feature with kitty's launch command if only there was a way to get the pid of the kitty window that runs "launch" or the shell running within it.

thanks for the good software.
**Additional context**

**Comment by kovidgoyal** [comment]
the kitty window id and pid are both available as env vars inside all
kitty windows. https://sw.kovidgoyal.net/kitty/glossary/#variables-that-kitty-sets-when-running-child-programs

**Comment by alkeryn** [comment]
@kovidgoyal yes but that does not help since kitty windows share the same pid when opened with lauch.
couldn't there be a way to pass the current shell pid of window A as an argument to launch ?

**Comment by kovidgoyal** [comment]
That will depend on your shell exporting its PID.

**Comment by alkeryn** [comment]
yes but even exported how can i pass it to the new windows or script with launch ?

**Comment by kovidgoyal** [comment]
However you like, you can run arbitrary command with launch, set env
vars, pass command line arguments.

**Comment by kovidgoyal** [comment]
Use 

kitty @ launch

not a launch mapping. And if you want details of the currently focused
window, in a launch keybinding, then write a kitten to do that.
https://sw.kovidgoyal.net/kitty/kittens/custom/

**Comment by alkeryn** [comment]
@kovidgoyal thanks for the help, i'll see what i can do !
