### ISSUE TITLE
tests for linux-package

### ISSUE THREAD

**Issue by solopasha** [kovidgoyal/kitty#6182]
**Is your feature request related to a problem? Please describe.**
Hi! According to https://github.com/kovidgoyal/kitty/blob/2f63f24e7d7a7998bd79fea0d74633f2453fdd38/setup.py#L1444-L1445 it seems that tests are installed & can be run only for *-freeze actions, can they also be run with linux-package?

**Describe the solution you'd like**
Tests are installed with linux-package

**Comment by kovidgoyal** [comment]
Not sure what you are asking. If you want to run the tests, simply run

make test
