### ISSUE TITLE
url_excluded_characters change in 0.28.0

### ISSUE THREAD

**Issue by chmouel** [kovidgoyal/kitty#6184]
**Describe the bug**

Since the upgrade to 0.28.0 i am getting this error

```
1:EOL while scanning string literal (<unknown>, line 1) in line: url_excluded_characters "}{'
**To Reproduce**
```

my url_excluded_characters config:

```
url_excluded_characters "}{'
```

It was working fine with 0.27.x

**Comment by kovidgoyal** [comment]
Change it to

url_excluded_characters '''"}{''''
