### ISSUE TITLE
Open a new shell session from other applications

### ISSUE THREAD

**Issue by sheijk** [kovidgoyal/kitty#6190]
Kitty provides the remote control API to create new tabs/windows from inside the shell and with a socket it can also let other apps use this. But this only works if Kitty is already running. Also figuring out the socket/pid is messy. I'd like to have a straight-forward way to invoke Kitty to open a new tab/window which will also work when Kitty is not running.

**Describe the solution you'd like**
A command line option similar to [Gnome Terminal's --tab](https://man.archlinux.org/man/gnome-terminal.1.en) would do the trick

**Describe alternatives you've considered**
A wrapper script which tries to connect to the socket and starts a new Kitty instance if needed would be a work-around. There is also mention of a kitten executable in #5956 but this seems to not be distributed with Homebrew or Nix packages

**Comment by kovidgoyal** [comment]
kitty --listen-on /tmp/mykitty

or

kitty --single-instance
