### ISSUE TITLE
Setting theme with +kitten themes produces empty current-theme.conf

### ISSUE THREAD

**Issue by smeikx** [kovidgoyal/kitty#6191]
Setting color theme/scheme using `kitty +kitten themes` does not work since 0.28.0, it only produces an empty `current-theme.conf`.

**To Reproduce**
1. `kitty +kitten themes`
2. select theme
3. press `m`
4. **an empty `~/.config/kitty/current-theme.conf` has been created**
5. `~/.config/kitty/kitty.conf` now contains this:
```
# BEGIN_KITTY_THEME
# Ayu Light
include current-theme.conf
# END_KITTY_THEME
```
The same happened with a different theme and when directly specifying a theme: `kitty +kitten themes duckbones`

**Environment details**
I tried it on Linux (Gentoo, sway) and macOS, each with my custom config and a completely empty `~/.config/kitty/kitty.conf`.

**Comment by kovidgoyal** [comment]
Works for me with

mv ~/.config/kitty /tmp && kitty +kitten themes duckbones && cat ~/.config/kitty/current-theme.conf&& rm -rf ~/.config/kitty && mv /tmp/kitty ~/.config

The duckbones theme is displayed, as expected.

**Comment by smeikx** [comment]
I overlooked a _major_ detail, sorry for being sloppy:

I forgot I have `~/.config/kitty/themes/`, containing `Ayu Light.conf` and `duckbones.conf`! Out of habit I subconsciously only tested with themes I am familiar with. 🤦 

It seems only overwritten and custom themes are affected. When running `kitty +kitten themes Grape` everything works as expected.

But by 

1. storing the output of `kitty +kitten themes --dump-theme Grape` in `~/.config/kitty/themes/Grape.conf` (curiously, using `>` did not work)
2. and running `kitty +kitten themes Grape`

the same thing happens as described in the issue. After removing `Grape.conf` it worked again.  
I also copied `Grape.conf` to `~/.config/kitty/themes/testy.conf` and tried setting this entirely new theme, but with no success.

---

PS: I noticed that the name in the comment header in a theme file (`## name: duckbones`) seems to have precedence over the file name when selecting a theme. This is [not mentioned in the documentation](https://sw.kovidgoyal.net/kitty/kittens/themes/#using-your-own-themes), specifically this line is misleading:

> You can use this to modify the builtin themes, by giving the conf file the name `Some theme name.conf` to override the builtin theme of that name.

**Comment by huyz** [comment]
Same.  The switching with **user-defined themes** is broken and I end up with an empty `current-theme.conf`

**Comment by olimorris** [comment]
Yeah I'm having this issue too.

**Comment by AdsonCicilioti** [comment]
I'm confirm this bug! The strange thing is that it was working normally.  But today after an update no more.

**Comment by huyz** [comment]
There's no need to add "me too"s.  This issue was closed because it was fixed by Kovid.  So you can expect the fix in the next release.
