### ISSUE TITLE
Fonts are thinner and less clear in editor after updating to kitty@0.28.0

### ISSUE THREAD

**Issue by xcpky** [kovidgoyal/kitty#6197]
**Describe the bug**
Hi guys, I am using helix editor and kitty for a long time. I just update kitty to 0.28.0 and find the terminal font is more thick and clear, which I do love. But I also find that in helix editor(similar to vim) the font seems thinner and less clear. And I found that in dark theme the rendering seems normal. I'll show old kitty, new kitty, and new kitty with dark theme in the screenshots.

**To Reproduce**
1. update kitty to 0.28.0
2. use helix editor

**Screenshots**
the picture below shows old kitty font rendering.
![oldkitty](https://user-images.githubusercontent.com/52552971/233248441-56462fdc-e4b8-4d06-b889-700fd834bf59.png)

the picture below shows new kitty font rendering.
![newkitty](https://user-images.githubusercontent.com/52552971/233248462-271dbe01-ac19-4eec-9dc1-c233cdb9c003.png)

the picture below shows new kitty font rendering in dark theme.
![newkitty-dark](https://user-images.githubusercontent.com/52552971/233248854-aa5c3b3b-8565-4ae1-a019-d1e357de0fce.png)

**Environment details**
os: archlinux
font: Hack Nerd Font Mono with font size 13

**Comment by kovidgoyal** [comment]
Read the changelog

**Comment by sharnoff** [comment]
Commenting for others who come across this:

Restoring the old font rendering can be done by setting
```
text_composition_strategy legacy
```
in your config file.

- Changelog: https://sw.kovidgoyal.net/kitty/changelog/#id2
- `text_composition_strategy` details: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy

**Comment by saviola777** [comment]
Thank you! I was about ready to make an appointment with my eye specialist.

I first tried legacy and then played around with the two values until I settled on 1.5 and 15.
