### ISSUE TITLE
Mouse selection broken

### ISSUE THREAD

**Issue by binor** [kovidgoyal/kitty#62]
On a MacBook Pro 15" (2016) running macOS 10.12.3 (16D32) the selection coordinates are off. I can't click a link nor select text.

#43 did not fix it for me.

**Comment by kovidgoyal** [comment]
Unfortunately, I dont have a mac machine capable of running kitty (only building it) so there is no way for me to investigate/fix the problem. Someone that can reproduce it will need to contribute. I suggest posting in #43 to see if the OP there is willing to help.

**Comment by binor** [comment]
Thank you! Will do.
