### ISSUE TITLE
Foreground, background cursor color for vi mode

### ISSUE THREAD

**Issue by bmariuszb** [kovidgoyal/kitty#6200]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup ~/.inputrc for vi mode and set cursor colors for ins and cmd mode, but I can't change the color of the character under the cursor, because OSC(Operating System Commands) doesn't have this feature.

**Describe the solution you'd like**
I would like to have modified version of this

> OSC Ps ; Pt BEL
> OSC Ps ; Pt ST
> Ps = 1 2  ⇒  Change text cursor color to Pt. (it actually changes the color of the cursor), this is from [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_)

to this
> OSC Ps ; Pt1 ; Pt2 BEL
> OSC Ps ; Pt1 ; Pt2 ST

Use Pt1 as the foreground cursor color and Pt2 as the background cursor color, or alternatively, use Pt1 for the cursor color and Pt2 for the character color under the cursor. It should be possible, because similar things are already implemented:
```
printf "\e[48;2;135;206;235m"
```
The character color under the cursor probably has a set color function, because by default the character under the cursor is black, at least for block cursor, but it changed to white after running this command
```
printf "\e]12;red\e\\"
```

Currently this command works
```
printf "\e]12;red;green\e\\"
```
, but it only sets the cursor color, but the character is actually white, not black as for default cursor color.

**Describe alternatives you've considered**
- Give up
- Maybe create a feature request somewhere in Xterm repo

**Additional context**
Feel free to ask me if you need any clarification.

**Comment by kovidgoyal** [comment]
It's possible certainly, but unless there is buy in from some major application developers, say of vim or emacs or similar stating they will use the feature, I am not interested in doing the work. That said a patch is welcome. As for your use case, it might be nicer to just modify the prompt when the mode changes. Some more advanced prompt libraries support doing this.
