### ISSUE TITLE
SSH Kitten regression: `hostname` config discards all other config items as of 0.28.0

### ISSUE THREAD

**Issue by azertyfun** [kovidgoyal/kitty#6202]
**Describe the bug**
Hi,

Since Kitty 0.28.0, when I use the `hostname` config item in `ssh.conf` to set a color scheme for certain hosts, my `env` arguments (possibly everything else as well, I didn't check) get discarded. This used to work in 0.27.x. I assume it's related to d98504e?

**To Reproduce**
1. `ssh.conf`:
   ```
   env TESTVAR=abc
   hostname testhost
       color_schemes themes/testhost.conf
   ```
2. ```
    $ ssh somehost
    somehost$ echo $TESTVAR
    abc
    somehost$ exit
    $ ssh testhost
    testhost$ echo $TESTVAR
    testhost$ exit
    ```
3. I would expect that on both hosts `$TESTVAR`  would be defined.

**Screenshots**
N/A

**Environment details**
```
kitty 0.28.0 created by Kovid Goyal
Linux chort-nmo 6.2.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Apr 2023 16:59:24 +0000 x86_64
Arch Linux 6.2.11-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: [32mWayland[39m
[32mFrozen:[39m False
[32mPaths:[39m
[33m  kitty:[39m /usr/bin/kitty
[33m  base dir:[39m /usr/lib/kitty
[33m  extensions dir:[39m /usr/lib/kitty/kitty
[33m  system shell:[39m /usr/bin/xonsh
[32mLoaded config files:[39m
  /home/nathan/.config/kitty/kitty.conf

Config options different from defaults:
allow_hyperlinks        0
allow_remote_control    yes
enable_audio_bell       False
enabled_layouts         ['splits', 'stack']
focus_follows_mouse     True
font_family             Fira Code Nerd Font
font_size               8.5
initial_window_height   (480, 'px')
scrollback_lines        100000
visual_bell_duration    0.05
[94mAdded shortcuts:[39m
	alt+down →  neighboring_window down
	alt+enter →  launch --type=window --cwd=current
	alt+f →  goto_layout stack
	alt+h →  neighboring_window left
	alt+j →  neighboring_window down
	alt+k →  neighboring_window up
	alt+l →  neighboring_window right
	alt+left →  neighboring_window left
	alt+right →  neighboring_window right
	alt+s →  layout_action rotate
	alt+t →  launch --type=tab --cwd=current
	alt+tab →  next_tab
	alt+up →  neighboring_window up
	ctrl+alt+t →  set_tab_title
	shift+alt+down →  resize_window shorter
	shift+alt+enter →  launch --type=window
	shift+alt+f →  last_used_layout
	shift+alt+h →  move_window left
	shift+alt+j →  move_window down
	shift+alt+k →  move_window up
	shift+alt+l →  move_window right
	shift+alt+left →  resize_window narrower
	shift+alt+right →  resize_window wider
	shift+alt+t →  launch --type=tab
	shift+alt+tab →  previous_tab
	shift+alt+up →  resize_window taller
[94mRemoved shortcuts:[39m
	kitty_mod+enter →  new_window
	kitty_mod+r →  start_resizing_window
[94mColors[39m:
	active_tab_background   #818387 [48:2:129:131:135m  [49m
	active_tab_foreground   #2c2d31 [48:2:44:45:49m  [49m
	background              #232326 [48:2:35:35:38m  [49m
	color0                  #101012 [48:2:16:16:18m  [49m
	color1                  #de5d68 [48:2:222:93:104m  [49m
	color10                 #51a8b3 [48:2:81:168:179m  [49m
	color11                 #dbb671 [48:2:219:182:113m  [49m
	color12                 #57a5e5 [48:2:87:165:229m  [49m
	color13                 #e557b3 [48:2:229:87:179m  [49m
	color14                 #48b0bd [48:2:72:176:189m  [49m
	color15                 #a7aab0 [48:2:167:170:176m  [49m
	color2                  #8fb573 [48:2:143:181:115m  [49m
	color3                  #dbb671 [48:2:219:182:113m  [49m
	color4                  #57a5e5 [48:2:87:165:229m  [49m
	color5                  #e557b3 [48:2:229:87:179m  [49m
	color6                  #48b0bd [48:2:72:176:189m  [49m
	color7                  #999ca1 [48:2:153:156:161m  [49m
	color8                  #5a5b5e [48:2:90:91:94m  [49m
	color9                  #c49060 [48:2:196:144:96m  [49m
	foreground              #a7aab0 [48:2:167:170:176m  [49m
	inactive_tab_background #2c2d31 [48:2:44:45:49m  [49m
	inactive_tab_foreground #818387 [48:2:129:131:135m  [49m

[32mImportant environment variables seen by the kitty process:[39m
	PATH                                [2m/home/nathan/.local/bin:/home/nathan/.local/bin/dotbin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/home/nathan/.dotnet/tools:/home/nathan/.local/share/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl[22m
	LANG                                [2men_US.UTF-8[22m
	SHELL                               [2m/bin/bash[22m
	DISPLAY                             [2m:0[22m
	WAYLAND_DISPLAY                     [2mwayland-1[22m
	USER                                [2mnathan[22m
	XCURSOR_SIZE                        [2m24[22m
	XDG_SEAT                            [2mseat0[22m
	XDG_SESSION_TYPE                    [2mwayland[22m
	XDG_CURRENT_DESKTOP                 [2msway[22m
	XDG_SESSION_CLASS                   [2muser[22m
	XDG_VTNR                            [2m2[22m
	XDG_SESSION_ID                      [2m1[22m
	XDG_RUNTIME_DIR                     [2m/run/user/1000[22m
	XDG_DATA_DIRS                       [2m/home/nathan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share[22m

[35mThis debug output has been copied to the clipboard[m
```

**Additional context**

**Comment by kovidgoyal** [comment]
IIRC this was a deliberate change that I forgot to document. The previous behavior in this case was not really well defined. Having config keys fallback to the value in some previously matched host if not specified is pretty fragile, it means that if you later edit the config and insert a new host block it can potentially change the values of things for subsequent blocks by "magic". And re ordering the blocks can also change things in non-obvious ways.

Instead the current behavior is that when a host block starts, all config for it is set to default values, not inherited from previous blocks. 

If you wish to share config between multiple host blocks, the best way to do that is using the include directive. As documented here: https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.hostname
This makes the sharing explicit and not order dependent.

I will add a note to the docs indicating this behavior changed in 0.28.0. Apologies for the inconvenience. I generally try not to break backwards compat but in this case I felt the previous behavior was bad enough that it was worth it.
