### ISSUE TITLE
scroll_end after show_scrollback does not take effect

### ISSUE THREAD

**Issue by ppwwyyxx** [kovidgoyal/kitty#6207]
**Describe the bug**
I want to get the benefits of both the following two in one keymap (i) flexible scroll destination such as `scroll_page_{up,down}, scroll_to_prompt` (ii) the power of the custom `scrollback_pager` . So I have the following config:

```
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
map shift+page_up       combine : scroll_page_up : show_scrollback : scroll_end
```

This will (i) scroll to one page earlier, and (ii) starts my pager at this location - as expected.
However, the problem is, when I quit the pager (with `q`), the terminal stays at one page earlier, despite I wrote `scroll_end` in the mapping.

**To Reproduce**
1. start kitty with a minimal config with the above two lines
2. trigger the above mapping
3. quit the pager
4. terminal didn't scroll to end

**Environment details**
```
kitty 0.28.0 (6e90bc1996) created by Kovid Goyal
Linux KeepRunning 6.2.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:27 +0000 x86_64
Arch Linux 6.2.12-zen1-1-zen (/dev/tty)
```

**Comment by kovidgoyal** [comment]
your last mapping will apply to the newly created window showing the scrollback. If you want to do this you will need to write a custom kitten for it. That will scroll, show the scrollback then scroll the original window back to the end.

**Comment by ppwwyyxx** [comment]
ic.. thanks for the clarification.
With this knowledge I can actually get what i want with:
```
map shift+page_up       combine : show_scrollback : send_text normal u
```
Except that this won't allow me to scroll to last prompt.
