### ISSUE TITLE
Clock updates going to wrong screen position in irssi/screen

### ISSUE THREAD

**Issue by dcolascione** [kovidgoyal/kitty#621]
When running irssi inside screen, updates occasionally go to the wrong place in the screen buffer. See the attached screenshots. Note that the timestamp in the "wrong" copy of the time string is later than the timestamp in the correctly-positioned time string. In other terminal emulators (pictured here, alacritty) connected to the same screen session, the irssi-screen combination doesn't misplace the clock.

![kitty](https://user-images.githubusercontent.com/331322/41194539-87969836-6bd1-11e8-99a4-9214ad2ab4d2.png)
![alacritty](https://user-images.githubusercontent.com/331322/41194556-dde52964-6bd1-11e8-8236-d44a7e457ceb.png)

**Comment by kovidgoyal** [comment]
Run kitty with --dump-bytes, do the minimum you can to reproduce the error and post the bytes log.

**Comment by dcolascione** [comment]
Cool debugging feature. Logs attached. The first incorrect clock update is 11:10. 
[kitty-bug.log](https://github.com/kovidgoyal/kitty/files/2087218/kitty-bug.log)
[kitty-bug.bytes.log](https://github.com/kovidgoyal/kitty/files/2087220/kitty-bug.bytes.log)
