### ISSUE TITLE
Feature request: Add option to start with blank input when renaming tab (as was the default before)

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#6217]
After updating Kitty to the latest version, changing tab title now has as a preset the current title. I think this is more inconvenient than the previous setting (blank input) :((

Would it be possible to add an option? Thanks in advance

Fwiw, I wasn't able to find this change in the Changelog.

**Comment by hacker-DOM** [comment]
Hmm, `ctrl-u` works to delete the input. Still would be nice to not have to press this every time :-)

**Comment by kovidgoyal** [comment]
the prompt, unlike before, supports default readline bindings, so you can easily
clear it with a single keypress. I am afraid I am not interested in
adding an option for this.

**Comment by kovidgoyal** [comment]
On second thoughts it's easy enough to add an option for it. Done.
