### ISSUE TITLE
Margin and body color no longer match when using lower opacity

### ISSUE THREAD

**Issue by gyvess** [kovidgoyal/kitty#6224]
X11
Picom Compositor
Mesa git
Kitty git

Regardless of background color set, the margin color is lighter than the body color.  Looks fine if you have background_opacity set to 1(default). I'm assuming this has to do with the background_opacity_fringing merge.

First pic is how it used to look. Second pic is what it looks like now, with the margins increased to 100 to make it more noticeable.

foreground #6c6c6c
background #FAFAFA
background_opacity 0.85
![23-01-12-121554_maim](https://user-images.githubusercontent.com/6826350/235293621-ba8c55f9-203d-4564-b067-0680471d28f4.png)
![23-04-29-040352_maim](https://user-images.githubusercontent.com/6826350/235293622-7ee8fda2-d315-4cc6-be95-b24316707ba3.png)

**Comment by kovidgoyal** [comment]
ping @m4rw3r this is caused by 9f41183628eac83ad37a7d7dc7bd6626b62079cb

**Comment by kovidgoyal** [comment]
Note that my fix is likely incomplete, the conditions in which linear2rgb are applied need to be matched up between the two shaders.
