### ISSUE TITLE
Inconsistent Font Rendering on Darker and Lighter Backgrounds

### ISSUE THREAD

**Issue by joshuajeschek** [kovidgoyal/kitty#6226]
**Describe the bug**
I noticed, following a recent update, that the font rendering had changed drastically. There seems to be some sort of fringing, the text looks quite fuzzy at the edges, definitely thicker than it should be.
I tried to remedy this with the new `text_composition_strategy` setting, and tried it out on a completely black background (background opacity set to 1, usually I have it on 0.5).
It seemed to improve the result, however when i switched the background opacity back to 0.5, it was looking quite different again. There are 6 Screenshots below, showing the problem on different backgrounds and different `text_composition_strategy` settings.

**To Reproduce**
1. set `background_opacity` to 0.5
2. use a wallpaper with varying brightness
3. move the window around to observe inconsistencies
4. test out with different `text_composition_strategy` values

**Screenshots**
<details><summary><code>text_composition_strategy legacy</code> on a lighter background:</summary>
<img alt="legacy on light background" src="https://user-images.githubusercontent.com/64850647/235348002-39539824-9f14-4236-b4bd-ca6a98e78d99.png">
</details>

<details><summary>default value for <code>text_composition_strategy</code> on a lighter background (the worst of all possibilites):</summary>
<img alt="default on light background" src="https://user-images.githubusercontent.com/64850647/235348059-b381699b-8501-445e-bf32-6da422f800c6.png">
</details>

<details><summary><code>text_composition_strategy legacy</code> on a darker background (acceptable imo, but not every region of my wallpaper is this dark):</summary>
<img alt="legacy on dark background" src="https://user-images.githubusercontent.com/64850647/235348093-a17a84d5-fe9e-415a-944d-81986823f824.png">
</details>

<details><summary>default value for <code>text_composition_strategy</code> on a darker background (less noticable but still codetty fuzzy):</summary>
<img alt="default on dark background" src="https://user-images.githubusercontent.com/64850647/235348140-8d371277-fbe5-48e8-8b26-daef33f75942.png">
</details>

<details><summary>default value for <code>text_composition_strategy</code> on a completely black background looks fine, but is actually to thick:</summary>
<img alt="default value on black" src="https://user-images.githubusercontent.com/64850647/235348209-4d6e5fac-5956-4d34-997d-16968cf4f4f8.png">
</details>

<details><summary><code>text_composition_strategy legacy</code> on a completely black background is exactly how i would expect it to look:</summary>
<img alt="legacy on black" src="https://user-images.githubusercontent.com/64850647/235348292-3c6c72f1-9d12-4447-9086-5a91c013a289.png">
</details>

**Environment details**
The listed options for `text_composition_strategy` and `background_opacity` obviously vary for the above screenshots :)
```
kitty 0.28.1 created by Kovid Goyal
Linux spectre 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64
Arch Linux 6.2.12-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/josh/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.5
bell_path             /home/josh/.config/kitty/boom.wav
cursor_shape          2
font_family           CaskaydiaCove Nerd Font
font_size             12.0
strip_trailing_spaces smart
url_style             1
window_padding_width  FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
Added mouse actions:
	right click grabbed →  paste_from_selection
	right click ungrabbed →  paste_from_selection
Changed shortcuts:
	kitty_mod+enter →  new_os_window_with_cwd
	kitty_mod+n →  discard_event
Colors:
	color1                #cc231c   
	color10               #b8ba25   
	color11               #fabc2e   
	color12               #83a597   
	color13               #d3859a   
	color14               #8ec07b   
	color15               #ebdbb2   
	color2                #989719   
	color3                #d79920   
	color4                #448488   
	color5                #b16185   
	color6                #689d69   
	color7                #a89983   
	color8                #928373   
	color9                #fb4833   
	foreground            #ebdbb2   
	selection_background  #ebdbb2   
	selection_foreground  #655b53   
	url_color             #d65c0d   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-1
	USER                                josh
	XCURSOR_SIZE                        24
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_BACKEND                         wayland
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 Hyprland
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Additional context**
Using `kitty --config NONE` it looks fine, but I can't comment on the thickness of the text, but it might be a bit to thick. Also, when highlighting the text, dark text on light background is too thin.

**Comment by kovidgoyal** [comment]
read the discussion in #5969 and comment there is you wish further clarification

**Comment by kovidgoyal** [comment]
Oh and for fringing see #6209

**Comment by joshuajeschek** [comment]
thanks for the pointers! switching to the newest version (with #6209 implemented) fixed the fringing, and leaving `text_composition_strategy` on `legacy` is fine for me :)
