### ISSUE TITLE
Privilge Escalation in edit-in-kitty

### ISSUE THREAD

**Issue by Stetsed** [kovidgoyal/kitty#6227]
**Is your feature request related to a problem? Please describe.**
So currently I manage a few home servers, and what I quiet often come across is that I have to edit files on those servers or across my devices using SSH. Now usually I end up using nano as it's too cumbersome to copy my neovim config over and install everything on every server, instead of using edit-in-kitty as quiete often the files I need to edit require privilege escalation.

**Describe the solution you'd like**
I would like it so that edit-in-kitty if it notices a file cannot be edited by the current user will ask for privilege escalation.

**Describe alternatives you've considered**
There aren't any real alternatives to doing this that I have found I could use, so I hope you could introduce this feature into edit-in-kitty.

**Additional context**
I have looked at open issues with the words “edit-in-kitty” "privilege" "escalation" "sudo" "doas", and haven't found any. If this has been requested before I do apologize

**Comment by Stetsed** [comment]
Currenly edit-in-kitty will display "Error: X is not readable and writeable" if the file can be read but cannot be written to. And displays "Error: Failed to open X for reading with error: open X: permission denied" if it cannot be read.

**Comment by Stetsed** [comment]
I did realise I could create a fish script which would be aliased to smth like the "edit" command, and then have that check if the file is writeable by the current user and if not ask for privilge esc. But I hope this can be integrated nativley into kitty.

**Comment by kovidgoyal** [comment]
Run

sudo kitten edit-in-kitty whatever
