### ISSUE TITLE
Cannot set or list custom user themes

### ISSUE THREAD

**Issue by emacann** [kovidgoyal/kitty#6233]
**Describe the bug**
I have two custom themes, placed in $XDC_CONFIG_HOME/kitty/themes, named "solight.conf" and "sodark.conf".
Kitty is unable to set or list them using the builtin "kitty +kitten themes" option.
Themes have been created using [template.conf](https://raw.githubusercontent.com/kovidgoyal/kitty-themes/master/template.conf).

**To Reproduce**
1. Place a custom theme in $XDC_CONFIG_HOME/kitty/themes
2. Invoke `kitty +kitten themes`
3. Navigate to the "User" tab
4. No custom themes are listed - the only list item is "The name of the theme (if not present, derived from filename).

**Screenshots**
See attachment.

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin emacann-mac 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
ProductName:		macOS ProductVersion:		13.3.1 BuildVersion:		22E261
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/emacann/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style   (True, False)
bold_font               SF Mono Semibold
bold_italic_font        SF Mono Semibold Italic
confirm_os_window_close 0
cursor_blink_interval   0.0
font_family             SF Mono Regular
font_size               14.0
initial_window_height   (600, 'px')
initial_window_width    (960, 'px')
italic_font             SF Mono Regular Italic
remember_window_size    False
scrollback_lines        200000
tab_bar_style           separator
tab_separator           
tab_title_template        {title}  
Colors:
	active_tab_background   #fdf6e3   
	active_tab_foreground   #002b36   
	background              #fdf6e3   
	color0                  #073642   
	color1                  #dc322f   
	color10                 #586e75   
	color11                 #657b83   
	color12                 #839496   
	color13                 #6c71c4   
	color14                 #93a1a1   
	color15                 #fdf6e3   
	color2                  #859900   
	color3                  #b58900   
	color4                  #268bd2   
	color5                  #d33682   
	color6                  #2aa198   
	color7                  #eee8d5   
	color8                  #002b36   
	color9                  #cb4b16   
	cursor                  #657b83   
	cursor_text_color       #fdf6e3   
	foreground              #657b83   
	inactive_tab_background #859900   
	inactive_tab_foreground #002b36   
	selection_background    #93a1a1   
	selection_foreground    #fdf6e3   
	tab_bar_background      #859900   
	tab_bar_margin_color    #859900   
	url_color               #268bd2   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.1IaYGJGJtD/org.xquartz:0
	USER                                emacann
```

**Additional context**
The same issue seems to reproduce without user-specific configuration - command used:
```
kitty --config NONE +kitten themes
```

**Comment by kovidgoyal** [comment]
Does not reproduce for me, with the following steps:

1) kitten themes --dump-theme clrs > ~/.config/kitty/themes/clrs.conf
2) kitten themes --dump-theme abc > ~/.config/kitty/themes/abc.conf
3) kitten themes
4) go to user tab, the above two themes are listed as expected

You didnt provide your theme files, so I am guessing it is something in
them that the re-written themes kitten doesnt like. If you attach one of
them I can take a look.

**Comment by emacann** [comment]
Interesting. I have tried the "dump-theme" option with my files, and here is the output:

```
% kitten themes --dump-theme .config/kitty/themes/solight.conf
Error: No theme named: .config/kitty/themes/solight.conf
```

Please see the two themes attached.
[themes.zip](https://github.com/kovidgoyal/kitty/files/11381041/themes.zip)

**Comment by kovidgoyal** [comment]
You need to fill in the metadata block in your theme files. Currently
they both have the name "The name of the theme (if not present, derived from filename)"
which is the placeholder value from the template. Put in actual names
and you will be fine.
