### ISSUE TITLE
kitty window not selected by default when opened on gnome with wayland

### ISSUE THREAD

**Issue by OldWorldOrdr** [kovidgoyal/kitty#6234]
**To Reproduce**
1. select any text box in another window
2. without deselecting the text box, open kitty
3. start typing
4. text will be typed into the other window, instead of kitty

clicking on kitty or alt+tabbing to kitty will select the window, but its still annoying to not be able to just start typing

**Comment by kovidgoyal** [comment]
That is a regression in mutter, report it to them.
