### ISSUE TITLE
Build dependency list might be inclomplete (libcrypto / Linux)

### ISSUE THREAD

**Issue by Finii** [kovidgoyal/kitty#6238]
**Describe the bug**
Documentation on https://sw.kovidgoyal.net/kitty/build/ (maybe) not complete

**To Reproduce**
1. Use Ubuntu 22.10 (cough)
2. Install dependencies as mentioned in above documentation
3. `make debug`
4. `libcrypto` is reported missing

**Screenshots**
After I determined the missing package's name and installing/building I wanted to make sure it is really this package that was missing:

![image](https://user-images.githubusercontent.com/16012374/235882311-f2263a0a-14c0-4fbb-abbb-fe6815ef914e.png)

No build without it.

**Environment details**
not applicable

**Additional context**
not applicable

**Conclusion**

Just a suggestion to include `libssl-dev` in the list of Linux dependencies on the website.
It seems to be not pulled in through anything else. Could also be because `go` is now a Snap :vomiting_face: on Ubuntu, no clue.

**Comment by Finii** [comment]
Well, `bug` label is a bit harsh, but none of the report templates seemed to fit.

Btw, ligatures showing now :tada:

**Comment by kovidgoyal** [comment]
Yeah, I dont really keep the list of -dev deps up to date as I dont use Ubuntu myself. PRs are most welcome, in this case I guess it would be libcryto-dev?

**Comment by Finii** [comment]
No, `libssl-dev` (as, see screenshot above). Ubuntu seems to not have `libcrypto-dev`.

https://packages.ubuntu.com/search?mode=exactfilename&suite=kinetic&section=all&arch=any&keywords=libcrypto.pc&searchon=contents

![image](https://user-images.githubusercontent.com/16012374/235934279-c4372c9e-547b-48c7-a5b1-eb80e1f71187.png)

I would PR, but I do not know the repo if the webpage :grimacing:
