### ISSUE TITLE
Command to temporarily hide/close the Kitty window

### ISSUE THREAD

**Issue by Spiffyk** [kovidgoyal/kitty#6246]
I use Kitty as my primary (well, sole, really) terminal in a tiling WM (Sway). I have a use case in mind in which I would run a graphical program from the terminal, at which point Kitty would temporarily hide its window while the child program is running, and would show back up again when the child exits.

This would theoretically alleviate some of the pain from having to manually hide Kitty using a stacked/tabbed layout, and at the same time could allow the user to explore the program's output after exiting, which is not possible when running graphical programs via e.g. `dmenu`.

I would be willing to try my hand at exploring Kitty's sources and implementing the feature myself as well, if there would be interest in having it. My idea is that window hiding and showing could be exposed through the Remote control API and the actual automatic hiding during a child's runtime would be a kitten that does this.

**Comment by kovidgoyal** [comment]
Simply create a wrapper script that launches such programs. It can run
the program, hide the current OS Window whose id you can get from the
WINDOWID env var on X11 (no clue on wayland). And the wait for the
program you started to terminate, and restore the hidden window.
