### ISSUE TITLE
Weird behavior with fonts and colours when using neovim

### ISSUE THREAD

**Issue by cloudUser98** [kovidgoyal/kitty#6248]
Im having a weird behavior in wich my font looks totally different when using neovim. I use JetBrains Mono in both the Kitty terminal and Alacritty, i switched to Kitty because the font and the colors looked more vibrant and rich in the kitty terminal, but thats not the case when using neovim inside the terminal. When using neovim both the font and the colors looks totally different, the colors look faded and the font thiner.

Ive installed Kitty using the curl method and the already builded package from the Fedora repo to see if there was any difference, but sadly no.

Here are some screenshots from Kitty and Alacritty on my machine, both are using the same font and size with minimal configuration:
- Kitty
![image](https://user-images.githubusercontent.com/109044519/236599930-55495962-166d-4e3b-99de-f4c9512bedc4.png)

- Alacritty
![image](https://user-images.githubusercontent.com/109044519/236599977-b6e84d6a-16e5-411f-88f9-9398edfd8dc3.png)

In Neovim:
- Kitty
![image](https://user-images.githubusercontent.com/109044519/236600073-6d21b5bc-d964-434a-9503-7996de2ff39e.png)

- Alacritty
![image](https://user-images.githubusercontent.com/109044519/236600101-7972b264-8a98-49bd-a753-178c2f8af357.png)

Im running Kitty version 0.28.0 on Fedora 38

The only options from the config file that i edited are the next ones:

font_family JetBrains Mono Regular
bold_font JetBrains Mono Bold
font_size 16.0

**Comment by kovidgoyal** [comment]
The fonts and colors are exactly the same. The only difference is how
gamma correction is done when blending colors. Which in kitty you can
customize to your liking via text_composition_strategy in kitty.conf.
