### ISSUE TITLE
mouse click to set cursor position for bash read

### ISSUE THREAD

**Issue by gknittl** [kovidgoyal/kitty#6260]
bash read -e creates an input line that supports cursor movement by the left, right, home, end keys and perhaps others. In a kitty terminal ,mouse clicks do not reset the cursor position in a read input line. To recreate type read -ei 'kitty is great' and try to move the cursor by clicking somewhere in the string.  

I realize that read may be the code that has to support the mouse click, but just asking in case there is a simple way that kitty can support this.

**Comment by kovidgoyal** [comment]
No, there is no way for kitty to support this. You would need to
implement shell integration for readline.
