### ISSUE TITLE
Update Python to 3.11

### ISSUE THREAD

**Issue by pooh2pooh** [kovidgoyal/kitty#6262]
with the Arch Linux update, the system version of python became 3.11 and now kitty does not start with an error:
`kitty: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

**Comment by kovidgoyal** [comment]
The official kitty binaries include their own copy of python, they dont
depend on the system python. You are presumbly using someth build other
than the official binaries. Rebuild.

**Comment by AstroBarker** [comment]
The same has happened to me, even after reinstalling kitty
