### ISSUE TITLE
Cursor is not centred in kitty

### ISSUE THREAD

**Issue by NotQuiteAwake** [kovidgoyal/kitty#6263]
**Describe the bug**
When kitty is launched the cursor is displaced and extends below the current line. I wasn't able to reproduce this on another machine of a similar setup (arch i3), and it also doesn't happen when I use another terminal emulator (alacritty). Thanks for your time.

**To Reproduce**
Install kitty

**Screenshots**
![1683806884](https://github.com/kovidgoyal/kitty/assets/11169901/1f055674-59ab-49bc-8382-75c5438c3d83)
![1683806675](https://github.com/kovidgoyal/kitty/assets/11169901/221f7cb8-dc46-4639-8a36-a51e358a3ebd)

**Environment details**
```
kitty 0.28.1 created by Kovid Goyal
Linux jimmy-mbp 6.1.27-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 18:18:27 +0000 x86_64
Arch Linux 6.1.27-1-lts (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/jimmy/.config/kitty/kitty.conf

Config options different from defaults:
font_size 18.0

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/jimmy/.local/bin
	LANG                                en_GB.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                jimmy
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    tty
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Additional context**
I can reproduce this with no config and on a different WM (Sway).

**Comment by justinbalaguer** [comment]
for those having the same issue with this, in your kitty try changing the font as well similar to what youre setting up on your machine

**Comment by NotQuiteAwake** [comment]
Hey, sorry for the late reply. It was indeed a font issue. I didn't set up my font properly on my machine and x11 resolved monospace font to the problematic "Nimbus Mono PS" which was pulled in by the `gsfonts` package.

I resolved the issue by blacklisting the Nimbus family fonts with a file at `~/.config/fontconfig/conf.d/99-no-nimbus.conf`:

```
<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <selectfont>
        <rejectfont>
            <glob>/usr/share/fonts/gsfonts/Nimbus*</glob>
        </rejectfont>	
    </selectfont>
</fontconfig>
```
