### ISSUE TITLE
lookaround/lookbehind regex that used to work not working anymore

### ISSUE THREAD

**Issue by Artturin** [kovidgoyal/kitty#6265]
**Describe the bug**

```
Error: Failed to compile the regex pattern: "(?<=got.....)sha256.{45}" with error: error parsing regexp: invalid or unsupported Perl syntax: `(?<`
```

**To Reproduce**
1. run `echo "got:    sha256-L8wivKxb5OWfbnU/7Rs6GzecDLOCxAsukoO2Qj7egfU=" | kitten hints --program @ --type regex --regex '(?<=got.....)sha256.{45}'`

https://regex101.com/r/ieCHXq/1 shows that it should work with PCRE/2, if golang is chosen from the flavors then it fails so it looks like its not supported in go regexp :(

kitty 5b8b91b6a3be6d4cede7062367f97a9a13f80086

**Comment by kovidgoyal** [comment]
The regex engine was changed to the one native to Go which doesnt
support these for performance reasons, IIRC.

**Comment by kovidgoyal** [comment]
Note that go has a regexp2 library that supports these, it should be a relatively simply patch to use that instead of the stdlib one to add support. I dont have much motivation for this, but PR is welcome.

**Comment by kovidgoyal** [comment]
You can also use the custom processing to do your matching in python using the python regex engine, without needing any patches.

**Comment by kovidgoyal** [comment]
Actually in your case you dont need the look behind at all. If the regex contains a single unnamed group the match will be just that groups contents. So you can use 
```
got.*?sha256(.{45})
```

**Comment by Artturin** [comment]
> Actually in your case you dont need the look behind at all. If the regex contains a single unnamed group the match will be just that groups contents. So you can use
> 
> ```
> got.*?sha256(.{45})
> ```

correct regex would be
`got.*?(sha256.{45})`

**Comment by Artturin** [comment]
Thanks for 65f8bb7.

You're awesome and one of the best open source developers!
