### ISSUE TITLE
padding left + right changes when opening/closing split window

### ISSUE THREAD

**Issue by marcoSven** [kovidgoyal/kitty#6273]
**Describe the bug**
When I open a split window the side padding changes and results in a content shift.

Looking at the second video with minimal configs you can see that it does not matter if the split is opened horizontally or vertically.

**To Reproduce**
```
window_padding_width 8 15 0 15
enabled_layouts horizontal

placement_strategy center

hide_window_decorations titlebar-only
remember_window_size  no
```

1. map new_window
2. map close_window_with_confirmation ignore-shell

**Screenshots**
Note the left padding 

https://github.com/kovidgoyal/kitty/assets/3860298/f31dbc48-1599-4d7f-893c-7afeb6ad2b44

removed all configs except mappings

https://github.com/kovidgoyal/kitty/assets/3860298/8a3cb9f9-6e20-4a87-b8e8-b757115bab31

 

**Environment details**
```
kitty 0.28.0 (b81f457e9b) created by Kovid Goyal
Darwin ms.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		13.1 BuildVersion:		22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/marcosven/.config/kitty/kitty.conf

Config options different from defaults:
Added shortcuts:
	
Removed shortcuts:

Changed shortcuts:


Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
The padding is a function of the extra pixels leftover when the window
size is not an exact multiple of the cell size. Creating splits will
change that number. It is unavoidable.

**Comment by marcoSven** [comment]
> It is unavoidable.

I hear you, just wondering why this does not appear to be an issue for WezTerm.
Also wondering why the x padding changes when performing a horizontal split.

**Comment by kovidgoyal** [comment]
On Wed, May 17, 2023 at 02:03:05PM -0700, marcoSven wrote:
> > It is unavoidable.
> 
> I hear you, just wondering why this does not appear to be an issue for WezTerm.

It is an issue there as well, you just haven't run across a combination
of window and font sizes that triggers it.

> Also wondering why the x padding changes when performing a horizontal split. 

Because the layout changes, with a single window the layout is
maximized, with multiple windows space must be reserved for borders/real
padding/margins.

**Comment by marcoSven** [comment]
Thank you for explaining.
