### ISSUE TITLE
Complete kitty.conf file

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#628]
Where can I find the lastest, complete, kitty.conf file?
I've just updated to the latest version (0.11.0) and some shortcuts aren't working anymore.

**Comment by maximbaz** [comment]
This one I think: https://sw.kovidgoyal.net/kitty/conf.html#sample-kitty-conf

**Comment by mihaicristiantanase** [comment]
Thanks, but I saw that one and it's missing a lot of keys.

**Comment by kovidgoyal** [comment]
Those are all the defaults, that sample is generated from the default config in the kitty source code. What keys are you missing?

**Comment by mihaicristiantanase** [comment]
Actually, I've rechecked the sample and all the keys are there (I initially didn't see the keyboard shortcuts for font section).
Unfortunately, the change font size keys are not working. I'll create a separate issue for this.

**Comment by blueyed** [comment]
btw: https://github.com/kovidgoyal/kitty/pull/644 improves generation of the default conf.
Running `make docs` should give you `docs/generated/conf/kitty.conf` then, which is easy for diffing against your current config.

**Comment by melMass** [comment]
This should be more obvious to find I think.
I have been using kitty for something like a year, and some config names changed or where added. It would be nice to quickly be able to check which! 

Thanks a lot, @kovidgoyal, for your hard work!

**Comment by blueyed** [comment]
@melMass 
See https://github.com/kovidgoyal/kitty/pull/644#issuecomment-397824997
IIRC it is mentioned in docs also, but consider improving it, of course.

**Comment by wookayin** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#sample-kitty-conf is a webpage, not a plain file. I would like to have a plain complete `kitty.conf` file printed (which is auto-generated from https://github.com/kovidgoyal/kitty/blob/master/kitty/options/definition.py). Is there any CLI that can do this?

**Comment by wookayin** [comment]
@Luflosi Thanks, I missed the link below. I can download from the link (although the URL contains specific SHA1 hash code)
`gen-config.py` is something I can run to generate kitty.conf file, but not from the `kitty` CLI. Probably I'll need to clone the repository and run them. Thanks!

**Comment by page-down** [comment]
@wookayin 

Please check out the 644 issue comment mentioned above.
You don't even need to use cli, just rename the existing `~/.config/kitty/kitty.conf`, run kitty and use the edit config default shortcut `ctrl+shift+f2` (macOS: `command+,` ) to immediately create a current version of `kitty.conf`.

It can also be generated using the cli without pulling the source code repository.

```shell
kitty +runpy "from kitty.config import commented_out_default_config; open('kitty.conf', 'w', encoding='utf-8').write(commented_out_default_config());"
```

**Comment by wookayin** [comment]
@page-down Thanks, that's really a great tip. In short, the following would be what I wanted (based on your CLI), which prints the default complete kitty.conf into stdout.

```bash
kitty +runpy "from kitty.config import commented_out_default_config as conf; print(conf());"
```

**Comment by ershov** [comment]
Hi,
This can be helpful to find out all available config options and actions: https://github.com/ershov/kitty_config

<img src="https://user-images.githubusercontent.com/449936/247107031-95625fea-0533-4312-bbd6-caf47479990f.png">

<img src="https://user-images.githubusercontent.com/449936/247107180-b2416091-8eb1-40cd-90a1-8052ce7bbbf8.png">
