### ISSUE TITLE
E558: Terminal entry not found in terminfo

### ISSUE THREAD

**Issue by jsphnecclia** [kovidgoyal/kitty#6282]
Hi. Im running macOS Ventura 13.0.1 on a M1 Pro. 

While running vim as a normal user works, when I try to run vim under sudo I get the error:

```
E558: Terminal entry not found in terminfo
'xterm-kitty' not known. Available builtin terminals are:
    builtin_ansi
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_pcansi
    builtin_win32
    builtin_amiga
    builtin_dumb
    builtin_debug
defaulting to 'ansi'
```

I haven't been able to find any relevant information online. This is not a problem related to ssh, echo $TERMINFO gives /Applications/kitty.app/Contents/Resources/kitty/terminfo, regardless of normal user or sudo, and similarly xterm-kitty with $TERM. 

Replacing TERM=xterm-256color works. But I don't think that is the right answer. 

Thanks!

**Comment by kovidgoyal** [comment]
Search the kitty FAQ for sudo

**Comment by jsphnecclia** [comment]
I have read that section, and went through it again now. None of those solutions work for me.

As I said earlier:

- This is not a problem related to ssh,
- echo $TERMINFO gives /Applications/kitty.app/Contents/Resources/kitty/terminfo for both sudo and normal user,
- similarly as above xterm-kitty is $TERM.
- sudo TERMINFO="$TERMINFO" -s -H gives a new shell, but the error persists

Thank you!

**Comment by kovidgoyal** [comment]
Then whatever program you are running under sudo is not respecting the
TERMINFO env var. Report the bug to that program's developers. You can
always install terminfo system-wide to get around it.

**Comment by jsphnecclia** [comment]
terminfo is installed system-wide. (sudo echo $TERM returns xterm-kitty)

the program in question is vim...

**Comment by kovidgoyal** [comment]
The report the issue to the vim developers.

**Comment by leleliu008** [comment]
@jsphnecclia 

```bash
TERM=kitty sudo /home/leleliu008/bin/vim /etc/hosts
```

Reference: https://vimhelp.org/term.txt.html#xterm-kitty

**Comment by jsphnecclia** [comment]
> @jsphnecclia
> 
> ```shell
> TERM=kitty sudo /home/leleliu008/bin/vim /etc/hosts
> ```
> 
> Reference: https://vimhelp.org/term.txt.html#xterm-kitty

Thank you! But how did you arrive at this command? I don't understand how the reference linked informs the solution

**Comment by leleliu008** [comment]
If you don't understand exactly what the document wrote,  `Linus Torvalds` said `read the fucking source code`

https://github.com/vim/vim/blob/master/src/os_unix.c#L2429-L2449
https://github.com/vim/vim/blob/master/src/term.c

**Comment by bobbykjack** [comment]
@jsphnecclia I don't have a *deep* understanding of this issue, but the following seems to have fixed it for me!

https://robot.unipv.it/toolleeo/2021/09/xterm-kitty-unknown-terminal-type/
