### ISSUE TITLE
vi mode cursor_shape faulty in kitty, not in iterm or mac terminal (shell_integration no-cursor not working)

### ISSUE THREAD

**Issue by tjex** [kovidgoyal/kitty#6288]
**Describe the bug**
kitty.conf:
```
shell_integration no-cursor
```
I'm using https://github.com/jeffreytse/zsh-vi-mode for vi mode. Underline for insert mode, block for normal mode.

Kitty starts up with underline (expected). Exit to normal mode shows block (expected). Re-entering to insert mode -> the cursor is beam, not underline (unexpected). 

This _only_ happens in kitty. I've tested in iterm and mac terminal and they work as expected (returning to underline when entering insert mode)

I also tried:
```
shell_integration no-cursor
cursor_shape underline
```

When the shell prompt executes / exits to a subsequent prompt, it displays the underline cursor correctly - even if the cursor was a beam previously. 

Here is a video of the bug via asciinema (using words to describe the cursor shape as asciinema doesnt show cursor shape): https://asciinema.org/a/7Q9azDdwcMNF27VbH97F6BeIK

**To Reproduce**
1. install https://github.com/jeffreytse/zsh-vi-mode
2. set vi insert mode cursor to underline `ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE`
3. exit / enter insert mode

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin n136-p141.eduroam.kth.se 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64
ProductName:    macOS ProductVersion:   12.6.1 BuildVersion:    21G217
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/tillman/.config/kitty/kitty.conf

Config options different from defaults:
cursor_blink_interval   0.5
cursor_shape            3
font_family             Fura Nerd Font Mono Regular
font_size               13.0
hide_window_decorations 1
inactive_text_alpha     0.7
initial_window_height   (98, 'cells')
initial_window_width    (140, 'cells')
modify_font:
    cell_height 4
resize_draw_strategy    3
scrollback_lines        100000
shell_integration       frozenset({'no-cursor'})
tab_bar_style           slant
window_margin_width     FloatEdges(left=6.0, top=6.0, right=6.0, bottom=6.0)
window_padding_width    FloatEdges(left=8.0, top=8.0, right=8.0, bottom=8.0)
Added shortcuts:
        ctrl+down →  move_window down
        ctrl+left →  move_window left
        ctrl+right →  move_window right
        ctrl+up →  move_window up
        opt+h →  previous_window
        opt+l →  next_window
Changed shortcuts:
        cmd+t →  launch --cwd=~/t-root --type=tab
Colors:
        active_border_color     #2c2c53   
        active_tab_background   #576a71   
        active_tab_foreground   #1f2335   
        background              #171a27   
        color0                  #181a24   
        color1                  #e95454   
        color10                 #8fbd5d   
        color11                 #cf9f5f   
        color12                 #6d90e4   
        color13                 #a58de4   
        color14                 #6cbde7   
        color15                 #b5bdcf   
```

**Additional context**
I'm on M1 mac os 12.6 
The problem persists with `kitty --config NONE`

**Comment by tjex** [comment]
maybe a hint? I just noticed that the first unbroken string in a prompt in kitty is using a different font than subsequent strings.

Kitty:
<img width="141" alt="Screen Shot 2023-05-19 at 15 58 10" src="https://github.com/kovidgoyal/kitty/assets/83029642/74fb2618-ccb3-4de2-9791-e4b3b5424a43">

mac Terminal (same font for first and second string): 
<img width="189" alt="Screen Shot 2023-05-19 at 16 00 47" src="https://github.com/kovidgoyal/kitty/assets/83029642/dbc927ee-bca9-4a4e-90e6-f099295a61a7">

**Comment by kovidgoyal** [comment]
Dont use zsh-vi-mode. kitty already sets the cursor according to vi mode
in zsh out of the box. As for debugging why zsh-vi-mode doesnt work, I
dont have the time/interest to do that.

**Comment by tjex** [comment]
Bit confused. I don't use zsh-vi-mode just to set cursor shapes. And I tried disabling setting the cursor shape via zsh-vi-mode settings. No change.
But I noticed now that the whole issue doesn't occur within tmux. And that's where I spend all my time really. So no worries.
