### ISSUE TITLE
Allow mouse selections during buffer updates

### ISSUE THREAD

**Issue by TheJJ** [kovidgoyal/kitty#629]
When the terminal buffer is updated (i.e. new data arrives) it is not possible to perform mouse text selections.

The selection is cleared right after new content arrives, but this should not matter e.g. when one scrolled back some lines and selects something there. When the output does not add new lines, but displays a rotating star with `\\r` `|\r` `/\r` `-\r` (the `emerge` dependency-calculation-spinner, for example), the terminal does not scroll at all, but it's still impossible to perform a selection.

(tested with `kitty-0.10.1` on Gentoo)

**Comment by kovidgoyal** [comment]
dup of #148
