### ISSUE TITLE
Add RISC-V nightly builds

### ISSUE THREAD

**Issue by Slackadays** [kovidgoyal/kitty#6290]
**Is your feature request related to a problem? Please describe.**
I'm trying to compile the latest Kitty version for my VisionFive 2 RISC-V board and I have to compile the entirety of golang because Debian's kitty version is super outdated and they only have go 1.19 prebuilt.

**Describe the solution you'd like**
Add RISC-V nightly builds along with the other arches for Linux

**Describe alternatives you've considered**
Compile Kitty for RISC-V manually

**Additional context**
RISC-V is becoming more popular more quickly than ever and soon it's going to be necessary to add nightly builds for this anyway.

**Comment by kovidgoyal** [comment]
I'm afraid doing that is rather more effort than its worth to me, sorry.
I am unfamiliar with RISC-V and its tooling.
