### ISSUE TITLE
Visually Identifying Windows

### ISSUE THREAD

**Issue by alreadytold** [kovidgoyal/kitty#6295]
**Is your feature request related to a problem? Please describe.**

Should it be possible to visually discriminate between windows? Having two kitty terminal windows open, how to distinguish between the two of them?

For example having two nearly identical buffers open, using one as a reference to modify the other, I'd like to be careful not to mistake one for the other.

Can kitty terminal windows be marked in some way?

I tried to do this with vim splits, and the only thing that immediately occurred to me was to bookmark the split that was acting as the reference buffer. I also received a suggestion to change the colorscheme. Can you think of another way?

**Describe the solution you'd like**
To be able to visually discriminate between independent instances of the kitty terminal.

**Describe alternatives you've considered**
Just using vim splits and creating bookmarks to indicate which is the reference buffer.

**Additional context**

**Comment by kovidgoyal** [comment]
Use remote control or a key binding to change colors or margins or
padding or title or opacity for the window of interest.
