### ISSUE TITLE
Ligatures apply to strings that are cut in half by a line-wrap (is misleading)

### ISSUE THREAD

**Issue by jfaure** [kovidgoyal/kitty#6297]
**To Reproduce**
1. enter spaces until last column is reached
2. enter <|> such that |> appears on a newline: the |> ligature then applies

**Context**
font_family JetBrains Mono
disable_ligatures never

**Comment by kovidgoyal** [comment]
Ligatures apply to any characters that the font says they apply to.
Rendering is done per line, so ligatures cannot apply across line
boundaries. That is simply a limitation of rendering per line, and
rendering per line is not going to change, for performance reasons.
