### ISSUE TITLE
Different font for tabs (smaller)

### ISSUE THREAD

**Issue by oernii** [kovidgoyal/kitty#6298]
**Is your feature request related to a problem? Please describe.**
Would it be possible to have a different/smaller font for TABs? I have sessions with a lot of tabs and tabs are unreadable. In other terminals I can change the tab font size.

**Describe the solution you'd like**
Smaller font for tabs

**Describe alternatives you've considered**
Alternatives are only different apps, like konsole, gnome-terminal

**Comment by kovidgoyal** [comment]
No given the way that tabs are implemented it is not possible. They are
drawn in the same font and the same way as the rest of kitty.
