### ISSUE TITLE
`kitty -1` detaches from a terminal

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#630]
i dont know know if this is intended and i cant recall this behaviour before.

**Comment by kovidgoyal** [comment]
kitty -1 will open a new window in  a previous instance of kitty -1, and exit.

If there is no previous instance, then it will run and not detach. That is still the case and has always been the case.

**Comment by SolitudeSF** [comment]
is there a way then to wait for exit of the instance launched with `-1`?

**Comment by kovidgoyal** [comment]
There is no instance launched with kitty -1, it's just a window in an existing instance. So no, there is no way to wait for that window to close.

**Comment by SolitudeSF** [comment]
ok, thanks for the info. i guess i can botch some workaround for my usecase.

**Comment by kovidgoyal** [comment]
What is your usecase?

**Comment by SolitudeSF** [comment]
script for editing clipboard in the terminal editor.

**Comment by kovidgoyal** [comment]
I need a little more detail than that. Why do you want kitty -1 to hang around until the window is closed? If it is in a terminal editor, why not just use a terminal mode program directly rather than a new GUI window?

**Comment by SolitudeSF** [comment]
its for invoking from outside the terminal.

**Comment by SolitudeSF** [comment]
wow, thank you
