### ISSUE TITLE
kitty +kitten panel crashes

### ISSUE THREAD

**Issue by peterwu** [kovidgoyal/kitty#6303]
**Describe the bug**
The example kitten panel code crashes

**To Reproduce**
1. run the example code `kitty +kitten panel sh -c 'printf "\n\n\nHello, world."; sleep 5s'` from https://sw.kovidgoyal.net/kitty/kitten
2. program crashes with the following error
```
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Atom id in failed request:  0x0
  Serial number of failed request:  297
  Current serial number in output stream:  299
```

**Additional context**
kitty 0.28.1 on Fedora 38

**Comment by kovidgoyal** [comment]
Works for me. Note this is only likely to work under X11 not XWayland.
And it auto exits after 5 seconds. Change the sleep there.

**Comment by peterwu** [comment]
I'm on x11 running herbstluftwm. 

Changing the sleep doesn't help. Let me know how I can help collect troubleshooting information here.

**Comment by kovidgoyal** [comment]
Then it will be because the window manager you are using doesnt support either setting either NET_WM_WINDOW_TYPE or NET_WM_STRUT_PARTIAL
