### ISSUE TITLE
Permission denied kitty +kitten themes

### ISSUE THREAD

**Issue by codePassion-dot** [kovidgoyal/kitty#6305]
**Describe the bug**
can't set a theme using kitty +kitten themes interactive session nor the non-interactive shell command 

**To Reproduce**
1. kitten +kitten themes
2. choose a theme and press m
3. nothing happens

1. kitty +kitten themes --reload-in=all Dimmed Monokai
2. Error: open /etc/xdg/kitty/current-theme.conf.atomic-write-81092104: permission denied 

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/63831898/f2ebf326-ab95-42af-bfb3-fb0205210838)

**Environment details**
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Linux pop-os 6.2.6-76060206-generic #202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M x86_64
Pop!_OS 22.04 LTS pop-os /dev/tty

DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/jacobo/.local/stow/kitty.app/bin/kitty
  base dir: /home/jacobo/.local/stow/kitty.app/lib/kitty
  extensions dir: /home/jacobo/.local/stow/kitty.app/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/jacobo/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    yes
background_tint         0.6
clipboard_control       ('write-clipboard', 'write-primary')
confirm_os_window_close 0
font_family             DankMono Nerd Font Mono
font_size               24.0
listen_on               unix:@mykitty
modify_font:
    cell_height 0
    cell_width 0
tab_title_template      {title}
url_prefixes            ('http', 'https', 'file', 'ftp')
Changed shortcuts:
	kitty_mod+e →  kitten hints

Important environment variables seen by the kitty process:
	PATH                                /home/jacobo/.cargo/bin:/home/jacobo/.local/bin:/home/jacobo/.yarn/bin:/home/jacobo/.local/bin:/home/jacobo/.local/share/bob/nvim-bin:/home/jacobo/.config/rofi/bin:/home/jacobo/Android/Sdk/emulator:/home/jacobo/Android/Sdk/platform-tools:/home/jacobo/.fly/bin:/home/jacobo/.deno/bin:/home/jacobo/go/bin:/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/cuda/bin:/home/jacobo/.local/share/JetBrains/Toolbox/scripts
	LANG                                en_US.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/zsh
	DISPLAY                             :1
	USER                                jacobo
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_MENU_PREFIX                     gnome-
	XDG_CURRENT_DESKTOP                 pop:GNOME
	XDG_SESSION_DESKTOP                 pop
	XDG_DATA_DIRS                       /usr/share/pop:/usr/share/gnome:/home/jacobo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-pop:/etc/xdg

**Additional context**

**Comment by kovidgoyal** [comment]
Create a user writeable kitty.conf in ~/.config/kitty it can be the
empty file and you will be fine.

**Comment by codePassion-dot** [comment]
I have my own config there:
![image](https://github.com/kovidgoyal/kitty/assets/63831898/9a22fd82-2ad9-4676-8a24-e9cecade1df9)
I removed the symlink of my personal config and create an empty file as you said and I'm still experiencing the issue. I think it's related with the /etc/xdg/kitty folder

**Comment by kovidgoyal** [comment]
The only way the kitten can be using /etc/xdg/kitty as the config directory is if it is in the XDG_CONFIG_HOME env var or if XDG_CONFIG_HOME is empty and it is in XDG_CONFIG_DIRS. In any case set KITTY_CONFIG_DIRECTORY=~/.config/kitty which will avoid all detection and just use ~/.config/kitty always

**Comment by codePassion-dot** [comment]
Yep I'm on the second case:

> if XDG_CONFIG_HOME is empty and it is in XDG_CONFIG

after setting that env variable I'm getting this error:
![image](https://github.com/kovidgoyal/kitty/assets/63831898/d7dbd97e-3d5e-4577-abdb-5a8558bf0ff6)

(thank you so much for the quick response btw, kitty is really great)

**Comment by codePassion-dot** [comment]
Nevermind I wasn't setting the path correctly, all working :+1:
