### ISSUE TITLE
I disabled window decorations, but I can't make window operations anymore.

### ISSUE THREAD

**Issue by shebangcode** [kovidgoyal/kitty#6312]
Hey, I've encountered a problem where I've disabled window decorations, but I can't resize or move the window anymore.

1. Open the ~/.config/kitty/kitty.conf file
2. Add the following line:
`hide_window_decorations yes`
3. Save the file and quit the editor
4. Relaunch kitty and see that you can't resize the window or move it

**Comment by kovidgoyal** [comment]
Yes, that's what window decorations are for, moving and resizing
windows. If you disable them you can do those things anymore.

**Comment by shebangcode** [comment]
Oh, I see, thanks!

**Comment by kovidgoyal** [comment]
Note that some window managers have alternate ways of doing these operations like holding the windows key and clicking and dragging. Consult the docs of your window manager.

**Comment by shebangcode** [comment]
Ok, I'll look into that.
