### ISSUE TITLE
Feature requests: Name OS windows and Move window to target OS window

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#6313]
It would be great if 'set_tab_title' and 'tab_title_template' got extended to OS windows (aka, 'set_os_window_title' and 'os_window_title_template')

It would also be great if the `detach_tab` picker showed all other OS windows with `New tab in OS window`

Thanks for the good work!

**Comment by kovidgoyal** [comment]
detach_tab already does that. And you can name OS windows using --name
and --class (although to be fair detach_tab does not show this data in
the picker), it lists OS window by the title of the currently active
tab in each OS Window.

As for having a separate template for naming OS windows, I dont see much
point given they can have name and class.

**Comment by hacker-DOM** [comment]
I guess what I'm after is an interactive way to name windows like 'set_tab_title'. Is that possible with the current Api?

**Comment by kovidgoyal** [comment]
Run the kitty shell (ctrl+shift+escape by default) and run the command

set-window-title --match id:win_id my window title

win_id here will be output at the top of the kitty shell which shows you
the id of the previously active window before the kitty shell was
started. Or you can use the ls command to find the id for some other
window.

**Comment by kovidgoyal** [comment]
Or use --match recent:1 for the previously active window no need to even read the id.

**Comment by kovidgoyal** [comment]
--name and --class dont set titles. Titles are set per window. I dont know of any use case where you would want the OS window title to be different from the title of the kitty window inside it. The only one I can think of is matching on OS Windows in some window manager rule, and that is precisely what --name and --class are for.

**Comment by hacker-DOM** [comment]
Tab titles are unfortunately not overriding window titles in my kitty instance (for the purposes of OS naming and MacOS tab title bar), it's probably a bug, but I don't have time to report it

My current workaround is:

```zsh
function dom_kitty_set_os_window_title() {
    for win_id in kitty @ ls | ~/bin/sync/py/kitty_ls_to_windows_in_current_os_window.py; do
	echo "Setting id:$win_id window.title -> $1"
	kitty @ set-window-title -m id:$win_id $1
    done
}

# Use as `ksos {new-os-window-title}`
alias ksos=dom_kitty_set_os_window_title
```

```python
#!/usr/bin/env python3
import json, sys

def main():
    # Read the JSON array from stdin
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        sys.exit(1)

    # Iterate over each element in the array
    for element in data:
        if "tabs" in element:
            # For each tab in the tabs list
            for tab in element["tabs"]:
                if "windows" in tab:
                    # For each window in the windows list
                    for window in tab["windows"]:
                        if "id" in window:
                            # Print the window id
                            print(window["id"])

if __name__ == '__main__':
    main()
```



^ sets the kitty window title for all kitty windows in current OS window

> map cmd+t launch --type=tab --title=current
> map cmd+enter launch --title=current


^ basically whenever I create new windows, it copies the name

By induction, the name will be the same everywhere □

**Comment by hacker-DOM** [comment]
> I dont know of any use case where you would want the OS window title to be different from the title of the kitty window inside it.

The use case is the following:

I have many monitors.
->  I like to move things around often.
->  I have many kitty OS windows.
On MacOS, window management is broken.
->  I cannot implement a good last-window-in-current-app switcher in Hammerspoon.
->  I have to use Contexts, where it somehow works.
->  Contexts does not allow me to override OS window titles, so I'm at the mercy of applications.
I'd like to have my 4-5 kitty OS windows have names like the monitor they're on and the project they're working on.
->  I'd love the ability to change OS window title in KiTTY

I'm guessing other peoples' use cases are similar

**Comment by kovidgoyal** [comment]
On Thu, Oct 03, 2024 at 07:55:08PM -0700, Dom wrote:
> Tab titles are unfortunately not overriding window titles in my kitty instance (for the purposes of OS naming and MacOS tab title bar), it's probably a bug, but I don't have time to report it

What makes you think tab titles are supposed to override window titles?
And if you dont have time to report bugs, why do you imagine I have time
to keep repeating the same things to you? Good luck.

**Comment by kovidgoyal** [comment]
On Thu, Oct 03, 2024 at 08:13:54PM -0700, Dom wrote:
> > I dont know of any use case where you would want the OS window title to be different from the title of the kitty window inside it.
>
> The use case is the following:
>
> I have many monitors.
> ->  I like to move things around often.
> ->  I have many kitty OS windows.
> On MacOS, window management is broken.
> ->  I cannot implement a good last-window-in-current-app switcher in Hammerspoon.
> ->  I have to use Contexts, where it somehow works.
> ->  Contexts does not allow me to override OS window titles, so I'm at the mercy of applications.
> I'd like to have my 4-5 kitty OS windows have names like the monitor they're on and the project they're working on.
> ->  I'd love the ability to change OS window title in KiTTY
>
> I'm guessing other peoples' use cases are similar

So your issue is macos window management is broken, maybe report that to
Apple and get them to fix it.

**Comment by hacker-DOM** [comment]
> So your issue is macos window management is broken, maybe report that to
Apple and get them to fix it.

"Broken" is a subjective issue. Apple would say it's just not part of the spec ((and it's up to app devs to add support..))

**Comment by hacker-DOM** [comment]
> What makes you think tab titles are supposed to override window titles? And if you dont have time to report bugs, why do you imagine I have time to keep repeating the same things to you? Good luck.

Several discussions, eg:

[this one](https://github.com/kovidgoyal/kitty/discussions/6317#discussioncomment-6050679)

>> On Wed, May 31, 2023 at 06:12:10AM -0700, Jens Dahl Møllerhøj wrote:
>> As far as I can tell, there is no remote control command to set the os window title. `set-window-title` sets the window title, but it is overwritten by tab titles (That is, it does not set the OS window title / id)

> There is set-tab0title as well. If you use tabs then use that.

[this one](https://github.com/kovidgoyal/kitty/discussions/6317#discussioncomment-6077773)

> The OS window title is whatever the title of the active tab is.

**Comment by hacker-DOM** [comment]
> Apple would say it's just not part of the spec

They would say it's up to me to ask the application developer to add this feature 🤷

**Comment by kovidgoyal** [comment]
On Thu, Oct 03, 2024 at 10:44:13PM -0700, Dom wrote:
> > So your issue is macos window management is broken, maybe report that to
> Apple and get them to fix it.
>
> "Broken" is a subjective issue. Apple would say it's just not part of the spec ((and it's up to app devs to add support..))

And I say that I would rather not spend time implementing a feature that
is only needed for a niche usecase on a single platform. And
incidentally nowhere in Apple's HIG does it mention that OS window
titles are something that should be under user control in order to work
around limitations of their window manager.

But feel free to submit a PR adding a os_window_title_template setting
to kitty modeled along the lines of tab_title_template.

**Comment by hacker-DOM** [comment]
> > you can name OS windows using --name
> > and --class
> 
> It seems this is only possible with the `kitty` cli or the `launch` command. It would be great if I didn't have to restart an OS window just to change the title


actually changing os window title is possible after the (os) jxwindow is launched!

<details>
<summary>Code</summary>

~/.config/kitty/kittens/set_os_window_title.py:

```python
from kitty.boss import Boss
from kitty.fast_data_types import set_os_window_title
from kittens.tui.handler import result_handler

from kittens.tui.loop import debug

def main(args: List[str]):
    pass

@result_handler(no_ui=True)
def handle_result(args: list[str], _answer: str, target_window_id: int, boss: Boss):
    j_current_kwin = boss.window_id_map[target_window_id]
    # args[0]  is  the path to the kitten (kittens/set_os_window_title.py)
    set_os_window_title(j_current_kwin.os_window_id, args[1])
```

I think the easiest way to run it is from the kitty shell

```
🐱 kitten kittens/set_os_window_title.py foo
```

or a regular shell:

~/.zshrc:

```zsh
function dom_kitty_set_os_window_title() {
    kitty @ kitten kittens/set_os_window_title.py "$1"
}

# Use as `ksos {new-os-window-title}`
alias ksos=dom_kitty_set_os_window_title

</details>

Now it's an even smaller step to also add this to a mappable_action / remote-control-action :) 🙏 @kovidgoyal

**Comment by kovidgoyal** [comment]
You can already map any remote control command to an action using the remote_control action.

**Comment by hacker-DOM** [comment]
Yup, and you can also run any _mappable_action_ using the _action___ command (to go the other way)

The issue is, my desired feature is missing from both.

We currently have actions __set_window_title__ (`window` by itself in _kitty_ project means _kitty window_ and __set_tab_title__. We also have commands __set-window-title__ and __set-tab-title__. But for os windows, there is an "in-app purchase" where you have to invest time to create the above script. Since this keeps coming up over and over, I suggest completing the featureness and adding __set-os-window-title__ (and ideally __set_os_window_title__).

**Comment by kovidgoyal** [comment]
It keeps coming over and over because *you* keep bringing it up over and
over. My opinion on the usefulness of such a feature remains unchanged.

**Comment by hacker-DOM** [comment]
> > > you can name OS windows using --name
> > > and --class
> > 
> > 
> > It seems this is only possible with the `kitty` cli or the `launch` command. It would be great if I didn't have to restart an OS window just to change the title
> 
> actually changing os window title is possible after the (os) window is launched!

True, but this title is NOT the same thing as name (in particular, the (only) difference seems to be that it doesn't show up in kitty @ ls). See https://github.com/kovidgoyal/kitty/issues/8333 (feature request: expose `title` in kitty @ ls).
