### ISSUE TITLE
Floating Window support

### ISSUE THREAD

**Issue by IndianBoy42** [kovidgoyal/kitty#6322]
**Is your feature request related to a problem? Please describe.**
"Floating windows" in applications like neovim are not actually floating, they are just drawing characters in the terminal grid with border characters for visual separation. neovim for example actually has a `ext_multigrid` feature that allows UIs to get each window as an actually separate grid. With this, programs like neovide can have transparent floating windows, narrower borders that don't take a whole cell. and in the future maybe even drawing the window at arbitrary coordinates rather than restricted to the main terminal grid spacing. Completely separate windows/grid at the terminal level would also allow each window to have different font sizes. 

The other use case would be to have user keybindings or kittens be able to pop up a floating terminal window, most likely as a temporary terminal to run some quick commands or display some output.

**Describe the solution you'd like**
This is definitely a pretty huge feature that would involve coming up with a protocol for programs to communicate to the terminal about windows and having separate grids for each of these windows. probably a collaboration with iterm/wezterm/etc 

I guess I'm just putting the idea out there. 

**Describe alternatives you've considered**
The status quo is terminals being one grid and having to write a separate GUI for more advanced features

**Comment by kovidgoyal** [comment]
It's on my long term TODO list. If you are interested in helping
implement it, then we can discuss, otherwise you will just have to wait
till I get around to it.
