### ISSUE TITLE
`-A` flag does not work using the `ssh` kitten

### ISSUE THREAD

**Issue by cor** [kovidgoyal/kitty#6324]
**Describe the bug**
When running: 
```
ssh -A -p 2200 localhost
...
ssh git@github.com
```

I get:
```
Hi cor! You've successfully authenticated, but GitHub does not provide shell access.
```

However, when running:
```
kitty +kitten ssh -A -p 2200 localhost
...
ssh git@github.com
```

I get:
```
git@github.com: Permission denied (publickey).
```

To me it looks like the `-A` flag does not properly work when using the kitten.

**Comment by kovidgoyal** [comment]
The ssh kitten uses master connections, make sure you are passing -A to
the first created connection to a particular host.

**Comment by cor** [comment]
Ah yes, this works! Thanks so much
