### ISSUE TITLE
Text Duplication with Dynamic Output

### ISSUE THREAD

**Issue by emrakyz** [kovidgoyal/kitty#6327]
**Description of the Bug**
Dynamic texts are duplicated if I resize the main window in Kitty terminal. Only if it's full or near full screen, then it's normal.

**Steps To Reproduce**
1. Open Kitty Terminal
2. Run a terminal command that has a dynamic output. Such as installing a software from a package manager or encoding a video file with ffmpeg.
3. Resize your window (Open a second terminal for window managers).
4. Encounter the problem.

**Screenshots**
The below output should normally be a single line but with every update of the output, it gets duplicated and if I make Kitty fullscreen again, it stops but the text looks bad as if the multiple lines are a single line. 
![image](https://github.com/kovidgoyal/kitty/assets/89175311/c70e0ac2-ca38-41df-8dc5-b19c52d8b17d)

**Environment details**
1. Linux 6.4
2. Kitty compiled with the latest git commit (On Gentoo Linux).
3. Wayland backend.
4. Hyprland compositor.
5. Nvidia GPU.

**Additional context**
I haven't changed many settings on Kitty except transparency, fonts and colors.

**Comment by kovidgoyal** [comment]
That is to be expected. When you resize the terminal, text gets reflowed. Depending on how your application is outputting its lines, that will happen. Usually the cursor will move to the next line, and the application will output again leading to what you perceive as  a duplicate.
