### ISSUE TITLE
Fallback to using `<ESC>[14t` to determine screen size for `icat`

### ISSUE THREAD

**Issue by attilusleung** [kovidgoyal/kitty#6329]
**Is your feature request related to a problem? Please describe.**
For some reason, on some `ssh` sessions, the `winsize` struct is not set properly and the terminal screen size cannot be determined using `TIOCGWINSIZE`. This causes `icat` to think we're using a terminal that isn't supported. The `<ESC>[14t` escape code, however, will still work.
 
**Describe the solution you'd like**
 Would it be possible to fallback to using this escape code to detect screen size for `icat` if `TIOCGWINSIZE` doesn't work (or maybe specify this method manually using a cli flag) so it can work on these ssh sessions?

Thank you!

**Comment by kovidgoyal** [comment]
Not worth the effort for me, patches welcome. Adding another escape code
which will also be fallible, am sure some terminal mutliplxer/session
recorder/etc will filter it seems like a waste. If I were you, I would
figure out what the issue with ssh is and fix it. As far as I know there
i no such problem in ssh, more likely there is something interfering on
the remote side, check if you are running inside a multiplexer or
similar there.
