### ISSUE TITLE
Chinese characters too small

### ISSUE THREAD

**Issue by ohnekopf** [kovidgoyal/kitty#6332]
I am trying to get kitty to print chinese characters (Noto Sans Mono CJK SC)  at a legible size (so a bit bigger than my normal font size) but i cannot seem to get kitty to pickup what i am trying to achieve with fontconfig.

my fc snippet is: 
```
<match target="font">
    <test name="family">
        <string>Noto Sans Mono CJK SC</string>
    </test>
    <edit name="pixelsize" mode="assign">
        <times><name>pixelsize</name>, <double>1.4</double></times>
    </edit>
</match>
```
the value of 1.4 results in a kinda exaggerated result so you can see the difference between setting it to 1.0 and 1.4 in xfce4-terminal, 
![image](https://github.com/kovidgoyal/kitty/assets/68486059/39b649a2-5505-454a-84ae-bb3ddfb7b480)
and without any enlargement:
![image](https://github.com/kovidgoyal/kitty/assets/68486059/0e13aa61-8928-435f-8946-b221db8a8d88)
but kitty doesn't seem to respond to fontconfig, although running kitty with the  `--debug-font-fallback` option confirms its the same font being used, no matter whether i set it the multiplier to 1.0, 1.4 or whatever the result is the same:
![image](https://github.com/kovidgoyal/kitty/assets/68486059/bc733b4b-2b9c-4215-8d4a-fc5ec9453840)
font comes out rather small and hard to read.
```U+662f Face(family=Noto Sans Mono CJK SC, style=Regular, ps_name=NotoSansMonoCJKsc-Regular, path=/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc, index=7, is_scalable=True, has_color=False, ascender=1160, descender=-288, height=1448, underline_position=-150, underline_thickness=50, strikethrough_position=325, strikethrough_thickness=50)```
what am i doing wrong? 

```kitty 0.19.3 created by Kovid Goyal
Linux luc-81mt 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64
Debian GNU/Linux 11 \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/me/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=35, green=31, blue=32)
color0                Color(red=35, green=31, blue=32)
color1                Color(red=238, green=46, blue=36)
color10               Color(red=0, green=133, blue=62)
color11               Color(red=255, green=210, blue=4)
color12               Color(red=0, green=157, blue=220)
color13               Color(red=152, green=0, blue=93)
color14               Color(red=133, green=206, blue=188)
color2                Color(red=0, green=133, blue=62)
color3                Color(red=255, green=210, blue=4)
color4                Color(red=0, green=157, blue=220)
color5                Color(red=152, green=0, blue=93)
color6                Color(red=133, green=206, blue=188)
color7                Color(red=217, green=216, blue=216)
color8                Color(red=115, green=113, blue=113)
color9                Color(red=238, green=46, blue=36)
font_size             12.0
foreground            Color(red=217, green=216, blue=216)
scrollback_pager      ['less', '-r']
update_check_interval 0.0
Added shortcuts:
	shift+super+v KeyAction(func='paste_from_clipboard', args=())
Changed shortcuts:
	shift+control+down KeyAction(func='decrease_font_size', args=())
	shift+control+up KeyAction(func='increase_font_size', args=())
```

Thanks

**Comment by kovidgoyal** [comment]
You cannot control the font size of fallback fonts. kitty is a strict
monospaced grid display. Characters from fallback fonts are rendered at
the size of the main font, and then resized as needed to ensure they fit
within the grid, which for CJK characters means two cells.

**Comment by ohnekopf** [comment]
oh, i see.  Well i dont really need more than two cells for CJK characters, but  the problem is that for some reason the font i am using uses a lot of padding  and is thus hard to read. 
I experimented a bit and for some reason  the font VL  Gothic works pretty well! but sadly that font is meant for japanese so its missing quite a few chinese characters. 
here's what happens if  set VL Gothic higher precedence  than Noto mono CJK in fc . 
![image](https://github.com/kovidgoyal/kitty/assets/68486059/e5b1914c-3729-49a2-a11c-8f1929ff020c)
the  妈  characters in there are from Noto Mono fonts (missing in VL Gothic apparently) and the rest are VL Gothic. for some reason VL Gothic takes full advantage of the allocated size while Noto mono CJK is less greedy.  what could be causing this? I feel like they should  be rendered to the same size.
```
U+5988 Face(family=Noto Sans Mono CJK SC, style=Regular, ps_name=NotoSansMonoCJKsc-Regular, path=/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc, index=7, is_scalable=True, has_color=False, ascender=1160, descender=-288, height=1448, underline_position=-150, underline_thickness=50, strikethrough_position=325, strikethrough_thickness=50)
U+662f Face(family=VL Gothic, style=regular, ps_name=VL-Gothic-Regular, path=/usr/share/fonts/truetype/vlgothic/VL-Gothic-Regular.ttf, index=0, is_scalable=True, has_color=False, ascender=860, descender=-140, height=1000, underline_position=-100, underline_thickness=50, strikethrough_position=258, strikethrough_thickness=49)
```
Anyway, i will experiment with other fonts, maybe Noto is to blame here.

**Comment by ohnekopf** [comment]
![image](https://github.com/kovidgoyal/kitty/assets/68486059/4147438f-8ce3-4e80-b43b-cc1a0ac51e87)
![image](https://github.com/kovidgoyal/kitty/assets/68486059/1842d61e-4093-475b-853d-c5c4491357a1)
![image](https://github.com/kovidgoyal/kitty/assets/68486059/5f1a636c-c745-409e-8628-be355a34cc16)
Ok i have tried a few different fonts.  As you can see its pretty inconsistent. Would like to know if anyone else has the same problem

**Comment by kovidgoyal** [comment]
How a glyph is rendered at a given point size is entirely font dependent. Someday I might add the ability to specify per glyph/codepoint scaling options, but its not a priority.
