### ISSUE TITLE
Some unicode characters render incorrectly

### ISSUE THREAD

**Issue by tmccombs** [kovidgoyal/kitty#634]
![image](https://user-images.githubusercontent.com/2541726/41330340-2632d124-6e90-11e8-9b01-9c0cbeb43384.png)

The above image is the rendering of "6 ⮚" (The second character is U+2B9A Three-D Top-Lighted Rightwards Equilateral Arrowhead). It renders properly in VTE based terminals such as termite and terminator. I am using "Source Code Pro" font, but changing the font doesn't seem to help.

It used to show up fine, but recently broke (I think because of an update).

I am using kitty version 0.11.0.

There are other characters that show up as strange hashing patterns as well:
![image](https://user-images.githubusercontent.com/2541726/41330813-cf91596e-6e92-11e8-88d0-dda722edec63.png)

should be:
"˰ᄏザϜᴦϴ"؛

And those do render correctly in other terminals.

Since they are non-latin characters, I wonder if it is falling back to a different font, but using the wrong metrics (from the Source Sans Pro font) or something.

**Comment by kovidgoyal** [comment]
This will happen when the fallback font chosen is a bitmap font. You need to install a scaleable font that has those characters, such as symbola. You can check what fallback font is being used via the --debug-fallback option
