### ISSUE TITLE
Search on docs website returns fewer results than expected

### ISSUE THREAD

**Issue by dlipovetsky** [kovidgoyal/kitty#6342]
**Describe the bug**
The docs site search returns fewer results than expected. For example on June 5, 2023, the repository search for `overlay` returns 7 results, the docs site search returns 0. I expect the docs site search to return 7 results.

(I wasn't able to find the docs site search configuration in the kitty repository, so I couldn't triage this issue further).

**To Reproduce**
1. Search for `overlay` in the docs site https://sw.kovidgoyal.net/kitty/search/?q=overlay&check_keywords=yes&area=default
2. Search for `overlay` in the repository:  https://github.com/search?q=repo%3Akovidgoyal%2Fkitty+overlay+language%3AreStructuredText&type=code&l=reStructuredText

**Screenshots**
Docs search:
![image](https://github.com/kovidgoyal/kitty/assets/3445370/64de81f2-422f-4079-b6ff-ccb8c99082bf)

Repository search:
![image](https://github.com/kovidgoyal/kitty/assets/3445370/5391f0aa-7b6d-4163-92a8-efc8224e7391)

**Comment by kovidgoyal** [comment]
This will be a bug in sphinx search index generation. The kitty docs are
generated using sphinx and there is no kitty specific search configuration (see
docs/conf.py)

I dont currently have the time/bandwidth to look into this further,
instructions for generating the docs are in docs/vuild.rst use

make develop-docs

to investigate.

**Comment by dlipovetsky** [comment]
Thanks for fixing this! :heart:
