### ISSUE TITLE
Incorrect arrow-key escape sequences in terminfo

### ISSUE THREAD

**Issue by LRitzdorf** [kovidgoyal/kitty#6343]
**Describe the bug**
Kitty's terminfo (based on `/usr/lib/kitty/terminfo/kitty.terminfo`) seems to provide incorrect escape sequences for the arrow keys.

**To Reproduce**
1. Observe the escape sequences generated by pressing arrow keys, for example via `cat > /dev/null`. These are of the form `^[[A` (for the up arrow, as an example).
1. Compare these to the sequences listed Kitty's terminfo file. These have the form `^[OA` (with an `O` replacing the `[` from earlier).

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/42657792/eef2e6c0-28cf-4cd9-b6ee-f260fa3cfa5c)

**Environment details**
```
kitty 0.28.1 created by Kovid Goyal
Linux ritzcracker 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64
Arch Linux 6.3.5-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/lucas/.config/kitty/kitty.conf

Config options different from defaults:
disable_ligatures   1
enabled_layouts     ['splits:split_axis=horizontal']
font_family         Cascadia Code
resize_in_steps     True
tab_activity_symbol 🔔 
tab_bar_style       powerline
Added shortcuts:
	alt+down →  neighboring_window down
	alt+left →  neighboring_window left
	alt+right →  neighboring_window right
	alt+up →  neighboring_window up
	ctrl+f4 →  launch --location=split
	ctrl+f5 →  launch --location=hsplit
	ctrl+f6 →  launch --location=vsplit
	ctrl+f7 →  layout_action rotate
	shift+down →  move_window down
	shift+left →  move_window left
	shift+right →  move_window right
	shift+up →  move_window up

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                lucas
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_DATA_HOME                       /home/lucas/.local/share
	XDG_CONFIG_HOME                     /home/lucas/.config
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_CACHE_HOME                      /home/lucas/.cache
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      2
	XDG_STATE_HOME                      /home/lucas/.local/state
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Additional context**
Issue reproduces with `kitty --config NONE`, since terminfo is unchanged.

**Note**
I'm relatively new to terminal-dependent features like terminfo, but am generally Linux-fluent and would be happy to provide any other information that I can to help debug this!

**Comment by kovidgoyal** [comment]
The escape sequences are dependent on *cursor key mode*. 

tput rmkx; showkey -a
tput smkx; showkey -a

These are described in termindo under cuu1 and kcuu1 respectively.

**Comment by LRitzdorf** [comment]
Ah, okay! I'll read up on that, since I'm not familiar with key modes in Kitty. Thanks for the quick response!

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. It is common to 99% of terminals.

**Comment by LRitzdorf** [comment]
All right! One more question, then: terminfo maps `cud1` to `^J`, and `cub1` to `^H`. This seems to be at odds with what `showkey -a` yields, even in cursor key mode (`^[[B` and `^[[D`, respectively). What's the reason for that?

**Comment by kovidgoyal** [comment]
cub and cud dont have anything to do with key presses. See man terminfo
