### ISSUE TITLE
Italic characters side are cut off

### ISSUE THREAD

**Issue by sytranvn** [kovidgoyal/kitty#6346]
**Describe the bug**
While Some capital italic characters like K, M, N, X are cut off.

**To Reproduce**
1. run `kitty --config NONE`
1. run bash command `echo -e "\e[3m   K   M    N   X    \e[0m"` to print some italic characters.
1. See error

**Screenshots**
No config
![image](https://github.com/kovidgoyal/kitty/assets/13009812/a6db7c25-1222-4138-b696-538ba7f3dd68)

Python comment with neovim
![Screenshot from 2023-06-07 22-13-43](https://github.com/kovidgoyal/kitty/assets/13009812/cf854de7-750e-4918-a795-33c0684218bd)

Echo italic in bash
![image](https://github.com/kovidgoyal/kitty/assets/13009812/e041f5dd-438c-454a-ba3b-b827f9865c91)

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Linux toor 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64
Ubuntu 22.04.2 LTS toor /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
Running under: Wayland
Frozen: True
Paths:
  kitty: /home/sytran/.local/kitty.app/bin/kitty
  base dir: /home/sytran/.local/kitty.app/lib/kitty
  extensions dir: /home/sytran/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                ~/.config/bin:/home/sytran/.yarn/bin:/home/sytran/.config/yarn/global/node_modules/.bin:/home/sytran/google-cloud-sdk/bin:/home/sytran/miniconda3/condabin:/home/sytran/.nvm/versions/node/v18.16.0/bin:/home/sytran/.local/kitty.app/bin:/home/sytran/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
	LANG                                en_US.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                sytran
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	LC_ADDRESS                          en_US.UTF-8
	LC_NAME                             en_US.UTF-8
	LC_MONETARY                         en_US.UTF-8
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            en_US.UTF-8
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   en_US.UTF-8
	LC_TELEPHONE                        en_US.UTF-8
	LC_MEASUREMENT                      en_US.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_US.UTF-8
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
	LC_NUMERIC                          en_US.UTF-8
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You need to use a font family that is truly monospace, that is one whose
italic and bold italic faces have the same metrics as the regular face.
Or alternately use the modify_font setting in kitty.conf to increase the
cell width enough to fit the italic face.

**Comment by kovidgoyal** [comment]
So what? The default font on your system suffers from this issue.
