### ISSUE TITLE
Run kitty actions from python

### ISSUE THREAD

**Issue by lolpie244** [kovidgoyal/kitty#6348]
Is there the ability to run kitty mappable actions (like `copy_to_clipboard`) from `kittens.tui.handler.result_handler`?

Use-case: I want to use a single keymap for Kitty and vim. Python script checked if the current window running vim, and if this is true - pass keymap to it, else - run kitty action

**Comment by lolpie244** [comment]
But is there some dictionary, that contains mappable action name and corresponding function?

**Comment by kovidgoyal** [comment]
The action names are function names. I suggest you read https://sw.kovidgoyal.net/kitty/kittens/custom/ and look at a few existing kittens to get an idea.

**Comment by lolpie244** [comment]
Thanks for advice!

**Comment by lolpie244** [comment]
> Hi, This kitten may be helpful discovering all possible actions: https://github.com/ershov/kitty_config
> 
> ![](https://user-images.githubusercontent.com/449936/247107180-b2416091-8eb1-40cd-90a1-8052ce7bbbf8.png)

I have already written a simple script that allows passing keys to Vim (https://github.com/lolpie244/my_linux_config/blob/main/dotfiles/kitty/send_to_vim.py). 
Usage: `map <kitty_keymap> kitten send_to_vim.py <action> <vim_keymap>`
Example: `map alt+c kitten send_to_vim.py copy_to_clipboard alt+c`

But thanks for the answer, I'm sure this will be helpful in the future.
