### ISSUE TITLE
Text on a new prompt line does not wrap

### ISSUE THREAD

**Issue by Bjineh** [kovidgoyal/kitty#6350]
**Describe the bug**
Characters entered on a new prompt line do not wrap, instead they continue from the start of the same line, running back over the prompt and the rest. At the end of the "second" line, text begins to behave normally and continues to the actual second line.

**To Reproduce**
1. Start a new prompt line
2. Type enough text that it hits the opposite edge of the kitty window (regardless of window size)
3. Error - text continues from the start of the same line (see vid below)

**Screenshots**

[kitty screencast.webm](https://github.com/kovidgoyal/kitty/assets/39022657/81b3b994-bbe9-4bfe-b2ce-d992aff1134f)

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux elite 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64
Ubuntu 22.04.2 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/[user]/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color   Color(red=97, green=175, blue=239)
allow_remote_control  y
background            Color(red=33, green=39, blue=51)
bold_font             Ubuntu Mono Bold
bold_italic_font      Ubuntu Mono Bold Italic
cursor                Color(red=255, green=204, blue=102)
editor                nvim
enable_audio_bell     False
font_family           Ubuntu Mono
font_size             13.0
foreground            Color(red=217, green=215, blue=206)
inactive_border_color Color(red=136, green=136, blue=136)
italic_font           Ubuntu Mono Italic
linux_display_server  x11
remember_window_size  False
selection_background  Color(red=52, green=63, blue=76)
selection_foreground  Color(red=33, green=39, blue=51)
tab_bar_style         powerline
update_check_interval 0.0
window_padding_width  FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
```

**Additional context**
`kitty --config NONE` - Problem still happening

**Comment by kovidgoyal** [comment]
Does not reproduce for me using up-to-date kitty.

**Comment by Bjineh** [comment]
Apologies! It was an issue with my bashrc, not kitty.
