### ISSUE TITLE
Nerd Fonts Are Not Rendering Correctly.

### ISSUE THREAD

**Issue by akashdiphazra** [kovidgoyal/kitty#6351]
**Describe the bug**
I am using Source Code Pro Nerd Font.
 
![Ubuntu-2023-06-09-11-35-53](https://github.com/kovidgoyal/kitty/assets/61003681/57fb866e-467b-4103-9232-0a70014fd181)

```conf
  font_family        SauceCodePro Nerd Font Mono
  bold_italic_font   Sauce Code Pro Semibold Nerd Font Complete Mono

```
![Ubuntu-2023-06-09-11-30-29](https://github.com/kovidgoyal/kitty/assets/61003681/29b0e763-af3c-4bf7-8046-9d05109f6836)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty
