### ISSUE TITLE
[Mac] call_remote_control from kitten not working

### ISSUE THREAD

**Issue by CubeVato** [kovidgoyal/kitty#6353]
**Describe the bug**
I'm having difficulty getting the [remote control API for kittens](https://sw.kovidgoyal.net/kitty/kittens/custom/#kitty-api-to-use-with-kittens) to work. I was trying to write a custom kitten to highlight some text (I know there's a separate option for custom marker scripts) and wasn't able to get it to work. The overlay to input text appeared, and I could verify that `handle_result()` was being called by using `w.paste_text(answer)`, as in the example, but I never saw any evidence that `call_remote_control()` was doing anything.

```python
from typing import List
from kitty.boss import Boss

def main(args: List[str]) -> str:
    return input('Text to highlight: ')

def handle_result(args: List[str], answer: str, target_window_id: int, boss: Boss) -> None:
    group = int(args[1]) if len(args) > 1 else 1
    w = boss.window_id_map.get(target_window_id)
    if w is not None:
        if answer != '':
            boss.call_remote_control(w, ('create-marker', 'text', group, answer))
        else:
            boss.call_remote_control(w, ('remove-marker', 'text'))
```

I took a step back and tried to reproduce the hello-world example using the remote control snippet from the documentation:

```python
from typing import List
from kitty.boss import Boss

def main(args: List[str]) -> str:
    # this is the main entry point of the kitten, it will be executed in
    # the overlay window when the kitten is launched
    answer = input('Enter some text: ')
    # whatever this function returns will be available in the
    # handle_result() function
    return answer

def handle_result(args: List[str], answer: str, target_window_id: int, boss: Boss) -> None:
    # get the kitty window to which to send text
    w = boss.window_id_map.get(target_window_id)
    if w is not None:
        boss.call_remote_control(w, ('send-text', 'hello world' + answer))
```

This also doesn't work. As with the first script, the overlay appears with the input prompt, but the text never appears on screen. It's worth noting that both `kitty @ create-marker text 1 "hello"` and `kitty @ send-text "hello world"` work fine when run from the command line, so it seems like the problem is isolated to `call_remote_control()` and/or kittens specifically.

I'm not sure if the `allow_remote_control` setting applies to this API, but it's also worth noting that I tried it with this set to both `socket-only` and `yes`, but this didn't appear to make a difference.

**To Reproduce**
1. Copy and paste the above Python snippet into a new kitten file: hello.py.
2. Relaunch kitty (in case this matters).
3. Run `kitty +kitten hello.py`.
4. See the overlay appear.
5. Enter any text and hit enter.
6. Notice that no text is sent to the terminal.

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin ramonlovato-mbp16m132.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.4 BuildVersion:		22F66
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ramon.lovato/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control              yes
cursor                            None
cursor_text_color                 None
env:
{'NONE': '_delete_this_env_var_'}
exe_search_path:
{'+./bin': '+./bin'}
font_size                         14.0
inactive_text_alpha               0.6
initial_window_height             (25, 'cells')
initial_window_width              (160, 'cells')
listen_on                         unix:/tmp/kitty
macos_option_as_alt               2
macos_show_window_title_in        window
macos_titlebar_color              1
modify_font:
    cell_width 100%
mouse_hide_wait                   3.0
narrow_symbols:
{(57504, 57507): 1, (57536, 57543): 1}
remember_window_size              False
remote_control_password:
{'': ('create-marker', 'remove-marker')}
select_by_word_characters_forward abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
symbol_map:
	U+e0a0 - U+e0a3 → PowerlineSymbols
	U+e0c0 - U+e0c7 → PowerlineSymbols
tab_activity_symbol               🚗 
tab_title_template                {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}. {title}
url_excluded_characters           " "
watcher:
{'./watchers/noop_watcher.py': './watchers/noop_watcher.py'}
Added shortcuts:
	cmd+d →  launch --location=neighbor
	cmd+f →  show_scrollback
	ctrl+n →  scroll_to_mark next
	ctrl+p →  scroll_to_mark prev
	f1 →  launch_tab vim
	f4 →  new_window_with_cwd
	f5 →  toggle_marker regex 1 \\bERROR\\b 2 \\bWARNING\\b
	opt+cmd+left →  previous_tab
	opt+cmd+right →  next_tab
Changed shortcuts:
	kitty_mod+f →  kitten kittens/highlight.py
Colors:
	background                        #1d1d1d   
	color0                            #343835   
	color1                            #ce3e60   
	color10                           #767e2b   
	color11                           #77592e   
	color12                           #135879   
	color13                           #5f4190   
	color14                           #76bbca   
	color15                           #b1b5ae   
	color2                            #7bb75b   
	color3                            #e8b32a   
	color4                            #4c99d3   
	color5                            #a57fc4   
	color6                            #389aac   
	color7                            #f9faf6   
	color8                            #585a58   
	color9                            #d18ea6   
	foreground                        #f7f6ec   
	selection_background              #165776   
	selection_foreground              #1d1d1d   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.M0D1eHJSyT/org.xquartz:0
	USER                                ramon.lovato
```

**Additional context**
The behavior running the kitten with `kitty --config NONE` is the same, as is with `kitty --config NONE -o allow_remote_control=yes` (in case that matters).

Starting a new kitty session with `kitty --dump-commands` and running `kitty +kitten hello.py` yields the same result. However, if, from the new session, I then run `kitty @` to drop into the REPL, and from there, run `kitten hello.py`, I then see the following message in the parent session's `--dump-commands` output:
```
[160 12:54:07.816632] Failed to write to child 3 as it does not exist
```
Since I do _not_ see this message when running it with `--dump-commands` and the `kitty +kitten hello.py` invocation, it's hard to know if this is relevant.

**Comment by kovidgoyal** [comment]
In order to use handle_result() you need to run the kitten via mapping
not directly, only then can it be run in the same process as kitty and
have access to kitty. Otherwise you are running it as a separate
process.

kitty -o 'map f1 kitten hello.py'


If you want to use remote control in a separately run kitten you do it
inside main() by something like

subprocess.run(['kitten', '@', 'send-text', 'whatever'])

and yes for this you have to enable remote control.

**Comment by CubeVato** [comment]
Thanks for taking a look. I thought that might be the case, but I wasn't sure if the kitten used the remote control socket to communicate with the parent process. I tried your suggesting, but that doesn't seem to be working either. If I try binding the kitten with `map f1 kitten hello.py` in kitty.conf, when hitting F1  results in the same behavior as if I run the run the command: the overlay appears asking for input, but the text never appears in the terminal. If I run it in a child process with `kitty -o 'map f1 kitten hello.py'`, as you've suggested, when I hit F1 in the child session, I get the same overlay + no output behavior, but the log in the parent shell reports that same error message I mentioned at the end of my original post:
```
[160 18:55:43.399814] Failed to write to child 2 as it does not exist
```

Using the subprocess approach is fine for my use case, so I can go ahead with that, but I think there may still be a bug here worth investigating.

**Comment by kovidgoyal** [comment]
That will be because target_window_id is pointing to the window in which
the kitten was run. This is likely a bug, I will need to check. Use 
w = boos.window_id_map.get(1) to get the first window.

**Comment by kovidgoyal** [comment]
Actually no use

call_remote_control(w, 'send-text', '-m', f'{w.id}', 'whatever')

the bug is really that call_remote_control doesnt override the active
window to the target window, so send text is sending to the kitten
window.
