### ISSUE TITLE
cannot generate go code when cross-compiling

### ISSUE THREAD

**Issue by classabbyamp** [kovidgoyal/kitty#6354]
because [this part of setup.py](https://github.com/kovidgoyal/kitty/blob/v0.28.1/setup.py#L890) tries to run something it has built to generate some go code, kitty cannot be cross-compiled on Linux (this was tested within void linux's build system - void-linux/void-packages#44338)

As a workaround, I tried prefixing the command linked above with `qemu-user-static`'s binary (e.g. `qemu-aarch64-static`) when crossbuilding. This seemed to work when building with `x86_64` as host and `aarch64` as target, but does not work with `armv6l` or `armv7l` as the target, failing with:

```py
Updating Go generated files...
Error processing line 1 of /usr/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/destdir/arm-linux-gnueabihf/kitty-0.28.1/usr/bin/../lib/kitty/__main__.py", line 7, in <module>
    main()
  File "/destdir/arm-linux-gnueabihf/kitty-0.28.1/usr/bin/../lib/kitty/kitty/entry_points.py", line 191, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/destdir/arm-linux-gnueabihf/kitty-0.28.1/usr/bin/../lib/kitty/kitty/entry_points.py", line 145, in namespaced
    func(args[1:])
  File "/destdir/arm-linux-gnueabihf/kitty-0.28.1/usr/bin/../lib/kitty/kitty/entry_points.py", line 73, in launch
    runpy.run_path(exe, run_name='__main__')
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/builddir/kitty-0.28.1/gen-go-code.py", line 4, in <module>
    import bz2
  File "/usr/lib/python3.11/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

is there a better way this could be done, that actually works? If not, could a way be added?

**Comment by kovidgoyal** [comment]
Supporting cross compilation is rather too much work for me. I prefer to
compile in VMs. If you really want to cross compile you will need
to cross compile python and use that as the python to build kitty with.
Because large bits of kitty code are generated, you need to be able to
run kitty on your build machine which means some of its deps, especially
python needs to be cross compiled as well and then they need to be run
with some kind of translation layer such as qemu-static.

Another alternative would be to run gen-go-code using a native build and
copy over the output and skip running it during cross-compilation. I
dont *think* anything in its output is arch dependent, but I cant be
100% sure of that. Basically do a native build, then copy over all the
files ending in _generated.go to the dir you are doing your cross build
in.

**Comment by classabbyamp** [comment]
thanks for the work on cross-compiling!

with your commit applied on top of v0.28.1, it took a little finagling with CFLAGS and such, but I was able to get it to cross-compile successfully for aarch64 from x86_64.

As a side note, I don't think there is a `build` target in that makefile ([ref](https://github.com/kovidgoyal/kitty/commit/88a5086f71f44e09539cae9af0cf62697df01f45#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R68)), but I wasn't using the makefile

![image](https://github.com/kovidgoyal/kitty/assets/5366828/105e5b9e-8ce9-4db9-bc73-69efd1e58598)

**Comment by kovidgoyal** [comment]
thanks, fixed.

**Comment by classabbyamp** [comment]
another thing that could make cross-compiling easier: we add `-I$XBPS_CROSS_BASE/usr/include/python3.11` (`XBPS_CROSS_BASE` is something like `/usr/arm-linux-gnueabihf`, depending on the target) to the `CFLAGS` env var when when cross-compiling.

In https://github.com/kovidgoyal/kitty/blob/master/setup.py#L195-L204 it seems that it relies exclusively on `sysconfig` for finding the includepaths, so that it doesn't pick up on the fact that it should be looking for python's headers in `/usr/arm-linux/gnueabihf/usr/include/python3.11` instead of just `/usr/include/python3.11`

**Comment by kovidgoyal** [comment]
On Tue, Jun 13, 2023 at 09:44:08PM -0700, classabbyamp wrote:
> another thing that could make cross-compiling easier: we add `-I$XBPS_CROSS_BASE/usr/include/python3.11` (`XBPS_CROSS_BASE` is something like `/usr/arm-linux-gnueabihf`, depending on the target) to the `CFLAGS` env var when when cross-compiling.
> 
> In https://github.com/kovidgoyal/kitty/blob/master/setup.py#L195-L204 it seems that it relies exclusively on `sysconfig` for finding the includepaths, so that it doesn't pick up on the fact that it should be looking for python's headers in `/usr/arm-linux/gnueabihf/usr/include/python3.11` instead of just `/usr/include/python3.11`

Not sure I follow. Why not simply run setup.py with the cross-compiled
python using qemu-static. In that case it will use the right sysconfig
automatically. Or get python to load the cross sysconfig module using
PYTHONPATH=/some/temp/dir/that/contains/a/copy/of/the/cross/sysconfig.py
