### ISSUE TITLE
test fails with python 3.12

### ISSUE THREAD

**Issue by solopasha** [kovidgoyal/kitty#6360]
**Describe the bug**
When building kitty against python 3.12 test_load_images test fails.

**To Reproduce**
1. try building kitty against python 3.12 (linux-package)
2. See error

Build logs: https://0x0.st/Hc0E.log
tests only output: https://0x0.st/Hc06.log

**Comment by solopasha** [comment]
There's also warnings 
```
kitty/line-buf.c: In function ‘copy_old’:
kitty/line-buf.c:541:15: error: missing braces around initializer [-Werror=missing-braces]
  541 |     Line sl = {{0}}, ol = {{0}};
      |               ^
      |                 {}
kitty/line-buf.c:541:27: error: missing braces around initializer [-Werror=missing-braces]
  541 |     Line sl = {{0}}, ol = {{0}};
      |                           ^
      |                             {}
cc1: all warnings being treated as errors
```
I ignored them with --ignore-compiler-warnings

**Comment by kovidgoyal** [comment]
I'm afraid I dont have the time/bandwidth to support pre-release versions of python.

**Comment by kovidgoyal** [comment]
That said, this should be a simple fix assuming the cause is what I think it is.
