### ISSUE TITLE
Allow `env` command in startup session file?

### ISSUE THREAD

**Issue by nhanb** [kovidgoyal/kitty#6362]
**Is your feature request related to a problem? Please describe.**

I'm setting up a startup session for my python project which uses a virtualenv. I want to keep its virtualenv activated for all existing and future tabs/windows of this session. So far I have to repeat the necessary `--env` values for every `launch` command, like this:

```
new_tab vim
cd ~/pj/bloghead-qt
launch --env VIRTUAL_ENV=$HOME/.venvs/bloghead-qt --env PATH=$HOME/.venvs/bloghead-qt/bin:$PATH fish -c 'vim README.md'

new_tab shell
cd ~/pj/bloghead-qt
launch --env VIRTUAL_ENV=$HOME/.venvs/bloghead-qt --env PATH=$HOME/.venvs/bloghead-qt/bin:$PATH fish -C 'ls -lha'
```

I'm looking for a way to define the environment variables in one place.

**Describe the solution you'd like**

Allowing the `env` command in session files is my first thought:

```
env VIRTUAL_ENV=$HOME/.venvs/bloghead-qt
env PATH=$HOME/.venvs/bloghead-qt/bin:$PATH

new_tab vim
cd ~/pj/bloghead-qt
launch fish -c 'vim README.md'

new_tab shell
cd ~/pj/bloghead-qt
launch fish -C 'ls -lha'
```

But this session gives an error: `ValueError: Unknown command in session file: env`. So, could we allow `env` in the session file?

**Describe alternatives you've considered**

I've tried `--copy-env` in the second `launch` but that didn't work (the second tab would not activate the virtualenv):

```
new_tab vim
cd ~/pj/bloghead-qt
launch --env VIRTUAL_ENV=$HOME/.venvs/bloghead-qt --env PATH=$HOME/.venvs/bloghead-qt/bin:$PATH fish -c 'vim README.md'

new_tab shell
cd ~/pj/bloghead-qt
launch --copy-env fish -C 'ls -lha'
```

It seems that `--copy-env` does nothing in a session file?

**Additional context**

I'm only having trouble with activating virtualenv for initial windows. For subsequent manually created windows, I can simply map a shortcut to `launch --copy-env [--type=tab]`.

**Comment by kovidgoyal** [comment]
Simply run kitty like this:

env MYENVAR1=whatever MYENVVAR2=whatever kitty --session mysessionfile

Or if you prefer to define them in a file use a conf file in
~/.config/kitty with

env A=B
env B=C
include kitty.conf

and run kitty with

kitty --config env.conf --session whatever

**Comment by nhanb** [comment]
I ended up following your second suggestion. Thanks!
