### ISSUE TITLE
Selecting word and until end of line

### ISSUE THREAD

**Issue by warpfork** [kovidgoyal/kitty#6363]
**Is your feature request related to a problem? Please describe.**

A feature I love from other terminals is tripleclick (or your choice of action) to select the current word (much like doubleclick does by default in kitty) and then extend the selection also to the end of the current line.

"Current word and to end of current line" is very often the ideal "do what I mean" for selecting part of a script, etc.  By contrast, selecting the whole line is often _not_ exactly what I mean, because it will also grab part of the terminal prompt text (e.g. the `$` or `#`, typically).

**Describe the solution you'd like**

I think what I'm asking for is the ability to say something like `mouse_map left triplepress ungrabbed mouse_selection line_from_word`.

Or, some way to combine `mouse_selection word` and `mouse_selection line_from_point`.

**Describe alternatives you've considered**

I've been trying to find some incantation combining existing features like `word` and `line_from_point` and possibly `extend` or `move-end`.  Or really any combination of keywords I see in https://sw.kovidgoyal.net/kitty/conf/#conf-kitty-mouse-mousemap .  I haven't yet found the correct incantation, though, if one exists :)

If there's a way to chain selection adjustments, it seems like that would work, but I don't think I've found examples of that.  (I see comma-separators in that mousemap config docs page, but those don't appear to be for the composing of actions.)

**Additional context**

Think that should do it.  Kitty is pretty great, thanks :)

**Comment by kovidgoyal** [comment]
Double click to select word then right click to extend selection.

**Comment by warpfork** [comment]
Is there a way I can map that to a single action, though?

**Comment by kovidgoyal** [comment]
I dont understand why you would want to select a word and then extend to end of line. Instead select to end of line from the start of the word. I suppose it requires a bit more precision to move your mouse to the start of the word rather than at any point in the word, but that's not sufficient motivation for me to implement such an action. A PR is most welcome.

**Comment by warpfork** [comment]
Right, it's a precision-required vs ease thing :)  I find it's a very very common action for me, so making it easy and require lower precision of motion is a large life-improvement.

I may try to make a PR, but I'm not very familiar with either Python or C and I might have some questions about the build process. :)
