### ISSUE TITLE
"428u" randomly spams

### ISSUE THREAD

**Issue by ignxcy** [kovidgoyal/kitty#6368]
**Describe the bug**

**To Reproduce**
1. Open the kitty terminal.
2. Perform normal operations or use any specific commands.
3 .Randomly observe the appearance of "428u" in the terminal output.
4. The "428u" text appears repeatedly and without any apparent reason.

**Screenshots**
![428u](https://i.imgur.com/KwmvsDz.png)

**Environment details**
```
kitty 0.28.1 created by Kovid Goyal
Linux fedora 6.3.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun  9 15:21:11 UTC 2023 x86_64
S
Kernel 6.3.7-200.fc38.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/ignacy/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.8
font_size            12.0
Colors:
        background           #272727   
        color0               #272727   
        color1               #cc231c   
        color10              #b8ba25   
        color11              #fabc2e   
        color12              #83a597   
        color13              #d3859a   
        color14              #8ec07b   
        color15              #ebdbb2   
        color2               #989719   
        color3               #d79920   
```

Also some random unicode familiar to "a" sometime spams, but it doesnt happen very often

**Comment by kovidgoyal** [comment]
Does not reproduce for me with those steps. And those are almost
certainly key events. Something you ran turned on the kitty keyboard
protocol and didnt turn it off again.

**Comment by ShamrockLee** [comment]
I'm experiencing similar problem on my LxQt NixOS (x86_64-linux). It's hard to reproduce but has the following properties:

- When a Kitty window starts spamming `428u`, it may stop when the window lose focus.
- In the above situation, opening another Kitty window and focus it does not cause the new Kitty window to spam, which also works for other application windows, showing that it's not the keyboard hardware feeding the strings.
- It is often accompanied by the loss of some keyboard functionality, such as the ability to repeat characters/operations during long pressing. The functionality lost is different from incident to incident.
- If one starts SimpleScreenRecorder, during the spamming, the spamming will continue when the problematic window regains focus. However, the spamming stops whenever SimpleScreenRecorder starts recording.

<img width="640" height="400" alt="Screenshot showing a Kitty window (decorator excluded) flooded with a repeated string: 428u" src="https://github.com/user-attachments/assets/fa30d4f2-9a2e-481a-837d-aee9ef765d73" />

**Comment by ShamrockLee** [comment]
Update. I'm experiencing the longest episode of spamming. It now spreads across kitty windows and even affects VLC Media Player (which keeps toggling between pause and play). Other applications (including xterm QTerminal, Firefox and VSCodium) are still not affected.

**Comment by ShamrockLee** [comment]
Update:
Found the cause. It is my new headset connected via a 3.5mm-to-USB-C adapter to my desktop. It probably happens when the 3.5mm TRRRS male connector not fully mated with the female connector on the adapter.
