### ISSUE TITLE
Support for rosetta 2 on mac os

### ISSUE THREAD

**Issue by darahask** [kovidgoyal/kitty#6369]
Add option to run kitty terminal using rosetta 2 on mac
<img width="257" alt="Screenshot 2023-06-17 at 4 30 12 PM" src="https://github.com/kovidgoyal/kitty/assets/44225449/63680497-fb45-4216-ac08-3b5d7f10f568">

**Comment by kovidgoyal** [comment]
Why on earth would you want to run a terminal emulator under emulation?
kitty runs natively on all architectures Apple supports.

**Comment by darahask** [comment]
Hi,

Cause some libraries doesn't work properly for arm (m1 chipset) so I am
running terminal app of mac using Rosetta 2 to install x86 version of
homebrew and take advantage.

**Comment by kovidgoyal** [comment]
Use the arch command for that.
