### ISSUE TITLE
Looking for a list of key combinations that are available to the shell inside the emulator.

### ISSUE THREAD

**Issue by Sleepful** [kovidgoyal/kitty#6370]
### Problem

I want to add a new keybinding inside one of my terminal apps like Neovim, but I do not know if the key combination that I want to create is something that the terminal can receive. I usually attempt to look at the result with `C-v` in the shell followed by the keys that I want. This is somewhat frustrating and often involves messing around with config files.

### Solution

Documentation, just a list of all possible key combos that can be read by the terminal. I know that kitty has access to all the combinations emitted by the OS, this is not what I mean. I mean the key combinations available in the terminal that are emitted or relayed from the OS by Kitty.

**Comment by Sleepful** [comment]
Seems like this link does a very good job at documenting the keycodes:

https://invisible-island.net/xterm/xterm-function-keys.html

It is for xterm but I see similar behavior in Kitty. Would be nice to have kitty-canonical information though, not sure if the xterm behavior is incongruent at some point.

**Comment by kovidgoyal** [comment]
Nowadays neovim supports the kitty keyboard protocol which means *all*
key combinations are useable.
