### ISSUE TITLE
macOS keyboard shortcut configurations limited by built-in, unconfigurable shortcuts

### ISSUE THREAD

**Issue by helgihg** [kovidgoyal/kitty#6371]
**Describe the bug**

A number of important keyboard shortcuts that are available on Linux are unavailable on macOS because the built-in keyboard shortcuts in the application's menubar supercede them. Examples are cmd-d (command-shift-d) and cmd-T (cmd-shift-t). A user may want cmd-shift-t to open a new tab in Tmux within Kitty, for example, while using ctrl-shift-t for a new Kitty tab.

The following combinations are unavailable to binding because they are superceded by the shortcuts in the menubar:

- cmd-n
- cmd-t
- cmd-enter
- cmd-shift-w
- cmd-w
- cmd-shift-d
- cmd-option-r
- cmd-k
- cmd-m

**To Reproduce**
1. Open configuration file (`~/.config/kitty/kitty.conf`) and insert line `map cmd+t set_tab_title`.
2. Close configuration file and reload settings with menu command "kitty" -> "Reload Preferences".
3. Hold command-button and press "T".
4. Notice that a new tab has opened in accordance with the shortcut in menubar "Shell" -> "New Tab", in contradiction with configuration, which says that it should rename the current (default) tab.

**Screenshots**
N/A

**Environment details**
```
macOS 13.4 (22F66)
kitty 0.28.1

Kitty was installed using Homebrew 4.0.23.
```

**Additional context**
The simplest solution is to remove the keyboard shortcuts from the menubar altogether, or at least those that aren't dictated by macOS.

A more sophisticated solution, however, would be to populate the menubar entries with the configurations as they appear in `~/.config/kitty/kitty.conf`. That way, the default shortcuts would still be visible to the user without customized configuration.

**Comment by kovidgoyal** [comment]
They work fine, you just need to restart kitty for these particular
ones.

**Comment by helgihg** [comment]
Ah, great! Thanks!
