### ISSUE TITLE
Raspberry Pi 4: cannot use installer as GLIBC version is 2.31

### ISSUE THREAD

**Issue by iandol** [kovidgoyal/kitty#6373]
**Describe the bug**
Use the kitty installer on 64bit Raspberry Pi 4 fails (tried both stable and nightly):

```
❯ curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=nightly
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4487  100  4487    0     0   1387      0  0:00:03  0:00:03 --:--:--  1387
Downloading from: https://github.com/kovidgoyal/kitty/releases/download/nightly/kitty-nightly-arm64.txz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 17.6M  100 17.6M    0     0  2971k      0  0:00:06  0:00:06 --:--:-- 3824k
Installing to /home/cog/.local/kitty.app
/home/cog/.local/kitty.app/bin/kitty: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/cog/.local/kitty.app/bin/kitty)
/home/cog/.local/kitty.app/bin/kitty: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/cog/.local/kitty.app/bin/kitty)
```

libc on RPi:

```
❯ apt search libc-
Sorting... Done
Full Text Search... Done
glibc-doc/stable,stable 2.31-13+rpt2+rpi1+deb11u5 all
  GNU C Library: Documentation

glibc-doc-reference/oldstable,oldstable 2.31-1 all
  GNU C Library: Documentation

glibc-source/stable,stable 2.31-13+rpt2+rpi1+deb11u5 all
  GNU C Library: sources

libc-bin/stable,now 2.31-13+rpt2+rpi1+deb11u5 arm64 [installed]
  GNU C Library: Binaries
```

**To Reproduce**
1. Use installer.sh on Raspberry Pi 4 (latest OS)

**Additional context**
I am pretty ignorant about C compilation and static linking so don't know if this could be fixed or not. Can this be solved or is manual compilation the only solution? Given you recently fixed the OpenGL compatibility issues Kitty would be a great fit now for this popular single-board computer...

**Comment by kovidgoyal** [comment]
I'm afraid I am not going to support arbitrarily old distros. Build from
source or use a distro package if you are going to be using such an old
distro.

**Comment by iandol** [comment]
@kovidgoyal -- Hi, i totally understand you don't want to support old software, but just to say this **is the the latest most modern version of the Raspberry Pi OS**:

```
Release date: May 3rd 2023
System: 64-bit
Kernel version: 6.1
Debian version: 11 (bullseye)
```

Which is using the stable version of [Debian](https://packages.debian.org/search?suite=bullseye&searchon=names&keywords=libc-), a fairly well recognised distro...

**Comment by kovidgoyal** [comment]
No, it's the latest version of *Debians stable* available *for the Pi*. Install
Arch instead, for example. Or build kitty for yourself using whatever
libc you need. The actual current Debian stable is Debian 12
which works fine with the kitty binaries.
