### ISSUE TITLE
Producing complete portable packages when building from source

### ISSUE THREAD

**Issue by warpfork** [kovidgoyal/kitty#6378]
(A better label for this might be "docs" or "help request", but "bug" seemed the closest of the issue templates...)

**Describe the bug**

I'm not sure how to recreate the (very nice, easily portable, wonderful!) linux packages equivalent to what I find downloadable from Github Releases.

**To Reproduce**

- I checked out the kitty git repo, and installed all the system level dependencies needed, as described in the [build from source](https://sw.kovidgoyal.net/kitty/build/) instructions...
- I was able to successfully run `make linux-package`.
- `./linux-package/bin/kitty` produced by this runs successfully.  So far, so good.
- However, I expected if I take the entirety of `./linux-package/`, create a tarball, and move it to another machine, it should work (as the releases on Github do!).  This is not the case.  Doing so results in `./bin/kitty: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory`.
- I observe that `./linux-package/lib/` contains only a `kitty` dir (which contains mostly glsl files, python files, etc).
  - By contrast, in the nice portable release on Github, the `lib` dir contains 28 files matching `*.so*`, the `libpython3.9.so.1.0` file among them.
  
Maybe I am "holding it wrong" :)  Is there some other subcommand I should be running in order to produce the portable packages?

**Comment by kovidgoyal** [comment]
Building the frozen binaries is not something regular users can do
easily. They are built in VMs running under QEmu and including thousands
of lines of code in bespoke build system. If you are interested look at
my bypy project.
