### ISSUE TITLE
window size (resize) to absolute value and choice of axis

### ISSUE THREAD

**Issue by ershov** [kovidgoyal/kitty#6382]
Hi,
I have two questions:

1. Is there a way to specify the window size in absolute units? `resize-window` only accepts positive or negative increments.
2. Is there a way to ask Kitty to resize the window regardless the axis? If I have a split, the axis is known and I should't be required to specify it. But it's a required parameter and using a wrong axis fails the command.

**Comment by kovidgoyal** [comment]
1. no
2. no

**Comment by ershov** [comment]
Is there any specific reason for that or it would require significant effort to implement?

**Comment by kovidgoyal** [comment]
Layouts work by distributing available space between windows based on
biases. There is no concept of fixed size windows in kitty.
https://sw.kovidgoyal.net/kitty/layouts/

**Comment by ershov** [comment]
That's right. I was thinking of 'splits' layout. I thought it was fully manual. Does it support the 'bias' parameter?

**Comment by kovidgoyal** [comment]
Yes, every split has a bias associated with it.

**Comment by ershov** [comment]
`layout_action bias` unfortunately doesn't work for `splits` payout and it can't be changed dynamically. Maybe, because the Splits one doesn't override the `apply_bias` function? https://github.com/search?q=repo%3Akovidgoyal%2Fkitty%20apply_bias&type=code

I also tried a trick like `enabled_layouts splits,splits:bias=90` but it looks like the `bias` option is ignored by Splits layout.

I however noticed a useful feature: it created two separate 'splits' layouts between which I can cycle. (but it doesn't solve the problem of setting a pre defined split size via the `bias` option)

**Comment by ershov** [comment]
Hmm ok it does implement `modify_size_of_window` though.

I think in layout_action it needs to implement the action name `bias` or some special action for this layout.

**Comment by ershov** [comment]
Can you please have a loot at https://github.com/kovidgoyal/kitty/pull/6386

**Comment by ershov** [comment]
I also have a neat solution for no.2 (increase/decrease/set size of window regardless the slit axis). Would you be interested in a pull request for that?

**Comment by kovidgoyal** [comment]
On Thu, Jun 22, 2023 at 02:22:13AM -0700, Yury Ershov wrote:
> I also have a neat solution for no.2 (increase/decrease/set size of window regardless the slit axis). Would you be interested in a pull request for that?

Let's focus on one thing at a time.
