### ISSUE TITLE
Pasting via fake_input on awesomeWM does not work

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#639]
I have the following function in my window manager's config (awesomeWM) to trigger Shift-Insert (i.e. middle-mouse pasting), since it is not easily accesible on my keyboard layout:

```lua
local send_shift_insert = function()
  -- send shift-insert
  -- XXX: works not everywhere, e.g. not in Thunderbird or qutebrowser.
  root.fake_input("key_press", "Shift_L")
  root.fake_input("key_press", "Insert")
  root.fake_input("key_release", "Insert")
  root.fake_input("key_release", "Shift_L")
end
```

As you can see it has some comment already that is does not work everywhere, and also does not in kitty.

When using it (via modkey-v) nothing happens.
Using it again then inserts `^[[2~` (which reminds me of bracketed-paste, but I am not sure).
This happens with both zsh (my default, with config), and bash (default config).

Using `Fn-Shift-End` for the natural `Shift-Insert` works.

Any idea what happens there?

**Comment by kovidgoyal** [comment]
I have no idea what awesomewm uses to simulate fake input, sorry (probably the XTest extension, but I cannot be certain). The correct way to do this is to use either XKB rules to remap the key combination, which should work in all applications, or if that is too hard (XKB is an undocumented mess) simply assign whatever key stroke you like to paste in kitty.conf

**Comment by blueyed** [comment]
Yes, it is using XTest.

The following works: `xte 'keydown Shift_L' 'key Insert' 'keyup Shift_L'` (from the xautomation package, https://cgit.freedesktop.org/xcb/demo/tree/app/xte/xte.c).

As for my function, I could make it work by releasing the modifier key manually.  The problem appears to be that kitty sees `Super_L + Shift + Insert` otherwise (https://github.com/awesomeWM/awesome/issues/260#issuecomment-111717794).

Thanks for your other suggestions.
kitty is awesome, and I am slowly migrating to it I think (from rxvt-unicode, which I've patched myself to handle wide glyphs better, but kitty is very nice in this regard).

**Comment by kovidgoyal** [comment]
You're welcome :)
