### ISSUE TITLE
Keyboard based selections

### ISSUE THREAD

**Issue by VernonGrant** [kovidgoyal/kitty#6396]
Hi, 

First, thanks for all the hard work that made this awesome terminal emulator possible! 

## Idea overview

I don't have any knowladege of terminal emulator development and the limitations that they possess. I'm also not sure if this is already possible in some way, but basically:

**I would like a way to make selections using the keyboard and not the mouse**. Simular to the way Emacs handles selections via marks. Ideally, I would like to press a keyboard combination such at `Ctrl+space` to set the starting point of the selection. The cursor then becomes the ending point of the selection, so moving the cursor to the left or right should expand or shrinks the selection, depending on where the starting was placed. This would allow me to quickly make selections via keyboard to perform operations such as deletion, copying, replacements and more.

**Comment by kovidgoyal** [comment]
dup of #719
