### ISSUE TITLE
kitty can not use the mouse to select the text

### ISSUE THREAD

**Issue by bluehysteric** [kovidgoyal/kitty#6398]
kitty can not use the mouse to select the text, I use the mouse to select the text, the selected marker instantly disappeared

**Comment by kovidgoyal** [comment]
WOrks for me. Note that you cannot select text while new content is
being output to the screen. Press ctrl+shift+h to browse the scrollback
if that is what you want to do.

**Comment by bluehysteric** [comment]
> WOrks for me. Note that you cannot select text while new content is being output to the screen. Press ctrl+shift+h to browse the scrollback if that is what you want to do.

As an example, I ran pacman -Syu and waited for the output to finish, and the selection range disappeared about 1 second after I selected the text content.

**Comment by kovidgoyal** [comment]
Again, does not reproduce for me.
