### ISSUE TITLE
Can't use custom --type for hints anymore

### ISSUE THREAD

**Issue by trygveaa** [kovidgoyal/kitty#6403]
**Describe the bug**
I have a custom hints processor which accepts other values for the `--type` option than the default ones. This worked fine in 0.27.1, but doesn't work anymore after the rewrite to go.

**To Reproduce**
1. Run hints with a custom value for the `--type` option. E.g. `kitty -o 'map kitty_mod+y kitten hints --type emoji --customize-processing custom-hints.py'`
2. Press the mapped key to start hints.
3. Observe that nothing happens, the hints interface doesn't open and no error is printed.

**Screenshots**

**Environment details**
```
kitty 0.28.1 created by Kovid Goyal
Linux elaine 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64
Arch Linux 6.3.9-arch1-1 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config overrides:
  map kitty_mod+y kitten hints --type emoji --customize-processing custom-hints.py

Config options different from defaults:
Added shortcuts:
	kitty_mod+y →  kitten hints --type emoji --customize-processing custom-hints.py

Important environment variables seen by the kitty process:
	PATH                                /home/trygve/.pyenv/shims:/home/trygve/.pyenv/bin:/home/trygve/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/home/trygve/.dotnet/tools:/usr/lib/emscripten:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:./node_modules/.bin:/home/trygve/.yarn/bin:/home/trygve/go/bin
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                trygve
	XCURSOR_SIZE                        24
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            nb_NO.UTF-8
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      nb_NO.UTF-8
	XDG_VTNR                            1
	XDG_SESSION_ID                      41
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_GB.UTF-8
```

**Additional context**
It happens with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
If it worked before it would be an accident/bug. --type is supposed to
take only a fixed set of values. The error message not showing is indeed
a regression, that I will address when I have a moment. 

I assume your actual use case is passing command line arguments to your
custom script, this is done like this:

map f1 kitten hints --customize-processing whatever.py arg1 arg2

These will be available as extra_cli_args in the mark() function of your
script.
