### ISSUE TITLE
A few feature requests / questions

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#641]
I'm a new user to kitty and i love it so far. Here is a couple of feature requests / questions ( sorry if these are already solved / discussed )

1. Save the previous location of the kitty window, or set it to screen center in the kitty.conf file
2. Set a default session file in kitty.conf
3. Make the links to conf, layouts etc. clearer from the main web site ( now it's inside the text with very little contrast in the link )

Thanks

**Comment by kovidgoyal** [comment]
The link contrast has already been enhanced, but links to the session docs are in the sidebar of the main page already. I can add a link to the conf docs there as well.

I'm not keen on saving kitty window locations. These are often managed by the window manager, so they are not robust, and they lead to problems like if the saved location is on a monitor that no longer exists, the window might end up offscreen, or in unexpected places. If you want particular windows to be in particular places, use the --title and --class options and setup rules in your window manager based on WM_CLASS (I am assuming you are on Linux, no idea if macOS is capable of this kind of thing).
