### ISSUE TITLE
Problems with send_text when trying to jump to next word

### ISSUE THREAD

**Issue by tymm** [kovidgoyal/kitty#6411]
**Describe the bug**
I'm currently in the process of customizing my keyboard shortcuts on MacOS with karabiner/goku.
While doing so I noticed that certain shortcuts are not working in Kitty while working everywhere else.

For example jumping back a word didn't initially work in Kitty but I was able to make it work with:
```map alt+left send_text all \x1B\x62```

However some things just don't seem possible like for example moving to the next word or deleting the next word:
```
# Jumping to the next word
map alt+right send_text all \x1B\x66
```

Also `kitty -o clear_all_shortcuts=yes kitty +kitten show_key` seems to not give me the correct codes when I'm trying to find out the codes required.

**To Reproduce**
1. Install karabiner elements and goku and add the following minimal karabiner.edn file:
```
{
 :layers {
   :tab-mode {:key :tab}
 }

  :main [
   {:des "Tab mode"
    :rules [:tab-mode
             [:f :!Oright_arrow] ; move to previous word
             [:b :!Oleft_arrow] ; move to next word
    ]
   }
  ]
}
```
2. Use a minimal kitty.conf and add the following:
```
# Move to previous word
map alt+left send_text all \x1B\x62
# Move to next word
map alt+right send_text all \x1B\x66
```
3. Observe that jumping backward with `tab+b` works while jumping forward with `tab+f` doesn't. Same problem exists when trying to add a shortcut that deletes a word forward and backward (backward works while forward doesn't).

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		13.4.1 BuildVersion:		22F82
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/tymm/.config/kitty/kitty.conf

Config options different from defaults:
Added shortcuts:
	opt+left →  send_text all \x1B\x62
	opt+right →  send_text all \x1B\x66

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                tymm
```

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in debugging whatever hackery karabiner
and goku do. You can run kitty with --debug-input and see what key
events it is getting and map those however you like using send_text.

**Comment by tymm** [comment]
@kovidgoyal since my karabiner shortcuts for e.g. moving a word forward work everywhere except in Kitty, I was under the assumption that it can't be the fault of karabiner/goku but looks like you disagree.

**Comment by kovidgoyal** [comment]
I have seen dozens of these types of hacks over the years. They all inject themselves in between the kernel/display server and the application and remap things in hacky ways and break downstream applications. I am not going to waste anymore of my life on them. As I said, use kitty --debug-input see what actual input events it is getting and remap them however you like.
