### ISSUE TITLE
I cant load kitty

### ISSUE THREAD

**Issue by bryant-the-coder** [kovidgoyal/kitty#6412]
I cant load kitty on Endeavour OS

```
~ 
 ╰─λ kitty
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  7
  Serial number of failed request:  277
  Current serial number in output stream:  278
```

How to solve?

**Comment by kovidgoyal** [comment]
No idea, that error doesnt contain anything useful, beyond that the X
server on your machine is out of resources. You can try running
with --debug-rendering you might get more information. You can also try
using software rendering via the appropriate mesa env vars.
