### ISSUE TITLE
Hyperlinked Grep isn't opening links with the wrong editor

### ISSUE THREAD

**Issue by matthewmturner** [kovidgoyal/kitty#6414]
**Describe the bug**
I'm trying to use Hyperlinked Grep with the following `open-actions.conf` which will open my editor, [Helix](https://github.com/helix-editor/helix), but whenever I `ctrl` + `shift` it opens an Xcode editor instead.  

Is there something wrong with my configuration or is this a bug?

```
# Open any file with a fragment in Helix, fragments are generated
# by the hyperlink_grep kitten and nothing else so far.
protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current hx +${FRAGMENT} ${FILE_PATH}

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=overlay --cwd=current hx ${FILE_PATH}
``` 

**To Reproduce**
1. Use the above `open-action.conf`
2. Use `kitty +kitten hyperlinked_grep something`
3. `ctrl` + `shift` then click a relevant line
4. The specified editor in `open-action.conf` is not used

**Screenshots**

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin MacBook-Pro 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		13.3 BuildVersion:		22E252
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/matth/.config/kitty/kitty.conf

Config options different from defaults:
bold_font        DejaVu Sans Mono for Powerline Bold Oblique
bold_italic_font DejaVu Sans Mono for Powerline Oblique
font_family      DejaVu Sans Mono for Powerline Bold
italic_font      DejaVu Sans Mono for Powerline Book

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/homebrew/bin/fish
	USER                                matth

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Set the EDITOR env var *in the environment in which kitty is run*. Or
set editor in kitty.conf.

**Comment by matthewmturner** [comment]
@kovidgoyal I already have 

```
editor hx
```

in my kitty.conf

**Comment by kovidgoyal** [comment]
Use absolute paths and use ${EDITOR} in your open-actions.conf

**Comment by matthewmturner** [comment]
so now I have 

```
editor /opt/homebrew/bin/hx
```

and

```
# Open any file with a fragment in Helix, fragments are generated
# by the hyperlink_grep kitten and nothing else so far.
protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current ${EDITOR} +${FRAGMENT} ${FILE_PATH}

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=overlay --cwd=current ${EDITOR} ${FILE_PATH}
```

And I've restarted kitty but still having the issue.  Sorry if I'm missing something obvious

**Comment by kovidgoyal** [comment]
That will work. Perhaps you have not put the open-actions.conf file in the right path or with the right name or the permissions are incorrect. run kitty from a terminal and see if any errors are printed to its stdout. Or better run kitty from source and debug the issue for yourself, see the get_editor() function in the kitty source code.
