### ISSUE TITLE
Installing for ubuntu

### ISSUE THREAD

**Issue by vushu** [kovidgoyal/kitty#642]
How to install it correctly for ubuntu I have used the way binary install from
https://sw.kovidgoyal.net/kitty/binary.html
, but no icons are displayed, I am using version ubuntu 18.04

![screenshot from 2018-06-16 16-13-16](https://user-images.githubusercontent.com/1658625/41499423-486cb820-7180-11e8-9ce9-b9b77defed41.png)

**Comment by kovidgoyal** [comment]
The installation does not do any integration withe OS, you have to do that manually. See #595 for example

**Comment by verhovsky** [comment]
`sudo apt install kitty`

**Comment by elgallo** [comment]
> `sudo apt install kitty`

E: Unable to locate package kitty

**Comment by verhovsky** [comment]
@elgallo it's on Ubuntu 18.10+

https://packages.ubuntu.com/disco/kitty

**Comment by ProgrammingLife** [comment]
Where is it now?

**Comment by verhovsky** [comment]
It's still there `sudo apt install kitty`

https://packages.ubuntu.com/focal/kitty

**Comment by dimanyc** [comment]
getting `Unable to locate package kitty` on 18.04

**Comment by trygveaa** [comment]
@dimanyc: As @verhovsky said, it's in **18.10+**, so 18.04 is too old. Kitty wasn't packaged in Ubuntu 18.04. For that version you have to see https://sw.kovidgoyal.net/kitty/binary.html.
