### ISSUE TITLE
Support of X session manager

### ISSUE THREAD

**Issue by lcheylus** [kovidgoyal/kitty#6420]
I would like to save my opened Kitty terminals in my X session to restart them after login. I am using XFCE as window manager and X session management is handled via the `xfce4-session` program.

To support X session management, Kitty must support XSMP Protocol (X Session Management Protocol), see https://en.wikipedia.org/wiki/X_session_manager for detailed explanations.

Other Linux terminals as XFCE-Terminal or Gnoe Terminal already supports X session management

**Comment by kovidgoyal** [comment]
This is not something worth the effort to me. Patches welcome.

**Comment by kovidgoyal** [comment]
Closing issue, feel free to ask for guidance if you want to work ona
patch yourself.
