### ISSUE TITLE
Native tabs on MacOS

### ISSUE THREAD

**Issue by ildus** [kovidgoyal/kitty#6421]
Hi,

Recently I tried to add native tabs to kitty on MacOS and it was surprisingly easy even without any knowledge in cocoa. It works in the way that OS windows become tabs. With  few extra menu items it's also easy to move between them.

I wonder why it was not implemented since it looks really nice and I prefer them to the kitty tabs.  I understand it's not so easy as in the patch (there are problems with the selection of text), but it seems as a nice feature.

The patch looks like this (it is quite silly but shows only changes I made to enable tabs).
```
diff --git a/glfw/cocoa_window.m b/glfw/cocoa_window.m
index 1a750f952..1e8b1c0f0 100644
--- a/glfw/cocoa_window.m
+++ b/glfw/cocoa_window.m
@@ -1666,7 +1666,7 @@ - (instancetype)initWithGlfwWindow:(NSRect)contentRect
     self = [super initWithContentRect:contentRect styleMask:style backing:backingStoreType defer:NO];
     if (self != nil) {
         glfw_window = initWindow;
-        self.tabbingMode = NSWindowTabbingModeDisallowed;
+        self.tabbingMode = NSWindowTabbingModePreferred;
     }
     return self;
 }
diff --git a/kitty/cocoa_window.m b/kitty/cocoa_window.m
index 8608780dd..02e293335 100644
--- a/kitty/cocoa_window.m
+++ b/kitty/cocoa_window.m
@@ -642,6 +642,12 @@ - (BOOL)openFileURLs:(NSPasteboard*)pasteboard
                    keyEquivalent:@""];
 
     [windowMenu addItem:[NSMenuItem separatorItem]];
+    [windowMenu addItemWithTitle:@"Select Next Tab"
+                          action:@selector(selectNextTab:)
+                   keyEquivalent:@""];
+    [windowMenu addItemWithTitle:@"Select Previous Tab"
+                          action:@selector(selectPreviousTab:)
+                   keyEquivalent:@""];
     MENU_ITEM(windowMenu, @"Show Previous Tab", previous_tab);
     MENU_ITEM(windowMenu, @"Show Next Tab", next_tab);
     [[windowMenu addItemWithTitle:@"Move Tab to New Window"
```

Also the screenshot:

<img width="1024" alt="Screenshot 2023-07-04 at 19 28 17" src="https://github.com/kovidgoyal/kitty/assets/314246/0a1bb291-455f-4000-a1a4-c3d060bb00d4">

**Comment by kovidgoyal** [comment]
I am afraid I am not going to platform specific tab implementations in
kitty.
