### ISSUE TITLE
fcitx5 chinese input selection box not rendered in kitty

### ISSUE THREAD

**Issue by denppa** [kovidgoyal/kitty#6423]
**Describe the bug**
The fcitx5 chinese IME character selection box is not rendered in kitty.

**To Reproduce**
1. Install fcitx5, chinese IME
2. Switch to Chinese input
3. type in kitty
4. The chinese characters do show up, but there is no selection menu

**Screenshots**
Sorry, no screenshot utility yet

**Environment details**
```
kitty 0.28.1 running in wayland mode
Fedora 38
Sway 1.8.1
fcitx5 5.0.23
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
```

**Additional context**

The character selection box works in firefox and various flatpak packages.

**Comment by kovidgoyal** [comment]
kitty on X11 supports only IBUS. You need to use fcitx5 ibus compat mode
or switch to wayland.

**Comment by denppa** [comment]
> kitty on X11 supports only IBUS. You need to use fcitx5 ibus compat mode or switch to wayland.

Thanks for the reply, I am using wayland session though, does kitty support fcitx5 in wayland or also only ibus in wayland?

**Comment by kovidgoyal** [comment]
kitty supports wayland text input protocol it does not support any
specific backend there

**Comment by denppa** [comment]
I think it is a sway problem, the following info is for future visitors (thanks @kovidgoyal):

https://www.reddit.com/r/swaywm/comments/y20llf/fcitx5_input_method_not_showing_popup_box/

Arch aur pkg sway-im
