### ISSUE TITLE
Please add better method of getting colors

### ISSUE THREAD

**Issue by mahyarmirrashed** [kovidgoyal/kitty#6425]
**Is your feature request related to a problem? Please describe.**
Please make a better interface for getting colors from Kitty remote control. It is really frustrating to have to do something like `kitty @ get-colors | grep '^background' | awk '{print $2}' to just get the current background color.

**Describe the solution you'd like**
Should be simple like `kitty @ get-colors background` similar to how `kitty @ set-colors background=red` works.

**Describe alternatives you've considered**
I have provided the BaSH script that does that but, it is not portable because I might have to change it based on what shell I am using, Please create this feature into Kitty.

**Additional context**
I am willing to make this change myself. Just show me the file where it is and I'll create the PR .

**Comment by kovidgoyal** [comment]
I'm afraid I dont find kitty @ get-colors | grep '^background' | cut -d" " -f2 at all difficult. And dont write a bash script write your script in POSIX sh then you wont need to ever change it on any system.

**Comment by mahyarmirrashed** [comment]
The beauty of open source is that it provides room for improvements from different perspectives, and this suggestion is just from one such perspective. While `kitty @ get-colors | grep '^background' | cut -d" " -f2` might be simple for seasoned users like us, it can be a bit intimidating for newcomers or people with less scripting experience.

Since I am willing to put in the work to create this feature, it may be a win-win situation for both the experienced users, who wouldn't find any change in their workflow, and the newer ones, who would find it easier to interact with Kitty. Plus, it would be an additional feature in Kitty's repertoire. Who doesn't love options?

Looking forward to your guidance on where I can make this improvement.

**Comment by kovidgoyal** [comment]
On Sat, Jul 08, 2023 at 03:47:26PM -0700, Mahyar Mirrashed wrote:
> The beauty of open source is that it provides room for improvements from different perspectives, and this suggestion is just from one such perspective. While `kitty @ get-colors | grep '^background' | cut -d" " -f2` might be simple for seasoned users like us, it can be a bit intimidating for newcomers or people with less scripting experience.

I have been doing open source for 30 years. You don't need to explain its
beauty or otherwise to me. kitty isn't aimed at novices, and the remote
control part of it even less so. As such, I don't see a real need for
this.

> 
> Since I am willing to put in the work to create this feature, it may be a win-win situation for both the experienced users, who wouldn't find any change in their workflow, and the newer ones, who would find it easier to interact with Kitty. Plus, it would be an additional feature in Kitty's repertoire. Who doesn't love options?

You might be willing to put in the initial work, but I will be the one
maintaining it in perpetuity, guiding you and reviewing the PR. All of
that takes non-trivial effort.

That said, since you seem to be so keen on this, I will accept the PR. 
The relevant code will be in get_colors.py and you will need to create
code on the Go side as well, see hwo set_colors.py works.
