### ISSUE TITLE
[Linux] can't open config file 

### ISSUE THREAD

**Issue by ccaneke** [kovidgoyal/kitty#6426]
**Describe the bug**
I can't open the config file using [ctrl+shift+f2](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Edit-config-file)  

**To Reproduce**
1. Install kitty via dnf
2. Open kitty
3. Try to open the config file using the shortcut ctrl+shift+f2

I looked in `~/.config/kitty` and there's no kitty.conf file.
There should be an alternative way to open or create kitty.conf.

__Output of kitty --version__
```
kitty 0.26.5 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
Your version of kitty is ancient, update. And th econfig is a plain text file open it in any editor you like.

**Comment by ccaneke** [comment]
@kovidgoyal Well I'm on fedora 37, that's why I have an older version of kitty. I can't find the config file. It's not in `~/.config/kitty`. Where can I find it?

**Comment by SolitudeSF** [comment]
if its not there - you create it. example config is usually located at `/usr/share/examples/kitty/kitty.conf` or `/usr/share/doc/kitty/kitty.conf`, whatever your distribution prefers. but in case of fedora they decided to not include it at all.
