### ISSUE TITLE
Add support for under-dotted and under-dashed

### ISSUE THREAD

**Issue by FalcoGer** [kovidgoyal/kitty#6427]
**Is your feature request related to a problem? Please describe.**
neovim (and possibly vim, too) offers the option to use underdotted or underdashed in gui mode, which is also available in the terminal with `set termguicolors`. I would like to use that feature for highlighting texts, such as search texts or references found by the coc plugin.

Currently only underline, double underline and curly underline are supported. When trying to use underdashed or underdotted, an undercurl line is rendered instead.

This currently looks like this:

![image](https://github.com/kovidgoyal/kitty/assets/16250196/56ef3472-2d34-45b0-8667-50c292f4d948)

**Describe the solution you'd like**
Implement support for the relevant escape codes. This test example can be used in bash.

```bash
printf '\e[4:1mHello, underline!
\e[m\e[4:2mHello, double-underline!
\e[m\e[4:3mHello, under-curl!
\e[m\e[4:4mHello, under-dotted!
\e[m\e[4:5mHello, under-dashed!\e[m\n'
```

It should look like this:
![image](https://user-images.githubusercontent.com/693212/149948736-7ae98ece-f1bb-4b2d-b743-d2da3680eaba.png)

**Describe alternatives you've considered**
None.

**Additional context**
Running Ubuntu Mate 22.04
Kitty version 0.21.2
Font in use is MesloLGS NF

**Comment by kovidgoyal** [comment]
Not something I care about personally but a PR is welcome.

**Comment by FalcoGer** [comment]
Seems like the ancient ubuntu repositories were holding me back yet again.
On a hunch I compiled the latest version, and it works just fine there.
