### ISSUE TITLE
Kitty not receiving focus when opened from Gnome Dock under Wayland

### ISSUE THREAD

**Issue by molaeiali** [kovidgoyal/kitty#6428]
Kitty is not receiving focus and needs a mouse click when opened from Gnome's Dock if there is already another window open that has focus under Wayland,

**To Reproduce**
1. Open any other application under Gnome-Wayland, say Firefox for example and make sure it has the focus
2. Open kitty from Gnome's Dock
3. Start typing and see it types inside Firefox not kitty

**Screenshots**
![Screenshot from 2023-07-08 12-52-16](https://github.com/kovidgoyal/kitty/assets/12999682/1521ccf5-27ed-44f5-929e-3e0deec30443)

**Environment details**
kitty 0.28.1 created by Kovid Goyal
Linux T490 6.4.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 18:35:54 +0000 x86_64
Arch Linux 6.4.2-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/ali/.config/kitty/kitty.conf

Config options different from defaults:
allow_hyperlinks      0
background_opacity    0.8
initial_window_height (600, 'px')
initial_window_width  (1000, 'px')
remember_window_size  False
tab_bar_style         powerline
term                  xterm
Changed shortcuts:
	kitty_mod+enter →  launch --cwd=current

Important environment variables seen by the kitty process:
	PATH                                /usr/lib/ccache/bin/:/usr/local/bin:/usr/bin:/home/ali/.local/myapps/android-sdk/tools:/home/ali/.local/myapps/android-sdk/platform-tools:/home/ali/.local/myapps/flutter/bin:/home/ali/.local/bin:/home/ali/.local/go/bin:/home/ali/.local/npm/config/bin/:/usr/local/sbin:/home/ali/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                ali
	XDG_DATA_DIRS                       /home/ali/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland

**Comment by kovidgoyal** [comment]
That is a bug in mutter.

**Comment by molaeiali** [comment]
Are you sure? It doesn't happen with any other application for me

**Comment by kovidgoyal** [comment]
yes, dup of #6234

**Comment by molaeiali** [comment]
Thanks, was searching in mutter issues, there's a link in the dup, i'll follow from there
