### ISSUE TITLE
Unicode input menu don't get displayed in wayland

### ISSUE THREAD

**Issue by ohjunseung** [kovidgoyal/kitty#6429]
**Describe the bug**
Unicode input menu don't get displayed in wayland. Default gnome unicode input get invoked instead.

**To Reproduce**
1. Use wayland
2. Press Ctrl+Shift+u

**Screenshots**
in wayland
![wayland](https://github.com/kovidgoyal/kitty/assets/53179765/a96f5f32-d1e1-4ba1-9af6-6028edc48efd)

in xorg
![xorg](https://github.com/kovidgoyal/kitty/assets/53179765/b70bb11f-7e61-40c3-aadf-f23fca20ce9e)

**Environment details**
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Linux cyberthink-pc 6.3.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul  2 13:17:31 UTC 2023 x86_64
S
Kernel 6.3.11-200.fc38.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: True
Paths:
  kitty: /home/cyberthink/.local/kitty.app/bin/kitty
  base dir: /home/cyberthink/.local/kitty.app/lib/kitty
  extensions dir: /home/cyberthink/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/cyberthink/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity        0.92
font_family               Cascadia Code PL
text_composition_strategy legacy
Changed shortcuts:
	kitty_mod+enter →  launch --cwd=last_reported
	kitty_mod+t →  launch --cwd=last_reported --type=tab
Colors:
	color1                    #ff5555   
	color10                   #55ff55   
	color11                   #ffff55   
	color12                   #5555ff   
	color13                   #ff55ff   
	color14                   #55ffff   
	color2                    #55ff55   
	color3                    #ffff55   
	color4                    #5555ff   
	color5                    #ff55ff   
	color6                    #55ffff   
	color7                    #bbbbbb   
	color8                    #545454   
	color9                    #ff5555   
	cursor                    #bbbbbb   
	foreground                #ffffff   
	selection_background      #b5d5ff   

Important environment variables seen by the kitty process:
	PATH                                /home/cyberthink/.cargo/bin:/home/cyberthink/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                cyberthink
	XDG_DATA_DIRS                       /home/cyberthink/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

**Comment by kovidgoyal** [comment]
That will be because your window manager is intercepting that key press.
Stop it from doing that or assign a different key for that action in
kitty.conf.

**Comment by giggio** [comment]
For anyone looking for this, you do it like this:

```bash
gsettings set org.freedesktop.ibus.panel.emoji unicode-hotkey "['<Control><Super><Shift>u']"
```

Found at: https://askubuntu.com/a/1510488/832580
