### ISSUE TITLE
0.29.0 Cannot Resize when hide_window_decorations is enabled

### ISSUE THREAD

**Issue by Pat-Ayres** [kovidgoyal/kitty#6436]
**Describe the bug**
After installing 0.29.0 I am unable to resize the window when `hide_window_decorations` is enabled.  When mousing over a corner, the cursor does not change to the resize icon.  Using keyboard commands to snap to a zone moves the window, but does not resize it to fit the zone.  I can enter full screen mode with `⌃+⌘+f`, but the window size remains the same with extra space filled as a border.

**To Reproduce**
1. Set `hide_window_decorations yes` in kitty.conf
2. Start kitty
3. Attempt to resize the window
4. Window never changes size

**Screenshots**
Windowed Mode
<img width="961" alt="image" src="https://github.com/kovidgoyal/kitty/assets/7363962/1ae1608e-c1d2-4d34-a9f5-e61b45ecf115">

Fullscreen Mode
<img width="1920" alt="image" src="https://github.com/kovidgoyal/kitty/assets/7363962/54c76b37-276a-4309-a820-aa8d8b7add18">

**Environment details**
```
kitty 0.29.0 (e2b5c6688d) created by Kovid Goyal
Darwin PE-Y2W24YV9Y4 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.4.1 BuildVersion:		22F82
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/payres/.config/kitty/kitty.conf

Config options different from defaults:
hide_window_decorations 1

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                payres

```

**Additional context**
I am able to resize as expected when `hide_window_decorations` is not set. None of the other config options I use seemed to interfere, but I disabled all of them anyway to get a minimal reproduction.

**Comment by kovidgoyal** [comment]
yes, now hide_window_decorations=y hides the shadow as well. use
hide_window_decorations=titlebar-only That it didnt hide the shadows
before was a bug.

**Comment by jannis-baum** [comment]
I have the same problem; I want the macOS titlebar and window borders to be hidden (`hide_window_decorations=yes`) but still be able to resize the window like I always have before 0.29.0. With `hide_window_decorations=yes` not even the [`toggle_maximized` action](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Toggle-maximized) works anymore.

Setting `hide_window_decorations=titlebar-only` fixes the resizing problem but creates annoying macOS window borders so this is not a good option for me. Is there any other way to have both OS window resizing and hidden borders like before 0.29.0 that I'm missing?

> yes, now hide_window_decorations=y hides the shadow as well. [...]
> That it didnt hide the shadows before was a bug.

How do shadows relate to this?

**Comment by kovidgoyal** [comment]
Read https://github.com/kovidgoyal/kitty/blob/master/docs/changelog.rst#0291-future

**Comment by gibfahn** [comment]
I hit this because I use Hammerspoon to resize windows, and that no longer works with `hide_window_decorations yes`, even though I'm not actually dragging anything.

So basically tl;dr of this thread:

- Change `hide_window_decorations yes` to `hide_window_decorations titlebar-only` to get resizing back (but you'll have rounded corners)
- Once `0.29.1` (or whatever the next version of Kitty is), change to `hide_window_decorations titlebar-and-corners`, which will let you resize the window, but still hide the rounded corners

The rounded corners are pretty minimal, and on my screen don't hide anything, just cut off the corner of the leftmost tab's title, which is fine.

**Comment by badrbouslikhin** [comment]
I'm having trouble getting `hide_window_decorations titlebar-and-corners` to work properly with version 0.29.1.
<img width="3120" alt="Screenshot 2023-07-17 at 11 32 14" src="https://github.com/kovidgoyal/kitty/assets/7818591/e34a2402-af0f-4f0b-b172-9b538e061bae">

`hide_window_decorations titlebar-only` works well.
<img width="3120" alt="Screenshot 2023-07-17 at 11 32 29" src="https://github.com/kovidgoyal/kitty/assets/7818591/26859633-f156-40c0-9f9e-c8da6373973d">

**Comment by kovidgoyal** [comment]
Works for me with

kitty -o hide_window_decorations=titlebar-and-corners

**Comment by kovidgoyal** [comment]
Remember to restart kitty not just reload the config.

**Comment by badrbouslikhin** [comment]
My mistake, that was the issue.

**Comment by gibfahn** [comment]
>Once 0.29.1 (or whatever the next version of Kitty is), change to `hide_window_decorations titlebar-and-corners`, which will let you resize the window, but still hide the rounded corners

Confirmed that this works as expected in 0.29.2. Thanks for the fix!
