### ISSUE TITLE
Text ghosting in 0.29.0 on macOS

### ISSUE THREAD

**Issue by Frederick888** [kovidgoyal/kitty#6439]
**Describe the bug**

Text ghosting when resizing the window, opening new tabs, etc. if background opacity is configured.

**To Reproduce**
1. Configure `background_opacity 0.85` and `macos_traditional_fullscreen yes`
2. Start Kitty and have a few lines of text
3. Switch between windowed mode and fullscreen mode
4. Can see text ghosting

It can be reproduced in other ways too, but I found the ghosting most obvious this way.

**Screenshots**

https://github.com/kovidgoyal/kitty/assets/4507647/0d2b0e31-399c-4807-a303-568711f088fb

(There was ghosting after it went back to windowed mode too. With the video compression it wasn't very clear.)

**Environment details**
```
kitty 0.29.0 (e2b5c6688d) created by Kovid Goyal
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
ProductName:		macOS ProductVersion:		13.4.1 BuildVersion:		22F82
Frozen: True
Paths:
  kitty: /Users/frederick/Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Users/frederick/Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/frederick/Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/frederick/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity                 0.85
bold_font                          BitstromWera Nerd Font Mono
bold_italic_font                   BitstromWera Nerd Font Mono
clipboard_control                  ('write-clipboard', 'write-primary', 'no-append')
copy_on_select                     clipboard
enable_audio_bell                  False
font_family                        BitstromWera Nerd Hybrid Font Mono
font_size                          12.0
initial_window_height              (900, 'px')
initial_window_width               (1440, 'px')
italic_font                        BitstromWera Nerd Font Mono
macos_option_as_alt                3
macos_quit_when_last_window_closed True
macos_traditional_fullscreen       True
mouse_hide_wait                    3.0
shell                              /usr/local/bin/zsh --login --interactive
strip_trailing_spaces              always
update_check_interval              0.0
Changed shortcuts:
	kitty_mod+h →  previous_tab
	kitty_mod+l →  next_tab
Colors:
	background                         #191919   
	color0                             #191919   
	color1                             #f3005f   
	color10                            #97e023   
	color11                            #dfd561   
	color12                            #9c64fe   
	color13                            #f3005f   
	color14                            #57d1ea   
	color15                            #f6f6ee   
	color2                             #97e023   
	color3                             #fa8419   
	color4                             #9c64fe   
	color5                             #f3005f   
	color6                             #57d1ea   
	color7                             #c4c4b5   
	color8                             #615e4b   
	color9                             #f3005f   
	cursor                             #f6f6ec   
	foreground                         #c4c4b5   
	selection_background               #343434   
	selection_foreground               #191919   

Important environment variables seen by the kitty process:
	PATH                                /Users/frederick/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_AU.UTF-8
	SHELL                               /bin/zsh
	USER                                frederick
```

**Additional context**

I can reproduce the issue with only `background_opacity 0.85` in my config.

**Comment by Frederick888** [comment]
I'm still seeing this in 0.29.1.

<img width="319" alt="image" src="https://github.com/kovidgoyal/kitty/assets/4507647/d9a22258-4cd5-4911-af48-328206f364eb">

**Comment by kovidgoyal** [comment]
I need some steps to repro it in that case.

**Comment by Frederick888** [comment]
@kovidgoyal The same steps can still be used to reproduce it.

Resizing the window also works (probably simpler):

1. This time I have only `background_opacity 0.85`, no `macos_traditional_fullscreen yes`
2. Type a few lines
3. Resize the window
4. Clear the lines

https://github.com/kovidgoyal/kitty/assets/4507647/94a12c07-19cd-4d89-ae11-c3a1558fe4c7

**Comment by kovidgoyal** [comment]
Does not repro for me with that. You did restart kitty after updating
yes?

**Comment by Frederick888** [comment]
> You did restart kitty after updating yes?

Yes. I checked the app name in menu bar was no longer Kitty (and my regular config has `macos_quit_when_last_window_closed yes`, so after start Kitty 0.28.1 -> upgrade -> vim change config -> quit -> start Kitty it's a new instance).

Maybe it's a platform thing? I'm using a 2019 Intel i7 MBP. GPUs are AMD 5300M and Intel 630.

**Comment by kovidgoyal** [comment]
I am testing on an M1 Air (Ventura). What version of macOS?

**Comment by Frederick888** [comment]
> I am testing on an M1 Air (Ventura). What version of macOS?

`13.4.1 (c) (22F770820d)`

**Comment by kovidgoyal** [comment]
Just to confirm that this is coming from the Cocoa shadow layer for you
as well, does the ghosting go away if you run kitty as

kitty -o hide_window_decorations=y

This should hide the shadow, the ghosting you see is basically the
shadow of the text which for some reason cocoa decides to draw and then
not invalidate when the window is resized. I worked around it by forcing
invalidation with a further resize.

**Comment by Frederick888** [comment]
Yes! With `hide_window_decorations=y` the issue is gone. Tested both resizing the window and switching on and off traditional full screen.

**Comment by kovidgoyal** [comment]
So really the question is why is the code in cocoa_set_shadow() under if
(has_shadow) not working for you. Try changing the +1 to -1 and the -1
to +1

**Comment by Frederick888** [comment]
> So really the question is why is the code in cocoa_set_shadow() under if (has_shadow) not working for you. Try changing the +1 to -1 and the -1 to +1

No it still happens after changing those two lines.

Just to avoid any miscommunication what I did was:
1. Git clone
2. Apply
  ```diff
  diff --git a/kitty/cocoa_window.m b/kitty/cocoa_window.m
  index 1d32979..bcfcfa5 100644
  --- a/kitty/cocoa_window.m
  +++ b/kitty/cocoa_window.m
  @@ -745,10 +745,10 @@ - (BOOL)openFileURLs:(NSPasteboard*)pasteboard
       if (has_shadow) {  // invalidate the shadow to clear the ghosting
           [window invalidateShadow];
           // invalidateShadow does not work with layer backed views, see http://www.openradar.me/34184270
           // so do the frame resize dance to force AppKit to invalidate the shadow even with the layer
  -        [window setFrame:NSMakeRect(NSMinX(window.frame), NSMinY(window.frame), NSWidth(window.frame)+1, NSHeight(window.frame)) display:NO animate:NO];
           [window setFrame:NSMakeRect(NSMinX(window.frame), NSMinY(window.frame), NSWidth(window.frame)-1, NSHeight(window.frame)) display:NO animate:NO];
  +        [window setFrame:NSMakeRect(NSMinX(window.frame), NSMinY(window.frame), NSWidth(window.frame)+1, NSHeight(window.frame)) display:NO animate:NO];
       }
       return current;
   }
  ```
3. `make`
4. Quit Kitty (well just to be safe)
5. `./kitty/launcher/kitty` from Terminal

**Comment by kovidgoyal** [comment]
Hmm then I am at a loss, the only solution is to once again disable the
shadow for transparent windows.

**Comment by Shirk** [comment]
Looks like the fix now causes this to happen on macOS in 0.29.1 without maximising / resizing - minimize & restore does it for me.

**Comment by kovidgoyal** [comment]
On Fri, Jul 21, 2023 at 04:50:45AM -0700, Renée Köcher wrote:
> Looks like the fix now causes this to happen on macOS in 0.29.1 without maximising / resizing - minimize & restore does it for me.

And what macOS version/GPU etc are you using?

**Comment by Shirk** [comment]
> And what macOS version/GPU etc are you using?

Completely forgot to add these.. sorry

13.4.1 (c) (22F770820d) on a 2020 M1 macBook Air

**Comment by kovidgoyal** [comment]
Well, I have limited patience for Apple bugs, so I have just reverted
the change to allow transparent windows to have shadows.
