### ISSUE TITLE
Support `inactive_cursor_shape` option

### ISSUE THREAD

**Issue by vollowx** [kovidgoyal/kitty#6457]
First of all, Kitty is really such a nice terminal, and I hope it can get better and better!

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add this option, then we can make cursor shape in both inactive and active status look the same, or somebody maybe wants to customize them into something other.

**Describe alternatives you've considered**
Make inactive cursor shape the same to `cursor_shape`.

**Additional context**
No.

**Comment by kovidgoyal** [comment]
Not something I care about personally, but patches are welcome.
