### ISSUE TITLE
Can we have configurable splits bias?

### ISSUE THREAD

**Issue by ftabaro** [kovidgoyal/kitty#6459]
I am trying to setup a session with the splits layout. I would like to have configurable splits dimensions so that I could say something like

```
launch bash
launch --location=hsplit;bias:30 bash
launch --location=vsplit bash
launch --location=hsplit bash
```

This should result in a 4 panels sessions with the top one taking only 30% of the window height.

Something like this
```
+-----------+
|___________|
|     |_____|
|     |     |
+-----------+
```

EDITS: get the diagram right :)

**Comment by kovidgoyal** [comment]
Use the resize directive to resize the splits however you like after
creating them.
