### ISSUE TITLE
selection highlighting: allow styles (reverse mode)

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#646]
Currently you can define `selection_foreground` and `selection_background` to configure the display of selected text.

I would like to be able to display it "inversed" (in "reverse" mode), which could be achieved by a new `selection_style` setting, and the following config:

```conf
selection_foreground = None
selection_background = None
selection_style = reverse
```

``selection_style`` should accept a list then, so that `selection_style =
reverse,underline` would also work.

This would make it work seamlessly with different color themes (light and dark).

btw: is it possible already to change options for the current kitty instance?  This could be used to dynamically change the selection fg/bg settings then when switching color profiles.
I know that there are a few nice xterm protocol extensions already, but this does not seem to be among them.

**Comment by kovidgoyal** [comment]
I personally hate reverse video for selections, so I am not interested in implementing this, but patches for an option are welcome. You can simply use a color pair that works with both light and dark color schemes, like say, medium blue with white or black text. Or change the selection colors with your theme.

And see the kitty FAQ for how to change all colors in running kitty instances. There do exist escape codes to do it, but you can do much more using the kitty remote control facility.

**Comment by jsomedon** [comment]
Selection with reversed fore-background color let your code syntax highlighted even when you select them. I guess users want this feature mainly for this reason.. Would be really beneficial if you bring this feature in.

**Comment by page-down** [comment]
I tried the latest selection reverse video feature and found that the text color seems to be the same as the background color.

> Setting both of these to none will cause a "reverse video" effect for selections ...

```shell
kitty --config=NONE -o selection_foreground=none -o selection_background=none
```

![](https://user-images.githubusercontent.com/57713011/144753660-3ecb28db-5e48-4449-8d70-36b6f3a9e27a.png)

Can be reproduced under macOS and Linux.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/2d66e37dcbf1e24c26cd324c03047c23c00ed058
