### ISSUE TITLE
Customizing click behavior for opening links

### ISSUE THREAD

**Issue by archelaus** [kovidgoyal/kitty#6464]
**Description:**
I'm looking to configure the click behavior for URLs in a specific way. Is it possible to configure Kitty to open a custom script on a single click but to retain the default behavior of opening links in the default web browser when I hold the Ctrl key?

If there are any configuration options or settings that can help achieve these behaviors, I would greatly appreciate any guidance or instructions on how to set them up.

**Comment by kovidgoyal** [comment]
see https://sw.kovidgoyal.net/kitty/conf/#mouse-actions

**Comment by archelaus** [comment]
What action I'm supposed to use? I'm a bit lost, I've skimmed through the documentation already
