### ISSUE TITLE
0.29.0 and hide_window_decorations exhibit faulty behaviour with window resizing through third party applications.

### ISSUE THREAD

**Issue by jamesb93** [kovidgoyal/kitty#6470]
**Describe the bug**
Since upgrading to 0.29.0 [Rectangle](https://rectangleapp.com/) on macOS fails to change the window width when a kitty configuration has `hide_window_decorations yes` in the configuration. I can reproduce the behaviour also with hammerspoon when trying to resize through their API. I wrote a script to test that: https://gist.github.com/jamesb93/3e19cc4769b43fc97968140c423edd0f.

**To Reproduce**
1. Add `hide_window decorations yes` to your kitty configuration file.
1. Focus Kitty.app
2. Initiate Left/Right half action through Rectangle.app
3. Left edge of the window will move, but it won't resize properly.

**Screenshots**

**Environment details**
```
kitty 0.29.0 (e2b5c6688d) created by Kovid Goyal
Darwin CLIENT3903 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:50:21 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8112 arm64
ProductName:		macOS ProductVersion:		13.2 BuildVersion:		22D49
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/jby/.config/kitty/kitty.conf

Config options different from defaults:
hide_window_decorations 1

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_AU.UTF-8
	SHELL                               /opt/homebrew/bin/fish
	USER                                jby
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
search the closed issues for a duplicate.

**Comment by jamesb93** [comment]
Thanks. For anyone else who arrives here: https://github.com/kovidgoyal/kitty/issues/6436
