### ISSUE TITLE
Kitty does not turn off POSIX mode for Bash after loading integration

### ISSUE THREAD

**Issue by carljparker** [kovidgoyal/kitty#6476]
**Describe the bug**
After I launch a Kitty terminal on macOS using Bash as my shell, I observe that Bash is running in POSIX mode--even though the documentation for Kitty shell integration says that Kitty turns POSIX mode off after it loads its integration code.

**To Reproduce**
1. Launch Kitty with default configuration on macOS
2. run `set -o | grep posix`
3. Observe that POSIX mode is set to on.
4. An additional test: On the command line define a function that uses hyphens `foo-bar() { echo foo; }` and see the error that the function name is not a valid identifier. Then turn POSIX mode off and try again to define the function and see that no error is emitted.

The above behavior seems inconsistent with what is described in the docs at the following URL:

https://sw.kovidgoyal.net/kitty/shell-integration/#how-it-works

> For bash, kitty starts bash in POSIX mode, using the environment variable [ENV](https://sw.kovidgoyal.net/kitty/glossary/#envvar-ENV) to load the shell integration script. This prevents bash from loading any startup files itself. The loading of the startup files is done by the integration script, after disabling POSIX mode. From the perspective of those scripts there should be no difference to running vanilla bash.

Although I do not mention it in the repro steps above, part of the impact of the issue is that my startup scripts do not run correctly. You can see the diagnostics emitted from the startup scripts in the screenshot attached below.

**Screenshots**
![Screen Shot 2023-07-16 at 4 26 47 PM](https://github.com/kovidgoyal/kitty/assets/1108664/c82b8459-9d1d-422a-b932-e1cfe05d755e)

**Environment details**
```
kitty 0.29.0 (e2b5c6688d) created by Kovid Goyal
Darwin Carls-Mac-Mini-M1.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.6.3 BuildVersion:	21G419
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /Users/carljparker/.config/kitty/kitty.conf

Config options different from defaults:
shell bash --login

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	USER                                carljparker

```

**Additional context**

The issue occurs with `kitty --config NONE`. The issue does **not** occur if I disable `shell_integration` in `kitty.conf`

I tried specifying `bash --login` for the shell in `kitty.conf`, but this had no affect on the issue.

**Comment by kovidgoyal** [comment]
Does not repro for me with

```
kitty --config=NONE -o shell=bash

set -o | grep posix
posix          	off
```

This will be caused by something in your environmnet, most likely your shell rc files bisect them to find the culprit.
