### ISSUE TITLE
send key mode for kitty selection highlight

### ISSUE THREAD

**Issue by sbalnave** [kovidgoyal/kitty#6480]
I'm using send_text with Cmd-c to send `"+y` for copying visually highlighted text in vim to the system clipboard, but it would to great if this didn't send_text when text is selected by Kitty (eg using Shift-MouseDrag) so that Cmd-c still does copy_to_clipboard.

**Comment by kovidgoyal** [comment]
If you want to do things conditional on the state of something else,
they way to do it is to write a custom kitten.
https://sw.kovidgoyal.net/kitty/kittens/custom/

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/custom/#using-kittens-to-script-kitty-without-any-terminal-ui
