### ISSUE TITLE
Is there a way to dump the current running configuration without the config file?

### ISSUE THREAD

**Issue by mwoodson** [kovidgoyal/kitty#6484]
Dumb question, hope there is an answer. 

I have a running kitty terminal with a lot of customizations on MacOS.  I overwrote the config dir with a new one, so I can't see what I had set. 

Is there a way to get the settings, especially colors, from a running session without the config file?  I know this is on me, just looking for some help while it's still running and really configured how I want!

Thanks for any suggestions!

**Comment by kovidgoyal** [comment]
Press ctrl+shift+f6

**Comment by mwoodson** [comment]
you are the best!!!!
