### ISSUE TITLE
Unable to use `show_key` kitten

### ISSUE THREAD

**Issue by ad-chaos** [kovidgoyal/kitty#6486]
**Describe the bug**
When I run `kitten show-key`, I get
```
Press any keys - Ctrl+D will terminate this program
UNIX		send_text
Error: read /dev/tty: resource temporarily unavailable
```
**To Reproduce**
run `kitten show-key`, see the above error
run `kitten show-key --key-mode=kitty` and do not see error
infact, all modes accept `kitty` seem to be affected

**Comment by kovidgoyal** [comment]
Works for me under both linux and macOS. Something unusual about your
setup?

**Comment by ad-chaos** [comment]
The commit fixes it, Thank you!
