### ISSUE TITLE
OSC report reply should use BEL if query uses it

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#649]
When querying the text foreground using `printf '\e]10;?\a'` kitty replies with: `^[]10;rgb:9393/a1a1/a1a1^[\`.

However, xterm and urxvt use `\a` (`^G`) in the reply: `^[]10;rgb:9393/a1a1/a1a1^G`

I.e. they use the delimiter from the query, and not `\e\` unconditionally.

Both urxvt and xterm will use `\e\` also in the reply when using `printf '\e]11;?\e\'` (i.e. `\e\` instead of `\a`).

urxvt uses this code to parse the ending delimiter (and uses it in the reply): https://github.com/exg/rxvt-unicode/blob/0767fe71f667f5be4e8967ca6ea27e2b14c19daf/src/command.C#L3214

**Comment by blueyed** [comment]
`man 7 urxvt` says this:

```
XTerm Operating System Commands
       "ESC ] Ps;Pt ST"
           Set XTerm Parameters. 8-bit ST: 0x9c, 7-bit ST sequence: ESC \ (0x1b, 0x5c),
           backwards compatible terminator BEL (0x07) is also accepted. any octet can be
           escaped by prefixing it with SYN (0x16, ^V).
```

I.e. it seems to have something to do with backward compatibility.

**Comment by kovidgoyal** [comment]
Both ST (Esc\) and BEL are perfectly valid terminators for OSC codes. See http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands 

kitty always prefers ST over BEL for all escape codes, because BEL has other meaning as well, while ST does not. ST which stands for String Terminator is explicitly designed to terminate string based escape codes. BEL is used for system bells, its use to terminate string codes is a historic artifact and should not be relied upon. If you have some code that relies on these being terminated by BEL you should change them to use ST instead. As far as I know, all applications that query emulators are perfectly happy with ST.

**Comment by blueyed** [comment]
Thanks for the explanation again.

For reference: I only noticed it, because Zsh (in my config) handles the case with BEL better: 

```
% zsh -f
% printf '\e]11;?\e\'; sleep 1
^[]11;rgb:0000/2b2b/3636^[%
% 
execute: 0000/2b2b/3636_  

% printf '\e]11;?\a'; sleep 1  
^[]11;rgb:0000/2b2b/3636^G%
%
```

In the first case it triggers the `execute-named-cmd` widget.

(The `sleep 1` is already necessary to make the response visible.)
(The `%` at the end of the line indicates that there is no output)

Likely more an issue with Zsh / or rather that the reply should be read in a special way (do you know how to from the terminal itself / or a shell script)?

**Comment by kovidgoyal** [comment]
I never use shell scripts for this kind of thing, they are waaay to fragile. If I were you, I'd write it in python. Indeed, I dont know of anyway this can be done robustly in a shell. There are various problems.

stdin (or /dev/tty) is by default line buffered. This needs to be turned off via termios (see VMIN and VMAX i n the termios man page). I dont know how you'd do that in a script. Then I dont know how you'd read only a few bytes at a time from stdin in a script either.

I'd suggest you use the infrastrucutre kitty already has for this. You can run arbitrary python csripts with

kitty +launch /path/to/script.py

See for example the TTYIO class which is used by various kittens in kitty to query the terminal emulator and read escape code based responses from it.

I dont know what you are trying to do, but if it is manipulate colors, I strongly suggest using kitty @ set-colors, far easier to use, more comprehensive and more robust.
