### ISSUE TITLE
Disable keybinds for neovim

### ISSUE THREAD

**Issue by fecet** [kovidgoyal/kitty#6490]
Can I disable kitty's keybind for specific program like neovim ? I have many keybinding conflict with kitty and I don't want to just map all of them to `no_op` as they are still pretty useful when I don't use neovim.

**Comment by kovidgoyal** [comment]
Use a special kitty config with the shortcuts unmapped and use a script
to start nvim that tells kitty to load the config before starting nvim
and after it quits tells kitty to load the main config again.
