### ISSUE TITLE
`$XDG_CACHE_HOME` and `$XDG_CONFIG_HOME` not respected

### ISSUE THREAD

**Issue by thcrt** [kovidgoyal/kitty#6491]
The XDG Base Directory specification is a great thing. And Kitty already complies with its defaults, storing cache files in `.cache/kitty` and config files in `$.config/kitty`. Wonderful!

However, I have a different setup, where I have the directory `~/local`, which contains subfolders like `~/local/config` and `~/local/cache`. I've set up the respective environment variables. And yet Kitty ignores them and just sticks with the defaults defined in the spec, not complying with a user's own choice to override them.

It would really be great if this could be fixed :)

**Comment by kovidgoyal** [comment]
kitty respects both of those already.
