### ISSUE TITLE
Allow the kitten hint to search the entire screen in split layouts

### ISSUE THREAD

**Issue by Subjective** [kovidgoyal/kitty#6494]
**Is your feature request related to a problem? Please describe.**
Hi! As someone who has been using kitty as my main terminal for quite some time now, one of my favorite features is the hints kitten as it really makes selecting links and git commit SHAs a breeze. However, when using a native split layout, it seems to only work for a given window/pane, not the entire screen (to the best of my knowledge). For situations where you have a git log (opened in less) in one window/pane, and an active shell in the other, it's not possible to select a hash from there to insert into the shell.

**Describe the solution you'd like**
It would be really cool if the hints kitten would search the entire screen for matches by default, with the option of passing in an additional flag to select a given window (though I'm not entirely sure how that would work).

**Describe alternatives you've considered**
The only workaround I found is to run a terminal multiplexer like tmux in the main window.

**Additional context**
<img width="902" alt="image" src="https://github.com/kovidgoyal/kitty/assets/56745535/16ac1bb0-e248-4a61-b9f3-bc96a5914529">

**Comment by kovidgoyal** [comment]
This is not possible given the way hints works, its a standalone program
that runs inside a window.
