### ISSUE TITLE
Does it support freetype infinality?

### ISSUE THREAD

**Issue by SolarAquarion** [kovidgoyal/kitty#65]

**Comment by kovidgoyal** [comment]
I have no idea. Not something I am interested in supporting, but patches are welcome -- although since kitty uses only official freetype APIs unless infinality breaks those somehow, it should work.

**Comment by SolarAquarion** [comment]
gcc -Wextra -Wno-missing-field-initializers -Wall -std=c99 -D_XOPEN_SOURCE=700 -pedantic-errors -Werror -O3 -DNDEBUG -fwrapv -fstack-protector-strong -pipe -march=native -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -pthread -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/python3.6m -I/usr/include/python3.6m -c /home/solaraquarion/.cache/pacaur/kitty-git/src/kitty/kitty/line.c -o /home/solaraquarion/.cache/pacaur/kitty-git/src/kitty/build/fast_data_types-line.c.o
gcc -Wextra -Wno-missing-field-initializers -Wall -std=c99 -D_XOPEN_SOURCE=700 -pedantic-errors -Werror -O3 -DNDEBUG -fwrapv -fstack-protector-strong -pipe -march=native -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -pthread -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/python3.6m -I/usr/include/python3.6m -c /home/solaraquarion/.cache/pacaur/kitty-git/src/kitty/kitty/freetype.c -o /home/solaraquarion/.cache/pacaur/kitty-git/src/kitty/build/fast_data_types-freetype.c.o
In file included from /usr/include/freetype2/freetype/config/ftconfig.h:42:0,
                 from /usr/include/freetype2/freetype/freetype.h:33,
                 from /home/solaraquarion/.cache/pacaur/kitty-git/src/kitty/kitty/freetype.c:11:
/usr/include/freetype2/freetype/config/ftoption.h:690:0: error: "TT_CONFIG_OPTION_SUBPIXEL_HINTING" redefined
 #define TT_CONFIG_OPTION_SUBPIXEL_HINTING  ( 1 | 2 )
 
/usr/include/freetype2/freetype/config/ftoption.h:689:0: note: this is the location of the previous definition
 #define TT_CONFIG_OPTION_SUBPIXEL_HINTING  1

**Comment by SolarAquarion** [comment]
I found the issue

**Comment by kovetskiy** [comment]
@SolarAquarion good that you found, can you share it with me and with others who use infinality?

**Comment by SolarAquarion** [comment]
It's about commenting out one of the options that are annoying you
