### ISSUE TITLE
kitty.conf file doesnt exist

### ISSUE THREAD

**Issue by metanoia1980** [kovidgoyal/kitty#6501]
I have downloaded kitty twice now trying to find this kitty.conf file but the kitty directory ~/.config/kitty is empty both times. I have managed to find the file online(an edited one, not the standard original) and put it there but it doesnt source from it... where is it sourcing the config file from? and why isnt my original kitty.conf file where it should be?

**Comment by kovidgoyal** [comment]
Read https://sw.kovidgoyal.net/kitty/conf/
