### ISSUE TITLE
extend blocks to border

### ISSUE THREAD

**Issue by theotheroracle** [kovidgoyal/kitty#6504]
**Is your feature request related to a problem? Please describe.**

there are always gaps around block characters when the size of the window is not an exact multple of the cells

**Describe the solution you'd like**

if the block characters were extended to the edge of the border, even though they're not perfectly aligned, they would still appear fine 

**Describe alternatives you've considered**

unfortunately the snap window size doesn't work on wayland, so that's not an option for me

**Additional context**

i'm willing to attempt to pr this myself given some direction and the ok to do so

**Comment by kovidgoyal** [comment]
Not going to happen. Blocks being fixed size is baked very deeply into
both kitty and the concept of a terminal.

**Comment by theotheroracle** [comment]
maybe a better way to phrase it would be to just, set the background colour at the edge to the same colour as the adjacent block ? the blocks are not actually changed, the gap between the blocks and the border is just not as obvious

**Comment by kovidgoyal** [comment]
background color of margins/padding is already set to the terminal
background color. If you are using a full screen application that
renders in a different backgroudn then that application should be fixed
to set the background color rather than filling in blocks. For example,
in vim you can do that in the color scheme definition.

**Comment by kovidgoyal** [comment]
Seems rather a lot of fiddly work for not much gain. Using the
background color is simple, efficient and works well. However if you
really want to implement this I wont stop you. I will review the PR and
merge it if its performance and code complexity impact is not too severe.

**Comment by theotheroracle** [comment]
excellent ! thanks so much
