### ISSUE TITLE
MacOS: Hide or change border color

### ISSUE THREAD

**Issue by AlexvZyl** [kovidgoyal/kitty#6508]
**Is your feature request related to a problem? Please describe.**
On MacOS, when I set `hide-window-decorations titlebar-only`, the MacOS border remains.  This is quite ugly.
  
<img width="202" alt="Screenshot 2023-07-29 at 23 37 11" src="https://github.com/kovidgoyal/kitty/assets/81622310/0d7137d9-5280-4ce7-970c-dcadc7348a3f">

**Describe the solution you'd like**
Provide an option to hide the border or change the color of the border.

**Describe alternatives you've considered**
Alacritty found a way to implement this, I am not sure how they did it.

<img width="202" alt="Screenshot 2023-07-29 at 23 35 03" src="https://github.com/kovidgoyal/kitty/assets/81622310/90f0ba94-eeaf-41a0-9545-d5f04bb41e67">

**Additional context**
I assume this will depend on the glfw/cocoa API.  I can head over the the alacritty team and hear what they did if you are interested.

**Comment by kovidgoyal** [comment]
Not something I care about, but patches welcome. Or just use
titlebar-and-corners.

**Comment by AlexvZyl** [comment]
I wish to keep the window rounding.  I will see if I can submit a PR.
