### ISSUE TITLE
Kitty does not exit when windows is closed in MacOS

### ISSUE THREAD

**Issue by Jacfger** [kovidgoyal/kitty#6509]
**Describe the bug**
I'm actually not sure if this is intended effect. But basically, if you invoke kitty with command kitty (or `/Applications/kitty.app/Contents/MacOS/kitty`), when I directly exit (<^-D>, exit, close the window), the shell who called kitty doesn't accept new command (which in my understanding is that kitty hasn't exited yet). And an extra <^-C> is needed to properly terminate it.

Is this behavior expected? Because right now I'm invoking kitty with Karabiner and I'm worried that this will create a lot of unterminated processes.
**To Reproduce**
1. Invoke Kitty in shell. (Kitty or MacOS in-built terminal)
2. Close the opened Kitty (either <^-D>, `exit` or closing the window)
3. The shell is showing kitty is not terminated.

**Screenshots**

**Environment details**
```
kitty 0.29.1 (a0341af3f8) created by Kovid Goyal
Darwin Nais-MacBook-Pro-2.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		13.5 BuildVersion:		22G74
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/jacfger/.config/kitty/kitty.conf

Config options different from defaults:
font_family         FiraCode Nerd Font Mono
macos_option_as_alt 3
Removed shortcuts:
	cmd+n →  new_os_window

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/homebrew/bin/fish
	USER                                jacfger
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

I tried invoking `kitty --config NONE`, and invoke kitty with the same command. Same behavior.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_quit_when_last_window_closed

**Comment by Jacfger** [comment]
omg lol thank you so much.
