### ISSUE TITLE
CSI u release is send keys resulting in key input 

### ISSUE THREAD

**Issue by kchibisov** [kovidgoyal/kitty#6516]
I'm not entirely sure whether it's a bug or not, but it doesn't make much sense.

The keyboard protocol says the following for *Report event types*:

>Key events that result in text are reported as plain UTF-8 text, so events are not supported for them, unless the application requests key report mode, see below.

So from my understanding if I enable only `printf "\e[=2u"` and press `e` I shouldn't get an event for it, because the key results in text input.

In particular, what happens is that I get regular `e` for press (expected), and then I get `101;1:3u` for release.

This doesn't happen in repeat, I'd assume that the logic is that release doesn't have a text attached, so it gets reported? But then not every key release is reported, like `ESC`.

If anything the https://sw.kovidgoyal.net/kitty/keyboard-protocol/#event-types should be a bit more clear when it really wants the event being sent.

**Comment by kovidgoyal** [comment]
0b10 means you are requesting the terminal to send you
event types, aka different press and release events.

But without report all keys as escape codes (0b1000), you are not going
to get events for every key type since not every key type is mapped to a
CSI u or similar code, which is needed for reporting release events.
Esc in particular is still encoded as \x1b. It does not make much sense
to use 0b10 and not 0b1000 since now your application has to process CSI
u codes but not for all keys.

**Comment by kchibisov** [comment]
>But without report all keys as escape codes (0b1000), you are not going
to get events for every key type since not every key type is mapped to a
CSI u or similar code, which is needed for reporting release events.

But that's the issue I have, but you've understood it differently?

Esc is not mapped to `CSI u` and I **don't get** release event, and that's **expected** from my reading the spec.

However my original issue is that `e` is not mapped to `CSI u`, because `0b1000` is not active, yet I'm getting a `CSI u` release for it, which is completely arbitrary.

The impression I have in the spec that only `CSI u` (or other known escape with encoded press) could have a `CSI u` indicating a release, is it not the case? What the logic behind the `e` handling?

**Comment by kovidgoyal** [comment]
Quite simple: e has no encoding for press so there is no problem with
using one for release. Esc has an encoding for press, so using a
different encoding for release is quite confusing.
