### ISSUE TITLE
non-PNG background images

### ISSUE THREAD

**Issue by jaacko-torus** [kovidgoyal/kitty#6517]
**Is your feature request related to a problem? Please describe.**

I have a lot of background images on my PC, some of them are PNG, some JPEG, and others SVG. Some official from my linux repo, some are git background image repos, some are things I've scrapped off the internet. I have a lot of these. But currently only PNGs work on kitty.

**Describe the solution you'd like**

I'm fine with converting the one (1) image _I_ want to use. But on #163 I saw no discussion on other image formats, so I'm adding this.

**Describe alternatives you've considered**

The alternative is converting every image one wants to use to PNG.

**Comment by kovidgoyal** [comment]
I have no interest in adding support for sundry image formats to kitty.
Convert the image you want to use to PNG.
