### ISSUE TITLE
kitty @ launch --hold <command> create new terminal

### ISSUE THREAD

**Issue by lolpie244** [kovidgoyal/kitty#6519]
**Describe the bug**
Now, the command `kitty @ launch --hold <command>` does not just run a command, but creates new terminal instance. 
In previous versions `--hold` flag added "press to close" functionality, without creating terminal

**To Reproduce**
`kitty @ launch --hold ls`

**Screenshots**
[Screencast from 2023-08-02 20-57-25.webm](https://github.com/kovidgoyal/kitty/assets/86479624/3e3d53a6-1343-4e1c-93ed-e43f0b6c7a5a)

**Environment details**
Version: 0.29.2-1
Os: arch linux

**Comment by kovidgoyal** [comment]
Yes, that's by design, read the changelog.
