### ISSUE TITLE
Issue with enter key in vim/nvim, only happens in kitty.

### ISSUE THREAD

**Issue by Sharkitty** [kovidgoyal/kitty#6527]
**Describe the bug**
The enter key is not correctly recognized in some context in vim and nvim.

In vim, when I enter a command and press the enter key to execute it, it prints `´` instead (Can't quit vim because of that :joy: )

In nvim I can enter commands, but in netrw the enter key just moves the cursor down instead of opening a file. It also doesn't work with the telescope fuzzy finder (moves the cursor down and breaks the prompt). 

This only happens in kitty terminal, I have tried in XFCE terminal and did not encounter this issue there. This is why I think it's a kitty related issue and not a vim/nvim bug. I'd also add that use fish shell, but I'm encountering the same behaviour in bash. As it's a fresh install I didn't have time to do much config yet so my kitty.conf is close to the default one, vim is default, and the issue also happens with default nvim. I would also indicate that I'm using an AZERTY keyboard layout, I don't know if that's relevant to the issue but I've never seen that on my main machine which has a QWERTY keyboard.

**To Reproduce**
1. Open kitty
2. Run vim
3. Press `:` to enter a command
4. Do any command, press enter to execute it. A `´` should appear in the prompt instead.
5. Good luck quitting since it's not possible to do `:q` with this issue :upside_down_face: 
6. Run nvim.
7. Use the `:Explore` command to open netrw.
8. Select any file or folder and press enter. The cursor should move down instead of opening the file.

**Environment details**
```
kitty 0.29.2 created by Kovid Goyal
Linux oem-spc-i.home 6.4.6-1-default #1 SMP PREEMPT_DYNAMIC Tue Jul 25 04:42:30 UTC 2023 (55520bc) x86_64
Welcome to openSUSE Tumbleweed 20230803 - Kernel 6.4.6-1-default (/dev/tty).

eno2: 4{eno2} 6{eno2}
wlo1: 4{wlo1} 6{wlo1}


Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/sharkitty/.config/kitty/kitty.conf

Config options different from defaults:
editor                nvim
shell                 fish
update_check_interval 0.0

Important environment variables seen by the kitty process:
	PATH                                /home/sharkitty/.local/bin:/home/sharkitty/bin:/usr/local/bin:/usr/bin:/bin
	LANG                                en_US.utf8
	SHELL                               /bin/bash
	DISPLAY                             :0.0
	USER                                sharkitty
	XDG_CONFIG_DIRS                     /etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg:/etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     xfce-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 xfce
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/sharkitty
	XDG_CURRENT_DESKTOP                 XFCE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      3
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/sharkitty/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
```

**Comment by kovidgoyal** [comment]
That will be  bug in the implementation of the kitty keyboard protocol
in those programs, report it there.
