### ISSUE TITLE
build: stringop-overflow warning

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#654]
I am seeing the following warning when building kitty:

```
In function ‘get_exts’,
    inlined from ‘find_extensionsGL’ at …/Vcs/kitty/kitty/gl-wrapper.c:3747:7,
    inlined from ‘gladLoadGLLoader.part.2’ at …/Vcs/kitty/kitty/gl-wrapper.c:3821:7:
…/Vcs/kitty/kitty/gl-wrapper.c:189:17: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
                 strncpy(local_str, gl_str_tmp, len+1);
                 ^
…/Vcs/kitty/kitty/gl-wrapper.c: In function ‘gladLoadGLLoader.part.2’:
…/Vcs/kitty/kitty/gl-wrapper.c:183:26: note: length computed here
             size_t len = strlen(gl_str_tmp);
                          ^
```

The code appears to be fine, but would be nice to silence this: https://github.com/kovidgoyal/kitty/blob/4c0f68150a2f32ab8b8e81f7a3c4f746e714a4a4/kitty/gl-wrapper.c#L182-L189

**Comment by kovidgoyal** [comment]
Sadly, this is generated code from the glad project, so it would need to be silenced there. gl-wrapper is generated from glad.py. You can report it upstream https://github.com/Dav1dde/glad https://github.com/Dav1dde/glad/blob/1b1b3bed219d45a22d8b4bd0a25245de08e2423d/glad/lang/c/loader/gl.py#L62

**Comment by Dav1dde** [comment]
Hey, I just found that issue by pure accident - I was just looking for a new terminal!

I'll fix that.

**Comment by blueyed** [comment]
@Dav1dde 
Cool!
Now you can have a terminal using your project.. :)

**Comment by kovidgoyal** [comment]
@Dav1dde you might also be interested in #701

It's also a harmless thing, but...

**Comment by kovidgoyal** [comment]
No worries, as I said it is harmless. My biggest feature request is to allow switching to the debug variants at runtime rather than compile time. I do that already in kitty (to support the --debug-gl command line option) by post-processing glad output, but it would be nice to have that as a builtin feature in glad.
