### ISSUE TITLE
background_opacity not working

### ISSUE THREAD

**Issue by vumtdev** [kovidgoyal/kitty#6545]
**Describe the bug**
I installed Kitty for the first time and can not set the background opacity properly

**Screenshots**
<img width="408" alt="image" src="https://github.com/kovidgoyal/kitty/assets/61374202/1b3ec2ef-ac3c-4a2c-8547-b9207879c347">

**Environment details**
```
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Darwin LAP14115s-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
ProductName:		macOS ProductVersion:		13.3 BuildVersion:		22E252
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/fish
Loaded config files:
  /Users/lap14115/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.5
editor             nvim .

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /usr/local/bin/fish
	USER                                lap14115


On older versions of kitty, run kitty --debug-config instead
```

**Comment by kovidgoyal** [comment]
Works fine for me on macOS with

kitty --config=NONE -o shell=fish -o background_opacity=0.5

From your screenshot I would guess its because fish is drawing a non-default color as the background on your system. Only the default background color is made transparent. Run kitty as

kitty cat

and see if it works.

**Comment by LittleHendrix** [comment]
> Works fine for me on macOS with
> 
> kitty --config=NONE -o shell=fish -o background_opacity=0.5
> 
> From your screenshot I would guess its because fish is drawing a non-default color as the background on your system. Only the default background color is made transparent. Run kitty as
> 
> kitty cat
> 
> and see if it works.

a bit late to the party, but I've been having the exact same issue with my installation. 
`kitty cat` renders transparency as expected. However, it's not working when I load kitty normally, and I can see that it's trying to apply transparency as I can see the transparent gaps (padding) around the terminal window. But the main area is completely opaque. 

I'm on MacOS Sonoma, kitty `v0.30.1`, using the nord theme.

**Comment by DelinQu** [comment]
> **Describe the bug** I installed Kitty for the first time and can not set the background opacity properly
> 
> **Screenshots** <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/61374202/260260912-1b3ec2ef-ac3c-4a2c-8547-b9207879c347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzY2MDgsIm5iZiI6MTczMTA3NjMwOCwicGF0aCI6Ii82MTM3NDIwMi8yNjAyNjA5MTItMWIzZWMyZWYtYWMzYy00YTJjLTg1NDctYjkyMDc4NzljMzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE0MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYTcwOGRjMjNjZDcxMWNmOWQ4OWFiNjU3YmU0MjFlY2VkZGUxMTMzZjk3ZGE0ZmZkYWEyYjJiZmRjNTY5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tzzVFAxIVgh23BCek3iupEoKNYUN3xzfAnUg7LFRXWg">
> 
> **Environment details**
> 
> ```
> kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
> Darwin LAP14115s-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
> ProductName:		macOS ProductVersion:		13.3 BuildVersion:		22E252
> Frozen: True
> Paths:
>   kitty: /Applications/kitty.app/Contents/MacOS/kitty
>   base dir: /Applications/kitty.app/Contents/Resources/kitty
>   extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
>   system shell: /usr/local/bin/fish
> Loaded config files:
>   /Users/lap14115/.config/kitty/kitty.conf
> 
> Config options different from defaults:
> background_opacity 0.5
> editor             nvim .
> 
> Important environment variables seen by the kitty process:
> 	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
> 	LANG                                en_US.UTF-8
> 	SHELL                               /usr/local/bin/fish
> 	USER                                lap14115
> 
> 
> On older versions of kitty, run kitty --debug-config instead
> ```

Hi, it might not relates to the question, but i wanna ask what's your terminal theme? It looks great.
