### ISSUE TITLE
Why is my activity symbol not working?

### ISSUE THREAD

**Issue by rafaariza** [kovidgoyal/kitty#6551]
**Describe the bug**
The option 'tab_activity_symbol' is not working on my machine. I have tried almost everything, also looked into the source code to determine what is triggering this option to be showed in the title of the tab but I got nothing.

**To Reproduce**
1. Minimal config file:
echo 'tab_activity_symbol "🔔 "' > configtest.conf
2. Run kitty -c configtest.conf
5. See error

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/64159271/11da8daf-0c7e-4370-a1bc-dcac146cba80)

**Environment details**
```
 parrot /dev/tty

Running under: X11
Frozen: True
Paths:
  kitty: /opt/kitty/bin/kitty
  base dir: /opt/kitty/lib/kitty
  extensions dir: /opt/kitty/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  configtest.conf

Config options different from defaults:
tab_activity_symbol    
update_check_interval 0.0

Important environment variables seen by the kitty process:
	PATH                                /home/silexx/.local/bin:/snap/bin:/usr/sandbox/:/opt/nvim-linux64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/opt/kitty/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/silexx/.fzf/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                silexx
	LC_TIME                             es_ES.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	LC_MONETARY                         es_ES.UTF-8
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      2
	LC_ADDRESS                          es_ES.UTF-8
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TELEPHONE                        es_ES.UTF-8
	XDG_SESSION_DESKTOP                 bspwm
	XDG_GREETER_DATA_DIR                /var/lib/lightdm/data/silexx
	LC_NAME                             es_ES.UTF-8
	LC_MEASUREMENT                      es_ES.UTF-8
	LC_IDENTIFICATION                   es_ES.UTF-8
	XDG_VTNR                            7
	LC_NUMERIC                          es_ES.UTF-8
	LC_PAPER                            es_ES.UTF-8
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
The activity symbol is displayed only in a non focused tab if there is
output in that tab while it is non-focused.

Running
kitty -o tab_activity_symbol=X

then doing 
sleep 5s; echo hello

and openening a new tab results in an X in the first tab after 5 seconds
as expected.

**Comment by rafaariza** [comment]
Thanks for clarifying it. Keep the good work up @kovidgoyal
