### ISSUE TITLE
Allow more characters for the option `visual_window_select_characters`

### ISSUE THREAD

**Issue by ed9w2in6** [kovidgoyal/kitty#6554]
**Is your feature request related to a problem? Please describe.**
Hi, may I ask if there are any reasons to only allow letters and digits for the option `visual_window_select_characters`?

**Describe the solution you'd like**
I would like to expand it to all characters that can be typed on an US (international) keyboard.  
Or at least those that can be typed without shift.
This is because setting `visual_window_select_characters ` to `o[]zdf` is more ergonomic IMO.

**Describe alternatives you've considered**
There are no real alternatives unless setting different values for `visual_window_select_characters` is considered alternative.

**Additional context**
None.

**Comment by kovidgoyal** [comment]
Not something I care about, but patches are welcome.

**Comment by ed9w2in6** [comment]
I was about to ask where I can start but you seemed to have implemented it, thank you @kovidgoyal

**Comment by kovidgoyal** [comment]
you are welcome
