### ISSUE TITLE
Freezing/black window after a while

### ISSUE THREAD

**Issue by kamnxt** [kovidgoyal/kitty#6557]
**Describe the bug**
So I've been battling this issue for a while now... For some reason, kitty seems to crash/hang/freeze/turn black and stop responding after a while. 

**To Reproduce**
1. Start kitty
2. Use kitty for a few hours
3. Notice _all_ instances of kitty have turned black and no longer respond to anything; the programs running inside still run fine 

**Screenshots**
_imagine a screenshot of a completely black window_

Sometimes, a window has contents, but looks like the lines are a different width than the window and wrap around, making the contents look scrambled (hard to explain; don't have a screenshot on hand right now)

**Environment details**

```
kitty 0.29.2 created by Kovid Goyal
Linux fg8 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64
Arch Linux 6.4.8-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/kamnxt/.config/kitty/kitty.conf

Config options different from defaults:
click_interval             0.5
cursor_blink_interval      0.4
cursor_stop_blinking_after 4.0
enable_audio_bell          False
focus_follows_mouse        True
font_family                SourceCodePro
font_size                  12.0
remember_window_size       False
scrollback_lines           10000
scrollback_pager           ['less', '+G', '-R']
select_by_word_characters  :@-./_~?&=%+#
term                       xterm-256color
window_border_width        (1.0, 'pt')
Changed shortcuts:
	kitty_mod+- →  decrease_font_size
	kitty_mod+= →  increase_font_size
	kitty_mod+backspace →  restore_font_size
	kitty_mod+o →  pass_selection_to_program firefox
Colors:
	background                 #3f3f3f   
	color0                     #616161   
	color1                     #d68787   
	color10                    #87af87   
	color11                    #ffd787   
	color12                    #add4fb   
	color13                    #ffafaf   
	color14                    #87d7d7   
	color15                    #e4e4e4   
	color2                     #5f865f   
	color3                     #d8af5f   
	color4                     #85add4   
	color5                     #d7afaf   
	color6                     #87afaf   
	color7                     #d0d0d0   
	color8                     #757575   
	color9                     #d75f87   
	foreground                 #d9d9d9   

Important environment variables seen by the kitty process:
	PATH                                /home/kamnxt/bin:/home/kamnxt/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/home/kamnxt/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                kamnxt
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    tty
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Additional context**
Probably some weird interaction with the graphics driver?
I have not yet managed to figure out the exact conditions when this happens - at first I thought this had to do with the proprietary Nvidia driver and Wayland, but then I switched over to nouveau and Xorg and the issue persisted. Thinking it might be related to PRIME, I have removed the nouveau driver (preventing me from using external displays...), hoping that would fix the issue. It now seems like this is happening less often, but somehow it still happens. 
I thought this might have been related to suspend/wake, but today it happened after ~3h of running with an AC adapter plugged in, no suspend, no external screen. Other programs (for example Firefox) survive whatever causes this issue with no problems.

**Comment by kovidgoyal** [comment]
It will definitely be a driver issue, firefox wont be affected as it
doesn't render directly to an opengl context. You can try using the mesa
llvmpipe software renderer and see if it works there as a test:

LIBGL_ALWAYS_SOFTWARE=1 kitty

Note that kitty will be slow and CPU intensive with this.
