### ISSUE TITLE
session file launch command to support bash source/posix . builtin command?

### ISSUE THREAD

**Issue by gknittl** [kovidgoyal/kitty#6561]
**Is your feature request related to a problem? Please describe.**
I bash source (posix .) commands at the terminal prompt at startup to format the command prompt and also to set shell session variables.
kitty @ send-text . setps1$'\n' works fine where setps1 is a script that contains the terminal escape codes.
I'm able to use a second send-text to set bash variables.
I cannot find how to source  setps1 using the kitty launch command in the session file. 
launch --hold sh -c ". setps1" 
fails silently.
launch --hold source setps1 
fails with "source failed with error: exec: "source": executable file not found in $PATH"

As I accumulate more tabs and windows in kitty it gets more inconvenient to have part of the launch in the session file and then complete each window in a kitty @ script. If I launch programs in the session file, then I can't set the command prompt with kitty @ send-text until exiting out of the program so I'm leaning towards abandoning the session file and using a script of kitty @ send-text commands instead.

**Describe the solution you'd like**
I pretty much have to enable remote control to get kitty @ ls which is essential to me as the number of tabs and windows in my kitty session increases. I think I can live without a session file and script the sessions with kitty @. I suppose a session file is still necessary when not allowing any remote control of kitty, but there is now lots of granularity in assigning remote control permissions.

Why have 2 distinct programming interfaces for setting up terminal sessions? Why maintain 2 overlapping code bases to do the same thing? I found the session file initially confusing as to what went into the config file vs the session file. Configuring sessions exclusively by remote control might reduce that learning curve. I start kitty infrequently so a few extra seconds at startup is not an issue. Is there any other benefit to having a session file?

If there is a need for the session file then it would be nice to have full support for the bash source builtin and also perhaps a session file equivalent to kitty @ send-text to better support running multiple programs at window startup. 

Mostly I think I just need some guidance on the design philosophy of the kitty session file so I use in the most effective way.

**Describe alternatives you've considered**

**Additional context**

**Comment by kovidgoyal** [comment]
I am confused. If you want to source a file on shell startup simply put
the source command in your shell rc files. What does kitty sessions have
to do with anything? If you need to some aspect of your shell startup
files use launch --env

And no remote control is not a substitute for session files, since
enabling remote control has security implications.

**Comment by gknittl** [comment]
Thanks as always for the prompt response.

The bashrc file affects all shells. I'd prefer to be able to control the prompt per shell invocation. e.g. shorter prompts when working in a restricted set of directories and longer prompts when using multiple file systems. bashrc appears to run after launch --env and overwrite any PS1 set in launch --env. As far as I know that means I need to source a script that sets PS1 either through the session launch command (which I can't figure out) or through kitty @ send-text which works.

session launch --env does set other environment variables and I think it could work on per session basis. I'm still leaning towards storing the variables in a script and using kitty @ send-text to update shell sessions because it seems easier to update especially while kitty is running.

**Comment by kovidgoyal** [comment]
You use something like

launch --env session_type=foo
launch --env session_type=bar

and in bashrc you use

if [ $session_type = "foo"] ...
