### ISSUE TITLE
Configure default when entering new tab titles

### ISSUE THREAD

**Issue by marcopiraccini** [kovidgoyal/kitty#6565]
**Is your feature request related to a problem? Please describe.**
When I want enter the title of a tab, the current title is shown, which defaults to the current PWD and might be very long. I have to delete it manually to enter the title I want (which is annoying). 

**Describe the solution you'd like**
It would be great to have a config param to specify what to show when entering the new title (so I could chose to have the current title, or none).

**Comment by kovidgoyal** [comment]
The prompt supports readline bindings. Press ctrl+u to clear it.

**Comment by ad-chaos** [comment]
There is a config param to have it not be pre-filled during interactive usage, https://sw.kovidgoyal.net/kitty/actions/#action-set_tab_title

`map ctrl+shift+alt+t set_tab_title " "` to change the default

**Comment by marcopiraccini** [comment]
> There is a config param to have it not be pre-filled during interactive usage, https://sw.kovidgoyal.net/kitty/actions/#action-set_tab_title
> 
> `map ctrl+shift+alt+t set_tab_title " "` to change the default

This is actually what I was looking for! Tnx!
