### ISSUE TITLE
Drop go-rfc1924 dependency

### ISSUE THREAD

**Issue by hickford** [kovidgoyal/kitty#6567]
Could the https://pkg.go.dev/github.com/jamesruan/go-rfc1924 dependency be replaced with standard library https://pkg.go.dev/encoding/ascii85 ?

**Comment by hickford** [comment]
Perhaps not. They use different character sets.

**Comment by kovidgoyal** [comment]
base85 encoding is used in communication with other independent components, therefore
the standard RFC version is required. I dont believe the stdlib has an
implementation of the RFC version.
