### ISSUE TITLE
Is there a way to start Kitty in maximized screen on Ubuntu?

### ISSUE THREAD

**Issue by rsmath** [kovidgoyal/kitty#6569]
Hi,

I have been trying to play around with the kitty.conf ``toggle_fullscreen`` mapping. While this works, Kitty doesn't automatically start in fullscreen next time. Is there a way to set this in the kitty.conf file (or somewhere in Ubuntu)?

Thank you.

**Comment by kovidgoyal** [comment]
--start-as

**Comment by rsmath** [comment]
So I just add ``kitty --start-as fullscreen`` to kitty.conf file?

**Comment by rsmath** [comment]
Doing this did not work. It still opens in a smaller window size.

**Comment by kovidgoyal** [comment]
--start-as is a command line option you pass to kitty when *invoking*
it.
