### ISSUE TITLE
Inconsistent width of ligatures for line and double line symbols

### ISSUE THREAD

**Issue by juancarlangas** [kovidgoyal/kitty#6570]
**Describe the bug**
For example, if we create a line or double line ligature, it becomes shorter and shorter when the ligature size increases

**To Reproduce**
1. Open a .md or .txt file
2. Write some line (preferently large)
3. Underline or double underline it.
3. You'll see that the underline ligature becomes shorter than the text above.

**Screenshots**
With Konsole:
![Screenshot_20230822_160342](https://github.com/kovidgoyal/kitty/assets/72962922/401006d3-6f07-4fd4-88a6-b304544ba517)

With Kitty:
![Screenshot_20230822_160300](https://github.com/kovidgoyal/kitty/assets/72962922/623f1cdd-c182-46d6-b4d2-e332273529b0)

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux Lisandra 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64
Ubuntu 22.04.3 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/juancarlangas/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.7
font_family           Cascadia Code PL
font_size             15.0
update_check_interval 0.0
Changed shortcuts:
	shift+ctrl+n KeyAction('new_os_window_with_cwd')
	shift+ctrl+t KeyAction('new_tab_with_cwd')
```

**Comment by kovidgoyal** [comment]
1) Your version of kitty is ancient, update
2) Ligatures come from fonts whatever font you are using will have
defined that ligature to not be the same width as the text
3) Your markdown renderer should replace these with box drawing
characters for font independent results

**Comment by kovidgoyal** [comment]
Actually only (1) is needed. dup of #3896

**Comment by juancarlangas** [comment]
Awesome, didnt think Ubuntu LTS official build was so outdated. Thank you. Solved!

**Comment by juancarlangas** [comment]
Taking advantage of your expertise, master, I have a question. You don't need to answer it; I can research it myself.

If I enter a flag (emoji), I must leave a blank character at the end of the line for it to remain as it is. If I delete that character, the flag transforms (into what I believe is a character with a lower numerical value).

With blank character:
![Screenshot_20230823_214206](https://github.com/kovidgoyal/kitty/assets/72962922/2c8e5236-9368-4b3d-93b2-1be916332871)

Without blank character:
![Screenshot_20230823_214247](https://github.com/kovidgoyal/kitty/assets/72962922/cd5732db-caec-4992-a774-ec600f1db0d8)

I dont know if I should consider an Issue.

Steps:

1. Insert a large emoji (UK Flag)
2. Delete the last empty character
3. Move cursor to next line

**Comment by kovidgoyal** [comment]
This will be an issue with whatever terminal program you are inserting things. Run cat instead and paste your flag emoji without a trailing blank, it will render fine.
