### ISSUE TITLE
Allow setting initial window size in scaling-relative units

### ISSUE THREAD

**Issue by mordae** [kovidgoyal/kitty#6571]
**Is your feature request related to a problem? Please describe:**

- I am using laptop with FHD built-in screen but frequently switch to external 4K screen with 2× scaling factor.
- Kitty lets me configure `initial_window_{width,height}`.
- The initial window size does not scale with the scaling factor so the window is either tiny on FHD screen or huge on 4K one.

**Describe the solution you'd like:**

- I would love an ability to set the initial dimensions in scaling-relative units.
- One possibility would be `initial_window_{rows,columns}` that would consult font size and size the window to fit that many rows and columns
- Other possibility would be e.g. `initial_window_width 900s`, that is with units after the value with `s` indicating scaled. The value would be scaled according to Wayland scaling factor or `Xft.dpi / 96` factor.

**Additional context**

- I am stuck on X because of KiCad.

**Comment by BigBrotherJu** [comment]
I believe you can specify the initial window size in cells. Not sure if this is what you are looking for.

**Comment by kovidgoyal** [comment]
You can already do this, see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remember_window_size
