### ISSUE TITLE
Ability to completely unbind some of the keybindings 

### ISSUE THREAD

**Issue by dmtrKovalenko** [kovidgoyal/kitty#6575]
**Is your feature request related to a problem? Please describe.**
I use kitty + neovim with advanced keyboard protocol https://sw.kovidgoyal.net/kitty/keyboard-protocol/ but there is no way to unbind some of the keyboard bindings like cmd+h which by default hides the app on macos. 

I have set this config and it is not hiding the window on press but also not forwarding the cmd+h keybinding to the terminal  (the `kitty +kitten show_key -m kitty` is not showing anything)

```
map cmd+h no_op
map cmd+alt+shift+h hide_macos_app 🍎
```

**Describe the solution you'd like**
If I unmapped the keyboard binding it should be forwarded to the terminal

**Comment by kovidgoyal** [comment]
Works for me, remember that you have to restart kitty for bindings that are handled by globally by cocoa to take effect.
