### ISSUE TITLE
Mac OS 10.14, OpenGL deprecation, and kitty

### ISSUE THREAD

**Issue by sheriferson** [kovidgoyal/kitty#658]
I was going to post a followup comment on your response to #214, but it seemed unrelated enough that I thought it warranted a separate issue for discussion.

> Just FYI, Apparently Apple agrees with me, they are removing sub-pixel antialias completely in 10.14 https://infinitediaries.net/removed-in-macos-10-14-mojave/

Along with sub-pixel antialias going away, [OpenGL is being deprecated in 10.14](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjXloO5i97bAhUSKnwKHd6BAr0QFggzMAI&url=https%3A%2F%2Fapple.slashdot.org%2Fstory%2F18%2F06%2F05%2F1719205%2Fapple-deprecates-opengl-and-opencl-in-macos-1014-mojave).

What does this mean for the future of kitty running on MacOS, since kitty uses OpenGL for rendering?

**Comment by kovidgoyal** [comment]
It's no big deal. There are lots and lots of applications that use OpenGL, so while Apple can deprecate it all it wants, I doubt it will actually remove it (see for example the situation with openssl on macOS). And if it does ever decide to remove it, kitty can be ported to use vulkan fairly easily (all the openGL code in kitty is encapsulated away from the rest of the code via an internal API). Indeed, it is on my TODO list to port kitty to Vulkan anyway, once it becomes more mature.

**Comment by sheriferson** [comment]
That's good, reassuring news. Thanks.
