### ISSUE TITLE
Blank kitty terminal when built from latest github source on Arm64 target

### ISSUE THREAD

**Issue by RoninTech** [kovidgoyal/kitty#6584]
**Describe the bug**

I cloned from github and built the latest kitty code on my Arm64 Debian Bullseye RPi4 target.  Terminal opens and I can type commands that are definitely processed.  When I type exit, window closes as expected.  Unfortunately the terminal contents are blank the whole time it is open.  When invoked from another terminal, the only log message I _sometimes_ receive is:

`WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation`

My target supports OpenGL ES 3.1, Vulkan 1.0.  Not sure if this is relevant but to get it to work with wezterm I had to use the option:

`config.front_end = "WebGpu"`

instead of:

`config.front_end = "OpenGL"`

Alacritty just worked out of the box.

If I invoke kitty with the --debug-rendering option and only type exit, I get:

```
GL version string: '3.3 (Core Profile) Mesa 20.3.5' Detected version: 3.3
prompt_marking: x=0 y=0 op='k;start_kitty'
prompt_marking: x=0 y=0 op='A'
prompt_marking: x=0 y=0 op='k;end_kitty'
prompt_marking: x=38 y=0 op='k;start_suffix_kitty'
prompt_marking: x=38 y=0 op='k;end_suffix_kitty'
prompt_marking: x=0 y=1 op='k;start_kitty'
prompt_marking: x=0 y=1 op='C'
prompt_marking: x=0 y=1 op='k;end_kitty'
prompt_marking: x=0 y=1 op='k;start_suffix_kitty'
prompt_marking: x=0 y=1 op='k;end_suffix_kitty'
```

I'm not sure if any other logs/relevant debug info are available.

**To Reproduce**
1. built latest github on RPi4 target
2. run the freshly squeezed kitty
3. see that the terminal contents are blank no matter what you type.

**Screenshots**

![image](https://github.com/kovidgoyal/kitty/assets/226861/d2d23c8e-5d4a-4940-918c-a0d062c29c41)

**Environment details**
```
kitty 0.29.2 (588da9f1dc) created by Kovid Goyal
Linux Pi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64
Debian GNU/Linux 11 Pi /dev/tty

Running under: X11
Frozen: False
Paths:
  kitty: /home/pi/projects/kitty/kitty/launcher/kitty
  base dir: /home/pi/projects/kitty
  extensions dir: /home/pi/projects/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/pi/.config/kitty/kitty.conf

Config options different from defaults:
editor                nvim
font_family           Firacode Nerd Font Mono
linux_display_server  x11
update_check_interval 0.0

Important environment variables seen by the kitty process:
	PATH                                /home/pi/projects/kitty/kitty/launcher:/home/pi/.cargo/bin:/home/pi/.local/bin:/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/local/go/bin:/home/pi/bin
	LANG                                en_CA.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                pi
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     lxde-pi-
	XDG_CONFIG_HOME                     /home/pi/.config
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 lightdm-xsession
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm/data/pi
	XDG_CURRENT_DESKTOP                 LXDE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      3
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_ALL                              en_CA.UTF-8
	XDG_DATA_DIRS                       /usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg:/home/pi/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop

```

**Additional context**

Blank terminal still happens with "--config NONE"

**Comment by kovidgoyal** [comment]
This will be some driver issue I doubt very much it has anything to do
with any recent kitty changes, but it should be easy to do a bisect to
check. Or at least try to run previous kitty releases. Unfortunately I
dont have this hardware to debug with so you will need to do the work.
