### ISSUE TITLE
ibus input method stopped working after updating to Debian Bookworm

### ISSUE THREAD

**Issue by vincent-olivert-riera** [kovidgoyal/kitty#6593]
By running Kitty with `GLFW_IM_MODULE=ibus kitty` I was able to use ibus as the input method, and then have the possibility to type CJK characters. That was working just fine on Debian Bullseye.

Now, after updating to Debian Bookworm it has stopped working. ibus continues to work just fine on other GUI apps, like this web browser: あいうえお。And also works fine on other terminals, like lxterminal. However, it has also stopped working for other terminals that used to work before, such as xterm or gnome-terminal.

@kovidgoyal , I don't know if you happen to have a Debian Bookworm machine where you can debug this. Or if you have any ideas you want me to try, please let me know.

I have also reported this on the [Debian forums](https://forums.debian.net/viewtopic.php?t=155899).

Thanks in advance.

**Comment by kovidgoyal** [comment]
Most likely you switched to wayland. Make sure kitty is running under
wayland not xwayland. And in wayland IME is native you dont need
GLFW_IM_MODULE. Or alternately switch back to an x11 session wayland
isnt worth the bother.

**Comment by vincent-olivert-riera** [comment]
> Most likely you switched to wayland. Make sure kitty is running under wayland not xwayland.

Before in Bullseye I was already using Sway (wayland) as my window manager, and it was working. The setup in Bookworm is the same.
Do you think that in Bullseye I was running kitty under xwayland, and that was working, and now in Bookworm running it under xwayland as well does not work?

How do I check if it's actually running under wayland or xwayland?

> And in wayland IME is native you dont need GLFW_IM_MODULE.

Good to know, thanks :+1:

> Or alternately switch back to an x11 session wayland isnt worth the bother.

That would mean stop using Sway, which I don't want.

**Comment by vincent-olivert-riera** [comment]
Uhm..., I have discovered something interesting.

CJK input works in kitty from a wayland session in Gnome (I also verified that is not running under xwayland), so I guess the problem must be with Sway 🤔

**Comment by kovidgoyal** [comment]
Use i3 and X11 sway is just a copy of i3 anyway. Probably sway has
implement the wayland text input protocol v3 which is needed for IME.
And see linux_display_backend in kitty.conf

**Comment by kovidgoyal** [comment]
On Fri, Sep 01, 2023 at 01:47:06AM -0700, Vicente Olivert Riera wrote:
> As far as I know [Sway uses wlroots](https://github.com/swaywm/sway/blob/master/include/sway/input/text_input.h#L4) which [does implement](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_text_input_v3.h) Wayland's text input protocol v3.
> Perhaps it is not a complete implementation?

The protocol is probably complete you probably need to get ibus running/integrating with it.
I dont use sway so cant really help you with that.

> 
> > And see linux_display_backend in kitty.conf
> 
> I could not find `linux_display_backend`. I guess you meant `linux_display_server`?
> https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.linux_display_server
> 
> Setting `linux_display_server x11` fixes the issue. I guess it's because this makes kitty use xwayland instead of just wayland. Now the xeyes move when hovering the mouse pointer over the kitty window.
> 
> It would be nice to know why it does not work when using just wayland, though 🤷🏻 


It works fine in wayland, I have tested it with both gnome and kde under
wayland. No clue about sway.

**Comment by vincent-olivert-riera** [comment]
> The protocol is probably complete you probably need to get ibus running/integrating with it. I dont use sway so cant really help you with that.

No worries, you have helped me enough. I think I will report all the findings to Debian.

> It works fine in wayland, I have tested it with both gnome and kde under wayland. No clue about sway.

In Debian Bookworm? I just tried Gnome under Wayland right now and it does not work for me.

**Comment by kovidgoyal** [comment]
On Fri, Sep 01, 2023 at 02:09:54AM -0700, Vicente Olivert Riera wrote:
> > The protocol is probably complete you probably need to get ibus running/integrating with it. I dont use sway so cant really help you with that.
> 
> No worries, you have helped me enough. I think I will report all the findings to Debian.
> 
> > It works fine in wayland, I have tested it with both gnome and kde under wayland. No clue about sway.
> 
> In Debian Bookworm? I just tried Gnome under Wayland right now and it does not work for me.

No I use Arch not Debian. But IME has worked under GNOME Wayland since
GNOME 40 IIRC.
