### ISSUE TITLE
Seg fault after icat and window resize M1 macos

### ISSUE THREAD

**Issue by mlau-anet** [kovidgoyal/kitty#6595]
**Describe the bug**
Use of icat causes segfault
**To Reproduce**
1. `kitty +kitten icat` this photo : https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.worldatlas.com%2Fupload%2Fa1%2Fc0%2Fd4%2Fshutterstock-1163119720.jpg&f=1&nofb=1&ipt=84f93b3205bcfe4631d5de670c14cdf99542ae98d61ebb541afb3d80c2737315&ipo=images
2. resize OS window
3. mouse click finder application or desktop
4. move OS window to an external monitor
5. Continue variations of steps 1-4 at random
6. See error

**Screenshots**

**Environment details**
```
kitty 0.29.2 created by Kovid Goyal
Darwin LYJ9G7Y4X0-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.2 BuildVersion:		22D49
Frozen: False
Paths:
  kitty: /Applications/MacPorts/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/MacPorts/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/MacPorts/kitty.app/Contents/Resources/kitty/kitty
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/MacPorts/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                mlau
	LC_CTYPE                            UTF-8

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

[kitty-crash.txt](https://github.com/kovidgoyal/kitty/files/12500822/kitty-crash.txt)

**Comment by kovidgoyal** [comment]
dup of #6555
