### ISSUE TITLE
Stored image disappears after Ctrl-L/clear

### ISSUE THREAD

**Issue by koterpillar** [kovidgoyal/kitty#6596]
**Describe the bug**

Once I clear the terminal using `clear` or `Ctrl-L`, images previously assigned IDs using `i=` can no longer be displayed with `a=p,i=`.

**To Reproduce**

1. Start `kitty --config NONE`
2. Get a PNG image and store it in the terminal:

```shell
builtin printf "\e_Gi=888,f=100,a=t,q=1,t=f;$(echo -n "/path/to/image.png" | base64)\e\\"

builtin printf -v DRAW "RR\e_Ga=p,i=888,q=2\e\\RR"
```

3. Display it: `echo $DRAW`. The image will be displayed between two pairs of `RR`.
4. Clear the terminal: `clear` (or `Ctrl-L`)
5. Display the image again: `echo $DRAW`

After clearing the terminal, the image won't be drawn, the only output will be `RRRR` with nothing in between.

**Screenshots**

Before `clear`: 
![image](https://github.com/kovidgoyal/kitty/assets/140276/3ec3b456-ae9b-4bbc-a77c-12c3d08da1a2)
After `clear`:
![image](https://github.com/kovidgoyal/kitty/assets/140276/7189dde2-2142-4c08-8d2a-f06a7c19e9bc)

**Environment details**
```
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Linux taohua 6.4.12-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023 x86_64
S
Kernel 6.4.12-200.fc38.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: True
Paths:
  kitty: /home/alex/.local/mybox/kovidgoyal--kitty/bin/kitty
  base dir: /home/alex/.local/mybox/kovidgoyal--kitty/lib/kitty
  extensions dir: /home/alex/.local/mybox/kovidgoyal--kitty/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/alex/.local/bin:/home/alex/.jenv/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                ru_RU.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                alex
	XDG_DATA_DIRS                       /home/alex/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

**Additional context**

I'm trying to add an image to the shell prompt. I've stored it once in `.zshrc` and added the `a=p,i=` command to `PS1`. However, I've found that the image disappears after clearing the terminal. If this is intended behaviour, would be good to document it on the [Terminal graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) page.

**Comment by kovidgoyal** [comment]
clear deletes images, see https://sw.kovidgoyal.net/kitty/graphics-protocol/#interaction-with-other-terminal-actions
