### ISSUE TITLE
weird cut in each line in kitty terminal

### ISSUE THREAD

**Issue by ardnyx** [kovidgoyal/kitty#6597]
I'm using Arch Linux (installed in Virtual Box) and I tried installing kitty, and it has this weird cut at the top in each line.
![image](https://github.com/kovidgoyal/kitty/assets/86859621/d971232a-ee03-40ee-ab15-cba5ccc8fab8)

Even opening the kitty.conf file in kitty itself doesn't change it, it still has that weird cut.
![image](https://github.com/kovidgoyal/kitty/assets/86859621/fa09bde6-9fab-45f2-8a88-5c1c745246d7)

This is the configuration in my kitty.conf file:
# Font config
font_family Hack
font_size 12

# General
mouse_hide_wait 2.0
confirm_os_window_close 0
window_padding_width 12

# Color schemes
background_opacity 1 
background      #2a2a2a
foreground      #fadee1

color0          #fadee1
color8          #fadee1

color1          #fdafab
color9          #fdafab

color2          #f6baba
color10         #f6baba

color3          #e89292
color11         #e89292

color4          #fec9cb
color12         #fec9cb

color5          #fea4b0
color13         #fea4b0

color6          #f38d98
color14         #f38d98

color7          #f282a7
color15         #f282a7

**Comment by kovidgoyal** [comment]
dup of #6257
