### ISSUE TITLE
How to remove this effect

### ISSUE THREAD

**Issue by riteshsonawane1372** [kovidgoyal/kitty#6598]
**Describe the bug**

**To Reproduce**

**Screenshots**
![Screenshot from 2023-09-02 20-00-09](https://github.com/kovidgoyal/kitty/assets/72307121/67d82318-f1d3-4161-9665-c16e2b4b2fc1)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
dup of #6069
