### ISSUE TITLE
Add support for ANSI printer escape sequences

### ISSUE THREAD

**Issue by mamccollum** [kovidgoyal/kitty#6599]
**Is your feature request related to a problem? Please describe.**

When running over SSH, I like to use a script that prints escape sequences to trigger a print dialog on my local machine (iTerm2 supports this standard ANSI feature) however it doesn't work in kitty.

**Describe the solution you'd like**

A CUPS print dialogue, or piping output to the `lp`/`lpr` command on the machine kitty is running on would be a nice feature when the escape codes are executed.

**Describe alternatives you've considered**

Using the system's `lp` or `lpr` command, but this doesn't really work when printing over SSH to the local machine...

**Additional context**

An example command that triggers the print dialog on iTerm2 (and other terminals that support this feature) is:

`printf "\e[5i"; printf 'hello, world!\n'; printf "\e[4i"`

Example of the print dialog triggered in iTerm2: 
![image](https://github.com/kovidgoyal/kitty/assets/124746350/4be162fc-b458-4935-bc5e-5b41efed219a)

**Comment by kovidgoyal** [comment]
While this is relatively simple to implement on macOS, for other
platforms that dont have a system GUI print dialog one would have to
write a wrapper for the lpr command presenting the various options etc.
This is too much work, at least for me, patches welcome.

**Comment by mamccollum** [comment]
Alright, understood. Thanks for taking the time to review this.
