### ISSUE TITLE
escape line breaks in kitty config

### ISSUE THREAD

**Issue by jake-stewart** [kovidgoyal/kitty#6600]
**Is your feature request related to a problem? Please describe.**
Lines exceed 80 columns in my kitty conf.

**Describe the solution you'd like**
The ability to escape newlines with the backslash character.

**Describe alternatives you've considered**
N/A

**Additional context**
It should be as simple as changing `_parse` to this in `kitty/conf/utils.py`. I have not tested it so i will not make a pull request.

```
def _parse(
    lines: Iterable[str],
    parse_conf_item: ItemParser,
    ans: Dict[str, Any],
    accumulate_bad_lines: Optional[List[BadLine]] = None
) -> None:
    name = getattr(lines, 'name', None)
    if name:
        base_path_for_includes = os.path.abspath(name) if name.endswith(os.path.sep) else os.path.dirname(os.path.abspath(name))
    else:
        from ..constants import config_dir
        base_path_for_includes = config_dir

    i = 0
    iterator = iter(lines)

    while True:
        try:
            line = next(iterator)
            i += 1
        except StopIteration:
            break
        while line.endswith('\\'):
            try:
                line = line[-1:] + next(iterator)
                i += 1
            except StopIteration:
                break
        try:
            with currently_parsing.set_line(line, i):
                parse_line(line, parse_conf_item, ans, base_path_for_includes, accumulate_bad_lines)
        except Exception as e:
            if accumulate_bad_lines is None:
                raise
            accumulate_bad_lines.append(BadLine(i, line.rstrip(), e, currently_parsing.file))
```

**Comment by kovidgoyal** [comment]
It's not nearly that simple.

1) You would break all existing config files that happen to have \ as
the last character in a line. For example:

map F1 send_text all \

2) You also need to patch the Go code used for parsing config files in
kittens

(1) is pretty critical. Breaking people's existing config files is not
something I do lightly. Certainly not for such a small payoff.

**Comment by jake-stewart** [comment]
thanks, i did not think hard enough about it. since a single backslash is valid config, it cannot be used.

how would you feel about additional syntax for this? for example, we could use braces:

```
{ map ctrl+key combine
    : launch --type background some_command
    : set_colors ~/.config/kitty/colors/theme.conf }
```

unless i am missing something, this should not break existing configs.

if you are happy with this or have a better alternative, i would be happy to spend a bit of time implementing and testing this properly. @kovidgoyal

**Comment by kovidgoyal** [comment]
Hmm not a fan of the {} it means } becomes illegal/needs to be escaped
in such blocks.

I actually suggest using \ in the first column as a line continuation
char. \ is not legal in the first column. It makes the parser a bit more
complicated as it needs to look one line ahead, but not too bad, I
think.

**Comment by jake-stewart** [comment]
#6603
