### ISSUE TITLE
"Are you sure you want to close" dialogs stack

### ISSUE THREAD

**Issue by rotu** [kovidgoyal/kitty#6601]
**Describe the bug**

If you attempt to use "Close OS Window" or "Close Tab" (either menu item or key combination), it layers a new close confirmation dialog on top, incrementing the number.

Note that closing the window with the corner button twice does *not* layer confirmation dialogs - the second time does nothing, even if the confirmation dialog is open in a different tab!

The "Close Window" action does not seem to be affected - this never seems to open a confirmation dialog. I'm not sure if this is by design or a separate bug.

**To Reproduce**
1. Start a process
2. Try to close the window with Close OS Window or Close Tab (either menu or hotkey will do.
3. Repeat step 2.

**Screenshots**

![Kitty Close](https://github.com/kovidgoyal/kitty/assets/119948/abc5cd81-f0ab-45d1-a609-a35d7f41743f)

**Environment details**
```
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Darwin Hypothesis.local 23.0.0 Darwin Kernel Version 23.0.0: Tue Aug 22 02:13:07 PDT 2023; root:xnu-10002.1.11~16/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		14.0 BuildVersion:		23A5337a
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/dan/.config/kitty/kitty.conf

Config options different from defaults:
font_family          Cascadia Code PL Light
font_size            12.0
Colors:
	color1               #e52222   
	color10              #55ff55   
	color11              #ffff55   
	color12              #5555ff   
	color13              #ff55ff   
	color14              #55ffff   
	color2               #a6e32d   
	color3               #fc951e   
	color4               #c48dff   
	color5               #fa2573   
	color6               #67d9f0   
	color7               #f2f2f2   
	color8               #545454   
	color9               #ff5555   
	cursor               #bbbbbb   
	foreground           #bbbbbb   
	selection_background #545454   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                dan
```

**Comment by kovidgoyal** [comment]
The confirmation only shows up when you try to close multiple windows.
Close Window does not close multiple windows. And yes you can get
duplicate confirms if you try to close multiple times. Not worth the
effort to me to fix. Patches welcome.

**Comment by rotu** [comment]
> The confirmation only shows up when you try to close multiple windows. Close Window does not close multiple windows.

Definitely part of my confusion was due to the [overloading of the term "Window"](#6602).

> Not worth the effort to me to fix. Patches welcome.

Fair enough. It didn't seem like a huge deal, but I don't know the codebase well enough to tell.

**Comment by kovidgoyal** [comment]
Actually, this is not that hard.
