### ISSUE TITLE
Consider renaming "Window"

### ISSUE THREAD

**Issue by rotu** [kovidgoyal/kitty#6602]
**Is your feature request related to a problem? Please describe.**
It's unintuitive that "[Window](https://sw.kovidgoyal.net/kitty/glossary/#term-window)" is overloaded to mean two things:

- "Kitty Window" (called simply "Window" in the Shell menu)
- "OS Window" (called simply "Window" in the Window menu)

**Describe the solution you'd like**
Rename "Kitty Window" to "Pane". This matches the intuition that, in colloquial usage, a window is composited of multiple panes. This aligns with the terminology of `tmux`'s visually similar feature.

**Comment by kovidgoyal** [comment]
I'm afraid not. kitty's terminology has existed for a decade now. It's
not going to change.

**Comment by rotu** [comment]
To paraphrase [something I recently read]:(https://github.com/kovidgoyal/kitty/issues/391#issuecomment-776487537)

> So, you using a term for a decade means it is not misleadingly bad name??
What brand of logic is this?

**Comment by kovidgoyal** [comment]
On Sat, Sep 02, 2023 at 11:37:39PM -0700, Dan Rose wrote:
> To paraphrase [something I recently read]:(https://github.com/kovidgoyal/kitty/issues/391#issuecomment-776487537)
> 
> > So, you using a term for a decade means it is not misleadingly bad name??
> What brand of logic is this?

Sigh. Here you go:

1) it's misleadingly bad *for you*, because of your personal history
with a product that used the term pane.

2) Even if it was objectively bad, which it is not, it has now been used
for a decade by tens of thousands of existing users, documentation,
howtos, blog posts and so on. That is the *cost* in changing it.

**Comment by rotu** [comment]
> because of your personal history with a product that used the term pane.

I don't actually use tmux. I just did some digging and surveyed some other pieces of software. Results above.

> That is the *cost* in changing it.

Undoubtedly there's a cost! There's also a discoverability cost to keeping it the way it is.

For example, the current name makes it un-obvious that "new window" splits the screen. The answer to this [StackOverflow post](https://stackoverflow.com/a/66543260) demonstrates as much:

> you can have both tabs and split screens (Kitty calls them "windows").

A clarifying note in the [glossary](https://sw.kovidgoyal.net/kitty/glossary/) to the tune of "panes (formerly known as *Kitty windows*)" would go far. Even if you don't want to rename them, it might be worthwhile to actually define "kitty window" in the glossary! The glossary explains they comprise layouts, but does not explain what one is, namely: a scrollable interface into its own shell process.

PS: I realize that another (possibly worse but more agreeable) name for this concept is a "box". As we all know, kitties love boxes!

**Comment by kovidgoyal** [comment]
On Sun, Sep 03, 2023 at 01:01:50AM -0700, Dan Rose wrote:
> > because of your personal history with a product that used the term pane.
> 
> I don't actually use tmux. I just did some digging and surveyed some other pieces of software. Results above.

Good for you :)

> 
> > That is the *cost* in changing it.
> 
> Undoubtedly there's a cost! There's also a discoverability cost to keeping it the way it is.

Yes, and one cost is greater than the other. Changing/breaking things is
a far higher cost, IMO.

> 
> For example, the current name makes it un-obvious that "new window" splits the screen. The answer to this [StackOverflow post](https://stackoverflow.com/a/66543260) demonstrates as much:

It doesn't split the screen, it creates a new window, depending on your
layout, that could split the screen or it wont, for example with the
stacked layout. This is precisely the problem. windows are **not**
panes. Panes, or more properly panels, are something that are parts of a
window and cannot be a window themselves. You point out the usage of pane in
tmux, I'll raise you the usage of the term in in "window pane" which is
at least half a millenium old.

tmux just gets the entire concept wrong, along with all the other 
things it gets wrong.

> 
> > you can have both tabs and split screens (Kitty calls them "windows").
> 
> A clarifying note in the [glossary](https://sw.kovidgoyal.net/kitty/glossary/) to the tune of "panes (formerly known as *Kitty windows*)" would go far. Even if you don't want to rename them, it might be worthwhile to actually define "kitty window" in the glossary! The glossary explains they comprise layouts, but does not explain what one is, namely: a scrollable interface into its own shell process.

The glossary already defines what an OS window and a window is, doesn't
seem to have helped you much so I dont see how it would "go far". If you
feel the current explanations in the glossary are insufficient, feel
free to send a PR to improve them.

**Comment by kovidgoyal** [comment]
> I don't actually use tmux.

Good for you :)

> Undoubtedly there's a cost! There's also a discoverability cost to keeping it the way it is.

Yes, and one cost is greater than the other. IMO that would be changing
decade old established usage.

> 
> For example, the current name makes it un-obvious that "new window" splits the screen. The answer to this [StackOverflow post](https://stackoverflow.com/a/66543260) demonstrates as much:

You make my point for me. Creating a new window *does not* split the
screen. It may or may not split the screen depending on what layout is
active. In the stack layout it will not. That is precisely the problem
with pane. "Pane" or more properly panel is a part of a window, not
something that can have its own independent existence. In kitty you can
actually make a kitty window into a tab or an OS window.

You point out the prior usage of pane in tmux, I raise you the half a
millenium old usage of "pane" in "window pane". The dictionary
definition of pane is: 

a piece of glass in a window, etc.

tmux get this wrong, just as it gets so many other things wrong. A
"pane" is not the correct term for this.

> 
> A clarifying note in the [glossary](https://sw.kovidgoyal.net/kitty/glossary/) to the tune of "panes (formerly known as _Kitty windows_)" would go far. Even if you don't want to rename them, it might be worthwhile to actually define "kitty window" in the glossary! The glossary explains they comprise layouts, but does not explain what one is, namely: a scrollable interface into its own shell process.


The definition of window and OS window in the glossary doesn't seem to
have helped you, so I dont see how it will "go far". If you feel the
existing definitions can be further clarified, a PR is welcome.

> 
> PS: I realize that another (possibly worse but more agreeable) name for this concept is a "box". As we all know, kitties love boxes!

The choices are endless, I chose window and OS window. That choice is
done now.
