### ISSUE TITLE
Starting kitty in a fullscreen session will disable DPMS unconditionally

### ISSUE THREAD

**Issue by dagbdagb** [kovidgoyal/kitty#6613]
**Describe the bug**
Starting kitty with --start-as=fullscreen will disable DPMS sleep, independent of kitty being visible on the current workspace or even if no longer in fullscreen mode. This with wayfire running as the compositor.

**To Reproduce**
* Set DPMS timeout to a low value in your wayland compositor or DE.
* Start kitty with option "--start-as=fullscreen"
* Move away from the workspace where kitty is running
* Observe that DPMS does not kick in after $timeout
* Move back to workspace with kitty running in fullscreen. shift-ctrl-f11 to change it to windows state.
* Observe that DPMS still doesn't kick in

**Environment details**
```
kitty 0.29.2 created by Kovid Goyal
Linux skalleper 6.4.6-gentoo #3 SMP Tue Aug 15 23:58:25 CEST 2023 x86_64

This is skalleper (Linux x86_64 6.4.6-gentoo) 14:14:26

DISTRIB_ID="Gentoo"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/dagb/.config/kitty/kitty.conf

Config options different from defaults:
cursor_stop_blinking_after 3.0
enabled_layouts            ['grid:split_axis=horizontal', 'vertical', 'splits:split_axis=horizo>
focus_follows_mouse        True
font_family                FiraCode Nerd Font Mono
startup_session            /home/dagb/.kitty
Added shortcuts:
        f5 →  launch --location=hsplit
        f6 →  launch --location=vsplit
        shift+down →  move_window down
        shift+left →  move_window left
        shift+right →  move_window right
        shift+up →  move_window up
Changed shortcuts:
        shift+insert →  paste_from_clipboard
Important environment variables seen by the kitty process:
        PATH                                /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/>
        LANG                                no
        EDITOR                              /bin/nano
        SHELL                               /bin/bash
        DISPLAY                             :0
        WAYLAND_DISPLAY                     wayland-1
        USER                                dagb
        XCURSOR_SIZE                        24
        XDG_CONFIG_DIRS                     /etc/xdg
        XDG_DATA_HOME                       /home/dagb/
        XDG_CONFIG_HOME                     /home/dagb/.config/
        XDG_SEAT                            seat0
        XDG_SESSION_TYPE                    wayland
        XDG_CURRENT_DESKTOP                 Unity
        XDG_SESSION_CLASS                   user
        XDG_VTNR                            2
        XDG_SESSION_ID                      c25
        XDG_RUNTIME_DIR                     /run/user/1000
        LC_ALL                              nb_NO.utf8
        XDG_DATA_DIRS                       /usr/local/share:/usr/share

This debug output has been copied to the clipboard
```

**Additional context**
I initially reported this with the wayfire project. See:
https://github.com/WayfireWM/wayfire/issues/1888

Reading and parsing the response to the best of my effort, I wonder if my observation counts as two separate bugs? Wayfire should ignore kitty's idle inhibitor when kitty isn't in view. And kitty should not have one, when not in fullscreen mode.

Thank you for kitty!

**Comment by kovidgoyal** [comment]
kitty does not disable DPMS. Indeed there is no DPMS related code in
kitty whatsoever. This will be behavior in your compositor.

**Comment by dagbdagb** [comment]
I never intended to claim that kitty has any DPMS code. Sorry if my communication was unclear.
For all I know, the relevant code resides in glfw. But the observation is clearly linked to something the client application (here: kitty) does different from other client applications.

**Comment by kovidgoyal** [comment]
That's what I meant neither kitty nor GLFW contains any DPMS related
code. So it cannot be disabling DPMS. kitty does not request DPMS be
terminated and GLFW does not have the code to implement that request
even if kitty were to make it. If I had to guess I would say your
compsoitor is deciding that the application going fullscreen means its
displaying a movie and so turns off power management.

**Comment by ammen99** [comment]
@kovidgoyal I am the author of the said compositor, and I have to say that kitty absolutely does request that DPMS is disabled. Kitty uses (via GLFW probably) the idle-inhibit wayland protocol, you can verify this easily by running kitty with `WAYLAND_DEBUG=1` and observing the calls made by the app. For example, `WAYLAND_DEBUG=1 kitty --start-as=fullscreen`, you will see:

```
zwp_idle_inhibit_manager_v1@14.create_inhibitor(new id zwp_idle_inhibitor_v1@32, wl_surface@22)
```

I am not sure whether this is the intended behavior - why would a terminal inhibit idle (idle is the same as DPMS, see [here](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/idle-inhibit/idle-inhibit-unstable-v1.xml?ref_type=heads#L61)?

**Comment by ammen99** [comment]
I suppose the question is why this line is enabled unconditionally: https://github.com/kovidgoyal/kitty/blob/master/glfw/wl_window.c#L491

**Comment by kovidgoyal** [comment]
Not sure what you mean by enabled unconditionally, it's being passed a
boolean. It means that it will ask for idle inhibition for a full screen
window only. I would assume GLFW believes full screen games should
enable idle inhibition since it is primarily targeted at games.

I am not familiar enough with Wayland to know if that is a reasonable
thing to do or not. But since kitty is not a game (though it can host
one), I suppose I can have kitty's GLFW fork not request idle inhibition
on full screen.

**Comment by dagbdagb** [comment]
There's also the oddity that the behavior doesn't appear to change when kitty is switched from fullscreen to windowed (when started with --start-as=fullscreen).

I kind of accept that fullscreen applications prevent DPMS from kicking in (ref. video players and games). But if this behavior can be overruled at the application level, it'd certainly make sense to do it for a terminal app.

I'll give current git a spin tonight.
