### ISSUE TITLE
tmux + kitty won't show fancy underlines

### ISSUE THREAD

**Issue by pattyjogal** [kovidgoyal/kitty#662]
So I've been using tmux with kitty for a while, and it's been great, except now I have a slight issue where I want to enable support for the curly underlines in vim. I've tracked through some issues and found that it is indeed possible, and I put in the correct escape sequences for it to work.

It appears to be working in normal vim, but when I'm in tmux, no undercurl shows. In fact, I've tried
```
echo -e "\e[4:1mTest\e[4:0m"
echo -e "\e[4:2mTest\e[4:0m"
echo -e "\e[4:3mTest\e[4:0m"
echo -e "\e[4mTest\e[24m"
```
and of those four, only the last one works (the legacy one). Everything else renders as normal text, whereas if I exit tmux, it renders as expected.

Here is my .tmux.conf

```
run-shell "powerline-daemon -q"
source "$HOME/powerline/bindings/tmux/powerline.conf"

set -g default-terminal "xterm-kitty"
set -sg escape-time 0
```

Let me know if I can add any more clarification!

**Comment by kovidgoyal** [comment]
There's not much I can do about that, you have to get tmux to pass through those escape codes, which will presumably require changes to tmux.

**Comment by g6ai** [comment]
@pattyjogal Do you have any progress on this now? I've tried the four commands you've provided, outside tmux only the third one `echo -e "\e[4:3mTest\e[4:0m"` works, but inside tmux none works, they all appears to be 'Test' with straight underlines.

**Comment by trygveaa** [comment]
@g6ai: All of those should work in kitty outside tmux (they do for me). To make them work inside tmux you need to add this to tmux.conf (plus a recent enough version of tmux to support it):

```
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
```

This config is copied from https://github.com/tmux/tmux/issues/1492#issuecomment-427939241 and https://github.com/tmux/tmux/pull/1771#issuecomment-500906522.

**Comment by g6ai** [comment]
@trygveaa Brilliant solution! So I tested tmux with those two lines, to edit a LaTeX file in Neovim. Well, after some weeks, I finally find the best tool for my workflow which needs good curly underline and italics inside tmux.

@kovidgoyal Interestingly, with a marketing message of 'designed for tmux and tiling wm' or some sorts, Alacritty never manages to display underlines, italics and powerline fonts well. I know you said kitty is designed to have its own tab/window management and not designed for tmux, but kitty is such a good piece of software that even excels in tmux usage. I have read quite a lot noises while trying to get to know kitty better, but the software speaks for itself. Thank you sir for creating kitty, we are rooting for you!

**Comment by kovidgoyal** [comment]
On Mon, Apr 12, 2021 at 11:46:26AM -0700, G. Bai wrote:
> @kovidgoyal Interestingly, with a marketing message of 'designed for tmux and tiling wm' or some sorts, Alacritty never manages to display underlines, italics and powerline fonts well. I know you said kitty is designed to have its own tab/window management and not designed for tmux, but kitty is such a good piece of software that even excels in tmux usage. I have read quite a lot noises while trying to get to know kitty better, but the software speaks for itself. Thank you sir for creating kitty, we are rooting for you!

You are welcome and while, indeed, I am not a fan of terminal
multiplexers such as tmux, it should work at least as well in kitty as
in any other terminal. kitty just will not support any tmux specific
things.
