### ISSUE TITLE
Config file ignored on i3wm

### ISSUE THREAD

**Issue by DarkblooM-SR** [kovidgoyal/kitty#6621]
**Describe the bug**
Kitty seemingly ignores my config file (`~/.config/kitty/kitty.conf`) on i3 when using `exec i3-sensible-terminal`.

**To Reproduce**
1. In i3, install Kitty
2. Open a terminal with your terminal keybind
3. Notice your Kitty config being ignored

**Screenshots**
-

**Environment details**
`Ctrl+Shift+F6` does nothing.

**Additional context**
-

**Comment by kovidgoyal** [comment]
It will read the config file based on the env vars present in whatever
environment it is launched in. Read the help for the --config flag in
kitty --help to see what algorithm is used.
