### ISSUE TITLE
docs for Go custom kittens?

### ISSUE THREAD

**Issue by josharian** [kovidgoyal/kitty#6622]
I want to write a custom kitten in Go, similar to the built-ins.

The [docs](https://sw.kovidgoyal.net/kitty/kittens/custom/#) only cover how to write a single-file Python kitten.

Copying over the built-in Go-based kittens into a config subdir doesn't work.

(I can't even get the Python imports to work when the kitten is in a config subdirectory, but that's probably just my Python inexperience.)

More docs, or even just an example or a few hints, would be lovely. Thanks!

**Comment by kovidgoyal** [comment]
You cant write custom kittens in Go, custom kittens must be in Python,
at least if you want them to integrate with the kitty kitten mechanism.
They are loaded dynamically at runtime and as such must be in an
interpreted language as kitty does not ship with a compiler.

kitten consist of two parts, a standalone program (the main() function)
and the handle_result() function which is actually run in the kitty
process address space. You could technically write the main function
part in any language as it is just a regular program that runs in a tty.
But to integrate it with kitty you would still need to write a python
script with a main() and handle_result() functions that call the
program.
