### ISSUE TITLE
[ENHANCEMENT] deallocate ram used by icat kitten, automatically or via cli option

### ISSUE THREAD

**Issue by adpce** [kovidgoyal/kitty#6627]
**Is your feature request related to a problem? Please describe.**
`kitty +kitten icat --clear` does not free the ram space allocated by previous invocations of the command, resulting in #6616
(The overuse of ram results in killing any open instances of Brave Browser, FreeTube, Steam, and causing them to insta-crash on reopen attempts (Firefox based browsers are strangely immune)
the icat kitten can no longer be invoked without having an issue)

**Describe the solution you'd like**
An additional option to icat, or modify the existing --clear option

**Describe alternatives you've considered**
Clearing the ram automatically when icat exits
Monitoring ram and clearing non-essential use when a certain threshold is met

**Additional context**
The only reason this is a concern is that it makes the recommended lf cleaner script totally ineffective
`kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty`
does absolutely nothing to address the mountain of ram that kitty is silently hoarding

Thank you for your time

**Comment by kovidgoyal** [comment]
icat does not use RAM, its not a persistent process. The terminal
emulator will temporarily use RAM to display visible images. But even
there, thats just while loading the image to send tot he GPU after which
the RAM is freed, images are cached on disk not in RAM. 

icat --clear does delete currently visible images from the terminal
emulator.  If you think it doesnt, then come up with a reproducer
demonstrating the issue not involving third party software like lf.
