### ISSUE TITLE
A kitten that uses the graphics protocol to draw a horizontal divider above each prompt

### ISSUE THREAD

**Issue by snoblenet** [kovidgoyal/kitty#6628]
**Is your feature request related to a problem? Please describe.**

I'd love to be able to easily draw a full-width horizontal divider above my shell prompt.

I'm hoping that Kitty's Terminal Graphics Protocol makes this practical.

**Describe the solution you'd like**

`kitty +kitten divider-above-prompt`

**Describe alternatives you've considered**

I've considered trying to hack my preferred prompt framework, Starship, to simulate this using Unicode characters.

**Additional context**

I currently have this:

![image](https://github.com/kovidgoyal/kitty/assets/62277/c07c4694-613d-4972-8ede-c5048574f409)

I am trying to create this:

![image](https://github.com/kovidgoyal/kitty/assets/62277/38ac014b-fe49-4344-823f-25cb7de51349)

**Comment by kovidgoyal** [comment]
You dont need graphics for this. You don't need even starship for this.
Simply use a multiline prompt the first line of which is your divider.
The exact details of how to implement it will depend on what shell you
are using. But even something as simple as 
PS1="------------\nactual prompt"

will basically do the trick replace - above with the box drawing char for
horizontal line and use your shells prompt drawing hook function to
change the number of chars drawn to match the width of the terminal.

**Comment by snoblenet** [comment]
Thanks. I've come up with something that looks quite good using Starship's 'fill' module:

https://starship.rs/config/#fill
