### ISSUE TITLE
Can't type Norwegian characters

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#663]
I'm on a macbook with a Norwegian keyboard and when i enter the keys `æøå`, they come out as `C&C8C%`, the same happens when i try to paste it using `ctrl-shift-v`. Forward ticks `´` does not work either and outputs `B4`. Are these unicode characters not supported by typing on the keyboard or am i missing something.

I'm on kitty  0.11.1. macOS 10.13.4. I'm using an empty kitty.conf.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.macos_option_as_alt

**Comment by erf** [comment]
The problem persist wheter `macos_option_as_alt` is set to `yes` or `no` @kovidgoyal

**Comment by kovidgoyal** [comment]
Works for me, steps I tried:

1) Run kitty as 
kitty --config NONE -o macos_option_as_alt=n

2) Press Option key + a
kitty displayed `å` at the prompt, as expected

**Comment by erf** [comment]
If i run `kitty --config NONE -o macos_option_as_alt=n` from a kitty terminal, then i'm able to type `æøå`, as long as i have set: `export LANG=no_NO.UTF-8` in `.bash_profile`. This does not work in the inital kitty terminal though ( i have a `kitty.conf` with only `macos_option_as_alt no` set ). If `LANG` was not set, when opening a new kitty with that command i get the message `Failed to set locale with LANG: en_NO.UTF-8`. Not sure if im missing some environment variables.
On a side note, when closing the second terminal, the first one still hangs on the kitty command that was run.

**Comment by kovidgoyal** [comment]
You need to set the LANG env var system wide. Setting it in your shells startup files is useless, since kitty runs before the shell.

**Comment by erf** [comment]
I set the `LANG` in `/etc/profile` and it's now working. It would not be possible to set this in `kitty.conf`? Thanks.

**Comment by maximbaz** [comment]
You probably want that to have this effect for all apps, not for kitty alone, that's why putting it in `/etc/profile` is better.
