### ISSUE TITLE
[feat-req] automatically switch to another them when the kitty window is maximized

### ISSUE THREAD

**Issue by philiparvidsson** [kovidgoyal/kitty#6630]
**Is your feature request related to a problem? Please describe.**
I use a certain color theme when I have my kitty in the scratchpad (running i3), which works well. It works less well when the window is maximized.

**Describe the solution you'd like**
When the window is maximized, I would like for kitty to automatically switch to a different them, and then back again when the window is restored.

**Describe alternatives you've considered**
I've considered running external scripts and polling the wm state of the window but it doesn't really sit well with me.

**Additional context**
n/a

**Comment by kovidgoyal** [comment]
If you are using i3, have whatever binding/commadn in i3 is maximizing
the window also change its colors using the kitty remote control API.

**Comment by philiparvidsson** [comment]
that binding is used to maximized any window that is focused, so maximizing any window would switch the kitty theme, I think.

**Comment by kovidgoyal** [comment]
In your binding, run a script, have the script query i3 for the
currently active window and only then maximize it. And if the window is
a kitty window, use remote control to do whatever you want to it,
including changing its colors.
