### ISSUE TITLE
kitty won't run programs or scripts that use bluetooth permission on MacOS Ventura

### ISSUE THREAD

**Issue by dmose** [kovidgoyal/kitty#6632]
**Describe the bug**
kitty won't run programs or scripts that use bluetooth permissions.

**To Reproduce**
1. Follow the instructions to set up and run this python script
2. Observe python aborting: `[1]    49355 abort      python EBYT.py`.
3. Check the MacOS abort dialog, and see this text:

```
Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.
```

**Environment details**
```
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Darwin MacBook-Pro-von-Dan.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		13.5.2 BuildVersion:		22G91
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                de_AT.UTF-8
	SHELL                               /bin/zsh
	USER                                dmose3
```

**Additional context**
Using `kitty --config NONE` doesn't fix the problem.

I can reproduce this with both Python 3.9 and Python 3.10.

Perhaps this is the same problem needing the same fix described in https://github.com/hbldh/bleak/issues/761#issuecomment-1036437107 ?

**Comment by kovidgoyal** [comment]
What does this have to do with kitty? You need to package your python
script into an app and add the requisite permissions into its
Info.plist.

**Comment by dmose** [comment]
This doesn't happen in (eg) Terminal.app.  I'd guess that use case is so that people can use cross-platform scripts that were developed by someone else on Linux or Windows without creating a plist file (as I was in this case).

**Comment by dmose** [comment]
Thank you!

Am Mo., 18. Sept. 2023 um 10:03 Uhr schrieb Kovid Goyal <
***@***.***>:

**Comment by outofambit** [comment]
@kovidgoyal thank you for already fixing this! i just ran into this yesterday. (and thanks @dmose to reporting it before me)
