### ISSUE TITLE
Add Option to let Characters bleed into other cells

### ISSUE THREAD

**Issue by jam1015** [kovidgoyal/kitty#6634]
**Is your feature request related to a problem? Please describe.**

I know you have discussed this. I know you will be annoyed. Please listen to me.

It is related to a problem.  Italic/oblique versions of fonts get cut off at the edge of cells.    

The obliqueness makes them run over into the next cell, the part that tries to overflow gets cut off. 

**Describe the solution you'd like**

I would like a config option to let characters bleed into adjacent cells. I know that you have written that it 

> 'is fine if the neighboring cell is empty, but looks terrible if it is not'.

I would add that it is also fine if the font you're using is designed to leave space at the beginning of cells for bleed-over from previous cells.  

Beautiful oblique handwriting on an actual page has precisely this property (overflow into the empty vertical space of the next character). This aesthetic is precisely what oblique and italic fonts are designed to capture, and the overflow into the next cell is what is necessary to let this property shine through, albeit in a slightly crude way.

I propose that you add an option to allow character overflow, but leave it turned off as a default setting.  I know that you think this character overflow, looks bad, but your users are very diverse of opinion.

**Describe alternatives you've considered**

Not using italic fonts.

**Additional context**

Thank you so much for writing the best terminal emulator!

**Comment by kovidgoyal** [comment]
I'm afraid my opinion on this has not changed.

**Comment by jam1015** [comment]
Sorry, you're right. I thought it would be a simple fix like 'delete an if statement' but I read more about the issue and I see that it is not so simple to fix.
