### ISSUE TITLE
SVG rendering support

### ISSUE THREAD

**Issue by spacekookie** [kovidgoyal/kitty#664]
So this is a bit of a weird one. 

I found this tool here: https://github.com/lunaryorn/mdcat which can render SVGs from markdown files on the terminal to easily read. 

But this feature is currently only supported in iTerm and [Terminology](https://www.enlightenment.org/about-terminology) and I was wondering if it would be possible for you to port this feature to kitty as well.

**Comment by kovidgoyal** [comment]
Youcan render any arbitrary graphics including SVG in kitty, https://sw.kovidgoyal.net/kitty/graphics-protocol.html
