### ISSUE TITLE
Bold is Bright vt102/ECMA35/48

### ISSUE THREAD

**Issue by Daemoen** [kovidgoyal/kitty#6641]
**Describe the bug**
Kitty ignores the vt102/ECMA35/48 standards and instead uses AIX extension definitions for bold/bright distinguishment, with *no* option to enable the industry standard convention.

**To Reproduce**
1. Install kitty

**Screenshots**
Not relevant

**Environment details**
```
Not relevant
```

**Additional context**
I've read through all of these arguments, and I must say, for folks who want to talk about following standards, you guys are just being jerks about it.  The purpose of a terminal emulator is to interact with a remote session console on a *nix* based platform.  The nix consoles have *always* used vt102/ECMA35/48, NOT aix extensions for their standard.  I actually came across all of these issues today because I still actively mud and use tintin when I am at work.  Imagine my surprise and disappointment to discover that kitty knowingly ignores the *actual standards* that it claims to be trying to enforce.  Completely messes up the way the games look, which of course impacts enjoyment.  You say that it is not 'kitty's fault' that everyone else does it wrong.  I call bologna.  The actual standards have always been based on vt102 and Ecma48.  You're the ones that broke the expected standard.  That isn't to say that your implementation is necessarily hideous, it does follow a different standard (aix extensions), but that is not what most consoles are designed according to.  Look at almost any of the terminal programs that are older, they follow the ECMA standards accordingly (SGR-1), not AIX.  It's also why when color was introduced to muds in the mid 90s, it used the bold sequence, because it was what was defined, even back then.

You have repeatedly seen people ask you to support the *Industry* standards.  You refuse to do so.  I am quite sad that I will not be able to enjoy kitty the same way I have enjoyed Calibre over the years, all because pride seems to be getting in the way.

**Comment by kovidgoyal** [comment]
Yes, I'm a jerk, don't use my sofrware.
