### ISSUE TITLE
kitty +kitten ssh: GLIB_2.27 not found on remote system

### ISSUE THREAD

**Issue by ecerulm** [kovidgoyal/kitty#6642]
**Describe the bug**

When I use `kitty +kitten ssh` with kitty 0.30, the kitty that is  install/built in the remote system does not work (GLIBC_2.27 not found)

The remote system is Amazon Linux 2 ( https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-al2.html, which comes with glibc 2.26-63)

 ```
kitty +kitten ssh xxxx
[ec2-user@xxx]$ kitty 
/home/ec2-user/.local/share/kitty-ssh-kitten/kitty/install/bin/kitty: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/.local/share/kitty-ssh-kitten/kitty/install/bin/../lib/libpython3.9.so.1.0)
```

Is there a way to get a kitty kitten to install a kitty compatible with glibc 2.26 on the remote system?

If not, could it be possible to refuse to install kitty on the remote instead? 

Then, should I just remove `/home/ec2-user/.local/share/kitty-ssh-kitten` ? 

**To Reproduce**
1. XXX
2. YYY
3. ZZZ

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Do not run your kitten as

kitty +kitten whatever

Just run

kitten whatever

and you will be fine. The kitten binary does not link against glibc
unlike the kitty binary.

**Comment by ecerulm** [comment]
That worked! 

```
kitten ssh xxxx
[ec2-user@xxx]$ kitten @set-tab-title "xxxx" 
```
