### ISSUE TITLE
Text rendering not sharp

### ISSUE THREAD

**Issue by duhd1993** [kovidgoyal/kitty#6643]
**Describe the bug**
Might not be a bug, but from my poor eyesight, I can feel that Kitty text rendering is not as sharp as alacritty on low resolution(1080P).

**To Reproduce**
ls a folder

**Screenshots**
![CleanShot 2023-09-21 at 18 09 28](https://github.com/kovidgoyal/kitty/assets/2936633/32552eab-a858-4c1d-822d-3b3aa372d361)

Not because it's thicker, but it has some artifacts at corners
<img width="977" alt="image" src="https://github.com/kovidgoyal/kitty/assets/2936633/dd1698eb-0ce3-4501-adb7-ec4c06c7793b">
This is improved when I change text_composition_strategy to legacy. Should I stick to this setting? 
![image](https://github.com/kovidgoyal/kitty/assets/2936633/107fa21e-7fe3-461a-8e1b-80dcd1f7e5f9)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
<details>
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.3.1 ProductVersionExtra:	(a) BuildVersion:		22E772610a
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/username/.config/kitty/kitty.conf

Config options different from defaults:
bold_font                          JetBrainsMono Mono Bold
bold_italic_font                   JetBrainsMono Mono Bold Italic
copy_on_select                     clipboard
font_family                        JetBrainsMono Mono
font_size                          13.0
initial_window_height              (720, 'px')
initial_window_width               (960, 'px')
italic_font                        JetBrainsMono Mono Italic
macos_quit_when_last_window_closed True
macos_titlebar_color               1
remember_window_size               False

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.HBhqGS9ied/org.xquartz:0
	USER                                username

</details>

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
kitty does not do sub-pixel antialiasing, so at very low resolutions
text is not going to look as smooth. And yes you can play with
text_composition_strategy to find whatever look suits your tastes the
most.
