### ISSUE TITLE
GLIBC dependencie not found when building from source

### ISSUE THREAD

**Issue by zuble** [kovidgoyal/kitty#6644]
Hi
Trying to build from source in a ubuntu 16.04 lts , but errors related to glibc version being outdated

```
(base)~/Downloads/kitty$ ./dev.sh build
Downloading linux-64.tar.xz
Dependencies downloaded. Now build kitty with: make develop
~/Downloads/kitty/dependencies/linux-amd64/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /Downloads/kitty/dependencies/linux-amd64/lib/libpython3.9.so.1.0)
~/Downloads/kitty/dependencies/linux-amd64/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by ~/Downloads/kitty/dependencies/linux-amd64/lib/libpython3.9.so.1.0)
~/Downloads/kitty/dependencies/linux-amd64/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by ~/Downloads/kitty/dependencies/linux-amd64/lib/libpython3.9.so.1.0)
The following build command failed: ~/Downloads/kitty/dependencies/linux-amd64/bin/python setup.py develop
exit status 1

(base) ~/Downloads/kitty$ go version
go version go1.21.1 linux/amd64

(base) ~/Downloads/kitty$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

The same error if i follow th ebinarie install.

**Comment by kovidgoyal** [comment]
GLIBC on your system is too old, you will need to build the dependencies
from source yourself as the pre-built ones require newer glibc than you
have.

**Comment by elkarouh** [comment]
Hi Kovid,
I have the same problem.
I run Redhat 7 at work and it is impossible to upgrade.
Wasn't it a selling point of the go language that it could provide self-contained static libraries ?

**Comment by kovidgoyal** [comment]
This has nothing to do with Go. kitty uses lots of non Go code.

**Comment by elkarouh** [comment]
A lot of potential kitty users are stuck with old distributions.
For the time being, I will stick with Wezterm which provides an  AppImage.

**Comment by kovidgoyal** [comment]
Appimages also require glibc this is a fundamental limitation of glibc on linux. Any binary built using any method including appimage will require glibc >= version of glibc it was built against.

**Comment by kovidgoyal** [comment]
Oh and kitty comes with pre-built binaries too: https://sw.kovidgoyal.net/kitty/binary/

**Comment by elkarouh** [comment]
I tried the prebuilt binaries. They failed because they rely on the
installed glibc version.
I had to use kitty-0.23.1-x86_64.txz to get a working version.

**Comment by kovidgoyal** [comment]
Exactly with pre-built binaries on linux your system has to have glibc
at least as new as the glibc in the system thebinaries were built
against.
