### ISSUE TITLE
DPI setting option for kitty.conf file

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#6648]
Hello Expert,

I know Kitty use most of the common setting from the native OS but is it possible to have a DPI config option like we have in Alacritty? it helps make text look crisp and sharp. Can we have similar feature in upcoming kitty

-Praveen

**Comment by kovidgoyal** [comment]
DPI has no relevance to how sharp or not text looks. You want
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy

**Comment by ciscohack** [comment]
@kovidgoyal Thanks Kovid.. but this is a setting option as I understand is for light themes right for dark there is no much different.. I also tried this option "text_fg_override_threshold"  but this option in dark theme is increased to 1% cause some white border or area popped in looks bad

**Comment by ciscohack** [comment]
"text_composition_strategy" This option I was thinking is the replacement of the thicken_font option which helps to determine the font weight

**Comment by kovidgoyal** [comment]
No text_composition_strategy works for both light and dark and controls
how thick you will perceive the text to be.

**Comment by ciscohack** [comment]
@kovidgoyal thanks it has 2 value can u please help me to know which is for font thickness and what is the use of other value

**Comment by ciscohack** [comment]
If I try text_fg_override_threshold and set it to value 2...my prompt gets ugly with this

<img width="185" alt="image" src="https://github.com/kovidgoyal/kitty/assets/11479557/75617a61-f4a2-4ead-a5d5-8bf01067a37d">

**Comment by ciscohack** [comment]
> @kovidgoyal thanks it has 2 value can u please help me to know which is for font thickness and what is the use of other value

I found the answer first value is Gamma and second is for contrast right

**Comment by tariks** [comment]
A DPI setting would still be useful for correct font sizing on HiDPI displays.

For example, I use BetterDisplay to enable full 254 dpi from the macbook's native 3024x1964 while scaled at more readable resolutions. I found that kitty fonts needed twice the font_size values to render the same sizes as wezterm, which allows setting dpi. The kitty sizes were similar to wezterm's when default settings (96 or 144 dpi) were used.

It would be wonderful to have this in kitty :)

**Comment by ciscohack** [comment]
> A DPI setting would still be useful for correct font sizing on HiDPI displays.
> 
> For example, I use BetterDisplay to enable full 254 dpi from the macbook's native 3024x1964 while scaled at more readable resolutions. I found that kitty fonts needed twice the font_size values to render the same sizes as wezterm, which allows setting dpi. The kitty sizes were similar to wezterm's when default settings (96 or 144 dpi) were used.
> 
> It would be wonderful to have this in kitty :)

Hi Tarik,

Thanks for the input. Can you provide me with some information about your scaling method? As a MacBook Pro user, I am interested in learning how to utilize Betterdisplay to achieve the full potential of my 254 DPI capability. Although I have attempted to use the software, I have not been able to locate any manual DPI setting. While I can alter the resolution using the native Mac display, I am curious to know how to use the software to its fullest extent. Additionally, what resolution setting do you recommend for a clear font and legible experience throughout the entire system?

When I install Betterdisplay I didn't find any special in it which I can do with native display option so uninstall. I hope you will help me to understand what you already been explored and using

**Comment by tariks** [comment]
As I understand it, macOS disables HiDPI on resolutions that aren't convenient ratios of native, and BetterDisplay circumvents this. I mainly use it for adjusting color, gamma, and contrast though.

I think, but am not sure, that many programs assume a standard dpi or do not notice HiDPI, resulting in much larger font sizes to get the same rendering as iterm (makes sense iterm would account for retina displays) or wezterm (with dpi manually defined in config).

I like bigger words for my aging eyes. My BetterDisplay/macbook/kitty settings work great with half-native resolution / HiDPI enabled (don't need better display necessarily) / font_size anywhere from 24-32 depending on font rotation [Terminus, Prestige, Operator, Edlo, and Dank Mono].

Finally I have some accessibility hotkeys for zooming in, these can be set in macOS system settings.

**Comment by ciscohack** [comment]
@tariks Thanks a lot for your response. what is your resolution on Mac? Is there any possibility I can use your setting to test on my device? I don't see gamma and contrast settings in my BetterDisplay why?

**Comment by tariks** [comment]
Default resolution is 1512x964, which is half of native. With or without BetterDisplay, this setting should result in four physical pixels per logical pixel, or "HiDPI on." BD would make the same true for other resolutions as well. Turning the HiDPI on or off in BD results in noticeable sharpening or blurring of text across programs.

Most BD features require the pro version, and some need to be enabled in settings to be seen.

**Comment by ciscohack** [comment]
> Default resolution is 1512x964, which is half of native. With or without BetterDisplay, this setting should result in four physical pixels per logical pixel, or "HiDPI on." BD would make the same true for other resolutions as well. Turning the HiDPI on or off in BD results in noticeable sharpening or blurring of text across programs.
> 
> Most BD features require the pro version, and some need to be enabled in settings to be seen.

Thanks!

**Comment by ciscohack** [comment]
@kovidgoyal I was conducting a small test to compare the text rendering of Kitty and Alacritty side by side. It was evident to me that Alacrity produced sharper and higher quality text rendering compared to Kitty. This could possibly be due to the DPI setting that Alacrity has and missing on our kitty term or some other optimisation in code in Alacritty. But I think you can take a look and make kitty text rendering to next level.

Alacritty:--
<img width="532" alt="image" src="https://github.com/kovidgoyal/kitty/assets/11479557/fa3a9c68-b5ef-46cf-b7c5-2d48b3b47c81">

In Kitty text looks a little dull compared to Alacritty, I tried the text_composition option platform and the legacy no difference platform makes text thick while legacy makes it thin is the only difference.
Kitty:--
<img width="590" alt="image" src="https://github.com/kovidgoyal/kitty/assets/11479557/d1459040-a2b4-435c-b7cf-16f2f2df6134">

**Comment by ciscohack** [comment]
@kovidgoyal Any input on this? in 2 screenshots you can see clear differences right? 

One more Question:- can I install Kitty nightly build through "brew install --cask"   cannot find any doc for the same.

**Comment by kovidgoyal** [comment]
No input. Your screenshots have different background colors, foreground colors and different font sizes and different cell spacings. Again use a color picker and actually match settings correctly if you want to compare. Though I will leave with saying: looking is alacritty is not a design goal for kitty. Unlike alacritty kitty gives you all the knobs to actually tune how fonts are rendered. Use them.
