### ISSUE TITLE
Deprecate hyperlinked ripgrep kitten

### ISSUE THREAD

**Issue by tim-hilt** [kovidgoyal/kitty#6653]
With https://github.com/BurntSushi/ripgrep/issues/665 being closed by https://github.com/BurntSushi/ripgrep/pull/2483, I think the hyperlinked ripgrep kitten can be deprecated 🎉 

I just tried it out with ripgrep-master and it seems to work just fine: Clicking on any filename after running `rg --hyperlink-format kitty test` just opens up the file in `$EDITOR`.

I'd like to learn more about kittys link-functionality and a quick search didn't yield a doc-result for me. Can you help out @kovidgoyal ?

**Comment by kovidgoyal** [comment]
Link opening customization is fully documented at
https://sw.kovidgoyal.net/kitty/open_actions/
