### ISSUE TITLE
macOS: Question mark in cube icon are not rendered

### ISSUE THREAD

**Issue by ivankovnatsky** [kovidgoyal/kitty#6654]
**Describe the bug**

I'm not 100% sure this is a bug, though it does not render for some reason.

**To Reproduce**

1. macOS ?
2. Nerd Font icons ?
4. Not rendered icon

**Screenshots**

In Terminal it's rendered normally: 
<img width="201" alt="image" src="https://github.com/kovidgoyal/kitty/assets/75213/462c4b48-0609-469d-bea3-c59abc1d5a06">

It does work in iTerm2 as well.

Kitty:
<img width="201" alt="image" src="https://github.com/kovidgoyal/kitty/assets/75213/5b9e515f-bc1f-43db-aa8f-45f70bd3e425">

**Environment details**

```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin Ivans-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.6 BuildVersion:		22G120
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ivan/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select                 clipboard
cursor_blink_interval          0.0
font_family                    Hack Nerd Font Mono
font_size                      13.0
hide_window_decorations        2
macos_menubar_title_max_length 1
macos_option_as_alt            3
modify_font:
    cell_height 115%
tab_bar_edge                   1
tab_title_template             {index}: {tab.active_exe}
window_margin_width            FloatEdges(left=0.5, top=0.5, right=0.5, bottom=0.5)
Changed shortcuts:
	cmd+1 →  goto_tab 1
	cmd+2 →  goto_tab 2
	cmd+3 →  goto_tab 3
	cmd+4 →  goto_tab 4
	cmd+5 →  goto_tab 5
	cmd+6 →  goto_tab 6
	cmd+7 →  goto_tab 7
	cmd+8 →  goto_tab 8
	cmd+9 →  goto_tab 9

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                ivan

```

**Additional context**

Same with `kitty --config NONE`

<img width="201" alt="image" src="https://github.com/kovidgoyal/kitty/assets/75213/e0000128-2ce6-4f15-991e-91475a651cc3">

**Comment by kovidgoyal** [comment]
First, update kitty you are running a fairly old version.

Secondly, follow the instructions about nerd fonts in the kitty FAQ
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font 

Thirdly, what unicode code point is that? Without that I have no way to
reproduce the issue. Start kitty with --dump-bytes and output reproduce
the issue and attach the dump.

**Comment by ivankovnatsky** [comment]
Thanks, actually my bad, that is a how kitty just renders an symbol font does not have a variant for it 🤦 .
