### ISSUE TITLE
the default ctrl+shift+page_up/page_down/home/end doesn't work

### ISSUE THREAD

**Issue by Cxcl00** [kovidgoyal/kitty#6656]
**Describe the bug**
the default key mapping doesn't work

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/126314224/f8cb9efd-83eb-42ce-8aaf-0502d9aa9d05)

**Environment details**
![image](https://github.com/kovidgoyal/kitty/assets/126314224/846939b7-40b0-4107-bad5-2dfae5c558cf)

**Additional context**
other default keymappings work well except the keymapping about keypad.
I have tried many methods, but nothing works. Can you tell me what to do

**Comment by kovidgoyal** [comment]
I cannot reproduce, the default mappings work fine. I cannot see what you have changed in your config since you posted only a screenshot. Paste the actual output which is automatically copied to clipboard, or just run 

kitty --config NONE

to verify the problem is in your config.

**Comment by Cxcl00** [comment]
![image](https://github.com/kovidgoyal/kitty/assets/126314224/c4eb8fde-b29c-4fa9-b8cd-f95f05a92971)
this is my config and result after run kitty --config NONE

**Comment by kovidgoyal** [comment]
Again doesnt reproduce for me. Presumably your system isnt actually generating the right key events. Use kitty --debug-input to see what events kitty is receiving.

**Comment by Cxcl00** [comment]
Thank you for answering my question

this is the output of kitty --debug-out, I just hit ctrl+shift+home 

![image](https://github.com/kovidgoyal/kitty/assets/126314224/b844778e-6e47-4a60-a3ea-b2c1a8de6712)

**Comment by kovidgoyal** [comment]
You are pressing keypad home not home. The default bindings dont include keypad keys. Create your own bindings for that in kitty.conf using the map directive.

**Comment by Cxcl00** [comment]
I see,Thank you！！！
