### ISSUE TITLE
Can kitty (possibly) be built using system's GLFW?

### ISSUE THREAD

**Issue by jeandudey** [kovidgoyal/kitty#6657]
I want to know if kitty could be built using the system's GLFW library, because it's vendored on the repository but I don't know if any kitty specific patches have been applied to it. Mainly I'm looking into modifying the build process if necessary to support it.

My use case is packaging recent versions of Kitty on GNU Guix and it already provides GLFW so I think it's best to take advantage of the already built GLFW library.

**Comment by kovidgoyal** [comment]
No, there are tons of kitty specific patches.
