### ISSUE TITLE
How to Change the Resize Keys in Resize Mode

### ISSUE THREAD

**Issue by IstoMan** [kovidgoyal/kitty#6658]
When you go into resize mode then we get this right:
``` 
Press one of the following keys:
  Wider
  Narrower
  Taller
  Shorter
  Reset
``` 
But is there a way in which we can change the keys ?  _more like vi_
in the documentation it gives a command like 
```
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3
# reset all windows in the tab to default sizes
map ctrl+home resize_window reset
```
but i don't want to use the control keys as it conflicts with other programs of mine

**Comment by kovidgoyal** [comment]
You dont have to use ctrl use whatever you like. And no the keys used by
the resize kitten cant be configured, they correspond to letters from
the words.
