### ISSUE TITLE
Round font size to partly eliminate padding

### ISSUE THREAD

**Issue by jryom** [kovidgoyal/kitty#6659]
**Is your feature request related to a problem? Please describe.**
When the window size is not an exact multiple of the cell size, the cell area has padding on the sides, which can be significant in some cases.

**Describe the solution you'd like**
It would be great to have the option to round the cell size up or down to the nearest match so either vertical or horizontal padding could be eliminated. It could be something like
`round_font_size_to_match`: `vertical | horizontal` or something similar.

**Describe alternatives you've considered**
Currently, the option to change the `placement_strategy` of the cell area is possible, which is nice, but that still leaves a lot of padding around the cell area in many cases.

**Comment by kovidgoyal** [comment]
Not something I am interested in, note that window size can be a prime
multiple so you cannot even in theory ever remove all padding no matter
what cell size you end up with.

**Comment by WieeRd** [comment]
Theoretically, [subpixel positioning](https://github.com/microsoft/terminal/issues/15805) could allow us to perfectly fill the screen even with a prime number window size.
But that is yet another non-trivial thing to implement that could impact the performance when poorly implemented.
I guess this feature won't be happening anytime soon in any terminal.

**Comment by kovidgoyal** [comment]
I suggest you simply set your terminal background color to the editor background color then you wont even notice the padding. This can be done dynamically in the editor config by using escape codes. If you do a bit of googling you should find other issues where I have described how to do it.
