### ISSUE TITLE
Kitty terminal unusually bright

### ISSUE THREAD

**Issue by tdljayden** [kovidgoyal/kitty#6665]
**Describe the bug**
After updating to kitty version 0.28.0, and also 0.28.1, 0.29.0, and 0.30.0, the colours are unusually bright and garish, with some artifacting. The issue is not present on 0.27.1.

**To Reproduce**
1. Emerge kitty on gentoo, using the Wayland USE flag.
2. Either emerge a version of 0.28.0 or later, or test a binary from the releases page.
3. Test the 0.27.1 binary from the github releases page.
4. Compare. Use a theme to see the difference if necessary.

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/110114652/0077281b-cc14-48b1-a7c0-00298e428402)
On the left is kitty version 0.27.1 where colours are proper and more in line with the nord theme on my system. On the right is kitty version 0.30.0, where there is strange artifacting on the fonts, and generally unusually bright colours. I have tested with various binaries from the github releases page and discovered that the issue manifests in version 0.28.0 onwards, and I hoped updating past that would fix it.

**Environment details**
```
kitty 0.30.0 created by Kovid Goyal
Linux JAYDEN-PC-GENTOO 6.1.55-gentoo-dist #1 SMP PREEMPT_DYNAMIC Sat Sep 30 18:18:29 BST 2023 x86_64

This is JAYDEN-PC-GENTOO (Linux x86_64 6.1.55-gentoo-dist) 12:41:31

DISTRIB_ID="Gentoo"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/tdljayden/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.5
editor             nvim
font_family        JetBrains Mono Nerd Font
input_delay        1
shell              zsh
shell_integration  frozenset({'enabled'})
Colors:
	background         #2e3440   
	color0             #3b4252   
	color1             #bf616a   
	color10            #a3be8c   
	color11            #ebcb8b   
	color12            #81a1c1   
	color13            #b48ead   
	color14            #8fbcbb   
	color15            #eceff4   
	color2             #a3be8c   
	color3             #ebcb8b   
	color4             #81a1c1   
	color5             #b48ead   
	color6             #88c0d0   
	color7             #e5e9f0   
	color8             #4c566a   
	color9             #bf616a   
	cursor             #81a1c1   
	foreground         #d8dee9   

Important environment variables seen by the kitty process:
	PATH                                /bin:/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/16/bin:/usr/lib/llvm/15/bin:/etc/eselect/wine/bin
	LANG                                en_US.utf8
	EDITOR                              nvim
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                tdljayden
	XCURSOR_SIZE                        2
	XDG_SESSION_TYPE                    wayland
	XDG_RUNTIME_DIR                     /home/tdljayden
	XDG_CURRENT_DESKTOP                 Hyprland
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_DATA_DIRS                       /usr/local/share:/usr/share:/etc/eselect/wine/share
	XDG_BACKEND                         wayland

```

**Additional context**
The issue is present with `kitty --config NONE` aswell.
![image](https://github.com/kovidgoyal/kitty/assets/110114652/4164ee7a-602a-4320-b67f-023219daa199)
You can see the issue is more subtle, but still present.

**Comment by kovidgoyal** [comment]
Read the changelog with reference to text_composition_strategy.

**Comment by tdljayden** [comment]
> Read the changelog with reference to text_composition_strategy.

I set text_composition_strategy to legacy, and although the glyphs look different, the core issue of bright colours still persists.

**Comment by tdljayden** [comment]
Messing around with the numbers in text_composition_strategy also only seems to change the text rendering, but not the colour issues.

**Comment by kovidgoyal** [comment]
There are no changes in color rendering, only glyph composition. In any
case colors in kitty are completely customizable, adjust your color
theme to whatever brightness you like.

**Comment by kovidgoyal** [comment]
> The issue is with how kitty handles transparency. When setting `background_opacity` to 1 the colours are comparable.

yes as I said composition has changed for better text rendering. You will need to adjust colors a little to compensate, see the various issues around text_composition_strategy in the issue tracker.

**Comment by tdljayden** [comment]
Yes I understand, I have customised the background colour to compensate for rendering changes affecting transparency, and I have customised the text_composition_strategy to what I think looks best. Thank you.
