### ISSUE TITLE
Mapping scroll wheel

### ISSUE THREAD

**Issue by derenv** [kovidgoyal/kitty#6667]
**Is your feature request related to a problem? Please describe.**
I would like to be able to map scroll wheel to commands - i.e. i want to be able to map `left ctrl + scroll up` and  `left ctrl + scroll up` to font increase/decrease size.

**Describe the solution you'd like**
Add a mouse event for scroll up and scroll down (or if this exists, make this clearer in the config file or documentation)

**Comment by kovidgoyal** [comment]
Not something I care to spend time on, patches welcome.

**Comment by scippio** [comment]
I can't use kitty witout this... do you have a solution? @derenv ?
