### ISSUE TITLE
--hold option

### ISSUE THREAD

**Issue by ReiLucio** [kovidgoyal/kitty#667]
There is something similar to the `--hold` parameter?
I wanna do something like `kitty --hold -e commandX`

Thnx

**Comment by kovidgoyal** [comment]
What is `--hold` supposed to do?

**Comment by kovidgoyal** [comment]
```
kitty sh -c "systemd-analyze; read"
```

**Comment by ReiLucio** [comment]
Thank you Sir i really appreciate your tools.
