### ISSUE TITLE
Keyboard shortcuts for moving across windows in a layout

### ISSUE THREAD

**Issue by anupambhatnagar** [kovidgoyal/kitty#6675]
I'm using the tall layout with multiple sub-windows in a window. Are there any predefined keyboard shortcuts to move across the sub-windows? If not, could you provide an example on how to define them? Thanks!

**Comment by kovidgoyal** [comment]
Read the help: https://sw.kovidgoyal.net/kitty/overview/#windows

**Comment by anupambhatnagar** [comment]
nvm, figured it out! I had some system re-mappings which were conflicting with kitty mappings.
