### ISSUE TITLE
ssh kitten not echoing when connecting to QNAP

### ISSUE THREAD

**Issue by warpspin** [kovidgoyal/kitty#6678]
**Describe the bug**
Whenever I use the ssh kitten to connect to a QNAP (based on Linux 5.10.60), the resulting shell (bash 3.2.57)  is not echoing any characters anymore. Using regular "ssh" to that server will have no problems though.

I already tried disabling shell_integration in the settings for that host and unset $TERMINFO on the server, which is the only substantial difference in the environment, to no avail.

Something must be happening during the login which disables the echo and does not re-enable it. Target system unfortunately does not have "stty", too, so that's no way to fix that easily via the .profilerc

No clue where to look next on how to fix this. Will accept any help on that, cause it's annoying to have to use a different alias to connect to those hosts than my default.

Alternatively, maybe a setting in ssh.conf could help, which simply disables any special behaviours and falls back to regular ssh for a matching hostname.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.delegate

**Comment by warpspin** [comment]
Ooops, thanks, totally did not see that in the docs.
