### ISSUE TITLE
Kitty crashed using Julia and KittyTerminalImages on M1 Mac

### ISSUE THREAD

**Issue by tallakt** [kovidgoyal/kitty#6679]
**Describe the bug**
Kitty crashed using Julia and KittyTerminalImages on M1 Mac

**To Reproduce**
1. Run Julia 1.9
2. ``using KittyTerminalImages```
3. After a while, Kitty will crash without warning, then a dialog offering to restart

**Screenshots**
N/A

**Environment details**
```
kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
Darwin pi.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.6 BuildVersion:	21G115
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/tallakt/.config/kitty/kitty.conf

Config options different from defaults:
font_family          Inconsolata for Powerline
font_size            20.0
shell                /bin/zsh --login
Colors:
	background           #002b36   
	color0               #073642   
	color1               #dc322f   
	color10              #586e75   
	color11              #657b83   
	color12              #839496   
	color13              #6c71c4   
	color14              #93a1a1   
	color15              #fdf6e3   
	color2               #859900   
	color3               #b58900   
	color4               #268bd2   
	color5               #d33682   
	color6               #2aa198   
	color7               #eee8d5   
	color8               #002b36   
	color9               #cb4b16   
	foreground           #839496   
	selection_background #586e75   
	selection_foreground #002b36   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                tallakt

```

**Additional context**
This was working stably earlier. I am not sure why my Kitty started crashing, but I think it could be related to upgrading to Julia1.9. I get errors now with Julia1.8 as well, so maybe with some package I installed.

Still, I would expect Kitty to not crash altogether. So even with a faulty Julia package, Kitty itself should survive.

If there is any way I could collect more debug information on this, please let me know. I would be glad to help in any way possible.

**Comment by kovidgoyal** [comment]
Post the stack trace for the crash or a reproducer. Just click the erorr
report button on the crash message to get the stak trace or use
console.app

Of course best would be to post a script to reproduce the issue.

**Comment by kovidgoyal** [comment]
No followup, if you post either the stack trace or a reproducer I will re-open.

**Comment by tallakt** [comment]
It didnt crash yet. I will follow up next time
