### ISSUE TITLE
Error running kitty shell

### ISSUE THREAD

**Issue by LkeMitchll** [kovidgoyal/kitty#668]
Hi, I have a slightly weird issue.

I'm using the released .dmg version for mac (0.11.1), which presents a few issues. 

I cannot run the command`kitty` when launched from the app. I get 'command not found'. I fix this by adding a `macos-launch-services-cmdline` containing:

```
-o allow_remote_control=yes --listen-on unix:/tmp/kitty
```

...and then in `zsh` creating an alias:

```
alias k='/Applications/kitty.app/Contents/MacOS/kitty @ --to unix:/tmp/kitty '
```

This means I can run commands like `kitty @ new-window`, but I can't spawn a kitty shell. The shortcut `map ctrl+shift+escape kitty_shell window` does nothing. If I run `kitty` I get "command not found". This is even the same if I build from source and `python3 .`

If you need more info please let me know.

**kitty.conf**

```
# vim: set ft=conf:
font_family           FuraCode Nerd Font Medium
bold_font             FuraCode Nerd Font Bold
font_size             18.5
adjust_line_height    6
adjust_column_width   0

box_drawing_scale     0.001, 1, 1.5, 2
window_padding_width  10
window_margin_width  10

# Enable/disable the audio bell. Useful in environments that require silence.
enable_audio_bell no
# Allow kitty to be controlled via script
allow_remote_control yes

enabled_layouts tall:bias=60
startup_session ~/.config/kitty/system.conf

# Which edge to show the tab bar on, top or bottom
tab_bar_edge top

# The separator between tabs in the tab bar
tab_bar_style separator
tab_separator " | "

# Colorscheme
include theme.conf

# Keyboard shortcuts
kitty_mod               super

map kitty_mod+1         goto_tab 1
map kitty_mod+2         goto_tab 2
map kitty_mod+3         goto_tab 3
map kitty_mod+4         goto_tab 4

map alt+3               send_text all \u0023
```

**Comment by kovidgoyal** [comment]
The only way kitty could not be available in your PATH from within kitty is you have some shell startup file that is setting PATH without taking into account existing PATH values. Fix that and you will be fine.

kitty always injects itself into the PATH, if it is not already there, at startup. See line 201 onwards in kitty/main.py

**Comment by LkeMitchll** [comment]
@kovidgoyal Thanks for pointing that out. So i've now got may PATH updated properly, and `kitty` is being added to the PATH correctly. However, when I now do the `kitty_shell window` shortcut I get the following error:

```
Traceback (most recent call last):
  File "kitty/shell.py", line 206, in main
  File "kitty/shell.py", line 88, in __enter__
FileExistsError: [Errno 17] File exists
Press enter to quit...
```

Any ideas why?

**Comment by kovidgoyal** [comment]
That error does not make any sense, that file is supposed to exist. I'm guessing ti comes from that readline history file having been written by a different version of readline/libedit than the one that is reading it. You can workaround it by deleting the file, or use the commit I just pushed which ignores the error.

**Comment by LkeMitchll** [comment]
@kovidgoyal Turns out I had to delete `~/Library/Caches/kitty` to fix that `FileExistsError`
