### ISSUE TITLE
Kitty stuck with uwufetch

### ISSUE THREAD

**Issue by victorfernandesraton** [kovidgoyal/kitty#6681]
**Kitty is stucking when i use uwufetch**

**Steps to reproduce**
1. Install uwufetch version 2.1
2. run uwufetch -i

**Screenshots**
![ezgif com-video-to-gif](https://github.com/kovidgoyal/kitty/assets/43411882/bdaa0dc0-8fb8-463c-bc65-987e5c68c46b)
**Environment details**
```
OS: NixOS 23.05
Shell: Zsh
```

**Comment by kovidgoyal** [comment]
What does this have to do with kitty? Report the issue to uwufetch.
