### ISSUE TITLE
Compiling from source, kitty top window briefly 

### ISSUE THREAD

**Issue by ZontarOne** [kovidgoyal/kitty#6688]
**Describe the bug**
I am trying to build kitty from source on MacOS Ventura. 
After compiling, launching kitty results in kitty starting but the main window flashes for an instant then closes. 
Kitty is running, the top menu on macOS is displayed, but every menu item that relates to windows just makes the main window flash briefly then disappear.
The app seems to be running in the Dock.

Version is 0.30.1

**To Reproduce**
1. `git clone https://github.com/kovidgoyal/kitty.git` 
2. `cd kitty`
3. `./dev.sh build`
4. `kitty/launcher/kitty`

**Screenshots**
The kitty (black terminal linke) window flashes for an instant then disappears. Impossible to detect, but I can share a video link here [Video of glitch](https://youtube.com/shorts/dGlHeX_dSB4?feature=share)

**Environment details**
```
allow_remote_control socket
listen_on unix:/tmp/kitty.sock
```

**Additional context**
  `kitty --config NONE`  shows the same behaviour

**Comment by kovidgoyal** [comment]
Look at the stdout/stderr of the kitty process is there anything printed
there? And what does the window "disappearing" mean. Is it closed? Is it
offscreen? And run kitty with

kitty --config NONE

**Comment by ZontarOne** [comment]
If I launch kitty from a terminal windows in Mac, i don't get any message/error.
There 
If I launch with `kitty --config NONE` the behaviour is the same:

<img width="91" alt="Screenshot 2023-10-09 at 08 45 22" src="https://github.com/kovidgoyal/kitty/assets/85888163/f39b802c-1a17-43ef-bea2-d58f5b24aeb6">

- i can see a kitty icon in the Dock (it's a terminal window like icon, see above)
- i see a black terminal-like window appear for 1/10th of a second, then disappears (as if it was closed)
- i see absolutely NO kitty window on my computer screen.
-  I've tried closing every other window to see if maybe i was just hiding behind another window, nothing, it's nowhere
- if I click on the kitty icon, i can see the black termina-like window appear for an instant, then disappear without being able to have a prompt inside

if you watch the video posted a few messages ago, you will see clearly the behaviour.

PS. I use Kitty 0.30.0 (donwloaded as a release zip) without issues.

**Comment by kovidgoyal** [comment]
Run kitty --config=NONE cat

**Comment by ZontarOne** [comment]
hi. 
wow. the black window stays there! The title is `cat`.

<img width="1275" alt="image" src="https://github.com/kovidgoyal/kitty/assets/85888163/c60ce438-8754-4063-9291-e9ebaffc7294">
btw `kitty cat` works the same, the `cat` output stays there.

So maybe the issue is that kitty doesn't find a shell script to run? i.e. `bash` or `zsh`?

**Comment by kovidgoyal** [comment]
you likely have multiple kitty and kitten binaries in your path. Try
uninstalling the regular kitty first then the built from source one
should work fine.

**Comment by ZontarOne** [comment]
Tried, but I had no `kitty` in the path.
Anyway I uninstalled the packaged kitty and this is the result:

<img width="233" alt="image" src="https://github.com/kovidgoyal/kitty/assets/85888163/c552187f-11e9-43d8-96fc-c8a8ddbf07f2">

If I launch the compiled `kitty` with a shell command it works:

`./kitty zsh` I can have the window open and show the Zsh prompt fine. It's just that I think.

**Comment by kovidgoyal** [comment]
Does 
kitty kitten run-shell 
work?

**Comment by ZontarOne** [comment]
no, i have the same black windows flashing one second then disappearing.

**Comment by kovidgoyal** [comment]
yeah that shows the kitten binary is not working as I suspected. Which
means it is some PATH issue, try using the absolute path to the built
kitten binary instead and see if it works.

**Comment by ZontarOne** [comment]
Hi,
I've used the full absolute path from root:
<img width="528" alt="image" src="https://github.com/kovidgoyal/kitty/assets/85888163/45dbaaf9-7f9b-4eaa-bfc4-491abb915db9">

It doesn't work (window flashes and disappears).

At the moment the only solution is to explicitly set a shell to run after the kitty command.
Could it be that this installation of kitty does not know where to find the current user shell, because of some misconfiguration? either in kitty or on my computer?

**Comment by kovidgoyal** [comment]
No, it isnt even getting to the shell. On macOS, kitty runs 
login which in turn runs kitten which finally runs the shell. See
child.py

**Comment by kovidgoyal** [comment]
And you can see why kitten is failing with something like

kitty sh -c "kitten run-shell; read"

**Comment by kovidgoyal** [comment]
Use the absolute path to kitten then what happens

**Comment by ZontarOne** [comment]
Ok, the terminal window opened and it said that kitten needed to be downloaded. It downloaded it then stayed open on my zsh prompt.
I've kille kitty and relaunched with 
` ./kitty sh -c "/Users/walter/Lavori/progettiPersonali/kitty/shell-integration/ssh/kitten run-shell; read"` 

and now I have my zsh prompt just fine inside the kitty terminal window.
