### ISSUE TITLE
Last login msg on latest kitty terminal 

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#6689]
Hi Expert,

I am running the latest BAT tool on my macOS M2 chip. whenever I tried to open the horizontal pane, I got the below msg. login banner. I want to remove it. I have a ".hushlogin " file created even though Kitty print msg saying "Last login: Mon Oct  9 00:35:57 on ttys001" Please how me know how to remove this login banner

I am running the latest BAT version

<img width="645" alt="image" src="https://github.com/kovidgoyal/kitty/assets/11479557/6444b588-b039-40c5-94db-cffa48ab4d10">

**Comment by uncenter** [comment]
Coincidentally I made a related Reddit thread earlier (https://www.reddit.com/r/KittyTerminal/comments/172d6m1/new_kitty_window_cwd_issues/). When kitty creates a new pane/kitty window in a directory that isn't the home directory, login(1) doesn't find the `.hushlogin` file. My proposed solution is to create the new shell instance in the home directory and CD to it. I was told by a commenter that this was a shell issue; it is not. Other terminals (Wezterm) and terminal multiplexers do not have this issue.

**Comment by uncenter** [comment]
Thanks!

**Comment by ciscohack** [comment]
@kovidgoyal thanks for quick help. so you means shell with --login option if yes then I am not using this option even then I have this last login issue

**Comment by ciscohack** [comment]
i think i found the answer what you means you means I should run the kitty with like this shell --login -q

**Comment by kovidgoyal** [comment]
No you should need to update to next kitty build or use the nightly from tomorrow.

**Comment by ciscohack** [comment]
oh my bad thanks but do i need any config modification or upgrade to nightly will be enough to get rid of this login banner msg

**Comment by uncenter** [comment]
Works like a charm on `v0.31.0`! Thanks again!

**Comment by avnigo** [comment]
> Works like a charm on `v0.31.0`! Thanks again!

Is this actually fixed after 32b7be2? It doesn't seem to be working for me on `v0.31.0`, but I didn't get a chance to try 619d4e3 either.

**Comment by uncenter** [comment]
I'm just on the latest version AFAIK and it works fine:


https://github.com/kovidgoyal/kitty/assets/47499684/d43cb642-eb7e-4b42-9b95-943c1ccd6355

**Comment by avnigo** [comment]
@uncenter, thanks for confirming. Here is mine with `kitty --config=NONE`, strange: 

<img width="492" alt="image" src="https://github.com/kovidgoyal/kitty/assets/43263288/f01b05fe-d7f0-420b-9acf-e7385ff07511">

Unfortunately, I'm not sure how to troubleshoot this, but I'm happy to provide any info or be pointed in the right direction to look into this further. I wonder if this could just be something on my end, although it was working fine before the changes about a month ago.

**Comment by uncenter** [comment]
Just to verify - you have `~/.hushlogin` in the root?

**Comment by avnigo** [comment]
> Just to verify - you have a `~/.hushlogin`?

I didn't as I understood that the update was going to fix having to add that file, but I added it now and it worked, thanks a lot!

**Comment by uncenter** [comment]
I think this was just about the login message being displayed when a new kitty window was created not in the home directory since `login` wouldn't recognize `.hushlogin`.  Personally it wouldn't make sense for kitty to disable the login message by default since that's a user preference, so yeah you still need that file. Glad it's working though!

**Comment by gibfahn** [comment]
I have also started seeing the  `Last login: Sat Dec 23 15:59:20 on ttys006` message on latest kitty (on macOS). After looking through the changelogs and commits, my understanding is that [kitty 0.30.1](https://github.com/kovidgoyal/kitty/blob/master/docs/changelog.rst#0301-2023-10-05) started using `login` which started printing this message:

>macOS: When running the default shell, run it via the login program so that calls to getlogin() work ([:iss:`6511`](https://github.com/kovidgoyal/kitty/issues/6689#id121))

And then [kitty 0.31.0](https://github.com/kovidgoyal/kitty/blob/master/docs/changelog.rst#0310-2023-11-08) fixed `~/.hushlogin` being respected:

>macOS: When running the default shell with the login program fix [:file:`~/.hushlogin`](https://github.com/kovidgoyal/kitty/issues/6689#id62) not being respected when opening windows not in the home directory ([:iss:`6689`](https://github.com/kovidgoyal/kitty/issues/6689#id64))

So as I understand it the new expectation is that you should `touch ~/.hushlogin` if you don't want to see this message. This would be great to include in the kitty docs somewhere , or maybe in the changelog. My understanding from this thread was that the `~/.hushlogin` file was no longer needed.

**Comment by kovidgoyal** [comment]
This si nothing to do with kitty. macOS expects terminals to start login
shells and login shells show that message without hushlogin, you will
see the same behavior in any terminal on macOS.

**Comment by gibfahn** [comment]
>This si nothing to do with kitty.

In general sure, but specifically the feature of "we show a message without hushlogin" wasn't a thing on kitty until recently, so when I bisect "what changed recently" to work out which tool to look at, kitty is what comes up.

**Comment by paschun** [comment]
Excuse me if everyone knows this already, but there is a flag `login -q` that "acts as if a .hushlogin is present"
