### ISSUE TITLE
kitty icat --place 100x100

### ISSUE THREAD

**Issue by tammersaleh** [kovidgoyal/kitty#669]
It'd be nice to be able to scale images down to a certain size without displaying them at absolute coordinates.   For example, `--place` could take a subset of the `PLACE` string (just the size), and default to displaying the image at the current prompt location.  Either that, or we could break `--place` up into two flags: `--size` and `--position`.

**Comment by kovidgoyal** [comment]
Since icat is simply a thin wrapper around ImageMagick, you can do whatever image operations you want using convert before calling icat. So I dont particularly see the need for adding arbitraryimage operations to icat. Still I wont refuse a PR to add a `--size` option.
