### ISSUE TITLE
kitty swallows mouse click event when switching focus to kitty window

### ISSUE THREAD

**Issue by yanshay** [kovidgoyal/kitty#6694]
**Describe the bug**
At least on Mac, when switching from another window to Kitty window using a mouse click, the click event isn't passed to the application running inside kitty. In iTerm this does work, so it appears to be a bug in kitty.

**To Reproduce**
1. Run neovim inside kitty and create two neovim buffer windows (so split screen), make buffer window number 1 active
2. Switch to another application (not kitty)
3. Using the mouse click on neovim buffer window number 2 (not 1)
Bug: Neovim window 1 has the focus. Another click on the same buffer window will switch focus to buffer window number 2.
With iTerm buffer window 1 will receive focus immediately which is the desired behavior.
Same issue with Zellij. 

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

kitty 0.27.1 () created by Kovid Goyal
Darwin My-MacBook-Pro-2.local 20.6.0 Darwin Kernel Version 20.6.0: Thu Mar  9 20:39:26 PST 2023; root:xnu-7195.141.49.700.6~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.7.6 BuildVersion:	20G1231
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/user/.config/kitty/kitty.conf

Config options different from defaults:
editor              nvim
font_family         JetBrainsMono Nerd Font
font_size           16.0
macos_option_as_alt 3
modify_font:
    cell_height 1
open_url_with       ['/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox']
resize_in_steps     True
shell               /Users/user/bin/fish
tab_bar_edge        1
tab_bar_style       powerline
tab_powerline_style slanted
tab_title_template  ({index}) {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                yanivshaya


On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Why would it? The click was to transfer focus. Having it perform two
unrelated things is wrong. If you want to transfer focus and click at the same
time use a window manager that supports focus follows mouse.

**Comment by yanshay** [comment]
Why? Because a typical usage (maybe even the most common) of terminals is to host multiple windows - be it tmux, zellij, neovim, etc. So, put aside technical events which the user doesn't really care about, a terminal is a host for multiple windows. So when I press a window (inside a terminal or outside) I want it to be active so my next keypress would go to the proper location.

This is why at least iTerm and Alacritty works that way, this is why Wezterm has a setting to support this so not to swallow the mouse clicks (actually two such settings for different use cases), and from checking on forums seems like this is the standard behavior of terminals that I haven't checked.

But I get the opinionated attitude, so will switch to another Terminal, many to choose from.

Thanks for the response anyway!

**Comment by kovidgoyal** [comment]
Wow. Threatening maintainers is such classy behavior. Implement my feature or I will use a competing product indeed. If you had bothered to search you would see kitty already has this feature with focus_follows_mouse as I mentioned in my reply. https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.focus_follows_mouse On macOS where you cant actually configure focus_follows_mouse in the window manager, if you turn it on kitty implemnets it for you.
