### ISSUE TITLE
macOS Stage Manager icon doesn't respect kitty.app.icns file

### ISSUE THREAD

**Issue by flipphillips** [kovidgoyal/kitty#6696]
**Describe the bug**
I have an alternate icon in macOS, via the `kitty.app.icns` mechanism. The icon gets properly replaced in the Dock and other Desktop mechanisms. But, the icon in the Stage Manager 'label' does not get changed and remains the default icon. Note that this could certainly be a bug with the newer version of macOS stage manager, since I don't have any other apps that replace the icon using this strategy to test this against. 

**To Reproduce**
1. Deploy a replacement icon in `.configs/kitty/kitty.app.icns`
2. Enable macOS Stage Manager
3. Launch kitty
4. Activate a non-kitty app to force kitty's window into the 'side window strip' 
5. Observe window label icon

**Screenshots**
<img width="85" alt="Screenshot 2023-10-10 at 12 58 19 PM" src="https://github.com/kovidgoyal/kitty/assets/671183/b3cdfc9b-f064-4992-a933-66846621b5b4">

<img width="183" alt="Screenshot 2023-10-10 at 10 56 58 AM" src="https://github.com/kovidgoyal/kitty/assets/671183/c6d6bc37-29b8-4207-a3d6-66aec7e722fe">

**Environment details**
```
kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
Darwin gan-flip-m 23.1.0 Darwin Kernel Version 23.1.0: Tue Sep 26 22:11:21 PDT 2023; root:xnu-10002.40.89.501.1~3/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.1 BuildVersion:		23B5056e
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/flip/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select          clipboard
env:
{'LC_TERMINAL': 'kitty'}
font_family             Fira Code
font_features:
{'FiraCode-Regular': ('+zero', '+onum')}
font_size               13.0
Added shortcuts:
	f1 →  toggle_marker function marker.py
Colors:
	active_tab_background   #0d1117   
	active_tab_foreground   #c9d1d9   
	background              #0d1117   
	color0                  #484f58   
	color1                  #ec8e2c   
	color10                 #79c0ff   
	color11                 #e3b341   
	color12                 #79c0ff   
	color13                 #d2a8ff   
	color14                 #56d4dd   
	color2                  #58a6ff   
	color3                  #d29922   
	color4                  #58a6ff   
	color5                  #bc8cff   
	color6                  #39c5cf   
	color7                  #b1bac4   
	color8                  #6e7681   
	color9                  #fdac54   
	cursor                  #58a6ff   
	foreground              #c9d1d9   
	inactive_tab_background #010409   
	inactive_tab_foreground #8b949e   
	selection_background    #58a6ff   
	selection_foreground    #0d1117   
	tab_bar_background      #010409   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                flip

```

**Additional context**
Same behavior with no config file. I'm not 100% sure where macOS gets those 'badge' icons from, so perhaps the icon substitution mechanism doesn't so what one would expect by default.

**Comment by kovidgoyal** [comment]
Sorry I have no clue about this, not an Apple user. The technique was
largely invented by @page-down, maybe he can comment. But most likely
its just Apple breaking something. They do that a lot. Patches welcome
if someone can figure out how to workaround it. Relevant code is
cocoa_set_app_icon which just calls Apples NSWorkspace::setIcon
function.

You can always fallback to the manual method of changing the icon as
described in https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon
