### ISSUE TITLE
Nano and syntax highlighting

### ISSUE THREAD

**Issue by nicman23** [kovidgoyal/kitty#67]
Hello, first of all thanks for making such a great terminal

~~Nano with [syntax highlighting](https://wiki.archlinux.org/index.php/nano#Syntax_highlighting) does not display correctly and leads to incorrect drawing of the whole application (and then to writing to the wrong line / column)~~

~~after writing to a for example bash script and an `else` changes color, the effect described above occurs~~

edit: I was mistaken, it also affects nano without any user configuration, especially when copy pasting
workaround: run tmux

**Comment by kovidgoyal** [comment]
I cannot replicate this. nano works fine for me in kitty. I tried the following step:

1) Start nano
2) Type some text
3) Press Home
4) Press ^K (cut text)
5) Press ^U (Uncut text)

I could see no problems

**Comment by kovidgoyal** [comment]
I tried it with syntax highlighting as well -- still works. Contents of .nanorc

include "/usr/share/nano/*.nanorc"

**Comment by nicman23** [comment]
sorry i meant with ctrl shift c/v to copy/ paste

**Comment by kovidgoyal** [comment]
Works for me, replacing step 4 above with select text with mouse, press ctrl+shift+c and step 5 with move to new line and press ctrl+shift+v

**Comment by kovidgoyal** [comment]
No followup
