### ISSUE TITLE
Implement org.freedesktop.FileManager1

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kovidgoyal/kitty#6705]
So it will be possible that other programs will open kitty with specific location. For example 1password on Linux uses **org.freedesktop.FileManager1** to open a folder with a report file, and currently I have no file manager that implements this, and anyway - I would like to open this folder in terminal.

**Comment by kovidgoyal** [comment]
Does anything other than 1password use it? I'm not aware of any. Much
simpler solution is to configure 1password to just run a program to open
a directory. The standard on Linux is xdg-open and you can configure
xdg-open to run kitty if you want (as I do).

Also what happens if multiple programs try to register this interface,
like if I open dolphin which claims this interface and then kitty which
tries and cannot.

**Comment by vitaly-zdanevich** [comment]
Now `xdg-open /tmp/` open kitty with that folder, this is good, but not 1password :(

> Also what happens if multiple programs try to register this interface

It can be a build flag, on Gentoo we have simple interface to specify what options do we want, currently:

```
$ equery uses kitty
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for x11-terms/kitty-9999:
 U I
 + + X                               : Add support for X11
 - - python_single_target_python3_10 : Build for Python 3.10 only
 + + python_single_target_python3_11 : Build for Python 3.11 only
 - - python_single_target_python3_12 : Build for Python 3.12 only
 - - test                            : Enable dependencies and/or preparations necessary to run tests (usually controlled by FEATURES=test but can be toggled independently)
 - - wayland                         : Enable dev-libs/wayland backend
```

**Comment by vitaly-zdanevich** [comment]
> Much simpler solution is to configure 1password to just run a program to open a directory

How?

**Comment by kovidgoyal** [comment]
No idea, I dont use 1password. If it is not actually configurable like
that, then you can write a simple dbus service that exposes this
interface and calls xdg-open for you. I am not going to implement this
in kitty for integration with one program on one platform.
