### ISSUE TITLE
Remote theme gets reverted if kitten transfer, icat or edit-in-kitty is used

### ISSUE THREAD

**Issue by marcellmars** [kovidgoyal/kitty#6708]
**Remote theme gets reverted if kitten transfer, icat or edit-in-kitty is used**

I have `color_scheme some_theme`  in my `~/.config/kitty/ssh.conf` and that works fine. The theme gets applied the moment `kitten ssh` starts its job.

If I do `kitten edit-in-kitty some_file` or `kitten icat` it works as expected but it changes back the theme to the one used for local kitty sessions.

**To Reproduce**
1. add `color_scheme` to `~/.config/kitty/ssh.conf`
2. connect with `kitten ssh` to remote host
3. try `kitten icat some.png`
4. see the theme changed for the session to the remote host

**Comment by kovidgoyal** [comment]
edit-in-kitty works by editing files in a *local* window running your
editor locally on a downloaded copy of the file, as such it does not and
cannot know anything about whatever remote theme you have setup.

I cannot replicate your issue with icat, running

kitten icat image.png

does not change any colors for me.

**Comment by marcellmars** [comment]
> edit-in-kitty works by editing files in a _local_ window running your editor locally on a downloaded copy of the file, as such it does not and cannot know anything about whatever remote theme you have setup.
> 
> I cannot replicate your issue with icat, running
> 
> kitten icat image.png
> 
> does not change any colors for me.

I am sorry if I didn't explain it clearly enough.
I am connected at the remote host and I have it with different theme so I know it is not local session.

Then I use the `kitten` with remote files to edit them with my local editor. And that works. But once I am back in the remote session I found the colors/theme the same like local theme but before `kitten icat` it had the theme I set in ssh.conf.

Your explanation is exactly what I expected and what I understood.

But also, never mind. Your tone in comments just make me feel the software bugs are not the worst thing in life.

**Comment by kovidgoyal** [comment]
I am not following, can you provide an exact set of steps to reproduce
your issue?

**Comment by kovidgoyal** [comment]
Ah, never mind I think I understood, its an issue with palette restore not working.

**Comment by marcellmars** [comment]
1. add `color_scheme` to `~/.config/kitty/ssh.conf`
2. connect with `kitten ssh` to remote host. see the theme being applied.
3. try `kitten icat some.png` (make sure it was run in remote ssh session)
4. see the theme changed for the session to the remote host.

**Comment by marcellmars** [comment]
I tried `nigthly` first and then compiled it locally but unfortunately this commit didn't fix the behavior i reported.

1. connecting to the remote server does apply the new color set via `color_scheme`.

2. running `kitten icat ....` on the remote server does show the image "inline". that's the moment the theme goes back to default (as expected because the local shell shows the image)

3.  once the cursor is back ready to run things on the remote server the theme set via `color_scheme` is not reverted. it is the same default theme i have set for local shell.

**Comment by kovidgoyal** [comment]
you need to update the kitten binary on the server. you can do that
manually once the next nightly is built or after the next release on the
server run:

kitten update-self

**Comment by marcellmars** [comment]
it works!
thank you!
