### ISSUE TITLE
How does reverse linewrapping / backspace at the leftmost margin work?

### ISSUE THREAD

**Issue by michaelfortunato** [kovidgoyal/kitty#6709]
When line wrapping is enabled, the cursor is on the bottom line and at column 0, and the BS key is pressed, where exactly in the source code does kitty change the cursor position to be `cursor->y = cursor->y - 1`, `cursor->x = screen->ncols -1` (or something to that effect). I believe that `line-buf.c:linebuf_set_last_char_as_continuation` plays an important role in saying whether the line buff is wrapped. In other words, how does kitty handle backspaces on a wrapped line when the cursor is at column 0 so that the cursor returns to the above line at column (screenwidth - 1)?

I also looked in the method `parser.c:dispatch_normal_mode_char` and it looks like the backspace case is handled without considering line wrapping.

(PS: I am currently writing a shell where forward wrapping is working fine, but when my shell issues (BS SP BS), at column 0 on a wrapped line, the cursor is not returning to the above line.) Thanks.

**Comment by kovidgoyal** [comment]
See the screen_backspace() function in screen.c

**Comment by michaelfortunato** [comment]
Hmm yea I saw that, but it looks like screen_backspace calls screen_cursor_back which does not alter the y values (so doesn't handle the "reverse" wrap.)

**Comment by kovidgoyal** [comment]
Yes, it isnt supposed to. run cat and type backspace in any terminal you
will see it stops at the line start. If you are implementing a shell the
correct way to do it is to track the prompt contents and the cursor
position relative to the prompt. Then redraw the entire prompt at every
update. This is a bit less efficient but much more robust. Use the
atomic screen update escape code to make this completely flicker free.

You can see the readline package in the kitty source code for an example
of a shell implementation (you can run the shell by pressing
ctrl+shift+esc)
