### ISSUE TITLE
Rendering of Ubuntu Mono font / fontconfig not honored?

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#671]
I am trying to figure out how to improve rendering of Ubuntu Mono with the freetype font system:

This is how it looks with urxvt (font-size 7.6):

![2018-06-23-045331_931x53_escrotum](https://user-images.githubusercontent.com/9766/41805042-aee3fdfe-76a1-11e8-9cee-998bdf66c5b0.png)

This is how it looks with kitty (7.6pt) - which is quite similar and OK with regard to the issue below, but too small:
![2018-06-23-045409_940x50_escrotum](https://user-images.githubusercontent.com/9766/41805043-aefe489e-76a1-11e8-8109-2547efbe1ac3.png)

When increasing it to 7.7pt it shows that e.g. the "e" is not rendered the same:

![2018-06-23-045458_946x49_escrotum](https://user-images.githubusercontent.com/9766/41805044-af1cd03e-76a1-11e8-8f7d-f05db63280dc.png)

It looks nice in larger sizes (10pt):
![2018-06-23-045930_948x72_escrotum](https://user-images.githubusercontent.com/9766/41805068-3c090d00-76a2-11e8-8a58-12af13f3adb1.png)

I've read #352, and have tried adjusting the cell sizes, but it appears to be not due to limitation of the cell's size.

Any hints?
I've seen that there is code for hintstyle, with regard to the harfbuzz font only?  Commenting the call to `hb_ft_font_set_load_flags` did not make a difference.

I have the following fontconfig, but it appears to not get applied?!  (I am uncommenting the antialias=false to check)

```xml
  <match target="font">
    <test name="weight" compare="more"><const>medium</const></test>
    <edit name="autohint" mode="assign"><bool>false</bool></edit>
    <!-- Using hintnone or hintslight would cause misalignment with normal/bold lines.
         See https://github.com/jazzband/django-configurations/pull/174#discussion-diff-127201020R123 -->
    <!-- <edit name="hintstyle" mode="assign"><const>hintnone</const></edit> -->
    <edit name="hintstyle" mode="assign"><const>hintmedium</const></edit>
    <!-- <edit name="antialias" mode="assign"><bool>false</bool></edit> -->
  </match>

  <match target="font">
    <test qual="any" name="family" compare="eq">
      <string>Ubuntu Mono</string>
    </test>
    <edit name="hintstyle" mode="assign"><const>hintnone</const></edit>
    <!-- <edit name="lcdfilter" mode="assign"><const>lcdlight</const></edit> -->
    <!-- <edit name="autohint" mode="assign"><bool>true</bool></edit> -->
    <!-- <edit name="antialias" mode="assign"><bool>false</bool></edit> -->
  </match>
```

**Comment by kovidgoyal** [comment]
rendered character size is not determined by pt size alone, but by the combination of pt size and DPI. kitty, like most modern software on linux uses Xft.dpi to determine the DPI to use. I have no idea what urxvt does, but it is presumably something different.

The other difference between kitty and older software is that kitty does not do sub-pixel anti-aliasisng for performance reasons, since it is unnecessary on modern high resolution monitors. As a result if you have low resolution monitors, text in kitty at smaller sizes will look lighter/thinner (#214)

I dont see what the problem with e at 7.7pt is, looks the same as the other characters.

**Comment by blueyed** [comment]
> kitty does not do sub-pixel anti-aliasisng

That might explain it then.

> Xft.dpi to determine the DPI to use

Via `_glfwGetSystemContentScaleX11`?  where is this used then?
I have `Xft.dpi = 175`.
I thin urxvt does not fetch/use it explicitly, but via fontconfig/freetype then..

> I dont see what the problem with e at 7.7pt is, looks the same as the other characters.

Compare the "e"s, they are much bolder on top/bottom - but that is likely the the sub-pixel anti-aliasing then.

**Comment by kovidgoyal** [comment]
grep for logical_dpi

**Comment by kovidgoyal** [comment]
And fontconfig do not use Xft.dpi, they require the DPI to be supplied to them via the application.

**Comment by blueyed** [comment]
urxvt seems to use `XftDrawRect`/`XftDrawGlyphSpec` (and libxft appears to handle dpi then).
