### ISSUE TITLE
Printing over 2nd cell in wide character should delete wide character 

### ISSUE THREAD

**Issue by mitchellh** [kovidgoyal/kitty#6714]
**Describe the bug**
Printing over the 2nd cell in a wide character is ignored.

**To Reproduce**
```
#!/usr/bin/env bash
printf "橋"
printf "\033[D"
printf "X"
read
```

Notice the terminal state is still just "橋". The "X" is seemingly ignored. The terminal state should be ` X` (note space prefix) if you agree with the following terminals. The character in question ("橋") doesn't matter, any wide character (`wcwidth == 2`) character will exhibit the problem.

**Additional context**
The following terminals result in ` X` (note the space prefix): xterm, urxvt, iTerm, libvte-based terminals.

It appears xterm preserves the current SGR state so if you do the following, the 1st cell also becomes red:

```
#!/usr/bin/env bash
printf "\033[4m"
printf "橋"
printf "\033[D"
printf "\033[41m"
printf "X"
read
```

**Comment by kovidgoyal** [comment]
I dont have strong feelings about this, one way or another.
Traditionally it has been up to client applications to handle cursor
movement and related delete/update semantics around wide chars, so this
kind of thing has been undefined on the terminal side. Beyond surveying
other terminal emulators do you have some docs/spec to define this
behavior? Some questions:

1) Which characters exactly cause this? What happens if its a
diacritic for instance? Or another wide character? Or a narrow character
followed by a VS2016 combining char that makes it a wide character?

2) Does the background/underline/etc. state of the space cell change to the
current cursor state? Or does it remain what it was when the wide
character was input?

kitty's current approach of ignoring the character avoids all these
questions. If you want me to change it, I will need them answered.

**Comment by mitchellh** [comment]
I also don’t have strong feelings about this, wasn’t sure if this was something you’d care about. I know the answers to your questions but if you’re not interested then I’m perfectly fine closing this, just wanted to make you aware of this differing behavior between various terminals.

**Comment by kovidgoyal** [comment]
I didnt say I am not interested, just that I dont much care which way
kitty jumps on this. I actually think getting all terminals
to behave the same for such things is a worthy goal. So if you can
answer my questions, please do so.

**Comment by mitchellh** [comment]
Sure. Sharing what I know or have figured out below.

> Which characters exactly cause this? What happens if its a
> diacritic for instance? Or another wide character? Or a narrow character
> followed by a VS2016 combining char that makes it a wide character?

The terminals that behave this way seem to primarily be the older ones that are processing characters on a codepoint-by-codepoint basis and using `wcwidth`. Therefore, it affects any character that has a `wcwidth == 2`. It doesn't appear combining characters have any effect since they're just treating as zero width without any grapheme clustering.

The exceptions to this are iTerm and WezTerm, but I'm not sure any consistency can be gleaned from that sample set because iTerm's grapheme clustering seems inconsistent (I haven't figured it out, I haven't read the source) and WezTerm _always_ performs grapheme clustering so with combining chars and so on, it'll move the cursor forward 2 cells for any wide _grapheme_ (does not use `wcwidth`). 

I haven't tested VS2016 combining chars either, but xterm doesn't handle them specially in the source as far as I can tell so I expect it'll behave in the simplest possible way: ignored, treated as zero width, dropped.

> Does the background/underline/etc. state of the space cell change to the
> current cursor state? Or does it remain what it was when the wide
> character was input?

This is easier, it appears to inherit only the background color. This is consistent with xterms general behavior around "clearing" cells that applies to all such sequences (ICH, IL, DL, SD, SU, etc.).

**Comment by kovidgoyal** [comment]
On Fri, Oct 13, 2023 at 07:53:34PM -0700, Mitchell Hashimoto wrote:
> Sure. Sharing what I know or have figured out below.
> 
> > Which characters exactly cause this? What happens if its a
> > diacritic for instance? Or another wide character? Or a narrow character
> > followed by a VS2016 combining char that makes it a wide character?
> 
> The terminals that behave this way seem to primarily be the older ones that are processing characters on a codepoint-by-codepoint basis and using `wcwidth`. Therefore, it affects any character that has a `wcwidth == 2`. It doesn't appear combining characters have any effect since they're just treating as zero width without any grapheme clustering.
> 
> The exceptions to this are iTerm and WezTerm, but I'm not sure any consistency can be gleaned from that sample set because iTerm's grapheme clustering seems inconsistent (I haven't figured it out, I haven't read the source) and WezTerm _always_ performs grapheme clustering so with combining chars and so on, it'll move the cursor forward 2 cells for any wide _grapheme_ (does not use `wcwidth`). 
> 
> I haven't tested VS2016 combining chars either, but xterm doesn't handle them specially in the source as far as I can tell so I expect it'll behave in the simplest possible way: ignored, treated as zero width, dropped.

So to clarify, is the following correct for what is expected to happen
when a char is output on cell 2 of and existing wide char:

1) Output a width one char: space + char replaces existing wide char
2) Output a width zero or -1 char: it is added to the first cell of the
existing wide char
3) Output a width 2 char: It replaces the existing wide char

> 
> > Does the background/underline/etc. state of the space cell change to the
> > current cursor state? Or does it remain what it was when the wide
> > character was input?
> 
> This is easier, it appears to inherit only the background color. This is consistent with xterms general behavior around "clearing" cells that applies to all such sequences (ICH, IL, DL, SD, SU, etc.).

So if I have an underlined wide char with red background and I output
a narrow char with green background:

1) On the first cell of the wide char: I get a single green bg narrow
char?
2) On the second cell of the wide char: I get a a red space and a green
bg narrow char?
3) If I have an underlined wide char and output a narrow char with no
underline or different underline style/color I get a space with the new
underline and a narrow char with the new uderline?
4) If I have a wide char with no underline and I output a narrow char
with an underline, I get a space and narrow char with the underline?

**Comment by arthsmn** [comment]
Might be worth mentioning: https://github.com/contour-terminal/terminal-unicode-core

**Comment by kovidgoyal** [comment]
This issue is fixed in vt branch which will eventually be merged into master. I settled on treating a write to the second cell as though the cursor is moved back to the first cell, a space is written, then the original write proceeds. This seemed like the most sensible and easily understood semantics. It means you can always now how long the string you have written to is. And the rules for what formatting applies to the space are simple.
