### ISSUE TITLE
background_image path/to/image doesn't work

### ISSUE THREAD

**Issue by Delice0** [kovidgoyal/kitty#6720]
**Describe the bug**
I'm trying to set a background image to my terminal given the path to home/downloads/image.png, but nothing happens

**To Reproduce**
1. background_image ~/Downloads/bg2.png
2. quit and reopen terminal
3. nothing happens!!

**Comment by kovidgoyal** [comment]
Works for me with those steps. If you want more help you need to provide
all the information asked for in the issue template.

**Comment by Delice0** [comment]
Try this these configs or whatever is relevant. These are _all_ the options I have modified.

```
font_size 13
modify_font cell_height 140%
hide_window_decorations titlebar-only
tab_bar_edge top
tab_bar_style powerline
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
background_opacity 0.6
background_blur 50
background_image ~/Downloads/bg2.png
editor /opt/homebrew/bin/nvim
```

**Comment by Delice0** [comment]
Updated with: https://github.com/kovidgoyal/kitty/issues/6722
