### ISSUE TITLE
Text colour is not inverted unless using the 'block' cursor

### ISSUE THREAD

**Issue by pallaswept** [kovidgoyal/kitty#6723]
**Describe the bug**
In my kitty.conf, I have:

```
cursor none
cursor_text_color background 
cursor_shape block
cursor_beam_thickness 3
cursor_blink_interval 0
```

Note that `cursor_text_color background`  should do nothing because the above is set to `cursor none`. If I comment it out, there is no change to any of the following. It's just there for completeness, I guess.... but it's superfluous.

I first noticed this when using kitty_grab kitten, and[ I logged the issue there](https://github.com/yurikhan/kitty_grab/issues/29)
The result when I use kitty_grab is as you'd expect - the cursor 'inverts' the background and foreground colours. Here's a shot (look at the 'y' in the middle:

![image](https://github.com/yurikhan/kitty_grab/assets/132128962/87f12d66-c900-4315-a86b-aea561a97cb1)

So that's nice, and working as expected. But I'd kinda like to be using the `beam` cursor. When I use beam, it uses the text foreground colour as the foreground of the beam, but doesn't use the text background colour as the text foreground colour, so instead of 'blue on black' becoming 'black on blue' as per the above shot, I get 'blue on blue' which means the text is invisible. screenshot:

![image](https://github.com/yurikhan/kitty_grab/assets/132128962/948f48f4-aa9c-4a74-a353-42ebf641a1eb)

I chose the lowercase letter y on purpose, so that you can see that the 'underline' cursor has the same issue:

![image](https://github.com/yurikhan/kitty_grab/assets/132128962/648d325e-f205-4e63-8891-a0b4ce2f04e5)

I started to wonder why this feature exists outside of kitty_grab, because I couldn't think of any other way to move the cursor around the screen, but then I realised that there's always moving the cursor at the command line. This is the result:

Block: 
![image](https://github.com/yurikhan/kitty_grab/assets/132128962/eb58ecc4-4eb8-43ab-8dc0-b3fa03e61d72)
Beam:
![image](https://github.com/yurikhan/kitty_grab/assets/132128962/b86efbd0-7d2f-470d-8219-4b6a391a292e)
Underline:
![image](https://github.com/yurikhan/kitty_grab/assets/132128962/c79a1592-a8e6-40b8-b27b-5079c252715e)

As you can see, the 'block' cursor inverts as expected, but 'beam' and 'underline' don't invert the text colour and the text is hidden behind the cursor.

I'll just keep using `block` for now, but it would be super cool if you know how to fix this up, so that I can switch to `beam` :)

Thanks in advance for any help!

**To Reproduce**
1. set cursor none (to invert cursor fg/bg colours)
2. set cursor to block
3. be happy
4. set cursor to beam or underline
5. be sad. awww sad kitty.

**Environment details**
```
kitty 0.30.1 created by Kovid Goyal
Linux Pallas 6.5.6-1-default #1 SMP PREEMPT_DYNAMIC Fri Oct  6 11:20:48 UTC 2023 (c97c2df) x86_64
Welcome to openSUSE Tumbleweed 20231013 - Kernel 6.5.6-1-default (/dev/tty).

br0: 4{br0} 6{br0}
enp6s0: 4{enp6s0} 6{enp6s0}
wlp5s0: 4{wlp5s0} 6{wlp5s0}


Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/pallaswept/.config/kitty/kitty.conf

Config options different from defaults:
cursor            None
cursor_shape      3
shell_integration frozenset({'no-cursor'})

Important environment variables seen by the kitty process:
	PATH                                /home/pallaswept/.cargo/bin:/home/pallaswept/.local/bin:/home/pallaswept/bin:/usr/local/bin:/usr/bin:/bin
	LANG                                en_GB.UTF-8
	VISUAL                              micro
	EDITOR                              micro
	SHELL                               /bin/bash
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                pallaswept
	XCURSOR_SIZE                        16
	LC_MEASUREMENT                      C
	LC_MONETARY                         en_AU.UTF-8
	LC_NUMERIC                          en_AU.UTF-8
	LC_TIME                             C
	XDG_CONFIG_DIRS                     /home/pallaswept/.config/kdedefaults:/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg
	XDG_CONFIG_HOME                     /home/pallaswept/.config
	XDG_CURRENT_DESKTOP                 KDE
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      10
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session4
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1

```

**Additional context**
> Post a minimal kitty.conf that reproduces the problem.

The following is the minimal kitty.conf to reproduce:
```
shell_integration no-cursor
          #otherwise bash makes it a thin beam
cursor none
         # to invert colours
cursor_shape beam
         #or
cursor_shape underline
         #cursor_shape block works great!
cursor_blink_interval 0
         #not critical, but it's easier to see if you have this
```

**Comment by kovidgoyal** [comment]
That's by design. Beam and underline are thin, having them inverted does not work well. You have configured them to be unusually thick which is why you prefer them to behave like blocks.

**Comment by pallaswept** [comment]
> That's by design. Beam and underline are thin, having them inverted does not work well. You have configured them to be unusually thick which is why you prefer them to behave like blocks.

Yeh I want a kind of half-block. But if this is the intended design then I guess I have to decide to have a thin beam or a full-fat block. I will take the block. Thanks for the quick answer!

**Comment by pallaswept** [comment]
> having them inverted does not work well

By the way, the reason I like it this strange "half block" way is because some old terminals back in the 80's when we only had two colours, used to work that way. So it can work well, which is why i wanted that effect. It doesn't here, but it can :) Maybe one day when you are bored you might like to try and get it to work in kitty. But I imagine you are very busy with such a popular terminal, so don't worry about it :)

**Comment by kovidgoyal** [comment]
Yeah not something I will ever realistically have time for, but if you
are really keen, patches welcome, you can have the setting apply to beam
cursors as well when their thickness is greater than a threshold
fraction of the cell.
