### ISSUE TITLE
Print key prints "361u" which is a problem in vim

### ISSUE THREAD

**Issue by zapp42** [kovidgoyal/kitty#6728]
**Describe the bug**
When I press the "Print" key on my keyboard, I get the following string in kitty: 361u

Xterm as well as konsole do not show this behaviour, both show no input on pressing the print key.

In vim this is a problem, as it undos the last 361 edits.

On my Thinkpad T14 the print key is annoyingly placed between right ctrl + AltGr, so I hit it by accident quite often.

**To Reproduce**
1. Open Kitty
2. Press Print key
3. See error

**Environment details**
```
kitty 0.30.0 created by Kovid Goyal
Linux fedora.fritz.box 6.5.5-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 23 22:53:02 UTC 2023 x86_64
S
Kernel 6.5.5-300.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/rof/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
enable_audio_bell    False
font_family          Source Code Pro
url_style            1
Colors:
        background           #e4e5f5   
        color1               #ff16b0   
        color10              #00af4f   
        color11              #ff8d01   
        color12              #0098fd   
```

**Comment by kovidgoyal** [comment]
If you are running up-to-date vim you will be fine since it implements
the kitty keyboar dprotocol. Or just map the print key to discard in
kitty.conf
