### ISSUE TITLE
Blurry rendering of TerminusTTF at certain sizes

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#673]
Using Terminus at certain sizes is rendered in a weird (very blurred) way:

```
font_family      Terminus (TTF)
font_size 7.6
```

![2018-06-23-062124_931x131_escrotum](https://user-images.githubusercontent.com/9766/41805596-beaca590-76ad-11e8-9f48-5728300d60a9.png)

It is fine at 7.7 and 7.2, but also blurry for 7.3 - 7.5.
My DPI is 175.

(I am looking at other fonts now, given #671 - and I think I like Hack the most currently, so this is not really an issue for me, but found it puzzling)

**Comment by kovidgoyal** [comment]
That will happen for bitmap fonts. I have never really looked into fixing bitmap font glyph rendering in kitty since kitty supports free font sizing and bitmap fonts do not, patches to improve it are welcome.
