### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [kovidgoyal/kitty#6732]
**Is your feature request related to a problem? Please describe.**
I've encountered a recurring issue when using the application – the lack of a built-in dark mode. Using the application in a bright environment or during nighttime can be straining on the eyes, and the absence of a dark mode makes it less user-friendly in low-light conditions.

**Describe the solution you'd like**
I would like to request the addition of a dark mode feature in the application. This dark mode should provide a user-friendly and visually comfortable interface with darker backgrounds and softer colors, making it easier on the eyes, especially in low-light settings. Users should be able to switch between light and dark modes in the application settings.

**Describe alternatives you've considered**
One alternative solution would be to rely on third-party tools or screen dimming software to adjust the display settings, but having a built-in dark mode within the application would offer a more seamless and integrated user experience.

**Additional context**
The addition of a dark mode would greatly improve the accessibility and user experience of our application. Many users, including those who work during nighttime hours or in dimly lit environments, would benefit from this feature. It's a common and expected feature in modern applications, and its implementation can enhance the application's appeal and usability.

**Comment by kovidgoyal** [comment]
I have no idea what this means. kitty has no UI of its own and its
colors are completely themeable to whatever you like including dark
ones.
https://sw.kovidgoyal.net/kitty/kittens/themes/

**Comment by bphd** [comment]
> I have no idea what this means. kitty has no UI of its own and its colors are completely themeable to whatever you like including dark ones. https://sw.kovidgoyal.net/kitty/kittens/themes/

Please re-open, it's not about having a UI or having colors, it's about split terminal view in two-page layout. Like it would be great for tiny screen to see the output on two-page layout, like two pages side by side, to we can see more on one screen. Because otherwise the screen have to be in portrait to display all its length

**Comment by kovidgoyal** [comment]
I dont know what this has to do with terminals, you need to implement
this feature ina  pager of which there are already some that do thi.s

**Comment by bphd** [comment]
> I dont know what this has to do with terminals, you need to implement this feature ina pager of which there are already some that do thi.s

Do you know any?
