### ISSUE TITLE
Strip whitespace from wrapped urls when hinting

### ISSUE THREAD

**Issue by agenbite** [kovidgoyal/kitty#6736]
**Describe the bug**
When using hints to visit URLs with the keyboard, if the URLs are cut on the screen by using whitespace (as if you're using word wrapping in your editor), while the URLs are properly highlighted, they are acted upon with the trailing whitespaces included in the middle, or rather, they're cut and only the first part is acted upon. Maybe kitty should know better and remove whitespace from those URLs?

**To Reproduce**
Steps to reproduce the behavior (I'm using vim but I suspect any other editor with softwrapping would do):
1. Open kitty in a not so wide window
2. `echo 'https://very.long.url/which/spans/a/lot/of/columns/and/is/wider/than/your/terminal/window/but/you/still/would/like/to/visit' | vim`
3. Enable soft wrapping: `:set linebreak`
4. Launch hints (Control+Shift+e)
5. Select the url to see that it is opened in the browser only up to the first whitespace.

**Environment details**
kitty 0.26.5 created by Kovid Goyal
Linux bisio 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023 x86_64
Ubuntu 23.04 bisio /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/me/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    yes
bold_font               Iosevka Comfy Motion Bold
bold_italic_font        Iosevka Comfy Motion Bold Italic
cursor_blink_interval   0.0
disable_ligatures       1
enable_audio_bell       False
font_family             Iosevka Comfy Motion
font_features:
{'Iosevka-Comfy-Motion': ('-calt', '+JSPT'),
 'Iosevka-Comfy-Motion-Bold': ('-calt', '+JSPT'),
 'Iosevka-Comfy-Motion-Bold-Italic': ('-calt', '+JSPT'),
 'Iosevka-Comfy-Motion-Italic': ('-calt', '+JSPT')}
font_size               13.0
italic_font             Iosevka Comfy Motion Italic
modify_font:
    cell_height 110%
scrollback_lines        5000
shell_integration       frozenset({'no-cursor'})
update_check_interval   0.0
Changed shortcuts:
	kitty_mod++ →  change_font_size all +0.5
	kitty_mod+- →  change_font_size all -0.5
	kitty_mod+u →  kitten hints --hints-offset=0 --alphabet=jfkdhgls --ascending --hints-background-color=yellow
Colors:
	active_tab_background   #9c6992   
	active_tab_foreground   #f0e4cf   
	background              #404040   
	color0                  #404040   
	color1                  #e3716e   
	color10                 #8bae68   
	color11                 #d68c67   
	color12                 #61abda   
	color13                 #cf86c1   
	color14                 #65b8c1   
	color15                 #c0ab86   
	color2                  #819b69   
	color3                  #b77e64   
	color4                  #6099c0   
	color5                  #b279a7   
	color6                  #66a5ad   
	color7                  #f0e4cf   
	color8                  #625a5b   
	color9                  #ec8685   
	cursor                  #f3eadb   
	cursor_text_color       #404040   
	foreground              #f0e4cf   
	inactive_tab_background #555555   
	inactive_tab_foreground #f0e4cf   
	selection_background    #746956   
	selection_foreground    #f0e4cf   

Important environment variables seen by the kitty process:
	PATH                                /home/me/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/me/.local/bin:/home/me/.go/bin
	LANG                                en_GB.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                me
	LC_TIME                             es_ES.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	LC_MONETARY                         es_ES.UTF-8
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      c3
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_ADDRESS                          es_ES.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 i3
	LC_TELEPHONE                        es_ES.UTF-8
	XDG_SESSION_DESKTOP                 i3
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/me
	LC_NAME                             es_ES.UTF-8
	LC_MEASUREMENT                      es_ES.UTF-8
	LC_IDENTIFICATION                   es_ES.UTF-8
	XDG_VTNR                            7
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-i3:/etc/xdg
	XDG_DATA_DIRS                       /usr/share/i3:/usr/local/share:/usr/share:/var/lib/snapd/desktop
	LC_NUMERIC                          es_ES.UTF-8
	LC_PAPER                            es_ES.UTF-8

**Comment by kovidgoyal** [comment]
You are using a very old version of kitty, IIRC this has already been
addressed:
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.url_excluded_characters

**Comment by agenbite** [comment]
Thanks, @kovidgoyal! I've updated to 0.30.1 and I can't see the improvement. Two questions: 

1. since that `url_excluded_characters` is filed under the mouse configuration, is the same logic applying to keyboard hints? And 
2. Do I have to change the default value of `url_excluded_characters` to make it work? Afaics, I shouldn't, but I'm not quite sure.

What I'm seeing is that using the mouse the url's highlighting is cut off upon carriage returns, while with hints the url is fully highlighted but it is then sent to the browser with spaces in it.

**Comment by kovidgoyal** [comment]
It works for me in mutt (indeed I use it everyday). Dunno about vim, in general, I dont think this is going to work for something like vim, because it has potentially a left gutter, or vim splits. The terminal has no notion of these so it cannot select across them. You should instead use a vim plugin for these.

**Comment by kovidgoyal** [comment]
And to be complete when I said works for me I meant both by clicking and with ctrl+shift+e in mutt. This is with all default kitty options.

**Comment by agenbite** [comment]
Understood. Thanks! And thanks for kitty!! :)

**Comment by agenbite** [comment]
Hi again. Have you tried this in mutt inside tmux with a vertical split? In my case, I get `| ` inside my urls if they're wrapped. This happens also with less, so it's not vim-related. May I insist with the two questions I posed before?

**Comment by kovidgoyal** [comment]
if its inside tmux there is no way it can work. The terminal cannot know
anything about what windows tmux has setup. You need to use a tmux
plugin for it.

And as for less, this works fine for me:

kitty sh -c "echo https://some-very-long-url-indeed-that-will-be-wrapped-by-less-works-fine.com | less"
