### ISSUE TITLE
Using `new_tab_with_cwd` while command is running uses command's cwd

### ISSUE THREAD

**Issue by mfontanini** [kovidgoyal/kitty#6737]
**Describe the bug**
If you open a tab using `new_tab_with_cwd` while a command is running, and that command has changed the `cwd`, the new tab seems to somehow open on that new `cwd` rather than what your shell's `cwd` originally had.

**To Reproduce**

1. Create a file somewhere, let's say the path is `/tmp/cd.sh`, with the following contents:

```bash
#!/bin/bash

cd /tmp
sleep 60
```
2. `chmod +x` the file.
3. cd anywhere that's not `/tmp`, let's say `/home`.
4. Run `/tmp/cd.sh` and while it's running, open a new tab using `new_tab_with_cwd`.
5. You will now notice that the new tab is open in `/tmp`. However, at no point _my shell_ was in `/tmp`. It seems like when the process that was spawned to run `cd.sh` changes the `cwd` it somehow gets propagated to the parent process.

Note that while I haven't use that many terminal emulators, at least `mate-terminal` which is the default in my distro does not have this behavior and instead will open a new tab in `/home`. I do think this is how it should be and the current behavior in kitty is unexpected. e.g. from the shell in my first tab's point of view, I never was in `/tmp` so how come the new tab opens there?

This is especially noticeable when I'm running something like `cargo build` and opening a tab takes me to some random `~/.cargo/very/long/path/name` and I have to get back to where I was by hand.

**Environment details**
I'm running on linux mint 21.2 and kitty `0.30.0`

**Additional context**
I can't reproduce this with an empty config because the default shortcut to open a new tab uses `new_tab` rather than `new_tab_with_cwd`.

**Comment by kovidgoyal** [comment]
That is by design. If you dont like it, use one of the options described
in https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-cwd
