### ISSUE TITLE
terminfo alias for sudo breaks user's shell config

### ISSUE THREAD

**Issue by ryanm0** [kovidgoyal/kitty#6740]
The alias for sudo introduced in commit d96fdb8 seems to override the alias for sudo that I defined in my bashrc.

**To Reproduce**

1. Add the line `alias sudo='sudo '` to `~/.bashrc` (for context: this allows other aliases to be expanded when using sudo; for example if I have an `alias v=vim` in my bashrc, I can now run `sudo v /path/to/file` to edit a file with vim).
2. Open a kitty window (assuming bash is default shell) and run `alias sudo`: output is `alias sudo='sudo TERMINFO="/usr/lib/kitty/terminfo"'` rather than the expected `alias sudo='sudo '`, showing that the alias has been overridden.

**Environment details**

Using kitty 0.30.1 on Void Linux

**Additional context**

I don't see why setting the TERMINFO environment variable is necessary in the first place, shouldn't the terminfo file for kitty already be installed to /usr/share/terminfo?

**Comment by kovidgoyal** [comment]
No, terminfo files are often not installed. If that alias bothers you,
you can always disable it via the shell_integration setting in
kitty.conf.

**Comment by IceAsteroid** [comment]
Just to further explain for specific options to be disabled, in this case, it's no-sudo, the format should look like this:

```shell_integration no-sudo```

To disable shell integration completely:
```shell_integration disabled```
