### ISSUE TITLE
[glfw error 65544] Wayland fatal display error : protocol error

### ISSUE THREAD

**Issue by alopezj97** [kovidgoyal/kitty#6741]
**Describe the bug**
Using kitty in Hyprland doesn't work. There are three scenarios:
1. When trying to run kitty using `SUPER+q` (default keybinding), it doesn't open.
2. When trying to run kitty from the rofi menu (`SUPER+r` + select kitty), it doesn't open and the system kind of gets unresponsive for a few seconds.
3. When trying to run it from another terminal, in my case `foot`, it shows the following error (see screenshot attached).

**To Reproduce**
1. Install arch using archinstall and select Hyprland desktop profile
2. Once installed, run kitty from Hyprland.

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/22918075/ee79dccd-55ba-4c6d-b90c-7dd778579189)

**Environment details**
Looking for solutions online I tried to set the following kitty conf but didn't work
```
hide_window_decorations yes
linux_display_server wayland
```
The same issue can be faced when running `kitty --config NONE`.

**Additional context**
I'm running my installation of Arch Linux in a VM using VMware Workstation. Before jumping to reply that the issue is based on the fact that I'm using a VM, please read:
- I did set `Accelerate 3D graphics` to true (in fact first in another installation I set it to false to verify that the error message was not the same).
- It is not related to the virtualization software. If I use KDE instead of Hyprland for example, kitty works fine, so either it is a configuration issue or a dependency issue.

**Comment by kovidgoyal** [comment]
kitty works fine in Hyprland, indeed it is the default terminal for
Hyprland. What the issue is in your VM, I have no idea, but it is almost
certainly something specific to the VM or the GPU drivers + VM drivers
combination. I'm afraid I dont have the time/interest to debug this
particular combination. Use a non GPU based terminal like foot or use
software rendering in kitty.
