### ISSUE TITLE
Terminal broken after switching users on macOS

### ISSUE THREAD

**Issue by dehesselle** [kovidgoyal/kitty#6742]
**Describe the bug**
After switching users (`su - some_user`), kitty misbehaves. Keyboard input is misinterpreted (backspace seems to insert space), accessing the history (with `cursor up` key) garbles the output into the same line, the terminal is basically unusable in this state.

**To Reproduce**
1. switch users with `su - some_user`
2. use `cursor up` to go through the history
3. type something and use backspace

**Screenshots**
![behavior_after_su](https://github.com/kovidgoyal/kitty/assets/11375494/b5b7d6e2-c9d3-40d4-b73b-cb1eb475384f)

**Environment details**
```
kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
Darwin Auriga.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		13.6 BuildVersion:		22G120
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/rene/.local/etc/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.9
font_family                Hurmit Nerd Font
font_size                  13.0
macos_show_window_title_in window
scrollback_lines           8000
shell_integration          frozenset({'disabled'})
tab_bar_style              powerline
tab_title_max_length       20
Changed shortcuts:
	cmd+0 →  goto_tab 10
	cmd+1 →  goto_tab 1
	cmd+2 →  goto_tab 2
	cmd+3 →  goto_tab 3
	cmd+4 →  goto_tab 4
	cmd+5 →  goto_tab 5
	cmd+6 →  goto_tab 6
	cmd+7 →  goto_tab 7
	cmd+8 →  goto_tab 8
	cmd+9 →  goto_tab 9

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                de_DE.UTF-8
	SHELL                               /bin/zsh
	USER                                rene
	XDG_RUNTIME_DIR                     /Users/rene/.local/tmp/run
	XDG_DATA_HOME                       /Users/rene/.local/share
	XDG_CONFIG_HOME                     /Users/rene/.local/etc
	XDG_CACHE_HOME                      /Users/rene/.local/tmp/cache
```

**Additional context**
The problem is also reproducible when using `kitty --config NONE`.

**Comment by dehesselle** [comment]
Hm I should have also searched the closed issues _before_ creating this one. I think I created a duplicate for https://github.com/kovidgoyal/kitty/issues/6528

**Comment by dehesselle** [comment]
Yep, having a valid `$TERMINFO` fixes this issue.

**Comment by dehesselle** [comment]
@kovidgoyal I'd be interested to know the reasoning behind this behavior. From my point of view, kitty is the only terminal I have ever used that suggests I either copy over terminfo files to every host I want to connect to or need to use some special configuration. Seeing that `TERMINFO` is by default `/Applications/kitty.app/Contents/Resources/kitty/terminfo` and the kitty process never loses access to that, why can't you silently fallback to that if there is no explicit setting?
I've read through quite a few other conversations here (e.g. about tmux) so I know you have strong opinions, which leads me to believe that this will be the case here as well.

**Comment by kovidgoyal** [comment]
It isnt kitty misbehaving, it's programs running in it. It is not kitty
that needs or uses TERMINFO it is some programs running in it. And this issue
has been discussed to death a million times by now, google is your
friend.
