### ISSUE TITLE
Laggy rendering for fast moving objects with JetBrains Mono

### ISSUE THREAD

**Issue by milan-panta** [kovidgoyal/kitty#6743]
**Describe the bug**
Kitty was being choppy when scrolling quickly through files so I ran cmatrix to see if there were visual rendering issues. It was choppy with lots of stutters but it went back to normal after switching to the no ligatures version of the same font.

**To Reproduce**
1. Open kitty with a font with ligatures (like JetBrains Mono).
2. Scroll quickly through large files or run a program that renders the screen a lot of times like cmake, or asciiquarium.
4. Observe.

**Screenshots**

https://github.com/kovidgoyal/kitty/assets/106028082/1988b10a-5c1b-4086-a0da-9e074f501b3a

The video shows cmatrix running on kitty with Jetbrains Mono, on kitty with Jetbrains Mono NL, and on alacritty with Jetbrains Mono. The choppy one is kitty using Jetbrains Mono. The stuttering issue is not exclusive to cmatrix, it was simply the clearest way of showing the difference in smoothness.

**Environment details**
```
kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
Darwin Milans-MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		14.0 BuildVersion:		23A344
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/milan/.config/kitty/kitty.conf

Config options different from defaults:
font_family JetBrains Mono
font_size   18.0

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
	LANG                                en_CA.UTF-8
	SHELL                               /bin/zsh
	USER                                milan
```

**Comment by kovidgoyal** [comment]
Doesnt repro on my Linux machine with

kitty --config=NONE -o 'font_family JetBrains Mono' --debug-font-fallback cmatrix

It's probably something specific to CoreText on macOS, although given
that kitty only renders ligatures once and uses the cached result I
cant think what it could be maybe the cache is not working on macOS?
Sadly I am swamped at the moment with work for a big calibre release,
so I dont have time to look into this, so patches welcome, or you will
have to wait till I can get around to it.

**Comment by milan-panta** [comment]
i get the same result (choppy) when pasting that snippet. Likely a mac specific issue, I'll just use the no ligatures version until it gets patched. Thank you for your work.
