### ISSUE TITLE
PS2 and multi-line PS1 leaks `;k=s` in bash when opening the scrollback buffer

### ISSUE THREAD

**Issue by agostonbarna** [kovidgoyal/kitty#6745]
**Describe the bug**
PS2 and multi-line PS1 leaks `;k=s` in bash when opening the scrollback buffer.

**To Reproduce**

**Steps to reproduce the behavior with the default PS2**
1. Set up an empty ~/.bashrc and ~/.bash_profile to make sure it does not affect this
2. Open kitty with the default config and bash shell: `kitty --config NONE -o shell=bash`
3. Type `\` then hit `Enter` in kitty
4. Press Ctrl+Shift+H in kitty to open the scrollback buffer
5. Notice the `;k=s` characters are leaked onto the screen from the OSC 133 shell integration:
```
bash-5.2$ \
;k=s> 
```

**Steps to reproduce the behavior with a multi-line PS1**
1. Set up a minimal ~/.bashrc to reproduce this: `PS1="LINE1\nLINE2 "`, and an empty ~/.bash_profile to make sure it does not affect this
2. Open kitty with the default config and bash shell: `kitty --config NONE -o shell=bash`
3. Press Ctrl+Shift+H in kitty to open the scrollback buffer
4. Notice the `;k=s` characters are leaked onto the screen from the OSC 133 shell integration:
```
LINE1
;k=sLINE2 
```

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/5561396/ecd0998c-ef12-465b-be1b-e30e5c1088f2)
![image](https://github.com/kovidgoyal/kitty/assets/5561396/0631ac08-bc97-4c64-ace7-a77852b322ee)

**Expected behavior**

The `;k=s` characters are hidden from the scrollback buffer like the other OSC sequences.

**Environment details**
```
kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
Linux fedora 6.5.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 11 04:07:58 UTC 2023 x86_64
S
Kernel 6.5.7-200.fc38.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: True
Paths:
  kitty: /home/barnabas/.local/bin/kitty
  base dir: /home/barnabas/.local/lib/kitty
  extensions dir: /home/barnabas/.local/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  shell bash

Config options different from defaults:
shell bash

Important environment variables seen by the kitty process:
	PATH                                /home/barnabas/.bin/work:/home/barnabas/.bin/linux:/home/barnabas/.bin/desktop:/home/barnabas/.bin:/home/barnabas/.local/bin:/home/barnabas/.local/share/cargo/bin:/home/barnabas/.local/share/go/bin:/home/barnabas/.local/share/node/modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                barnabas
	XDG_MENU_PREFIX                     gnome-
	XDG_DATA_HOME                       /home/barnabas/.local/share
	XDG_CONFIG_HOME                     /home/barnabas/.config
	LC_MONETARY                         hu_HU.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            hu_HU.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_CACHE_HOME                      /home/barnabas/.cache
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      hu_HU.UTF-8
	XDG_STATE_HOME                      /home/barnabas/.local/state
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             hu_HU.UTF-8
	LC_NUMERIC                          C
```

**Additional context**

I could reproduce this on Fedora 38 with bash 5.2.15(1), and on macOS Sonoma with bash 5.2.15(1) and bash 3.2.57(1)

**Comment by kovidgoyal** [comment]
that will be because you are using an outdated version of less that
doesn't support these escape codes. Update less or wait until I get
around to writing a replacement for less.

**Comment by kovidgoyal** [comment]
Doesnt repro for me on linux with less 643 with

kitty --config NONE -o shell=bash

and empty bash startup files. Make sure the less kitty is invoking is the updated less and not your original system less.

**Comment by kovidgoyal** [comment]
actually never mind I forgot about the multiline part, I can repro it.

**Comment by kovidgoyal** [comment]
And using the following script as a scrollback_pager
```sh
echo 'bytes received'
cat | hexdump
kitten __hold_till_enter__ < /dev/tty
```

we see that the bytes sent by kitty to less are

```
0000000 5b1b 1b6d 315d 3333 413b 5c1b 6b5b 766f
0000010 6469 6740 7465 6661 7869 6220 6e69 245d
0000020 5c20 1b0a 6d5b 5d1b 3331 3b33 3b41 3d6b
0000030 1b73 3e5c 0a20 0a0a 0a0a 0a0a 0a0a 0a0a
0000040 0a0a 0a0a 0a0a 0a0a 0a0a 0a0a 0a0a 0a0a
0000050 0a0a 0a0a 0a0a 0a0a 0a0a 000a          
000005b
```

this is perfectly correct, the bug is in less not stripping out the secondary prompt marking of the form `<ESC>]133;A;k=s<ST>`.  It's basically stopping at the semi-colon instead of going on to the <ST> bytes. Presumably whatever parser/regex less is using to strip out these is buggy. You should report the bug to less or wait for me to write that less replacement based on a correct escape code parser.

**Comment by agostonbarna** [comment]
@kovidgoyal: thanks for looking into this :+1:
