### ISSUE TITLE
colorspace option seems not working on M2 chip macbook

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#6747]
Is the "colorspace" option in Kitty still valid for the M2 chip MacBook in terms of color rendering? I tested the option, but I didn't notice any difference with any of the colorspace options. Second, I'm encountering this error on my Kitty. Should I be concerned, and how can I resolve it? Will this affect the quality negatively?

[297 18:02:04.913775] WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation

I am running latest kitty 0.30.1 on macOS 14.0

**Comment by kovidgoyal** [comment]
No you shouldnt be concerned and colorspace continues to work as it
always has. Use a color meter if your eyes cant discern a difference.

**Comment by ciscohack** [comment]
But then why we have this error "WARNING: Your system's OpenGL implementation does not have glCopyImageSubData, falling back to a slower implementation"
