### ISSUE TITLE
Incorrect rendering of tree

### ISSUE THREAD

**Issue by chergert** [kovidgoyal/kitty#6752]
**Describe the bug**
Run a `tree ~/` inside kitty and get strange artifacts in output

I need another terminal to launch my gnome-terminal/vte work, so I tend to use kitty for that. Was comparing performance of some things today and noticed artifacts in the Kitty rendering. My VTE work is also GPU rendered and renders fine, so I suspect this is either a Kitty issue or a Kitty/Asahi GPU driver combination issue. It looks like Asahi supports GL 3.1.

Happy to help you debug further as remote hands if you need. I'm all too familiar with how frustrating GL rendering work can be.

**To Reproduce**
1. Start kitty (From GNOME Shell overview)
2. Maximize window
3. `tree ~/`

**Screenshots**
![Screenshot from 2023-10-24 15-18-45](https://github.com/kovidgoyal/kitty/assets/25676/eb44d092-058a-469d-b938-eb9d139ff4aa)

**Environment details**
```
kitty 0.30.0 created by Kovid Goyal
Linux fedora 6.5.6-403.asahi.fc39.aarch64+16k #1 SMP PREEMPT_DYNAMIC Wed Oct 11 21:20:41 UTC 2023 aarch64
S
Kernel 6.5.6-403.asahi.fc39.aarch64+16k on an aarch64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/chergert/.local/bin:/home/chergert/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                chergert
	XDG_DATA_DIRS                       /home/chergert/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

**Additional context**
Default kitty setup (just `dnf install kitty` from Fedora Asahi Remix.

M2 Pro based macbook pro 16" w/ Fedora Asahi Linux (F39)

**Comment by kovidgoyal** [comment]
That's definitely a GPU driver issue, not a kitty issue. There was a very similar one with VirtualBox GPU drivers, if you search the issue list you will find it, the VIsrtualBox driver was eventually fixed, presumably the asahi driver needs a similar fix.
