### ISSUE TITLE
Some Shell Integration functionality doesn't work

### ISSUE THREAD

**Issue by BozeBro** [kovidgoyal/kitty#6753]
**Describe the bug**
I have shell_integration explicity set in my kitty.conf file. I see some of the basic features that the website says like clicking on a cmd will bring the cursor there and having a bar instead of a block cursor. However, some commands like show_last_command_output and its other variants don't actually show the last output, only a blank screen.

**To Reproduce**
Run kitty --config=NONE -o 'scrollback_pager=less --RAW-CONTROL-CHARS' -o 'map ctrl+shift+k show_last_non_empty_command_output' with blank zshrc file
Run ls
Run Clear
Press ctrl+shift+k
Result is a blank screen but should be the previous output of ls

**Environment details**
```
kitty 0.30.1 (b1ec1c2678) created by Kovid Goyal
Darwin benedicts-air.wifi.local.cmu.edu 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		14.0 BuildVersion:		23A344
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/MyUser/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control true
editor               /opt/homebrew/bin/nvim
Added shortcuts:
	f1 →  launch --allow-remote-control kitty +kitten broadcast --match title:"^Master"
	f2 →  launch --title current
Changed shortcuts:
	cmd+enter →  new_window_with_cwd
	kitty_mod+k →  show_last_command_output

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.0yaVo7j9Fq/org.xquartz:0
	USER                                ______ (Omitted)

```

**Additional context**

I saw from people's previous issues that p10k was causing shell integration issues, and I had an older version, but I uninstalled it and removed all references.

MY kitty config

editor /opt/homebrew/bin/nvim
allow_remote_control true
map cmd+enter new_window_with_cwd

kitty_mod ctrl+shift
shell_integration enabled
map ctrl+shift+k show_last_command_output

**Comment by kovidgoyal** [comment]
Running clear will *erase* the last command output. There is nothing to
report. Read https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal
