### ISSUE TITLE
Sudo alias in shell integration breaks `sudo --edit`

### ISSUE THREAD

**Issue by kidonng** [kovidgoyal/kitty#6754]
**Describe the bug**

d96fdb80edf0c743ead772219980dcd8007bdc24 introduced sudo alias which [does not work with `sudo --edit` (or `sudo -e`)](https://www.sudo.ws/docs/man/sudo.man/#you~2).

The integration will need to check for the flag before adding the environment variable.

**To Reproduce**
1. Enable shell integration, without `no-sudo`
2. Run `sudo -e`
3. See error

```sh-session
$ sudo -e /etc/pacman.conf
sudo: you may not specify environment variables in edit mode
```

**Screenshots**
N/A

**Environment details**
N/A

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
It's a simple alias, changing it to a function and parsing sudo command
line arguments is way more brittle. You have various options:

1) no-sudo in kitty.conf
2) Run sudoedit instead of sudo -e
3) Run sudo vim file instead of sudo -e file

Although I have to say, sudo -e is absurdly insecure. It allows any
process running as the user on the computer to edit the file, since it
works by creating a temp file owned by the user and then copying that
to the actual file.

**Comment by kidonng** [comment]
> It's a simple alias, changing it to a function and parsing sudo command
> line arguments is way more brittle.

For this case the solution is simple enough. I can't speak for other shells, but for fish it's to change

https://github.com/kovidgoyal/kitty/blob/b1ec1c2678a6efddf25999fb420373dcffe2beab/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish#L113-L115

to

```fish
if test -n "$TERMINFO"
    function sudo
        if ! contains -- --edit $argv && ! contains -- -e $argv
            set --prepend argv TERMINFO="$TERMINFO"
        end
        command sudo $argv
    end
end
```

(The shell integration should better use `function` instead of `alias` anyway, but that's another topic)

> Although I have to say, sudo -e is absurdly insecure.

I won't argue with that, just the error message is too cryptic unless you already know kitty will alias sudo (as I suppose few people would do that themselves).

**Comment by kovidgoyal** [comment]
Nope, that will break when using sudo to run a command that happens to
take the -e option such as

sudo grep -e whatever

**Comment by mil-ad** [comment]
Maybe this should go into a separate issue but this integration also breaks `wg-quick` that interfaces with Wireguard with this error message:

```
sudo: sorry, you are not allowed to set the following environment variables: TERMINFO
```

**Comment by SevereOverfl0w** [comment]
As an alternative to disabling aliasing in kitty.conf you can also enable TERMINFO to be conveyed via sudo by placing this in your `/etc/sudoers` or (or in my case I was able to place it in `/etc/sudoers.d/env_kitty`):

```
Defaults env_keep += "TERMINFO"
```
