### ISSUE TITLE
Config Option: Force Background Transparency

### ISSUE THREAD

**Issue by TheTollingBell** [kovidgoyal/kitty#6756]
**Is your feature request related to a problem? Please describe.**
One thing that I liked about Alacritty was the option `colors.transparent_background_colors` which forces all background colors to be transparent. I understand that for high opacity it makes sense but in my use case it ends up making my status bars pop too much, when they should really also be transparent.

**Describe the solution you'd like**
Add another config option similar to Alacritty's that allows this.

**Describe alternatives you've considered**
It's suggested on the Kitty wiki to just change the color of the application but in my case the status line should be a different color but still be transparent.

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
Not something I care about, patches welcome.
