### ISSUE TITLE
facing issue with shell integration and allow_remote_control feature

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#6757]
Hi Kovid,

Is there a way to test whether kitty shell integration is okay or not? I have followed the doc and enabled shell_integration and ran the kitten run-shell command for auto integration and also tried the manual method of adding config snippet in zshrc but unfortunately, some of the key bindings related to shell integration are not working for me. I can't use ctrl+shift+g and ctrl+shift+z and ctrl+shift+x  keybindings

kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
ProductName:            macOS ProductVersion:           14.0 BuildVersion:              23A344
  system shell: /bin/zsh
Loaded config files:
  /Users/praverai/.config/kitty/kitty.conf

Config options different from defaults:
bold_font                          OperatorMonoSSmNerdLig-Book
font_family                        OperatorMonoSSmNerdLig-Light
font_size                          16.0
hide_window_decorations            1
listen_on                          unix:${TEMP}/mykitty
macos_colorspace                   displayp3
macos_quit_when_last_window_closed True
macos_thicken_font                 0.2
scrollback_lines                   50000
text_composition_strategy          2.4 40
shell_integration enabled
Colors:
        background                         #23272e   
        color0                             #3f4451   
        color1                             #e05561   
        color10                            #a5e075   
        color11                            #f0a45d   
        color12                            #4dc4ff   
        color13                            #de73ff   
        color14                            #4cd1e0   
        color15                            #e6e6e6   
        color2                             #8cc265   
        color3                             #d18f52   
        color4                             #4aa5f0   
        color5                             #c162de   
        color6                             #42b3c2   
        color7                             #d7dae0   
        color8                             #4f5666   
        color9                             #ff616e   
        cursor                             #528bff   
        foreground                         #abb2bf   
        selection_background               #2c313a   
        selection_foreground               #d7dae0   
        url_color                          #4d78cc   

map ctrl+shift+g show_last_command_output
map ctrl+shift+x scroll_to_prompt 1
map ctrl+shift+z scroll_to_prompt -1

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                praverai

:

The second issue I face on my kitty is when I set "allow_remote_control to yes" and then when I type kitty on the terminal nothing happens and the kitty prints a traceback as below.

[299 13:51:37.263397] The font OperatorMonoSSmNerdLig-Light was not found, falling back to Menlo
[299 13:51:37.263444] The font OperatorMonoSSmNerdLig-Light was not found, falling back to Menlo
[299 13:51:37.349720] Traceback (most recent call last):
  File "lib/python3.9/kitty/main.py", line 559, in main
  File "lib/python3.9/kitty/main.py", line 551, in _main
  File "lib/python3.9/kitty/main.py", line 293, in __call__
  File "lib/python3.9/kitty/main.py", line 271, in _run_app
  File "lib/python3.9/kitty/boss.py", line 364, in __init__
  File "lib/python3.9/kitty/boss.py", line 177, in listen_on
FileNotFoundError: [Errno 2] No such file or directory

**Comment by kovidgoyal** [comment]
You cannot use env vars in listen_on. Use /tmp not ${TEMP}

And if the variable _ksi_state is defined in your shell then shell
integration is active.

Also to ask for help, use discussions, not issues.
