### ISSUE TITLE
CMD key for Mac

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#676]
Is it possible to use the CMD (Command) Key found on a Mac keyboard to replace mappings in kitty.conf?
For example: instead of Ctrl+Shift+C use Cmd+C for copy.

**Comment by johnallen3d** [comment]
Use the word `super` for the Command key. For example:

```conf
map super+shift+]       next_tab
```

**Comment by mihaicristiantanase** [comment]
Works perfectly. Thanks!

**Comment by kovidgoyal** [comment]
Youcan use super, cmd or even ⌘

**Comment by kai-alpha** [comment]
I guess this worths a paragraph under https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts ?
