### ISSUE TITLE
Unable to paste in to main window

### ISSUE THREAD

**Issue by ba0f3** [kovidgoyal/kitty#6762]
**Describe the bug**
After run command `kitty @ send-text --match 'title:^Output' --stdin` in main windows, unable to paste anything in to it, hence unable to paste to matched windows

**To Reproduce**
1. launch new window: `kitty @ launch --title Output --keep-focus`
2. run send-text with stdin: `k @ send-text --match title:^Output --stdin`
3. Paste text into main windows: use Ctrl + V, Ctrl +Shift + V, Shift + Insert
4. I map F2 with command `paste_from_clipboard` too, but it wont work

**Environment details**
```
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Linux k87 6.5.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1kali2 (2023-10-03) x86_64
XX GNU/Linux Rolling xxx /dev/tty

Running under: X11
Frozen: True
Paths:
  kitty: /opt/kitty/bin/kitty
  base dir: /opt/kitty/lib/kitty
  extensions dir: /opt/kitty/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /home/huy/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
background_opacity   0.85
font_family          "Fira Code"
font_size            8.0
tab_bar_style        powerline
Added shortcuts:
        f1 →  new_window_with_cwd
        f2 →  paste_from_clipboard
Changed shortcuts:
        kitty_mod+- →  change_font_size all -0.5
        kitty_mod+= →  change_font_size all +0.5
        shift+insert →  paste_from_clipboard
```

**Comment by kovidgoyal** [comment]
--stdin means anything you paste will be read by the send-text kitten so
it wont show up on your screen.

**Comment by ba0f3** [comment]
It did work before, but stopped in recent versions, I usually used it to paste commands in to multiple server

**Comment by kovidgoyal** [comment]
Use the broadcast kitten for that.
https://sw.kovidgoyal.net/kitty/kittens/broadcast/

If that doesnt work too let me know and I will take a look.

**Comment by ba0f3** [comment]
It works, thank you!
