### ISSUE TITLE
Incremental selection by using mouse

### ISSUE THREAD

**Issue by SammysHP** [kovidgoyal/kitty#6772]
**Is your feature request related to a problem? Please describe.**
This is about selecting text using the mouse and double/triple click. Kitty already tries to be clever and handles some special cases like URLs. There are also configurable word delimiters and keyboard modifiers (e.g. select from word to end of line).

But often this is not enough. Consider the following example:

```
echo "foo bar baz"
```

Double clicking on `foo` selects foo:

```
echo "[foo] bar baz"
```

(In these examples `[…]` indicate the selected text).

Triple clicking foo selects the whole line:

```
[echo "foo bar baz"]
```

**Describe the solution you'd like**
_urxvt_ supports complex selections provided by the `selection` extension. The delimiters can be configured and it is also possible to configure custom regular expressions.

> A double-click usually selects the word under the cursor, further clicks will enlarge the selection.

Double clicking on `foo` and then continue to click would result in the following sequence:

```
echo "foo bar baz"
echo "[foo] bar baz"
echo "[foo bar baz]"
echo ["foo bar baz"]
[echo "foo bar baz"]
[echo "foo bar baz"          ]   # whole line including newline
echo "[foo] bar baz"
```

This is very convenient in many situations like selecting quoted arguments, a single word of such an argument, text in parentheses, parts of an URL (like the domain) or another click that selects the whole URL etc.

**Describe alternatives you've considered**
The support of Perl extensions make urxvt very powerful. It would be nice to have something similar, but for now handling this feature in Kitty itself would be more than enough.

**Additional context**
Just try it out with urxvt and the selection extension. I've also set `URxvt.cutchars: "\"&'()*,;<=>?@[\\]^`{|}:$"`.

**Comment by kovidgoyal** [comment]
Right click extends selections, you can also double and triple click and
drag to extend selections.

**Comment by SammysHP** [comment]
Dragging doesn't solve my use case because you have to determine and hit the boundaries manually. The required precision is additional workload because you have to move the mouse cursor precisely to the correct location twice.

The method I described automatically extends the selection to the next likely candidate as configured. This is similar to the already special case of detecting URLs and path names, but at the same time allows you to select for example the filename with extension, then the whole path and then the full line.

```
cat /path/to/file.txt
cat /path/to/[file.txt]
cat [/path/to/file.txt]
[cat /path/to/file.txt]
```

**Comment by kovidgoyal** [comment]
I am afraid I have no interest in scripting mouse selections, I much
prefer to use the hints kitten for selecting snippets of text anyway.
Which is completely scriptable, in python.

And no, you dont need to hit boundaries, double click somewhere to select
a word, then right click anywhere in the word you want to extend the
selection to.

**Comment by SammysHP** [comment]
Here is an example from urxvt. The first double click selects `foo`, each consecutive click extends the selection to the next matcher.


https://github.com/kovidgoyal/kitty/assets/922874/a7eb575d-7acb-486b-bd42-8d7762ddd65a

**Comment by didib** [comment]
@SammysHP Thanks for tagging my issue. Did you find a solution? What do you use? Thanks!

**Comment by SammysHP** [comment]
@didib Haven't found a solution yet.
