### ISSUE TITLE
Api to explicitly change tab title

### ISSUE THREAD

**Issue by dmtrKovalenko** [kovidgoyal/kitty#6773]
**Is your feature request related to a problem? Please describe.**
My problem is straightforward — I usually travel across different projects using Vim's project management tools and my tab's titles are either do not represent current open projects or display something like this 

<img width="869" alt="image" src="https://github.com/kovidgoyal/kitty/assets/16926049/028f6bff-68da-4a4b-a14f-49b8ec187442">

**Describe the solution you'd like**
My desired solution is to be able to do something like that will change the title of the current tab

```
kitty set-title <<My project name>>
```
and then I will set my chdir to execute this every time Vim switches the cwd

**Describe alternatives you've considered**
Using shell-based titles are alternative but they are usually very limited and do not always allow totally custom values. The fish version is executing before and after the command which makes it impossible to use with the vim and totally custom switching between different context within one command

**Additional context**
If you are interested I can try to open PR on my own, just wanna sync first and will wait for the green light!

**Comment by kovidgoyal** [comment]
Already possible with https://sw.kovidgoyal.net/kitty/remote-control/
