### ISSUE TITLE
Current window index in tab_title_template

### ISSUE THREAD

**Issue by cesher** [kovidgoyal/kitty#6775]
**Is your feature request related to a problem? Please describe.**
When using the stacked window layout and multiple windows I can't tell which window I am on. I would like some form of affordance I could display somewhere.

**Describe the solution you'd like**
A `window_index` option for `tab_title_template`. Currently I am using:
```
tab_title_template "{index}: {title}[{num_windows}]"
```
and would like to set it like so:
```
tab_title_template "{index}: {title}[{window_index}:{num_windows}]"
```

**Describe alternatives you've considered**
I am unaware of any other way to tell which window I am on. Besides the window index, it would be interesting to see window names, similarly to how I can name panes.

**Additional context**
nope.

**Comment by kovidgoyal** [comment]
Set the window title to whatever you want and then `title` in the
template will show it.

**Comment by cesher** [comment]
> Set the window title to whatever you want and then `title` in the template will show it.

@kovidgoyal How do I give a kitty window a custom title, the documentation doesn't say anything about that. I've only been able to find a mention of setting the tab title with `crtl+shift+alt+t` and `shift+cmd+i` on macos.

**Comment by kovidgoyal** [comment]
On Wed, Nov 01, 2023 at 11:30:58AM -0700, Cesar Hernandez wrote:
> > Set the window title to whatever you want and then `title` in the template will show it.
> 
> @kovidgoyal How do I give a kitty window a custom title, the documentation doesn't say anything about that. I've only been able to find a mention of setting the tab title with `crtl+shift+alt+t` and `shift+cmd+i` on macos.

THere is a standard escape code you can use in all terminals to set the
window title. Google it or use the kitty remote control API which has 
a command to set the window title.
