### ISSUE TITLE
Allow braille characters to be rendered by font

### ISSUE THREAD

**Issue by n6v26r** [kovidgoyal/kitty#6776]
I know that it's in kitty's design pattern to have some glyphs rendered independent of font, but could we at least have a toggle for it?
This has been a very requested thing throughout the community, and I understand the reasoning behind the current choice, but mabye such an antifeature isn't the best solution...

**Comment by kovidgoyal** [comment]
THis has been asked and answered.

**Comment by Maritsu** [comment]
> [...] but could we at least have a toggle for it?

You can do it by editing the source code; e.g. to disable Braille characters being rendered in the kitty-specific way, comment out the line https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts.c#L621 (`kitty/fonts.c:621`).
