### ISSUE TITLE
Propagate command exit status

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#678]
When starting Kitty and giving it some program to run, e.g.
```
kitty /bin/bash -c "./configure && make -j"
```
it would be nice if Kitty could propagate exit status returned by the command (`/bin/bash` in this example) to exit status of Kitty process itself.

**Comment by kovidgoyal** [comment]
That's fine when there is one command, but what if the kitty process has
multiple windows? Or if the process is ended by using the close window
shortcut rather than the child process dying? I dont think this can be
made reliable enough to be useful.

**Comment by Frederick888** [comment]
I actually have a use case for this.

I'm working on https://github.com/Frederick888/external-editor-revived which opens Vim/Neovim/etc in a terminal to edit Thunderbird emails. It opens a new Kitty instance, containing only the editor (like `kitty --start-as=normal -- nvim /path/tmp.eml`), and wait for Kitty to exit and report back to Thunderbird.

So in case the editor crashes, it'll be nice if Kitty can exit with a non-0 code, and then I can preserve the temporary file and show a warning notification. If Kitty is ended by using a shortcut (or close button on the window title bar etc), I'm fine with a 0 exit code and I can document this to tell users to avoid doing this.

**Comment by kovidgoyal** [comment]
As I said before this isnt really robust. If you need this simply use a wrapper bash script to launch the editor. It can run the editor and record its exit status somewhere.
