### ISSUE TITLE
kitten ssh breaks `'^ '` mapping in ZSH after returning from session

### ISSUE THREAD

**Issue by mehalter** [kovidgoyal/kitty#6780]
**Describe the bug**

If I have something bound to ctrl-space in ZSH (`'^ '`) and I use `kitten ssh` to ssh to a host it breaks my original mapping.

This does not even have to be a complete, successful ssh connection. If you use `kitten ssh` to access a machine with a password prompt (not password-less login) and quit with `<C-c>` several times, the mapping is still broken. This rules out that conflicting ZSH bindings could be coming into play.

I have tested this across many terminals and cannot replicate the issue. I also cannot replicate the issue when I just use `ssh` and do not use `kitten ssh`

**To Reproduce**

1. Start a clean kitty session with no config: `kitty --config=NONE`
2. Start a clean zsh session with no config: `zsh -f`
3. Set a ctrl+space binding: `bindkey -s '^ ' TEST`
4. Test that it works by pressing ctrl+space
5. SSH to a remote machine with `kitten ssh`
   - this doesn't have to complete, you can ctrl+c back to the prompt from the password prompt
6. Close the session and return to your machine
7. Press ctrl+space and see that "TEST" is not printed
8. run `bindkey` and see that the binding is still set

**Environment details**
Fully and completely clean environment with v0.30.1 to rule out all possible conflicts

**Comment by mehalter** [comment]
Thanks for the quick fix! 😍

**Comment by mehalter** [comment]
@kovidgoyal this problem is not fully resolved. This should be reopened. If you do `ctrl-c` in the middle of making an ssh connection then the mapping still gets messed up. It does seem to be resolved in the case where a full ssh connection is made and then closed.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/bc1da5525e97164389eb9466ccf62a76c78c5942

**Comment by mehalter** [comment]
Thanks! I'll test in the next day or two! 🤞 Very excited for this to be resolved after many months! Thanks so much for quick fixes after reporting with a clear issue.

**Comment by mehalter** [comment]
I can confirm that this appears to be fully fixed. Thanks again!
