### ISSUE TITLE
FR: A kitten to do port forwarding over tty

### ISSUE THREAD

**Issue by amosbird** [kovidgoyal/kitty#6782]
There are cases when ssh port forwarding is not available due to security concerns or multiple ssh jumps. We already support `transfer` kitten that works over nested SSH sessions. Maybe it's possible to extend that support to forward port? (It should be fine that during the forwarding, the current SSH session will be irresponsive)

**Comment by kovidgoyal** [comment]
It's possible technically, but it would be a fair bit of work to
implement. It means creating a new escape code based protocol for it and
implementing it in both kitty and a kitten. I dont have a personal use
for this, so it's not worth the effort to me, but patches are welcome, I
can provide any needed guidance on protocol design/implementation.

**Comment by amosbird** [comment]
> It's possible technically

Thanks for confirming that it's doable. I'll try to build a prototype based on the transfer kitten.
