### ISSUE TITLE
Transparency setting not working

### ISSUE THREAD

**Issue by LittleHendrix** [kovidgoyal/kitty#6790]
**Describe the bug**

Same issue as reported in [#6545](https://github.com/kovidgoyal/kitty/issues/6545)

I have tried running `kitty cat` and it works as expected (see attached).

kitty cat renders transparency as expected. However, it's not working when I load kitty normally, and I can see that it's trying to apply transparency as I can see the transparent gaps (padding) around the terminal window. But the main area is completely opaque.

**Screenshots**
normal window
![image](https://github.com/kovidgoyal/kitty/assets/1037065/a390fa8c-4e4a-49ff-ba4c-c9e4a550ad28)

kitty cat window on top
![image](https://github.com/kovidgoyal/kitty/assets/1037065/d8a2ed6e-95f6-4772-b9ea-88fe68a38369)

**Environment details**
```
kitty 0.30.1 (6a3529b7c2) created by Kovid Goyal
Darwin chen.lu@tray.io 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64
ProductName:            macOS ProductVersion:           14.1 BuildVersion:              23B74
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/chen/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.5
bold_font             UbuntuMono Nerd Font Bold
bold_italic_font      UbuntuMono Nerd Font Bold Italic
cursor_blink_interval 0.5
cursor_shape          3
enabled_layouts       ['splits', 'stack']
font_family           UbuntuMono Nerd Font Regular
font_size             13.0
inactive_text_alpha   0.5
italic_font           UbuntuMono Nerd Font Italic
modify_font:
    cell_height 2
scrollback_lines      10000
shell_integration     frozenset({'no-cursor'})
tab_bar_edge          1
tab_bar_style         powerline
tab_powerline_style   slanted
tab_title_template    {index} {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}
window_padding_width  FloatEdges(left=1.5, top=1.5, right=1.5, bottom=1.5)
Added shortcuts:
        shift+cmd+0 →  resize_window reset
        shift+cmd+down →  resize_window shorter 3
        shift+cmd+h →  launch --location=hsplit --cwd=current
        shift+cmd+left →  resize_window narrower 2
        shift+cmd+n →  new_os_window_with_cwd
        shift+cmd+r →  layout_action rotate
        shift+cmd+right →  resize_window wider 2
        shift+cmd+t →  new_tab_with_cwd
        shift+cmd+up →  resize_window taller 3
        shift+cmd+v →  launch --location=vsplit --cwd=current
        shift+cmd+z →  toggle_layout stack
Changed shortcuts:
        shift+cmd+i →  launch --allow-remote-control kitty +kitten broadcast
Colors:
        background            #2e3440   
        color0                #3b4252   
        color1                #bf616a   
        color10               #a3be8c   
        color11               #ebcb8b   
        color12               #81a1c1   
        color13               #b48ead   
        color14               #8fbcbb   
        color15               #eceff4   
        color2                #a3be8c   
        color3                #ebcb8b   
        color4                #81a1c1   
        color5                #b48ead   
        color6                #88c0d0   
        color7                #e5e9f0   
        color8                #4c566a   
        color9                #bf616a   
        cursor                #81a1c1   
        foreground            #d8dee9   
        tab_bar_background    #444444   

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                en_GB.UTF-8
        SHELL                               /bin/zsh
        USER                                chen

On older versions of kitty, run kitty --debug-config instead
```

**Comment by kovidgoyal** [comment]
that will mean your shell rc files are changing the background color.
Bisect them to find the culprit.

**Comment by LittleHendrix** [comment]
> that will mean your shell rc files are changing the background color. Bisect them to find the culprit.

Thank you for the quick reply 👍

**Comment by Bretton-K-Scarbrough** [comment]
@LittleHendrix where you able to identify the specific issue?

**Comment by sherloach** [comment]
same here! did you find any solutions please? @LittleHendrix @Bretton-K-Scarbrough

**Comment by LittleHendrix** [comment]
@Bretton-K-Scarbrough @sherloach ok guys, what I had done to make this working in the end, was to reboot the OS. I've tried reloading the config inside kitty, as well as restarting kitty. But neither had worked. And I didn't change any settings in the end, as it looked correct. So, after a fresh reboot, I started kitty, and then the transparency kicked in.

**Comment by sherloach** [comment]
yes, it worked. Thanks! @LittleHendrix

**Comment by rolanday** [comment]
> @Bretton-K-Scarbrough @sherloach ok guys, what I had done to make this working in the end, was to reboot the OS. I've tried reloading the config inside kitty, as well as restarting kitty. But neither had worked. And I didn't change any settings in the end, as it looked correct. So, after a fresh reboot, I started kitty, and then the transparency kicked in.

Didn't believe it would work, but rebooted and sure enough. Would love to know why. Regardless, thank you!
