### ISSUE TITLE
Feature Request: layout picker

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#6795]
It would be great if there was a layout picker (i guess a fullscreen app like kitten:unicode) that would:

* show you all layouts that will be cycled through when firing `next_layout` (ie, those in `enabled_layouts`)
* allow you to switch
* also show inactive layouts (with default options) that you can switch to

I was going to write a kitten for this but afaict there isn't a remote control api to read the current layout (nor one to view currently enabled layouts).

<img width="842" alt="image" src="https://github.com/kovidgoyal/kitty/assets/18601956/d2457bcd-a712-423f-aee8-713f72177249">

Motivation: I currently have 

```
enabled_layouts splits:split_axis=vertical, *
```

which correct me if i'm wrong enables eight layouts in the order

* custom splits
* stack
* tall
* fat
* grid
* default splits
* horizontal
* vertical,

and it is not trivial at all to navigate between them with 0 aid. Thanks for the consideration

**Comment by kovidgoyal** [comment]
You can get the current layout, last used layout and enabled layouts via
kitten @ ls (look at the fields in the "tab" object.

After that, writing a picker to choose one is pretty trivial, I leave
that as an exercise to the reader.

**Comment by edubxb** [comment]
Just my 2 cents, I added the current layout in the [tab title](https://github.com/edubxb/dotfiles/blob/main/home/private_dot_config/kitty/kitty.conf#L78), to know the current layout in use, so I can [cycle](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Next-layout) between them "easily".

Hope this helps!
