### ISSUE TITLE
Feature suggestion: marking position

### ISSUE THREAD

**Issue by Ma-Shell** [kovidgoyal/kitty#680]
Hello,
I have been meaning to implement the following feature into kitty and would like to hear 
your opinions about it:
The feature would include the possibility to add a marking, associating a name, category, and tags with a certain line and position in that line. Markings could be used for the following actions:
- Scrolling to a given mark
- Getting the text between two given marks

If bundled with shell-integration, this feature could become really powerful:
Most modern shells (at least bash, zsh, fish) have hooks that are executed before a command is executed (preexec) and before a prompt is printed (i.e. after a command is executed: precmd). My suggestion is for the user to add a script to be sourced in their shell's init-file to use these hooks and send a marking to kitty. These markings can then be used for the following:
- Scroll on a per-command-basis (i.e. scroll to the previous mark of the category "precmd"). This is quite useful, if one command prints a long text and you want to see the output of the command before that
- Get the output of a certain command (i.e. get the contents between a "preexec"-mark and the next "precmd"-mark).

# User-interaction:
I would mean to implement these features in the following way:
- Adding an additional command:
`kitty @add-mark [--mouse] [-n NAME] [-c CATEGORY] [-t TAGS]`
This command would insert the mark with the given name, category, tags (or corresponding default-values) in the position of the cursor or, if `--mouse` was specified at the current position of the mouse (so the user can manually insert custom marks at a key-stroke to come back to an interesting location later)
- Extending the `extent`-parameter of the `get-text`-command to support a range of two markings or giving the x-th last command:
`--extent=[MARK_NAME_FROM]:[MARK_NAME_TO]`
`--extent=cmd[X]`, whereas X is if positive, an id of the given command or if negative, the X-th-last command (i.e. -1 would give the last, -2 the one before that).
- Adding a command:
`kitty @scroll-to-mark [-n NAME | -c CATEGORY]`
This command would scroll to either the mark with the given name or the last mark from the given category.
- Adding a command:
`kitty @toggle-marks`
To toggle mark-rendering on and off.

# Rendering:
I would like to give the option to render the marks (i.e. as small colored names next to the text), which could be toggled on and off. Using tags, one could give special formatting options.
One thing that first comes to my mind: I would draw a line between a preexec- and a precmd-mark in order to signify that this is the output of one command. We could pass the output of `$?` as a tag to the precmd-mark in order to differently color the line to signify the output-status of the corresponding command (i.e. 0 would render green, while any non-zero-value would render red). (I will add a mockup of what I expect of rendering when I have time)

# Implementation details:
For Implementation I would add a line identifier (uint32_t should be enough) to each line, which is counted upwards automatically. Python would then keep track of a dictionary mapping the mark-name to the category, tags, x-position and line-id.
A line with the corresponding id can be quickly found, since the id of the last line is known and it can be simply counted backwards.
An overflow in the uint32_t would not be dramatic, since it would simply mean that old marks can not be used anymore, however, I think 4 billion lines should be enough for a single terminal session.

I believe, this feature would really benefit kitty without adding a lot of bloat (shouldn't be too hard to implement, either). However, I would like to hear your opinions before I really get on this!
The idea to this feature is somewhat rooted in the frames-feature (with a little less bling) which can be seen in https://github.com/sedwards2009/extraterm

**Comment by kovidgoyal** [comment]
From what I can tell you basically want a way to jump to previous commands in the scrollback buffer. You can do that already by using the existing kitty feature to open the scrollback in an external program. Simply add a directive to kitty.conf to open the scrollback in less with a search pattern matching the command prompt, then you can jump to previous command prompts using the N key.

This has the advantage of not needing to enable remote control and not needing any shell integration.

The only caveat is I dont know if less implements the ability to specify the search pattern as a command line argument. If not you would need to implement a pager kitten to use in place of less. This is on my TODO list anyway, as I want the ability to select arbitrary regions in the pager using vim movement commands, which less cannot do.

**Comment by Ma-Shell** [comment]
My main intuition was to get a way to quickly get the output of the previous command only, e.g. if I wanted to grep for something or go through it in a pager.
While this feature would be quite a bit more advanced, reliable and more flexible than just regex-searching for the prompt through the scrollback-buffer, you are right that most of this is already doable. I guess, this should in most cases be good enough and I can just add some very distinct strings to the start and end of the PS1-variable to make it more reliable. So I suppose, it wouldn't really be worthwile to integrate the markings into kitty, then.
