### ISSUE TITLE
Some characters seem to be ignored

### ISSUE THREAD

**Issue by Galactum** [kovidgoyal/kitty#6800]
kitty appears to not render some characters, such as this character >> ─ (U+2500).
I do not think this is to do with the font I am using as I tried several and none of them worked.
Below a side-by-side comparison of the same exact program running in kitty (left) and the standard macOS terminal (right)
<img width="1509" alt="image" src="https://github.com/kovidgoyal/kitty/assets/67226139/6d1d1667-e29a-4778-8f3b-e5bb811665dd">

**Comment by kovidgoyal** [comment]
kitty renders any and all characters that are presnt in a font on your
system.

printf "\u2500"

renders correctly on my macbook.

Most likely you have some font installed on your system that has an
empty glyph for this character. Use --debug-font-fallback to see which
font is used for it.
