### ISSUE TITLE
The CTRL-SHIFT-F5 and CTRL-SHIFT-F6 options only operate on config files loaded when kitty started

### ISSUE THREAD

**Issue by nileshpatra** [kovidgoyal/kitty#6801]
**Describe the bug**
The CTRL-SHIFT-F5 option does not reload the config when the user launches kitty for the first time/there is no kitty.conf present in ~/.config/kitty/

**To Reproduce**
```
Steps to reproduce the behavior:
1. Remove ~/.config/kitty (from another terminal)
2. Launch kitty terminal
3. Hit CTRL-SHIFT-F2
4. Change font_size to 20
5. Try to reload with CTRL-SHIFT-F5
```

Nothing happens. It was expected to get the font size changed. The font size would change only when the terminal is closed and a new (kitty) terminal window is opened, after which the reload works fine. This can be confusing for first time (new) kitty users.

**Additional context**
This was reported as a Debian bug report that has more verbose description in-case that helps: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054633

**Comment by kovidgoyal** [comment]
Does not reproduce for me with current kitty 0.31.0 Update kitty first
and if you can reproduce with that, let me know.

**Comment by nileshpatra** [comment]
Hi and thanks for the prompt response. I actually reproduced this with the latest kitty 0.31.0 before I opened this bug report.

I'm pasting a more verbose debug output in case that helps you out. Based on this it seems kitty does not load kitty.conf the first time it gets created and it only does that once the term is closed and opened again. I'd appreciate if this issue could be re-opened.

```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Linux debian 6.5.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1 (2023-10-07) x86_64
Debian GNU/Linux trixie/sid debian /dev/tty

Running under: X11
Frozen: True
Paths:
  kitty: /tmp/bin/kitty
  base dir: /tmp/lib/kitty
  extensions dir: /tmp/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0

Important environment variables seen by the kitty process:
	PATH                                /tmp/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
	LANG                                en_IN
	EDITOR                              /usr/bin/vim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                nilesh
	LC_ADDRESS                          en_IN
	LC_IDENTIFICATION                   en_IN
	LC_MEASUREMENT                      en_IN
	LC_MONETARY                         en_IN
	LC_NAME                             en_IN
	LC_NUMERIC                          en_IN
	LC_PAPER                            en_IN
	LC_TELEPHONE                        en_IN
	LC_TIME                             en_IN
	XDG_CURRENT_DESKTOP                 X-Cinnamon
	XDG_DATA_DIRS                       /usr/share/gnome:/home/nilesh/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_GREETER_DATA_DIR                /var/lib/lightdm/data/nilesh
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 lightdm-xsession
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SESSION_TYPE                    x11
	XDG_VTNR                            7
	LC_CTYPE                            en_US.UTF-8
	LC_ALL                              en_US.UTF-8
```

**Comment by nileshpatra** [comment]
To be complete, I took the binary directly from the releases here: https://github.com/kovidgoyal/kitty/releases/tag/v0.31.0

So there should be nothing else at play here as such.

**Comment by kovidgoyal** [comment]
Still doesnt reproduce for me with the steps:
1) Run kitty as
KITTY_CONFIG_DIR=$(mktemp -d) kitty
2) Press ctrl_shift+f2
3) Add the followinf line to the bottom of the file
font_size 21
4) save and quit the editor
5) press ctrl+shift+f2

font size is increased as expected.

I need an reproducer to be able to help you further.

**Comment by nileshpatra** [comment]
Thank you for checking. I think the correct variable as per [the docs](https://github.com/kovidgoyal/kitty/blob/master/docs/conf.rst) is `KITTY_CONFIG_DIRECTORY` instead (not KITTY_CONFIG_DIR).

I am able to repro the error after launching kitty as: `KITTY_CONFIG_DIRECTORY=$(mktemp -d) ./bin/kitty`
and emulating the steps 2-5 as you wrote above as-is.

Does this help?

**Comment by kovidgoyal** [comment]
On Fri, Nov 10, 2023 at 11:35:40AM -0800, Nilesh Patra wrote:
> Does this help? 

No, I need a way that *I* can reproduce it.

**Comment by nileshpatra** [comment]
On 11 November 2023 7:39:19 am IST, Kovid Goyal ***@***.***> wrote:
>On Fri, Nov 10, 2023 at 11:35:40AM -0800, Nilesh Patra wrote:
>> Does this help? 
>
>No, I need a way that *I* can reproduce it.

Ofcourse :)

Are you not able to reproduce even after using `KITTY_CONFIG_DIRECTORY` (**not** KITTY_CONFIG_DIR)?

If so, that'd be odd and I'll try to check across different systems.

**Comment by kovidgoyal** [comment]
On Fri, Nov 10, 2023 at 07:59:48PM -0800, Nilesh Patra wrote:
> 
> 
> On 11 November 2023 7:39:19 am IST, Kovid Goyal ***@***.***> wrote:
> >On Fri, Nov 10, 2023 at 11:35:40AM -0800, Nilesh Patra wrote:
> >> Does this help? 
> >
> >No, I need a way that *I* can reproduce it.
> 
> Ofcourse :)
> 
> Are you not able to reproduce even after using `KITTY_CONFIG_DIRECTORY` (**not** KITTY_CONFIG_DIR)?

I did use KITTY_CONFIG_DIRECTORY I simply typoed it when posting.

**Comment by Maytha8** [comment]
I've also been able to reproduce the issue described here, using the binary provided in the Releases on the latest version (0.31.0).

[Here's a video reproducing the bug](https://drive.google.com/file/d/1kRTaHF_ooiVtvTk_JMeBwXIXzkxNaN8i/view?usp=sharing) so you can see exactly what's happening when this bug is occurring.

**Comment by nileshpatra** [comment]
> I've also been able to reproduce the issue described here, using the binary provided in the Releases on the latest version (0.31.0).
> 
> [Here's a video reproducing the bug](https://drive.google.com/file/d/1kRTaHF_ooiVtvTk_JMeBwXIXzkxNaN8i/view?usp=sharing) so you can see exactly what's happening when this bug is occurring.

@kovidgoyal since by far it has been reproduced on latest kitty/kitten binary off GitHub by 3 people atleast 2 of which have different desktop env/window managers and configurations, it is hard to find a common source that would be causing this. This can ofcourse be due to some user (mis)configuration. If you could point us to any logs that we could look into in order to rootcause this, that'd be great and much appreciated! This can definitely wait until you have the time for it.

And ofcourse, Happy Diwali! 🪔

**Comment by kovidgoyal** [comment]
It's pretty trivial code just add a few prints for yourself and see
what's happening. Relevant function is load_config_file() in boss.py

If you find an issue, feel free to send a PR.

And Happy Diwali to you too.

**Comment by nileshpatra** [comment]
Thanks. I followed along these lines and oddly enough, `old_opts.config_paths` does not get updated in the same session and it shows me `OLD_OPTS: ('/etc/xdg/kitty/kitty.conf',)` even after the kitty.conf file has been created (ofcourse this only happens the first time).

On changing the config file loading code to use default path instead of old_path, it fixes the issue for me. Something like:

```
-        prev_paths = old_opts.config_paths or default_config_paths(self.args.config)
+        prev_paths = default_config_paths(self.args.config) or old_opts.config_paths
```

But I don't think this a very sensible thing to do. I tried to look at how `get_options` changes its `config_paths` and I see it is actually importing it from a `.so` lib which is compiled off a stub file. The only definition of this in a stub file with which I have very limited experience - so I'm not sure where to look next. Can I ask for some help with the next part, please?

**Comment by nileshpatra** [comment]
One difference I see is that kitty downloads the '.so' of all its deps and places the fast_datatype .so in kitty-extensions. However distros actually install the .py files and try to load the options from the '.so' file (/usr/lib/kitty/kitty/fast_data_types.so) same for arch linux as well: https://archlinux.org/packages/extra/x86_64/kitty/files/

Something happens differently when trying to load the get_options object everytime from distro path v/s the one in kitty-extensions with a bunch of other so libs. Not sure what exactly.

**Comment by kovidgoyal** [comment]
You have an existing
/etc/xdg/kitty/kitty.conf
?

If so that would explain it. Since the original config is loaded from
there, the code assumes thats what needs to be reloaded. 

I am guessing the debian package is for some reason installing this?
What's in it?

**Comment by nileshpatra** [comment]
> You have an existing /etc/xdg/kitty/kitty.conf ?
> 
> If so that would explain it. Since the original config is loaded from there, the code assumes thats what needs to be reloaded.

Ah, I see.

> I am guessing the debian package is for some reason installing this? What's in it?

$ cat /etc/xdg/kitty/kitty.conf
update_check_interval 0

This was added by the previous maintainer with this rationale, which makes sense for a distro package:

```
    Install a system kitty.conf to disable update checks
    
    By default, kitty will check every 24 hours if there is a new release
    available.  Since this is a packaged version, that serves no purpose
    other than phoning home.
    
    Signed-off-by: James McCoy <jamessan@debian.org>
```

**Comment by kovidgoyal** [comment]
Remove it, distro builds of kitty do not do update checking

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.update_check_interval

**Comment by nileshpatra** [comment]
Sorry for the admittedly stupid question but do I need to patch the instances of `update_check_interval` and set them to zero? If not would you consider to point me to the code where this is disabled for distribution packages?

**Comment by kovidgoyal** [comment]
You dont need to patch anything, it is done automatically. I cant be bothered to track down the code, if you dont believe me use a network monitoring tool to verify it for yourself.

**Comment by kovidgoyal** [comment]
Well actually line 1156 of boss.py shows that update_check_interval is only respected for frozen builds which distro builds are not.

**Comment by nileshpatra** [comment]
Yes, I just noticed that as well. I see you added a patch anyway :)

> if you dont believe me use a network monitoring tool to verify it for yourself.

And nothing like that -- I was only curious to look.

Thanks a lot for your help, I have never in my life seen another upstream responding to bug reports so quickly so I find it really cool!
