### ISSUE TITLE
Multiple font styles support

### ISSUE THREAD

**Issue by dpc** [kovidgoyal/kitty#6804]
**Is your feature request related to a problem? Please describe.**

No. I was looking at https://news.ycombinator.com/item?id=38210574 and it made me think - wouldn't it be cool if we could use different font styles in CLI text editors as well?

Someone said that xterm allegedly does support something like that already:

> `ESC[<10-19>m` is the escape sequence to pick font 0-9 

I have no idea if that's true, but in principle it doesn't seem all that difficult for a terminal to support it (I might be wrong thought, because what do I know).

**Describe the solution you'd like**

Would be great if Kitty supported it somehow. If if did it shouldn't be too difficult to add support for in CLI text editors like Helix.

**Comment by kovidgoyal** [comment]
You already have 4 fonts style available, regular, bold, italic and bold
italic. Adding more is not something I see much point in. Not to mention
that using different font faces wont work unless the faces have
compatible metrics. There are already issues with many exisitng
monospace families that dont even have compatible metrics between the
bold/italic/regular faces. 

As such, I dont think this is worth the effort. If in the future there
are many such compatible faces and somebody that writes a reasonably
popular editor commits to adding support for such a thing, I might be
willing to discuss. Until then, wontfix.

**Comment by dpc** [comment]
Fair enough.

> If in the future there
are many such compatible faces and somebody that writes a reasonably
popular editor commits to adding support for such a thing

![image](https://github.com/kovidgoyal/kitty/assets/9209/1f2b38d5-d48f-4eae-a9f2-685adc44673e)

**Comment by dpc** [comment]
I don't even think the text editors are the only potential user. I could imaging this being useful in many places - like shell auto-completion, menus, pagers, starship prompt.

If it's possible, people will find applications for it. Since it isn't possible, people assume it just has to be this way.

**Comment by dpc** [comment]
Oh, and it just occurred to me that it could be even useful for getting rid of hacks like patching fonts with nerdfonts...

**Comment by kovidgoyal** [comment]
You dont need to patch fonts in kitty already.

**Comment by dpc** [comment]
Thanks. I didn't know about it.

**Comment by PMunch** [comment]
> If in the future there are many such compatible faces and somebody that writes a reasonably
popular editor commits to adding support for such a thing, I might be willing to discuss. Until then, wontfix.

With the recent release of Monaspace this is exactly what we're seeing, fonts with matching metrics. And someone has to go first, there's no point for terminal editors to implement this feature if there are no terminal emulators that support it. If anything this would be a nice chance to make Kitty more popular as it would be mentioned all around as one of the few terminal emulators that supports this feature.

As for the amount of effort all the pieces are already there. With settings like `bold_font` and `italic_font` Kitty already supports switching between fonts based on escape codes. And of course the escape code parsing is already in place. So it feels like all that has to be updated is the config parser and a few extra SGR parameters.

Kitty is already such a great terminal emulator with a very rich feature set, and adding this fairly minor feature would enable it to do something quite few terminals can do.

**Comment by kovidgoyal** [comment]
On Fri, Nov 10, 2023 at 11:23:42AM +0000, Peter Munch-Ellingsen wrote:
> > If in the future there are many such compatible faces and somebody that writes a reasonably
> popular editor commits to adding support for such a thing, I might be willing to discuss. Until then, wontfix.
> 
> With the recent release of Monaspace this is exactly what we're seeing, fonts with matching metrics. And someone has to go first, there's no point for terminal editors to implement this feature if there are no terminal emulators that support it. If anything this would be a nice chance to make Kitty more popular as it would be mentioned all around as one of the few terminal emulators that supports this feature.

That's **one** font family with matching metrics and while it claims it
has matching metrics, whether it actually does have them remains to be
seem. Again unless you can get some *commitment* from someone developing
some significant terminal program to actually use this, I am not going
to spend time on it. I am not even asking for an implementation, just a
credible commitment.

I have stated I am willing to implement it provided there are likely to exist
some programs that will make use of it.

Get some commitments from the developers of some such programs and then
come back here. Until then I have far higher priority things to spend my
time on. Without a program actually using this feature, it wont help
kitty or its users in anyway, since it will be invisible/useless.

**Comment by kovidgoyal** [comment]
And here we go: #6807 so much for monaspace being metric compatible.

**Comment by PMunch** [comment]
> And here we go: #6807 so much for monaspace being metric compatible.

Seems like there's a little bit more than that to it. The Monaspace font has an issue on this which goes into some detail on what's going on. It also includes a handy fix for Kitty which in my testing works great and makes the text line up properly: https://github.com/githubnext/monaspace/issues/37#issuecomment-1806715309

**Comment by kovidgoyal** [comment]
That's about baseline positioning, the issue I linked to has nothing to
do with baseline positioning.

**Comment by PMunch** [comment]
What do you mean? In their third point they mention that some letters are being placed further down than they are supposed to, which is exactly the same issue that's reported in the Monaspace issue I linked. I have seen this issue myself when using Monaspace in Kitty, and applying the baseline fix from the Monaspace issue has fixed the issue and everything appears normal now, even with bold text.

**Comment by kovidgoyal** [comment]
That just means the glyphs dont fit vertically. The baseline adjustment you posted applies to all glyphs, so if it fixes only osme glyphs then those must not fit in the cell with the unadjusted baseline.

**Comment by PMunch** [comment]
Are you sure? [This comment](https://github.com/githubnext/monaspace/issues/37#issuecomment-1806703496) seems to indicate that it's a common but slightly incorrect way of calculating positions from font metrics which causes the issue.

The way Monaspace rendered in Kitty without the baseline fix is similar to in the screenshot above. Every character sat too high up in the box, apart from characters like 'f' which would then have reached outside the top of it. These characters where slightly shifted down. With the `modify font baseline -2` fix now all the characters move slightly down, except those that where already at this lower level. The effect is bringing them all into line.

I haven't looked at how spacing is calculated in Kitty, but if it uses a similar formula to the one given in the linked issue then it might be worth looking into. Seems like not many traditional Monospace fonts has this parameter set, so Kitty would render those just fine, but then trip over fonts that has that parameter like Monaspace.

**Comment by kovidgoyal** [comment]
Nope, kitty doesn't use that formula. It lets CoreText render two lines
of text and gets the cell height from the output. See the
cell_metrics() function in core_text.m

I dont recall in detail what it does on Linux, IIRC it takes the height
value from freetype and then increases it if the height value is
insufficient to fit the rendered underscore char. See cell_metrics() in
freetype.c for details.

**Comment by PMunch** [comment]
Hmm, looking at `cell_metrics()` in freetype.c I can see [this line](https://github.com/kovidgoyal/kitty/blob/master/kitty/freetype.c#L314C6-L314C14) setting the baseline variable to be just the ascender. If we compare this to the issue I linked:

```
cell_height = ascent + descent + leading
cell_baseline = height - ascent
```

We can see that this also uses just the `ascent` value to calculate the baseline (although it appears to be calculating it from the other side of the character). Their update algorithm adds half of `leading` to the baseline:

```
cell_height = ascent + descent + leading
cell_baseline = height - (ascent + (leading / 2))
```

So if `leading` is typically set to 0 for most monospace fonts these formulas would give the same value. But apparently Monaspace has this as a non-zero value at which point Kittys baseline calculation would diverge.

I tried to apply this to Kitty to see if it would work. And despite doing it in a bit of a hacky way this patch works and renders both fonts I tested with perfectly:

```
diff --git a/kitty/freetype.c b/kitty/freetype.c
index bd028202c..636cfd27f 100644
--- a/kitty/freetype.c
+++ b/kitty/freetype.c
@@ -12,6 +12,7 @@
 #include <structmember.h>
 #include <ft2build.h>
 #include <hb-ft.h>
+#include <hb-ot.h>
 
 #if FREETYPE_MAJOR == 2 && FREETYPE_MINOR < 7
 #define FT_Bitmap_Init FT_Bitmap_New
@@ -311,7 +312,9 @@ cell_metrics(PyObject *s, unsigned int* cell_width, unsigned int* cell_height, u
     Face *self = (Face*)s;
     *cell_width = calc_cell_width(self);
     *cell_height = calc_cell_height(self, true);
-    *baseline = font_units_to_pixels_y(self, self->ascender);
+    hb_font_extents_t extents;
+    hb_ot_layout_get_font_extents(self->harfbuzz_font, HB_DIRECTION_LTR, HB_SCRIPT_COMMON, HB_SCRIPT_COMMON, &extents);
+    *baseline = font_units_to_pixels_y(self, self->ascender + extents.line_gap/2);
     *underline_position = MIN(*cell_height - 1, (unsigned int)font_units_to_pixels_y(self, MAX(0, self->ascender - self->underline_position)));
     *underline_thickness = MAX(1, font_units_to_pixels_y(self, self->underline_thickness));
```

**Comment by kovidgoyal** [comment]
I am not opposed to making that adjustment, with the following provisos:

1) Need to get the leading from freetype not harfbuzz 
2) Need to check at least a few of the most popular monospace fonts to
ensure they actually have zero leading
3) Need to check if leading is included in the freetype height value or
if it needs to be explicity added

If the answer to 3 is yes then 1 should just be self->height -
self->ascender - self->descender (taking into account the freetype
practice of using negative values for some of these).

**Comment by PMunch** [comment]
> Again unless you can get some *commitment* from someone developing some significant terminal program to actually use this, I am not going to spend time on it. I am not even asking for an implementation, just a credible commitment. I have stated I am willing to implement it provided there are likely to exist some programs that will make use of it. Get some commitments from the developers of some such programs and then come back here.

Support for this just landed in [Vim](https://github.com/vim/vim/commit/a606f3ac036e5f3dc313f620e6b4bc00812314f9) as of version 9.1.0030. Is this a big enough terminal program for you to consider it?

**Comment by kovidgoyal** [comment]
Sure, feel free to submit a PR and I can commit to reviewing it.
