### ISSUE TITLE
Dual Themes, One for location and one for remote connections?

### ISSUE THREAD

**Issue by ZerkerEOD** [kovidgoyal/kitty#6806]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to be able to set a theme for the local terminal and then one a remote terminal when using something like kitten ssh.

**Describe alternatives you've considered**
Right now I am changing my theme manually when I need to grab screenshots from the remote host then manually changing it back to the color theme I prefer even though it changes the colors around.

Maybe even assigning a theme to a hokey if that is possible, so that I can quickly change themes even remotely with a hotkey.

**Additional context**
I don't think there is much additional context.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.color_scheme
