### ISSUE TITLE
Inconsistent/incorrect font height

### ISSUE THREAD

**Issue by jeremiah-miller** [kovidgoyal/kitty#6807]
**Describe the bug**
Some bold characters go below the line that others are on in kitty, most notably 'i' and 'f'. I'm using [monaspace neon](https://monaspace.githubnext.com/) font. 

**To Reproduce**
1. Configure kitty to use monaspace neon
2. run a command that outputs bold text
3. some characters will be lower than others, particularly 'i' and 'f'

**Screenshots**
![2023-11-10-16:13:51_screenshot](https://github.com/kovidgoyal/kitty/assets/4341884/36fb6320-ba8d-40bb-9316-6592ae1f0e3d)
![2023-11-10-16:31:12_screenshot](https://github.com/kovidgoyal/kitty/assets/4341884/17183c37-2e88-43eb-a3f3-a82e52e28596)

I copied the text into gedit and libreoffice with the same font to show the comparison

**Environment details**
```
kitty 0.30.1 created by Kovid Goyal
Linux linux 6.5.10-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Thu, 02 Nov 2023 22:02:29 +0000 x86_64
Arch Linux 6.5.10-hardened1-1-hardened (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/dash
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
font_size            20.0
linux_display_server wayland
shell                /usr/bin/fish
Colors:
	background           #f8f8f8   
	color1               #de3d35   
	color10              #3e953a   
	color11              #d2b67b   
	color12              #2f5af3   
	color13              #a00095   
	color14              #3e953a   
	color2               #3e953a   
	color3               #d2b67b   
	color4               #2f5af3   
	color5               #950095   
	color6               #3e953a   
	color7               #bbbbbb   
	color8               #000000   
	color9               #de3d35   
	cursor               #bbbbbb   
	foreground           #2a2b33   
	selection_background #e5e5e6   
	selection_foreground #2a2b33   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/dash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                user
	XCURSOR_SIZE                        36
	LC_TIME                             en_DK.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_VTNR                            1

```

**Additional context**

```
~ $ fc-match monospace
MonaspaceNeon-Regular.otf: "Monaspace Neon" "Regular"
```
with only `font_family      monospace` in the config you can still see the issues, this time primarily with 'f' and 'l'
![2023-11-10-16:34:37_screenshot](https://github.com/kovidgoyal/kitty/assets/4341884/12ab834a-81cc-47c5-8d1e-7b32baf77933)

**Comment by kovidgoyal** [comment]
This will happen when the fonts metrics dont match. In order to fit the
glyph in the cell it will be resized causing baseline alignment
problems. Report the issue to the font if it claims to be a monospace
font it needs to have all glyphs rendered in the same width/height.
Alternately you can use modify_font in kitty.conf to widen the cells so
the bold glyphs fit but at the cost of increasing widespace for all
glyphs.

**Comment by PMunch** [comment]
Found this workaround in the Monaspace issues: https://github.com/githubnext/monaspace/issues/37#issuecomment-1806715309. Seems to work well for me at least.

**Comment by Finii** [comment]
Thanks kovidgoyal, I raised an issue at the font.

**Comment by kovidgoyal** [comment]
Thanks, see also 
https://github.com/kovidgoyal/kitty/issues/6804#issuecomment-1809847328

for how this could potentially be fixed in kitty at least on Linux. But someone needs to do the work. It would indeed be much better if monaspace did not rely on a line gap, like all other monospace fonts out there.
