### ISSUE TITLE
Add a manual page for "kitten"

### ISSUE THREAD

**Issue by Maytha8** [kovidgoyal/kitty#6808]
Hello, I'm one of the co-maintainers for the kitty Debian package.

**Is your feature request related to a problem? Please describe.**
The Debian package for kitty needs to conform to the Debian Policy section 12.1, which states that "each program, utility, and function should have an associated manual page included in the same package or a dependency" and that "if no manual page is available, this is considered as a bug."
It additionally states that "[we] may forward a complaint about a missing man page to the upstream authors."
The tool we use to check our packages against the Debian Policy (called lintian) reported this violation (see output below under 'Additional context')
There is a manual page present for kitty, but no manual page for kitten.

**Describe the solution you'd like**
We would like a manual page for "kitten".

**Describe alternatives you've considered**
- No manual page (violates Debian Policy)
- Symlink kitty man page to kitten man page (but kitten has its own commands, options, etc.)

**Additional context**
Lintian (the tool we use to lint Debian packages), outputs the following error:
```text
N:   Each binary in /usr/bin, /usr/sbin, /bin, /sbin or /usr/games should have a manual page
N:   
N:   Note that though the man program has the capability to check for several program names in the NAMES section, each of these programs should have its own manual page (a
N:   symbolic link to the appropriate manual page is sufficient) because other manual page viewers such as xman or tkman don't support this.
N:   
N:   If the name of the manual page differs from the binary by case, man may be able to find it anyway; however, it is still best practice to match the exact capitalization of
N:   the executable in the manual page.
N:   
N:   If the manual pages are provided by another package on which this package depends, Lintian may not be able to determine that manual pages are available. In this case, after
N:   confirming that all binaries do have manual pages after this package and its dependencies are installed, please add a Lintian override.
N: 
N:   Please refer to Debian Policy Manual section 12.1 for details.
```
Thanks!

**Comment by kovidgoyal** [comment]
This is just pointless busy work. Even if I were to create a man page
for kitten it would just be the same as you can already read using kitten
--help just with worse formatting, because of limitations in groff.
Debian really needs to come up with more sensible policies. 

That said I am not absolutely opposed to doing this, since I know there
are people out there that instinctually type man rather than --help.
But there are far higher priority things for me to be spending my time
on, so patches welcome.

**Comment by Maytha8** [comment]
Thank you!
