### ISSUE TITLE
Split kitty and kitten into separate repos

### ISSUE THREAD

**Issue by Maytha8** [kovidgoyal/kitty#6809]
Hello, I'm one of the co-maintainers for the kitty Debian package.

**Is your feature request related to a problem? Please describe.**
Packaging kitty is a great burden on the package maintainers due to there being two different programming languages to worry about.
We need to ensure that both the Python parts and the Golang parts build without problem, using our own tooling as much as possible.

We've had to patch out the building of "kitten" from setup.py downstream in the Debian packaging and do it manually, since setup.py downloads Go dependencies from the internet, whereas we'd rather Go use the dependencies we've provided as packages. This is the same approach that Fedora has taken when packaging kitty as well, so we're not the only ones doing this. This has caused the package to become very unstable at the moment.

**Describe the solution you'd like**
Both the primary maintainer of the Debian package for kitty and I agree that it would make more sense for kitty and kitten to be split, as they're separate programs and they don't rely on each other's code (due to them being in different languages). Kitty would then become a dependency of kitten.

**Describe alternatives you've considered**
Keeping it the way it is (which will make it harder for packagers to maintain kitty).

**Additional context**
You can have a look at the downstream Debian packaging at https://salsa.debian.org/debian/kitty/-/tree/debian/experimental
You can also find the way Fedora have packaged kitty at https://src.fedoraproject.org/rpms/kitty/tree/rawhide

Thanks!

**Comment by kovidgoyal** [comment]
setup.py does not download anything, it calls go build which will
download packages not already in the go cache. And the go build tool has
excellent support for using local versions of packages, use it.

And yes the Go code depends on the rest of the code so splitting it is
not going to happen.

**Comment by kovidgoyal** [comment]
On Fri, Nov 10, 2023 at 06:56:32PM -0800, Maytham wrote:
> By setup.py downloading dependencies, I meant that `go build` would download dependencies, and for packaging, it's better that the building of the Go components is done separately with our own systems.
> What I mean by this, is that we should be able to build and install "kitten" in a consistent, reproducable manner with `go build` or `go install`, rather than invoking `setup.py`.

You cannot, kitten includes code generated by the kitty executable which
is built by setup.py. 

> 
> > And the go build tool has excellent support for using local versions of packages, use it.
> That's precisely what we have already done.
> 
> Separating the API, kitty, and kitten components would make for much easier maintainability, and result in Debian/Fedora/etc. packages that are of higher quality and much easier and simpler to maintain. If you'd like assistance in this, I'm happy to help.

Maybe see how Arch does it, that way you will be able to maintain a
perfect kitty package with 50 lines of shell script.

**Comment by nileshpatra** [comment]
> Maybe see how Arch does it, that way you will be able to maintain a
perfect kitty package with 50 lines of shell script.

Right. But the packaging standards and requirements in debian and arch are poles apart so that's not something we could do.

If not separate repositories, pushing kitten code to a separate subdirectory and adding in a makefile for building the go part would help us as well.

Thanks for your prompt responses!

**Comment by kovidgoyal** [comment]
On Fri, Nov 10, 2023 at 08:04:34PM -0800, Nilesh Patra wrote:
> > Maybe see how Arch does it, that way you will be able to maintain a
> perfect kitty package with 50 lines of shell script.
> 
> Right. But the packaging standards and requirements in debian and arch are poles apart so that's not something we could do.
> 
> If not separate repositories, pushing kitten code to a separate subdirectory and adding in a makefile for building the go part would help us as well.

Why? Here is how you should be packaging it:

1) Download the Go dependencies to the local go cache or set the env vars to point go build to
use already existing local copies of them

2) Run make

3) Run make test

4) Run make docs

5) Run make linux-package

6) Package up the contents of the linux-package directory however you like into tarballs or debs or whatever debian is using these days
This directory contains everything including docs, terminfo,
shell-integration and the kitten executable. You can split it up however
you like into multiple packages.

Assuming you did (1) correctly there will be no network access.

**Comment by nileshpatra** [comment]
On Fri, Nov 10, 2023 at 08:17:26PM -0800, Kovid Goyal wrote:
> On Fri, Nov 10, 2023 at 08:04:34PM -0800, Nilesh Patra wrote:
> > > Maybe see how Arch does it, that way you will be able to maintain a
> > perfect kitty package with 50 lines of shell script.
> > 
> > Right. But the packaging standards and requirements in debian and arch are poles apart so that's not something we could do.
> > 
> > If not separate repositories, pushing kitten code to a separate subdirectory and adding in a makefile for building the go part would help us as well.
> 
> Why? Here is how you should be packaging it:
> 
> 1) Download the Go dependencies to the local go cache or set the env vars to point go build to
> use already existing local copies of them

I agree with all your points (again). However for this step, we are
using the debian go buildsystem (dh-golang) which has some quirks with
the way kitty buildsystem is structured since the former is equipped to
work with go modules (as it should). dh-golang is needed to both
avoid a lot of manual work at our end, increase package quality and also
inject a couple of useful (packaging) fields at different places. And so
having a different subdir would ease out some of the work - I however
perfectly understand if you do not want to do it.

Maybe we would switch to a different layout going forward if this
continues to be of some real maintenance burden (for us).

BTW, thank you for your prompt responses. I really appreciate them.

**Comment by kovidgoyal** [comment]
On Fri, Nov 10, 2023 at 08:53:02PM -0800, Nilesh Patra wrote:
> On Fri, Nov 10, 2023 at 08:17:26PM -0800, Kovid Goyal wrote:
> > On Fri, Nov 10, 2023 at 08:04:34PM -0800, Nilesh Patra wrote:
> > > > Maybe see how Arch does it, that way you will be able to maintain a
> > > perfect kitty package with 50 lines of shell script.
> > > 
> > > Right. But the packaging standards and requirements in debian and arch are poles apart so that's not something we could do.
> > > 
> > > If not separate repositories, pushing kitten code to a separate subdirectory and adding in a makefile for building the go part would help us as well.
> > 
> > Why? Here is how you should be packaging it:
> > 
> > 1) Download the Go dependencies to the local go cache or set the env vars to point go build to
> > use already existing local copies of them
> 
> I agree with all your points (again). However for this step, we are
> using the debian go buildsystem (dh-golang) which has some quirks with
> the way kitty buildsystem is structured since the former is equipped to
> work with go modules (as it should). dh-golang is needed to both
> avoid a lot of manual work at our end, increase package quality and also
> inject a couple of useful (packaging) fields at different places. And so
> having a different subdir would ease out some of the work - I however
> perfectly understand if you do not want to do it.
> 

I am not willing to restructure code layout to suit Debian, however, if
there is some option I can add to setup.py to help you I am happy to do
so.

I obviously dont know anything about dh-golang but if you can explain 
what the issue is maybe we can arrive at a mututally satisfactory
solution.

> Maybe we would switch to a different layout going forward if this
> continues to be of some real maintenance burden (for us).
> 
> BTW, thank you for your prompt responses. I really appreciate them.

You are most welcome.

**Comment by Maytha8** [comment]
> I am not willing to restructure code layout to suit Debian,

We understand why you don't want to do it, and if we were in your shoes, we wouldn't either.

> however, if there is some option I can add to setup.py to help you I am happy to do so.

Adding an option that would stop the Golang parts (i.e "kitten") from being built would be greatly appreciated, because at the moment we've had to [patch it out](https://salsa.debian.org/debian/kitty/-/blob/4e355f1421f1abcc0b763a33b9a1e6309747b6b7/debian/patches/0003-build-golang-components-with-dh-golang.patch) on our end.

**Comment by kovidgoyal** [comment]
What command are you running when you want this option? As in,

./setup.py what?

**Comment by Maytha8** [comment]
> What command are you running when you want this option? As in,
> 
> ./setup.py what?

./setup.py linux-package

**Comment by Maytha8** [comment]
Thanks for your help! Hopefully we can push the new version of kitty to Debian Unstable soon.
