### ISSUE TITLE
test_fish_integration fails when sudo is not installed

### ISSUE THREAD

**Issue by nileshpatra** [kovidgoyal/kitty#6812]
**Describe the bug**
The test `test_fish_integration` fails if the 'sudo' package is not installed, this is specifically true for container and chroots (which
Debian uses for builds) and chokes with the error:

```
======================================================================
FAIL: test_fish_integration (kitty_tests.shell_integration.ShellIntegration.test_fish_integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/debian/kitty/debian/output/source_dir/kitty/launcher/../../kitty_tests/shell_integration.py", line 183, in test_fish_integration
    self.ae(pty.screen_contents(), q)
    completions_dir = '/builds/debian/kitty/debian/output/source_dir/shell-integration/fish/vendor_completions.d'
    fish_prompt = 'left>'
    pty = <kitty_tests.PTY object at 0x7f699f81f110>
    q = 'left>                                                                     <right'
    right_prompt = '<right'
    self = <kitty_tests.shell_integration.ShellIntegration testMethod=test_fish_integration>
AssertionError: 'type: Could not find \'sudo\'\ntest: Expe[461 chars]ight' != 'left>                                    [35 chars]ight'
- type: Could not find 'sudo'
- test: Expected a combining operator like '-a' at index 5
- -n /builds/debian/kitty/debian/output/source_dir/terminfo -a file =
-                                                                   ^
- Standard input (line 114): 
-         and test -n "$TERMINFO" -a "file" = (type -t sudo)
-             ^
- in function '__ksi_schedule'
- in event handler: handler for generic event 'fish_prompt'
  left>                                                                     <right
```

If a check could be added to set KITTY_SHELL_INTEGRATION to "no-sudo" if sudo is not found in `PATH` that'd be great!
In Debian, I have currently added a [patch](https://salsa.debian.org/debian/kitty/-/blob/debian/experimental/debian/patches/0011-fix-test_fish_integration.patch) to set this to no-sudo for this test by default.

**To Reproduce**
Steps to reproduce the behavior: Run the tests in a chroot without sudo

**Comment by nileshpatra** [comment]
Thank you!

**Comment by HomerSlated** [comment]
In my case I'm using doas instead of sudo.

Is there any way to support both, rather that being hard wired to sudo?

**Comment by kovidgoyal** [comment]
You can write your own doas function similar to the sudo function in
your shell rc files. But does doas even strip the TERMINFO env var?

**Comment by HomerSlated** [comment]
> But does doas even strip the TERMINFO env var?

Yes, unless explicitly told not to, either with the keepenv option, or the more secure setenv option for only specific vars.

https://man.openbsd.org/doas.conf

**Comment by kovidgoyal** [comment]
Well as I said you can make your own function in your shell rc files. I
dont want to do it builtin as it takes space and these files are copied
over ssh by  the ssh kitten. doas is not common enough.

**Comment by symgryph** [comment]
Or you can just create a fake sudo and it works fine.

I just did cd /bin
touch sudo
chmod +x sudo
POOF no more error.
