### ISSUE TITLE
background_opacity not applying contrast changes

### ISSUE THREAD

**Issue by Aqa-Ib** [kovidgoyal/kitty#6815]
**Is your feature request related to a problem? Please describe.**
When changing the background_opacity option between 0 and 1, the window becomes transparent as expected, but also the colors of my wallpaper become "saturated".
Also, note that if background_opacity = 0, no contrast changes are applied. So this happens when opacity is set between 0 and 1, but not 0 or 1.

**Describe the solution you'd like**
background_opacity not applying contrast changes.

**Describe alternatives you've considered**
Maybe move the constrast changes into a separate option. Just removing them from background_opacity would be fine for me too.

**Additional context**
Using kitty on Wayland (Hyprland).
The wallpaper looks like this with background_opacity 0.1:
![20231113_09h39m32s_grim](https://github.com/kovidgoyal/kitty/assets/16420574/eaa57680-5242-4602-9773-19f0642a9e15)

With no contrast (applying compositor transparency, not kitty's):
![20231113_09h45m01s_grim](https://github.com/kovidgoyal/kitty/assets/16420574/d078c12c-18ee-499d-9a2e-2c8078e31c02)

Thank you so much for your attention and for this wonderful terminal.

**Comment by kovidgoyal** [comment]
kitty does not draw that. kitty provides the compositor with a buffer
containing semi transparent pixels after that, how it is blended with
the background is upto the compositor. I can tell you this does not
happen on other wayland compositors. You should report the issue to
hyprland, or more likely there is some config there that can control it.

**Comment by Aqa-Ib** [comment]
I have been investigating the issue and I can reproduce it on Sway and on Plasma+Wayland.
Worth noting is that it is only reproducible using kitty **light** themes. Dark themes do not present this problem at all.

**Comment by kovidgoyal** [comment]
Then you are seeing the result of blending a light color with your
background. Again this blending is not done in kitty, so there is
nothing kitty can do about it. kitty simply passes a buffer with RGBA
pixels of the specified opacity to the compositor.

**Comment by Aqa-Ib** [comment]
kitty treats dark and light themes differently when background_opacity is active. That is a fact, but I do not know why. You can check setting background_opacity to 0.1 and then launching "kitten themes" and navigating in both the dark and light categories. You can see that dark themes do not apply a background color but light themes do apply it indeed.

**Comment by kovidgoyal** [comment]
Again, the blending IS DONE BY THE COMPOSITOR NOT KITTY so kitty cannot
be doing ANYTHING to affect that blending. It simply passes a BUFFER of
RGBA pixels to the compositor. That is how rendering on wayland works.

**Comment by Aqa-Ib** [comment]
I have tried alacritty and konsole and they do not have this problem using the same conditions; the same opacity, the same wallpaper and the same kitten theme within them. I don't know why man, but I like kitty, so in the future I might come with a pull request fixing this. Thank you so much for your attention and for this marvelous terminal. Have a wonderful day.
