### ISSUE TITLE
Middle click pasting very slow

### ISSUE THREAD

**Issue by vimeitor** [kovidgoyal/kitty#682]
Hello,

Pasting with middle click is abnormally slow, at least compared to vte. Pasting something of the order of 1000 lines can very well take 20 seconds or more on my computer. Is there something we can do about it?

(I'm on kitty 0.11.1)

**Comment by kovidgoyal** [comment]
Is that only iddle-click paste or paste from clipboard as well (ctrl+shift+v)

**Comment by vimeitor** [comment]
There's also another issue I have noticed with pasting: quite often, kitty won't let me paste anything with middle click right after opening it for the first time unless I click somewhere with text (that could either be the prompt or some text I just typed or the cursor). As soon as I'm able to paste, this issue never happens again with the current kitty instance; that is, then I'm able to click anywhere in the terminal and I can paste anything.

**Comment by erf** [comment]
Pasting 104 lines of "hello world" into the command line or `vim` causes it to freeze on my mac ( 0.11.1 ).

On a side note it does work when pasting into [vis](https://github.com/martanne/vis)
