### ISSUE TITLE
Automatic add alias of `ls` when using kitten ssh

### ISSUE THREAD

**Issue by kuba3351** [kovidgoyal/kitty#6822]
**Is your feature request related to a problem? Please describe.**
Kitten ssh has a nice feature that allows of download and edit files on a remote host when using `ls` with `--hyperlink=always` parameter. I think it should be nice if kitten ssh will automatic alias `ls` to `ls --hyperlink=auto` on a remote machine. Then I will not have to remember to add this parameter when I would like to use this feature.

**Comment by kovidgoyal** [comment]
I dont think changing how basic tools like ls work automatically is a
good thing, too much potential for breakage. Note that the ssh kitten
cam copy over your  shell config automatically (see the docs) so all
your aliases and any other config can be made available on the remote
automatically.
