### ISSUE TITLE
Query cell size by pixels

### ISSUE THREAD

**Issue by Notarin** [kovidgoyal/kitty#6825]
Good morning,
I am developing an application that will use the kitty graphics protocol to display an image with said application, however, it is important that the image is constrained within a sectioned off area of cells, in order to do this my approach is to find the cell size and multiply by the known width and height of the section that I plan to place my graphic, and place said image within the area.

Kitty is pretty reliable when it comes to introducing standards and protocols, and I think it would be well suited within its definition of a standard to introduce some method of querying a cell size in pixels. To my understanding there are usually methods to query window size and cell columns, but I struggle to find a method of querying the cell height, which is required. As well as it being a pain to do so, usually this can be inaccurate at times with padding, decorations, etc.

I wouldn't be closed minded if it came down to some other solution that may be more complicated in nature if it was overall simpler in the sense it would be scalable to including more information. But I don't see much variance in my ideal solution besides the method of retrieving such information. I would prefer memory safe options so shared memory and the such are definitely methods I would like to avoid; I would also like to avoid relying on some method of piping out to STDOUT and reading from STDIN, but if that's the most consistent and cleancut approach I would not complain.

If I've made some fundamental misunderstanding or have missed a preferable method to accomplish my task, please inform me as I would really appreciate it.

**Comment by kovidgoyal** [comment]
Get the window size as described here:
https://sw.kovidgoyal.net/kitty/graphics-protocol/#getting-the-window-size

Divide the window size by the number fo cells to get the cell size in
pixels.

**Comment by Notarin** [comment]
I have been bashing my skull against the brick wall over this problem for two days now, I am convinced this is not possible without unsafe code, I am truly at my wits end.

**Comment by kovidgoyal** [comment]
What does unsafe code mean? You can query the ioctl from *any* language including "safe" ones other than shell script. And to use it in shell script, you dont need to rely on the kitty binary, you rely on the kitten binary which is statically conpiled and write in a "safe" language, namely Go. And if you really want to do it in pure bash you could *probably* manage using the escape code to query the size as documented at that link.

**Comment by Notarin** [comment]
I'm not very sure how to explain what safe vs unsafe code is as its not really a surface level topic I'd be comfortable explaining over a github issue, but I can reference the documentation.
https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html
also, I don't plan to do this in bash, I don't think i have, but if I've given the impression I am sorry about that.
> you dont need to rely on the kitty binary, you rely on the kitten binary which is statically compiled and write in a "safe" language, namely Go

what? "you dont need to rely on the kitty binary, you rely on the kitten binary" huh? I am not sure if this was a mistake or conveying some point I don't get. Also, the reason I am wary of relying on the kitty binary, is not because I have some aversion to kitty, but rather I dont want to declare kitty as a dependency of the app, as well as it only working on the kitty terminal too.
> And if you really want to do it in pure bash

I uh.... I don't

I plan on seeing how the escape code method works

**Comment by kovidgoyal** [comment]
Yeah you cant do it efficiently in "safe" rust. If you want to use
"safe" rust, use the escape code method, but be aware that doing that is
both potentially a million times slower (depends on the speed of the
network between your program and the terminal) and much more fiddly
since if you want to parse responses from the terminal robustly you need
a full escape code sequence parser and you have to deal with
asynchronicity issues, the terminal could send you keypresses or other
events while you are waiting for a response.

Not to mention that this is not actually safe, since your "safe" I/O
calls to read/write to the terminal that the rust runtime provides are
backed by unsafe I/O underneath that rust just hides from you.  So just
use https://docs.rs/nix/latest/nix/sys/ioctl/index.html to do the ioctl
which provides you with the same illusion of "safety" as the regular
read()/write() you think is "safe".

"safe" rust is basically a layer of bird shit on top of a skyscraper of "unsafe" code.

**Comment by Notarin** [comment]
> "safe" rust is basically a layer of bird shit on top of a skyscraper of "unsafe" code.

This is actually so true lmao, but the model works lol
also, to be fair, the "illusion" of safety is more of a trust of safety, you trust that those who used the unsafe code are not morons.

> use https://docs.rs/nix/latest/nix/sys/ioctl/index.html

Thank you, every method of performing this under the nix crate I've found so far required using unsafe, so if this works out you've done a huge favor to me

I'm not super adverse to unsafe code and am aware that literally all safe code is unsafe when you dig deep enough, but it was a goal of the project to not use the unsafe keyword, and I've gotten quite far and would've been really disappointing if I had to fail that goal after this much progress,

**Comment by Notarin** [comment]
> So just
use https://docs.rs/nix/latest/nix/sys/ioctl/index.html to do the ioctl
which provides you with the same illusion of "safety" as the regular
read()/write() you think is "safe".

@kovidgoyal This unfortunately still requires an unsafe block, as much as it pains me, I think I'll just have to scrap this goal.

**Comment by kovidgoyal** [comment]
I dont really understand your goal. What earthly difference does it make
if the unsafe block is in your code or in a library your code uses? If
its so important to you that there is no unsafe in your app, make a
crate that does the unsafe bit and provides a "safe" wrapper for it
and use it in your app. Every bit of safe I/O in your app is already
using unsafe code from some crate or stdlib. Using an ioctl to do I/O
with the kernel is no different.

**Comment by Notarin** [comment]
it was really just a simple goal in the beginning, I just wanted to see if I could make the project without unsafe code, the problem is that I've gone this long without breaking that, I've managed to find ways to do things without using explicit unsafe code and have put forth a lot of effort to do so, mainly because its a goal that's survived this long.
aamof, the very first line of code in the project is:
```rust
#![forbid(unsafe_code)]
```
And yes, I know literally everything is unsafe if you dig deep enough, as I have made clear many times now.
But its less of a technical requirement and more of a personal preference due to my sunken cost.

But alas, I have caved and just removed the goal.

wait- dear god, I just realized I have misread something important
"you dont need to rely on the kitty binary, you rely on the kitten binary"........ dear lord I cannot read, I might be able to reinstate the goal
