### ISSUE TITLE
br can't be launched in a kitty startup session

### ISSUE THREAD

**Issue by Schweber** [kovidgoyal/kitty#6826]
**Describe the bug**
I would like to define a [kitty startup session](https://sw.kovidgoyal.net/kitty/overview/#startup-sessions) that launches `br` (launches [broot](https://github.com/Canop/broot) with improved shell capabilities) on startup. However, if i add `launch br` then kitty fails with 
```
Failed to launch child: br
With error: No such file or directory
Press Enter or Esc to exit
```
If i add `launch broot` it works but then i can't use `:cd` etc. After the window is open i can run `br` and it works as usual but that's not what i'm trying to achieve.

**To Reproduce**
1. install `broot` and its `br` shell improvement
2. add `launch br` to a kitty startup session and execute it
3. See error

**Environment details**
I can't press Ctrl+Shift+F6 on my current keyboard setup and `kitty --debug-config` yields `Unknown option: --debug-config`.

**Additional context**
Same error occurs with `kitty --config NONE`. I am using kitty 0.31.0 on NixOS.
https://github.com/Canop/broot/issues/797

**Comment by kovidgoyal** [comment]
launch runs *programs* not shell aliases. If you want to run a shell
alias, run something like

launch bash -il -c "br"

You will need to adjust the options to bash or whatever shell you use to
make sure it sources whatever files the alias is defined in.

**Comment by Schweber** [comment]
I see, thank you!

**Comment by Schweber** [comment]
With `launch fish -c br` it is started as intended but if i close `broot`, the kitty window is closed as well (it should return to the shell).

However, if i create a `new_window` in this kitty startup session, `broot` works fine in the new window. So the window created by the startup session will still close when i close `broot` but the one i created with `new_window` can run `broot` fine and will stay open when i close `broot` in it. So i can have two kitty windows in the same OS window that behave differently.

@kovidgoyal Do you have an idea why that happens?

**Comment by Schweber** [comment]
@kovidgoyal I tried that but it makes no difference. I launch kitty with `kitty -1 --class kitty_code --hold --session ~/Programmieren/kitty-session.conf`. In `kitty-session.conf` there is only
```
cd ~/Programmieren
launch fish -ilc br
```

I then get a kitty window with `broot` running in ~/Programmieren. So far so good.

But if i then exit `broot`, the kitty window is closed as well. This is not what i want/expect because if i run `br` manually from a shell (bash or fish or nushell, doesn't matter) and then close `broot`, i'm back at the shell prompt and i don't have to use `--hold` for that. 

The strange thing is the part that i described in my previous post:

> However, if i create a `new_window` in this kitty startup session, `broot` works fine in the new window. So the window created by the startup session will still close when i close `broot` but the one i created with `new_window` _in this startup session_ can run `broot` fine and will stay open when i close `broot` in it. So i can have two kitty windows in the same OS window that behave differently.

So this new window stays open and `--hold` is not needed. I don't understand this behaviour.

**Comment by kovidgoyal** [comment]
launch --hold fish -ilc br

**Comment by Schweber** [comment]
That works, thank you for helping me!
