### ISSUE TITLE
iterm2 like Triggers

### ISSUE THREAD

**Issue by dufferzafar** [kovidgoyal/kitty#683]
Is it possible to take __automatic__ action based on some text matching a regex?

iterm2 calls it Triggers: https://www.iterm2.com/documentation-triggers.html

This is different from the hints kitten because that is manual as it requires pressing a key to go into hints mode etc.

Triggers I use (on iTerm2) and would love to use in Kitty as well:

- Highlight Text: The text matching the regex in the trigger will change color (which is user defined.) 
- Run Command: Run a user-defined command.

**Comment by kovidgoyal** [comment]
No, this seems like a big performance killer. The terminal would have to continuously run the regexes over all input on every byte received. Not a good design IMO. What do you actually want to do? Seems like a much better way to do it would be to simply pipe the output of the command you want to monitor into a script and have it scan for regex and do whatever action you like.

**Comment by dufferzafar** [comment]
TIL about Supercat: http://supercat.nosredna.net/index.html 

Which can colorize text based on regexes (exactly follows the approach suggested by kovid.)

**Comment by liebkne** [comment]
@dufferzafar How can I setup `supercat` to apply to every command line outputs like iTerm2 without piping manually?

**Comment by regular** [comment]
> No, this seems like a big performance killer. The terminal would have to continuously run the regexes over all input on every byte received. Not a good design IMO. What do you actually want to do? Seems like a much better way to do it would be to simply pipe the output of the command you want to monitor into a script and have it scan for regex and do whatever action you like.

Well, you have to do that anyway in order to implement ANSI escape sequences, right? So maybe this wouldn't add that much overhead if implemented as user-defined escape sequences? I'd find that feature pretty useful.

**Comment by kovidgoyal** [comment]
On Wed, Aug 21, 2024 at 04:45:59AM -0700, Jan Bölsche wrote:
> > No, this seems like a big performance killer. The terminal would have to continuously run the regexes over all input on every byte received. Not a good design IMO. What do you actually want to do? Seems like a much better way to do it would be to simply pipe the output of the command you want to monitor into a script and have it scan for regex and do whatever action you like.
>
> Well, you have to do that anyway in order to implement ANSI escape sequences, right? So maybe this wouldn't add that much overhead if implemented as user-defined escape sequences? I'd find that feature pretty useful.

Escape sequences are not parsed by regex.

**Comment by regular** [comment]
My mistake. What I meant to say: For many use cases a match against a simple byte sequence (i.e. not regex), like you have to do for escape sequences anyway, would probably be sufficient, and might not add much of a performance penalty. You could even require those sequences to begin with ASCII 27, then your fast path wouldn't be impacted at all. (this would reduce the number of uses cases though, obviously)

My personal use case by the way: adding some magic bytes to the shell prompt that would trigger changing kitty's color scheme. This would make different contexts (such as being ssh'ed into a remote machine, nix develop shell, etc.) very obvious. Just a thought.

**Comment by kovidgoyal** [comment]
use the ssh kitten to change colors on remote hosts
https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.color_scheme

Or if you prefer to put something in your shell prompt put the actual
escape codes to change colors. See https://sw.kovidgoyal.net/kitty/faq/#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by regular** [comment]
Oh, I wasn't aware that there is a sequence that would change the background color of the _entire screen_. This is actually very useful for my particular use-case. 

For reference:

> Change the default background color:
> $ printf '\x1b]11;blue\x1b\\'

Thanks for the quick response!
