### ISSUE TITLE
Trying to use vim shortcuts with an spanish keyboard layout.

### ISSUE THREAD

**Issue by JosemaGIT** [kovidgoyal/kitty#6836]
**Describe the bug**
I am trying to use the vim shortcut ctrl+] that lets me jump to subject. The thing is that I am currently using a macbook air, with an spanish layout. That means that for that combination of keys I need to press: ctrl+option+'+'.

The thing is that vim doesn't detect that key combination as ctrl+]. I have tried the same in another terminal and it works so I assumed that it had to do with kitty.

**To Reproduce**
1. Configure your keyboard layout to be spanish.
2. Try to use the shortcut ctrl+] with Vim.
3. See that it doesn't work.

** The configuration is barebones kitty and barebones vim.

**Comment by kovidgoyal** [comment]
That will be an issue with vim's implementation of the kitty ketboard
protocol. Report it there.
