### ISSUE TITLE
Add a way to reload the configuration

### ISSUE THREAD

**Issue by Risto-Stevcev** [kovidgoyal/kitty#684]
Use case is to reload the config without closing the terminal in order to avoid losing work

**Comment by kovidgoyal** [comment]
Not going to happen. If you want to change colors you can do that already using one of the many ways documented in the FAQ. Similarly you can change font sizes using key bindings. If there is some particular config setting(s) yo want to change you can ask for a mechanism to do that, but general config reloading is way too much work given how configurable kitty is.

**Comment by Risto-Stevcev** [comment]
@kovidgoyal Sorry I should've probably mentioned why I'm looking for this. Specifically it's just to change the font size on the fly. Same use case as in the browser, ie: If you're looking at a different monitor further away or text that isn't particularly wide you can increase the font to avoid eye strain and then decrease it later without losing your current workspace/session

**Comment by SolitudeSF** [comment]
```
map kitty_mod+equal    change_font_size all +2.0
map kitty_mod+minus    change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
# map kitty_mod+f6     change_font_size all 10.0
# map kitty_mod+f6     change_font_size current 10.0
```

**Comment by Risto-Stevcev** [comment]
Ah thanks @SolitudeSF :slightly_smiling_face:
