### ISSUE TITLE
Add kitten_pager for more pager customisability

### ISSUE THREAD

**Issue by jackielii** [kovidgoyal/kitty#6843]
**Is your feature request related to a problem? Please describe.**

Just switched from tmux to kitty for window management. I use a few things from tmux that I miss:

1. enter pager mode and select something to paste directly to current prompt
2. enter search mode and search and paste directly

I find that pager solutions in kitty are flexible, yet lacking in certain areas:

The good things:
1. ability to scroll to previous command thannks to shell integration, which I love, tmux doesn't have it.
2. ability to bring back previous visited output.

The bits I miss from tmux and the best solutions out there for kitty in various places
1. [kitty+page.lua](https://gist.github.com/galaxia4Eva/9e91c4f275554b4bd844b6feece16b3d) changes the `scrollback_pager` option so it's used in all places where pager is used, e.g. `show_last_visited_command_output`, `show_first_command_output_on_screen`. However, I can't easily control how to paste directly after I select something in nvim.
2. [kitty-scrollback.nvim](https://github.com/mikesmithgh/kitty-scrollback.nvim/) seems to be the best solutions out there with lots of featurs. However, it doesn't use the `scrollback_pager`, so for every place where `scrollback_pager` is used, I need to configure it to use a special command using mapping or script.

I wish there is a solution that works everywhere and is as flexible as a custom kitten.

**Describe the solution you'd like**

A quick browse of the source code, I can see [function display_scrollback in boss.py](https://github.com/kovidgoyal/kitty/blob/master/kitty/boss.py#L1773) is used as everywhere. E.g. by various commands `show_first_command_output_on_screen`, `show_last_visited_command_output` etc to display pager. It's also used by custom kittens (e.g. [kitty_config](https://github.com/ershov/kitty_config)) to display pager using `boss.display_scrollback()`

My proposed solution is to add a config called `kitten_pager` that hijacks `boss.display_scrollback()` to use the custom kitten instead of using a command

**Describe alternatives you've considered**

- kitty+page.lua 
- kitty-scrollback.nvim

**Additional context**

**Comment by kovidgoyal** [comment]
I'm not keen on adding another option for this. There are only a handful
of things you have to remap, 4-5 at best. So I don't think adding
mappings for them is such a burden. ctrl+shift+h, ctrl_shift+g and the
mouse right click map are about all I can think off. Three lines in
kitty.conf. And you can use action_alias to avoid redundancy in those
maps. See the sample kitty.conf in the nvim scrollback plugin docs.

If there's a whole bunch of them I am overlooking, feel free to let me know.

**Comment by jackielii** [comment]
@kovidgoyal thanks for your reply.

I'm currently mapping:

1. show_scrollback
2. show_last_visited_command_output
3. show_last_non_empty_command_output
4. show_last_command_output
5. show_first_command_output_on_screen

I agree it's only 5 mappings. However for other kittens that invokes `boss.display_scrollback()` (e.g. in [kitty_config](https://github.com/ershov/kitty_config) custom kitten and probably others), I have to fork the kitten in order to get the functionality I want.

A pager using custom kitten also allows the user to implement single key to paste. i.e.:

1. enter pager mode in a overlay window
2. make a selection
3. yank selection to clipboard
4. send text to parent window
5. exit pager mode

In addition, IMHO, this makes writing a custom pager much easier as one can detect the text and manipulate the behaviour much easier with the kitten API.

**Comment by kovidgoyal** [comment]
On Thu, Nov 23, 2023 at 07:27:28AM -0800, Jackie Li wrote:
> @kovidgoyal thanks for your reply.
> 
> I'm currently mapping:
> 
> 1. show_scrollback
> 2. show_last_visited_command_output
> 3. show_last_non_empty_command_output
> 4. show_last_command_output
> 5. show_first_command_output_on_screen
> 
> I agree it's only 5 mappings. However for other kittens that invokes `boss.display_scrollback()` (e.g. in [kitty_config](https://github.com/ershov/kitty_config) custom kitten and probably others), I have to fork the kitten in order to get the functionality I want.

That would be an argument for adding config to that kitten.

> 
> A pager using custom kitten also allows the user to implement single key to paste. i.e.:
> 
> 1. enter pager mode in a overlay window
> 2. make a selection
> 3. yank selection to clipboard
> 4. send text to parent window
> 5. exit pager mode

This is nothing specific to a kitten, an ordinary pager program can do
so as well, one just has to enable remote control for it. 

> 
> In addition, IMHO, this makes writing a custom pager much easier as one can detect the text and manipulate the behaviour much easier with the kitten API.

What kitten API? If you mean remote control, this is again useable in
any pager program not just in a kitten. The actual kitten API only
happens after the kitten quits and control returns to kitty.

**Comment by jackielii** [comment]
> This is nothing specific to a kitten, an ordinary pager program can do so as well, one just has to enable remote control for it.

You're right! This was my main argument of having a custom kitty for the pager.

So there only leaves one argument which is 

> However for other kittens that invokes `boss.display_scrollback()` (e.g. in [kitty_config](https://github.com/ershov/kitty_config) custom kitten and probably others), I have to fork the kitten in order to get the functionality I want.

This is not a deal breaker. Most of my use cases are covered by your point. Thanks again!

**Comment by jackielii** [comment]
Thinking on it again, even the `boss.display_scrollback()` can be covered by your comment:

> This is nothing specific to a kitten, an ordinary pager program can do so as well, one just has to enable remote control for it.

**Comment by kovidgoyal** [comment]
Yes, basically using a kitten for this is a red herring, one could just
write a normal program achieve all the same features with using remote
control.
