### ISSUE TITLE
Changes in config do not seem to take effect

### ISSUE THREAD

**Issue by ejheil** [kovidgoyal/kitty#6846]
**Describe the bug**
I've made changes in my kitty.conf using the prescribed mechanism (control-shift-f2) and I do not see them reflected in kitty

**To Reproduce**
1. Install kitty (in this case on MacOS Sonoma on M2 macbook air, though I have seen the same effect on Linux)
2. Edit config file using control-shift-f2.  Uncomment "shell_integration enabled" and "allow_hyperlinks yes"
3. Reload conf and/or completely quit (command-q) and restart kitty
4. View config debug: notice that no config options appear to have been set:

```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin Eds-MacBook-Air.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 ar>
ProductName:            macOS ProductVersion:           14.1.1 BuildVersion:            23B81
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ed/.config/kitty/kitty.conf

Config options different from defaults:

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                ed

```
KITTY_SHELL_INTEGRATION has not been set:

```
➜  ~ set | grep KITTY
KITTY_INSTALLATION_DIR=/Applications/kitty.app/Contents/Resources/kitty
KITTY_PID=52583
KITTY_PUBLIC_KEY='1:#3W`MTG{0}^LP9l2!AYO4=~J+VmSzcZP{@s+MWFi'
KITTY_WINDOW_ID=1
```
**Environment details**
```
see above
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Running kitty --config NONE differs from the above config only in that it has a full PATH (what's up with that?) and doesn't have a "Loaded config files: /Users/ed/.config/kitty/kitty.conf"

```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin Eds-MacBook-Air.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 ar>
ProductName:            macOS ProductVersion:           14.1.1 BuildVersion:            23B81
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
        PATH                                /Users/ed/.rbenv/shims:/Users/ed/bin:/usr/local/bin:/Users/ed/Library/Python/3.9/bin:/Applicatio>
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                ed


```

I've seen the same thing on a Linux machine (Debian, using a downloaded kitty, not the debian repo kitty which is rather old).

**Comment by kovidgoyal** [comment]
Uncommenting default values is going to have no effect since they are
*already set* to that value. Debug config shows you settings *different*
from the defaults.

**Comment by ejheil** [comment]
Sorry, I guess I'm confused -- I saw that the KITTEN_SHELL_INTEGRATION variable had not been set, and so I assumed shell integration wasn't happening successfully?

**Comment by kovidgoyal** [comment]
KITTY_SHELL_INTEGRATION is unset automatically after being read. It is
an internal kitty implementation detail.

**Comment by ejheil** [comment]
Thank you!
