### ISSUE TITLE
Build Target: Windows

### ISSUE THREAD

**Issue by geraldsnm** [kovidgoyal/kitty#6850]
**Is your feature request related to a problem? Please describe.**

Perhaps there is a problem, it's unclear who's running the site that does have (outdated) binaries of kitty for windows.

**Describe the solution you'd like**

Can you please clarify if the author of this software is running the download page available here which hosts windows binaries:

https://www.9bis.net/kitty/#!index.md

the above site links to this fosshub URL that has an outdated release:

https://www.fosshub.com/KiTTY.html

this is concerning because it's different than the URL provided here on the main project page (https://sw.kovidgoyal.net/kitty) and I think the community needs clarity whether or not the person(s) running the site with release of the windows distribution is related to the owner of this project. 

**Describe alternatives you've considered**

If both sites are run by the same person, would it be too much to ask to get windows binaries that are up to date ?

**Comment by kovidgoyal** [comment]
That's a different kitty. https://github.com/cyd01/KiTTY
