### ISSUE TITLE
[Question] Distinguishing second copy of kitty?

### ISSUE THREAD

**Issue by nicoandmee** [kovidgoyal/kitty#6854]
Is there a way to build a second copy of kitty from source, and distinguish it in some way such that some applescript can communicate with it like this?

```applescript
tell application "${appName}"
	activate
end tell
```

My use case is I am using a macOS window manager and I want kitty to work as a dropdown quake window, whilst leaving my "non-quake" windows alone. I tried many different solutions from hammerspoon to skhd but the best would be just to have a special kitty that responds to the quake shortcut. 

thanks!

**Comment by kovidgoyal** [comment]
You can build kitty however many times you like. As for distinguishing it, no idea,
probably try changing the entries in Info.plist in the built kitty.
