### ISSUE TITLE
transparent background in inverted ascii

### ISSUE THREAD

**Issue by mil-ad** [kovidgoyal/kitty#6858]
I was playing around with [oh-my-posh](https://ohmyposh.dev/) shell prompts. They seem be to using inverted ascii to swap background/foreground for the usual powerline  character but this doesn't seem to be supported in Kitty:

![image](https://github.com/kovidgoyal/kitty/assets/686449/a7db68f1-811d-468b-bec8-b043ab2be675)

I think the leading  is supposed to be rendered inverted i.e. foreground should be transparent and background should be the normal foreground. I raised [an issue](https://github.com/JanDeDobbeleer/oh-my-posh/issues/4490) but they think it's something that must be supported in the terminal program.

**Comment by JanDeDobbeleer** [comment]
> they think

We know :-)

Rendering is always a terminal's responsibility. We print `\x1b[0m\x1b[0;32;49m\x1b[7mhello\x1b[27m` which inverts the ANSI sequence (transparent hello in a yellow background). When the foreground is set but the background isn't, this will create transparent text with the background as the current foreground.

**Comment by mil-ad** [comment]
🫡 Thanks for the clear explanation @JanDeDobbeleer !

**Comment by JanDeDobbeleer** [comment]
@mil-ad I found out that most terminals don't allow setting a transparent background, but rather have the window set transparent. This will still print black triangles when the background color is set to black. I don't see a way around that either as omitting the default background color (49) makes the foreground incorrect on all terminals.

**Comment by mil-ad** [comment]
That was a good test: 

![image](https://github.com/kovidgoyal/kitty/assets/686449/4912706a-720a-4cf5-86d4-777bcff68ac7)

**Comment by kovidgoyal** [comment]
See the docs for the background_opacity setting in kitty.  Any background color that matches (has the same value as) *the default background color* will be rendered transparent. Any other background color will not. Reverse video is explicitly not transparent as reverse video is usually used to emphasize something, make it stand out. If you want background color to be transparent make sure it is not using reverse video and that the value of the background color matches the default background color.
