### ISSUE TITLE
Image resolution reduced when fixing `Error opening terminal: xterm-kitty.`

### ISSUE THREAD

**Issue by thisismygitrepo** [kovidgoyal/kitty#6862]
**Describe the bug**
I'm displaying images using `viu` & `chafa` inside `kitty`. Both worked great until suddenly they started producing highly pixelated low resolution images.

I realized that this happened when I followed the solutions provide for `Error opening terminal: xterm-kitty.` problem by settings `TERM=xterm`.

I'm in a dilemma.

**Comment by kovidgoyal** [comment]
Never change TERM you will break all sorts of things. The solution for
unknown terminal is in the FAQ, and it is *not* changing the value of
TERM.
