### ISSUE TITLE
Phantom mouse selection

### ISSUE THREAD

**Issue by trapgate** [kovidgoyal/kitty#6863]
**Describe the bug**
Occasionally, when I'm moving the mouse over a kitty window, it'll create a selection in that window as if the left mouse button were held down when it is not. The starting point for the selection seems to always be the last cell that was clicked in that window.

**To Reproduce**
I've been trying for ages to find a way to reliably reproduce this behavior, but I haven't succeeded. I experience it many times a day, but I can't quite get it to happen on demand.

1. It seems to be necessary to have kitty displaying multiple windows for this to happen. I don't mean window manager windows - I usually have only one kitty window open in my WM. I typically have two kitty windows stacked vertically in a layout, but I've seen this happen with > 2 windows in other kitty layouts also. It doesn't seem to happen when kitty is displaying a single window.
2. I also have multiple monitors, and it may be that this is required too.
3. I've run into this on both gnome and kde, using both X and Wayland. My current setup is kde on Wayland. I've also seen it on both Ubuntu and Arch.
4. When the problem happens, it's as if the left mouse button is held down in the affected window - the selection will expand and contract as you move the mouse over the window, and moving past the top or bottom of the screen will trigger scrolling to expand the selection. Other kitty windows are unaffected. 

**Screenshots**
This is probably not super helpful, but here's a screencast of the problem in action. Yes, it looks like the left mouse button is held down to produce this, but it's not. This is triggered simply by moving the mouse over the window without touching any buttons.

[Screencast_20231127_165309-1.webm](https://github.com/kovidgoyal/kitty/assets/32468/894a8ced-3d80-4292-a748-c394b8a68dec)

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux leopard 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64
Arch Linux 6.6.2-arch1-1 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/fish
Loaded config files:
  /home/geoff/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select          clipboard
font_family             FiraCode-Retina
touch_scroll_multiplier 5.0

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/geoff/bin:/home/geoff/.local/bin:/home/geoff/go/bin:/home/geoff/mygo/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nvim
	SHELL                               /bin/fish
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                geoff
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     /home/geoff/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/geoff/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1

```

**Additional context**
I can reproduce this with `kitty --config NONE`.

I did find some mention of this bug on reddit from a couple of years ago - search for "kitty phantom mouse selection" and you should find it.

**Comment by kovidgoyal** [comment]
Without a reproducer there isn't anything I can do to help.

You can try running kitty as

kitty --debug-input

That shows you the list of input events kitty gets and how they are
handled. Keeping watch on those when this happens might throw some light
on the issue. Post the events from the log when you reproduce the issue and I will see
if it tells me anything useful.

**Comment by trapgate** [comment]
Thanks for the suggestion, I've been running kitty with --debug-input. Interestingly that seems to make the problem happen less often, but I still experience it many times a day. I've never seen it happen in a single-kitty window, and I haven't seen it happen in the first window of a multi-kitty layout either.

I've attached the shortest output I've collected so far. If you filter out all the moves and just look at mouse presses and releases, you'll get this:

```
$ cat ~/kitty-input-9.txt | grep 'Press\|Release\|on_mouse' 
Press mouse_button: 0 mods: none grabbed: 0
on_mouse_input: press button: left mods: none grabbed: 0 handled_in_kitty: 1
Release mouse_button: 0 mods: none grabbed: 0
on_mouse_input: release button: left mods: none grabbed: 0 handled_in_kitty: 0
on_mouse_input: click button: left mods: none grabbed: 0 handled_in_kitty: 1
Press mouse_button: 0 mods: none grabbed: 0
on_mouse_input: press button: left mods: none grabbed: 0 handled_in_kitty: 1
Release mouse_button: 0 mods: none handled as drag end
on_mouse_input: click button: left mods: none grabbed: 0 handled_in_kitty: 1
```

The first press of the mouse button is the phantom. I never hit that button. The second mouse button is real, and is me ending the selection started by the phantom mouse event.

Here's another example with the moves filtered out:

```
on_mouse_input: press button: left mods: none grabbed: 0 handled_in_kitty: 1
text-input: done event: serial: 38 current_commit_serial: 40
text-input: done event: serial: 39 current_commit_serial: 40
text-input: done event: serial: 40 current_commit_serial: 40
Release mouse_button: 0 mods: none handled as drag end
bbed: 0
Press mouse_button: 0 mods: none grabbed: 0
on_mouse_input: press button: left mods: none grabbed: 0 handled_in_kitty: 1
Release mouse_button: 0 mods: none handled as drag end
 grabbed: 0
Press mouse_button: 0 mods: none grabbed: 0
on_mouse_input: press button: leftMouseEvent matched action: mouse_handle_click
 mods: none grabbed: 0 handled_in_kitty: 1
Release mouse_button: 0 mods: none handled as drag end
on_mouse_input: click button: left mods: none grabbed: 0 handled_in_kitty: 1
```

In this case the phantom is the last line. That happened as I was moving the mouse from the upper pane of my two-window kitty layout.
 
[kitty-input-9.txt](https://github.com/kovidgoyal/kitty/files/13654033/kitty-input-9.txt)

**Comment by kovidgoyal** [comment]
That indicates your system is sending the events to kitty, there's not anything kitty can do here. The Press ... line comes from mouse_event() which is called from mouse_button_callback() which is called by glfw via window system events.

**Comment by kovidgoyal** [comment]
That indicates your system is sending the events to kitty, there's not anything kitty can do here. The Press ... line comes from mouse_event() which is called from 
mouse_button_callback() which is called by glfw via window system events.

**Comment by trapgate** [comment]
Just a quick note for anyone else who might run into this: this continued to be a problem until sometime in August or September, then it stopped happening and has not recurred. I made no major config changes to the system, so I'd guess this was a bug somewhere in one of the input layers in the system that got fixed.
