### ISSUE TITLE
Rendering multi-cell-wide characters changes how other characters are rendered for some fonts

### ISSUE THREAD

**Issue by mkalinski** [kovidgoyal/kitty#6865]
**Describe the bug**

Some characters that normally behave as 1-cell-wide start behaving as multi-cell-wide if they are rendered after another multi-cell-wide character is rendered first.

By this, I mean rendered anywhere at all since the kitty instance was started, not necessarily adjacent.

I would expect characters to always be rendered with the same width property, given the same font.

This happens in several fonts. I'm using Source Code Pro in this report, because it seems the most mainstream (comes preinstalled with Fedora Linux, for example), and doesn't have any ligatures.

**To Reproduce**

1. Open a kitty instance with the minimal config.
2. Type character `✚` (U+271A, Heavy Greek Cross).
3. The cross character behaves like a 1-cell-wide character. It will continue to behave like this in this kitty instance.
4. Open another kitty instance with the minimal config.
5. Type character `🗔` (U+1F5D4, Desktop Window). This is just an example, this seems to happen with all characters that are always multi-cell-wide.
6. Type character `✚` (U+271A, Heavy Greek Cross).
7. The cross character now behaves like a multi-cell-wide character. It does not fit inside a single cell, and is clipped if another character is typed beside it.

**Screenshots**

![image](https://github.com/kovidgoyal/kitty/assets/959502/7a457d60-9af7-4b70-8594-361ff020d88d)
The cross is rendered as a single-cell character. Typing a multi-cell character doesn't retroactively change this.

![image](https://github.com/kovidgoyal/kitty/assets/959502/b1c068dc-7feb-4285-ba65-850198efcc53)
If the multi-cell character is typed before the cross character appears, the cross will become and remain a multi-cell character.

**Environment details**

```
kitty 0.31.0 created by Kovid Goyal
Linux fedora 6.5.12-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023 x86_64
S
Kernel 6.5.12-300.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  minikitty.conf

Config options different from defaults:
font_family Source Code Pro

Important environment variables seen by the kitty process:
	PATH                                /home/mk/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_GB.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /usr/bin/fish
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                mk
	XDG_SESSION_CLASS                   user
	XDG_DATA_DIRS                       /home/mk/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_SESSION_TYPE                    wayland
	LC_MESSAGES                         en_US.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SESSION_DESKTOP                 gnome
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
```

**Additional context**

Minimal kitty config:
```
font_family Source Code Pro
```

**Comment by kovidgoyal** [comment]
That will be because it is being rendered from a different font. Easily
confirmed by using --debug-font-fallback. When you render your extra
character it will be queried from the system. Whatever font it was found
in is now checked first to avoid having to query the system again, which
is slow. That font presumably has your character in emoji form instead
of text form. 

I could of course change kitty to always query the system, but this is a
performance hit to support an edge case. Instead I recommend using
symbol_map. 

Or maybe I can have the system query occur only if the fallback font is
returning an emoji for a text symbol or vice versa.

**Comment by mkalinski** [comment]
Okay, I understand what's going on now. I'm going to use symbol_map.

This behaviour is surprising, but I get that it's an edge case that's not worth potentially sacrificing performance for.
