### ISSUE TITLE
set_tab_title with mouse doubleclick

### ISSUE THREAD

**Issue by porjo** [kovidgoyal/kitty#6866]
Other terminal applications I've used have a convention of renaming tabs by doubleclick'ing on the tab title. It would be nice if Kitty supported this.

Using `mouse_map` I can map a doubleclick to this action e.g.
```
mouse_map left doubleclick ungrabbed set_tab_title
```
however it only triggers when clicking on the main window, not the tab title. I would like the opposite - only trigger when clicking on the tab title.

**Comment by kovidgoyal** [comment]
Not something I am interested in implementing, but a PR is welcome.
