### ISSUE TITLE
Open URL hints in background?

### ISSUE THREAD

**Issue by alok** [kovidgoyal/kitty#687]
I often want to open several URLs at once from my terminal, and then switch to my browser to view them. Vim's `gx` is annoying for me because it focuses the browser each time, forcing me to refocus Vim before I open the next URL.

Kitty is the same way, and I was wondering if you'd be interested in adding a way to configure that.

**Comment by kovidgoyal** [comment]
kitty does not focus the browser. Your window system does that. All kitty does is call whatever command you tell it to (defaulting to open or xdg-open). So if you have a command that can cause browsers to open URLs without focusing themselves, use that and you will get the result you want. The only caveat is that you will need to press `ctrl+shift+e` again after each activation. It would be relatively simple patch to the hints kitten to have it not exit after activating the URL, PRs for that are welcome.

**Comment by alok** [comment]
Thanks. The choice of `esc` instead of `return` to open the selection does seem a little unusual to me, since Vim has conditioned me to use `esc` to cancel.

**Comment by kovidgoyal** [comment]
Enter is already used to select matches when there are multi-character matches.
