### ISSUE TITLE
Cant' connect via ssh: Creating temp directory failed

### ISSUE THREAD

**Issue by Ianneee** [kovidgoyal/kitty#6879]
**Describe the bug**
I'm trying to connect to [OverTheWire](https://overthewire.org/wargames/bandit/bandit0.html) via SSH, but I'm receiving this error:
```
mktemp: failed to create directory via template ‘/home/bandit0/.kitty-ssh-kitten-untar-XXXXXXXXXXXX’: Permission denied
Creating temp directory failed
Shared connection to bandit.labs.overthewire.org closed.
```

**To Reproduce**
*Level bandit0 https://overthewire.org/wargames/bandit/bandit0.html*
1. kitty +kitten ssh bandit0@bandit.labs.overthewire.org -p2220
2. Enter password: bandit0

**Comment by kovidgoyal** [comment]
That error is quite clear, you dont have permission to write to $HOME on
the remote server, the kitten needs this ability.
