### ISSUE TITLE
Unable to copy text after copying text to unnamedplus in neovim under wayland

### ISSUE THREAD

**Issue by ch3n9w** [kovidgoyal/kitty#6890]
**Describe the bug**
After copy text in neovim and quit, I can't copy text in kitty, unless I focus to another window and then focus back.

**To Reproduce**
1. launch kitty, open file with `nvim <file>`
2. copy text A to unnamedplus by pressing `yy` in neovim
3. quit nvim, paste the text copied from neovim, the output should be text A as expected
4. select and copy text B in kitty
5. paste the copied text, the output is text A rather than text B
6. focus to another window (like another kitty terminal), and focus back
7. reproduce step 4 and 5, the output is text B as expected

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux Shadow 6.6.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 04 Dec 2023 00:28:58 +0000 x86_64
Arch Linux 6.6.4-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
        PATH                                /opt/google-cloud-cli/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        GLFW_IM_MODULE                      ibus
        DISPLAY                             :1
        WAYLAND_DISPLAY                     wayland-1
        USER                                ch4ser
        XCURSOR_SIZE                        24
        XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
        XDG_BACKEND                         wayland
        XDG_SEAT                            seat0
        XDG_SESSION_DESKTOP                 Hyprland
        XDG_SESSION_TYPE                    wayland
        XDG_CURRENT_DESKTOP                 Hyprland
        XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
        XDG_SESSION_CLASS                   user
        XDG_VTNR                            1
        XDG_SESSION_ID                      2
        XDG_RUNTIME_DIR                     /run/user/1000
        XDG_DATA_DIRS                       /home/ch4ser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

This debug output has been copied to the clipboard
~
```

neovim version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**

the issue can be reproduced with `kitty --config NONE`, and the neovim's configuration only contains `set clipboard=unnamedplus` in ~/.config/nvim/init.vim. The compositor is hyprland.

**Comment by kovidgoyal** [comment]
Update to neovim 0.10 which has native osc52 support and you should be fine. Or use https://github.com/ojroques/nvim-osc52

**Comment by kovidgoyal** [comment]
Then please come up with a reproducer without nvim involved.

**Comment by kovidgoyal** [comment]
It is related to wayland and more specifically to how wl-copy works,
easily confirmed by running kitty with linux_display_backend x11 in
kitty.conf. As I said for nvim, use osc52 instead and you will be fine.
In this case instead of using wl-copy use kitten clipboard 

echo hello | kitten clipboard

**Comment by ch3n9w** [comment]
Thanks for your advice! A feasible mitigation method at this stage is not to use wl-clipboard in kitty and modify g:clipboard in neovim, which solves my issue.

**Comment by life5ign** [comment]
For reference, this was reported on tmux-yank: https://github.com/tmux-plugins/tmux-yank/issues/151
