### ISSUE TITLE
Espanso Expansion Issue: Kitty rendering wrong characters

### ISSUE THREAD

**Issue by lewisblackburn** [kovidgoyal/kitty#6895]
**Describe the Bug**

When using Espanso to expand a command in Kitty terminal, the pipe character (`|`) is rendered as a backslash (`\`). This happens with any character "unshifted" character e.g. less than (`<`) is rendered as a comma (`,`). I think the bug is related to kitty as it seems to not be an issue in other terminals.

**To Reproduce**

Steps to reproduce the behaviour:

1. Obviously Espanso needs to be installed.
2. Type an expansion, in my case `;cp`, in the terminal.
3. This expands to `xclip -selection clipboard ,`.
2. It should expand to `xclip -selection clipboard <`

**Environment Details**

- **Terminal Emulator:** Kitty
- **Espanso Version:** 2.2.0
- **Operating System:** Fedora Linux 39
- **Shell:** Fish

**Comment by kovidgoyal** [comment]
Espanso will be using some xtest based hack or the other to insert text,
I'm afraid I dont have the time/interest to debug it, but patches are
welcome.

**Comment by kovidgoyal** [comment]
And dup of #4487
