### ISSUE TITLE
UTF-8 decoding across multiple reads

### ISSUE THREAD

**Issue by egmontkob** [kovidgoyal/kitty#69]
kitty handles incorrectly if a UTF-8 sequence is read in two fragments, with a slight delay in between.

Example:

`echo -ne '\xc3'; sleep 1; echo -e '\xa1'`

Expected behavior: The letter `á` should appear on the screen after the 1 second delay.

Actual behavior: Some other symbol is displayed.

This causes random screen corruptions in potentially plenty of apps. I've seen one with a giant Midnight Commander screen.

**Comment by kovidgoyal** [comment]
Hmm, I though I handled this, but obviously, I forgot, thanks for the bug report.
