### ISSUE TITLE
For the Community

### ISSUE THREAD

**Issue by quintanaplaca** [kovidgoyal/kitty#6904]
Hello!

I've made the migration to the Kitty terminal emulator, and I'm really thrilled with it. For usability, features, performance. 

I've been looking for a group, a community to discuss ideas, make customizations and help with any questions. 

As I didn't find a community like this, I decided to create one, via the Telegram messaging app, which can be accessed via: https://t.me/kittyemulator

I hope that those responsible for the project agree with this initiative, and I invite everyone who wants to participate. 

Thank you.

**Comment by kovidgoyal** [comment]
Note that you can use the discussion here or the reddit group as linked in the readme as well.
