### ISSUE TITLE
Feature Request: A kitten for drag and dop of files

### ISSUE THREAD

**Issue by vypxl** [kovidgoyal/kitty#6906]
**Is your feature request related to a problem? Please describe.**
I don't like to open a file manager or have to click through a 'select file' dialog whenever I have to upload a file somewhere.

**Describe the solution you'd like**
A kitten (or 2) that would work like this:
- `kitten drag <fname>` would start a file drag / or transform the kitty window into a drag source, so the specified file/directory can be dragged into another application.
- `kitten drop <fname>` transforms the kitty window into a drag sink, so a file/directory can be dropped onto it. The dropped content will be written to `fname`.

**Describe alternatives you've considered**
There are tools for this, like [dragon](https://github.com/mwh/dragon) and [ripdrag](https://github.com/nik012003/ripdrag).
They both create a GTK window to drag / drop files from / to. This feels cumbersome, that's why I think a kitty integration would be great.

**Comment by vypxl** [comment]
I would be willing to work on this, but I have no idea how to go about making the kitty window drag/droppable haha

**Comment by kovidgoyal** [comment]
Not something I am interested in, sorry. kitty already has various
kittens that make transferring files/directories elsewhere very easy.
See the remote_file and transfer kittens. IMO drag/drop is not a
superior interface for this.

**Comment by vypxl** [comment]
I understand that you don't want to work on this. Could it be a third party kitten maybe?

I don't want to use this to transfer files. I agree that drag and drop isn't better for that.
The idea was just for use with things like web forms, where you need to upload files without the possiblilty of using anything else besides a file picker or drag drop.

**Comment by kovidgoyal** [comment]
dup of #5851
