### ISSUE TITLE
Scroll page up and down not working

### ISSUE THREAD

**Issue by munzirtaha** [kovidgoyal/kitty#6911]
**Describe the bug**
I am new to kitty and thought to try it so sorry if I am missing something obvious. My understanding is ctrl+shift+page_up by default should scroll one page up. For me, pressing the sequence just prints `6~` in kitty with bash. Then, I tried to define  `map ctrl+shift+page_up scroll_page_up` in `kitty.conf` to no avail.

**To Reproduce**
1. run and command like `find .`
2. pressing `ctrl+shift+page_up`
3. `6~` printed and no scrolling happens

**Screenshots**

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux lenovo 6.6.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 11 Dec 2023 11:48:23 +0000 x86_64
Arch Linux 6.6.6-arch1-1 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/me/.config/kitty/kitty.conf

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/me/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                me
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     /home/me/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/me/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1
```

**Additional context**
Tried `kitty --config NONE` and the problem is exactly the same. However, using `map ctrl+shift+0xff9a scroll_page_up` worked for me.

**Comment by kovidgoyal** [comment]
Does not reproduce for me with those steps, presumably your system is
generating some other key code for ctrl+shift+pgup Use --debug-input to
see what they are and map them accordingly.

**Comment by munzirtaha** [comment]
This is the output of `--debug-input`:

```
Press xkb_keycode: 0x49 clean_sym: KP_Prior composed_sym: KP_Prior mods: none glfw_key: 57421 (KP_PAGE_UP) xkb_key: 65434 (KP_Prior)
on_key_input: glfw key: 0xe04d native_code: 0xff9a action: PRESS mods: none text: '' state: 0 
text-input: updating cursor position: left=174 top=43 width=10 height=20
sent encoded key to child: ^[ [ 5 ~ 
text-input: done event: serial: 6 current_commit_serial: 6
```

I guess KP_PAGE_UP because I am using the PgUp from the KeyPad which is the only PgUp I have on my laptop. Do you intentionally distinguish between PageUp whether from full size keyboards or the keypad? As human beings should we expect this PgUp sensitivity?

**Comment by kovidgoyal** [comment]
yes, it is intentional. It allows people to make full use of the numeric
keypad.

**Comment by mannubaveja007** [comment]
> yes, it is intentional. It allows people to make full use of the numeric keypad.

new to this sorry would you mind sharing how to make full use of numeric keypad in the same?
