### ISSUE TITLE
Cursor size is inconsistent with the rest of the DE in Plasma 6/Wayland

### ISSUE THREAD

**Issue by MadCatX** [kovidgoyal/kitty#6914]
According to KDE developers, the cause is kitty's lack of support for `input-shape-v1` Wayland protocol. See https://bugs.kde.org/show_bug.cgi?id=478107 for the original report at KDE bugzilla.

**Comment by kovidgoyal** [comment]
Yeah I might someday get around to supporting that protocol which IIRC
was released a few *months* ago. If KDE expects applications to support
a months old protocol they are insane. They need to set XCURSOR_SIZE
or use the desktop settings portal to make that size available to
applications.

**Comment by kovidgoyal** [comment]
Not to mention that that protocol is both unstable and provides no way to know the cursor size for custom cursors and so is not a solution to the DE not providing cursor size information in backward compatible ways.

**Comment by MadCatX** [comment]
Thanks for explaining the situation. Any hints where to look in case I'd like to give it a go myself? I assume that the actual protocol name is [cursor_shape_v1](https://hoyon.github.io/wayland-protocol-docs/protocols/cursor_shape_v1.html)?

**Comment by kovidgoyal** [comment]
yes you would need to implement that in glfw/wl_*

**Comment by kovidgoyal** [comment]
I had a few minutes so I implemented it, but it is currently disabled by an if (false) since no actual released wayland compositors support it so I cant test it. See line 726 in wl_init.c to enable. https://github.com/kovidgoyal/kitty/commit/cff490f881a8eba6636a32387a00d1c91c6ee4d4

**Comment by MadCatX** [comment]
Just tested it with Plasma 6 and it seems to work fine. Thanks for doing this.

**Comment by kovidgoyal** [comment]
Problem is it causes hyprland to crash so I can enable it.

**Comment by MadCatX** [comment]
I understand. Any chance in can be hidden behind an env var or a setting? I'm okay with enabling it manually because it does improve my Kitty experience under Plasma 6 a lot.

**Comment by kovidgoyal** [comment]
I suggest opening an issue with hyprland, if they fix it, I can just
enable it in kitty. This is rather too small a thing for a dedicated
setting/env var.

**Comment by MadCatX** [comment]
Just FTR, I just tried the patched kitty with the latest Hyprland from git and it seems to work correctly for me.
