### ISSUE TITLE
[Feature Request] Support iterm2 like smart selection

### ISSUE THREAD

**Issue by hiberabyss** [kovidgoyal/kitty#6919]
**Is your feature request related to a problem? Please describe.**
Sometimes, we need to convert some text into url.
For example, `git@github.com:torvalds/linux` could be converted to `https://github.com/torvalds/linux`.

When mouse hover in such text, I would like to like to click the text and open the converted url.

**Describe the solution you'd like**
In iterm2, I could accomplish this via the `Smart Selection` feature.
We could define regex to recognize text, and specify action will be done when click. The regex group could be referenced in the action.

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/kittens/hints/
