### ISSUE TITLE
Open new tab in same folder

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#692]
Is there a way to open a new tab in the same folder as in the current tab. This as a default would be ok with me, similar ot the macOS Terminal app.

**Comment by erf** [comment]
Thanks!

**Comment by alper** [comment]
So how do you do this?

**Comment by page-down** [comment]
> So how do you do this?

Write `map f1 new_tab_with_cwd ` in your config file, and pressing F1 will open a new tab in the current location.

You can also use the `launch` action.

https://sw.kovidgoyal.net/kitty/launch/

**Comment by alper** [comment]
OK. So if I want this to be the behaviour of Command-T, then I have to find out where that is defined and replace it with `new_tab_with_cwd`?

**Comment by page-down** [comment]
Just write it to the configuration file.
The configuration file can be opened in the macOS menu "kitty" -> "Preferences", or by default with cmd+, or ctrl+shift+f2.

https://sw.kovidgoyal.net/kitty/conf/

Search for `new_tab` on the above page.

**Comment by worthless443** [comment]
`map ctrl+shift+t new_tab_with_cwd` does not work

**Comment by Jarmos-san** [comment]
Yup, `map ctrl+shift+t new_tab_with_cwd` doesn't work even though it's there in the `kitty.conf` file.

**Comment by page-down** [comment]
@Jarmos-san

I have seen some recent feedback about the cwd issue, however I cannot reproduce it with `kitty --config=NONE -o 'map f1 new_tab_with_cwd'`.
It would be helpful if you could provide minimal reproduction steps.
For example, the problem will occur when used with some configuration of the shell or with some other software.

**Comment by Mattchine** [comment]
Both works for me in kitty 0.24.4

```conf
map kitty_mod+enter launch --cwd=current
map kitty_mod+t     new_tab_with_cwd
```

**Comment by t-h2o** [comment]
With:
```kitty
map ctrl+t     new_tab new_tab_with_cwd
```
I get this error:
```error
Failed to launch child: new_tab_with_cwd
With error: No such file or directory
Press Enter to exit.
```
```version
$ kitty --version 
kitty 0.24.2 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment]
map ctrl+t launch --cwd=current --type=tab

**Comment by svenjacobs** [comment]
Use this if you want to have the same functionality for windows.

```
map kitty_mod+enter launch --cwd=current --type=window
map cmd+enter       launch --cwd=current --type=window
```

**Comment by TinyProbe** [comment]
map kitty_mod+t new_tab_with_cwd does work
map cmd+t new_tab_with_cwd doesn't work

i'm using macbook air m2.

**Comment by nihil2501** [comment]
> map kitty_mod+t new_tab_with_cwd does work map cmd+t new_tab_with_cwd doesn't work
> 
> i'm using macbook air m2.

I also am on macbook air m2 and this worked for me after restarting kitty

**Comment by whoop-t** [comment]
Macbook Pro
`map kitty_mod+t new_tab_with_cwd` -> doesnt work
`map cmd+t new_tab_with_cwd` -> works

I have to map both so this works on my mac and linux machine

**Comment by wraithm** [comment]
> Use this if you want to have the same functionality for windows.
> 
> ```
> map kitty_mod+enter launch --cwd=current --type=window
> map cmd+enter       launch --cwd=current --type=window
> ```

I found that I had to do `--type=os-window`

**Comment by jmada** [comment]
> map ctrl+t launch --cwd=current --type=tab

Worked perfectly!

**Comment by julioselva** [comment]
added this and worked perfectly on Ubuntu for new tabs and windows:
```sh
map kitty_mod+enter launch --cwd=current --type=window
map cmd+enter       launch --cwd=current --type=window
map kitty_mod+t     launch --cwd=current --type=tab
map cmd+t           launch --cwd=current --type=tab
```

I believe this should work on MacOS too, but I could not test it.

**Comment by josephdburdick** [comment]
> added this and worked perfectly on Ubuntu for new tabs and windows:
> 
> ```shell
> map kitty_mod+enter launch --cwd=current --type=window
> map cmd+enter       launch --cwd=current --type=window
> map kitty_mod+t     launch --cwd=current --type=tab
> map cmd+t           launch --cwd=current --type=tab
> ```
> 
> I believe this should work on MacOS too, but I could not test it.

Can confirm the new tab opens in current working directory on MacOS.

**Comment by Hisui02** [comment]
Is there a way to get this behavior but prevent it on SSH connections?
It happens to me a lot that I'm connected via SSH to somewhere and I need to check something on my computer but every tab opens already connected and exiting actually closes the tab and not the connection so it's really annoying.
I use the ssh kitten if there is a config there I'm missing, I could not find anything.

**Comment by t-h2o** [comment]
@Hisui02 ,
IMO, you should use tmux/screen on your server.
If you lost SSH connection for a while, you can easily come back on what you was doing.
With tmux you stay in the same folder after creating a new tab.

**Comment by Hisui02** [comment]
> @Hisui02 ,
> IMO, you should use tmux/screen on your server.
> If you lost SSH connection for a while, you can easily come back on what you was doing.
> With tmux you stay in the same folder after creating a new tab.

I'm not a huge tmux fan, at least having the multiplexer already built in kitty.
I just want to open new kitty tabs in the same directory but prevent it if I'm connected via SSH because it does not work properly.

**Comment by kovidgoyal** [comment]
Should be a pretty trivial script to write, something like:

```
map kitty_mod+t remote_control_script /path/to/script.sh
```

In script.sh use

kitten @ ls 

to get the active window and what command is running in it, easy with jq. Then if its the ssh kitten run

```
kitten @ launch --type=tab
```

if it isnt run
```
kitten @ launch --type=tab --cwd=current
```

dont forget to make script.sh executable.

**Comment by Hisui02** [comment]
> Should be a pretty trivial script to write, something like:
> 
> ```
> map kitty_mod+t remote_control_script /path/to/script.sh
> ```
> 
> In script.sh use
> 
> kitten @ ls
> 
> to get the active window and what command is running in it, easy with jq. Then if its the ssh kitten run
> 
> ```
> kitten @ launch --type=tab
> ```
> 
> if it isnt run
> 
> ```
> kitten @ launch --type=tab --cwd=current
> ```
> 
> dont forget to make script.sh executable.

I can't get it to work, this is what I got but it is always false?

```sh
#!/bin/sh

if jq '.[] | .tabs[] | .windows[] | select(.is_active and .is_focused) | any(.foreground_processes[]?; .cmdline[0] == "kitten" and .cmdline[1] == "ssh")' kitten @ ls | grep -q true; then
  kitten @ launch --type=tab
else
  kitten @ launch --type=tab --cwd=current
fi

```

**Comment by kovidgoyal** [comment]
Sorry I dont have time to write the code to parse JSON for you, if you
find jq too hard, use python or whatever language you are familiar with, instead.

**Comment by Hisui02** [comment]
I made it work, I'll leave it here if anyone needs it:
```~/.config/kitty/is_ssh.sh```
```sh
#!/bin/sh

IS_KSSH=$(kitten @ ls | jq '.[] | .tabs[] | .windows[] | select(.is_active and .is_focused) | any(.foreground_processes[]?; .cmdline[0] == "kitten" and .cmdline[1] == "ssh")')

if echo "$IS_KSSH" | grep -q true; then
  kitten @ launch --type=$1
else
  kitten @ launch --type=$1 --cwd=current
fi

```

```kitty.conf```
```
map kitty_mod+enter remote_control_script ~/.config/kitty/is_kssh.sh window
map kitty_mod+t remote_control_script ~/.config/kitty/is_kssh.sh tab
```

**Comment by julionc** [comment]
Edit `.config/kitty/kitty.conf`
```
map kitty_mod+t launch --cwd=current --type=tab
map cmd+t       launch --cwd=current --type=tab
```

**Comment by yitaverse** [comment]
In Fedora (XFCE, with Hyprland), I created the `custom.conf` file in the `~/.config/kitty` path, assuming that the `~/.config/kitty/kitty.conf` file contains:

```
# Include Custom Configuration
# Create the custom.conf file in ~/.config/kitty to overwrite the default configuration
include ./custom.conf
```

And in the `custom.conf` file, I added:

```
map super+n new_tab_with_cwd .
copy_on_select yes
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard
```

Then, pressing the key combination `super+N` opens a new tab in the same path as the previous one (note the period at the end of the first line, indicating the current path to open the new tab; `super` = Windows key on PC = `cmd` on Mac).

The remaining three lines in the `custom.conf` file are used to manage copying to the clipboard on selection and copy/paste with the shortcuts `CTRL+C` (copy, only if there is a selection; otherwise, it aborts the process) and `CTRL+V` (paste).
