### ISSUE TITLE
[startup_session] kitty crashes after opening 

### ISSUE THREAD

**Issue by usb1** [kovidgoyal/kitty#6921]
I'm currently working on configuring my Kitty terminal emulator to automatically display an image when it starts. To achieve this, I've set up a session file that includes a launch command to display an image using kitty +kitten icat /path/to/image.jpg. This session file is referenced in my kitty.conf under startup_session. However, I'm facing a challenge where Kitty opens, shows the image for a short moment, but then closes immediately. Unfortunately, it doesn't provide any error messages or logs, even when I start it from another terminal or attempt to use debugging flags

I'm experiencing an issue with the Kitty terminal where it closes instantly after opening. The setup includes a kitty.conf file with a startup_session directive pointing to a session file. This session file contains a launch command (launch kitty +kitten icat /path/to/image.jpg) to display an image at startup. When I open Kitty, it briefly shows the image, then shuts down without any error messages. Running Kitty from another terminal doesn't provide any debug information. I also tried the --debug flag, but it wasn't recognized. How can I effectively diagnose and resolve this issue?

**Comment by kovidgoyal** [comment]
You want

launch kitten icat --hold /absolute/path/to/image.png
or better
launch --hold kitten icat /absolute/path/to/image.png

**Comment by usb1** [comment]
Hey thank you this worked amazing, but now I wanted to ask for some help with a startup script in Kitty terminal. My script's aim is to display a random image at Kitty's startup:

`#!/bin/bash
IMAGES_DIR="/home/xiao/Downloads/png"
IMAGE=$(find "$IMAGES_DIR" -type f | shuf -n 1)
kitty +kitten icat "$IMAGE"
`
This script works when run manually, but not when set as startup_session in kitty.conf. Additionally, I initially tried using launch --hold kitty +kitten icat, but it seems launch isn't recognized in a bash script context. Why might launch not work here, and is there a way to use it or an alternative to achieve my goal of displaying an image at startup without immediately closing Kitty?

**Comment by kovidgoyal** [comment]
launch is not a script command its a kitty command. And your script will work fine in startup session you just need to run it correctly.
