### ISSUE TITLE
kitty hints highlight the wrong character in RTL text

### ISSUE THREAD

**Issue by munzirtaha** [kovidgoyal/kitty#6927]
**Describe the bug**
The highlighted character for the hint numbering is not correct in case of RTL text. 

**To Reproduce**
1. `mkdir 'اللغة العربية'`
2. `kitty_mod+p>y`
3. See the number added is in a different place than the highlighted character

**Comment by kovidgoyal** [comment]
This is not something I have the time/interest to fix, but patches are
most welcome. Relevant code is in the hints/marks.go file.

**Comment by munzirtaha** [comment]
I guess this should be a trivial fix. Instead of highlighting the first character of the RTL word, just highlight the last character, theoretically, this should fix it. Does this make sense to you?

**Comment by kovidgoyal** [comment]
Sure, in principle, there might be some edge cases to handle though. For
instance for words that contain a mix of characters, punctuation, etc.

**Comment by munzirtaha** [comment]
Even if some edge cases show, it's not important, but I couldn't understand why mix of characters or punctuation would even be an exception. By "word", I meant any characters before the space, so e.g.

```
>>> a="عربي!!"
>>> a[len(a)-1]
'!'
```
That's fine because now the **"!"** would be highlighted which is the last character of the Arabic word and it would be the first character in the column aligned with currently rendered highlight. Of course, I am speaking about a **"word"** not a **"string"**, so in **"Hello, World!"**, the **","** should be highlighted and not the **"!"**

**Comment by kovidgoyal** [comment]
The hints kitten can match many things apart from words. You need to
check what a particular match is an decide whether to treat it as RTL or
LTR based on the codepoints in the match. There is no straightforward way
to make that decision, in general, for mixed text. FOr example if you
are matching a path and one of the path components is LTR and another is
RTL, so you put the hint at the start or the end?

**Comment by munzirtaha** [comment]
> FOr example if you are matching a path and one of the path components is LTR and another is RTL, so you put the hint at the start or the end?

Only if the first component is Arabic, you put the the hint at the end.

If this is easy for  you to modify, I would be willing to test all the cases, and at least I would understand which functions needs modifications. Otherwise, I would would put it on my TOOD list, though I don't know a thing about Go. Thanks for your hints ;)
