### ISSUE TITLE
Kitty is crashing when exit like as Tile Window 

### ISSUE THREAD

**Issue by jockrow** [kovidgoyal/kitty#6929]
**Describe the bug**
When I Tile Kitty to Left or Right of Screen and I try to back to normal Window, Kitty is crashing, I have this setting in my kitty.conf: hide_window_decorations titlebar-only

**To Reproduce**
1. Tile the window to Left and choose another app
2. Exit another app to normal window
3. I try to back Exit Full Screen
4. Kitty is crashing

**Environment details**
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin Richards-MacBook-Air.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		14.0 BuildVersion:		23A344
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/richard/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style        (True, False)
background_blur              8
background_opacity           0.8
copy_on_select               clipboard
enabled_layouts              ['fat:bias=75;full_size=1;mirrored=false']
font_family                  SauceCodePro Nerd Font
font_size                    12.0
hide_window_decorations      2
macos_option_as_alt          3
macos_traditional_fullscreen True
tab_bar_min_tabs             1
tab_bar_style                custom
tab_title_template           {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index} {title}
Added shortcuts:
	ctrl+= →  resize_window reset
	ctrl+cmd+down →  resize_window shorter 3
	ctrl+cmd+left →  resize_window narrower
	ctrl+cmd+right →  resize_window wider
	ctrl+cmd+up →  resize_window taller
	f7 →  layout_action rotate
	opt+cmd+down →  neighboring_window down
	opt+cmd+left →  neighboring_window left
	opt+cmd+right →  neighboring_window right
	opt+cmd+up →  neighboring_window up
Changed shortcuts:
	cmd+0 →  goto_tab 0
	cmd+1 →  goto_tab 1
	cmd+2 →  goto_tab 2
	cmd+3 →  goto_tab 3
	cmd+4 →  goto_tab 4
	cmd+5 →  goto_tab 5
	cmd+6 →  goto_tab 6
	cmd+7 →  goto_tab 7
	cmd+8 →  goto_tab 8
	cmd+9 →  goto_tab 9
	cmd+enter →  new_window_with_cwd
	kitty_mod+down →  layout_action move_to_screen_edge bottom
	kitty_mod+left →  layout_action move_to_screen_edge left
	kitty_mod+right →  layout_action move_to_screen_edge right
	kitty_mod+up →  layout_action move_to_screen_edge top

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                richard

**Comment by kovidgoyal** [comment]
I dont understand your reproduction steps. What does exit another app to
normal screen mean? And post the crash report.

**Comment by kovidgoyal** [comment]
no followup
