### ISSUE TITLE
Interaction between kitty and shell bindings

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#693]
Binding kitty remote actions is very inconsistent. Is it supposed to work? Or is `@` actions and kittens are only for interactive use? I cant understand on which side the problem is. Just recently the keybind to get selection content started crashing, sometimes instantly, sometimes after a big timeout, with different traceback in different situations.

Using kitty bindings is more consistent but greatly reduces scripting possibilities.

**Comment by kovidgoyal** [comment]
You'd have to give me some actual examples of what you are talking about. kittens dont care how they are invoked, as long as the terminal they are connected to is kitty.

**Comment by SolitudeSF** [comment]
i havent used kittens from bindings, so i can only talk about `@` commands. i used `kitty @ get-text --self --extent=selection`. it worked pre ~0.11. now it inconsistently crashes with 
```[bytes out] Traceback (most recent call last):
[bytes out]   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[bytes out]     "__main__", mod_spec)
[bytes out]   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
[bytes out]     exec(code, run_globals)
[bytes out]   File "/usr/bin/../lib/kitty/__main__.py", line 104, in <module>
[bytes out]     main()
[bytes out]   File "/usr/bin/../lib/kitty/__main__.py", line 100, in main
[bytes out]     func(sys.argv[1:])
[bytes out]   File "/usr/bin/../lib/kitty/__main__.py", line 21, in remote_control
[bytes out]     main(args)
[bytes out]   File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 159, in main
[bytes out]     response = do_io(global_opts.to, send, func.no_response)
[bytes out]   File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 115, in do_io
[bytes out]     received = io.recv(timeout=10)
[bytes out]   File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 95, in recv
[bytes out]     read_command_response(self.tty_fd, timeout, ans)
[bytes out] TimeoutError: Timed out while waiting to read cmd response

 ▲ ~  cea:362c2b97j}            
```
as you can see it also leaks some data to shell. this may be problem in the shell, but reverting to older version didnt fixed it. im using `elvish`. i tried to check it in bash but havent managed to do anything.

**Comment by kovidgoyal** [comment]
Well, without some way to reproduce the error there's not much I can do about it. That error basically means that the response from kitty to the kitty @ command never arrived, or only partially arrived. The only way that can happen is if something is putting the tty driver into canonical mode while kitty @ is waiting for the response. In canonical mode, the tty device becomes line buffered.
kitty @ sets the tty driver into raw mode, before starting. 

I'm not familiar with elvish, so I can't comment on it, but you can likely workaround the issue by using the sockets mode for @ commands. See the --to and --listen-on options.
