### ISSUE TITLE
Broken brpaste when using kitty+tmux+joe editor

### ISSUE THREAD

**Issue by ondrejj** [kovidgoyal/kitty#6939]
**Describe the bug**
In special situations bracketed paste is broken. I am using kitty, tmux and joe's editor and this combination doesn't work.
Joe's editor has -brpaste/--brpaste setting, which can enable/disable brpaste support in this editor. Doesn't matter, which setting is used, it's still broken. Also tmux has brpaste autodetection, but able to set it manually too. Still same problem for both settings.

Using another terminal, like gnome-terminal can fix my problems and gnome-terminal+tmux+joe works well. That is why I am reporting this against kitty.

Another problem is, that in joe's editor each newline consumes one row from next lines. But again only in kitty when doing bracketed paste.

**To Reproduce**
1. run kitty
2. run tmux
3. run seq 10
4. copy rows 1-10
5. run joe
6. paste

**Screenshots**
Just text output:
`I    Unnamed (Modified)                                    Row 1    Col 12`
`12345678910`

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux home.salstar.sk 6.6.6-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Dec 11 17:29:08 UTC 2023 x86_64
S
Kernel 6.6.6-200.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: [32mWayland[39m
[32mFrozen:[39m False
[32mPaths:[39m
[33m  kitty:[39m /usr/bin/kitty
[33m  base dir:[39m /usr/lib64/kitty
[33m  extensions dir:[39m /usr/lib64/kitty/kitty
[33m  system shell:[39m /bin/bash
[32mLoaded config files:[39m
  /home/ondrejj/.config/kitty/kitty.conf

Config options different from defaults:
close_on_child_death  True
font_family           Sans Mono
font_size             13.0
initial_window_height (25, 'cells')
initial_window_width  (80, 'cells')
[94mmodify_font:[39m
    cell_height 2
    cell_width 1
placement_strategy    top-left
remember_window_size  False
resize_in_steps       True
shell_integration     frozenset({'disabled'})
tab_bar_style         powerline
window_padding_width  FloatEdges(left=4.0, top=0, right=4.0, bottom=0)
[94mAdded mouse actions:[39m
	ctrl+left click grabbed →  mouse_click_url_or_select
	ctrl+left click ungrabbed →  mouse_click_url_or_select
[94mRemoved mouse actions:[39m
	left click ungrabbed →  mouse_handle_click selection link prompt
[94mAdded shortcuts:[39m
	alt+1 →  goto_tab 1
	alt+2 →  goto_tab 2
	alt+3 →  goto_tab 3
	alt+4 →  goto_tab 4
	alt+5 →  goto_tab 5
	shift+page_down →  scroll_page_down
	shift+page_up →  scroll_page_up
[94mRemoved shortcuts:[39m
	kitty_mod+- →  change_font_size all -2.0
[94mColors[39m:
	color1                #cd0000 [48:2:205:0:0m  [49m
	color10               #00ff00 [48:2:0:255:0m  [49m
	color11               #ffff00 [48:2:255:255:0m  [49m
	color12               #5c5cff [48:2:92:92:255m  [49m
	color13               #ff00ff [48:2:255:0:255m  [49m
	color14               #00ffff [48:2:0:255:255m  [49m
	color2                #00cd00 [48:2:0:205:0m  [49m
	color3                #cdcd00 [48:2:205:205:0m  [49m
	color4                #1010ff [48:2:16:16:255m  [49m
	color5                #cd00cd [48:2:205:0:205m  [49m
	color6                #00cdcd [48:2:0:205:205m  [49m
	color7                #faebd7 [48:2:250:235:215m  [49m
	color8                #404040 [48:2:64:64:64m  [49m
	color9                #ff0000 [48:2:255:0:0m  [49m
	foreground            #ffffff [48:2:255:255:255m  [49m

[32mImportant environment variables seen by the kitty process:[39m
	PATH                                [2m/home/ondrejj/bin:/home/ondrejj/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/usr/sbin:/home/ondrejj/.local/bin[22m
	LANG                                [2msk_SK.UTF-8[22m
	EDITOR                              [2mjoe[22m
	SHELL                               [2m/bin/bash[22m
	DISPLAY                             [2m:0[22m
	WAYLAND_DISPLAY                     [2mwayland-0[22m
	USER                                [2mondrejj[22m
	XDG_DATA_DIRS                       [2m/home/ondrejj/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/[22m
	XDG_RUNTIME_DIR                     [2m/run/user/1000[22m
	XDG_CURRENT_DESKTOP                 [2mGNOME[22m
	XDG_SESSION_CLASS                   [2muser[22m
	XDG_SESSION_DESKTOP                 [2mgnome[22m
	XDG_SESSION_TYPE                    [2mwayland[22m
	XDG_MENU_PREFIX                     [2mgnome-[22m

[35mThis debug output has been copied to the clipboard[m
```

**Additional context**
All other combinations works well, for example:
gnome-terminal + tmux + joe
xterm + tmux + joe
kitty + joe
kitty + tmux + cat > /tmp/file

**Comment by kovidgoyal** [comment]
I'm afraid I dont have the time/interest to debug issues caused by tmux.
If you can reproduce without tmux, I'll take a look. In general turn on
bracketed paste manually in yout tmux config.

**Comment by ondrejj** [comment]
Doesn't matter, if bracketed paste mode is enabled or disabled in tmux.
Also doesn't matter, if bracketed paste is enabled or disabled in joe. There is always a problem pasting into joe, when runnng kitty+tmux+joe. I tested to set in .tmux.conf:
`set terminal-features Dsbp` or `set terminal-features Enbp`.
Also run `joe --brpaste` and `joe --brpaste` in both situations. Always same problem.

I don't this, this is a tmux or joe problem, because cat or native bash runs well in tmux under kitty.

**Comment by ondrejj** [comment]
After some experiments I found, than using:
`seq 10 | sed 's/$/\r\n/' | xclip -selection clipboard`
paste is better. Paste is identified by kitty and I am able to select, if it should be sanitized or just pasted. Pasting without sanitize will paste it as multiple rows.
Without `\n` pasted text is similar, but still some characters are eaten from text below (which doen't happen when running without tmux or in other terminal with tmux).

**Comment by ondrejj** [comment]
After some testing there is no tmux required to reproduce this issue. Just open `joe -brpaste` in kitty terminal and copy&paste some rows. Rows are pasted without newlines and each row consumes one line from buffer below cursor.

@kovidgoyal, please, reopen this issue. I can't. Thank you.

**Comment by ondrejj** [comment]
Hmm, but joe's author can tell this too, that report this to kitty, because all other terminals like xterm, gnome-terminal, roxterm, Cool-retro-term, ... works well with joe. Just kitty didn't. :-(

**Comment by kovidgoyal** [comment]
Well, I know kitty's implementation of bracketed paste is correct. I
have no idea what joe does. Given it even needs a special command line
flag just to enable it points to its implementation not being mature.

**Comment by kovidgoyal** [comment]
Indeed from your description of this issue I can deduce that joe is not interpreting newlines in pasted text when bracketed paste is enabled. It is expecting carriage return instead of newline to terminate lines. This is wrong. kitty converts newlines to carriage returns when not in bracketed paste only. See https://github.com/kovidgoyal/kitty/issues/994 for discussion.

**Comment by ondrejj** [comment]
This -brpaste parameter is in default configuration and should be applied automatically, but for some reasons it isn't. I can take a look at this.

But brpaste implementation in joe is simple. Just disables wordwrap, autoindent and spaces temporarily. There is no special processing of other data between brpaste sequences, just like keyboard input.

Now looking into window.py, this function:
```
    def paste_text(self, text: Union[str, bytes]) -> None:
        if text and not self.destroyed:
            if isinstance(text, str):
                text = text.encode('utf-8')
            if self.screen.in_bracketed_paste_mode:
                text = sanitize_for_bracketed_paste(text)
            else:
                # Workaround for broken editors like nano that cannot handle
                # newlines in pasted text see https://github.com/kovidgoyal/kitt
                text = text.replace(b'\r\n', b'\n').replace(b'\n', b'\r')
            self.screen.paste(text)
```

When you are not in brpaste mode, `\n` is replaced by `\r` (LF newline converted to CR).
But when you are in brpaste mode, then no similar conversion is done.
You say, that kitty converts newlines (do you mean LF?) to CR, but I don't see this code.

This change helps to work for me well:
```
def paste_text(self, text: Union[str, bytes]) -> None:
        if text and not self.destroyed:
            if isinstance(text, str):
                text = text.encode('utf-8')
            if self.screen.in_bracketed_paste_mode:
                text = sanitize_for_bracketed_paste(text.replace(b'\n', b'\r'))
            else:
                # Workaround for broken editors like nano that cannot handle
                # newlines in pasted text see https://github.com/kovidgoyal/kitt
                text = text.replace(b'\r\n', b'\n').replace(b'\n', b'\r')
            self.screen.paste(text)
```

Works well for joe -brpaste, joe --brpaste (disabled) and also all combinations with tmux.

Thank you for pointing me to window.py sources.

**Comment by ondrejj** [comment]
Just for information, `-brpaste` parameter is as default in configuration, just I added `--brpaste` (disable brpaste) to my configuration years ago. Works well in joe. I think I did this because kitty's or other terminal's paste has been broken. With change above it's not needed to disable brpaste in joe.

**Comment by kovidgoyal** [comment]
Yes, kitty does not convert any bytes when pasting in bracketed paste. This is correct behavior. joe needs to be fixed to handle this. Converting newlines to carriage returns on paste is a horrible hack for broken editors.

**Comment by ondrejj** [comment]
Hmm, curious, that according to wikipedia (https://en.wikipedia.org/wiki/Bracketed-paste), first implementations of bracketed paste are in xterm and curiously joe's editor. This combination still works well. So looks like joe's editor was reference implementation in client application (when xterm is considered server app, joe user app).

According to this kitty is not working as other implementations.

In joe CTRL+J (0x10 or \\n) is a "delete to end of line" command. It's normally not pasted from terminal. I can make a patch to disable and convert CTRL+J to newline enters inside bracketed paste blocks, but I don't think this is a good behaviour.

Is it possible to add options to turn on/off this feature in kitty?

I wrote an paste-action script, which works, but kitty considers this converted block as unsafe.

**Comment by kovidgoyal** [comment]
The whole point of bracketed paste mode is that it allows pasting
unmodified text (barring the bracket paste termination sequence),
without security issues. If you are going to be modifying bytes anyway
there is no point in using it. Bracketed paste unambiguously signals
that the bytes within it are *content* not keystrokes and should be
interpreted as such by whatever is turning on bracketed paste.

Adding an option just means that now applications can have no clue what
the contents of a paste are. As such, no I wont be accepting an option
for this. If you cannot get joe fixed then feel free to run kitty with a
local patch.

**Comment by ondrejj** [comment]
No, local patch is not acceptable for me. I use Fedora packages and automatic updates. But this paste_action works and can be useful for other users too:

```
[ondrejj@work ~]$ cat .config/kitty/paste-actions.py 
#!/usr/bin/python3

def filter_paste(text):
    # fix kitty bracketed paste (brpaste)
    return text.replace("\n", "\r")
[ondrejj@work ~]$
```

Just kitty marks this as unsafe in later code. But using tmux clears this check for me.
