### ISSUE TITLE
Weird clipboard behavior on Mac OS

### ISSUE THREAD

**Issue by pcasaretto** [kovidgoyal/kitty#694]
From inside tmux I'm able to copy things from vim and paste them in any other kitty window.
tmux itself however cannot seem to access the clipboard.

I've recorded an asciicinema to demonstrate:
https://asciinema.org/a/aDLUs2gnS5iqdxREAYLkmXcQW

Here's my [current kitty config](https://github.com/pcasaretto/dotfiles/blob/d0ff33432a20171ced772b9907641132864dbe9e/kitty/kitty.conf.xdglink)

Also for [tmux](https://github.com/pcasaretto/dotfiles/blob/d0ff33432a20171ced772b9907641132864dbe9e/tmux/tmux.conf.symlink)

0.11.1

**Comment by kovidgoyal** [comment]
tmux needs to be told to use the OSC 52 clipboard escape codes and if you want to read from the clipboard in tmux then you have to enable that in kitty.conf (it is disdabled by default for security reasons). See clipboad_control in kitty.conf

**Comment by pcasaretto** [comment]
Nope. Went back to iTerm.
