### ISSUE TITLE
Window size decreased each time Kitty is open

### ISSUE THREAD

**Issue by koterpillar** [kovidgoyal/kitty#6946]
**Describe the bug**

Each time Kitty is open and closed, its window size, when not maximised, becomes smaller and smaller.

**To Reproduce**

1. Open Kitty and un-maximise the window if it is maximised.
2. Repeatedly close and open Kitty a few times.
3. The window size becomes smaller each time it is opened.
4. Eventually it complains:
```
[359 21:44:35.428235] Invalid geometry ignored: framebuffer: 632x40 window: 316x20

[359 21:44:35.468639] Ignoring resize request for tiny size: 632x40
[359 21:44:35.568872] Invalid geometry ignored: framebuffer: 632x40 window: 316x20
```

**Screenshots**
![first run](https://github.com/kovidgoyal/kitty/assets/140276/27600fd8-deb4-42e9-b496-8ed49a410458)

![second run](https://github.com/kovidgoyal/kitty/assets/140276/672a0605-8502-4fbe-af08-24e2f3c6686d)

![after about 12 runs](https://github.com/kovidgoyal/kitty/assets/140276/58eca45e-0044-4394-b5f1-1f9a0e5c5032)

**Environment details**
```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Linux <redacted> 6.6.7-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 21:43:37 UTC 2023 x86_64
S
Kernel 6.6.7-200.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: True
Paths:
  kitty: /home/<redacted>/.local/<redacted>/bin/kitty
  base dir: /home/<redacted>/.local/<redacted>/lib/kitty
  extensions dir: /home/<redacted>/.local/<redacted>/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/<redacted>/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                <redacted>.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                <redacted>
	XDG_DATA_DIRS                       /home/<redacted>/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

**Additional context**

Kitty configuration was deleted prior to reproducing.

This is Fedora 39, and other applications like the stock Terminal and Files don't shrink when repeatedly launched.

**Comment by kovidgoyal** [comment]
This is a GNOME+Wayland specific issue. I already spent several days
fixing it a few years back. Apparently some change to mutter broke it
again. I'm afraid I dont have the time/interest to deal with the endless
problems caused by GNOME. Patches welcome.

**Comment by kovidgoyal** [comment]
actually, on second thoughts, this may be a different GNOME specific
issue. Possibly kitty is not taking into account CSD size when saving 
last used OS window size.
