### ISSUE TITLE
kitty cannot capture focus when switching programs via keyboard on WSLg

### ISSUE THREAD

**Issue by ofseed** [kovidgoyal/kitty#6949]
**Describe the bug**
When using kitty on WSLg, If I switch between programs by using keyboard shortcuts, kitty will never
capture the focus.

**To Reproduce**
1. Open kitty on WSLg.
2. Switch to another program.
3. Try switching to kitty with a shortcut like `Alt +Tab`.
4. The former program lost the focus but kitty does not capture it either.
5. Click kitty's window, focus captured.

**Environment details**
```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Linux PCWORKSTATION 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64
Debian GNU/Linux 12 PCWORKSTATION /dev/tty

Running under: Wayland
Frozen: True
Paths:
  kitty: /home/ofseed/.local/kitty.app/bin/kitty
  base dir: /home/ofseed/.local/kitty.app/lib/kitty
  extensions dir: /home/ofseed/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/ofseed/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.8
font_family             CaskaydiaCove Nerd Font
font_features:
{'CaskaydiaCoveNF-Italic': ('+calt', '+ss01', '+ss02'),
 'CaskaydiaCoveNF-Regular': ('+ss02',)}
initial_window_height   (45, 'cells')
initial_window_width    (100, 'cells')
modify_font:
    underline_position 150%
    underline_thickness 150%
remember_window_size    False
shell                   fish --interactive
shell_integration       frozenset({'no-rc', 'enabled'})
update_check_interval   0.0
Colors:
	active_border_color     #b4befe   
	active_tab_background   #cba6f7   
	active_tab_foreground   #11111b   
	background              #1e1e2e   
	bell_border_color       #f9e2af   
	color0                  #45475a   
	color1                  #f38ba8   
	color10                 #a6e3a1   
	color11                 #f9e2af   
	color12                 #89b4fa   
	color13                 #f5c2e7   
	color14                 #94e2d5   
	color15                 #a6adc8   
	color2                  #a6e3a1   
	color3                  #f9e2af   
	color4                  #89b4fa   
	color5                  #f5c2e7   
	color6                  #94e2d5   
	color7                  #bac2de   
	color8                  #585b70   
	color9                  #f38ba8   
	cursor                  #f5e0dc   
	cursor_text_color       #1e1e2e   
	foreground              #cdd6f4   
	inactive_border_color   #6c7086   
	inactive_tab_background #181825   
	inactive_tab_foreground #cdd6f4   
	mark1_background        #b4befe   
	mark1_foreground        #1e1e2e   
	mark2_background        #cba6f7   
	mark2_foreground        #1e1e2e   
	mark3_background        #74c7ec   
	mark3_foreground        #1e1e2e   
	selection_background    #f5e0dc   
	selection_foreground    #1e1e2e   
	tab_bar_background      #11111b   
	url_color               #f5e0dc   

Important environment variables seen by the kitty process:
	PATH                                /home/ofseed/.cargo/bin:/home/ofseed/neovim/bin:/home/ofseed/.local/bin:/home/ofseed/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                ofseed
	XDG_RUNTIME_DIR                     /run/user/1000/
	XDG_DATA_DIRS                       /usr/local/share:/usr/share:/home/ofseed/.nix-profile/share:/nix/var/nix/profiles/default/share
```

**Additional context**
Same problem with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
there is no concept of "capturing" focus. Focus is distributed to top
level windows by the window manager.

**Comment by ofseed** [comment]
Thanks, related: https://github.com/microsoft/wslg/issues/959

**Comment by simonhf** [comment]
Thanks to @ofseed who published the workaround at the above link. The workaround is to run kitty as root via sudo. Then when alt-tabbing back to kitty, the keyboard always seems to get focus as expected. @kovidgoyal, does it make sense to you why the window manager would be treating a root process window differently from a user process window?

I also have to say that this focus issue only happens for some programs and not others, again suggesting that the issues is something to do with kitty and not the windows manager? For example, I use the `geany` GUI editor to keep notes, and it runs as a regular user (not root), and it's never had an issue with alt-tab and it's cursor appearing and being usable straight away.

@kovidgoyal it would be great if you could ruminate on this further as to what kitty might be  doing different than other programs like `geany`? Thanks! :-)

**Comment by kovidgoyal** [comment]
No clue you would need to ask the developers of the window manager that wslg uses. Again in wayland focus is not something managed by applications, it is managed by the compositor. Only the developers of th ecompositor can tell you why it is behaving in a particular way.

**Comment by ofseed** [comment]
Yes, as @kovidgoyal mentioned, this is definitely a WSLg issue. I previously found that WSLg has its own logic to match Windows windows with Linux windows. The focus cannot be captured because you focused on the Windows window, but WSLg cannot match the corresponding Linux window to focus on it. The failure of this logic will also cause windows of gtk >= 4.12 applications to be unable to close on WSLg, which behaves very strangely. See https://github.com/microsoft/wslg/issues/1265 .
