### ISSUE TITLE
When splitting to create a new panel, the previous panel will flash.

### ISSUE THREAD

**Issue by tumarsh** [kovidgoyal/kitty#6953]
**Describe the bug**

When splitting to create a new panel, the previous panel will flash.

**To Reproduce**

use these map config
 ```
map ctrl+space>e launch --location=hsplit --cwd=current
map ctrl+space>i launch --location=vsplit --cwd=current
```

open nvim then do split you will see a flash in  nvim...

**Screenshots**

https://github.com/kovidgoyal/kitty/assets/112620329/ee54dfda-d5a4-44d5-81dc-f4735727e76b

**Environment details**

sry my keybord Fx is broken ..which command  kitty --debug-gl kitty --debug-font-back I only saw these commands.

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
kitty has no control over how nvim chooses to redraw the screen on
resize. nvim should use the atomic updae exscape codes to ensure flicker
free redrawing.

**Comment by tumarsh** [comment]
hello i just tried open window without any  binary file. the  previous window zsh prompt moves to the left when I split the window . it's not fixed.

**Comment by tumarsh** [comment]
tried with wezterm there is no issue on wezterm. so could you please rethink of it..

**Comment by tumarsh** [comment]
i am pretty sure because it's not fixed caused neovim redraw. if it's fixed there is no problem.  you can do split see the left window. i have zsh with prompt theme notice it moves to left a little when i do split.  in fact panel should be fixed . even i create a new split prev panel shouldn't move ... thanks

**Comment by kovidgoyal** [comment]
it will move because the amount of padding changes, when the window size
is not an exact multiple of cell size. If you dont like
that set placement_strategy in kitty.conf to top-left instead of the
default of center.

**Comment by tumarsh** [comment]
thanks i tried it yep zsh prompt not move . but neovim still flash like redraw .. i don't know why then. neovim side a member tell me it works fine in tmux. so i tried tmux . no problem.

**Comment by kovidgoyal** [comment]
That will be because tmux is slow so it causes the draw commands to batch up. As I said, nvim needs to use the proper atomic update escape codes when drawing the screen, without that whether an update appears atomic or not to the user depends on the speed of the various underlying components.

**Comment by tumarsh** [comment]
thanks .but i still thought is wired when split ... i don't know how neovim redraw screen..
