### ISSUE TITLE
new_tab on session_file only run once

### ISSUE THREAD

**Issue by tumarsh** [kovidgoyal/kitty#6955]
**Describe the bug**
I create a session file when startup kitty . and it have two new_tabs commands. but only run once.

**To Reproduce**

```
launch nvim

new_tab 2

new_tab 3
```
use this in seesion file

**Screenshots**
 no need maybe

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
That's because you have not launched anything in your second tab. So
kitty assumes its a unneeded tab and merges into into tab 3

**Comment by tumarsh** [comment]
thansk can i force create it.

**Comment by kovidgoyal** [comment]
```
new_tab 2
launch
new_tab 3
```

**Comment by tumarsh** [comment]
that's cool. thank you. another question i found after i run some commands tab2 tab3 auto removed. can i keep them always on unless i delete this shell   like <C-d> etc
