### ISSUE TITLE
macOS: "Q" button does not emit "release" event in extended keyboard mode

### ISSUE THREAD

**Issue by dottedmag** [kovidgoyal/kitty#6956]
**Describe the bug**

Under macOS letter "Q" does not emit "release" event in extended keyboard mode. Yes, I know it sounds very weird.

**To Reproduce**
1. Open new Kitty window
2. `kitten show-key -m kitty`
3. Press and release "W" button, observe "press" and "release" events
6. Press and release "Q" button, observe one "press". If you try it again, you'll get "repeat" event.

**Screenshots**
![Screenshot 2023-12-29 at 18 58 35](https://github.com/kovidgoyal/kitty/assets/16120/d586d796-b549-446d-b503-ab95f0b373e8)

**Environment details**
```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin mm.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.2 BuildVersion:		23C64
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/dottedmag/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select               clipboard
cursor_blink_interval        0.1
disable_ligatures            2
enable_audio_bell            False
font_family                  Liberation Mono
font_size                    12.0
initial_window_height        (25, 'cells')
initial_window_width         (80, 'cells')
kitty_mod                    shift+cmd
macos_option_as_alt          2
macos_traditional_fullscreen True
remember_window_size         False
resize_in_steps              True
scrollback_lines             4294967295
select_by_word_characters    :@-./_~?&=%+#;$[]<>*^(){},
tab_bar_style                separator
tab_separator                 
update_check_interval        0.0
visual_bell_duration         0.1
window_padding_width         FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
Added shortcuts:
	shift+page_down →  scroll_page_down
	shift+page_up →  scroll_page_up
Removed shortcuts:
	shift+cmd+- →  change_font_size all -2.0
	shift+cmd+= →  change_font_size all +2.0
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+w →  close_os_window
Changed shortcuts:
	kitty_mod+[ →  previous_tab
	kitty_mod+] →  next_tab
	kitty_mod+w →  close_os_window
Colors:
	cursor                       #999999   
	foreground                   #ffffff   
	selection_background         #9bcaff   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.5P2HpQadA6/org.xquartz:0
	USER                                dottedmag
```

**Additional context**

- Works the same with `kitty --config NONE`
- I managed to get a release event for "Q" button by switching to another application.
- The effect can be seen in other layouts too: if you install Dvorak, switch to it and press "X" keyboard button (that emits "Q" letter), you'll get the same behaviour.

**Comment by dottedmag** [comment]
Here's the excerpt from `--debug-input`:

```
---------------- key down -------------------
NSEvent: type=KeyDown loc=(393.18,195.16) time=1325430.5 flags=0x100 win=0x11f70af30 winNum=60453 ctxt=0x0 chars="w" unmodchars="w" repeat=0 keyCode=13
Press: native_key: 0xd (w) glfw_key: 0x77 mods: none char_count: 1 deadKeyState: 0 repeat: 0 
	insertText: w replacementRange: (9223372036854775807, 0)
text: 0x77 glfw_key: w marked_text: ()
on_key_input: glfw key: 0x77 native_code: 0xd action: PRESS mods: none text: 'w' state: 0 sent key as text to child: w
----------------- key up --------------------
NSEvent: type=KeyUp loc=(393.18,195.16) time=1325430.6 flags=0x100 win=0x11f70af30 winNum=60453 ctxt=0x0 chars="w" unmodchars="w" repeat=0 keyCode=13
Release: native_key: 0xd (w) glfw_key: 0x77 mods: none 
on_key_input: glfw key: 0x77 native_code: 0xd action: RELEASE mods: none text: '' state: 0 ignoring as keyboard mode does not support encoding this event
---------------- key down -------------------
NSEvent: type=KeyDown loc=(393.18,195.16) time=1325431.6 flags=0x100 win=0x11f70af30 winNum=60453 ctxt=0x0 chars="q" unmodchars="q" repeat=0 keyCode=12
keyDown triggered global macOS shortcut ignoring
Press: native_key: 0xc (q) glfw_key: 0x71 mods: none char_count: 1 deadKeyState: 0 repeat: 0 
	insertText: q replacementRange: (9223372036854775807, 0)
text: 0x71 glfw_key: q marked_text: ()
on_key_input: glfw key: 0x71 native_code: 0xc action: PRESS mods: none text: 'q' state: 0 sent key as text to child: q
----------------- key up --------------------
NSEvent: type=KeyUp loc=(393.18,195.16) time=1325431.7 flags=0x100 win=0x11f70af30 winNum=60453 ctxt=0x0 chars="q" unmodchars="q" repeat=0 keyCode=12
keyUp ignored as corresponds to previous keyDown that triggered a shortcut
```

I don't know of any "global shortcuts" installed on bare "Q" on my machine. At least the letter works just fine everywhere.

**Comment by kovidgoyal** [comment]
Doesnt replicate on my mac running

kitty --config=NONE kitten show-key -m kitty

pressing and releasing q both generate the expected events. Does it replicate for you with --config NONE?

**Comment by kovidgoyal** [comment]
And look in the full --debug-input log for a line like keyDown triggerred global something..

**Comment by dottedmag** [comment]
> Does it replicate for you with --config NONE?

Yes, it does. I guess I have got _something_ that installed a global shortcut on a Q plus some modifiers, and Kitty's heuristic "leave useful global shortcuts alone" triggers on that, however I can't think of any hotkeys with Q I have ever created. Global Cmd-Q and Cmd-Shift-Q are still present, I haven't touched them, but they should be present on every Mac anyway.

I have quit everything that might have created any shortcuts (Karabiner Elements, AltTab, 1Password, Hammerspoon, OmniFocus), and it still happens.

**Comment by kovidgoyal** [comment]
The relevant code is in cocoa_init.m line 826 onwards. There is no
heuristic IIRC, it asks cocoa to perform the key equivalent onthe global
menu bar and if it does its marked as s hortcut. Additionally some well
known apple shortcuts see the function is_useful_apple_global_shortcut()
in which the only Q based one is fn+Q

**Comment by dottedmag** [comment]
I think I have found the culprit:
- System Preferences -> Keyboard -> Keyboard Shortcuts -> Mission Control -> Enable/Disable Quick Note shortcut.

It's got its weird "globe" modifier, probably that's the reason why Kitty triggered on a plain "Q" without modifiers.

**Comment by kovidgoyal** [comment]
That's the fn or "globe" key that I mentioned in the last post.

**Comment by kovidgoyal** [comment]
and it is enabled in my mac as well but doesnt cause any issues.
