### ISSUE TITLE
Feature suggestion: rounded corners/border radius

### ISSUE THREAD

**Issue by ev0rtex** [kovidgoyal/kitty#696]
I have been running a patched version of iTerm2 on my mac system for awhile that allows me to have a radius on the corners of the terminal window when I have the title bar hidden. I'm curious if this would be possible to implement in kitty. Here's a screenshot of my iTerm2 window:
<img width="1210" alt="screen shot 2018-07-02 at 11 47 15 am" src="https://user-images.githubusercontent.com/1640672/42179333-cbb7b8a2-7df0-11e8-94f8-f219d24885ea.png">
I know some people probably don't care about something like this but I find it quite aesthetically pleasing.

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but I am willing to consider a patch, providing it does not have negative performance implications/interfere with other terminal features such as transparency.

**Comment by HobbinHood** [comment]
Previously (prior #1127) there had been a toggle `macos_hide_titlebar`. Did this do exactly what it was named like, meaning not displaying the titlebar only and leaving the border window decoration intact?
If so, bringing back this flag would add rounded corners automatically, because of the default mac border window decoration.

Or has this been consolidated, since it removed all of window decorations anyhow and my whole idea is non-sense?

**Comment by kovidgoyal** [comment]
As far as I recall it hid everything.

**Comment by Luflosi** [comment]
Yes, as discussed in #1106, `macos_hide_titlebar` hid all the window decorations. And if you look at https://github.com/kovidgoyal/kitty/commit/53166d659e2c7dd236e66a1d5f514f6ff0d43db2, you can see, that this commit didn't change any of the actual functionality to hide the window decorations.

**Comment by lucaorio** [comment]
+1 to this. It'd be great to have an option to hide the titlebar while keeping intact the border radius, especially on macOS.

**Comment by Luflosi** [comment]
In case you guys are still interested and haven't seen it yet, I added an option to do this in January, see #2286 and https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.hide_window_decorations.

**Comment by nyxtom** [comment]
@Luflosi Is there anyway to also add functionality to allow the window to be dragged around without the titlebar? Alacritty has this kind of functionality so I was curious if something like that could be implemented for kitty?

**Comment by Luflosi** [comment]
Most macOS apps seem to support being dragged around at any of the four window borders but I have no clue how to implement this in kitty. If anyone knows, feel free to make a PR.

**Comment by nyxtom** [comment]
@Luflosi It looks like this behavior actually works if you have focused another application prior to attempting to drag the top area of the window. It causes Kitty to have focus and you can move the window around. It just doesn't appear to work when the window already has focus is all.

**Comment by Luflosi** [comment]
It appears that I didn't test this properly last time. This totally works for me, I just have to drag at a right angle to the resize direction. This is how it works in all other applications I tested too. I didn't have any issues with focusing like you described.
