### ISSUE TITLE
Get Error When piping  `kitty @ ls` to Neovim

### ISSUE THREAD

**Issue by jam1015** [kovidgoyal/kitty#6960]
**Describe the bug**

The Command `kitty @ ls` can be piped to programs like `cat`, `less`, `more` and `bat`.  When piping to `nvim --clean` I get the error

`Error: i/o timeout`. 

This also occurs when `nvim --clean` is the last in a pipeline.

The issue could be with Neovim and not Kitty. Making a [bug report over there](https://github.com/neovim/neovim/issues/26814) as well. 

**To Reproduce**
1. Open a default instance of Kitty with remote control enabled.  From Alacritty I go: `kitty --config NONE -o allow_remote_control=yes`
2. In that instance of Kitty, go `kitty @ ls | nvim --clean` or `kitty @ ls | cat | nvim --clean`
3. After a long pause, that gives the error `Error: i/o timeout`. 
4.  Note that the problem does not occur when piping to other programs like `kitty @ ls | cat`
I can cat other files 

**Environment details**

```
kitty 0.31.0 created by Kovid Goyal
Linux jmtp 6.6.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:17:26 +0000 x86_64
Arch Linux 6.6.2-zen1-1-zen (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control yes

Important environment variables seen by the kitty process:
	PATH                                /home/jordan/.asdf/shims:/opt/asdf-vm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/Users/jordanmandel/.local/bin:/Users/jordanmandel/bin:/Users/jordanmandel/.local/bin:/Users/jordanmandel/bin
	LANG                                en_US.UTF-8
	VISUAL                              /home/jordan/.visual_editor.bash
	EDITOR                              nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                jordan
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      1
	XDG_SESSION_TYPE                    tty
	XDG_VTNR                            1

```

Nvim version 0.9.4.

**Comment by kovidgoyal** [comment]
you have two programs doing I/O simultaneously to the same terminal
device. That wont work. Use a socket for remote control.
