### ISSUE TITLE
kitty as flatpak on flathub?

### ISSUE THREAD

**Issue by briandipalma** [kovidgoyal/kitty#6965]
I'm trying to transition all my desktop applications to containers/flatpaks so it would be nice if kitty was available as a flatpak. I realize there is a performance impact but I notice wezterm is available as a flatpak and it receives about a 100 installs a day so clearly I'm not the only person willing to sacrifice performance for immutability/ease of upgradability.

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in flatpaks. kitty is already available as
a self contained binary, use it.
