### ISSUE TITLE
configure option to quit broadcast mode

### ISSUE THREAD

**Issue by xeon123** [kovidgoyal/kitty#6974]
I am using kitty in ubuntu with xfce terminal. When I try to quit broadcast mode in kitty with ctrl+esc, it shows me the menu of xfce.
I'm am trying to configure another key (e.g., kitty_mod+c or ctrl+f1) to quit broadcast mode in kitty.conf.
Unfortunately, the only option available is the default ctrl+esc.

I have tried different configuration in kitty.conf, but all of them fail. 

![image](https://github.com/kovidgoyal/kitty/assets/173446/1df1b1b0-3f72-4c3c-9486-1118b1c5e1af)

Why not allow to map another key to exit broadcast mode?

**Comment by nemonein** [comment]
@xeon123, I've found the way.

on kitty.conf,

```
map f1 launch --allow-remote-control kitty +kitten broadcast --end-session alt+esc
```
For me, `Ctrl`+`F1` does not work, but `Alt`+`Esc` or `Alt`+`F1` does.
