### ISSUE TITLE
soft-hyphen (U+00AD) ignored?

### ISSUE THREAD

**Issue by bukzor-sentryio** [kovidgoyal/kitty#6978]
**Describe the bug**

When a soft-hyphen (AKA U+00AD or `&shy;`) is printed to kitty, it is (evidently) treated as a zero-width space. This leaves naive curses programs (cough, vim) with erroneous UI, as a cell is reserved for `&shy;`, and the character is naively handed to kitty for printing, but kitty does not print any character to the cell reserved for it. The result is "ghosting" of prior output in cells occupied by a soft-hyphen character.

The screenshots show this behavior, below.

**To Reproduce**
1. create shy.txt
```console
$ xxd -r > shy.txt <<EOF
00000000: 3230 203e 3ec2 adc2 adc2 adc2 adc2 adc2  20 >>...........
00000010: adc2 adc2 adc2 adc2 adc2 adc2 adc2 adc2  ................
00000020: adc2 adc2 adc2 adc2 adc2 adc2 ad0a c2ad  ................
00000030: c2ad c2ad c2ad c2ad c2ad c2ad c2ad c2ad  ................
00000040: c2ad c2ad c2ad c2ad c2ad c2ad c2ad c2ad  ................
00000050: c2ad c2ad c2ad 3c3c 2032 300a 3230 203e  ......<< 20.20 >
00000060: c2ad c2ad c2ad c2ad c2ad c2ad c2ad c2ad  ................
00000070: c2ad c2ad c2ad c2ad c2ad c2ad c2ad c2ad  ................
00000080: c2ad c2ad c2ad c2ad 3c20 3230 0a         ........< 20.
EOF
```
2. cat shy.txt -- note `&shy;` is treated as zero-width space
3. vim shy.txt, do some editting (press `ddp` to swap first and second line)
4. note rendering artifacts

**Screenshots**

Actual:­­
<img width="277" alt="Screenshot 2024-01-06 at 6 28 41 PM" src="https://github.com/kovidgoyal/kitty/assets/112430378/9e0882c2-032c-413b-9b21-d29dc9e8b106">

Expected:
<img width="276" alt="image" src="https://github.com/kovidgoyal/kitty/assets/112430378/25e56a87-de53-4445-a74e-75d9f396c7a7">

The "Expected" was obtained by simply backgrounding (`ctrl+z`) then foregrounding (`fg`) the same vim session.

**Environment details**

You can see I attempted to make U+00AD behave better via `narrow_symbols` and via `symbol_map`, but they did nothing. The situation is unchanged with `kitty -c NONE`.

```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin jnpyxr75kj.lan 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.6 BuildVersion:		22G120
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/buck/.config/kitty/kitty.conf

Config options different from defaults:
cursor_text_color       None
font_family             Inconsolata Nerd Font Mono
font_size               17.0
narrow_symbols:
{(173, 173): 1}
scrollback_lines        1000000
symbol_map:
	U+00ad - U+00ad → PT Mono Bold
Colors:
	<snip: I'm using https://github.com/wdomitrz/kitty_gruvbox_theme /> 

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                buck
```

**Additional context**
> Try to reproduce the problem with `kitty --config NONE` ...

Yes, it reproduces under these conditions too. I'm running no tmux, no ssh, nothing that could interfere with rendering.

**Suggested fix**
The built-in MacOS Terminal renders `&shy;` as a plain-old hyphen. While not conforming to unicode standards, this is much more usable for viewing and editting data.

<img width="236" alt="Screenshot 2024-01-07 at 4 20 26 PM" src="https://github.com/kovidgoyal/kitty/assets/112430378/dcaca3c7-ee50-486c-b8c9-c94c070fb6b2">

**Comment by kovidgoyal** [comment]
Deviating from the unicode standards just leads to chaos. Now every terminal application has to not only conform to the standard but an arbitrary list of per terminal exceptions to it. So I'm afraid this is not going to happen. Editors/pagers/text display tools should use a standard conforming implementation of wcswidth(), that's the only sane way forward.

**Comment by bukzor-sentryio** [comment]
Filed upstream with neovim, at https://github.com/neovim/neovim/issues/26945

I agree your approach is absolutely the right way forward in the long term, but in the short term it means that this is the only unicode character that makes some tools unusable, in kitty but not "worse" terminals. Do you have any suggestions or ideas for short-term solutions?

**Comment by kovidgoyal** [comment]
Run a filter to remove/replace the soft hyphens when opening the file in your
editor.
