### ISSUE TITLE
Password Perplexity

### ISSUE THREAD

**Issue by Bubba-Bubba** [kovidgoyal/kitty#6982]
Konsole running zsh works fine.

In Kitty, running zsh, my passwords do not work. I have disabled Starship, but it makes no difference. 

> **Environment details**
> kitty 0.31.0 created by Kovid Goyal
> Linux dd 6.6.9-1-default #1 SMP PREEMPT_DYNAMIC Tue Jan  2 07:19:30 UTC 2024 (61d1d44) x86_64
> Welcome to openSUSE Tumbleweed 20240106 - Kernel 6.6.9-1-default (/dev/tty).
> 
> wlp2s0: 4{wlp2s0} 6{wlp2s0}
> 
> 
> Running under: X11
> Frozen: False
> Paths:
>   kitty: /usr/bin/kitty
>   base dir: /usr/lib64/kitty
>   extensions dir: /usr/lib64/kitty/kitty
>   system shell: /usr/bin/zsh
> Loaded config files:
>   /home/marcus/.config/kitty/kitty.conf
> 
> Config options different from defaults:
> allow_remote_control yes
> enabled_layouts      ['horizontal']
> font_size            23.0
> Added shortcuts:
> 	ctrl+down →  neighboring_window down
> 	ctrl+left →  neighboring_window left
> 	ctrl+right →  neighboring_window right
> 	ctrl+up →  neighboring_window up
> 	f4 →  launch --location=split
> 	f5 →  launch --location=hsplit
> 	f6 →  launch --location=vsplit
> 	f7 →  layout_action rotate
> 	shift+down →  move_window down
> 	shift+left →  move_window left
> 	shift+right →  move_window right
> 	shift+up →  move_window up
> Changed shortcuts:
> 	kitty_mod+down →  layout_action move_to_screen_edge bottom
> 	kitty_mod+left →  layout_action move_to_screen_edge left
> 	kitty_mod+right →  layout_action move_to_screen_edge right
> 	kitty_mod+up →  layout_action move_to_screen_edge top
> Colors:
> 	background           #282420   
> 	color0               #111417   
> 	color1               #c84134   
> 	color10              #97e035   
> 	color11              #dfd561   
> 	color12              #5ed9ff   
> 	color13              #ff9168   
> 	color14              #83ef88   
> 	color15              #f6f6ec   
> 	color2               #84c44b   
> 	color3               #f4ae2e   
> 	color4               #1397b9   
> 	color5               #d0623c   
> 	color6               #4f9452   
> 	color7               #e5c5a9   
> 	color8               #665e54   
> 	color9               #ff6459   
> 	cursor               #f6f6ec   
> 	foreground           #e5c6a8   
> 	selection_background #111417   
> 	selection_foreground #282420   
> 
> Important environment variables seen by the kitty process:
> 	PATH                                /home/marcus/.local/bin:/home/marcus/bin:/usr/local/bin:/usr/bin:/bin
> 	LANG                                fr_FR.UTF-8
> 	SHELL                               /usr/bin/zsh
> 	DISPLAY                             :0
> 	USER                                marcus
> 	XCURSOR_SIZE                        24
> 	XDG_DATA_DIRS                       /home/marcus/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
> 	XDG_RUNTIME_DIR                     /run/user/1000
> 	XDG_CONFIG_DIRS                     /home/marcus/.config/kdedefaults:/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg
> 	XDG_CURRENT_DESKTOP                 KDE
> 	XDG_SEAT                            seat0
> 	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
> 	XDG_SESSION_CLASS                   user
> 	XDG_SESSION_DESKTOP                 KDE
> 	XDG_SESSION_ID                      1
> 	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
> 	XDG_SESSION_TYPE                    x11
> 	XDG_VTNR                            2
> 
> 
>

**Comment by kovidgoyal** [comment]
passwords in what? And not sure what this has to do with the terminal.
The terminal or shell doesnt process passwords whatever software you are running 
that wants a password processes it. When such software malfunctions
typically, the causes are some env var or the other. Start with TERM,
LANG, TERMINFO, LC_*, PATH, USER and HOME.

**Comment by Bubba-Bubba** [comment]
Thanks Kovid. 
GPT was clueless initially, but your prompts elicited some more meaningful suggestions.

Finally, after much head scratching, the problem is the ^ symbol in my password.

kitty handles it differently to konsole, so I need, for some obscure reason, to press it twice in kitty.

Super terminal by the way. On Plasma, I get all the functionality I need, so bravo, thank you Kovid
