### ISSUE TITLE
hyperlink detection go across newline when the newline is at terminal edge

### ISSUE THREAD

**Issue by iacore** [kovidgoyal/kitty#6986]
**Describe the bug**

the link span across multiple lines but it shouldn't be

https://github.com/kovidgoyal/kitty/assets/74560659/4175798c-ff55-4b99-949c-95d7ae9ea867

**To Reproduce**
1. Resize the terminal
2. Type the text in the screencast, with newline exactly at end of line, and some more text after that
3. Ctrl+Click on the link.

**Additional context**
Can be reproduced with `kitty --config NONE`.

**Comment by trygveaa** [comment]
This is intentional, as some full screen programs insert a newline character at the end of each line even if the line wraps.

To disable it, see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.url_excluded_characters

**Comment by iacore** [comment]
is it possible to only accept \n in alternate screen?
