### ISSUE TITLE
`cursor none` does not work on macos

### ISSUE THREAD

**Issue by Song-Tianxiang** [kovidgoyal/kitty#6987]
**Describe the bug**
I have set `cursor none` in config file, but it not work on macOS

**To Reproduce**
1. Put `cursor none` in config file and reload kitty, cursor color does not get reverse video effect

**Screenshots**
![Screen Shot 2024-01-11 at 00 05 10](https://github.com/kovidgoyal/kitty/assets/149415622/a794aa55-425b-4efc-9ae3-05ec0c030847)

**Environment details**
```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin Yus-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Jul  6 22:18:26 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.6.8 BuildVersion:	21G725
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/fish
Loaded config files:
  /Users/yufei/.config/kitty/kitty.conf

Config options different from defaults:
background_blur          25
cursor_blink_interval    0.0
font_family              IBM Plex Mono
font_size                26.0
initial_window_height    (800, 'px')
initial_window_width     (1280, 'px')
macos_custom_beam_cursor True
macos_option_as_alt      3
remember_window_size     False
sync_to_monitor          False
Colors:
	active_border_color      #81a1c1   
	active_tab_background    #88c0d0   
	active_tab_foreground    #3b4252   
	background               #2e3440   
	bell_border_color        #88c0d0   
	color0                   #3b4252   
	color1                   #bf616a   
	color10                  #a3be8c   
	color11                  #d08770   
	color12                  #5e81ac   
	color13                  #b48ead   
	color14                  #8fbcbb   
	color15                  #eceff4   
	color2                   #a3be8c   
	color3                   #ebcb8b   
	color4                   #81a1c1   
	color5                   #b48ead   
	color6                   #88c0d0   
	color7                   #e5e9f0   
	color8                   #4c566a   
	color9                   #bf616a   
	cursor                   #d8dee9   
	cursor_text_color        #3b4252   
	foreground               #d8dee9   
	inactive_border_color    #4c566a   
	inactive_tab_background  #4c566a   
	inactive_tab_foreground  #e5e9f0   
	mark1_background         #88c0d0   
	mark1_foreground         #3b4252   
	mark2_background         #bf616a   
	mark2_foreground         #3b4252   
	mark3_background         #ebcb8b   
	mark3_foreground         #3b4252   
	selection_background     #434c5e   
	selection_foreground     #d8dee9   
	tab_bar_background       #3b4252   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /usr/local/bin/fish
	USER                                yufei

```

**Additional context**

**Comment by kovidgoyal** [comment]
works for me. Remember that reverse video is only for block cursors, not
bar or underline or box cursors.

**Comment by larkinrt** [comment]
I had a similar issue and found that when I have a theme enabled the cursor matches whatever the theme dictates. For example, if I change my theme in nvim internally, the cursor matches whatever kitty's theme is and doesn't change.

`cursor none` only has an effect when placed below the code loaded by `kitten themes`. I assume this is the problem @Song-Tianxiang was having looking at the screenshot.

**Comment by Song-Tianxiang** [comment]
> I had a similar issue and found that when I have a theme enabled the cursor matches whatever the theme dictates. For example, if I change my theme in nvim internally, the cursor matches whatever kitty's theme is and doesn't change.我遇到了类似的问题，发现当我启用主题时，光标会匹配主题指示的任何内容。例如，如果我在 nvim 内部更改我的主题，光标会与小猫的主题匹配并且不会改变。
> 
> `cursor none` only has an effect when placed below the code loaded by `kitten themes`. I assume this is the problem @Song-Tianxiang was having looking at the screenshot. `cursor none` 仅当放置在 加载 `kitten themes` 的代码下方时才有效。我认为这是看截图的问题。

Thank you. I put `cursor none` after `kitten themes` and it works now. Maybe we can mention it on doc.
