### ISSUE TITLE
Printing text over an image does not display said text

### ISSUE THREAD

**Issue by mfontanini** [kovidgoyal/kitty#6988]
**Describe the bug**
When you print an image, then move the cursor back, and print text on top of the image, the text is not visible. I would expect printing `A` over a cell that already contains `B` would always display `A`, and this is the case if `B` is text, but not if it's a piece of an image.

I tried this on wezterm and the behavior there is what I'd expect. If you're wondering the rational behind this issue, I'm building a [modal-like view on top of some text/images](https://github.com/mfontanini/presenterm/pull/128). The modal works as expected when the screen only contains text but it shows up behind images when those are present.

**To Reproduce**
Reproduce this using rust:

```shell
cargo new --bin kitty-images
```

* Edit `Cargo.toml`:

```toml
[package]
name = "kitty-images"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
viuer = "0.7.1"
```

* Edit `src/main.rs`:

```rust
use std::io::stdout;

fn main() {
    viuer::print_from_file("kitty.png", &Default::default()).expect("kitty.png not found");
    crossterm::execute!(stdout(), crossterm::cursor::MoveTo(0, 0)).unwrap();
    println!("{}", "A".repeat(150)); // print lots
    // print just a bit, to showcase that the above will overflow to the right of the image but this won't
    println!("{}", "B".repeat(10)); 
    println!("{}", "C".repeat(10));
}
```

* Create a `kitty.png` file (I used the kitty logo but anything will do).
* `cargo run`

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/969090/04ef145a-79ad-4947-b785-46a31ca05ea8)

**Environment details**
```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Linux hello 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64
Linux Mint 21.2 Victoria hello /dev/tty

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.2
DISTRIB_CODENAME=victoria
DISTRIB_DESCRIPTION="Linux Mint 21.2 Victoria"
Running under: X11
Frozen: True
Paths:
  kitty: /home/matias/.local/kitty.app/bin/kitty
  base dir: /home/matias/.local/kitty.app/lib/kitty
  extensions dir: /home/matias/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /home/matias/.config/kitty/kitty.conf

Config options different from defaults:
click_interval            0.5
cursor_blink_interval     0.5
editor                    lvim
enable_audio_bell         False
font_family               Fantasque Sans Mono
font_size                 12.0
initial_window_height     (1800, 'px')
initial_window_width      (3200, 'px')
mouse_hide_wait           0.0
remember_window_size      False
scrollback_lines          10000
scrollback_pager          ['less', '+G', '-R']
select_by_word_characters :@-./_~?&=%+#
shell_integration         frozenset({'no-cursor'})
tab_bar_style             slant
tab_title_max_length      40
window_border_width       (0, 'pt')
```

**Additional context**
This also happens when running kitty with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
You need to set the z-index of the image correctly.
https://sw.kovidgoyal.net/kitty/graphics-protocol/

**Comment by mfontanini** [comment]
Would you consider a mode where print order is the tie breaker? This puts more burden on us when building apps that print images/text. wezterm's default behavior feels a lot saner IMO.

**Comment by kovidgoyal** [comment]
No.

**Comment by mfontanini** [comment]
Thanks!

**Comment by mfontanini** [comment]
Can you please explain how would I get the desired behavior if I cleared the screen using some background color, then I drew an image, and finally I printed text on top of it? This seems to be what you would normally do in cases where you have a modal, e.g. you clear the screen, paint some stuff, and then draw the modal on top of it.

If I use a z-index below `INT_MIN/2`, the image won't show up at all because it seems to be behind the clear screen's background. e.g. it's stacked as `image / background / text`.

If I use a z-index < 0 but above that threshold, I see the image is in between the background and the text, meaning I see the text but the text's background behind the image. e.g. `background / image / text`.

What I would need to get is `background / image / text_with_background`. You can reproduce this using this:

```python
import sys
from base64 import standard_b64encode


# --- this is copied from https://sw.kovidgoyal.net/kitty/graphics-protocol/#a-minimal-example
def serialize_gr_command(**cmd):
    payload = cmd.pop("payload", None)
    cmd = ",".join(f"{k}={v}" for k, v in cmd.items())
    ans = []
    w = ans.append
    w(b"\033_G"), w(cmd.encode("ascii"))
    if payload:
        w(b";")
        w(payload)
    w(b"\033\\")
    return b"".join(ans)


def write_chunked(**cmd):
    data = standard_b64encode(cmd.pop("data"))
    while data:
        chunk, data = data[:4096], data[4096:]
        m = 1 if data else 0
        sys.stdout.buffer.write(serialize_gr_command(payload=chunk, m=m, **cmd))
        sys.stdout.flush()
        cmd.clear()


# -----------------------------------------------------------------------------


def move_cursor(x, y):
    cmd = "\x1b[{};{}H".format(y, x)
    sys.stdout.write(cmd)
    sys.stdout.flush()


def set_bg_color():
    cmd = "\x1b[41m"
    sys.stdout.write(cmd)
    sys.stdout.flush()


def clear_screen():
    cmd = "\x1b[2J"
    sys.stdout.write(cmd)
    sys.stdout.flush()


def run_example(image_path):
    x = 0
    y = 0
    offset = 5
    set_bg_color()
    clear_screen()

    # draw some text with red background
    for i in range(10):
        move_cursor(x, y + i)
        print("this is some text on top of the image")

    # draw image at an offset
    move_cursor(x + offset, y + offset)

    # Negative z-index values below INT32_MIN/2 (-1,073,741,824) will be drawn under cells with non-default background colors.
    INT32_MIN_2 = -1_073_741_824
    z = INT32_MIN_2 + 1 # play with this line <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

    with open(image_path, "rb") as f:
        write_chunked(a="T", f=100, data=f.read(), z=z)


# path to a png image:
image_path = "kitty.png"

run_example(image_path)
```

**Comment by kovidgoyal** [comment]
You cannot, there are not multiple layers of background color, which is what you are asking for. Use a semi-transparent image with z=-1 as your background, then you will get it blending with the background color giving you a distinct visual appearance for your modal region and draw text on top of it. You will of course need to erase any previously existing text in the region, otherwise that too will appear on top of the modal background.

**Comment by mfontanini** [comment]
Thanks, this should work.

However, I think you really should reconsider the logic here for z-index 0. In that z-index, where text lives, there's currently inconsistent/surprising behavior: text can overwrite text on the same cell but images can't be overwritten. I've tested this in other terminals (includiing wezterm using sixel, iterm2 _and_ the kitty graphics protocol) and they all do what I expect so I don't imagine I can be that off on my expectations here.

It's nice that there's a workaround but I don't think I should have to go to these lengths to do something this simple. Note that I'm referring specifically to z-index 0 here, the behavior in other indexes sounds sensible.

**Comment by kovidgoyal** [comment]
As I said before, no. kitty graphics are not cell based, for very good
reasons, discussed at length when the spec was designed. WezTerm's
kitty graphics implementation is full of bugs including this one.
