### ISSUE TITLE
Opening kitty window with tabs running apps at i3 startup

### ISSUE THREAD

**Issue by klozamarek** [kovidgoyal/kitty#6989]
I am looking for a way to open a kitty window with several tabs running different apps inside them. I want this window to load when i3 starts up. I have allow_remote_control set to "yes" and listen_on set to "unix:/tmp/kitty" in kitty.config file. I cannot manage to set proper commands in i3/config file. I can open kitty window allright using:
exec no-startup-id kitty
but have not found a way to open new tabs and launch apps inside them. Any help would be appreciated.

**Comment by kovidgoyal** [comment]
Use kitty sessions.
