### ISSUE TITLE
Remove "::zsh" from menu bar

### ISSUE THREAD

**Issue by smartinellimarco** [kovidgoyal/kitty#6995]
**Is your feature request related to a problem? Please describe.**

I would like to be able to remove this "::zsh" button in the MacOS menu bar.

<img width="388" alt="Screenshot 2024-01-14 at 21 41 38" src="https://github.com/kovidgoyal/kitty/assets/15314838/d5b18ea7-6ee5-4348-999a-60cc32cd6f0b">

You can make it appear by opening and then closing a new kitty window

**Describe the solution you'd like**

I'd rather not have it by default, since it does nothing when you click it.

**Describe alternatives you've considered**

I tried removing it with the the menu_map option without success.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_show_window_title_in
