### ISSUE TITLE
stty iutf8

### ISSUE THREAD

**Issue by egmontkob** [kovidgoyal/kitty#70]
In UTF-8 mode, start a `cat`. Type a few accented characters, e.g. `áéíóöőúüű`, then press backspace a couple of times (let's say four times). Press Enter.

Expected behavior: The same row is echoed back.

Actual behavior: Not all the letters were removed from the kernel's line buffer, hence more letters appear in the echoed response than in the input row.

The solution is to set the IUTF8 flag of the terminal (in UTF-8 mode only, of course).

**Comment by kovidgoyal** [comment]
Is this actually the terminal emulators responsibility? Shouldn't UTF-8 producing applications do this? And if the terminal emulator does this, how does it work with the fact that there can be multiple programs running in the same terminal emulator, some of which may or maynot be UTF-8 aware.

**Comment by kovidgoyal** [comment]
Also, this seems to be linux specific, it is not in POSIX and as far as I can tell is not implemented in OS X: http://www.manpages.info/macosx/termios.4.html

**Comment by kovidgoyal** [comment]
On deeper investigation it does seem to be present on OSX as well: https://github.com/st3fan/osx-10.9/blob/master/xnu-2422.1.72/bsd/sys/termios.h#L133

Probably worth doing to emulate behavior of xterm/vte

**Comment by egmontkob** [comment]
Other terminal emulators set it as well. This option is primarly important for those tools that leave the terminal in canonical mode, that is, don't even care whether their standard input is a terminal or not. It's unreasonable for such utilities to fiddle with terminal settings. Thanks for addressing this issue!
