### ISSUE TITLE
ZSH anchor based matching active, cannot complete

### ISSUE THREAD

**Issue by cpiber** [kovidgoyal/kitty#7002]
I understand based on the comment in the source code, that supporting this behavior is not planned:
https://github.com/kovidgoyal/kitty/blob/22dbc94c5fdb3b829b9f8ce8dab92c217eec25ad/tools/cli/zsh.go#L57-L67

Would it be possible to mention this in the FAQ? Especially since Oh-my-zsh offers the setting `CASE_SENSITIVE`, which when set to true will trigger this line.

Actually I think the comment is wrong, since the omz will always add a matcher, and the one I (should) have now more closely matches the error case described: https://github.com/ohmyzsh/ohmyzsh/blob/c0074974313215360a9529e01204792cdf6ca473/lib/completion.zsh#L17-L25

**Comment by kovidgoyal** [comment]
How is the comment wrong? Your OMZ default matcher spec is
'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|=*' 'l:|=* r:|=*'

which effectively means only the m matcher is defined in the $_matcher, 
not any of l, r, b or e for completions. Which is what the condition
checks. The Debian one uses 'r:|[._-]=*' which means r shows up as well.
r:|=* appends * to the match pattern which doesnt break completion and
doesnt show up in $_matcher

Matchers change the meaning of the completion candidates, which will
break completion, but only in specific circumstances. ZSH doesnt have a
mechanism that I have found to prevent this breakage.

I'm afraid this isn't a common enough issue to merit a mention in the
FAQ, which is pretty long already :)

**Comment by cpiber** [comment]
I see, thank you, I misread what the issue was.

I think plenty of people will use omz if they use zsh, but it's your decision of course :)
