### ISSUE TITLE
[RFC] New 2x faster escape code parser using vector CPU instructions

### ISSUE THREAD

**Issue by kovidgoyal** [kovidgoyal/kitty#7005]
Hi all,

I've spent the last few months working on and off on a new escape code parser for kitty, that uses vector CPU instructions (AVX2 or SSE 4.2 or their ARM equivalents, whatever is available) to greatly speed up parsing of the input byte stream. This has led to speedups with throughput for parsing different kind of input data of between 50% to 400%. 

There is a new benchmarking kitten that can be used to benchmark terminal performance as well. The benchmark results from running `kitten __benchmark__` on my system with kitty master branch and vt branch (the latter has the new code):

master branch:
```
Results:
  Only ASCII chars         : 4.55s      @ 43.9    MB/s
  Unicode chars            : 2.73s      @ 64.9    MB/s
  CSI codes with few chars : 3.56s      @ 28.1    MB/s
  Long escape codes        : 8.12s      @ 96.5    MB/s
  Images                   : 10.06s     @ 53.0    MB/s
```

vt branch with SIMD acceleration:
```
Results:
  Only ASCII chars         : 1.73s      @ 115.7   MB/s
  Unicode chars            : 1.78s      @ 99.5    MB/s
  CSI codes with few chars : 1.76s      @ 56.7    MB/s
  Long escape codes        : 2.39s      @ 327.9   MB/s
  Images                   : 1.97s      @ 270.8   MB/s
```

A table comparing the results from the vt branch with other terminal emulators I have on my system is at https://github.com/kovidgoyal/kitty/blob/vt/docs/performance.rst#throughput showing kitty is much faster than the rest with the new code.

There are of course some downsides, most importantly, the new code required fairly invasive changes to various parts of kitty so its likely some edge cases are broken. In particular kitty no longer supports input data in non utf-8 encodings and also does not support C1 control codes. The latter are supported only by VTE based terminals and WezTerm out of the box, so they are not widely used.

I'd appreciate if some of you could build kitty from source and help
test things for regressions. Building kitty from source is very easy you
need only C and Go compilers and to run a single command, instructions are at: https://sw.kovidgoyal.net/kitty/build/

Please report any issues you find here.

Thanks, and enjoy!

P.S. For the curious, the things that have been sped up are:

1) Searching for the start and end of escape codes in the input byte stream
2) UTF-8 decoding via SIMD instructions
3) base64 decoding via SIMD instructions (base64 is used for various
escape codes such as images, copy/paste, etc.)
4) SIMD XOR used for securely storing image frame data in a disk cache

Currently I have restricted the SIMD implementations to AVX2 at max, not
AVX512 as that tends to have a major energy/warm up penalty and prevents
running on "economy cores". Something to revisit in the future.

**Comment by EgZvor** [comment]
In what cases is this change perceivable?

**Comment by kovidgoyal** [comment]
On Tue, Jan 16, 2024 at 11:56:58PM -0800, Egor Zvorykin wrote:
> In what cases is this change perceivable?

Depends on what you do in your terminal. Anything that requires
processing lots of data fast, will be faster.

**Comment by EgZvor** [comment]
Will this improve Vim redrawing speed?

**Comment by kovidgoyal** [comment]
It will, indeed my original motivation for making kitty was the horrible performance of vim in the terminals at the time. However, whether you notice *this particular change* or not as a human, depends on your vim config, terminal window size, how sensitive you are to noticing such things, etc.

**Comment by neurocyte** [comment]
Impressive numbers! I have tried a few basic tests and it is definitely faster. Up to 30% with the craziest pixel pushing test case I tried and around 10% when just scrolling large amounts of text. Nice!

In regular use kitty is really never the bottle neck in anything I do, but it should be a nice little bit of battery/CPU saving though.

I have been using a build from the vt branch all afternoon and have not seen any kind of regression so far. 👍

**Comment by mikesmithgh** [comment]
This is awesome. Should this build on MacOS?
```
ProductName: macOS
ProductVersion:	14.2.1 
BuildVersion: 23C71
```

I am receiving the following error:
```
./dev.sh build
[1/1] Compiling kitty/simd-string.c ... done
Compiling kitty/simd-string.c ...
clang -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=31 -DXT_VERSION="0.31.0" -DGL_SILENCE_DEPRECATION -I/Users/mike/go/src/github.com/kovidgoyal/kitty/dependencies/darwin-arm64/include -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-
errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -D_FORTIFY_SOURCE=2 -mbranch-protection=standard -fno-plt -flto -pthread -I/Users/mike/go/src/github.com/kovidgoyal/kitty/dependencies/darwin-arm64/include/libpng16 -I/Users/mike/go/src/github.com/kovidgoyal/kitty/dependen
cies/darwin-arm64/include -I/Users/mike/go/src/github.com/kovidgoyal/kitty/dependencies/darwin-arm64/include -I/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/T/t/openssl,x86_64,-5kbzhdrp/include -I/Users/mike/go/src/github.com/kovidgoyal/kitty/dependencies/darwin-arm64/include/harfbuzz -I/Users/mike
/go/src/github.com/kovidgoyal/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/3.9/include/python3.9 -c kitty/simd-string.c -o build/fast_data_types-kitty-simd-string.c.o
In file included from kitty/simd-string.c:13:
kitty/simd-string-impl.h:18:10: fatal error: 'simde/x86/avx2.h' file not found
#include <simde/x86/avx2.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
The following build command failed: /Users/mike/go/src/github.com/kovidgoyal/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/Current/bin/python3 setup.py develop
exit status 1
```

**Comment by kovidgoyal** [comment]
It will work on macOS, you just need to update your copy of the dependencies,  with `./dev.sh deps`

**Comment by mikesmithgh** [comment]
> It will work on macOS, you just need to update your copy of the dependencies, with `./dev.sh deps`

thanks, that worked

**Comment by ad-chaos** [comment]
I'm getting broken rendering when running the vt branch on my M1 mac.

with the following zshrc
```zsh
PS1="%% "

export KEYTIMEOUT=1
bindkey -v

autoload -Uz compinit
compinit
zmodload zsh/complist

zstyle ':completion:*' menu select
bindkey -M menuselect '^[' send-break
```
and the following `kitty.conf`
```
font_family      Inconsolata Medium
bold_font        Inconsolata SemiBold
italic_font      Inconsolata Light
bold_italic_font Inconsolata SemiBold
font_size 20
```
create a window with `50x20` cells , cd into the kitty repository and `ls` to somewhat fill the entire screen, then `cd <Tab>` and navigate to any menu item and press escape to see some items from the ls output disappear. 

https://github.com/kovidgoyal/kitty/assets/90276965/220fe2da-af1a-48f3-b772-65508ebebadc

And sometimes all output is immediately cleared on my terminal, though I was unable to make a reproducer for it.

https://github.com/kovidgoyal/kitty/assets/90276965/6256fe3f-0069-4a4b-9221-99a058692c2a

**Comment by kovidgoyal** [comment]
@ad-chaos Can you please run kitty with --dump-bytes and do minimal steps to reproduce the problem and post the dump alongwith the window size in cells you reproduced at. Your steps arent reproducing on my M2 mac.

**Comment by ad-chaos** [comment]
[dumped-bytes.log](https://github.com/kovidgoyal/kitty/files/13991689/dumped-bytes.log)

The window size was `50x20` cells

**Comment by kovidgoyal** [comment]
@ad-chaos: Thanks, with that I can see a difference between master and
vt, will investigate more when I have a moment.

**Comment by kovidgoyal** [comment]
@ad-chaos Fixed by https://github.com/kovidgoyal/kitty/commit/12b684edee136cc1ad63221efd0fc2d76ac8fa85

**Comment by ad-chaos** [comment]
I can confirm the problem no longer exists on nightly.

**Comment by dalizard** [comment]
@kovidgoyal I imagine this improvement would have no impact if you are in a tmux session?

**Comment by kovidgoyal** [comment]
On Tue, Jan 23, 2024 at 01:15:40PM -0800, Dimitar Haralanov wrote:
> @kovidgoyal I imagine this improvement would have no impact if you are in a tmux session?

Speed wise, no since your performance will be limited by tmux not kitty.
But kitty will still use less energy to parse whatever tmux sends it.

**Comment by ces42** [comment]
I'm seeing pretty high idle cpu usage on my build of this branch. It constantly hovers around 3-4% on an empty terminal prompt (as opposed to 0.00% for the master branch).

**Comment by kovidgoyal** [comment]
On Tue, Jan 23, 2024 at 09:54:16PM -0800, Carlos Esparza wrote:
> I'm seeing pretty high idle cpu usage on my build of this branch. It constantly hovers around 3-4% on an empty terminal prompt (as opposed to 0.00% for the master branch).

OK, will look at it when I have a moment. Probably unrelated to the SIMD
code, some of the render loop was re-written for additional speedups as
well.

**Comment by p7r0x7** [comment]
Love to see that you're regularly improving this!

**Comment by kovidgoyal** [comment]
On Tue, Jan 23, 2024 at 09:54:16PM -0800, Carlos Esparza wrote:
> I'm seeing pretty high idle cpu usage on my build of this branch. It constantly hovers around 3-4% on an empty terminal prompt (as opposed to 0.00% for the master branch).

Fixed by https://github.com/kovidgoyal/kitty/commit/8c0607b8e09b97376491dd5c151d3dd04b190cd2

**Comment by up-to-you** [comment]
Everything that is TUI should benefit from vt, isn't it ?
I use [`bottom` ](https://github.com/ClementTsang/bottom) with .5sec refresh rate and 8 widgets (quite enough load i think for the case), should it consume less cpu now ?

**Comment by kovidgoyal** [comment]
yes.

**Comment by kovidgoyal** [comment]
A further 5% improvement in the benchmark with https://github.com/kovidgoyal/kitty/commit/f1d70622af7d97ace534336d714cefbf604914ba

**Comment by kovidgoyal** [comment]
A further 5% improvement in the benchmark with https://github.com/kovidgoyal/kitty/commit/f1d70622af7d97ace534336d714cefbf604914ba

**Comment by ces42** [comment]
Here's a bug: write just "⚠️" into a text file. Then opening the file with vim (9.0) or neovim (lastest master) shows what looks like a file with just one space.

**Comment by kovidgoyal** [comment]
On Thu, Feb 01, 2024 at 07:33:44PM -0800, Carlos Esparza wrote:
> Here's a bug: write just "⚠️" into a text file. Then opening the file with vim (9.0) or neovim (lastest master) shows what looks like a file with just one space.

Nice catch:
https://github.com/kovidgoyal/kitty/commit/b02f3f6231e8ff97f4066a8608c44ca29b06a2d1

Although technically, this was both a bug in the vt branch and in vim.
vim doesnt realize that the character is wide because it is a default
narrow character + emoji variation selector codepoint, which presumably
vim doesnt support. So vim was incorrectly positioning the cursor on the
second cell of the wide character and then issuing more commands, which
exposed the regression in the vt branch in turn.

**Comment by brandonfouts** [comment]
Heads up that the current build on vt branch is not working (pulled from repo just now). Here's what I get when I run a ./dev.sh/build:

```clang -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=32 -DXT_VERSION="0.32.1" -DGL_SILENCE_DEPRECATION -I/.../dev/kitty/dependencies/darwin-arm64/include -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -D_FORTIFY_SOURCE=2 -fno-plt -flto -mbranch-protection=standard -pthread -I/.../dev/kitty/dependencies/darwin-arm64/include/libpng16 -I/.../dev/kitty/dependencies/darwin-arm64/include -I/.../dev/kitty/dependencies/darwin-arm64/include -I/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/T/t/openssl,x86_64,-5kbzhdrp/include -I/.../dev/kitty/dependencies/darwin-arm64/include/harfbuzz -I/.../dev/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/3.11/include/python3.11 -c kitty/simd-string-256.c -o build/fast_data_types-kitty-simd-string-256.c.o
In file included from kitty/simd-string-256.c:9:
kitty/simd-string-impl.h:260:5: error: call to undeclared function '_mm256_zeroupper'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    zero_upper();
    ^
kitty/simd-string-impl.h:92:20: note: expanded from macro 'zero_upper'
#define zero_upper _mm256_zeroupper
                   ^
kitty/simd-string-impl.h:645:5: error: call to undeclared function '_mm256_zeroupper'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    zero_upper();
    ^
kitty/simd-string-impl.h:92:20: note: expanded from macro 'zero_upper'
#define zero_upper _mm256_zeroupper
                   ^
2 errors generated.
The following build command failed: /....../kitty/dependencies/darwin-arm64/python/Python.framework/Versions/Current/bin/python3 setup.py develop
exit status 1```

**Comment by kovidgoyal** [comment]
Should be fixed by: https://github.com/kovidgoyal/kitty/commit/e1e932e56b0cddac336ceac00298bbf7b8c408a7

**Comment by erikolofsson** [comment]
https://github.com/kovidgoyal/kitty/commit/40e8ade9a2f5140a124ceda76f207ee3ef9f9103 causes my bash to not load the profile.

**Comment by kovidgoyal** [comment]
On Sun, Feb 11, 2024 at 01:45:53AM -0800, Erik Olofsson wrote:
> https://github.com/kovidgoyal/kitty/commit/40e8ade9a2f5140a124ceda76f207ee3ef9f9103 causes my bash to not load the profile.

Dont see how that's possible unless you have KITTY_RUNNING_BASH_INTEGRATION_TEST
set in your environment?

**Comment by kovidgoyal** [comment]
Never mind, this should take care fo it: https://github.com/kovidgoyal/kitty/commit/e5565e5567b951e17b124bfbbe323c9984c9b42a

**Comment by brandonfouts** [comment]
Latest go 1.22 dependency is throwing the following error on builds in the vt branch. This is on Mac 14.3.1:

`go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available`

**Comment by kovidgoyal** [comment]
On Sun, Feb 11, 2024 at 07:44:16PM -0800, brandonfouts wrote:
> Latest go 1.22 dependency is throwing the following error on builds in the vt branch. This is on Mac 14.3.1:
> 
> `go: downloading go1.22 (darwin/arm64)
> go: download go1.22 for darwin/arm64: toolchain not available`

Update your version of go to 1.22

**Comment by mikesmithgh** [comment]
I use lpass (https://github.com/lastpass/lastpass-cli) and noticed the box characters are incorrect on the `vt` branch.

- `vt` `c3e5b31a8`
![lpass-vt](https://github.com/kovidgoyal/kitty/assets/10135646/bd6099df-cde6-4cea-9e2e-d349bacdd8ba)

- `v0.32.2`
![lpass-0-32-2](https://github.com/kovidgoyal/kitty/assets/10135646/aed55683-5f5f-40d5-8bf3-c108dabeea8a)

#### Steps to reproduce (using MacOS `14.2.1 (23C71)`)
- install lpass (https://github.com/lastpass/lastpass-cli)
- run `lpass login test` `// you don't need to have a real account to reproduce`

**Comment by kovidgoyal** [comment]
No clue about that. From your screenshot it looks like lpass has decided to not use box drawing characters on the vt branch.
![screenshot](https://github.com/kovidgoyal/kitty/assets/1308621/fc70b42a-8ce6-4f69-b72b-042b701c97e4)
  And on my system I get no box drawn at all in either master or vt by lastpass-cli 1.3.5

**Comment by brandonfouts** [comment]
I get a similar issue as @mikesmithgh when using gopass - in this case it's just using GPGs password prompt..

Here's the vt branch:

![Screenshot 2024-02-11 at 23 00 26](https://github.com/kovidgoyal/kitty/assets/134417205/71b85c77-81dd-45ce-ae08-5b78abf9a3d2)

Here's the master branch:
![Screenshot 2024-02-11 at 23 01 37](https://github.com/kovidgoyal/kitty/assets/134417205/73e5310d-4d71-4435-9cef-231ad59ec0dd)

**Comment by kovidgoyal** [comment]
What actual program is this? gpg-pinentry-curses doesnt look anything like that.

**Comment by brandonfouts** [comment]
My screenshot is from gopass (https://github.com/gopasspw/gopass). It uses GnuPG for storing/retrieving the master password. If I call GnuPG to say export that master key I get the same sort of pin entry screen with the mangled border.

**Comment by kovidgoyal** [comment]
What gnupg command are you using?

**Comment by brandonfouts** [comment]
There's likely an easier command to get the pinentry screen but this will work:

`gpg --output private.pgp --armor --export-secret-key YOUR_EMAIL@ADDRESS_FOR_YOUR_KEY`

**Comment by kovidgoyal** [comment]
Doesnt reproduce for me with that command. And yes easier way to run gpg pinentry is via pinentry-curses or pinentry-tty

**Comment by kovidgoyal** [comment]
To be precise

pinentry-curses
then type GETPIN and enter

**Comment by kovidgoyal** [comment]
Ah, I know what's going on. This is just the execrable ncurses as usual. Set

export NCURSES_NO_UTF8_ACS=1

in your shell and you will be fine. I have had this set in my environment for years so it didnt reproduce for me. The underlying issue is that the vt branch has dropped support for non-UTF8 encodings, which ncurses still uses without that env var.

**Comment by kovidgoyal** [comment]
And it should be fixed by this: https://github.com/kovidgoyal/kitty/commit/c3a6404264c2b8d55f2b21c9040f25097459c8b0

**Comment by mikesmithgh** [comment]
> And it should be fixed by this: [c3a6404](https://github.com/kovidgoyal/kitty/commit/c3a6404264c2b8d55f2b21c9040f25097459c8b0)

confirmed: fixed the lpass issue for me 👍

**Comment by mikesmithgh** [comment]
OK I have a weird one.

Background: when I am in a git repo, my PROMPT_COMMAND executes a function calling some git commands to show data in the PS1 prompt.

Problem: If the git command takes too long, the PS1 prompt does not show up until I type a key

I reproduced this by adding a small delay to the PROMPT_COMMAND via `sleep 0.2`.

os: MacOS 14.2.1 (23C71)
bash: GNU bash, version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)

#### Steps to reproduce:
- `bash --noprofile --norc`
- `PROMPT_COMMAND='sleep 0.2'`
- `PS1='$ '`
- `echo hi`

#### Actual:
- The PS1 does not show on the next line until I press a key

#### Expected: 
- The PS1 prompt shows after the command executes

#### Demo:

https://github.com/kovidgoyal/kitty/assets/10135646/3220e95a-cf20-47c5-9426-d4a4f59c49ef

**Comment by kovidgoyal** [comment]
Doesnt repro for me, but given its timing dependent thats not too
surprising. Can you run kitty with --dump-bytes and post the dump file
after running echo hi and waiting a couple of seconds. Also post the
output of
tput cols lines
So I can try to reproduce on a same size window.

**Comment by mikesmithgh** [comment]
#### Input commands:
```
PROMPT_COMMAND='sleep 0.2'
PS1='$ '
echo hi
kitty --version
tput cols
tput lines
exit
```


#### kitty `v0.32.2`:
`kitty --dump-bytes kitty-session-0-32-2.txt`

output of --dump-bytes: [kitty-session-0-32-2.txt](https://github.com/kovidgoyal/kitty/files/14314569/kitty-session-0-32-2.txt)
output of stdout: [kitty-commands-0-32-2.txt](https://github.com/kovidgoyal/kitty/files/14314567/kitty-commands-0-32-2.txt)
output of tput cols: 105 
output of tput lines: 47

#### kitty vt `472f57705` :
`./kitty/launcher/kitty --dump-bytes kitty-session-vt.txt`
output of --dump-bytes: [kitty-session-vt.txt](https://github.com/kovidgoyal/kitty/files/14314570/kitty-session-vt.txt)
output of stdout: [kitty-commands-vt.txt](https://github.com/kovidgoyal/kitty/files/14314568/kitty-commands-vt.txt)
output of tput cols: 105 
output of tput lines: 47

I ran the same commands against `v0.32.2` and the `vt` branch. The `--dump-bytes` file looks odd on the `vt` branch. It has repeating characters vs `v0.32.2`.

For example,

kitty-session-0-32-2.txt#7:
```
^[[?2004h$ tput cols
```

vs

kitty-session-vt.txt#13:
```
^[[?2004h$ ttppuuttt  ccoollss
``` 

@kovidgoyal Let me know if you need anything else to troubleshoot.

**Comment by kovidgoyal** [comment]
That was a bug in the --dump-bytes implementation, fixed by: https://github.com/kovidgoyal/kitty/commit/58d1f082c53fa92e9c3fb89c035115cdab374ddf

But I still cannot reproduce your actual issue. Can you do the following:

1) To the top of ~/.bashrc add
```sh
PROMPT_COMMAND='sleep 0.2'
PS1='$ '
return
```

Update to tip of vt branch and then run kitty as
```
kitty --config=NONE --dump-bytes=dump.txt -o shell_integration=disabled -o shell=bash -o confirm_os_window_close=0
```

type echo hi and press enter
wait a couple of seconds and quit kitty by pressing cmd+q 

Then post dump.txt

**Comment by mikesmithgh** [comment]
> That was a bug in the --dump-bytes implementation, fixed by: [58d1f08](https://github.com/kovidgoyal/kitty/commit/58d1f082c53fa92e9c3fb89c035115cdab374ddf)
> 
> But I still cannot reproduce your actual issue.

Hey @kovidgoyal, It looks like it is fixed 🤷! I can no longer produce the issue on `22a0b96e00`. I'll let you know if I run into it again, but I don't think I will be cause it was consistently reproducible before. Thanks!

**Comment by kovidgoyal** [comment]
Probably this one: https://github.com/kovidgoyal/kitty/commit/a2b20ba9cd5d9905e7c84593da91c66360a590ce

fixed it.

**Comment by kovidgoyal** [comment]
Thanks to everyone for your testing. This is now merged into master as there are no outstanding reported issues.

**Comment by Safari77** [comment]
`./dev.sh build` works but `make linux-package` results into `kitty/simd-string-impl.h:35:10: fatal error: simde/x86/avx2.h: No such file or directory` error.

Fedora 39 x86_64.

**Comment by kovidgoyal** [comment]
You need to install simde, new dependency.

**Comment by kovidgoyal** [comment]
If you want to build it without dev.sh then you are using system tools
and you need to install it system wide.

**Comment by kovidgoyal** [comment]
Closing as this has been released in kitty 0.33

**Comment by moderation** [comment]
> If you want to build it without dev.sh then you are using system tools and you need to install it system wide.

With the new `simde` dependency requirement I can no longer build on SUSE Tumblewood. `./dev.sh deps` followed by `./dev.sh build` returns 
```
/bin/sh: /home/moderation/Library/kitty/dependencies/linux-amd64/lib/libreadline.so.8: no version information available (required by /bin/sh)
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_set_timeout, version READLINE_8.2
The package libcrypto was not found on your system
The following build command failed: /home/moderation/Library/kitty/dependencies/linux-amd64/bin/python setup.py develop
exit status 1
```
and the manual build process which used to work fails with 
```
kitty/simd-string-impl.h:35:10: fatal error: simde/x86/avx2.h: No such file or directory
   35 | #include <simde/x86/avx2.h>
      |          ^~~~~~~~~~~~~~~~~~
```
I can't find `simde` in the Tumbleweed packages and wondering if I need to build this from source?

**Comment by SolitudeSF** [comment]
> I can't find simde in the Tumbleweed packages and wondering if I need to build this from source?
`simde` is header only. `python3 setup.py -Ipath-to-simde` should work. just point it to simde include directory that `dev.sh deps` fetches.

**Comment by moderation** [comment]
There is zero urgency on this and I'm happy to noodle around to get it working again. I successfully built with an Ubuntu machine so this looks Tumbleweed specific.

Using @SolitudeSF 's tip I'm now successfully building `kitty` with `env CPPFLAGS="-I./dependencies/linux-amd64/include" LDFLAGS="-I./dependencies/linux-amd64/lib" make --jobs (nproc)`

I'm hitting an other error now and will keep debugging
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/moderation/Library/kitty/kitty/launcher/../../__main__.py", line 7, in <module>
    main()
  File "/home/moderation/Library/kitty/kitty/launcher/../../kitty/entry_points.py", line 194, in main
    from kitty.main import main as kitty_main
  File "/home/moderation/Library/kitty/kitty/launcher/../../kitty/main.py", line 11, in <module>
    from .borders import load_borders_program
  File "/home/moderation/Library/kitty/kitty/launcher/../../kitty/borders.py", line 7, in <module>
    from .fast_data_types import BORDERS_PROGRAM, add_borders_rect, get_options, init_borders_program, os_window_has_background_image
ImportError: /home/moderation/Library/kitty/kitty/launcher/../../kitty/fast_data_types.so: undefined symbol: EVP_CIPHER_CTX_block_size
```

**Comment by moderation** [comment]
Worked it out
`sudo ln -fs /home/moderation/Library/kitty/dependencies/linux-amd64/lib/libcrypto.so.1.1 /usr/lib64/libcrypto.so.1.1`
`env CC='gcc' CXX='g++' python3.12 setup.py --verbose -I./dependencies/linux-amd64/include -L./dependencies/linux-amd64/lib`

**Comment by mcourteaux** [comment]
wow, I just updated and the speed difference is real. I can feel it's faster in my Vim on a large monitor. Amazing work!

**Comment by aaronlifton** [comment]
I now use neovim in Kitty instead of Neovide, it is the smoothest experience by far for me.

**Comment by michaelfortunato** [comment]
Yeah, in view, Kitty is perceptually much faste than Neovide. Can anyone conjecture why this might be the case? It seems counterintuitive, but I really think moving in Kitty feels faster than Neovide.
