### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [kovidgoyal/kitty#701]
I would like to point out that an identifier like “[`__glad_h_`](https://github.com/kovidgoyal/kitty/blob/bf0dcb1d2eea9f5923828371b2bb9b8c23b008e5/kitty/gl-wrapper.h#L21 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by kovidgoyal** [comment]
That comes from the glad project, report the issue to them https://github.com/Dav1dde/glad

**Comment by elfring** [comment]
How much do you care that bundled software components are standard-compliant for the usage in your tool?

**Comment by kovidgoyal** [comment]
That is not a bundled software component, that is a generated bindings file generated by glad, as you would know if you had bothered to read the header in that file.

**Comment by kovidgoyal** [comment]
I dont think about it. You are wasting your time and mine. For the last time, the correct place to report this is in the glad project.
