### ISSUE TITLE
Make a new KITTY_ARCH variable available for conf includes

### ISSUE THREAD

**Issue by lespea** [kovidgoyal/kitty#7019]
**Is your feature request related to a problem? Please describe.**
Brew has different paths for x86 and arm and since I'm setting the shell and editor to programs within brew, I currently have to use symlinks to get it to work on both architectures.  Ideally I would be able to split the conf into an arm and an x86 version and import them based on the architecture of the machine.

**Describe the solution you'd like**
Similar to how KITTY_OS can be used in an include statement, make KITTY_ARCH (or equivalent) available as well.

**Describe alternatives you've considered**
I can continue using symlinks.

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
Seems like too niche a use case. You can instead set an env var globally
based on arch and include conditionally using that. Be sure to set it in
launchd otherwise kitty wont see it.
