### ISSUE TITLE
fcf-protection change breaks build on armv7 and i586

### ISSUE THREAD

**Issue by kekePower** [kovidgoyal/kitty#7026]
**Describe the bug**
The change made in commit 1c72a94b2f2c652bc388e06ca21e67fe881e7dc2 breaks build on i586 and armv7hl.

armv7hl message:
```cc1: error: '-fcf-protection=full' is not supported for this target```

i586 message:
```cc1: error: '-fcf-protection' is not compatible with this target```

**To Reproduce**
armv7hl build log: https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20240119170236.kekepower.duvel.2706159/kitty-0.32.0-1.mga10/build.armv7hl.0.20240119170249.log
i586 build log: https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20240119170236.kekepower.duvel.2706159/kitty-0.32.0-1.mga10/build.i586.0.20240119192340.log

**Screenshots**
N/A

**Environment details**
This in the Mageia Cauldron Build System.

**Additional context**
N/A

**Comment by solopasha** [comment]
It also breaks on ppc64le and s390x

**Comment by classabbyamp** [comment]
can reproduce this when cross-compiling from x86_64 to arm on Void Linux. Looks like it assumes that host arch == target arch for arm at least: https://github.com/kovidgoyal/kitty/blob/v0.32.0/setup.py#L52
