### ISSUE TITLE
Using remote control with the send-text command sends text twice

### ISSUE THREAD

**Issue by konomikitten** [kovidgoyal/kitty#7027]
**Describe the bug**

Using remote control with the send-text command sends text twice.

**To Reproduce**
1. kitty --config=NONE --override allow_remote_control=yes --listen-on unix:/tmp/kitty &
2. kitty @ --to unix:/tmp/kitty set-tab-title One
3. kitty @ --to unix:/tmp/kitty send-text -t "title:One" 'One'

**Screenshots**

![Screenshot_2024-01-21_00-04-18](https://github.com/kovidgoyal/kitty/assets/12713710/f83e9d02-61fa-408d-9fd1-cf687623b50a)

**Environment details**
```
kitty 0.32.0 created by Kovid Goyal
Linux debian 6.6.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.11-1 (2024-01-14) x86_64
Debian GNU/Linux trixie/sid debian /dev/tty

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control yes

Important environment variables seen by the kitty process:
	PATH                                /home/strawberry/.cargo/bin:/home/strawberry/.npm-packages/bin:/home/strawberry/.local/share/gem/ruby/3.1.0/bin:/home/strawberry/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
	LANG                                en_AU.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/bash
	DISPLAY                             :0.0
	USER                                strawberry
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     xfce-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 lightdm-xsession
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm/data/strawberry
	XDG_CURRENT_DESKTOP                 XFCE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/xfce4:/home/strawberry/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Does nto replicate for me with those steps. From your screen shot I am guessing your shell is responsible for the doubling. Try running it like this

```sh
kitty --config=NONE --override allow_remote_control=yes --listen-on unix:/tmp/kitty cat &
kitty @ --to unix:/tmp/kitty send-text -m id:1 One
```

**Comment by konomikitten** [comment]
> Does nto replicate for me with those steps. From your screen shot I am guessing your shell is responsible for the doubling. Try running it like this
> 
> ```shell
> kitty --config=NONE --override allow_remote_control=yes --listen-on unix:/tmp/kitty cat &
> kitty @ --to unix:/tmp/kitty send-text -m id:1 One
> ```

The bug is specifically with sending to the title of a tab not the id. Running what you provided works correctly. Running this sends the text twice still:

```txt
kitty --config=NONE --override allow_remote_control=yes --listen-on unix:/tmp/kitty cat &
kitty @ --to unix:/tmp/kitty set-tab-title One
kitty @ --to unix:/tmp/kitty send-text -t title:One One
```

Downgrading back to 0.31.0 fixes the issue.

**Comment by LaptopDev** [comment]
kitty 0.38.1-1:
```
laptop:~$ kitty @ send-text "test"
testlaptop:~$ test
```

**Comment by kovidgoyal** [comment]
```sh
kovid getafix ~/work/kitty $ kitty @ send-text test
kovid getafix ~/work/kitty $ test
```

**Comment by LaptopDev** [comment]
ran in fresh horizontal pane:
```
laptop:~$ kitty @ send-text test
testlaptop:~$ test
```
created a new vertical split changes the output in said pane:
```
laptop:~$ kitty @ send-text test
laptop:~$ test
```
![Screenshot From 2025-01-12 02-42-37](https://github.com/user-attachments/assets/9c5a790c-7133-470e-aa2e-04cfe7c2a57d)
![Screenshot From 2025-01-12 02-42-19](https://github.com/user-attachments/assets/ec0b3a4c-918e-4627-aea5-05149ed75e38)

**Comment by kovidgoyal** [comment]
```
kitty --config=NONE -o enabled_layouts=vertical -o allow_remote_control=y --session <(echo "launch\nlaunch") -o shell=bash
```

![screenshot](https://github.com/user-attachments/assets/51b5bc14-7a83-4f04-b760-8d61078c1a23)

**Comment by LaptopDev** [comment]
<details>
<summary>Details</summary>

laptop:~$ kitty --config=NONE -o enabled_layouts=vertical -o allow_remote_control=y --session <(echo "launch\nlaunch") -o shell=bash
[0.059] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 531, in main
    _main()
    ~~~~~^^
  File "/usr/bin/../lib/kitty/kitty/main.py", line 523, in _main
    run_app(opts, cli_opts, bad_lines, talk_fd)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/main.py", line 256, in __call__
    _run_app(opts, args, bad_lines, talk_fd)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/main.py", line 216, in _run_app
    startup_sessions = tuple(create_sessions(opts, args, default_session=opts.startup_session))
  File "/usr/bin/../lib/kitty/kitty/session.py", line 257, in create_sessions
    yield from parse_session(session_data, opts, environ=environ)
  File "/usr/bin/../lib/kitty/kitty/session.py", line 221, in parse_session
    raise ValueError(f'Unknown command in session file: {cmd}')
ValueError: Unknown command in session file: launch\nlaunch

laptop:~$ 

</details>


![Screenshot From 2025-01-12 02-54-15](https://github.com/user-attachments/assets/a5090209-3f81-4a26-9791-2c01358dbceb)

**Comment by kovidgoyal** [comment]
Seriously! Adjust the command for whatever shell you are using.

**Comment by LaptopDev** [comment]
`kitty --config=NONE -o enabled_layouts=vertical -o allow_remote_control=y --session <(printf "launch\nlaunch") -o shell=bash`

![Screenshot From 2025-01-12 03-20-55](https://github.com/user-attachments/assets/b29f5412-79c3-4093-9f49-5f752c8b208e)
![Screenshot From 2025-01-12 03-19-14](https://github.com/user-attachments/assets/f667516a-f67e-4205-9d9b-66c969ebd87a)


Appears to work in this window

**Comment by kovidgoyal** [comment]
This is a race between kitty sending the text and the shell resuming control of the tty after executing the send-text command. Easily demonstrated by doing:

```
kitty @ send-text test; sleep 1s;
```

You will always get doubled text. And that doubled text comes because the tty line discipline is in echo mode so the kernel echoes the text sent back to the tty and the the shell resumes control of the tty, reads the text and redraws it. 

You dont get the doubling if the shell instead wins the race and takes control of the tty and turns off echo mode before kitty sends the text.

If you want to ensure the text is always sent after the shell resumes control, do something like

```
sh -c "sleep 1s; kitten @ send-text test" &
```

instead.

**Comment by LaptopDev** [comment]
Thanks for teaching me about that. I appreciate the resolution you helped me come to quickly.

I'll prepend `stty -echo;` to `kitty @ send-text` commands then restart echo after sending text, with `stty echo`.


Might tcgetattr() and tcsetattr() system calls able to be implemented into the project?


Some pseudocode:

```
disable_echo(target_tty_fd);
send_text_to_tty(target_tty_fd, "test");
enable_echo(target_tty_fd);
```

**Comment by LaptopDev** [comment]
Hypothetical way to modify send-text.py

<details>
<summary>Details</summary>


 

```python
import tty, termios

for w in actual_windows:
    if sid:
        w.screen.render_unfocused_cursor = True
        s.window_ids.add(w.id)
    if isinstance(data, WindowSystemKeyEvent):
        kdata = w.encoded_key(data)
        if kdata:
            w.write_to_child(kdata)
    else:
        if bp == 'enable' or (bp == 'auto' and w.screen.in_bracketed_paste_mode):
            data = b'\x1b[200~' + sanitize_for_bracketed_paste(data) + b'\x1b[201~'
        
        # Disable echo mode
        tty_fd = w.get_tty_fd()  # Hypothetical method to retrieve fd
        old_settings = termios.tcgetattr(tty_fd)
        new_settings = old_settings[:]
        new_settings[3] &= ~termios.ECHO  # Clear the ECHO flag
        termios.tcsetattr(tty_fd, termios.TCSANOW, new_settings)

        # Write text
        w.write_to_child(data)

        # Re-enable echo mode
        termios.tcsetattr(tty_fd, termios.TCSANOW, old_settings)

```

 


</details>

**Comment by kovidgoyal** [comment]
send-text isnt going to change termios state, that is a completely
unexpected and possibly undesired side effect. termios is global state
and applications running in the tty can break if it is randomnly changed
from under them.

If you need to disable echo while using send text you can do so
trivially yourself using stty or similar tools.
