### ISSUE TITLE
documentation links broken inside an ssh session

### ISSUE THREAD

**Issue by ad-chaos** [kovidgoyal/kitty#7029]
**Describe the bug**
When inside an ssh session, the help output's documentation links appear broken

**To Reproduce**
1. Build kitty from source on the master branch
2. `./kitty/launcher/kitty --config NONE --allow_remote_control=yes`
3. `kitten @ detach-tab --help` and observe that the links are appropriately underlined and work
4. Then `kitten ssh` into a machine
5. `kitten @ detach-tab --help` and observe that the links are not underlined and do not work

**Screenshots**
Normally:
<img width="532" alt="Screenshot 2024-01-20 at 9 21 15 PM" src="https://github.com/kovidgoyal/kitty/assets/90276965/7a52daa0-d971-443d-a712-1764678b31ec">

Inside an SSH session:
<img width="862" alt="Screenshot 2024-01-20 at 9 22 17 PM" src="https://github.com/kovidgoyal/kitty/assets/90276965/9307e64b-a342-4082-a016-a713c2878d63">

**Comment by ad-chaos** [comment]
sorry accidentally pressed enter

**Comment by kovidgoyal** [comment]
Works for me running from current master, possibly the fix for your
other issue also fixed this.
