### ISSUE TITLE
Stream of "[PARSE ERROR] Unsupported screen mode:  1 (private)"

### ISSUE THREAD

**Issue by smprather** [kovidgoyal/kitty#7030]
When using tmux, nvim (and probably anything else that hits ncurses), I get a constant stream of these messages.

I have just installed and run. 100% out-of-box, no configuration.

I am running on a stock Redhat 8.7 VM displayed via Citrix.

kitty 0.32.0 (eb5dd364ae) created by Kovid Goyal
Running under: X11
Frozen: True
Paths:
  kitty: /proj/cot_globals/tools/foss/kitty/0.32.0/bin/kitty
  base dir: /proj/cot_globals/tools/foss/kitty/0.32.0/lib/kitty
  extensions dir: /proj/cot_globals/tools/foss/kitty/0.32.0/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
        PATH                                /proj/cot_globals/tools/foss/kitty/0.32.0/bin:/proj/cot_globals/bin:/app/vbuild/RHEL7-x86_64/nodejs/18.13.0/bin:/proj/asic/tools/synops>
        LANG                                C.UTF-8
        VISUAL                              vim
        EDITOR                              vim
        SHELL                               /bin/bash
        DISPLAY                             seroiuvd01790:1
        USER                                epramyl
        XDG_SESSION_ID                      4
        LC_COLLATE                          C
        XDG_DATA_DIRS                       /home/epramyl/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
        LC_MESSAGES                         C
        XDG_RUNTIME_DIR                     /run/user/7477102
        LC_TIME                             C

Thanks Kovid!

**Comment by kovidgoyal** [comment]
Not sure what the issue is? If you are running programs that are
outputting unsupported escape codes, you should report the bug to those
programs.
