### ISSUE TITLE
kitten @ send-key not exposed to the cli

### ISSUE THREAD

**Issue by apolopena** [kovidgoyal/kitty#7031]
**The Issue**
I would like to send key presses to another window using the kitty `kitten @ send-key` as documented [here](https://sw.kovidgoyal.net/kitty/remote-control/#kitten-send-key). 
However the command is not available:
$ `kitten @ --help | grep -A 1 "send-key"` 
outputs nothing

Is there another recommended way to send key preses to another window?
I was hoping to avoid writing my own kitten.

**To Reproduce**
$ `kitty @ send-key ctrl+a`
outputs:
`Error: send-key is not a known subcommand for @. Use --help to get a list of valid subcommands.`

**Environment details**
- _kitty version_: `0.31.0`
- _kitten version_: `0.31.0`
```conf
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	XDG_RUNTIME_DIR                     /mnt/wslg/runtime-dir
	LC_COLLATE                          C
```

**Comment by apolopena** [comment]
I found a [workaround](https://github.com/kovidgoyal/kitty/issues/1462#issuecomment-472483497). Simply send the escape character for the enter key. Thanks Kovid!
I am still wondering though why the `send-key` command is not available from the cli

**Comment by kovidgoyal** [comment]
send-key is new in 0.32.0
