### ISSUE TITLE
Nerd Font 4 bytes unicode

### ISSUE THREAD

**Issue by Mister7F** [kovidgoyal/kitty#7034]
I have the following configuration

```
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
```

It's working well for any "2 bytes unicode", but fail as soon as the unicode has 4 bytes
![image](https://github.com/kovidgoyal/kitty/assets/35213773/12e3b3a1-3119-47c2-a225-d44521396373)

**Comment by kovidgoyal** [comment]
iI have no idea what you are trying to do. \udb80 and \ude0f are not
valid unicode characters. If you want to output a non-BMP unicode
character you use something like the following:
echo "\U1f805"

**Comment by Mister7F** [comment]
@kovidgoyal I'm trying to use nerd font in kitty, to show that icon

https://www.nerdfonts.com/cheat-sheet
![image](https://github.com/kovidgoyal/kitty/assets/35213773/bb6385e7-26c4-4f62-a6bf-f9e441b964a7)

**Comment by Mister7F** [comment]
Nevermind, it was just nerdfont showing the wrong code...
with this it worked, thanks
```
echo -e '\Uf020f'
```

**Comment by ad-chaos** [comment]
The UTF button on that website copies the UTF-16 code-units to clipboard not UTF-8
