### ISSUE TITLE
Respect hyphens in kitten filenames specified in keyboard mappings

### ISSUE THREAD

**Issue by ad-chaos** [kovidgoyal/kitty#7035]
**Describe the bug**
kitty replaces all `-` with `_` when searching for a kitten specified in a map directive. Not a deal breaker but would be nice if I could have all of the be in kebab-case, like paste-actions, open-actions and a lot of kitty options are also in kebab-case.

**To Reproduce**
1. `map f1 kitten my-kitten.py`
2. open a new kitty window
3. press f1
```
kitten my-kitten.py
[Errno 2] No such file or directory: '/Users/adchaos/.config/kitty/my_kitten.py'
```

**Comment by kovidgoyal** [comment]
hyphens are not valid in python identifiers. Therefore for python
filenames, it is better to use underscore, as python filenames become
python module names which are identifiers.

**Comment by ad-chaos** [comment]
ah I see

**Comment by stelcodes** [comment]
A consequence of not allowing hyphens in filenames is that it becomes impossible to reference kitten python scripts in the Nix store when using NixOS or the Nix package manager. For example, with home-manager I tried to do this:
```nix
let
  kitty-resize-window = pkgs.writeTextFile {
    name = "kitty_resize_window.py";
    text = builtins.readFile ./kitty_resize_window.py;
  };
in
{
  programs.kitty.keymaps = {
    "kitty_mod+up" = "kitten ${kitty-resize-window} up";
  };
}
```
In the config file, this gets turned into:
```
map kitty_mod+up kitten /nix/store/vrnr1m4wxm77cn7b1lkfa0mlqvc1v11p-kitty_resize_window.py up
```
Notice the hyphen in the filename. All Nix store paths have hyphens in them separating the hash from the package name, so any kitten script in the Nix store becomes impossible to use.
