### ISSUE TITLE
Use kitty @  send-key to trigger a kitty keyboard shortcut

### ISSUE THREAD

**Issue by apolopena** [kovidgoyal/kitty#7038]
I am using Using kitty version `0.32.0`

My `kitty.conf` has the following entry:
`map f1 launch_tab`

Perhaps I just dont understand exactly how  `kitty @  send-key` works but according to the docs, I would expect this to open a new tab

$ `kitty @ send-key f1`

Instead just get an empty line which seems to happen with anything valid that I try to send.

**Comment by kovidgoyal** [comment]
send-key will send the specified key to the program running inside
kitty. Not to kitty itself.

**Comment by kovidgoyal** [comment]
And if you want to open a tab in kitty via a script you use

kitten @ launch --type=tab

**Comment by apolopena** [comment]
Thanks.
What I am really trying to is make kitty run ctrl+shift+f5 from a script ;)

**Comment by kovidgoyal** [comment]
If you want to reload the config file, simply do

kill -SIGUSR1 $KITTY_PID

**Comment by apolopena** [comment]
@kovidgoyal you are awesome, thank you so much!
