### ISSUE TITLE
Any roadmap on when kittens can update their respective environment variables on the go? Can it even be done?

### ISSUE THREAD

**Issue by excited-bore** [kovidgoyal/kitty#7042]
**Is your feature request related to a problem? Please describe.**
I don't need Tmux and I swear to you that it is not in any case related to Tmux. 

**Describe the solution you'd like**
Updating environment variables on the go would just be a nice feature.

**Describe alternatives you've considered**
The only alternative that I can think of is setting env PROGRAM= in kitty.conf, and for each subsequent opening and closing of PROGRAM, I close and relaunch a kitten devoid of foul PROGRAM environment variable. This works locally, but does not go over as well over an SSH connection though.  

**Additional context**
I love kitty, but i sometimes need a terminal multiplexer to run a thingy over SSH, then detach it and go do something else. 
And I would really like a decent solution to "Multiple pane managers" having completly seperate keybindings, and I believe this would help tremendously. What i'm doing right now is telling kitty (through a kitten) to pass the keys after being decoded based on foreground processes (for vim) and i would like the same for environment variables. However, as described [here](https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal), kitty only checks for environment variables _at launch_, wich makes a setup like the one i'm trying to get pretty if nigh impossible. 
 Even if this is a little unnecesary, having env variables that update and have kitty pick up on that behavior automagically without closing and opening your pane seems like something that's pretty practical...

**Comment by kovidgoyal** [comment]
I dont know what you are asking for, be more specific. If you mean you
want to change env vars in a shell session and then clone the shell
session with th eupdated env vars, simply run the clone-in-kitty
command.
