### ISSUE TITLE
Hints mode not working

### ISSUE THREAD

**Issue by dalizard** [kovidgoyal/kitty#7047]
**Describe the bug**
A single _kitty.conf_ with only the following line:
```
map ctrl+shift+p>f kitten hints --type path --program -
```
causes the application to freeze when the action is triggered via its shortcut. Removing the config line (or starting with `-c NONE`) does not cause a problem. This happens in kitty 0.32.0, but not in 0.30.0.

**To Reproduce**
1. Launch kitty
2. Trigger the action via Ctrl + Shift + p > f
3. kitty freezes

1. Launch kitty
2. Launch another instance of kitty by simply typing `kitty` in the shell
3. Trigger the action via Ctrl + Shift + p > f
4. In the first terminal instance you would see the following error:
```
Traceback (most recent call last):
  File "/Applications/MacPorts/kitty.app/Contents/MacOS/../Resources/kitty/kitty/boss.py", line 1406, in dispatch_possible_special_key
    mode.keymap[fa.rest[0]].append(fa.shift_sequence_and_copy())
                ~~~~~~~^^^
IndexError: tuple index out of range
```

**Screenshots**

**Environment details**
```
kitty 0.30.0 created by Kovid Goyal
Darwin Smeagol.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.3 BuildVersion:		23D56
Frozen: False
Paths:
  kitty: /Applications/MacPorts/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/MacPorts/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/MacPorts/kitty.app/Contents/Resources/kitty/kitty
  system shell: /opt/local/bin/fish
Loaded config files:
  /Users/<username>/.config/kitty/kitty.conf

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/MacPorts/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/local/bin/fish
	USER                                <username>
	LC_CTYPE                            UTF-8
```

**Additional context**
The problem is not reproducible with `kitty -c NONE`.

**Comment by dalizard** [comment]
I feel like this is something related to the installation of kitty. When building 0.32.0 from source the problem is no longer reproducible.

**Comment by kovidgoyal** [comment]
dup of #7044
