### ISSUE TITLE
Optimizations for software rendering

### ISSUE THREAD

**Issue by apolopena** [kovidgoyal/kitty#7048]
**Is your feature request related to a problem? Please describe.**
I want to daily drive Kitty in my WSL2 environment. WSL2 does not support GPU passthrough so I am stuck with software rendering. So on WSL, text rendering is really slow in a Wayland session and a little better  in an x11 session but still kind of choppy when it renders key strokes.

**Describe the solution you'd like**
Optimization in Kitty in regards to how it draws text when using software rendering.  Keystrokes are slow and especially slow when using backspace key.

**Describe alternatives you've considered**
Running X11 instead of Wayland using `linux_display_server x11` in `kitty.conf` gives me twice the speed but its still slower than other terminals in the same environment such as xfce terminal.

**Additional context**
I have a feeling this would be a good deal of work that you may not have the bandwidth or even want to do and I understand that. I was wondering if its possible and generally how much effort it would take and where to look around in the code base to add this feature in case I get inspired.

I would just put up with the performance hit in WSL's  X11 however the light theme in the window decorations for an x11 session creates quite a bit of eye strain for me. I remedy this by using Wayland and setting `wayland_titlebar_color #353935` in `kitty.conf' but then the performance hit it is just too much to daily drive.

**Comment by kovidgoyal** [comment]
Not something I am interested in. You would essentially need to rewrite
the entire rendering stack to not use OpenGL.

**Comment by apolopena** [comment]
ok how about adding something like: `x11_titlebar_color #353935` in `kitty.conf`

**Comment by kovidgoyal** [comment]
On Tue, Jan 23, 2024 at 09:25:48PM -0800, Apolo Pena wrote:
> ok how about adding something like: `x11_titlebar_color #353935` in `kitty.conf`

kitty doesnt draw the titlebar in X11
