### ISSUE TITLE
Support setting WM_WINDOW_ROLE with --role flag

### ISSUE THREAD

**Issue by dsifford** [kovidgoyal/kitty#705]
Hello there,

Currently, kitty allows the user to set `WM_NAME`, `WM_CLASS` (1), and `WM_CLASS` (0) using the flags `--title`, `--class`, and `--name`, respectively.

However, there currently appears to be no support for `WM_ROLE`. I'd like the ability to add support for this because I have settings in my window manager to make all windows with the role `pop-up` to be floating windows (and I'd like to target a specific kitty session on startup to be one of those windows).

This can obviously also be achieved with one of the above settings, but it will require one more line of configuration to my already giant wm config file.

Thanks for considering!

**Comment by kovidgoyal** [comment]
glfw, the windowing toolkit kitty uses has no API to set WM_ROLE. That makes adding support it for it to kitty, way more work than it is worth. So not worth the the effort for me, patches are welcome.

**Comment by dsifford** [comment]
Totally understand. Thanks for the clarification!

**Comment by aspiers** [comment]
8 years later, I've requested this feature in glfw.
