### ISSUE TITLE
Keyboard protocol spec: clarify associated text

### ISSUE THREAD

**Issue by rockorager** [kovidgoyal/kitty#7051]
**Is your feature request related to a problem? Please describe.**
The spec for keyboard encoding does not define what text should be considered "associated text".

**Describe the solution you'd like**
Update the spec to define what is considered "text". I'm not a unicode expert, but most libraries provide some sort of "is_printable" type function which _generally_ (from my quick perusing) is anything in the General category, sans control characters (https://www.unicode.org/reports/tr44/#General_Category_Values)

**Describe alternatives you've considered**
alacritty is the only terminal with a current [issue](https://github.com/alacritty/alacritty/issues/7657) here. Previously, wezterm had an issue but it was fixed.

**Additional context**
None

**Comment by rockorager** [comment]
I should say: my assumption is that control characters _shouldn't_ be considered as text (backspace, tab, enter as very obvious examples). Maybe that _isn't_ correct. I don't care either way, just want clarity :)

**Comment by kovidgoyal** [comment]
If you have some concerns with my fix, feel free to say so.

**Comment by kchibisov** [comment]
Should the associated text be also reported if I have a text outside the said range, but I have e.g. Alt+Shift+something pressed? I know that some users don't expect associated text when you have non-empty modifiers with the exception of shift.
