### ISSUE TITLE
kitty fails to run when OS is in FIPS mode

### ISSUE THREAD

**Issue by vroetman** [kovidgoyal/kitty#7053]
**Describe the bug**
I am running on RHEL-8 in FIPS mode, which restricts which crypto algorithms can be used. `kitty` fails to start because of this. `kitty` build was obtained from EPEL.

**To Reproduce**
1. Put Linux OS in FIPS mode (OS dependent)
2. run `kitty`
3. It produces this error for me:
```
[024 10:00:15.885011] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 477, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 469, in _main
    run_app(opts, cli_opts, prewarm, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 233, in __call__
    _run_app(opts, args, prewarm, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 211, in _run_app
    boss = Boss(opts, args, cached_values, global_shortcuts, prewarm)
  File "/usr/bin/../lib64/kitty/kitty/boss.py", line 248, in __init__
    self.encryption_key = EllipticCurveKey()
fast_data_types.CryptoError: Failed to create context for key generation: 140365534281664:error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS:crypto/evp/pmeth_lib.c:143:
```

**Additional context**
The EllipticCurveKey() functions are [hard-coded to use X25519](https://github.com/kovidgoyal/kitty/blob/90e1ba77812dde95920cd595e56c51f420b0f13e/kitty/crypto.c#L118), and this is not allowed ([see page 19 of this pdf](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3661.pdf)) with FIPS 140-2. If the specific curve was not chosen, the function may return a FIPS compliant key if the system is in FIPS mode.

**Comment by kovidgoyal** [comment]
I'm afraid I dont have any interest in implementing a different curve
for this. Use the official kitty binaries and they will work fine since
they wont be using the system openssl libraries.
