### ISSUE TITLE
[Bug or Feature Request?] Combining actions when mapping mouse (mouse_map... combine)

### ISSUE THREAD

**Issue by mojolo** [kovidgoyal/kitty#7056]
**Describe the bug**
Not sure if this is a bug or a feature request. Kitty doesn't seem able to combine actions when mapping mouse presses. If this is by design, can this feature be added?

I am trying to map `ctrl+right press` to: open a command's output in the pager (_less_); and immediately send the `/` keystroke to start a search. 
While a similar `combine` mapping works for pure keyboard bindings, it doesn't work for mouse mappings.

**To Reproduce**

1. Set the following config in `kitty.conf`:
```
mouse_map ctrl+right press ungrabbed combine : mouse_show_command_output : send_text normal,application /
```

2. Run some command with some output
3. Hold down control and right click on the output
4. The output opens up in _less_ as expected
5. **[ERROR]** But the `/` keystroke isn't sent
6. Quit _less_
7. **[ERROR]** The `/` keystroke is instead sent to the terminal command line.

**Environment details**
kitty 0.31.0 (not using 0.32.0 due to custom kb mapping bug)
zsh 5.9
Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-14-generic (64-bit)
Graphics Platform: X11

**Comment by kovidgoyal** [comment]
Works fine, as you can verify by running kitty with --debug-input. less
is probably just swallowing that keystroke during startup, use

mouse_map ctrl+right press ungrabbed combine : mouse_show_command_output : sleep 0.1 : send_key /

adjust the sleep timing to whatever feels best to you.

**Comment by mojolo** [comment]
Thanks Kovid!

FYI in case others come across this issue: the `send_key` action is new to Kitty v0.32.0.
