### ISSUE TITLE
Dump the last X scrollback lines' worth graphics buffer into a screenshot?

### ISSUE THREAD

**Issue by p7r0x7** [kovidgoyal/kitty#7057]
**Is your feature request related to a problem? Please describe.**
Wanna take proper terminal screenshots that are taller than my terminal window.

**Describe the solution you'd like**
I don't care the format of the output so long as it's losslessly encoded pixels.

**Describe alternatives you've considered**
Taking a normal screenshot obviously won't suffice.

**Additional context**
You may wish to use an image format that supports an effectively arbitrary number of pixels (like ppm or jxl), but all of my uses won't produce screenshots of more than 65536x65536 as is supported by nearly all lossless formats I know.

**Comment by p7r0x7** [comment]
I'm a CLI (and eventually TUI) dev (the cli is for a VP9 encoder, not that that's related) who's programming a TCT video encoder playable only by fast terminal emulator like kitty (that and I daily drive kitty so pls thx with love)

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but patches welcome.

**Comment by kovidgoyal** [comment]
In fact you can do this already using kitty remote control and a script.

In your script use 

kitten @ scroll-window 1p-  (or whatever amt)

take a screenshot, repeat for however many screenfulls you want, then stictch your screenshots together using something like imagemagick's convert utility.

**Comment by p7r0x7** [comment]
> Not something I am interested in personally, but patches welcome.

Where is the code that stores those buffers?

**Comment by kovidgoyal** [comment]
There's no buffer it's rendered directly on GPU
