### ISSUE TITLE
[Linux] Keyboard shortcut overrides don't work (re-map default shortcuts)

### ISSUE THREAD

**Issue by mojolo** [kovidgoyal/kitty#7058]
**Describe the bug**

Kinda similar to #7016, which effected macOS and was fixed with [this commit](https://github.com/kovidgoyal/kitty/commit/89c3b4f9e22422767fa5b18ff08a0ea317fd0687)

On Linux, re-mapping default shortcuts no longer works as expected with _kitty v0.32_ or _v0.32 nightly_. Below is a simple example, but the bug effects all of my default shortcut overrides.

**To Reproduce**

1. Add `map kitty_mod+o no_op` to `kitty.conf`
2. In `kitty v0.31.0` and previous versions, the default shortcut is removed, as expected. `kitty_mod+f6` reports:
```
Removed shortcuts:
        kitty_mod+o →  pass_selection_to_program
```
3. **[ERROR]** In `kitty v0.32.0` and later nightlies, kitty no longer removes the default shortcut. Instead, the new action (`no_op` in this case) is added (comma-seperated) to the original default action. `kitty_mod+f6` reports:
```
Changed shortcuts:
        kitty_mod+o →  pass_selection_to_program, no-op
```

**Environment details**
```
kitty 0.32.0 (828f4f312a) created by Kovid Goyal
zsh v5.9
Linux 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64
Kubuntu 23.10
Running under: X11
```

**Comment by kovidgoyal** [comment]
What's the actual bug? remapping works fine, the debug output now shows all shortcuts not just the active one, because some of those shortcuts may have --when-focus-on rules that mean they might take precedence in some situations. I suppose the debug output could be made more clear.

**Comment by mojolo** [comment]
Thanks Kovid!

FYI in case others come across this issue: the `send_key` action is only recognized in Kitty v0.32.0 or later.

**Comment by mojolo** [comment]
Here's a more real world example with the following two mappings in `kitty.conf`:
```
map kitty_mod+a scroll_to_prompt -1
map kitty_mod+z scroll_to_prompt 1
```

- In **v0.31**, pressing `ctrl+shift+a` scrolls to the previous prompt and `ctrl+shift+z` scrolls to the next prompt, as expected. Here's the debug output:
```
Added shortcuts:
        kitty_mod+a →  scroll_to_prompt -1

Changed shortcuts:
        kitty_mod+z →  scroll_to_prompt 1

Removed shortcuts:
        kitty_mod+a > 1 →  set_background_opacity 1
        kitty_mod+a > d →  set_background_opacity default
        kitty_mod+a > l →  set_background_opacity -0.1
        kitty_mod+a > m →  set_background_opacity +0.1
```

- In **v0.32+**, pressing `ctrl+shift+a` or `ctrl+shift+z` does nothing.
   If I press `ctrl+shift+a` twice though, the following raw output is inserted into the command line: `7;6u7;6u`(pressing `ctrl+shift+z` twice does nothing)Here's the debug output:

**Comment by kovidgoyal** [comment]
kitty_mod+z works fine. kitty_mod+a doesnt because of the conflicting
multi-key mapping, in 0.31 the single key mapping overrides all the
multiple keys, that changed in 0.32 accidentally, I will change it back
for the next release.

**Comment by mojolo** [comment]
Got it, thanks Kovid!
