### ISSUE TITLE
When it displays Chinese, garbled characters occur

### ISSUE THREAD

**Issue by jack9603301** [kovidgoyal/kitty#7060]
**Describe the bug**
I am located in China, and when using the Linux operating system Kitty to view directories, it always inexplicably starts displaying garbled characters in Chinese at certain times. Is this a font output error? How should I solve it? Please fix this issue as soon as possible

Equal width font used: Source Code Pro

**To Reproduce**
N/A

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/9047180/8c0ec410-a22d-40f9-b6c5-50a5d1f3cb75)

**Environment details**

branch: master
Operator System: Linux From Scratch 12.0

**Comment by kovidgoyal** [comment]
You need to install a font on your system that has glyphs covering
whatever those characters are.

**Comment by jack9603301** [comment]
Is there a recommended font?

**Comment by kovidgoyal** [comment]
Use whatever font you like, remember this is a font you simply need to have installed not the font you configure kitty to use.

**Comment by jack9603301** [comment]
I have installed Siyuan font and Source Code Pro
What else do I need?

**Comment by jack9603301** [comment]
![image](https://github.com/kovidgoyal/kitty/assets/9047180/0dd01972-bd54-4aa5-9f06-7497fa26ea99)
