### ISSUE TITLE
Pasting copied files from Dolphin doesn't work

### ISSUE THREAD

**Issue by equeim** [kovidgoyal/kitty#7068]
**Describe the bug**
When file/list of file is copy-pasted from Dolphin to Kitty using Ctrl+C and Ctrl+Shift+V shortcuts respectively, nothing happens.

In Konsole doing this pastes file paths (not `file://` URIs, that's important) in terminal, quoted using single quotes if needed (to handle spaces in path).

Also using drag&drop for this in Kitty works as expected.

**To Reproduce**
1. Copy selected files in Dolphin using Ctrl+C shortcut
2. Paste them in Kitty using Ctrl+Shift+V shortcut

**Environment details**

KDE Plasma 5.27.10, with Wayland session.

```
kitty 0.31.0 created by Kovid Goyal
Linux localhost.localdomain 6.6.12-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jan 16 01:35:44 UTC 2024 x86_64
S
Kernel 6.6.12-200.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/alexey/.config/kitty/kitty.conf

Config options different from defaults:
bold_font            Iosevka Term Bold Extended
bold_italic_font     Iosevka Term Bold Extended Italic
font_family          Iosevka Term Extended
font_size            12.0
italic_font          Iosevka Term Extended Italic
linux_display_server wayland
tab_bar_edge         1
tab_bar_min_tabs     1
tab_bar_style        powerline
tab_powerline_style  slanted
tab_title_template       {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}    
Added shortcuts:
	shift+page_down →  scroll_page_down
	shift+page_up →  scroll_page_up
Changed shortcuts:
	kitty_mod+k →  clear_terminal clear active
Colors:
	color1               #cc0000   
	color10              #8ae234   
	color11              #fce94f   
	color12              #729fcf   
	color13              #ad7fa8   
	color14              #34e2e2   
	color15              #eeeeec   
	color2               #4e9a06   
	color3               #c4a000   
	color4               #3465a4   
	color5               #75507b   
	color6               #06989a   
	color7               #d3d7cf   
	color8               #555753   
	color9               #ef2929   
	cursor               #ffffff   
	foreground           #ffffff   
	selection_background #b4d5ff   

Important environment variables seen by the kitty process:
	PATH                                /home/alexey/.cargo/bin:/home/alexey/Android/Sdk/platform-tools:/home/alexey/.local/share/JetBrains/Toolbox/scripts:/home/alexey/.cargo/bin:/home/alexey/.local/bin:/home/alexey/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
	LANG                                ru_RU.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                alexey
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     /home/alexey/.config/kdedefaults:/etc/xdg:/usr/share/kde-settings/kde-profile/default/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/alexey/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_MENU_PREFIX                     kf5-
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            2

```

**Comment by kovidgoyal** [comment]
Works fine for me in KDE Plasma Wayland (5.27.10) using up to date kitty
(0.32.0).

**Comment by equeim** [comment]
Strange, I just built 0.32.1 and it doesn't work for me (on Fedora 39, Plasma Wayland 5.27.10). How do I debug this?
Launch with WAYLAND_DEBUG=1 I see this in output:
```
[ 192775.696] wl_data_device@12.data_offer(new id wl_data_offer@4278190081)
[ 192775.699] wl_data_offer@4278190081.offer("text/uri-list")
[ 192775.703] wl_data_offer@4278190081.offer("application/x-kde4-urilist")
[ 192775.706] wl_data_device@12.selection(wl_data_offer@4278190081)
[ 192775.709]  -> wl_data_offer@4278190082.destroy()
```

**Comment by equeim** [comment]
It seems that the issue is that plain_text_mime_for_offer() function in wl_window.c file that's being called from _glfwPlatformGetClipboard() returns NULL which causes _glfwPlatformGetClipboard() to bail. My Dolphin version by the way is 23.08.4 and KDE Frameworks is 5.113.0

**Comment by kovidgoyal** [comment]
Copy a single file at a time then dolphin will send text/plain and kitty will paste it. Pasting pastes text/plain not any other mimetype.

**Comment by equeim** [comment]
> Copy a single file at a time then dolphin will send text/plain and kitty will paste it. Pasting pastes text/plain not any other mimetype.

Well on my system Dolphin uses `text/uri-list` even when single file is copied 🤔. GNOME Terminal also supports pasting `text/uri-list`, though as a separate context menu action, not Ctrl+Shift+V shortcut. Personally I find this feature very useful.

**Comment by kovidgoyal** [comment]
On Sat, Jan 27, 2024 at 10:07:07AM -0800, Alexey Rochev wrote:
> > Copy a single file at a time then dolphin will send text/plain and kitty will paste it. Pasting pastes text/plain not any other mimetype.
> 
> Well on my system Dolphin uses `text/uri-list` even when single file is copied 🤔. GNOME Terminal also supports pasting `text/uri-list`, though as a separate context menu action, not Ctrl+Shift+V shortcut. Personally I find this feature very useful.

You can paste any mimetype you like in kitty with the clipboard kitten
https://sw.kovidgoyal.net/kitty/kittens/clipboard/
