### ISSUE TITLE
Using a custom Emoji font?

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#707]
Can I use a font like this https://www.fsd.it/shop/fonts/fsd-emoji/ to render custom emojis instead of system ones?

I tried this but it didn't work

```
symbol_map U+1F610-U+1F6B6 <font name>
```

**Comment by ahmedelgabri** [comment]
Works in `kitty_mod + u` but not when I do `echo "\u1F610"` for example any reason why?

**Comment by maximbaz** [comment]
Try a capital `U`:

![image](https://user-images.githubusercontent.com/1177900/42401234-ff2c8b5e-8174-11e8-9bd9-be74c8ac59fa.png)

**Comment by ahmedelgabri** [comment]
Thanks @maximbaz
