### ISSUE TITLE
I'd like to be able to declare font_family with multiple fonts `font_family: Hack Nerd Font Mono, Hack, Noto Sans`

### ISSUE THREAD

**Issue by mxaddict** [kovidgoyal/kitty#7076]
I'd like to be able to declare `font_family` value with more than 1 font.

I use multiple machines that all share the same .config files (including kitty)

On some machines (Arch mainly) I use `Hack` as my font.

On my mac I use Noto Sans.

I'm trying to figure out a way to have different fonts on different machines without having to edit my config specifically for that machine. It would be nice if kitty could support comma separated list of fonts and pick the first one available on the system from left to right.

Something like this: 
```
font_family: Hack Nerd Font Mono, Hack, Noto Sans
```

**Comment by kovidgoyal** [comment]
You dont need to edit your config for particular machines. Simply use
the following in kitty.conf

include ${KITTY_OS}.conf

and have a linux.conf and macos.conf

**Comment by mxaddict** [comment]
> You dont need to edit your config for particular machines. Simply use the following in kitty.conf
> 
> include ${KITTY_OS}.conf
> 
> and have a linux.conf and macos.conf

This works for me! Thanks!
