### ISSUE TITLE
Add shortcut ctrl + k for search column

### ISSUE THREAD

**Issue by 3xploiton3** [kovidgoyal/kitty#7077]
![image](https://github.com/kovidgoyal/kitty/assets/19517680/e870fc2b-8e71-4e95-ad71-9415b37985a7)

**Comment by 3xploiton3** [comment]
![image](https://github.com/kovidgoyal/kitty/assets/19517680/25f3b606-0a97-412b-b2a3-cc091ea070f6)

**Comment by kovidgoyal** [comment]
The website is generated using the Sphinx documentation system, you
would need to get this feature added to either sphinx or the furo sphinx
theme that the website uses.
