### ISSUE TITLE
Keyboard layout not working

### ISSUE THREAD

**Issue by calbertts** [kovidgoyal/kitty#708]
First of all, I have to say this is the fastest terminal I've used ever, I love it.

Few weeks ago, I've made a change from iTerm2 to Kitty, is fast and works almost perfectly with Neovim.
The problem I have now, is my keyboard layout, I have a latin american keyboard, but I've found that I'm not able to find some characters normally.. for example:

This one: **~** 
I use it a lot in a day because of routes, etc.. I haven't been able to find how can I get this character.

This ones: **[]{}\|@**
I have to use strange keyboard shortcuts to get them, and I haven't been able to find **@** in any way, I would like to use the normal keyboard distribution, this is a problem I don't have in any other terminal.

I think this is the only thing I'm missing in this terminal, apart of that, is just perfect.

**Comment by erf** [comment]
Sounds similar to the following issue i had  #663

**Comment by kovidgoyal** [comment]
On macOs if you want to use the option key to type special characters you have to set the macos_option_as_alt to no in kitty.conf

**Comment by calbertts** [comment]
Worked perfectly, thanks.
