### ISSUE TITLE
Support XEmbed as a host/embedder

### ISSUE THREAD

**Issue by rhaberkorn** [kovidgoyal/kitty#7083]
**Is your feature request related to a problem? Please describe.**
When opening graphical editors from the terminal, a new window is spawned (naturally). This does not work well with a command-line centered workflow. When using Kitty tabs, the editor window will not be in a regular tab. When using tiling window managers, you will end up with additional tabs (the ones that are waiting for the graphical apps to terminate).

**Describe the solution you'd like**
Supporting the [Xembed](https://specifications.freedesktop.org/xembed-spec/xembed-spec-latest.html) protocol as a host to allow graphical editors to embed themselves into running Kitty windows. Many X11-editors support Xembed.
There could be some `launch --type=xembed` command to launch an Xembed-aware application as an overlay, similar to `--type=overlay`.

**Describe alternatives you've considered**
Starting terminal-based versions of the editor in question.

**Additional context**
I see that you are probably against adding X11-only features, but still wanted to give it a try. ;-)

**Comment by kovidgoyal** [comment]
Sorry, my position on X11 only features has not changed.

**Comment by rhaberkorn** [comment]
Although it seems, something similar could be done on Wayland as well. Not sure whether any widget toolkit has out-of-the-box support for this, though.
https://wayland.app/protocols/xdg-foreign-unstable-v2

**Comment by kovidgoyal** [comment]
Wayland protocols are pretty useless. They will be implemented by 7 out of 39 wayland compositors, and that too each compositor will have different bugs in its implementation and in this case where one expects co-operation from another application, each application will have implemented it using its own custom buggy implementation, if its implemented at all. And all those bugs end up as bug reports here that I have to waste my time reading/responding too.

All of which means I have to waste more of my life on supporting the train wreck that is wayland. And after all that, it will still be a linux only feature and require tons of obscure code and even more tons of maintenance. 

I suggest if you are investing in a command line workflow, you invest in picking a TUI based editor as well. These days they have pretty good integration and features. I develop both kitty and calibre using a TUI mode editor.

**Comment by rhaberkorn** [comment]
> All of which means I have to waste more of my life on supporting the train wreck that is wayland.

I was thinking about adopting Wayland or at least giving it a try, but your comments and the cautious tales of others convinced me that, no probably I shouldn't.

> I suggest if you are investing in a command line workflow, you invest in picking a TUI based editor as well. These days they have pretty good integration and features. I develop both kitty and calibre using a TUI mode editor.

I have my own editor project [SciTECO](https://github.com/rhaberkorn/sciteco), which supports both Curses and GTK. It's designed in such a way that the GTK version actually looks and behaves very similar to the Curses one. And while I do usually use the Curses implementation, I always thought that it would be cool to run the GTK one as an "overlay" on the terminal window, just like a fullscreen Curses editor effectively does. I implemented Xembed support for that purpose, which is quite trivial on Gtk, but was surprised that are almost no applications that can act as an Xembed host. [tabbed](https://tools.suckless.org/tabbed/) from the "suckless" community being the most popular one (and quite useless when running tiling window managers).

It turns out that the [st](https://st.suckless.org/) "simpleterm" does have support for Xembed hosting in the form of an [obscure patch](https://lists.suckless.org/hackers/2001/17072.html). It's the only terminal emulator I know of, that has at least some support for this. Playing around with it now. It does work but st does not pick up the title of embedded applications. Also, it does not play well with all Xembeddable apps. So I will have to patch the patch it seems...

Actually simpleterm is quite nice as a terminal emulator. They managed to implement most important things - at least everything I need - in around 5000 lines of plain C code. At the same time, it turns out to be very fast. It's actually a bit faster than Kitty on my system, even after patching in a scroll buffer.

**Comment by rhaberkorn** [comment]
That sounds overly negative towards Kitty. I do actually like the image support you implemented and have already integrated it into one of my projects. It's not public yet, but I will mail you once it is.

It's a shame that innovations like this will probably never really take off due to the lack of standardization and the lack of support in terminfo. As you may have noticed, it's a pain *** to actually write applications that make use of non-standard terminal features and are still portable across a range of emulators. You will have to whitelist terminal emulators for the Kitty image protocol. If you would like to support SIXEL as well, you will be confronted with the fact that its support is not actually detectable by applications at runtime, so you will have to make this a configurable, effectively scriptable, feature. Otherwise you will find that your application works fine on one emulator, but spits out garbage on another one. And sadly, that's true for a lot of useful extensions. Clipboard-integration immediately comes to mind.

**Comment by kovidgoyal** [comment]
On Thu, Feb 01, 2024 at 04:27:58AM -0800, Robin Haberkorn wrote:
> > All of which means I have to waste more of my life on supporting the train wreck that is wayland.
> 
> I was thinking about adopting Wayland or at least giving it a try, but your comments and the cautious tales of others convinced me that, no probably I shouldn't.

Yeah, I have been completely soured on Wayland with the experience of
maintaining calibre and kitty and dealing with countless bugs caused by
Wayland. For calibre I just mark them all as wontfix, Qt's problem. But
sadly for kitty because it manages its own graphics stack I feel obliged
to work around the most egregious ones. Just grep the kitty changelog
for all mentions of Wayland to get an idea of the endless issues.
Compare and contrast with mentions of X11.
> 
> > I suggest if you are investing in a command line workflow, you invest in picking a TUI based editor as well. These days they have pretty good integration and features. I develop both kitty and calibre using a TUI mode editor.
> 
> I have my own editor project [SciTECO](https://github.com/rhaberkorn/sciteco), which supports both Curses and GTK. It's designed in such a way that the GTK version actually looks and behaves very similar to the Curses one. And while I do usually use the Curses implementation, I always thought that it would be cool to run the GTK one as an "overlay" on the terminal window, just like a fullscreen Curses editor effectively does. I implemented Xembed support for that purpose, which is quite trivial on Gtk, but was surprised that are almost no applications that can act as an Xembed host. [tabbed](https://tools.suckless.org/tabbed/) from the "suckless" community being the most popular one (and quite useless when running tiling window managers).

You can actually run your editor's GTK interface inside kitty directly,
hell there are even projects that run an entire browser inside kitty.
https://github.com/chase/awrit you dont need XEmbed for this. It even
works over SSH, providing you have a fast enough connection. 

> 
> It turns out that the [st](https://st.suckless.org/) "simpleterm" does have support for Xembed hosting in the form of an [obscure patch](https://lists.suckless.org/hackers/2001/17072.html). It's the only terminal emulator I know of, that has at least some support for this. Playing around with it now. It does work but st does not pick up the title of embedded applications. Also, it does not play well with all Xembeddable apps. So I will have to patch the patch it seems...
> 
> Actually simpleterm is quite nice as a terminal emulator. They managed to implement most important things - at least everything I need - in around 5000 lines of plain C code. At the same time, it turns out to be very fast. It's actually a bit faster than Kitty on my system, even after patching in a scroll buffer.

Try the kitty vt branch :)
https://github.com/kovidgoyal/kitty/issues/7005

**Comment by kovidgoyal** [comment]
On Thu, Feb 01, 2024 at 04:46:39AM -0800, Robin Haberkorn wrote:
> That sounds overly negative towards Kitty. I do actually like the image support you implemented and have already integrated it into one of my projects. It's not public yet, but I will mail you once it is.
> 
> It's a shame that innovations like this will probably never really take off due to the lack of standardization and the lack of support in terminfo. As you may have noticed, it's a pain *** to actually write applications that make use of non-standard terminal features and are still portable across a range of emulators. You will have to whitelist terminal emulators for the Kitty image protocol. If you would like to support SIXEL as well, you will be confronted with the fact that its support is not actually detectable by applications at runtime, so you will have to make this a configurable, effectively scriptable, feature. Otherwise you will find that your application works fine on one emulator, but spits out garbage on another one. And sadly, that's true for a lot of useful extensions. Clipboard-integration immediately comes to mind.

Not at all, you can robustly detect if a terminal supports the kitty
graphics protocol. 
https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums

For an example of it in action, run

kitten icat image.png

in a terminal that doesnt support the graphics protocol.

**Comment by rhaberkorn** [comment]
> You can actually run your editor's GTK interface inside kitty directly, hell there are even projects that run an entire browser inside kitty. https://github.com/chase/awrit you dont need XEmbed for this.

That's working via the image protocol as well? Won't that be a terrible hack that would require me to include lots of Kitty-specific code?

> Try the kitty vt branch :)
> [#7005](https://github.com/kovidgoyal/kitty/issues/7005)

Perhaps I will try once it's mainline.

> Not at all, you can robustly detect if a terminal supports the kitty
> graphics protocol.

Just tried this from st and urxvt. Turns out that on st it hangs a few seconds and in the meantime spews out random characters (probably the remnants of unsupported escape sequences). On urxvt it spews out characters without hanging. That's not what you want to do every time your app starts up. Sure, I mean this way, you could "detect" the presence of the clipboard escapes as well, but that's everything but robust.

**Comment by kovidgoyal** [comment]
On Thu, Feb 01, 2024 at 06:44:56AM -0800, Robin Haberkorn wrote:
> > You can actually run your editor's GTK interface inside kitty directly, hell there are even projects that run an entire browser inside kitty. https://github.com/chase/awrit you dont need XEmbed for this.
> 
> That's working via the image protocol as well? Won't that be a terrible hack that would require me to include lots of Kitty-specific code?

About as much of a terrible hack as XEmbed. 

> Just tried this from st and urxvt. Turns out that on st it hangs a few seconds and in the meantime spews out random characters (probably the remnants of unsupported escape sequences). On urxvt it spews out characters without hanging. That's not what you want to do every time your app starts up. Sure, I mean this way, you could "detect" the presence of the clipboard escapes as well, but that's everything but robust.

That just means st and urxvt dont implement correct VT escape code
parsers. Any even partially non-braindead terminal should ignore well
formed escape codes it doesnt understand, not spew them to screen. 

If you do want to insist on using outmoded terminal emulators to test
with at least pick one that can parse escape codes somewhat correctly,
say xterm.
