### ISSUE TITLE
Add wider_symbols option

### ISSUE THREAD

**Issue by ribru17** [kovidgoyal/kitty#7084]
**Is your feature request related to a problem? Please describe.**
I would like to extend what symbols are allowed to take up a larger width (I am aware that currently it is just private-use unicode characters and some wingdings). I would really love, for example, if check box characters (`☑ ☐`) would take a wider width in my editor.

**Describe the solution you'd like**
I would love if there was perhaps a `wider_symbols` (`wide_symbols`?) option that acts like `narrow_symbols` but the opposite: it allows these characters to take up a larger width.

**Describe alternatives you've considered**
Not many alternatives, but I would be very grateful if even just these symbols were added to the allowed "wider" list.

**Additional context**
Thank you for the amazing terminal emulator.

**Comment by kovidgoyal** [comment]
They already do, as shown by the screenshot below:
![screenshot](https://github.com/kovidgoyal/kitty/assets/1308621/42392426-f886-40eb-af74-b21557d9bcb1)

**Comment by ribru17** [comment]
Weird, I guess my font is improperly configured. Thanks!
