### ISSUE TITLE
Output from background proccesses disappears when adjusting windows

### ISSUE THREAD

**Issue by JellyKid** [kovidgoyal/kitty#7085]
**Describe the bug**
If a background process outputs logs/information, that output will disappear when resizing the window in anyway. This includes splitting a window. The Gnome Terminal and other terminals I've worked on, do not exhibit this behavior.

**To Reproduce**
1. Run the script below as a background process, i.e. "background_process.sh &"
2. Allow the script to write a few foobars to stdout.
3. Adjust the window size in anyway or split the window
4. You should see all of the output from the script disappear.

**background_process.sh**
```
#!/bin/sh

echo
echo
echo "If running in foreground ctrl+c will quit, otherwise type \"kill $$\" to quit." 
echo

#Write foobar to stdout every 2 seconds
foobar () {
    while true; do
    echo "foobar"
    sleep 2
    done
}

#run foobar in the background and get process ID of foobar
foobar &
bgpid=$! 

cleanup () {
    echo "cleanup called"
    kill -9 $bgpid
}

#hook to call cleanup func on sigint/quit/term etc
trap "cleanup" INT TERM HUP

wait $bgpid
```

**Screenshots**
Before window resize:
![Screenshot from 2024-02-01 14-31-22](https://github.com/kovidgoyal/kitty/assets/8331976/74880588-dc99-42ca-acff-c05ebc31f08f)

After window resize:
![Screenshot from 2024-02-01 14-31-33](https://github.com/kovidgoyal/kitty/assets/8331976/83e28786-f479-45b1-ae9e-1405844d1848)

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux fedora 6.6.13-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 20 18:03:28 UTC 2024 x86_64
S
Kernel 6.6.13-200.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/jake/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.75
editor                nvim
enable_audio_bell     False
enabled_layouts       ['tall', 'fat', 'grid', 'horizontal', 'vertical']
font_size             12.0
inactive_text_alpha   0.6
shell_integration     frozenset({'no-cursor'})
window_border_width   (1.0, 'pt')
Colors:
	inactive_border_color #787878   

Important environment variables seen by the kitty process:
	PATH                                /home/jake/.local/bin:/home/jake/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_US.UTF-8
	VISUAL                              /usr/bin/code
	EDITOR                              /usr/bin/nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                jake
	XDG_DATA_DIRS                       /home/jake/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland

```

**Additional context**
I also tried with `kitty --config NONE` and see the same behavior. I'm sure the problem isn't going to the front of the line, but it is something that makes this term a little more frustrating than others. I've been developing some docker containers that run in the background and will output things to the stdout, and if I'm not careful I will accidentally lose that info by resizing the window or splitting it. Either way, it's a great TTY with good documentation and I appreciate everyone's hard work on it.

**Comment by kovidgoyal** [comment]
Does not replicate for me with those steps, using kitty and bash with default configurations.
![screenshot](https://github.com/kovidgoyal/kitty/assets/1308621/cbfd94b2-ed90-446a-a728-1a0ba5581e24)

Screensshot generated by running:

```sh
kitty --config=NONE -o shell=bash -o enabled_layouts=tall
```
waiting for a few foobars and splitting.


Indeed, terminals in general and kitty in particular do not know or care whether processes writing to their tty devices are background or foreground, there is no way for them to know if any particular write comes from the foregound or background process. This will be something in your shell rc files most likely related to how it redraws the prompt on a  resize.

**Comment by JellyKid** [comment]
You didn't run the script in the background with &. Your test should be "sh /t/bg.sh &"

**Comment by kovidgoyal** [comment]
Ah, right sorry. Yes in that case this will happen, because on resize
kitty shell integration *clears* everything after the prompt on resize to allow
the shell to redraw its prompt correctly. See
https://sw.kovidgoyal.net/kitty/shell-integration 

In particular:

Glitch free window resizing even with complex prompts. Achieved by erasing the prompt on resize and allowing the shell to redraw it cleanly.

Turn off shell integration if you dont want this behavior in kitty.conf

Although I will note that having multiple processes writing to the same
tty device is broken in so many ways its not even funny.
