### ISSUE TITLE
kitty start blanks in hyprland

### ISSUE THREAD

**Issue by realsnick** [kovidgoyal/kitty#7087]
**Describe the bug**
kitty starts blank with the following error

```
[033 09:50:25.162933] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```
**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/1440852/1838ce62-6e15-4e7d-a4d0-3712e8cd5efe)

**Environment details**
![image](https://github.com/kovidgoyal/kitty/assets/1440852/e49d0c8f-fae8-4148-ae84-8630601f2434)

 `kitty --config NONE` doesn't change and kitty still starts blank

`export KITTY_DISABLE_WAYLAND=1` seems to make kitty work again and visible... though this is just pointing to an issue with wayland/hyprland and kitty

**Comment by kovidgoyal** [comment]
Does not reproduce for me. kitty works fine in Hyprland 0.34.0 under Wayland.
And being unable to read desktop settings doesnt prevent kitty from
working. Though you should install some desktop settings portal. 

And I note you are using an NVIDIA driver so see #7021
