### ISSUE TITLE
[macOS] Clipboard paste regression in v0.11.2

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#709]
When I paste a larger amount of text in Kitty (does not matter if it is in the kitty prompt, a vim / nvim editing session, or if tmux is involved or not), Kitty will incorrectly duplicate some of the text, instead of pasting the correct contents.

To clarify, it does output the expected number of lines, but about halfway through, the content is repeated, rather than outputting what I expect.

I double-checked that this bug is not present in 0.11.1.

Edit: The issue is also present on the latest master branch.

Edit: It's not actually a large amount of text either, something about 42 LOC will trigger this issue for me.

**Comment by kovidgoyal** [comment]
You are pasting how? With the keyboard shortcut?

**Comment by koekeishiya** [comment]
Yeah using the keyboard shortcut: `map super+v             paste_from_clipboard`

**Comment by koekeishiya** [comment]
Confirmed working. Thanks for the quick fix as usual.
