### ISSUE TITLE
Remote Control causing errors

### ISSUE THREAD

**Issue by doonoo** [kovidgoyal/kitty#7093]
**Describe the bug**
When it's disabled, this popups;
`@kitty-cmd{"ok": false, "error": "Remote control is disabled"} `
When enabled
`@kitty-cmd{"ok": false, "error": "argument 1 must be dict, not None", "tb": "Traceback (most recent call last):\n  File \"/usr/bin/../lib/kitty/kitty/boss.py\", line 721, in _execute_remote_command\n    response = handle_cmd(self, window, pcmd, peer_id, self_window)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/bin/../lib/kitty/kitty/remote_control.py\", line 242, in handle_cmd\n    ans = c.response_from_kitty(boss, self_window or window, PayloadGetter(c, payload))\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/bin/../lib/kitty/kitty/rc/set_colors.py\", line 127, in response_from_kitty\n    patch_color_profiles(colors, profiles, payload_get('configured'))\nTypeError: argument 1 must be dict, not None\n"}`
**To Reproduce**
Just enable remote control in config

Kitty isn't open debug when pressing CTRL+ALT+F6

**Comment by kovidgoyal** [comment]
kitty does not use remote control by itself. You have setup something
that does, and does so ina broken way. Fond out whatever that is, and
disable it.

**Comment by doonoo** [comment]
Is there a way to find out?
