### ISSUE TITLE
Colored strikethrough

### ISSUE THREAD

**Issue by egmontkob** [kovidgoyal/kitty#71]
Hi,

I'm just wondering... do you think it would make sense for the underline color `\e[58...m` to be applied for strikethrough as well?

(Note that underlining and strikethrough are not mutually exclusive, you can have both at the same time... although it's really not a typical use case.)

I'm thinking about implementing this feature in VTE (the engine behind gnome-terminal and many others)...

**Comment by kovidgoyal** [comment]
I dont know of any use cases for colored strikethrough. My motivation for implementing colored underlines was for text editors, in particular the colored wavy underlines for spelling, grammar and syntax errors.

**Comment by kovidgoyal** [comment]
Closing.
