### ISSUE TITLE
Kitty seems slow to open.

### ISSUE THREAD

**Issue by notaduck** [kovidgoyal/kitty#710]
Hi. I've just installed Kitty last night and I'm about to make the transition from Termite to Kitty.
However it seems that Kitty is pretty slow to open a new terminal window. 

It takes about ~3.00 sec where termite opens a new instance in ~0.5 sec. Is this the normal/expected behavior?

And when it runs it runs flawless!

**Comment by SolitudeSF** [comment]
![image](https://user-images.githubusercontent.com/10168645/42418931-7cbf49dc-82b3-11e8-9f3f-8a027ea32e15.png)

launch kitty as `kitty -1` if you want to speedup start time.

**Comment by kovidgoyal** [comment]
3 seconds is definitely not normal. Typical startup times are between 0.2 to 0.6 seconds. If for some reason on your system it is taking very long to start, you can use the `--single-instance` option for instant startups, as pointed out by @SolitudeSF 

If you want to debug why it is taking so long on your system you can use the profiling steps desribed here: https://sw.kovidgoyal.net/kitty/performance.html

**Comment by notaduck** [comment]
That was definitely an improvement! but....... if I open kitty with `-1` then the first time I open it is still slow, if I open two more they open instant. If I then close all of the instances and open one again then it is still slow.

**Comment by kovidgoyal** [comment]
Well, yes. That's because -1 opens a new window in an existing instance, there has to be an existing instance for it to work.

**Comment by notaduck** [comment]
but there should all ready be a single instance which is starting on boot. 
That window is hidden, but always running

**Comment by kovidgoyal** [comment]
That instance also has to be started with the -1 argument.

**Comment by notaduck** [comment]
That should all ready be the case `exec --no-startup-id $term --name="git" --single-instance` however I'm using `--single-instance` and `$term` is declared as `kitty`

**Comment by kovidgoyal** [comment]
Well something is causing that instance to no run,you can check that using top or ps.

**Comment by notaduck** [comment]
Can the reason be that the terminal which is starting at system startup has it's own name?

**Comment by kovidgoyal** [comment]
The name is derived from three things:

1) user id
2) application name
3) --single-instance-group

None of those should be different during statrup other than possible (1) if for some reason your startup scripts are run under a different user
