### ISSUE TITLE
macos_hide_titlebar breaks window resizing after exiting fullscreen

### ISSUE THREAD

**Issue by nikhilkamineni** [kovidgoyal/kitty#711]
After exiting fullscreen mode I cannot resize a window. Placing cursor on the corner does not switch to the resize icon and clicking/dragging does not work. I also use an app called Spectacle (spectacleapp.com) for moving/resizing purposes and resizing doesn't work correctly with that either. Everything works as expected before entering fullscreen.

This issue doesn't happen when `macos_hide_titlebar` is not enabled. I'm on macOS 10.13.5. Let me know if I can provide any other info.

**Comment by kovidgoyal** [comment]
Not much I can do about that, I'm afraid. The resizing facility comes form the operating system, not kitty. If resizing + fullscreen + no titlebar does not work in cocoa, it's because of something lower down in the stack than kitty.

**Comment by kovidgoyal** [comment]
Nevermind, I found a workaround for this.
