### ISSUE TITLE
[feature request] add option to copy env vars for remote kittens

### ISSUE THREAD

**Issue by mikesmithgh** [kovidgoyal/kitty#7112]
**Is your feature request related to a problem? Please describe.**
I do not have access to environment variables when calling a remote custom kitten.

**Describe the solution you'd like**
I would like an option for remote kittens to copy environment variables similar to the `launch` command. Currently, you can copy environment variables with `kitty @ launch --copy-env`. It would be nice to have a similar capability with kittens. e.g., `kitty @ kitten --copy-env test_kitten.py`

**Describe alternatives you've considered**
n/a

**Additional context**

I am trying to add a new feature to https://github.com/mikesmithgh/kitty-scrollback.nvim to let the user get the scrollback buffer for tmux sessions. The general idea right now is:
- if the `TMUX` environment variable is present, use `tmux capture-pane` to get the scrollback buffer
- else use `kitty @ get-text` to get the scrollback buffer

The problem I am hitting at the moment is that I don't have access to the environment variables when calling the `kitty_scrollback_nvim.py` kitten. So, I can't pull the info from the `TMUX` environment variable.

The following examples are using the file `test_kitten.py`.
```py
from typing import List
from kitty.boss import Boss
import os

def main(args: List[str]) -> str:
    test_env = os.environ.get('TEST')
    print(f'The env var TEST is {test_env}')
    input('Press any key...')
    return test_env
```

#### Remote kitten does not have access to environment variables
`TEST=something kitty @ kitten test_kitten.py`
![Screenshot 2024-02-09 at 9 13 28 PM](https://github.com/kovidgoyal/kitty/assets/10135646/424f9d27-98ba-43b8-b7cf-59a7411d1f49)

#### Other variations of launching Kitty that does have access to environment variables
- `TEST=something kitty --hold sh -c 'echo $TEST'`
![Screenshot 2024-02-09 at 9 11 49 PM](https://github.com/kovidgoyal/kitty/assets/10135646/d4c567e4-04b3-4cb0-922f-7b9654214b55)

- `TEST=something kitty @ launch --hold --copy-env sh -c 'echo STEST`
![Screenshot 2024-02-09 at 9 10 39 PM](https://github.com/kovidgoyal/kitty/assets/10135646/9b84601e-48b1-480e-a308-f22df28161bd)

- `TEST=something kitty +kitten test_kitten.py`
![Screenshot 2024-02-09 at 9 18 17 PM](https://github.com/kovidgoyal/kitty/assets/10135646/0edb8856-66ca-446b-8400-5a2d0db16bba)

**Comment by kovidgoyal** [comment]
Use

kitten @ kitten mykitten.py TMUX=$TMUX

In other words pass the env vars you are interested in as command line
arguments to your kitten. They will then be present as args in the
kitten API.

**Comment by mikesmithgh** [comment]
Thanks that worked!
