### ISSUE TITLE
High Resolution Terminals -> High GPU Usage 

### ISSUE THREAD

**Issue by anymuster2** [kovidgoyal/kitty#7114]
**Describe the bug**

Using a 4k monitor, each kitty terminal consumes approx 50mb VRAM per window, this usage is correlated to the size of the kitty window, and does not decrease when I switch to a different workspace or when the window is entirely covered by another window. `nvidia-smi` reports kitty processes but the Xorg process also increases substantially with each window.

In comparison, gnome-terminal uses VRAM also, but appears to reduce consumption when not in the foreground or when on a different workspace.

**To Reproduce**

Using a high resolution display, run `nvidia-smi` or `radeontop`, open many kitty windows. Attempt to change work spaces, similar results.

**Environment details**

Tested in gnome3 and openbox, I also confirmed the same behavior on both nvidia and amd gpus. 

```
kitty 0.26.5 created by Kovid Goyal
Linux 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64
Debian GNU/Linux 12 /dev/tty

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:~/.bin/:/etc/shell/bin:/opt/bin:~/.bin/:/etc/shell/bin:/opt/bin
	LANG                                en_AU.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :0
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_VTNR                            2
	XDG_SEAT                            seat0
	XDG_DATA_DIRS                       /usr/share/gnome:/usr/local/share/:/usr/share/
	XDG_SESSION_DESKTOP                 gnome
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_ID                      3
	XDG_SESSION_CLASS                   user

```

**Additional context**

**Comment by kovidgoyal** [comment]
So what? Your graphics drivers will page it out when it is needed and
unused.
