### ISSUE TITLE
kitty keyboard shortcut is not delivered to kitty window in focus

### ISSUE THREAD

**Issue by nileshpatra** [kovidgoyal/kitty#7116]
**Describe the bug**
I got this bug report in Debian bug[#1061832](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061832). It does not personally repro for me in my own DE/WM or a couple other places I tried. But if you could please spend a couple of mins to check this at your end as well, if you're able to repro this or not -- maybe you could, I would be super-super grateful.

**To Reproduce**
I start several kitty windows with "kitty -1".
kitty.conf contains "map kitty_mod+t new_tab".

After a bit switching back and forth between several other programs,
coming back to the 2nd kitty window the normal key presses are delivered
to the shell as usual, but when pressing kitty_mod+t the new tab is not
opened in the kitty window in focus, but in the other (I think the first)
kitty window.

Same behaviour for all other shortcuts, like move_tab_forward,
move_tab_backward, etc...

**Comment by kovidgoyal** [comment]
Does not reproduce for me. As always with input issues, one can run
kitty with --debug-input which will show exactly what key events are
delivered to kitty and what it does with them.

**Comment by nileshpatra** [comment]
Hey, thank you for spending time on it -- much appreciated! I've closed the corresponding bug report also in Debian with similar comments.
