### ISSUE TITLE
kitty-merge: a mergetool companion for kitty-diff

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#712]
`kitty-diff` is just awesome, I only wish I could have a similar kitten for dealing with git merges, which I could define in `~/.gitconfig` in the `[mergetool]` section.

Have you considered this?

**Comment by kovidgoyal** [comment]
I've never felt the need for a mergetool personally, as I tend not to do a lot of complicated merging. As such, I dont have a good handle on what makes for a good merge tool. That makes me not the right person to create one.

**Comment by sean9999** [comment]
I see that this has been closed, but feel it would be useful to people. Would you consider a pull request that includes said functionality?

**Comment by kovidgoyal** [comment]
You dont need to make a PR, you can create kittens (which is what the
diff tool is) that live outside the kitty codebase.
https://sw.kovidgoyal.net/kitty/kittens/custom.html

If you can make one that works well, we can discuss distributing it with
kitty.
