### ISSUE TITLE
feat: toggle to disable font increase/decrease bindings

### ISSUE THREAD

**Issue by falcucci** [kovidgoyal/kitty#7125]
**Is your feature request related to a problem? Please describe.**
Currently the default font size Kitty bindings are overwriting my personal vim bindings and seems not to be able to disable permanently those bindings.

```bash
#: Increase font size

map kitty_mod+equal  change_font_size all +2.0
map kitty_mod+plus   change_font_size all +2.0
map kitty_mod+kp_add change_font_size all +2.0
map cmd+plus         change_font_size all +2.0
map cmd+equal        change_font_size all +2.0
map shift+cmd+equal  change_font_size all +2.0

#: Decrease font size

map kitty_mod+minus       change_font_size all -2.0
map kitty_mod+kp_subtract change_font_size all -2.0
map cmd+minus             change_font_size all -2.0
map shift+cmd+minus       change_font_size all -2.0
```

**Describe the solution you'd like**
add a toggle about font increase/decrease to consider or not those mappings.

**Describe alternatives you've considered**
Any workaround would be welcome.

**Comment by MatthewFluet** [comment]
Unbind those bindings in your `kitty.conf` like

```
map kitty_mod+equal no_op
```

See https://sw.kovidgoyal.net/kitty/actions/#action-no_op.
