### ISSUE TITLE
Per tab font size

### ISSUE THREAD

**Issue by benner** [kovidgoyal/kitty#7129]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be great to be able to have different font size per tab or even split in same tab

**Describe alternatives you've considered**

N/A

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
I'm afraid not, my answer hasnt changed since the last time this was
asked for.

**Comment by benner** [comment]
Maybe with https://sw.kovidgoyal.net/kitty/text-sizing-protocol/ it's possible?

**Comment by nenahp** [comment]
Is  per os-windows font_size (but the same kitty instance) possible?

I want to open a popup with smaller font:
```sh
kitty -1 -o font_size=10 --app-id kitty-rofi-like fzf-rofi
```

**Comment by kovidgoyal** [comment]
On Thu, Apr 10, 2025 at 08:43:24PM -0700, nenahp wrote:
> nenahp left a comment (kovidgoyal/kitty#7129)
>
> Is  per os-windows font_size (but the same kitty instance) possible?

kitten @ set-font-size -h
