### ISSUE TITLE
Nested Tabs

### ISSUE THREAD

**Issue by davvid** [kovidgoyal/kitty#7138]
The *only* thing that tmux brings to the table for me is that it allows for switching between multiple terminals from within a single kitty split pane window.

Using something like my [fork of abduco](https://github.com/davvid/abduco) with a shell script[1] makes it trivial to reactivate a shell sessions, which makes the need for tmux basically zero if kitty had a way to have tabs inside of a split pane window.

[1] example abduco-session shell script for reactivating sesions
```bash
#!/bin/sh
usage () {
    echo "abduco-session starts or attaches to an existing abduco + zellij session"
    echo "usage: $(basename $0) <session-name>"
    echo
    abduco -l
    exit 1
}

main () {
    for arg in "$@"
    do
        case "${arg}" in
        -h|--help)
            usage
            ;;
        *)
            # Allow the session to be specified.
            session="${arg}"
            ;;
        esac
    done
    # Guard against nested sesssions.
    if test -n "${ABDUCO_SESSION}"
    then
        echo "error: session '${ABDUCO_SESSION}' is already active"
        exit 1
    fi
    # If the session has not been specified then use the most recent session.
    if test -z "${session}"
    then
        session=$(get_abduco_session)
    fi
    # If no session can be found then display usage and exit.
    if test -z "${session}"
    then
        usage
    fi
    # Use ctrl-q as the detach command
    abduco -e ^q -A "${session}"
}

# Get all the sessions.
get_abduco_sessions () {
    abduco -l | grep '^*' | awk '{print $6}'
}

# Get the last session.
get_abduco_session () {
    get_abduco_sessions | tail -n 1
}

main "$@"
```

Right now tabs are global over all the splits. It'd be great to be able to jump between terminals within a single split pane. This does seem like a separate concept from the main tabs, as those remain useful as-is.

Nested tabs would need separate actions/hotkeys for cycling through them separate from the main tabs.

It doesn't seem like nesting beyond one level is useful. The use case is something like a 3-split layout with a tall main editor terminal on the right and a split pane on the left with two terminal views, each of which can be cycle between multiple terminals using nested tabs.

tmux can currently do this, and tmux is a bad way of doing it.

I haven't studied kitty's code but if you think this wouldn't be a terrible feature to add I could start studying it to see if I could try and contribute something. This would be a great tmux killer for me, at least.

**Comment by kovidgoyal** [comment]
nested tabs arent worth the complexity to me. For your specific use
case, you could use the existing overlay windows feature. You create a
tall layout tab and on the right put your second terminal window as an
overlay of the first. 

Then you would need to write a relatively simple kitten that could can be
mapped to some keystroke to switch between the two overlay windows,
probably by swapping which window is an overlay and which is the base
window.

Another simple way to achieve this is if you use a tiling window
manager, you can have two kitty OS windows one with your main panel on
the left and the second with two tabs on the right.

**Comment by davvid** [comment]
I'm not sure if the overlays would quite accomplish the same thing.

For the left side, it's actually split as well (3 terminal panes total, one on the right and two on the left), and it's within both of the splits on the left that swapping terminals would be helpful. That's something per-split tabs would solve that in a way that's not possible. That means it wouldn't be two OS windows, it'd be three, which is pretty clunky. It's so much nicer to just maximize a kitty window and work within that.

Right now we can jump between the split panes using ctrl-shift-[ and ]. It'd be great to be able to do that but separating them out into separate kitty windows kills that feature.

Using a tiling window manager is a bit of a lame solution, and doesn't jive with macOS either, as then the window manager's hotkeys are added into the mix whereas kitty could do it so much better on its own without any flash or delay when focus moves around. We'd also get to use kitty's native hotkeys for moving between panes. Another wrinkle is that the panes would have kitty's focus indicators if it were a native feature. Using multiple OS-level windows means they all visually display as "focused" panes.

Anyways, I'm just explaining why this seemed like a useful feature.  Maybe I should switch to a tiling window manager after all. Thanks for quickly explaining that this is considered too complex to be worth it ~ I appreciate that.

**Comment by kovidgoyal** [comment]
On Sun, Feb 18, 2024 at 07:26:16PM -0800, David Aguilar wrote:
> I'm not sure if the overlays would quite accomplish the same thing.
> 
> For the left side, it's actually split as well (3 terminal panes total, one on the right and two on the left), and it's within both of the splits on the left that swapping terminals would be helpful. That's something per-split tabs would solve that in a way that's not possible. That means it wouldn't be two OS windows, it'd be three, which is pretty clunky. It's so much nicer to just maximize a kitty window and work within that.
> 
> Right now we can jump between the split panes using ctrl-shift-[ and ]. It'd be great to be able to do that but separating them out into separate kitty windows kills that feature.

You can do the same with overlays, as I said, write your own kitten, map
it to cs-[ and cs-] and have it implement whatever window shifting logic
you like.

The only limitation of overlays vs tabs in splits is there is no tab bar
showing which windows are present, you see only the currently focused
one, like the stack layout in kitty.
