### ISSUE TITLE
[Help Wanted] strange font size in ligatures

### ISSUE THREAD

**Issue by subframe7536** [kovidgoyal/kitty#7142]
Hello, I'm developing a [monospace font](https://github.com/subframe7536/maple-font/tree/variable). I have encountered a [issue](https://github.com/subframe7536/maple-font/issues/141) with ligatures in kitty terminal and cannot figure out why this happen, so I'm here asking for help.

For example, in `##`, all `#` will be replaced a new glyph that have logger horizon line to fix the gap, but unexpectedly, the font size is decreased. You can see more details in the [original issue](https://github.com/subframe7536/maple-font/issues/141)

**Comment by kovidgoyal** [comment]
The font size will be decreased when the glyph does not fit in the
available space for it. Your replacement glyph needs to be the exact
same length including leading etc as the N original glyphs in a
monospace font.
