### ISSUE TITLE
`diff` kitten feature enhancements for terminal power users

### ISSUE THREAD

**Issue by razcore-rad** [kovidgoyal/kitty#7143]
**Is your feature request related to a problem? Please describe.**
What stops the `diff` kitten being a useful tool in my opinion are these two lacking features:
1.  Select and transfer hunks from one file to the other.
2. When running on directories it should present a browser so we can select which files to open instead of diffing one-by-one.

**Describe the solution you'd like**
For 1. - be able to select hunks with the keyboard and transfer them to the other file, similar to how hints work. For example we could have `ctrl+shift+p>k` to bring up the interface for selecting a hunk with the numbering/lettering system. Then if the hunk does exist in one file and not the other it should be copied over. Maybe a `ctrl+shift+p>d` for deleting hunks. I'm sure we can come up with a reasonable behavior. We also need some undo/redo or cancel operation somehow.

For 2. - something like a dual panel similar to `meld` would be nice where files that have differences are color-coded, then we should be able to select which file we want to open in the per-file diff view.

**Describe alternatives you've considered**
Replace using the `diff` kitten with `meld` which is a GUI app, I'd rather stay in `kitty` if possible.

**Additional context**
Example `meld` selection panel for directory diff:
![image](https://github.com/kovidgoyal/kitty/assets/1177508/f6b62095-99f9-4f8c-bdba-2fdb6823ccd5)

Example `meld`  transferring from one file to the other in per-file diff view:
![image](https://github.com/kovidgoyal/kitty/assets/1177508/ce6c9085-67b9-4589-baed-2d46dc70ee2b)

**Comment by kovidgoyal** [comment]
The diff kitten is exactly that, diff. Patchset management features are
out of scope for it.
