### ISSUE TITLE
Flexible width for tab_title_template

### ISSUE THREAD

**Issue by up-to-you** [kovidgoyal/kitty#7148]
**Is your feature request related to a problem? Please describe.**
Currently there is an option to assign any string literal to `tab_title_template` and accomplish desired tab width but fixed. There is no way to make tab title width flexible such that previous tabs shrink in width if new tab title overflow screen width.

**Describe the solution you'd like**
Better to provide an example:
- tab title width is assigned to 40%
- 2 tabs occupy 80%
- when the third tab opens previous tabs shrink down to 33.3% and third tab width also adjusts down to 33.3%

**Comment by kovidgoyal** [comment]
Not something I am interested in, but note that you can completely
customize how tabs are drawn using whatever algorithm you prefer 
. See
https://github.com/kovidgoyal/kitty/discussions/4447 for examples.
