### ISSUE TITLE
Full screen Kitty window on dual monitors in Ubuntu flickers/bleeds/swaps into the 2nd screen

### ISSUE THREAD

**Issue by pbower** [kovidgoyal/kitty#7152]
**Describe the bug**
When moving to full-screen CTRL-SHIFT F11, the Kitty Window bleeds into the 2nd monitors position, causing flickering,  resolution changes, and flipping to appear on the other monitor in Ubuntu 22.04.4 LTS.

Tested on dual screen 3840 x 2160 150% scale 60hz setup (28" Lenovo monitors).

**To Reproduce**
1. Open Kitty Terminal
2. Ctrl-Shift-F11 Full-screen
3. After approx 60 seconds, screen will intermittently flicker and change resolution, swapping kitty to the other monitor's screen, and for e.g. affecting the resolution and positioning of other windows in the environment (see github issue pasted).  In this case, I had firefox in fullscreen on the other monitor.
4. Refer screenshots below

**Screenshots**
The set resolution (prior to fullscreen):
![image](https://github.com/kovidgoyal/kitty/assets/37089506/b355fcda-46d2-434d-a103-865b7febf080)

Issue occuring after 60 seconds (resolution change + swap of terminal to the other monitor, plus then changed resolution of other programs).
![image](https://github.com/kovidgoyal/kitty/assets/37089506/9ec39663-8239-482a-8435-a3bb9086e986)
![image](https://github.com/kovidgoyal/kitty/assets/37089506/d3960c62-e69e-4584-b860-bdff607a31a1)

**Environment details**
```
        active_tab_background   #729fcf   
        active_tab_foreground   #0f0f0f   
        background              #0f0f0f   
        color0                  #2e3436   
        color1                  #cc0000   
        color10                 #55ff55   
        color11                 #fce94f   
        color12                 #729fcf   
        color13                 #ad7fa8   
        color14                 #34e2e2   
        color15                 #eeeeec   
        color2                  #55ff55   
        color3                  #c4a000   
        color4                  #729fcf   
        color5                  #75507b   
        color6                  #06989a   
        color7                  #d3d7cf   
        color8                  #555753   
        color9                  #ef2929   
        foreground              #d0cfcc   
        inactive_tab_background #2e3436   
        inactive_tab_foreground #d0cfcc   

Important environment variables seen by the kitty process:
        PATH                                /home/pbower/.cargo/bin:/home/pbower/.local/bin:/home/pbower/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:>
        LANG                                en_AU.UTF-8
        SHELL                               /usr/bin/zsh
        DISPLAY                             :1
        USER                                pbower
        XDG_SESSION_TYPE                    x11
        XDG_SESSION_CLASS                   user
        XDG_RUNTIME_DIR                     /run/user/1000
        XDG_MENU_PREFIX                     gnome-
        XDG_CURRENT_DESKTOP                 ubuntu:GNOME
        XDG_SESSION_DESKTOP                 ubuntu
        XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/share/gnome:/home/pbower/.local/share/flatpak/exports/share:/var/lib/flatpak/export>
        XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg

```

**Additional context**
- The issue does not happen with GNOME terminal and/or other programs (tested). It is Kitty specific and consistent at least in this environment. 
- I have turned off all GNOME extensions prior to testing.
- There is no TMUX or other terminal items running - it is clean Kitty.
- It occurs with kitty --config NONE.
- It may occur more when the text is increased with SHIFT-CTRL-+, but I cannot be certain this is a trigger.

**Comment by kovidgoyal** [comment]
kitty does not change resolution by itself, ever. That will be coming from your window manager. You truncated the debug output in your bug report so I cant be sure, but I am guessing you are running wayland. Wayland especially with GNOME is full of bugs. I suggest you make your life a lot simpler and avoid it like the plague that it is.
