### ISSUE TITLE
[question] Why is the font_size_delta option gone?

### ISSUE THREAD

**Issue by metalelf0** [kovidgoyal/kitty#716]
Hi, I used to set font_size_delta to 1 to allow having a finer control over my font size. However starting kitty with the `--debug-font-fallback` switch I've noticed that the option is now ignored, and the default delta when you change font size with keyboard shortcuts is 2 px. May I know what's the reasoning behind this? Wouldn't 1px be a better default? Thanks and keep up the great work!

**Comment by kovidgoyal** [comment]
Because you can change the delta directly in the key binding now. https://sw.kovidgoyal.net/kitty/conf.html#font-sizes

**Comment by metalelf0** [comment]
@kovidgoyal thank you, and sorry, missed it in the doc :)
