### ISSUE TITLE
Monaspace not working

### ISSUE THREAD

**Issue by etherswangel** [kovidgoyal/kitty#7166]
**Describe the bug**
Font [monaspace](https://github.com/githubnext/monaspace) doesn't work in kitty after a recent update. I can still see it in font-book and it works in vscode.

**To Reproduce**
1. install ~monospace~ monaspace
2. font_family           Monaspace
3. restart kitty
4. it's using the default font

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

kitty 0.32.2 (925043d645) created by Kovid Goyal
Darwin Walkers-MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031 arm64
ProductName:		macOS ProductVersion:		14.2.1 BuildVersion:		23C71
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/walker/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.95
enable_audio_bell    False
enabled_layouts      ['tall', 'fat', 'horizontal']
font_family          Monaspace
font_size            13.0
macos_option_as_alt  3
scrollback_lines     100000
window_padding_width FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	kitty_mod+enter →  new_window
	kitty_mod+t →  new_tab
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window
Changed shortcuts:
	cmd+enter →  new_window_with_cwd
	cmd+t →  new_tab_with_cwd
Colors:
	background           #2e3440   
	color0               #3b4252   
	color1               #bf616a   
	color10              #a3be8c   
	color11              #ebcb8b   
	color12              #81a1c1   
	color13              #b48ead   
	color14              #8fbcbb   
	color15              #eceff4   
	color2               #a3be8c   
	color3               #ebcb8b   
	color4               #81a1c1   
	color5               #b48ead   
	color6               #88c0d0   
	color7               #e5e9f0   
	color8               #4c566a   
	color9               #bf616a   
	cursor               #81a1c1   
	foreground           #d8dee9   
	url_color            #ffffff   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/homebrew/bin/fish
	DISPLAY                             /private/tmp/com.apple.launchd.PrYGgI3fbp/org.xquartz:0
	USER                                walker

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
