### ISSUE TITLE
Box drawing char misalign

### ISSUE THREAD

**Issue by xzbdmw** [kovidgoyal/kitty#7167]
**Describe the bug**
I have these box draing chars          
`"─", "│", "─", "│", "╭", "╮", "╯", "╰" `
they look like this in kitty, the curve width is strange, I don't know whether it is expected.
<img width="244" alt="截屏2024-02-28 22 10 38" src="https://github.com/kovidgoyal/kitty/assets/97848247/9302b6b7-3d57-4def-b08c-80313fb70bf2">

**To Reproduce**
Paste these char into shell prompt

**Comment by kovidgoyal** [comment]
That is how they are supposed to look.
![screenshot](https://github.com/kovidgoyal/kitty/assets/1308621/25a92881-22e6-4a9a-a250-da2fe4cdc876)
