### ISSUE TITLE
Older tic versions warning

### ISSUE THREAD

**Issue by horta** [kovidgoyal/kitty#717]
After entering

```
infocmp xterm-kitty | ssh myserver tic -x -o \~/.terminfo /dev/stdin
```

I get

```
"/homes/horta/.xterm-kitty.ti", line 2, col 22, terminal 'xterm-kitty': older tic versions may treat the description field as an alias
```

everytime I log into that server.

Kitty: 0.11.3
From: MacOS
Server: Linux

Let me know if you need further information.

**Comment by kovidgoyal** [comment]
There is not much I can do about that, I dont have control over what tic outputs. Use

```
kitty +kitten ssh myserver
```

instead, which redirects tic output to null.

**Comment by horta** [comment]
Sorry, I didnt explain very well.

I mean I get the above warning everytime I log into the server using ssh, after creating that `.xterm-kitty.ti`. And if I enter

```
kitty +kitten ssh myserver
```

I get the following warning:

```
"/homes/horta/.xterm-kitty.ti", line 2, col 22, terminal 'xterm-kitty': older tic versions may treat the description field as an alias
nvm is not compatible with the npm config "prefix" option: currently set to "/nfs/software/stegle/system/linuxbrew2"
Run `npm config delete prefix` or `nvm use --delete-prefix v9.11.1 --silent` to unset it.
```

**Comment by kovidgoyal** [comment]
Yes you will gwet that warning because every time you log into the server with that command, tic is run. You dont need to use the command more than once for a particular server, after that you can simply use plain ssh and tic will not be run and you wont get the warning.

**Comment by horta** [comment]
Sure, but I get the first warning I showed by simpying using plain ssh.

I do

```
ssh yoda-login.ebi.ac.uk
```

I get

```
"/homes/horta/.xterm-kitty.ti", line 2, col 22, terminal 'xterm-kitty': older tic versions may treat the description field as an alias
```

**Comment by kovidgoyal** [comment]
Then something in your shell startup scripts on the server is running tic. Find that and remove it and you will be fine.
