### ISSUE TITLE
update to python3.12

### ISSUE THREAD

**Issue by k2662** [kovidgoyal/kitty#7171]
python3.12 is way faster than python 3.11 and could speed up kitty significantly.

**Comment by kovidgoyal** [comment]
It's not way faster, its a few percent faster and no python is in any
performance critical code path in kitty anyway, so you will not get any
significant speedups from upgrading python. But, feel free to build
kitty from source against whatever version of python you like to test
for yourself.
https://sw.kovidgoyal.net/kitty/build/
