### ISSUE TITLE
Other options in detach_window

### ISSUE THREAD

**Issue by rainerborene** [kovidgoyal/kitty#7172]
@kovidgoyal I have noticed that there are more options for `detach_window` present in the codebase. I would like to know if they are supported like `new-tab-right` and `new-tab-left` as these are not documented yet (idk if it really works). I tried the following keyboard mapping but it opens a new window instead:

```map ctrl+f>! detach_window new-tab-right```

ps: kitty is amazing btw. I have just ditched tmux for kitty :D

**Comment by ces42** [comment]
They are supported (and documented) in the current source, but there hasn't been a release including that code yet.

**Comment by rainerborene** [comment]
@ces42 Thanks for the heads up! Lets wait for the next release then. :metal:
