### ISSUE TITLE
Linux Libertine Mono doesn't load

### ISSUE THREAD

**Issue by Poly2it** [kovidgoyal/kitty#7176]
**Describe the bug**
[Linux Libertine Mono](https://www.fontsquirrel.com/fonts/linux-libertine) does not load even after following the steps provided at https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font to force fontconfig to set the width. What differentiates this mono-space fonts from others?

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<match target="scan">
    <test name="family">
        <string>Linux Libertine Mono</string>
    </test>
    <edit name="spacing">
        <int>100</int>
    </edit>
</match>
</fontconfig>
```

**To Reproduce**
1. Install Linux Libertine Mono
2. Observe that the font does not show up after the patch: `fc-list : family spacing outline scalable | grep -e spacing=100 -e spacing=90 | grep -e outline=True | grep -e scalable=True | grep Linux`
3. Neither Kitty will accept it

**Comment by Poly2it** [comment]
I put the font through [FontSquirrel's webfont generator](https://www.fontsquirrel.com/tools/webfont-generator), which made Kitty able to load it, but the solution is not optimal.

**Comment by kovidgoyal** [comment]
You need to get fontconfig to recognize the font as monospaced. What
criteria fontconfig uses, you would need to ask the fontconfig
developers.
