### ISSUE TITLE
Search current terminal contents

### ISSUE THREAD

**Issue by JJGO** [kovidgoyal/kitty#718]
Is there a way to search and highlight for specific words in the current terminal contents like `Ctrl+F` does in iTerm2?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/#scrollback

**Comment by sergiotapia** [comment]
ctrl shift h just gives me a `:` prompt that doesn't let me type in words to search.

How can I search simply like in iterms2? I can type cmd f and type text which highlights in real time

**Comment by SolitudeSF** [comment]
its less (or whatever is default on macos). type `/` and search term, or '?' to search backwards.

**Comment by up-to-you** [comment]
If someone interested in fuzzy search at current window (fzf required):
```
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/local/bin/fzf --no-sort --no-mouse --exact -i
```

**Comment by rjhilgefort** [comment]
@up-to-you That's fantastic! Thanks! Is there a flag or some way to not invert the scrollback output?

**Comment by emirom** [comment]
> If someone interested in fuzzy search at current window (fzf required):
> 
> ```
> map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/local/bin/fzf --no-sort --no-mouse --exact -i
> ```
> 
> For me it was very convenient after switching from Alacritty to Kitty (mb it could be mentioned in dock)

did not diagnose the `map` repo. may you link it?

**Comment by Kareem-Medhat** [comment]
You can leave the scrollback output uninverted by passing the `--tac` flag to the fzf command.
`map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/local/bin/fzf --no-sort --no-mouse --exact -i --tac`

**Comment by salfum** [comment]
I'll just leave it here in case someone will seek. https://github.com/trygveaa/kitty-kitten-search

**Comment by brentluna** [comment]
> If someone interested in fuzzy search at current window (fzf required):
> 
> ```
> map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/local/bin/fzf --no-sort --no-mouse --exact -i
> ```
> 
> For me it was very convenient after switching from Alacritty to Kitty (mb it could be mentioned in dock)

@up-to-you is there a way to bring you to that point in the output when you select a found result? hoping to be able to see more context around certain points

**Comment by wintermelons** [comment]
@brentluna from what I can tell, Kitty would need to support a `scroll_to_line` function that `fzf` can feed into, which it currently does not have.
https://sw.kovidgoyal.net/kitty/actions/?highlight=scroll_#scrolling

**Comment by kovidgoyal** [comment]
You are opening the scrollback in an external program in this case. That program needs to manage scrolling, for example if instead of fzf you use less you can scroll to any line.

**Comment by kovidgoyal** [comment]
On Wed, Jun 01, 2022 at 11:12:36AM -0700, David Song wrote:
> Good point - `fzf` runs in an overlay window. Perhaps we can use `kitty @ scroll-window` (assuming remote control is enabled) to scroll the original window if `fzf` can return a line number?

That's certainly possible.

**Comment by kylepaulsen** [comment]
For the launch fzf solution, anyone know how to copy what you select into the clipboard?
I tried piping into yank for example, but nothing happens.

```
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/local/bin/fzf --no-sort --no-mouse --exact -i --tac | yank
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/clipboard/

**Comment by kylepaulsen** [comment]
> https://sw.kovidgoyal.net/kitty/kittens/clipboard/

This could also work, but piping to it seems to make ctrl + f do nothing. In fact even piping to echo makes the keybind do nothing. 

Thanks for the help btw.

**Comment by kovidgoyal** [comment]
You cant use a pipe in a launch command. You need to wrap it in sh -c

**Comment by kylepaulsen** [comment]
That did the trick! Thank you!

In case anyone else wants this:
```
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /bin/sh -c "/usr/local/bin/fzf --no-sort --no-mouse --exact -i --tac | kitty +kitten clipboard"
```

**Comment by Zackhardtoname** [comment]
> its `less` (or whatever is default on macos). type `/` and search term, or `?` to search backwards.

Could anyone kindly clarify how we use `less` or `/` to search?
Say we have a new prompt, `/` or `less` would just be typed input, as expected, but wouldn't search past output.

**Comment by choznerol** [comment]
> > > ctrl shift h just gives me a `:` prompt that doesn't let me type in words to search.
> > >
> > > How can I search simply like in iterms2? I can type cmd f and type text which highlights in real time
> > its `less` (or whatever is default on macos). type `/` and search term, or `?` to search backwards.
> 
> Could anyone kindly clarify how we use `less` or `/` to search? Say we have a new prompt, `/` or `less` would just be typed input, as expected, but wouldn't search past output.

Given following terminal session, with any configuration change:

```
my_cool_prompt> echo 123 > test.txt
my_cool_prompt> cat test.txt
123
my_cool_prompt> _
```

1. Type <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>H</kbd> and you will get `:` just like in `less`:

```
my_cool_prompt> echo 123 > test.txt
my_cool_prompt> cat test.txt
123
my_cool_prompt> 
:
```

2. Type <kbd>/</kbd> and you will get a search prompt `/`:

```
my_cool_prompt> echo 123 > test.txt
my_cool_prompt> cat test.txt
123
my_cool_prompt> 
/
```

3. Type `"23"` to search and highlight both `23` (denoted `[23]`):

```
my_cool_prompt> echo 1[23] > test.txt
my_cool_prompt> cat test.txt
1[23]
my_cool_prompt> 
/23
```

4. You can now iterate through them with <kbd>n</kbd> and <kbd>Shift</kbd>+<kbd>n</kbd>

**Comment by Zackhardtoname** [comment]
Oh I didn't know about `control shift h`. Thank you!

**Comment by PascalLeMerrer** [comment]
I just tried to set up the fzf solution, as I already use this tool, and started using kitty recently.
ctrl+f looks like it opens an overlay and close it immediately.
Is the fzf tip stll working for some of you?

**Comment by Jackenmen** [comment]
I no longer use fzf solution but yes, this continues to work:
```
map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i --tac
```

Personally, I switched to using `less`:
```
map ctrl+shift+f combine : show_scrollback : send_text normal,application /
```

**Comment by PascalLeMerrer** [comment]
It was just the path to fzf, which is hardcoded in the examples above, which was not the right one for my computer.
I mapped both solutions to different keys and will experiment with them.
Thanks for your help @Jackenmen

**Comment by Cruising0904** [comment]
> Oh I didn't know about `control shift h`. Thank you!

How to map this to other key? 
I use ctrol+shift+h for navigation. I looked through conf file is not defined... 

and no marks show up to select..
![image](https://user-images.githubusercontent.com/29267295/221757923-d368e671-f317-489a-9697-aa42d7268899.png)
it looks very nice though

**Comment by page-down** [comment]
@Cruising0904

https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Browse-scrollback-buffer-in-pager

> ... I looked through conf file is not defined ...

If it is the default commented configuration file, this is just a few lines below the content of your screenshot.

**Comment by doplumi** [comment]
these don't work when running inside a full-screen app like tmux, correct?

**Comment by page-down** [comment]
> ... when running inside ...

The terminal runs these CLI programs instead of running inside, so anything you can see is available as text.

**Comment by doplumi** [comment]
>...anything you can see...
I'm not sure I understand your comment. I can see stuff that is inside tmux or vi obviously, but I can't search it. Unlike iTerm2 `ctrl+f`, for example. Is that accurate?

**Comment by page-down** [comment]
@doplumi
> I'm not sure I understand your comment. ...

For the `full-screen apps like tmux` you mentioned, these programs usually enter the terminal alternate screen and only the text being displayed on the screen (not the text in the tmux scrollback that needs to be scrolled up and down to be seen) is available to the terminal and will be sent to the pager (which is less by default, `Ctrl+Shift+H`) to search (press `/` in less).

> ... but I can't search it ... Unlike iTerm2 ctrl+f ...

When I press Ctrl+Shift+H, the configured pager is displayed and I can press `/` to search the text.

And I can also search by the custom neovim pager I gave in the link below.
https://github.com/kovidgoyal/kitty/issues/719#issuecomment-952039731

I don't know whether you have problems using it, but if you need help, you need to explain what documentation you have read, what steps you have tried, and then were unable to achieve the functionality described in the documentation or the goals discussed here.

**Comment by TroySigX** [comment]
> Good point - `fzf` runs in an overlay window. Perhaps we can use `kitty @ scroll-window` (assuming remote control is enabled) to scroll the original window if `fzf` can return a line number?

Can you please share how to do this?

**Comment by danielhoherd** [comment]
For anybody looking for the answer, the new docs URL is https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer

**Comment by eliahreeves** [comment]
I found this discussion very helpful, so I thought I'd share my approach.
```
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback nvim -c 'set nobackup nowritebackup' -c 'set buftype=nofile' -c 'normal G'
```
Not strictly for searching, I like it for copying with vim bindings.

**Comment by CyrenArkade** [comment]
This uses bat, it seems to work well enough. It highlights the fzf query and uses the full height of the preview window to show context around it.

`map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback --stdin-add-formatting --copy-env /path/to/below/script`

```bash
#!/usr/bin/env bash

show_context() {
    local n=$1
    local height=$FZF_PREVIEW_LINES

    ((height > total_lines)) && height=$total_lines

    local start=$((n - height / 2))
    local end=$((start + height))

    if ((start < 1)); then
        start=1
        end=$height
    elif ((end > total_lines)); then
        end=$total_lines
        start=$((end - height + 1))
        ((start < 1)) && start=1
    fi

    bat --color always --decorations never \
        --line-range $start:$end \
        --highlight-line $((n + 1)) \
        "$stdin"
}

stdin=$(mktemp)
cat > "$stdin"

total_lines=$(( $(wc -l < "$stdin") + 1 ))

export stdin
export total_lines
export -f show_context

export SHELL=bash

fzf --ansi \
    --no-sort --tac \
    --exact -i \
    --preview 'show_context {n}' \
    --preview-window border-none \
    --preview-window noinfo \
    < "$stdin"
```

**Comment by MehmetMHY** [comment]
I liked the solutions in this feed, but none of them really worked for me personally. But after some testing, I think I found something that I love and might be useful to some people.

Add the following two lines to your `kitty.conf` file:

```bash
scrollback_lines 1000000000
map ctrl+f launch --stdin-source=@screen_scrollback --type=overlay hx
```

By adding these configs, it does a couple things. First it increase the line limit for a single terminal section which I personally love. And it maps **CTRL-F** to grab the content from your current terminal section and send it to the [Helix](https://github.com/helix-editor/helix) text editor were you can easily do a search. Now, Helix is my preferred text editor but you can easily modify this config to use your preferred choice of a text editor like NeoVim, Emacs, Vim, Nano, etc.

All the solutions here are great. This is just another idea that I personally use and love. I hope this helps!

**Comment by samuelborn** [comment]
It is also possible to remove the trailing newline character when copying:

```
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /bin/sh -c 'fzf --no-sort --no-mouse --exact -i --tac | tr -d "\n" | kitty +kitten clipboard'
```

**Comment by blakkd** [comment]
Really thanks to @up-to-you for their initial sexy solution :)
However, I also faced the lack of context issue, along with select-->copy using the mouse.

I ended up using https://github.com/mikesmithgh/kitty-scrollback.nvim as suggested in https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer, and it's working out of the box! At least for me, no need to look further:
- CTRL-SHIFT-H --> /<term_you_search> --> ENTER --> N for next result; SHIFT-N for previous
- whole scrollback context
- select and copy with mouse
- also comes with a CTRL-SHIFT-G for the same but only inside the output of the last command
of course, you can modify the bindings in kitty.conf, and even bind it to ctrl-f if you want :)

Cheers and thanks everyone :)

**Comment by its-izhar** [comment]
I know this is a resolved issue, but just leaving this solution here for anyone in future who stumbles here. My solution is improving upon @CyrenArkade's solution from  https://github.com/kovidgoyal/kitty/issues/718#issuecomment-3030621503 - to add many improvements, such as:
 - Allow scrolling through entire scrollback buffer by preview scroll up/down through keybinds (ctrl+b/f) and mouse
 - Remove unnecessary math for always showing result centered in the preview window and let fzf handle it instead

```bash
#!/usr/bin/env bash

# Purpose: Fuzzy-find through the Kitty scrollback buffer and copy the selected line to clipboard
# Method: Pipe the scrollback buffer into this script, then use fzf to search and select a line
# Preview: Use bat to show context around the selected line in the preview window

stdin=$(mktemp)
cat >"$stdin"

show_context() {
    local n=$1
    local fin=$2

    # n is zero-based, but bat's --highlight-line is one-based
    bat \
        --color=always --decorations=never \
        --highlight-line $((n + 1)) $fin
}

# In case fzf spawns a new shell, ensure it uses bash
export -f show_context

# Filter through fzf, previewing with bat, and copy the result to clipboard
fzf \
    --ansi --no-sort --exact --tac \
    --preview-label 'Scrollback Buffer (Search Result Highlighted)' \
    --preview "show_context {n} $stdin" \
    --preview-window 'up,80%,border-rounded,+{n}/2' \
    --bind 'ctrl-c:abort' \
    --bind 'ctrl-b:preview-half-page-up' \
    --bind 'ctrl-f:preview-half-page-down' \
    <"$stdin" |
    (tr -d "\n" | kitty +kitten clipboard)

```

Then map it to your shortcut in kitty.conf:
```
map kitty_mod+f launch --type=overlay --stdin-source=@screen_scrollback --stdin-add-formatting --copy-env ~/bin/fzf_ksb_find.sh
```

**Comment by wrobelda** [comment]
> I know this is a resolved issue, but just leaving this solution here for anyone in future who stumbles here. My solution is improving upon [@CyrenArkade](https://github.com/CyrenArkade)'s solution from [#718 (comment)](https://github.com/kovidgoyal/kitty/issues/718#issuecomment-3030621503) - to add many improvements

Hey there, tried your solution but somehow I am getting an empty section in the middle of the window and I am not exactly what should be shown here? I assume it should be the preview around the line selected, but am at loss how to debug ths.

<img width="2553" height="904" alt="Image" src="https://github.com/user-attachments/assets/09d0886b-c8d7-4774-a1f6-cc5eb79809ce" />

EDIT: problem is I am using fish and your script does not actually spawn in bash despite saying so, as evidenced by pressing ctrl-f: `fish: Unknown command: show_context` . Solution is to execute fzf with explicit shell command, i.e.
```
fzf \
    --with-shell='bash -c' \
(...)
```

**Comment by its-izhar** [comment]
@wrobelda yes, for FZF, the default command to spawn the child processes is `$SHELL -c` if `$SHELL` is set, otherwise `sh -c`. 
In the script, you can set the `export SHELL=/bin/bash` and then you don't have to use `--with-shell` option in fzf, that's a cleaner way IMO.

As a side note, I've made a much more improved version of the script since last time and been using it daily since then, you can give it a try if you'd like. It has many improvements and additional features such as using the same script to fuzzy search through entire scrollback or just the last command output, for example.

NOTE: you'd still need to set the `SHELL` or use `--with-shell` in your case, I'm just pasting my script here as is:

```shell
#!/usr/bin/env bash

# fzf_ksb_find.sh - Fuzzy-find through Kitty scrollback buffer
#
# Launched by Kitty as an overlay window. Receives the scrollback buffer
# (or last command output) on stdin, lets the user search it with fzf,
# and copies the selected line to the system clipboard.
#
# Invocation (from kitty.conf):
#   map kitty_mod+k launch --type=overlay \
#       --stdin-source=@screen_scrollback --stdin-add-formatting \
#       --env FZF_STDIN_SOURCE=@screen_scrollback \
#       fzf_ksb_find.sh
#
#   map kitty_mod+j launch --type=overlay \
#       --stdin-source=@last_cmd_output --stdin-add-formatting \
#       --env FZF_STDIN_SOURCE=@last_cmd_output \
#       fzf_ksb_find.sh
#
# Environment (set by Kitty before this script runs):
#   FZF_STDIN_SOURCE  - "@screen_scrollback" or "@last_cmd_output"
#   KITTY_WINDOW_ID   - numeric ID of the Kitty window
#
# Requires: fzf, bat
#
# Keybindings:
#   Enter   - select line and copy to clipboard
#   Ctrl-C  - abort (nothing copied)
#   Esc     - abort (nothing copied)
#   Ctrl-B  - scroll preview up (half page)
#   Ctrl-F  - scroll preview down (half page)

# --- Save stdin (scrollback buffer) to a temp file for bat preview ---
# fzf reads from this file via --input redirect, and bat reads it for the
# preview pane. The temp file is cleaned up on exit regardless of how the
# script terminates.
source=$(mktemp)
trap 'rm -f "$source"' EXIT
cat >"$source"

# Build the label string shown in the preview border.
# Both vars are set by Kitty before launching this script.
label_str="$FZF_STDIN_SOURCE:$KITTY_WINDOW_ID"

# --- Launch fzf ---
# --ansi            : interpret ANSI color codes in scrollback input
# --no-sort         : preserve original line order (don't rank by match score)
# --exact           : use exact substring matching instead of fuzzy matching
# --tac             : reverse input so newest lines appear first
# --query ''        : start with an empty search query
#
# Preview: bat shows the full scrollback file with the selected line
# highlighted. {n} is fzf's 0-indexed line number of the current selection,
# so we add 1 for bat's 1-indexed --highlight-line.
#
# Preview scroll: +{n}+1/2 scrolls the preview so the highlighted line
# (1-indexed) is centered vertically in the preview window.
selected=$(fzf \
        --ansi --no-sort --exact --tac \
        --query '' \
        --prompt 'Search Scrollback> ' \
        --preview-label ' Scrollback Buffer ['"$label_str"'] ' \
        --preview 'bat \
                    --color=always --decorations=never \
                    --highlight-line $(( {n}+1 )) '"$source"'' \
        --preview-window 'up,75%,+{n}+1/2' \
        --bind 'result:transform-list-label:
        if [[ -z $FZF_QUERY ]]; then
          echo " $FZF_MATCH_COUNT items ($FZF_STDIN_SOURCE:$KITTY_WINDOW_ID) "
        else
          echo " $FZF_MATCH_COUNT matches for [$FZF_QUERY] ($FZF_STDIN_SOURCE:$KITTY_WINDOW_ID) "
        fi
        ' \
        --input-border --color 'input-border:#996666,input-label:#ffcccc' \
        --list-border --color 'list-border:#669966,list-label:#99cc99:bold' \
        --preview-border --color 'preview-border:#9999cc,preview-label:#ccccff:bold' \
        --bind 'ctrl-c,esc:abort' \
        --bind 'ctrl-b:preview-half-page-up' \
        --bind 'ctrl-f:preview-half-page-down' \
        <"$source")

# --- Copy selected line to clipboard ---
# Only copy if fzf exited successfully (user made a selection).
# On abort (Ctrl-C/Esc), fzf exits non-zero and we skip the copy
# to avoid clearing the clipboard with empty input.
if [[ -n $selected ]]; then
        printf '%s' "$selected" | kitten clipboard
fi
```

**Comment by wrobelda** [comment]
@its-izhar I think this deserves a repo of its own, will be easier to track your changes and update the script locally!
