### ISSUE TITLE
Cursor doesnt change

### ISSUE THREAD

**Issue by quadans** [kovidgoyal/kitty#7185]
I tried `shell_integration  no-cursor`  in kitty.conf to be able to change anything to the cursor like blinking (`cursor_blink_interval 0` ) or underline (cursor_shape underline), but nothing happens. 
The config itself gets loaded because things like `font_size xx` take effect. Also, if i misstype something on purpose like `cursor_shape udline` it gives me an error when I reload (ctrl shift f5).
So the setting about the cursor just get ignored and I dont know why.

Shell is zsh and OS is arch.

With Ctrl+Shift+F6, Config options different from defaults:
cursor_shape 3
shell_integration frozenset({'no-cursor'})

So it seems kitty reads the changes fine but doesnt apply them.

**Comment by kovidgoyal** [comment]
Works fine for me. I suggest you follow the issue tmeplate provide the
requested information, then you might get more asistance.

**Comment by quadans** [comment]
kitty 0.31.0 created by Kovid Goyal
Linux hax 6.7.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 x86_64
Arch Linux 6.7.6-arch1-1 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /sbin/zsh
Loaded config files:
  /home/pal/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close 0
cursor_shape            3
enable_audio_bell       False
font_family             CommitMonoNerdFont
font_size               18.0
shell_integration       frozenset({'disabled'})
Colors:
	background              #0e1419   
	color1                  #ff3333   
	color10                 #e9fe83   
	color11                 #fff778   
	color12                 #68d4ff   
	color13                 #ffa3aa   
	color14                 #c7fffc   
	color2                  #b8cc52   
	color3                  #e6c446   
	color4                  #36a3d9   
	color5                  #f07078   
	color6                  #95e5cb   
	color7                  #ffffff   
	color8                  #323232   
	color9                  #ff6565   
	cursor                  #87ff87   
	foreground              #e5e1cf   
	selection_background    #243340   
	selection_foreground    #0e1419   

Important environment variables seen by the kitty process:
	PATH                                /sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                C.UTF-8
	EDITOR                              nvim
	SHELL                               /sbin/zsh
	DISPLAY                             :0
	USER                                pal
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 xmonad
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/pal/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

**Comment by kovidgoyal** [comment]
Works fine for me with:
kitty --config=NONE -o shell_integration=disabled -o cursor_shape=underline -o shell=cat
and also with:
kitty --config=NONE -o shell_integration=disabled -o cursor_shape=underline -o shell=zsh

If its not working for you with the latter, it means something in your
zshrc is setting the cursor shape. As noted in the docs for the
cursor_shape option it is applied only when the program running in the
terminal doesnt set a cursor shape

**Comment by quadans** [comment]
Funny thing is your debug code also doesnt work for me. It starts the console with normal cursor and not underline. Wth

**Comment by kovidgoyal** [comment]
There is a whole bunch of files involved in zsh startup not just zshrc. Read man zsh for details.

**Comment by quadans** [comment]
I dont have .zshenv, .zprofile, .zlogin or .zlogout. Neither in home dir nor in /etc/
