### ISSUE TITLE
Kitty paste_from_clipboard + <cmd-v> interaction

### ISSUE THREAD

**Issue by luisjakon** [kovidgoyal/kitty#7191]
**Describe the bug**
Kitty does an amazing job at mapping keyboard codes. For the most part everything works out the box. 

However, when using ```map cmd+v paste_from_clipboard``` in the kitty.conf, pasting onto nvim works fine in insert mode, but appends after the first character in normal mode.

I have looked around and cannot figure out how or where to make the changes. It would be an amazing feat to overcome this final annoyance without having to retort to muscle memory to remember normal mode and insert modes paste differently.

I understand this may not be a kitty problem, but I think the problem is so close to an out-of-the-box experience that it should be at least documented somewhere here if a solution can be found.  Many thanks for all the great work!

**To Reproduce**
1. kitty --debug-input --config=NONE vim -u NONE
2. Copy/Paste anything to the app in normal and insert mode
3. Note the location of the cursor and the differences in paste output to screen

**Comment by kovidgoyal** [comment]
That will be a bug in nvim. Report it there. When pasting, a terminal
emulator simply sends the text in the clipboard to the program running
inside it over STDIN. If the program indicates it supports bracketed
paste the terminal emulator wraps the text in bracketed paste escape
codes. nvim should:

1) indicate it supports bracketed paste in both normal and insert modes
2) detect a bracketed paste text received over stdin and paste it
correctly
