### ISSUE TITLE
an option for kitty @ send-text to fail if no terminals match

### ISSUE THREAD

**Issue by cosmikwolf** [kovidgoyal/kitty#7193]
I'd like the kitty @ send-text function to have an option like --match_fail so it will produce an error if no terminals match the send-text match function.
I think this type of option would be beneficial for most of the kitten actions to have.

The current behavior is that the $? (or $status for my fish shell) is 0 even if the matched terminal doesn't exist.

This could also be satisfied by having a kitten @ count  action that would count the number of terminals that match the query. This is satisfied by @ ls, but that requires that I use json libraries to achieve the goal.

**Comment by kovidgoyal** [comment]
--match does return an error when no matches are found in almost all @
actions. send-text is an exception for technical reasons having to do
with how it is implemented. It could possibly be changed, but its not
worth the effort, at least for me. To check if at least one window
matches you can do @ ls --match which will return an error when nothing
matches. No need for JSON libraries.
