### ISSUE TITLE
Feature request: tab_title_program

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#7195]
I find my biggest pain point with Kitty is tab-sprawl where I have 10+ tabs and not no what is where.

I think the greatest tool against tab sprawl is a good naming system for tabs so I can super-efficiently see what is going on in other tabs.

One possible improvement I think would be to render paths like

```
/Users/dteiml/p/abch/wake
```

as

```
~/p/a/w
```

Now, I am not asking this to be implemented. I merely want more flexibility in defining the tab title, ideally through an external program (and take the first line of stdout). Eg A small python program takes 20ms to execute on my machine, I doubt it will be a performance sink

I'd like to be able to do

```
tab_title_program "python3 /path/to/script {title} {tab.active_wd}"
```

Alternatively/additionally, just the path could be provided and it would have to be a python file.

Thank you! 🙏

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.tab_bar_style  in
particular custom
