### ISSUE TITLE
allow selecting and copying text using the keyboard

### ISSUE THREAD

**Issue by KiaraGrouwstra** [kovidgoyal/kitty#7199]
**Is your feature request related to a problem? Please describe.**

I sometimes want to copy some text in the terminal.
I prefer using keyboard over mouse.
It would be nice if there was an option to select and copy text using the keyboard.

**Describe the solution you'd like**

Prior art includes:

- Alacritty's [Vi Mode](https://github.com/alacritty/alacritty/blob/master/docs/features.md#vi-mode)
- WezTerm's [Copy Mode](https://wezfurlong.org/wezterm/copymode.html)

**Describe alternatives you've considered**

- Using a different terminal (😿)
- Using a mouse (😿😿)

**Additional context**
n/a

**Comment by neurocyte** [comment]
You can set the scrollback pager to anything you want. Set it to something that has the keyboard functionality you want. See:

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.scrollback_pager
https://sw.kovidgoyal.net/kitty/actions/#action-show_scrollback

**Comment by ad-chaos** [comment]
There's also a kitten available: https://sw.kovidgoyal.net/kitty/integrations/#id29

**Comment by neurocyte** [comment]
Or for the ultimate nvim integration: https://github.com/mikesmithgh/kitty-scrollback.nvim
