### ISSUE TITLE
[fish shell integration] repaint removes text printed by fish key binding

### ISSUE THREAD

**Issue by iacore** [kovidgoyal/kitty#7200]
**Describe the bug**
text printed by keybind in fish disappear when screen is repaint (such as resizing the window)

**To Reproduce**
1. open new window with `kitty --config NONE fish`
2. run `bind \eg 'echo; git status; git remote -v; echo; commandline -f repaint'`
3. press Alt+g in a git repo
4. resize the window to be wider or narrower (in width)

**Screenshots**

The screenshots below show the whole window width.

After `git init`, I pressed Alt+g, and git information is shown.

![image](https://github.com/kovidgoyal/kitty/assets/74560659/9909270a-0e78-44be-8219-a8f819f6d9cb)

Then, I resize the kitty window to be wider, and the git info text is gone, leaving an empty space.

![image](https://github.com/kovidgoyal/kitty/assets/74560659/843c77a6-2f7b-455f-98d5-4f62c5580e6e)

**Environment details**
```
❯ kitty --version
kitty 0.31.0 created by Kovid Goyal

❯ fish --version
fish, version 3.6.4
```

**Additional context**

Ctrl+Shift+G (show last command output in pager) ignores the output printed by fish keybind. I think this is the appropriate behavior.

Can reproduce with `kitty --config NONE`. Latest fish version (3.7.0) probably works too.

The issue is first discussed in https://github.com/fish-shell/fish-shell/discussions/10289.

**Comment by iacore** [comment]
I have "fixed" the problem by calling `__ksi_mark_prompt_start` at the end.

e.g. `bind \eg 'echo; git status; git remote -v; echo; commandline -f repaint; __ksi_mark_prompt_start'`

**Comment by kovidgoyal** [comment]
I dont know of anyway to fix this. If commandline -f repaint doesnt run
the prompt marking hooks, there is nothing the shell integration script
can do about it. Really, the correct fix for this is for fish to
implement prompt marking itself instead of every terminal emulator
having to write a script for it.
