### ISSUE TITLE
(IBus) second level ignored in punctuation for Pinyin input

### ISSUE THREAD

**Issue by imyxh** [kovidgoyal/kitty#721]
When in IBus Pinyin input, it is usually the case that pressing `;` will input "；" (U+FF1B: fullwidth semicolon) and pressing `shift-;` will input "：" (U+FF1A: fullwidth colon).

In the IBus branch of kitty, however, both key combinations will simply input a fullwidth semicolon.

This is the same for the following keys:
- `，`instead of `《`
- `。` is always entered, never `》`
- `‘` and not `“`
- `【` and not `『`
- `】` and not `』`
- `、` and not `|`

Furthermore, IBus replaces some western punctuation like so:
- `~` becomes `～`
- `!` becomes `！`
- `$` becomes `￥`
- `^` becomes `……`
- `(` becomes `（`
- `)` becomes `）`
- `_` becomes `——`

For those, simply the western punctuation is inserted—even though it is on the second level.

**Comment by kovidgoyal** [comment]
which ibus engine is this exactly? Post the output of 

ibus engine

**Comment by imyxh** [comment]
It's libpinyin.

**Comment by kovidgoyal** [comment]
Should be fine now.
