### ISSUE TITLE
[Question] Is there a way to increase color contrast

### ISSUE THREAD

**Issue by ivankovnatsky** [kovidgoyal/kitty#7216]
Hello, thanks for working on kitty, I really love it, among the current set of
terminals it suits most of my needs and requirements.

Though, recently I wanted to try out a light theme and somehow text looked
rather dim, even though similar colors in Terminal and let's say iTerm2 is
fine, at least I can find a theme that would suffice.

I've tried multiple light themes from the `kitten themes` light tab arsenal and
almost all of them are dim. I'm not sure if I'm asking what will help me, but
I thought that possibly by increasing contrast that will render the colors not
so dim. I've tried this in iTerm2: <img width="706" alt="image"
src="https://github.com/kovidgoyal/kitty/assets/75213/1a535738-7e50-4b6a-998c-387f54876cbd">,
it did the trick.

I don't have any very complex color and other terminal tweaks, everything pretty masic:

```conf
include current-theme.conf

font_family Hack Nerd Font
font_size 13

allow_remote_control yes
adjust_line_height 115%
hide_window_decorations titlebar-only
cursor_blink_interval 0
copy_on_select yes
draw_minimal_borders yes
tab_bar_edge top
tab_title_template "{index}: {tab.active_exe}"
macos_option_as_alt yes

enabled_layouts tall, grid

map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right

map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right

# This is the remap of default value
# Was ctrl+shift+l
map ctrl+shift+space next_layout

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
```

Currently trying out this theme:
https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/Tango_Light.conf
and again tried it least half of them that is surely, with dark themes no
issues at all.

Thanks,

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy

**Comment by ivankovnatsky** [comment]
OK, tried that, did not work for me.
