### ISSUE TITLE
terminal identification (for example, with DECRPTUI/DA3)

### ISSUE THREAD

**Issue by determin1st** [kovidgoyal/kitty#7217]
im able to identify `libvte` terminals and `xterm` with DA3 ESC sequence, sending `<ESC>[=0c` gives a reply `<ESC>P!|<encoded_id><ESC>\` which allows to identify those terminals. encoding is ascii characters in hex representation, xterm didnt make it human readable (which is fine), it sends `00000000` that is simply 4 zero bytes when decoded, `kitty` could send `00000001` or alike.

what is the `kitty`s chosen way of identification?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/query_terminal/
