### ISSUE TITLE
ctrl+space sometimes fails

### ISSUE THREAD

**Issue by ggsalas** [kovidgoyal/kitty#722]
Hi, I have noted that sometimes the keys `ctrl+space` not work with neovim. I think this bug could be related to [kitty keyboard-handling](https://sw.kovidgoyal.net/kitty/protocol-extensions.html#keyboard-handling) but I don't now how to fix that. 

When I see this error in neovim:
- if do `:verbose map <c-space>`, I get my mapping. 
- if I do `<c-v> <c-space>` on insert mode I get a blank space

But when is working:
- if I do `<c-v> <c-space>` on insert mode I get `<C-Space>`

Thanks!

**Comment by kovidgoyal** [comment]
There isn't anything kitty can do about that. Ctrl+space sends a null byte to the program running in the terminal, which you can verify by running showkey -a in kitty and pressing ctrl+space. After that it is up to the program to act on that byte however it likes.

As for the extended keyboard protocol, as far as I know, nvim does not use it. If you can convince the nvim developers to start using it, it would be great, but...

**Comment by ggsalas** [comment]
Neovim use <c-space> and works on other terminals like iterm2. On Kitty work sometimes, for a while. Is a pity that can't be resolved. This shortcut is great.

**Comment by kovidgoyal** [comment]
There is nothing to resolve in kitty, as long as kitty is sending the null byte, that is all it can do. As I said, use showkey -a or (cat is showkey is not available) to verify that kittyis indeed sending the null byte. As to why nvim is sometimes failing to register it, you will have to ask the nvim developers.

**Comment by ggsalas** [comment]
I have mapped `ctrl+space` to an action on kitty and is working. So, you are right.
I would like another approach to fix my issue with neovim: Can I map `ctrl+space` to `ctrl+p`?. That's would fix my issue.

I think I can do something like this, but not sure how to find the codes:
`map ctrl+space send_text normal <ctrl+p code normal>`
`map ctrl+space send_text application <ctrl+p code app>`

Thanks!

**Comment by kovidgoyal** [comment]
Use showkey -a to see the bytes, like this:
```
showkey -a                                                                                                                                  

Press any keys - Ctrl-D will terminate this program

^P       16 0020 0x10
```

which tells you the needed code for send_text is \x10

**Comment by ggsalas** [comment]
Thanks @kovidgoyal works perfect!
I'm on a mac 😕 and I have found no way to use showkey. Also I don't know how to use cat to see to see the key codes. I try with -a but I see:
`
cat: illegal option -- a
usage: cat [-benstuv] [file ...]
`

Thanks for all the help. I really enjoy to use Kitty 😄
