### ISSUE TITLE
OSC-52 copy failed in 0.33

### ISSUE THREAD

**Issue by scturtle** [kovidgoyal/kitty#7227]
**Describe the bug**
There seems to be an issue with copying text using OSC-52 protocol in version 0.33.

In some cases, the copy function might not work as expected with certain text.

May be related to https://github.com/kovidgoyal/kitty/issues/7005.

**To Reproduce**

`printf "\033]52;c;$(printf "%s" "world" | base64)\a"`

See screenshots below. "hello" can be copied but not for "world".

**Screenshots**
<img width="711" alt="image" src="https://github.com/kovidgoyal/kitty/assets/320163/0ab61114-68fa-467a-9419-11e728f3fb7c">

**Environment details**
**Apple M1 Pro** with kitty 0.33 installed from homebrew.

**Additional context**
Reproduciable with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
dup of #7213

**Comment by scturtle** [comment]
> dup of #7213

I think it's not the same problem. I'm not doing "Request it back again with OSC 52". I'm just using cmd+v to paste from system clipboard.

**Comment by kovidgoyal** [comment]
Install the kitty nightly build and check for yourself. The fix was in
parse_osc52 which should be relevant both ways.

**Comment by scturtle** [comment]
Nightly build works for me. Thanks.
