### ISSUE TITLE
[question] How to set window title and tab title independently

### ISSUE THREAD

**Issue by baremetalfreak** [kovidgoyal/kitty#723]
I am currently using 
```
# {{{1 set title
chpwd() {
  print -Pn "\033]0;%~\007"
}
chpwd # call it once because no directory change is happening at shell start
```
in my .zshrc to set the current tab/window title

Is there a way in Kitty to set the window title separately from the tab title? For example to have the full path to current working directory in the window title and git branch name in the tab title?

**Comment by kovidgoyal** [comment]
You can use the remote control facilit or the keyboard shortcut to set tab titles. Then they will be fixed to what you have set and (IIRC) the window title will be whatever the program running in kitty sets as the window title.

**Comment by kovidgoyal** [comment]
It does link to it from the list of major features. But sure, I can add an entry for it in the sidebar as well.
