### ISSUE TITLE
Does kitty assume arch baseline for amd64 and arm64?

### ISSUE THREAD

**Issue by nileshpatra** [kovidgoyal/kitty#7231]
Hi,

I wanted to update the debian packageto 0.33.0  and noticed that kitty introduces some simd intrinsics. I did not deep dive and I figured it'd be best if I just clarified with you.

Debian considers amd64 baseline to be SSE2 and anything above that is a violation, so I'd need to build the package for different baselines and write a dispatcher script to select the appropriate baseline based on /proc/cpuinfo as detailed in: https://wiki.debian.org/SIMDEverywhere

However, as far as I checked, kitty and the 3rd party lib bundled with it will do this during runtime, will not violate the baseline and hence I can build the package normally irrespective of the target CPU architecture. Can you confirm this is the case or do I need to something special here?

**Comment by kovidgoyal** [comment]
You dont need to do anything. SIMD support is detected and used at runtime.
