### ISSUE TITLE
Font Opacity?

### ISSUE THREAD

**Issue by ManuGraiph** [kovidgoyal/kitty#7236]
Hi..

As the title says, it's possible to change the font opacity?

I switched to kitty 5 minutes ago after using the term with fontopacity for years and my eyes are burning up xD.

**Comment by kovidgoyal** [comment]
I have no idea what font opacity means. Read the kitty documentation for
all the various options that exist to control text rendering, and maybe
spend more than 5 mins with it before asking other people to spend their
valuable time helping you.

**Comment by ManuGraiph** [comment]
It's a way of speaking, spent hours trying to find a way to change the font opacity/transparency/alpha but couldn't find anything either in the docs or any example config file.

But don't worry, don't waste your valuable time.
