### ISSUE TITLE
Instruction to build a complete macOS package 

### ISSUE THREAD

**Issue by ppwwyyxx** [kovidgoyal/kitty#7237]
In the documentation https://sw.kovidgoyal.net/kitty/build/, I could not find instructions on how to build a complete package for macOS. 

I can successfully run `/dev.sh build --full` on macOS and obtain binaries and a `kitty.app` directory. However they have to be used in the exact location they are built. If I move them to a different location, e.g. `/Application/kitty.app`, it will not start. I think it's because the directory does not package all the dependencies it needs.

On the other hand, the released official macOS packages contain more files than the "kitty.app" directory obtained above.

Appreciate it if you could provide documentation on how to build.

**Comment by kovidgoyal** [comment]
Dont move it anywhere, symlink it from /Applications or wherever you are
trying to move it too.

**Comment by ppwwyyxx** [comment]
I'm aware of that, but I still would like to build a complete package. The instructions for that are missing.

With a symlink of the entire directory, the icon is not nice looking: 
![image](https://github.com/kovidgoyal/kitty/assets/1381301/86930bad-a1f8-4efd-87e9-c28796373196). In addition to that I would have to create another clone of the repo for development to not break the installation.

If I symlink the binary only, macOS will refuse to open it from finder.

**Comment by kovidgoyal** [comment]
I am afraid I have no interest in documenting how to build a standalone macos package as that is an extrememly involved process.

**Comment by irisjae** [comment]
Would you mind giving us an outline and some pointers so we may look up more information on how to do that?
