### ISSUE TITLE
Openning kitty shell with key shortcut fails

### ISSUE THREAD

**Issue by baremetalfreak** [kovidgoyal/kitty#724]
```
~ kitty --version
kitty 0.11.2 created by Kovid Goyal
```
running on macOS Sierra 10.12.6 (16G1408). I have
```
map super+e        kitty_shell window
```
in my kitty.conf and when I press CMD+e I get

```
Welcome to the kitty shell!
Use help for assistance or exit to quit
Traceback (most recent call last):
  File "kitty/shell.py", line 209, in main
  File "kitty/shell.py", line 158, in real_main
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f431' in position 0: ordinal not in range(128)
Press enter to quit...
```

Running `kitty @` works fine
```
~ kitty @
Welcome to the kitty shell!
Use help for assistance or exit to quit
🐱 exit
```

**Comment by kovidgoyal** [comment]
Works on my mac, that error makes it look like python thinks the I/O encoding for stdout is asciii on your system for some reason. Yo uhave any python related environment variables set?

**Comment by kovidgoyal** [comment]
Try setting the LANG environment variable to something like

LANG=en_US.UTF-8

and you should be fine.

**Comment by kovidgoyal** [comment]
Note that that should be set system-wide, not in your shell startup scripts, since those are not sourced by kitty. So use /etc/profile

**Comment by baremetalfreak** [comment]
- changed my shell to bash
- put `LANG=en_US.UTF-8` into /etc/profile
- restarted the computer

still getting the same error :-(

**Comment by baremetalfreak** [comment]
the `env` output is 
```
NIX_PROFILES=/nix/var/nix/profiles/default /Users/baremetalfreak/.nix-profile
TERM=xterm-kitty
SHELL=/bin/bash
TMPDIR=/var/folders/32/bd5qm53j2bl5sd81vlc1fdl00000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.qF39qjnI3T/Render
USER=baremetalfreak
NIX_REMOTE=daemon
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.amAg4tFRjz/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/baremetalfreak/.cargo/bin:/Users/baremetalfreak/.nix-profile/bin:/Users/baremetalfreak/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default:/nix/var/nix/profiles/default/lib/kde4/libexec:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/kitty.app/Contents/MacOS
NIX_PATH=/nix/var/nix/profiles/per-user/root/channels
PWD=/Users/baremetalfreak
EDITOR="/usr/local/bin/nvim"
XPC_FLAGS=0x0
ITERM_ORIG_PS1=\h:\W \u\$ 
NIX_SSL_CERT_FILE=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
PS1=\h:\W \u\$ 
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/baremetalfreak
TERMINFO=/Applications/kitty.app/Contents/Frameworks/kitty/terminfo
ITERM_PREV_PS1=\[]133;D;$?]1337;RemoteHost=baremetalfreak@baremetalfreak.local]1337;CurrentDir=/Users/baremetalfreak]133;A\]\h:\W \u\$ \[]133;B\]
LOGNAME=baremetalfreak
KITTY_WINDOW_ID=3
DISPLAY=/private/tmp/com.apple.launchd.jwC4RZ3L2u/org.macosforge.xquartz:0
NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/baremetalfreak
COLORTERM=truecolor
_=/usr/bin/env
```

**Comment by kovidgoyal** [comment]
Oh and looking at your env output it doesn't look like the LANG env var is set. Probably you need to set it somewhere other than /etc/profile (I'm not  mac user so I cant tell you where).

Incidentally, what does
```
kitty +runpy 'from kitty.fast_data_types import *; print(cocoa_get_lang())'
```

kitty will normally set LANG for you if it is inset, unless that function fails to detect the languuage set in your macOS settings.

**Comment by baremetalfreak** [comment]
Funny, it says `en_CZ` I wonder how it got there. I think /etc/profile is run by bash after user logs in. I have no idea how system wide env variables are set when a user starts his mac and logs in. Will have to do some research.

**Comment by baremetalfreak** [comment]
I went to System Preferences > Language & Region and changed Region to "United States (Computer)" and it did the trick. `env` now correctly outputs `LANG=en_US.UTF-8` and kitty shell opens without the error.

**Comment by baremetalfreak** [comment]
As far as environment variable set up for gui applications (like kitty) go, [launchd](https://en.wikipedia.org/wiki/Launchd) seems to be the top level thing setting env variables for anyone on a mac since Mac OS X Tiger. And `launchctl` is a CLI to it.

`man launchd`, `man launchctl`, ` man launchd.plist`
https://wiki.freebsd.org/launchd
https://www.youtube.com/watch?v=mLwn_TbBntI
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/Introduction.html
