### ISSUE TITLE
No mouse drag end event when dragging mouse out of the window

### ISSUE THREAD

**Issue by anhpt379** [kovidgoyal/kitty#7244]
**Describe the bug**
I'm on macOS Sonoma 14.3.1. When using tmux (version 3.4), the `MouseDragEnd1Pane` event doesn't get triggered when I drag the mouse out of the current window. I've tried with the default macOS Terminal app, and WezTerm, they don't have this issue.

**To Reproduce**
1. Copy this config to `/tmp/tmux.conf`:
```
set-option -g mouse on
set-option -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane display-message "Drag ended"
```
2. Launch tmux with the config file above: `tmux -f /tmp/tmux.conf`.
3. Press the left mouse button in the middle of a text line in the window.
4. Hold and drag the mouse to the left, outside of the current window.
5. Release the left mouse button.
6. No `Drag ended` doesn't show up, meaning the mouse drag end event doesn't fire.

**Environment details**
```
kitty 0.33.1 (a5fea33757) created by Kovid Goyal
Darwin L2HHKL97RH 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.3.1 BuildVersion:		23D60
Frozen: True
Paths:
  kitty: /Users/panh/Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Users/panh/Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/panh/Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Privileges.app/Contents/Resources:/usr/local/munki:/Users/panh/Applications/kitty.app/Contents/MacOS
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             /private/tmp/com.apple.launchd.gxTONFhPQD/org.xquartz:0
	USER                                panh
```

**Additional context**
It sort of works when using the **default** font size, **and** when the window is in full screen mode: dragging the mouse to the left edge of the screen and release, the message `Drag ended` shows up. But when switching to a different font size it stops working.

**Comment by kovidgoyal** [comment]
Please come up witha  reproducer not involving tmux. Simply run

kitty kitten mouse-demo

to see what mouse events are delivered to a program running inside
kitty. And run kitty with --debug-input to see what events are delivered
to kitty itself.

**Comment by anhpt379** [comment]
It happens when something grabs the mouse (like neovim with `set mouse=a`, or tmux with `set -g mouse on`, or `less --MOUSE`). 

Here's how to reproduce it:

1. Run `kitty --debug-input`.
2. Run `less --MOUSE /path/to/a/file` on the newly created window (I'm using `less` version `643`).
3. Start dragging, with the starting point in the window.
4. Drag the mouse out of the window, and release.

When releasing the mouse in the window, the debug log shows 2 events:

```
Move x: 116.0 y: 282.1 grabbed: 1
Move x: 116.4 y: 282.1 grabbed: 1
Move x: 116.9 y: 282.1 grabbed: 1
Release mouse_button: 0 mods: none grabbed: 1
on_mouse_input: release button: left mods: none grabbed: 1 handled_in_kitty: 0
Move x: 117.9 y: 282.1 grabbed: 1
Move x: 118.3 y: 282.1 grabbed: 1
```

When releasing the mouse outside of the window, the debug log doesn't show the `on_mouse_input` line:

```
Move x: -104.3 y: 105.2
Move x: -104.6 y: 105.0
Release mouse_button: 0 mods: none
Move x: -104.1 y: 104.8
Move x: -101.7 y: 106.0
```

When running `less` without `--MOUSE` and trying to release the mouse both inside & outside the window, the debug log shows only something like this (with no `on_mouse_input` line): 

```
Move x: 32.7 y: 101.6 handled as drag move
Move x: 32.2 y: 101.6 handled as drag move
Release mouse_button: 0 mods: none handled as drag end
Move x: 31.2 y: 101.6 grabbed: 0
Move x: 31.6 y: 101.6 grabbed: 0
```

**Comment by kovidgoyal** [comment]
kitten mouse-demo grabs the mouse. It doesn't reproduce for me in either
X11 or macOS (via VNC) with kitten mouse-demo. Haven't tried with less
but I dont see why that would make a difference. Are you saying it
doesn't reproduce for you with mouse-demo but does with less? Or if it
reproduces with both is there something unusual about your system? I
will try it on macOS without VNC when I next have access to my mac.

**Comment by anhpt379** [comment]
For `kitty kitten mouse-demo`, when I drag & release the mouse in the window, the `Type` always stays at `move`. When I release the mouse outside of the window, the `Type` switches to `release`. I don't know what that means.

For `less` or `nvim`, they don't provide any visual indicator for the issue. The only difference I saw was the `on_mouse_input` line in the `kitty --debug-input` log.

**Comment by anhpt379** [comment]
I'm sure that my mouse doesn't move when I release the button. The type in mouse-demo only switches to `release` when I release the mouse outside the window. When inside, the type always stays at `move` both when I drag & when I release the mouse button.

**Comment by kovidgoyal** [comment]
On Thu, Mar 21, 2024 at 07:50:38AM -0700, Anh Pham wrote:
> I'm sure that my mouse doesn't move when I release the button. The type in mouse-demo only switches to `release` when I release the mouse outside the window. When inside, the type always stays at `move` both when I drag & when I release the mouse button.

That does not reproduce for me.

**Comment by anhpt379** [comment]
I made a recording for it:
https://github.com/kovidgoyal/kitty/assets/222319/3f13166a-ad6d-4120-8c7c-4e7ec64f7035

Can you suggest what else for me to try?

**Comment by kovidgoyal** [comment]
You dont need to try anything, your original issue is fixed already.

**Comment by anhpt379** [comment]
ah, sorry I didn't notice the commit. Thank you for being so responsive :)
