### ISSUE TITLE
Unicode character no longer displayed in Monaspace font after upgrading to 0.33.1

### ISSUE THREAD

**Issue by infogrind** [kovidgoyal/kitty#7248]
**Describe the bug**
After upgrading from 0.32.1 to 0.33.1, the unicode character U276f ("Heavy Right-Pointing Angle Quotation Mark Ornament"), which I use as part of my shell prompt, is no longer displayed. Instead, a right rectangle is shown.

With 0.32.1:
<img width="384" alt="Screenshot 2024-03-22 at 07 20 29" src="https://github.com/kovidgoyal/kitty/assets/718881/b5b2a13c-3f82-4a14-afba-1b4eef32baa0">

With 0.33.1:
<img width="383" alt="Screenshot 2024-03-22 at 07 23 15" src="https://github.com/kovidgoyal/kitty/assets/718881/25263360-90b2-4296-8fc1-1630ef0ade63">

I have been able to reproduce this only with my current terminal font Monaspace; the problem does not occur when reverting to my default font.

**To Reproduce**
1. Update to Kitty 0.33.1
2. Install the Monaspace Neon font from https://github.com/githubnext/monaspace and set `font_family             Monaspace Neon Light` in the config.
3. Open kitty and type `python3 -c "print('\276f')"`
4. See error.

**Screenshots**
See above

**Environment details**
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

See https://gist.github.com/infogrind/07134a0d74620a600e6a52c379cc3cf1

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

As described above, it is not reproducible that way, because it depends on a specific font.

**Comment by kovidgoyal** [comment]
Fill in the information asked for in the issue template.

**Comment by infogrind** [comment]
Sorry, I sent it too fast. Updated everything now.

**Comment by kovidgoyal** [comment]
Most likely the fallback font used for it on your system has changed. use symbol_map in kitty.conf to override it to some font that actually has that symbol, such as DejaVu Sans Mono or similar. Use --debug-font-fallback to see what font is actually being used.

I cant test it since Monascape isnt actually monospaced, it doesnt having spacing=100 as per fontconfig.

**Comment by infogrind** [comment]
Thanks! 

> Most likely the fallback font used for it on your system has changed.

Do you mean as part of the Kitty upgrade, or do you mean it was some external change that had nothing to do with the Kitty upgrade? (I tested it on two separate systems, and the change in behavior correlates exactly with the Kitty upgrade.)

> Use --debug-font-fallback to see what font is actually being used.

Thanks, good tip. Just FYI, here is the output:

```
[082 09:08:58.527115] Preloaded font faces:
[082 09:08:58.527136] normal face: /Users/mkleiner/Library/Fonts/MonaspaceNeon-Light.otf
[082 09:08:58.527141] bold face: /Users/mkleiner/Library/Fonts/MonaspaceNeon-Bold.otf
[082 09:08:58.527145] italic face: /Users/mkleiner/Library/Fonts/MonaspaceRadon-Italic.otf
[082 09:08:58.527149] bi face: /Users/mkleiner/Library/Fonts/MonaspaceRadon-BoldItalic.otf
U+276f 
The font chosen by the OS for the text: U+276f is  but it does not actually contain glyphs for that text
```

It seems that instead of printing an actual fallback font, there is an empty string (see the two spaces between `is  but`). I am not sure what that means. 

> use symbol_map in kitty.conf to override it to some font that actually has that symbol

This worked, thanks!

```
symbol_map U+276f Symbols Nerd Font
```

**Comment by infogrind** [comment]
And just because I was curious, I downgraded to 0.32.1. again and then run `kitty --debug-font-fallback` (without any `symbol_map` defined).

```
[082 09:16:39.143403] Preloaded font faces:
[082 09:16:39.143424] normal face: /Users/mkleiner/Library/Fonts/MonaspaceNeon-Light.otf
[082 09:16:39.143429] bold face: /Users/mkleiner/Library/Fonts/MonaspaceNeon-Bold.otf
[082 09:16:39.143434] italic face: /Users/mkleiner/Library/Fonts/MonaspaceRadon-Italic.otf
[082 09:16:39.143438] bi face: /Users/mkleiner/Library/Fonts/MonaspaceRadon-BoldItalic.otf
U+276f Face(family=Zapf Dingbats, full_name=Zapf Dingbats, postscript_name=ZapfDingbatsITC, path=/System/Library/Fonts/ZapfDingbats.ttf, units_per_em=2048, ascent=21.2, descent=4.6, leading=0.0, scaled_point_sz=26.0, underline_position=-2.6 underline_thickness=1.6) (new face)
```

Do you know why the new Kitty version would change that behavior?

**Comment by kovidgoyal** [comment]
Follow up in #7249
