### ISSUE TITLE
Some characters are shown as squares in v0.33.1

### ISSUE THREAD

**Issue by 0x7a7a** [kovidgoyal/kitty#7249]
After yesterday's update(0.33.1), I realized that the [which-key plugin](https://github.com/folke/which-key.nvim) icon in my Neovim was showing up as a square,but it displays correctly in editors and terminals.

I've mapped nerd fonts in kitty's configuration with symbol map, and it worked fine before.

I'm using macOS, and looking at yesterday's changelog there are a lot of character related update, so I'm wondering if there's something wrong.

I tried rolling back to version 0.33 and the problem was solved.

If there is any other information you need, please let me know,thanks!

Below is a screenshot of the problem:
<img width="965" alt="image" src="https://github.com/kovidgoyal/kitty/assets/8832748/b2a530f1-fc53-49e5-ab22-b23565e2539a">

**Comment by kovidgoyal** [comment]
I need to know which characters there are as in their unicode code points. Which you can get by pressing ga in vim with the cursor over the character. Once you know which character run

```
kitty --debug-font-fallback zsh -c 'printf "\uABCD"; read'
```

replace ABCD above with the hex code for the character and post the output.

**Comment by 0x7a7a** [comment]
```zsh
kitty --debug-font-fallback zsh -c 'printf "\u279c"; read'                                                        ─╯
[082 16:05:09.109146] Symbol map: U+26FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E600-U+E6C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F373,U+F400-U+F532,U+F0001-U+F1AF0 Symbols Nerd Font Mono is invalid, ignoring
[082 16:05:09.489706] Preloaded font faces:
[082 16:05:09.489752] normal face: /Users/lucky/Library/Fonts/Hack-Regular.ttf
[082 16:05:09.489763] bold face: /Users/lucky/Library/Fonts/Hack-Bold.ttf
[082 16:05:09.489772] italic face: /Users/lucky/Library/Fonts/Hack-Italic.ttf
[082 16:05:09.489780] bi face: /Users/lucky/Library/Fonts/Hack-BoldItalic.ttf
```

My Font Configuration:
```
font_family      Hack
italic_font      auto
bold_font        auto
bold_italic_font auto

font_size 13
disable_ligatures never

symbol_map U+26FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E600-U+E6C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F373,U+F400-U+F532,U+F0001-U+F1AF0 Symbols Nerd Font Mono
```

**Comment by kovidgoyal** [comment]
To be clear is it not rendering with the above?  Because it renders fine for me. With default configuration. Which font exactly is hack? And if it is not rendering, does it render without using Hack?

**Comment by medicm** [comment]
Yes, I have also noticed when upgrading from 0.33.0 to 0.33.1 that Symbols Nerd Font starts rendering as blocks.

0.33.0 output
```bash
✦ 09:11:54.715 +0100 ❯ kitty --debug-font-fallback zsh -c 'printf "\u❯✦"; read'
[082 09:12:26.045762] Ignoring unknown config key: share_connections
[082 09:12:26.045782] Ignoring unknown config key: askpass
[082 09:12:26.297254] Preloaded font faces:
[082 09:12:26.297272] normal face: /Users/marko/Library/Fonts/SFMono Regular Nerd Font Complete.otf
[082 09:12:26.297277] bold face: /Users/marko/Library/Fonts/SFMono Semibold Nerd Font Complete.otf
[082 09:12:26.297282] italic face: /Users/marko/Library/Fonts/SFMono Regular Italic Nerd Font Complete.otf
[082 09:12:26.297286] bi face: /Users/marko/Library/Fonts/SFMono Semibold Italic Nerd Font Complete.otf
[082 09:12:26.297294] Symbol map faces:
[082 09:12:26.297299] /Users/marko/Library/Fonts/SymbolsNerdFontMono-Regular.ttf
U+276f Face(family=Zapf Dingbats, full_name=Zapf Dingbats, postscript_name=ZapfDingbatsITC, path=/System/Library/Fonts/ZapfDingbats.ttf, units_per_em=2048, ascent=10.6, descent=2.3, leading=0.0, scaled_point_sz=13.0, underline_position=-1.3 underline_thickness=0.8) (new face)
U+2726 0 (new face)
```
![CleanShot 2024-03-22 at 09 19 18](https://github.com/kovidgoyal/kitty/assets/15942498/175bc2e4-7db9-4865-9457-0a6b42f526b5)



0.33.1 output
```bash
✦ 09:15:41.595 +0100 ❯ kitty --debug-font-fallback zsh -c 'printf "\u❯✦"; read'
[082 09:15:50.627165] Ignoring unknown config key: share_connections
[082 09:15:50.627186] Ignoring unknown config key: askpass
[082 09:15:50.876766] Preloaded font faces:
[082 09:15:50.876783] normal face: /Users/marko/Library/Fonts/SFMono Regular Nerd Font Complete.otf
[082 09:15:50.876788] bold face: /Users/marko/Library/Fonts/SFMono Semibold Nerd Font Complete.otf
[082 09:15:50.876794] italic face: /Users/marko/Library/Fonts/SFMono Regular Italic Nerd Font Complete.otf
[082 09:15:50.876798] bi face: /Users/marko/Library/Fonts/SFMono Semibold Italic Nerd Font Complete.otf
[082 09:15:50.876805] Symbol map faces:
[082 09:15:50.876810] /Users/marko/Library/Fonts/SymbolsNerdFontMono-Regular.ttf
U+276f 
The font chosen by the OS for the text: U+276f is  but it does not actually contain glyphs for that text
U+2726 
The font chosen by the OS for the text: U+2726 is  but it does not actually contain glyphs for that text
ValueError: character U+656e6f4e is not in range [U+0000; U+10ffff]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/python3.11/kitty/boss.py", line 1156, in on_window_resize
SystemError: <method 'get' of 'dict' objects> returned a result with an exception set
```

![CleanShot 2024-03-22 at 09 17 36](https://github.com/kovidgoyal/kitty/assets/15942498/dc120b81-27e6-4f8b-b6de-46ea87d06318)

**Comment by 0x7a7a** [comment]
> To be clear is it not rendering with the above?

I don't think it's unrenderable, because it's not a problem in kitty's version 0.33.
<img width="1188" alt="image" src="https://github.com/kovidgoyal/kitty/assets/8832748/bd1f5c6d-ba9d-4214-a5b4-d59fcd238887">


> Which font exactly is hack

The [Hack](https://github.com/source-foundry/Hack) font is a little old, but it's always worked well before.

> does it render without using Hack

I've tried other fonts, but the problem is still not solved.

**Comment by kovidgoyal** [comment]
I think the issue is caused by the Zapf Dingbats font. Try removing it from your system temporarily to confirm.

**Comment by 0x7a7a** [comment]
This is the result of running in v0.33
```
kitty --debug-font-fallback zsh -c 'printf "\u279c"; read'                                                                                    ─╯
[082 16:26:22.009140] Preloaded font faces:
[082 16:26:22.009187] normal face: /Users/lucky/Library/Fonts/Hack-Regular.ttf
[082 16:26:22.009198] bold face: /Users/lucky/Library/Fonts/Hack-Bold.ttf
[082 16:26:22.009206] italic face: /Users/lucky/Library/Fonts/Hack-Italic.ttf
[082 16:26:22.009215] bi face: /Users/lucky/Library/Fonts/Hack-BoldItalic.ttf
[082 16:26:22.009224] Symbol map faces:
[082 16:26:22.009232] /Users/lucky/Library/Fonts/SymbolsNerdFontMono-Regular.ttf
```

**Comment by kovidgoyal** [comment]
The changes in 0.33.1 to try to get coretext to return fallback fonts matching the bold/italic attributes are for some reason causing it to return Zapf Dingbats on your systems. Which doesn't actually contain those codepoints.

**Comment by 0x7a7a** [comment]
It's a system font that can't seem to be removed. 
I'm worried that forcing it to be removed will have an effect on other programs.
<img width="273" alt="image" src="https://github.com/kovidgoyal/kitty/assets/8832748/6e6ef8e4-5675-4f6e-a8b1-54b214f9a913">

**Comment by kovidgoyal** [comment]
its a font, it cant cause any problem beyond some charactes not
rendering. Do something like

sudo mv /System/Library/Fonts/ZapfDingbats.ttf /tmp

run the test

and move it back.

**Comment by 0x7a7a** [comment]
> its a font, it cant cause any problem beyond some charactes not rendering. Do something like
> 
> sudo mv /System/Library/Fonts/ZapfDingbats.ttf /tmp
> 
> run the test
> 
> and move it back.

This operation seems to be interfered by the System Integrity Protection, unless I disable the SIP and reboot.
<img width="628" alt="image" src="https://github.com/kovidgoyal/kitty/assets/8832748/c56f7c39-5c84-4dd9-80b3-d68c6d17a058">
I can try. I'll have to get back to you.

**Comment by 0x7a7a** [comment]
@medicm @kovidgoyal 
I've turned off SIP, but I still can't remove the font.
<img width="816" alt="image" src="https://github.com/kovidgoyal/kitty/assets/8832748/99f6f507-85e6-430c-af00-1aa44246c78f">


> The changes in 0.33.1 to try to get coretext to return fallback fonts matching the bold/italic attributes are for some reason causing it to return Zapf Dingbats on your systems. Which doesn't actually contain those codepoints.

Would such a matching rule bypass the symbol_map configuration?

**Comment by kovidgoyal** [comment]
No, it doesnt. symbol_map has highest priority. hack does not contain U+2726. On my system COreText returns Menlo as the fallback for it. Dont know why its returning Zapf Dingbats on yours. In any case a temporary fix you can use symbol_map to map U+2726 to Menlo

**Comment by 0x7a7a** [comment]
> ```shell
> Zap
> ```
It seems we've had a misunderstanding. You replied to @medicm .

About my character problem I tried to configure U+279C with symbol_map, but it still doesn't match
<img width="640" alt="image" src="https://github.com/kovidgoyal/kitty/assets/8832748/d392f53c-f01b-4885-8a3e-fb9eb57a268e">

**Comment by kovidgoyal** [comment]
U+279c not in NERD fonts. You want to symbol_map it to Menlo. And note that the fix is speculative as I cant reproduce the issue, so YMMV.

**Comment by kovidgoyal** [comment]
And interestingly, all three of ❯✦➜ are present in zapf dingbats as well in my system. So I really have no clue whats going on.

**Comment by 0x7a7a** [comment]
> U+279c not in NERD fonts. You want to symbol_map it to Menlo. And note that the fix in the commit is speculative as I cant reproduce the issue, so YMMV.

Can symbol_map be configured with multiple fonts?
In my case, I want to configure the nerd font as the first choice, and then match the Menlo, I do not know how to config

> And interestingly, all three of ❯✦➜ are present in zapf dingbats as well in my system. So I really have no clue whats going on.

I don't know why, but it's a good start if you can reproduce it 😄

**Comment by kovidgoyal** [comment]
yes you can, and symbol_map is disjoint in your case anyway, which means it will only use menlo for that codepoint. And no I cant reproduce it. I should note my mac is 14.4 Sonoma.

**Comment by 0x7a7a** [comment]
> yes you can, and symbol_map is disjoint in your case anyway, which means it will only use menlo for that codepoint. And no I cant reproduce it. I should note my mac is 14.4 Sonoma.

I have the same version of the OS.

--- 
Am I configuring this correctly? It seems to be working. I just wanted to make sure.
```
symbol_map  codepoints  Symbols Nerd Font Mono
symbol_map  codepoints  Menlo
```

Can you tell me how to determine what fonts the codepoints are in, so I can deal with a similar problem myself next time?
Sorry. I'm a bit of a babbler.

**Comment by kovidgoyal** [comment]
Yes, it's correct, but there is no need, I have pushed the correct fix, see my latest commit.
https://github.com/kovidgoyal/kitty/commit/4878b7cfd3b594b863280298bb972cd3026bb385

**Comment by infogrind** [comment]
This is great, thank you Kovid!

**Comment by 0x7a7a** [comment]
> Yes, it's correct, but there is no need, I have pushed the correct fix, see my latest commit. [4878b7c](https://github.com/kovidgoyal/kitty/commit/4878b7cfd3b594b863280298bb972cd3026bb385)

Thank you very much for your quick response, I really like kitty

**Comment by gwenwindflower** [comment]
thank you for this thread! been going batty trying to figure this out! much appreciated. just downloaded the nightly build and can confirm, same issue is fixed. thank you. 💗🙏🏻
