### ISSUE TITLE
Kitty using physical key instead of logical key if logical key is extended ascii character

### ISSUE THREAD

**Issue by tamwile** [kovidgoyal/kitty#7254]
Thank you for this terminal emulator.

**Description**

I tried to use some extended ascii character for a keybind (meta-à or alt-à) in a TUI application (weechat),
but meta-à is recognized as meta-z (which is the physical key, not the logical key).
This binding works in urxvt, terminator, and also outside of weechat, if we use for example emacs -nw.
This is the same thing for other keys i tested like é, è, ê, ç, to give a few examples.

Expected Behaviour:
meta-à or any other extended ascii character should use the logical key according to the layout and not the physical key by default.
Same for ctrl-à or other character.

`kitten show_key -m kitty`

```
ENTER RELEASE 
CSI 13 ; 1 : 3 u

à PRESS à
CSI 224 :  : 122 ;  ; 224 u
Alternate key: z 

à RELEASE 
CSI 224 :  : 122 ; 1 : 3 u
Alternate key: z 

LEFT_ALT PRESS 
CSI 57443 u

alt+à PRESS 
CSI 224 :  : 122 ; 3 u
Alternate key: z 

alt+à RELEASE 
CSI 224 :  : 122 ; 3 : 3 u
Alternate key: z 

alt+LEFT_ALT RELEASE 
CSI 57443 ; 3 : 3 u

LEFT_CONTROL PRESS 
CSI 57442 u

ctrl+à PRESS 
CSI 224 :  : 122 ; 5 u
Alternate key: z 

ctrl+à RELEASE 
CSI 224 :  : 122 ; 5 : 3 u
Alternate key: z 

ctrl+LEFT_CONTROL RELEASE 
CSI 57442 ; 5 : 3 u
```

**Environment details**

```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
```

```
Key action failed


debug_config
cannot import name 'KeyboardMode' from 'kitty.options.utils' (/usr/bin/../lib/kitty/kitty/options/utils.py)

Press e to see detailed traceback or any other key to exit
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1618, in combine
    this is useful if focus is not on any kitty OS window at all, however, it will only work if the window manager
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1571, in dispatch_action
    self.drain_actions(list(actions[1:]), window_for_dispatch, dispatch_type)
      ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 2920, in debug_config
    output += '\n\x1b[35mThis debug output has been copied to the clipboard\x1b[m'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/debug_config.py", line 22, in <module>
    from .options.utils import KeyboardMode, KeyDefinition
ImportError: cannot import name 'KeyboardMode' from 'kitty.options.utils' (/usr/bin/../lib/kitty/kitty/options/utils.py)
```

**Additional context**

The problem persists with `kitty --config NONE`

It has to be noted that i have a z key in my layout, and in this case meta-z correctly gives meta-z.
Which means sometimes the physical key is chosen, and sometimes the logical key is chosen.

**Comment by kovidgoyal** [comment]
According to your own show-key output that is exactly what kitty is
doing. In addition to sending it as 224 aka (Unicode U+00e0) aka à it
ALSO sends an alternate key, namely z. Why weechat doesnt bind to the
primary key you would need to ask its developers.
