### ISSUE TITLE
Scrollbar or indicator where we are in scrollback buffer

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [kovidgoyal/kitty#7255]
Hi,
I usually use a long scrollback, but without any indicator, it is a horror to use.

Please add some sort of indicator to show where the user is in the scrollback in the form of any useful form. I do not care if it will be a percentage indicator, a small indicator on the right edge where a scrollbar used to be, or something similar.

I see that you do not like many visual features that users want to use with this terminal emulator. I politely remind you that with every missing feature, you clearly risk that someone gets pissed off and create a fork with all the requested features or starts to implement a similar but more useful and widely accepted terminal emulator.

Have a nice day,
electry

**Comment by kovidgoyal** [comment]
Oooo a politely worded threat, my favorite kind.

Press ctrl+shift+h
