### ISSUE TITLE
Nightly build artifacts are missing on Github Release

### ISSUE THREAD

**Issue by mikesmithgh** [kovidgoyal/kitty#7257]
**Describe the bug**
Nightly build artifacts are missing on Github Release, I noticed this on Mar 23, 2024, 8:13 PM EDT 

**To Reproduce**
Steps to reproduce the behavior: n/a

**Screenshots**
![nightly-missing](https://github.com/kovidgoyal/kitty/assets/10135646/92bae429-23e0-4e84-b356-708e81414515)

**Environment details**
n/a

**Additional context**
Failing [kitty-scrollback.nvim](https://github.com/mikesmithgh/kitty-scrollback.nvim) CI builds for nightly: https://github.com/mikesmithgh/kitty-scrollback.nvim/actions/workflows/tests.yml?query=event%3Aschedule

**Comment by kovidgoyal** [comment]
Yeah github has been rather flaky of late and the upload deletes all first so if it flakes out then you end up with a partial upload. It will autocorrect in a few hours. I have to figure out why the upload script didnt error out and notify me, will do that sometime later.
