### ISSUE TITLE
Function keys not sending the correct keys

### ISSUE THREAD

**Issue by tamasgal** [kovidgoyal/kitty#726]
I have an issue with Kitty on my Manjaro desktop (on xmonad): the function keys are not sent correctly. In all other terminals it's working fine.

Is this a known issue or default behaviour? I could not find any information about the function keys in the documentation...

**Comment by kovidgoyal** [comment]
What does not sent correctly mean? kitty generates the bytes for the function key as per its terminfo definition file. You can see those bytes using showkey -a

You will see that they match the terminfo. If you want them to generate some other bytes, for example if you have applications that have hardocded the values that they expect instead of using terminfo, then you can override them using the send_text mapping in kitty.conf. See the help for send_text in the kitty website for details.

**Comment by tamasgal** [comment]
I will look into `send_text`. Not correctly means I get B or D or S etc. displayed, instead of the expected key code, which means, the key bindings in `mutt` for example do not work.
In other terminals it's working fine.

**Comment by kovidgoyal** [comment]
Here is the output of showkey -a for pressing the F1, F2 and F3 keys in kitty. You should get the same.

```
^[OP     27 0033 0x1b
         79 0117 0x4f
         80 0120 0x50
^[OQ     27 0033 0x1b
         79 0117 0x4f
         81 0121 0x51
^[OR     27 0033 0x1b
         79 0117 0x4f
         82 0122 0x52
```

If you do, that means it is working correctly.

**Comment by tamasgal** [comment]
Thanks, I will cross check tomorrow. I am already at home and cannot start Kitty via SSH -y...

```
> kitty
xkbcommon: ERROR: x11: failed to get keymap from X server: unmet condition in get_controls(): reply->numGroups > 0 && reply->numGroups <= 4
[197 21:20:40.469421] [glfw error 65544]: Failed to compile XKB keymap
[1]    29211 segmentation fault (core dumped)  kitty
```

**Comment by tamasgal** [comment]
I get the same values for the F keys but mutt still says "Key is not bound". It however works when I launch mutt in xterm or urxvt etc.

**Comment by kovidgoyal** [comment]
I just tried showkey -a in xterm and I get exactly the same values there as well, indeed this part of the terminfo file of most terminals (kitty and xterm included) are basically the same, see

infocmp | grep kf1

**Comment by tamasgal** [comment]
Any idea what's going wrong then? I am a bit clueless... since I see the same values as well

**Comment by kovidgoyal** [comment]
No idea, sorry, I'm not familiar with mutt's codebase. I tried running mutt on my computer and pressing F1 it opened the mutt user manual. Pressing F2 caused a Key is not bound message in the status area of mutt. SO I cannot reproduce your symptoms in mutt either.

Only things I can suggest are:

1) try with no muttrc
2) try running mutt directly without an intervening shell, like this:

kitty mutt

**Comment by tamasgal** [comment]
Thanks for the remarks. I just ran `kitty mutt` and the keys are working, but the colours are messed up. At least now I can dig further ;)

**Comment by tamasgal** [comment]
Ok this boils down to the `export TERM=rxvt-unicode-256color` which I once set to have the correct colours in VIM etc.
Also when I have `$TERM` set to the default `kitty` or `xterm-kitty`, I have no backspace when I connect through SSH.

I am not sure how to solve these issues though... even `export TERM=xterm-256color` gives the wrong colour map.

**Comment by kovidgoyal** [comment]
You should never change TERM. See the kitty faq for what to do about the ssh issue. And as for colors, you can configure whatever colors you like in kitty.conf

**Comment by tamasgal** [comment]
OK, I'll look in the faq.

Regarding the colours, I am using the Base16-shell which worked fine for the last years both on Linux and macOS terminals. I recently switched to kitty because I wanted to use a ligature font (Fira code) and on Linux there is almost no support (other than kitty ;)

However I now face the above mentioned issues with colours and mutt...

**Comment by kovidgoyal** [comment]
I dont know what base16 shell is but kitty has the most comprehensive color support of any terminal anywhere. I'm guessing it is some shell script to change colors. It is probably a broken-ass script that hardocdes escape codes based on TERM values. Get rid of it and use kitty's native color management features which are far easier to use and far more comprehensive. 

And please, never, never change TERM.

**Comment by tamasgal** [comment]
I am working on a whole bunch of computers and don't have kitty everywhere, that's why I am using base16 which works absolutely fine. I can change themes with a single command to match for example the lighting conditions when I do presentations etc.

I'd rather try to fix this issue with my kitty setup (which is just one computer) than changing all the others.

Currently I figured out that it's `mutt` which messes the colours. If `TERM` is untouched (yes, I will never touch it again ;) all the colours in e.g. VIM etc. work as they should. When I however start `mutt`, the colours are wrong and after exiting mutt, the colours stay wrong when I open VIM again, the colours stays messed up.

Not sure what mutt does there, but at least this is not happening with other terminals. So I guess there is something not so standard in kitty maybe?

> Get rid of it and use kitty's native color management features which are far easier to use and far more comprehensive.

I'll have a look at it, but currently I just need to type `base16_materia` or `base16_unikitty-light` etc. to switch themes on any machine, regardless of the terminal, and this is what works for me for years on several machines.
I don't yet see the reason to change this just because I am using kitty on one of the many machines I have to work on ;)

**Comment by kovidgoyal** [comment]
Sure, feel free to use whatever workflow suits you best. The only thing that you really should not do is change TERM, as how terminal programs interact with the terminal depend on that.

**Comment by janos-r** [comment]
I don't understand the proposed solution. When I press F1-3 I get the same codes in the terminal.
I just freshly installed kitty through apt on Mint21.1 and when I pres ctrl+shift+F1 the terminal prints [1;6P
