### ISSUE TITLE
Scrolling with the touchpad will sometime reset the view back to the cursor in Kakoune

### ISSUE THREAD

**Issue by jamesaustin** [kovidgoyal/kitty#7260]
**Describe the bug**
When using the trackpad to scroll through a long text file with Kakoune (2023.08.05-248-g4101e181) on macOS 14.2.1 the view will occasionally snap back to the cursor position.

However when scrolling with the mouse rollerball with Kakoune the file is navigated as expected.

Likewise when scrolling with the trackpad or rollerball in other terminals (tested Terminal.app, Alacritty, and iTerm2) the file is navigated as expected.

This suggests that there is an issue with how Kitty is reporting the trackpad input to Kakoune and triggers the issue.

**To Reproduce**
1. Open a long text file with Kakoune (default config) with Kitty (default config) and two-finger scroll down through the file.
2. Occasionally the view will snap back to the cursor position and scrolling will continue from the cursor position.

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
kitty 0.33.1 (a5fea33757) created by Kovid Goyal
Darwin James-MacBook-Pro-M1.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.2.1 BuildVersion:		23C71
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/local/bin/bash

Config options different from defaults:
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/Users/james/local/bin:/usr/local/bin:/Applications/MacPorts/kitty.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_GB.UTF-8
	EDITOR                              kak
	SHELL                               /opt/local/bin/bash
	USER                                james

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Issue happens with the default config.

I couldn't see any anomalous inputs whilst debugging with --debug-keyboard.

**Comment by kovidgoyal** [comment]
I'm afraid I dont see how this has anything to do with kitty. If you can
find some stronger evidence than kakoune misbehaving I will be happy to
take a look. For instance, a misbehavior is some other program, say 
less --MOUSE

**Comment by jamesaustin** [comment]
I did first assume it would be an issue with Kakoune itself.

But the issue isn't triggered when using different terminals. I tested with Alacrity, Terminal.app, iTerms, and even others. Which suggested it was Kitty + Kakoune specific.

**Comment by kovidgoyal** [comment]
Unfortunately, that doesnt really mean anything. For instance, it could simply be that
the rate at which events are delivered is higher in kitty triggering a
race in kakoune. You can get a log of all events kitty receives and what
it does with them by running with --debug-input but I doubt that will
tell you anything.
