### ISSUE TITLE
Cannot use kitten theme on workplace network even when using proxy

### ISSUE THREAD

**Issue by nighthawk469** [kovidgoyal/kitty#7268]
**Describe the bug**
Cannot use kitten theme on workplace network even when using the proxy variable ALL_PROXY=http://<proxy-ip>

```
kitten themes 
Error: Failed to download https://codeload.github.com/kovidgoyal/kitty-themes/zip/master with error: Get "https://codeload.github.com/kovidgoyal/kitty-themes/zip/master": dial tcp: lookup codeload.github.com: no such host
```

`curl https://codeload.github.com/kovidgoyal/kitty-themes/zip/master` works and respects the ALL_PROXY variable.

**To Reproduce**
1. Type `kitten themes`
2. See error

**Screenshots**

**Environment details**
```
kitty 0.33.0 (04f8cb6d30) created by Kovid Goyal
Darwin MGC1G9T7JYXT 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 arm64
ProductName:            macOS ProductVersion:           14.3.1 BuildVersion:            23D60
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
Go does not support this: https://github.com/golang/go/issues/31813

**Comment by nighthawk469** [comment]
I got it working with 

```
export http_proxy=<proxy>
export https_proxy=<proxy>
kitten themes
```
