### ISSUE TITLE
How to run diff kitten over SSH?

### ISSUE THREAD

**Issue by alok** [kovidgoyal/kitty#727]
[The docs](https://sw.kovidgoyal.net/kitty/kittens/diff.html?highlight=ssh) mention that the diff kitten "displays images as well as text diffs, even over SSH", though I'm not clear on how to use that functionality.

In my gitconfig on both local and remotehost, I have my difftool set to `kitty +kitten diff $LOCAL $REMOTE`.

**Comment by kovidgoyal** [comment]
SSH into a computer that has kitty installed on it and run the diff kitten. You dont have to do anything.

**Comment by amanjitsk** [comment]
Following up on this, is there a way of doing a diff between two files, one on the local machine and one on the remote server. For example, using the built-in `diff`, I'd have to do something like 
```
ssh remoteserver "cat ~/.bashrc" | diff - ~/.bashrc
```
I tried doing something similar with `kitty +kitten diff`, but this does not accept `stdin` as one of the arguments. Any plans on adding this as a feature (or if it already exists) ? Ideally, I'd like to be able to do something like
```
kitty +kitten diff remoteserver:/home/user/.bashrc ~/.bashrc
```
where the ssh server names can be read from the user's ssh config file (sort of similar in syntax to `rsync`)

Thanks,
Amanjit

**Comment by kovidgoyal** [comment]
Just use /dev/stdin as the filename.

**Comment by amanjitsk** [comment]
![image](https://user-images.githubusercontent.com/12499495/66085746-184edd00-e540-11e9-9b39-b03364336203.png)

This is the error i get when I tried

```
ssh vws51 "cat ~/.tmux.conf" | kitty +kitten diff ~/.tmux.conf /dev/stdin
```

**Comment by amanjitsk** [comment]
![image](https://user-images.githubusercontent.com/12499495/66085897-7b407400-e540-11e9-9c34-06ea399dd3a9.png)

This is the error i get when i run the command below

```
ssh remoteserver "cat ~/.tmux.conf" | kitty +kitten diff ~/.tmux.conf /dev/stdin
```

**Comment by kovidgoyal** [comment]
Well ok, I have added the capability to diff files over ssh.
