### ISSUE TITLE
Kitty version 0.33.1 not showing some unicode character

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#7272]
Running Kitty version 0.33.1 on macOS 14.3 observed some of Unicode character not rendering .. while same I checked in other terminal app working fine

<img width="199" alt="image" src="https://github.com/kovidgoyal/kitty/assets/11479557/3c9fe21d-c8d8-45c9-828f-8cb99216fb31">

working 

<img width="174" alt="image" src="https://github.com/kovidgoyal/kitty/assets/11479557/d6438d11-cfa2-495a-82dc-bef54561b1eb">

**Comment by kovidgoyal** [comment]
dup of #7249
