### ISSUE TITLE
benchmark and optimize startup time

### ISSUE THREAD

**Issue by lolbinarycat** [kovidgoyal/kitty#7278]
**Is your feature request related to a problem? Please describe.**
based on [the performance page](https://sw.kovidgoyal.net/kitty/performance/), no effort was put into benchmarking and it kinda shows.

some rudimentary testing using the fish shell time builtin:
```
> time st bash -c exit

________________________________________________________
Executed in   47.18 millis    fish           external
   usr time   27.72 millis    0.31 millis   27.41 millis
   sys time   15.63 millis    1.06 millis   14.56 millis

> time konsole bash -c exit
________________________________________________________
Executed in  138.72 millis    fish           external
   usr time   99.65 millis  429.00 micros   99.22 millis
   sys time   36.83 millis  113.00 micros   36.71 millis

> time alacritty -e bash -c exit
________________________________________________________
Executed in  177.67 millis    fish           external
   usr time  112.26 millis  371.00 micros  111.89 millis
   sys time   55.26 millis   96.00 micros   55.16 millis

> time kitty bash -c exit
________________________________________________________
Executed in  404.49 millis    fish           external
   usr time  309.89 millis  499.00 micros  309.40 millis
   sys time   98.41 millis    0.00 micros   98.41 millis
```

out of all the terminal emulators i tested, `kitty` fared the wort on this (though in practice konsole is much worse, the subprocess exits long before the window shows up, if anyone can come up with a better methodology let me know)

as a sway user, i tend to open a lot of terminals.

**Describe the solution you'd like**
benchmark, profile, and optimize the time from exec until kitty has a window open and is able to respond to keyboard events. 

**Describe alternatives you've considered**
daemonize kitty so most of the startup only has to be done once.

**Comment by kovidgoyal** [comment]
kitty --single-instance
