### ISSUE TITLE
Invoke native fullscreen mode at startup on macOS

### ISSUE THREAD

**Issue by kutsan** [kovidgoyal/kitty#728]
Is there a way to activate fullscreen mode at startup on macOS? Pressing <kbd>^⌘F</kbd> would do that manually. Default `kitty_mod+f11` wouldn't work because it doesn't use native fullscreen functionality for some reason. I'm also aware that we have session file option but I don't know if it's capable to do that. Thanks in advance!

![image](https://user-images.githubusercontent.com/10108377/42823667-c92d57a2-89e6-11e8-9af3-81fe2f4fcc15.png)

**Comment by kovidgoyal** [comment]
kitty_mod+f11 is actually native full screen mode (it takes over the monitor, bypassing the OS window manager). What you call native fullscreen mode is managed by the OS not the application. If this was linux I'd tell you that you could create a rule in your window manager configuration to do this, on macOS, I dont know. I doubt Apple's window manager is powerful enough for tat kind of thig. You could switch to something like chunkwm or similar instead. 

Or you could add a config option to kitty to ave it request full screen from the OS on startup, not something I am interested in implementing myself, but patches are welcome.

**Comment by kutsan** [comment]
Yeah, I'm about to use something like that but I wondered if it's possible built-in via kitty. Thanks again, much appreciated.

**Comment by kutsan** [comment]
I got it working with this:

```conf
startup_session ~/.config/kitty/session.conf
```

```conf
new_tab
launch osascript -e 'tell app "System Events" to keystroke "f" using {control down, command down}'

new_tab
launch /usr/local/bin/zsh
```
> ~/.config/kitty/session.conf
