### ISSUE TITLE
Autohide tabbar

### ISSUE THREAD

**Issue by sassanh** [kovidgoyal/kitty#7280]
**Is your feature request related to a problem? Please describe.**
iTerm 2 has an option for tabbar which hides the tabbar all the time except for when you are switching between tabs, it would be nice if we could have something similar in Kitty.

**Additional context**
Relevant: https://github.com/kovidgoyal/kitty/issues/1014

**Comment by kovidgoyal** [comment]
So dont use a tab bar instead map a shortcut to  https://sw.kovidgoyal.net/kitty/actions/#action-select_tab

**Comment by sassanh** [comment]
@kovidgoyal 
That's a different thing, not close in experience to what I'm looking for, I want to go to the next tab/previous tab and just see the tab bar quickly while transitioning, I don't want to hide my whole terminal and render something else on top of it.
But if you are not willing to implement this feature in Kitty I understand.
