### ISSUE TITLE
Cursor gets Reset after sourcing ~/.zshrc

### ISSUE THREAD

**Issue by kuro337** [kovidgoyal/kitty#7282]
Hey! 

Loving the project , big props to yall :)

I was having an issue - whenever I source my zshrc - my cursor was getting reset to the Block Variant - tried following some of the threads but couldn't seem to get it to work

`~/.config/kitty/kitty.conf`

```
include current-theme.conf
initial_window_width 160c
initial_window_height 60c
enable_audio_bell no
font_family JetBrains Mono
font_size 18.0
scrollback_pager sh -c '$HOME/go/bin/vtclean | vim -'
active_tab_background   #0d1117
active_tab_foreground   #c9d1d9
tab_bar_background      #010409
```

`~/.zshrc`

```bash
# ZSH KURO
export STARSHIP_LOG="error"
export KITTY_SHELL_INTEGRATION="enabled" 
autoload -Uz -- $HOME/.config/kitty/kitty-integration; kitty-integration; unfunction kitty-integration 
```

Copied the kitty integration file from https://github.com/kovidgoyal/kitty/blob/master/shell-integration/zsh/kitty-integration

Thats it pretty much

For e.g

When I open the Application

![image](https://github.com/kovidgoyal/kitty/assets/65412787/0b272fa3-f3fd-4238-a698-cd494c1eee97)

Doing source zshrc

![image](https://github.com/kovidgoyal/kitty/assets/65412787/9e7a2593-1345-449f-8e3b-d171e2d3035a)

Gets Reset

**Comment by kovidgoyal** [comment]
1) Dont use manual integration unless you know what you are doing. There
is generally no need for it. If you must use it, do it like documented. See
https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration

2) Presumably something in your zshrc is causing this. Bisect it to find
the culprit.

**Comment by kuro337** [comment]
Yep fixed it, it was a zsh issue thanks
