### ISSUE TITLE
Scrolling became unusable on Wayland

### ISSUE THREAD

**Issue by rivenirvana** [kovidgoyal/kitty#7287]
**Describe the bug**
Scrolling the terminal with the mouse wheel has become unreliable and unusable on Wayland. It takes a significant amount of scrolling before it decides to scroll one line on either direction. The bug occurs throughout the usage of the terminal from launch, and inside programs. It also occurs even without a config, but scroll inputs seem to be captured correctly, as per `kitty -c NONE --debug-input`. Scrolling via touchpad works, as well as in X11. The bug first appeared from somewhere in between commits 8335a52 and 274a9d7, and has persisted up to master 94a612c, according to my COPR builds.

**Environment details**
- Fedora 39 and 40 Beta, GNOME Wayland
- kitty built nightly from master branch via COPR, specfile used for builds are highly similar to current Fedora sources

**Comment by kovidgoyal** [comment]
It will be this commit I would guess: https://github.com/kovidgoyal/kitty/commit/506be129e17e8cdfc511c3d0f6e0bb202ee0c17f

**Comment by kovidgoyal** [comment]
Just a heads up, I made another try at this: https://github.com/kovidgoyal/kitty/commit/7ec292e7c5ac062d201d47f95d199ee7b8152d31

I tested it with my mouse wheel and I found and fixed the bug in the original attempt, so it should be fine, but...

**Comment by rivenirvana** [comment]
I can confirm that it is working fine with my mouse wheel, as well.
