### ISSUE TITLE
kitty is constantly freezing up

### ISSUE THREAD

**Issue by jonathanmarvens** [kovidgoyal/kitty#7295]
**Describe the bug**
I recently decided to update __kitty__ to the latest version (`v0.33.1`) and it’s been the most frustrating update since I first started using __kitty__ a few years ago, which had been virtually flawless for me until this update. __kitty__ is constantly freezing up and requiring me to force quit it. And sadly, I have no idea what’s causing this issue.

**To Reproduce**
I’m not sure.

**Screenshots**
![Screenshot 2024-04-01 16:03:33](https://github.com/kovidgoyal/kitty/assets/890200/d4f2e40a-4706-42a7-83fc-04a6d688c304)

**Environment details**
```
kitty 0.33.1 (a5fea33757) created by Kovid Goyal
Linux base 5.15.0-101-generic #111~20.04.1-Ubuntu SMP Mon Mar 11 15:44:43 UTC 2024 x86_64
Zorin OS 16.3 base /dev/tty

DISTRIB_ID=Zorin
DISTRIB_RELEASE=16
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Zorin OS 16.3"
Running under: X11
Frozen: True
Paths:
  kitty: /home/jonathan/.local/opt/kitty/bin/kitty
  base dir: /home/jonathan/.local/opt/kitty/lib/kitty
  extensions dir: /home/jonathan/.local/opt/kitty/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /home/jonathan/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close    1
cursor_blink_interval      0.0
cursor_shape               3
cursor_text_color          None
cursor_underline_thickness 1.0
font_family                Inconsolata Nerd Font Mono
font_size                  14.0
scrollback_lines           4294967295
tab_bar_edge               1
tab_bar_min_tabs           1
tab_bar_style              separator
tab_separator                 ┇   
visual_bell_duration       1.0
Colors:
	active_border_color        #f8f8f2   
	active_tab_background      #f8f8f2   
	active_tab_foreground      #282a36   
	background                 #282a36   
	color0                     #21222c   
	color1                     #ff5555   
	color10                    #69ff94   
	color11                    #ffffa5   
	color12                    #d6acff   
	color13                    #ff92df   
	color14                    #a4ffff   
	color2                     #50fa7b   
	color3                     #f1fa8c   
	color4                     #bd93f9   
	color5                     #ff79c6   
	color6                     #8be9fd   
	color7                     #f8f8f2   
	color8                     #6272a4   
	color9                     #ff6e6e   
	cursor                     #f8f8f2   
	foreground                 #f8f8f2   
	inactive_border_color      #6272a4   
	inactive_tab_background    #6272a4   
	inactive_tab_foreground    #282a36   
	mark1_background           #ff5555   
	mark1_foreground           #282a36   
	selection_background       #44475a   
	selection_foreground       #ffffff   
	url_color                  #8be9fd   

Important environment variables seen by the kitty process:
	PATH                                /home/jonathan/.local/opt/kitty/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jonathan/.dotnet/tools
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :1
	USER                                jonathan
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_MENU_PREFIX                     gnome-
	XDG_CURRENT_DESKTOP                 zorin:GNOME
	XDG_SESSION_DESKTOP                 zorin
	XDG_DATA_DIRS                       /usr/share/zorin:/home/jonathan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-zorin:/etc/xdg
```

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
This will have nothing to do with kitty updates and something to do with
some other component on your system.

Regardless, there is nothing I can do to help you without a reproducer.
Or a bisect showing a problematic commit, or build kitty from source
with make debug-event-loop and try to find where it is freezing.

If you think it is caused by a kitty update then downgrade kitty all
previous releases are available as a first step to find which release it
starts happening in. Then build kitty from source and do git bisect to
find the problematic commit.

**Comment by jonathanmarvens** [comment]
Respectfully, it doesn’t make sense that this has nothing to do with upgrading __kitty__ when I’ve had literally no issues with __kitty__ for years until I updated it to the latest version, and nothing else on my system has changed (I’m extremely careful when it comes to changes/updates). I downgraded to `v0.31.0` (the previous version I had prior to the latest version) and __kitty__ hasn’t frozen up at all since I did that (on `v0.33.1`, it would’ve already frozen up at least a few times).

I don’t think it makes sense to just close this issue, because it’s a real issue and it’s unsolved, but it’s your project, so I won’t tell you what to do. As a user of __kitty__ who absolutely loves the project though, I must admit I’m disappointed here.

**Comment by teto** [comment]
I've seen the same with 0.33.1 on nixos-unstable. I've found similar older reports where someone mentioned the nvidia driver so I'll leave here min in case that helps.
```
$ nvidia-smi --version                                                                                                                                                                                    
NVIDIA-SMI version  : 550.67
NVML version        : 550.67
DRIVER version      : 550.67
CUDA Version        : 12.4
```

In my case it seems to happen regularly when I send neovim to the background with CTRL+Z. Then I can't input anything in my shells but I can switch to firefox and it works fine. What's troubling me is that if I try to open a tty with CTRL+ALT+F2/F3 it freezes as well. Is there a way to disable gpu to check if that's it ? meanwhile I am reverting to 0.33.0 to see if that changes anything.

**Comment by kovidgoyal** [comment]
This is definitely a driver issue. You can use the mesa env var to turn
on software rendering but performance will fall off a cliff. Cant
remember the name of the env var a quick google will find it.

**Comment by gfeun** [comment]
Chiming in to report the same bug, my terminals getting stuck when i Ctrl-Z from neovim with TTY also getting stuck in the process. 
And i have indeed upgraded nvidia drivers recently.

I tried downgrading my drivers from to `535.161.08` but it did not help.

Quite frustrating bug that i hope will get fixed upstream hopefully.
