### ISSUE TITLE
some font cannot show

### ISSUE THREAD

**Issue by newyorkthink** [kovidgoyal/kitty#7302]
![image](https://github.com/kovidgoyal/kitty/assets/87791643/fba1a250-db7c-4983-87ac-13d80f2506ec)

the font cannot show, 

version: latest
os deb
env:i3wm

**Comment by newyorkthink** [comment]
![image](https://github.com/kovidgoyal/kitty/assets/87791643/a0deae0a-75fe-4bc6-a69d-766595b58437)

**Comment by kovidgoyal** [comment]
dup of #7263
