### ISSUE TITLE
Possibly missing KP_ENTER in terminfo database

### ISSUE THREAD

**Issue by Pierre-Colin** [kovidgoyal/kitty#7304]
**Describe the bug**
When `nocompatible` is enabled, Vim uses the Kitty keyboard protocol, but the numpad <kbd>Enter</kbd> key is not treated as such. Instead, its CSI code 57414 is inserted as a UTF-8 character. This issue doesn’t arise for other keypad keys.

Although there is a workaround, it seems the definitive solution would be to [add an entry to the Kitty terminfo database](https://github.com/vim/vim/issues/14353#issuecomment-2029766389). While I’m not very familiar with terminfo, I gave it a shot  but with no success (I likely edited the wrong file).

**To Reproduce**
1. Start a Kitty terminal with `kitty --config NONE`.
2. Start Vim with `vim --clean -u NONE "+set nocompatible"`.
3. Press <kbd>A</kbd> to go into insert mode.
4. Press the keypad <kbd>Enter</kbd> key.

<details>

<summary>Environment details</summary>

```
kitty 0.33.0 created by Kovid Goyal
Linux marshev 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64
Arch Linux 6.8.2-arch2-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/pierre/.config/kitty/kitty.conf

Config options different from defaults:
bold_font         Bitstream Vera Sans Mono Bold
bold_italic_font  Bitstream Vera Sans Mono Bold Oblique
enable_audio_bell False
font_family       Bitstream Vera Sans Mono
font_size         9.0
italic_font       Bitstream Vera Sans Mono Oblique
Added shortcuts:
	shift+page_down →  scroll_page_down
	shift+page_up →  scroll_page_up
Colors:
	color1            #c00000   
	color10           #3fff3f   
	color11           #ffff3f   
	color12           #3f3fff   
	color13           #ff3fff   
	color14           #3fffff   
	color2            #00c000   
	color3            #c0c000   
	color4            #0000c0   
	color5            #c000c0   
	color6            #00c0c0   
	color7            #c0c0c0   
	color8            #3f3f3f   
	color9            #ff3f3f   
	foreground        #c0c0c0   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/pierre/.cargo/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                pierre
	XCURSOR_SIZE                        24
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
```
</details>

**Comment by kovidgoyal** [comment]
That doesnt make sense, the kitty keyboard protocol doesnt rely on
terminfo at all. All keys have set values that any terminal that
implements the protocol *must* follow. Therefore consuming applications
do not need terminfo to decipher key presses.

You can run

kitten show-key -m kitty

inside kitty to see the codes used and press the relevant key. vim needs
to add that code to whatever lookup table it uses for the protocol. The
complete list of codes is in the protocol spec.
https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions

Search for KP_ENTER
