### ISSUE TITLE
Q: Is `input_unicode_character` just a wrapper or there is more to it?

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#731]
Basically, is there any difference between the two, and if not, why do we have a special way to execute unicode_input kitten?

```
map ctrl+shift+u   input_unicode_character
map ctrl+shift+u   run_kitten text unicode_input
```

**Comment by kovidgoyal** [comment]
No difference as far as I recall. It's there for historical reasons, it was written before the kittens system existed in its present form.

**Comment by maximbaz** [comment]
OK, maybe make the [default config](https://sw.kovidgoyal.net/kitty/conf.html#miscellaneous) use `run_kitten` variant so that less and less people use the old form of referring to it 😉

**Comment by kovidgoyal** [comment]
Actually, IIRC run_kitten is obsolete as well :) I think the final form is just kitten

**Comment by kovidgoyal** [comment]
Oh and I think I remember why I used a special name for it. it is so that people reading through the conf file know what that setting is for. But I suppose just having kitten unicode_input is also fairly clear.
