### ISSUE TITLE
Build fails if  -D_FORTIFY_SOURCES is in env CFLAGS 

### ISSUE THREAD

**Issue by real-or-random** [kovidgoyal/kitty#7310]
**Describe the bug**
`setup.py` prepends the env CFLAGS with `-D_FORTIFY_SOURCES=2`. This leads to a build failure when the env CFLAGS contain a different definition. For example, Arch Linux recently switched to `-D_FORTIFY_SOURCES=3` (see https://rfc.archlinux.page/0017-increase-fortification-level/). When I try to build the Arch AUR package `kitty-git`, I get this (after modifying `setup.py` not to suppress stderr):
```
<command-line>: error: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
Failed to determine target architecture compiling test program failed with exit code: 1  
```
See https://aur.archlinux.org/packages/kitty-git#comment-961665 for more reports of this.

**Analysis/Suggestion**
This is a bit unfortunate. Usually, later CFLAGS override earlier CFLAGS (to give the user the last word), but not in the case of `-D`. (Strictly speaking, `-D_FORTIFY_SOURCES=2` belongs to CPPFLAGS, but it probably won't matter, and even Arch Linux's defaults get this wrong... edit: Apparently this is there for good reasons: https://rfc.archlinux.page/0003-buildflags/)

I suggest
 - adding `-D_FORTIFY_SOURCES=2` only if CFLAGS and CPPFLAGS don't contain the substring `-D_FORTIFY_SOURCES=`
 - switching to `-D_FORTIFY_SOURCES=3`  (this alone would make the problem go away on Arch Linux, but it's not a proper solution...)

**Comment by real-or-random** [comment]
> I am on Arch too, it doesnt set CFLAGS as an env var. This must be
> something specific to the kitty-git aur build script.

Okay, strictly speaking, Arch doesn't set it, but makepkg does: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/makepkg.conf?ref_type=heads

**Comment by CanadianBaconBoi** [comment]
The kitty-git package builds perfectly when manually running `makepkg -si`. The yay AUR helper is where the issue seems to lie.

**Comment by real-or-random** [comment]
> The kitty-git package builds perfectly when manually running `makepkg -si`. The yay AUR helper is where the issue seems to lie.

Okay, I don't know. I haven't tried this. Anyway, it's fixed now. :)

**Comment by kovidgoyal** [comment]
It prevents it from overriding fortify source yes, but there are many
other things it doesnt override anyway.
