### ISSUE TITLE
Alias Invader

### ISSUE THREAD

**Issue by C4E5G3** [kovidgoyal/kitty#7312]
(Absolutely love Kitty btw)

I have not set this as an alias, and I have not installed any kittens (to the best of my knowledge), so just curious about this alias, which appears when I CL "alias"
(obviously it is not in my alias configs)

```
$ alias
alias edit-in-kitty='kitten edit-in-kitty'
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/shell-integration
