### ISSUE TITLE
Question: Where is layouts.py?

### ISSUE THREAD

**Issue by bdmorin** [kovidgoyal/kitty#733]
In my default kitty.py is the following
```
# The enabled window layouts. A comma separated list of layout names. The special value * means
# all layouts. The first listed layout will be used as the startup layout.
# For a list of available layouts, see the file layouts.py
enabled_layouts *
```
I'm looking all over for layouts.py. I looked in source, and in releases, I can't find it anywhere. Any ideas what this means?

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.enabled_layouts

That help text is from a historical kitty.conf.
