### ISSUE TITLE
Bramhic script support in kitty

### ISSUE THREAD

**Issue by mm-crj** [kovidgoyal/kitty#7332]
**Is your feature request related to a problem? Please describe.**
I work with Indian language texts (Brambhic script). Kitty shows the joint glyphs as two different letters instead of the joint letter.
I have changed fonts to no effect.

**Describe the solution you'd like**
I would like to view joint letters as one letters in such scripts.

**Describe alternatives you've considered**
In Konsole this can be done by Menu>settings> configure Konsole> Profiles> new Profile> Edit> Appearance > Complex Text Layout Check Bramhic Script Character. However, Konsole is not so fast and feature rich. 

**Additional context**
Text as shown in Konsole
![image](https://github.com/kovidgoyal/kitty/assets/14097405/c06df1a1-e279-414b-b4d1-d3132a49e292)
Text as shown in kitty
![image](https://github.com/kovidgoyal/kitty/assets/14097405/ca495b3b-0afc-4e6f-8965-cca5edd569c0)

Its the same `MesloLGS NF:h11` font for both the terminals

**Comment by kovidgoyal** [comment]
kitty is a strictly character grid based display, which is part of what gives it
its speed, and such languages dont really fit into a character grid.
Supporting them would involve a redesign of the core of kitty and
regressing its performance for most other languages that do fit in a
grid. As such not something I plan on doing, sorry.
