### ISSUE TITLE
option to disable comprehensive keyboard (kitty.conf)

### ISSUE THREAD

**Issue by fschlegelone** [kovidgoyal/kitty#7333]
I don't even know why someone implemented random unicode characters being pasted to the prompt on execution of specific shortcuts, but I hate it. And it seems like there is no option you can set in kitty.conf to get rid of it. 
clear_all_shortcuts yes - unmaps all default shortcuts but not the comprehensive keyboards.

![CleanShot 2024-04-10 at 13 12 48@2x](https://github.com/kovidgoyal/kitty/assets/118682177/5a75b3ed-72c7-4ffb-9501-87b1390fa551)

**Comment by kovidgoyal** [comment]
So map the keys you dont want to generate events to discard_event

And be polite when you request help.
