### ISSUE TITLE
Ability to change keybinds inside of start_resizing_window mode?

### ISSUE THREAD

**Issue by jacobrreed** [kovidgoyal/kitty#7334]
**Is your feature request related to a problem? Please describe.**
https://sw.kovidgoyal.net/kitty/actions/#action-start_resizing_window -> currently when you enter resize mode it uses certain keybinds, i.e W for wider, N for narrower, T for taller, S for shorter, R for reset.
Would be nice to be able to change these binds

**Describe the solution you'd like**
Some option to customize these binds, I would like on entering resize mode to use vim like binds, i.e `j` for shorter, `k` for taller, `h` for wider, and `l` for narrower

**Describe alternatives you've considered**
Currently im binding alternate bind i.e `ctrl+t>j` to manually `resize_window shorter` but would like to use start_resizing_window instead

**Additional context**

**Comment by kovidgoyal** [comment]
You can use advanced keyboard mapping for this. See https://sw.kovidgoyal.net/kitty/mapping/

First, create a new keyboard mode that uses the send_key action to
trnsalate hjkl to wtns or whatever you like

Then map a shortcut using combine that both starts resizing mode and
also switches to the custom mode you created.

**Comment by kovidgoyal** [comment]
That should work fine, but note that you can also just map resizing
actions directly without going through the window, see https://sw.kovidgoyal.net/kitty/layouts/#window-resizing

**Comment by jacobrreed** [comment]
> That should work fine, but note that you can also just map resizing actions directly without going through the window, see https://sw.kovidgoyal.net/kitty/layouts/#window-resizing

ya im doing that as well, oh well thanks for the help

**Comment by jacobrreed** [comment]
ended up just doing this, works nice
```
map --new-mode resizing ctrl+t>r
map --mode resizing j resize_window shorter
map --mode resizing k resize_window taller
map --mode resizing l resize_window wider
map --mode resizing h resize_window narrower
map --mode resizing esc pop_keyboard_mode

```
