### ISSUE TITLE
macOS: Kitty opened from a file explorer only opens in new window, rather than new tab

### ISSUE THREAD

**Issue by nestedbuilder** [kovidgoyal/kitty#7335]
**Is your feature request related to a problem? Please describe.**
When opening kitty from a macOS file explorer, it always opens a new WINDOW (rather than a preferred new TAB). File explorers I've tested so far are QSpace Pro, and "Folders" (from the app store). With these 2 explorers, opening in the default Terminal.app does open new tabs for it. Which leads me to believe this is a terminal emulator specific issue/preference. But either I can't find a pre-existing preference for this, or it doesn't exist. 

**Describe the solution you'd like**
When opening kitty from an EXTERNAL app like a file explorer, I want some kind of preference (such as in kitty.conf) to enable force opening a new TAB by default (rather than opening a new window). 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kovidgoyal** [comment]
kitty has no way of knowing what you are opening it FROM. If you want to
open new tabs/windows/whatever in an existing kitty instance, you use
the remote control feature:
https://sw.kovidgoyal.net/kitty/remote-control/ configure your file
explorers to calla script that runs the remote control command.
