### ISSUE TITLE
Option to prevent closing tab/window if process other than the shell is running

### ISSUE THREAD

**Issue by amarshall** [kovidgoyal/kitty#734]
This would help prevent accidental termination of running processes. For example, the desired behavior:

1. Open Kitty
2. Run `cat`, or some other non-terminating process
3. Attempt to close tab/window
4. Refuses to close as there is a process running (possibly notified via popup alert)
5. User terminates `cat`
6. Attempt to close tab/window again, this time it’s successful as no processes other than the immediate child shell are running.

It shouldn’t matter, I think, if the subprocess is running in the foreground, background, or suspended.

For what it’s worth, both Terminal.app and iTerm 2 have this feature.

**Comment by kovidgoyal** [comment]
Personally, I have never been of fan of this behavior, I've always turned it off in terminal emulators that support it. If I ask a terminal emulator to do something, I dont want it to ask me if I'm sure. 

That said, I have no objection to adding an option (default off) for it, but I am not going to work on it myself, patches are welcome.

**Comment by frabjous** [comment]
You must not do your text editing in a terminal window... That's OK. I didn't need that work I did this morning that badly...

**Comment by kovidgoyal** [comment]
hahaha that is about the funniest thing I have ever heard. I do *everything* in a terminal window, except browse the internet, and even for that I have created my own browser with a key centric interface. https://github.com/kovidgoyal/vise

Again, if I ask a terminal emulator to do something, I dont want it asking me if I am sure.

**Comment by jenstroeger** [comment]
@kovidgoyal, take a look at [lynx](https://lynx.browser.org/) if you want terminal-based web-browsing.

> Again, if I ask a terminal emulator to do something, I dont want it asking me if I am sure.

In general, I agree, but quitting is not just “something” it is terminating the entire app. That might be accidental because (quite frankly) macOS sucks when it comes to window focus. It happens quite a bit that I hit Cmd+Q and close the wrong app because macOS focuses on other apps when I switch desktops, etc. In such cases I’d like to get a warning because I have a dozen vims open and they’re _all_ gone!

**Comment by frabjous** [comment]
I don't have any such excuse. I'm using i3gaps, with settings that make it pretty obvious what window is focused. 

Indeed, I'm also kitty's own option for applying a different alpha on inactive text, which helps with that too.

My problem is just that I'm an idiot. 

I have no idea how Kovid got to be so infallible, but I'm jealous.

If I get much much better with programming than I am now, I'll look into creating a patch. (But again, there's the whole idiot thing.)

**Comment by jenstroeger** [comment]
@frabjous, this has nothing to do with “idiot”, and if you’ve ever used multiple desktops on Mac, interleaved with Xquartz you’ll know what I mean. Mojave isn’t even able to remember the active app after the screen saver has kicked in, or periodic background tasks steal focus away from active terminals, etc…

**Comment by paperbenni** [comment]
I'd also really like to have this feature

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.confirm_os_window_close
