### ISSUE TITLE
reload config on sighup

### ISSUE THREAD

**Issue by lolbinarycat** [kovidgoyal/kitty#7341]
**Is your feature request related to a problem? Please describe.**
i have several terminal windows open, using `kitty --single-instance`.

the only way i've found to fix this is to find the pid of kitty using htop, kill the process, and restart
**Describe the solution you'd like**
like other long-running processes, kitty should reload its config after getting a SIGHUP signal

**Comment by kovidgoyal** [comment]
Read the first couple of paragraphs of https://sw.kovidgoyal.net/kitty/conf/
