### ISSUE TITLE
Floating tabs/panes

### ISSUE THREAD

**Issue by nitin88** [kovidgoyal/kitty#7345]
**Is your feature request related to a problem? Please describe.**
Currently Kitty supports both windows/tabs for organizing the terminal.
Within window, we can split tabs and re-arrange them in multiple ways.
Sometimes, we would like to "float" specific tab like Zjelli does https://zellij.dev/tutorials/basic-functionality/#using-floating-panes

**Comment by kovidgoyal** [comment]
Not something I am interested in as I dont see many use cases for it, but
patches are welcome. It is on my TODO list to implement floating/popup
windows useable by terminal programs rather than the user, this can be a
subset of that if and when I implement it.
