### ISSUE TITLE
Kitty Windows Locked Up On Certain Shell Completions When Spawn from VSCodium

### ISSUE THREAD

**Issue by iacore** [kovidgoyal/kitty#7347]
**Describe the bug**
Basically, when the terminals are spawn from VSCodium, the windows become unresponsive upon git shell completion (when I press Tab). If I close the VSCodium, the windows unfreeze immediately.

**To Reproduce**
1. Open a project in VSCodium 1.88.1.24102-1 or vscodium-bin-1.88.1.24104-1
2. Set User Preferences (JSON) `"terminal.external.linuxExec": "/usr/bin/kitty",`
3. Open a Kitty terminal with Ctrl+T
4. (Optionally) open more Kitty terminals from VSCodium with Ctrl+T
5. (Optionally) open Kitty terminals from any spawned Kitty terminal with `Ctrl+Shift+T`
6. enter `git reset` and press <kbd>Tab</kbd>
7. See error

When the kitty window is frozen, it seems like the terminal has forgotten to swap the rendering buffer.

**Environment details**
Artix, Fish

I want to diagnose this problem myself since it's rare to trigger. Please tell me how to diagnose this.

**Additional context**
`kitty --config NONE` does not change anything. still buggy.

I think the terminal and the shell are still processing keyboard input when the window is frozen. It is just not rendering.

**Comment by kovidgoyal** [comment]
Doesnt reproduce for me with those steps. However, I suggest you run
kitty with --detach and also check what environment variables are
vscodium is running kitty with https://sw.kovidgoyal.net/kitty/actions/#action-show_kitty_env_vars

**Comment by iacore** [comment]
`kitty --detach` has fixed it. The output of Ctrl-Shift-F6 under vscodium or not under vscodium are exactly the same.
