### ISSUE TITLE
Kitty 0.34 window titlebar icon not shown

### ISSUE THREAD

**Issue by winstonma** [kovidgoyal/kitty#7349]
**Describe the bug**
The window titlebar icon didn't show up

**To Reproduce**
1. Update kitty to 0.34
2. Open kitty

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/1215090/7949c761-423d-4f06-82c4-a7380cefe041).

**Environment details**
```
kitty 0.34.0 (2b671100d9) created by Kovid Goyal

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
Running under: Wayland (GNOME Shell 42.9) missing: preferred_scale
Frozen: True

Config options different from defaults:

Important environment variables seen by the kitty process:
        LANG                                en_US.UTF-8
        SHELL                               /bin/bash
        DISPLAY                             :0
        WAYLAND_DISPLAY                     wayland-0
        LC_TIME                             en_HK.UTF-8
        XDG_SESSION_TYPE                    wayland
        LC_MONETARY                         en_HK.UTF-8
        XDG_SESSION_CLASS                   user
        XDG_RUNTIME_DIR                     /run/user/1000
        LC_ADDRESS                          en_HK.UTF-8
        XDG_MENU_PREFIX                     gnome-
        LC_TELEPHONE                        en_HK.UTF-8
        XDG_CURRENT_DESKTOP                 ubuntu:GNOME
        XDG_SESSION_DESKTOP                 ubuntu
        LC_NAME                             en_HK.UTF-8
        LC_MEASUREMENT                      en_HK.UTF-8
        LC_IDENTIFICATION                   en_HK.UTF-8
        XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
        LC_NUMERIC                          en_HK.UTF-8
        LC_PAPER                            en_HK.UTF-8
```

**Additional context**
`kitty --config NONE` doesn't get the icon back

**Comment by kovidgoyal** [comment]
Yes, it was changed to and angle bracket. And you need to install a font
that has the maximize/minimize/etc unicode symbols to see th ebuttons on
the right.

**Comment by winstonma** [comment]
@kovidgoyal I am using Ubuntu font and unicode is not included. Just wonder if it is possible that I could get the titlebar removed? Thanks

**Comment by kovidgoyal** [comment]
On Mon, Apr 15, 2024 at 07:17:03PM -0700, Winston Ma wrote:
> @kovidgoyal I am using Ubuntu font and unicode is not included. Just wonder if it is possible that I could get the titlebar removed? Thanks

You need to have *some* font on your system that has those glyphs. It
doesnt need to be your main font.
And read: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.hide_window_decorations

**Comment by winstonma** [comment]
Thanks a lot. Alternatively I did the following 

1. Install Noto San Fonts
```bash
sudo apt-get install fonts-noto
```
2. [Use Gnome Tweaks and Set Interface text as `Noto Sans Regular`](https://www.omgubuntu.co.uk/2016/03/how-to-change-ubuntu-desktop-font)
3. Open Kitty

Now it works. Hope this help other Ubuntu User.

**Comment by ryannathans** [comment]
I have two machines, both Pop OS 22.04.
In gnome tweaks, both have the same fonts set: 
![image](https://github.com/kovidgoyal/kitty/assets/1307375/554772cc-41dd-490d-8832-8ba04d6fb1c3)

Yet one still displays these squares..
![image](https://github.com/kovidgoyal/kitty/assets/1307375/da84e66a-e1e7-4dba-a5a4-2afb25b21f7f)

Any ideas? Has got me scratching my head

**Comment by winstonma** [comment]
@ryannathans The font add [many unicode characters on version 6 release](https://github.com/tonsky/FiraCode/releases/tag/6). I think it is worth updating the font on both machines.

**Comment by ryannathans** [comment]
`sudo apt install fonts-firacode`
`fonts-firacode is already the newest version (6.2-1).`

I don't think this font is directly related to my interface font Fira Sans Book, but regardless, it's already the latest version on the system with broken icons.

**Comment by ryannathans** [comment]
Genius solution, thanks

**Comment by grimm26** [comment]
> Thanks a lot. Alternatively I did the following
> 
> 1. Install Noto San Fonts
> 
> ```shell
> sudo apt-get install fonts-noto
> ```
> 
> 2. [Use Gnome Tweaks and Set Interface text as `Noto Sans Regular`](https://www.omgubuntu.co.uk/2016/03/how-to-change-ubuntu-desktop-font)
> 3. Open Kitty
> 
> Now it works. Hope this help other Ubuntu/Gnome User.

fonts-symbola is the package you needed

**Comment by winstonma** [comment]
> fonts-symbola is the package you needed

Thanks. Installed 0.34.1 which the icon is built-in. I can uninstall Noto fonts now.

**Comment by BoltsJ** [comment]
Is there a way to simply hide the window control buttons? I think the old titlebar without them looked better.
