### ISSUE TITLE
Environment for $PAGER Scrollback <ctrl+shift+h>

### ISSUE THREAD

**Issue by arolle** [kovidgoyal/kitty#735]
The environment for the `$PAGER` is different from the user environment when kitty is started through the kitty.app on macOS.

Steps to repoduce
- start kitty.app
- `<ctrl+shift+h>`
- `! env`

Compare this to
- start kitty. app
- `$ kitty`
- `<ctrl+shift+h>`
- `! env`

For me in the first case this breaks support for non-ASCII characters. Compare the two in the pager:

1.
   ```
   $ tree -L 1
   .
   <E2><94><94><E2><94><80><E2><94><80> foo
   ```
  
2.
   ```
   $ tree -L 1
   .
   └── foo
   ```

A solution might be to internally invoke the pager or kitty (within kitty.app) in the shell that is specified in the config.

**Comment by kovidgoyal** [comment]
No the solution is to properly set your user environment (mainly LANG) via launchd not shell startup scripts, which is the correct way to set user environment on macOS. That way all your applicatoins get the same environment regardless of how they are started.
