### ISSUE TITLE
Not sure background_blur for KDE (kitty 0.34.0) is working correctly.

### ISSUE THREAD

**Issue by jonwilts** [kovidgoyal/kitty#7351]
**Describe the bug**

Kitty 0.34.0 running with a wayland backend on KDE Plasma 6.0.3, on an old 2015 Macbook Air with an Intel HD6000 graphics chip and the latest i915 driver.

```
background_opacity 0.8
dynamic_background_opacity yes
```

With `background_blur=0` kitty + desktop looks like this:
 ![Screenshot_20240416_060751](https://github.com/kovidgoyal/kitty/assets/9073828/4bd8b5b5-11db-494e-8ff5-bfa5eb3bd38e) 

With `background_blur=1` or any other integer > 0, kitty looks like this:
![Screenshot_20240416_061034](https://github.com/kovidgoyal/kitty/assets/9073828/c3995101-3986-4b9f-b015-f93fac4f9dc4)

If it isn't clear - the background is now almost entirely black & opaque. That darker rectangle is a window behind kitty - so there is some transparency - but as you can see it's blurred beyond all usability. I tried various values between 1 and 64 and there's no discernible difference - just total blur!

Also, when background_blur > 0, resizing the window causes this:
![Screenshot_20240416_061241](https://github.com/kovidgoyal/kitty/assets/9073828/e0e3e283-380c-4640-97eb-0aa198930016)

**To Reproduce**
- Install KDE 6.0.3
- Install Kitty 0.34.0
- Set kitty.conf values as above.

**Screenshots**
See above.

**Environment details**
```
kitty 0.34.0 (2b671100d9) created by Kovid Goyal
Linux air 6.8.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:18 +0000 x86_64
Arch Linux 6.8.5-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland (kwin 6.0.3) missing: single_pixel_buffer
Frozen: True
Paths:
  kitty: /opt/kitty/kitty_2024-04-15/bin/kitty
  base dir: /opt/kitty/kitty_2024-04-15/lib/kitty
  extensions dir: /opt/kitty/kitty_2024-04-15/lib/kitty-extensions
  system shell: /usr/bin/bash
Loaded config files:
  /home/jon/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       yes
background_blur            64
confirm_os_window_close    0
dynamic_background_opacity True
font_family                FiraCode Nerd Font
font_features:
{'FiraCodeNF-Ret': ('+ss03',)}
font_size                  10.5
initial_window_height      (836, 'px')
initial_window_width       (1070, 'px')
linux_display_server       wayland
listen_on                  unix:@kitty{kitty_pid}
remember_window_size       False
shell_integration          frozenset({'disabled'})
tab_bar_edge               1
tab_bar_margin_height      TabBarMarginHeight(outer=5.0, inner=0)
tab_bar_style              slant
wayland_enable_ime         False
window_padding_width       FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Added shortcuts:
	shift+super+[ →  previous_window
	shift+super+] →  next_window
	shift+super+c →  copy_to_clipboard
	shift+super+t →  new_window
	shift+super+v →  paste_from_clipboard
	super+[ →  previous_tab
	super+] →  next_tab
	super+enter →  toggle_fullscreen
	super+t →  new_tab
Colors:
	active_tab_background      #e5e9f0   
	active_tab_foreground      #2e3440   
	inactive_tab_background    #4c566a   
	inactive_tab_foreground    #2e3440   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/bash
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                jon
	XDG_CONFIG_DIRS                     /home/jon/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/jon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_MENU_PREFIX                     plasma-
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
kitty has no control over the blurring the KDE blur protocol is simply a
boolean. The integer value is used only on macOS. If you dont like the
blurring, report it to KDE.

**Comment by jonwilts** [comment]
Ah - ok - thank you. Configuring the blur effect in KDE does improve it.

However, I think the resizing issue is kitty's - resizing eg konsole works as expected.

**Comment by jonwilts** [comment]
These pictures illustrate the resizing issue better:

Kitty at initial launch, over a Dolphin window:
![Screenshot_20240416_072556](https://github.com/kovidgoyal/kitty/assets/9073828/61a2cfd5-fb18-441a-85d0-3af7c85a074e)

Resizing kitty by stretching the window downwards:
![Screenshot_20240416_072812](https://github.com/kovidgoyal/kitty/assets/9073828/14f88008-0971-4357-bacc-85795a7799e8)

**Comment by jonwilts** [comment]
Confirmed that fixes it. Thank you.
