### ISSUE TITLE
Copy & paste stops working in Kitty sporadically

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [kovidgoyal/kitty#7353]
**Describe the bug**

Copy & paste sporadically does not work any more. When that happens, trying to copy & paste within Kitty does not work no matter how often you try. When you copy from another app then it works again

**To Reproduce**
1. see above

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
kitty 0.31.0 created by Kovid Goyal
Linux vbm 6.7.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:58:50 +0000 x86_64
Arch Linux 6.7.9-zen1-1-zen (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/vbm/.config/kitty/kitty.conf
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control yes
enable_audio_bell    False
font_size            24.0
scrollback_lines     5000
startup_session      /home/vbm/.config/kitty/session.conf
Added shortcuts:
        alt+i →  next_tab
        alt+j →  scroll_line_down
        alt+k →  scroll_line_up
        alt+o →  previous_tab
        alt+q →  show_scrollback
        alt+x →  close_window
        ctrl+alt+a →  move_tab_backward
        ctrl+alt+e →  move_tab_forward
        ctrl+alt+p →  toggle_layout stack
        ctrl+alt+s →  goto_layout stack
        ctrl+alt+t →  set_tab_title
        ctrl+alt+z →  last_used_layout
        ctrl+down →  neighboring_window bottom
        ctrl+left →  neighboring_window left
        ctrl+p →  nth_window -1
        ctrl+q →  close_tab
        ctrl+right →  neighboring_window right
        ctrl+shift+m →  toggle_marker iregex 1 \\bERROR\\b 2 \\bWARNING\\b
        ctrl+up →  neighboring_window up
        ctrl+v →  paste_from_clipboard
        kitty_mod+y →  launch neomutt
        shift+super+i →  set_tab_title
        super+c →  copy_to_clipboard
        super+q →  quit
        super+v →  paste_from_clipboard
Changed shortcuts:
        kitty_mod+h →  kitten pass_keys.py neighboring_window left   ctrl+h
        kitty_mod+j →  kitten pass_keys.py neighboring_window bottom ctrl+j
        kitty_mod+k →  kitten pass_keys.py neighboring_window top    ctrl+k
        kitty_mod+l →  kitten pass_keys.py neighboring_window right  ctrl+l

Important environment variables seen by the kitty process:
        PATH                                /usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin
        LANG                                en_GB.UTF-8
        EDITOR                              vim
        SHELL                               /bin/zsh
        GLFW_IM_MODULE                      ibus 
        DISPLAY                             :0
        WAYLAND_DISPLAY                     wayland-1
        USER                                vbm
        XCURSOR_SIZE                        32
        XDG_BACKEND                         wayland
        LC_MONETARY                         de_DE.UTF-8
        XDG_SEAT                            seat0
        XDG_SESSION_DESKTOP                 hyprland
        XDG_SESSION_TYPE                    wayland
        LC_PAPER                            de_DE.UTF-8
        XDG_CURRENT_DESKTOP                 Hyprland
        XDG_SESSION_CLASS                   user
        LC_MEASUREMENT                      de_DE.UTF-8
        XDG_VTNR                            2
        XDG_SESSION_ID                      1
        XDG_RUNTIME_DIR                     /run/user/1000
        LC_TIME                             de_DE.UTF-8
        XDG_DATA_DIRS                       /usr/local/share/:/usr/share/:/var/lib/snapd/desktop
        LC_NUMERIC                          de_DE.UTF-8

This debug output has been copied to the clipboard
(END)

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You havent posted the full debug output.

**Comment by kovidgoyal** [comment]
Your version of kitty is outdated, first update and see if you can reproduce. Because I cannot reproduce using current kitty. And the debug output is opened in less, copying using kitty copy can only copy a screenfull since less only displays a screenfull at a time. And note that debug output is copied to theclipboard automatically.
