### ISSUE TITLE
Running kitten ssh in zellij doesn't work

### ISSUE THREAD

**Issue by munnik** [kovidgoyal/kitty#7357]
> I'm afraid there isnt anything I can do to help you since, literally any
> program/command on the remote system could be hanging. You will need to
> log into it and debug the issue yourself. 

Normal ssh just works fine, but running it with the kitten wrapper does not show a shell prompt.

I just found out that [Zellij](https://zellij.dev/) is somehow causing the issue. If I run it directly from kitty I get a shell prompt after login, running it from within a Zellij workspace causes the issue.

> If you need pointers on how to get started, feel free to ask, I will provide.

Are there any verbose options when running `kitten ssh`?

_Originally posted by @munnik in https://github.com/kovidgoyal/kitty/issues/7355#issuecomment-2061113165_

**Comment by kovidgoyal** [comment]
dup of #7355 follow up there
