### ISSUE TITLE
Graphics not staying with text

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#736]
I just began using kitty and it renders images with very good quality. However I've noticed that even though the graphics scroll with the text, when I change the layout with `ctrl+shift+l`, the images are no longer aligned with the text and lose their original position. This is even worse when I do a page break in the terminal with `ctrl + l` as this causes images to be removed from the window.

**Comment by kovidgoyal** [comment]
Yeah there is no good way to preserve graphics position on resize, because on resize text can wrap/unwrap. So if there is graphics on line N, the corresponding text could be anywhere, on line N+-M. Since graphics are positioned absolutely, there is no way to wrap them along with the text.

As for ctrl + l it removes both text and graphics, that is by design (IIRC internally it operates as a clear)

**Comment by kovidgoyal** [comment]
If you are coming from a libsixel based terminal emulator, this is different in kitty. libsixel based images are part of the text, so they rewrap automatically (but they can get distorted by resizes if they are close to the edge). In kitty, graphics care not part of the text but can be displayed either over or under it.

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks for explaining the cause of this phenomenon. Is this a limitation of having alpha blending and text over/under images?
I'm coming from gnome terminal, not sure if its libsixel or not but for me `ctrl + l` acts like a page break, it doesn't remove text unless when I've reached the limit of scrollback.

**Comment by kovidgoyal** [comment]
ctrl+l is not implemented in terminal emulators it is implemented in shells. A terminal emulator sends an ascii control code known as the form feed when you press ctrl+l. What happens on the screen after that depends on what program is running. Many shells and readline based programs interpret form-feed as clear screen. Try the following experiment. Run cat and then press ctrl-l you will see the output ^L no screen clearing.
