### ISSUE TITLE
Path hints only copy up to the first space instead of the full path

### ISSUE THREAD

**Issue by ArijanJ** [kovidgoyal/kitty#7362]
**Is your feature request related to a problem? Please describe.**
Path hints use the same selection logic as words as far as I can tell, the only difference is where the hint is displayed.
This obviously leads to the full path not being selected for the hint action if it contains spaces:
![image](https://github.com/kovidgoyal/kitty/assets/56356662/3ea19426-ad76-4005-bf8a-6433084caafe)
(the green is what's actually selected)

**Describe the solution you'd like**
The path parser (haven't looked at the implementation, sorry) should continue if it encounters a `\` or ignore spaces if the first character in the whole match is a quote.

**Describe alternatives you've considered**
None yet, please feel free to share if anything comes to mind.

**Additional context**
There is some backtracking going on already, so the quotes shouldn't be a problem (there is no / at the beginning of these):
![image](https://github.com/kovidgoyal/kitty/assets/56356662/eaefd7bd-db90-49f1-8e90-ab5a21509fd1)

**Comment by kovidgoyal** [comment]
Lots of tools output paths in contexts where they are separated by
spaces. As such the path matching treats space as a boundary. That's not
going to change. Fortunately, the hints kitten is completely
customizable to the extent that you can write your own matching logic,
see its docs.

Although from your description it sounds like you want to match the
output of ls, which you can do much more robustly by using
ls --hyperlink-auto and using the hints kitten in hyperlink mode with
ctrl+shift+p>y
