### ISSUE TITLE
Kitty application won't open

### ISSUE THREAD

**Issue by Ssionn** [kovidgoyal/kitty#7364]
**Describe the bug**
I've installed the binary but It won't open the application, any reason why this could happen?

```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
```

**To Reproduce**
1. Install binary
2. Open kitty
3. Nothing...

**Screenshots**

https://github.com/kovidgoyal/kitty/assets/90753599/58fb2d17-6d7c-4dd1-9f7d-8059cb3a82d6

**Environment details**
None

**Comment by kovidgoyal** [comment]
Run it from another  terminal then  you might get some information about why it's not running.
