### ISSUE TITLE
Ghosting in GIF Animation

### ISSUE THREAD

**Issue by v4u6h4n** [kovidgoyal/kitty#7365]
**Describe the bug**
I'm getting some ghosting of previous frames during the animation of a specific GIF, not sure what the problem is. I tried a couple other from a web search and they all seem to render fine. Any suggestions would be appreciated :-)

**To Reproduce**
`kitty icat https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_dcd06b30a5c24f6eb871e8f5edbd44f7/default/dark/1.0`

**Environment details**
Arch linux

**Additional context**
Tested `kitty --config NONE` with the same result.

**Comment by kovidgoyal** [comment]
It will be ebcause that GIF is buggy. Browsers have various heuristics
ot fix buggy gifs that kitty's icat does not implement. If you search
the issues for GIF you will find more details.

**Comment by v4u6h4n** [comment]
Thanks :-)
