### ISSUE TITLE
Clarification needed on how to use the hint kitten

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#737]
The hint kitten is a powerful feature that would be very useful to me. My current use case is for selecting paths in the terminal and reusing them in different commands. I use a non-US keyboard and I can't type the shortcut __ctrl+shift+p>f__. Does this literally mean hold down __ctrl, shift, p, >__ and __f__?

I've also tried using it via the commandline but I cannot get it to work:
```
Loaded config files: /home/user/.config/kitty/kitty.conf

Config options different from defaults:
[user@fedora28 ~]$ kitty +kitten hints --type path --program -
You must pass the text to be hinted on STDIN
Press Enter to quit
```

**Comment by maximbaz** [comment]
It means: hold Ctrl, Shift and press p, then release all, then press f

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks, it worked. For the commandline version, do you know how it works?

**Comment by kovidgoyal** [comment]
There is no command line version. You use it by pressing shortcut keys in kitty. It is implemented as a command line program, as are all kittens. You can use the different command line options to create new shortcut mappings in your kitty.conf.

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks for confirming @kovidgoyal, it's very well designed.
