### ISSUE TITLE
Launch kitten with remote control

### ISSUE THREAD

**Issue by net** [kovidgoyal/kitty#738]
Could we get a way to launch kittens in the current window/matched windows via the remote control interface?

`kitty @ kitten [--match <match>] <kitten path/name> [args]`

This would allow contextual arguments to be passed to kittens and kittens to be launched programmatically from scripts.

![](http://catnipsum.com/wp-content/uploads/2013/03/wishing-cat.jpg)

**Comment by kovidgoyal** [comment]
I like the pic :) However, what is the use case for this? If all you want to do is run a program in a new window, you can do it already with just running

kitty kitty +launch program-to-run.py

Is there something the kitten system allows you to do that you cannot by running an arbitrary program?

**Comment by net** [comment]
I'd like to run a program in a new window covering an existing window.

**Comment by net** [comment]
Wow, thanks!

<img height="580" src="https://user-images.githubusercontent.com/6983821/43207177-6c2e3bf6-8ff5-11e8-8a56-01a4065648ee.jpg">
