### ISSUE TITLE
kitty: incorrectly acts like mouse button is pressed

### ISSUE THREAD

**Issue by nileshpatra** [kovidgoyal/kitty#7382]
Hi

We have got https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069740 in debian. Pasting the content:

Package: kitty
Version: 0.33.1-1
Severity: normal

I routinely run kitty with between 4 and 16 terminals in one kitty window.
When moving the mouse across the screen it's a common occurance (multiple
times per hour) for one terminal to act like the mouse button is pressed
and try to make it a swipe to select operation.

This happens on my laptop running Unstable and my workstation running
Bookworm.

-- System Information:
Debian Release: trixie/sid
Architecture: amd64 (x86_64)

Kernel: Linux 6.7.9-amd64 (SMP w/4 CPU threads; PREEMPT)
Kernel taint flags: TAINT_WARN
Locale: LANG=en_AU.UTF-8, LC_CTYPE=en_AU.UTF-8 (charmap=UTF-8), LANGUAGE=en_AU:en
Shell: /bin/sh linked to /usr/bin/dash
Init: unable to detect

Versions of packages kitty depends on:
ii  kitty-shell-integration  0.33.1-1
ii  kitty-terminfo           0.33.1-1
ii  libc6                    2.37-18
ii  libdbus-1-3              1.14.10-4+b1
ii  libharfbuzz0b            8.3.0-2+b1
ii  liblcms2-2               2.14-2+b1
ii  libpng16-16t64           1.6.43-5
ii  libpython3.11t64         3.11.9-1
ii  libssl3t64               3.2.1-3
ii  libwayland-client0       1.22.0-2.1+b1
ii  libx11-6                 2:1.8.7-1
ii  libx11-xcb1              2:1.8.7-1
ii  libxcursor1              1:1.2.1-1
ii  libxkbcommon-x11-0       1.6.0-1
ii  libxkbcommon0            1.6.0-1
ii  libxxhash0               0.8.2-2+b1
ii  python3                  3.11.8-1
ii  python3.11               3.11.9-1
ii  zlib1g                   1:1.3.dfsg-3.1

Versions of packages kitty recommends:
pn  kitty-doc                       <none>
ii  libcanberra0t64 [libcanberra0]  0.30-12.2+b2

Versions of packages kitty suggests:
ii  imagemagick                      8:6.9.12.98+dfsg1-5.2
ii  imagemagick-6.q16 [imagemagick]  8:6.9.12.98+dfsg1-5.2

-- debconf-show failed

**Comment by kovidgoyal** [comment]
dup of #7381
