### ISSUE TITLE
Open new tab next to current instead of at the end of the list of open tabs.

### ISSUE THREAD

**Issue by p7r0x7** [kovidgoyal/kitty#7388]
When I Ctrl-Alt-T to make a new tab, I'd prefer kitty open that tab immediately following the current tab, moving the rest over; this is a common default on web browsers.

Can an option be added for this?

It may also make sense to make the tab list optionally grow left instead right, and allow the list to be left aligned instead of right aligned.

**Comment by kovidgoyal** [comment]
Both these questions are answered in the docs:

https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-location
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.tab_bar_style
