### ISSUE TITLE
Unable to open config file in kitty with ctrl+shift+f2

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#739]
When I try to open the config file in kitty using __ctrl+shift+f2__ a new pop up window appears for half a second and disappears. How do I open the config file using this shortcut?

**Comment by Althorion** [comment]
What's your `$EDITOR`?

**Comment by kovidgoyal** [comment]
That's likely because you dont have the EDITOR environment variable set. Set it to whatever terminal editor you like. Or set the editro option in kitty.conf. If it is not set kitty uses vim by default, so you presumably dont have vim installed.

**Comment by ChukwuemezieChristopherAneke** [comment]
Yes, your suspicions are correct, $EDITOR is not set but I do have vi installed. Shouldn't kitty have used Vi then?

**Comment by kovidgoyal** [comment]
No vi, but vim see line 407 of kitty/utils.py
