### ISSUE TITLE
per window background color

### ISSUE THREAD

**Issue by FalcoGer** [kovidgoyal/kitty#7392]
**Is your feature request related to a problem? Please describe.**
I often find myself working with multiple SSH instances and even though the hostname is in my prompt, it would be more noticeable if the whole terminal window were a different color. I know i can start `kitty -o background="#400"`, but then all new tabs and windows will have that color. I'd like a solution where I can have multiple windows in the same tab and cycle through a list of background colors.

**Describe the solution you'd like**
A configuration option where I define a list of background colors and a facility to map keyboard bindings where I can cycle through them and/or pick the n-th one.

**Describe alternatives you've considered**
Some kind of interactive color selection that comes up with a key bind.
Some kind of automatic color selection based on the hostname, so on local it would be black, on dev it would be blue and on production it would be red or something. Though I sometimes do CTFs and the hostnames vary wildly and i don't always use the standard ssh. so something manual would also be nice.

**Additional context**
Something like this in mate-terminal.
![image](https://github.com/kovidgoyal/kitty/assets/16250196/2cbfb1de-b2a5-45ff-acfb-a2b4cbc0f781)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by FalcoGer** [comment]
Thank you.

For reference and others looking for a solution. I created red.conf in ~/.config/kitty/
```
# either same as in kitty.conf or same as background in kitty.conf.
tab_bar_background      #121212
tab_bar_margin_color    #121212

foreground #00DF00
background #180000
```

and added this to kitty.conf

```
map kitty_mod+alt+1  set_colors --configured /home/paul/.config/kitty/kitty.conf
map kitty_mod+alt+2  set_colors --configured /home/paul/.config/kitty/red.conf
map kitty_mod+alt+3  [...]
```

then ctrl+shift+alt+numbers can switch profiles
