### ISSUE TITLE
Option for alternate rendering of shade characters

### ISSUE THREAD

**Issue by etzrx** [kovidgoyal/kitty#7398]
The way kitty renders the Unicode shade characters results in them not tiling seamlessly on most font sizes.

You can see that in this image

<img width="623" alt="image" src="https://github.com/kovidgoyal/kitty/assets/134213432/4315ae24-e72b-4bd8-8dad-6feb9d35b210">

And (on mac Retina displays anyway) the Moiré patterns this creates are character-aligned, which makes the above image look like the 2nd row is darker or lighter than the rest.

I don't know of any way to fix this while keeping each character identical. 
But some fonts use diagonal lines instead like below, which solves both issues at the expense of not looking like the majority of fonts

<img width="443" alt="image" src="https://github.com/kovidgoyal/kitty/assets/134213432/008cbca4-c664-4e5d-87f5-d050d2defa66"> ( Iosevka in iTerm2 )

Would adding something like this as an alternative option be a good idea?

**Comment by kovidgoyal** [comment]
I'm afraid not, kitty renders these characters as their appearance is
specified in the Unicode standard. Having a standard rendering allows
writes of programs running in kitty to rely on that appearance in their
code.

Personally speaking, I would like shade characters to be rendered as
semi-transparent blocks, IMO that's the most useful, but...

**Comment by kovidgoyal** [comment]
What grid's dimensions? And you are welcome to send a PR to improve their rendering as long a their apperance remains consistent with the unicode spec.
