### ISSUE TITLE
Enter key outputs ^M instead of executing command during apt upgrade prompt

### ISSUE THREAD

**Issue by h-b** [kovidgoyal/kitty#7399]
**Description**
In the kitty terminal (version 0.33.1), pressing the Enter key during a `sudo apt upgrade` prompt does not execute the command but instead outputs `^M`. This issue specifically occurs when responding to interactive prompts in the terminal. Normal functionality of the Enter key is observed in other uses within the terminal as well as in other terminal emulators like XFCE's terminal.

**To Reproduce**
- Open kitty terminal.
- ssh into Debian based server (either with `kitten ssh` or with `ssh`)
- run sudo apt upgrade.
- when prompted to continue with [Y/n], press the Enter key.

**Environment details**
```
kitty 0.33.1 created by Kovid Goyal
Linux akino 6.8.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:00 +0000 x86_64
Garuda Linux 6.8.7-zen1-1-zen (/dev/tty)

DISTRIB_ID=Garuda
DISTRIB_RELEASE=Soaring
DISTRIB_DESCRIPTION="Garuda Linux"
DISTRIB_CODENAME="Spizaetus"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/stefan/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell False
font_size         9.0
Added shortcuts:
	shift+alt+escape →  kitty_shell window

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                C.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :0.0
	USER                                stefan
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     xfce-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 xfce
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/stefan
	XDG_CURRENT_DESKTOP                 XFCE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share
```

**Additional context**
I manage two headless Ubuntu servers. Interestingly, the issue of the Enter key outputting `^M` during interactive prompts occurs only on one server. Both servers are configured with $SHELL set to `/bin/bash` and $TERM set to `xterm-kitty`, which suggests that the terminal settings are consistent across both. This leads me to believe that a specific configuration on the affected server might be responsible for this anomaly. I am ready to provide further details about this server's configuration to assist in diagnosing the issue.

**Comment by kovidgoyal** [comment]
Does not reproduce for me. You are likely missing the kitty terminfo in
your sudo environment, read the kitty FAQ on the subject, especially the
part about sudo.

https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work
