### ISSUE TITLE
Unable to write \ { } MacOS (scandinavian layout)

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#74]
I stumbled upon this application the other night, and have to say I'm very impressed by the speed and responsiveness. There is a slight problem preventing me from being able to replace my old terminal application, namely the ability to type `\` `{` and `}`

My keyboard has norwegian (scandinavian) layout, and so I have to press `shift + alt - { 7, 8, 9 }` for these characters, yet these keypresses are not registered in the Kitty prompt or any application running inside of it.

I have forked the project (and glfw) to do some other personal unrelated tweaks, and was wondering if you had any idea pointers as to where this issue may come from?

**Comment by kovidgoyal** [comment]
keyboard handling happens in keys.py see get_localized_key()

**Comment by koekeishiya** [comment]
Thanks, I'll take a look at it.

Also just another minor issue, not sure if I'm missing something. After building Kitty from source, using `python3 setup.py osx-bundle`, the prompt seems to always start from the MacOS Resources directory, rather than the home folder. Am I doing something wrong here?

**Comment by kovidgoyal** [comment]
Unfortunately, I dont have an OS X machine capable of running kitty, only building it. But, this should be taken care of by line 228 in main.py

I'd guess you are not launching the newly built kitty via launch services. If you want to run kitty from source, there is no need to use osx-bundle. Just python3 setup.py build && python3 .

**Comment by koekeishiya** [comment]
I was looking a bit at the get_localized_key() function in  keys.py.

The key-lookup succeeds just fine, and returns the keyname `8` which matches the key that I pressed. The modifier flags are also set properly, so when I hit `shift + alt - 8` I receive the `8 down` event with modifier flags set to `5`. 

So I assume this is the case:
`mod_shift_flag = 0x1`
`mod_alt_flag =  0x100` 

I notice that there are special handling of events where the ctrl or alt modifier are combined with a key, and in my case we enter the "else" branch and `bytes(data)` returns empty

**Comment by kovidgoyal** [comment]
The problem is that get_localized_key() should return '{' not '8'. Probably because {} is missing from valid_localized_key_names. The other problem is that if shift+alt+8 is supposed to map to just a plain { then there needs to be some way to remove alt from the modifiers in this case. But I dont know of a api in glfw to do this. 

Basically, keyboard handling in glfw is fairly broken for any exotic setups (even the numlock key is not properly supported). See for example: https://github.com/glfw/glfw/issues/946

**Comment by koekeishiya** [comment]
Hmm I see. I'll take a look at how glfw performs their mapping towards MacOS and I should probably be able to patch it up from there.

Thanks for responding so quickly.

**Comment by koekeishiya** [comment]
So I was able to patch the glfw code so that I can properly write `[` and `]` (alt + 8, 9), but I don't see an `GLFW` key constant for `LEFT_BRACE` (`{`). Do you happen to know which keycode Kitty might expect glfw to return for this character?
