### ISSUE TITLE
Feature Request: Foreground opacity

### ISSUE THREAD

**Issue by v4u6h4n** [kovidgoyal/kitty#7403]
I would like to be able to render my foreground as transparent and my background as opaque, so the characters in my terminal inherit my background wallpaper in my window manager (which is an animated rainbow gradient which would hopefully look cool). I had a look through the docs and seems like only the background has an opacity setting.

**Comment by kovidgoyal** [comment]
I have no idea what that means. foreground is text. text is rendered
over a background. That backround can be either a solid color or
transparent. If you make the foreground transparent it mens you dont see
anything at all. If you want to make the entire window transparent you
do so via your window manager's configuration.
