### ISSUE TITLE
The output buffer does not support sRGB color encoding, colors will be incorrect.

### ISSUE THREAD

**Issue by JayaswalPrateek** [kovidgoyal/kitty#7409]
**Describe the bug**
every time a kitty instance is launched, this error is logged:
`[0.160] The output buffer does not support sRGB color encoding, colors will be incorrect.`

**To Reproduce**
1. open any terminal(kitty or gnome-console) regardless of the shell
2. run `kitty` to launch a new kitty instance
3. See error

**Environment details**
```
kitty 0.34.1 created by Kovid Goyal
Linux sus 6.8.8-cb1.0.lto.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Apr 29 12:43:24 UTC 2024 x86_64
S
Kernel 6.8.8-cb1.0.lto.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/prateek/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       yes
confirm_os_window_close    0
cursor_shape               2
cursor_stop_blinking_after 0
editor                     nano
enable_audio_bell          False
font_family                JetBrains Mono Nerd Font
font_size                  15.0
initial_window_height      (720, 'px')
initial_window_width       (1280, 'px')
input_delay                0
linux_display_server       x11
modify_font:
    cell_height 1
mouse_hide_wait            4.0
remember_window_size       False
repaint_delay              0
shell                      fish
sync_to_monitor            False
Colors:
	active_border_color        #89e234   
	active_tab_background      #ffffff   
	background                 #303030   
	bell_border_color          #ef2828   
	color1                     #ef2828   
	color10                    #89e234   
	color11                    #fbe84f   
	color12                    #729ecf   
	color13                    #ac7ea8   
	color14                    #34e2e2   
	color2                     #89e234   
	color3                     #fbe84f   
	color4                     #729ecf   
	color5                     #ac7ea8   
	color6                     #34e2e2   
	color7                     #d3d6cf   
	color8                     #545652   
	color9                     #ef2828   
	cursor                     #ffffff   
	cursor_text_color          #ffffff   
	foreground                 #ffffff   
	inactive_border_color      #545652   
	inactive_tab_background    #545652   
	inactive_tab_foreground    #d3d6cf   
	mark1_background           #34e2e2   
	mark3_background           #ac7ea8   
	selection_background       #545652   
	selection_foreground       #ffffff   
	url_color                  #34e2e2   

Important environment variables seen by the kitty process:
	PATH                                /home/prateek/.local/bin:/home/prateek/bin:/home/prateek/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/go/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /bin/bash
	DISPLAY                             :1
	USER                                prateek
	XDG_DATA_DIRS                       /home/prateek/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    x11
```

**Additional context**
reproducible with `kitty --config NONE`
I suppose this was exclusively a Nvidia+Wayland issue resolved by Nvidia upstream 550.60 drivers(see https://github.com/kovidgoyal/kitty/issues/7021), but here I am using X on fedora-gnome with 550.78 and still facing this issue. Is there a way I can suppress this till it gets resloved? It's been bugging some of the scripts that I use to spawn kitty instances.

**Comment by kovidgoyal** [comment]
Your GPU drivers dont support sRGB output colors, you need to fix them.

**Comment by JayaswalPrateek** [comment]
Is there a way to suppress the message by changing the debug/logging level from the config without having to recompile from the source?

**Comment by kovidgoyal** [comment]
kitty 2> /dev/null

**Comment by osbm** [comment]
> Your GPU drivers dont support sRGB output colors, you need to fix them.

Well, this comment has confused me, turns out it wasnt related to the gpu drivers (in my case at least).

Enabling HDR in both KDE display settings and monitor settings has resolved this issue for me.

**Comment by ninetailedtori** [comment]
Unsure why it won't work for me when enabling HDR output through aquamarine, rip

**Comment by firephreek** [comment]
> Your GPU drivers dont support sRGB output colors, you need to fix them.

Just a heads up: I encountered the same message when I ran `kitty themes` (per now understood and resolved erroneous advice) but doing so gave me a "Failed to launch child: theme With error: No such file or directory Press Enter or Esc to exit" and then on the terminal it told me my GPU drivers didn't support sRGB.

It's 2025 and I'm running a Nvidia 4070 with the latest drivers. I *definitely* have sRGB support (double verified) so there's a problem here and it's not likely people's GPU's.   That kind of dismissive response though does make think Kitty might not be for me.

**Comment by kovidgoyal** [comment]
Then get your drivers to correctly report that they support sRGB via the OpenGL API. This kind of poorly thought out complaint makes me strongly encourage you to not use kitty as you are clearly someone that will waste my precious time.

I'll leave this thread with a link to the code:
https://github.com/kovidgoyal/kitty/blob/master/kitty/glfw.c#L1491

That error message is printed when OpenGL says the output encoding is not sRGB. So again despite your "surety" that your drivers support sRGB, which seems to be based on nothing more than the date, either they dont, or they don't report it to OpenGL.
