### ISSUE TITLE
Move tabs by dragging

### ISSUE THREAD

**Issue by gvlassis** [kovidgoyal/kitty#7410]
Hello!

I am on Kitty 0.34.1 (macOS), and I cannot move tabs by dragging them with the mouse. I wanted to confirm that this is intended behaviour and not a bug.

In either case, is there any way I can fix this?

**Comment by kovidgoyal** [comment]
Yes there is no support for this, if you want it you are welcome to send
a PR implementing it, but its not something I care about.

**Comment by specious** [comment]
Is there any way whatsoever to rearrange the tab order?

**Comment by kovidgoyal** [comment]
On Thu, May 15, 2025 at 11:33:07PM -0700, Ildar Sagdejev wrote:
> specious left a comment (kovidgoyal/kitty#7410)
>
> Is there any way whatsoever to rearrange the tab order?

https://sw.kovidgoyal.net/kitty/actions/#action-move_tab_backward
