### ISSUE TITLE
Backspace performs incorrectly in SSH connections

### ISSUE THREAD

**Issue by 120L021026** [kovidgoyal/kitty#7418]
**Describe the bug**
After successfully connecting to SSH, if I backspace when modifying input commands, it will cause the backspace to appear on the command line in a way that looks like a space. Although entering the correct number of backscatters can actually remove the characters I want to delete, it doesn't seem like that.
For example, if "clera" is entered after SSH connection, I want to delete the last "ra", so I will backspace twice. However, at this point, Kitty will display "clera  ", but the actual effect is "cle". If I continue to input "ar" at this time, the kitty will display "clera  ar", which can correctly execute the "clear" command.

**To Reproduce**
1. Execute SSH command:` admin@Debian:~$ ssh abcd@1.1.1.1 `;
2. Do not exit the SSH connection, enter some letters and then enter backspace:` abcd@efg:~$ abc[BackSpace][BackSpace] `。

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Linux Debian 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64
Debian GNU/Linux 12 Debian /dev/tty

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
bold_font             Victor Mono Bold
font_family           Victor Mono Medium
font_size             12.0
italic_font           Victor Mono Italic
shell                 /usr/local/bin/elvish
tab_bar_min_tabs      1
tab_bar_style         powerline
tab_powerline_style   slanted
tab_title_template    {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
update_check_interval 0.0
Colors:
        background            #303446   
        foreground            #c6d0f5   

Important environment variables seen by the kitty process:
        PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
        LANG                                zh_CN.UTF-8
        SHELL                               /bin/bash
        GLFW_IM_MODULE                      ibus
        DISPLAY                             :1
```

**Comment by kovidgoyal** [comment]
Search the kitty FAQ for ssh.
