### ISSUE TITLE
Kitty dropping characters on fast input

### ISSUE THREAD

**Issue by dezfx** [kovidgoyal/kitty#742]
Typing fast or using external char input (in my case a yubikey) drops characters.

Linux, local build @ d72098bdf82fee8a788aa1b59d9c162545b7606e
This issue was introduced relatively recently, I think.

**Comment by dezfx** [comment]
Test: ran with --debug-keyboard, typed 'git', expected 'git', got 'gt'

Debug output:
Connecting to IBUS daemon @ unix:abstract=/tmp/dbus-D90XgO3R,guid=1c463e39515108e7cdc37e515b574fec for IME input management
Connected to IBUS daemon for IME input management
Press scancode: 0x2a clean_sym: g composed_sym: g text: g mods: none glfw_key: G xkb_key_name: g
↳ to IBUS: keycode: 0x22 keysym: 0x67 (g) mods: none 
IBUS processed scancode: 0x2a release: 0 handled: 0
From IBUS: scancode: 0x2a name: g is_release: 0
↳ to application
Press scancode: 0x1f clean_sym: i composed_sym: i text: i mods: none glfw_key: I xkb_key_name: i
↳ to IBUS: keycode: 0x17 keysym: 0x69 (i) mods: none 
Release scancode: 0x2a clean_sym: g mods: none glfw_key: G xkb_key_name: g
↳ to IBUS: keycode: 0x22 keysym: 0x67 (g) mods: none 
IBUS processed scancode: 0x1f release: 0 handled: 0
From IBUS: scancode: 0x1f name: i is_release: 0
↳ to application
IBUS processed scancode: 0x2a release: 1 handled: 0
From IBUS: scancode: 0x2a name: g is_release: 1
↳ to application
Release scancode: 0x1f clean_sym: i mods: none glfw_key: I xkb_key_name: i
↳ to IBUS: keycode: 0x17 keysym: 0x69 (i) mods: none 
Press scancode: 0x1c clean_sym: t composed_sym: t text: t mods: none glfw_key: T xkb_key_name: t
↳ to IBUS: keycode: 0x14 keysym: 0x74 (t) mods: none 
IBUS processed scancode: 0x1f release: 1 handled: 0
From IBUS: scancode: 0x1f name: i is_release: 1
↳ to application
IBUS processed scancode: 0x1c release: 0 handled: 0
From IBUS: scancode: 0x1c name: t is_release: 0
↳ to application
Release scancode: 0x1c clean_sym: t mods: none glfw_key: T xkb_key_name: t
↳ to IBUS: keycode: 0x14 keysym: 0x74 (t) mods: none 
IBUS processed scancode: 0x1c release: 1 handled: 0
From IBUS: scancode: 0x1c name: t is_release: 1
↳ to application

**Comment by kovidgoyal** [comment]
I just pushed a commit that shoud provide even more debug output with --debug-keyboard post the output from that.

**Comment by dezfx** [comment]
GLFW_IM_MODULE=none kitty addresses the issue. Let me grab that debug output.

**Comment by dezfx** [comment]
Having trouble getting a repro without a full yubikey hit. I have ligblfw3-wayland installed with libibus-1.0-5. Not sure specifically what downstream might be interesting.

**Comment by kovidgoyal** [comment]
Post the debug log with yubikey, it might still be interesting.

**Comment by kovidgoyal** [comment]
No followup, closing.
