### ISSUE TITLE
kitten hints add option for avoiding numeric characters in hints

### ISSUE THREAD

**Issue by itacud95** [kovidgoyal/kitty#7428]
**Is your feature request related to a problem? Please describe.**
I use this config for opening paths in vscode
```
map f3 kitten hints --type=path --program "vscodium -g -r"
```
But I find that I need to look down at keyboard for locating the numeric parts of the hints. I would like it to name/create the hints like the vimium chrome extension does. For example `AG`, `FL`, instead of the current solution, which has a number in front (`3f`). 

**Describe the solution you'd like**
Add a option for avoiding adding a number to the hints. 

**Additional context**
Here is a screenshot of how vimium does this: 
![image](https://github.com/kovidgoyal/kitty/assets/25989444/6b1edde0-3ae7-4bff-977b-dce1e20274a9)

Happy to help out, if you can point me in the direction of where the hints are created.

**Comment by kovidgoyal** [comment]
Use the --alphabet option to the hints kitten.

**Comment by tmccombs** [comment]
Yes, that works. But I would still like a single configuration that lets you set the default alphabet for _all_ hint invocations, instead of having to override it for every keybinding.

**Comment by kovidgoyal** [comment]
Use action_alias
