### ISSUE TITLE
Hints kitten not working as expected in Less

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#743]
In a pager such as less, trying to open a link with __ctrl+shift+e__ opens an emoji pop up window rather than opening the link in the browser.
~If this shortcut does not work in less is there an alternative way to open links?~ Never mind the second part, __ctrl+shift+left_click__ opens a link in the browser.

**Comment by kovidgoyal** [comment]
I cannot reproduce. Steps I tried:

1) less README.asciidoc
2) ctrl+shift+e 
3) The hints kitty starts in URL mode

I dont see how what program you are running could possibly affect which kitten starts, since keyboard shortcuts are implemented in kitty long before the keys are sent to the program.

**Comment by ChukwuemezieChristopherAneke** [comment]
@kovidgoyal I just checked and its actually the linux man page, which I assume uses less by default as all the keys work the same. For example: Opening the man page with `man realpath` and typing __ctrl+shift+e__ does not open a link in this pager.

**Comment by kovidgoyal** [comment]
Cannot reproduce, steps I tried:

1) Run ```MANPAGER=less man ls```
2) Press the end key to go to the bottom where there are some actual links
3) Press ctrl+shift+e
4) links are highlighted

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks for the hint, I realised that the __ctrl+shift+e__ shortcut was occupied by the gnome emoji choice app. I opened ibus-setup by typing `ibus-setup` in kitty, switched to the emoji tab in the pop up window, selected the tripple dot menu to the right of the emoji choice text box and then proceeded to delete this shortcut and replace it with a shortcut that is not being used.
