### ISSUE TITLE
How to spawn a remote shell?

### ISSUE THREAD

**Issue by MinatoTW** [kovidgoyal/kitty#7430]
Hello,

Is it possible to launch a kitty shell from a remote host? 

After I run `kitty +kitten ssh host` I would like to spawn a kitty shell from the `host` on my local machine and direct some output to it. I tried using the UNIX socket feature and SSH forwarding that socket but it doesn't seem to work.

Thank you.

**Comment by kovidgoyal** [comment]
Use remote control. It works fine.
https://sw.kovidgoyal.net/kitty/remote-control/
