### ISSUE TITLE
[FeatureRequest] Add a confirm config for close window when it has a running process

### ISSUE THREAD

**Issue by gutenye** [kovidgoyal/kitty#7434]
**Is your feature request related to a problem? Please describe.**

If you have a running process, then close kitty will show a confirmation.

<img width="692" alt="SCR-20240515-izgo" src="https://github.com/kovidgoyal/kitty/assets/377544/a550f077-8f52-43e4-bda6-6c1da0483485">

Kitty does not have a config key for this behavior.

Every day, when I close the app, I always have to press the extra Y button

**Describe the solution you'd like**

I want Kitty to add a new configuration key, like

```
confirm_running_os_window_close no
```

**Comment by kovidgoyal** [comment]
confirm_os_window_close 0

**Comment by gutenye** [comment]
Thanks. I knew the `-1` value for this key, but missed the `0` value.
