### ISSUE TITLE
Add option to specify a color for the scrollback indicator

### ISSUE THREAD

**Issue by jryom** [kovidgoyal/kitty#7435]
**Is your feature request related to a problem? Please describe.**
The scrollback indicator is really difficult to see.

**Describe the solution you'd like**
An option to specify a color for the scrollback indicator instead of just a setting for its opacity. The ability to also set its width would also help I guess.

**Additional context**
<img width="780" alt="Screenshot 2024-05-15 at 12 21 45" src="https://github.com/kovidgoyal/kitty/assets/2834949/df0b7463-35ed-47f2-9d50-13c3e3c90649">

**Comment by kovidgoyal** [comment]
The color is the same as whatever your highlight_foreground is set to.
Change that.

**Comment by mid-kid** [comment]
I have `selection_background none` because i want the colors to be inverted when selecting, but the scrollback indicator shows up black, and I want to change it independently.
