### ISSUE TITLE
kitty icat ImageMagick error

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#744]
I tried to view an image in kitty by typing the following but it didn't work.

```
$ kitty icat ~/Downloads/aws.png
Failed to convert image: /home/user/Downloads/aws.png with error: ImageMagick failed to convert /home/user/Downloads/aws.png correctly, it generated 4046840 < 4049820 of data
```
What does
>it generated 4046840 < 4049820 of data

mean and why did it fail?

**Comment by kovidgoyal** [comment]
It means imagemagick failed to convert the image to the correct number of bytes of raw rgb data. As for why it failed, I have no idea. Attach the image and I could probably tell you more.

**Comment by aaronduino** [comment]
Same issue. I cannot get any images to work

**Comment by aaronduino** [comment]
I think this could have to do with terminal window size

**Comment by kovidgoyal** [comment]
Window size has no bearing on this issue (except indirectly in that the size the image has oto be resized to depends on the window size). The question is why is imagemagick not converting the image to the correct number of bytes of RGB data.

**Comment by kovidgoyal** [comment]
See if https://github.com/kovidgoyal/kitty/commit/8d20dbe81ddabf0414dccd99d22e2fa55f4f5c37 helps

**Comment by aaronduino** [comment]
I mention window size because I only seem to get this error when the image
is larger than the window
