### ISSUE TITLE
 embedded: contains no embeddable files

### ISSUE THREAD

**Issue by arkhan** [kovidgoyal/kitty#7442]
**To Reproduce**
I try to compile this together with terminal kitty, but I get this error, I report it in Chroma's repo but apparently no problem https://github.com/alecthomas/chroma/issues/965:

``` sh
[118/119] Compiling kitty/simd-string-256.c ...
[119/119] Compiling kitty/gl-wrapper.c ...
 done
[1/5] Linking kitty/fast_data_types ...
[2/5] Linking [x11] kitty/glfw-x11 ...
[3/5] Linking [wayland] kitty/glfw-wayland ...
[4/5] Linking kittens/transfer/rsync ...
[5/5] Linking launcher ...
 done
../github.com/alecthomas/chroma/v2/lexers/lexers.go:10:12: pattern embedded: cannot embed directory embedded: contains no embeddable files
../github.com/alecthomas/chroma/v2/styles/api.go:11:12: pattern *.xml: cannot embed irregular file abap.xml
```

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/3141865/179ef984-830b-4c88-8a00-ba930f0703bb)

**Comment by kovidgoyal** [comment]
Sorry I have no clue why chroma is refusing to build, there's nothing
kitty specific in building chroma. If you cant figure it out I suggest
you use the kitty nightly builds instead if you need access to a
new feature.
