### ISSUE TITLE
Z-index/window stack order isssue on gnome + Arch 

### ISSUE THREAD

**Issue by drschwabe** [kovidgoyal/kitty#7445]
Kitty often loses its ability to be 'clicked' when its in the background where foreground windows are in front of it.   There's weird behavior where the other windows in foreground will toggle focus even when clicking the kitty background.    

The expected behavior is obviously when you click Kitty even if windows are in the foreground Kitty will appear above the stacking order.   

The workaround when this happens is to Alt-Tab directly to Kitty and then it has focus as expected.  
Or to close the Kitty window entirely and start a new one (until the issue occurs again) 

**To Reproduce**
1. use kitty for a while with a bunch of other windows like browser, a text edtitor, etc
2. eventually the aforementioned window bug starts happening 

It doesn't always happen and seems to be more prone to happening when i have a long running process that is spitting out lots of lines at once to stdout. 

It could also be a gnome bug but I only have this issue with Kitty so I decided to post the issue here first in my attempt to solve the issue. 

**Environment details**
```
kitty 0.32.2 (925043d645) created by Kovid Goyal
Linux orc16 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64
EndeavourOS Linux 6.7.9-arch1-1 (/dev/tty)

DISTRIB_ID="EndeavourOS"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME="rolling"
Running under: X11
```

**Comment by kovidgoyal** [comment]
There is no such thing as "ability to be clicked". kitty does not focus
itself when it is clicked, that is done by the window manager, so if
kitty is not getting focused on click the issue is in the window
manager.

Since you are running under X11, what happens is the x server sends a
client a "FocusIn" event to indicate to it it now has keyboard focus.

Note that you can see all keyboard and mouse events kitty receives from
the system by running it with --debug-input.

**Comment by drschwabe** [comment]
Ok thanks perhaps i'll look into the bug via gnome then and/or try a different desktop manager to split test the issue. 

The odd thing is that when this bug happens you can get kitty's focus back (ie- by alt tab) but it still cannot be clicked - it can only receive keyboard input - if you try clicking kitty the foreground windows unexpectedly appear where you click.

**Comment by kovidgoyal** [comment]
On Fri, May 17, 2024 at 08:25:59AM -0700, Derrick Schwabe wrote:
> Ok thanks perhaps i'll look into the bug via gnome then and/or try a different desktop manager to split test the issue.
>
> The odd thing is that when this bug happens you can get kitty's focus back (ie- by alt tab) but it still cannot be clicked - it can only receive keyboard input - if you try clicking kitty the foreground windows unexpectedly appear where you click.

This is again not something kitty can be doing. It cannot bring random
other windows into focus. Only the window manager can do that.
