### ISSUE TITLE
Option to add outline around text for readability with low opacity

### ISSUE THREAD

**Issue by jokesper** [kovidgoyal/kitty#7447]
**Is your feature request related to a problem? Please describe.**
Depending on what is on screen low opacity makes text hard to read

**Describe the solution you'd like**
An option to enable (possibly with a width) drawing an outline around
every character in a similar way to subtitles in anime.

**Describe alternatives you've considered**
Modifying a font to have an outline of a fixed color would be an option.
This would cause small issues when the color is close to the hard coded outline.

**Comment by kovidgoyal** [comment]
Not something I am interested in. Use higher opacity or background blur.
