### ISSUE TITLE
FR: Support overlay window with customized size and position parameters.

### ISSUE THREAD

**Issue by amosbird** [kovidgoyal/kitty#7450]
The overlay window is already one of the **unmatched** feature among other terminal emulators. It will be more powerful if it supports customized size and position parameters which partially overlays the underlying window. The covered window should still render updates when this partially covering overlay window is active.

The motivation is to build general popup widgets such as completion dialog at the position of current cursor.

Usually this is done by TUI applications themselves, such as https://github.com/nvim-telescope/telescope.nvim, https://github.com/helix-editor/helix, tmux floating popups, etc. However, being able to achieve this using `kitten @ launch` alone will be more general, which can help less capable TUI applications such as terminal emacs to do fancy stuff.

**Comment by kovidgoyal** [comment]
Yes, this is called floating windows, it's on my TODO list to build. It
wont be via remote control, it will be via escape codes so TUI programs
can use them and other terminal emulators can implement the spec, if
they want.  It requires designing a spec like the various other specs
for terminal protocol extensions kitty has.

Sadly, my TODO list stretches to the moon so I cant give you an ETA on
this.

If you want to get involved/do some work on it let me know and we can
discuss, otherwise you will need to wait till I find the time.

**Comment by amosbird** [comment]
Hmm, "floating windows" sounds like a more complex but slightly different feature which can also be used to achieve features like completion dialog. It will require TUI programs to extend their display code in core.

Overlay windows with customizable size and position, on the other hand, is more flexible. We can build any kinds of plugins using kitty remote control without recompilation of TUI programs. We can also use it to customize kitty's confirmation window so that it renders at the center of the current window.

> If you want to get involved/do some work on it let me know and we can discuss, otherwise you will need to wait till I find the time.

I don't have any experience of developing a terminal protocol spec. I guess for "floating windows" I'll have to wait. But for features like "overlay windows with customizable size and position", I think I can give it a try :)

**Comment by kovidgoyal** [comment]
On Sun, May 19, 2024 at 03:47:41AM -0700, Amos Bird wrote:
> Hmm, "floating windows" sounds like a more complex but slightly different feature which can also be used to achieve features like completion dialog. It will require TUI programs to extend their display code in core.

So will remote control unless you restrict remote control to being over
a socket only. And obviously just as you can control normal kitty
windows via remote control, you will be able to control floating ones as
well. The important part is having floating windows. Once you do, they
can be controlled in many different ways.

>
> Overlay windows with customizable size and position, on the other hand, is more flexible. We can build any kinds of plugins using kitty remote control without recompilation of TUI programs. We can also use it to customize kitty's confirmation window so that it renders at the center of the current window.

What configuration window? You mean to edit kitty.conf? It currently
covers the entire current window, why would you want to use less space
for it?

>
> > If you want to get involved/do some work on it let me know and we can discuss, otherwise you will need to wait till I find the time.
>
> I don't have any experience of developing a terminal protocol spec. I guess for "floating windows" I'll have to wait. But for features like "overlay windows with customizable size and position", I think I can give it a try :)

You are welcome to try, I see no harm in it. Just be aware that whatever
internal infrastructure is created for it needs to be flexible enough to
use for floating windows in the future. So I will likely have lots of
nit picking to do over it.

**Comment by amosbird** [comment]
> So will remote control unless you restrict remote control to being over a socket only. 

It's slightly different. The window created by `kitten @ launch --type=overlay` uses another tty, which allows to render anything freely. TUI programs can be totally unaware of its existence. Remote control is only used to spawn this overlay.

> What configuration window? why would you want to use less space for it?

I mean the confirmation dialog. Here is an illustration of what I have in mind.

![copied-2024-05-19-20_58_35_792](https://github.com/kovidgoyal/kitty/assets/5085485/76a12bfe-758d-4c95-922d-af5a3550b12f)

**Comment by kovidgoyal** [comment]
On Sun, May 19, 2024 at 05:59:35AM -0700, Amos Bird wrote:
> > So will remote control unless you restrict remote control to being over a socket only.
>
> It's slightly different. The window created by `kitten @ launch --type=overlay` uses another tty, which allows to render anything freely. TUI programs can be totally unaware of its existence. Remote control is only used to spawn this overlay.

Yes, but then you cant really integrate with the TUI program at all.
Your window will steal focus from the main window and note that there is
no mechanism in kitty to transfer focus between an overlay and the
window beneath it.

>
> > What configuration window? why would you want to use less space for it?
>
> I mean the confirmation dialog. Here is an illustration of what I have in mind.

Isnt that already centered? Or you mean you want it to just cover a part
of the window beneath it? In that case you are going to have a bit of
trouble with sizing, since if you make it too small the text/buttons get
messed up.

**Comment by amosbird** [comment]
> Yes, but then you cant really integrate with the TUI program at all. Your window will steal focus from the main window 

Even though we can only focus on the overlay window, there will still be some opportunities to integrate. For example, we can build a fuzzy searcher which takes the input keyword under the cursor and spawn a small dialog window at the right place doing arbitrary searching. It's better than consuming the entire window area for such dialog.

> Or you mean you want it to just cover a part of the window beneath it? 

Exactly! And the window beneath it will still render actively (e.g. a running `top` program in the background)

**Comment by kovidgoyal** [comment]
On Sun, May 19, 2024 at 06:59:13AM -0700, Amos Bird wrote:
> > Yes, but then you cant really integrate with the TUI program at all. Your window will steal focus from the main window
>
> Even though we can only focus on the overlay window, there will still be some opportunities to integrate. For example, we can build a fuzzy searcher which takes the input keyword under the cursor and spawn a small dialog window at the right place doing arbitrary searching. It's better than consuming the entire window area for such dialog.

I dont really see the usecase. If you are searching for something, then
presumably you want to search, why would you restrict the available
screen real estate in which to perform that search? Maybe at best you
can have a border and a little bit of background cause it looks nice, I
dont know.

Typically, floating/popup windows are used to display some small snippet
of information such as a tooltip or completion candidates or
similar. Modal activities by definition take focus and thus deserve the
full available space.

That said, just because I dont see a valid usecase doesnt mean there
isnt one, and you are free to implement this, since the infrastructure
will come in handy later for floating windows it works for me as well.

>
> > Or you mean you want it to just cover a part of the window beneath it?
>
> Exactly! And the window beneath it will still render actively (e.g. a running `top` program in the background)

But its a confirmation dialog. Why would you want to leave it on screen
obscuring a part of top running under it?

**Comment by amosbird** [comment]
>  If you are searching for something, then presumably you want to search, why would you restrict the available screen real estate in which to perform that search?

Because a full screen search dialog is too distracting :)  I'm thinking something like https://github.com/davatorium/rofi

> But its a confirmation dialog. Why would you want to leave it on screen obscuring a part of top running under it?

Agree. This example doesn't make much sense. It is meant to be distracting (grab user's full attention)

**Comment by kovidgoyal** [comment]
On Sun, May 19, 2024 at 08:51:50AM -0700, Amos Bird wrote:
> >  If you are searching for something, then presumably you want to search, why would you restrict the available screen real estate in which to perform that search?
>
> Because a full screen search dialog is too distracting :)  I'm thinking something like https://github.com/davatorium/rofi

Well, I always wished rofi would go full screen and present me with more
information :) But as I said, sure, go for it, I dont mind as it has
side benefit for me.

**Comment by visrosa** [comment]
@amosbird I've been trying to kludge together a popup for the fzf completion menu using os-window. It's not good and not general purpose, and should probably be a kitten, but might give you some ideas? [Here's the code I'm using](https://github.com/visrosa/kitty-popup)  and here's a badly cropped screenshot of the completion menu open in another os-window:

![Badly cropped screenshot](https://github.com/user-attachments/assets/daef96d6-0710-49bb-8937-89689eebdcc8) 

 




As for @kovidgoyal plans, I love the idea of a spec other people can implement/support. Hope it happens sometime.

That said, just being able to set the overlay window size seems easier to tackle and fits the usecases where stealing focus is desirable. Too bad I don't know programming well enough to try my hand implementing it.

**Comment by brandon-fryslie** [comment]
> I dont really see the usecase. If you are searching for something, then
> presumably you want to search, why would you restrict the available
> screen real estate in which to perform that search? 

If you're searching, it would be convenient to show the text you're searching through without opening a completely separate buffer.  For example, your web browser likely has a search function.  It likely shows a small UI element with a text field and a button or two

I was hoping something similar would be possible in Kitty.  I suppose the existence of this issue and that it's closed means Kitty cannot do this.  I was hoping overlays could achieve this, but it seems like they're just another full screen buffer as well.  A layout seems like it might be the best option, but I'd be very grateful if there are other ideas.

**Comment by kovidgoyal** [comment]
Umm sorry dont follow. If you want to search the buffer contents, open it in a pager or editor using the facilities present in kitty, then your search input is a single line at the bottom like yousay you want. That has nothing to do with floating overlays.

**Comment by Thesola10** [comment]
> Or you mean you want it to just cover a part of the window beneath it?

I think I have a usecase for a smaller-sized popup window: `$EDITOR` for Git commits, which would allow you to still see the repository (or host TUI program) while editing the commit message for context.

Is there a way to use `kitten @ launch --type=overlay` to achieve this like `tmux popup` can?
