### ISSUE TITLE
Unicode character picker does not work like gtk ctr+shif+u

### ISSUE THREAD

**Issue by leiserfg** [kovidgoyal/kitty#7451]
**Describe the bug**

I'm using a [kmk](https://kmkfw.io/) in my keyboard and with it I can bind keys sequences to a single key press, using that and `ctr+shift+u` I can enter unicode characters in gtk based apps. But when I do the same in kitty, sometimes it does not work, I think it's because the keyboard is "pressing" enter before the kitten is done showing the match or processing it.
I would like if the kitten didn't even show if the keypresses came very quick, cause right now besides that it's not working as expected  it also blinks (cause it's  opening and closing very quickly).

Thanks in advance.

**Comment by kovidgoyal** [comment]
The kitten opens in a few milliseconds (2-3 ms), I highly doubt you type faster
than that. If you do, I'm afraid there is nothing that can be done, I
know of no way to make the kitten open faster than that, if you do, then
patches are most welcome.
