### ISSUE TITLE
feat: cheap as possible NOP remote control command to just check if that window still exists

### ISSUE THREAD

**Issue by IndianBoy42** [kovidgoyal/kitty#7452]
**Is your feature request related to a problem? Please describe.**
I am using the kitty remote control protocol to control kitty windows from inside neovim. But I need to detect if the kitty window was closed from the outside and potentially relaunch it. I'm not sure what command I can use that wouldn't affect anything and doesn't incur unnecessary computation (like using ls)

**Describe the solution you'd like**
`kitten @ exists --match` simply checks if the given match arguments finds any existing window, signalling success/failure through the exit code 

**Describe alternatives you've considered**
`ls` could work but still does slightly more work than absolutely necessary

**Comment by kovidgoyal** [comment]
I wouldnt worry about the overhead of ls, it's just serializing a few
existing fields into JSON. Indeed doing the matching will probably cost
more than that. Use ls --match id:$WINDOW_ID to restrict ls to just a
single window to minimize even that.

**Comment by IndianBoy42** [comment]
Alright sure, sounds good
