### ISSUE TITLE
selection doesn't update when scrolling via the scroll wheel.

### ISSUE THREAD

**Issue by lolbinarycat** [kovidgoyal/kitty#7453]
1. run `yes` to fill up the scrollback buffer
2. hold mouse1
3. scroll up without moving your mouse

here's an untested patch i guess.  i was going to submit a PR properly, but i couldn't wrap my head around the 3 different build systems.  also i don't really trust software that's still using openssl 1.1
```diff
diff --git a/kitty/mouse.c b/kitty/mouse.c
index 792403d..46cd734 100644
--- a/kitty/mouse.c
+++ b/kitty/mouse.c
@@ -980,7 +980,7 @@ scroll_event(double xoffset, double yoffset, int flags, int modifiers) {
             }
         }
     }
-
+    update_drag(w);
 }
 
 static PyObject*
```

**Comment by kovidgoyal** [comment]
On Sun, May 19, 2024 at 08:02:06PM -0700, lolbinarycat wrote:
> Steps to reproduce the behavior:
> 1. run `yes` to fill up the scrollback buffer
> 2. hold mouse1
> 3. scroll up without moving your mouse
>
> here's an untested patch i guess.  i was going to submit a PR properly, but i couldn't wrap my head around the 3 different build systems.

I guess

./dev.sh build

is too hard for you.

> also i don't really trust software that's still using openssl 1.1

Then please do me a favor and stop using kitty.

**Comment by lolbinarycat** [comment]
> I guess
> ./dev.sh build
> is too hard for you.

wowee, definatly didn't try that 5 times already!

also how is this closed as completed??? you have done nothing to address the bug itself.

> Then please do me a favor and stop using kitty.

already switching to alacritty, which doesn't have this bug btw.

**Comment by kovidgoyal** [comment]
On Sun, May 19, 2024 at 08:43:04PM -0700, lolbinarycat wrote:
> already switching to alacritty, which doesn't have this bug btw.

Yay!!
