### ISSUE TITLE
Tab Bar Does Not Immediately Redraw After Keyboard Mode Change

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#7455]
**Describe the bug**

The tab bar does not redraw immediately after switching keyboard modes. It only redraws after a key is pressed.

**To Reproduce**

1. Launch kitty using this shell script:
    ```sh
    #!/bin/bash
    for i in {1..9}; do
      set -- -o "map --mode gt $i goto_tab $i" "$@"
    done
    kitty --config NONE \
      -o tab_bar_min_tabs=1 \
      -o "map --new-mode gt --on-unknown end kitty_mod+g" \
      -o "map --mode gt esc pop_keyboard_mode" \
      -o "tab_title_template={sup.index if keyboard_mode == 'gt' else ' '}{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}" \
      "$@"
    ```

2. Open a few tabs using `kitty_mod+t`:

3. Switch to the new keyboard mode using `kitty_mod+g`:

**Observed error**

Notice that the tab indices do not show within the tab bar until the user presses a key, such as 1, to get the tab bar to redraw. Similarly, when exiting the keyboard mode, the indices do not hide until after the user presses the left or right arrow keys to cause the tab bar to redraw.

I would expect the tab bar to redraw as soon as the keyboard mode changes, as the `tab_title_template` depends on the `keyboard_mode`.

**Environment details**
```
kitty 0.34.1 (7f61f1f9f3) created by Kovid Goyal
Linux byteevo 5.15.0-107-generic #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024 x86_64
Ubuntu 20.04.6 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  tab_bar_min_tabs 1
  map --new-mode gt --on-unknown end kitty_mod+g
  map --mode gt esc pop_keyboard_mode
  tab_title_template {sup.index if keyboard_mode == 'gt' else ' '}{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}
  map --mode gt 9 goto_tab 9
  map --mode gt 8 goto_tab 8
  map --mode gt 7 goto_tab 7
  map --mode gt 6 goto_tab 6
  map --mode gt 5 goto_tab 5
  map --mode gt 4 goto_tab 4
  map --mode gt 3 goto_tab 3
  map --mode gt 2 goto_tab 2
  map --mode gt 1 goto_tab 1

Config options different from defaults:
tab_bar_min_tabs   1
tab_title_template {sup.index if keyboard_mode == 'gt' else ' '}{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}
Changed shortcuts:
	kitty_mod+g →  push_keyboard_mode gt
Changes in keyboard mode: gt
Added shortcuts:
	1 →  goto_tab 1
	2 →  goto_tab 2
	3 →  goto_tab 3
	4 →  goto_tab 4
	5 →  goto_tab 5
	6 →  goto_tab 6
	7 →  goto_tab 7
	8 →  goto_tab 8
	9 →  goto_tab 9
	escape →  pop_keyboard_mode

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.local/lib/precor:/home/precor/.local/bin:/home/precor/.local/node/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/Android/Sdk/build-tools/34.0.0:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Comment by salmankhilji** [comment]
This is not quite fixed yet.

This bug still reproduces when the keyboard mode ends due to an unknown key.

With this:

```
map --new-mode gt --on-action end --on-unknown end kitty_mod+g
```

press an unknown key and have the keyboard mode pop. The tab bar still does not redraw.

Tested with kitty built from source as there was no nightly for some reason.

P.S:  Are nightly builds automatically produced?

**Comment by kovidgoyal** [comment]
On Tue, May 21, 2024 at 02:04:05AM -0700, salmankhilji wrote:
> This is not quite fixed yet.
>
> This bug still reproduces when the keyboard mode ends due to an unknown key.
>
> With this:
>
> ```
> map --new-mode gt --on-action end --on-unknown end kitty_mod+g
> ```
>
> press an unknown key and have the keyboard mode pop. The tab bar still does not redraw.

https://github.com/kovidgoyal/kitty/commit/95c44cac01f4494781051332de27069fe0a08454

>
> Tested with kitty built from source as there was no nightly for some reason.
>
> P.S:  Are nightly builds automatically produced?

Yes, obviously I am not waking up every night to produce them. But they
do sometimes fail, depending on the state of master.

**Comment by salmankhilji** [comment]
Works now.  Thanks :)
