### ISSUE TITLE
List processes that are keeping a tab open when a close is requested

### ISSUE THREAD

**Issue by NeilGirdhar** [kovidgoyal/kitty#7456]
**Is your feature request related to a problem? Please describe.**
https://github.com/kovidgoyal/kitty/issues/6158 explains how a request to close a tab can remain pending if child processes remain open.

**Describe the solution you'd like**
After ctrl-d, if there are open child processes, please print the process ID and task name.  This way, the task can be closed from another tab if necessary.

Thus, we would have something like:
```
> [ctrl-d]
Tab is being kept open by the following tasks:
PID      Task name
2312    /usr/bin/rg
1231    nvim
```
**Describe alternatives you've considered**
I've considered setting `[close_on_child_death](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.close_on_child_death)` to `yes`, but this will leave the child processes running?

**Comment by kovidgoyal** [comment]
dup of #7331

**Comment by NeilGirdhar** [comment]
@kovidgoyal Sorry for the duplicate, and so happy to see you've already implemented this!!
