### ISSUE TITLE
Cannot chang input method,get erro: [glfw error 65544]: Failed to open IBUS address file

### ISSUE THREAD

**Issue by DeccanLin** [kovidgoyal/kitty#7459]
**Describe the bug**
Run 'GLFW_IM_MODULE=ibus kitty' inside ubuntu 22.04 docker, then get error *[glfw error 65544]: Failed to open IBUS address file: : /home/xxxx/.config/ibus/bus/ecafc056f12e4be194b5167157d65060-unix-0 with error: No such file or directory*

**To Reproduce**
1. Run docker: `docker run -it -e NVIDIA_DRIVER_CAPABILITIES=all -e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v $HOME/.Xauthority:/root/.Xauthority ubuntu:jammy /bin/bash`
2. Install tool and install kitty: `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n  && sudo ln -s ~/.local/kitty.app/bin/kitty /usr/local/bin/`
3. launch kitty: `GLFW_IM_MODULE=ibus kitty`

**Comment by kovidgoyal** [comment]
The error message is quite clear you are missing the IBUS socket in your
environment. Fix that and you will be fine.

**Comment by DeccanLin** [comment]
In Docker, wezterm can directly use the host's input method without the need to install separate tools like ibus. I'm not quite sure about the underlying implementation. Does kitty have a similar configuration option to enable this feature?

**Comment by kovidgoyal** [comment]
There is no way anything can use ibus unless its socket is available.
You are probably running kitty under X11 and wezterm under wayland. In
wayland IME works over the wayland socket not a separate socket.
