### ISSUE TITLE
Using kittens without completely installing kitty

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#746]
Is it possible to use a kitten without fully installing kitty and all of its dependancies? I'd like to use the icat kitten on a headless linux machine without installing seemingly unnecessary dependencies like harfbuzz.

**Comment by kovidgoyal** [comment]
Use the pre-built linux binaries, they come with harfbuzz included.

**Comment by Luflosi** [comment]
Well, the headless linux machine is a Raspberry Pi and there are no pre-built binaries for arm.

**Comment by kovidgoyal** [comment]
In that case I'm afraid you cannot avoid installing harfbuzz.

**Comment by Luflosi** [comment]
Ok, thanks anyways.
