### ISSUE TITLE
kitty: error while loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory how to fix in garuda linux

### ISSUE THREAD

**Issue by Thecode764** [kovidgoyal/kitty#7461]
Hi i installed kitty on garuda linux
my error
kitty: error while loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory

**Comment by kovidgoyal** [comment]
Use the official kitty binaries that come with their own python. https://sw.kovidgoyal.net/kitty/binary/

**Comment by Thecode764** [comment]
thank you
@kovidgoyal
