### ISSUE TITLE
Inconsistent background_opacity 

### ISSUE THREAD

**Issue by Trial97** [kovidgoyal/kitty#7463]
**Describe the bug**
You can set the `background_opacity 0.0` if you try to use a command like `map kitty_mod+a>0 set_background_opacity 0.0`  it will set it to 0.1

**To Reproduce**
1. Enable and set `background_opacity` to 0.0
2. Add a command that sets the background opacity:
```
map kitty_mod+a>0 set_background_opacity 0.0
map kitty_mod+a>d set_background_opacity default
```
3. Press key combination 
4. The terminal background changes( I expect to not or at least to not let me set the opacity to 0 from the first try)

**Screenshots**
Kitty just opened(with opacity 0):
![image](https://github.com/kovidgoyal/kitty/assets/42720688/95d18400-3b64-483c-be1f-8edfd3d3a893)
Kitty after I press the combination of keys:
![image](https://github.com/kovidgoyal/kitty/assets/42720688/99cbca9b-0f64-4c42-8155-ac20d2dbc623)

**Environment details**
```
kitty 0.33.1 created by Kovid Goyal
Linux Clockwork 6.6.31-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat May 18 01:27:42 UTC 2024 x86_64
Manjaro Linux 6.6.31-1-MANJARO  (Clockwork) (/dev/tty)


DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="24.0.0"
DISTRIB_CODENAME="Wynsdey"
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/trial/.config/kitty/kitty_bug.conf

Config options different from defaults:
background_opacity         0
dynamic_background_opacity True
Changed shortcuts:
	kitty_mod+a > m →  set_background_opacity default, set_background_opacity 0.0, set_background_opacity 1, set_background_opacity -0.1, set_background_opacity +0.1

Important environment variables seen by the kitty process:
	LANG                                en_US.utf8
	EDITOR                              nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 awesome
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
```

**Additional context**
Basic config used:
```
dynamic_background_opacity yes
background_opacity 0.0

map kitty_mod+a>d set_background_opacity 0.0
map kitty_mod+a>0 set_background_opacity default
```
Is there a reason that when dynamically setting the opacity the minimum is set to 0.1?

**Comment by Trial97** [comment]
Not sure if this is intentional: https://github.com/kovidgoyal/kitty/blob/84989646132837815f7260b0f50f3860765d1cbb/tools/cmd/at/set_background_opacity.go#L12-L14 here you are still setting the minimum to 0.1 for some opacity stuff

**Comment by kovidgoyal** [comment]
Yeah thanks, forgot that one.
