### ISSUE TITLE
detach_window enhancements

### ISSUE THREAD

**Issue by gknittl** [kovidgoyal/kitty#7468]
Kitty is so functional it constantly opens up possibilities for new function that I would have never dreamed when I used Gnome Terminal...

**Is your feature request related to a problem? Please describe.**
While working in a Kitty OS Window with 10 tabs over days or weeks, open kitty windows accumulate with long running processes, or with terminal command sequences that I'm not using but that I want to come back to later. I don't want to close them, but I don't want them to take up space on the screen either.

detach_window ask is perfect for this. I've reached the limits of key combinations that I can remember and that don't conflict with kakoune so kitten @ action detach_window ask is even better to move windows I don't want to look at to a "parking" tab. The "problem" is that I already know that I want to send the kitty window to the "parking" tab but have to specify this interactively under the ask option.

**Describe the solution you'd like**
kitten @ action detach_window to support --match option (for tabs). For those that prefer to attach actions to key bindings perhaps the underlying key binding could also support --match 
This has the advantage that I can name the "parking" tab "parking" and then use --match title:parking in my remote control script

Another solution would be to allow "minimizing" windows so they take up no/minimal space on the screen but remain in the current tab. It seems to me this could create changes to multiple other commands such as moving between windows, requires a command to restore minimized windows, kitten @ ls to note if window is minimized etc so I completely understand not wanting to implement this. 

Additionally it would be nice to have a detach_windows option to remain in the current tab instead of focus shifting to the "parking" tab

**Describe alternatives you've considered**
I can usually set up long running processes to log to file and then notify when complete which avoids the need to park them. However, it can take me a while to get around to this so it's nice to have a workaround in Kitty while I'm fine tuning the workflow.
Logging every command output #5713 https://github.com/kovidgoyal/kitty/discussions/5713. This might partly cover the scenario where I'm trying to preserve terminal commands as opposed to a long running process.
Kitty/shell is so rich in function that there are probably more alternatives that I haven't thought of. 

**Additional context**
thanks again for Kitty

**Comment by gknittl** [comment]
another alternative might be a "minimise" option for the resize_window action

**Comment by gknittl** [comment]
thanks! 
the only micro enhancement left would be a detach-windows option to remain in the current tab...

**Comment by gknittl** [comment]
No response required.

For those reading this later

since we are already scripting it's easy to 
-capture the current tab title using jq (JSON query)
- park it
-  come back to current tab

curtab=$(kitty @ ls -t recent:0 |jq -r '.[].tabs[].title'); kitten @ detach-window -t title:parking;kitten @ focus-tab -m title:"$curtab"

Also kitten @ get-text could be another way to preserve terminal commands to file without parking the terminal.

**Comment by kovidgoyal** [comment]
Dont use tab title, use ids they are guaranteed to be unique. Or use the --stay-in-tab flag my commit added.
