### ISSUE TITLE
Questions about modal map best practices

### ISSUE THREAD

**Issue by b02860de585071a2** [kovidgoyal/kitty#7470]
This is a stupid question, but is there anything "wrong" with mapping the same key to both a modal map AND an action inside that mode?

Example: I want to create a `resizing` mode which calls `start_resizing_window` with additional keybinds (very similar to https://github.com/kovidgoyal/kitty/issues/7334). I want `alt+r` to trigger this, and `esc` to exit. 

This is how I've set up my config file:
```
map --new-mode resizing alt+r
map alt+r combine : push_keyboard_mode resizing : start_resizing_window
map --mode resizing h resize_window wider
map --mode resizing l resize_window narrower
map --mode resizing k resize_window taller
map --mode resizing j resize_window shorter
map --mode resizing esc combine : pop_keyboard_mode : send_key esc
```

This simple example works fine, but I have a couple questions:

1. Is it "safe" to map `<key>` to `--new-mode <mode>` + an action inside that same mode? Could this introduce unwanted side effects?
2. Is there a better way to accomplish this? I feel like it *should* be doable with something like `map <key> combine : new_mode <mode> : push_keyboard_mode <mode> : <action>` (ie declaring the mode without an explicit keybind). I've looked through documentation and haven't seen anything to clarify/support this.

**Comment by kovidgoyal** [comment]
On Thu, May 23, 2024 at 04:11:34PM -0700, b02860de585071a2 wrote:
> This is a stupid question, but is there anything "wrong" with mapping the same key to both a modal map AND an action inside that mode?
>
> Example: I want to create a `resizing` mode which calls `start_resizing_window` with additional keybinds (very similar to https://github.com/kovidgoyal/kitty/issues/7334). I want `alt+r` to trigger this, and `esc` to exit.
>
> This is how I've set up my config file:
> ```
> map --new-mode resizing alt+r
> map alt+r combine : push_keyboard_mode resizing : start_resizing_window
> map --mode resizing h resize_window wider
> map --mode resizing l resize_window narrower
> map --mode resizing k resize_window taller
> map --mode resizing j resize_window shorter
> map --mode resizing esc combine : pop_keyboard_mode : send_key esc
> ```
>
>
> This simple example works fine, but I have a couple questions:
>
> 1. Is it "safe" to map `<key>` to `--new-mode <mode>` + an action inside that same mode? Could this introduce unwanted side effects?

combine simply runs the actions one by one. map is not an action so you
cannot run it inside combine.

> 2. Is there a better way to accomplish this? I feel like it *should* be doable with something like `map <key> combine : new_mode <mode> : push_keyboard_mode <mode> : <action>` (ie declaring the mode without an explicit keybind). I've looked through documentation and haven't seen anything to clarify/support this.

No, there is no action named new_mode. map literally creates a mapping
of key events to actions. There can be modal maps. These all are created
*once* when kitty.conf is read. You cannot create/modify maps inside
actions (well technically you can using the remote_control load_config
action to override mappings but it wont help you since you cannot
declare a mode without a keybind).

If you are concerned about "wasting" keybinds simply use a key that
doesn't exist on your keyboard, like for example a unicode character or
the F13 key or whatever.

**Comment by b02860de585071a2** [comment]
> You cannot create/modify maps inside actions (well technically you can using the remote_control load_config action to override mappings but it wont help you since you cannot declare a mode without a keybind). 

> If you are concerned about "wasting" keybinds simply use a key that doesn't exist on your keyboard [...]

I think I'm using the term "action" incorrectly. I was referring to using the same key for both:
1. a mode 
2. \<something else\>


eg:

```
map --new-mode <mode> key1
map key1 <another_thing>
```

That answers my questions, thank you!
