### ISSUE TITLE
Multiplayer / session sharing

### ISSUE THREAD

**Issue by camelpunch** [kovidgoyal/kitty#7472]
I'd like to replace tmux for remote pair programming. Is this feasible with Kitty remote control?

Ideally it'd work like `tmux attach`, where any number of users can watch and interact with the session.

If it doesn't already exist I'd be willing to take it on as a project.

**Comment by kovidgoyal** [comment]
Anything is feasible, but if you really want multiple people writing to
the same tty device at the same time there's no way to make that robust.
In any case all you need to do is export the remote control socket to
all your users, using some kind of port forwarding mechanism, see for
example how the socket is optionally forwarded by the ssh kitten. After
that they can use @ get-text to get the screen contents and @ send-key
to send key events. You will need to write a wrapper program that
facilitates that usage by running a pty and forwarding their input via
remote control @ send-key and updating their screens via @ get-text.

**Comment by camelpunch** [comment]
Thanks! Yeah the 80% case is watching one person's terminal, and then switching who 'drives'. I'll give it a whirl.
