### ISSUE TITLE
Yabai not handling kitty's windows

### ISSUE THREAD

**Issue by Meaticus22** [kovidgoyal/kitty#7473]
I'm seeking assistance on regarding an issue I've encountered with shortcuts with skhd when managing kitty terminal windows. Specifically, whenever I attempt to use a shortcut configured through skhd to handle a kitty window, I experience a glitchy red effect. However, when applying the same shortcut to manage a Firefox window, everything functions smoothly without any issues. Could anyone provide guidance on how to integrate yabai with kitty's windows using the alt+shift+right command shortcut via skhd? For a clearer understanding of the problem, please refer to this video demonstration: https://streamable.com/stad8m

Dotfiles: https://github.com/Meaticus22/dotfiles/tree/main

**Comment by kovidgoyal** [comment]
I dont see why this is a kitty issue. kitty has no control on what a
window manager does with its windows. You should ask for help in the
window manager's issue tracker. Presumably it has issues with OpenGL
windows.

**Comment by Meaticus22** [comment]
Thank you for your response. 
I would like to know where I can find the issue tracker for the window manager in question.
