### ISSUE TITLE
`icat` selective image removal support

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [kovidgoyal/kitty#7480]
Hello!

**Is your feature request related to a problem? Please describe.**
Currently `icat --clear` removes all images from the terminal. And there is no way to remove a single or multiple images just specifying their _IDs_ (I saw the `--image-id <IMAGE_ID>` but it does not look relevant to `icat --clear`).

**Describe the solution you'd like**
* `icat --place` to return a unique rendered image ID (or multiple ones: not sure if `icat --place` accepts multiple images somehow);
* maybe something like `icat --remove`, or `--clear` if it fits the design choice, accepting multiple `ID` returned from the `--place` above .

**Describe alternatives you've considered**
I guess there are none.

**Additional context**
The reason of why I'd like to have this feature is building a **very** specialized photo organizer written in `bash`: rendering multiple photos takes some time, and I would like to remove images that must be replaced with another one or merely removed without the need to redraw entire scene.

Thank you.

**Comment by kovidgoyal** [comment]
printf '\e_Gd=i,i=whatever\e\\`
See https://sw.kovidgoyal.net/kitty/graphics-protocol/

**Comment by lyubomyr-shaydariv** [comment]
Seems exactly what I need, thank you @kovidgoyal!
