### ISSUE TITLE
swap_with_tab swap tabs by numbers 

### ISSUE THREAD

**Issue by chmouel** [kovidgoyal/kitty#7485]
**Is your feature request related to a problem? Please describe.**

The same way we have `swap_with_window` it would be nice if we can have `swap_with_tab`

I generally like to reorder my tabs a lot (by group but tab grouping is not what i request) and it would be easier to have a easy way to reorder the tab the same way swap_with_window works.

**Describe the solution you'd like**

have a `swap_with_tabs` function to let switch between the current tab to the tab selected.
additionally it would be nice to be able to insert the tabs at position, ie if you choose 2 it would insert the current tab between 1 and 3 instead of switching the tab 2 with the current tab position.

**Describe alternatives you've considered**

**Additional context**

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but a PR is welcome, you
should be able to follow along with the swap_with_window implementation.
