### ISSUE TITLE
Kitty wont start on postmarketOS in gnome-mobile  

### ISSUE THREAD

**Issue by vogonwann** [kovidgoyal/kitty#7486]
**Describe the bug**
As title says, my favorite terminal wont start on pmOS under gnome-mobile.

Error is: 
`
fish: Job 1, 'kitty' terminated by signal SIGSEGV (Address boundary error)
`
**To Reproduce**
1. Just start kitty from console
 

**Screenshots**

**Environment details**
```  
 postmarketOS edge, 
gnome-mobile 46 (mutter),
kitty: 0.31.0 
```

**Comment by kovidgoyal** [comment]
First, update kitty. You are quite out of date.
https://sw.kovidgoyal.net/kitty/binary/

**Comment by vogonwann** [comment]
of course I tried the binaries. This is the error:
```
 exec: Failed to execute process './.local/kitty.app/bin/kitty': The file exists and is executable. Check the interpreter or linker?
```

**Comment by kovidgoyal** [comment]
I have no idea what gnome-mobile is presumably it cant execute intel or
ARM binaries.

**Comment by kovidgoyal** [comment]
From googling it looks like postmarketos is some kind of phone OS? Sorry I have no clue about it. You will have to debug things on your own. First step is to get a backtrace.

**Comment by vogonwann** [comment]
Yes it's Linux for phones. Gnome-mobile is mobile configuration of standard gnome-shell,  but it is aarch64. I'll try to compile it from source.

**Comment by kovidgoyal** [comment]
There are aarch64 binaries as well, I assume you tried those.

**Comment by vogonwann** [comment]
yes, same error as above
