### ISSUE TITLE
Hints kitten does not copy full path

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#749]
When I list contents of a directory in kitty using `ls` and the output is a 4 x 5 matrix, using __ctrl+shift+p>f__ misses the last two characters of the file extension (see argument for `less`).

```
[user@host applications]$ ls
app_brush.desktop  app_heif.desktop       app_ora.desktop  app_psd.desktop       app_svg.desktop   org.distro.app.desktop
app_csv.desktop    app_heightmap.desktop  app_pdf.desktop  app_qimageio.desktop  app_tga.desktop
app_exr.desktop    app_jpeg.desktop       app_png.desktop  app_raw.desktop       app_tiff.desktop
app_gif.desktop    app_kra.desktop        app_ppm.desktop  app_spriter.desktop   app_xcf.desktop
[user@host applications]$ less app_png.deskt
```

**Comment by kovidgoyal** [comment]
The regex used to detect paths assumes extensions are a maximum of 5 characters in length to reduce false positives. Fell free to use a different regex if you prefer via the options to the hints kitten.
