### ISSUE TITLE
`--hold-on-error` option

### ISSUE THREAD

**Issue by con-f-use** [kovidgoyal/kitty#7496]
**Is your feature request related to a problem? Please describe.**
When using kitty as the console for qemu virtual machines, it would sometimes be nice, for kitty to hold and not exit, when the main command exits with an error code other than 0, so one can se the error message.

**Describe the solution you'd like**
Introduce a `--hold-on-error` command line argument, that does what `--hold` does, i.e. keep kitty running when the inner process exits, but only when the exit code indicates an error. Otherwise, when the inner process exits with code 0, kitty should also exit normally with this new option.

Example for the wanted behavior:
```shell
$ kitty --hold-on-error /bin/true
# [kitty exits]

$ kitty --hold-on-error /bin/false
false failed with error: exit status 1
# [kitty holds]

**Comment by kovidgoyal** [comment]
kitty sh -c "run-whatever; [[ $? != 0 ]] && read"
