### ISSUE TITLE
building a dmg / .app for mac

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#75]
Hello again, I was able to fix the keyboard input from the previous issue #74,
and noticed that you include a .dmg file in your releases.

I tried generating a macos app using the `py2app` approach, and this works fine, except that the application is named `__main__.app` and it ignores the kitty icon file.

I am aware that the .app extension is just a predefined directory structure that can be set up manually, but I can't seem to do it in regards to kitty. This is just me lacking any experience with how python works..

The reason I'm trying to build it into a .app is so that I can run it through a program I've made that runs commands through keypresses, and ideally I'd like for that to perform `open -na /Applications/Kitty.app`

Is there something special or specific you do to build either a dmg or .app on your mac mini?

Feel free to close this if you don't want to bother or feel it's out of scope.
Appreciate any help you would be willing to give though :)

Cheers for Kitty btw, it is working great for me so far except for this minor annoyance.

**Comment by kovidgoyal** [comment]
See the kitty branch of https://github.com/kovidgoyal/build-calibre

**Comment by kovidgoyal** [comment]
In particular the freeze/osx/__init__.py script which does what py2app does, only much better and with much less code :)

**Comment by kovidgoyal** [comment]
Oh and the easiest way for you to do what you want is simply fix the rpaths in the fast_data_types.so and the dylibs that you are building, then replace the ones in an existing kitty.app and either delete the code signature or resign it yourself if you have a apple dev account. No need to build the bundle yourself.

**Comment by koekeishiya** [comment]
Will check it after work. Thanks again :)

**Comment by koekeishiya** [comment]
> Oh and the easiest way for you to do what you want is simply fix the rpaths in the fast_data_types.so and the dylibs that you are building, then replace the ones in an existing kitty.app and either delete the code signature or resign it yourself if you have a apple dev account. No need to build the bundle yourself.

This worked just fine, thanks!
