### ISSUE TITLE
Hints kitten does not work for dot files

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#750]
When using the hints kitten to select and paste a path, it does not recognise dot files.

#### Steps to reproduce:
1.
```
ls -a | grep -E 'bash|image'
.bash_history
.bash_logout
.bash_profile
.bash_rc
image.png
```

2. __ctrl+shift+p>f__

#### Result
Only `image.png` is selected

#### Expected outcome:
All the files should be indexed including the dot files.

**Comment by kovidgoyal** [comment]
It's not going to, it looks for filenames of the worn name.extension not .name

**Comment by SolitudeSF** [comment]
for line separated output you like this you can just use `ctrl+shitf+p>l`

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks for the explanation @kovidgoyal .

@SolitudeSF that is very useful, thanks. It takes the entire line but that fine as long as the target is an output and not an input or else, it will take the prompt as well.
