### ISSUE TITLE
Why can't I set the background image in kitty.cfg for Kitty on MacOS and have it take effect?

### ISSUE THREAD

**Issue by HaiX1nG** [kovidgoyal/kitty#7500]
I used Homebrew to download Kitty, and after completion, I configured some related settings as shown in the image below. However, when I save the configuration using vim and reopen Kitty, the settings are not applied successfully. Did I make a mistake in the configuration? Or do I need to integrate other plugins to set a background image

this is my `kitty.cfg`
<img width="801" alt="截屏2024-06-03 01 33 56" src="https://github.com/kovidgoyal/kitty/assets/134215827/2e6c9a66-f74e-4d11-92e2-8d2c78f16136">

Thank you very much for your answer!!

**Comment by kovidgoyal** [comment]
Provide all the information asked for in the issue template if you want
help. And setting the background_image option to an absolute path to a
PNG image is all that is required.
