### ISSUE TITLE
Add Yazi terminal file manager to the list of software implementing kitty's graphics protocol

### ISSUE THREAD

**Issue by sxyazi** [kovidgoyal/kitty#7505]
Please add [Yazi](https://github.com/sxyazi/yazi) to this page: https://sw.kovidgoyal.net/kitty/graphics-protocol/

Yazi is a "Blazing fast terminal file manager written in Rust, based on async I/O" that implements the kitty graphics protocol (both Classic and Unicode placeholders), and automatically enables it when terminal support is detected.

**Comment by kovidgoyal** [comment]
Feel free to send a PR to both graphics-protocol.rst and
integrations.rst the website is generated from these on every kitty
update.
