### ISSUE TITLE
Drawing cell border

### ISSUE THREAD

**Issue by xzbdmw** [kovidgoyal/kitty#7511]
**Is your feature request related to a problem? Please describe.**
It will be great if kitty can draw cell border like underline effect, something like this.
<img width="102" alt="截屏2024-06-05 04 05 10" src="https://github.com/kovidgoyal/kitty/assets/97848247/5665fed2-f98f-4435-92e4-3a61bd793fa0">

**Additional context**
Since kitty already support draw underline which can be treated top and bottom part of a cell, with vertical part cell border so something like floating window in neovim don't need to use extra space to draw borders

This image showing we can already draw bottom border within neovim
<img width="577" alt="截屏2024-06-05 04 08 41" src="https://github.com/kovidgoyal/kitty/assets/97848247/dc484bee-0697-44f0-b3ec-d90767278bd7">

**Comment by kovidgoyal** [comment]
Doing this would require a whole new SGR escape code property, indeed four for the four borders and then at least one more for the border color. Which is a huge performance hit, it would require something like 26bits of more storage per cell. And then you would need to wait for other terminals to agree to adopt it and for nvim to actually use it. Not worth it for this usecase. As for floating window borders, the correct solution for this is for nvim to use terminal native floating windows. These dont yet exist but it is on my TODO list to create a protocol for them.
