### ISSUE TITLE
`symbol_map` and `narrow_symbols` should be font-family-aware

### ISSUE THREAD

**Issue by galou** [kovidgoyal/kitty#7514]
**Is your feature request related to a problem? Please describe.**
I wanted to nicely show some italic characters with Victor Mono fonts but have issue with the one-cell character policy of Kitty (cf. https://github.com/rubjo/victor-mono/issues/44). I though to use `narrow_symbols` but I cannot do it because I cannot specify that only the italic representation of the character should be tuned.

**Describe the solution you'd like**
`narrow_symbols codepoints [optionally the number of cells] [optional font_family]`

**Describe alternatives you've considered**
`symbol_map U+0051 VictorMonoNerdFont # Q that renders too small with Italic`. Replaces the italic with regular but I would prefer to replace with Oblique.

**Additional context**
https://github.com/rubjo/victor-mono/issues/44.

**Comment by kovidgoyal** [comment]
As the name implies narrow_symbols is meant for symbols not text,
symbols dont have italics and in any case the way this works is that if
a symbol followed by a space would have been rendered by kitty in 2 or
more cells you can restrict it to 1 cell. It wont help with the issue of
a font with non metric compatible italics.
