### ISSUE TITLE
Kitty is submitting trashed / uninitialized buffers via linux-dmabuf when resizing

### ISSUE THREAD

**Issue by vaxerski** [kovidgoyal/kitty#7516]
**Describe the bug**
Hi Kovid! I've been using kitty for ages, and recently while working on a rewrite of the dmabuf infrastructure in hyprland (ref: https://github.com/hyprwm/Hyprland/pull/6268) I've stumbled on a bug in kitty that is preventing me from using it.

You'll see what I mean in the screenshots, but whenever rapidly resizing, (e.g. with a mouse) kitty's dmabuf sometimes becomes corrupted for a single frame. This could be kitty trashing the buffer, or sending an uninitialized one, or a freed one.

I am convinced this is a kitty issue, because I've tested numerous other clients using linux-dmabuf-v1 and kitty is the _only one with this issue_. Tested: mpv, gtk apps, alacritty.

I've scrubbed the code of the MR for days by now and couldn't find anything amiss on my side.

I can also alter the environment a bit to fix this issue, see additional context at the bottom.

**To Reproduce**
1. Checkout hyprland to the `wayland-rewrite` branch.
2. Launch kitty
3. Use mod+mouse to resize the window with a mouse

**Screenshots**
Video:

https://github.com/kovidgoyal/kitty/assets/43317083/74c65829-b644-4dac-9ab8-026020ab1a6e

Frame where the bug happens:
![image](https://github.com/kovidgoyal/kitty/assets/43317083/d1483952-9ab1-4099-aba2-2aef5f7f7926)

**Environment details**

<details> 
  <summary> log </summary>

```
kitty 0.35.1 created by Kovid Goyal
Linux Arch 6.9.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:26 +0000 x86_64
Arch Linux 6.9.3-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland (/home/vaxry/WMS/hyprland/build/Hyprland) missing: single_pixel_buffer
OpenGL: '4.6 (Core Profile) Mesa 24.1.0-arch1.1' Detected version: 4.6
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/vaxry/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close 0
remember_window_size    False
Colors:
	background              #110e0e
	color0                  #302b2a
	color1                  #a6463d
	color10                 #128c20
	color11                 #fc6a20
	color12                 #7898f7
	color13                 #fc89a0
	color14                 #fad384
	color15                 #fffefe
	color2                  #577644
	color3                  #9c5f2a
	color4                  #84362e
	color5                  #854551
	color6                  #9c814e
	color7                  #c8c8c8
	color8                  #4d4d47
	color9                  #aa000c
	cursor                  #fffefe
	foreground              #bfbfbf
	selection_background    #302b2a
	selection_foreground    #1a1818

Important environment variables seen by the kitty process:
	PATH                                /home/vaxry/.local/bin:/home/vaxry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-2
	USER                                vaxry
	XCURSOR_SIZE                        32
	XDG_BACKEND                         wayland
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 Hyprland
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	LC_CTYPE                            en_US.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000

```

</details>

**Additional context**
Curious info:
 - commenting out `background: #110E0E` _fixes this issue_ (???)
 - Blacklisting 3 modifiers that kitty would use by default makes it fallback to a non-DCC modifier and creates a single-plane buffer. This also makes the issue go away.
 - this only happens on specific hardware combinations, I haven't seen this on my laptop, but is very common on the desktop. Both are AMD.

**Comment by kovidgoyal** [comment]
Doesn't repro for me on my AMD Radeon Vega laptop and I'm travelling so I dont have another machine to test on. kitty (or rather glfw that kitty has a fork of) doesnt actually submit buffers to the compositor directly except briefly during window creation. Buffers are submitted via EGL swap. So for instance there is no DCC or dmabuf in the entire codebase. That said there was a recent commit that moves calling wl_egl_resize() back before resizing the framebuffer instead of before swapping, as it was causing issues with the NVIDIA drivers, so try running kitty from master. 

https://sw.kovidgoyal.net/kitty/build/  (instructions for running from source)

**Comment by kovidgoyal** [comment]
Oh and if you dont want to build kitty you can also just try the nightly https://sw.kovidgoyal.net/kitty/binary

**Comment by vaxerski** [comment]
I've built from source and it actually makes the problem worse! The flickering is now more frequent when resizing.

**Comment by kovidgoyal** [comment]
Then I haven't a clue what could be causing it. And without being able to reproduce there isnt a lot I can do to debug unless you are willing to dive into kitty/glfw code with some guidance from me.

As for the EGL: Failed to get EGL display: Success error is that specific to running from master or does it affect released kitty as well.

**Comment by vaxerski** [comment]
only master, release kitty works fine (EGL error)

I am fine with diving into the code, because I got no clue either about what's up here, and it would be great if I could keep using kitty :P

I'll try to tinker a bit with the egl code, see what I can do. I assume all egl stuff is in glfw/egl_context.c?

**Comment by vaxerski** [comment]
I've reset the source to 0.35.1 and the GLFW EGL error is still there. I've recloned, still there. It seems like it's a problem in the build process. I run `./dev.sh build`, then `./kitty/launcher/kitty`. I've installed the AUR package `kitty-git` and it works too...?

**Comment by kovidgoyal** [comment]
make clean and rebuild probably.

**Comment by kovidgoyal** [comment]
And if you are on Arch you dont need to use ./dev.sh you can just do 

make debug

as its easy to install all the needed dependencies.

**Comment by vaxerski** [comment]
thanks! make debug worked.

**Comment by kovidgoyal** [comment]
On Fri, Jun 07, 2024 at 02:07:52AM -0700, Vaxry wrote:
> only master, release kitty works fine (EGL error)
>
> I am fine with diving into the code, because I got no clue either about what's up here, and it would be great if I could keep using kitty :P

OK, see below.

>
> I'll try to tinker a bit with the egl code, see what I can do. I assume all egl stuff is in glfw/egl_context.c?

egl_context is where the context is created and swapped and managed. wl_window.c and wl_init.c is where the wayland integration takes place.

kitty itself draws in shaders.c and swapping of buffers and clearing and
so on happens in glfw.c

**Comment by vaxerski** [comment]
it gets at least 10x rarer when I comment out glfwSwapInterval(val) in glfw.c@48

**Comment by kovidgoyal** [comment]
IIRC that just means that now mesa will submit a wayland render frame request and only swap after the compositor responds. This is a big performance hit and is unnecessary since kitty already uses the wayland render frame protocol to throttle rendering. Relevant code in child-monitor.c grep for USE_RENDER_FRAMES and see the sync_to_monitor option that controls it in kitty.conf.

**Comment by kovidgoyal** [comment]
Although perhaps render frames are ignored during a live resize. But, even if they are, a client submitting a frame without a render frame response is not actually a bug as far as I know.

**Comment by vaxerski** [comment]
it's not, it only would be a bug if you started rendering to a buffer before .release() was received I believe

**Comment by kovidgoyal** [comment]
Dont see how that could happen in kitty code. kitty just calls swap and draws in between swap calls there is no actual buffer management being done. That is done by mesa/gpu driver/lowerlayers.

**Comment by vaxerski** [comment]
Me neither, but it only happens in kitty. I've just booted up my laptop again and instead of the green shimmers, the buffer looks empty for a frame, so it does seem to happen too, just differently.

Other apps that use dmabufs that don't do this:
 - nautilus (gtk4)
 - firefox (gtk...something)
 - alacritty (rust)
 - mpv (independent)
 
I assume there is no way in kitty to force wl_shm to test if it does happen there too?

**Comment by kovidgoyal** [comment]
A blank buffer can happen if there is a call to blank_canvas() and then swap without an intervening call to draw_cell() and friends. This should be easy to trace to check if it happens. 

Not sure what force wl_shm to test means?

**Comment by vaxerski** [comment]
instead of using egl stuff, render to a ram pixel buffer and submit that via wl_shm (aka. software rendering)

> A blank buffer can happen if there is a call to blank_canvas() and then swap without an intervening call to draw_cell() and friends. This should be easy to trace to check if it happens.

doesn't seem to happen, and likely isn't the case. To me, this looks like uninitialized memory, so something like skipping the entire render pipeline altogether and doing eglSwapBuffers would be the only thing I could guess.

**Comment by kovidgoyal** [comment]
No there's no infrastructure in kitty for software rendering but you can get mesa to do it via some env var whose exact name escapes me at the moment.

You can trace all calls to eglswapbuffers, it is called in only one place in the entire codebase. Just trace calls to render_prepared_os_window() and eglswapbuffers() if you see a swap without a render that's a hint something is off.

**Comment by kovidgoyal** [comment]
Just FYI, I am travelling so I'm afraid I am going to be available only sporadically but I would be most interested if you do find a bug in kitty code and I will try to respond to any queries as and when I can.

**Comment by vaxerski** [comment]
I'll keep debugging this on both sides and keep you posted. Thanks for the help and enjoy your time :)

**Comment by vaxerski** [comment]
haven't found much in either kitty or hyprland, but I have had one person saying that the blank buffers bug does happen for him on nvidia regardless of the hyprland version, that's about it.

**Comment by vaxerski** [comment]
this may be a broader issue in the interaction between the hl impl and glfw in general, as I've reproduced (even nastier) effects in minecraft, which also uses glfw.

**Comment by kovidgoyal** [comment]
The commit I referred to earlier was specifically to fix flickering during resize on NVIDIA (in all compositors). Your user's report probably refers to that.

**Comment by vaxerski** [comment]
could be. This bug is unlikely to be a kitty bug in light of the current state of things, as I've reproduced similar issues in minecraft (opengl/glfw) so it's likely an interaction with glfw <-> hl rewrite, so I'll close this for now.

I'd guess there is an issue with implicit sync somewhere in hl, but it's odd that only glfw apps are affected.

Thanks for the help :)

**Comment by kovidgoyal** [comment]
Welcome and just FYI kitty uses a heavily patched fork of glfw, so if you do find it is caused by an issue in glfw do let me know and I will probably end up fixing it before official glfw does.

**Comment by vaxerski** [comment]
it's likely not an issue with glfw, as per this disco:

https://github.com/kovidgoyal/kitty/assets/43317083/286e1a65-cb29-4e68-b840-b545b9337a44
(that's qt with qml)

I wish I knew where sync is getting broken. I hate software development.

**Comment by kovidgoyal** [comment]
I feel your pain. I have had to debug a few similar things in my career and its never fun. If there is anything I can do to help in kitty do let me know. Software rendering would be rather too time consuming to implement, but perhaps some kind of logging using a shared timesource or a custom wayland protocol by which kitty can inform you of exactly when it calls swap or something along those lines.

**Comment by vaxerski** [comment]
I fixed it, finally after 2 weeks: https://github.com/hyprwm/Hyprland/commit/9994b73ad0af5c9ba5fc4058234cea77d0a1ddb1

nothing wrong on your side, cheers :)
