### ISSUE TITLE
After installing NVIDIA drivers, kitty won't start from taskbar.

### ISSUE THREAD

**Issue by Amirali-Amirifar** [kovidgoyal/kitty#7517]
**Describe the bug**
After I installed nvidia drivers in my system and rebooted. I cannot open up kitty using my shortcut, taskbar or main menu. but I found out that I could open a kitty instance from another terminal emulator like konsole. 
Before this I used to use it only by my integrated graphics card.
It seems like it has a problem in  `[glfw error 65542]: EGL: Failed to get EGL display: Success`.

**To Reproduce**
Here are the logs I found:
logs

![image](https://github.com/kovidgoyal/kitty/assets/9336920/31bd2af7-a03c-401b-85a3-2cd1da4bc8e3)

**Environment details**
```
kitty 0.35.1 created by Kovid Goyal
Linux arch 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64
Arch Linux 6.9.3-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland (kwin 6.0.5) missing: single_pixel_buffer
OpenGL: '4.6 (Core Profile) Mesa 24.1.1-arch1.1' Detected version: 4.6
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/amirali/.config/kitty/kitty.conf

Config options different from defaults: -Not included-

Important environment variables seen by the kitty process:
	PATH                                /home/amirali/Projects/Github/chromium/depot_tools:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/amirali/.fzf/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                amirali
	XDG_CONFIG_DIRS                     /home/amirali/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/amirali/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_MENU_PREFIX                     plasma-
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session2
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1

```

PS:
I have temporarily fixed the problem by changing my shortcut to run script `kitty` instead of application.

**Comment by kovidgoyal** [comment]
This is a GPU driver regression. Report it to the mesa or nvidia or
whatever organisation you get your GPU drivers from and rollback the
drivers and you will be fine.

**Comment by Amirali-Amirifar** [comment]
It wasn't related to GPU drivers. I did the following things and it eventually worked somehow. I don't know which of the following fixed the issue:
1. remove kitty completely 
2. install glfw package
3. install it manually (didnt work so removed it)
4. installed again using package manager and now it works !

**Comment by kovidgoyal** [comment]
Then it will be something in the updated GPU drivers that broke compatibility with one of the bundled libraries in the kitty binary package.  Since you are on Arch you can just use the arch kitty package instead they keep it relative up-to-date.
