### ISSUE TITLE
Letters cut

### ISSUE THREAD

**Issue by fernat001** [kovidgoyal/kitty#7519]
Hello.
I have started a new kali virtual machine.
I just run this commands:
`sudo apt update`
`sudo apt upgrade`
'sudo apt install kitty'
And when I run kitty I see:
https://cdn.discordapp.com/attachments/801794166199681045/1248539430906499113/image.png?ex=66640875&is=6662b6f5&hm=f7eacf1ada8e3936482a8f7f65480f8eee0cf5b85bb7ce4a4706264a8508ba9a&
What can I do to solve it?
Thanks

**Comment by kovidgoyal** [comment]
dup of #6257
