### ISSUE TITLE
kitty diff jump to next file

### ISSUE THREAD

**Issue by jackielii** [kovidgoyal/kitty#7523]
**Is your feature request related to a problem? Please describe.**

I searched through issues and PRs, couldn't find reference to this functionality.

When there is a commit which contains large files, usually generated, I just want to skip over it. Jumping to next page is the fastest, but still not fast enough.

**Describe the solution you'd like**

I propose adding a mapping to jump to next file change

**Describe alternatives you've considered**

Jump page by page, but still too slow

**Additional context**

**Comment by kovidgoyal** [comment]
There is already scroll to next change (N). This will skip over the
entire current change. This wont help if your file contains lots of
small changes, but otherwise will do the trick. If you want a jump to
next file action, a PR adding it is welcome.
