### ISSUE TITLE
Mac OS: Font fallback fails for Fira Code with the hyphen symbol `‐` (U+2010)

### ISSUE THREAD

**Issue by ilyagr** [kovidgoyal/kitty#7525]
I reproduced this bug with Kitty 0.33.0, 0.33.1, and 0.35.1. This is on Mac OS Sonoma 14.5.

The problem is that Kitty fails to print the `‐` symbol when the font is set to Fira Code. Instead, it prints a question mark inside a rectangle. Here is a screenshot (commands to produce it are below)

![image](https://github.com/kovidgoyal/kitty/assets/4123047/c9902484-fff8-416e-b6bd-ed53aded9f4e)

(I noticed this because Nix's version of man uses it as, well, a hyphen)

Other terminals (Apple's Terminal App, iTerm2, VS Code terminal or the editor itself) do not have this problem. https://github.com/kovidgoyal/kitty/issues/3591  suggests that Kitty is meant to find a fall-back font if the character is not present in Fira Code, so I'm guessing this is a bug. I don't see this problem with other fonts either (but again, other terminals handle this font somehow)

## Debug output & what I ran

```console
$ brew install --cask font-fira-code
...
$ uname -a
Darwin macaw.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64 arm 
$ cat kitty.demo.conf
font_family Fira Code
$ kitty --debug-font-fallback --config kitty.demo.conf /bin/dash  -c 'echo ‐ ‐;read qq'
[0.168] Preloaded font faces:
[0.168] normal face: /Users/ilyagr/Library/Fonts/disabled/FiraCode-Regular.ttf
[0.168] bold face: /Users/ilyagr/Library/Fonts/disabled/FiraCode-SemiBold.ttf
[0.168] italic face: /Users/ilyagr/Library/Fonts/disabled/FiraCode-Regular.ttf
[0.168] bi face: /Users/ilyagr/Library/Fonts/disabled/FiraCode-Regular.ttf
[0.215] Cell height calculation:
[0.215] 	line height from line origins: 33.000000
[0.215] 	line bounds: origin-y: -6.769257 height: 32.492432
[0.215] 	line bounds-no-leading: origin-y: -6.769257 height: 32.492432
[0.215] 	bounds metrics: ascent: 25.723175
[0.215] 	line metrics: ascent: 20.307770 descent: 6.769257 leading: 0.000000
[0.215] 	font metrics: ascent: 20.307770 descent: 6.769257 leading: 0.000000 underline_position: -1.128205
[0.215] 	cell_height: 33 baseline: 26 underline_position: 27 strikethrough_position: 16
2024-06-07 16:58:37.162 kitty[26159:9297464] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
```

<details><summary>Kitty's Alt+F6 debug output</summary>

I'm running Kitty 0.35.1 straight from the DMG here, but I see the same problem with installed Kitty 0.33.1 as well.

```
kitty 0.35.1 (1bfb1de7fc) created by Kovid Goyal
Darwin macaw.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		14.5 BuildVersion:		23F79
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1
Frozen: True
Paths:
  kitty: /private/var/folders/lj/rv4h95_d0mxb9ryztzpz4qph0000gn/T/AppTranslocation/3EF8FDD2-748D-4C6F-97C2-7A9674F05902/d/kitty.app/Contents/MacOS/kitty
  base dir: /private/var/folders/lj/rv4h95_d0mxb9ryztzpz4qph0000gn/T/AppTranslocation/3EF8FDD2-748D-4C6F-97C2-7A9674F05902/d/kitty.app/Contents/Resources/kitty
  extensions dir: /private/var/folders/lj/rv4h95_d0mxb9ryztzpz4qph0000gn/T/AppTranslocation/3EF8FDD2-748D-4C6F-97C2-7A9674F05902/d/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/bash
Loaded config files:
  kitty.demo.conf

Config options different from defaults:
font_family Fira Code
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /Users/ilyagr/.nix-profile/bin:/Users/ilyagr/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ilyagr/.cargo/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/private/var/folders/lj/rv4h95_d0mxb9ryztzpz4qph0000gn/T/AppTranslocation/3EF8FDD2-748D-4C6F-97C2-7A9674F05902/d/kitty.app/Contents/MacOS
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /opt/homebrew/bin/fish
	DISPLAY                             /private/tmp/com.apple.launchd.WqZgAzJRQd/org.xquartz:0
	USER                                ilyagr
	XDG_DATA_DIRS                       /usr/local/share:/usr/share:/Users/ilyagr/.nix-profile/share:/nix/var/nix/profiles/default/share:/Users/ilyagr/.nix-profile/share:/nix/var/nix/profiles/default/share
```

</details>

Cc: https://github.com/kovidgoyal/kitty/discussions/4007

**Comment by kovidgoyal** [comment]
Works fine for me with.

kitty --config=NONE -o 'font_family Fira Code' --debug-font-fallback sh -c 'printf "\u2010"; read'

The fact that --debug-font-fallback is not outputting anything about
U+2010 means that it is being loaded from Fira Code. Which implies that
the Fira Code on your system maps the character to the unknown character
glyph. I suggest you update Fira Code. Or use symbol_map in kitty.conf
to explicitly load it from another font. Also I dont know why you have
Fira Code in a directory named disabled, though that's irrelevant to
this issue.

**Comment by ilyagr** [comment]
Thanks for looking!

I just tried to install Fira Code by updating it from Homebrew. It didn't quite work (that's why you saw "disabled/" in the path), but I just tried again properly. I'm using the proper version obtained with `brew install --cask font-fira-code` today, and I got the same result.

How did you install Fira Code? I wonder why it'd work differently on your machine...

I tried your command; I think we have different `sh`, but changing your command to use `zsh` instead gave me the same question mark.

In any case, I can certainly use `symbol_map` to fix it. I think there must be some underlying bug or difference of behavior form all the other terminals, but it might not matter much if this is its only effect.

**Comment by kovidgoyal** [comment]
Do you actually have a font on your system that has glyph for that
character? I have a ton of different fonts installed. On my system the
glyph came from Consolas, for instance.

And I install fonts by simply downloading the zip file containing the
font ttf files and extracting them into ~/Library/Fonts no need for any
package managers.

It might be your other terminal emulators special case this
character to render using the glyph for the ASCII hyphen.

**Comment by ilyagr** [comment]
> Do you actually have a font on your system that has glyph for that
character?

I think so.

```
kitty --config=NONE -o 'font_family Fira Code' -o 'symbol_map U+2010 Monospace' --debug-font-fallback /bin/zsh -c 'printf "\u2010"; read'
```

works. I'm not sure how to debug any further, though. It falls back to Menlo:

```
[159 21:36:29.152121] Preloaded font faces:
[159 21:36:29.152143] normal face: /Users/ilyagr/Library/Fonts/FiraCode-Regular.ttf
[159 21:36:29.152149] bold face: /Users/ilyagr/Library/Fonts/FiraCode-SemiBold.ttf
[159 21:36:29.152154] italic face: /Users/ilyagr/Library/Fonts/FiraCode-Regular.ttf
[159 21:36:29.152157] bi face: /Users/ilyagr/Library/Fonts/FiraCode-Regular.ttf
[159 21:36:29.152162] Symbol map faces:
[159 21:36:29.152165] /System/Library/Fonts/Menlo.ttc
2024-06-07 21:36:30.868 kitty[2287:10074868] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
```

**Comment by ilyagr** [comment]
Thank you very much!

It is amusing how complicated the patch and the cause is for this problem. Fonts are crazy, thank you again for having the patience to dig through it.

**Comment by kovidgoyal** [comment]
You are welcome, and yes fonts have a *lot* of legacy that makes them
particularly painful to deal with.
