### ISSUE TITLE
Mouse wheel scrolls too fast when using nvim

### ISSUE THREAD

**Issue by ofseed** [kovidgoyal/kitty#7527]
With the `"ver:3,hor:6"` default value of `'mousescroll'`, just rolling the mouse wheel once will scroll more than ten lines.

Seems like because of my high-precision mouse wheel, but I tried both `wheel_scroll_multiplier` (which the doc says for low-precision devices) and `touch_scroll_multiplier` (which the doc says for high-precision devices), either do not work.

I tried negative value for the both, found only `wheel_scroll_multiplier` works, and according the doc seem that `touch_scroll_multiplier` only take effect on high-precision touchpads. No option for high precision mouse wheel?

Platform is Arch Linux, KDE on Wayland, the kitty version is 0.34.1.

**Comment by kovidgoyal** [comment]
Does not reproduce for me. Scrolling in nvim reverses direction with

kitty --config=NONE -o touch_scroll_multiplier=-1 nvim --clean setup.py

and scrolls three lines per event not 10.

kitty does not know or care about touchpads and wheel mice. The system
is responsible for reporting either high or low resolution devices and
in either case the appropriate multiplier is applied, as can be seen in
the scroll_event() function.

And note that the terminal mouse protocol doesnt allow reporting
magnitudes for scroll events (its the usual poorly designed crap
inherited form xterm). So changing the magnitude of the multiplier wil
only affect how fast kitty's own scrollback scrolls.
