### ISSUE TITLE
How does dynamic_background_opacity impact performace

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#753]
I [read](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.enabled_layouts) that this parameter is turned off by default as it is a performance cost. However it doesn't say how much of a performance cost this is. I would like to get more information about what this means, and what part of kitty's performance is affected?

**Comment by kovidgoyal** [comment]
try it and see. How much of a performance cost it is depends on what you
use kitty for and your hardware and your graphic drivers.
