### ISSUE TITLE
Feature request: show a border on a kitty window even when the tab contains only one single window

### ISSUE THREAD

**Issue by thenbe** [kovidgoyal/kitty#7531]
Currently, kitty can indicate the active window within a tab by using `active_border_color` and `inactive_border_color`. This border is only displayed when a tab contains more than one window. If I understand it correctly, this is because those `(in_)active_border_color` settings are intended to help identify the active window within a tab. Therefore if a tab only contained a single window, a border is redundant for that use case.

Using a simple watcher (~7 [lines](https://github.com/kovidgoyal/kitty/issues/7530#issue-2345499039) of python), we can utilize those settings to enable kitty to indicate the current _focused_ window (globally) with a colored border (as opposed to only indicate the active window with a tab). This mostly works except for a single scenario: when a kitty tab contains only one window.

This is a feature request to allow a kitty window to have a border even if the tab only contains a single window.

## Use case

The desired state is to indicate the currently focused window (be it firefox, a kitty os-window, or a kitty window) using a colored border. There should only be one visibile colored border on the screen at any given time.

Therefore, I have set up my WM (awesomewm) to handle borders for non-kitty windows and left kitty to handle border for itself (using the watcher shown in this [comment](https://github.com/kovidgoyal/kitty/issues/7530#issue-2345499039)). Now, the WM only adds a border if this condition is true: `client.class != 'kitty'`.

This works great except for a single scenario: there is no colored border when a kitty tab contains only one single window. The reason is there is no border in this scenario is because the WM skips the border because of our condition. Meanwhile, kitty itself does not support drawing a colored border on a window when the parent tab contains only one single window (see above for why that is).

## Workaround

Have the window manager draw a border on kitty windows (as per https://github.com/kovidgoyal/kitty/issues/7530#issuecomment-2159957740). This works (and it's what I'm doing now). However, this leaves us with the undesired effect of having double borders, one drawn by kitty on the kitty window and the other drawn by the window manager. While this is generally not an issue at first, it starts becoming one as you start adding more windows. For instance, if I switch to a workspace like the one seen towards the end of this video, I would need a moment to realize where the focus lies .

https://github.com/kovidgoyal/kitty/assets/33713262/e280d872-abc8-4087-99d6-41587121003a

&nbsp;

I'm also open to other suggestion on how to accomplish this. Whether through a custom kitty watcher or through the window manager.

**Comment by kovidgoyal** [comment]
no, not really. Indicating the globally focused OS window is the window
managers job not that of individual applications.
