### ISSUE TITLE
Feature Request: Option to clamp background outside center or scale window logo

### ISSUE THREAD

**Issue by amuDev** [kovidgoyal/kitty#7532]
**Is your feature request related to a problem? Please describe.**
The `window_logo` parameter seems to have the same goals that I am trying to achieve but with one major shortfall, there is no scaling applied when the window size changes. Why might this be a problem? Sometimes I just want to have a nice logo on that scales in my terminal. Using the current window_logo creates either a logo far too small when using a larger terminal window, or a logo that blocks far too much content on smaller terminal windows.

**Describe the solution you'd like**
Ideally an additional parameter that is tied either to background or window logo. In the case of the background having a choice to set the anchor point to cscale (instead of forced centre). In the case of the logo, a simple flag to enable scaling, though this seems a bit more complex since there would also likely need to be a ratio set to determine what to scale the logo to.

**Describe alternatives you've considered**
Not many relevant alternatives that arent listed. I have created a [fork branch](https://github.com/kovidgoyal/kitty/compare/master...amuDev:kitty:bg-br-clamping) that simply forces this behaviour when using cscaled, though this is purely for my use and a further demonstration to what the goal is. Although the actual implementation is just changing the scaling behaivour on the `draw_background_image` method with slightly different calculations for left and top to allow clamping on bottom right.

**Additional context**
![image](https://github.com/kovidgoyal/kitty/assets/51936412/f941addc-cb64-48bf-ba2b-5813aa54adfc)

**Comment by kovidgoyal** [comment]
I dont follow your use case. If you want a logo that scales with the
terminal window, simply use a background image that is completely
transparent other than the logo part in the bottom right (or wherever)
and make sure this image is larger than the max terminal size you use.
It will be scaled automatically and your logo will be always displayed
at the bottom right scaled alongwith it.

As for your feature request, I am in principle fine with adding a
window_logo_scale type option but I dont really see the need given what
I said above. In any case I am not going to implement such a feature
myself, but a PR is welcome. If you do choose to submit a PR we can
discuss the semantics of such an option.

**Comment by amuDev** [comment]
The problem with using cscaled in conjunction with an oversized image is that when the aspect ratio of the image and window are different there is some portion of the image that gets cut. This can't be mitigated much since (at least on a tiling window manager) the aspect ratio of a given terminal session can vary from the whole screen to a small box, in cases where there is a greater discrepancy between the usable aspect ratios and the images aspect ratio, it becomes very difficult to have a properly positioned "logo" while still scaling.

3840x2160 (16:9) background displayed on various window sizes using cscaled.
![image](https://github.com/kovidgoyal/kitty/assets/51936412/3e62dfee-9a84-4823-8259-9036a95e066a)

3440x1440 (21:9) background displayed on various window sizes using cscaled.
![image](https://github.com/kovidgoyal/kitty/assets/51936412/bdca5404-5840-4085-b184-e70e903a4f19)

On the topic of window_logo_scale, I presume the best design would be assigning a ratio of the terminal to scale to? e.g. `window_logo_scale = 15` scales the size of the logo to 15% of the screen size in the largest dimension?
