### ISSUE TITLE
Unable to use `remote_control_password` option with empty password

### ISSUE THREAD

**Issue by ducmtran** [kovidgoyal/kitty#7538]
**Describe the bug**
`remote_control_password` option doesn't seem to work with blank password

**To Reproduce**
Set in kitty.conf
```
 allow_remote_control password
 remote_control_password "" set-tab-title
```
Running kitty commands
```
➜  ~ kitty @ --password= set-tab-title 'foo'
Error: Remote control is disabled. Add allow_remote_control to your kitty.conf
➜  ~ kitty @ --password='' set-tab-title 'foo'
Error: Remote control is disabled. Add allow_remote_control to your kitty.conf
➜  ~ kitty @ set-tab-title 'foo'                 
Error: Remote control is disabled. Add allow_remote_control to your kitty.conf
```

**Screenshots**

**Environment details**
```
allow_remote_control      password
copy_on_select            clipboard
enable_audio_bell         False
enabled_layouts           ['splits', 'grid', 'tall']
font_family               Office Code Pro
font_size                 13.0
inactive_text_alpha       0.6
remote_control_password:
{'set-tab-title': ()}
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
yes, it's not supposed to. If you want to use a blank password, dont use
remote control password at all. If you want to use a password for a
particular action that is simple, use "a" or whatever. Once apassword is
involved, communication is encrypted, therefore, blank passwords cannot
be used.

**Comment by ducmtran** [comment]
that makes sense - i was trying that because it's referenced in the docs that i can use it https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remote_control_password:~:text=A%20set%20of%20actions%20to%20be%20allowed - this probably should be updated

**Comment by kovidgoyal** [comment]
If its documented it is probably intended to work in some situations, let me investigate in more detail when I have some time.
