### ISSUE TITLE
After installing Kitty, it becomes the default opening method for multiple file types

### ISSUE THREAD

**Issue by epheien** [kovidgoyal/kitty#7543]
After installing Kitty (copy kitty.app to /Applications/), it becomes the default opening method for multiple file types.

OS: macOS 12.7.5
kitty: 0.35.1 or nightly

1. Install kitty.app
2. Right click on the dmg file with the mouse
3. move to "Open With'
4. See kitty.app as default

**Screenshots**
<img width="708" alt="Xnip2024-06-14_11-47-52" src="https://github.com/kovidgoyal/kitty/assets/3406908/da5232df-7f6c-4b36-8a45-12985f5ac8b1">
<img width="710" alt="Xnip2024-06-14_11-48-17" src="https://github.com/kovidgoyal/kitty/assets/3406908/3d90f020-3c31-42dd-b240-4a216c03c79a">

**Comment by kovidgoyal** [comment]
kitty does not make itself the default handler for any filetypes. That
is upto the OS.

**Comment by epheien** [comment]
I don't know wich app modify my `~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist` 
```
$ grep kitty com.apple.launchservices.secure.plist  | wc -l
40
```

After deleting this file and restarting, the problem was resolved.
