### ISSUE TITLE
Conditional launch

### ISSUE THREAD

**Issue by roylez** [kovidgoyal/kitty#7550]
**Is your feature request related to a problem? Please describe.**

I would like to dedicate keybindings to some specific program, for example mutt, and hitting `cmd+m` should launch mutt in a new tab with `--tab-title=MUTT` or take me to a tab titled "MUTT".

Currently if there is already a mutt tab open, `combine | toggle_tab title:MUTT | launch --type tab --tab-title MUTT mutt` will still open a second mutt tab.

**Describe the solution you'd like**

- make combine to do "OR" operations, maybe with "::" or "||" separators.
- make toggle_tab to have a switch to be silent about failures but still tell combine about its failures so that subsequent commands could action accordingly.

**Describe alternatives you've considered**

- make combine to do "OR" operations, maybe with "::" or "||" separators.
- a separate `condition` action

**Comment by kovidgoyal** [comment]
This kind of thing is trivially accomplished using either a kitten (written in python) or a remote control script, written in any language you like that can call the kitten @ binary to perform remote control commands. 

https://sw.kovidgoyal.net/kitty/kittens/custom/
or
https://sw.kovidgoyal.net/kitty/remote-control/
especially focus on remote_control_script  (and no you dont need to turn on remote control globally for this) https://sw.kovidgoyal.net/kitty/remote-control/#mapping-key-presses-to-remote-control-commands

**Comment by roylez** [comment]
Indeed. `remote_control_script` is all I need.

```
#!/bin/bash

TITLE=$1
shift

if (kitten @ ls --self -t title:${TITLE} 2>/dev/null); then
  kitten @ action toggle_tab title:${TITLE}
else
  kitten @ launch --type=tab --tab-title=${TITLE} "$@"
fi
```
