### ISSUE TITLE
`close_on_child_death` setting and docs are confusing

### ISSUE THREAD

**Issue by benjamin051000** [kovidgoyal/kitty#7551]
When reading  #4171, I realized that the relevant documentation for `close_child_on_death` has some strange wording that I'm not sure lines up correctly with its behavior. Full excerpt: 
> Close the window when the child process (shell) exits. With the default value no, the terminal will remain open when the child exits as long as there are still processes outputting to the terminal (for example disowned or backgrounded processes). When enabled with yes, the window will close as soon as the child process exits. Note that setting it to yes means that any background processes still using the terminal can fail silently because their stdout/stderr/stdin no longer work.

Let's break it down:

> With the default value no, the terminal will remain open when the child exits as long as there are still processes outputting to the terminal (for example disowned or backgrounded processes).

This statement is false. The terminal appears to remain open when a child process exits regardless of the value of `close_on_child_death`. 

> When enabled with yes, the window will close as soon as the child process exits.

This happens if and only if I run `exit` or pass `^D` to my shell while a background/disowned process exists. `/usr/bin/vlc &`  (and optionally a `disown` of the `vlc` process) does not exit the shell even after I kill vlc. It only exits when I tell it to.

---

What this setting actually appears to control is the ability for the terminal window to close despite there being child/disowned jobs. If `no`, it will hang until all children/disowned jobs exit (since they may print to the terminal) (unless you use `Ctrl+Shift+W` to close the kitty window that way). If `yes`, the terminal may close despite these processes existing.

Am I misunderstanding what you mean in this documentation? To me, what this variable should really be named something like `hang_while_children_exist`, and the documentation should better reflect this behavior.

**Comment by kovidgoyal** [comment]
The child process here is the child process of the *terminal* not of the
*shell*. IOW, the child process here is the *shell itself*. Once you realize
that, the documentation is perfectly correct. The documentation even
states "child process (shell)" to make that clear.

**Comment by benjamin051000** [comment]
ohhhh, that does make more sense. Thanks for your explanation.
