### ISSUE TITLE
Inherit PATH in remote control script

### ISSUE THREAD

**Issue by roylez** [kovidgoyal/kitty#7556]
**Is your feature request related to a problem? Please describe.**

When writing a remote control script, I was caught by surprise that the script always failed when triggered by a keybinding. It turns out that the reason was that `jq` was not in the PATH because remote control scripts do not inherit the full PATH from kitty.

Here is the content of the PATH that the script gets, even though Kitty has set `exe_search_path` and PATH in a shell has more directories:

```
/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by kovidgoyal** [comment]
remote control scripts have the same PATH as the kitty process. kitty is
started *before* your shell, it cannot get the PATH from the shell
scripts. You should change your path system wide not in shell scripts,
or alternately set it in kitty.conf.
