### ISSUE TITLE
Split Left Oriented. 

### ISSUE THREAD

**Issue by brunoferromega** [kovidgoyal/kitty#7560]
Whenever I split the layout, it move to the right side. 
For example: I want to use as The Tall Layout in the doc, but inverted. 
My suggestion is to create a setting for change the split orientation, so when I split it will prefer the left side. 
I would like to know, if is it possible ?

**Comment by kovidgoyal** [comment]
Again read the docs and do not post multiple issues/discussion asking the same thing.

**Comment by brunoferromega** [comment]
Sorry, I didn't the best channel for that.
