### ISSUE TITLE
Neovim becomes transparent when it has the same background color as Kitty

### ISSUE THREAD

**Issue by gmr458** [kovidgoyal/kitty#7563]
**Describe the bug**
When Neovim's background is set to the same color as Kitty's, Neovim becomes transparent, I'am using Neovim 0.10.0 without config file. Here is a video, you can see how when I use other colors the transparency disappears.

https://github.com/kovidgoyal/kitty/assets/53343401/256bd90c-c07f-484d-a334-95fbd1572372

I tried to reproduce the issue with Alacritty, Wezterm and Foot using the equivalent configurations, but only Kitty has this issue.

Alacritty:
https://github.com/kovidgoyal/kitty/assets/53343401/c7c827a7-80e0-42da-83e0-cd7dd445dc33

Wezterm:
https://github.com/kovidgoyal/kitty/assets/53343401/41fe9fc7-76f9-482c-b055-dee0880ba9f7

Foot:
https://github.com/kovidgoyal/kitty/assets/53343401/08f9ca86-13ab-4fab-a86f-e6383506d35f

**To Reproduce**
1. Open Kitty with this settings in the config file:
```
background #0e0e0e
background_opacity 0.9
```
The purpose of using `background_opacity` is to be sure whether Neovim becomes transparent or not.

2. Open Neovim without a configuration file and execute this command: `:hi Normal guibg=#0e0e0e`, this command sets the Neovim background to the color `#0e0e0e`, the same background used in Kitty's configuration.

**Environment details**
```
kitty 0.35.1 (1bfb1de7fc) created by Kovid Goyal
Linux fedora 6.8.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sun May 26 20:05:41 UTC 2024 x86_64
S
Kernel 6.8.11-200.fc39.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland (GNOME Shell 45.7) missing: preferred_scale
OpenGL: '4.6 (Core Profile) Mesa 23.3.6' Detected version: 4.6
Frozen: True
Paths:
  kitty: /home/gdmr/.local/kitty.app/bin/kitty
  base dir: /home/gdmr/.local/kitty.app/lib/kitty
  extensions dir: /home/gdmr/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /home/gdmr/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.9
font_size          20.0
Colors:
	background         #0e0e0e   

Important environment variables seen by the kitty process:
	PATH                                /home/gdmr/.local/kitty.app/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/gdmr/.composer/vendor/bin:/home/gdmr/.dotnet/tools
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                gdmr
	XDG_DATA_DIRS                       /home/gdmr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

**Comment by kovidgoyal** [comment]
This is by design: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.background_opacity
