### ISSUE TITLE
Kitten ssh keeps sessions established  even if you closed it.

### ISSUE THREAD

**Issue by mihailigoshin** [kovidgoyal/kitty#7567]
If I simply ssh to arbitrary ssh server once I kill the session (Ctrl+D, or exit) the session is actually closed. 
But If i use kitten ssh even if I Ctrl_D or exit session is still established. 

Screenshot illustrate that in begging there is no established session to server 10.189.112.186.
Then, ssh and close connection again no established session.
And in the end kitten ssh and then close the session but actually session is still established to 10.189.112.186. 

This is really annoying if you port forwarding for example with -D 1080. You can't reuse the port until you close kitty terminal itself. Closing the tab is not helping. 

![2024-06-20_23-27](https://github.com/kovidgoyal/kitty/assets/67579275/da30b2c4-a100-47e1-a13d-55091ba7c5ae)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.share_connections

**Comment by mihailigoshin** [comment]
This will kill every session. If you are logged into another servers this will kill those sessions as well. 

I've specifically gave as argument the ssh config with -F but disregard 

    ControlMaster
    ControlPath 
    ControlPersist

**Comment by kovidgoyal** [comment]
An option to not use shared connections doesnt kill anything. It simply doesnt use shared connections. And therefore no connection will persist after being closed.
