### ISSUE TITLE
Make resizing notification optional

### ISSUE THREAD

**Issue by FI3EI2** [kovidgoyal/kitty#7569]
Is it possible to make resizing notification optional with a config parameter?

https://github.com/kovidgoyal/kitty/blob/581db0ab7ab5e26d3e9ac084c6d6ee2b010f9359/kitty/child-monitor.c#L809

Thanks in advance.

**Comment by kovidgoyal** [comment]
No, it isnt. How else are you supposed to know how many cells the new
window size will use
