### ISSUE TITLE
Ability to specify icon at startup

### ISSUE THREAD

**Issue by YoloClin** [kovidgoyal/kitty#757]
I have keybinds to open terminals in various states (standard user, root, ssh to remote systems etc). Would it be possible to set the kitty icon at startup so I can specify specific icons for specific terminals? 

Thanks!

**Comment by kovidgoyal** [comment]
On what OS? As far as I know macOS reads the icon from the bundle statically. It's likely possible on X11, but no idea about wayland. But for your actual use case, i'd suggest using different color schemes instead, which you can specify on the kitty command line with either the --config option (and use includes to include common config) or use the --override option to set the colors directly. Those are far more visually noticeable than icons.

**Comment by YoloClin** [comment]
Linux/X11 - color schemes work inside the terminal, but not alt/tab menus, but thankyou for the suggestion :)
