### ISSUE TITLE
Please implement the 'install' target

### ISSUE THREAD

**Issue by yurivict** [kovidgoyal/kitty#759]
I've built it, but 'install' isn't implemented. How can I install it?

**Comment by kovidgoyal** [comment]
You do not need to install. It runs in place.

**Comment by yurivict** [comment]
'install' is needed to create a package.

**Comment by kovidgoyal** [comment]
Instructions for creating a package are on the page with the instructions for building from source

**Comment by yurivict** [comment]
With 'install' target such instructions aren't even needed.

**Comment by kovidgoyal** [comment]
I dont want people creating zero effort kitty packages. Somebody creating a kitty package should be aware of how kitty is designed to work and at least take the time to read two paragraphs of text.
