### ISSUE TITLE
Set text background opacity

### ISSUE THREAD

**Issue by ursuscamp** [kovidgoyal/kitty#7592]
**Is your feature request related to a problem? Please describe.**
I would like to set a partially transparent text background so that I can partially see the background image behind Neovim.

**Describe the solution you'd like**
Wezterm has a feature called `text_background_opacity` with applies a partial transparency to text background colors. It would be nice if a setting like this existed.

If there is some combination of config options which allows this, I have no found them yet. Thanks.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.background_opacity

**Comment by ursuscamp** [comment]
Sorry if I am being dense, but I have read through that option and fiddled with it, but I don't think it does what I am asking.

AFAICT that setting changes the OS window opacity. What I am referring to is the text background opacity specifically. What I would like to be able to do is:

1) Set a background image in kitty
2) Use a color scheme in neovim with a background color, but see the background image partially opaque through the editor's background color.

If this possible with `background_opacity` I don't see how.

Thanks.

**Comment by kovidgoyal** [comment]
yes make your image the desktop background and use background_opacity.
Make sure your neovim background color is the same color as the terminal
background color and it will be semi transparent.
