### ISSUE TITLE
Resizing kitty window: resize message is doubled

### ISSUE THREAD

**Issue by bjd-pfq** [kovidgoyal/kitty#7595]
Resizing kitty window: resize message is doubled

A picture paints a thousand words:
![screenshot-20240704-233603](https://github.com/kovidgoyal/kitty/assets/3042621/7c1aba02-87c6-4c0c-a3cf-51bcdde1126a)

kitty --version
kitty 0.21.2 created by Kovid Goyal

grep -v '^#' /home/bjd/.config/kitty/kitty.conf | sed '/^$/d'
font_family     LiterationMonoNerd Font
font_family LiterationMono Nerd Font Mono Italic
italic_font LiterationMono Nerd Font Mono Italic
font_size 12.0
disable_ligatures always
font_features none
cursor #5FDEBB
cursor #800000
cursor_blink_interval 1
scrollback_lines 2000
detect_urls yes
select_by_word_characters @-./_~?&=%+#:
click_interval 0.5
default_pointer_shape arrow
mouse_map right triplepress grabbed,ungrabbed new_tab
enable_audio_bell yes
visual_bell_duration 0
remember_window_size  yes
draw_minimal_borders yes
window_padding_width 0 1 0 2
resize_draw_strategy size
resize_in_steps yes
tab_bar_edge top
tab_bar_margin_height 0.8 0.5
tab_bar_style powerline
active_tab_background   #ffffff
active_tab_foreground   #800000
active_tab_font_style bold-normal
inactive_tab_background #d4d4d4
inactive_tab_font_style normal
foreground #000000
background #E9FDFB
background_image_layout scaled
selection_foreground #ffffff
selection_background #0476DF

**Comment by kovidgoyal** [comment]
update kitty
