### ISSUE TITLE
Using env variables in kitty.conf

### ISSUE THREAD

**Issue by Momen-MKadry** [kovidgoyal/kitty#7596]
Hey, I want to have my terminal's theme to be different accrding to my window manager, for more context I have BSPWM and hyprland and each has a rice that uses kitty, each rice contains different themes with different colors for the terminal, here is how the part I want to change look

```
include theme.conf
```

i tried doing a condition like this

```
include ${XDG_CURRENT_DESKTOP}.conf

x=$XDG_CURRENT_DESKTOP

if [[ $x = "bspwm" ]]
  then
    themeFile="current-theme.conf"
elif [[ $x = "hyprland" ]]
  then
    themeFile="theme.conf"
fi

include themeFile

```
`current-theme.conf` is BSPWM's file, `theme.conf` is hyprland's

Doing this, it doesn't load either file. Just the default kitty theme

Is there something I am doing wrong or is it not possible to do this?

**Comment by kovidgoyal** [comment]
kitty's config file is not a shell script. You can use env vars for
conditional includsion in include directives as described in https://sw.kovidgoyal.net/kitty/conf/
