### ISSUE TITLE
What's up with my bold "pp".  It is rendered in a weird and squished way.

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#7598]
**Describe the bug**
The letter 'pp' is rendered in a weird and squished way when it is bold.

**To Reproduce**
```
#shell /bin/zsh --login
startup_session ~/.config/kitty/kitstart.conf
allow_remote_control yes
kitty_mod cmd

# Do not accidentally close:
#map kitty_map+b no_op

# Font stuff
bold_font           PragmataPro Mono Liga Bold
bold_italic_font    PragmataPro Mono Liga Bold Italic
italic_font     PragmataPro Mono Liga Italic
#font_family        PragmataPro Mono Liga Regular
font_family PragmataProMonoLiga Nerd Font Mono Regular

font_size 17
text_composition_strategy platform
macos_colorspace srgb
shell_integration enabled
```

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/Hi5S2Tf)

kitty v0.35.2

**Comment by kovidgoyal** [comment]
Your font's bold face does not have compatible metrics with its regular face. Either use a font that is has actual monospace bold/italic faces or uses modify_font in kitty.conf to increase cell width to fit the bold face.

**Comment by esn89** [comment]
Thank you.  That has fixed my pp.
