### ISSUE TITLE
Full paths of the build directory are found in .pyc files

### ISSUE THREAD

**Issue by yurivict** [kovidgoyal/kitty#760]
These paths should never be encoded in the binaries:

```
Error: 'lib/kitty/kitty/conf/__pycache__/definition.cpython-36.pyc' is referring to /usr/ports/x11/kitty/work-py36/stage
Error: 'lib/kitty/kitty/conf/__pycache__/__init__.cpython-36.pyc' is referring to /usr/ports/x11/kitty/work-py36/stage
Error: 'lib/kitty/kitty/conf/__pycache__/utils.cpython-36.pyc' is referring to /usr/ports/x11/kitty/work-py36/stage
Error: 'lib/kitty/kitty/fonts/__pycache__/core_text.cpython-36.pyc' is referring to /usr/ports/x11/kitty/work-py36/stage
Error: 'lib/kitty/kitty/fonts/__pycache__/__init__.cpython-36.pyc' is referring to /usr/ports/x11/kitty/work-py36/stage
```

**Comment by kovidgoyal** [comment]
That is how python works. https://stackoverflow.com/questions/11191680/why-do-python-pyc-files-contain-the-absolute-path-of-their-source-code

You can work around it by not copying the pyc files during your install step and instead generate the files after they have been copied to their install location (see the docs for the python compileall module). 

And how to specifying the staging directory is documented on the build page. If it's unclear feel free to ask.

**Comment by yurivict** [comment]
Here https://sw.kovidgoyal.net/kitty/ it only talks about pre-built binaries.
On the github page there's nothing about build: https://github.com/kovidgoyal/kitty
Where's 'build page'?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/build.html
