### ISSUE TITLE
Fish shell auto-completion does not work on OpenBSD (access via SSH from macOS)

### ISSUE THREAD

**Issue by nalzok** [kovidgoyal/kitty#7602]
**Describe the bug**
Fish shell auto-completion does not work on OpenBSD (access via SSH from macOS). This is probably because `kitten` is not installed as an executable on OpenBSD via [the x11/kitty port](https://openports.pl/path/x11/kitty).

**To Reproduce**
<pre lang="fish">
$ ssh -X qys@192.168.1.60
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
> doas pkg_add kitty
quirks-7.14 signed on 2024-07-03T17:56:08Z

> kitty <b>(Press Tab for auto-completion)</b> fish: Unknown command: kitten
~/.local/share/kitty-ssh-kitten/shell-integration/fish/vendor_completions.d/kitty.fish (line 4): 
    printf "%s\n" $tokens $ct | command kitten __complete__ fish | source -
                                        ^~~~~^
in function '__ksi_completions'
in command substitution

> kitten
fish: Unknown command: kitten
</pre>

**Screenshots**
<img width="1528" alt="image" src="https://github.com/kovidgoyal/kitty/assets/13443062/dd8a82c5-361a-4345-a369-17c78207d744">

**Environment details**
```
kitty 0.35.1 created by Kovid Goyal
Darwin Qingyaos-MBP 21.6.0 Darwin Kernel Version 21.6.0: Wed Apr 24 06:02:02 PDT 2024; root:xnu-8020.240.18.708.4~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.7.5 BuildVersion:	21H1222
OpenGL: '4.1 INTEL-18.8.16' Detected version: 4.1
Frozen: False
Paths:
  kitty: /Applications/MacPorts/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/MacPorts/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/MacPorts/kitty.app/Contents/Resources/kitty/kitty
  system shell: /opt/local/bin/fish
Loaded config files:
  /Users/qys/.config/kitty/kitty.conf

Config options different from defaults:
font_family   PragmataPro Mono Liga
font_features:
{'PragmataProMonoLiga-Regular': ('+calt', '+cv03')}
font_size     16.0
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /Applications/MacPorts/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/local/bin/fish
	DISPLAY                             /private/tmp/com.apple.launchd.VQEfQr9siC/org.xquartz:0
	USER                                qys
	LC_CTYPE                            UTF-8
```

**Additional context**

Pinging @rfht who seems to be the maintainer of the [OpenBSD port](https://github.com/openbsd/ports/commit/c4042bd0e5517a145d92654aab1b826418565713). By the way, `0.26.5p1` looks pretty old, could you please update it to the version?

```fish
$ cat ~/.config/kitty/kitty.conf
font_family         PragmataPro Mono Liga
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size           16.0
font_features       PragmataProMonoLiga-Regular +calt +cv03
```

**Comment by kovidgoyal** [comment]
I have no control over what OpenBSD chooses to package. Simply do

kitten ssh your-openbsd-machine

to connect to it and kitten will then be available.

**Comment by nalzok** [comment]
Thanks, it's good to know that I don't need to install `kitty` on the remote OpenBSD host. However, `kitten` is not available on the remote host for some reason, even if I access it via `kitten ssh`

```
$ kitten ssh qys@192.168.1.60
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
qys@sentinel ~> kitten
fish: Unknown command: kitten
```

I also tried `kitty +kitten ssh`, but that didn't work either. (What's the difference between `kitten` and `kitty +kitten`?)

```
$ kitty +kitten ssh qys@192.168.1.60
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
qys@sentinel ~> kitten
fish: Unknown command: kitten
```

**Comment by kovidgoyal** [comment]
Then install the binary yourself, pre-compiled static kitten binaries
are available for every unix like platform under the sun on the download
page.

**Comment by nalzok** [comment]
Just to check, is there a bug in `kitten ssh` that caused its failure to install `kitten` on the remote host? How does that work: do you download a pre-compiled static binary based on the remote machine's operating system?

Also, looks like the pre-compiled static binary for OpenBSD does not work:
```
> uname -a
OpenBSD sentinel.lan 7.5 GENERIC.MP#82 amd64

> wget https://github.com/kovidgoyal/kitty/releases/download/v0.35.2/kitten-openbsd-amd64
...
2024-07-07 00:28:17 (5.27 MB/s) - ‘kitten-openbsd-amd64’ saved [15470872/15470872]

> file kitten-openbsd-amd64 
kitten-openbsd-amd64: ELF 64-bit LSB executable, x86-64, version 1

> chmod a+x kitten-openbsd-amd64 

> ./kitten-openbsd-amd64 
kitten-openbsd-amd64:./kitten-openbsd-amd64: undefined symbol 'syscall'
ld.so: kitten-openbsd-amd64: lazy binding failed!
fish: Job 1, './kitten-openbsd-amd64' terminated by signal SIGKILL (Forced quit)

[SIGKILL]> 
```

**Comment by kovidgoyal** [comment]
On Sat, Jul 06, 2024 at 09:35:52PM -0700, Qingyao Sun wrote:
> Just to check, is there a bug in `kitten ssh` that caused its failure to install `kitten` on the remote host? How does that work: do you download a pre-compiled static binary based on the remote machine's operating system?

Not that I know of. And no it doesnt download anything, until you
actually try to run kitten.

>
> Also, looks like the pre-compiled static binary for OpenBSD does not work:
> ```
> > uname -a
> OpenBSD sentinel.lan 7.5 GENERIC.MP#82 amd64
>
> > wget https://github.com/kovidgoyal/kitty/releases/download/v0.35.2/kitten-openbsd-amd64
> ...
> 2024-07-07 00:28:17 (5.27 MB/s) - ‘kitten-openbsd-amd64’ saved [15470872/15470872]
>
> > file kitten-openbsd-amd64
> kitten-openbsd-amd64: ELF 64-bit LSB executable, x86-64, version 1
>
> > chmod a+x kitten-openbsd-amd64
>
> > ./kitten-openbsd-amd64
> kitten-openbsd-amd64:./kitten-openbsd-amd64: undefined symbol 'syscall'
> ld.so: kitten-openbsd-amd64: lazy binding failed!
> fish: Job 1, './kitten-openbsd-amd64' terminated by signal SIGKILL (Forced quit)
>
> [SIGKILL]>

Then that would be a bug in Go's stdlib on OpenBSD. Sadly I know nothing
about OpenBSD, so I cant help you with that. From the error message
OpenBSD's libc is apparently missing syscall.

**Comment by voutilad** [comment]
OpenBSD no longer allows indirect system calls via `syscall(2)`: https://github.com/openbsd/src/commit/cafeb892b121ee89c39c2b940e8ccd6950f50009

For more details, see this announcement https://marc.info/?l=openbsd-tech&m=170647326029909&w=2

In short, Go has traditionally needed some changes to work with OpenBSD given its history of trying to avoid using libc. A lot of fixes and patches have been landing, but chances are you need to rebuild with a newer version of Go.

**Comment by nalzok** [comment]
Thanks @voutilad. Are you aware of any document/issue to track the status of Go's support for OpenBSD? A quick Google search reveals [Go 1.16 will make system calls through libc on OpenBSD](https://utcc.utoronto.ca/~cks/space/blog/programming/Go116OpenBSDUsesLibc), but apparently even Go 1.22 is still not enough. I'm curious what are the missing pieces.

**Comment by voutilad** [comment]
@4a6f656c might have an idea as they do a lot of work upstreaming OpenBSD patches for Go. I know we removed the `syscall` syscall itself. I think that's probably the issue in this case.

**Comment by 4a6f656c** [comment]
> Thanks @voutilad. Are you aware of any document/issue to track the status of Go's support for OpenBSD?

@nalzok - Go is fully supported on OpenBSD across most platforms - 1.22.x runs and passes all tests on OpenBSD 7.5 (you'll find it in ports, Go -tip also works). Most challenges result from the use of older versions of packages such as golang.org/x/sys/unix, or code that is doing things that are out of the ordinary/no longer workable on newer OpenBSD.

**Comment by 4a6f656c** [comment]
> Then that would be a bug in Go's stdlib on OpenBSD. Sadly I know nothing about OpenBSD, so I cant help you with that. From the error message OpenBSD's libc is apparently missing syscall.

OpenBSD 7.5 removed the `syscall` system call - working binaries would need to be built with Go 1.22 from OpenBSD ports, or with Go 1.23rc1+ for cross build.

**Comment by nalzok** [comment]
Hi @kovidgoyal, I asked on the [OpenBSD mailing list](https://marc.info/?t=172038600300002&r=1&w=2) about the issue, and someone commented the following. The point is that "it isn't an issue with the Go version used to compile", but "Kitty uses syscalls in a way which OpenBSD no longer supports".

The commenter also shared some pointers on how this can be fixed. Please take a look!

> OpenBSD recently changed access to its syscalls.
> The change which allows upstream Go to build working executables
> for current OpenBSD was committed on May 4th.
> https://github.com/golang/go/commit/8841f50d98b224ecf5ee27d9b7e6f18ad2c98e46
> 
> The kitty binary was built by Go version 1.22.4.
> $ strings kitten-openbsd-amd64 | grep go1
> ...
> go1.22.4
> 
> Go 1.22.4 was released June 4th.
> https://go.dev/doc/devel/release#go1.22.0
> 
> It isn't an issue with the Go version used to compile.
> The change was upstreamed two months ago, and the Go version used
> was released one month ago.
> 
> It's an issue with kitty itself.
> $ git clone https://github.com/kovidgoyal/kitty .
> $ grep -r syscall *
> ...
> kittens/transfer/receive.go:func syscall_mode(i os.FileMode) (o uint32) {
> kittens/transfer/receive.go:			if err := unix.Fchmodat(unix.AT_FDCWD, self.expanded_local_path, syscall_mode(self.permissions), unix.AT_SYMLINK_NOFOLLOW); err == nil || !(errors.Is(err, unix.EINTR) || errors.Is(err, unix.EAGAIN)) {
> kittens/transfer/send.go:	"syscall"
> kittens/transfer/send.go:	stat, ok := stat_result.Sys().(*syscall.Stat_t)
> kittens/transfer/send.go:				stat, ok := st.Sys().(*syscall.Stat_t)
> ...
> 
> Kitty uses syscalls in a way which OpenBSD no longer supports.
> Send the maintainer of Kitty to look at this code:
> https://github.com/golang/go/blob/master/src/syscall/syscall_openbsd_libc.go#L19
> If they're willing to do the work, they'll have enough information
> to figure out how to fix the software.

**Comment by kovidgoyal** [comment]
What on earth. None of those are actual calls to syscall in kitty code. One is a call to Fchmodat and the other is a conversion of a result of a stat() call. 

If OpenBSD wants to make their platform hostile to all binaries by willy nilly removing functions from their libc, that's their lookout.

**Comment by nalzok** [comment]
Another person replied to that message and they seems to agree with you: https://marc.info/?l=openbsd-bugs&m=172042567722078&w=2. Anyway, I'll try to build `kitten` on OpenBSD myself and see if that works.

**Comment by kovidgoyal** [comment]
There was indeed one use of syscall left in kitty code, now replaced: https://github.com/kovidgoyal/kitty/commit/e45d518082b38ccfe9e5c59237d0d01cb5709c5a

So whenever Go 1.23 is released and kitty is updated to use it, this issue *should* be fixed.
