### ISSUE TITLE
Progressive Enhancement flag stack may leak on SSH connection drop

### ISSUE THREAD

**Issue by krobelus** [kovidgoyal/kitty#7603]
(Not yet sure where's the right place to resolve this issue, feel free to close)

If my process tree is

    fish1 -> ssh -> fish2

fish2 (as of latest master) pushes progressive enhancement flags.

Now if the connection drops, fish2 doesn't have a chance to clean up.
Subsequent invocations of `bash` will have broken keybindings.

It's a general problem that a drop of connection can leave the terminal in a weird state (leave bracketed paste on etc.), ideally we can find a general solution.
It's probably not an absolute show-stopper because the workaround is obvious (restart the terminal) but it would be good to fix.

## Possible solution 1:

On exit, `ssh` could run the equivalent of NCurses's `reset`.
I'll look into why it doesn't, probably ask OpenSSH folks.

## Possible solution 2:

1. On startup, `ssh` shall query and record the current size of the flag stack (let's say `CSI ?? u`)
2. On exit, `ssh` shall truncate the flag stack to the recorded size (perhaps `CSI == 123 u`)

One potential problem with 1 is that it requires `ssh` to do a timed read to read back the stack size, which might not be acceptable.

This implies that SSH should also reset bracketed paste and others on exit.

## Possible workaround:

Instead of using the stack, fish could always set the progressive enhancement flags outright.
This is not great because it won't work for other parent processes like `bash -> ssh -> fish`.

---

(A similar issue exists when a program crashes after pushing flags, though that's less important.)

A related issue is that when reconnecting and re-attaching `tmux`, the programs running inside of it will not re-initialize flags immediately.
For fish, this issue is probably not so bad because it will set flags after each command.

Originally reported at https://github.com/fish-shell/fish-shell/pull/10603
Programs using [crossterm](https://github.com/crossterm-rs/crossterm) suffer from the same problem (they expose PushKeyboardEnhancementFlags and PopKeyboardEnhancementFlags).

**Comment by kovidgoyal** [comment]
It is generally the case that when a terminal program crashes (a
connection drop is basically a less severe form of this) the terminal
state is undefined. There is no general solution to this, terminal state
includes a whole bunch of things, not just the keyboard mode, most of
those things dont even have a stack.

The only solution (or rather workaround) for this is to reset the
terminal, which you can do in kitty by either running reset (or if the
state is so bad that you cant run a command, pressing ctrl+shift+delete).

The terminal cant really fix this issue since it has no way to know if a
state is the result of a crash/connection drop/other exceptional
circumstance or deliberately changed.

Shells should in general always push the keyboard state they want just
before drawing the prompt and pop it just before relinquishing the
terminal to a child process. That fixes corrupted state for the shell
itself, but not for commands that the shell will run since they will
inherit the state left by the previous command. I would argue this is
desired behavior, it allows a user to change the state with a command
and then use that state on subsequent commands.

**Comment by kovidgoyal** [comment]
Oh and I closed the issue since as far as I can see there isnt anything
a terminal can do here, but feel free to discuss further.

**Comment by krobelus** [comment]
> Shells should in general always push the keyboard state they want just
> before drawing the prompt and pop it just before relinquishing the
> terminal to a child process.
> That fixes corrupted state for the shell itself, but not for commands
> that the shell will run since they will inherit the state left by the
> previous command.

Right.

> I would argue this is desired behavior, it allows a user to change the
> state with a command and then use that state on subsequent commands.

Ok so with a CSI u aware shell that works like that (and uses flags 5 for
this example), this is how one can recover:

	ssh host "printf '\x1b[>9u'"
	# now the stack is [9, 5]
	bash
	# now the stack is [9]
	printf '\x1b[=0u'
	# now keyboard input works again in bash

It looks like the last printf command actually modifies the top of the stack,
because "exit" followed by "bash" will still work. I'm a bit surprised but
I guess this is good.

---

I asked on the [OpenSSH mailing list] (https://marc.info/?l=openssh-unix-dev&m=172036211030598&w=2),
it sounds like there are reasons to keep things as they are
and let the user run "reset" if needed.

**Comment by kovidgoyal** [comment]
Yes and in general I expect this issue to become less severe over time. Hopefully someday all actively maintained shells will support or at least understand/recognize the full kitty keyboard protocol so even if the state gets corrupted they will be capable of decoding key events, thereby allowing the user to use the reset command.

**Comment by krobelus** [comment]
I wonder though if there is any real advantage to having the stack?
The applications that I know about already want to reset all requisite flags whenever they acquire or relinquish ownership of the terminal, so the stack doesn't add much

**Comment by kovidgoyal** [comment]
On Mon, Jul 08, 2024 at 05:15:47AM -0700, Johannes Altmanninger wrote:
> I wonder though if there is any real advantage to having the stack?

It allows, for example, shells to leave the state to be whatever the
last command set it to when running the next command.

**Comment by krobelus** [comment]
> > I wonder though if there is any real advantage to having the stack?
> It allows, for example, shells to leave the state to be whatever the
> last command set it to when running the next command.

I'm struggling to find a use case where the stack is particularly useful.
I guess it allows power users to run

	$ printf '\x1b[=9u'
	$ bash

to have protocols enabled in bash. The workaround would be

	$ printf '\x1b[=9u'; bash


If we weigh this inconvenience against the confusion created by our original
scenario here:

	$ fish
	$ ssh somehost fish
	(disconnect)
	$ bash # or some ncurses application etc
	(keyboard shortcuts are broken)

I'd say that it's more important to fix the latter scenario because that
one can be realistically hit by casual users who don't even know about
these protocols.

The fix would be to make fish not push to or pop from the stack but set the
flags directly.

I agree that we should encourage terminal apps to decode CSI u but that's
gonna take a while.
