### ISSUE TITLE
Broken text rendering when I leave Kitty running for days on end

### ISSUE THREAD

**Issue by melodyogonna** [kovidgoyal/kitty#7614]
**Describe the bug**
I really don't understand what could be causing the problem, but I see this broken rendering after using Kitty extensively for days.

**Screenshots**
<img width="1280" alt="Screen Shot 2024-07-08 at 19 17 47" src="https://github.com/kovidgoyal/kitty/assets/24739630/3e33f706-8524-4048-b73d-fe9e172bbbc4">

**Environment details**
```
MacOS 12.7.5
Kitty 0.33.1
```

**Additional Context**
I have encountered this problem twice in the months I have used Kitty, both times I had to restart my computer to fix it, closing Kitty and opening it again does not work (or I might be doing it incorrectly).

**Comment by kovidgoyal** [comment]
update kitty
