### ISSUE TITLE
I cannot use the option key on Mac to perform functions inside Neovim when using Kitty. How can I use the option key?

### ISSUE THREAD

**Issue by ugotuan** [kovidgoyal/kitty#7615]
Ex: i want use option+j but it isn't work.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt

**Comment by ugotuan** [comment]
in kitty.conf
`macos_option_as_alt no`

in keymap.lua
`keymap.set("n", "<M-j>", ":MoveLine(1)<CR>", opts)`

but it isn't work, i tried it on Alacritty, it's work

**Comment by kovidgoyal** [comment]
u want

macos_option_as_alt yes

**Comment by ugotuan** [comment]
Thank you so much! @kovidgoyal

**Comment by wojciech-kulik** [comment]
FYI: This option requires Kitty to be restarted :).
