### ISSUE TITLE
Bash script display issue

### ISSUE THREAD

**Issue by erickmufath** [kovidgoyal/kitty#7616]
**Describe the bug**
\n on script also displayed and not doing new line

**To Reproduce**
sh start.sh

**Screenshots**
![17205839643733616462605447704873](https://github.com/kovidgoyal/kitty/assets/90117993/7cfccad2-8966-46a8-ba91-f2b2c44a7cda)

**Comment by kovidgoyal** [comment]
This has nothing to with the terminal. Debug your bash script and if it isnt working as you expect, report the issue to bash.

**Comment by erickmufath** [comment]
> This has nothing to with the terminal. Debug your bash script and if it isnt working as you expect, report the issue to bash.

Bash script in other terminal: spesifically termux with "\n" will doing new line. Is there nothing to do?

**Comment by kovidgoyal** [comment]
Terminals dont run bash scripts, the bash interpreter does that.
