### ISSUE TITLE
Mappable action for modify_font (cell_height)

### ISSUE THREAD

**Issue by raffaem** [kovidgoyal/kitty#7617]
**Is your feature request related to a problem? Please describe.**
I would like a keyboard shortcut to change cell height

**Describe the solution you'd like**
A mappable action for cell height

There is a [config option](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font) but there seems to be no [mappable action](https://sw.kovidgoyal.net/kitty/actions/)

**Describe alternatives you've considered**
A script that changes it in the config file and then sends SIGUSR1 to kitty

**Comment by kovidgoyal** [comment]
map f1 remote_control load-config --override modify_font=whatever

**Comment by raffaem** [comment]
I don't think this allows to increase or decrease the cell height, but only to set it at a specified height?

```
map kitty_mod+n remote_control load-config --override modify_font="cell_height -20px"
```

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font
