### ISSUE TITLE
AutoKey send_keys to kitty not working as expected 

### ISSUE THREAD

**Issue by marsjane** [kovidgoyal/kitty#7620]
**Describe the bug**
the autokey send_keys seems send keys but the key not received properly in kitty, the same config works fine in other terminals

**To Reproduce**
1. install autokey with `yay -S autokey-git`
2. in autokey, add a script as follows:
```
# Enter script code
import time
time.sleep(0.2)
keyboard.send_keys("<ctrl>+b")
keyboard.send_keys("1")
```
then set the hotkey as sth you want, for example `super+1`
3. go to kitty, open a tmux session, create several windows, you can try manually `<ctrl>+b` then `1`, it should works fine to switch windows to window `1`, then you try to use the shortcut `super+1`, I can see the `b1` shown in the current windows, but the window doesn't switch. 
4. You can try on other terminal, I tested in alacritty it works fine, so I wonder how I can let it work in kitty

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I have no clue what autokey does, probably some awful hackery with
XTEST. If you want to send keystrokes to kitty use the kitty remote
control facility it is designed to do this robustly and flexibly.
