### ISSUE TITLE
`U+2500` not being repeated on `glances`

### ISSUE THREAD

**Issue by Neved4** [kovidgoyal/kitty#7622]
First, thank you so much for Kitty! 🤍 It's an amazing term.

Second, recently was fighting `glances` to make it render its horizontal dividers nicely across other terminals. Did [glances/PR#2867](https://github.com/nicolargo/glances/pull/2867) to try fix [glances/#2866](https://github.com/nicolargo/glances/issues/2866) and [glances#2817](https://github.com/nicolargo/glances/issues/2817)

Basically, `glances` uses `curses` and they were resorting to an uncommon char. Replacing with a more common one fixed it for iTerm but not Kitty, where the char is only displayed once instead of repeating till the end of the line.

Maybe this isn't Kitty's fault, I'm ignorant here. Not sure whether https://github.com/kovidgoyal/kitty/issues/6978 or others could be related.

Let me know if this is best sorted upstream, insight welcome.

---

### Describe the bug
`glances`'s horizontal dividers to display incorrectly

### To Reproduce

1. Start `glances` normally.
2. Observe the output in `kitty`.
3. Notice `U+2500` not being repeated till the end of line.

### Screenshots

Expected output (`Terminal.app`):
![Terminal.app](https://github.com/kovidgoyal/kitty/assets/63655535/7c1318d9-4f3f-4aac-a43a-b1646c376093)

Kitty's output:
![Kitty](https://github.com/kovidgoyal/kitty/assets/63655535/670cd7cd-e658-4df5-aaf6-d2d8ac13db22)

### Environment details

```
kitty 0.35.2 (ad328bfeaa) created by Kovid Goyal
Darwin 17-1.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		14.5 BuildVersion:		23F79
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Little Snitch.app/Contents/Components:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/kitty.app/Contents/MacOS
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                Neved4
```

### Additional context

Can reproduce with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
I'm not going to debug glances, don't have that kind of time. In general
you can test if kitty is rendering that character correctly using

printf '\u2500\u2500\u2500'

which works fine for me. If it doesn't for you then I can look into it.
Run kitty with --debug-font-fallback and it will show you what font it
is falling back to for that character.

Alternately, you can attach a simple python script to demonstrate the
issue using the stdlib curses module and I will look at that as well.

And while I am here, let me just say on a general note, I strongly
recommend not using curses, it's horrible.

**Comment by Neved4** [comment]
@kovidgoyal First time with curses, got this:

```py
#!/usr/bin/env python3

import curses

def draw_lines(stdscr):
    stdscr.clear()
    height, width = stdscr.getmaxyx()
    char = '\u002d' * (width - 1)
    stdscr.addstr(0, 0, char)
    char = '\u2500' * (width - 1)
    stdscr.addstr(1, 0, char)
    stdscr.addstr(2, 0, ' ' * (width - 1))
    stdscr.refresh()
    stdscr.getch()

curses.wrapper(draw_lines)
```

*Press any key to exit.

Kitty's output (with `--config NONE`):
![Kitty](https://github.com/user-attachments/assets/90117202-3bf3-48f6-9d84-4a9f1e3dc34d)

macOS Terminal.app (for reference):
![Terminal.app](https://github.com/user-attachments/assets/fb5318ee-f27b-4d24-8f38-237ac37f8a4a)

**Comment by kovidgoyal** [comment]
That's a bug in macOS ncurses, it is not sending the draw command for the U+2500 line, easily checked by running kitty with --dump-commands.

And note that to draw lines using curses the correct way is to use the dedicated ncurses functions for it, in your case:

```py
    stdscr.hline(1, 0, curses.ACS_HLINE, width-1)
```

**Comment by Neved4** [comment]
Fixed this upstream using `window.hline()`

Props to Kovid Goyal! Cheers to him for helping me figure things out,
despite me cluelessly bringing up an issue unrelated to Kitty.

Thanks a ton!

**Comment by kovidgoyal** [comment]
You're welcome!
