### ISSUE TITLE
kitty selection mouse-drag not working or behaving erratically (video proof)

### ISSUE THREAD

**Issue by bjd-pfq** [kovidgoyal/kitty#7624]
**Describe the bug**
kitty selection mouse-drag on Linux Mint 21.3 does not work at all or works erratically when mouse leaves Kitty window
![screenshot-20240710-035705](https://github.com/user-attachments/assets/a364b9a9-6e79-4929-acea-b3eb845e6ee5)

https://github.com/user-attachments/assets/fee16d55-f41d-4adb-b709-75030567d027

https://github.com/user-attachments/assets/5a3b0cca-1339-4543-b3e4-7d87dd3f5af1

https://github.com/user-attachments/assets/544a6583-1155-4bb7-aaca-73d8eb2a52c7

**To Reproduce**
See videos provided.

provided:
- worksheet image with differences in behavior between Kitty, Gnome-terminal and Tilix.
- three videos:

1. selection under Kitty 0.35.2 with Mint Cinnamon "Window Focus Follows Mouse" plus "Window Autoraise" set to true; note that in the video the first three selection attempts stop as soon as the mouse leaves the Kitty window (and note that the selection is LOST, even though a section of the screen remains highlighted); note how the 4th attempt in the video works, but only because the mouse did not leave the window;  note how attempts 5 and 6 work; note how the remainder of the attempts do not work.

2. video of the selection under Tilix; all selection operations work, and work reliably

3. video of selection under Kitty working ONLY when window focus is set to "On Mouse Click" (and implicitly with "Window Autoraise" OFF). In the videos I have started a small script to dump the contents of the three selection mechanisms XA_PRIMARY, XA_SECONDARY and XA_CLIPBOARD. (please note --although not material to this bug report) that under Tilix I had and option set  ON to keep XA_CLIPBOARD in sync with XA_PRIMARY).

Insofar as erratic behavior is reproducible, see videos/

**Screenshots**
See image and videos.

**Environment details**

Particulars:

Using Kitty nightly build from July 4th (Kitty 0.35.2)

```
$> uname -a
Linux skyscraper 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


$> lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia


$> grep -v -e '^#' -e '^$' ~/.config/kitty/kitty.conf
font_family			Bitstream Vera Sans Mono Oblique
bold_font			Bitstream Vera Sans Mono Bold Oblique
bold_italic_font	Bitstream Vera Sans Mono Bold Oblique
italic_font			Bitstream Vera Sans Mono Oblique
font_size 12.0
disable_ligatures never
cursor #800000
click_interval 0.5
focus_follows_mouse yes
pointer_shape_when_grabbed arrow
default_pointer_shape beam
pointer_shape_when_dragging hand
mouse_map right triplepress grabbed,ungrabbed new_tab
window_padding_width 0 1 0 2
single_window_padding_width 0 1 0 2
window_logo_path ~/.themes/current/gtk-3.0/apps/BabyGnuAlpha.png
resize_in_steps yes
tab_bar_edge top
tab_bar_margin_height 0.8 0.5
tab_bar_margin_height 1.0 1.0
tab_bar_style powerline
tab_fade 0.25 0.5 0.75 1
tab_powerline_style angled
tab_title_template "{index}: {tab.active_wd}"
active_tab_background	#ffffff
active_tab_foreground	#2978FF
active_tab_font_style	bold
inactive_tab_background	#d4d4d4
inactive_tab_foreground	#000000
inactive_tab_font_style	bold
tab_bar_background #ACC0E5
tab_bar_margin_color #2978FF
foreground #000000
background #E9FDFB
background_image_layout scaled
selection_foreground #ffffff
selection_background #0476DF


cat ~/bin/dump-selections
#!/bin/bash

while true
do
	d="$(date +%Y%m%d-%H%M%S)"
	echo "-------[ $d ]-------"
	echo -en "XA_PRIMARY:	"; xsel -p; echo
	echo -en "XA_SECONDARY:"; xsel -s; echo
	echo -en "XA_CLIPBOARD:	"; xsel -b; echo

	echo
	sleep 2
done
```

**Comment by kovidgoyal** [comment]
dup of #7381

**Comment by bjd-pfq** [comment]
Not a dup at all (an I'm not using Wayland). The behavior is totally different. You are closing real bugs too soon. Anyway, the misbehavior is persistent. But I won't be bugging you again.

**Comment by kovidgoyal** [comment]
Sigh, the fix was not wayland specific and was precisely to do with your scenario of focus being transferred from one OS window to another in the middle of a drag. But yes, please dont bug me again, my life is too short to deal with bug reports from people that think they know what an issue is better than maintainers and dont even bother to provide the information asked for in the issue template.

**Comment by bjd-pfq** [comment]
Says a maintainer who, after having been issued a new bug report, wastes all of 18 hours to not ask for clarification, not for additional information, but to rush out a hurried "cannot replicate" and "closed bug" mail before the issuer can even begin to clarify.

My friend, "cannot replicate" does not mean your bugs aren't real. I have found a few others, as real as my earlier ones, but I have decided to ditch Kitty until such time as you start treating your bug reporters with a bit more respect and take them seriously, and of course you fixed the major showstoppers to which you yourself remain blind.

"Cannot replicate, bug closed" is not the way to stamp out bugs, it is a way to get shiny statistics.

**Comment by kovidgoyal** [comment]
On Sat, Jul 13, 2024 at 08:34:55PM -0700, bjd-pfq wrote:
> Says a maintainer who, after having been issued a new bug report, wastes all of 18 hours to not ask for clarification, not for additional information, but to rush out a hurried "cannot replicate" and "closed bug" mail before the issuer can even begin to clarify.

Read CONTRIBUTING.md.

>
> My friend, "cannot replicate" does not mean your bugs aren't real. I have found a few others, as real as my earlier ones, but I have decided to ditch Kitty until such time as you start treating your bug reporters with a bit more respect and take them seriously, and of course you fixed the major showstoppers to which you yourself remain blind.

Good riddance. Don't let the door hit you on the way out.

>
> "Cannot replicate, bug closed" is not the way to stamp out bugs, it is a way to get shiny statistics.

It's a very effective way of not wasting my time dealing with idiots that have an
inflated sense of entitlement and their own importance.
