### ISSUE TITLE
Not a bug, but a modest feature request

### ISSUE THREAD

**Issue by bjd-pfq** [kovidgoyal/kitty#7625]
Under a running kitty, how can we know what version is running?  Obviously 'kitty --version' won't do, since the kitty running 'kitty --version' might not be the instance or version we are running under.

I would propose kitty sets an environment variable of its version, e.g. like bash does with its BASH_VERSION='5.1.16(1)-release'.

**Comment by trygveaa** [comment]
You can press Ctrl+Shift+F6 to see the version and a lot of other stuff.

**Comment by kovidgoyal** [comment]
Or run use the query terminal kitten. https://sw.kovidgoyal.net/kitty/kittens/query_terminal/
