### ISSUE TITLE
While Copy/paste kitty terminal not follow the source formatting

### ISSUE THREAD

**Issue by ciscohack** [kovidgoyal/kitty#7626]
Running Kitty terminal version 0.35.2 and observing whenever I copy and paste any text from any src to kitty terminal it does not adhere to the formatting whereas if I do the same in Alacritty or iterm2 they follow the copy src format and paste as it it in terminal for example 

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/7565f596-b315-4ab4-9de5-355e5a3d45f2">

The same copy in Alacritty produces the correct formatting. 

<img width="573" alt="image" src="https://github.com/user-attachments/assets/bb874ebe-53e6-426d-bbcc-68c62ad24d2e">

need help to fix this issue.

**Comment by kovidgoyal** [comment]
paste_actions no-op

in kitty.conf

**Comment by ciscohack** [comment]
> paste_actions no-op
> 
> in kitty.conf

let me try thanks genius

**Comment by ciscohack** [comment]
yes solved the problem thanks
