### ISSUE TITLE
Add readline's `ctrl-h` in overlays

### ISSUE THREAD

**Issue by sodapopcan** [kovidgoyal/kitty#7629]
Would it be possible to get readline's `ctrl-h` in overlays?  I use it often instead of backspace as it is much less of a stretch.  Currently it inserts `^H`.  `ctrl-w` and `ctrl-u` both already work.

No worries if this is not possible.

Thanks for all your hard work on this great terminal!

**Comment by kovidgoyal** [comment]
ctrl+h is mapped to backspace in the current kitty release. See line 31
in readline/keys.go

**Comment by sodapopcan** [comment]
Oh my so sorry, I haven't updated in a bit.  Thank you!
