### ISSUE TITLE
Kitty fails to run with a dlopen on glfw-x11.so.

### ISSUE THREAD

**Issue by Dread2** [kovidgoyal/kitty#7631]
**Describe the bug**
After installing Kitty 0.35.2 on my Gentoo system, I get errors about /usr/lib64/kitty/kitty/glfw-x11.so. My system is running AMD drivers on Mesa/OpenGL with the wayland backend. I have also enabled the wayland use flag's on the package x11-terms/kitty. Once the package is down installing, kitty fails to completely open resulting in...
[0.039] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 562, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 550, in _main
    init_glfw(opts, cli_opts.debug_keyboard, cli_opts.debug_rendering)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 144, in init_glfw
    init_glfw_module(glfw_module, debug_keyboard, debug_rendering, wayland_enable_ime=opts.wayland_enable_ime)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 138, in init_glfw_module
    if not glfw_init(glfw_path(glfw_module), edge_spacing, debug_keyboard, debug_rendering, wayland_enable_ime):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to dlopen /usr/lib64/kitty/kitty/glfw-x11.so with error: /usr/lib64/kitty/kitty/glfw-x11.so: cannot open shared object file: No such file or directory.
I have tried installing media-libs/glfw, with both the X, or Wayland use flags and still get this dlopen error, no matter if I have glfw installed or not. 

**To Reproduce**
1. Install Kitty 0.35.2 from the Gentoo Ebuild repositories. 
2. Use Wayland/Mesa
3. Getting a resulting glfw-x11.so

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I'm afraid I dont maintain the Gentoo package, you need to report the bug to Gentoo. I recommend people use the official kityt binaries from: https://sw.kovidgoyal.net/kitty/binary/
