### ISSUE TITLE
[feat] launch kitty window with relative size

### ISSUE THREAD

**Issue by k4lizen** [kovidgoyal/kitty#7634]
**Is your feature request related to a problem? Please describe.**
When running a pwntools script that launches gdb, it can be set to open the output/gdb pane next to each other with tmux like this:
```python
context.terminal = "tmux splitw -h -l 65% -b".split()
```
This makes it so that the window is split vertically, where the left one is 65% of the width of the unsplit window. This is really convenient for me as changing the width each time manually is tiresome, and I rerun the script quite often. For kitty I have this:
```python
context.terminal = "kitty @ launch --location=vsplit --cwd=current".split()
```
but as far as I know there is no way to make it so the split is at 65%

**Describe the solution you'd like**
A cmd argument that allows the split to be at a % location.

**Describe alternatives you've considered**
I've looked at [this](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.remember_window_size) but I don't think it solves my problem, or if it does I don't know how.

**Comment by kovidgoyal** [comment]
There isnt a declarative way to do it, you need to write a 5 line script
to do it for you.

Get the current window size, with
tput lines columns
Then calculate 15% of columns
Then launch with kitten @ launch
Then resize with kitten @ resize-window --increment=calculated value

**Comment by k4lizen** [comment]
@kovidgoyal 
So my updated setup is:
`context.terminal = "kitty @ action launch --location=before ~/.config/kitty/pwntools_debug.sh".split()`
```bash
#!/bin/bash
split_size=$((120 - $(tput cols)))
if [ $split_size -ne 0 ]; then
    kitty @ resize-window --increment=$split_size
fi
"$@"
```
And that works almost as well, the problem with calculating current size and doing +%15 is that when the pane is split, closed, and reopened - it remembers where it was before. So reruning the command (which happens often), continues pushing it by 15%.
If you know a scriptable solution for this that be great, otherwise there may be merit to reopening the issue.

**Comment by kovidgoyal** [comment]
If the size of the new window is already 65%, dont resize it.

**Comment by k4lizen** [comment]
Yes, but the way you outlined it initially doesn't work since the script gets run in the new window, not in the initial window, so `tput cols` has no sense of what the total size of the (left + right) window is. Anyways, this works:
```bash
#!/bin/bash

# set the percentage here
gdb_pct=65

# left is gdb, right is process output
left_columns=$(tput cols)
right_columns=$(kitty @ ls --match neighbor:right | jq '.[0].tabs[0].windows[0].columns')
total_columns=$((right_columns+left_columns))
goal=$((total_columns * gdb_pct / 100))

increment=$((goal-left_columns))
if [ $increment -ne 0 ]; then
    kitty @ resize-window --increment=$increment
fi

"$@"
```
Which im fairly satisfied with. Also for anyone reading in the future, the if-statement will be redundant once https://github.com/kovidgoyal/kitty/commit/15dd95d420148720efce8dee9731a192903c03fb gets released.

**Comment by k4lizen** [comment]
Thanks!
