### ISSUE TITLE
VT Extension: In-Band Resize Notifications

### ISSUE THREAD

**Issue by rockorager** [kovidgoyal/kitty#7642]
**Is your feature request related to a problem? Please describe.**
The data stream of every event needed to create terminal applications is within a single stream, except for window resize events.

**Describe the solution you'd like**
Consider implementing a new VT Extension: [Private Mode 2048: In-band resize notifications](https://gist.github.com/rockorager/e695fb2924d36b2bcf1fff4a3704bd83)

**Describe alternatives you've considered**
SIGWINCH is the only solution. Windows, when using the `ReadConsoleInput` API delivers window resize events in-band and this API is very nice to use.

**Additional context**
SIGWINCH is reliable, but *can* cause race conditions as there is now a third party (the kernel) introduced which delivers the signal from the terminal to the application on it's own schedule, from a different thread than the application is operating on.

**Other implementations**
- Ghostty has implemented
- Foot has an open PR: https://codeberg.org/dnkl/foot/pulls/1753
- I have integrated this into two TUI libraries I maintain for [go](https://git.sr.ht/~rockorager/vaxis) and [zig](https://github.com/rockorager/libvaxis)
- Wezterm [feature request](https://github.com/wez/wezterm/issues/5826)

**Comment by kovidgoyal** [comment]
You might want to think about extensibility of the reporting escape code
in the future. Have the spec specify that all four fields must be
present always with unknown values set to 0. And specify that subfields
separated by colons may be added in the future, to any field, which must
be ignored by clients that do not understand them.

I can see, for example, adding pixel density information in the future.

**Comment by rockorager** [comment]
Thanks for the suggestions. I think I had originally thought all fields should be present but went with allowing the last two to be dropped - but requiring all four seems like a better choice. I will update with that, and agree about adding that any field may contain a subparam.

**Comment by rockorager** [comment]
> Oh and in your spec you have the order of the parameters in DECRPM mixed up, the second one is the mode value, the first one is mode number.

Fixed!

**Comment by kovidgoyal** [comment]
One more point, the spec should state that the terminal must reply with the current size when the mode is switched on, even if it was already on.

**Comment by kovidgoyal** [comment]
And another point, the spec should probably specify sequencing of the events. Terminals must all follow the same sequence:

1) First, do the actual resize of the terminal data structures
2) Send both SIGWNCH and resize events. It is undefined which the client program will receive first.

That is, it is imperative the client receive the resize events only once the terminal has finished resizing its internal data structures/state.

Just FYI I added support for these events to all the kittens in kitty.

**Comment by rockorager** [comment]
> Just FYI I added support for these events to all the kittens in kitty.

Very cool!

Good points regarding sequencing - I will update the spec with that
