### ISSUE TITLE
Vertical Split results in less usable vertical space due to padding

### ISSUE THREAD

**Issue by haydonryan** [kovidgoyal/kitty#7643]
**Describe the bug**
Love kitty - keep up the fantastic work! 

In full screen (or full height of the 4k monitor) on linux, the terminal fits great with no space above the tab bar.  In tall layout, if I add a second window, then kitty adds some space at the top of the original window even though I have it set to draw minimal borders. 

I'm assuming that drawing minimal borders with just two windows would ONLY draw a line down the middle of the two windows, AND it would not add any padding  /  black space around the other 3 sides each of the windows  This is where I feel there is a bug.

This results in being able to fit one less line of text on the screen and a big gap to the tab bar.   Switching layouts from stack to tall also results in the same behavior.

**To Reproduce**

kitty.conf:
```
###########
# Layouts #
###########
enabled_layouts tall, fat, stack
draw_minimal_borders yes

window_border_width 1

window_margin_width 0
single_window_margin_width 0

window_padding_width 0
single_window_padding_width 0

placement_strategy top
```

**Screenshots**
![Screenshot from 2024-07-18 20-40-10](https://github.com/user-attachments/assets/b2990a90-1ff7-4ba9-9056-26cbfe7fb4c6)
106 lines in vim in stack mode / single window tall.

![Screenshot from 2024-07-18 20-41-36](https://github.com/user-attachments/assets/88274207-ec20-4d73-a870-469cdd3410ca)
105 lines in vim - kitty is adding margin to the window at the top / bottom, resulting in less usable space even though there is no margin

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

kitty 0.35.2 created by Kovid Goyal
Linux falcon 6.9.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000 x86_64
Arch Linux 6.9.9-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
OpenGL: '3.1.0 NVIDIA 555.58.02' Detected version: 3.1
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/haydon/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style       (True, False)
enable_audio_bell           False
enabled_layouts             ['tall', 'fat', 'stack']
font_family                 Liberation Mono
font_size                   12.0
inactive_text_alpha         0.6
placement_strategy          top
resize_in_steps             True
shell_integration           frozenset({'enabled', 'no-cursor'})
single_window_margin_width  FloatEdges(left=0.0, top=0.0, right=0.0, bottom=0.0)
single_window_padding_width FloatEdges(left=0.0, top=0.0, right=0.0, bottom=0.0)
tab_bar_min_tabs            1
tab_fade                    (1.0,)
tab_title_template           {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title} 
term                        xterm-256color
window_border_width         (1.0, 'pt')
Added shortcuts:
	ctrl+c →  copy_to_clipboard
	ctrl+l →  send_text '\E[H\E[3J'
	ctrl+shift+alt+1 →  goto_tab 1
	ctrl+shift+alt+2 →  goto_tab 2
	ctrl+shift+alt+3 →  goto_tab 3
	ctrl+shift+alt+4 →  goto_tab 4
	ctrl+shift+alt+5 →  goto_tab 5
	ctrl+shift+alt+6 →  goto_tab 6
	ctrl+shift+alt+7 →  goto_tab 7
	ctrl+shift+alt+8 →  goto_tab 8
	ctrl+shift+alt+9 →  goto_tab 9
	ctrl+v →  paste_from_clipboard
Changed shortcuts:
	kitty_mod+- →  decrease_font_size
	kitty_mod+= →  increase_font_size
	kitty_mod+backspace →  restore_font_size
	kitty_mod+c →  send_text all \x03
	kitty_mod+v →  no-op
Colors:
	active_tab_background       #880403   
	active_tab_foreground       #aaaaaa   
	color0                      #151515   
	color1                      #ac4142   
	color10                     #7e8d50   
	color11                     #e5b566   
	color12                     #6c99ba   
	color13                     #9e4e85   
	color14                     #7dd5cf   
	color15                     #f5f5f5   
	color2                      #7e8d50   
	color3                      #e5b566   
	color4                      #6c99ba   
	color5                      #9e4e85   
	color6                      #7dd5cf   
	color7                      #d0d0d0   
	color8                      #505050   
	color9                      #ac4142   
	cursor                      #a04040   
	foreground                  #ffffff   
	inactive_tab_background     #aaaaaa   
	inactive_tab_foreground     #000000   
	selection_background        #aaaaaa   
	selection_foreground        #232323   
	tab_bar_background          #202020   
	url_color                   #e5e9f0   

Important environment variables seen by the kitty process:
	PATH                                /home/haydon/.cargo/bin:/usr/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                haydon
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome-xorg
	XDG_SESSION_TYPE                    x11

```

**Comment by kovidgoyal** [comment]
There is no padding being added, the space you see will come from the
fact that the widow height - border is not a multiple of cell height.

**Comment by haydonryan** [comment]
Yes that's correct `window border 100px` plus  `draw_minimal_borders yes` leaves 100px of background around on 3 sides of each window,  and then draws the border in the middle.

I note the documentation says that it will _only_ draw the borders it needs but _to me_ that infers that space would not also be  applied on the other sides (for what I'm calling "padding").

> draw_minimal_borders yes
> 
> Draw only the minimum borders needed. This means that only the borders that separate the window from a neighbor are drawn. Note that setting a non-zero [window_margin_width](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.window_margin_width) overrides this and causes all borders to be drawn.

Is there a way to set a config that given my example (`window border 100px` plus  `draw_minimal_borders yes` ) the only place 100px is applied is the common edge between the two windows, maximizing window space?

Alternately  would you entertain a feature request / PR for another switch that would enable the functionality I'm describing?

Thanks in advance.

**Comment by kovidgoyal** [comment]
padding has nothing to do with borders. It's a property of each window and has nothing to do with how the rest of the windows are laid out. Borders (when draw_minimal_borders is on) are part of the layout and do not belong to a single window (though their color can change based on neighboring window state). 

I am afraid I am not interested in adding padding to minimal borders, which is what you are asking for, not window padding. That said I will review a PR for a "minimal_border_padding" option. If it's not too complex, I might be willing to merge. Will depend on the implementation.

**Comment by haydonryan** [comment]
> I am afraid I am not interested in adding padding to minimal borders, which is what you are asking for, not window padding.

I think we might be misunderstanding what the other is saying.  Let me try to illustrate better using images.   I'm not asking to add anything to minimal borders.  I want to remove the areas I circled in red below.

### Current behavior: 
Kitty with `window border 100px` plus `draw_minimal_borders yes` in tall layout fills the red section in the pic below with 100px of space.  
![borders](https://github.com/user-attachments/assets/993efebe-5307-416a-9eb6-863630af79a5)

### Suggested (photoshopped): 
The two windows should be able to fill the space to the edge.  So the only border that is drawn is the vertical bar between the two windows.... 
![suggested png](https://github.com/user-attachments/assets/8176034e-c996-4949-8254-52c4ce319949)

I hope this makes sense!  (I'm happy for this to be behind a config option)

**Comment by kovidgoyal** [comment]
Yes, exactly. What you want would be accomplished by adding padding to the minimal border and setting window_padding to zero.
