### ISSUE TITLE
[RFC] Animating the cursor blink

### ISSUE THREAD

**Issue by kovidgoyal** [kovidgoyal/kitty#7644]
Hi all,

I have added support for animating the cursor blink to kitty. It is off by default but can be turned on using the cursor_blink_interval option in kitty.conf. For example:

```sh
kitty -o 'cursor_blink_interval 0.5 ease-in-out'
```
See the [docs for the option](https://github.com/kovidgoyal/kitty/blob/master/kitty/options/definition.py#L331) for details.

I'd appreciate some testing and feedback on how it works given there are lots of different possibilities for cursor colors, backgrounds, opacity, etc.

This is in master now and will be in the next nightly build in an hour or so.

Thanks and enjoy.

**Comment by PythonHacker24** [comment]
## Facing an Error 

<img width="791" alt="Screenshot 2024-07-29 at 10 32 48" src="https://github.com/user-attachments/assets/469b25a3-8fa8-4039-9ccb-4eed7dd56dca">

Hey @kovidgoyal I am facing this Error when I try to execute `kitty -o 'cursor_blink_interval 0.5 ease-in-out'` on my kitty terminal. 

I tried to change values in kitty.conf and it works in there.

**Comment by kovidgoyal** [comment]
That implies the kitty you are running is not built from master/nightly.

**Comment by PythonHacker24** [comment]
Okay, thanks for resolving it.

**Comment by kovidgoyal** [comment]
released in version 0.36.0
