### ISSUE TITLE
top fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [kovidgoyal/kitty#765]
It prints this:
```
$ top 
top: can't open termcap file
```
shows the list of processes and exits, instead of staying and updating the screen every second.

**Comment by kovidgoyal** [comment]
Presumably top doesn't support the TERMINFO environment variable. So you will need to install the kitty terminfo files system-wide.

**Comment by yurivict** [comment]
```ncurses``` that ```top``` uses understands ```TERMINFO```.
```TERMINFO``` directory that you install is empty:  ```/usr/local/lib/kitty/terminfo```

**Comment by kovidgoyal** [comment]
Not it is not:
```
find linux-package/share/terminfo                                                                                   master 
linux-package/share/terminfo
linux-package/share/terminfo/x
linux-package/share/terminfo/x/xterm-kitty
```

**Comment by kovidgoyal** [comment]
And
```
find linux-package/lib/kitty/terminfo
linux-package/lib/kitty/terminfo
linux-package/lib/kitty/terminfo/x
linux-package/lib/kitty/terminfo/x/xterm-kitty
```

**Comment by yurivict** [comment]
It doesn't install the ```x/xterm-kitty``` part for me.

**Comment by kovidgoyal** [comment]
There is no installing involved those files are generated by calling tic with the kitty.terminfo file. See line 598 of setup.py If it is not there, then tic on your system is malfunctioning.

**Comment by amarshall** [comment]
Most FreeBSD software, especially in base, will use termcap, rather than terminfo, files. The way to install the entry is then a bit convoluted:

1. On a machine with Kitty terminfo installed: `infocmp -C xterm-kitty`
2. On FreeBSD host: append to `/usr/share/misc/termcap` the termcap entry which was output from step one
3. On FreeBSD host: `cd /usr/share/misc && cap_mkdb termcap`

**Comment by jacwah** [comment]
@amarshall Thanks for the clear instructions!

@kovidgoyal Perhaps this could be added to the FAQ?

**Comment by kovidgoyal** [comment]
Feel free to send a PR, relevant file is faq.rst

**Comment by Guitarbum722** [comment]
@amarshall that worked perfectly.  Thank you for the instructions provided!
