### ISSUE TITLE
OSC-99 query for support

### ISSUE THREAD

**Issue by dnkl** [kovidgoyal/kitty#7658]
There's a discussion on https://web.libera.chat/?channels=#senpai (https://sr.ht/~delthas/senpai/), on how an application should choose which notification protocol to use.

Neither OSC-777, OSC-99, nor OSC-9 can be auto-detected in a meaningful way (I don't consider querying the terminal name and version meaningful).

Would you be open to adding a way to query for OSC-99 support?

For example:

Query:
```
OSC 99 ; ? ST
```
or, if you want to keep the parameter+payload format:
```
OSC 99 ; ? ; ST
```
Response:
```
OSC 99 ST
```
I'm hoping the protocol as a whole is simple enough that we don't need to include _which_ features/parameters are supported.

**Comment by kovidgoyal** [comment]
Feel free to comment if you have concerns.

**Comment by dnkl** [comment]
Looks good to me. @delthas?

**Comment by kovidgoyal** [comment]
I also added urgency to the query response, since there *might* be
platforms that don't support it.

**Comment by kovidgoyal** [comment]
Apologies, I forgot about supporting multiplexers in the query/response, see https://github.com/kovidgoyal/kitty/commit/c4baed73a22c445db3a187843cb5f87464104a73
