### ISSUE TITLE
Request: Support for "simple fullscreen" mode on OSX

### ISSUE THREAD

**Issue by alecthomas** [kovidgoyal/kitty#766]
Hello,

First off, I have to say I am loving Kitty. It is super fast and nicely configurable.

I realise from reading a bunch of other fullscreen related issues that you are not an OSX user, so you probably aren't aware of just how annoying OSX's native fullscreen mode is (ctl+cmd+f). A fullscreen app lives on its own virtual desktop and switching between it and any other app involves a ridiculous 1 second sliding animation (vs. normal switching which is instantaneous).

Quite a few developer-centric apps have worked around this by implemented a "simple fullscreen" mode. Sublime Text and iTerm 2 both natively support it, for example. There are also popular requests for [Atom](https://github.com/atom/atom/issues/967) for and [VSCode](https://github.com/Microsoft/vscode/issues/5344).

The GLFW fullscreen mode is even worse in terms of time it takes to switch between Kitty and any other app.

Neither of these modes' issues are specific to Kitty, they are common to all OSX apps, so there's no real issue with Kitty itself. This is just a request for a feature that would make your OSX users lives much nicer.

Thanks for considering, all the best.

**Comment by kovidgoyal** [comment]
I'm afraid I have neither the interest nor required cocoa knowledge to implement this, but patches are welcome. The relevant code in kitty/glfw.c and kitty/cocoa_window.c and glfw/cocoa_window.c

**Comment by alecthomas** [comment]
Actually I've noticed `macos_hide_titlebar` is very close to "simple fullscreen" mode, all it would need to do is hide the OSX menubar (somehow).

**Comment by kovidgoyal** [comment]
If I were you, I'd just switch to a more developer friendly window manager, such as chunkwm or similar.
