### ISSUE TITLE
Global modifier keys not working when hovering over Kitty

### ISSUE THREAD

**Issue by rtgibbons** [kovidgoyal/kitty#7660]
I use Rectangle Pro as a window manager in macOS. One of the options is to Move and Resize a window with modifier keys anywhere in the window. 

![CleanShot 2024-07-23 at 15 57 52](https://github.com/user-attachments/assets/80e744f8-5c16-456e-957c-b7359adf72aa)

I'm not sure when this broke, it's been at least a couple updates. 

**Environment details**
This happens with base config.
```
kitty 0.35.2 (ad328bfeaa) created by Kovid Goyal
Darwin 0x63E16F4A.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		14.5 BuildVersion:		23F79
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public:/Applications/kitty.app/Contents/MacOS:/Users/rgibbons/.orbstack/bin
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /bin/zsh
	USER                                rgibbons
```

**Comment by rtgibbons** [comment]
I just went through and tested. This broke between release 0.25.2 and 0.26.0

**Comment by kovidgoyal** [comment]
I dont know what kind of hackery rectangle does to intercept global
keypresses. Whatever it is, I'm afraid I am not interested in spending
time trying to support it. You are welcome to investigate and propose a
fix, provided you can come up with one that does not interfere with
kitty functionality.

Once a keypress is delivered by the OS to kitty, it is kitty's property to do with
as it pleases. If something wants to implement global keypresses, it
needs to do so by preventing their delivery to applications.

**Comment by rtgibbons** [comment]
Fair enough, was hoping narrowing down the releases might make something stick out. It works with every other window in my install instead of Kitty. I'll play with it in my spare time to see what i can come up with.

**Comment by rtgibbons** [comment]
Found this, https://github.com/rxhanson/RectanglePro-Community/issues/384#issuecomment-1810504720 

Still reading and researching
