### ISSUE TITLE
solution to kde blur "korners" bug?

### ISSUE THREAD

**Issue by nvkomata** [kovidgoyal/kitty#7662]
when using the kde blur in kitty and rounded window decorations (e.g. breeze) kitty suffers from the korner bug. kde apps often deal with this by using a mask provided by the window decoration when they enable blur.

is it possible to solve this issue on kitty's end?

(one hacky solution, if possible, would be to not blur the whole window, although that would create theming issues - it could be configurable in kitty.conf) 

*alt: screenshot of the corner of kitty's server side decoration while using kde blur, it should be rounded (not sharp)*
![image](https://github.com/user-attachments/assets/fa4c0ee9-aee8-4157-91da-c3232720294f)

**Comment by kovidgoyal** [comment]
blurring is not done by applications, its done by the compositor.
Indeed, in Wayland applications cannot even access whats behind them so
they cannot do the blur even if they wanted to. This can only be solved
by the compositor.
