### ISSUE TITLE
option to force CSD (wayland)

### ISSUE THREAD

**Issue by nvkomata** [kovidgoyal/kitty#7663]
instead of just preferring ssd and falling back to csd (for gnome), there should be a config option to prefer kitty's client side decorations

**Comment by kovidgoyal** [comment]
Why? compositors draw much more appropriate window decorations than
kitty ever could. If someday kitty actually gets more functional window
decorations beyond just the title and three buttons it might be worth
making this configurable, but otherwise I dont see the point.

**Comment by nvkomata** [comment]
> Why? compositors draw much more appropriate window decorations than kitty ever could. If someday kitty actually gets more functional window decorations beyond just the title and three buttons it might be worth making this configurable, but otherwise I dont see the point.

why not? the point of my suggestion is simply provide the option, i don't see the point of outright rejecting it

**Comment by kovidgoyal** [comment]
On Wed, Jul 24, 2024 at 03:16:05AM -0700, nvkomata wrote:
> > Why? compositors draw much more appropriate window decorations than kitty ever could. If someday kitty actually gets more functional window decorations beyond just the title and three buttons it might be worth making this configurable, but otherwise I dont see the point.
>
> why not? the point of my suggestion is simply provide the option, i don't see the point of outright rejecting it

Because it takes *effort* to develop and maintain.
