### ISSUE TITLE
Disabling desktop notifications

### ISSUE THREAD

**Issue by ieviev** [kovidgoyal/kitty#7670]
Is it possible to disable osc 9/99 notifications entirely?

these two issues mention shell configuration, but what about commands you don't have control over? e.g. i don't want to be notified every time a compilation finishes.

https://github.com/kovidgoyal/kitty/issues/7518
https://github.com/kovidgoyal/kitty/issues/5172

**Comment by kovidgoyal** [comment]
Configure whatever is sending the notifications to not do so, or
configure the notification system on your desktop to not display
notifications, on macOS it's as trivial as a single toggle, on Linux,
depends on your desktop.

**Comment by ieviev** [comment]
found a solution incase someone else is struggling with this, on swaync you can put this into `~/.config/swaync/.config.json`

```json
{
    "notification-visibility": {
        "ignore-notif": {
            "state": "ignored",
            "app-name": "kitty"
        }
    }
}
```
