### ISSUE TITLE
HTML markup is honored (on Free Desktop platforms)

### ISSUE THREAD

**Issue by randomstuff** [kovidgoyal/kitty#7671]
**Describe the bug**

When using OSC 99 desktop notifications (on Free desktop platforms), [HTML markup](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#markup) is interpreted. It is not clear whether this is a bug or an expected behavior (and therefore a bug in the specification).

This behavior is not documented in the [specification](https://sw.kovidgoyal.net/kitty/desktop-notifications/) and I guess markup HTML are not honored on other platforms (?).

**To Reproduce**

~~~sh
printf '\x1b]99;i=1:d=0:e=1;%s\x1b\\\x1b]99;i=1:d=1:p=body:e=1;%s\x1b\\' \
  "$(echo -n title | base64)" \
   "$(echo -n 'Normal <b>Bold</b> Normal' | base64)"
~~~

**Screenshots**

![image](https://github.com/user-attachments/assets/71d9e1c0-2112-47e9-b3d3-f7af369db7f4)

**Environment details**
```
kitty 0.35.2 created by Kovid Goyal
Linux marvin 6.9.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.9-1 (2024-07-13) x86_64
Debian GNU/Linux trixie/sid marvin /dev/tty

Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 24.1.3-2' Detected version: 4.6
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/john/.config/kitty/kitty.conf
```

**Comment by kovidgoyal** [comment]
It's optional in the freedesktop spec. For instance I use a notification server on Linux that doesnt honor it. And macOS doesnt honor markup in notifications, other than stripping printf style escapes in the body. https://developer.apple.com/documentation/usernotifications/unnotificationcontent/body?language=objc

I guess I can add some language to the spec that title and body must be plain text only, and modify the implementation to sanitize markup.

**Comment by randomstuff** [comment]
> I guess I can add some language to the spec that title and body must be plain text only, and modify the implementation to sanitize markup.

Yes, I guess this should be done in order to have a consistent behavior across platforms.

**Comment by randomstuff** [comment]
> and modify the implementation to sanitize markup.

To clarify, I would expect markup to be escaped (so that `<a>` would be rendered as "\<a>") when talking to the Free Desktop backend (as upposed to `<a>` being stripped). Is that what you meant?

See this comment for [context](https://invent.kde.org/utilities/konsole/-/merge_requests/954#note_1000276). I'd intend to do the same thing (escaping HTML markup) in Konsole.

**Comment by kovidgoyal** [comment]
Yes, they should be escaped. It's not clear to me how they should be
escaped though. The spec just says they should be stripped, but that
would be rather surprising in an otherwise plain text format.

**Comment by randomstuff** [comment]
I'll do some further testing but I would expect `&` would have to be escaped as well (something like `html.escape()`), wouldn't it?

**Comment by randomstuff** [comment]
![image](https://github.com/user-attachments/assets/eba8dd41-cb5b-412d-9e1f-934fe55635ad)

**Comment by kovidgoyal** [comment]
Doing html.escape() wont work since HTML support is *optional* which means that on a server that doesn't support it, it will result in the escaped markup being shown as escaped markup. Indeed, I would argue that entities being processed is a bug in the server, since the spec clearly states that HTML support is limited to ONLY the specified tags. 

In any case, replacing & with &\u200c will work for that as well.

**Comment by randomstuff** [comment]
> Indeed, I would argue that entities being processed is a bug in the server, since the spec clearly states that HTML support is limited to ONLY the specified tags.

The spec is quite ambiguous in this regard but I understand it as a restriction of which HTML tags are expected to be supported but the markup is still expected to be HTML (or XML ?) so that '&' is recognized.

Anyway replacing & with &\u200c should probably work. (Though, strictly speaking, if an implementation is really XML-based (as required by the specification) instead of HTML-based, we might expect invalid '&…' sequences to generate a XML parse error?)

**Comment by kovidgoyal** [comment]
Let's not overthink it. This is about the best that can be done. To do better the freedesktop spec needs to be fixed. Clients should be able to specify a hint to tell the server the body type, plain text or html or whatever else in the future.

**Comment by randomstuff** [comment]
[XFCE implementation](https://github.com/xfce-mirror/xfce4-notifyd/blob/master/common/xfce-notify-common.c) uses [GMarkupParseContext](https://docs.gtk.org/glib/struct.MarkupParseContext.html) which returns a parse error when it finds unescaped '&'. I'll have to check but I believe this would fail on XFCE.

**Comment by kovidgoyal** [comment]
notifications have been sending unescaped & to servers for years if not decades. I highly doubt XFCE fails on that and if it does, there isnt anything we can do about it. It needs to be fixed.

**Comment by randomstuff** [comment]
So I have been doing some tests on XFCE. What happens is that if the XML parsing fails, XFCE4 falls back to treating the whole string as plain text. Your fix should make the thing work on XFCE because it will prevent glib from parsing the string as proper XML.

**Comment by kovidgoyal** [comment]
Cool, thanks.
