### ISSUE TITLE
Enable creation of log files in kitty.log for debugging purposes.

### ISSUE THREAD

**Issue by swastkk** [kovidgoyal/kitty#7672]
**Is your feature request related to a problem? Please describe.**
Yes it's the problem that we developers are facing while working with core implementation of kitty and kittens while debugging. Currently, we are using Golang and mostly working with fmt.Println() for debugging purposes which is not a good practice. So we require something like a kitty.log in the .config/kitty directory which can be kept open on another text editor to see logs generated by bad code. 

**Describe the solution you'd like**
Creation of an API internal to kitty that would be called at breakpoints in the code which needs monitoring and given a specific string that would be added into logs. This log file can be accessed by kitty, kittens, etc. for logging errors into it. Or if not API, just a format of writing into it (specified by documentation) which can be implemented by new kittens or kitty functionalities in development process. 

**Describe alternatives you've considered**
We were building a kitten for images in grid as per FOSS Issue @kovidgoyal created in our personal repo, where we were just doing `fmt.Println()` but now we need some robust mechanism for logging and standardised approach for debugging. 

**Additional context**
This is something that most of the tools used as Free and Open Source posses and it would be a good feature in kitty too.

**Comment by kovidgoyal** [comment]
In your code use the tty.DebugPrintln function. In kitty.conf set

forward_stdio yes

Then run kitty like this

kitty 2> /tmp/kitty.log

and run your kitten inside that kitty instance and all your prints will
be in /tmp/kitty.log

Or just read the output directly in another terminal instance.
