### ISSUE TITLE
Cannot exit normal mode when using vi in kitty cmdline

### ISSUE THREAD

**Issue by jrmd54** [kovidgoyal/kitty#7678]
When using inputrc vi mode to edit kitty cmdline, kitty can get stuck and never execute the command being edited

**To Reproduce**
1 - Have ~/.inputrc file whose content is:
     `set editing-mode vi`
2 - `kitty -c NONE`
3 - `vim -u NONE`
4 - execute command `:!echo foo`
5 - press <enter> 
6 - press  <ctrl>+z    (put vim in background)
7 - press <escape> to enter inputrc vi mode
8 - user is now stuck and cannot escape from vi mode

**Environment details**
My vim version is 9.0, kitty is 0.35.2

Thank you very much

**Comment by kovidgoyal** [comment]
this will be because vi is not properly resetting the kitty keyboard protocol
state on suspend.

**Comment by jrmd54** [comment]
Upgrading from Ubuntu 23.04 lunar to Ubuntu 23.10 mantic fixed the issue
(vi version number is the same vi but --version shows that patches were added)
