### ISSUE TITLE
[FreeBSD 11.2] TERM=xterm-kitty causes rendering issues

### ISSUE THREAD

**Issue by azah** [kovidgoyal/kitty#769]
## Issue

When `TERM` is set to `xterm-kitty`:
* The first word gets duplicate characters [just visual]. Example:
```
eecchecho $TERM 
```
* Backspace doesn't work
* ctrl-u doesn't register visually
* ctrl-l doesn't work correctly

## Solution

set `TERM` to `xterm-256color`. This fixed all the above issues.

**Comment by maximbaz** [comment]
You are probably missing terminfo file, how did you install kitty?

Do you have this file? `/usr/share/terminfo/x/xterm-kitty`

**Comment by kovidgoyal** [comment]
dup of #765
