### ISSUE TITLE
More settings for the panel kitten

### ISSUE THREAD

**Issue by Aworldc** [kovidgoyal/kitty#7691]
**Is your feature request related to a problem? Please describe.**
Im on wayland and hyprland. i want a terminal on top of the wallpaper but behind the bar. i can't do this because the terminal layer is forced to take exclusive use of the space.

**Describe the solution you'd like**
Add a flag to the panel kitten to set exactly which layer to put the terminal in, and a flag to set whether the layer should take exclusive use of the space

**Describe alternatives you've considered**
Try and get hyprland to add a layer rule to force non-exclusive use of the space.

**Additional context**

**Comment by kovidgoyal** [comment]
There is no "terminal layer". When the panel kitten is run in background
mode it places itself in the background layer, which is the correct
layer for it. In panel mode it places the panels in the bottom layer.
Which is again the correct layer for it.

See line 1060 in wl_window.c
