### ISSUE TITLE
Font rendering in Mint 22 defective

### ISSUE THREAD

**Issue by andrewbernard** [kovidgoyal/kitty#7692]
Kitty font rendering in Mint 22 Cinnamon Xorg desktop is defective.

**To Reproduce**
Run kitty.

**Screenshots**

![image](https://github.com/user-attachments/assets/1cf1e0e8-0a02-44f8-9b16-c8106b9a87cd)

**Environment details**

kitty 0.35.2 (ad328bfeaa) created by Kovid Goyal
Linux mint 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64
Linux Mint 22 Wilma mint /dev/tty

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=22
DISTRIB_CODENAME=wilma
DISTRIB_DESCRIPTION="Linux Mint 22 Wilma"
Running under: X11
OpenGL: '4.1 (Core Profile) Mesa 24.0.9-0ubuntu0.1' Detected version: 4.1
Frozen: True
Paths:
  kitty: /home/acb/.local/kitty.app/bin/kitty
  base dir: /home/acb/.local/kitty.app/lib/kitty
  extensions dir: /home/acb/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/acb/.local/bin:/home/acb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/acb/.local/bin:/home/acb/bin:/home/acb/lilypond/bin
	LANG                                en_AU.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                acb
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-cinnamon:/etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 cinnamon
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/acb
	XDG_CURRENT_DESKTOP                 X-Cinnamon
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      c2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/cinnamon:/usr/share/gnome:/home/acb/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

**Comment by kovidgoyal** [comment]
That's an issue with the GPU drivers in your machine.

**Comment by andrewbernard** [comment]
Sorry, neglected to mention it is Virtualbox. Any suggestions on what to do?

**Comment by kovidgoyal** [comment]
dup of #6257

**Comment by kovidgoyal** [comment]
search the issue list for virtualbox and you will find more information.
