### ISSUE TITLE
Follow GTK/Qt color scheme for frame and background and text

### ISSUE THREAD

**Issue by bphd** [kovidgoyal/kitty#7697]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kovidgoyal** [comment]
Not going to happen.

**Comment by bphd** [comment]
> Not going to happen.

Why? And it's not completed but rather not supported

**Comment by kovidgoyal** [comment]
Because it's a bad idea. You didnt bother to explain why you think it
should be done, I am not going to bother to explain why I think it
shouldnt.

**Comment by bphd** [comment]
It should to avoid eye strain and GNOME already did it. You can deactivate if you want a custom theme
