### ISSUE TITLE
Can't create new top-level windows with kitty @

### ISSUE THREAD

**Issue by 00dani** [kovidgoyal/kitty#770]
`kitty @` supports a `new-window` command, which can open new split windows and new tabs, but as far as I can tell cannot open new native system windows.

This unfortunately means that `kitty @` doesn't completely replicate the functionality of the `--single-instance` flag, so both features must be used in tandem.

Additionally, invoking kitty with `--single-instance` does not return the new window's ID, so it currently isn't even possible to - for example - spawn a new system window and then send some text to it. Something like this really ought to work:
```bash
kit() { kitty @ --to $MYKITTYSOCKET "$@" }
wid=$(kit new-window --top-level)
echo 'ls -la' | kit send-text --stdin -m id:$wid
```
(On a related note, I think `kitty @` should be able to read the socket to use from an environment variable, to avoid the need for that `kit` helper function!)

**Comment by kovidgoyal** [comment]
I dont see much point in supporting env vars, since you'd never want to type the command directly anyway. You can simply create an alias:

```sh
alias kit='kitty @ --to $MYSOCKET`
```

No need for a function
