### ISSUE TITLE
Missing package in shell.nix (Go)

### ISSUE THREAD

**Issue by nomisreual** [kovidgoyal/kitty#7700]
**Describe the bug**
I attempted to build kitty from source following the documentation provided. *Go* seems to be missing as a build input in shell.nix.

**To Reproduce**
1. Dowloaded and extracted the latest release tarball.
2. Dropped myself in a nix shell with `nix-shell --pure`.
3. Attempted to build kitty with `make linux-package`.
4. Build failed, as *Go* was not available.

**Comment by kovidgoyal** [comment]
I am afraid I dont use nix so the nix build script is best effort. Feel
free to send a PR to update it as needed.
