### ISSUE TITLE
Disable confirm OS window close for certain programs

### ISSUE THREAD

**Issue by diagonalized** [kovidgoyal/kitty#7703]
**Is your feature request related to a problem? Please describe.**
Disabling the confirmation for programs used as quick TUIs that are meant to be opened and closed. Ex. I want to keep the confirmation for programs like Neovim but disable it for my clipboard manager clipse.

**Describe the solution you'd like**
I noticed the program name is in the confirmation so maybe something like:
 `confirm_os_window_close "clipse" 0`
or similarly, this could override `confirm_os_window_close 0` to make certain programs have the confirmation: `close_program_window_with_confirmation "nvim" 1`

**Describe alternatives you've considered**
I was looking into the existing confirm_os_window_close and close_window_with_confirmation however they only seem to disable the confirmation altogether. 

In Hyprland I considered using `hyprctl activewindow` to get the name of the current active program but only found moderate success.

**Additional context**

**Comment by kovidgoyal** [comment]
Simply launch clipse as

kitty -o confirm_os_window_close=0 clipse

**Comment by diagonalized** [comment]
Works like a charm thanks! 

just in case this helps anyone out, to connect to a floating windowrulev2 my bind to open is:
`bind = SUPER, V, exec, kitty -o confirm_os_window_close=0 --class clipse -e clipse`

**Comment by kovidgoyal** [comment]
Just FYI.

-e is not needed, it's a no-op present for compatibility with some other
terminals that stupidly require it to specify the command to run.

And since you are on Wayland better to use --app-id rather than --class
(the two are aliases).

**Comment by diagonalized** [comment]
Gotcha, Hyprland specifically uses class in the config to refer to the name of a window so I was just keeping them aligned.

Thanks for the -e tip tho
