### ISSUE TITLE
Kitty portable shortcuts mapping does not work

### ISSUE THREAD

**Issue by rimvydukas** [kovidgoyal/kitty#7704]
Hi,

I have kitty portable on windows (1.76.1.13p). I've tried to defing keyboard shortcut mapping:

[Shortcuts]
; Shortcuts: definition for the menu shortcuts keys
ctrl+a new_window_with_cwd
ctrl+shift+x=send_text all ls -la\n

Restarted kitty. But it seems that kitty does not react to shortcut mapping in any way. Can anyone help me with this or is it some kind of bug? Thanks.

**Comment by kovidgoyal** [comment]
https://github.com/cyd01/KiTTY
