### ISSUE TITLE
Passthrough option for `kitten @ launch --stdin-source`

### ISSUE THREAD

**Issue by tyckesak** [kovidgoyal/kitty#7706]
**Is your feature request related to a problem? Please describe.**
Exploring man pages today, I found that it would help my flow if I was able to simply pop open a man page set in a split window right next to my shell, with layout already taken care of by Kitty (excellent piece of software!). I eventually settled on something like
```
export PAGER="kitten @ –-password <<pass>> launch most +s -w"  # +s for disabling cd, write, ...
```
in my `.zshenv` (macOS user here), but this command fails at being a `$PAGER`, since it cannot accept stdin that is piped from somewhere. If set, `man` uses `$PAGER` to display manuals it finds, and it feeds it data from stdin, as can be seen by doing `man -d man` (verbose run of man) and looking at the output's last line.

This is not just for looking at Bash man pages: I do some data analysis in R as well, and the help command `?sum`, `?matrix`, ... also passes its manual to the pager, and I can't get Kitty to accept stdin from a pipe, despite `--stdin-source` looking so promising.

**Describe the solution you'd like**
Another option "passthrough" or something similar for the parameter `--stdin-source` in `kitten @ launch`, so that the call site can feed its stdin into the remote launch invocation.

**Describe alternatives you've considered**
- A small intermediate shim script as `$PAGER` acting as middleman that yanks the stdin into a temporary variable, then passes it on. Does not work cleanly with pagers: `most`, `less` and friends want their input piped as stdin or a file path — as long as we don't start shoving stdin into a temp file, but this would be just another hack in a hack. Not to mention that for each program I would want to pipe stdin into, I will likely need a slightly different shim with slightly different parameters for each use case.
- A kitten, but I realized that I would have the same problem of not being able to cleanly pass the piped stdin down to the newly launched window.

**Additional context**
Running kitty 0.35.2 on macOS 14.5

**Comment by kovidgoyal** [comment]
launch is not going to work to send arbitrary data. If for some reason
you don't want to use temp files for this, you can use kitten @ launch
followed by kitten @ send-text --stdin which will copy its STDIN to the
STDIN of the newly launched window.

**Comment by tyckesak** [comment]
Exactly what I was looking for, thank you!
