### ISSUE TITLE
Consider this project as the default icon for kitty. It's gorgeous!

### ISSUE THREAD

**Issue by sebnapi** [kovidgoyal/kitty#7707]
**Is your feature request related to a problem? Please describe.**
The default icon looks a bit old and clumsy for such a good terminal emulator.

**Describe the solution you'd like**
DinkDonk created this beautiful icon: https://github.com/DinkDonk/kitty-icon ❤️ 

<img width="232" alt="Screenshot 2024-08-09 at 10 34 57" src="https://github.com/user-attachments/assets/27f903aa-9e3b-407c-b4ef-fefcf0d4ddd2">

**Comment by kovidgoyal** [comment]
As I have explained before, the default icon is not going to change.

**Comment by sebnapi** [comment]
Ok, thank you for kitty, it feels really good!
