### ISSUE TITLE
New behavior for send-text -- stdin

### ISSUE THREAD

**Issue by akaikaze-code** [kovidgoyal/kitty#7710]
**Is your feature request related to a problem? Please describe.**

Hi, I noticed that there is a change of behavior with new versions of kitty (not sure when, I was using 0.26.5).

 Previous, when using commands like:
"kitty @ send-text --match title:demo --exclude-active --stdin" 
I would not get text I type repeated in active window. That is not the case anymore. 

![Screenshot_2024-08-09_22-13-58](https://github.com/user-attachments/assets/9d6d945b-e2b5-4160-8bdd-dbc612bd80a0)

I tested with bare config (only "allow_remote_control yes")

**Describe the solution you'd like**

Is it possible somehow to avoid (by default or optional) that your input is repeated in active window when --exclude-active is selected?

Thanks for your time!

**Comment by kovidgoyal** [comment]
Does not replicate for me with current kitty:

kitty -o allow_remote_control=y -o enabled_layouts=tall --session <(echo -e "launch kitten @ send-text --all --exclude-active --stdin\nlaunch")

Typing causes text to be sent to the second window only not the active
window.

And note that these days, for this task you should use the broadcast
kitten, it's much nicer.
https://sw.kovidgoyal.net/kitty/kittens/broadcast/
