### ISSUE TITLE
MacOS 14.6, German Keyboard not fully working

### ISSUE THREAD

**Issue by gerd-moellmann** [kovidgoyal/kitty#7711]
Kitty version 0.35.2.

This is on a MacBook Pro with German Keyboard. I've mapped the left Option key to Alt in `kitty.conf`, the right option key is left as Option, to be able to enter characters like `~[]|{}`.

With this setup, I run `emacs -nw` using `kkp.el` which handles the Kitty Keyboard Protocol in Emacs.

In Emacs, enter `Control + #`, Emacs shows `C-@ is undefined`.
Enter `Left Option + Control + A`. Emacs says that `a with an accent runs self-insert-command`.

Switch to a US keyboard layout in macOS. Everything works just fine.  `M-C-a` for example is shown as `M-C-a` in Emacs.

Both Alacritty and iTerm2 handle the case of the German keyboard correctly. That is, when I run Emacs there, `C-#` is received by Emacs as `C-#`, `M-C-a` as `M-C-a` and so on.

**Comment by kovidgoyal** [comment]
I'm afraid I have zero interest in debugging emacs and kkp.el.
If you wish to demonstrate an issue with kitty, run

kitty --debug-input kitten show-key -m kitty

and press your problematic keys and see the output displayed by the
show-key kitten. If you wish to claim that is incorrect then post that
output and also the log from --debug-input which you will get in the
terminal in which you ran the above command.

**Comment by gerd-moellmann** [comment]
If you aren't interested that's okay, of course.

OTOH, I have zero interest in debugging Kitty. I'll just use Alacritty or iTerm :-)

**Comment by kovidgoyal** [comment]
Excellent! Don't let the door hit you in the way out.
