### ISSUE TITLE
Emojis not displayed even though I installed ttf-joypixels on my Arch Linux as described in #73

### ISSUE THREAD

**Issue by JackySu** [kovidgoyal/kitty#7713]
**Describe the bug**
emojis like 📦 not displayed

**To Reproduce**
1. copy 📦 to Kitty
2. it doesn't display
3. run `kitty --debug-font-fallback sh -c "printf '\U0001F4E6'; read"`
4. also doesn't display

**Screenshots**
![image](https://github.com/user-attachments/assets/0d7f0ac1-f62b-4116-a522-f6555e5e2512)
As you see normal unicode characters are ok, but not for emoji

**Environment details**
```
kitty 0.35.2 created by Kovid Goyal
Linux arch 6.10.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000 x86_64
Arch Linux 6.10.3-arch1-2 (/dev/tty)

Running under: Wayland (Hyprland v0.41.2,) missing: single_pixel_buffer
OpenGL: '3.1.0 NVIDIA 555.58.02' Detected version: 3.1
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/fish
Loaded config files:
  /home/iulx0/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.5
confirm_os_window_close 0
enable_audio_bell       False
font_family             Fira Code SemiBold
font_size               12.0
selection_background    None
selection_foreground    None
window_padding_width    FloatEdges(left=4.0, top=4.0, right=4.0, bottom=4.0)
Colors:
	cursor                  #dddddd   

Important environment variables seen by the kitty process:
	PATH                                /home/iulx0/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/fish
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-1
	USER                                iulx0
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_BACKEND                         wayland
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 Hyprland
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 Hyprland
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

I tried to install https://archlinux.org/packages/extra/any/ttf-joypixels/ like described in #73 but yet to work

**Comment by kovidgoyal** [comment]
You didnt actually post the output from running --debug-font-fallback but I am going to guess this is because you have some COLRv1 based font on your system, fix that and you will be fine.

dup of #7140

**Comment by JackySu** [comment]
> You didnt actually post the output from running --debug-font-fallback but I am going to guess this is because you have some COLRv1 based font on your system, fix that and you will be fine.
> 
> dup of #7140

Thanks for the quick reply! Sorry for my not being careful enough, COLRv0 based font fixed my issue.

**Comment by JackySu** [comment]
For anyone interested in the solution, hope this helps:
1. it is my COLRv1 (segoe I remember) current user fonts in `/usr/local/share/fonts`  had conflicts with my global fonts, I kind of think its better to make sure fonts are installed globally in `/usr/share/fonts/` and I just deleted conflicting local fonts
2. if everything fails for you, turn to this https://www.reddit.com/r/archlinux/comments/o1n6fd/tip_for_anyone_struggling_to_get_emojis_to/
this 100% works for everyone
