### ISSUE TITLE
macOS window movement using held key broken for main Kitty window

### ISSUE THREAD

**Issue by unphased** [kovidgoyal/kitty#7718]
**Is your feature request related to a problem? Please describe.**
I configure BTT (bettertouchtool)'s window moving modifier feature to allow me to quickly move windows around in macOS without first targeting the draggable areas of windows. 
<img width="973" alt="image" src="https://github.com/user-attachments/assets/887eaefd-eae8-4cdc-b1ed-feff989fa1d8">

This works everywhere in almost all apps I've enountered except for Kitty. Specifically, only the title bar of Kitty windows actually count as window real estate, so, for some reason I cannot move kitty windows around with this capability. there are also other tools that implement this method of moving windows, such as https://github.com/finestructure/Hummingbird and several others. I have only used BTT for this in recent times because I already use BTT for gestures so there is no sense having a special app dedicated to this functionality.

**Describe the solution you'd like**
I'd like us to look into why this window movement method isn't working properly (which I really need to work especially for the terminal which is the most important app on the computer). 

**Describe alternatives you've considered**
There really are no alternatives, but I would be willing to use other key-to-move/resize-windows apps to get the functionality for kitty if one exists. I am NOT requesting adding a feature to kitty to change how its window behaves for macOS.

**Additional context**
I have 3 main issues preventing me currently from migrating to kitty from alacritty. This is by far the biggest one. the others are: 

- related to this one. Be able to make a terminal without title bar or borders to save on space. In particular since only the title bar allows me to move the window at all, using the existing `hide_window_decorations yes` setting makes it so i am unable to move the window at all, because the borders and titlebar are the normal ways to drag a window around, and I cannot use the BTT or other key based way to drag a window around. 
- a quick full screen toggle behavior. right now kitty has a Ctrl+Shift+F11 default bind to trigger fullscreen but it uses the macos native fullscreen, which is not a desirable fullscreen mode to use, because it has an animation (yes i know i can disable that) and yanks the window out to a new Space (this is the part that is really troublesome and disruptive). I need something like alacritty's "Simple fullscreen" mode which toggles instantly while bypassing the os fullscreen.

**Comment by kovidgoyal** [comment]
I have no clue how BTT works or why it doesn't like kitty windows, you
would need to ask its developers. If there is something non-invasive
that can be done in kitty, I'll be happy to accept a PR.

Closing as this is not actionable, but feel free to discuss further.

**Comment by unphased** [comment]
Maybe one way to approach it is to see how kitty implements the window (is it GLFW?) and see if we can replicate it against these other software with a simple window created in a similar way and explore the problem from there.

**Comment by kovidgoyal** [comment]
Feel free to do so, windows are created in glfw/cocoa_window.m

**Comment by unphased** [comment]
Alright I got a nice update, so i noticed that the dragging behavior for this implemented by BTT has some quirks already, it seems to move the window by an offset that is a bit larger than the pointer movement. 

I went to actually try Hummingbird and what do you know, it works fine with Kitty. So at this time it looks like BTT's key based window dragging/resize is broken and I'm going back to using hummingbird. 

Pretty happy about this situation to be honest.

**Comment by unphased** [comment]
Ah crap it's not 100%. Hummingbird works better than BTT for this but it's still a bit flaky. the first time mouse is over a kitty window, it won't "see it" until i go to the title bar. then once i engage this mechanism to move it, it can "see" the whole window at that point. Hmm. There is just something weird going on. It's like whatever method these tools use are not able to see the kitty glfw window's full extents. Only status bar.

**Comment by kovidgoyal** [comment]
You really should ask the developers of these software to comment, only they can tell us why their software doesn't work with kitty, it's impossible for anyone else to do anything more than make handwavy guesses.
