### ISSUE TITLE
kitty not showing thumbnails

### ISSUE THREAD

**Issue by tabletseeker** [kovidgoyal/kitty#7727]
Hi, I know this belongs over at ytfzf  but the maintainer left so I was hoping somebody here might know.

Starting ytfzf in tmux breaks thumbnails.

A script contains the following code to start ytfzf
/home/user/script:
```
ytfzf -t -T kitty
```

Then this script is called in tmux session with this:
```
sudo -u user /home/user/script
```
It works fine when started in a regular terminal without, though.

Any advice on how that can be fixed?

Regards

**Comment by tabletseeker** [comment]
Small update:

The thumbnails actually work with sudo -u when the terminal has the default size. 

As soon as I resize the terminal all thumbnails disappear. Executing the command again in a resized terminal results in no thumbnails being shown.

Only spawning a new terminal with default window size allows thumbnails to be shown.

What the hell could that be?

**Comment by kovidgoyal** [comment]
No clue, I know nothing about ytfzf.

**Comment by tabletseeker** [comment]
Hi, is there something about tmux environment variables or the fact that kitty is started in a subshell that could stop it from working?

**Comment by kovidgoyal** [comment]
No idea, depends on what ytfzf is doing. The kitty graphics protocol
doesn't depend on any env vars or similar, and works despite tmux's best
efforts to break it. As always, my advice is to ditch terminal
multiplexers they are not worth the headaches they cause.

**Comment by tabletseeker** [comment]
Haha, yes you're probably right. This has just been driving me crazy.

Kitty thumbnails work fine with tmux and ytfzf when running ytfzf command directly.

It only stops working when I use sudo -u user in combination. I'll keep looking.

Anyway thank you for your time.
