### ISSUE TITLE
PragmataPro symbols are rendered smaller than they should

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#7729]
**Describe the bug**

**To Reproduce**
1. Open kitty `0.35.2`
2. Run `echo -ne "\UF05A9 "` [wifi symbol](https://fabrizioschiavi.github.io/pragmatapro-semiotics/?q=F05A9) It should look like this 

![Screenshot 2024-08-17 at 16-25-25 screenshot png (PNG Image 3360 × 2100 pixels)](https://github.com/user-attachments/assets/4fb665ea-a950-47c6-97aa-f3c8ef7b55af)

3. Upgrade to `0.36.0`
4. Run `echo -ne "\UF05A9 "`, now it looks like this

<img alt="Screenshot 2024-08-17 at 16 24 52" src="https://github.com/user-attachments/assets/4c0a39eb-f54b-4f62-9c81-01e25cc1e607">

**Environment details**
```
kitty 0.36.0 (d8db17c513) created by Kovid Goyal
Darwin pandoras-box 21.6.0 Darwin Kernel Version 21.6.0: Mon Jun 24 00:56:10 PDT 2024; root:xnu-8020.240.18.709.2~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.7.6 BuildVersion:	21H1320
OpenGL: '4.1 INTEL-18.8.16' Detected version: 4.1
Frozen: True
Fonts:
  medium: PragmataProMono-Regular: /Library/Fonts/PragmataPro_Mono_R_0830.ttf
  bold: PragmataProMono-Bold: /Library/Fonts/PragmataPro_Mono_B_0830.ttf
  italic: PragmataProMono-Italic: /Library/Fonts/PragmataPro_Mono_I_0830.ttf
  bi: PragmataProMono-BoldItalic: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_Z_0830.ttf
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ahmed/.config/kitty/kitty.conf
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
active_border_color             None
allow_remote_control            yes
clipboard_control               ('write-clipboard', 'write-primary', 'no-append')
confirm_os_window_close         0
cursor_stop_blinking_after      0
disable_ligatures               1
enable_audio_bell               False
font_family                     family="PragmataPro Mono"
font_size                       12.0
hide_window_decorations         1
inactive_text_alpha             0.6
kitty_mod                       cmd
macos_colorspace                displayp3
macos_custom_beam_cursor        True
macos_option_as_alt             3
macos_traditional_fullscreen    True
scrollback_fill_enlarged_window True
scrollback_lines                20000
scrollback_pager                ['nvim', '-c', 'set nonumber nolist showtabline=0 foldcolumn=0', '-c', 'autocmd VimEnter * cnoremap q q!|nnoremap q :q!<CR>|normal G', '-c', 'silent write /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - ']
select_by_word_characters       :@-./_~?&=%+#
shell_integration               frozenset({'no-cursor'})
strip_trailing_spaces           smart
tab_activity_symbol             ▲
tab_bar_edge                    1
update_check_interval           0.0
window_alert_on_bell            False
window_padding_width            FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added mouse actions:
	cmd+left press grabbed →  mouse_discard_event
	cmd+left release grabbed →  mouse_click_url
	cmd+left release ungrabbed →  mouse_click_url
	opt+cmd+left press ungrabbed →  mouse_selection rectangle
Added shortcuts:
	ctrl+i →  send_text application \x48
	kitty_mod+p > h →  kitten hints --type linenum, run_kitten text hints --type word --program -, run_kitten text hints --type line --program -, run_kitten text hints --type path, run_kitten text hints --type path --program -, kitten hints --type hyperlink, kitten hints --type hash --program -
	kitty_mod+shift+h →  show_scrollback
Removed shortcuts:
	cmd++ →  change_font_size all +2.0
	cmd+, →  edit_config_file
	cmd+- →  change_font_size all -2.0
	cmd+0 →  change_font_size all 0
	cmd+1 →  first_window
	cmd+2 →  second_window
	cmd+3 →  third_window
	cmd+4 →  fourth_window
	cmd+5 →  fifth_window
	cmd+6 →  sixth_window
	cmd+7 →  seventh_window
	cmd+8 →  eighth_window
	cmd+9 →  ninth_window
	cmd+= →  change_font_size all +2.0
	cmd+c →  copy_to_clipboard
	cmd+down →  scroll_line_down
	cmd+end →  scroll_end
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+home →  scroll_home
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+page_down →  scroll_page_down
	cmd+page_up →  scroll_page_up
	cmd+q →  quit
	cmd+r →  start_resizing_window
	cmd+t →  new_tab
	cmd+up →  scroll_line_up
	cmd+v →  paste_from_clipboard
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	kitty_mod+enter →  new_window
	kitty_mod+f2 →  edit_config_file
	kitty_mod+k →  scroll_line_up
	kitty_mod+n →  new_os_window
	kitty_mod+p > f →  kitten hints --type hyperlink, kitten hints --type linenum, kitten hints --type hash --program -, kitten hints --type word --program -, kitten hints --type line --program -, kitten hints --type path, kitten hints --type path --program -
	kitty_mod+q →  close_tab
	kitty_mod+t →  new_tab
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window
Changed shortcuts:
	kitty_mod+0 →  change_font_size all 0
	kitty_mod+e →  run_kitten text hints
	kitty_mod+h →  previous_window
	kitty_mod+u →  input_unicode_character
Colors:
	background                      #111111   
	color0                          #1d1f21   
	color1                          #cc6666   
	color10                         #99cc99   
	color11                         #ffcc66   
	color12                         #6699cc   
	color13                         #cc99cc   
	color14                         #66cccc   
	color15                         #dddddd   
	color2                          #b5bd68   
	color3                          #f0c674   
	color4                          #81a2be   
	color5                          #b294bb   
	color6                          #8abeb7   
	color7                          #c5c8c6   
	color8                          #333333   
	color9                          #f2777a   
	cursor                          #20bbfc   
	foreground                      #c5c8c6   
	inactive_tab_background         #1d1f21   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                ahmed
```

**Additional context**

Minimal config

```
font_family                  family="PragmataPro Mono"
bold_font                    auto
italic_font                  auto
bold_italic_font             auto
font_size                    12.0
```

**Comment by kovidgoyal** [comment]
I doubt that pragmata pro has the symbol, run kitty with --debug-font-fallback to see what font it's actually coming from.

**Comment by ahmedelgabri** [comment]
> I doubt that pragmata pro has the symbol

Pragamata Pro does have the symbol 

- https://github.com/fabrizioschiavi/pragmatapro/blob/b757518ef20aeda85e1c26a3c85c5ea246ddeea4/useful_files/All_chars.png
- https://fabrizioschiavi.github.io/pragmatapro-semiotics/?q=F05A9


> run kitty with --debug-font-fallback to see what font it's actually coming from.

This is what I get back

```
▲ kitty --debug-font-fallback sh -c "printf '\UF05A9'; read"
[0.452] Cell height calculation:
[0.452] 	line height from line origins: 26.000000
[0.452] 	line bounds: origin-y: -4.242188 height: 26.320312
[0.452] 	line bounds-no-leading: origin-y: -4.242188 height: 26.320312
[0.452] 	bounds metrics: ascent: 22.078125
[0.452] 	line metrics: ascent: 22.078125 descent: 4.242188 leading: 0.000000
[0.452] 	font metrics: ascent: 22.078125 descent: 4.242188 leading: 0.000000 underline_position: -3.574219
[0.452] 	cell_height: 26 baseline: 22 underline_position: 26 strikethrough_position: 14
[0.894] Text fonts:
[0.894]   Normal: PragmataProMono-Regular: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_R_0830.ttf
[0.894]   Bold: PragmataProMono-Bold: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_B_0830.ttf
[0.894]   Italic: PragmataProMono-Italic: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_I_0830.ttf
[0.894]   Bold-Italic: PragmataProMono-BoldItalic: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_Z_0830.ttf
```

**Comment by kovidgoyal** [comment]
OK I'll look at it when I have a moment, but in the meantime you can
likely fix it by mapping those symbols to an actual symbol font such as
the NERD font in kitty.conf using symbol_map.

**Comment by kovidgoyal** [comment]
Just realised Pragmata Pro is a paid font so I cant access it. If you want me to debug further email me a copy of the fonts, you can find my email address at the top of most kitty source code files.

**Comment by ahmedelgabri** [comment]
> OK I'll look at it when I have a moment, but in the meantime you can
likely fix it by mapping those symbols to an actual symbol font such as
the NERD font in kitty.conf using symbol_map.

`symbol_map U+E000-U+F8F9 "PragmataPro Mono"`

If I do this & run `kitty --debug-font-fallback sh -c "printf '\UF05A9'; read"` I get this now


```
▲ kitty --debug-font-fallback sh -c "printf '\UF05A9'; read"
[0.390] The font "PragmataPro Mono" was not found, falling back to Menlo
[0.504] Cell height calculation:
[0.504]         line height from line origins: 26.000000
[0.504]         line bounds: origin-y: -4.242188 height: 26.320312
[0.504]         line bounds-no-leading: origin-y: -4.242188 height: 26.320312
[0.504]         bounds metrics: ascent: 22.078125
[0.504]         line metrics: ascent: 22.078125 descent: 4.242188 leading: 0.000000
[0.504]         font metrics: ascent: 22.078125 descent: 4.242188 leading: 0.000000 underline_position: -3.574219
[0.504]         cell_height: 26 baseline: 22 underline_position: 26 strikethrough_position: 14
[0.949] Text fonts:
[0.949]   Normal: PragmataProMono-Regular: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_R_0830.ttf
[0.949]   Bold: PragmataProMono-Bold: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_B_0830.ttf
[0.949]   Italic: PragmataProMono-Italic: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_I_0830.ttf
[0.949]   Bold-Italic: PragmataProMono-BoldItalic: /Library/Fonts/Nix Fonts/ccfgwmvycqyn3bwm2gmd7ah7afv7rvk8-pragmatapro-0.830/share/fonts/truetype/PragmataPro_Mono_Z_0830.ttf
[0.949] Symbol map fonts:
[0.949]   Menlo-Regular: /System/Library/Fonts/Menlo.ttc
```


> Just realised Pragmata Pro is a paid font so I cant access it. If you want me to debug further email me a copy of the fonts, you can find my email address at the top of most kitty source code files.

Not sure if I'm allowed to do this because of the font licence, will check and get back to you.

**Comment by ahmedelgabri** [comment]
Ok, if I have the font name quoted it will fall back to Menlo-Regular 

This doesn't work

```
symbol_map U+E000-U+F8F9 "PragmataPro Mono"
```

This reports back correctly, but doesn't fix the size issue

```
symbol_map U+E000-U+F8F9 PragmataPro Mono
```

**Comment by kovidgoyal** [comment]
```
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
```

**Comment by kovidgoyal** [comment]
It's rendering in a single cell for me with 0.35.2 as well (tested on Linux, not macOS, but the code is the same for deciding how many cells to render in, so I didn't bother checking on macOS). Indeed looking at the metrics of that character in Pragmata Pro it is supposed to render in one cell (the glyph is no wider than the glyph for H or W), so rendering it small is correct. Use the symbol_map I posted above and you should be fine, the symbol will be loaded from the builtin NERD font that comes with kitty 0.36 and thus will be wide and will be rendered in two cells.

**Comment by ahmedelgabri** [comment]
> It's rendering in a single cell for me with 0.35.2 as well (tested on Linux, not macOS, but the code is the same for deciding how many cells to render in, so I didn't bother checking on macOS). Indeed looking at the metrics of that character in Pragmata Pro it is supposed to render in one cell (the glyph is no wider than the glyph for H or W), so rendering it small is correct. 

In 0.35.2

This would render inside a single cell

`echo -ne "\UF05A9"`

This (notice the extra space at the end) would render it bigger. But this is no longer the case. 

`echo -ne "\UF05A9 "`

> Use the symbol_map I posted above and you should be fine, the symbol will be loaded from the builtin NERD font that comes with kitty 0.36 and thus will be wide and will be rendered in two cells.

I did try this and it didn't work, it said the font was missing or something. (I'm on my phone now, will post the output later), plus it will be nicer to use the same glyphs from the same font IMO.

**Comment by kovidgoyal** [comment]
On Sun, Aug 18, 2024 at 11:13:28PM -0700, Ahmed El Gabri wrote:
> > It's rendering in a single cell for me with 0.35.2 as well (tested on Linux, not macOS, but the code is the same for deciding how many cells to render in, so I didn't bother checking on macOS). Indeed looking at the metrics of that character in Pragmata Pro it is supposed to render in one cell (the glyph is no wider than the glyph for H or W), so rendering it small is correct.
>
> In 0.35.2
>
> This would render inside a single cell
>
> `echo -ne "\UF05A9"`
>
> This (notice the extra space at the end) would render it bigger. But this is no longer the case.
>
> `echo -ne "\UF05A9 "`

Nope it renders in one cell on 0.35.2 for me, I tested it in macOS as
well. And indeed, I dont see how its possible for it to have rendered in
two cells, as I said the glyph in the font has the same width as the
rest of the glyphs. You can check that for yourself using some font
inspection program such as FontForge.

See here:
https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts.c#L1384

desired_cells is calculated as glyph width / cell_width. Do a git blame
on that file and you will see that the last changes to that part of the
code were over a year before, long before 0.35.2

Now look at
https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts.c#L1393

that shows the number of spaces used to render the glyph is limited by
desired_cells. Also not changed for over a year.

>
> > Use the symbol_map I posted above and you should be fine, the symbol will be loaded from the builtin NERD font that comes with kitty 0.36 and thus will be wide and will be rendered in two cells.
>
> I did try this and it didn't work, it said the font was missing or something. (I'm on my phone now, will post the output later), plus it will be nicer to use the same glyphs from the same font IMO.

NERD font is builtin into kitty as of 0.36 so I dont see how that's
possible

**Comment by ahmedelgabri** [comment]
> Nope it renders in one cell on 0.35.2 for me, I tested it in macOS as
well. And indeed, I dont see how its possible for it to have rendered in
two cells, as I said the glyph in the font has the same width as the
rest of the glyphs. You can check that for yourself using some font
inspection program such as FontForge.
>
> See here:
> https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts.c#L1384
>
> desired_cells is calculated as glyph width / cell_width. Do a git blame
on that file and you will see that the last changes to that part of the
code were over a year before, long before 0.35.2
>
> Now look at
> https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts.c#L1393
>
> that shows the number of spaces used to render the glyph is limited by
desired_cells. Also not changed for over a year.

That's very odd because this is 0.35.2 on my machine & both `kitty --debug-font-fallback sh -c "printf '\UF05A9'; read"` and `kitty --debug-font-fallback sh -c "printf '\UF05A9 '; read"` report back PragmataPro and render small and wider glyphs.

![Screenshot 2024-08-19 at 09 37 44](https://github.com/user-attachments/assets/7dea5884-d983-44c2-8ca2-4b81462768b6)

> NERD font is builtin into kitty as of 0.36 so I dont see how that's
possible

Ok, this works but the output on the first line says it's can't find the font and falls back to Menlo but at the end it logs the path to the font so not sure what's correct here.

```
ϟ kitty --debug-font-fallback sh -c "printf '\UF05A9'; read"
[0.399] The font Symbols Nerd Font Mono was not found, falling back to Menlo
[0.512] Cell height calculation:
[0.512] 	line height from line origins: 26.000000
[0.512] 	line bounds: origin-y: -4.242188 height: 26.320312
[0.512] 	line bounds-no-leading: origin-y: -4.242188 height: 26.320312
[0.512] 	bounds metrics: ascent: 22.078125
[0.512] 	line metrics: ascent: 22.078125 descent: 4.242188 leading: 0.000000
[0.512] 	font metrics: ascent: 22.078125 descent: 4.242188 leading: 0.000000 underline_position: -3.574219
[0.512] 	cell_height: 26 baseline: 22 underline_position: 26 strikethrough_position: 14
[1.015] Text fonts:
[1.015]   Normal: PragmataProMono-Regular: /Library/Fonts/Nix Fonts/4c6v2z6g8wjvs8s3icmkk3s0zbbpn76x-PragmataPro0.830/share/fonts/opentype/PragmataPro_Mono_R_0830.otf
[1.015]   Bold: PragmataProMono-Bold: /Library/Fonts/Nix Fonts/4c6v2z6g8wjvs8s3icmkk3s0zbbpn76x-PragmataPro0.830/share/fonts/opentype/PragmataPro_Mono_B_0830.otf
[1.015]   Italic: PragmataProMono-Italic: /Library/Fonts/Nix Fonts/4c6v2z6g8wjvs8s3icmkk3s0zbbpn76x-PragmataPro0.830/share/fonts/opentype/PragmataPro_Mono_I_0830.otf
[1.015]   Bold-Italic: PragmataProMono-BoldItalic: /Library/Fonts/Nix Fonts/4c6v2z6g8wjvs8s3icmkk3s0zbbpn76x-PragmataPro0.830/share/fonts/opentype/PragmataPro_Mono_Z_0830.otf
[1.015] Symbol map fonts:
[1.015]   SymbolsNFM: /Applications/kitty.app/Contents/Resources/kitty/fonts/SymbolsNerdFontMono-Regular.ttf
```

**Comment by schiegl** [comment]
I'm experiencing the same issue where Nerd Font symbols are much smaller now and I'm not using Pragmata Pro, rather JetBrains Mono (the Nerd Font variant). Using just regular JetBrains Mono (which you recommend) increases the Nerd Font symbol size. However, I find the Nerd Font variant of the font to have a spacing/sizing which fits better with the font.

Is there a way to resize built-in Nerd Font symbols or disable replacing symbols if one uses the Nerd Font already?

**Comment by kovidgoyal** [comment]
If a symbol is found in the font it will be rendered from the font
unless you define it in symbol_map. You can define the symbol map to use
your patched font instead though that will likely end up with the same
small sized symbol. Basically, a symbol is rendered in more than one
cell only if the font it comes from defines the glyph as being wider
than the width of a single cell and the cell is followed by a space.
That has always been the case, I don't know how you are getting wider
symbols in previous kitty versions, I cant replicate and I cant see how
its possible given the code either.

**Comment by kovidgoyal** [comment]
What would be the point? I don't disbelive that you have the issue, I
just don't understand it/see how it is possible. And, the behavior in
0.36.0 is the intended behavior. If a glyph in a font is not wide then
kitty is not going to render it wide, even if followed by space, indeed
to do so it would have to increase the font size when rendering that
glyph.

I can only assume that somehow with your configs on pre 0.36 kitty was
actually loading the glyph from another font, due to some bug that got
incidentally fixed. That's the only way I can see it being rendered wide.

Using symbol_map to load glyphs from another font that are not suitable
in your main font is the correct/designed way to do this.

**Comment by ahmedelgabri** [comment]
> What would be the point? I don't disbelive that you have the issue, I
just don't understand it/see how it is possible. And, the behavior in
0.36.0 is the intended behavior. If a glyph in a font is not wide then
kitty is not going to render it wide, even if followed by space, indeed
to do so it would have to increase the font size when rendering that
glyph.

I totally understand your POV, I'm just trying to understand what really happened here, I'm a Kitty user since `0.8.*` and it has been always working like this. I noticed something interesting though in my change between `0.35.2` -> `0.36.0`

```diff
- font_family PragmataPro Liga
+ font_family family="PragmataPro Mono Liga"
```

This was added because `kitten choose-font` only saw 

- PragmataPro Mono
- PragmataPro Mono Liga

The font actually has 4 and I think `0.35.2` I would see all 4 as options:

- PragmataPro
- PragmataPro Liga
- PragmataPro Mono
- PragmataPro Mono Liga

Maybe this is the problem?

**Comment by kovidgoyal** [comment]
The other's are not monospaced. Only things that show up under "fixed
width" in the Font Book application are allowed. There was indeed a bug
in prior versions of kitty where on macOS only it allowed some
non-monospaced fonts. This was fixed. But I don't see how it would affect
glyph selection logic, as glyphs are selected from already loaded fonts.

**Comment by kovidgoyal** [comment]
Well yes, that's because the metrics for the builtin font are unlikely to match that of whatever font you choose for the main font. Either you should follow up such symbols with a space or use symbol_map to load them from a font that is metric compatible with your main font, it could even be your main font itself if it is  patched font.

**Comment by ahmedelgabri** [comment]
I have to say that after a couple of days with `Symbols Nerd Font Mono` plus `symbol_map`, I'm not really happy with the results and I'd prefer the old behavior to be honest. Because the symbols/icons don't really match the font size, they look bigger and don't look nice.

I understand the reasoning, but maybe allowing the user to use whatever font they want (maybe warn them about their choice) might be a better approach than forcing them into a specific solution. 

This is a very subjective topic of course because fonts are a kind of UI and this is more taste and preference than anything.

**Comment by kovidgoyal** [comment]
You can symbol_map the symbols to use the patched pragmata pro if you
prefer that.

**Comment by ahmedelgabri** [comment]
Here is another issue with `symbol_map` and `Symbols Nerd Font Mono` looks like it breaks `kitten choose-font`

https://github.com/user-attachments/assets/2b63d7ad-437f-4a46-b166-3ed0c2d82dca

**Comment by kovidgoyal** [comment]
Reporting it as missing just means that its not an installed font on your system. Instead the bundled copy that comes with kitty will be used.
