### ISSUE TITLE
Create a new macOS window doesn't (always) work

### ISSUE THREAD

**Issue by rizo** [kovidgoyal/kitty#773]
I have the `map cmd+shift+n  new_os_window` mapping in my config. It works as expected when a kitty window is open and active. But it doesn't seem to work on a new mission control desktop on macOS.

Usually I organize projects by macOS desktops, so when I create a new one I often need to open a new kitty window too. Currently I have to go to an existing desktop with a kitty window, open a new window and move it to the new desktop.

Am I missing some configuration or is it a missing feature?

Thanks in advance.

**Comment by kovidgoyal** [comment]
In macOS keyboard shortcuts only work if the application has focus. i.e. if the application is shown in the top menubar. If you to launch kitty using a global keyboard shortcut you have to configure such a hotkey in the system preferences.

**Comment by rizo** [comment]
@koekeishiya Thanks for the quick reply!

I do have in fact the kitty application open and with focus. The topbar shows the kitty application.

<img width="510" alt="screen shot 2018-07-30 at 13 49 52" src="https://user-images.githubusercontent.com/308413/43398267-7a4a7d0e-93ff-11e8-8a7c-4214403c2edf.png">

The mapping should be sent to kitty, this is not a global shortcut. When I press `cmd+shift+n` nothing happens.

**Comment by rizo** [comment]
Maybe this is relevant: under System Preferences/Mission Control, I have the "When switching to an application, switch to a Space with open windows for the application" option unchecked. This way selecting kitty with cmd+tab doesn't switch the desktop and focuses the app.

**Comment by kovidgoyal** [comment]
Use whatever shortcut is present in the kitty menu for "New OS window" (IIRC it defaults to cmd+n) Or just click that menu entry using the mouse.

**Comment by rizo** [comment]
The shortcut I defined in the config file doesn't work. Nor does `cmd+n` or other combinations. I am making sure that the app is focused and shown in the menubar.

Also there's no menu entry to create a new window:

<img width="473" alt="screen shot 2018-07-30 at 13 56 48" src="https://user-images.githubusercontent.com/308413/43398587-6f8ee386-9400-11e8-90d9-a1e0fe313077.png">

The `:: fish /Users/rizo` menu doesn't have any options at all.

Is there a way to debug this, so that I could give you more information?

**Comment by kovidgoyal** [comment]
Click kitty not window

**Comment by rizo** [comment]
Sorry, it doesn't have that option :(

<img width="422" alt="screen shot 2018-07-30 at 13 59 51" src="https://user-images.githubusercontent.com/308413/43398759-e1241c64-9400-11e8-88d5-198722c418fa.png">

(Interestingly if I click on the "Preferences..." menu entry a new window appears with the config file open.)

**Comment by kovidgoyal** [comment]
What version of kitty are you running? Update to 0.11.3

**Comment by rizo** [comment]
Just updated and the option is now there! Sorry, should have checked my version first.

Thank you very much! :)
