### ISSUE TITLE
error why loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CreepinGenius** [kovidgoyal/kitty#7731]
**Describe the bug**
I have manually installed kitty by following this tutorial: https://sw.kovidgoyal.net/kitty/binary/ but when I run `kitty` I get the following error:
`error why loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory`

I have tried flags like `--debug` and didn't get anything more, so I tried `--help` and got the same error too.
I have also tried reinstalling it... 3 times!

**To Reproduce**
1. Manually install kitty by following  https://sw.kovidgoyal.net/kitty/binary/ on debian 11.7
2. Run the `kitty` command.

**Screenshots**
![Screenshot_2024-08-17_17-33-38](https://github.com/user-attachments/assets/9eb27bdc-b4b0-4639-9099-970b325db49a)
sorry for the bad quality, I'm running this on XTerm

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
That's a really old distro, most likely it is missing some library
needed by python 12 that kitty doesnt bundle. You can try running it as
LD_DEBUG=libs kitty

that will probably tell you what the real issue is, it cant be missing
libpython since that is included with the kitty binaries.

**Comment by kovidgoyal** [comment]
And I just tried it in a debian oldstable container and it works fine. 

```sh
podman run -i -t debian:oldstable
apt update && apt install curl xz-utils && mkdir -p ~/.local && curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin && ~/.local/kitty.app/bin/kitty +runpy 'print("hello")'
```

Prints hello as expected.

**Comment by CreepinGenius** [comment]
Here's the new error I get using LD_DEBUG, also I am running debian 11 in a qubes vm, but this shouldn't do any difference except if they have some libraries missing...
![Screenshot_2024-08-18_12-31-39](https://github.com/user-attachments/assets/ea036eba-c5fb-45cf-8ca9-6778dee66210)

**Comment by kovidgoyal** [comment]
Presumably qubes breaks RPATH based linking then. Nothing I can do
about that.

**Comment by CreepinGenius** [comment]
so there's **nothing** I can do about that? couldn't I copy these files manually or something?

**Comment by kovidgoyal** [comment]
The files are already there. There is nothing to copy, your OS is setup
to disallow RPATH based linking. Use a different OS or build from source
to avoid RPATH based linking.

**Comment by CreepinGenius** [comment]
so building kitty from source should work?

**Comment by kovidgoyal** [comment]
No idea, depends on how badly Cubes fucks up its environment. I can tell
you building from source doesnt use RPATH.

**Comment by kovidgoyal** [comment]
I just showed you kitty works out of thebox even in debian oldstable aka debian 11. 

https://github.com/kovidgoyal/kitty/issues/7731#issuecomment-2295106790

**Comment by andrewbernard** [comment]
I was not clear. I can't build from source on Debian 12 as python fails due to not being able to find this library, even though I understand it downloads all its dependencies. I should have been more specific.

**Comment by kovidgoyal** [comment]
If python is failing on your machine then you need to fix that, it has nothing to do with kitty.

**Comment by andrewbernard** [comment]
It's the Python that is downloaded with dev.sh. Python works fine in Debian. All the best for your endeavours anyway.

**Comment by kovidgoyal** [comment]
I really dont understand. You posted you are having the exact same issue on a bug report about RUNNING KITTY. But apparently you are trying to build kitty instead. If dev.sh is not working for you, simply install the dependencies and build it against the system libs instead. dev.sh is a convenience service not something I guarantee will work everywhere.
