### ISSUE TITLE
Tab title truncation point should be configurable

### ISSUE THREAD

**Issue by jmpolom** [kovidgoyal/kitty#7732]
**Is your feature request related to a problem? Please describe.**
Kitty truncates tab titles at the end of the title. If one sets shell title based on shell pwd and has numerous open tabs deep into a directory structure (a long title), kitty may end up truncating the "interesting" and useful part of the title (ex: the cwd). Consequently you may end up with a bunch of tabs that all have the same visible title with ... at the end but the cwd is different and not visible.

**Describe the solution you'd like**
Truncation should be configurable either as the beginning or end of the title string.

**Describe alternatives you've considered**
If the title is being set by a shell rc/config this could be configured to just truncate the set title at the beginning or end (user preference) if it's over a certain length. But this won't take into account the actual tab size on the screen and is pretty inflexible not to mention something that does not belong in a shell rc.

Configuring `tab_title_template` is not really an option for this because only a generic `{title}` place holder is available. The truncation is occurring in a way which does not appear configurable via the existing tab title config options.

**Comment by kovidgoyal** [comment]
The title comes from your shell. Configure it to send whatever form of
title you like, various shells have various ways of truncating long
paths.
