### ISSUE TITLE
0.36 version is crashing on macOS after installation

### ISSUE THREAD

**Issue by ankitsharma07** [kovidgoyal/kitty#7738]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               kitty [24850]
Path:                  /Applications/kitty.app/Contents/MacOS/kitty
Identifier:            net.kovidgoyal.kitty
Version:               0.36.0 (0.36.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-08-18 21:29:45.2804 +0530
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Bridge OS Version:     8.5 (21P5077)
Anonymous UUID:        9690C556-21DF-21E6-F999-AF6A69DDFBE9

Sleep/Wake UUID:       5151DB1C-BD61-4E66-921B-A315CB9C1714

Time Awake Since Boot: 410000 seconds
Time Since Wake:       1143 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000010cb6f000
Exception Codes:       0x0000000000000001, 0x000000010cb6f000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [24850]

VM Region Info: 0x10cb6f000 is not in any region.  Bytes after previous region: 1  Bytes before following region: 105548607983616
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      mapped file                 10c900000-10cb6f000    [ 2492K] r--/rw- SM=COW  Object_id=484d7c3b
--->  GAP OF 0x5ffef3491000 BYTES
      MALLOC_NANO              600000000000-600020000000 [512.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	    0x7ff81987d609 _platform_memmove$VARIANT$Haswell + 41
1   Python                        	       0x10612cb81 PyBytes_FromStringAndSize + 225
2   Python                        	       0x10630fe8e va_build_stack + 158
3   Python                        	       0x10613da4e _PyObject_CallFunctionVa + 94
4   Python                        	       0x10613e074 _PyObject_CallFunction_SizeT + 164
5   Python                        	       0x1061f63c0 unicode_decode_call_errorhandler_writer + 224
6   Python                        	       0x1061f3764 unicode_decode_utf8 + 2468
7   Python                        	       0x10630ea51 do_mkvalue + 1121
8   Python                        	       0x10630fc60 _Py_BuildValue_SizeT + 208
9   kitty.fast_data_types.so      	       0x10552d4e6 0x105513000 + 107750
10  Python                        	       0x10614e9cb method_vectorcall_NOARGS + 107
11  Python                        	       0x10628da4c _PyEval_EvalFrameDefault + 63052
12  Python                        	       0x10613bdcf _PyObject_FastCallDictTstate + 95
13  Python                        	       0x1061d2de2 slot_tp_call + 194
14  Python                        	       0x10613b921 _PyObject_MakeTpCall + 129
15  Python                        	       0x10628dc1a _PyEval_EvalFrameDefault + 63514
16  Python                        	       0x10627d38b PyEval_EvalCode + 299
17  Python                        	       0x1062788fd builtin_exec + 445
18  Python                        	       0x1061a7d7b cfunction_vectorcall_FASTCALL_KEYWORDS + 75
19  Python                        	       0x10628da4c _PyEval_EvalFrameDefault + 63052
20  Python                        	       0x1063555bc pymain_run_module + 268
21  Python                        	       0x106354e68 pymain_run_python + 1192
22  Python                        	       0x106354977 Py_RunMain + 23
23  kitty                         	       0x104af4819 0x104aee000 + 26649
24  kitty                         	       0x104af391b main + 2411
25  dyld                          	    0x7ff8194c5366 start + 1942

**Comment by kovidgoyal** [comment]
dup of #7734
