### ISSUE TITLE
Kitty Auto Highlights When I Type

### ISSUE THREAD

**Issue by theovo** [kovidgoyal/kitty#7739]
When I start typing, Kitty automatically highlights the words I type. It doesn't happen in Terminal, nor any other application. I've used Kitty for a while now. It's the first time this is happening.

![kitty](https://github.com/user-attachments/assets/6b0ce692-3200-4b8e-9d45-a032000d04c8)

Currently Running:
kitty 0.36.0 (d8db17c513)
macOS Ventura 13.6.9

**Comment by kovidgoyal** [comment]
You need to follow the issue template when reporting issues. From your screenshot that looks like you have enabled the marks feature in kitty.conf. Disable it again. That's the only thing in kitty that can cause highlighting of screen content. If it isnt that, the highlighting will be comeing from your shell rc files.
