### ISSUE TITLE
Invisible text and double tab bar  

### ISSUE THREAD

**Issue by aequitas** [kovidgoyal/kitty#774]
Sorry upfront that I'm unable to provide a replication cause for this problem, but I just don't know why it triggers. If I find out I'll update on it, but I have the following problem for a few weeks now and I'm just unable to find out why.

Sometimes when I switch back to kitty from another window all text in the terminal is invisible. The cursor is visible and at the place I would expect for the prompt. I can give input, output is generated, but it is just not visible. Hyperlinks in the invisible text do produce a hyperlink mousecursor and the links can be clicked. Also I have kitty configured with tabbar at the bottom but when this happens there is a second tabbar at the top. This tabbar however is not functional. Only one tab is affected so the other tabs in the window work just fine. But sometimes this happens to multiple tabs. 

I have found no way yet to solve this other than to exit the shell and create it again.

Opening scrollback history for this tab does render the content fine (and without double tab bar) but when that mode is exited the tab is still 'broken' (see screenshot below).

It is really hard to reproduce this reliably, some days it happens a few times, other time it doesn't happen for days.

Kitty 0.11.3 on Ubuntu Linux 18.04

Config:
```
adjust_line_height 1
window_alert_on_bell no
bell_on_tab no
enable_audio_bell no

kitty_mod super

map kitty_mod+t new_tab
map kitty_mod+w close_tab
map kitty_mod+[ previous_tab
map kitty_mod+] next_tab
map kitty_mod+shift+right move_tab_forward
map kitty_mod+shift+left move_tab_backward
map kitty_mod+1 goto_tab 1map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+0 goto_tab 10
map kitty_mod+n new_os_window

map kitty_mod+y new_os_window @ansi less +G -R
map ctrl+shift+h show_scrollback

map page_up scroll_page_up
map page_down scroll_page_down
map page_home scroll_page_home
map page_end scroll_page_end
map kitty_mod+minus change_font_size all -1.0map kitty_mod+shift+equal change_font_size all +1.0
```

Defunkt tab with cursor at position after the prompt (as expected):
![image](https://user-images.githubusercontent.com/365827/43409777-282df728-9425-11e8-8219-1617dfc64b48.png)

Tab content after `show_scrollback`:
![image](https://user-images.githubusercontent.com/365827/43410110-1ecfeaf0-9426-11e8-841f-ce2285cd3470.png)

**Comment by kovidgoyal** [comment]
I doubt this has anything to do with kitty directly, but more to do with the shell. You can test that by using the key combination to reset the terminal. (ctrl+shift+backspace) Note however that this is not available in released kitty, so you will either have to build from source or wait for the next release.

**Comment by kovidgoyal** [comment]
Actually never mind the double tab bar makes it more likely a kitty problem. Redirect kitty stdout/stderr to a log file and see if anything is printed there when this problem happens.

```
kitty > /tmp/log 2 > /tmp/log

**Comment by aequitas** [comment]
Thanks for the quick response. I'll see what I can find that way and report back.

**Comment by kovidgoyal** [comment]
You're welcome. And if you can find steps to reproduce the problem reliably, with only a single tab, you can use the --dump-bytes debug option to kitty to create a dump that I can use to reproduce the issue.

**Comment by aequitas** [comment]
Ok, so I've been running with log output capturing for a week, had two occasions where a tab would go dark. Both don't show anything in the logging[0] (stdout or stderr) that seems related as timestamps don't match up and these message are in the logging regardless of black tabs.
```
[214 15:48:02.188447] [PARSE ERROR] Unknown CSI code: 'b' with start_modifier: '^@' and end_modifier: '^@' and parameters: '146'
...
[218 17:30:30.498174] [PARSE ERROR] Unknown CSI t sequence with start and end modifiers: '^@' '^@' and 3 parameters
...
[218 17:32:36.012120] [PARSE ERROR] Unsupported screen mode:  1034 (private)
```
I'll build the latest release and try if the terminal reset does anything.

**Comment by kovidgoyal** [comment]
Yeah those errors are not relevant -- they mean that the application sent kitty some terminal escape codes it does not understand, which it logs and ignores.
