### ISSUE TITLE
Kitty Keyboard Protocol Spec: Limit amount of associated text

### ISSUE THREAD

**Issue by mnemnion** [kovidgoyal/kitty#7749]
The spec as written allows for any number of codepoints to be included as associated text:

> If multiple code points are present, they must be separated by colons.

This is an unreasonable specification to implement in a language without a garbage collector, as it means that a reported key event cannot be fit into a struct or union of a fixed size.  Without this, the only terminal reports of arbitrary length are paste-bracketed text, which may be included in a report by including a pointer and length of the region of the buffer containing the pasted text.  (I'm aware there are others, but they share the feature of being unencoded plain text, which the KKP associated text is not).

The equivalent of this would be something like a special reporting event which refers to the fixed length of the in buffer containing the untranslated colon-separated codes, which is awkward.   Otherwise it is impossible to write a spec-compliant reader which doesn't dynamically allocate memory. 

Are there circumstances where Kitty itself reports more than one code point here? What about other terminals? Is there some reasonable limit on their number? Could we add some language like "a conformant reader may ignore more than N codepoints" so that terminal implementers know not to send more than that? 

I'll return a slice of raw CSI if I have to, but this is an unsatisfactory approach to the problem.

**Comment by kovidgoyal** [comment]
On Mon, Aug 19, 2024 at 12:01:58PM -0700, Sam Atman wrote:
> The spec as written allows for any number of codepoints to be included as associated text:
>
> > If multiple code points are present, they must be separated by colons.
>
> This is an unreasonable specification to implement in a language without a garbage collector, as it means that a reported key event cannot be fit into a struct or union of a fixed size.  Without this, the only terminal reports of arbitrary length are paste-bracketed text, which may be included in a report by including a pointer and length of the region of the buffer containing the pasted text.  (I'm aware there are others, but they share the feature of being unencoded plain text, which the KKP associated text is not).

What nonsense. If you are writing in a language without a garbage
collector I suggest you learn how to do manual memory management.
Despite all the internet hand waving to the contrary, it's not that
hard.

And incidentally there are literally hundreds of escape codes that are
not fixed length, ranging from SGR to OSC, APC, PM, and so on.

>
> The equivalent of this would be something like a special reporting event which refers to the fixed length of the in buffer containing the untranslated colon-separated codes, which is awkward.   Otherwise it is impossible to write a spec-compliant reader which doesn't dynamically allocate memory.

You cannot do that anyway. Escape codes are *not* fixed length
regardless of the KKP.

>
> Are there circumstances where Kitty itself reports more than one code point here? What about other terminals? Is there some reasonable limit on their number? Could we add some language like "a conformant reader may ignore more than N codepoints" so that terminal implementers know not to send more than that?

Yup, any IME is free to send any number of codepoints to a program in
response to a single key event. The KKP closely models the state of
reality.

**Comment by mnemnion** [comment]
The spec allows the entire King James Bible to be sent as decimal-encoded codepoints. I don't think that reflects reality.

> You cannot do that anyway. Escape codes are *not* fixed length
regardless of the KKP.

This comment is about the size of the input, my concern is with the size of the parsed output. Different things entirely. The parser receives a buffer, which is already allocated. Sequences of indefinite length, such as paste bracketing, and OSC reports, can be referred to with one pointer and one offset from that pointer: the client can then copy over that memory and use it, because it's encoded as plain text. 

As I said in the initial post, the problem with literally unlimited amounts of associated text is that it's ASCII decimal encoded. So yes, an unsatisfactory solution to the dilemma posed by that is to provide a pointer and offset to the offending decimal-encoded-colon-separated sequence, and let the client deal with turning it into something usable.  

Or, my parser must require an allocator, just for this one unreasonable task, which is nonsense: now instead of placing the parsed input on the stack, clients have to detect allocation and handle freeing it accordingly. 

> And incidentally there are literally hundreds of escape codes that are not fixed length, ranging from SGR to OSC, APC, PM, and so on.

You're not telling me anything new here. This isn't about the receiving buffer, this is about the parsed form of the input.  Show me a specific input from a terminal which is not either of fixed dimensions or encoded as plain text.  [Terminal Guide](https://terminalguide.namepad.de/seq/), which is of course not complete, but is at least suggestive, doesn't even have a notation for this. It has (n) for a number, (c) for cursor attributes (which also parse to a finite length), (b) for a data buffer, and (s) for a string. The latter two can be provided as a view.  

If the intention is to support arbitrary text, the protocol should do what every other input sequence containing arbitrary text does, and provide it in an unencoded form.  This could be the existing CSI u followed by some sort of OSC N; [text] ST, to be compatible with existing sequences of this nature.

If the intention is, however, to allow a *grapheme* to be included, that's a different story. To quote [Unicode](http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries):

> Degenerate Cases. The default specifications are designed to be simple to implement, and provide an algorithmic determination of grapheme clusters. However, they do not have to cover edge cases that will not occur in practice. For the purpose of segmentation, they may also include degenerate cases that are not thought of as grapheme clusters, such as an isolated control character or combining mark. In this, they differ from the combining character sequences and extended combining character sequences defined in [[Unicode](http://www.unicode.org/reports/tr41/tr41-32.html#Unicode)].

That rule is there to prevent the sort of denial-of-service attacks you've inadvertently written into this standard, where a bad actor sends a crafted input which obeys the superficial combining rules of a single grapheme cluster, but which is, potentially, many megabytes in size. 

There's no normative reference on this question, unfortunately, but [this post](https://ardislu.dev/biggest-unicode-grapheme-cluster) finds an 11 codepoint Emoji cluster. The section on [conjoining Jamo](https://www.unicode.org/versions/Unicode15.0.0/UnicodeStandard-15.0.pdf) in the Unicode standard identifies three codepoints as the maximum combining form. 🏴󠁧󠁢󠁳󠁣󠁴󠁿 is seven codepoints. It strikes me as exceedingly unlikely that a Brahmic script would have a combined form with more codepoints than 11. 

To offer a generous buffer for future emojification of Unicode, the KKP standard could provide a limit of, let's say, 24 codepoints.  This would allow reader implementations to preallocate a scratch buffer for translating those codepoints to a textual form, which could be provided as a view when this sort of sequence is encountered.  There is [active discussion in the Unicode consortium](https://www.unicode.org/L2/L2023/23140-graphemes-expectations.pdf) about creating and publishing a reasonable maximum size for conforming implementations, exactly because Zalgo text is an unanticipated abuse of the standard.  If future Unicode editions are published, the KKP standard can be updated to indicate that maximum value. 

Or you could leave this flawed and insecure requirement in your protocol. I urge you to reconsider.

**Comment by kovidgoyal** [comment]
On Tue, Aug 20, 2024 at 09:42:40AM -0700, Sam Atman wrote:
> The spec allows the entire King James Bible to be sent as decimal-encoded codepoints. I don't think that reflects reality.
>
> > You cannot do that anyway. Escape codes are *not* fixed length
> regardless of the KKP.
>
> This comment is about the size of the input, my concern is with the size of the parsed output. Different things entirely. The parser receives a buffer, which is already allocated. Sequences of indefinite length, such as paste bracketing, and OSC reports, can be referred to with one pointer and one offset from that pointer: the client can then copy over that memory and use it, because it's encoded as plain text.

Have you ever written a parser of anything in your life? You are willing
to allocate buffers for input but not output!! That alone tells me all I
need to know about your level of competence. Good luck to you.

>
> As I said in the initial post, the problem with literally unlimited amounts of associated text is that it's ASCII decimal encoded. So yes, an unsatisfactory solution to the dilemma posed by that is to provide a pointer and offset to the offending decimal-encoded-colon-separated sequence, and let the client deal with turning it into something usable.

So what? Decode it and then pass it to your clients. Or better yet leave
writing parsers to people with a minimum level of competence.

>
> Or, my parser must require an allocator, just for this one unreasonable task, which is nonsense: now instead of placing the parsed input on the stack, clients have to detect allocation and handle freeing it accordingly.
>
> > And incidentally there are literally hundreds of escape codes that are not fixed length, ranging from SGR to OSC, APC, PM, and so on.
>
> You're not telling me anything new here. This isn't about the receiving buffer, this is about the parsed form of the input.  Show me a specific input from a terminal which is not either of fixed dimensions or encoded as plain text.  [Terminal Guide](https://terminalguide.namepad.de/seq/), which is of course not complete, but is at least suggestive, doesn't even have a notation for this. It has (n) for a number, (c) for cursor attributes (which also parse to a finite length), (b) for a data buffer, and (s) for a string. The latter two can be provided as a view.

Google OSC 52. Not of fixed length and not encoded as plain text. Or
XTGETTCAP.

>
> If the intention is to support arbitrary text, the protocol should do what every other input sequence containing arbitrary text does, and provide it in an unencoded form.  This could be the existing CSI u followed by some sort of OSC N; [text] ST, to be compatible with existing sequences of this nature.
>
> If the intention is, however, to allow a *grapheme* to be included, that's a different story. To quote [Unicode](http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries):

Pay attention, IME systems can pass arbitrary amounts of text in response
to key events. The protocol is designed to handle this.

>
> > Degenerate Cases. The default specifications are designed to be simple to implement, and provide an algorithmic determination of grapheme clusters. However, they do not have to cover edge cases that will not occur in practice. For the purpose of segmentation, they may also include degenerate cases that are not thought of as grapheme clusters, such as an isolated control character or combining mark. In this, they differ from the combining character sequences and extended combining character sequences defined in [[Unicode](http://www.unicode.org/reports/tr41/tr41-32.html#Unicode)].
>
> That rule is there to prevent the sort of denial-of-service attacks you've inadvertently written into this standard, where a bad actor sends a crafted input which obeys the superficial combining rules of a single grapheme cluster, but which is, potentially, many megabytes in size.
>
> There's no normative reference on this question, unfortunately, but [this post](https://ardislu.dev/biggest-unicode-grapheme-cluster) finds an 11 codepoint Emoji cluster. The section on [conjoining Jamo](https://www.unicode.org/versions/Unicode15.0.0/UnicodeStandard-15.0.pdf) in the Unicode standard identifies three codepoints as the maximum combining form. 🏴󠁧󠁢󠁳󠁣󠁴󠁿 is seven codepoints. It strikes me as exceedingly unlikely that a Brahmic script would have a combined form with more codepoints than 11.
>
> To offer a generous buffer for future emojification of Unicode, the KKP standard could provide a limit of, let's say, 24 codepoints.  This would allow reader implementations to preallocate a scratch buffer for translating those codepoints to a textual form, which could be provided as a view when this sort of sequence is encountered.  There is [active discussion in the Unicode consortium](https://www.unicode.org/L2/L2023/23140-graphemes-expectations.pdf) about creating and publishing a reasonable maximum size for conforming implementations, exactly because Zalgo text is an unanticipated abuse of the standard.  If future Unicode editions are published, the KKP standard can be updated to indicate that maximum value.
>
> Or you could leave this flawed and insecure requirement in your protocol. I urge you to reconsider.

Or I can just ignore nonsense spouted by morons. You are concerned about
DDOS then write a maximum size for the input in your parser. Which you
have to do anyway because again, ESCAPE CODES ARE NOT FIXED SIZE AND RAM
IS FINITE.

There is absolutely no reason the STANDARD should impose a limit on
IMPLEMENTATIONS.

I have wasted enough of my precious time on you. Good bye.
