### ISSUE TITLE
Is there any easier than escape shortcut for going to normal mode?

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#775]
I have a problem with navigating inside my commands. I mean for example when I want to run the last command with sudo I press up and then I have a problem:D what I used to do before was using the home button and then typing sudo and then pressing enter. but home and end buttons behave very strange in kitty. I can't find out what they do in the docs. So what I do now is pressing escape and then ^/0 and then i and then typing and then enter. which is a little hard especially for the escape part. I would like to know how one does such things. also I want to know how I can select what I've written. before I used to use shift + end/home/arrow_keys but that doesn't work in kitty also. and also shift overrides numlock for me.

**Comment by kovidgoyal** [comment]
Terminals do not process keystrokes (apart from their own shortcuts). Your shell does that. If your shell is not handling keys properly then it is likely because you have changed the value of TERM. Make sure TERM is xterm-kitty and you should be fine.
