### ISSUE TITLE
Split `kitty.conf` into "unit files"

### ISSUE THREAD

**Issue by pearagit** [kovidgoyal/kitty#7750]
**Is your feature request related to a problem? Please describe.**

A single large `kitty.conf` can be cumbersome to maintain, especially when updates to kitty include a change to the default config

**Describe the solution you'd like**

Consider adopting some standard such as [systemd's "drop-in" directory](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html):

> Along with a unit file foo.service, a "drop-in" directory foo.service.d/ may exist. All files with the suffix ".conf" from this directory will be merged in the alphanumeric order and parsed after the main unit file itself has been parsed. This is useful to alter or add configuration settings for a unit, without having to modify unit files.

**Describe alternatives you've considered**

The solution I've chosen for myself is to copy the default `kitty.conf`, and add a `globinclude kitty.conf.d/*.conf` directive to load the respective top-level folds in kitty.conf:

![Screenshot from 2024-08-19 14-48-25](https://github.com/user-attachments/assets/5911dad9-2b9c-4e14-b919-ad973923bbd7)

**Additional context**

--

**Comment by kovidgoyal** [comment]
IMO having a single file is much better because it allows searching
through the entire config easily when editing it.

If you want to split it up, then globinclude exists for you, as you
discovered.

**Comment by kovidgoyal** [comment]
Yeah no worries, I just prefer the ease of having everything in one
file by default.
