### ISSUE TITLE
OSC7 does not work as expected

### ISSUE THREAD

**Issue by neurocyte** [kovidgoyal/kitty#7754]
**Describe the bug**
I have observed that kitty occationally opens the wrong directory in a new window when working in my editor Flow Control. In an attempt to reproduce this behaviour for a bug report wrote a small script to test OSC7. This does not work at all in kitty although it works in all other terminals tested. This is the same escape code format sent by Flow, but there it mostly works, just not reliably.

**To Reproduce**
1. Start kitty: `kitty --config=NONE --override "map=ctrl+alt+enter launch --cwd=current sh" sh`
2. Execute this test script:
```
#!/bin/sh
set -e

HOSTNAME=$(hostname -s)

open_dir() {
    DIR="$1"
    mkdir -p "$DIR"
    printf '\x1b]7;file://%s%s\x1b\\' "$HOSTNAME" "$DIR"
    printf 'sent osc7: file://%s%s \n' "$HOSTNAME" "$DIR"
    printf 'open new window now or press enter to continue \n'
    read -r _
}

open_dir "/tmp/a"
open_dir "/tmp/b"
open_dir "/tmp/c"
open_dir "/tmp/a"
```
4. Open new windows with ctrl+alt+enter as instructed
5. Check the cwd in then new window with `pwd`. Kitty does not open the expected directory.

**Environment details**
```
kitty 0.35.2 (d7902f6b24) created by Kovid Goyal
Linux dent 6.10.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 x86_64
Arch Linux 6.10.5-arch1-1 (/dev/tty)
```

**Additional context**
I did not succeed in reproducing the original bug I was looking for because kitty doesn't seem to react to OSC7 at all in my test script. This script works just as expected in foot, ghostty, wezterm, gnome-terminal, gnome-console and konsole.

Here is an example run on my machine with kitty:
![image](https://github.com/user-attachments/assets/cde6d951-fef7-4a76-b922-8428e74ff926)

**Comment by neurocyte** [comment]
I re-tested with latest master:
```
kitty 0.36.0 (6d06415ec5) created by Kovid Goyal
Linux dent 6.10.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 x86_64
Arch Linux 6.10.5-arch1-1 (/dev/tty)
```

**Comment by neurocyte** [comment]
Btw, the actual bug I was trying to reproduce is that kitty ignores repeated directories in OSC7 messages sent by Flow. i.e The last line of the test does not work in Flow. The first three do.

**Comment by kovidgoyal** [comment]
Use --cwd=last_reported and you will be fine.

--cwd=current means use the CWD of the current foreground process in the
window.
