### ISSUE TITLE
Kitty for Windows

### ISSUE THREAD

**Issue by ManiArasteh** [kovidgoyal/kitty#7755]
Please release kitty for Windows. If not working, try to optimize for it. Because Windows is the most popular and as Microsoft reported in April 2022, Over 1.4 billion of computers running Windows, Linux is very popular on phones, not computers and MacOS is running on only 5% of computer. If you won't release it, Kitty will only run on 6% of computers

**Comment by kovidgoyal** [comment]
dup of #640

**Comment by ManiArasteh** [comment]
Duplicate of another closed issue. Make this open!

**Comment by ManiArasteh** [comment]
Other, I report this app

**Comment by kovidgoyal** [comment]
Go right ahead.

**Comment by ManiAra2** [comment]
Hahaha! I'm here! From another account

**Comment by inoperable** [comment]
> Because

We are happy being unpopular :]

**Comment by BrycensRanch** [comment]
![image](https://github.com/user-attachments/assets/557eea2d-5771-4fc8-ae73-f4525809d85c)

The year of the Windows Kitty desktop is here!
