### ISSUE TITLE
Kitty Server like Foot server?

### ISSUE THREAD

**Issue by turbomaster95** [kovidgoyal/kitty#7756]
**Is your feature request related to a problem? Please describe.**
Foot is faster at starting on my computer than kitty as kitty starts a new process every time it starts, while foot has a server running in the background and the footclient connects to it instead of starting a new process.

**Describe the solution you'd like**
add a kind of "kitty --server" 

**Describe alternatives you've considered**
Foot Terminal

**Additional context**

**Comment by trygveaa** [comment]
See https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-single-instance
