### ISSUE TITLE
more apps supporting kitty's keyboard protocol

### ISSUE THREAD

**Issue by unxed** [kovidgoyal/kitty#7763]
Kitty's keyboard protocol has been added to several apps and frameworks:

1. `Free Vision` — Free Pascal's Turbo Vision fork
https://gitlab.com/freepascal.org/fpc/source/-/issues/40673#note_2061428120

2. Another modern `Turbo Vision` implementation, in C++
https://github.com/magiblot/tvision/commit/6e5a7b46c6634079feb2ac98f0b890bbed59f1ba
Also `turbo`, console text editor based on this framework
https://github.com/magiblot/turbo/commit/b2e279b573bf6e4905f4cbadd9412fd9be003a55

3. `far2l` file manager now implements kitty's protocol not only in it's tty rendering backend, but in it's internal virtual terminal also:
https://github.com/elfmz/far2l/pull/2347

Please add to compatible software list.

**Comment by kovidgoyal** [comment]
that is built from source with every kitty release.

**Comment by unxed** [comment]
Web page layout is disturbed in FreeVision line, pls check

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/2c01405d85d24c0575eb8d0e03a8e1ca68f3e359
