### ISSUE TITLE
Negative padding values

### ISSUE THREAD

**Issue by fabolous005** [kovidgoyal/kitty#7764]
**Is your feature request related to a problem? Please describe.**
When using kittys panel feature i would like to have the options to cut out a little bit of the window.

**Describe the solution you'd like**
My idea is to support negative padding values

**Describe alternatives you've considered**
None come to mind, but if you guys have an idea...

This would for example allow to hide a few pixels of the bottom of cava.
![image](https://github.com/user-attachments/assets/7f49e4ec-5014-432b-8434-e02edce7d1df)

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but patches are welcome.
