### ISSUE TITLE
Keyboard shorcut doesn't work all the time

### ISSUE THREAD

**Issue by hanoii** [kovidgoyal/kitty#7769]
I am having trouble understanding why a keyboard mapping doesn't always work.

I have the following:

```
map cmd+shift+t launch --cwd=current --type=background fish -c "ddev tableplus"
map cmd+shift+d>t launch --cwd=current --type=background fish -c "ddev tableplus"
```

The second one works all the time. but the first one doesn't. Most often it just doesn't work. In tracking this and using `kitty --debug-input` I get the follwing:

```
---------------- key down -------------------
NSEvent: type=KeyDown loc=(354.289,72.8438) time=314148.5 flags=0x12010a win=0x12be9f1a0 winNum=28082 ctxt=0x0 chars="t" unmodchars="T" repeat=0 keyCode=17
2024-08-22 09:53:48.774 kitty[58303:7506679] Unable to find object to handle service <_NSServiceEntry - 0x60000172e900:
	bundleIdentifier:		net.kovidgoyal.kitty
	bundlePath:			/Applications/kitty.app
	executablePath:			(null)
	defaultTitle:			New kitty Tab Here
	localizedTitleWithoutSubstitutions:			New kitty Tab Here
	defaultKeyboardShortcut:	<NSKeyboardShortcut: 0x600002b95440 ()>
	keyboardShortcut:		<NSKeyboardShortcut: 0x600002ba7ac0 (⇧⌘T)>
	message:			openTab
	portName:			(null)
	sendPasteboardTypes:		[dyn.agu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn, public.plain-text]
	returnTypes:			[(null)]
	userData:			(null)
	languages:			[(null)]
	required context: (
    "<_NSServiceFilter: 0x600000f0f1e0 contents: File Path>"
)>
keyDown triggered global menu bar action ignoring
```

One strange thing is that if I launch `kitty --debug-input` from another kitty window, the shortcut works on the window that's showing the debug output but doesn't on the new window that was open and triggers the above without the shortcut working 🤔 .

Any advise?

**Comment by kovidgoyal** [comment]
This is because cmd+shift+t is the macos global "openTab" service
shortcut. When you run kitty normally that service is defined via the
plist file in app bundle. When you run kitty as a standalone binary that
plist file is not read. There is no way for kitty to override this
shortcut since its a macos global one. So I recommend picking another
key combination for it, or disable it globally in macOS.
