### ISSUE TITLE
fcitx key combo doesn't work with kitty

### ISSUE THREAD

**Issue by yzhou61** [kovidgoyal/kitty#777]
When I'm in kitty, using the fcitx combo key doesn't work. Normally in other applications (firefox, rxvt, etc.) the combo key would switch fcitx to the desired input method. It feels like kitty is not properly forwarding the key combo to the system.

I even tried mapping the key combo in question to `no_op` in kitty's config.

If this is an easy problem to solve, great. Otherwise, I'd be interested to look into it if someone can give me some pointers.

Thanks.

**Comment by kovidgoyal** [comment]
See #469
