### ISSUE TITLE
Blck walyand/ x11 sleep when command is active

### ISSUE THREAD

**Issue by solomoncyj** [kovidgoyal/kitty#7792]
**Is your feature request related to a problem? Please describe.**
When sleep is not manualy blocked, 

**Describe the solution you'd like**
If the command run is not a static command (eg editors like nano, shells like bash), kitty does not block sleep, how ever if it is an active process, eg make, fsck and sudo  sleep should be blocked

**Describe alternatives you've considered**
Manualy blocking sleep from de control panel

**Additional context**

**Comment by kovidgoyal** [comment]
I have no idea what "blocking sleep" means. If you mean prevents the
monitor from going to sleep, kitty has no code to do that, ever.

**Comment by kovidgoyal** [comment]
And if you are saying that it should block sleep when  make is running or whatever, then I absolutely dont see why that would be the case. Why would running make mean the monitor should not sleep? If you were serious about this, there would need to be an escape code based protocl for blocking monitor sleep, that terminal programs could optionally use.

**Comment by solomoncyj** [comment]
![image](https://github.com/user-attachments/assets/8a2d5051-7017-454f-858d-5f0ca92fea59)
Sleeping means suspending system state to ram and stopping the cpu. this also stops the execution of current applications, if they did not block sleep. if the system sleeps while  command is running, no work is done while the system is sleeping, which is a waste of time

**Comment by solomoncyj** [comment]
we do not need to block screen locking as tasks can still run while the screen is locked

**Comment by kovidgoyal** [comment]
Sorry I am *definitely* not going to block system suspend when a command
is running. If you have configured your system to go to sleep, I suggest
you unconfigure it to do that. Sleep only when the lid is closed. It is
*defnitely* not a terminal emulators job to insert itself into system
sleep policies.

**Comment by neurocyte** [comment]
Run your command with `caffinate -i <cmd...>` and your mac will not sleep until the command exits. There is no need for kitty to get involved.

**Comment by solomoncyj** [comment]
`systemd-inhibit` also does the job. just need to discriminte which commands do not get to use it
