### ISSUE TITLE
Can't control kitty over TCP

### ISSUE THREAD

**Issue by hainkind** [kovidgoyal/kitty#7794]
**Describe the bug**
So I'm trying to control kitty over my home network. I can see and reach the ports but kitty won't talk to them. It works on the same machine.

![image](https://github.com/user-attachments/assets/53fc1dac-93f0-4526-9c79-de59b2e75624)

![image](https://github.com/user-attachments/assets/475763ab-e7f3-4435-bad6-4d479b1f5c01)

any ideas what's going on? or did i misunderstood the feature?

**Comment by kovidgoyal** [comment]
If you ask kitty to listen on localhost then you can only connect on
localhost. You need to choose the proper address to listen on,
presumably the IP address of whatever network card is connected to
your LAN

**Comment by hainkind** [comment]
i had kitty listen on 0.0.0.0

**Comment by hainkind** [comment]
otherwise nmap and nc shouldn't have been able to connect to it....

**Comment by hainkind** [comment]
it also doesn't work if directly specify the interface to listen on e.g. 
listen_on tcp:192.168.178.20:12345

if it would be a networking issue i should't be able to connect with nc.

i know assuming that everybody is stupid is a good heuristic 90% of the time, but i think this time you're wrong.

**Comment by kovidgoyal** [comment]
> i had kitty listen on 0.0.0.0

Since you didnt bother including this or indeed any of the information asked for in the issue template, how am I supposed to know that? Reading your mind? Magic? Wasting my time peering at your screenshots trying to figure out what you are doing?

Given your attitude I have zero desire to help you. Good luck figuring out your issue and if you do figure it out feel free to send a PR.

**Comment by hainkind** [comment]
sorry i don't have much time atm and i thought that the screenshots explain it better then many words.
but i have to admit that ignoring your template and expecting you to figure my screenshots out is a bit of a dick move. Sorry!

**Comment by kovidgoyal** [comment]
No worries. It issue is already fixed in master in anycase:
https://github.com/kovidgoyal/kitty/commit/fdc3c3d7c1fd503785ebbd9a531f55ca1e4493b6
