### ISSUE TITLE
"Keep terminal window after command execution" not respected (integration with PCManFM)

### ISSUE THREAD

**Issue by belkka** [kovidgoyal/kitty#7801]
I use PCManFM 1.3.2 as my file manager, and I've set `kitty` as a "Terminal Emulator" in pcmanfm settings (see screenshot 1).

**Steps to reproduce** the behavior:
1. Right click any file in pcmanfm
2. Select "Open with..."
3. Open "Custom Command Line" tab
4. Write some command in "Command line to execute", e.g., `file %f`
5. Enable checkboxes "Execute in terminal emulator" and "Keep terminal window open after command execution"
6. Press "OK"

I **expected** that the terminal window is kept open after command execution, so that I can read the output, then close window manually.

**Instead**, I see some black window (assumably, kitty) appears for a brief moment, then disappears.

The presense of "Keep terminal window open after command execution" option in a file manager suggests that there may be some kind of communication protocol between applications (like pcmanfm) and terminals to tell the terminal to be run in "do not auto-close" mode (environment variable? widely used command line option?). Apparently, pcmanfm and kitty fail to communicate about that.

Could it be an issue with my configuration? Could it be an issue in PCManFM?

![screenshot 1, pcmanfm settings](https://github.com/user-attachments/assets/ce3e2e69-5886-415d-8667-10c60ebc4195)
![open with...](https://github.com/user-attachments/assets/b50e068a-a11b-4518-88a7-856848a1cf90)

**Environment details**
```
kitty 0.35.2 created by Kovid Goyal
Linux BComputer2 6.10.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Sun, 11 Aug 2024 16:19:06 +0000 x86_64
Arch Linux 6.10.4-arch2-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
OpenGL: '3.1.0 NVIDIA 555.58.02' Detected version: 3.1
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/user/.config/kitty/kitty.conf
```

**Comment by kovidgoyal** [comment]
Not sure what this is has to do with kitty. If you want kitty to stay
open after the program you asked it to run terminates, use the --hold
command line option. You will need to configure pcman or whatever to use
this option.

**Comment by belkka** [comment]
> Not sure what this is has to do with kitty

@kovidgoyal Did you read this paragraph?

> The presense of "Keep terminal window open after command execution" option in a file manager suggests that there may be **some kind of communication protocol** between applications (like pcmanfm) and terminals to tell the terminal to be run in "do not auto-close" mode (environment variable? widely used command line option?). Apparently, pcmanfm and kitty fail to communicate about that.

**Comment by belkka** [comment]
I'm not sure. I only see this one https://github.com/kovidgoyal/kitty/issues/7801#issuecomment-2316953755. Are there any others?
