### ISSUE TITLE
Monoid Nerd Font Bold looks very blurry since kitty v0.36

### ISSUE THREAD

**Issue by Schweber** [kovidgoyal/kitty#7802]
**Describe the bug**
I've been using kitty for several years with Monoid Nerd Font and it always looked crisp. Since kitty v0.36 the bold version looks very blurry.

I ran `kitten choose-fonts` to make sure that my kitty.conf is correct but the problem persists.

**To Reproduce**
1. Display text in Monoid Nerd Font Bold in kitty v0.35 and v0.36 and see the difference

**Screenshots**
This is kitty v0.36.1 (note that the font turns bold starting with the word "Linux")
![image](https://github.com/user-attachments/assets/5677949f-27e3-4e50-a53c-b5054678e196)

This is foot v1.18.1 (kitty was as crisp in v0.35)
![image](https://github.com/user-attachments/assets/30d1afea-32fb-4fe6-ad4a-654502c0dbd6)

**Environment details**
Can't press the key combination due to a minimal keyboard.

**Additional context**
```
font_family      family='Monoid Nerd Font Mono' style=Retina
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 9
```

**Comment by kovidgoyal** [comment]
Those are two different bold fonts. Use --debug-font-fallback to see exactly which font is being used and then either specify the face you prefer  using the choose-fonts kitten or manually in kitty.conf.

Also, dont use patched NERD fonts in kitty, there is no need. NERD symvols work automatically.
