### ISSUE TITLE
cmd key(⌘) is working as super+LEFT_SUPER in mac

### ISSUE THREAD

**Issue by Bhavya031** [kovidgoyal/kitty#7804]
**Describe the bug**
First, this app is great, and I love its community. From what I understand, there is no support for the Command key in every terminal. The thing is, I like using the Command key in Vim, but I can't because, for some reason, the Shift key is also pressed with it. So if I want to bind any key with Command, I have to add Shift as well. Is there any solution? Here is the output of `kitten show-key -m kitty` for the Command key:
```
super+LEFT_SUPER PRESS 
CSI 57444 ; 9 u

LEFT_SUPER RELEASE 
CSI 57444 ; 1 : 3 u
```

**Comment by kovidgoyal** [comment]
That output is correctly showing a cmd key press as super+left_super.
You are pressing the left cmd key and pressing that key turns on the
super modifier.
