### ISSUE TITLE
Segfault when launching from icon

### ISSUE THREAD

**Issue by eo1989** [kovidgoyal/kitty#7808]
**Describe the bug**

**To Reproduce**
Unsure how to reproduce because I don't know what happened. Only thing I did was log out and log back in. As soon as I logged in I clicked on the kitty icon and nothing happened. Opened console and found an issue (provided below).
Kitty could only be launched from another terminal (Terminal.app) where it runs without issue..(?) In fact it's the only way to run I could launch kitty. Which is strange because this issue didn't exist until I logged out and logged back in. Prior to that my mbp booted up and I was able to start the terminal (from the icon) without issue. I have converted the .crash file to a .log file (so that Safari would allow me to upload it). Unsure if that will create any issues with reading it on anyone else's end.

**Screenshots**
<img width="821" alt="Screen Shot 2024-08-30 at 20 54 11" src="https://github.com/user-attachments/assets/9fcdd1cd-73fd-4163-b151-14cf0dd50a8f">
<img width="1076" alt="Screen Shot 2024-08-30 at 20 53 17" src="https://github.com/user-attachments/assets/e586936a-655c-4ff5-9e83-ae6466a78d1c">

**Environment details**
---
kitty 0.36.1 (95245ee473) created by Kovid Goyal
Darwin eo-rmbp.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H2026
OpenGL: '4.1 INTEL-14.7.28' Detected version: 4.1
Frozen: True
Fonts:
  medium: FiraCodeNF-Ret: /Users/eo/Library/Fonts/FiraCodeNerdFont-Retina.ttf
  bold: VictorMonoNerdFontComplete-SemiBold: /Users/eo/Library/Fonts/Victor-Mono-SemiBold-Nerd-Font-Complete.ttf
  italic: VictorMonoNF-MediumItalic: /Users/eo/Library/Fonts/VictorMonoNerdFont-MediumItalic.ttf
  bi: VictorMonoNF-SemiBoldItalic: /Users/eo/Library/Fonts/VictorMonoNerdFont-SemiBoldItalic.ttf
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /usr/local/bin/zsh -l
Loaded config files:
  /Users/eo/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control               yes
background_opacity                 0.8
bell_on_tab                        
bold_font                          VictorMonoNerdFontComplete-SemiBold
bold_italic_font                   VictorMonoNF-SemiBoldItalic
clipboard_control                  ('write-clipboard', 'write-primary', 'read-clipboard', 'read-primary')
clone_source_strategies            frozenset({'env_var', 'path', 'venv'})
confirm_os_window_close            0
copy_on_select                     clipboard
cursor_shape                       2
cursor_stop_blinking_after         0
dim_opacity                        0.9
editor                             /Users/eo/dev/eo_contrib/neovim/bin/nvim
enable_audio_bell                  False
enabled_layouts                    ['fat', 'vertical', 'horizontal', 'grid', 'splits', 'stack:bias=65']
file_transfer_confirmation_bypass  true
font_family                        FiraCodeNF-Ret
font_features:
{'FiraCodeNF-Ret': ('ss01',
                    'ss03',
                    'ss04',
                    'ss05',
                    'ss06',
                    'ss07',
                    'ss09',
                    'cv01',
                    'cv02',
                    'cv24',
                    'cv25',
                    'cv26',
                    'cv32',
                    'cv28',
                    'cv29',
                    'cv30',
                    'cv31',
                    'liga')}
font_size                          12.0
hide_window_decorations            2
inactive_tab_font_style            (False, True)
italic_font                        VictorMonoNF-MediumItalic
listen_on                          unix:/tmp/kitty
macos_custom_beam_cursor           True
macos_option_as_alt                3
macos_quit_when_last_window_closed True
macos_show_window_title_in         menubar
macos_thicken_font                 0.65
pointer_shape_when_grabbed         beam
repaint_delay                      2
scrollback_lines                   10000
select_by_word_characters          :@-./_~?&=%+#
shell                              /usr/local/bin/zsh
single_window_margin_width         FloatEdges(left=0.0, top=0.0, right=0.0, bottom=0.0)
strip_trailing_spaces              smart
tab_bar_align                      center
tab_bar_margin_width               1.0
tab_fade                           (0.2, 0.4, 0.6, 0.8, 1.0)
tab_separator                      fade
tab_title_template                 {sup.index}{activity_symbol}{fmt.fg.tab}{title}
touch_scroll_multiplier            1.2
update_check_interval              48.0
url_style                          1
window_alert_on_bell               False
window_border_width                (1.0, 'pt')
Added shortcuts:
	ctrl+enter →  send_text normal,application \x1b[13;5u
	opt+backspace →  send_text all \x17
	opt+cmd+j →  kitten pass_keys.py neighboring_window bottom ctrl+alt+j "^.* - nvim$"
	opt+cmd+k →  kitten pass_keys.py neighboring_window top    ctrl+alt+k "^.* - nvim$"
	opt+cmd+l →  kitten pass_keys.py neighboring_window right  ctrl+alt+l "^.* - nvim$"
	shift+enter →  send_text normal,application \x1b[13;2u
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	kitty_mod+n →  new_os_window
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window
Changed shortcuts:
	cmd+n →  launch --cwd=current --type=tab --allow-remote-control
	kitty_mod+p > f →  kitten hints --type path --program -, kitten hints --type hyperlink, kitten hints --type linenum, kitten hints --type hash --program -, kitten hints --type word --program -, kitten hints --type line --program -, kitten hints --type path --program -
	opt+cmd+h →  kitten pass_keys.py neighboring_window left   ctrl+alt+h "^.* - nvim$"
Colors:
	background                         #282a36   
	color0                             #282a36   
	color1                             #ff5c57   
	color10                            #5af78e   
	color11                            #f3f99d   
	color12                            #57c7ff   
	color13                            #ff6ac1   
	color14                            #9aedfe   
	color15                            #eff0eb   
	color2                             #5af78e   
	color3                             #f3f99d   
	color4                             #57c7ff   
	color5                             #ff6ac1   
	color6                             #9aedfe   
	color7                             #f1f1f0   
	color8                             #686868   
	color9                             #ff5c57   
	cursor                             #97979b   
	cursor_text_color                  #282a36   
	foreground                         #eff0eb   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/Users/eo/dev/eo_contrib/neovim/bin:/Users/eo/.local/bin:/Users/eo/.cargo/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/whois/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/gnu-which/libexec/gnubin:/usr/local/opt/gnu-units/libexec/gnubin:/usr/local/opt/gnu-time/libexec/gnubin:/usr/local/opt/make/libexec/gnubin:/usr/local/opt:/usr/local/Cellar/pyenv-virtualenv/1.2.4/shims:/Users/eo/.pyenv/shims:/Users/eo/.pyenv/bin:/usr/local/bin:/usr/local/sbin:/Users/eo/.luarocks/bin:/usr/bin:/bin:/Users/eo/go/bin:/usr/local/opt/go/libexec:/Users/eo/.local/share/nvim/mason/bin
	LANG                                en_US.UTF-8
	VISUAL                              /Users/eo/Dev/eo_contrib/neovim/bin/nvim
	EDITOR                              /Users/eo/Dev/eo_contrib/neovim/bin/nvim
	SHELL                               /usr/local/bin/zsh -l
	DISPLAY                             /private/tmp/com.apple.launchd.1q0VsPa1PT/org.xquartz:0
	USER                                eo
	LC_ALL                              en_US.UTF-8

---

[zsh_2026-08-30-210152_eo-rmbp.log](https://github.com/user-attachments/files/16823053/zsh_2026-08-30-210152_eo-rmbp.log)

**Comment by kovidgoyal** [comment]
That's a segfault in zsh not kitty. You should report it there. Presumably some env var is different when launching via launch services that zsh doesnt like.

**Comment by eo1989** [comment]
Understood. Thank you for taking the time to look!
