### ISSUE TITLE
KITTY_SHELL_INTEGRATION unset in no-rc mode on macOS

### ISSUE THREAD

**Issue by dcolascione** [kovidgoyal/kitty#7809]
**Describe the bug**
 On macOS,  we use the shell launcher kitten in Go to launch the shell to work around the getlogin() issue. When we do so, and kitty shell integration is set to no-rc, we don't set the shell integration environment variable, which makes manual integration do nothing.

**To Reproduce**
1. Use no-rc mode
2. Launch shell
3. env
4. See lack of variables set

**Comment by kovidgoyal** [comment]
KITTY_SHELL_INTEGRATION is not supposed to be set in this mode. If you
want to do manual sheel integration follow the instructions in
https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration

Although there is no need for this at all since this issue was fixed
over a year ago see #6511

**Comment by dcolascione** [comment]
```
if [[ -z "$KITTY_SHELL_INTEGRATION" ]]; then builtin return; fi
```

The integration bails out early if the variable isn't set.

**Comment by kovidgoyal** [comment]
Again, read the docs. If you did so, you will note that
shell_integration needs to be set to disabled and you need to set
KITTY_SHELL_INTEGRATION to whatever you want **manually**.

**Comment by dcolascione** [comment]
The docs say this:

```
no-rc
Do not modify the shell’s launch environment to enable integration. Useful if you prefer to load the kitty shell integration code yourself, either as part of [manual integration](https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration) or because you have some other software that sets up shell integration. This will still set the [KITTY_SHELL_INTEGRATION](https://sw.kovidgoyal.net/kitty/glossary/#envvar-KITTY_SHELL_INTEGRATION) environment variable when kitty runs the shell.
```

However, on macOS, setting `shell_integration` to `no-rc` results in the `KITTY_SHELL_INTEGRATION` not being set. Either the docs or wrong or the code is wrong.

**Comment by kovidgoyal** [comment]
Sigh, good luck.

**Comment by dcolascione** [comment]
> Sigh, good luck.

Your code is wrong. You want to leave it like that to win a GitHub comment thread?

**Comment by dcolascione** [comment]
I mean, on macOS, the environment variable isn't set, and on Linux it is. That's just a fact. Is this behavior difference by design? That's on you to document. Don't sit there and tell me to RTFM when I *did* read the manual and it's wrong.

**Comment by kovidgoyal** [comment]
On Sat, Aug 31, 2024 at 09:36:59PM -0700, Daniel Colascione wrote:
> > Sigh, good luck.
>
> Your code is wrong. You want to leave it like that to win a GitHub comment thread?

Says, you. And I dont want to win a github comment thread, I just want
to stop wasting my time on you.
