### ISSUE TITLE
glfw error 65542

### ISSUE THREAD

**Issue by wgmayer0** [kovidgoyal/kitty#7811]
**Describe the bug**
When trying to launch Kitty from xterm it says: 
`[0.093] [glfw error 65542]: GLX: GLX extension not found
[0.122] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.1 drivers.
`

**To Reproduce**
1. open xterm
2. type in 'kitty'
3. press enter

**Additional context**
This happened right after a kernel update via pacman on arch linux

**Comment by kovidgoyal** [comment]
Your OpenGL drivers are broken.

**Comment by wgmayer0** [comment]
Can I fix them or would I have to wait for arch to fix them
