### ISSUE TITLE
Show `[current_tab/total_tabs]` in window title when `tab_bar_style hidden` is set

### ISSUE THREAD

**Issue by yavorski** [kovidgoyal/kitty#7812]
**Is your feature request related to a problem? Please describe.**
It would be nice to know the current tab and total tabs when you are using  `tab_bar_style hidden` is config.
I use this option on small laptops screens like 12.5/13" to have more available space.

**Describe the solution you'd like**
Current tabs can be displayed in window title bar, like wezterm, when you are hiding the tabs. 
Example: `[1/3] - the rest of the tile`
Please see the screenshot.

![wez-term-tabs-in-window-title](https://github.com/user-attachments/assets/e8527def-c981-443e-8621-e222afa9e7d0)

**Describe alternatives you've considered**
Have tried to write a custom script but it's still not there and having issues:

```bash
update_kitty_window_title() {
  # Fetch the current window information using Kitty's remote control
  window_info=$(kitty @ ls)

  # Extract the total number of tabs
  total_tabs=$(echo "$window_info" | jq -r '.[0].tabs | length')

  # Extract the tab index of the currently focused tab
  tab_index=$(echo "$window_info" | jq -r '.[0].tabs | to_entries[] | select(.value.is_focused == true) | .key + 1')

  # Extract the current window title from the focused window of the focused tab
  current_title=$(echo "$window_info" | jq -r '.[0].tabs[] | select(.is_focused == true) | .windows[] | select(.is_focused == true) | .title')

  # Prepend custom text "[x/y]" (tab index / total tabs) to the existing window title
  new_title="[${tab_index}/${total_tabs}] ${current_title}"

  # Set the new window title
  kitty @ set-window-title "$new_title"
}
```

**Additional context**

None

**Comment by kovidgoyal** [comment]
Not something I am interested in spending time on, patches welcome.

That said for your actual use case I would instead hide the window
decorations and leave the tab bar visible, much more functional.
