### ISSUE TITLE
GVim doesn't get focus when started via Kitty

### ISSUE THREAD

**Issue by torfsen** [kovidgoyal/kitty#7816]
**Describe the bug**

When I start GVim from within a Kitty session (via `gvim`) the new GVim GUI window pops up in front of the Kitty window, but it does not get the keyboard focus (Kitty still has it).

What I've tried:

* The issue is not present with other programs (e.g. Firefox)
* The issue is not present with other terminals (e.g. the default GNOME Terminal)

I also get a GNOME notifcation about the GVim window being ready, something that I do not get when starting GVim from other terminals or other GUI programs from Kitty.

I know that this may very well be an issue with GVim (I'm using the `vim-gtk3` package in Ubuntu 20.04), but given that it is working with Kitty and other GUI programs and with GNOME's Terminal and GVim I figured there might be some issue related to Kitty after all.

**To Reproduce**
1. Open a Kitty window
2. Execute `gvim`
3. GVim window shows, Kitty still has keyboard focus

**Screenshots**
N/A

**Environment details**
The problem can be seen when starting Kitty via `kitty --config NONE`.

I have installed GVim via the `vim-gtk3` package.

The issue was not present on my old system running Ubuntu 20.04 and Kitty 0.16.0.

```
kitty 0.36.1 (95245ee473) created by Kovid Goyal
Linux it09 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64
Ubuntu 24.04.1 LTS it09 /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
Running under: Wayland (GNOME Shell 46.0) missing: layer_shell
OpenGL: '4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.1' Detected version: 4.6
Frozen: True
Fonts:
  medium: DejaVuSansMono: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
  bold: DejaVuSansMono-Bold: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf:0
  italic: DejaVuSansMono-Oblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf:0
  bi: DejaVuSansMono-BoldOblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf:0
Paths:
  kitty: /home/XXX/.local/kitty.app/bin/kitty
  base dir: /home/XXX/.local/kitty.app/lib/kitty
  extensions dir: /home/XXX/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/XXX/.pyenv/plugins/pyenv-virtualenv/shims:/home/XXX/.pyenv/shims:/home/XXX/.pyenv/bin:/home/XXX/bin:/home/XXX/.local/kitty.app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                XXX
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	LC_ADDRESS                          de_DE.UTF-8
	LC_NAME                             de_DE.UTF-8
	LC_MONETARY                         de_DE.UTF-8
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            de_DE.UTF-8
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   de_DE.UTF-8
	LC_TELEPHONE                        de_DE.UTF-8
	LC_MEASUREMENT                      de_DE.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             de_DE.UTF-8
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
	LC_NUMERIC                          de_DE.UTF-8
```

**Comment by kovidgoyal** [comment]
Sorry, no clue. I tend to avoid GNOME like the plague (just look at the
number of GNOME+Wayland specific issues in the kitty changelog).

I tried this in a couple of other wayland environments (KDE, sway) and
there was no issue, gvim gets focus, as expected.

Here, it is the shell running gvim not kitty. Furthermore, focus in
Wayland is managed entirely by the compositor, not applications, for
security theatre reasons, so I don't see what kitty could possibly be
doing here. Report the issue to mutter developers, maybe they can
enlighten us. Probably this is because gvim is using obselete gtk3 which
has some wayland bug which is trigerred by some timing or env var or
other issue that happens only when running from inside kitty.

**Comment by torfsen** [comment]
OK, fair points!

As a workaround I've written a small Bash script that I alias to `gvim`, which seems to work well so far. Unless the issue starts happening with other tools this should be enough.

```bash
get_latest_gvim_window_id() {
    wmctrl -lp \
        | grep GVIM \
        | tr -s ' ' \
        | cut -d ' ' -f 1,3 \
        | sort -k2 -nr \
        | head -n 1 \
        | cut -d ' ' -f 1
}

LATEST_ID=$(get_latest_gvim_window_id)

gvim "$@" &

while true
do
    NEW_ID=$(get_latest_gvim_window_id)
    if [ "$LATEST_ID" != "$NEW_ID" ];
    then
        wmctrl -ia "$NEW_ID"
        break
    fi
done
```
