### ISSUE TITLE
Colors within fzf vanish after using the diff kitten

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#7819]
**Describe the Bug**
A recent change around version v0.33 causes the diff kitten to alter the terminal screen, resulting in the `fzf` tool losing its colors. While the issue may be within `fzf`, I'm filing this report here because the problem did not occur in previous Kitty releases.

**To Reproduce**

1. Install the `fzf` tool, if not already installed, from: [https://github.com/junegunn/fzf](https://github.com/junegunn/fzf).

2. Configure the kitten diff by adding the following to `~/.gitconfig`:

   ```ini
   [diff]
     tool = kitty
   [difftool]
     prompt = false
     trustExitCode = true
   [difftool "kitty"]
     cmd = kitten diff $LOCAL $REMOTE
   ```

3. Navigate to a Git repository:

   ```sh
   cd /path/to/git/repo
   ```

4. Execute the following command:

   ```sh
   git log --color=always --oneline | fzf --ansi --bind='space:execute:(git difftool --no-symlinks --dir-diff {1}^!)'
   ```

5. Select a commit and press space to view the changes.

6. Press Escape to exit the diff kitten and return to `fzf`.

**Observed Behavior**
After exiting the diff kitten, the contents in `fzf` lose all colors except for the current line.

![Screenshot from 2024-09-04 00-32-15](https://github.com/user-attachments/assets/26e925bf-fe45-4dad-8ad4-1d16e3448c41)

**Expected Behavior**
Colors should remain intact as they did in previous versions.

![Screenshot from 2024-09-04 00-31-54](https://github.com/user-attachments/assets/cfc4f73b-e2f6-417b-9bbc-e737fce50782)

**Environment details**
```
kitty 0.36.1 (95245ee473) created by Kovid Goyal
Linux byteevo 5.15.0-119-generic #129~20.04.1-Ubuntu SMP Wed Aug 7 13:07:13 UTC 2024 x86_64
Ubuntu 20.04.6 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 21.2.6' Detected version: 4.6
Frozen: True
Fonts:
  medium: DejaVuSansMono: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
  bold: DejaVuSansMono-Bold: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf:0
  italic: DejaVuSansMono-Oblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf:0
  bi: DejaVuSansMono-BoldOblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf:0
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  allow_remote_control yes

Config options different from defaults:
allow_remote_control yes

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.local/lib/precor:/home/precor/.local/bin:/home/precor/.local/node/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/Android/Sdk/build-tools/34.0.0:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**

1. Temporary workaround is to run the diff kitten within an overlay window, like this:
  ```
  git log --color=always --oneline | fzf --ansi --bind='space:execute:(kitty @ launch --cwd=current --type=overlay --no-response git difftool --no-symlinks --dir-diff {1}^!)'
  ```

**Comment by salmankhilji** [comment]
I'm unsure if this is the correct approach, but would it be possible for kitten to utilize the alternate screen buffer? This might help prevent any rendering issues that occur after exiting.

**Comment by kovidgoyal** [comment]
The diff kitten does use the alternate screen and it does restore the
screen on exit. Your issues are caused by the fact that both fzf and the
diff kitten perform I/O with the tty. That is unsafe/undefined behavior.
