### ISSUE TITLE
backspace not working in kitty

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#783]
The backspace button does not work when logged in as root via `su -` Instead of deleting characters, it acts as a space bar. How do I reset the kitty terminal to make backspace start working?

**Comment by kovidgoyal** [comment]
Make sure the TERMINFO environment variable is preserved in your su - environment or install the kitty terminfo files system wide.

**Comment by ChukwuemezieChristopherAneke** [comment]
You're right, its not preserved in my `su -` environment; `echo $TERMINFO` as normal user returns /home/user/kitty/src/terminfo but when logged in as root with `su -` it shows nothing. I will create a symlink from to a directory already exported in my path and this should then be availabe to root.

Can you confirm which terminfo file I need. This is what is in the terminfo directroy:








```
/home/user/kitty/src/terminfo
├── 78
│   └── xterm-kitty
├── kitty.terminfo
└── x
    └── xterm-kitty
```

**Comment by kovidgoyal** [comment]
It depends on the ncurses library your system is using. Simply copy both directories to /usr/share/terminfo. Or better dont use su at all, it is obsoleted by sudo use

sudo -s -H

instead and add TERMINFO to env_keep in /etc/sudoers

**Comment by ChukwuemezieChristopherAneke** [comment]
Unfortunately when I installed fedora, I did not set up any sudoers but I've been wanting to correct this mistake. 

Thanks for mentioning sudo, its great advice. Can you confirm what `sudo -s -H` does? 

1. Does it set up a new sudoer? 
2. Does the `-H` option set the $HOME variable of the sudo command to /root or is it /home/user? 
3. Does the `-s` option run commands passed to sudo as an argument in bash since it the shell I am using?

**Comment by ekevoo** [comment]
`su -` sets a lot of stuff that is pretty convenient, most notably the cwd. I didn't find anything in its BSD manual about how to tell it to preserve additional environment variables. :\
