### ISSUE TITLE
kitty fails to build on OpenBSD

### ISSUE THREAD

**Issue by neelchakrabrty** [kovidgoyal/kitty#7830]
**Describe the bug**
Kitty fails to build throwing out error about `go` toolchain not being available

**To Reproduce**
1. `git clone https://github.com/kovidgoyal/kitty.git && cd kitty`
2. `./dev.sh build`

The build stage fails throwing out the following error
` go: download go1.23 for openbsd/amd64: toolchain not available`

I have `go` installed and output of `go version` is `go version go1.22.1 openbsd/amd64`

**Comment by kovidgoyal** [comment]
I'm afraid I dont know anything about OpenBSD. And the dev.sh route for
building only works on platforms for which kitty binaries are available.
On OpenBSD you will need to install all the dependencies first and then
build using make.

**Comment by k2662** [comment]
> I'm afraid I dont know anything about OpenBSD. And the dev.sh route for building only works on platforms for which kitty binaries are available. On OpenBSD you will need to install all the dependencies first and then build using make.

I've tried it in a vm and that doesn't work
