### ISSUE TITLE
Brahmic Character Support

### ISSUE THREAD

**Issue by mrsnailo** [kovidgoyal/kitty#7832]
**Is your feature request related to a problem? Please describe.**

I often use Kitty as my IDE and type in multiple languages, including Bengali. However, when I try to type Bengali characters, they are not rendered correctly. This seems to be a lack of Brahmic script character support in the terminal, as fonts that work in other terminals (like Konsole) do not display properly in Kitty.

**Describe the solution you'd like**

It would be great if Kitty could support Brahmic scripts, particularly the Bengali script. Konsole, for example, handles these characters correctly. I'd like to see an option or built-in support for these scripts in Kitty, so that Bengali characters display without any issues.

**Describe alternatives you've considered**

I have tried using different fonts, such as Noto Sans Bengali and Lohit Bengali, alongside Nerd Fonts for icons, but this does not solve the issue. I also tried tweaking configuration settings in Kitty, but the problem persists.

**Additional context**
![Screenshot_20240908_061444](https://github.com/user-attachments/assets/ecf7e163-7e60-4915-965c-4faa3c8ccea3)

It would be helpful to have similar font and script support as Konsole, which renders Bengali characters correctly. This would make Kitty a more versatile option for multilingual development and use.

**Comment by kovidgoyal** [comment]
dup of #3045
