### ISSUE TITLE
Use mac native shortcuts

### ISSUE THREAD

**Issue by DoLoop216** [kovidgoyal/kitty#7833]
**Is your feature request related to a problem? Please describe.**
I am using kitty on all devices and love it, however on mac there is a problem. Mac uses "Command + C" instead of "Control + C" to copy and same for paste. Kitty uses "Control + shift + C". What is frustrating is once I am working on mac, I am used to "Command" and only in kitty, I need to switch my brain to "Control".

**Describe the solution you'd like**
It would be nice to set key binding for mac on copy/paste to be "Command + shift + c / command + shift + v" instead of "control + shift + c / control + shift + v"

Also think about some other commands (I have just started using mac so not sure what other commands like this are there)

**Comment by DoLoop216** [comment]
Just realized that all the things with "ctrl" should be re-mapped to the "command" on mac.

**Comment by kovidgoyal** [comment]
Use whatever mappings you like, all shortcuts are completely
customizable. Not to mention that by default on macOS kitty supports
cmd+c/v for copy/paste out of the box.
