### ISSUE TITLE
Setting for initial layout (horizontal/vertical) when opening up a window inside kitty

### ISSUE THREAD

**Issue by excited-bore** [kovidgoyal/kitty#7835]
When I open kitty like this:

![kitty_1window](https://github.com/user-attachments/assets/476b4a8c-16a5-4c7a-8b7b-21651a1333b8)

and I open a new window (with `ctrl+shift+enter`), I get this:

![kitty_vertical](https://github.com/user-attachments/assets/1a515bdd-e4c6-4b08-ac9d-d24a75f715b0)

I would like this new window to be horizontal, 
like full in height and split in width

Im sorry if this is already a feature, I just couldn't find it anywhere (apart from limiting `enabled_layout`, which I rather keep to the default `*`)  

**Is your feature request related to a problem? Please describe.**
Not really, it's purely a nicety to have

**Describe the solution you'd like**
A setting that allows this in kitty.conf, 
like `layout new-window: horizontal/vertical/???`

**Comment by kovidgoyal** [comment]
use the splits layout then you can control which direction the split
happens by using an argument to the launch command in the map.

https://sw.kovidgoyal.net/kitty/launch/

**Comment by excited-bore** [comment]
Got it!
 
So by changing:

`map kitty_mod+enter  (cwd_)new_window
 enabled_layouts *
`
to

`map kitty_mod+enter   launch --location vsplit (--cwd=current)
 enabled_layouts splits,stack,tall,vertical,horizontal,grid,fat
`
, I got the desired result.

(`splits` as the initial layout with `launch --location vsplit` as the command to open up a new vertical window)

![kitty_vertical_yess](https://github.com/user-attachments/assets/6acb6ddd-88e2-47ef-ba98-3b5e77b8cab0)

Thanks for the explanation! :grin:
