### ISSUE TITLE
Border between windows became thick

### ISSUE THREAD

**Issue by eulersson** [kovidgoyal/kitty#7848]
Is there a way to configure how thick the gaps between windows is?

OS: macOS 14.6.1 

Screenshot:

<img width="935" alt="image" src="https://github.com/user-attachments/assets/f37c9b25-cebb-457c-8b53-b5d8f26540d7">

**Comment by kovidgoyal** [comment]
See the docs for all the options to control window margins and padding.
https://sw.kovidgoyal.net/kitty/conf/
