### ISSUE TITLE
Cannot quit kitty terminal window on M1 Mac

### ISSUE THREAD

**Issue by u3Izx9ql7vW4** [kovidgoyal/kitty#7856]
**Describe the bug**
Cannot close the terminal window. Quit, doesn't do anything. Window stays open no matter what. 

**To Reproduce**
1.  Install kitty terminal using curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
2. It launches automatically
3. Try to quit it via menu bar, or dock, etc.
4. It doesn't quit
5. I had to force quit via task manager 

**Screenshots**

**Environment details**
Didn't bother with entering anything on terminal if I can't quit the application. It's been uninstalled.
```
macOS 14.5
```

**Additional context**
Didn't bother with entering anything on terminal if I can't quit the application. It's been uninstalled.

**Comment by kovidgoyal** [comment]
Didn't bother trying to replicate your issue since I know kitty quits
just fine on macOS.

**Comment by kovidgoyal** [comment]
Good riddance.
