### ISSUE TITLE
Create a way to install to /usr/local (or, ideally, make Kitty available through package installers)

### ISSUE THREAD

**Issue by mscheper** [kovidgoyal/kitty#7857]
**Is your feature request related to a problem? Please describe.**
Kitty's quickstart docs say Kitty will be installed to ~/.local/kitty.app. But I want to install it system-wide, thus to /usr/local, /usr/bin, etc.

I sometimes use multiple user accounts on the same machine and I don't want to install multiple copies; I don't want third-party binaries to get caught in my /home folder backups; and /home just doesn't seem like the right place to install a program like Kitty.

**Describe the solution you'd like**
Ideally, I'd like there to be an apt repo I can add or a deb file I can download. Short of that, I'd like there to be an option in the installation script to install Kitty systemwide. If there is already such an option, it ought to be documented in the quickstart, or the quickstart should have a link to more detailed installation instructions. (I spent some time searching GitHub and the Web for how to do this, but didn't find anything. I apologise if the answer actually is posted somewhere.)

**Describe alternatives you've considered**
The quickstart suggests creating a symlink from my home directory to /usr/bin, but I strongly doubt many Linux professionals think this is a good idea.

**Additional context**
My distro (Mint 21.3) actually does have an apt candidate, but it's ancient.

**Comment by kovidgoyal** [comment]
Read https://sw.kovidgoyal.net/kitty/binary/#customizing-the-installation

**Comment by mscheper** [comment]
@kovidgoyal: Ah, yes, thank you. I did see the `dest` switch, but forgot about it when I started searching for a more orthodox way to install Kitty.

**Question**: Is there a way to get it to install directly to the specified directory, and not have it create the kitty.app subdirectory? I hadn't heard of `*.app` directories before new, and it seems to be an Apple convention.

For anybody else landing on this issue (and for my own future notes), I did the following, and apart from creating the nonstandard subdirectory, it seems to work. I'll add further comments if I find it causes any problems:
```
sudo mkdir /usr/local/kitty
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sudo sh /dev/stdin dest=/usr/local/kitty launch=n
sudo ln -s /usr/local/kitty/kitty.app/bin/kitt* /usr/bin
```

At this stage I'd still feel more comfortable with a managed package, but if problems don't arise and updates prove easy, I'll probably just do it this way on other machines.

**Comment by kovidgoyal** [comment]
No, installing directly to a directory is just a recipe for users to
destroy their data by accidentally specifying the wrong directory. With
the current system the worst the installer can do is delete a directory
named kitty.app, highly unlikely to contain valuable user data.
