### ISSUE TITLE
active_window_history is missing latest window on creation

### ISSUE THREAD

**Issue by nmattia** [kovidgoyal/kitty#7859]
**Describe the bug**

It looks `active_window_history` does not include the current window if the window has not been moved to (even if it is currently focused).

The following script logs `active_window_history` to the current window (assuming 1 tab & 1 OS window):

```bash
#!/usr/bin/env bash

active_window_history=$(kitten @ ls | jq -cMr '.[0].tabs.[0].active_window_history')

kitten @ send-text "#" "$active_window_history" '\n'
```

can be bound with e.g.:

```
map ctrl+space remote_control_script /path/to/repro
```

When a window was just created & focused, it does not show up in `active_window_history`:

https://github.com/user-attachments/assets/1485e878-be76-4e09-8508-814c64a48d2c

**Environment details**
```
kitty 0.34.1 created by Kovid Goyal
Darwin ... ... Darwin Kernel Version ...: ...; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		... BuildVersion:		...
Frozen: False
Paths:
  kitty: .../Applications/kitty.app/Contents/MacOS/kitty
  base dir: .../Applications/kitty.app/Contents/Resources/kitty
  extensions dir: .../Applications/kitty.app/Contents/Resources/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  ./.../kitty/kitty.conf

Config options different from defaults:
enable_audio_bell                  False
font_size                          13.0
macos_option_as_alt                1
macos_quit_when_last_window_closed True
scrollback_lines                   100000
shell_integration                  frozenset({'enabled'})
Added shortcuts:
	ctrl+space →  remote_control_script /.../kitty/repro
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                ...
	LANG                                en_US.UTF-8
	KITTY_CONFIG_DIRECTORY              /path/to/conf
	SHELL                               /bin/zsh
	USER                                ...

```

---

Alternatively if this is the expected behavior, what's a good workaround? i.e. what's the most lightweight way to ensure the window is included in `active_window_history`?

**Comment by kovidgoyal** [comment]
Yes, that's how it is implemented. active_window_history represents
windows that have been active in the past. It doesn't necessarily
include the currently active window. It's purpose is to allow switching
to a previously active window, for which having the currently active
window in the list is useless.

**Comment by nmattia** [comment]
Thanks for the quick reply.

After experimenting a bit more I realize that I might not understand what an "active" window is. For instance, when inspecting the output of `kitten @ ls --self` in a new window, the window ID does not match that of the window where the cursor blinks. This means that the active window is not necessarily the focused window, correct? What does it mean for a window to be active (beyond being "active in its parent tab")? And from `kitten @ ls --self`:

> --self: Run the action on the window this command is run in instead of the active window.

What window are commands run in when a mappable action is triggered? From experimenting with the following script, it looks like `--self` always returns the window with ID `1`:

```bash
#!/usr/bin/env bash

window_id=$(kitten @ ls --self | jq -cMr '.[0].tabs.[0].windows.[0].id')

kitten @ send-text "echo" '$KITTY_WINDOW_ID' "#" "self is $window_id" '\n'

# outputs something like this:
# ~% echo $KITTY_WINDOW_ID # self is 1 
# 4
```

Do I understand correctly that `--self` is mostly useful for remote control, but not necessarily for mapping an action with `remote_control_script` (which will always run the script from the first window)? 

If I wanted to get the window where I can currently type, I should use `--match state:focused`, is that right?

**Comment by kovidgoyal** [comment]
active means just that, active in its parent tab. Since there can be
multiple tabs there can be multiple active windows. If what you are
interested in is keyboard focus, then there can be only one focused window at a time

--self means the window the remote control command was run in and yes it
is only used for remote control.
