### ISSUE TITLE
Please allow active window resizing according to directions(left, right, up, down)

### ISSUE THREAD

**Issue by syedadeed** [kovidgoyal/kitty#7860]
i have binded atl+shift+{left, right, up, down} keys to resize_window {narrower, wider, taller,  shorter}
this resizes windows in the direction of the arrow only if they are on the right side of the screen
for windows on the left side it resizes windows in the opposite direction of the arrow

So its my humble request if possible can you refactor the resize window function to resize windows according left, right, top, bottom directions
 
I dont know about any possible alternatives maybe a custom kitten or something might be able to help in this case
but i cant say for certain because i havent yet read docs for creating custom kittens

You can see the window resizing in hyprland as an example, it resizes windows according to specified directions

**Comment by kovidgoyal** [comment]
I'm afraid not, I find wider/taller much more useful than directional
resizing. But if you like directional resizing you can of course
implement it using a custom kitten (by adjusting the biases in the
layout to give the windows the sizes you want when the kitten is
triggerred). I am also open to a PR for it, but then you would have to
implement it for *every* layout kitty supports not just the one you use.

**Comment by syedadeed** [comment]
i created a custom kitten for it :)
