### ISSUE TITLE
sporadic freeze on resume when kitty is running

### ISSUE THREAD

**Issue by MarkoSchuetz** [kovidgoyal/kitty#7863]
**Describe the bug**
Upon resume I get sporadic freezes of the login screen (sddm) when kitty is running.

I run kitty with the command
```
kitty --detach --class ploverkitty sh -c "tail -f ~/.config/plover/clippy_2.org | sed -e 's/^.*\[0m \(.*\[0m .*\) < .*$/\1/g'" &
```
to monitor Plover suggestions for shorter steno strokes than the ones I'm using. When I have kitty running that way, then sometimes when I suspend/resume the system, I get the lock-screen with the clock showing the time of the resume (not the time of the suspend) but I cannot unlock. Today, when it happened I was able to access other consoles (Ctrl-Alt-Fx), but I do not remember whether I can ALWAYS access them I had intentionally not used this way of running kitty since the start of July and without kitty running this command, this type of lock-up has never happened. Also, I run kitty with `tdrop -ma kitty` attached to keyboard shortcut F12, but whether that kitty is displayed or not does not seem to have any effect on whether or not the lock-screen becomes locked.

**To Reproduce**
Since this is sporadic there are no sure steps to bring this about.

**Environment details**
```
kitty 0.36.1 created by Kovid Goyal
Linux allofthis 6.6.47-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Aug 19 09:51:26 UTC 2024 x86_64
Manjaro Linux 6.6.47-1-MANJARO  (allofthis) (/dev/tty)


DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="24.0.8"
DISTRIB_CODENAME="Wynsdey"
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 24.1.6-arch1.1' Detected version: 4.6
Frozen: False
Fonts:
  medium: NotoSansMono-Regular: /usr/share/fonts/noto/NotoSansMono-Regular.ttf:0
  bold: NotoSansMono-Bold: /usr/share/fonts/noto/NotoSansMono-Bold.ttf:0
  italic: NotoSansMono-Regular: /usr/share/fonts/noto/NotoSansMono-Regular.ttf:0
  bi: NotoSansMono-Bold: /usr/share/fonts/noto/NotoSansMono-Bold.ttf:0
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/marko/.local/bin:/home/marko/.local/bin:/home/marko/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/emscripten:/home/marko/.local/share/flatpak/exports/bin:/usr/lib/jvm/default/bin:/opt/mpich/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                marko
	XDG_CONFIG_DIRS                     /home/marko/.config/kdedefaults:/etc/xdg:/usr/share/manjaro-kde-settings/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_MENU_PREFIX                     plasma-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 KDE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/marko/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
```

**Comment by kovidgoyal** [comment]
I don't see what sddm freezing has to do with kitty? If sddm is freezing
your first port of call needs to be the sddm bug tracker. Generally
speaking, if components of your system are freezing it will be because
of problems with things lower down in the stack like GPU
drivers/X11/mesa and friends.

**Comment by MarkoSchuetz** [comment]
I agree with your reaction and I would never have written this issue, if the would happen in any other situation. This machine gets carried around to different environments and I do all my work and personal stuff on it,  it puzzles me that it ONLY ever happens when kitty is running...

**Comment by kovidgoyal** [comment]
Nonetheless, there is nothing in kitty that could possibly cause other applications to misbehave barring bugs in things lower down in the stack.
