### ISSUE TITLE
Mac shortcuts don't seem to be working

### ISSUE THREAD

**Issue by eric-lief** [kovidgoyal/kitty#7865]
I have customized config and no kitty_mod + l will enable any layout
I have enabled all layouts.
I did cmd + l, and now it just deletes everything but no layout change.

**Describe the bug**

**To Reproduce**
1. XXX
2. YYY
3. ZZZ

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
I 
On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
You need to provide all the information asked for in the issue template
if you expect assistance.
