### ISSUE TITLE
Is there a way to use both 'launch' and 'send_text'? 

### ISSUE THREAD

**Issue by excited-bore** [kovidgoyal/kitty#7868]
Im actually trying to copy my directory stack to that one of the new window. 

Right now I put my current directories in a variable $DIRS and put that inside a file ~/.config/kitty/env.conf (using a cd wrapper that sed's 'env DIR' in env.conf each directory change) basing myself on  [this suggestion](https://github.com/kovidgoyal/kitty/issues/6362#issuecomment-1591033375).

env.conf:
```
 env DIRS=/home/user /home/user/Applications /home/user/.config
```

kitty.conf
```
include env.conf

...
map kitty_mod+enter launch --cwd=current --location=vsplit bash -ic "for i in $DIRS; do pushd $i &>/dev/null; echo $i; done; bash --login"
```
I checked and if a run `for i in $DIRS; do pushd $i &>/dev/null; echo $i; done` after I launch a new window it *does* set my directory stack properly, but not when using the custom launch command `map kitty_mod+enter launch --cwd=current --location=vsplit bash -ic "for i in $DIRS; do pushd $i &>/dev/null; echo $i; done; bash --login"`.

Is there a way to mitigate this by f.ex. using a combination a `launch` command and a `send_text` using the same `map`? 
Or is there maybe a way to combine launching a window and launching a command (using the original windows environment)?  

EDIT: The directory stack that you get from `dirs`

**Comment by kovidgoyal** [comment]
If you want to combine actions use combine see the kitty docs for it. Tough if what you want to do is clone your shell into a new window, including env vars just use the builtin clone-in-kitty command. 
https://sw.kovidgoyal.net/kitty/shell-integration/#clone-shell
