### ISSUE TITLE
Keymaps should work when kitty is not fully closed

### ISSUE THREAD

**Issue by smartinellimarco** [kovidgoyal/kitty#7869]
**Describe the bug**
When kitty doesn't have any opened windows, but the app itself its not closed, it should listen for keymap events in order to be able to open a new window/tab, or quit the app. This is how safari, finder, or other Mac apps behave.

**To Reproduce**
1. Close all windows
2. Try to open a new window or quit the app with a keymap

**Comment by kovidgoyal** [comment]
It works fine for me. Steps I tried:

kitty --config NONE -o 'map f1 new_window'

Notice that the shortcut for new window in the global menubar is now F1,
as expected. Quit the kitty window. Press f1. New kitty window opens.

**Comment by smartinellimarco** [comment]
Hi @kovidgoyal,

I just wanted to add that I'm using the "Remove all default keymaps" option. I tested it, and as you mentioned, it works when running Kitty from the shell, but not when launching it from the GUI. Could you confirm if this is expected behavior?

Thanks in advance!

**Comment by kovidgoyal** [comment]
Works for me with
echo 'map f1 new_window' >> ~/.config/kitty/kitty.conf

and launching kitty from the GUI as well.
