### ISSUE TITLE
Keyboard shortcuts and layouts not working in Mac

### ISSUE THREAD

**Issue by eric-lief** [kovidgoyal/kitty#7870]
I have customized the config and tried kitty_mod set to various meta keys with the same issue
I have enabled all layouts.
meta + l either does nothing or just deletes everything but no layout change. 

 
[kitty copy.txt](https://github.com/user-attachments/files/17043832/kitty.copy.txt)

**Screenshots**

**Environment details**
Mac OS 14.6.1
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
kitty 0.36.2 (15ac33a058) created by Kovid Goyal
Darwin Enriques-MacBook-Pro.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64
ProductName:		macOS ProductVersion:		14.6.1 BuildVersion:		23G93
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1
Frozen: True
Fonts:
  medium: Menlo-Regular: /System/Library/Fonts/Menlo.ttc
          Features: ()
    bold: Menlo-Bold: /System/Library/Fonts/Menlo.ttc
          Features: ()
  italic: Menlo-Italic: /System/Library/Fonts/Menlo.ttc
          Features: ()
      bi: Menlo-BoldItalic: /System/Library/Fonts/Menlo.ttc
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/liefe/.config/kitty/kitty.conf

Config options different from defaults:
open_url_with ['firefox']
Added shortcuts:
	f2 →  launch_tab emacs
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window
Changed shortcuts:
	kitty_mod+o →  pass_selection_to_program firefox

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/Users/liefe/.venvs/speech/bin:/opt/homebrew/opt/llvm@14/bin:/Users/liefe/.pyenv/shims:/Users/liefe/.local/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/liefe/.local/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                liefe

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
According to that debug output you have only changed two options from
default values, open_url_with and f2 to launch emacs. Do this

echo -e '\n\nmap cmd+l next_layout' >> ~/.config/kitty/kitty.conf

then restart kitty and you will be fine.

**Comment by eric-lief** [comment]
![Screenshot 2024-09-18 at 9 53 08 AM](https://github.com/user-attachments/assets/61d53614-fc2a-4d5a-ae27-3a39b85d127e)
![Screenshot 2024-09-18 at 9 57 27 AM](https://github.com/user-attachments/assets/dcad7e46-a3c3-4177-8771-02fd5ef04c37)

Not sure why you are so quick to close things when they aren't verified... If you look at the copy of my config I originally attached I had many mappings in the config that just aren't in the output, but in the config.

So, I did what you said with appending, and with the mapping of kitty_meta to control, pressing enter kept on horizontally splitting the panes without stopping (screenshot). Changing the meta back to control + shift. Nothing happens as in the second screenshot.

**Comment by kovidgoyal** [comment]
I have no idea what you are doing. I didnt suggest you do anything about mapping kitty_meta to anything. There is no such thing as kitty_meta. The debug output shows that you arent actually changing your kitty.conf. I'm afraid I have spent as much time help you as I have available. I will leave you with this:

Run

kitty --config NONE -o 'map cmd+l next_layout'

Open multiple windows, then press cmd+l you will see the layout change. Good luck.

**Comment by eric-lief** [comment]
Sorry 'kitty_mod', not meta...
I am not on linux, but mac. So to open: 
open -n /Applications/kitty.app --args  --config NONE -o 'map cmd+l next_layout'

Doing this, and opening multiple tabs, windows, etc. does 'nothing'

I am also very busy and if mac is not really supported, I woudn't have invested my time in trying to learn how to use and debug this. I thought it looked like a great alternative to the mac Terminal or iTerm, but every time I try a new terminal on mac, there is some issue with the key bindings not working correctly.

**Comment by kovidgoyal** [comment]
mac is supported and the key binding works perfectly. Fix whatever it is
you are doing wrong. Good luck.

**Comment by eric-lief** [comment]
Fix whatever it is you are doing wrong? Dude wtf, I would have to basically redo your project. If you provide software that you intend others to be able to use, you should make it easy for them to get your help into what they are doing wrong. So far, I wasted my time doing exactly what you said, and the behavior on my computer is not what you say. So, you are not supporting differences between your system/s  and the ones you ostensibly support

**Comment by kovidgoyal** [comment]
What a waste of time.  Goodbye.

**Comment by Julian** [comment]
I haven't diagnosed yet but I'll just mention that next_layout has stopped working here as well on macOS. If I remap it to `kitty_mod+k` it works, but `kitty_mod+l` does not. I'll open an issue after diagnosing, but just curious if that's the same for you @eric-lief.

**Comment by kovidgoyal** [comment]
If it's not working it will be because there is some macOS global
shortcut taking precedence on your machine, run kitty with --debug-input
to confirm.

**Comment by Julian** [comment]
Aha! Indeed, thanks, that was helpful -- it seems opening Safari (which I never do, and then must have done a week ago) *enabled* some global shortcut. Disabling it now gets things working again. Appreciated.
