### ISSUE TITLE
Allow `tab_bar_margin_color` to set vertical and horizontal margins separately

### ISSUE THREAD

**Issue by wincent** [kovidgoyal/kitty#7871]
**Is your feature request related to a problem? Please describe.**

Take a config like the following, which has the intent of drawing a border between the tab bar and the main content:

```
# This is the default:
tab_bar_margin_width 0.0

# This overrides the default (0.0 0.0):
tab_bar_margin_height 0.0 2.0

# This overrides the default (none):
tab_bar_margin_color #e0e0e0

# This overrides the default (center):
placement_strategy top
```

You will see the desired margin between the tab bar and the main content.

But, because kitty pads windows when the dimensions don't match integer multiples of the text cell size, you will either see the color on the left and right of the tab bar:

![Image](https://github.com/user-attachments/assets/f75bbfaa-dfe1-4539-9605-93e76f8b2d38)

Or no color on the left and right:

![Image](https://github.com/user-attachments/assets/c12bbb19-120b-4e80-8864-88e50ce1241d)

**Describe the solution you'd like**

The left and right margins popping in and out depending on font size is distracting, so it would be nice to be able to set the colors of vertical margins independently from the horizontal ones.

ie. something like this (using the semantics of [CSS shorthand properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties) to allow passing 1, 2, 3, or 4 values):

```
# 1. Sets the color for all margins, unconditionally:
tab_bar_margin_color #color1

# 2. Sets first color for top/bottom margins and second color for left/right margins:
tab_bar_margin_color #color1 #color2

# 3. Special case of the above — using the keyword "none" to indicate
# "use color that matches neighboring tab background":
tab_bar_margin_color #color1 none

# 4. Separate colors for top, left/right, and bottom margins:
tab_bar_margin_color #color1 #color2 #color3

# 5. Sets separate colors for top, right, bottom, and left margins:
tab_bar_margin_color #color1 #color2 #color3 #color4
```

Now, I don't know if you want to incur the complexity of implementing all those variants. The only one I actually care about here is "3", but I listing them all out anyway in case you wanted to get ahead of potential future feature requests.

**Describe alternatives you've considered**

I looked at:

- https://github.com/kovidgoyal/kitty/issues/5719

which was asking for the same thing:

> Add a second argument to the `tab_bar_margin_color` option, allowing users to set a separate left/right margin color

But it was noted there:

> This wont work since the color needed is different based on whether the active tab is left most or right most or neither.

Eventually, it lead to the solution in fda4aa21a1d29acf3c74ea82dace740120b1a387, which takes care to draw left and right margins accounting for inactive/active tab status. However, it doesn't seem to address the use case I'm detailing here.

**Additional context**

n/a

**Comment by kovidgoyal** [comment]
Not something I care enough about to spend time on, patches welcome.

Note that for your use case, I would just set a non zero
tab_bar_margin_width then you will always have a small margin there will
be no popping or alternately set your tab bar background and your
general background to the same color so the margins dont pop out at all.

**Comment by wincent** [comment]
Sent:

- https://github.com/kovidgoyal/kitty/pull/7876

which ends up being quite a bit more minimal than I had imagined in this issue. No need to add new configuration options, just need to respect the existing `tab_bar_margin_width`.
