### ISSUE TITLE
Tab bar color match terminal background (similar to `macos_titlebar_color background`)

### ISSUE THREAD

**Issue by mike-hearn** [kovidgoyal/kitty#788]
Apologies for what might be a dumb question, but I couldn't find anything in the settings documentation.

Is there a way to color the tab bar to match the active background color of the terminal? Similar to the Mac setting `macos_titlebar_color background`, where the title bar adjusts automatically to match the background.

I tried `inactive_tab_background background`, but that prevented Kitty from opening.

If this isn't possible, and isn't on the roadmap, I'll close this issue. Just wanted to check. Thank you guys for truly excellent software.

**Comment by kovidgoyal** [comment]
Not something I care about personally, but patches are welcome. It should be fairly easy to implement using the same codepaths as used to set the padding color to that of the active window background.
