### ISSUE TITLE
The display and behavior of Bengali in Vim and Neovim are quite strange.

### ISSUE THREAD

**Issue by yishao0925** [kovidgoyal/kitty#7882]
**Describe the bug**
When manipulating Bengali strings in Neovim’s normal and visual modes, abnormal behavior occurs.

**To Reproduce**
#### Normal mode
1.	In normal mode, move the cursor to the line containing Bengali text.
2.	Press $ to move to the end of the line.
3.	The cursor actually moves past the last character, leaving a gap of space beyond it.

#### Visual mode
1.	Enter visual mode and put cursor on the Bengali text.
2.	Select the Bengali text to cut.
3.	Press d to cut the selected text.
4.	The cut text and the remaining text do not behave as expected.

**Screenshots**
[Normal mode video](https://github.com/yishao0925/kitty-bug/blob/main/%E8%9E%A2%E5%B9%95%E9%8C%84%E5%BD%B1%202024-09-21%2018.31.30.mp4)  
[Normalr mode screenshot](https://github.com/user-attachments/assets/75d6bcbf-efef-4d0d-b9b1-9a96241d205c)  
[Visual mode video](https://github.com/yishao0925/kitty-bug/blob/main/%E8%9E%A2%E5%B9%95%E9%8C%84%E5%BD%B1%202024-09-21%2020.16.20.mp4)  
[Visual mode screenshot before cut:](https://github.com/user-attachments/assets/b31aee5a-91f5-41ad-afbf-90b31b56a177)
[Visual mode screenshot after cut:](https://github.com/user-attachments/assets/1a65fb58-8cb5-4678-9eab-1b7d0227c121)

**Comment by kovidgoyal** [comment]
Yes this is because the editor and the terminal disagree on the width of
those characters. Curerntly there is no robust solution to this, however
I am working on one which will hopefully cure such issues permanently.
