### ISSUE TITLE
How do i install the kitty with winget and homebrew??

### ISSUE THREAD

**Issue by arsalanmohseni** [kovidgoyal/kitty#7883]
Hi
I wanna install kitty without any installers, so i wanna install it with winget in my windows enviroment and homebrew in macos
How did i do that??

**Comment by kovidgoyal** [comment]
kitty doesnt run on windows and you can install it with homebrew just
like you install any other software with homebrew.

**Comment by Kasparsu** [comment]
you could and can install kitty on WSL in windows and launch it. Might need to tweak it a bit if window doesn't show up. google running gui apps in WSL. I have had great success with running kitty inside WSL

**Comment by arsalanmohseni** [comment]
So how to do this with homebrew??

**Comment by Kasparsu** [comment]
> So how to do this with homebrew??

on homebrew you can install kitty afaik normally as you would... WSL is for windows as you asked about winget as well. 
[https://formulae.brew.sh/cask/kitty#default](https://formulae.brew.sh/cask/kitty#default)

on windows with wsl you can follow this guide 
https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
and as it is for all intents and purposes a ubuntu you can install it on there with `sudo apt install kitty` or follow install guide here
https://sw.kovidgoyal.net/kitty/binary/ for manual install
