### ISSUE TITLE
browse last command output with `--chop-long-lines` option not working

### ISSUE THREAD

**Issue by simonhf** [kovidgoyal/kitty#7884]
The kitty browse last command output is convenient and seems to just use `less` under the covers. While browsing it's possible to switch on the `less` option `--chop-long-lines` via `-` `shift` `s`. However, after toggling the option then the output never appears chopped. Bug?

Also, how to configure kitty to always browse last command output with the `--chop-long-lines` on by default?

[1] https://superuser.com/questions/735036/how-can-i-switch-line-wrapping-on-and-off-from-within-less

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.scrollback_pager

and kitty has no control over how less renderes lines once less is
running.

**Comment by simonhf** [comment]
Thanks for the link to the conf option to enable `--chop-long-lines`, and I enabled it as follows (and re-loaded the conf file) but it still doesn't work:

```
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

#: Program with which to view scrollback in a new window. The
#: scrollback buffer is passed as STDIN to this program. If you change
#: it, make sure the program you use can handle ANSI escape sequences
#: for colors and text formatting. INPUT_LINE_NUMBER in the command
#: line above will be replaced by an integer representing which line
#: should be at the top of the screen. Similarly CURSOR_LINE and
#: CURSOR_COLUMN will be replaced by the current cursor position or
#: set to 0 if there is no cursor, for example, when showing the last
#: command output.
```

It's like the lines are already wrapped before being fed into `less` with `--chop-long-lines` enabled.

While viewing, I can press e.g. `shift right arrow` and it'll still scroll right, but lines have already been wrapped.

**Comment by kovidgoyal** [comment]
yes, if you are using the default view history binding it shows history
in an overlay that exactly mirrors the underlying window. If you want to
browse output in a different form use the various different ways of
getting that output as described in the docs:
https://sw.kovidgoyal.net/kitty/launch/

In particular dont add wrap markers to the output.
