### ISSUE TITLE
`action launch --cwd=current` uses initial CWD instead of current one when `${EDITOR}` is launched

### ISSUE THREAD

**Issue by Andrew15-5** [kovidgoyal/kitty#7889]
**Describe the bug**
I use kitty with [zellij](https://zellij.dev/about/). I opened a repo and searched for a keyword with `rg` and then opened one of showed URLs via kitty. This opened Neovim, but my script didn't work. Turns out the problem is that the CWD wasn't set correctly. I'm guessing this is because zellij is an abstract program that can open many shells at the same time, and kitty wouldn't know which CWD to use among many.
I think the only solution is somehow coordinate/find out from which shell the URL was opened. But my guess is that kitty can't do this without some additional hacking. Let me know what you think about this.

**To Reproduce**
1. ```kitty
   map kitty_mod+o kitten hints --type hyperlink
   map kitty_mod+;>;>d debug_config
   ```
2. ```conf
   protocol file
   fragment_matches [0-9]+
   action launch --type=os-window --cwd=current ${EDITOR} +${FRAGMENT} ${FILE_PATH}
   ```
3. ```sh
   alias rg='rg --hyperlink-format=kitty'
   ```
4. `kitty zellij` (CWD = initial dir)
<!-- 4. `env -i DISPLAY=$DISPLAY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS PATH=$PATH SHELL=$SHELL kitty zellij` (CWD = initial dir) -->
5. `cd <to some dir with text files>` (CWD ≠ initial dir)
6. `rg <something that exists in some file in CWD>` (CWD ≠ initial dir)
7. kitty_mod+o > select any line number link (CWD ≠ initial dir)
8. a Neovim is opened in a new OS window (inside kitty) (CWD = initial dir)
9. run `:!pwd` (CWD = initial dir)
10. See initial CWD instead of current one (CWD = initial dir)

**Environment details**
<details><summary>details</summary>

```
kitty 0.35.2 (ad328bfeaa) created by Kovid Goyal
Linux pop-os 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64
Pop!_OS 22.04 LTS pop-os /dev/tty

DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319' Detected version: 4.6
Frozen: True
Paths:
  kitty: /home/user/.local/share/kitty.app/bin/kitty
  base dir: /home/user/.local/share/kitty.app/lib/kitty
  extensions dir: /home/user/.local/share/kitty.app/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /home/user/.config/kitty/kitty.conf

Config options different from defaults:
Added shortcuts:
	kitty_mod+; > ; > d →  debug_config
Changed shortcuts:
	kitty_mod+o →  kitten hints --type hyperlink

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	SHELL                               /bin/zsh
	DISPLAY                             :1
```

</details>

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

```kitty
map kitty_mod+o kitten hints --type hyperlink
map kitty_mod+;>;>d debug_config
```

**Comment by kovidgoyal** [comment]
As always my advice is don't use terminal multiplexers, they are a bad
idea. As for your use case you need to get zellij to use the proper
terminal escape code to report the correct cwd corresponding to the
active zellij window to the terminal. And then you need to use
cwd=last_reported in kitty
