### ISSUE TITLE
Re-anchor content after toggle_layout

### ISSUE THREAD

**Issue by dr-yd** [kovidgoyal/kitty#7893]
**Is your feature request related to a problem? Please describe.**
I use `toggle_layout stack` to implement window zooming from splits as suggested in #870 . Usually, this is because the content in the zoomed window does not fit on screen, and I e.g. need to type something that refers to a previous output. After zooming however, the cursor line is in the middle of the buffer, leaving the bottom half blank and unused. Additionally, even when scrolling up and starting to type, Kitty recenters the content so half the window is blank again, obscuring the required context.

**Describe the solution you'd like**
Ideally, content should flow to the bottom of the new layout from the start. If the user has indicated that the content is desired by scrolling, this should be respected in any case.

**Describe alternatives you've considered**
Would probably reuqire a custom kitten if I tried to implement any solution, unless I'm missing something in the docs, but I'm not sure where to start.

**Additional context**
-

**Comment by kovidgoyal** [comment]
Not something I care about. On window resize, the contents of the screen
are reflowed. If the new window size is bigger it wont occupy the full screen.
The only way to occupy the full screen would be to pull content from the
scrollback buffer.

This feature already exists in kitty, it's called unscrolling you can
use it via either escape codes or remote control. To integrate it for
your use case, you would need to write a watcher script that on resize
checks the cursor position and then uses the unscroll function to
unscroll the appropriate number of lines down.

**Comment by dr-yd** [comment]
Alright, thanks for the pointer! I'll have a look at the watcher option.
