### ISSUE TITLE
Cursor option does not work

### ISSUE THREAD

**Issue by CorbinWunderlich** [kovidgoyal/kitty#7897]
Using NixOS home manager to configure kitty  makes it so that the cursor config (in home manager) does not work. The unfocused cursor does work. The same config options did work on my old Arch install.

**To Reproduce**
1. Use this home manager module
```nix
{ pkgs, lib, config, ... }: {
  options.kitty.enable = lib.mkEnableOption "Enables Kitty";

  config = lib.mkIf config.kitty.enable {
    programs.kitty = {
      enable = true;

      environment = { "TERM" = "xterm-256color"; };

      settings = {
        font_family = "JetBrainsMono NF SemiBold";
        bold_font = "JetBrainsMono NF Bold";
        italic_font = "JetBrainsMono NF SemiBold Italic";
        bold_italic_font = "JetBrainsMono NF Bold Italic";

        font_size = 9;

        cursor_shape = "underline";
        cursor_shape_unfocused = "underline";
        shell_integration = "no-cursor";

        cursor_beam_thickness = "1.5";

        cursor_blink_interval = 0;

        default_pointer_shape = "arrow";

        repaint_delay = 6;

        window_margin_width = 5;

        tab_bar_edge = "top";
        tab_bar_margin_height = "6 0";
        tab_bar_style = "fade";
        tab_separator = "";

        tab_bar_align = "left";

        active_tab_font_style = "bold";

        background_opacity = 0;
      };
    };
  };
}
```

**Screenshots**
unfocused: ![unfocused](https://github.com/user-attachments/assets/861acb7e-c240-4769-9e7b-52418415b7ff)
focused: ![focused](https://github.com/user-attachments/assets/1a4ef10b-2b79-40e1-98fa-a89823c0533c)

**Comment by kovidgoyal** [comment]
I am afraid I have no time/interest to debug nix. If you can reproduce
without using nix then feel free to update the issue and I will take a
look.

**Comment by CorbinWunderlich** [comment]
> I am afraid I have no time/interest to debug nix. If you can reproduce without using nix then feel free to update the issue and I will take a look.

This should do for a regular config

```
font_family  JetBrainsMono NF SemiBold;
        bold_font  JetBrainsMono NF Bold;
        italic_font  JetBrainsMono NF SemiBold Italic;
        bold_italic_font  JetBrainsMono NF Bold Italic;

        font_size  9.0

        cursor_shape underline
        cursor_shape_unfocused underline
        shell_integration no-cursor

        cursor_beam_thickness 1.5

        cursor_blink_interval 0

        default_pointer_shape arrow

        repaint_delay 6

        window_margin_width 5

        tab_bar_edge top
        tab_bar_margin_height 6 0
        tab_bar_style fade
        tab_separator ""

        tab_bar_align left

        active_tab_font_style bold

        background_opacity 0
``` 

(sorry for bad formatting)

**Comment by kovidgoyal** [comment]
Works for me with
kitty -o cursor_shape_unfocused=underline -o cursor_shape=underline -o shell_integration=no-cursor

**Comment by CorbinWunderlich** [comment]
> Works for me with kitty -o cursor_shape_unfocused=underline -o cursor_shape=underline -o shell_integration=no-cursor

Running that exact command doesn't work for me :(

**Comment by kovidgoyal** [comment]
then you have something in your shell rc files overriding the cursor
shape.
