### ISSUE TITLE
Background opacity not work properly

### ISSUE THREAD

**Issue by AhJi26** [kovidgoyal/kitty#7898]
**Describe the bug**
After upgrading to 0.36.3, the background opacity can't work properly, the border seems not controlled by this keyword.

**To Reproduce**
open kitty with background opacity less than 1 

**Screenshots**
![image](https://github.com/user-attachments/assets/53d003f5-194e-4ab0-9f4c-9a40b574a51f)

**Environment details**
hyprland 0.43.0 on archlinx.
linux6.10.10

**Comment by kovidgoyal** [comment]
dup of #7895
