### ISSUE TITLE
kitty does not animate gifs

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [kovidgoyal/kitty#790]
kitty icat displays an image in the terminal but if the image is a gif, then it does not animate it. 
Are there plans to have kitty show non-static images the same way they appear in the browser?

**Comment by kovidgoyal** [comment]
No. If you want to view animated images you need a proper terminal image viewer program. icat is never going to do that. It is on my TODO list to someday port y iv image viewer to the terminal, but dont hold your breath.

**Comment by kovidgoyal** [comment]
I dont know of one, but if all you want to do is display a single animated image at a time, it should not require more than a few hundred lines of code to write one.

**Comment by scopatz** [comment]
What is your iv image viewer?

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/iv

**Comment by scopatz** [comment]
Thanks!

**Comment by cybarspace** [comment]
Terminology terminal emulator is able to display gifs inside the terminal. Wouldn't it be easy to "copy" what they do to bring that functionality to icat?

**Comment by kovidgoyal** [comment]
Copy away, I look forward to the PR.

**Comment by cybarspace** [comment]
I'm a noob tho. I can't really do that. Maybe, someday...

**Comment by kovidgoyal** [comment]
Well, to be honest its actually on my TODO list, see #3111 for discussion.
