### ISSUE TITLE
Only Padding area is not Transparent 

### ISSUE THREAD

**Issue by RahulGotrekiya** [kovidgoyal/kitty#7903]
Hi...

I am facing an issue with the Kitty where the entire terminal window is transparent, but the padding area remains non-transparent, and yes, I am facing this after updating Kitty today.
```
background_opacity        0.8
window_padding_width      10
```
(I have just started using Kitty, so if I am missing any configuration, please let me know.  )

Kitty version: kitty 0.36.3
OS: Arch Linux
Window Manager: Hyprland

**Screenshot:**

![image](https://github.com/user-attachments/assets/abec0312-8074-4397-9580-68927853273b)

**Comment by kovidgoyal** [comment]
dup of #7895
