### ISSUE TITLE
background_opacity stopped affecting window_padding_width with version  0.36.3 

### ISSUE THREAD

**Issue by jagaimoworks** [kovidgoyal/kitty#7906]
Starting with kitty 0.36.3 the padding from the *window_padding_width* setting stopped getting affected by *background_opacity*, therefore introducing an unseemly border.

**To Reproduce**
1. Set *background_opacity 0.8*
2. Set *window_padding_width 5* 

**Screenshots**
kitty 0.36.3
![image](https://github.com/user-attachments/assets/e7521834-377d-4dfd-8609-f854c0096137)

and with 0.36.2
![image](https://github.com/user-attachments/assets/ad3408f3-e064-491d-85a7-1120e729b1cc)

**Comment by KeryWT** [comment]
Happening to me too.
Using Arch Linux with KDE Plasma.
Kitty version 0.36.3

**Comment by Reishimanfr** [comment]
can confirm this happens with background_opacity enabled

**Comment by kovidgoyal** [comment]
dup of #7895
