### ISSUE TITLE
Kitty window resizing breaks tmux sessions and Neovim instances after update to v0.36.3 (macOS)

### ISSUE THREAD

**Issue by av1155** [kovidgoyal/kitty#7908]
I have noticed that content in Kitty, such as Tmux sessions or Neovim instances do NOT resize properly anymore and all content gets basically destroyed, when I resize Kitty. This also used to work fine before but now I need to fully quit and open the Kitty app (macOS). Closing the tmux session and starting a new one does not work. Before the update this was never an issue so something must have changed hat affects this.

Since [v0.36.3](https://github.com/kovidgoyal/kitty/releases/tag/v0.36.3).

<img width="850" alt="image" src="https://github.com/user-attachments/assets/0e3a6bc1-1c85-4780-9c77-58f5d3c79653">
<img width="846" alt="image" src="https://github.com/user-attachments/assets/06a9e6ed-cbdd-496c-a107-ddc9c14d088b">
<img width="857" alt="image" src="https://github.com/user-attachments/assets/0a5c83f1-1920-4b35-8021-7b1ac400253c">
<img width="857" alt="image" src="https://github.com/user-attachments/assets/5d4e1258-dc09-4782-b1d2-235a9fd90cd4">
<img width="850" alt="image" src="https://github.com/user-attachments/assets/085cc6a4-3bbb-4d8e-987e-9cba5d9cac75">

**Comment by kovidgoyal** [comment]
Nothing has changed in window resizing in any 0.36 release. And I cannot replicate steps I tried:

1) Start kitty
2) Start nvim
3) open a  file in nvim
4) resize kitty window multiple times
5) observe that nvim redraws correctly after every resize
