### ISSUE TITLE
Shift-PageUp cannot be distinguished from PageUp

### ISSUE THREAD

**Issue by MarSoft** [kovidgoyal/kitty#791]
Steps to reproduce:
1. Open terminal
2. Run `cat`
3. Press `PageUp`. You see: `^[[5~`. This is as expected.
4. Press `Shift+PageUp`. In other terminals it will produce `^[[5;2~` (`st`) or print nothing (`xterm`, `urxvt`). But in `kitty` it will print `^[[5~` just like plain `PageUp`.

Same with `PageDown` (`^[[6~`) and maybe some other keys.

It is convenient to map `Shift+PageUp` to access scrollback buffer in software like `tmux`, similar to how that combination works in "regular" plain-text linux console.

Kitty version: git `master`, commit 634d262b.

**Comment by MarSoft** [comment]
Thanks! Works like a charm now. Extremely fast fix!

**Comment by XenGi** [comment]
if this is fixed why does It still not work for me?
```
$ kitty --version
kitty 0.16.0 created by Kovid Goyal
$ cat
only pgup:
^[[5~

shift+pgup:
^[[5;2~
```

**Comment by XenGi** [comment]
I just thought, this was still an issue because scrolling was not working for me. Turns out I'm just stupid. After putting these 2 lines in my `kitty.conf` everything was working like it should.
```
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
```
