### ISSUE TITLE
Do not remap alt+key as esc+key

### ISSUE THREAD

**Issue by BbIXOD** [kovidgoyal/kitty#7913]
**Is your feature request related to a problem? Please describe.**
I want to play nethack and some commands look like M-key. But kitty (and other terminals) remap alt+key as esc+key.

**Describe the solution you'd like**
Some setting for that in config file.

**Describe alternatives you've considered**
I anyway have alacrity and konsole installed, but they do the same. So I need to set up at least one of them

**Additional context**
IDK, is this exist already.

**Comment by kovidgoyal** [comment]
It exists, read the docs and you will find it.

**Comment by BbIXOD** [comment]
I literally watched every occurance of alt key but i found only option for macos (i am using linux) and kitty_mod which is for kitty shortcuts, not in-app

**Comment by kovidgoyal** [comment]
The *first* thing you do before opening an issue asking for help
from hard working maintainers is read the FAQ.

From the FAQ:
https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program
