### ISSUE TITLE
Kitty fails to use zsh linked library when launched from spotlight/dock

### ISSUE THREAD

**Issue by vfosterm** [kovidgoyal/kitty#7914]
**Describe the bug**
The Macos version of ZSH does not ship with pcre linked. A zsh plugin I use requires it, so I installed the homebrew version and changed my shell.
This fixed the issue in every terminal except for kitty when launched from spotlight, in which case I get the following:
```
p_parse_config_file:7: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.9/zsh/pcre.so, 0x0009): tried: '/usr/lib/zsh/5.9/zsh/pcre.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/zsh/5.9/zsh/pcre.so' (no such file), '/usr/lib/zsh/5.9/zsh/pcre.so' (no such file, not in dyld cache)
_parse_config_file:7: -pcre-match not available for regex
```
If I launch from itself with the exact same config it works fine:
`kitty --config ~/.config/kitty/kitty.conf`

The library itself is linked:
```
otool -L $(which zsh)
/usr/local/bin/zsh:
	/usr/local/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.13.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
	/usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
```
vs the zsh shipped by macos:
```
otool -L /bin/zsh
/bin/zsh:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)

If I manually execute the shell binary from kitty it also works fine:
/usr/local/bin/zsh
```

**To Reproduce**
1. See https://github.com/sunlei/zsh-ssh/issues/23 for the plugin installation / remediation steps
2. Try to use the plugin
3. See error
4. Use the workarounds above / try other shells to see that the issue is only present when kitty is launched from spotlight/dock/etc and not from terminal

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

**Comment by vfosterm** [comment]
Thank you for pointing me in the right direction. I was able to resolve this by setting the shell variable in the kitty.conf
`shell /usr/local/bin/zsh`

out of curiosity, where is kitty getting the shell env variable from? If possible I would like for kitty to see the correct environment variable without overriding it in the kitty.conf.

It is a bit confusing since everything inside the terminal was behaving as if the shell was indeed the correctly specified one.
