### ISSUE TITLE
Dark frame appears along the window border after update

### ISSUE THREAD

**Issue by ms4rkl** [kovidgoyal/kitty#7916]
After running regular packages update on Arch linux (Endeavour OS) there has this dark frame appeared in each kitty window.

It looks like this:
![Screenshot_2024-09-27_18-01-47](https://github.com/user-attachments/assets/280ffbfa-4c07-4fdc-aa9b-98e4f2962eef)

It isn't part of the WM's window frames. I have those disabled globally.

**Comment by kovidgoyal** [comment]
dup of #7895
