### ISSUE TITLE
simd-string-impl.h : fatal error: simde/x86/avx2.h: No such file or directory

### ISSUE THREAD

**Issue by nonumeros** [kovidgoyal/kitty#7918]
When I tried to compile from sources the above message showed up,  `simd-string-impl.h : fatal error: simde/x86/avx2.h: No such file or directory` 

While trying to find anything relevant to this particular issue, 

AI Overview
Learn more
…
This error indicates that the compiler cannot find the simde/x86/avx2.h header file, which is part of the SIMDe library. SIMDe provides a portable way to use SIMD instructions across different platforms.
Here are the potential causes and solutions:
1. SIMDe Library Not Installed or Incorrectly Installed
Solution: Ensure that the SIMDe library is installed on your system. If it's not, install it using your package manager. For example, on Debian-based systems:
Code

   sudo apt-get install libsimde-dev
Solution: If SIMDe is already installed, verify that the installation is correct and that the header files are in the expected location.
2. Missing Include Directory
Solution: Add the include directory for SIMDe to your compiler flags. For example, if you are using GCC:
Code

   g++ -I/path/to/simde/include ...
Replace /path/to/simde/include with the actual path to the SIMDe include directory on your system.
3. Project Configuration Issues
Solution: If you are using a build system like CMake, ensure that it is correctly configured to find and link against the SIMDe library.
4. Compiler Support for SIMD Intrinsics
Solution: Make sure your compiler supports the SIMD instructions you are trying to use. If not, you may need to use a different compiler or disable the use of SIMD instructions in your code.
Troubleshooting Steps
Locate SIMDe Installation: Use the find command to locate the simde/x86/avx2.h file:
Code

   find / -name "avx2.h" 2>/dev/null
Check Compiler Flags:
Verify that the compiler flags are correctly set to include the SIMDe include directory.
Check Build System Configuration:
If you are using a build system, review its configuration to ensure that it is correctly configured to use SIMDe.
Need More Help?
If you are still encountering issues, please provide the following information: Operating System and version, Compiler and version, Build system (if applicable), and Relevant code snippets.
Generative AI is experimental.

Anyhow. My question is, is there any reason as to why both `#include <simde/x86/avx2.h>` and `#include <simde/arm/neon.h>` were set to point to a path that doesn't even exist? What is this? 

```
// Boilerplate {{{
START_IGNORE_DIAGNOSTIC("-Wfloat-conversion")
START_IGNORE_DIAGNOSTIC("-Wpedantic")
#if  defined(__clang__) && __clang_major__ > 13
_Pragma("clang diagnostic push")
_Pragma("clang diagnostic ignored \"-Wbitwise-instead-of-logical\"")
#endif
#include <simde/x86/avx2.h>
#include <simde/arm/neon.h>
#if  defined(__clang__) && __clang_major__ > 13
_Pragma("clang diagnostic pop")
#endif
END_IGNORE_DIAGNOSTIC
END_IGNORE_DIAGNOSTIC
```

Also, what is this from the 

`exec go run bypy/devenv.go "$@"` 

What does it even do? Does it mean that I can't build from source unless that `devenv.go` is  there accordingly? 

I'm just trying to understand here what the purpose of `dev.sh` is at this point, that's all.

You see. Problem is that going by the documentation alone and invoking it (the above) through the  `dev.sh build or dev.sh deps` doesn't get me anywhere really, whereas with the ol' `make` at the very very least I get to have a somehow working kitty. For what it's worth. 

Thank you for the work Kovid.

**Comment by kovidgoyal** [comment]
Why on earth are you posting a bunch of AI slop here? If dev.sh isn't
working for you but make is, go ahead and use make, its not mandatory to
use dev.sh, it's present as a convenience. And what it does is
documented in the kitty build docs.
