### ISSUE TITLE
Can't change color6 - stays yellow forever.

### ISSUE THREAD

**Issue by jellytux** [kovidgoyal/kitty#792]
![config](https://i.imgur.com/3iEHyFx.png)

On the left you see the kitty config.
On the right I print colors 0-15.

**Comment by kovidgoyal** [comment]
I cannot reproduce, running

```
kitty -o 'color6=#3e4450' sh -c 'printf "\e[36mtest"; read'
```

shows test in gray. You either have something in your shell startup scripts that is reseting that color or you aren't using the config file you think you are (--debug-config is useful to check that)
