### ISSUE TITLE
window_padding_width causes non transparent bars with a transparent background

### ISSUE THREAD

**Issue by Naokotani** [kovidgoyal/kitty#7925]
When I set window_padding_width, there are non transparent bars around the window content, but they do not appear with window_margin_width.

I am using nvidia proprietary drivers and hyprland.

with window_padding_width:
![20240929_10h10m07s_grim](https://github.com/user-attachments/assets/fb3749db-3c3f-48b1-a777-fbb532e396d7)

with window_margin_width
![20240929_10h11m01s_grim](https://github.com/user-attachments/assets/04639c36-6f41-4e03-8606-af0c77a8d642)

debug info:
![20240929_10h17m54s_grim](https://github.com/user-attachments/assets/51bf94c0-a9a4-43ea-a2fc-a7a88dc9db0f)

minimal config to reproduce on my system:
```
window_padding_width 10
background_opacity 0.7
```

**Comment by kovidgoyal** [comment]
dup of #7895
