### ISSUE TITLE
Question regarding minimum requirements

### ISSUE THREAD

**Issue by eo1989** [kovidgoyal/kitty#7928]
I run kitty on an old MacBook Pro (Catalina 10.15.7) and am on kitty v.0.36.1. Noticed the notification that 36.4 came out & ran brew upgrade kitty. Brew returned that the minimum version was raised to Big Sur, but I can't find anything on the [changelog](https://sw.kovidgoyal.net/kitty/changelog/#detailed-list-of-changes) to support the upgraded minimum requirement. I'm guessing even if I uninstalled kitty from brew & built it from source, the build would fail? I'm guessing you raised the minimum requirements at the same time you fixed one of the "regressions" mentioned in 36.2 or 36.3?

Cheers!

**Comment by kovidgoyal** [comment]
See 81061a8d43cbbf4732e6af3d47f0fe50b0e46ca8

**Comment by kovidgoyal** [comment]
Ah no, there was one more change: d36a64087e0d12fbb46cf5f98958a45fc5c69b81
So yes the minimum version is now 11 thanks to Go. Catalina was EOLed two years ago. So if you really need to use it, then stick with 0.36.1
