### ISSUE TITLE
IBUS input preview popup doesn't update position and embedded preview is buggy

### ISSUE THREAD

**Issue by PyroLagus** [kovidgoyal/kitty#793]
Normally, the IBUS input popup is always supposed to appear below the first character you type and then move over to the next position after you hit enter and start typing again, but kitty doesn't do that. If I start kitty from xterm, for example, and type something with IBUS, the preview popup appears where it would appear if I typed inside of xterm, not inside the kitty window.

Also, the "embed preedit text in application window" feature is kind of broken in kitty: 

- producing visual glitches (I haven't found a way to reliably reproduce these yet)
- not deleting left-over characters when converting to kanji (for example typing "わたし" (watashi) and converting to kanji with space results in "私たし" instead of "私")
- and sometimes flowing back into the prompt when deleting text (type "ありがとう" (arigatou), convert to kanji, then press '.' instead of enter, and hit backspace several times)

I don't know how much effort it would take to fix that (and many terminal emulators don't even bother to implement that feature), so I think an option to disable that in the kitty config would be enough in the meantime.

**Comment by kovidgoyal** [comment]
I cannot replicate that. The IBUS popup moves with the cursor for me, even after launching kitty from xterm. And I dont know what you mean by "embed preedit text in application window" do you mean display of the preedit text during composing? If so, the backspace functionality is broken -- I just haven't got around to implementing it.
