### ISSUE TITLE
Why does 'kitten @ launch --title Output --keep-focus lazygit' not work?

### ISSUE THREAD

**Issue by bommbo** [kovidgoyal/kitty#7930]
kitten @ launch --title Output --keep-focus vim can work normally.

**Comment by kovidgoyal** [comment]
Presumably because lazygit is not an executable in the PATH you are
running kitty nuder.

**Comment by bommbo** [comment]
But gitui is the same situation, it doesn't work. However, yazi and ranger work normally.

**Comment by kovidgoyal** [comment]
Use launch --hold and you will get error output from the launched program. THough as I said it will be because you are running it in a different environmnet from your shell.

**Comment by bommbo** [comment]
I got it. Thx. I need this .  https://github.com/kovidgoyal/kitty/issues/4903
