### ISSUE TITLE
OSC proposal: Escape code for opening links in user's browser

### ISSUE THREAD

**Issue by kevcube** [kovidgoyal/kitty#7932]
(Not sure if kitty is the right place to propose a new escape code, but seems like a good place to start)

I use terminal applications remotely and in containers that would like to open URLs. When these are run on a user's machine they have options for opening a link in the default browser, but I would like this functionality to work at a terminal level so it can be offloaded from the CLI tool to the terminal.

Similar to how OSC 52 has the ability to interface with a system's clipboard functionality, this proposal would require different behavior on different operating systems.

## Risks

Any app that prints to a terminal now has the ability to open URLs - there are privacy implications here that possibly an application could detect a user's IP from just printing text. In my situation this is not something I am concerned about, because an untrusted program running on my machine is already a risk, and I don't often connect to untrusted remote applications in my terminal. Terminal applications could give users the ability to disable this escape code.

**Comment by kovidgoyal** [comment]
OSC 8 already exists for hyperlinks and is supported in a wide variety
of command line programs from ls to gcc and beyond.

**Comment by kevcube** [comment]
@kovidgoyal as I understand OSC 8 is for printing URLs formatted to the terminal. I’m talking about an escape code that will launch the users default browser to the escaped URL. Possibly an extension of OSC 8

**Comment by kovidgoyal** [comment]
Yes and then the user clicks the URL to launch it. No terminal is going
to allow programs to open arbitrary URLs without user confirmation
anyway, so OSC 8 is functionally equivalent.

If as a user you want your terminal programs to be able to do this and
you dont care about the security implications, you can simply turn on
remote control in kitty and have your terminal programs use it to do
whatever they like, including opening URLs. Remote control has fine
grained access controls so you can lock it down to just allow opening
URLs if you like as well.
