### ISSUE TITLE
cwd entry in "kitty @ ls" output seems wrong

### ISSUE THREAD

**Issue by Percentnineteen** [kovidgoyal/kitty#7937]
**Describe the bug**
I was trying to write a way to dump my session but found that the "cwd" field for a window described by the ls command doesn't seem to reflect the correct window. foreground_processes, KITTY_WINDOW_ID, etc all match expectations

**To Reproduce**
1. Launch a new kitty window (let's assume the cwd is ~)
2. create a new window
3. return to the first window and change directory to somewhere else (for example, ~/code)
4. run kitty @ ls from this window
5. the cwd entry for window 1 is ~ while the cwd entry for window 2 is ~/code

Output from the kitty @ ls
```
[
  {
    "background_opacity": 1.0,
    "id": 1,
    "is_active": true,
    "is_focused": true,
    "last_focused": true,
    "platform_window_id": 12718,
    "tabs": [
      {
        "active_window_history": [
          1,
          2
        ],
        "enabled_layouts": [
          "fat",
          "grid",
          "horizontal",
          "splits",
          "stack",
          "tall",
          "vertical"
        ],
        "groups": [
          {
            "id": 1,
            "windows": [
              1
            ]
          },
          {
            "id": 2,
            "windows": [
              2
            ]
          }
        ],
        "id": 1,
        "is_active": true,
        "is_focused": true,
        "layout": "fat",
        "layout_opts": {
          "bias": 50,
          "full_size": 1,
          "mirrored": false
        },
        "layout_state": {
          "biased_map": {},
          "main_bias": [
            0.5,
            0.5
          ],
          "num_full_size_windows": 1
        },
        "title": "kitty @ ls",
        "windows": [
          {
            "at_prompt": false,
            "cmdline": [
              "/bin/zsh"
            ],
            "columns": 98,
            "created_at": 1727999605363403000,
            "cwd": "/Users/junk",
            "env": {
              "KITTY_WINDOW_ID": "1"
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "kitten",
                  "@",
                  "ls"
                ],
                "cwd": "/Users/junk/code",
                "pid": 57293
              }
            ],
            "id": 1,
            "is_active": true,
            "is_focused": true,
            "is_self": true,
            "last_cmd_exit_status": 0,
            "last_reported_cmdline": "kitty @ ls",
            "lines": 33,
            "pid": 57145,
            "title": "kitty @ ls",
            "user_vars": {}
          },
          {
            "at_prompt": true,
            "cmdline": [
              "/bin/zsh"
            ],
            "columns": 98,
            "created_at": 1727999606807330000,
            "cwd": "/Users/junk/code",
            "env": {
              "KITTY_WINDOW_ID": "2"
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "-zsh"
                ],
                "cwd": "/Users/junk",
                "pid": 57194
              }
            ],
            "id": 2,
            "is_active": false,
            "is_focused": false,
            "is_self": false,
            "last_cmd_exit_status": 0,
            "last_reported_cmdline": "",
            "lines": 34,
            "pid": 57191,
            "title": "junk@macbookair:~",
            "user_vars": {}
          }
        ]
      }
    ],
    "wm_class": "kitty",
    "wm_name": "kitty"
  }
]
```

**Environment details**
```
kitty 0.36.2 (15ac33a058) created by Kovid Goyal
Darwin macbookair.lan 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:49:48 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		15.0 BuildVersion:		24A335
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: True
Fonts:
  medium: Menlo-Regular: /System/Library/Fonts/Menlo.ttc
          Features: ()
    bold: Menlo-Bold: /System/Library/Fonts/Menlo.ttc
          Features: ()
  italic: Menlo-Italic: /System/Library/Fonts/Menlo.ttc
          Features: ()
      bi: Menlo-BoldItalic: /System/Library/Fonts/Menlo.ttc
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/junk/.config/kitty/min.conf

Config options different from defaults:
allow_remote_control yes
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window

Important environment variables seen by the kitty process:
	PATH                                /Users/junk/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/kitty.app/Contents/MacOS
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                junk
	XDG_DATA_DIRS                       /usr/local/share:/usr/share:/Users/junk/.nix-profile/share:/nix/var/nix/profiles/default/share
```

**Comment by kovidgoyal** [comment]
cwd is the cwd of the foreground process. Using cd in a shell does not
necessarily change the shell processed cwd, it only changed the cwd for
subsequent commands run in the shell (depending on how your shell
implements this).

**Comment by Percentnineteen** [comment]
Why does using cd in window 1 change the cwd of window 2? That seems
nonsensical...

**Comment by kovidgoyal** [comment]
Does not reproduce for me with:

kitty -o allow_remote_control=y --session <(echo "layout tall\nlaunch --cwd=~ --hold sh -c 'kitten @ ls'\nlaunch --cwd=/tmp")

**Comment by Percentnineteen** [comment]
That doesn't reflect the sequence I described. Try this:
kitty --config None -o allow_remote_control=y --session <(echo "layout tall\nlaunch --cwd=~ --hold sh -c 'kitten @ ls'\nlaunch --cwd=~")

then, inside that window that launches, (window 1 should be active) run:
cd /tmp && kitten @ ls

You should observe that the cwd of window 2 changed to /tmp. I just don't see how changing the directory of window 1 should change the cwd entry for window 2

**Comment by kovidgoyal** [comment]
On Thu, Oct 03, 2024 at 08:56:06PM -0700, KN wrote:
> That doesn't reflect the sequence I described. Try this:
> kitty --config None -o allow_remote_control=y --session <(echo "layout tall\nlaunch --cwd=~ --hold sh -c 'kitten @ ls'\nlaunch --cwd=~")
>
> then, inside that window that launches, (window 1 should be active) run:
> cd /tmp && kitten @ ls

These instructions are self contradictory. The window that launches is
window 2. If I am running something inside it, window 1 cant be active.

>
> You should observe that the cwd of window 2 changed to /tmp.

Nope the output has cwd=/home/kovid for window with id=1 and cwd=/tmp for window
with id=2, as expected, running it in window 2. And also running it in
window 1 after having run it in 2.

> I just don't see how changing the directory of window 1 should change the cwd entry for window 2

Yup, there is no way that can happen, and it doesn't happen.

**Comment by Percentnineteen** [comment]
When I run the kitty command provided, my window with id 1 is definitely active, so I'm not sure where the mismatch is there. When I run "cd /tmp && kitten @ ls" in the window with id=1, actually BOTH of my windows get cwd updated to /tmp. This behavior is slightly different from what I was seeing in my less narrowed down case but it is still incorrect behavior.

Maybe this will illustrate more clearly:
1. , I launch with:
kitty --config None -o allow_remote_control=y --session <(echo "layout tall\nlaunch --cwd=~ --hold sh -c 'kitten @ ls | grep -e \\\"cwd\\\" -e \\\"id\\\"'\nlaunch --cwd=~"
2. select window 1 in the new window and run:
kitty --config None -o allow_remote_control=y --session <(echo "layout tall\nlaunch --cwd=~ --hold sh -c 'kitten @ ls | grep -e \\\"cwd\\\" -e \\\"id\\\"'\nlaunch --cwd=~"

My output in the window is this:
<img width="695" alt="Screenshot 2024-10-03 at 11 53 20 PM" src="https://github.com/user-attachments/assets/96848fb1-7765-446a-9707-f20d1d043888">

As you can see, I didn't do anything in the second window but you can see that both cwd values changed. I agree with you that this SHOULD'T happen. But I hope an image is sufficient to show that it DOES.

**Comment by kovidgoyal** [comment]
I dont know what on earth you are doing. You seem to be starting one kitty instance and then starting another kitty instance inside it. The second kitty instance will inherit the cwd from the first kitty instance, since when you run kitty it uses the cwd of its environment as its cwd, just like all well behaved non-daemonic programs should. 

I dont know what you are trying to do. Why are you running kitten @ ls multiple times? Why are you starting multiple kitty instances? In any case I have spent about as much time on this as I have available. I will restate that the reported cwd of a window *does not* reflect the cwd of anything other than the foreground process running in that window.

**Comment by Percentnineteen** [comment]
I am attempting to write a kitten to save the layout of a given session (along with the cwd for each window) so that it can be reloaded at a later time. While parsing the output of 'kitten @ ls' to that end, I found that the cwd attribute for windows did not match what was actually in the windows. So I did a little experimentation to see how minimal of a setup I could to reproduce the bug.

I am running kitten @ ls multiple times simply to attempt to show that the state of window 2 changes despite nothing being done in window 2. Previously I only had multiple kitty instances because I was launching my testcase from within another kitty terminal. I can reproduce the same no matter where the kitty process starts from.

In this attached screenshot, I am running one instance of kitty from a Terminal.app window. I killed the kitty process prior to starting this, so everything is as fresh and clean as possible. I literally run the kitty command to start up the session, then inside the kitty session run the cd and kitten @ ls command and the cwd of window 2 changes as evidenced from the output of the first kitty @ ls command and the output of the second. I'm not sure how else to explain this bug. But it is a bug because, as you have agreed, window 2's cwd should not change yet this image shows that it does.

<img width="1223" alt="Screenshot 2024-10-04 at 12 41 41 AM" src="https://github.com/user-attachments/assets/e1e35b87-808f-4d79-8e00-6e36d5dc6c20">

**Comment by kovidgoyal** [comment]
Your previous reproduction steps show you running two kitty instances, not one.
Your latest text description of your steps says you are using one kitty
instance, so again I don't know what you are doing. I suggest you either:

1) Come up with a PR to solve the bug since you say you can reproduce it

2) Write a script that uses remote control to reproduce the issue that
doesn't require any manual steps beyond running kitty as

kitty --config=NONE -o allow_remote_control=y

Then I can fix it. As it stands I cannot reproduce, as I dont
understand your reproduction steps.
