### ISSUE TITLE
mouse cursor invisible when inside the terminal windows in mac os x

### ISSUE THREAD

**Issue by egaburov** [kovidgoyal/kitty#794]
Using master branch.
Built with `make app`

Once the mouse cursor is moved inside an active kitty terminal window, it disappears. I can still select text inside window. but no cursor is visible.

Image with selected text but no cursor:

<img width="1959" alt="screenshot 2018-08-05 21 50 55" src="https://user-images.githubusercontent.com/1485713/43697527-ac30f9ac-98f9-11e8-8f52-4b23b5f4d41e.png">

**Comment by kovidgoyal** [comment]
I cannot replicate this using kitty built from current master.  Steps I tried:

1) Start kitty
2) Wait a few seconds until the mouse cursor disappers
3) Move mouse
4) Mouse cursor re-appears

Make sure your mouse_hide_wait setting i kitty.conf is correct. it should either be zero or some high number like 3 or 5.

**Comment by egaburov** [comment]
When running on integrated GPU (macbook pro 2017,  15'') mouse disappears, but when forcing discrete gpu (by disabling  "automatic graphics switching" in System Preferences->Energy Saver) mouse appears. I have mouse_hide_wait set to 0.0, tried 3, did not try 5, same effect. no mouse cursor when using integrated gpu.

**Comment by kovidgoyal** [comment]
I dont have a macbook pro so I cannot test with that, but on my air which has only an integrated GPU, I cannot reproduce. Presumably, there is some issue with using custom mouse cursor images and dual GPUs. Sadly, without the needed hardware it is hard for me to fix. You can test that by commenting out the call to set_custom_ibeam_cursor in main.py

**Comment by egaburov** [comment]
yup, commenting call to `set_custom_ibeam_cursor` fixes the issue. Thanks
