### ISSUE TITLE
underline_hyperlinks always does not seem to work

### ISSUE THREAD

**Issue by gvlassis** [kovidgoyal/kitty#7945]
Hello!

I am on Kitty 0.36.4 and mac OS 15.

I decided to try underline_hyperlinks always, but it does not seem to take effect. Links are still underlined only if I hover my cursor over them. For debugging, I also tried underline_hyperlinks never, which also does not seem to work (still underlined when I hover).

P.S. I restarted Kitty after the new settings.

**Comment by kovidgoyal** [comment]
underline_hyperlinks only works for actual hyperlinks like those produced
by ls --hyperlink=auto. Text that is detected to be a URL on mouse
over is not affected by this setting, as it is not a real hyperlink.
