### ISSUE TITLE
kitty window won't close by itself after last shell exits

### ISSUE THREAD

**Issue by terceiro** [kovidgoyal/kitty#795]
Occasionally when I exit the last shell on a kitty window, the window won't close by itself. the terminal stays there, as if `exit` was waiting for input (it obviously isn't).

I can't yet determine exactly what triggers this behavior, so I can't reproduce the issue consistently. But I have seen it on several occasions already.

Platform: Debian unstable, kitty 0.11.3-1 from the Debian archive (just checked and it is unpatched)

**Comment by kovidgoyal** [comment]
It will be because some program has the terminal file still open. If you want kitty to close regardless, use the close_on_child_death option in kitty.conf
