### ISSUE TITLE
Startup Sessions: Why is my environment not loaded?

### ISSUE THREAD

**Issue by schroedermatthias** [kovidgoyal/kitty#7952]
**Describe the bug**

I started to discover the Startup Sessions feature. So far, I like it, but the environment does not work as expected and somehow the documentation is very sparse.

**What I want to achieve**

On Kitty startup: 
1) one tab with zsh in ~
2) one tab with k9s
3) one tab with nvim in ~/.config

The issue I am facing is, that the tabs in the sessio**n do not have my environment variables** loaded.

```
new_tab zsh
cd ~
launch zsh <- running env prints all expected environment variables

new_tab k9s
cd ~
launch k9s <- k9s is loaded, but does not know anything about $KUBECONFIG

new_tab .config
cd ~/.config
launch nvim  <- nvim is loaded, but knows nothing about $PATH
```

If I add a section like:

```
new_tab k9s
cd ~
launch zsh -c "k9s"
```

The tab "crashes" and disappears from the tab list. How would I debug why this happens?

Also
```
new_tab k9s
cd ~
launch --env KUBECONFIG=... k9s
```
Works but is definetly not what I want.

**Some facts:**

* macOS Sequoia 15.0.1
* I am using zsh as my default shell + oh-my-zsh
* My ~/.zshenv looks like this:
```
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh/matthias-m1"
```
* In $XDG_CONFIG_HOME/zsh/matthias-m1 my .zshrc resides ans sets lots of environment variables ($PATH, ...)

What am I missing? Overall I think the documentation on how to use the Startup Sessions could be improved as it's currently only a list of possible commands.

Please let me know if you need more info for troubleshooting.

Thanks for helping and best regards
Matthias

**Comment by kovidgoyal** [comment]
On Tue, Oct 08, 2024 at 05:23:21AM -0700, Matthias Schröder wrote:
> **Describe the bug**
>
> I started to discover the Startup Sessions feature. So far, I like it, but the environment does not work as expected and somehow the documentation is very sparse.

You need to read the documentation of your shell not kitty.

>
> **What I want to achieve**
>
> On Kitty startup:
> 1) one tab with zsh in ~
> 2) one tab with k9s
> 3) one tab with nvim in ~/.config
>
> The issue I am facing is, that the tabs in the sessio**n do not have my environment variables** loaded.
>
> ```
> new_tab zsh
> cd ~
> launch zsh <- running env prints all expected environment variables
>
> new_tab k9s
> cd ~
> launch k9s <- k9s is loaded, but does not know anything about $KUBECONFIG

Obviously since you presumably define that env var in your shell startup
files.

>
> new_tab .config
> cd ~/.config
> launch nvim  <- nvim is loaded, but knows nothing about $PATH
> ```

Again, shell startup files.

>
> If I add a section like:
>
> ```
> new_tab k9s
> cd ~
> launch zsh -c "k9s"
> ```
>
> The tab "crashes" and disappears from the tab list. How would I debug why this happens?

launch --hold

>
> Also
> ```
> new_tab k9s
> cd ~
> launch --env KUBECONFIG=... k9s
> ```
> Works but is definetly not what I want.

You need to read the man page of zsh which will tell you that when you
run zsh -c it doesnt read all its startup files and will also tell you
how to get it to do that.

**Comment by schroedermatthias** [comment]
Thank you very much, @kovidgoyal !
Nevertheless you could consider to add --hold to the docs page https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

Thanks and BR
Matthias

**Comment by kovidgoyal** [comment]
It is in the docs page of the launch command.
