### ISSUE TITLE
Kitty slower on Ubuntu 24

### ISSUE THREAD

**Issue by rsmath** [kovidgoyal/kitty#7957]
Hi,

I recently upgraded my Framework 13 laptop from Ubuntu 22.04 to 24.04. None of my startup scripts or kitty config files have changed. But I am definitely noticing a small lag in opening new windows in Kitty. They take more time to load. It's small, but I wonder if I can do anything to fix it.

Relevant: I had to do a fresh install of Ubuntu 24. So I don't know if there's an Ubuntu setting that I did last time I installed Ubuntu, if someone can please remind me of something like that, that would be really helpful.

Thank you for the best terminal.

**Comment by kovidgoyal** [comment]
linux_display_backend x11

**Comment by rsmath** [comment]
I think this is it. Sorry for the naive question, do i disable x11 or do I enable it (by disabling wayland).

Thank you for your prompt reply!!

**Comment by rsmath** [comment]
Adding this line in the kitty.conf did not work 🤔 


``linux_display_server x11``

**Comment by kovidgoyal** [comment]
There is no other setting that can have a bearing on startup speed. And startup speed for me remains the same on Arch Linux up-to-date. I have no clue what Ubuntu 24 does, nor do I much care. Presumably they broke something, I can suggest using the kitty binary releases instead of Ubuntu's kitty package, that might help given the kitty package in Ubuntu will be severly out of date and possibly have random patches added by incompetent package maintainers. Or just use --single-instance for instant startup.

**Comment by rsmath** [comment]
Sorry, I did not explain myself clearly above. The startup speed (when I open kitty as an app) is fast, it is okay. New tabs load slowly. Is this the same problem?

I will try reinstalling Kitty using the binaries on GitHub. Thank you for the suggestion.

**Comment by kovidgoyal** [comment]
New tab/windows loading slowly is your shell loading slowly, it has
nothing to do with kitty.

**Comment by rsmath** [comment]
I see. I will look into my bashrc and see if I'm doing something in there that could be slowing it down. Thanks!

**Comment by rsmath** [comment]
I checked and confirmed that this is what's slowing the new tab/window loading down. Loading conda

```
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ramansh/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ramansh/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ramansh/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ramansh/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
```

I don't know if you use miniconda for your work, but do you initialize conda like this in your setup? This used to work fine in the previous iteration, I wonder what's making it slower now.

**Comment by kovidgoyal** [comment]
no clue, dont use conda.
