### ISSUE TITLE
new action for making the focused window in a layout temporarily full screen

### ISSUE THREAD

**Issue by mil-ad** [kovidgoyal/kitty#7958]
**Is your feature request related to a problem? Please describe.**
Sometimes when I have a stack layout with multiple windows, I'd like to temporarily make the focused windowfull screen to look up something and then go back to the normal stacked layout.

**Describe the solution you'd like**
I'd like an action to toggle full screen for one window (there's `toggle_fullscreen` action but that's for the whole program). If it helps this would the equivalent of i3's `fullscreen toggle` option that toggles fullscreen mode for the focused container

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/actions/#action-toggle_layout
