### ISSUE TITLE
kbd protocol "Disambiguate escape codes" disables VINTR/VSTOP

### ISSUE THREAD

**Issue by krobelus** [kovidgoyal/kitty#7961]
As of today fish prefers to receive `ctrl-c` as SIGINT (not the CSI u encoding) to be able to cancel things like wildcard expansions.
Additionally some users want to enable flow control (`ctrl-s`/`VSTOP`) while inside the shell.

I don't really see a good way of enabling these when the associated key is sent as CSI u encoding.

Maybe we can think of some kind of protocol extension to enable applications to opt into backwards compatibility for select keys.

See also https://codeberg.org/dnkl/foot/issues/1854 for a longer description

**Comment by kovidgoyal** [comment]
In your input handling function, simply signal yourself with SIGINT when
you get ctrl-c. Of course the actual key can be configured via termios
so you need to look it up there via VINTR, VSUSP, VQUIT for interrupt,
stop and quit signals.

That said kitty already has this functionality, albeit undocumented, as
I never bothered to get around to formalising it and adding it to the
spec.

If you want kitty to signal you when user presses the interrupt and
stop keys, set the private mode 19997 via DECSET. Then kitty will
automatically convert VINTR, VSUSP, VQUIT into SIGINT, SIGTSTP and
SIGQUIT as long as ISIG is set in termios for the tty device at the time
of key press.

If there is interest in formalizing this, so other terminal emulators
can implement it, feel free to discuss further. We would need to come up
with a better number that 19997 and add it to spec.

**Comment by kovidgoyal** [comment]
Or actually I am misremembering and this functionality in kitty only works when in legacy keyboard mode. I think it was there for the ssh kitten so that interrupt would work even when ISIG is disabled during the transmit data phase of the kitten. But yes, the mechanism could easily be extended for the keyboard protocol as well. Though given that signalling yourself works just as well I dont really see the point.

**Comment by krobelus** [comment]
Thanks. I was confused because fish is an old-school program where almost everything, including input handling happens on the main thread. I think it shouldn't be a problem to move at least input handling to a separate thread since fish is already using various backgroujnd threads (for better or worse).

Kakoune solves this very elegantly (of course) with their server/client architecture; the client handles all input and signals the server. This allows them to also define `ctrl-g` as another kind of interrupt key.

I don't think there is a way to support flow control (`ctrl-s`/`ctrl-q`) with this setup,
at least not the real one that works across multiple prompts/commands.

I'll ask around how many people want to toggle flow control inside the shell prompt. Maybe that's worth a DECSET code or progressive enhancement flag, we'll see
