### ISSUE TITLE
How to escape single quote (') in config file

### ISSUE THREAD

**Issue by khsoh** [kovidgoyal/kitty#7962]
Hi I am writing key bindings.  How do I escape the single quote character?  For example:

```
map --new-mode pfx --on-action end

map --mode pfx ' select_tab
```

The above does not work because it reports error:

`49:Unterminated string at the end of input in line: map --mode pfx ' select_tab
`

**Comment by kovidgoyal** [comment]
```
"'"
```

**Comment by khsoh** [comment]
Hi I tried putting the single quote within the pair of double quotes:

`map --mode pfx "'" select_tab
`

It did not work.   I am on macOS.

Also, I did confirm that if I use another key like

`map --mode pfx z select_tab
`
It would work fine.

**Comment by kovidgoyal** [comment]
map --mode pfx apostrophe select_tab
