### ISSUE TITLE
Feature request: `kitty --pipe-stdout --pipe-stderr`

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#7964]
It would be great if there was an option that allowed me to pipe the stdout/stderr back to the calling command.

Use case:

I'm creating a workflow where Hammerspoon/Alfred launches 
`zoxide query --interactive`, and the result is used further.

I can do that by launching `kitty sh -c 'zoxide query --interactive' `. Kitty is launched, zoxide/fzf are launched and I can pick my directory. But when I do the child process exits and so the parent kitty process exits and the choice is lost forever

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.forward_stdio
