### ISSUE TITLE
WSL background_image always fails to load

### ISSUE THREAD

**Issue by brianmaher84** [kovidgoyal/kitty#7965]
**Describe the bug**

**To Reproduce**
1. Create kitty.conf file with background_image tag set to (jpg/png/bmp, all failed for me)
2. Download kitty from releases page and copy to directory in /opt/kitty
3. Run kitty from windows terminal kitty --session /home/username/.config/kitty/session.kitty.conf  --config /home/username/.config/kitty/kitty.conf
5. See error

 Failed to convert image at /home/username/kittybg.png to bitmap with python error:
Traceback (most recent call last):
  File "kitty/render_cache.py", line 99, in __call__
  File "kitty/render_cache.py", line 79, in read_metadata
struct.error: unpack requires a buffer of 8 bytes

**Screenshots**

**Environment details**
```
kitty 0.36.4 created by Kovid Goyal
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.4894
Ubuntu 20.04

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

> background_opacity 0.8
background_image /home/username/kittybg.png
background_image_layout scaled
background_tint 0.8
background_tint_gaps -10.0

**Comment by kovidgoyal** [comment]
I'm afraid I dont have the time/interest to support WSL, but you are
welcome to debug further yourself. Basically, that error means the
program kitty uses to convert the image to RGBA data is not writing any
output. You can run it manually and see if you get some errors, like
this:

kitten __convert_image__ RGBA < /path/to/image.jpg > rgba.data

check that rgba.data is not empty after it runs. If it is seeif the
program outputs some error messages. Also delete ~/.cache/kitty/rgba
and retry after my latest commit which improves the error message.

**Comment by kovidgoyal** [comment]
I had a few minutes so I installed WSLg and tried it, it works fine for me. I suggest deleting the cache and trying again as described above.
