### ISSUE TITLE
Deleting an image after interrupted direct transmission doesn't work

### ISSUE THREAD

**Issue by sergei-grechanik** [kovidgoyal/kitty#7968]
**Describe the bug**
Consider the following scenario:
1) A direct image transmission starts, but is interrupted before it finishes.
2) The interrupted image is deleted by image id.
3) It is transmitted again with the same image id.

Deleting the image is important because there is no way to distinguish between a command that starts a direct transmission and a command in the middle of a direct transmission (please correct me if I'm wrong), so otherwise the terminal will construe this as a continuation, and the image will be corrupted. However, this trick doesn't work in kitty. Formally, I don't think it's specified whether deleting an unfinished image is legal, but it's the most logical thing to do in this situation.

**To Reproduce**
Run this script:  [direct_interrupt.sh.txt](https://github.com/user-attachments/files/17351313/direct_interrupt.sh.txt)
Currently it results in the following errors:
```
^[_Gi=100;EILSEQ:More payload loading refers to non-existent image^[\^[_Gi=100;EINVAL:Zero width/height not allowed^[\^[_Gi=100;EINVAL:Zero width/height not allowed^[\^[_Gi=100;EINVAL:Zero width/height not allowed^[\^[_Gi=100;EINVAL:Zero width/height not allowed^[\
```
If the upload is successful, it will display an image of Tux.

**Comment by kovidgoyal** [comment]
I am somewhat puzzled by the use case. First of, why would a
transmission be interrupted and then resumed? Why not just use a new id?
When doing so the previously partially transmitted image is discarded as
the protocol states there can be only one in transit image at a time. If
you want to re-use the same id, transmit a new 1pixel image, delete it,
then re-transmit.

I suppose one could have delete by id delete an in transmit image as
well, but seems unnecessary to me. Consider the delete existing and
in-transit image delete operation to be transmit new 1px image with the
id and then delete it.

**Comment by kovidgoyal** [comment]
I have closed but feel free to discuss further if needed.

**Comment by sergei-grechanik** [comment]
> First of, why would a transmission be interrupted and then resumed?

User interrupt. Or sigkill. Then the user tries to upload the same image.

> Why not just use a new id?

- In tupimage I try to use the same id for the same image for consistency. 
- Some applications may be restricted to 8-bit IDs. Even if we choose the new id at random, the probability of a collision is relatively high.
- Some applications use the same id over and over again (if they need to display a single image at a time). Last time I checked, yazi did this.

> Consider the delete existing and in-transit image delete operation to be transmit new 1px image with the id and then delete it.

I guess I'll try that. It's super hacky though.

**Comment by kovidgoyal** [comment]
On Sat, Oct 12, 2024 at 08:25:24PM -0700, Sergei Grechanik wrote:
> > First of, why would a transmission be interrupted and then resumed?
>
> User interrupt. Or sigkill. Then the user tries to upload the same image.

Interrupts should be handled gracefully by well behaved applications,
they should abort the transmission correctly. As for SIGKILL, sure, but then
sigkill in general can mess up all sorts of terminal state, that is
unavoidable.

>
> > Why not just use a new id?
>
> - In tupimage I try to use the same id for the same image for consistency.

What if the user wants to display the same image twice?

> - Some applications may be restricted to 8-bit IDs. Even if we choose the new id at random, the probability of a collision is relatively high.

Collisions are always going to cause issues, they can cause an existing
image to be unexpectedly deleted, there's no way around that. This is
just another such issue.

> - Some applications use the same id over and over again (if they need to display a single image at a time). Last time I checked, yazi did this.

Weird choice. It should just use an image number rather than and id and
let the terminal pick an id for it. But unless it picks the same id on
every run it will be unaffected. Not to mention that I doubt it sends a
delete before transmit anyway.

>
> > Consider the delete existing and in-transit image delete operation to be transmit new 1px image with the id and then delete it.
>
> I guess I'll try that. It's super hacky though.

In what way is it hacky? It should work with exactly the semantics you
want.

**Comment by sergei-grechanik** [comment]
> Weird choice. It should just use an image number rather than and id and let the terminal pick an id for it.

It's for the unicode placeholder case, where we cannot use image numbers.

> In what way is it hacky? It should work with exactly the semantics you want.

I found a better solution: it's possible to send the final direct transmission command with `m=0` and no data, so I think I will use that.
