### ISSUE TITLE
kitty 0.76.1.13 / windows exe does not support options --help or --config 

### ISSUE THREAD

**Issue by jaalto** [kovidgoyal/kitty#7974]
**Describe the bug**
Windows kitty.exe does not support --config etc. options.  Please add, so that a Desktop Shortcut can be defined to refer to a config file.

**To Reproduce**
1. Download Kitty Classic https://www.fosshub.com/KiTTY.html => rename to kitty.exe
2. Save to DIR
3. cd to DIR
4. ./kitty.exe --config => Command line error: unknown option --config

**Screenshots**

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.
![kitty exe--error](https://github.com/user-attachments/assets/12a53aba-0031-4d5b-a394-0c88998fa237)

**Comment by kovidgoyal** [comment]
You want https://github.com/cyd01/KiTTY

**Comment by jaalto** [comment]
Hm, please elaborate.

1. The https://github.com/cyd01/KiTTY => Official download page / KiTTY is available at our main CDN: Fosshub.
2. points to https://www.fosshub.com/KiTTY.html
Where it reads "KITTY dowload" => Windows classic (exe) 0.76.1.13

The official exe was used In the bug report.
