### ISSUE TITLE
Mac OS: Bell initiates sound device even if sounds are disabled (clicks when turned on and again when turned off)

### ISSUE THREAD

**Issue by krite** [kovidgoyal/kitty#7977]
**Describe the bug**
Bell initiates sound device even if sounds are disabled in kitty-configuration.

This means that if you have corded-headphones, a click is heard even if no sound is played, as the sound-card initiates the sound-system and output, and another click when the sound is turned off.

If using BT-headphones, the same issue is there, the headphones initiate (goes out of sleep-mode) and back again.

**To Reproduce**
1. Have no sound running, all devices are in sleep-state/disabled.
2. Type some nonsene in Kitty terminal and press tab to initiate an error / unable to complete a command.
3. Kitty will try to initiate a bell
4. The sound system is initiated and a click is heard when activating and another when it's deactivated.

**Screenshots**

**Environment details**
Any fairly late OS X version, on any Macbook-laptop.

**Additional context**
For reference, the 'Tabby Terminal' actually disables the sound-activation all together.
The built-in terminal, iTerm2 and several other terminals do the same as Kitty, but that is no reason to not fix this.

**Comment by kovidgoyal** [comment]
There is no bell code called at all when that option is off. See line
2101 in screen.c and line 1973 in glfw.c so what you describe cant be
happening. Most likely this is coming from cocoa when the window
requests attention. You can turn that off via window_alert_on_bell in
kitty.conf.

**Comment by krite** [comment]
Yes, I suspect it's not a direct call to a sound sub-system, but the setting you are referring to is already disabled, so that is not the solution.
Something is still triggering the attention-request, where I seek to totally disable attention-requests.
Please re-open.

**Comment by kovidgoyal** [comment]
I don't see how that's possible. With both those settings disabled,
absolutely no code is called. You have something else going on in your
system. If you disagree a PR is most welcome.

**Comment by krite** [comment]
It is extremely easy to reproduce, so you can very quickly verify it.
Something is triggering the sound-system to go out of sleep-state, this is a fact.
The system is nearly newly bought, weeks old, so no, nothing is unique with the system.

I suggest skipping getting the OSWindow and posting an empty event if none of the two settings (audio_bell and window_alert_on_bell) are set.
This will most definitely not trigger anything. Right now the window instance is fetched and the event is sent in vain (and probably / possibly trigger the sound system activation)

**Comment by kovidgoyal** [comment]
Does not reproduce for me and posting an empty event has absolutely no
connection to the sound system.

**Comment by krite** [comment]
Ok.

So this is a most likely a user-error of course from my side.

The preferences seem not to be re-read when killing the app and restarting it.
Reloading them manually in the menu however actually do make the settings bite.

Indeed there is no sound-activation when the ring_audio_bell is manually set to no.
This I assume is set to yes implicitly if not manually configured?

This ticket can indeed be closed.
Thank you for your patience.
