### ISSUE TITLE
xprop -version may not exist.

### ISSUE THREAD

**Issue by tkerber** [kovidgoyal/kitty#798]
The `panel` kitten runs `xprop -version` to check for the presence of `xprop`. On NixOS (`18.09pre148008.70e72355109 (Jellyfish)`), `xprop -version` doesn't seem to exist as an option, so `xprop` exists with status code 1, and the kitten exits without doing anything.

**Comment by tkerber** [comment]
`xprop` is installed. Considering that the [official man page](https://www.x.org/releases/X11R7.5/doc/man/man1/xprop.1.html) doesn't list the `-version` flag, I would say that it, not nixos, is non-standard in this case.

**Comment by kovidgoyal** [comment]
I have no idea where that man page is coming from. The man page of xprop on my system does list it. As does the man page in the actual source code for xprop from: https://xorg.freedesktop.org/archive/individual/app/xprop-1.2.3.tar.bz2

So what source code is nixos using to build xprop?

**Comment by maximbaz** [comment]
Note that manpage has a typo, it lists the flag as `verson`, not `version`, although `version` is the correct name and also works on my system.

> -verson Print program version information and exit.

**Comment by kovidgoyal** [comment]
I'm guessing nixos is using an older release of xprop. Probably -version was not present in older releases.

**Comment by tkerber** [comment]
Thanks! I should have done more digging on the version differences, but I didn't expect a `-version` flag to be a recent addition to xorg...
