### ISSUE TITLE
padding in Full Screen (Mac with Notch)

### ISSUE THREAD

**Issue by adityaongit** [kovidgoyal/kitty#7981]
**Describe the bug**
When opening Kitty terminal in full screen mode on a MacBook Air M3 with a notch, there is a default padding on the top, left, and right sides of the window. This padding persists even after adding a kitty.conf file with `window_padding_width 0` and `window_padding_height 0` settings. The issue only occurs in full screen mode; other modes work fine without the unwanted padding.

**To Reproduce**
1. Install Kitty terminal on a MacBook Air M3 with a notch
2. Open Kitty terminal
3. Enter full screen mode
4. Observe the unwanted padding on top, left, and right sides
5. Create a kitty.conf file with the following contents:
   ```
   window_padding_width 0
   window_padding_height 0
   ```
6. Restart Kitty and enter full screen mode again
7. Observe that the padding is still present

**Screenshots**
N/A - Screenshots are not provided as the issue affects the entire MacBook screen when the app is opened. So when I try to take screenshots it screenshots the smaller area (inside of the padding)

**Additional context**
- The issue occurs on a MacBook Air M3 with a notch.
- The problem persists even with a minimal configuration (`kitty --config NONE`).
- The padding issue only occurs in full screen mode.
- It's possible that the MacBook's notch is contributing to the problem.

**Comment by kovidgoyal** [comment]
That happens when the window size is not a multiple of the cell size, it
is unavoidable.
