### ISSUE TITLE
Ability to specify different scale/size for fallback font

### ISSUE THREAD

**Issue by maulik13** [kovidgoyal/kitty#7984]
**Is your feature request related to a problem? Please describe.**
I have chosen Iosevka font as my main fonts and Symbols Nerd Font as fallback fonts. This results in icons/symbols being rendered way bigger compared to the main Iosevka fonts. 

**Describe the solution you'd like**
It could probably help fix this issue if I could specify different font size for fallback fonts used in `symbol_map`. I have no idea about feasibility and hence a request.

**Describe alternatives you've considered**
I am looking for a way to rebuild symbols fonts with smaller scale, but I am not an expert here so I have not found anything yet. 

**Additional context**

Fallback font is `Symbols Nerd Font Mono` and regular font `Iosevka`
![image](https://github.com/user-attachments/assets/60b5e06a-3ce0-4f63-b695-0c2031c50592)
![image](https://github.com/user-attachments/assets/fb3111c2-1555-484d-b9a9-f7480e8f8115)

Using `Iosevka patched fonts`
![image](https://github.com/user-attachments/assets/ce3050b3-1d35-45f8-8ab6-11c742c435d2)
![image](https://github.com/user-attachments/assets/82e21303-eb0a-4546-9e84-3921969c336b)

**Comment by kovidgoyal** [comment]
You are following those symbols with a blank space that is why they are rendered larger. Either dont use a blank space or tell kitty you want them rendered in a single cell via narrow_symbols in kitty.conf

**Comment by kovidgoyal** [comment]
no there is no way to specify a different size for fallback fonts.

**Comment by maulik13** [comment]
@kovidgoyal I see. I will then have to find a way to build custom fonts. Thanks.
