### ISSUE TITLE
open-actions.conf works for clicks, doesn't work for hotkeys?

### ISSUE THREAD

**Issue by 097115** [kovidgoyal/kitty#7988]
Probably something on my side, just can't figure out what exactly...

I have `open_url_with` property set to `default`, and also the following open-actions.conf:

    protocol http, https
    action launch --type=background my_own_script ${URL}

The combo works just fine if I click on the URL. However, if I invoke a hotkey (set like this in my kitty.conf: `map kitty_mod+p>u open_url_with_hints`) and then try to open the very same URL, it still calls `xdg-open`... What may I be missing?

Ubuntu 22.04.4 LTS
kitty 0.36.4 (nightly release, generated on: 2024-10-19 21:26:00 UTC from commit: 002d0a0)

**Comment by kovidgoyal** [comment]
The hints kitten, which is what you are using there has its own separate configuration, see:
https://sw.kovidgoyal.net/kitty/kittens/hints/

**Comment by 097115** [comment]
@kovidgoyal 

Thanks for the reply! Just wanted to note that [Open URL hotkey documentation](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Open-URL) explicitly states that

> The program used to open the URL is specified in [open_url_with](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.open_url_with).

Which then seems to contradict the actual behavior :)

---

For anyone facing the same question, you may want to replace the `open_url_with_hints` mapping with something like this:

    map kitty_mod+p>u kitten hints --program my_own_script --type url
