### ISSUE TITLE
IP hints broken

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#7989]
**Describe the bug**
IP hints broken, when my hotkeys get pressed the IPs do not show the markers for the hints and the highlighting looks questionable.

**To Reproduce**
Set: `map kitty_mod+i>p kitten hints --type ip --program @` in `~/.config/kitty/kitty.conf`
2. Just dump some IPs into the terminal
3. Press your kitty mod with i then p.
4. Unable to select any

**Screenshots**
[image](https://imgur.com/a/wIeLl6z)

**Environment details**
```
kitty 0.36.4 (c127517c96) created by Kovid Goyal
Darwin M-J6HX003X0L 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020 arm64
ProductName:            macOS ProductVersion:           14.7 BuildVersion:              23H124
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1```

**Comment by kovidgoyal** [comment]
I cannot replicate, running the following:

kitty -o 'map f1 kitten hints --type ip --program @' --hold sh -c 'echo 1.2.3.4 191.168.1.5; echo 1.1.1.1:80'

All three IP addresses are hinted as expected when pressing F1

**Comment by esn89** [comment]
You are right.  I had another line down below it, that messed things up:

```map kitty_mod+i kitten hints --type regex --regex [a-zA-Z0-9+/=\n\r\0]+ --program - ```
I removed that and all is good.
