### ISSUE TITLE
Sometimes unicode symbols are not displayed 

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#799]
Sometimes I end up with characters like this in my prompt 

<img width="96" alt="screen shot 2018-08-08 at 22 10 52" src="https://user-images.githubusercontent.com/63876/43861724-f9e76d74-9b57-11e8-86fa-e0c016eb06cd.png">

And it happens quite randomly _sometimes it renders, sometimes not_, I tried several fonts too:

- San Francisco Mono
- IBM Plex Mono
- Fira Code
- Iosevka Term

Here are the symbols I use https://github.com/ahmedelgabri/dotfiles/blob/ef31ad9d2ad052e1901f8c406a22948f4f43d701/zsh/.zshrc#L139-L150

They all work in iTerm & alacritty fine.

**Comment by alok** [comment]
I've had this too. I use DejaVu sans mono and most of the time the symbols render fine, but very occasionally it doesn't happen.

**Comment by kovidgoyal** [comment]
Use the --debug-font-fallback option to get information about what fonts are used to render symbols not present in the main font (although I dont recall how well that option is implemented on macOS). Still it might give something useful.

**Comment by kovidgoyal** [comment]
Oh and note that you can tell kitty exactly which font you want it to use for a particular symbol via symbol_map in kitty.conf

**Comment by ahmedelgabri** [comment]
> Oh and note that you can tell kitty exactly which font you want it to use for a particular symbol via symbol_map in kitty.conf

Yeah I know that, but these symbols are in the font & gets rendered already sometimes. That's the problem; it's a bit random. Sometimes they work, sometimes not.

I'm not even sure if it's a fallback font issue, since they render fine with all the fonts I listed in multiple terminal emulators

For example in Iosevka's `U+E0A0` https://be5invis.github.io/Iosevka/specimen.html there is a branch glyph. Sometimes it renders & sometimes not. 


Here is the output of `--debug-font-fallback`

```
[221 11:18:24.030074] Preloaded font faces:
[221 11:18:24.030123] normal face: {'path': '/Users/ahmed/Library/Fonts/iosevka-term-medium.ttf', 'postscript_name': 'Iosevka-Term-Medium', 'family': 'Iosevka Term', 'style': 'Medium', 'bold': False, 'italic': False, 'monospace': True, 'weight': 0.23000000417232513, 'width': 0.0, 'traits': 2147484672}
[221 11:18:24.030153] bold face: {'path': '/Users/ahmed/Library/Fonts/iosevka-term-extrabold.ttf', 'postscript_name': 'Iosevka-Term-Extrabold', 'family': 'Iosevka Term', 'style': 'Extrabold', 'bold': True, 'italic': False, 'monospace': True, 'weight': 0.5, 'width': 0.0, 'traits': 2147484674}
[221 11:18:24.030174] italic face: {'path': '/Users/ahmed/Library/Fonts/iosevka-term-mediumitalic.ttf', 'postscript_name': 'Iosevka-Term-Medium-Italic', 'family': 'Iosevka Term', 'style': 'Medium Italic', 'bold': False, 'italic': True, 'monospace': True, 'weight': 0.23000000417232513, 'width': 0.0, 'traits': 2147484673}
[221 11:18:24.030191] bi face: {'path': '/Users/ahmed/Library/Fonts/iosevka-term-extrabolditalic.ttf', 'postscript_name': 'Iosevka-Term-Extrabold-Italic', 'family': 'Iosevka Term', 'style': 'Extrabold Italic', 'bold': True, 'italic': True, 'monospace': True, 'weight': 0.5, 'width': 0.0, 'traits': 2147484675}
U+9f8 Face(family=Kohinoor Bangla, full_name=Kohinoor Bangla Medium, postscript_name=KohinoorBangla-Medium, path=/System/Library/Fonts/KohinoorBangla.ttc, units_per_em=1000, ascent=25.2, descent=8.4, leading=2.4, point_sz=0.0, scaled_point_sz=24.0, underline_position=-1.8 underline_thickness=1.2) (new face)
U+9f8 Face(family=Kohinoor Bangla, full_name=Kohinoor Bangla Medium, postscript_name=KohinoorBangla-Medium, path=/System/Library/Fonts/KohinoorBangla.ttc, units_per_em=1000, ascent=25.2, descent=8.4, leading=2.4, point_sz=0.0, scaled_point_sz=24.0, underline_position=-1.8 underline_thickness=1.2)
```

**Comment by kovidgoyal** [comment]
I need the debug output from a time when it doesn't render fine.

**Comment by kovidgoyal** [comment]
That shows it is indeed a fallback issue, cocoa is returning the "Last Resort" font for the U+e0a0 symbol. That font always renders as a question mark. U+e0a0 is a private use symbol https://www.fileformat.info/info/unicode/char/e0a0/index.htm

so it will not be present in normal fonts. What font on your system has this symbol? For private use unicode codepoints you really should use symbol_map -- that's what it's designed for. Otherwise what rendering your get for it is not determined by any standard and depends on what order the ystem searches fonts for it.

**Comment by ahmedelgabri** [comment]
That symbol is in Iosevka but that was not the only symbol there were also `◢`, `◥` & `৸` which should be available in IBM Plex too. You can try the typetester here https://www.ibm.com/plex/

**Comment by juanibiapina** [comment]
This still happens. Suddently all weird unicode characters are gone. Restarting kitty doesn't help. At some point things go back to normal, but I can't find the cause.

**Comment by femtomc** [comment]
I'm having the same issue as well - although I think mine is slightly complicated by the fact that I'm using PragmataPro Mono (which doesn't support nerd font glyphs). Sometimes, they render correctly - sometimes they don't.

Is there a way to force a fallback? I'm don't know much about this.
