### ISSUE TITLE
not getting the full kitty.conf

### ISSUE THREAD

**Issue by HyperStandard** [kovidgoyal/kitty#7991]
Not sure if this counts as a bug 
When I used ctrl+shift+f2 to open `kitty.conf` it was mostly empty, except for font family information
I had to remove the file (`~/.config/kitty/kitty.conf`) so that the *next* time I used ctrl+shift+f2 it fills in the whole file

reproduce:
1.fresh install, no config file
2. `kitty +list_fonts` to use the nice tui to change the font (great addition)
3. ctrl+shift+f2 to edit kitty.conf and when you do the only content is the font family
4. you can "fix" it by manually removing kitty.conf and using ctrl+shift+f2 *before* font selection

it would be nice if it maybe copied the whole file in when setting the font if it's a missing file

**Comment by AquilaFasciata** [comment]
What system are you running?
