### ISSUE TITLE
font width and modify_font cell_width issue

### ISSUE THREAD

**Issue by epheien** [kovidgoyal/kitty#7993]
**Describe the bug**

The font width of Kitty terminal is wider than that of other terminals (See image below).
This will cause inconsistency for users migrating from other terminals to Kitty.
<img width="840" alt="Xnip2024-10-23_22-28-24" src="https://github.com/user-attachments/assets/f05020ae-ce86-455b-bef4-6e1a1d8657f9">

This is probably related to the issue of floating-point rounding, which ultimately leads to a difference of 1px.
So I add `modify_font cell_width -1px` in kitty.conf.
This looks like the font width is exactly the same.
<img width="838" alt="Xnip2024-10-23_22-46-07" src="https://github.com/user-attachments/assets/5c83b539-212d-4afb-b3b0-ab02544a1858">

However, this has led to another issue, which is that the rendering of some fonts is truncated by a width of 1 pixel.
(The lower part of the picture is configured with `modify_font cell_width -1px`)
<img width="779" alt="Xnip2024-10-23_22-59-01" src="https://github.com/user-attachments/assets/723e9df9-6ba3-4175-be76-be9c8af62ebb">

**Environment details**
OS: macOS 12
Font: SF Mono
Kitty: nightly

**Comment by kovidgoyal** [comment]
There is no rounding issue, as you found out for yourself when you tried
to narrow the cell size. The font you are using requires that size of
cell. Matching rendered font size with any other terminal is not a goal of kitty.

**Comment by epheien** [comment]
> The font you are using requires that size of cell.

Are you saying that the font is displayed in the cell by truncation rather than scaling?

**Comment by epheien** [comment]
I try `modify_font cell_width -2px`, `%` will not truncate.

I also tried iTerm2 and set the horizontal scaling to 66%. iTerm2 did not experience character truncation and can be said to have achieved perfect scaling.

As shown in the figure below, iTerm2 is above and Kitty is below (`modify_font cell_width 66%`).
<img width="353" alt="Xnip2024-10-24_01-45-49" src="https://github.com/user-attachments/assets/77c1e48d-6d42-48bc-b63a-977af2fdd57e">

**Comment by kovidgoyal** [comment]
Decreasing the cell width will cause truncation, as noted in the docs
for that option. If you want "perfect scaling" change the font_size not
the cell width.

**Comment by epheien** [comment]
> There is no rounding issue

![2024-10-31 14 17 55](https://github.com/user-attachments/assets/56b9c5cd-a710-4ceb-94f0-f9b816efa2d8)

I change `ceilf` to `floorf`, and finally fix my problem.

**Comment by kovidgoyal** [comment]
That is you introducing a rounding problem. If the advance for a glyph is more than N pixels but less than N+1 pixels then the glyph needs N+1 pixels to render, hence ceilf is correct not floorf
