### ISSUE TITLE
[diff kitten] unable to map `cmd+c` to copy_to_clipboard

### ISSUE THREAD

**Issue by jackieli-tes** [kovidgoyal/kitty#7995]
**Describe the bug**

in `diff.conf` I have:

```
map cmd+c copy_to_clipboard
```

However this will not copy text

I have put some print statement in `func (self *Handler) on_key_event(ev *loop.KeyEvent) error `

It turns out the key event never reached diff kitten. Is it because kitty has already intercepted it?

Thanks & Regards,
jackie

**Comment by kovidgoyal** [comment]
yes cmd+c is bound to copy text in kitty itself by default. You can
check such things by running kitty with --debug-input and you can setup
a modal mapping as described in https://sw.kovidgoyal.net/kitty/mapping/
so that cmd+c is unbound when running the diff kitten.
