### ISSUE TITLE
Symbol Lookup Error after updating Ubuntu to 24.10

### ISSUE THREAD

**Issue by kabeleh** [kovidgoyal/kitty#7997]
**Describe the bug**
`kitty` cannot launch, but instead reports `kitty: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_display_create_queue_with_name`

The update of Ubuntu 24.04 to 24.10 introduced this behaviour.

**To Reproduce**
1. Update to Ubuntu 24.10
2. run `kitty` in terminal to see error message.

**Screenshots**

**Environment details**
```
n/a
```

**Additional context**
Same behaviour with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Does not reproduce for me using the current kitty release of 0.36.4
which comes with wayland-123.0 which does have
wl_display_create_queue_with_name in it.
