### ISSUE TITLE
Focusing error with glfw on wayland

### ISSUE THREAD

**Issue by cynddl** [kovidgoyal/kitty#8]
I tried to install kitty on wayland (using the ``glfw-wayland`` package on archlinux), but I get the following error message:

     [glfw error]  Wayland: Focusing a window requires user interaction

I'm not sure how to debug this. Any clue?

**Comment by kovidgoyal** [comment]
No idea, I am completely unfamiliar with wayland. That happens during startup? Does it prevent kitty from running?

**Comment by kovidgoyal** [comment]
From grepping the source code, I cant see anyplace kitty tries to set window focus at all -- it only asks glfw to notify when when the window gains/loses focus -- so I'm guessing this is caused bya  bug in the glfw-wayland backend -- from the docs it is still in beta.

**Comment by cynddl** [comment]
Right, it completely prevents kitty from running and nothing is displayed.

**Comment by kovidgoyal** [comment]
Sorry, I dont have much insight to offer. The code to create the window and startup kitty is in main.py (run_app() function) you can try sticking a few print statements in there to see where the problem is occurring.

**Comment by kovidgoyal** [comment]
Googling that error message shows a couple of other instances of it, for example: https://github.com/nigels-com/glew/issues/115

**Comment by kovidgoyal** [comment]
According to https://github.com/glfw/glfw/issues/945 that error message is harmless, so kitty not workin with wayland is likely caused by something else.

**Comment by kovidgoyal** [comment]
I setup a wayland environment and kitty launches fine in it, provided both glfw and glew are compiled with wayland support. That means building glew with 

make SYSTEM=linux-egl

and glfw with

cmake -DGLFW_USE_WAYLAND=ON ..

**Comment by kovidgoyal** [comment]
nicer numbers from monotonic

**Comment by Luflosi** [comment]
Thanks. I think you meant to post the answer on the commit, not here.
