### ISSUE TITLE
Shell prompt in new tmux pane is drawn incorrectly after vertical split.

### ISSUE THREAD

**Issue by nochiel** [kovidgoyal/kitty#80]
- While in a tmux session: `tmux split-window`
- Notice: 
    - shell prompt is drawn at the bottom of the pane in the tmux status line.
    - cursor is correctly on the first line of the pane.
- `tmux resize-pane -Z` (maximize pane to fill the entire terminal)
- Notice prompt is correctly drawn.
- `tmux resize-pane -Z` (restore pane to previous size of split)
- Notice prompt is either: 
    - not visible.
   - drawn over the tmux status line (until tmux redraws its status line)
---
Attached: 
1. screenshot indicating the prompt drawn incorrectly after `tmux split-window`.
![screenshot at 2017-05-22 21-50-24](https://cloud.githubusercontent.com/assets/284914/26324226/9c0da440-3f3a-11e7-9bda-f81606dbd411.png)

2. kitty [dump.bin](https://drive.google.com/open?id=0By5XNHEDzGd5aEljdlJrVHBxLWs) of tmux when window is split.

**Comment by kovidgoyal** [comment]
Probably another esoteric CSI code I either forgot to implement or implemented incorrectly. I'll look into it when I have moment.
