### ISSUE TITLE
show backscroll after enlarging window

### ISSUE THREAD

**Issue by donpdonp** [kovidgoyal/kitty#800]
I'm a recent kitty convert and probably the only thing I notice thats missing from gnome-terminal is the behavior when a window is maximized.

In gnome-shell when the window is resized to be taller, the cursor stays at the bottom and new lines up top are filled with the backscroll. This is very convenient - many times the output of a command exceeds the window size and I can quickly maximize the window, read what I missed, then restore the window size.

In kitty, the amount of information in the maximized window equals the information that was already in the smaller window. I didnt see a setting for this so I'm filing this request. Thank you.

**Comment by kovidgoyal** [comment]
I'm afraid this is not something I am interested in implementing, but patches are welcome.  If you want to see the contents of the scrollback buffer, simply press ctrl+shift+h and scroll around to read it to your hearts content using your favorite pager program. https://sw.kovidgoyal.net/kitty/#the-scrollback-buffer
