### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by surprisetalk** [kovidgoyal/kitty#8004]
![kitty](https://github.com/user-attachments/assets/a80e407e-0f28-4558-9487-1ebc25a723af)

Anybody up for a new icon? I whipped up something to get the conversation going :)

I'd also be down to hire a real graphic designer, since I see this icon in my dock all day!

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon
