### ISSUE TITLE
Feature request: drawing panels in top or overlays layers

### ISSUE THREAD

**Issue by robin-carlier** [kovidgoyal/kitty#8007]
I really like the new `panel` kitten, but as far as I can tell, it only allows rendering the panels in layers 0 (via `GLFW_LAYER_SHELL_BACKGROUND` or 1 (via `GLFW_LAYER_SHELL_PANEL`). It looks like the various functions in `wl_window.c` don’t allow changing the layer via anything exposed to the user. Would it be possible to add an option/flag to render kitty in layers 2 or 3 (so, top/overlay)? It would allow using a TUI program as a screensaver for instance.

**Comment by kovidgoyal** [comment]
Sure you are welcome to send a PR for it. It's on my long term TODO list but I dont personally have a use case for it at the moment so its not high on that list. Although, how would it work for a screensaver, doesnt a screensaver also need to inform the compositor somehow and lock the screen etc? You can add edge=overlay/whatever for it. 
Ideally, there would be some way to specify geometry so it could be used to draw popups like notifications or dialogs as well. Though I dont remember what the layer shell protocol supports in the way of geometry specification, wayland is queerly allergic to allow windows to position themselves.

Closing the issue feel free to ask more questions if needed.

**Comment by robin-carlier** [comment]
> Although, how would it work for a screensaver, doesnt a screensaver also need to inform the compositor somehow and lock the screen etc?

I was thinking about letting swaylock/hyprlock/whatever handle that.

>Ideally, there would be some way to specify geometry so it could be used to draw popups like notifications or dialogs as well.

Agreed, this would be nice to be able to use kitty as a rofi/wofi/dmenu kind of thing.

> Sure you are welcome to send a PR for it.

I’ll see if I can cook up something in a relatively near future, but that’d be my first time doing something like this and working with this protocol, so this will probably need to be very carefully reviewed once ready.

**Comment by kovidgoyal** [comment]
On Fri, Nov 01, 2024 at 04:22:02AM -0700, Robin Carlier wrote:
>
> &gt; Although, how would it work for a screensaver, doesnt a screensaver also need to inform the compositor somehow and lock the screen etc?
>
> I was thinking about letting swaylock/hyprlock/whatever handle that.
>
> &gt;Ideally, there would be some way to specify geometry so it could be used to draw popups like notifications or dialogs as well.
>
> Agreed, this would be nice to be able to use kitty as a rofi/wofi/dmenu kind of thing.

I doubt you will find the layer_ext protocol capable of doing this. But I will be
happy to be surprised.

>
> &gt; Sure you are welcome to send a PR for it.
>
> I’ll see if I can cook up something in a relatively near future, but that’d be my first time doing something like this and working with this protocol, so this will probably need to be very carefully reviewed once ready.

It should be a fairly trivial patch, simply add more values that --type
can take and them some plumbing to pass them into wl_window.c which just
needs to change the type of surface when creating it based on that
value.
