### ISSUE TITLE
Cannot map ctrl+tab to next_tab

### ISSUE THREAD

**Issue by chdsbd** [kovidgoyal/kitty#801]
Hello,

I've been trying to map `ctrl+tab` to `next_tab`. Here is my config:

```
clear_all_shortcuts yes
map ctrl+tab next_tab
map cmd+t new_tab
```

I'm able to create a new tab with `cmd+tab`, but `ctrl+tab` fails to cycle to the next tab.

I think I'm missing some obvious.

**Comment by kovidgoyal** [comment]
Works for me, remember that if you are on macOS ctrl means the control key on the keyboard. And your keyboard shortcut should not conflict with any globally defined shortcuts/hotkeys.

**Comment by chdsbd** [comment]
I ran `kitty --debug-keyboard` and it seems like the `ctrl+tab` sequence is not being received. Trying with `ctrl+i` worked.

`ctrl+tab` is the [standard way](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Tab_management) to change tabs on macOS, so maybe it's not being handled somewhere in the interface between kitty and macOS.

Did you test `ctrl+tab` on macOS? I've tried this on 10.13 and 10.12 with no success.

**Comment by kovidgoyal** [comment]
Ah macOS -- yeah you are out of luck there. Apple's control freakyness means there is no good way to handle keys Apple has decided should belong to cocoa without jumping through a ton of hoops. Not being a coca developer, I have no clue what those hoops might be. But, patches are welcome.

**Comment by kovidgoyal** [comment]
See for example https://github.com/aseprite/aseprite/blob/4acf12a47890e506999218e9e9aab77033e8d2ba/src/she/osx/event_queue.mm#L38

**Comment by chdsbd** [comment]
Thanks for the quick response and fix!
