### ISSUE TITLE
Cannot get `paste-actions.py` to work

### ISSUE THREAD

**Issue by simonhf** [kovidgoyal/kitty#8013]
**Describe the bug**
I have a config setting which looks like this:
```
# paste_actions quote-urls-at-prompt,confirm
paste_actions filter

#: A comma separated list of actions to take when pasting text into
#: the terminal. The supported paste actions are:

#: quote-urls-at-prompt:
#:     If the text being pasted is a URL and the cursor is at a shell prompt,
#:     automatically quote the URL (needs shell_integration).
#: replace-dangerous-control-codes
#:     Replace dangerous control codes from pasted text, without confirmation.
#: replace-newline
#:     Replace the newline character from pasted text, without confirmation.
#: confirm:
#:     Confirm the paste if the text to be pasted contains any terminal control codes
#:     as this can be dangerous, leading to code execution if the shell/program running
#:     in the terminal does not properly handle these.
#: confirm-if-large
#:     Confirm the paste if it is very large (larger than 16KB) as pasting
#:     large amounts of text into shells can be very slow.
#: filter:
#:     Run the filter_paste() function from the file paste-actions.py in
#:     the kitty config directory on the pasted text. The text returned by the
#:     function will be actually pasted.
#: no-op:
#:     Has no effect.
```
And a `paste-actions.py` file (taken from this [1] example) which looks like this for testing:
```
$ ls ~/.config/kitty/
kitty.conf  paste-actions.py

$ cat ~/.config/kitty/paste-actions.py 
#!/usr/bin/python3

def filter_paste(text):
    # fix kitty bracketed paste (brpaste)
    #return text.replace("\n", "\r")
    new_string = text + "!"
    return new_string
```

However, after reloading the kitty config and attempting to copy and paste a string, then I do not see any exclamation marks! :-(

[1] https://github.com/kovidgoyal/kitty/issues/6939#issuecomment-1880797351

**To Reproduce**
See above.

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 
```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Linux 24-PA-GM0F428N 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64
Ubuntu 24.04.1 LTS 24-PA-GM0F428N /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
Running under: X11
OpenGL: '4.1 (Core Profile) Mesa 24.0.9-0ubuntu0.2' Detected version: 4.1
Frozen: True
Fonts:
  medium: DejaVuSansMono: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
          Features: ()
    bold: DejaVuSansMono-Bold: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf:0
          Features: ()
  italic: DejaVuSansMono-Oblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf:0
          Features: ()
      bi: DejaVuSansMono-BoldOblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf:0
          Features: ()
Paths:
  kitty: /home/simon/.local/kitty.app/bin/kitty
  base dir: /home/simon/.local/kitty.app/lib/kitty
  extensions dir: /home/simon/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/simon/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
mouse_hide_wait      0.0
paste_actions        frozenset({'filter'})
scrollback_lines     20000
Added shortcuts:
	ctrl+insert →  copy_to_clipboard
Changed shortcuts:
	kitty_mod+enter →  new_window_with_cwd
	kitty_mod+t →  new_tab_with_cwd
	shift+insert →  paste_from_clipboard

Important environment variables seen by the kitty process:
	PATH                                /home/simon/.local/kitty.app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
	LANG                                C.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                simon
```

**Comment by kovidgoyal** [comment]
Works for me with:

```sh
echo "def filter_paste(text): return text + 'XXX'" > ~/.config/kitty/paste-actions.py && kitty -o paste_actions=filter
```
