### ISSUE TITLE
No shadow or border with transparent window on macOS

### ISSUE THREAD

**Issue by towerofnix** [kovidgoyal/kitty#8016]
**Describe the bug**

When running kitty 0.37.0 with only one kitty.conf option, `background_opacity 0.90`, set, the window renders with no shadows and mostly no border, except for the highlight along the very top of the macOS window chrome (presumably rendered differently than the typical border around the entire window when in dark mode).

This appears to be the same issue as #2827. PR #6416 was initially opened to address it and commit d3f14ffbf414377743f8e8d76ef24dd173dfc730 was used instead, landing in 0.37.0. Possibly related to #7161, in particular https://github.com/kovidgoyal/kitty/issues/7161#issuecomment-2144226339.

**To Reproduce**

Running macOS 15.1 and kitty 0.37.0.

1. Create `demo-kitty.conf` with contents only `background_opacity 0.90`
2. Run `kitty --conf=demo-kitty.conf`
3. Note the missing shadow and border on the window

**Screenshots**

Running with the specified config:

<img width="929" alt="Kitty window with no shadow" src="https://github.com/user-attachments/assets/755814dc-3c11-48ef-b569-d9558c151e49">

Running kitty with `--config NONE` renders with shadow and border as expected:

<img width="902" alt="Kitty window with all usual macOS decorations" src="https://github.com/user-attachments/assets/a02b11c1-a1b9-49f2-9381-449b8fcb7845">

**Environment details**

```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Darwin cc101.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112 arm64
ProductName:		macOS ProductVersion:		15.1 BuildVersion:		24B83
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: True
Fonts:
  medium: Menlo-Regular: /System/Library/Fonts/Menlo.ttc
          Features: ()
    bold: Menlo-Bold: /System/Library/Fonts/Menlo.ttc
          Features: ()
  italic: Menlo-Italic: /System/Library/Fonts/Menlo.ttc
          Features: ()
      bi: Menlo-BoldItalic: /System/Library/Fonts/Menlo.ttc
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  demo-kitty.conf

Config options different from defaults:
background_opacity 0.9
Changed shortcuts:
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website

Important environment variables seen by the kitty process:
	PATH                                /Users/nebula/.nvm/versions/node/v20.10.0/bin:/opt/homebrew/opt/util-linux/sbin:/opt/homebrew/opt/util-linux/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/kitty.app/Contents/MacOS:/Users/nebula/bin:/Users/nebula/Library/Python/3.12/bin:/Users/nebula/Applications/Development & Editors/Sublime Text.app)/Contents/SharedSupport/bin
	LANG                                en_CA.UTF-8
	SHELL                               /bin/zsh
	USER                                nebula
```

**Comment by kovidgoyal** [comment]
That commit was in version 0.29.0 over a year ago. Are you updating from that old a version or are you saying this is a regression between 0.36 and 0.37? If the latter then it would be helpful if you could bisect to find the offending commit as I cant think of anything that has changed recently that would affect this. And I can never keep track of the ever evolving hacks that apple needs to get decent window decorations.

**Comment by kovidgoyal** [comment]
And ook at the blame history, this is the reason:
https://github.com/kovidgoyal/kitty/issues/6439

**Comment by towerofnix** [comment]
Thanks, I misread the information GitHub was presenting. I saw this 0.37.0 tag element and assumed that meant it was the release including the commit, but didn't think to sanity-check that by comparing dates.

> <img width="424" alt="Commit view on GitHub with 0.37.0 tag" src="https://github.com/user-attachments/assets/40ca725e-347c-44ca-9ced-cc08f5f9592f">

That said I have only been using kitty for a few months, and never tried the `background_opacity` option before today, so I only have experience encountering this issue in 0.37.0 — the comment about the date of the commit was a red herring.

No hard feelings for not tolerating macOS windowing being a pain LOL, thank you for referring to the reason that change was reverted.

**Comment by nem75** [comment]
Should anyone want to look deeper into this, [this flutter issue](https://github.com/flutter/flutter/issues/122133) seems related, which in turn points to [this developer.apple.com forum thread](https://developer.apple.com/forums/thread/696742). Maybe it would be possible to trigger `[NSWindow invalidateShadow]` periodically (e.g. after every move/resize), although that has the smell of a performance reducing hack. Could be worth a try if no other solution is found though.

**Comment by kovidgoyal** [comment]
It's been a while so my memory might be faulty, but IIRC its not about moves and resizes only simply drawing text and then clearing it leaves behind shadows so invalidateShadow isnt going to work. And as for drawing my own shadows, I went that route for GNOME once already, dont have the energy to do it again for this, but PR welcome.

**Comment by nem75** [comment]
I could entirely be wrong as I'm really not proficient in writing desktop apps, but maybe it would be solution to compose the window of a parent window (with shadow) and a child window for the actual terminal (with transparency), thereby breaking up the (apparently on Mac not (well) working) combination of shadow plus transparency on a single window. Just putting it out there, if anyone wants to try.

**Comment by echuber2** [comment]
With respect to this and the related issue https://github.com/kovidgoyal/kitty/issues/6439, would there be a workaround for the text ghosting problem that would involve rendering an opaque rectangle in the terminal and removing it before rendering the text, similar to black frame insertion in LCDs?

Otherwise, in my opinion, the text ghosting issue is *much more subtle and easily ignored* than the lack of window shadows, which really breaks cohesion with the rest of the macOS desktop.
