### ISSUE TITLE
`^M` sending carriage return (`\r`) instead of key code

### ISSUE THREAD

**Issue by jneidel** [kovidgoyal/kitty#8017]
**Describe the bug**
Kitty is returning carriage return (`\r`) instead of the literal key code (`\x0d`, I believe.)

**To Reproduce**
1. `kitty +kitten show_key`
2.  Press `^M`
3. -> `\r`

**Environment details**

Observed in 0.37.0 and 0.36.4

**Additional information**
This is a regression, since it did not happen in previous version (detected because a binding broke.)

**Comment by kovidgoyal** [comment]
^M and \r are the same thing.
In the show-key output you will see ^M in the unix column and \r in the
send_text column indicating they are the same thing.

Furthermore, there were no changes to key handling in 0.37.0

**Comment by kovidgoyal** [comment]
Just to clarify further 0x0d == 13 == byte value of \r in ASCII which is Carriage Return.
