### ISSUE TITLE
Shell text blink

### ISSUE THREAD

**Issue by yermulnik** [kovidgoyal/kitty#8030]
**Describe the bug**
A shell escape codes to make text blink doesn't work in Kitty.

**To Reproduce**
1. `echo '\033[33;5mTitle of the Program\033[0m'`
2. The text `Title of the Program` should be yellow on black and blinking
3. Instead in Kitty it is not blinking

**Environment details**
`kitty 0.37.0 (2531c31d02) created by Kovid Goyal`

**Additional context**
Same behavior with `kitty --config NONE`.
Is it maybe I'm doing something wrong? 🤔

**Comment by kovidgoyal** [comment]
kitty does not and will not support blinking text.

**Comment by kovidgoyal** [comment]
already discussed search the closed issues.

**Comment by yermulnik** [comment]
![image](https://github.com/user-attachments/assets/245e61df-3a89-46c3-9e49-85795272dceb)
334 issues, 14 pages — it's probably easier to update README and provide brief outline of why Kitty doesn't support standard shell feature.

**Comment by kovidgoyal** [comment]
github search is shit google kitty blink issues github and you will find #540 as your first match

**Comment by yermulnik** [comment]
Thanks for the pointer. Pity you've declined this feature. Kitty is great, though those a few missing features from common/traditional terminal apps (e.g. blink and bold) are the rough decision to consider switching to Kitty finally 🙁

**Comment by glad2rest** [comment]
"I won't do a blink, viu support is a rare case, i won't do that, i won't do this blah-blah-blah overhead blah-blah-blah".
You're just lazy. Half measures, half product, half kitty.

**Comment by kovidgoyal** [comment]
ROFL what a moron. Issue closed since it has started attracting fools.
