### ISSUE TITLE
Cursor flickers in Neovim

### ISSUE THREAD

**Issue by pietervdheijden** [kovidgoyal/kitty#8033]
**Describe the bug**
When I open Neovim in Kitty (on Arch Linux), the cursor starts flickering. I attached a screen cast to demonstrate the issue. The same Neovim configuration doesn't let the cursor flicker on Windows terminal and Gnome terminal, so I don't think it's related to my Neovim configuration.

My Neovim configuration can be found on GitHub: https://github.com/pietervdheijden/dotfiles/tree/main/dotfiles/.config/nvim.

**To Reproduce**
N/A - see screencast.

**Screenshots**
Screen cast: 

[Screencast From 2024-11-09 22-18-40.webm](https://github.com/user-attachments/assets/48b3f086-e28b-4193-9f2d-4123f6244af9)

**Environment details**
```
kitty 0.36.4 created by Kovid Goyal
Linux pvdh-dev 6.11.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 17 Oct 2024 20:53:41 +0000 x86_64
Arch Linux 6.11.4-arch1-1 (/dev/tty)

Running under: Wayland (GNOME Shell 47.1) missing: layer_shell
OpenGL: '4.6 (Core Profile) Mesa 24.2.5-arch1.1' Detected version: 4.6
Frozen: False
Fonts:
  medium: FiraCode-Regular: /usr/share/fonts/TTF/FiraCode-Regular.ttf:0
          Features: ()
    bold: FiraCode-SemiBold: /usr/share/fonts/TTF/FiraCode-SemiBold.ttf:0
          Features: ()
  italic: FiraCode-Retina: /usr/share/fonts/TTF/FiraCode-Retina.ttf:0
          Features: ()
      bi: FiraCode-SemiBold: /usr/share/fonts/TTF/FiraCode-SemiBold.ttf:0
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/pieter/.config/kitty/kitty.conf

Config options different from defaults:
font_family FiraCode
font_size   14.0
shell       /usr/bin/zsh

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                pieter
	XDG_DATA_DIRS                       /home/pieter/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

**Additional context**
Issue is still present when running `kitty --config NONE`.

My kitty.config:

```
shell /usr/bin/zsh
font_family FiraCode
font_size 14
```

**Comment by kovidgoyal** [comment]
That's not a flicker its a blink. Change cursor_blink_interval in kitty.conf to something sensible, the default IIRC is to read it from your system configuration where it is presumably some too small value.

**Comment by pietervdheijden** [comment]
Actually, it was indeed a flicker, and I found the cause: my lualine configuration included a function to check if the file was tracked by Git. Apparently, Kitty calls this function continuously, which led to the flickering. After updating the code to a more efficient implementation, the flickering issue is resolved.

For more details, see: https://github.com/pietervdheijden/dotfiles/commit/cc0a7aad212a07c896f907eee3c7bf0da33a51c9.

Anyway, thanks for your quick response!

**Comment by kovidgoyal** [comment]
kitty doesnt call any functions in neovim. If your statusline is being
updated at short intervals it will be because of something in your
stasusline, you should figure out what that is and fix it in the name
of general efficiency if nothing else.

**Comment by pixlmint** [comment]
> Actually, it was indeed a flicker, and I found the cause: my lualine configuration included a function to check if the file was tracked by Git. Apparently, Kitty calls this function continuously, which led to the flickering. After updating the code to a more efficient implementation, the flickering issue is resolved.
> 
> For more details, see: [pietervdheijden/dotfiles@cc0a7aa](https://github.com/pietervdheijden/dotfiles/commit/cc0a7aad212a07c896f907eee3c7bf0da33a51c9).
> 
> Anyway, thanks for your quick response!

Oh my goodnes, I have the exact same issue, lualine checking if the current file is part of git and if my local repo is out of sync with the remote. You just saved my sanity.
