### ISSUE TITLE
Double `\x1b` breaks ANSI codes

### ISSUE THREAD

**Issue by Pistonight** [kovidgoyal/kitty#8037]
**Describe the bug**
When 2 `\x1b` are printed together, it ignores the next ANSI code

**To Reproduce**
```
python -c 'print("Test\x1b\x1b[0m")'
```
Expected Output: `Test`
Actual Output: `Test[0m`

Logs show `[PARSE ERROR] Unknown char after ESC: 0x1b`

Other terminals I tested on (konsole and Windows Terminal) both handle this case gracefully

**Comment by kovidgoyal** [comment]
This is the correct behavior. ESC ESC is an unknown escape code. You
should not be emitting it. Making kitty discard duplicate ESC is of
course, trivial to implement, but I am not at all sure that is a good
idea. It just serves to mask bugs in applications.

**Comment by Pistonight** [comment]
I see your point. However I don't think the standard specifies how invalid escape code should be handled by the parser, so it's up to the terminal emulators to implement. While ESC ESC is invalid, one could argue that it is a valid escape sequence starting from the second ESC (ESC [0m), and kitty not rendering this sequence is incorrect. 

Also consider that from the users' perspectives, the symptom is "X program working in [other terminal] but not kitty". Another way to put it is this fix will prevent the application bug from impacting user experience.

But I totally agree with you it's an application bug if double ESC is emitted.

**Comment by kovidgoyal** [comment]
Yes, but the more such hacks terminal emulators implement the more
people get away with writing broken applications and the worse the
overall ecosystem becomes. Just see the mess that is HTML. I don't want
the terminal ecosystem to become equally messy.
