### ISSUE TITLE
OSC 52 parsing does not validate properly

### ISSUE THREAD

**Issue by benaryorg** [kovidgoyal/kitty#804]
# Issue

The OSC parsing does not handle multiple specified buffers correctly, neither does it implement all possible values and uses defaults that might result in odd behaviour in edge cases, plus it's parsing does not handle invalid data properly.
It is also not handling the querying of the buffer at all (and will in that case probably even break).

## Buffers

The OSC 52 definition as per *xterm* (which is linked in the [*kitty* FAQ](https://github.com/kovidgoyal/kitty/blob/52ec4dc21bfe9e18d3d1b9bb3fba233f6929edf5/docs/faq.rst)) specifies that the second field (there named *Pc*):

> may contain zero or more [buffers]

This is generally handled by checking whether *PRIMARY* is affected or not.
In edge cases (people actually using anything other than `p` or `c`, this may lead to unexpected behaviour.

## Regex

The above mentioned buffers may also be `/[0-7]+/`, therefore the used regex to match the OSC number may mistakenly match that, in case of malformed, or special input.
The Regex used should at least be anchored to the start of the string, because otherwise the trailing semicolon in the pattern might not be the first semicolon found in the string.

## Query

This may or may not be wanted by users and this should probably be feature gated since it allows extraction of sensitive information even on remote shells (e.g. via SSH).
*xterm* does do this for example using it's allowed-opts.

When the value the clipboard should be set to is not a `base64`-encoded string, but a single question mark (`?`), then the terminal should respond with the data contained within the selected buffer.

## Error Handling

Since the data passed to `standard_b64decode()` is not previously validated, this may lead to errors if malformed data is passed (e.g. `cat /dev/urandom` or other binary data).
This goes hand in hand with the above query-thing since that needs to be checked anyway (even if the query itself stays unimplemented for now).

# Possible Solution

I'd prefer the Regex not to be anchored as mentioned above, but instead the whole string partitioned by semicolon from the start and then the individual parts checked.
That way there is no need to parse through the whole string with a Regex and afterwards split by a character that was used as a delimiter in a Regex-search.
Plus a dispatch table since I've seen issues for other OSCs to be implemented.

Of course everything's up for discussion and I'd like to hear your opinion on all this.
However, since this is a terminal which can at times be displaying raw binary data ("oops, forgot the `base64` at the end, now I output my `gzip` stream") I think safe parsing and fault-tolerance should have priority here.

Here a little pseudocode:

```python
def parse_osc(osc_query):
	# a dispatch table, for later easy expansion
	osc_handlers =
		{ 52: copy_to_clipboard,
		}

	# partitioning this first
	(osc_code_raw,_delimiter,rest) = osc_query.partition(';')
	# just in case something fails (e.g. int-parsing)
	try:
		osc_code = int(osc_code_raw)
		# query dispatch_table or default to erroring
		osc_handlers[osc_code]()
	except KeyError:
		# unknown OSC code
		pass
	except ParseError: # or whatever it's named
		# osc_code invalid
		pass

# gets passed the remaining line of the osc_query
def copy_to_clipboard(query):
	# split into the things we are interested
	(buffers,_delimiter,value) = query.partition(';')

	# check for valid buffer values
	if not buffers.match(r'^[cps0-7]+$')
		# buffers invalid
		raise BufferError

	# for every buffer
	for buf in buffers:
		# report it?
		if value == '?':
			if should_report_buffer:
				# report buffer
				pass
			else:
				# maybe report a violation?
				pass
		# valid value?
		elif validate_base64(value):
			# copy to buf
			pass
		else:
			# cannot handle this type of payload
			pass
```

# Relevant Links

- [OSC 52 definition from the *xterm* docs](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands)
- [OSC 52 parsing in *kitty*](https://github.com/kovidgoyal/kitty/blob/2c3235d452580310fd7e23d7a97602819c2a1bc2/kittens/tui/loop.py#L240)

**Comment by kovidgoyal** [comment]
That's not how OSC is parsed in kitty, but in kittens. kittens are intended to run inside kitty and kitty never produces OSC 52 with anything other than p or c. If you want to see how kitty parses OSC 52 look in parser.c and window.py. THere are no regexes involved.
