### ISSUE TITLE
some kind of "draw_minimal_borders always" option

### ISSUE THREAD

**Issue by rkitover** [kovidgoyal/kitty#805]
I'd love it if when I have the `draw_minimal_borders` option enabled, I had minimal borders for all windows, not just inactive ones.

I really don't like the top and bottom borders on windows adjacent to the OS window edge.

Perhaps we could make an option such as:

`draw_minimal_borders always`

for this behavior, and:

`draw_minimal_borders inactive`

would be the same as:

`draw_minimal_borders yes`

**Comment by rkitover** [comment]
> Have borders on only edges in between kitty windows

this does not work, because the active window still has all borders

**Comment by kovidgoyal** [comment]
Yes, that's by design, since that's how the active window is indicated.

**Comment by akhilles** [comment]
@kovidgoyal Would you maybe consider something similar to what tmux does? 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/4852873/54582061-98f72300-49cc-11e9-942d-49f0b3494a3e.png">


I see a couple benefits:

No gaps at window border
<img width="258" alt="image" src="https://user-images.githubusercontent.com/4852873/54582334-93e6a380-49cd-11e9-97a1-32dc4d6502ff.png">

Standard border thickness and appearance no matter which window is active
<img width="309" alt="image" src="https://user-images.githubusercontent.com/4852873/54582411-dc05c600-49cd-11e9-9904-3dea1ad9fcfa.png">

IMO tmux has a very elegant design for this. I'd be willing to contribute to this if you're open to the proposal.

**Comment by kovidgoyal** [comment]
I dont quite understand your proposal. You want active windows to not
have all around borders? If so how would you know which window is active
in the case of say, two side-by-side windows, where there is only a
single border between them?

**Comment by akhilles** [comment]
I was suggesting the approach that tmux uses. In the case you described, half of the shared border is rendered using "active" color based on which pane is active.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/4852873/54585751-37d54c80-49d8-11e9-824a-fd8d371d9772.png">

I realize this is not very intuitive, but I guess I'm sorta used to it.

Maybe it makes more sense to add an option to fully disable active window border? Users can rely on inactive text alpha to identify active window.

As an aside: an option to render the active window with a different background color or opacity would be amazing (but that's probably a separate issue).

**Comment by akhilles** [comment]
I was suggesting the approach that tmux uses. In the case you described, half of the shared border is rendered using "active" color based on which pane is active.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/4852873/54585751-37d54c80-49d8-11e9-824a-fd8d371d9772.png">

I realize this is not very intuitive, but I guess I'm sorta used to it from using tmux.

Maybe it would be simpler to add an option to disable active window border? Also, text alpha can be used to identify active window.

**Comment by kovidgoyal** [comment]
You can probably mostly acheive that already by just setting th eactive window border color to the background color.

**Comment by akhilles** [comment]
I did try that, but the active window border is painted over the inactive border. So, some edges don't show based on which window is active.

**Comment by akhilles** [comment]
Something like `draw_active_window_borders yes` sounds reasonable to me.

**Comment by kovidgoyal** [comment]
Weel you are welcome to contribute a patch for it if you like, not
something I am interested in personally.
