### ISSUE TITLE
Can't select text in interactive terminal app

### ISSUE THREAD

**Issue by joihn** [kovidgoyal/kitty#8057]
thanks for this tool :)
Minor issue:
**Describe the bug**
I like to select/copy text in interactive by doing `ctrl-alt-shift`+ mouse selection
However in lazydocker (https://github.com/jesseduffield/lazydocker), it does not work,
My selection disappear 0.5 second after creating it, so I don't have the time to copy it,

It works well in gnome-terminator, issue seems specific to kitty

**To Reproduce**
1. run lazydocker
2. try to select some text with `ctrl-alt-shift`+ mouse selection

**Environment details**
kitty 0.37.0
ubuntu 24.01
lazydocker Version: 0.23.3

** note **
problem also appears when I start with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
selections get cleared when screen contents in the selected area change. If you want to grab
a snapshot of the screen then press ctrl+shift+h and then do your
selection.
