### ISSUE TITLE
rc files not sourced when using cmd+, to edit config file

### ISSUE THREAD

**Issue by ApolloBian** [kovidgoyal/kitty#806]
I have used some special characters in my .vimrc file, so I have to set `LC_ALL=en_US.UTF-8` in my `.zshrc` file in order for vim to work properly.

When I edit the config file from cmdline, everything works fine:
```bash
vim .config/kitty/kitty.conf
```
![image](https://user-images.githubusercontent.com/13659369/44148547-64ca0d2c-a0cb-11e8-9f8c-9f5da690760f.png)

But when I use `cmd + ,` to edit the config file, it gives the following error:
![image](https://user-images.githubusercontent.com/13659369/44148576-8060b982-a0cb-11e8-8cee-492eb4e3392f.png)

and typing `:!locale` in vim shows the following locale:
![image](https://user-images.githubusercontent.com/13659369/44148615-a3e25654-a0cb-11e8-942e-7e0ede603be4.png)

More info:
     - I use default config file
     - other env variables are not set as well, so I think that the rc files are not sourced

**Comment by kovidgoyal** [comment]
You need to set your environment variables ssytem wide, not in your shell startup scripts. Then they will be present for all processes, not just processes launched via a shell. When you edit the config file using the shortcut in kitty, it does not go via a shell.

**Comment by ApolloBian** [comment]
@kovidgoyal setting environment variables system wide is not always an option due to privillege issues. I come up with this workaround:
```bash
# editor .
# editor vim +"set fileencodings=utf-8"
```

seems to work fine.

**Comment by kovidgoyal** [comment]
I can't imagine a privilege issue that prevents you from setting environment variables system-wide for your user account. But sure, you can do all sorts of things to manually set env vars in the editor command, for example:

```
editor env LANG=en_US.UTF-8 vim
