### ISSUE TITLE
blacklist for `text_fg_override_threshold` feature

### ISSUE THREAD

**Issue by joihn** [kovidgoyal/kitty#8060]
**Is your feature request related to a problem? Please describe.**
feature `text_fg_override_threshold` is awesome, 
but in some binary(often terminal UI) (for example broot https://github.com/Canop/broot) it is undesirable, but still get activated

**Describe the solution you'd like**
In the config, I would like to be able to specifiy a blacklist of apps not to be affected by `text_fg_override_threshold`

**Additional context**
kitty already does have the knowledge about the binary beeing run currently, it currently shows its name in the window title
![image](https://github.com/user-attachments/assets/86d69122-67c4-4e8f-8d50-16569d68868d)

**Comment by kovidgoyal** [comment]
kitty does not have knowledge of the application being run, applications
can be run over SSH for example. If you want to turn this off for broot
use remote control and launch broot via shell alias that first disables
it and then re-enables it after broot quits.
