### ISSUE TITLE
Issue with double click executeable file(help wanted)

### ISSUE THREAD

**Issue by lriy816** [kovidgoyal/kitty#8063]
OS:Arch Linux
DE:xfce4
WM:xfwm4

Hello,thanks for the wonderful terminal.
I have met a weird problem with kitty.

if you have a file with execute bit enable,and with kitty as your only terminal simulator,double click it,it will launch a terminal window and **execute** that file.However,the other terminal simulator's behavior is launch a terminal and launch some text editor like nvim and show the content.I think this behavior is a bit dangerous

Have no idea if this is a special feature for kitty
![2024-11-21_21-28](https://github.com/user-attachments/assets/2edb192a-ae1b-48c8-ada1-02d0983a073e)
![2024-11-21_21-29](https://github.com/user-attachments/assets/621161c5-93e9-482f-9c11-dd739e047b65)
alacritty launch the nvim while kitty execute the file

**Comment by kovidgoyal** [comment]
If you double click on a *executable* file it will be executed. If you
double click on a non-executable shell script you will be asked what to
do with it, edit, it, view it or execute it.

You should not be marking shell scripts you dont trust as executable in
the first place. If you do that, then kitty reasonably assumes you want
to be able to execute the file.
