### ISSUE TITLE
Remotely controlling kitty by password over socket without KITTY_PUBLIC_KEY

### ISSUE THREAD

**Issue by alex-huff** [kovidgoyal/kitty#8069]
It is my understanding that currently it is not possible to remotely control kitty over a password protected socket without the `KITTY_PUBLIC_KEY`.

Having some mechanism for retrieving the `KITTY_PUBLIC_KEY` would enable remote control use cases where `KITTY_PUBLIC_KEY` is not easily obtainable. Better yet, the key could be provided to the `@` kitten automatically. Is there a reason that the public key could not be automatically given to the `@` kitten when it connects to a kitty instance which requests a password?

I've considered disabling the password requirement for remote control over the socket. However, I forward the socket when using the `ssh` kitten and this introduces an obvious security vulnerability. I need to forward the socket because sometimes I launch the `@` kitten from a process that does not have a controlling tty.

My use case:
I use a daemon that listens for MIDI events from a MIDI controller and executes scripts when certain events are received (kind of like a hotkey daemon but for MIDI controllers since they have analog controls like knobs and sliders). I am trying to configure it so that whenever I turn a knob it adjusts the font size of the focused kitty instance using the `@` kitten. Every time knob 75 is turned and kitty is focused I call the kitten:

```
# kitty change font size
MIDI{STATUS==cc}{CC_FUNCTION==75}{FOCUSED_APP_ID=="kitty"}(
    "<size>"->f"{CC_VALUE_SCALED(4, 60)}",
    "<pid>"->FOCUSED_PID
)
[BLOCK|DEBOUNCE]->
{
    # this script is launched by the daemon every time the knob is turned
    # <size> is replaced by a new font size between 4 and 60 based on how far the knob is turned
    # <pid> is replaced by the PID of kitty

    kitten @ --to=unix:"$XDG_RUNTIME_DIR/kitty-<pid>" set-font-size <size>
}

# similar integrations for things like opacity etc.
...
```

The problem is that I have `allow_remote_control` set to `password` so `KITTY_PUBLIC_KEY` must be present in order to remotely control kitty. As my daemon was not launched from kitty, I do not have access to `KITTY_PUBLIC_KEY`.

**Comment by kovidgoyal** [comment]
You can use any mechanism you like. For example in your shell rc files
you can check for $KITTY_PID and $KITTY_PUBLIC_KEY and write the public
key to a file where your daemon can read it. Or you can start kitty with
--session and in the session run a background task that does the above.
Or you can use the watcher mechanism and in your watcher script at
initialization write out the public key as above (available as
boss.encryption_public_key)
