### ISSUE TITLE
Some unicode symbols rendered broken

### ISSUE THREAD

**Issue by webknjaz** [kovidgoyal/kitty#807]
Hi, I'm using [Spaceship theme](https://github.com/denysdovhan/spaceship-prompt) + [Fira Code font](https://github.com/tonsky/FiraCode) and some of symbols appear almost missing.

#### Actual result (Kitty screenshot)
![2018-08-16_102219_391913565](https://user-images.githubusercontent.com/578543/44197489-0e50fb80-a13f-11e8-8161-6f0ebf40a90d.png)

#### Expected result ([Alacritty](https://github.com/jwilm/alacritty) screenshot with the same zsh env)
![2018-08-16_102335_198499381](https://user-images.githubusercontent.com/578543/44197487-0e50fb80-a13f-11e8-9833-6280191c509e.png)

#### Additional info
The broken symbol on screenshot is `➜ `, but I also saw others like `✘ `, `⇡ `, `⇣ `, `⇕ ` etc.

Could you please guide me how to debug the issue and provide you more details if needed?

**Comment by kovidgoyal** [comment]
That will happen if a bitmapped font is used for the symbol in question. kitty does not support bitmapped fonts. Make sure you have a scaleable font with those symbols installed on your system, such as symbola.

You can use the --debug-font-fallback option to kitty to see which font is used for which symbol.

**Comment by webknjaz** [comment]
Is Fira Code bitmapped? Does this mean that it contains *some* bitmapped symbols and others are vectorized?

**Comment by kovidgoyal** [comment]
fira code isn't where those symbols are coming from. As I said, use the --debug-font-fallback option.

**Comment by webknjaz** [comment]
Oh.. okay, thanks!
```
➜ kitty --debug-font-fallback         
[228 11:05:15.274189] Ignoring unknown config key: draw_minimal_borders
[228 11:05:15.274741] Ignoring unknown config key: macos_window_resizable
[228 11:05:15.282706] Preloaded font faces:
[228 11:05:15.282750] normal face: /usr/share/fonts/ttf-bitstream-vera/VeraMono.ttf:0
[228 11:05:15.282794] bold face: /usr/share/fonts/ttf-bitstream-vera/VeraMoBd.ttf:0
[228 11:05:15.282803] italic face: /usr/share/fonts/ttf-bitstream-vera/VeraMoIt.ttf:0
[228 11:05:15.282828] bi face: /usr/share/fonts/ttf-bitstream-vera/VeraMoBI.ttf:0
U+e0a0 bold Face(family=Source Code Pro, style=Bold, ps_name=SourceCodePro-Bold, path=/usr/share/fonts/source-pro/SourceCodePro-Bold.otf, index=0, is_scalable=True, has_color=False, ascender=984, descender=-273, height=1257, underline_position=-100, underline_thickness=50) (new face)
U+279c bold Face(family=Misc Fixed, style=SemiCondensed, ps_name=, path=/usr/share/fonts/misc/6x12.pcf.gz, index=0, is_scalable=False, has_color=False, ascender=0, descender=0, height=0, underline_position=0, underline_thickness=0) (new face)
```

**Comment by kovidgoyal** [comment]
As I said it is using a bitmapped font mis fixed. Install symbola and you will be fine.

**Comment by webknjaz** [comment]
In case if someone is Googling the same issue in future, here's my fixed render:
![2018-08-16_113805_262095255](https://user-images.githubusercontent.com/578543/44201188-f8483880-a148-11e8-9790-1799f220997c.png)

I did `sudo emerge -vu symbola` (Gentoo command for installing symbola font), also optionally adding an explicit symbol mapping *might be* needed (depending on your font priority configs):
```
symbol_map U+279c Symbola
```
