### ISSUE TITLE
Cut/remove selected text

### ISSUE THREAD

**Issue by artenax** [kovidgoyal/kitty#8073]
I like that in Kitty it is possible to move the cursor anywhere in the command.

But to be completely happy, I miss the ability to cut/delete selected text with a hotkey (ideally “Delete”), without workarounds (like copy, delete with Backspace by character/word).

Look at the screenshot.
![kitty](https://github.com/user-attachments/assets/489daddf-0ccc-4c8c-a1b1-ddb6fb0b8595)

I.e. I want functionality like in a text editor. Delete deletes selected text, Ctrl+X cuts.

Maybe this is possible with tweaking kitty.conf? Or will you make such functionality?

There is similar in 9term from plan9port and warp.dev terminals.

**Comment by kovidgoyal** [comment]
No, that functionality requires co-operation from the shell, or doing
some abomination like using a separate editor window like warp does.

**Comment by ParadaCarleton** [comment]
> No, that functionality requires co-operation from the shell, or doing some abomination like using a separate editor window like warp does.

I think it should be fairly easy to enable this for line editors that already cooperate by supporting text selection (e.g. `zle` with `zsh-shift-selection`, `blesh`, and `fish` with `natural-selection`): the same way that mouse clicks transmit a series of `left`/`right` moves, you can have shift+click transmit a series of `shift`+`left`/`right` moves.
