### ISSUE TITLE
Bitmap fonts don't work

### ISSUE THREAD

**Issue by ballerburg9005** [kovidgoyal/kitty#8075]
I cannot load the 6x13 font, and then I saw a really grotesque discussion where devs were pretending that some universe exists where this could somehow make sense to some people some of the time allegedly. When of course in reality, any terminal emulator is total trash that cannot load bitmap fonts. It could not be worse than this. A terminal emulator that doesn't produce crisp text, is like a toaster that can't produce crisp toasts and like a freezer that doesn't freeze. Worse than safety glasses that ship scratched dull from factory, it would be a petty crime against humanity (lowest of low garbage).

I don't care if you can do cheap tricks to make it work. If this is really a design choice, I would say the devs are clinically insane and I don't see how I could ever trust such a project.

Please tell me this is not true.

**Comment by kovidgoyal** [comment]
Fuck off.
