### ISSUE TITLE
expose `launch` options like `--tab` on cli

### ISSUE THREAD

**Issue by KiaraGrouwstra** [kovidgoyal/kitty#8077]
**Is your feature request related to a problem? Please describe.**
i'd like to be able to script tasks like, 'given some directory, open a terminal with tabs for an editor, a git TUI and a shell'. if i understand correctly, actions like running a command in a new kitty tab are now exposed in [`launch`](https://sw.kovidgoyal.net/kitty/launch/) to use with keybinds within kitty, tho not yet more generally.

**Describe the solution you'd like**
expose `launch`'s `--tab` option on the cli

**Describe alternatives you've considered**
wezterm

**Additional context**
-

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/remote-control/

**Comment by KiaraGrouwstra** [comment]
thanks! i now also found another link on people [doing things like this](https://www.reddit.com/r/KittyTerminal/comments/149e7mh/start_multiple_programs_in_new_tabs/).
