### ISSUE TITLE
Line breaks when kitty window size is too small.

### ISSUE THREAD

**Issue by mcourteaux** [kovidgoyal/kitty#8079]
**Describe the bug**
For a couple of months, I get occasionally a random newline / line break inserted in the output of the applications. I was holding of on reporting it for so long, because I have no way of reliably reproducing this, and was only noticing it in my own application, so I didn't have a way to rule out it wasn't my fault. However, today I got several random new lines inserted running another application. Oddly enough, I have so far exclusively noticed them when printing tables using a lot of spaces and `|` as column separators. After some more experimenting, I think I have a way to reproduce.

**To Reproduce**
1. Save this CSV file: https://gist.github.com/mcourteaux/2525144e3673616829874c3d4d8d4c27 (click [Raw to get the data](https://gist.githubusercontent.com/mcourteaux/2525144e3673616829874c3d4d8d4c27/raw/fa41a67264dd3f4aa6aab7d1d4a54daa1db76356/test.csv)).
2. Open kitty, and make a window that's smaller than the output of the next step in both height and width.
3. Run the command to print it in tabular form: `column -s, -t test.csv`
4. Now, maximize the window such that it's bigger than the expected output size. If you can't because the screen is too small for this output, try making the font smaller.
5. Observe the cut in the output.

Alternative steps to reproduce:

1. Make window small.
2. Run: `head -c 50000 /dev/random  | base64 -w 500`
3. Make window big.

Note that I couldn't trigger the issue with only 10000 bytes from random (instead of 50000).
Regardless of the input, it always seems to happen towards the end of the output. If I make sample 100.000 bytes from random, I still get exactly one line break, but again only a couple of lines before the end. The minimum amount of characters outputted to trigger this glitch is dependent on the window size. Bigger window sizes cause this minimum to be larger.

**Screenshots**
![image](https://github.com/user-attachments/assets/c8834c46-7970-4059-84d6-5002f42d579d)

Alternative way:
![image](https://github.com/user-attachments/assets/4de6a013-faaa-4cf2-ad29-392379e32b79)

**Environment details**
```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Linux desktop-martijn 6.11.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 19:13:11 UTC 2024 x86_64
S
Kernel 6.11.5-200.fc40.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland (sway version 1.10-c93ff730 (Nov  6 2024, branch 'v1.10')) missing: blur
OpenGL: '3.1.0 NVIDIA 560.35.03' Detected version: 3.1
Frozen: True
Fonts:
  medium: NotoSansMono-Regular: /usr/share/fonts/google-noto-vf/NotoSansMono[wght].ttf:0
          Features: ()
    bold: NotoSansMono-Bold: /usr/share/fonts/google-noto-vf/NotoSansMono[wght].ttf:262144
          Features: ()
  italic: NotoSansMono-Regular: /usr/share/fonts/google-noto-vf/NotoSansMono[wght].ttf:0
          Features: ()
      bi: NotoSansMono-Bold: /usr/share/fonts/google-noto-vf/NotoSansMono[wght].ttf:262144
          Features: ()
Paths:
  kitty: /home/martijn/.local/kitty.app/bin/kitty
  base dir: /home/martijn/.local/kitty.app/lib/kitty
  extensions dir: /home/martijn/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /home/martijn/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.8
font_family          family="Rec Mono Casual"
font_size            12.0
modify_font:
    cell_width 100%
scrollback_lines     100000
term                 xterm-256color
Added shortcuts:
	kitty_mod+& →  disable_ligatures_in active always
Changed shortcuts:
	kitty_mod+w →  no-op
Colors:
	background           #1c1c1c   
	color0               #3d352a   
	color1               #cd5c5c   
	color10              #88aa22   
	color11              #ffa75d   
	color12              #87ceeb   
	color13              #996600   
	color14              #b0c4de   
	color15              #ddccbb   
	color2               #86af80   
	color3               #e8ae5b   
	color4               #6495ed   
	color5               #deb887   
	color6               #b0c4de   
	color7               #bbaa99   
	color8               #554444   
	color9               #cc5533   
	cursor               #e2bbef   
	foreground           #ddeedd   
	selection_background #4d4d4d   
	selection_foreground #1c1c1c   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/martijn/bin/:/home/martijn/.local/bin/:/home/martijn/.cargo/bin/:/usr/local/go/bin:/home/martijn/go/bin
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                martijn
	XCURSOR_SIZE                        24
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000

```

**Additional context**
The issue also happens when running with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
What happens is when you resize the window, the text content gets reflowed. In that reflow process you can occasionally get a spurious newline.  But you will get just one. It's never bothered me enough to track down but I suspect it happens at the boundary between the screen and history buffers, when there are just right (or rather wrong) number of characters on the screen. Reflowing requires stitching those buffers together and this is not a completely loss free process.

And if you are concerned about this happening in your application, you should always be redrawing the screen when the terminal sends you SIGWNCH indicating a resize has happened (assuming this is a full screen application we are talking about). 

As an application developer you cannot make any assumptions about what is on screen after a resize. Some terminals reflow, some dont, the ones that reflow use different algorithms, etc. Therefore *always* redraw the screen on resize.

If you really care about this issue a PR is welcome. Relevant code is in reflow.c, line-buf.c and history.c

**Comment by mcourteaux** [comment]
I believe you accidentally closed this real issue? Having actual issues be open is useful for other people to find it, and have a place to discuss it. Just because you don't find it important enough doesn't make this a real bug in the program.

> Relevant code is in reflow.c, line-buf.c and history.c

Appreciate this pointers! Thanks!

> And if you are concerned about this happening in your application, you should always be redrawing the screen when the terminal sends you SIGWNCH indicating a resize has happened (assuming this is a full screen application we are talking about).

This is not relevant, as the application already terminated, as shown in my original steps to reproduce. It's just a block of text that gets reflowed incorrectly.

**Comment by kovidgoyal** [comment]
On Tue, Nov 26, 2024 at 06:49:15AM -0800, Martijn Courteaux wrote:
> I believe you accidentally closed this real issue? Having actual issues be open is useful for other people to find it, and have a place to discuss it. Just because you don't find it important enough doesn't make this a real bug in the program.

I dont keep issues open that Ihave no intention of addressing. Just
because an issue is closed doesnt mean it is invisble and you can
continue to post as much as you like on it and if you need something
from me, I will respond.

**Comment by kovidgoyal** [comment]
Oh and sorry reflow.c should be rewrap.c and the entry point function is screen_resize() in screen.c

**Comment by kovidgoyal** [comment]
And previous discussion: https://github.com/kovidgoyal/kitty/issues/7033

**Comment by kovidgoyal** [comment]
fixed in master
