### ISSUE TITLE
Travis CI config refactor

### ISSUE THREAD

**Issue by webknjaz** [kovidgoyal/kitty#808]
I've noticed that `.travis.yml` is a bit messy, would you accept/need a contribution refactoring it?

**Comment by kovidgoyal** [comment]
No, all I care about is that the testing matrix remains the same, the form of travis.yml is not important.

**Comment by webknjaz** [comment]
Well, I think readability matters :)

**Comment by kovidgoyal** [comment]
Perfectly readable to me, but hey, as I said contributions are welcome.
