### ISSUE TITLE
A convenient override for using non-resizeable fonts

### ISSUE THREAD

**Issue by SpomJ** [kovidgoyal/kitty#8085]
As outlined [here](https://github.com/kovidgoyal/kitty/issues/97#issuecomment-579094656), one absolutely can set a font to be scalable (and thus, usable in kitty) by blatantly lying about its scalability.

However, I think there shouldn't be any need for a 'workaround' that involves duplicating fonts just because of kitty's views on "should" and "shouldn't".

A simple config override like `font_use_non_scalable` would do.

---

My use case: `Latin Modern Mono` comes with different faces for different font sizes, and I'd like to use it at ~12px size. CMU exists, but its hinting kinda messes up at size<16px.

**Comment by kovidgoyal** [comment]
As I have said already kitty is not ever going to support non scaleable
fonts. Kindly dont waste your time and mine asking for them.
