### ISSUE TITLE
Desktop notification through tmux adds extra data

### ISSUE THREAD

**Issue by globalshrug** [kovidgoyal/kitty#8086]
**Describe the bug**
From Kitty:
```
printf '\033]99;;Test\033\\'
```
results in the desktop notification ("Test") as expected.
From within `tmux`, with `allow-passthrough` set to `on` or `all`, and with the passthrough escape sequence added to the above (see: https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it):
```
printf '\033Ptmux;\033\033]99;;Test\033\\'
```
results in the desktop notification shown in the screenshot.

**Screenshots**
![Screenshot 2024-11-27 at 2 44 49 PM](https://github.com/user-attachments/assets/5449b011-da59-4fdb-8e5c-e2b4c5b1f73d)

**Environment details**
```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Darwin proteus.local 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:49:39 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.7 BuildVersion:		23H124
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1
Frozen: True
Fonts:
  medium: Menlo-Regular: /System/Library/Fonts/Menlo.ttc
          Features: ()
    bold: Menlo-Bold: /System/Library/Fonts/Menlo.ttc
          Features: ()
  italic: Menlo-Italic: /System/Library/Fonts/Menlo.ttc
          Features: ()
      bi: Menlo-BoldItalic: /System/Library/Fonts/Menlo.ttc
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/ashleyharvey/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity         0.9
bold_font                  menlo Bold
confirm_os_window_close    0
dynamic_background_opacity True
font_family                menlo
hide_window_decorations    1
inactive_text_alpha        0.6
italic_font                menlo Italic
macos_option_as_alt        3
strip_trailing_spaces      smart
window_border_width        (1.0, 'pt')
window_margin_width        FloatEdges(left=1.5, top=1.5, right=1.5, bottom=1.5)
window_padding_width       FloatEdges(left=3.0, top=3.0, right=3.0, bottom=3.0)
Changed shortcuts:
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	kitty_mod+e →  send_text all \x0D
	kitty_mod+escape →  send_text all \x00
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website
Colors:
	active_border_color        #000000   
	inactive_border_color      #000000   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_CA.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.RDIvNP3y5P/org.xquartz:0
	USER                                ashleyharvey
```

**Additional context**
Reproduced with `kitty --config NONE`.

Minimal tmux.conf this was tested with:
```
set-option -g default-terminal screen-256color

# Enable passthrough mode. This is so we can pass escape codes back to kitty for desktop notifications.
set -g allow-passthrough all
```

**Comment by trygveaa** [comment]
You're missing the terminator sequence for the notification. The correct would be:

```
printf '\033Ptmux;\033\033]99;;Test\033\033\\\033\\'
```

**Comment by trygveaa** [comment]
@ashleyharvey: I see that the wiki isn't very clear about the sequence. It says that it's a DCS sequence, which means that it takes the form `\033P<content>\033\\` (as specified in [ECMA-48](https://ecma-international.org/publications-and-standards/standards/ecma-48/)), and that the content has to be prefixed with `tmux;` and any escape characters doubled.

So you start with the sequence `\033]99;;Test\033\\`. Then you need to double every escape character so it becomes `\033\033]99;;Test\033\033\\`. Then you need to prefix it with `\033Ptmux;` and suffix it with `\033\\`. With that it becomes `\033Ptmux;\033\033]99;;Test\033\033\\\033\\`.

**Comment by kovidgoyal** [comment]
Note that passthrough isn't enough to support the desktop notifications spec, this is because it allows for two way communication, the terminal can notify the application when the user clicks the notification or a button on the notification. Passthrough only works for program -> terminal communication not the reverse

**Comment by kovidgoyal** [comment]
On Thu, Nov 28, 2024 at 12:51:50PM -0800, Ashley Harvey wrote:
> > Note that passthrough isn't enough to support the desktop notifications spec, this is because it allows for two way communication, the terminal can notify the application when the user clicks the notification or a button on the notification. Passthrough only works for program -> terminal communication not the reverse
>
> Makes sense. Are you opposed to a feature to get (one-way, as you say) desktop notifications out of tmux? I spend all of my time in tmux and it’s so helpful to e.g. `$ doSomething; kitten notify […]`, but I recognize that may not line up with how kitty is designed. I was going to write in this feature myself but I’ll just opt for a local script instead if that would be unwelcome.

No it's fine, you can model it on the --passthrough-mode flag for the
icat kitten. Just add a disclaimer to the docs that it wont work with
the wait modes.
