### ISSUE TITLE
Dynamically adjust cell size to fit the screen perfectly

### ISSUE THREAD

**Issue by WieeRd** [kovidgoyal/kitty#8087]
**Is your feature request related to a problem? Please describe.**

When `{window size} % {cell size} != 0`, the cells cannot fill the available space completely and an awkward leftover space stands out from a corner. As someone who uses Neovim and TUI apps a lot, this has always bothered me more than it should.

**Describe the solution you'd like**

I propose a new `placement_strategy`, "scale".
Whenever a window resize is detected, re-calculate the cell size that would perfectly divide the available space. Evenly distributing the leftover space between the cells as line spacing.

Most people set their editor font size to show at least 50 lines when vertically maxed out.
Since the leftover space is always smaller than a single cell, only 1-2% change in line spacing
is required to fill the space. 2-4% if the terminal is vertically split.
This is going to be slightly noticeable, but certainly not a disruptive amount.
The change in columns / cell width is going to be even smaller.

The original `cell_height` and `cell_width` can serve as the base / minimum value when this feature is enabled.

**Describe alternatives you've considered**

There are 2 workarounds for this problem, but both of them have significant limitations.

1. `initial_window_height` and `resize_in_steps`.
Fit the window to the cells instead of fitting the cells to the window.
These options were very useful when I was using stacking window managers.
However, they are practically useless for tiling WM users.

2. Adjusting the font size until it fits the screen.
Thanks to Kitty's fractional font size support, it is to set a perfect font size.
...but for only one specific window size. Again, if you are a tiling WM user,
you will be adjusting the terminal to be maxed out, fullscreen, half the screen,
one third of the screen, and on a different monitor with different size and DPI.
Finding a cell size that is the common divisor of all these layouts is impossible.

**Comment by kovidgoyal** [comment]
dup of #6659
