### ISSUE TITLE
Cannot map shift+ctrl+tab to previous_tab

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#809]
I was trying to do basically the same thing as described in #801 but with `shift+ctrl+tab` instead. `kitty --debug-keyboard` also did not receive the tab key while pressing shift and control at the same time. Looking at a143faaf056fcf85098b80758199163c9450068b, it seems that you don't check for this combination.

**Comment by chdsbd** [comment]
@Luflosi Could you check if f9b1f6b fixed this? I just tried the newest Kitty release and `shift+ctrl+tab` doesn't seem to work even with this change

I have this config

```
clear_all_shortcuts yes
map cmd+t new_tab
map ctrl+tab next_tab
map shift+ctrl+tab prev_tab
```

`ctrl+tab` works, `shift+ctrl+tab` doesn't.

**Comment by Luflosi** [comment]
@kovidgoyal Do you think `prev_tab` should be an alias for `previous_tab `?

**Comment by kovidgoyal** [comment]
I have no objections to that, but if you do it, do it for the pther previous commands as well, such as previous_window

**Comment by Luflosi** [comment]
Is there already some command which is an alias for another command? If not how would I implement this?

**Comment by kovidgoyal** [comment]
Just add prev_tab = previous_tab under the definition of the previous_tab method
