### ISSUE TITLE
Desktop notifications don't work from within tmux

### ISSUE THREAD

**Issue by ashleyharvey** [kovidgoyal/kitty#8090]
**Is your feature request related to a problem? Please describe.**
`tmux`, by default, doesn't pass ANSI escape codes through to the terminal. There is an option to pass on the escape code, but only when `tmux` is configured correctly and when the escape code is further wrapped.

It is currently impossible to get desktop notifications from within `tmux` using the notification kitten.

**Describe the solution you'd like**
Get basic, (one-way) desktop notifications from within `tmux` using the notification kitten.

**Additional context**
See: https://github.com/kovidgoyal/kitty/issues/8086
https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it
https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b

**Comment by kovidgoyal** [comment]
There's no need for an issue since you are planning a PR just open the PR directly. If you need help you can always ask here, but closing the issue.
