### ISSUE TITLE
Help with changing window color

### ISSUE THREAD

**Issue by ficolas2** [kovidgoyal/kitty#8091]
I'm trying to change the window color, on the on_focus_change watcher.
It used to work with

`window.change_colors({DynamicColor.default_bg: color})`

But that was removed in 0cf9a79
I tried using window.report_color, but I get this
![image](https://github.com/user-attachments/assets/6da76ca7-ffc0-43df-88ac-113bbf45bf24)

Im guessing I need to call something to send a scape code or something first?

My current code:
```python
from typing import Any, Dict

from kitty.boss import Boss
from kitty.window import Window, DynamicColor
from kitty.fast_data_types import Color
from kitty.conf.utils import to_color

active = "#24273a"
inactive = "#1e1e2e"

def on_focus_change(boss: Boss, window: Window, data: Dict[str, Any])-> None:
    if data["focused"]:
        window.report_color(DynamicColor.default_bg, to_color(active))
    else:
        window.report_color(DynamicColor.default_bg, to_color(inactive))
    window.screen.mark_as_dirty()
    boss.default_bg_changed_for(window.id)
```

**Comment by kovidgoyal** [comment]
Use the remote control API for all such operations, it is stable. See
https://sw.kovidgoyal.net/kitty/kittens/custom/#kitty-api-to-use-with-kittens
