### ISSUE TITLE
[Feature Request] Allow Window Dragging with Hidden Window Decorations on macOS (Command + Drag)

### ISSUE THREAD

**Issue by NEX-S** [kovidgoyal/kitty#8093]
Hello,
I would like to submit a feature request for the macOS version of the Kitty terminal.

Feature Description:
On macOS, when hide_window_decorations is set to no, the window decorations (such as the title bar and borders) are hidden. This makes it impossible to move the window using the standard methods. I propose adding the ability to drag the window by holding down the Command key and dragging anywhere within the window.

Reasons for Implementation:
Improved User Experience: Users who prefer a minimalist setup by hiding window decorations still need a way to reposition the window. Enabling window dragging with Command + drag provides an intuitive method to move the window without revealing decorations.

Consistency with macOS Behavior: Many macOS applications (like iTerm2 and Alacritty) allow users to move windows by holding the Command key and dragging the window content when window decorations are hidden. Implementing this feature would align Kitty with common macOS conventions.

Enhanced Customization: Offering this functionality enhances user customization, allowing for a cleaner interface without sacrificing usability.

Thank you for your continuous efforts in developing Kitty into a powerful and efficient terminal emulator. Implementing this feature would greatly enhance the usability of Kitty on macOS for users who prefer to hide window decorations.
I appreciate your consideration of this request.

**Comment by kovidgoyal** [comment]
hide_window_decorations titlebar-only

then you can drag the window around to move it by dragging the top
shadow area of the window.
