### ISSUE TITLE
kitty window take the full screen when switching to floating in sway window manager

### ISSUE THREAD

**Issue by mhakm** [kovidgoyal/kitty#8094]
**Describe the bug**
When using Kitty with a window manager like Sway, toggling the window to floating mode causes it to occupy the entire screen, rather than behaving like a normal floating window. For comparison, using a different terminal like Foot results in the expected resizing behavior for floating windows. but i need to add that, when switching to float and resizing then closing kitty then open it again and toggling float it remember the size but when refreshing the wm the issue come back
**To Reproduce**
1. open new terminal window
2. toggle float mode
3. See error

**Screenshots**

![20241201_23h37m19s_grim](https://github.com/user-attachments/assets/69533232-cdbc-4d6a-b794-d84fd587bc5a)
![20241201_23h37m41s_grim](https://github.com/user-attachments/assets/b204a5ed-204a-4c11-af6e-93959ca1eb67)

**Comment by kovidgoyal** [comment]
Does not reproduce for me on sway. Simply set the initital window size
to whatever size you want in kitty.conf. That size will be used for
floating windows.

**Comment by mhakm** [comment]
> Does not reproduce for me on sway. Simply set the initital window size to whatever size you want in kitty.conf. That size will be used for floating windows.

didnt work:(
