### ISSUE TITLE
Flickering / jiggling when calling launch

### ISSUE THREAD

**Issue by for-coursera** [kovidgoyal/kitty#8096]
Let's say we have the following mapping:

    map kitty_mod+p>u kitten hints --type url --program "launch --type=background open"

Now, with the current line being the last line (i.e., the scrollback is already filled with some previous output, like `ls -la /bin/`), let's run the following command, for example:

    echo 'https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-type'

Then press the above mentioned hotkey, and then select one of the hints available (which will lead to the selected URL being opened in a default browser).

My problem here is that the moment we select one of the hints, kitty shudders a bit, like the scrollback jumps a line up and then down. Can this somehow be avoided? Alacritty, for instance, doesn't have this side-effect :(

It seems to me, I saw this issue discussed already but couldn't find it right now, so I apologize in advance. But can please something be done? It really messes up the whole experience :(

**Comment by kovidgoyal** [comment]
Does not replicate for me there is no flickering or jiggling. The
contents of the screen are exactly the same as before triggering the
hints overlay, except for colors and the hint characters. There is
certainly no change in lines on the screen. Maybe you are describing the
problem well, I suggest you post a video showing the issue and highlight
in it the problem.

**Comment by for-coursera** [comment]
@kovidgoyal 

Here's a video attached:

https://github.com/user-attachments/assets/70c6b65a-751a-4668-9c9c-47a27b256d4a

**Comment by kovidgoyal** [comment]
I can see it in your video but it does not reproduce for me with

```
kitty --config=NONE --hold -o 'map f1 kitten hints --type url --program "launch --type=background xdg-open"' sh -c 'ls -l; echo https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-type;'
```

Press F1

Then either press 1 or esc to cancel in neither case do I get a
flicker.

Make sure you are running up-to-date kitty. And try to reproduce with
empty or minimal kitty.conf

**Comment by kovidgoyal** [comment]
Yes, my cursor is on the last line and scrollback contains lines. I am
guessing your flicker is caused by the window being resized by your
window manager when your browser is launched. Prevent that from
happening and you will be fine.

**Comment by for-coursera** [comment]
@kovidgoyal, thanks again for your reply!

> I am guessing your flicker is caused by the window being resized by your
window manager when your browser is launched.

Just in case, it happens no matter what if kitty is fullscreen, maximized or just a regular window (with or without decorations). The browser window can be maximized or a regular window, too.

Also, just for the record, it doesn't always happen with the first try. Sometimes the first time I open a hint, no jump is observed. But if I then switch back to kitty and open a hint once again, it jumps.

> Prevent that from happening and you will be fine.

Could you provide any hints on how I can do this? Or any links maybe? It's just the first time I hear about such possibility... I'm running Openbox WM, and my setup has no specific settings for kitty or any windows.

Also, as I said, it doesn't happen with alacritty... I understand that their mechanism is different , I guess. But if your WM guess is true, then their terminal somehow doesn't suffer from it...

**Comment by kovidgoyal** [comment]
The only ways you can get a spontaneous scroll which is what it looks
like you are seeing is either the window being resized or a spurious
touchpad/wheel event being delivered. kitty will never scroll its window
contents on its own. You can run with --debug-input and
--debug-rendering to see the events kitty receives. As for how to
prevent the window being resized, that's dependent on your window
manager. I have never used openbox so cant help you with that.

And what does alacritty have to do with anything, it just so happens
that whatever input is causing the issue is either buffered or not
rendered fast enough causing it to be not noticeable.

Anyway I cant really help you without a way to reproduce.

**Comment by for-coursera** [comment]
@kovidgoyal 

And thanks once again :)

> You can run with --debug-input and --debug-rendering to see the events kitty receives.

I saved a log, could you take a look? I press F1 at ~7 sec: https://paste.rs/QwSeJ

> kitty will never scroll its window contents on its own. 

I don't think it's kitty per se but maybe some feedback it receives or something like that? In the log, you could notice my `xdg-open` reports back something like:

> Opening in existing browser session.
> [184035:184035:0100/000000.947372:ERROR:zygote_linux.cc(678)] write: Broken pipe (32)

I tried to replace `xdg-open` with a custom script ,which produces no output at all, but it didn't help, the flickering was still there...

Also, maybe your computer is just way faster, and therefore the jump is so microscopic that you simply do not notice it? :)

**Comment by for-coursera** [comment]
@kovidgoyal 

I examined it a bit further, and it is indeed some kind of feedback after `launch` execution.

If I skip filling the scroll back buffer, and issue `echo 'https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-type'` on the first line, then, after pressing F1 and 1, **I can spot `<nil>` flickering right beside the cursor line.**

Here are two frames from a video I just recorded (notice the cursor jumping one row below):

![a](https://github.com/user-attachments/assets/ec317436-e5ed-49f4-9a64-d50f90afbc85)
![b](https://github.com/user-attachments/assets/6b32dcd2-9c74-487a-8e0b-00bbf8d91e87)


That's why it flickers then the cursor in on the last line: because this `<nil>` needs a row to appear. Then it vanishes (covered by the kitty's overlay?), and everything looks like it was before, just my eye registers that "jump".

What do you think, what this `<nil>` thing is?

**Comment by for-coursera** [comment]
Also: I downloaded this old release v.0.26.5. And there's no this problem there, no flickering at all. Maybe because the feedback from launch goes to the process, that spawned this particular kitty instance?

Please, @kovidgoyal, could you look into this?

**Comment by kovidgoyal** [comment]
There is no connection to the current window. The way the hints kitten works is by opening an overlay window with the text from the current window. Once you select a match that match is sent to the kitty process which runs the specified program.

Since your command is launch --type=background whatever that is run in a separate background process. Incidentally you don't need launch. You can just use --program xdg-open  not that it should make any difference.

**Comment by for-coursera** [comment]
@kovidgoyal, 

And [that `<nil>` thing that does cause the flickering](https://github.com/kovidgoyal/kitty/issues/8096#issuecomment-2510980027), what do you think about it? And why it doesn't happen with 0.26.5?

**Comment by kovidgoyal** [comment]
no clue, you can always bisect to try to find a problematic commit,
though I dont see what could possibly lead to it and I cannot replicate
it.

**Comment by for-coursera** [comment]
> you can always bisect to try to find a problematic commit,

Well, I did find a release, that changed everything here, but you simply disregard it as a non-issue.

> I cannot replicate it.

It's not the point, though, isn't it? Under certain conditions **your software behaves wrong**. I brought you every evidence and even found a turning point. And you simply don't care because you don't care. Let's blindly blame my WM and whatnot instead.

**Comment by for-coursera** [comment]
> How exactly do you think I am supposed to fix your issue when I have no way to reproduce it? 

By knowing **your** code? A bit old-fashioned, I understand.

> Do you think I am your fucking servant? 

No. I think you just don't care.

This is certainly not the first time you shit on people here but I thought you would be at least interested in your own bugs. Well, I was wrong. If it works for you, others simply do not exist.

> Some people!!

Indeed.

**Comment by kovidgoyal** [comment]
On Mon, Dec 02, 2024 at 03:02:43AM -0800, for-coursera wrote:
> > How exactly do you think I am supposed to fix your issue when I have no way to reproduce it?
>
> By knowing **your** code? A bit old-fashioned, I understand.

ROFL. Sure I guess you restrict yourself to writing hello world
programs.

>
> > Do you think I am your fucking servant?
>
> No. I think you just don't care.

I definitely do not care about entitled assholes that demand service for
trivial issues that are specific to them.

>
> This is certainly not the first time you shit on people here but I thought you would be at least interested in your own bugs. Well, I was wrong. If it works for you, others simply do not exist.

Nope, if the bug reporter cant be bothered to do some actual work while
demanding free service, they definitely do not exist for me.

>
> > Some people!!
>
> Indeed.

Don't let the door hit you on the way out.
