### ISSUE TITLE
Feat: Option to hide_window_decorations but keep shadows

### ISSUE THREAD

**Issue by SamuelBorn** [kovidgoyal/kitty#8098]
**Is your feature request related to a problem? Please describe.**
I would like to disable window_decorations but keep window shadows.
Setting `hide_window_decorations yes` hides both the titlebar and window shadows.
This makes it sometimes hard to differentiate overlapping windows.

**Describe the solution you'd like**
An option like `hide_titlebar yes` that retains the shadows and just removes the titlebar with the close, maximize, minimize titlebar buttons.

**Additional context**
I am on GNOME 47 (Wayland) which is terrible with window decorations.
I am not entirely sure if this a problem with kitty or with GNOME that the shadows disappear when disabling window_decorations.

**Comment by kovidgoyal** [comment]
Not something I am interested in implementing but patches are welcome. I
have wasted enough of my life working around GNOME.
