### ISSUE TITLE
C-Alt-v not registered

### ISSUE THREAD

**Issue by nochiel** [kovidgoyal/kitty#81]
- `cat`
- Type `C-Alt-v` (typically bound to `scroll-other-window` in emacs)
- Expected: `^[^`
- Similarly for other `C-Alt-<key>` combinations.

**Comment by kovidgoyal** [comment]
Typing cat and C-A-v gets me no output on xterm either. And I dont see how C-A-<key> is supposed to work in general, since there are no single byte control codes for it to map to. If as you say it maps to ^[^ then how is it is distinguished from typing C-[ followed by Shift+6

**Comment by kovidgoyal** [comment]
And on libvte `C-A-v` outputs `^[` not `^[^`. Which is the same as typing `C-[`

As far as I know, it is, in general, impossible to use multi-modifier key combinations with terminal programs that dont implement the extended key handling protocol I invented for kitty: https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc#keyboard-handling

**Comment by nochiel** [comment]
> And on libvte C-A-v outputs ^[ not ^[^. Which is the same as typing C-[

I'm not certain that's the case. On libvte 2.91 (which was what I tested with), it does seem to be, as you said, equivalent to `C-[ S-6`. (Though, reading through the [libvte implementation](https://github.com/GNOME/vte/blob/master/src/keymap.cc#L941) , which I'm probably misunderstanding, seems to indicate that `C-M` and `C-S-M` are handled distinctly, yet from my rudimentary testing, the latter isn't handled in libvte.) 

In a virtual console, too, `C-A-v`, outputs ` ^[^`. Perhaps there's a quirk in my installation that I'm unaware of. I'll investigate further.

Still, I see your point.  The xterm documentation asserts that vte has [inconsistent support for modifier keys](http://invisible-island.net/xterm/xterm.faq.html#vte_widget). In future I'll test with both when testing kitty.

**Comment by kovidgoyal** [comment]
python 3.5 is five years old, and is being end-of-lifed in a few months.
I have had enough of writing uglier code to support it. And the
immediate motivation for dropping support is the use of type annotations
on variables which python 3.5 does not support. Look at the failing
tests on 3.5 from the previous commit.

**Comment by Luflosi** [comment]
This comment was meant to be in response to https://github.com/kovidgoyal/kitty/commit/81a58186c6fae2de7bb4d7c7a3dc1a418d2b3d03#commitcomment-37684741, cross-linking for future reference.
@kovidgoyal Whatever you're using to write responses doesn't work correctly with comments on commits.

**Comment by kovidgoyal** [comment]
@Luflosi: Yeah I need to updated my responder script to filter out
commit emails.
