### ISSUE TITLE
Rectangular selection not working.

### ISSUE THREAD

**Issue by josswright** [kovidgoyal/kitty#810]
Using kitty 0.11.3-2 installed via pacman on Arch Linux.

Rectangular selection doesn't seem to work for me. I have:

```rectangle_select_modifiers ctrl+alt```

in my `kitty.conf`, but it doesn't work either in a standard zsh or when running any applications. I've also tried holding down shift as well, as I noticed that that had been added to allow override of mouse grabbing, but that also doesn't work.

**Comment by maximbaz** [comment]
Strange, works for me using the same package, with or without custom configuration.

**Comment by kovidgoyal** [comment]
Don't see anything in the config that looks suspicious and if it happens with --config NONE then something else is going on. You can andd some debugging to mouse.c to see what is going on see the update_drag() function.

**Comment by josswright** [comment]
My fault! No issue here.

I use an external keyboard on my laptop with reprogrammable keymap (Vortex Pok3r) and the left Alt key had somehow been mapped to Meta without me noticing. I only realised when I tried my laptop's internal keyboard on a whim.

Apologies!
