### ISSUE TITLE
vim/nvim diff is slow when using kitty

### ISSUE THREAD

**Issue by MayDomine** [kovidgoyal/kitty#8102]
**Describe the bug**
vim/nvim diff is slow when using kitty
**To Reproduce**
1. just install any vim/nvim release and any kitty release
2. then create a nvim/vim diff buffer
3. try to scroll, it would be very slow 

**Environment details**
```
Macos Sonoma 14.3.1 (23D60)
```

**Comment by kovidgoyal** [comment]
Then you should report it to vim/nvim diff's maintainers.
If you want fast and pretty and functional diff use
https://sw.kovidgoyal.net/kitty/kittens/diff/

**Comment by MayDomine** [comment]
It is so weird that I did not meet  same thing with any other terminal.
Could you please tell me any possible reason?

**Comment by kovidgoyal** [comment]
No clue, presumably that software is doing something different based on
the value of TERM. Use a decent benchmarking tool and you will find that
kitty is actually faster than all other terminals.

**Comment by MayDomine** [comment]
No, this is unrelated with $TERM, I tried TMUX or ssh remote to do something like diff, which disabled xterm-kitty, it is still so slow in scrolling in a vim/nvim diff. I  do not understand why. Anything else works perfect with kitty and it  is more efficient and faster than other terminal like weztem.

**Comment by MayDomine** [comment]
But kitty is indeed very slow in scrolling in a nvim/vim diff on my system

**Comment by MayDomine** [comment]
I tried kitty diff, it fails to open ....
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/9842599b-2182-4845-ba11-e786d0674a39">

**Comment by kovidgoyal** [comment]
You'd have to ask the developers of that software and TERM here is a
generic expression modern programs detect terminals using a mix of
escape codes, heuristics, TERM, etc.

**Comment by MayDomine** [comment]
Just found this out, use 
```
font_family      JetBrainsMono Nerd Font Mono
```
That's why I get here.
