### ISSUE TITLE
Kitty grabs global shortcuts alt-letter and alt-shift-letter on Sequoia

### ISSUE THREAD

**Issue by sschuldenzucker** [kovidgoyal/kitty#8108]
**Describe the bug**
On MacOS Sequoia, when you configure an application (tested with aerospace and amethyst) that's supposed to grab keyboard shortcuts like alt-<letter> or alt-shift-<letter> globally, this doesn't work when a kitty window is focused. Instead, the key is grabbed by kitty (produces an accented letter).

I haven't seen this happen on Sonoma.

I'm not super sure if this is a bug in kitty or just some kind of funky interaction between kitty and whatever app is grabbing global shortcuts, but it only happens with kitty, so there seems to be *some* special thing that kitty does here. Happy to do more targeted tests.

**To Reproduce**
Steps to reproduce the behavior (at the example of aerospace; this should happen in any other app that configures global keyboard shortcuts, though):

0. You have to be on MacOS Sequoia. This only happened when I upgraded from Sonoma to Sequoia.

1. Configure Aerospace to do something on `alt-shift-` or `alt-`, for example, in `~/.config/aerospace/aerospace.toml`:

```
[mode.main.binding]
alt-shift-k = 'focus up'
alt-j = 'focus down'
```

2. Start aerospace / reload config.

3. Open a kitty window and a window of some other app (e.g., Safari) and arrange vertically. Then try to move between windows using `alt-shift-k` and `alt-j` (where alt = option).

*Expected behavior:* The keys move focus vertically between the windows.

*Actual behavior:* They keys move focus vertically between the windows if the other app is focused but *not* if the kitty window is focused. If the kitty window is focused, an accented letter is output to the shell instead.

This does not happen for other modifier combos, e.g., `ctrl-` or `ctrl-alt-` or `ctrl-shift-`.

**Environment details**
```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Darwin srs.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		15.1.1 BuildVersion:		24B91
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: True
Fonts:
  medium: Menlo-Regular: /System/Library/Fonts/Menlo.ttc
          Features: ()
    bold: Menlo-Bold: /System/Library/Fonts/Menlo.ttc
          Features: ()
  italic: Menlo-Italic: /System/Library/Fonts/Menlo.ttc
          Features: ()
      bi: Menlo-BoldItalic: /System/Library/Fonts/Menlo.ttc
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish

Config options different from defaults:
Changed shortcuts:
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/Users/steffen/.local/bin:/Users/steffen/.asdf/shims:/Users/steffen/.asdf/bin:/Users/steffen/.ghcup/bin:/Users/steffen/.cabal/bin:/Users/steffen/.foundry/bin:/Users/steffen/.nimble/bin:/Users/steffen/.cargo/bin:/usr/local/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/opt/postgresql@16/bin/:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/podman/bin:/Applications/quarto/bin:/Library/TeX/texbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Applications/iTerm.app/Contents/Resources/utilities
	LANG                                en_US.UTF-8
	EDITOR                              hx
	SHELL                               /opt/homebrew/bin/fish
	USER                                steffen
	LC_TERMINAL_VERSION                 3.5.10
	LC_TERMINAL                         iTerm2

```

**Additional context**

Tested with `kitty --config NONE`, issue persists.

Aerospace version I used for testing:
```
aerospace CLI client version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
AeroSpace.app server version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
```

**Comment by kovidgoyal** [comment]
You probably turned on secure text input turn it off again.

**Comment by sschuldenzucker** [comment]
Man you're a wizard! Of course you're absolutely right. This also seems to be persistent across kitty app restarts, right?

For the record, I don't remember having turned this on; it might be possible that the Sequoia upgrade did this somehow. (or I actually did it by accident ;) )

**Comment by linkarzu** [comment]
You have no idea how much I suffered because of this. I coincidentally had flashed my keyboard firmware from 40 to 36 keys and I thought it was keyboard related, then I thought it was skhd (hotkey daemon) related. But now, at some point I pressed cmd+option+s and all went to hell

**Comment by kovidgoyal** [comment]
On Sun, May 31, 2026 at 05:30:14PM -0700, linkarzu wrote:
> linkarzu left a comment (kovidgoyal/kitty#8108)
>
> You have no idea how much I suffered because of this. I coincidentally had flashed my keyboard firmware from 40 to 36 keys and I thought it was keyboard related, then I thought it was skhd (hotkey daemon) related. But now, at some point I pressed cmd+option+s and all went to hell


See if this helps: https://github.com/kovidgoyal/kitty/commit/f388fdabdc22bf81c35e9cba7509282c8af4489a

**Comment by linkarzu** [comment]
> On Sun, May 31, 2026 at 05:30:14PM -0700, linkarzu wrote:
>  linkarzu left a comment ([kovidgoyal/kitty#8108](https://github.com/kovidgoyal/kitty/issues/8108))
> 
>  You have no idea how much I suffered because of this. I coincidentally had flashed my keyboard firmware from 40 to 36 keys and I thought it was keyboard related, then I thought it was skhd (hotkey daemon) related. But now, at some point I pressed cmd+option+s and all went to hell
> See if this helps: [f388fda](https://github.com/kovidgoyal/kitty/commit/f388fdabdc22bf81c35e9cba7509282c8af4489a)

I see what you mean, that does indeed seem helpful to someone using the default macOS menubar

<img width="2560" height="860" alt="Image" src="https://github.com/user-attachments/assets/ce2978f3-3ee7-437e-9b14-6edd1fca18fa" />

But as usual, I like complicating myself and I hide the default macOS menubar and use a custom menubar called sketchybar, and there's other custom menu bars, so it doesn't make sense to try to support them all.

<img width="2560" height="860" alt="Image" src="https://github.com/user-attachments/assets/f8ced1ab-efc6-4f01-a935-ae86f04c024b" />

Just an idea that came to mind, it would be cool if next to the tabs there could be a small area destined for "notifications" where a lock could be shown, or people can put whatever custom text they want in there, like the time, or when an LLM running in a tab is done and waiting for prompt, or whatever

<img width="2560" height="720" alt="Image" src="https://github.com/user-attachments/assets/1cf0d77a-45b3-450c-94db-3dc52e04cd11" />

Similar to this small banner I had in tmux, back when I used it, before you talked me out of it 😂

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/d4569917-59d4-42b8-9038-2eb55691c088" />


Again, this is just an idea that could probably be useful? But not sure if you think it would benefit people or not. You know I'd create a video out of it and show it off to people, so other terminals get jealous and implement it in the future too 🙊

Again, thanks for all you do Kovid, really much appreciated!!

**Comment by kovidgoyal** [comment]
You can do that already with a bit of work by customizing how the tab bar is drawn. You will find examples of this in the discussion about custom tab bar styles. More generally using the tab bar for this has the same issue you have with the global menubar many users dont use tabs and hence dont ever see the tab bar.

**Comment by linkarzu** [comment]
> You can do that already with a bit of work by customizing how the tab bar is drawn. You will find examples of this in the discussion about custom tab bar styles. More generally using the tab bar for this has the same issue you have with the global menubar many users dont use tabs and hence dont ever see the tab bar.

Thad exciting, I'll try to figure it out some other day!
