### ISSUE TITLE
Add ability to map Window>Move & Resize shortcuts

### ISSUE THREAD

**Issue by Coqueiro** [kovidgoyal/kitty#8112]
**Problem description**
Hello there! I currently enjoy having the following config in my `kitty.conf`:
```
map ctrl+page_down              next_tab
map ctrl+page_up                previous_tab
```
That said, in my keyboard the way to access `ctrl+page_down` for example is by pressing ctrl + fn/globe_key + down arrow, which also triggers the window menu action Window>Move & Resize>Bottom & Top, which seems to be taking precedence, not enabling me to change window tabs as I intend.

**Alternatives of solution that I thought of**
Possible solutions I can think of:
- Enabling remapping of those actions
- Change precedence order (actions mapped in the kitty.conf takes precedence)
- Enabling disabling Move & Resize shortcuts (I currently manage windows for all apps using "Rectangle", so I don't intend on using kitty's native Move & Resize, don't know if it's the case for many users)

Thanks for the attention!

**Comment by kovidgoyal** [comment]
There is nothing kitty can do about global shortcuts you define outside
of it. You need to settle on global shortcuts that dont conflict with
ones you want to use in the applications you like to use.
