### ISSUE TITLE
chance icon in linux

### ISSUE THREAD

**Issue by rkochar** [kovidgoyal/kitty#8116]
**Describe the bug**
I would like to change the icon of Kitty on Linux.
Expected behavior: new icon.
Current behavior: default icon

**To Reproduce**

I see the [guide here](https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon) saying to place it at `~/.config/kitty`. This does not change the logo.
I have also replaced `kitty.png` and `kitty-128.png` at `/usr/lib/kitty/logo` [see here](https://github.com/k0nserv/kitty-icon/issues/10) but that too does not work.

**Environment details**
```
Terminal: kitty 0.37.0
OS: Manjaro Linux x86_64
Kernel: Linux 6.1.119-1-MANJARO
DE: GNOME 47.2
WM: Mutter (X11)
```

I love kitty, thank you.

**Comment by kovidgoyal** [comment]
You will need to ask how to change application icons in whatever distro
you are using.
