### ISSUE TITLE
Support oklch colors

### ISSUE THREAD

**Issue by jrood** [kovidgoyal/kitty#8117]
**Is your feature request related to a problem? Please describe.**
It would be sweet to use [oklch](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch) colors. I want to use vibrant colors in the P3 color space that aren't available in the rgb space.

**Describe the solution you'd like**
Ability to specify an oklch color, e.g.
```
foreground oklch(73.32% 0.2189 49.06)
```

**Describe alternatives you've considered**
I don't think there's an alternate way to achieve this.

**Additional context**
[oklch.com](https://oklch.com/) is a useful tool for visualizing oklch colors and which color spaces they fall into. Most Apple devices support P3.

**Comment by kovidgoyal** [comment]
I dont know what you mean by not available in the rgb colorspace. Any
color is representable in any color space, it just requires more bits of
precision. I'm afraid I am not going to add more bits of precision to
colors in kitty, it's a performance hit that's not justified by the
returns IMO. And note that you can control the display colorspace kitty
uses via the macos_colorspace option in kitty.conf

**Comment by jrood** [comment]
> Any color is representable in any color space, it just requires more bits of
precision.

This is actually not the case. You may be thinking of color bit depth (which has to do with precision), but color space is a different concept. Colors in the P3 space can have greater saturation than colors in the sRGB space. If you view [this example](https://oklch.com/#70,0.2432,40.96,100) on an Apple device, you'll see in the upper left that it shows the P3 example which is a very vibrant orange, and it shows the sRGB fallback which is much less vibrant because there is not a way to represent that color in the sRGB space.

**Comment by jrood** [comment]
Ah, but I didn't realize that using `macos_colorspace displayp3` would scale values to extend into that space. In that case, I can achieve the colors I'm looking for using that option. Thanks!
