### ISSUE TITLE
EINVAL:[Errno 45] Operation not supported: '/home/sa' when trying to kitten transfer

### ISSUE THREAD

**Issue by epicwhale** [kovidgoyal/kitty#8118]
**Describe the bug**
I get a EINVAL:[Errno 45] Operation not supported: when trying to kitten transfer from within an ssh session. I ssh'd using kitten ssh.

**To Reproduce**
1. kitten ssh  into a server
2. kitten transfer foo.txt ~/Download
3. See error

```
Scanning files…
Found 1 files and directories, requesting transfer permission…
Permission granted for this transfer
✘ /home/sa/code/foo.txt                                        4.1MB @ 32MB/s 🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋🬋   <1 sec
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
File data transfer has not yet started
Transfer of 1 out of 1 files failed
/home/sa/code/foo.txt
  EINVAL:[Errno 45] Operation not supported: '/home/sa'

```

**Environment details**
```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Darwin l 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6031 arm64
ProductName:		macOS ProductVersion:		15.1.1 BuildVersion:		24B91
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: True
Fonts:
  medium: MesloLGS-NF-Regular: /Users/3/Library/Fonts/MesloLGS NF Regular.ttf
          Features: ()
    bold: MesloLGS-NF-Bold: /Users/33/Library/Fonts/MesloLGS NF Bold.ttf
          Features: ()
  italic: MesloLGS-NF-Italic: /Users/33/Library/Fonts/MesloLGS NF Italic.ttf
          Features: ()
      bi: MesloLGS-NF-Bold-Italic: /Users/33/Library/Fonts/MesloLGS NF Bold Italic.ttf
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/33/.config/kitty/kitty.conf

Config options different from defaults:
font_family family="MesloLGS NF"
font_size   14.0
Changed shortcuts:
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_GB.UTF-8
	SHELL                               /bin/zsh
	USER                                33

```

**Comment by kovidgoyal** [comment]
That's because Apple thinks allowing non-Apple programs to write into ~/Download will terminally endanger their clueless users. You need to give kitty permission to access and modify !/Download or transfer elsewhere.

**Comment by kovidgoyal** [comment]
No idea, I am not a macOS user. IIRC there are a bunch of "special"
folders on macOS that the OS restricts access too and they need to be
granted to individual applications, though my memory is quite hazy about
that.

**Comment by epicwhale** [comment]
thanks for trying to help debug! As per this https://support.apple.com/en-gb/guide/mac-help/mchld5a35146/mac (it looks like ive covered the ground). Apps like Raycast / Telegram are having no trouble writing into the same folder.

Leaving a screenshot here for anyone facing the same issue on a mac to validate.. 

![image](https://github.com/user-attachments/assets/220a6125-9ea8-4dd5-b85b-6b737580ead2)

**Comment by kovidgoyal** [comment]
Just to confirm this is only in Downloads right? Other destinations work?

**Comment by epicwhale** [comment]
Nope, all destinations are failing. Not just Downloads. Don't think this is a folder specific problem

**Comment by kovidgoyal** [comment]
OK then its not that issue, I will take a look at it next time I am on
my mac machine.

**Comment by kovidgoyal** [comment]
Ah never mind, looking at your reproducer command more closely I see you
are missing the trailing slash. Your command is trying to copy foo.txt
to ~/Downloads that is it is trying to replace a folder with a file, add
a trailing slash to ~/Downloads/ and you will be fine. The reason this
is needed is because the transfer kitten has no way to know that
~/Downloads is a folder on the remote machine.

**Comment by epicwhale** [comment]
hmm, the trailing slash did not seem to help by itself (see - 1 below)... but I think the culprit seems to be the `~/` prefix to Downloads/ which does not seem to resolve to the home directory. I did a full path replacement `kitten transfer foo.txt /Users/foo/Downloads/` and it seems to work now!


1) Only trailing slash - Fails
```
╰─ kitten transfer foo.txt ~/Downloads/                                   ─╯
Scanning files…
Found 1 files and directories, requesting transfer permission…
Permission granted for this transfer
✘ /home/sa/code/foo.txt                               0B @ 0B/s   <1 sec
─────────────────────────────────────────────────────────────────────────────
File data transfer has not yet started
Transfer of 1 out of 1 files failed
/home/sa/code/foo.txt
  EINVAL:[Errno 45] Operation not supported: '/home/sa'
```

2) `kitten transfer foo.txt /Users/foo/Downloads/`
```
kitten transfer foo.txt /Users/foo/Downloads/                       ─╯
Scanning files…
Found 1 files and directories, requesting transfer permission…
Permission granted for this transfer
✔ /home/sa/code/foo.txt                               0B @ 0B/s   <1 sec
─────────────────────────────────────────────────────────────────────────────
```

Would be convenient to be able to use the `~/` to refer to local paths

Thanks for investigating this!

**Comment by epicwhale** [comment]
aha, I now  got that to work :)

`kitten transfer log_1.txt \~/Downloads/` ✅

Thanks mate!
