### ISSUE TITLE
MacOS: trying to do multicast networking on macos in Sequoia fails.

### ISSUE THREAD

**Issue by spott** [kovidgoyal/kitty#8120]
**Describe the bug**
Using https://github.com/SoCo/SoCo or https://github.com/avantrec/soco-cli silently fails in kitty since I've updated to Sequoia.  These work in Macos terminal.  I have given Kitty all the permissions I can find in privacy and security in settings.

I *believe* it is related to the "multicast entitlement" (see here: https://developer.apple.com/forums/thread/663875), which needs to be requested by Kitty in order for me to grant it.

**To Reproduce**

have a sonos system and install and run soco-cli:

```
pip install soco-cli
sonos-discover -t 256 -n 1.0 -m 24
```

In kitty it silently fails, in terminal it succeeds.

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. ```

neither of these worked for me...

but my version is: 0.31.0, though I don't believe this has been fixed since then (the entitlements here: https://github.com/kovidgoyal/kitty/blob/9d48fa91262e1df7280dbee91c6c0120d556feb0/bypy/macos/__main__.py#L120 don't mention local network access).

**Comment by kovidgoyal** [comment]
Sigh, Apple. Adding com.apple.developer.networking.multicast to the
entitlements causes the OS to kill any kitty binary on startup.

And using codesign -d --entitlements - --xml /System/Applications/Utilities/Terminal.app/

we see that it does not have that entitlement.
And according to: https://forums.developer.apple.com/forums/thread/663271
this entitlement is not used on macOS.


I'm afraid I dont have the time/interest to go spelunking any further to
try to find out how to workaround apple's latest bit of brain damage,
but if you can figure it out I will be happy to accept a PR or a
pointer.
