### ISSUE TITLE
Mouse override in SSH session

### ISSUE THREAD

**Issue by kylechui** [kovidgoyal/kitty#8121]
Many thanks for your work on this application! Apologies if this is somehow possible, and I wasn't able to figure it out.

**Is your feature request related to a problem? Please describe.**
I would like to be able to define a custom handler for clicking on terminal hyperlinks _in an SSH session_. As it is right now, even if I define custom click handlers in `open-actions.conf`, performing `ctrl+shift+left` opens the [remote file pop-up](https://sw.kovidgoyal.net/kitty/kittens/remote_file/), instead of using my custom logic.

**Describe the solution you'd like**
I think it would be nice to have a way to disable the remote file popup and fallback on `open-actions.conf`, or a way to detect "in SSH session" inside `open-actions.conf`. That way I can run custom logic if I click on a terminal hyperlink in a SSH session, instead of seeing the remote-file pop-up.

**Describe alternatives you've considered**
I've tried briefly to write a custom kitten to do this, but it seems like the terminal hyperlinks detection is built-in to the application itself, not a part of the remote file kitten, so I wasn't quite sure how to proceed there. Right now I am extending the hints kitten using `--type=hyperlink` with `launch --type=background /path/to/foo.sh`, which works well, but I would like to be able to use the mouse for this too.

```sh
# The hinted hyperlink seems to be passed in via STDIN
map ctrl+g kitten hints --type=hyperlink --program "launch --type=background /path/to/foo.sh"
```

**Additional context**
My `open-actions.conf` works very well for clicking on _local_ hyperlinks, just not when I am in an SSH session:

```
protocol file
mime text/html
action launch --type=background -- open ${FILE_PATH}
```

**Comment by kovidgoyal** [comment]
Use mouse_map in kitty.conf map the click to your custom kitten. In your
custom kitten check the hostname of the url under the mouse and handle
if remote or call kitty's native handling functions if not.

**Comment by kylechui** [comment]
Hi, I've been able to use `get_mouse_data_for_window` in order to obtain the cursor's location when the custom kitten is called, but I'm unsure how to go from there to parsing the URL hostname (or getting the link from underneath the cursor in general). I also have figured out the latter half as `w.mouse_click_url()`. Any pointers for what functions to call would be much appreciated!

**Comment by kovidgoyal** [comment]
On Sun, Dec 15, 2024 at 12:05:06AM -0800, Kyle Chui wrote:
> Hi, I've been able to use `get_mouse_data_for_window` in order to obtain the cursor's location when the custom kitten is called, but I'm unsure how to go from there to parsing the URL hostname (or getting the link from underneath the cursor in general). I also have figured out the latter half as `w.mouse_click_url()`. Any pointers for what functions to call would be much appreciated!

There's no builtin function for this (it happens in native code for
performance), but for the common use case simply do:

line = self.screen.line(current_line_under_mouse)
text_in_line = str(line)

Then you can extract the URL in the text and do whatever you like with
it. If instead you want to click a hyperlink:

ids = line.hyperlink_ids()
hyperlink_id = ids[current_cell_x_under_mouse]
url = screen.hyperlink_for_id(hyperlink_id)

**Comment by kylechui** [comment]
Ahh thank you so much! I really appreciate it; hope you have a great rest of your day
