### ISSUE TITLE
`--hold` option does not honor `--cwd` option

### ISSUE THREAD

**Issue by zachdaniel** [kovidgoyal/kitty#8122]
**Describe the bug**

When I execute the following `kitty @ launch --type os-window --cwd ~/dev --hold /bin/zsh -c "/opt/homebrew/bin/nvim"`,
and then I exit vim, I am left at a shell that is at `~` instead of `~/dev`.

This *seems* incorrect to me. This could 100% be intentional, or due to some factor I don't understand, but it's a bit counterintuitive to me and I haven't figured out a way around it yet.

**To Reproduce**

1. run an equivalent to the command listed above:

```
kitty @ launch --type os-window --cwd ~/dev --hold /bin/zsh -c "/opt/homebrew/bin/nvim"
```

2. exit vim

3. See that you are not at `--cwd`

**Environment details**
```
kitty 0.37.0 (2531c31d02) created by Kovid Goyal
Darwin Zachs-MacBook-Pro-2.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 19:01:59 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		15.2 BuildVersion:		24C101
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: True
Fonts:
  medium: JetBrainsMono-Regular: /Users/zachdaniel/Library/Fonts/JetBrainsMono-Regular.ttf
          Features: ()
    bold: JetBrainsMono-SemiBold: /Users/zachdaniel/Library/Fonts/JetBrainsMono-SemiBold.ttf
          Features: ()
  italic: JetBrainsMono-Italic: /Users/zachdaniel/Library/Fonts/JetBrainsMono-Italic.ttf
          Features: ()
      bi: JetBrainsMono-SemiBoldItalic: /Users/zachdaniel/Library/Fonts/JetBrainsMono-SemiBoldItalic.ttf
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/zachdaniel/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    yes
background_blur         14
background_image        /Users/zachdaniel/.dotfiles/images/gradient-fire-ice.png
background_image_layout scaled
background_opacity      0.6
background_tint         0.88
enabled_layouts         ['vertical', 'stack']
font_family             family="JetBrains Mono"
font_size               14.0
hide_window_decorations 2
window_border_width     (1.0, 'pt')
window_margin_width     FloatEdges(left=8.0, top=8.0, right=8.0, bottom=8.0)
Added shortcuts:
	cmd+p →  remote_control_script /Users/zachdaniel/.dotfiles/priv_scripts/project-hot-key
Changed shortcuts:
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website
Colors:
	active_border_color     #44ffff   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                zachdaniel
```

**Comment by kovidgoyal** [comment]
Does not replicate for me, steps I tried:

1) kitty -o allow_remote_control=y
2) Run: kitten @ launch --type os-window --cwd /tmp --hold sh -c 'echo `pwd`'
3) I see the output /tmp and am left at prompt at /tmp as expected

I am guessing you have something in your shell rc files that causes the
shell to cd to your home directory.

**Comment by zachdaniel** [comment]
I see the same using `sh`, but not using `zsh`, will investigate, thanks 🙇

**Comment by zachdaniel** [comment]
Running `zsh` from any directory doesn't cd into the home directory, though, so if its something wrong with my setup it is something other than just having some kind of `cd ~` in my `~/.zshrc` I imagine.

**Comment by zachdaniel** [comment]
Also when I run `zsh` like so to ignore any of my custom files:

```
kitten @ launch --type os-window --cwd /tmp --hold /bin/zsh --no-rcs -dfc 'echo pwd'
```
it still doesn't behave the same as `sh`. So perhaps the problem is with zsh specifically in some way?

**Comment by zachdaniel** [comment]
Alright, well, it seems that I'm using the zsh that comes installed on my Mac, or was installed in some other way. Installing `zsh` via home-brew and updating the executable to `/opt/homebrew/bin/zsh` and now it behaves the same as bash. 🤷🏻‍♂️

**Comment by kovidgoyal** [comment]
The command you are running is irrelevant. --hold works by running your
shell after the specified command completes, via the run-shell kitten.
Which will always source your rc files.

**Comment by zachdaniel** [comment]
I understand what you're saying, but running these commands back to back, confirming that they are using the same rc files etc.

```
➜  ~ kitten @ launch --type os-window --cwd /tmp --hold /bin/zsh --no-rcs -dfc 'echo pwd'
2
➜  ~ kitten @ launch --type os-window --cwd /tmp --hold /opt/homebrew/bin/zsh --no-rcs -dfc 'echo pwd'
3
```

produces a different result.

**Comment by zachdaniel** [comment]
The corresponding window for each is left at a different directory.

**Comment by zachdaniel** [comment]
I'm positive it's something stupid I'm doing, so I appreciate the quick response. Ultimately I have what I wanted working working now also, and maybe this will help someone else down the road doing the same stupid thing I was doing 😆

**Comment by kovidgoyal** [comment]
On Sat, Dec 14, 2024 at 10:16:00PM -0800, Zach Daniel wrote:
> I understand what you're saying, but running these commands back to back, confirming that they are using the same rc files etc.
>
> ```
> ➜  ~ kitten @ launch --type os-window --cwd /tmp --hold /bin/zsh --no-rcs -dfc 'echo pwd'
> 2
> ➜  ~ kitten @ launch --type os-window --cwd /tmp --hold /opt/homebrew/bin/zsh --no-rcs -dfc 'echo pwd'
> 3
> ```
>
> produces a different result.

Then, that will be because of something the shells involved are doing.
The run-shell kitten very simply executes the specified command, and
when it completes runs your configured shell. Relevant code in
run-shell/main.go

**Comment by Ottigan** [comment]
Just to pitch in, I have the same exact issue with `zsh`.
