### ISSUE TITLE
No such file or directory: '-M'

### ISSUE THREAD

**Issue by FrancescoMagliocco** [kovidgoyal/kitty#813]
It's been a few months since I last updated **Kitty**, so I may have missed something big in updating such as a new dependency or something.  I also forget how I use to compile and install **Kitty**, I'm pretty sure I use to do this: `sudo python3 setup.py --prefix=/usr linux-package` which is what I am doing now as well, and this is the error that I am getting.

```
make docs
make FAIL_WARN= -C docs man
make[1]: Entering directory '/home/cmptr/.src/frks/kitty/docs'
python3 .. +launch  -M man "." "_build" -T  
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "../__main__.py", line 104, in <module>
    main()
  File "../__main__.py", line 95, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "../__main__.py", line 56, in namespaced
    func(args[1:])
  File "../__main__.py", line 39, in launch
    runpy.run_path(args[1], run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.6/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '-M'
make[1]: *** [Makefile:20: man] Error 1
make[1]: Leaving directory '/home/cmptr/.src/frks/kitty/docs'
make: *** [Makefile:37: man] Error 2
```

I am using the latest version hosted here on Git.  I also tried `sudo make clean` followed by re-compiling, with no success.

- [ ] Compilation Failure

**Comment by kovidgoyal** [comment]
If you want to run linux-package, you need to have sphinx-build installed. If all you want to do is run kitty from source, use

make

and

python3 .

to run kitty. No need for sphinx. See https://sw.kovidgoyal.net/kitty/build.html
