### ISSUE TITLE
Problem defining conditional mapping

### ISSUE THREAD

**Issue by jrmd54** [kovidgoyal/kitty#8139]
Hello,

I am trying to add conditional mappings to my kitty.conf file, by following the associated documentation ([link](https://sw.kovidgoyal.net/kitty/mapping/#conditional-mappings-depending-on-the-state-of-the-focused-window)).

I have an empty .bashrc file and my .vimrc and kitty.conf contains only the following lines:

.vimrc:
```
let &t_ti = &t_ti . "\\033]1337;SetUserVar=in_editor=MQo\\007"
let &t_te = &t_te . "\\033]1337;SetUserVar=in_editor\\007"
```

kitty.conf:
```
map --when-focus-on title:TEST a paste_from_clipboard
map --when-focus-on var:in_vim_editor a paste_from_clipboard
```

The first map (focus-on title) works as expected, if the title of the window is TEST then pressing 'a' pastes the content of the clipboard.

However the second map (focus-on var), when in vim, does not seem to have any effect: pressing a simply enters insert mode or type a depending of the current vim mode.

Am i doing something wrong?
Exiting vim also prints '\033]1337;SetUserVar=in_editor\007' on the terminal but i think this is expected?

My Kitty version is 0.38.0, vim version is 9.0, on Ubuntu 23.10 mantic.
Running : set keyprotocol in vim outputs:
`keyprotocol=kitty:kitty,foot:kitty,wezterm:kitty,xterm:mok2`

Thank you very much

**Comment by kovidgoyal** [comment]
Looks correct to me, and works fine for me with vim 9.1

```sh
echo 'let &t_ti = &t_ti . "\033]1337;SetUserVar=in_editor=MQo\007"' > /tmp/vimrc; kitty -o 'map --when-focus-on var:in_editor f1 new_os_window' vim -u /tmp/vimrc
```

Pressing f1 opens a new os window as expected. Pressing f1 in the new os
window has no effect as expected.

It should not be printed to the terminal, that indicates its not being
escaped properly by vim most likely.

**Comment by jrmd54** [comment]
You are right, i have to remove the double \\s in the vim config
With
```
let &t_ti = &t_ti . "\033]1337;SetUserVar=in_editor=MQo\007"
let &t_te = &t_te . "\033]1337;SetUserVar=in_editor\007"
```
it works like a charm, thank you.
