### ISSUE TITLE
Launching kitty results in no interface for org freedesktop portal

### ISSUE THREAD

**Issue by mostafatouny** [kovidgoyal/kitty#8141]
**Describe the bug**
launching kitty yields `[0.352] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop`

**To Reproduce**
launch kitty

**Screenshots**

![Screenshot_2024-12-20_23-34-40](https://github.com/user-attachments/assets/eed6f6be-fd7c-4395-90f2-17614d22a605)

**Environment details**
```
kitty 0.37.0 created by Kovid Goyal
Linux touny-lenovo 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 x86_64
EndeavourOS Linux 6.12.4-arch1-1 (/dev/tty)

DISTRIB_ID="EndeavourOS"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME="rolling"
Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 24.3.1-arch1.3' Detected version: 4.6
Frozen: False
Fonts:
  medium: JetBrainsMonoNF-Regular: /home/touny/.local/share/fonts/JetBrainsMono/JetBrainsMonoNerdFont-Regular.ttf:0
          Features: ()
    bold: JetBrainsMonoNF-SemiBold: /home/touny/.local/share/fonts/JetBrainsMono/JetBrainsMonoNerdFont-SemiBold.ttf:0
          Features: ()
  italic: JetBrainsMonoNF-Italic: /home/touny/.local/share/fonts/JetBrainsMono/JetBrainsMonoNerdFont-Italic.ttf:0
          Features: ()
      bi: JetBrainsMonoNF-SemiBoldItalic: /home/touny/.local/share/fonts/JetBrainsMono/JetBrainsMonoNerdFont-SemiBoldItalic.ttf:0
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/touny/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.93
enable_audio_bell  False
font_family        JetBrainsMonoNerdFont
font_size          14.0
Changed shortcuts:
	kitty_mod+t →  launch --cwd=current --type=os-window

Important environment variables seen by the kitty process:
	PATH                                /home/touny/.opam/default/bin:/home/touny/.juliaup/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              nano
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                touny
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_ADDRESS                          en_US.UTF-8
	LC_NAME                             en_US.UTF-8
	LC_MONETARY                         en_US.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/touny
	LC_PAPER                            en_US.UTF-8
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   en_US.UTF-8
	LC_TELEPHONE                        en_US.UTF-8
	LC_MEASUREMENT                      en_US.UTF-8
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_US.UTF-8
	LC_NUMERIC                          en_US.UTF-8
```

![Screenshot_2024-12-20_23-40-27](https://github.com/user-attachments/assets/74153af3-f0bb-49fd-b5e3-da96e5cc6945)

![Screenshot_2024-12-20_23-36-29](https://github.com/user-attachments/assets/cb43de79-6395-4155-b021-be37b65d0704)

xorg logs in `/var/log/Xorg.0.log`
[Xorg.0.log](https://github.com/user-attachments/files/18215702/Xorg.0.log)

**Additional context**
Try to reproduce the problem with `kitty --config NONE`.
Same problem.

**Comment by kovidgoyal** [comment]
So install a portal or ignore the message if you dont want to install
one.

**Comment by kovidgoyal** [comment]
Its not a fail its a message.

**Comment by ljkenny** [comment]
```
[0.421] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod]
No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

`failed with error` looks like a fail.

This is the only "message" I get from Kitty.  Why now and why is it necessary / acceptable?

This is a regression with respect to UX.

**Comment by JustinWayland** [comment]
@ljkenny You have forgotten to install an appropriate backend for the xdg-desktop-portal, which Kitty needs to function.  You can fix this by installing ```xdg-desktop-portal-gtk```.

**Comment by mostafatouny** [comment]
> [@ljkenny](https://github.com/ljkenny) I figured out what your problem is. I had this pop up too, but on dwl.
> 
> You forgot to install an appropriate backend for the xdg-desktop-portal, which Kitty needs to function. You can fix this by installing `xdg-desktop-portal-gtk`.

I have the same problem after installing `xdg-desktop-portal-gtk`.

**Comment by JustinWayland** [comment]
That message is telling you that it can't find any settings through the desktop portal.  The solution is going to be dependent on DE or WM you are running in.

You should consult [this Arch Wiki page](https://wiki.archlinux.org/title/XDG_Desktop_Portal) to find the appropriate desktop portal backend to install.  GTK *should* have worked, as its generic, but again, the Arch Wiki page should guide you towards what to install.

I unfortunately can not help you anymore, but that Arch Wiki page should help you.
