### ISSUE TITLE
Everytime I wakup from hiberation, when I switch to already opened kitty session, my whole system will freeze for over 10s

### ISSUE THREAD

**Issue by c02y** [kovidgoyal/kitty#8142]
**Describe the bug**

I use i3wm (picom enabled or disabled doesn't affect the result here), for example, I open Firefox in workspace1, kitty doing nothing in workspace 2, I switch to workspace1 and hibernate, then I wakeup from hibernation, switch to workspace2 which contains kitty window, my whole system will freeze for over 10 seconds, I cannot type in the terminal, I cannot switch to another workspace.  If workspace2 contains other program such Calibre or alacritty, switching to it works totally fine.

I noticed this problem a few months ago, it happens every single time since then.

**To Reproduce**
1. Firefox or any other program in workspace 1
2. kitty window doing nothing in workspace 2
3. switch to workspace 1
4. hiberate the system
5. wakeup
6. switch to workspace 2
7. the system will freeze for over 10 seconds

**Screenshots**

**Environment details**
```
kitty 0.37.0 created by Kovid Goyal
Linux Archlinux 6.12.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:30:31 +0000 x86_64
S{PRETTY_NAME} 6.12.4-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
OpenGL: '3.1.0 NVIDIA 565.77' Detected version: 3.1
Frozen: False
Fonts:
  medium: NotoSansMonoCJKsc-Regular: /usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc:7
          Features: ()
    bold: NotoSansMonoCJKsc-Bold: /usr/share/fonts/noto-cjk/NotoSansCJK-Bold.ttc:7
          Features: ()
  italic: NotoSansMonoCJKsc-Regular: /usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc:7
          Features: ()
      bi: NotoSansMonoCJKsc-Bold: /usr/share/fonts/noto-cjk/NotoSansCJK-Bold.ttc:7
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/home/chz/.local/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.utf8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                chz
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_ADDRESS                          en_US.UTF-8
	LC_NAME                             en_US.UTF-8
	LC_MONETARY                         en_US.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/chz
	LC_PAPER                            en_US.UTF-8
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   en_US.UTF-8
	LC_TELEPHONE                        en_US.UTF-8
	LC_MEASUREMENT                      en_US.UTF-8
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_US.UTF-8
	LC_NUMERIC                          en_US.UTF-8
```

**Additional context**

I can reproduce this using empty `~/.config/kitty`

**Comment by kovidgoyal** [comment]
kitty has no code to deal with hibernation in any shape or form.
hibernation is something done by the OS kernel. And if the entire system
is freezing then the bug is somewhere in whatever is actually freezing
which could be either the kernel or the X server or the GPU drivers. I
suggest you try disabling picom or switching to wayland. Or report the
issue to whatever is actually freezing, only they can debug and tell you
what causes it.

**Comment by c02y** [comment]
Yeah, don't know why it happens only to Kitty, all ther programs like Alacritty or Calibre work totally fine.

Thanks for the project, really love Kitty, I'll simply switch to Wezterm.
