### ISSUE TITLE
Cursor trailing not visible when cursor moves vertically in a straight line

### ISSUE THREAD

**Issue by ucimo** [kovidgoyal/kitty#8150]
**Describe the bug**
Cursor trailing not visible when cursor moves vertically in a straight line. Jumping from start to end of file is not animated and that's the longest jump you can make. That's how I noticed it. Now I can't not notice it even when I jump just a couple of lines.

**To Reproduce**
1. Move cursor in N/Vim vertically in a straight line

**Screenshots**
Video:
https://github.com/user-attachments/assets/40530990-960f-4d3b-ad30-0d196bdc91e7

**Environment details**
```
macOS Sequoia 15.2
kitty 0.38.0 
```

**Additional context**
Just enable cursor_trail

**Comment by kovidgoyal** [comment]
@jinhwanlazy will have to comment

**Comment by jinhwanlazy** [comment]
Can't reproduce this issue. Could you share what's in your kitty.conf? Are you referring to the H and L movement keys in Vim?

By the way, there's a known issue with long key presses - you might want to check out this PR: https://github.com/kovidgoyal/kitty/pull/8092. Could that be what you're experiencing

**Comment by kovidgoyal** [comment]
It repros for me doing 10j to move down 10 lines with

kitty --config=NONE -o cursor_trail=3 nvim --clean setup.py

1. gg to go to start of file
2. 10j
 cursor jumps down 10 lines without a trail

**Comment by jinhwanlazy** [comment]
Ok I see it now.
