### ISSUE TITLE
The mouse cursor is not accurate in kitty on macos15.2

### ISSUE THREAD

**Issue by leavesullic** [kovidgoyal/kitty#8155]
**Describe the bug**
This is a really great tool and is my favorite.
This bug does not affect the use of Kitty but it is very annoying.
I don't know if this is a bug of macos or a bug of kitty, because I hardly found this bug on other application windows.
The mouse does not switch to the correct shape when it moves across the entire kitty window.
To be precise, in the kitty window, the mouse will always be an arrow or text selection cursor, and will not change according to the information the mouse is pointing to.

**To Reproduce**
1. focus on kitty window
2. drag the window to move for a while
3. then the mouse cursor becomes inaccurate

**Screenshots**
In the 1st pic, the cursor shape is wrong in kitty window.
In the 2nd pic, the cursor shape is right in macos default terminal window.
![SCR-20241224-nojx](https://github.com/user-attachments/assets/234bc8b5-1efa-4691-8033-a51aed76d20b)
![SCR-20241224-nomd](https://github.com/user-attachments/assets/1feca1bb-bd0e-44bf-892e-cfc58b6e63ad)

**Environment details**
kitty 0.38.0 (d3f93cb0cb) created by Kovid Goyal
Darwin sullicsmac.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 19:04:03 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8132 arm64
ProductName:		macOS ProductVersion:		15.2 BuildVersion:		24C101
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: True
Fonts:
  medium: ComicCode-Regular: /Users/sullic/Library/Fonts/Comic Code.otf
          Features: ()
    bold: ComicCode-Bold: /Users/sullic/Library/Fonts/Comic Code Bold.otf
          Features: ()
  italic: ComicCode-Italic: /Users/sullic/Library/Fonts/Comic Code Italic.otf
          Features: ()
      bi: ComicCode-BoldItalic: /Users/sullic/Library/Fonts/Comic Code Bold Italic.otf
          Features: ()
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
System color scheme: light. Applied color theme type: none
Loaded config files:
  /Users/sullic/.config/kitty/kitty.conf

Config options different from defaults:
bold_font            Comic Code Bold
bold_italic_font     Comic Code Bold Italic
focus_follows_mouse  True
font_family          Comic Code
font_size            16.0
italic_font          Comic Code Italic
mouse_hide_wait      2.0
symbol_map:
	U+3400 - U+4dbf → Hannotate SC
	U+4e00 - U+9fff → Hannotate SC
	U+f900 - U+faff → Hannotate SC
	U+20000 - U+2a6df → Hannotate SC
	U+2a700 - U+2b73f → Hannotate SC
	U+2b740 - U+2b81f → Hannotate SC
	U+2b820 - U+2ceaf → Hannotate SC
Changed shortcuts:
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website
Colors:
	background           #fafafa   
	color1               #ff3333   
	color10              #b8e532   
	color11              #ffc849   
	color12              #73d7ff   
	color13              #ffa3aa   
	color14              #7ff0cb   
	color2               #86b200   
	color3               #f19618   
	color4               #41a6d9   
	color5               #f07078   
	color6               #4cbe99   
	color7               #ffffff   
	color8               #323232   
	color9               #ff6565   
	cursor               #ff6900   
	foreground           #5b6673   
	selection_background #f0ede4   
	selection_foreground #fafafa   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                zh_CN.UTF-8
	SHELL                               /bin/zsh
	USER                                sullic

**Additional context**
None

**Comment by HUMORCE** [comment]
I have encountered a similar issue.

Reproduction:
1. Set the mouse cursor to Text cursor (aka I-Beam Cursor)
2. Switch to Kitty and move the mouse any position within the Kitty window; the mouse cursor will be keeping show as the Text cursor
3. Unless you move mouse cursor out from Kitty window then back, or moving kitty window by click title bar then drag.

I am not sure if this cause by macOS, but I have not experienced this with other programs. I have been this issue since macOS 12.x with Kitty.

**Comment by kovidgoyal** [comment]
Does not reproduce for me. Steps I tried:

1) Start kitty
2) Run echo http://test.com
3) Move mouse over test.com
4) Mouse becomes pointing hand cursor, as expected.
5) move mouse elsewhere in kitty window
6) mouse becomes text cursor, as expected.

Can you post some exact steps to reproduce your issue.

**Comment by kovidgoyal** [comment]
Never mind I think I follow the issue, it's when the mouse re-enters a kitty window after leaving it, correct?

**Comment by leavesullic** [comment]
> Never mind I think I follow the issue, it's when the mouse re-enters a kitty window after leaving it, correct?

yes, exactly

**Comment by HUMORCE** [comment]
The first step is making mouse cursor to Text cursor(I), on another program (e.g. inputbox on browser)
