### ISSUE TITLE
Kitty Cannot Start (GLFW Window Creation Issue)

### ISSUE THREAD

**Issue by sashasylona** [kovidgoyal/kitty#816]
Error: [231 17:37:03.569938] [glfw error 65543]: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
[231 17:37:03.570000] Failed to create GLFW temp window!

Stopped working after changing the colour theme of kitty. Remembering window size is not enabled.

**Comment by kovidgoyal** [comment]
That's an error with your OpenGL drivers. Not anything kitty can do about it. Make sure your OpenGL is actually working -- typically all you need to do is reboot.

**Comment by sashasylona** [comment]
Nope, that is incorrect; glxgears runs fine and so does a random OpenGL benchmark.

**Comment by sashasylona** [comment]
Additionally, I am running on OpenGL 4.6.0 on NVIDIA drivers, version 396.45.

**Comment by kovidgoyal** [comment]
That error literally means creation of the OpenGL context failed. I dont know what more I can tell you.

**Comment by sashasylona** [comment]
Probably something wrong with GLFW window creation. If you reopen this, somebody down the line could propose a solution.

**Comment by kovidgoyal** [comment]
This is not a bug tracker for GLFW, you are welcome to report the bug on the GLFW bug tracker, though I'm pretty sure they will tell you the issue is with your OpenGL drivers as well.

**Comment by sashasylona** [comment]
Seeing as my drivers are up-to-date, other OpenGL programmes function perfectly well, and GLFW window creation is not an issue, I find it unlikely that the problem is on GLFW's end.

**Comment by kovidgoyal** [comment]
Sure, and given that the thing that is failing is literally this line:

```
GLFWwindow *temp_window = glfwCreateWindow(640, 480, "temp", NULL, common_context); // with a NULL value for common_context. 
```

I dont see how this could possibly be an issue with anything other than your OpenGL drivers.

**Comment by sashasylona** [comment]
But since that line works perfectly fine when I run it on my own, there's no real reason for Kitty not to be working because of my up-to-date discrete drivers.

**Comment by kovidgoyal** [comment]
Sure there is. kitty uses an OpenGL 3.3 Core profile. That profile is what is used when creating windows. Your graphics drivers are failing to create a 3.3 core profile opengl window. Anyway I am done discussing this. As far as I can tell this is a bug in your graphics drivers. If you feel differently, feel free to suggest a patch for kitty code that resolves the problem, I know of nothing that kitty could do differently, but I am always happy to be proved wrong.

**Comment by sashasylona** [comment]
That would make sense as an answer if OpenGL weren't backwards compatible, but [my drivers are.](https://developer.nvidia.com/opengl-driver). My OpenGL 4.6 drivers should not crash when running a programme interfacing with the 3.3 core.

**Comment by sashasylona** [comment]
Yes, but only with your programme. Software as far back as 2.1 runs without a hitch.

**Comment by kovidgoyal** [comment]
I dont know what you are hoping to accomplish here. Endlessly repeating the same claim with is not going change my mind. As I said, as far as I can tell, there is nothing in kitty code that can be changed to fix your issue. If you feel differently, patches are welcome.
