### ISSUE TITLE
MacOS window decorations are turned off when background_opacity is set

### ISSUE THREAD

**Issue by dmtrKovalenko** [kovidgoyal/kitty#8165]
**Describe the bug**
is it  possible to keep window decorations (border and background shadow) for transparent windows? It would be really amazing 

**To Reproduce**
1. set background_opacity 
3. notice that window decorations are lost 

**Screenshots**
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/11bac85f-88d7-4f9c-81ad-b501fc3d97f9" />

**Environment details**
wasn't able to reproduce this using the shortcut mention but I use the kitty 0.38.0 on the ProductName:		macOS
ProductVersion:		15.2
BuildVersion:		24C101

**Additional context**.
not sure if its possilbe but maybe it would be possible to manually set some decoration because this gap between windows is killing me 
<img width="196" alt="image" src="https://github.com/user-attachments/assets/5646997b-b619-46cc-b855-0790f605c817" />

**Comment by kovidgoyal** [comment]
No, it isnt, see previous issues about it.
