### ISSUE TITLE
doesn´t support tmux?

### ISSUE THREAD

**Issue by lee-** [kovidgoyal/kitty#817]
> # tmux attach
> open terminal failed: missing or unsuitable terminal: xterm-kitty

This is on Fedora 28.

For the record, I had to install some dependencies to be able to compile:

harfbuzz-devel
fontconfig-devel
python3-devel
libxkbcommon-devel
libXrandr-devel
libXcursor-devel
libxkbcommon-x11-devel
dbus-devel
libXi-devel

I´m providing those so you could update the compiling instructions.

**Comment by lee-** [comment]
PS:

TERM=xterm tmux attach

... works.  Do I better specify another terminal type to make use of features xterm might not support but tmux does?

**Comment by kovidgoyal** [comment]
tmux sessions cannot attach across terminal emulators that have different terminfo databases. That is a limitation of tmux. And all those dependencies are already mentioned in the compiling instructions. Although if all you want to do is run kitty, use the pre-built binaries.

**Comment by lee-** [comment]
I had tmux detached from the terminal before trying to attach with kitty.  When exporting TERM, tmux attaches to kitty even while it´s still attached to xterm :)

I didn´t see all of the dependencies mentioned, that´s why I provided them.


This is a great project, btw :)

**Comment by kovidgoyal** [comment]
If you are building from master, then the up-to date list of dependencies is in docs/build.rst (if something is missing there, let me know). If you are building the released source tarball then the kitty website has the up-to-date dependencies.

Yeah, but by changing TERM to xterm you will break lots of other things. You are essentially telling all terminal programs that kitty is xterm, which it is not. Dont do that. Close your tmux sessions, then create new ones in kitty and they will work fine.

**Comment by lee-** [comment]
Thanks!  I´ve been building from master, and looking at docs/build.rst and again at the list on the web site, I think I must have overlooked that libXi-devel is actually mentioned.  However, the package names differ between different distributions ...

Closing the tmux session and creating a new one in kitty works fine :)

**Comment by kovidgoyal** [comment]
Yeah different package names across distros is a bridge too far for me. It is up to the users to convert the names I list into whatever name variant their distro uses.

**Comment by lee-** [comment]
BTW, could we have, or is there, an option to have the tab bar on the left or right?  My screen is wider than it´s high ...

**Comment by kovidgoyal** [comment]
Not something I am interested in, but patches are welcome.

**Comment by lee-** [comment]
Ok, if I can ever figure it out ...  Hiding the tabs might suffice ...

Now I´ve created a tab in kitty, started an ssh session to a remote machine and am trying to run tmux on the remote machine through that, and I´m getting the "failed" message again.  What should I do for tmuxes on remote machines via ssh with a local kitty?

**Comment by maximbaz** [comment]
Pretty much the same, close old session and create a new one. Also, connect to the remote host with `kitty +kitten ssh <hostname>` at least once so that kitty's terminfo is installed on that host.

**Comment by lee-** [comment]
I did close the tmux session.

Connecting once as kitten works, but when I try to start tmux from a tab in the running kitten, it still says the terminal type is unsuitable.

**Comment by silverjam** [comment]
@lee- I think you have to close any running tmux session, e.g. `tmux kill-server` before it'll work, not sure why.
