### ISSUE TITLE
Error building from source on Linux

### ISSUE THREAD

**Issue by syntacticalowen** [kovidgoyal/kitty#8174]
**Describe the bug**
When attempting to build from source using the `dev.sh build` command I receive a "no such file or directory" error.

```
./dev.sh build
The following build command failed: /home/<REDACTED>/kitty/dependencies/linux-amd64/bin/python setup.py develop
Error: fork/exec /home/<REDACTED>/kitty/dependencies/linux-amd64/bin/python: no such file or directory
```

**To Reproduce**
1. Install Go and C compiler (`build-essential` Debian package)
2. Clone repo
3. `./dev.sh build`

**Environment details**

* Fresh install of Ubuntu 22.04.5 LTS (5.15.0-124-generic)
* go version go1.23.4 linux/amd64
* gcc version 11.4.0

**Comment by kovidgoyal** [comment]
Doesnt repro for me and doesnt repro in CI either, which uses a Ubuntu image for testing. Try running ./dev.sh deps first.

**Comment by syntacticalowen** [comment]
@kovidgoyal I should have also clarified, this was a minimal install of Ubuntu server. After running `./dev.sh deps` I encountered other errors from missing system packages. From a fresh image, here is everything I needed to install

```
libxi-dev libdbus-1-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcursor-dev libxinerama-dev libxrandr-dev build-essential pkg-config fontconfig uuid-dev mesa-common-dev

```

then after running `./dev.sh deps` and `./dev.sh build` I was able to build from source. Cheers!

**Comment by kovidgoyal** [comment]
Yeah not every single dep is included basic ones like X11 and mesa and
are not. The list of included deps is in sources.json.
