### ISSUE TITLE
Ability to launch a specific layout running predetermined commands from a .sh file

### ISSUE THREAD

**Issue by enzojs** [kovidgoyal/kitty#8175]
**Is your feature request related to a problem? Please describe.**
I have like 4 scripts that I need to run in order to start a project:
- dev server
- local database
- Web socket server
- ....etc

I would like to run one command and have kitty terminal launch a window with a specific layout running the given commands

Also have a key bind to stop all running processes

**Describe the solution you'd like**

Something like this, I don't want to use tmux though
How to translate this to kitty terminal without tmux
```bash
#!/usr/bin/env bash

SESSION_NAME="dev_session"

# Create new tmux session, but don't attach to it yet
tmux new-session -d -s $SESSION_NAME

# Rename the first window
tmux rename-window -t $SESSION_NAME:0 'dev'

# Run `npm run dev` in the first pane
tmux send-keys -t $SESSION_NAME:0 'npm run dev' C-m

# Split the current window horizontally (or vertically, if preferred)
tmux split-window -h -t $SESSION_NAME:0

# Run `npm run db:start` in the new pane
tmux send-keys -t $SESSION_NAME:0.1 'npm run db:start' C-m

# Finally, attach to the session
tmux attach-session -t $SESSION_NAME

```

**Describe alternatives you've considered**
tmux works relatively fine but has some issues with kitty terminal, 

also this:
              On Wed, Jun 03, 2020 at 09:33:53AM -0700, Jason Stewart wrote:
> @kovidgoyal where do you keep your opinions on these things?  I'd love to read them.

I'm too lazy to blog I'm afraid, but searching the kitty issues for
multiplexer should find plenty of my comments on them. In summary:
multiplexers add unnecessary overhead, suffer from a complexity cascade,
because they actually have to *translate* escape codes, modifying them
in hackish ways to get them to work with their concepts of
windows/sessions.

Energy/performance wise they are poison, every byte has to be parsed
twice, once by the middleman and once by the terminal. And they act as a
drag on the ecosystem as a whole, making it very hard to get any new
features. Designing features becomes harder because you have to design
for compatibility with a horrible hack and the diffusion into the
ecosystem tends to get gated by basically a handful of individuals with,
let's say, very limited vision.

> 
> My take is that terminals are a horrible hack to begin with, we are already fallen and impure, so why not add drugs to the orgy?  But I haven't written a GPU accelerated terminal emulator, so there is much room for enlightenment on my side.

Terminals are fine, certainly better than any other interface paradigm I
have ever seen :) They are of course sadly neglected and have a lot of
legacy baggage it would be good to get rid of *cough* ncurses *cough*.

It never ceases to amaze me how little effort we developers put into the
tools we use.

_Originally posted by @kovidgoyal in https://github.com/kovidgoyal/kitty/issues/391#issuecomment-638320745_
            

**Additional context**
I tried using `kitty --session session.conf` but does not quite work as expected

**Comment by kovidgoyal** [comment]
Use https://sw.kovidgoyal.net/kitty/remote-control/

**Comment by enzojs** [comment]
Thanks for the quick reply!
I am a new kitty terminal user and been struggling with this for the past 3 hours.

Could you please provide an example on how can I achieve the same result as tmux?

Do I pass 2 —match args to send-text?

**Comment by kovidgoyal** [comment]
Read the docs I linked they are full of examples. I'm afraid I dont have the time to write a canned solution for you.
