### ISSUE TITLE
Install kitty in Kubuntu

### ISSUE THREAD

**Issue by xukai92** [kovidgoyal/kitty#818]
Hi I am trying to install kitty by `curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin` but get the error below
```
.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```
I check this issue https://github.com/kovidgoyal/kitty/issues/595 and particualrly this comment https://github.com/kovidgoyal/kitty/issues/595#issuecomment-407540165 but I don't know how to follow the solution
> Download new harfbuzz + freetype
build freetype with harfbuzz
install libraries into kitty/lib
patch libharfbuzz provided by kitty to look in '$ORIGIN' first

Is there some more detailed instructin on it?

**Comment by kovidgoyal** [comment]
Post on #595 if you need more help. Or simply update your Kubuntu -- up to date versions have a new enough freetype.

**Comment by okdewit** [comment]
Quick way to update to Freetype 2.8 on Ubuntu and derivatives (tested on Mint 18.3):
```
sudo add-apt-repository ppa:glasen/freetype2
sudo apt update
sudo apt upgrade
```

**Comment by xukai92** [comment]
Update Ubuntu solved this issue.
