### ISSUE TITLE
Cannot install on Fedora because of glew

### ISSUE THREAD

**Issue by camsn0w** [kovidgoyal/kitty#82]
Even after installing glew 2.0 I get 
CC: gcc (6, 3)
Package glew was not found in the pkg-config search path.
Perhaps you should add the directory containing `glew.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glew' found
glew >= 2.0.0 is required, found version: not found

**Comment by kovidgoyal** [comment]
Either the fedora package is incomplete or you also need to install the -dev variant, something like glew-dev or libglew-dev, or such). In any case glew is trivial to install from source, see the .travis.yml file in this repository for example.

**Comment by kovidgoyal** [comment]
Sorry, ignore the bit about travis, that was for glfw not glew. According to this page: https://www.rpmfind.net/linux/rpm2html/search.php?query=pkgconfig(glew)

the appropriate package is glew-devel
