### ISSUE TITLE
feature request to include a vi-mode for shortcuts.

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#820]
I would love it if there is a possbie vi-mode for shortcuts. for example I find changing tabs with arrow keys very difficult and it would be so much easier if I just could switch to normal mode of my kitty and then press shift+j/k to switch tabs.

**Comment by kovidgoyal** [comment]
Not something I am interested in, but you should be able to create a kitten to do this pretty easily, similar to the way the kitten used for resizing windows works.
