### ISSUE TITLE
How to go to the next tab with remote control?

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#821]
for example in the config file kitty_mod + arrow keys are mapped to next_tab and previous_tab. but I can't understand from the doc what next_tab and previous_tab are and how I can trigger them from a script myslelf.

**Comment by kovidgoyal** [comment]
There is no direct equivalent to next_tab, what you need to do is run

kitty @ ls

parse the JSON output to find the id of the next tab and then use kitty @ focus-tab

https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-focus-tab

**Comment by aranmohyeddin** [comment]
is there anyway to get the id of the current tab?

**Comment by aranmohyeddin** [comment]
let me tell you my exact use case maybe you can help me better, I just want to be able to change kitty tab with shift+j/k when I'm in normal mode of zsh. This is so useful for me because I also use this to change tabs in firefox and weechat.

**Comment by kovidgoyal** [comment]
Just map shift+j/k to next/prev tab in kitty.conf. As for getting the current tab via ls use is_focused in the JSON output (but note that you have to be running from master for that as it is not in a released kitty version yet.

**Comment by aranmohyeddin** [comment]
But if I make that mapping it will switch tabs while I'm typing j/k and I definitely don't want that.

**Comment by kovidgoyal** [comment]
I'm not sure what you are asking for. If you want to change tabs using a particular mapping, then obviously you cannot use that mapping to type. If you insist on using a mapping that has other uses as well, then use a prefix key with the mapping, such as

```
map kitty_mod+t>j next_tab
```

Although how this is any better than just using kitty_mod+arrow keys I dont know.
