### ISSUE TITLE
Cannot scroll slowly on mac os

### ISSUE THREAD

**Issue by dylan-chong** [kovidgoyal/kitty#822]
I have `wheel_scroll_multiplier 1.0` set in my configuration file, however, it is still quite uncomfortable to scroll on Mac trackpads. If I don't move my fingers fast enough on the trackpad, the terminal will never scroll. This is very disorienting, because it took me a long time to figure out that I was scrolling slightly too slowly for the scrolling to trigger.

I guess a possible solution would be to 'accumulate' scrolling distance, so that if the user is moving finger very slowly, if they move their finger a large enough distance, a single scroll event would trigger.

**Comment by dylan-chong** [comment]
By the way, it would be good to have smoother scrolling in general on Mac OS (or any trackpad for that matter). iterm2 supports smooth scrolling like any other Mac OS scrollable view port

**Comment by kovidgoyal** [comment]
dup of #819
