### ISSUE TITLE
`kitty +kitten icat image.png; clear` does not clear the printed image.

### ISSUE THREAD

**Issue by jellytux** [kovidgoyal/kitty#825]
`kitty +kitten icat image.png; clear` does not clear the printed image.`

**Comment by kovidgoyal** [comment]
Works for me, from current master, with the following test image:


kitty +kitten icat logo/kitty.png; clear

**Comment by meain** [comment]
This issue still exists on `0.14.0`.

I am on macOS High Sierra.
