### ISSUE TITLE
Specifying font variant fails on macOS

### ISSUE THREAD

**Issue by net** [kovidgoyal/kitty#83]
Specifying font variant fails on macOS

```
font_family      SF Mono Medium
italic_font      SF Mono Medium Italic
bold_font        SF Mono Semibold
bold_italic_font SF Mono Semibold Italic
```

<img width="91" alt="screen shot 2017-06-01 at 8 10 56 am" src="https://cloud.githubusercontent.com/assets/6983821/26679164/e0037eea-46a1-11e7-9984-1065e09e1ac1.png">

Using `auto` works fine.

```
font_family      SF Mono
italic_font      auto
bold_font        auto
bold_italic_font auto
```

**Comment by kovidgoyal** [comment]
Unfortuantely, I dont have an OS X machine capable of running kitty, only building it, so debugging font rendering issues is rather difficult for me. I have not really looked into font variant handling in OSX, but the relevant code is in core_text.py (set_font_family()) and core_text.m new()

Probably some some further attributes need to be set on the font_attributes dictionary.

**Comment by kovidgoyal** [comment]
The correct syntax for choosing SF Mono Semibold as your bold font is.

```
font_family SF Mono Medium
italic_font SF Mono Medium
bold_font        SF Mono Semibold
bold_italic_font SF Mono Semibold
```
