### ISSUE TITLE
Background rendering in vim

### ISSUE THREAD

**Issue by aw1cks** [kovidgoyal/kitty#831]
Hello,
I am having an issue with vim where using a theme with a different background colour from kitty creates a rendering issue. Here is a screenshot comparing kitty (on the left) to another terminal emulator on the right to show the difference in the background:
![term-bug](https://user-images.githubusercontent.com/12629429/44654118-8abdc700-a9e8-11e8-9e19-7624eb041f14.jpg)
 However when I open vim in tmux from kitty the issue seems to go away.
![tmux-bg](https://user-images.githubusercontent.com/12629429/44654141-9c06d380-a9e8-11e8-9722-864de93271db.jpg)
 Any suggestions for something I could try or is there a bug here?

**Comment by kovidgoyal** [comment]
this is answered in the kitty FAQ
