### ISSUE TITLE
ld: warning: text-based stub file TBD-file-path and library file library-file-path are out of sync

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#834]
When compiling kitty on macOS, I always got a lot of warnings that looked something like this:
`ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.`
I found the solution on another GitHub issue, which linked to http://sd.jtimothyking.com/2018/07/26/stub-file-and-library-file-out-of-sync/. The solution was to reinstall the command-line tools like this:
```
sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.old
xcode-select --install
sudo rm -rf /Library/Developer/CommandLineTools.old
```
Now I don't get any such warnings anymore.
I posted this issue in case anyone has the same problem since it took me quite a while to find this (admittedly easy) solution.

**Comment by kovidgoyal** [comment]
Thanks for the heads up.
