### ISSUE TITLE
Ctrl+C doesn't work under Workman Keyboard Layout on macOS

### ISSUE THREAD

**Issue by l2dy** [kovidgoyal/kitty#835]
I'm using the [Workman keyboard layout](https://github.com/workman-layout/Workman) on macOS 10.13.6. Kitty 0.11.3 ignores the <kbd>ctrl</kbd> in <kbd>ctrl</kbd>+{<kbd>C</kbd>,<kbd>A</kbd>,<kbd>E</kbd>,…} under this layout but recognizes <kbd>ctrl</kbd> correctly under the U.S. layout.

##### Under Workman Layout
```
char_count: 1 cocoa text: 63
scancode: 0x9 (c) mods: ctrl text: 63 glfw_key: C
```
##### Under U.S. Layout
```
char_count: 1 cocoa text: <none>
scancode: 0x8 (c) mods: ctrl text: <none> glfw_key: C
```

**Comment by kovidgoyal** [comment]
Assuming you inverted your debug logs since they show the expected output for the Workman layout and the incorrect output for the US layout, the problem is most likely that the layout breaks the UCKeyTranslate function from Apple. I dont know of any way to fix that, if you do, patches are welcome. See the keyDown function in glfw/cocoa_window.m for details. Either that functin is no working correctly or the keyboard unicode data supplied to it is incorrect which is loaded in updateUnicodeDataNS

**Comment by l2dy** [comment]
No, I didn't invert the logs. Here are the logs with kitty cf7ecd5e668093b7ade7f33be318291d815bc86e.

Workman:
```
on_key_input: glfw key: 345 native_code: 62 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
2018-08-28 xx:xx:xx.xxx kitty[] char_count: 1 cocoa text: 63
2018-08-28 xx:xx:xx.xxx kitty[] scancode: 0x9 (c) mods: ctrl text: 63 glfw_key: C
on_key_input: glfw key: 67 native_code: 9 action: PRESS mods: 0x2 text: 'c' state: 0 sent text to child
on_key_input: glfw key: 67 native_code: 9 action: RELEASE mods: 0x2 text: '' state: 0 ignoring as keyboard mode does not allow release events
on_key_input: glfw key: 345 native_code: 62 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```
U.S.:
```
on_key_input: glfw key: 345 native_code: 62 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
2018-08-28 xx:xx:xx.xxx kitty[] char_count: 1 cocoa text: <none>
2018-08-28 xx:xx:xx.xxx kitty[] scancode: 0x8 (c) mods: ctrl text: <none> glfw_key: C
on_key_input: glfw key: 67 native_code: 8 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
```

**Comment by kovidgoyal** [comment]
And of course the proper fix is to fix the layout definition files so that cocoa does not generate text when pressing ctrl+key

**Comment by l2dy** [comment]
> I suggest you simply hardcode a workaround in that function for your layout

The layout definition is just an XML file, so this could be a Cocoa-specific behavior. https://github.com/workman-layout/Workman/blob/master/mac/Workman.bundle/Contents/Resources/Workman.keylayout

The macOS built-in Terminal.app and iTerm2 both work with this layout, I'll try to find out if iTerm2 made a specific workaround.

**Comment by evaporei** [comment]
@l2dy did you find if any of those have a specific workaround? I don't want to leave kitty, but I'm invested in workman, and every other terminal emulator I tried `Ctrl-C` works just fine 😕

**Comment by l2dy** [comment]
@evaporei No. I gave up and kept using iTerm2 since then.

**Comment by evaporei** [comment]
I see, I've been able to reproduce my kitty config in Ghostty, I think I'll stick with that.
