### ISSUE TITLE
pasting text with special quote after ssh

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#836]
I ssh to a remote machine using Kitty, and the try to paste some text containing the following quotes like this:
```
grep “123” current.log
```
Which results in the following:
```
current.log123grep
```

Using the following quotes pasting is ok:
```
grep "123" current.log
```

I notice this also happen on the macos Terminal app. Is this supposed to be like this?

**Comment by kovidgoyal** [comment]
This has nothing to do with kitty. The unicode symbols are being eaten up by whatever shell you are running on the server. Run a modern shell such as up-to-date zsh and make sure your LANG variable is correctly set to a UTF-8 locale and you will be fine.
