### ISSUE TITLE
Jumping words in macOS

### ISSUE THREAD

**Issue by sssilver** [kovidgoyal/kitty#838]
How do you jump the cursor per word in macOS?

Option+arrows just type alphabetic characters into the terminal, although in every other macOS app they jump words.

**Comment by kovidgoyal** [comment]
Use whatever bindings your shell has for it, IIRC ctrl+w in bash. Which will work in all operating systems. And if you really want to use macOS shortcuts add hte appropriate mapping in your kitty.conf.

**Comment by matthewgrossman** [comment]
For those searching, I was able to get this working via:
https://github.com/matthewgrossman/dotfiles/blob/7966e32aebbf50102eb7e848c066e5065a87f68b/config/kitty/kitty.conf#L653-L655

**Comment by kbd** [comment]
> Use whatever bindings your shell has for it, IIRC ctrl+w in bash

^ This is best. Note that option+left/right doesn't work out-of-the-box on iTerm2 either. Here are Zsh keybinds to enable option+left/right to move by words. 

```
# iterm
bindkey "\e\e[D" backward-word # ⌥←
bindkey "\e\e[C" forward-word # ⌥→

# kitty
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word # ⌥→
```

**Comment by danisvaliev001** [comment]
> For those searching, I was able to get this working via: https://github.com/matthewgrossman/dotfiles/blob/7966e32aebbf50102eb7e848c066e5065a87f68b/config/kitty/kitty.conf#L653-L655
> 
> ```
> map alt+left send_text all \x1b\x62
> map alt+right send_text all \x1b\x66
> ```

Is there some way to keep it working word-by-word in paths? It is jumping over the full path and ignoring `/` now.

**Comment by hermannolafs** [comment]
> ^ This is best. Note that option+left/right doesn't work out-of-the-box on iTerm2 either.

It does however ship with a full preset for this! I can't find it in the iTerm2 docs, but this stack [exchange thread shows where it's found](https://apple.stackexchange.com/a/463739).
I think this is what people missing from Kitty, and I imagine someone has already compiled all of the binds from there to a kitty config. 
👀 Now it is just to find it 🕵️‍♀️

**Comment by deepu-james** [comment]
> Is there some way to keep it working word-by-word in paths? It is jumping over the full path and ignoring `/` now.

@danisvaliev001 , were you able to crack this?

**Comment by danisvaliev001** [comment]
> > Is there some way to keep it working word-by-word in paths? It is jumping over the full path and ignoring `/` now.
> 
> @danisvaliev001 , were you able to crack this?

In ZSH it works by adding the next line to `.zshrc`:
```
export WORDCHARS='*?_-.[]~&;!#$%^(){}<>'
```

In Nushell it works by default.

My kitty configuration for ⌥ and ⌘ usage:
```shell
### remap kitty to use ⌥ and ⌘:
map cmd+v paste_from_clipboard
## jump to end of line:
map super+right send_text all \x05
## jump to start of line:
map super+left send_text all \x01
## jump right to end of word:
map alt+right send_text all \x1b\x66
## jump left to beginning of word:
map alt+left send_text all \x1b\x62
## delete line from cursor position to start of line:
map super+backspace send_text all \x15
## delete word works by default via opt+backspace
## undo:
map super+z send_text all \x1f
```
