### ISSUE TITLE
Option to hide titlebar on macOS

### ISSUE THREAD

**Issue by net** [kovidgoyal/kitty#84]
An option to hide the titlebar on macOS would be nice.

<img width="325" alt="screen shot 2017-06-01 at 8 18 53 am" src="https://cloud.githubusercontent.com/assets/6983821/26679436/fbc7660e-46a2-11e7-99bc-a79a8d28d88b.png">

**Comment by kovidgoyal** [comment]
I know of no way to do that using glfw (the windowing toolkit kitty uses). The only way I know of is to use glfwWindowHint(GLFW_DECORATED, false);

but that has the side effect of there now being no way to move/resize the window. 

If you know of some way to do this, then feel free to re-open this.

**Comment by net** [comment]
You can still move windows on macOS without a title bar. Hover over the edge of a window so the resize arrow appears, then drag perpendicular to the direction of the resize arrow.

Anyways, I use a window manager, and probably most people who would disable the titlebar also use a window manager.

**Comment by net** [comment]
Ah, I see what you mean. `GLFW_DECORATED, false` removes the resize-from-edge ability.

**Comment by koekeishiya** [comment]
I forked glfw and tweaked their cocoa window crestion to make GLFW_DECORATED not make it unresizable. You can tweak the brew formulae head option to pull from that branch and replace the dylib in the kitty app

**Comment by net** [comment]
@koekeishiya Thanks, that worked! I had to build glfw manually, brew gave me [an error](https://gist.github.com/net/9632953ab1ce38c3849118fec4d681d8).

**Comment by net** [comment]
@kovidgoyal How do I package the .app?

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/issues/75

**Comment by koekeishiya** [comment]
@net You don't have to compile Kitty yourself, unless you've made some custom changes.

Simply copy the compiled glfw.dylib into `Kitty.app/Contents/Frameworks/` replacing the existing glf3.dylib file (note: names must match). The Kitty executable rpaths will still be valid and it will run using your modified dylib.

**Comment by net** [comment]
@koekeishiya How else would I disable the titlebar?

**Comment by net** [comment]
🎉

**Comment by Istanful** [comment]
You can use this to hide the titlebar.

```
macos_hide_titlebar yes
```

For some reason magnet stops working for that window though. :/

**Comment by jdhao** [comment]
It seems that this option is not available. we should use option `hide_window_decorations yes` instead, ref [here](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.hide_window_decorations).

**Comment by dusty-phillips** [comment]
> reason magnet stops working for that window though. :/

This is still be the case with `hide_window_decorations yes`. Has anyone solved it?

**Comment by Luflosi** [comment]
Does `hide_window_decorations titlebar-only` do what you want?

**Comment by dusty-phillips** [comment]
it does! thanks. :-)

**Comment by maxlibin** [comment]
is there an option that allow me to drag around(not resize) if `hide_window_decorations yes` ?

**Comment by Luflosi** [comment]
I don't know about `hide_window_decorations yes` but if `hide_window_decorations titlebar-only` is also fine for you, you can move the window by dragging at the window borders perpendicular to the resize direction (just like almost all other macOS apps).

**Comment by Amparose** [comment]
On MacOS 11, the perpendicular drag trick doesn't seem to `hide_window_decorations yes`. Perhaps due to a minimised hit zone. `hide_window_decorations titlebar-only` works and you can see and invisible hit zone above the window too. Any way to influence this as I prefer `hide_window_decorations yes`?

**Comment by sheerun** [comment]
titlebar-only works, but I'm unable to move the window, like in iterm ;(

**Comment by adrianmihalko** [comment]
Minimal style titlebar (like iTerm2) would be awesome:

<img width="657" alt="Screenshot 2021-12-14 at 23 41 16" src="https://user-images.githubusercontent.com/733361/146090953-f7729b3e-b3a6-4115-a31b-40c581e2836a.png">

**Comment by yamiteru** [comment]
Setting it either to titlebar-only or yes does nothing. I'm on Monterey.

**Comment by Ozarklake** [comment]
@yamiteru Restart the kitty and it will work. Thx @page-down

**Comment by vamsee007** [comment]
In Mac OS Sonoma, none of these options seem to work

`hide_window_decorations yes ` 
`macos_hide_titlebar yes`

Anyone else facing the same issue

**Comment by ad-chaos** [comment]
nope, cannot reproduce this on the master branch with `kitty --config none -o hide_window_decorations=yes`

**Comment by oskarrough** [comment]
I'm on OS X Sonoma and setting `hide_window_decorations titlebar-only` works here.

However the "drag area" of the window is naturally very small. You'll need to drag perpendicular while the cursor is exactly on the window edges.

**Comment by vamsee007** [comment]
I was able to hide the title-bar when the kitty window is non-fullscreen...
I'd like to hide the title-bar even when the kitty window is set tot full-screen.
Once I maximize kitty to Full-Screen, I still see the title bar. 

In the previous MAC OS versions, the title-bar is not shown with these options even in full-screen.. (same with iTerm2)
But with Sonoma, I see this issue on Kitty as well as iTerm2.. I guess its something to do with the MAC OS..

If anyone could figure out if there's any way to disable the title-bar completely in full-screen that'd be Great!

**Comment by saito-sv** [comment]
`macos_show_window_title_in none`

#: Control where the window title is displayed on macOS. A value of
#: window will show the title of the currently active window at the
#: top of the macOS window. A value of menubar will show the title of
#: the currently active window in the macOS global menu bar, making
#: use of otherwise wasted space. A value of all will show the title
#: in both places, and none hides the title. See
#: macos_menubar_title_max_length for how to control the length of the
#: title in the menu bar.

`macos_menubar_title_max_length 0`

#: The maximum number of characters from the window title to show in
#: the macOS global menu bar. Values less than one means that there is
#: no maximum limit.

**Comment by JohnAnon9771** [comment]
Set the background color of your terminal and it will have an "invisible" appearance

```sh
macos_show_window_title_in none
macos_titlebar_color #272727
macos_menubar_title_max_length 0
```

<img width="1440" alt="image" src="https://github.com/kovidgoyal/kitty/assets/42195321/ee4733fd-ad3c-4303-b2aa-07431883ba10">

**Comment by diegoulloao** [comment]
> Set the background color of your terminal and it will have an "invisible" appearance
> 
> ```shell
> macos_show_window_title_in none
> macos_titlebar_color #272727
> macos_menubar_title_max_length 0
> ```
> 
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/42195321/335026401-ee4733fd-ad3c-4303-b2aa-07431883ba10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzI2NjYsIm5iZiI6MTcyMTkzMjM2NiwicGF0aCI6Ii80MjE5NTMyMS8zMzUwMjY0MDEtZWU0NzMzZmQtYWQzYy00MzAzLWIyYWEtMDc0MzE4ODNiYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE4MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDFjNTk1NDA4NzVlZTYzMmNlMmJjNjc1YzliN2UzYWExNzYxY2RiYmViYmYyY2FiOTg1OGUxMjE1OWUxNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ytLAOhkV0MNj4AK6mqeA1zWyISYuNLb6QOIZb_bad4s">

In my case I'm using a background image.

**Comment by muuvmuuv** [comment]
@JohnAnon9771 how did you got rid of that black border here?
![image](https://github.com/user-attachments/assets/0da36517-8eb4-444e-a54a-39f4030136ec)
