### ISSUE TITLE
Mouse-cursor gone

### ISSUE THREAD

**Issue by hjanuschka** [kovidgoyal/kitty#842]
hello,

sadly i have no way to constantly reproduce it, but it happens quiet a lot.

having kitty open maximized, sometimes when i move the mouse to the second monitor, the "cursor" is gone - invisible, rightclicking, shaking it recovers it.

OS: OSX 10.13.5
kitty: master

**Comment by kovidgoyal** [comment]
Unfortunately I dont have multi-monitors to test with so there's not much I can do about it. Given that simply moving the mouse will cause it to show up, I dont think it's a big deal. You canalso disable mouse cursor hiding completely in kitty.conf.

If someone on macOS wishes to contribute a patch to fix it, that is welcome.

**Comment by a1k0n** [comment]
This is driving me crazy.

I have a theory that kitty on OS X is hiding the mouse cursor even if it's not the active program; to reproduce, select a kitty window, start typing, then go click on another app window. 3 seconds later, the mouse cursor disappears and moving it doesn't make it reappear. I am also using a multi-monitor setup.

I ended up disabling mouse cursor hiding to restore my sanity for now, but I might take a closer look later.

**Comment by kovidgoyal** [comment]
I dont see how kitty hiding the mouse would make the mouse disappear on non-kitty windows, that would mean any app can play tricks with the mouse cursor for any other app. Typically in window systems if one app hides the mouse on its window it stays hidden only when that window has focus. If you switch to an unrelated window, the mouse cursor should automatically be made visible unless that window has also chosen to hide the mouse cursor.

**Comment by kovidgoyal** [comment]
Indeed I tried to reporduce this on a single monitor in macOs and could not. I even tried the following:

1) start kitty
2) wait for mouse cursor to be hidden
3) press alt tab to focus some other application
4) the mouse cursor becomes visible even though it is still over kitty

which I think demonstrates that one window cannot hide the mouse cursor for an unrelated window when that window gains focus,

**Comment by a1k0n** [comment]
The steps I was able to reproduce it with yesterday were to type with the mouse visible in the kitty window, then switch to another window before the mouse hide wait, and then it would hide the mouse even on another application. However it's not happening now. I suspect it's some bug in MacOS or something (of course it shouldn't allow mouse hiding in unrelated windows); it's infuriating because it's so hard to figure out when it's happening, but disabling mouse hiding cured it for me.

**Comment by hjanuschka** [comment]
🚀🚀🚀🚀🚀🚀  
that thing was driving me nuts for ages.


mouse_hide_wait 0  


fixed it  

--  
Helmut Januschka
Sent with Airmail

**Comment by Luflosi** [comment]
I also experienced this issue before but I didn't find a reliable way to reproduce it. Shaking the cursor really fast to make the cursor change size for a moment (a feature of macOS to find the cursor more easily) usually made it reappear but that did not always work and was very annoying to do. https://github.com/Luflosi/kitty/commit/362ab966ce1d9b6261e03257a932de49ebf79044 seems to have improved the situation a lot for some reason. I know this is probably not a proper fix but it might point us in the right direction. @hjanuschka and @a1k0n can you try to comment out those two lines and see if it makes any difference?

**Comment by olekli** [comment]
I have just updated to Catalina. Kitty is in fullscreen. When kitty hides the mouse cursor and now I switch to another fullscreen app using the keyboard, the mouse cursor does not reappear. The mouse is still active but no cursor is shown. Moving the invisible cursor to the top menu bar makes it reappear after a moment.

When kitty hides the mouse cursor and I move it while still inside kitty, it will reappear. But after it has disappeared, moving it inside kitty has no effect.

**Comment by Luflosi** [comment]
I have not yet updated my main Mac to Catalina, so I didn't experience this bug yet.
@kovidgoyal maybe we need to manually show the cursor again when kitty looses focus?

**Comment by kovidgoyal** [comment]
maybe, but seems like overkill and might have other side effects.

lets first see if we can reproduce the issue and fix it properly.

**Comment by Luflosi** [comment]
I'll probably update to Catalina in the next couple days, then I'll try to reproduce the issue.

**Comment by olekli** [comment]
Well yes, about reproducing: I have another machine, also on Catalina, and it turns out, there it does not happen... I'll let you know if I happen to figure out what the difference between the setups is. (It's 2018 13" vs 2019 15", mostly the same software, the latter one shows the bug.)

**Comment by olekli** [comment]
It is related to having a second display. I usually only use an external display, the bug does not occur then. If I additionally use the internal display of the macbook, the bug does not occur either.

But I had tested the new sidecar feature with my Ipad. After this, the bug appears and may or may not stay after disconnecting the sidecar.

If it stays, it can be resolved by logout/login.

The only observable difference between using the sidecar vs using the internal display as second display is that using the sidecar also results in a change of scaling on the external monitor.

I guess it has nothing to do with Catalina but was rather the sidecar that came with Catalina.

For me this is no issue anymore.
