### ISSUE TITLE
some unicode characters are shown wrong

### ISSUE THREAD

**Issue by DLFW** [kovidgoyal/kitty#844]
Just pasting "▒ ╠ ╡ ╢ ╣ ╤ ╥ ╦ ╧ ╨ ╩ ╪ ╫ ╬ ► ◃─" to kitty or printing it from a program or script (tried java and python) gives some pretty ugly output. Copying it back to the clipboard results in the correct string again. Tried with fonts Inconsolata and DejaVu Sans Mono. Removed my kitty.conf to use the default config. Same results in all cases.

The screenshot shows a program printing this string in - from top to bottom:

* konsole
* urxvt
* kitty

![screenshot_20180829_231852](https://user-images.githubusercontent.com/22507197/44816703-506c4980-abe3-11e8-910d-a57b1b4131f1.png)

Any ideas?

**Comment by maximbaz** [comment]
How do these look for you on the screenshot of my kitty, are they considered "wrong" or "correct"?

![image](https://user-images.githubusercontent.com/1177900/44816956-210a0c80-abe4-11e8-8282-31637800ef67.png)

**Comment by DLFW** [comment]
Well, I just realized, there is a funny effect.
@maximbaz , they look half-correct: correct characters but the box-drawing characters are somehow to “widened”.
@kovidgoyal , I just pulled freshly from the master before trying yesterday

The funny effect is that it depends simply on the font size. If I increase the font size massively, the box drawing characters look normal. If they are medium size, they look fatty like in maximbaz' screenshot. If you make it smaller, they completely degenerate.
I tried it with a few more unicode characters and so far, only the box drawing characters seems to be affected.

**Comment by kovidgoyal** [comment]
If you dont like them fat there is a setting you can use to make them thin see box_drawing_scale in https://sw.kovidgoyal.net/kitty/conf.html

And what font size and monitor DPI are using that they are distorted at?

**Comment by kovidgoyal** [comment]
Box drawing characters are not drawn from fonts that would cause them not to be perfectly aligned with cell boundaries (this is the case for most terminal emulators as far as I know). Their thickness is not related to font size in anyway. If you want to see the algorithms used to draw them, look in box_drawing.py
