### ISSUE TITLE
kitty shell command: change layout

### ISSUE THREAD

**Issue by jschementi** [kovidgoyal/kitty#845]
It'd be useful to change the layout of a tab from the kitty shell, like `kitty @ layout vertical`.

I ues a script with `kitty @` calls to script the creation of a kitty terminal environment, since startup sessions don't seem to work well for me, and I prefer having a script that I can control the flow of things with. Being able to set the layout would be great!

**Comment by jschementi** [comment]
Hi @kovidgoyal! Can you give any context about why this won't be done?

**Comment by kovidgoyal** [comment]
It's already done. Follow the link to the commit referenced in the closing message.

**Comment by jschementi** [comment]
Oh, fantastic! 👏 

Apologies for not seeing the commit earlier.
