### ISSUE TITLE
Hide titlebar in linux

### ISSUE THREAD

**Issue by midnio** [kovidgoyal/kitty#846]
![image](https://user-images.githubusercontent.com/36359066/44840030-e8e8e500-ac48-11e8-9954-479b51fdaded.png)
I do not want to see this titlebar anymore. It's can be really annoying sometimes. What should i add to my kitty.conf file?

**Comment by kovidgoyal** [comment]
Create a rule in your window manager configuration to hide the titlebar from windows with class name kitty.
