### ISSUE TITLE
<ALT>+key not working

### ISSUE THREAD

**Issue by ThomasMarcel** [kovidgoyal/kitty#847]
OS: macOS High Sierra 10.13.6 (17G65)
Kitty: 0.11.3

`<ALT>+key` are displaying something wrong or are beeping and aren't displayed like in other terminals.

FYI I use a Spanish keyboard, the key `ñ` is displayed correctly, so I don't think it has to do with the layout in terminal, but all that is `<ALT>+ñ` which should give `~` beeps as wrong inputs do.
`<ALT>+´` which should give `{`, instead returns `''`, and pretty much all other combinations with `<ALT>` are beeping and not displaying anything.

**Comment by Luflosi** [comment]
Put `macos_option_as_alt no` into your kitty.conf. This will let you use the alt key to type unicode characters again instead of passing the alt key directly to the shell or whatever you're running.

**Comment by ThomasMarcel** [comment]
Thank you! That did it.

**Comment by Athesto** [comment]
I don't know if it could be here, but I had the same problem, but i'm in a `PC` with `ubuntu 20.04` and to get the `alt+ñ` I did a map in the kitty.conf
```
map alt+ñ               send_text application \x1bñ
```
it was perfect for my vim' spanish configuration
