### ISSUE TITLE
Support padding

### ISSUE THREAD

**Issue by cserb** [kovidgoyal/kitty#85]
Are there any plans on supporting inner padding?

**Comment by kovidgoyal** [comment]
What is inner padding?

**Comment by cserb** [comment]
The distance between text and border. Just like `internalBorder` for urxvt: 
```
URxvt.internalBorder: 4
```

**Comment by kovidgoyal** [comment]
You mean the border of the window? I dont have any plans for that, but it should not be particularly hardfor a motivated third party to create a patch. Basically modify the layout_dimension() function to account for the padding.

**Comment by kovidgoyal** [comment]
See for example: https://github.com/kovidgoyal/kitty/commit/bbc6b2d86a7701f8692f3ebe1dca022661b024ab

padding is a little more involved because you have to change the border drawing code as well, in borders.py
