### ISSUE TITLE
Kitty 12.0 breaks image preview.

### ISSUE THREAD

**Issue by VGrol** [kovidgoyal/kitty#850]
> Arch Linux 4.18
> Kitty 0.12.0
> Neofetch 5.0.0

The upgrade to Kitty V12.0 on Arch Linux seemed to have broken image displays via the Kitty protocol.
Neofetch configured to display images the 'Kitty' way, is no longer functioning in V12, it instead returns
`^[_Gi=1;OK^[\^[_Gi=2;OK^[\0s max. wait)...`
and then after several seconds it returns.
`^[_Gi=1;OK^[\^[_Gi=2;OK^[\0`
After which it just drops the Neofetch text without the image.

A rollback to V11.3 results in the problem being resolved.

I'm not exactly certain if this needs to be reporterd here or on the Neofetch repo,
Unless the kitty-image display has gotten a major overhaul, I don't think it is a problem with the Neofetch implementation of the kitty image viewer.

**Comment by kovidgoyal** [comment]
icat still works for me on Arch with kitty 0.12 doesn't neofetch just use icat? How is one supposed to get neofetch to display an image, so I can reproduce?

**Comment by itaton** [comment]
icat does not work for me on Arch with kitty 0.12 (I tried ``kitty icat image.png``)
I'm getting the same output as VGrol at first and after a couple of seconds when it return, it prints ``^[_Gi=1;OK^[\^[_Gi=2;OK^[\This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it``

I can also confirm that it was working before I upgraded.

**Comment by kovidgoyal** [comment]
As I said icat works for me on arch and I can't think of anything that could have changed in 0.12 to break it. The only thing I can think of is a problem in the binaries, as I am running from source. Can one of you check if it works when running from source. 

Also, as a workaround, since detection seems to be failing for you, you can use icat --transfer-mode=file to bypass it or if you are over an SSH connection, use icat --transfer-mode=stream

**Comment by kovidgoyal** [comment]
I tested it with the binary on arch and that also works for me.

**Comment by itaton** [comment]
``kitty icat --transfer-mode=file image.png`` works

**Comment by kovidgoyal** [comment]
You can try a bisect to see which commit is breaking detection. The only two commits I can find that might be relevant are: 0cc008e and d964146

**Comment by kovidgoyal** [comment]
Ah, that makes sense -- I'll fix that, but neofetch should be changed to use +kitten icat asplain icat is legacy.

**Comment by SolitudeSF** [comment]
i submitted pr with updated invocation to neofetch

**Comment by kovidgoyal** [comment]
thanks :)
