### ISSUE TITLE
Unable to use arguments when using macOS open command

### ISSUE THREAD

**Issue by jessetan** [kovidgoyal/kitty#854]
On the macOS terminal, the following command correctly handles the supplied argument:
```console
$ /Applications/kitty.app/Contents/MacOS/kitty --version
kitty 0.12.0 created by Kovid Goyal
```

But the following does not:
```console
open -a "kitty" --args --version
```

Result: A new Kitty window opens.
Expected: The version string is printed and no Kity windows is opened.

**Comment by kovidgoyal** [comment]
When you open things with launch service (i.e. via open) they are not connected to the current terminal, so they will not print anything out. kitty has its own mechanism to pass command line arguments when launched via launch services see  https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos

However, I suppose I can add support for using open --args as well when the user is not using the kitty mechanism.
