### ISSUE TITLE
Layouts don't work (or documentation is confusing)

### ISSUE THREAD

**Issue by skorokithakis** [kovidgoyal/kitty#858]
I'm trying out kitty and I can't figure out how to get layouts to work. I'm pressing ctrl+shift+l, there's a bit of a flash but nothing happens. The documentation does not say anything on the topic, how can I use layouts?

**Comment by skorokithakis** [comment]
I just read the part on windows and figured things out. You might want to make that part a bit clearer in the documentation, e.g. mention "changing a layout will rearrange all the currently open windows".

**Comment by kovidgoyal** [comment]
You are welcome to send a PR with improvements to the documentation (docs are in the docs directory)
