### ISSUE TITLE
Kitty's images are broken since ~1 week ago

### ISSUE THREAD

**Issue by Snuggle** [kovidgoyal/kitty#865]
Hey! Ever since an update about a week or so ago, my images have been completely broken and I'm not sure why. This happens when using both the `kitty icat` command and when using images in neofetch. I'm using the latest NVIDIA drivers and nothing else should've changed dramatically.

![image](https://user-images.githubusercontent.com/26250962/45132759-0e667900-b18a-11e8-9098-0ad906db70ca.png)

My kitty.conf - https://pastebin.com/sCCgr1dD

My neofetch:
```
~ 
➜ neofetch --stdout
snuggle@cherrypie 
----------------- 
OS: Arch Linux x86_64 
Kernel: Linux 4.18.5-zen1-1-zen 
Uptime: 8 hours, 38 mins 
Packages: 1242 (pacman) 
Shell: fish 
Resolution: 1920x1080, 1360x768, 1920x1080 
DE: GNOME 3.28.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Arc-Dark-solid 
Icons: Papirus 
Terminal: kitty 
Terminal Font: Noto Sans 
CPU: Intel i7-2600K (8) @ 5.9GHz [42.0°C] 
GPU: NVIDIA GeForce GTX 960 
Memory: 6615MiB / 13975MiB 
GPU Driver: NVIDIA 396.54 
Disk (/): 40G / 461G (9%) 
Disk (/mnt/Storage): 533G / 932G (58%) 
```

**Comment by kovidgoyal** [comment]
dup of #850

**Comment by Snuggle** [comment]
My apologies, I couldn't find a duplicate after a short look.
