### ISSUE TITLE
Cannot find a lot of commands, vim does not work properly

### ISSUE THREAD

**Issue by eprislac** [kovidgoyal/kitty#87]
On macOS, this does not read ~/.bash_profile upon opening (can be applied via `source ~/.bash_profile`), and does not recognize packages installed via HomeBrew, meaning tmux, nvim, and even my updated bash (macOS ships with 3.2, I have 4 installed), and homebrew itself are unavailable to me at the moment in this terminal (also missing are fasd, ondir and rbenv, which are all called via a bash-it script). zsh can be loaded via `exec zsh` and does load oh-my-zsh, but is afflicted by the same problems as bash and cannot access HomeBrew or packages installed via brew.

**Comment by kovidgoyal** [comment]
Umm kitty has nothing to do with any of that. The job of a terminal emulator is to provide a pseudo-termial device, send keystrokes to it, read and display output from it. Reading ~/.bash_profile and co. are the job of the program connected to the pseuo-terminal, usually a shell like bash or zsh.

Since both bash and zsh work just fine under kitty on macOS, it's likely something in one of your shell startup scripts that is broken. Probably some poorly though out conditionals based on the TERM environment variable. Either fix your shell startup scripts or tell kitty to use a different TERM value via its config file, the safest is probably ``xterm``

**Comment by eprislac** [comment]
@kividgoyal I use xterm-266color for TERM in both iTerm and Terminal, this is what shows up in Kitty. I'd recommend making the login shell the default, rather than something that needs to be configured.

**Comment by kovidgoyal** [comment]
I assume you mean xterm-256color, not xterm-266color. And you absolutely should not set TERM variables in startup scripts. This is a widespread anti-pattern from the bad old days. TERM variables should be set only by actual terminal software. TERM variables are used to access terminal control sequence information from the terminfo databases. Setting them in shell startup scripts breaks that and should only be used a last resort and then only if you really know what you are doing. 

And let me re-iterate kitty works just fine out of the box with zsh and bash with their default configurations.

**Comment by braham-snyder** [comment]
FWIW, for me on OS X (at least on El Capitan), even after setting `SHELL` to `/bin/bash`, none of my login shell config is available when I open kitty using the GUI (Finder, Spotlight). (Just using, for example, `fish --login --command 'open -a kitty'` avoids the behavior, of course.)

I have no `~/.bashrc`, and this is my `~/.bash_profile` at the moment:
```
# Since bash does not read ~/.profile if ~/.bash_profile exists, and yet we
# probably still want ~/.bash_profile (this file) for bash-specific login
# configuration: e.g., sourcing ~/.fzf.bash.
[ -r ~/.profile ] && source ~/.profile
# Because OS X (and macOS) is weird and opens nearly all shells as login shells
# instead of opening one login shell when... logging in... and then merely
# opening interactive sub-shells (and/or sub-"processes"? same gist) thereafter,
# this is required to ensure that we source our interactive configuration. See,
# e.g.:
# https://apple.stackexchange.com/questions/119711/why-doesnt-mac-os-x-source-bashrc
[ -r ~/.bashrc ] && source ~/.bashrc

[ -r ~/.fzf.bash ] && source ~/.fzf.bash
```

and the first few lines of my `~/.profile` (`XDG_CONFIG_HOME` is only empty when I launch `kitty` using the GUI):
```
export XDG_CONFIG_HOME=~/.config/
export XDG_CACHE_HOME=~/.cache/
export XDG_DATA_HOME=~/.local/share/
```

Setting `term` to `xterm` in my `kitty.conf` didn't change that behavior for me.

All that said, using `fish --login --command [...]` is fairly painless.
