### ISSUE TITLE
Can't enter a tilde character

### ISSUE THREAD

**Issue by joa** [kovidgoyal/kitty#871]
### Expected Behavior
Entering text works.

### Actual Behavior
On my Mac, I enter `~` by pressing Alt+N. This doesn't work in Kitty. Same goes for all other characters that require Alt as a modifier key, like `€`, `™`, `é`, `´` etc.

I am using the "U.S. International - PC" layout as this provides me the option to enter characters like `ä` by entering `"` followed by an `a` for instance. (`"` is " and then space). Maybe this is some weird IME issue?

### Steps to Reproduce
1. Switch to "U.S. International - PC" on a Mac
2. Press Alt+N in the GitHub comment box to verify you get a `~` character. 
3. Press Alt+N inside Kitty

**Comment by kovidgoyal** [comment]
Set macos_option_as_alt=no in your kitty.conf to use alt as a compose key.

**Comment by kovidgoyal** [comment]
Sorry make that 
```
macos_option_as_alt no
```

in kitty.conf

**Comment by Herz3h** [comment]
I think that it should be the default too, I'm new to kitty, I tried kitty few days ago and I stopped using it because my option key wouldn't work and I had no idea why.... Maybe user should be prompted upon first launch if he wants this or not ?

**Comment by kovidgoyal** [comment]
Dunno, in my experience popus on first run are usually ignored because the user is focused on getting to the app.

**Comment by joa** [comment]
Alt-Shortcuts (or at least the subset I am used to) are working without additional configuration in Terminal.app -- as well as the unicode input mode. 

Seems like there is some middle ground?

**Comment by kovidgoyal** [comment]
I dont see how that's possible. In terminal.app run cat and type option+a you will either get a with a little circle on top or ^\a (which is alt+a) depending on the value of the setting "Use Option as meta key" in the terminal.app preferences under keyboard
