### ISSUE TITLE
Problems with certain emojis

### ISSUE THREAD

**Issue by rightaway** [kovidgoyal/kitty#875]
When I paste emojis into the terminal and delete them it mostly works fine, but with some emojis like the flag emojis (like 🇦🇫 🇦🇽 🇦🇱 🇩🇿 🇦🇸) pasting it pastes extra space characters, and trying to delete them results in some strange display issues, and having to press delete multiple times to delete a single emoji, and then I can't get to the beginning of the line to delete everything.

**Comment by kovidgoyal** [comment]
This is likely caused by issues in your shell not kitty. Try running cat and then pasting your flag emojis and deleting them, they will work fine. If not let me know.

**Comment by maximbaz** [comment]
It is reproducible in cat:

![peek 2018-09-06 13-09](https://user-images.githubusercontent.com/1177900/45153950-25cb5380-b1d6-11e8-869f-e36dfb072dfe.gif)

**Comment by kovidgoyal** [comment]
OK I'll take a look at it when I have a moment

**Comment by rightaway** [comment]
@maximbaz Thanks for double checking. How did you take that screen video?

**Comment by maximbaz** [comment]
Using https://github.com/phw/peek, but be aware of this bug https://github.com/phw/peek/issues/331

**Comment by Luflosi** [comment]
I can also reproduce this bug. I think the unicode flag symbols consist of two special unicode characters next to each other. This would explain, why it's possible to press backspace twice and why there is a weird character when pressing backspace once.

**Comment by kovidgoyal** [comment]
Yeah I looked at it, its not realy a bug. flags are two unicode symbols. So when you pres backspace one of them get deleted, leaving the other behind. Sadly the unicode committee did not make flags combining symbols so that is expected behavior.

**Comment by maximbaz** [comment]
Pressing backspace twice is understandable, but see my gif, I cannot get rid of (A) emoji no matter how many times I press backspace

**Comment by kovidgoyal** [comment]
OK I'll open it again, this looks like its going to go on all night :)

**Comment by Snuggle** [comment]
This happens with other emojis too. It causes a ton of issues when needing to use emojis in a terminal. I can't backspace either, and some of the emojis don't actually exist.

**Here's a recording**
[![asciicast](https://asciinema.org/a/6mVmTSoY3DrnnuEUeYg1rZ3Pt.png)](https://asciinema.org/a/6mVmTSoY3DrnnuEUeYg1rZ3Pt)

**Comment by kovidgoyal** [comment]
@Snuggle like I said initially, dont use a shell. Different shells have widely arying support for emoji. Try to reproduce the problem in cat. Flags are not emoji and have special problems. As far as I know all actual emojis work fine in kitty.

**Comment by kovidgoyal** [comment]
Works fine for me in vim. But sure, I can probably look into making the erase_char operation detect wide characters and act intelligently on it. I just hope doing that does not screw it up in vim. Probably have to make it zero both cells and then move one cell back. That should work in both cat and vim.

**Comment by maximbaz** [comment]
The issue with flag and fist emojis is fixed on master, thanks 😉 

I was wondering if in 7f0674a you should have removed removed *all* wide characters before the cursor, no only one wide character before the cursor.

------------

Also if you are not sick of emojis yet, can you have a look at these ones?

- `👨‍👦` (`U+1F468, ‍U+200D, U+1F466`) - kitty requires pressing backspace *twice* even though there is a joiner
- `👨‍👧‍👦` (`U+1F468, ‍U+200D, U+1F467, ‍U+200D, U+1F466`) - similarly requires 3 times to press backspace

**Comment by kovidgoyal** [comment]
Why would I want to remove all wide characters? Pressing backspace once should remove one wide character, not all of them.

kitty does not support joiners beyon treating them as basic combining characters.

**Comment by blahgeek** [comment]
Commit 7f0674a breaks backspace for unicode characters in NeoVim for me:

With content “你好” in neovim, pressing backspace once would delete two instead of one character.

**Comment by kovidgoyal** [comment]
Still works in vim. This is what I was basically afraid of. There is no standard that I can find about what backspace is supposed to do with wide characters. Which means that no matter what choice I make, something will not work. 

Presumably neovim expect the terminal to do what kitty did before this patch. I'm not sure how vim is able to handle both behaviors, probably it manages cursor position manually when dealing with wide characters to get around differences in terminal behavior.

Maybe @justinmk would like to comment on what neovim does.

**Comment by toonn** [comment]
Hmm, is this an instance of the same issue? Running cat (in fish, in kitty, on mac os). I insert an emoji 😄, then backspace, then insert another 🎄, the smiley remains visible, only when pressing enter the christmas tree becomes visible on the next line.

**Comment by kovidgoyal** [comment]
yeah cat is dumb, so it will never know how to backspace emoji
