### ISSUE TITLE
Missing dependency on README

### ISSUE THREAD

**Issue by lfmet** [kovidgoyal/kitty#88]
Trying to compile kitty got me an unsupported function `ARB_texture_buffer_object_rgb32`. Which is only available on OpenGL 4.0 (at least on [nvidia](http://docs.nvidia.com/tegra-graphics-debugger/2.4/content/developertools/mobile/tegra_graphics_debugger/tgd_supported_functions.htm) (and my hardware only supports 3.3 :disappointed:))

**Comment by kovidgoyal** [comment]
That function is in opengl 3.2 written in 2009 

https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_buffer_object_rgb32.txt

**Comment by lfmet** [comment]
I read this too, but I'm confused:
- `File "./kitty/main.py", line 205, in run_app
    glewInit()
RuntimeError: The OpenGL driver on this system is missing the required extension: ARB_texture_buffer_object_rgb32`
- `OpenGL renderer string: GeForce 8400GS/PCIe/SSE2`
  `OpenGL version string: 3.3.0 NVIDIA 340.101`
- [This](http://rastergrid.com/blog/2010/03/a-brief-preview-of-the-new-features-introduced-by-opengl-3-3-and-4-0/comment-page-1/) link citing this extensions as a new feature to OpenGL 4.0 (plus my nvidia link).
- [This](https://khronos.org/registry/OpenGL/specs/gl/glspec40.core.pdf) official document on page 424, says that this extension is a `new feature`.

**Comment by kovidgoyal** [comment]
Who knows, OpenGL is an enormous clusterfuck. I go by the khronos registry.
