### ISSUE TITLE
Iosevka ligations are misaligned

### ISSUE THREAD

**Issue by hauleth** [kovidgoyal/kitty#882]
It looks like this:

![zrzut ekranu 2018-09-06 14 56 16](https://user-images.githubusercontent.com/291639/45158697-0d166a00-b1e5-11e8-92ab-1e12316b201e.png)

While in iTerm2:

![zrzut ekranu 2018-09-06 14 57 03](https://user-images.githubusercontent.com/291639/45158729-2ae3cf00-b1e5-11e8-8806-73eebced636d.png)

**Comment by kovidgoyal** [comment]
dup of #298
