### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by skrat** [kovidgoyal/kitty#883]
It would be nice to have the ability to open multiple OS (Linux) windows within one kitty process, to save on (shared) resources and most importantly: improve startup time for tiling window managers. Is this possible?

**Comment by maximbaz** [comment]
Of course, use `kitty -1`, first load will be slow, consequent instances will open instantly.

**Comment by kovidgoyal** [comment]
kitty --help (see --single-instance)
