### ISSUE TITLE
osx kitty.dmg: NameError: name 'highlight_collection' is not defined` when running diff

### ISSUE THREAD

**Issue by shanmuha** [kovidgoyal/kitty#895]
Thanks for a wonderful terminal emulator!

I have installed kitty from the 0.12.0 release dmg and I am getting this error when running  the diff kitten:
`NameError: name 'highlight_collection' is not defined`
as I understand from https://github.com/kovidgoyal/kitty/issues/863, this is because pygments is missing. I do have pygments installed in my normal python 3, but I think kitty installed from dmg uses its own python - how get pygments into there? 

Happy to help, if I know what to do!

**Comment by shanmuha** [comment]
I did try using `kitty +launch` to install pygments using its setup.py, but got an error about missing setuptools, tried to install pip using get-pip.py and that resulted in a dynamic library error.

**Comment by kovidgoyal** [comment]
This is a bug in the macOS kitty build, it will be fixed in the next release.
