### ISSUE TITLE
Solarized colorscheme?

### ISSUE THREAD

**Issue by peterdemin** [kovidgoyal/kitty#897]
Hi, the only thing that stops me from using Kitty is Solarized color scheme. I am used to it and configured my iTerm to use it. Is it possible to make Kitty use the same colors?

**Comment by SolitudeSF** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#color-scheme

**Comment by egmontkob** [comment]
The light version is incorrect, see https://github.com/altercation/solarized/issues/382.

**Comment by SolitudeSF** [comment]
Oops, fixed it. That repo was the first result yielded by search.

**Comment by peterdemin** [comment]
Thanks! Worked like a charm!

**Comment by skarnl** [comment]
Just wanted to thank you for referring to http://terminal.sexy
Great site to port your custom color scheme (from iTerm2) to the correct Kitty scheme (the `alacritty` export worked the best for me) 👍

**Comment by mhalano** [comment]
The dark version has a slight problem not related to Kitty, but worth mention it: https://github.com/zsh-users/zsh-autosuggestions/issues/416

**Comment by almereyda** [comment]
This is the Terminator solarized color scheme, in case anyone is interested:

```
background              #171717
foreground              #737373
cursor                  #93a1a1

selection_background    #81908f
selection_foreground    #002831

color0                  #1c353c
color1                  #8a3630
color2                  #5e6a00
color3                  #776301
color4                  #346289
color5                  #86375f
color6                  #336e69
color7                  #959289
color8                  #192e35
color9                  #82431f
color10                 #485358
color11                 #505a5f
color12                 #5f6768
color13                 #545582
```

**Comment by Sleepful** [comment]
Is there any way in which we could change the color scheme with a keybinding?

**Comment by Luflosi** [comment]
`map ctrl+s remote_control set-colors -a "/path/to/theme.conf"`
Where `theme.conf` could for example be a file from https://github.com/dexpota/kitty-themes.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-change-the-colors-in-a-running-kitty-instance

**Comment by TornaxO7** [comment]
For anyone who just wants to copy + paste the settings for a solarized-light-kitty setup, I just created a [gist](https://gist.github.com/TornaxO7/76654bd2769489ee1fccba71cd3d9bf9) with the settings.
