### ISSUE TITLE
Crash when disconnecting an external monitor where kitty is full screen

### ISSUE THREAD

**Issue by zenazn** [kovidgoyal/kitty#898]
Mac 10.13.6
Custom kitty build @ `d6b70f10d39dd0aee9998339762fb1f78d7df910` (no modifications to the source tree)

I have an external monitor, which I have kitty full-screen on (using `toggle_fullscreen`). When I disconnect the external monitor, kitty reliably crashes ~immediately (kitty does not need to be in the foreground / visible on screen)

**Comment by kovidgoyal** [comment]
no followup

**Comment by zenazn** [comment]
Oops—sorry! Didn't have access to my external monitor at work over the weekend:
https://gist.github.com/zenazn/350537fc43d2d1b51017c2f297d8b177

**Comment by kovidgoyal** [comment]
Hmm looks like an object lifetime issue in glfw's cocoa backend, probably related to https://github.com/glfw/glfw/issues/1251

To be clear, it only happens if the window on the external monitor is fullscreen?

**Comment by zenazn** [comment]
Yeah, that's correct. If the kitty window is on the external monitor as a normal free-floating window, it won't crash when unplugging the external monitor

**Comment by kovidgoyal** [comment]
OK, so as I noted int eh commit, I have chaged the way full screening is done in kitty on macOS, so hopefully it fixes it.
