### ISSUE TITLE
Locale inconsistency on macOS

### ISSUE THREAD

**Issue by jhenahan** [kovidgoyal/kitty#90]
OS: macOS 10.12.6 Beta (16G16b)

In iTerm 2 and Terminal.app, `locale` reports
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```
In Kitty, `locale` reports

```
LANG=
LC_COLLATE="C"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I don't have the variables set explicitly in my shell config, so that may be normal. The weird part is that kitty seems to silently default the locale to `ru_RU`, leading to (for instance) `git status` reporting

Kitty:
```
На ветке master
Ваша ветка обновлена в соответствии с «origin/master».
нечего коммитить, нет изменений в рабочем каталоге
```

iTerm and Terminal.app:
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

English is set to my primary system language in OS X preferences, though I do also have Russian as a secondary language. Removing the secondary language or explicitly setting the `LC_MESSAGES` variable to anything other than the empty string resolves the issue, but it does seem a bit mysterious.

**Comment by kovidgoyal** [comment]
Hmm, I'm not really familiar with how locale() works on macOS. The only locale related thing kitty does is call locale.setlocale(locale.LC_ALL, '') in main.py at startup. I'm not sure what, if anything, it could be doing differently.

**Comment by kovidgoyal** [comment]
So if you dont have the locale env vars set in your environment, I assume the other terminals are setting it explicitly. For example in iTerm2: https://github.com/gnachman/iTerm2/blob/faf3b633cee9d8749ca2f02a5b3226af4f93411f/sources/PTYSession.m#L1656

It seems wrong to me that a terminal emulator should set local environment variables...

**Comment by jhenahan** [comment]
Yeah, that seems sensible, it just seems odd that the unset variables are defaulting to a secondary language rather than the primary language. It seems to suggest that macOS is setting `LANG` according to the secondary language, but then Terminal.app has the primary language, which seems bizarre.

**Comment by kovidgoyal** [comment]
Maybe the solution is, on macOS, to check if the LANG env var is set and if not set it based on the OS language preferences.
