### ISSUE TITLE
Broadcast input?

### ISSUE THREAD

**Issue by newhook** [kovidgoyal/kitty#902]
iterm2 has "broadcast input" mode where keystrokes are "broadcast" to all panes (terminals) in a given window (or to a selection of terminals).  I personally find this indispensable when working on multiple replicas (think 60 remote machines where I need to run identical commands) when I don't want to use fabric or similar. Any plans to add support for this?

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/remote-control.html (in particular send-text) You can open a kitty shell and use it without even needing to turn on remote control.

**Comment by boweeb** [comment]
For anyone late to the party, the `broadcast` kitten is a more usable method than having to invoke `send-text`for each statement.

https://sw.kovidgoyal.net/kitty/remote-control.html#broadcasting-what-you-type-to-all-kitty-windows

Note, the behavior is not quite the same.  Input with the `broadcast` kitten is sent to _all_ windows, in _all_ tabs.  It also commandeers the active window for the input.  Honestly, I think this is pretty awkward.  The behavior of `iTerm2` is much more akin to `synchronize-panes` with `tmux` and I believe far more useful.

**Comment by kovidgoyal** [comment]
No, you can configure which window(s) the input goes to. And you can
open it in a new window, so it doesnt commandeer the current window, if
you prefer.

**Comment by replay111** [comment]
Also I just noticed that this broadcast does not send Backspace command so if you make typo there is no way to delete and fix... at least I did not find it - just starting with Kitty ;-)

**Comment by kovidgoyal** [comment]
This should fix it: https://github.com/kovidgoyal/kitty/commit/d3d3e99979a63e73534651aecd912087518b6807
