### ISSUE TITLE
Cursor sometimes disappears on macOS when Kitty is open

### ISSUE THREAD

**Issue by jyc** [kovidgoyal/kitty#903]
Kitty appears to cause my cursor to sometimes disappear on macOS. I'm running macOS High Sierra 10.13.6. I would look into debugging this myself because kitty is so great, but I figured someone else might have a better idea of what could be going wrong. Let me know if you need any more information about my system.

**Comment by kovidgoyal** [comment]
If you mean mouse cursor it is deliberate and can be turned off in kitty.conf (mouse_hide_wait)

**Comment by jyc** [comment]
Interesting, that does seem to fix it! Thanks for the prompt reply and for the very nice software.

**Comment by evanheller** [comment]
For me, the unexpected behavior is that the mouse cursor will disappear when the mouse is hovered over a Kitty window that is not in focus. Unlike when Kitty has focus and moving the mouse causes the cursor to reappear, if it is not in focus, the cursor will remain hidden until you move outside of the Kitty window. I was expecting mouse_hide_wait to apply only when Kitty has the focus (or only when actually typing within the window).

**Comment by Luflosi** [comment]
Which version of kitty are you using? This should be fixed in the latest version.

**Comment by evanheller** [comment]
It must have been 0.13.3--it is indeed fixed in the latest version. Thanks!
