### ISSUE TITLE
Minimum supported version of MacOS is not documented

### ISSUE THREAD

**Issue by inferiorhumanorgans** [kovidgoyal/kitty#904]

**Comment by kovidgoyal** [comment]
It is documented in the plist file of the kitty app bundle. If you try to run kitty on earlier versions of macOS the OS should give you a nice error message. Given that Apple actively discourages apps from maintaining backward compatibility on their platforms, this is about the level of effort I am willing to put into documenting it.

**Comment by inferiorhumanorgans** [comment]
> You want to build kitty without even running it once? 

Well, yes.  It is not clear what versions of OSX kitty supports and not clear why the pre-compiled binaries are limited.  So, yes, I attempted to build kitty to determine if there was a hard or soft dependency.
