### ISSUE TITLE
Missing key strokes

### ISSUE THREAD

**Issue by simontretter** [kovidgoyal/kitty#905]
Kitty seems to miss key presses randomly when typing too fast on my installation. 

Same sentence typed in Kitty:
"Kittyseemstomiss key presses radomly whentyping to faston my installaon."

kitty -v
kitty 0.12.0 created by Kovid Goyal

Running on Wayland / Gnome 3.28

**Comment by kovidgoyal** [comment]
Turn off IME. Run kitty like this:

GLFW_IM_MODULE=none kitty

IME on linux has this crazy design where key strokes go to a separate process over DBUS and are then returned to the application. This introduces tons of latency and potential for missed keystrokes.

**Comment by marco-fp** [comment]
Could you point a way of executing kitty from the .desktop file with this variable? 
Thanks :)

**Comment by kovidgoyal** [comment]
https://wiki.archlinux.org/index.php/desktop_entries#Modify_environment_variables
