### ISSUE TITLE
Missed keystrokes

### ISSUE THREAD

**Issue by aftersomemath** [kovidgoyal/kitty#906]
System: Ubuntu 18.04 (Fresh install)
Kitty Version: Binary release of 0.12.0 and built from source

On my system keystrokes are being dropped randomly. The effect can be easily seen when typing quickly. It can be easily reproduced at speeds of at least 80 wpm.

The attached screenshot shows the result of the typing "the quick brown fox jumped over the lazy dog" in kitty and gnome-terminal. I repeated the test several times to make sure it was not due to typing errors.

![image](https://user-images.githubusercontent.com/6125615/45199373-44af0180-b239-11e8-9616-0cf01649784b.png)

**Comment by kovidgoyal** [comment]
dup of #905

**Comment by aftersomemath** [comment]
Just found #905
