### ISSUE TITLE
Not writing certain characters then typing

### ISSUE THREAD

**Issue by marco-fp** [kovidgoyal/kitty#907]
When I type at a normal pace, some characters won't show up. 
If I type slowly every character it will be written correctly.

**System Information:**

- OS: Ubuntu 18.04.1 LTS
- DE: Gnome 3.28.2
- CPU: Intel® Core™ i7-8650U CPU @ 1.90GHz × 8 
- GPU: Intel® UHD Graphics 620 (Kabylake GT2)
- RAM: 16GB

**Comment by kovidgoyal** [comment]
dup of #905
