### ISSUE TITLE
Thick underlines

### ISSUE THREAD

**Issue by khrt** [kovidgoyal/kitty#908]
It would be nice if there would be a way to configure thickness (or even style) of underlines in kitty.
Also underlines in iTerm2 are under the text, while in kitty it over it.

Here is the example of how it looks in iTerm2 and kitty.

![iTerm2 on the left, kitty on the right](https://user-images.githubusercontent.com/736103/45201297-13ecbd80-b275-11e8-9e92-0f393ff2d754.png)

**Comment by kovidgoyal** [comment]
The thickness and position of underlines comes from the font. I'm not interested in overriding that, since there is no good way to override it that works across all fonts and all font sizes. But if you have such a way in mind, patches are most welcome.

**Comment by jrnkng** [comment]
I'm very happy with kitty but the thick underline is frustrating. If it is something related only to the font, why is it that in all my other terminals the underline looks much better?

**Comment by jrnkng** [comment]
@khrt Did you figure out a way to reduce to the thickness?
