### ISSUE TITLE
Fonts are not shown properly when displayed on an external monitor directly attached to Macbook Pro

### ISSUE THREAD

**Issue by soumyadipdm** [kovidgoyal/kitty#909]
Two of my external monitors (HP Zdisplay, resolution 1920x1200) are directly attached to my Mackbook Pro (spec below)
```
OS: High Sierra v10.13.6
MacBook Pro (Retina, 13-inch, Mid 2014)
Processor: 2.6 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel Iris 1536 MB
```
When the terminal is displayed on any of the external monitors, the fonts look blurry and weird (pic below). It does not happen when the terminal is placed on the Retina display of the Macbook. I have tested with all of the popular monospace fonts e.g Source Code Pro, Menlo, DejaVu Sans Mono, SF Mono etc. at 12pt size and the results are same.

![screen shot 2018-09-07 at 12 06 32 pm](https://user-images.githubusercontent.com/9334127/45202464-bc5f4980-b296-11e8-87bf-304a948241d6.png)

And here's Iterm2 v3.2.0 displaying the same text with same font (SF Mono 12pt) on the same monitor without any issue.

![screen shot 2018-09-07 at 12 06 46 pm](https://user-images.githubusercontent.com/9334127/45202534-f16b9c00-b296-11e8-8e6e-9548ff8caf92.png)

Here's my Kitty (v0.12.0) config: https://gist.github.com/soumyadipdm/62960fa3bda44fcfa888019c620f4506

Please advise!

**Comment by kovidgoyal** [comment]
dup of #214
