### ISSUE TITLE
Long tab titles leaking under their siblings

### ISSUE THREAD

**Issue by helb** [kovidgoyal/kitty#91]
I just noticed something odd when running an update on a remote machine – the second tab (*"[mosh] Jobs: 4 of 7 … 6.16, 3.90"*) kind of leaks under the 3th and 4th:

![kitty-2](https://user-images.githubusercontent.com/178133/28115329-c5fa0090-6704-11e7-9041-911b93f1751a.gif)

It seems to be reproducible with just creating a directory with a stupid long name and `cd`ing into it:

```
mkdir tmp/oh-this-shit-is-really-long-oh-my-god-nobody-does-that
cd tmp/oh-this-shit-is-really-long-oh-my-god-nobody-does-that
```

![kookaburra_20170712_132229](https://user-images.githubusercontent.com/178133/28115464-64dcb086-6705-11e7-9201-42120e16c5ea.png)

I guess one possible solution might be just trimming the title after some (configurable?) length. Few people probably want the tab title to take up half of the monitor width. :)

---

Kitty version: 62db44c 
Window manager: i3 4.13-89-g9178c5b8
Shell: ZSH 5.3.1

**Comment by kovidgoyal** [comment]
I'll take a look at it when I have a moment.

**Comment by helb** [comment]
Hmm, maybe there's something wrong with my graphics drivers or something, i just got this (on a different computer though, but both with intel graphics):

![magpie_20170713_124032](https://user-images.githubusercontent.com/178133/28162788-9cb253bc-67c8-11e7-911a-2374eadd79ed.png)

**Comment by kovidgoyal** [comment]
I can reproduce your original problem (which occurs when the window is too small for all tab titles to fit) but the other one definitely looks like some kind of problem with the graphics driver. You can try running with --debug-gl which will check all OpenGL calls for errors (it will slow things down but may print something useful to stderr)
