### ISSUE TITLE
Fast Full Screen Mode.

### ISSUE THREAD

**Issue by jordwalke** [kovidgoyal/kitty#911]
Kitty is all about the speed, but one thing that slows me down is entering Full Screen mode in OSX. It performs a (slow) OSX animation that gets in the way (and then ties you to a weird OSX desktop mode where switching to other apps is also slowed down via a pointless animation). Could Kitty have a "Fast Full Screen" mode that operates like MacVim or iTerm's full screen? It more or less instantly transitions to full screen and operates like a "normal app" in full screen mode.

**Comment by kovidgoyal** [comment]
I'm afraid I have no idea how to implement such a mode (those pointless animations come from the OS). But patches are welcome.

**Comment by erf** [comment]
@jordwalke see this answer: https://apple.stackexchange.com/questions/128717/how-to-disable-full-screen-animation-on-os-x-10-9
It shows how to 'reduce motion' in the settings.

**Comment by lhc70000** [comment]
I think jordwalke is talking about a "legacy full screen" mode. Basically it can be done by creating a boderless full screen window:
- adding `NSWindowStyleMaskBorderless ` and `NSWindowStyleMaskFullScreen ` the window style mask
- adding `NSApplicationPresentationAutoHideMenuBar` and `NSApplicationPresentationAutoHideDock ` to window presentation options
- setting the window frame to the same as the screen's.

**Comment by kovidgoyal** [comment]
My policy is to keep reports that dont have a clear path to implementation or that I dont think are particularly good ideas closed. In this case I am somewhat skeptical of the concept of using a deprecated technique for full screening windows. It's quite possible it will stop working in the future (apple seems to love breaking things with every new macOS release).

I am willing to merge a patch for it, but I dont particularly want to encourage anyone to do it.

**Comment by kovidgoyal** [comment]
It's certainly possible, but I am reluctant to do so because of #898 I really dont like having crashing bugs in my software, and because I dont have an external monitor and the problem is not in kitty code, it is hard fo rme to find any other way to fix it.

**Comment by kovidgoyal** [comment]
Well, I think I figured out how to solve the crashing issue, at least I hope so. So I have modified this patch to make it an option, defaulting to off
