### ISSUE TITLE
Layout, launch and closing

### ISSUE THREAD

**Issue by ptbrowne** [kovidgoyal/kitty#912]
I'm trying to go full Kitty and remove my tmuxinator configuration. One thing that "surprised" me was that when `launch`ing in the session config, if you ctrl+c the program that is launched, the window is closed. Is there a way to launch so that afterwards, if you ctrl+c the launched program you go back to the shell and not close the window ? This can be useful for example to restart a server (ctrl +c , arrow up, enter).

**Comment by kovidgoyal** [comment]
When you launch a program, that program runs, there is no shell to go back to. If you want to run a program inside a shell use something like

launch bash -c "program; bash"
