### ISSUE TITLE
trouble building kitty on MacOS El Capitan 10.11.6

### ISSUE THREAD

**Issue by cameron-simpson** [kovidgoyal/kitty#914]
Had a little trouble building kitty on El Capitan. I'm attaching a diff of the hacks I made to make it happy. In short the issues seem to be:

- no <os/log.h> include file and corresponding os_log() function

- missing #define NSEventTypeKeyDown NSKeyDown to match existing one for NSEventTypeKeyUp

- the test for MAC_OS_X_VERSION_MAX_ALLOWED < 101200 may be a bit conservative

I'll attach the diff in a sec...

Cheers,
Cameron SImpson

**Comment by kovidgoyal** [comment]
kitty requires macOS 10.12 at a minimum. I'm afraid I am not interested in supporting older macOS versions.

**Comment by cameron-simpson** [comment]
[kitty-hacks-diff.txt](https://github.com/kovidgoyal/kitty/files/2360464/kitty-hacks-diff.txt)

**Comment by cameron-simpson** [comment]
Ok. I've attached the (very small) diff anyway. Run your eye over it and discard it if you wish. Thanks, Cameron

**Comment by kovidgoyal** [comment]
thanks, it will come in handy for people that want to run kityt on old macOS, however, I am not going to officially support running on < 10.12
