### ISSUE TITLE
very long path display wrong

### ISSUE THREAD

**Issue by XiaoDianDi** [kovidgoyal/kitty#915]
When I use kitty to cd a very deep directory, the information of PS1 and path will display wrong like the snapshot.
![image](https://user-images.githubusercontent.com/10094017/45210927-7ec4e580-b2c3-11e8-882b-719b36be8924.png)
And you can see the snapshot, and the HOME path, display is right, when I cd a very deep directory, the display will mess.
Thanks

**Comment by kovidgoyal** [comment]
I'm going to need more information than that. A screenshot and a set of steps to reproduce, at a minimum.

**Comment by XiaoDianDi** [comment]
Sorry about it, hit the key by mistake.
Had update  information
Thanks for the reply.

**Comment by XiaoDianDi** [comment]
BTW, Kitty package from Debian.
Version kitty 0.11.3 created by Kovid Goyal

**Comment by kovidgoyal** [comment]
that is not something that is controlled by kitty, but by whatever shell you are running in kitty. I suggest using a PROMPT setup for your shell that truncates long paths.

**Comment by XiaoDianDi** [comment]
I still think this is the kitty issue, when I use kitty ssh to the server, and will not show the PSI color and new line set, and then the long path will mess.
Left is Gnome terminal, right kitty.
![image](https://user-images.githubusercontent.com/10094017/45211878-0dd2fd00-b2c6-11e8-8f5e-c662f0ae0296.png)
Open the vim then exit, will not clear vim, and the Ctrl+L not effect.
Only on my computer will ok, ssh login another will error.
Kitty native show like below.
![image](https://user-images.githubusercontent.com/10094017/45212110-a36e8c80-b2c6-11e8-9d24-108d30edfdcb.png)

Thanks.

**Comment by kovidgoyal** [comment]
Your need to install the kitty terminfo file on your server.

See https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

**Comment by XiaoDianDi** [comment]
Thanks a lot, I will have a try.
