### ISSUE TITLE
Support for direction of windows (left_window, right_window, up_window, down_window)

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#916]
Hi I was wondering if this support currently exists, or is something in the roadmap.
Coming from years of vim and other vim like tools, I have a habit with kitty_mod + {h,j,k,l} to select the window relative to where I am at. 

Is there any way of doing so?

**Comment by kovidgoyal** [comment]
It's not in the roadmap, but it is pretty trivial to implement, I might get to it someday. Personally, I would prefer a visual selector. Press a key see numbers/letters overlaid over the windows and pick the one you want.

In the meantime, patches are welcome, if you wish to work on this and you need guidance, feel free to ask, I will be happy to help.

**Comment by esn89** [comment]
Thanks for the quick reply.

For starters, which file should I start looking into for examples if I were to make a PR?

**Comment by kovidgoyal** [comment]
Just grep the code for next_window you would need to implement similar functions for left_window, right_window, etc

**Comment by esn89** [comment]
and to build the app/view my changes, it is simply:   make app?  and then run the binary that results?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/build.html

**Comment by esn89** [comment]
Thank you so much @kovidgoyal , you are the best!

**Comment by kovidgoyal** [comment]
you're welcome :)

**Comment by strix** [comment]
This is awesome! Any way you’ll extend this functionality to movement as well?

**Comment by strix** [comment]
Thank you!
