### ISSUE TITLE
Need a way to disable bracked paste

### ISSUE THREAD

**Issue by davideder** [kovidgoyal/kitty#920]
I understand that it is a great and needed security feature.

But it badly breaks applications not written for it.  For example, nano is completely unusable.

Would it be possible to have a config option or keyboard shortcut to enable/disable it?

**Comment by kovidgoyal** [comment]
Bracketed paste is off by default. Only if a terminal application sends the code to turn it on does it get turned on. Presumably you have turned it on in your shell/readline config, turn it off there and you will be fine.
