### ISSUE TITLE
Custom URL Patterns

### ISSUE THREAD

**Issue by coxley** [kovidgoyal/kitty#922]
Does `kitty` have support for custom URL patterns? I'm looking for a better alternative to terminator and the most productive feature for me is being able to do:

* Turn `T[0-9]+` into a clickable link going to internal ticketing system
* Turn `D[0-9]+` into clickable link going to internal code review system
* etc

I referenced the configuration guide first but it's quite extensive -- didn't see anything quite along these lines

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/hints.html
