### ISSUE TITLE
Feature request: maximize window

### ISSUE THREAD

**Issue by sirex** [kovidgoyal/kitty#926]
It would be really usefull to have `ctrl+shift+x` which would maximize current window to take all available space hiding all other windows. Pressing `ctrl-shift+x` again, previous layout with exactly same sizes would be returned back.

Some times you just need to focus on a single window and then go back to where you were.

I think this could be done with `map ctrl+alt+x goto_layout stack`, but there is no way how to get back to the previous layout and preserve all window sizes as they were.

**Comment by kovidgoyal** [comment]
dup of #870
