### ISSUE TITLE
disabling scrollback and forwarding mouse to terminal applications

### ISSUE THREAD

**Issue by slashfoo** [kovidgoyal/kitty#927]
Hey, I haven't been able to figure out how to use my mouse with kitty and vim or tmux. On other terminals, I would just be able to set mouse mode and it'd work, but with Kitty, the mouse wheel events are not forwarded to tmux or vim.

I tried setting scrollback_lines to 0, and also mouse_scroll_multiplier to 0; but I still can't get the events to the terminal&applications.

Is this supported? and if so, how may I set it up?

**Comment by kovidgoyal** [comment]
It works automatically. In vim you might need to add

```
set mouse=a
```

to force vim to turn on terminal mouse integration. No idea about tmux but it is likely similar.

**Comment by kendfss** [comment]
fwiw, the tmux setting is `set -g mouse on`
