### ISSUE TITLE
cd to current directory when spawning a new window

### ISSUE THREAD

**Issue by skorokithakis** [kovidgoyal/kitty#928]
When spawning a new shell/tab/window, most terminals will start in the directory the previous terminal was in. This is a big timesaver, because when I spawn a second window, it's usually because I want to do work in the directory I am currently in. Kitty doesn't do that right now, so I am forced to cd to the directory manually every time I start a terminal.

**Comment by kovidgoyal** [comment]
Use new_window_with_cwd See https://sw.kovidgoyal.net/kitty/conf.htmlfor details.

**Comment by skorokithakis** [comment]
Thank you, I had missed that. Maybe it should be the default.
