### ISSUE TITLE
Set tab name or window title automatically to the current directory or file

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#930]
Is there a way to set the tab name or window title to the current directory or file you are in as you move around?

I see you can set tab names and window titles using remote, but is there a way to listen to changes for which directory or file you are in? Could this be added as a kitty config setting to be set automatically?

I like to work with several tabs open and now they all say `bash`. I guess i could set the tab name as i open them but then it would stick if i change the folder. 

I'm on macOS, using kitty 12.1

**Comment by kovidgoyal** [comment]
You configure this in your shell https://stackoverflow.com/questions/10517128/change-gnome-terminal-title-to-reflect-the-current-directory

**Comment by freetz13** [comment]
In zsh it's done via `precmd () {print -Pn "\e]0;%~\a"}` in .zshrc

**Comment by blackieer** [comment]
> In zsh it's done via `precmd () {print -Pn "\e]0;%~\a"}` in .zshrc

I add your codes in my .zshrc but nothing's changed. 
What may I missed?
Thank you.

**Comment by freetz13** [comment]
> What may I missed?

- You use a terminal emulator other than kitty?
- You didn't restart it?

**Comment by blackieer** [comment]
> > What may I missed?
> 
> * You use a terminal emulator other than kitty?
> * You didn't restart it?

Thank for quick response.

- I installed other terminals, but at now, I am only opening kitty.
- I run `source ~/.zshrc`. May I do anything?

Thank you again.

**Comment by freetz13** [comment]
Try to close all instances of kitty and run it again. I have the exact same line in my .zshrc and it works perfectly.

**Comment by hrqmonteiro** [comment]
> In zsh it's done via `precmd () {print -Pn "\e]0;%~\a"}` in .zshrc

I put this in my `.zshrc` and all it shows as the title is `~`, always. No matter what i open in the terminal or what command i type.

**Comment by freetz13** [comment]
> I put this in my `.zshrc` and all it shows as the title is `~`, always. No matter what i open in the terminal or what command i type.

Look how it works for me: ![2021-01-08-11-50-46](https://user-images.githubusercontent.com/7419347/103964837-201c1900-51a8-11eb-8a5d-edc90a56b81f.png)

Also,

```
user@manjaro ~
> alacritty --version
alacritty 0.6.0 (04cbf767)
```

So I really don't know why you can't make  it work.

**Comment by freetz13** [comment]
> I put this in my `.zshrc` and all it shows as the title is `~`, always. No matter what i open in the terminal or what command i type.

OMG, I forgot that I've switched to Alacritty, sorry for that. But zsh in kitty works just fine too

![2021-01-08-12-11-44](https://user-images.githubusercontent.com/7419347/103966094-e698dd00-51aa-11eb-8f01-83dbd2215fd1.png)

```
user@manjaro ~ 
> kitty --version
kitty 0.19.3 created by Kovid Goyal
```

**Comment by 6801318d8d** [comment]
> You configure this in your shell https://stackoverflow.com/questions/10517128/change-gnome-terminal-title-to-reflect-the-current-directory 

Can I ask WHY it works?

In the Bash manual, `PROMPT_COMMAND` is [described as](https://www.gnu.org/software/bash/manual/bash.html#index-PROMPT_005fCOMMAND):

> PROMPT_COMMAND
> If this variable is set, and is an array, the value of each set element is interpreted as a command to execute before printing
> the primary prompt ($PS1). If this is set but not an array variable, its value is used as a command to execute instead.

So it looks like it is a command to be execute before the prompt is printed.

What is has to do with tab titles in kitty?

**Comment by 6801318d8d** [comment]
[Here](https://unix.stackexchange.com/questions/697699/kitty-terminal-tab-title-without-path) it says to use the `tab_title_template` kitty configuration variable BTW
