### ISSUE TITLE
Text Being Clipped

### ISSUE THREAD

**Issue by ibrokemypie** [kovidgoyal/kitty#931]
Hello, using kitty with monofur for Powerline my text is getting clipped at the bottom as shown in screenshots. Havent changed any options other than font.

![image](https://user-images.githubusercontent.com/7827846/45250844-58fd1680-b37f-11e8-92c1-a77b0960f444.png)

![image](https://user-images.githubusercontent.com/7827846/45250855-906bc300-b37f-11e8-82cf-b78c0d6f4f5a.png)

note the square brackets and g's and y's.

Kitty version 0.12.0
arch linux

**Comment by kovidgoyal** [comment]
That happens in the font does not have proper metrics. You can workaround it by using the adjust_line_height option in kitty.conf see https://sw.kovidgoyal.net/kitty/conf.htmlfor details.
