### ISSUE TITLE
[Request] Transparency blur

### ISSUE THREAD

**Issue by fosspill** [kovidgoyal/kitty#932]
Hi,
It would be great to see an option for blurring the elements shown through the transparency, like Konsole.

**Comment by kovidgoyal** [comment]
I'm afraid this is not something I am interested in, but patches are welcome!

**Comment by fosspill** [comment]
Fair enough. Would it be a hard thing to implement for someone who doesn't know much about opengl?

**Comment by kovidgoyal** [comment]
Its fairly complex. On platforms other than X11 such as macOS and wayland you cannot even get access to what is under the window for security reasons, so any blur transparency has to be done by the window manager. On X11 you have full access and you could do it yourself, but that does require some opengl knowledge.

**Comment by RaitaroH** [comment]
@fosspill 

I have this in my zshrc. Found it on reddit [here](https://www.reddit.com/r/kde/comments/6jzuwu/konsole_and_yakuake_blur/)
```
# Blur {{{
if [[ $(ps --no-header -p $PPID -o comm) =~ '^yakuake|kitty$' ]]; then
        for wid in $(xdotool search --pid $PPID); do
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
# }}}
```

**Comment by rahatzamancse** [comment]
Additional note for @RaitaroH's zshrc snippet. It only works with KDE.
Also, any way to get this with Gnome or picom?

**Comment by RaitaroH** [comment]
> Additional note for @RaitaroH's zshrc snippet. It only works with KDE.
> Also, any way to get this with Gnome or picom?

I am not aware, sorry.

**Comment by SamDc73** [comment]
> fosspill

Is this solutions still working ? because it's not on my KDE machine :(

**Comment by SilverBzH** [comment]
Is transparency blur available on Kitty since the last update ? Otherwise we should definitely re-open this issue. Even if @kovidgoyal is not the one who will implement it.

**Comment by kirill-martynov** [comment]
It's still not possible to add blur?

I'm on OS X using background_opacity, and I'm really missing blur feature

**Comment by kaem-e** [comment]
could it b possible to write an app that does this ouside of kitty perhaps ? especially for other apps like alacritty or neovide. Im aware of apps like micaforall on windows that achieve basically this

**Comment by jioyla** [comment]
I need it ,very very!!!!!

**Comment by mcurses** [comment]
What about a Pseudo Transparency (with blur) like the [background image](https://st.suckless.org/patches/background_image/) patch for the suckless terminal? It might be easier to implement than a real blur.
