### ISSUE TITLE
Add option to start maximized

### ISSUE THREAD

**Issue by skorokithakis** [kovidgoyal/kitty#935]
My preferred way of using the terminal is to have it maximized. Unfortunately, Kitty doesn't support this use case, the closest it has is "save last window position", which doesn't work well with multiple screens (if I open kitty on the second screen, it ends up on the third instead because of its size). It would be nice if there were an option for the window to start maximized instead of with a specific size.

**Comment by kovidgoyal** [comment]
Doesn't your window manager allow you to do this? Sinply match on kitty's WM_CLASS (see the --class kitty cmdline option) and create a rule to start all such windows maximized.

**Comment by skorokithakis** [comment]
It probably does, but it's much easier to sync kitty's config file across machines than the window manager settings, which might be across OS flavors or different OSes. Thanks for the implementation!

**Comment by devth** [comment]
How do you use this if you don't launch kitty from a terminal? e.g. I'm on macOS and launch the .app I downloaded from brew cask. Could this be a config file option?

**Comment by Luflosi** [comment]
Works for me but only if I open kitty by double click, cmd+o, Spotlight, `open -a kitty.app`, etc. but not via the command line.

**Comment by devth** [comment]
Thanks for confirming! Looks like I forgot to run `rcup` so my file wasn't in place yet. Works now! (I launch via Alfred).

**Comment by nyxar77** [comment]
yall know how to this but in `kitty.conf` i can't find anything about it

**Comment by EricDuminil** [comment]
@nyxar77 :

Setting too large a window seems to start Kitty maximized, at least on Cinnamon:

```
remember_window_size  no
initial_window_width  5000
initial_window_height 5000
```
