### ISSUE TITLE
`kitty @ set-colors` doesn't work with tab colors

### ISSUE THREAD

**Issue by autrimpo** [kovidgoyal/kitty#937]
Running kitty 0.12.1 on Void Linux, I noticed that when sourcing my color config using @ set-colors, the tabs did not change. Probably a variation of #623 ?

**Comment by kovidgoyal** [comment]
Works for me with

```
kitty @set-colors active_tab_foreground=red
```

**Comment by autrimpo** [comment]
I just tried a combination of {in,}active_tab_{fore,back}ground and the foreground ones work, but the background ones do not.
