### ISSUE TITLE
xterm-256color support

### ISSUE THREAD

**Issue by z0rc** [kovidgoyal/kitty#939]
This is followup to https://github.com/kovidgoyal/kitty/issues/879#issuecomment-419727436, but I think this should better go in separate thread, so things won't be mixed up.

I the light, that inclusion of xterm-kitty to ncurses database isn't a smooth run, maybe we can compromise on having kitty operational with `term xterm-256color`? I researched this topic, and AFAIK xterm-kitty is mostly about having protocol extensions as described in https://sw.kovidgoyal.net/kitty/protocol-extensions.html. Please correct me, if I'm wrong.

In my personal case, having my terminal operational in all cases on any remote server wins over additional extensions that kitty introduces.

For example, I can run konsole, iTerm2 or any libvte-based terminal with TERM=xterm-256color just fine, and AFAIK this is default TERM for them.

**Comment by kovidgoyal** [comment]
You should be able to run kitty with another TERM as well if you want. Some things will not work (some keys and bce which is used if you use a background color in vim). Try it and see. Note that vte's terminfo will probably be a closer match for kitty than xterms terminfo.
