### ISSUE TITLE
Resizing a transparent window makes it disappear on macOS

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#941]
When i try to resize a kitty window with `background_opacity 0.75` only the top bar is shown - the rest disappears. I'm on macOS using Kitty 0.12.1.

**Comment by kovidgoyal** [comment]
Works for me with macOS 10.14.6. Note that if you are ona  beta of 10.14 there are problems with it, see #887

**Comment by erf** [comment]
Strange. I'm also on `10.13.6 (17G65)`. I disabled the other options except `background_opacity`, but same result. Is there anything more i could try?

Here are some more stats:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Intel Iris Plus Graphics 640 1536 MB

**Comment by kovidgoyal** [comment]
Oh sorry I think I know what you meant. While the resize is in progress the window is not drawn. Yeah that is a limitation of glfw+cocoa see https://github.com/glfw/glfw/issues/1251 sadly I dont know of any way to fix it.

**Comment by kovidgoyal** [comment]
You'll notice the same thing with non-transparent windows as well, basically the contents of the window will not be drawn while the resize is in progress.

**Comment by erf** [comment]
Ah ok. No problem. Yes i see that, but with an opaque background, you are able to see the black background whilst resizing ( so a little better ).
