### ISSUE TITLE
Mouse selection with matching brackets

### ISSUE THREAD

**Issue by spl** [kovidgoyal/kitty#942]
One useful feature in iTerm2 is the ability to select everything starting with an open bracket (e.g. parenthesis `(`, square bracket `[`, or curly brace `{`) and ending with the appropriate closing bracket. It works by multiple clicks on the opening bracket. Handling multiple-line selection and nested brackets is important. Since the click is on the bracket itself, and (I would guess) one doesn't usually (double-)click on a bracket to select a word, the feature is intuitive and doesn't interfere with other forms of selection.

Is this currently possible in kitty, or would it be something to consider?

**Comment by kovidgoyal** [comment]
I'm not a fan of this kind of thing -- the behavior is not discoverable and is confusing if accidentally triggered. It is not robust in that if the closing bracket is of the screen the terminal emulator cannot match it.

In kitty, I prefer to handle these kinds of things by piping the screen contents to an external program -- one that is designed for this. You can use ctrl+shift+h to do that, or the new pipe facility I just added to master.

That said, I recognize that piping and then selecting the output is more cumbersome than just double clicking, so I wont refuse a patch to implement it, but it is not something I am interested in personally.
