### ISSUE TITLE
startup_session and "Failure to launch child: nvim"

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#943]
I'm trying to write a startup session for kitty, at the moment I have something like this:
```
layout vertical
launch zsh

new_tab test
cd ~/Documents/Projects
launch zsh
launch nvim
```

However, it is the "launch nvim" place that fails.  I get an error which looks like this:
https://i.imgur.com/NAovBkN.png

I did some searching on the issues and tried to add:
shell /bin/zsh --login  (i am using zsh too)
to my kitty.conf but that didn't seem to work.

Any help would be appreciated.

**Comment by kovidgoyal** [comment]
nvim is not in PATH. And this is the PATH in the environment kitty runs in, not the PATH in a shell inside kitty. Either fix PATH in the environment, create a symlink from /usr/bin/nvim to wherever nvim is or use an absolute path to nvim in the session file.

**Comment by esn89** [comment]
I'm a bit confused.  So there are two paths?

Because when I go:
`which nvim`
`/usr/local/bin/nvim`

when I echo my $PATH, I see the `/usr/local/bin`
How will I find the PATH kitty runs it?

**Comment by esn89** [comment]
@kovidgoyal 

I have added that and although it has loaded, it is behaving strangely saying that it cannot load one of my plugins.
```[deoplete] deoplete failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.```

Does this plugin need to be in the same PATH as well?

**Comment by kovidgoyal** [comment]
That plugin probably depends on something else in your environment. You should define your environment variables at the desktop level so all applications see them, not in your .zshrc file because then only the programs that are started through the shell will see them.

depending on exactly how you setup that environment you could do

launch zsh -c nvim

instead. But if, for instance you setup bits of that envronment in the interactive section of the rc file, it wont work.

**Comment by esn89** [comment]
Thank you for your speedy replies.
I will now look at setting environment variables at desktop level.  Since this is not a kitty issue anymore.

One last question before (related to kitty)

```layout vertical
launch zsh
launch /usr/local/bin/weechat

new_tab test
cd ~/Documents/Projects
launch zsh
launch zsh -c nvim```

I am able to set a tab name for the second tab that I created.  How can I set a name for the initial (1st tab) that starts up upon launch?

**Comment by kovidgoyal** [comment]
Start your session file with 
new_tab XXX

**Comment by esn89** [comment]
Thanks a million.
