### ISSUE TITLE
Completion issue

### ISSUE THREAD

**Issue by melMass** [kovidgoyal/kitty#946]
Hi

I'm trying to add completion to zsh with the following

```sh
kitty +complete zsh
```

but keep getting:
```log
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 104, in <module>
  File "kitty/__main__.py", line 95, in main
  File "kitty/__main__.py", line 55, in namespaced
KeyError: 'complete'
```

**Comment by kovidgoyal** [comment]
update kitty, completion is only available in 0.12

**Comment by melMass** [comment]
Thanks, so the brew cask is not up to date.
Here is the edited cask for anyone interested:

```ruby
cask 'kitty' do
  version '0.12.1'
  sha256 'adeb930ef7a42a6d839e343a386e378bf5f400bc11031cd94a553cc8cae16c6d'

  url "https://github.com/kovidgoyal/kitty/releases/download/v#{version}/kitty-#{version}.dmg"
  appcast 'https://github.com/kovidgoyal/kitty/releases.atom'
  name 'kitty'
  homepage 'https://github.com/kovidgoyal/kitty'

  app 'kitty.app'

  zap trash: [
               '~/.config/kitty',
               '~/Library/Preferences/kitty',
               '~/Library/Saved Application State/net.kovidgoyal.kitty.savedState',
             ]
end

```

**Comment by zylent** [comment]
#brew cask info kitty                                                                                                                                                     
kitty: 0.12.1
https://github.com/kovidgoyal/kitty
/usr/local/Caskroom/kitty/0.9.0 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kitty.rb
==> Name
kitty
==> Artifacts
kitty.app (App)

**Comment by zylent** [comment]
looks to have been updated.
