### ISSUE TITLE
anyone tested for windows?

### ISSUE THREAD

**Issue by ReSearchITEng** [kovidgoyal/kitty#947]
It's a python app, so, can it run in windows?
What setup is required besides the pip dependencies ?

**Comment by jordwalke** [comment]
Have you seen this very recent update to Windows 10 for a PTY-like infrastructure? https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by kovidgoyal** [comment]
Yeah that why I said currently, above. Once windows gets a pty it should be possible, in principle, to port any unix terminal emulator to it. Whether that actually gets done will depend on whether people are willing to do the work.

**Comment by jordwalke** [comment]
Are there any blockers to people actually working on this? The new PTY API isn't in the latest windows, but it's in the Creators version I thought. Also, isn't a lot of the work getting Kitty's rendering and build to work on Windows? (Things like menus, rendering, font management for Windows). Is all of that stuff a ton of work?

**Comment by kovidgoyal** [comment]
There are no blockers, people are welcome to work on it. Kitty has no menus and its build system is written in python, it should be trivial to port to using, say clang, on windows. The hard parts will be:

1) I have made various modifications/improvements to glfw especially related to keyboard handling, these will need to be ported to windows (See https://github.com/glfw/glfw/issues/1140)

2) Kitty uses unix idioms is its code a fair bit, things like file descriptors/poll/fork etc. that dont have direct windows equivalents, so the main lopp and I/O handling will likely need to have thir own windows implementations.
