### ISSUE TITLE
Remapping command+h on macos doesn't work

### ISSUE THREAD

**Issue by tbodt** [kovidgoyal/kitty#948]
A mapping such as `map super+h previous_window` doesn't override the system's Hide shortcut, so pressing command+h hides Kitty. There's probably some way around this, not too sure what it is.

**Comment by kovidgoyal** [comment]
I dont know of a way around it. As far as I understand cocoa key processing (and I am no expert) those shortcuts are intercepted by the OS before reaching the application.

**Comment by YellowKirby** [comment]
One way around this is to set up an app-specific keybinding in Preferences, which can override the default keybinding. I've moved the `Hide kitty` option to `hyper+h`, which lets me use `command+h` freely in `kitty.conf`:

![image](https://user-images.githubusercontent.com/1654019/45308680-e69f4a00-b4d6-11e8-8d94-0e2b1836d4de.png)

Some other potential options: https://apple.stackexchange.com/questions/101754/os-x-disable-cmd-h-or-hide-app-command

**Comment by tbodt** [comment]
iTerm manages to do it if you specify a custom key binding, which is why I said there's probably a way.

**Comment by kovidgoyal** [comment]
Well, I am happy to learn from iTerm if you can figure out what it does.

**Comment by kovidgoyal** [comment]
If you figure out how to do it, feel free to send a PR (assuming it requires jumping through only a reasonable number of hoops). In the meantime closing this issue.

**Comment by tbodt** [comment]
It turns out mappings for command+h do work in fullscreen, where the hide option in the menu is disabled. I normally work in fullscreen so that's good enough for me. For non fullscreen mode, manually removing the key equivalent on the hide menu item when command+h is mapped might work.

**Comment by kovidgoyal** [comment]
Hmm too much work at least for me. Patches welcome.

**Comment by gibfahn** [comment]
I use this to map "Hide Kitty" to something untypable, and then use Cmd-h in kitty shortcuts:

```bash
  if ! defaults read net.kovidgoyal.kitty NSUserKeyEquivalents | grep -q "Hide kitty"; then
    defaults write net.kovidgoyal.kitty NSUserKeyEquivalents -dict-add "Hide kitty" '~^$\\U00a7'
  fi
```

I find having it as a shell command I can run in my dotfiles makes it easy enough that a hack in kitty wouldn't be necessary.

**Comment by chancez** [comment]
Does anyone know to make it so we can map `cmd+hjkl` overall? I was able to use the workaround for `cmd+h` but, I still don't have `cmd+l` or `cmd+j` working (looks like `cmd+k` works already)

**Comment by page-down** [comment]
@liouk 

Any shortcuts that exist in the default configuration can be configured directly in kitty.conf. There is no need for these workarounds.

https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

For example, for `cmd+k`, you can bind to `no_op` if you want the key to be sent to the program in the window, or bind to any other action.

```shell
kitty -o "map cmd+k no_op" kitty +kitten show_key -m kitty
```

**Comment by liouk** [comment]
@page-down I can't get this to work. Even if I put in my `kitty.conf` the following
```
map cmd+k no_op
```

the key combo still clears the terminal ("Clear to Cursor Line"). Therefore the mapping I want to create,
```
map cmd+k neighboring_window up
```

doesn't work either. I also tried clearing all shortcuts first, but with no luck. Any suggestions?
