### ISSUE TITLE
Start session inside the current terminal

### ISSUE THREAD

**Issue by ptbrowne** [kovidgoyal/kitty#953]
When starting with `--session`, I want the session to start in the same OS window so that I don't have two Kitty terminals opened. Is it possible ?

**Comment by kovidgoyal** [comment]
Use remote control for that. https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by ronjouch** [comment]
> Use remote control for that. https://sw.kovidgoyal.net/kitty/remote-control.html

@kovidgoyal 👍, that makes sense. But then how do I `map` a key combination to a remote control "run"? Say for example I want to bind <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> to a work session that consists in two windows:

```
map kitty_mod+o kitty @ new-window --new-tab --tab-title "Work" && kitty @ new-window
```

But that doesn't work. I searched for "launch", "run", "eval", "command" in kitty.conf, without success.

**Comment by kovidgoyal** [comment]
Why do you need a key combination? Simply create a script with kitty remote control commands and run that.

**Comment by ronjouch** [comment]
> Why do you need a key combination? Simply create a script with kitty remote control commands and run that.

@kovidgoyal to not pollute my scrollback. But yeah the script option can work. Thanks for the fast feedback and thanks for kitty.
