### ISSUE TITLE
Unrecognized escape sequences ?

### ISSUE THREAD

**Issue by ptbrowne** [kovidgoyal/kitty#955]
When running Webpack with a progress bar : 

![image](https://user-images.githubusercontent.com/465582/45346305-25053980-b5a9-11e8-9999-2dfee1d02861.png)

I think the escape sequence is supposed to delete the line to redraw the progress bar ?

`[254 09:57:18.333034] [PARSE ERROR] Invalid character in CSI: 0x1b, ignoring the sequence`

**Comment by kovidgoyal** [comment]
that indicates that whatever library is used to draw the progress bar is broken, it's sending invalid escape codes. A CSI escape code is of the form:

```
<ESC>[<numbers or semi-colon or colon><alphabet>
```

The byte stream kitty is receiving contains a CSI code with an <ESC> in the middle. I'm not familiar with webpack, but I assume it is based on node so if you can track down whatever library it uses for terminal progress bars, I can take a look.
