### ISSUE TITLE
Enable changing of line height on the fly

### ISSUE THREAD

**Issue by idhx** [kovidgoyal/kitty#956]
It would be great to have optional keyboard shortcuts to change line height / column width on the fly, similarly to how font size can be changed. I use kitty with vim, and I like to increase the line height when editing prose (but not code).

The ideal solution would be a mappable function similar to change_font_size---perhaps change_line_height?

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but patches are welcome.
