### ISSUE TITLE
How should one detect that one is using Kitty

### ISSUE THREAD

**Issue by gibfahn** [kovidgoyal/kitty#957]
What is the best way to tell that the current program is running inside a kitty terminal?

For example, `vim-ghost` uses this to detect `iTerm` and `Terminal.app`:

https://github.com/raghur/vim-ghost/blob/a6d3785abbd696f0e78bb3eed9203fe888938b2f/rplugin/python3/ghost.py#L137-L142

```py
        elif sys.platform.startswith('darwin'):
            if os.getenv('ITERM_PROFILE', None):
                self.darwinapp = "iTerm2"
            elif os.getenv('TERM_PROGRAM', None) == 'Apple_Terminal':
                self.darwinapp = "Terminal"
            logger.debug(self.darwinapp + " detected")
```

I see that Kitty defines a `KITTY_WINDOW_ID`, but is that guaranteed to be defined?

**Comment by kovidgoyal** [comment]
yes, it is guaranteed to be defined. You can also query the terminal using escape codes which will work even over ssh. THere's the escape code for querying terminfo capabilities, in particular th TN capability which will return xterm-kitty

**Comment by gibfahn** [comment]
>THere's the escape code for querying terminfo capabilities, in particular th TN capability which will return xterm-kitty

I had a go but can't work out how to get that in a `printf`, something like `printf "\e]P;qPtST"`?

**Comment by kovidgoyal** [comment]
IIRC

```
printf '\eP+q544e\e\\'
```

note however that the terminal will respond with an escape code of its own that you have to process, details here: http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Device-Control-functions

**Comment by kovidgoyal** [comment]
To see the response you can use, you can use

```
kitty sh -c "printf '\eP+q544e\e\\'; read"
```
