### ISSUE TITLE
"kitty --version" should also print git commit hash when building with new commits since the latest version

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#959]
Currently `kitty --version` only prints the version number, even when there were new commits since the latest version tag during build time.
Would you accept a pull request that executes `git describe --abbrev=4 --dirty --always --tags` when building and uses the output as the version? This would print the tag name when the latest commit has a tag, else also the number of commits since the latest tag and a uniquely abbreviated git commit. If the working directory is dirty, it would also print `-dirty`.
This could also mean that you would not have to change the version number in the constants file every time you release a new version.

**Comment by kovidgoyal** [comment]
kitty --debug-config does that already, feel free to add it to --version as well. But I prefer to manage the version number manually.
