### ISSUE TITLE
opening scrollback in pager has incorrect history

### ISSUE THREAD

**Issue by newhook** [kovidgoyal/kitty#960]
I'm ssh'd into a remote session. Here are the lines at the top of my current window:

```
59949
61155
61789
62145
```

If I scrollback a few lines I get:

```
51705
53104
55870
56184
56354
5723
57823
57840
58402
58822
```

Pressing shift-ctrl-h I get a pager as expected:

However the line immediately before the 59949 isn't 58822, it is instead:
`unning]:\nruntime/debug.Stack(0xc4216a0f90, 0x1, 0x1)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ncustomerio/ui_api/serve.RealTimeout.func1.1.1(0xc421ee1b00, 0xc420032a80, 0xc4205c2ea0)\n\t/source/src/customerio/ui_api/serve/timeout.go:132 +0x12b\npanic(0xd89c40, 0x14912a0)\n\t/usr/` 

which was a line much further back in the history.

**Comment by kovidgoyal** [comment]
can you reproduce this without sshing? If not have you uploaded the kitty terminfo file to the server as described in the kitty FAQ?

**Comment by SolitudeSF** [comment]
my `scrollback_lines` is 5000. if i execute `seq 5200` if get this in `less` after scrolling 4 lines up 
![image](https://user-images.githubusercontent.com/10168645/45417529-05ded880-b68b-11e8-91c9-9948f506f5ef.png)
2 missing from numbers from `5000` are probably my prompt.

**Comment by newhook** [comment]
> can you reproduce this without sshing?

I'm trying to work out how to reproduce it. A simple test with cat didn't show the same issue (remotely or locally). I'll respond when I have more details.

> If not have you uploaded the kitty terminfo file to the server as described in the kitty FAQ?

Yeah, I did `kitty +kitten ssh <remote host>`

**Comment by kovidgoyal** [comment]
That's OK I think I figured out how to reproduce it.
