### ISSUE TITLE
Kitty starts out blank until I resize the window

### ISSUE THREAD

**Issue by nthapaliya** [kovidgoyal/kitty#962]
When I start a new Kitty window, it starts out completely blank. There's the regular terminal 'underneath' it, because I can type in commands and stuff, but the screen redraws once I resize and everything is back to normal

MacOS Mojave, kitty version 0.12.1

Quick gif demonstrating what I mean by "blank window"

![screen capture 9-12-18 3 55 54 pm mp4](https://user-images.githubusercontent.com/4131655/45455845-beb21100-b6a5-11e8-9058-708c45b1373b.gif)

**Comment by kovidgoyal** [comment]
dup of #887
