### ISSUE TITLE
Change mouse cursor color?

### ISSUE THREAD

**Issue by esell** [kovidgoyal/kitty#964]
Is there a way to change the mouse cursor color when inside of a kitty window?

I am on macOS running kitty 0.12.1, which is awesome btw, and when I place my mouse cursor over a window, the cursor remains black so it is almost impossible to see because my terminal has a black background. In other apps like iTerm the mouse cursor will change to white or whatever.

I have looked into the config file but haven't been able to find a place where this could be changed. Is it possible?

Thanks!

**Comment by kovidgoyal** [comment]
dup of #359
