### ISSUE TITLE
Strange unicode behavior

### ISSUE THREAD

**Issue by 2toxic** [kovidgoyal/kitty#966]
Unexpectedly, I could `cat` that file, but not view diff or even write unicode(russian) letters:
![image](https://user-images.githubusercontent.com/42947087/45528517-3fc5f100-b7e9-11e8-924e-5ec4cb07afed.png)

Description of above image:
1. I `cat` file
2. I tried to print `при`
3. I tried to print `при` and pressed space
4. `git diff` in another split

More strange bug is that font of russian letters changed, when I moved to another kitty window:
![image](https://user-images.githubusercontent.com/42947087/45528609-b8c54880-b7e9-11e8-8f18-e4a7841cae8f.png)

Other emulators show expected behavior

**Comment by kovidgoyal** [comment]
Works for me. Make sure you have setup your locale for UTF-8 properly. That mean having a LANG value of something like en_US.UTF-8 (the language part can be arbitrary, of course. And having the corresponding locale generated in the locale database.
