### ISSUE TITLE
How to map to commands ?

### ISSUE THREAD

**Issue by melMass** [kovidgoyal/kitty#968]
Is there a way to `map` to commands, aliases or program ?

```conf
map cmd+r launch ranger
```

like `new_window *args` does but in current session.

**Comment by kovidgoyal** [comment]
If you mean you want a keypress to type in ranger and press enter for you, you can use the send_text directive for that, see https://sw.kovidgoyal.net/kitty/conf.html for details

map ctrl+r send_text all ranger\r
