### ISSUE TITLE
Is it possible to support "if-shell" like tmux

### ISSUE THREAD

**Issue by wmonk** [kovidgoyal/kitty#969]
Tmux supports executing a shell command and changing behaviour based on the result. My current use case is used to switch between vim and tmux panes seamlessly. The binding in tmux config looks like:
```
bind-key -n C-h if-shell "$is_vim" "send-keys Escape \"[104;5u\""  "select-pane -L"
```

where you can see it tries to check if the current running shell is inside vim, and send the respective keys. Ideally I could do away with tmux and use native kitty panes - do you think this is/would be possible?

tmux docs:
http://man7.org/linux/man-pages/man1/tmux.1.html#MISCELLANEOUS

**Comment by kovidgoyal** [comment]
You can use remote-control https://sw.kovidgoyal.net/kitty/remote-control.htmlthere is no if-shell as such but using kitty @ls you can get all the data including what program is running where and write a script to emulate if-shell
