### ISSUE TITLE
Pseudo Transparency Support

### ISSUE THREAD

**Issue by coxley** [kovidgoyal/kitty#971]
I realize that `kitty` has real transparency support (providing your WM does). The problem with this is Compton has mixed results with tiling window managers, especially ones that allow tabbed-tiles. It's not well-supported these days either.

Would love to have something akin to other terminals that's a cheap "show me the wallpaper" background without interfering with programs like vim and the like.

**Comment by kovidgoyal** [comment]
Probably related to #163 

If #163 were implemented, it would be fairly trivial to have the background image be the wallpaer rather than a user selected image. CLosing in favor of that, since this is a subset.

**Comment by coxley** [comment]
@kovidgoyal: That's fair. I've a follow-up question that might solve my issue though. Do you know off-hand why a compositor on other terminal emulators leaves the vim background alone, where with kitty it's made transparent?

**Comment by kovidgoyal** [comment]
In kitty, transparency works by making the default background color transparent and leaving all other colors opaque. This allows you, for instance, to have solid background colors in prompts/status bar/etc. while still having most of the window be translucent. I am guessing you have setup vim to change the terminal default background color. Which is why it becomes translucent.

**Comment by coxley** [comment]
Ah! That's it. Would you be open to making a toggle for background color based on a WM_NAME substring match or regex?

**Comment by kovidgoyal** [comment]
Not sure what you mean by that.

**Comment by coxley** [comment]
Unless I'm missing something, can't find a way to set the vim `ctermbg` in a way that:
* Maintains the color
* Doesn't get turned transparent by `kitty`

Writing code with a transparent editor is extremely painful so surprised it hasn't come up. Was wondering if `kitty` could provide a configuration option to match on X11 `WM_NAME` for opacity behavior.

**Comment by kovidgoyal** [comment]
Use a solid color bg vim background theme. For example from my vimrc

```
set termguicolors
let &t_ut=''
hi Normal 		guifg=#f6f3e8 guibg=#242424
```

**Comment by coxley** [comment]
@kovidgoyal That's how I have it. Attaching video

![example](https://user-images.githubusercontent.com/8285973/45580959-f490fa00-b84b-11e8-843b-79d2334f8d7a.gif)

**Comment by kovidgoyal** [comment]
Works for me with wayland, I have never used X11 compositors so I cannot comment about those. Note that to run kitty with the wayland backend you have to use

KITTY_ENABLE_WAYLAND=1 kitty

**Comment by kovidgoyal** [comment]
Sadly I have no idea how to take a screenshot on wayland, so I cannot post photographic evidence, ut basically, the backround in vim is fully opaque, while the background in the shell is translucent.

**Comment by coxley** [comment]
Confirmed by running a `weston` instance inside an X11 window. That's a bummer. :slightly_frowning_face: This should be changed to an actual issue of X11 vs. Wayland behavior -- unless you've no interest in supporting that

**Comment by kovidgoyal** [comment]
As far as I know kitty does nothing differently with regards to transparency on X11 and Wayland. With translarency kitty basically does two things: request a sem-transparent window from the OS and write sem-transparent pixels into the openGl display buffer. I suspect the difference, whatever it is, is in a layer below kitty. Either glw or the display system/compositor itself. X11 compositors were always a bit of a hack. So yeah, this is not something I am interested in supporting, but if it can be addressed in kitty code and someone comes with a reasonable patch to make it work, I will consider merging.

**Comment by coxley** [comment]
Unfortunately I'm not familiar with this realm. I've updated the title and summary should someone else wander here. Care to re-open the issue?

**Comment by kovidgoyal** [comment]
Not really, sorry. My policy is only to keep issues open that have a reasonable path to implementation. In this case not only does the issue lack that, I am far from certain it is even an issue in kitty's codebase.

**Comment by coxley** [comment]
Eh, your project. Kills discoverability for future folks who might know what's up. Thanks for your responsiveness :)

**Comment by kovidgoyal** [comment]
IME leaving every issue open leads to the same effect in the long run and has additional downsides.
