### ISSUE TITLE
Pragmata Pro doesn't render correctly

### ISSUE THREAD

**Issue by baremetalfreak** [kovidgoyal/kitty#973]
Pragmata Pro characters are cut at the top, see attached screenshots from kitty and macOS terminal 
<img width="72" alt="kitty" src="https://user-images.githubusercontent.com/19686979/45586163-4c823c00-b8f2-11e8-8cfe-db799b64da85.png">
<img width="67" alt="macos terminal" src="https://user-images.githubusercontent.com/19686979/45586164-4c823c00-b8f2-11e8-9140-f85fefe55ca4.png">

Kitty Version 0.12.1 (0.12.1)

**Comment by kovidgoyal** [comment]
As far as I know pragmata pro is not really a proper monospaced font. You need to use the one with the mono suffix, see for example #557.

Also, you can always adjust the line height to fine tune it, if needed. There is a setting for it in kitty.conf.

**Comment by baremetalfreak** [comment]
It looks as if they were shifted couple pixeles to the top because not only are the glyphs cropped at the top, but the letters seem unnaturally lifted compared to the line itself.

**Comment by kovidgoyal** [comment]
Since this is a paid for font, i'm afraid I cannot debug it, I suggest you simply use the adjust_line_height option

**Comment by baremetalfreak** [comment]
Thanks. Build 0.827 of PragmataPro does not seem to have this problem.
