### ISSUE TITLE
[i3] broken startup notifications

### ISSUE THREAD

**Issue by facelesspanda** [kovidgoyal/kitty#976]
Hello,
I have noticed that kitty doesn't react handle startup notifications well. I understand that it [used  to](https://github.com/i3/i3/issues/3048), but here's what happened to me.

my kitty version is 0.12.1 (latest from master branch)
my i3 version is 4.15 (latest stable)

the command
```sh
 i3-msg "workspace 4;exec kitty;workspace 7"
```
resulted in kitty being open on workspace 7, not 4

To be noted that
```sh
 i3-msg "workspace 4;exec i3-sensible-terminal;workspace 7"
```
worked and opened `gnome-terminal` on workspace 4

---
Maybe some other factor in my kitty config plays, so [here it is](https://pastebin.com/q3XV8X1W)

**Comment by kovidgoyal** [comment]
Works fine for me with:

```
i3-msg workspace number 1; i3-msg exec "kitty --detach"; i3-msg workspace number 5
```

**Comment by facelesspanda** [comment]
Just as a follow up:

I installed a manjaro-i3 distribution and built kitty from master, and it works now, somehow.
I don't know what's different with my ubuntu setup, though

**Comment by hseg** [comment]
Just got bitten by this again on `kitty 0.35.2`:
```bash
i3-msg 'exec kitty --name test; [class="^kitty$" instance="^test$"] move scratchpad'
```
doesn't properly wait for kitty to finish starting up, causing the `move` command to have no effect. However, if I manually wait for kitty to start an run the `move` command separately, things work fine. My current workaround for now (based on https://unix.stackexchange.com/a/363204):
```bash
xprop -spy -root _NET_ACTIVE_WINDOW | \
while read -r line ; do
    if xprop WM_CLASS -id "${line##* }" \
        | sed -u 's/.*=//' \
        | grep -q '"test", "kitty"' \
        ; then break; fi
done
```
