### ISSUE TITLE
Allow opening file paths with mouse

### ISSUE THREAD

**Issue by chdsbd** [kovidgoyal/kitty#977]
Currently you can open urls using the mouse, as specified in the [docs][url-mouse] via the `open_url_modifiers` key. It would be nice to extend this to support opening file paths with the mouse.

[url-mouse]: https://sw.kovidgoyal.net/kitty/conf.html?highlight=url#mouse

**Comment by kovidgoyal** [comment]
File paths are not nearly as robust to detect. Lots of false positives and negatives. But you can do so using  the hints kitten. https://sw.kovidgoyal.net/kitty/kittens/hints.html which can be fine-tuned manually for the kinds of things you want to detect.

**Comment by merlinND** [comment]
I would like to update my config to support opening a few known file types with `kitty_mod + click` through the `hints` kitten.
In issue #452, I've seen examples of how to use `--regex` and map it to keyboard shortcuts.

How to map it to the same click action as the built-in URL opening?

**Comment by kovidgoyal** [comment]
The hints kitten is designed for keyboard usage not clicking.
