### ISSUE TITLE
New tab position

### ISSUE THREAD

**Issue by xiaket** [kovidgoyal/kitty#979]
Hi there,

From what I can see in `kitty/kitty/session.py`, when new tab is created, it goes to the end of the tab list: [line 35 in session.py](https://github.com/kovidgoyal/kitty/blob/1f63ff1d4109558545e6fb5047b0617e3916bca5/kitty/session.py#L35). Is it possible to add an option so this new tab can go to the right side of the current active tab?

For example, if we have three tabs:

```
[tab1] [tab2] [tab3]
```

If I'm currently working in tab1, I'd wish the new tab(`tab4`) will be positioned between `tab1` and `tab2`. This will save a lot of tab relocation for some people.

**Comment by kovidgoyal** [comment]
I am somewhat confused. Are you talking about tabs creted using a session file or new tab created via the keyboard shortcuts? If the latter, the relevant code is in tabs.py not session.py

**Comment by xiaket** [comment]
Cheers!
