### ISSUE TITLE
Hints issue

### ISSUE THREAD

**Issue by melMass** [kovidgoyal/kitty#980]
Hi Kovi,

I'm in love with your `hints` concept, really powerful
The issue I have is I cannot use `hints` to print to terminal/ I've used the `--program -` arg as in the sample conf and docs but it stills uses `open` (on OSX).

Do you know what is going on ?

```conf
map cmd+s              kitten hints --type path --program -
# MAC FIXES
map alt+left           send_text all \x1bb
map alt+right          send_text all \x1bf
map alt+shift+0x2f     send_text all \\
map alt+n              send_text all ~
map alt+shift+l        send_text all |
map alt+shift+l        send_text all |
map alt+0x17           send_text all {
map alt+0x1b           send_text all }
```

**Comment by kovidgoyal** [comment]
Works for me, on macOS, running kitty like this:

```
kitty -o 'map=x kitten hints --type path --program -'
```

Run pwd press the x key kitten is dsiplayed. Press the 0 key, to choose the output of pwd from the previous step and it gets inserted into the prompt when the kitten exits.

What shell are you using? Try it with vanilla bash or zsh and see if it works.

**Comment by melMass** [comment]
Yep it was my mistake.... 
I did not relaunch kitty between conf changes.. 🤦‍♂️
 
I realised that as `kitty --debug-keyboard` did run a shell with the updated conf. 
Is there info about how the conf is sourced ?

Also a quick question, I saw on #732 that you could create custom kittens. Does kitty have other python extensible parts ?

**Comment by kovidgoyal** [comment]
config files are sourced at startup. kittens are the only directly extensible parts. For other things yo uhave to modify kitty code, which is half python anyway.
