### ISSUE TITLE
"kitty_mod cmd" does not work on macos

### ISSUE THREAD

**Issue by bbtdev** [kovidgoyal/kitty#982]
Hello,

Planning to switch from iterm2, so installed kitty. I'm trying to use cmd instead of ctrl+shift
# kitty_mod ctrl+shift
kitty_mod cmd

but no success.

**Comment by kovidgoyal** [comment]
works fine for me. steps I tried;

1) Run kitty as kitty -o 'kitty_mod=cmd'
2) Press cmd+enter

a new window opens as expected.
