### ISSUE TITLE
Spawn new panel in existing `kitty`

### ISSUE THREAD

**Issue by spacekookie** [kovidgoyal/kitty#988]
Pardon me if this question has already been asked, but is it possible somehow to tell `kitty` (from inside `kitty`) to create a new window.

Background: the editor `kakoune` doesn't implement any panels/ layout itself and relies on it's wrapping tool to do so. Which means that if I could tell `kitty` from `kakoune` to spawn a new window with $X content, I wouldn't need a tmux anymore! :smile:

**Comment by kovidgoyal** [comment]
See https://sw.kovidgoyal.net/kitty/remote-control.html

**Comment by spacekookie** [comment]
@SolitudeSF Theoretically, but that didn't work for me yesterday when I tried it so I thought I'd go back one step and look at how it's generally possible :grimacing: 

But thanks @kovidgoyal. Sorry for having to open an issue for what's essentially inability to properly search >.<
