### ISSUE TITLE
htop displays garbled characters

### ISSUE THREAD

**Issue by ndench** [kovidgoyal/kitty#99]
I've just started using kitty, I'm using the default config from `/usr/lib/kitty/kittty/kitty.conf`. When using `htop`, it breaks something and displays some garbled characters like in the following screenshot.

![2017-08-01_10-48-11](https://user-images.githubusercontent.com/2062388/28804514-0e8571ee-76a7-11e7-8716-c74c03a5133d.png)

After exiting `htop` all the characters in my terminal display are garbled the same way:

![2017-08-01_10-51-42](https://user-images.githubusercontent.com/2062388/28804565-74d3fa2e-76a7-11e7-89fa-3a530256bd48.png)

Closing and restarting kitty fixes the problem but it's an annoying fix. I've tried using `top` instead and that works fine. Also `htop` works in other terminal emulators like `termite` and `alacritty`.

**Comment by kovidgoyal** [comment]
htop works fine in kitty for me, with default htop and kitty configs. Try deleting your ~/.config/htop/htoprc

Also check that running locale reports a proper UTF-8 locae on your system. From your screenshot it looks like htop is not using utf-8 output mode. 

And you dont need to restart kitty, simply run reset.
