### ISSUE TITLE
Firefox + Pass Selection

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#990]
I'm quite interested in this feature of Kitty: 
https://sw.kovidgoyal.net/kitty/conf.html?highlight=pass%20selection#shortcut-kitty.Pass%20selection%20to%20program

I've to made a mapping for it and decided to pass it to my browser "Firefox" on Mac.

Unlike Linux, Firefox isn't on my $PATH, rather it lives here: 
`/Applications/Firefox.app/Contents/MacOS/firefox`

When I try to press the hot key to give the selected text, that didn't work as it isn't in the PATH.  I then added that Firefox location to my $PATH and it said that only one instance of Firefox can run at any given time.

Any ideas on how to solve this?  I understand this is more of a Mac/Firefox issue than it is Kitty's.  I am just putting it other there as maybe a Kitty user has experienced this before.

**Comment by kovidgoyal** [comment]
What are you expecting firefox to do with the text passed to it? You can always use the --new-instance command line option to firefox to force the start of a new instance. Although at least on linux firefox will simply open the passed URL in a new tab in the existing instance. Maybe it behaves differently on macs, I dont know.

Note that if all you want to do is open URLs in a browser you can simply hold down ctrl+shift and click on the URL in kitty, or use the hints kitten https://sw.kovidgoyal.net/kitty/kittens/hints.html
