### ISSUE TITLE
iptraf-ng looks broken on kitty

### ISSUE THREAD

**Issue by terceiro** [kovidgoyal/kitty#993]
When using iptraf-ng, the UI looks very messed up. Running it on the same system in gnome-terminal or xterm just works.

![captura de tela de 2018-09-19 11-04-42](https://user-images.githubusercontent.com/30027/45772178-ddf7f380-bbfb-11e8-83d6-f655865c0fcb.png)
![captura de tela de 2018-09-19 11-04-24](https://user-images.githubusercontent.com/30027/45772180-ddf7f380-bbfb-11e8-987c-0c4e765de315.png)

**Comment by kovidgoyal** [comment]
You need to make sure your TERM env var is xterm-kitty and the kitty terminfo files are available on the machine you are sshing into if you are using ssh. See the kitty FAQ
