### ISSUE TITLE
pointer invisible in osx with black background

### ISSUE THREAD

**Issue by newhook** [kovidgoyal/kitty#996]
I find the pointer really really hard to see under OSX with a black terminal background. I don't have this problem with the iterm2 pointer which is much "whiter". Any chance of fixing that?

**Comment by Luflosi** [comment]
This functionality was added back as an option in #985. It was disabled because of #794. To use it put `macos_custom_beam_cursor yes` into your `kitty.conf`. I don't think this is in the latest release yet and if that's true then you'll have to build from source if you want to use this option.

**Comment by kovidgoyal** [comment]
yes, it is not yet released so wait for the release or run from master in the meantime.
