### ISSUE TITLE
Micro fails to initialize a screen on Kitty

### ISSUE THREAD

**Issue by serebit** [kovidgoyal/kitty#997]
I know we went over this last night, but there's been some new developments.

I got micro to work on kitty on my desktop by uninstalling the old version of kitty and installing the newest version. However, these steps did not fix the issue on my laptop, which still gives me the following error when attempting to use micro from kitty:
```
terminal entry not found
Fatal: Micro could not initialize a screen.
```
When running kitty through another terminal to show error outputs, running micro (and, in fact, running just about any command) outputs the following:
```
[263 14:28:41.868002] [PARSE ERROR] Unknown OSC code: 777
[263 14:28:41.868916] [PARSE ERROR] Unknown OSC code: 7
```
Not sure if that's related, but it's interesting nonetheless.

**Comment by kovidgoyal** [comment]
Run infocmp and make sure it is reading the kitty terminfo. LIke this:

```
infocmp
#       Reconstructed via infocmp from file: /home/kovid/work/kitty/terminfo/x/xterm-kitty
xterm-kitty|KovIdTTY,
        am, ccc, hs, km, mc5i, mir, msgr, npc, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, dsl=\E]2;\007, ech=\E[%p1%dX,
        ed=\E[J, el=\E[K, el1=\E[1K, flash=\E[?5h$<100/>\E[?5l,
        fsl=^G, home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH,
        ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=\n,
        indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        kEND=\E[1;2F, kHOM=\E[1;2H, kLFT=\E[1;2D, kRIT=\E[1;2C,
        ka1=, ka3=, kbs=^?, kc1=, kc3=, kcbt=\E[Z, kcub1=\EOD,
        kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~, kend=\EOF,
        kf1=\EOP, kf10=\E[21~, kf11=\E[23~, kf12=\E[24~,
        kf13=\E[1;2P, kf14=\E[1;2Q, kf15=\E[1;2R, kf16=\E[1;2S,
        kf17=\E[15;2~, kf18=\E[17;2~, kf19=\E[18;2~, kf2=\EOQ,
        kf20=\E[19;2~, kf21=\E[20;2~, kf22=\E[21;2~,
        kf23=\E[23;2~, kf24=\E[24;2~, kf25=\E[1;5P, kf3=\EOR,
        kf4=\EOS, kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~,
        kf9=\E[20~, khlp=, khome=\EOH, kich1=\E[2~, kind=\E[1;2B,
        kmous=\E[M, knp=\E[6~, kpp=\E[5~, kri=\E[1;2A, kund=,
        oc=\E]104\007, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
        rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l, rmso=\E[27m,
        rmul=\E[24m, rs1=\Ec, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h, smso=\E[7m,
        smul=\E[4m, tbc=\E[3g, tsl=\E]2;, vpa=\E[%i%p1%dd,
```

if it works and micro doesn't it will be because whatever library it uses to read terminfo definitions does not support the terminfo env var. Which you can work around by copying the kitty terminfo files into /usr/share/terminfo

**Comment by serebit** [comment]
infocmp outputs correctly, and the Kitty terminfo files are already in /usr/share/terminfo. Even if I manually copy them over, the issue persists.

**Comment by kovidgoyal** [comment]
I dont know what kitty can do about it in that case, sorry. I cannot reproduce, and I know nothing of micro's internals.

**Comment by martinetd** [comment]
I installed micro just to try, and can reproduce; the issue seems to be that micro has its own terminfo-like database in addition to terminfo, and looks for xterm-kitty in this file:
https://raw.githubusercontent.com/gdamore/tcell/master/database.json

@serebit: You should open an issue over there (micro or tcell) asking them to add kitty, I guess

**Comment by serebit** [comment]
@martinetd Thanks for the input, I'll throw a suggestion their way. :+1:

**Comment by serebit** [comment]
Looks like an issue is already opened on tcell for this very problem... and has been since June. That's disheartening.

**Comment by bagobor** [comment]
@serebit please try to set
> export TERM='xterm-256color' 
before micro start
it helped me in the same situation.
