### ISSUE TITLE
Multiple Hints

### ISSUE THREAD

**Issue by melMass** [kovidgoyal/kitty#998]
Is there a way to treat the returned strings from hints when mapping to a shortcut ?

I want to be able to concatenate paths (what it does by default) with one shortcut, but also filter the input whit another one.
For instance adding spaces between returned results.

Is that possible or would require a custom hints kitten ? 

Thanks

**Comment by melMass** [comment]
Ok looking at the code it seams I need to make my own hints version.
What is the easiest way to manage external Kittens ? In the config file root ?

Thanks

**Comment by kovidgoyal** [comment]
Write your own kitten for that: see https://github.com/kovidgoyal/kitty/blob/master/docs/kittens/custom.rst
